### ISSUE TITLE
Unable to join after first join

### ISSUE THREAD

**Issue by WesleyVanNeck** [GeyserMC/Geyser#10]
has disconnected for reason CLOSED_BY_REMOTE_PEER [0m
[37;1mInsaneLegacy883 has disconnected from remote java server on address
 because of java.lang.IllegalStateException: Connection has been closed[0m

**Comment by SupremeMortal** [comment]
That's expected behaviour

**Comment by Kiana-Kaslana85** [comment]
@Kiana-Kaslana85 am unable join again then

**Comment by TechDroid2002** [comment]
@SupremeMortal I got the errors on geyser of raknet @RednedEpic

**Comment by TechDroid2002** [comment]
`aneboy1201) has connected to remote java server on address 185.239.237.166[0m
[37;1mSpawned player at 97.84381325690035 63.61960160842961 1649.9508886404542[0m
56577 [Network Listener - #1] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:173)
	com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryEncode(BedrockPacketCodec.java:75)
	com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.compressPackets(DefaultBedrockCompressionHandler.java:40)
	com.nukkitx.protocol.bedrock.BedrockSession.sendWrapped(BedrockSession.java:106)
	com.nukkitx.protocol.bedrock.BedrockSession.sendQueued(BedrockSession.java:178)
	com.nukkitx.protocol.bedrock.BedrockSession.onTick(BedrockSession.java:149)
	io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:338)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.lang.Thread.run(Thread.java:748)
[33;1mBedrock user with ip: /86.84.203.137 has disconnected for reason TIMED_OUT[0m`

**Comment by lukeeey** [comment]
Seems similar to what i showed you @SupremeMortal

**Comment by SupremeMortal** [comment]
This will be fixed in protocol lib version 2.1.3

**Comment by TechDroid2002** [comment]
Well I don't use protocollib

**Comment by TechDroid2002** [comment]
Ok am stupid he means nukkit one

**Comment by towuk118** [comment]
yes i have this problem too!

**Comment by RednedEpic** [comment]
Resolved.
