### ISSUE TITLE
Support authlib-injector

### ISSUE THREAD

**Issue by SinonGame** [GeyserMC/Geyser#1000]
**What feature do you want?**
Add support to authlib-injector, or make authlib-injector able to use
https://github.com/yushijinhun/authlib-injector/

Here's a feature compare for authlib-injector and classic offline mode
![better](https://user-images.githubusercontent.com/55188112/88271040-2bb67900-cd09-11ea-97c6-29a0f0457721.png)

**Alternatives?**
classic offline mode

**Comment by rtm516** [comment]
We have discussed this and as it would allow piracy and we don't support that, we will not be implementing this. Also this is a duplicate of https://github.com/GeyserMC/Geyser/issues/974

**Comment by DoctorMacc** [comment]
This also is something that would have to be implemented in our Java library MCProtocolLib. According to https://github.com/Steveice10/MCProtocolLib/issues/552 this is something that Steveice wishes to happen.

**Comment by Mooling0602** [comment]
> We have discussed this and as it would allow piracy and we don't support that, we will not be implementing this. Also this is a duplicate of [#974](https://github.com/GeyserMC/Geyser/issues/974)

True it would allow piracy, but it won't block players to buy the game. And in some countries, connection to Microsoft & Mojang's auth server is very unstable, self-host servers that supports authlib-injector help a lot. As Microsoft & Mojang is also still keeping offline mode, I think you developers should reconsider this.
Allowing pirated players to play the game is the fault of the server operators, not the developers.
