### ISSUE TITLE
Droppers and dispensers don't show up in the crafting book

### ISSUE THREAD

**Issue by Comstepr** [GeyserMC/Geyser#1002]
**Describe the bug**
Droppers and dispensers don't show up in the crafting book

**To Reproduce**
https://youtu.be/r_8bJ-LdH4A

**Expected behavior**
To be able to show it in the crafting book

**Screenshots / Videos**
https://youtu.be/r_8bJ-LdH4A

**Server Version**
This server is running Tuinity version git-Tuinity-"d3dc35c" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Previous version: git-Tuinity-"97aa029" (MC: 1.16.1)
You are running the latest version

**Geyser Version**
This server is running Geyser version 1.0.0 (git-master-728daaf) (Java: 1.16.1, Bedrock: 1.16.0)
Checking version, please wait...
Failed to check for updates

Forked version of Geyser, up to date with master: https://github.com/Comstepr/Geyser

**Minecraft: Bedrock Edition Version**
v1.16.0 Win10

**Additional Context**
https://dump.geysermc.org/qjeFmTiExdhGTeCyacYW1CAzdDCmcWND

**Comment by DoctorMacc** [comment]
Pistons also appear to be missing. I think this error is related to https://github.com/GeyserMC/Geyser/pull/347 ; the same items are missing.
