### ISSUE TITLE
No particles when feeding a chicken

### ISSUE THREAD

**Issue by MagnoBooter** [GeyserMC/Geyser#1005]
**Describe the bug**
When feeding a seed to a child chicken, no green particles appear, like when using bone meal on crops.
But even worse: you lose all the seeds you feed, but the chicken doesn't grow into an adult.

**To Reproduce**
1. Feed a seed to a child chicken.
2. You lose the seed, but no green particles appear, so the chicken has probably not grown at all.

**Expected behavior**
Green particles should appear. Chicken should eventually grow into an adult chicken.

**Screenshots / Videos**
-

**Server Version**
Tested on PaperMC build 111, with Geyser-Spigot plugin.

**Geyser Version**

Geyser-Spigot build 280 (git-master-b103d86)

**Minecraft: Bedrock Edition Version**
1.16.10.02

**Additional Context**
If a dump is needed, I'll be happy to provide one. Just drop me a line here.

**Comment by DoctorMacc** [comment]
If the seed is taken, then the chicken probably received it. It's more likely that we aren't sending the particles back to Bedrock.

**Comment by MagnoBooter** [comment]
Well, after feeding 40 seeds, the chicken is still a baby chicken... should be adult by then?

**Comment by DoctorMacc** [comment]
`Baby chickens take 20 minutes to grow up, but the growth time can be accelerated by 10% each time it is fed seeds. `

I just tested myself and the baby grew into an adult soon after.

**Comment by DoctorMacc** [comment]
Looks like this effect is handled by the client on Java. You can replicate this by attempting to view the effect from another Java client.
