### ISSUE TITLE
Can't walk on thick snow

### ISSUE THREAD

**Issue by lxcoo** [GeyserMC/Geyser#1008]
**Describe the bug**

Unable to walk on thick snow, the java server console report: XX moved wrongly!
**To Reproduce**

Walk to the snow
Then bounced back
**Expected behavior**

Keep moving forward
**Screenshots / Videos**

[bug.zip](https://github.com/GeyserMC/Geyser/files/4970599/bug.zip)
**Server Version**

Paper1.16.1-111
**Geyser Version**

git-master-b103d86
**Minecraft: Bedrock Edition Version**

1.16.1
**Additional Context**

**Comment by Heath123** [comment]
Will be fixed by #699

**Comment by lxcoo** [comment]
> Will be fixed by #699

Oh, thanks

**Comment by greenskype** [comment]
It seems to be the same when moving on blocks with incomplete collision boxes

**Comment by DoctorMacc** [comment]
This is now largely fixed.
