### ISSUE TITLE
Angry wolf texture not displaying!

### ISSUE THREAD

**Issue by towuk118** [GeyserMC/Geyser#1018]
**Describe the bug**

**To Reproduce**
start spigot
join world
tap to wolfs
dont change visible red eyes (angry texture animal)
and console dont show Russian text!

**Expected behavior**
not

**Screenshots / Videos**
VIDEO
https://youtu.be/AXJnE1Y0VXQ

**Server Version**
latest now

**Geyser Version**
latest now

**Minecraft: Bedrock Edition Version**
stable release 1.16+

**Additional Context**
not have

**Comment by rtm516** [comment]
Please split this issue into 2, and provide us with a dump by using `/geyser dump`

**Comment by towuk118** [comment]
> Please split this issue into 2, and provide us with a dump by using `/geyser dump`

https://dump.geysermc.org/3PvnRHUkeJHTY8ffySyHP4tq0op5Ejgl

**Comment by Heath123** [comment]
> https://dump.geysermc.org/3PvnRHUkeJHTY8ffySyHP4tq0op5Ejgl

<table>
      <tr><td colspan="3"><b><a href="https://dump.geysermc.org/sCNdQD4I0pJUNP8tRZglvgS60wdZtoMR">Geyser Spigot Dump Analysis</a></b></td></tr>
      <tr><td colspan="3"><b>Git Info</b></td></tr>
      <tr><td colspan="3"><b>Latest:</b> yes<br>
      <b>Commit:</b> <a href="https://github.com/GeyserMC/Geyser/commit/5b1116b15a19f0b98568c95de03af4d59a40082a"><code>5b1116b</code></a></td></tr>
      <tr><td><b>Platform</b></td><td><b>Remote address</b></td><td><b>Listen address</b></td></tr>
      <tr><td>Spigot</td><td>127.0.0.1:25565 (internal IP)</td><td>0.0.0.0:19132</td></tr>
      <tr><td><b>Auth type</b></td><td><b>Server version</b></td><td></td></tr>
      <tr><td>offline</td><td>git-Spigot-9639cf7-7c03d25 (MC: 1.16.1)</td><td></td></tr>
</table>

**Comment by towuk118** [comment]
> > https://dump.geysermc.org/3PvnRHUkeJHTY8ffySyHP4tq0op5Ejgl
> 
> [Geyser Spigot Dump Analysis](https://dump.geysermc.org/sCNdQD4I0pJUNP8tRZglvgS60wdZtoMR)
> Git Info
> Latest: yes
> Commit: [`5b1116b`](https://github.com/GeyserMC/Geyser/commit/5b1116b15a19f0b98568c95de03af4d59a40082a)
> Platform	Remote address	Listen address
> Spigot	127.0.0.1:25565 (internal IP)	0.0.0.0:19132
> Auth type	Server version	
> offline	git-Spigot-9639cf7-7c03d25 (MC: 1.16.1)

yes iam use local host windows
