### ISSUE TITLE
Unicode UTF-8 (RUSSIAN) dont correctly visible!

### ISSUE THREAD

**Issue by towuk118** [GeyserMC/Geyser#1019]
**Describe the bug**
in name issue

**To Reproduce**
check video

**Expected behavior**
none

**Screenshots / Videos**
https://youtu.be/pzJRJ_rOkkE

**Server Version** + **Geyser Version** + **Minecraft: Bedrock Edition Version**
https://dump.geysermc.org/nWJyN55JP1OuJ3cJoSNXvpsEh8YAhgIM | BE v1.16.10

**Additional Context**
none

**Comment by rtm516** [comment]
Without the UTF-9 flag does it work?

**Comment by rtm516** [comment]
This is caused by CMD not supporting UTF-8, if you use `chcp 1251` to allow it to support Russian characters.
