### ISSUE TITLE
Server 189.1.173.227:10111 cannot be connected to

### ISSUE THREAD

**Issue by DoctorMacc** [GeyserMC/Geyser#1023]
**Describe the bug**
This server cannot be connected to - gives a `io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused` error. I can connect fine on Java.

**Server Version**

According to McSrvStatus the server is running some form of BungeeCord.

**Geyser Version**
Build 284

**Minecraft: Bedrock Edition Version**
1.16.10.2

**Additional Context**
Relevant Geyser dump of the first reported problem: https://dump.geysermc.org/hZ7hJVe6nGOe4uN5iUY2rKkq19Vl3We0

**Comment by DoctorMacc** [comment]
The person is using BungeeGuard.

**Comment by rtm516** [comment]
This is likely conflicting with floodgates auth, it might work if floodgate doesn't forward data to the endpoint servers.

**Comment by DoctorMacc** [comment]
As this server isn't even up right now, I'm closing this issue.
