### ISSUE TITLE
Chest UI translation sometimes does not work well.

### ISSUE THREAD

**Issue by PQguanfang** [GeyserMC/Geyser#1026]
**Describe the bug**
This problem had been reported before:(https://github.com/GeyserMC/Geyser/issues/211 )and was fixed by this PR(https://github.com/GeyserMC/Geyser/pull/602) .
However,this problem reappear after Geyser updated to Minecraft 1.16 version.

**To Reproduce**
1.Download Geyser-Spigot.jar and then put it in plugins folder.
2.Start the server.
3.Prepare two chest UI page,you can do it by some menu plugins.One of which opens first,it has a item in it which can open the other chest UI page.
4.Try to open the other chest UI,but failed.
5.This problem may occur when the two chest UI have different sizes.

**Server Version**
Paper 1.16.1

**Geyser Version**
Geyser-Spigot 

**Minecraft: Bedrock Edition Version**
1.16.1

**Comment by zimzaza4** [comment]
video

**Comment by zimzaza4** [comment]
ok

**Comment by zimzaza4** [comment]
[https://cdn.discordapp.com/attachments/613169749525790737/736487391405146112/Screen_Recording_20200725-153422_Minecraft.mp4](video)

**Comment by zimzaza4** [comment]
https://cdn.discordapp.com/attachments/613169749525790737/736487391405146112/Screen_Recording_20200725-153422_Minecraft.mp4
