### ISSUE TITLE
When I walking on gathered snow, I will have position-moving that it’s uncontrolled.

### ISSUE THREAD

**Issue by DPlddP** [GeyserMC/Geyser#1030]

**Comment by PQguanfang** [comment]
The same as https://github.com/GeyserMC/Geyser/issues/1008,you can close this issue by yourself.

**Comment by DPlddP** [comment]
> The same as #1008 can close this issue by yourself.



> The same as #1008 can close this issue by yourself.



> The same as #1008 can close this issue by yourself.

ok
