### ISSUE TITLE
The inventory is not displayed when picking up dropped objects

### ISSUE THREAD

**Issue by l-ddP** [GeyserMC/Geyser#1031]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by rtm516** [comment]
> **Describe the bug**
> 
> **To Reproduce**
> 
> **Expected behavior**
> 
> **Screenshots / Videos**
> 
> **Server Version**
> 
> **Geyser Version**
> 
> **Minecraft: Bedrock Edition Version**
> 
> **Additional Context**

Please fill in the template. So we can work out what exactly you mean and work out how/why it happens.

**Comment by l-ddP** [comment]
Sorry, I already know the cause of this problem. It is due to an error in my plugin configuration, not geyser's problem. I am very sorry to the developers for my mistake.
