### ISSUE TITLE
The items in the inventory sometimes disappear

### ISSUE THREAD

**Issue by l-ddP** [GeyserMC/Geyser#1032]
**Describe the bug**
Within a period of time after entering the server, all the inventory that originally had items disappeared.

**To Reproduce**
1. join in server
2. Some time has passed (no items picked up or discarded during this time)
3. The items in the inventory disappear for no reason.

**Expected behavior**
Items in the inventory should not disappear without a reason.

**Screenshots / Videos**
Sorry, there are no screenshots/videos at the moment, I will add them later.

**Server Version**
Paper-116(1.16.1)

**Geyser Version**
git-master-5c2a225 (No Floodgate)

**Minecraft: Bedrock Edition Version**
1.16.0

**Additional Context**

**Comment by rtm516** [comment]
> **Describe the bug**
> 
> **To Reproduce**
> 
> **Expected behavior**
> 
> **Screenshots / Videos**
> 
> **Server Version**
> 
> **Geyser Version**
> 
> **Minecraft: Bedrock Edition Version**
> 
> **Additional Context**

Please fill in the template. So we can work out what exactly you mean and work out how/why it happens.

**Comment by DPlddP** [comment]
I have filled in the template, but I can't seem to see the edited effect here. If necessary, I can send a screenshot.😂

**Comment by rtm516** [comment]
> I have filled in the template, but I can't seem to see the edited effect here. If necessary, I can send a screenshot.😂

I have edited your post as you still had the comment marks round the responses, but it looks like you are still missing a dump, can you please run `/geyser dump` and add the link under `Additional Context`

**Comment by DPlddP** [comment]
I have added,thanks for your help!🥰

**Comment by DPlddP** [comment]
I can’t add the link.this link is here: https://dump.geysermc.org/lGWYUdXrEi8ptFgRRt4Pw3JQnnj3DoF7
#1031 different from this question,about #1031 I will give more information later.

**Comment by ImDaBigBoss** [comment]
This is because player UUIDs change.
Fix:
1. make your server online
2. get floodgate

**Comment by RednedEpic** [comment]
Unable to reproduce. Can you please provide a video of this happening?

**Comment by DoctorMacc** [comment]
@ImDaBigBoss what do you mean by your comment?

**Comment by RednedEpic** [comment]
Closing as we've seen no other reports of this and because of no response from OP.
