### ISSUE TITLE
Color NickName!

### ISSUE THREAD

**Issue by TOWUK** [GeyserMC/Geyser#1042]
**Describe the bug**
nickname color is not displayed (in game)
_upd: I supplement, the nickname (color) is displayed after the end of the game in another world!_ `check video`
bedrock:
![image](https://user-images.githubusercontent.com/28830162/88659103-2d9f8400-d0dd-11ea-8c66-2b188692b5c7.png)

java:
![image](https://user-images.githubusercontent.com/28830162/88659272-75bea680-d0dd-11ea-8a21-d5c69f1a7f45.png)

**To Reproduce**
just join and play bedwars (spigot)

**Expected behavior**
none

**Screenshots / Videos**
Video: https://youtu.be/YhSRxoNnIDk
upd: always red nickname from Java: https://youtu.be/RVfevEzqjJM

**/geyser version**
На этом сервере Geyser-spigot версии 1.0.0 (git-master-fe75320) (Java: 1.16.1, Bedrock: 1.16.0)

**Additional Context**
Dump: https://dump.geysermc.org/pKoVECbM9o0WiH1TNVsVhpBn6X1wmNY7

**Comment by TOWUK** [comment]
up?

**Comment by rtm516** [comment]
Could you retest in the latest version?

**Comment by TOWUK** [comment]
> 
> 
> Could you retest in the latest version?

thanks, i go to test it!)

**Comment by Chew** [comment]
Any update?

**Comment by RednedEpic** [comment]
We've rewritten our message handling lately, which hypothetically should resolve this issue. We've seen no other reports of this, so I'm going to close this issue for now. If this is still a problem, please comment here with screenshots + videos and I'll reopen the issue.
