### ISSUE TITLE
Top snow cannot be obtained.

### ISSUE THREAD

**Issue by Comstepr** [GeyserMC/Geyser#1044]
**Describe the bug**
Top snow cannot be placed.

**To Reproduce**
In creative mode, try to obtain top snow. It allows you to drag it to your hotbar but once you exit item picking, it disappears.

**Expected behavior**
N.A. Snow (block) places layers of snow instead.

**Screenshots / Videos**

**Server Version**
Tuinity git-master-d3dc55c

**Geyser Version**
git-master-b5c5e23 of my own fork
https://github.com/Comstepr/Geyser

Should be almost up to date with master, I don't see any latest commits fixing this.

**Minecraft: Bedrock Edition Version**
v1.16.0

**Additional Context**
https://dump.geysermc.org/LEn8LbjcBc6vCGgjNH0fOYmvugZhLDOc

**Comment by RednedEpic** [comment]
Can you please confirm if this issue is a problem on the latest _master_ branch of Geyser? We only accept reports for official versions of the software.

**Comment by Comstepr** [comment]
I am unable to confirm that then, I only use my own fork. Note that my own fork does not modify anything to do with block placements/inventories, it is almost up to date with master.

**Comment by rtm516** [comment]
Confirmed this is an issue, likely just a mappings issue.

**Comment by Comstepr** [comment]
Thank you for taking a look at my issue!
