### ISSUE TITLE
Enchantment Table does not work

### ISSUE THREAD

**Issue by ipad54** [GeyserMC/Geyser#1045]
**Describe the bug**
Enchantment Table does not work 

**To Reproduce**
1. Place Enchantment Table
2. Click on '.Enchantment Table' -->

**Expected behavior**

**Screenshots / Videos**

**Server Version**

This server is running Paper version git-Paper-111

**Geyser Version**

1.0.0

**Minecraft: Bedrock Edition Version**

1.16.1

**Additional Context**

**Comment by DoctorMacc** [comment]
This should be fixed in our inventory rewrite.

**Comment by RednedEpic** [comment]
This is already mentioned in our README as an unimplemented feature which as stated above is coming in our inventory rewrite. Closing.
