### ISSUE TITLE
Structure blocks

### ISSUE THREAD

**Issue by EasyClifton** [GeyserMC/Geyser#1056]
**What feature do you want?**
It would be nice to have structure blocks implemented someday. They are a pretty cool thing, because if you ever use one, you can't stop.
Structure blocks are a little different on java and bedrock, but maybe some features from Java could be implemented in another way in bedrock.
**Alternatives?**
World Edit, maybe, but sometimes its not suitable.

**Comment by ImDaBigBoss** [comment]
Structure blocks is the same problem as command blocks, you will have o be OP on bedrock (pause menu) to be able to use them. I believe that adding the bedrock permissions would make a mess if you tried to put a player into custom permissions as Java does not support it. (nor visitor for that matter)

**Comment by EasyClifton** [comment]
I know that and should've specified it here.

**Comment by ImDaBigBoss** [comment]
If the devs think it's a good idea, maybe I could try looking into implementing this? I'm not saying I'll manage easily or at all but it's worth a try. I'll only dive into it if the devs think it's ok to to it tho...

**Comment by DoctorMacc** [comment]
Feel free to give it a shot! No one else is working on it as far as I know.

**Comment by ImDaBigBoss** [comment]
Ok I'll see what I can do...

**Comment by RednedEpic** [comment]
Structure blocks are mentioned as unimplemented in the README, so I'm going to close this.

**Comment by EasyClifton** [comment]
Yes, because I added them :)

**Comment by Heath123** [comment]
Shouldn't the issue still stay open?

**Comment by Heath123** [comment]
Because it isn't fixed, you can't add that to the todo, people might make duplicates if they're only searching for open issues (I've done that a few times) etc.
