### ISSUE TITLE
IP Binding

### ISSUE THREAD

**Issue by ds2600** [GeyserMC/Geyser#107]
**What feature do you want?**
On startup or in properties, ability to set one OR MORE IPs to bind to. For instance, my server will have 4 NICs, I would like to set the server to bind to either 1 specific NIC or multiple NICs to reach across different networks.

**Alternatives?**
Any alternatives you have tryed

**Comment by RednedEpic** [comment]
> **What feature do you want?**
> On startup or in properties, ability to set one OR MORE IPs to bind to. For instance, my server will have 4 NICs, I would like to set the server to bind to either 1 specific NIC or multiple NICs to reach across different networks.
> 
> **Alternatives?**
> Any alternatives you have tryed

Could you please elaborate a bit more? You're able to specify which server you want to use with Geyser using [the remote address](https://github.com/GeyserMC/Geyser/blob/master/connector/src/main/resources/config.yml#L20) option in the config.yml.

**Comment by ds2600** [comment]
I apologize. I hadn't seen any documentation stating that during setup. Thank you.

**Comment by 90257550** [comment]
So can you teach me how to do it? I may have the same problem. Thank you.
![Screenshot_2024-05-08-00-18-09-401_com microsoft rdc androidx](https://github.com/GeyserMC/Geyser/assets/120694559/d3188cff-4fe5-4309-9cdc-42fc22c9da15)

**Comment by 90257550** [comment]
So can you teach me how to fill it out? I need help. Thank you.
![Uploading Screenshot_2024-05-08-00-18-09-401_com.microsoft.rdc.androidx.jpg…]()

**Comment by Konicai** [comment]
Reach out to us on Discord for help please, this issue is closed and likely unrelated

**Comment by 90257550** [comment]
> 请在 Discord 上与我们联系寻求帮助，此问题已关闭且可能无关
Okay, thank you.
