### ISSUE TITLE
Tp camera rotation

### ISSUE THREAD

**Issue by Dycool** [GeyserMC/Geyser#1070]
**Describe the bug**
Rotation is ignored when a player is teleported.

**To Reproduce**
1. use spigot 1.10.2
2. use viaversion and geyser plugins
3. I used the map called "asleep 2" which I know at the start it dont lets you control the camera in java edition.

**Expected behavior**
You should be able to rotate the camera while your on that cutscene when you first go to sleep. On the java edition, you should not be able to rotate the camera.

**Server Version**
1.10.2

**Geyser Version**
(git-4dc5d28c48bee19cc322e067745cd11e0283bb64-4dc5d28) (Java: 1.16.1, Bedrock: 1.16.0)

**Minecraft: Bedrock Edition Version**
bedrock version: 1.16.1

**Additional Context**
https://dump.geysermc.org/6DJQpK9Od8ryYg4yi7c7kzBa9tJCNNks

**Comment by Heath123** [comment]
This is because small teleported are ignored and it will be fixed in #699. There might be a better way to fix this in the short term though.

**Comment by DoctorMacc** [comment]
This should now be fixed.
