### ISSUE TITLE
Bedrock players get stuck on "Building terrain" When switching server or world

### ISSUE THREAD

**Issue by partridge420x** [GeyserMC/Geyser#1072]
**Describe the bug**
When players switch server via /server, When admins /send (player) (server), or switching worlds. Happens more often with switching servers. Does not happen 100% of the time, i would say around a 40% chance of happening

**To Reproduce**
Join with bedrock client. Switch servers, or die in the nether (happens more often with switching bungeecord servers)
**Expected behavior**
Player is able to switch servers seamlessly

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/26298829/89104772-cee24f00-d3e9-11ea-8b81-8591d27a2f83.png)

**Server Version**
Paper version git-Paper-129 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

running Geyser version 1.0.0 (git-master-7fc14d8) (Java: 1.16.1, Bedrock: 1.16.0)

**Minecraft: Bedrock Edition Version**
Mcpe 1.16.1

**Additional Context**
https://dump.geysermc.org/knMgfrz0doGrIJcsbwpzydWtwOn7TICc

**Comment by DoctorMacc** [comment]
I'm not familiar with the BungeeCord plugin landscape; do any of your plugins modify how players are transferred between servers?

**Comment by partridge420x** [comment]
Not spesifically no. It uses the bungee api to move players i believe

**Comment by partridge420x** [comment]
Jpremium's author said it was something to do with the user's prefix. Needs to be disabled

**Comment by partridge420x** [comment]
Disabling the bedrock player's prefix worked, Though bedrock players still need to register and login using JPremium. When all Bedrock players are technically authenticated through geyser via mojangs api

**Comment by DoctorMacc** [comment]
So the Building Terrain issue happens for you because of JPremium?

**Comment by partridge420x** [comment]
That was my bad. Wrong issue
https://github.com/GeyserMC/Floodgate/issues/53

**Comment by partridge420x** [comment]
i have 2 going at once so i accidentally lost track

**Comment by partridge420x** [comment]
This happens when they attempt to switch servers. Or get /sent to a server

**Comment by partridge420x** [comment]
though it very happens when dying in the nether. I had to use /spawn (playername) and kill their fake player for it to start working again

**Comment by DoctorMacc** [comment]
No need to spam the issues! Either edit your comment or just put everything into one message.
