### ISSUE TITLE
Fishing rods show incorrect durability on Bedrock Edition

### ISSUE THREAD

**Issue by ChickenSaysBak** [GeyserMC/Geyser#1078]
**Describe the bug**
Fishing rods show significantly higher durability on Bedrock Edition than on Java Edition. This applies to all rods whether or not they have the Unbreaking enchantment.

**To Reproduce**
1. Get a fishing rod.
2. Use it some.
3. Compare the durability values across editions.

**Expected behavior**
I expected the durability bars to match.

**Screenshots / Videos**
[Equal Durability Test](https://i.imgur.com/4H8Uehy.png)
[Mixed Durability Test](https://i.imgur.com/rAkyZ7S.png)

**Server Version**
This server is running Waterfall version git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:3c6c0a2:365 by md_5
This server is running Paper version git-Paper-100 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.0.0 (git-master-07f3d45) (Java: 1.16.1, Bedrock: 1.16.0)
(Bungee Plugin)

**Minecraft: Bedrock Edition Version**
1.16.10

**Additional Context**
This was tested on both a 1.12.2 server and 1.16.1 server. I have tried other tools/armor and have found that only fishing rods display inaccurately.
https://dump.geysermc.org/XopObF4GfMZ1dhfs3e4Ev1mEWhA1X5Hp

**Comment by DoctorMacc** [comment]
Looking into this further, this seems to be a Bedrock client bug as I was able to replicate this on a vanilla Bedrock issue. Therefore I am closing.
