### ISSUE TITLE
Cant connect from phone

### ISSUE THREAD

**Issue by TheArrowGuy1241** [GeyserMC/Geyser#1082]
**Describe the bug**
When I run geyser it works,but when I go to play on my phone it shows there are no local servers. I tried to add a server with 0.0.0.0 as the ip,I tried putting localhost,my ip and my public ip. None of those worked.

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by DoctorMacc** [comment]
Hello! As this is likely a connection issue, please join us on our Discord for assistance.
