### ISSUE TITLE
PS4 Players crash with certain firework effects.

### ISSUE THREAD

**Issue by Zoxplers** [GeyserMC/Geyser#1083]
**Describe the bug**
Fireworks with the trail effect crash ps4 players

**To Reproduce**
Create a firework with the trail effect

**Expected behavior**
PS4 players shouldn't crash

**Server Version**
Paper version git-Paper-130 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.0.0 (git-master-86f18c9) (Java: 1.16.1, Bedrock: 1.16.0)

**Minecraft: Bedrock Edition Version**
PS4 Bedrock 1.16.0

**Additional Context**
Twinkle effect not tested, ps4 players got mad.

**Comment by DoctorMacc** [comment]
Any errors in console?

**Comment by DoctorMacc** [comment]
I was unable to confirm this on Android; however, I don't have access to a PS4. If there are any server logs that would be amazingly helpful, and a Geyser dump would also be great.

**Comment by Trains77** [comment]
I can confirm that on my PS4  minecraft does sometimes crash with the firework effects

**Comment by DoctorMacc** [comment]
@Trains77 any errors in console for you?

**Comment by DoctorMacc** [comment]
Closing, as this is a client bug: https://bugs.mojang.com/browse/MCPE-92503
