### ISSUE TITLE
How do I Disable "Login to Your Minecraft Account"?

### ISSUE THREAD

**Issue by AlexDev404** [GeyserMC/Geyser#1085]
Hi. I would like to know how to disable the login screen whenever you join the Java server (with Geyser installed) using a Bedrock client. As some of the people who are connecting to this Java server do not have a Java account, or rather, some don't have any Minecraft account at all; I figure that instead of patching the server with Floodgate or something similar it is best that I just disable the login screen altogether. I am aware that in your predecessor software "Geyser", this was not an issue as all. How do I do this with Geyser?

**Comment by rtm516** [comment]
Use Floodgate, please see https://github.com/GeyserMC/Geyser/wiki/Floodgate
If you have any further questions please join our discord @ https://discord.geysermc.org/

**Comment by SacriPudding** [comment]
If you are not wishing to use floodgate the only option is an offline mode server which would mean neither side needs a legit account. This is generally unsafe as people can easily sign in as other people.

**Comment by AlexDev404** [comment]
I have already done this, but it is not working.

**Comment by rtm516** [comment]
Please join our discord https://discord.geysermc.org/

**Comment by AlexDev404** [comment]
> Please join our discord https://discord.geysermc.org/

What do I do now?

**Comment by Heath123** [comment]
Floodgate isn't a replacement for Geyser, it adds something to the server so you don't have to log in

**Comment by JezzDaBezz** [comment]
I have the same problem, when I enable offline it says "login failed: invalid login session" when I log in to my server

**Comment by Heath123** [comment]
@JezzDaBezz If you want to use offline mode you also have to set your server to offline mode

**Comment by NijremNL** [comment]
Is it possible to setup that you do have to login bult juist once not everytime that you join?

**Comment by onebeastchris** [comment]
@NijremNL 
You can add saved user logins in the Geyser config, that would effectively act this way
