### ISSUE TITLE
Grindstone does not work

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Geyser#1087]
Grindstone does not work

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

Spigot1.16.1

**Geyser Version**

**Minecraft: Bedrock Edition Version**

1.16.1

**Additional Context**

**Comment by DoctorMacc** [comment]
Please fill in the issue template next time.

This should be fixed in our inventory rewrite.

**Comment by ExDrill** [comment]
Wow that was a quick response! I'm glad to see Geyser improving! :D

**Comment by RCTarzan** [comment]
Running a Paper 1.16.5 Server with Windows 10 Edition 1.16.201, and while I can mine and place the grindstone, no matter what I do I cannot open the GUI

**Comment by D3ATHBRINGER13** [comment]
This is known see the TODO list
