### ISSUE TITLE
Book & Quill doesn't work

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Geyser#1088]
**Describe the bug**

Unable to write on a Book

**To Reproduce**

1.write
![Screenshot_20200805_085958_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/89360490-330f5680-d6fb-11ea-9092-462a2519c7ee.jpg)

2. Click on Sign

3.Sign and close
![Screenshot_20200805_090005_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/89360577-74a00180-d6fb-11ea-9d0b-8581fac32c55.jpg)

4.Text becomes null
![Screenshot_20200805_090009_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/89360599-87b2d180-d6fb-11ea-98b2-2f6a07cb37c6.jpg)

**Server Version**

Spigot1.16

**Geyser Version**

![IMG20200805091254](https://user-images.githubusercontent.com/53421735/89360721-e5dfb480-d6fb-11ea-9f0b-084de79ee8b8.jpg)

**Minecraft: Bedrock Edition Version**

1.16.1

**Comment by diamond-gold** [comment]
Its working fine for me on Spigot 1.15.2 Geyser build 309

**Comment by rtm516** [comment]
This is not merged so it should stay open and let it close automatically

**Comment by Paril** [comment]
Still broken on 1.16.4 builds.

**Comment by DoctorMacc** [comment]
This will be fixed soon.

**Comment by NathanWolf** [comment]
Hello, I am sorry to bother but I was wondering if there are still issues with the PR fix for this, or plans to merge it?
Thank you!

**Comment by Camotoy** [comment]
Creative might accidentally work, but I would not expect the issue to be totally resolved.

Regardless, the PR will be merged soon.

**Comment by NathanWolf** [comment]
Ah yes thank you! I got confused, it worked when I tested locally but on my server. Creative mode was the difference. 
Great to hear it!
