### ISSUE TITLE
[Feature] server-icon.png support

### ISSUE THREAD

**Issue by towuk118** [GeyserMC/Geyser#1091]
just support icon like java menu servers:
(i am use [astral client](https://astralclient.net/download.html) for bedrock v 6.1) 
Java:
![image](https://user-images.githubusercontent.com/28830162/89476413-42da7980-d793-11ea-9f81-21bfa96244fc.png)

Bedrock:
![image](https://user-images.githubusercontent.com/28830162/89476322-17f02580-d793-11ea-8c1a-2ac1f09bf6ca.png)

**Comment by DoctorMacc** [comment]
Hello! As far as we know, there is no way to support server icons on Bedrock. I see you are using a special client; if there is a way to support server icons for them please give us an API reference and we will reopen.

**Comment by towuk118** [comment]
> Hello! As far as we know, there is no way to support server icons on Bedrock. I see you are using a special client; if there is a way to support server icons for them please give us an API reference and we will reopen.

i say it from discord astral (https://discord.gg/bnBqWzS) - link astral client

**Comment by DoctorMacc** [comment]
`MCBE by default do not support server icons for 3rd party servers so we can't do anything about that :(` according to the Astral Client Discord.
