### ISSUE TITLE
Mojang Skin system not worked [online mode all configs]

### ISSUE THREAD

**Issue by TOWUK** [GeyserMC/Geyser#1092]
**Describe the bug**
just set online mode true in all server configs
check video (advanced)
**Expected behavior**
ESBE 2G shaders, ASTRAL client - Bedrock

**Screenshots / Videos**
https://youtu.be/YN5tr0vd_co

**Server Version**
dump

**Geyser Version**
dump

**Minecraft: Bedrock Edition Version**
1.16.1+ win10

**Additional Context**
https://dump.geysermc.org/FcKbCHaBH0G68bio9wpS21vIzxzSNoha

**Comment by towuk118** [comment]
log: spawning after skin set???
[latest.log](https://github.com/GeyserMC/Geyser/files/5031919/latest.log)

**Comment by rtm516** [comment]
Likely caused by skin restorer, please see https://github.com/GeyserMC/Geyser/pull/680

**Comment by towuk118** [comment]
> Likely caused by skin restorer, please see #680

I found this error before installing skinsrestorer, and then installed It as well...

**Comment by towuk118** [comment]
UPD: skins turned out to be fixed by removing viarevind and viaversion

**Comment by DoctorMacc** [comment]
Can you confirm if this is fixed in the latest build?

**Comment by DoctorMacc** [comment]
Closing as there is no response and we've had several skin updates. Please reopen if this still occurs.
