### ISSUE TITLE
If a player on join moves from the End to Overworld really fast, sky glitches out to void.

### ISSUE THREAD

**Issue by yashendra2797** [GeyserMC/Geyser#1093]
I was asked by rtm516 on the Discord to submit this as an issue.

**Describe the bug**
Sometimes when a player logs in, if the player passes through The End, Minecraft Bedrock glitches out and thinks its "the End dimension with an overworld biome ID." (-Camotoy)

**To Reproduce**
Once in a while when I login to my server this happens. Server config is Bungee>Queue Server>Hub. The Queue and Hub are 2 separate servers. When a player logs in, assuming the hub has free slots, the Queue server waits 6000 ms, and then sends the player to the Hub. Everyone, no matter what goes through the Queue server. This excludes Admins.

Rejoining fixes this issue.

**Expected behavior**
Overworld Biomes should have Overworld Skies

**Screenshots / Videos**

![](https://cdn.discordapp.com/attachments/613169789900161035/740740635467972679/unknown.png)

**Server Version**
Bungeecord: `Waterfall version git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:8afc4e2:366 by md_5`
Queue and Hub Server: `Paper-130 (MC: 1.16.1)`

**Geyser Version**
Geyser version 1.0.0 (git-master-dea9329) (Java: 1.16.1, Bedrock: 1.16.0), on Bungeecord

**Minecraft: Bedrock Edition Version**
v1.16.0

**Additional Context**
Geyser Dump: https://dump.geysermc.org/a1hjCQJz81xxitBvSgwyD2qya4tfuquI
Possibly conflicting Queue Plugin: https://www.spigotmc.org/resources/leeesbungeequeue.74615/
Queue Plugin's config.yml: https://hastebin.com/ruqufumaja.yaml
Queue Server's Plugin's config.yml: https://hastebin.com/ixafujojij.yaml

Please let me know if I can help in any way. Thank you!

**Comment by RednedEpic** [comment]
Does this still occur?

**Comment by yashendra2797** [comment]
Hmmm. I haven't tested this in forever. These last few months have been... bad for me.

Let me run a few tests, and maybe y'all can close this in a week? Thoughts?

**Comment by Camotoy** [comment]
That would be lovely, but no pressure!

**Comment by RednedEpic** [comment]
Has been fixed with some recent changes, but seems we forgot to close this issue. Thanks for the report!

**Comment by Camotoy** [comment]
(Or, if it hasn't been fixed, it's been a year since any update here, we've heard no other report of it and we've changed enough code to make this possibly obsolete)
