### ISSUE TITLE
I hope to be able to support both genuine Java and Blessing Skin 

### ISSUE THREAD

**Issue by KelaLeaf** [GeyserMC/Geyser#1095]
**What feature do you want?**
I hope to be able to support both genuine Java and Blessing Skin ("https://github.com/bs-community/blessing-skin-server" This program uses Yggdrasil API to log in) to log in to the game.

**Alternatives?**
I am currently using authlib-injector (https://github.com/yushijinhun/authlib-injector) with YggdrasilMojangProxy (https://github.com/Karlatemp/YggdrasilMojangProxy) to ensure that the server can support both genuine Java and Yggdrasil API to log in to the game at the same time. But now I have a problem. Both the genuine Java client and Yggdrasil API can log in, but the BE version only supports Yggdrasil API to log in to the game, and logging in with a genuine Java account will display "You must have a genuine Java account". If there are multiple roles in Blessing Skin, "Authentication failed" will be displayed,which may require a Yggdrasil API role selection function.

**Comment by KelaLeaf** [comment]
YggdrasilOfficialProxy (https://github.com/Karlatemp/YggdrasilOfficialProxy) replaces YggdrasilMojangProxy, because I will not use YggdrasilOfficialProxy. So my server still uses the original YggdrasilMojangProxy

**Comment by SinonGame** [comment]
Geyser won't support authlib-injector, they've said about it multi times

**Comment by RednedEpic** [comment]
Authlib injector is something that MCProtocoLib (the java protocol library we use) would need to implement (See Steveice10/MCProtocolLib#552). Until then, there isn't much we can do here.
