### ISSUE TITLE
Request to add account mapping in offline mode

### ISSUE THREAD

**Issue by MyBlueHorizon** [GeyserMC/Geyser#1096]
**What feature do you want?**
Account mapping between Bedrock Edition and Java Edition in offline mode
If my Bedrock Edition username is 123 456, I hope it can provide a way to convert it to Java Edition username 123_456, or something else. It would be better if a specific UUID can be assigned
**Alternatives?**
Nothing

**Comment by DoctorMacc** [comment]
This functionality can largely be found in [Floodgate](https://github.com/GeyserMC/Floodgate/).

**Comment by MyBlueHorizon** [comment]
Floodgate can only be installed as a plugin on Spigot (including Paper and forks), Bungeecord, and Velocity, and can only be utilized on servers that have it installed.
I hope have a way in Vanilla Server to add account mapping and work in offline mode server

**Comment by Heath123** [comment]
> Floodgate can only be installed as a plugin on Spigot (including Paper and forks), Bungeecord, and Velocity, and can only be utilized on servers that have it installed.
> I hope have a way in Vanilla Server to add account mapping and work in offline mode server

Use BungeeCord in front of the vanilla server and get Floodgate there

**Comment by MyBlueHorizon** [comment]
But this still requires a Mojang account in the offline mode server.

**Comment by MyBlueHorizon** [comment]
If only in offline server,I think Geyser should do it.

**Comment by DoctorMacc** [comment]
A workaround could be to set the Geyser instance to online mode so users could set any name they want to.

Otherwise, Geyser itself will likely not implement this but it will be possible with the upcoming API.

**Comment by MyBlueHorizon** [comment]
I set Geyser to online,but it need users have a Java Edition Mojang account.
I mean is to allow Java Edition players without a Mojang account to log in to the offline mode server using the Java Edition ID (with "_" and without " ")

**Comment by MyBlueHorizon** [comment]
If it can't be achieved through account mapping on the server, can it be like a login page and provide an input box in offline mode for players to enter the ID they want to use?

**Comment by DoctorMacc** [comment]
No, on that page you should be able to enter any username in the email and a blank password and it should work.

**Comment by MyBlueHorizon** [comment]
Thanks,It is working.

**Comment by Heath123** [comment]
> But this still requires a Mojang account in the offline mode server.

Bungee cord can work in offline mode
