### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by klokwert** [GeyserMC/Geyser#1099]
**Describe the bug**
I got banned on hypixel because "I was flyhacking" but i only use this proxy and that's all.

**To Reproduce**
1. set ip in config to play.hypixel.net
2. move a little bit around for about 10 secs
3. **BOOM!**, banned

**Expected behavior**
I expected a working proxy that wouldn't ban my main hypixel account (forever)

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/49615248/89707566-8d185200-d96f-11ea-995f-c5f1fd68f04d.png)

**Server Version**
idk, i can't i'm banned

**Geyser Version**
version 1.0.0 (git-master-d49856c) (Java: 1.16.1, Bedrock: 1.16.0)

**Minecraft: Bedrock Edition Version**
v1.16.10

**Comment by TheMasterBlaster** [comment]
Known "issue", Bedrock doesn't have the same movement as Java

**Comment by rtm516** [comment]
We do give disclaimers and warn not to use this in 'production' environments (EG hypixel) and movement is a known issue. So I will close this as there is nothing we can do.
