### ISSUE TITLE
Bedrock plate material

### ISSUE THREAD

**Issue by StarYunmeng** [GeyserMC/Geyser#1101]
I want to send different material packages to the computer version and the bedrock version

**Comment by Heath123** [comment]
Firstly, please fill in the issue template. Secondly, what does "material packages" mean? Resource packs?

**Comment by StarYunmeng** [comment]
Resource packs

**Comment by StarYunmeng** [comment]
I want to send resource packs to my mobile phone

**Comment by RednedEpic** [comment]
Duplicate of #210. Currently working on this in #1076.

**Comment by Heath123** [comment]
(sort of) duplicate of #210, and you can already do this with the resources branch

**Comment by Heath123** [comment]
This technically isn't a direct duplicate, because #210 is about passing through the Java resource pack
