### ISSUE TITLE
Bedrock player skins are the same between players

### ISSUE THREAD

**Issue by Arcratist** [GeyserMC/Geyser#1106]
**Screenshots / Videos**
https://i.imgur.com/DGC2mG9.png

**Server Version**
1.16.1 paper build 131

**Geyser Version**
Geyser version 1.0.0 (git-master-3ef7e30) (Java: 1.16.1, Bedrock: 1.16.0) and floodgate

**Minecraft: Bedrock Edition Version**
1.16.10

**Additional Context**
https://dump.geysermc.org/5YyjsRiBJ5ks0NM4MvCjwZ9nDKNqyrl7

**Comment by DoctorMacc** [comment]
Fixed with #1131.
