### ISSUE TITLE
Particle effects are inconsistent 

### ISSUE THREAD

**Issue by Arcratist** [GeyserMC/Geyser#1107]
Screenshots / Videos
https://i.imgur.com/KZ97ldl.png

Server Version
1.16.1 paper build 131

Geyser Version
Geyser version 1.0.0 (git-master-3ef7e30) (Java: 1.16.1, Bedrock: 1.16.0) and floodgate

Minecraft: Bedrock Edition Version
1.16.10

Additional Context
https://dump.geysermc.org/5YyjsRiBJ5ks0NM4MvCjwZ9nDKNqyrl7

The plugin is Custom JumpPads (https://www.spigotmc.org/resources/custom-jumppads-1-8-1-16.44876/) and I am unsure of the particles they are using

**Comment by Arcratist** [comment]
The issue has been swiftly solved.

**Comment by rtm516** [comment]
Leaving this open until the PR is merged then it will autoclose
