### ISSUE TITLE
Spigot: Enabling MOTD passthrough does not allow Bedrock clients to see/connect to the server

### ISSUE THREAD

**Issue by LightningXCE** [GeyserMC/Geyser#1111]
When enabling MOTD passthrough with the following string,

`Wither we wanted it or not, we've stepped into a war with the Cabal on Mars. So let's get to taking out their command, one by one. Valus Ta'aurc. From what I can gather he commands the Siege Dancers from an Imperial Land Tank outside of Rubicon. He's well protected, but with the right team, we can punch through those defenses, take this beast out, and break their grip on Freehold.`, bedrock clients are unable to connect. 

**To Reproduce**

1. Set MOTD to the string above
2. Enable MOTD passthrough
3. Connection fails.

Disabling passthrough allows the server to communicate properly with Bedrock clients.

**Expected behavior**
 Being able to connect

**Server Version**
Paper version git-Paper-110 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Geyser version 1.0.0 (git-master-3ef7e30)

**Minecraft: Bedrock Edition Version**
1.16.0/1 Android and Switch

**Additional Context**
Dump:
https://dump.geysermc.org/atFiqJhraKRUlUjeYZPgoPNWFw2VI7RG

**Comment by rtm516** [comment]
Likely a client limitation we can probs just trim the string to be shorter in Geyser. Why do you have a motd that long anyway? Not even java will display the full thing.

**Comment by LightningXCE** [comment]
Heh. The full message is a copy-paste meme from another game, and a few services we use let you see the full message haha.

Still good to catch! Glad it could be semi-useful information.
