### ISSUE TITLE
[Suggestion] Add compatibility to ItemsAdder custom items plugin

### ISSUE THREAD

**Issue by LoneDev6** [GeyserMC/Geyser#1114]
**What feature do you want?**
Collaborate to add compatibility to [ItemsAdder](https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-itemsadder%E2%9C%A8textures-3d-models-huds-gui-emojis-ores-blocks-wings-tails-hats.73355/)

https://github.com/LoneDev6/ItemsAdder/issues/206

**Alternatives?**
Provide me documentation on how to use Bedrock resourcepack features to emulate custommodeldata and other NBT stuff.

**Comment by Heath123** [comment]
It might start working by itself with the resources branch, but probably not because Bedrock doesn't have CustomModelData...

**Comment by rtm516** [comment]
This will likely be possible when the plugin API is merged, and when that is we can add a simple call to register custom items since bedrock allows for that then build and send the resource pack. Feel free to jump over to the discord server and we can talk some more https://discord.geysermc.org/

**Comment by LoneDev6** [comment]
I think that a wrapper/converter must be coded because bedrock resourcepacks have a different structure and luckly don't use CustomModelData but a real items declaration with namespaced ids, no hacky way.

I don't think NBT data is really needed as it would be handled by the Spigot server, client doesn't need to care about this data.

So surely I'd need to get a proper doc on how to declare these namespaced items in the pack, so I can code the converter by myself and send the correct pack.zip file to the client if their brand is "Geyser"

**Comment by rtm516** [comment]
Bedrock resource packs are quite strange and limited.
Some links for the geyser support and the wiki page with a slight bit of info. Feel free to @ me on the discord in the #development channel.
https://github.com/GeyserMC/Geyser/pull/1076 https://github.com/GeyserMC/Geyser/pull/742 https://minecraft.gamepedia.com/Tutorials/Creating_resource_pack_add-ons

**Comment by RednedEpic** [comment]
Closing this as this more or less falls under general resource pack support/conversion from java packs which #210 already covers. #1076 currently adds support for resource packs directly in the native bedrock resource pack format, and likely any conversion code we add in the future to convert packs from one version to another will also still allow for bedrock-exclusive features or changes in resource packs to be used.

**Comment by DoctorMacc** [comment]
If there are any resources/guides for how custom items are generally implemented with resource packs, feel free to reach out to us!

**Comment by CitizenPrayer** [comment]
I made quite a big stink about this in the discord, and wanted to make sure I put my voice on this thread as a show of support (another number to the list of users wanting this resolved). Thank you for all the hard work you guys have put into this.

**Comment by Camotoy** [comment]
Do note that CustomModelData support is being worked on under PR #2822. Once it is merged, we won't directly have ItemsAdder support, but the infrastructure and documentation will be available for users to map CustomModelData items to Bedrock, or for plugins such as ItemsAdder to utilize the API. For further resource pack discussion, please use issue #210.
