### ISSUE TITLE
Floodgate and online support together

### ISSUE THREAD

**Issue by ClientKitty** [GeyserMC/Geyser#1116]
**What feature do you want?**
What if you could set something in the config to set it to run with online and floodgate? When you join on the bedrock client you could select to play on a bedrock account through floodgate or sign into your java account.

**Alternatives?**
I tried setting up 2 proxy's one being online and one being floodgate on separate ports but it's super unconventional.

**Comment by DoctorMacc** [comment]
Floodgate has account linking that likely achieves what you want.

**Comment by ClientKitty** [comment]
@DoctorMacc How do I link the accounts with floodgate?

**Comment by DoctorMacc** [comment]
Enable it in the Floodgate config. If it's not there, regenerate your config.

**Comment by ClientKitty** [comment]
Ok, Thanks!

**Comment by toinouH** [comment]
If you have a Java account but not a Bedrock one can you connect to the server anyways ?
