### ISSUE TITLE
Sticks don't stack properly in inventory.

### ISSUE THREAD

**Issue by JeriRyu** [GeyserMC/Geyser#1120]
**Describe the bug**

Sticks don't stack properly inventory and don't work in crafting table. 

**To Reproduce**

In Creative Mode:
1. Go to inventory and take 64 sticks.

2. Put the sticks in the crafting table.
![IMG_1359](https://user-images.githubusercontent.com/40090923/89889618-87876a00-dc04-11ea-9dd1-cbd21a5ef34b.PNG)

3. Long press the sticks and try dragging some to any other block of crafting table inventory. Now you will see the number mark of selected sticks become yellow and cannot be placed anywhere in the inventory.
![IMG_1362](https://user-images.githubusercontent.com/40090923/89890620-3d9f8380-dc06-11ea-9c14-e5002ae24924.PNG)

4. When you close the crafting table interface, all the sticks drop out. And when the player collects them, they are stored separately in the inventory, without any stack.
![IMG_1361](https://user-images.githubusercontent.com/40090923/89890804-8ce5b400-dc06-11ea-9410-d20039e323a3.PNG)

5. By the way, if you try to craft any kind of tools that need sticks, it is not able to get the final result(e.g. diamond pickaxe) by pressing it. The item seems "stuck" in the crafting UI. 

**Expected behavior**

Just like any normal crafting, when you long-press and drag things here and there, it should work fine.

**Screenshots / Videos**

Attached above.

**Server Version**

Paper version git-Paper-134 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**

Geyser version 1.0.0 (git-master-3ef7e30) (Java: 1.16.1, Bedrock: 1.16.0)

**Minecraft: Bedrock Edition Version**

Minecraft Bedrock v1.16.10

**Additional Context**

**Comment by DoctorMacc** [comment]
Well then.

Is it just sticks?

**Comment by JeriRyu** [comment]
> Well then.
> 
> Does this just happen with sticks?

By far, Yes. I am doing further tests.

**Comment by bundabrg** [comment]
Inventory packet issue. Looks like it's leaving it in the cursor.

**Comment by DoctorMacc** [comment]
Is this still an issue?

**Comment by Chew** [comment]
No response in 7 months. This might've been resolved by the inventory rewrite, or other things since then. If you happen to still experience this issue, we encourage you to go ahead and open a new issue. Regardless, thank you for the report!
