### ISSUE TITLE
Spigot: Crash from bedrock-client-side whe u using "/lay"

### ISSUE THREAD

**Issue by KotoHacker** [GeyserMC/Geyser#1121]
**Describe the bug**
Game was crashing when u use "/lay" command from bedrock.

**To Reproduce**
1. Download latest build of [PosePlugin](https://www.spigotmc.org/resources/poseplugin-choose-your-favorite-pose.76990/) on your server.
2. Join into the server
3. Send command /lay
4. See this bug.

**Expected behavior**
The character had to lie down on the surface on which he is.

**Server Version**
1.16.1. Spigot Latest.

**Geyser Version**
Geyser build #318 [BungeeCord]

**Minecraft: Bedrock Edition Version**
1.16.1

**Additional Context**
dump: https://dump.geysermc.org/3WXd07zptvC8CffP7XHLnOKI1FUXkKOG

**Comment by towuk118** [comment]
ok
