### ISSUE TITLE
An error is reported when connecting to the server

### ISSUE THREAD

**Issue by MingxuanGame** [GeyserMC/Geyser#1122]
The bedrock version cannot connect to the java server

I can use the MC of Java to enter

When the bedrock version is connected, the server console will report an error and the bedrock version will be stuck in the loading interface

This is true for both the use of spot and individual cores

(the uploaded attachment is log, * is IP mask)
[latest.log](https://github.com/GeyserMC/Geyser/files/5057456/latest.log)

**Comment by MingxuanGame** [comment]
Remarks: Chinese

**Comment by rtm516** [comment]
Please see https://github.com/GeyserMC/Geyser/wiki/Common-Issues#javalangassertionerror-expected-aes-to-be-available-when-a-user-tries-to-connect and for any further issues join our discord @ https://discord.geysermc.org/

**Comment by MingxuanGame** [comment]
> Please see https://github.com/GeyserMC/Geyser/wiki/Common-Issues#javalangassertionerror-expected-aes-to-be-available-when-a-user-tries-to-connect and for any further issues join our discord @ https://discord.geysermc.org/

The system I use is Windows Server 2012
