### ISSUE TITLE
Ability to use menu in CrazyAuction or chestcommands.

### ISSUE THREAD

**Issue by Jakubar** [GeyserMC/Geyser#1123]
When u make fast click, u will see "lore" of item and the cost
So the main idea is, when you try to click "next page" you are not able to open it.
![image](https://user-images.githubusercontent.com/57572014/89927248-41480000-dc30-11ea-957d-fafc50be60f2.png)

**Comment by rtm516** [comment]
> When u make fast click, u will see "lore" of item and the cost
> So the main idea is, when you try to click "next page" you are not able to open it.
> ![image](https://user-images.githubusercontent.com/57572014/89927248-41480000-dc30-11ea-957d-fafc50be60f2.png)

Please use the bug report template.

**Comment by RednedEpic** [comment]
Closing as the bug report template was not used and we do not have enough information about this going from the given information. If this is still a problem, please edit the initial bug report to follow the issue template and comment here so we can open it back up.
