### ISSUE TITLE
[floodgate-spigot] the value does not change "*"

### ISSUE THREAD

**Issue by towuk118** [GeyserMC/Geyser#1126]
**Describe the bug**

start server witch online mode + floodgate-spigot (not installed plugins)
start geyser
connect

**Screenshots / Videos**
if you set an empty value, it doesn't work, it is still replaced with the value of an asterisk ( "*" ) in the game:
![image](https://user-images.githubusercontent.com/28830162/89932686-b0b0f600-dc16-11ea-9337-90a595bd1c76.png)
![image](https://user-images.githubusercontent.com/28830162/89933119-46e51c00-dc17-11ea-91dd-3cd4c55172f9.png)

PAPER + floodgate-spigot: This server is running Paper version git-Paper-135 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT) JAVA + BE clients: 1.16.1 and 1.16.10
Geyser standalone: https://dump.geysermc.org/abBn2fvbOlhDQS3a2O6q1rgMvB5wMQR4

**Comment by DoctorMacc** [comment]
Delete your `usercache.json` file located in the root server directory.

In the future please make this issue in the Floodgate repository.

**Comment by towuk118** [comment]
sorry
