### ISSUE TITLE
Bad Omen Effect not visible to Bedrock Players

### ISSUE THREAD

**Issue by romibi** [GeyserMC/Geyser#1129]
**Describe the bug**
Bad Omen Effect is not shown

**To Reproduce**
1. Connect to Server with Geyser with some Bedrock Client
2. Find a Raid Captain
3. Kill Raid Captain
4. Bug: Bad Omen Effect is not visible
5. Resulting Problem: Raid starts unexpectedly when going into a Village

**Expected behavior**
On Step 4 the Bad Omen Effect should be shown

**Screenshots / Videos**
If wanted I can provide Videos at a later date …

**Server Version**
`This server is running CraftBukkit version git-Spigot-8918ad0-7a9e4f7 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`

**Geyser Version**
`This server is running Geyser version 1.0.0 (git-master-964432e) (Java: 1.16.1, Bedrock: 1.16.0)`

**Minecraft: Bedrock Edition Version**
Nintendo Switch on Minecraft 1.16.10

**Additional Context**
`Plugins (3): CoreProtect, Geyser-Spigot, Vivecraft-Spigot-Extensions`
I have issued the dump command but … **could you please maybe warn people that the dump gets uploaded automatically to your servers containing the server IP ~~and no way to censor it~~‽** …
Dump: https://gist.github.com/113cb10451f022ac769cdde4d1327b73

Edit: moved Fire related issues to new Bug #1130

**Comment by DoctorMacc** [comment]
Thanks for reporting this! Could you make a separate issue for the things related to the fire, and then keep this one strictly for the bad omen effect? It really helps us out with organization. (What I meant by related was the two bullet points you had related to the fire)

And yeah, I do apologize about the dump information. We'll take steps to restrict the amount of data shown by default.

**Comment by Heath123** [comment]
**and no way to censor it‽**
It will still get uploaded, but you can censor it manually and not share the original link if you want while you wait for us to restrict the info properly. Keep in mind that having the IP does help with troubleshooting, but you're right, I think it should be opt-in.
