### ISSUE TITLE
Fire (from exploding beds in the nether) not properly synced for Bedrock Players

### ISSUE THREAD

**Issue by romibi** [GeyserMC/Geyser#1130]
Now split off from #1129
**Describe the bug**
- exploding beds in the nether does not properly sync created fires to the client
- exploding beds in the nether do not vanish
- punching said fires to put them out does not (always) propagate to the server

**To Reproduce**
1. Craft some Beds
2. Go to Nether
3. Place Bed
4. Try to sleep
5. Explosion happens (expected)
6. Invisible fires light you on fire (and bed is still visible)
7. leave nether and enter again
8. Punch now visible Fires to put out
9. Fire vanishes on client but stays on Server

**Expected behavior**
On Step 5/6 the Bed should vanish and Fire should appear
On Step 8/9 the fire should also vanish on the Server

**Screenshots / Videos**
https://youtu.be/HtYQWKDdnOM

**Server Version**
`This server is running CraftBukkit version git-Spigot-8918ad0-7a9e4f7 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`

**Geyser Version**
Previous: `This server is running Geyser version 1.0.0 (git-master-964432e) (Java: 1.16.1, Bedrock: 1.16.0)`
Now Updated: `This server is running Geyser version 1.1.0 (git-master-e02495c) (Java: 1.16.2, Bedrock: 1.16.20)`

**Minecraft: Bedrock Edition Version**
Previous: Nintendo Switch and Android both on Minecraft 1.16.10
Now Updated: Nintendo Switch on 1.16.20 (Android untested)

**Additional Context**
Previous: `Plugins (3): CoreProtect, Geyser-Spigot, Vivecraft-Spigot-Extensions`
Dump: https://gist.github.com/113cb10451f022ac769cdde4d1327b73
Now Updated: `Plugins (5): CoreProtect, floodgate-bukkit, ViaVersion, Geyser-Spigot, Vivecraft-Spigot-Extensions`
Dump: not yet done …

Edit: Updated info after updating Geyser, adding ViaVersion and Floodgate. And added link to Video.

**Comment by DoctorMacc** [comment]
Thank you for splitting the issues!

**Comment by Heath123** [comment]
Could this be a non-full chunk issue?

**Comment by romibi** [comment]
After updating Minecraft for Switch and Geyser today to 1.16.2, installing ViaVersion (server is still on 1.16.1) and installing floodgate, now punching out fires got more reliable: punching the blocks they are on works always ... punching them sideways does not ...
you know if it worked if you hear the sizzeling ... even when punching invisible fires ...
I have a video on the SD Card but i'm currently too lazy to copy it to the PC and dont want it on FB/Twitter ...

**Comment by DoctorMacc** [comment]
Could you please update Geyser and see if the fires are now accurate?

**Comment by romibi** [comment]
The Bed properly vanishes, the Fire properly appears …
But punching Fire sideways still doesn't sync to the server:
https://youtu.be/upE47bgGOwA

One thing i noticed when updating: in the config the remote address 127.0.0.1 doesn't work anymore … had to put the public server ip there … this isn't an issue for me and i haven't checked if there is already a ticket created … just something i noticed

**Comment by RednedEpic** [comment]
The problem with the fire being unable to be hit is separate from this and I believe there is already an open issue for it. As for the remote address problem, please reach out to us on Discord. As the problem in this issue has been solved, I am going to close this. Thanks for the report!
