### ISSUE TITLE
Weather not synced

### ISSUE THREAD

**Issue by jkcoxson** [GeyserMC/Geyser#1134]
**Describe the bug**
On bedrock clients, rain does not show up. Changing the weather to rain does not work, relogging does not fix it. Java clients experience weather fine.

**To Reproduce**
1. Log in on Java and see that it is raining.
2. Log in on Bedrock and see that it is not raining.

**Expected behavior**
It is supposed to be raining on bedrock.

**Screenshots / Videos**
https://drive.google.com/file/d/16j7sQOUdGMsFVnFwBq2_80wdGNdBnb-4/view?usp=sharing, https://drive.google.com/file/d/1Z5gh3W6aocxn5RqHL7HtsUnO-c5_8p0Z/view?usp=sharing

**Server Version**
Minecraft Server Software from Mojang, 1.16.1

**Geyser Version**
This server is running Geyser version 1.0.0 (git-master-b84986a)

**Minecraft: Bedrock Edition Version**
16.1.1

**Additional Context**
https://dump.geysermc.org/CaOdW2tYMP0G8KadwQWrKn1YofA9Dh1t

**Comment by DoctorMacc** [comment]
Testing on an official vanilla server, the bug occurs. It does not occur on the test server.
