### ISSUE TITLE
[bug] formatting the server name

### ISSUE THREAD

**Issue by TOWUK** [GeyserMC/Geyser#1136]
**Describe the bug**
formatting the server names are displayed slightly incorrectly

**To Reproduce**
server.properties:
![image](https://user-images.githubusercontent.com/28830162/90031796-540d1400-dcc6-11ea-9d82-047856a94962.png)

**Expected behavior**
```
bug: [**YOURNAME] TEMPLATE SERVER**
fixed: [**YOURNAME**] **TEMPLATE SERVER**
```

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/28830162/90032037-9c2c3680-dcc6-11ea-9f49-c59471dd3f40.png)

![image](https://user-images.githubusercontent.com/28830162/90031859-65eeb700-dcc6-11ea-9ff5-effb683ccd1a.png)

**Server Version**
This server is running CraftBukkit version git-Spigot-379750e-43c7ff9 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Geyser Version**
На этом сервере Geyser версии 1.1.0 (git-master-e02495c) (Java: 1.16.2, Bedrock: 1.16.20)

**Minecraft: Bedrock Edition Version**
1.16.20

**Additional Context**
Мы сохранили информацию отладки, сообщите нам о вашей проблеме и укажите этот url: https://dump.geysermc.org/Ez5KSh2Ti7gQYMKJjiiW5ZlLxQWr8mJt

**Comment by BlusteryS** [comment]
In Java, after each new color, the bold font is reset. Not so in Bedrock. But I also want this to be changed as in Java.

**Comment by RednedEpic** [comment]
This is because the bedrock client does not reset the formatting when a new color is introduced. What you can do in this instance is after "YOURNAME", use `\u00A7r` to reset and everything should work fine. Aside from that, there is already an issue for this at #652 so this is a duplicate.
