### ISSUE TITLE
Update for 1.16.2

### ISSUE THREAD

**Issue by SubMGRru** [GeyserMC/Geyser#1137]
Needs update to Hotflix 1.16.2

**Comment by DoctorMacc** [comment]
The latest Geyser is updated on both Java and Bedrock.

**Comment by SubMGRru** [comment]
I'm updated to 361 build from Jenkins, and I still getting message about "Outdated server. I'm still on 1.16.1", using Spigot

**Comment by DoctorMacc** [comment]
Install ViaVersion on your server.

**Comment by towuk118** [comment]
> I'm updated to 361 build from Jenkins, and I still getting message about "Outdated server. I'm still on 1.16.1", using Spigot

build 361???  are you from the future?
![image](https://user-images.githubusercontent.com/28830162/90040535-ba972f80-dcd0-11ea-9088-54d2c323984e.png)

**Comment by TOWUK** [comment]
> Install ViaVersion on your server.

why? spigot is already 1.16.2 and everything works without a kick about the availability of the version
