### ISSUE TITLE
Enable/Disable check for XBOX in the config

### ISSUE THREAD

**Issue by BlusteryS** [GeyserMC/Geyser#1143]
**What feature do you need?**
I want the config to have an option: enable or disable check for XBOX.

**Alternatives?**
Haven't tried anything.

**Comment by ipad54** [comment]
О, блустери саша, привет

**Comment by ImDaBigBoss** [comment]
That would be sooo helpful!

**Comment by DoctorMacc** [comment]
Why should we?

**Comment by DoctorMacc** [comment]
This is not something that Geyser intends to fix. Xbox Live accounts are free.

If this is for piracy, Geyser does not support piracy. Please buy the game and support Mojang.

**Comment by BlusteryS** [comment]
Spigot has pirated version support

**Comment by Heath123** [comment]
> Spigot has pirated version support. It will be very good for server owners if this proxy has such a function.

That's offline mode, which is intended for playing without an Internet connection. Again, Xbox Live accounts are free, this has nothing to do with piracy, it's just not that useful

**Comment by Heath123** [comment]
Maybe this could be useful for testing/playing on a local network from the Friends tab though? Maybe it could do what the Bedrock Dedicated Server does and only accept unauthenticated connections from local networks

**Comment by Menci** [comment]
![image](https://user-images.githubusercontent.com/11341955/105175330-b82de100-5b5e-11eb-80f4-b79a5dd0f5d1.png)

I bought Minecraft BE but it doesn't login. So I can't play on my Geyser server.

I hope this issue could be resolved.

**Comment by YHDiamond** [comment]
I think you commented on the wrong issue @Menci If you need help solving a geyser issue please go to our dicord (discord.geysermc.org)

**Comment by vnt-83** [comment]
> Это не то, что Geyser намеревается исправить. Учетные записи Xbox Live бесплатны.
> 
> Если это для пиратства, Geyser не поддерживает пиратство. Пожалуйста, купите игру и поддержите Mojang.



> Spigot has pirated version support. It will be very good for server owners if this proxy has such a function.

dunce

I have two children with a purchased game. When you are logged into xbox, you cannot play at home with each other on the Friends tab.
