### ISSUE TITLE
Links in chat are not clickable

### ISSUE THREAD

**Issue by DarkyCat** [GeyserMC/Geyser#1146]
If a link is sent to the server and a player with bedrock edition cannot click on it. Only if you manually rewrite.

**Comment by PQguanfang** [comment]
What? Does Minecraft Bedrock Edition have this function that players can click the links in chat?

**Comment by PQguanfang** [comment]
What? Does Minecraft Bedrock Edition have this function that players can click the links in chat?

**Comment by EasyClifton** [comment]
Bedrock does not have link clicking functionality.

**Comment by DarkyCat** [comment]
The problem is, when you click on the link in the chat, nothing happens. Not like the PC version.

**Comment by toinouH** [comment]
I would add the tag "Won't fix" because we can't do anything for the moment.

**Comment by Heath123** [comment]
Yes, this is impossible to fix because it isn't in Bedrock Edition

**Comment by bundabrg** [comment]
Closing as bedrock limitation.
