### ISSUE TITLE
Can the proxy run from a dummy plugin?

### ISSUE THREAD

**Issue by anar4732** [GeyserMC/Geyser#1150]
I do not tell to port this to a plugin instead of this we can use dummy plugin to start the actual proxy process on another thread and pass it the ip adress and port directliy.
this makes we can use the actual server and proxy with one jar.
then we can use this on minecraft server hosts that supports just a jar file for starting server.

**Comment by Heath123** [comment]
@anar4732 Why not use the plugin version of Geyser?

**Comment by Heath123** [comment]
Geyser-Spigot.jar already exists
