### ISSUE TITLE
Stuck on 'Building terrain' when switching dimensions

### ISSUE THREAD

**Issue by YEET78** [GeyserMC/Geyser#1154]
**Describe the bug**
When loading into the nether on Bedrock, the client crashes and has to be reloaded 

**To Reproduce**
1. load into the game on bedrock 1.16.2
2. join a java (forge 1.16.2) server
3. load into the nether
4. game will stick on building terrain screen

**Expected behavior**
Game should load into the nether with no client crashes

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/55087407/90302427-0519d700-de9e-11ea-8d02-3881f9f3eb1c.png)

**Server Version**
Forge 1.16.2 (33.0.5)

**Geyser Version**
Standalone: Geyser version 1.1.0 (git-master-4bcf446) (Java: 1.16.2, Bedrock: 1.16.20)

**Minecraft: Bedrock Edition Version**
1.16.2

**Additional Context**
No Server Plugins
https://dump.geysermc.org/I6hyG4Kq4j4LGNlbzqnX89hFC2pz2glA

**Comment by DoctorMacc** [comment]
Thank you for following the issue template.

**Comment by DoctorMacc** [comment]
I encountered this issue when running 1.16.2-rc2 with Geyser but the error disappeared after I updated. Might be related?

**Comment by DoctorMacc** [comment]
I was unable to confirm this on a Forge server.

**Comment by RednedEpic** [comment]
Looking at this now, don't think this is specific to forge as others were having similar problems in vanilla in #1072. Considering the given information they're likely related. @YEET78 can you confirm if this is still a problem and if it's related to #1072? You mention that the client crashes but also mention that it only gets stuck on this dimension screen.

**Comment by CberYellowstone** [comment]
> This problem does not exist on Spigot nor Paper.

so will you fix this bug?
This problem greatly affects the game experience.

**Comment by RednedEpic** [comment]
> > This problem does not exist on Spigot nor Paper.
> 
> so will you fix this bug?
> This problem greatly affects the game experience.

It's definitely a bug, so yes. We're trying to get more information on what the problem is and are reporting some of our findings back to this issue.
