### ISSUE TITLE
Anti Knockback

### ISSUE THREAD

**Issue by KingRainbow44** [GeyserMC/Geyser#1155]
**Describe the bug**

When others attack you, you do not take any knockback.
**To Reproduce**

1. Join a server
2. Attack the player using Geyser
**Expected behavior**

The player is meant to take knockback.
**Screenshots / Videos**

**Server Version**

1.8.9 - 1.16.x
**Geyser Version**

1.1.0
**Minecraft: Bedrock Edition Version**

1.16.20
**Additional Context**

**Comment by KingRainbow44** [comment]
This issue was also mentioned by #891

**Comment by DoctorMacc** [comment]
Thank you for reporting this issue! However, there is no need to duplicate issues if they already exist; therefore I am closing this.
