### ISSUE TITLE
Wrong particles on bedrock

### ISSUE THREAD

**Issue by diamond-gold** [GeyserMC/Geyser#1157]
**Describe the bug**
Particles displayed on bedrock is different from Java

**To Reproduce**
Put a repeating command block with the command /particle minecraft:enchant ~ ~1 ~
Bedrock players sees happy villager particle instead of enchantment table particle

**Expected behavior**
Java and bedrock sees the same particle

**Server Version**
This server is running Paper version git-Paper-384 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
build 332

**Minecraft: Bedrock Edition Version**
1.16.20

**Additional Context**
Some particles that I tested
enchant seen as happy_villager
happy_villager seen as angry_villager
angry_villager seen as rain splash
dragon_breath seen as end rod
bubble_column_up seen as randomly colored enchant
squid_ink seen as potion
entity_effect seen as black falling dust
item_slime seen as black dust
falling_dust seen as dripping honey
witch seen as note
rain seen as item_slime
totem_of_undying seen as cloud

note seen as nothing
end_rod seen as nothing
campfire_cosy_smoke seen as nothing

**Comment by DoctorMacc** [comment]
Finally looking into this - do you happen to be on our Discord?

**Comment by DoctorMacc** [comment]
Fixed in #684.
