### ISSUE TITLE
Certain worlds not loading

### ISSUE THREAD

**Issue by SanjeetKhangura** [GeyserMC/Geyser#1159]
so when bedrock players join, the world doesn't load for them.. like they see all the npcs but not the blocks
![Capture](https://user-images.githubusercontent.com/69596998/90340216-7e532000-dfab-11ea-9cc1-93b528263ea1.JPG)
![Capture1](https://user-images.githubusercontent.com/69596998/90340221-81e6a700-dfab-11ea-8cd7-48f244ecd97b.JPG)
![Capture2](https://user-images.githubusercontent.com/69596998/90340232-8b700f00-dfab-11ea-8158-f8d5bb32be2e.JPG)
![Capture3](https://user-images.githubusercontent.com/69596998/90340236-8e6aff80-dfab-11ea-8140-5bee252cf8e1.JPG)
The Most recent error even after the new update ^

**Comment by SanjeetKhangura** [comment]
![IMG_5593](https://user-images.githubusercontent.com/69596998/90340333-4698a800-dfac-11ea-93a4-9471e2cdd7a4.png)
Same thing happened with the 2nd latest version with this error

**Comment by RednedEpic** [comment]
Thanks for opening an issue, however please follow the bug report format when opening reports. As for some of the errors here, they aren't even related to Geyser at all. 

Could you please provide a dump by running `/geyser dump`?

**Comment by SanjeetKhangura** [comment]
Should I just copy paste the dump?

**Comment by RednedEpic** [comment]
Run `/geyser dump` then paste the link it gives you here.

**Comment by SanjeetKhangura** [comment]
https://dump.geysermc.org/2OQGXwQWRSvvJyzRlNCiCPuFmXFnm4wM

**Comment by RednedEpic** [comment]
Please update both your Geyser and Paper versions as you're quite out of date for both. Let us know if the issue still persists after you've done that.

**Comment by SanjeetKhangura** [comment]
okay will do .. and give u an update after Thanks!

**Comment by DoctorMacc** [comment]
As we have made improvements to this part of the code, I am going to assume this is fixed. Please let us know if this is not the case!
