### ISSUE TITLE
mcMMO crash bug

### ISSUE THREAD

**Issue by JacksFO** [GeyserMC/Geyser#1164]
**Describe the bug**
The bug is while using mcMMO plugin on Paper-Spigot with Geyser+Floodgate allowing bedrock players to connect, I had my friend join me on his Xbox one. I gave him an iron axe and made him use his tree fella ability (shift + right click / crouch left trigger) the ability allows you to mine one of the tree blocks and destroys the entire tree, once you activate and once the ability end there are green and red particles. Which caused him to crash entirely. He then reconnected and tried to do the same with a pickaxe (the ability just gives you a small buff to mine quicker for a few seconds until you level it up) when he used the pickaxe it was fine even with the particles. Then I used MY shovel to mine some sand (he was standing 2 blocks away from me) looking at me and it crashed him.

**To Reproduce**
MAKE SURE YOU HAVE mcMMO Classic spigot plugin installed, Go into survival mode and give yourself a iron axe / iron pickaxe / iron shovel / iron sword (on bedrock version of the game)
Then shift + right click / crouch + right trigger (xbox) with one of the items in your hand to activate your ability (should say in chat "you ready'd your *item* a.k.a axe/pickaxe etc. )
then mine the appropricate resource for that item, (so for axe mine a tree, pickaxe mine some stone)
See if game crashes.

**Expected behavior**
Nothing is expected just not to crash.

**Screenshots / Videos**
https://youtu.be/rUi9Pmg_cYo?t=100  (STARTED AT 1:40) (WASN'T ABLE TO CUT VIDEO)

**Server Version**
1.16.1 (Paper)

**Geyser Version**
Geyser Version - Geyser-Spigot.jar #338
Floodgate Version - Flootgate-Bukkit.jar #25

**Minecraft: Bedrock Edition Version**
Bedrock version 1.16.20

**Additional Context**
We believe it was to do with particles from mcMMO, when you activate your ability / use it, there are red and green firework particles set in the config for mcMMO you can turn these particles off / make the smaller they are default to large fireworks.
I had turned the particles off and re-tested and he was now not crashing either when he tried his abilities or when he watched me do it.

**Comment by RednedEpic** [comment]
> **Describe the bug**
> The bug is while using mcMMO plugin on Paper-Spigot with Geyser+Floodgate allowing bedrock players to connect, I had my friend join me on his Xbox one. I gave him an iron axe and made him use his tree fella ability (shift + right click / crouch left trigger) the ability allows you to mine one of the tree blocks and destroys the entire tree, once you activate and once the ability end there are green and red particles. Which caused him to crash entirely. He then reconnected and tried to do the same with a pickaxe (the ability just gives you a small buff to mine quicker for a few seconds until you level it up) when he used the pickaxe it was fine even with the particles. Then I used MY shovel to mine some sand (he was standing 2 blocks away from me) looking at me and it crashed him.
> 
> **To Reproduce**
> MAKE SURE YOU HAVE mcMMO Classic spigot plugin installed, Go into survival mode and give yourself a iron axe / iron pickaxe / iron shovel / iron sword (on bedrock version of the game)
> Then shift + right click / crouch + right trigger (xbox) with one of the items in your hand to activate your ability (should say in chat "you ready'd your _item_ a.k.a axe/pickaxe etc. )
> then mine the appropricate resource for that item, (so for axe mine a tree, pickaxe mine some stone)
> See if game crashes.
> 
> **Expected behavior**
> Nothing is expected just not to crash.
> 
> **Screenshots / Videos**
> https://youtu.be/rUi9Pmg_cYo?t=100 (STARTED AT 1:40) (WASN'T ABLE TO CUT VIDEO)
> 
> **Server Version**
> 1.16.1 (Paper)
> 
> **Geyser Version**
> Geyser Version - Geyser-Spigot.jar #338
> Floodgate Version - Flootgate-Bukkit.jar #25
> 
> **Minecraft: Bedrock Edition Version**
> Bedrock version 1.16.20
> 
> **Additional Context**
> We believe it was to do with particles from mcMMO, when you activate your ability / use it, there are red and green firework particles set in the config for mcMMO you can turn these particles off / make the smaller they are default to large fireworks.
> I had turned the particles off and re-tested and he was now not crashing either when he tried his abilities or when he watched me do it.

This crash is because fireworks are involved which currently crash consoles. This is unfortunately a game bug which is something Mojang will need to fix (exclusive to consoles at this point in time), though we'll be looking into ways to get around this in the meantime. Regardless, thanks for the report!
