### ISSUE TITLE
Can join using ngrok?

### ISSUE THREAD

**Issue by Pling123** [GeyserMC/Geyser#1165]
I put the plugin in my server but i cant join the ngrok server because the ngrok ip was 2.tcp.eu.ngrok.io:12989. I tried putting the 12989 as a port but still i/my friend cant connect. I use ngrok cuz i have problems with forwarding/ i have duoble nat cuz of my internet provider.

**Comment by LogicismDev** [comment]
Ngrok is not supported over UDP as Bedrock Protocol uses UDP

**Comment by Pling123** [comment]
is there anyway that i can use udp using ngrok?

**Comment by rtm516** [comment]
As mentioned here (https://github.com/inconshreveable/ngrok/issues/26) ngrok doesnt support UDP.

**Comment by Pling123** [comment]
> 
> 
> As mentioned here ([inconshreveable/ngrok#26](https://github.com/inconshreveable/ngrok/issues/26)) ngrok doesnt support UDP.

Is there any other way i can host using udp and tcp?

**Comment by rtm516** [comment]
> Is there any other way i can host using udp and tcp?

Portforward or try using UPnP, please jump on our [Discord](http://discord.geysermc.org/) if you want to continue this.
