### ISSUE TITLE
Player cannot open Enchantment Table

### ISSUE THREAD

**Issue by partridge420x** [GeyserMC/Geyser#1167]
**Describe the bug**
Mcpe Player cannot open any enchanting table

**To Reproduce**
Login with MCPE
Build a enchanting table
Try to open it
Unable to open its inventory, no console error

**Expected behavior**
Have the ability to open the enchantment table and apply enchantments to weapons and armor

**Screenshots / Videos**

**Server Version**
 This server is running Paper version git-Paper-129 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.1.0 (git-master-8c514d9) (Java: 1.16.2, Bedrock: 1.16.20)
Sister servers are running Paper version git-Paper-129 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT) with viaversion to allow latest update for bedrock to still connect to my server

**Minecraft: Bedrock Edition Version**
1.16.2

**Additional Context**

https://dump.geysermc.org/wPvyPRdKcCH9SP3pY1M9PPrLOZuYC2pw

**Comment by RednedEpic** [comment]
This is known and is mentioned in the README as unimplemented. Support for this will be added once the inventory rewrite is complete. Regardless, thanks for taking the time to open an issue, but in the future, please check the README and other open issues to ensure there isn't already a report about this :)
