### ISSUE TITLE
User connects, gets disconnected when using a crafting (Sending to many packets)

### ISSUE THREAD

**Issue by Lorenzo-St** [GeyserMC/Geyser#1176]
[latest.log](https://github.com/GeyserMC/Geyser/files/5105129/latest.log)

**Describe the bug**
I set up a Spigot server using geyser as a plugin, when my sister plays on the server on our Xbox one, when she opens/leaves a crafting table she gets kicked. I have only been able to reproduce using the Xbox one version, my windows 10 edition has not been able to reproduce this bug.

**To Reproduce**
1. set up latest spigot server using geyser in plugin form
2. join server using Xbox one edition bedrock client
3. open crafting table and crafting a couple things on Xbox one edition client
4. Leave crafting table

**Expected behavior**
When using crafting table on Xbox one bedrock client the client would get disconnected, with the server saying
[11:47:00] [Server thread/INFO]: *User lost connection: You are sending too many packets, :(
[11:47:00] [nioEventLoopGroup-11-2/INFO]: [Geyser-Spigot] User has disconnected from remote Java server on address 192.168.4.55 because of {"text":"","extra":["You are sending too many packets, :("]}

**Screenshots / Videos**
Idk how useful this image will be of the disconnect screen but here it is anyway
https://drive.google.com/file/d/1X_WUM8XSeEZBqoZEn_lkPQpKodnnE-Ue/view?usp=sharing

**Server Version**
The server is running version git-Spigot-9639cf7-4b9bc9d (MC: 116.1)

**Geyser Version**
Using Geyser version 1.1.0 (git-master-e7363b4)

**Minecraft: Bedrock Edition Version**
v1.16.20 as taken from Minecraft Home screen

**Additional Context**
The plugins on the server are
1. Floodgate
2. Sleepmost
3. geyser
4. VaiVersion

Geyser dump: https://dump.geysermc.org/jrXHT3Q8S8Dyfx6aPDDlO1pP2Lbly2lx

I have attached the logs for when i attempted to reproduce the bug.

**Comment by j5155** [comment]
A fix for this would be setting max-pps in ViaVersion config settings to -1, which would disable getting kicked for too many packets. However, it seems a bit odd that it only kicks you on Xbox. Are you using the crafting book or putting in the recipe manually?

**Comment by DoctorMacc** [comment]
It's like the crafting book. Fun fact, that didn't work until 1.16. Might be related.

**Comment by Lorenzo-St** [comment]
in response to j5155's question, I used both

**Comment by brickett6** [comment]
The temp fix doesn't work

**Comment by Lorenzo-St** [comment]
it does work, just make sure that all number values under the "Global Packet Limiter" section are equal to -1

**Comment by Camotoy** [comment]
I haven't heard this occurring since the inventory rewrite. If this still happens, let us know!

**Comment by AlphaJH5** [comment]
PS4 Users on my Server are getting kicked out while crafting
