### ISSUE TITLE
Error when use 1.16.2 protocol with authlib-injector

### ISSUE THREAD

**Issue by MlgmXyysd** [GeyserMC/Geyser#1178]
**Describe the bug**
I used [Blessing Skin Server](https://github.com/bs-community/blessing-skin-server) to set up a yggdrasil server, use [Authlib Injector](https://github.com/yushijinhun/authlib-injector) to replace authentication server.
When using Java Edition 1.16.2, I can log in and play normally.
When using the Android Bedrock Edition 1.16.20 to log in to the game, I can normally enter and pop up the login prompt.
But when I enter the user name and password, I disconnect and prompt `Authentication servers are down. Please try again later, sorry!`
I'm sure that the authentication server is working properly, and it works when running 1.16.1 and its compatible older version of Geyser.

**To Reproduce**
1. Connected server with Android Bedrock Edition 1.16.20.
2. Enter the user name and password for my custom authentication server.
3. Disconnect: Authentication servers are down. Please try again later, sorry!
4. See error in log.

**Expected behavior**
log in and play normally

**Screenshots / Videos**
Only console logs
```
[Network Listener - #1/INFO]: [Geyser-Spigot] /127.0.0.1:12345 tried to connect!
[authlib-injector.transform] [INFO] Transformed [com.github.steveice10.mc.auth.service.SessionService] with [Constant URL Transformer]
[Network Listener - #1/INFO]: [Geyser-Spigot] Player connected with username xxx
[authlib-injector.transform] [INFO] Transformed [com.github.steveice10.mc.auth.service.AuthenticationService] with [Constant URL Transformer]
[nioEventLoopGroup-2-2/INFO]: [Geyser-Spigot] MlgmXyysd (logged in as: xxx) has connected to remote java server on address 127.0.0.1
[authlib-injector.internal.fi.iki.elonen.NanoHTTPD] [SEVERE] Could not send response to the client
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.ChunkedOutputStream.write(ChunkedOutputStream.java:83)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.Response.sendBody(Response.java:292)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.Response.sendBodyWithCorrectTransferAndEncoding(Response.java:262)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.Response.send(Response.java:232)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:428)
        at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:116)
        at java.lang.Thread.run(Thread.java:748)

[User Authenticator #1/INFO]: Disconnecting com.mojang.authlib.GameProfile@5a83d45c[id=<null>,name=mlgmxyysd,properties={},legacy=false] (/127.0.0.1:12345): Authentication servers are down. Please try again later, sorry!
[User Authenticator #1/ERROR]: Couldn't verify username because servers are unavailable
[nioEventLoopGroup-2-2/INFO]: [Geyser-Spigot] xxx has disconnected from remote Java server on address 127.0.0.1 because of Authentication servers are down. Please try again later, sorry!
[Server thread/INFO]: com.mojang.authlib.GameProfile@5a83d45c[id=<null>,name=xxx,properties={},legacy=false] (/127.0.0.1:52728) lost connection: Authentication servers are down. Please try again later, sorry!
[Network Listener - #1/INFO]: [Geyser-Spigot] Bedrock user with ip: /127.0.0.1 has disconnected for reason CLOSED_BY_REMOTE_PEER
```

**Server Version**
CraftBukkit version git-Spigot-379750e-eaf0bac (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Geyser Version**
Geyser version 1.1.0 (git-master-7fcfa7d) (Java: 1.16.2, Bedrock: 1.16.20)

**Minecraft: Bedrock Edition Version**
1.16.20

**Additional Context**
https://dump.geysermc.org/VtfZcoq9IBWSerXMFfvhh1iOYWDZBM1b

**Comment by DoctorMacc** [comment]
Thanks for the issue! See https://github.com/GeyserMC/Geyser/issues/1095#issuecomment-675202620 for the status of this.
