### ISSUE TITLE
Single Player Sleep Plugin

### ISSUE THREAD

**Issue by JacksFO** [GeyserMC/Geyser#1182]
**Describe the bug**
Just some info on a plugin I use. So we use (https://www.spigotmc.org/resources/singleplayersleep.68139/) and it works for the Java players, but when a Console player sleeps it doesn't skip the night / bring up the message in chat (https://gyazo.com/97aecf6fc3af519e7cbd4e16638c4311)

**To Reproduce**
Sleep in a bed? Use the plugin here (https://www.spigotmc.org/resources/singleplayersleep.68139/) and won't work for bedrock players.

**Expected behavior**
They should bring a message up in chat here (https://gyazo.com/97aecf6fc3af519e7cbd4e16638c4311) and skip the night, but they do not.

**Server Version**
Server Version 1.16.1 Paper

**Geyser Version**
Geyser-Spigot #347

**Minecraft: Bedrock Edition Version**
1.16.2

**Aditional Information**
When a Java player sleeps its sends this message in console 

"22.08 19:12:09 [Server] INFO tellraw *CWI6 ["",{"text":"JacksFO is sleeping ["},{"text":"CANCEL]","clickEvent":{"action":"run_command","value":"/spscancel"},"hoverEvent":{"action":"show_text","value":"Click to cancel sleep"}}]<--[HERE]"

CWI6 Is a bedrock player, JacksFO Is me Java Player

**Comment by RednedEpic** [comment]
Closing as there is not a whole lot we can do in this case. As suggested above, I'd recommend using another plugin, or if that is simply not an option, you can modify the prefix in the Floodgate config to a different character that the plugin allows.
