### ISSUE TITLE
Inaccurate ping

### ISSUE THREAD

**Issue by Comstepr** [GeyserMC/Geyser#1186]
**Describe the bug**
When checking a user's ping, it shows as 0 or -1

**To Reproduce**
Check a player's ping with a server plugin, such as PremiumVanish or a Skript which checks ping

**Expected behavior**
Show accurate ping

**Screenshots / Videos**

**Server Version**
git-Tuinity-"30ac89a"

**Geyser Version**
git-master-af1efe9 of my fork
**Note that I use my own fork of Geyser, however I don't see why this would mess with server ping.**

**Additional Context**
https://dump.geysermc.org/CCbnrpIQ7Xf4rVf9Mj0iG6CQJ4PZ23yg

**Comment by DoctorMacc** [comment]
Thanks for the report! However, this is the current limitation of the ping passthrough system since it calls Spigot methods to determine the ping (which may be unreliable). If you wish to use plugins that modify the ping system you have to enable legacy ping passthrough.
