### ISSUE TITLE
You copied DragonProxy and you should credit it! 

### ISSUE THREAD

**Issue by DefinitlyEvil** [GeyserMC/Geyser#119]
You copied DragonProxy and you should credit it! 
You even changed author names from original sources. 
Should be ashamed by yourself. 

Original code: https://github.com/DragonetMC/DragonProxy

**Comment by Tim203** [comment]
?

**Comment by Tim203** [comment]
#ad ? Xd

**Comment by DefinitlyEvil** [comment]
@Tim203 This is no ad, this repo will be taken down.

**Comment by RednedEpic** [comment]
> You copied DragonProxy and you should credit it!
> You even changed author names from original sources.
> Should be ashamed by yourself.
> 
> Original code: https://github.com/DragonetMC/DragonProxy

You could argue Sponge copied Bukkit... or Velocity copies BungeeCord...

**Comment by LegacyGamerHD** [comment]
what the hell

**Comment by DefinitlyEvil** [comment]
@RednedEpic They rewrote the code, you just copied and changed the author.

**Comment by RednedEpic** [comment]
> @RednedEpic They rewrote the code, you just copied and changed the author.

You might wanna do your research, because it’s actually the other way around.

**Comment by Heath123** [comment]
I hope this is a joke

**Comment by LegacyGamerHD** [comment]
@DefinitlyEvil  your wrong most code is originel on geyser

**Comment by LegacyGamerHD** [comment]
@DefinitlyEvil  your wrong most code is originel on geyser

**Comment by Tim203** [comment]
GL lol. I never looked at DP code except when I tried to help DP with Chunks

**Comment by JustTalDevelops** [comment]
If Geyser copied DragonProxy, then why is DragonProxy not getting updates yet Geyser is?

**Comment by Stualyttle** [comment]
The developpers of Dragonproxy even recommend using this! 
![image](https://user-images.githubusercontent.com/27898452/71448688-3e4edc80-273f-11ea-86bd-70052bd0c0bc.png)

**Comment by RednedEpic** [comment]
This was all just a misunderstanding. The situation has been resolved.
