### ISSUE TITLE
The saplings did not grow properly

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Geyser#1190]
**Describe the bug**

The saplings did not grow properly

**To Reproduce**

Placing saplings

Using bone meal

Trees are sometimes incomplete

**Expected behavior**

Trees should display normally

**Screenshots / Videos**

![Screenshot_20200824_120112_com huawei himovie](https://user-images.githubusercontent.com/53421735/91002708-f94ab500-e601-11ea-8f83-95887078b4df.jpg)

Video:
https://cdn.discordapp.com/attachments/624959336275509248/747309822952734770/QQ_c0c6e816cf5fe72c61845dad81d760e71598242916.mp4

**Server Version**

Paper1.16.1

**Geyser Version**

Geyser-Spigot 351

**Minecraft: Bedrock Edition Version**

1.16.20

**Comment by zimzaza4** [comment]
After filling the blocks with / fill, the blocks display is not correct

**Comment by RednedEpic** [comment]
This is due to Geyser not yet supporting non-full chunks. This has already been reported in #399 so I'm going to close this issue.
