### ISSUE TITLE
Cant walk on some blocks

### ISSUE THREAD

**Issue by ElectroGamesYT** [GeyserMC/Geyser#1191]
**Describe the bug**
You are not able to walk on alot of blocks such as stairs, slabs, lily pads, carpets, and probably more that I dont know of. When you walk on these blocks, you will constantly lag back to that block when you try to get off of it. Some of the blocks you can sneak to go across them but others will keep you on it and its almost impossible to get unstuck. 

**To Reproduce**
Walk onto one of the blocks above then try to walk off it.

**Expected behavior**
Your supposed to be able to walk across these blocks without lagging back and getting stuck...

**Server Version**
Im pretty sure all

**Geyser Version**
1.1.0

**Minecraft: Bedrock Edition Version**
1.16.20

**Comment by bundabrg** [comment]
Known issue and being worked on in #699. A workaround for now is to relax anticheat like flying in your server config so it's more tolerant. Please follow progress in the linked pr.
