### ISSUE TITLE
World border issues

### ISSUE THREAD

**Issue by Comstepr** [GeyserMC/Geyser#1193]
**Describe the bug**
Worldborder cannot be seen on Bedrock Edition

I'm omitting some information as I am aware that there is a Worldborder branch on this repo, but it is still a bug.

**Comment by Hellohi3654** [comment]
I'm guessing they're working on the world border that's why it's still a separate branch

**Comment by RednedEpic** [comment]
Duplicate of #447. Additionally, in the future, please follow the full issue template when reporting bugs.
