### ISSUE TITLE
Login choice

### ISSUE THREAD

**Issue by ImDaBigBoss** [GeyserMC/Geyser#1200]
**What feature do you want?**
Would it be possible to let players choose if they want to use floodgate or online mode?
It would be helpful in situations when a java players want to continue their progress on bedrock but allow bedrock players with no java account connect.

**Alternatives?**
Nothing

**Comment by rtm516** [comment]
This is a duplicate of https://github.com/GeyserMC/Geyser/issues/1116
Please use Floodgate account linking.
