### ISSUE TITLE
Bedrock player does not die in void when using a lobby with player damage disabled

### ISSUE THREAD

**Issue by kobenetwork** [GeyserMC/Geyser#1201]
If bedrock player joins server with a lobby plug-in like deluxehub that disables player damage the bedrock player does not die nor spawn back to the server spawnpoint. 

* Java players gets teleported on spawnpoint

* Bedrock players keep floating till server kicks them for flying (in void)

How to recreate: have a no player damage plugin-option-gamerule

**Comment by RednedEpic** [comment]
Please follow the issue template.
