### ISSUE TITLE
Item Frames placed in Java are Invisible on Bedrock until you right click the spot with empty hand

### ISSUE THREAD

**Issue by DragonBornMage** [GeyserMC/Geyser#1207]
**Describe the bug**

When item frame is placed on a wall, also if an item is placed in that item frame, on Java, both the item frame and item in it are invisible on Bedrock version. If you right click the spot where the frame should be on Bedrock with nothing in your hand then the item frame and item in it appears.
**To Reproduce**

1. In Java place an item frame on a wall, and place any item in the frame. Log off the game from Java.

2. Go to Bedrock edition. The item frame will not be visible

3. Right click the spot on the wall where the item frame is placed with nothing in your hand, and it appears

**Expected behavior**

Item frames placed in Java should automatically be visible on bedrock
**Screenshots / Videos**

[Video of Issue](https://www.reddit.com/user/DragonBornMage/comments/igs4n3/item_frame_issue/)
**Server Version**

paper-145 ( 1.16.2 )
**Geyser Version**

Build 357
**Minecraft: Bedrock Edition Version**

1.16.2
**Additional Context**

I notice that if both the Java player and bedrock player are on the game in the same area then the item frame appears when the java player places it. But if it was already there its invisible

**Comment by DoctorMacc** [comment]
I was unable to confirm this myself. Could you please provide a Geyser dump with `/geyser dump`?

**Comment by botjuice** [comment]
I had a similar issue except that when I was in bedrock if I wasn’t within 3 blocks distance from where I was placing an object, the object would not appear. When I moved into that space though it would start glitching. If I wanted it to appear I would have to use a weapon or empty hand.
Hope this helps. 🙂

**Comment by DoctorMacc** [comment]
@botjuice are you on mobile when this happens?

**Comment by botjuice** [comment]
Yes

**Comment by Camotoy** [comment]
Does this issue still occur from anyone?

**Comment by Jens-Co** [comment]
I'll close this issue due to no response, If this issue still occurs to someone feel free to comment here and I'll reopen this issue.
