### ISSUE TITLE
Geyser Scoreboard Formatting Issue 1.16.2

### ISSUE THREAD

**Issue by EmperorDRT1** [GeyserMC/Geyser#1216]
**Describe the bug**

When connecting to a geyser java server from bedrock the scoreboard's formatting is incorrect.
**To Reproduce**

To reproduce join any java server using a scoreboard to display extra information. IP of server I used: 
Java: thebois.tech
Bedrock: thebois.games
**Expected behavior**

Scoreboard should display its information with similar formatting and positions as the java server.
**Screenshots / Videos**

https://ibb.co/NnMySHp
https://ibb.co/Qp8BKcz
**Server Version**

paper version 1.16.2 build 150
**Geyser Version**

This server is running Geyser version 1.1.0 (git-master-caa5098) (Java: 1.16.2, Bedrock: 1.16.20)
**Minecraft: Bedrock Edition Version**

Minecraft Windows 10 Edition v1.16.20
**Additional Context**

I did not have this issue on the Java 1.15.2/Geyser 1.14 and has only occurred after updated both to 1.16.2

**Comment by Tim203** [comment]
What is the Scoreboard plugin you're using to get this?

**Comment by EmperorDRT1** [comment]
We are using SimpleScore.
https://www.spigotmc.org/resources/simplescore.23243/

**Comment by BiGUNMAN** [comment]
This bug exists when using other scoreboard systems as well, such as: https://www.spigotmc.org/resources/kiteboard.13694/

**Comment by Tim203** [comment]
Ensure you're on the latest Geyser version and please provide something like a screenshot

**Comment by EmperorDRT1** [comment]
I'm still have the same issue on the latest version of geyser.

**Comment by BiGUNMAN** [comment]
@Tim203 Here is a screenshot: https://media.discordapp.net/attachments/623241204729118780/752646104784437308/image0.png?width=1062&height=490
