### ISSUE TITLE
Warning on Console

### ISSUE THREAD

**Issue by Hellohi3654** [GeyserMC/Geyser#1218]
![image](https://user-images.githubusercontent.com/57390764/91632476-4d9bcd80-ea24-11ea-812f-2962add7b43d.png)
Found this bug it said to report 
Don't know what the player was doing

**Comment by ImDaBigBoss** [comment]
It seems they have managed to get items into "slot 50" of the inventory. Java allows 27 slots + 9 on the hotbar.

**Comment by DoctorMacc** [comment]
Likely related to the the ability of consoles to now craft; closing as it's not connected to a specific issue.
