### ISSUE TITLE
Whitelist and OP fix for plugin

### ISSUE THREAD

**Issue by ImDaBigBoss** [GeyserMC/Geyser#1219]
**What feature do you want?**
I would like a geyser command to whitelist/op bedrock players. For example /geyser op <player> /geyser whitelist <player>. Or an override to the default commands?

**Alternatives?**
Manualy editing the op.json and whitelist.json files.

**Comment by rtm516** [comment]
This is more appropriate in the floodgate repo, but there is already a request open there https://github.com/GeyserMC/Floodgate/issues/39
