### ISSUE TITLE
Use an extra creative inventory slot as trash slot

### ISSUE THREAD

**Issue by jackson-57** [GeyserMC/Geyser#1222]
**What feature do you want?**
Even though this feature isn't natively in Bedrock, it would still be nice to have, and make the Bedrock experience more like Java Edition. I think the 'crafting result' slot would be perfect, as it's currently empty.

**Alternatives?**
Items can still be deleted by selecting them and replacing them with something in the creative item picker menu.

**Comment by bundabrg** [comment]
I don't think the result slot can have items placed inside?

**Comment by jackson-57** [comment]
Ah, I should have expected that. I don't know much about how the inventory system works, but potentially one (or all, if the barriers don't have to be removed) of the crafting slots could still be used as a trash slot.

**Comment by bundabrg** [comment]
That should be fine. We can detect the change and will chuck away the cursor then reset the barrier..

**Comment by soshimee** [comment]
I would really appreciate if this gets added.

**Comment by RednedEpic** [comment]
This is unlikely to be implemented into Geyser, given there hasn't been any interest + activity on this in over a year. Thanks for the suggestion regardless!
