### ISSUE TITLE
Crossbow not visibly charged

### ISSUE THREAD

**Issue by Mskitty301** [GeyserMC/Geyser#1223]
**Describe the bug**

Crossbows aren't shown to be charged on bedrock.

**To Reproduce**

Charge a crossbow on bedrock edition in a java server.

**Expected behavior**

It should charge and have the arrow visible in the crossbow but it doesn't.

**Screenshots / Videos**
(Both have no audio)

https://youtu.be/lBZgTvaRm0c (Bedrock only)

https://youtu.be/lUtrg-0_nyE (Includes Bedrock & Java)

**Server Version**

Paper version git-Paper-158 (MC:1.16.2) (Implenting API verison 1.16.2-R0.1-SNAPSHOT)

**Geyser Version**

Geyser version 1.1.0 (git-master-37c4192) (Java: 1.16.2, Bedrock 1.16.0 - 1.16.100)

**Minecraft: Bedrock Edition Version**

Minecraft windows 10 edition v1.16.20

**Additional Context**

**Comment by Mskitty301** [comment]
What is the geyser repo? I don't use github

**Comment by rtm516** [comment]
> What is the geyser repo? I don't use github

I moved it on your behalf, but please follow the issue template as seen on the other issues.

**Comment by Mskitty301** [comment]
Should be good now.

**Comment by DoctorMacc** [comment]
This should be fixed.
