### ISSUE TITLE
Jumping into water when running won’t result in smooth swimming

### ISSUE THREAD

**Issue by botjuice** [GeyserMC/Geyser#1230]
**Describe the bug**

Running into water won’t make you swim
**To Reproduce**

On iOS run into water. (Android hasn’t been tested)
**Expected behavior**

Dive into the water and start swimming immediately
**Screenshots / Videos**

**Server Version**

![IMG_1666](https://user-images.githubusercontent.com/52659026/91727148-ea3ba800-eba9-11ea-9d3a-e0881380560a.jpeg)

**Geyser Version**
Geyser version: 1.1.0

**Minecraft: Bedrock Edition Version**

1.16.2
**Additional Context**
Don’t know if this is the same issue or not, but when you surface in the water it still takes breathing bubbles in survival.

**Comment by Camotoy** [comment]
In iOS, I can successfully jump into water and start swimming. This may have been fixed, so if there is no reply here I will close this in a week.

**Comment by Camotoy** [comment]
No response within a week. Thank you for making an issue regardless!
