### ISSUE TITLE
Customizable kick message when disabled

### ISSUE THREAD

**Issue by diamond-gold** [GeyserMC/Geyser#1232]
**What feature do you want?**
Please make the kick message customizable, the message when Geyser is disabled and kicks all bedrock players

**Alternatives?**
None

**Comment by DoctorMacc** [comment]
What would you want to change it to, as a curiosity?

**Comment by diamond-gold** [comment]
Maybe to same as java server? I customised the shutdown message for Java players, it would be great if the bedrock players can see it too

**Comment by TOWUK** [comment]
![image](https://user-images.githubusercontent.com/28830162/92274744-73c6df00-eef6-11ea-81b2-2f1a95f6e980.png)
like its messages :)

**Comment by RednedEpic** [comment]
This is already customizable; open up the jar with any archive program (7zip, Winrar, etc.), navigate to the locale files (in `languages/texts/...`) and change `geyser.core.shutdown.kick.message` to whatever you want.
