### ISSUE TITLE
Bedrock players cant see disguised players [Lib Disguise]

### ISSUE THREAD

**Issue by Grizzly90** [GeyserMC/Geyser#1233]
**Describe the bug**
Bedrock players connected via Geyser to a Java server can't see players who are disguised with Lib Disguise

**To Reproduce**
1. setup server with lib disguise(we use premium but it shouldn't make a difference)
2. stay in front of each other.
3. disguise
4. Every disguised player is completely invisible (but you can see your own disguise if you are disguised yourself [e.g. as a chicken you will see a chicken instead of yourself])

**Expected behavior**
see the other players in their disguise

**Server Version**
This server is running CraftBukkit version git-Spigot-9639cf7-4b9bc9d (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
 Auf diesem Server läuft Geyser Version 1.1.0 (git-master-2f9ff0c) (Java: 1.16.2, Bedrock: 1.16.0 - 1.16.100)
As Bungee plugin

**Minecraft: Bedrock Edition Version**
1.16.20 (if it's the version number on the screen after start)

**Additional Context**
the warning on disguise in the Bungee console:
23:59:11 [WARNUNG] [Geyser-BungeeCord] Fehler beim Übersetzen der Metadaten: EntityMetadata(id=14, type=BYTE, value=0) für Entität PLAYER
23:59:11 [WARNUNG] [Geyser-BungeeCord] Fehler beim Übersetzen der Metadaten: EntityMetadata(id=14, type=BYTE, value=0) für Entität PLAYER

https://dump.geysermc.org/GIeA89uqdPkFIYm1WvsJ8RDDkLoUoyVj

**Comment by FdiiX** [comment]
hello can someone fix this after 2 years??

**Comment by Kas-tle** [comment]
> hello can someone fix this after 2 years??

@FdiiX the issue was closed presumably because it was fixed. If you are experiencing this or a similar issue on the current version of Geyser, please open a new.

**Comment by Chew** [comment]
Guys...
Camotoy closed this as [completed](https://github.com/GeyserMC/Geyser/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/GeyserMC/Geyser/pull/1263 [on Sep 14, 2020](https://github.com/GeyserMC/Geyser/issues/1233#event-3765915394)

But yes, see above.
