### ISSUE TITLE
Legacy ping passthrough

### ISSUE THREAD

**Issue by Comstepr** [GeyserMC/Geyser#1234]
**Describe the bug**
Ping is rather inaccurate giving Low figures. Users on Bedrock edition get extremely Low ping

**To Reproduce**
Enable legacy ping pass through 
Get a plug-in which shows a users ping

**Expected behavior**

The ping is meant to be way higher as some people are not in the same country the server is hosted on

**Screenshots / Videos**

Unable to get one at the moment

**Server Version**

Trinity

This server is running Tuinity version git-Tuinity-"f663f6e" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Geyser Version**

This server is running Geyser version 1.1.0 (git-master-61a6559) (Java: 1.16.2, Bedrock: 1.16.0 - 1.16.100)
This is from my fork of Geyser. However my fork is even with the main branch.

**Additional Context**

**Comment by Comstepr** [comment]
We've made a dump with useful information, report your issue and provide this url: https://dump.geysermc.org/Ao4dB3ozrgOfQf2x7ABBhthPRFDOpbG3

**Comment by DoctorMacc** [comment]
A bit of confusion here with the user over what ping passthrough is. For passersby, ping passthrough is for showing the Java server's MOTD and player count. For the time being we have no way to emulate showing the correct ping. Closing; thanks for reporting anyway!
