### ISSUE TITLE
[RPi3] Client crashes on server join

### ISSUE THREAD

**Issue by Retloldin** [GeyserMC/Geyser#124]
**Describe the bug**
When you run the proxy on an RPi3 with Java JDK 1.8.0_231, bedrock clients close when they receive map chunks.

**To Reproduce**
1. Run Geyser on RPi3
2. Connect whit any bedrock client (Android, Windows tested)
3. Proxy shows */X.X.X.X:YYYYY tried to connect!*
3.1. Client don't receive map chunks: The client stays connected
3.2 The proxy tries to send map chunks: The client closes without any error on the screen

**Expected behavior**
The client connects and receives the map chunks without closing.

**Server version**
PaperMC 1.15.1

**Geyser version**
I have tried the following versions:
- Jenkins
- Compiled from master
- Floodgate patched version (someone uploaded on Discord)

**Bedrock version**
1.14.1

**Additional context**
The proxy was tested with the following versions of Java:
OpenJDK 8
OpenJDK 9
OpenJDK 11
Oracle JDK 8 (downloaded from web)

**Comment by RednedEpic** [comment]
We've gotten a few reports of offline mode not working properly in some cases. Could you check to make sure that is not the cause of the issue?

**Comment by Retloldin** [comment]
Using "online-mode=true" on PaperMC and "auth-type: online" on Geyser the client stays connected but does not receive any map chunk. NPCs load on screen but the player keeps floating on nothing.

**Comment by RednedEpic** [comment]
Try teleporting around and moving.

**Comment by Retloldin** [comment]
After trying to reconnect, teleport, change gamemode and /kill the client still does not see the map. Testing the same .jar on a Debian 10 x64 machine after the second login the client starts to see the map.

**Comment by RednedEpic** [comment]
What are the specs of each computer and how much ram are you allocating?

**Comment by Retloldin** [comment]
I've been doing more tests and these are the results:
- Debian 10 x64 (4 cpu cores, 4 GB RAM, Oracle JDK 8, Online / Offline): Works after 2nd connection.
- Debian 10 x86 (2 cpu cores, 2 GB RAM, OpenJDK11, Online / Offline): Works after 2nd connection.
- Debian 10 x86 (1 cpu cores, 1 GB RAM, OpenJDK11, Online / Offline): Works after 2nd connection.

- Raspbian Buster (RPi3, 1GB RAM, OpenJDK11 / OpenJDK8 / Oracle JDK 8, Offline): First connection without map chunks, second connection crashes the application.
- Raspbian Buster (RPi3, 1GB RAM, OpenJDK11 / OpenJDK8 / Oracle JDK 8, Online): Clients connect to the server and are able to move in the current chunk, but are not able to see any block.

I attach a video of a client (Recorded from Android) when connecting to the server in Rpi3 with Online mode:
https://youtu.be/aWymViv-STg

**Comment by RednedEpic** [comment]
> I've been doing more tests and these are the results:
> 
> * Debian 10 x64 (4 cpu cores, 4 GB RAM, Oracle JDK 8, Online / Offline): Works after 2nd connection.
> * Debian 10 x86 (2 cpu cores, 2 GB RAM, OpenJDK11, Online / Offline): Works after 2nd connection.
> * Debian 10 x86 (1 cpu cores, 1 GB RAM, OpenJDK11, Online / Offline): Works after 2nd connection.
> * Raspbian Buster (RPi3, 1GB RAM, OpenJDK11 / OpenJDK8 / Oracle JDK 8, Offline): First connection without map chunks, second connection crashes the application.
> * Raspbian Buster (RPi3, 1GB RAM, OpenJDK11 / OpenJDK8 / Oracle JDK 8, Online): Clients connect to the server and are able to move in the current chunk, but are not able to see any block.
> 
> I attach a video of a client (Recorded from Android) when connecting to the server in Rpi3 with Online mode:
> https://youtu.be/aWymViv-STg

If I had to guess, it’s due to the low amount of RAM and likely a slow processor. Try waiting for a prolonged amount of time (like 5 mins) to see if anything else happens.

**Comment by RednedEpic** [comment]
Closing due to lack of response. Please contact us on Discord or comment here if this is still an issue and the above did not work.
