### ISSUE TITLE
Armour stand book

### ISSUE THREAD

**Issue by homelyseven250** [GeyserMC/Geyser#1241]
**What feature do you want?**
I would like for the Armour Stands Book from [Vanilla Tweaks](https://vanillatweaks.net/picker/datapacks/) to show the custom armour stands on bedrock, and maybe also the book itself.

**Alternatives?**
None.

**Comment by EasyClifton** [comment]
Unfortunately, that's impossible, as the armor stands can only have certain pre-set poses on bedrock and the clickable things in books are impossible to make too, because they don't exist on bedrock.

**Comment by homelyseven250** [comment]
OK, it would have been cool, but it's clearly not possible. Thanks for taking a look!
