### ISSUE TITLE
Boats do not always place correctly

### ISSUE THREAD

**Issue by zanson** [GeyserMC/Geyser#1247]
**Describe the bug**

Placing a boat from an iOS client does not always work.  Some times when placing a boat the iOS client will think it placed the boat and it disappears from your inventory, but then it does not appear in the world.  If you do something to refresh your inventory it will appear back in your bar.

**To Reproduce**

1. Get a boat.
2. Go to some water.
3. Tap to place the boat in the water.
4. Boat disappears from inventory as if placed.
5. Boat does not appear in the water.
6. Boat eventually appears back in your inventory.

**Expected behavior**

The boat appears in the water.

**Screenshots / Videos**

Video: https://imgur.com/a/1GadeXD

**Server Version**

git-Paper-141 (MC: 1.16.2)

**Geyser Version**

Geyser version 1.1.0 (git-master-2f9ff0c) (Java: 1.16.2, Bedrock: 1.16.0 - 1.16.100)

**Minecraft: Bedrock Edition Version**

iOS 1.16.20

**Additional Context**

ViaVersionPlugin 3.1.0
ViaBackwards 3.1.0
floodgate-bukkit 1.0-SNAPSHOT

**Comment by HyperSkys** [comment]
This is most likely a bug with trying to get the players inventory or trying to get where you wanted to place the boat, currently, I couldn't see a fix for this.

**Comment by Errorcode101** [comment]
I have had the same issue when placing boats on water and on ice, I believe it happens when you try to place a boat and there is another block nearby that the boat would sit inside of (Placing a boat too close to the shore or Placing a boat where a majority of the boat would be floating)

**Comment by onkr0d** [comment]
Issue still persists on Geyser 2.0.0, Paper-1.18.1-100

**Comment by RednedEpic** [comment]
@onkr0d are you able to provide a video of this happen + further replication steps?

**Comment by onkr0d** [comment]
@RednedEpic the video initially provided by @zanson demonstrates the bug correctly. The replication steps still apply as well.
