### ISSUE TITLE
Punching Fire sideways does not sync to server

### ISSUE THREAD

**Issue by romibi** [GeyserMC/Geyser#1248]
Punching Fire sideways, that means punching a block which is adjacent to, not under the fire does put out the fire on Bedrock Client visually but does not sync to the server.
Walking onto the block which contained the fire does put you on fire and makes you take damage.
Punching the block under the invisible fire properly puts out the fire on the serverside as well.
The hiss sound of vanishing fire is a good indicator if the fire was really put out.
It is played when punching the block under the (invisible) fire but not when punching through the fire (a block on the side).

**To Reproduce**
1. Login onto a Java Server with a Bedrock Client
2. Create a fire in any convenient way
3. Punch a block next to the fire sideways through the fire
4. The fire vanishes but no hiss sound
5. Step on the block the fire was on
6. Leave the block the fire was on because you are on fire
7. (Optionally) Wait until you don't burn anymore
8. Punch the block the fire was on
9. Hear hiss sound, repeat step 5 and notice all is fine

**Expected behavior**
On Step 4: a hiss sound
On Step 6: not getting put on fire
On Step 9: not hear hiss sound
Steps 6-9 unnecessary if issue resolved.

**Screenshots / Videos**
https://youtu.be/upE47bgGOwA
(Fire created via Bed-Explosion because of Issue #1130 )

**Server Version**
This server is running CraftBukkit version git-Spigot-379750e-fe4efd1 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
(I know it's not the newest, but I'm too lazy to build it myself)

**Geyser Version**
This server is running Geyser version 1.1.0 (git-master-5b76a85) (Java: 1.16.2, Bedrock: 1.16.0 - 1.16.100)

**Minecraft: Bedrock Edition Version**
Minecraft Switch 1.16.21 (Connected via BedrockConnect)

**Additional Context**
Plugins: GeyserMC, Floodgate, ViaVersion, ViaBackwards (only some few versions enabled), Vivecraft Extension
Some VanillaTweaks Datapacks installed
Hosted on gamed.de (it could be added to the supported hosters if you don't mind non-english hosters on the list)
Geyser dump: https://gist.github.com/romibi/f29614a625647be83535c9ab6f5a0b65

**Comment by DoctorMacc** [comment]
Just noticed the `Hosted on gamed.de` - yes, any host can be added to the Supported Hosting Providers list.
