### ISSUE TITLE
Problems with respawn entities

### ISSUE THREAD

**Issue by linmiao233** [GeyserMC/Geyser#125]
Problems with respawn entities,But other players see you as normal.

![text] (https://s2.ax1x.com/2019/12/31/l3gh0H.jpg)

**Comment by RednedEpic** [comment]
Apologies for the late reply, but could you please provide some more information about how you got yourself to show up like this? Also please use the format.

**Comment by linmiao233** [comment]
I used the historical version of Geyser, and the problem does not exist now
