### ISSUE TITLE
Compatibility problem with Vehicles Plugin

### ISSUE THREAD

**Issue by S4Ma3Lx** [GeyserMC/Geyser#1250]
When I join with my Windows 10 version on my Paper server (build 387 1.15.2 with via.version for 1.16.2) with Geyser Spigot 1.1.0 I can't see the vehicles created with the plugin Vehicles which does not require any texture pack because they're armor stand.

**Comment by DoctorMacc** [comment]
In the future, please follow the issue template. However this is part of a bigger issue that I will create a placeholder issue for.
