### ISSUE TITLE
Armor stand invisibility is inconsistent with Java

### ISSUE THREAD

**Issue by Camotoy** [GeyserMC/Geyser#1251]
**Describe the bug**
When an armor stand is invisible in Java, the items that are attached to the armor stand still show. Bedrock does not follow this behavior.

At this time, there is nothing we can do about it. This issue will stand as a placeholder for information and to discuss workarounds.

**Geyser Version**
As of build 377.

**Minecraft: Bedrock Edition Version**
1.16.10

**Comment by EasyClifton** [comment]
A crazy, laggy and an unpractical idea: make a custom entity for where the the thing, that the armor stand displays should be. Like the custom heads.

**Comment by DoctorMacc** [comment]
Might be the most practical. If we send a custom resource pack, we can swap out the armor stand.

**Comment by diamond-gold** [comment]
In vanilla bedrock, if the armor stand becomes invisible (throw an invisibility splash potion at it) while holding an item the item is still shown, geyser should be able to do the same?

**Comment by DoctorMacc** [comment]
Yes, that is possible; however, nametags don't show then.

**Comment by EasyClifton** [comment]
Another crazy idea: Analyze what the thing made with all these armor stands should look like and merge it into a single model.

**Comment by DoctorMacc** [comment]
Nope. Even if that were possible I don't think we would want to do that.

**Comment by Heath123** [comment]
> Yes, that is possible; however, nametags don't show then.

Can't you spawn a separate entity for that? It sounds WAY cleaner than a custom enitity

**Comment by DoctorMacc** [comment]
Going to see if that's possible now.

**Comment by Heath123** [comment]
![image](https://user-images.githubusercontent.com/13787163/92415272-175efc00-f150-11ea-9f3a-572c87f59feb.png)

**Comment by bobhenl** [comment]
I think that this PR should be merged as soon as possible... cause this is really important when you imagine so many things are did via holograms, may my hologram issue https://github.com/GeyserMC/Geyser/issues/1734 could be related too to this. And it's important to see armor stands.
