### ISSUE TITLE
"given scan urls are empty. set urls in the configuration" on startup

### ISSUE THREAD

**Issue by DoctorMacc** [GeyserMC/Geyser#1252]
**Describe the bug**
On starting up plugin versions, the message `[org.geysermc.platform.<PLATFORM>.shaded.reflections.Reflections] given scan urls are empty. set urls in the configuration` is given. This is a harmless error that affects nothing.

**To Reproduce**
Start up a plugin version of Geyser.

**Geyser Version**
As of build 377.

**Comment by anoxic** [comment]
this might have something to do with the Reflections library: https://github.com/ronmamo/reflections/issues/186

**Comment by rtm516** [comment]
It is, and an issue with the version we use but if we upgrade it then it breaks android support.

**Comment by anoxic** [comment]
Maybe this stackoverflow will help: https://stackoverflow.com/questions/41932635/scanning-classpath-modulepath-in-runtime-in-java-9/45612376#45612376

**Comment by DoctorMacc** [comment]
At a cursory glance this isn't specifically a Java 9 thing - I develop with Java 8 and get this all the time.

**Comment by MichaIng** [comment]
Seeing this on Java 11 as well.

**Comment by NotStirred** [comment]
I'm seeing issues with it taking more than 3 minutes to get through it. Whether it's this or something else I'm not sure
```
[10:34:52 WARN]: [org.geysermc.platform.spigot.shaded.reflections.Reflections] given scan urls are empty. set urls in the configuration
[10:38:20 WARN]: [org.geysermc.platform.spigot.shaded.reflections.Reflections] given scan urls are empty. set urls in the configuration
```

**Comment by MichaIng** [comment]
Yes those messages are appearing with a significant delay (heavily depending on the power of the host machine of course, in my case it was something around 20 seconds) between each other. But it cannot be derived that the underlying issue is the reason for the delay, but maybe there is a lot of other processing which at some distant points produce the warnings.

**Comment by DoctorMacc** [comment]
I would expect that the delay is not because of those errors.

**Comment by soshimee** [comment]
> It is, and an issue with the version we use but if we upgrade it then it breaks android support.

d...owngrade maybe?

**Comment by Chew** [comment]
I believe you misunderstand. The version we are on gives that warning, but IF we upgrade, Android support will no longer work. No need to downgrade, it won't solve anything.

**Comment by Advewave** [comment]
Any update on this bug? It's still going on for me.

**Comment by yehudahrrs** [comment]
Yes. This bug is part of a library we use, you can ignore it and it will not break anything.

**Comment by Advewave** [comment]
> Yes. This bug is part of a library we use, you can ignore it and it will not break anything.

thank you!

**Comment by soshimee** [comment]
I don't know why people say it takes minutes to go through that stage, it only takes 3~5 secs with a small server.

**Comment by MichaIng** [comment]
I tested it on some VMs (old i3 3110M CPU) where it took a significant time (minutes range all together). A native x86 server will likely have no issues, so practically it's more the SBC servers, which however become increasingly relevant (and also capable) in general, I guess.

**Comment by Heath123** [comment]
What about using a fork of Reflections? Or is it better to wait for them to fix Android?

**Comment by Tim203** [comment]
It's a harmless message, so I don't think that we need a fork.

**Comment by Heath123** [comment]
Yes, but it's consfusing and with a fork you could pull in some of the new changes probably

**Comment by Heath123** [comment]
0.9.11 vs 0.9.12
https://github.com/ronmamo/reflections/compare/c95609a4e83e1f3fc71e4b2fc58b17352a16eef7..7741e8f5d13f739d644ef5e91dde055fbe88ca57

**Comment by jackson-57** [comment]
> It's a harmless message, so I don't think that we need to fork it.

Agreed, although over in the Discord, we still get a ton of people asking about it. I think that forking it wouldn't be too hard to do, but if we don't want to go that route, could we possibly add our own message to the top/bottom of it, telling people to ignore?
