### ISSUE TITLE
Error spam with ViaVersion 3.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by Minecon724** [GeyserMC/Geyser#1257]
**Describe the bug**

Geyser spams errors in console
Everything else works fine

**To Reproduce**

1. Join server with geyser installed
2. Look at console output

**Expected behavior**

No errors

**Screenshots / Videos**

![IMG_20200906_194125](https://user-images.githubusercontent.com/39800107/92331864-e1e7df00-f079-11ea-92e3-3b89804e02ed.jpg)

**Server Version**

![IMG_20200906_194102](https://user-images.githubusercontent.com/39800107/92331879-f9bf6300-f079-11ea-9e1e-f5773f9adeb7.jpg)

**Geyser Version**

![IMG_20200906_194924](https://user-images.githubusercontent.com/39800107/92331902-21163000-f07a-11ea-9655-2cf920abfe69.jpg)

**Minecraft: Bedrock Edition Version**

Android 1.16.1

**Additional Context**

[/geyser dump](https://dump.geysermc.org/8MBWLhJHQs3BzHHMvL9rzg0HLMfoMTcu)

**Comment by DoctorMacc** [comment]
This is a result of ViaVersion being too new. We will have a fix in the coming days, but for now use the ViaVersion on Spigot if you wish to remove the error.

**Comment by Hellohi3654** [comment]
This plugin is your best friend
https://www.spigotmc.org/resources/console-spam-fix.18410/

**Comment by MrZomka** [comment]
No it’s not. It’s not only the spam, it’s also in-game problems

**Comment by DoctorMacc** [comment]
This issue has long since been resolved.
