### ISSUE TITLE
Server IP does not save on Geyser Android

### ISSUE THREAD

**Issue by CrixPlayZ** [GeyserMC/Geyser#1259]
Hello, there's this issue on Geyser Android, when you put a server IP correctly and click on save, then start the server - it does not direct you to that server, instead, it is directing me test.geysermc.org rather than the server I put down and saved.

I was recording a video for youtube when this happened, please fix the saving mechanic for Geyser Android, thank you.

**Comment by rtm516** [comment]
Please follow the template and recreate this issue in https://github.com/rtm516/GeyserAndroid
Also can you record this happening so I can understand what is going on more.
