### ISSUE TITLE
Bedrock players shouldn't be able to jump dismount

### ISSUE THREAD

**Issue by KyBur** [GeyserMC/Geyser#1260]
**Describe the bug**
On bedrock editions players can jump to dismount an animal that doesn't have a jump bar. This becomes an issue with plugins like SimplePets where the player should be able to jump without dismounting the animal

**To Reproduce**

 Put saddle on a pig
 Jump to dismount when it should only allow sneak to dismount

**Expected behavior**
  Jumping should dismount, not sneak.

**Server Version**
 You are 1 version(s) behind

**Geyser Version**
 You are 1 versions behind; download the latest build from http://ci.geysermc.org/

**Minecraft: Bedrock Edition Version**
 1.16.2

Being one version behind doesn't seem to be the problem

**Comment by KyBur** [comment]
Jumping to dismount is a natural bedrock feature, but causes issues with java plugins, is there a way to disable it? Another issue that happens with SimplePets is it puts the player below the animal instead of 'riding' above it. Any suggestions how I should go about changing this? I understand java and was thinking maybe a possible fix could be checking player name of person riding and if they have the '~' sign for bedrock, then moving their y position up 2-3 blocks? Idk, any suggestions?

**Comment by DoctorMacc** [comment]
It appears there is no way to distinguish between jumping to leave a vehicle and sneaking to leave a vehicle (tested on boats) - both send the same packet information. Perhaps there is a way to tell the client that you can jump on a vehicle.

**Comment by RednedEpic** [comment]
Bedrock limitation here - not much we can do regarding this unfortunately.

**Comment by SilentParrot** [comment]
Is there possibility to fake the ability to power jump on all mounted entities?
