### ISSUE TITLE
Hide scoreboard named x

### ISSUE THREAD

**Issue by soshimee** [GeyserMC/Geyser#1261]
**What feature do you want?**
Hide scoreboards with a certain name.

**Alternatives?**
Disabling scoreboards for Bedrock Edition completely.

**Comment by rtm516** [comment]
Why would you want this?

**Comment by soshimee** [comment]
I have a plugin that adds a scoreboard for showing ping on the tab list, but it looks repetitive with the player names also showing.

**Comment by rtm516** [comment]
Could you provide a video or screenshot?

**Comment by soshimee** [comment]
I can't right now, but it looks something like this in text format:

soshimee 100
someone 100

soshimee
someone

**Comment by Camotoy** [comment]
This *sounds* like a workaround for a bug, which is not an ideal solution. I will be closing this, but if you believe this is in error do let us know!
