### ISSUE TITLE
Carpets translated as slabs for java clients

### ISSUE THREAD

**Issue by lifegame1lu111** [GeyserMC/Geyser#1262]
**Describe the bug**
When i go on a carpet my java friend sees me as if i was standing on a slab so for them i am floating on the carpet

**To Reproduce**
1. Go on a carpet
2. Tell someone playing in java to screenshot you

**Expected behavior**
Stand normally on the carpet without floating

**Screenshots / Videos**
https://prnt.sc/udn9qo

**Server Version**
Java 1.16.2

**Geyser Version**
Standalone: git-master-d47360d

**Minecraft: Bedrock Edition Version**
Bedrock 1.16.40

**Comment by DoctorMacc** [comment]
Hello! We're consolidating all of our move issues into #204. Thank you regardless for the report!
