### ISSUE TITLE
Console spammed by a warning message

### ISSUE THREAD

**Issue by ZeTioZ** [GeyserMC/Geyser#1268]
Hi, I have installed Geyser and it seems that when a player connected through it, the console is spammed by this warning message...

![image](https://user-images.githubusercontent.com/12181249/92665302-7c5c5280-f306-11ea-8d8f-c60c28f2ac1c.png)

**Comment by DoctorMacc** [comment]
Please follow the issue template given to you when you create an issue. Thank you!
