### ISSUE TITLE
is there a way to join a 1.12.2 server or what is the version that is forced

### ISSUE THREAD

**Issue by thisisafakeacount** [GeyserMC/Geyser#127]
I got everything working but during joining the server it kicks me because ""i'm still on 1.12"
thank you.

Edit: spelling

**Comment by RednedEpic** [comment]
If the server has the plugin ViaVersion installed or allows 1.15.1 clients, then you can. If it doesn't, then there isn't anything you can do.

**Comment by thisisafakeacount** [comment]
thank you
