### ISSUE TITLE
Partial connection loss after radom action

### ISSUE THREAD

**Issue by xManInWhitex** [GeyserMC/Geyser#1273]
My Bedrock-Client seems to lose the connection to the Server Network but without disconnecting. I can move and commands will be redirected to the spigot server but every clickable block will not work (buttons, pressure plates, ...) and I'll get no feedback from the server. If I want to execute /spawn for example, the console of the Server says PlayerXY executed /spawn and teleports the client to the spawn location but on the side of the bedrock client the player will not be ported. If the Bedrock-Client does reconnect, the player stands on the position where the player should be.

The Inventory button on the screen of the bedrock client also won't work in this state.
I have not found defined way to break the connection. Sometimes it works for some commands sometimes it won't work directly after connecting.

If I'm using Geyser-Bungee no error messages appearing. When I'm using Geyser-Standalone I get some error messages.

`io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Operation not permitted`

Full Geyser-Log: https://hasteb.in/efilowun
Geyser Dump: https://dump.geysermc.org/OSk9rrYpJFRmploYAAEg4BGgs5uTwLEU

I've tested with bedrock on Windows 10 and Android.
I'm using BungeeCord#1533 with three PaperSpigot#187 Servers. (1.16.2)

**Comment by toinouH** [comment]
Could you please follow the issue template ? :D

**Comment by DoctorMacc** [comment]
Thanks for reporting the issue! However, yeah, please follow the issue template.
