### ISSUE TITLE
Resource Packs and Commands

### ISSUE THREAD

**Issue by creep3rcrafter** [GeyserMC/Geyser#1276]
it would be nice if they added it where you could trigger a resource pack/texture pack with a command like (/geyser loadrp [filename]) to apply a resource pack and another one to remove the pack like (/geyser reloadrp) or even add an option to the config to load from a resource pack file on join

**Comment by BasedUser** [comment]
Bumping this, conversion of resource packs would simplify workflow.

**Comment by arnauddorgans** [comment]
+1

**Comment by GoldenMyst** [comment]
+1

**Comment by Chew** [comment]
Please don't spam the issue unnecessarily, there are reactions for a reason.

**Comment by Camotoy** [comment]
A command for this is better suited for a future extension since it doesn't add parity and doesn't necessarily act as a workaround. Thanks anyway for the feature request!
