### ISSUE TITLE
Add prefix

### ISSUE THREAD

**Issue by GuerreroCraft61** [GeyserMC/Geyser#1277]
**What feature do you want?**
Add prefix to bedrock player (to prevent duplicate usernames) like using floodgate, but using `auth-type: offline`

**Alternatives?**
floodgate, but it don't work for no premium server (¿?)

**Comment by DoctorMacc** [comment]
Sorry, we don't have an interest in implementing such a feature, especially for the offline auth-type. 

`but it don't work for no premium server` Floodgate works with online mode servers (...and offline mode servers as well).

Thank you anyway!
