### ISSUE TITLE
Hopper Minecart on Bedrock is placed as Furnace Minecart

### ISSUE THREAD

**Issue by Spectr3D** [GeyserMC/Geyser#1279]
**Describe the bug**
When placing a Hopper Minecart on Bedrock edition, it places a Furnace Minecart instead. 

**To Reproduce**
1. Place Hopper Minecart on rail
*done*

**Server Version**
CraftBukkit version git-Spigot-3a70bd9-bf3d720 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**
Geyser version 1.1.0 (git-master-8c86308) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.100)
Plugin Version with Floodgate

**Minecraft: Bedrock Edition Version**
1.16.40

**Comment by DoctorMacc** [comment]
More specifically, the hopper minecart item is mistranslated.

**Comment by soshimee** [comment]
Only if someone in creative mode gets it, it places correctly if you use /give or crafting.
