### ISSUE TITLE
What type plugin? Bukkit? Snapshot? Vanilla?

### ISSUE THREAD

**Issue by GuckTubeYT** [GeyserMC/Geyser#128]
What type plugin? Bukkit? Snapshot? Vanilla?

**Comment by RednedEpic** [comment]
Geyer is not a plugin, it's a standalone proxy. Support for it being able to be ran as a plugin is being worked on, but not complete yet. Please read the wiki for more instructions.

**Comment by Heath123** [comment]
This isn't a plugin (there is a work-in-progress plugin version though). It's a separate program that translates between Bedrock and Java.

**Comment by Heath123** [comment]
> Geyer is not a plugin, it's a standalone proxy. Support for it being able to be ran as a plugin is being worked on, but not complete yet. Please read the wiki for more instructions.

Oh, I posted at the same time as you

**Comment by GuckTubeYT** [comment]
Oh thanks
