### ISSUE TITLE
Implement using items in offhand

### ISSUE THREAD

**Issue by soshimee** [GeyserMC/Geyser#1281]
**What feature do you want?**
In java, it is possible to use items that are in offhand, but it is not possible in Bedrock, like eating food in offhand. But in Bedrock, the nature of the game does not allow usage of items on offhand except few items like shield. I think there should be a way to use items in offhand.

**Alternatives?**
Using on mainhand, but it is slower to switch slots.

**Comment by DoctorMacc** [comment]
Thanks for the request! However, we already have a workaround for this in the form of `/geyser offhand`.

**Comment by soshimee** [comment]
Doesn't /geyser offhand "put" an item in the offhand? I can't "use" an item in the offhand.

**Comment by EasyClifton** [comment]
Yes, it just puts an item in the offhand. You can't use that item because that functionality is not in bedrock.

**Comment by soshimee** [comment]
I think Geyser should implement that, forcing the player to use the item when the player does certain action.

**Comment by DoctorMacc** [comment]
That *may* be out of Geyser's boundaries, as we have no way to tell when the offhand item is being used.

**Comment by soshimee** [comment]
Maybe using a command like /geyser offhand use?

**Comment by iamilam** [comment]
> Maybe using a command like /geyser offhand use?

that would be **_very_** inefficient

**Comment by Chew** [comment]
Ah yeah, let me run `/geyser placetorch`.

Anyway, please don't bump old issues, this discussion has run its course.
