### ISSUE TITLE
Minecraft Pocket Edition 1.16.2 Outdated Server, Im still on 1.16.2

### ISSUE THREAD

**Issue by hashplayer** [GeyserMC/Geyser#1282]
When i try to go on the Server on Minecraft Pocket Edition 1.16.2,I will be kicked and it says Outdated Server, Im still on 1.16.2 does anyone know how to fix it?

**Comment by DoctaEnkoda** [comment]
Just connect to 1.16.3

**Comment by Hellohi3654** [comment]
You need to have viaversion on the server
