### ISSUE TITLE
Kicked with IllegalStateException : Adding 1 elements would exceed capacity of 128

### ISSUE THREAD

**Issue by Kikisito** [GeyserMC/Geyser#1288]
**Describe the bug**

This bug kicks any Bedrock player that has been connected for a while. This has happened to multiple players. The user is kicked with the following reason.
> IllegalStateException : Adding 1 elements would exceed capacity of 128 @ com.google.common.base.Preconditions:593

**To Reproduce**

Connect to the server through any Bedrock version and wait about 15/20 minutes.

**Expected behavior**

A normal behaviour is expected with no kicks after 15/20 minutes.

**Screenshots / Videos**

![image](https://i.imgur.com/LpjdnSy.png)

**Server Version**

Paper#191 / Waterfall#373

**Geyser Version**

Geyser 8c86308 / build 379. Geyser is being used as a BungeeCord plugin, with Floodgate.

**Minecraft: Bedrock Edition Version**

Minecraft Bedrock 1.16.40 (Win10 and Android)

**Additional Context**

[Error stacktrace](https://hasteb.in/inesadew.lua)
[Geyser dump](https://dump.geysermc.org/rUBa7VxHJGOAIWt3iFQIEwtkM0hS6Ebh)

**Comment by DoctorMacc** [comment]
I believe we've had this error come up in the Geyser Discord and the solution was removing another plugin (so I would try without other plugins if possible). Does it happen at random with no event triggering it?

**Comment by Kikisito** [comment]
I couldn't find the solution you told me. This happens totally at random, no event is triggered.

**Comment by DoctorMacc** [comment]
Looks like it has to do with plugin messages. It could make sense since you're using Floodgate, but we don't send plugin messages unless the server sends the plugin message `minecraft:brand`.

**Comment by Kikisito** [comment]
I'm using a plugin ([F3Name](https://www.spigotmc.org/resources/f3name-edit-your-server-brand-in-debug-screen.58997/)) that sends the plugin message `minecraft:brand` every 20 seconds. I'll try to reproduce the bug without this plugin and I'll tell you.

**Comment by Kikisito** [comment]
I couldn't reproduce the bug. Anyways, I'll tell other people to try it. 

As this is a bug produced by a plugin, I guess I should report it to the plugin author, or is it something that should be fixed in Geyser? I don't really know how it works, so I would appreciate your answer.

**Comment by DoctorMacc** [comment]
Well, actually, your error message is in Waterfall itself! I would try BungeeCord to narrow down options, and then we can go from there.

**Comment by DoctorMacc** [comment]
Are you on our Discord?

**Comment by Kikisito** [comment]
Yes. I'm also trying to reproduce the bug on BungeeCord

**Comment by Kikisito** [comment]
> Yes. I'm also trying to reproduce the bug on BungeeCord
> 
> My discord is Kikisito#2106

Confirmed on BungeeCord

**Comment by NovaPixell** [comment]
Excuse me guys, i had this issues some month ago. Has been fixed? Now can I use F3Name on Bungee without risking the user from minecraft bedrock crashes?
