### ISSUE TITLE
Walking on glass in Java plays the breaking glass sound on the MCPE client.

### ISSUE THREAD

**Issue by applebee1558** [GeyserMC/Geyser#1289]
**Describe the bug**

When in a server with other java players, the walking on glass sound packet gets converted into breaking glass sound. 
**To Reproduce**

1. Go from a high distance and fall down on glass, hear the sound.
OR
1. Go in a server on MCPE and Java
2. Walk on the java account and hear sounds from the mcpe client.

**Expected behavior**

It should play the glass walking sound.

**Screenshots / Videos**

**Server Version**

Spigot 1.16.2 
![image](https://user-images.githubusercontent.com/30390986/93035583-3b0fbf80-f5f2-11ea-894d-07fdfd04ab36.png)

**Geyser Version**

1.1.0
![image](https://user-images.githubusercontent.com/30390986/93035603-4fec5300-f5f2-11ea-870a-464a54fccd17.png)

**Minecraft: Bedrock Edition Version**

1.16
**Additional Context**

https://dump.geysermc.org/vpIEPtlBbjavZCpB0Uz7yEpRzIr8hRP
ViaVersion for compability
Envoy for proxying from the edge server to the geyser instance

**Comment by RednedEpic** [comment]
Can you please send your plugin list and a video of this happening?

**Comment by DoctorMacc** [comment]
(The dump link also appears to be incorrect)

**Comment by applebee1558** [comment]
Plugins: 
![image](https://user-images.githubusercontent.com/30390986/93035823-f5072b80-f5f2-11ea-9a57-97086706c6ce.png)
Video: https://cdn.applebee1558.com/2020/09/IYa57ItyL6.mp4

**Comment by RednedEpic** [comment]
Can you try without ProtocolSupport? Someone in the past had this issue and removing that plugin fixed it for them.

**Comment by applebee1558** [comment]
Try this? https://dump.geysermc.org/HzzIJhtaha0yk8ij8gRJ99PINbYFQxVG

**Comment by applebee1558** [comment]
I can't test this in the production server, will get back to you once I bootstrap a testing server

**Comment by applebee1558** [comment]
Yes, its normal without protocolsupport

**Comment by RednedEpic** [comment]
Closing as this appears to be a ProtocolSupport bug.
