### ISSUE TITLE
Error while Bedrock user is not identified with AuthmeReloaded Plugin

### ISSUE THREAD

**Issue by Danifoxe** [GeyserMC/Geyser#1290]
**Describe the bug**
When a user enters the server, while not identifying with AuthmeReloaded, an error is presented in the console. The error also occurs when the user logs out.

**To Reproduce**
1.Bedrock user enters the server
2.AuthmeReloaded asks password to identify itself
3. The console displays the error
4. The error message is kept several times until the user is finished identifying.

**Expected behavior**
Geyser should wait until AuthmeReloaded has finished identifying the user, showing no errors to the console.

**Server Version**
This server is running Paper version git-Paper-195 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**
 Geyser 1.1.0 (git-master-46c3484) ( Java Edition: 1.16.3 Bedrock Edition: 1.16.0 - 1.16.100)

**Minecraft: Bedrock Edition Version**
Bedrock 1.16.40

**Additional Context**
https://dump.geysermc.org/TqDYrgTj107bWGvtoQhzgT8k94wVkIMb

I attach a text document with what is shown in the console
[console.txt](https://github.com/GeyserMC/Geyser/files/5218679/console.txt)

**Comment by soshimee** [comment]
Are you using floodgate?

**Comment by Danifoxe** [comment]
> 
> 
> Are you using floodgate?
Hello.
Yes, i am using.

**Comment by soshimee** [comment]
Try changing the bedrock identification character (in floodgate config) from * to -, * isn't valid for some situations.

**Comment by Danifoxe** [comment]
> 
> 
> Try changing the bedrock identification character (in floodgate config) from * to -, * isn't valid for some situations.

I changed it, and rebooted the server, but the error remains

**Comment by soshimee** [comment]
Looks like AuthMeReloaded is incompatible with special names.

**Comment by Danifoxe** [comment]
> 
> 
> Looks like AuthMeReloaded is incompatible with special names.
> To be sure, what were the errors?

The error is always the same as in the attachment I put. As I said, this ends when the user finishes logging in, after that the error no longer appears.

I will still send you another file with the errors after having made the change you told me.
[console2.txt](https://github.com/GeyserMC/Geyser/files/5219229/console2.txt)

**Comment by soshimee** [comment]
The error seems similar to #1275

**Comment by Danifoxe** [comment]
> 
> 
> The error seems similar to #1275

>
>
> xManInWhitex commented 19 hours ago
>Seems like I solved the problem. I lowered the MTU to 700 and set the scoreboard timer to 5.

Excuse me, a query, I don't understand what he means by **MTU** and **Scoreboard Timer**?
In Scoreboard Timer he perhaps refers to "scoreboard-packet-threshold"?, and of the other I have no idea.

**Comment by soshimee** [comment]
Yes, MTU would be mtu.

**Comment by RednedEpic** [comment]
I'm fairly certain there is a way to tweak which usernames are allowed, but as we do not support piracy here, you are on your own. This is the result of Floodgate prepending an asterisk to the player's username and this is not an issue using online mode.

**Comment by soshimee** [comment]
It's not "blocking," it's "struggling."
