### ISSUE TITLE
Custom NBT tags seem to get cleared when an item is dropped from a mc bedrock client

### ISSUE THREAD

**Issue by fabyanMikhael** [GeyserMC/Geyser#1292]
**Describe the bug**

Custom NBT tags seem to get cleared when an item is dropped from a mc bedrock client. A custom enchant plugin has its enchants removed on drop. Also, when using any chest as a ui there seems to be lots of item duplication happening. 
**To Reproduce**

Get a custom enchant plugin. (GoldenEnchants used)
Enchant an item on a java client and give it to a mc bedrock player.
Once the bedrock player drops the item, its custom enchants get cleared away

**Expected behavior**

NBT tags should be properly copied over before dropping the new instance of item.
**Screenshots / Videos**

**Server Version**

Paper - 196.
Mc 1.16.3
**Geyser Version**

1.1.0
**Minecraft: Bedrock Edition Version**

1.16.20
**Additional Context**

**Comment by DoctorMacc** [comment]
Could you attach a Geyser dump?

**Comment by Comstepr** [comment]
**I have tested this myself and I'm attaching a Geyser dump here**
_This issue does not seem to occur for me_

**Some context**
A item with:
- unbreakable flags
- lore
- item name

**Video** https://youtu.be/mBN8EocjxWs

**Server Version** This server is running Tuinity version git-Tuinity-"58fef63" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Geyser Version** This server is running Geyser version 1.1.0 (git-master-6638c53) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.100)

**Comment by fabyanMikhael** [comment]
> **I have tested this myself and I'm attaching a Geyser dump here**
> _This issue does not seem to occur for me_
> 
> **Some context**
> A item with:
> 
> * unbreakable flags
> * lore
> * item name
> 
> **Video** https://youtu.be/mBN8EocjxWs
> 
> **Server Version** This server is running Tuinity version git-Tuinity-"58fef63" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
> 
> **Geyser Version** This server is running Geyser version 1.1.0 (git-master-6638c53) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.100)

Try it with a custom enchant plugin..... dont use base game nbt tags, and u will see that they dont get properly set on the item entity dropped

**Comment by Comstepr** [comment]
I don't see the difference. Plus, you're missing the Geyser dump and the right Geyser version. Who knows you might've messed with something? Next there is no evidence such as a video or screenshot which makes it harder to diagnose the issue.

**Comment by RednedEpic** [comment]
Item NBT in player inventories is handled serverside, so it sounds like a faulty plugin of some kind or a bug in the enchantment plugin being used. Closing as there is not much we can do in this regard.
