### ISSUE TITLE
Pick block causes invalid hotbar selection

### ISSUE THREAD

**Issue by soshimee** [GeyserMC/Geyser#1294]
**Describe the bug**

When using pick block in a slot where there is already an item, the server kicks the player.

**To Reproduce**

Use pick block.
Pick another block in same slot.
You will be kicked.

**Expected behavior**

The block switching to the newer picked block.

**Screenshots / Videos**

**Server Version**

This server is running Paper version git-Paper-191 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**

This server is running Geyser version 1.1.0 (git-master-6638c53) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.100)

**Minecraft: Bedrock Edition Version**

It was up-to-date but I do not know how to check it.

**Additional Context**

https://dump.geysermc.org/4nHrjZFz5VDRImbRnddEd2lG2zLarynW

**Comment by DoctorMacc** [comment]
Confirmed on Paper. I overlooked as I tested on vanilla.
