### ISSUE TITLE
Support left / right mouse button in chest menu

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Geyser#1296]
**What feature do you want?**
Add a description
The menu of some plugins requires the player to operate the left / right mouse button in the chest menu
(Residence)
**Alternatives?**
List any alternatives you might have tried
Add a command

**Comment by E404NNF** [comment]
that's really not possible because of bedrock limitations

**Comment by zimzaza4** [comment]
> 由于基岩限制，这实际上是不可能的

The right mouse button is used to move items out of chest and the left button to move items into inventory

**Comment by zimzaza4** [comment]
Geyser has supported it, but I didn't find out

> 由于基岩限制，这实际上是不可能的

**Comment by soshimee** [comment]
Try right clicking your phone.

**Comment by E404NNF** [comment]
> Try right clicking your phone.
> And using a command is not really possible if a GUI is open.

Sorry for late reply, that doesn't really work, even on windows 10 edition
