### ISSUE TITLE
"Login failed: Authentication error: Access Token can not be null or empty" (plus better Documentation)

### ISSUE THREAD

**Issue by ROTARTSI82** [GeyserMC/Geyser#13]
First of all, when i try to connect to geyser with mcpe, i get "Login failed: Authentication error: Access Token can not be null or empty." I'm assuming I've been doing something wrong. 
I ran Geyser using `sudo java -jar Geyser.jar` and set the config.yml to reflect the address of the JE server and changed the ip to my local address so i can connect from my iPad. However, trying to connect results in said error. (I can see the error on my JE server logs and my Geyser logs, so my iPad is trying to connect to the Geyser proxy).

Second of all, you should give the link to the precompiled Jenkins site on the GitHub README instead of just on the Discord server. (And also document what Geyser actually is, b/c at first I thought it was a paper plugin like protocol support but for mcpe.)

**Comment by ROTARTSI82** [comment]
Oh yeah. you _could_ fix it by setting the server to offline mode, but I don't want to do that.

**Comment by ROTARTSI82** [comment]
This _could_ be fixed by setting `online-mode=false` in server.properties, but I don't want to do that...

**Comment by RednedEpic** [comment]
Was gonna start on some documentation tonight. As for your bug report, make sure both the remote server and Geyser have online-mode set to true, and you’re typing your credentials in correctly. If your remote server is in offline mode, make sure online-mode for Geyser is false.

**Comment by EOT3000** [comment]
I think this is not an issue anymore
