### ISSUE TITLE
Close teleportations sometimes does not work.

### ISSUE THREAD

**Issue by soshimee** [GeyserMC/Geyser#1303]
**Describe the bug**

Sometimes, when teleporting to a close place (very close, only several blocks), the player does not teleport.

**To Reproduce**

1. Teleport just one block.
2. Player sometimes does not teleport.

**Expected behavior**

Player teleporting.

**Screenshots / Videos**

**Server Version**

This server is running Paper version git-Paper-191 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**

This server is running Geyser version 1.1.0 (git-master-99e72f3) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)
Floodgate used.

**Minecraft: Bedrock Edition Version**

1.16.?

**Additional Context**

https://dump.geysermc.org/M2xtrIudT873bFH9sZETHZWV54LRXhBZ
Also, spectator mode puts the player in their original position if they haven’t moved much in the gamemode.

**Comment by DoctorMacc** [comment]
Thanks for the issue! I'm closing this as this is likely the same issue as #1070 (small teleports are ignored).
