### ISSUE TITLE
The player does not move

### ISSUE THREAD

**Issue by iSilviu-debug** [GeyserMC/Geyser#1307]
**Describe the bug**
When the player changes world / is teleported, he is no longer able to move, indeed he moves on the bedrock but looking at it with the java edition remains motionless.

**Expected behavior**
for the player to move

**Screenshots / Videos**
now I'm on the phone, I would try later

**Server Version**
1.16.3
**Geyser Version**
Geyser version 1.1.0 (git-master-46c3484) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.100)
**Minecraft: Bedrock Edition Version**
1.16.3

**Comment by iSilviu-debug** [comment]
**When the player in the bedrock edition changes world or gets teleported, in the java edition you won't see him move anymore. He still can move on the bedrock but looking at it from the java edition he remains like "motionless" or "stuck".**

**Comment by iSilviu-debug** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/67197594/93462974-62fb6d80-f8e7-11ea-807e-b084f7260d42.gif)

**Comment by RednedEpic** [comment]
Can you please provide a dump?

**Comment by Comstepr** [comment]
@iSilviu-debug You are using an older version of Geyser. The server version is inaccurate, you should use `/version` and give the output. Missing Geyser dump as well.

**Comment by byquanton** [comment]
A player on my server had a similar issue. When a player gets teleported to a spawn of a lobby (while joining) and it isn't a full block he will be sucked at the position on java side. The problem was not happening when teleporting the player some blocks above the spawn.

**Comment by iSilviu-debug** [comment]
> Can you please provide a dump?

https://dump.geysermc.org/DkPYctetoCRyTH1HGOatuInVTHGOOwPb


> @iSilviu-debug You are using an older version of Geyser. The server version is inaccurate, you should use `/version` and give the output. Missing Geyser dump as well.

I updated geyser a few hours ago, same problem

**The problem occurs when the player is on the move and is teleported.**

**Comment by DoctorMacc** [comment]
Thank you for the dump update! However, this branch is not compiled from our master branch, and therefore cannot be guaranteed that it's reproducible on our repository.

**Comment by iSilviu-debug** [comment]
> Thank you for the dump update! However, this branch is not compiled from our master branch, and therefore cannot be guaranteed that it's reproducible on our repository.

where can I download the right file?

**Comment by DoctorMacc** [comment]
https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/

**Comment by iSilviu-debug** [comment]
> https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/

in the end I downloaded it from here and it gives me the same problem

**Comment by DoctorMacc** [comment]
Can you please provide a new dump?

**Comment by iSilviu-debug** [comment]
> Can you please provide a new dump? I'm unable to replicate this.

https://dump.geysermc.org/Czx0keAKvAQqO76hHqzHNaw9xAerPk0j

**Comment by iSilviu-debug** [comment]
Hey? @DoctorMacc ?

**Comment by DoctorMacc** [comment]
This may be a duplicate of #673.

**Comment by Chucky891** [comment]
https://dump.geysermc.org/rj9WSLkq6i95kzSZmMjTSE0OB72skJ28
