### ISSUE TITLE
slot 50 error

### ISSUE THREAD

**Issue by Hellohi3654** [GeyserMC/Geyser#1308]
![image](https://user-images.githubusercontent.com/57390764/93460151-2438d800-f926-11ea-809a-99f052cd8c97.png)

**Comment by Hellohi3654** [comment]
https://dump.geysermc.org/79G3zoorK82hLhbrksFQtgj8nAHDk1tj

**Comment by soshimee** [comment]
Please follow the format.

**Comment by RednedEpic** [comment]
Please follow the issue template.
