### ISSUE TITLE
. is a command prefix

### ISSUE THREAD

**Issue by soshimee** [GeyserMC/Geyser#1309]
**Describe the bug**

. is a command prefix, for example, if a player types .command, it is equivalent of typing /command.

**To Reproduce**

Try to send any message that starts with . (which I often do).

**Expected behavior**

. being sent out in chat, instead of being a command.

**Screenshots / Videos**

**Server Version**

This server is running Paper version git-Paper-191 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**

This server is running Geyser version 1.1.0 (git-master-99e72f3) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)
Floodgate is used.

**Minecraft: Bedrock Edition Version**

1.16.?

**Additional Context**

https://dump.geysermc.org/S5lpPpcsuNDOOlfMgdryto5hsh9THfGE

**Comment by RednedEpic** [comment]
This is intended as some commands (/help for example) are overriden by the Bedrock client.

**Comment by soshimee** [comment]
Any way to disable it? Everyone thinks it's annoying and not intended.
