### ISSUE TITLE
Form API Support

### ISSUE THREAD

**Issue by Papadoubulus** [GeyserMC/Geyser#1312]
**What feature do you want?**
Add a description

being able to use formapi from nukkit on spigot would be useful for mobile phone gamers

**Alternatives?**
List any alternatives you might have tried

or that the chestgui in spigot is made a little easier, which means that as a mobile phone player you only have to press the item and not pull it out

**Comment by RednedEpic** [comment]
This is something being implemented in Floodgate 2.0, and an issue for that on the Floodgate issue already exists [here](https://github.com/GeyserMC/Floodgate/issues/36).
