### ISSUE TITLE
Bugs with unkillable and end screen

### ISSUE THREAD

**Issue by Skrayvee** [GeyserMC/Geyser#1313]
Hello
I nned help
When someone dies from the phone, the enemies become immortal and run lying down, on the part of Java there are no such problems:
https://prntscr.com/uicsob

And then there's the endless screen of death.
https://prntscr.com/uicrvj

But the player for others stands and collects resources

It's Screaming BedWars

To Reproduce
1. Play to bedwars
2. Suicide
 3. See error

Geyser Version

**Minecraft: Bedrock Edition Version**
1.16.1.

**Comment by DoctorMacc** [comment]
Please provide a Geyser dump.

Optionally, what would be super helpful is a premade Screaming BedWars map and configuration.

**Comment by Noah7563** [comment]
Umm it's not the same problem with from but it's similar
When a player dies sometimes he is stuck in the end can't move and chat 
Or if he logs out in end he relog he gets stuck in end as the same problem it doesn't happens all time but most of time

**Comment by Skrayvee** [comment]
Sorry, but I now can't send dump

**Comment by Comstepr** [comment]
I've used ScreamingBedWars before on my server with Geyser, haven't received this report before.

**Comment by DoctorMacc** [comment]
What version did you use? I have heard of something like this once before.

**Comment by Comstepr** [comment]
Cant remember. Stopped using it since then

**Comment by DoctorMacc** [comment]
Does this still persist in the latest Geyser?

**Comment by Skrayvee** [comment]
Unfortunately I still can't verify it, I'll be able to do it on Thursday.

**Comment by RednedEpic** [comment]
Shortly after this issue was made, we put in a fix for respawns and have not received any reports of this further. As OP has not responded to this issue and due to the fact that we've not received reports on this further, I am going to close this issue. If this continues to occur, please feel free to state so on this issue with a video and I'll reopen it.
