### ISSUE TITLE
Planting seeds/crops while sprinting causes some crops to appear planted on client but not on server

### ISSUE THREAD

**Issue by colinsantos** [GeyserMC/Geyser#1315]
**Describe the bug**
When planting crops on Bedrock while sprinting, the crops appear visually as planted on the Bedrock client but some of the planted crops don't actually update on the server side.

**To Reproduce**
1. Get some seeds/crops
2. Plant the seeds on tilled dirt while sprinting
3. Once the seeds have been planted, exit the server
4. Rejoin the server (there should be some blocks where no seeds appear to be planted)

**Expected behavior**
All the planted seeds should be updated on the server and appear when reconnecting to the server.

**Screenshots / Videos**
https://www.youtube.com/watch?v=EmMxePJBkbo

**Server Version**
git-Paper-202 (MC: 1.16.3)

**Geyser Version**
Geyser version 1.1.0 (git-master-5fafa07) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)
(Geyser standalone)

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
https://dump.geysermc.org/MgMj9MXYrjVXAVawvTJcLd5OKeKNDjpO

**Comment by Kooldude183** [comment]
This also happens with other blocks like torches, rails, etc.

**Comment by onebeastchris** [comment]
Does this still occur on the latest version of Geyser? Haven't been able to reproduce it.

**Comment by onebeastchris** [comment]
Closing due to no response. If this bug is still reproducible, please open a new issue
