### ISSUE TITLE
Your username contains illegal characters.

### ISSUE THREAD

**Issue by ZerataX** [GeyserMC/Geyser#1316]
**Describe the bug**
When trying to connect with a bedrock client to an offline java server with geyser and floodgate, I can't join and get immediately disconnect with the error: `Your username contains illegal characters  Allowed chars: [a-zA-Z0-9_]*`

But my username is `m0jibake`, which should fit perfectly to that regex, no?

**To Reproduce**
1. install geyser and floodgate
2. set geyser auth mode to floodgate
3. floodgate enable account linking
4. restart server
5. join server with a bedrock client

**Expected behavior**
I join the server

**Screenshots / Videos**
![error](https://user-images.githubusercontent.com/5024958/93712522-b3c4cd80-fb56-11ea-81fb-de2d9aca436a.png)

**Server Version**
git-Paper-202 (MC:1.16.3)

**Geyser Version**
1.1.0 (git-master-5fafa07)

**Minecraft: Bedrock Edition Version**
v.1.16.40 windows 10 and android

**Additional Context**
https://dump.geysermc.org/VobURCfL9zcYxsSd5ydAr1jCu50XEmAm

```
Sep 20 15:24:57 phantom.dmnd.sh java[5597]: [15:24:57 INFO]: [Geyser-Spigot] /redacted:65223 tried to connect!
Sep 20 15:24:58 phantom.dmnd.sh java[5597]: [15:24:58 INFO]: [Geyser-Spigot] Player connected with username m0jibake
Sep 20 15:25:03 phantom.dmnd.sh java[5597]: [15:25:03 INFO]: [Geyser-Spigot] Attempting to login using floodgate mode... authentication will be encrypted.
Sep 20 15:25:03 phantom.dmnd.sh java[5597]: [15:25:03 INFO]: [Geyser-Spigot] Loaded Floodgate key!
Sep 20 15:25:03 phantom.dmnd.sh java[5597]: [15:25:03 INFO]: [Geyser-Spigot] m0jibake (logged in as: m0jibake) has connected to remote java server on address 127.0.1.1
Sep 20 15:25:03 phantom.dmnd.sh java[5597]: [15:25:03 INFO]: [floodgate-bukkit] Added *m0jibake 00000000-0000-0000-0009-01f46db1fa18
Sep 20 15:25:03 phantom.dmnd.sh java[5597]: [15:25:03 INFO]: Disconnecting com.mojang.authlib.GameProfile@3b46a637[id=00000000-0000-0000-0009-01f46db1fa18,name=*m0jibake,properties={},legacy=false] (/redacted:42620): Your username contains illegal characters. Allowed chars:
Sep 20 15:25:03 phantom.dmnd.sh java[5597]: [15:25:03 INFO]: [Geyser-Spigot] m0jibake has disconnected from remote Java server on address 127.0.1.1 because of Your username contains illegal characters. Allowed chars: [a-zA-Z0-9_]*
Sep 20 15:25:03 phantom.dmnd.sh java[5597]: [15:25:03 INFO]: com.mojang.authlib.GameProfile@3b46a637[id=00000000-0000-0000-0009-01f46db1fa18,name=*m0jibake,properties={},legacy=false] (/redacted:42620) lost connection: Your username contains illegal characters. Allowed chars
Sep 20 15:25:03 phantom.dmnd.sh java[5597]: [15:25:03 INFO]: [Geyser-Spigot] Bedrock user with ip: /redacted has disconnected for reason CLOSED_BY_REMOTE_PEER
```

**Comment by rtm516** [comment]
Please change the below in your authme config, we also wont offer any more support as we don't support nor condone piracy.
```
allowedNicknameCharacters: '[a-zA-Z0-9_]*'
in your AuthMe config should be changed to
allowedNicknameCharacters: '\*?[a-zA-Z0-9_]*'
```

**Comment by GianLucky08** [comment]
> Please change the below in your authme config, we also wont offer any more support as we don't support nor condone piracy.
> 
> ```
> allowedNicknameCharacters: '[a-zA-Z0-9_]*'
> in your AuthMe config should be changed to
> allowedNicknameCharacters: '\*?[a-zA-Z0-9_]*'
> ```

I tried to do what rtm516 says and I still get the same error, is there another solution?

**Comment by Chew** [comment]
That's very outdated because it uses floodgate's old config. I believe you just need to replace `\*?` with `\.?` and it'll work. If you have further issues, please hop on [Discord](https://discord.gg/geysermc) to prevent bumping this old issue.

**Comment by TGZJDV666** [comment]
修改fullgate的配置文件，默认设置会在用户名前面加“.”
