### ISSUE TITLE
knowlege book recipes broken

### ISSUE THREAD

**Issue by DabbingEevee** [GeyserMC/Geyser#1317]
**Describe the bug**
i was playing a datapack with a friend when he realized that he can not craft the jewlary table due to the datapacks uniqu custom crafting stratagy. the datapack crafts a knowlege book that disappears and makes a item. 

**To Reproduce**
install The Creeper's Code datapack
on a geyser client, attempt to craft jewlary table.

**Expected behavior**
the jewlaryy table gets crafted

**Screenshots / Videos**

**Server Version**
1.16.3 paper

**Geyser Version**
Geyser version 1.1.0 (git-master-5fafa07)

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**

**Comment by DoctorMacc** [comment]
Please provide a Geyser dump. A direct link to the datapack would also be appreciated.

**Comment by DabbingEevee** [comment]
https://thecreeperscode.com/download/
https://dump.geysermc.org/cYWo8eS4I3tHaorAj4RxqmQsn9adYZpX

**Comment by RednedEpic** [comment]
Superseded by #1571.
