### ISSUE TITLE
Java player rendering issue

### ISSUE THREAD

**Issue by Wolfalpha360** [GeyserMC/Geyser#1319]
**Describe the bug**
If a minecraft java player goes out of the render distance of the bedrock player then comes back in the java player does not render again for the bedrock player making it to where only the java player can see the bedrock player.

**To Reproduce**
Have the java player go far out of view distance and come back

**Expected behavior**
after not rendering the java player they don't get rendered again

**Screenshots / Videos**
links to images
 java players view                    https://ibb.co/5rgsx13
 bedrock players view             https://ibb.co/bjV85Q1

**Server Version**
the server version is 1.16.3

**Geyser Version**
newest ver 1.16.3

**Minecraft: Bedrock Edition Version**
1.16.4

**Additional Context**
No plugins or error messages

**Comment by DoctorMacc** [comment]
Please provide a Geyser dump.

**Comment by Wolfalpha360** [comment]
what is that

**Comment by DoctorMacc** [comment]
Run `/geyser dump` and provide the output of that.

**Comment by Wolfalpha360** [comment]
ok

**Comment by Wolfalpha360** [comment]
https://dump.geysermc.org/chsgxrqPtF4HRFZMORIbCQD2wZtckbG6

**Comment by DoctorMacc** [comment]
You're running an old build of Geyser. Please download a build from https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/ as we have fixed this.

**Comment by Wolfalpha360** [comment]
thx
