### ISSUE TITLE
Disconnection from server when touching honey block

### ISSUE THREAD

**Issue by 1MagicSweet** [GeyserMC/Geyser#132]
**Describe the bug**
A disconnection from server when touching honey block

**To Reproduce**
1. Touch the honey block (and try to slide down or jump on it)
2. Get the crash with error 'io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value 53 has no mapping for key class com.github.steveice10.mc.protocol.data.game.entity.EntityStatus.'

**Expected behavior**
A normal Honey Block's behavior

**Screenshots**
![Annotation 2020-01-07 012734](https://user-images.githubusercontent.com/49122140/71853623-0fe0e200-30ed-11ea-83d3-25f06d436635.jpg)
![Annotation 2020-01-07 012750](https://user-images.githubusercontent.com/49122140/71853625-0fe0e200-30ed-11ea-8d02-729e20bacfe0.jpg)
![Annotation 2020-01-07 012759](https://user-images.githubusercontent.com/49122140/71853626-0fe0e200-30ed-11ea-9481-858567ddb783.jpg)
![Annotation 2020-01-07 012814](https://user-images.githubusercontent.com/49122140/71853627-10797880-30ed-11ea-9afd-e3de9109725f.jpg)

**Server version**
git-Paper-33 (MC: 1.15.1)

**Geyser version**
Build #159 from Dec 31

**Bedrock version**
1.14.1

**Comment by RednedEpic** [comment]
> **Describe the bug**
> A disconnection from server when touching honey block
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Touch the honey block (and try to slide down or jump on it)
> 2. Get the crash with error 'io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value 53 has no mapping for key class com.github.steveice10.mc.protocol.data.game.entity.EntityStatus.'
> 
> **Expected behavior**
> A normal Honey Block's behavior
> 
> **Screenshots**
> ![Annotation 2020-01-07 012734](https://user-images.githubusercontent.com/49122140/71853623-0fe0e200-30ed-11ea-83d3-25f06d436635.jpg)
> ![Annotation 2020-01-07 012750](https://user-images.githubusercontent.com/49122140/71853625-0fe0e200-30ed-11ea-8d02-729e20bacfe0.jpg)
> ![Annotation 2020-01-07 012759](https://user-images.githubusercontent.com/49122140/71853626-0fe0e200-30ed-11ea-9481-858567ddb783.jpg)
> ![Annotation 2020-01-07 012814](https://user-images.githubusercontent.com/49122140/71853627-10797880-30ed-11ea-9afd-e3de9109725f.jpg)
> 
> **Server version**
> git-Paper-33 (MC: 1.15.1)
> 
> **Geyser version**
> Build #159 from Dec 31
> 
> **Bedrock version**
> 1.14.1

Thanks for the detailed report, should have this resolved in the next few hours.

**Comment by RednedEpic** [comment]
Resolved in Steveice10/MCProtocolLib#508. Once this gets merged and Geyser gets rebuilt, this issue will be closed. For the time being, if you want this fix now, just compile [GeyserMC/MCProtocolLib](https://github.com/GeyserMC/MCProtocolLib) yourself.
