### ISSUE TITLE
Can't drink milk

### ISSUE THREAD

**Issue by MagnoBooter** [GeyserMC/Geyser#1321]
**Describe the bug**
When drinking a bucket of milk, the milk-drinking animation is shown and heard, but the milk is not consumed and any unwanted status effect is not removed.

**To Reproduce**

1. Bring a bucket of milk with you, and find a mob causing a harming status effect. You could go visit a witch, or wave to a wither skeleton.
2. Let the mob harm you, causing the effect. Now drink the bucket of milk.
3. Yummy, that was tasty, and the bucket doesn't empty, you even get to keep the status effect. Lucky you. :smile: 

**Expected behavior**
The status effect should disappear and the bucket should empty.

**Screenshots / Videos**
_Should not be necessary to understand the problem._

**Server Version**
Paper version git-Paper-202 (MC: 1.16.3)

**Geyser Version**
1.1.0 (git-master-5fafa07)

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**

[Geyser Dump](https://dump.geysermc.org/kO7WEkimT6XLBq7RTduspBbFC5lAsszF)

**Comment by DoctorMacc** [comment]
Would you mind also providing a Geyser dump?

**Comment by MagnoBooter** [comment]
Sure, sorry for the delay! :flushed:

**Comment by DoctorMacc** [comment]
It's a feature™️

**Comment by soshimee** [comment]
> It's a feature™️

Everything is a feature before they are fixed. 🤣
