### ISSUE TITLE
Chunks don't load in some areas when render distance is set to 32

### ISSUE THREAD

**Issue by ChargerSRT64** [GeyserMC/Geyser#1322]
**Describe the bug**
Specific areas of chunks won't load for bedrock clients. It is usually a rectangle then extents diagonally. animals will spawn and i can break some of the "invisible blocks" (their outlines show). If I keep going into the unloaded chunks, I will hit something (even when flying high over an ocean). The chunks in that area often switch between loaded and unloaded around the edge.

**To Reproduce**
1. Join proxy server from Bedrock
2. Fly around in creative mode
3. You should eventually find an unloaded area (usually within a min or two)

**Expected behavior**
All chunks loading in reasonable time

**Screenshots / Videos**
![Screenshot (98)](https://user-images.githubusercontent.com/71677227/93834854-ecda6c00-fc42-11ea-9243-47797f562164.png)
![Screenshot (99)](https://user-images.githubusercontent.com/71677227/93834858-eea42f80-fc42-11ea-8e59-0ac327483260.png)
![Screenshot (100)](https://user-images.githubusercontent.com/71677227/93834867-f82d9780-fc42-11ea-9051-cd086b447056.png)
![Screenshot (101)](https://user-images.githubusercontent.com/71677227/93834870-f95ec480-fc42-11ea-8efb-6910ac2ed153.png)

**Server Version**
Paper-203 
Java 1.16.3 (first noticed shortly after updating to 1.16.2 and latest geyser build at the time)

**Geyser Version**
geyser-spigot build #395 but has been doing it in previous builds

**Minecraft: Bedrock Edition Version**
1.16.40 Build 4641649

**Additional Context**
Problem also occurs on the bungeechord version using waterfall. It persisted after running a template server with no other plugins except geyser and floodgate. Console does not output any errors. Async chunk loading enabled.

**Comment by DoctorMacc** [comment]
Could you provide a Geyser dump?

Does relogging Bedrock fix the problem?

Did you switch your render distance by chance?

Are there any errors in your server console?

**Comment by ChargerSRT64** [comment]
https://dump.geysermc.org/YXCdyC535GGEbzZGweGJ5B1co54KU2EM

Relogging or tping away and back fixes that instance but it just happens again later in a different location.

The server render distance was changed from 32 to 16 but i dont remember if that was before or after the problem started. i was using a 32 render on client but setting it to 16 did nothing.

The only errors are warnings for loading floodgate and empty scan urls when the server starts.

**Comment by DoctorMacc** [comment]
Could you try updating Paper? I'm curious if it has to do with their chunk changes which occured from 200-203 before it was reverted.

**Comment by ChargerSRT64** [comment]
does the same in 204 but i think i had 168 when i first noticed

**Comment by DoctorMacc** [comment]
On the latest Geyser-Spigot with Paper 191 I had no issues but it could be a render-distance-specific bug.

So your client render distance can be either 32 or 16, and your server render distance is 16?

**Comment by ChargerSRT64** [comment]
I rechecked the properties and the server was set to 32. changing it to 16 fixes it. i tested on a fresh server as well and the issue persists on 32 render distance but not 16.

**Comment by DoctorMacc** [comment]
OK, I was able to confirm on vanilla with render distance set to 32. We have a PR where if you change the render distance on the client, a similar effect happens: https://github.com/GeyserMC/Geyser/pull/1020

**Comment by DoctorMacc** [comment]
@ChargerSRT64 if you're still active, could you try PR #1546? Feel free to join our Discord for assistance with downloading it.
