### ISSUE TITLE
Timed_Out while AFK after 30 mins(roughly)

### ISSUE THREAD

**Issue by EuanM199** [GeyserMC/Geyser#1327]
**Describe the bug**
After a amount of time is passed on any bedrock Server client is timed out from server, have reproduced on both my server and on the official geyser Test server, Thanks to @DoctorMacc 

This only happens when the player is AFK, players Playing do not have this issue

**To Reproduce**
1 Go on any server you want
2 Wait
3 check console for timed out
4 Cry

**Expected behavior**
Player Stays afk and is not kicked .

**Screenshots / Videos**
 N/A. 

**Server Version**
1.16.3. 

**Geyser Version**
 Geyser Build 398, Floodgate Build 25. 

**Minecraft: Bedrock Edition Version**
1.16.4

**Additional Context**
N/A

**Comment by DoctorMacc** [comment]
I can confirm that I experienced this issue but have yet to try to reproduce it.

**Comment by DoctorMacc** [comment]
`[Essentials] Permissions lag notice with (LuckPermsHandler). Response took 36.869931ms. Summary: Getting prefix for *Madlad2741` this occurred 36 seconds before the disconnect.

**Comment by EuanM199** [comment]
Yes, i have that on my server too, happens to both Bedrock and java players, didnt see it before disconnect tho, only when the player joins

**Comment by DoctorMacc** [comment]
Can you attach your own Geyser dump? Perhaps it's something with a specific server type.

**Comment by EuanM199** [comment]
https://dump.geysermc.org/3YQZk9TLtGu8BgAYR6DNLZG87KmTn500

**Comment by DoctorMacc** [comment]
Is this still an issue?

**Comment by RednedEpic** [comment]
Should be resolved by 70031c65e778c5ae277c504d50768f9ad1e38932. Closing for now, but if you continue to experience this bug, please state so here and I will reopen the issue.
