### ISSUE TITLE
Scoreboard not going away completely 

### ISSUE THREAD

**Issue by LightBotDiscoord** [GeyserMC/Geyser#1328]
**Describe the bug**
The scoreboard does not go away completely on bedrock, but on java it does.

**To Reproduce**

1.  Use a map that uses scoreboards
2.  Get to the part when the scoreboard is supposed to go away
3.  Watch as the title (In this case, "Custom Settings) doesn't go away but the things below it (in this case, "Impostors") do.
4.  cry

**Expected behavior**
The scoreboard title "Custom Settings" should go away, but don't.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/67489949/93966143-d30b5880-fd18-11ea-8987-df602a6aba93.png)
Picture above is before game start
![image](https://user-images.githubusercontent.com/67489949/93966602-f4207900-fd19-11ea-9a83-185302c57d78.png)
Picture above is after the game started.

**Server Version**
Vanilla 1.16.3

**Geyser Version**
Geyser Standalone Build 398

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
https://dump.geysermc.org/DsUi6LVzawGp8mpOZa2mWNfjeJQdVOe6

**Comment by Grizzly90** [comment]
we can confirm that issue.

same geyser but as bungee and floodgate
