### ISSUE TITLE
enchantment wont show on bedrock but will on java

### ISSUE THREAD

**Issue by thisisafakeacount** [GeyserMC/Geyser#133]
**Describe the bug**
the proxy won't display the name list for enchantment but the enchantments will still work

**To Reproduce**
1. join your server on java and put enchantments on items
2. join on bedrock minecraft
3. hold the item
4. the enchantments are not shown

**Expected behavior**
it should show the same or similar enchantments as on java minecraft

**Screenshots**
1.12 java
![java](https://user-images.githubusercontent.com/59156790/71856937-77ba0d00-309a-11ea-824f-23a1e439b0ad.PNG)
bedrock 1.14.1.5
![bedrock](https://user-images.githubusercontent.com/59156790/71856947-80aade80-309a-11ea-8f64-c275fe80fde1.PNG)

**Server version**
run / version

1.12.2 with spigot
plugins:
FastAsyncWorldEdit-bukkit-19.07.12-5cc5ce5-1277-22.3.0
viabackwards-all-2.4.0-SNAPSHOT
ViaVersion-2.2.2
ViaRewind-1.4.5
worldedit-bukkit-6.1.9 (3)

**Geyser version**
1.0-SNAPSHOT

**Bedrock version**
The version of your Minecraft pe
bedrock 1.14.1.5

**Comment by RednedEpic** [comment]
Fixed in #67.

**Comment by thisisafakeacount** [comment]
wow your qwick

**Comment by RednedEpic** [comment]
Implemented in inventory branch.
