### ISSUE TITLE
Custom Buttons for inventories

### ISSUE THREAD

**Issue by NidzGamingTV** [GeyserMC/Geyser#1332]
**What feature do you want?**
I want an additional button for left and right click because some of the servers requires right click to sell items in shop but holding an item doesn't work to trigger right click.

**Alternatives?**
I've tried keymapper but it doesn't work on right clicking

**Comment by DoctorMacc** [comment]
There's really no place we can add these buttons.

**Comment by soshimee** [comment]
Could be the sixth row in large chest guis

**Comment by EasyClifton** [comment]
And if that's in use?

**Comment by NidzGamingTV** [comment]
How about 

> There's really no place we can add these buttons, unfortunately.

How about an addon support?

**Comment by NidzGamingTV** [comment]
I remember the addon that i used before its called fast change button Addon here's the link
https://mcpedl.com/fast-change-button/?cookie_check=1

Maybe add an Addon support to the geyser and change this 2 buttons to left and right click
![Uploading fast-change-button-2.jpg…]()

**Comment by NidzGamingTV** [comment]
It is also useful for flying using rockets

**Comment by soshimee** [comment]
> And if that's in use?

> open another gui when clicked.

**Comment by RednedEpic** [comment]
Bedrock limitation, not much we can do here.
