### ISSUE TITLE
Geyser Auto Update

### ISSUE THREAD

**Issue by RehanPlayz** [GeyserMC/Geyser#1333]
**What feature do you want?**
A way for Geyser To Automatically Download the Latest Update (On Restart) 

**Alternatives?**
Manually Updating?

**Comment by RehanPlayz** [comment]
(Using a API or Something)

**Comment by soshimee** [comment]
I don't think it's a good idea...

**Comment by RehanPlayz** [comment]
(As an Option)Rehan-------- Original Message --------Subject: Re: [GeyserMC/Geyser] Geyser Auto Update (#1333)From: soshimee To: GeyserMC/Geyser CC: RehanPlayz ,Author 
I don't think it's a good idea...

**Comment by NekoMeowy** [comment]
i think is a good idea !
i don't need to download Geyser from ci and replace the Server files to update Geyser to latest version !

**Comment by RehanPlayz** [comment]
If this is going to be implemented, it should be a config option

**Comment by 1creeperbomb** [comment]
Just setup a script to pull the latest build from Jenkins if you really want to.

They're making builds every few hours sometimes and I usually wait until the end of the week to check which bugs have been fixed etc. before updating.

**Comment by JammSpread** [comment]
We could simply use an input stream for the Jenkins latest build. We could probably make a separate jar for it.

**Comment by JammSpread** [comment]
We could create a separate archive for the updater that the main archive starts. It would probably open an input stream from the   Jenkins latest build, passing what type of artifact it is.

**Comment by JammSpread** [comment]
The artifacts are pretty heavy so we should use a command and auto-updating might not make sense. Although telling the user that it needs updating or critical updates might work.
Could use a config option for these messages.
Also, maybe we can host a file that says whether or not there is an update (maybe holds other data too) and accordingly download new artifacts from Jenkins.

**Comment by JammSpread** [comment]
Although (https://github.com/GeyserMC/Geyser/pull/1335) has some of it worked out, maybe instead make it a separate updater archive.

**Comment by snaildos** [comment]
I think this is a perfect idea, it should be disabled by default and only updates for main releases, not micro fixes that cause more bugs.
Eh, That's just me.

**Comment by bobhenl** [comment]
Hi, I agree, how it looks with it please?

**Comment by RehanPlayz** [comment]
Oh Haven't seen all the replies....

**Comment by bobhenl** [comment]
Don't you wanna suggest them it on Discord that it has so positive replies? :D May they'll implement it after few months finally

**Comment by RehanPlayz** [comment]
Sure

**Comment by Chew** [comment]
No dev input so I should give mine. Auto-update is a bad idea. If anything, there should be a `/geyser update` that updates the JAR on restart. If something goes wrong in a build, anyone and everyone who uses auto-update will be affected (it's happened on Paper a few times). It's a good idea, but bad in practicality.

**Comment by Camotoy** [comment]
The only difference with Geyser is that we can't break a setup permanently.

**Comment by bobhenl** [comment]
But yea at least /geyser update please, but I still think if something broke, then it will get fixed after restart... same as people can download it broken in exact moment and also download fix and restart, so it's almost same if you update it automatically or manually to broken build.

**Comment by YHDiamond** [comment]
Someone is working on this, I don't know if this will be added though.

**Comment by RednedEpic** [comment]
Thanks for the suggestion, however this is not something we intend to implement into the main project. You can see whether you are out of date in the `/geyser version` command. Regardless, thanks for the suggestion!
