### ISSUE TITLE
Chat clickable link support

### ISSUE THREAD

**Issue by Camotoy** [GeyserMC/Geyser#1340]
**What feature do you want?**
Currently Bedrock simply has no support for URLs/running commands in chat. This is being put up as a possible discussion of getting around that.

**Alternatives?**
Not sure of any alternatives at this point.

**Comment by E404NNF** [comment]
Maybe send the links and stuff in chat? I know that's a bad workaround but it works™

**Comment by lukeeey** [comment]
It doesn't, a lot of servers have a click event that will run a command or something

**Comment by TOWUK** [comment]
join and confirm, waiting for support for clicks in the chat!

**Comment by TOWUK** [comment]
fawe use this function (**load schem** and **schem list** example)

**Comment by soshimee** [comment]
Maybe interactive chat gui or something.

**Comment by lukeeey** [comment]
That's not possible

**Comment by soshimee** [comment]
I mean, replacing chat with separate GUI.

**Comment by EOT3000** [comment]
Log the hover events in geyser, so that when for example hypixel sends "Join party- click here", it is replaced with something like "Join party- click here (or run /hoverevent a)". When the player does run /hoverevent a , the stored command is run in place of it?

**Comment by strubbe06** [comment]
Java uses plain tellraw to do clickable chat

Example.
“/tellraw @a {"text":"clickable","clickEvent":{"action":"run_command","value":"/say done"}}”

If geyser can read the {“text”:} portion of the tellraw there could be a “/select” command setup where (in this case) you could type “/select clickable”, and it would run the action.

If there are multiple of the same clickevents with the same {“text”:} there could be a way to order them by appearance, Ex. “/select clickable 1”, “/select clickable 2”

To save time you could select with only the first few letters maybe? Like “/select cl 1”? (To make it easier it can just auto select the first tellraw that appeared so they dont have to type in a number everytime)

**Comment by Hellohi3654** [comment]
> Java uses plain tellraw to do clickable chat
> 
> Example.
> “/tellraw @A {"text":"clickable","clickEvent":{"action":"run_command","value":"/say done"}}”
> 
> If geyser can read the {“text”:} portion of the tellraw there could be a “/select” command setup where (in this case) you could type “/select clickable”, and it would run the action.
> 
> If there are multiple of the same clickevents with the same {“text”:} there could be a way to order them by appearance, Ex. “/select clickable 1”, “/select clickable 2”
> 
> To save time you could select with only the first few letters maybe? Like “/select cl 1”? (To make it easier it can just auto select the first tellraw that appeared so they dont have to type in a number everytime)

Using this method you could choose which clickable link you want to press using "/select clickable 1 or 2" then display the link as a command auto correct or paste the link into the command section (whichever is possible) so that the player can copy the link and paste it in a web browser

**Comment by TOWUK** [comment]
is it possible to make a resource pack for integration with geyser and java chat + make it mandatory? it will be located in the geyser resource packs folder

**Comment by NovaPixell** [comment]
Hello! have you found solutions? I would need support for clickable links in chat

**Comment by EasyClifton** [comment]
This won't be possible to implement so it works like in java unless it gets implemented into bedrock. We are yet do decide how we want to work around this.

**Comment by NovaPixell** [comment]
Exists a solution that I will implement this with a plugin?

**Comment by Tim203** [comment]
No, this is a Bedrock limitation. It isn't possible to implement this with a plugin.

**Comment by NovaPixell** [comment]
bedrock does not allow opening of links. right?

**Comment by Hellohi3654** [comment]
> > Java uses plain tellraw to do clickable chat
> > Example.
> > “/tellraw @A {"text":"clickable","clickEvent":{"action":"run_command","value":"/say done"}}”
> > If geyser can read the {“text”:} portion of the tellraw there could be a “/select” command setup where (in this case) you could type “/select clickable”, and it would run the action.
> > If there are multiple of the same clickevents with the same {“text”:} there could be a way to order them by appearance, Ex. “/select clickable 1”, “/select clickable 2”
> > To save time you could select with only the first few letters maybe? Like “/select cl 1”? (To make it easier it can just auto select the first tellraw that appeared so they dont have to type in a number everytime)
> 
> Using this method you could choose which clickable link you want to press using "/select clickable 1 or 2" then display the link as a command auto correct or paste the link into the command section (whichever is possible) so that the player can copy the link and paste it in a web browser

What I suggested here is really the only way to add it

**Comment by Hellohi3654** [comment]
But I don't know if that is even possible

**Comment by EasyClifton** [comment]
> bedrock does not allow opening of links. right?

No, you just can't click things in chat on bedrock.

**Comment by Hellohi3654** [comment]
There is another way to do this

If you replaced the chat window with a form you could just add buttons allowing players to select a link to click on then you could either set the link as a command auto correct or send the link to the player in chat

**Comment by rhld16** [comment]
But they still wouldn't be able to open the link...

**Comment by Hellohi3654** [comment]
But at least the player can see the link

**Comment by Hellohi3654** [comment]
Bedrock can't open links in chat

**Comment by YodaLightsabr** [comment]
> I mean, replacing chat with separate GUI.

+1 Yes. Just. Yes. If you've ever played Minecraft: Bedrock Edition featured servers, you'll know that they have that GUI type thing with a list of buttons. Geyser could make a command called `/chatgui` that allows you to view all the links that were sent in the chat, and fire the click event when the Bedrock player clicks a button.

**Comment by NovaPixell** [comment]
Yea please, make it. I really need!

**Comment by Chew** [comment]
@NovaPixell  Please avoid pointlessly bumping issues. GitHub has reactions for this very reason.

**Comment by RednedEpic** [comment]
Adding to wiki as bedrock limitation. Closing.

**Comment by TerdyTheTerd** [comment]
Just noting as I poke around the github: This is still listed under the Geyser Project Board for missing client features "We should attempt to find workarounds for these issues." since there appears to be no future attempt at workarounds for this it shouldn't be listed under that board either. I had gotten excited when I saw it there before realizing it's been long closed and forgotten about.

**Comment by DJelly4K** [comment]
Maybe it is possible to detect the clickable command and open the interface of click information through a new command /geyser click, which players can use by corresponding text and click content?

Or... 1.19's copy coordinate ui can help...?

**Comment by Xiang990293** [comment]
I don't know why, but I can't click the text and run command on java, copy to clipboard work fine to me.

**Comment by Camotoy** [comment]
That does not sound like our issue - Geyser nor Floodgate should modify Java player behavior in that manner.
