### ISSUE TITLE
The option to be able to sign into a Java Edition Account, or stay as a Bedrock Edition user.

### ISSUE THREAD

**Issue by PatMillman** [GeyserMC/Geyser#1345]
**What feature do you want?**
I would like an option to be added to Geyser, where players of a server have the option to either sign into a Java Edition Account if they have one, or stay logged in with their bedrock account. This could come in handy for those who want to play on one world, with multiple devices and not have to constantly give their items to the other player. 

**Alternatives?**
I tried using Floodgate, as it looked like that would've done the trick. I was mistaken, though.

**Comment by toinouH** [comment]
use the command `/linkaccount`
You can close the issue now ^^
