### ISSUE TITLE
Grief Prevention - Hard to claim

### ISSUE THREAD

**Issue by RaspberryTech01** [GeyserMC/Geyser#1347]
Bedrock users find it hard to claim. Takes several tries to make a claim. It seems to glitch out. Not sure if this is geysers problem, but it works on java edition.

**Comment by TOWUK** [comment]
подробнее можете описать проблему, и написать по форме?
you can describe the problem in more detail, and write in the form?

**Comment by DoctorMacc** [comment]
Thank you for reporting! However, please follow the given issue template.
