### ISSUE TITLE
 Add support for "virtual" books

### ISSUE THREAD

**Issue by nussaleo** [GeyserMC/Geyser#1351]
**What feature do you want?**

In my tests to use the geyser, I noticed that it does not support plugins that use virtual books (Examples: Slimefun, VirtualBooks, InteractiveBooks, CitizensBooks, etc ...)

I think it is not a complicated thing to solve, and it would be great to have support for these books in the geyser for players to see interesting and creative things.

**Alternatives?**

In fact I tested all the plugins I mentioned above, none of them showed the virtual books to those who were in bedrock, while it worked normal for those who were in java.

**Comment by MrZomka** [comment]
Probably won't be possible because from what I know Bedrock doesn't have this feature.

**Comment by DoctorMacc** [comment]
It's possible with a workaround, I think - if we can put a lectern above the player and close it when they're done reading, that would work.

**Comment by Leomello** [comment]
My suggestion is more for the advantage of showing the text, the interactive json part I already know that there is no way.

all the plugins I mentioned above have support for placeholder api for example, which is quite fun creating informative books and etc ...

**Comment by SnickoDeadMC** [comment]
> 

I would love to know how to do this. I have tried:

`			player.getLocation().add(0,2,0).getBlock().setType(Material.LECTERN);
			player.openBook(book);`

Is that what you mean?

**Comment by Camotoy** [comment]
The workaround was potentially as a Geyser-side fix. But, I don't think it would work in hindsight.

**Comment by xttlegend** [comment]
Please fix this:)
