### ISSUE TITLE
Bedrock not joining Java server

### ISSUE THREAD

**Issue by Higa9** [GeyserMC/Geyser#1352]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by DoctorMacc** [comment]
Please follow the issue template.

**Comment by Higa9** [comment]
So I run my 1.16.3 Java server with geyser in the plugins folder and installed and when I join on my bedrock account it won’t let me join the server it says outdated version join on 1.16.3 but I’m on 1.16.50 on bedrock so I don’t know what to do

**Comment by DoctorMacc** [comment]
Please ensure you are downloading Geyser from https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/ .

**Comment by Higa9** [comment]
> Please follow the issue template; thank you!

Where’s that

**Comment by Higa9** [comment]
> Please ensure you are downloading Geyser from https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/ .

I did

**Comment by DoctorMacc** [comment]
Please join our Discord server for further assistance as this is not an error in Geyser but a setup misconfiguration.

**Comment by Higa9** [comment]
> Please ensure you are downloading Geyser from https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/ .

If I where to reinstall geyser will I have to reinstall floodgate too

**Comment by Higa9** [comment]
If I where to reinstall geyser will I have to reinstall floodgate too ANSWER PLEASE I DONT HAVE TO TIME TO TALK ON DISCORD IT TO COMPLICATED

**Comment by DoctorMacc** [comment]
no

**Comment by RednedEpic** [comment]
> If I where to reinstall geyser will I have to reinstall floodgate too ANSWER PLEASE I DONT HAVE TO TIME TO TALK ON DISCORD IT TO COMPLICATED

Read the wiki and setup guide, it explains this in much more detail 🙂

**Comment by Higa9** [comment]
> no

why

**Comment by DoctorMacc** [comment]
In response to your question.

**Comment by RednedEpic** [comment]
Discord is the place for this type of communication. Please continue this conversation there.
