### ISSUE TITLE
There is a problem with the enchanting table

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Geyser#1356]
**Describe the bug**

Enchanting becomes confused
**To Reproduce**

Click the enchanting table

Enchant equipment
![Screenshot_20201002_143015_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/94894875-d2af5200-04bc-11eb-9136-2dcc3397d71d.jpg)

![Screenshot_20201002_143017_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/94894891-dd69e700-04bc-11eb-987f-a540dc58c9c4.jpg)

Aqua affinity II becomes thorns II
Some enchantments seem to be out of order
**Expected behavior**

The enchantment table should display the correct enchantment

**Screenshots / Videos**

**Server Version**

Paper-135(1.16.1)

**Geyser Version**

![IMG20201002144449](https://user-images.githubusercontent.com/53421735/94895365-db545800-04bd-11eb-9590-8f7b836f3e61.jpg)

**Minecraft: Bedrock Edition Version**

Bedrock 1.16.20

**Comment by Loganh4005** [comment]
Probably a mapping issue

**Comment by Renzoez** [comment]
Well Its just a GUI appearence.

on my server it appears like this.

![image](https://user-images.githubusercontent.com/19679239/97103098-77feb580-1678-11eb-9bbd-46421aa328e8.png)

So you just have to drag the item and the lapislazuli, after will show the enchantments.

**Comment by Camotoy** [comment]
This will be fixed in the inventory rewrite.
