### ISSUE TITLE
bounding boxes are wrong

### ISSUE THREAD

**Issue by LegacyGamerHD** [GeyserMC/Geyser#136]
stand close to a block and jump on also happens with auto jump this prevents players from getting out of swimming i wash testing stuff see here https://github.com/LegacyGamerHD/LoyaltyMC-Geyser/blob/4fb371791bcde064103eb61b71f007993d45d4fb/connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockActionTranslator.java#L64 you can get out of the watter but yu cant you get stuck onb the block might it be the bounding boces of blocks?

**Comment by LegacyGamerHD** [comment]
might be related to #109

**Comment by LegacyGamerHD** [comment]
idk for shure it realy seems bounding boxes are (way) off

**Comment by LegacyGamerHD** [comment]
bounding boxes are indeed wrong also https://github.com/LegacyGamerHD/LoyaltyMC-pspe/blob/main_loyalty/resources/resources/pe/entitydata.json why not use json for it

**Comment by LegacyGamerHD** [comment]
also that caush #109 i changed and i could walk over stars and slabs again

**Comment by RednedEpic** [comment]
You're going to need to provide more information about what is wrong and what you changed that fixed the issue with movement. Either way, the "fix" you're describing sounds more like a hack, and at least on the Java side, the entity would pretty much be "flying."

I'm going to need more information about _what_ is wrong with the bounding boxes, and how you know this is the case. Otherwise, the rest of the issue seems to be related to the movement bug which is known and being worked on.

**Comment by andrew121410** [comment]
rip

**Comment by LegacyGamerHD** [comment]
They aren't wrong if am seeing at pspe code only pspe set player a little higher almost not noticeable so yeah

**Comment by LegacyGamerHD** [comment]
> rip

That's ectopic...

**Comment by LegacyGamerHD** [comment]
> You're going to need to provide more information about what is wrong and what you changed that fixed the issue with movement. Either way, the "fix" you're describing sounds more like a hack, and at least on the Java side, the entity would pretty much be "flying."
> 
> I'm going to need more information about _what_ is wrong with the bounding boxes, and how you know this is the case. Otherwise, the rest of the issue seems to be related to the movement bug which is known and being worked on.

Yeah am aware that is a hack well I did some more testing after it and yes that but I cant hit a dam pig without standing in some way another do I need record it ......
