### ISSUE TITLE
Color bossbar

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Geyser#1361]
**What feature do you want?**
Add a description
Display colored bossbar
**Alternatives?**
List any alternatives you might have tried

I found that the material pack seems to support multiple colored bossbar
![41fc6d5416afbb47](https://user-images.githubusercontent.com/53421735/95006695-89d0d800-0639-11eb-930f-f022f983e375.jpg)
![-27f98cac7854f96b](https://user-images.githubusercontent.com/53421735/95006698-8d645f00-0639-11eb-82b3-8a7b2c82295a.jpg)

**Comment by DoctorMacc** [comment]
Please elaborate - do you want this feature to be correctly translated from Java Edition? Can you give an example of where this fails?

**Comment by zimzaza4** [comment]
> 请详细说明-您是否要从Java Edition正确翻译此功能？您能举一个失败的例子吗？

Java
![-69cfaa3a58226046](https://user-images.githubusercontent.com/53421735/95006765-52aef680-063a-11eb-8cfd-5be8c08d583b.jpg)
Bedrock
![Uploading IMG20201004120748.jpg…]()

**Comment by zimzaza4** [comment]
> 请详细说明-您是否要从Java Edition正确翻译此功能？您能举一个失败的例子吗？

Java
![-69cfaa3a58226046](https://user-images.githubusercontent.com/53421735/95006765-52aef680-063a-11eb-8cfd-5be8c08d583b.jpg)
Bedrock
![IMG20201004120748](https://user-images.githubusercontent.com/53421735/95006769-580c4100-063a-11eb-9521-faabac118ea2.jpg)

**Comment by RednedEpic** [comment]
This is a limitation of the Bedrock client unfortunately, meaning we're unable to implement this until proper color support is implemented on Bedrock's end.

**Comment by PQguanfang** [comment]
Please reopen it as this feature has been added in the latest Minecraft Bedrock Edition.At least, Nukkit can do this.
