### ISSUE TITLE
Gamemode, teleport errors

### ISSUE THREAD

**Issue by TOWUK** [GeyserMC/Geyser#1362]
**Describe the bug**
teleport and gamemode dont correctly changed!

**To Reproduce**
Check video, spectator mode not worked, this bug Geyser! not plugin bug!!! (Maybe bug steveice protocol lib)

**Expected behavior**
none, clear client BE and JAVA

**Screenshots / Videos**
https://youtu.be/xEsEHr2l0Uk

**Server Version**
dump (i use latest paper 1.16.3 now)

**Geyser Version**
dump (i use latest Geyser-Spigot offline-mode now)

**Minecraft: Bedrock Edition Version**
1.16.40+

**Additional Context**
https://dump.geysermc.org/TxiBJED6xWNXCJkdR7vCXzuk8Srycx1y

log:
[22:51:34] [nioEventLoopGroup-3-2/WARN]: [Geyser-Spigot] Ошибка нисходящего пакета данных! Value -1 has no mapping for key class com.github.steveice10.mc.protocol.data.game.entity.player.GameMode.

**Comment by soshimee** [comment]
Can not reproduce on neither paper 1.16.3 nor tuinity 1.16.3.

**Comment by DoctorMacc** [comment]
Likely MBedwars acting up.

**Comment by MrEAlderson** [comment]
-1 is a valid, but widely unkown, game mode which is being fully supported by the client. It's not "MBedwars acting up". Go try it out for yourself.
Cheers

**Comment by DoctorMacc** [comment]
@MrEAlderson what is the behavior of the -1 gamemode?

**Comment by MrEAlderson** [comment]
> @MrEAlderson what is the behavior of the -1 gamemode?

Same as the survival gamemode, but the health&food bar disappear

**Comment by DoctorMacc** [comment]
Ah, I see. Not sure if we can remove those options in Bedrock, but I can add support so we don't freak out at the -1. I think we already technically handle -1 for the secondary gamemode so I'll just extend that functionality. Thank you for the insight! (Sorry for assuming MBedwars was just doing something hacky or something!)

**Comment by MrEAlderson** [comment]
No problem and thank you for being so kind 🙂

**Comment by DoctorMacc** [comment]
Is there an easy way to test this gamemode -1? Unfortunately I don't have access to a MBedwars instance (and it's probably not a good idea for me to step into a random game with the expectation of getting bugged).

**Comment by TOWUK** [comment]
> Is there an easy way to test this gamemode -1? Unfortunately I don't have access to a MBedwars instance (and it's probably not a good idea for me to step into a random game with the expectation of getting bugged).

GET ME FIX GEYSER, I WILL TESTS

**Comment by MrEAlderson** [comment]
You can send yourself the gamemode state change packet. I can create a small plugin for you to test it

**Comment by DoctorMacc** [comment]
That would be lovely!

**Comment by TOWUK** [comment]
can you find out when they will fix this problem?

**Comment by MrEAlderson** [comment]
> can you find out when they will fix this problem?

Sorry, but I'm currently a bit busy. He has to wait for me to fix it. Will try to send it the next two days

**Comment by MrEAlderson** [comment]
There you go. Rename that file from .zip to .jar, install on spigot 1.16.3 and join to obtain it
[testplugin.zip](https://github.com/GeyserMC/Geyser/files/5417899/testplugin.zip)

**Comment by DoctorMacc** [comment]
Thank you so much!

**Comment by DoctorMacc** [comment]
This has been fixed.

**Comment by TOWUK** [comment]
> 
> 
> This has been fixed.

not...

**Comment by TOWUK** [comment]
> 
> 
> This has been fixed.

I'm still being teleported down the map from the geyser...

```
[10:05:46] [Server thread/INFO]: TOWUK_yt[/127.0.0.1:61947] logged in with entity id 29 at ([lobby]0.5, 65.0, -16.5)
[10:05:46] [Thread-32/INFO]: [Geyser-Spigot] Заспаунен игрок на координатах -0,732 64 -12,123
[10:05:52] [Thread-32/INFO]: [Geyser-Spigot] Заспаунен игрок на координатах 0,5 115,1 0,5
[10:05:52] [Server thread/WARN]: [MBedwars] Something in the config 'lobby-countdownstart-calculation' seems to be wrong! (Error)
[10:05:52] [Server thread/WARN]: TOWUK_yt moved too quickly! 6.428974,-51.099999999999994,0.20497549999999998
[10:07:22] [Thread-32/INFO]: [Geyser-Spigot] Заспаунен игрок на координатах 99,5 70 1,5
[10:09:23] [Network Listener - #1/INFO]: [Geyser-Spigot] Bedrock пользователь с IP: /127.0.0.1 отключился по причине CLOSED_BY_REMOTE_PEER
[10:09:23] [nioEventLoopGroup-3-2/INFO]: [Geyser-Spigot] TOWUK yt отключился от удалённого Java сервера 192.168.0.8 по причине CLOSED_BY_REMOTE_PEER
```

**Comment by DoctorMacc** [comment]
The gamemode bug mentioned has been fixed.
