### ISSUE TITLE
Bedrock Prefix Change

### ISSUE THREAD

**Issue by EvoGier** [GeyserMC/Geyser#1364]
**What feature do you want?**
I wish I had the ability to change the prefix of the Bedrock community on my server. I would like to change the asterisk to something else so I can use their UUID without issues.

**Comment by RednedEpic** [comment]
You can do this in the Floodgate config.

**Comment by EvoGier** [comment]
Lol thx man... that was quick. I am so glad that the community actually responds. 😀

**Comment by EvoGier** [comment]
> You can do this in the Floodgate config.

When I change it, and reload the server, it keeps the asterisk. Do you have any other suggestions?

**Comment by toinouH** [comment]
Delete usercache.json ^^
