### ISSUE TITLE
Can’t Change Bedrock Prefix

### ISSUE THREAD

**Issue by EvoGier** [GeyserMC/Geyser#1366]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by RednedEpic** [comment]
Please follow the issue template, and report this in the correct place. Additionally, make sure you restart your server after changing this prefix as well as removing the usercache.json in your server.
