### ISSUE TITLE
Packet Logger to add stuff faster and easier

### ISSUE THREAD

**Issue by Loganh4005** [GeyserMC/Geyser#1367]
**What feature do you want?**
Something that logs EVERY packet for both Java and Bedrock. I'm thinking a separate app. (You could make a proxy log every packet eg. Waterfall and Waterdog) An example that this could fix is getting the proper guis working by checking the packets

**Alternatives?**
List any alternatives you might have tried
no.

**Comment by DoctorMacc** [comment]
If you're hoping that will help development, that won't necessarily. We can just add print statements to where the packets are sent or received, or use Pakkit or ProxyPass.

**Comment by bundabrg** [comment]
This could work as an extension. Capture all packet events and log to file so you can trace both sides.

**Comment by RednedEpic** [comment]
This is something that is a bit out of the scope of the project - it would best be implemented as an extension once we get support for that implemented.
