### ISSUE TITLE
Water does not flow in Creative, does flow in Survival

### ISSUE THREAD

**Issue by freekvh** [GeyserMC/Geyser#1372]
**Describe the bug**

Water buckets can place water (at times, it seems a bit tedious) but it does not start to flow in Creative. It does flow in Survival.

**To Reproduce**

Get a bucket of water
Place it.
Water is confined to 1 block in Creative, see screenshot below.

**Expected behavior**

I would expect the water to start flowing

**Screenshots / Videos**

![schermshot](https://user-images.githubusercontent.com/12241293/95011231-8c2e3480-062f-11eb-8d0b-073ca5d2db3e.png)
The water just stays there

**Server Version**

1.16.3 git-Paper-208

**Geyser Version**

https://dump.geysermc.org/LdI4aOAPL82cp9nMvJD2VINKbWRfQQpZ
Version: "1.1.0 (git-master-ba6f174)"
Yes, using floodgate

**Minecraft: Bedrock Edition Version**

Android 1.16.40

**Additional Context**

No plugins other than geyser and floodgate.
I reported this here first #1293 , after that a user on Discord confirmed the behviour (and pointed out that it does work in survival, which I confirmed after that.)

**Comment by rtm516** [comment]
This is due to the bucket placement not registering properly on the server while in creative.

**Comment by DoctorMacc** [comment]
This should be fixed with https://github.com/GeyserMC/Geyser/pull/1369 - I pinged a person with this same username with instructions in Discord if you would try this PR out!
