### ISSUE TITLE
Anvil item repairs and it's enchantment levels/costs not working properly

### ISSUE THREAD

**Issue by vijaypondini** [GeyserMC/Geyser#1374]
**Describe the bug**
Attempting to repair an enchanted item with an anvil takes up more/less levels than what it displays in the Anvil GUI. 

**To Reproduce**
1. Get an enchanted item and a non-enchanted item of same type.
2. Set your xp level higher than the cost to repair the item.
3. set gamemode to survival, and attempt to repair it

**Expected behavior**
Item gets repaired, but uses up more levels than what was disaplyed in Anvil UI. 
Relogging did not recover player levels.

**Screenshots / Videos**
https://imgur.com/a/HOPsfNL

**Server Version**
server is running Paper version git-Paper-174 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Geyser Version**
server is running Geyser version 1.1.0 (git-master-0cd4381) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
No anvil based plugins, or any enchantment modification plugins present in my server

**Comment by MagnoBooter** [comment]
I can confirm this is the case sometimes. But not always.
The displayed enchantment cost is usually correct, so there must be certain conditions causing this.
As an example, I tried to combine two enchanted bows. The Anvil estimated an enchantment cost of 7, but when performing the repair, I lost 13 levels.
(This was Paper 230, Geyser jenkins build 426)

**Comment by vijaypondini** [comment]
Can anyone review this? We've tested this multiple times and it still did not seem to work. I can also see that @MagnoBooter tried it and it didn't work for him too

**Comment by Hellohi3654** [comment]
> I can confirm this is the case sometimes. But not always.
> The displayed enchantment cost is usually correct, so there must be certain conditions causing this.
> As an example, I tried to combine two enchanted bows. The Anvil estimated an enchantment cost of 7, but when performing the repair, I lost 13 levels.
> (This was Paper 230, Geyser jenkins build 426)

did you try leaving and rejoining afterwards to see if the item was in your inventory
I think eating a piece of food might also update your inventory

**Comment by AziRixXOffi** [comment]
This bug is current already, not graphic, it's a real problem
