### ISSUE TITLE
Teleporting out from end fountain to overworld in bedrock has a small issue

### ISSUE THREAD

**Issue by vijaypondini** [GeyserMC/Geyser#1375]
**Describe the bug**
When exiting the end world via end fountain, you end up 32,768 blocks in Y direction, at 0 X and 0 Z direction

**To Reproduce**
1. beat the ender dragon, get the end fountain
2. attempt to enter it ( obviously )
3. You would get teleported to 0 32768 0

**Expected behavior**
You would fall down 100 blocks or so until you get back to your respawn point you set in the overworld, similar to how you login to a game via bedrock and you fall some blocks before you can start playing ( during the login process with floodgate )

**Screenshots / Videos**
https://imgur.com/a/EUbb4wl

**Server Version**
server is running Paper version git-Paper-174 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Geyser Version**
server is running Geyser version 1.1.0 (git-master-0cd4381) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
Using multiverse-core for the specified version. Have a plugin called lastlocation that just keeps player back in last location but i really don't think that affects this.

**Comment by DoctorMacc** [comment]
This might just be the way we load in dimensions. It's only aesthetic, yes?

**Comment by vijaypondini** [comment]
Pretty much yes. not something that interrupts the gaming experience.

**Comment by vijaypondini** [comment]
Heh, 9 months later. Still low priority 😅

**Comment by RednedEpic** [comment]
Thanks for the report, however due to this actually not having any gameplay impact and being a result of another dimensions witch bug that will subsequently fix this issue when resolved, I am going to close this issue. Thanks for reporting tho!
