### ISSUE TITLE
Movement packets are blocked if a bed is slept in

### ISSUE THREAD

**Issue by Roadhog360** [GeyserMC/Geyser#1378]
**Describe the bug**

Here's where my beds in my house are. If I sleep in them, upon waking up on the client I can move but the server no longer detects movement, and I am stuck standing on the bed until I re-log in. This issue does not happen with beds I place out in the open and sleep in, so I'd assume it's something to do with the fake bed spawning in my ceiling somehow. I usually sleep in the purple bed.

![image](https://user-images.githubusercontent.com/11903511/95266790-ea127600-0801-11eb-9515-e068e36e88cd.png)

**To Reproduce**
1. Sleep in a bed that's 3 blocks below a ceiling
2. Let it turn to day naturally
3. Now all client movement is fake, try moving about 32 blocks away from the bed and placing a block; you can't

As far as I know, the only way to get out of this bug is to re-join.

**Expected behavior**
After waking up, I should be able to resume playing the game and moving around.

**Screenshots / Videos**

**Server Version**

Vanilla 1.16.3 (So no plugins, no Spigot, etc)

**Geyser Version**

![image](https://user-images.githubusercontent.com/11903511/95267222-b5eb8500-0802-11eb-8199-94eced6cd6fa.png)
Floodgate is not used, you need a Java account to play.

**Minecraft: Bedrock Edition Version**

1.16.40

**Additional Context**

Sometimes I'm not home when I sleep, and so I place a bed in the middle of the biome I'm in to sleep. This seems to work fine and not stop the server to see movement from me. It's only the beds in my home that do this.

**Comment by E404NNF** [comment]
Geyser dump please? I think it isn't important but it's good to have

**Comment by Roadhog360** [comment]
https://dump.geysermc.org/Fj6oK7imjmW5vy5ICvuVhV6P1p1oE9As

**Comment by Roadhog360** [comment]
Argh, GitHub messed up the formatting on my post, hold on.

**Comment by DoctorMacc** [comment]
Could you enable cache-chunks in your Geyser config and see if the issue persists?

**Comment by Roadhog360** [comment]
It seems this fixed the issue. Do you know why that fixed it? I noticed the cache feature says it uses more RAM? How much more? I currently allocate 2GB

**Comment by DoctorMacc** [comment]
Likely not much; someone on our Discord has successfully ran a standalone instance of Geyser with cache-chunks and one player with 64MB of RAM allocated.

**Comment by Roadhog360** [comment]
Nice. So the little amount I have applied is more than enough?

**Comment by DoctorMacc** [comment]
Oh yeah, you're fine.

**Comment by Roadhog360** [comment]
I can probably tone it down to like 256MB then.

**Comment by ImDaBigBoss** [comment]
It also does it to beds just under build limit for some reason.

**Comment by Roadhog360** [comment]
Okay, so it seems the issue popped up again, but I was wrong, it's not limited to beds near ceilings, it seems to be a little random and it only being in my house was a coincidence. All related info like version is still the same.

**Comment by DoctorMacc** [comment]
Is this with cache chunks on or off?

**Comment by Roadhog360** [comment]
Still on. I noticed that when I first turned it on, my character actually sleeps on the bed instead of above it. But after I restarted Geyser it went back to putting me on fake beds above where I click.

**Comment by DoctorMacc** [comment]
Perhaps it has something to do with beds placed during your game versus beds already placed when you logged on?

**Comment by DoctorMacc** [comment]
If it's not that then it must be orientation of the bed, or which part of the bed you clicked (pillow part or not pillow part).

**Comment by Roadhog360** [comment]
That could be related. I'll test more with it once I get off of work, I've gotta go pretty soon.

**Comment by DoctorMacc** [comment]
Any update on this? I can test myself soon if need be.

**Comment by Roadhog360** [comment]
Oh crap, I completely forgot about this. Do you still want me to test this?

**Comment by DoctorMacc** [comment]
That would be lovely; thanks!

**Comment by RednedEpic** [comment]
Any update on this?

**Comment by Roadhog360** [comment]
Oh shoot. I did a bit of testing back in October and forgot to report my findings. It's been a while, but I believe I didn't really see any difference. I don't think it actually mattered where the bed was or what I clicked on though.

**Comment by Camotoy** [comment]
As this issue has been inactive, there have been changes in the bed code, and this issue has not been re-reported, I am closing. Do let us know if this is in error!
