### ISSUE TITLE
Bedrock client crashes when trying to join server

### ISSUE THREAD

**Issue by cloakfox** [GeyserMC/Geyser#1379]
**Describe the bug**
Bedrock client crashes and closes when trying to join the survival server at play.darkscorner.net
The crash does not happen 100% of the time, but happens quite often (only on server join)
**To Reproduce**
Try joining the survival server

**Expected behavior**
To be able to join without an issue

**Screenshots / Videos**
none

**Server Version**
Tuinity 1.16.3

**Geyser Version**
> geyser version
[06:06:52] [INFO]: This server is running Geyser version 1.1.0 (git-master-ba6f174) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)
[06:06:52] [INFO]: Checking version, please wait...
[06:06:53] [INFO]: No updates available.

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
Error on bungee: https://pastebin.com/PX8h9F9V

**Comment by DoctorMacc** [comment]
Unable to replicate by connecting to that IP three times - once by directly joining that IP and another by joining through my standalone Geyser instance.

A Geyser dump would be helpful.

**Comment by DoctorMacc** [comment]
Additionally the Bedrock platform you tried to join with would also be helpful.

**Comment by soshimee** [comment]
Also happens to me on iPad and latest Bedrock. Not 100% but usually on first joins.

**Comment by cloakfox** [comment]
> Unable to replicate by connecting to that IP three times (six times total) - once by directly joining that IP and another by joining through my standalone Geyser instance.
> 
> A Geyser dump would be helpful.



> Additionally the Bedrock platform you tried to join with would also be helpful.

https://dump.geysermc.org/rckd9WiFQnhUu4aPjPrrWzOVpL8mFxLT

I was using windows edition

I noticed that when I joined the oneblock gamemode or creative gamemode first instead of survival that it would not produce a crash when then survival after.

Mostly on first connection to survival it will crash and close the client completely.

**Comment by cloakfox** [comment]
I can't even seem to ping the server on bedrock now, I dont know why. I have not touched any settings.

**Comment by cloakfox** [comment]
Okay now thats weird. It was saying "Unable to connect to world" and now I tried again and it works.

:/

**Comment by filfat** [comment]
This seems to be a general raknet implementation problem. We’re currently experiencing the same problems on JSPrismarine, but only with certain platforms or certain conditions. I’ll let you know when we’ve figured out the issue (our best best right now is that the packets might arrive or be sent in the wrong order under certain conditions).

**Comment by DoctorMacc** [comment]
Interesting. Thanks for the insight! Thinking about it, I crash on login sometimes as well, but I usually blame that on my Linux launcher that runs the Android version of the game.

**Comment by Noxillio** [comment]
I'm going to put this here just in case the author is still looking for a solution. I believe it's possible that this lead to a fix: https://github.com/GeyserMC/Geyser/issues/1497#issuecomment-751824564

**Comment by timof121** [comment]
Same. iPad Mini 2. Other bedrock servers work ok

**Comment by MrRazamataz** [comment]
This is an issue for me. Even with https://github.com/GeyserMC/Geyser/pull/1775

**Comment by RednedEpic** [comment]
Does this still occur?

**Comment by cloakfox** [comment]
Yes

**Comment by cloakfox** [comment]
Forgot to link the more up to date report, basically same issue I think.
https://github.com/GeyserMC/Geyser/issues/2212

**Comment by Camotoy** [comment]
Sounds good.

**Comment by marcelschoen** [comment]
I am having the same issue (Bedrock crash on join). Just installed the latest builds of Geyser and Floodgate (Oct. 29). See https://dump.geysermc.org/r8ajtDEgEbWbmApEyTBwNcfnpD9zh3s6

**Comment by Camotoy** [comment]
Please open a new issue and, if possible, provide debugging steps!
