### ISSUE TITLE
Eror when connecting

### ISSUE THREAD

**Issue by SDS1234** [GeyserMC/Geyser#1384]
Hello
When I connect via my bedrock account it says to wait and shortly after that it says connection timed out. What can I do to connect? 

**Describe the bug**
I connect to the bedrock server can't do anything and shortly afterwards it says connection timed out.

1.12.2

**Geyser Version**
 This server is running Geyser version 1.1.0 (git-master-ec609fa) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

https://pastebin.com/23uut30d

**Comment by DoctorMacc** [comment]
`0.0.29.139` is likely not a valid IP address.

This is definitely a user error. For support, please hop onto our Discord. Thank you!
