### ISSUE TITLE
There's something wrong with the scoreboard

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Geyser#1385]
**Describe the bug**

When the player enters the server, the content of the scoreboard is not loaded.
**To Reproduce**
Join server
The content of the scoreboard is not displayed, only the title
![IMG20201010190922](https://user-images.githubusercontent.com/53421735/95653562-27da0c00-0b2c-11eb-9563-b87876c9c5dc.jpg)

If I reload the scoreboard, it will load the contents of the scoreboard

**Expected behavior**

When the player joins the server, the scoreboard should display the content
![IMG20201010190934](https://user-images.githubusercontent.com/53421735/95653568-2c062980-0b2c-11eb-904d-8246ff39e212.jpg)

**Server Version**

Paper -135
**Geyser Version**

Geyser-Spigot
![IMG20201010190614](https://user-images.githubusercontent.com/53421735/95653497-b7cb8600-0b2b-11eb-8d81-dbb798a4dafc.jpg)

**Minecraft: Bedrock Edition Version**

1.16.20

**Comment by DoctorMacc** [comment]
Is this a new issue or an issue that has been occurring? How can we replicate it? Can we get a Geyser dump?

**Comment by Hellohi3654** [comment]
https://github.com/Hellohi3654/Geyser/issues/143

**Comment by Hellohi3654** [comment]
I think this became a problem after the latest scoreboard fixes

**Comment by zimzaza4** [comment]
> Is this a new issue or an issue that has been occurring? How can we replicate it? Can we get a Geyser dump?

 https://dump.geysermc.org/VpUMnxI9sJCGRtCpHrLSxAYPWcwTvDON

**Comment by zimzaza4** [comment]
The problem seems to have occurred only in geyser-spigot

**Comment by zimzaza4** [comment]
![Uploading IMG20201024214501.jpg…]()

**Comment by DoctorMacc** [comment]
Could you please test https://github.com/GeyserMC/Geyser/pull/1446 and see if it fixes your issue?

**Comment by zimzaza4** [comment]
> Could you please test #1446 and see if it fixes your issue?

I used that PR and it didn't solve the problem

**Comment by Tim203** [comment]
Did it change anything for you?
Btw which Scoreboard plugin do you use?

**Comment by zimzaza4** [comment]
> 它为您改变了什么吗？
> 顺便说一句，您使用哪个记分板插件？

Nothing seems to have changed
I use MiaoBoard
Previous versions of geyser can be displayed

**Comment by zimzaza4** [comment]
May be related to PR1830

**Comment by Tim203** [comment]
Did it work before #1381 or before #1166 or did it never work?

**Comment by zimzaza4** [comment]
> 它是在[＃1381](https://github.com/GeyserMC/Geyser/pull/1381)之前还是在[＃1166](https://github.com/GeyserMC/Geyser/pull/1166)之前起作用，还是从未起作用？

This problem occurred after the consolidation of #1381

**Comment by snaildos** [comment]
Hey; I am having this problem too. Is there something in the config we need to change?

**Comment by zimzaza4** [comment]
What is the config you are talking about

**Comment by DoctorMacc** [comment]
There is no config that will fix this. It's a bug we need to fix.

**Comment by zimzaza4** [comment]
> Hey; I am having this problem too. Is there something in the config we need to change?

You can try #1446,although it doesn't solve my problem

**Comment by snaildos** [comment]
Alright, sounds good.

**Comment by snaildos** [comment]
I can also confirm this doesn't only happen on spigot. It happens on bungee.

**Comment by zimzaza4** [comment]
If I reload the scoreboard, it will show

**Comment by DoctorMacc** [comment]
Does #1446 fix the issue now?
