### ISSUE TITLE
Partial config crashes the plugin

### ISSUE THREAD

**Issue by matthi4s** [GeyserMC/Geyser#1386]
**Describe the bug**
A partial config file, e.g. with only one option crashes the Geyser plugin.

**To Reproduce**
1. Set the config to:
```
bedrock:
  clone-remote-port: true
```
2. Start the server
3. Geyser plugin crashes: 
```
[23:07:33] [Server thread/ERROR]: Error occurred while enabling Geyser-Spigot v1.1.0 (Is it up to date?)
--
128 | java.lang.NullPointerException: null
129 | at org.geysermc.platform.spigot.GeyserSpigotPlugin.onEnable(GeyserSpigotPlugin.java:84) ~[?:?]
130 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[minecraft_server.jar:git-Paper-221]
131 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[minecraft_server.jar:git-Paper-221]
132 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[minecraft_server.jar:git-Paper-221]
133 | at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[minecraft_server.jar:git-Paper-221]
134 | at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[minecraft_server.jar:git-Paper-221]
135 | at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[minecraft_server.jar:git-Paper-221]
136 | at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[minecraft_server.jar:git-Paper-221]
137 | at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[minecraft_server.jar:git-Paper-221]
138 | at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[minecraft_server.jar:git-Paper-221]
139 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Expected behavior**
Geyser plugin loads and generates the config including the previously set partial config options.

**Server Version**
Paper version git-Paper-221 (MC: 1.16.3)

**Geyser Version**
Geyser version 1.1.0 (git-master-ec609fa) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)
(with Floodgate)

**Minecraft: Bedrock Edition Version**
1.16.50

**Additional Context**
This is maybe not an important bug and there are ways to work around this (e.g. starting the server first, using a pre-generated config, obtaining the config from somewhere else and modifying it), but we want to automatically set an option (`clone-remote-port`) to true on plugin installation. Using a pre-generated config or something similar could lead to issues when the default config is changed.

**Comment by DoctorMacc** [comment]
Should be fixed by #1387.

**Comment by matthi4s** [comment]
Thank you for the insanely quick fix! I've just tested it and the plugin is no longer crashing, but it also doesn't generate the full config and even ignores the set `clone-remote-port` option. The log says `[Geyser-Spigot] Your Geyser config is out of date! Please regenerate your config when possible.`

**Comment by toinouH** [comment]
Did you delete the config file after the update ?
If not deleting it could solve the issue ^^

**Comment by matthi4s** [comment]
Deleting the config will fix this error, but what I want to suggest here is the possibility to set *some* options before starting the server the first time with a minimal/partial config.

**Comment by DoctorMacc** [comment]
Generating the remaining part of the config is definitely something that's going to be more difficult, and is currently out of my knowledge of the config parsing library we use. It's something I can look into soon if no one else does.

**Comment by toinouH** [comment]
Request a feature here:
 https://github.com/GeyserMC/Geyser/issues/new?assignees=&labels=&template=feature_request.md&title=

If you are busy I can do it tomorrow but I'm not in your head and I guess you have a more precise idea of what you want ^^

**Comment by matthi4s** [comment]
Thanks a lot, we currently have a workaround, but a proper solution would probably be better.

**Comment by DoctorMacc** [comment]
Good luck with your setup and please feel free to reach out to us if there's something else we can do.
