### ISSUE TITLE
Allow partial config

### ISSUE THREAD

**Issue by matthi4s** [GeyserMC/Geyser#1388]
**What feature do you want?**
As discussed in #1386 it would be great if you could add a possibility to set only *some* options in a config file before starting the server for the first time by creating a partial config file like this:
```
bedrock:
  clone-remote-port: true
```
On the first start the plugin would generate the full config including the values of the partial config.

**Alternatives?**
An alternative is getting a predefined config and using that to change some options. The downside is that this could break with updates.

**Comment by onebeastchris** [comment]
Some partial configuration is possible nowadays with system properties, e.g. port/ip - see here: https://wiki.geysermc.org/geyser/geyser-command-line-arguments-and-system-properties/ 
Maybe partial configs (or rather, configs that auto-update to include latest features) will be possible once Geyser uses a different config lib; afaik a switch to Configurate is planned at some point.

**Comment by Camotoy** [comment]
Closing this issue as the core request has been resolved with system properties. If someone else desires partial configs, let us know why. Thanks.
