### ISSUE TITLE
Blocks stop being placed when towering/building up

### ISSUE THREAD

**Issue by jackson-57** [GeyserMC/Geyser#1389]
**Describe the bug**

When towering up by holding space and right click to continually jump and place blocks, after a few seconds blocks will stop being placed, and you have to stop holding right click then start holding right click again in order for block placing to continue for a couple more seconds.
**To Reproduce**

1. Hold blocks in hand
2. Look down
3. Hold the jump and place block buttons
4. Blocks will stop being placed after a couple seconds

**Expected behavior**

Blocks should be continually placed below the player's feet, which should create a tower.
**Screenshots / Videos**

[Link to video (will download it)](https://cdn.discordapp.com/attachments/613163671870242842/764671144711684106/SPOILER_geyser_bug_video_recompressed.mp4)
[Link to discord message where video was posted (must be in geyser discord)](https://discordapp.com/channels/613163671870242838/613163671870242842/764671147722801152)
**Server Version**

Paper 220, MC 1.16.3
**Geyser Version**

Tested on Geyser test server, roughly 30 minutes ago. I do not have access to `/geyser version`.
**Minecraft: Bedrock Edition Version**

1.16.40
**Additional Context**

**Comment by jackson-57** [comment]
Realized this is a duplicate of #873. I'm not sure which issue should stay open.

**Comment by DoctorMacc** [comment]
I'll close this issue in favor of the older one. Feel free to link your video and any new information there!
