### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by bennasar99** [GeyserMC/Geyser#139]
It would be awesome if Geyser (when it's more complete) could run as an android app in the same mobile phone in which you play Minecraft.

**Comment by LegacyGamerHD** [comment]
Nope most phones aren't even strong anough not only that just freaking PC or a vps is it that hard

**Comment by LegacyGamerHD** [comment]
People reported issues on a raspberry pi 4 so let alone on phone

**Comment by alissonlauffer** [comment]
> Nope most phones aren't even strong anough not only that just freaking PC or a vps is it that hard

I can run it here by chrooting a Linux distro on Termux :man_shrugging:

**Comment by alissonlauffer** [comment]
- First, download Termux and AnLinux apps (they can be found on Play Store or F-Droid).
- Then select a distro to install on AnLinux and paste the commands into Termux shell.
- After a successful install, you can install java, download Geyser .jar and run it.

**Comment by alissonlauffer** [comment]
![](https://user-images.githubusercontent.com/29029632/72526110-6c0dd980-3844-11ea-8695-2e2df021edd2.png)

Proof

**Comment by LegacyGamerHD** [comment]
@alissonlauffer doesn't mean it runs good on all devices

**Comment by LegacyGamerHD** [comment]
And it shouldn't be hosted on android or at least low and phones

**Comment by alissonlauffer** [comment]
> And it shouldn't be hosted on android or at least low and phones

But it should work well even on low end smartphones. Mine is a Moto G5S Plus and I can run Geyser + Minecraft fine.

**Comment by LegacyGamerHD** [comment]
> > Nope most phones aren't even strong anough not only that just freaking PC or a vps is it that hard
> 
> I can run it here by chrooting a Linux distro on Termux

Yeah you can run but doesn't mean its stable or fast enough

**Comment by lukeeey** [comment]
Phones these days are more powerful than raspberry pi’s....

They are more than capable of running Geyser.

**Comment by LegacyGamerHD** [comment]
It's not meant to run it but yeah you can run it

**Comment by RednedEpic** [comment]
This is something we've been looking at implementing, but Android is not something many have worked too much with. It's definitely something we'd be willing to accept if someone were to open a Pull Request adding support for Android or if any of us ever decide to delve into Android in the future.

Also to those who participated, irrelevant conversation should be kept out of the issues section. If you don't know too much about a subject, please don't chime into the conversation.

**Comment by Heath123** [comment]
This exists now

**Comment by RednedEpic** [comment]
Android version is available here: https://github.com/rtm516/GeyserAndroid. Will be moved to the main organization soon, but here is the link for now.
