### ISSUE TITLE
Inventories not working with Release2Beta

### ISSUE THREAD

**Issue by E404NNF** [GeyserMC/Geyser#1393]
**Describe the bug**

All types of inventories not working when playing on a beta server through Release2Beta (the hotbar works)
**To Reproduce**

1. Join a beta server through Release2Beta
2. Get an item
3. Try moving from hotbar to inventory or crafting slots
4. Observe.

**Expected behavior**

All types of inventories to work
**Screenshots / Videos**

**Server Version**

CraftBukkit 1060-1090 (and it's forks)
Release2Beta Latest Commit (Commit `ed43011` recommended because of issues with furnaces)
**Geyser Version**

Build 420
**Minecraft: Bedrock Edition Version**

1.16.10
**Additional Context**

`Plugins (21/21): AuthMe, BetaItemStacker, BlocksOnGlass, DiscordChatBridge, DiscordCore, DynamicLight, Essentials, EssentialsChat, EssentialsSpawn, EvolutionCore, HeroicDeath, LWC, NoCheat, PermissionsEx, ReleaseToBeta, SleepPercent, StairsDrop, TPSPlugin, WorldBorder, WorldEdit, WorldGuard`

https://dump.geysermc.org/R50t7Bp5OehOnDpU5TgnA7aniCYPn9Mn

**Comment by E404NNF** [comment]
Fixed on R2B's side

**Comment by DoctorMacc** [comment]
Could you link the commit?

**Comment by E404NNF** [comment]
Commit fixed inventory issues with pre-1.11 clients: https://github.com/DirtPowered/Release2Beta/commit/e8d4e66d170ace529dfb51eb65ec02acf26a1af0 (partially fixed issues with geyser, had a bug that was in 1.12 players fixed in the second linked commit)
Fixed an issue with 1.11+ players caused by the commit linked above: https://github.com/DirtPowered/Release2Beta/commit/e7a3cee847b00d2b87c84a1f8b390bb962dfb901
