### ISSUE TITLE
Sending a component with a copy_to_clipboard clickEvent breaks client chat

### ISSUE THREAD

**Issue by JLyne** [GeyserMC/Geyser#1399]
**Describe the bug**
Sending a chat component including a `clickEvent` set to `copy_to_clipboard`, results in bedrock clients showing the raw component JSON, rather than showing the message correctly and ignoring the unsupported property.

This issue seems to be specific to `copy_to_clipboard`. I regularly use `open_url`,`suggest_command` and `run_command` without encountering this issue.

**To Reproduce**
1. Connect via geyser
2. Send a component including a `clickEvent` to the geyser-connected client (i.e `{"text": "test", "clickEvent": {"action": "copy_to_clipboard", "value": "test"}}`)
3. Observe how the client chat displays raw JSON rather than a parsed message.

**Expected behavior**
The message displays correctly, without the copy to clipboard functionality which bedrock doesn't support

**Screenshots / Videos**
An example. This message includes extra content before the `copy_to_clipboard` component, which all works correctly until the `copy_to_clipboard` component is added at the end.
![image](https://user-images.githubusercontent.com/4615316/95894180-a0d1a180-0d80-11eb-9e47-677c035e25ed.png)

**Server Version**
The chat is being handled by Velocity 1.1.0-SNAPSHOT (git-3b1009ca-b262)

**Geyser Version**
This server is running Geyser version 1.1.0 (git-master-73bec58) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
Dump: https://dump.geysermc.org/TbCxuVVMqUzxJ3w8PavXqICzgSsh0A94

**Comment by DoctorMacc** [comment]
If you would like to test https://github.com/GeyserMC/Geyser/pull/1400 - it happens to include RTM's fix.

**Comment by DoctorMacc** [comment]
This has been merged - could you please confirm is this has been fixed? (I will have time later to confirm myself)

**Comment by JLyne** [comment]
Updated and seems to be working fine now. Appreciate the quick fix.
