### ISSUE TITLE
Linux setup

### ISSUE THREAD

**Issue by E3BIT** [GeyserMC/Geyser#140]
i m not sure where should i write this because there is no such forums for GeyserMC ..

I m not really a pro in Linux but that instalation guide on geyserMC for linux is not really enough for me... i can solve basic problems on linux but i m still learning and for a lot of people its hard to understand somethings in linux.. 

my point is that i dont know how to setup GeyserMC .. i have done all the steps and geyser didnt created any files... no setup file or steps how to turn on server afterwards.. can anyone help

**Comment by RednedEpic** [comment]
> i m not sure where should i write this because there is no such forums for GeyserMC ..
> 
> I m not really a pro in Linux but that instalation guide on geyserMC for linux is not really enough for me... i can solve basic problems on linux but i m still learning and for a lot of people its hard to understand somethings in linux..
> 
> my point is that i dont know how to setup GeyserMC .. i have done all the steps and geyser didnt created any files... no setup file or steps how to turn on server afterwards.. can anyone help

You’re going to have to give us more information about where your stuck and what is lacking on that page (there is a whole page on how to make the startup script). However, the place to ask questions like this is in our Discord server linked in the README.

**Comment by alissonlauffer** [comment]
install java/openjdk from your distro and run `java -jar Geyser.jar`

**Comment by E3BIT** [comment]
@RednedEpic i followed the steps on this site https://github.com/GeyserMC/Geyser/wiki/Creating-a-Startup-Script under linux... i m using SOLUS 4.0 .. i m gonna send you pictures what i did .. but the command that @alissonlauffer wrote down worked just fine and i m ready to go.. 
But i m gonna send you pics what i did soo you can probably correct me what i did wrong or something

so i downloaded Geyser.jar and made a file run.sh with the following command on the pic
https://i.imgur.com/LeNZRgb.png
Then i made File executable as a program (its in another language but u can see its allowed there)
https://i.imgur.com/7AZbzzU.png
Then i ran the command which worked fine cuz no error has been showed
https://imgur.com/a/FqMxXsL
so i was a bit confused where i should go from there.. i tried to find files.. if the command did something but i couldnt found anything ( i searched trough files with CD command an LS to show files)

@alissonlauffer i already had java/openjdk from distro but command u send worked fine.. THANK YOU :)

I m gonna support this project and report bugs and other things :)

**Comment by RednedEpic** [comment]
Closing since Discord is the place to handle this stuff & the OP has joined.
