### ISSUE TITLE
Scoreboard does not load in builds equal to or greater than #417

### ISSUE THREAD

**Issue by JH3Y50N** [GeyserMC/Geyser#1408]
**Describe the bug**

**To Reproduce**
put the lasted version of Geyser and join in a 1.8 server, some times the scoreboard works but it's RARE

**Expected behavior**

![image](https://user-images.githubusercontent.com/29031972/96507313-5d1ee200-122f-11eb-9a75-4e0920d52ca8.png)

**Screenshots / Videos**

Bugged scoreboard
![image](https://user-images.githubusercontent.com/29031972/96170375-e1a0f600-0ef9-11eb-87a9-902e85ccd435.png)

BUGGED VERSION
![image](https://user-images.githubusercontent.com/29031972/96170300-ccc46280-0ef9-11eb-8c42-7189acdc2dba.png)

**Server Version**

![image](https://user-images.githubusercontent.com/29031972/96170424-f1b8d580-0ef9-11eb-9869-4253a3c5083d.png)

**Geyser Version**

All builds equal to or greater than #417

The #416 works normally

**Minecraft: Bedrock Edition Version**

1.16.40, Tested on Bedrock and MCPE

**Additional Context**

**Comment by Tim203** [comment]
What Scoreboard plugin do you use?

**Comment by JH3Y50N** [comment]
> What Scoreboard plugin do you use?

Own, and it's not a scoreboard plugin problem... read, works fine on the build #416

**Comment by Tim203** [comment]
It's easier to identify the issue when I know what the Scoreboard plugin is sending.

**Comment by JH3Y50N** [comment]
> It's easier to identify the issue when I know what the Scoreboard plugin is sending.

own scoreboard plugin

Java version you see that: 
![image](https://user-images.githubusercontent.com/29031972/96171241-03e74380-0efb-11eb-80cd-64965040204c.png)

**Comment by Tim203** [comment]
I mean the actual packets, but we have another Scoreboard issue (#1385) which might be related.
So I'll look into that one first and maybe it does fix your issue as well.

**Comment by zimzaza4** [comment]
> 您使用哪个记分板插件？

I used Titlemanager
This is the output of the console
![Uploading IMG20201024214501.jpg…]()
Scoreboard content not shown

**Comment by DoctorMacc** [comment]
Does #1446 fix the issue now?

**Comment by JH3Y50N** [comment]
> Does #1446 fix the issue now?

i have no tested

**Comment by Tim203** [comment]
Would be nice if you can test it

**Comment by JH3Y50N** [comment]
> Would be nice if you can test it

i can't test... because i have edited my scoreboard plugin to work with MCPE.. and now i'm busy wait some days

**Comment by JH3Y50N** [comment]
> Would be nice if you can test it

I just tested it and apparently it was solved.

**Comment by JH3Y50N** [comment]
> > Would be nice if you can test it
> 
> I just tested it and apparently it was solved.

![image](https://user-images.githubusercontent.com/29031972/98485231-9bd30700-21f3-11eb-9147-577b2fe2dec5.png)
Some Teams is not set.. Team suffix and prefix

**Comment by Tim203** [comment]
Good to know, thanks

**Comment by DoctorMacc** [comment]
As the initial issue is now fixed, I am closing this.
