### ISSUE TITLE
Sword sweep visibility

### ISSUE THREAD

**Issue by Roadhog360** [GeyserMC/Geyser#1409]
**What feature do you want?**
Being able to see the sword sweep particles by using a TNT particle since it looks like a sweep.

For the sound I'm not sure. I'm thinking maybe super sped up Elytra gliding or dragon wings?

**Comment by DoctorMacc** [comment]
We will likely have a resource pack that includes these sounds in the future.

**Comment by DoctorMacc** [comment]
I see you were discussing this on Discord before - yes, other particles as a replacement is definitely possible.

**Comment by Camotoy** [comment]
Alternatively implemented using a resource pack in #2176.
