### ISSUE TITLE
geyser reload command

### ISSUE THREAD

**Issue by LegacyGamerHD** [GeyserMC/Geyser#141]
geyser reload command like /geyser reload that reload config so as motd and metrics , ping pass trough

**Comment by EOT3000** [comment]
if you just want to reload the configs, that should be fairly easy to do, however, if EVRYTHING needs to be reloaded, that becomes MUCH harder, considering there could be hundreds of variables needed to be reloaded

**Comment by RednedEpic** [comment]
> if you just want to reload the configs, that should be fairly easy to do, however, if EVRYTHING needs to be reloaded, that becomes MUCH harder, considering there could be hundreds of variables needed to be reloaded

Eh, wouldn’t be _that_ difficult 😄.

**Comment by RisksY** [comment]
Right it can be. Maybe if possile you won't quit then reload to change config but it can make lots of bugs and open time of Geyser is not too much. It opens in nearly 5 seconds. :)

**Comment by RednedEpic** [comment]
> Right it can be. Maybe if possile you won't quit then reload to change config but it can make lots of bugs and open time of Geyser is not too much. It opens in nearly 5 seconds. :)

Soon to be even faster 😉.
