### ISSUE TITLE
Shulkers visible on bedrock when supposed to be invisible

### ISSUE THREAD

**Issue by notnotnotswipez** [GeyserMC/Geyser#1412]
**Describe the bug**
Shulkers appear on bedrock when invisible, supposed to be invisible on java

**To Reproduce**
1. Summon a shulker
2. Give the shulker an invisibility affect

**Expected behavior**
Shulker is supposed to go invisible

**Screenshots / Videos**
N/A

**Server Version**

This server is running CraftBukkit version git-Spigot-cbd1a1b-009d8af (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Geyser Version**

This server is running Geyser version 1.1.0 (git-master-64f2233) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**
1.16.61

**Additional Context**
Dump
https://dump.geysermc.org/dx27LwfPiv547BMY30q7SOEG00MTISFm

**Comment by DoctorMacc** [comment]
A singleplayer Bedrock world shows the same results - this might be a Bedrock bug.

**Comment by HyperSkys** [comment]
> A singleplayer Bedrock world shows the same results - this might be a Bedrock bug.

This is an issue with bedrock, I think they may have fixed it recently I don't know

**Comment by notnotnotswipez** [comment]
Geyser optional pack do be fixing this issue doe.
