### ISSUE TITLE
Java Players are Invisible

### ISSUE THREAD

**Issue by RobloxmanP** [GeyserMC/Geyser#1413]
**Describe the bug**
Java players are invisible on bedrock on death.

**To Reproduce**
1. Make a Java player go through a different dimension or die.

2. Bedrock players won't see them on respawn

**Expected behavior**
Java Players should show on death or dimension switch

**Screenshots / Videos**
N/A

**Server Version**

Minecraft: Java Edition 1.16.3

**Geyser Version**

This server is running Geyser version 1.1.0 (git-master-6638c53) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.100)

**Bedrock Version**
1.16.40

**Comment by DoctorMacc** [comment]
You are on a month-old version of Geyser. Please update! (And your issue will probably be fixed)
