### ISSUE TITLE
I can confirm that the bugg doesn’t happen on 1.8.8 tacospigot

### ISSUE THREAD

**Issue by Hyronymos1337** [GeyserMC/Geyser#1414]
I can confirm that the bugg doesn’t happen on 1.8.8 tacospigot

sign text is visible and readable

_Originally posted by @Hyronymos1337 in https://github.com/GeyserMC/Geyser/issue_comments/709872169_

**Comment by rtm516** [comment]
Closing this as its a duplicate of https://github.com/GeyserMC/Geyser/issues/603
Please don't copy your comments into new posts.
