### ISSUE TITLE
Spectator mode flying is slow

### ISSUE THREAD

**Issue by ImDaBigBoss** [GeyserMC/Geyser#1417]
**Describe the bug**
When flying around in spectator mode, I realized that it is painfully slow to move around.

**To Reproduce**
Go to spectator mode and fly around

**Expected behavior**
Flying should be just as fast as in creative mode.

**Screenshots / Videos**
None

**Server Version**
This server is running CraftBukkit version git-Spigot-988b411-055870c (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.1.0 (git-master-64f2233) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**
1.16.3

**Additional Context**
None needed

**Comment by Blobbie01** [comment]
You can edit speed with the scroll button on ur mouse, scroll up to go faster and down to go slower
