### ISSUE TITLE
Other players cannot join the server

### ISSUE THREAD

**Issue by Germanplayer578** [GeyserMC/Geyser#1420]
Hi.  Sorry for my bad english, i am german.

A few weeks ago I hosted a server at server.pro and installed GeyserMC on it. Everything went wonderfully at first sight. The server is shown to me as online and I can easily join it via the Bedrock version.

The problem, however, is that no one else can join. I was looking for players in Xbox lookup. (The players were filtered by Windows 10 players. So no Xbox players) However, all three people told me that their server is shown as offline and they cannot join. A buddy of mine reported the same problem.

Aternos has now announced that GeyserMC will be supported. (With Exaroton too). So I've now tried GeyserMc at Exaroton. Here again the same problem. For some reason, my buddy can access the server, but other people can't. Unfortunately, they couldn't help me on the Discord.

The server's ip is minepvp.exaroton.me

I don't currently have the server online 24/7.
At the time of the test, the server was of course online.

**Expected behavior**

**Screenshots / Videos**

**Server Version**
This server is running CraftBukkit version git-Spigot-57bbdd8-b8dd5ec (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.1.0 (git-master-64f2233) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
https://dump.geysermc.org/MAUiu4cIV3jCbXxV9y0LTVg9NKvVDTbi

**Comment by RednedEpic** [comment]
Please join us on discord for support with connection issues.
