### ISSUE TITLE
[1.16.100] Chunk wood button bug

### ISSUE THREAD

**Issue by TuskarMA** [GeyserMC/Geyser#1423]
**Describe the bug**
Some of the chunks seem to load not correctly 

**To Reproduce**
1) Load to the world

**Expected behavior**
Loading world without "artifacts"

**Screenshots / Videos**
https://youtu.be/8rwZzbhYkJA

**Server Version**
CraftBukkit version git-Spigot-57bbdd8-b8dd5ec (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**
1.1.0 (git-feature/1.16.100-ea4a40b)

**Minecraft: Bedrock Edition Version**
1.16.100.60

**Additional Context**
geyser dump - https://dump.geysermc.org/yfanEemv0zPS5Ngtfkm1Uh1hXh3K5aCP

**Comment by rtm516** [comment]
Since the 1.16.100 branch is currently in development, I would suggest moving back to master for a more stable experience.

**Comment by DoctorMacc** [comment]
I would agree. Regardless, thanks for reporting! That's one less bug that people will experience later on. I'll have a look before this gets merged into master.

**Comment by DoctorMacc** [comment]
This should now be fixed in the latest build - thanks so much for reporting! Feel free to keep testing these builds - the most testing they get, the more stable of an update we get for 1.16.100!
