### ISSUE TITLE
Faster Login

### ISSUE THREAD

**Issue by RehanPlayz** [GeyserMC/Geyser#1425]
**What feature do you want?**
Faster Login Time

**Alternatives?**
Current Login Time?

**Comment by DoctorMacc** [comment]
Hello, and thank you for reporting a feature request!
Geyser login speed is already pretty fast for what it has to handle, and if we knew how we could make it faster we would've already done that. I'm closing this as it doesn't mention a specific area we could improve on, but that doesn't mean we won't be interested in improving it in the future as time goes on - we do have a PR that may help improve it in the future.
