### ISSUE TITLE
Random Server kicks

### ISSUE THREAD

**Issue by Hyronymos1337** [GeyserMC/Geyser#1426]
**Describe the bug**
People get sometimes random kicked, maybe because they was afk for some seconds

**Screenshots / Videos**
https://www.youtube.com/watch?v=KSaj_C6tS7U

**Server Version**
1.8.8 Taco Spigot

**Geyser Version**
Latest Geyser BungeeCord & Floodgate

**Minecraft: Bedrock Edition Version**
Latest Minecraft Bedrock Edition (on Android)

**Comment by RednedEpic** [comment]
Unfortunately “randomly kicked” is too vague of a bug for us to investigate. This could be the result of many different factors that are non-Geyser related. We’ve had someone online on one Geyser instance for nearly 2 days before getting kicked (which wasn’t even Geyser related :P). I’ll be closing this issue for now, but if you have any sort of console error or steps that allow us to reproduce this issue consistently, please note so on this issue and we will reopen it.

**Comment by DoctorMacc** [comment]
This issue will likely be fixed with #1421.

**Comment by Hyronymos1337** [comment]
Thanks a mill
