### ISSUE TITLE
Not Viewing BedrockSkin and has a weird Star on the bedrock users name 

### ISSUE THREAD

**Issue by TheBlade21** [GeyserMC/Geyser#1427]
**Describe the bug**

**To Reproduce**

**Expected behavior**
 When a bedrock player joins that person is a steve or alex and has a star at the beginning or their name

**Screenshots / Videos**

**Server Version**
 1.16.3

**Geyser Version**

**Minecraft: Bedrock Edition Version**
 1.16.5

**Additional Context**

**Comment by RednedEpic** [comment]
This is intended behavior to prevent duplicate name entries across Java and Bedrock players. If you wish to remove the asterisk, there is an option in the Floodgate config to do so.

**Comment by DoctorMacc** [comment]
As for skins, that is currently missing behavior. For now you can use a plugin such as SkinsRestorer to restore the functionality.

**Comment by TheBlade21** [comment]
ok thankyou

**Comment by TheBlade21** [comment]
but where do i change the asterisk in the config

**Comment by DoctorMacc** [comment]
https://github.com/GeyserMC/Geyser/wiki/Floodgate

For further questions, please refer to our Discord.

**Comment by TheBlade21** [comment]
ok
