### ISSUE TITLE
Custom Crafting plugin not works

### ISSUE THREAD

**Issue by candrawardana** [GeyserMC/Geyser#1433]
Custom Crafting (https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-14-1-16-x-free.55883/) not works in bedrock, but Uncraftable plugin (https://www.spigotmc.org/resources/craft-the-uncraftable-fun.11379/) works

**Comment by RednedEpic** [comment]
Please follow the issue template.
