### ISSUE TITLE
Send the player ip in plugin message

### ISSUE THREAD

**Issue by JH3Y50N** [GeyserMC/Geyser#1436]
**What feature do you want?**
Send player ip using a plugin message to server like **GeyserUser:127.0.0.1**

**Alternatives?**
PR fail.

**Comment by RednedEpic** [comment]
Going to close this. Not the best way to forward information about a player and this info is already forwarded in Floodgate.

**Comment by Camotoy** [comment]
Additionally, the injection PR will provide correct player IPs no matter the authentication type, on most plugin platforms.
