### ISSUE TITLE
Slime Blocks glitched for bedrock users

### ISSUE THREAD

**Issue by OhNo2** [GeyserMC/Geyser#1437]
**Describe the bug**

When slime blocks are pushed upward for bedrock players instead of being shot into the sky they glitch through the floor
**To Reproduce**

1. Place slime block on a piston facing up
2. Activate piston with bedrock player on top of the slime block
3. Player will be glitched below slime block instead of launching into the air

**Expected behavior**

Player bounces up into the air
**Screenshots / Videos**

**Server Version**

git-Spigot-2740d5a-d5a7296
**Geyser Version**

git-master-ba6f174
**Minecraft: Bedrock Edition Version**

1.16.40
**Additional Context**

**Comment by DoctorMacc** [comment]
This happens with pistons without a slime block as well; you won't stay on the piston if it extends when you're on top.

**Comment by DoctorMacc** [comment]
From my testing, this is something that the Java player calculates clientside. Also, Bedrock does not have this feature; this doesn't make this feature impossible, just a little more difficult.
