### ISSUE TITLE
Rain issue

### ISSUE THREAD

**Issue by DaJokni** [GeyserMC/Geyser#144]
**Description**
This bug basically is that it rains when it shouldnt.

1. Clear the weather in the java world/server, rain will start on bedrock
2. When you start rain on the java world/server, it starts raining for bedrock edition.

**Expected behavior**
When weather is clear, it should be clear. When it rains, it should rain.
**Server version**
Latest travertine version (#127)
Subservers go from 1.8 to 1.15.2

**Geyser version**
https://github.com/GeyserMC/Geyser/suites/385301327/artifacts/958454

**Bedrock version**
Protocol version: 389
Build: 3561570

**Comment by RednedEpic** [comment]
> 4. See error
Could you provide said error?

**Comment by DaJokni** [comment]
Oh god i did that quickly and left the defaults there, an error is not shown.

**Comment by BenjiButton** [comment]
This is the same error that was reported and fixed in the protocol library
https://github.com/Steveice10/MCProtocolLib/pull/506
it is fixed in the latest version with 1.15.2

**Comment by DaJokni** [comment]
Ah

**Comment by RednedEpic** [comment]
> This is the same error that was reported and fixed in the protocol library
> [Steveice10/MCProtocolLib#506](https://github.com/Steveice10/MCProtocolLib/pull/506)
> it is fixed in the latest version with 1.15.2

This error was noticed using the latest version of Geyser that has that commit in it. I’m thinking that this commit may be causing this issue, but more testing is needed.

**Comment by LegacyGamerHD** [comment]
I have it as well

**Comment by LegacyGamerHD** [comment]
I can confirm

**Comment by RednedEpic** [comment]
Resolved in Steveice10/MCProtocolLib#514. Once merged this issue will be closed.

**Comment by RednedEpic** [comment]
PR referenced above has been merged. Closing.
