### ISSUE TITLE
Player Y position is incorrectly rounded on the ground

### ISSUE THREAD

**Issue by Benedani** [GeyserMC/Geyser#1440]
**Describe the bug**
This seems to be the cause of issues such as being unable to step on certain blocks. Basically, whenever the player stands on a block that is not exactly slab-sized (e.g. farmland, soulsand, chests, beds), their position is rounded up to the next 0.5 step, even if the client sees themselves as correctly standing on the block.

**To Reproduce**
1. Join the server on a Bedrock client, and watch from a different player's perspective (other Bedrock clients work too)
2. Place any block that doesn't exactly round to 0.5.
3. Walk on the block.
4. From a different player's perspective, they should now be hovering above the block.

**Expected behavior**
The player should be standing on the block, at least with the hitbox the Bedrock client uses.

**Screenshots / Videos**
![broken](https://cdn.discordapp.com/attachments/355785621454716958/769168544130531328/unknown.png)

**Server Version**
1.16.2 (git-Paper-189)

**Geyser Version**
1.1.0 (git-master-62d984d), running on Waterfall

**Minecraft: Bedrock Edition Version**
1.16.40

Edit: added Bedrock Edition version thanks to MotooKong.

**Comment by DoctorMacc** [comment]
Thanks for reporting this! We're compiling all our general movement issues into #204, and as the movement PR will fix this behavior and for cleanliness I will close this specifically PR. Thank you anyway for reporting this!
