### ISSUE TITLE
/geyser reloadskin

### ISSUE THREAD

**Issue by Roadhog360** [GeyserMC/Geyser#1442]
**What feature do you want?**
Sometimes, your skin gets "Steved" or "Alexed" and you have to rejoin the server. My solution is a command, /geyser reloadskin, a player can type to reload their skin on their end.

**Alternatives?**
Rejoining the server (Annoying)

**Comment by DoctorMacc** [comment]
Thanks for reporting! However, I'm going to close this as this is something we would only implement as a worst-case option. The better solution would be to prevent the skin from being Steve in the first place.

**Comment by DoctorMacc** [comment]
(You can make an issue for that, assuming you're on the latest Geyser version)

**Comment by DoctorMacc** [comment]
(You can make an issue for that, assuming you're on the latest Geyser version)
