### ISSUE TITLE
Can't trade itens with NPC

### ISSUE THREAD

**Issue by JH3Y50N** [GeyserMC/Geyser#1447]
**Describe the bug**

I can't trade items with NPC the items are not traded and also the items add to the inventory it is necessary to update the inventory for them to come back.

**To Reproduce**

Try to trade with villager

**Expected behavior**

trade with NPC

**Screenshots / Videos**

![2020-10-25_07-30-54](https://user-images.githubusercontent.com/29031972/97104697-a8544d00-1694-11eb-9c3b-54465f7e6637.gif)
![2020-10-25_07-39-51](https://user-images.githubusercontent.com/29031972/97104790-519b4300-1695-11eb-855b-40d0dbbf9a48.gif)

**Server Version**

PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Geyser Version**

1.1.0 (git-master-7f2b2e0) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**

1.16.40

**Additional Context**

**Comment by rtm516** [comment]
Can you provide a dump?

**Comment by JH3Y50N** [comment]
> Can you provide a dump?

https://dump.geysermc.org/GHDorwAYmPO8eqdxcl7WI34s7hyFekib

**Comment by JH3Y50N** [comment]
@rtm516 then?

> > Can you provide a dump?
> 
> https://dump.geysermc.org/GHDorwAYmPO8eqdxcl7WI34s7hyFekib

**Comment by JH3Y50N** [comment]
this issue has already been fixed, I don't remember the update number but this are fixed.
