### ISSUE TITLE
Bedrock players can't see items on Java players' hands

### ISSUE THREAD

**Issue by linmiao233** [GeyserMC/Geyser#145]
**Describe the bug**
Bedrock players can't see items on Java players' hands

**To Reproduce**
1. Java player holds items in his hand
2. Bedrock players watch

**Screenshots**
![image](https://s2.ax1x.com/2020/01/28/1K1Uh9.jpg?raw=true)
![image](https://s2.ax1x.com/2020/01/28/1K1dpR.jpg?raw=true)
![image](https://s2.ax1x.com/2020/01/28/1K1tk4.jpg?raw=true)
![image](https://s2.ax1x.com/2020/01/28/1K1J7F.jpg?raw=true)

**Geyser version**
#67 

**Bedrock version**
1.14.1

**Comment by AJ-Ferguson** [comment]
Resolved in the latest commit of #67
