### ISSUE TITLE
Available for Mac

### ISSUE THREAD

**Issue by GreenPotatoe** [GeyserMC/Geyser#1452]
I tried downloading the .jar file on my mac, then proceed to run it. I did get the necessary files, but I wasn't able to connect to my custom server on my android device. I've followed the instructions correctly and still did not work, so I wondered that maybe it isn't compatible for Mac. Maybe you could add a version available for mac?

**Comment by toinouH** [comment]
Hello.
1. For assistance join our Discord please
2. If it's a real issue please follow the issue template.
Have a nice day

**Comment by Heath123** [comment]
To be clear, Geyser already works on Mac. Your issue is probably something else...
