### ISSUE TITLE
Bedrock players are able to hit others player while crouching with shield.

### ISSUE THREAD

**Issue by SrFakon** [GeyserMC/Geyser#1453]
**Describe the bug**
Bedrock players can activate the shield and attack at the same time while Java players can't. The shield still protects the player from other players attack.

**To Reproduce**
1. Take a shield
2. Put the shield on the 2nd hand
3. Crouch
4. Use the main hand
5 *Optional*. Call another player to try to hit you while you're doing steps 3 and 4.

**Expected behavior**
The Bedrock player can attack and defend at the same time.

**Screenshots / Videos**
[Video](https://youtu.be/dZdFVXfbqpA)

**Server Version**
git-Paper-246 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**
Geyser version 1.1.0 (git-master-c30cb78) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**
Minecraft Windows 10 Edition. 1.16.40

**Additional Context**
https://dump.geysermc.org/Cl4FKOFipaRmfH4IxHw8AkHFbjYDv9r3

**Comment by Camotoy** [comment]
As an extension to this, it appears that Java can do zero interactions whilst blocking.

**Comment by RednedEpic** [comment]
To follow from the above, this is likely no longer an issue with the updated mechanics. Closing.
