### ISSUE TITLE
custom heads

### ISSUE THREAD

**Issue by elaineandsparky** [GeyserMC/Geyser#1454]
Decorative heads from the plugin head database show as steve heads for bedrock players.

Skulls spawned in using /skull are also showing as steve.

https://www.spigotmc.org/resources/head-database.14280/

I believe we are using build #442 as i updated to latest bungeecord jar this morning.

**Comment by rtm516** [comment]
1. Please follow the issue template
2. This is due to a bedrock limitation
3. We are working on a work around: https://github.com/GeyserMC/Geyser/pull/683
