### ISSUE TITLE
Allow players to crawl by forcing them into swim mode

### ISSUE THREAD

**Issue by SpySter** [GeyserMC/Geyser#1455]
**What feature do you want?**
It should be able to allow bedrock players to crawl like how you can in java currently on bedrock it looks like java players are walking through a wall. But if you force the bedrock players into either elytra fly mode or swim mode they could crawl through 1x1 holes

**Alternatives?**
List any alternatives you might have tried
I currently use command blocks to spawn water to force bedrock players into swim mode so they can crawl in my mazes.

**Comment by ZandercraftGames** [comment]
Elytra fly mode would cause extreme movement bugs (as far as I can tell), but putting them into swim and sending the client information saying that they have a slowness potion to a level that slows the client down to normal crawling speed could potentially work.

**Comment by Camotoy** [comment]
This has been implemented in Geyser! It may be a little buggy but the trapdoor method works for sure.
