### ISSUE TITLE
Players can't move through 1.5 black gaps

### ISSUE THREAD

**Issue by xXTeraXx** [GeyserMC/Geyser#1456]
**Describe the bug**
Players cannot move through 1.5 block gaps. Eg a 2x1 gab with a slab in the top or bottom. 

**To Reproduce**
Make a geyser server using geyser bungee/spigot

Make a 2x1 doorway (without a door) place a slab in the doorway at the top. 

Players on java can move through these gaps while sneaking, but bedrock players cannot 

(I know that this is a bedrock thing but I really need a fix for it.) 

**Expected behavior**
Players can move through the gap as though they were on java

**Server Version**
Paper 1.16.3 latest build.  Bungeecord (NOT waterfall) 1.8-1.16 (was downloaded 10/26)

**Geyser Version**
Geyser 1.1.0 (git-master-dfba278). Floodgate is installed though account used for testing was a linked java account

**Minecraft: Bedrock Edition Version**
1.16.4.0

**Additional Context**
<!--- Add any other context about the problem here. 

Server is on paper with coreprotect

https://dump.geysermc.org/VCiMnwc0gbTBaWQSaFy4i9xc2gCVusNk

**Comment by RedSmarty** [comment]
Maybe, this can conflict with anticheat. Correct me if i am wrong.
But u can make a behaviour pack to decrease player size. I am not sure how behaviour packs will work, but i am just a noob. xD

**Comment by Hellohi3654** [comment]
It is possible to modify player hitboxes on the client end
Behavior packs can do this so I believe it is possible

**Comment by xXTeraXx** [comment]
Any idea of how I would do this.  I need the player to be 2 blocks tall until they go through the gap while crouching.  Maybe I can use the crouch button as the activator but I have no idea how to make bedrock behavior packs

**Comment by zimzaza4** [comment]
It should be possible to modify the collision box

**Comment by zimzaza4** [comment]
At least nukkit can change the size of the player's collision box through the plugins

**Comment by rtm516** [comment]
> At least nukkit can change the size of the player's collision box through the plugins

Could you link one of these plugins?

**Comment by zimzaza4** [comment]
> > At least nukkit can change the size of the player's collision box through the plugins
> 
> Could you link one of these plugins?

I'm not very clear about that
But I found a small game in the easecation server that changed the player's collision box

**Comment by zimzaza4** [comment]
> > At least nukkit can change the size of the player's collision box through the plugins
> 
> Could you link one of these plugins?

What I can provide at present:
![IMG20201028205546](https://user-images.githubusercontent.com/53421735/97438727-29933480-1960-11eb-8bac-093d3187eb97.jpg)

**Comment by zimzaza4** [comment]
Normal players:
![IMG20201028205519](https://user-images.githubusercontent.com/53421735/97438775-39ab1400-1960-11eb-8f37-a8612415eba5.jpg)
