### ISSUE TITLE
Im having an issue with my MCPE server it becomes non usable after some time of inactivity and just gives the message locating server and only becomes playable after executing geyser reload command and this happens frequently how can i fix this Geyser dump : https://dump.geysermc.org/NNxefk5thJqy3iSzpFBfvQaFJGAVM10V

### ISSUE THREAD

**Issue by nanduharidas** [GeyserMC/Geyser#1458]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by xXTeraXx** [comment]
I'm not a geyser dev but YOU NEED TO FILL OUT THE FORM.  It is the only way that people can help you.  All I can tell you is try with a clean install.  If the devs or other people cannot reproduce the issue clean install is likely the only advice you're going to get

**Comment by nanduharidas** [comment]
> I'm not a geyser dev but YOU NEED TO FILL OUT THE FORM. It is the only way that people can help you. All I can tell you is try with a clean install. If the devs or other people cannot reproduce the issue clean install is likely the only advice you're going to get

which form?

**Comment by TheMasterBlaster** [comment]
You left all these blank.
![Screenshot_20201027-122759_Edge](https://user-images.githubusercontent.com/9083212/97331593-f1043580-184f-11eb-8cc9-cc15589f3e56.jpg)
