### ISSUE TITLE
Ominous Banner doesnt display correctly

### ISSUE THREAD

**Issue by Carbuino** [GeyserMC/Geyser#1461]
**Describe the bug**
Due to limitations with Banner Patterns in Bedrock Edition, the Ominous Banner doesnt display correctly.

**To Reproduce**
1. Obtain an Ominous Banner
2. Place the banner

**Expected behavior**
The banner is expected to look the game way it does in Java Edition

**Screenshots / Videos**
![Ominous_Banner](https://user-images.githubusercontent.com/19510288/97359633-ac35ca00-1862-11eb-9e60-fb28f966bcb1.png)
![Screenshot_20201027-142653_Minecraft](https://user-images.githubusercontent.com/19510288/97359644-afc95100-1862-11eb-935b-021841eef513.jpg)

**Server Version**
PaperMC 1.16.3 (build 245)

**Geyser Version**
GeyserMC 1.1.0 (git-Master-62d984d) on Waterfall

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
None

**Comment by DoctorMacc** [comment]
While this can be solved, we would have to remove another layer at this time to get it to work, and we would also have to specifically check for the ominous banner. 
Alternatively, we could replace the ominous banner Java pattern with its Bedrock alternative which I would be open to.

**Comment by ZandercraftGames** [comment]
I would say that probably the second option would be the most sensible, as there are already differences in texture with other things in the game. That's just my opinion, though.
