### ISSUE TITLE
Add achievement support and commands disabling in the configuration.

### ISSUE THREAD

**Issue by Meta-link** [GeyserMC/Geyser#1463]
**What feature do you want?**
Having achievements and the ability to disable commands for bedrock clients (both are needed to get Xbox achievements working) using the configuration file.

**Alternatives?**
I was able to have achievements working on bedrock with the advices of @rtm516 (who asked me to create this post) by modifying these two lines before rebuilding : 
https://github.com/GeyserMC/Geyser/blob/a2a7e99402d3f074141f7b70f49212ed720a740d/connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java#L626
https://github.com/GeyserMC/Geyser/blob/a2a7e99402d3f074141f7b70f49212ed720a740d/connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java#L637

But it would be way more practical to have them in the configuration file instead of having to rebuild Geyser to enable or disable them.

**Comment by Roadhog360** [comment]
Why do you need to disable commands to get achievements working?

**Comment by Chew** [comment]
"Commands" are considered cheats. Once cheats are enabled, you cannot earn achievements anymore.
