### ISSUE TITLE
Scoreboards in different worlds don't unload when switching to other worlds.

### ISSUE THREAD

**Issue by vijaypondini** [GeyserMC/Geyser#1470]
**Describe the bug**
Scoreboards which I have automatically made to load when joining a world, don't get removed when I switch back to a world without a scoreboard.

**To Reproduce**
Make a world automatically load a scoreboard upon joining ( in this case I use a skywars plugin that auto loads the scoreboard upon a player join) https://www.spigotmc.org/resources/skywarsreloaded-updated-recoded-1-16-support-new-features-1-8x-1-16x.69436/
/mv tp to the world and then tp back to a world where the scoreboard should not be auto loaded.

**Expected behavior**
Scoreboard should unload upon exiting the world.
**Please note that this issue happens only on bedrock clients and not java clients**_so I highly doubt it's a plugin problem._

**Screenshots / Videos**
https://imgur.com/a/IpzuyEl

**Server Version**
 server is running Paper version git-Paper-174 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
Previous version: git-Paper-135 (MC: 1.16.1). 15 version(s) behind

**Geyser Version**
 server is running Geyser version 1.1.0 (git-master-ba6f174) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)
42 versions behind. Using floodgate bukkit as well

**Minecraft: Bedrock Edition Version**
Bedrock 1.16.5 ( latest )

**Additional Context**
https://dump.geysermc.org/7SKVrc5sw8yN6r0pSvIi8pcsOSMpxTaM

**Comment by DoctorMacc** [comment]
Please update Geyser and re-test.

**Comment by vijaypondini** [comment]
Retested with updated geyser, works. 
You can close this issue
