### ISSUE TITLE
Fire is not showing up on sea lanterns

### ISSUE THREAD

**Issue by mjcox244** [GeyserMC/Geyser#1471]
**Describe the bug**

when you put fire on a sea lantern it doesnt show up on bedrock cliants
**To Reproduce**

 1. Go to any world
2. set sea lantern on fire
3.it wont be visible on bedrock but intractable
4.shows up and work fine on java
**Expected behavior**

be able to see fire on it
**Screenshots / Videos**

**Server Version**

[13:50:37 INFO]: This server is running Paper version git-Paper-249 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[13:50:37 INFO]: Checking version, please wait...
[13:50:37 INFO]: You are 2 version(s) behind

**Geyser Version**

[13:51:10 INFO]: This server is running Geyser version 1.1.0 (git-master-a2a7e99) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)
[13:51:10 INFO]: Checking version, please wait...
[13:51:10 INFO]: No updates available.
**Minecraft: Bedrock Edition Version**

1.16.40 xboxone
**Additional Context**

https://dump.geysermc.org/j6lE45hEVdDIXA4D7yBCC3P6cvngLe5b

**Comment by toinouH** [comment]
https://cdn.discordapp.com/attachments/613169789900161035/771366613902688306/unknown.png
https://cdn.discordapp.com/attachments/613169789900161035/771366781524115486/20201029_133606.jpg
#support-2

**Comment by DoctorMacc** [comment]
This also happens on a vanilla Bedrock world, and therefore may be unfixable.

**Comment by Roadhog360** [comment]
In older versions of Minecraft, fire used to only work when touching a flammable block, or else it would disappear and be invisible beforehand. It's a good possibility Bedrock is still this way.

**Comment by RednedEpic** [comment]
Closing as this is a Bedrock limitation and there isn't really anything we can do regarding this issue.
