### ISSUE TITLE
Geyser on Velocity not working

### ISSUE THREAD

**Issue by loganj2010** [GeyserMC/Geyser#1473]
Ok so I set up a server (using velocity) with the geyser plugin and when ever I join the right ip and everything works but I disconnect because apparently I "Log in too fast" please help.

**Comment by DoctorMacc** [comment]
In the future, please follow the issue template. However, I would recommend you join the Geyser Discord for this kind of issue if you haven't. Thank you!

**Comment by loganj2010** [comment]
What do you mean? I'm new to this.. Sorry

**Comment by DoctorMacc** [comment]
If the issue persists, join us on Discord in one of our support channels: https://discord.geysermc.org.

**Comment by loganj2010** [comment]
Geyser version 1.1.0
Bedrock 1.16.40
iPad 4
iOS 9.3.6
umm I don't know anything else to put here sorry

**Comment by loganj2010** [comment]
iPad 3 sorry

**Comment by loganj2010** [comment]
I'll show a screenshot hold on

**Comment by loganj2010** [comment]
I can't show a screen shot now it won't let me

**Comment by loganj2010** [comment]
I can't show a screen shot now it won't let me

**Comment by loganj2010** [comment]
![IMG_2168](https://user-images.githubusercontent.com/66440439/97704471-59e6ea00-1aaa-11eb-9075-8dc57f641931.PNG)

**Comment by loganj2010** [comment]
@DoctorMacc where is the issue template??

**Comment by rtm516** [comment]
You can find the issue template https://github.com/GeyserMC/Geyser/issues/new?assignees=&labels=&template=bug_report.md&title=
But for this issue please join our discord to resolve it.

**Comment by NT-Corp** [comment]
thanks
