### ISSUE TITLE
Crafting Table GUI doesn't show proper header

### ISSUE THREAD

**Issue by snaildos** [GeyserMC/Geyser#1479]
**Describe the bug**
When people join my server, bedrock and java, they get moved into a authentication where there IP gets logged and the ban system registers them as well as some behind the scenes movement. Another thing that happens is a user has to register for there account on the server. 

However: Bedrock players dont know what to do:
On java: 
![image](https://user-images.githubusercontent.com/46210117/97793439-dd2d4a80-1c26-11eb-939b-e27f27f83681.png)
On bedrock:
![image](https://user-images.githubusercontent.com/46210117/97793533-3e095280-1c28-11eb-8971-994dd73df4e3.png)

**To Reproduce**
Change "Crafting to a custom title"

**Expected behavior**
Crafting should be the custom one.

**Screenshots / Videos**
Already displayed. 

**Server Version**
Latest paper
Latest bukkit

**Geyser Version**

1.1.0 23 builds behind

**Minecraft: Bedrock Edition Version**
latest

**Additional Context**
Nothing else.

**Comment by DoctorMacc** [comment]
Update Geyser. This should be fixed.

**Comment by snaildos** [comment]
![image](https://user-images.githubusercontent.com/46210117/97793652-ccca9f00-1c29-11eb-9122-9673d09b31e3.png)
still crafting

**Comment by DoctorMacc** [comment]
https://dump.geysermc.org/0DjBIY3ndgfhGZV3lThMLs9tamhJqQw8

**Comment by rtm516** [comment]
After looking into this more, it looks like a bedrock limitation.

**Comment by snaildos** [comment]
Is this defiantly correct? There is no way to change the crafting table header text?

**Comment by rtm516** [comment]
From what I can tell no, I have not found any information to prove otherwise and we send the titles the same way as we do for chests so if bedrock does start supporting it with the same method it will start to work.
