### ISSUE TITLE
Linux steps on wiki doesn't work

### ISSUE THREAD

**Issue by Sprtcrnbry** [GeyserMC/Geyser#148]
**Describe the bug**
The linux script doesn't work, and the how to run the script is actually to make the script have executable permissions.

**To Reproduce**
1. Go to https://github.com/GeyserMC/Geyser/wiki/Creating-a-Startup-Script#linux
2. Scroll down to "Linux"
3. Use the steps listed

**Expected behavior**
Scripts will run.

**Screenshots**
![Screenshot_20200130_170510](https://user-images.githubusercontent.com/17063780/73439808-ccdbfc80-4382-11ea-885a-b6bbaab35c45.jpg)

**Server version**
latest

**Geyser version**
Jenkins

**Bedrock version**
1.14.2

**Additional context**
`#!/bin/sh BINDIR=$(dirname "$(readlink -fn "$0")") cd "$BINDIR"; java -jar Geyser.jar` Corrected the code for script, added command separators.
`~/(dir)/run.sh` is the correct steps to run the script, and `chmod +x ~/(dir)/run.sh` is to add executable permissions.

**Comment by LegacyGamerHD** [comment]
works fine for me

**Comment by EOT3000** [comment]
any error?

**Comment by alissonlauffer** [comment]
There are missing newlines for the script to work.

**Comment by RisksY** [comment]
I downloaded jar then running it via` java -jar Geyser.jar`

**Comment by RednedEpic** [comment]
Updated wiki with instructions that were tested by others on Discord.
