### ISSUE TITLE
GSit crashes Bedrock players

### ISSUE THREAD

**Issue by soshimee** [GeyserMC/Geyser#1480]
**Describe the bug**
Using GSit to /lay or /crawl crashes the Bedrock client.

**To Reproduce**
1. Install plugin GSit
2. Use /lay or /crawl.
3. Enjoy Bedrock client struggle.

**Expected behavior**
Working like it does in Java

**Screenshots / Videos**
None

**Server Version**
This server is running Tuinity version git-Tuinity-"de1983b" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.1.0 (git-master-ca1f87d) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20) (Geyser-Spigot)

**Minecraft: Bedrock Edition Version**
1.16.10

**Additional Context**
https://dump.geysermc.org/TcNoK6Z6DvZLJbKUmOBodc4nyoN15zR5

**Comment by andrew121410** [comment]
I have gsit running on my city server and /sit doesn’t crash the bedrock client but /crawl does though.

**Comment by DoctorMacc** [comment]
I'm going to consolidate this with #1121. Regardless, thanks for reporting!
