### ISSUE TITLE
Fire is invisible when launched from a blaze

### ISSUE THREAD

**Issue by roymercenary** [GeyserMC/Geyser#1482]
**Describe the bug**
All fire that is created from a blaze projectile turns invisible when they land

**To Reproduce**
go into survival mode
be noticed by blaze
wait for it to attack you
when the projectiles land the fire is invisible

**Expected behavior**
when the projectiles land they are supposed to create a visible fire

**Screenshots / Videos**
NA

**Server Version**
 1.16.3

**Geyser Version**
1.1.0 build 432

**Minecraft: Bedrock Edition Version**
1.16.2

**Additional Context**

**Comment by RednedEpic** [comment]
Unable to reproduce anything relating to Geyser here. In any instance where no fire was placed, the Java client did not see it either, so it's not a Geyser problem here.
