### ISSUE TITLE
common's POM.xml isn't calling the correct version for parent

### ISSUE THREAD

**Issue by otctaudio** [GeyserMC/Geyser#1484]
**Describe the bug**
When running a maven search at  https://repo.opencollab.dev/maven-snapshots/, an error comes up involving the common repository. The versioning in the pom.xml is literally just "parent" when it should be '1.0-SNAPSHOT'

**To Reproduce**
download POM file here https://repo.opencollab.dev/maven-snapshots/org/geysermc/common/1.0-SNAPSHOT/common-1.0-20200708.191042-432.pom

read <parent> version number

**Expected behavior**
version should be 1.0-SNAPSHOT so it downloads the correct pom for the parent repo.

**Comment by DoctorMacc** [comment]
This should now be fixed.
