### ISSUE TITLE
Command line arguments 

### ISSUE THREAD

**Issue by CreaZyp154** [GeyserMC/Geyser#1485]
Command line argument would allow to override some setting in the config.yml file

Example:
`java -jar geyser.jar --server-ip test.geysermc.org`
(syntax might be different)

This would save so much time when we want to try out some settings or just simply switch the server.

This also open doors for custom scripts that can do pretty much everything you want: from a simple server list to a web based manager, the list is just infinite

Alternative:

For now we can run a script that changes the config.yml file but it's not perfect.

**Comment by JH3Y50N** [comment]
--server-port --server-name --server-threads and more...

**Comment by Chew** [comment]
If you add too many flags you might as well just --config file.yml at that point

**Comment by lukeeey** [comment]
I would say simply allow specifying config keys as arguments like pmmp and nukkit, but only if we can guarantee the config wouldn't change often as those arguments would break

**Comment by CreaZyp154** [comment]
> If you add too many flags you might as well just --config file.yml at that point

Yea both options should be possible
