### ISSUE TITLE
Beacon gui doesn't open on bedrock

### ISSUE THREAD

**Issue by ChargerSRT64** [GeyserMC/Geyser#1489]
**Describe the bug**
Beacon gui will not open for bedrock clients. works fine in java. when clicking Beacon nothing happens

**To Reproduce**
1. Place a beacon
2. click Beacon
3. Nothing happens

**Expected behavior**
Beacon gui should open when clicking a beacon

**Server Version**
Paper 251 on java 1.16.3

**Geyser Version**
geyser #459 on bungeecord

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
the player an i both tested with same result. he said it did this on another server as well with unknown version.
https://dump.geysermc.org/AEjwBS4DcyTpYJxZ8herl5tt1OE3f6tb

**Comment by E404NNF** [comment]
Known issue

**Comment by hteppl** [comment]
Look at readme 👀

**Comment by Chew** [comment]
This is currently being worked on, it's known. Closing as we don't need open issues for to-do list items.
