### ISSUE TITLE
Sounds from java edition do not play in bedrock clients

### ISSUE THREAD

**Issue by Seamusmario** [GeyserMC/Geyser#149]
**Describe the bug**
Sounds from java edition do not play in bedrock clients.

**To Reproduce**
Eat something, break something or shoot a arrow.
**Expected behavior**
Bedrock should play sounds from java

**Geyser version**
Jenkins

**Bedrock version**
1.14.1

**Comment by RednedEpic** [comment]
This is stated as something to be implemented in the README. Next time, please make sure you aren't opening an issue for an already known issue or a feature being worked on still. Also, next time follow the issue format rather than using the template and only having your issue in the title.

**Comment by Seamusmario** [comment]
Understandable.
