### ISSUE TITLE
UX for Using Command 

### ISSUE THREAD

**Issue by data-dataninja** [GeyserMC/Geyser#1490]
**What feature do you want?**
Typing Command stop freezing client

**Alternatives?**
I turned suggestions to false (as in the FAQ), however it still often freeze the client, I have it to false on all my servers, all servers have the same issue.

kindly help address the issue or point us to the right direction

THANK U for your dev on Geyser & its revolutionary & life-saver for us

**Comment by rtm516** [comment]
Toggling the option in the config will stop the command list being sent to the client so should prevent the crash/freeze. Can you provide a dump using `geyser dump` in the server console?

**Comment by RednedEpic** [comment]
Command freezing seems to be much better on 1.16.100+, but ultimately there is nothing we can really do as this is a client problem. Closing.
