### ISSUE TITLE
name item dont show correctly

### ISSUE THREAD

**Issue by TOWUK** [GeyserMC/Geyser#1493]
**Describe the bug**
formatting text italic from normal?

**To Reproduce**
just install deluxehub3 plugin
join on server

**Expected behavior**

**Screenshots / Videos**
![Снимок экрана 2020-11-04 102948](https://user-images.githubusercontent.com/28830162/98082277-86737b00-1e89-11eb-8389-7e30b2ce03d1.png)
![Снимок экрана 2020-11-04 103015](https://user-images.githubusercontent.com/28830162/98082290-8a9f9880-1e89-11eb-89ae-5e27728cf29d.png)

**Server Version**
dump

**Geyser Version**
dump

**Minecraft: Bedrock Edition Version**
1.16.40 (408 protocol)

**Additional Context**
https://dump.geysermc.org/JnqquABhaJWuYS3tRM7Kf71jGAkWtJqk

**Comment by HyperSkys** [comment]
If I am not wrong, maybe this is a problem with your phone lang settings or mc lang settings? because I don't see this issue I am just running a test server

**Comment by Chew** [comment]
Good point. Can you try with your font set to Mojangles? I highly doubt it's the issue but it's one less step in diganosing.

**Comment by DoctorMacc** [comment]
This is fixed in the chat rewrite - RTM could explain it better but it has to do with resetting chat formatting.
