### ISSUE TITLE
Invisble blocks above nether roof

### ISSUE THREAD

**Issue by Cwickks** [GeyserMC/Geyser#1494]
**Describe the bug**
Invisble blocks above nether roof

**To Reproduce**
Go to PC, Make hole in nether roof
Destroy the old portal then place it on the nether roof
Go to mobile
Enter portal
See magic

**Expected behavior**
You will be able to see blocks & the building height error will not show

**Screenshots / Videos**

**Server Version**
1.16.4

**Geyser Version**
1.1.0

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**

**Comment by DoctorMacc** [comment]
There is an option in the config to allow above Bedrock Nether building.
