### ISSUE TITLE
Unable to go down on scaffolding

### ISSUE THREAD

**Issue by Cwickks** [GeyserMC/Geyser#1495]
**Describe the bug**
Unable to go down on scaffolding

**To Reproduce**
Put scaffolding on Java Edition
Go to Pocket Edition
Step on top of scaffolding

**Expected behavior**
When crouching, expected to go down

**Screenshots / Videos**

**Server Version**
1.16.4

**Geyser Version**
1.1.0

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**

**Comment by DoctorMacc** [comment]
Since the entirety of scaffolds do not work correctly, I'm consolidating this into #617. Thank you for reporting anyway!
