### ISSUE TITLE
Bedrock users do not Spawn in correct place. Presumed gamerule Spawnradius issue.

### ISSUE THREAD

**Issue by EliasRipley** [GeyserMC/Geyser#1496]
**Bedrock users do not spawn on spawn block.**
In our Java world, we have players join on the block 0, 0 as this is a nice easy coord to remember for users and admins.
After installing Geyser we noticed that Bedrock players are spawning around that location, yet not on the exact block. 
Gamerule spawnradius seems to be ignored for Bedrock users.

**To Reproduce**
Create a world.
Use /setworldspawn
Use /gamerule spawnRadius 0
Connect via Bedrock in Geyser.

**Expected behavior**
To spawn on the exact block of where you used /setworldspawn

**Screenshots / Videos**

**Server Version**
1.16.3 (Using ViaVersion)

**Geyser Version**
#462
Note that we also use Floodgate build #25.

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
Dump:
https://dump.geysermc.org/T8azrlvACaSIlK9dBvfS82XRBphooyrX

**Comment by Thrasilias** [comment]
Can confirm this isnt an gamerule spawnradius issue. I have it disabled on my server and people spawn around spawn location

**Comment by DoctorMacc** [comment]
I would suspect this is not an issue on our end (I may very well be wrong) - that gamerule is not indicated to the client over the network, nor, to Thras's comment, is there any range sent to the player.

**Comment by snaildos** [comment]
I can confirm this happens too.

**Comment by monckey100** [comment]
I would just like to reconfirm that this issue is still present

**Comment by Camotoy** [comment]
Please create a new issue with replication steps. Thank you!

**Comment by monckey100** [comment]
I have isolated the issue, bedrock players will spawn at the highest block possible and will avoid lower blocks if there is a higher block present.
