### ISSUE TITLE
custom nametags dont show up

### ISSUE THREAD

**Issue by LegacyGamerHD** [GeyserMC/Geyser#150]
**Describe the bug**

**To Reproduce**
1. add nametagedit
2. create a custom nametag
3. it wonts show up on bedrock players

**Expected behavior**
should look like:

![2020-02-02_10 38 34](https://user-images.githubusercontent.com/25864932/73613212-40ab1e80-45a8-11ea-90e9-906e0828d71c.png)

**Server version**
![image](https://user-images.githubusercontent.com/25864932/73613235-69331880-45a8-11ea-95f7-6da09520615d.png)

**Geyser version**
latest

**Bedrock version**
latest

**Comment by EOT3000** [comment]
so, do you mean the nametag item or the nametag as in the thing above the player?

**Comment by LegacyGamerHD** [comment]
@EOT3000  the nametag above the player
