### ISSUE TITLE
Support with 1.8.9 servers

### ISSUE THREAD

**Issue by usedframebr** [GeyserMC/Geyser#1500]
**What feature do you want?**
Support to connect with 1.8.9 java servers

**Alternatives?**
Support with 1.8.9 - 1.16.3

**Comment by RednedEpic** [comment]
Install ViaVerion on the server or have the server owner install it if its not your server. Supporting 1.8 is not something we're planning on doing.

**Comment by Soulstarop** [comment]
but how bedrock client join through any any version of bedrock to a old java version java like 1.8.9
I am really want it. I have make a skyblock server in java and I want to make it crossplay server

**Comment by NoobMC105** [comment]
Pre 1.12 support is removed and using them on 1.12 to 1.16 will require you to have ViaVersion also you cannot join from any version of bedrock the latest geyser works with 1.17 bedrock only
