### ISSUE TITLE
Phantom Blocks

### ISSUE THREAD

**Issue by xXTeraXx** [GeyserMC/Geyser#1503]
**Describe the bug**
Blocks do not have the right name and have the wring texture.  Or blocks appear to be something else

**To Reproduce**
This was reported by one of my players.  He did not say how to reproduce the bug.

**Expected behavior**
Blocks have to be working normally.
**Screenshots / Videos**
https://youtu.be/T4bK4BeaLmw

**Server Version**

**Geyser Version**
Geyser version 1.1.0 (git-master-dfba278) With floodgate
**Minecraft: Bedrock Edition Version**

1.16.4.0
**Additional Context**
 https://dump.geysermc.org/vynGB1SRY77J473kHSKZoyRQGXlT91wE

**Comment by DoctorMacc** [comment]
You're not on the latest version of Geyser - update (along with ViaVersion) and see if the issue still persists. Additionally, make sure that normal 1.16.4 clients do not experience the same issues.
