### ISSUE TITLE
Bedrock can’t connect to Java server (Displays “outdated client”, despite both versions being on the latest)

### ISSUE THREAD

**Issue by Budderman18** [GeyserMC/Geyser#1507]
So i run a server with Geyser. The first time i downloaded Geyser was on Spigot 1.16.4. However, bedrock users can’t connect to it. My guess is because bedrock’s latest version is “1.16.50”. I know for a fact that there will never be a 1.16.50 for java, but it wouldn’t make sense for it to not work.

**Comment by rtm516** [comment]
Please follow the issue template next time, but for this issue come over to our Discord server to resolve this.
https://discord.geysermc.org/
