### ISSUE TITLE
armor wont show up for pc clients on bedrock

### ISSUE THREAD

**Issue by LegacyGamerHD** [GeyserMC/Geyser#151]
**Describe the bug**

**To Reproduce**
1. put on armor on pc
2.  see result

**Expected behavior**
you should see that a player is wearing armor

**Server version**
![image](https://user-images.githubusercontent.com/25864932/73613303-f37b7c80-45a8-11ea-839c-a178bc09b27b.png)

**Geyser version**
latest

**Bedrock version**
latest

**Additional context**

**Comment by RednedEpic** [comment]
Is this error able to be observed on normal entities as well?

**Comment by LegacyGamerHD** [comment]
entitys are fine

**Comment by LegacyGamerHD** [comment]
seems to work now -_-

**Comment by LegacyGamerHD** [comment]
after telporting around
