### ISSUE TITLE
Command Completions

### ISSUE THREAD

**Issue by GoldenMyst** [GeyserMC/Geyser#1512]
**What feature do you want?**
I want a feature that has the ability to remove all other commands but only whitelist certain commands (with custom descriptions or such) to prevent the player from lagging & crashing due to too many commands. And it would be easier for the player to know what commands to execute by just opening chat.

**Alternatives?**
I tried using multiple plugins that edits what players see on tab completion, but all of them didn’t seem to work.

**Comment by DoctorMacc** [comment]
This suggestion is already present in #733. Thank you for asking anyway!
