### ISSUE TITLE
Bedrock players cannot passthrough 1-block height when crawling and feature request 

### ISSUE THREAD

**Issue by Jacky10X** [GeyserMC/Geyser#1513]
**Describe the bug**
When bedrock player crawling. It cannot passthrough 1 block height.

**To Reproduce**
Using Water to trigger crawling (piston, trapdoor won't work in bedrock version)
Create something that only have one-block height exit/entry
Try to go through but it cannot passthrough

**Expected behavior**
It should be passthrough

**Screenshots / Videos**
None

**Server Version**
Paper version git-Paper-262 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
Geyser version 1.1.0 (git-master-2d95302) (Java: 1.16.4, Bedrock: 1.16.0 - 1.16.20)
Floodgate build 25? (the latest one)

**Minecraft: Bedrock Edition Version**

1.16.40

**Additional Context**
dump: https://dump.geysermc.org/7pbJspgu6tcosRoKy34eVpOVSonOXSFN

[Feature request]
Bedrock edition:
When sneaking/crouching, the player's height becomes 1.65 blocks, that mean player can passthrough 1.65 or above height-block.
Java edition:
When sneaking/crouching, the  player's height becomes 1.5 blocks, that mean player can passthrough 1.5 height-block.
So is there anyway that we can set it to 1.5 block when bedrock player sneaking/crouching.
Also, can we make a bedrock player also can be triggered the crawling by using piston, trapdoor.

**Comment by DoctorMacc** [comment]
This feature request is already present at #1455. Regardless, thank you for reporting!
