### ISSUE TITLE
Sitting on an armorstand is still bugged on bedrock

### ISSUE THREAD

**Issue by SpySter** [GeyserMC/Geyser#1515]
**Describe the bug**
When sitting on stairs using the ultimate stairs plugin, the player is offset by about to blocks into the air, it shows as normal on java but looking in bedrock the player is offset by 2 blocks

**To Reproduce**

Right click on stairs and it causes the the player to sit in mid air rather than the correct spot

**Expected behavior**
the player should be sat in the correct location

**Screenshots / Videos**
Java:
![image](https://user-images.githubusercontent.com/37638986/98463389-e8352d00-2188-11eb-89d7-eb4d7b5fd7bb.png)
Bedrock:
![image](https://user-images.githubusercontent.com/37638986/98463392-f2572b80-2188-11eb-80ad-31ce8e04aa69.png)

**Server Version**
Paper-Git-261, Minecraft 1.16.4

**Geyser Version**
2d95302 - Geyser 1.1.0
Floodgate - build 25

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**

https://dump.geysermc.org/4R9wneUBmkgYVgaJZh89cE2wKi7HOyVy

**Comment by E404NNF** [comment]
Uhh interesting image in the background...
Anyways, what plugin are you using for "sitting on stairs"?

**Comment by EasyClifton** [comment]
Ultimate Stairs, they said it in the issue

**Comment by E404NNF** [comment]
> Ultimate Stairs, they said it in the issue
> 
> 

Oh, took me a while to see it

**Comment by SpySter** [comment]
> Uhh interesting image in the background...
> Anyways, what plugin are you using for "sitting on stairs"?

We don't talk about the image in the background, you are disrespecting my religion 😠 
Also I am using UltimateChairs

**Comment by Konicai** [comment]
Does this still occur?

**Comment by TerdyTheTerd** [comment]
I can confirm this still occurs using both GSit and UltimateChairs plugins (they both use armorstands as the player vehicle).

Using the latest Geyser at the time (Snapshot 2.0.0 Build# 963).
