### ISSUE TITLE
When joining a fancy gui pops up saying "Loading... Please wait"

### ISSUE THREAD

**Issue by snaildos** [GeyserMC/Geyser#1517]
**What feature do you want?**
I think a fancy gui should pop up, NOT SPAMMING THE PLAYER "LOGGING IN". I think it should pop up, with a nice fancy gui, saying, "Loading..."
That's just my opinion. Can't be that hard.... r..right?

**Comment by yehudahrrs** [comment]
No, it is there on purpose afaik. I guess it wouldn't be that hard to make it only go every 3 seconds or something. Idk if that's what the devs want tho

**Comment by Chew** [comment]
Not sure what exactly you're wanting to meaning. Where does this spam come in?

**Comment by yehudahrrs** [comment]
When you are waiting to be logged in (I think with floodgate) and you move it sends u a please wait until you're logged in

**Comment by snaildos** [comment]
Yep. It spams it. I think it would be VERY nice to have a gui saying. "Loading..." Instead of spam.

**Comment by yehudahrrs** [comment]
Well geyser is open source so you can add it and PR it.

**Comment by snaildos** [comment]
I don't know Java. That is why I am requesting this feature.

**Comment by lukeeey** [comment]
What do you mean?

**Comment by snaildos** [comment]
I mean when you join: It spams LOGGING IN. I just requested a feature that will give you a nice GUI saying Loading.. Please wait.

**Comment by HyperSkys** [comment]
Did you just restart the server, because sometimes that happens
and maybe if this is happening check your logs to find errors maybe it's your port connection?

**Comment by DoctorMacc** [comment]
@HyperSkys this is a feature request for a different implementation of that!

**Comment by snaildos** [comment]
I talked to a developer and I was told that it takes takes a while for the UI to appear, and you would load in by then. I still think this should be implemented. If anyone has the time and understands Java UI maybe add it?
I don't know Java myself and I am just Feature requesting and bug reporting.

**Comment by BlueBurgersTDD** [comment]
I'm not that good at java, but I can try to make a PR for this

**Comment by snaildos** [comment]
@BlueBurgersTDD Sounds good, I couldn't find the line that even had "Logging in..."... Did I stuff up something? I just forked geyser and looked everywhere for this line.

**Comment by DoctorMacc** [comment]
@snaildos look in the GeyserMC/languages repository. Most of our strings are translated.

**Comment by snaildos** [comment]
So, Since I'm new to Java but actually want to learn; I would check in the lang repo, Look for that exact line, find the "name of that line like a variable" and then search through everything "for that variable". I would try to make a UI and then I would "test and build with mvn" Right? Am I on the right track?

**Comment by DoctorMacc** [comment]
Yeah, that sounds right.

**Comment by snaildos** [comment]
Whew! Found it "geyser.auth.login.wai" My god, if I knew this before! Awesome. There is no Geyser "UI LIB" right? I would have to make my own ui lib.

**Comment by snaildos** [comment]
From the information I gathered so if someone else is keen to do it, you can use this information.
1. Reuse the translation that is already there. "geyser.auth.login.wait".
2. That form image https://user-images.githubusercontent.com/46210117/99017943-f376c700-2593-11eb-8aeb-b9967f4940e1.png , You can reuse that form code, just remove the buttons, only have a title and a description, making sure you are using geyser.auth.login.wat . 
I am not even going to try anymore unless a miracle happens, This is why I hate Java.

**Comment by DoctorMacc** [comment]
If someone wants to implement this (I'm personally not invested in this) - you don't need to send a form in my opinion, just a title packet so it shows up big.

**Comment by lukeeey** [comment]
Why not just use an action bar?

**Comment by DoctorMacc** [comment]
That would also work.

**Comment by lukeeey** [comment]
Would be much cleaner than a form

**Comment by snaildos** [comment]
Oh! I like that idea! Yes, a action bar and title would be great.

**Comment by yehudahrrs** [comment]
Yeah I like it

**Comment by snaildos** [comment]
So... who is planning to do it now? xD

**Comment by BlueBurgersTDD** [comment]
> So... who is planning to do it now? xD

I can do it in about 5 hours

**Comment by BlueBurgersTDD** [comment]
Also would it not be better to just show this screen? ![loadscreen](https://user-images.githubusercontent.com/58081413/99060507-6dad4880-25a0-11eb-99d2-0f21c94dd95a.png)

**Comment by lukeeey** [comment]
No @BlueBurgersTDD

**Comment by snaildos** [comment]
No. Defiantly not.

**Comment by BlueBurgersTDD** [comment]
Ok I'll just try to make it send a title, but as I said, I'm no that good at java

**Comment by lukeeey** [comment]
Don't do it then

**Comment by snaildos** [comment]
Make it a action bar and title.

**Comment by lukeeey** [comment]
You only need one not both

**Comment by Carbuino** [comment]
I've managed to change the message to be on the Action Bar and it looks way better than titles or chat spam.
![actionbar](https://user-images.githubusercontent.com/19510288/99776401-ff034a00-2acd-11eb-8d95-2227a1c31d59.png)

**Comment by snaildos** [comment]
That sounds awesome! Really appreciate it. Thank you again!
Just keeping this open until a dev want's it closed. :)

**Comment by snaildos** [comment]
Damn, I didn't check my emails since 2020! Thanks for that! Perfect.
