### ISSUE TITLE
trident while frowing is invisable

### ISSUE THREAD

**Issue by LegacyGamerHD** [GeyserMC/Geyser#152]
**Describe the bug**

**To Reproduce**
1. frow a trident 
2. see on place it lands
3. locate it XD

**Expected behavior**

**Screenshots**

**Server version**
![image](https://user-images.githubusercontent.com/25864932/73613453-af897700-45aa-11ea-9ae8-b7d13c370eaa.png)

**Geyser version**
latest

**Bedrock version**
latest

**Additional context**

**Comment by EOT3000** [comment]
do you not see the trident while it's flying through the air or when it lands?

**Comment by LegacyGamerHD** [comment]
@EOT3000 both

**Comment by EOT3000** [comment]
I assume it says Entity is NULL: TRIDENT in colsole?

**Comment by LegacyGamerHD** [comment]
Yes @EOT3000

**Comment by RednedEpic** [comment]
>> I assume it says Entity is NULL: TRIDENT in colsole?

> Yes @EOT3000

Unable to get this in console. Could you please send a screenshot of where it says this is null?
