### ISSUE TITLE
Bedrock players on top of carpet float ~.5 blocks above the carpet on java.

### ISSUE THREAD

**Issue by kelvitos** [GeyserMC/Geyser#1521]
**Describe the bug**
When a bedrock player steps onto a carpet it visibly raises them ~.5 blocks into the air on java clients. Bedrock players actually can't go into two block high spaces if there is carpet on the floor because they get raised.

**To Reproduce**
1. Log on server with bedrock
2. Step on a carpet.
3. Have another player from java look at the bedrock player on the carpet.
4. Walk on carpet whilst in a two block high space.

**Expected behavior**
The bedrock player isn't raised and can walk on carpet in a two block high space.

**Screenshots / Videos**
![2020-11-09_09 04 17](https://user-images.githubusercontent.com/69998586/98575440-13457c80-226e-11eb-87a0-28e06cdeabf1.png)

**Server Version**
This server is running Tuinity version git-Tuinity-"52f4d08" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.1.0 (git-master-2d95302) (Java: 1.16.4, Bedrock: 1.16.0 - 1.16.20)

Using Geyser-Spigot plugin with floodgate add-on.

**Minecraft: Bedrock Edition Version**
1.16.50 (MCPE)

**Additional Context**
https://dump.geysermc.org/gRAArDMA5Gg2DlHdnU4ngtWNWADQF3MG

**Comment by DoctorMacc** [comment]
This is known and is covered in #204. Thank you for reporting anyway!
