### ISSUE TITLE
When I try to join my server I get the issue CLOSED_BY_REMOTE_PEER in my console

### ISSUE THREAD

**Issue by Hpcrafter** [GeyserMC/Geyser#1523]
When I try to join on my phone to a server on my computer using my IPv4 address it comes up with this issue in my console "[17:18:28 INFO]: [Geyser-Spigot] Bedrock user with ip: /192.168.1.248 has disconnected for reason CLOSED_BY_REMOTE_PEER"

**To Reproduce**
Added the plugin to my server. 
Added floodgate to my server also.
Changed the "auth-type" to "floodgate" as it said to do in the how to set up floodgate tutorial

**Expected behavior**
Join the server from my phone

**Server Version**
Paper version git-Paper-259 (MC: 1.16.4)

**Geyser Version**
Geyser version 1.1.0 (git-master-ea52107) (Java 1.16.4, Bedrock: 1.16.0 - 1.16.20)
Yes I am using floodgate I downloaded the latest version that was available on 10/11/2020 (DD/MM/YYYY) sorry I'm not sure how to find the floodagte version

**Minecraft: Bedrock Edition Version**
The latest one as of 10/11/2020 (DD/MM/YYYY) again really sorry not sure exactly what version that is

**Additional Context**
https://dump.geysermc.org/TdLGfdyiCBYPYfc4c1uDvU1Yu6Q5onrI

**Comment by DoctorMacc** [comment]
This is most likely a configuration issue. Please join our Discord; thank you!

**Comment by Hpcrafter** [comment]
> This is most likely a configuration issue. Please join our Discord; thank you!

I joined the discord and I was told to look on the help page. I could not find anything pertaining to my issue to I thought I would ask here
