### ISSUE TITLE
Scoreboard Inconsistencies

### ISSUE THREAD

**Issue by iSilviu-debug** [GeyserMC/Geyser#1524]
**Describe the bug**
1) Bug scoreboard (again)
2) When I fall into the void I can walk until minecraft kicks me off the server

**To Reproduce**
1) No mistakes just the bugged scoreboard
2) No mistakes

**Expected behavior**
1) When the scoreboard updates.
2) When I fall into the void

**Screenshots / Videos**
1) ![image](https://user-images.githubusercontent.com/67197594/98721418-12f1d200-2391-11eb-9cf3-0d3dcdb7b154.png)
2) ![ezgif com-gif-maker](https://user-images.githubusercontent.com/67197594/98723084-2c474e00-2392-11eb-9a2e-63ec6edb0dc9.gif)

**Server Version**
This server is running Yatopia version git-Yatopia-"0dd46b6" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**
 This server is running Geyser version 1.1.0 (git-master-4237503) (Java: 1.16.4, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**
Bedrock: 1.16.0 - 1.16.20

**Additional Context**
https://dump.geysermc.org/UJVN3GUYYuFCmveSbyo1ar7reFrRGyW8
🌵

**Comment by DoctorMacc** [comment]
The void thing is known and will be fixed. In the future, please do not make one issue with two subjects.

**Comment by DoctorMacc** [comment]
Additionally - can we get a comparison between Java and Bedrock on the scoreboard?

**Comment by iSilviu-debug** [comment]
Certo!

**Comment by iSilviu-debug** [comment]
sure*

**Comment by iSilviu-debug** [comment]
@DoctorMacc 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/67197594/98723969-5b11f400-2393-11eb-90ee-39efbd8968b9.gif)

**Comment by iSilviu-debug** [comment]
@DoctorMacc How are you doing with this issue?

**Comment by CamGamingYT** [comment]
I have this same issue, it does the same thing then crashes the Bedrock client. 

And gives this error in console:

`01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-0. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-1. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-2. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-3. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-4. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-5. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-6. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-7. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-8. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-9. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-10. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-11. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-12. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-13. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-14. It overrides without removing old team.
01.12 22:33:18 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-15. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-0. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-1. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-2. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-3. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-4. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-5. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-6. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-7. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-8. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-9. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-10. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-11. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-12. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-13. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-14. It overrides without removing old team.
01.12 22:33:34 [Server] INFO [Geyser-Spigot] Ignoring team tm-sb-15. It overrides without removing old team.`

**Comment by PQguanfang** [comment]
Does someone are trying fix this problem???
