### ISSUE TITLE
How i can join pirate(offline) server

### ISSUE THREAD

**Issue by ROBGUI09** [GeyserMC/Geyser#1525]
I want to connect to not license server wihout license how can i do it. offline mode dont work in config.yml. i write my nickname, random password and geyser kicking me with message wrong profile data. Help me please

**Comment by rtm516** [comment]
From our Discord:

Cracked servers are not supported here and by setting your server as so, you will not receive support here any further.
"Cracked" or "offline mode" servers basically disable any sort of Mojang authentication and allow people with non-genuine versions of the game to join. **This is software piracy and is illegal!** By setting your server as so, you are condoning the use of piracy. 

If you are simply just wanting Bedrock players to be able to join your Java server without a Java account, we recommend using our plugin Floodgate: (https://github.com/GeyserMC/Geyser/wiki/Floodgate) which allows them to join the server with it being in online mode. If you did not mean to set your server to offline mode or don't understand what it means, please read the above and set your server to online mode.

If you are intending to allow non-genuine Minecraft accounts on your server and are aware that you're supporting software piracy, you are on your own in terms of Geyser support. Please seek support elsewhere.

**Comment by lukeeey** [comment]
Offline mode is officially supported on the vanilla java edition server straight from Mojang.
