### ISSUE TITLE
Joining older Java Versions

### ISSUE THREAD

**Issue by Altamash347** [GeyserMC/Geyser#1526]
**Add Old Minecraft Java Version Support**
You should add support for Minecraft Java Editon 1.8 - latest on the latest Bedrock Version.
Example: I have Minecraft Bedrock Edition 1.16.40 and I want to play on a 1.12.2 Minecraft Java server.
Sorry for bad english

**Never Tried**
Never tried any alternatives for it, as you know Geyser is the only software for it.

**Comment by Tim203** [comment]
You can use ViaVersion for this specific problem, but other then that, we don't plan on supporting older Java Edition versions.

**Comment by DoctorMacc** [comment]
> We currently cannot support multiple protocol versions on the Java end due to limitations within the Java protocol library we use. 

So it's not even that we don't want to, but that we cannot.
