### ISSUE TITLE
CLIENT MODIFICATION

### ISSUE THREAD

**Issue by lilprogramist** [GeyserMC/Geyser#1531]
Banned in server for client modification while playing 5 minutes of bedwars in java server. Why?

**Comment by j5155** [comment]
er what do you mean by client modification
like bedrock edition mods?

**Comment by lilprogramist** [comment]
> er what do you mean by client modification
> like bedrock edition mods?

Banned in server for client modification while playing 5 minutes of bedwars in java server. Why? (sorry for my broken english tho) https://imgur.com/a/7n2h0rE

**Comment by DoctorMacc** [comment]
Geyser standalone gives out a warning that joining other servers can get you banned because of inconsistencies between Bedrock and Java. We will keep working to make the experience with Geyser as smooth as possible, but unfortunately anticheats flagging Geyser will happen.
