### ISSUE TITLE
Book & Quills do not save on Bedrock Edition

### ISSUE THREAD

**Issue by whakama** [GeyserMC/Geyser#1533]
**Describe the bug**
When writing in a book & quill on Bedrock Edition, the contents do not save once closed out, signed or not signed.

**To Reproduce**
1. Get a Book & Quill on Bedrock Edition.
2. Write anything in it.
3. Sign the book or close out of it.
4. Drop the item on the ground and pick it back up.
5. Read book, contents not saved.

**Expected behavior**
Text written should be saved, regardless of book being signed or not.

**Screenshots / Videos**

**Server Version**
"CraftBukkit version git-Spigot-2740d5a-890130b (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)"

**Geyser Version**
"Geyser version 1.1.0 (git-622d4f6b51014ba1b198ae390e8cd44c60a87c84-622d4f6) (Java: 1.16.4, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
Server is hosted on 1.16.3, with ViaVersion allowing for 1.16.4 players.

**Comment by DoctorMacc** [comment]
This is already present as an issue with #1088. Thank you regardless for reporting!
