### ISSUE TITLE
How does connecting a domain to a geyser server work?

### ISSUE THREAD

**Issue by DerpoDrago** [GeyserMC/Geyser#1535]
I have been trying to get my domain to work with my geyser server for a bit and just wanted to know if there are any special requirements that need to be fulfilled before i can do so. Thanks!

**Comment by rtm516** [comment]
Bedrock servers don't support SRV records, so you will have to use an A record or similar. Please come over to our [Discord](https://discord.geysermc.org/) if you need more help.

**Comment by dave9123** [comment]
This should help you https://wiki.geysermc.org/geyser/understanding-the-config/#remote-section

**Comment by MrZomka** [comment]
Did you seriously reply to 1 year old issue that was already closed?

**Comment by S0M0G** [comment]
> Did you seriously reply to 1 year old issue that was already closed?

2 year old*

**Comment by Chew** [comment]
1.5 years old... and why are we all bumping an old issue 🤨

**Comment by dave9123** [comment]
Sort of
________________________________

**Comment by S0M0G** [comment]
Not really bumping in, I just got a mail that you wrote this, idk why tho

**Comment by nununununununununununununununu** [comment]
wait so old now
