### ISSUE TITLE
Authlib for all players from BE

### ISSUE THREAD

**Issue by ProsperFall** [GeyserMC/Geyser#1537]
I'm a server master,
I hope players from all platforms can join our server，but they said they only bought MCBE and floodgate only support spigot.
'cause uuid, JE player don't want use offline mode
Now I want write a program for ALL KINDS OF SERVER.
It is about Authlib,would you provides an API? (just replace "https://authserver.mojang.com" with another URL,only registered(or other)  BE players&mojang players could pass it)  please.
if it could be true,you will not need to write different versions of plug-ins for different servers.

**Comment by D3ATHBRINGER13** [comment]
What server software are you using?

**Comment by DoctorMacc** [comment]
Floodgate also supports Velocity and BungeeCord (which is an alternative in any scenario, since you should be able to put any Minecraft server behind a proxy).

**Comment by RednedEpic** [comment]
We don’t touch this at all when it comes to Floodgate, and an authlib-type system isn’t something we’re intending to support as we have no guarantee the user actually purchased Minecraft (on any platform) to begin with. Unless there is a usecase I’m missing here, this seems like a way around online mode.

If there is a server software you’re using which Floodgate does not support, please feel free to open a feature request over at the Floodgate repo.
