### ISSUE TITLE
Players cannot eat

### ISSUE THREAD

**Issue by linmiao233** [GeyserMC/Geyser#154]
**Describe the bug**
Can't eat / drink any food, as soon as you eat it, it will automatically return to the first slot.

**To Reproduce**
1. Pick up food or potion
2. And then start eating longer
3. Will return a space to see the error

**Expected behavior**
Should be able to eat, not automatically jump back to a slot when you start eating

**Server version**
1.8.8

**Geyser version**
#67 

**Bedrock version**
1.14.2

**Comment by LegacyGamerHD** [comment]
Not a geyser issue I can eat fine in geyser

**Comment by linmiao233** [comment]
> 不是间歇泉的问题，我可以在间歇泉吃得很好
I am using # 67 Is it a Java version problem?

**Comment by linmiao233** [comment]
> Not a geyser issue I can eat fine in geyser

I am using # 67 Is it a Java version problem?

**Comment by AJ-Ferguson** [comment]
This bug seems to be present in the master branch as well. I was able to reproduce using craftbukkit 1.8.8 and ViaVersion 2.2.3. I should have a fix soon unless someone beats me to it.
