### ISSUE TITLE
Ignoring Team tm-sb-1 Error

### ISSUE THREAD

**Issue by Anston06** [GeyserMC/Geyser#1544]
Whenever I have a Bedrock player on it continously output errors like this: "Ignoring team tm-sb-1. It overrides without removing old team." Does anyone know what this is and how to fix it?

Config.yml [https://pastebin.com/5LdF4XNp](https://pastebin.com/5LdF4XNp)

**Comment by DoctorMacc** [comment]
I'm closing this as it doesn't follow the issue template. However, if you let me know what scoreboard plugin is being used on the server, we can be able to fix the spam.

**Comment by Anston06** [comment]
The scoreboard plugin I’m using is TitleManager.
