### ISSUE TITLE
Scoreboard not appearing

### ISSUE THREAD

**Issue by lifegame1lu111** [GeyserMC/Geyser#1545]
**Describe the bug**
The scoreboard does not load

**To Reproduce**
-Log on mc.stardix.com with the most recent geyser build

**Expected behavior**
The scoreboard would load properly like on java

**Screenshots / Videos**
![Captura de Tela (354)](https://user-images.githubusercontent.com/40743123/99200374-ace7bf00-2783-11eb-977d-f71600d62f12.png)
Java Scoreboard ^^

**Server Version**
Not known as server is not mine

**Geyser Version**
#478
Branch master
**Minecraft: Bedrock Edition Version**
1.16.40

**Additional Context**
.

**Comment by DoctorMacc** [comment]
Can you please attach a Geyser dump?

**Comment by lifegame1lu111** [comment]
Ok will be attacthing: https://dump.geysermc.org/FSGwJPv8LZ9qYVzxKkGiWbEE1c0yut2s

**Comment by lifegame1lu111** [comment]
closing issue as it got fixed in build #496
