### ISSUE TITLE
Tamed Wolfs Turn Color of Collar

### ISSUE THREAD

**Issue by TheMasterBlaster** [GeyserMC/Geyser#1547]
**Describe the bug**

Tamed Wolfs will show to the client as Red.

**To Reproduce**

1. Spawn a Wolf
2. Tame the Wolf
3. See Wolf has turned Red

**Expected behavior**

For the Wolf to not be Red?

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/9083212/99209989-92691200-2792-11eb-911d-9a315c955be9.png)

**Server Version**

Paper version git-Paper-261 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**

Geyser Bungeecord version 1.1.0 (git-master-47f25f1) (Java: 1.16.4, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**

1.16.40

**Additional Context**

I did not notice this issue until I updated a few hours ago. I was only 1 version behind at the time.

**Comment by DoctorMacc** [comment]
This commit: https://github.com/GeyserMC/Geyser/commit/e748240a02c9eb7062fb114f3dcd285f4efb47fe is probably the suspect.

Could you please provide a Geyser dump?

**Comment by TheMasterBlaster** [comment]
https://dump.geysermc.org/Rn89xnLW976A6iHUiSJArCmwPci9Apa1

**Comment by DoctorMacc** [comment]
What is the backend server type and version? Can you share the plugins?

**Comment by TheMasterBlaster** [comment]
By back end you mean the actual server right? if so..
Version and Type: Paper version git-Paper-261 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Plugins: ActionHealth*, AntiXrayHeuristics, AuctionHouse, BetterRTP, BlockLocker, BottledExp, ChestSort, Citizens, CitizensCMD, CMI, CMIPaperLib, CoreProtect, CraftingStore, CrateReloaded, Crawling, DiscordSRV, (WorldEdit)FastAsyncWorldEdit, HeadDatabase*, HolographicDisplays, IllegalStack, Images, Jobs, KBUtils, LagAssist, LibsDisguises, LiteBans, LuckPerms, mcMMO, MMOItems, MMOLib, Multiverse-Core, MythicMobs, PhantomSpawnControl, PlaceholderAPI, PlayerParticles, PlayerWarps, ProtocolLib, PvPToggle, QuickShop, SafariNet, ShopGUIPlus, ShowItem, SuperLuckyBlock, TAB, TheNewEconomy, TimeVote, Towny, TownyNameUpdater, TriggerReactor, Vault, VentureChat, VoidGenerator, Votifier, WeatherVote, WorldGuard, xPCommandBlocker*

**Comment by lukeeey** [comment]
Cannot reproduce on latest master
![image](https://user-images.githubusercontent.com/32024335/99253302-6d16eb00-2808-11eb-9c70-2fa18f49df73.png)

**Comment by TheMasterBlaster** [comment]
Wonder why I'm having this issue on the Latest Master then? It happens on Multiple devices as well :/

**Comment by rtm516** [comment]
Could you send over the region file or at least that part of the world? So we can see if its a plugin causing it or just some strange NBT on the wolf.

**Comment by TheMasterBlaster** [comment]
Just now checked the region file on a test server without plugins and I did not have the glitched Wolf issue, Has to be a plugin doing something Geyser/Bedrock doesnt like.

**Comment by TheMasterBlaster** [comment]
So I have noticed whatever color the Wolfs collar is determines what color the Wolf itself is. 
![image](https://user-images.githubusercontent.com/9083212/99418593-31902580-28c9-11eb-8574-ca5460ffc8c0.png)
![image](https://user-images.githubusercontent.com/9083212/99418632-3bb22400-28c9-11eb-8b78-20d21a355102.png)
![image](https://user-images.githubusercontent.com/9083212/99418714-4d93c700-28c9-11eb-8938-6a0d618077a2.png)

**Comment by TheMasterBlaster** [comment]
Since Its not my Server, I setup a quick test server with all the same plugins without having the Wolf color issue

**Comment by CreaZyp154** [comment]
Yeah I saw this on a video I don't remember exactly but If i'm correct this is a vanilla Minecraft issue. I'll edit this comment if I find it

**Comment by lukeeey** [comment]
@TheMasterBlaster can you please use the same world on a server without any plugins

**Comment by TheMasterBlaster** [comment]
The world itself is like 40 / 50GB

**Comment by CCF100** [comment]
This bug is amazing

**Comment by Chew** [comment]
Please refrain from bumping issues for off topic reasons

**Comment by lukeeey** [comment]
@TheMasterBlaster just disable your plugins... rename them to have a different extension or copy them into another directory for now, or just swap out the spigot jar with the vanilla minecraft server

**Comment by TheMasterBlaster** [comment]
@lukeeey as I said before it's not my server to just remove plugins for testing like that.

**Comment by lukeeey** [comment]
I’m not sure what you want us to do then

**Comment by DoctorMacc** [comment]
Can you provide a server IP for us?

**Comment by TheMasterBlaster** [comment]
mc.gingycraft.net @DoctorMacc

**Comment by TheMasterBlaster** [comment]
@lukeeey I don't understand why you are acting annoyed. I have done what I can to help. Since I'm experiencing this issue I wanted to report it.. if its such a hassle I'll just close this

**Comment by DoctorMacc** [comment]
Issues have no need to be closed unless they cannot be replicated, have been fixed, or are a "can't fix". 

Thanks for provided a server IP. I'll try it out now and see if I can replicate the issue on there.

**Comment by DoctorMacc** [comment]
I'm able to confirm this issue.

**Comment by orionakaiba** [comment]
> Você pode nos fornecer um IP de servidor?

Hello hello  my name is David i me Brazil e eu preciso muito falar com você sobre um projeto de Minecraft que estou a 7 anos e só você pode me ajudar
