### ISSUE TITLE
When a bedrock player joins they are unable to see the skin of java players

### ISSUE THREAD

**Issue by Eilux** [GeyserMC/Geyser#1550]
**Describe the bug**

When a bedrock player joins java players will appear as Steve but if the java player disconnects and rejoins then the skin renders correctly.

**To Reproduce**
1. log in with a java account
2. log in with a bedrock account (the java player will look like a Steve)
3. relog with the java account (the java player will look correct)

**Expected behavior**
Java skin should always render

**Screenshots / Videos**

**Server Version**
Paper version git-Paper-277 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
 Geyser version 1.1.0 (git-master-981ac3b) 

**Minecraft: Bedrock Edition Version**
1.16.50

**Additional Context**
I am also using floodgate

**Comment by DoctorMacc** [comment]
Please attach a Geyser dump.

**Comment by Eilux** [comment]
oops here it is: https://dump.geysermc.org/U14QnDwz3V8qiiRfottVHDrFq8XtBUSE

**Comment by Camotoy** [comment]
As this is a stale issue, I am closing. Do let us know if you believe this is in error!
