### ISSUE TITLE
death messages are like "%1$ killed %2$"

### ISSUE THREAD

**Issue by Noah7563** [GeyserMC/Geyser#1554]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by Noah7563** [comment]
[https://cdn.discordapp.com/attachments/770478131328319488/778257178179403776/Screenshot_2020-11-17-21-52-49-64.png](url)

**Comment by rtm516** [comment]
Please fill in the bug report template, it exists so we don't have to ask a tonne of questions.
