### ISSUE TITLE
Player#openBook(itemstack) doesn't actually open a book

### ISSUE THREAD

**Issue by skerit** [GeyserMC/Geyser#1562]
**Describe the bug**

I made a Spigot plugin that uses books as a way to make dialogs with NPCs. However, Bedrock players never get to see the book. Nothing happens on their side.

Now the book does contain clickable links, which I know are not supported in Bedrock, so 2 questions:

1: Is that the reason why they're not showing up on Bedrock, or should it just ignore the links?

2: Is there any alternative method you can think of? I thought about detecting bedrock players in the plugin and then just using another method for them, but I'm not sure what. 

**Minecraft: Bedrock Edition Version**
1.16.100

**Comment by rtm516** [comment]
Can you provide a dump and server logs if there are any errors?

**Comment by DoctorMacc** [comment]
The mechanic itself is addressed in https://github.com/GeyserMC/Geyser/issues/1351.

You will have to implement some sort of workaround - Bedrock has no packet to simply open a book. You can use the Floodgate API for now to determine if a player is from Bedrock - in the future we will have more options with forms to send to the Bedrock player as an alternative.
While clickable links are indeed unsupported on Bedrock, these should not be issues for interpreting books in general.

As hopefully your questions are answered, I'm going to close this issue, but feel free to ask more questions if needed!

**Comment by skerit** [comment]
Thank you for the explanation! I'll figure something out :)
