### ISSUE TITLE
JsonSyntaxException

### ISSUE THREAD

**Issue by SeqSEE** [GeyserMC/Geyser#1563]
**Describe the bug**

**To Reproduce**

1. Get an achievment or die
2. Look at the console output of the bungeecord server

**Expected behavior**

No errors in console, probably no warnings too. 

**Screenshots / Videos**

**Server Version**

Waterfall version git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:38

**Geyser Version**

Geyser Bungeecord version 1.2.0-SNAPSHOT (git-master-199778f)

**Minecraft: Bedrock Edition Version**

1.16.100

**Additional Context**

https://hasteb.in/ukavadon

**Comment by SeqSEE** [comment]
**Bungeecord Plugins**
BBQueue
BungeeJail
BungeeTabListPlus
BungeePerms
DiscordBridge
Floodgate Bungee
Geyser-Bungeecord
IndustrialChatBridge
ViaVersion

**Dump**
https://dump.geysermc.org/b1rxNq0RrGrJ3MyGnypeE4k1NV3sf72c

 **Proxied Java Server**
 Paper version git-Paper-214 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)


**Paper Server Plugins**
AsyncWorldEdit
Beds
BungeeTabListPlus
CombatLogX
Essentials
EssentialsSpawn
Guns
Hit
HolographicDisplays
IndustrialEvolution
IPortal
mcMMO
MineableSpawners
ObsidianDestroyer
PermissionsEx*
PlaceholderAPI
ProtocolLib
StuckMobRemover
VanishNoPacket*
Vault
ViaVersion
Vivecraft-Spigot-Extensions*
WorldEdit
WorldGuard
WorldGuardExtraFlags

**Comment by rtm516** [comment]
>it was a normal server message
for advancement
and also for player death

Likely the cause

**Comment by rtm516** [comment]
After looking this over with Kyori, its caused by bad HoverEvent handling in MCProtocolLib.
