### ISSUE TITLE
Item Movement is Very Glitchy

### ISSUE THREAD

**Issue by Etrainquandt17** [GeyserMC/Geyser#1564]
**Describe the bug**
When dropping an item on the floor, exploded from a chest, or dropped from a dispenser or hopper movement seems to be very unusual

**To Reproduce**
1. Do any of the things I mentioned above

**Expected behavior**
Item movement should match that of java edition

**Screenshots / Videos**
![ezgif-3-a0a36dc651e0](https://user-images.githubusercontent.com/25209546/99600486-8320d900-29cb-11eb-8f53-6e4dba7c1569.gif)

**Server Version**
CraftBukkit version git-Spigot-a19903d-009f0ba CMC: 1,16.4)

**Geyser Version**
Geyser version 1.2.0-SNAPSHOT (git-master-199778f Java: 1.16.4, Bedrock: 1.16.100.60)

**Minecraft: Bedrock Edition Version**
1.16.100 Windows 10

**Additional Context**
Just floodgate
https://dump.geysermc.org/RsNxPU7jfp2jjqrSkhjcDD7OHutnVGee

**Comment by DoctorMacc** [comment]
Can confirm that item behavior seems glitchier than usual. This happened after 1.16.00.

**Comment by DoctorMacc** [comment]
1.16.200 has largely made this better, in my experience. Therefore, I am closing this for the time being.
