### ISSUE TITLE
Mob Movement is Jagged/Very Unsmooth

### ISSUE THREAD

**Issue by Etrainquandt17** [GeyserMC/Geyser#1565]
**Describe the bug**
Mob movement doesn't look right at all

**To Reproduce**
1. Observe the movement of a mob (works best with spiders or when attacking a mob with knockback or watching a mob fall off a cliff)

**Expected behavior**
Movement should be smooth

**Screenshots / Videos**
https://streamable.com/dq7o5l

**Server Version**
CraftBukkit version git-Spigot-a19903d-009f0ba (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
Geyser version 1.2.0-SNAPSHOT (git-master-4297215) (Java: 1.16.4, Bedrock: 1.16.100.60)

**Minecraft: Bedrock Edition Version**
1.16.100 Windows 10

**Additional Context**
Only floodgate and may be related to #1564
https://dump.geysermc.org/Q1nhddkcgeGlBanTv261phiKJ3zAN08c

**Comment by haloflooder** [comment]
I don't know man. That looks much better than what I'm seeing on my server

https://www.youtube.com/watch?v=W4BA7Yhu7rU

**Comment by Chew** [comment]
Reminds me of the ancient Minecraft days.. we're repeating history

**Comment by Etrainquandt17** [comment]
> I don't know man. That looks much better than what I'm seeing on my server
> 
> https://www.youtube.com/watch?v=W4BA7Yhu7rU

Oh god... I pretty sure that this is the same issue but multiplied due to the amount of players (unless you have enough ram for that amount)

**Comment by DoctorMacc** [comment]
This appears to be resolved in 1.16.200.
