### ISSUE TITLE
Skeleton Horses can not be mounted.

### ISSUE THREAD

**Issue by VoyagerXyX** [GeyserMC/Geyser#1566]
**Describe the bug**
When you attempt to mount a skeleton horse you can not ride them, they just stand in place and jumping may cause glitching and movement issues after an attempt to mount. 

**To Reproduce**

Attempt to mount a skeleton horse

**Expected behavior**

Skeleton horse should be mounted

**Server Version**

Spigot - Latest Version

**Geyser Version**

488
Minecraft: Bedrock Edition Version (PC)
1.16.100

**Comment by DoctorMacc** [comment]
Can you provide a Geyser dump?

**Comment by RednedEpic** [comment]
Unable to reproduce - was able to mount onto a skeleton horse successfully without issue.
