### ISSUE TITLE
Mounting horses on path blocks causes horse to sink

### ISSUE THREAD

**Issue by yehudahrrs** [GeyserMC/Geyser#1568]
Description: I try to mount a horse with a saddle and the horse is on a path block, but a second after I mount the horse the horse and I sink into the path block. but we can get out by making the horse jump.

To reproduce: Tame a horse, put a saddle on it, and put it on a square of a bunch of path blocks, then mount it and wait.

Context: This is on the Geyser test server on move_test world. I can send video or screenshot if you want.

**Comment by RednedEpic** [comment]
Unable to reproduce.
