### ISSUE TITLE
Issues With Custom Crafting Recipes

### ISSUE THREAD

**Issue by NathanWolf** [GeyserMC/Geyser#1571]
**Describe the bug**
I have a plugin that allows for custom crafting. Most recipes are two-stage, there is an an initial item you craft, then you use that item in other recipes.

The first recipe seems to work fine, it outputs an item with some custom NBT data (and name, lore). 

The second recipes cause some strange behavior on Bedrock clients, the input item ("Magic Heart") glitches out, item count turns yellow and it's stuck to the cursor. The item will often drop to the ground.

It seems like things work better if you just give yourself the recipe ingredient, though.

**To Reproduce**
1. Download my plugin: https://jenkins.elmakers.com/job/Magic-Stable/9/artifact/Magic/target/Magic-8.0.2.jar
2. Join the server, give yourself a workbench, stick, 4 emeralds and a diamond
3. Arrange emeralds and diamond like this: https://imgur.com/SVXPPkM
4. This should give you a custom item that looks like a Heart of the Sea
5. Now try to craft with the heart of the sea, using the stick like this: https://imgur.com/oIxTSu4
6. You should see the heart of the sea item kind of glitches out, and the recipe will not work

7. If you want to try crafting the 2nd stage only, use `/mgive magicheart`

**Expected behavior**
That crafting would work as normal, even with custom recipes

**Screenshots / Videos**
Here is a video of me trying it: https://gfycat.com/graciouslikelyhoneybadger

**Server Version**
CraftBukkit version git-Spigot-a19903d-167ff59 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
Geyser version 1.2.0-SNAPSHOT (git-master-4297215) (Java: 1.16.4, Bedrock: 1.16.100.60)

**Minecraft: Bedrock Edition Version**
v1.16.100

**Additional Context**
https://dump.geysermc.org/dUSWM4rHkhtCKbWxWMtBw3D7fjL8B7ID

Thank you!

**Comment by NathanWolf** [comment]
Update with a little more info: After step 4 above, you just get a locally-glitched item from the recipe. Interacting with it at all seems glitchy, not just when trying to craft with it.

Relogging seems to fix the item, and it can then be used as a crafting ingredient.

**Comment by NathanWolf** [comment]
I've further narrowed this down to something about how my plugin modifies the crafting result in the CraftItemEvent.

I'll try to narrow this down all the way, and if I can I will provide a simple test plugin for reproducing the problem.

**Comment by NathanWolf** [comment]
I've nailed it down to this:

```
    @EventHandler
    public void onCraftItem(CraftItemEvent event) {
        ItemStack item = event.getCurrentItem();

        // This is the culprit here.
        item.setDurability(item.getDurability());
    }
```

I still use `setDurability` in my plugin for some legacy Spigot version support (sadly), otherwise I think other, non-deprecated methods (setting metadata, even changing item type) seem to be fine. I probably call setDurability here in other places, too, and I haven't seen issues so this seems like a very specific problem.

An example plugin with jar can be found here:
https://github.com/NathanWolf/Bukkit-Unit-Tests/releases/tag/crafting-1.1

I've worked around this myself for now, so please don't worry about fixing it on my account, but I was curious to track it down completely.

Thank you!

**Comment by DoctorMacc** [comment]
Interesting. Thank you so much for all the detail!

**Comment by jackson-57** [comment]
According to @DabbingEevee, his initial issue was fixed.

**Comment by RednedEpic** [comment]
Not seen any reports of this in a long time (especially since we rewrote our inventory system), so chances are its fixed, plus considering others have reported it being fixed as well. Thanks for the reporting this bug!
