### ISSUE TITLE
Incorrect Items in trade menu

### ISSUE THREAD

**Issue by kelvitos** [GeyserMC/Geyser#1573]
**Issue**
When opening a villager trade the items related to trade are completely wrong. For example you can see in the screenshot that emeralds are being replaced with a music disc

**To Reproduce**
1. Trade with a villager

**Expected behavior**
Normal trades that match java

**Screenshots / Videos**
![IMG_0885](https://user-images.githubusercontent.com/69998586/99865728-b47edd80-2b60-11eb-9656-66c654dfbd2c.PNG)

**Server Version**
git-Tuinity-"0850468" 1.16.4

**Geyser Version**
1.2.0-SNAPSHOT (git-master-99558b6) Java 1.16.4 Bedrock 1.16.100.60

**Minecraft: Bedrock Edition Version**
1.16.100

**Additional Context**
https://dump.geysermc.org/O2ztBkCCKiY27AON4YxlVfTih7apF5pu

**Comment by DoctorMacc** [comment]
This has been please; please update. Thank you!
