### ISSUE TITLE
Minecart movement not smooth and look like glitch in Bedrock

### ISSUE THREAD

**Issue by hyperonlineshop** [GeyserMC/Geyser#1578]
**Describe the bug**
When using a minecart on a bend rail / zig zag rail is quite abnormal

**To Reproduce**

Try using minecart at zig zag rail

**Expected behavior**

Want minecart movement like normal when at zig zag rail

Screenshots / Videos
Video Link : https://drive.google.com/file/d/1ih1jl-klPk4f3lnSz0JlKcyNDsigJLLR/view?usp=sharing

**Server Version**

Paper - Latest Version

**Geyser Version**

Latest Version with Fix mounts

**Minecraft: Bedrock Edition Version**
1.16.100 Windows 10

**Additional Context**
Just floodgate

**Comment by DoctorMacc** [comment]
Unable to view the video, but I tested, and I was fine with how minecarts work (with cache chunks + my PR to fix getting in mounts in the first place).

**Comment by hyperonlineshop** [comment]
@DoctorMacc try see this screenshot

https://imgur.com/a/BUuaO7D

**Comment by DoctorMacc** [comment]
If I had to guess, this is just Bedrock being Bedrock and nothing we can do about it.

**Comment by hyperonlineshop** [comment]
You mean this issue because bedrock ? not come from Geyser ?

**Comment by AwesomestCode** [comment]
Yes, that's what he means. Try replicating this on a singleplayer world and see if it still occurs.

**Comment by Chew** [comment]
OP's Video: https://cdn.discordapp.com/attachments/744287608217272351/780119050726408223/Minecraft_2020-11-22_14-38-49.mp4

My testing in single player 1.16.100 -> https://cdn.discordapp.com/attachments/613194828359925800/780483103663194112/BOyxq7aWGW8-xiJm.mp4

**Comment by Hellohi3654** [comment]
I believe this issue is a problem with Geyser

**Comment by Hellohi3654** [comment]
I also noticed that hyperonlineshop (https://cdn.discordapp.com/attachments/744287608217272351/780119050726408223/Minecraft_2020-11-22_14-38-49.mp4)
Looked a bit laggy when just going straight along the rail

**Comment by hyperonlineshop** [comment]
I hope dev look this issue

**Comment by DoctorMacc** [comment]
This issue will be lower priority, as it's purely visual and still playable.

**Comment by onebeastchris** [comment]
does this still occur in the latest version(s)?

**Comment by onebeastchris** [comment]
Unable to replicate the original issue from the issue, closing due to no response.
