### ISSUE TITLE
Chunks weirding out when using FAWE.

### ISSUE THREAD

**Issue by BetaDv** [GeyserMC/Geyser#1580]
I tried making some walls but some weird chunks i suppose were pretty broken. Here, watch this video: https://we.tl/t-1echlaJ57p

How i did: I got a stick, was holding it, i run /br sphere sand 3, i then tried making the walls. It was on a flat world.
I'm not sure if it can also happen to the testers. I recorded it on Android.

**Comment by Chew** [comment]
Please fill out template :)

```
Describe the bug

To Reproduce

Expected behavior

Screenshots / Videos

Server Version

Geyser Version

Minecraft: Bedrock Edition Version

Additional Context
```

We also need a geyser dump. Once we get all the information, we'll re-open this. Alternatively, open a new issue with this information.
