### ISSUE TITLE
Chunks appearing when using FAWE, client sided.

### ISSUE THREAD

**Issue by BetaDv** [GeyserMC/Geyser#1581]
**Describe the bug**
Random Chunks i suppose, appearing when using FAWE, i want to make a map and yeah, they interfere with my work, it also only removes a part of it if the sand from the sphere interacts with it. Then some other parts remain, either dirt, either bedrock, either grass. Or grass eith dirt. It only shows on client side, it's just slowing me down quite a bit.

**To Reproduce**
1. Install Fast Async World Edit.
2. Get a stick.
3. Run "/br sphere sand 3" with the stick in your hand.
4. Try making a wall i guess.

**Expected behavior**
Not Show the Broken chunks.

**Screenshots / Videos**
https://we.tl/t-1echlaJ57p - Video

**Server Version**
CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) 

**Geyser Version**
493 Branch

**Minecraft: Bedrock Edition Version**
1.16.100

**Additional Context**
I used FAWE (FastAsyncWorldEdit) when the bug happened.

**Comment by DoctorMacc** [comment]
Could you please attach a Geyser dump?

`Run geyser dump (server console) / /geyser dump (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.`

**Comment by BetaDv** [comment]
Okay, wait a bit tho. I gotta start the server back. It closed.

**Comment by BetaDv** [comment]
Had a bunch of issues opening the server. Lmao. An hour later the dump is finally here. https://dump.geysermc.org/Te1jUiQTOKl2w48DeLh5HCITbXZKqJYh

**Comment by BetaDv** [comment]
sed
