### ISSUE TITLE
Geyser Backwards

### ISSUE THREAD

**Issue by NidzGamingTV** [GeyserMC/Geyser#1583]
**What feature do you want?**
Latest Geyser should support lower server version. So that every pr or new geyser released, we can still join in lower server version.   

**Alternatives?**
If it is possible to put viaversion to geyser itself just like skin resorter

**Comment by DoctorMacc** [comment]
Unfortunately, due to the limitations of our Java protocol library, we can't implement this. In the future we may try to implement ViaVersion as an extension to Geyser, but as the plugin API is yet to be merged, this doesn't yet exist.
