### ISSUE TITLE
Recipe for bed produces a shield

### ISSUE THREAD

**Issue by Quickbe4m** [GeyserMC/Geyser#1584]
**Describe the bug**
When crafting on Win 10 and xbox the bed is not listed as a craftable object and when you try to craft it you get a shield. The bed does show up on Java and in the creative menus.

**To Reproduce**
1. Go to any crafting bench on the server
2. try to craft a bed
 3. See error 

**Expected behavior**
the workbench would allow me to craft a bed

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/74891377/99931029-b55a6f80-2d18-11eb-8d14-c744e11ce6d9.png)

**Server Version**
This server is running CraftBukkit version git-Spigot-a19903d-009f0ba (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-99558b6) (Java: 1.16.4, Bedrock: 1.16.100.60)  Plugin

**Minecraft: Bedrock Edition Version**
1.16.100
**Additional Context**
https://dump.geysermc.org/cEW7OzOhCa7nXQIPnllysvqOLjrYRbED

**Comment by DoctorMacc** [comment]
Please update your Geyser; thank you anyway!
