### ISSUE TITLE
Lots of issues with vehicles

### ISSUE THREAD

**Issue by Leonardo-Fiori** [GeyserMC/Geyser#1585]
**Describe the bug**
- Boats fly when driving them off a block
- Can't mount on boats
- Can't mount on carts
- If you manage to mount on boats, they won't move
- Think the same for carts?

**To Reproduce**
Try to use a vehicle after the movement fixes update got merged into master branch!

**Screenshots / Videos**
Fly https://youtu.be/lztjMDLSHv4
Glitch https://youtu.be/im6__82EbhU

**Server Version**
git-Tuinity-"576e2cc" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT) (it's a cool fork of paper)

**Geyser Version**
running Geyser version 1.2.0-SNAPSHOT (git-master-e412ba0) (Java: 1.16.4, Bedrock: 1.16.100.60)

**Minecraft: Bedrock Edition Version**
1.16.100

**Additional Context**
Recently got this exception but I think it's unrelated
https://hastebin.com/xifepotule.apache

Dump
https://dump.geysermc.org/zQoS3TK1m6g4c9bNT86dxRdwKekGG5Sy

**Comment by DoctorMacc** [comment]
Mounting issues will be fixed with #1576. Boats flying is a 1.16.100 thing and not a move fixes thing

**Comment by Leonardo-Fiori** [comment]
> If you manage to mount on boats, they won't move
I guess this will be also fixed with next update?

**Comment by DoctorMacc** [comment]
Boats worked fine for me in the water.

**Comment by Leonardo-Fiori** [comment]
Tomorrow ill try again from IPad, on the ground. Thanks for now!

**Comment by Leonardo-Fiori** [comment]
@DoctorMacc nope! Still having big issues with boats, just updated geyser
![image](https://user-images.githubusercontent.com/25549272/100210610-78a29a00-2f0b-11eb-9017-dc1a4a21a402.png)

**Comment by DoctorMacc** [comment]
@Leonardo-Fiori can you try the PR build specifically?

**Comment by Leonardo-Fiori** [comment]
Ugh, nope, i used a build from jenkins!

**Comment by DoctorMacc** [comment]
Mounting issues are fixed. Can you confirm is moving is still an issue for you?

**Comment by Leonardo-Fiori** [comment]
@DoctorMacc updates on this:

just updated geyser to latest version on jenkins:
- I can now successfully mount on boats
- boats do properly move on water

But:
- boats can't be moved on solid blocks
- seems like that with some punching they can be moved on ice, but if ice stops and there is a solid block, they stop instantly
