### ISSUE TITLE
Can't open backpack again

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Geyser#1588]
**Describe the bug**

Unable to open inventory
**To Reproduce**

Click this button
![IMG20201124200944](https://user-images.githubusercontent.com/53421735/100092453-08efc900-2e91-11eb-8a2b-0b9b6910100d.jpg)

It can be opened for the first time

Close the interface

Click the button again

Cannot open

**Expected behavior**

The backpack should be opened correctly
**Screenshots / Videos**

**Server Version**

Paper1.16.4
**Geyser Version**

1.2.0-SNAPSHOT (git-master-881e7a0) (Java: 1.16.4, Bedrock: 1.16.100.60)
**Minecraft: Bedrock Edition Version**

1.16.100 & 1.16.101
**Additional Context**

**Comment by rtm516** [comment]
Please provide a dump using `/geyser dump` (ingame) or `geyser dump` (server console).

**Comment by zimzaza4** [comment]
> Please provide a dump using `/geyser dump` (ingame) or `geyser dump` (server console).

https://dump.geysermc.org/P95UB1zdByy6zJZ3kXvYAMGSZC8ZQ05H

**Comment by zimzaza4** [comment]
Reinterpretation:If you use the pocket UI, you won't have this problem

**Comment by zimzaza4** [comment]
This problem only occurs in the classic UI

**Comment by rtm516** [comment]
Sounds like a client issue.

**Comment by zimzaza4** [comment]
There is no such problem in single player games

**Comment by rtm516** [comment]
Just tested on the official test server and had no issues. Can you try it on there aswell? `test.geysermc.org`

**Comment by zimzaza4** [comment]
> Just tested on the official test server and had no issues. Can you try it on there aswell? `test.geysermc.org`

Strangely, there is no such problem

**Comment by zimzaza4** [comment]
This is a client problem

**Comment by zimzaza4** [comment]
It seems that there are some special items in the backpack that can cause

**Comment by zimzaza4** [comment]
Most of the items in my backpack carry lore

**Comment by zimzaza4** [comment]
After I emptied my backpack

**Comment by zimzaza4** [comment]
After re entering the server, the backpack can be opened repeatedly
