### ISSUE TITLE
Java combat effects

### ISSUE THREAD

**Issue by Topnitel** [GeyserMC/Geyser#1589]
**java sword sweep/swipe effect**
i've reviewed the 'java addon' on mcpe, it works pretty well as it adds the java sword sweep effect, tho it depends on an addon instead of a resource pack by itself
there may be a way to make it be a resource pack with the sound and effect, but i dont know crap about coding

there were no alternatives

**Comment by DoctorMacc** [comment]
This has already been requested in #1409. Thank you for requesting anyway!
