### ISSUE TITLE
a bug or a question about rowing boat

### ISSUE THREAD

**Issue by FrankHan052176** [GeyserMC/Geyser#1596]
**Describe the bug**
players can not row the boat on the ice.when players get on the boat,the boat will hang in the air in the perspective of the players of Java edition

**Server Version1.14.4

**Geyser Version1.2

**Minecraft: Bedrock Edition Version1.16.100.6

**Comment by MagnoBooter** [comment]
Could this possibly be a duplicate of issue #1585 ?

**Comment by DoctorMacc** [comment]
Yes, and it doesn't follow the full issue template anyway, so I will close this. Thank you anyway!
