### ISSUE TITLE
Scoreboard Issue

### ISSUE THREAD

**Issue by PQguanfang** [GeyserMC/Geyser#1597]
**Describe the bug**
Scoreboard is not work well. It may normal when the scoreboard only have some player information. But when it has something like game countdown..

**To Reproduce**
1.Join your Geyser server.
2.See scoreboard.

**Expected behavior**
Scoreboard should work well.

**Screenshots / Videos**
![Screenshot_20201127_220132](https://user-images.githubusercontent.com/35395058/100457745-90417480-30fd-11eb-808e-ee9686d67660.jpg)

**Server Version**
git-Paper-294(1.16.4)

**Geyser Version**
1.2.0-SNAPSHOT (git-master-894275b) (Java: 1.16.4, Bedrock: 1.16.100.60 - 1.16.200.56)

**Minecraft: Bedrock Edition Version**
1.16.100

**Comment by DoctorMacc** [comment]
This appears to be the same issue as #1524. Regardless, thank you for reporting!
