### ISSUE TITLE
Occasionally Bedrock players will have limbs turn invisible

### ISSUE THREAD

**Issue by o1230sponge** [GeyserMC/Geyser#1598]
**Describe the bug**

Bedrock players will have the left arm and leg stop rendering occasionally. It seems to be at random. One user on Switch had the issue on log on, another on PS4 after about 20 minutes
**To Reproduce**

1. Log in
2. Play
3. Eventually limbs will stop rendering
**Expected behavior**

Full player model to always be visible for all players
**Screenshots / Videos**

[https://cdn.discordapp.com/attachments/596459812389126145/781884811505696820/My_Great_Capture_Screenshot_2020-11-27_09-11-03.png](url)
**Server Version**

Spigot 1.16.4 R0.1-Snapshot
**Geyser Version**

Geyser 1.2.0-SNAPSHOT
**Minecraft: Bedrock Edition Version**

1.16.100
**Additional Context**

**Comment by awgybop1** [comment]
Any errors in your Console? Does this happen suddenly, or only when you teleport?
Is this visible to everyone or only you?

**Comment by DoctorMacc** [comment]
Can you provide a Geyser dump?

**Comment by o1230sponge** [comment]
It happens suddenly from what I recall, but I can't say for certain.
It doesn't say anything in the console from what I recall, I haven't been told of it happening since I reported the bug. Next time I hear about it, I'll do a dump and give you more info.

**Comment by o1230sponge** [comment]
I managed to get it to happen again. It occurred after respawning.
Here is the link to the [dump](https://dump.geysermc.org/pJGkljt3wfRmMlKCAAOieCyEyEeRCaiv)
And the server console reports nothing

**Comment by DoctorMacc** [comment]
Thank you!

**Comment by Chew** [comment]
There have been no recent reports of this, so we're gonna assume it's been resolved. If you happen to reproduce it, please let us know, and we'll re-open this. Thank you, everyone, for your contributions!
