### ISSUE TITLE
Java7 is not supported? 

### ISSUE THREAD

**Issue by RisksY** [GeyserMC/Geyser#160]
**Describe the bug**
```
That's a very small problem. It shows warning when I start the server but it starts with no problem:
******************************************

Loading Geyser version 1.0-SNAPSHOT

******************************************
Feb 10, 2020 10:06:42 PM com.fasterxml.jackson.databind.ext.Java7Support <clinit>
WARNING: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
Started Geyser on 0.0.0.0:19132
Done (14.633s)! Run /help for help!
stop
Shutting down connector
```

Java version:
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~19.10-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```
OS: Ubuntu eoan latest

**To Reproduce**
1. Start the server when you're on Ubuntu. 
2. I don't remember if I installed Java myself but I think it came ready.
3. It will show that warning.

**Expected behavior**
Start server without this warning.

**Screenshots**
Will try.

**Server version**
not necessary

**Geyser version**
Jenkins

**Bedrock version**
not necessary

**Additional context**
Thanks.

**Comment by RednedEpic** [comment]
This warning is harmless but at the very least misleading. It’s due to one of our dependencies failing to recognize Java 7 support, but ultimately has no effect on the program whatsoever. Geyser requires Java 8 just FYI.

**Comment by RisksY** [comment]
Thanks!
