### ISSUE TITLE
GUI and chest spawning

### ISSUE THREAD

**Issue by MidWolfhunter** [GeyserMC/Geyser#1604]
**Describe the bug**

Whenever I try to open the GUIshop on a bedrock client (Windows 10) it only allows me to op en the GUI. It does not allow me to click on a section to enter it. It suddenly closes the GUI and spawns a chest above my head which does not dissapear, rather I have to break it myself.

**To Reproduce**

Download the latest version of GUIshop on the spigot page.
Then upload it to your server. 
Give the nessecsry permissions, (unless you are operetor).
A default shop had been added with items already so no need to add items. 
Type in the command /shop
Click on any section of the shop.

**Expected behavior**

I expected to be entering a section in the GUIshop. Unfortunately it did not happen, instead it exited the GUI unexpectedly.

**Screenshots / Videos**

I currently do not have any. Although I have shared on in the support1 discord channel

**Server Version**

1.16.100

**Geyser Version**

Geyser version 1.2-SNAPSHOT (git-master-eb68726) (java 1.16.4, Bedrock 1.16.100.60 - 1.16.200.56)
I am using geyser-spigot.jar

**Minecraft: Bedrock Edition Version**

Minecraft Windows 10 Edition version 1.16.100

**Additional Context**

Perhaps make an announcement in the discord server or email me at factionsunlimitedmcpe@gmail.com  once its fixed so that I can update right away. Thank you!

**Comment by lukeeey** [comment]
I don’t have anything to add to this issue, but I would like to point out the fact that you shouldn’t provide your email for us to contact you at. As much as we would love to let everyone know when we implement a feature or fix a bug, the reality is that we simply don’t have the time or reason to do it.

I’m not trying to be rude, just letting you know. You can watch this issue to be notified of any comments or when/if it’s been fixed.

**Comment by MidWolfhunter** [comment]
Good say'

I hope you are well. I completely understand your concern. I will follow up
on this bug instead. Thank you for taking the time to respond.

Yours faithfully
Dylan

**Comment by DoctorMacc** [comment]
I'm unable to confirm with the latest Geyser. GUIShop works fine for me.

**Comment by Super-Toaster** [comment]
It does the same for me as well. I use Bentobox + Bskyblock,challenges,control panel. and when i do /island challenges it spawns a double chest over my head

**Comment by Chew** [comment]
That's unrelated and is an intended feature.

**Comment by ArcticRaven** [comment]
I have similar issues with several GUI based resource - I've noticed the behavior in MMOItems when attempting to browse the Item Catalog and the occasional Chest Based GUI, it might be an issue with how Java Devs are handling inventories?

**Comment by Jens-Co** [comment]
Hello there, are you still having this problem with GUIshop? If so can you get back to us ASAP? Otherwise this issue will get closed soon.
Thanks Jens

**Comment by Camotoy** [comment]
Seeing as this issue predates the inventory rewrite and has not been reported since, I am going to safely close the issue. Do feel free to report a new issue if you can replicate it. Thank you!
