### ISSUE TITLE
Geyser standalone prints out ANSI codes to the log files

### ISSUE THREAD

**Issue by clrxbl** [GeyserMC/Geyser#1606]
**Describe the bug**
Geyser standalone prints out ANSI codes to the log files

**To Reproduce**
Run Geyser standalone

**Expected behavior**
Don't print ANSI codes to logs so they can be read properly. 

**Screenshots / Videos**
```
2020-11-29 12:15:03.513 [main] I - {^[[0m^[[1m^[[0m}
2020-11-29 12:15:03.516 [main] I - {^[[0m^[[1mLoading Geyser version 1.2.0-SNAPSHOT (git-master-eb687e6)^[[0m}
2020-11-29 12:15:03.517 [main] I - {^[[0m^[[1m^[[0m}
```

**Server Version**
N/A

**Geyser Version**
Geyser version 1.2.0-SNAPSHOT (git-master-eb687e6)

**Minecraft: Bedrock Edition Version**
N/A

**Additional Context**
Likely related to https://github.com/GeyserMC/Geyser/blob/master/bootstrap/standalone/src/main/java/org/geysermc/platform/standalone/GeyserStandaloneLogger.java. I tried modifying log4j2.xml but the colour codes are printed directly from {%msg}

**Comment by TOWUK** [comment]
![image](https://user-images.githubusercontent.com/28830162/101067854-156ad480-35a9-11eb-9a95-49390064a029.png)

**Comment by Chew** [comment]
Mac (Terminal, zsh):
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/8278263/101071083-bd5caf80-3561-11eb-915d-509ddbd38c31.png">

Ubuntu 18.04 (SSH via Termius)
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/8278263/101071255-f563f280-3561-11eb-97ce-36a6c64c1da1.png">

**Comment by clrxbl** [comment]
Windows does not support ANSI-codes for the most part in the default terminal emulator.

**Comment by lukeeey** [comment]
@Chew this is talking about the log files

**Comment by clrxbl** [comment]
While the original issue is about log files, the console printing out ANSI codes on Windows is likely related to the same issue.

**Comment by oldium** [comment]
What about the new Windows Terminal? Does it work there?

**Comment by clrxbl** [comment]
Windows Terminal works fine

**Comment by TOWUK** [comment]
windows
console mode and just run jar file

![image](https://user-images.githubusercontent.com/28830162/101236693-5582a200-36e4-11eb-9fd9-1cf909d546ca.png)
![image](https://user-images.githubusercontent.com/28830162/101236711-71864380-36e4-11eb-97f9-2263796d9885.png)
latest update fixed it?

**Comment by RednedEpic** [comment]
Is this still a problem for anyone? I am unable to reproduce this.

**Comment by Camotoy** [comment]
Yes lol

**Comment by clrxbl** [comment]
```
2021-07-24 16:58:51.071 [main] I - ^[[0m^[[1m******************************************^[[0m
2021-07-24 16:58:51.087 [main] I - ^[[0m^[[1m^[[0m
2021-07-24 16:58:51.118 [main] I - ^[[0m^[[1mLoading Geyser version 1.4.1-SNAPSHOT (git-master-c658913)^[[0m
2021-07-24 16:58:51.119 [main] I - ^[[0m^[[1m^[[0m
2021-07-24 16:58:51.119 [main] I - ^[[0m^[[1m******************************************^[[0m
2021-07-24 16:58:56.527 [main] I - ^[[0m^[[1mLoaded Floodgate key!^[[0m
```

yes
