### ISSUE TITLE
Unable to connect to world

### ISSUE THREAD

**Issue by DiamondCreeper14** [GeyserMC/Geyser#1607]
Java players can connect and there are errors in my console. I've tried restarting minecraft and the port is forwarded.
The server is being hosted on lunix Ubuntu.
I've tried everything on (https://github.com/GeyserMC/Geyser/wiki/Fixing-%22Unable-to-Connect-to-World%22) and still not working

**Comment by DoctorMacc** [comment]
Please join our Discord for issues like these! (In the future, please follow the issue template.) Thank you!
