### ISSUE TITLE
New Movement System Issue

### ISSUE THREAD

**Issue by Legit4K** [GeyserMC/Geyser#1609]
**Describe the bug**

The New Movement System is Geyser seems to trigger multiple false positives on various different Anticheats such as Matrix, Spartan and WitherAC when walking up a block. It specifically triggers the Anti Fly Module and modifying the VL Value does not reduce the impact. 

**To Reproduce**

Walk up a block

**Expected behavior**

Successfully walk up a block without reverting movement / triggering AC. 

**Screenshots / Videos**

https://imgur.com/a/qOKZNys

**Server Version**

Paper-294 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**

This server is running Geyser version 1.2
.0-SNAPSHOT (git-master-eb687e6) (Java: 1.16.4, Bedrock: 1.16.100.60 - 1.16.200.56)

**Minecraft: Bedrock Edition Version**

1.16.100

**Additional Context**

**Comment by Chew** [comment]
Hey there! Thank you for the report. Are you still able to reproduce this issue with the latest builds?

**Comment by Legit4K** [comment]
Yes, however this issue is more or less fixed with the #1814 PR

**Comment by Jens-Co** [comment]
Hello @Legit4K, Any more info about this issue ? Otherwise ill test it and close this issue.

**Comment by Legit4K** [comment]
The referenced PR has since been merged so this issue has been resolved 🎉
