### ISSUE TITLE
Why not support BungeeCord Server？

### ISSUE THREAD

**Issue by LazyCreeper** [GeyserMC/Geyser#161]
I can't join BungeeCord Server :(
`java.ioException：你的主机中的软件终止了一个已建立的连接`

---

And I can't join PaperSpigot 1.14.4
![Screenshot_2020-02-11-19-46-19-688_com.mojang.min.jpg](https://imgs.lovpass.cn/img/2020/02/11/422439e41f47320200211.jpg)
https://imgs.lovpass.cn/img/2020/02/11/422439e41f47320200211.jpg
Minecraft Version:`1.14.4`
MCPE Version:`1.14.20.1`

**Comment by LegacyGamerHD** [comment]
1.15.2 only or add via version

**Comment by RednedEpic** [comment]
The error tells you exactly what the issue is. Only the latest release of JE (currently 1.15.2 is supported).
