### ISSUE TITLE
Teleport api maybe....

### ISSUE THREAD

**Issue by TOWUK** [GeyserMC/Geyser#1612]
**Describe the bug**
teleport not worked (maybe error api plugin?)

**To Reproduce**
dont work teleport to spawn if falling to void.

**Expected behavior**
Usually the plugin teleports to spawn when falling into the void, here it does not kill or teleport to spawn.

**Screenshots / Videos**
VIDEO: https://youtu.be/l0mXBa3yT5s

**Server Version, Geyser Version, Minecraft: Bedrock Edition Version**
check dump (all latest software)

**Additional Context**
DUMP: https://dump.geysermc.org/bv1FtLHvDe63c1edEXALm7xtXgEZ8PDZ

**Comment by DoctorMacc** [comment]
This is likely because we have not merged our void floor workaround.

**Comment by TOWUK** [comment]
> This is likely because we have not merged our void floor workaround.

what do you mean?

**Comment by EasyClifton** [comment]
> > This is likely because we have not merged our void floor workaround.
> 
> what do you mean?

Bedrock has an invisible floor at -40 y, and it's not removable. So basically what the void floor workaround does is teleport you one block below it so you can fall further.

**Comment by Camotoy** [comment]
This is likely fixed in the next build.
