### ISSUE TITLE
Crashes the Bedrock players game suddenly after joining the Server

### ISSUE THREAD

**Issue by Sub2Assassin** [GeyserMC/Geyser#1613]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by DoctorMacc** [comment]
Please fill in the issue template. Thank you!

**Comment by Sub2Assassin** [comment]
when joining with the bedrock, lobby loads and it crashes the game completely

![screenshot-panel apexminecrafthosting com-2020 12 02-23_01_16](https://user-images.githubusercontent.com/71583933/100909220-7388b080-34f2-11eb-8370-a33d5e90ecc5.png)
My console...while I join with bedrock

The server is running on 1.16.3 Paper

Geyser-spigot.jar Latest version

Minecraft Bedrock 1.16.100

**Comment by DoctorMacc** [comment]
Thank you.

This problem has been reported, and we are working on a fix.

**Comment by Sub2Assassin** [comment]
thank you very much.

**Comment by Sub2Assassin** [comment]
When and from where Will I know if the fix is implemented?

**Comment by DoctorMacc** [comment]
Watch the added commits here or Jenkins for scoreboard changes.
