### ISSUE TITLE
Joining with bedrock Instantly crashes the game

### ISSUE THREAD

**Issue by Sub2Assassin** [GeyserMC/Geyser#1614]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by Paul-Lukas** [comment]
Do have this problem with PE

**Comment by DoctorMacc** [comment]
Please fill out the issue template on your existing issue, and then we can open the issue.
