### ISSUE TITLE
Player heads show up as Steve heads in the bedrock edition of Minecraft

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [GeyserMC/Geyser#1616]
**Describe the bug**
Player heads show up as steve heads on the bedrock edition of minecraft

**To Reproduce**
1. Obtain/place a player head.
2. On java, the head looks like it should, however, on the bedrock edition, it shows up as a steve head.

**Expected behavior**
I would expect the player head to be the same as it is on the java edition

**Screenshots / Videos**
Bedrock:
![image](https://user-images.githubusercontent.com/66212375/100935459-1d9a1580-34be-11eb-866c-ba1f1ba256ab.png)
Java:
![image](https://user-images.githubusercontent.com/66212375/100935489-27237d80-34be-11eb-91ff-2f7058e9c120.png)

**Server Version**
paper (git-version-277)

**Geyser Version**
1.2.0 SNAPSHOT

**Minecraft: Bedrock Edition Version**

**Additional Context**
https://dump.geysermc.org/1FPlikA1iIYFPGxeHRDJQ6o7yto6SSK5

**Comment by bolo374** [comment]
Bedrock doesn't support player heads, I don't think there's a way for geyser to fix that.


also that's my head pog

**Comment by j5155** [comment]
They're working on this, here's the pr: https://github.com/GeyserMC/Geyser/pull/683#issue-424766065
If you want, you can use the artifacts button to install it.

**Comment by Galgonite** [comment]
YO Thats my head.

**Comment by Galgonite** [comment]
pog champ

**Comment by DUDEbehindDUDE** [comment]
oh okay thanks
