### ISSUE TITLE
Unable to do any commands in bedrock

### ISSUE THREAD

**Issue by masterblaster221** [GeyserMC/Geyser#1618]
I'm unable to do any commands it says cheats aren't enabled on this level. it's weird because I'm op. I'm using apex Minecraft hosting if that's anything to do with it?
![Screenshot 2020-12-03 073844](https://user-images.githubusercontent.com/35042730/101042624-a191e300-353a-11eb-96d0-05745416b6a5.png)

**Comment by rtm516** [comment]
This is due to the `xbox-achievements-enabled` setting being enabled, please set that to false if you would like to use 'cheat' commands. This is not something we can fix, it is a bedrock limitation.

**Comment by Noxillio** [comment]
I have this same issue and I'm not even using "cheat" commands. It is literally ALL COMMANDS. Absolutely NOTHING works.

**Comment by EasyClifton** [comment]
You still need to disable the `xbox-achievements-enabled` option in the config.

**Comment by Camotoy** [comment]
Do you have `xbox-achievements-enabled` set to true in your config? If so, there's literally no workaround. Bedrock disables the commands; we don't.

**Comment by Noxillio** [comment]
Why say "commands like 'gamemode' and 'give'" rather than all commands if that's the case? Seems very confusing.
