### ISSUE TITLE
Tropical fish not showing 

### ISSUE THREAD

**Issue by Nixuge** [GeyserMC/Geyser#162]
**Describe the bug**
Tropical fish aren't showing

**To Reproduce**
-Spawn a tropical fish
-Done

**Expected behavior**
Show the fish

**Screenshots**
https://i.imgur.com/q1qdUDT.jpg

**Server version**
1.15.2

**Geyser version**
Jenkins latest

**Bedrock version**
Latest

**Additional context**
No

**Comment by rtm516** [comment]
This is now fixed, as https://github.com/GeyserMC/Geyser/pull/374 was merged.
