### ISSUE TITLE
Bedrock players can break logs faster than Java players

### ISSUE THREAD

**Issue by kADOMPHy** [GeyserMC/Geyser#1621]
**Describe the bug**
Bedrock players can instantly mine different type of log blocks (for example, oak logs)

**To Reproduce**
1. Give bedrock user efficiency 5 netherite axe (probably works with diamond too)
2. Give bedrock user haste 2
3. Mine log blocks

**Expected behavior**
The speed of log breaking from bedrock players match Java vanilla breaking speeds.

**Screenshots / Videos**
Video comparison - https://cdn.discordapp.com/attachments/723107369759801344/784139285887713330/Geyser_issue.mp4

**Server Version**
`This server is running Tuinity version git-Tuinity-"957a2ef" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)`

**Geyser Version**
`This server is running Geyser version 1.2.0-SNAPSHOT (git-master-a70d3e2) (Java: 1.16.4, Bedrock: 1.16.100.60)`

**Minecraft: Bedrock Edition Version**
`1.16.100`

**Comment by HelveticaToast** [comment]
This isn't an issue, it's bedrock edition mining speeds.

**Comment by j5155** [comment]
> This isn't an issue, it's bedrock edition mining speeds
Doesn't geyser need to make Bedrock match Java? This may be a Bedrock bug, but Geyser still needs to find a workaround.

**Comment by TOWUK** [comment]
check it on paper.

**Comment by Chew** [comment]
That shouldn't make a difference. This is still probably a bedrock bug

**Comment by masterblaster221** [comment]
I can confirm that it takes the same time to brake a log! if you go on mobile the circle filling to show destruction time is the same. I time tested. but the block looks as if its faster?

**Comment by kADOMPHy** [comment]
> I can confirm that it takes the same time to brake a log! if you go on mobile the circle filling to show destruction time is the same. I time tested. but the block looks as if its faster?

Look at the video - you can almost instantly mine the logs, where in java, it takes longer. This is broken especially when using jobs plugin (bedrock players can make money much faster)

**Comment by Camotoy** [comment]
The issue here is that Bedrock thinks that the break time should be shorter, and Java happens to accept the speed.

**Comment by shinnag0103** [comment]
I'm using bedwars  plugin and the big problem is obsidian breaking speed.
I hope this problem will be resolved soon.

**Comment by wellnesscookie** [comment]
Greetings, this is still an issue on latest minecraft and geyser versions. Players with Bedrock mine blocks almost instantly without requing super enchantments as java players.

**Comment by onebeastchris** [comment]
Fixed natively in Bedrock 1.20.30 and higher - [source](https://feedback.minecraft.net/hc/en-us/articles/19545277817357-Minecraft-1-20-30-Bedrock-)
Specifically:
> We have adjusted the breaking times of 188 blocks to match Java Edition and our intended design. Some blocks couldn't be changed yet for technical reasons and Obsidian was left unchanged because we're still deciding what breaking speed it should have. Bringing more blocks to parity makes it easier for our team to keep both versions up to date. We also hope it will be easier for the community to make and share guides that work for all players on all platforms.

Logs should now have the same break times across both versions :)
