### ISSUE TITLE
Texts on sign keep disappearing

### ISSUE THREAD

**Issue by AxeTPG** [GeyserMC/Geyser#1622]
Hi, I'm using Geyser 1.1.0 for Minecraft Bedrock 1.16.20 and 1.16.40, And we're using Paper Spigot server,

the thing is whenever I'm done on first line of sign, so i will press enter button to write to the 2nd line,
3rd line and 4th, but after writing on the sign,
it only shows the first line texts,

because of this I can't setup my chest shop

**Comment by rtm516** [comment]
We don't support older versions of Geyser, this has been fixed in the latest release. Please download that from https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/

**Comment by DoctorMacc** [comment]
This might not have been fixed. Regardless, your issue has been reported, you're on an older version and you have not followed the issue template.
