### ISSUE TITLE
Can’t place non bedrock items in offhand

### ISSUE THREAD

**Issue by TKDKid1000** [GeyserMC/Geyser#1624]
So I was testing out some java features in bedrock. (Like redstone and commands) I also tried putting steak in my offhand. In java any item is placeable in the off hand. I tried in bedrock, and it didn’t work. I can only put maps, arrows, fireworks, and shields in my off hand.

1. Click on any any (not a map, shield, firework, or arrow) in the inventory
2. Click on the Shield slot underneath the crafting grid

Placing the item into the off hand.

This server is running CraftBukkit version git-Spigot-37d799b-3eb7236 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

This server is running Geyser version 1.2.0-SNAPSHOT (git-master-24fd7da) (Java: 1.16.4, Bedrock: 1.16.100.60 - 1.16.200.56)

1.16.101

Geyser dump: https://dump.geysermc.org/avTRHqJERnKEqH85FgNMwOty0VsjXgIT

**Comment by DoctorMacc** [comment]
Unfortunately as of right now this can't be worked around due to Bedrock limitations. For the time being, please use `/geyser offhand`.
