### ISSUE TITLE
walking up partial blocks is impossible

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Geyser#1626]
**Describe the bug**

**To Reproduce**
1. load geyser, connect to java server on bedrock, try to step up a block that is <0.6 blocks height

**Expected behavior**
you step up the block
**Actual behavior**
you continuously glitch back to previous location

**Server Version**
paper 1.16.4

**Geyser Version**
Geyser version 1.2.0-SNAPSHOT

**Minecraft: Bedrock Edition Version**
1.16.100

**Comment by DoctorMacc** [comment]
Please provide a Geyser dump.

**Comment by Maximillus** [comment]
completely stock plugin/paper setup

**Comment by Maximillus** [comment]
I think this is problem with the server.

**Comment by DoctorMacc** [comment]
Unable to replicate with same Paper version and latest Geyser with clean setups for both.

**Comment by Heath123** [comment]
Please provide a dump, or at least tell us if chunk caching is on (having it on should help)

**Comment by Maximillus** [comment]
chunk caching is on yes

**Comment by Maximillus** [comment]
its default geyser setup like i say

**Comment by Heath123** [comment]
Can you provide a dump please?

**Comment by Heath123** [comment]
> Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

> If you use the Geyser Standalone GUI then it is inside the Commands menu as seen below.

**Comment by Maximillus** [comment]
i said its a server problem already, issue doesnt happen on vanilla server https://dump.geysermc.org/xoGDb3JeFVUSQLdJKDfD5CQOlZaTO8hh

**Comment by Heath123** [comment]
> issue doesnt happen on vanilla server

We still need to fix it because most people don't use vanilla servers

**Comment by Hellohi3654** [comment]
You can use https://github.com/Heath123/floodgate-noclip if you use floodgate as a fix for now

**Comment by Heath123** [comment]
No idea if that actually still works though

**Comment by Camotoy** [comment]
I'm going to close this in about a week if there is no response, as we haven't had anyone else report this. Thank you for the report anyway!

**Comment by Tydium** [comment]
I think I may have experienced this on Geyser-Bungee a few times even with chunk caching on. Sometimes it does it sometimes it doesnt. Not entirely sure how to reproduce it.

**Comment by Jens-Co** [comment]
Hello, any feedback on this ? If no response at all I'll be closing this issue. 
Jens

**Comment by Tydium** [comment]
Yeap. I think I might also have this

**Comment by Jens-Co** [comment]
I'll do some testing later today thanks.

**Comment by spookymgmt** [comment]
Having similar issues on 1.17.1. Latest geyser.

**Comment by RednedEpic** [comment]
If you are going to bump issues @spookymgmt, can you please provide further information on how to replicate this as well as include a video?

**Comment by RednedEpic** [comment]
Closing due to lack of response. Movement has been updated a lot over the past year so chances are this no longer is an issue.
