### ISSUE TITLE
Colored particles do not work

### ISSUE THREAD

**Issue by Maximillus** [GeyserMC/Geyser#1627]
**Describe the bug**

Redstone particles with rainbow colors show as only red

**To Reproduce**
go on java edition server and display colored redstone particles

Server Version
paper 1.16.4

Geyser Version
Geyser version 1.2.0-SNAPSHOT

Minecraft: Bedrock Edition Version
1.16.100

**Comment by DoctorMacc** [comment]
This is a limitation of Bedrock at this time.

**Comment by TOWUK** [comment]
really worked?

**Comment by Camotoy** [comment]
RTM and I had an understanding that it was impossible, but Redned and his vast knowledge from CubeCraft helped us out.
