### ISSUE TITLE
Error with loading GeyserMC with WaterFall

### ISSUE THREAD

**Issue by EddieDiamondFire** [GeyserMC/Geyser#1629]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by EasyClifton** [comment]
I think you accidentally put everything in a comment

**Comment by Chew** [comment]
Probbaly same problem with https://github.com/PaperMC/Waterfall/issues/588.

**Comment by EddieDiamondFire** [comment]
yea I accidently filed this which is not related to GeyserMC
