### ISSUE TITLE
Can`t locate server

### ISSUE THREAD

**Issue by baxandrei** [GeyserMC/Geyser#163]
I configured Geyser and started it, I got into the game (bedrock v1.14.20) and my server appears red, it cannot be located. The Java server is on version 1.15.2, but I think the problem is from Geyser because the server appears offline.

**Comment by Nixuge** [comment]
Is the server on the save pc as the client?

**Comment by RednedEpic** [comment]
See the common issues page on the wiki.

**Comment by baxandrei** [comment]
`CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"` solved my problem. THank you!
