### ISSUE TITLE
Ability to register new commands that are not under /geyser

### ISSUE THREAD

**Issue by bundabrg** [GeyserMC/Geyser#1637]
**What feature do you want?**
Presently it is possible to register subcommands of `/geyser`. However with extensions it may be desirable to be able to provide top level commands of our own.

For example, with the `GeyserReversion` extension it would probably be better to have a `/geyserreversion` and optional `/gr` that takes care of all things related to that extension.

This is a non-required dependency of https://github.com/GeyserMC/Geyser/pull/742

(Also a good first issue for someone wanting to contribute)

**Comment by RednedEpic** [comment]
Seems you've already opened a feature request for this in #1371 😉.
