### ISSUE TITLE
The bungeecord plugins won't take the IP's

### ISSUE THREAD

**Issue by Redwolf223** [GeyserMC/Geyser#1641]
**Describe the bug**
When a player connect to the bungeecord, the plugin with high priority takes the local IP and not the one of the player.

**To Reproduce**

Use Floodgate and GeyserMC bungeecord with a plugin that takes the IP of the player when he joins. 

**Expected behavior**
When a player joins the IP should be the one of the player instead of the local machine.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/58572866/101549166-73365c80-39ad-11eb-8669-fe715db0256d.png)

**Server Version**

Geyser version 1.2.0-SNAPSHOT (git-master-3bcdf4c) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.56)

**Geyser Version**

Geyser version 1.2.0-SNAPSHOT (git-master-3bcdf4c) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.56)

Yes, we are using Floodgate 1.0 Alpha

**Minecraft: Bedrock Edition Version**
16.4.1

**Additional Context**

Right now we are using the connector but it's doing the same thing with the plugin.
https://dump.geysermc.org/jGdXRetLnLHr3pKPj3e3OxDffRCd7HAx

**Comment by DoctorMacc** [comment]
Floodgate is made to prevent people of using offline mode and is not supported using it alongside offline mode. Feel free to open the issue again if it still doesn't work when you remove FastLogin, but we won't provide support for offline mode server.

**Comment by Redwolf223** [comment]
Issue persist even if online mode is true and we remove FastLogin.

**Comment by iSilviu-debug** [comment]
join in issue @DoctorMacc
