### ISSUE TITLE
Microsoft based minecraft accounts cannot sign in

### ISSUE THREAD

**Issue by yfvham** [GeyserMC/Geyser#1648]
It appears that only legacy mojang account can sign in, I have tested with two newer Microsoft based accounts and neither of them will make it past the sign in prompt once I connect to the Geyser endpoint. 

I am on bedrock 1.16.200

**Comment by RednedEpic** [comment]
Yes, we are aware of this. We’re currently working on support for these accounts 😄

**Comment by yfvham** [comment]
Is there an existing issue for this? I didn't manage to find one before I opened this one.

**Comment by RednedEpic** [comment]
> Is there an existing issue for this? I didn't manage to find one before I opened this one.

This is the first. MSA-based sign-in for Minecraft: Java Edition only became a thing on the first of this month, so it’s still quite new.

**Comment by TOWUK** [comment]
msa? what is?

> > Is there an existing issue for this? I didn't manage to find one before I opened this one.
> 
> This is the first. MSA-based sign-in for Minecraft: Java Edition only became a thing on the first of this month, so it’s still quite new.

**Comment by Camotoy** [comment]
MSA = Microsoft authentication. https://www.minecraft.net/en-us/article/java-edition-moving-house

**Comment by InfRandomness** [comment]
Hello, I'd like to know if there's an ETA for the release of this feature

**Comment by EasyClifton** [comment]
> It'll be done when it's done. Considering the type of software Geyser is, we can't just throw out ETA's left and right. It could be a matter of a few hours before your feature or bug is fixed, or a few months. Sometimes we hit roadblocks or run into issues that we didn't expect. Please be patient; we'll get around to it when we have time or more information is learned.

A quote from our Discord server. But I guess this will be implemented in the near future.
