### ISSUE TITLE
ReadTimeoutException: null when switching servers with BungeeCord

### ISSUE THREAD

**Issue by tlkh40** [GeyserMC/Geyser#1650]
**Describe the bug**

When switching servers bedrock players will get ReadTimeoutException: null

**To Reproduce**
1.Make a bungee server with geyser.
2. Switch to a different server.
3.Get the error thats seen in the video below.

**Expected behavior**
It should connect without timing out.

**Screenshots / Videos**
tlkh40.com/geyser/timeout.mp4

**Server Version**
sans2 (look in video) : This server is running Origami version git-Origami-"7f7edcf" (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

lobby: This server is running Origami version git-Origami-"7f7edcf" (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

Note : I have tried with both paper and spigot and they have the same result.

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-39a11da) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)

**Minecraft: Bedrock Edition Version**
Minecraft Bedrock Edition / Pocket Edition 1.16.100

**Additional Context**
https://dump.geysermc.org/OFULiCfQDQiiclodMBb1U6DiTQfCPZE0

**Comment by Camotoy** [comment]
Have you tried without BungeeGuard?

**Comment by tlkh40** [comment]
Yes, and it works just fine.

**Comment by tlkh40** [comment]
oh wait
i miss read
but no same thing (sorry if i caused a problem)

**Comment by tlkh40** [comment]
oh yeah one more thing if i use geyser standalone if the player joins they would crash.

**Comment by Camotoy** [comment]
Does changing `passthrough-player-counts` do anything for BungeeCord?

**Comment by tlkh40** [comment]
No it doesn't do anything

**Comment by Camotoy** [comment]
Label added to the wrong issue. I might look at this later, but I suspect a plugin is in play. Try removing all your plugins and see if the problem persists.

**Comment by tlkh40** [comment]
sorry for not responding i was very busy with school ill try to do it when i have some free time

**Comment by tlkh40** [comment]
ok i have just tried it out without any plugins
and it works
should i try with bungeeguard again ?

**Comment by tlkh40** [comment]
i can confirm again that it works with bungeeguard 
is it cus of luckperms or authme

**Comment by Camotoy** [comment]
Any update on this issue by chance?

**Comment by tlkh40** [comment]
this doesnt happen anymore.

**Comment by Camotoy** [comment]
Thanks!
