### ISSUE TITLE
If die in the Respawn area where the monster resides, and if don't resurrect immediately, the monster location synchronization is not correct.

### ISSUE THREAD

**Issue by rosiecube** [GeyserMC/Geyser#1652]
**Describe the bug**

If die in the Respawn area where the monster resides, and if don't resurrect immediately, the monster location synchronization is not correct.

**To Reproduce**

1. Killed by a monster in the respawn area
2. Check monster movement to another client
3. Respawn
4. Synchronized from pre-death position to relative position.

**Expected behavior**

When resurrected, the monster's position must be refreshed.

**Screenshots / Videos**

![unknown (1)](https://user-images.githubusercontent.com/53262103/101869121-1364cf00-3bc2-11eb-9581-ec336b26e139.png)

**Server Version**

![image](https://user-images.githubusercontent.com/53262103/101869150-26779f00-3bc2-11eb-9d9b-7f39968a7f8d.png)

**Geyser Version**

![image](https://user-images.githubusercontent.com/53262103/101869810-ace0b080-3bc3-11eb-9252-c597ed23a959.png)

**Minecraft: Bedrock Edition Version**

1.16.200

**Additional Context**

https://dump.geysermc.org/LymNbGyZkrIEyEObgzvvtTUNfc0AAswI

**Comment by rosiecube** [comment]
Especially the skeleton

**Comment by Camotoy** [comment]
I'm not sure what `Lisbon` means,

**Comment by rosiecube** [comment]
> I'm not sure what `Lisbon` means.

I'm sorry.. Lisbon -> Respawn

**Comment by RednedEpic** [comment]
Is this still an issue?

**Comment by RednedEpic** [comment]
Seeing that there hasn't been a reply here since December of last year, I am going to assume this is resolved.
