### ISSUE TITLE
Protocol library not correctly handling invalid packets

### ISSUE THREAD

**Issue by iSilviu-debug** [GeyserMC/Geyser#1653]
**Describe the bug**
There are some players that send packets that spam the console with Exception, this is a problem because after a while it starts to saturate the cpu making everything laggy and eventually making Geyser crash. Can you fix this?

**To Reproduce**
Send a very large package crashing the library RakNet

**Expected behavior**
The server must not receive packets and reach 100% ci cpu.

**Screenshots / Videos**
https://pastebin.com/TN4sQ6B0

**Server Version**
This server is running Waterfall version git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:40370a3:388 by md_5

**Geyser Version**
Geyser version 1.2.0-SNAPSHOT (git-master-91cdda9) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)

**Minecraft: Bedrock Edition Version**
1.16.100

**Additional Context**
🌵

**Comment by Camotoy** [comment]
Please send a Geyser dump as well.

**Comment by iSilviu-debug** [comment]
https://dump.geysermc.org/qj5lMjXEO5Dl7yNL8DzHzKicbwZo9yvs

**Comment by Camotoy** [comment]
Do you have proof that this is because of malicious intent?

**Comment by iSilviu-debug** [comment]
Yes of course, it was exactly one person.

**Comment by iSilviu-debug** [comment]
Any idea?

**Comment by RednedEpic** [comment]
Not seen any reports on this since this issue was opened and the packet handling in the Network library has changed slightly since then. This issue is likely no longer an issue as a result, but thanks for reporting!
