### ISSUE TITLE
multiple issues

### ISSUE THREAD

**Issue by Topnitel** [GeyserMC/Geyser#1654]
**Describe the bug**
1. thorns enchantment not giving the red effect on mobs if the enchantment deals damage
2. written books become un-written after a few seconds / immediately
3. armour boots disappear after a while and will appear either by putting other boots of just waiting
4. naming with anvil breaks, not even while putting enchantments or merging items
**To Reproduce**
1.
  -get thorns on your armour
  -make a mob hit you
  -the mob gets slight knockback, takes damage, does not have the becoming-red effect
2. 
  -write a book
  -close it or sign it
  -the book becomes the default book and quill
3.
  -literally do anything (i havent observed closely)
  -the boots' protection and enchantments are still there, just disappearing visually
4. 
  -try to name something
  -it doesn’t allow you, the arrow for the result is still crossed
**Expected behavior**
1. mobs become red upon getting damaged by the thorns enchantment on armour
2. the book is written properly
3. the boots dont disappear
4. naming items with an anvil should be possible
**Screenshots / Videos**
i didnt get any unfortunately
**Server Version**
paper build 323, version 1.16.4
**Geyser Version**
510
**Minecraft: Bedrock Edition Version**
1.16.200 all devices
**Additional Context**
none applicable, have not yet created a dump

**Comment by Topnitel** [comment]
sorry if theres trouble reviewing multiple issues in 1 post

**Comment by jkcoxson** [comment]
They are gonna ask you to put them in different issues

**Comment by RednedEpic** [comment]
Please reopen these as individual issues. Additionally, it seems some of the issues you have included here already have issues opened for them, so make sure to check for those before opening one 🙂
