### ISSUE TITLE
Enchantment tables broken

### ISSUE THREAD

**Issue by Peng1029** [GeyserMC/Geyser#1655]
**Describe the bug**

The enchantment table doesn't work just as said here https://github.com/GeyserMC/Geyser/issues/1302#issue-702309880
**To Reproduce**
get on bedrock
and try to enchant with levels
**Expected behavior**

I can enchant stuff

**Screenshots / Videos**

**Server Version**

No idea sorry
**Geyser Version**

above 1.16.100 and on bungee cord so assuming the 517 build? this may not be exact but I'm not the server owner and they updated yesterday of 12,10,2020 if that helps
**Minecraft: Bedrock Edition Version**

1.16.200
**Additional Context**

**Comment by Camotoy** [comment]
I just tested this on Paper and the latest Geyser version and had no issues. Without further information about the server, we cannot  figure out this issue. Either obtain a dump of the server, or provide an IP address with consent from the server owner.
