### ISSUE TITLE
Unable to fly as high on Geyser

### ISSUE THREAD

**Issue by jkcoxson** [GeyserMC/Geyser#1657]
**Describe the bug**
When I use rockets to fly almost straight up on a Java account and a Bedrock world I can go up about 100-120 blocks, but when playing on Geyser I only get about 60-70

**To Reproduce**
Join a world on Geyser, use rockets and point about 75 degrees up

**Expected behavior**
Being able to fly 100-120 up

**Screenshots / Videos**
https://drive.google.com/file/d/1QFaTN9Iz8fxGXo3IDQeEVGEFqQnxOWYM/view?usp=sharing

**Server Version**
1.16.100

**Geyser Version**
1.2.0

**Minecraft: Bedrock Edition Version**
1.16.200

**Additional Context**
I'm using velocity

**Comment by Camotoy** [comment]
Does this issue still persist?

**Comment by Camotoy** [comment]
No response, and I was unable to replicate this. I am closing; if you believe this is in error do let us know!
