### ISSUE TITLE
can't name anything

### ISSUE THREAD

**Issue by vent1998** [GeyserMC/Geyser#1658]
**Describe the bug**
name tags won't allow bedrock users to put a name on name tags

**To Reproduce**

 1. Go to the anvil
 2. Click on a name tag

**Expected behavior**
to be able to use name tags

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/75877956/101979097-8a7c8080-3c1f-11eb-8cce-3a5ddecd2041.png)

**Server Version**
CraftBukkit version git-Spigot-a19903d-5b74714 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
1.2.0-SNAPSHOT (git-master-a60ab4e) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5) spigot

**Minecraft: Bedrock Edition Version**
1.16.4

**Additional Context**

**Comment by rhld16** [comment]
This might me just being naive but I can't find the ClientRenameItemPacket (which is what's created on an item being renamed [here](https://github.com/GeyserMC/Geyser/blob/41cb593dc43ae3058c552f2302d726f172ee6a9d/connector/src/main/java/org/geysermc/connector/network/translators/inventory/AnvilInventoryTranslator.java#L121) in the NukkitX protocol lib?

**Comment by Camotoy** [comment]
@rhld16 The NukkitX/Cloudburst Protocol library handles only the Bedrock side of things at this time. You should be looking here for the Java communications library: https://github.com/Steveice10/MCProtocolLib :)

**Comment by rhld16** [comment]
> @rhld16 The NukkitX/Cloudburst Protocol library handles only the Bedrock side of things at this time. You should be looking here for the Java communications library: https://github.com/Steveice10/MCProtocolLib :)

Ah yes I see now. So me just being naive... Carry on like nothing happened.

**Comment by Camotoy** [comment]
This is specifically a 1.16.200 bug. 1.16.100 understands the name tag is being renamed.

**Comment by Hellohi3654** [comment]
Can confirm
