### ISSUE TITLE
Occupying too many ports

### ISSUE THREAD

**Issue by bilibili237594166** [GeyserMC/Geyser#166]
**Describe the bug**
This proxy will perform IPv4 loopback, forcibly occupying most of the ports on the host, causing other servers that have been opened to fail to operate normally.

**To Reproduce**
1. Run the proxy
2. Wait a moment.
3. Check your port occupation list

**Expected behavior**
Only occupy the set port.

**Screenshots**

**Server version**
WindowsServer2012R2

**Geyser version**
least

**Bedrock version**
1.14.30.2

**Additional context**
My English is not good, All the content is machine translation, Please forgive me.

**Comment by RednedEpic** [comment]
> **Describe the bug**
> This proxy will perform IPv4 loopback, forcibly occupying most of the ports on the host, causing other servers that have been opened to fail to operate normally.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Run the proxy
> 2. Wait a moment.
> 3. Check your port occupation list
> 4. See error
> 
> **Expected behavior**
> Only occupy the set port.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Server version**
> WindowsServer2012R2
> 
> **Geyser version**
> least
> 
> **Bedrock version**
> 1.14.30.2
> 
> **Additional context**
> My English is not good, All the content is machine translation, Please forgive me.

Could you please provide screenshots and more information? Geyser should only use one port (default 19132) as specified in the config.

**Comment by XiaoLiuJiangYou** [comment]
![-1426d94230524527](https://user-images.githubusercontent.com/53588108/74581688-15372380-4fed-11ea-835a-70b8d7936aa8.png)
![-37d83cd93d00e7ed](https://user-images.githubusercontent.com/53588108/74581689-1a946e00-4fed-11ea-8e14-1ebd996f7e92.png)

**Comment by RednedEpic** [comment]
This is not Geyser as Geyser opens a port over UDP.

**Comment by bilibili237594166** [comment]
Oh,I see.Thanks.
