### ISSUE TITLE
Crafting Bug

### ISSUE THREAD

**Issue by Rakise** [GeyserMC/Geyser#1661]
**Describe the bug**
I'm using ViaVersion And ViaRewind, geyser works fine, but bedrock clients can't craft in inventory or workbench, i'm using the plugin version of geyser.

**To Reproduce:**

1. go to a server
2. try to crafting

**Server Version**
CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) Implementing API version 1.8.8-R0.1-SNAPSHOT

**Geyser Version**
1.2.0-SnapShot
no floodgate

**Minecraft: Bedrock Edition Version**
1.16.200

https://dump.geysermc.org/ov9ZEWhQYhLPfXZzBAbpgRrzIdU6hvD8

**Comment by EasyClifton** [comment]
This issue occurs because your server version is too old. Crafting only works on versions above 1.11, since that's when the new crafting system Geyser relies on was introduced.

**Comment by Camotoy** [comment]
This is a duplicate of #511. Regardless, thank you for reporting!
