### ISSUE TITLE
Bedrock Players Can't Interact with some tile entities.

### ISSUE THREAD

**Issue by Cy4Shot** [GeyserMC/Geyser#1662]
Bedrock players cannot interact with chests, barrels, fence gates, shulker boxes and crops.

**To Reproduce**
1. Create a Paper server with GeyserMC and floodgate.
2. Connect with a bedrock client.

**Expected behavior**
Possibility to interact with tile entities.

**Server Version**
Server version - git-Paper-294 (MC: 1.16.4)

**Geyser Version**
Geyser version - 1.2.0-SNAPSHOT (git-master-41cb593) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)

**Minecraft: Bedrock Edition Version**
1.16.200

**Additional Context**
Dump: https://dump.geysermc.org/zKkbXiPgMv9irESKkhO8fyo0ypVjyMcT

**Comment by RednedEpic** [comment]
Try without plugins to see if the issue persists. Additionally, make sure you’re out of the server spawn protection radius.

**Comment by Cy4Shot** [comment]
> Try without plugins (other than Geyser & Floodgate) to see if the issue persists. Additionally, make sure you’re out of the server spawn protection radius.

There are no other plugins, not within spawn radius.

**Comment by RednedEpic** [comment]
> > Try without plugins (other than Geyser & Floodgate) to see if the issue persists. Additionally, make sure you’re out of the server spawn protection radius.
> 
> There are no other plugins, not within spawn radius.

According to your dump, you have ServerRestorer installed. Can you remove that plugin and test?

**Comment by Cy4Shot** [comment]
> > > Try without plugins (other than Geyser & Floodgate) to see if the issue persists. Additionally, make sure you’re out of the server spawn protection radius.
> > 
> > 
> > There are no other plugins, not within spawn radius.
> 
> According to your dump, you have ServerRestorer installed. Can you remove that plugin and test?

all it does is create a zip file with a command, it doesnt affect anything? i can still test tho.

**Comment by Camotoy** [comment]
With the latest Geyser and Floodgate and your version of Paper, I cannot replicate your issue.

**Comment by TheMasterBlaster** [comment]
Some plugins have issues with the default Floodgate prefix, I have found setting the prefix to " . " can sometimes help.

**Comment by ArcticRaven** [comment]
related to #1727 ?

**Comment by Chew** [comment]
No? Seemingly unrelated

**Comment by Camotoy** [comment]
The original issue mentions fence gates and crops, which are not inventories. Therefore they are very likely unrelated.

**Comment by Jens-Co** [comment]
Hello @Cy4Shot , are you still having trouble with this bug ? If so can you update Geyser and Floodgate and see if the bug persist ? Please let me know otherwise this issue will get closed soon.
Jens

**Comment by Cy4Shot** [comment]
This issue looks like it has been fixed @Jens-Co

**Comment by Jens-Co** [comment]
> This issue looks like it has been fixed @Jens-Co 

Thanks for getting back to me! Noted that.
