### ISSUE TITLE
Bedrock Users Can’t Ride Skeleton Horses

### ISSUE THREAD

**Issue by SoullessJewel6** [GeyserMC/Geyser#1663]
I saw a Skeleton Horse and I tried to ride it and I could t no then I killed all the skeletons that where near and I still could ride it and I went to the other ones and I couldn’t ride them either.

**Comment by RednedEpic** [comment]
Tested this last night and was unable to reproduce. Please follow the issue template and if this remains an issue, provide a video.

**Comment by SoullessJewel6** [comment]
How did u test or last night I put the comment up less then a minute ago?

**Comment by RednedEpic** [comment]
Another issue had been reported.

**Comment by SoullessJewel6** [comment]
Ok fair enough

**Comment by SoullessJewel6** [comment]
Hello again my friend I have now got video proof of my problem. @RednedEpic

**Comment by Camotoy** [comment]
Please post this video over at https://github.com/GeyserMC/Geyser/issues/1566 and provide a Geyser dump there.

**Comment by SoullessJewel6** [comment]
I can’t post videos for some reason
