### ISSUE TITLE
Bedrock book crafting issue

### ISSUE THREAD

**Issue by AceWolf2** [GeyserMC/Geyser#1664]
1.16.4 server with latest plugin 1.2.0 - SNAPSHOT (git-master-41cb593) running on Bedrock client 1.16.2 

Issue : when crafting using crafting book on bedrock client, item does not craft | crafting manually still works 
Example : crafting a crafting table out of 4 planks causes 4 planks to be spit out on the ground instead of ever crafting the crafting table 

you can recreate this by simply crafting any item using the crafting book

**Comment by RednedEpic** [comment]
Please follow the issue template.

**Comment by Camotoy** [comment]
Additionally, please make sure your issue has not already been reported. Thank you!
