### ISSUE TITLE
Add ability to bypass bedrock limitations

### ISSUE THREAD

**Issue by RedSmarty** [GeyserMC/Geyser#1666]
**What feature do you want?**
Add an way to bypass some bedrock limitations like right click in inventory, by making a floating bubble in Geyser-Android which can send a right click packet when clicked, and make geyser listen to those custom bedrock packets.

**Alternatives?**
Cant think of any other way.

**Comment by Camotoy** [comment]
Duplicate of #1332 (I'll clarify the name of that one). Thank you regardless for suggesting!
