### ISSUE TITLE
Armour Invisible/ Java Player Invisible

### ISSUE THREAD

**Issue by Jamidiot** [GeyserMC/Geyser#1669]
**Reproducing the problem**
1. Die at relatively the same time as the bedrock player
2. Respawn

**Expected behavior**
On the bedrock account it will look like the Java player is still wearing the armour or invisible.

**Screenshots / Videos**
I will get them

**Server Version**
This server is running CraftBukkit version git-Spigot-a19903d-5b74714 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-798ae34) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.56) with floodgate.

**Minecraft: Bedrock Edition Version**
1.16.210

**Additional Context**
https://dump.geysermc.org/N2CM0nXCofgEztx8FhSX9JlM60aE0l3s

**2nd issue**

**Reproducing the problem**
1. Die at relatively the same time as the bedrock player
2. Respawn

**Expected behavior**
On the bedrock account it will show the Java player as invisible and they won't be able to see them

**Screenshots / Videos**
I will get them

**Server Version**
This server is running CraftBukkit version git-Spigot-a19903d-5b74714 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-798ae34) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.56) with floodgate.

**Minecraft: Bedrock Edition Version**
1.16.210

**Additional Context**
https://dump.geysermc.org/N2CM0nXCofgEztx8FhSX9JlM60aE0l3s

**Comment by Camotoy** [comment]
I am closing on account of no other reports. If this issue still occurs, please let us know!
