### ISSUE TITLE
Remove NPCs from the Tab/Players List

### ISSUE THREAD

**Issue by Hipopotofobia** [GeyserMC/Geyser#167]
**What feature do you want?**
Remove NPCs from the Tab/Players list in the "pause" menu. 

**Alternatives?**
N/A

**Comment by bundabrg** [comment]
This may be possible with one or more of the following:

* Using only the PlayerSkin and AddPlayer packets and not using PlayerList Packet

* Using the PlayerList packet but removing it straight away

This just means we need a reliable way of determining which player entities are npc and handling it with the regular way that java sends its player lists out. My suspicion is that npc's may be marked as such through the use of a team or maybe the scoreboard but will require some further research.

**Comment by bundabrg** [comment]
This can be closed I believe. I fixed this long ago.
