### ISSUE TITLE
Smithing Tables, Grindstones don't work for Bedrock Players.

### ISSUE THREAD

**Issue by ExDrill** [GeyserMC/Geyser#1670]
For bedrock players on geyser, they are not allowed to access grindstones nor smithing tables, this is a huge for people wanting to get netherite armor or getting xp back from disenchanting.

**To Reproduce**
Install Spigot on a server.
Install FloodgateBukkit and GeyserSpigot
Access the server through a Bedrock Client
Get a grindstone and a smithing table
Try to access them

**Expected behavior**
You are supposed to access them and see the UI of the tile entity.

**Server Version**
1.16.4

**Geyser Version**
Geyser version 1.2.0-SNAPSHOT (git-master-41cb593)

**Minecraft: Bedrock Edition Version**
1.16.200

**Comment by Camotoy** [comment]
This is listed in our README as something we're working on. Thank you for reporting anyway!
