### ISSUE TITLE
Virtual Sign GUI

### ISSUE THREAD

**Issue by GoldenMyst** [GeyserMC/Geyser#1671]
**What feature do you want?**
A virtual sign gui for bedrock players.

**Alternatives?**
I dont know of any.

**Comment by Camotoy** [comment]
Could you please elaborate?

**Comment by GoldenMyst** [comment]
For example:
/withdraw: opens sign gui and put the amount of money to withdraw
![Uploading CA3D8083-B164-4AA9-911E-BFAAD7E47D96.png…]()

**Comment by GoldenMyst** [comment]
Like hypixel’s piggy bank deposit sign gui

**Comment by soshimee** [comment]
Why would you send an uploading image? They're useless, please wait for the upload to complete.

**Comment by GoldenMyst** [comment]
![6F353D15-C694-4F1A-B1FC-E3436D01BD97](https://user-images.githubusercontent.com/74118946/102157724-dce2ba80-3e34-11eb-8e80-23c20b923f17.png)

**Comment by YHDiamond** [comment]
is it not working on bedrock?

**Comment by Camotoy** [comment]
Bedrock cannot open a sign GUI without having placed a sign. Java can.

**Comment by YHDiamond** [comment]
Can we make it imitate them opening a sign, kinda like we did with chests?

**Comment by Camotoy** [comment]
That's doubtful. Bedrock's limitation is that it just needs a block location; there's still a packet to open a container. For signs, there is no packet to open a sign.

**Comment by YHDiamond** [comment]
so it is unfixable?

**Comment by Camotoy** [comment]
The alternative is probably sending a form GUI with four lines (though lines that are already on the sign might not transfer over.

**Comment by YHDiamond** [comment]
Also we'd need to set a char limit and stuff. I like that idea of the forms.

**Comment by YHDiamond** [comment]
time to spin up pakkit and look at what a sign packet looks like

**Comment by RednedEpic** [comment]
Thanks for the suggestion, unfortunately due to the limitations mentioned above, this is not something that would feasibly fit within Geyser. While forms would work as a potential solution, the ultimate result would be quite clunky with the form types currently available and would probably be more confusing than anything. Might work as an extension in the future, but for now I am going to close this. Thanks for the suggestion regardless!
