### ISSUE TITLE
Block glitching

### ISSUE THREAD

**Issue by qlow** [GeyserMC/Geyser#1673]
**Describe the bug**
You can build blocks in yourself as a bedrock player. This video describes it the best: https://www.youtube.com/watch?v=eXmyTVjdy8k

**To Reproduce**
Like in the video

**Expected behavior**
Just like in singleplayer and on other servers, you shouldn't be able to build blocks in yourself because you suffocate in them.

**Screenshots / Videos**
https://www.youtube.com/watch?v=eXmyTVjdy8k

**Server Version**
PaperSpigot 1.8

**Geyser Version**
Geyser 1.2.0 for BungeeCord

**Minecraft: Bedrock Edition Version**
1.16.200

**Additional Context**
I don't think a dump would help in this context.

**Comment by rtm516** [comment]
Please provide a dump, I'm unable to replicate this on the latest version.

**Comment by qlow** [comment]
> Please provide a dump, I'm unable to replicate this on the latest version.

https://dump.geysermc.org/qcMOL2rc4ZOyOibVlK3r0QeIHAUHgXYB

**Comment by rtm516** [comment]
My guess is its something in your custom fork as the config is set to what should work. Can you test with a normal Geyser build?

**Comment by qlow** [comment]
I already tested with normal Geyser and it is exactly the same.

**Comment by rtm516** [comment]
Does this only happen for bedrock players or can you check if it happens for Java 1.16.4 players? Also would you mind providing a server IP I can join to test at some point. (Feel free to send via Discord DMs)

**Comment by qlow** [comment]
> Does this only happen for bedrock players or can you check if it happens for Java 1.16.4 players? Also would you mind providing a server IP I can join to test at some point. (Feel free to send via Discord DMs)

Only happens for bedrock players

**Comment by qlow** [comment]
It actually does happen in 1.16, might be an issue with ViaVersion

**Comment by Camotoy** [comment]
See https://github.com/ViaVersion/ViaVersion/issues/1087 which I think is the error you're getting.
