### ISSUE TITLE
Players get stuck underneath Fence

### ISSUE THREAD

**Issue by HandyHat** [GeyserMC/Geyser#1675]
**Describe the bug**
While flying past a fence while a fence is on top of them, the player can get stuck underneath while going past the fence pole.

**To Reproduce**
1. Join server from Bedrock using Geyser
2. Build a fence post with a fence coming off the side
3. Position player so that their head is touching the bottom of the fence that is coming off the side
4. Try to walk past the fence pole while the player's head is touching the bottom of the fence
5. Observe player getting stuck underneath

**Expected behavior**
Player to not get stuck underneath

**Screenshots / Videos**
https://imgur.com/a/7mFJaPq

**Server Version**
`This server is running Paper version git-Paper-325 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)`

**Geyser Version**
Issue occurs on both build `525` of `master`: (`This server is running Geyser version 1.2.0-SNAPSHOT (git-master-799f634) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)`)
and on `Release v1.16-b48` from https://github.com/bundabrg/Geyser/tree/bleeding
Both were installed as Spigot Plugins.

**Minecraft: Bedrock Edition Version**
Issue occurs with both v1.16.200 of Minecraft: Windows 10 Edition and v1.16.200 of Minecraft (Android)

**Additional Context**
Issue could be reproduced on a Paper server running only the plugins Geyser and Floodgate.
https://dump.geysermc.org/vI7mR7zhf0sriGF1OfuiG7thasRlJGG0

**Comment by Jens-Co** [comment]
Hello @HandyHat, are you still having this problem? Otherwise I'll test it myself and close this issue within a few days after.
Jens

**Comment by HandyHat** [comment]
Hello there, I can still reproduce this problem running `Paper version git-Paper-119 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f25facb)` and `Geyser version 1.4.1-SNAPSHOT (git-inject-78cf6b4) (Java: 1.17.1, Bedrock: 1.17.10)`

I turned on debug mode in the config and this shows up when the issue occurs:

```
[Network Listener - #1/INFO]: [Geyser-Spigot] Confirmed teleport 2
[Thread-61/INFO]: [Geyser-Spigot] Teleport from -106.075 65.99802 -223.20105
[Thread-61/INFO]: [Geyser-Spigot] to -106.02697 65.99802 -223.1422
[Network Listener - #1/INFO]: [Geyser-Spigot] Confirmed teleport 3
[Thread-61/INFO]: [Geyser-Spigot] Teleport from -106.075 65.99802 -223.20105
[Thread-61/INFO]: [Geyser-Spigot] to -106.02697 65.99802 -223.1422
[Network Listener - #1/INFO]: [Geyser-Spigot] Confirmed teleport 4
[Thread-61/INFO]: [Geyser-Spigot] Teleport from -106.075 65.99802 -223.20105
[Thread-61/INFO]: [Geyser-Spigot] to -106.02697 65.99802 -223.1422
[Network Listener - #1/INFO]: [Geyser-Spigot] Confirmed teleport 5
[Thread-61/INFO]: [Geyser-Spigot] Teleport from -106.075 65.99802 -223.20105
[Thread-61/INFO]: [Geyser-Spigot] to -106.02697 65.99802 -223.1422

**Comment by Jens-Co** [comment]
Thanks for that info I'll do some testing on this!

**Comment by RednedEpic** [comment]
Not seen anything on this lately - closing due to lack of response.
