### ISSUE TITLE
PS4 players getting "Timed out"

### ISSUE THREAD

**Issue by rhld16** [GeyserMC/Geyser#1676]
**Describe the bug**

I can join normally using iOS and Windows 10 (with Geyser) and Mac (no Geyser). But when I join with PS4 (dnsmasq server with galaxite pointing to geyser server) I can join and interact for some time but after around 10-30 seconds I get disconnected with "Timed out"
**To Reproduce**

1. Join with PS4
2. Play around for a bit
3. Get disconnected

**Expected behavior**

Like the other devices, staying in the game.
**Screenshots / Videos**

https://imgur.com/a/dqy5uMM
**Server Version**

Tuinity git-8056d13 1.16.4
**Geyser Version**

1.2.0-SNAPSHOT (git-master-41cb593)
**Minecraft: Bedrock Edition Version**

1.16.200
**Additional Context**

Dump: https://dump.geysermc.org/THOqBoEaFoPzo4PlKYbMiH6ps8p0OQag
Sorry I understand this is a harder bug to confirm I'll add screenshots soon.

**Comment by Camotoy** [comment]
Unfortunately no one on the core development has easy access to a PS4 so this is going to be a trickier one.

Does it only happen on your server? Can you try pointing to `test.geysermc.org`? (the build on that server might be a bit outdated at the moment)

**Comment by Camotoy** [comment]
Also - can we get a list of plugins on the server? Does it happen with Paper/Spigot? Are you able to temporarily try *vanilla*?

**Comment by rhld16** [comment]
I don’t have personally have a PS4 either but just had my friend join the test server and he still got disconnect still with “Timed out”. No plugins on my server

**Comment by Camotoy** [comment]
We run Paper, for reference.

Does `pe.mineteria.com` work for them? That's a server that definitely does not run Geyser.

**Comment by rhld16** [comment]
He's confirmed that he was in the server without issues at all. I understand that you can't really test this yourself so don't worry too much if you can't help.

**Comment by Camotoy** [comment]
It's still something I'd like to fix - bugs like these are annoying for you because, whereas most other bugs don't prevent you from playing on the server at all, these prevent you from playing on the server through any capacity.

**Comment by rhld16** [comment]
Okay thank you so much, if you need any info I'll try relay it to my friend

**Comment by Camotoy** [comment]
Can you try https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/506/ ? That's the oldest build we have that works with 1.16.200. It will work if you don't have a resource pack supplied by Bedrock.

**Comment by rhld16** [comment]
It worked. Won't be able to test other versions tonight (GMT time zone) but if you want us to test other versions I'll carry on switch builds

**Comment by Camotoy** [comment]
Yes, please! Keep trying newer builds until you identify where it breaks. If I had to guess, you're going to break at 511.

**Comment by rhld16** [comment]
Thank you so much for fixing this so fast I don’t know how you could’ve worked that out

**Comment by Camotoy** [comment]
All thanks go to Notnotnotswipez on the Discord. They painstakingly kept connecting to a test Geyser instance until I was able to narrow down the issue. ^^
