### ISSUE TITLE
Head Support

### ISSUE THREAD

**Issue by MetallicGoat** [GeyserMC/Geyser#1679]
**What feature do you want?**
Support for plugins like Head Database. For example if you take a head that looks like a hamburger and put in a chest, java players can see the hamburger, but bedrock players just see a Steve head. If a 'colored' head is placed on the ground however, both bedrock and java can see the head is a hamburger.

**Comment by Camotoy** [comment]
Unfortunately at this time, this is a Bedrock limitation. We can't easily texture heads in the inventory. In the future there *might* be a way to selectively choose which heads are textured, but in general there's not much we can do to support all heads.
