### ISSUE TITLE
Textures aren't loading

### ISSUE THREAD

**Issue by Kili2108** [GeyserMC/Geyser#168]
Every Time I try to connect from my MCPE to my Minecraft Java Server, i can connect, but the textures aren't loading

1. Connect to the Server
2. Login with Minecraft Username and Password

I'm running the Minecraft Java Server Version 1.15.2

I'm running the latest version of Geyser

Bedrock Version is 1.14.30

Can somebody please help me?

**Comment by RednedEpic** [comment]
I assume you mean chunks or blocks not loading in?

**Comment by Nixuge** [comment]
I've got the same issue,  sometimes the textures are just invisible (even tho you can still interact with the terrain) but usually relogging fix the problem

**Comment by Kili2108** [comment]
> I assume you mean chunks or blocks not loading in?

First, Thank you for replying

Yes, chunks and blocks are not loading.

I mad a screenshot where you can see it.

It can’t be my MCPE or Geyser, because installed both new
![9E34F933-5732-408D-99E1-A5030323DC35](https://user-images.githubusercontent.com/61068014/74575774-8c869c00-4f88-11ea-9d88-9a110bbe577b.png)

**Comment by RednedEpic** [comment]
Try [this build](https://github.com/GeyserMC/Geyser/suites/452066593/artifacts/1772457) and see if you have any luck with it.

**Comment by RednedEpic** [comment]
If the above link isn't working, hop on Discord and I'll send you a jar.

**Comment by Kili2108** [comment]
The link was working and I installed it, but sadly i have the same result as before.
![58F57926-0002-4027-975E-C7111FF55901](https://user-images.githubusercontent.com/61068014/74576549-a07fcd00-4f8b-11ea-8c06-a4174a3c5199.png)

**Comment by RednedEpic** [comment]
> The link was working and I installed it, but sadly i have the same result as before.

Could you tell us what OS you're running Geyser on (as well as computer specs) and how much RAM/resources you've allocated towards Geyser? One thing we have noticed off and on is sometimes chunks won't load due to Geyser not having near enough resources (mainly on Termux environments).

**Comment by Kili2108** [comment]
Geyser is running on the newest Raspbian Buster on a Raspberry Pi 3b+ and I gave Geyser like in the Tutorial 512M

**Comment by RednedEpic** [comment]
This could be related to #124. Try giving Geyser more RAM and see what happens.

**Comment by jackson-57** [comment]
I'd like to add that I was having the same issues running Geyser on termux (snapdragon 835, 4gb ram, 512m allocated). I have yet to try the build that Redned linked.

**Comment by RednedEpic** [comment]
Here is that build for anyone else: https://cdn.discordapp.com/attachments/650675635282509845/676926714307412016/Geyser-chunktest-4.jar

**Comment by Kili2108** [comment]
More RAM worked for me.
Thank You!
