### ISSUE TITLE
Horse spam in console

### ISSUE THREAD

**Issue by supertakeru** [GeyserMC/Geyser#1682]
**Describe the bug**
BEDROCK PLAYER JOIN SERVER USING FLOODGATE+GEYSER-SPIGOT, RIDE HORSE, CONSOLE GETS SPAMMED

**To Reproduce**
Bedrock player join Java server using Floodgate+Geyser-spigot
Rides horse
Console gets spammed

**Expected behavior**
No console spam when bedrock player ride horse

**Screenshots / Videos**
https://pastebin.com/Skgtm7s0

**Server Version**
Paper 1.16.4 325

**Geyser Version**
USING FLOODGATE
GEYSER 1.2.0 SNAPSHOT 41cb593

**Minecraft: Bedrock Edition Version**
1.16.200 MCPE

**Additional Context**
https://dump.geysermc.org/UlaL7YIOrZyaJ9AjQEh4eRxAbhvDKqvz

**Comment by Kooldude183** [comment]
Just increase the moved-too-quickly-threshold value in spigot.yml

**Comment by Adogs1** [comment]
> 只需增加 spigot.yml 中的移动过快阈值即可

There are also such errors on the fabric, but there is no configuration file that moves too fast a threshold. Therefore, it is a common error on all servers.

**Comment by Adogs1** [comment]
> Fabric 是一个单独的问题，您甚至可以通过普通传送获得该消息:p您可以使用例如 https://modrinth.com/mod/gotta-go-fast-fabric 来消除这些错误。

But it is undeniable that almost all servers experience this error
