### ISSUE TITLE
(Bedrock) Change the 1.9 cooldown title command to an actionbar.

### ISSUE THREAD

**Issue by ExDrill** [GeyserMC/Geyser#1685]
So on the bedrock side of geyser, when you enter a server with 1.9+ combat, a little title command will pop up showing when to attack. I suggest to change the title command to an actionbar for better visibility.

Maybe some sort of alternative could be for it to be an option with a command to switch between the two.

**Comment by rtm516** [comment]
Please follow the feature request template. And the title bar is placed where it is currently as that's the closest to Java.

**Comment by ExDrill** [comment]
> Please follow the feature request template. And the title bar is placed where it is currently as that's the closest to Java.

Java has a option that makes the cooldown thing down to the hotbar.
