### ISSUE TITLE
Natural healing flags for fastheal on NCP

### ISSUE THREAD

**Issue by lifegame1lu111** [GeyserMC/Geyser#1689]
**Describe the bug**
each time you heal 0.5 hp you get flagged on the FIGHT_FASTHEAL check

**To Reproduce**
1- Go on a server with the latest version of NCP
2- take damage
3- then let your character heal

**Expected behavior**
Healing normally and not being flagged
**Screenshots / Videos**

**Server Version**
Any, NCP version: 
NoCheatPlus 3.16.0-RC-sMD5NET-b1134
**Geyser Version**
Standalone git-master-55cf7d1

**Minecraft: Bedrock Edition Version**
1.16.201
**Additional Context**

Geyser dump: https://dump.geysermc.org/plesIT26J5af57NnpzKQbeo7sgOvLoXY

**Comment by nickg2** [comment]
I personally use NCP, but I modify the config to make it very fine tuned, and this has never happened to me. If you want my config. just msg me on discord: NickTheNerd#5835

**Comment by lifegame1lu111** [comment]
the server im testing on is not mine, its using default configs, but thx anyways xd

**Comment by Konicai** [comment]
Anticheat plugins generally require tuning to support Geyser players. Unfortunately if you're using Geyser Standalone on a server without intent of supporting Bedrock players themselves, there's not much you can do. Closing this as it can be resolved by tuning anticheat configs, and Geyser is continuously working to make Bedrock players have better parity
