### ISSUE TITLE
Bedrock players with plug-ins similar to the online skin display in offline servers will be kicked out

### ISSUE THREAD

**Issue by linmiao233** [GeyserMC/Geyser#169]
**Describe the bug**
Bedrock players with plug-ins similar to the online skin display in offline servers will be kicked out

**To Reproduce**
1. Server is set offline
2. Install the online skin display plugin example: Myskin SkinsRestorer 
3. Bedrock players enter the server
4. Player is kicked out,See error

**Expected behavior**
Players should not be kicked out

**Screenshots**
![image](https://s2.ax1x.com/2020/02/15/1x9MlQ.png?raw=true)

**Server version**
1.8.8

**Geyser version**
Jenkins latest

**Bedrock version**
1.14.30

**Comment by RednedEpic** [comment]
The error you sent does not seem to quite correlate with the issue of skins. More than likely this is a broader issue, so let us know if you run into this issue by doing other things.

**Comment by Loganh4005** [comment]
Hi i think i have an idea of why this happens, It tries to fetch the skin of the player (in bedrock) in the minecraft (java) database, which is non-existent, so because it can't find it it just crashes.

**Comment by Mhowser** [comment]
it should just load the default steve/alex skin then right?

**Comment by RednedEpic** [comment]
> it should just load the default steve/alex skin then right?

Yes it should. If it fails to find the skin, it auto-uses the Steve skin.

**Comment by Mhowser** [comment]
ah, ok. Can OP produce console logs by any chance?

**Comment by Loganh4005** [comment]
Maybe it crashes trying to load the skins for java players?

**Comment by chenxi050402** [comment]
I use skinrestorer and geyser having no problems (except the skin not showing u need to customize it client side)
Also I'm Chinese too

**Comment by RednedEpic** [comment]
Unable to reproduce and has not been reported at all since. If I had to guess, it seems more like a plugin issue since vanilla does not send this.
