### ISSUE TITLE
Issue with gamemode

### ISSUE THREAD

**Issue by NunoHiggs** [GeyserMC/Geyser#1693]
**Issue**

The gamemode on a bedrock client is set by default to survival, although the server is set to creative, and i am not able to change.

**To Reproduce**
Login with a bedrock client, on this case IOS client on a private server. The mode that the client sees is survival.
If i login with a java client, same world, same server, and it's sees creative mode as enabled.
Also i cannot change mode on the bedrock client.

**Expected behavior**
Bedrock client to remain on the default of the server that is creative mode.

**Server Version**
Paper version git-Paper-325 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
Geyser version 1.2.0-SNAPSHOT (git-master-988fd66)

**Minecraft: Bedrock Edition Version**
IOS Client 1.16.201

**Comment by Camotoy** [comment]
Please provide a Geyser dump.

**Comment by Heath123** [comment]
Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

If you use the Geyser Standalone GUI then it is inside the `Commands` menu as seen below.
[GUI](https://images-ext-2.discordapp.net/external/0rwfZ7Xh3uRMjPZFxbJKtBAo8YIrOymN702eeVHUSKc/https/media.discordapp.net/attachments/774372288061243482/776957132465373184/97361099-751ce400-1875-11eb-84b5-2945d840dfff.png)

**Comment by NunoHiggs** [comment]
https://dump.geysermc.org/6BGxkdbrbsu0nKqOG4x4BjrQuH4sNwyb

**Comment by Camotoy** [comment]
@NunoHiggs does this still persist? Have you tried downloading a newer build?

**Comment by Chew** [comment]
The author didn't reply for 3 months :(. If you happen to reproduce this on the latest build please let us know and we'll be happy to re-open this issue. As always, thank you for the report!
