### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by SrMoohs** [GeyserMC/Geyser#1699]
hello, well there is a simple coordinate bug, when you disable the geyser r coordinates you teleport to another world the coordinates appear again

CLIP: https://youtu.be/3CGd6Y-A570

GEYSER VERSION:  Geyser version 1.2.0-SNAPSHOT (git-master-988fd66) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)
GEYSER BUNGEECORD: Geyser version 1.2.0-SNAPSHOT (git-master-988fd66) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)
SPIGOT VERSION: CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
plugins being used on spigot: ViaVersion
MINECRAFT PE: 1.16.200

**Comment by RednedEpic** [comment]
For the third time, please submit an issue _with_ the template filled out. Submitting an empty template then proceeding to open another issue without following it is "not filling in the template".
