### ISSUE TITLE
Unable to auto craft on console

### ISSUE THREAD

**Issue by AkanshDivker** [GeyserMC/Geyser#1704]
**Describe the bug**

For my console players, they are unable to craft using any recipes it seems. If they use a recipe and attempt to craft, the items just get returned back without being crafted. Crafting seems to only work by manually placing each item. On console this can be a pretty tedious task. 

"Basically I can’t auto craft and when I try, it says I did but it’s not in my inventory and throws the resources on the ground so if I want to make something I have to but the resources in individually like 2 sticks and 3 stone of that makes sense"

The user who reported this on my server is playing on Xbox.

**To Reproduce**

1. Connect to server
2. Attempt to craft an item using recipe
3. Press button to craft
4. Items should be returned without new item being crafted

**Expected behavior**

A crafted item should be returned instead of the ingredients being returned.

**Screenshots / Videos**

Unavailable.

**Server Version**

Paper 1.16.4

**Geyser Version**

[Build #536](https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/536/)

**Minecraft: Bedrock Edition Version**

1.16.201

**Additional Context**

There are no other plugins running on my server, just Floodgate.

**Comment by Camotoy** [comment]
Thank you for writing a detailed issue report!

Due to the similarities of the issue (and what I believe is the same problem, just regressed on 1.16.200), I'm going to consolidate this with #1192. Thank you again for reporting!
