### ISSUE TITLE
Show the owner of the skull in another way

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Geyser#1707]
**What feature do you want?**
Add a line of Lore to display the name of the skull owner

**Alternatives?**
Lore?

**Comment by Camotoy** [comment]
For what reason would you want this? I personally don't see a practical reason for this - we handle skull owner names the exact same way vanilla Java does.

**Comment by zimzaza4** [comment]
During the production of the skull branch, you replaced the name of the skull to show the owner

**Comment by zimzaza4** [comment]
If you add a line of Lore, there is no need to replace the item name

**Comment by Camotoy** [comment]
> you replaced the name of the skull to show the owner

Yes, in order to replicate vanilla behavior. This shouldn't happen if the skull item is renamed (and, if so, this is a bug).

**Comment by Camotoy** [comment]
I'm closing this - the requested feature isn't something that, to my knowledge, exists as an equal in Java Edition, and it would clutter up the config with an extra option I don't see being necessary. If you disagree with this, please do feel free to comment.
