### ISSUE TITLE
Item frames with maps not always loading when joining server

### ISSUE THREAD

**Issue by hokudan** [GeyserMC/Geyser#1709]
**Describe the bug**
When I join a server, the maps that I have placed into item frames do not always load completely. I have 10-15 item frames grouped together on a wall, some with maps, some without. I have to leave an rejoin the server 3-4 times for all of the frames to show.

**To Reproduce**
1. create a wall with 15 item frames
2. fill each item frame with an item- in my case I used map segments
3. leave the server and quit Minecraft
4. relaunch minecraft
5. rejoin server

**Expected behavior**
All item frames with their map segments to display

**Screenshots / Videos**

**Server Version**
This server is running Paper version git-Paper-313 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
 [Geyser-Spigot] Loading Geyser version 1.2.0-SNAPSHOT (git-master-91cdda9)

**Minecraft: Bedrock Edition Version**
1.16.201

**Additional Context**
https://dump.geysermc.org/F8HPS6cBIMpNsnsQgC0mX2iyyNxkQYoO
viaversion, viarewind, viabackwards, worldborder, customwelcomemessage, floodgate, geyser/spigot

**Comment by hokudan** [comment]
![2nd join](https://user-images.githubusercontent.com/76224478/102647601-d9904d00-411a-11eb-9474-529135cf34b5.png)
![first join](https://user-images.githubusercontent.com/76224478/102647603-da28e380-411a-11eb-9450-ec1025d40fd3.png)

**Comment by hokudan** [comment]
Posted screenshots of another instance from frames on the floor

**Comment by MrZomka** [comment]
Try updating Geyser and Paper.

**Comment by hokudan** [comment]
Just updated both and got the same result.

**Comment by Camotoy** [comment]
Closing as this has not been reported recently. If you believe this is in error, do let us know!
