### ISSUE TITLE
Black Box Appears When Selecting Hotbar Inventory

### ISSUE THREAD

**Issue by Brooksd91** [GeyserMC/Geyser#1710]
**Describe the bug**
 From mobile when I click the hot bar inventory selections a double black opaque box appears for about 1 second and then goes away as if to show the name of the item in the actions. Its preceded by a millisecond load gui. It goes away too fast to screen shot the load part, but the double black boxes stay for a moment.  This issue is not recreated for bedrock joining on pc or java users in the server. 

**To Reproduce**
 Open minecraft mobile
Load the server, 
Click any hot bar inventory selection
change selections to see it again.
 Black boxes show up then go away

**Expected behavior**
Normally you might see the name of the selected item or maybe the enchants it could have or item variables. 

**Screenshots / Videos**
here is a video screen record and a screenshot. [Video](https://youtu.be/P0fhhwlGM6M)

Screenshot
![20201217_135704](https://user-images.githubusercontent.com/76223498/102647290-1d8b4e00-412b-11eb-8268-5ed0c54b33eb.jpg)

**Server Version**
 Spigot 1.16.4

**Geyser Version**
We are using floodgate and our version of geysers is build #536 of Geyser-Spigot

**Minecraft: Bedrock Edition Version**
 Minecraft Bedrock 1.16.201

**Additional Context**
 I am using apex hosting and they have checked the entire server for issues and disabled the plugins that are not needed to run the server. They have suggested that I
 send my report here;.

**Comment by Camotoy** [comment]
Please provide a Geyser dump. (`/geyser dump`)

**Comment by Brooksd91** [comment]
Here is the dump. https://dump.geysermc.org/ksnWfPIGnuYrDHiWxP9Llf9UqGF8WxaO

**Comment by Camotoy** [comment]
Unable to replicate.

- What device are you running Bedrock from?
- If you disable `show-cooldown` in your config, does it disappear?

**Comment by zimzaza4** [comment]
There is a solution

**Comment by zimzaza4** [comment]
There is a solution

**Comment by zimzaza4** [comment]
![Screenshot_20201219_071912_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/102671596-9392c200-41ca-11eb-850b-5747f5a72777.jpg)
You can adjust it in the client settings

**Comment by Brooksd91** [comment]
> Unable to replicate.
> 
> * What device are you running Bedrock from?
> * If you disable `show-cooldown` in your config, does it disappear?

Running on Samsung galaxy s5e tablet

**Comment by Chew** [comment]
Glad to hear! Thank you for your report :)

**Comment by Camotoy** [comment]
I'm reopening this since... it shouldn't happen. It might be a Bedrock bug though.

**Comment by notnotnotswipez** [comment]
@Brooksd91 A reinstall of your game should fix your problem completely, its a texture corruption error that happens sometimes. If it doesnt fix your issue, back up your world files and delete your save data (wherever that may be stored).

**Comment by zimzaza4** [comment]
lt should be able to be modified in the client settings. .

**Comment by Hellohi3654** [comment]
> ![Screenshot_20201219_071912_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/102671596-9392c200-41ca-11eb-850b-5747f5a72777.jpg)
> You can adjust it in the client settings

Doing that ^ seems to fix the issue

**Comment by notnotnotswipez** [comment]
The fake cooldown that Geyser displays would still most likely show the black box even with the opacity set to 0%, that or they wont be able to use the cooldown feature

**Comment by zimzaza4** [comment]
> The fake cooldown that Geyser displays would still most likely show the black box even with the opacity set to 0%, that or they wont be able to use the cooldown feature.
> 
> EDIT: This affects any titles that are displayed to the player, not just in Geyser or the cooldown exclusively

This may be a client bug.
It may be solved if you set it to 100%

**Comment by notnotnotswipez** [comment]
> > The fake cooldown that Geyser displays would still most likely show the black box even with the opacity set to 0%, that or they wont be able to use the cooldown feature.
> > EDIT: This affects any titles that are displayed to the player, not just in Geyser or the cooldown exclusively
> 
> This may be a client bug.
> It may be solved if you set it to 100%

Yes, this is a Bedrock texture corruption

**Comment by MrRazamataz** [comment]
Some players reinstalled the game and it still happens.

**Comment by MrRazamataz** [comment]
Setting Text Background Opacity to 0 is a fix for this.

**Comment by nickg2** [comment]
+1 for this is happening to me, some players get the black box of death on floodgate 2.0 geyser latest version. seems the only fix is settings Text Background Opacity to 0 is the only fix.

**Comment by Column01** [comment]
Can confirm it's still an issue with the latest geyser and floodgate. I disabled the cooldown thing for now, but it would be nice to have it work

**Comment by zimzaza4** [comment]
I think this should be added to Common Issues

**Comment by Camotoy** [comment]
With thanks to 7man7LMYT I was alerted to the fact that the text opacity setting was indeed off this whole time.

**Comment by Camotoy** [comment]
As of the latest CI build (1063), fake cooldown is... better. The black box at the top will still appear, but it will disappear as soon as the cooldown is done. This is probably the best we can do; instead, we should start working on documentation addressing why the fake cooldown acts the way it does and how to address it.

**Comment by Camotoy** [comment]
As far as I know, this issue still exists and there isn't much we can do about it. We've mitigated it the best we can, and I've just updated our config explaining the issue.
