### ISSUE TITLE
disconnected with: You are sending too many packets, :(

### ISSUE THREAD

**Issue by MeowedAt** [GeyserMC/Geyser#1714]
**Describe the bug**

When Bedrock players attempt to connect, they get sent the the world "world" and then to spawn. After that the client crashes.

```
10:36:07 [INFO] [Geyser-BungeeCord] /xx.xx.xxx.xxx:49658 tried to connect!
10:36:10 [INFO] [Geyser-BungeeCord] Player connected with username TTVepicninja749
10:36:21 [INFO] [Geyser-BungeeCord] Attempting to login using floodgate mode... authentication will be encrypted.
10:36:21 [INFO] [Geyser-BungeeCord] Loaded Floodgate key!
10:36:21 [INFO] [Geyser-BungeeCord] TTVepicninja749 (logged in as: TTVepicninja749) has connected to remote java server on address 172.18.0.3
10:36:22 [INFO] [/172.18.0.3:50516] <-> InitialHandler has connected
10:36:23 [INFO] [*TTVepicninja749] <-> ServerConnector [skyblock] has connected
10:36:23 [INFO] [Geyser-BungeeCord] Registering bedrock skin for *TTVepicninja749 (00000000-0000-0000-0009-01f9be73c683)
10:36:33 [INFO] [Geyser-BungeeCord] Spawned player at 112.5 53 171.5
10:36:35 [INFO] [Geyser-BungeeCord] Spawned player at 41.5 4 245.5
10:36:46 [INFO] [/80.2.39.251:52859] <-> InitialHandler has pinged
10:36:46 [WARNING] [Geyser-BungeeCord] Downstream packet error! com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
10:36:55 [INFO] [*TTVepicninja749] disconnected with: You are sending too many packets, :(
```

**To Reproduce**
Join the server on a Bedrock client with default settings on Geyser (bungeecord)

**Expected behavior**
Player joins in world "spawn"

**Screenshots / Videos**
N/A

**Server Version**
Skyblock: [10:46:06 INFO]: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[10:46:06 INFO]: You are running the latest version
Viaversion works with latest 1.16.4

**Geyser Version**
10:48:07 [INFO] This server is running Geyser version 1.2.0-SNAPSHOT (git-master-c921500) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)
10:48:07 [INFO] Checking version, please wait...
10:48:07 [INFO] No updates available.

**Minecraft: Bedrock Edition Version**
I don't know but there are no available updates.

**Additional Context**
 https://dump.geysermc.org/TqG5capxG1ivBF3hpKFErslCB2VFrlnm

**Comment by rtm516** [comment]
This is caused by ViaVersions `max-pps` option, please increase this or disable it. For future please use Discord for these sorts of issues.
