### ISSUE TITLE
Invisible armore stands are visible for pocket players.

### ISSUE THREAD

**Issue by baxandrei** [GeyserMC/Geyser#172]
**Describe the bug**
We use on the server a plugin called HolographicDisplay that adds holograms into the game using invisible armor stands that are apparently visible to mobile players.

**To Reproduce**
Use a server that uses this plugin.

**Expected behavior**
To be invisible.

**Screenshots**
MC:PE (Bedrock): 
![image](https://user-images.githubusercontent.com/12484505/74589666-cf3f8700-500f-11ea-90b0-c4358dcb2af6.png)
JAVA: 
![image](https://user-images.githubusercontent.com/12484505/74589761-d2874280-5010-11ea-8dbf-4b20b0bbea40.png)

**Server version**
This server is running Paper version git-Paper-71 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser version**
https://ci.nukkitx.com/job/Geyser/job/master/171/

**Bedrock version**
1.14.30

**Additional context**
Sometimes, if the player is spawned far from holograms, they will not be generated at all.

**Comment by Nixuge** [comment]
[#137](https://github.com/GeyserMC/Geyser/issues/137)

**Comment by baxandrei** [comment]
From what I notice the fix was made about 20 days ago, and the version of Geyser I use is 5 days ago, which is why I did the ticket, because the problem is still there.

**Comment by RednedEpic** [comment]
> From what I notice the fix was made about 20 days ago, and the version of Geyser I use is 5 days ago, which is why I did the ticket, because the problem is still there.

That fix is what made armor stand names visible in the first place. Previously, you could see the armor stand in this instance but not the name.
