### ISSUE TITLE
Disabled Xbox Live authentification

### ISSUE THREAD

**Issue by TheBlackfurGuy** [GeyserMC/Geyser#1721]
Feature Request:
I think it would be useful to add a option to config.yml that disables Xbox Live Auth as not everyone can or want's to create a Xbox Live account as on some platforms it costs money.

**To Reproduce**
1. Install PaperMC/Spigot/Bukkit
2. Install GeyserMC
3. Set "online-mode" to false in server.properties
4. Set "auth-mode" to offline in plugins/Geyser-Spigot/config.yml
5. Try join the Server with a Bedrock Client not logged into Xbox Live

**Expected behavior**
Client should be able to join.

**Server Version**
- git-Paper-338

**Geyser Version**
- git-master-dbfdae6
- Plugin Version
- No Floodgate

**Minecraft: Bedrock Edition Version**
- v1.16.201

**Additional Context**
No other Plugins

**Comment by Camotoy** [comment]
> as on some platforms it costs money

You said this is the case on Xbox One, but I cannot confirm this. I was able to create an Xbox account *on my Xbox One* for absolutely free. Additionally, there isn't a way to play Minecraft without logging in on Xbox (this is why you lose your worlds if you get banned on Xbox)

**Comment by HelveticaToast** [comment]
It's free to create an Xbox Account, but in Xbox, you are required to have an Xbox Live Gold subscription.
