### ISSUE TITLE
Armour disappearing visually randomly

### ISSUE THREAD

**Issue by Topnitel** [GeyserMC/Geyser#1722]
**Describe the bug**
Any type of armour just randomly disappear out of nowhere, especially boots
They only disappear visually, all protection and enchantments still affect the player
They reappear if you put another piece of armour, or again, sometimes randomly

**To Reproduce**
I... actually have no idea

**Expected behavior**
The armour pieces do not disappear randomly and stay there

**Screenshots / Videos**
I would love to take a screenshot or video but the bug is pretty rare and I never had the opportunity to do it

**Server Version**
This server is running Paper version git-Paper-338 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-c921500) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)

**Minecraft: Bedrock Edition Version**
Both 1.16.200 (PC) and 1.16.201 (iPhone)

**Additional Context**
https://dump.geysermc.org/0JMv0JfSSt4mTFKfjuDkEZ65ZkdYmZBR

**Comment by ShyloFluff** [comment]
I can confirm this, It reappears back on its own after a while. A simple quick fix for this is to put on another piece of armor on the slots where the armor has went invisible. The armor will reappear.

**Comment by Camotoy** [comment]
Are there consistent replication steps for this?

**Comment by Topnitel** [comment]
> Are there consistent replication steps for this?

No, it seems to happen when I literally do anything.
Currently discovered: eating, equipping armour, using elytra

**Comment by Camotoy** [comment]
My pants have disappeared.

oh no

**Comment by Topnitel** [comment]
this comment caught me off guard because i got the email about it just now

**Comment by Camotoy** [comment]
It's been a solid year since this has been reported and it hasn't been reported since. It's safe to say the pants are safely visible. Thanks.

**Comment by Sys-h-sudo** [comment]
Reopened cause same issue is reappearing.
