### ISSUE TITLE
Player hitbox is 2 blocks tall when swimming (and possibly while flying with elytra)

### ISSUE THREAD

**Issue by Topnitel** [GeyserMC/Geyser#1724]
**Describe the bug**
While swimming, the player hitbox does not change, making swimming through 1 block gaps impossible

**To Reproduce**
1. Go swimming
2. Get a one block tall gap
3. Unable to get through it

**Expected behavior**
Able to swim through 1 block tall gaps

**Screenshots / Videos**
Will get soon, I'm actually able to record this

**Server Version**
This server is running Paper version git-Paper-338 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-c921500) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)

**Minecraft: Bedrock Edition Version**
Both 1.16.200 (PC) and 1.16.201 (iPhone)

**Additional Context**
https://dump.geysermc.org/0JMv0JfSSt4mTFKfjuDkEZ65ZkdYmZBR

btw im copy and pasting the last part yes

**Comment by Hellohi3654** [comment]
This is a known issue and is yet to be implemented into Geyser
Thanks for the reminder though
