### ISSUE TITLE
Shield might be activated but doesn't function

### ISSUE THREAD

**Issue by Topnitel** [GeyserMC/Geyser#1725]
**Describe the bug**
Shield can activate but sometimes it doesn't function and doesn't block damage

**To Reproduce**
1. Get a shield
2. Use it multiple times
3. Small chance of it not functioning

**Expected behavior**
The shield is always functional (except if disabled by axe) while sneaking

**Screenshots / Videos**
This is quite rare, didn't get any screenshots or videos

**Server Version**
This server is running Paper version git-Paper-338 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-c921500) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)

**Minecraft: Bedrock Edition Version**
Both 1.16.200 (PC) and 1.16.201 (iPhone)

**Additional Context**
https://dump.geysermc.org/0JMv0JfSSt4mTFKfjuDkEZ65ZkdYmZBR

**Comment by Topnitel** [comment]
i'm done for now here

**Comment by timof121** [comment]
Same

**Comment by Chew** [comment]
There have been some changes to shields since this issue that should help with this, so we're going to go ahead and close this. If you happen to run into any new issues, please feel free to make a new issue. As always, thank you for the report!
