### ISSUE TITLE
Java to bedrock texterpack support

### ISSUE THREAD

**Issue by Creeperz653** [GeyserMC/Geyser#1726]
**What feature do you want?**
so there needs to be support for java texterpacks to bedrock even if they cant do that can they at lest add a area where i can put my bedrock texterpack  because i have no problem remaking the texter pack for bedrock <my texterpack adds custom music disks
**Alternatives?**
none

**Comment by Creeperz653** [comment]
**e**

**Comment by Camotoy** [comment]
Duplicate of #210. Thank you for reporting regardless!

**Comment by EasyClifton** [comment]
This functionality already exists. You can put bedrock resource packs into the `packs` folder in the Geyser folder and they will be sent to bedrock players on join. Also, please ask these sorts of questions on our [Discord](https://discord.geysermc.org) server.

**Comment by Creeperz653** [comment]
ohhhh i didnt know

**Comment by ByteMyRaspberryPi** [comment]
Do I have to manually convert a Java resource pack to a bedrock resource pack with an online tool and then place it in this folder?
