### ISSUE TITLE
Issue with icons above holograms

### ISSUE THREAD

**Issue by bobhenl** [GeyserMC/Geyser#1734]
**Describe the bug**

Hi, when I have on my server CMI and there are icons above holograms (created with /cmi hologram new, and then used ICON:XXX there, it creates icon. But in normal Minecraft java edition icon is above text holograms (yea, we can move it, but in this case it's really above texts, and it falled down under the text from some reason...)
https://github.com/Zrips/CMI/issues/4807 Reported to CMI github too

**To Reproduce**

1. Create hologram with /cmi hologram new <xxx>
2. Then use /hologram edit <xxx> and click on + and put there ICON:XXX above all lines
![image](https://user-images.githubusercontent.com/18662086/103138412-b04f5e00-46d2-11eb-8c88-35de775d06aa.png)
3. Put some text there.
4. You should see it like this:
![image](https://user-images.githubusercontent.com/18662086/103138415-c0673d80-46d2-11eb-864a-ca8498c2244c.png)
But on Bedrock you see it like this:
![image](https://user-images.githubusercontent.com/18662086/103138424-cfe68680-46d2-11eb-9585-05d0147326b6.png)

**Expected behavior**

Icon should be above text like in Java edition
![image](https://user-images.githubusercontent.com/18662086/103138415-c0673d80-46d2-11eb-864a-ca8498c2244c.png)

**Screenshots / Videos**

Screenshots are used above.

**Server Version**

![image](https://user-images.githubusercontent.com/18662086/103138431-dffe6600-46d2-11eb-9e4b-736ca33a59b4.png)

**Geyser Version**

![image](https://user-images.githubusercontent.com/18662086/103138435-f2789f80-46d2-11eb-9e36-2bd792806cf1.png)

**Minecraft: Bedrock Edition Version**

Win 10, 
![image](https://user-images.githubusercontent.com/18662086/103138451-0cb27d80-46d3-11eb-83a0-369eb3b6aa67.png)

**Additional Context**

CMI plugin https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/updates

Dump: https://dump.geysermc.org/NlFQBlepUTc8SorxBD2reoPkdT1BUSBN

**Comment by YHDiamond** [comment]
this looks like a floor item isn't rendering properly

**Comment by bobhenl** [comment]
Also holograms are visible through walls when they shouldn't be, on Java they aren't when using CMI.
![image](https://user-images.githubusercontent.com/18662086/105051680-4cb91600-5a6f-11eb-8592-a3443a657062.png)

**Comment by EasyClifton** [comment]
> Also holograms are visible through walls when they shouldn't be, on Java they aren't when using CMI.
> ![image](https://user-images.githubusercontent.com/18662086/105051680-4cb91600-5a6f-11eb-8592-a3443a657062.png)

This is just how holograms look in Bedrock. Probably noting we can do about it.

**Comment by Jens-Co** [comment]
Was unable to replicate this issue.

Tested with Paper server 1.16.5 ,  holographic-displays, Latest version of Geyser and Floodgate.
Pictures are both Java and Bedrock. Holograms can be seen through walls but icons not. 

![test1](https://user-images.githubusercontent.com/63231928/164947017-de1b7b70-9a44-432c-85d8-7cc66ee8fae8.jpg)
![test2](https://user-images.githubusercontent.com/63231928/164947019-b0e9f03a-781f-41a4-8d4d-84f2853897e9.jpg)
![ECFF4A08-9BDE-489C-BBA6-39678BA9D5E9](https://user-images.githubusercontent.com/63231928/164947042-77b4a6ab-bdb3-4fd6-99d3-bf76cd4fc720.png)
![F565C666-E986-437C-8911-8107054E5A70](https://user-images.githubusercontent.com/63231928/164947044-06f9a87c-03f5-49d9-837b-3b6e36f127fe.png)

**Comment by Jens-Co** [comment]
Ill close this issue for now. 

If you are still having this problem let me know and ill reopen this issue.
thanks
