### ISSUE TITLE
Issue with furniture (armor stands)

### ISSUE THREAD

**Issue by bobhenl** [GeyserMC/Geyser#1735]
**Describe the bug**

Hi, I have issue with armor stands plugin – https://www.spigotmc.org/resources/furniturelibary-protectionlib.9368/updates. In Java edition player can normally place furniture to make their house etc. better, but on Bedrock they don't see it! And that's the problem...

**To Reproduce**

1. Download furniturelib + dicefurniture.
2. Use /furniture give SnowGolem / CandyCane / Tent1 or anything like this.
3. Place it and you see it like this
![image](https://user-images.githubusercontent.com/18662086/103138562-2b654400-46d4-11eb-9b97-c420f0969a57.png)
4. Go on Bedrock and then you will not see any furniture there...
![image](https://user-images.githubusercontent.com/18662086/103138569-36b86f80-46d4-11eb-9105-098e05a02964.png)
Neither tent, sunshade, camera, candycane, snowgolme... anything.

and btw there are armor stands so don't know why it's not shown
![image](https://user-images.githubusercontent.com/18662086/103138572-489a1280-46d4-11eb-94e1-a80053d78b86.png) (screenshot from Java)

**Expected behavior**

It should normally be seen like on Java edition
![image](https://user-images.githubusercontent.com/18662086/103138562-2b654400-46d4-11eb-9b97-c420f0969a57.png)

**Screenshots / Videos**

Above

**Server Version**

![image](https://user-images.githubusercontent.com/18662086/103138415-c0673d80-46d2-11eb-864a-ca8498c2244c.png)

**Geyser Version**

![image](https://user-images.githubusercontent.com/18662086/103138579-59e31f00-46d4-11eb-91d0-ce9c45cca1db.png)

**Minecraft: Bedrock Edition Version**

![image](https://user-images.githubusercontent.com/18662086/103138587-6f584900-46d4-11eb-8e7a-ae22a3d4cd6e.png)
Win 10 + one player on Mobile edition, prob. the latest too

**Additional Context**

Furniture plugin https://www.spigotmc.org/resources/furniturelibary-protectionlib.9368/updates + dicefurniture https://www.spigotmc.org/resources/dicefurniture-plugin-m%C3%B6bel-plugin.6006/updates

Dump: https://dump.geysermc.org/NlFQBlepUTc8SorxBD2reoPkdT1BUSBN

**Comment by Camotoy** [comment]
As this is related to #1251, I'm going to go ahead and close this to consolidate (this can still be used as a reference). Thank you for reporting!
