### ISSUE TITLE
Issue with Resource Pack

### ISSUE THREAD

**Issue by bobhenl** [GeyserMC/Geyser#1736]
**Describe the bug**

Hi, I have Magic plugin and Slimefun plugin on my Java server... author of Magic plugin merged these one and created fully working resource pack which I use. Btw I have bungee network and this resource pack works only on Survival server when you use /getrp, /getrp auto or you download it with /getrp url.

**To Reproduce**

1. Use Magic on server (you don't need Slimefun, but you can if you wanna try reproduce mine issue).
2. Set this in magic config:
```
example: slimefun
examples:
- robes
- star
- automata
- engineering
```
Again, if you don't use Slimefun - it's not needed, you don't have to do anything and you can skip this step
3. Now on Java you can download resource pack (I have the one with Slimefun) via /getrp, /getrp auto or /getrp url (give you this link https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-slimefun-RP-8-1.16.zip
4. Then on Java you will see magic wand (give with /mgive wand or /sf guide for trying slimefun guide too, you will see it like this:
![image](https://user-images.githubusercontent.com/18662086/103139662-b1868800-46de-11eb-8fe1-731f0dfeccff.png)
![image](https://user-images.githubusercontent.com/18662086/103139613-5c4a7680-46de-11eb-8e32-19aa70970595.png)
![image](https://user-images.githubusercontent.com/18662086/103139617-5fddfd80-46de-11eb-883d-dffa80d694a0.png)
![image](https://user-images.githubusercontent.com/18662086/103139622-653b4800-46de-11eb-8d2f-8f0700e632b1.png)
5. Convert this resource pack to Bedrock (you can do it via https://ozelot379.github.io/ConvertJavaTextureToBedrock/ and you'll get this:
The original one didn't converted to MCBE:
[Magic-slimefun-RP-8-1.16.zip](https://github.com/GeyserMC/Geyser/files/5742226/Magic-slimefun-RP-8-1.16.zip)
The converted one:
[Magic-slimefun-RP-8-1.16.zip](https://github.com/GeyserMC/Geyser/files/5742227/Magic-slimefun-RP-8-1.16.zip)
I'm uploading it unzipped, don't worry, it's just in zip to upload here)
6. Join server on Bedrock and you can see it shows that there are resource packs to install
![image](https://user-images.githubusercontent.com/18662086/103139659-acc1d400-46de-11eb-8843-be5a059ac6ad.png)
7. But when you join game and survival server where you have magic (and slimefun, not needed) you will not see anything... I tried use /getrp multiple times, also /getrp url and anything happened. But I'm not sure if there commands don't download it officially for Java edition and this may could be cause...

**Expected behavior**

It should normally work like mentioned up, it should show resource pack icons.

**Screenshots / Videos**

Screenshots are used above.

**Server Version**

![image](https://user-images.githubusercontent.com/18662086/103138431-dffe6600-46d2-11eb-9e4b-736ca33a59b4.png)

**Geyser Version**

![image](https://user-images.githubusercontent.com/18662086/103138435-f2789f80-46d2-11eb-9e36-2bd792806cf1.png)

**Minecraft: Bedrock Edition Version**

Win 10, 
![image](https://user-images.githubusercontent.com/18662086/103138451-0cb27d80-46d3-11eb-83a0-369eb3b6aa67.png)

**Additional Context**

Magic plugin: https://www.spigotmc.org/resources/magic.1056/updates

Also could be tested with Slimefun, but isn't needed! Magic is enough. https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/ + cscorelib

Dump: https://dump.geysermc.org/NlFQBlepUTc8SorxBD2reoPkdT1BUSBN

**Comment by Camotoy** [comment]
This behavior is already an issue under #210 (because of the way extra items have to be handled). Thank you for reporting anyway!
