### ISSUE TITLE
Issue with skins that aren't same as Java names

### ISSUE THREAD

**Issue by bobhenl** [GeyserMC/Geyser#1737]
**Describe the bug**

Hi, when I tested (now I don't have enabled it) using Geyser with offline mode and bungee is normally on online mode, skins weren't shown when player (on Bedrock) joined for ex. with nick Ciiba4 (he has original player Ciiba), but I wanted to just test, so we've set Geyser to offline), but he had bought Bedrock edition and skin on it, but the skin wasn't shown for players on Java. I think this is a little bit problem. It happened when I set offline in Geyser config to let allow join people who JUST bought Bedrock edition and not the Java one, but I've just tested it to see how it works. But this is probably problem, cause it should show skin and in this case Geyser should work like some skin plugin that will convert Bedrock original players skins to Java one, shouldn't it?

**To Reproduce**

1. Set offline mode in Geyser.
2. May also set BUngee to offline to test it.
3. Join with your premium (originally) bought Bedrock edition account
4. Now you won't have skin on this Java server

**Expected behavior**

There should be probably converted skin from Bedrock to java, shouldn't it? even when player doesn't have Java account.

**Screenshots / Videos**

Probably aren't needed.

**Server Version**

![image](https://user-images.githubusercontent.com/18662086/103138431-dffe6600-46d2-11eb-9e4b-736ca33a59b4.png)

**Geyser Version**

![image](https://user-images.githubusercontent.com/18662086/103138435-f2789f80-46d2-11eb-9e36-2bd792806cf1.png)

**Minecraft: Bedrock Edition Version**

Win 10, 
![image](https://user-images.githubusercontent.com/18662086/103138451-0cb27d80-46d3-11eb-83a0-369eb3b6aa67.png)

**Additional Context**

Dump: https://dump.geysermc.org/NlFQBlepUTc8SorxBD2reoPkdT1BUSBN for testing turned offline mode

**Comment by Camotoy** [comment]
With offline mode, you wouldn't get skins on Java anyway, so this is expected behavior. Skins will be coming to Floodgate soon: https://github.com/GeyserMC/Geyser/wiki/Floodgate

**Comment by bobhenl** [comment]
and with just offline auth there can't be conversion method implemented to geyser that could work like skinsrestorer?

**Comment by Camotoy** [comment]
Just use SkinsRestorer. It works for Bedrock, too.

**Comment by bobhenl** [comment]
And can't somehow geyser implement function to hook to skinsrestorer and convert automatically? Cause in skinsrestorer you can set skin via url etc.?

**Comment by Camotoy** [comment]
We will do something similar in Floodgate.
