### ISSUE TITLE
[Question] Way to disable UNICODE?

### ISSUE THREAD

**Issue by bobhenl** [GeyserMC/Geyser#1738]
Hi, just question, is there way to disable unicode transfering? Or wouldn't it be possible, should I create feature request? Cause look at it... it's really weird when something is smaller than something else. It's due to diacritics, I know, but do you think it could be improved?
![image](https://user-images.githubusercontent.com/18662086/103139841-d7ad2780-46e0-11eb-8f6d-c9efb097c71f.png)

**Comment by Camotoy** [comment]
This can likely be fixed with a Java font resource pack - I don't have a link on hand but someone else might. We *may* fix this in the future but we're unsure.

Because this is Bedrock behavior, I'm going to close it.

**Comment by bobhenl** [comment]
Can't find any pack that fixes it :( May if you could help me try find it out? Or if you could try implement it in future

**Comment by EasyClifton** [comment]
Here's one I use for myself 
[MinecraftFont.zip](https://github.com/GeyserMC/Geyser/files/5742397/MinecraftFont.zip)
Though for the letters to render normally in inventories the GUI scale must be set to -1, or else the letters will look a little weird. Also, to let bedrock players connect to your online mode server without a java account you can use [Floodgate](https://github.com/GeyserMC/Geyser/wiki/Floodgate).

**Comment by bobhenl** [comment]
And what's difference between offline and floodgate?

**Comment by bobhenl** [comment]
And just question, how to use your mentioned font? I tried rename to mcpack but it didn't work, I have to convert it?

**Comment by EasyClifton** [comment]
I renamed it form mcpack

**Comment by bobhenl** [comment]
When I use your pack I can't join... even when I renamed it. May try zip it again like really zip mcpack file, or are you using the newest ver? This is really weird @EasyClifton
