### ISSUE TITLE
Online users on offline server compatibillity

### ISSUE THREAD

**Issue by KeyloHyum** [GeyserMC/Geyser#1739]
**Describe the bug**

Hello there! I would like to report you issue that happens when any user that has autologin enabled (from FastLogin) tries to join server, then something like this appear in console https://pastebin.com/jezgbYVn. And he can't join!  I use offline mode, cause why to use Floodgate when it's breaking UUIDS? and there isn't way to disable it and I don't want use prefix before player names, I would like allow them to play from mobile and then from Java PC.

**To Reproduce**

1. So set offline mode in config of Geyser!
2. Then reload plugin!
3. Install FastLogin or something similar!
4. Activate premium login via /premium (double) and then relog to let see ifit's activated
5. AND NOW try it on Bedrock edition!
6. OH! You can't join! And admins see this in console https://pastebin.com/jezgbYVn now big drama appearing, what to do?!

**Expected behavior**

I think that you can make semi-offline mode or something mixed out, or normally accept also online logins in offline mode.  And btw why to use floodgate when it destroy uuids and then players can't play on same account on mobile and on pc.

**Screenshots / Videos**

Screenshots?!
![image](https://user-images.githubusercontent.com/76599428/103141955-96c30c00-46fc-11eb-8330-86e8d5a1c283.png)
Here you are!
**Server Version**

1.16.4, always the newest, but with ViaVersion and Backwards!
**Geyser Version**

as I already told, always the newest!
>....[22:02:17 INFO]: This server is running Geyser version 1.2.0-SNAPSHOT (git-master-9fc6228) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)
[22:02:17 INFO]: Checking version, please wait...

Plugin version for bungeecord!
**Minecraft: Bedrock Edition Version**

1.16.201
**Additional Context**

Additional plugins: FastLogin!

**Comment by Camotoy** [comment]
This is not something we're going to fix. While we allow for offline mode usage, we will not support it nor make accommodations for it. Ask FastLogin to fix this.
