### ISSUE TITLE
Sweeping edge enchantment name visibility

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [GeyserMC/Geyser#1741]
**What feature do you want?**
A description for the sweeping edge enchantment to be visible when it's on an item; since it's a Java only enchant it doesn't show up on a bedrock client besides in the current enchanting table gui

**Alternatives?**
I don't know of any

**Comment by Camotoy** [comment]
Related to https://github.com/GeyserMC/Geyser/issues/1409.

**Comment by ImDaBigBoss** [comment]
I think this is handled by GeyserOptionalPack now isn't it?

**Comment by Camotoy** [comment]
No. This issue requests for the description and not the particle.

**Comment by TBYT** [comment]
> its almost been a year since the last comment here so ill ask, will this be fixed anytime soon?

I've made an alternative @Oofman1062 @DUDEbehindDUDE . It's a spigot plugin that the server owner would need to download. https://github.com/TBYT/GeyserParity/releases
