### ISSUE TITLE
Spawner Movement Bug

### ISSUE THREAD

**Issue by GoldenMyst** [GeyserMC/Geyser#1743]
**Describe the bug**
Player movement glitches when close to spawners.

**To Reproduce**
  1. Stand very close to a spawner
  2. Move

**Expected behavior**
Move without glitches

**Screenshots / Videos**

https://user-images.githubusercontent.com/74118946/103159013-17bfe900-4779-11eb-9f1c-ced7162b8011.MOV

**Server Version**
1.16.4 (git-Paper-335)

**Geyser Version**
1.2.0-SNAPSHOT

**Minecraft: Bedrock Edition Version**
1.16+

**Additional Context**
none

**Comment by Topnitel** [comment]
This also happens to me quite often while fighting blazes at a spawner
Since I assume this happens on just about every server, here's a dump:
https://dump.geysermc.org/koMLsKupPwcyQCKXnQ3bDJVRVdXDkMcZ

**Comment by davchoo** [comment]
Seems to be due to https://bugs.mojang.com/browse/MCPE-41996
