### ISSUE TITLE
Possible sound bug

### ISSUE THREAD

**Issue by Extollite** [GeyserMC/Geyser#1745]
In lines highlighted below getBedrock() appears twice, it doesn't seem intended, but I'm not sure what should be there.

https://github.com/GeyserMC/Geyser/blob/d1c571d710ea2c14a606b6e224a76bebed967a84/connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaPlayBuiltinSoundTranslator.java#L62

**Comment by rtm516** [comment]
Looks like your correct, this if statement seems completely redundant https://github.com/GeyserMC/Geyser/blob/d1c571d710ea2c14a606b6e224a76bebed967a84/connector/src/main/java/org/geysermc/connector/network/translators/java/world/JavaPlayBuiltinSoundTranslator.java#L63-L65

**Comment by YHDiamond** [comment]
yeah it looks like the 3 if statements after the first one will never run because it was just set to not null.
