### ISSUE TITLE
Blocks Wont Break and Change Upon Leaving

### ISSUE THREAD

**Issue by Brooksd91** [GeyserMC/Geyser#1746]
**Describe the bug**
When I leave a chunk and return my blocks are mixed up on the project I built. Also blocks im standing near wont break often and jus reappear. 

**To Reproduce**
Build something then leave the area.
return to the area and see the broken project.

**Expected behavior**
When I return id expect to see the project as I had just left it.

**Screenshots / Videos**
https://youtu.be/3SZd-ctD7_s
https://youtu.be/nz6vK_Uw3ss 
![Minecraft_2020-12-27-02-09-19](https://user-images.githubusercontent.com/76223498/103173853-42ff1280-4823-11eb-96c3-a21f3e103e0b.jpg)
![Minecraft_2020-12-26-20-56-00](https://user-images.githubusercontent.com/76223498/103173857-46929980-4823-11eb-9556-eb827b576608.jpg)

**Server Version**

Spigot 1.16.4

**Geyser Version**

We are using floodgate and our version of geysers is build #536 of Geyser-Spigot

**Minecraft: Bedrock Edition Version**

1.16.201
**Additional Context**

The server cpu and memory both remain under half, my server ping is 60 and no players are reporting lagg also the the staff at apex hosting have suggested I make this report as they have tried to config the server tic and such to reduce this issue. 

Geyser dump: https://dump.geysermc.org/CL5cITDGmT1s5eygTyo2Alf8aswiSrYJ

**Comment by Brooksd91** [comment]
I removed the solid fix Plugin and stll have the issue for sure.  In the photos , one photo is what i made, and the other is what i returned too. I built the word hit then teleported away and returned to see it not as I jus left. 

![Minecraft_2020-12-29-09-10-21](https://user-images.githubusercontent.com/76223498/103293655-e718c300-49b5-11eb-8979-d186d765190d.jpg)

![Minecraft_2020-12-29-09-10-45](https://user-images.githubusercontent.com/76223498/103293628-dc5e2e00-49b5-11eb-931a-949bc58350e3.jpg)
![Minecraft_2020-12-29-09-09-54](https://user-images.githubusercontent.com/76223498/103293640-dff1b500-49b5-11eb-8da2-7110bfc180f5.jpg)
![Minecraft_2020-12-29-09-08-51](https://user-images.githubusercontent.com/76223498/103293648-e3853c00-49b5-11eb-99b7-532dec0bb092.jpg)

**Comment by Camotoy** [comment]
It looks like your last screenshot encountered the known ghost block issue that occurs because mobile reach (especially on creative) is further than survival. I would try https://github.com/GeyserMC/Geyser/pull/1336 and see if it resolves your issues - please feel free to ask how to download this on our Discord.

**Comment by Brooksd91** [comment]
The issue still continues for me after installing the new geyser jar. do you know any thing else that could be causing the issue?

**Comment by Camotoy** [comment]
Have you been working with mobile during all this? Do you have access to another non-touch platform that you can try to verify the behavior?

**Comment by Brooksd91** [comment]
I have a pc on order. Im waiting to try it tomorrow when it arrives. I'll reply asap.

**Comment by Camotoy** [comment]
Any update by chance?

**Comment by Brooksd91** [comment]
It seems to be due to the multiverse plugin that generated the world
originally.

**Comment by Jens-Co** [comment]
Hello @Brooksd91, are you still encountering this problem? If not I will be closing this issue soon.

**Comment by Brooksd91** [comment]
Yes, although it only seems to have the issue more than 5000 blocks from
0,0,0

**Comment by RednedEpic** [comment]
No further reports of this & we've done a large set of changes since this was last reported. Please open a new issue with updated replication steps if this still occurs.
