### ISSUE TITLE
Geyser Error

### ISSUE THREAD

**Issue by xMercyTheDeveloper** [GeyserMC/Geyser#1747]
**Describe the bug**
When I start my server, i get errors continuously.

**To Reproduce**
1. Install Geyser-Spigot.jar
2. Put in the plugins folder.
3. Start the server

**Expected behavior**
I expected to start the server without errors

**Screenshots / Videos**
![Screenshot](https://prnt.sc/wauoe9)

**Server Version**
CraftBukkit version git-Spigot-628435a-878b437 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
Build #544 (27 Dec 2020, 00:51:26)

**Minecraft: Bedrock Edition Version**
(Didn't tested cause of the error)

**Additional Context**
I can't

**Comment by rtm516** [comment]
Can you re-upload the image, and share server logs?

**Comment by timof121** [comment]
Same

**Comment by xMercyTheDeveloper** [comment]
ok

**Comment by xMercyTheDeveloper** [comment]
https://prnt.sc/wauoe9

**Comment by xMercyTheDeveloper** [comment]
I deleted the server logs...

**Comment by xMercyTheDeveloper** [comment]
oh nvm

**Comment by xMercyTheDeveloper** [comment]
https://pastebin.com/uWSJvp3P

it's same error, it's repeating the same error....

**Comment by xMercyTheDeveloper** [comment]
the entire log
https://pastebin.com/CcgmGvfQ

**Comment by Camotoy** [comment]
Are you able to get a Geyser dump?

> Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by Chew** [comment]
Sadly no dump was provided. If you happen to run into these errors on the latest version, please feel free to open a new issue. Thank you for your report regardless!
