### ISSUE TITLE
Include Build Number in Start logs and /geyser version

### ISSUE THREAD

**Issue by Chew** [GeyserMC/Geyser#1748]
**What feature do you want?**
It would be nice to see the Build number in the startup logs to see what build you're on in case something goes sour and you can't make a dump.

Additionally, seeing it in /geyser version is a clear indication of how many builds you are, and it would be nice if it could mimic the behavior of `/icanhasbukkit` and show how many builds behind you are.

**Alternatives?**
Crying myself to sleep never knowing what build I'm on

**Comment by jkcoxson** [comment]
This is a great idea, although may not work in practice. CI handles the build numbering. What we could do instead is what Dolphin does; include the git hash in Geyser versioning to compare what version you are on.

**Comment by Camotoy** [comment]
We include a `git.properties` file that holds the build number.

**Comment by jkcoxson** [comment]
The jar or plugin, which people are downloading and using, does not create git.properties. I think that is the feature request here. From what I know about the code, it creates it on build.
