### ISSUE TITLE
Skin is usually steve with thin arms when logging into Geyser with a java account

### ISSUE THREAD

**Issue by leem919** [GeyserMC/Geyser#1750]
**Describe the bug**

When logging into Geyser using a java account, my skin shows up as steve with thin arms rather than my java skin.
**To Reproduce**

1. Connect to Geyser server
2. Log in with java account at the prompt
3. Join in and look at skin
4. It's not java skin
**Expected behavior**

My bedrock skin gets changed to my java skin instead of broken steve
**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/8106607/103182991-80d05b00-4864-11eb-9d60-d947c1917c08.png)

**Server Version**

![image](https://user-images.githubusercontent.com/8106607/103182912-e4a65400-4863-11eb-99e9-18845ea1ef1f.png)

**Geyser Version**

Plugin for spigot. Build #544
**Minecraft: Bedrock Edition Version**

1.16.201
**Additional Context**

https://dump.geysermc.org/uASkIkSdFEbrI6b7vNGLeVIbKDnbwsdx

**Comment by RedSmarty** [comment]
Steve texture on alex model?
