### ISSUE TITLE
bedrock redstone dots

### ISSUE THREAD

**Issue by silvercreeper356** [GeyserMC/Geyser#1754]
**What feature do you want?**
 when a bedrock player right clicks a redstone piece the sevrer sees it as changed to a dot but the bedrock client does not
add the redstone dot to java

**Comment by YHDiamond** [comment]
I think theyll look the same in bedrock no matter what because bedrock doesn't even have that feature afaik

**Comment by Camotoy** [comment]
This was submitted from the Discord as a request that we do something on our side, which is possible with a resource pack.

**Comment by EasyClifton** [comment]
Yes, Bedrock doesn't have that feature and it was introduced into Java very recently.

**Comment by YHDiamond** [comment]
Why is this the "can't fix" label if we can fix it with a resource pack?

**Comment by Tydium** [comment]
I would assume its a "Can't Fix" because it can't be fixed natively. However if you guys do manage to fix that with a resource pack let me know.

**Comment by Kas-tle** [comment]
To fix this with a resource pack would require a separate, new custom block, and Geyser would need to ensure it always replaced redstone wire blocks in a chunk with this custom block. This is because, for the moment, vanilla blocks simply cannot be edited via resource or behavior pack.

**Comment by YodaLightsabr** [comment]
> To fix this with a resource pack would require a separate, new custom block, and Geyser would need to ensure it always replaced redstone wire blocks in a chunk with this custom block. This is because, for the moment, vanilla blocks simply cannot be edited via resource or behavior pack.

Sounds like it's hard to fix, but it can still be fixed, so we should remove the "Can't Fix" label. Add a "Too difficult for me to fix" label if you want to, but remove the "Can't Fix" label.

**Comment by Camotoy** [comment]
It is still unknown if all the properties of the redstone dot can be implemented through a custom resource pack. Therefore, the label stays until proven otherwise.

**Comment by RednedEpic** [comment]
Closing as this is technically a Bedrock limitation, and am adding this to the limitations page on the wiki. If this are to be implemented through the GeyserOptionalPack, it will be marked as so on that page.
