### ISSUE TITLE
Block mining animations are inconsistent

### ISSUE THREAD

**Issue by GoldenMyst** [GeyserMC/Geyser#1755]
**Describe the bug**
When mining with mining fatigue, haste and efficiency, the block mining animation are messed up.

**To Reproduce**
    1. Get mining fatigue and haste on a pickaxe (or any item) [maybe efficiency]
    2. Mine a block

**Expected behavior**
A consistent animation like in vanilla mcpe

**Screenshots / Videos**

**Server Version**
1.8-1.16+

**Geyser Version**
Build #535

**Minecraft: Bedrock Edition Version**
1.16+

**Additional Context**

**Comment by WolfyRed** [comment]
Yes, that would be the case for me too. Except it's more inconsistent with any tool, even your fist.

I do hope the bug is fixed in close to 5 days

**Comment by RednedEpic** [comment]
Do you have a video of this occurring?
