### ISSUE TITLE
Giant Stone chunks appearing in unloaded areas of world!! (BUG!)

### ISSUE THREAD

**Issue by WolfyRed** [GeyserMC/Geyser#1757]
**Describe the bug**
Me and my family play on my server, it works fine for every client (Java client), EXCEPT for Bedrock clients!! Giant HUGE chunks of stone generate at unloaded parts of the world!!

**To Reproduce**
1. Login on Bedrock edition (With Geyser + ViaVersion plugin)
2. MOVE FAR AWAY FROM THE SPAWN POINT
3. Giant chunks of stone is displayed!!! They even have collision!

**Expected behaviour**
I expected giant weird chunk errors to **not** occur, knowing I only have 4 Plugins in my server files!

**Screenshots / Videos**
Screenshots provided!!!
![Minecraft 12_29_2020 5_39_50 PM](https://user-images.githubusercontent.com/66114400/103318644-169eee00-49fd-11eb-8207-894bc2650be0.png)
![Minecraft 12_29_2020 5_17_08 PM](https://user-images.githubusercontent.com/66114400/103318650-1b63a200-49fd-11eb-9f49-be8a758ea891.png)
![Minecraft 12_29_2020 6_00_39 PM](https://user-images.githubusercontent.com/66114400/103319407-cf662c80-49ff-11eb-805b-e4d1c3d48afb.png)

**Server Version**
 1.12 Spigot server

**Geyser Version**
1.2.0-SNAPSHOT

**Minecraft: Bedrock Edition Version**
v1.16.201

**Additional server info**
I use ViaVersion and Geyser plugins, no BungeeCord! (Spigot 1.12)
`((I also like the 1.12 world generation so that's why I use 1.12!!))`
`(And the server runs at 8 GB of RAM as well!)`

**Comment by WolfyRed** [comment]
Leave open until the error has been fixed, even almost completely is fine.

**Comment by Camotoy** [comment]
Likely related to #1581.
