### ISSUE TITLE
Supports for custom models

### ISSUE THREAD

**Issue by YuttaL** [GeyserMC/Geyser#1759]
**SUPPORT**
Add support for custom models Or datapacks
I couldn't think much about it and they may have already put the same thing as me but, I was thinking that it could be implemented as a behavior pack or as if it were a bedrock addon

**Alternatives?**
Normally custom models come in texture packs maybe if there was a way to convert those texture packs into a behavior or as it would be spectacular (?.

**Comment by Camotoy** [comment]
This sounds like the same thing currently being discussed in #210 (resource pack conversion); in order to keep issues tidy, I'm closing this since it discusses a similar topic. If you disagree, please let me know! Thank you!
