### ISSUE TITLE
Boats cannot be placed

### ISSUE THREAD

**Issue by Legit4K** [GeyserMC/Geyser#176]
**Describe the bug**
All varients of boats can't be placed (land & water) 

**To Reproduce**
1. Try to place a Boat
2. Watch it fail
3. The boat will re appear in the inventory

**Expected behavior**
The boat gets placed

**Screenshots**
Would be pointless to describe this bug

**Server version**
git-Paper-105 (for MC 1.15.2)

**Geyser version**
Tested on Latest Build on master branch
Also tested on the Inventory Branch
Also tested on the block entities Branch

**Bedrock version**
1.14.30.2 (Release)

**Additional context**
Buckets also seem to have a similar issue

**Comment by RednedEpic** [comment]
Superseded by #187.
