### ISSUE TITLE
Bedrock players can't grab items out of item frames in adventure mode

### ISSUE THREAD

**Issue by ThyradorYT** [GeyserMC/Geyser#1761]
**Describe the bug**
Bedrock players can't grab items out of an item frame in adventure mode, while I believe java can

**To Reproduce**
1. Go into adventure mode on a minecraft server with geyser installed
2. Try getting an item out of an item frame

**Expected behavior**
I expected the item frame to drop its contents after being hit by a player 

**Server Version**
PaperMC 1.16.4

**Geyser Version**
Geyser master #544

**Minecraft: Bedrock Edition Version**
1.16.201 ios and win10

**Comment by Camotoy** [comment]
This may be a limitation of Bedrock - if they aren't sending the packets to attempt to interact with the item frame while in adventure mode, there may not be a way to make the client interact.

**Comment by Camotoy** [comment]
This *might* be possible, but in a hacky way. But because Bedrock cannot do it, I've marked this as Can't Fix for the time being.
