### ISSUE TITLE
The block an item can be placed on isnt displayed properly on bedrock

### ISSUE THREAD

**Issue by ThyradorYT** [GeyserMC/Geyser#1762]
**Describe the bug**
In adventure maps a lot of items have the "can be placed on:.." tag, on bedrock this tag doesn't display the proper blocks, for example, red concrete, yellow concrete etc. all turn into white_concrete on the tag

**To Reproduce**
1. Go into adventure mode on a minecraft server with geyser installed
2. Look at an items description that can be placed on a specific coloured block

**Expected behavior**
I expected the item to properly display what block it should be placed on, rather than it being reset to the default colour 

**Server Version**
PaperMC 1.16.4

**Geyser Version**
Geyser master #544

**Minecraft: Bedrock Edition Version**
1.16.201 ios and win10

**Comment by rtm516** [comment]
Can you share some screenshots? and I presume the Geyser version is the build number and if so that's https://github.com/GeyserMC/Geyser/commit/d1c571d710ea2c14a606b6e224a76bebed967a84

**Comment by Camotoy** [comment]
This is a bug I anticipated when I added support for the system. Adding proper support shouldn't be too hard.

**Comment by Camotoy** [comment]
This may be impossible to fix. Items such as concrete are kind of one item in Bedrock, with their data values (in this case, color) as a separate property. From what I understand, there is no way to translate this second property over the can place/can destroy tag.

**Comment by RednedEpic** [comment]
Moved to current limitations page on wiki.
