### ISSUE TITLE
Fake blocks On Geyser.

### ISSUE THREAD

**Issue by Tydium** [GeyserMC/Geyser#1767]
**Describe the bug**
Everytime you mass set a structure to air using the world edit plugin it creates some type of invisible block to java players but on bedrock some blocks get left behind and your able to fully interact with them.

**To REPRODUCE**
1.Use world edit plugin
2.//wand
3. Use wand to select a big area (seems to work on snow and stairs)
4. Do //set air 
5. It should create a chunk outline or left behind blocks. If so then the glitch is working
**Expected behavior**
Java cant see the blocks, but bedrock can and interact

**Screenshots / Videos**
JAVA SIDE: https://youtu.be/RBW3fBgSPNk
BEDROCK SIDE: https://youtu.be/HOPd0W4YACY
**Server Version**
Server hosted on Bungeecord leading into a 1.8.8 Paper Server

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-41cb593) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 ) 

Geyser Bungee ^

**Minecraft: Bedrock Edition Version**
1.16.201

**Additional Context**
If you would like to have hands on interaction with the glitch please Direct Message me on discord 
(Tydium#4117)

**Comment by Hellohi3654** [comment]
strange Geyser must not be able to handle mass block change

**Comment by YHDiamond** [comment]
Well it looks like the java server doesn't actually set all the blocks to air, and geyser is actually doing a better job rendering them than java lol

**Comment by Tydium** [comment]
although at the moment I am unable to confirm this. I think I may have fixed this by finally getting the latest update of world edit (waiting a long time for it) 1.16.5 seems to work okay, while 1.8.8 is still backed up. I do not think this is a geyser issue anymore but for safe keeping ill keep an eye on it.

**Comment by timof121** [comment]
fawe works ok

**Comment by Tydium** [comment]
This bug is extremely old, I actually can confirm that it no longer happens. I think this was a bug with world edit and not geyser now that I think about it. I think it is safe to close this :)
