### ISSUE TITLE
Players can pass through world borders

### ISSUE THREAD

**Issue by GoldenMyst** [GeyserMC/Geyser#1773]
**Describe the bug**
World borders can be pass through

**To Reproduce**
  1. Move above the blue particles
  2. Move forwards and pass through

**Expected behavior**
The player should be able to pass through

**Screenshots / Videos**

https://user-images.githubusercontent.com/74118946/103434249-6cb59200-4bb3-11eb-8237-d9cd029bf78c.MOV

**Server Version**
git-Paper-335 // MC: 1.16.4

**Geyser Version**
git-master-a17f220

**Minecraft: Bedrock Edition Version**
1.16+

**Additional Context**

**Comment by Camotoy** [comment]
Can you provide the plugin that is making this world border, as well as what it looks like on Java?

**Comment by GoldenMyst** [comment]
Plugin (BSkyBlock): https://github.com/BentoBoxWorld/BSkyBlock/tree/master

Im on my phone right now but on java it has personal world borders for each island/player.

**Comment by BlunderCig** [comment]
This happens with vanilla world borders too

**Comment by Camotoy** [comment]
Yes, that is known and documented in #447.

**Comment by RednedEpic** [comment]
Does this still occur?

**Comment by Chew** [comment]
No reply from OP regarding this, so we're gonna have to close due to inactivity. If you continue to experience this, please reply or open a new issue. Thank you for reporting!
