### ISSUE TITLE
Unable to connect to world

### ISSUE THREAD

**Issue by HAHALOSAH** [GeyserMC/Geyser#1776]
**Describe the bug**
"Unable to connect to world" on bedrock (iOS)

**To Reproduce**
1. Start GeyserMC
2. Try to join on bedrock

**Expected behavior**
Join the server

**Server Version**
[11:54:39] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-ff439d1-560b65c (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[11:54:39] [Server thread/INFO]: You are running the latest version

**Geyser Version**
version 1.2.0-SNAPSHOT (git-master-a17f220)

**Minecraft: Bedrock Edition Version**
1.16.201

**Additional Context**
Using linux distro Linux Mint 20 Ulyana
https://dump.geysermc.org/VNjutaMsmqMcxM71SLSq3JaPJbYZAl2Y
Firewall is OFF

**Comment by YHDiamond** [comment]
We have a page in the wiki explaining how to fix this.it is a not a geyser problem.

**Comment by HAHALOSAH** [comment]
I have read all of that wiki page, nothing helpful, I can't even join from LAN. Java edition seems to work though.

**Comment by YHDiamond** [comment]
Ok it is not a geyser issue if you come to the discord we'd be happy to help you.

**Comment by RednedEpic** [comment]
Please join our discord at https://discord.geysermc.org for further support on this issue - this is typically not a Geyser issue causing you to be unable to connect.

**Comment by xxxcrow** [comment]
hi everyone
i think it would be very helpful to add it to wiki 
in my case it was necessary to specify the protocol in docker(and also don't forget to add it in the first place)
19132:19132 to 19132:19132/udp

**Comment by jackson-57** [comment]
You're welcome to add it to the wiki, anyone can edit the wiki 🙂
