### ISSUE TITLE
Geyser timed out error

### ISSUE THREAD

**Issue by Dawn-Shalve** [GeyserMC/Geyser#1777]
My bedrock players are getting timed out.
All bedrock players are getting timed out
https://dump.geysermc.org/ykuLcgQeoXOY5c7Q4KHlskf4uz5Yl8df
All players
A raspberry pi(CPU)
Idk what a MTU is

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by Camotoy** [comment]
Closing since this should be a part of the timeout megathread.

**Comment by Dawn-Shalve** [comment]
all right I just did that
