### ISSUE TITLE
Fishing rod bobber is jerky when being thrown

### ISSUE THREAD

**Issue by jackson-57** [GeyserMC/Geyser#1778]
**Describe the bug**

The animation of the fishing rod bobber landing into water is jerky.

**To Reproduce**

1. Use the fishing rod.

**Expected behavior**

The bobber should smoothly be thrown into the water.

**Screenshots / Videos**

https://user-images.githubusercontent.com/49173011/103447342-cdd67780-4c3e-11eb-9df7-ae21a0434637.mp4

**Server Version**
Paper 1.16.4 git-Paper-353

**Geyser Version**
Geyser version git-master-a17f220 (1.2.0-SNAPSHOT) (Spigot)

**Minecraft: Bedrock Edition Version**
1.16.201

**Additional Context**
[Link to dump](https://dump.geysermc.org/N5qfnDCN0WU0mgPH503mOLS23nLbh0ej)

**Comment by Camotoy** [comment]
We might need to apply the same velocity trick we use with thrown potions and the like.

**Comment by Camotoy** [comment]
Fixed with #1929.
