### ISSUE TITLE
Dogs don't show if there tamed and can't be sit down

### ISSUE THREAD

**Issue by LegacyGamerHD** [GeyserMC/Geyser#178]
**Describe the bug**
Dogs cant be sit down while right clicking and no collor tags

to reproduce the behavior:
1. Go to tame a wolf
2. Click on it with a bone
3. You don't see if it's tamed and can't be with down

**Expected behavior**
Right click will sit down the dog they shoeld have a collored tag

**Screenshots**

**Server version**
Latest

**Geyser version**
Latest

**Bedrock version**
1.14.3

**Additional context**

**Comment by RednedEpic** [comment]
Currently being worked on. Next time please follow the issue format and provide all the information.

**Comment by LegacyGamerHD** [comment]
@RednedEpic  did full it in correct

**Comment by LegacyGamerHD** [comment]
Also i Was in a hurry

**Comment by RednedEpic** [comment]
Resolved.

**Comment by Valeri0p** [comment]
Not to open another bug since I'm not the server's admin so I can't check the version or other technical details, but it seems like the dog's tail position remains fixed and doesn't change when the dog looses health e.g. after being attacked by a mob or when it gets healed. Also the feed/sit button feels buggy in general.

**Comment by rtm516** [comment]
> Not to open another bug since I'm not the server's admin so I can't check the version or other technical details, but it seems like the dog's tail position remains fixed and doesn't change when the dog looses health e.g. after being attacked by a mob or when it gets healed. Also the feed/sit button feels buggy in general. (Android minecraft ver 1.16.201.01, geyser plugin updated recently by the server owner it seems)

This is the first report of this we have had and my guess is the tail position is calculated client-side but if I remember I'll look into this tonight if no-one else does.
