### ISSUE TITLE
Fishing rod bobber has broken catching sound/animation

### ISSUE THREAD

**Issue by jackson-57** [GeyserMC/Geyser#1780]
**Describe the bug**

The sound that plays when a fish is caught is either delayed or doesn't play at all. Additionally, the animation is a lot slower than the one on Java Edition and on Bedrock singleplayer. When the sound does play, it's after the animation finishes (which takes a few seconds), so the fish has escaped the hook by then.

**To Reproduce**

1. Use the fishing rod to catch a fish. You might need to try a few times in order to see the full extent of the behavior.

**Expected behavior**

The sound should play immediately (before the animation) when a fish is caught. The animation should be much quicker and smoother.

**Screenshots / Videos**

Bedrock via Geyser (two scenarios in the one clip):

https://user-images.githubusercontent.com/49173011/103448087-0a0ed580-4c49-11eb-9791-bd0457ac98f4.mp4

Java:

https://user-images.githubusercontent.com/49173011/103448093-21e65980-4c49-11eb-8beb-be63d50ffbca.mp4

Bedrock Singleplayer:

https://user-images.githubusercontent.com/49173011/103448106-64a83180-4c49-11eb-83cc-2d9b31984f46.mp4

**Server Version**
Paper 1.16.4 git-Paper-353

**Geyser Version**
Geyser version git-master-a17f220 (1.2.0-SNAPSHOT) (Spigot)

**Minecraft: Bedrock Edition Version**
1.16.201

**Additional Context**
[Link to dump](https://dump.geysermc.org/N5qfnDCN0WU0mgPH503mOLS23nLbh0ej)

**Comment by Camotoy** [comment]
Not yet, buddy.
