### ISSUE TITLE
EssentialsX MOTD only show on the first server the Bedrock client joins and not other linked servers

### ISSUE THREAD

**Issue by Garfieldwxg55** [GeyserMC/Geyser#1783]
EssentialsX MOTDs only show up on the first Spigot server a Bedrock client joins (for instance a Lobby or a Hub server) on a Bungeecord network, and not the other linked servers.

To Reproduce
1. Set up a Bungeecord network with Geyser installed.
2. Set up at least 2 Spigot servers, both with EssentialsX and different MOTDs set to each server.
3. Link the servers so that there is one Spigot server that is a lobby server and the other server can be joined from the lobby.
4. Join the Lobby on Bedrock Edition.
5. Connect to the other server from the lobby.
6. Notice that the EssentialsX MOTD displayed on the Lobby server but not the other server

Expected behavior
I expected the different MOTDs to display on both servers instead of just my Lobby server.

Server Version
Paper-318

Geyser Version
Geyser 1.2.0-Snapshot

Minecraft: Bedrock Edition Version
v1.16.201

Dump
https://dump.geysermc.org/POsvPg2e4PzNTuoFb2Yay2bnnQjniqwL

**Comment by rtm516** [comment]
This sounds like a non-Geyser issue, can you provide some screenshots of where it occurs?

**Comment by Garfieldwxg55** [comment]
> This sounds like a non-Geyser issue, can you provide some screenshots of where it occurs?

No, it works fine on Java edition, so I believe that it is a Geyser issue, I'll post the screenshots as soon as I can access my server again (my internets down)

**Comment by Garfieldwxg55** [comment]
![IMG_6888](https://user-images.githubusercontent.com/69670324/103517363-f2378b80-4eac-11eb-8786-cacff9087fec.png)

**Comment by Garfieldwxg55** [comment]
![IMG_6889](https://user-images.githubusercontent.com/69670324/103517397-011e3e00-4ead-11eb-87b6-72100ce7007e.png)

**Comment by Garfieldwxg55** [comment]
![2021-01-04_16 47 12](https://user-images.githubusercontent.com/69670324/103517475-290da180-4ead-11eb-807a-1175753e463c.png)

**Comment by Garfieldwxg55** [comment]
![2021-01-04_16 48 03](https://user-images.githubusercontent.com/69670324/103517506-36c32700-4ead-11eb-9e6e-279581635bbd.png)

**Comment by Garfieldwxg55** [comment]
Notice that the second MOTD on the Survival Server only shows up on Java edition and not Bedrock edition

**Comment by Chew** [comment]
I'm unable to reproduce this with the following setup:

3 total servers:
1) BungeeCord b1549
2/3) Paper 1.16.5 b579

Set motd, fixed permissions, both showed up fine:

![image](https://user-images.githubusercontent.com/8278263/114807463-176d4d00-9d6c-11eb-9a5f-ec0bacbb5873.png)


This may just be a permission error. If the player doesn't have access to `/motd`, one won't show up. This may have also just been resolved.

If you're still having issues, please verify the bedrock player can run `/motd`, and we can go from there. Otherwise, thank you for the report, and have a great day!
