### ISSUE TITLE
Minecraft Bedrock crafting table above my head!! (BUG)

### ISSUE THREAD

**Issue by WolfyRed** [GeyserMC/Geyser#1784]
**Describe the bug**
When you go to a block with interface (EX: Crafting table, Chest, Furnace) it will appear above your head

**To Reproduce**

1. In survival, break a log of wood.
2. Craft a "Crafting Table" ("Work Bench").
3. Place it down, and go into it's interface.
4. Get out of the interface, and look above your head!

**Expected behavior**
The crafting table to stay in the place it's at, and go into the interface of that crafting table.

**Screenshots / Videos**

**Server Version**
1.12.2 final

**Geyser Version**
1.2.0-SNAPSHOT (git-master-396d1b6) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 -  1.16.200.5)

**Minecraft: Bedrock Edition Version**
v1.16.201

**Additional Context**
![image](https://user-images.githubusercontent.com/66114400/103451284-0bafbc00-4c90-11eb-8b8e-5e0312b795a0.png)

**Comment by jackson-57** [comment]
Not a bug

**Comment by WolfyRed** [comment]
> Not a bug. This is intentional behavior.

What if the block above the player's head is a chest and they click on a crafting table

**Comment by jackson-57** [comment]
It won't overwrite the chest (the chest will reappear). Additionally, the crafting table should disappear after a second.

**Comment by WolfyRed** [comment]
> It won't overwrite the chest (the chest will reappear). Additionally, the crafting table should disappear after a second.

Alright, well in that case I am not worried anymore about this issue.
I was still wondering about the fact why block breaking animations don't show in survival mode for Bedrock clients, and if I can change a plugin.yml setting to change that

**Comment by jackson-57** [comment]
Turn on cache-chunks to get block mining animations working.

**Comment by WolfyRed** [comment]
> Turn on cache-chunks to get block mining animations working.

Off or on? I looked and it says it's set to "true"

**Comment by Chew** [comment]
This should be further discussed on [Geyser's Discord server](https://discord.geysermc.org)
