### ISSUE TITLE
Partial blocks breaks head movement 

### ISSUE THREAD

**Issue by Riverhappytv** [GeyserMC/Geyser#1786]
**Describe the bug**
If you walk next to block such as:
Bamboo, iron bars, ladders and other and other partial blocks 

**To Reproduce**
Steps to reproduce the bug:
1. Go to partial block
2. Walk into block
3. Head does crazy movement 
4. (If on ladder unable to climb up)

**Expected behavior**
To be able to Stand next to partial blocks and climb up ladders

**Screenshots / Videos**
https://youtu.be/f79xs_fCMJs

**Server Version**
I’m guessing this means the Java version the sever runs on
1.16.4

**Geyser Version**
1.2.0 -SNAPSHOT 

**Minecraft: Bedrock Edition Version**
1.16.201

**Additional Context**
https://dump.geyser.mc.org/rJRMl7otj5ysGDTfRdngG8vkKU6u9H3

(Idk if I typed it in correctly but idk if it matters) also I did use floodgate

**Comment by Camotoy** [comment]
Bamboo is known and is an entirely separate problem to fix because of the placement differences between Java and Bedrock.

**Comment by RednedEpic** [comment]
Should be fixed by #2430.
