### ISSUE TITLE
Links in wiki are broken.

### ISSUE THREAD

**Issue by applebee1558** [GeyserMC/Geyser#179]
A) The links such as “how to set up geyser” and “how geyser works” do nothing except redirecting to the same page.

B) The wiki in floodgate is confusing as it both says you must compile yourself, but at the same time gives a link downloading a prebuilt one. The plugin itself seems to be a standalone server, but the wiki doesn't explain that clearly.

**Comment by RednedEpic** [comment]
Fixed.
