### ISSUE TITLE
Buying items in BossShop not working

### ISSUE THREAD

**Issue by Eoraptorur** [GeyserMC/Geyser#1791]
**Describe the bug**
Menus in BossShop work fine, but clicking on items for command items or buyable doesn't work

**To Reproduce**

Open menu and click on buyable/command items.

**Expected behavior**
To run commands or buy items

**Screenshots / Videos**
![Test](https://user-images.githubusercontent.com/29491724/103490158-404f7f00-4e1a-11eb-8665-bd16581c26d0.gif)
/sell items

**Server Version**
1.16.4

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-1a08e11) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)

**Minecraft: Bedrock Edition Version**
Latest version

**Comment by Camotoy** [comment]
Please provide a Geyser dump, as well as a log, if there are any errors present there.

**Comment by Camotoy** [comment]
Turns out this person just didn't see the chat due to the way that Bedrock and Java differentiate on handling chat while in a menu.
