### ISSUE TITLE
Adding GeyserMC to Minecraft Java Edition as a client mod?

### ISSUE THREAD

**Issue by RKDUDE02** [GeyserMC/Geyser#1792]
I was wondering if it was possible to add GeyserMC to Minecraft Java Edition as a client mod, so that when i open a world to a LAN, bedrock clients can join my java lan world? This would eliminate the need for a server. Is it even possible to port GeyserMC as a client mod?

**Comment by Camotoy** [comment]
See Geyser-Fabric: https://github.com/GeyserMC/Geyser-Fabric

While it's not in perfect shape, it, ideally, should work.
