### ISSUE TITLE
Reloading plugin after placing new jar (also used ServerUtilities plugin)

### ISSUE THREAD

**Issue by bobhenl** [GeyserMC/Geyser#1793]
**Describe the bug**

Hi, I wanna report that when you try to reload plugin after changing your jar from new to old (for ex. when new build is out), then you try /geyser reload to apply changes, it doesn't work, cause you'll get kicked for:
![image](https://user-images.githubusercontent.com/18662086/103493117-cc1fd600-4e2f-11eb-8fbe-91e45257bff5.png)

Also tried with /bsu unloadplugin Geyser but getting same error https://www.spigotmc.org/threads/serverutils-bungeecord-spigot-manage-plugins-in-game-plugman-alternative-more.442838/

**To Reproduce**
1. Place there old build jar (I've had the one placed on Discord yesterday when repository server was down – https://drive.google.com/file/d/1GXnEUDigNP5HOF-2hnjB23nYqKERCM2R/view?usp=sharing).
2. Restart server.
3. Place there new jar (I tried 554)
4. Use /geyser reload or try /bsu unloadplugin /reloadplugin Geyser-Bungeecord (or simply tab complete, IDK how it is there)
5. Then you'll see followed message and you will be kicked from server:
![image](https://user-images.githubusercontent.com/18662086/103493117-cc1fd600-4e2f-11eb-8fbe-91e45257bff5.png)
https://pastebin.com/npcbKPUC

**Expected behavior**

It should normally be reloaded and use new version, at least this error shouldn't occur. Then also it isn't displaying server for Bedrock players.

**Screenshots / Videos**

Mentioned above.

**Server Version**

It probably isn't needed, I've mentioned versions above, using 1.16.4 and paper from end of December, but it isn't relate.

**Geyser Version**

Also mentioned up, but if you want
**Minecraft: Bedrock Edition Version**

![image](https://user-images.githubusercontent.com/18662086/103493276-98917b80-4e30-11eb-8b79-003a069e577a.png)

**Additional Context**

**Comment by RednedEpic** [comment]
Using /geyser reload to change out a jar is not supported under any capacity. This command is for reloading configuration options. Additionally, any kind of hotswapping jars (such as through PlugMan) is not supported either.

**Comment by bobhenl** [comment]
But maybe you could at least add way to don't corrupt it and let players normally join, and prevent this.

**Comment by Camotoy** [comment]
We wouldn't know how to. When you're reloading a plugin that you changed, you're heading into uncharted territory. If you can give us an example of a plugin that does handle this correctly, then feel free to place it here.
