### ISSUE TITLE
Downstream packet... error when player is joining

### ISSUE THREAD

**Issue by bobhenl** [GeyserMC/Geyser#1794]
**Describe the bug**

Hi, this error is occurring when player is joining server, I don't know why etc., but I could help investigate.
![image](https://user-images.githubusercontent.com/18662086/103493296-c5de2980-4e30-11eb-885b-8fc3a5824c28.png)

**To Reproduce**
1. Join server
Don't know, I can help investigate, just give me tips what could be the issue.

**Expected behavior**

Any error.

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/18662086/103493310-d7273600-4e30-11eb-9cc7-bb3b462066cb.png)

**Server Version**

![image](https://user-images.githubusercontent.com/18662086/103493315-e0180780-4e30-11eb-979e-9d08a8533913.png)

and the newest Waterfall (I have auto updater,really)
**Geyser Version**

![image](https://user-images.githubusercontent.com/18662086/103493323-e7d7ac00-4e30-11eb-83b3-a4f331e8ef82.png)

**Minecraft: Bedrock Edition Version**

1.16.201
**Additional Context**

Anything, I can help more if you wanna.

**Comment by Camotoy** [comment]
Please enable debug mode in Geyser's config, restart, and attach logs of someone connected.

**Comment by bobhenl** [comment]
https://pastebin.com/m76BpS2p Here Camotoy

**Comment by bobhenl** [comment]
Anything new?

**Comment by Camotoy** [comment]
@bobhenl it appears the error occurs with an empty title being sent? Please try the following:

If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
- Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by bobhenl** [comment]
Ok, solved, sorry. I can't find the plugin on internet, so I downloaded another one. IT probably doesn't exist anymore there.
