### ISSUE TITLE
AdvancedNMotd plugin (gradient motd, but it should convert! incompatibility

### ISSUE THREAD

**Issue by bobhenl** [GeyserMC/Geyser#1795]
**Describe the bug**

Hi, I have problem when using https://www.spigotmc.org/resources/advancednmotd-let-your-motd-smile.58677/updates, after the latest update with `passthrough-motd: true` in Geyser and following files (added gradient motd, but when you will read it's update nodes you will see that for ex. on older clients it converts to normal colors, so it shouldn't be problem) https://pastebin.com/7iqAHd91 - strings file https://pastebin.com/sxmXfw87 - config file -> you can use for testing issue

Then server can't be found in server list and couldn't be joined due to Unable to connect to the world message. But as mentioned, there's file Colors.yml in ADvancedNMotd, that should convert gradient colors to the most similar colors before 1.16.4, so the normal one.

BTW: How to use colors in Geyser motd in config? If it couldn't be fixed.

**To Reproduce**
1. DOwnload AdvancedNMotd.
2. Place there my config file and my strings.yml file.
3. Download geyser as well :D and enable passthrough-motd: true
4. Try to ping server on Bedrock (normally add it on server list) and you wouldn't see it and you wouldn't be able to join, due to gradient there probably (cause on previous update without gradient it worked great even when I passed motd, and there were colors too! Now I don't have any colors without passthroughing motd :( )

**Expected behavior**

It should be normally visible with older colors. Or at least it should be normally joinable.

**Screenshots / Videos**

Aren't needed probably.

**Server Version**

![image](https://user-images.githubusercontent.com/18662086/103493315-e0180780-4e30-11eb-979e-9d08a8533913.png)

and the newest Waterfall (I have auto updater,really)
**Geyser Version**

![image](https://user-images.githubusercontent.com/18662086/103493323-e7d7ac00-4e30-11eb-83b3-a4f331e8ef82.png)

+ the newest ver of AdvancedNMotd

**Minecraft: Bedrock Edition Version**

1.16.201
**Additional Context**

Just question :D How to set colors in motd1 and motd2 sections? Cause color codes like &f etc. don't work.

**Comment by Camotoy** [comment]
Colors can probably be added with `§` instead of `&`.
