### ISSUE TITLE
Auto deny resource packs

### ISSUE THREAD

**Issue by Projecki** [GeyserMC/Geyser#1796]
**What feature do you want?**
Automatically deny resource packs that java servers ask their users to apply.

Resource packs have caused connection issues for bedrock players on our network.

Camotoy ask me to create this to resolve my issues.

**Alternatives?**

Create a prompt for accepting or denying resource pack, and if accepted apply the resource pack. Not sure how feasible this is though.

**Comment by Camotoy** [comment]
The alternative will be done in the future.

**Comment by Projecki** [comment]
I know we aren't looking into the connection issue fixes but for future reference, here's the error presented to bedrock client next time I login after this issue occurs. 
https://cdn.discordapp.com/attachments/613168464634576897/795463051548688462/unknown.png

**Comment by onebeastchris** [comment]
Implemented in https://github.com/GeyserMC/Geyser/commit/3547fab228aefe556be948d8a4e650870a526cb5
