### ISSUE TITLE
Incorrect Sounds

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [GeyserMC/Geyser#1803]
**Describe the bug**

throwing an eye of ender makes the firework rocket sound, and putting an ender eye into a portal frame block plays the sound twice

**To Reproduce**

throw an eye of ender, and ot sounds like a firework being launched

put an eye of ender into an end portal frame, and it sounds as if its played twice

**Expected behavior**

the eye of ender should sound like an eye of ender being thrown and putting it into portal frame should only play once

**Screenshots / Videos**

**Server Version and Plugins**

This server is running Geyser version 1.2.0-SNAPSHOT (git-master-69dc4a9) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)

**Geyser Dump**

https://dump.geysermc.org/kfL2SOzHZla2ht8Uuy3lPjs42b27rKUi

**Minecraft: Bedrock Edition Version**

android 10, 1.16.201

**Comment by AJ-Ferguson** [comment]
>put an eye of ender into an end portal frame, and it sounds as if its played twice

This is a Bedrock client bug.
https://bugs.mojang.com/browse/MCPE-94727

>throw an eye of ender, and ot sounds like a firework being launched

The exact sound used in Java Edition when throwing an eye of ender is missing in Bedrock, so the sound is substituted.
Though maybe it would be better to use the bow shoot sound instead. (Might have been original intention based on the current playsound mapping.) 
https://github.com/GeyserMC/mappings/blob/a4103ea47d63f98a0fe78b18b258c16309107650/sounds.json#L941-L943

**Comment by DUDEbehindDUDE** [comment]
> The exact sound used in Java Edition when throwing an eye of ender is missing in Bedrock, so the sound is substituted.
Wouldn't it just make the most sense to use the throwing sound that bedrock already uses?

**Comment by timof121** [comment]
Also flower sound is stone i think

**Comment by EasyClifton** [comment]
I believe that happens if chunk caching isn't enabled.

**Comment by RednedEpic** [comment]
These are the default bedrock sounds / are potentially bugs on bedrock. Closing.
