### ISSUE TITLE
BrokenPipe

### ISSUE THREAD

**Issue by marcussmith03** [GeyserMC/Geyser#1804]
**Describe the bug**

I got a brokenpipe error when i first added geyser and floodgate then tried to join. 
**To Reproduce**

1. Join server on bedrock
2.get kicked for brokenpipe
3. See error

**Expected behavior**

expected to be able to join like i can on my other paper servers.

**Server Version and Plugins**
viaversion
geyser-spigot
floodgate-bukkit

If you're running a multi-server instance, or using Geyser Standalone:

- multiserver-Paper version git-Paper-323 (MC: 1.16.4), and Magma version bb50f45 (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge Version 14.23.5.2855) <<< (the server im having issues with)
- too many plugins on my paper server,,, geyser-spigot and floodagate and viaversion only on Magma

**Geyser Dump**

https://dump.geysermc.org/9Kb49rlhWxUfyrZvJJO9rKXLf799HNbB

**Minecraft: Bedrock Edition Version**

ios 14.0 mc version 1.16.200
**Additional Context**
full error

[01:16:06] [Netty Epoll Server IO #1/WARN] []: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.LoginListener$LoginHandler
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:106)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at java.lang.Class.forName0(Native Method)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at java.lang.Class.forName(Class.java:348)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at org.magmafoundation.magma.remapper.proxy.ProxyClass.forName(ProxyClass.java:42)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at org.magmafoundation.magma.remapper.proxy.ProxyClass.forName(ProxyClass.java:38)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at org.geysermc.floodgate.util.ReflectionUtil.getClass(ReflectionUtil.java:23)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at org.geysermc.floodgate.util.ReflectionUtil.getPrefixedClass(ReflectionUtil.java:18)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at org.geysermc.floodgate.PacketHandler.<clinit>(PacketHandler.java:180)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at org.geysermc.floodgate.injector.BukkitInjector$2$1.initChannel(BukkitInjector.java:72)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at io.netty.channel.DefaultChannelPipeline$3.run(DefaultChannelPipeline.java:220)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> [01:16:06] [Netty Epoll Server IO #1/WARN] []: at java.lang.Thread.run(Thread.java:748)
> [01:16:06] [Netty Epoll Server IO #1/WARN] [io.netty.channel.ChannelInitializer]: Failed to initialize a channel. Closing: [id: 0x1e57bf38, L:/172.18.0.43:25664 - R:/172.18.0.43:46158]
java.lang.ExceptionInInitializerError: null
at org.geysermc.floodgate.injector.BukkitInjector$2$1.initChannel(BukkitInjector.java:72) ~[?:?]
at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [ChannelInitializer.class:?]
at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [ChannelInitializer.class:?]
at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597) [DefaultChannelPipeline.class:?]
at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44) [DefaultChannelPipeline.class:?]
at io.netty.channel.DefaultChannelPipeline$3.run(DefaultChannelPipeline.java:220) [DefaultChannelPipeline$3.class:?]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [AbstractEventExecutor.class:?]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [SingleThreadEventExecutor.class:?]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [EpollEventLoop.class:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NullPointerException
at org.geysermc.floodgate.PacketHandler.<clinit>(PacketHandler.java:183) ~[?:?]
... 11 more
> [01:16:06] [nioEventLoopGroup-2-2/INFO] [org.geysermc.platform.spigot.GeyserSpigotPlugin]: [Geyser-Spigot] SmokinGank has disconnected from remote Java server on address 172.18.0.43 because of java.io.IOException: Broken pipe
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: java.io.IOException: Broken pipe
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at sun.nio.ch.IOUtil.write(IOUtil.java:51)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:408)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:898)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1384)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:789)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:812)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1037)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:293)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:223)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at com.github.steveice10.mc.protocol.ClientListener.packetSent(ClientListener.java:128)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at com.github.steveice10.packetlib.event.session.PacketSentEvent.call(PacketSentEvent.java:51)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at com.github.steveice10.packetlib.tcp.TcpSession$1.operationComplete(TcpSession.java:227)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at com.github.steveice10.packetlib.tcp.TcpSession$1.operationComplete(TcpSession.java:223)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:183)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:223)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at com.github.steveice10.mc.protocol.ClientListener.connected(ClientListener.java:138)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:335)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:272)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1410)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:907)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at org.geysermc.platform.spigot.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> [01:16:06] [nioEventLoopGroup-2-2/WARN] []: at java.lang.Thread.run(Thread.java:748)

**Comment by rtm516** [comment]
We don't support forge/Magma and as I understand this is because it doesn't implement the full bukkit API and floodgate relies on reflection which won't work with it.
