### ISSUE TITLE
Custom Capes and Skin geometry

### ISSUE THREAD

**Issue by justlunix** [GeyserMC/Geyser#1807]
**What feature do you want?**
In Bedrock, there is an option to create custom capes (actual capes) as well as adding skin geometry data. (This does not work on Java)
I.e. see [here](https://github.com/pmmp/PocketMine-MP/blob/5b7b2dd0e22447b497e49e4412abd7a8822c8873/src/pocketmine/entity/Skin.php#L39).
I would like to have this option with Geyser, too.

**Alternatives?**
Java Edition plugins that use banners as capes, but they don't look as good & the performance is not very great.

**Comment by RednedEpic** [comment]
Out of the scope of the Geyser project. Likely better suited as an extension.
