### ISSUE TITLE
Java.IOException: Broken pipe

### ISSUE THREAD

**Issue by owlman5126** [GeyserMC/Geyser#1809]
**Describe the bug**
Bedrock players can not connect and get this error `Java.IOException: Broken pipe`

**To Reproduce**

1. Join the server on Bedrock
2. Wait to connect
3. See small flash of the world/void

**Expected behavior**
Player can join server and is put in the hub

**Screenshots / Videos**

none

**Server Version and Plugins**
```
[14:58:43 INFO]: This server is running Paper version git-Paper-253 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[14:58:43 INFO]: You are running the latest version
```
Waterfall
Viaversion 

**Geyser Dump**

 https://dump.geysermc.org/R49JOvxIa0hCBEFF8ObvZJn1vCRD9tuz

**Minecraft: Bedrock Edition Version**

v1.16.201(Android 10, Latest version of Minecraft.

**Additional Context**

I know this has been reported before but disabling ping passthrough doesn't fix it
**Config**
[Config](https://pastebin.com/1gJgpEbD)

**Comment by Camotoy** [comment]
Can you please provide your BungeeCord config and logs?

**Comment by owlman5126** [comment]
**Bungee Config**
https://pastebin.com/W3n2b20d

**Bungee Log**
https://pastebin.com/NW86G961

**Comment by Camotoy** [comment]
`proxy_protocol: false` this needs to be set to `true` in BungeeCord if you want to enable `use-proxy-protocol` in your Geyser config. This will break Java players joining, though.

If I might ask, why did you enable that setting?

(Closing this as the issue should be resolved)

**Comment by owlman5126** [comment]
I might of, I don't think I did. Thank You for helping
