### ISSUE TITLE
EquipmentSlot error when joining server

### ISSUE THREAD

**Issue by OutRite** [GeyserMC/Geyser#181]
**Describe the bug**
Upon connecting to the Geyser server, it errors out with "io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value 118 has no mapping for key class com.github.steveice10.mc.protocol.data.game.entity.EquipmentSlot.

**To Reproduce**
1. Set server to offline
2. Attempt to join Herobrine.org (a cracked server)
3. The error may occur

**Expected behavior**
The server to load the lobby.

**Server version**
Java Server version 1.15.2

**Geyser version**
Jenkins Build # 175

**Bedrock version**
v1.14.30

**Comment by RednedEpic** [comment]
> **Describe the bug**
> Upon connecting to the Geyser server, it errors out with "io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value 118 has no mapping for key class com.github.steveice10.mc.protocol.data.game.entity.EquipmentSlot.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Set server to offline
> 2. Attempt to join Herobrine.org (a cracked server)
> 3. The error may occur
> 
> **Expected behavior**
> The server to load the lobby.
> 
> **Server version**
> Java Server version 1.15.2
> 
> **Geyser version**
> Jenkins Build # 175
> 
> **Bedrock version**
> v1.14.30

Is the server you're trying to join by chance modded?

**Comment by OutRite** [comment]
It does have plugins, since its a network, but I'm not sure if it has any custom items. It can be connected to from a vanilla client without problems.

**Comment by RednedEpic** [comment]
I ask because under normal circumstances, there should be no mapping slot 118, let alone anything above 5 (0 is main hand, 1 is offhand, 2 is helmet, 3 is chestplate, 4 is leggings, and 5 is boots). Will require some more investigation.

**Comment by RednedEpic** [comment]
Unable to reproduce; perhaps related to #169.
