### ISSUE TITLE
Geyser- Spigot Not working with Java 11?

### ISSUE THREAD

**Issue by Turtley12** [GeyserMC/Geyser#1811]
**Describe the bug**

Geyser does not start up on java 11

**To Reproduce**

1. Run Geyser plugin on paper server using Java 11
2. get error

**Expected behavior**

Geyser Should start successfully and function (currently works on Java 8)

**Server Version and Plugins**

This server is running Paper version git-Paper-391 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

I would prefer not to give a list of plugins

**Geyser Version**
This server is running Geyser version 1.2.0-SNAPSHOT (git-master-894275b) (Java: 1.16.4, Bedrock: 1.16.100.60 - 1.16.200.56)

**Floodgate Version**
floodgate-bukkit version 1.0-SNAPSHOT

**Additional Context**
`06.01 00:25:50 [Server] INFO Enabling Geyser-Spigot v1.2.0-SNAPSHOT`
`06.01 00:25:50 [Server] INFO ******************************************`
`06.01 00:25:50 [Server] INFO Loading Geyser version 1.2.0-SNAPSHOT (git-master-894275b)`
`06.01 00:25:50 [Server] INFO ******************************************`
`06.01 00:26:05 [Server] ERROR Failed to start Geyser on <server ip>:19132`
there are more errors that I can provide if necessary

**Comment by Camotoy** [comment]
Are you on Shockbyte?

**Comment by Turtley12** [comment]
I am on Shockbyte for hosting

**Comment by Camotoy** [comment]
Please contact them asking how to setup Geyser with Shockbyte on Java 11. It appears that their setup with Geyser is still a little off.
