### ISSUE TITLE
Geyser not work on Paper

### ISSUE THREAD

**Issue by FlipGamesCze** [GeyserMC/Geyser#1813]
**Describe the bug**

Geyser isnt work on mobile

**Expected behavior**

I want to have my server on mobile, but its not work

**Screenshots / Videos**

here is message from console about starting geyser:
[10:22:13 INFO]: [Geyser-Spigot] ************************************ * ******
[10:22:13 INFO]: [Geyser-Pin]
[10:22:13 INFO]: [Geyser-Spigot] Loading Geyser version 1.2.0-SNAPSHOT (git-master-50b80a6)
[10:22:13 INFO]: [Geyser-Pin]
[10:22:13 INFO]: [Geyser-Spigot] ************************************ * ******
[10:22:15 INFO]: [Geyser-Spigot] Geyser turned on 192.168.170.17:19132
[10:22:15 INFO]: [Geyser-Spigot] Done (1,862 s)! Run / geyser help for help!

Geyser is not in LAN Games:
![04063f6c-b106-4ecf-9e03-7091950fe16e](https://user-images.githubusercontent.com/63102572/103752660-44da8a00-500a-11eb-99b0-519d28d2a39e.jpg)

I have added Geyser to my servers  on my lan ip:
![598eb53d-6e59-4be7-b464-a013970f2d81](https://user-images.githubusercontent.com/63102572/103752665-46a44d80-500a-11eb-834a-b5b5f174fbc4.jpg)

But its not working
![1aaf5293-b882-4150-aa95-8a0bea53a11d](https://user-images.githubusercontent.com/63102572/103752632-3b512200-500a-11eb-9faf-3afbb4b6dfc5.jpg)

**Server Version and Plugins**

This server is running Paper version git-Paper-253 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

plugins: Geyser-Spigot, RemoteChat*, SeePlayerInventory, ServerRestorer, ShulkerRespawner, SkinsRestorer, SkQuery, Skript, SuperLobby, TAB, TridentTweaks, VarLight, Vault, ViaBackwards, ViaVersion, VillagerLobotomizatorNator, VillagerOptimiser, VoidGenerator, WebConsole, WorldBorder, ZombieApocalypse

If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

**Geyser Dump**
{
    "versionInfo": {
        "name": "Geyser",
        "version": "1.2.0-SNAPSHOT (git-master-50b80a6)",
        "javaVersion": "1.8.0_271",
        "architecture": "amd64",
        "operatingSystem": "Windows 10",
        "operatingSystemVersion": "10.0",
        "network": {
            "internalIP": "***",
            "dockerCheck": false
        },
        "mcInfo": {
            "bedrockVersion": "1.16.200.5",
            "bedrockProtocol": 422,
            "javaVersion": "1.16.4",
            "javaProtocol": 754
        }
    },
    "gitInfo": {
        "git.tags": "",
        "git.commit.id.abbrev": "50b80a6",
        "git.commit.message.full": "Dimension switching cleanup (#1694)\n\n* Dimension switching cleanup\r\n\r\nCleans up dimension switching logic that should no longer be needed. Also fixes above Nether Bedrock building dimension switching.\r\n\r\n* Clear thunder on dimension switch too\r\n\r\n* Clarify fake dimension switch function name\r\n\r\n* Javadoc that",
        "git.commit.id": "50b80a64d3e8de39c82fa454453bcfd31bc544a7",
        "git.build.version": "1.2.0-SNAPSHOT",
        "git.total.commit.count": "1561",
        "git.branch": "master",
        "git.build.host": "ci",
        "git.local.branch.ahead": "NO_REMOTE",
        "git.commit.time": "2021-01-04T00:06:20+0000",
        "git.local.branch.behind": "NO_REMOTE",
        "git.build.number": "555",
        "git.dirty": "false",
        "git.remote.origin.url": "https://github.com/GeyserMC/Geyser.git",
        "git.build.time": "2021-01-04T00:07:20+0000"
    },
    "config": {
        "autoconfiguredRemote": true,
        "bedrock": {
            "address": "***",
            "port": 19132,
            "motd1": "MinePlay",
            "motd2": "MinePlay server for mobile",
            "clone-remote-port": false,
            "server-name": "MinePlay"
        },
        "remote": {
            "address": "***",
            "port": 25565,
            "auth-type": "offline",
            "use-proxy-protocol": false
        },
        "userAuths": null,
        "metrics": {
            "enabled": true,
            "uuid": "37686828-3a5e-47f6-9cbf-77f457354c1f"
        },
        "floodgate-key-file": "public-key.pem",
        "command-suggestions": true,
        "passthrough-motd": false,
        "passthrough-player-counts": false,
        "passthrough-protocol-name": false,
        "legacy-ping-passthrough": false,
        "ping-passthrough-interval": 3,
        "max-players": 5,
        "debug-mode": false,
        "general-thread-pool": 32,
        "allow-third-party-capes": true,
        "show-cooldown": true,
        "show-coordinates": true,
        "allow-third-party-ears": false,
        "default-locale": null,
        "cache-chunks": true,
        "cache-images": 0,
        "allow-custom-skulls": true,
        "above-bedrock-nether-building": false,
        "force-resource-packs": true,
        "xbox-achievements-enabled": false,
        "scoreboard-packet-threshold": 20,
        "enable-proxy-connections": false,
        "mtu": 1400,
        "use-adapters": true,
        "config-version": 4
    },
    "userPlatforms": {},
    "ramInfo": {
        "free": 5030,
        "total": 6753,
        "max": 6753
    },
    "bootstrapInfo": {
        "platform": "SPIGOT",
        "platformName": "Paper",
        "platformVersion": "git-Paper-253 (MC: 1.16.3)",
        "platformAPIVersion": "1.16.3-R0.1-SNAPSHOT",
        "onlineMode": false,
        "serverIP": "",
        "serverPort": 25565,
        "plugins": [
            {
                "enabled": true,
                "name": "RemoteChat",
                "version": "1.0",
                "main": "me.johnnywoof.remotechat.spigot.RemoteChat",
                "authors": [
                    "Johnnywoof"
                ]
            },
            {
                "enabled": true,
                "name": "SeePlayerInventory",
                "version": "2.7",
                "main": "me.peti446.SeePlayerInventory.SeePlayerInventory",
                "authors": [
                    "peti446"
                ]
            },
            {
                "enabled": true,
                "name": "VarLight",
                "version": "1.12.8",
                "main": "me.shawlaf.varlight.spigot.VarLightPlugin",
                "authors": [
                    "shawlaf"
                ]
            },
            {
                "enabled": true,
                "name": "TridentTweaks",
                "version": "1.0.0",
                "main": "com.darkender.plugins.tridenttweaks.TridentTweaks",
                "authors": [
                    "Techdoodle"
                ]
            },
            {
                "enabled": true,
                "name": "VoidGenerator",
                "version": "1.7.0",
                "main": "de.xtkq.voidgenerator.VoidGenerator",
                "authors": [
                    "xtkq"
                ]
            },
            {
                "enabled": true,
                "name": "VillagerOptimiser",
                "version": "1.1.5",
                "main": "com.froobworld.avl.Avl",
                "authors": [
                    "froobynooby"
                ]
            },
            {
                "enabled": true,
                "name": "VillagerLobotomizatorNator",
                "version": "1.5.1_1.16R3_256",
                "main": "merchant.genocide.villagerlobotomizatornator.VillagerLobotomizatorNator",
                "authors": [
                    "dr.doofenshmirtz"
                ]
            },
            {
                "enabled": true,
                "name": "ZombieApocalypse",
                "version": "1.2.2",
                "main": "com.ericdebouwer.zombieapocalypse.ZombieApocalypse",
                "authors": [
                    "ericdebouwer (3ricL)"
                ]
            },
            {
                "enabled": true,
                "name": "ShulkerRespawner",
                "version": "1.13_1.0.5",
                "main": "com.github.joelgodofwar.sr.ShulkerRespawner",
                "authors": [
                    "JoelGodOfWar(JoelYahwehOfWar)"
                ]
            },
            {
                "enabled": true,
                "name": "WebConsole",
                "version": "2.1",
                "main": "es.mesacarlos.webconsole.WebConsole",
                "authors": [
                    "Carlos Mesa"
                ]
            },
            {
                "enabled": true,
                "name": "ViaVersion",
                "version": "3.2.0",
                "main": "us.myles.ViaVersion.ViaVersionPlugin",
                "authors": [
                    "_MylesC",
                    "creeper123123321",
                    "Gerrygames",
                    "KennyTV",
                    "Matsv"
                ]
            },
            {
                "enabled": true,
                "name": "WorldBorder",
                "version": "1.9.10 (beta)",
                "main": "com.wimbli.WorldBorder.WorldBorder",
                "authors": [
                    "Brettflan"
                ]
            },
            {
                "enabled": true,
                "name": "ServerRestorer",
                "version": "1.0.39",
                "main": "me.zombie_striker.sr.Main",
                "authors": [
                    "Zombie_Striker"
                ]
            },
            {
                "enabled": true,
                "name": "Vault",
                "version": "1.7.3-b131",
                "main": "net.milkbowl.vault.Vault",
                "authors": [
                    "cereal",
                    "Sleaker",
                    "mung3r"
                ]
            },
            {
                "enabled": true,
                "name": "ViaBackwards",
                "version": "3.2.0",
                "main": "nl.matsv.viabackwards.BukkitPlugin",
                "authors": [
                    "Matsv",
                    "KennyTV",
                    "Gerrygames",
                    "creeper123123321",
                    "ForceUpdate1"
                ]
            },
            {
                "enabled": true,
                "name": "SuperLobby",
                "version": "4.2.9",
                "main": "com.pedrojm96.superlobby.SuperLobby",
                "authors": [
                    "PedroJM96"
                ]
            },
            {
                "enabled": true,
                "name": "SkinsRestorer",
                "version": "13.8.6",
                "main": "skinsrestorer.bukkit.SkinsRestorer",
                "authors": [
                    "Th3Tr0LLeR",
                    "McLive",
                    "DoNotSpamPls",
                    "knat"
                ]
            },
            {
                "enabled": true,
                "name": "Skript",
                "version": "2.5",
                "main": "ch.njol.skript.Skript",
                "authors": [
                    "Njol",
                    "Mirreski",
                    "bensku",
                    "TheBentoBox",
                    "FranKusmiruk",
                    "ShaneBeee",
                    "Blueyescat",
                    "JRoy",
                    "Nicofisi",
                    "APickledWalrus",
                    "xXAndrew28Xx",
                    "Syst3ms",
                    "TheLimeGlass",
                    "Pikachu920",
                    "Sashie",
                    "Wealthyturtle",
                    "OfficialDonut",
                    "eyesniper2"
                ]
            },
            {
                "enabled": true,
                "name": "TAB",
                "version": "2.8.8",
                "main": "me.neznamy.tab.platforms.bukkit.Main",
                "authors": [
                    "NEZNAMY"
                ]
            },
            {
                "enabled": true,
                "name": "Geyser-Spigot",
                "version": "1.2.0-SNAPSHOT",
                "main": "org.geysermc.platform.spigot.GeyserSpigotPlugin",
                "authors": [
                    "GeyserMC"
                ]
            },
            {
                "enabled": true,
                "name": "SkQuery",
                "version": "4.1.3",
                "main": "com.w00tmast3r.skquery.SkQuery",
                "authors": [
                    "LimeGlass",
                    "w00tmast3r"
                ]
            }
        ]
    }
}

**Minecraft: Bedrock Edition Version**

1.16.201
**Additional Context**

nothing

**Comment by rtm516** [comment]
Geyser should work with no issues on paper, its likely a firewall issue please see this wiki page and if you have further issues contact us via Discord.
https://github.com/GeyserMC/Geyser/wiki/Fixing-%22Unable-to-Connect-to-World%22
https://discord.geysermc.org/
