### ISSUE TITLE
Unmapped particles.

### ISSUE THREAD

**Issue by Extollite** [GeyserMC/Geyser#1817]
Listed particles are missing mappings in Geyser:

- `soul_flame`
- `falling_obsidian_tear`
- `soul`
- `flash`
- `falling_nectar`
- `falling_honey`

According to java wiki corresponding particles are:
- `minecraft:blue_flame_particle`
- `obsidian_tear_particle`
- `minecraft:soul_particle`
- `minecraft:flash`
- `minecraft:nectar_drip_particle`
- `minecraft:honey_drip_particle`

**Comment by Camotoy** [comment]
These should be fixed - either in the GeyserOptionalPack or their Bedrock equivalents.
