### ISSUE TITLE
Custom Skin (SkinRestorer, CustomSkin, MySkin) Crash Bedrock Player

### ISSUE THREAD

**Issue by Herossandro** [GeyserMC/Geyser#1820]
**Describe the bug**
When a player on bedrock tries to join in the server, it crashes because of skin plugin. I tried skin restorer, my skin, customskin and everytime the bedrock players crashes. I tried to remove them and everything worked fine. 

"Unable to load bedrock skin for 'Herossandro' as they are likely using a customised skin"

**To Reproduce**

1) Insert a skin plugin like skinrestorer in plugin folder of ther server
2) Start server
3) Minecraft Bedrock crash on join

**Expected behavior**
I want that every player can have their skin because the server is in online-mode false I need skin plugin to allow everybody to see their skin or set another one they want.

**Screenshots / Videos**

https://mega.nz/file/gK5EXSoA#ry8-DPlLh3KClOuTQQgZm54sS5QqJknZy6S2ISv2lEk

**Server Version and Plugins**

Version: 1.16.4

BotSentry
AECommunicate
Trade
ViaBackwards
NexEngine
worldguard
AntiAFK
CoreProtect
Vault
Shopkeepers
VotingPlugin
kitspreview
LPC
nuvotifier
GoldenCrates
LuckPerms
CombactLogX
ViaRewind
TAB
AnnouncementsEverywhere
FastAsyncWorledit
EssentialsXChat
HolographicDisplays
Buycraft
ViaVersion
RandomTeleport
LoginSecurity
EssentialsXSpawn
FastChunkPregenerator
EssentialsX
Geyser-Spigot
SkinRestorer (The problem)

If you just run Geyser-Spigot, you can leave this area blank as the next section covers this information.

If you're running a multi-server instance, or using Geyser Standalone:

- Give us the exact output from `/version` on all servers involved. Saying "latest" does not help us at all.
- Please list all plugins on all servers involved.

If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

**Geyser Dump**

https://dump.geysermc.org/LdT94fpQmGliOHpEGn3AHbkJeVvAD81R

**Minecraft: Bedrock Edition Version**

Tried:
1.16.201.2
1.16.200.2

**Additional Context**

**Comment by Camotoy** [comment]
Try removing TAB and see if your crashing problem goes away.

**Comment by Herossandro** [comment]
Thanks it seems it was TAB, now all works properly...
There is a solution for TAB plugin?

**Comment by Camotoy** [comment]
I'm going to close this because we are aware of an issue with TAB, but strangely I haven't been able to replicate it recently.

*However*, are you only crashing once you have applied a skin?
