### ISSUE TITLE
Smithing table not working

### ISSUE THREAD

**Issue by emanstress04** [GeyserMC/Geyser#1821]
**Describe the bug**

Smithing Table GUI not popup/working

**To Reproduce**

1. Go to 'inventory'
2. Search for 'smithing table'
3. Click on the crafting table

**Expected behavior**

Smithing Table GUI will popup and can be use

**Screenshots / Videos**

**Server Version and Plugins**
.

If you're running a multi-server instance, or using Geyser Standalone:

- Give us the exact output from `/version` on all servers involved. Saying "latest" does not help us at all.
- Please list all plugins on all servers involved.

If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

**Geyser Dump**

https://dump.geysermc.org/vv1PTOEGmR6I1LFfFnSEvkub8N45KUvd

**Minecraft: Bedrock Edition Version**

Minecraft Bedrock 1.16.201, MCPE Android and IOS

**Additional Context**

**Comment by iSilviu-debug** [comment]
Please Geyser, fix the Smithing Table, even with a remedy like the enchanting table

**Comment by mjcox244** [comment]
known issue

if i remember correctly there's an inventory rewright in the works

**Comment by mjcox244** [comment]
yep this is c clone of [#1077](https://github.com/GeyserMC/Geyser/issues/1077)

**Comment by Camotoy** [comment]
As such, I will be closing this issue. Thank you for reporting anyway! Make sure you're on our Discord to get the first opportunity to fix this.
