### ISSUE TITLE
Hebrew flipped

### ISSUE THREAD

**Issue by AdamPri** [GeyserMC/Geyser#1823]
**Describe the bug**
Because Hebrew is a right-to-left language, bedrock players see it flipped.

**To Reproduce**
Write something in Hebrew.

**Expected behavior**
Hebrew text appears the same, both on Java and Bedrock clients.

**Screenshots / Videos**

Java:

![Java](https://user-images.githubusercontent.com/73665382/104110077-0acaeb80-5289-11eb-8313-1261d795a650.png)

Bedrock:

![Bedrock](https://user-images.githubusercontent.com/73665382/104110080-0e5e7280-5289-11eb-8e24-30fb655d2b64.png)

**Server Version**
1.16.4

**Minecraft: Bedrock Edition Version**

Version 1.16.201, Windows 10

**Comment by Camotoy** [comment]
Thanks for submitting! Would you mind following the issue template to the best of your ability? (You can just start creating a new issue and copy the template from there)

**Comment by YHDiamond** [comment]
I speak hebrew and I can tell you that this is the most annoying thing that can happen with tech and hebrew. I did some of the translations to hebrew even. I'd have to test it with more things before I can see how to fix it.

**Comment by YHDiamond** [comment]
Just some news on this, turns out this is a bedrock client issue, but I will do my best to fix it. I have also opened a bug request in Minecraft bedrock Jira bug tracker thingy majig

**Comment by RednedEpic** [comment]
Closing as this is a client bug.
