### ISSUE TITLE
Dimension Crash Bug

### ISSUE THREAD

**Issue by Legit4K** [GeyserMC/Geyser#183]
**Describe the bug**
After entering the End Dimension, players will be stuck in a crash loop.

**To Reproduce**
1. Enter the End Dimension
2. Experience it all

**Expected behavior**
A successful transition into end dimension.

**Screenshots**
Unavailable

**Server version**
Latest PaperMC commit

**Geyser version**
Latest on new protocol lib branch

**Bedrock version**
1.14.30

**Additional context**
None for now.

**Comment by AJ-Ferguson** [comment]
Should be fixed when #156 is merged.

**Comment by RednedEpic** [comment]
Fixed in #156 which has been merged.

**Comment by Legit4K** [comment]
Crashing Still seems to occur (latest Inventory-Branch Build)
