### ISSUE TITLE
The possibility of ConcurrentModificationException

### ISSUE THREAD

**Issue by konradgab** [GeyserMC/Geyser#1830]
With 100 clients connected there is possibility to ConcurrentModificationException occure in the line below.

https://github.com/GeyserMC/Geyser/blob/fb283fcce8600eca01c777d0df94217e978f1413/connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java#L373

While running performance tests, we encountered this exception when we connected/disconnected 100 clients to the server in quick succession.

**Comment by Camotoy** [comment]
Could you try PR #1831?

> To download a PR/pull request:
1. Make sure you are signed in with a GitHub account
2. Follow the pull request link that was sent to you
3. Follow the guide on this picture: https://i.ibb.co/tCcB1Qp/PR1.png

**Comment by konradgab** [comment]
Yeah, sure

**Comment by konradgab** [comment]
Oh mb, I wasn't accurate enough. Exeception is thrown from forEach which is executed on player list. Not emotes set.

**Comment by Camotoy** [comment]
Ah, still an easy fix. Hold on.

**Comment by Camotoy** [comment]
Try again after the latest commit has built. It should take about five-to-ten minutes.

**Comment by konradgab** [comment]
We considered about this solution. We will testing this.

**Comment by Extollite** [comment]
Tested with #1831 and looks like it is fixed.
