### ISSUE TITLE
Animation with different tier tools is incorrect

### ISSUE THREAD

**Issue by Extollite** [GeyserMC/Geyser#1837]
**Describe the bug**

Cannot break iron ore with wooden pickaxe.

**To Reproduce**

1. Find iron ore.
2. Break it with wooden pickaxe.
3. It stays in place.

**Expected behavior**

Blocks break but doesn't give ore.

**Screenshots / Videos**

https://streamable.com/w87ulz

**Geyser Dump**

https://dump.geysermc.org/qwjO2aUOGTQpRpGO3JHJ4SlUi9YSTbha

**Minecraft: Bedrock Edition Version**

1.16.201 android.

**Comment by Camotoy** [comment]
I suspect what is happening is not that you cannot break the ore, but that the break math is off. Try holding down on the block even after the break animation has ended.

**Comment by Extollite** [comment]
Indeed animation is broken.

**Comment by SyzuTopia54y** [comment]
Hey you you want the iron ore ? Just use stone or iron pickaxe if use wooden pickaxe never drop iron😂😂😂

**Comment by Camotoy** [comment]
This is not the focus of this issue.

**Comment by YHDiamond** [comment]
How would this be fixable?

**Comment by Camotoy** [comment]
Our block breaking calculation doesn't consider if the current tool tier can break the block.

I have a fix locally, but also I tried to fix haste speedmining to no avail.

**Comment by YHDiamond** [comment]
What is your local fix if I may ask?

**Comment by Camotoy** [comment]
I add in a property in our mappings if a block requires a higher tool tier, and then factor that into the math for block breaking.

**Comment by YHDiamond** [comment]
is this PRable?

**Comment by Camotoy** [comment]
I will either PR it separately or try to fix the haste speedbreaking issue.

If you have any other questions about its release, please refer yourself to the output of `!!eta` in the Geyser Discord.

**Comment by YHDiamond** [comment]
Ok bro I know that I am not questioning everything about it I just wanted to know if your fix was something that was possible to PR, I believe it will be done knowing how you work :)

**Comment by Camotoy** [comment]
There is code that currently exists that I have written to fix it, if that's what you're asking.

**Comment by Camotoy** [comment]
This will be fixed in 1.17, as the server should now control this instead of hardcoded mappings.

**Comment by YHDiamond** [comment]
Is this currently in a snapshot or was it announced and not implemented yet

**Comment by Camotoy** [comment]
It is currently in a snapshot. 21w19a:

> Added needs_stone_tool, needs_iron_tool and needs_diamond_tool block tags. If a block requires the correct tool to drop, these tags determine which tier of that tool is required.

**Comment by YHDiamond** [comment]
Ah nice.
Do you plan to wait for 1.17?

Mojang might delete that feature cuz they already deleted half the snapshot /s

**Comment by Camotoy** [comment]
Mojang has not removed any technical capability from the snapshot yet, nor do I expect them to.

**Comment by YHDiamond** [comment]
Yes that was a joke, I will stop commenting now

**Comment by Camotoy** [comment]
Fixed in 1f83a5a.
