### ISSUE TITLE
Add GUI support

### ISSUE THREAD

**Issue by mcdudu233** [GeyserMC/Geyser#184]
**What feature do you want?**
I want to open the chest and menu.

**Comment by jackson-57** [comment]
this is already implemented in #67.

**Comment by mcdudu233** [comment]
> this is already implemented in #67.

But I can't open the GUI.
I am using 1.14.2.

**Comment by jackson-57** [comment]
Are you using the master branch or the inventory PR build?

**Comment by mcdudu233** [comment]
> Are you using the master branch or the inventory PR build?

I am using the lastest master branch.

**Comment by jackson-57** [comment]
Ah, that'd be the problem. Download the Inventory PR build by going to https://github.com/GeyserMC/Geyser/pull/67/checks and clicking on Geyser.jar under the Artifacts drop down.

**Comment by mcdudu233** [comment]
> Ah, that'd be the problem. Download the Inventory PR build by going to https://github.com/GeyserMC/Geyser/pull/67/checks and clicking on Geyser.jar under the Artifacts drop down.

Oh, thank you.
