### ISSUE TITLE
Bug with the visual of Multicraft

### ISSUE THREAD

**Issue by DjeyMute** [GeyserMC/Geyser#1843]
Hello,
I have had a problem with my visual of Multicraft and Geyser pannel for several months now.
Everything works fine the only problem is the display on Multicraft.
Multicraft tells me that the Geyser server is off and when I click on it it tells me that it is turning on while everything is working fine.

**The main menu :**
![1](https://user-images.githubusercontent.com/47302852/104816621-aece0d00-581c-11eb-96c8-ce6255b98fcc.png)

**In the geyser :**
![2](https://user-images.githubusercontent.com/47302852/104816623-b1306700-581c-11eb-97fc-6936f3620565.png)

Thank you in advance.

Version of Geyser : Build 586

**Comment by rtm516** [comment]
This isn't a Geyser issue but in fact and issue with Multicraft. It will check for a certain string to indicate that the server has started and that will only be present in Minecraft servers so it won't know when it's finished starting. If you would like to use a panel with Geyser then we suggest moving over to Pterodactyl panel which we have premade configurations for it.
https://github.com/GeyserMC/pterodactyl-stuff/
