### ISSUE TITLE
Real DualWield by LoneDev

### ISSUE THREAD

**Issue by AnhvietPlays** [GeyserMC/Geyser#1844]
**Describe the bug**

The "Real DualWield" plug-in by 'LoneDev' doesn't allow BEDROCK players/client to put a weapon or tool in the shield slot in the GUI. Works fine for JAVA players/client. 

**To Reproduce**

1. Go to a Spigot/Paper server with GeyserMC and Real DualWield plug-ins installed while using a BEDROCK client.
2. Click on 'equipment GUI'
3. Try 'to put a weapon or sword in the shield slot'
4. See error 'GUI doesn't allow anything beside a shield in this slot'

**Expected behavior**

Weapons like sword or tools like pickaxe will not go inside the GUI slot. Shield can go inside. 

**Screenshots / Videos**

N/A

**Server Version and Plugins**

Paper 1.16.4 running Geyser-Spigot

**Geyser Dump**

N/A

**Minecraft: Bedrock Edition Version**

WINDOW 10 1.16.201
PS4 1.16.201
PS5 1.16.201

**Additional Context**

N/A

**Comment by Camotoy** [comment]
Unfortunately, this is a Bedrock limitation and nothing we can do - only shields, totems and fireworks (perhaps other items, but they have specific properties) are permitted in that slot. In the meantime, `/geyser offhand` will swap your main hand and offhand.

Sorry, but thanks for reporting an error!
