### ISSUE TITLE
Scoreboard doesnt shrink down after it resizes to a bigger one.

### ISSUE THREAD

**Issue by MrRazamataz** [GeyserMC/Geyser#1845]
**Describe the bug**
If the scoreboard gets bigger to show some info, it doesnt then shrink back to what it should be, instead, it stays big and takes up a lot of space.

**To Reproduce**

Have a scoreboard with (eg) a placeholder.
Make the placeholder value long.
Scoreboard on bedrock stretches to fit it.
Make the placeholder value shorter.
Scoreboard on bedrock stays long.
**Expected behaviour**
Its meant to resize back to the shorter vaule.

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/56600481/104939742-b5898b00-59a8-11eb-89ac-d7beb661df3f.png)

**Server Version and Plugins**

If you just run Geyser-Spigot, you can leave this area blank as the next section covers this information.

If you're running a multi-server instance, or using Geyser Standalone:

Its Geyser Spigot
- Please list all plugins on all servers involved.
Plugins: 
AuctionHouse, AutoAnnouncer*, ChatFormat*, ChestShop, CombatLogX, CoreProtect, DeathMessagesPrime, DiscordSRV, Essentials, EssentialsGeoIP, EssentialsSpawn, floodgate-bukkit, Geyser-Spigot, Graves, HelpMe*, HolographicDisplays, Join-Leave*, LiteBans, LuckPerms, NoCheatPlus, OldCombatMechanics, PlaceholderAPI, Plan, PlayerWarps, PlugMan, ProtocolLib, Residence, Scoreboard-revision*, ServerlistMOTD*, SimplePets, SkQuery, Skript, Slabbo, StaffChat*, TAB, Vault, WelcomeTitle*, WorldBorder, Worldstats*
If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

**Geyser Dump**

https://dump.geysermc.org/Pra5bUEjRNWYpdSXNgUGfL9Nea3m4C22

**Minecraft: Bedrock Edition Version**

Windows 10, 1.16.201

**Comment by Chew** [comment]
Sadly the scoreboard width is Bedrock's behavior. Hopefully, this is a bug that has been patched since this issue was reported, but this isn't anything Geyser can fix. Thank you for the report, however!
