### ISSUE TITLE
/playsound command not working on bedrock using command blocks (in console works fine)

### ISSUE THREAD

**Issue by Aushyro** [GeyserMC/Geyser#1847]
**Describe the bug**

Some of the sounds are not playing on bedrock clients when using them in commandblocks. Like following commands:
/playsound minecraft:entity.ender_dragon.flap ambient @a[distance=..45] -278 67 334 3 1
/playsound minecraft:entity.generic.explode ambient @a[distance=..30] -321 52 298 1 1 0.1

**To Reproduce**

Put

/playsound minecraft:entity.ender_dragon.flap ambient @a[distance=..45] -278 67 334 3 1

or

/playsound minecraft:entity.generic.explode ambient @a[distance=..30] -321 52 298 1 1 0.1

in a command block (change coordinates as you desire). The sound is played on Java clients, but not Bedrock clients.

**Expected behavior**

Hear the sound in the given range (45 or 30)

**Screenshots / Videos**

-

**Server Version and Plugins**

Geyser build 589 is running on Bungeecord build 1543

**Geyser Dump**

https://dump.geysermc.org/yNEvp1Wil0dgJdlvJ2Fn6jwAfecfodBG

**Minecraft: Bedrock Edition Version**

Minecraft Bedrock on Windows 10 v 1.16.201

**Comment by YHDiamond** [comment]
I'd say first try testing to make sure that if you do this near Java they can hear it.

**Comment by RednedEpic** [comment]
Stale + unable to reproduce. Closing.
