### ISSUE TITLE
[Question] IPs used by Geyser

### ISSUE THREAD

**Issue by bobhenl** [GeyserMC/Geyser#1848]
Hi, I just wanna ask question, what all IPs are used by Geyser? I have to manually allow them, now I discovered it's not only 172.18.0.5, but it's 172.18.0.2 too. What are next please? I'm using SecuredNetwork plugin and I have to whitelist these ips to allow them joining

**Comment by Camotoy** [comment]
Geyser doesn't use any specific set of IPs - it likely depends on what your `remote` `address` is set to.

**Comment by bobhenl** [comment]
```
remote:
  # The IP address of the remote (Java Edition) server
  # If it is "auto", for standalone version the remote address will be set to 127.0.0.1,
  # for plugin versions, Geyser will attempt to find the best address to connect to.
  address: auto
```

Should I rather set there some number? If yes, what do you suggest?

**Comment by Camotoy** [comment]
No, leave that as-is.

Is there a wildcard system in SecuredNetwork? If so, it appears you can allow any IP that starts with 172.18.0.* as these will never be external IPs.
