### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by bobhenl** [GeyserMC/Geyser#1849]
**Describe the bug**

Hi, when I'm joining, I'm getting this error sometimes and then message that I can't join to this world (to whole server).
https://pastebin.com/VpLRudV4

**To Reproduce**

Sorry, don't know, but see error please.

**Expected behavior**

It should work.

**Server Version and Plugins**
![image](https://user-images.githubusercontent.com/18662086/105053153-ef25c900-5a70-11eb-81c9-69d2e6062017.png)
(used paper before)

`[16:12:10 INFO]:  Plugins: AdvancedPortals, CMDispatcher, ChatDisable, ConsoleSpamFix, HackedCore, HackedServer, HamsterAPI, HoloInfo, HolographicDisplays, JukeBox, Kotlin4MC, LagAssist, LuckPerms, NoteBlockAPI, PacketLimiter, Plan, ProtocolLib, SecuredNetwork, ServerUtils, Sockets4MC, Vault, ViaBackwards, ViaBoundingBox, ViaCheckConnection, ViaRewind, ViaVersion and Winter`

**Geyser Dump**
https://dump.geysermc.org/47CGj9oZ2gWrrlqwSOQA041jsSZ2cSy0

**Minecraft: Bedrock Edition Version**
1.16.201

**Additional Context**

Anything else

**Comment by Camotoy** [comment]
This is the same error present in your issue #1974. Please follow the instructions I asked in my last comment there. Thank you!
