### ISSUE TITLE
CustomPotionColor doesn't work on Bedrock

### ISSUE THREAD

**Issue by lukp0t** [GeyserMC/Geyser#1850]
**Describe the bug**

When you give a potion using the /give command with an integer tag CustomPotionColor, the color of potion on Bedrock remains the default.

**To Reproduce**

1. Start the server.
2. Join it from Bedrock.
3. Enter the command /give ... potion with the CustomColorPotion tag (for example: /give NickName potion 1 0 {Potion:"water",CustomPotionColor:16777215,CustomPotionEffects:[{Id:9,Duration:60}],display:{Name:"Custom Name"}})
4. The potion will have the default color.

**Expected behavior**

The potion was expected to have the color specified in the command.

**Screenshots / Videos**

https://prnt.sc/x8clxi Java
https://prnt.sc/x8cny5 Bedrock

**Server Version and Plugins**

Paper version git-Paper-368 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Geyser version 1.2.0-SNAPSHOT (git-master-16fdf51) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201)

There are no plugins that change potions.

**Geyser Dump**

...

**Minecraft: Bedrock Edition Version**

Tested with Bedrock 1.16.201 (Android)

**Additional Context**

...

**Comment by EasyClifton** [comment]
Bedrock doesn't support colored potions.

**Comment by RednedEpic** [comment]
Moving to current limitations page on wiki; closing.
