### ISSUE TITLE
Weird item stack amount when giving from Creative window

### ISSUE THREAD

**Issue by bobhenl** [GeyserMC/Geyser#1853]
**Describe the bug**

Hi, when you try to give yourselves item in creative mode, the behavior is really weird.

**To Reproduce**

1. Use /gm 1 on Bedrock.
2. Try to put some item into your inventory
![image](https://user-images.githubusercontent.com/18662086/105116381-f4176680-5aca-11eb-86e6-ecc4e5cbea8b.png)
3. You will see this
![image](https://user-images.githubusercontent.com/18662086/105116402-fed1fb80-5aca-11eb-8914-6362e9c46591.png)
But in inventory when you close you will see this
![image](https://user-images.githubusercontent.com/18662086/105116536-3f317980-5acb-11eb-8ed0-ac969b560841.png)
4. Turn back /gm 0 and you will see again 64 of them
![image](https://user-images.githubusercontent.com/18662086/105116551-46588780-5acb-11eb-8192-e5e01ec5cb40.png)

**Expected behavior**

It should probably show 64 even in Creative inventory.

**Server Version and Plugins**
![image](https://user-images.githubusercontent.com/18662086/105053153-ef25c900-5a70-11eb-81c9-69d2e6062017.png)
(used paper before)

**Geyser Dump**
https://dump.geysermc.org/47CGj9oZ2gWrrlqwSOQA041jsSZ2cSy0

**Minecraft: Bedrock Edition Version**
1.16.201

**Additional Context**

Anything else

**Comment by Camotoy** [comment]
This is just how Bedrock works (I think the logic behind it is that, in creative, you don't need to worry about quantities?). Nothing we can fix, sorry! Thanks anyway for reporting an issue.

**Comment by bobhenl** [comment]
Oh, ok, but it looked a little bit weird. Sorry for wrong issue

**Comment by Camotoy** [comment]
Generally, if it also happens in Bedrock without Geyser, we might not be able to fix it.
