### ISSUE TITLE
[Question] Suggestions of arguments?

### ISSUE THREAD

**Issue by bobhenl** [GeyserMC/Geyser#1854]
Hi, just question cause I don't know normal behavior, but shouldn't be there suggested arguments when someone uses for ex /warp?
![image](https://user-images.githubusercontent.com/18662086/105116753-a0594d00-5acb-11eb-9b43-03cc48c6873c.png)

**Comment by Camotoy** [comment]
If I had to guess, it might not be possible if that's sent on-the-fly. I *could* be very wrong.

**Comment by bobhenl** [comment]
but it seems that arguments aren't anywhere

**Comment by RednedEpic** [comment]
Fairly confident this is a limitation with the command protocol, so there isn't much we can do here. Adding to the current limitations wiki page.

**Comment by Camotoy** [comment]
Plugins can implement Minecraft's Brigadier library which will allow Bedrock players to see things correctly.
