### ISSUE TITLE
request: client render distance value passed through to java server

### ISSUE THREAD

**Issue by heathfx** [GeyserMC/Geyser#1860]
**What feature do you want?**
So, I'm testing with viewDistanceCat on 1.16.5 and the java client behaves as expected showing the unticked chunks all the way out to my configured view distance of 20 chunks. When I play on bedrock, using geyser (i've tested both the spigot plugin and standalone), I am only sent chunks that are ticking. If I use paper's built-in unticked chunks feature, it works, but then I miss out on the main reason for using viewDistanceCat. It only sends the chunks required by the client's render distance instead of blindly sending all of them, this saves bandwidth (especially for players with poor internet) and allows me to set per-player unticked view distances. Is there any way for geyser to read the client side render-distance setting on bedrock and forward that to the java edition server?

**Alternatives?**
none

**Comment by Camotoy** [comment]
This has been resolved with https://github.com/GeyserMC/Geyser/commit/8a93f6a116e423db0716938b7057417398b20da0.
