### ISSUE TITLE
Lightning does not have sound

### ISSUE THREAD

**Issue by GoldenMyst** [GeyserMC/Geyser#1862]
**Describe the bug**
When lightning struck, there is no sound

**To Reproduce**

1. Put your Volume up to MAX
2. Strike lightning close to player
3. Listen

**Expected behavior**

Lightning should have sound

**Screenshots / Videos**

**Server Version and Plugins**.
v1.16.5

**Geyser Dump**

**Minecraft: Bedrock Edition Version**
1.16+ (phone)

**Additional Context**

**Comment by YHDiamond** [comment]
Can you provide a video? I think I have heard lightning from Bedrock before. I can try to do some more testing.

**Comment by GoldenMyst** [comment]
> Can you provide a video? I think I have heard lightning from Bedrock before. I can try to do some more testing.

https://filebin.net/9bb7dnq6qpcgjyaa/IMG_6052.TRIM.MOV?t=dj0qnoip
