### ISSUE TITLE
Receiving lot of Ignoring team tm-sb-1. It overrides without removing old team.

### ISSUE THREAD

**Issue by Gladorme** [GeyserMC/Geyser#1865]
**Describe the bug**

The console is spammed of: **Ignoring team tm-sb-1. It overrides without removing old team.** 
When the scoreboard is updated with new placeholders value. The scoreboard is created with TitleManager.

**To Reproduce**

1. Install TitleManager
2. Connect to the serveur with Bedrock edition
3. Enable scoreboard (/tm scoreboard toggle). If no error maybe add a placeholder that can update itself.
4. See info message: **Ignoring team tm-sb-_X_. It overrides without removing old team.** in the console.

**Expected behavior**

To not receive print info messages. It's seems like debug message for me.

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/5657041/105639217-44017f00-5e77-11eb-8f51-76e27c8e16af.png)
(Messages spamming in the console in french)

**Server Version and Plugins**

Serveur: Purpur build 960 (1.16.5)
GeyserMC: 1.2.0-SNAPSHOT (git-master-5a8604f) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201)
TitleManager: 2.3.1

**Minecraft: Bedrock Edition Version**

Windows 10 Bedrock Edition, but also get the error on other platform like iOS. Probably Android too.

**Additional Context**

Similar issue: #1544

**Comment by Tim203** [comment]
This is a problem with your scoreboard plugin, please contact the scoreboard plugin developer or use an alternative to fix this

**Comment by Gladorme** [comment]
The scoreboard is working fine. Maybe not the best way. But still it's a debug message for me.

**Comment by Tim203** [comment]
The Java client logs this as well (as a fatal error instead of the info message we use), so I think that it's good to let the scoreboard plugin developers know that it shouldn't be done this way.

**Comment by Tim203** [comment]
![r47ssbvaez1yp646](https://user-images.githubusercontent.com/14874493/105640433-59c67280-5e7e-11eb-9013-86746b3a4e7e.png)

**Comment by Gladorme** [comment]
Okay, thanks for the additionnal info!
