### ISSUE TITLE
Bedrock Player get instantly timeouted on join with TAB Plugin

### ISSUE THREAD

**Issue by gameusefly** [GeyserMC/Geyser#1867]
**Describe the bug**

If i join as bedrock player on my server on beginning is all fine, but i get instantly timeouted from the server.

**To Reproduce**

The Server have to run the TAB Plugin (https://www.spigotmc.org/resources/tab-1-5-x-1-16-4.57806/)

1. Join Server with Geyser Standalone, Geyser Spigot Plugin and the TAB Plugin 
2. Loading World
3. Get timeouted
4. See error on Geyser Standalone (Packet violation warning sent from client! PacketViolationWarningPacket(type=MALFORMED_PACKET, severity=FINAL_WARNING, packetCauseId=76, context=))

**Expected 

That i can join my server without to get timeouted

**Geyser Dump**

https://dump.geysermc.org/CMCoPNIEdkY0vdeIafX7i9uFEK2ZhgEP

**Minecraft: Bedrock Edition Version**

1.16.201 Windows 10

**Comment by Camotoy** [comment]
I was able to download TAB and this person's configuration, but I was unable to replicate the same error. It might be another plugin in combination with TAB that interferes here.

**Comment by Xyntexx** [comment]
I have this bug too. Both on spigot and paper 1.16.5

https://dump.geysermc.org/17vqtZJ8b0dhLQuZGtXsoj4vtOfxSrXp

Geyser Dump
Minecraft: Bedrock Edition Version

1.16.201 Windows 10

**Comment by Camotoy** [comment]
Please also share your TAB config(s).

**Comment by Xyntexx** [comment]
geyser is running on bungeecord and 2 other servers in the network working fine with almost identical configurations.
[animations (3).yml.txt](https://github.com/GeyserMC/Geyser/files/6072359/animations.3.yml.txt)
[bossbar.yml.txt](https://github.com/GeyserMC/Geyser/files/6072360/bossbar.yml.txt)
[config (8).yml.txt](https://github.com/GeyserMC/Geyser/files/6072361/config.8.yml.txt)
[translation.yml.txt](https://github.com/GeyserMC/Geyser/files/6072362/translation.yml.txt)

**Comment by Xyntexx** [comment]
the error disappeared randomly

**Comment by GoldenMyst** [comment]
> the error disappeared suddenly

I had the same issue, to fix it I just disable `classic-vanilla-belowname` in the `config.yml`

**Comment by Jens-Co** [comment]
Hello @gameusefly, are you still having problems on this issue? If so please get back to us, Since Camotoy was unable to replicate this error I will close it in a few days.

**Comment by gameusefly** [comment]
I dont have this issue but i deleted the TAB Plugin and created a own Tab System Plugin. Thanks for the help!
