### ISSUE TITLE
Right clicking inventory does not act as expected for plugin

### ISSUE THREAD

**Issue by terikan** [GeyserMC/Geyser#1868]
Geyser plugin for Spigot.

Plugin MythicDrops

Use: Grab item from inventory (gem), move on top of other item (armor with socket), right click to combine.

Intended effect: Activates special plugin function. Works on JE

What happens on bedrock: items switch places, one goes to the cursor, the other into an inventory slot.

**Comment by Camotoy** [comment]
Unfortunately, this is a can't fix - there is no way to determine if a client is left-clicking or right-clicking on a spot. 
In the future, please follow the issue template.
Thank you for reporting anyway!
