### ISSUE TITLE
Cant see javaplayers players

### ISSUE THREAD

**Issue by Conclavice** [GeyserMC/Geyser#1871]
**Describe the bug**

bedrock players cant see java players. its a personally hosted server. its a survival server

**To Reproduce**

1. join the server 
2. look at where a java player should be

**Expected behavior**

Java Players won't appear on bedrock players screens

**Screenshots / Videos**

**Server Version and Plugins**

If you're running a multi-server instance, or using Geyser Standalone:

- Give us the exact output from `/version` on all servers involved. Saying "latest" does not help us at all.
- Please list all plugins on all servers involved.

![image](https://user-images.githubusercontent.com/70980664/105931421-054b0080-6000-11eb-934d-d540aba1721f.png)

![image](https://user-images.githubusercontent.com/70980664/105931386-f2383080-5fff-11eb-8330-5c77024ba309.png)

If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

**Geyser Dump**

If Geyser starts correctly, please also include the link to a dump by using `/geyser dump`. If you use the Standalone GUI, the option can be found under `Commands` => `Dump`. This provides us information about your server that we can use to debug your issue.

https://dump.geysermc.org/6eU9MESBYnA9Cj37rSZHKkrQNXiKlPlM

The version of your Minecraft: Bedrock Edition client you tested with, along with your device type (e.g. Windows 10, Switch...).

Mobile. not sure on what else

EDIT: I'm an idiot and didn't realise I was vanised. sorry about that

**Comment by Camotoy** [comment]
Please also attach logs of a Bedrock player and a Java player joining.

**Comment by Conclavice** [comment]
> Please also attach logs of a Bedrock player and a Java player joining.
