### ISSUE TITLE
Cant see bedrock players skin

### ISSUE THREAD

**Issue by Conclavice** [GeyserMC/Geyser#1872]
when I'm in java edition I cant see bedrock skins

when I'm in java edition I cant see bedrock skins

1. Go to a server with geyser on java
2. Look at a bedrock player

Shown as a steve skin

Bedrock Veiw
![image](https://user-images.githubusercontent.com/70980664/105937738-06cdf600-600b-11eb-9c0a-627c3819c58a.png)

Java view
![image](https://user-images.githubusercontent.com/70980664/105938010-8eb40000-600b-11eb-905a-40cff62810a5.png)

If you just run Geyser-Spigot, you can leave this area blank as the next section covers this information.

If you're running a multi-server instance, or using Geyser Standalone:

- Give us the exact output from `/version` on all servers involved. Saying "latest" does not help us at all.
- Please list all plugins on all servers involved.

![image](https://user-images.githubusercontent.com/70980664/105938117-c622ac80-600b-11eb-9c07-50515f112e6b.png)

If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

https://dump.geysermc.org/828DVfmhtGHVXCgBp08xHDz3NGzV0I3a

If Geyser starts correctly, please also include the link to a dump by using `/geyser dump`. If you use the Standalone GUI, the option can be found under `Commands` => `Dump`. This provides us information about your server that we can use to debug your issue.

**Minecraft: Bedrock Edition Version**

Windows 10 on an msi laptop

**Additional Context**

**Comment by Camotoy** [comment]
This will be fixed in the future with a Floodgate plugin update. Stay tuned!

**Comment by thebikwirm** [comment]
Has this been updated
