### ISSUE TITLE
Chunks Not loading Properly

### ISSUE THREAD

**Issue by SourceadminYT** [GeyserMC/Geyser#1876]
Hello Gyser, I've run into this issue several times and no longer have any idea on how to fix it.

Recently, I tried to make geyser work for my java Minecraft server, so bedrock players could join.

However, my testing wasn't very successful, as I had almost no issues with players joining the server, but with people actually playing on it. 

I'll attach screenshots of this issue, but it's very weird, and nothing I've ever seen before, and has happened across the following clients (on different networks)

Ps4 Bedrock (new)

Mobile Bedrock

Xbox One Bedrock (new)

Nintendo Switch Bedrock (newest)

Minecraft Windows 10 Edition (newest)

I had a couple plugins installed that I thought might have effected my server, so I removed them.

However, they didn't fix the issue.

I removed ViaVersion, ViaRewind, and ViaBackwards, along with a custom VPN/Proxy Guard plugin.

I even turned on "allow proxy connections" in my configuration file for the java server.

(and I'm using floodgate to allow players to join if that makes a difference) 

![unknown](https://user-images.githubusercontent.com/69773691/106069362-60e4bf00-60d0-11eb-9116-1caed19ce8ad.png)

**Comment by Konicai** [comment]
This is a bedrock client issue

https://minecraft.gamepedia.com/Bedrock_Edition_distance_effects

**Comment by SourceadminYT** [comment]
Oh okay, I'll move my spawn to 0,0

**Comment by Camotoy** [comment]
Thank you for reporting an issue anyway!
