### ISSUE TITLE
Errors in RakNet when trying to join and Unable To Connect to World

### ISSUE THREAD

**Issue by TSP1257** [GeyserMC/Geyser#1878]
**Describe the bug**
When i start the server and join it through geyser (The plugin version) it immediantly says both in offline and online that there's a issue with RakNet and then Unable To Connect To World 

**To Reproduce**
I just installed the latest Geyser Plugin and changed the port to what my server port in both remote port and bedrock port. (The IP's were on 0.0.0.0 and auto in java/remote)

**Expected behavior**
I expected issues, but i have tried everything that's everybody told me to do including using a PR

**Screenshots / Videos**
*Too long, it will be a ton of screenshots so i am going to send a little bit of the logs*
https://mclo.gs/M2QY9DO

**Server Version and Plugins**
I just ran Only geyser-spigot yesterday and it didn't work, now it doesn't work aswell with all of the plugins
If you just run Geyser-Spigot, you can leave this area blank as the next section covers this information.

If you're running a multi-server instance, or using Geyser Standalone:

- Give us the exact output from `/version` on all servers involved. Saying "latest" does not help us at all.
- Please list all plugins on all servers involved.

If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

**Geyser Dump**
https://dump.geysermc.org/kZOQjJXf8mJ2r7zmu5THQr7TYP5uL9JV

If Geyser starts correctly, please also include the link to a dump by using `/geyser dump`. If you use the Standalone GUI, the option can be found under `Commands` => `Dump`. This provides us information about your server that we can use to debug your issue.

**Minecraft: Bedrock Edition Version**
Windows 10, v1.16.201
The version of your Minecraft: Bedrock Edition client you tested with, along with your device type (e.g. Windows 10, Switch...).

**Additional Context**

My server is hosted on Shockbyte, i have already tried almost all possibilities (someone from your discord server helped me) and nothing worked, also it has worked on standalone 
EDIT/UPDATE: I checked on Port 19132, seems to not give the error but still it won't log me in

**Comment by Hellohi3654** [comment]
If your server is offline then make sure that in the geyser config it's set to offline and if it's online set it too online 
Also if you want to allow any players to join your online server with or without a Java account use floodgate and then set in the geyser config to floodgate

**Comment by TSP1257** [comment]
@Hellohi3654  Have done that already in the config  so it won't help

**Comment by Camotoy** [comment]
Try https://github.com/GeyserMC/Geyser/pull/1775.

To download a pull request (or a "PR") you need to:
1. Make sure you are signed in with a GitHub account
2. Follow the pull request link that was sent to you
3. Follow the guide on this picture: https://images-ext-2.discordapp.net/external/GTXJkSGA22bfKu6zbE4IOCFeJ6GVN_O2RtGXx3mOcLM/https/i.ibb.co/tCcB1Qp/PR1.png?width=340&height=300

**Comment by TSP1257** [comment]
@Camotoy nope, already did already didn't work

**Comment by YHDiamond** [comment]
Are there any odd network settings you have on the device? (Also nice to see someone that speaks Hebrew too 👋)

**Comment by TSP1257** [comment]
@YHDiamond If you're talking about my PC (The plugin is hosted on Shockbyte) then i don't think so, because on standalone i am able to log in.

**Comment by HandyHat** [comment]
Not sure if you are still having an issue, but if you are using Java 8 on Shockbyte your Geyser Bedrock address needs to be your Java Server IP, as detailed here: https://github.com/GeyserMC/Geyser/wiki/Supported-Hosting-Providers

**Comment by Chew** [comment]
Hey there! The aforementioned PR has been merged. Can you see if you're still having issues with the latest build? It also looks like the above person has a suggestion for you to try as well.

**Comment by RednedEpic** [comment]
Closing due to lack of response and no future reports about this.
