### ISSUE TITLE
Mobile Players Often Can't Connect

### ISSUE THREAD

**Issue by haydenCodes** [GeyserMC/Geyser#1879]
**Describe the bug**

Java Edition 1.16.4 Tuinity server. 

When Windows 10 players try to connect/ ping the server, it always works. Haven't tested on console versions, but phones only work every so often. 

Every phone is different - some can connect with no issues, while others can't connect at all. If I restart the proxy, that'll change whether some phones can connect or not. For instance, lets say phone 1 can connect and phone 2 can't. If I restart the proxy, it may make it so phone 1 can't connect, and phone 2 can. 

**To Reproduce**

1. Bungeecord instance running Geyser
2. Configure Geyser to use Floodgate
3. Have bungeecord poiting to a 1.16.4 Tuinity server 
4. Try connecting on a mobile bedrock version

**Expected behavior**

Mobile players would be able to enter the IP and connect to the server.

**Screenshots / Videos**

n/a

**Server Version and Plugins**

Tuinity 1.16.4, BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:281aece:1538 by md_5.

Plugins (Bungee):
- Via Version
- Via Backwards
- Luckperms
- Geyser Bungee
- Floodgate bungee
- Clean MOTD
- Changeslots

Plugins (Spigot):
- Worldedit
- Void generator
- Verus
- Vault
- Protocol Lib
- Multiverse Core
- Luck Perms
- Litebans
- Gholo
- Citizens

**Geyser Dump**

https://dump.geysermc.org/ZAXOvsHyAMmbdV8WLwqWDpTrKbEiV3qz

**Minecraft: Bedrock Edition Version**

Windows 10: Bedrock 1.16.201
IOS: Bedrock 1.16.201
Java: Minecraft 1.16.4

**Additional Context**

b/a

**Comment by w41k3r26** [comment]
having similar issue

**Comment by Hellohi3654** [comment]
Mobile Bedrock is currently buggy at the moment 
This is nothing to do with Geyser 
The only fix is to completely restart Minecraft on mobile until it works
If not try making a pocketmine, nukkit or MCBE dedicated server and see if the problem persists

**Comment by Camotoy** [comment]
You can also try https://github.com/GeyserMC/Geyser/pull/1775.

To download a pull request (or a "PR") you need to:
1. Make sure you are signed in with a GitHub account
2. Follow the pull request link that was sent to you
3. Follow the guide on this picture: https://images-ext-2.discordapp.net/external/GTXJkSGA22bfKu6zbE4IOCFeJ6GVN_O2RtGXx3mOcLM/https/i.ibb.co/tCcB1Qp/PR1.png?width=340&height=300

**Comment by haydenCodes** [comment]
> You can also try #1775.
> 
> To download a pull request (or a "PR") you need to:
> 
> 1. Make sure you are signed in with a GitHub account
> 2. Follow the pull request link that was sent to you
> 3. Follow the guide on this picture: https://images-ext-2.discordapp.net/external/GTXJkSGA22bfKu6zbE4IOCFeJ6GVN_O2RtGXx3mOcLM/https/i.ibb.co/tCcB1Qp/PR1.png?width=340&height=300

Unfortunately, this did not solve the issue.

Anyone have any other ideas? I don't think it's impossible to fix since servers like The Hive have mastered connecting through mobile.

**Comment by Camotoy** [comment]
I would recommend trying a Bedrock dedicated server from https://www.minecraft.net/en-us/download/server/bedrock if wherever you're hosting permits it. That would narrow down your issue between host and Geyser.

**Comment by haydenCodes** [comment]
> I would recommend trying a Bedrock dedicated server from https://www.minecraft.net/en-us/download/server/bedrock if wherever you're hosting permits it. That would narrow down your issue between host and Geyser.

Thanks but that's definitely not an option either since we're specifically shooting for Java & Geyser cross compatibility.

**Comment by Camotoy** [comment]
Of course - I'm requesting that you try that software and see if your connection issues persist. If they do, then the issue likely is not us.

**Comment by haydenCodes** [comment]
> Of course - I'm requesting that you try that software and see if your connection issues persist. If they do, then the issue likely is not us.

They don't persists when using that software. It only happens through Geyser

**Comment by Camotoy** [comment]
You can try lowering the MTU value in your Geyser config - see the wiki for details. Otherwise, it's going to be a bit difficult to replicate this.

**Comment by Camotoy** [comment]
Additionally, if you have a host provider, sharing that knowledge would be helpful.

**Comment by ActionSavage** [comment]
Just to flag that I have had a similar problem. Camotoy was very helpful on Discord but installing this PR (overwrote production Geyser jar with the one from PR 1775) resulted in a load of errors. So I too am seeing the same error with:
1) Old iPad 2 connecting consistently
2) Newer iPad Air 2 NEVER connecting
3) iPhone X connecting once or twice then needs app restarted a few times.
4) Desktop Java client of course never having an issue.

If I can help with debugging/testing at all then let me know.

**Comment by Camotoy** [comment]
^ This guy is on the same network (which rules out port forwarding/network being a thing) and is getting no pings from the other devices.

**Comment by Hellohi3654** [comment]
> Mobile Bedrock is currently buggy at the moment
> This is nothing to do with Geyser
> The only fix is to completely restart Minecraft on mobile until it works
> If not try making a pocketmine, nukkit or MCBE dedicated server and see if the problem persists

As I said before mobile is quite buggy at the moment 
@ActionSavage did you try restarting Minecraft on all your devices and trying to join the server at least 5 times 
Sometimes it takes me 5 tries to join my server on mobile 
Also @ActionSavage maybe make sure that all the devices including the host computer are on the same wifi network. That may help

**Comment by ActionSavage** [comment]
@Hellohi3654 ya I've restarted both the app and devices numerous times. I see the exact same behaviour on each of the particular devices, but each behaves differently - (iPhone X is 50/50, old iPad is 100% and new iPad is 0%) after many many attempts over the weekend (definitely many 10s of attempts if not 100+ on the iPad in particular). 

I cannot put the server on the WIFi network as it's an old Dell Optiplex that only has Cat 5, no wifi. But all devices and servers can ping each other, see the same DHCP/DNS/IP Range/UDP broadcasts and more. I did switch the new iPad (0% one) from a 5GHz to a 2.4Ghz network to see if that helped, but no joy.

Happy if there's any more questions or things to try.

**Comment by Camotoy** [comment]
If anyone here uses Android and gets this issue: try downgrading to 1.16.200 or 1.16.101 and see if the issues persist?

**Comment by Hellohi3654** [comment]
> If anyone here uses Android and gets this issue: try downgrading to 1.16.200 or 1.16.101 and see if the issues persist?

I'll try that this afternoon

**Comment by RednedEpic** [comment]
Seems to be fixed as of 1.16.220.
