### ISSUE TITLE
Chat is cut off on bedrock clients

### ISSUE THREAD

**Issue by ClientKitty** [GeyserMC/Geyser#188]
Stuff in the chat appears to be cut off on the end when playing on Spigot servers. The server version is 1.8 and the bedrock version is Windows 10 edition 1.14.3. I'm pretty sure I have the newest version of Geyser as well.

**Comment by AnonAlpha** [comment]
Spigot version 1.15.2 don't have that problem

**Comment by jackson-57** [comment]
I've experienced the problem on various branches, but I can't remember which. I wouldn't think it's due to the server, though
