### ISSUE TITLE
Bedrock player can't use ice road with slabs in between

### ISSUE THREAD

**Issue by gameusefly** [GeyserMC/Geyser#1882]
**Describe the bug**

On Java the players can build and use an ice road to travel very fast. With buttons on the ice bedrock players can't use them. Java Players can use the road

**To Reproduce**

1. Build an ice road like my screenshot
2. go on the boat
3. drive
4. see scuffed movement

**Expected behavior**

That i can drive clean my ice road

**Screenshots / Videos**

[https://prnt.sc/xt7dl3](url)

[https://prnt.sc/xt7fh6](url)

**Server Version and Plugins**

https://dump.geysermc.org/CMCoPNIEdkY0vdeIafX7i9uFEK2ZhgEP

**Minecraft: Bedrock Edition Version**

1.16.201 Windows 10

**Comment by Camotoy** [comment]
This might be a can't-fix on our end, if Bedrock doesn't treat buttons as glidable. This needs to be replicated on BDS.

**Comment by Degagelemming95** [comment]
I have tested this in a normal Minecraft world and having buttons on ice blocks, blue ice, packed ice, and normal ice does in fact allow the boat to glide on them so this should be possible!!

**Comment by gameusefly** [comment]
The Problem is that i have slabs between the ice that stops bedrock players but java player not. On Server with Geyser and on single player i have the problem

**Comment by Camotoy** [comment]
I was able to confirm this on Geyser and on a Bedrock vanilla server. While I think this *is* fixable, it's likely not going to be fixed for a long time on our end. Bedrock controls the boat speed, not Geyser, so when it sees the slabs it slows down the boat.

For the time being, remove the slabs in between if you want Bedrock players to go at full speed.

**Comment by RednedEpic** [comment]
Closing as this is primarily a client limitation. While it _may_ be fixable, it's only hypothetical at this point and is very unlikely to be fixed by us.
