### ISSUE TITLE
iOS clients get instantly crashed

### ISSUE THREAD

**Issue by timof121** [GeyserMC/Geyser#1883]
**Describe the bug**

If you are on iOS and you join any 1.12.2 server with geyser (or if it has geyser plugin) it will crash your game.

**To Reproduce**

1. Start MCBE on any iOS device
2. Join any 1.12.2 with geyser (I’m not sure if other server versions are affected with this bug)
3. When you will load, it will show the void for a second and crash your game.

**Expected behavior**

Should normally load into the game

**Screenshots / Videos**

https://user-images.githubusercontent.com/52547763/106284405-79291b00-6243-11eb-806e-f4b370d40fce.MOV

**Server Version and Plugins**

[Server thread/INFO]: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

The only plugins im using are floodgate, geyser-spigot and viaversion (for geyser to work)

**Geyser Dump**

https://dump.geysermc.org/hEworSTi5Uby1787vQzHi2Iv1J6ZWBgo

**Minecraft: Bedrock Edition Version**

1.16.201 (Latest) on iOS iPad Mini 2 (Tested on iPhone X and iPhone 8, also crashes)

**Additional Context**
Im not sure if the issue also happens on >1.12.2 servers (Also hypixel doesn’t crash)

**Comment by Camotoy** [comment]
I am unable to replicate with an iPhone 8 and 1.16.201. 

- Have you tried with a completely fresh server setup? If you did change the configs, which ones?
- Does the crash happen using Geyser standalone?

**Comment by timof121** [comment]
I created my server this week, and the only configs i changed are the max players and in paper.yml mob spawning and chunk saving.

And yes the crash happens with geyser standalone

**Comment by Chew** [comment]
Hey there! Sorry to hear you're having issues. Are you still running into issues with crashing on the latest versions?

**Comment by timof121** [comment]
> Hey there! Sorry to hear you're having issues. Are you still running into issues with crashing on the latest versions?

Idk. I bought an android device so ill close the issue

**Comment by Chew** [comment]
Darn :(

**Comment by steviee** [comment]
I have this same issue.

**Comment by onebeastchris** [comment]
@steviee Update Bedrock to 1.20.41 - and for the future, please create a new post instead of commenting on a 2+ year old post :)
