### ISSUE TITLE
Username Autocomplete Not Working

### ISSUE THREAD

**Issue by kotykd** [GeyserMC/Geyser#1884]
**Describe the bug**

I have Luckperms along with other plugins and whenever I want to type in a username it does NOT autocomplete. I don't know if this is a bedrock client issue or if it is an issue on your end but this would be very useful if you could get it to work.

**To Reproduce**

1. If you have a plugin that requires you to type in a username (like Luckperms) then you will see that whenever you need to type in a username (like if your going to add a user to a group) then it will not autocomplete the name.
2. 
3. 
4. 

**Expected behavior**

I expect it to autocomplete a username whenever necessary.

**Screenshots / Videos**

**Server Version and Plugins**

If you just run Geyser-Spigot, you can leave this area blank as the next section covers this information.

If you're running a multi-server instance, or using Geyser Standalone:

- Give us the exact output from `/version` on all servers involved. Saying "latest" does not help us at all.
- Please list all plugins on all servers involved.

If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

**Geyser Dump**

{
    "versionInfo": {
        "name": "Geyser",
        "version": "1.2.0-SNAPSHOT (git-master-5a8604f)",
        "javaVersion": "11.0.2",
        "architecture": "amd64",
        "operatingSystem": "Linux",
        "operatingSystemVersion": "4.15.0-122-generic",
        "network": {
            "internalIP": "***",
            "dockerCheck": false
        },
        "mcInfo": {
            "bedrockVersion": "1.16.201",
            "bedrockProtocol": 422,
            "javaVersion": "1.16.4",
            "javaProtocol": 754
        }
    },
    "gitInfo": {
        "git.tags": "",
        "git.build.version": "1.2.0-SNAPSHOT",
        "git.commit.id.abbrev": "5a8604f",
        "git.branch": "master",
        "git.build.host": "nukkitx.com",
        "git.build.number": "592",
        "git.total.commit.count": "1591",
        "git.commit.id": "5a8604fe54d9391cac0288d8738b10cf31605884",
        "git.local.branch.ahead": "NO_REMOTE",
        "git.build.time": "2021-01-22T01:04:36+0100",
        "git.commit.time": "2021-01-22T01:03:46+0100",
        "git.local.branch.behind": "NO_REMOTE",
        "git.dirty": "false",
        "git.commit.message.full": "Skin fixes and optimizations (#1856)\n\n- Fix self-assigned player skins getting overwritten\r\n- Fix players with no skin silently throwing an exception, and properly handle it instead\r\n- CRITICAL bug fix of handling Deadmau5's skin - it's not handled by his UUID but by his username",
        "git.remote.origin.url": "https://github.com/GeyserMC/Geyser.git"
    },
    "config": {
        "autoconfiguredRemote": true,
        "bedrock": {
            "address": "***",
            "port": 25565,
            "motd1": "The Golden Games",
            "motd2": "Golden Games Server",
            "clone-remote-port": false,
            "server-name": "Golden Games"
        },
        "remote": {
            "address": "***",
            "port": 25565,
            "auth-type": "floodgate",
            "allow-password-authentication": true,
            "use-proxy-protocol": false
        },
        "userAuths": null,
        "metrics": {
            "enabled": true,
            "uuid": "97805480-a209-466c-8601-5ddd994c6695"
        },
        "floodgate-key-file": "public-key.pem",
        "command-suggestions": true,
        "passthrough-motd": false,
        "passthrough-player-counts": false,
        "passthrough-protocol-name": false,
        "legacy-ping-passthrough": false,
        "ping-passthrough-interval": 3,
        "max-players": 100,
        "debug-mode": false,
        "general-thread-pool": 32,
        "allow-third-party-capes": true,
        "show-cooldown": true,
        "show-coordinates": true,
        "allow-third-party-ears": false,
        "default-locale": null,
        "cache-chunks": true,
        "cache-images": 0,
        "allow-custom-skulls": true,
        "above-bedrock-nether-building": false,
        "force-resource-packs": true,
        "xbox-achievements-enabled": false,
        "scoreboard-packet-threshold": 20,
        "enable-proxy-connections": false,
        "mtu": 1400,
        "use-adapters": true,
        "config-version": 4
    },
    "userPlatforms": {
        "WIN10": 1
    },
    "ramInfo": {
        "free": 206,
        "total": 879,
        "max": 1024
    },
    "bootstrapInfo": {
        "platform": "SPIGOT",
        "platformName": "Paper",
        "platformVersion": "git-Paper-189 (MC: 1.16.2)",
        "platformAPIVersion": "1.16.2-R0.1-SNAPSHOT",
        "onlineMode": true,
        "serverIP": "***",
        "serverPort": 25565,
        "plugins": [
            {
                "enabled": true,
                "name": "ViaVersion",
                "version": "3.2.1",
                "main": "us.myles.ViaVersion.ViaVersionPlugin",
                "authors": [
                    "_MylesC",
                    "creeper123123321",
                    "Gerrygames",
                    "KennyTV",
                    "Matsv"
                ]
            },
            {
                "enabled": true,
                "name": "floodgate-bukkit",
                "version": "1.0-SNAPSHOT",
                "main": "org.geysermc.floodgate.BukkitPlugin",
                "authors": [
                    "GeyserMC"
                ]
            },
            {
                "enabled": true,
                "name": "OpenInv",
                "version": "4.1.5",
                "main": "com.lishid.openinv.OpenInv",
                "authors": [
                    "lishid",
                    "Jikoo",
                    "ShadowRanger"
                ]
            },
            {
                "enabled": true,
                "name": "ProtocolLib",
                "version": "4.6.0-SNAPSHOT-b493",
                "main": "com.comphenix.protocol.ProtocolLib",
                "authors": [
                    "dmulloy2",
                    "comphenix"
                ]
            },
            {
                "enabled": true,
                "name": "LuckPerms",
                "version": "5.2.76",
                "main": "me.lucko.luckperms.bukkit.LPBukkitBootstrap",
                "authors": [
                    "Luck"
                ]
            },
            {
                "enabled": true,
                "name": "Geyser-Spigot",
                "version": "1.2.0-SNAPSHOT",
                "main": "org.geysermc.platform.spigot.GeyserSpigotPlugin",
                "authors": [
                    "GeyserMC"
                ]
            },
            {
                "enabled": true,
                "name": "Vault",
                "version": "1.7.3-b131",
                "main": "net.milkbowl.vault.Vault",
                "authors": [
                    "cereal",
                    "Sleaker",
                    "mung3r"
                ]
            },
            {
                "enabled": true,
                "name": "FastAsyncWorldEdit",
                "version": "1.16-581;dd65cff",
                "main": "com.sk89q.worldedit.bukkit.WorldEditPlugin",
                "authors": [
                    "Empire92",
                    "MattBDev",
                    "IronApollo",
                    "dordsor21",
                    "NotMyFault"
                ]
            },
            {
                "enabled": true,
                "name": "lightEconomy",
                "version": "2.9.3",
                "main": "de.light.economy.organisation.Main",
                "authors": [
                    "lightPlugins"
                ]
            },
            {
                "enabled": true,
                "name": "Essentials",
                "version": "2.18.2.0",
                "main": "com.earth2me.essentials.Essentials",
                "authors": [
                    "Zenexer",
                    "ementalo",
                    "Aelux",
                    "Brettflan",
                    "KimKandor",
                    "snowleo",
                    "ceulemans",
                    "Xeology",
                    "KHobbits",
                    "md_5",
                    "Iaccidentally",
                    "drtshock",
                    "vemacs",
                    "SupaHam",
                    "md678685"
                ]
            },
            {
                "enabled": true,
                "name": "EssentialsChat",
                "version": "2.18.2.0",
                "main": "com.earth2me.essentials.chat.EssentialsChat",
                "authors": [
                    "Zenexer",
                    "ementalo",
                    "Aelux",
                    "Brettflan",
                    "KimKandor",
                    "snowleo",
                    "ceulemans",
                    "Xeology",
                    "KHobbits",
                    "md_5",
                    "Okamosy",
                    "Iaccidentally"
                ]
            }
        ]
    }
}

**Minecraft: Bedrock Edition Version**

1.16.201

**Additional Context**

**Comment by Camotoy** [comment]
I'm going to close this because there's nothing we can do about this. You can change Bedrock players' Floodgate prefix - removing it (which we don't recommend) will work, but also try a prefix such as `.`

**Comment by kotykd** [comment]
But everytime I try to delete the prefix altogether or even change it to "." it doesn't actually change it.

**Comment by Camotoy** [comment]
Check here: https://github.com/GeyserMC/Geyser/wiki/Floodgate
