### ISSUE TITLE
Bedrock Players can't see any banner layers past first 6

### ISSUE THREAD

**Issue by LichLord91** [GeyserMC/Geyser#1887]
**Describe the bug**

Bedrock players don't see banner more than 6 banner layers.

**To Reproduce**

1. Create banner with more than 6 layers with command block or in creative mode
2. Example command block banner generation

`/minecraft:give @p blue_banner{BlockEntityTag:{Patterns:[{Pattern:"ss",Color:15},{Pattern:"bts",Color:8},{Pattern:"hh",Color:8},{Pattern:"gra",Color:15},{Pattern:"gru",Color:15},{Pattern:"flo",Color:2},{Pattern:"mr",Color:10},{Pattern:"mc",Color:10},{Pattern:"mc",Color:2},{Pattern:"sku",Color:15}]}} 1`

**Expected behavior**

Bedrock players able to see all layers of banner

**Screenshots / Videos**

Layers of the banner
![image](https://user-images.githubusercontent.com/8435580/106375871-c640e600-6344-11eb-9ecb-5ec016dae6f7.png)

Java Player
![image](https://user-images.githubusercontent.com/8435580/106375872-ca6d0380-6344-11eb-89f4-0c8f19f975b8.png)

Bedrock player via Geyser
![image](https://user-images.githubusercontent.com/8435580/106375876-d1941180-6344-11eb-9b9e-6751183f7418.png)

**Server Version and Plugins**

Geyser version 1.2.0-SNAPSHOT (git-server-inventory-4a8d937)

**Geyser Dump**

https://dump.geysermc.org/MxZridVRLbbBzQVHfqtAPQ3uw2Cu0efv

**Minecraft: Bedrock Edition Version**

v1.16.201 on Windows 10 and IOS

**Additional Context**

**Comment by Camotoy** [comment]
Unfortunately, this is a Bedrock limitation, if I am correct.

**Comment by YHDiamond** [comment]
Can we fix with a custom generated resource pack or something like that or is that too crazy

**Comment by Camotoy** [comment]
Probably not.

**Comment by LichLord91** [comment]
RIP , yeah bedrock can't create anything with more than 6 layers for the banner, though it can see it in the item tooltip. The first picture i showed is what it looks like on bedrock side (the item tooltip that is)

**Comment by RednedEpic** [comment]
Closing as this is a bedrock limitation.
