### ISSUE TITLE
Itemlore and name bug

### ISSUE THREAD

**Issue by MightyEclipseAWE** [GeyserMC/Geyser#1893]
**Describe the bug**

If i rename an item or edit the lore and drop this item to an mcpe player and he drops it back the name and Lore get removed.

**To Reproduce**

1. Go to java
2. Add a lore and name to an item.
3. Drop the item do an mcpe player.
4. The MCPE player drops the item back
5. The Item gets reset.

**Expected behavior**

The item lore and name should be same before and after dropping.

**Screenshots / Videos**

**Server Version and Plugins**
1.16.5 Spigot 
Plugins: BetterRTP, BuycraftX, Citizens, Clans, ClansChatAddon, ClansRenameAddon, ClansShowAddon, CoreProtect, DiscordSRV, Essentials, FastAsyncWorldEdit (WorldEdit), floodgate-bukkit, Geyser-Spigot, GHolo, GoldenCrates, GriefPrevention, HeadDatabase*, IllegalStack, JoinEventsPro, LPC, LuckPerms, Md5Lukas-Commons, Multiverse-Core, NexEngine, PlaceholderAPI, Playtime, ProtocolLib, QuickBoard*, SetTheSpawn, UberEnchant, Vault, VoxelSniper, WorldGuard

If you're running a multi-server instance, or using Geyser Standalone:

- Give us the exact output from `/version` on all servers involved. Saying "latest" does not help us at all.
- Please list all plugins on all servers involved.

If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

**Geyser Dump**

https://dump.geysermc.org/YmH49mGAToGDnF2jAzt1uNjoc1g1Et0x

**Minecraft: Bedrock Edition Version**

Newest MCPE Mobile Version.
**Additional Context**

**Comment by Camotoy** [comment]
Is the player in creative mode when this happens?

**Comment by MightyEclipseAWE** [comment]
Yes

Camotoy <notifications@github.com> schrieb am Mi., 3. Feb. 2021, 04:53:

**Comment by MightyEclipseAWE** [comment]
Yes.

**Comment by Camotoy** [comment]
This will be fixed in the inventory rewrite.

**Comment by MightyEclipseAWE** [comment]
when will it be done?

**Comment by Camotoy** [comment]
There is no ETA at this time, but you can try out the `server-inventory` branch on our build server.
