### ISSUE TITLE
Geyser starts slowly or does not start due to regional network problems

### ISSUE THREAD

**Issue by CuleSKY** [GeyserMC/Geyser#1897]
**What feature do you want?**
Can you provide the complete package of Geyser for launching in areas with poor network access (e.g. mainland China).

**Comment by ExusiaiMoe** [comment]
Think that language files can't be prepacked, it should be in the game jar, by prepacking it, maybe this is against MOJANG's EULA?

**Comment by CuleSKY** [comment]
> Think that language files can't be prepacked, it should be in the game jar, by prepacking it, maybe this is against MOJANG's EULA?

If pre-packaging is not available, can Geyser offer users to skip the "network check" step?

**Comment by Heath123** [comment]
It's not a check, Geyser sort of needs to do it for certain chat messages to work well

**Comment by ExusiaiMoe** [comment]
just like health123 said, geyser just need the language file which you can extract from the game jar manually, it don't have a "network check"

**Comment by rtm516** [comment]
You could download these files manually beforehand as they only need to be downloaded once, but we will likely not supply a jar with them included due to copyright infringement.

**Comment by CuleSKY** [comment]
> You could download these files manually beforehand as they only need to be downloaded once, but we will likely not supply a jar with them included due to copyright infringement.

I tried to use geyser on a server with a good internet connection and copied its entire folder into my server in mainland China (with the relevant language files included). But it reminded me that it could not read the local cache.Geyser tired to connect the download server but it failed.

**Comment by ExusiaiMoe** [comment]
don't think it can be fixed on geyser's side, maybe we'll add a wiki explaining how to do it manually.

**Comment by Heath123** [comment]
Or what about a fallback that breaks translation strings but at least lets you play the game?

**Comment by ExusiaiMoe** [comment]
> > You could download these files manually beforehand as they only need to be downloaded once, but we will likely not supply a jar with them included due to copyright infringement.
> 
> I tried to use geyser on a server with a good internet connection and copied its entire folder into my server in mainland China (with the relevant language files included). But it reminded me that it could not read the local cache.Geyser tired to connect the download server but it failed.

You are sure geyser is requesting mojang's server for jar? Or what's the **Download server** you are mentioning?
Any error message in console when failed?

**Comment by Camotoy** [comment]
#1907 will allow Geyser to boot if it is unable to download the Minecraft English locale file.
