### ISSUE TITLE
Ip forwarding

### ISSUE THREAD

**Issue by Maxsimuss** [GeyserMC/Geyser#190]
**What feature do you want?**
Ip forwarding similar to bungeecord's

**Alternatives?**
None

**Comment by Tim203** [comment]
See https://github.com/GeyserMC/Floodgate

**Comment by Maxsimuss** [comment]
Still displays connected from 127.0.0.1

**Comment by RednedEpic** [comment]
This isn’t possible without Floodgate and has been confirmed to work with it installed. Please make sure you have everything set up with it properly.
