### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by KelaLeaf** [GeyserMC/Geyser#1904]
**Describe the bug**

Client crash

**To Reproduce**

I joined the server on my phone, logged in to my account, and the client crashed

**Expected behavior**

I wish I could get into the game properly and not have the client back out

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/62498430/107114645-64333400-68a2-11eb-870d-0bbb201066d4.png)

**Server Version and Plugins**

[17:41:18 INFO]: This server is running Paper version git-Paper-416 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[17:41:18 INFO]: Checking version, please wait...
[17:41:20 INFO]: Previous version: git-Paper-412 (MC: 1.16.4)
[17:41:20 INFO]: You are running the latest version
[17:42:53 INFO]: 该服务器正在运行 Geyser 版本 1.2.0-SNAPSHOT (git-master-c26a2ba) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201)

![image](https://user-images.githubusercontent.com/62498430/107114795-aad55e00-68a3-11eb-9653-74cdc7dea606.png)

If you're running a multi-server instance, or using Geyser Standalone:

- Give us the exact output from `/version` on all servers involved. Saying "latest" does not help us at all.
- Please list all plugins on all servers involved.

If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

**Geyser Dump**

https://dump.geysermc.org/I0Azl17r6gpvAzYmqJxIBnsmOISNhk0r

**Minecraft: Bedrock Edition Version**

Android Bedrock 1.16.201.01

**Additional Context**

**Comment by Konicai** [comment]
This is likely an issue with TitleManager-3.2.1

Does anything change if you disable it or use TitleManager-3.2.0 ?

#1865 is related

**Comment by KelaLeaf** [comment]
> This is likely an issue with TitleManager-3.2.1
> 
> Does anything change if you disable it or use TitleManager-3.2.0 ?
> 
> #1865 is related

Thank you very much! Problem solved.

**Comment by Chew** [comment]
Is the issue resolved?

**Comment by RednedEpic** [comment]
Closing due to lack of response.
