### ISSUE TITLE
Bedrock users can't connect if i add other plugins

### ISSUE THREAD

**Issue by CubPuyi** [GeyserMC/Geyser#1908]
I get the error java.ov,IOExecption: Connection reset by peer if i add plugins when geyser have been installed

**Comment by Camotoy** [comment]
Please follow the bug report issue template, or I will close this issue. Thank you!

**Comment by CubPuyi** [comment]
Mb didn't read what said in the template at first. But you can just close this issue since i don't know if I'm gonna use the plugin with a few friends. Can also issue again if it happens to i do:)

**Comment by Camotoy** [comment]
Sounds good.
