### ISSUE TITLE
Bedrock player API

### ISSUE THREAD

**Issue by Maxsimuss** [GeyserMC/Geyser#191]
**What feature do you want?**
Make an API for BungeeCord and Spigot so the server could detect if the player is using a bedrock minecraft version or not (Useful for disabling anticheat for certain players)

**Alternatives?**
Detect if the connection is coming from localhost (a **very** bad idea), won't work with ip forwarding

**Comment by Tim203** [comment]
See https://github.com/GeyserMC/Floodgate

**Comment by Maxsimuss** [comment]
Isn't that only for bypassing authentication? I need the api to bypass the anticheat

**Comment by Tim203** [comment]
It has an API too
