### ISSUE TITLE
Stonecutter UI

### ISSUE THREAD

**Issue by kersid** [GeyserMC/Geyser#1913]
**What feature do you want?**
Stonecutter Use

**Alternatives?**
Using the block doesn't work as UI doesn't show up
Using /stonecutter or /estonecutter from EssentialsX also does not work
Unable to find workaround other than creating custom crafting plugin and reducing prices of all craftables

**Comment by Camotoy** [comment]
This is known and listed on the README. If you want to check out a work-in-progress build with these inventories, please see https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/server-inventory/.
