### ISSUE TITLE
 When gamerule "doImmediateRespawn" is active, bedrock players aren't immediately respawned.

### ISSUE THREAD

**Issue by k4deng** [GeyserMC/Geyser#1914]
**Describe the bug**

When gamerule "doImmediateRespawn" is active, bedrock players aren't immediately respawned.

**To Reproduce**

1. Turn on the gamerule, doImmediateRespawn
2. Die

**Expected behavior**

No GUI when dead, just respawns player.

**Screenshots / Videos**

Not needed.

**Server Version and Plugins**

Paper;
Plugins (19): BlueMap, Citizens, DeadChest, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, floodgate-bukkit, Geyser-Spigot, GSit, Harbor, LuckPerms, Multiverse-Core, Multiverse-NetherPortals, PlaceholderAPI, SimpleScore, Vault, WorldEdit, WorldGuard

The server is running Paper version git-Paper-457 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Geyser Dump**

[https://dump.geysermc.org/Xkt5osaixi8dPhdAquCkqXn7r2y00ahx](https://dump.geysermc.org/Xkt5osaixi8dPhdAquCkqXn7r2y00ahx)

**Minecraft: Bedrock Edition Version**

iPhone, 1.16.201

**Comment by Camotoy** [comment]
Unable to replicate on an iPhone with 1.16.201 and Paper 457. No other plugins are installed, however.

**Comment by k4deng** [comment]
I found that I really should clarify that I was not the user that experienced this. A friend playing in my server said it was not working for him. Now that I think of it, I probably should have asked him to leave and rejoin or had a server restart.

**Comment by RednedEpic** [comment]
Seen no future reports of this at all. In the future please only open bug reports if you personally experience the bug on your end or have definitive proof from the player reporting it that this is indeed occurring.
