### ISSUE TITLE
The port of bedrock is closed

### ISSUE THREAD

**Issue by MCwenka** [GeyserMC/Geyser#1915]
I tried to use the plug-in version of geyser. When I started spigot, geyser told me the port was 19132. I can't connect to the server using the bedrock. But when I tried to scan port 19132 with nmap, nmap told me that port 19132 was closed. But port 25565 of java version is open correctly.....
This is part of my profile.I tried to set the address of bedrock to 127.0.0.1, but the problem remains. The spigot version is 1.16.5.

bedrock:
  address: 0.0.0.0
  port: 19132
  clone-remote-port: false
  motd1: "GeyserMC"
  motd2: "Another GeyserMC forced host."
  server-name: "Geyser"
remote:
  address: 127.0.0.1
  port: 25565
  auth-type: false
  allow-password-authentication: true
  use-proxy-protocol: false

**Comment by Camotoy** [comment]
You are probably scanning using TCP and not UDP - Java Edition uses TCP; Bedrock Edition uses UDP.

For help with connection issues like these, please join our Discord. Thank you!

**Comment by ylluminate** [comment]
I'm having perhaps a similar issue, but with UDP not showing as open. `sudo netstat -tulpn | grep LISTEN` reveals that only `25565` is open and `19132` is not to be seen (Ubuntu 20.04 with Geyser-Spigot on most recent Paper release).

**Comment by Chew** [comment]
Please hop onto [our Discord server](https://discord.gg/geysermc) for help with this. Thank you!

**Comment by ylluminate** [comment]
@Chew thanks - already there.  Just wanted to mention this here in case it is related. Not much luck yet in finding anyone who's aware of what could be going on yet over there.
