### ISSUE TITLE
High network latency

### ISSUE THREAD

**Issue by nikissXI** [GeyserMC/Geyser#1917]
![图片](https://user-images.githubusercontent.com/31379266/107513691-8c44cf00-6be3-11eb-9faf-c69b446e366a.png)
geyser version: #606 Geyser-Spigot.jar
java version: 1.16.5 paperspigot
I test it in LAN, not WAN. The network latency should be about 20ms.
When I first enter the server through geyser, the network latency is about 10 to 20ms.
After 1min it will keep at 100ms.
If I use WAN, it can increase to about 200 to 300ms from 20ms.
What's going on???

**Comment by Camotoy** [comment]
Geyser forwards the ping, and because it has to go through Geyser and Bedrock, that's where the number comes from.

We will likely lower that amount in the future.
