### ISSUE TITLE
No server status

### ISSUE THREAD

**Issue by nikissXI** [GeyserMC/Geyser#1918]
geyser version: #606 Geyser-Spigot.jar
java version: 1.16.5 paperspigot
IOS bedrock 1.16.201 can not display the passthrough-motd and passthrough-player-counts and server status.
Android bedrock no problem.
But I can enter the server.
![图片](https://user-images.githubusercontent.com/31379266/107604369-f0f73c80-6c6a-11eb-8def-52b0cbaddee3.png)
![图片](https://user-images.githubusercontent.com/31379266/107604383-fce2fe80-6c6a-11eb-9f09-3b0451ffffa0.png)

**Comment by Camotoy** [comment]
For connections issues like these, please join our Discord server. If the issues persist, please follow the issue template.

Have you tried restarting your client? Does disabling the passthrough options allow iOS to see the server?
