### ISSUE TITLE
Leaves show breaking particles

### ISSUE THREAD

**Issue by luciobortoletto** [GeyserMC/Geyser#1919]
**Describe the bug**
When I join a server from Bedrock Edition with GeyserMC installed, the leaves show breaking particles.

**To Reproduce**

1. Join the server
2. Find a tree
3. The leaves show breaking particles.

**Expected behavior**
I expected to see no particles.

**Screenshots / Videos**
![Minecraft 11_02_2021 21_26_50](https://user-images.githubusercontent.com/52795018/107694682-f1fe8d00-6caf-11eb-816b-a853dac84e10.png)

**Server Version and Plugins**
I'm using Geyser Velocity
Output of /version: 
![2021-02-11_21 29 56](https://user-images.githubusercontent.com/52795018/107695067-633e4000-6cb0-11eb-8605-f9b73fe80152.png)
Geyser version: 607
Other plugins on velocity: skinsrestorer 13.8.8
Other plugins on the server: ascmd 2.2, bungeeguard 1.2.0, essentialsx (antibuild+chat+spawn) dev 71, holograms 1.13.3, mambience 3.0.0 and skinsrestorer 13.8.8.

**Geyser Dump**
https://dump.geysermc.org/6YKUKliZj0uSW0a9bi585FAwety0uxNW

**Minecraft: Bedrock Edition Version**
1.16.201 Windows 10

**Additional Context**
The bug is here even on Android.

**Comment by Chew** [comment]
Sorry to hear about this!

If you're still able to reproduce this, can you please upload a video from Java and Bedrock edition showcasing this issue? Thank you!

**Comment by luciobortoletto** [comment]
With the new version it's fixed
