### ISSUE TITLE
Chest packet problem

### ISSUE THREAD

**Issue by Kirilliriks** [GeyserMC/Geyser#192]
**Describe the bug**

If the player tries to open the chest, then the chest does not open, the same with the package that the server sends to the player in Java (for example, the chest menu)

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/51951407/75915292-4b86f680-5e67-11ea-8abc-782c1ced0a63.png)

**Server version**
1.15.2

**Geyser version**
Shanpshot - 1

**Bedrock version**
14.

**Additional context**

**Comment by LegacyGamerHD** [comment]
@Kirilliriks use inventory branch

**Comment by LegacyGamerHD** [comment]
@RednedEpic close this

**Comment by Kirilliriks** [comment]
> @Kirilliriks use inventory branch

But I use 180 build, it seemed to me that this build is invetory, at least judging by the commits, this 180 build corresponds to the inventory branch

**Comment by RednedEpic** [comment]
> > @Kirilliriks use inventory branch
> 
> But I use 180 build, it seemed to me that this build is invetory, at least judging by the commits, this 180 build corresponds to the inventory branch

Chest opening animation is not in inventory branch yet.

**Comment by Kirilliriks** [comment]
> > > @Kirilliriks use inventory branch
> > 
> > 
> > But I use 180 build, it seemed to me that this build is invetory, at least judging by the commits, this 180 build corresponds to the inventory branch
> 
> Chest opening animation is not in the inventory branch yet.

I apologize for the bad English, but I meant that the inventory of the chest does not even form and does not open on the client side

**Comment by RednedEpic** [comment]
> I apologize for the bad English, but I meant that the inventory of the chest does not even form and does not open on the client side

Use the inventory branch off Jenkins. It’s not implemented in master yet.

**Comment by RednedEpic** [comment]
Implemented in inventory branch.
