### ISSUE TITLE
Tinted chestplates not shown in Java clients

### ISSUE THREAD

**Issue by MalexTP** [GeyserMC/Geyser#1922]
**Describe the bug**

when a Bedrock user equips a tinted leather chestplate, it isn't correctly shown, and when he takes off the object it changes from tinted to normal leather

**To Reproduce**

1. Equip any tinted leather chestplate in bedrock client
2. View if it is shown correctly in Java client
3. No? Take off your chestplate in bedrock and its now untinted chestplate

**Expected behavior**

Tinted chestplates should be correctly shown in java clients

**Screenshots / Videos**

![2021-02-12_21 14 42](https://user-images.githubusercontent.com/24663715/107839404-8dbcf580-6da3-11eb-920f-d66442f39701.png)
![2021-02-12_21 14 21](https://user-images.githubusercontent.com/24663715/107839407-8f86b900-6da3-11eb-82eb-c677815ceb48.png)
![2021-02-12_21 14 48](https://user-images.githubusercontent.com/24663715/107839401-8b5a9b80-6da3-11eb-8bc7-09cd1e7d7c93.png)

**Server Version and Plugins**

Yatopia 1.16.5 build 22
Geyser-Spigot 1.2.0 (c26a2ba)

**Minecraft: Bedrock Edition Version**

1.16.200.01

**Comment by Camotoy** [comment]
This is probably a creative mode bug. Try replicating in survival.

**Comment by MalexTP** [comment]
> This is probably a creative mode bug. Try replicating in survival.

absolutely! it is working on survival but not in creative

**Comment by Camotoy** [comment]
This will be fixed in the inventory rewrite.
