### ISSUE TITLE
Sometimes "U.I.S." shows up in Inventory

### ISSUE THREAD

**Issue by WolfyRed** [GeyserMC/Geyser#1924]
**Describe the bug**

Sometimes the "Unused Inventory Space" item shows up in the Inventory (More specifically, the Hotbar)

**To Reproduce**
This is an example I've found:
1. Get a Shulker Box
2. Put down the Shulker Box
3. Fill the Shulker Box with items (until it is full)
4. Break the Shulker Box
5. Pick up the S̤̟̼̗ͩ͑͆̐4̂̔ͫ̽̈́̌U̐̌Lͯk̞ͫ3͚͋rͦ̓̓̃̀ͪͮ ̪̻͉̹ͤ͗̈́ͬb͒̐̊0Xͫͨͧ̋ (Or go around the area the Shulker Box was broken, until you pick up ⊘̮͇̤͎̙̟̞̄ͩͪ̿ͧͩ͋ͭͮͅͅ⊘͍̩̈́̍⊘̰̟͍̖̠̩͍̹̬͇̊͌̋ͬ͒ͤ̓͊ͤͭ⊘̂͂͐ͬͨ̋͆ͭ̋̈̿́ͩͥ⊘̩̝̖̰̦̤̱̘͙̗̯⊘̃̅͌̔͋̈́͊̀̅͗̓͐̓͑̅)

**Expected behavior**

The Shulker Box to break and for it to show up as it's own item on the ground, being able to pick it up and nothing weird to happen.

**Screenshots / Videos**

https://user-images.githubusercontent.com/66114400/107873957-380c4a00-6e84-11eb-824d-29805b17fc79.mp4

If you're running a multi-server instance, or using Geyser Standalone:

Final build for 1.12.2

-- Plugins --
![image](https://user-images.githubusercontent.com/66114400/107874048-cc76ac80-6e84-11eb-8f4a-bac452a7ddb6.png)

If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

**Geyser Dump**

https://dump.geysermc.org/pcbSqYUHNTvBJKzZaq6I4esrH60BozNo

**Minecraft: Bedrock Edition Version**

`v1.16.201`   -   Minecraft [Windows 10 Edition]

**Additional Context**

*It's literally the "Unusable Inventory Space" from the creative inventory crafting slot from Minecraft Bedrock, how does it end up in your hotbar??*

**Comment by lukeeey** [comment]
I don’t understand this because I implemented the unusable inventory space block which is just a barrier with a custom name and lore but the item is completely fake, it is only sent to the bedrock client but doesn’t actually exist on the server and shouldn’t be visible to anyone else.

**Comment by WolfyRed** [comment]
> I don’t understand this because I implemented the unusable inventory space block which is just a barrier with a custom name and lore but the item is completely fake, it is only sent to the bedrock client but doesn’t actually exist on the server and shouldn’t be visible to anyone else.

If you get it in your hotbar you can click Q to drop it

**Comment by WolfyRed** [comment]
Fixed as of one of the newest releases on Jenkins.

Closing now
