### ISSUE TITLE
scoreboard sidebar name sometimes says "unknown"

### ISSUE THREAD

**Issue by I3ladeDragon** [GeyserMC/Geyser#1925]
**Describe the bug**

When changing between scoreboards, sometimes the Bedrock Edition scoreboard shows "unknown" instead of the scoreboard name.

**To Reproduce**

1. Create a new scoreboard by typing **/scoreboard objectives add test1 dummy "test1"**
2. Create another scoreboard by typing **/scoreboard objectives add test2 dummy "test2"**
3. Apply a score value to any player in both scoreboards
4. Alternate between the scoreboard sidebar displays by typing **/scoreboard objectives setdisplay sidebar test1** and **/scoreboard objectives setdisplay sidebar test2**
5. The Java Edition will correctly show the scoreboard title, while the Bedrock Edition will display "unknown". I've included pictures for reference.

**Expected behavior**

When the scoreboard display changes on the sidebar, the name should update to show the proper name.

**Screenshots / Videos**

Java Scoreboard:
![Java Scoreboard](https://user-images.githubusercontent.com/21696622/107892243-b692d700-6ed8-11eb-9261-be193ddfe83b.png)

Bedrock Scoreboard:
![Bedrock Scoreboard](https://user-images.githubusercontent.com/21696622/107892248-bdb9e500-6ed8-11eb-8f99-2a355f53f2ec.png)

**Server Version and Plugins**

- If you're running a multi-server instance, or using Geyser Standalone:

This server is running CraftBukkit version git-Spigot-f011ca2-3af81c7 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
You are 64 version(s) behind

- Please list all plugins on all servers involved:

Plugins (15): LuckPerms, WorldEdit, MiniaturePets, Harbor, OpenInvies, NoTrades, TeamChat, ChestLock, IllegalStack, ProtocolLib, CoreProtect, PacketLimiter, PremiumVanish, DiscordSRV, LiteBans

**Geyser Dump**

https://dump.geysermc.org/HY9IMQrlWSrTYJufBWpNMWUj0dBcA61m

**Minecraft: Bedrock Edition Version**

Bedrock Edition: v1.16.201
Device: Samsung Galaxy Note 8

**Additional Context**

**Comment by JH3Y50N** [comment]
I have this problem too, but for my server scoreboard java coded..

**Comment by I3ladeDragon** [comment]
> I have this problem too, but for my server scoreboard java coded..

I think it has something to do with the scoreboard display being swapped from one scoreboard to another.

**Comment by wifi-left** [comment]
Also, the scoreboard appears when it shouldn't be displayed.

**Comment by Chew** [comment]
Some scoreboard fixes have been merged in. Are you still experiencing issues?

**Comment by RednedEpic** [comment]
Stale. Please open a new issue with updated replication steps if this still occurs.
