### ISSUE TITLE
Clickable links in books do not work

### ISSUE THREAD

**Issue by I3ladeDragon** [GeyserMC/Geyser#1926]
**Describe the bug**

When having a link within a book that runs a command, Bedrock Edition does nothing when it is clicked.

**To Reproduce**

1. Run this command **/give @p written_book{pages:['["",{"text":"click","clickEvent":{"action":"run_command","value":"/say hi"}},{"text":" <---"}]'],title:test,author:test}**
2. Give the book to the Bedrock Edition player.
3. Have the Bedrock Edition player open the book and try to click the link that says "click".
4. Command does not execute.

**Expected behavior**

When the Bedrock Edition player clicks the text that says "click", it should run the command **/say hi**.

**Screenshots / Videos**

**Server Version and Plugins**

- If you're running a multi-server instance, or using Geyser Standalone:

This server is running CraftBukkit version git-Spigot-f011ca2-3af81c7 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
You are 64 version(s) behind

- Please list all plugins on all servers involved:

Plugins (15): LuckPerms, WorldEdit, MiniaturePets, Harbor, OpenInvies, NoTrades, TeamChat, ChestLock, IllegalStack, ProtocolLib, CoreProtect, PacketLimiter, PremiumVanish, DiscordSRV, LiteBans

**Geyser Dump**

https://dump.geysermc.org/HY9IMQrlWSrTYJufBWpNMWUj0dBcA61m

**Minecraft: Bedrock Edition Version**

Bedrock Edition: v1.16.201
Device: Samsung Galaxy Note 8

**Additional Context**

**Comment by Camotoy** [comment]
This is unfortunately a Bedrock limitation (there is no clickable text).

Related: https://github.com/GeyserMC/Geyser/issues/1340

**Comment by YodaLightsabr** [comment]
Shouldn't the issue be closed then?

**Comment by Chew** [comment]
@YodaLightsabr There are always alternatives and the potential to fix it on Bedrock's end.

**Comment by RednedEpic** [comment]
Added to the Current Limitations page on the wiki, closing.
