### ISSUE TITLE
Double Chest appears above player when opening containers parodically. 

### ISSUE THREAD

**Issue by LichLord91** [GeyserMC/Geyser#1928]
**Describe the bug**

Sometimes when clicking containers a double chest will appear above players heads

**To Reproduce**

1. open chests/barrels sometimes crafting containers i think and look above when opening.

**Expected behavior**

No chests above head? Its not really affecting anything just a visual glitch.

**Screenshots / Videos**

Here's a video 
https://streamable.com/386asq

**Server Version and Plugins**

"version": "1.2.0-SNAPSHOT (git-server-inventory-ce33ca5)",

**Geyser Dump**

https://dump.geysermc.org/3SdKEgbuhYygjOUD3ZzYwzdAckruXq8j

**Minecraft: Bedrock Edition Version**

v1.16.201 on Windows 10 and IOS and Xbox

**Additional Context**

**Comment by YHDiamond** [comment]
This is an intended feature otherwise we aren't able to have Bedrock use chests. We are working on a way to make this a bit better in the inventory rewrite :)

**Comment by Camotoy** [comment]
This person is on the server-inventory branch.

Chests will still appear above people's heads if the inventory is not tied to a block.

Barrels intentionally do not have the patch to fix the chest-above-head thing at this time.

**Comment by LichLord91** [comment]
Ahh okay thanks for the explanation. I didn't see any reports here about this so I thought it may have been unique to me. Maybe I just couldn't find one haha, this was the ticket I owed you Camotoy. Ill make sure to report anything else I find to help. <3

**Comment by YHDiamond** [comment]
> This person is on the server-inventory branch.
> 
> Chests will still appear above people's heads if the inventory is not tied to a block.
> 
> Barrels intentionally do not have the patch to fix the chest-above-head thing at this time.

f my brain then, but still...

**Comment by BeetGaming45** [comment]
> **Describe the bug**
> 
> Sometimes when clicking containers a double chest will appear above players heads
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. open chests/barrels sometimes crafting containers i think and look above when opening.
> 
> **Expected behavior**
> 
> No chests above head? Its not really affecting anything just a visual glitch.
> 
> **Screenshots / Videos**
> 
> Here's a video
> https://streamable.com/386asq
> 
> **Server Version and Plugins**
> 
> "version": "1.2.0-SNAPSHOT (git-server-inventory-ce33ca5)",
> 
> **Geyser Dump**
> 
> https://dump.geysermc.org/3SdKEgbuhYygjOUD3ZzYwzdAckruXq8j
> 
> **Minecraft: Bedrock Edition Version**
> 
> v1.16.201 on Windows 10 and IOS and Xbox
> 
> **Additional Context**

some of the players of my server told me that it also happens on furnaces..

**Comment by EasyClifton** [comment]
Yes, it happens with all inventories.

**Comment by burdoto** [comment]
There's an _actual bug_ related to this as well:
When opening a single chest or barrel (tested with barrel) while standing below an existing double chest, the barrel inventory will open up with a size of 6x9.
The Inventories are managed correctly, and attempting to place items in any of the extra slots will not work; but it's a little confusing and, finally leads to breaking inventories opening at all at some point.

**Comment by RednedEpic** [comment]
Going to close as Bedrock requires a block to actually exist in the world in order for container menus to actually show up properly. I believe with chests and other containers that actually exist in the world now just use that block specifically, but virtual ones require us to send a fake block somewhere. We may look to move this elsewhere in the future, such as behind the player, but ultimately this is something we're required to do, and thus not a bug.



> There's a bug related to this:
> When opening a single chest or barrel (tested with barrel) while standing below an existing double chest, the barrel inventory will open up with a size of 6x9.
> The Inventories are managed correctly, and attempting to place items in any of the extra slots will not work; but it's a little confusing and, finally leads to breaking inventories opening at all at some point.

There is already an issue open for this, #1727

**Comment by mac3ed** [comment]
en geyser 742 The event also happens to me. When I open a chest or barrel, a chest appears overhead. Maybe as they say, the solution would be to send it back.
