### ISSUE TITLE
Shields do not reactivate after clicking a block or eating

### ISSUE THREAD

**Issue by TardisLX** [GeyserMC/Geyser#1930]
**Describe the bug**
After sneaking to activate the shield if placing or clicking a block, the player is still sneaking, but the shield will not resume activation. And players may not be able to eat while using the shield.

**To Reproduce**

1. The deputy equips a shield and sneaks
2. Eating/placing or clicking a block
3. See error

**Expected behavior**

The shield should automatically reactivate after the interaction event is over, and the player should be able to eat.

**Screenshots / Videos**

https://youtu.be/jTA8P-xu8fo

**Server Version and Plugins**

This server is running Paper version git-Paper-468 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Geyser Dump**

https://dump.geysermc.org/YhLDOTx4Z68341AHYjx2TJvP6vAGNnGL

**Minecraft: Bedrock Edition Version**
1.16.201
Tested using Windows 10 Minecraft build 5131175 r/16_u2 . And Android Minecraft build 5121767 r/16_u2

**Additional Context**

**Comment by RednedEpic** [comment]
Is this still an issue?

**Comment by Chew** [comment]
There have been no reports of this occurring since the last reply 2 months ago, so we're gonna go ahead and close this. Thank you for reporting!
