### ISSUE TITLE
Snowball and Egg take up whole vision

### ISSUE THREAD

**Issue by bundabrg** [GeyserMC/Geyser#1934]
**Describe the bug**

When throwing an egg or a snowball it starts right up in front of the face as opposed to lower down on a vanilla client. This obscures the players vision for a bit.

This is purely a cosmetic issue. A video can be found [here](https://media.giphy.com/media/hlMZiJ7sIGxAlc2EBQ/giphy.gif)  (ignore the particles as that relates to [another issue](https://github.com/bundabrg/GeyserReversion/issues/38))

**To Reproduce**

Steps to reproduce the behaviour:
1. Throw snowball or eggs and observe how they look
2. Now try in a single player game and observe how they look

**Server Version and Plugins**

If you're running a multi-server instance, or using Geyser Standalone:

Paper:
```
[15:40:05 INFO]: This server is running Paper version git-Paper-204 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[15:40:05 INFO]: Checking version, please wait...
[15:40:07 INFO]: Previous version: git-Paper-38 (MC: 1.16.1)
[15:40:07 INFO]: You are 49 version(s) behind
```

**Geyser Dump**

https://dump.geysermc.org/vYBp6L0wkocOibNVwUCTcnJBq4h0Wjwb

**Minecraft: Bedrock Edition Version**

1.16.201.1, linux apk launcher

**Comment by Konicai** [comment]
Also happens with ender pearls, splash potions, lingering potions, and bottle o enchanting. It kind of happens with eyes of ender if you look straight down (since it spawns below you).
https://dump.geysermc.org/glK9LGV2b664pG4t5NTyopFisgtLec8z + fabric 1.17.1
