### ISSUE TITLE
"Dust" particle effect does not display correctly

### ISSUE THREAD

**Issue by I3ladeDragon** [GeyserMC/Geyser#1937]
**Describe the bug**

"Dust" particle effect does not display correctly in Bedrock.

**To Reproduce**

1a. Place a repeat command block to always active with the following command: `execute as @e[type=armor_stand] at @s anchored eyes run particle minecraft:dust 254 254 254 1 ^ ^-0.3 ^ .1 .1 .1 2500 20 force`
1b. Place a repeat command block to always active with the following command: `execute at @e[type=armor_stand] run particle minecraft:dust 1 0 0 1 ~ ~1.2 ~ .1 .4 .1 5000 20 force`
2. Summon an armor stand.
3. The armor stand will show the incorrect color and/or particle spread.

**Expected behavior**

"Dust" particle effect should show the correct colors and/or spread.

**Screenshots / Videos**

Java:
![image](https://user-images.githubusercontent.com/21696622/108128002-fa184d00-7060-11eb-8ff4-cf9adc6521f3.png)
![image](https://user-images.githubusercontent.com/21696622/108128839-38fad280-7062-11eb-8385-d5150c5b8f6d.png)

Bedrock:
![image](https://user-images.githubusercontent.com/21696622/108128049-0e5c4a00-7061-11eb-9a4f-87799f078247.png)
![image](https://user-images.githubusercontent.com/21696622/108128865-43b56780-7062-11eb-8716-ebb9db3f4479.png)

**Server Version and Plugins**

- If you're running a multi-server instance, or using Geyser Standalone:

This server is running CraftBukkit version git-Spigot-f011ca2-3af81c7 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
You are 64 version(s) behind

- Please list all plugins on all servers involved:

Plugins (15): LuckPerms, WorldEdit, MiniaturePets, Harbor, OpenInvies, NoTrades, TeamChat, ChestLock, IllegalStack, ProtocolLib, CoreProtect, PacketLimiter, PremiumVanish, DiscordSRV, LiteBans

**Geyser Dump**

https://dump.geysermc.org/HY9IMQrlWSrTYJufBWpNMWUj0dBcA61m

**Minecraft: Bedrock Edition Version**

Bedrock Edition: v1.16.201
Device: Samsung Galaxy Note 8

**Additional Context**

**Comment by ItzFlippp** [comment]
I’m experiencing the same issue.

**Comment by RednedEpic** [comment]
Stale. Please open a new issue with updated replication steps if this is still occurring.
