### ISSUE TITLE
Cannot reconncet after initial connection.

### ISSUE THREAD

**Issue by Ru-Pirie** [GeyserMC/Geyser#1945]
**Describe the bug**

This bug has puzzeled me. I was able to connect once to the server using a java account then when going to reconnect it throws an invalid credentials error. To clarify THIS IS NOT A CONNCETION ISSUE i am fully able to connect to the server it is when I go to login with an account that is the issue.

**To Reproduce**

1. Login once using a mojang account
2. Log out of the server
3. Log in again with a mojang account

**Expected behavior**

I was expecting to be able to login without any issue using a java account.

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/67950865/108262015-46948300-715c-11eb-989d-4489d6d7b2c9.png)

**Server Version and Plugins**

Waterfall version#395

**Geyser Dump**

https://dump.geysermc.org/jUHZ6ftPw1kMpEVLD2A8xTNGaeCqyXnF

**Minecraft: Bedrock Edition Version**

Windows 10 V1.16.201

**Comment by Ru-Pirie** [comment]
Issue has now progressed to total failer, looking into it myself.

**Comment by Ru-Pirie** [comment]
So, I can now no longer connect to the server at all with the bedrock side of things. The java is all fine and when using the [server checker](https://mcsrvstat.us/server/158.69.52.150:19132) it was seen however was not able to be pinged. I'm not sure what this means. Any ideas?

**Comment by jackson-57** [comment]
> So, I can now no longer connect to the server at all with the bedrock side of things. The java is all fine and when using the [server checker](https://mcsrvstat.us/server/158.69.52.150:19132) it was seen however was not able to be pinged. I'm not sure what this means. Any ideas?

Have you tried restarting your game? Bedrock multiplayer breaks after suspending the game (tabbing out of it or going to the homescreen), so you often have to restart it to get multiplayer working again

**Comment by Ru-Pirie** [comment]
OK, so that fixed the not finding the server issue...
Now, back to the original one... when i enter the correct account details for the java account to log on it still says incorrect credentials.
Your just gona have to trust me that the credentials are correct. All i get in the console is
```java
[21:16:07 INFO] [Geyser-BungeeCord]: User 'rubens.pirie@gmail.com' entered invalid login info, kicking.
[21:16:07 INFO] [Geyser-BungeeCord]: Bedrock user with ip: /81.110.1.132 has disconnected for reason CLOSED_BY_REMOTE_PEER```

**Comment by Ru-Pirie** [comment]
For some reason you can log in once and then never again...

**Comment by Ru-Pirie** [comment]
> Unable to replicate with Waterfall 395 and Geyser 616.

When doing this what things where changed in your config that differed from the standerd configuration files.

**Comment by Ru-Pirie** [comment]
Never mind issue resolved. It seems that somehow mojang classed it as suspicious activity and soft banned the account therefor meaning that once the account loged in the connection would not be allowed again! This issue was resolved by reseting the password on the account. I'm curious as to why the activity was classed as suspicious, if you have any idea please make note on this issue. Thanks for the support have a great day!
