### ISSUE TITLE
Add jar hash to dumps

### ISSUE THREAD

**Issue by rtm516** [GeyserMC/Geyser#1946]
**What feature do you want?**
Add the Geyser jar hash to dumps so we can get the bot to flag corrupted jars/downloads. This should be calculated either on start or when the dump is created and not at build time.

**Alternatives?**
N/A

**Notes**
You can likely reuse the SHA hash calculator from the resource pack stuff, need to check what hashes are supported by Jenkins to search on the API, or on jfrog/artifactory.

**Comment by Camotoy** [comment]
#2026 fixes this, though I have not verified if the hash is accessible via Jenkins.
