### ISSUE TITLE
Ability to change colour/font of version number in MOTD

### ISSUE THREAD

**Issue by Garfieldwxg55** [GeyserMC/Geyser#1947]
**What feature do you want?**
Currently the version shows in the same colour and font of the server MOTD, I propose that this could be altered in the configuration, this would allow for more customisation.

**Comment by lukeeey** [comment]
You can just add a color to the end of the motd

**Comment by Garfieldwxg55** [comment]
That's ok if you want to have the version details be one color, but say you want the dash to be one color and the actual version to be another, then that currently can't be done

**Comment by RednedEpic** [comment]
Luke's solution should work okay here. Version is something that is hardly rendered due to how tiny the server UI is & there isn't much interest on our end to implement a potential workaround. Closing.
