### ISSUE TITLE
Ladder bug

### ISSUE THREAD

**Issue by OOLEHLEH** [GeyserMC/Geyser#1948]
**Describe the bug**

Glitching when going up ladders when on Minecraft bedrock

**To Reproduce**

1. go up a ladder on bedrock edition

**Expected behavior**
Ladder bugs out

**Screenshots / Videos**
https://www.youtube.com/watch?v=XPqunXKSi4M

**Server Version and Plugins**
PaperMC Server
DiscordSRV
Autosave
GeyserSkinManager
ProtocolLib
SinglePlayersleep

If you just run Geyser-Spigot, you can leave this area blank as the next section covers this information.

If you're running a multi-server instance, or using Geyser Standalone:
multi-server

- Give us the exact output from `/version` on all servers involved. Saying "latest" does not help us at all.
- Please list all plugins on all servers involved.

If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

**Geyser Dump**
https://dump.geysermc.org/XOezEGdegXhKUrGyscWka0h29FkACGl1
''This server is running Geyser Version 1.2.0-SNAPSHOT (git-master-c4573bb) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201

If Geyser starts correctly, please also include the link to a dump by using `/geyser dump`. If you use the Standalone GUI, the option can be found under `Commands` => `Dump`. This provides us information about your server that we can use to debug your issue.

**Minecraft: Bedrock Edition Version**
S20 FE, Minecraft Bedrock v1.16.201

The version of your Minecraft: Bedrock Edition client you tested with, along with your device type (e.g. Windows 10, Switch...).

**Additional Context**
This only happens on bedrock and not java

**Comment by Camotoy** [comment]
It looks like this issue is the same as #682. See if the information presented there lines up.

I've also heard once that there is a difference between pressing forward to go up and pressing jump.
