### ISSUE TITLE
Mounting mobs automatically not working on bedrock

### ISSUE THREAD

**Issue by ItzFlippp** [GeyserMC/Geyser#1952]
**Describe the bug**

- Bedrock players are unable to automatically mount and ride on mobs. For example, on my skewers server, if a player has a win effect of riding a dragon, bedrock players hop on the dragon once they win, but then are immediately ejected off the mob

**To Reproduce**

1. Download UltraSkywars
2. Purchase dragon rider, wither rider, daredevil, etc.
3. Win a game on bedrock edition

**Expected behavior**

- Bedrock player will be mounted on the mob when triggered, but then immediately ejected off the mob.

**Screenshots / Videos**

https://vimeo.com/514118972

**Server Version and Plugins**

If you just run Geyser-Spigot, you can leave this area blank as the next section covers this information.

If you're running a multi-server instance, or using Geyser Standalone:

- Give us the exact output from `/version` on all servers involved. Saying "latest" does not help us at all.
- Please list all plugins on all servers involved.

If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

**Geyser Dump**

If Geyser starts correctly, please also include the link to a dump by using `/geyser dump`. If you use the Standalone GUI, the option can be found under `Commands` => `Dump`. This provides us information about your server that we can use to debug your issue.
From Bungeecord proxy:
 https://dump.geysermc.org/ZN76mdt9E35k192fLmbFLAD6heUxTRx5

**Minecraft: Bedrock Edition Version**

The version of your Minecraft: Bedrock Edition client you tested with, along with your device type (e.g. Windows 10, Switch...).
1.16.201 on mobile and windows 10
**Additional Context**

**Comment by Camotoy** [comment]
It appears that said plugin is paid? If there is a source for this, or another way for us to replicate this event, that would be superb.

**Comment by Camotoy** [comment]
Closing as #1979 appears to supersede this. If this is incorrect, please let me know!
