### ISSUE TITLE
Disable the use for login

### ISSUE THREAD

**Issue by anonymusdennis** [GeyserMC/Geyser#1954]
I have many friends that don't own a minecraft account...
I want them to be able to join the server even though they don't have an java account ...
Is this possible?

**Comment by GCPins** [comment]
> I have many friends that don't own a minecraft account...
> I want them to be able to join the server even though they don't have an java account ...
> Is this possible?

Yes. Install [Floodgate](https://github.com/GeyserMC/Geyser/wiki/Floodgate) and Geyser on the server.
