### ISSUE TITLE
Join without Xbox Live account

### ISSUE THREAD

**Issue by SimaKyr** [GeyserMC/Geyser#1957]
**What feature do you want?**
I have choosen "offline" mode in config file.
I tried to join to server without Xbox Live account but Minecraft says:
`Please, join in Xbox Live, to connect to this server.`
I took **official bedrock** server config file `server.properties`.
In this file we have option `online-mode` and commentary what meaning you can connect without authenticated to Xbox Live.
Can you please add like `auth-type: super-offline` support or just make connect to server without Xbox Live account.
**Alternatives?**
I tried floodgate, but it request install to server plugin and Foodgate is says **DO NOT DISTRIBUTE THIS KEY TO ANYBODY!** about `encrypted.txt`. It's mean I can't give my friends file because this is not secure.

**Comment by rtm516** [comment]
Xbox accounts are free so there is no reason not to get one to play the game. There is no way of disabling the Xbox account requirement.

**Comment by smirnovv2007** [comment]
In some countries there are problems logging into Xbox Live
