### ISSUE TITLE
Internet goes off when connecting to server hosted on the same IP adress

### ISSUE THREAD

**Issue by S0M0G** [GeyserMC/Geyser#1960]
Whenever I connect to my Minecraft server with GeyserMC plugin installed i get the message disconnected from the server a few seconds later and my internet goes off for everyone. When I tried to use my Mobile data it worked. It doesn't work if I'm on the same IP adress as the server itself.

**Comment by Camotoy** [comment]
This doesn't sound like a Geyser issue - we don't touch any network outside of running our own program. Maybe try hopping on our Discord? If you still feel this is an issue, please follow the bug report issue template. Thank you!

**Comment by S0M0G** [comment]
The template didn't appear.
