### ISSUE TITLE
**Join to Geyser without XboxLive**

### ISSUE THREAD

**Issue by Klubuntu** [GeyserMC/Geyser#1961]
**Please add**
Join to Geyser without Xbox Live, because, how do I join Geyser when I don't have the internet on the Internet and the hotspot from another device does not give me anything, because I want to continue joining via Xbox Live

**Alternatives**
auth-type: offline no working to disable join in Xbox Account

**Comment by Chew** [comment]
Duplicate of many issues. All boiling down to "There is no way of disabling the Xbox account requirement," and there never will be. If you don't have enough internet to sign in to Xbox, I highly doubt you'll have enough internet to actually join and play a game.

**Comment by Klubuntu** [comment]
My network isn't stable and often throw out

**Comment by IceBaka** [comment]
Offical Bedrock Server allow players join without xbox account in offline mode.Why Geyser can't?

**Comment by toinouH** [comment]
> Offical Bedrock Server allow players join without xbox account in offline mode.Why Geyser can't?

Because we do not support piracy.

**Comment by Chew** [comment]
Because Xbox accounts are free and there's 0 reason to not make one

**Comment by KaffinPX** [comment]
In my xbox my java edition nickname is in usage so i think its a good idea.

**Comment by xjh2009** [comment]
But how to use in WDPE

**Comment by MrZomka** [comment]
> My network isn't stable and often throw out

If your network is unstable, you won't be able to play even without Xbox Live.


> In my xbox my java edition nickname is in usage so i think its a good idea.

The only way to join servers without Xbox Live is to remove the Xbox Live check, which is usually done for piracy reasons.

**Comment by MrZomka** [comment]
> But how to use in WDPE

How is WaterdogPE related to this conversation?

**Comment by TomatoGarden666** [comment]
You maybe not know,in china,we has the "greatwall firewall",so we can't link at the Mojang auth server,but it isn't we cannot play the game...

**Comment by rwonkensv2** [comment]
this is annoying

**Comment by xjh2009** [comment]
> > 但是如何在 WDPE 中使用
> 
> WaterdogPE 与这次对话有什么关系？

WDPE requires Xbox Live to be turned off in order to join the server.
