### ISSUE TITLE
Can't hold anything else than shield in offhand

### ISSUE THREAD

**Issue by S0M0G** [GeyserMC/Geyser#1962]
**Describe the bug**
On Java, you can hold anything in your offhand, but in bedrock, I don't think that u can which makes it not possible to hold anything else than a shield in your offhand in a GeyserMC (plugin) server

**To Reproduce**
Join a world with GeyserMC (plugin) installed. Try to put something in your off-hand except the shield.

**Expected behavior**
You should be able to hold whatever item you want in your off-hand.

**Screenshots / Videos**
https://youtu.be/qF9A8h4sHus

**Server Version and Plugins**
Paper 1.16.5 466.
Plugins: GeyserMC, Openinv, SkinsRestorer
Geyser version: Geyser (git-master-f2550de) 1.16.201 (Vanilla).

If this bug occurs on a server you do not control, please fill this to the best of your knowledge.

**Geyser Dump**
https://dump.geysermc.org/OZiqPDtSi0RaD9oOdhpsfXFeJ8ojuVxw

**Minecraft: Bedrock Edition Version**
Minecraft BE 1.16.201

The version of your Minecraft: Bedrock Edition client you tested with, along with your device type (e.g. Windows 10, Switch...).
Minecraft BE 1.16.201 Win 10

**Additional Context**

**Comment by Camotoy** [comment]
Unfortunately, we can't do anything about this. :( Bedrock locks the offhand slot on their hand, and we can't do anything about it. Our workaround is present as a command: `/geyser offhand`, which switches the main and offhand item.
