### ISSUE TITLE
Geyser doesn't start correctly.

### ISSUE THREAD

**Issue by MinhCrafters** [GeyserMC/Geyser#1966]
**Describe the bug**

When I start the server, geyser plugin just return a java.lang.NoSuchFieldError: SPIGOT error and I can't connect to my server.

**To Reproduce**

1. Start the server.
2. See error.

**Expected behavior**

Geyser should start correctly.

**Screenshots / Videos**

https://imgur.com/a/Tvv2BNZ

**Server Version and Plugins**

**Geyser Dump**

**Minecraft: Bedrock Edition Version**

Minecraft: Bedrock Edition 1.16.201 for Android

**Additional Context**

**Comment by Camotoy** [comment]
Update Floodgate.
