### ISSUE TITLE
geyser wont work on my Paper MC server

### ISSUE THREAD

**Issue by bixwyd** [GeyserMC/Geyser#1969]
**Describe the bug**
Whenever I start my server, I keep retaining this error
ERROR Failed to start Geyser on 0.0.0.0:19132 , and then a string of errors like 
WARN java.util.concurrent.CompletionException: java.net.BindException: Address already in use
22.02 12:46:43 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
22.02 12:46:43 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
22.02 12:46:43 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1423)
22.02 12:46:43 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1144)
22.02 12:46:43 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
22.02 12:46:43 [Server] WARN at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
22.02 12:46:43 [Server] WARN at com.nukkitx.network.util.Bootstraps.lambda$allOf$0(Bootstraps.java:111)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1009)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:552)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
22.02 12:46:43 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

**To Reproduce**

1. Go to install geyser on a Paper 1.16.5 (I'm using geyser-spigot)
2. Click on restart
3. Scroll down in console and look to see for the warnings

**Expected behavior**

I expected geyser to start and recognize my floodgate key and allow me to do bedrock/java
**Screenshots / Videos**

**Server Version and Plugins**
Paper 1.16.5 
If you just run Geyser-Spigot, you can leave this area blank as the next section covers this information.

If you're running a multi-server instance, or using Geyser Standalone:

- Give us the exact output from `/version` on all servers involved. Saying "latest" does not help us at all.
- Please list all plugins on all servers involved.

If this bug occurs on a server you do not control, please fill this in to the best of your knowledge.

**Geyser Dump**

If Geyser starts correctly, please also include the link to a dump by using `/geyser dump`. If you use the Standalone GUI, the option can be found under `Commands` => `Dump`. This provides us information about your server that we can use to debug your issue.

**Minecraft: Bedrock Edition Version**

The version of your Minecraft: Bedrock Edition client you tested with, along with your device type (e.g. Windows 10, Switch...).
Latest version, Windows 10 PC
**Additional Context**

Nothing,  just need answers and help.

**Comment by Camotoy** [comment]
There is already something running on that port. 

Since this is a setup issue, we recommend joining our Discord for assistance.
