### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by GoldenMyst** [GeyserMC/Geyser#1971]
**Describe the bug**

When a player joins the server crashes and spams an error.

**To Reproduce**

1. Install Geyser
2. Join the server

**Expected behavior**

No crashes or errors

**Screenshots / Videos**

**Server Version and Plugins**

1.16.5 Tuinity

**Geyser Dump**

**Minecraft: Bedrock Edition Version**

1.16.201 on Iphone

**Additional Context**

Error: https://pastebin.com/FgUAvVMy

**Comment by Camotoy** [comment]
Please provide a complete log if possible, as well as a Geyser dump.

**Comment by Camotoy** [comment]
Additionally, try disabling `allow-third-party-capes`, restart, and see if your issue is resolved.

**Comment by GoldenMyst** [comment]
It didnt work, so here.

Dump: https://dump.geysermc.org/LNFvJw0WsUXSodMtWZkLJrpia6B6sDr6
Log: https://pastebin.com/NRV8pRNR

**Comment by GoldenMyst** [comment]
@Camotoy any updates on this?

**Comment by Camotoy** [comment]
Does it happen on Paper?
Does it happen if you disable `passthrough-player-counts`?

**Comment by GoldenMyst** [comment]
> Does it happen on Paper?
> Does it happen if you disable `passthrough-player-counts`?

Still doesn’t work, but I found the problem. I tried removing plugins one by one and came down to the plugin “Citizens”. Idk why it caused the crashes tho...

**Comment by Camotoy** [comment]
Does Citizens crash on its own, or only in tandem with Geyser?

**Comment by GoldenMyst** [comment]
> Does Citizens crash on its own, or only in tandem with Geyser?

I haven’t tested it yet but I just know joining while having the citizens plugin loaded crashes the server on bedrock. I haven’t test with java yet. Also there is another issue, it keeps saying “cheats aren’t allowed on this level” when ever I execute a command

**Comment by Camotoy** [comment]
Disable Xbox achievements in your Geyser config.
