### ISSUE TITLE
cant see the server

### ISSUE THREAD

**Issue by shafiahaz2478** [GeyserMC/Geyser#1972]
![image](https://user-images.githubusercontent.com/69790524/108823701-3a844780-75da-11eb-8304-bb862a7869c1.png)
cant see the server i disabled the firewall even

**Comment by Camotoy** [comment]
You probably need to do this: https://github.com/GeyserMC/Geyser/wiki/Fixing-%22Unable-to-Connect-to-World%22#windows-10

In the future, please follow the issue template, and for connection issues like these we recommend you join our Discord. Thank you!
