### ISSUE TITLE
resourcepack feature called namespaces to organize them better.

### ISSUE THREAD

**Issue by anthony114669** [GeyserMC/Geyser#1974]
Hello, currently the Geyser resourcepack feature and these resourcepack converters doesn't support namespaces.
They must add that in order to support ItemsAdder as it uses a resourcepack feature called namespaces to organize them better.

this in order to accept important plugins like "items adder" wich create new items for minecraft like rubu swords, more food etc. i really like to used with bedrock edition, because all the bedrock players cant see the new items because that resource pack is not compatible at all with bedrock edition. thanks so much!

**Comment by Camotoy** [comment]
Looks like this request goes along with #210 which is discussing adding custom items in general. For organization, I'll close this issue in favor of that one, where there is already some progress going on. Thank you for making a feature request anyway!
