### ISSUE TITLE
Many utility blocks and crafting either don't work correctly or look different

### ISSUE THREAD

**Issue by Meltinglce** [GeyserMC/Geyser#1975]
**Describe the bug**

Many utility blocks, such as smithing tables, cartography tables, grindstones, etc. don't work. When crafting, on consoles you are unable to use the A or Y buttons to craft. Instead you have to press X, move over to the item being crafted, and hit A. With enchantment tables, the enchanting UI is much different than what it should be.

**To Reproduce**

Simply try to open a utility block or craft how you normally would (on consoles), usually doesn't work.

**Expected behaviour**

Smithing tables, cartography tables, enchantment tables, etc.: Should open the normal GUI

**Screenshots / Videos**

_No response_

**Server Version and Plugins**

Tuinity 1.16.5 "a539774"
Floodgate, oldcombatmechanics, plugman

**Geyser Dump**

https://dump.geysermc.org/aSLalTwwwAYT4mCoH5ujuTo9wyF5JUJM

**Geyser Version**

1.2.0-snapshot "c4573bb"

**Minecraft: Bedrock Edition Version**

1.16.201

**Additional Context**

_No response_

**Comment by Camotoy** [comment]
All of these are either addressed in the README or are already issues. The `server-inventory` branch should fix all of these issues. Thank you for making an issue anyway!

**Comment by Meltinglce** [comment]
For my brother (on xbox), with the `server-inventory` plugin, everything works, but once you craft or trade normally once, it immediately goes back to how it was with the master branch. However, when I was testing (on pc), it seemed to work fine. Very weird.
