### ISSUE TITLE
Weird Disconnect bug

### ISSUE THREAD

**Issue by ELRandomMan** [GeyserMC/Geyser#1976]
**Describe the bug**

Whenever I am playing in my server, on bedrock, randomly after about 2-5 minutes it will disconnect me saying disconnected from server.

**To Reproduce**

join the server and wait.

**Expected behaviour**

It shouldn't disconnect

**Screenshots / Videos**

_No response_

**Server Version and Plugins**

_No response_

**Geyser Dump**

https://dump.geysermc.org/LiXaDj4cdiXGqMWCLPP2LzELRbE0YGSb

**Geyser Version**

I am not sure how to find this, I do know that I downloaded the latest version recently yesterday
(edit) I found the version it is 1.2.0 snapshot

**Minecraft: Bedrock Edition Version**

1.16.201

**Additional Context**

_No response_

here is the log if you need it  
[latest.log](https://github.com/GeyserMC/Geyser/files/6038326/latest.log)

**Comment by Camotoy** [comment]
Please provide a Geyser dump.

**Comment by ELRandomMan** [comment]
> Please provide a Geyser dump.

I have edited my issue and added a dump file

**Comment by Camotoy** [comment]
Perhaps see if switching to Paper would resolve the issue?

**Comment by ELRandomMan** [comment]
> Perhaps see if switching to Paper would resolve the issue?

Do you think it could be that I am using an IPv6 address to host the server? Even if it is not, do you know how to switch it to IPv4?

**Comment by ELRandomMan** [comment]
> Perhaps see if switching to Paper would resolve the issue?

Im not sure what you mean by paper

**Comment by BeetGaming45** [comment]
i have a PaperMC server and the same problem occurs ,here's the log link
https://mclo.gs/32tVtaC

line: 863
line: 2079

**Comment by RednedEpic** [comment]
This is not caused by Geyser - the `Stopping the server` message in the log indicates something (whether it be your host or another plugin) is forcefully executing the `/stop` command.



> i have a PaperMC server and the same problem occurs, here's the log link
> https://mclo.gs/32tVtaC
> 
> line: 863
> line: 2079

In your case this, looks to possibly be ClearLag; not caused by Geyser here.
