### ISSUE TITLE
Suggestion: Mojang login, players support memorizing information

### ISSUE THREAD

**Issue by BingYanchi** [GeyserMC/Geyser#1977]
It is recommended to give an option to remember when choosing Mojang to log in. No need to pass the verification on the Java side, just confirm that the Mojang account password can log in, and then bind the xbox id.

If possible, I would like to add another one to log in directly with a user name. Just enter the user name to log in. (Suitable for some servers with login plugins) I hope these two functions can be implemented at the same time, because there are some servers that can use Fastlogin to make Mojang logged-in players and offline logged-in players play together.

**Comment by RednedEpic** [comment]
We aren't going to support any form of "memorizing login information". What we do now have implemented in Floodgate is global linking, meaning you link once and on every other server that has global linking enabled, your accounts remain linked.
