### ISSUE TITLE
trading does not seem to work

### ISSUE THREAD

**Issue by Meltinglce** [GeyserMC/Geyser#1978]
**Describe the bug**

With a controller or with pc, selecting a trade and pressing A or right clicking on a trade will not trade the item. On PC, it is a bit more bearable, but on consoles, it is incredibly annoying.

**To Reproduce**

Try to trade with a villager.
Right click and/or press A on a trade
On the first try, it should work.
Close and re-open the trading menu
After that, it seems to not trade correctly.

**Expected behaviour**

When pressing A or right clicking, it should subtract the amount of emeralds required for the trade from the amount of emeralds you have, then give you the item.

**Screenshots / Videos**

https://www.youtube.com/watch?v=T_AtvmKv5j0

**Server Version and Plugins**

_No response_

**Geyser Dump**

https://dump.geysermc.org/iyzg6Cf2Z2hBxo6BVtmbDq9xmTk6Xr1O

**Geyser Version**

1.2.0-SNAPSHOT (git-server-inventory-e2df486)

**Minecraft: Bedrock Edition Version**

1.16.201

**Additional Context**

I have checked, we also have enough emeralds to do the trade.

**Comment by Camotoy** [comment]
Please try the latest server-inventory build.

**Comment by LichLord91** [comment]
I also had this issue, sorry i didn't report. I found that clicking the trade button seemed to work, ill test as well on my nintendo switch/windows 10. Just updated to latest.

**Comment by LichLord91** [comment]
Just tested and seems to be working well now. At least on my end :) 👍
