### ISSUE TITLE
Mounting Mobs on Bedrock Doesn't Work

### ISSUE THREAD

**Issue by ItzFlippp** [GeyserMC/Geyser#1979]
**Describe the bug**

I previously posted an issue regarding UltraSkywars and not being able to ride a dragon upon winning a game on bedrock edition, and I just noticed that you cannot mount mobs period on bedrock. When a bedrock player tries to mount a mob, such as a blaze through the Gadgets Menu plugin, the bedrock player gets ejected off the mob immediately and there is a message on the action bar that states "action.hint.exit.blaze". This also happened with the Ultra SkyWars Plugin. Just for context, this similar error happens on Java 1.16+ version players mounting mobs; however, the difference is the 1.16 java player is seen mounted on the mob for other players (such as players on java 1.8), and the java 1.16 player cannot move and is glitched within the mob. I am not certain if this bedrock issue is connected to ViaVersion or not, but bedrock players cannot mount entities without being ejected off.

**To Reproduce**

1. Install the Gadgets Menu plugin (free version works)
2. Launch server and open the gadgets menu through the hotbar item.
3. Click the item that says "Pets" and spawn a horse for example
4. Try to mount the horse by right clicking.

**Expected behaviour**

What I expect to happen is as soon as the bedrock player right clicks on the mob, they should be able to mount on top of the mob and stay mounted on the entity. The player should be able to move using W,A,S,D keys, or controller or mobile joysticks with the player controlling the mob, like being on a horse

**Screenshots / Videos**

https://vimeo.com/516897593

**Server Version and Plugins**

This server is running CraftBukkit version git-Spigot-fdc1440-53fac9f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

 Plugins (57): HackedCore, PlaceholderAPI, MiniBoardGames, NametagEdit, tpLogin, VisibilityToggle, TitleWelcomeMessage, NoteBlockAPI, NoDeathMessage, ViaVersion, NBTAPI, EZColors, icJukeBox, JukeBox, CustomHelpMessage, LuckPerms, WorldEdit, AntiRain, ChatInjector, HackedServer, BuycraftX, LiteFly, Multiverse-Core, ProtocolLib, iDisguise, PunishGUI, DeluxeMenus, AntiDisconnectSpam, CustomJoinItems, CustomJoinAndQuitMessages, Vault, VenientOptions, HolographicDisplays, WorldGuard, ChestCommands, noDamage, Essentials, GadgetsMenu, Lobby, CommandPanels, LiteBans, 1vs1, Citizens, AlonsoTags, EssentialsChat, TAB, ItemJoin, ProtectionStones, HolographicExtension, AlonsoLevels, EazyNick, CitizensCMD, EssentialsProtect, EssentialsGeoIP, EssentialsSpawn, PremiumVanish, TitleManager

**Geyser Dump**

 https://dump.geysermc.org/RJa4l3RCERSWxL7DHv3tmZ5CR0KvcWQ5

**Geyser Version**

 version 1.2.0-SNAPSHOT (git-master-1ec589f) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201)

**Minecraft: Bedrock Edition Version**

1.16.201

**Additional Context**

_No response_

**Comment by RednedEpic** [comment]
Seems to be a limitation over the protocol of 1.16 or a bug on Via's end. https://github.com/ViaVersion/ViaVersion/issues/2119 for more info. Highly recommended that you update past 1.8 as it's an ancient version.
