### ISSUE TITLE
Shulker boxes shown upside down on open

### ISSUE THREAD

**Issue by LichLord91** [GeyserMC/Geyser#1980]
**Describe the bug**

Shulker boxes get flipped upside down when opened and also the open animation is downward. 
Possibly related to https://github.com/GeyserMC/Geyser/pull/446 ?

**To Reproduce**

1. open any shulker box that is right side up 
2. you'll see it open downward and the shulker box is now upside down

**Expected behaviour**

To open in the direction originally placed and not be flipped upside down for bedrock users

**Screenshots / Videos**

https://streamable.com/r6wayy

**Server Version and Plugins**

Everything is in dump below

**Geyser Dump**

https://dump.geysermc.org/iGiKker1rziCLIaO2vagAqZTDoXAxnFK

**Geyser Version**

1.2.0-SNAPSHOT (git-server-inventory-e1db626)

**Minecraft: Bedrock Edition Version**

1.16.201 windows/switch

**Additional Context**

_No response_

**Comment by LichLord91** [comment]
This has been an issue for awhile just haven't reported till now. Not sure if this issue exist in the master branch.

**Comment by Camotoy** [comment]
Resolved in acbcf4baf32f3cf21730cbe3aa1270d88ae2d25b.

**Comment by LichLord91** [comment]
Thanks Camotoy ❤️ ill give it a whirl!

https://media.giphy.com/media/ncsQI9sF3pa8w/giphy.gif

**Comment by LichLord91** [comment]
Tested in my windows 10/switch, looks good 👍
