### ISSUE TITLE
(Server-Inventory-Branch) Books don't appear on lecterns upon relogining in 

### ISSUE THREAD

**Issue by LichLord91** [GeyserMC/Geyser#1981]
**Describe the bug**

Books on lecterns do not appear to display on them unless you right click on the lectern itself then itll show. However re-logining shows them gone once again. 

May be related to https://github.com/GeyserMC/Geyser/issues/1529 

**To Reproduce**

1.  place a book on a lectern
2. re login to game using bedrock client
3. see if book is visible and if you're able to make it reappear by trying to open the lectern

**Expected behaviour**

Books to show on Lecterns automagically

**Screenshots / Videos**

https://streamable.com/lnig5h

**Server Version and Plugins**

info in Geyser dump below

**Geyser Dump**

https://dump.geysermc.org/d2fztaNhzuJEMwGsqT3IShiqzolI1NAs

**Geyser Version**

1.2.0-SNAPSHOT (git-server-inventory-acbcf4b)"

**Minecraft: Bedrock Edition Version**

1.16.201 windows/switch

**Additional Context**

_No response_

**Comment by Camotoy** [comment]
Addressed in 13c924f841c95b69bc75212550191a914e213467.
