### ISSUE TITLE
Some items are difficult to put into the chests normally

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Geyser#1983]
**Describe the bug**

Some items are difficult to put into the box normally
(For example, items from MythicMobs...?)

**To Reproduce**

Selected item(Note: This item is a MythicMobs item)
![Screenshot_20210226_215203_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/109308568-27dd6d00-787d-11eb-9fd4-89211b0357bf.jpg)
Try to put in the chest
Item will be stuck.
And cannot manipulate items. 
![Screenshot_20210226_215206_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/109308726-5e1aec80-787d-11eb-988d-3d8feb17f2c1.jpg)
If you close the interface at this time
Item may drop
(This caused some gui plugins to not work properly)

**Expected behaviour**

Items should be put in the chest correctly

**Screenshots / Videos**

_No response_

**Server Version and Plugins**

Tuinity(Paper's fork) 1.16.5-R0.1
![IMG20210226220243](https://user-images.githubusercontent.com/53421735/109309545-5f004e00-787e-11eb-8bfa-20a8d35cae7d.jpg)

**Geyser Dump**

_No response_

**Geyser Version**

 ![IMG20210226220530](https://user-images.githubusercontent.com/53421735/109309840-c0c0b800-787e-11eb-85ec-ced2ca248596.jpg)

**Minecraft: Bedrock Edition Version**

1.16.200

**Additional Context**

_No response_

**Comment by RednedEpic** [comment]
Is this still an issue?

**Comment by zimzaza4** [comment]
This issue is probably resolved

**Comment by Jens-Co** [comment]
I'll close this issue for now, If you encounter this issue again I will reopen this. Thanks!
