### ISSUE TITLE
Bedrock can't interact with World!

### ISSUE THREAD

**Issue by d1ddle** [GeyserMC/Geyser#1985]
**Describe the bug**

Bedrock Edition (Win 10) Players cannot interact with the world. EG:
-Open doors,
-Open chests
-Place blocks

There could be multiple factors contributing to this but its more likely the fact that I have my server running as a Windows Service (kinda) - https://github.com/vincss/mcsleepingserverstarter
I have Sleeping Server Starter installed as the service executable so that when the service starts, it starts the executable which listens on port 25565 and starts the server when a player requests to join. This is also why it does not automatically start the server from Bedrock because as we all know, Bedrock uses port 19132. However this doesn't likely contribute to the fact that Bedrock clients can't interact with the world. In the server console I have errors such as 
`[15:05:43] [Server thread/WARN]: *CitywideMars50 moved wrongly!`
Which I got with my previous attempt, and I understand this is getting improved.

Thank you very much for your time, even if this is a stupid config error 😅

**To Reproduce**

1. Create a Paper 1.16.5 server in a place like Documents and install the plugins: Geyser version specified, floodgate, EmptyServerStopper v.03 https://dev.bukkit.org/projects/emptyserverstopper
and WebConsole (To view the command-line prompt) https://www.spigotmc.org/resources/webconsole.70370/
2. Download the Non Sucking Service Manager (NSSM.exe) for Win-64 and place in the server directory. https://nssm.cc/download
3. Download SleepingServerStarter.exe and place in the server directory. (1.16.4 build works with 1.16.5)
https://github.com/vincss/mcsleepingserverstarter/releases/tag/1.16.4
4. Open an admin command prompt and type in "cd (server directory)".
5. Type in "nssm install Minecraft Server Service" without the quotes at the beginning and end. Note: You will need administrator permission to install a service. Don't worry, you can uninstall it later.
6. Select SleepingServer.exe as the Application Path and your server directory as Startup Directory.
7. Change to the Log On tab and type in your credentials. Note: Required!! (Service can be removed later.)
8. Click Install Service. 
9. Open Services.msc (type services into windows search)  and start the service. You should then be able to connect to the server in Minecraft. Note: After entering the IP, a Sleeping Server Icon and MOTD should display. Once you join, it will start the server and you can reconnect. On Bedrock, the server must have already been started for a Bedrock player to join. IE not in Sleeping State (See your server icon)
10. To remove the service, repeat step 4. 
11. Instead of typing "nssm install", type "nssm remove Minecraft Server Service".

**Expected behaviour**

Bedrock player should be able to interact with the world: Open doors, place blocks etc

**Screenshots / Videos**

Video
(boy I'd feel stupid if this was a config error)
![image](https://user-images.githubusercontent.com/69437145/109327123-e4b8d500-784f-11eb-8f70-9c061bd44e9d.png)

https://youtu.be/SFVUmb0FkbY

**Server Version and Plugins**

git-Paper-483 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Checking version, please wait...
You are 15 version(s) behind
Plugins (9): DiscordSRV, https://bin.scarsz.me/f7491dba-1830-4fd7-af58-c1f493387fce#iU6mtokgtIlJDgPM3mzUTWiOZx6ezyYx
EmptyServerStopper*, v.03 , last updated to work with 1.9, works fine with 1.16.5
floodgate-bukkit, unknown..
Geyser-Spigot, (below)
LuckPerms, v5.2.76
Multiverse-Core, 4.2.2-b812
Vault, v1.7.3-b131
ViaVersion, https://dump.viaversion.com/6f1aa257fc302723d33f180866773dc30289f8b71bfcd25b73224ff410f987aa
WebConsole 2.1

**Geyser Dump**

https://dump.geysermc.org/4hAk6acoIOV2j4s4a70aiv0zyKcwHzSh

**Geyser Version**

1.2.0-SNAPSHOT (git-master-f480fbf) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201) You are 5 versions behind

**Minecraft: Bedrock Edition Version**

1.16.201

**Additional Context**

`#Minecraft server properties`
`#Fri Feb 26 15:00:55 GMT 2021`
`broadcast-console-to-ops=true`
`enable-query=true`
`enable-status=true`
`network-compression-threshold=256
`rcon.port=25575`
`server-port=25565`
`debug=false`
`server-ip=`
`spawn-npcs=true`
`online-mode=true`
`level-seed=`
`use-native-transport=true`
`prevent-proxy-connections=false`
`enable-jmx-monitoring=false`
`enable-rcon=false`
`rate-limit=0`

**Comment by Camotoy** [comment]
Developers love when you provide details. Thank you!

I would honestly suspect that the way you're running the server is not a part of this issue, but rather some sort of permissions issue. Try removing LuckPerms temporarily, or give your Bedrock player `op`.

**Comment by Camotoy** [comment]
Spawn protection was on.

**Comment by d1ddle** [comment]
Yeah Huh 😅

**Comment by 2br-2b** [comment]
I had the same problem. Note for future people: by default, Spawn Protection is enabled for 16 chunks. Change this to 0 to make it work!

https://minecraft.wiki/w/Server.properties#Default_content
