### ISSUE TITLE
add the banner on shield crafting feature on bedrock

### ISSUE THREAD

**Issue by BeetGaming45** [GeyserMC/Geyser#1986]
**What feature do you want to see added?**

a feature on java that makes it so that you can add custom banner on your shield on bedrock 

**Are there any alternatives?**

N/A

so considering that this software can make it so that java and bedrock can join at the same time with same command features, could it be possible for you to add the feature where you could add custom banners in our shield in bedrock?

**Comment by EasyClifton** [comment]
That's not how it works. Likely, the only way we could add this is create a separate shield item for each banner patters, but there are just too much patterns, so that would be pretty much impossible and impractical.

**Comment by Camotoy** [comment]
Yeah, this is very very very very very very unlikely.

**Comment by virivongithub** [comment]
This is just a idea but what if there was a armor stand holding the banner over the shield

**Comment by RednedEpic** [comment]
Not something we are interested in pursuing. Closing.

**Comment by Camotoy** [comment]
To be clear: we are interested in pursuing, but it's probably too much work to implement.

**Comment by Kas-tle** [comment]
We will be able to fix this in 1.20 per the preview released today.
