### ISSUE TITLE
Command suggestions duplicates

### ISSUE THREAD

**Issue by sisit135** [GeyserMC/Geyser#1987]
**Describe the bug**

When I type  '/' all commands suggestions show ''Link your Java and Bedrock account".

**To Reproduce**

1. Join the sever.
2. Type '/'.

**Expected behaviour**

Commands suggestion should not duplicate.

**Screenshots / Videos**

https://imgur.com/a/2hzN569

**Server Version and Plugins**

Paper version git-Paper-496 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugins (22): ClearLag, CommandPanels, DiscordSRV, elyby-skinsystem*, FakePlayer, floodgate-bukkit, Geyser-Spigot, HolographicDisplays, LagMonitor*, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, PlaceholderAPI, Plan, Positions*, RandomServerIcon*, Skywars, TouchscreenHolograms, VoidGenerator, WorldEdit, WorldGuard

**Geyser Dump**

https://dump.geysermc.org/uHCTgQ6tvDBHClTEo0dQx6DwnHe8BSxs

**Geyser Version**

Geyser version 1.2.0-SNAPSHOT (git-master-58e2c7d) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201)

**Minecraft: Bedrock Edition Version**

1.16.201 Windows 10

**Additional Context**

Log file : https://mclo.gs/86UxvXL

**Comment by Camotoy** [comment]
I did confirm this was an issue, but unfortunately re-implementing it seems to make command suggestions take even longer, so I'm not sure how I want to handle this.

**Comment by sisit135** [comment]
I think Geyser group plugins command incorrectly, with the same description.
The bug is not happening on vanilla commands.

This is a packet from server --> client.
https://wiki.vg/Bedrock_Protocol#Available_Commands
![packet-group](https://user-images.githubusercontent.com/63706816/109427773-7ed27600-7a26-11eb-98f3-57c3318902eb.PNG)

**Comment by Camotoy** [comment]
Yes, that is the bug. The problem is, by reverting that bug, command freezing (where the client freezes when typing `/`) has returned to a terrible amount.

**Comment by DUDEbehindDUDE** [comment]
you could try making command suggestions only load in once you've typed the first letter

**Comment by Camotoy** [comment]
There's no indication that the client has typed or opened the chat window.

**Comment by DUDEbehindDUDE** [comment]
then I would think the best way to go about this is to have a commands.yml file where you list all the commands that will be sent to the client, which could by default be a blacklist but could be changed to a whitelist

**Comment by MrRazamataz** [comment]
> then I would think the best way to go about this is to have a commands.yml file where you list all the commands that will be sent to the client, which could by default be a blacklist but could be changed to a whitelist

Until a solution to this is found, you could try a plugin called CommandWhitelist, I have heard it works and was going to config it for my server soon.

**Comment by Camotoy** [comment]
This has been fixed.
