### ISSUE TITLE
Walking on snow is broken (cant move just like slab used to do)

### ISSUE THREAD

**Issue by ImT3chy** [GeyserMC/Geyser#199]
**Describe the bug**
When trying to move on snow your player gets stuck onless its a full block or slab higb snow.
**To Reproduce**
1. Make snow in diffenrt highst
2. Try walking on it

**Expected behavior**
walk just like normal and there moving

**Server version**
Git-spigot-8faa8b4-7f61a25 (1.15.2) Api Version 1.15.2-RO.1-snapshot

**Geyser version**
Inventory 7

**Bedrock version**
1.14.30

**Comment by AnonAlpha** [comment]
Here's a supplement for this issue
#204

**Comment by Loganh4005** [comment]
What I think is Java and Bedrock have different meshes for snow. I think bedrock uses it  for you just walk in java detects that you are going into a block and pulls you back which flags the anti-cheat of you teleporting

**Comment by RednedEpic** [comment]
> What I think is Java and Bedrock have different meshes for snow. I think bedrock uses it for you just walk in java detects that you are going into a block and pulls you back which flags the anti-cheat of you teleporting

It's because when walking on snow in Java, your player is actually put on top of the snow block, opposed to bedrock where for the first couple of layers, the player does not move up the snow.

**Comment by Loganh4005** [comment]
That is what I was trying to say but can't we get the client to display a resource pack that has the snow actually a solid block or am I just crazy

**Comment by RednedEpic** [comment]
Superseded by #204.
