### ISSUE TITLE
Villager job site blocks not working for bedrock users.

### ISSUE THREAD

**Issue by GSG002** [GeyserMC/Geyser#1991]
**Describe the bug**

Job site blocks such as cartography tables, stonecutters and looms are not bringing up the UI and act like normal blocks. The blocks still give villagers professions. 

**To Reproduce**

1. Right click any profession block with a UI using a bedrock account

**Expected behaviour**

A UI appears and allows the user to craft

**Screenshots / Videos**

_No response_

**Server Version and Plugins**

_No response_

**Geyser Dump**

https://dump.geysermc.org/iNNdaxwdfOdttxzSdZR5UJGn6KvFDLAA

**Geyser Version**

1.2.0-SNAPSHOT (git-master-498f765)

**Minecraft: Bedrock Edition Version**

1.16.201

**Additional Context**

_No response_

**Comment by Camotoy** [comment]
This is mentioned in the README and will be fixed in the inventory rewrite. As such, I am closing for tidiness. Thank you for reporting!
