### ISSUE TITLE
Massive CPU leak

### ISSUE THREAD

**Issue by Joshinn-io** [GeyserMC/Geyser#1992]
**Describe the bug**

We tried geyser 6~ months ago using the bungee version, and after a random amount of uptime the geyser instance on the machine would be eating every core available and tanking every server on the box. We decided to help report it and noticed others were having the same issue, due to time constraints we had to drop using geyser. Fast forward to now, we need geyser for this project again, and using the standalone version produced the same CPU usage issues after about 2 days of uptime on our first run at it.

https://thereefmc.gg/resourcepack/output.txt
Here is a thread dump during geyser going haywire. It seems that both of the top (and only memorable) culprits are originating from org.geysermc.connector.network.translators.java.world.JavaUpdateTileEntityTranslator.translate after an Object2IntOpenHashMap call. I assume if this one problem point was looked at, the issues would go away.

**To Reproduce**

Run a server with geyser standalone / bungee (not sure if it exists on all, it probably does.

Have a few hundred geyser players joining over the course of a day or two.

It just happens randomly.

**Expected behaviour**

Not crash an entire dedicated machine.

**Screenshots / Videos**

https://cdn.discordapp.com/attachments/613169789900161035/815693207765647400/image0.png

As you can see from the top line of the HTOP output, Geyser.jar is using 1532% cpu out of 1600%.

**Server Version and Plugins**

This server is running AirplaneLite version git-AirplaneLite-"459bb20" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) <-- Issues was reproduced on paper as well, same issue, so don't blame airplane plz.

Enabled Waterfall version git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:1d2221d:384

[14:54:11 INFO]: Plugins (54): AdvancedEnchantments, BetterRTP, BlockParticles, ChatBrawl, Chunky, Citizens, Companions, CoreProtect, CrazyCrates, DeluxeMenus, dynmap*, eGlow, Elevator, Essentials, EssentialsProtect, EssentialsSpawn, FactionsX, FastAsyncWorldEdit (WorldEdit), FastChunkPregenerator, HeadDatabase, HolographicDisplays, Jobs, LibsDisguises, LiteBans, LuckPerms, LumineChat, LumineCore, LumineParties*, MarketPlace, MarriageMaster, mcMMO, MMOItems, MMOLib, Multiverse-Core, MythicCrucible, MythicMobs, Outpost*, PinataParty, PlaceholderAPI, PlayerParticles, PlayerVaults, PluginHiderPlus, PocketGames, ProtocolLib, ReefCore, ShopGUIPlus, ShopGUIPlusSilkSpawnersBridge, SilkSpawners, spark, TAB, Terra, Vault, VeinMiner, WorldGuard

**Geyser Dump**

https://dump.geysermc.org/ZwGpNY5iwQ2TxEI4tRjIGy4efpFjpgVW   This is post restart sadly, will try and get one if it spikes again to update the ticket.

**Geyser Version**

This server is running Geyser version 1.2.0-SNAPSHOT (git-master-f480fbf) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201)

**Minecraft: Bedrock Edition Version**

This server is running Geyser version 1.2.0-SNAPSHOT (git-master-f480fbf) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201) <-- Shows it in there

**Additional Context**

_No response_

**Comment by Joshinn-mc** [comment]
https://github.com/GeyserMC/Geyser/issues/1229 https://github.com/GeyserMC/Geyser/issues/930

Related issues. Old and never got fixed.

**Comment by Camotoy** [comment]
Two things you should try:

- Update Geyser to the latest version. We just updated the dependency that HashMap is from.
- Enable cache chunks, which prevents those top two methods in your stack trace from being called.

**Comment by Joshinn-mc** [comment]
Will try these things and report back in a few days... it’s hard to always be on latest for these reports because they take a few days sometimes to pop up, and by then we’re outdated. Good to hear the maps were just updated.  Will also try that option.

**Comment by Jens-Co** [comment]
Hello @Joshinn-io, Did you resolve your problem? hope ill get some feedback, Issue will be closed within a few days.

**Comment by Jens-Co** [comment]
I will close this issue due to no response, if this still occurs please let me know and I'll reopen this issue. Thanks
