### ISSUE TITLE
MOTD and Ping not coming through on Server List

### ISSUE THREAD

**Issue by BloxBoss6** [GeyserMC/Geyser#1993]
**Describe the bug**

Exactly as the title says, I've been getting an error where when I type the IP of my geyser server on bedrock, nothing passes through the server list. It works perfectly in the friends list.

In the server list below the name it just says "Locating server".
Then when I click on the server, it says "Online:" and has the picture of the player, but nothing else there.
Below that it says "Current Ping:" and then a red dot.

**To Reproduce**

Not sure, since I can't find anyone else having this issue.

**Expected behaviour**

It is supposed to show the MOTD, the online players amount, and the current ping for the server.

**Screenshots / Videos**

https://imgur.com/gallery/IjGakcl

**Server Version and Plugins**

_No response_

**Geyser Dump**

_No response_

**Geyser Version**

This server is running Geyser version 1.2.0-SNAPSHOT (git-master-f480fbf) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201)

**Minecraft: Bedrock Edition Version**

1.16.201

**Additional Context**

_No response_

**Comment by Camotoy** [comment]
Are you able to connect to the server?

**Comment by BloxBoss6** [comment]
> Are you able to connect to the server?

Yes, I'm able to join the server. I just tried from a different network, and now it works, I guess it was just getting confused being on the same wifi.
