### ISSUE TITLE
I have a gear vr with minecraft bedrock 1.16.40 and I want to play with my friends but I can't

### ISSUE THREAD

**Issue by javapcl** [GeyserMC/Geyser#1994]
**Describe the bug**

English:
Hello everything that read this, I have had a giant problem with geysermc, since I have been trying to use geysermc with minecraft bedrock 1.16.40 but it gives me the typical error "CLOSED_BY_REMOTE_PEER" and I cannot enter the server, it should be clarified that I do not I own that server so I can't install a plugin to fix it. I have tried to use geysermc standalone, or mostly the version for windows 10 to connect through my local network, but it keeps giving me the error. I have asked on the discord server and they have told me to use viaversion, geyser reversion, or directly install build 480 but I don't know how to configure any of those 2 plugins, does anyone know what I could do to play with my friends? plssssssssssssssss

Español:
Hola a todos los que lean esto, he tenido un problema gigante con geysermc, ya que he estado tratando de usar geysermc con minecraft bedrock 1.16.40 pero me da el tipico error "CLOSED_BY_REMOTE_PEER" y no puedo entrar al server, cabe aclarar que yo no soy dueño de ese servidor entonces no puedo instalar un plugin para solucionarlo. He tratado de usar geysermc standalone, o más que nada la versión para windows 10 para conectarme por mi red local, pero me sigue dando el error. He preguntado en el servidor de discord y me han dicho que use viaversion, geyser reversion, o instalar directamente la build 480 pero no sé configurar ninguno de esos 2 plugins, alguien sabe que podria hacer para jugar con mis amigos? plssssssssssssssss

**To Reproduce**

Minecraft Bedrock 1.16.40
with any versión of java.

**Expected behaviour**

I need to play with my friends but ican´t find a compatible version.

**Screenshots / Videos**

_No response_

**Server Version and Plugins**

_No response_

**Geyser Dump**

_No response_

**Geyser Version**

Build 628

**Minecraft: Bedrock Edition Version**

1.16.40

**Additional Context**

_No response_

**Comment by Camotoy** [comment]
https://ci.opencollab.dev//job/GeyserMC/job/Geyser/job/master/480/ you will not receive support for this build, nor can it support 1.16.100+.

https://github.com/bundabrg/GeyserReversion is another option if you absolutely need 1.16.100+ support as well.
