### ISSUE TITLE
error with users being able to craft items

### ISSUE THREAD

**Issue by FallingGames** [GeyserMC/Geyser#1996]
### Describe the bug

some users are unable to use certain items and also cant craft items in the crafting table.

### To Reproduce

1. open a crafting table
2. try to craft an item

### Expected behaviour

it wont allow them to craft item

### Server Version and Plugins

we use 1.16.5

### Geyser Version

newest version

### Minecraft: Bedrock Edition Version

1.16.201

**Comment by Camotoy** [comment]
I'm closing this as there is no Geyser dump and this issue has likely been reported. If the players are console players, this is definitely known and will be fixed in the inventory rewrite.
