### ISSUE TITLE
[Bug]Flickering sky with authentic-vanilla server.

### ISSUE THREAD

**Issue by Neubulae** [GeyserMC/Geyser#200]
**Describe the bug**
While using a server that's implemented in the vanilla way, i.e. official server jars, the day-night cycle is broken, resulting in a flickering sky.

**To Reproduce**
Just use an official jar to host the server.

**Expected behavior**
A clear and concise sky behavior.

**Server version**
Official 1.15.2

**Geyser version**
Inventory #7

**Bedrock version**
1.14.30

**Comment by RednedEpic** [comment]
Unable to reproduce on my end, though we've received a couple reports of this. Could you please provide a video?

**Comment by Neubulae** [comment]
> Unable to reproduce on my end, though we've received a couple reports of this. Could you please provide a video?

Are you using an vanilla official jar? I am using 1.15.2 official by the way.

**Comment by Neubulae** [comment]
Oh I forgot a detail: the ingame time is currently a very high number, around 500000 days passed I guess, Imanually set that just for fun but I remembered that being there before I change the day.
