### ISSUE TITLE
i cannot play without a xbox live account

### ISSUE THREAD

**Issue by javapcl** [GeyserMC/Geyser#2004]
### Describe the bug

Yeah, I looked in issues and the people is screaming for it to be played without xbox live, because in my case (I already made a question about gear vr) I have a VR of samsung x oculus but the VR does not work with the phone that I use  (Samsung S8 +)  haves compatibility for the most recent VR models that have USB-C, and Oculus haves a developer mode that allows you as if you had the VR  , and I use that to play minecraft, and it is difficult for me to log in to xbox live since it is impossible to achieve, I tried a thousand ways and still I could not, and I must necessarily be without an xbox live account and that leads to not being able to play my friends' server from bedrock since geysermc begs me to use one xbox live account and can't use it :\

### To Reproduce

...

### Expected behaviour

...

### Geyser Version

...

**Comment by javapcl** [comment]
And YES, I bought Minecraft on Oculus and Play store

**Comment by ImDaBigBoss** [comment]
Try setting `auth-type: offline`? But your server needs to be offline. There is no other way around it...

**Comment by javapcl** [comment]
Geyser And My Server Is On Offline Mode :/

**Comment by ImDaBigBoss** [comment]
Ah, that is bedrock doing it, if you are hosting locally, try setting your port to 19132 if it's not already done. Then remove your server from the server list. (You might need to reload Minecraft) Then join from the friends tab.

**Comment by javapcl** [comment]
humm, I already did all that, I already joined from the friends list and the bedrock port is set to 19132, I don't know what happens

**Comment by Giacomo213342** [comment]
Maybe try to reset the config and download the newest version of geyser?

**Comment by Camotoy** [comment]
It's time someone closes this. If you are having trouble logging into an Xbox account, Google is your friend, or perhaps even someone on the Geyser Discord will help you out! 

Have a good day.

**Comment by NachoToast** [comment]
I'm getting this issue too, was working fine before the Bedrock update (1.16.210) but after updating to 1.16.210 and build 637 neither 'floodgate' nor 'offline' are preventing the "sign in with xbox" message that prevents connection.

**Comment by Chew** [comment]
Not an issue, you need to sign in with Xbox regardless. Are you referring to Sign in with Microsoft or something once you're in?

**Comment by javapcl** [comment]
yes, i need to sign in with microsoft with the developer mode of oculus gear vr

**Comment by Chew** [comment]
Yeah once you're logged in, if you bought an account prior to December 1st, select "Sign in with Mojang", otherwise "Sign in with Microsoft". Though these options don't appear with Floodgate (or offline, I believe).

**Comment by javapcl** [comment]
i need to use offline mode and i have 1.16.40 because is the latest versión for gear vr
