### ISSUE TITLE
% is not displayed in Bedrock Edition

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Geyser#2009]
### Describe the bug

The "%" in the item name and lore is not displayed

### To Reproduce

Java:
![IMG20210307093756](https://user-images.githubusercontent.com/53421735/110226305-fde51400-7f28-11eb-8e0d-89d8da5732a4.jpg)
Bedrock:
![IMG20210307093812](https://user-images.githubusercontent.com/53421735/110226307-ffaed780-7f28-11eb-9af9-bda63eefb613.jpg)

### Expected behaviour

% should be displayed normally

### Server Version and Plugins

Tuinity 1.16.5 R0.1

### Geyser Version

![109309840-c0c0b800-787e-11eb-85ec-ced2ca248596](https://user-images.githubusercontent.com/53421735/110226375-8cf22c00-7f29-11eb-82d9-d8c24b5f5784.jpg)

### Minecraft: Bedrock Edition Version

1.16.201

**Comment by rtm516** [comment]
I'm unable to replicate this, can you send over the players inventory containing this item? `/world/playerdata/uuid.dat`

**Comment by zimzaza4** [comment]
Umm

**Comment by zimzaza4** [comment]
I used "/rename %" to change the name of the item
Will not be displayed in Bedrock Edition

**Comment by rtm516** [comment]
> I used "/rename %" to change the name of the item
> Will not be displayed in Bedrock Edition

That is not a vanilla command, what plugin is it from?

**Comment by zimzaza4** [comment]
CMI
If I use Skript to get the item, the item name still won’t show %

**Comment by rtm516** [comment]
Using this displays with no issues for me `/minecraft:give @p stick{display:{Name:'{"text":"Test 100%"}'}} 1`

**Comment by zimzaza4** [comment]
Umm
![IMG20210307195048](https://user-images.githubusercontent.com/53421735/110238776-6dd1b980-7f7e-11eb-98a1-b44cfcb00a01.jpg)
![IMG20210307195037](https://user-images.githubusercontent.com/53421735/110238778-6f02e680-7f7e-11eb-80bc-310380105eaf.jpg)

**Comment by rtm516** [comment]
This seems like a bedrock or plugin bug, can you provide a dump and what language is your game in?

**Comment by zimzaza4** [comment]
This is a client issue...

**Comment by zimzaza4** [comment]
I just tried it in bedrock vanilla
