### ISSUE TITLE
Lily Pads placement issue

### ISSUE THREAD

**Issue by RealBitslayn** [GeyserMC/Geyser#2012]
### Describe the bug

When you place a lily pad while only having one left, the lily pad doesn't place and it hides from your inventory. 

### To Reproduce

1. Place lily pad while only holding one.
2. Lily pad disappears.

### Expected behaviour

The lily pad should place correctly.

### Server Version and Plugins

This server is running Paper version git-Paper-441 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugins (18): DiscordSRV, dynmap*, DynmapBannerMarkers, Essentials, floodgate-bukkit, Geyser-Spigot, GeyserSkinManager, GeyserUpdater, Graves, LuckPerms, NoBoom, SignShop, SilkSpawners, StatsSB, SuperChairs, TimeIsMoney*, Vault, WorldBorder

### Geyser Dump

https://dump.geysermc.org/sKsZTlSlJZVk7kqhEIIwPuVrWcwNG01t

### Geyser Version

Geyser version 1.2.0-SNAPSHOT (git-server-inventory-814fa95)

### Minecraft: Bedrock Edition Version

1.16.201

**Comment by zimzaza4** [comment]
When you long press the screen, it can be placed normally

**Comment by RednedEpic** [comment]
Stale. Please open a new issue if this is still occurring w/ updated repro steps.
