### ISSUE TITLE
Elytras don't open

### ISSUE THREAD

**Issue by RealBitslayn** [GeyserMC/Geyser#2015]
### Describe the bug

Elytras don't stay open in survival at least. Trying to fly using an elytra doesn't work unless you spam the jump button.

### To Reproduce

1. Open elytra.
2. Attempt to fly.
3. Elytra closes a tick after you open it.

### Expected behaviour

You should be able to open the elytra normally.

### Server Version and Plugins

This server is running Paper version git-Paper-441 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugins (18): DiscordSRV, dynmap*, DynmapBannerMarkers, Essentials, floodgate-bukkit, Geyser-Spigot, GeyserSkinManager, GeyserUpdater, Graves, LuckPerms, NoBoom, SignShop, SilkSpawners, StatsSB, SuperChairs, TimeIsMoney*, Vault, WorldBorder

### Geyser Dump

https://dump.geysermc.org/sKsZTlSlJZVk7kqhEIIwPuVrWcwNG01t

### Geyser Version

Geyser version 1.2.0-SNAPSHOT (git-server-inventory-814fa95)

### Minecraft: Bedrock Edition Version

1.16.201

**Comment by Camotoy** [comment]
This *may* be a Bedrock issue - elytra activation behavior definitely differs between the two (I believe you can't activate an elytra in Bedrock if you're looking up?)

**Comment by RednedEpic** [comment]
Stale. Likely not a Geyser issue & if it is, please open a new issue with updated replication steps & a comparison of singleplayer & Geyser.
