### ISSUE TITLE
Failed to start Geyser

### ISSUE THREAD

**Issue by Jupitermastergit** [GeyserMC/Geyser#2018]
### Describe the bug

so i was using aternos to test out geyser for the first time. i downloaded the flooagate,right plugin version and the floodgate.i was starting the server then i saw a error and it says [Geyser-Spigot] Failed to start Geyser and then says java.util.concurrent.CompletionException: java.net.BindException: Cannot assign requested address and then a  load of console errors start to appear(sorry if my english is bad btw im not from a country that has english as native language)

### To Reproduce

1.create a new server in aternos
2. add geyser and floodgate
3.configurate the config for example set the remote ip to 120.0.0.1 or whatever the auto ip is
4.start the server
5. the error begins

then i tried to search how to fix it and i think no one ever reported it

### Expected behaviour

i just excepted it to load up the server without errors.

### Server Version and Plugins

version of the server is 1.16.5 ,im not using any plugins except geyser and floodgate.

### Geyser Version

 the geyser version is the 635th build of geyser-spigot 1.20 snapshot

### Minecraft: Bedrock Edition Version

1.16.201

**Comment by Camotoy** [comment]
You likely changed the `bedrock` `address` or `port` of your Geyser config. If you did, revert that. If you did not, then talk to Aternos, as it would likely be an error on their end.
