### ISSUE TITLE
Unable to Craft or enter a chest and use the crafting table (Not sure if this is a known bug

### ISSUE THREAD

**Issue by ChieflyDevon** [GeyserMC/Geyser#202]
**Describe the bug**
Im unable to use a crafting table or use chests.

**To Reproduce**
Im currently using the newest version of Geyser-bukkit along side original-floodgate-bukkit on a spigot 1.15 and Im unable to use both.

**Comment by jackson-57** [comment]
Use the inventory branch, as it has not yet been implemented in master.

**Comment by ChieflyDevon** [comment]
Do you know if i am able to use it alongside floodgate ?

**Comment by jackson-57** [comment]
Yes.

**Comment by ChieflyDevon** [comment]
Ah okay thank you

**Comment by ChieflyDevon** [comment]
Using the latest version of Geyser-Bukkit.jar inventory branch along side original-floodgate-bukkit.jar i receive the error:

org.geysermc.platform.bukkit.shaded.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Invalid packet id: 27

any ideas ?

**Comment by RednedEpic** [comment]
> Using the latest version of Geyser-Bukkit.jar inventory branch along side original-floodgate-bukkit.jar i receive the error:
> 
> org.geysermc.platform.bukkit.shaded.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Invalid packet id: 27
> 
> any ideas ?

Latest version of floodgate is currently incompatible with the inventory branch. Should have this resolved sometime tonight.

**Comment by ChieflyDevon** [comment]
Oh okay thank you and is there a previous version of floodgate that is compatible ?

**Comment by RednedEpic** [comment]
> Oh okay thank you and is there a previous version of floodgate that is compatible ?

The old version was bugged. Just wait a few hours and I should have it resolved.

**Comment by ChieflyDevon** [comment]
alright thank you
