### ISSUE TITLE
1.16.210 does not work on server-inventory branch

### ISSUE THREAD

**Issue by nickg2** [GeyserMC/Geyser#2021]
### Describe the bug

Players trying to join on 1.16.210 cannot join, it gives then the "geyser proxy outdated"  when trying to join.

### To Reproduce

1. install the (latest) server inventory branch
2. be on bedrock 1.16.210
3. try to join

### Expected behaviour

Be able to join correctly.

### Geyser Dump

https://dump.geysermc.org/tAbG8633N7Sk0oPCn0zzsBwNiWtMWUkb

### Geyser Version

Geyser version 1.2.0-sNAPSHOT (git-server-inventory-d80372e)

### Minecraft: Bedrock Edition Version

Bedrock 1.16.210 (mobile, havent tested other platforms)

**Comment by Camotoy** [comment]
You are not on the latest server inventory branch.
