### ISSUE TITLE
Teleport on 32k height after death

### ISSUE THREAD

**Issue by rymusov** [GeyserMC/Geyser#2022]
### Describe the bug

If player die in nether - he is die after respawn in overworld from fall(just double death).
This can happen in the ordinary world.
Tried two ways of geyser operation: separate core and plugin. It still has a 60% chance to teleport and you die.

### To Reproduce

1. Install Yatopia
2. Install Geyser
3. Go to nether
4. Fun from double death

### Expected behaviour

I think yatopia

### Screenshots / Videos

https://youtu.be/t2jwM1SepGw

### Server Version and Plugins

Version: git-Yatopia-ver/1.16.5-30 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Plugins (29): AdvancedBan*, BanAnnouncer*, Chatty, CoreProtect, CoreProtectTNT, CustomHelp*, DBVerifierLinker*, DiscordSRV, dynmap*, DynmapHider*, floodgate-bukkit, Geyser-Spigot, GSit, Harbor, InventoryRollback, InvisibleItemFrames, LuckPerms, OpenInv, PlaceholderAPI, Playtimes*, ProtocolLib, SkinsRestorer, Spicord*, TAB, Terra, TwoPlayerHorseRiding, UltimateAutoRestart, Vault, WorldBorder

### Geyser Dump

https://dump.geysermc.org/Rv4WoxcJbprABBa68OJqKer2uvLkt4Fw

### Geyser Version

1.2.0-SNAPSHOT (git-server-inventory-ded00df) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.210)

### Minecraft: Bedrock Edition Version

1.16.200/1.16.210

**Comment by rtm516** [comment]
Please try with normal paper, as we have had some incompatibilities with Yatopia before.

**Comment by rymusov** [comment]
I tried to run Yatopia and Paper on a separate hosting. Well with the clear paper everything was fine at death in nether. With Yatopia there was the same story as how it all began in the post.

**Comment by Tim203** [comment]
I recommend sticking with Paper in general. Yatopia is unstable and causes issues.

**Comment by rtm516** [comment]
> I tried to run Yatopia and Paper on a separate hosting. Well with the clear paper everything was fine at death in nether. With Yatopia there was the same story as how it all began in the post.

If it only happens with Yatopia its likely a bug on their end. Please raise it on their issue tracker.

**Comment by Tydium** [comment]
Hey Yatopia is kinda buggy right now. If you are trying to look for a better optimized version (THAT DOESN'T KILL GEYSER) I recommend Purpur. I've had some very good experience with it using geyser. Perhaps you could give it a try also.

**Comment by Camotoy** [comment]
@rymusov does Java experience any sort of similar inconsistency with death?

**Comment by rymusov** [comment]
> @rymusov does Java experience any sort of similar inconsistency with death?

No, all is okey. Only with bedrock
