### ISSUE TITLE
Bedrock Players break fire weird

### ISSUE THREAD

**Issue by gameusefly** [GeyserMC/Geyser#2023]
### Describe the bug

When Bedrock players break fire for the bedrock player the fire is gone but for the server and for java players the fire still there. Bedrock Players get also damage at the block where the fire is (but for bedrock players gone)

### To Reproduce

1. Bedrock or Java Player place an fire anywhere.
2. Bedrock Player break the fire that was placed by anyone.
3. For Bedrock Player the fire is gone but for the java player not.
4. On move on this block where the fire is placed bedrock player get damage 

### Expected behaviour

The Fire placement is not scuffed and weird

### Screenshots / Videos

https://prnt.sc/10i4bdu
https://prnt.sc/10i4bs4
https://prnt.sc/10i4c5u

### Server Version and Plugins

git-Purpur-1007 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugins (23): ArmorStandTools, AuctionMaster, BadlionClientModAPI, Citizens, CloudNet-Bridge, CloudNet-Signs, CoreProtect, CraftAttack, dynmap, FastASyncWorldEdit (WorldEdit), floodgate-bukkit, Geyser-Spigot, GSit, InventoryRollback, LuckPerms, Minecord, MobFarmManager, ProtocolLib, QuickShop, Vault, Votifier, VotingPlugin, WorldGuard.

https://timings.pl3x.net/?id=ff9c541c98a946e4833245c0a95e6c87

### Geyser Dump

https://dump.geysermc.org/FtREx4x1dW7MMSDjNuZuOJRBumaGkA7W

### Geyser Version

1.2.0-SNAPSHOT (git-master-f0e6e55)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Jens-Co** [comment]
Could not replicate this problem. tested on my own & official geyser server. Can you check if this problem still occurs on your server ? otherwise ill close this issue.

**Comment by Jens-Co** [comment]
This was already been patched.

**Comment by Camotoy** [comment]
More specifically, we've had no other reports of this issue. Anyone can feel free to reopen a new issue if they still experience this!
