### ISSUE TITLE
RealDual Plugin by LoneDev

### ISSUE THREAD

**Issue by Sentaku** [GeyserMC/Geyser#2025]
### What feature do you want to see added?

https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-real-dualwield-attack-with-both-hands-with-real-animation-without-mods.30816/

### Are there any alternatives?

Nothing; just wanted that feature to be added to geyser

I want to see if you guys can add this plugin to be compatible with geyser

I talked to Author of plugin and it needs offhand animation packets on left hand

**Comment by lukeeey** [comment]
Only certain items such as maps and torches can be placed in the offhand on Bedrock

**Comment by Camotoy** [comment]
As far as we know, there is no way to trigger a left-hand animation.

**Comment by Sentaku** [comment]
Oh okay.

**Comment by Camotoy** [comment]
This has been resolved with the OptionalPack for the third person - first-hand offhand animation has not been implemented. Either way, that's either no longer relevant to this repository or marked as a can't-fix, so I'm closing. Thanks!
