### ISSUE TITLE
Actionbar now shows as item name not actionbar

### ISSUE THREAD

**Issue by GoldenMyst** [GeyserMC/Geyser#2027]
### Describe the bug

Some devbuilds back the actionbar was correct but now it is a item name

### To Reproduce

1. Send Actionbar to player

### Expected behaviour

Expect the actionbar to be at the correct place

### Screenshots / Videos

https://user-images.githubusercontent.com/74118946/110717217-7c59e400-81bd-11eb-824a-8e8c3e013bfe.MOV

### Server Version and Plugins

Version: git-Tuinity-“f87cb79” (MC:1.16.5)

### Geyser Dump

https://dump.geysermc.org/uZ5XOc8aAoKn64LhgV5Mi3TFrrIxoRjw

### Geyser Version

1.2.0 SNAPSHOT git-server-inventory-ded00df

### Minecraft: Bedrock Edition Version

1.16.201

**Comment by Camotoy** [comment]
We have not changed action bar mapping recently. Perhaps this change occurred in Bedrock?

**Comment by GoldenMyst** [comment]
> We have not changed action bar mapping recently. Perhaps this change occurred in Bedrock?

It seems to work on bedrock, Also I thought it was my texture pack but it wasn’t when I disabled it.

**Comment by Camotoy** [comment]
There's not much we can do with this information, since that is mimicking correct action bar behavior.

- Are you able to determine when this broke?
- What do you think the action bar is supposed to look like on Bedrock?

**Comment by GoldenMyst** [comment]
> There's not much we can do with this information, since that video is mimicking correct action bar behavior, and therefore could be correct.
> 
> * Are you able to determine when this broke?
> * What do you think the action bar is supposed to look like on Bedrock?

1. After updating Geyser. (has already happened for 2-3 weeks now, in that time I tried to fix it but nothing worked)
2. The actionbar should have been more up (higher than the item name box)

**Comment by RednedEpic** [comment]
We have no control over the action bar position; it's more than likely your resource pack doing this.

**Comment by lukeeey** [comment]
It appears to not be a resource pack issue
