### ISSUE TITLE
Update indication system

### ISSUE THREAD

**Issue by Camotoy** [GeyserMC/Geyser#2028]
### What feature do you want to see added?

Some sort of update system that doesn't download the latest update, but indicates that either Bedrock or Java has updated and therefore require a Geyser update.

Considerations:

- There should likely be two settings for each platform. A Java update nag would just be informative and less important for people running a server. A Bedrock nag is likely far more important for our auto-updating friends.
- A Jenkins plugin that determines the latest protocol versions by grabbing the `BedrockProtocol.DEFAULT_BEDROCK_CODEC.getProtocolVersion()` and MCProtocolLib's constant? Ideally we compare the two protocol numbers. 
- When we find an update, do we nag multiple times or only once? Do we go out of our way to inform operators?
- How often do we check for an update? 24 hours?
- Three strings for each kind of update? (Java, Bedrock, and both) Or just share both a Bedrock and Java message at the same time.

### Are there any alternatives?

Checking manually, knowing to update by following Bedrock news, or praying there is no update.

**Comment by rtm516** [comment]
Maybe https://github.com/YHDiamond/GeyserUpdater can be partially integrated?

**Comment by Jens-Co** [comment]
> Maybe https://github.com/YHDiamond/GeyserUpdater can be partially integrated?
I'm open for this.

**Comment by onebeastchris** [comment]
Isnt this already implemented with https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1178/? aka the notify op upon join?

**Comment by Camotoy** [comment]
Yes.
