### ISSUE TITLE
Shield placement on the face

### ISSUE THREAD

**Issue by TheFlagen430297** [GeyserMC/Geyser#2030]
### Describe the bug

Okay, so what is happening is when a player tries to use a shield it gets placed on the face and the handle gets placed on the neck. I run it on bungeecord and it seems to only happen for mobile

### To Reproduce

1. Start the server
2. Get a shield
3. Put it in your off-hand or hotbar

### Expected behaviour

To be on the respective arm
Or in other words to be on the arm, not the neck

### Screenshots / Videos

https://cdn.discordapp.com/attachments/739352516105338970/819956487504920616/image0.png

### Server Version and Plugins

Bungeecord
• Version: git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:9c078b7:1539
• Plugins (16): AdvancedBan, badlionclientmodapibungee, BungeeControl-Red, BungeeGuard, BungeeTabListPlus, CMIB, floodgate-bungee, Geyser-BungeeCord, LuckPerms-Bungee, NametagEdit, nuvotifier, PistonMOTD, Plan, ServerListPlus, SkinsRestorer, UltraStaffChat

Server
• Version: Paper(416) 1.16.4-R0.1-SNAPSHOT
• Plugins (78): ActionHealth*, AntiSwear*, BankNote*, BigDoors, BookShelf, BungeeGuard, BungeeTabListPlus, BuycraftX, ChatControlRed, ChatGames*, Chunkmaster, Citizens, ClearLag, CMI, CMILib, CMIPaperLib, CommandCooldown*, CoreProtect, CraftPlus, CrazyAuctions, CutterDamage, DailyRandomShop, DeluxeMenus, Denizen, DiceFurniture, DiscordSRV, DiscordSRV-Staff-Chat, dynmap*, EditableSign, EpicEnchants, EpicHeads, FastAsyncWorldEdit (WorldEdit), FastLeafDecay, FurnitureLib, FurnitureMaker, GriefPrevention, GriefPreventionDynmap*, HolographicDisplays, HolographicExtension, InteractionVisualizer, InteractiveBoard, InventoryRollback, ItemEditor, KeepDeathDrop, LightAPI, LuckPerms, mcMMO, MFHoppers, MusicBox, MyCommand, NerfPhantoms, Not-Too-Expensive, NoteBlockAPI, PetBlocks*, PetDragon, Piano, PlaceholderAPI, Plan, PlayerParticles, PlayerVaults, PlayerWarps, PluginLibrary, PlugMan, ProtocolLib, RTP, SkinsRestorer, SpecializedCrates, SuperVanish, TAB, Trade, UltimateStacker, Vault, Vehicles, VillagerMarket, Votifier, VotingPlugin, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

https://dump.geysermc.org/5h03QRh0G1KfxfA5KAT0pmDQOT6dSuez

### Geyser Version

1.2.0-SNAPSHOT (git-master-f0e6e55)

### Minecraft: Bedrock Edition Version

1.16.210

### Additional Context

Umm, it started after the 1.16.210 update. And the issue only happens on mobile, and we've only seen it on iOS but I don't know if it happens on Andriod. And it doesn't happen on Windows 10

**Comment by Camotoy** [comment]
Thanks for the issue report! We *believe* this is a general issue for Bedrock right now (see https://www.reddit.com/r/MCPE/comments/m21w1e/i_dont_think_this_is_how_im_supposed_to_hold_my/?utm_medium=android_app&utm_source=share). Therefore, I will close this issue, but feel free to discuss here.

**Comment by TheFlagen430297** [comment]
Ah okay cool, Thanks for the quick reply!
