### ISSUE TITLE
1.16.5 -  1.2.0-SNAPSHOT (git-master-f0e6e55) - Error - " Could not translate packet InventoryTransactionPacket "

### ISSUE THREAD

**Issue by Kruize1** [GeyserMC/Geyser#2031]
### Describe the bug

I recently updated to the latest version of Geyser and Paper available.

I allowed a user to connect, who I suspect is an existing user, but I believe they changed their name.

I woke up this morning and saw the error in the console logs.

### To Reproduce

Unfortunately I don't have any specific repro steps.

This user I believe is an existing Bedrock user, but he changed his name, and re-joined my server.

### Expected behaviour

Ideally no error.

### Screenshots / Videos

12.03 13:21:47 [Server] WARN Could not translate packet InventoryTransactionPacket
12.03 13:21:47 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: 50
12.03 13:21:47 [Server] INFO at org.geysermc.connector.inventory.Inventory.getItem(Inventory.java:82) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.connector.network.translators.inventory.action.InventoryActionDataTranslator.translate(InventoryActionDataTranslator.java:70) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.connector.network.translators.inventory.PlayerInventoryTranslator.translateActions(PlayerInventoryTranslator.java:230) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:87) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:70) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:95) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:53) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:216) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:162) ~[?:?]
12.03 13:21:47 [Server] INFO at com.nukkitx.protocol.bedrock.packet.InventoryTransactionPacket.handle(InventoryTransactionPacket.java:49) ~[?:?]
12.03 13:21:47 [Server] INFO at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:29) ~[?:?]
12.03 13:21:47 [Server] INFO at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:288) ~[?:?]
12.03 13:21:47 [Server] INFO at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:33) ~[?:?]
12.03 13:21:47 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:275) ~[?:?]
12.03 13:21:47 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:398) ~[?:?]
12.03 13:21:47 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:378) ~[?:?]
12.03 13:21:47 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:371) ~[?:?]
12.03 13:21:47 [Server] INFO at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:247) ~[?:?]
12.03 13:21:47 [Server] INFO at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:378) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
12.03 13:21:47 [Server] INFO at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
12.03 13:21:47 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
12.03 13:21:47 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 50
12.03 13:21:47 [Server] WARN at org.geysermc.connector.inventory.Inventory.getItem(Inventory.java:82)
12.03 13:21:47 [Server] WARN at org.geysermc.connector.network.translators.inventory.action.InventoryActionDataTranslator.translate(InventoryActionDataTranslator.java:70)
12.03 13:21:47 [Server] WARN at org.geysermc.connector.network.translators.inventory.PlayerInventoryTranslator.translateActions(PlayerInventoryTranslator.java:230)
12.03 13:21:47 [Server] WARN at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:87)
12.03 13:21:47 [Server] WARN at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:70)
12.03 13:21:47 [Server] WARN at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:95)
12.03 13:21:47 [Server] WARN at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:53)
12.03 13:21:47 [Server] WARN at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:216)
12.03 13:21:47 [Server] WARN at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:162)
12.03 13:21:47 [Server] WARN at com.nukkitx.protocol.bedrock.packet.InventoryTransactionPacket.handle(InventoryTransactionPacket.java:49)
12.03 13:21:47 [Server] WARN at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:29)
12.03 13:21:47 [Server] WARN at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:288)
12.03 13:21:47 [Server] WARN at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:33)
12.03 13:21:47 [Server] WARN at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:275)
12.03 13:21:47 [Server] WARN at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:398)
12.03 13:21:47 [Server] WARN at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:378)
12.03 13:21:47 [Server] WARN at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:371)
12.03 13:21:47 [Server] WARN at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:247)
12.03 13:21:47 [Server] WARN at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:378)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
12.03 13:21:47 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
12.03 13:21:47 [Server] WARN at java.lang.Thread.run(Thread.java:748)

### Geyser Dump

https://dump.geysermc.org/DF2PyfQX6t2nIDOQwmnfgVOKPPY4ht4U

### Geyser Version

Geyser version 1.2.0-SNAPSHOT (git-master-f0e6e55) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.210)

### Minecraft: Bedrock Edition Version

1.16.210 (is what they're using)

### Additional Context

The error seems to be related to inventory? 

Looking at the chat logs the user didn't seem to experience any issues, from what I can tell.

**Comment by Camotoy** [comment]
This is the same error described in #1549, so I'm closing this. Thank you regardless for reporting!
