### ISSUE TITLE
Lecterns having problems on server-inventory branch. 

### ISSUE THREAD

**Issue by nickg2** [GeyserMC/Geyser#2033]
### Describe the bug

Whenever a bedrock player (java works fine) tries to us a lectern, the book wont show up, but if the bedrock player placed the book in the lectern, the first 2 pages show up, but the player cannot scroll to the other pages.

### To Reproduce

1. use latest inventory branch (this started happening after latest update)
2. make a book with more than 2 pages
3. place the book in a lectern.
4. try to scroll through the pages

### Expected behaviour

be able to scroll through pages.

### Geyser Dump

https://dump.geysermc.org/6uMkA15Oa6YvIYrxTIqMGOhTgTViMONB

### Geyser Version

 This server is running Geyser version 1.2.0-SNAPSHOT (git-master-09105e0) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.210)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment]
Unable to replicate on the latest server inventory build and Paper (you're about two builds behind as of the time of writing).

**Comment by Camotoy** [comment]
Does this issue still persist?

**Comment by nickg2** [comment]
i dont think so.

**Comment by Camotoy** [comment]
Cool beans. Closing, then! And I'll reopen if it does persist.
