### ISSUE TITLE
Items with durability cannot be moved with the EcoEnchants plugin

### ISSUE THREAD

**Issue by jassyel** [GeyserMC/Geyser#2034]
### Describe the bug

When I have tools (sword, ax, pickaxe, etc.) and I try to place it in another inventory slot, the item remains floating in the inventory and I cannot place it

### To Reproduce

1.- Join server Since Android / ios
2.- get a sword Or any other tool
3.- Try to move the tool to another slot in your inventory 
4.- see bug

### Expected behaviour

place the item in another slot

### Server Version and Plugins

Paper Spigot 1.16.2

### Geyser Version

1.2.0-SNAPSHOT (git-master-2d9bbaf1)

### Minecraft: Bedrock Edition Version

1.16.210

### Additional Context

Please help

**Comment by Camotoy** [comment]
Please provide a Geyser dump.

**Comment by jassyel** [comment]
https://dump.geysermc.org/ziitjXjKb0hBnXJ2RSSP6XWqsrpnhYZY

**Comment by Camotoy** [comment]
This user's issue was resolved after removing EcoEnchants.

**Comment by Kooldude183** [comment]
A similar issue happens to me where I sometimes have to double-click to move an item to another slot.

**Comment by AlecMcQuarrie** [comment]
Hey! It actually didn't appear to be EcoEnchants for me. It was the dependency called: eco. I had this problem on both paper and yatopia on different versions, and the Eco version I am using is 5.1.0.

**Comment by LautaKooh** [comment]
Any way to fix it without removing the Eco Enchants?

**Comment by AlecMcQuarrie** [comment]
Use a plugin called AdvancedEnchantments. It does the same thing but works with geyser somewhat. The only problem is the plugin uses lore to show the enchants but bedrock users with geyser have some problems with it

**Comment by LautaKooh** [comment]
Thanks, I'll buy it then.

**Comment by Konicai** [comment]
Likely due to usage of ProtocolLib in eco

**Comment by RednedEpic** [comment]
Seems to possibly be the same issue as #2219. Since that was stated as potentially being fixed, am going to close this. Please open a new issue with updated replication steps if this still occurs.
