### ISSUE TITLE
Max Build Height in Nether

### ISSUE THREAD

**Issue by ItzYanick** [GeyserMC/Geyser#2040]
### Describe the bug

So I run a simple survival server in 1.16.5 where a bug appears that you can abuse to get to the roof in the nether and build stuff up there like farms etc. This works fine for Java Edition as the max build height in the nether is also 255 but in the bedrock version the max built height is 128. Therefore when you built stuff on the roof in the nether in java edition, it simply does not show up in bedrock edition

### To Reproduce

1. Create a server with Geyser (obviously)
2. Go with a java client to the roof of the nether and start building blocks
3. Join with the bedrock client and tp to the same position. (Will see no block while you still see them with the java client)
(4. try building blocks with the bedrock client. It will display a message saying that you reached the max build height)

### Expected behaviour

The max build height of the bedrock client should be raised as well so that you can see built blocks on the roof of the nether as well as building blocks there with the bedrock client.

### Server Version and Plugins

Paper version git-Paper-549 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/OHb7ukD1fE28NGl5DrumvMkZpGgtexPj

### Geyser Version

Jenkins Build (Spigot) #643

### Minecraft: Bedrock Edition Version

1.16.210

### Additional Context

i tested it only with bedrock client on switch. Maybe it behaves otherwise on bedrock on client but it should not

**Comment by Camotoy** [comment]
Enable `above-bedrock-nether-building` in your Geyser config.
