### ISSUE TITLE
cross-platform versions

### ISSUE THREAD

**Issue by StAYsON9** [GeyserMC/Geyser#2041]
### What feature do you want to see added?

Is it possible to make it so that it would be possible to go to the servers of version 1.12.2 by downloading another version of bedrock, I suggest the cross-platform of versions 1.12.2 and 1.16, since the bulk of the servers are built on it

### Are there any alternatives?

Not yet

**Comment by Camotoy** [comment]
Install ViaVersion on the server, if you manage it, or look into https://github.com/ViaVersion/VIAaaS/.

It's not easy for Geyser to support multiversion natively - it's not as simple as telling the server we run 1.12.2.
