### ISSUE TITLE
GUI opened via command closes instantly

### ISSUE THREAD

**Issue by J0RDANTV** [GeyserMC/Geyser#2043]
### Describe the bug

When opening any GUI via a command; it opens then closes right after.

### To Reproduce

1: Open a GUI of your making
2: Watch it open then close

### Expected behaviour

You can expect the GUI to close

### Screenshots / Videos

Self-explanatory

### Server Version and Plugins

I run a bungee network, it occurs on 1.8.8 and 1.16.4

### Geyser Dump

https://dump.geysermc.org/fkqPG7539JeildeRSiecb60UiQjQNYqb

### Geyser Version

1.2.0-SNAPSHOT (git-master-2ebd7dc) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.210)

### Minecraft: Bedrock Edition Version

1.16.201 (latest)

**Comment by Camotoy** [comment]
I'm unable to replicate on Spigot 1.8.8 with Essentials's `/workbench`, nor am I able to replicate with Paper-506 with the same command and CrazyCrates's `/cc` command. Please provide exact replication steps, including plugins, plugin versions and server softwares.

Also, please note that the latest Bedrock version is 1.16.210.

**Comment by J0RDANTV** [comment]
Apologies for the delay. This only seems to happen on version 1.8.8 taco spigot with the latest bedrock version (1.16.2.0.2). Use the plugin "DeluxeMenus" and create a menu. Then open the GUi with a command and it will automatically close itself.

**Comment by Camotoy** [comment]
Hmm, I'm afraid I still cannot replicate this. I used TacoSpigot 1.8.8 compiled from GitHub, DeluxeMenus v1.13.3-Release, and PlaceholderAPI v2.10.10-DEV-122. Have you changed any settings in TacoSpigot?

**Comment by Jens-Co** [comment]
Hello @J0RDANTV, you got any updates on this issue ? Thanks

**Comment by Tydium** [comment]
I actually just had this bug last last night. I'll send a video in.

**Comment by Tydium** [comment]
This seems to happen if you are moving while in a GUI. Im not entirely sure however https://user-images.githubusercontent.com/67938521/127163335-2d55561b-06c9-4f3a-a70a-ab60f3ec09f2.mp4

**Comment by Camotoy** [comment]
Can you provide replication steps?

**Comment by Camotoy** [comment]
^^ Tydium's variable of the bug was a GeyserConnect bug that has since been resolved.

**Comment by Konicai** [comment]
If you can provide replication steps to make this occur again, this can be reopened
