### ISSUE TITLE
Bedrock Instant Crash

### ISSUE THREAD

**Issue by stixess** [GeyserMC/Geyser#2045]
### Describe the bug

As soon as a player joins on Bedrock their client will crash instantly

### To Reproduce

https://dump.geysermc.org/VquBxvnYWbeSA1Xa7PNuuYoZY9gZXprf

### Expected behaviour

Bedrock client crashes

### Geyser Dump

https://dump.geysermc.org/VquBxvnYWbeSA1Xa7PNuuYoZY9gZXprf

### Geyser Version

1.2.0-SNAPSHOT (git-master-d41d8b0)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment]
What does "crash" mean?

Can we get a list of plugins on backend/lobby server?

**Comment by stixess** [comment]
When I say crash the bedrock client completely closes and you have to reboot it back up

Bungeecord Plugins:
- BanManagerBungeecord
- ajQueuePlus
- BungeeGuard
- flood-gate
- Geyser-bungeecord
- LuckPerms-Bungee
- Maintenance
- slingshot-2.0
- ViaBackwards
- ViaVersion
- VPNGuardBungee

Lobby Plugins:
- ajParkour
- ajQueuePlus
- BanManagerBukkit
- BungeeGuard
- BuycraftX
- Citizens
- CoreProtect
- CustomJoinMessages
- DeluxeHub
- EssentialsX
- HeadDatabase
- HolographicDisplays
- LuckPerms-Bukkit
- Multiverse-core
- PlaceholderAPI
- ProtocolLib
- SuperVanish
- **TAB_Premium_v2.8.9** (I did research into this and found possibly a similar issue with someone else but wasn't sure)
- Vault
- VentureChat
- ViaBackwards
- ViaVersion
- WorldBorder
- WorldGuard
- WorldEdit



Thank you for looking into this :)

**Comment by Camotoy** [comment]
Yes, please try deleting TAB temporarily and see if the issue persists.

**Comment by stixess** [comment]
ok will do sorry for the delayed response

**Comment by RednedEpic** [comment]
Any update on this issue?

**Comment by Chew** [comment]
OP hasn't responded to the request in several months so unfortunately, we'll have to close this due to inactivity. Thank you for reporting!
