### ISSUE TITLE
Item's durability bar disappears when moved to a different inventory slot

### ISSUE THREAD

**Issue by Kooldude183** [GeyserMC/Geyser#2046]
### Describe the bug

When an item with a durability bar is moved to another slot in the inventory, the durability bar disappears temporarily.

### To Reproduce

1. Open inventory
2. Select item that has a durability bar
3. Place in another slot in the inventory

### Expected behaviour

The durability bar should show.

### Screenshots / Videos

https://youtu.be/nUQEuGZJHFk

### Server Version and Plugins

Purpur version git-Purpur-989 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Plugins (58): ActionHealth*, AdvancedBan*, AdvancedTeleport, AntiCreeper, AntiVPN, AutoBroadcast, AutomaticInventory, BedrockPlayerManager, ChestSort, CommandAliases, CoreProtect, DiscordSRV, DynamicShop, dynmap*, EasyCarts, Essentials, EssentialsChat, EternalLight, floodgate-bukkit, Graves, GriefPrevention, GriefPreventionFlags, HolographicDisplays, ImageOnMap, JDynmapGriefPrevention*, LuckPerms, Md5Lukas-Commons, MoneyHunters, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NametagEdit*, NexEngine, PlaceholderAPI, Plan, ProtocolLib, PunishGUI*, QuickShop, SAML, ServerListPlus*, ServerRestorer, SignBoard, SimpleTaxes*, SkinsRestorer, spark, SpigotPing, TabList, TradeSystem, UltimateAutoRestart, UltimateTimber, Vault, ViaBackwards, ViaVersion, ViewDistanceTweaks, Waypoints, Wild, WorldBorder, XP-Transfer*

### Geyser Dump

https://dump.geysermc.org/fLJKFAYs3YujTH1fk9uT3vM5aQ1kVL4h

### Geyser Version

1.2.0-SNAPSHOT (git-master-2f058e0)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment]
This was fixed by #2042. Please update!

Thanks anyway for reporting.
