### ISSUE TITLE
Windows 10 (at least) cannot enter or exit beds properly

### ISSUE THREAD

**Issue by WillyWhitewool** [GeyserMC/Geyser#2047]
### Describe the bug

Basically when a Windows 10 player (have not tested on other bedrock versions) goes in a bed, for Java it appears the player is in the bed, for Windows 10 it appears that the player cannot enter the bed, and "time freezes" for the Windows 10 player. Breaking the bed puts the Windows 10 player back into the game.

### To Reproduce

1. On Windows 10 enter a bed.
2. Another player (PC) breaking the bed fixes it.

### Expected behaviour

I expected the Windows 10 player to be able to normally use beds.

### Server Version and Plugins

Geyser version 1.2.0-SNAPSHOT (git-server-inventory-48aa586) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.210)
Plugins: 
AdvancedArmorStands, Better_Combat, BetterChairs, CoreProtect, CorpseReborn, EasyCarts, Essentials, EssentialsChat, EssentialsSpawn, FactionChat, Factions, floodgate-bukkit, Geyser-Spigot, ImageOnMap, LuckPerms, MassiveCore, OpenInv, PiggyBack, ProtocolLib, SkQuery, skRayFall, Skript, TAB, ViaVersion, WorldBorder, WorldEdit

### Geyser Dump

https://dump.geysermc.org/FUOYUeK9N57C9eLkDcFaBv0qHIIfzD86

### Geyser Version

Geyser version 1.2.0-SNAPSHOT (git-server-inventory-48aa586) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.210)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment]
You can update to master now as server-inventory has been merged.
