### ISSUE TITLE
Inventory bar get hidden

### ISSUE THREAD

**Issue by AnonAlpha** [GeyserMC/Geyser#205]
**Describe the bug**
Sometime player's inventory bar got hidden(Tested on win10 that players can select item using kwyboard) when they die once they can see the inventory bar

**To Reproduce**
1. Build a spigot server with ScreamingBedWar plugin
2. Select a team
3. See error
(Detail in video below)

**Expected behavior**
Inventory bar showing without player dying once

**Screenshots**
[Video](https://streamable.com/8zypm)

**Server version**
spigot latest

**Geyser version**
Inventory branch latest

**Bedrock version**
latest 1.14

**Comment by Loganh4005** [comment]
Just wondering what geyser ver are you using

**Comment by AnonAlpha** [comment]
> Just wondering what geyser ver are you using

Newest Inventory Branch

**Comment by Loganh4005** [comment]
But inventory lastest ver Is Broke

**Comment by AnonAlpha** [comment]
> But inventory lastest ver Is Broke

What do you mean broken? If it can't work right now then I'm using the latest workable one

**Comment by AnonAlpha** [comment]
> But inventory lastest ver Is Broke

What do you mean broken? If it can't work right now then I'm using the latest workable one

**Comment by RednedEpic** [comment]
Have not been able to reproduce this at all lately. Not much has changed, but I want to know if anyone else still has this problem.

**Comment by AnonAlpha** [comment]
Just tested, it still happens
[https://github.com/ScreamingSandals/BedWars](https://github.com/ScreamingSandals/BedWars)
this is the plugin I'm using, when you select a team, your inventory bar got hidden, maybe check it's code?

**Comment by Loganh4005** [comment]
I can confirm that the inventory bar does get hidden and it only happens when you select using the compass - on bedwars

**Comment by AnonAlpha** [comment]
Confirmed to happen also when using TownyGUI plugin

**Comment by AnonAlpha** [comment]
Just tested, this will happen when the gui returns a text or so, seems the client don't realise the GUI is closed, so the client won't show the inventory bar

**Comment by AnonAlpha** [comment]
This seems to be also happening on PMMP servers

**Comment by towuk118** [comment]
https://github.com/GeyserMC/Geyser/issues/621#issuecomment-632930150
fix repository this bug (i compile and tested)
