### ISSUE TITLE
Falling Blocks cause Flickering on Bedrock Edition.

### ISSUE THREAD

**Issue by Tydium** [GeyserMC/Geyser#2050]
### Describe the bug

We have a game called Tetrominoes Survival on our server (WIP) and this Falling blocks thing just started happening. I can't tell if its from the minecraft update or geyser itself (Im going to assume Minecraft update) Basically the Blocks would flicker in the game (disappearing and reappearing) visually. Like I said before I can't really tell if its geyser or Bugrock.

### To Reproduce

(Your going to need to probably come on my server to actually test this since we made the plugin)
1. Start a game of Tetrominoes survival on bedrock edition (or something with falling blocks with physics)
2. Watch the blocks fall.
3. watch them visually flicker.

### Expected behaviour

I'm expecting this to have a normal smooth fall like it did before. I would hope to get it back to how it was before like Java edition.

### Screenshots / Videos

You can see exactly what I'm talking about here (Java VS Bedrock)
Bedrock: https://streamable.com/pn9449
Java: https://streamable.com/73ft7d

### Server Version and Plugins

GEYSER BUNGEECORD (Running on waterfall): This server is running Waterfall version git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395 by md_5
 
This server is running Purpur version git-Purpur-981 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) (FORK OF TUINITY WHICH IS ALSO A FORK OF PAPER) 

Server Plugins: Plugins (30): Citizens, CommandHook, CommandNPC*, CommandSigns, Essentials, EssentialsChat, floodgate-bukkit, FloodgatePlaceholders, GeyserSkinManager, HolographicDisplays, HolographicExtension, HolographicPlaceholders, HubThat, LaunchPlate, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MyCommand, NeoNoobs, Parkour, PlaceholderAPI, PlugMan, ProtocolLib, TetrominoesSurvival, TouchBuff, Vault, VoidGenerator, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/fuhW48B1ZboRahGneG0vNQ6REuE0x4Bk

### Geyser Version

This server is running Geyser version 1.2.0-SNAPSHOT (git-master-f0e6e55) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.210)

### Minecraft: Bedrock Edition Version

Windows 10 + Mobile

### Additional Context

Feel free to dm me at Tydium#4117 on discord for more information or to test yourself.

**Comment by Tydium** [comment]
Also I would like to mention that we tested some type of same scenario in bedrock edition. https://streamable.com/ndjhxy

This is a full on geyser bug. As the video here isn't flickering (It seems like it, but its having placement issues because of how many blocks are being spawned and dropped at once)

**Comment by Tydium** [comment]
This is an updated video after I have updated geyser. It seemed to have gotten worse???? (You'll see it once you hear the tetrominoes music start playing (30 seconds in))

https://youtu.be/RoZwAyO-wLw

**Comment by Tydium** [comment]
Was gonna state this here earliar but I forgot. Bug is still present on Geyser Bungeecord/Velocity with Floodgate 2.0

**Comment by RednedEpic** [comment]
Bedrock issue.
