### ISSUE TITLE
GLITCHY MOVEMENT

### ISSUE THREAD

**Issue by lecatos** [GeyserMC/Geyser#2052]
### Describe the bug

When I play on bedrock but on java server using geyser as a proxy, I experienced a glitchy movement. As I move around in the server, it pull me back to where I was a few block away when I try to jump onto a block. Walking in to bamboos also causes this glitch. I don't know why it is so but it could be the server's anticheat. Sometimes the server detected me as flying and it kicks me out of the server.
Please fix this bug asap, thank you ;}}}}}}

### To Reproduce

Jumping on to a block
Walking in to bamboos

### Expected behaviour

the server pulls you back to where you was a few blocks away

### Screenshots / Videos

https://imgur.com/rOtOHoh

### Geyser Version

Geyser version 1.2.0-SNAPSHOT (git-master-2f058e0)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment]
Bamboo is known and, at this time, unfixable.

Please send a Geyser dump as well.

**Comment by Chew** [comment]
No response in over 2 months. Without the critical information, we're going to have to close this issue. Your theories may be correct, it could be an anti-cheat, or it could be unfixable behavior. Regardless, thank you for reporting!
