### ISSUE TITLE
Allow for bedrock addons  for bedrock players

### ISSUE THREAD

**Issue by NotGalacticFire** [GeyserMC/Geyser#2056]
### What feature do you want to see added?

Bedrock  addons should be able to be added to the server and then they should work only for bedrock players

### Are there any alternatives?

Using plugins/data packs but this doesn't really work because bedrock add-ons are meant for bedrock and can add features to bedrock that are already on java

**Comment by Camotoy** [comment]
> and then they should work only for bedrock players

Behavior packs modify server behavior, making this reaaaalllyy unlikely. You should give an example of what you want working.

**Comment by NotGalacticFire** [comment]
Well actually what I want is the bedrock sweep attack animation behavior pack because with the animation that's currently on geyser it just has the bar and it can be confusing with the java combat because it doesn't show any sweep animation and it's kind of hard to see

**Comment by Camotoy** [comment]
We will fix that in another, upcoming method. Stay tuned! ;)

As such, I will close this issue. Thanks for suggesting anyway!
