### ISSUE TITLE
Allow bedrock players to put all items in offhand

### ISSUE THREAD

**Issue by NotGalacticFire** [GeyserMC/Geyser#2057]
### What feature do you want to see added?

I would like for bedrock players to be able to put items in their offhand other than the items allowed by normal bedrock edition.

### Are there any alternatives?

there are not really any alternatives

**Comment by Camotoy** [comment]
Unfortunately, this is a Bedrock limitation. There's nothing we can do about it. :(

If it becomes apparent that we can, we will implement it, but for now I'm closing this as a Can't Fix. Thanks for asking anyway.
