### ISSUE TITLE
I hope geyser can support the customization of login window

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Geyser#2059]
### What feature do you want to see added?

I hope geyser can support the customization of login window

### Are there any alternatives?

At present, we can only modify the code in the jar file to customize, but this is very cumbersome, and once the plug-in is updated, it has to be modified again, and this operation is easy to cause the plug-in to be unable to use. I hope geyser can officially add custom functions to the login window.

希望Geyser可以支持登录窗口的自定义。目前只能通过修改jar文件内的代码来进行自定义，但这样非常繁琐而且一旦插件更新后还得重新进行修改，而且这种操作很容易导致插件无法使用。希望Geyser官方可以添加对登录窗口的自定义功能。
I hope geyser can support the customization of login window. At present, we can only modify the code in the jar file to customize, but this is very cumbersome, and once the plug-in is updated, it has to be modified again, and this operation is easy to cause the plug-in to be unable to use. I hope geyser can officially add custom functions to the login window.

**Comment by rtm516** [comment]
Geyser only supports official authentication methods which the login form has options for all of them. What could possibly need adding to this?

**Comment by CanNian2002** [comment]
> Geyser仅支持官方身份验证方法，登录表单为所有方法提供选项。可能需要添加什么？

不是添加，就是自定义界面。某些修改按钮文字，数量什么的
Either add or customize the interface.  Some edit button text, quantity or something

**Comment by CanNian2002** [comment]
> Geyser仅支持官方身份验证方法，登录表单提供选项。可能需要添加什么？

因为我是用谷歌翻译来交流的，所以意思可能不是太对。
因为我使用谷歌翻译进行沟通，所以含义可能不太正确。

**Comment by Camotoy** [comment]
This seems more suitable for the future plugin/extension API rather than something Geyser supports otherwise.

**Comment by CanNian2002** [comment]
> This seems more suitable for the future plugin/extension API rather than something Geyser supports otherwise.

但是这个窗口是Geyser本身的窗口。扩展之类的Geyser好像并不支持吧
But this window is the window of Geyser itself.  Geyser like extension doesn't seem to support it

**Comment by RedSmarty** [comment]
Can't you just disable online mode and use floodgate or offline mode and send a custom login form? Then you can check if the details provided are correct using mojang api.

**Comment by CanNian2002** [comment]
> Can't you just disable online mode and use floodgate or offline mode and send a custom login form? Then you can check if the details provided are correct using mojang api.

我指的是自定义间歇泉的登陆窗口，而不是说什么切换登录模式调用mojang API
I am referring to the custom geyser login window, not to switch the login mode to call the mojang API

**Comment by CanNian2002** [comment]
所以，能采纳吗？？？
So, can it be adopted?  ?  ?

**Comment by Camotoy** [comment]
I'm still confused on exactly what you want to do. Can you send a picture of a mockup or something?

**Comment by CanNian2002** [comment]
> I'm still confused on exactly what you want to do. Can you send a picture of a mockup or something?

稍等，我找一下
Wait a moment, let me find

**Comment by CanNian2002** [comment]
如果看不到的话我把图片发GitHub里（第一次用GitHub，不是太会用）
If I can't see it, I'll send it to GitHub(I used GitHub for the first time, but I'm not very good at it.)

**Comment by CanNian2002** [comment]
这个是自定义过的Geyser登录窗口
This is a custom geyser login window
![QQ图片20210323225334](https://user-images.githubusercontent.com/43288791/112175412-30358780-8c32-11eb-8733-bec8ddd5c07d.png)
这个是原版简体中文的Geyser登录窗口
This is the original simplified Chinese geyser login window
![QQ图片20210323225455](https://user-images.githubusercontent.com/43288791/112175435-33307800-8c32-11eb-84eb-acf823d477c5.png)

**Comment by CanNian2002** [comment]
希望可以添加一个文件，用以自定义这个登录界面。
I want to add a file to customize the login interface.

**Comment by Merith-TK** [comment]
It appears he wants to just customize what it says and the colors

**Comment by CanNian2002** [comment]
> It appears he wants to just customize what it says and the colors

不只是自定义颜色和内容，按钮如果可以的话希望也可以自定义（就是自定义是否显示这个按钮）
Not only customize the color and content, the button can also be customized if possible (that is, whether to display the button)

**Comment by TheMonBonGH** [comment]
he just wants an option to customize the forms (custom text/colors) without customizing the jar, because it’s tiring for every update

**Comment by Jens-Co** [comment]
Could make a separate config file for that "forms.yml" and just make the forms customizable bet that's no biggie.

**Comment by ExusiaiMoe** [comment]
Don't think this is possible, it's much more simple to just use floodgate api to customize, for how can you customize the login logic with a config file????

**Comment by RednedEpic** [comment]
Adding custom buttons and whatnot to the login menu and making them customizable sounds like something better for the extension API. If you wish to change the colors, you are free to do so by opening the jar and modifying the locale files, but at the moment no official way to modify those messages directly without opening the jar exists. A feature suggestion for this already exists at #1390, closing.
