### ISSUE TITLE
Crash on rejoining a server and sometimes it crashes on just joining a server

### ISSUE THREAD

**Issue by ChieflyDevon** [GeyserMC/Geyser#206]
**Describe the bug**
Attempting to rejoin the server on a bedrock device after leaving results in a crash and some users are unable to join the server because there game crashes and disconnects on join

Using the inventory branch of Geyser but the same issue seems to happen on the master branch of Geyser along side floodgate

**To Reproduce**
1. Join the server on a bedrock device
2. Leave the server
3. Attempt to rejoin the server

**Expected behavior**
Be able to join and rejoin

**Additional context**
Looking down as soon as you can seems to allow bedrock players to have a higher chance of joining the server successfully this may be due to loading in the chunks of the server. One player was kicked for the reason of a "TIMED_OUT" as well as "FLYING"

**Comment by RednedEpic** [comment]
Do you have Floodgate installed?

**Comment by ChieflyDevon** [comment]
yeah i have the latest version installed and just today i tried the master Gyser version for Xbox however this results in the same crash. I cant seem to stay in the server more than a couple of seconds without the game crashing on both the inventory branch and the Master branch

**Comment by RednedEpic** [comment]
This crash is due to something completely separate that we're working on fixing right now.

**Comment by ChieflyDevon** [comment]
oh right i managed to get in a server on the inventory branch yesterday however today it just doesn't work and its strange since i haven't edited any files

**Comment by RednedEpic** [comment]
Resolved in latest build.
