### ISSUE TITLE
Make it so that textures for worn heads show up as the correct texture

### ISSUE THREAD

**Issue by NotGalacticFire** [GeyserMC/Geyser#2062]
### What feature do you want to see added?

So I know that it's listed as a bedrock limitation for heads in the inventory but not heads when worn. Basically I have a datapack called "more mob heads" and for these heads, when they are placed down the texture shows but when they are worn the texture isn't shown.

### Are there any alternatives?

No there aren't any alternatives

**Comment by Camotoy** [comment]
This is close enough to #782 that I'll close this in favor of that. Thanks for your request!
