### ISSUE TITLE
Killing yourself OR attempting to spectate an entity in spectator mode bugs vertical movement

### ISSUE THREAD

**Issue by ProfessorPickles** [GeyserMC/Geyser#2064]
### Describe the bug

While in spectator mode, killing yourself or spectating an entity (it is possible that doing other things can also trigger this) will make vertical movement impossible. When you crouch to fly downwards, it just does the crouching animation without moving you downwards. When you hold jump to fly upwards, it only makes you fly up by a super tiny amount. I think doing either of these things makes the game think you are still in survival mode, and therefore you cannot fly.

### To Reproduce

1. Go into spectator mode on a bedrock client.
2. Run /kill on yourself or attempt to spectate another entity.
3. Hit crouch or jump and you will hardly be able to move at all.
4. Relog into the server and spectator mode will work normally again.

### Expected behavior

When running /kill on yourself in spectator mode, you should respawn in spectator mode and vertical movement should function exactly how it should.

When attempting to spectate an entity, you should either go into the entity's view, or if that isn't possible just do nothing.

### Server Version and Plugins

Paper version git-Paper-564 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/Al8adw9fbY89AumoLQjf36lpNYJlU6Rv

### Geyser Version

1.2.0-SNAPSHOT (git-master-86397ef)

### Minecraft: Bedrock Edition Version

Platform: Windows 10
Version: 1.16.201

### Additional Context

It's just annoying because I use my Bedrock Edition alt as an admin account on my server. To make sure nobody is hacking I use spectator mode around them. When I have to return to spawn with /kill, I need to relog in order for spectator mode to work again.

**Comment by ProfessorPickles** [comment]
Please let me know if you need any more information.

**Comment by TechnicJelle** [comment]
I'm having kind of the same problem, only kind of the reverse, somehow…
My server is a creative build server where anyone can log in, they'll just be in spectator mode. This is set in the `server.properties` file with `gamemode=spectator`. To prevent people who have got access to creative mode being put back into spectator mode upon joining, I've set `force-gamemode=false`
Upon joining with my Bedrock account, I was put into spectator mode just as it should be, but I found that I couldn't move up or down. If I change the Bedrock player's gamemode to creative and then back again, the problem persists. It can be temporarily worked around by being put into creative mode, taking off into flight, and only then being put back into spectator mode.
When I /kill the Bedrock player and they respawn flight is also restored for the session.
When I log out and back in, the vertical movement is gone again.

If I double-tap the space bar, I do move up a tiny bit, but that's it.

I've made a video (https://youtu.be/8TThc75ZBQ0) of all these things happening, so you can see how it is, if you wish.

**Comment by Jens-Co** [comment]
Hello there, Any updates on this issue ? since then we patched up some weird movements on the spectator mode thanks!

#1034

**Comment by TechnicJelle** [comment]
The server I had this problem on has since been abandoned, but I still had the files, so I updated Geyser and Floodgate and spun it back up for a moment. Spectator mode *seems* to work well now, but I think it would be better if other people also tested it.

**Comment by RednedEpic** [comment]
Stated as no longer an issue & no responses since then. Closing.
