### ISSUE TITLE
User unable to connect.

### ISSUE THREAD

**Issue by IsXGeo** [GeyserMC/Geyser#2067]
### Describe the bug

The bedrock player is unable to join the server. Tried both Waterfall and Bungeecord.

https://pastebin.com/zQUgDk5c

### To Reproduce

1. Join Server
2. Fail to join

### Expected behaviour

Player connects to server and joins.

### Screenshots / Videos

https://imgur.com/a/oH8AL6P

### Server Version and Plugins

Paper version git-Paper-521 (MC: 1.16.5)
Bungeecord Build #1549 and Waterfall (Not sure which version, no cmd to find it as far as I can tell)
Plugins on Waterfall Instance: 2FA, AntiVPN, BungeeWhitelist, DKBans, Floodgate, Geyser, LuckPerms, McNative, Plan, RedirectPlus, Serverlist Plus, Server Status, Matrix Anticheat, BuyCraftX.

### Geyser Dump

https://dump.geysermc.org/Tqj35t9dtDn6W7gUxqnrTZ723093HuLy

### Geyser Version

Geyser version 1.2.0-SNAPSHOT (git-master-86397ef)

### Minecraft: Bedrock Edition Version

1.16.04201

**Comment by Camotoy** [comment]
`at net.pretronic.libraries.utility.reflect.ReflectionUtil.getFieldValue(ReflectionUtil.java:93) `

Looks like another plugin is conflicting with Floodgate. Remove that and try again.

**Comment by IsXGeo** [comment]
Yep it was another plugin that was interfering. Its a tad unfortunete as it was my Ban plugin. Thanks for the help anyways!
