### ISSUE TITLE
Cannot turn command block into "conditional"

### ISSUE THREAD

**Issue by PappoYT** [GeyserMC/Geyser#2069]
### Describe the bug

From bedrock client I cannot turn command block into "conditional" mode. See attached video.

### To Reproduce

Place a command block.
Click on command block to open menu.
Set "conditional".
Exit command block menu.
Click again on command block.
It is not "conditional".

### Expected behaviour

Command block should turn in "conditional" mode.

### Screenshots / Videos

https://youtu.be/awK448PwLJE

### Geyser Dump

https://dump.geysermc.org/DGjCk2ktzeBotF08LZndj16qzATMYQve

### Geyser Version

Geyser build 650

### Minecraft: Bedrock Edition Version

Paper 1.16.5

**Comment by Camotoy** [comment]
Unable to replicate with Windows 10 1.16.210 and Paper 453.

**Comment by PappoYT** [comment]
I can invite you on the server where I had this problem.
Otherwise, let me know ho can give you further informations. TY

**Comment by Chew** [comment]
Can you provide `/version` and plugins? That was left blank.

**Comment by Camotoy** [comment]
The Geyser dump provides that information for us.

**Comment by Camotoy** [comment]
OK, I was able to replicate this at least once on Paper 543.

**Comment by onebeastchris** [comment]
Tested & works fine on latest version of Geyser; can be closed
Tested on both Geyser-Spigot, and Geyser-Velocity

**Comment by Camotoy** [comment]
Looks like we cannot reproduce. Please open a new issue if this still persists!
