### ISSUE TITLE
Xbox cannot seem to join the server but other platforms can

### ISSUE THREAD

**Issue by ChieflyDevon** [GeyserMC/Geyser#207]
**Describe the bug**
Ive attempted to get my xbox to join my Geyser server running the inventory branch and floodgate and i receive the error "We were unable to connect you."

**To Reproduce**
1. Attempt to join the Geyser Lan game on a xbox

**Expected behavior**
To be able to join

I attempted to join with the Xbox Geyser branch but it didnt seem to work either

**Comment by RednedEpic** [comment]
Resolved in #203.
