### ISSUE TITLE
Takes a long time to load in

### ISSUE THREAD

**Issue by NotGalacticFire** [GeyserMC/Geyser#2071]
### Describe the bug

When you join the world on bedrock it takes a very long time to load in.

### To Reproduce

Go onto a java server with bedrock, and then when your loading in it takes a very long time to load in

### Expected behaviour

It should take a short time to load in

### Server Version and Plugins

Paper version git-Paper-418 (MC: 1.16.5)
FInvsee, floodgate-bukkit, Geyser-Spigot, GeyserUpdater, LaggRemover, OnePlayerSleep, SkinsRestorer

### Geyser Dump

https://dump.geysermc.org/PdhoGPtNvgbE2kYFSOTaf1fcH9j9pb6c

### Geyser Version

1.2.0-SNAPSHOT (git-master-3a4b1e4)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment]
Thank you for the issue report!

Geyser login speed is already pretty fast for what it has to handle, and if we knew how we could make it faster we would've already done that. I'm closing this as it doesn't mention a specific area we could improve on, but that doesn't mean we won't be interested in improving it in the future as time goes on.

The exception is if this is an issue that only recently appeared, in which case please let us know.
