### ISSUE TITLE
Things take a while to register on bedrock

### ISSUE THREAD

**Issue by NotGalacticFire** [GeyserMC/Geyser#2072]
### Describe the bug

Whenever you do things like break  blocks, or hit a mob, or do a command, it takes like 30 seconds for the server to actually register that you did it.

### To Reproduce

Go onto a geyser server on bedrock edition.
Try and break blocks or hit a mob.

### Expected behaviour

When you break blocks or hit a mob it should register almost immidiately

### Server Version and Plugins

Paper version git-Paper-418 (MC: 1.16.5)
FInvsee, floodgate-bukkit, Geyser-Spigot, GeyserUpdater, LaggRemover, OnePlayerSleep, SkinsRestorer

### Geyser Dump

https://dump.geysermc.org/PdhoGPtNvgbE2kYFSOTaf1fcH9j9pb6c

### Geyser Version

1.2.0-SNAPSHOT (git-master-3a4b1e4)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment]
Thank you for the issue report!

Without replication steps, there's not much we can do with this information - I certainly cannot say I've experienced this. I'm closing this as it doesn't mention a specific area we could improve on, but of course we're always interested in improving performance times.

The exception is if this is an issue that only recently appeared, in which case please let us know.

**Comment by NotGalacticFire** [comment]
This actually wasn't happening before and then I updated to the latest geyser version and it started happening.

**Comment by Camotoy** [comment]
Can you please go back to your previous version and see if the lag resolves?

**Comment by NotGalacticFire** [comment]
Yeah the lag resolved when I went back to version number #653

**Comment by Camotoy** [comment]
Unless there is a major bug in Fastutil, I do not see how the changes made in 654 would affect lag to that extent.

I'm going to leave this closed, for now, but I acknowledge your issue.
