### ISSUE TITLE
Bug with jumping

### ISSUE THREAD

**Issue by hilltty** [GeyserMC/Geyser#2073]
### Describe the bug

Problems with movement while jumping when there is a block at the top

### To Reproduce

1. Jump when there is a block above you
2. Observe the result

### Expected behaviour

Possibly wrong player hitbox

### Screenshots / Videos

https://youtu.be/Ey0esomjUe0

### Server Version and Plugins

Yatopia version git-Yatopia-ver/1.16.5-42 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Plugins (12): AdvancedNMotd, AuthMe, AutoRestart, Chunky, CommandWhitelist, CoreProtect, Geyser-Spigot, Harbor, InventoryRollbackPlus, LiveKit, SimpleWhiteList, TakeAim*

### Geyser Dump

https://dump.geysermc.org/7nH67LxCrdQgyVGyFxBzpOdvA2PjJhcN

### Geyser Version

1.2.0-SNAPSHOT (git-master-7f03446)

### Minecraft: Bedrock Edition Version

1.16.210 (PS4)

**Comment by Camotoy** [comment]
Could you please temporarily try Paper and see if the issue persists on there?

**Comment by hilltty** [comment]
Strange, on Paper everything works fine, I checked it on Purpur and there is also the same problem

**Comment by Camotoy** [comment]
What about Tuinity and Airplane?

**Comment by hilltty** [comment]
With Tuinity the same problem, now I'm downloading Airplane

**Comment by Camotoy** [comment]
I believe Airplane inherits from Tuinity, so there is no need to test that. :)

**Comment by hilltty** [comment]
Yes, as expected, Airplane also has this bug

**Comment by Tydium** [comment]
I can confirm on Latest purpur that this is a real geyser glitch on Tuinity up to Purpur. I have been having this problem also, but couldn't tell for sure. Glad im not the only one.

**Comment by 12emin34** [comment]
Confirmed on Purpur-1042

**Comment by Camotoy** [comment]
If you're experienced with testing PRs, I ask that you try https://github.com/GeyserMC/Geyser/pull/1814 as it contains a fix that might be relevant.

**Comment by hilltty** [comment]
I tested this PR, and I can say that yes, it fixes this bug, but somewhere in 1 case out of 20, the player will teleport everything back

**Comment by Legit4K** [comment]
> I tested this PR, and I can say that yes, it fixes this bug, but somewhere in 1 case out of 20, the player will teleport everything back

I also tested the PR and it fixes the said issue (& therefore also some false positives that Anticheats would flag). 🎉

**Comment by Camotoy** [comment]
I've gotten this to happen again at least once - if you're able to replicate this bug, I'd like to know how it happened.

**Comment by Tydium** [comment]
On my server hub I use a SHIT TON of slabs in some areas and when I'm running through corners or flying through them I sometimes get rubber banded. This was on Waterfall/Purpur. I'm testing this on velocity/purpur to see if its caused still. (With latest floodgate 2 Build)

**Comment by Tydium** [comment]
I HAVE GREAT NEWS. I CAN CONFIRM THIS FIXED FOR WINDOWS 10 EDITION AND NINTENDO SWITCH. I DONT FEEL THIS ON PURPUR ANY MORE LESSSGOOOO

**Comment by Camotoy** [comment]
Seems like this is fixed. Let us know if it persists. Thanks!
