### ISSUE TITLE
The enchanting table giving the wrong enchantment

### ISSUE THREAD

**Issue by BeetPlayz** [GeyserMC/Geyser#2074]
### Describe the bug

 enchanting table gave piercing enchantment on a crossbow instead of giving it multishot

### To Reproduce

-go to enchanting table on bedrock edition
-enchant a crossbow with an available multishot enchantment

### Expected behaviour

it should gave multishot instead of piercing

### Geyser Version

1.2.0-SNAPSHOT (git-master-f0e6e55)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment]
This has already been fixed - please update! And remember to always check for the latest version before making an issue. ;)

Thanks for reporting anyway!
