### ISSUE TITLE
Bottle of water

### ISSUE THREAD

**Issue by Baqpla** [GeyserMC/Geyser#2075]

**Comment by Camotoy** [comment]
This is likely a limitation of water bottles and tied to the bucket issue that also plagues mobile controls without crosshair.

**Comment by Baqpla** [comment]
Is it possible to fix this in a future updates? Or somehow fix it in the paper mc itself?

**Comment by Camotoy** [comment]
We are exploring possibilities. What I can say is that it is in our interest to fix this.

**Comment by Baqpla** [comment]
Just wondering. Since buckets of water or empty bottles cannot be filled without crosshair, how can we break blocks and open chests outside of this crosshair? Could the same exception be made for these items, or does it work somehow differently?

**Comment by Camotoy** [comment]
Short answer: it works differently, yes. The action we send to use buckets and water bottles does not include the position of the block that it is being performed on.

**Comment by Konicai** [comment]
Closing this in favour of the more detailed https://github.com/GeyserMC/Geyser/issues/2727
