### ISSUE TITLE
Bedrock Players Always Getting Disconnected!

### ISSUE THREAD

**Issue by mrniceguy051** [GeyserMC/Geyser#2076]
### Describe the bug

I can't describe the bug but all my Bedrock player getting Disconnected together even the server is not lagging, i even check the timings of my server and there CPU usage and Memory and Ram, its all fine.

### To Reproduce

Can't Reproduce. It just happen sometimes and mostly every pick time.

### Expected behaviour

It Should not Disconnect Bedrock Players.

### Server Version and Plugins

Geyser-Spigot version 1.3.0-SNAPSHOT
or
Geyser-Spigot (floodgate-2.0#3)

### Geyser Dump

https://dump.geysermc.org/70dDkcHi2l64hxg4OuCaNuY15yQyaxHs

### Geyser Version

Geyser-Spigot version 1.3.0-SNAPSHOT (Floodgate-2.0 Build #3)

### Minecraft: Bedrock Edition Version

1.16.201 to 1.16.210

### Additional Context

Can you make Geyser a Priority Plugin. I hope this is Resolve even on the Master Build #655 its worse.

I hope this get Fix, or just make A FORK of PaperMC, I don't know if its possible.

**Comment by Camotoy** [comment]
Please provide a server log as well.
