### ISSUE TITLE
java.io.IOException: connection reset by peer when kicking player as they join

### ISSUE THREAD

**Issue by Miqhtiedev** [GeyserMC/Geyser#2077]
### Describe the bug

For the server we have a custom plugin with a verification system in place. It will kick the player as soon as they join provided they are not verified and send them a kick message with the code to verify and all those instructions.

It works fine on java edition but on geyser it just shows `java.io.IOException: connection reset by peer`

### To Reproduce

1. Register an OnPlayerJoinEvent listener and kick the player for a custom reason as soon as they join
2. Connect to the server with a bedrock client

### Expected behaviour

It to show the custom kickmessage

### Screenshots / Videos

![](https://cdn.discordapp.com/attachments/819491412231585793/825279891629015040/Screenshot_20210327-010629.png)
![](https://i.imgur.com/0tBS4Tk.png)

### Server Version and Plugins

This server is running Tuinity version git-Tuinity-"502d57b" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 47 version(s) behind

Plugins (21): AngelChest, Citizens, CoreProtect, DiscordSRV, dynmap*, FastChunkPregenerator, floodgate-bukkit, Geyser-Spigot, GriefPrevention, ImageMaps, JDynmapGriefPrevention*, KipperzSMP, LuckPerms, LuckPermsGUI*, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, ProtocolLib, Vault, VaultChatFormatter*, WorldBorder

### Geyser Dump

https://dump.geysermc.org/vna8L8AUhZrdrP36DkJt6pWpwDSbvaW9

### Geyser Version

1.2.0-SNAPSHOT (git-master-f0e6e55)

### Minecraft: Bedrock Edition Version

v1.16.210

### Additional Context

Note the custom kick messages does include color formatting 
Idk if that affects anything

**Comment by Camotoy** [comment]
Please provide a full log when a Bedrock player tries to join.

**Comment by Miqhtiedev** [comment]
Fixed the issue by doing /geyser reload
Sorry about that
