### ISSUE TITLE
3 bugs

### ISSUE THREAD

**Issue by LightMute** [GeyserMC/Geyser#2079]
### Describe the bug

Good evening, I'm reporting some pretty big bug, 

1- when we connect geyser to a Waterfall players geyser we ip 127.0.0.1 if we activate protocol in configuration it causes a broken error pipe

2- Geyser players can write in color chat despite that not permissions by third-party plugins

3-a api for dev as well as setting up plugin would be more than bad for servers

Thank you good night.

### To Reproduce

1- when we connect geyser to a Waterfall players geyser we ip 127.0.0.1 if we activate protocol in configuration it causes a broken error pipe

2- Geyser players can write in color chat despite that not permissions by third-party plugins

3-a api for dev as well as setting up plugin would be more than bad for servers

### Expected behaviour

1- when we connect geyser to a Waterfall players geyser we ip 127.0.0.1 if we activate protocol in configuration it causes a broken error pipe

2- Geyser players can write in color chat despite that not permissions by third-party plugins

3-a api for dev as well as setting up plugin would be more than bad for servers

### Geyser Version

1.2.0

**Comment by Camotoy** [comment]
If you want to report multiple issues, please create three separate issues for each. That way, we can track their progress better!!

Per issue 1: You likely do not want to activate `enable-proxy-protocol` unless you're using HAProxy. If you don't know what HAProxy is, you're not using it.
Per issue 2: We can't do anything with this information without knowing how to replicate it. `despite that not permissions by third-party plugins` which ones???
Per issue 3: "a api for dev as well as setting up plugin would be more than bad for servers" are you saying this would be a bad idea? It sounds like you're using a translator so you should rephrase that.
