### ISSUE TITLE
Inventory & Master, Bedrock client crashes with floodgate

### ISSUE THREAD

**Issue by applebee1558** [GeyserMC/Geyser#208]
Reproduce:
Install Floodgate plugin on bungeecord
Start the latest master/inventory proxy with floodgate
Join the server

Fix:
Turn bungeecord to offline mode and remove floodgate plugin
(this removes the purpose of floodgate though)

**Comment by LogicismDev** [comment]
Yes this is a known issue, we are currently fixing this.

**Comment by RednedEpic** [comment]
Duplicate of #206.
