### ISSUE TITLE
Items bugging when dropping

### ISSUE THREAD

**Issue by zOIDAdaJulian** [GeyserMC/Geyser#2080]
### Describe the bug

On the Floodgate 2.0 Branch of Geyser, Items are bugging when you drop them.

### To Reproduce

1. Download Floodgate 2.0 and the Geyser Version of Floodgate 2.0
2. Drop Items on the Bedrock Edition
3. Items are bugging

### Expected behaviour

Items should drop smoothly.

### Screenshots / Videos

https://youtu.be/UT5s_00mP9E

### Server Version and Plugins

Server Version: git-Paper-526 (MC: 1.16.5)
Plugins: Floodgate 2.0 (Spigot)

### Geyser Dump

https://dump.geysermc.org/NVbViEVDLUA3SChrR35lsE5SOBo6DEsZ

### Geyser Version

1.3.0-SNAPSHOT (git-floodgate-2.0-677a8d6)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by hilltty** [comment]
I confirm this, the bug works on all server software, tested on Paper, Tuinity and Yatopia

**Comment by Camotoy** [comment]
Only on the Floodgate 2.0 version?

**Comment by zOIDAdaJulian** [comment]
Yeah, I also tried it on master but there everything works fine ^^

**Comment by hilltty** [comment]
No, there is a bug in any version

**Comment by hilltty** [comment]
I tested and the bug is always present, even without Floodgate installed

**Comment by zOIDAdaJulian** [comment]
So, all I can say is, that this issue for me only occurs on Floodgate 2.0 and Geyser (2.0 Branch).
On Geyser (master) with Floodgate 1.0 everything is smooth and fine for me.

**Comment by RednedEpic** [comment]
Floodgate would have no effect here. It very likely has to do with 1.16.220 and some expected motion changes with item drops.

**Comment by Camotoy** [comment]
Yes, I'm able to confirm this bug only exists on 1.16.210, and it's not exclusive to Floodgate.

**Comment by zOIDAdaJulian** [comment]
Ok, thats weird. Then big sry for the false report from my side. As I tried it before I rly thought it was fine on master branch.

**Comment by Camotoy** [comment]
No worries.

**Comment by AJ-Ferguson** [comment]
I believe this is related to #2050. Sending a motion packet for both falling block and item entities seems to cause strange behavior in recent bedrock updates. I think the reason this doesn't appear to happen on a bds server is because they also send position packets very frequently.

**Comment by Camotoy** [comment]
Sounds like we should apply the same logic for throwable items to item drops and falling block entities, then?

**Comment by jassyel** [comment]
This bug is still present using the latest version of Minecraft, Geyser and floodgate 1.0, when you drop an object it behaves strange, Even some particles

**Comment by PRO100KatYT** [comment]
This bug is still present in 1.17

**Comment by DelxHQ** [comment]
I believe this issue goes away whenever you use the vanilla java server.

**Comment by PRO100KatYT** [comment]
> I believe this issue goes away whenever you use the vanilla java server.

I've just checked this, and maybe item dropping and falling blocks behave a bit different than on Paper/Tuinity etc., but their movement is still broken which is most evident in the failing blocks.

**Comment by davchoo** [comment]
Should be fixed with GeyserMC#2406
