### ISSUE TITLE
End stone bricks break incorrectly

### ISSUE THREAD

**Issue by hilltty** [GeyserMC/Geyser#2081]
### Describe the bug

When you try to break the end stone brick, there are some problems that really pissed me off when demolishing the city in the end

### To Reproduce

1. Break end stone brick with any pickaxe

### Expected behaviour

I do not know

### Screenshots / Videos

https://youtu.be/XLArh0zvLr4

### Server Version and Plugins

Yatopia version git-Yatopia-ver/1.16.5-42 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Plugins (12): AdvancedNMotd, AuthMe, AutoRestart, Chunky, CommandWhitelist, CoreProtect, Geyser-Spigot, Harbor, InventoryRollbackPlus, LiveKit, SimpleWhiteList, TakeAim*

### Geyser Dump

https://dump.geysermc.org/DtZXbqGKtVgFb0GL7nimj847XgaEAkmE

### Geyser Version

Geyser версии 1.2.0-SNAPSHOT (git-master-3a4b1e4)

### Minecraft: Bedrock Edition Version

1.16.210 (PS4)

### Additional Context

Checked on Paper, Tuinity and Yatopia. The bug is everywhere.

**Comment by Camotoy** [comment]
Specifically, end stone break time is about two times shorter on Bedrock.

**Comment by MrZomka** [comment]
Don't use Yatopia, it's discontinued. Also, you would not recieve support on the Discord server because you have online mode off.

**Comment by Camotoy** [comment]
> Checked on Paper, Tuinity and Yatopia. The bug is everywhere.

It's not a specific Yatopia issue; I believe three days ago I verified it on vanilla.

**Comment by Chew** [comment]
> Also, you would not receive* support on the Discord server because you have online mode off.

This really only applies to using or setting up Geyser. If an issue occurs in offline mode it'll likely occur in online mode. No bug should be discontinued based on platform (so long as the platform isn't at fault)

**Comment by onebeastchris** [comment]
Fixed natively in Bedrock 1.20.30 and higher - [source](https://feedback.minecraft.net/hc/en-us/articles/19545277817357-Minecraft-1-20-30-Bedrock-)
Specifically:
> We have adjusted the breaking times of 188 blocks to match Java Edition and our intended design. Some blocks couldn't be changed yet for technical reasons and Obsidian was left unchanged because we're still deciding what breaking speed it should have. Bringing more blocks to parity makes it easier for our team to keep both versions up to date. We also hope it will be easier for the community to make and share guides that work for all players on all platforms.

End stone & end stone bricks too should now break consistently on both platforms.
