### ISSUE TITLE
Ender eye plays firework sound

### ISSUE THREAD

**Issue by GoldenMyst** [GeyserMC/Geyser#2082]
### Describe the bug

When using an eye of ender, a firework sound instead of the regular sound.

### To Reproduce

1. Rightclick an ender eye

### Expected behaviour

Expected to hear the regular sound played when right clicking ender eyes.

### Screenshots / Videos

https://user-images.githubusercontent.com/74118946/112761276-69ae2000-8faf-11eb-8e3c-2b7f880358df.MOV

### Geyser Dump

https://dump.geysermc.org/1lTucCi4R4FzY9bGZLtkGOEelQvtPwq3

### Geyser Version

1.3.0-SNAPSHOT (git-floodgate-2.0-677a8d6)

### Minecraft: Bedrock Edition Version

1.16.201

**Comment by Camotoy** [comment]
Thanks for the issue report! This has been reported in #1803, so I'm going to close it in favor of that.
