### ISSUE TITLE
I can`t connect with bedrock client

### ISSUE THREAD

**Issue by SoenkeK** [GeyserMC/Geyser#2085]
### Describe the bug

When I join my Server it load a long time and said "Connecting to external Server" after that it says: " Connecting timed out, unable to connect to world" With the java client I can without problems join the Server.

I have a Paper 1.16.5 Server but I tested the same with a Spigot Server.
It was the same Problem.

### To Reproduce

.

### Expected behaviour

.

### Screenshots / Videos

The Log: https://workupload.com/file/6kcprF4xx79

### Server Version and Plugins

Plugins: only the Geyser plugin. nothing else

### Geyser Dump

https://dump.geysermc.org/g6vjhUY6NNTeLjHQo4cJsNwck8sUKKEw

### Geyser Version

1.3.0-SNAPSHOT (git-floodgate-2.0-677a8d6) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.210)

### Minecraft: Bedrock Edition Version

1.16.210

### Additional Context

#Geyser version:
 I also have tested a other Geyser Version. It was the same problem.

**Comment by Camotoy** [comment]
`Current Java version: 1.8.0_51`

Your Java version is out of date. Please download a new version from https://adoptopenjdk.net/.
