### ISSUE TITLE
team scoreboard setdisplay ignored

### ISSUE THREAD

**Issue by EldritchGarden** [GeyserMC/Geyser#2086]
### Describe the bug

Team scoreboards do not work correctly for bedrock players. Bedrock players can see a team scoreboard even when they are not in the team, or may not even if they are in the team.

Bedrock players can see a team sidebar even when they arent in the team if there is no default sidebar. If a default sidebar is set and then unset they can no longer see the team sidebar, however when that player then joins the team they do not see the team sidebar (it appears after relogging though).

### To Reproduce

1. create a dummy objective with random score
2. set display for objective to a team color sidebar

### Expected behaviour

Expected behavior is for bedrock players not in a team to be unable to see a team color sidebar, and for the sidebar to then appear when the player joins a team.

### Server Version and Plugins

Running Paper git-paper-573 on MC 1.16.5

### Geyser Dump

https://dump.geysermc.org/p78hbbEb1udn0XiYtHCm3oXvLlkQHmO4

### Geyser Version

1.2.0-SNAPSHOT (git-master-3a4b1e4)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment]
If you are familiar with testing PRs, could you try https://github.com/GeyserMC/Geyser/pull/2078 and see if your issue is resolved there?

**Comment by KalixWolf** [comment]
That PR seems to solve the issue of being able to see teams sidebars, however when the sidebar is cleared/the player leaves the team they can still see the sidebar until the player relogs.

Setting the objective to sidebar.team.aqua - bedrock player unable to see it
Adding the player to team color aqua - player can see it
Removing the player from team aqua - player can still see until they relog

**Comment by Jens-Co** [comment]
Hello @KalixWolf, Are you still having this probem? Otherwise ill test this out and close this issue.

**Comment by KalixWolf** [comment]
I don't really have time right now and I haven't been using scoreboards on my server recently so I haven't had any issues

**Comment by Jens-Co** [comment]
I'll close this issue for now, if you are still having this problem let me know and I'll reopen this.

**Comment by HaveSomeRubicon** [comment]
Im having this problem
