### ISSUE TITLE
Crashing when connecting from Low-end device

### ISSUE THREAD

**Issue by WolfyRed** [GeyserMC/Geyser#2088]
### Describe the bug

Joining the Geyser Server on a low-end device crashes the client joining, before it can even render chunks.

### To Reproduce

1. Get a slow tablet/phone
2. Join a Geyser Server that seems to have this bug
3. The server loads in
4. Your client tries to render the world
5. SUDDEN CRASH!!!

### Expected behaviour

To be able to join the server, since I can join the Geyser official testing server just fine on the low-end device. (Shown below)

### Screenshots / Videos

https://user-images.githubusercontent.com/66114400/112939453-7dfe3400-90f9-11eb-8c50-54cc1f789d71.mp4

### Server Version and Plugins

* **Version:**
`Paper version git-Paper-655` *(MC: 1.13.2)*

* **Plugins:**
`ViaVersion`  *(ViaVersion-3.2.2-SNAPSHOT)*
`Geyser-Spigot`  *1.2.0-SNAPSHOT (git-master-3a4b1e4)*
`floodgate-bukkit`  *(4th release)*

### Geyser Dump

https://dump.geysermc.org/E1nchJ3uiCKMzFnYfnPWo9UBwJLbqzSP

### Geyser Version

1.2.0-SNAPSHOT (git-master-3a4b1e4)

### Minecraft: Bedrock Edition Version

v1.16.201

### Additional Context

*P.S.; please don't suggest "Just join from a better device".*

*Some people don't have better devices to join from, and if it's also a Bedrock Server, they can join from Minecraft Bedrock.*

**Comment by WolfyRed** [comment]
If you saw the "Server version" as `1.12.2` before, that was a mistake, since it is inconsistent with what was tested *(And what the Geyser Dump had output)*

**Comment by rtm516** [comment]
My guess is that this is caused by a strange entity in the world. If you could try a few things as listed below.
1. Try a fresh world
2. Try a fresh world with old player data (checks if its inventory-related)
3. Try another position in the existing world
4. Maybe worth updating the server as I see no reason for you not too.
5. If all else fails please can you share the world file?

**Comment by WolfyRed** [comment]
> My guess is that this is caused by a strange entity in the world. If you could try a few things as listed below.
> 
> 1. Try a fresh world
> 2. Try a fresh world with old player data (checks if its inventory-related)
> 3. Try another position in the existing world
> 4. Maybe worth updating the server as I see no reason for you not too.
> 5. If all else fails please can you share the world file?

I did try a fresh world, it was brand new.

**Comment by WolfyRed** [comment]
Also what info is needed? I provided a Geyser dump, it provides much info on the server.

**Comment by rtm516** [comment]
> Also what info is needed? I provided a Geyser dump, it provides much info on the server.

I need you to try all the steps, but because you are in a fresh world you can start from 3

**Comment by Camotoy** [comment]
You have ViaVersion on both BungeeCord and the backend - remove it from one (preferably BungeeCord) and try again.

**Comment by WolfyRed** [comment]
> You have ViaVersion on both BungeeCord and the backend - remove it from one (preferably BungeeCord) and try again.

It still crashed, and I'm running only the Spigot server and joining it from Geyser

**Comment by WolfyRed** [comment]
"Try from a different position" what do you mean by that? Would any position work, like 5 blocks away and join again, or 64 chunks away?

**Comment by Camotoy** [comment]
More like 64 chunks away.

**Comment by WolfyRed** [comment]
> 
> 
> More like 64 chunks away.

Gonna try again then but real quick does viaversion 4.0.0 work cuz im about to use that version

**Comment by Camotoy** [comment]
You would need to use the `viaversion4.0.0` Geyser branch.

**Comment by WolfyRed** [comment]
> 
> 
> You would need to use the `viaversion4.0.0` Geyser branch.

is that floodgate 2.0 or 1.0 based

**Comment by Camotoy** [comment]
Only the Floodgate 2.0 branch is 2.0-based.

**Comment by WolfyRed** [comment]
It did not work, I sent myself 64 chunks away and it crashed again

**Comment by Jens-Co** [comment]
Hello @WolfyRed, you got any more info on this issue yet ?

**Comment by Jens-Co** [comment]
I'll close this issue since there is no response. If somehow you are still getting this error on the latest, please let me know and I'll reopen this issue. Thanks.
