### ISSUE TITLE
horse bugs

### ISSUE THREAD

**Issue by shinnag0103** [GeyserMC/Geyser#2089]
### Describe the bug

1. When I jump on a horse, the forefoot will remain bounce.
2. When another user is running on the horse, it looks like running sideways.
3. If I get damage while riding a horse or enter the water flow, the screen crashes such as warping.

### To Reproduce

As above

### Expected behaviour

As above

### Screenshots / Videos

https://youtu.be/bx9DZJSxpNk

### Server Version and Plugins

spigot-1.16.5

blocklocker
floodgate-bukkit
GamemodeInventories
Geyser-spigot
Luckperms
LWCX
Multiverse-core
Multiverse-NetherPortal
Multiverse-Portals
ServerRestorer
SignBoard
SkinRestorer

### Geyser Dump

https://dump.geysermc.org/GhblBgHs1AumYp1No2AUu7E7vC60pVow

### Geyser Version

 1.2.0-SNAPSHOT (git-master-3a4b1e4)

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment]
Please provide a Geyser dump. `Run "geyser dump" (server console) / "/geyser dump" (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. `

**Comment by shinnag0103** [comment]
https://dump.geysermc.org/GhblBgHs1AumYp1No2AUu7E7vC60pVow

**Comment by Camotoy** [comment]
Bullet points one and three have been addressed by #2115.

**Comment by RednedEpic** [comment]
Stale. Please open a new issue if the second bullet point mentioned still occurs.
