### ISSUE TITLE
Anticheats bugs

### ISSUE THREAD

**Issue by Ruymanphone** [GeyserMC/Geyser#209]
**Describe the bug**
AAC Anticheat (And NoCheatPlus) detects climbing plants and water lily like flying and move hacks

**To Reproduce**
1. Go to your paper server'
2. Use AAC Advanced Anticheat and NoCheatPlus'
3. Play in a swamp, will be funny, enjoy it '
5. I don't know if there are more related with this bug, the aac is more annoying because kicks you from the server, nocheatplus only cancel the move and send spam

*(This will happen too if you try to move before logging with the AuthMe Reloaded)
*Swimming too

**Expected behavior**
Don't have problems

**Server version**
Paper 229 (1.15.2)+Waterfall 341 with ViaVersion

**Geyser version**
Master 103

**Bedrock version**
1.14.60 (I tried in W10)

Opinion: I actually testing GeyserMC in my test subserver, but I really won't use GeyserMC in my survival server if the anticheat only give false errors and kick players because yes, but anyway, you can see that the plugin still has a lot of work to do, I want to use &2 or color nodes \u00A74 in the motd

Disabling multiplayer anticheat by detecting that they enter via bedrock will not be an option, people in the future could imitate mods to cheat servers and avoid banning and there are currently cheats in bedrock edition like ToolBox

Much encouragement for your project

![Eo](https://user-images.githubusercontent.com/24842739/76695739-cb3c6e80-667a-11ea-9294-bfc8a9ca70b4.png)

**Comment by RednedEpic** [comment]
This is likely both caused by bedrock edition and the anticheat itself thinking the player is hacking. Bedrock movement is slightly different than java edition, and the anticheat doesn’t know that. 

While I’m not saying there isn’t room for improvement on Geyser’s end as there definitely is, don’t expect anticheats to treat bedrock players the same as java players—support for Geyser in most all cases will need to be implemented in the anticheat itself. 

Could you please provide more information on what exactly caused the false detections? You say climbing and moving, but climbing on what, and moving on what?

**Comment by Ruymanphone** [comment]
Climbing plants, walking on water lilies, swimming, I have not tested more but then I could do a test with all the blocks, effects such as levitation and trying someone else's pvp, then I try when I have time

**Comment by Ruymanphone** [comment]
If you like I can also give you access to the ip so you can enter the server

**Comment by Ruymanphone** [comment]
There are problems with FastEat too

**Comment by Ruymanphone** [comment]
Okay, when the player is levitating with shulker, tells a bit of ExtraElytra, and when is fall tells is fly and kick the player, the potions don't have skin too and the player sometimes can't equip his armor when is enchanted

**Comment by Ruymanphone** [comment]
If you are using SkinRestorer, the server won't load the parts of custom look in that users

**Comment by Ruymanphone** [comment]
Its me or the sync of inventory its not very well xd

**Comment by Ruymanphone** [comment]
I think the problem has to do with the ping that the client's server receives, in most errors it comes out 0ms, the anticheats use ms information to work on users

**Comment by TermitCG** [comment]
There are issues with walking on stairs and slabs too. Also detects as flying.

**Comment by ohlookitsderpy** [comment]
I can reproduce this issue with the Spartan anti-cheat - it detects as speed hacks (got kicked from a server when using Geyser standalone and moving around).

**Comment by AnonAlpha** [comment]
Also can be reproduced with AntiAura, even if the strictness is only 1, it will still detect bedrock as cheating, and none anticheat can anti the real cheat such as toolbox

**Comment by Heath123** [comment]
NoCheatPlus has issues because of float/double precision differences as far as I can tell.

**Comment by RednedEpic** [comment]
These bugs reported here more or less fall under general movement bugs which are covered in #204. If you notice that other non-movement related actions are flagging anticheats, please feel free to open individual issues for those specific instances (preferably with videos) so we can look into that specifically with more detail.
