### ISSUE TITLE
Soul sand slowdown is not working correctly

### ISSUE THREAD

**Issue by hilltty** [GeyserMC/Geyser#2092]
### Describe the bug

Soul sand stopped slowing when jumping

### To Reproduce

1. Run across the soul sand and jump

### Expected behaviour

Possible player hitbox bug

### Screenshots / Videos

https://youtu.be/tDyJUiDT72Y

### Server Version and Plugins

Yatopia version git-Yatopia-pr/upstream-"e33aa22" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Plugins (12): AdvancedNMotd, AuthMe, AutoRestart, Chunky, CommandWhitelist, CoreProtect, Geyser-Spigot, Harbor, InventoryRollbackPlus, LiveKit, TakeAim, WhitelistPlayers

### Geyser Dump

https://dump.geysermc.org/1ec4vDwb3OYwycrEWg7Ze5mU8J7iOMeY

### Geyser Version

1.2.0-SNAPSHOT (git-master-aa5c3c3)

### Minecraft: Bedrock Edition Version

1.16.210 (PS4)

### Additional Context

Also checked for Paper and Tuinity, the bug is everywhere

**Comment by Camotoy** [comment]
I was able to confirm this, but it also happens on a Bedrock server, meaning it's more of a client issue.

**Comment by RednedEpic** [comment]
Client issue which may be fixed now. Closing.
