### ISSUE TITLE
Hopper GUI not working

### ISSUE THREAD

**Issue by TesterHere06** [GeyserMC/Geyser#2094]
### Describe the bug

I was testing Space plugin and for some reason it doesn't open the hopper GUI on bedrock as I showed on video. Horewer first hopper menu open, second one didn't

### To Reproduce

1. Open hopper GUI

### Expected behaviour

I cliked first hopper GUI to launch myself into space, after some time it was supposed to open another Hopper GUI to choose either you want to choose a planet or return to earth as it does on Java.

### Screenshots / Videos

https://youtu.be/M9EWW5tlUGg

### Geyser Dump

https://dump.geysermc.org/kW14L4vfjTd2owAHXw3Ku1EGw4KFowu9

### Geyser Version

1.2.0-SNAPSHOT(git-master-aa5c3c3)

### Minecraft: Bedrock Edition Version

1.16.210

### Additional Context

Also as I showed in the video the flying iron nugget that is supposed to represent the rocket doesn't show up.

The code that is supposed to run to open the GUI is shown in the video. At least that's what I think it is.

**Comment by TheMonBonGH** [comment]
What plugins and server version are you using?

**Comment by Camotoy** [comment]
The Geyser dump shows that.

What would be most helpful is which plugin(s) the hopper GUI comes from.

**Comment by TesterHere06** [comment]
> What plugins and server version are you using?

Written in the dump.

**Comment by TesterHere06** [comment]
> The Geyser dump shows that.
> 
> What would be most helpful is which plugin(s) the hopper GUI comes from.

Space

**Comment by TesterHere06** [comment]
https://www.spigotmc.org/resources/space.59572/

**Comment by Camotoy** [comment]
Ah, paid.

I'm afraid it won't be easy for us to debug this without an alternative way to replicate the issue.

**Comment by TesterHere06** [comment]
That's sad... Is there any way I could help? Because I really wish there was some way to fix that.

**Comment by RednedEpic** [comment]
Plugin is paid. If there are updated replication steps on how to reproduce this without using a paid plugin (perhaps with a code snippet) please open a new issue.
