### ISSUE TITLE
World/Server Switching

### ISSUE THREAD

**Issue by TheMonBonGH** [GeyserMC/Geyser#2096]
### What feature do you want to see added?

I want to request a configuration in Geyser to change the way servers are being switched to (bungeecord/velocity). Instead of switching servers like going to a dimension, I want it to change chunks to the other server just like CubeCraft does when switching lobbies and playing a game, without showing the nether/end screen.

### Are there any alternatives?

I have no idea. If this already exists, then let me know.

**Comment by Camotoy** [comment]
This *is* possible, though of course not for switching between dimensions. Some server softwares, such as BungeeCord, do this on a network level, so we can't avoid that. If @RednedEpic has time, I'd appreciate any input he has on if this would be worth implementing/replacing the old system.

**Comment by YHDiamond** [comment]
This would be more of a server side thing though, right? The server should choose how to switch a server.

**Comment by RednedEpic** [comment]
To keep behavior consistent with Java and to prevent potential desyncs + loading issues, this isn't something we're interested in pursuing.
