### ISSUE TITLE
....... In middle screen

### ISSUE THREAD

**Issue by itjerryz** [GeyserMC/Geyser#2101]
### Describe the bug

When i left click on air it's alway .......... In middle screen 
How can i disable it

### To Reproduce

F

### Expected behaviour

F

### Screenshots / Videos

F

### Geyser Version

Latest Version

### Minecraft: Bedrock Edition Version

1.16.210

**Comment by Camotoy** [comment]
Set `show-cooldown` to `false` in your Geyser config if you don't wish to have the attack cooldown.
