### ISSUE TITLE
Ominous Banner not shown above Pillager Captains

### ISSUE THREAD

**Issue by MagnoBooter** [GeyserMC/Geyser#2103]
### Describe the bug

You can't tell the difference between a regular Pillager and a Pillager Captain, because the Ominous Banner is not displayed above his head.

### To Reproduce

1. Summon a pillager until it has the NBT tag PatrolLeader set to 1, and a Ominous Banner in its ArmorItems NBT tag.
2. You will not be able to tell the difference unless you read its data (using /data get entity ...)

### Expected behaviour

An Ominous Banner should be visible above the Pillagers head if the Pillager is a captain.

### Geyser Dump

https://dump.geysermc.org/dvMcBnVo0kSGp2nWRtbuoaz974l97cCW

### Geyser Version

1.2.0-SNAPSHOT (git-master-8f6785e)

### Minecraft: Bedrock Edition Version

1.16.201.01

BEDROCK screenshot:
![Screenshot at 2021-04-05 16-13-21](https://user-images.githubusercontent.com/3240114/113595372-31ef4a00-9639-11eb-8c70-7c3768eefcc4.png)

JAVA screenshot:
![Screenshot at 2021-04-05 16-13-49](https://user-images.githubusercontent.com/3240114/113595375-33207700-9639-11eb-88ce-912a0bdeed0a.png)

**Comment by ChiboYen** [comment]
Unfortunately this issue is back in the latest build of Geyser.
`[06:02:42 INFO]: This server is running Geyser version 2.1.2-SNAPSHOT (git-master-0e3e2d0) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)`

https://github.com/GeyserMC/Geyser/assets/69435677/8a644642-bf6c-4822-b485-f9bb1e7afd2e
