### ISSUE TITLE
When PC players are on, mobile players crash

### ISSUE THREAD

**Issue by FuyuChan1** [GeyserMC/Geyser#2104]
### Describe the bug

Whenever java players are on, bedrock players start crashing. I have no idea whats causing this. The plugins i have on my server are skinsrestorer, geyser-spigot and floodgate-bukkit, the version is spigot 1.16.5

### To Reproduce

1. mobile players enter, play ok
2. java player enters
3.mobile players crash

### Expected behaviour

1.mobile players enter, play ok
2.java player enters
3.mobile players stay

### Geyser Version

idk how to find the version, it says geyser-spigot

**Comment by Konicai** [comment]
Please provide a dump. 

run `geyser dump` in console or `/geyser dump` in game.

**Comment by Chew** [comment]
Not enough information has been provided to keep this issue open. Gonna close it unless we get some more info. Thank you for reporting!
