### ISSUE TITLE
A way for bedrock players to get their xuid easier

### ISSUE THREAD

**Issue by BlAnKcOd3** [GeyserMC/Geyser#2107]
### What feature do you want to see added?

A way for bedrock users to get their xuid so their skin can be uploaded for floodgate 2.0. I would like to see it in the geyser test server or it can built into Floodgate/Geyser. The command would be /f xuid and it can be used for other players like /f xuid ".Player". But, the /f xuid ''.Player" can only be used for operators of the server. When you issue the command, it would say something like: "Your xuid is ..." or "Player's xuid is ...". I am not sure if this has been talked about but it's an idea that geyser can implement. 

### Are there any alternatives?

Another alternative is to have a tutorial or a wiki page about getting your xuid.

**Comment by Chew** [comment]
So, essentially, get their UUID normally? I can't exactly tell what the suggestion is.

**Comment by Camotoy** [comment]
Yeah, this is out of the scope of the Geyser program. It's not a bad idea for the wiki though. Thanks for suggesting anyway!
