### ISSUE TITLE
Cannot craft items that use redstone torches in latest 1.16.220 release

### ISSUE THREAD

**Issue by rgronberg** [GeyserMC/Geyser#2111]
### Describe the bug

Today I updated my server plugin to the latest to support 1.16.220. There is now a but where I cannot craft any recipe that uses redstone torches (repeater, comparator, activator rail). The crafting UI looks as if I do not have any redstone torches in my inventory. The redstone torches in the crafting grid appear with red boxes. Even if I manually build up the recipe, the crafting output slot does not populate. When I login the same user in Java client I can craft the items just fine

### To Reproduce

Have three redstone torch, three stone, and one quartz in inventory and try to craft a comparator in the crafting table

### Expected behaviour

Can craft items that require redstone torches

### Geyser Version

`This server is running Geyser version 1.2.1-SNAPSHOT (git-master-86b2901) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220)`

### Minecraft: Bedrock Edition Version

1.16.220

**Comment by Camotoy** [comment]
Can you try to reproduce this bug in a singleplayer world or standard multiplayer Bedrock environment? Does it affect 1.16.210 or below?

**Comment by rgronberg** [comment]
This was initially reported against a nintendo switch client. On that device in a single player world and on dedicated bedrock server, the crafting is working as expected.

I did try to login to my server from the same account that was having issues on the switch, but from my phone with a controller attached and I *can* craft using redstone torches. Not sure if mobile is handled differently.

So far, I can reliably reproduce on a switch client running 1.16.220 in a Geyser proxied server, but not single player or bedrock dedicated server.

**Comment by Camotoy** [comment]
I'm able to confirm this on Geyser with Windows 10 1.16.220.

**Comment by zombihunterbonn** [comment]
Is it fix?

**Comment by Chew** [comment]
^ indeed it is :) Please avoid bumping issues for updates though
