### ISSUE TITLE
Shulker Boxes arent craft able in 1.16.220 geyser update

### ISSUE THREAD

**Issue by MrRazamataz** [GeyserMC/Geyser#2112]
### Describe the bug

I have confirmed its a geyser bug as it works in singleplayer. The crafting receipe doesnt show and doesnt work when you manually place it. It works in 1.16.210.  Similar to the redstone crafting issues in #2111

### To Reproduce

Get the items for a shulker box.
Try to craft it.
You cant

### Expected behaviour

Be able to craft the shulker box.

### Screenshots / Videos

In geyser: https://mrrazamataz.ga/archive/mcserver/noshulker.png
In vanilla: https://mrrazamataz.ga/archive/mcserver/shulker.png

### Server Version and Plugins

This server is running Yatopia version git-Yatopia-ver/1.16.5-42 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Previous version: git-Yatopia-ver/1.16.5-40 (MC: 1.16.5)

This server is running Geyser version 1.2.1-SNAPSHOT (git-master-86b2901) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220) BungeeCord

### Geyser Dump

https://dump.geysermc.org/eCuJwTkRIRmoqzX7iDPCP9NvqSO2yMhM

### Geyser Version

1.2.1-SNAPSHOT (git-master-86b2901)

### Minecraft: Bedrock Edition Version

1.16.220

**Comment by Camotoy** [comment]
Marking this as confirmed as hoppers are also uncraftable - so the missing link is likely the chests doesn't show up correctly.

**Comment by NotGalacticFire** [comment]
So after the default version was changed to 1.16.220 i upgraded geyser to the latest version but crafting hoppers still doesn't work
