### ISSUE TITLE
Can't connect from bedrock clients

### ISSUE THREAD

**Issue by Lucaslah** [GeyserMC/Geyser#2119]
### Describe the bug

I have setup Geyser with floodgate Bukkit but when I try and connect from a bedrock client the app crashes (Bedrock Client App)

Output of `/geyser dump` https://dump.geysermc.org/hN6Zl4prxPWDO5splfpVf02fNpopuuCX

When I first tried to connect I got a Broken Pipe error.

Then I changed `ping-passthrough-interval: 3` to `ping-passthrough-interval: 6` to try and fix the error, Now the Bedrock client app crashes when I try and join the server.

Joining other bedrock server works on my bedrock client

### To Reproduce

1. Download and Install Geyser and floodgate
2. Copy `public-key.pem` from the floodgate-bukkit folder to the Geyser-Spigot folder
3. Change `auth-type` from online to floodgate in the config.yml file
4. When Connecting from a bedrock client, It dose not work

### Expected behaviour

I should be able to connect from a bedrock client

### Server Version and Plugins

Version: 3036-Bukkit-c85efa8 (MC: 1.16.5)

Plugins: 
- ChestCommands
- dynmap
- floodgate-bukkit
- Multiverse-Core
- scriptcraft
- SetHomes
- WorldBorder
- WorldEdit
- WorldGuard

### Geyser Dump

https://dump.geysermc.org/hN6Zl4prxPWDO5splfpVf02fNpopuuCX

### Geyser Version

1.2.1-SNAPSHOT (git-master-e549792)

### Minecraft: Bedrock Edition Version

1.16.200

### Additional Context

The Bedrock client is IOS, on an iPad mini 2

**Comment by Camotoy** [comment]
Don't use Bukkit. Use Spigot or one of its forks.

Closing since that's likely your issue - otherwise, please let us know!

**Comment by Lucaslah** [comment]
I switched to Spigot and I worked, Thanks

But after about 10min's of playing I get disconnected.
