### ISSUE TITLE
remaining inventory bugs

### ISSUE THREAD

**Issue by LegacyGamerHD** [GeyserMC/Geyser#212]
**Describe the bug**

- get a inventory plugin with back space the next menu wont open  (expected: that can be opend) 
- some old custom inventory plugins have ghost items (expected: nto not ghost and open them)
- left click doesnt work on windows 10 and android (exepcted: hat you can left click a item so it opens a sell meu or someting else)
- crafting on xbox is broken (cant craft on xbox i dident test it yet i heard multiple poeple talking on discord(expected: is that can craft on xbox))

**Screenshots**
Ghosting item issue: https://www.youtube.com/watch?v=tyjIkv0lCWA

**Server version**
run paper build  #137 

**Geyser version**
latest inventory from jenkins #9 

**Bedrock version**
1.14.30

**Additional context**
pls tell me if there are more 📦

**Comment by LegacyGamerHD** [comment]
i will record more info when i got more time

**Comment by LegacyGamerHD** [comment]
this is supirier of #211

**Comment by RednedEpic** [comment]
See todo list on #67.

**Comment by LegacyGamerHD** [comment]
@RednedEpic  those arnt on the todo list

**Comment by LegacyGamerHD** [comment]
reopen it.... right click isnt in todo list and doesnt work ehh ghosting issue isnt on there etc

**Comment by JuniorJPDJ** [comment]
open new issue then
every bug should have separate issue @LegacyGamerHD 
it's easier to maintain it like that

**Comment by LegacyGamerHD** [comment]
@JuniorJPDJ  can you not mix with it

**Comment by Heath123** [comment]
> @JuniorJPDJ can you not mix with it
?
