### ISSUE TITLE
Unable to move items in inventory when the durability bar is showing.

### ISSUE THREAD

**Issue by AlecMcQuarrie** [GeyserMC/Geyser#2120]
### Describe the bug

When you are on Bedrock, you are unable to move items from one slot to another in your inventory if the durability bar is showing. This means that, when the item is in perfect condition (no durability bar) you are able to move it, but when the items is slightly or any form of damaged, you can't move it. You can still drop the item and pick up the item, but not move it to a different slot.

### To Reproduce

Have an item in which the item has some damage, to where the durability bar shows, and attempt to move it to a different slot within your inventory on bedrock.

### Expected behaviour

The item should be able to be moved between slots in your inventory, but you are unable to move it.

### Geyser Dump

https://dump.geysermc.org/bg5vgJ9BSlquN5p4FfDo6d2nnLv2h1Vo

### Geyser Version

1.3.0-SNAPSHOT (git-floodgate-2.0-34fa547)

### Minecraft: Bedrock Edition Version

1.16.220

**Comment by Camotoy** [comment]
Unable to replicate with the latest master build and Paper 1.16.5 579. Can you try testing with Paper?

**Comment by Camotoy** [comment]
The user updated in my DMs that the issue has to do with EcoEnchants, which we have an existing issue open for (#2034)
