### ISSUE TITLE
Problem with executing command with an item gui

### ISSUE THREAD

**Issue by TheRealSlimFury** [GeyserMC/Geyser#2121]
### Describe the bug

When connected to a proxy (WaterdogPE) if you use an item from an inventory gui the command that the item should execute doesn’t work.

### To Reproduce

OLD GEYSER VERSION:
Joined the server with WaterdogPE proxy and the commands executed from the item gui worked
NEW VERSION OF GEYSER WITH THIS BUG:
Joined the server with WaterdogPE proxy and the commands executed from the item gui don’t work
Joined the server without WaterdogPE proxy and the commands from the item gui work.

WaterdogPE is not the problem because the commands from the guis stopped working since a new update (1.16.210 build) and on the new 1.16.220 version
These are the two geyser that i’ve used (the old version with 1.16.210 that worked fine and the new one that has this bug)
https://filebin.net/l426ni7p0s66iicx

### Expected behaviour

When joining trough the proxy commands with item gui should execute

### Screenshots / Videos

Example video with a casual premade server:
https://filebin.net/tgqbu99bgs2ugadk

### Server Version and Plugins

PaperSpigot 1.8.8 with java 1.8.0
Plugins used: StrikePractice, Geyser-Spigot
With WaterdogPE Proxy (1.16.210)

### Geyser Dump

https://dump.geysermc.org/vtWYH0S76cc12vlCZqDhnrwOLvLBKB2b

### Geyser Version

git-master-7a7cf18e997b10dd48a5fa887498ad7b9ef30570

### Minecraft: Bedrock Edition Version

1.16.210

### Additional Context

The proves that i’ve sent were made a day before the 1.16.220 bedrock update (latest 1.16.210 build), i can’t remember what’s the last build that didn’t have this bug.
I tried using the latest version of java, paperspigot spigot, geyser and waterdogpe and still didn’t work.

**Comment by Camotoy** [comment]
Does the bug exist when not using WaterdogPE?

**Comment by Camotoy** [comment]
Also, please provide exact replication steps - what plugins can we use with what configuration files, for example? How can one of the developers replicate this step-for-step?

**Comment by TheRealSlimFury** [comment]
> Also, please provide exact replication steps - what plugins can we use with what configuration files, for example? How can one of the developers replicate this step-for-step?

- Download StrikePractice plugin: https://www.spigotmc.org/resources/strikepractice-–-1v1-2v2-bots-fights-pvp-events-parties-build-fights-and-more.46906/
- Download PaperSpigot 1.8.8
- Download ViaVersion latest
- Download Geyser latest
- Download and set up WaterdogPE latest:
https://jenkins.waterdog.dev/job/Waterdog/job/WaterdogPE/job/master/54/
- Start the server
- Set up a casual arena with strikepractice
- Restart the server
- Join the server via WaterdogPE proxy and use the command /queue or /unranked or the item to join a queue and click on the item (you should be able to join but it won’t)
- Join the server without proxy and do the same, it will actually work.

**Comment by TheRealSlimFury** [comment]
> Does the bug exist when not using WaterdogPE?

The bug doesn’t exist when not connected to the proxy but as i already clarified, waterdog isn’t the problem because it was working fine before the 1.16.220 geyser update

**Comment by Camotoy** [comment]
I disagree. If it only happens with Waterdog, then it sounds like a Waterdog issue. Try updating it if it got an update? Otherwise, I don't see how this is our issue to fix. Talk to Waterdog - if they think we need to fix something, then let them know to contact me.

Thanks for reporting a bug anyway!

**Comment by TheRealSlimFury** [comment]
> I disagree. If it only happens with Waterdog, then it sounds like a Waterdog issue. Try updating it if it got an update? Otherwise, I don't see how this is our issue to fix. Talk to Waterdog - if they think we need to fix something, then let them know to contact me.
> 
> Thanks for reporting a bug anyway!

But the with the old version of geyser was working fine, anyway I’ll talk to the Waterdog Devs too
