### ISSUE TITLE
Enchanting Not Working on Bedrock

### ISSUE THREAD

**Issue by WillyWhitewool** [GeyserMC/Geyser#2126]
### Describe the bug

Enchanting is not working on bedrock. Enchanting tables will not enchant even when you click the enchantment, and getting a enchanted book from commands or dropped by another player generally disconnects the player.

### To Reproduce

1. Get an enchanting table, lapis and an enchantable item.
2. Try to enchant it.
3. Try using anvils and enchanting books and even enchanted items.

### Expected behaviour

Player either cannot enchant an item, or is disconnected when enchanted items are in his inventory. Once I got the "Connection Closed" error message.

### Geyser Dump

https://dump.geysermc.org/Y3RbttrqRgGaM7Lz6rhutstJ0X1jk2Ge

### Geyser Version

1.3.0-SNAPSHOT (git-floodgate-2.0-53ac196)

### Minecraft: Bedrock Edition Version

1.16.210 - 1.16.220

**Comment by Camotoy** [comment]
I can confirm that enchanting does not work on 1.12.2.

**Comment by Konicai** [comment]
Do you know if the same applies to versions below 1.12.2?

**Comment by Camotoy** [comment]
Working my way up from 1.12.2 - that way I can use ViaVersion as a base for what changed in the code to allow an enchant.

**Comment by Camotoy** [comment]
It works in 1.14.4.

**Comment by WillyWhitewool** [comment]
Should I install the Geyser Compression level jar from ci?

**Comment by Camotoy** [comment]
That jar is not related to this PR.

**Comment by WillyWhitewool** [comment]
Still having the issue on the latest version of Geyser and Floodgate 2.0.

https://dump.geysermc.org/AsxPoa4aIOaUAei0S9HVGRp7ygd0LyMk

**Comment by Camotoy** [comment]
This bug has not yet been merged into Floodgate 2.0.
