### ISSUE TITLE
lags and PID 18

### ISSUE THREAD

**Issue by masterhacka** [GeyserMC/Geyser#2129]
### Describe the bug

Most of the time a Bedrock player joins the server the log says: Can't keep up. Also the player is often falling down on join and spawns somewhere else except from the spawn where it should. The most problem is the Error in log followed by a crash: [https://paste.gg/p/anonymous/1009e482f3334d07844221e135dec70d](https://paste.gg/p/anonymous/1009e482f3334d07844221e135dec70d)

### To Reproduce

Install Geyser and Floodgate on a Paper server and join the server.

### Expected behaviour

No lags and no errors in log. Also no crashes.

### Server Version and Plugins

newest Paper build
Plugins can be seen in Geyser dump

### Geyser Dump

https://dump.geysermc.org/cL80wPBih77nQ1E38dabXsZyxlF52upK

### Geyser Version

1.2.1-SNAPSHOT-latest build

**Comment by Camotoy** [comment]
Looks like your server is simply overloaded. The Paper guys said to ask in their help channel, and we'd recommend that as well. If they determine that this is indeed a Geyser issue, feel free to let us know. Thank you!
