### ISSUE TITLE
[Suggestion] PluginEventTranslator

### ISSUE THREAD

**Issue by TheRobLP** [GeyserMC/Geyser#213]
**What feature do you want?**
Okay, so. Geyser is designed for the latest Minecraft. However, many plugins are still using pre-1.15 events to function, mainly for backwards-compatability reasons. While Paper and Spigot have a sytsem for this case, Geyser does not. I would love to see a Translator for Events and so on, to ensure that as many plugns as possible can work with Geyser

**Alternatives?**
None as far as I know

**Comment by Tim203** [comment]
What do you mean?
Geyser is a protocol translator, not a server software.

**Comment by RednedEpic** [comment]
Sounds a bit like an x y problem situation here. What I could gather from your message on discord was that the inventory branch was bugging out with the shop plugin you were using. The link you gave me was to the developer API events the plugin exposed. It only called them, not listened to them.

> However, many plugins are still using pre-1.15 events to function, mainly for backwards-compatability reasons. 

This doesn't make much sense at all. There are no pre-1.15 events in Spigot. All events work and are for the latest version of the game.

> I would love to see a Translator for Events and so on, to ensure that as many plugns as possible can work with Geyser.

This is not something Geyser would implement, nor would this be the proper way to implement an "event translator." Event's in Bukkit are just actions and even listeners listen for when those actions are called. For example, there is an event for when a player throws an egg. When the egg is thrown, the code listening to it is called. It's simply just a function of the Bukkit API and is nothing Geyser would implement.

**Comment by TheRobLP** [comment]
To my defense: LegacyGamerHD told me that. Since he knows more about development then I do, I believed him.

**Comment by LegacyGamerHD** [comment]
hey @TheRobLP i dident say that am bad english

**Comment by TheRobLP** [comment]
Can someone maybe delete this commit? It makes me look VERY dumb, and tha´s a bit emberassing to be honest.
