### ISSUE TITLE
 Illegal reflective access Java 9+

### ISSUE THREAD

**Issue by DoctaEnkoda** [GeyserMC/Geyser#2131]
### Describe the bug

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.nukkitx.protocol.bedrock.util.EncryptionUtils (file:/var/lib/pufferpanel/servers/fe3febc9/plugins/Geyser-Velocity.jar) to method com.sun.crypto.provider.GaloisCounterMode.getJ0(byte[],byte[])

### To Reproduce

Use Java 15 and Velocity

### Expected behaviour

When player bedrock connect, this warning is here

### Server Version and Plugins

Plugins : Floodgate, Geyser

### Geyser Dump

https://dump.geysermc.org/mG5f9bROP4bi4yKgY4ZiuNwh2SgxvdCN

### Geyser Version

1.3.0-SNAPSHOT (git-floodgate-2.0-34fa547)

### Minecraft: Bedrock Edition Version

1.16.220

**Comment by Camotoy** [comment]
This warning is likely present on Java 9 and above. It is safe to ignore on your version, but Java 16 currently does not work with Geyser due to this error. We plan to have a workaround in the future!

**Comment by RednedEpic** [comment]
Fixed in latest version.
