### ISSUE TITLE
Issues with anti cheat reloaded / any anti-cheat

### ISSUE THREAD

**Issue by Gontijo8199** [GeyserMC/Geyser#2134]
### Describe the bug

False positives due to the movement of bedrock players in the server.

### To Reproduce

Download ACR and ProtocolLib
Install geyser and floodgate
Start the server
Join with a deoped bedrock account, start walking/jumping/breaking blocks
Get warned/kicked for "hacking"

### Expected behaviour

Get warned/kicked/auto-banned by a false positive of movement hacks.

### Screenshots / Videos

![image0](https://user-images.githubusercontent.com/79460524/114703296-75ae1780-9cfb-11eb-8e06-39557985b3f0.png)
Screenshot related to the issue.

### Server Version and Plugins

PaperMC Latest (And a proxy: Bungee/waterfall)
ACR latest
Geyser&Floodgage latest

### Geyser Dump

I am not using Standalone GUI

### Geyser Version

Latest dev version released (In my bungee and paper server)

### Minecraft: Bedrock Edition Version

Latest released.

### Additional Context

I don't know if this is a copy from another issue
I solved this issue in my server creating a profile only for bedrock players, and with that profile, I added the bypass permission node, even tho it still being a bug.

**Comment by rtm516** [comment]
This isn't really a Geyser bug and just cause by how bedrock handles movement client-side therefore there isn't much we can do about it. I would suggest making sure that you have chunk caching enabled as that will help, I would check for you but you didn't provide a dump (dumps can be made on any Geyser platform not just standalone).

**Comment by Camotoy** [comment]
Do feel free to add the anticheat(s) here: https://github.com/GeyserMC/Geyser/wiki/Anticheat-Compatibility

The page is currently not on the wiki sidebar, but I've been meaning to build it up a little more first!
