### ISSUE TITLE
Cannot pick up water

### ISSUE THREAD

**Issue by HideyBoi** [GeyserMC/Geyser#2137]
### Describe the bug

When on bedrock, sometimes it does not let you pick up water.

### To Reproduce

1. place a bucket of water.
2. try to pick it up

It seems to be random, so it might not work...

### Expected behaviour

The water is supposed to be picked up and in your inventory.

### Geyser Dump

https://dump.geysermc.org/m3WJqPnMAGefwHDpGiWl3TJY7kdDdG93

### Geyser Version

1.2.1 Snapshot

### Minecraft: Bedrock Edition Version

1.16.220

**Comment by Camotoy** [comment]
Judging by "it seems to be random", you're running into the same issue as #1891. Therefore, I will close this issue.

Thank you regardless for reporting!
