### ISSUE TITLE
Head display is abnormal

### ISSUE THREAD

**Issue by yueziji** [GeyserMC/Geyser#214]
**Describe the bug**
Head display is abnormal

**To Reproduce**
–Open slimefun GUI
–Head display is abnormal

**Expected behavior**
Head can show normal

**Screenshots**
like this
![S00318-00532025](https://user-images.githubusercontent.com/21022131/76881493-2f964280-68b4-11ea-9b86-8740de01bb6c.png)
![S00318-00532851](https://user-images.githubusercontent.com/21022131/76881517-38871400-68b4-11ea-8ae0-c02139be805b.png)

**Server version**
git–paper-243（MC1.14.4）
Slimefun-v4.2-NIGHTLY-200317
ViaVersion-3.0.0-SNAPSHOT
（ViaVersion-Abstraction # 43）
ViaBackwards-3.0.0-SNAPSHOT
（ViaBackwards-Abstraction # 109）

**Geyser version**
Jenkins inventory # 9

**Bedrock version**
Bedrock v1.14.30.2

**Additional context**
none.

**Comment by LegacyGamerHD** [comment]
well thats limation off bedrock bedrock doesnt support custom player heads so close this redned

**Comment by yueziji** [comment]
> well thats limation off bedrock bedrock doesnt support custom player heads so close this redned

ok，well😌
