### ISSUE TITLE
Towny doesn't register bedrock players (UUID?)

### ISSUE THREAD

**Issue by xxxcrow** [GeyserMC/Geyser#2140]
Hi, everyone 👋
Recently I've noticed that towny actually doesn't work with Geyser
It says the same thing when i try to break block in somebody's town, join a town, create a town 🥲
It says "player is not registered, try to relog"
I'm still investigating the problem
I already tried to reinstall geyser, floodgate, and towny, didn't work
I'm pretty sure i noticed some similar problem in some other place, if i find i will add it here 🤔
Thank you ❤️

**Comment by rtm516** [comment]
This is likely caused by the floodgate prefix, I would suggest changing it to `.` in the config. But if that doesn't fix it please resubmit this issue but following the bug report template.
https://github.com/GeyserMC/Geyser/issues/new?assignees=&labels=&template=bug_report.yml

**Comment by xxxcrow** [comment]
@rtm516 i don't see any template from my app 😂 although it supports it, and i had one on another hub around 15 minutes ago 😃

**Comment by xxxcrow** [comment]
@rtm516 holly molly, it worked 🤯🤯🤯🤯
I had no hope of truly solving this issue, but here it is✨✨✨
Thank you a lot ❤️
