### ISSUE TITLE
Health Check For Geyser

### ISSUE THREAD

**Issue by CoreyShupe** [GeyserMC/Geyser#2141]
### What feature do you want to see added?

Would like to see an internal server to export health information.

### Example:
Define a port in configuration to run the internal server for health checks.

In the same server we can use an external process to query `127.0.0.1:port/health` to retrieve health status of geyser.

### Use Case:
In certain cases in devops there's a necessity to know when something is failing, working properly, or going down.
This health check would either return a 200 status when healthy, 404 when not ready, along with other status codes to define current state/health of the geyser proxy.

### Benefits:
This would allow an external process to monitor the health of geyser.

### Are there any alternatives?

Have looked through the codebase a bit and it doesn't look like there's anything to probe the health of the geyser without passing through UDP packets which is not necessarily ideal for this kind of service.

**Comment by rtm516** [comment]
Couldn't you just send a server query to Geyser for what you want? Since if the server is up then it will respond.

**Comment by CoreyShupe** [comment]
> Couldn't you just send a server query to Geyser for what you want? Since if the server is up then it will respond.

Is what you're talking about a UDP query to geyser to get the status of the server? Like imitating a bedrock client handshake to get server data.

If so, that seems a bit unnecessary / heavy for a health check. Also, doesn't that also try to contact the bungee for server information or am I misunderstanding what that query actually does.

**Comment by rtm516** [comment]
It also supports the normal java query (also uses UDP).
Not sure this is something that would be suited in core Geyser, my main concerns are the extra jar size a web server library would create as that's something we are trying to keep low.

**Comment by CoreyShupe** [comment]
> It also supports the normal java query (also uses UDP).
> Not sure this is something that would be suited in core Geyser, my main concerns are the extra jar size a web server library would create as that's something we are trying to keep low.

It'd just be a request -> response, there are plenty of lightweight http response things out there. I don't think a full web server library is necessary, especially when java itself packages in some nice http server, which is all that's necessary for this kind of work honestly.

My main concerns with the UDP query is that the java query (UDP query) looks heavy for something like a health check. It looks like it also wants quite a bit more information than just a ping to the server (looking at a few go libs which do support this kind of ping).

I think the benefits the health check will give to the devops world outweighs the concern for package size, especially since there's http server handlers within java itself.

**Comment by CoreyShupe** [comment]
Another note, seems like this would generally only be necessary in the standalone versions where it's not running inside of another process, since it's expected that the containing process has some sort of health indicator which can also handle the state of geyser. I'll scratch up a PR for the standalone integration of this concept.

**Comment by rtm516** [comment]
It's best to just integrate it into the connector module then it should work on any platform.

**Comment by CoreyShupe** [comment]
This was denied in the PR stages. Closing for now.
