### ISSUE TITLE
[PE] Items with durability get stuck in player's cursor

### ISSUE THREAD

**Issue by Miv2nir** [GeyserMC/Geyser#2145]
### Describe the bug

When I try to pick an unenchanted item with durability from my inventory and move it to chest, it basically retracts to my cursor and since I'm playing BE on mobile, it just gets stuck so the only thing I can do with it is to throw it out of the inv. (I'm using both Geyser and Viaaas, however when using via with java edition nothing like that ever happens to mel

### To Reproduce

1. Use Geyser to join a server with somewhat low tps (probably)
2. Aqcuire any items that have durability and try to move them around in your inventory (on win10 similar thing happens when doing Shift + Left Click)
3. Observe the issue

### Expected behaviour

The item should be able to stay in place and not to get stuck in my cursor, unable to put it anywhere except throw out.

### Screenshots / Videos

[PE bug](https://youtu.be/E4mEz6rQqSc) 
[Win10 bug](https://youtu.be/E0uelgbuHbg) 

### Server Version and Plugins

The server version is currently 1.12.2 (this is why I use Viaaas). It is running Sponge with a bunch of custom written plugins that I don't have access to :(. Server ip is minecraftonline.com, in case if you wanna investigate it yourself

### Geyser Dump

https://dump.geysermc.org/qSj4jKgQugAUTZadf71XtY55pMq8E6hr

### Geyser Version

1.2.1-SNAPSHOT (git-master-70e2860)

### Minecraft: Bedrock Edition Version

1.16.220

**Comment by Camotoy** [comment]
Does the server run some form of EcoEnchants or Eco?

**Comment by Miv2nir** [comment]
> Does the server run some form of EcoEnchants or Eco?

Nope. An admin said that their plugins are all custom at this point :(

**Comment by Camotoy** [comment]
Hmm. It would be super helpful if we could narrow it down - we'd rather not hijack the server by joining and leaving repeatedly while trying to figure out the issue!

**Comment by Miv2nir** [comment]
Well as far as I can tell, it only happens when I move those items with Shift + Click on win10 version, and it only happens with items that have durability but no enchantments. The server also is on fairly low tps most of the time. My setup is geyser pointing to viaaas, that I use to join 1.12.2 servers, however when using viaaas with java edition this thing does not happen. I also asked a server admin about that bug, however, they said they were not gonna bother because the server is intended to be played from java. You can also contact one of the plugin developers and admins of minecraftonline over [https://discord.gg/minecraftonline](here). If you're gonna do it, I recommend contacting Vecxin. (not posting his discord ID here)

**Comment by sankalp2736** [comment]
I have the same problem some times. I am playing on bedrock on a java server running 1.16.5

**Comment by Camotoy** [comment]
Please provide a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by Konicai** [comment]
Without further information, and considering none of these plugins are public, this will be closed. 

There's a high chance this is due to some sort of ProtocolLib usage. See https://github.com/GeyserMC/Geyser/issues/2219 and https://github.com/GeyserMC/Geyser/issues/2034
