### ISSUE TITLE
Extreme Lag in Xbox using both BedrockConnect and Phantom Proxy software

### ISSUE THREAD

**Issue by burdoto** [GeyserMC/Geyser#2148]
### Describe the bug

So I'm aware theres probably a limitation to this; but recently Geyser has been observed to be causing extreme latency when trying to play on a Java Server with Geyser from Xbox through a DNS proxy utility; both BedrockConnect and Phantom have been tested, and neither has been performing anywhere near acceptable latencies.
Please provide me with details on how to extract the necessary logs for evaluation. Love this project!

### To Reproduce

- Paper MC 1.16.5 (Build 599)
- GeyserMC (version of today)
- Pugmatt/BedrockConnect (Branch Tag 1.6.4)
- jhead/Phantom (Tag 0.5.3)

### Expected behaviour

no lag

### Server Version and Plugins

PaperMC 1.16.5 (Build 599)

### Geyser Dump

https://dump.geysermc.org/WCX1iYq8xRAtIkd2k1peMHhRiAJJ3PYY

### Geyser Version

Build Number 674 (where is your version listed....)

### Minecraft: Bedrock Edition Version

1.16.22002.70

**Comment by Camotoy** [comment]
As a starting point: try the `compression-level` branch on the Jenkins CI?

**Comment by burdoto** [comment]
I have just attempted using that Version and while it seems it does help with most latency issues, combat is still a no-go. Short lag spikes of .5-2 seconds are still ocurring once I start attacking something, or something starts attacking me. (Skeletons are easy now, duh).
I have created another Dump after testing: https://dump.geysermc.org/Y5fWhS89WlXlTdq9ofRhSa0Y57CKT9ST

**Comment by Camotoy** [comment]
It adds a new setting under `bedrock` titled `compression-level` that goes up to 9. See if increasing it helps at all?

Otherwise, we'll have to look elsewhere, but seeing that branch helped is a great start.

**Comment by burdoto** [comment]
Okay so, cranking this option up to 9 from the beginning has helped another MARGIN, yet theres still some latency involved.
Things like Fighting a Zombie, excavating a couple of iron ore and then moving on no longer includes large latency problems, but walking through a cave and THEN meeting a Zombie still causes large lag spikes, which, upon stopping to move, calm down fairly quickly.

And a Note; Connecting takes a LONG while, always did on every configuration. Inventory being loaded after 30 up to sometimes 90 seconds?

**Comment by Camotoy** [comment]
What is your `remote` `address` set to? (Do `/geyser dump full` to see what it ends up being).

**Comment by burdoto** [comment]
ah jeez! i just did that other one, now i'm being ratelimited.

**Comment by burdoto** [comment]
Here's the full dump: https://dump.geysermc.org/SsT3agc6SwNq9zYupVYuJfgeZ7rRKXpG

**Comment by Camotoy** [comment]
Try setting `remote` `address` to `127.0.0.1`?

**Comment by burdoto** [comment]
The Geyser Server now is no longer reachable from outside. I'm not highly aware of the network connection of this server.

**Comment by burdoto** [comment]
Another Update about `compression-level` branch:
 Today, stuff's running even better. Combat is still hard sometimes, but overall it provided a MARGINAL improvement towards master branch, so far also no bugs or crashes. I'll consider this case closed.

**Comment by Camotoy** [comment]
Great! I'll try to get that merged today into master.

**Comment by burdoto** [comment]
Another Note: Not combat in particular, but Projectiles seem to be one problematic thing. 

Patchnotes:
Skeletons are now Enderman 😋
