### ISSUE TITLE
Some particles are broken

### ISSUE THREAD

**Issue by GoldenMyst** [GeyserMC/Geyser#2150]
### Describe the bug

Using end rod particle it shows as carrot item crack, but on the actual item it shows it correctly. And angry villager shows as slime particle.

### To Reproduce

1. Summon particles of end rod or/and angry villager

### Expected behaviour

I was expecting the correct particle

### Server Version and Plugins

git-Tuinity-“94f025a” (MC: 1.16.5)

### Geyser Version

1.3.0-SNAPSHOT (git-floodgate-2.0-34fa547)

### Minecraft: Bedrock Edition Version

1.16.220

### Additional Context

* I disabled my texture pack but it didn’t fix it.

**Comment by nickg2** [comment]
can confirm this happens to me too

**Comment by GoldenMyst** [comment]
https://user-images.githubusercontent.com/74118946/115156024-423ef600-a037-11eb-9a12-b01ec4d1e26b.MOV

**Comment by Camotoy** [comment]
Fixed with #2147.
