### ISSUE TITLE
Broken Pipe when trying to connect from Bedrock client

### ISSUE THREAD

**Issue by kubus1472** [GeyserMC/Geyser#2152]
### Describe the bug

I am trying to join my server from minecraft bedrock edition client and i am getting an error "java.io.IOException: Broken Pipe"
i can't join the server from java edition as well - when i try to join from java edition it just says "Disconnected"

### To Reproduce

1. start the server
2. try to join from minecraft bedrock client
3. see error

### Expected behaviour

be able to join from both java edition and bedrock edition

### Server Version and Plugins

Server version:
This server is running CraftBukkit version 3045-Spigot-a25e8ed-115244c (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

 Plugins (65): CraftserveAgent, PlaceholderAPI, LumenTech, NametagEdit, InsaneAnnouncer, ConsoleSpamFix, SpigotPing, SkinsRestorer, MinecraftManhunt, PlayerReport, HeadDrops, MurderMystery, EasyWhitelist, Geyser-Spigot, LuckPerms, AnimatedScoreboard, MoreSounds, TheBridge, InventoryRollback, AnvilLot, LoginPlus, floodgate-bukkit, SnowballDamage, Vault, LastLoginAPI, Graves, WorldEdit, Essentials, BountyHunters, SafeTrade, Multiverse-Core, HomeGUI, Multiverse-Portals, CCTV, WorldGuard, EssentialsProtect, MinecraftChess, GSit, EssentialsSpawn, PvPManager, CoreProtect, Skript, Citizens, BuildBattle, Duels, ReviveMe, BedWars, CombatIndicator, Skywars, MobArena, HolographicDisplays, VillageDefense, SignShop, LockettePro, Magic, OreAnnouncer, ProtocolLib, Instruments, Orebfuscator, VentureChat, InteractiveChat, ServerlistMOTD, DiscordSRV, SBAHypixelify, InteractiveChatDiscordSRVAddon

### Geyser Dump

https://dump.geysermc.org/35GOvBDeSBDn2pvx8fyx900ggg3WXdyg

### Geyser Version

Geyser version 1.2.1-SNAPSHOT (git-master-852d5b0) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220)

### Minecraft: Bedrock Edition Version

1.16.220.2

**Comment by Camotoy** [comment]
Errors like these are usually a result of configuration errors. Please join our Discord for more assistance. Thank you!
