### ISSUE TITLE
Cross-save

### ISSUE THREAD

**Issue by lewidar** [GeyserMC/Geyser#2155]
### What feature do you want to see added?

Having the cross-save feature for Java and Bedrock. For example, you build a house on your Bedrock account, log out, and log in in your Java account, and you can get back to building (if you linked these two accounts.)

### Are there any alternatives?

Finding plugins that already does that.

**Comment by Camotoy** [comment]
This is already accomplished in Floodgate's account linking feature. Therefore, I am closing. Thanks anyway!
