### ISSUE TITLE
Old server Player data issue with Usernames for java players.

### ISSUE THREAD

**Issue by pupshadow** [GeyserMC/Geyser#2156]
### Describe the bug

Hello I have an issue with bedrock players not seeing java players usernames on their head it is showing numbers instead. 

I am running the most updated papermc and have a bunch of plugins but diagnosed that my plugins aren't the issue. I found the issue to be my PlayerData file in my main world. 

My server is from 2013 and I have had many players join this is the first year I have had geysermc and floodgate 2.0 on my server people connect great but there is just slight issues with them seeing established java players names on my server.

Bedrock players can see the names in chat but only numbers above the heads.

### To Reproduce

So when I first found this issue out I contacted Camotoy on Discord and he told me to start with a fresh build and try to reproduce the issue.

Steps I took:

1: New Papermc jar and installed both geysermc and flood2.0.  (Can see java players names on bedrock.)

2: Started to bring my starting world in with all Playerdata.  (Wasn't able to java players names anymore just numbers.)

3: Deleted player data file completely and started fresh. (Can see java players names on bedrock.)

4: Put back player data then just deleted my user file only. (Wasn't able to see java players names anymore just numbers.)

5: deleted all player data and brought in all plugins. (Can see java players names on bedrock.)

### Expected behaviour

I expect to have any bedrock player to see any of my java players name properly and not numbers...

### Screenshots / Videos

Here is the issue with player data added.
![Player data added](https://user-images.githubusercontent.com/35120956/115337147-76690280-a16e-11eb-9f59-eabce40a937d.jpg)

Here is it with all player data deleted.

![Player data Deleted](https://user-images.githubusercontent.com/35120956/115337744-8d5c2480-a16f-11eb-80ae-54b193c99843.jpg)

### Server Version and Plugins

Version:  

[00:25:43 INFO]: Checking version, please wait...
[00:25:43 INFO]: This server is running Paper version git-Paper-602 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-584 (MC: 1.16.5)

Plugins:

AdvancedNMotd v9.1.1
AntiXRay v1.9.0
AutoRestart v4.2.1
BentoBox v1.16.1
ChestSort v9.7.1
ClearLag v3.2.2
CoreProtect v19.5
DeadChest v4.3.0
dynmap v3.1-457
Essentials v2.19.0-dev+87-b43790e
Essentials_WarpGUI v2.2.2
EssentialsAntiBuild v2.19.0-dev+87-b43790e
EssentialsChat v2.19.0-dev+87-b43790e
EssentialsGeoIP v2.19.0-dev+87-b43790e
EssentialsProtect v2.19.0-dev+87-b43790e
EssentialsSpawn v2.19.0-dev+87-b43790e
eZProtector v1.1.0
EZRanksPro v1.10.2
FastAsyncWorldEdit v1.16-659;8b69d8a
floodgate v2.0-SNAPSHOT
Geyser-Spigot v1.3.0-SNAPSHOT
Harbor v1.6.3
Lands v5.5.1
LibsDisguises v10.0.24
LuckPerms v5.2.76
LWC v2.1.5-09ad392
MineConnect v0.4
Multiverse-Core v4.2.3-SNAPSHOT-b837
Multiverse-Inventories v4.2.3-SNAPSHOT-b511
Multiverse-Portals v4.2.2-SNAPSHOT-b841
PlotSquared v5.13.11-Premium
PlugMan v2.2.1
ProtocolLib v4.6.1-SNAPSHOT-b498
PureTickets v5.1.0
ServerSigns v4.6.4
ShatteredCore v1.4.19 (9a12b74)
ShatteredScrolls v2.0.0 (fb1a98d)
SkinsRestorer v14.0.2
StaffFacilities v5.0.9
TreeAssist v7.1.18
Vault v1.7.3-b131
Vivecraft-Spigot-Extensions v1.16.5-r1
VoidGenerator v1.7.0
WorldBorderAPI v1.0
WorldGeneratorApi v1.1.4
WorldGuard v7.0.4+f7ff984
WorldGuardEvents v1.0

### Geyser Dump

https://dump.geysermc.org/cGjE2DHvKTXkdTeTOYbRdBKwfNaxDHJk

### Geyser Version

Geyser-Spigot v1.3.0-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.16.220

**Comment by pupshadow** [comment]
With the help of Camotoy looking at my Playerdata files. They found that my file had an CustomName attribute and i have searched the rest of the files in the list and only found a few files with it so I'm thinking that the older my players were that joined in the early days I must have had a plugin that added it onto their files.    Fix was just removing that CustomName attribute from the files that had them and it fully fixed my issue. Thank for the help. :Closing Ticket:

**Comment by Camotoy** [comment]
Reopening since this shouldn't have happened in the first place. :P

**Comment by Camotoy** [comment]
This is probably fixed now; and since you removed the file manually and I don't currently have access to your world data I'll close this issue.

**Comment by pupshadow** [comment]
> This is probably fixed now; and since you removed the data manually and I don't currently have access to your world data I'll close this issue.

Yeah I think it fully is it hasn't happened again if you would like the old world data I think I can bring it back up for you again. But I just have a feeling since I have had my server since 2013 it may have just been a very messed up data file from one of the older Minecraft server updates that was created.
