### ISSUE TITLE
Dynamic lights implementation

### ISSUE THREAD

**Issue by ImDaBigBoss** [GeyserMC/Geyser#2157]
### What feature do you want to see added?

Dynamic lights option for bedrock players. Maybe this could be done by placing light blocks at the position of the player.

### Are there any alternatives?

Simply placing torches or an other light source down.

**Comment by Camotoy** [comment]
Could you elaborate on the purpose of this?

**Comment by Camotoy** [comment]
It may make things look realistic, but it's not exactly vanilla behavior. :P 

This seems out of the scope of the Geyser project, but it's not an invalid request, so I'll leave this open for now. If this can be done via a resource pack, that would likely be the preferred option.

**Comment by RednedEpic** [comment]
Considering Optifine is a Minecraft mod and this is not something that Minecraft does natively, it's not really within our scope. This may be better fit as an extension in the future but not really in the main project itself.
