### ISSUE TITLE
Titles in Java does not appear in Bedrock

### ISSUE THREAD

**Issue by mentobento** [GeyserMC/Geyser#2158]
### Describe the bug

The title (the thing that is in the middle of the screen and run with /title) does not appear in Java. This is a problem since titles can be used for captcha and welcome messages. Please chec asap

### To Reproduce

Open a minecraft server with a welcome message plugin. 
Error: welcome message doesnt appear

### Expected behaviour

It should have displayed "Welcome to the Server! <IGN>. 

### Geyser Version

1.3

### Minecraft: Bedrock Edition Version

1.16.201

**Comment by Camotoy** [comment]
Please provide a Geyser dump.

For the time being, I can confirm that this is not an issue as I was just testing a server with titles showing up fine.

**Comment by Konicai** [comment]
Do you have Hud Opacity greater than zero % in your client video settings?

**Comment by chenxi050402** [comment]
I have this issue before when I was using titles
The title displays but it needs another title to bump it out

**Comment by RedSmarty** [comment]
> The title (the thing that is in the middle of the screen and run with /title) does not appear in Java. This is a problem since titles can be used for captcha and welcome messages. Please chec asap
But geyser doesn't modify the server at all, so I don't think its the reason for titles to not appear on **Java Edition**. Correct me if i am wrong :p

**Comment by MrRazamataz** [comment]
Does your title appear on java edition?

**Comment by RednedEpic** [comment]
Closing due to lack of response and inability to reproduce.
