### ISSUE TITLE
Putting items into container sometimes glitch out

### ISSUE THREAD

**Issue by TaaranGupta** [GeyserMC/Geyser#2160]
### Describe the bug

Update: So my previous description of this bug and steps to reproduce were wrong and unclear, so here are the updated one:
So when I try to put items into a container, some of the items glitch and become a small image of themselves and follow the cursor. It happens to random items and so I did a few tests to see any common stats of items this bug happens to, and after a few tests, I have come up with a list of items that this bug happens to, when transferring from inventory to any container or vice versa.
(Note: The items that this bug happens to is random and the following list is just the statistics of a major amount of items. This means that some items from the list below, might not be bugged and even items not in the following list might be bugged for you)
1. Tools or Armor enchanted by a Java player before or after adding the geyser plugin to the server.
2. Enchanted tools that were dropped by killing a mob like zombie, drowned, etc. by a Java player.
3. Items renamed by a Java player BEFORE geyser plugin was added to the server.
(Bugged items will remain bugged for that mcpe player and no items are bugged for the Java player, even the ones that are bugged for mcpe player)

### To Reproduce

(Random)
1. (By Java player) Get a bunch items from the list above and place them in chests(or any container).
2. (By mcpe player) open the containers and transfer these items from the container to your inventory one by one. 
3. Some of these items will be bugged for you.

### Expected behaviour

Expected: the item should have simply gone in the container without any problems.

### Screenshots / Videos

https://user-images.githubusercontent.com/82931006/115510488-6f8cdd80-a29d-11eb-9dfb-e941c93f7e17.mp4

### Server Version and Plugins
Server version:- spigot 1.16.5

### Geyser Dump

https://dump.geysermc.org/VOAZ775UNqEPuTGVh7DkEZNYmEwOqefI

### Geyser Version

1.2.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.16.220

**Comment by Camotoy** [comment]
Please provide a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by TaaranGupta** [comment]
Ok I just uploaded the dump

**Comment by Camotoy** [comment]
I'm unable to replicate this. 
3048-Spigot-a25e8ed-9db9aee
Geyser 678

**Comment by trool00** [comment]
This small item bug also happen when collecting item from furnace and sometimes crafting items

**Comment by RednedEpic** [comment]
Is this still an issue?

**Comment by Jens-Co** [comment]
Tried to replicate on latest Geyser & Floodgate was not able to replicate. I'll  close this issue, if the bug still appears please let me know I'll reopen this issue.
Thanks

**Comment by TaaranGupta** [comment]
> Tried to replicate on latest Geyser & Floodgate was not able to replicate. I'll close this issue, if the bug still appears please let me know I'll reopen this issue.
> Thanks



> Tried to replicate on latest Geyser & Floodgate was not able to replicate. I'll close this issue, if the bug still appears please let me know I'll reopen this issue.
> Thanks

I have updated the issue and it's still very much a bug so I would like to reopen this issue

**Comment by Jens-Co** [comment]
I've reopened this issue, can you please add an updated geyser dump ( command: geyser dump )

**Comment by RednedEpic** [comment]
No updated Geyser dump since requested. No further reports from others either, so am going to close this. Please open a new issue if this still occurs with updated replication steps (& a new Geyser dump).
