### ISSUE TITLE
Custom Model Data

### ISSUE THREAD

**Issue by jravuwannab** [GeyserMC/Geyser#2165]
### What feature do you want to see added?

Custom model data in resource packs would be an awesome feature. Ive seen lots of people requesting it in the discord so I figured I'd make an official request here.

### Are there any alternatives?

Other than changing the model of the actual item there is no other way that I am aware of.

**Comment by Camotoy** [comment]
Thanks for the request! This has been tracked in #210; because of this I will close this issue in favor of that one.
