### ISSUE TITLE
Failed to start Geyser on 0.0.0.0:19132, Address already in use

### ISSUE THREAD

**Issue by SethHumanBean** [GeyserMC/Geyser#2167]
### Describe the bug

When I install Geyser onto my Paper server it gives me the error `Failed to start Geyser on 0.0.0.0:19132`
I noticed that the same error was in the Common Issues section of the wiki, but I'm using Apex as a host, not running it on my own computer so there would be no other programs running and restarting the server didn't fix anything.
These are the full logs: https://pastebin.com/kMkpbjH2, the issue with Geyser appears around the middle of the paste.
Here's my config.yml: https://pastebin.com/44UcZ2E9
The config for Floodgate is default.
Here's my plugin list:
![image](https://user-images.githubusercontent.com/62271290/115889241-01692780-a411-11eb-91a8-b2353012ba44.png)

### To Reproduce

1. Install Geyser-Spigot and Floodgate-Bukkit
2. Restart the server

### Expected behaviour

I expected Geyser to work, it did not.

### Server Version and Plugins

Version:
![image](https://user-images.githubusercontent.com/62271290/115889902-9ec45b80-a411-11eb-9b38-d132dbb9595e.png)
Plugins:
![image](https://user-images.githubusercontent.com/62271290/115889942-a97ef080-a411-11eb-9138-e526fa6da94a.png)

### Geyser Version

The latest one from the Jenkins build page

**Comment by Camotoy** [comment]
According to the Supported Hosting Providers page, you need to set `bedrock` `address` to your external IP, and you may need to change your assigned port as well.

We generally don't keep connection/setup issues on the issue tracker, so if you need further help, do feel free to join our Discord. Thank you!

**Comment by tlaus1** [comment]
i get the same error but i dont get what you mean bc im not a tech expert
