### ISSUE TITLE
Blocks above nether roof cannot be displayed

### ISSUE THREAD

**Issue by chenxi050402** [GeyserMC/Geyser#217]
**Describe the bug**
Blocks above the nether roof cannot be displayed and appeared to be ghost blocks.

**To Reproduce**
1. Build something above the nether roof in Java edition
2. Log in with bedrock edition.
3. Anything above y = 127 cannot be displayed.

**Expected behavior**
Just like Java edition, you can build and load buildings above the nether roof.

**Screenshots**
![批注 2020-03-18 110232](https://user-images.githubusercontent.com/62318879/76921053-fe476200-6907-11ea-8203-79d3a9844fc6.png)

**Server version**
Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Geyser version**
Geyser-Bukkit version 1.0-SNAPSHOT

**Bedrock version**
ver 1.14.30

**Additional context**
Bedrock nether build height is 128.

**Comment by RednedEpic** [comment]
> **Describe the bug**
> Blocks above the nether roof cannot be displayed and appeared to be ghost blocks.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Build something above the nether roof in Java edition
> 2. Log in with bedrock edition.
> 3. Anything above y = 127 cannot be displayed.
> 
> **Expected behavior**
> Just like Java edition, you can build and load buildings above the nether roof.
> 
> **Screenshots**
> ![批注 2020-03-18 110232](https://user-images.githubusercontent.com/62318879/76921053-fe476200-6907-11ea-8203-79d3a9844fc6.png)
> 
> **Server version**
> Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
> 
> **Geyser version**
> Geyser-Bukkit version 1.0-SNAPSHOT
> 
> **Bedrock version**
> ver 1.14.30
> 
> **Additional context**
> Bedrock nether build height is 128.

From your screenshot it looks like the build is there. Perhaps I’m misunderstanding, but could you provide a screenshot comparison of both versions?

**Comment by jackson-57** [comment]
I've had the same thing happen on my server. Want screenshots?

**Comment by RednedEpic** [comment]
> I've had the same thing happen on my server. Want screenshots?

Yeah.

**Comment by chenxi050402** [comment]
![2020-03-18_11 10 56](https://user-images.githubusercontent.com/62318879/76921654-837f4680-6909-11ea-8256-61a542774c53.png)
Screenshot from Java edition

**Comment by jackson-57** [comment]
That's what it looks like for me. Yours is a better example than mine, anyway. I'm not running the latest build, but I doubt that would change anything?

**Comment by jackson-57** [comment]
If I remember correctly, it shows the height limit message in chat when you attempt to build.

**Comment by chenxi050402** [comment]
Maybe the bedrock edition won't load anything above y=127

**Comment by Loganh4005** [comment]
I think due to height limit it won't load above because I believe that it only loads in a certain radius on upward (aka 127 blocks) and then it just thinks the rest is air so I don't think it is possible to fix

**Comment by endevrr** [comment]
It is possible to fix, setting the sky to an overworld sky makes the blocks re-appear, only the nether sky prevents blocks above y 128 from rendering

**Comment by creativegamer03** [comment]
Same thing to End structures above y=256 on the newest 1.18 update, especially with the Nullscape modpack on a Java server. lost my stuff because i cant access the graves due to "glitching" in unrendered blocks of an End City structure (that is half rendered) and the Shulkers assumed im on air which the projectiles did travel in the "air". I hope Mojang increase the build height limit to 512 or more.

**Comment by Camotoy** [comment]
If this Nullscape pack uses the 320/-64 height, then you're free to make another issue about it (where we can exchange the End dimension for the overworld). If it goes further than that, we're not interested in adding a workaround for it unless Bedrock allows that functionality natively
