### ISSUE TITLE
Add per user settings

### ISSUE THREAD

**Issue by ImDaBigBoss** [GeyserMC/Geyser#2171]
### What feature do you want to see added?

There is already `/geyser settings` but this globally sets the settings. What would be nice would be an option for individual users to choose settings that they want. Maybe not everyone wants show coordinates on, maybe not everyone wants to see the hit cooldown in the title as opposed to in the actionbar.

### Are there any alternatives?

Not really

**Comment by Konicai** [comment]
Would require geyser storing data afaik. Would be cool though.

**Comment by Camotoy** [comment]
Storing data would only be required for user preferences to remain on relogging, which isn't mentioned as a part of this issue. 

`show-coordinates` already has a user toggle.

**Comment by Tydium** [comment]
I was actually thinking about something like this today, but for showing all command suggestions. Maybe if a specific player has a permission for seeing geyser.suggestions (example) then they would be able to see all command suggestions next time they join. Or something like that.

**Comment by Chew** [comment]
It's an interesting concept but leaves out users who use standalone or platforms that don't support permissions.

**Comment by Konicai** [comment]
This has pretty much been implemented unless you want user settings to persist after logout

**Comment by ImDaBigBoss** [comment]
Well I guess I should close this issue?
