### ISSUE TITLE
Skins disappear when joining from bedrock

### ISSUE THREAD

**Issue by leonal1** [GeyserMC/Geyser#2175]
### Describe the bug

I installed geyser through aternos and everything great but my skin is set to Steve when I join

### To Reproduce

download geyser through aternos as a plug in to your server, join through a bedrock device (iPad)

### Expected behaviour

for my skin to load

### Geyser Version

683 (Bedrock v1.16.100 - v1.16.220)

### Minecraft: Bedrock Edition Version

1.16.221

**Comment by Camotoy** [comment]
Your Bedrock skin will not be applied when using just Geyser. Since you're on Aternos, you will have to wait until Floodgate 2.0 releases.

Thanks anyway!
