### ISSUE TITLE
Custom anvil recipes are not working

### ISSUE THREAD

**Issue by TaminoPalm** [GeyserMC/Geyser#2177]
### Describe the bug

I have a Plugin on my server called ArmoredElytra, You can craft an Elytra together with a Chestplate and you get an ArmoredElytra, but it works only on java ;(

### To Reproduce

1 Dowload ArmoredElytra from Spigot
2 Open an Anvil on Bedrock
3 Drag a Chestplate and an Elytra in the Anvil
4 You dont get the Eytra
5 Try it on Java Edition to see it

### Expected behaviour

You should see the ArmoredElytra in the Anvil Field

### Screenshots / Videos

https://ibb.co/qpwsf53

### Server Version and Plugins

This server is running Tuinity version git-Tuinity-"32b4d52" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 7 version(s) behind
Previous version: git-Tuinity-"94f025a" (MC: 1.16.5)

### Geyser Dump

https://dump.geysermc.org/rMnEtc7vUdH72AGgoGUXmGJZFu8j2XG2

### Geyser Version

Geyser Version 1.2.1

### Minecraft: Bedrock Edition Version

1.16.221

**Comment by TaminoPalm** [comment]
Here a Screenshot: https://ibb.co/qpwsf53

**Comment by Camotoy** [comment]
To my knowledge, there is no way to add custom recipes to the anvil.

**Comment by RednedEpic** [comment]
Closing as this is a Bedrock limitation.
