### ISSUE TITLE
enable-proxy-protocol prohibits non-proxy connections

### ISSUE THREAD

**Issue by Brandin** [GeyserMC/Geyser#2178]
### Describe the bug

When you enable `enable-proxy-protocol`, non-proxy connections are prohibited. This setting is described as one that enables and allows Proxy Connections, it is not described as allowing Proxy connections and disallowing Non-Proxy Connections. While one may expect that is the expectation of a user who enables this, thats not always the case. 

### To Reproduce

1. Enable `enable-proxy-protocol` 
2. Connect natively with no proxy to the server
3. Connection will not succeed 

1. Disable `enable-proxy-protocol`
2. Connect to the server with a proxy that passes this value 
3. Connection will not succeed

### Expected behaviour

I'm in the midst of migrating to a new Proxy service (which is still implementing some features) which means at this time I require both: 
- users who connect to the proxy with the Proxy setting enabled to be able to connect
- those who connect through the new service with no Proxy, with the Proxy setting enabled should be able to connect

This change, however, changes the behavior of the setting, so an additional setting that allows the restriction, maybe called `enable-proxy-restriction` should be added to toggle this behavior, and enabled by default so the changes to `enable-proxy-protocol` do not create issues for existing users. 

### Geyser Dump

https://dump.geysermc.org/TmJN1kiqFnj7GGQA3dxo7shy63Qv8bZi

### Geyser Version

1.2.1-SNAPSHOT (git-master-873e37e)

**Comment by Camotoy** [comment]
I don't think we're going to implement such a niche feature. Plus, it seems generally understood within the Minecraft community that this poses a security risk: https://github.com/PaperMC/Velocity/issues/652 .
Thanks anyway.
