### ISSUE TITLE
Bricks slab and trap door can't be placed properly

### ISSUE THREAD

**Issue by AnonAlpha** [GeyserMC/Geyser#218]
**Describe the bug**
When player place a bricks slab or a trap door it just fall down.
More information in the video
[video](https://streamable.com/zptei)

**To Reproduce**
1. Setup server with geyser
2. Place a brick slab or a trap door
3. See error

**Expected behavior**
Brick slab and trap door can stay where they are and not falling down

**Screenshots**
See video above

**Server version**
paper 1.15 latest

**Geyser version**
Jenkins inventory branch latest

**Bedrock version**
latest

**Comment by TheMasterBlaster** [comment]
Stairs do the same thing when trying to place them upside down.
