### ISSUE TITLE
[Geyser-Spigot] Got an error

### ISSUE THREAD

**Issue by pupshadow** [GeyserMC/Geyser#2181]
### Describe the bug

Error file paste:

https://ghostbin.co/paste/zq7tw

### To Reproduce

IDK how to reproduce this one.

### Expected behaviour

to not spam the console.

### Server Version and Plugins

[11:29:06 INFO]: Checking version, please wait...
This server is running Paper version git-Paper-629 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-602 (MC: 1.16.5)

Plugins (52): AdvancedNMotd, AntiXRay, AutoRestart*, BentoBox, ChestSort, ClearLag, CMI, CMILib, CoreProtect, DeadChest, DiscordX*, dynmap*, eZProtector, EZRanksPro, floodgate, Geyser-Spigot, Harbor, Lands, LevelledMobs, LibsDisguises, LuckPerms, LWC, MineConnect, MoneyFromMobs, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MythicLib, MythicMobs, MythicMobsExtension, PlotSquared, PlugMan, ProtocolLib, PureTickets, ServerSigns, ShatteredCore, ShatteredScrolls, SkinsRestorer, StaffFacilities, TreeAssist, Vault, ViaBackwards, ViaRewind, ViaVersion, Vivecraft-Spigot-Extensions, VoidGenerator, WarpSystem, WorldBorderAPI, WorldEdit, WorldGeneratorApi, WorldGuard, WorldGuardEvents

### Geyser Dump

https://dump.geysermc.org/rAv9sBSO3UQPX37FMQ1yPl4nZ1vHr7ne

### Geyser Version

Geyser version 1.3.0-SNAPSHOT

### Additional Context

floodgate 2.0 running as well.

**Comment by Camotoy** [comment]
Looks like you're also getting errors about `discord.com` not being found - this just seems like your server couldn't reach DNS momentarily.

**Comment by pupshadow** [comment]
I just got rid of the DiscordX plugin it seemed to be fairly buggy. it seems to have fixed my issue here.
