### ISSUE TITLE
Translate Scoretags

### ISSUE THREAD

**Issue by RealTriassic** [GeyserMC/Geyser#2184]
### What feature do you want to see added?

It seems that Geyser doesn't translate Scoretags (the text that can be placed under a player's nametag.) It would be nice if they could be translated. I hope this is clear and concise enough of a feature request, thanks.

### Are there any alternatives?

No, there are no alternatives to try. This is a feature that is missing in Geyser.

**Comment by Camotoy** [comment]
Seems like this is already present under #1927; therefore, I'm going to close this issue in favor of that one. If this is incorrect, let me know. Thanks!
