### ISSUE TITLE
Geyser does not detect floodgate

### ISSUE THREAD

**Issue by Arthurmeade12** [GeyserMC/Geyser#2187]
### Describe the bug

When my server starts, geyser loads, but then tells me "[12:16:48 ERROR]: [Geyser-Spigot] Auth-type set to Floodgate but Floodgate is not installed! Disabling..."

### To Reproduce

1. [Download the geyser jar](https://ci.opencollab.dev//job/GeyserMC/job/Geyser/job/viaversion4.0.0/lastSuccessfulBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar)
This is exactly where I downloaded the geyser jar from. A Viaversion + Geyser combo?
2. [Download floodgate](https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/dev%252F2.0/lastSuccessfulBuild/artifact/spigot/target/floodgate-spigot.jar)
3. Make bungeecord server
4. Install [floodgate bungeecord](https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/dev%252F2.0/lastSuccessfulBuild/artifact/bungee/target/floodgate-bungee.jar) and [spigot bungeecord](https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/dev%252F2.0/lastSuccessfulBuild/artifact/spigot/target/floodgate-spigot.jar) 
5. Configure the servers how mine are configured (config for
6. Restart Bungeecord and Paper Server
7. 

### Expected behaviour

Geyser would load properly with floodgate, and no errors would occur

### Screenshots / Videos

Server error on server 2: 
https://user-images.githubusercontent.com/71673838/116822664-a5f01580-ab45-11eb-8808-f6052c68949b.png

Server error on server 1:
https://user-images.githubusercontent.com/71673838/116822666-a7214280-ab45-11eb-8e19-eeeebc4c8aaa.png

Bungeecord functioning flawlessly:

### Server Version and Plugins

Version: 

[12:29:56 INFO]: This server is running Purpur version git-Purpur-1077 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 1 version(s) behind
Previous version: git-Purpur-1070 (MC: 1.16.5)

Plugins: [12:30:27 INFO]: Plugins (13): AdvancedPortals, AntiXRay, CommandLoc*, DeadChest, DisplayName*, floodgate, Geyser-Spigot, GeyserSkinManager, Hibernate, ServerRestartWarning*, SetHomes, Timber, Vault

Note: The names of all the plugins are in green text, except for geyser which is in red text. 

### Geyser Version

Unknown, geyser shuts itself down before the server finishes loading, so I cannot run /geyser version. I am using the geyser spigot version and it tells me, "[12:20:34 INFO]: [Geyser-Spigot] Loading Geyser-Spigot v1.2.1-SNAPSHOT". 

### Minecraft: Bedrock Edition Version

? (Unable to run /geyser version)

### Additional Context

Note: I am using the same version(s) for geyser and floodgate on my bungeecord, and it functions flawlessly, leading me to believe there is something wrong in the config(s). 
Additionally, I am having this problem on both of my servers that are attached to my bungeecord. I can configure everything since both servers and the bungeecord are on my machine. 

Server 1 config.yml (converted to txt): 
[config copy.txt](https://github.com/GeyserMC/Geyser/files/6411995/config.copy.txt)

Server 2 config.yml (also converted to txt): 
[config copy.txt](https://github.com/GeyserMC/Geyser/files/6411997/config.copy.txt)

OS: MacOS 11.2.3
JDK: 11.0.10 oracle

**Comment by Camotoy** [comment]
You need to also download the Floodgate 2.0-specific Geyser build. Thanks anyway!
