### ISSUE TITLE
Bug with players on bedrock going afk.

### ISSUE THREAD

**Issue by pupshadow** [GeyserMC/Geyser#2195]
### Describe the bug

When bedrock players go afk geyser seems to throw this error.

[15:06:02 WARN]: [Geyser-Spigot] Downstream packet error! Don't know how to turn null into a Component
[15:06:02 WARN]: [Geyser-Spigot] Downstream packet error! Don't know how to turn null into a Component

### To Reproduce

have a player go afk on server and look at logs.

### Expected behaviour

to not throw a null.

### Server Version and Plugins

This server is running Paper version git-Paper-643 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 2 version(s) behind
Previous version: git-Paper-629 (MC: 1.16.5)

Plugins (52): AdvancedNMotd, AntiXRay, AutoRestart*, BentoBox, ChestSort, Citizens, ClearLag, CMI, CMILib, CoreProtect, DangerousCaves, DeadChest, DiscordSRV, dynmap*, eZProtector, EZRanksPro, floodgate, Geyser-Spigot, Harbor, Lands, LevelledMobs, LibsDisguises, LuckPerms, LWC, MineConnect, MoneyFromMobs, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, PlaceholderAPI, PlayerWarps, PlotSquared, PlugMan, ProtocolLib, PureTickets, ServerSigns, SkinsRestorer, StaffFacilities, TreeAssist, Vault, VentureChat, ViaBackwards, ViaRewind, ViaVersion, Vivecraft-Spigot-Extensions, VoidGenerator, WarpSystem, WorldBorderAPI, WorldEdit, WorldGeneratorApi, WorldGuard, WorldGuardEvents

### Geyser Dump

https://dump.geysermc.org/OgD4ilviQgiOcNVGqmrl2fHBfmxEmfth

### Geyser Version

This server is running Geyser version 1.3.0-SNAPSHOT (git-floodgate-2.0-3b9674a) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220)

**Comment by Camotoy** [comment]
1: Please provide logs with `debug-mode` enabled on Geyser and this happening.
2: Is there any plugin that provides a message when a player goes AFK? Otherwise, it would be helpful to know what plugin is causing that error.

**Comment by pupshadow** [comment]
I think CMI does afk handling  Give me a few on this debug mode.

**Comment by KappaDariusTheDen** [comment]
Any fix for this issue yet?

**Comment by Camotoy** [comment]
When does it happen for you?

**Comment by KappaDariusTheDen** [comment]
It happens every time someone goes afk on bedrock. It is constant spam. The spam stops after the user has disconnected.

**Comment by Camotoy** [comment]
Do you also have the CMI plugin installed? Does it fix itself after temporary removal?

**Comment by KappaDariusTheDen** [comment]
What do you mean by CMI? What does it stand for

**Comment by Camotoy** [comment]
Please provide a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by KappaDariusTheDen** [comment]
https://dump.geysermc.org/mMCBn7SbFtZ8Lho64iNjZfLKit16SuHA

**Comment by Camotoy** [comment]
Please try the below:

If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
- Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by KappaDariusTheDen** [comment]
If you could tell me what the error means, that would be helpful. I personally don't know what "Downstream packet error! Don't know how to turn null into a Component" means.

**Comment by KappaDariusTheDen** [comment]
It would be easier to at least have some knowledge on my end so I know what to look for.

**Comment by Camotoy** [comment]
Unless 1.17 changed something, a plugin is trying to send a title with no content.

**Comment by KappaDariusTheDen** [comment]
What do you mean by "no content" is there a way to know what content means, is there a line of code that doesn't have anything in it, or wat.

**Comment by KappaDariusTheDen** [comment]
Also I figured out this does not only happen during an afk message. It happens as soon as the person joins on bedrock.

**Comment by Konicai** [comment]
No content means that it is an empty message (zero length).

For anyone who has had this error, please follow the instructions that Camo sent to determine which plugin is (likely) causing the issue.

-  Temporarily remove/move half of your plugins from your server's plugins folder.
-   If the problem persists, remove another half.
-    If the problem goes away, swap that half of your plugins with the other half.
-    Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by Camotoy** [comment]
We've resolved this error from occurring.
