### ISSUE TITLE
Breaking a lectern kicks bedrock players

### ISSUE THREAD

**Issue by pupshadow** [GeyserMC/Geyser#2197]
### Describe the bug

When bedrock players break a lectern it kick them hard.

Error Log. https://mclo.gs/iWxz73K

### To Reproduce

get a bedrock client to break a lectern kicks them.

### Expected behaviour

to not kick the player on break.

### Server Version and Plugins

This server is running Paper version git-Paper-643 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Plugins (52): AdvancedNMotd, AntiXRay, AutoRestart*, BentoBox, ChestSort, Citizens, ClearLag, CMI, CMILib, CoreProtect, DangerousCaves, DeadChest, DiscordSRV, dynmap*, eZProtector, EZRanksPro, floodgate, Geyser-Spigot, Harbor, Lands, LevelledMobs, LibsDisguises, LuckPerms, LWC, MineConnect, MoneyFromMobs, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, PlaceholderAPI, PlayerWarps, PlotSquared, PlugMan, ProtocolLib, PureTickets, ServerSigns, SkinsRestorer, StaffFacilities, TreeAssist, Vault, VentureChat, ViaBackwards, ViaRewind, ViaVersion, Vivecraft-Spigot-Extensions, VoidGenerator, WarpSystem, WorldBorderAPI, WorldEdit, WorldGeneratorApi, WorldGuard, WorldGuardEvents

### Geyser Dump

https://dump.geysermc.org/3p3QXxnW7FOUlUSeNPHJPza0Wfzyot7Z

### Geyser Version

Geyser-Spigot v1.3.0-SNAPSHOT

**Comment by Camotoy** [comment]
Which gamemode is the Bedrock player in when this happens?

**Comment by pupshadow** [comment]
They where in creative mode when it happens.

**Comment by Konicai** [comment]
Can you still reproduce this issue?

**Comment by Konicai** [comment]
Please let us know if you're can still reproduce this issue
