### ISSUE TITLE
Minecarts are Buggy on Bedrock

### ISSUE THREAD

**Issue by WillyWhitewool** [GeyserMC/Geyser#2198]
### Describe the bug

Riding in minecarts (at least on Paper 1.12.2) has some visual glitches and lag. Possibly caused by a plugin.

### To Reproduce

1. I am using two plugins that modify minecart behavior: EasyCarts modifies speed and CraftBook makes it so right clicking on rails spawns a minecart and enters you in it, and exiting a minecart despawns it. However there were still problems before I installed CraftBook, but EasyCarts may affect minecarts on Bedrock.
2. Ride a minecart on Bedrock and exit it.

### Expected behaviour

When riding a minecart, there is lag between where the player appears to be and where they actually are. A Java account looking at a Bedrock player riding a minecart would see all functioning normally, but for Bedrock players the minecart freezes if you are not pressing the W key, usually even if you are. The Minecart will freeze at intervals and then teleport forward to, and usually be a few seconds behind its actual position. On exitting, everything in the world freezes except for your movement for about 20 seconds, and then you are teleported to the spot where you exited and all is normal again.

### Geyser Dump

https://dump.geysermc.org/l80WgceT8f7TRZMCFZYRrMyJwSjPUtx4

### Geyser Version

1.3.0-SNAPSHOT (git-floodgate-2.0-3b9674a)

### Minecraft: Bedrock Edition Version

1.16.220

**Comment by candrawardana** [comment]
![image](https://user-images.githubusercontent.com/38995778/117555963-2060ee00-b08e-11eb-9485-cf03274a8b4f.png)

Same issues here, there is no rotation in minecart

but this issue will fix if you downgrade your geyser. it's issue in new release

**Comment by Camotoy** [comment]
@candrawardana your issue does not appear to be related to the opened issue in any way. Regardless, minecart rotation when not on a track has an open PR to fix the issue.

**Comment by Kas-tle** [comment]
Given the plugins to reproduce this issue no longer actively updated and there have been various changes to entity riding, please try to reproduce this issue on the latest version of Geyser. If this can still be reproduced, I'll reopen.
