### ISSUE TITLE
chunks are not loaded on the bedrock

### ISSUE THREAD

**Issue by Brevzor** [GeyserMC/Geyser#2199]
### Describe the bug

For Java, everything works fine, for the bedrock, this is the problem:
![image](https://user-images.githubusercontent.com/57866392/117379616-814ac380-aee0-11eb-9403-5c9cb3c07973.png)

### To Reproduce

start server spigot (1.16.5) + GeySerMC last version

### Expected behaviour

adequate work.

### Server Version and Plugins

This server is running CraftBukkit version 3059-Spigot-4225eac-7ea8b96 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

Plugins (10): PermissionsEx, SetHome, WorldEdit, TreeCapitator, TimTheEnchanter, Geyser-Spigot, Essentials, EssentialsSpawn, EssentialsChat, SuperVanish

### Geyser Dump

https://dump.geysermc.org/WbPd3urPB3VZjaVyeOBEPUkSK3u0LhSR

### Geyser Version

Geyser version 1.2.1-SNAPSHOT (git-master-1301cd9)

### Minecraft: Bedrock Edition Version

1.16.221

**Comment by Camotoy** [comment]
Unfortunately, this is a Bedrock bug - without a workaround, we can't do anything about this. Your coordinates are too far out from 0,0 - move way closer to fix the issue. Sorry, but thanks for reporting anyway!

**Comment by matsyui** [comment]
So until now this is still a thing for bedrock?

Running: Java 21 (OpenJDK 64-Bit Server VM 21.0.6+7-Ubuntu-124.04.1; Ubuntu null) on Linux 6.8.0-51-generic (amd64) Paper 1.21.4-214-main@894631f (2025-03-21T17:21:46Z) for Minecraft 1.21.4

Plugins (33):
AuthMe (5.6.0-bCUSTOM), AutomaticBroadcast (1.9.0), BlockLocker (1.13), ChestShop (3.12.2 (build 353)), Chunky (1.4.28), CommandBlocker (1.6), CraftingStore (2.9.3), DecentHolograms (2.8.15), Essentials (2.21.0), EssentialsChat (2.21.0), EssentialsDiscord (2.21.0), EssentialsDiscordLink (2.21.0), EssentialsSpawn (2.21.0), FreedomChat (1.7.2), Geyser-Spigot (2.6.2-SNAPSHOT), HealthBar-Reloaded (2.0.4.1), LuckPerms (5.4.131), MoneyFromMobs (4.9), MyPet (3.12), PlaceholderAPI (2.11.6), ProtocolLib (5.3.0), SimpleClaimSystem (1.12.3), SkinsRestorer (15.6.0), TerraformGenerator (18.1.2), Themis (0.17.5), Vault (1.7.3-b131), ViaVersion (5.2.1), VotifierPlus (1.4), VotingPlugin (6.18.3), WorldEdit (7.3.10+7004-768a436), WorldGuard (7.0.13+82fdc65), floodgate (2.2.4-SNAPSHOT (b116-0e3163c)), sleep-most (5.5.3)

Bedrock (v1.21.70): Issue, players can't move and chunks are stripped

![Image](https://github.com/user-attachments/assets/d038ff39-286d-4956-a455-31f8aecf5c47)

Java (v1.21.4): Fine no issue at all.

![Image](https://github.com/user-attachments/assets/5d826944-7db5-4988-8702-1b17a7e04b7f)
