### ISSUE TITLE
[Idea] Add BossBar (with colors) support

### ISSUE THREAD

**Issue by x9nico** [GeyserMC/Geyser#22]
Hi, I have the idea to add support for BossBar with colors :)

**Comment by lukeeey** [comment]
Not possible

**Comment by x9nico** [comment]
Why? it's not implemented into Bedrock Edition ?

**Comment by lukeeey** [comment]
No

**Comment by Malfrador** [comment]
Geyser has Bossbar-Support, so it should work here too. 
It does not support colors (and my plugins update-logic does not work with it), but atleast its a bossbar.

**Comment by RednedEpic** [comment]
Tim’s PR has support for bossbars.

**Comment by Tim203** [comment]
But without support for colors, as described above.

**Comment by Malfrador** [comment]
> But without support for colors, as described above.

Colors do work fine with your PR.
![ApplicationFrameHost_2019-10-04_21-14-40](https://user-images.githubusercontent.com/6106558/66233585-09a52900-e6ec-11e9-8b8e-99ec501c180b.png)

Some flickering/double bossbars when updating, but other than its working great.

**Comment by Tim203** [comment]
I mean colors as is bar colors, and I will look into flikker and duplicates
