### ISSUE TITLE
i can't connect to my geyser server

### ISSUE THREAD

**Issue by POTJATHEGOD** [GeyserMC/Geyser#2201]
### Describe the bug

everytime i want join my geyser server it says loginsecurity your username contains ilegal characters
and the console of the server says  reason CLOSED_BY_REMOTE_PEER

### To Reproduce

i dont know what the problem is

### Expected behaviour

i expected to happend that everything would work.

### Screenshots / Videos

![2021-05-08 09_43_00-](https://user-images.githubusercontent.com/83860262/117531788-a7598c00-afe4-11eb-8674-6f654f931edc.png)

### Server Version and Plugins

the server is running 1.16.5 and here is list of what plugins are installed on the server
![2021-05-08 10_05_43-](https://user-images.githubusercontent.com/83860262/117531865-00292480-afe5-11eb-9948-14c29334efd7.png)

### Geyser Dump

https://dump.geysermc.org/gbIK07rfR5Dt0IUUKZuFKz8bGaCBLwSo

### Geyser Version

version 1.2.1-SNAPSHOT (git-master-ce000a4)

### Minecraft: Bedrock Edition Version

1.16.231

### Additional Context

i also made the server cracked for java is this a problem

**Comment by toinouH** [comment]
First, we don't like to support piracy so your server should be in online-mode and as you have floodgate it adds a prefix (a start `*` to your bedrock players and it seems that LoginSecurity counts it as an illegal character. If your server is in online-mode you don't need LoginSecurity and you can allow account-linking in the floodgate config if some players want to use their java account on Bedrock.
I think you can close this issue.
