### ISSUE TITLE
[BUG] Zombies and spiders are totally invisible while creepers and skeletons aren't

### ISSUE THREAD

**Issue by CriticalRange** [GeyserMC/Geyser#2204]
### Describe the bug

Zombies and spiders can't be seen by bedrock players at all.

### To Reproduce

1.Join the server
2.Summon Zombie
3. Can't see the Zombie (same applies to spiders, but skeletons and creeper are appearing)

### Expected behaviour

I was expecting to be able to see Zombies, spiders and maybe other mobs that can't be seen.

### Screenshots / Videos

https://imgur.com/qCTosXn

### Server Version and Plugins

[22:10:38 INFO]: Checking version, please wait...
[22:10:39 INFO]: This server is running Paper version git-Paper-651 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 7 version(s) behind

### Geyser Dump

https://dump.geysermc.org/csFPS3LpPUnt7Nqt7z9nyeO1ROm46ZFg

### Geyser Version

Geyser 1.2.1-SNAPSHOT (git-master-0691bb6)

### Minecraft: Bedrock Edition Version

Bedrock: 1.16.220

### Additional Context

I want this to be fixed, thank you for working on this project.

**Comment by Camotoy** [comment]
I can't confirm this - loaded into a survival world with Paper 651 and Geyser 696 and saw a naturally generated spider right away during nighttime.

**Comment by CriticalRange** [comment]
Idk, i tried spigot aswell, it does the same

**Comment by Kamilkampfwagen-II** [comment]
I can confirm, also pillagers are not visible. You can hear and get attacked by them but you cannot interact. Punching also doesn't work.
Server is Spigot 1.16.5
Geyser and Floodgate are both latest version
Client is 1.16.201 Bedrock (PC)

**Comment by Jens-Co** [comment]
Are you both spawning mobs with an external mob plugin?

**Comment by Kamilkampfwagen-II** [comment]
Nope, just vanilla minecraft.

**Comment by CriticalRange** [comment]
> Are you both spawning mobs with an external mob plugin?

no, just /give command.

**Comment by CriticalRange** [comment]
Also, i reproduced this on my mobile as well

**Comment by Camotoy** [comment]
Have either of you modified either the Spigot or Paper config settings?

**Comment by CriticalRange** [comment]
> Have either of you modified either the Spigot or Paper config settings?

I thought i might have broke something so
I tried a fresh install of paper and spigot, it still didn't work

**Comment by CriticalRange** [comment]
Also, I use offline mode, maybe that's the problem

**Comment by Jens-Co** [comment]
Hi there,
Are you still encountering this problem ? Thanks :)

**Comment by EfeSorogluu** [comment]
> Merhaba, hala bu sorunla karşılaşıyor musunuz? Teşekkürler :)

yes

**Comment by RednedEpic** [comment]
Stale. Please open a new issue with updated replication steps if this is still occurring.
