### ISSUE TITLE
[Bug} Plugin: AdvancedReplays - replays do not work correctly

### ISSUE THREAD

**Issue by Bonnie20402** [GeyserMC/Geyser#2207]
### Describe the bug

Bedrock clients can't watch replays with the plugin advanced replays. They can't see anything. (https://www.spigotmc.org/resources/advancedreplay-1-8-1-16.52849/)

### To Reproduce

1. Download ProtocolLib
2. Download Advanced replays
3. Go to server and start recording
4. Do something for a few seconds
5. Stop recording
6. Do /replay play (replayname)

### Expected behaviour

Bedrock clients should see the replay playing

### Server Version and Plugins

This server is running Paper version git-Paper-651 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

AdvancedReplay*, Essentials, FastAsyncWorldEdit (WorldEdit), floodgate-bukkit, Geyser-Spigot, HolographicDisplays, OldCombatMechanics, PermissionsEx*, ProtocolLib, Sk-Perm*, SkBee, Skript, skript-reflect, skript-yaml, TuSKe*, Vault, Vixio*, WorldGuard

### Geyser Dump

https://dump.geysermc.org/1iCpGUCwZRdlP9aFR3f6GRVXBSsfHoS5

### Geyser Version

1.2.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.16.220

**Comment by RednedEpic** [comment]
Unsure what could be causing this but given this issue is stale, am going to close for now. Please open a new issue w/ updated replication steps if this still occurs.
