### ISSUE TITLE
Custom Inventory not showing up if teleported

### ISSUE THREAD

**Issue by ChiAkuma** [GeyserMC/Geyser#2210]
### Describe the bug

I have an Inventory that should be opened every time. It does open but if i teleport then the inventory does not open anymore until i change worlds.

### To Reproduce

CloudNet installation
with Velocity as Proxy
and geyser velocity
floodgate velocity and on every paper server
a paper server
with plugin BentoBox (bskyblock)
the testet command /is
teleportation 300 blocks with advancedportals

hope you can reproduce it. I surely can do. it is every time

### Expected behaviour

Opens inventory every time

### Screenshots / Videos

There is no screenshot that shows nothing xD

### Server Version and Plugins

Paper 1.16.5 latest
Velocity proxy
geyser latest downloadable (but says 7 versions behind whatever that is)
floodgate newest
advancedportals latest
bentobox latest

as of today 14.05.2021

### Geyser Dump

https://dump.geysermc.org/75fKGPyXzZbpWXo8RrMvAsZ7Hr87YwMj

### Geyser Version

1.2.1-Snapshot git master ce000a4

### Minecraft: Bedrock Edition Version

idk newest

**Comment by ChiAkuma** [comment]
Ok i had isolated the issue:

With AdvancedPortals i can make it so if a player is through a portal he executes a command.
And if i then are with bedrock it executes the command for the player, but nothing is shown and then if i try using that exact command it doesnt work anymore and dont wanna show up

**Comment by RednedEpic** [comment]
Bedrock limitation. Closing.
