### ISSUE TITLE
Errors while using with mcMMO

### ISSUE THREAD

**Issue by TehPigYT** [GeyserMC/Geyser#2214]
### Describe the bug

So recently I started getting some weird errors in console and I had no idea where they were coming from.
I tried uninstalling the mcMMO plugin (which showed in the error) and its folder to see if that would have fixed the issue. Sadly, it seemed like there was an issue with Geyser itself. I do not understand this happens though. It was fine a few days ago but after I updated to the latest Geyser version my issue did not get resolved. This is my error logs.

https://paste.gg/p/anonymous/44f1b63ee7d549a39b0c186a410bcfe6/revisions

Thank you

### To Reproduce

1. Go on a server that has both Geyser and mcMMO installed
2. Try to cut some wood, or mine to upgrade your skills
3. Tons of errors will appear on console

### Expected behaviour

No errors in console at all

### Screenshots / Videos

No screenshots/videos

### Server Version and Plugins

Server Version

[11:29:26 INFO]: Checking version, please wait...
[11:29:26 INFO]: This server is running Paper version git-Paper-682 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 1 version(s) behind
Previous version: git-Paper-681 (MC: 1.16.5)

Everything else is in the dump provided.

### Geyser Version

 https://dump.geysermc.org/qWM4xeKrvc8bbB8CTLCxQqDxp6covzwY

### Minecraft: Bedrock Edition Version

1.16.221

**Comment by Camotoy** [comment]
This is actually likely a result of a Paper change that causes McMMO to spam out. I will leave this open as I am unsure if Geyser should also be complaining, and if we can do anything about it.

**Comment by Camotoy** [comment]
@TehPigYT looks like the paste expired. Could you please reupload it?

**Comment by TehPigYT** [comment]
I hope this is good enough :D
https://paste.gg/p/anonymous/468974f989a34becaf53733f0609f572

**Comment by TehPigYT** [comment]
Basically I was getting this error because of Geyser, not mcMMO itself.
It only happens for bedrock users.

**Comment by Camotoy** [comment]
Thanks for the upload - your previous stacktrace specifically included one that mentioned Geyser in it. This one does not. Could you find that and re-upload it? (I don't think that stacktrace is specifically a Geyser error because I've heard of someone else who doesn't use Geyser get it)

**Comment by TehPigYT** [comment]
Give me a minute, I will join from bedrock and send you the logs again.
As I mentioned, those errors only show because of bedrock users' actions.

**Comment by TehPigYT** [comment]
So after playing on the server using bedrock for a minute, this is what I got in console, there are probably more logs, but the console erased them due to being too many. 

I am sure that the issue is 100% using Java 16 instead of Java 11 but it's good to inform anyways :)
Here is the new paste
https://paste.gg/p/anonymous/86afa82db385471d8052a33c17b10941

**Comment by TehPigYT** [comment]
Seems like Im getting the same issue using Java 11

**Comment by AgileGhost** [comment]
I'm using Java openJDK 11.0.9.1 and I'm getting the same problem. Had no problems with previous versions of Geyser. It was nice enough to make my log file about 2.46GB XD

**Comment by jakey1995abc** [comment]
I'm having the same issue but with my server's name being referenced without MCMMO being referenced (although I do have MCMMO installed)
https://paste.gg/p/anonymous/f29bc3bd6e2b4159a0548a1eff456aa5

**Comment by Camotoy** [comment]
Paper reverted the change on their end - update Paper and see if your problem is resolved. Because of that, I'm closing this issue. Thanks for reporting!
