### ISSUE TITLE
next line (\n) for action bars, scoreboards & bossbars implementation

### ISSUE THREAD

**Issue by GoldenMyst** [GeyserMC/Geyser#2216]
### What feature do you want to see added?

I would like to see “\n (next line)” working for actionbars, bossbars & scoreboards like they do in bedrock.

### Are there any alternatives?

none

**Comment by RednedEpic** [comment]
Hypothetically this should already be supported as this is handled on the Bedrock client when a newline character is present. However as Java does not support this natively, it’s not something we’re all too interested in supporting so I’m going to close this. Thanks for the suggestion though!
