### ISSUE TITLE
support for newer versions

### ISSUE THREAD

**Issue by killme990** [GeyserMC/Geyser#2217]
### What feature do you want to see added?

add support to 1.16.221 and beta versions

### Are there any alternatives?

 a

**Comment by MrZomka** [comment]
1.16.221 is supported. Beta isn't planned to be supported.

**Comment by Camotoy** [comment]
Correct, 1.16.221 is supported. We will not actively be adding beta support - the work to support each version is far more troublesome than we should bother. Thanks for making a feature request anyway!
