### ISSUE TITLE
Bedrock players can't interact with GriefPrevention claim despite being trusted

### ISSUE THREAD

**Issue by Stonewall0210** [GeyserMC/Geyser#2218]
### Describe the bug

On my server using [GriefPrevention](https://dev.bukkit.org/projects/grief-prevention), an issue arises where despite being trusted on a claim, bedrock players cannot interact with the claim (except when they have `*` as a permissions wildcard)

### To Reproduce

1. Create a claim on Java
2. Attempting to interact with the claim on Bedrock will display that you do not have the correct permissions
3. Trust bedrock player
4. Bedrock player still cannot interact with the claim

### Expected behaviour

Bedrock player should be able to interact with the claim, building with `/trust`, opening containers with `/containertrust`, or accessing doors with `/accesstrust`

### Screenshots / Videos

**JAVA**
*Before trusting*
![Before](https://cdn.discordapp.com/attachments/839983231984992266/845509366839771146/unknown.png)
*After trusting*
![After](https://cdn.discordapp.com/attachments/839983231984992266/845511208189689917/unknown.png)
**BEDROCK**
*Before/After trusting*
![Bedrock](https://cdn.discordapp.com/attachments/839983231984992266/845512202651435008/image0.jpg)
(Error messages in image appear both before and after trusting the account in question)

### Server Version and Plugins

Geyser is installed on Bungee (waterfall): ![Bungee version](https://cdn.discordapp.com/attachments/839983231984992266/845516222060691456/unknown.png)
Backend Servers: ![Backend](https://cdn.discordapp.com/attachments/839983231984992266/845516695183687680/unknown.png)

### Geyser Dump

https://dump.geysermc.org/VhKqNdGaIRNSlKRzI2DwHw5TNwRl0UUI

### Geyser Version

`This server is running Geyser version 1.3.0-SNAPSHOT (git-floodgate-2.0-5c76bd8) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220)`

### Minecraft: Bedrock Edition Version

1.16.221

### Additional Context

This happens on 2 backend servers, and I run floodgate 2.0
Hopefully this is enough information, if I missed anything or you need more info, tell me

**Comment by BlAnKcOd3** [comment]
You can just change the floodgate prefix to something that GriefPrevention accepts.

**Comment by Stonewall0210** [comment]
> You can just change the floodgate prefix to something that GriefPrevention accepts.

Could you give an example?

**Comment by Stonewall0210** [comment]
I actually don't think that that would be the problem, because it works just fine with a bedrock account that has a permission node of `*`

**Comment by Camotoy** [comment]
I would ask that you remove Floodgate's name prefix temporarily and see if the issue persists. If it no longer persists, then this issue is definitely on GriefPrevention's end and not ours.

**Comment by Stonewall0210** [comment]
> I would ask that you remove Floodgate's name prefix temporarily and see if the issue persists. If it no longer persists, then this issue is definitely on GriefPrevention's end and not ours.

I will try that the next chance I get

**Comment by Kooldude183** [comment]
It's the '.' prefix with Floodgate 2.0. We had the same problem on my server, so we just changed the prefix to '-'.

**Comment by Stonewall0210** [comment]
> It's the '.' prefix with Floodgate 2.0. We had the same problem on my server, so we just changed the prefix to '-'.

Ok, I was gonna update to use velocity instead of bungeecord anyway so I’ll change the prefix.

closing issue

**Comment by GOBO1912** [comment]
I have same issue but am on bungeecord
