### ISSUE TITLE
Can't move the items in inventory when itemstacks in SET_SLOT were edited with ProtocolLib

### ISSUE THREAD

**Issue by Rothes** [GeyserMC/Geyser#2219]
### Describe the bug

I got a plugin depends on ProtocolLib and it listens packet PacketType.Play.Server.SET_SLOT.
It edits the DisplayName and Lore of the ItemStack sends to the clients. Bedrock clients can't move the items edited to other slots.

### To Reproduce

1. Make a plugin listens on PacketType.Play.Server.SET_SLOT and edit the itemstack in it.
2. Let a Bedrock client click on a ItemStack edited and click on the other slots.
3. the ItemStack is not put in the slot.

### Expected behaviour

Move the ItemStack normally.

### Screenshots / Videos

[https://drive.google.com/file/d/1OHAG3lgjCAlR-dnRAGg9_hPmbBaOfi1N/view?usp=sharing](url)

### Server Version and Plugins

This server is running Tuinity version git-Tuinity-"44e8e5d" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Plugins (11): CMI, CMILib, CMIPaperLib, CoreProtect, Geyser-Spigot, PlaceholderAPI, PlugMan, ProtocolLib, ProtocolStringReplacer, Slimefun, ViaVersion

### Geyser Version

1.2.1-SNAPSHOT (git-master-74a688b)

### Minecraft: Bedrock Edition Version

1.16.221

### Additional Context

Tested on other servers and got the same result.

**Comment by Camotoy** [comment]
What Bedrock platform are you running? Additionally, if relevant, what control scheme are you using?

**Comment by Konicai** [comment]
Just for reference, the issue I was experiencing was that I could move items with edited ItemMeta using ProtocolLib by dragging them, however shift clicking did not work. [this](https://dump.geysermc.org/aVrmFaptXYqzSI1fu2qhXHXXh068PBNb) was my dump. [this](https://github.com/ProjectG-Plugins/GeyserEnchantDescriptions/blob/main/src/main/java/me/konicai/geyserenchantdescriptions/listeners/OutgoingInventoryItem.java) class handled the packets and [this](https://github.com/ProjectG-Plugins/GeyserEnchantDescriptions/blob/main/src/main/java/me/konicai/geyserenchantdescriptions/listeners/enchantments/SweepingEdge.java) class extends it and modifies the ItemMeta of the ItemStack. 

I also listens on PacketType.Play.Server.WINDOW_ITEMS

**Comment by Rothes** [comment]
> What Bedrock platform are you running? Additionally, if relevant, what control scheme are you using?

Tested on Android, and the UI Profile is Classic. This issue is related to it SET_SLOT but I also listen on WINDOW_ITEMS, like Konicai above.
I just write the ItemStack in ItemModifier, here is the code:
`public PacketAdapter packetAdapter = new PacketAdapter(ProtocolStringReplacer.getInstance(), ListenerPriority.LOW, PacketType.Play.Server.SET_SLOT) {
        public void onPacketSending(PacketEvent packetEvent) {
            PacketContainer packet = packetEvent.getPacket();
            StructureModifier<ItemStack> itemStackStructureModifier = packet.getItemModifier();
            for(int i = 0; i < itemStackStructureModifier.size(); i++) {
                ItemStack itemStack = itemStackStructureModifier.read(i);
                if (itemStack != null) {
                    if (!itemStack.hasItemMeta()) continue;
                    ItemMeta itemMeta = itemStack.getItemMeta();
                    itemMeta.setDisplayName("Name");

                    if (itemMeta.hasLore()) {
                        List<String> lore = itemMeta.getLore();

                        for (int i1 = 0; i1 < lore.size(); i1++) {
                            lore.set(i1, "Lore");

                            itemMeta.setLore(lore);
                        }
                    }
                    itemStack.setItemMeta(itemMeta);

                    itemStackStructureModifier.write(i, itemStack);
                }
            }
        }
    };`

**Comment by Konicai** [comment]
Just a heads up its not necessary to have `itemStackStructureModifier.write(i, itemStack);` at the end

**Comment by Rothes** [comment]
> Just a heads up its not necessary to have `itemStackStructureModifier.write(i, itemStack);` at the end

Once I deepClone the packet. This code is cleaned now, Thanks😙

**Comment by Rothes** [comment]
I tested on Windows 10 Edition just now. As Konicai said, Windows 10 clients can move the item but can't use Shift + Click. However, Android Edition even can't move the item.

**Comment by Camotoy** [comment]
So this *might* have to wait until 1.17, where the network communication for item stacks is going to change a bit. 
- Clicking items normally (I.E. left-clicking) sends the item being picked up in the packet
- Bedrock doesn't always shift-click to the same spot Java would, so we have to send two normal left-click packets in a row
- The server freaks out about the not-equal item being moved and cancels the second left-click packet, and that's the source of our issue.

**Comment by Konicai** [comment]
Has 1.17 gotten the necessary changes that might make this possible?

**Comment by RednedEpic** [comment]
No response in over a year. Likely fixed - closing.
