### ISSUE TITLE
Players become sideways when they respawn as seen by bedrock players.

### ISSUE THREAD

**Issue by SpecifiedNull** [GeyserMC/Geyser#2221]
### Describe the bug

Bedrock/PocketEdition players can play normal and see everything but when they kill a player and that player respawns, they will be shown sideways to bedrock players. this issue does not happen if bedrock player kills bedrock player. only they see java players sideways when java player respawns.
This causes them to not be able to attack the players that are sideways.

### To Reproduce

1. Login with Bedrock account
2. Kill a player that is on Java 
3. they become sideways

### Expected behaviour

They are not supposed to become side ways

### Screenshots / Videos

[https://cdn.discordapp.com/attachments/613168464634576897/846039698840748052/unknown.png](https://cdn.discordapp.com/attachments/613168464634576897/846039698840748052/unknown.png)

### Server Version and Plugins

 Paper version git-Paper-675 (MC: 1.16.5)

### Geyser Dump

https://dump.geysermc.org/ihJAxNOhFipZGbpxuQvHS6U1ptlzN2qN

### Geyser Version

1.3.0-SNAPSHOT (git-floodgate-2.0-085c122)

**Comment by RednedEpic** [comment]
Likely same cause as https://github.com/GeyserMC/Geyser/issues/980. Closing.
