### ISSUE TITLE
Bedrock Users Cannot Move Most Items With More Than 3 Enchants Into Tile Entities (Chests, Smithingtables, Ect.)

### ISSUE THREAD

**Issue by Gizmo-Gadget** [GeyserMC/Geyser#2222]
### Describe the bug

When a player using bedrock tries to put items, such as armor or tools, with more than one enchant into any tile entity or anything you can put things in, it does not work. When they click to place it, it doesn't go into the chest.

### To Reproduce

1. Make a chestplate with more that 3 enchants.
2. Try to put it into a chest or smithing table.

### Expected behaviour

User Is Supposed To Be Able To Put It Back Into The Chest, But Has To Resort To Using A Hopper For Chests, And Asking A Friend For The Smithing Table.

### Screenshots / Videos

https://user-images.githubusercontent.com/78033079/119278445-51473400-bbf3-11eb-980b-d0494cf070e1.mp4

Sorry about the quality, friend sent it over text.

### Server Version and Plugins

We run an anticheat plugin, but have exempt it for bedrock players.

### Geyser Version

Were using floodgate 2.0 along with its corresponding gyser version.

### Minecraft: Bedrock Edition Version

Newest

**Comment by Camotoy** [comment]
Please attach a Geyser dump.

**Comment by Gizmo-Gadget** [comment]
Sorry about that, here it is: https://dump.geysermc.org/Sbm8C5mwv0oEX1kZNHQMp4HyLpjFO2Ho

**Comment by Camotoy** [comment]
This is likely the same issue as #2219, #2145 and #2034.

**Comment by Gizmo-Gadget** [comment]
Okay, thank you for responding so quickly and helping! Does this issue need to be closed?

**Comment by Camotoy** [comment]
For now, since they are caused differently, I'll leave it open.

**Comment by RednedEpic** [comment]
Stale. Above issues that are likely related are all closed now so will close this one since I've not seen anything relating to this. Please open a new issue if this bug still occurs w/ updated replication steps.
