### ISSUE TITLE
Scoreboard order with Geyser on Bungeecord

### ISSUE THREAD

**Issue by TheCalypso** [GeyserMC/Geyser#2223]
### Describe the bug

Hello,
I am currently using GeyserMC on my proxy which is working fine. Scoreboards that are sent / managed from the proxy have no problem with the bedrock Edition client. However, as soon as a player joins a server where the scoreboard is managed by "bukkit", the client receives it with "0" everywhere.

I specify that I do not use Geyser on my Spigot servers.

### To Reproduce

1. Put GeyserMC on bungeecord
2. Send scoreboard with BungeeCordAPI
3. Send scoreboard with BukkitAPI

### Expected behaviour

I don't know if I should install GeyserMC on my spigot servers or is it possible to adjust this from the GeyserMC of the Proxy.

### Screenshots / Videos

This is the scoreboard managed by proxy :
![image](https://user-images.githubusercontent.com/33781244/119360494-f53fe680-bcaa-11eb-8886-a0b1659a511b.png)

This is the scoreboard managed by spigot/bukkit : 
![image](https://user-images.githubusercontent.com/33781244/119360861-59fb4100-bcab-11eb-9ecd-28435f7318f8.png)

In the first part of the scoreboard, the numbers from 9 to 1 are taken from an old scoreboard. The "real" scoreboard corresponds to the line with the 0's.

### Server Version and Plugins

This server is running Waterfall version git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:8dfe4d2:412 by md_5

Paper / Spigot : This server is running Paper version git-Paper-629 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Geyser Version

Geyser-BungeeCord | n°build : 700 

### Minecraft: Bedrock Edition Version

1.16.221

**Comment by Jens-Co** [comment]
Hi there, are you still having this issue ? Also encounter this problem especially when I added empty string to space things out, fixed it by adding a few symbols into empty strings.

**Comment by TheCalypso** [comment]
Hello, I still have the problem. I did not find a way to solve my problem unfortunately :(

**Comment by Konicai** [comment]
Can you provide a geyser dump (run the command `geyser dump`), and the name and version of the spigot scoreboard plugin you're using

**Comment by TheCalypso** [comment]
Hello, the plugin we are using for the scoreboard on the Spigot server is a plugin that was made by us. As for the dump here it is: https://dump.geysermc.org/wz2R2yJgdJtb91OcnGZmsG8R0Da1HtKt

**Comment by Konicai** [comment]
Have you tried other spigot scoreboard plugins in an attempt to reproduce this? Issues with unavailable or paid plugins here are usually low priority due to their inaccessibility

**Comment by Jens-Co** [comment]
You are still using floodgate 1 and geyser 1.2.1 I recommend to update geyser and floodgate to!

**Comment by TheCalypso** [comment]
We think that the concern arises from the way the packets transit because when BungeCord manages the scoreboard we have no problem but only as soon as the packets are managed by Spigot the lines are in any direction.

**Comment by TheCalypso** [comment]
I can send you the part that allows us to send the packets to the players if you wish. I would like to point out that the way we operate is the same as the other open access plugins.

**Comment by TheCalypso** [comment]
This is the code we have on the side of our BungeeCord plugin : 
![image](https://user-images.githubusercontent.com/33781244/128054357-97e04a58-1840-4119-a89e-b29ca17a2659.png)

**Comment by TheCalypso** [comment]
This is the code we have on the side of our Spigot plugin :
![image](https://user-images.githubusercontent.com/33781244/128054644-77947791-b785-49b5-9a74-4430c81acc94.png)

**Comment by marcbal** [comment]
I have the same bug with the scoreboard. I made a test plugin that change the content of the sidebar progressively so we can see the bug.
Here is a video that illustrate the bug (left is Bedrock, right is Java) : https://youtu.be/buFCqAr7I1U
As you can see, when the content of a line is updated (that is, in the point of view of the scoreboard, a deletion of the old line and an addition of the new line with the appropriate score), the line has a score of 0 in the Bedrock client, but has the good score in the Java client.

I use standalone Geyser with BungeeCord behind, and Paper server.

**Paper version** git-Paper-121 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b854e7e)
Previous version: git-Paper-778 (MC: 1.16.5)

**BungeeCord version** git:BungeeCord-Bootstrap:1.17-R0.1-SNAPSHOT:bda1605:1598 by md_5

**Geyser version** This server is running Geyser version 1.4.1-SNAPSHOT (git-master-36ad561) (Java: 1.17.1, Bedrock: 1.17.0/1.17.1/1.17.2 - 1.17.10/1.17.11)

**Java client version** 1.17.1
**Bedrock client version** 1.17.11 on Windows 10

**Test plugin** https://gist.github.com/marcbal/cadd9918ecce659d1f5b5fa82b6f3fb8

**Comment by onebeastchris** [comment]
Is this still an issue?
