### ISSUE TITLE
Villagers take the incorrect amount of items from players.

### ISSUE THREAD

**Issue by kareem-ghazi** [GeyserMC/Geyser#2224]
### Describe the bug

Villagers take the incorrect amount of items from players when doing a trade. Apparently, it has only happened in fletchers. The player who experienced the issue was able to reproduce it again and also relogged but it didn't go away.

### To Reproduce

1. Place down a villager.
2. Change its profession to a fletcher.
3. Trade with it a stack of sticks.
4. Villager takes more sticks for the trade.

### Expected behaviour

Players trade the correct amount of sticks for the correct amount of emeralds.

### Screenshots / Videos

https://ufile.io/f/lj87x

### Server Version and Plugins

[Tue, 25. May 2021 11:47:22 UTC INFO] This server is running Paper version git-Paper-706 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
---------------------------------------------------------------------------------------------------------------------------------------
[Tue, 25. May 2021 11:48:53 UTC INFO] Plugins (22): AureliumSkills, BetterSleeping3, ChatReaction, ChestSort, CoreProtect, DiscordSRV, EntityDetection, Essentials, EssentialsChat, EssentialsSpawn, floodgate-bukkit, Geyser-Spigot, GriefPrevention, InvSeePlusPlus, LuckPerms, Quests, SAML, TradeShop, Vault, WorldBorder, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/DAHzgIsEOBTr7yNy6i0UD6jUzh3MP3nC

### Geyser Version

1.2.1-SNAPSHOT (git-master-4734ce2)

### Minecraft: Bedrock Edition Version

1.16.221

**Comment by Camotoy** [comment]
Is there a reason this was closed?

**Comment by Kimosauraus** [comment]
Addressed the issue on discord, name is "Danku". Thought to close the issue for now considering I received support.

**Comment by Camotoy** [comment]
As the bug is still present, I will reopen this. Thanks though!

**Comment by Kimosauraus** [comment]
No problem :).

**Comment by onebeastchris** [comment]
Could you try updating to the latest version of Geyser, and see if the issue persists?
If it does, send a new Geyser dump by running "geyser dump" in your server console.

**Comment by onebeastchris** [comment]
Closing due to no response.
