### ISSUE TITLE
Endermen mechanics are bugged/glitched.

### ISSUE THREAD

**Issue by kareem-ghazi** [GeyserMC/Geyser#2225]
### Describe the bug

Endermen are able to hit people through walls and also get aggravated without even looking at them. This issue happens mostly in the end (being there a lot of endermen). Sometimes, players also don't aggravate endermen by looking at them. Feels like the crosshair in bedrock is different but that's just a guess.

### To Reproduce

1. Go to the end (mostly where the issue occur)
2. Try walking around or looking at endermen.

Sorry for the vague steps as the issue happens at random times and occurs differently.

### Expected behaviour

Endermen shouldn't get aggravated unless looked at directly and shouldn't be able to hit players through walls.

### Screenshots / Videos

https://youtu.be/Rf1L9v2kumY
https://youtu.be/qvvuzAFsTs0

### Server Version and Plugins

[Tue, 25. May 2021 17:05:37 UTC INFO] This server is running Paper version git-Paper-706 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

[Tue, 25. May 2021 17:05:52 UTC INFO] Plugins (22): AureliumSkills, BetterSleeping3, ChatReaction, ChestSort, CoreProtect, DiscordSRV, EntityDetection, Essentials, EssentialsChat, EssentialsSpawn, floodgate-bukkit, Geyser-Spigot, GriefPrevention, InvSeePlusPlus, LuckPerms, Quests, SAML, TradeShop, Vault, WorldBorder, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/aQIfCh135KFJNvUt1TbwQj3Pjwk4hfRl

### Geyser Version

1.2.1-SNAPSHOT (git-master-4734ce2)

### Minecraft: Bedrock Edition Version

1.16.221

**Comment by Camotoy** [comment]
> Endermen are able to hit people through walls

This does not sound like a Geyser issue. If Java players are also being affected, this is 100% not an us issue.

**Comment by Kimosauraus** [comment]
I will check if any java players experience the wall hit issue. What about the endermen aggravating issue that's shown in the second clip?

**Comment by Camotoy** [comment]
Also unlikely to be us - the server would calculate that based on the player's rotation. If the player's rotation looks correct when viewed from a Java player, that's what the server should process against. Again, it *could* be us but I don't see how - we don't touch server behavior.

**Comment by RednedEpic** [comment]
Since we don't touch server behavior, this is likely not us. Closing since there has been no further reports of this aside from this one issue.
