### ISSUE TITLE
Cannot reply to EncryptionPacket without profile with access token

### ISSUE THREAD

**Issue by Yusaki-Akito** [GeyserMC/Geyser#2227]
### Describe the bug

Server Side Error:

![](https://media.discordapp.net/attachments/696709438580719706/847069090069086248/image0.jpg)

### Detail
Version: git-Paper-733 (MC 1.16.5) (Implementing API Version 1.16.5-RO. I-SNAPSHOT)

GeyserMC Error:

![](https://media.discordapp.net/attachments/696709438580719706/847070080160104458/image0.png)

### Detail
Version: Latest

### To Reproduce

1. Start geyser and config
2. Connect to the server by mcpe

### Expected behaviour

Just want to play my own server by cross platform with my friends follow this ip: `play.snowboltz.net`

### Geyser Version

wget https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/standalone/target/Geyser.jar From this url

### Minecraft: Bedrock Edition Version

1.16.221

**Comment by Camotoy** [comment]
You are very likely trying to connect to an online mode server with Geyser in offline mode. Please connect to the server with a Java account. If this is not the case, please let us know. Thank you!

**Comment by Yusaki-Akito** [comment]
> You are very likely trying to connect to an online mode server with Geyser in offline mode. Please connect to the server with a Java account. If this is not the case, please let us know. Thank you!

But I was on offline mode

**Comment by Camotoy** [comment]
Yes, but the server isn't.

**Comment by Yusaki-Akito** [comment]
I mean for both them in offline mode

**Comment by Camotoy** [comment]
In your case, that server already has Geyser installed. Unless you're running that Bedrock server on the same IP, you don't need to setup a standalone Geyser instance.
