### ISSUE TITLE
Item frames are not visible

### ISSUE THREAD

**Issue by JuniorJPDJ** [GeyserMC/Geyser#223]
**Describe the bug**
Placed item frames are not visible

**To Reproduce**
1. Look at place, where ltem frame IS on java edition
2. No item frame on bedrock

**Expected behavior**
I'd like to see item frame

**Screenshots**

**Server version**
This server is running Paper version git-Paper-137 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser version**
1bcee8d (latest inventory branch commit at the moment)

**Bedrock version**
1.14.1.5 android arm

**Comment by Loganh4005** [comment]
It is due to in java item frames are an entity and on bedrock, they are a block, It would cause some conflict between blocks due to you can place an item frame and a non-full-block
