### ISSUE TITLE
CosmicGuard/TCPShield

### ISSUE THREAD

**Issue by SladeHazard** [GeyserMC/Geyser#2230]
### Describe the bug

Is there a way to support cosmicguard/tcpshield ? Players can't join because cosmicguard/tcpshield don't let people connect to the remote IP. 

### To Reproduce

Joining the server on bedrock

### Expected behaviour

Player actually join the server

### Server Version and Plugins

Velocity as the proxy
Spigot servers 1.12.2

### Geyser Version

"latest"

### Additional Context

I couldn't find any wikis for this.

**Comment by Camotoy** [comment]
TCPShield has support for Geyser players on their paid plan - contact them. I'm unsure about CosmicGuard support but if it's anything like TCPShield you will need to contact them.
Closing as there's unlikely anything we can do on our end to fix. Thank you anyway!
