### ISSUE TITLE
Cannot reply to EncryptionRequestPacket without profile and access token.

### ISSUE THREAD

**Issue by I3ladeDragon** [GeyserMC/Geyser#2232]
### Describe the bug

When connecting to my Bungeecord server from Bedrock, it will connect... but as the world is trying to load in, I get this error:

java.lang.IllegalStateException: Cannot reply to EncryptionRequestPacket without profile and access token.

### To Reproduce

1. I upgraded from Floodgate 1.0 to Floodgate 2.0, with the appropriate Geyser version to support it. 

2. I put the plugins into the Bungeecord instance.

3. I copied the key.pem file over and modified the Geyser config to point to it.

4. Tried to connect with Bedrock edition and get the EncryptionRequestPacket error.

### Expected behaviour

Bedrock players should be able to connect to the network.

### Server Version and Plugins

This server is running CraftBukkit version 3034-Spigot-1ad8354-0791e54 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Plugins (14): LuckPerms, WorldEdit, MiniaturePets, DeluxeHub, OpenInv, TeamChat, VoxelSniper, ProtocolLib, CoreProtect, PacketLimiter, LiteBans, PremiumVanish, DiscordSRV, BungeeTabListPlus

### Geyser Dump

https://dump.geysermc.org/EwhtOx423bCdDFSyYfO2pn3RttHvgGpj

### Geyser Version

1.3.0-SNAPSHOT (git-floodgate-2.0-934fc12)

### Minecraft: Bedrock Edition Version

1.16.201

### Additional Context

Everything worked normally until I tried upgrading to the latest version of Geyser/Floodgate. It may have been an error on my part... but there wasn't any helpful documentation on this issue and I am a little lost with this upgrade at this point. Figured I would try to get it resolved before I try a fresh install of Geyser/Floodgate.

**Comment by Camotoy** [comment]
That is a new error introduced by the update. I can't say I'm able to replicate your error on BungeeCord.

**Comment by agucova** [comment]
I have this same error after adding Floodgate to a previously Geyser-only server.

**Comment by a6doff** [comment]
Can reproduce with [JPremium](https://www.spigotmc.org/resources/%E2%96%A0-jpremium-%E2%96%A0-authorization-plugin-%E2%96%A0-automatic-login-premium-%E2%96%A0-cracked-sessions-%E2%96%A0-password-recovery-%E2%96%A0.27766/) on the server

**Comment by Camotoy** [comment]
Likely an issue that JPremium needs to resolve.

**Comment by a6doff** [comment]
Nevermind, I fixed that issue just right after putting that here, put `allow-password-authentication` as false, it will work way better.

**Comment by Gaming32** [comment]
I can confirm this bug.
Result of the `/plugins` command over RCON: `Plugins (4): TheStudio-Minecraft, ViaVersion, floodgate, Geyser-Spigot`

**Comment by agucova** [comment]
I ended up isolating the problem to the way nLogin sends packets to do premium user authentication directly, the same mechanism used by FastLogin (which also has the same error).

**Comment by Gaming32** [comment]
The 1.17 issue seems to be caused by missing NMS, and info about that is posted in their Discord:
> We are aware that Floodgate does not currently work on Spigot 1.17. This is due to some changes that were done in regards to NMS, however if you run Floodgate on a proxy such as Velocity, this does not affect you. For the time being we recommend keeping your server on 1.16.5 and running ViaVersion as Spigot is still ironing out some fairly major bugs, but we anticipate to have this fixed shortly :smile:

**Comment by Bartek200219** [comment]
I have the same bug on Bungeecord.

**Comment by Konicai** [comment]
If you come to the Geyser discord and share your logs through https://mclo.gs we can help you

**Comment by Bartek200219** [comment]
> If you come to the Geyser discord and share your logs through https://mclo.gs we can help you

No one helped me, so I'll post logs here https://mclo.gs/M2BJZAu https://mclo.gs/1KXfENf

**Comment by Chew** [comment]
Going to close this somewhat due to inactivity and somewhat because of these factors:
1) This issue has supposedly been fixed per #2498 
2) This error might also be caused by offline mode set in config but online mode set on server. Check these.

If it's not one of these, let's continue the discussion over on our [Discord server](https://discord.gg/geysermc). Get a Geyser Dump ready, just in case.

**Comment by LittleChest** [comment]
I have the same bug on Bungeecord (Waterfall)
