### ISSUE TITLE
Villager Enchantment books Unknown

### ISSUE THREAD

**Issue by lilspojo** [GeyserMC/Geyser#2233]
### Describe the bug

When trading with a librarian, and there is a trade for a enchantment book, at least on mobile, it is impossible to tell what the book is, can’t hover over it to see, as this is mobile, and tapping on it does nothing. This is joining a java server from Geyser standalone.

### To Reproduce

1. Get a librarian on a java server in mobile
2. That’s it, you can attempt to see what the enchantment book is, but you can’t tell, only workaround I’ve found is to label the villagers with signs.

### Expected behaviour

Be able to tell what the enchantment book is when trading with a villager.

### Server Version and Plugins

Server is running on paper spigot 1.16.5, not sure of much else.

### Geyser Version

Latest 1.2.0 snapshot

### Minecraft: Bedrock Edition Version

Latest, don’t know exact version

**Comment by SuryanshxND24** [comment]
If the book is not showing any enchantment that means its the book of `sweeping edge` because bedrock natively doesn't have this enchantment but java has so it doesn't show up to bedrock players through geyser.

**Comment by lilspojo** [comment]
Well that’s the thing, this is for all enchantment books, I checked this same villager on java, it’s sharpness 5.

**Comment by lilspojo** [comment]
Nevermind I’m just dumb, when trading there’s something you tap on under the book that shows the type
