### ISSUE TITLE
scattered savnna's biome's grass looks same as the plain biome's not savanna's in bedrock

### ISSUE THREAD

**Issue by shafiahaz2478** [GeyserMC/Geyser#2234]
### Describe the bug

I play on my survival world and thought to check it out in bedrock through geyser but my spawn biome is scattered savanna which is like huge mountains. my bedrock client spawned in scattered savanna biome and the grass and leaves look like flesh green like how plain biome has.

### To Reproduce

1.search for scattered savanna biome
2.tp both java and bedrock client
then you will notice

you can use this seed to immediate notice 2589100313386943726

### Expected behaviour

the grass colour want to look like how savanna has

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/69790524/119933126-886f6980-bf94-11eb-8f9d-7c7f53a4af5c.png)

### Geyser Version

1.2.1-SNAPSHOT (git-master-4734ce2)

**Comment by RednedEpic** [comment]
Not a bug - this is just how savannah biomes look in Bedrock. You'll also notice that dark oak biomes don't look the same across versions either, this is just due to how they're implemented in each game.

**Comment by Camotoy** [comment]
Specifically, this is (apparently) how mutated savanna biomes look like.
