### ISSUE TITLE
Permissions not registered by LuckPerms

### ISSUE THREAD

**Issue by LucasMucGH** [GeyserMC/Geyser#2239]
### Describe the bug

If you try to see all registered Permissions, using `/lp tree`, you can see that the permissions are not registered by luckperms; after the usage of a command, the associated permission appears. This causes problems, because at one it is more difficult to see and edit all floodgate and geyser permissions, but also everyone can see the floodgate and geyser commands (via tab-complete), even if he doesn't have permission to use them.

### To Reproduce

1. Start the server
2. type `/lp tree`
3. Check the link and you will see that neither geyser nor floodgate permissions are listed
4. Type any geyser or floodgate command
5. Type `/lp tree` again
6. Check the link and you will see that only the permission of the command is now listed

### Expected behavior

All permissions should be registered by luckperms or other permission plugins at startup.

### Server Version and Plugins

The relevant plugin and server info:

```
System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9) Host: Windows 10 10.0 (amd64)
[12:33:31 INFO]: This server is running Paper version git-Paper-741 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[12:33:36 INFO]: [LuckPerms] Loading LuckPerms v5.3.42
[12:33:36 INFO]: [floodgate] Loading floodgate v2.0-SNAPSHOT
[12:33:38 INFO]: [Geyser-Spigot] Loading Geyser-Spigot v1.3.0-SNAPSHOT
```

### Geyser Dump

https://dump.geysermc.org/61Rvmp0aWF1so7WPrVtBGyKG3rHLAmst

### Geyser Version

Geyser-Spigot v1.3.0-SNAPSHOT

### Minecraft: Bedrock Edition Version

_Not related_

### Additional Context

If you need more system and server info please don't hesitate to ask; also it may be helpful to add that everything works fine except the permission registration; no errors or problems whatsoever.

**Comment by Konicai** [comment]
#2246 Has been merged so permissions should show up in the luckperms tree without having to run the commands first. tab-complete still isn't hidden. 

Feel free to open a new issue specifically for tab completes showing for players that dont have permissions, since I don't think there is an issue for that yet.
