### ISSUE TITLE
ViaVersion Support

### ISSUE THREAD

**Issue by ibidd** [GeyserMC/Geyser#2242]
### Describe the bug

Geyser isn't compatible with 1.8 spigot with viaversion.

### To Reproduce

1. Set minecraft java version to 1.8
2. Install geyser and floodgate
3. Install via version
4. Start server
5. Look in console

### Expected behaviour

Whenever you start the server, in the console it states that geyser doesn't work on this version.

### Geyser Version

1.2.1-SNAPSHOT (git-master-08ba82a)

### Additional Context

In prerequisites it states that you can use ViaVersion if your server has an older version.

**Comment by RednedEpic** [comment]
Geyser is only supported on 1.12.2+ with ViaVersion.

**Comment by Camotoy** [comment]
Geyser-Spigot* 

Do feel free to read the message it gives you if you wish to still use 1.8.
