### ISSUE TITLE
Trees in the snow biome turn red

### ISSUE THREAD

**Issue by Grabiie** [GeyserMC/Geyser#2244]
### Describe the bug

When you go to a snow biome the trees turn **red**

### To Reproduce

1. Go to a **snow biome**
2. **Find a tree**

### Expected behaviour

I expected the tree to remain **normal**

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/42703366/120118743-6cbdbc00-c16a-11eb-8c86-bc5da64eb5ef.png)

### Server Version and Plugins

![image](https://user-images.githubusercontent.com/42703366/120118884-1dc45680-c16b-11eb-983e-7d91d5554453.png)

### Geyser Dump

https://dump.geysermc.org/JimE339gp8yANYPbUJpzCCiaUz3KyyIo

### Geyser Version

1.2.1-SNAPSHOT (git-master-d80c31f) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220)

### Minecraft: Bedrock Edition Version

1.16.221

### Additional Context

Thank you for geyser!

**Comment by PutoPug** [comment]
This looks like an issue with mcpe, please look at [https://bugs.mojang.com/browse/MCPE-110815](https://bugs.mojang.com/browse/MCPE-110815)

**Comment by Camotoy** [comment]
If this is indeed a Bedrock bug, then it's not within our scope. If you feel otherwise (for example, it doesn't happen on other servers or singleplayer), do let us know. Thank you!
