### ISSUE TITLE
Making it possible to play with Geyser on a LAN party without Internet access 

### ISSUE THREAD

**Issue by Filipe1236** [GeyserMC/Geyser#2245]
### What feature do you want to see added?

For the bedrock "session" that Geyser standalone creates to connect through bedrock, the online-mode is probably set to true, meaning that it enforces all users to be connected to xbox live, even through the LAN. Unfortunately, this configuration line isn't available on the config.yml file, meaning that I can't access or change it. Is there a way to access other types of configs and find the online-mode config for the bedrock "session" that Geyser uses? Not referring to the java server line about the auth, but the auth system of the bedrock "session" itself. Is there a way to connect to the Java server through bedrock without a proper xuid, only a local username?

Why am I asking this (my issue)?
I am trying to set up a LAN party where I don't have direct access to the Internet and I want to play on both versions with my friends, etc. 
So I have been testing Geyser for a while and I've noticed that the Geyser itself rejects connections from players who are not connected to xbox live and enforces all users to be connected to xbox live, which is impossible to do inside the LAN party (there is not Internet access at all). I am not talking about setting the online-mode of the java to false or setting the auth method to offline on the config.yml, because I've already done that and I still get this issue. 
So my suggestion would be adding a config line to the config.yml file for the authentication method of the bedrock connection to Geyser itself, making the connection to xbox live optional via settings, so it is totally possible to play on the Java server via bedrock through Geyser while being totally offline, via LAN.

### Are there any alternatives?

Aditional note: I've already discussed this on the discord server, but someone suggested me to make an issue on GitHub. I am sorry for bothering you.

**Comment by Camotoy** [comment]
Enable `enable-proxy-connections`.

**Comment by ShifatTheDev** [comment]
not working
