### ISSUE TITLE
Compatibility with ViaVersion's new api

### ISSUE THREAD

**Issue by LaserSlime** [GeyserMC/Geyser#2248]
### What feature do you want to see added?

ViaVersion recoded their api in the dev branch. The dev branch will merge into master once 1.17 gets released. The current Geyser version isn't compatible with the new api and doesn't start at all if ViaVersion is installed. This needs to be fixed.

### Are there any alternatives?

no

**Comment by RednedEpic** [comment]
We will be doing this as part of the 1.17 update.

**Comment by Camotoy** [comment]
If you cannot wait, there is a viaversion4.0.0 branch on the CI.
