### ISSUE TITLE
Trapped Chests Don't Show Up

### ISSUE THREAD

**Issue by Loganh4005** [GeyserMC/Geyser#225]
**Describe the bug**
Trapped Chest Don't Show Up

**To Reproduce**
1. Place a trapped chest
2. Relog
3. Chest Gone

**Expected behavior**
Trapped Chests Show Up

**Server version**
Spigot and Paper 1.15.2

**Geyser version**
Jenkins Inventory

**Bedrock version**
1.14.30

**Comment by TheMasterBlaster** [comment]
I can confirm on the Inventory branch using Standalone, Trapped chests are invisible after relogging.

**Comment by Loganh4005** [comment]
Redned can't you just copy the chest code for block entity to the trapped chest

**Comment by JuniorJPDJ** [comment]
Yes, I also confirm.
Evidence in #280.
