### ISSUE TITLE
Placing a sweet berry bush makes bedrock players start to eat

### ISSUE THREAD

**Issue by LaserSlime** [GeyserMC/Geyser#2250]
### Describe the bug

If a bedrock player places down a sweet berry bush, he starts to eat if he has more sweet berry bushes in that slot.

### To Reproduce

1. Put more than 1 sweet berry in your selected slot.
2. Give yourself some hunger.
3. Place one sweet berry bush.
4. Wait a few seconds and you will automatically eat another sweet berry.

### Expected behaviour

You should be able to place sweet berry bushes without eating them.

### Server Version and Plugins

This server is running Tuinity version git-Tuinity-"3eda860" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/SjOuuabfKeK7lfBLKymhE7ZpKLZsIF7h

### Geyser Version

This server is running Geyser version 1.2.1-SNAPSHOT (git-viaversion4.0.0-50bea0e) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220)

### Minecraft: Bedrock Edition Version

1.16.221

**Comment by Camotoy** [comment]
This sounds like a Bedrock behavior difference we may not be able to do anything about - can you confirm it is not reproducable in singleplayer or another Bedrock server?

**Comment by LaserSlime** [comment]
What do you mean by "another Bedrock server"?

**Comment by Camotoy** [comment]
Does it happen on a server that isn't Geyser.

**Comment by LaserSlime** [comment]
Well on nukkit I can't place them down at all.

**Comment by Camotoy** [comment]
Test with a singleplayer Bedrock world, then.

**Comment by LaserSlime** [comment]
Doesn't happend there.

**Comment by jackson-57** [comment]
This sounds a whole lot like #1782.

**Comment by RednedEpic** [comment]
Same underlying issue as #1782, closing in favor of that one.
