### ISSUE TITLE
Carpet Bots

### ISSUE THREAD

**Issue by Lardbutt200** [GeyserMC/Geyser#2251]
### Describe the bug

When using carpet mod to spawn a bot, you recieve an error "An unexpected error occured trying to execute that command"

### To Reproduce

1. install carpet mod
2. type /player steve spawn
3. recieve message

### Expected behaviour

A server side bot should spawn.

### Server Version and Plugins

1.16.5 Fabric server
Mods: 
carpet-extra-1.16.5-1.4.34.jar 
fabric-api-0.34.0+1.16.jar
fabric-carpet-1.16.5-1.4.35+v210505.jar
floodgate-fabric.jar
Geyser-Fabric-1.3.0-SNAPSHOT.jar 
InvView-1.4.1-1.16.4+.jar
lithium-fabric-mc1.16.5-0.6.4.jar
phosphor-fabric-mc1.16.3-0.7.2+build.12.jar

### Geyser Dump

Https://dump.geysermc.org/1JaStPAl6VZNcfONnBBD4gj68BELN2GV

### Geyser Version

Geyser-Fabric-1.3.0-SNAPSHOT.jar

**Comment by Camotoy** [comment]
Is your Floodgate-Fabric version up-to-date?

**Comment by Lardbutt200** [comment]
I'm pretty sure it is.

**Comment by Camotoy** [comment]
This should be resolved; and if it is not, please re-open an issue. Thanks!

**Comment by flashsugarr** [comment]
Still an issue

**Comment by Camotoy** [comment]
We're aware, and Carpet is aware; there is no need to bump it in multiple threads.
