### ISSUE TITLE
ProtocolSupport error when on BungeeCord backend

### ISSUE THREAD

**Issue by AxlRose-RX** [GeyserMC/Geyser#2253]
### Describe the bug

ERROR13:00:12
[+AxlRose6782|/51.222.93.59:49897]: <-> ServerConnector [bedwars] - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!

On the server:

UUID of player +AxlRose6782 is 00000000-0000-0000-0009-01fc13709f02
[floodgate]: Floodgate player logged in as +AxlRose6782 disconnected
protocolsupport.protocol.utils.authlib.LoginProfile(name: +AxlRose6782, originalName: +AxlRose6782, uuid: 00000000-0000-0000-0009-01fc13709f02, originalUUID: 00000000-0000-0000-0009-01fc13709f02, onlinemode: false) (/51.222.93.59:36663) lost connection:
13:06:33
Disconnecting protocolsupport.protocol.utils.authlib.LoginProfile(name: +AxlRose6782, originalName: +AxlRose6782, uuid: 00000000-0000-0000-0009-01fc13709f02, originalUUID: 00000000-0000-0000-0009-01fc13709f02, onlinemode: false) (/51.222.93.59:36663): Timeout while waiting for login success send

When try to join a server that has via version, via backwards, via rewind and protocol support, can't join it

https://timings.pl3x.net/?id=6a8c092b45484922bf21669387093e18

### To Reproduce

1. Bungee with Floodgate 2.0 and Geyser
2. Server with Floodgate 2.0
3. Server has 3 Via plugins and Protocol support
4. ProtocolSupport is needed for 1.8 players to join, less errors if present, more errors if not present
5. Can't join

### Expected behaviour

Should let people join the server

1.16.5 clients can join
1.8 can join

Geyser players can't

### Server Version and Plugins

This server is running Purpur version git-Purpur-1158 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Purpur-1077 (MC: 1.16.5)

### Geyser Dump

https://dump.geysermc.org/0MkPXGhBSPSZBY93hURWAjnDxtK7wKXH

### Geyser Version

1.3.0-SNAPSHOT (git-floodgate-2.0-e16d83e) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220)

**Comment by RednedEpic** [comment]
You should not have ProtocolSupport installed alongside any of the Via* plugins (aside from ViaVersion if you need it). ViaBackwards/ViaRewind do exactly what ProtocolSupport do, except don't go down quite as many versions. Install either ProtocolSupport or ViaBackwards/ViaRewind.
