### ISSUE TITLE
NullPointer /geyser reload

### ISSUE THREAD

**Issue by TheKlimoT** [GeyserMC/Geyser#2255]
### Describe the bug

https://paste.helpch.at/osopiyecub.css

### To Reproduce

-

### Expected behaviour

-

### Server Version and Plugins

 1.3.0-SNAPSHOT (git-floodgate-2.0-e16d83e) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220)

### Geyser Version

 1.3.0-SNAPSHOT (git-floodgate-2.0-e16d83e) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220)

**Comment by Jens-Co** [comment]
Do a full server restart, Reload break things.
