### ISSUE TITLE
Bedrock Player cant move and they are under the floor

### ISSUE THREAD

**Issue by TheLastCrafters** [GeyserMC/Geyser#2256]
### Describe the bug

When a bedrock player enter in the server they go under the floor and they cant move and the view or the steve(alex, his character)

### To Reproduce

1. play pe minecraft in 1.16.220.20
2. put the ip and port of the server
3. enter the server
4. log in the server
5. automatic get bugged

### Expected behaviour

![WhatsApp Image 2021-06-05 at 2 40 13 PM](https://user-images.githubusercontent.com/85413861/120903503-0d4d2980-c60c-11eb-8f85-f9f14bccc8a3.jpeg)

### Server Version and Plugins

40ServidoresMC, AdvancedNMotd, AuctionHouse, AuthMe, Better-Enchantments, BuycraftX, Chairs, ChatColor2, CoreProtect, CrackShot, DeadlyDisasters, Essentials, floodgate-bukkit, Geyser-Spigot, GoldenCrates, Harbor, HolographicDisplays, ImageOnMap, Jobs, KarenProtect*, LPC, LuckPerms, Minepacks, Multiverse-Core, Multiverse-Portals, MythicMobs, NexEngine, OreAnnouncer, Parties, PlaceholderAPI, PlayerControl, PrettySimpleShop, ProtocolLib, PvPManager, Scoreboard, SetSpawn*, Shopkeepers, SkinsRestorer, SpawnerSilk, Timber, TrollBoss, UberEnchant, UltraChest, Vault, Votifier, VotingPlugin, WorldBorder*, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/RfMzDq7534RA5uEjHq88tpIlBQcU5vWO

### Geyser Version

1.2.1-SNAPSHOT (git-master-dbf366b)

### Minecraft: Bedrock Edition Version

1.16.220.02

**Comment by Degagelemming95** [comment]
thats because you are 20 million blocks out and bedrock cant load the world properly at that distance since it runs on 32 bits where java can load that because it runs on 64 bits. Also, thats why theres random 2d looking blocks in a grid pattern.

**Comment by RednedEpic** [comment]
As mentioned, this is a Bedrock limitation.
