### ISSUE TITLE
Scaffolding Fall Damage

### ISSUE THREAD

**Issue by angrynerd** [GeyserMC/Geyser#2257]
### Describe the bug

Players take fall damage when going down scaffolding blocks while majorily outside the block. THis also occurs if someone where to exit the scaffolding and then come back in mid drop which is not a java behavior. 

### To Reproduce

1. build scaffolding to a distance that one could take fall damage from.
2.  stand majorily outside of the scaffolding block without falling off of it. 
3. decend the scaffolding untill you hit the ground.
4. optionally this can also be done with a drop outside of the scaffolding and then re-entering mid drop.

### Expected behaviour

Both cases should not produce fall damage.

### Server Version and Plugins

This server is running Geyser version 1.2.1-SNAPSHOT (git-master-4c542ba) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220)

I also use several plugins.
1. lithium
2. phosphor
3. krypton
4. ferrite
5. hydrogen
6. gunpowder
7. fabric api
8. carpet 
9. carpet fixes
10. lazydfu
11. smoothboot
12. randompatches

### Geyser Dump

https://dump.geysermc.org/s7ZMDzEMtIpQTOhLkiXPFqXdVKogoq4S

### Geyser Version

This server is running Geyser version 1.2.1-SNAPSHOT (git-master-4c542ba) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220)

### Minecraft: Bedrock Edition Version

1.16.220

**Comment by RednedEpic** [comment]
Stale issue - feel free to comment here if this is still an issue & please attach a video if so.

**Comment by eihqnh** [comment]
Still exist
https://media.discordapp.net/attachments/613163671870242842/1007652347100541079/QQ_4117946ea77c374341410e595006d2d71660312525.mp4
