### ISSUE TITLE
Is it possible to work with Model Engine—Ultimate Entity Model Manager

### ISSUE THREAD

**Issue by Lukamino** [GeyserMC/Geyser#2259]
### What feature do you want to see added?

I added the texturepack that i use with my custom models, but the bedrock player sees nothing but the java players do so is it possible to add this?

sorry for my bad spelling

### Are there any alternatives?

The only thing i tried is to use the newest geyser build and i installed the new update of Model Engine.

**Comment by Camotoy** [comment]
This would very likely be bound to resource pack support which we have funneled into #210. Thank you for feature requesting anyway!

**Comment by ofunny** [comment]
See #2988 for more about it.
