### ISSUE TITLE
Player name display and java skins

### ISSUE THREAD

**Issue by FPSUsername** [GeyserMC/Geyser#2261]
### Describe the bug

Players that have the same name as the Bedrock player get the player tag "pig".
This happens at least with offline java accounts.

Furthermore, it looks like java player skins don't render on Bedrock. Either with true online players or [SkinsRestorer](https://github.com/SkinsRestorer/SkinsRestorerX). Java players can see skins  from Bedrock players that use SkinsRestorer.

### To Reproduce

Login on the server with a Bedrock and offline java account (with the same name). Walk up to each other and observe the nametag.

Configs that might be of importance:
`server.properties` &rarr; `online-mode=false`
GeyserMC `config.yml` &rarr; `auth-type: floodgate`

### Expected behaviour

Show the correct name of the user with the same player name and skins for online users.

### Screenshots / Videos

Offline java account with the same name
![Screenshot_2021-06-07-15-30-54-497_com mojang minecraftpe](https://user-images.githubusercontent.com/10143926/121025657-afece000-c7a5-11eb-8385-66a9ac04aa00.jpg)

The Bedrock account has an asterisk symbol in front of its name
![Screenshot_2021-06-07-15-38-12-504_com Mojang minecraftpe](https://user-images.githubusercontent.com/10143926/121026576-8d0efb80-c7a6-11eb-8f4a-f3760681a056.jpg)

Online java account, different username. No Minecraft skin visible
![Screenshot_2021-06-07-15-36-10-580_com mojang minecraftpe](https://user-images.githubusercontent.com/10143926/121026747-b039ab00-c7a6-11eb-83dd-3e5aa98e400d.jpg)

#### Edit
A couple of restarts and it works. Playerheads and skins render fine. However, I noticed that java players can't see the skins of bedrock players, at least not with  free microsoft bedrock accounts (pocket edition)
![Screenshot_2021-06-07-20-11-19-735_com mojang minecraftpe](https://user-images.githubusercontent.com/10143926/121068724-ea1da800-c7cc-11eb-8022-d5b981864208.jpg)

### Server Version and Plugins

***Version***
This server is running Paper version git-Paper-770 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-769 (MC: 1.16.5)

***Plugins***
ActionBarAPI-1.5.4.jar
AdvancedWeapons.jar
Alchema-1.1.2.jar
Bookshelf-3.0.0.1.jar
Cameras.jar
Chairs.jar
CoreProtect-19.5.jar
CustomPortals.jar
CutterDamage-1.1-SNAPSHOT.jar
DecorHeads.jar
Elevators+v2.jar
ElevatorsPlus.jar
EssentialsX-2.19.0-dev+113-0d640d1.jar
EssentialsXSpawn-2.19.0-dev+113-0d640d1.jar
FastAsyncWorldEdit-Bukkit-1.16-688.jar
Geyser-Spigot.jar
Harbor-1.6.3.jar
HorseStats-5.0.3.jar
InteractionVisualizer-1.14.10.7.jar
InteractiveChat-3.3.0.12.jar
ItemFrameToggle-1.1.1.jar
Lift.jar
LightAPI-fork-3.4.6.jar
LuckPerms-Bukkit-5.3.16.jar
Multiverse-Core-4.2.3-SNAPSHOT.jar
Multiverse-Inventories-4.2.3-SNAPSHOT.jar
Multiverse-NetherPortals-4.2.2-SNAPSHOT.jar
Multiverse-Portals-4.2.2-SNAPSHOT.jar
MusicBox-2.0.4-all.jar
MyDog-0.1.1-alpha-2.jar
NoteBlockAPI-1.6.1.1-SNAPSHOT.jar
OwnGarden.jar
PetMaster.jar
PixelMOTD-v8.8.6-PreAlpha1.jar
PlaceholderAPI-2.10.9.jar
PlugMan.jar
ProtocolLib.jar
RealisticSnow.jar
RedstoneProximitySensor-2.5.2.jar
SKLibrary.jar
Seasons.jar
ShulkerboxPreview-2.1.jar
SilkSpawners.jar
SkinsRestorer.jar
TCPShield-2.5.jar
TabList-5.5.4.jar
TitleWelcomeMessage-3.3.7.jar
UltimateHeads.jar
Vault.jar
ViewDistanceTweaks-1.3.2.jar
WorldBorder.jar
farmingupgrade-1.2.5.jar
floodgate-bukkit.jar
worldguard-bukkit-7.0.4.jar

### Geyser Dump

https://dump.geysermc.org/dnLOEhr80O1a3jsIhzvKPAuYFGDwZT2J

### Geyser Version

1.2.1-SNAPSHOT (git-master-aaa100b)

### Minecraft: Bedrock Edition Version

1.16.221.01

**Comment by Camotoy** [comment]
> Players that have the same name as the Bedrock player get the player tag "pig".

Very very very likely a result of plugins not working well with multiple users with the same username. The Floodgate prefix exists for this reason. :P

**Comment by FPSUsername** [comment]
That explains the asterisk then, but not why the java player is called "pig" haha

**Comment by Konicai** [comment]
No response; closing
