### ISSUE TITLE
Issue/incompatibility with cinematics plugin

### ISSUE THREAD

**Issue by wearenoobsuk** [GeyserMC/Geyser#2263]
### Describe the bug

**Using this plugin** 
https://www.spigotmc.org/resources/cinematic-studio-tell-stories-through-cutscenes-npc-motion-capture-1-14-1-16-x.88671/

When ever a java player runs any cinematic, it runs perfectly with no issue,
When ever a bedrock player attempts this, they get thrown into a hard crash, (It doesnt say no responding) it just freezes, their ingame character vanishes ( I think they actually do go into the cinematic but it just frozen on their screen)

The only way out of this freeze is to kill minecraft.exe in task manager.
When they relog in after this, they are at the end of the cinematic (different location) which leads me to believe they do 'technically' go through the cinematic, 

I have attached a video of it happening,

### To Reproduce

Install https://www.spigotmc.org/resources/cinematic-studio-tell-stories-through-cutscenes-npc-motion-capture-1-14-1-16-x.88671/

Make any cinematic
try and run it on/as a bedrock player

### Expected behaviour

To be able to have the same experience as the java player

### Screenshots / Videos

https://streamable.com/xho8jk

### Geyser Version

Geyser version 1.2.1-SNAPSHOT (git-master-aaa100b) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.220)

### Additional Context

I feel like this is related to geyser not the cinematics plugin as, it doesn't do anything bedrock specific. If any diagnosis is used i can give permissions to any geyser staff on my server for testing purposes , ty!

Have tested floodgate 1.0 and 2.0 and fully updated everything also

**Comment by Konicai** [comment]
maybe related to this https://github.com/GeyserMC/Geyser/issues/1334 ?

**Comment by wearenoobsuk** [comment]
> maybe related to this #1334 ?

I probably should have mentioned sorry, I did have it set up to put the player in gmsp, but i removed that as i thought this was the issue myself, it still crashes in gms, or gmc etc

**Comment by wearenoobsuk** [comment]
Any input on this? I been doing as much investigating as I can I believe the author said its most likely on geyser side as he doesn't handle anything bedrock specific

**Comment by Jens-Co** [comment]
Hello there, can you update geyser to the latest master version ? The issue with Spectator mode should be fixed in (https://github.com/GeyserMC/Geyser/commit/5529a1cc1c004b066c5a737f96e7de1749a2acf0)

**Comment by Jens-Co** [comment]
I will close this issue due to no response and unable to recreate this issue with the specific plugin in question dues to it being a paid one. I will test with other cinematic plugins. If you encounter this issue let me know and I reopen this. Thanks!

If you update this please add a dump to.
