### ISSUE TITLE
"You Died" screen doesn't cancel while playing a game of The Bridge by Plugily Projects

### ISSUE THREAD

**Issue by TheMonBonGH** [GeyserMC/Geyser#2265]
### Describe the bug

While in a game of [The Bridge](https://github.com/Plugily-Projects/TheBridge), when dying, the "You Died!" screen shows, then is cancelled, on a Java Edition client. However, on a Bedrock client, The death screen stays without the event being cancelled and you have to press the Respawn button to continue the game. Everything in the plugin does do its job, but the death screen does give a time disadvantage to Bedrock clients.

### To Reproduce

You can join `bedrock.greaper88.net:19172 / java.greaper88.net` and do `/ctf` to join a server with the plugin already set up
1. Set up a 1.16.5 Tuinity server with ["The Bridge" plugin by Plugily Projects](https://www.spigotmc.org/resources/the-bridge-1-8-8-1-16.87320/)
2. Join a game with a Bedrock Edition  and Java Edition client for comparison
3. Kill the Bedrock player/fall in the void on both clients to compare

### Expected behaviour

When dying from a player/falling to the void, the normal "You Died!" screen should show, then should disappear in a short time.

### Screenshots / Videos

https://youtu.be/det4MTfhW4M
When my Java Edition Client walks up to my Bedrock Client and kills me, the "You Died" screen pops up but isn't cancelled instantly. What's supposed to happen is when a Java player dies, the "You Died" screen should pop up then be closed automatically by the server.

### Server Version and Plugins

_THIS INFORMATION IS FROM THE BACKEND SERVER WITH THE MINIGAME PLUGIN_
This server is running Tuinity version git-Tuinity-"df76b3c" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Plugins (16): ChatPing*, Citizens, FastAsyncWorldEdit (WorldEdit), goBrush, goPaint, HubBasics, MultiChat*, Multiverse-Core, OldCombatMechanics, PerWorldServer, PlaceholderAPI, ProtocolLib, **TheBridge**, Vault, VoidGenerator, WorldEditSUI

### Geyser Dump

https://dump.geysermc.org/XFeO1iIZjMxUj0nZv43L11bjxm2VTP9K

### Geyser Version

1.4.0-SNAPSHOT (2b7c759)

### Minecraft: Bedrock Edition Version

1.17.0

**Comment by TheMonBonGH** [comment]
Any update?

**Comment by Camotoy** [comment]
Does the bug still persist in the latest version of Geyser?

**Comment by TheMonBonGH** [comment]
> Does the bug still persist in the latest version of Geyser?

On my iPhone X and Windows 10 game, yes it still persists.

**Comment by TheMonBonGH** [comment]
I seem to fix the issue visually as will, by enabling the doImmediateRespawn gamerule, sorry for any inconvenience!
