### ISSUE TITLE
Can not join with 1.17 even with viaversion updated

### ISSUE THREAD

**Issue by elaineandsparky** [GeyserMC/Geyser#2268]
### Describe the bug

1.17 p.e players can not join my 1.16.5 server even with viaversion installed and updated. it jjust says can't connect and gives no messages in console.

Viaversion gives a warning in console that we are running an older java version (11.0.11) and need 16. Hosts say this will be done automatically when paper and spigot update to 1.17. However we can't update our server properly to 1.17 until other plugins have updated.

I'm assuming this is why 1.17 players can't join on p.e (but can on java). Can geyser support older java versions for a few more months until people can update their servers properly after other plugins have updated rather than just using viaversion.

### To Reproduce

.

### Expected behaviour

.

### Geyser Version

bungeecord 709

**Comment by SuryanshxND24** [comment]
Well you should close this as geyser needs java 16

**Comment by Jens-Co** [comment]
^ he is still using the 1.16 server. Currently geyser can still use older versions of Java, for further support you can join our discord.

**Comment by elaineandsparky** [comment]
discord isn't coming back with any resolutions hense coming here.

**Comment by PappoYT** [comment]
Same problem here.
Paper 1.16.5 with Geyser build 709 and Floodgate build 7.

Players with bedrock edition cannot join server after they update their client to 1.17.
Error: Cannot connect to world.

**Comment by PajamaFrix** [comment]
also having this issue. i messed around with different configuration settings in both geyser and floodgate, disabled some plugins, ran a server under a test environment (simple paper 1.16.5 server with geyser, floodgate, and viaversion), upgraded my server, all to no avail. java users are able to connect, just not under bedrock.

technical details: paper 1.16.5 server; latest geyser, floodgate, and viaversion builds; java 16.0. some example (server-side) errors are '[Geyser-Spigot] Outdated Bedrock client! Please use 1.17.0' and '... lost connection: Failed to verify username!' (though i doubt the latter is related to Geyser, but i'm including it just in case) and 'Cannot connect to world' (client-side).

**Comment by Tim203** [comment]
> Outdated Bedrock client! Please use 1.17.0

Sounds like you're still on 1.16.

But for all the other errors you guys are having: please send some logs. Just saying that it doesn't work isn't really helpful for finding a solution.

**Comment by elaineandsparky** [comment]
https://mclo.gs/UgyrIw4

It is worth noting that I do not have and have never had floodgate which has never been an issue.

**Comment by elaineandsparky** [comment]
turns out i did have floodgate after all! my bad. all good now after updating that. Thank you for your replies anyway.

**Comment by Camotoy** [comment]
At this point, I suspect any issue is an indirect result of something else. If you have issues with connecting, it is likely some setup error; please join our Discord. Thank you!!
