### ISSUE TITLE
Bedrock players can't see other players

### ISSUE THREAD

**Issue by Luuk-VH** [GeyserMC/Geyser#2270]
### Describe the bug

Dear,

I updated geyser, floodgate, viaversion, viabackwards. The server is running 1.16.5 and bedrock players can join etc. But the problem is that java players can see bedrock players but bedrock players cant see any players even other bedrock players not.

### To Reproduce

[19:18:27 WARN] [Geyser-BungeeCord]: Haven't received PlayerListEntry packet before spawning player! We ignore the player 7e343f1c-c352-4c9a-815e-a98465b281de

### Server Version and Plugins

This server is running Tuinity version git-Tuinity-"b12d0cc" (MC: 1.16.5), geyserbungee, viaversion, viabackwards, floodgate all are the latest versions

### Geyser Dump

https://dump.geysermc.org/DQVxdXUEPz3WKIOncdQl5m1P993Irqo4

### Geyser Version

This server is running Geyser version 1.4.0-SNAPSHOT (git-master-78b7955) (Java: 1.17, Bedrock: 1.17.0)

### Minecraft: Bedrock Edition Version

1.17

**Comment by Camotoy** [comment]
Can you see if this problem persists with Java 1.17 players?

**Comment by Luuk-VH** [comment]
> Can you see if this problem persists with Java 1.17 players (if they have the same issues as Bedrock players)?

If 1.17 players join they got this error:

Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: com:google.gson.stream.MalformedJsonException: Use JsonReader.setLeniet((true) to accept malformed JSON at line 1 column 1 path $

**Comment by RednedEpic** [comment]
The kick mentioned is because of a BungeeTabListPlus issue when ViaVersion is installed. Can you try removing BungeeTabListPlus for now and see what happens?

**Comment by Luuk-VH** [comment]
> The kick mentioned is because of a BungeeTabListPlus issue when ViaVersion is installed. Can you try removing BungeeTabListPlus for now and see what happens?

How did you know that this is this plugin?

**Comment by RednedEpic** [comment]
It was mentioned in Via’s discord.

**Comment by Luuk-VH** [comment]
> It was mentioned in Via’s discord.

Alright m8, i removed the BUngeeTablistPlus. Java 1.17 players could join now and bedrock players sees everyone again!
