### ISSUE TITLE
Geyser cant connect with v1.17.0 

### ISSUE THREAD

**Issue by KaptanINO** [GeyserMC/Geyser#2271]
### Describe the bug

Can't connect my server with Geyser. My error is (Outdated server! I'm still on 1.16.5).
Bedrock Version v1.17.0

### To Reproduce

1.Open your server
2.Try to connect your server from bedrock editon ( you need to use v1.17.0)
3.See error

### Expected behaviour

I got (Outdated server! I'm still on 1.16.5) when try to connect with bedrock. 

### Server Version and Plugins

Paper Version: Lastest
Plugins: ChestShop, ClearLag, EasyWarp*, Essentials, FabledSkyBlock, floodgate, Geyser-Spigot, GoldenCrates, HolographicDisplays, Multiverse-Core, NexAuth, NexEngine, OpenInv, PlaceholderAPI, ServerSigns, ServersNPC, SetHomes, SetSpawn*, SkinsRestorer, SuperVanish, TAB, UltraPermissions, Vault, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/8wobZA7cEHLTAlOQ6cOP2LUUhjsPgJph

### Geyser Version

1.4.0-SNAPSHOT (git-master-1df6e21)

### Minecraft: Bedrock Edition Version

v1.17.0

**Comment by Chew** [comment]
You need ViaVersion (download from https://viaversion.com). This will allow 1.17 clients (you) to join your 1.16.5 server.
