### ISSUE TITLE
The item drop animation is buggy

### ISSUE THREAD

**Issue by ubanning** [GeyserMC/Geyser#2273]
### Describe the bug

When an item is dropped for the first time on the ground, the animation is very strange

### To Reproduce

Just drop a single item on the ground and watch the animation

### Expected behaviour

A drop animation similar to when you are in Single Player

### Geyser Version

1.4.0-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17

### Additional Context

This problem also happens in previous versions.

**Comment by Konicai** [comment]
As of 1.17.10 the animation is completely gone
