### ISSUE TITLE
Java to Bedrock 

### ISSUE THREAD

**Issue by SDS1234** [GeyserMC/Geyser#2274]
### What feature do you want to see added?

Hello can you add the function that you can also set the proxy so that you can join a bedrock server with a java client?
It would make me very happy. 

With kind regards

### Are there any alternatives?

I didn't find any.

**Comment by Camotoy** [comment]
It's not that simple, I am afraid, and if the Geyser team does this it will not be in the Geyser project but a new project. Therefore I am closing this. Thanks anyway!

**Comment by SDS1234** [comment]
And where should I propose that then?

**Comment by Camotoy** [comment]
There is no place to propose that. We are aware of the interest surrounding a way to join a Bedrock server from a Java client.

**Comment by SDS1234** [comment]
I have suggested it here because geyser already has something as far as the "translation" is concerned.
