### ISSUE TITLE
Error when joining from Bedrock

### ISSUE THREAD

**Issue by Arvicii** [GeyserMC/Geyser#2279]
### Describe the bug

when bedrock players try to connect, it shows them geyser.auth.floodgate.encryption_fail

### To Reproduce

1.Run the Server
2. Try to connect from bedrock

### Expected behaviour

Bedrock players should be able to join the server

### Geyser Version

CraftBukkit version 3106-Spigot-191e497-a3df386 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

**Comment by Chew** [comment]
Likely related to https://github.com/GeyserMC/Floodgate/issues/156
Without enough information, it's hard to tell. But Floodgate on Spigot 1.17 doesn't work yet anyway. If, once the above issue is resolved, you still have issues, please feel free to open a more detailed report over on that repo. Thanks!
