### ISSUE TITLE
Floodgate Fabric not working

### ISSUE THREAD

**Issue by Sludgycomb40045** [GeyserMC/Geyser#2280]
### Describe the bug

I kept trying to get Geyser+Floodgate working on fabric, but whenever I tried it, the server would crash. I eventually tried removing floodgate and the server worked just fine. I reinstalled it and we were right back to crashes. I found a post from a while ago saying you need to use floodgate alone, delete files, then put geyser back in. I tried that but the server still crashed, and no files were created so I couldn't try the rest of the workaround.

### To Reproduce

Add Floodgate Fabric to Fabric 1.17

Start the server

### Expected behavior

Have floodgate and geyser work as they would with plugins

### Screenshots / Videos

Heres the logs:
https://mclo.gs/Dv0dOx4

### Server Version and Plugins

Fabric 1.17
Fabric API
Geyser Fabric
Floodgate fabric

### Geyser Dump

cant actually do a dump because the server crashes immediately 

### Geyser Version

Geyser-Fabric-1.0-SNAPSHOT

**Comment by Camotoy** [comment]
This is likely because of https://github.com/GeyserMC/Floodgate-Fabric/issues/7#issuecomment-817022484. Because of this, I am closing the issue, but if it still occurs after the workaround steps in that comment, please re-open this issue in the Floodgate-Fabric repository. Thank you!
