### ISSUE TITLE
1.17 Please

### ISSUE THREAD

**Issue by RedstoneBoy0509** [GeyserMC/Geyser#2282]
### What feature do you want to see added?

I am wanting an update to 1.17 as I use latest version servers and your plugin throws NMS errors on 1.17. I am a dev myself and understand the version-specific NMS stuff, however I cannot use this plugin in 1.17.

### Are there any alternatives?

- I can't find any alternatives, everything would require completely recompiling the module

**Comment by Camotoy** [comment]
Geyser 1.17 is already working. Floodgate is in progress. Please be patient. Thank you!!
