### ISSUE TITLE
Bedrock attack damage description not matching Java Edition

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [GeyserMC/Geyser#2283]
### Describe the bug

The `attack damage` description shown when hovering over an item in bedrock is not changed to match how much attack damage is done in the Java Edition. The sharpness enchant is also affected, as in Bedrock each level of sharpness increases the attack damage by 1, while in Java the first level of sharpness adds 1 attack damage and each additional level only adds 0.5 attack damage.

(I'm reporting this for the sake of it being in the issue tracker as I don't see an open or closed issue regarding it)

### To Reproduce

1. Obtain any weapon/tool
2. Read it's attack damage, found by hovering over the item on both the Bedrock and Java editions, and see that these values are not changed from how they are in Bedrock to how they are in Java
3. Add sharpness to the item, and see that sharpness does not scale on Bedrock as it does on Java

### Expected behaviour

The attack damage shown on Bedrock should match what's shown in Java

### Screenshots / Videos

Bedrock:
![Screenshot_20210612-001012-412](https://user-images.githubusercontent.com/66212375/121765050-46a6fd00-cb16-11eb-915a-ceadb2d2af40.png)
![Screenshot_20210612-001031-755](https://user-images.githubusercontent.com/66212375/121765054-4b6bb100-cb16-11eb-95c6-50174de1ff7f.png)
![Screenshot_20210612-001046-492](https://user-images.githubusercontent.com/66212375/121765056-4c9cde00-cb16-11eb-9e5b-90d62bd72817.png)
![Screenshot_20210612-001100-762](https://user-images.githubusercontent.com/66212375/121765057-4e66a180-cb16-11eb-9627-96c64f899dcb.png)
![Screenshot_20210612-001124-017](https://user-images.githubusercontent.com/66212375/121765061-50c8fb80-cb16-11eb-82ab-a7e38c03b8cf.png)
![Screenshot_20210612-001144-434](https://user-images.githubusercontent.com/66212375/121765065-5292bf00-cb16-11eb-8541-d4b9695f5e0c.png)

Java:
![Screenshot_20210612-000309-305](https://user-images.githubusercontent.com/66212375/121765114-b87f4680-cb16-11eb-9b2f-0964ab4b294e.png)
![Screenshot_20210612-000333-280](https://user-images.githubusercontent.com/66212375/121765116-bb7a3700-cb16-11eb-8d07-c98ae34faf06.png)
![Screenshot_20210612-000554-757](https://user-images.githubusercontent.com/66212375/121765124-c1701800-cb16-11eb-89b3-313d14e8ec49.png)
![Screenshot_20210612-000612-144](https://user-images.githubusercontent.com/66212375/121765128-c3d27200-cb16-11eb-99aa-b5142620a61f.png)
![Screenshot_20210612-000632-292](https://user-images.githubusercontent.com/66212375/121765129-c6cd6280-cb16-11eb-9ba2-32a46e9a0829.png)
![Screenshot_20210612-000656-701](https://user-images.githubusercontent.com/66212375/121765134-c9c85300-cb16-11eb-8099-0c80f1069b74.png)

### Geyser Dump

https://dump.geysermc.org/mXvgfTt10fAivGPxQZrdRTfYfN3j1YSd

### Geyser Version

Fabric 1.4.0-SNAPSHOT (git-master-2b7c759)

### Minecraft: Bedrock Edition Version

1.17.0

**Comment by Camotoy** [comment]
The server doesn't control this behavior. Maybe an OptionalPack fix, but I'm skeptical that can be done.

**Comment by kylevardy1** [comment]
This isn't a geyser problem. This is just how Minecraft was programmed. Please close the ticket.

**Comment by RednedEpic** [comment]
This is a Bedrock limitation as stated above, closing.
