### ISSUE TITLE
Server thread/ERROR Error occurred while enabling Geyser-Spigot v1.4.0-SNAPSHOT (Is it up to date?)

### ISSUE THREAD

**Issue by Mendezewq** [GeyserMC/Geyser#2284]
### Describe the bug

Server thread/ERROR Error occurred while enabling Geyser-Spigot v1.4.0-SNAPSHOT (Is it up to date?)

### To Reproduce

Server thread/ERROR Error occurred while enabling Geyser-Spigot v1.4.0-SNAPSHOT (Is it up to date?)

### Expected behaviour

Play Java on bedrock

### Geyser Version

 Geyser-Spigot v1.4.0-SNAPSHOT

**Comment by rtm516** [comment]
Please provide a full server startup log, this is likely a configuration issue.

**Comment by Camotoy** [comment]
As there has been no response, I am closing. If you continue to have this error, it is likely a setup issue; please join our Discord for further assistance. Thank you!
