### ISSUE TITLE
No poision when attacked by poision spiders

### ISSUE THREAD

**Issue by AngelBePro** [GeyserMC/Geyser#2285]
### Describe the bug

When my friend finded mineshaft and was playing on bedrock he didn't take poision effect by the poision spiders he was only taking damage.

### To Reproduce

You just get damaged by poisioned spider and get damage without poision effect

### Expected behaviour

To not have poision effect when got hit by the spider.

### Geyser Dump

 https://dump.geysermc.org/H81Sm5bna4XFKwvpBU3OFP38MtWd9gzA

### Geyser Version

1.4.0 SNAPSHOT (git-master-cc2d26d)

### Minecraft: Bedrock Edition Version

1.16.220

### Additional Context

Im on java and he told me he was not taking poision damage and it was unfair for me and i reported it to you

**Comment by Camotoy** [comment]
This should not be a Geyser issue, as this behavior is controlled entirely by the server. I would recommend seeing if there's another plugin interfering.

**Comment by AngelBePro** [comment]
The plugins I installed are:
Floodgate-spigot
EssentialX latest version
Better Sleeping
GSit
ImageOnMap
WorldEdit-bukkit-7.2.5-dist

**Comment by AngelBePro** [comment]
Not sure if thats helpful but thats all plugins installed

**Comment by UrLocalPerson** [comment]
Like Camotoy said this isnt a geyser issue i've experienced this happening at regular servers too even singleplayer worlds so its on minecrafts side if it happens like once in a while but if it happens everytime then its either a plugin thats interfering or the server

**Comment by AngelBePro** [comment]
Ok then closing this not issue

**Comment by Chew** [comment]
As far as I know, this requires a higher difficulty and may be affected by the local difficulty. Both of these are controlled by the server, however.
