### ISSUE TITLE
Server is too popular

### ISSUE THREAD

**Issue by BlastPerson12345** [GeyserMC/Geyser#2286]
### Describe the bug

Hi. When I was trying to join my server from bedrock, it said server too popular. Any fixes? Thanks.

### To Reproduce

Go to Play
Click On Servers
Click on my geyser server

### Expected behaviour

For me to join into my world and to play with my friends.

### Geyser Version

1.17

### Minecraft: Bedrock Edition Version

1.17

**Comment by Camotoy** [comment]
This is a known issue that occasionally occurs. Try connecting with an IP address instead of a domain, if that applies to your situation. Otherwise, make sure you're connecting to the right IP and port. Geyser itself shouldn't produce this error.

**Comment by BlastPerson12345** [comment]
Wow, fast reply thanks! I will try this, your a life saver

**Comment by BlastPerson12345** [comment]
It did not work, anything else that could fix it?

**Comment by Camotoy** [comment]
Please provide a Geyser dump, then.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by BlastPerson12345** [comment]
when I ran geyser dump i got: an internal error occured while trying to perform that command. if this helps, i am hosting my server from Apex Hosting

**Comment by Camotoy** [comment]
That's probably part of your issue. I would recommend joining our Discord for further support as this sounds like a setup issue. Thanks!

**Comment by BlastPerson12345** [comment]
thx
