### ISSUE TITLE
Bedrock players do not load in, cannot move, or freeze (unplayable) when Java players are present

### ISSUE THREAD

**Issue by noahburning** [GeyserMC/Geyser#2288]
Keep in mind, the following issue occurred once the server was updated to 1.17. When the server was on 1.16.5, none of these issues occurred.

The following log and full Geyser dump was done on a full reset of my server, spigot was deleted and rebuilt using the latest updated BuildTools.jar and Geyser and Floodgate are on their latest updated jars. The world was completely reset, this issue continued occurring even on a fresh world.

The issue is as follows:

Bedrock players are unable to play, they are falling into the void for the end of time or they get in a frozen state and cannot move. This all happens the moment a Java player joins. If a bedrock player is the first person to enter the server after it has been started, they will have no issues playing on it whatsoever. However, the moment a Java edition player joins the server, they get completely frozen on the Java side, are still able to move and hit players, but cannot see anything moving as if the server crashed. Additionally, if they try to rejoin, they are simply thrown into the void at Y= -40 and never load in. The server is running with a starting ram of 5gb with a maximum ram of 6gb. It is running a 2.5gz Intel Core i5 processor. It is running on a dedicated laptop bought this year, running on a SSD. I have been having this issue ever since the 1.17 spigot update came out. All Geyser and Floodgate configs have been reset multiple times to their default states. No other plugins are being run on the server.

The following are the logs and full geyser dumps. Thank you. 

https://mclo.gs/KIQ8ZH2
https://dump.geysermc.org/96C3V3Ak0MHBldoa77VPtVWOhy78AOEc

**Comment by noahburning** [comment]
To whomever it may concern: This continues to occur even with regular Geyser online.

**Comment by noahburning** [comment]
A little update: When Java players are already playing and a bedrock player tries to join, they are stuck at y=-40 in the void and never can leave. Is this due to a lack of RAM?

**Comment by Konicai** [comment]
Check in task manager if the java runtime environment for the spigot server is maxing out on available memory (whatever you specified as Xmx in the java startup arguments). If it isn't close, Geyser probably isn't running out of memory.

**Comment by Camotoy** [comment]
Also, send a log with debug mode enabled in Geyser's config?

**Comment by Hellohi3654** [comment]
I have had a similar issue before
When the bedrock players freeze but have loaded in and can move and hit things. Try teleporting them to a location nearby and see if they start moving then.
I think it might be some sort of desync issue where as soon as the bedrock player's position desyncs they freeze in place on the server side but not client side

**Comment by noahburning** [comment]
> Check in task manager if the java runtime environment for the spigot server is maxing out on available memory (whatever you specified as Xmx in the java startup arguments). If it isn't close, Geyser probably isn't running out of memory.

Hello! I have checked and it is nowhere near close to it's allotted memory maximum.

**Comment by noahburning** [comment]
> Also, send a log with debug mode enabled in Geyser's config?

Hello! Thank you for your help.

The following are the latest log (with a bedrock player joining, able to move, then breaking once a java player joins) and, subsequently, a full geyser dump with debug enabled in the config. Thanks!

https://mclo.gs/cGCN7UJ
https://dump.geysermc.org/bMrqieoAzbbk1g2xctHttczzRs8zUsYO

**Comment by Konicai** [comment]
Geyser is definitely wacking out with all those movement checker teleports...

**Comment by noahburning** [comment]
@Konicai @Hellohi3654 @Camotoy 

This is probably a good thing to note. I followed @Hellohi3654 's advice and Geyser completely freaked out (latest log attached below). It tried to repeat the teleport a billion times it seems. 

https://mclo.gs/ZvRbLWn

**Comment by Hellohi3654** [comment]
> @Konicai @Hellohi3654 @Camotoy
> 
> This is probably a good thing to note. I followed @Hellohi3654 's advice and Geyser completely freaked out (latest log attached below). It tried to repeat the teleport a billion times it seems.
> 
> https://mclo.gs/ZvRbLWn

Not sure but if your not using spigot try using it

Other than that idk

**Comment by noahburning** [comment]
> > @Konicai @Hellohi3654 @Camotoy
> > This is probably a good thing to note. I followed @Hellohi3654 's advice and Geyser completely freaked out (latest log attached below). It tried to repeat the teleport a billion times it seems.
> > https://mclo.gs/ZvRbLWn
> 
> Not sure but if your not using spigot try using it
> 
> Other than that idk

Hello! 

I don't know if you can see in the log files or the gesyer dump but I am using the latest update of spigot via buildtools :)

**Comment by Hellohi3654** [comment]
> > > @Konicai @Hellohi3654 @Camotoy
> > > This is probably a good thing to note. I followed @Hellohi3654 's advice and Geyser completely freaked out (latest log attached below). It tried to repeat the teleport a billion times it seems.
> > > https://mclo.gs/ZvRbLWn
> > 
> > 
> > Not sure but if your not using spigot try using it
> > Other than that idk
> 
> Hello!
> 
> I don't know if you can see in the log files or the gesyer dump but I am using the latest update of spigot via buildtools :)

Couldn't tell if it was spigot or bukkit

**Comment by noahburning** [comment]
I am going to attempt to see if any of the new geyser or floodgate updates have fixed my issues.

**Comment by noahburning** [comment]
It did not

**Comment by Gaming32** [comment]
I discovered afterwards that my issue was that players are millions of blocks away from (0,0)

**Comment by Konicai** [comment]
Definitely something to look out for, but unfortunately not the case for noah

**Comment by ProbablyGallium** [comment]
I'm encountering the same issue, except even with a completely empty server, bedrock clients still experience the world not loading in. I'm running Paper version `git-Paper-46` and the latest builds of Geyser and Floodgate.

**Comment by Camotoy** [comment]
Do you share the same symptom of it only happening when a Java player is present?

**Comment by ProbablyGallium** [comment]
I do not. The issue persists if the server has no players on it except for one bedrock client.

**Comment by Camotoy** [comment]
Can you provide a Geyser dump?

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by ProbablyGallium** [comment]
Sure! Here it is: https://dump.geysermc.org/H4kJ65uzBRPAm5Kwc4ZbsLybAC3Wi71n

**Comment by Camotoy** [comment]
Two things you can try:

- set `remote` `address` to `127.0.0.1` and `remote` `auth-type` to `floodgate` and see if that resolves your issue.
- try the build linked here: https://github.com/GeyserMC/Floodgate/issues/154#issuecomment-867227665

**Comment by ProbablyGallium** [comment]
Alright, after setting the remote address and remote auth-type and running `geyser reload`, the same results occurred.
*However*, after using the build linked above, the issue still persists, but now only if Java clients are connected.

**Comment by ProbablyGallium** [comment]
Update on this: It seems as though if the issue happens once, it will continue to happen? as now Bedrock clients encounter the same issue on a completely empty server. They fall into the void endlessly clientside, serverside they connect, suffocate in a wall, and then get kicked due to keepalive timeout.

**Comment by Camotoy** [comment]
Could you please try the latest Geyser build?

**Comment by ProbablyGallium** [comment]
On the latest Geyser build, the issue still persists, but again only if Java clients connect, however: If you were in the server before the Java client connected, you're able to still interact, albeit in a slightly buggy state, like, you can break blocks but they'll disappear rather than the normal breaking behavior, and chat messages won't register client-side. Reconnecting while a Java client is connected causes you to fall into the void once again.

**Comment by mcmohen** [comment]
> 在最新的 Geyser 版本中，该问题仍然存在，但同样仅当 Java 客户端连接时：如果您在 Java 客户端连接之前在服务器中，您仍然可以进行交互，尽管处于稍微有问题的状态，例如，您可以破坏块，但它们会消失而不是正常的破坏行为，并且聊天消息不会在客户端注册。在连接 Java 客户端时重新连接会导致您再次陷入空白。

totally the same problem,any solution pls?

**Comment by noahburning** [comment]
I'd like to note that this issue still persists even with the latest build, version of MC (1.18), and latest version of Floodgate. This describes the issue perfectly:

"On the latest Geyser build, the issue still persists, but again only if Java clients connect, however: If you were in the server before the Java client connected, you're able to still interact, albeit in a slightly buggy state, like, you can break blocks but they'll disappear rather than the normal breaking behavior, and chat messages won't register client-side. Reconnecting while a Java client is connected causes you to fall into the void once again."

**Comment by Camotoy** [comment]
Can you send a new Geyser dump?

**Comment by noahburning** [comment]
https://dump.geysermc.org/OBnOFFpooOETWAUQn4TQgtSQ8ScNF2Nj

**Comment by Camotoy** [comment]
Have you tried with two Bedrock players?

**Comment by noahburning** [comment]
Do you want me to try with two bedrock and one java or just two bedrock?
Friday, 03 December 2021, 07:00PM -08:00 from Camotoy  ***@***.*** :

**Comment by Camotoy** [comment]
Specifically, I'm looking to see if another player is what causes the lag, or specifically a Java player.

**Comment by ibrahimkhurram407** [comment]
I am having the same problem with my paper 1.18.1 server :| (I thought its because of a weak internet connection but after reading this forum I don't think its the internet.

**Comment by joveaaron** [comment]
IT'S STILL FUCKING BROKEN

**Comment by RednedEpic** [comment]
Not seen any further reports on this. Please open a new issue w/ updated replication steps if this is still an issue.
