### ISSUE TITLE
Make Java player skins visible in Bedrock

### ISSUE THREAD

**Issue by Minionguyjpro** [GeyserMC/Geyser#2289]
### What feature do you want to see added?

Make java player skins visible in Bedrock. because then it looks more normal and beyter.

### Are there any alternatives?

No

**Comment by Camotoy** [comment]
Skins from Java players should be visible to Bedrock players. Please attach a Geyser dump.

**Comment by RednedEpic** [comment]
Nothing meaningful we can do with this information. Please open a new issue using the issue format if this is an issue, and make sure you are not in offline mode.
