### ISSUE TITLE
Geyser-Spigot Team Override log

### ISSUE THREAD

**Issue by KaptanINO** [GeyserMC/Geyser#2290]
### Describe the bug

I always get "Ignoring team tm-sb-10. It overrides without removing old team." log when a player connected with geyser. Its messing up my logs! (BTW the tm-sb-10 always changes. Like tm-sb11,tm-sb12,tm-sb13,tm-sb14)

### To Reproduce

1. Install Geyser version 1.4.0-SNAPSHOT (git-master-1df6e21) (Java: 1.17, Bedrock: 1.17.0)
2. Open your server.
3. Connect to your server with geyser.
4. See error.

### Expected behaviour

I tried to connect my server with geyser. I connected but my logs are messing up because Geyser. I always get this info message from Geyser-Spigot "Ignoring team tm-sb-10. It overrides without removing old team.".

### Server Version and Plugins

Lastest Paper 1.16.5

### Geyser Dump

https://dump.geysermc.org/gxu6zLepdcKuajUXucyq6QgcUg5EY4iL

### Geyser Version

1.4.0-SNAPSHOT (git-master-1df6e21)

### Minecraft: Bedrock Edition Version

v1.17.0

**Comment by Camotoy** [comment]
This message is intentional - the TitleManager plugin is improperly handling the scoreboard (Java Edition also throws errors at this in its client log). Please downgrade to 2.3.0 if you want to resolve this. (Also you should update your ProtocolLib build)

We don't intend on fixing this for the above reason. Thank you anyway for reporting!

**Comment by KaptanINO** [comment]
> This message is intentional - the TitleManager plugin is improperly handling the scoreboard (Java Edition also throws errors at this in its client log). Please downgrade to 2.3.0 if you want to resolve this. (Also you should update your ProtocolLib build)
> 
> We don't intend on fixing this for the above reason. Thank you anyway for reporting!


Which plugin is version 2.3.0 for?

**Comment by Camotoy** [comment]
TitleManager.

**Comment by KaptanINO** [comment]
> TitleManager.

Thanks for fast help mate!
