### ISSUE TITLE
Cannot be self-harmed by an arrow

### ISSUE THREAD

**Issue by vijaypondini** [GeyserMC/Geyser#2294]
### Describe the bug

Attempt to damage yourself by pointing your bow upwards and shooting an arrow to directly hit you. You will notice that the arrow floats above the player's head and it does not damage the player. In some instances, the player can move away and they won't get damaged by it, in some instances, the player does get damaged.

### To Reproduce

1. Get yourself a bow
2. As well as some arrows
3. Point yourself directly upwards, and shoot an arrow so that it hits you
4. Try this with normal arrows as well as tipped arrows with potion effects

### Expected behaviour

You should be hit with the arrow. C'mon, i wanna injure myself!

### Screenshots / Videos

https://imgur.com/a/SsBSSWf

### Server Version and Plugins

This server is running Geyser version 1.4.0-SNAPSHOT (git-master-2b7c759) (Java: 1.17, Bedrock: 1.17.0)
[10:09:47 INFO]: Checking version, please wait...
[10:09:47 INFO]: You are 16 versions behind; download the latest build from https://ci.geysermc.org/

This server is running Waterfall version git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437 by md_5

My plugins

![image](https://user-images.githubusercontent.com/70318494/122357877-bfbcaf00-cf71-11eb-89d6-bab7fc535360.png)

### Geyser Dump

https://dump.geysermc.org/c60yMk71vBFqT12m4bmxkIyPgE2B7UIT

### Geyser Version

1.4.0-SNAPSHOT (git-master-2b7c759)

### Minecraft: Bedrock Edition Version

1.17.0.1 or whichever's latest

### Additional Context

Nope

**Comment by Camotoy** [comment]
Unless the way we send the firing of the arrow affects its damage, I don't see how this could be affected by us. This smells like server behavior.

**Comment by vijaypondini** [comment]
Here's my backend server's information -
`[15:35:00 INFO]: Plugins (28): BedrockPlayerManager, ClearLag, Craftconomy3*, DiscordSRV, EasyFloodgateForms, EconomyShopGUI, floodgate, GriefPrevention, InventoryRollback, MCSF, MyCommand, OpenInv, PlaceholderAPI, Plan, PlugMan, PowerRanks, ProtocolLib, RegularTasks, SinglePlayerSleep, spark, Spartan, TridentDespawnControl, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard
`
`[15:35:21 INFO]: This server is running Paper version git-Paper-777 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

TridentDespawnControl does not control arrows, it controls tridents despawn rates only.

arrow-despawn-rate: 600 at my spigot.yml

    non-player-arrow-despawn-rate: -1
    creative-arrow-despawn-rate: -1
At my paper.yml

And you've seen the plugins on the proxy, nothing that could be possibly affecting them
