### ISSUE TITLE
Cannot join server that has ViaVersion on proxy

### ISSUE THREAD

**Issue by vijaypondini** [GeyserMC/Geyser#2295]
### Describe the bug

I have a proxy server setup with the latest version of waterfall, and the via family of plugins, ViaVersion, viarewind, and viabackwards. I have removed the via family of plugins on my backend server for the sake fo showing this issue. For now, I have only my survival server turned on without the via family.
Attempting to connect will give you a "Connection closed" error.

### To Reproduce

1. Have a proxy server with the via family of plugins installed, or even just ViaVersion.
2.  Have a backend server without any via plugins, that is connected to the proxy
3. Attempt to connect to the server through the proxy, and the error will show up.

### Expected behaviour

You should be able to connect, obviously :P

### Screenshots / Videos

-

### Server Version and Plugins

#2294 issue covers server versions, but I'll post it here as well
This server is running Geyser version 1.4.0-SNAPSHOT (git-master-2b7c759) (Java: 1.17, Bedrock: 1.17.0)
[10:09:47 INFO]: Checking version, please wait...
[10:09:47 INFO]: You are 16 versions behind; download the latest build from https://ci.geysermc.org/

This server is running Waterfall version git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:436f47f:437 by md_5

Plugins are geyser bungeecord, floodgate, ViaVersion, viabackwards, viarewind, player analytics ( plan ), litebans, and BotSentry.

### Geyser Dump

https://dump.geysermc.org/c60yMk71vBFqT12m4bmxkIyPgE2B7UIT

### Geyser Version

1.4.0-SNAPSHOT (git-master-2b7c759)

### Minecraft: Bedrock Edition Version

1.17.0.1 or whichever's latest

### Additional Context

Apparently, reverting back to Build 431 of waterfall and before will fix this issue, as it's on 1.16.5. I am currently on build 437 as per what it says.

**Comment by Konicai** [comment]
Can you share server logs as well please

**Comment by vijaypondini** [comment]
Will share tommorow in approx 11 hours

**Comment by vijaypondini** [comment]
https://mclo.gs/bvZog1F is my logs for the proxy.

**Comment by vijaypondini** [comment]
Ok, after some disucssion with rtm in #support-1 as well as a bunch of trial and error runs, I have concluded the following points -
https://discord.com/channels/613163671870242838/613168464634576897/855342870944415765 is where you can read our messages from.

On the latest waterfall proxy, Build 437, using via plugins on the proxy, the error we get is "connection closed"
On the waterfall proxy, build 431 ( 1.16.5's latest ), using via plugins on the proxy, the error we get is "outdated server i'm still on blah blah )
On the waterfall proxy, build 431 ( 1.16.5's latest ), using via DEV plugins ( ViaVersion 4.0.1 ONLY ), the error we get is timed out.
On the backend server, Latest papermc build 778 1.16.5, using via plugins, we get a timed out error
On the backend server, Latest paprmc buid 778 1.16.5, using via DEV plugins ( ViaVersion 4.0.1 ONLY ), the error we get is Connection closed.

I have floodgate-spigot on my backend server installed, as I need to utilise the API for a forms plugin I have
I have the latest possible geyser and floodgate bungeecord plugins setup, 1.4.0-SNAPSHOT (git-master-3c9f628)
Geyser dump for my waterfall on latest -  https://dump.geysermc.org/d9a1QOShNkVDH8QVCUPpzjsw14Sll5Fk

openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

**The only possible solution, after all the trial and errors above, to let 1.17 players join, is to get the dev version of viaversion and install it on the backend servers. This seemed to be the only way I could fix the connection problems**
More relevant screenshots are also available in the discord conversation ( link above )

I hope we've solved a relatively big issue here.

**Comment by vijaypondini** [comment]
Bump
Any ideas here?

**Comment by Camotoy** [comment]
Have you tried without Floodgate?

**Comment by vijaypondini** [comment]
It works without floodgate, but the problem is lying with having floodgate on the server.

**Comment by vijaypondini** [comment]
So, can we do anything.. you need a video showcasing it, anything I can do from my side?

**Comment by vijaypondini** [comment]
10:08:50 INFO]: [.QuickestRhyme56] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
As well as tons of downstream packet errors -
New errors have appeared, this time i'm on latest via versions, latest geyser and floodgate builds

Connection closed at client-side

https://mclo.gs/mKcKJnc

This server is running Geyser version 1.4.0-SNAPSHOT (git-master-5b1d815) (Java: 1.17, Bedrock: 1.17.0)
[10:11:24 INFO]: Checking version, please wait...
[10:11:24 INFO]: No updates available
https://dump.geysermc.org/GgDW1963p8rkNIsurgxhRNKVaVcKmam3

No via plugins at backend.

**Comment by vijaypondini** [comment]
I'm closing this issue since there's been very little testing done on it further from this problem. It primarily seems to be that some versions of via plugins work, some don't, and it's just trial and error.
