### ISSUE TITLE
excesive use of server resources

### ISSUE THREAD

**Issue by PIZZAAXX** [GeyserMC/Geyser#2297]
### Describe the bug

I've just updated Geyser to its latest version (bungeecord), but now every time a Bedrock player joins, the CPU and RAM usage goes all the way up to their limit, the server freezes and I have to restart it to make it work again. This didn't happen before updating.

### To Reproduce

1. Update Geyser to its latest version (https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/724/).

### Expected behaviour

Much less CPU and RAM use (rn RAM is using 1.89GB/2GB and the CPU is at it's limit).

### Server Version and Plugins

`[00:14:27 INFO]: This server is running Mohist version 1.12.2-225 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2855)`

`[00:15:35 INFO]: Plugins (25): BanItem, BungeeGuard, CoreProtect, DiSky, Essentials, EssentialsAntiBuild, EssentialsProtect, LuckPerms, MundoSK, SimplePrefix, SkBee, Skent, SkQuery, Skript, skript-reflect, skript-yaml, SkStuff, skUtilities, TAB, TuSKe, Vault, WolvSK, WorldEdit, WorldGuard, WorldGuardExtraFlags`

### Geyser Dump

https://dump.geysermc.org/Qjr2wSv0CdlTjHYjPcH17xyhahCpWeEv

### Geyser Version

Build #724

### Minecraft: Bedrock Edition Version

1.17

### Additional Context

The server it's connecting to is 1.12.2.

**Comment by Camotoy** [comment]
Probably related to https://github.com/GeyserMC/Floodgate/issues/154.

**Comment by Camotoy** [comment]
```
Spark is a plugin that helps you monitor performance for you server.
https://spark.lucko.me/download

To record performance on your server use:
/spark profiler --thread * --timeout 60
This will run for 60 seconds then it will automatically stop.
It'll probably lag the server a good deal but it'll give us a link we might be able to process.
```

Run that command as the lag is occurring.

**Comment by PIZZAAXX** [comment]
I can't run the command because the server literally freezes, so nothing can be run.

**Comment by PIZZAAXX** [comment]
ok i made it work, here's the link https://spark.lucko.me/yuolVrH4Oi

**Comment by Camotoy** [comment]
Try updating Floodgate and see if by chance it resolves?

**Comment by XboxBedrock** [comment]
I have encountered a similar issue and can confirm it's not floodgate, as not using floodgate does not resolve the issue, nor does updating it.

**Comment by Camotoy** [comment]
Does this issue still occur for either of you? If so, could you send a Spark report following the steps above?

**Comment by Chew** [comment]
No response in over a month. If this does still occur, please feel free to reply or make a new issue. Thank you for reporting!

**Comment by XboxBedrock** [comment]
This issue is the same as in #2421  so basically resolved
