### ISSUE TITLE
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer.

### ISSUE THREAD

**Issue by Cosnas1707** [GeyserMC/Geyser#2298]
### Describe the bug

java players have no issue, joining the server and playing. Bedrock players connect for a second, and then they are kicked and given the (io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer.) screen.
![Capture 4](https://user-images.githubusercontent.com/86142335/122633763-7b005780-d0da-11eb-9f63-2a2e0f22547f.PNG)

### To Reproduce

have a bedrock account join the server.

### Expected behaviour

find and fix the issue.

### Screenshots / Videos

![Capture5](https://user-images.githubusercontent.com/86142335/122633867-15609b00-d0db-11eb-8ca8-7bbeb600d166.PNG)
 This is from the Server console when a bedrock player tries to join, and then gets kicked. 

### Server Version and Plugins

Geyser-Spigot
Floodgate
Game version: 1.17

SERVER PLUGINS
-AngelChest Free
-HyperSleep
-Harbor-A Sleep Enhancement Plugin!

### Geyser Dump

https://dump.geysermc.org/x2jY9HwI4tgpimp4Z7TlaSI33bI5xbT3

### Geyser Version

Geyser-Spigot v1.4.0-SNAPSHOT

**Comment by Camotoy** [comment]
"If you want to share your logs while keeping your IP addresses private, use https://mclo.gs/ and give us the link after you saved it. Logs can be found in the `logs` folder on your server."

Please attach a full log with this happening. You cut off the important part of the error.

**Comment by Cosnas1707** [comment]
https://mclo.gs/s9fXQaK

**Comment by Konicai** [comment]
Those logs don't contain the error, please have a bedrock player join, then get the logs and reshare them

**Comment by Cosnas1707** [comment]
> Those logs don't contain the error, please have a bedrock player join, then get the logs and reshare them

https://mclo.gs/HF076e7

**Comment by Konicai** [comment]
Delete all of the `.pem` files. Let floodgate regenerate a new `key.pem`. Don't copy it into the Geyser-Spigot folder; there should be no `.pem` files there. Make sure that in the geyser config, `floodgate-key-file` is set to `key.pem`

If you have any questions or need help following those instructions please ask in the Geyser discord https://discord.gg/geysermc/

**Comment by Cosnas1707** [comment]
Thank you,

Konicai & Camotoy.
Wish you both the best.
