### ISSUE TITLE
Add Miniature Pets Plugin Support

### ISSUE THREAD

**Issue by tyepavitt** [GeyserMC/Geyser#2300]
### What feature do you want to see added?

Add miniature pets plugin support so it shows the pets correctly rather than showing default heads, as shown below:
![image](https://user-images.githubusercontent.com/35017430/122645792-0c3ff000-d114-11eb-8d55-af3f327de217.png)

### Are there any alternatives?

I haven't tried any.

**Comment by Camotoy** [comment]
This is a limitation already documented by #782, so I will close this issue.

Thank you anyway!
