### ISSUE TITLE
Bedrock players can't open or see powered beacons with a block that has the tag "beacon_base_blocks"

### ISSUE THREAD

**Issue by ExDrill** [GeyserMC/Geyser#2301]
### Describe the bug

Bedrock players cannot open a beacon or see a powered beacon beam whenever the block that is fuelling it is a block that has the tag "beacon_base_blocks". This only applies to blocks that don't have the tag in vanilla.

### To Reproduce

1. Create a datapack that gives a block aside from the vanilla ore blocks the tag "beacon_base_blocks"
2.  Join a Geyser server on a Bedrock Client
3. Make a beacon with the blocks added in the datapack

### Expected behaviour

The beacon should have a beam on the bedrock client and should be open-able.

### Geyser Dump

https://dump.geysermc.org/AaSl0ZuyPyQSkxI3SrMsdgsSpwmJFygM

### Geyser Version

1.4.0-SNAPSHOT (git-master-cc2d26d)

### Minecraft: Bedrock Edition Version

1.17.0

**Comment by Camotoy** [comment]
This is probably a Bedrock limitation - it relies on the beacon location to ensure that it is a valid beacon. I will leave this open as more research is needed.

**Comment by Konicai** [comment]
When you say beacon location do you mean just the beacon block, or also the blocks under it?

**Comment by Camotoy** [comment]
Both.

**Comment by Matt2021-A** [comment]
This issue still persists - Server is Paper 1.18 build #185 running Geyser-Spigot.jar 2.0.0 Snapshot Build #1017 with Floodgate-Spigot.jar 2.1.0 Snapshot Build #63

**Comment by onebeastchris** [comment]
This is unfortunately a can't be fixed as beacon base blocks are hardcoded on Bedrock :/

**Comment by Julmik647** [comment]
I have idea to use some custom UI, for example chest based UI that has same features as beacon UI for datapacks like this.
