### ISSUE TITLE
Geyser wont start on server

### ISSUE THREAD

**Issue by BrenBoy1506** [GeyserMC/Geyser#2303]
### Describe the bug

I downloaded the latest version of geyser as of writing this, I removed all other plugins other than geyser on the server, and i ran a /restart but it always gave me an error and wont host anything to bedrock edition. (Logs included below)

### To Reproduce

Install geyser on the spigot version:

Craftbukkit version 3149-Spigot-101ebb6-9122f5a (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

Thats all it took.

### Expected behaviour

Geyser would start on my server and allow bedrock to connect as intended.

### Screenshots / Videos

https://mclo.gs/bDhVEOw

### Server Version and Plugins

Only geyser

Craftbukkit version 3149-Spigot-101ebb6-9122f5a (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

### Geyser Dump

Geyser doesnt start

### Geyser Version

1.4.0 SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17

**Comment by Camotoy** [comment]
Try redownloading Geyser.

**Comment by BrenBoy1506** [comment]
I downloaded the latest version from https://ci.opencollab.dev//job/GeyserMC/job/Geyser/job/master/ and still get the same error as in the log

**Comment by Camotoy** [comment]
I just checked for the existence of that class and it's definitely there. Try deleting Geyser, starting up the server to ensure it was deleted, redownloading and re-applying.

**Comment by BrenBoy1506** [comment]
will do

**Comment by BrenBoy1506** [comment]
https://mclo.gs/KFlYQv4
New error arises

**Comment by Camotoy** [comment]
Yeah, however you're uploading plugins is borked. I'm afraid there's nothing we can do here - you just need to... upload your plugins better, or find an alternate way to get our jarfile onto your server.

**Comment by BrenBoy1506** [comment]
I'm going through filezilla. And it has worked fine in 1.16.5

**Comment by Konicai** [comment]
`Caused by: java.util.zip.ZipException: invalid CEN header (bad entry name)` indicates the file is just borked
