### ISSUE TITLE
passthrough-protocol-name not working

### ISSUE THREAD

**Issue by KolakZ** [GeyserMC/Geyser#2304]
### Describe the bug

I have `passthrough-protocol-name` enabled in my Geyser-Bungeecord config. But, it's not working. When I ping the server using https://mcsrvstat.us on Java edition, it says https://imgur.com/a/bCOe60u. But when I ping the server using https://mcsrvstat.us on Bedrock edition, it says https://imgur.com/a/wGupU2q.

### To Reproduce

Use a custom protocol for a BungeeCord server, and enable `passthrough-protocol-name` in the Geyser-Bungeecord config.

### Expected behaviour

I expected the protocol to be the same for Bedrock edition as it is on Java edition.

### Geyser Version

Build #725

**Comment by Camotoy** [comment]
`passthrough-protocol-name` was/is for the query system that PocketMine uses. You can see it when `Bedrock server` is not explicitly defined, under `map`: https://mcsrvstat.us/server/test.geysermc.org:19132 

Unfortunately, I will have to close this. The version string is also used when Bedrock clients ping the server, and it is required to be a string with only numbers and letters - this is not something we'd rather expose and potentially break Bedrock clients.

Thank you anyway for the report.
