### ISSUE TITLE
failed to connect to the world(i solved the problem)

### ISSUE THREAD

**Issue by Nastalgist** [GeyserMC/Geyser#2305]
### Describe the bug

Can't log into the server from version 1 17 Bedrock edition. I go to the BungeeCord server and the error "Failed to connect to the world" appears.

### To Reproduce

Join to the server

### Expected behaviour

??

### Server Version and Plugins

1.12.2 PaperSpigot, Bungeecord 1.8-1.17

### Geyser Version

1.4.0 snapshot

### Minecraft: Bedrock Edition Version

1.17-1.17.1

**Comment by RednedEpic** [comment]
Please use the Discord for these kinds of issues going forward.
