### ISSUE TITLE
Unable to connect via bedrock on a server running on an Oracle VM.

### ISSUE THREAD

**Issue by MrChemistryCow** [GeyserMC/Geyser#2307]
### Describe the bug

A server made with the Oracle VM does not allow Bedrock Connections, even after directly copying the server files over to it. It repeats the error for both Floodgate and Geyser, saying "[06:53:11 WARN]: [Geyser-Spigot] en_ is not a valid Bedrock language.". This is the only discernable difference to my friend and I.

### To Reproduce

1. Create an Oracle VM (Ours uses 4 ARM cores, 24 GB of RAM, on Ubuntu 24.0 full.)
2. Install Paper 1.17 # 22 (Don't know if it is important, but included)
3. Install Geyser + Floodgate

### Expected behaviour

I was expecting to be able to connect to the server via bedrock and not get the error "[06:53:11 WARN]: [Geyser-Spigot] en_ is not a valid Bedrock language."

### Screenshots / Videos

![Screenshot (857)](https://user-images.githubusercontent.com/86220206/122719813-91fe9100-d223-11eb-8749-5c26267c0157.png)
![Screenshot (858)](https://user-images.githubusercontent.com/86220206/122719818-92972780-d223-11eb-9412-3ee386467170.png)

### Server Version and Plugins

/version: "This server is running Paper version git-Paper-"6dfe049" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are 1 version(s) behind"

/version Geyser-Spigot: "Geyser-Spigot version 1.4.0-SNAPSHOT"

/version floodgate: "floodgate version 2.0-SNAPSHOT"

All plugins:
DiscordSRV-build-1.23.0
ebackup-1.2.0
floodgate-spigot
Geyser-Spigot
orebfuscator-plugin-5.1.5
ProtocolLib

### Geyser Dump

https://dump.geysermc.org/xFerWl3p3cqDAL4zHRB6WUdNYl9SNtpP

### Geyser Version

1.4.0-SNAPSHOT

### Minecraft: Bedrock Edition Version

v1.17.0

**Comment by Camotoy** [comment]
The error you get is unrelated to any connection issue. I do know of one person who has gotten Oracle's VMs to work with Geyser, so I would just make sure there is no firewall getting in the way.

**Comment by MrChemistryCow** [comment]
Yup, that was it, thanks so much! Rookie mistake on my part, used to only having to port foward. Also do you know of a way I can keep my whitelist on while allowing bedrock players?

**Comment by Camotoy** [comment]
Floodgate has the `/fwhitelist` command you can use.

Glad that was it!
