### ISSUE TITLE
[BUG] Geyser networking issues

### ISSUE THREAD

**Issue by KolakZ** [GeyserMC/Geyser#2309]
### Describe the bug

After adding Geyser to my server, mobs suddenly teleport and there are a bunch of block-break delays that have been reported by many players which got fixed when I removed Geyser.

### To Reproduce

Not sure how to explain steps to reproduce this but I'd be happy to do any tests on my servers or provide server configs.

### Expected behaviour

I expect the mobs to have normal behavior and block-breaks without delays.

### Server Version and Plugins

Backend servers 1-4: `This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version`
Backend server 5: `This server is running CraftBukkit version 3159-Spigot-f773da8-887bc05 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)`

### Geyser Dump

https://dump.geysermc.org/d1rMps1CKJKoeUuPppp9hGskrgXXPwoy

### Geyser Version

Build #726

**Comment by Camotoy** [comment]
Try temporarily removing Floodgate?

**Comment by KolakZ** [comment]
Sorry, just realized and came here to make a follow up. It gets fixed when I remove Floodgate, not Geyser.
