### ISSUE TITLE
the text in the signs is not visible between platforms

### ISSUE THREAD

**Issue by dr03ramos** [GeyserMC/Geyser#231]
**how to reproduce**
1. in java, put a sign on a block
2. write some words
3. look to the block in bedrock and see no text

**how to reproduce, 2**
1. in bedrock, put a sign on a block
2. write some words
3. look to the block in java (or other bedrock client) and see no text

**Comment by LegacyGamerHD** [comment]
use paper spigot

**Comment by dr03ramos** [comment]
how can i do that?

**Comment by Heath123** [comment]
https://papermc.io/

**Comment by JuniorJPDJ** [comment]
What's the reason of this issue btw?

**Comment by Heath123** [comment]
This shouldn't be closed yet
