### ISSUE TITLE
Anvil visual duplication glitch

### ISSUE THREAD

**Issue by hydevdotbiz** [GeyserMC/Geyser#2311]
### Describe the bug

Anvil can duplicate item many time with book or same item

### To Reproduce

1) Any Item
2) Add any item at Anvil

### Expected behaviour

Most Player in my server can spam duplicate any item

### Screenshots / Videos

https://cdn.discordapp.com/attachments/613170125696270357/856777262787592214/VID-20210622-WA0028.mp4

### Server Version and Plugins

Paper 1.17 - Latest Build
Geyser Master - Latest Build
Floodgate - Latest Build

### Geyser Dump

https://dump.geysermc.org/jmnT3kt96oc4xCwVT77KxKQP3TK86sVH

### Geyser Version

Geyser Master #727

### Minecraft: Bedrock Edition Version

1.17.0

**Comment by waddon1** [comment]
Not 100%, but I'm pretty sure I saw this somewhere and it's a 1.17 vanilla bug that's fixed in 1.17.1 Pre Release 1

**Comment by Camotoy** [comment]
Do the items persist on relog? Otherwise, this is a visual bug.

**Comment by shoucandanghehe** [comment]
Same error

**Comment by Konicai** [comment]
Does this still occur with the latest Geyser?

**Comment by Konicai** [comment]
Let us know if you can still reproduce this
