### ISSUE TITLE
Bedrock player is invisible in the Server

### ISSUE THREAD

**Issue by hmjBill** [GeyserMC/Geyser#2313]
### Describe the bug

Describe the bug
Dear,

I updated geyser, floodgate, viaversion, viabackwards, and BungeeCord. The server is running 1.17 and bedrock players can join etc. But the problem is that java players can't see bedrock players, and even bedrock players can't see each other.

### To Reproduce

[23:48:40 WARN] [Geyser-BungeeCord]: Haven't received PlayerListEntry packet before spawning player! We ignore the player 8a2064ce-efdd-3334-9524-ba69bc513933

### Expected behaviour

Plz Fix it!
THANK YOU!

### Screenshots / Videos

 

https://user-images.githubusercontent.com/33179096/122963472-dec7a080-d3b8-11eb-9e1e-5c13b0e799ed.mp4

### Server Version and Plugins

This server is running Tuinity version git-Tuinity-"b12d0cc" (MC: 1.17), geyserbungee, viaversion, viabackwards, floodgate all are the latest versions

### Geyser Dump

https://dump.geysermc.org/9FvZGbngW2K84U1ErBOpgnKZmjxuCk1J

### Geyser Version

1.4.0-SNAPSHOT (git-master-65c52f9) (Java: 1.17, Bedrock: 1.17.0)

### Minecraft: Bedrock Edition Version

1.17

**Comment by Camotoy** [comment]
If Java players cannot see Bedrock players, then that is not something we touch (Java player experience is not affected by us). I'm closing this as it is very very likely not our issue, and rather likely something as a result of using not-ready-for-production server builds (even if not, it's not our issue and that error message is the reason Java players can't see you either).
