### ISSUE TITLE
sometimes bossbar is not displayed

### ISSUE THREAD

**Issue by artemzheglovds** [GeyserMC/Geyser#2316]
### Describe the bug

sometimes, if you go to another server from the lobby, the bossbar is not displayed.

### To Reproduce

1. Install Velocity
2. Install Geyser to velocity
3. Install floodgate 2.0 on each server
4. Make a lobby with a deluxemenus menu in it and connect via the menu to the server with the bossbar
5. Sometimes bossbar doesn't show up
6. I tried on a completely clean server - I got this problem there too.

Plugin I'm using: https://github.com/LeonTG/Timer

Also, bossbar may not appear when raiding in a village.

### Expected behaviour

the bossbar is always displayed when it exists

### Screenshots / Videos

Java:
![image](https://user-images.githubusercontent.com/65168490/123063974-8b843b00-d416-11eb-9840-028110695730.png)
Bedrock:
![image](https://user-images.githubusercontent.com/65168490/123063997-90e18580-d416-11eb-8a2f-b5fefc00aa7a.png)

### Server Version and Plugins

Latest Geyser, latest velocity, latest floodgate.

### Geyser Dump

https://dump.geysermc.org/l2i0vDLSd7ZnrqZNY3D3yatlaRlcfjJg

### Geyser Version

1.4.0-SNAPSHOT (git-master-65c52f9)

### Minecraft: Bedrock Edition Version

1.17.0

### Additional Context

it happens randomly.

**Comment by Jens-Co** [comment]
Hi there, are you still having problems with your bossBar ?

**Comment by Chew** [comment]
No response in a month. Additionally, there is not much we can do with such little information. This could easily be a Bedrock bug, but it's hard to say. Regardless, thank you for reporting.
