### ISSUE TITLE
Scoreboard causes bedrock client to crash

### ISSUE THREAD

**Issue by Sanluli36li** [GeyserMC/Geyser#2318]
### Describe the bug

I used a datapack that rotates the scoreboard on the server. every 15 seconds, the server will switch the score display
https://github.com/DGBCraft/DGBCraft-Custom/blob/master/datapacks/DGBCraft/data/dgbcraft_scoreboard/functions/install.mcfunction
https://github.com/DGBCraft/DGBCraft-Custom/blob/master/datapacks/DGBCraft/data/dgbcraft_scoreboard/functions/tick.mcfunction

When a player joins the server using the bedrock client, the client will crash after a while
I tried to disable this data packet and turn off the scoreboard display in the sidebar, and then played for dozens of minutes, the game was all normal

I tried to use `/scoreboard objectives setdisplay sidebar XXX` on bedrock to turn on the scoreboard, everything worked fine
Then I closed the scoreboard, and client crashed
It looks like some packets sent when executing the `/score board setdisplay` command cannot be processed by the client

### To Reproduce

1. use the `/scoreboard` command to create an objective
2. Let the scoreboard have some data
3. use the `/scoreboard objective setdisplay sidebar` command to switch it.
4. Try a few more times, not every time it will crash

### Expected behaviour

The scoreboard displays normally and rotates normally without crashing

### Screenshots / Videos

https://user-images.githubusercontent.com/5201743/123143481-39cac780-d48d-11eb-8de1-ff12fcf97aa2.mp4

### Server Version and Plugins

Velocity 1.1.5
Geyser version 1.4.0-SNAPSHOT (git-master-ca558fc)
floodgate use build 15
ViaVersion 4.0.0
ViaBackwards 4.0.0

Server is 1.16.5 with Fabric loader 0.11.3
with CarpetMod, Lithium, Phosphor, Servux
and datapack https://github.com/DGBCraft/DGBCraft-Custom/blob/master/datapacks/DGBCraft/

### Geyser Dump

https://dump.geysermc.org/UvmPxCVAG2HmuE3xKE6rS0uKsv5Llcwy

### Geyser Version

Geyser version 1.4.0-SNAPSHOT (git-master-ca558fc)

### Minecraft: Bedrock Edition Version

1.17.2

### Additional Context

At least, in the short term, is it possible to add an option to completely block the server’s scoreboard?

**Comment by Camotoy** [comment]
Could you please try https://github.com/GeyserMC/Geyser/pull/2078 and see if your issue is resolved?

To download a pull request (or a "PR") you need to:
1. Make sure you are signed in with a GitHub account
2. Follow the pull request link that was sent to you
3. Follow the guide on this picture
https://i.ibb.co/tCcB1Qp/PR1.png

**Comment by Sanluli36li** [comment]
> Could you please try #2078 and see if your issue is resolved?
> 
> To download a pull request (or a "PR") you need to:
> 
> 1. Make sure you are signed in with a GitHub account
> 2. Follow the pull request link that was sent to you
> 3. Follow the guide on this picture
>    https://i.ibb.co/tCcB1Qp/PR1.png

No, client still crashes when modify scoreboard

**Comment by Sanluli36li** [comment]
This pull provides a team scoreboard, and then I try to switch teams. At this time, the scoreboard is hidden and client crashes.

**Comment by Sanluli36li** [comment]
In fact, any attempt to close the client’s scoreboard will cause a crash

**Comment by Tim203** [comment]
Can you try the latest version of that PR?

**Comment by Sanluli36li** [comment]
It doesn't seem to work, the client still crashed when I closed the scoreboard

**Comment by Jens-Co** [comment]
> It doesn't seem to work, the client still crashed when I closed the scoreboard

Can you provide some logs of that error please?

**Comment by Jens-Co** [comment]
Any updates on this issue ? If not I will close this in a few days.

**Comment by Jens-Co** [comment]
Hello there, can you please upload the install.mcfunction and tick.mcfunction, im trying to replicate your setup but im not yet able to get things working.

**Comment by Sanluli36li** [comment]
All in here: https://github.com/DGBCraft/DGBCraft-Custom/tree/master/datapacks/DGBCraft/data/dgbcraft_scoreboard/functions

**Comment by Sanluli36li** [comment]
In fact, when I try to use the /scoreboard command to hide the scoreboard, it will crash

**Comment by Jens-Co** [comment]
Hello there, are you still having this issue on the latest Geyser build ?

**Comment by Konicai** [comment]
Let us know if you still experience this

**Comment by viciscat** [comment]
Hello! On my side i added a simple scorebord on the sidebar that displays the number of deaths, and my friend on xbox (he uses BedrockTogether) crashed while it was displayed. I am on aternos and I use the latest public version.
