### ISSUE TITLE
Bedrock Players can't render below bedrock making 1.18 Generation Datapack unusable.

### ISSUE THREAD

**Issue by AndysComing** [GeyserMC/Geyser#2319]
### Describe the bug

When using the official [1.18 world generation datapack](https://feedback.minecraft.net/hc/en-us/articles/4402614709389-Caves-Cliffs-Prototype-Data-Pack-for-Minecraft-Java-Edition) bedrock players can't see anything below bedrock except for an empty void.

### To Reproduce

1. Install the Caves & Cliffs Prototype Data Pack onto your server (https://feedback.minecraft.net/hc/en-us/articles/4402614709389-Caves-Cliffs-Prototype-Data-Pack-for-Minecraft-Java-Edition)
2. Join on bedrock and head to Y-Level 0.

### Expected behaviour

When you get there, you notice that everything below 0 is just void.

### Geyser Version

Geyser-Spigot v1.4.0-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.0

**Comment by Camotoy** [comment]
This is currently a Bedrock limitation, as stated in the README and as a warning in the console when you log into the server. Thank you anyway.

**Comment by Weirddudewastaken** [comment]
I got the same issue but the "1.18 world generation datapack" has been added to bedrock as a world generation setting (in bedrock) called "Caves and Cliffs". the bedrock version is 1.17.10 and the problem should be resolved but it isnt...
It still does the same thing even though the limitation has been removed, its stupid.

**Comment by Camotoy** [comment]
You are correct that we are able to utilize that, but it takes time and won't just magically work. Be patient, please!

**Comment by Weirddudewastaken** [comment]
I will wait because well what else am i supposed to do.

**Comment by cmod31** [comment]
please comment on it when its fixed i subscribed to this issue

**Comment by Camotoy** [comment]
For those who subscribed to the issue: the latest builds have a `extended-world-height` setting you can enable to allow this.
