### ISSUE TITLE
Steve skin locked on to character in Java

### ISSUE THREAD

**Issue by Jamtasty** [GeyserMC/Geyser#2322]
### Describe the bug

My friends and I installed geyser for my server so we can play crossplay, for some reason whenever i join my Minecraft skin lis locked to the default: Steve

### To Reproduce

1.just add geyser to a java server
2.skins don't work

### Expected behaviour

skin customization

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/86430289/123308782-b8555280-d4e9-11eb-88a2-34de3f95d4bb.png)

### Server Version and Plugins

![image](https://user-images.githubusercontent.com/86430289/123309018-023e3880-d4ea-11eb-830f-12a1150c12fb.png)

### Geyser Dump

https://dump.geysermc.org/dtaUHnIyjclabXHog4HwPkIZ430GmlzG

### Geyser Version

1.17

### Minecraft: Bedrock Edition Version

1.17

**Comment by Camotoy** [comment]
If all skins stopped working, it's because you set your server to offline mode. Re-enable online mode.
