### ISSUE TITLE
Standalone Passthrough Ping Doesnt Work in conjunction with HAProxy

### ISSUE THREAD

**Issue by CoreyShupe** [GeyserMC/Geyser#2323]
### Describe the bug

When enabling passthrough ping in any fashion while using a velocity proxy it does not work.

Tux (core velocity developer) said it's done in an incorrect way or doesn't properly send the correct ping data. This should be fixed.

### To Reproduce

1) enable passthrough ping for your standalone geyser instance
2) enable proxy-protocol (HaProxy)
3) point it to a velocity instance

### Expected behaviour

For the ping passthrough to work.

### Server Version and Plugins

Floodgate 2.0
Geyser - latest

### Geyser Version

1.4.0-SNAPSHOT

### Minecraft: Bedrock Edition Version

latest

### Additional Context

This was discussed amongst geyser devs and velocity devs and is a confirmed issue.

**Comment by Camotoy** [comment]
I'm unable to replicate with Geyser 742 on standalone. The forwarded message shows up correctly for me.

**Comment by Camotoy** [comment]
This should finally be fixed by 16bb79e.
