### ISSUE TITLE
Allow Passthrough Ping to Forward Host

### ISSUE THREAD

**Issue by CoreyShupe** [GeyserMC/Geyser#2324]
### What feature do you want to see added?

There should be more features with passthrough ping. It would be nice if there was an option to disable ping caching and forward pings directly so that:
`player -> geyser -> proxy` instead of `geyser <-> proxy` then `player -> geyser cache`

This would allow proper forced-host reading for ping information so that you could give different ping information based on the host.

### Are there any alternatives?

There doesn't seem to be any alternatives since the ping is force-cached.

**Comment by onebeastchris** [comment]
Seems like Bedrock isn't passing through the address it is pinging, which prevents us from implementing this feature (aka forward the address to get the correct motd. Sorry :/
