### ISSUE TITLE
Broken skins on bedrock with Java account linked

### ISSUE THREAD

**Issue by waddon1** [GeyserMC/Geyser#2326]
### Describe the bug

If a bedrock player with a linked java account logs in for a second time without the server restarting their skin breaks and the head displays the bedrock skin instead of the Java skin shown in image below.  This bug only occurs with floodgate enabled.

### To Reproduce

Link Java and Bedrock accounts
Join server twice

### Expected behaviour

Java skin is applied to bedrock player and it looks correct.

### Screenshots / Videos

https://imgur.com/a/Bj0zf0o

### Server Version and Plugins

This server is running Purpur version git-Purpur-1191 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: bdcea0e on HEAD)
25.06 16:42:59 [Server] INFO You are running the latest version
25.06 16:42:59 [Server] INFO Previous version: git-Purpur-1187 (MC: 1.17)

### Geyser Dump

https://dump.geysermc.org/HqQTWZ5RtsD3kyYwT6rKx3DPlVgMB8OV

### Geyser Version

732

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by waddon1** [comment]
Not sure if this is related,  but I just joined my server and the server console said "Got disconnected from the skin uploader: pings have to be at least 10 seconds apart"

**Comment by Tydium** [comment]
I can fill in. I can confirm that this bug does exist and is still on going.

**Comment by TrashyOne** [comment]
Confirming this bug when a friend joined a server of mine, just the torso is missing, only legs, floating arms and a floating head.

**Comment by MrZomka** [comment]
Up.

**Comment by Camotoy** [comment]
This *should* be fixed with https://github.com/GeyserMC/Floodgate/commit/0216b6d79821ef861445ff8cc7cdc0431d3e80f1.
