### ISSUE TITLE
Add an option to use bedrock's scoreboard like HUD for kill cooldown

### ISSUE THREAD

**Issue by hf02** [GeyserMC/Geyser#2327]
### What feature do you want to see added?

Bedrock has a scoreboard like HUD that Java doesn't have:

![image](https://user-images.githubusercontent.com/55464333/123466778-c4124900-d5bd-11eb-82c0-e44adbe75cef.png)
(screenshot from murder mystery on the hive)

Adding an option to have the kill cooldown appear there would be better because its bedrock exclusive. It won't override the subtitle or actionbar.

### Are there any alternatives?

Using 1.8 combat, or having it display as a subtitle or actionbar.

**Comment by Camotoy** [comment]
That is a resource pack overriding the scoreboard sidebar, so we can't do that without compromising the existing scoreboard system and providing a resource pack with that functionality. Thanks anyway!
