### ISSUE TITLE
Walking through bamboo is buggy

### ISSUE THREAD

**Issue by Plokie** [GeyserMC/Geyser#2328]
### Describe the bug

Walking through Bamboo, when a Bedrock client is connected to a Java server, causes a lot of rubberbanding issues.

### To Reproduce

1. Connect to a 1.17 Geyser Java server running build 734 (1.4.0 SNAPSHOT) or below.
2. Find bamboo/bamboo forest
3. Try to walk in-between/brush past bamboo
4. Experience rubberbanding

### Expected behaviour

Expected behaviour: To talk between/past bamboo without rubberbanding, and experience movement akin to Java

### Screenshots / Videos

https://user-images.githubusercontent.com/80136737/123484960-19bc1500-d601-11eb-92f3-619a25977003.mp4

### Geyser Dump

https://dump.geysermc.org/KlscWyG9soTjgbaFJxpAaaXRkstj5ntD

### Geyser Version

Build 734 from Jenkins (1.4.0 SNAPSHOT i think?)

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by Camotoy** [comment]
This is documented as known on our limitations page. In the future, we may have an official way to fix this, but for now if you want a hacky solution: https://github.com/Camotoy/BambooCollisionFix/

Thank you anyway!
