### ISSUE TITLE
Glow squid animation not working (GeyserMC Plugin)

### ISSUE THREAD

**Issue by caleb9782** [GeyserMC/Geyser#2329]
### Describe the bug

The animation doesn't happen for the glow squid on GeyserMC bedrock, the animation plays in single player mode. (this was tested on mobile)

### To Reproduce

Open Minecraft on a phone,
Connect to server with the plugin, 
Spawn in a glow squid and watch as it has no animation, 
back out, and load up a single player world on the same device,
then spawn in a glow squid and watch.

### Expected behaviour

Expected behavior: Glow Squid should have animation. 

### Server Version and Plugins

1.17
Plugins: GeyserMC, Floodgate.

### Geyser Version

#734

**Comment by Camotoy** [comment]
I'm going to close this in favor of #230, which describes the same issue. Thank you anyway!
