### ISSUE TITLE
banners are not displaying correctly

### ISSUE THREAD

**Issue by dr03ramos** [GeyserMC/Geyser#233]
**Describe the bug**
banners collected by bedrock players are not displaying the correct color or pattern

**To Reproduce**
1. pick a banner with any pattern on java
2. drop it to a bedrock player
3. in bedrock, see that this banner is without patterns and have any other color
_part 2_
5. make the bedrock player put this banner in the world
6. note that the banner is different between java and bedrock

**Expected behavior**
same banner across platforms

**Screenshots**

**Server version**
1.15.2

**Geyser version**
most recent

**Bedrock version**
1.14.30

**Comment by RednedEpic** [comment]
Implemented in inventory branch.
