### ISSUE TITLE
Geyser couldn't make sure that the system clock is accurate

### ISSUE THREAD

**Issue by Skeagle137** [GeyserMC/Geyser#2330]
### Describe the bug

Whenever a bedrock player joins, this log is sent from both geyser and floodgate: 
`We couldn't make sure that your system clock is accurate. This can cause issues with logging in.` If 2-3 bedrock players are online, the server will start lagging and eventually all bedrock players (and _only_ the bedrock players) are kicked. The lag stops once they leave, and any java players that are online are unaffected (not sure if that is related to the system clock logs or another problem from geyser, but I assume so since it's strange that only the bedrock players are affected). I have checked and the time on my machine that the server runs on is synced (check screenshots), yet the error still persists. This only started happening to me when I updated my server to 1.17 as well.

### To Reproduce

- Download the latest snapshot of geyser and floodgate
- Connect a bedrock account to the server, which will display the log

### Expected behaviour

Bedrock players should be able to join as normal and not be kicked after some time.

### Screenshots / Videos

![error](https://user-images.githubusercontent.com/18729303/123514297-4c492a80-d660-11eb-9e72-742a0a160189.png)
![synced time](https://user-images.githubusercontent.com/18729303/123518286-34c76d00-d673-11eb-9d65-47c068813dc9.png)

### Geyser Dump

https://dump.geysermc.org/3T9HHpPNCumkplaSB80mRDlGpQg6hoCR

### Geyser Version

1.4.0-SNAPSHOT (git-master-495eafc)

### Minecraft: Bedrock Edition Version

1.17.0

**Comment by Camotoy** [comment]
Geyser and Floodgate currently sync up using Cloudflare's NTP server for additional security when logging in (when this fails, you get such an error message). It is very unlikely that is tied to lagging Bedrock players.

**Comment by Skeagle137** [comment]
Well, that's good to know I guess. Seems it might be another plugin that has issues with bedrock specifically, for some reason.

**Comment by Camotoy** [comment]
Could you please try the latest Geyser build?

**Comment by Skeagle137** [comment]
Using the latest build, the log still shows. I also confirmed the lag was from another plugin and not from geyser.

**Comment by YHDiamond** [comment]
What is the purpose of verifying system time?

**Comment by Tim203** [comment]
Preventing replay attacks

**Comment by PappoYT** [comment]
Geyser/Floodgate on PaperMC.

Since today bedrock players get this error when trying to enter the server:
```
24.07 16:12:50 [Server] WARN We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
24.07 16:12:50 [Server] WARN We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
```
They are spawned in nowhere.
Then they are logged out.

This is an example:
```
[14:12:50] [Network Listener - #1/INFO]: [Geyser-Spigot] Tentativo di accesso usando la modalit? floodgate... l'autenticazione sar? criptata.
[14:12:50] [epollEventLoopGroup-2-1/INFO]: [Geyser-Spigot] Samuele0079901 (loggato come: Samuele0079901) si ? connesso al server java in remoto all?indirizzo 172.17.0.5
[14:12:50] [epollEventLoopGroup-2-1/WARN]: [Geyser-Spigot] We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
[14:12:50] [Netty Epoll Server IO #3/WARN]: [floodgate] We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
[14:13:06] [Network Listener - #1/INFO]: [Geyser-Spigot] /79.49.91.244:50446 Ha provato a collegarsi!
[14:13:06] [Network Listener - #1/INFO]: [Geyser-Spigot] Un giocatore Bedrock con ip: /5.171.199.143 si ? disconnesso per CLOSED_BY_REMOTE_PEER
[14:13:06] [epollEventLoopGroup-2-1/INFO]: [Geyser-Spigot] Samuele0079901 si ? disconnesso dal server Java remoto sull'indirizzo 172.17.0.5 per il motivo: CLOSED_BY_REMOTE_PEER
```

Geyser and Floodgate are updated to latest build.
So PaperMC.
Here is the log file: [https://mclo.gs/NZnOfCo](https://mclo.gs/NZnOfCo)

Java players enter without any problem.

**Comment by DJelly4K** [comment]
> Geyser/Floodgate on PaperMC.
> 
> Since today bedrock players get this error when trying to enter the server:
> 
> ```
> 24.07 16:12:50 [Server] WARN We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
> 24.07 16:12:50 [Server] WARN We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
> ```
> 
> They are spawned in nowhere.
> Then they are logged out.
> 
> This is an example:
> 
> ```
> [14:12:50] [Network Listener - #1/INFO]: [Geyser-Spigot] Tentativo di accesso usando la modalit? floodgate... l'autenticazione sar? criptata.
> [14:12:50] [epollEventLoopGroup-2-1/INFO]: [Geyser-Spigot] Samuele0079901 (loggato come: Samuele0079901) si ? connesso al server java in remoto all?indirizzo 172.17.0.5
> [14:12:50] [epollEventLoopGroup-2-1/WARN]: [Geyser-Spigot] We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
> [14:12:50] [Netty Epoll Server IO #3/WARN]: [floodgate] We couldn't make sure that your system clock is accurate. This can cause issues with logging in.
> [14:13:06] [Network Listener - #1/INFO]: [Geyser-Spigot] /79.49.91.244:50446 Ha provato a collegarsi!
> [14:13:06] [Network Listener - #1/INFO]: [Geyser-Spigot] Un giocatore Bedrock con ip: /5.171.199.143 si ? disconnesso per CLOSED_BY_REMOTE_PEER
> [14:13:06] [epollEventLoopGroup-2-1/INFO]: [Geyser-Spigot] Samuele0079901 si ? disconnesso dal server Java remoto sull'indirizzo 172.17.0.5 per il motivo: CLOSED_BY_REMOTE_PEER
> ```
> 
> Geyser and Floodgate are updated to latest build.
> So PaperMC.
> Here is the log file: https://mclo.gs/NZnOfCo
> 
> Java players enter without any problem.

I have this problem too

**Comment by Tim203** [comment]
Can you run `/floodgate firewall` to see if it should be working properly?

**Comment by OblogDesign** [comment]
> Можете ли вы побежать `/floodgate firewall`посмотреть, должно ли оно работать правильно?

[12:27:25] [Thread-2191/INFO]: Testing global api...
> [12:27:25] [Thread-2191/INFO]: Was able to connect to global api!
> [12:27:25] [Thread-2191/INFO]: Testing time sync...
> [12:27:31] [Thread-2191/INFO]: Failed to connect:
> [12:27:31] [Thread-2191/INFO]: java.lang.IllegalStateException: Failed to receive time offset
> [12:27:31] [Thread-2191/INFO]: at org.geysermc.floodgate.command.main.FirewallCheckSubcommand.lambda$timeSyncCheck$2(FirewallCheckSubcommand.java:83)
> [12:27:31] [Thread-2191/INFO]: at org.geysermc.floodgate.command.main.FirewallCheckSubcommand.lambda$executeFirewallText$3(FirewallCheckSubcommand.java:92)
> [12:27:31] [Thread-2191/INFO]: at org.geysermc.floodgate.command.main.FirewallCheckSubcommand.lambda$executeChecks$4(FirewallCheckSubcommand.java:111)
> [12:27:31] [Thread-2191/INFO]: at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
> [12:27:31] [Thread-2191/INFO]: at java.base/java.lang.Thread.run(Thread.java:831)
> [12:27:31] [Thread-2191/INFO]:
> [12:27:31] [Thread-2191/INFO]: The checks have finished. 1/2 were successful

**Comment by tomikcz987** [comment]
> 
> 
> > Можете ли вы побежать `/floodgate firewall`посмотреть, должно ли оно работать правильно?
> 
> [12:27:25] [Thread-2191/INFO]: Testing global api...
> 
> > [12:27:25] [Thread-2191/INFO]: Was able to connect to global api!
> > [12:27:25] [Thread-2191/INFO]: Testing time sync...
> > [12:27:31] [Thread-2191/INFO]: Failed to connect:
> > [12:27:31] [Thread-2191/INFO]: java.lang.IllegalStateException: Failed to receive time offset
> > [12:27:31] [Thread-2191/INFO]: at org.geysermc.floodgate.command.main.FirewallCheckSubcommand.lambda$timeSyncCheck$2(FirewallCheckSubcommand.java:83)
> > [12:27:31] [Thread-2191/INFO]: at org.geysermc.floodgate.command.main.FirewallCheckSubcommand.lambda$executeFirewallText$3(FirewallCheckSubcommand.java:92)
> > [12:27:31] [Thread-2191/INFO]: at org.geysermc.floodgate.command.main.FirewallCheckSubcommand.lambda$executeChecks$4(FirewallCheckSubcommand.java:111)
> > [12:27:31] [Thread-2191/INFO]: at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
> > [12:27:31] [Thread-2191/INFO]: at java.base/java.lang.Thread.run(Thread.java:831)
> > [12:27:31] [Thread-2191/INFO]:
> > [12:27:31] [Thread-2191/INFO]: The checks have finished. 1/2 were successful

I have the same problem with time. I added geyser to bungee and couldn't connect with bedrock.

**Comment by Tim203** [comment]
Looks like your firewall is blocking `time.cloudflare.com` UDP port `123`

**Comment by tomikcz987** [comment]
> 
> 
> Looks like your firewall is blocking `time.cloudflare.com` UDP port `123`

My firewall is not blocking outgoing connections to cloudflare

**Comment by Tim203** [comment]
Then you shouldn't get that message ^^

**Comment by SwirlClinic** [comment]
I’m also having this issue with a clean install of paper, geyser and floodgate on a pterodactyl game panel install

**Comment by Tim203** [comment]
This is an issue related to your firewall. Geyser and Floodgate try to connect to `time.cloudflare.com` (UDP port 123), and when Geyser/Floodgate aren't able to get the time from Cloudflare that error will pop up

**Comment by Baterka** [comment]
It seems like my problem is purely hosting based... I tested it on different and it is working... Sorry.

**Comment by Camotoy** [comment]
I'm closing this as that error will soon be irrelevant.
