### ISSUE TITLE
Bridge at y=1 entering new chunk freezes

### ISSUE THREAD

**Issue by AxlRose-RX** [GeyserMC/Geyser#2332]
### Describe the bug

When at the End dimension on y=1 making a bridge and as soon as player moves to the next chunk it freezes him

### To Reproduce

1. Go to the end at y=1 and start a bridge as you bridge into the next chunk it freezes the game

### Expected behaviour

Should not freeze the bedrock player

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/10159672/123573832-ae0eaf00-d79c-11eb-8afe-7fd3ea7d07ca.png)

### Server Version and Plugins

This server is running Purpur version git-Purpur-1204 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: b4e0fc7 on HEAD)
Geyser Build #736 (Jun 27, 2021, 11:58:22 PM)

Plugins (39): AuctionHouse, BossBarMessage*, BungeeTabListPlus, Chunky, ChunkyBorder, Citizens, CMILib, CoreProtect, DeluxeMenus, DiscordSRV, Essentials, EssentialsSpawn, FeatherBoard, floodgate, GriefPrevention, GSit, HeadDatabase, HolographicDisplays, InventoryRollbackPlus, Jobs, LuckPerms, mcMMO, MineSync, MobHeads, OpenInv, PlaceholderAPI, ProtocolLib, Quests, ShopGUIPlus, ShopGUIPlus-SellGUI, SkinsRestorer, Spartan, Vault, VentureChat, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

https://dump.geysermc.org/iO0TPJXuHgCoOYw4qGIlGCCIH3Bho7MJ

### Geyser Version

1.4.0-SNAPSHOT (git-master-215ffc6)

### Additional Context

https://timings.pl3x.net/?id=b0baa3c3c80e4b34a0113aa823b35231

**Comment by Camotoy** [comment]
Is this still an issue with the latest Geyser build?

**Comment by Konicai** [comment]
Let us know if this still occurs and this can be reopened
