### ISSUE TITLE
Boat glitch

### ISSUE THREAD

**Issue by timr2000** [GeyserMC/Geyser#2337]
### Describe the bug

Once in a Boat, after 2 or 3 seconds you get kicked out of the Boat. Doesnt matter if you move or not. You got kicked out of the Boat.

### To Reproduce

1. Just enter a boat, and it'll kick you out of it after a few seconds

### Expected behaviour

it shouldnt kick users out of their boat.

### Screenshots / Videos

https://www.youtube.com/watch?v=QpxItldpsuo

### Server Version and Plugins

Server version: Purpur build 1051 1.16.5
Viaversion: 4.0.0

### Geyser Version

Geyser version: 1.4.0 Build 735

### Minecraft: Bedrock Edition Version

1.17.0

**Comment by Konicai** [comment]
Hi, can you please provide a geyser dump? 

Also, is this issue still happening?

**Comment by timr2000** [comment]
> Hi, can you please provide a geyser dump?
> 
> Also, is this issue still happening?

Hello, for some reason this has been solved, probably an plugin conflicting. Im sorry for not closing. Has been solved for me!
