### ISSUE TITLE
Your nickname is invalid

### ISSUE THREAD

**Issue by ElMoha943** [GeyserMC/Geyser#2338]
### Describe the bug

Geyser kicks every bedrock player with reason "Your nickname is invalid, remove spaces, symbols, and invalid characters from your name."

example
`[Geyser-Spigot] VoicingPuma2475 has disconnected from remote Java server on address 172.18.0.20 because of ` It should be a valid nickname...

### To Reproduce

Join the server from bedrock with any name.

### Expected behaviour

It should let players join if the username is valid.

### Screenshots / Videos

![Uploading image.png…]()

### Server Version and Plugins

Paper version git-Paper-64 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 333cc2e)

Plugins:
- EssentialsX
- LuckPerms
- Vault
- nLogin
- DiscordSRV

### Geyser Dump

Paper version git-Paper-64 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 333cc2e)

### Geyser Version

Geyser version 1.4.0-SNAPSHOT (git-master-afc1f48) (Java: 1.17, Bedrock: 1.17.0)

**Comment by Camotoy** [comment]
Seeing as you have the `nLogin` plugin, that is likely your issue. You will need to modify its configuration to allow `.` at the beginning of names, or remove the prefix from your Floodgate config. [Or even better, switch to online mode! :O ]

Closing as this isn't an issue on our end. Thank you anyway.
