### ISSUE TITLE
creative inventory is empty

### ISSUE THREAD

**Issue by dr03ramos** [GeyserMC/Geyser#234]
**Describe the bug**
the creative inventory have nothing on bedrock

**To Reproduce**
1. open the map in bedrock
2. open the inventory
3. See error

**Expected behavior**
inventory showing all items/blocks and these items can be picked up

**Screenshots**
![Screenshot_20200322-082222_Minecraft](https://user-images.githubusercontent.com/50461210/77248249-bfbaeb80-6c16-11ea-99ec-a2a70f2574fb.jpg)

**Server version**
1.15.2

**Geyser version**
most recent

**Bedrock version**
1.14.30

**Additional context**
these items in my hotbar was given by other players

**Comment by TheMasterBlaster** [comment]
Use the Inventory branch.

**Comment by dr03ramos** [comment]
how can i use that?

**Comment by endevrr** [comment]
Download from here: https://ci.nukkitx.com/job/Geyser/job/inventory/

**Comment by dr03ramos** [comment]
ok, apparently it's not a geyser bug :)
