### ISSUE TITLE
Teleport End <-> Nether

### ISSUE THREAD

**Issue by AxlRose-RX** [GeyserMC/Geyser#2342]
### Describe the bug

Game crashes for Bedrock players when they teleport now from Nether to The End or The End to Nether.

This does not happen when they teleport from overworld to those dimensions.

This happens when an OP teleports them, when they teleport with /tpa, /home, or even Bedrock OPs

### To Reproduce

1. Go to the Nether
2. Teleport to The End dimension or the other way around

### Expected behaviour

should just teleport but crashes the game

### Server Version and Plugins

It happens on my 1.16 and 1.17 survivals

git-Purpur-1204 (MC: 1.17) build #1215 and also on my Purpur 1.16

### Geyser Dump

https://dump.geysermc.org/iyIsR6eyrQNzDILVVmWb8OrKPJrhVaBR

### Geyser Version

1.4.0-SNAPSHOT (git-master-b757032)

### Minecraft: Bedrock Edition Version

1.17.2 (latest)

### Additional Context

https://timings.pl3x.net/?id=41c1ff94680c4b08ba3f8646365cec6f

**Comment by Camotoy** [comment]
What does the crash look like? Does the game close or just stall on the same screen? (You can verify by shutting down the server - if the client returns to the menu after some time, it's just a stall)

**Comment by AxlRose-RX** [comment]
doesn't crash gets stuck on loading, I can teleport the affected player to overworld or to me
