### ISSUE TITLE
Timed Out when Geyser disconnect and stop proxy

### ISSUE THREAD

**Issue by MasqueOu** [GeyserMC/Geyser#2343]
### Describe the bug

Hello,

When I shut down my server with Geyser, the server timed out at each shutdown when Geyser shuts down and disconnects players, I have to force a shutdown of my instance and then restart the server.

Thanks to you,

### To Reproduce

Use Geyser and stop the server when bedrock player are connected.

### Expected behaviour

When I shut down my server with Geyser, the server timed out at each shutdown when Geyser shuts down and disconnects players, I have to force a shutdown of my instance and then restart the server.

### Screenshots / Videos

/

### Server Version and Plugins

This server is running Paper version git-Paper-60 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 4713937)
You are 6 version(s) behind
Previous version: git-Paper-46 (MC: 1.17)

### Geyser Dump

https://dump.geysermc.org/wyPEShErjcru84sRPE7wqZx4dMM1v3ND

### Geyser Version

1.4.0 SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.0

**Comment by Rick1029** [comment]
Same issue here. I've tested on the Fabric version and Spigot and shutting down / restarting will save the world then hang indefinitely. I have to kill the process manually. This happens regardless of whether players are online or not.

**Comment by RednedEpic** [comment]
This was likely due to a concurrency related issue which has since been resolved. Please open a new issue if this still occurs.
