### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by Cosmos9999** [GeyserMC/Geyser#2344]
### Describe the bug

When bedrock players attempt to connect, they join for a split second and then get this error:

io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer

Java players have no issues.

### To Reproduce

1. Attempt to connect to server
2. See if it works?

### Expected behaviour

I expected to connect to the server with no issues.

### Screenshots / Videos

![IMG_2115](https://user-images.githubusercontent.com/86790270/124144394-eabafe80-da59-11eb-8b69-876c9d7c82c6.PNG)

### Server Version and Plugins

floodgate-spigot, CoreProtect

### Geyser Version

Geyser-Spigot v1.4.0-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.2

### Additional Context

I also occasionally get "Connection Closed" when I attempt to connect.

**Comment by Cosmos9999** [comment]
I apologize that I can't get the full dump, but this is where the issue occurred: https://mclo.gs/GjUJ3GE

**Comment by Camotoy** [comment]
Shut down your server, delete all key files in the `floodgate` and `Geyser-Spigot` folders, and then start your server back up.

**Comment by Cosmos9999** [comment]
Can you be more specific on "Key files?"

**Comment by Camotoy** [comment]
Any file that contains the word `key`.

**Comment by Cosmos9999** [comment]
All right, thanks

**Comment by Cosmos9999** [comment]
I tried this, same error occurred.

**Comment by Cosmos9999** [comment]
Never mind, we took care of it

**Comment by WaowMand** [comment]
> Never mind, we took care of it

What did you do to fix it?

**Comment by Cosmos9999** [comment]
We just didn’t delete all key files when we thought we did. Our mistake.

**Comment by WaowMand** [comment]
> We just didn’t delete all key files when we thought we did. Our mistake.

Are there other key files than the ones in the "floodgate" and "Geyser-Spigot" folder called "key.pem"?

**Comment by Cosmos9999** [comment]
I honestly do not know the specifics, but I do know we had issues with the key when we were originally installing it, and I'm guessing that had an impact on it.
