### ISSUE TITLE
MacOS: Server crashes with the geyser plugin installed

### ISSUE THREAD

**Issue by Temder** [GeyserMC/Geyser#2345]
### Describe the bug

This bug is a crash that happens every time the server is started on Mac OS X with the geyser plugin. The crash happens when the server is enabling the geyser plugin. It crashes with the error message: "dyld: lazy symbol binding failed: Symbol not found: _clock_gettime".

### To Reproduce

1. Open the directory your server is in on an Macbook.
2. Start the server with the geyser plugin installed in the plugins folder.
3. The server is crashing when enabling the geyser plugin.

### Expected behaviour

I expected the server to start without a crash.

### Screenshots / Videos

![crash](https://user-images.githubusercontent.com/57451447/124177830-0dc4cd00-dab1-11eb-9697-3b7532a49d9e.png)

### Geyser Version

1.4.0-SNAPSHOT (git-master-7ae27c7)

### Additional Context

In this file is more detailed information about the error:
[message.txt](https://github.com/GeyserMC/Geyser/files/6750223/message.txt)

**Comment by Konicai** [comment]
Please provide a geyser dump, as the template asks

**Comment by Temder** [comment]
I can not because the server crashes on startup

**Comment by Konicai** [comment]
sorry not a smart moment for me lmao

**Comment by Temder** [comment]
it is not a problem

**Comment by Chew** [comment]
Can't reproduce with `System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9) Host: Mac OS X 11.4 (x86_64)`

![image](https://user-images.githubusercontent.com/8278263/124179567-a25f0900-da78-11eb-967f-58874e70146c.png)

What version of macOS are you on?

**Comment by Chew** [comment]
Also, try `xcode-select --install` in a terminal.

**Comment by Temder** [comment]
the macOS version is in the message.txt file in additional  context

**Comment by Chew** [comment]
Closing due to no response from my suggestion, if running `xcode-select --install` please reply and we can re-open.
