### ISSUE TITLE
Hunger bar on death

### ISSUE THREAD

**Issue by KattaHimaVamsi** [GeyserMC/Geyser#2347]
### Describe the bug

Hunger bar on death sometimes does not  get refilled

### To Reproduce

1. First type /kill with a partially full hunger bar
2. Respawn 
3. Check hunger bar
4. Repeat until the bug happens (it is fairly common and happens most of the time) 

### Expected behaviour

The bar will still be the same and not full

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/76478107/124306886-a24c2f80-db84-11eb-836b-160c7b329f36.png)

### Geyser Dump

https://dump.geysermc.org/MEfY6VETyU73UO8QgTDja6t71ccJFgL1

### Geyser Version

1.4.0-SNAPSHOT (git-master-7ae27c7)

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by Camotoy** [comment]
I find myself unable to replicate this on Paper 1.17 build 69. 
Reproduction steps:
`effect give @s minecraft:hunger 1 255`
`kill @s`

**Comment by Jens-Co** [comment]
Hi there, any updates about this issue ? :)

**Comment by KattaHimaVamsi** [comment]
Update, this is a visual bug, after a couple seconds it resets the bar to full saturation again.

**Comment by Jens-Co** [comment]
Ill close this issue for now, Will be reopened if this issue reappears.
 thanks for the report!
