### ISSUE TITLE
Show Bedrock Players Java-Exclusive Enchantments

### ISSUE THREAD

**Issue by ProfessorPickles** [GeyserMC/Geyser#2348]
### What feature do you want to see added?

Show Bedrock players enchantments that are only available on Java Edition, such as Sweeping Edge. When I enchanted my sword with Sweeping Edge III on Java Edition, I relogged onto the server (with the same Mojang account) on Bedrock Edition and the enchantment did not show up on the sword.

### Are there any alternatives?

None?

**Comment by Camotoy** [comment]
As Sweeping Edge is the only (unless I'm very wrong) Java-only enchantment, we have an issue for this covered at #1741. Thank you anyway!
