### ISSUE TITLE
Crafting glitch

### ISSUE THREAD

**Issue by BeetGaming45** [GeyserMC/Geyser#2350]
### Describe the bug

When crafting items, it sometimes glitching (e.g. items placed on the columns getting switched by another item in a player inventory)

### To Reproduce

Just crafting any item on a crafting table and place the ingredients onto the columns

### Expected behaviour

No item switching glitches/player can craft normally without any item they placed getting switched with a random item in their inventory

### Screenshots / Videos

https://user-images.githubusercontent.com/79033198/124343426-e92a3b80-dbfd-11eb-8752-e51f18484b00.mp4

### Geyser Version

1.4.0-SNAPSHOT (git-master-7ae27c7)

### Minecraft: Bedrock Edition Version

1.17.1/1.17.2

**Comment by sta0003** [comment]
I have this same problem, my users are complaining as it being basically unplayable.

**Comment by Camotoy** [comment]
There was a similar crafting glitch that was fixed recently. Ensure you are updated.

**Comment by Jens-Co** [comment]
Hello there, is there any update on this issue ?

**Comment by T1murik** [comment]
reproduced on latest (1.4.1-SNAPSHOT git-master-e0e6605) version

**Comment by Yandura** [comment]
I can also confirm this is an issue in the current version

**Comment by Konicai** [comment]
Someone on Discord reported their issue was most similar to this report:

https://dump.geysermc.org/PoIucKNaksEfBDLy7tryjfOgpiMxdPfi
Video:
https://cdn.discordapp.com/attachments/613168464634576897/924299084821585940/Screenrecorder-2021-12-25-01-22-03-688_1.mp4

**Comment by spookymgmt** [comment]
Having a similar issue with the most recent jenkins build.

**Comment by Camotoy** [comment]
Please ensure you're using the absolute most recent; otherwise, send a Geyser dump.

**Comment by MacGyverBrasil** [comment]
I'm going through this too!!! Has anyone found a solution??

**Comment by Camotoy** [comment]
Please send a Geyser dump.

**Comment by Camotoy** [comment]
I can't replicate this on 1.18.2 on the latest Paper on mobile. Can you provide a video example or specific replication steps?

**Comment by Jens-Co** [comment]
Can you update this issue? If not I'll close this soon, thanks.

**Comment by Konicai** [comment]
Create a new issue if you appear to be experiencing this.
