### ISSUE TITLE
Villagers Face The Wrong Way on Bedrock Edition

### ISSUE THREAD

**Issue by ProfessorPickles** [GeyserMC/Geyser#2351]
### Describe the bug

Librarian Villagers in front of lecterns sometimes face backwards or sideways. They even do the animation of looking down at the lectern, even though it is behind them. It doesn't happen all the time.

### To Reproduce

Have a trading hall with librarian villagers in front of lecterns

Enter the room that they are in with a Bedrock client.

If they aren't showing the bug, disconnect and reconnect with the Bedrock client.

### Expected behaviour

Villagers should face the lectern that they work at, not backwards or sideways.

### Screenshots / Videos

Bedrock

![Minecraft 7_2_2021 10_08_51 PM](https://user-images.githubusercontent.com/68560517/124343762-ec341600-db82-11eb-9410-f3ecfe1c79bb.png)

Java

![image](https://user-images.githubusercontent.com/68560517/124343856-9613a280-db83-11eb-87ad-5cdf151e57fd.png)

### Server Version and Plugins

This server is running Paper version git-Paper-778 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 1 version(s) behind

### Geyser Dump

https://dump.geysermc.org/5OYrqSjYS02xV3gq5dnF1kkC99kYu19T

### Geyser Version

Geyser version 1.4.0-SNAPSHOT (git-master-b757032) (Java: 1.17, Bedrock: 1.17.0)

### Minecraft: Bedrock Edition Version

1.17.2

### Additional Context

Sorry, I don't know how to remove HUD from Bedrock Edition.
Also I asked about this in the Discord server and they directed me here.

**Comment by RednedEpic** [comment]
Stale. Please open a new issue w/ updated repro steps if this still occurs.
