### ISSUE TITLE
Doesn't Work on Sponge API-8

### ISSUE THREAD

**Issue by np22-jpg** [GeyserMC/Geyser#2353]
### Describe the bug

Plugin is simply not recognized on a server running API-8, though the documentation on Sponge seems sparse.

I'm using this specific commit of Sponge on SpongeVanilla
https://github.com/SpongePowered/Sponge/commit/5ce8e0dc329dc34353cdaaa2678dfe79f9688a71 

and I'm using this build of geyser
https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/744/ 

### To Reproduce

1. Download plugin
2. Compile/run Sponge
3. Shut down sponge, put plugin in "mods" folder
4. Observe Sponge ignoring the plugin

### Expected behaviour

The plugin should be recognized and loaded up.

### Server Version and Plugins

I didn't have any other plugins, logs here
[latest.log](https://github.com/GeyserMC/Geyser/files/6759359/latest.log)
Using "version" doesn't return anything.

### Geyser Version

1.4.0-SNAPSHOT (git-master-7ae27c7)

### Minecraft: Bedrock Edition Version

N/A

**Comment by Camotoy** [comment]
We plan on updating our Sponge module to API 8 around the time it's planned for release.
