### ISSUE TITLE
[Bug] Bedrock users randomly aren't able to connect.

### ISSUE THREAD

**Issue by Ryoyo2** [GeyserMC/Geyser#2354]
### Describe the bug

Bedrock-Players often can't connect and/or have to wait for a couple minutes before they can connect. It seems to happen at random. They will just be kicked with the message "This server requires you to connect with Velocity." I use modern forwarding on Velocity and I have Geyser and floodgate on both velocity, as well as paper (airplane) with send-floodgate-data: true because I need the api for BedrockPlayerManager. 

I should also note that I had the same issue with waterfall and BungeeGuard. In that instance it was BungeeGuard disconnecting players and letting them connect after waiting enough time and trying often enough.

Relevant server-log on disconnect:
https://mclo.gs/hdCgRdK

Velocity log:
https://mclo.gs/U4k5aV1

### To Reproduce

1. Attempt to connect to server with bedrock edition of Minecraft.
2. Get kicked out with message "This server requires you to connect with Velocity."
3. Wait a couple minutes and try again.
4. Connect without issues.

### Expected behaviour

Bedrock players can connect normally without being kicked or having to wait.

### Screenshots / Videos

https://www.youtube.com/watch?v=zzILy_9vjmA

### Server Version and Plugins

git-airplane-9 (MC: 1.16.5)
velocity 1.18

### Geyser Dump

https://dump.geysermc.org/JaFpMtjsnTo9wQUbKZcZaBHqZzD91Lct

### Geyser Version

1.4.0-SNAPSHOT (git-master-7ae27c7)

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by Camotoy** [comment]
What plugins do you have on your backend?

**Comment by Ryoyo2** [comment]
It's...quite a lot. I haven't yet gone through a binary search, although I can probably do that soon.

`Plugins (88): AcceptTheRules*, AdvancedHelp, ajLeaderboards, AngelChest, AntiSeedCracker, ArtMap, Auto-Tune, BedrockPlayerManager, BetterPortals, BetterSleeping3, Brewery, BuildBattle, BungeeGuard, BuyRegion, Celeste, ChatControl, Chunky, ChunkyBorder, Citizens, CitizensGUI, CoreProtect, CustomJoinMessages*, DailyRandomShop, DeathMessagesPrime, DiceFurniture, DiscordSRV, DMPInventoryPlayerInfo, DMPMonitorCompat, DMPPlaceholderAPI*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, floodgate, FurnitureLib, Geyser-Spigot, GSit, HeadDatabase, HolographicDisplays, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollback, InvisibleItemFrames, JetsAntiAFKPro, LightAPI, LuckPerms, LWC, LWCTrust, Matrix, MobFarmManager, MovingDevApi, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MusicBox, NoteBlockAPI, OpenInv, OpToggle*, Parkour, PermissionShopZ, PlaceholderAPI, PremiumVanish, ProtectionLib, ProtocolLib, PyroFishingPro, PyroWeatherPro, RainbowsPro, ShareCoordinates*, Shop, SilkSpawners, spark, TAB, TabuuCore, TeleCraft, TetrisFriends, TogglePvp*, TouchscreenHolograms, UltimateFireworks, Vault, ViaVersion, Vivecraft-Spigot-Extensions, WanderingTrades, WorldEdit, WorldGuard, zAuctionHouse-Discord, zAuctionHouseV3`

**Comment by Camotoy** [comment]
One thing I can see right away is that Geyser-Spigot is not needed on the backend server. Other than that, a binary search would be a good idea.

**Comment by Camotoy** [comment]
I also see BungeeGuard, so I wonder if there's some issue there. Maybe see if switching to modern forwarding fixes your issue?

**Comment by Ryoyo2** [comment]
I've just gone through that list myself as well and you're completely right. I have forgotten a handful of things after swapping to velocity yesterday. I'll be deleting BungeeGuard, Vivecraft-Spigot-Extensions and Geyser-Spigot. I'm already on modern forwarding, but I've forgotten to get rid of BungeeGuard on the backend (see description). I'll report back after restarting and testing with the plugins removed.

**Comment by Ryoyo2** [comment]
Issue persists with these plugins removed.

**Comment by Ryoyo2** [comment]
It _seems_ like the issue has been fixed by removing the plugins, updating all other plugins (some of which apparently resolved compatibility issues with viaversion) and regenerating and refilling the geyser config. I will close this for now as I believe the issue is fixed.

**Comment by ThiagoSolfo** [comment]
I'm having the same issue with the latest version of Velocity and Geyser

Velocity [3.2.0 226] Plugins: floodgate-velocity, Geyser-Velocity, LuckPerms-Velocity-5.4.61, Remember.Me-1.2.3.

Hub plugins [Backend - Purpur 1.19.3 || v1913]: AuthMe, Citizens, DeluxeHub, FastAsyncWorldEdit (WorldEdit), floodgate, LuckPerms, PlaceholderAPI, spark, VoxelSniper

Geyser 2.1.0-SNAPSHOT (git-master-ee754c5)

**Comment by Camotoy** [comment]
Check your hosting/service provider to see if they have any special setup steps: https://wiki.geysermc.org/geyser/supported-hosting-providers/

If the issue still persists, please create a new issue. Thanks!

**Comment by ThiagoSolfo** [comment]
Thanks for the answer @Camotoy 

I followed the two additional steps and the problem persists (Oracle Cloud / OCI). I will open a new issue as you suggested
