### ISSUE TITLE
taking items from GUI menu (MyCommand)

### ISSUE THREAD

**Issue by kuraiskrap** [GeyserMC/Geyser#2355]
### Describe the bug

so this is very niche, and highly specific

so we have a plugin called MyCommand
basically lets you do sudo custom plugins easily
there's a issue where bedrock users are able to take items from the GUI's by swapping them with another item.
Means something isn't quite matching up in terms of java and bedrock, tried it with B~ and B. as prefixxes

### To Reproduce

i did it on mobile (effects consoles 2)
open a GUI in mycommand
tap an item so its highlighted
tap a 2nd item and it will throw one out of your inventory
get items from GUI

### Expected behaviour

shouldnt be able to get items from a GUI

### Server Version and Plugins

Server: Paper and spigot (effected multiple paper versions, tried newest spigot)
Bungeecord: Travertine (version 191 which is current, effected on multiple versions)
Geyser: Geyser 745 (effected multiple versions)

**plugins:** 
ViaVersion 
ViaBackwards 
FloodGate 
MyCommand 

**BungeeCord Plugins:** 
Geyser-BungeeCord
FloodGate-Bugeegee
ServerListMotd

### Geyser Dump

https://dump.geysermc.org/6cUT46eF9eriCKRR7H7AJ9S1HBdGGkjT

### Geyser Version

Geyser 745

### Minecraft: Bedrock Edition Version

1.17.0 (also effected 1.16.5) Mobile, Switch (fairly sure it effected other versions just unable to test during bug report)

### Additional Context

made a test server to narrow things down as best i can, if you need more details or access to anything i can help you out with that

**Comment by rtm516** [comment]
Can you try with either stock bungee cord or waterfall? Since Travertine is no longer supported by the paper devs.

**Comment by kuraiskrap** [comment]
just did it on both, the bug is still there
waterfall (newest) and bungeecord (newest) added ViaRewind (because we are still on 1.16.5)
and updated FloodGate to make sure it was current aswell

**Comment by Cal3y** [comment]
Have a same issue, I already posted about this to mycmd's owner. Couldn't figure much with mycmd myself, but I tested EssentialsX's "/invsee [player]" command, which uses similar chest gui menu and with assigned permission "essentials.invsee.preventmodify" (prevents picking up items even for op users on java). It works on pocket edition and any bedrock device I tested - you can't pick up or throw items on the ground. If someone can take a look at this, it would solve a lot actually, but I feel like this depends on how the plugin's gui menu is coded/implemented. For now I had to limit using gui menus and offer alternative chat-based commands for mobile users.

**Comment by RednedEpic** [comment]
Is someone able to provide a video of this?

**Comment by Konicai** [comment]
If anyone experiences this issue, a new and updated bug report can be made,
