### ISSUE TITLE
When enabling RTX the playermodel gets bugged

### ISSUE THREAD

**Issue by Peppershade** [GeyserMC/Geyser#2356]
### Describe the bug

When enabling any RTX resource pack on a Geyser server, the player model will not render properly. The parts that get swapped are mostly random and change after a relog on the server.

It seems that if you get out of the render distance of the broken skin and return, the skin is normal again.

The same resource packs are showing up normally on any other regular bedrock server.

Resource pack's I've tried:
- Kelly's RTX Vanilla conversion
- Vanilla RTX by Nicinator
- Homa RTX

### To Reproduce

Install any RTX pack on Minecraft Bedrock, make sure the RTX option is turned on, and join a Geyser server.

### Expected behaviour

A normal playermodel

### Screenshots / Videos

![NVIDIA_Share_K0uF4tJ0WJ](https://user-images.githubusercontent.com/7840625/124626168-b93d9b00-de7e-11eb-8ab7-43ff0b792a2a.png)
![NVIDIA_Share_CBg9g2I505](https://user-images.githubusercontent.com/7840625/124626171-ba6ec800-de7e-11eb-8d43-19ab286df19b.png)
![NVIDIA_Share_JkeFZZdG1J](https://user-images.githubusercontent.com/7840625/124626174-bb075e80-de7e-11eb-9122-9f3ea3b9e907.png)

### Server Version and Plugins

We're using a 1.17 BungeeCord build #1594 (latest)
We've also tested with Travertine, but no luck.

### Geyser Dump

We've made a dump with useful information, report your issue and provide this url: https://dump.geysermc.org/VmQxIls1m0CMTXOVjh23zoyJeU4Fuyis

### Geyser Version

Geyser Bungeecord build #745

### Minecraft: Bedrock Edition Version

1.17.2

### Additional Context

If you need me for testing RTX, my discord is Pepper#0666

**Comment by rtm516** [comment]
Seems like with the RTX resources enabled the geometry meshes are getting duplicated. It looks like it could be a bedrock bug but the fact it only happens on Geyser and not in single-player or partnered servers suggests otherwise.

**Comment by StarkyOficial** [comment]
From my experience, that's not a Geyser Bug, that's a vanilla bug from Bedrock. It happens everywhere, even on singleplayer.

**Comment by RednedEpic** [comment]
Very likely not a Geyser bug. Closing.
