### ISSUE TITLE
Outdated server 

### ISSUE THREAD

**Issue by 1812z** [GeyserMC/Geyser#2357]
### Describe the bug

spigot 1.17 lastest build
but if i use bedrock 1.17.2 enter this server,it shows "outdated server! im still on 1.17"
geyser version: jenkins build #746

### To Reproduce

lastest version[spigot and geyser]
everytime

### Expected behaviour

can enter with 1.17

### Screenshots / Videos

![}89OV939AGP~6{H)9L%)X9A](https://user-images.githubusercontent.com/61372168/124632203-b3fc4280-deb6-11eb-84ef-396865df5ad7.jpg)

### Server Version and Plugins

spigot1.17[lastest until now]
geyser #746 build

### Geyser Version

1.4.0-snapshot git-master-b407e8a

### Minecraft: Bedrock Edition Version

1.17.2

### Additional Context

Log:
0:02:52] [nioEventLoopGroup-2-1/INFO]: [Geyser-Spigot] ThreeSheep33029 因 Outdated server! Im still on 1.17 从远程Java服务器 192.168.1.173 断开
[00:02:52] [Network Listener - #1/INFO]: [Geyser-Spigot] 基岩版IP为: /192.168.1.214 的玩家因 CLOSED_BY_REMOTE_PEER 断开连接

**Comment by Chew** [comment]
Update your version of Geyser.

**Comment by Chuanwise** [comment]
I don't think it's a bug of geyser.

**Comment by kevinpro142** [comment]
![IMG-20220311-WA0058](https://user-images.githubusercontent.com/66867179/158006489-6f9dd6c0-da82-4548-abf7-db65bc508118.jpg)
It happened to me, but my Bedrock is 1.18.0 and the server is Java 1.18

**Comment by Chew** [comment]
Please see my above comment, and do not bump old issues. Please use [Discord](https://discord.gg/geysermc) if you need further assistance.
