### ISSUE TITLE
Support transfer to other BEDROCK servers (like BDS, NKX, PM4)

### ISSUE THREAD

**Issue by DJelly4K** [GeyserMC/Geyser#2359]
### What feature do you want to see added?

Just enter "/geyser transfer <ip> <port>" can transfer to other BEDROCK servers.
*(like a plugin on NukkitX)*
Can **be called by spigot plugins** *(such as ChestCommands, CommandNPC and so on)*

### Are there any alternatives?

None. I think.

**Comment by Camotoy** [comment]
Thank you for the feature request! Unfortunately, we have determined this is out of scope for our project. If you wish to use something like this, https://github.com/Camotoy/BedrockTransferPacketCommand is an option, though you likely have to compile it yourself.
