### ISSUE TITLE
Boats jump over mobs on Bedrock edition instead of being stopped by them

### ISSUE THREAD

**Issue by Garfieldwxg55** [GeyserMC/Geyser#2361]
### Describe the bug

I was testing my Nether highways on Bedrock edition, and I noticed a parity issue between the two versions. On Java edition, whenever I run into mobs on my nether highway, my boat is stopped and I have to either go around them or move my boat. On Bedrock edition however, the game tries to jump over the mobs and continue on the highway.

### To Reproduce

1. Ride on a nether highway that has not been mob-proofed
2. Run into some mobs (I found Zombie Piglins)
3. Notice that you don't stop and instead "drive" over them

### Expected behaviour

The boat should probably stop when it runs into mobs as it does on Java edition.

### Server Version and Plugins

Server Version: CraftBukkit Version 3172-Spigot-610a8c0-99561c2 (1.17.1)
Bungee Version: BungeeCord Version 1594
Plugins: BungeeServerSigns, LuckPerms, BambooCollisionFix, CustomBuckets, PlaceholderAPI, TAB-BukkitBridge, floodgate, Vault, ProtocalLib, Floodgate Placeholders, WorldEdit, Essentials, EssentialsProtect, EssentialsChat, TAB, JukeboxExtendedFork, EssentialsSpawn, WorldGuard, Citizens, MobHeads
Plugins (Bungee): AdvancedBan, BungeeResourcepacks, floodgate-bungee, Geyser-Bungeecord, LuckPerms-Bungee, TAB Bungee

### Geyser Dump

https://dump.geysermc.org/QNM206qgG4FG0NEpHANcSeZds7IhAuJb

### Geyser Version

1.4.0-SNAPSHOT (git-master-334e4fb)

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by RednedEpic** [comment]
Stale. Please open a new issue if this still occurs & if you have a video that would be amazing.
