### ISSUE TITLE
Mobs sometimes become invisible

### ISSUE THREAD

**Issue by CAT555502** [GeyserMC/Geyser#2362]
### Describe the bug

**With some chance, for example, a zombie can become invisible and beat the player. I noticed this on my server.**

### To Reproduce

**1. Spawn zombies.
2. Kill all zombies.
3. Switch to survival mode.
4. Die from invisible zombie.**

### Expected behaviour

**The zombie will become invisible to the Bedrock client and will attack, also it does not become visible after re-entering the game**

### Screenshots / Videos

**None**

### Server Version and Plugins

 This server using Paper version git-paper-90 (MC: 1.17.1) API Version: 1.17.1-R0.1-SNAPSHOT (git:bb44da8)

Plugins(18):  AdvancedBan, ChatEx, CombatPlus, AuctionSystem, RedCore, Essentials, floodgate, HideStream, KillerMoney, LuckPerms, NametagRealizer, PlaceholderAPI, ProtocolLib, Scoreboard, Vault, WorldEdit, WorldGuard

My bungeecord plugins: floodgate-bungee, Geyser-BungeeCord, HubConnector

### Geyser Dump

No dump, i use BungeeCord

### Geyser Version

1.4.9-SNAPSHOT (git-master-32bbd8a) (Java:1.17.1 Bedrock: 1.17.1)

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by CAT555502** [comment]
Error, Geyser version 1.4.0

**Comment by CAT555502** [comment]
Error, Geyser version 1.4.0

**Comment by RednedEpic** [comment]
Do you have any video of this occurring, or any errors in console?

**Comment by CAT555502** [comment]
> Do you have any video of this occurring, or any errors in console?

No errors in console!

**Comment by Camotoy** [comment]
Please update as the error should be fixed.
