### ISSUE TITLE
After killing a mob, its death sound is played twice

### ISSUE THREAD

**Issue by hausemaster3734** [GeyserMC/Geyser#2363]
### Describe the bug

When you kill any mob, be it for example a chicken, the sound of its death will be played twice. See video

### To Reproduce

1. Spawn any mob, for example chicken.
2. Kill chicken

### Expected behaviour

The sound of the mob's death must be played once

### Screenshots / Videos

https://youtu.be/tXbL2VBGCXY

### Server Version and Plugins

This server using Paper version git-paper-90 (MC: 1.17.1) API Version: 1.17.1-R0.1-SNAPSHOT (git:bb44da8)

Plugins(18): AdvancedBan, ChatEx, CombatPlus, AuctionSystem, RedCore, Essentials, floodgate, HideStream, KillerMoney, LuckPerms, NametagRealizer, PlaceholderAPI, ProtocolLib, Scoreboard, Vault, WorldEdit, WorldGuard

My bungeecord plugins: floodgate-bungee, Geyser-BungeeCord, HubConnector

### Geyser Version

1.4.0-SNAPSHOT (git-master-32bbd8a) (Java:1.17.1 Bedrock: 1.17.1)

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by Camotoy** [comment]
Cause: https://github.com/GeyserMC/Geyser/blob/master/connector/src/main/java/org/geysermc/connector/network/translators/java/entity/JavaEntityStatusTranslator.java#L230
