### ISSUE TITLE
Add armor dressing in one click or tap

### ISSUE THREAD

**Issue by CAT555502** [GeyserMC/Geyser#2364]
### What feature do you want to see added?

Although this is a feature of Minecraft Bedrock, but it has a place to be. 
This makes it uncomfortable for many players.

### Are there any alternatives?

None

**Comment by Camotoy** [comment]
Can you send a screenshot or video of what you want?

**Comment by CAT555502** [comment]
> Can you send a screenshot or video of what you want?
https://youtu.be/nHunDu8q4Uc

**Comment by Camotoy** [comment]
Duplicate of #2364. Thank you anyway!
