### ISSUE TITLE
Server is using up to 70% of its memory with only a few Bedrock Players connected

### ISSUE THREAD

**Issue by Cosmos9999** [GeyserMC/Geyser#2366]
### Describe the bug

Our server has 4gb of RAM, and whenever bedrock players join it, the memory used jumps up, and every so often all bedrock players connected to the server disconnect.

### To Reproduce

1. Connect to the server on bedrock
2. Memory being used jumps up by a large percentage.
3. Disconnection if too many players are online.

### Expected behaviour

On an old test world for our server, we did not have this issue, we expected bedrock players to join and the memory used only rise a small amount. We also expected them to stay connected as long as they want to be on the server.

### Server Version and Plugins

This server is running Paper version git-Paper-64 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 333cc2e)
You are 15 version(s) behind

With Plugins CoreProtect, Floodgate, Geyser-Spigot, GriefPrevention, SkQuery, Skript, SuperVanish

### Geyser Version

Geyser-Spigot v1.4.0-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by Camotoy** [comment]
Please send us a heap dump: https://www.baeldung.com/java-heap-dump-capture

**Comment by Cosmos9999** [comment]
Ok, updated issue, I'm working on getting the dump, but from what I can tell, the RAM usage spikes only when the bedrock player first joins, and then only bedrock players are experiencing serious lag, such as game freezing. Eventually, all bedrock players disconnnect at the same time and get the message "Disconnected"

**Comment by Cosmos9999** [comment]
Closing because issue is different then first assumed.

**Comment by Cosmos9999** [comment]
We've fixed the issue by updating to 1.17.1 and reinstalling Geyser and floodgate.
