### ISSUE TITLE
The player's items are saved visually after death in unloaded chunks

### ISSUE THREAD

**Issue by hausemaster3734** [GeyserMC/Geyser#2367]
### Describe the bug

Key moments: 0:07, 0:28, 0:32, 0:37 and 1:39 

### To Reproduce

1. Give the player armor.
2. Teleport the player to chunks that the player has not yet been to, or unloaded.
3. Kill the player.
4. Teleport the player to yourself and let him put on any element of armor

### Expected behaviour

The player's items must be cleared after the murder.

### Screenshots / Videos

https://youtu.be/14rv12fjCWs

### Server Version and Plugins

This server using Paper version git-paper-90 (MC: 1.17.1) API Version: 1.17.1-R0.1-SNAPSHOT (git:bb44da8)

Plugins(18): AdvancedBan, ChatEx, CombatPlus, AuctionSystem, RedCore, Essentials, floodgate, HideStream, LuckPerms, NametagRealizer, PlaceholderAPI, ProtocolLib, Scoreboard, Vault, WorldEdit, WorldGuard

My bungeecord plugins: floodgate-bungee, Geyser-BungeeCord, HubConnector

### Geyser Version

Geyser build #752

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by RednedEpic** [comment]
Stale. Please open a new issue w/ updated repro steps if this still occurs.
