### ISSUE TITLE
connection lost because of too much packets 

### ISSUE THREAD

**Issue by AdamDAuria** [GeyserMC/Geyser#2368]
### Describe the bug

players can play on the server for a 1 hour and 40 mins and then suddenly then get a lot of connection lost error when they try to join the server bedrock and java 

### To Reproduce

have on the server 5 or more players
play on at least 100 mins 

### Expected behaviour

it not suppose to spam the console like crazy

### Screenshots / Videos

the error -  https://ibb.co/FxqM7SQ 

### Server Version and Plugins

1.17.1

### Geyser Dump

https://dump.geysermc.org/TUppJY4WsajNr89tlqLGqdOz7MZothqA

### Geyser Version

1.14.0

### Minecraft: Bedrock Edition Version

1.17.2

### Additional Context

none

**Comment by Camotoy** [comment]
We *do not* touch Java packets at all. Since that is a Java error, there is absolutely no way this could be us.
