### ISSUE TITLE
bug with menu plugins

### ISSUE THREAD

**Issue by thinh2021** [GeyserMC/Geyser#2372]
### Describe the bug

Plugins that use menus like deluxemenus, slime guide, skyblock when holding an item and dropping it on any item you have, will get x2 times. For example, when buying items at the menu, when you hold an item to confirm the purchase and drop it on any item, you will get x2 times of that item.

### To Reproduce

1. go to plugin have menu
2. use item on menu and drop it on any item you have in inventory.
3. menu features will be doubled

### Expected behaviour

Plugins that use menus like deluxemenus, slime guide, skyblock when holding an item and dropping it on any item you have, will get x2 times. For example, when buying items at the menu, when you hold an item to confirm the purchase and drop it on any item, you will get x2 times of that item.

### Screenshots / Videos

https://drive.google.com/file/d/17Zo8Qyeistla8kvvuM34YSrnjH8gNDxu/view?fbclid=IwAR2k7MpbxJtbNfUw7FZYtZDVowekWj42mjjHVDgTeYeg8i22hZWRTlQkCmI

### Server Version and Plugins

Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Geyser Dump

 https://dump.geysermc.org/waJMj80n8ihVOAEU17YVFAOKv6fpnsaq

### Geyser Version

Geyser version 1.4.0-SNAPSHOT (git-master-887296e)

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by Camotoy** [comment]
Could you provide a video example? Or configuration files for one of those plugins in order to replicate it?

**Comment by Camotoy** [comment]
Also please provide a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by thinh2021** [comment]
https://dump.geysermc.org/wQGjTI93sxZLJ8wX4Kos1onBPaQXBmyB

**Comment by thinh2021** [comment]
this is video

**Comment by rtm516** [comment]
Updated with info from #2374

**Comment by LowScarlet** [comment]
What this?

**Comment by RednedEpic** [comment]
Stale. We've done a few changes to our inventory system since this was last replied to. Please open a new issue if this still occurs w/ updated repro steps & a video.
