### ISSUE TITLE
Bug X2 With Plugin Menu

### ISSUE THREAD

**Issue by thinh2021** [GeyserMC/Geyser#2374]
### Describe the bug

Plugins that use menus like deluxemenus, slime guide, skyblock when holding an item and dropping it on any item you have, will get x2 times. For example, when buying items at the menu, when you hold an item to confirm the purchase and drop it on any item, you will get x2 times of that item.

### To Reproduce

1. go to plugin have menu
2. use item on menu and drop it on any item you have in inventory.
3. menu features will be doubled

### Expected behaviour

Plugins that use menus like deluxemenus, slime guide, skyblock when holding an item and dropping it on any item you have, will get x2 times. For example, when buying items at the menu, when you hold an item to confirm the purchase and drop it on any item, you will get x2 times of that item.

### Screenshots / Videos

https://drive.google.com/file/d/17Zo8Qyeistla8kvvuM34YSrnjH8gNDxu/view?fbclid=IwAR2k7MpbxJtbNfUw7FZYtZDVowekWj42mjjHVDgTeYeg8i22hZWRTlQkCmI

### Server Version and Plugins

Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Geyser Dump

 https://dump.geysermc.org/waJMj80n8ihVOAEU17YVFAOKv6fpnsaq

### Geyser Version

Geyser version 1.4.0-SNAPSHOT (git-master-887296e)

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by thinh2021** [comment]
This bug work all plugin use gui.

**Comment by rtm516** [comment]
Updated #2372 and reopened
