### ISSUE TITLE
AuthMe Support

### ISSUE THREAD

**Issue by TheCiROMG** [GeyserMC/Geyser#2375]
### What feature do you want to see added?

That when the user connects, it shows their own ip, unfortunately, I cannot use floodgate, and without this little addition, I cannot ban bedrock users, SINCE THEY HAVE THE SAME IP, this is a vulnerability without a doubt

### Are there any alternatives?

Yes, the most common alternative, FLOODGATE, which was used before, but with the recent changes, it is no longer a solution or "alternative". Unfortunately, this saddens me.

**Comment by TheCiROMG** [comment]
What if I've already tried and it didn't work?

How do I solve it?

The server is offline, and I use authme with fastlogin, but, when setting floodgate, users cannot log in, or, basically, if they put the command / login (password) it doesn't log them

**Comment by Jens-Co** [comment]
> What if I've already tried and it didn't work?
> 
> How do I solve it?
> 
> The server is offline, and I use authme with fastlogin, but, when setting floodgate, users cannot log in, or, basically, if they put the command / login (password) it doesn't log them

Using offline mode is not supported, in doing so you are on your own for that matter sorry.
