### ISSUE TITLE
Bedrock players can't play at all after the server is up for a few minutes (can log in tho)

### ISSUE THREAD

**Issue by KKYH246** [GeyserMC/Geyser#2376]
### Describe the bug

imma just copy and paste whatever i said on discord, no one helped:

msg 1:
Does anyone has an issue , when the server just started and i join as a bedrock player (i was using pocket edition v1.17.2), everything seems fine, until around 1 minute later, everything seems frozen on my phone (no movement at all). I can move, and when i destroy blocks, they just disappear. Nothing wrong when i join with java, and when i tp myself to the bedrock client, the bedrock player is just stationary no matter how i attempt to move the bedrock player(this is after everything seems frozen on the bedrock client)  <this is using paper 1.17.1 build 96, geyser build 13 floodgate 2.0

msg 2:
so i have tested this on 2 computers. one is my new pc which is where i wanted the server to be, and my laptop which is the previous server machine. On the pc, this issue occurs. On bedrock, after the server is on for a while, everything in the bedrock client will seem like they are frozen (bedrock players cannot move at all, it seems like nothing is moving also, but in actual fact if i tp a java player right in front of the affected player and the bedrock player taps on the screen[like he is hitting something], the java player will get hit). If other bedrock players log on, they will seem like they are in the void (the coords show 0 -40 0).
For the first minute or so when the server is on, everything seems fine. 

On my laptop, none of these issues above occur.

None of these affects java players gameplay, only bedrock players unable to play.

Im not sure if its a plugin problem or my pc problem(probably my pc), so maybe if anyone knows what's going on, pls help?

My laptop is a asus vivobook 14  --> i5 8265u, 8   gb ram, 256gb ssd
The PC(mini pc) is a NUCPAHi5 --> i5 1135g7, 32 gb ram, 1tb ssd

Ill be putting in 2 videos here shortly, one is when the server just started and i connect with a bedrock client (everything seems to be frozen after a while), another one when i log in after the issue has started.

### To Reproduce

1. Start the server
2.  Log in with Bedrock client
3. do random things while everything seems normal. For me I just spammed click a spruce door to test. (The sound of the door can be heard still at this point)
4. When you are tapping on the door, the door should rightfully be making the open/closing noise, but after a while there isnt the noise. Try breaking blocks, they will seem like they disappear. Seemingly, you still can interact with things but in actual fact no. Entities on the client will stop moving but in the server none of these happened
5. Use a Java Client to inspect the actions and movements carried out by the bedrock client. From this point of view while step 4 is in place, the bedrock player will not move at all, and even though he cant see any entity moving, he will be able to hit entities if the bedrock client person taps on the screen at the correct spot (im used pocket edition here)

### Expected behaviour

Basically none of whatever i described happening: where bedrock players can play normally

### Server Version and Plugins

it doesnt matter how many plugins are there. i did a test setup where there is only geyser(with appropriate version of paper), the same thing happened

[20:55:59 INFO]: This server is running Geyser version 1.4.0-SNAPSHOT (git-master-887296e) (Java: 1.17.1, Bedrock: 1.17.0)
[20:55:59 INFO]: Checking version, please wait...
[20:56:00 INFO]: You are 1 versions behind; download the latest build from https://ci.geysermc.org/

### Geyser Dump

https://dump.geysermc.org/IgLWBlzKHHfgQN3jltMsqD1ZJUWGn3Sz

### Geyser Version

1.4.0-SNAPSHOT (git-master-887296e)

### Minecraft: Bedrock Edition Version

1.17.2

### Additional Context

This only happens on my mini pc which i just received. Im not sure if geyser has any dependencies. I only installed Java 16 to get the server up and running.

I tested this with the exact same server files (it's in a external hard drive) and my previous machine, an Asus Vivobook 14 with i5 8265u, 8gb ram. and another machine in my house. The issue does not occur. Does this only happens on mini pcs? Im using a Intel NUCPAHi5 with 1tb SSD 32 GB RAM and it has i5 1135g7 in it

**Comment by Camotoy** [comment]
Can you please send a Geyser dump from these other machines?

**Comment by KKYH246** [comment]
oki sure but gimme a while

**Comment by KKYH246** [comment]
https://dump.geysermc.org/LpjL7LaLF3rK56TpsHaIVkctLn9eeEcb

**Comment by KKYH246** [comment]
does this have to do with some hardware issue(i cant think of it) . or some network issue

**Comment by KKYH246** [comment]
idk because it seems like geyser is working, but the client aint receiving data or vice versa. Usually when i login while the problem is there, i get teleported to 0 -40 0, which is client side only after using a java client to verify. Sometimes if im lucky, on the client i will be on where im supposed to be, but after that split second everything seems to freeze again.

**Comment by KKYH246** [comment]
https://dump.geysermc.org/08TUE3t9aRCmXky6xYLddh9UJvFyhr8f
[13:03:53 INFO]: [Geyser-Spigot] Spawned entity SQUID at location (-1367.5, 53.0, 4167.5) with id 194 (java id 5285)
[13:03:53 INFO]: This server is running Geyser version 1.4.0-SNAPSHOT (git-feature/1.17.10-472c88c) (Java: 1.17.1, Bedrock: 1.17.10)
(PC <this is not the mini pc>)

**Comment by boeserKuchen** [comment]
did you find a solution? i have the same problem

**Comment by KKYH246** [comment]
nope, sorry.

**Comment by KKYH246** [comment]
besides using a different computer

**Comment by Camotoy** [comment]
Does the issue still occur?

**Comment by KKYH246** [comment]
yup

**Comment by Camotoy** [comment]
Can you provide a new Geyser dump, and then download the Spark plugin (link below) and when the issue is happening:

> Spark is a plugin that helps you monitor performance for your server.
> https://spark.lucko.me/download

> To record performance on your server use:
> `/spark profiler --thread *` . Once the monitored action is done, use `/spark profiler --stop`.

**Comment by KKYH246** [comment]
ill do it in within these few days (prob in a few hours, if not tmr)

**Comment by Jens-Co** [comment]
> ill do it in within these few days (prob in a few hours, if not tmr)
> 
> 

Any info about this issue ? Thanks ;)

**Comment by bafgd** [comment]
Yep I tried to change server types and I have tried to change computers on which the server runs on nothing works. The bug is only present in java and I don’t want to go about doing /restart every 5 mins.

**Comment by August7** [comment]
This looks like I'm having the same problem [https://github.com/GeyserMC/Geyser/issues/2741](url)

**Comment by Camotoy** [comment]
We finally have narrowed down a workaround for this bug. See #2861. It was the CPU this whole time.
