### ISSUE TITLE
movement glitch when climbing stairs

### ISSUE THREAD

**Issue by dr03ramos** [GeyserMC/Geyser#238]
**Describe the bug**
The player walks backwards when climbing stairs (as shown in the video)

**To Reproduce**
1. go up some stairs
2. See error

**Expected behavior**
the player normally going up stairs without glitches

**Screenshots**
here's a video: 
https://drive.google.com/file/d/13bVVYdBcwauiKhjrsRNxllMepgbntk5I/view?usp=drivesdk

**Server version**
spigot 1.15.2

**Geyser version**
most recent

**Bedrock version**
1.14.30

**Additional context**
apparently it doesn't recognize the coordinates properly

**Comment by RednedEpic** [comment]
> **Describe the bug**
> The player walks backwards when climbing stairs (as shown in the video)
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. go up some stairs
> 2. See error
> 
> **Expected behavior**
> the player normally going up stairs without glitches
> 
> **Screenshots**
> here's a video:
> https://drive.google.com/file/d/13bVVYdBcwauiKhjrsRNxllMepgbntk5I/view?usp=drivesdk
> 
> **Server version**
> spigot 1.15.2
> 
> **Geyser version**
> most recent
> 
> **Bedrock version**
> 1.14.30
> 
> **Additional context**
> apparently it doesn't recognize the coordinates properly

Make sure you have autojump disabled; it causes problems with stairs and since movement on them (as shown in the video) is faster on bedrock, the java server doesn't think the movement is valid and teleports you back.

**Comment by dr03ramos** [comment]
ok, my autojump is on always on, might be this
