### ISSUE TITLE
Bedrock Players on 1.17.10 are reporting they cannot craft items or trade with Villagers

### ISSUE THREAD

**Issue by Kruize1** [GeyserMC/Geyser#2381]
### Describe the bug

Bedrock Players on 1.17.10 are reporting they cannot craft items or trade with Villagers

Seems to be related to the 1.14.1 snapshot build (1.4.1-SNAPSHOT (git-master-f7ef902))

### To Reproduce

1. Have Bedrock player join
2. Have them attempt to craft items and trade with Villagers

### Expected behaviour

Player should be able to craft items and trade with villagers.

### Geyser Dump

https://dump.geysermc.org/CDSSArGzIEHqbTuCcP4x8xZ7mYXj2TOf

### Geyser Version

1.4.1-SNAPSHOT (git-master-f7ef902)

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Camotoy** [comment]
I'm unable to confirm this on Paper 1.17.10. Can you list what platforms these players are on?

**Comment by Kruize1** [comment]
They play on Switch.

Also, I clarified with them, and they are using the crafting book or the equivalent of that to try and craft items. That's where they are running into the problem.

Putting them items into the crafting bench seems to work for them.

![image](https://user-images.githubusercontent.com/21042824/125535239-be7d4291-146f-4f13-8ddf-dd448012d6e3.png)

**Comment by Camotoy** [comment]
Confirmed. :(

**Comment by Konicai** [comment]
Specifically on switch?

**Comment by Camotoy** [comment]
Tested on Switch. Untested on other platforms.

**Comment by rjmurray** [comment]
I've got a video from a bedrock user on my server demonstrating the issue being discussed here. They play on xbox one s. [

https://user-images.githubusercontent.com/6089731/125543498-245429f4-03a4-43f7-9e11-8803328bf159.mp4

](url)

**Comment by dannysmc95** [comment]
Hey @Camotoy the commit you added to this, is this actually a fix? (I see you put a to-do notice in there).
If so, is this fix released? Just checking as a player who is connecting via PS4 on my server is also experiencing the same issue.

**Comment by Camotoy** [comment]
Yes. The fix was a change in one of Geyser's libraries. Please ensure your Geyser version is completely up-to-date.

**Comment by dannysmc95** [comment]
@Camotoy that's great to hear, thanks for the update, I shall go ahead and update my plugins!
