### ISSUE TITLE
Bug while flying into block with riptide trident

### ISSUE THREAD

**Issue by Minionguyjpro** [GeyserMC/Geyser#2383]
### Describe the bug

Bug while flying into block with riptide trident

### To Reproduce

1. Go into a server with Geyser on Bedrock edition. 
2. Get an trident with riptide enchantment on it.
3. Place water
4. Place a block 10 blocks above you
5. Throw the trident completely up
6. You bug inside the block temporary

### Expected behaviour

Just not fly inside the block

### Server Version and Plugins

git-AirplanePurpur-15 (MC: 1.17.1)

### Geyser Version

1.4.1-SNAPSHOT (git-master-ba4e0cf)

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by CAT555502** [comment]
I think it's vanilla. Because I have encountered this in my world

**Comment by RednedEpic** [comment]
Stale. Please open a new issue w/ updated repro steps if this still occurs & try and replicate on singleplayer as this is possibly a vanilla bug.

**Comment by Minionguyjpro** [comment]
It is not happening in Singleplayer.
