### ISSUE TITLE
Legacy Console being able to connect to Java or Bedrock world

### ISSUE THREAD

**Issue by MiniDuncan** [GeyserMC/Geyser#2384]
### What feature do you want to see added?

I am very aware that this is probably impossible, but I miss the legacy console versions of the game so much and I would like to see something similar to GeyserConnect or BedrockConnect, implemented into the legacy console versions of the game, as they are a lot of versions behind, if it was possible to do, I would have either used something like ViaVersion for Java. I'm pretty sure Bedrock already has support for transferring legacy worlds, so maybe theres a way to use that.

### Are there any alternatives?

- A datapack and texture pack to make bedrock exactly like the legacy console versions

Seeing as you are the only people to add cross version cross platform, it might have been worth posting it here

**Comment by Camotoy** [comment]
While this sounds like an interesting project, this is definitely out of scope of Geyser. Even if we added support, we do not wish to maintain support. If an easy way to support these devices come around (there is no known documentation for how these versions talk over the network), I'm sure some of us will be there for making some form of connectivity. Thanks anyway.
