### ISSUE TITLE
The ability to add your own suggestions for commands.

### ISSUE THREAD

**Issue by hausemaster3734** [GeyserMC/Geyser#2389]
### What feature do you want to see added?

In a separate file suggestions.yml file, you can add your own suggestions for the commands.
With this, you can prevent lags from command suggestions on Bedrock and it will be much more convenient for players to use it on the server

### Are there any alternatives?

No alternatives

**Comment by YHDiamond** [comment]
So there would be something in the config file that would contain a list of commands that should be whitelisted or blacklisted from the command suggestions?

**Comment by CAT555502** [comment]
> So there would be something in the config file that would contain a list of commands that should be whitelisted or blacklisted from the command suggestions?

It seems to me that the black list will be inconvenient, because there will be no description for the commands, which will be inconvenient for players playing from bedrock.

This is the solution that I think will be more convenient for the players.

**Comment by RednedEpic** [comment]
Somewhat out of scope for the Geyser project. Will likely be implemented by an extension in the future.
