### ISSUE TITLE
Allows to switch the state of the custom skull display through a command or client setting

### ISSUE THREAD

**Issue by zimzaza4** [GeyserMC/Geyser#2392]
### What feature do you want to see added?

Allows to switch the state of the custom skull display through a command or client setting.

### Are there any alternatives?

Command or client settings

**Comment by Camotoy** [comment]
I'm not sure what you mean.

**Comment by zimzaza4** [comment]
The custom skull will cause the bedrock client to freeze, so I have to close it. But some players want this feature.
Add a way to switch the display of custom skull.

**Comment by rtm516** [comment]
Do you mean a per-client option of `allow-custom-skulls`?

**Comment by zimzaza4** [comment]
> Do you mean a per-client option of `allow-custom-skulls`?

yes
