### ISSUE TITLE
Java custom heads shows as steve

### ISSUE THREAD

**Issue by Aryan2-1** [GeyserMC/Geyser#2393]
### Describe the bug

Java custom heads shows as steve in inventory and also while placed i got #683 but that is too old can you please fix it?

[this plugin](https://www.spigotmc.org/resources/ultimate-mob-heads.54946/?__cf_chl_jschl_tk__=8c9a84e80f52e5f222f341c8c778632d7a52347c-1626581595-0-AfoeOZ7NuiQUVWbhYouIRlD5mXR0sQf5vHwETEtK0UCxkkS2UQBv-n1cTcVIyAZr6JFqvmEOPG0AIr9arxLSpOv9jc-ervldXUkqIs0xit3ew1y4xR0oiOtHYLX-V57EDFwNf-XGEKQUixzxhByooDRKU6QwaWE0EEqCn99ZDItS1UG3wISQxTYDjlWpUgRrJzhBZ-joLfN_Ze24IED_mUsazXti_yPwXossuPDdYEAJWsP966HVSYqXdYNk8bLmEG2tGhdcg_2cYH9MoxSFqtEeF0YferVbNcyCSrcvlx6ArDZ74URqXiNkHBeL_ABo3eiXkBefJ_QlTAJd1sfdg3G0hIl7EHBq2HHdtv2VMkkPpHljWg-nsb0XByMyAJqhB5cMAh1t76Rc_2i-7QLL_6kdfTK6fEcloxp0XGgXpAZngCeW2SAF5HP-jq2TfqkFNQ) heads works on both java and bedrock but [this plugin](https://www.spigotmc.org/resources/christmaspresents-1-7-1-16.39859/) heads show up as steve also after placing.

### To Reproduce

I don't know java :/

### Expected behaviour

I expected it will show up as custom head

### Server Version and Plugins

[06:09:19 INFO]: This server is running Paper version git-Paper-108 (MC: 1.17. 1) (Implementing API version 1.17.1-RO.1-SNAPSHOT) (Git: a5acf36) You are 3 version (s) behind

Previous version: git-Paper-69 (MC: 1.17)

### Geyser Dump

https://dump.geysermc.org/dkuSzhDTTtx3AWEhBC0Fm5Cd66rFSCPa

### Geyser Version

759

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Jens-Co** [comment]
Custom player heads in the inventory is a client sided problem which cannot be fixed, I assume that the plugin you are using is non functional especially since it's last updated in 2018. The best thing you can do is use an updated plugin.

**Comment by Aryan2-1** [comment]
> Custom player heads in the inventory is a client sided problem which cannot be fixed, I assume that the plugin you are using is non functional especially since it's last updated in 2018. The best thing you can do is use an updated plugin.

Custom heads also don't work on armour stand i am using ultra minions and the minion head shows as steve how to fix it? I changed minion heads ids in config

**Comment by EasyClifton** [comment]
> > Custom player heads in the inventory is a client sided problem which cannot be fixed, I assume that the plugin you are using is non functional especially since it's last updated in 2018. The best thing you can do is use an updated plugin.
> 
> Custom heads also don't work on armour stand i am using ultra minions and the minion head shows as steve how to fix it? I changed minion heads ids in config 

Sorry, this is also a client limitation we can't do anything about

**Comment by Camotoy** [comment]
Custom heads on armor stands could be worked around, but would potentially lag out the client more than player skulls already do. Custom heads in the inventory is likely possible, but requires much work and manual setup. I'm closing this as armor stands are covered in #782 and player heads are currently documented as a limitation. Thanks.

**Comment by nate-moo** [comment]
Using slimefun causes major lag both on android and windows 10 edition because of the sheer amount of playerheads

since they show up like this:
![image](https://user-images.githubusercontent.com/40650681/135169477-448d71a7-450e-4f09-8cac-fe65dc7958cc.png)
![image](https://user-images.githubusercontent.com/40650681/135169509-3ee940b5-9fa5-40e6-be13-7549068a4234.png)

**Comment by tectonic21** [comment]
I have the same issue on my server. It is a geyser server and my bedrock players are reporting that all custom heads and npcs look like the picture shown. Do you know what plugin is causing this and if so what? Or if there is a way to fix this via server files.

**Comment by onebeastchris** [comment]
double check that you are on the latest version of Geyser; as well as that all your bedrock players are on 1.19.63. That should stop that from happening
