### ISSUE TITLE
Add support for Args for Plugin Version

### ISSUE THREAD

**Issue by TUBEOF** [GeyserMC/Geyser#2394]
### What feature do you want to see added?

As already merged here for standalone: https://github.com/GeyserMC/Geyser/pull/1506
A way to add options like this to the plugin version would be very helpful. 
For example: -Dgeyser.serverip=0.0.0.0

### Are there any alternatives?

Edit values via script in config file, but it's not perfect and "easy".

**Comment by rtm516** [comment]
Why not just edit the config?

**Comment by TUBEOF** [comment]
Editing GeyserMC via the config is all well and good for a single server, but if you want to automate it with the setup of servers, the whole thing is simply very error-prone.
It would also be a good way for hosters to set these options.

**Comment by TheMonBonGH** [comment]
with the plugin versions, you wouldn’t really need to edit the configuration?

**Comment by TUBEOF** [comment]
Sure? You need to define the bedrock port for example

**Comment by Camotoy** [comment]
I could see this as a valid request. Shockbyte already does something to force Geyser plugin configs to bind to a certain IP - having a way for them to just include a startup parameter instead surely would be helpful.

**Comment by rtm516** [comment]
Most server panels have the feature of editing config files and I know of some hosting providers that create partial configs, this seems like a lot for something that would likely only change once.
There are config options to automatically set all ports and the geyser -> java side of IPs.
Maybe worth bringing this over to the `#development` channel on [Discord](https://discord.gg/geysermc) to discuss more.

**Comment by TUBEOF** [comment]
In any case, I think it would be worth implementing. It was also implemented in the standalone version (even if there is a config), so I don't think it should make any difference whether it can now also be used in the plugin version with the args.

**Comment by YHDiamond** [comment]
Where would you put the args?

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/issues/3597 possible duplicate?

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/commit/f39e689b83c1be89ec4f51ab9fc60b9c419b7b99 This commit added the functionality of setting address and port via system properties; therefore closing as completed
