### ISSUE TITLE
Player-Server Item held desync + Client sided ghost blocks

### ISSUE THREAD

**Issue by supertakeru** [GeyserMC/Geyser#2395]
### Describe the bug

The bug appears to be that sometimes there is a desync in what the player is holding on their client and what they appear to be holding on the server, i.e. they are holding a stone axe on their client but on the server they are holding a different item on their hot bar such as wheat seeds.

A workaround for displaying the correct item is to tell the player to resync their inventory by repeatedly switching their axe out with another item forcing inventory updates until the server correctly shows what the player is holding on their client.

Despite this work around, when blocks are broken by the axe they are not broken server side and only client side resulting in client sided ghost blocks.

I have had this problem happen to multiple players so just blaming it on connection issues for all of them would be a bit difficult. The players that it happens to typically tend to be on mobile, I was unable to reproduce this problem on my PC and PE Bedrock account (i tested both platforms). I am really at a loss for what is going on.

### To Reproduce

Difficult to reproduce

1. Log onto server
2. Break blocks with tools
3. Hopefully desync/ghost blocks do not occur

### Expected behaviour

Player inventory is synced , blocks broken by player tools are correctly broken client side and server side -- no ghost blocks are created

### Screenshots / Videos

https://streamable.com/gkwzxu (this problem could be due to connection, no chests are opening)

https://streamable.com/1eecwl (client glitching due to ghost block broken by axe, but on server side that block is still there)

https://streamable.com/foocbg (perfect example of the problem that is occurring)

https://streamable.com/0ncomr (another great example of the issue showing that blocks broken by the players fist are registering correctly but the axe is creating ghost blocks)

https://streamable.com/nkaqoj (another player report)

https://streamable.com/cp5bty (player report showing axes having problems with stripping [only strips one log and then stops working])

### Server Version and Plugins

Purpur version git-Purpur-1287 (MC: 1.17.1)

Paper version #112 1.17.1

(Tested 2 versions)

DATAPACKS:
Mojang 1.18 world generation preview datapack
Mesa villages
Pillager strongholds and Pillager settlements
Geodes

### Geyser Dump

https://dump.geysermc.org/JJeSTc80iEh4TcVJyiAVARAxszGU8FUX

### Geyser Version

"version": "1.4.1-SNAPSHOT (git-inject-3131d27)"

### Minecraft: Bedrock Edition Version

1.16.1

### Additional Context

I tried removing every plugin except floodgate and geyser, and the problem still persisted.

Further testing with one of the affected players showed that the bug is inconsistent and sometimes does not occur and they are able to break the blocks normally

* will continue to update with information

**Comment by Konicai** [comment]
Hi, does this persist if you set `use-direct-connection` in Geyser's config to `false` ?

**Comment by Camotoy** [comment]
This user first reported in the #development channel and said the issue persisted with the master branch, which is effectively the same thing.

**Comment by Konicai** [comment]
Ah alright, perhaps try plugin debugging if you haven't yet?
- Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by supertakeru** [comment]
I have tried plugin debugging as written in Additional Context

**Comment by supertakeru** [comment]
Just as a note for anyone viewing this problem I will continue to add videos of bug reports to this issue by editing the main issue above

**Comment by Jens-Co** [comment]
Hello there, would it be possible for you to add the spark plugin ? So the developers can take an in-depth look at your server. Thanks 

https://www.spigotmc.org/resources/spark.57242

**Comment by supertakeru** [comment]
Yes I have the spark plugin, what information do you need?

**Comment by supertakeru** [comment]
I have found out that this problem is potentially and likely connected to: https://www.spigotmc.org/resources/simpletoolstats.81854/

Now I am just curious as to why this is the case

**Comment by Konicai** [comment]
Can you provide full replication steps if that plugin is causing this?

**Comment by onebeastchris** [comment]
Could you try updating to the latest version of Geyser, and see if the issue persists?
If it does, send a new Geyser dump by running "geyser dump" in your server console.

**Comment by onebeastchris** [comment]
Closing due to no response.
