### ISSUE TITLE
EliteMobs (/em) book doesnt load or display book interface for Bedrock Users

### ISSUE THREAD

**Issue by AlphaJH5** [GeyserMC/Geyser#2397]
### Describe the bug

Using EliteMobs using /em in Java displays a book navigator, doing the same in Bedrock doesn't work. 

https://www.spigotmc.org/resources/40090/
https://github.com/MagmaGuy/EliteMobs

### To Reproduce

1. Using EliteMobs & Geyser
2. Do '/em' Book Interface should appear but in Geyser Bedrock it does not

### Expected behaviour

Book UI is meant to be their

### Screenshots / Videos

https://user-images.githubusercontent.com/5401186/126161021-fb21677d-40a2-429b-abe3-1c07746b07d6.mp4

### Server Version and Plugins

Paper 1.17,1

### Geyser Dump 

https://dump.geysermc.org/SugKPunmfoRfZ8sk9wrFJFcmOYQ8VxYE

### Geyser Version

1.4.1

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by Jens-Co** [comment]
Duplicate from #1351, You can find more information about this issue.
