### ISSUE TITLE
No custem join items show up

### ISSUE THREAD

**Issue by TechDroid2002** [GeyserMC/Geyser#24]

**Comment by x9nico** [comment]
Not implemented for moment.

**Comment by TechDroid2002** [comment]
@x9nico it is items show up

**Comment by x9nico** [comment]
I know, that's what I told you.

**Comment by RednedEpic** [comment]
> I know, that's what I told you.

Items are implemented, some won’t show up yet though, yes.

**Comment by RednedEpic** [comment]
There was a bug in one of the builds a couple days ago causing items to not show up at all. This has since been resolved. However, some items do not show up due to missing mappings. If you notice anything, please open a new issue with the items that are missing.

**Comment by TechDroid2002** [comment]
@RednedEpic latest build

**Comment by TechDroid2002** [comment]
Reopen it

**Comment by RednedEpic** [comment]
I’ll take a look shortly.
