### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Waddl3s** [GeyserMC/Geyser#2401]
### Describe the bug

Geyser setup all correctly. Server is pinging and showing online on Bedrock and Online checker. Port is open on UDP, Same with TCP. Tried completely disabling firewall same issue. No console errors, only output in console from when trying to connect is. Attempted troubleshooting on discord support, not able to fix. https://discord.com/channels/613163671870242838/613168464634576897/867035174066585630 (Correspondence between Tootal and Tydium).

`[Geyser-Spigot] *My IP* tried to connect!`

`[Geyser-Spigot] Bedrock user with ip: *My IP* has disconnected for reason CLOSED_BY_REMOTE_PEER` 

### To Reproduce

1. Fresh install of geyser
2. Fill out config with correct information
3. Shows online on Bedrock
4. Try to connect, 
5. Stuck on connecting to external server

### Expected behaviour

Should connect and load up world. 

### Screenshots / Videos

https://i.imgur.com/uoLyRqG.png

### Geyser Dump

https://dump.geysermc.org/DW3JmHftUUVUCMwtjHnhQ1PSeiUgAREX

### Geyser Version

1.4.1-Snapshot (git-master-0e72952)

### Minecraft: Bedrock Edition Version

1.17-1.17.10

**Comment by Camotoy** [comment]
https://github.com/GeyserMC/Geyser/wiki/Common-Issues#stuck-on-locating-server-with-no-errors may be an option to consider. If that doesn't help, please send a full log with the debug mode option in Geyser's config enabled.

**Comment by Waddl3s** [comment]
> 
> 
> https://github.com/GeyserMC/Geyser/wiki/Common-Issues#stuck-on-locating-server-with-no-errors may be an option to consider. If that doesn't help, please send a full log with the debug mode option in Geyser's config enabled.

Yeah I've tried them, Nothing

**Comment by Camotoy** [comment]
Make sure the log has a player joining, please!

**Comment by Waddl3s** [comment]
https://pastebin.com/1VWBr45j

**Comment by Camotoy** [comment]
Can you try with no other plugins installed?

**Comment by Jens-Co** [comment]
I was able to connect to it once and got het whitelist login screen. Afterwards I was unable to join again yet I got ping. You should check your logs for the username .KobeNetwork.

**Comment by Waddl3s** [comment]
Im not gonna do that, caused enough distress with the amount of restarts for my players. If it can't work with what i've got I won't use it


> 
> 
> Can you try with no other plugins installed?

Im not gonna do that, caused enough distress with the amount of restarts for my players. If it can't work with what i've got I won't use it

**Comment by Jens-Co** [comment]
> Im not gonna do that, caused enough distress with the amount of restarts for my players. If it can't work with what i've got I won't use it
> 
> > Can you try with no other plugins installed?
> 
> Im not gonna do that, caused enough distress with the amount of restarts for my players. If it can't work with what i've got I won't use it

You can always use the Stand Aldine geyser version, With this you do not need to restart your server each time you make a change to geyser.

**Comment by Camotoy** [comment]
Yes, though my inquiry was based on the plugins on the server which would not be relevant to my question.

**Comment by Waddl3s** [comment]
> 
> 
> I was able to connect to it once and got het whitelist login screen. Afterwards I was unable to join again yet I got ping. You should check your logs for the username .KobeNetwork.

I dont see your name on the logs, when you were trying to connect I was seeing your IP pop up in console as trying to connect then a few seconds later you disconnected. Guessing that was the whitelist. I've added you to the whitelist incase you try again.

**Comment by Jens-Co** [comment]
> > I was able to connect to it once and got het whitelist login screen. Afterwards I was unable to join again yet I got ping. You should check your logs for the username .KobeNetwork.
> 
> I dont see your name on the logs, when you were trying to connect I was seeing your IP pop up in console as trying to connect then a few seconds later you disconnected. Guessing that was the whitelist. I've added you to the whitelist incase you try again.

I've been trying for a while to connect to your server but still not able to join. If you want and can, would you setup an stand alone geyser ? Less stress for you and we can maybe find out what is causing your problem.

**Comment by Waddl3s** [comment]
Right now im setting up a blank server on the same machine to try it on there

**Comment by Waddl3s** [comment]
Just tried on a blank server then, same thing

**Comment by Waddl3s** [comment]
Fixed

**Comment by Jens-Co** [comment]
> Fixed

Can you please leave a note here what exactly was the problem ? For future like wise problems ?

**Comment by Waddl3s** [comment]
I very stupidly didn't realize I had layer7 protection enabled. I turned DDOs protection onto sensor only
