### ISSUE TITLE
Parrot glitch (Visual)

### ISSUE THREAD

**Issue by ItsObjektNik** [GeyserMC/Geyser#2402]
### Describe the bug

Ok so the bug is parrots which dupe on the shoulder (im not 100 % sure if it comes from geyser but i think bc they only dupe on bedrock) like the parrots dupe on the shoulder somehow and i think if you leave then it is ok again for a while until he hops on the shoulder again. Its only visual tho they (a texture glitch) 
![unknown png (325×476) - Persönlich – Microsoft​ Edge 20 07 2021 22_39_33](https://user-images.githubusercontent.com/87725383/126393144-c30d1aee-6d16-4e7b-b3cc-703aa4b705c7.png)

### To Reproduce

1. You can leave the game 
2. you can just not get a parrot 
Im not sure havent tested alot with it but rejoining helps

### Expected behaviour

There should be only one parrot and this has happened multiple times

### Screenshots / Videos

![unknown png (325×476) - Persönlich – Microsoft​ Edge 20 07 2021 22_39_33](https://user-images.githubusercontent.com/87725383/126393332-e3d738f7-6408-48b1-8cf7-247ccc6423ed.png)

### Server Version and Plugins

Paper (Fork of Spigot) and on 1.17.1 for java 

### Geyser Dump

-

### Geyser Version

the newest one since the 20.7.2021 (europe Date)

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Konicai** [comment]
Hi, can you please share a dump? Run `geyser dump` in your console

**Comment by ItsObjektNik** [comment]
Ok hold on i will do it :D

Konicai ***@***.***> schrieb am Di., 20. Juli 2021, 22:51:

**Comment by ItsObjektNik** [comment]
Do i need to send you the url?

Its Nik ***@***.***> schrieb am Di., 20. Juli 2021, 22:52:

**Comment by Konicai** [comment]
Yes please

**Comment by ItsObjektNik** [comment]
ok btw sry for not doing it i didnt know what it was :/ but here is the
link have a great day or night :D
 https://dump.geysermc.org/Fh4y7EyD09V75cmRQsjaoMV8MZjFuJ0q

Am Di., 20. Juli 2021 um 22:59 Uhr schrieb Konicai ***@***.***

**Comment by Konicai** [comment]
Can you also share a plugin list of the backend server(s) that this is happening on?

**Comment by ItsObjektNik** [comment]
Yes sure can i send a screenshot?


Am Di., 20. Juli 2021 um 23:04 Uhr schrieb Konicai ***@***.***

**Comment by Konicai** [comment]
As long as its clear and readable, yes

**Comment by ItsObjektNik** [comment]
[image: Command Craft _ File Manager - Google Chrome 20.07.2021
23_07_15.png]

Am Di., 20. Juli 2021 um 23:05 Uhr schrieb Its Nik ***@***.***

**Comment by ItsObjektNik** [comment]
i sent a screenshot but i have geyser on bungeecoord do i need to send the
bungeecoord plugin list too?


Am Di., 20. Juli 2021 um 23:07 Uhr schrieb Its Nik ***@***.***

**Comment by Konicai** [comment]
No, the geyser dump contains the bungeecord plugin list

Your screenshot isn't appearing for me though

**Comment by ItsObjektNik** [comment]
Ok i will send them by hand

Konicai ***@***.***> schrieb am Di., 20. Juli 2021, 23:10:

**Comment by ItsObjektNik** [comment]
ok here is my list i will send it like this bc of the screenshot not
appearing:
Citizens-2.0.28-b2347.jar
4.05 MB
Jul 11th, 2021 8:27PM
CombatLogX.jar
211.92 kB
Jul 17th, 2021 4:22AM
EssentialsX-2.18.2.0.jar
1.61 MB
Jul 16th, 2021 6:52PM
EssentialsXChat-2.18.2.0.jar
12.54 kB
Jul 16th, 2021 6:52PM
EssentialsXSpawn-2.18.2.0.jar
16.88 kB
Jul 16th, 2021 7:47PM
LuckPerms-Bukkit-5.3.47 (5).jar
1.26 MB
Jul 17th, 2021 1:19AM
Multiverse-Core-4.3.0.jar
459.07 kB
Jul 11th, 2021 8:27PM
Multiverse-Inventories-4.2.2.jar
329.94 kB
Jul 14th, 2021 7:41PM
Multiverse-NetherPortals-4.2.1.jar
48.41 kB
Jul 11th, 2021 8:27PM
Multiverse-Portals-4.2.1.jar
106.44 kB
Jul 11th, 2021 8:27PM
OpenInv.jar
116.97 kB
Jul 11th, 2021 8:27PM
PerWorldChatPlus_5.1.1v









PsudoCommands
SirBlobmanCore-2.2.4
TpLogin-4.2.0
Vault
worldedit-bukkit-7.2.5-dist
worldguard-bukkit-7.0.5-dist

CREATE DIRECTORY
UPLOAD


Am Di., 20. Juli 2021 um 23:08 Uhr schrieb Its Nik ***@***.***

**Comment by ItsObjektNik** [comment]
ohh no i sent my mail on accident is it ok like this or do you want me to
sort it? if you want then i can sort the plugins for you again i have no
problem with that
:D

Am Di., 20. Juli 2021 um 23:17 Uhr schrieb Its Nik ***@***.***

**Comment by Konicai** [comment]
If you could remove the dates and sizes and extra space it would be easier to read, thanks

**Comment by ItsObjektNik** [comment]
Here a better list im sorry
                          Citizens-2.0.28-b2347.jar
4.05 MB
Jul 11th, 2021 8:27PM
CombatLogX.jar
211.92 kB
Jul 17th, 2021 4:22AM
EssentialsX-2.18.2.0.jar
1.61 MB
Jul 16th, 2021 6:52PM
EssentialsXChat-2.18.2.0.jar
12.54 kB
Jul 16th, 2021 6:52PM
EssentialsXSpawn-2.18.2.0.jar
16.88 kB
Jul 16th, 2021 7:47PM
LuckPerms-Bukkit-5.3.47 (5).jar
1.26 MB
Jul 17th, 2021 1:19AM
Multiverse-Core-4.3.0.jar
459.07 kB
Jul 11th, 2021 8:27PM
Multiverse-Inventories-4.2.2.jar
329.94 kB
Jul 14th, 2021 7:41PM
Multiverse-NetherPortals-4.2.1.jar
48.41 kB
Jul 11th, 2021 8:27PM
Multiverse-Portals-4.2.1.jar
106.44 kB
Jul 11th, 2021 8:27PM
OpenInv.jar
116.97 kB
Jul 11th, 2021 8:27PM
PerWorldChatPlus_5.1.1v.jar
57.29 kB
Jul 17th, 2021 8:59PM
PsudoCommands.jar
17.64 kB
Jul 17th, 2021 5:46PM
SirBlobmanCore-2.2.4.jar
516.34 kB
Jul 17th, 2021 4:24AM
TAB.v2.9.2.jar
604.05 kB
Jul 17th, 2021 2:57AM
TpLogin-4.2.0 (3).jar
64.3 kB
1 day ago
Vault.jar
265.88 kB
Jul 11th, 2021 8:27PM
worldedit-bukkit-7.2.5-dist.jar
4.2 MB
Jul 11th, 2021 8:27PM
worldguard-bukkit-7.0.5-dist.jar
1.09 MB

**Comment by ItsObjektNik** [comment]
Ohh ok i will remove the data and sizes

Konicai ***@***.***> schrieb am Di., 20. Juli 2021, 23:20:

**Comment by ItsObjektNik** [comment]
Citizens-2.0.28-b2347.jar

CombatLogX

EssentialsX-2.18.2.0

EssentialsXChat-2.18.2.0
EssentialsXSpawn-2.18.2.0

LuckPerms-Bukkit-5.3.47
Multiverse-Core-4.3.0

Multiverse-Inventories-4.2.2

Multiverse-NetherPortals-4.2.1

Multiverse-Portals-4.2.1
Opening

PerWorldChatPlus_5.1.1v

PsudoCommands

SirBlobmanCore-2.2.4

TAB.v2.9.2

TpLogin-4.2.0
Vault

worldedit-bukkit-7.2.5-dist

worldguard-bukkit-7.0.5-dist


Am Di., 20. Juli 2021 um 23:21 Uhr schrieb Its Nik ***@***.***
>:

> Here a better list im sorry
>                           Citizens-2.0.28-b2347.jar
> 4.05 MB
> Jul 11th, 2021 8:27PM
> CombatLogX.jar
> 211.92 kB
> Jul 17th, 2021 4:22AM
> EssentialsX-2.18.2.0.jar
> 1.61 MB
> Jul 16th, 2021 6:52PM
> EssentialsXChat-2.18.2.0.jar
> 12.54 kB
> Jul 16th, 2021 6:52PM
> EssentialsXSpawn-2.18.2.0.jar
> 16.88 kB
> Jul 16th, 2021 7:47PM
> LuckPerms-Bukkit-5.3.47 (5).jar
> 1.26 MB
> Jul 17th, 2021 1:19AM
> Multiverse-Core-4.3.0.jar
> 459.07 kB
> Jul 11th, 2021 8:27PM
> Multiverse-Inventories-4.2.2.jar
> 329.94 kB
> Jul 14th, 2021 7:41PM
> Multiverse-NetherPortals-4.2.1.jar
> 48.41 kB
> Jul 11th, 2021 8:27PM
> Multiverse-Portals-4.2.1.jar
> 106.44 kB
> Jul 11th, 2021 8:27PM
> OpenInv.jar
> 116.97 kB
> Jul 11th, 2021 8:27PM
> PerWorldChatPlus_5.1.1v.jar
> 57.29 kB
> Jul 17th, 2021 8:59PM
> PsudoCommands.jar
> 17.64 kB
> Jul 17th, 2021 5:46PM
> SirBlobmanCore-2.2.4.jar
> 516.34 kB
> Jul 17th, 2021 4:24AM
> TAB.v2.9.2.jar
> 604.05 kB
> Jul 17th, 2021 2:57AM
> TpLogin-4.2.0 (3).jar
> 64.3 kB
> 1 day ago
> Vault.jar
> 265.88 kB
> Jul 11th, 2021 8:27PM
> worldedit-bukkit-7.2.5-dist.jar
> 4.2 MB
> Jul 11th, 2021 8:27PM
> worldguard-bukkit-7.0.5-dist.jar
> 1.09 MB
>
>

**Comment by Chew** [comment]
Please avoid spamming this issue, several people get notifications for every reply...

**Comment by ItsObjektNik** [comment]
Take this list which i sent you last because its the best one sry didnt see
the message earlier next time i will just put them into a document or
something it would be easier do you need anything else? :D

Am Di., 20. Juli 2021 um 23:24 Uhr schrieb Its Nik ***@***.***
>:

> Citizens-2.0.28-b2347.jar
>
> CombatLogX
>
> EssentialsX-2.18.2.0
>
> EssentialsXChat-2.18.2.0
> EssentialsXSpawn-2.18.2.0
>
> LuckPerms-Bukkit-5.3.47
> Multiverse-Core-4.3.0
>
> Multiverse-Inventories-4.2.2
>
> Multiverse-NetherPortals-4.2.1
>
> Multiverse-Portals-4.2.1
> Opening
>
> PerWorldChatPlus_5.1.1v
>
> PsudoCommands
>
> SirBlobmanCore-2.2.4
>
> TAB.v2.9.2
>
> TpLogin-4.2.0
> Vault
>
> worldedit-bukkit-7.2.5-dist
>
> worldguard-bukkit-7.0.5-dist
>
>
> Am Di., 20. Juli 2021 um 23:21 Uhr schrieb Its Nik <
> ***@***.***>:
>
>> Here a better list im sorry
>>                           Citizens-2.0.28-b2347.jar
>> 4.05 MB
>> Jul 11th, 2021 8:27PM
>> CombatLogX.jar
>> 211.92 kB
>> Jul 17th, 2021 4:22AM
>> EssentialsX-2.18.2.0.jar
>> 1.61 MB
>> Jul 16th, 2021 6:52PM
>> EssentialsXChat-2.18.2.0.jar
>> 12.54 kB
>> Jul 16th, 2021 6:52PM
>> EssentialsXSpawn-2.18.2.0.jar
>> 16.88 kB
>> Jul 16th, 2021 7:47PM
>> LuckPerms-Bukkit-5.3.47 (5).jar
>> 1.26 MB
>> Jul 17th, 2021 1:19AM
>> Multiverse-Core-4.3.0.jar
>> 459.07 kB
>> Jul 11th, 2021 8:27PM
>> Multiverse-Inventories-4.2.2.jar
>> 329.94 kB
>> Jul 14th, 2021 7:41PM
>> Multiverse-NetherPortals-4.2.1.jar
>> 48.41 kB
>> Jul 11th, 2021 8:27PM
>> Multiverse-Portals-4.2.1.jar
>> 106.44 kB
>> Jul 11th, 2021 8:27PM
>> OpenInv.jar
>> 116.97 kB
>> Jul 11th, 2021 8:27PM
>> PerWorldChatPlus_5.1.1v.jar
>> 57.29 kB
>> Jul 17th, 2021 8:59PM
>> PsudoCommands.jar
>> 17.64 kB
>> Jul 17th, 2021 5:46PM
>> SirBlobmanCore-2.2.4.jar
>> 516.34 kB
>> Jul 17th, 2021 4:24AM
>> TAB.v2.9.2.jar
>> 604.05 kB
>> Jul 17th, 2021 2:57AM
>> TpLogin-4.2.0 (3).jar
>> 64.3 kB
>> 1 day ago
>> Vault.jar
>> 265.88 kB
>> Jul 11th, 2021 8:27PM
>> worldedit-bukkit-7.2.5-dist.jar
>> 4.2 MB
>> Jul 11th, 2021 8:27PM
>> worldguard-bukkit-7.0.5-dist.jar
>> 1.09 MB
>>
>>

**Comment by ItsObjektNik** [comment]
Ohh im sorry i didnt meant to i will send a document next time i got
confused bc of the copy paste and stuff and had to resend it

Olivia ***@***.***> schrieb am Di., 20. Juli 2021, 23:26:
