### ISSUE TITLE
When will Java players be able to see Bedrock Player's Skins

### ISSUE THREAD

**Issue by Lucien950** [GeyserMC/Geyser#2404]
### What feature do you want to see added?

In the title

### Are there any alternatives?

I've tried SkinRestorer I guess

**Comment by Camotoy** [comment]
We are actively working on making the skin experience better using Floodgate. It's not easy as we need to upload skins to Mojang servers. Please be patient!!

**Comment by Lucien950** [comment]
@Camotoy Is there an issue/PR for this so I can follow along?

**Comment by Konicai** [comment]
Not really, the skin upload queue through floodgate/global api has an estimated wait time of `1 week 6 days 13 hours 18 minutes` (join https://discord.gg/GeyserMC and run `/queue` )
