### ISSUE TITLE
Limit Ip 

### ISSUE THREAD

**Issue by StormXd12** [GeyserMC/Geyser#2405]
### Describe the bug

All bedrock and pe version can't join the server it's telling that they have exhausted the limit per ip

### To Reproduce

I don't know how to fix it 

### Expected behaviour

Idk

### Screenshots / Videos

![](https://cdn.discordapp.com/attachments/795996234723754055/865610674515738634/Screenshot_2021_0716_203726.jpg)

### Server Version and Plugins

1.17.1

### Geyser Dump

https://dump.geysermc.org/bVIn1u8CRhUcPExp5rQMn2k4auY3dtZ4

### Geyser Version

1.4.1 Snapshot (git-master-4e629fe)

### Additional Context

Pls tell a solution

**Comment by Tim203** [comment]
A bit more context would've been nice, however, this is not a vanilla message.
So try to find the plugin that's causing this and contact them to (for example) use the Floodgate API if they have to.

**Comment by Camotoy** [comment]
Closing as this isn't a Geyser/Floodgate issue and probably a result of nLogin. However, as a side effect of other changes we are making, this issue will eventually be fixed on most plugin platforms.
