### ISSUE TITLE
Optional Killer Bunny texture

### ISSUE THREAD

**Issue by FarLanderCraft** [GeyserMC/Geyser#2411]
### What feature do you want to see added?

I would like it if there was an option to add the Killer Bunny texture to Bedrock, preferably built into `add-non-bedrock-items` (the option that adds the Furnace Minecart), as The Killer Bunny looks like a normal white rabbit in Bedrock, even with this enabled.
![image](https://user-images.githubusercontent.com/67613281/126837533-771ee475-e89e-4f60-957e-f9d362b4abb3.png)

### Are there any alternatives?

**There is no alternative.**
lol Perhaps the option to add a resource/behavior pack for The Killer Bunny? 
(Not an alternative I've tried, as, well, I don't know if any alternative would exist...)

**Comment by Camotoy** [comment]
https://github.com/GeyserMC/GeyserOptionalPack :)

**Comment by FarLanderCraft** [comment]
I genuinely didn't notice that, sorry lol .

**Comment by FarLanderCraft** [comment]
> https://github.com/GeyserMC/GeyserOptionalPack :)

And thank you.
