### ISSUE TITLE
Bedrock Player model and hitbox does not move

### ISSUE THREAD

**Issue by Skullgen** [GeyserMC/Geyser#2414]
### Describe the bug

First off I just want to that I do not know about programs. I'm just a player that found a bug. I use a lan app to connect my ps4 to geyserconnect.net to play java servers.

When I use geyser to connect to a java server I'm able to move but my character dousnt move. I see myself move but everyone else sees me stand still. If I try to break/place a block or access a server menu to far away from where my body is it wont work. I'm able to do all that when I'm close to my body. I've tried restarting, re logging, deleting and reinstalling minecraft. I've tried 4 separate Java servers all of them used to work.

### To Reproduce

Idk

### Expected behaviour

I should be able to play the game normally

### Screenshots / Videos

N/A if needed I can get some

### Server Version and Plugins

Multiple servers

### Geyser Dump

Idk

### Geyser Version

Idk

### Minecraft: Bedrock Edition Version

Up to date ps4 version

### Additional Context

I'm sorry if I wrote that all out of format. Like i said i dont know code and I'm just a player reporting a bug

**Comment by Skullgen** [comment]
I want to add that I found  similar bug reports but they said that a simple relogging in fixed it. I have tried relogging a lot of times

**Comment by TheMonBonGH** [comment]
None of this information helps, **at all**. Also, we don't host the public geyser connect, greaper88 does. Please make this more detailed, or the team won't understand this.

**Comment by Camotoy** [comment]
I'm going to close this, as we just can't get any information from this unless we know what plugins and server type is running on the backend. If you're able to provide a Geyser dump, then we can reopen. We are aware that this is an issue, however. Thanks.

**Comment by Skullgen** [comment]
Thank you for the response. I'm sorry I'm unable to provide the required information. I didnt realize that this wasn't the place to report bugs on geyserconnect.net. For my misunderstanding of this site, and my inability to find the information you need to help me find the problem, I do honestly apologize.  thank you

**Comment by Camotoy** [comment]
It's OK. Your bug probably belongs here but without knowing server information we can't do anything about it when we don't normally have this issue.
