### ISSUE TITLE
errer

### ISSUE THREAD

**Issue by JekoTC** [GeyserMC/Geyser#2415]
### Describe the bug

25.07 15:38:22 [Server] ERROR io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
25.07 15:38:23 [Server] INFO [Geyser-BungeeCord]: Bedrock user with ip: /172.58.36.74 has disconnected for reason CLOSED_BY_REMOTE_PEER
25.07 15:39:02 [Server] INFO [Geyser-BungeeCord]: /27.71.83.205:44727 tried to connect!
25.07 15:39:04 [Server] INFO [Geyser-BungeeCord]: Player connected with username Sangdeptrii
25.07 15:39:22 [Server] INFO [Geyser-BungeeCord]: Attempting to login using floodgate mode... authentication will be encrypted.
25.07 15:39:22 [Server] INFO [Geyser-BungeeCord]: Sangdeptrii (logged in as: Sangdeptrii) has connected to remote java server on address 139.99.19.5
25.07 15:39:22 [Server] INFO [Geyser-BungeeCord]: Sangdeptrii has disconnected from remote Java server on address 139.99.19.5 because of io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe

### To Reproduce

25.07 15:38:22 [Server] ERROR io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe
25.07 15:38:23 [Server] INFO [Geyser-BungeeCord]: Bedrock user with ip: /172.58.36.74 has disconnected for reason CLOSED_BY_REMOTE_PEER
25.07 15:39:02 [Server] INFO [Geyser-BungeeCord]: /27.71.83.205:44727 tried to connect!
25.07 15:39:04 [Server] INFO [Geyser-BungeeCord]: Player connected with username Sangdeptrii
25.07 15:39:22 [Server] INFO [Geyser-BungeeCord]: Attempting to login using floodgate mode... authentication will be encrypted.
25.07 15:39:22 [Server] INFO [Geyser-BungeeCord]: Sangdeptrii (logged in as: Sangdeptrii) has connected to remote java server on address 139.99.19.5
25.07 15:39:22 [Server] INFO [Geyser-BungeeCord]: Sangdeptrii has disconnected from remote Java server on address 139.99.19.5 because of io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe

### Expected behaviour

Idk

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/85834402/126891652-82675f8d-b242-4e41-9f16-1335aa30306f.png)

### Server Version and Plugins

main : This server is running Purpur version git-Purpur-1255 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 89c9c90 on HEAD)
Auth : This server is running Purpur version git-Purpur-1255 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 89c9c90 on HEAD)
Queue : This server is running Purpur version git-Purpur-1255 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 89c9c90 on HEAD)
Bungee This server is running Waterfall version git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448 by md_5

### Geyser Dump

https://dump.geysermc.org/X5RJlIoLXFd5vUOpy7dUY3K93ysJlilN

### Geyser Version

Geyser version 1.4.1-SNAPSHOT (git-master-e73b7f5) (Java: 1.17.1, Bedrock: 1.17.0/1.17.1/1.17.2 - 1.17.10)

### Minecraft: Bedrock Edition Version

1.17 and 1.17.10

**Comment by Jens-Co** [comment]
Hello there, it's know that beta clients will not work with geyser. You can switch back to the normal (non beta) client and check if the error persists and if so let me know.

**Comment by Camotoy** [comment]
Disable `use-proxy-protocol`.

**Comment by JekoTC** [comment]
> Hello there, it's know that beta clients will not work with geyser. You can switch back to the normal (non beta) client and check if the error persists and if so let me know.

im not use bete cilents

**Comment by JekoTC** [comment]
> Hello there, it's know that beta clients will not work with geyser. You can switch back to the normal (non beta) client and check if the error persists and if so let me know.

please connect through the official geyser

> Disable `use-proxy-protocol`. The beta client you're using is not recommended (use 1.17.10.04 instead), but it will connect to Geyser.

please connect through the official geyser
