### ISSUE TITLE
Honeycomb displays when attempting to craft

### ISSUE THREAD

**Issue by SightedBike273** [GeyserMC/Geyser#2416]
### Describe the bug

When attempting to craft, a honeycomb ghost block shows. If you do craft an item, it will only be a ghost item and can't be used.

### To Reproduce

1) Open inventory or crafting table
2) The honeycomb will display

### Expected behaviour

The honeycomb shouldn't display and crafting should work as intended.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/73698519/126897964-811497c4-a6d4-47cb-ba84-b9510b529dc1.png)
![image](https://user-images.githubusercontent.com/73698519/126897965-985a097d-1029-43cd-9e81-b4f81287a2c0.png)

### Server Version and Plugins

![image](https://user-images.githubusercontent.com/73698519/126897950-bfc05d53-d6aa-4126-b8d3-1caa7ca90eb3.png)
![image](https://user-images.githubusercontent.com/73698519/126897958-2ad97435-8da6-477f-97ee-ce67a71dd4cc.png)

### Geyser Dump

https://dump.geysermc.org/PMnNf94qZy6umyKaRlFiNZYt3W8aZOVa

### Geyser Version

1.4.1-SNAPSHOT (git-master-143464b)

### Minecraft: Bedrock Edition Version

1.17.1

### Additional Context

I had had this problem in the past and I fixed it by reinstalling but that isn't working now

**Comment by Altamash347** [comment]
Please fix this as soon as possible, me and sighted are having this problem for our MCPE server.

**Comment by Camotoy** [comment]
Please do not bump issues in the future and instead add new data to your existing issue in the future. 

Seeing as most people have not reported such an issue, your error likely comes down to a plugin error or Paper/Spigot config setting. For the plugin part, please try these steps:

- Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by Camotoy** [comment]
Also, please make sure Java Edition clients do not see the same thing.

**Comment by Jens-Co** [comment]
Hello @SightedBike273, since you closed the issue did you found your problem ? Could you perhaps leave some feedback to what plugin etc was causing your issue ?
Thanks :)

**Comment by SightedBike273** [comment]
It was my permission plugin. I'm so sorry for creating the issue.

**Comment by SightedBike273** [comment]
It was an API plugin that was messing with the inventory. Sorry for creating this issue
