### ISSUE TITLE
ProtocolLib plugin preventing non-OP users from building/breaking/opening/closing anything

### ISSUE THREAD

**Issue by 1017rg** [GeyserMC/Geyser#2418]
### Describe the bug

I run a local online non-cracked PaperMC server using my IP and the standard ports in the geyser config, only my brother & I play, and I had troubles doing anything without making ourselves OP. After installing my favorite plugins one-by-one and testing the server--stopping and restarting, I discovered a small conflict with the plugin ProtocolLib and the overall playability of a non-OP user.

### To Reproduce

1) Download ProtocolLib (for spigot) plugin
2) Upload ProtocolLib.jar into 'plugins' file of server
3) Stop and Restart server to fully install ProtocolLib plugin
4) Start server and load into world
5) Try breaking blocks as a NON-OP user

### Expected behaviour

Non-OP'd users in the server will not be allowed to interact with the world at all, even with permissions granted, even using UUID for permission granting. Only OP users will be able to play regularly.

### Screenshots / Videos

https://user-images.githubusercontent.com/33552523/126911266-bdc7f16b-8871-49e4-b5ce-87b36f2a9c55.mp4

### Server Version and Plugins

**Server Version**: PaperMC 1.17.1

**Plugins**: ProtocolLib

### Geyser Dump

https://dump.geysermc.org/U6cewHTj2aWpkC0H4klEkWnEm0DHNeX6

### Geyser Version

Geyser Spigot v1.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.1

### Additional Context

Unfortunately, I wasn't running ProtocolLib for this dump I linked here, so my apologies if it's not in there. But I can assure as of right now, the problem is very easy to reproduce. I didn't bother changing any configs of ProtocolLib. I only noticed that it was conflicting with any non-OP playability in the game. (I use ProtocolLib only to display the HUD for another plugin named 'LevelledMobs' ; without ProtocolLib it won't show the HUD that includes the mob Lvl. Health and Name) Thank you Geyser team <3

**Comment by Camotoy** [comment]
I am unable to confirm this with a non-opped player and the latest release ProtocolLib. Have you tried with *just* ProtocolLib?

https://dump.geysermc.org/ABsYmv4Qmprul99gWUlOKw9ZycRMoEot

**Comment by 1017rg** [comment]
I have not tried only ProtocolLib as the only plugin. I can definitely try that out and report back

**Comment by 1017rg** [comment]
I installed the plugins backward this time. It was working fine until I load up my Java account character into my world. Java acc. somehow isn't allowed to do anything non-OP while the Bedrock account can do everything non-OP without a problem.

**Comment by 1017rg** [comment]
it just has a mind of it's own honestly I have no idea what the issue is. i set perms for myself and all of sudden can't do anything

**Comment by Jens-Co** [comment]
Hi there, does this happen for Java to ?

**Comment by 1017rg** [comment]
Hello. Yeah it happens on both really; I test the OP and non-OP settings on my Bedrock account to verify that it'll work for my friend on PS4 but when I switch to Java it goes kinda haywire! I don't know what could possibly be triggering that issue, I really thought I had it fixed for a sec.

**Comment by 1017rg** [comment]
I'm assuming it conflicts with another plugin I have but after installing them one-by-one I hadn't seen any issues until I played in my original world. My other plugins installed are: 
EssentialsX 
EssentialsXChat 
LuckPerms
Vault
PCGF_PluginLib
Minepacks
ReviveMe
smoothtimber

and of course the Geyser and floodgate.jar files

**Comment by Camotoy** [comment]
If Java players are affected, then it's very very likely not us. Try removing Floodgate and Geyser at this point.

**Comment by Jens-Co** [comment]
Can you upload your latest.log here ? You can use this link to hide ip's https://mclo.gs/ :) not sure if this is a Geyser related issue.

**Comment by 1017rg** [comment]
I see, I'll definitely mess around a bit more to see if I can find a fix. Thank you for the support! https://mclo.gs/vd6qA1P

**Comment by Jens-Co** [comment]
Something is odd on the way you give perms to player. Can you use command /lp editor? This will send an link to a webpage, the best thing you can do is add all needed perms in the default group press save paste the link that will be given on saving into console and try a few commands.

**Comment by Jens-Co** [comment]
> Something is odd on the way you give perms to player. Can you use command /lp editor? This will send an link to a webpage, the best thing you can do is add all needed perms in the default group press save paste the link that will be given on saving into console and try a few commands.

Side note do not add op commands into default as this rank will be given to all player. Make a new group "admin" for all op commands.

**Comment by ZodiussDev** [comment]
im pretty sure you have spawn protection on or something lol. turn it off in server.properties

**Comment by Konicai** [comment]
We haven't had any similar reports recently - please let us know if you're still having this issue
