### ISSUE TITLE
fireworks not working

### ISSUE THREAD

**Issue by aj821** [GeyserMC/Geyser#2419]
### Describe the bug

fireworks not translated from java to bedrock?

also i check this page
https://github.com/GeyserMC/Geyser/wiki/Current-Limitations

### To Reproduce

take firework from creative menu.
place/launch firework both bedrock and java
ps4 bedrock not show
ios bedrocks is fine.

### Expected behaviour

on java client firework is visible when launched by java and bedrock players.
on bedrock client firework is not seen as if nothing happens.
ps4 bedrock not show
ios bedrocks is fine.

### Server Version and Plugins

setup details
server ver 1.17.1 spigot
client java 1.17.1 vanilla
client bedrock 1.17.1
geyser ver 781 spigot

Plugins (19): LuckPerms, SwearFilter, TitleAPI, MinecartSpeedPlus, Vault, floodgate, WorldEdit, Essentials, EssentialsChat, Geyser-Spigot, RandomTP, PlotSquared, EssentialsSpawn, Multiverse-Core, WorldGuard, Multiverse-SignPortals, Multiverse-Inventories, Multiverse-Portals, ProtectionStones

### Geyser Dump

https://dump.geysermc.org/P3li11gXNkTLluR4aoiGe0kPa3UiXwHi

### Geyser Version

1.4.1  latest

### Minecraft: Bedrock Edition Version

1.17.1

### Additional Context
update 
bedrock client on ps4 appears to show the issue 
bedrock client on ios shows firework just fine
personally still investigating why

**Comment by Konicai** [comment]
Can you provide a geyser dump, as the bug report form requests, please

**Comment by aj821** [comment]
> Can you provide a geyser dump, as the bug report form requests, please

should i leave link or send full dump?

**Comment by Konicai** [comment]
A link here is good

**Comment by aj821** [comment]
> A link here is good

link and plugin list edited in.

**Comment by aj821** [comment]
update appears to be a consul problem

**Comment by Camotoy** [comment]
This is currently intentional, as there was previously a bug involving fireworks that crashed consoles. I'm closing this as the behavior is intentional, but will try to circle back and see if the firework blocking can be rolled back.
