### ISSUE TITLE
Text not visible on a white background

### ISSUE THREAD

**Issue by Heath123** [GeyserMC/Geyser#242]
**Describe the bug**
Text is always set to white instead on the default colour, causing problems with white backgrounds

**To Reproduce**
1. Open your terminal of choice (Gnome Terminal, Command Prompt, Powershell...)
2. Set the background to white and the text to black
3. Run Geyser

**Expected behavior**
The text should be the default colour (black)

**Screenshots**
![image](https://user-images.githubusercontent.com/13787163/77553741-193c4800-6ead-11ea-81d8-c584f78f3f2c.png)

**Server version**
N/A

**Geyser version**
Jenkins

**Bedrock version**
N/A

**Additional context**
N/A

**Comment by LegacyGamerHD** [comment]
this is more a issue on gnome i sepose

**Comment by Heath123** [comment]
> this is more a issue on gnome i sepose

No, most programs work fine with it.
