### ISSUE TITLE
server freezes when a bedrock player joins, due to excessive CPU and RAM usage

### ISSUE THREAD

**Issue by PIZZAAXX** [GeyserMC/Geyser#2421]
### Describe the bug

Basically what the title says, the server CPU and RAM usage skyrockets when a bedrock client joins the server, causing the server to freeze and kick everyone after some time. Then, the server has to be killed because it doesn't get fixed after everyone has been kicked, it just remains frozen.

### To Reproduce

I don't know what to put here

### Expected behaviour

Normal CPU and RAM usage.

### Screenshots / Videos

Normal CPU and RAM usage:
![image](https://user-images.githubusercontent.com/75264687/127029000-568cd4b8-9fcf-425e-8f49-7d8daf653d49.png)

CPU and RAM usage when a Bedrock client joins:
![image](https://user-images.githubusercontent.com/75264687/127029232-3cba1296-cffd-4337-801f-3839903c5678.png)

### Server Version and Plugins

**Main server:** `[16:45:55 INFO]: This server is running Mohist version 1.12.2-225 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2855)`
**Plugins:** WorldGuard, WorldEdit, Essentials, LightCleaner, Skript (and many addons), Citizens, BungeeGuard, Vault, Luckperms
**Mods:** WorldEdit, Terra++, CubicChunks, CubicWorldGen, JourneyMap, Terramap

**BungeeCord Proxy:** Waterfall-1.17-448
**Plugins:** BungeeGuard, Floodgate (#19), Geyser (#781), ServerListPlus, ViaBackwards, ViaRewind, ViaVersion

### Geyser Dump

https://dump.geysermc.org/CeHjcjeYDCkaq9Bl9pMG7VghFiDFMuyp

### Geyser Version

Build #781

### Minecraft: Bedrock Edition Version

1.17.1

**Comment by Konicai** [comment]
I assume thats the CPU and RAM of the bungeecord? 

Also, could you share your full server logs through https://mclo.gs ?

**Comment by Camotoy** [comment]
^ BungeeCord specifically; the backend logs are irrelevant to us.

**Comment by PIZZAAXX** [comment]
yes, the BungeeCord server

https://mclo.gs/j7gXqpN

**Comment by Camotoy** [comment]
Please add `-XX:+HeapDumpOnOutOfMemoryError` to your BungeeCord startup logs. This will generate a file with your Java memory contents we can use to analyze when the error occurs. Send that file to us and we can analyze it.

**Comment by PIZZAAXX** [comment]
I'm waiting for my host to change the startup command since I can't change it directly.

**Comment by PIZZAAXX** [comment]
where should be the file?

**Comment by Camotoy** [comment]
You can upload it here via any storage provider or DM me on Discord.

**Comment by PIZZAAXX** [comment]
yes, but where in the server files is that file?

**Comment by Camotoy** [comment]
Ah, my apologies. It should be in the same directory as your BungeeCord file and end in `.hprof`.

**Comment by Camotoy** [comment]
This is likely a CubicChunks issue - non-full-chunks no longer exist in 1.17, causing ViaVersion to send massive MultiBlockChange packets which in turn get sent as an individual packet for each block (as Bedrock has no multi-block-update packet, unlike Java). Queuing all those packets up means giant RAM usage leading to your situation. 

Try testing without cubic chunks, if possible? If that is the issue, we're discussing workarounds.

**Comment by RednedEpic** [comment]
We’ve discussed this internally and unfortunately at this point in time there is very little we’re able to do here. With 1.18 around the corner and bringing the potential for data driven world heights on Bedrock, we’re hopeful that we’ll be able to find an alternative in the near future but right now our options are quite limited.

I’m going to close this issue, but thank you for taking the time to open this report.

**Comment by Camotoy** [comment]
More specifically: the exact issue here is very convoluted. ViaVersion takes sub-chunk packets from pre-1.16 and makes them into multi-block packets. Geyser currently has to take this information and divide it into 4096 individual packets. It would just be better in this case to have a Cubic Chunks designed for the 1.17 protocol - my vanilla 1.17 client didn't have a fun time either. If someone *would* like to take a stab at improving this scenario, by all means, feel free, but the core team going to leave this specific scenario as-is.
