### ISSUE TITLE
Bedrock Client Crashing Using Incendium datapack

### ISSUE THREAD

**Issue by Robert-Kidder** [GeyserMC/Geyser#2423]
### Describe the bug

I added a data packet named "[Incendium](https://www.planetminecraft.com/data-pack/incendium-nether-expansion/)" to the data packet of the world. This data packet made some changes for Nether, but when I entered the changed Nether through the Bedrock Edition client, The client always crashes unexpectedly, and above-bedrock-nether-building is true. When I use the Java version of the client, I can enter the Nether normally.

### To Reproduce

1. Put the "[Incendium](https://www.planetminecraft.com/data-pack/incendium-nether-expansion/)" datapack
2. Start the server
3. After the world is generated, close the server and restart
4. Use the Bedrock Edition client to enter the server
5. Entering the Nether, the Bedrock Edition client crashes

### Expected behaviour

Using "[Incendium](https://www.planetminecraft.com/data-pack/incendium-nether-expansion/)" as the server's data package, the client no longer crashes when entering the Nether through the Bedrock Edition client

### Screenshots / Videos

After entering the Nether, the Bedrock Edition client crashes

### Server Version and Plugins

Main server: This server is running Paper version git-Paper-133 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b32a3b1)
Plugins: Geyser-Spigot (#2422 ）

### Geyser Dump

https://dump.geysermc.org/2hVG1DS6DeD80C8t20qiGnUeFxGrhF1Q

### Geyser Version

1.4.1-SNAPSHOT (git-master-e0e6605)

### Minecraft: Bedrock Edition Version

1.17.10

### Additional Context

Whether or not above-bedrock-nether-building is true, the crash of the Bedrock Edition client will always happen

**Comment by Konicai** [comment]
Like due to this https://github.com/GeyserMC/Geyser/issues/2400#issuecomment-885983765

**Comment by Camotoy** [comment]
This user said the crash also happened without extended world height, so the issues are unrelated then.

**Comment by Konicai** [comment]
Pretty sure the client crashes whenever a chunk is loaded in the nether that contains an Incendium biome. I joined the nether and only crashed once I went close enough to one of the biomes

**Comment by Robert-Kidder** [comment]
@Konicai thank! It turned out to be because of the addition of a new nether biome. May this problem be solved in the future, or... just wait for mojang to make changes?

**Comment by Camotoy** [comment]
This will be addressed in the future by us.

**Comment by Camotoy** [comment]
Fixed with 7a99aa0.
