### ISSUE TITLE
Error joining

### ISSUE THREAD

**Issue by ZayanPlayz** [GeyserMC/Geyser#2424]
### Describe the bug

whenever I join it says 

sorry, but your using invalid nickname

### To Reproduce

1. joining
2. error comes

### Expected behaviour

it's supposed to perfectly join and log in by doing /login or /register

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/78526458/127136676-342d6136-025b-42b2-9543-88cd415d4a4e.png)

### Server Version and Plugins

AccountGuard*, AdvancedMention*, AltDetector, AntiJoinBot*, AntiLagReloaded*, AntiProxyJoin*, AureliumSkills, DiscordSRV, EconomyShopGUI, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, FarmProtect*, floodgate, Geyser-Spigot, GriefPrevention, GSit, HolographicDisplays, NoMobLag, NoPlugins, OnePlayerSleep, OpeNLogin, PlaceholderAPI, PlayTime*, PowerRanks, ServerMinimap, SilkSpawners, SkinsRestorer, TabList, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, WorldEdit, WorldGuard

This server is running Paper version git-Paper-133 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b32a3b1)
You are running the latest version
Previous version: git-Paper-132 (MC: 1.17.1)

### Geyser Dump

https://dump.geysermc.org/z77O7k4Mb6vwR4OjpNLt4qZxm8wIpA4a

### Geyser Version

782 (Bedrock v1.17.0 - v1.17.10)

### Minecraft: Bedrock Edition Version

1.17.10

### Additional Context

Nothing... Just that error :/

**Comment by Jens-Co** [comment]
Hello there, I do not give support on fixing cracked servers. Floodgate adds an prefix "." That login plugins cannot handle therefore giving you that error. Simple fix would be using Online-mode and removing the login plugin. 
thanks.

**Comment by Konicai** [comment]
Since the login plugin is blocking the character, consider contacting them
