### ISSUE TITLE
Already bro?

### ISSUE THREAD

**Issue by JekoTC** [GeyserMC/Geyser#2428]
### Describe the bug

Im already use use-proxy-protocol bro

### To Reproduce

Please help

### Expected behaviour

Why im already something error?

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/85834402/127235673-e5233a87-b383-409d-bc69-9f2e777a7f3b.png)

### Geyser Version

Geyser version 1.4.1-SNAPSHOT (git-master-e73b7f5) (Java: 1.17.1, Bedrock: 1.17.0/1.17.1/1.17.2 - 1.17.10)

**Comment by Heath123** [comment]
You need to turn it off
