### ISSUE TITLE
bedrick players cant break blocks 

### ISSUE THREAD

**Issue by JOrge1578** [GeyserMC/Geyser#2431]
### Describe the bug

whenever a bedrock player joins they can't break anything or open anything, i have already installed and setup luckperms but it still doesn't work, i have to op them for them to be able to do anything. i have tried asking on the discord but it has lead nowhere. im using spigot and have the geyser, floodgate, luckperms, 
. i alreay allowed invalid usernames on luck perm and have assigned the basic default group. 

### To Reproduce

1. start server
2. bedrock player joins
3. bedrock player cant break anything unless op is assigned 

### Expected behaviour

bedrock player not being able to do anything unless they have op 

### Server Version and Plugins

[latest.log](https://github.com/GeyserMC/Geyser/files/6896533/latest.log)

### Geyser Dump

https://dump.geysermc.org/qqpbUkQBDAHbAhlA7e8SgyFEdM3AC4UO

### Geyser Version

1.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17/1

### Additional Context

i also get spammed with player moved wrongly and i had to change the threshold

**Comment by Konicai** [comment]
Has the bedrock player left the spawn protection radius? Have you tried removing all your plugins except Geyser and Floodgate and seeing if this still persists?

**Comment by Konicai** [comment]
User said it was spawn protection on Discord
