### ISSUE TITLE
High coordinates flickering while moving

### ISSUE THREAD

**Issue by rafaelsms** [GeyserMC/Geyser#2432]
### Describe the bug

The bug is a flicker issue while moving around, probably due to float approximations. I can't even walk around on ~8 million.

Some of my users are already building around 1 million and bedrock users have experienced flickering because of this.

### To Reproduce

1. Teleport to 800,000 70 800,000
2. Move around
3. Notice flickering

### Expected behaviour

Smoother experience while moving around on great coordinates

### Screenshots / Videos

https://www.youtube.com/watch?v=3GnqQA4OK1s

### Server Version and Plugins

Waterfall version git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448

Tuinity version git-Tuinity-25 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: de19b33 on HEAD)

### Geyser Dump

https://dump.geysermc.org/nCxlLEzFcNP5vWHsSE4nrhpmQ3oysN0I

### Geyser Version

1.4.1-SNAPSHOT (git-master-b866483)

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Camotoy** [comment]
Not much we can do about this; this is a Bedrock bug. In the future we may work around it by shifting coordinates but for now this is a known issue with Bedrock where the fix is not building that far away. Best of luck.

**Comment by rafaelsms** [comment]
Thank you for your fast response! I'll warn my players about it then :)
