### ISSUE TITLE
Pufferfish with CustomName is invisible

### ISSUE THREAD

**Issue by cssbz** [GeyserMC/Geyser#2433]
### Describe the bug

When I `/summon` a pufferfish with a `CustomName` NBT tag, the resulting fish is invisible.

### To Reproduce

OK: `/summon pufferfish -223 18 -29`
FAIL: `/summon pufferfish -223 18 -29 {CustomName:"\"Puffy\""}`

### Expected behaviour

In the OK case, we see a pufferfish, as expected.

In the FAIL case, in a Bedrock client, the fish is invisible. We can see the fish's shadow ok. Also we can see the custom name above the invisible fish, when the player is pointed in the right direction.

These problems only occur in the Bedrock client - in a Java client, the fish is visible, as expected.

### Server Version and Plugins

Running `/version` in a Java client on this server produces "This server is running CraftBukkit version 3180-Spigot-38e6c03-ca0fe5b (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)".

I'm not the server owner and don't know all the details. Geyser is running in a Bungee proxy server. The owner has run `/geyser dump` - details below. I do know the owner well and can supply more detail if requested.

NB for the "Geyser Version" field in this bug report form below, I've found that detail from the Geyser Dump.

### Geyser Dump

https://dump.geysermc.org/Bar9HgQe2ogeSbWNO95LkjvAdLn4sGlL

### Geyser Version

1.4.1-SNAPSHOT (git-master-e0e6605)

### Minecraft: Bedrock Edition Version

v1.17.10

### Additional Context

I believe the `{CustomName:"\"Puffy\""}` syntax I'm using here is correct - it is mentioned at https://minecraft.fandom.com/wiki/Tutorials/Command_NBT_tags, and produces a working result in the Java client. We have tried a variety of other syntax combinations, but we have been unable to find a command that results in both a name and a visible fish.

**Comment by Konicai** [comment]
Does this still occur?

**Comment by cssbz** [comment]
Thanks. We verified the issue was still present about 2 weeks ago. I'll check again as soon as I can.

**Comment by cssbz** [comment]
@Konicai I just verified and the issue is still present.

Running `/version` in a Java client on this server gives "This server is running CraftBukkit version 3276-Spigot-3892929-b58f429 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)".

Let me know if you need more details.

**Comment by Camotoy** [comment]
I tested this recently and was unable to replicate it.

**Comment by RednedEpic** [comment]
Closing due to lack of response.
