### ISSUE TITLE
Read Timed Out error since using Aegis Bungee

### ISSUE THREAD

**Issue by PatrikX23** [GeyserMC/Geyser#2434]
### Describe the bug

I'm changed from Waterfall to Aegis since then its always says Read Timed Out error. I'am using standalone version and floodgate on all servers as well on proxy as the wiki says. Its worked when I used with waterfall.

### To Reproduce

1. Connect to a Geyser proxy thats pointing to an Aegis Proxy

### Expected behaviour

Connect to the lobby server to select server.

### Screenshots / Videos

![kép_2021-07-30_234316](https://user-images.githubusercontent.com/55624438/127714494-ad3a2d9e-03a6-4d60-95ba-a71ff8d7f5f7.png)

### Geyser Dump

https://dump.geysermc.org/CbENrbSFpSg38vUCGc2tNdqSagYcarLL

### Geyser Version

1.4.1-SNAPSHOT (git-master-e0e6605)

### Minecraft: Bedrock Edition Version

v1.17.10

**Comment by RednedEpic** [comment]
We do not support paid forks. We highly recommend you stick to Waterfall or Velocity instead.

**Comment by ixRaGe** [comment]
> We do not support paid forks. We highly recommend you stick to Waterfall or Velocity instead.

does Aegis work with geyser?

**Comment by Konicai** [comment]
We don't support it, so we don't attempt to make it compatible and we don't do testing. 

Please join our Discord for any more questions and don't bump old issues.
