### ISSUE TITLE
Low FPS when using MoreOres plugin 7FPS!

### ISSUE THREAD

**Issue by danielboos1** [GeyserMC/Geyser#2435]
### Describe the bug

This 'bug' causes my fps to drop to 7fps in bedrock windows 10 client. I have tested single player mode with no issues.
My specs are pretty high,
16gb ddr4
r5 3600 oc 4.4Ghz
1070 oc 2Ghz
SSD

### To Reproduce

Now use this map https://www.mediafire.com/folder/8dnnj0ny8f8o4/world
This map seems to cause this.
I was going to bed specially after not sleeping since 2 days, untill it hit me, what causing the issue is the addition of the plugin MoreOres and that I think it did permanent change to the map, however this isnt an issue on java. I havent had to time to check if MoreOres was the issue but its my guess until I do further testing

### Expected behaviour

Normal fps

### Screenshots / Videos

https://cdn.discordapp.com/attachments/696360651613929553/871126580146094160/2021-08-01_06-22-58.mp4 

### Server Version and Plugins

#136

### Geyser Dump
https://dump.geysermc.org/HYoMPgXpBpF75tsDpWBHnoJiXmwuFofG
### Geyser Version

Master Build 789 and earlier

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Konicai** [comment]
Your bedrock version is shown on the bottom right corner of the landing/main page of Bedrock Edition.

Also, please attach a geyser dump by running `geyser dump` in your console.

**Comment by danielboos1** [comment]
> Your bedrock version is shown on the bottom right corner of the landing/main page of Bedrock Edition.
> 
> Also, please attach a geyser dump by running `geyser dump` in your console.
> 
> Also, I assume you're referring to Paper `#136`?

I updated it!

**Comment by ganfalf** [comment]
i can confirm i used MoreOres on my server ,and it causing lagg with bedrock

**Comment by diamond-gold** [comment]
Since More Ores uses player skulls as the ores, enabling the config option "allow-custom-skulls" will cause geyser to spawn a player for every ore, which lags the bedrock client. The fix is to set "allow-custom-skulls" in config to false

**Comment by Konicai** [comment]
Yeah, lots of heads will destroy bedrock clients. IIRC Geyser needs to spawn an invisible armour to display the custom head, which is the source of lag.

As diamond-gold suggested there is the `allow-custom-skulls` which can be disabled. There is now also a per-client option which can be toggled in `/geyser settings` if `allow-custom-skulls` is true.
