### ISSUE TITLE
Ps4 cant drive a boat and smarthphone players see me in vanish

### ISSUE THREAD

**Issue by zlMarcoPolo** [GeyserMC/Geyser#2438]
### Describe the bug

1. normal players can see me (the owner) in vanish in the tablist. i got these plugin for my tablist: https://www.spigotmc.org/resources/tab-1-5-x-1-16-4-premium.83967/
2. the ps4 players cant drive a boat on my server.. they are thrown out of the boat after one move
I have a 1.16.5 paperspigot server on Zap-Hosting with 98 plugins. 

### To Reproduce

1. go to the playerslist 
2. get in a boat and go

### Expected behaviour

The boat driver should not be kicked out of the boat

### Geyser Version

1.4.1

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by byquanton** [comment]
Please provide a List of Plugins installed on your Server. In my experience, Zap Hosting has quite old Versions of Geyser and the Issue with the Boat could be because of an installed Anti Cheat

**Comment by Konicai** [comment]
1. We can't really offer support for paid plugins
2. Please provide more information as asked by the bug report template (geyser dump, screenshot of the tablist/playerlist, etc)

Please create separate bug reports for different issues/bugs in the future
