### ISSUE TITLE
Cape patterns on elytra

### ISSUE THREAD

**Issue by DoctorMacc** [GeyserMC/Geyser#244]
**What feature do you want?**
Official and custom capes shown by Java players can be viewed by Bedrock; therefore it should be possible to apply these patterns to an elytra. Currently Java users with a cape have the normal elytra pattern when viewed by a Bedrock player.

**Comment by Tim203** [comment]
You mean what Java players see when they look at Bedrock players?

**Comment by DoctorMacc** [comment]
Language clarified; I'm referring to extending the already existing feature where Bedrock players see Java capes.

**Comment by DoctorMacc** [comment]
Fixed with #539.
