### ISSUE TITLE
Player stuck on server when they enter server

### ISSUE THREAD

**Issue by DongShaoNB** [GeyserMC/Geyser#2443]
### Describe the bug

It was good before. Just now all players can't enter the server through Geyser

### To Reproduce

1.Start Geyser
2.Player use BE enter server

### Expected behaviour

Player shoud enter the server normally

### Screenshots / Videos

[https://i.loli.net/2021/08/04/pXzLlgIwNadAOSx.png](url)

### Server Version and Plugins

it is not happen in my server

### Geyser Version

1.4.1-SNAPSHOT (git-master-3eb73a5)

### Minecraft: Bedrock Edition Version

1.17.10

### Additional Context

It seems to be stuck in Geyser's authentication server and can't jump to my server

**Comment by Jens-Co** [comment]
Hello there, Can you please add your logs and a dump like the issue template said? Without more information there isn't much we can do and will close this issue. Thanks

**Comment by DongShaoNB** [comment]
> Hello there, Can you please add your logs and a dump like the issue template said? Without more information there isn't much we can do and will close this issue. Thanks

oh sorry,now i add my logs and dump
dump : https://dump.geysermc.org/8dGuTo1O1JlDdx9aMgEtCEDpCQgbGwKf
logs : [https://i.loli.net/2021/08/05/Zj7phBWwu4x1FIk.png](url)

Thanks!

**Comment by Konicai** [comment]
This just looks like a misconfiguration, please join us on our discord https://discord.gg/GeyserMC for further help
