### ISSUE TITLE
Player getting the rubber band effect when walking into glass pane

### ISSUE THREAD

**Issue by Sm0rezDev** [GeyserMC/Geyser#2444]
### Describe the bug

This is a bug I encounter while walking into a glass pane in Minecraft bedrock with geyser. What happen is whenever I walk into an glass pane edge or trying to jump over it my character seems to be stuck at that position but bouncing back and forward.

### To Reproduce

1. Place down a row (2 blocks long or more) of glass pane
2. Try walking in to it at the sides

### Expected behaviour

Player shouldn't be rubber banding when walking into the glass pane.

### Screenshots / Videos

https://streamable.com/2lrfdf

### Geyser Dump

https://dump.geysermc.org/FpYcJL2cgXfliZGJohVETMFo5P1vw1E0

### Geyser Version

1.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17

**Comment by YHDiamond** [comment]
I was able to replicate this with build 931. Just note that it only happens when walking into panes the exact way as shown in the video. Walking into the sides or a 1x1 is not a problem, just when walking into a pane with one direction extended from the opposite side of where you're walking.
