### ISSUE TITLE
Geyser is making DiscordSRV console log entity spawning

### ISSUE THREAD

**Issue by ILayZee** [GeyserMC/Geyser#2445]
### Describe the bug

Hi, according to this error, (
[03:03:37 WARN]: [Geyser-Spigot] Loaded class org.slf4j.impl.StaticLoggerBinder from DiscordSRV v1.23.0 which is not a depend, softdepend or loadbefore of this plugin.), geyser is enabling something in the code of DiscordSRV that is making it log every entity spawn.

[Wed, 4. Aug 2021 02:43:15 CEST INFO] Spawned entity SALMON at location (66.45959, 58.434464, 6582.5137) with id 3854 (java id 15266) But it happens with different numbers and animals whenever a new animal spawns.

Here is a log of the console: https://paste.lucko.me/O8YGc8pvKY

### To Reproduce

No idea but it has to do with both DiscordSRV and geyserMC

### Expected behaviour

Lots of entity logging

### Screenshots / Videos

I added in the console log by joining and moving around(I removed my ip)

### Server Version and Plugins

This server is running Paper version git-Paper-137 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: a67959e)

### Geyser Dump

https://dump.geysermc.org/oIYdZeko5W9FNHJXUcP5KPuRHwOamwvy

### Geyser Version

On the Jenkins website it’s build 793

### Minecraft: Bedrock Edition Version

1.17.10

### Additional Context

I have viaversion and viabackwards installed

**Comment by RednedEpic** [comment]
This has nothing to do with DiscordSRV. The messages you are seeing is because you have debug mode enabled in the Geyser config.
