### ISSUE TITLE
Rememeber Auth Tokens temporarily.

### ISSUE THREAD

**Issue by Greaper88** [GeyserMC/Geyser#2448]
### What feature do you want to see added?

This is primarily aimed at the GeyserConnect, but it would need to be implemented in Geyser itself.

Since Bedock has an issue with the minimizing of the game resulting in the game no longer being able to make connections, mobile users have a hard time with using web authorization. Since the long-term goal of the popular Public GeyserConnect instance is to do away with password logins, this is a concern to the usability for players. Easiest way around this is to remember the Auth Tokens in memory so players have time to restart their game and they will automatically be authenticated once thy reconnect.

So far,  two options to consider have been presented:
1. Remember the Auth-token for 5 minutes after initial auth. This will allow players 5 minutes to reconnect and and get back in, and gives them said window to hop around a few servers.
2. Remember the Auth-token for 2~5 minutes after most recent disconnect. This will allow players to change servers at will within a reasonable time-frame. This seems to me to be a common thing with the GeyserConnect players in particular.
3. Another idea that occurred to me while writing this: Allow a config option, which is set to disabled by default. Use this setting to allow the admin to choose with method and how long.

### Are there any alternatives?

Mobile users' alternative is using a separate auth device with is neither ideal, nor possible for everyone.

**Comment by Greaper88** [comment]
Another idea. What about using a CORS proxy in some fashion like VIAaaS does? Would this allow users' devices to retain the auth tokens as long as they want, and security of the token is with the user?

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/pull/2688 implemented this, this just wasnt closed for some reason. Closing!
