### ISSUE TITLE
Crafting does not work when using the recipe book

### ISSUE THREAD

**Issue by DoctorMacc** [GeyserMC/Geyser#245]
**Describe the bug**
When in survival mode, using the recipe book fails to give you your item. Graphically it "crafts" but then reverts to the previous inventory state after crafting. This is particularly a problem when using controllers.

I believe this is why people say Xbox crafting does not work; however crafting works normally when manually putting items in the crafting table.

**To Reproduce**
1. Join a server in survival mode
2. Attempt to use only the recipe book to craft.

**Expected behavior**
The item/items craft when using the recipe book.

**Server version**
git-Paper-143 (MC: 1.15.2)

**Geyser version**
Jenkins Inventory Build 9

**Bedrock version**
Minecraft Bedrock v1.14.30 (Tested on both Xbox One and iOS with controller)

**Additional context**
There is one different packet sent between crafting 'normally' and crafting with the recipe book.
https://mcpaste.io/880b088bedbceec2 - Packet while crafting normally.
https://mcpaste.io/7b8bc58f6508e6fb - Packet while crafting using the recipe book.

**Comment by Heath123** [comment]
If anyone wants to try fixing it, I formatted and reshuffled the packets and made this diff:

https://www.diffchecker.com/NXq4zasf

I changed the order of `actions` to make them both match - I don't know if that's important or not.

**Comment by DoctorMacc** [comment]
So it turns out this was fixed in 1.16 and no one noticed for almost two months. Awesome!

**Comment by rgronberg** [comment]
I am currently being affected by this issue on a server I recently set up.

Java server type and version: This server is running Paper version git-Paper-318 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

GeyserMC version: This server is running Geyser version 1.2.0-SNAPSHOT (git-master-91cdda9) (Java: 1.16.4, Bedrock: 1.16.100/1.16.101 - 1.16.200.5)

Bedrock client is running 1.16.201 (latest current version for nintendo switch)

**Comment by Camotoy** [comment]
That is a possible code fix, not a player fix.

There are a couple existing issues open about this - look for Xbox crafting.

**Comment by rgronberg** [comment]
Thanks for the tip, I found a few other tickets I can follow.

In the meantime, I was able to clone and build the plugin locally, but I cannot find the file that the changes at https://www.diffchecker.com/NXq4zasf correspond to. How I test these changes in a local build of the plugin?

**Comment by Camotoy** [comment]
The diff checker isn't pointing to code but to packets - it's not an easy fix (that's why it hadn't been implemented at the time). The inventory rewrite is currently in progress which will fix the issue.
