### ISSUE TITLE
Connection Closed

### ISSUE THREAD

**Issue by enriquesloth** [GeyserMC/Geyser#2450]
### Describe the bug

Whenever I tried to but Geyser on my server I did and whenever I try to join on bedrock, it says Connection Closed.

### To Reproduce

1. Go onto Minecraft Bedrock servers
2. Type in the IP and Port
3. Join the server
4. Finish Loading
5. Disconnected because of Connection Closed

### Expected behaviour

I expected to join on bedrock and see Java players but it just said Connection Closed.

### Screenshots / Videos

![WIN_20210806_17_17_30_Pro](https://user-images.githubusercontent.com/88561359/128571979-a36f416c-b300-4723-a95a-e3b57d6c1a6a.jpg)

### Geyser Version

1.4.1-SNAPSHOT (git-master-3eb73a5)

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Jens-Co** [comment]
Hello there, Can you please share your logs (latest.log) with this link https://mclo.gs/. Also include a dump with this command in console ( geyser dump ) and share the given link. Without that information we cannot help you out. Thanks!

**Comment by Konicai** [comment]
Please join us on our Discord https://discord.gg/geysermc for help fixing this error, as it is usually configuration error (and I'll have to assume that with the limited information provided)
