### ISSUE TITLE
Unable to Connect (Bedrock)

### ISSUE THREAD

**Issue by TechnicalRoper** [GeyserMC/Geyser#2451]
### Describe the bug

Getting unable to connect to world on connecting from Bedrock Edition. Even geyser is fully setuped and I can see it in https://mcsrvstat.us/

### To Reproduce

1. Make server in Server.pro.
2. Geyser fully setuped.
3. Getting unable to connect in bedrock edition.

### Expected behaviour

Please solve this issue fastly.

### Screenshots / Videos

[https://prnt.sc/1kdaqzk](https://prnt.sc/1kdaqzk)

[https://prnt.sc/1kdayah](https://prnt.sc/1kdayah)

### Server Version and Plugins

1.17.1 - Paper

### Geyser Dump

https://dump.geysermc.org/R63jZ5fjw3OOVbhIv5b5ohoDZ44x8p5X

### Geyser Version

1.4.1-SNAPSHOT (git-master-3eb73a5)

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by byquanton** [comment]
Are you using a free Server?
Take a Look at this Wiki Page: 
https://github.com/GeyserMC/Geyser/wiki/Supported-Hosting-Providers 

Get Geyser as a plugin. If you are using a Premium or Free plan, use the same port as your Java server for the Bedrock port in the configuration file and connect with that same port; for the Free plan, also enable the clone-remote-port option; leave the IP values as default (0.0.0.0 and auto). If you are using a Pro or VPS plan, you can use any port you'd like and it's recommended to leave it to the default or 19132.

**Comment by TechnicalRoper** [comment]
> Are you using a free Server?
> Take a Look at this Wiki Page:
> https://github.com/GeyserMC/Geyser/wiki/Supported-Hosting-Providers
> 
> Get Geyser as a plugin. If you are using a Premium or Free plan, use the same port as your Java server for the Bedrock port in the configuration file and connect with that same port; for the Free plan, also enable the clone-remote-port option; leave the IP values as default (0.0.0.0 and auto). If you are using a Pro or VPS plan, you can use any port you'd like and it's recommended to leave it to the default or 19132.


I m using a pro plan, And i tried all solutions. But nothing fix.

**Comment by byquanton** [comment]
Ask over at the Geyser Discord for help because this Issue doesn't look like a Geyser Issue but more like an Issue with your Hoster. https://discord.com/invite/geysermc

**Comment by Konicai** [comment]
Please try [this](https://github.com/GeyserMC/Geyser/wiki/Fixing-'Unable-to-Connect-to-World'#bedrock-players-can-connect-after-hitting-the-server-on-a-tcp-port-eg-on-java-or-a-website-on-the-same-server-or-only-people-who-also-play-on-java-edition-can-join-from-geyser)

If you *can* connect after trying the two workarounds listed, then your issue is because of the way Server.pro's firewall is setup (which we can't fix)
