### ISSUE TITLE
Crash the plugin by a player who is not on the server.

### ISSUE THREAD

**Issue by alex110220021** [GeyserMC/Geyser#2454]
**Describe the bug**
It appears that when someone is trying to ping a geyser server through UDP port it becomes completely unresponsive in Minecraft Bedrock until whole server is restarted.

**To Reproduce**
1. Start up a server with Geyser plugin
2. Join the server with Bedrock
3. Send a ping request to a UDP port
4. You get disconnected with a "Timed out" message and you can't join anymore.

**Expected behaviour**
Server continues to work and replies to ping packet accordingly.

**Screenshots / Videos**

**Server Version and Plugins**
1.17.1(Java), 1.17.10(Bedrock)
LuckPerms,
ProtocolLib,
Themis,
Geyser-Spigot,
Vault,
dynmap,
WorldEdit,
PlayerKits,
Essentials,
AdvancedBan,
WorldBorder,
WorldGuard,
Citizens,
AuctionHouse,
EssentialsProtect,
EssentialsChat,
NexEngine,
EssentialsSpawn,
CMILib,
Towny,
SmallPets,
Jobs,
TownyChat,
NexAuth,
Dynmap-Towny

This server is running CraftBukkit version 3210-Spigot-18c71bf-e1c96e5 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

**Geyser Dump**
https://dump.geysermc.org/9ensaNdRnpyiqsH7un7YETKHYpoNqgCD

**Geyser Version**
This server is running Geyser version 1.4.1-SNAPSHOT (git-master-3eb73a5) (Java: 1.17.1, Bedrock: 1.17.0/1.17.1/1.17.2 - 1.17.10)

**Minecraft: Bedrock Edition Version**
1.17.10

**Additional Context**

Update:
Server log: https://mclo.gs/G0xN0ZH

**Comment by Konicai** [comment]
Can you share your full server logs by uploading to https://mclo.gs and pasting the link here?

**Comment by alex110220021** [comment]
https://mclo.gs/G0xN0ZH

**Comment by alex110220021** [comment]
immediately after the geyser fell, I turned off the server *

**Comment by alex110220021** [comment]
the player who did badly to the server said that because of one query ping on the udp port is enough to put the Geyser. can you check this information with yourself?

**Comment by RednedEpic** [comment]
Not much we can do with the information provided, so will close this. If anyone has updated replication steps or encounters this issue, please open a new issue.
