### ISSUE TITLE
not locating

### ISSUE THREAD

**Issue by Soulstarop** [GeyserMC/Geyser#2456]
### Describe the bug

I have setup gaysermc with Floodgate in a server but yesterday its working but when I try to join today it is not locating and saying unable to connect.

### To Reproduce

idk how

### Expected behaviour

work properly all time because it is a public server

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/83019699/128659227-3557290f-2e8c-4bf3-ab5f-c2867a3b9759.png)

### Geyser Version

Geyser version 1.4.1-SNAPSHOT (git-master-3eb73a5)

### Minecraft: Bedrock Edition Version

1.17.1

**Comment by Camotoy** [comment]
Stuff like this is largely either a configuration issue or a hosting provider issue. For connection issues like these, please join our Discord for further assistance. Thanks!

**Comment by Soulstarop** [comment]
discord link?

**Comment by Jens-Co** [comment]
> discord link?

https://discord.gg/geysermc
