### ISSUE TITLE
PS4 Player get kicked of the server

### ISSUE THREAD

**Issue by boeserKuchen** [GeyserMC/Geyser#2457]
### Describe the bug

I can join normally using iOS and Windows 10. But when I join with an PS4 I can join and interact for some time but after a few seconds I get disconnected

### To Reproduce

1. Join on server on PS4
2. Play for a while
3. Get disconnected

### Expected behaviour

Stay in the game and don’t get kicked all 10 minutes 

### Server Version and Plugins

No plugins

Paper version git-Paper-84 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5059ada)

### Geyser Dump

https://dump.geysermc.org/nkTrAxN53VZi7KaZlrPQ7sF7apIoBJBK

### Geyser Version

Version 1.4.1-SNAPSHOT (git-master-3eb73a5) (Java: 1.17.1, Bedrock: 1.17.0/1.17.1/1.17.2 - 1.17.10)

### Minecraft: Bedrock Edition Version

1.17.1

### Additional Context

The server console also contains the following error:
![249C8AB2-6D54-4A5A-9C43-0241FB3AA645](https://user-images.githubusercontent.com/88647514/128694207-920f616d-0e98-432f-a8ba-b4ec0b3772ca.jpeg)

**Comment by TheFloyds4240** [comment]
Well for one, try updating paper, your build is more than a month out of date. If you look two builds forward, it was not even verified to fully support plugins.

**Comment by boeserKuchen** [comment]
> Well for one, try updating paper, your build is more than a month out of date. If you look two builds forward, it was not even verified to fully support plugins.

I have now updated the server, but the error has remained, as well as the problem with the system clock

**Comment by Camotoy** [comment]
I'm unable to confirm with Geyser build 798 and a regular PS4 connected over LAN. The server is Paper 130.

**Comment by Konicai** [comment]
Does this still occur?

**Comment by Konicai** [comment]
Let us know if this still occurs
