### ISSUE TITLE
Error on Join

### ISSUE THREAD

**Issue by knockiger** [GeyserMC/Geyser#2458]
### Describe the bug

![Screenshot_20210809-141220](https://user-images.githubusercontent.com/38558911/128704645-9651c097-085c-44ed-a12d-09438b28e32c.png)

### To Reproduce

1. Join Server
2. try to transfer to hypixel

### Expected behaviour

Transfer to a server

### Screenshots / Videos

![Screenshot_20210809-141220](https://user-images.githubusercontent.com/38558911/128704675-456e3025-6361-4fbf-b094-aca3ffff9f30.png)

### Geyser Version

latest version

### Minecraft: Bedrock Edition Version

1.17

### Additional Context

nothing

**Comment by TheMonBonGH** [comment]
why are you joining hypixel?

**Comment by Konicai** [comment]
Please provide a geyser dump as the issue template asks. Also, "latest" is not a helpful version.

**Comment by Arasple** [comment]
I have the same error joining my 1.17.1 server (git-Tuinity-"8e7cc4d" (MC: 1.17.1))
Dump: https://dump.geysermc.org/KNy3RJ30ISbL9zVoBsjlg0FQTojs84d0

**Comment by Camotoy** [comment]
Is there any extended error in your logs? How can a developer replicate this?

**Comment by Arasple** [comment]
![](https://i.loli.net/2021/08/10/yKcSRti8qbaA7zo.png)
I've made clean test servers for you

https://drive.google.com/file/d/11nfUaFuFLZiZgmwIEhuifpjB8QquuGth/view?usp=sharing

**Comment by Arasple** [comment]
Any news? Can you reproduce it with that?

**Comment by Camotoy** [comment]
This should be fixed with the latest commit, or at least this specific disconnect message - you likely inputted invalid credentials. You should now disconnect with the proper message.

**Comment by knockiger** [comment]
Okay, the error with me was that I had tried to sign up with nem Xbox Live Acc, but did not have one yet.
