### ISSUE TITLE
can u add old version support like 1.12.2 or 1.8.9

### ISSUE THREAD

**Issue by iiDELTaPRO** [GeyserMC/Geyser#2459]
### What feature do you want to see added?

by adding old version support GeyserMc community will grow by adding PvP and survival versions that will be so good for more fun with friends and familly

### Are there any alternatives?

i have tried to use geyser with a spigot 1.12.2 server but it doesnt work i just wanna to know if im doingh a mistake or you have been added old version support btw i used viaversion but it doesnt work

**Comment by NoobMC105** [comment]
Geyser on 1.12 works you have to use ViaVersion https://www.spigotmc.org/resources/viaversion.19254/
You must read the wiki and FAQ

**Comment by NoobMC105** [comment]
Also Geyser on proxy works with pre 1.12

**Comment by Jens-Co** [comment]
Hi there, Geyser should work on an 1.12 Server. If it's not working it's probably indeed an misconfiguration. Please join our Discord server for further assistance on how to setup Geyser https://discord.gg/geysermc.

Do know that we do not officially support server version below 1.12.

Thanks

**Comment by Konicai** [comment]
If you want to connect to servers below 1.12, you must use Geyser-BungeeCord, Geyser-Velocity, or Geyser-Standalone, which is still unsupported as Jens mentioned
