### ISSUE TITLE
Boats don't travel fast on ice

### ISSUE THREAD

**Issue by QPCrummer** [GeyserMC/Geyser#2460]
### Describe the bug

Boats do not travel the same speed as Java Edition on ice. They move the same speed as boats on land in Java.

### To Reproduce

Row a boat on ice.

### Expected behaviour

It should go very quickly.

### Server Version and Plugins

Velocity and Fabric 1.17.1 with Lithium
This commit "https://github.com/GeyserMC/Geyser/commit/1d04a61a46bfdbee7fe8d3af70e9a9ba4fb3e296"

### Geyser Dump

I can't get the dump because Linux is refusing to open terminals. I'll post it when I can get it to work

### Geyser Version

https://github.com/GeyserMC/Geyser/commit/1d04a61a46bfdbee7fe8d3af70e9a9ba4fb3e296

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by TheMonBonGH** [comment]
This is because of the bedrock client.

**Comment by Camotoy** [comment]
We haven't received any other reports of this and there has been no dump attached. Do note that Bedrock cannot ride on ice if a button is on top, unlike Java.
Thanks for the report anyway!
