### ISSUE TITLE
Console Spammed with eror

### ISSUE THREAD

**Issue by BurnhamR** [GeyserMC/Geyser#2461]
### Describe the bug

Error: https://pastebin.com/BCQMg2uD

### To Reproduce

Installed Geyser, On java player leaving, I received that error.

### Expected behaviour

N/A

### Server Version and Plugins

Paper version git-Paper-167 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bfb3d42)

Plugins: Geyser, EssentialsX, ViaVersion, ViaRewind, floodgate-spigot, ProtocolLib, Vault, WorldEdit.

### Geyser Version

1.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

v1.17.10

**Comment by Chew** [comment]
There was an API outage, should be good now. If it's still an issue flush your DNS cache.
