### ISSUE TITLE
Crafting glitch

### ISSUE THREAD

**Issue by Rom4ik777** [GeyserMC/Geyser#2462]
### Describe the bug

Crash when crafting items: items placed on the columns getting switched by another item in a player inventory.

p.s. the user (BeetGaming45) has a similar problem, but this always happens to me

### To Reproduce

Just crafting any item on a crafting table and place the ingredients onto the columns

### Expected behaviour

No item switching glitches/player can craft normally without any item they placed getting switched with a random item in their inventory

### Screenshots / Videos

https://user-images.githubusercontent.com/88676100/128831907-03c4bcf9-5b4e-42a2-a7df-653dfc1e629a.mp4

### Server Version and Plugins

1.12.2
viaversion

### Geyser Version

Geyser version 1.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.1

**Comment by Jens-Co** [comment]
Hi there, Can you please share a dump ? Use command: geyser dump, Can you take take out all plugins except Geyser & or floodgate to see if the problem still persists, Thanks.

**Comment by Rom4ik777** [comment]
> Привет, не могли бы вы поделиться дампом? Используйте команду: дамп гейзера. Можете ли вы удалить все плагины, кроме Гейзера или шлюза, чтобы проверить, сохранить ли проблема? Спасибо.
https://dump.geysermc.org/0NOAuu2LeJmFxfRIU6M6xaQrlmLpTqXf

please consider troubleshooting plugins

**Comment by Jens-Co** [comment]
![8BD1C94F-B26B-4A72-8DC0-63F3CA84CC15](https://user-images.githubusercontent.com/63231928/129484857-029a905d-361b-415d-bd90-54a51a36ff73.jpeg)
Follow these instructions to find the plugin that's causing your issue.

**Comment by Jens-Co** [comment]
Any updates about this issue ?

**Comment by Rom4ik777** [comment]
thanks for the help. The conflict was in the NoCheatPlus plugin

вт, 31 авг. 2021 г. в 10:44, Jens Collaert ***@***.***>:

**Comment by Jens-Co** [comment]
Glad to hear that you found the issue, thanks for the feedback to!

**Comment by RednedEpic** [comment]
We've done a set of changes to our inventory code that should resolve this. Will close.
