### ISSUE TITLE
Limit to connection, packets to prevent DDoS attacks

### ISSUE THREAD

**Issue by JH3Y50N** [GeyserMC/Geyser#2464]
### What feature do you want to see added?

Create limitations on connections such as Bungeecord "connection throttle", to prevent attacks on the GeyserMC server
and limit the packets, also only start the connection with the remote server if the geyser confirms the player's data, as they can flood connections on the geyser so that it also floods connections on the remote server

### Are there any alternatives?

Tried iptables

**Comment by Camotoy** [comment]
> also only start the connection with the remote server if the geyser confirms the player's data

This is already the behavior Geyser exhibits.

**Comment by MrGuizin** [comment]
Pretty good

**Comment by KaltsitMoe** [comment]
Actually, as Bedrock is using UDP as it's protocol, it's pretty easy to do UDPFlood or other type of DOS, you'd better use a dedicated firewall or proxy for protection

**Comment by RednedEpic** [comment]
Not really within our scope. Please use TCPShield or a similar service to prevent these attacks against your server.
