### ISSUE TITLE
Extended World Height = true does nothing!

### ISSUE THREAD

**Issue by DiamonC** [GeyserMC/Geyser#2466]
### Describe the bug

I wanted to play around with the extended-world-height setting, so i turned it on and generated a new world just to be safe. but i soon came to realize that it didnt do anything. Im on the latest version of spigot, the latest version of geyser, and was playing on java edition 1.17.1. What did i do wrong?

### To Reproduce

Have a geyser-spigot server
Change extended-world-height to true
Start a new world
Check for extended world height

### Expected behaviour

Height limit should be -64 -> 319

### Geyser Dump

https://dump.geysermc.org/gzVkQa4tFcZu9WrXKu35L9aXgXUjZwB0

### Geyser Version

1.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Camotoy** [comment]
Can you post your config value?

**Comment by RednedEpic** [comment]
Your dump indicates you did not toggle this option. Please ensure you saved your config file after toggling the option.
