### ISSUE TITLE
The sculk sensor does not display correctly on Bedrock Edition

### ISSUE THREAD

**Issue by Robert-Kidder** [GeyserMC/Geyser#2469]
### Describe the bug

There is an error in the texture of the sculk sensor in Bedrock Edition.
This should be regarded as a Feature request. I don’t know if I can make the sculk sensor display correctly in the Bedrock Edition.

### To Reproduce

Observe the sculk sensor in the bedrock version of geyser agent, and find that the texture is wrong

### Expected behaviour

Sculk sensor can be displayed correctly in Bedrock Edition

### Screenshots / Videos

The display of sculk sensor in Java Edition :

![image](https://user-images.githubusercontent.com/61925945/129407159-2599f04a-b0e0-49e9-b9d4-c599e11510ca.png)

The display of sculk sensor in Bedrock Edition : 

![4ff510ddf4e5ef635ac8788f86789b3](https://user-images.githubusercontent.com/61925945/129407566-8febb045-b835-48dc-872a-1872386a1f8a.jpg)

### Server Version and Plugins

This server is running Paper version git-Paper-177 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e942509)

### Geyser Dump

https://dump.geysermc.org/WuFiiyyAyAzkJAKwylFLl4EGTZYXi2ZE

### Geyser Version

1.4.1-SNAPSHOT (git-master-1afa22d)

### Minecraft: Bedrock Edition Version

1.17.11

### Additional Context

This should be regarded as a Feature request. I don’t know if I can make the sculk sensor display correctly in the Bedrock Edition.

**Comment by Camotoy** [comment]
Enable `extended-world-height` to fix this. This will be properly fixed, assuming all goes well, for 1.18.
