### ISSUE TITLE
Crafting glitch

### ISSUE THREAD

**Issue by Rom4ik777** [GeyserMC/Geyser#2474]
### Describe the bug

Crash when crafting items: items placed on the columns getting switched by another item in a player inventory.

p.s. the user (BeetGaming45) has a similar problem, but this always happens to me

### To Reproduce

Just crafting any item on a crafting table and place the ingredients onto the columns

### Expected behaviour

Items should be crafting normally instead of disappearing in the crafting menu

### Screenshots / Videos

https://user-images.githubusercontent.com/88676100/129484505-137c93d0-addd-4d1a-94ab-ca4769a21575.mp4

### Server Version and Plugins

1.12.2

### Geyser Dump

https://dump.geysermc.org/0NOAuu2LeJmFxfRIU6M6xaQrlmLpTqXf

### Geyser Version

Geyser version 1.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.1

**Comment by Camotoy** [comment]
*Please* do not bump issues.
