### ISSUE TITLE
teleportion giltch

### ISSUE THREAD

**Issue by Zenuimc** [GeyserMC/Geyser#2475]
### Describe the bug

notice bedrock users when teleporting they are sometimes unable to move or see surroundings, no errors server side that we have noticed on test to replicate the issue 

### To Reproduce

bedrock client logged in with geyser on to java 1.17.1 server we added commands /tp 999 99 999 when player was teleported surrounding terrain was unvisable, and was unable to move from the location, did /kill command to respawn and repeated the teleport commands same result

### Expected behaviour

we was expecting something from what other players have told us and our test matched what was discribed

### Server Version and Plugins

git-paper version 132 minecraft version 1.17.1 

### Geyser Version

132

### Minecraft: Bedrock Edition Version

1.17.1

**Comment by Konicai** [comment]
Distances that far are essentially unsupported by Bedrock Edition. You won't be able to go that far in a singleplayer or multiplayer Bedrock Edition either.

Its described pretty well here: 
https://minecraft.fandom.com/wiki/Bedrock_Edition_distance_effects
