### ISSUE TITLE
Missing mapping for brigadier:long argument type.

### ISSUE THREAD

**Issue by marcbal** [GeyserMC/Geyser#2476]
### Describe the bug

I have that error message in the standalone Geyser log:
```
[20:49:16 WARN] Downstream packet error! Value brigadier:long has no mapping for key class com.github.steveice10.mc.protocol.data.game.command.CommandParser.
```
Also, I do not have commands suggested while typing them in the chat, despite having the option `command-suggestions: true`. This is probably related to the error message above.

### To Reproduce

- You need to have a custom plugin altering the Brigadier command structure in the server (Paper?) to add a command with an argument of type `brigadier:long` (see additional context for more details)
- As long as a player connect to that server through Geyser, the error message appears in the log, and the player does not have any command suggested, except `/help` and `/?`.

### Expected behaviour

- Not having that error message
- Having commands suggested while typing them

### Server Version and Plugins

- BungeeCord: custom version
    - 1 custom plugin
    - Floodgate
- Paper: git-Paper-121 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b854e7e)
    - EssentialsX
    - ProtocolLib
    - Vault
    - WorldEdit
    - 1 custom plugin

### Geyser Dump

https://dump.geysermc.org/t3d935ilqqhLa79EAQ16fXA6A7E8gwWU

### Geyser Version

1.4.1-SNAPSHOT (git-master-9f4c2ce)

### Minecraft: Bedrock Edition Version

1.17.11

### Additional Context

As said in the `To Reproduce` section, I have a plugin that uses the Brigadier library to declare their commands, so I have proper suggestions and colors while using commands in Java Edition.
Brigadier library contains standard argument type as StringArgumentType, IntegerArgumentType, ... and also LongArgumentType ([Full list here](https://github.com/Mojang/brigadier/tree/master/src/main/java/com/mojang/brigadier/arguments)).
The long argument type is also declared in the internals of minecraft as `brigadier:long` and the vanilla Java Edition client fully supports it (otherwise I would not include that in my commands).
Since Minecraft vanilla commands are not using LongArumentType, it probably explains why its support is not implemented in Geyser.

After exploring the code, it looks like the argument type is missing in MCProtocolLib: [MagicValues.java](https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/data/MagicValues.java) [CommandParser.java](https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/data/game/command/CommandParser.java).

I will also open an issue on MCProtocolLib repository.

**Comment by Camotoy** [comment]
No need to open an issue since I'll be PRing there anyway.

A code snippet for Paper to reproduce this issue would allow us to fix it much faster!

**Comment by marcbal** [comment]
Ok thanks,

do you mean a small plugin with just the necessary code ?

**Comment by Camotoy** [comment]
Yes.

**Comment by marcbal** [comment]
This should do the work: https://gist.github.com/marcbal/e3118729681b4a8b495e75e69d8b6d96
It needs Paper 1.17.1 server jar to compile (it uses NMS)
