### ISSUE TITLE
Please connect through the official Geyser error on logging

### ISSUE THREAD

**Issue by abhisantos** [GeyserMC/Geyser#2478]
### Describe the bug

I have been using Geyser for some months and all worked fine.
Yesterday I had to reinstall it in another machine, so now some players (not all) are facing two problems

1. you join the server and stay in the void, you can see the sky but not the map of the lobby.
2. when you try to join there is a message ''Please connect through the official Geyser''

I use standalone, for a bungeecord network.

![Screenshot_29](https://user-images.githubusercontent.com/46583073/129925432-2428b19a-d4e5-4d43-b35b-41d3399596bb.png)

### To Reproduce

Just try to join

### Expected behaviour

To join normally

### Server Version and Plugins

Spigot 1.16
Bungeecord 1.17

### Geyser Dump

https://dump.geysermc.org/Lad2DP0zHQycNupXIsPEr8PtInsHKgLS

### Geyser Version

Geyser version 1.4.1-SNAPSHOT (git-master-9f4c2ce)

### Minecraft: Bedrock Edition Version

1.17.1

**Comment by Camotoy** [comment]
Please provide complete log files.

**Comment by lukeeey** [comment]
Make sure the public/private key are present as this message is shown when an invalid key is specified, usually when connecting through a Geyser instance without the public key.

**Comment by Camotoy** [comment]
There is no longer a public key so disregard that specific detail. Your key files being corrupt or improperly transferred could be an issue.

**Comment by abhisantos** [comment]
This is the full log https://www.codepile.net/pile/zb4L2eb4
The key.pem I copied from the ''old'' one. Is there a way to generate a new one for this new install?

Also, the key.pem file goes only in the /geyser directory right? Not in floodgate-bungee.

Half of players can join, but many others can't join because of these two issues.

**Comment by abhisantos** [comment]
> Please provide complete log files.

This is the full log https://www.codepile.net/pile/zb4L2eb4
The key.pem I copied from the ''old'' one. Is there a way to generate a new one for this new install?

Also, the key.pem file goes only in the /geyser directory right? Not in floodgate-bungee.

Half of players can join, but many others can't join because of these two issues.

**Comment by abhisantos** [comment]
My server usually has from 100 to 140 players online, but with this issue only 70 to 80 are getting to loggin

**Comment by Tim203** [comment]
Ok so, you have 2 proxies. Both of them have Floodgate and Geyser.
Floodgate is responsible for creating the key. So you copy the Floodgate key from proxy 1 to Floodgate on proxy 2.
Geyser should automatically use the key in the Floodgate folder, but to be sure: copy the Floodgate key from proxy 1 to Geyser on proxy 2 as well and everything should work just fine.

**Comment by abhisantos** [comment]
> Ok so, you have 2 proxies. Both of them have Floodgate and Geyser.
> Floodgate is responsible for creating the key. So you copy the Floodgate key from proxy 1 to Floodgate on proxy 2.
> Geyser should automatically use the key in the Floodgate folder, but just to be sure: copy the Floodgate key from proxy 1 to Geyser on proxy 2 as well and everything should work just fine.

Sorry, i didn't understand about the 2 proxies, as i thought i had only one
I have ''bungeecord/plugins/floodgate-bungee''
and a separate standalone geyser for this bungeecord.

but floodgate i have only one, in the bungeecord plugins folder

**Comment by abhisantos** [comment]
Solved!
The problem was that i had two folders in bungeecord plugins
**/floodgate-bungee** and **/floodgate**
I was updating the first one, but the right one was only **/floodgate**

So i reinstalled floodgate, generated a new key.pem and copied it to the standalone Geyser, using the command line, not ftp.

Now it is connecting fine for everyone.

**Thank you  Camotoy, lukeeey and Tim203 for the great help!**
