### ISSUE TITLE
I mean question: Can I use 1.16.5 server

### ISSUE THREAD

**Issue by Timtaran** [GeyserMC/Geyser#2479]
### What feature do you want to see added?

Hello, can I use 1.16.5 Java server and 1.17.10 Bedrock?

### Are there any alternatives?

Uhm....

**Comment by jackson-57** [comment]
ViaVersion will work perfectly here (it allows newer clients to join older servers), as Geyser emulates a Java client. For further questions, I'd recommend joining our Discord.
