### ISSUE TITLE
Compass with NBT cannot be translated and is not visible.

### ISSUE THREAD

**Issue by Primia** [GeyserMC/Geyser#2480]
### Describe the bug

Compass with NBT cannot be translated and is not visible.
NBT:
give Player minecraft:compass{LodestoneDimension:"minecraft:overworld" ,LodestoneTracked: 0b, LodestonePos:{X:1, Y:1, Z:1 }, display:{Name:"\"Point1\"",Lore:["\"Point1\"","\"Overworld\"","\"x:1y:1z:1\""]} }

### To Reproduce

give Player minecraft:compass{LodestoneDimension:"minecraft:overworld" ,LodestoneTracked: 0b, LodestonePos:{X:1, Y:1, Z:1 }, display:{Name:"\"Point1\"",Lore:["\"Point1\"","\"Overworld\"","\"x:1y:1z:1\""]} }

### Expected behaviour

![QQ截图20210819154647](https://user-images.githubusercontent.com/87895370/130029352-441cd3e1-2ead-4c13-b983-d694e6a38c4f.png)

### Server Version and Plugins

Fabric 1.16.5 
Bungeecord plugin:Viaversion

### Geyser Version

#817

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Primia** [comment]
https://pastebin.ubuntu.com/p/SNqs245MNx/
[Server] [16:48:37] [Server thread/INFO]: hail122 has the following entity data: [{Slot: 0b, id: "minecraft:rotten_flesh", Count: 3b}, {Slot: 1b, id: "minecraft:white_wool", Count: 1b}, {Slot: 2b, id: "minecraft:iron_nugget", Count: 58b}, {Slot: 3b, id: "minecraft:obsidian", Count: 2b}, {Slot: 4b, id: "minecraft:gold_nugget", Count: 13b}, {Slot: 5b, id: "minecraft:azure_bluet", Count: 1b}, {Slot: 6b, id: "minecraft:compass", Count: 64b}, {Slot: 9b, id: "minecraft:rabbit_hide", Count: 1b}, {Slot: 10b, id: "minecraft:arrow", Count: 1b}, {Slot: 11b, id: "minecraft:egg", Count: 1b}]
[Server] [16:48:37] [Server thread/INFO]: Removed 1 items from player hail122
[Server] [16:48:37] [Server thread/INFO]: Gave 1 [Lodestone Compass] to hail122
[Server] [16:48:37] [Thread-94/WARN]: 翻译元数据错误: 实体 ITEM 得到了 EntityMetadata(id=7, type=ITEM, value=ItemStack(id=683, amount=1, nbt=CompoundTag { {LodestoneDimension=StringTag(LodestoneDimension) { minecraft:overworld }, LodestoneTracked=ByteTag(LodestoneTracked) { 0 }, LodestonePos=CompoundTag(LodestonePos) { {X=DoubleTag(X) { -1169.5687960881871 }, Y=DoubleTag(Y) { 64.0 }, Z=DoubleTag(Z) { -1667.4349760406667 }} }} }))
[Server] [16:48:37] [Thread-94/ERROR]: Error processing inventory task
[Server] java.lang.ClassCastException: com.github.steveice10.opennbt.tag.builtin.DoubleTag incompatible with com.github.steveice10.opennbt.tag.builtin.IntTag
[Server]        at org.geysermc.connector.network.translators.item.translators.CompassTranslator.translateToBedrock(CompassTranslator.java:62) ~[Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at org.geysermc.connector.network.translators.item.ItemTranslator.translateToBedrock(ItemTranslator.java:156) ~[Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at org.geysermc.connector.inventory.GeyserItemStack.getItemData(GeyserItemStack.java:102) ~[Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at org.geysermc.connector.inventory.Inventory.updateItemNetId(Inventory.java:109) ~[Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at org.geysermc.connector.inventory.Inventory.setItem(Inventory.java:103) ~[Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at org.geysermc.connector.network.translators.java.window.JavaSetSlotTranslator.lambda$translate$2(JavaSetSlotTranslator.java:88) ~[Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at org.geysermc.connector.network.translators.java.window.JavaSetSlotTranslator$$Lambda$5220/0x0000000000000000.run(Unknown Source) ~[?:?]
[Server]        at java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815) [?:?]
[Server]        at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799) [?:?]
[Server]        at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121) [?:?]
[Server]        at org.geysermc.connector.network.session.GeyserSession.addInventoryTask(GeyserSession.java:1076) [Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at org.geysermc.connector.network.translators.java.window.JavaSetSlotTranslator.translate(JavaSetSlotTranslator.java:62) [Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at org.geysermc.connector.network.translators.java.window.JavaSetSlotTranslator.translate(JavaSetSlotTranslator.java:57) [Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:95) [Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:804) [Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at com.github.steveice10.packetlib.tcp.TcpSession$2.run(TcpSession.java:321) [Geyser-Fabric-1.0-SNAPSHOT.jar:?]
[Server]        at java.lang.Thread.run(Thread.java:836) [?:?]

**Comment by rtm516** [comment]
The example commands you provided don't replicate this issue, by the looks of it you have a plugin generating invalid NBT for the compass, it's setting a double value where only ints should be. Please correct the plugin and this issue should disappear, if not please re-open the issue with more information.
https://minecraft.fandom.com/wiki/Compass#Item_data
