### ISSUE TITLE
Not listening on port

### ISSUE THREAD

**Issue by Dev-Sona** [GeyserMC/Geyser#2481]
### Describe the bug

I've tried many different setting configurations, and I've fucked with my firewall. The remote port always works but bedrock refuses to listen on the port I assign it. I even tried 25565 for both.

### To Reproduce

bedrock:
  address: 0.0.0.0
  port: 25565 #Also tried 19132
  clone-remote-port: false #Also tried true
  compression-level: 6
remote:
  address: 127.0.0.1 #Also tried auto
  port: 25565
  auth-type: floodgate #also tried online

### Expected behaviour

Console log, no open port, no error.

### Geyser Dump

https://dump.geysermc.org/AXOzXyMxBhrFk30vF0P47enkI3ElQCZn

### Geyser Version

1.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.11.1

**Comment by Camotoy** [comment]
I'm going to close this since we don't track connection issues here, but you can keep updating here if necessary. A couple things to note:
- Make sure you're opening UDP ports on your firewalls, not TCP
- https://github.com/GeyserMC/Geyser/wiki/Fixing-'Unable-to-Connect-to-World'#windows-10

**Comment by Dev-Sona** [comment]
Perhaps you're misunderstanding, I ran the check and it said OK. The problem is not Minecraft, the port is not listening. I checked canyouseeme.org and 25565 is open, but not 19132. The issue is geyser not opening the port itself. The firewall is done correctly. Both inbound and outbound allowed over both port types and all ports.

**Comment by Camotoy** [comment]
canyouseeme.org does not appear to use UDP. I tested myself with my own IP and it detects my opened port running a server as offline.
Geyser does not open up any ports. If you're referring to a service such as uPnP, Geyser does not currently do this.

**Comment by Camotoy** [comment]
A better testing website is https://mcsrvstat.us/ which verifiably detects if your Minecraft server is running.

**Comment by Dev-Sona** [comment]
![image](https://user-images.githubusercontent.com/70853905/130143753-2af73e16-25cf-4db9-a8ba-bba79702cc07.png)
![image](https://user-images.githubusercontent.com/70853905/130143793-bbd998cc-a976-423d-b81a-cd08519055ec.png)
19132 tried as well.

**Comment by Camotoy** [comment]
Make sure to specify a port, and wait a minute each time since MCSrvStatus does a bit of caching.

**Comment by Dev-Sona** [comment]
still failed. just if you think my firewall or forwarding is wrong:
![image](https://user-images.githubusercontent.com/70853905/130144285-22a1547a-57a9-4113-801b-bd17c5009341.png)
![image](https://user-images.githubusercontent.com/70853905/130144328-01c06a47-3a3e-4637-b180-a0cf9a542943.png)

**Comment by Dev-Sona** [comment]
UDP port is listening just fine when im using a software other than geyser.

**Comment by Dev-Sona** [comment]
![image](https://user-images.githubusercontent.com/70853905/130144803-29b6743b-53f2-4f3f-a43a-f02ad066dd8a.png)
![image](https://user-images.githubusercontent.com/70853905/130144810-fde33f8d-3412-4a64-a632-6f2f5c88e256.png)

**Comment by Dev-Sona** [comment]
Wtf how can you connect but I can't

**Comment by Dev-Sona** [comment]
Dude it just magically started working

**Comment by Dev-Sona** [comment]
![image](https://user-images.githubusercontent.com/70853905/130145340-f880f9b4-3191-4b3e-9365-09f01b143ea2.png)

**Comment by Camotoy** [comment]
That's probably just caching getting in the way.

Have fun with your server.

**Comment by Dev-Sona** [comment]
... -__
iight well thanks for fixing it somehow lol
