### ISSUE TITLE
Not listening on port (NOT A CONNECTION ISSUE)

### ISSUE THREAD

**Issue by Dev-Sona** [GeyserMC/Geyser#2482]
### Describe the bug

I've tried many different setting configurations, and I've fucked with my firewall. The remote port always works but bedrock refuses to listen on the port I assign it. I even tried 25565 for both.

### To Reproduce

bedrock:
address: 0.0.0.0
port: 25565 #Also tried 19132
clone-remote-port: false #Also tried true
compression-level: 6
remote:
address: 127.0.0.1 #Also tried auto
port: 25565
auth-type: floodgate #also tried online

### Expected behaviour

Console log, no open port, no error.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/70853905/130141588-f44fcc89-4723-4e52-b54a-19066e746375.png)

### Geyser Dump

https://dump.geysermc.org/AXOzXyMxBhrFk30vF0P47enkI3ElQCZn

### Geyser Version

1.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.11.1

### Additional Context

This is NOT a connection issue. 25565 is working fine and is open. This is a problem with Geyser itself, not Minecraft, my firewall, or my internet.

**Comment by Camotoy** [comment]
I have updated your original issue. Please do not bump issues in the future.
