### ISSUE TITLE
Crafting very slow

### ISSUE THREAD

**Issue by l3unnyAnoF4** [GeyserMC/Geyser#2483]
### Describe the bug

Crafting very slow when i use craft on bedrock

### To Reproduce

-

### Expected behaviour

-

### Screenshots / Videos

https://user-images.githubusercontent.com/67956962/130174723-3934b27f-aedd-48c9-9463-1e546317417d.mp4

### Server Version and Plugins

Just plugin geyser and floodgate

### Geyser Version

Build #818

### Minecraft: Bedrock Edition Version

1.17.11

**Comment by Camotoy** [comment]
Please provide a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by l3unnyAnoF4** [comment]
https://dump.geysermc.org/ETPM18fIqGN0bji1gh1yHuTKvHcP2C6w

**Comment by Camotoy** [comment]
I recently refactored our inventory code to better handle 1.17 changes, so this should be resolved/far less of an issue.
