### ISSUE TITLE
Bedrock players could make illegal portals

### ISSUE THREAD

**Issue by BeetGaming45** [GeyserMC/Geyser#2484]
### Describe the bug

bedrock players can make irregularly shaped nether portals instead of a normal rectangle nether portal resulting in this sus looking portal, bedrock players could lit the portal while java players can't

### To Reproduce

1. join on a bedrock account
2. build an irregularly shaped portal
3. lit the portal

### Expected behaviour

bedrock players shouldn't lit these kind of portals

### Screenshots / Videos

https://user-images.githubusercontent.com/79033198/130178874-19c83fa9-9666-4048-8353-92ee0f096f97.mp4

### Server Version and Plugins

 This server is running Paper version git-Paper-196 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 59d449d)

Plugins:
AntiProxy*, ClearLag, ConsoleSpamFix, DiscordSRV, ezBroadcast*, floodgate, Geyser-Spigot, HeadsLite, ImageOnMap, LoginSecurity*, MoreCommands, Multiverse-Core, NoMobGriefing, NoSwear, OnePlayerSleep, PowerRanks, ProtocolLib, SilkSpawners, SkinsRestorer, Sudo*, SuperVanish, ViaBackwards, ViaVersion, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geyser.org/jNdGRWYDm5lMwbeQLWVcw65DmpS3Nb9B

### Geyser Version

1.4.1-SNAPSHOT (git-master-52fa067)

### Minecraft: Bedrock Edition Version

1.17.10-1.17.11

**Comment by Jens-Co** [comment]
Updated link:(https://dump.geysermc.org/jNdGRWYDm5lMwbeQLWVcw65DmpS3Nb9B)

**Comment by Jens-Co** [comment]
![9461E946-A002-443B-87F9-804E435400E0](https://user-images.githubusercontent.com/63231928/130180081-8351843d-0aac-4865-9db6-322c1a2e6ba9.png)
was able to recreate it on single player So it will be Minecraft bedrock mechanic.

**Comment by lukeeey** [comment]
but aren’t the nether portal blocks set server side…

**Comment by jackson-57** [comment]
> ![9461E946-A002-443B-87F9-804E435400E0](https://user-images.githubusercontent.com/63231928/130180081-8351843d-0aac-4865-9db6-322c1a2e6ba9.png)
> was able to recreate it on single player So it will be Minecraft bedrock mechanic.

Nether portals can be made like that in java. They need to be rectangles and they need to be as least as tall and wide as the normal portals (and there's a pretty high limit on size iirc)
the one in the initial post isn't a rectangle, though

**Comment by rtm516** [comment]
Just checked this with the same portal shape on the test server and the portal doesn't light, must be a plugin on your server and not Geyser.

https://user-images.githubusercontent.com/5401186/130205878-f7ab88b4-3f7c-4cd6-9a7e-775221e6f590.mp4
