### ISSUE TITLE
1.17.1 - "Could not translate packet ServerRemoveEntitiesPacket"

### ISSUE THREAD

**Issue by Kruize1** [GeyserMC/Geyser#2485]
### Describe the bug

I saw this error in my console. I never saw this before and I recently updated to Geyser version 1.4.1-SNAPSHOT (git-master-89dde2a) https://pastebin.com/SHrFK00T

### To Reproduce

Unknown repro steps, but rebooting made the error go away for now.

### Expected behaviour

No errors

### Screenshots / Videos

https://pastebin.com/SHrFK00T

### Geyser Dump

https://dump.geysermc.org/J79DngFwfvgbU9oirrfvitWEE0made1k

### Geyser Version

1.4.1-SNAPSHOT (git-master-89dde2a)

### Minecraft: Bedrock Edition Version

1.17.11

### Additional Context

I'm also using this https://github.com/GeyserMC/Geyser/wiki/GeyserOptionalPack

Not sure if this is part of the issue? Also, not sure if I need this anymore?

**Comment by Camotoy** [comment]
Yes, GeyserOptionalPack is still in use.

A commit was just pushed that should resolve this issue? Let me know if you experience it within the next week.

**Comment by RednedEpic** [comment]
As mentioned, this issue has been fixed and since there has been no response here, I am going to assume this problem was fixed.
