### ISSUE TITLE
Extended-world-height error? 

### ISSUE THREAD

**Issue by rad1914** [GeyserMC/Geyser#2486]
### Describe the bug

Hello, I have recently applied a DataPack that enables the new World generation of the -Y layer on my Java server, and when entering from Bedrock, and the players reach the negative layers, they start to shake in a loop without being able to exit, in the error 
"[18:29:57 WARN]: [Geyser-Spigot] The server is using chunk heights bigger than Bedrock can normally accept! Please enable the option extended-world-height in your Geyser config to fix this."  
I can't find the option to enable generation -Y in bedrock.  What I can do?
And.. Here's the Geyser configuration file, Which one am I supposed to activate?
https://pastebin.com/CDZ9MV10

### To Reproduce

#2319

### Expected behaviour

It should be able to interact with the -Y chunks

### Screenshots / Videos

![Screenshot_2021-08-20-20-45-58-360_com google android apps photos_compress72](https://user-images.githubusercontent.com/51271703/130306751-ceca39f8-2901-4309-bfc2-6945719a2758.jpg)
The white points are the chunks bug in -Y

### Server Version and Plugins

Purpur Server, the plugins are Holographic displays, BroadcastPlus, LaggRemover, world edit and via

### Geyser Dump

https://dump.geysermc.org/9IOTaZgO1ADtdcoGGXTiWIR56Tb5Liea

### Geyser Version

Geyser 1.4.1-SNAPSHOT (git-master-52fa067)

### Minecraft: Bedrock Edition Version

1.17.11

### Additional Context

.

**Comment by jackson-57** [comment]
You'll have to either delete your config (so it regenerates) or add it to the config manually.

**Comment by Chew** [comment]
See above, your config is outdated. Here's an up-to-date config: https://github.com/GeyserMC/Geyser/blob/master/connector/src/main/resources/config.yml

As stated, add it manually or regenerate.
