### ISSUE TITLE
/Replaceitem

### ISSUE THREAD

**Issue by Zachadactyl** [GeyserMC/Geyser#2487]
### What feature do you want to see added?

I miss /replaceitem on GeyserMC.  My friends on Java can do it, but not me.  This could be really cool.

### Are there any alternatives?

None

**Comment by Konicai** [comment]
Please use the bug report template when reporting incompatibility issues (you can create a new one with it). If the command works on java edition but not bedrock, it sounds like you're having some sort of incompatibility issue. 

You can also join our Discord for help https://discord.gg/GeyserMC
