### ISSUE TITLE
Close Inventory, Deluxe Menus

### ISSUE THREAD

**Issue by vakhdmyt06** [GeyserMC/Geyser#2488]
### Describe the bug

im simply making it execute [close], and this shows the behavior like the third item is explaining

https://pastebin.com/Merqmg2k
[DeluxeMenus.zip](https://github.com/GeyserMC/Geyser/files/7027003/DeluxeMenus.zip)

```
Found errors in the log!
See below for details and possible fixes
java.lang.ClassCastException: class org.geysermc.connector.inventory.PlayerInventory cannot be cast to class org.geysermc.connector.inventory.Container (org.geysermc.connector.inventory.PlayerInventory and org.geysermc.connector.inventory.Container are ...
Unknown fix!
Class: DoubleChestInventoryTranslator
Method: closeInventory
Line: 142
Link: DoubleChestInventoryTranslator.java#L142
```

### To Reproduce

1. download plugin and use these configs
2. restart server
3. go ingame
4. type /sm
5. select the third item
6. and there we go

### Expected behaviour

Inventory should close without any console errors or bugs, just close the inventory ingame and its done

### Server Version and Plugins

blank

### Geyser Dump

 https://dump.geysermc.org/Tl4S2sHF8BoCK7NEojTQkY8tAjPGKjeH

### Geyser Version

i downloaded latest dev yesterday

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Chew** [comment]
The config provided had 2 syntax errors that prevented me from loading the plugin. Upon fixing them, I could not reproduce this issue.
![image](https://user-images.githubusercontent.com/8278263/135389691-49898aa0-cb90-4a10-8d96-bcd75ebd5dd3.png)

Tested with:
```
This server is running Paper version git-Paper-276 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 1707c10)
```
And specifically Geyser-Spigot.

As this report is from over a month ago, it's likely a commit between now and then has fixed this. If not, please feel free to let me know and I can re-open this issue.
