### ISSUE TITLE
The scoreboard is not displayed correctly.

### ISSUE THREAD

**Issue by wifi-left** [GeyserMC/Geyser#2491]
### Describe the bug

# As shown in the picture below, the scoreboard will not be displayed in minecraft Java Edition, but it will be displayed in minecraft bedrock edition, and the title becomes unknown.

## In Minecraft Java:
![OUJ5TRLC_(8%PWJUMJL7NFE](https://user-images.githubusercontent.com/63381531/130394317-ad6ed505-e83d-4bb4-9fa5-890e574d21b9.png)
![Q94TN_X5 F70BQ6BU%T7{`X](https://user-images.githubusercontent.com/63381531/130394463-b71ffe01-9f46-471f-ab0b-51ed67aee72d.png)
## In Minecraft Bedrock:
![20210823131340](https://user-images.githubusercontent.com/63381531/130394615-eb774412-13a2-4dca-b73a-53a1a8d8cba9.png)

# Tip:
The two screenshots are taken at the same location and state in the same map.

### To Reproduce

1. Start a fabric-carpet server.
2. Start Geyser.
3. Enter the server in Minecraft Java
4. Enter the server in Minecraft Bedrock
5. You can find that the scoreboard displays differently for the two roles in the same state.

### Expected behaviour

Scoreboard display error

### Screenshots / Videos

![OUJ5TRLC_(8%PWJUMJL7NFE](https://user-images.githubusercontent.com/63381531/130394913-3188ca32-ca46-4563-a05e-9a4c2f440756.png)
![Q94TN_X5 F70BQ6BU%T7{`X](https://user-images.githubusercontent.com/63381531/130394919-1e8c8e1d-88ff-4528-8153-9b3763837eb9.png)
![20210823131340](https://user-images.githubusercontent.com/63381531/130394930-ae6719d0-5bda-4ce4-b95e-5d7cbabad058.png)

### Server Version and Plugins

# Fabric Server (1.17.1)
# Mod:
1. Fabric-api
2. Carpet
3. FabricProxy-1.4.9

# Geyser:
Latest version.

### Geyser Version

The latest version.

**Comment by Konicai** [comment]
Please include a geyser dump by running the command `geyser dump` and adding the link to your post

also, "latest version" isn't really helpful, but a geyser dump will suffice

**Comment by Jens-Co** [comment]
Copy of #1925.
