### ISSUE TITLE
cannot switch gamemode from survival to creative or other gamemodes from geyser client[bedrock][all types]

### ISSUE THREAD

**Issue by BRASHEXODUS** [GeyserMC/Geyser#2492]
### Describe the bug

cannot switch the gamemode of a bedrock player to the servers gamemode [also have multiverse cores gamemode set to something specific example creative]
here is a dump list https://dump.geysermc.org/1BrHwDAWq1YqLPFC4VgZuxQg5kO1VxFC

### To Reproduce

https://dump.geysermc.org/1BrHwDAWq1YqLPFC4VgZuxQg5kO1VxFC

### Expected behaviour

https://dump.geysermc.org/1BrHwDAWq1YqLPFC4VgZuxQg5kO1VxFC

### Geyser Dump

https://dump.geysermc.org/1BrHwDAWq1YqLPFC4VgZuxQg5kO1VxFC

### Geyser Version

latest

**Comment by RednedEpic** [comment]
Please answer the questions provided to you in the issue format. Pasting a dump as an answer for everything and ignoring some of the information/requests in the format gives us nothing useful in regards to reproducing this.

**Comment by Camotoy** [comment]
The fastest way to have this fixed is by providing exact steps in order to replicate this on a clean server setup.

**Comment by BRASHEXODUS** [comment]
i have no idea what i should replicate? or providing exact steps? i followed the geyser tutorial on the spigot version and this just doesn't work I could share all the plugins I'm using but like I said it just doesn't switch over

**Comment by Yuta12342** [comment]
All I can say regarding this, is this has always worked fine for me. What you might be facing is an issue of conflicting OP Status. I've had it happen where for some reason, the Bedrock Client seen me as a Guest Player instead of a Member, so it would only let me do anything when I OP'd that Client, until I checked the Permissions and messed with the menu a bit, before it fixed itself.

**Comment by Konicai** [comment]
Without further information its difficult to help. If you're still having this issue, please let us know, and try the following:


   - Temporarily remove half of your plugins from your server's plugins folder.
   - If the problem persists, remove another half.
   - If the problem goes away, swap that half of your plugins with the other half.
   - Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.
