### ISSUE TITLE
No /replaceitem on Bedrock!

### ISSUE THREAD

**Issue by Zachadactyl** [GeyserMC/Geyser#2494]
### Describe the bug

I join my PaperMC server with GeyserMC as a plugin, and I have the other java commands, but not /replaceitem.  /replaceitem is in bedrock, but it has a slightly different use on Java, which I need.

### To Reproduce

1. Join from bedrock to any PaperMC server with GeyserMC as a plugin
2. Try to use /replaceitem
3. It won't work

### Expected behaviour

It should let you place items on your head in funny ways, and equip armor.

### Geyser Dump

https://dump.geysermc.org/Fjdohje60q11tvNi2RXimdGJhP0IeWfR

### Geyser Version

Geyser version 1.4.1-SNAPSHOT (git-master-7639988) (Java: 1.17.1, Bedrock: 1.17.10/1.17.11)

### Minecraft: Bedrock Edition Version

v1.17.11

**Comment by RednedEpic** [comment]
Geyser only connects you to a Java server; it does not add in new base mechanics the Java server does not have. This command was replaced with the /item command on 1.17 in Java edition.

**Comment by Konicai** [comment]
Please do not create duplicate issues.
