### ISSUE TITLE
Option to hide "Unusable inventory space" item

### ISSUE THREAD

**Issue by ElFlyGod** [GeyserMC/Geyser#2495]
### What feature do you want to see added?

Option to hide "Unusable inventory space" item, its currently a barrier but an option to hide it and just be blank space would look a lot better.

If some sort of chat message is required when this is added then it would be good if it was configurable

This is how it looks, but the GUI would be a lot better with it just hidden.
![image](https://user-images.githubusercontent.com/29352381/130697508-2dde6f86-dfa3-46ff-acb3-3206ca4b0c8e.png)

### Are there any alternatives?

.

**Comment by lukeeey** [comment]
I think the best way to do this would be to make it configurable and let the user select what item to go there.

You can then set it to air if you’d like to hide it completely.

**Comment by ElFlyGod** [comment]
> I think the best way to do this would be to make it configurable and let the user select what item to go there.
> 
> You can then set it to air if you’d like to hide it completely.

Good idea

**Comment by ROBGUI09** [comment]
better way replace barrier with light gray stained pane and change the name of glass pane to old barriers name

**Comment by lukeeey** [comment]
> better way replace barrier with light gray stained pane and change the name of glass pane to old barriers name

That indeed sounds like a great idea but thats the first thing i tried. On Bedrock, stained glass panes aren’t 2D in the inventory like on Java, they’re 3D which just looks absolutely horrible.

**Comment by lukeeey** [comment]
That could be an idea for GeyserOptiobalPack though ^

**Comment by Camotoy** [comment]
The problem is that, at the moment, we don't know if a player has the pack installed. It seems inevitable enough that we will add features that require the pack to be installed, though.

**Comment by Yuta12342** [comment]
At some point, it might just be better to enforce the pack at some point, which is technically possible for people using the Plugin Version of Geyser, using the "packs" folder.
