### ISSUE TITLE
Weather not working correctly

### ISSUE THREAD

**Issue by jcarney2024** [GeyserMC/Geyser#2499]
### Describe the bug

When changing the weather on bedrock, it does not affect anything. However, if you change the weather on Java, it doesn't affect bedrock.

### To Reproduce

1. Change weather on bedrock
2. See no changes
-------
1. Change weather on java
2. See changes only on Java, and not bedrock

### Expected behaviour

I expect the weather to change to the desired setting when changing the value.

### Geyser Dump

https://dump.geysermc.org/QuE8VeMBGwbQN1ffINji9cQOnMWHxlDH

### Geyser Version

1.41-SNAPSHOT (git-master-e0e6605)

### Minecraft: Bedrock Edition Version

1.71.1

**Comment by ver24436** [comment]
So I'm unsure if this is related, but I've noticed after installing EssentialsX I started having this issue with it raining constantly for bedrock users. Using /weather clear - has no effect.

I have the world set to use /gamerule doWeatherCycle false - without EssentialsX works as expected, but with EssentialsX installed, it will frequently rain on the bedrock client. If the player leaves and rejoins it clears, or if the player uses /pweather reset.

**Comment by Camotoy** [comment]
Possibly related: https://bugs.mojang.com/browse/MCPE-131325

**Comment by IonicEcko** [comment]
Have this issue regularly on my server. Its 1.18.2 Fabric with Floodgate, Geyser and Lithium.

Can provide anything needed to help resolve.

**Comment by Stuart-Cox** [comment]
> Using `/weather rain` and `/weather clear`, then `/weather thunder` and `/weather clear` all showed the correct weather. I've heard mentions of incorrect weather since about 1.17, so I'm sure this bug still exists, just with more specific details.

I am currently experiencing this exact behaviour regularly on my 1.19 spigot server.
Using /weather clear on its own doesn't clear the "fake" bedrock rain but doing /weather rain, then /weather clear does. 
If I don't do this command it will rain ethier near infinitely. The "fake" bedrock only rain doesn't have the effect of it actually raining (snow tiles don't appear in snowly biomes).

This is a regular occurrence on my server, so I can provide any evidence needed to move this out of "Unconfirmed"

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/pull/3352 should fix some occurences of this - but besides that, ive seen this bug occur often enough on normal bedrock servers too. That kind of weather desync is unfortunately only temporarily fixed after restarting the bedrock client

**Comment by Konicai** [comment]
Does this still occur?

**Comment by HunterOcelot27** [comment]
Yes it does and appears to often preceed actual java rain and rains for a while after java rain stops. appears to be more of how sensitve bedrock defines the humidity... 
also it rains while in a dry biome.
