### ISSUE TITLE
Hide remote ip address from clients.

### ISSUE THREAD

**Issue by Leymooo** [GeyserMC/Geyser#2501]
### What feature do you want to see added?

I think geyser should not expose remote ip address to clients.
For example: 
![image](https://user-images.githubusercontent.com/8667294/131086544-8414d8bf-677c-438c-b21d-afd878a7a201.png)

Maybe these messages revealing the ip address could be replaced with translatable ones. For example 'Could not connect to remote server. Please try again' 

### Are there any alternatives?

-

**Comment by Leymooo** [comment]
TCPShield -> BungeeCord and Geyser-Standalone -> BungeeCord. We know that TCPShield can provide geyser tunnel, but we want to preserve orignal players ips(ip forwarding) so we decided to buy VPS on ovh and run geyser proxy seperatly. Usually geyser does not show bungeecord IP to players, but there is a risk of leak, when bungeecord will not available (proxy restart, DC network fault, DS problem, etc).

**Comment by Konicai** [comment]
So when you tried the bedrock tunnel, the IP addresses of bedrock players were not passed to Geyser-Bungeecord?

**Comment by Leymooo** [comment]
Yes. Players have TCPShield's ip addresses instead of theirs.
