### ISSUE TITLE
1.18 beta on bedrock not joining 1.18 exp snapshot on java

### ISSUE THREAD

**Issue by TrillionDeTurtle** [GeyserMC/Geyser#2506]
### Describe the bug

there is no geyser standalone proxy that allows for this

### To Reproduce

load up 1.18 on both versions
join geyser server connecting to java one

### Expected behaviour

Outdated geyser proxy! im still on 1.17.10/1.17.11

### Geyser Version

1.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Camotoy** [comment]
Unfortunately, betas are not supported by Geyser on either end of the equation.
