### ISSUE TITLE
Crashing iPhone 6 client

### ISSUE THREAD

**Issue by GronyRalph** [GeyserMC/Geyser#2509]
### Describe the bug

So I got a bungeecord network, added Geyser and floodgate, everything seems to be and does work fine, except I think Geyser itself has an issue where on the iPhone 6 any Geyser server crashes the client, I got the game from the store, so the version is the latest one, my friends can join from android without trouble and I tried joinning any other server with the geyserconnect public server but it just crashes, black screen 1s and boom, out of the game. On my server with the plugin goes a little further cuz it like flashes the void when joining, I see my hand and nothing else, but it just crashes.
And it isn't my iPhone, every other server works flawlessly, even the geyserconnect one before I get into any server, no lags, no hot device at all, just crashes. It's not my server cause I can't join any other one with Geyser, it always crashes

### To Reproduce

1. Get the game into your iPhone 6
2. Try to join any Geyser server

### Expected behaviour

To join normally without crashing the whole client

### Geyser Version

1.4.1-SNAPSHOT (git-master-26a778f)

### Minecraft: Bedrock Edition Version

1.17.11 (Idk, the one from the app store)

**Comment by Konicai** [comment]
Unable to reproduce on BE 1.17.11 (build 6874656) on iPhone 6s 13.6.1

**Comment by GronyRalph** [comment]
I got the iPhone 6 not 6s

**Comment by Camotoy** [comment]
I'm unable to replicate with an iPhone 6.

**Comment by jackson-57** [comment]
It might be worth reinstalling Minecraft to see if your client is somehow corrupted. If needed, you could probably back up your worlds through the Files app on your phone. Also, what iOS version are you running? I'm not sure if it would make a difference, but I might as well ask.

**Comment by GronyRalph** [comment]
It didn’t work and I have iOS 12.5.4

**Comment by Camotoy** [comment]
I still cannot replicate after updating to iOS 12.5.4 and joining the Geyser Test Server.

**Comment by GronyRalph** [comment]
Mine crashes, ig it's my phone then :(
