### ISSUE TITLE
Scoreboard not working correctly

### ISSUE THREAD

**Issue by TheBlankSlate** [GeyserMC/Geyser#2510]
### Describe the bug

There are two bugs at play here:
1. I'm not sure if it's the scoreboard plugin or Geyser but whenever I join/are just on the server on bedrock I get spammed with this in the console.

3. Another bug that happens is that when I toggle off the scoreboard using `/sb toggle` it doesn't completely disable the scoreboard until I rejoin the server (it does however stop the console spam). 

Please refer to the video/screenshot section for a visualization of the problem

### To Reproduce

First bug:
1. Make sure you have the scoreboard toggled on with `/sb toggle`

Second bug:
1. toggle off the scoreboard with `/sb toggle`

### Expected behaviour

For the first bug, it's supposed to display the information as well as not spam the console.

For the second bug, it's supposed to completely disable the scoreboard

### Screenshots / Videos

Here is the Error:
![image](https://user-images.githubusercontent.com/68253054/131413822-d21a292e-00bc-44fb-bce1-4997fd82867f.png)

Here is what happens in java (what is supposed to happen):
https://user-images.githubusercontent.com/68253054/131414488-ae119868-568c-4813-a619-01925ee5fa4b.mp4

Here is what happens in bedrock:
https://drive.google.com/file/d/1Bu_9ZJBepsupUZUMZkiRbkgOoYxwv-Mr/view?usp=sharing

### Server Version and Plugins

Java Version `16`
MC Java Edition Version: `1.17.1`
Scoreboard Plugin: `SimpleScore` by `R4G3__BABY`

Paper Version:
``` 
This server is running Paper version git-Paper-231 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f99119e)
You are running the latest version
Previous version: git-Paper-228 (MC: 1.17.1)
```

### Geyser Dump

https://dump.geysermc.org/1fJX9eZ6oVkcxh51n6GMo3Ghfc3PybL9

### Geyser Version

1.4.2-SNAPSHOT (git-master-26c7553

### Minecraft: Bedrock Edition Version

1.17.11

**Comment by RednedEpic** [comment]
Stale. Please open a new issue with updated replication steps if this still occurs.
