### ISSUE TITLE
Item Frame Invisibility Bug

### ISSUE THREAD

**Issue by Magstar1670** [GeyserMC/Geyser#2512]
### Describe the bug

When trying to give an invisible item frame, The invisibility effect is only on the JAVA side, Bedrock still sees the frame.

### To Reproduce

Give your self an item frame with /minecraft:give <user> item_frame{EntityTag:{Invisible:1b}}
Place it wherever with an item in it.
Java will not see the frame, but bedrock will.

### Expected behaviour

Expected behavior is for the item frame to be invisible to both clients

### Screenshots / Videos

Bedrock
![Screenshot_20210902-140241](https://user-images.githubusercontent.com/87979012/131901823-81605d24-8d68-4a10-95fb-ec33d1b379e3.png)
Java
![2021-09-02_14 01 12](https://user-images.githubusercontent.com/87979012/131902025-2c2aa604-26be-4616-a086-d2097e0c2aba.png)

### Server Version and Plugins

1.17.1
WorldGuard
Worldedit
ViaVersion
Vault
SudoSigns
SimplePortals
ServerSelectorX
ProtocolLib
PocketGames
PartyGamesX
Paintball
Luckperms
Ipwhitelist
holographicDisplays
floodgate-spigot
EssentialsXSpawn
EssentialsXProtect
EssentialsXChat
EssentialsXAntibuild
EssentialsX
CoreProtect

### Geyser Dump

https://dump.geysermc.org/XhM0nCnpGGlDuCKtfqJa74l4qn2vvzSM

### Geyser Version

1.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

v1.17.10

**Comment by Camotoy** [comment]
Unfortunately, this is a Bedrock limitation as it does not have invisible item frames. I have added it to our Current Limitations page for documentation: https://github.com/GeyserMC/Geyser/wiki/Current-Limitations

Thank you for reporting anyway!
