### ISSUE TITLE
Anvil showing less levels than Java client

### ISSUE THREAD

**Issue by MalexTP** [GeyserMC/Geyser#2515]
### Describe the bug

A bedrock user reported me that can't put together two fishing rods because it "need" 6 leves but in java it need 24 or 28 levels

### To Reproduce

1. put together two fishing rods in bedrock
2. put together the same two fishing rods in java
3. compare levels

### Expected behaviour

same levels at java and bedrock

### Screenshots / Videos

bedrock side:
![imagen](https://user-images.githubusercontent.com/24663715/132141808-13497334-5c57-4f59-b373-1a3e4974e958.png)
java:
![imagen](https://user-images.githubusercontent.com/24663715/132141811-6ac33200-bbe0-4b6c-967a-8eefa4aed687.png)

### Server Version and Plugins

This server is running Paper version git-Paper-249 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6fa1983)
plugins:
![imagen](https://user-images.githubusercontent.com/24663715/132141851-5c517a48-b3b5-4e85-b948-84f7e933f4ff.png)

### Geyser Version

Loading Geyser version 1.4.2-SNAPSHOT (git-master-c1e66f3)

### Minecraft: Bedrock Edition Version

1.17.1

**Comment by Camotoy** [comment]
This *may* be a Bedrock limitation as we can't control enchantment levels on anvils as far as we know.

**Comment by Yuta12342** [comment]
Luckily, the Server Side should probably correct how much XP is used, when the deed is done.
Maybe if Geyser gets support for having Behavior Packs loaded, they could possibly use those to fix the issue.

**Comment by Camotoy** [comment]
Behavior packs are largely used to control serverside behavior. Anything those can do we can already program.

**Comment by MalexTP** [comment]
yep users can enchant if they have the required java levels but the problem is that they cant know how much they need if theres no a java player to help him
