### ISSUE TITLE
Cannot Whitelist a player

### ISSUE THREAD

**Issue by bryanfolstad** [GeyserMC/Geyser#2516]
### Describe the bug

using the command "fwhitelist add playername" brings up the following error in the command prompt or Minecraft console

### To Reproduce

1. type "fwhitelist add playername" into the console to get a result

### Expected behaviour

I should get "player name has been whitelisted" or similar result.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/90162995/132147408-24e5a1ab-1e14-4d47-a9a3-bb11261fbb13.png)

### Server Version and Plugins

PaperMC 1.17.1-250
BetterSleeping V4
DoubleShulkerShells V1
Dynmap 3.2 beta 3 spigot
Floodgate spigot 27
Geyser spigot 842
NoEndermanGrief 1.14_1.0.2

### Geyser Dump

https://dump.geysermc.org/Ociv5byCa1txS1tTjxZe0V1hk3Uu5aYS

### Geyser Version

1.17.1-R0.1-SNAPSHOT

**Comment by Camotoy** [comment]
This is a bug we are aware of; I'm going to close this issue in the meantime as this doesn't belong in the Geyser repository. The easiest solution to working around this is to ask the Xbox player to join the `test.geysermc.org` server, then try whitelisting.
