### ISSUE TITLE
Cannot add or remove players to the whitelist.

### ISSUE THREAD

**Issue by Ev3Friv** [GeyserMC/Geyser#2519]
### Describe the bug

When I tried to whitelist any bedrock player I got this error: "[ERROR] [floodgate] Got an error from requesting the xuid of a Bedrock player: The Xbox Api isn't setup correctly. Please contact a GeyserMC developer" 
I tried joining the geyser test server with the bedrock player but that didn't fix the issue either.
I have several different players asking to be whitelisted. They are all on different devices and they all have the same isssue.

### To Reproduce

Use the command /whitelist add <playername>
Or use  /whitelist remove <playername>

### Expected behaviour

A message saying the player was either removed or added to the whitelist.

### Geyser Version

1.4.2-SNAPSHOT (git-master-d602d82)

**Comment by Camotoy** [comment]
This is a known issue at the moment. One workaround is to have the Bedrock player join `test.geysermc.org` and then try to whitelist. If that does not work, have the player join your server as it is temporarily un-whitelisted, then whitelist them normally like a Java player.
