### ISSUE TITLE
Skulls and heads all show up as skeleton skulls facing same direction

### ISSUE THREAD

**Issue by DoctorMacc** [GeyserMC/Geyser#252]
**Describe the bug**
All skulls and heads appear placed as a skeleton skull, with the same orientation.

**To Reproduce**
Place any skull in the world.

**Expected behavior**
Skulls and heads show up as their proper values in-world.

**Server version**
Paper Build 146

**Geyser version**
Jenkins Inventory 11

**Bedrock version**
v1.14.30

**Additional context**
The skull heads all showing up as skeleton is the same problem that beds had, so it's likely that a restructuring of the code is required in order to efficiently solve this problem.

**Comment by rtm516** [comment]
Looking over the wiki and some bedrock stuff, I'm not sure bedrock support custom skulls yet so not sure if this will be possible. The held item doesn't have the correct texture either for player heads its just the default steve.

**Comment by DoctorMacc** [comment]
No, this issue is not referring to custom skulls - zombie heads, generic player heads, wither skeleton heads all show up in the Inventory branch as a skeleton head.
