### ISSUE TITLE
first letter in the Player username from bedrock is (.) or (,)

### ISSUE THREAD

**Issue by FadDevelop** [GeyserMC/Geyser#2525]
### What feature do you want to see added?

I have an server with EssentialsX plugin. And i download geysermc and floodgate. i invite my brother at pocket edition to play with me. but, hes first letter name is (.) or (,). i want to tp to him but i cant. because, EssentialsX says its not a "Valid" name. so i hope the letter name doesn't have first letter with (.) or (,)

### Are there any alternatives?

I dont have

**Comment by SuryanshxND24** [comment]
That is a default prefix that is added by *floodgate* plugin to differentiate the bedrock players from java.

**Comment by FadDevelop** [comment]
> That is a default prefix that is added by _floodgate_ plugin to differentiate the bedrock players from java.

Ohhh okay thank you
