### ISSUE TITLE
Bedrock players crash

### ISSUE THREAD

**Issue by HysteriaMC** [GeyserMC/Geyser#2527]
### Describe the bug

I've installed Geyser today, and within 20 seconds of a Bedrock player joining, they crash. 

Java players are fine, and they can play as normal and expected. 

Console does get spammed with these: 

`<username> moved too quickly. current position: (88.289925, 24.62001, 153.50241), new position: (0.3, 42.22313, 0.3)`

`13.09 16:04:20 [Server] INFO [Geyser-Spigot] Recalculating position...
13.09 16:04:20 [Server] INFO [Geyser-Spigot] Team packet  CREATE []
13.09 16:04:20 [Server] INFO [Geyser-Spigot] Team packet  CREATE []
13.09 16:04:20 [Server] INFO [Geyser-Spigot] Team packet  CREATE []
13.09 16:04:20 [Server] INFO [Geyser-Spigot] Team packet  CREATE []`

`Spawned entity ARMOR_STAND at location (81.609, 24.261, 163.104) with id 52 (java id 71)`

### To Reproduce

1. Join the server on Geyser

### Expected behaviour

I expected them to be able to play without crashing

### Screenshots / Videos

https://user-images.githubusercontent.com/87421210/133098407-bf0fc6ef-510b-4d3d-94a2-85419d6dec71.mp4

### Server Version and Plugins

Server version: PaperMC 1.16.5
Running ViaVersion

### Geyser Dump

https://dump.geysermc.org/vmgwseTe4Ws1jkgSGInib1MY6wyoWFiY

### Geyser Version

1.4.3-SNAPSHOT (git-master-e13643d) (Java: 1.17.1, Bedrock: 1.17.10/1.17.11)

### Minecraft: Bedrock Edition Version

1.17.10/1.17.11

**Comment by HysteriaMC** [comment]
Update:

After some testing, this ONLY occurs on Windows 10 edition 

(Although I haven't been able to test Console/iOS and won't be able to)

**Comment by S0M0G** [comment]
If you are hosting the server on the same internet, then it'll happen. The same happened to me. But if not idk.

**Comment by lukeeey** [comment]
Is this still an issue on the latest master build?

**Comment by HysteriaMC** [comment]
> Is this still an issue on the latest master build?

I will check soon and get back to you.

**Comment by Konicai** [comment]
Let us know if this still occurs
