### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Den4enko** [GeyserMC/Geyser#2528]
### Describe the bug

The player starts to lag, and an error is written in the console. I don't know why or how it happened.

### To Reproduce

I don't know, this is happened randomly

### Expected behaviour

The player starts to lag, and an error is written in the console.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/60628208/133132026-5601a1b3-9d94-4b44-9a56-bbb8a8d1fd27.png)

### Server Version and Plugins

This server is running Purpur version git-Purpur-1385 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 529daae on ver/1.17.1)

Plugins:
Essentials, Geyser, Floodgate, LuckPerms, Vault, Themis, ProtocolLib

### Geyser Dump

https://dump.geysermc.org/chkcqLbEf6vrG5v4XBdqnwLZJ6XFUnW4

### Geyser Version

1.4.3-SNAPSHOT (git-master-e13643d)

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Camotoy** [comment]
When does this happen?

**Comment by Den4enko** [comment]
I don't know for sure, but probably when a player opens a double chest
