### ISSUE TITLE
Bedrock - Connection closed

### ISSUE THREAD

**Issue by Broascaa** [GeyserMC/Geyser#2529]
### Describe the bug

So i connect on my Java Server using Bedrock Edition but i got disconnect with message "Connection closed" and no errors displayed in console.

### To Reproduce

I installed geyser-bungeecord and floodgate-bungeecord & floodgate-spigot (on all backend servers), setup port and ip, restarted the proxy and tried to connect for that error.

### Expected behaviour

-

### Screenshots / Videos

![InkedCapture_LI](https://user-images.githubusercontent.com/86567732/133226699-d0fa8049-9b7f-4513-b70e-068fe790363b.jpg)
This is all i see on bungee console

### Server Version and Plugins

waterfall-1.17-449
floodgate-bungee 2.0-SNAPSHOT
geyser-bungeecord 1.4.3-SNAPSHOT

backend servers:
floodgate-spigot 2.0-SNAPSHOT

### Geyser Dump

https://dump.geysermc.org/7mLt0355AOcdRtLNORn5FyLF80udhKb9

### Geyser Version

1.4.3-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.11

**Comment by Camotoy** [comment]
Are there any logs on the backend Spigot server?

**Comment by Broascaa** [comment]
No, that is all i see

> Are there any logs on the backend Spigot server?

**Comment by WitheRskelett** [comment]
Yes on Paper, but with updating the plugin, it was gone.

**Comment by Broascaa** [comment]
Any update?? 1 week already guys :|

**Comment by TacoGuyAT** [comment]
> 
> 
> Any update?? 1 week already guys :|

Same thing, latest Geyser, Floodgate and Paper without bungee
Tested bedrock clients: 1.17.10, build 6472284 on W10 and 1.17.11, build 6874675 on Android

https://dump.geysermc.org/oCAVojskI6Y1RlfazNUn1qRBt1jWiYSb
[2021-09-20-21.log](https://github.com/GeyserMC/Geyser/files/7198438/2021-09-20-21.log)

**Comment by Camotoy** [comment]
@TacoGuyAT does this persist if you remove Floodgate?

**Comment by TacoGuyAT** [comment]
> 
> 
> @TacoGuyAT does this persist if you remove Floodgate?

Nope, only while I use Floodgate with local storage

**Comment by Camotoy** [comment]
Can you post your Floodgate config and a Geyser dump?

**Comment by TacoGuyAT** [comment]
> 
> 
> Can you post your Floodgate config and a Geyser dump?

Sure:
https://dump.geysermc.org/wZ3znrEDdWCqmCsxFfm8ZelsL1yNpPI1 (new one)
[configs.zip](https://github.com/GeyserMC/Geyser/files/7231394/configs.zip)
