### ISSUE TITLE
Geyser does not shut down with /geyser shutdown, or Control-C after a player has joined

### ISSUE THREAD

**Issue by DoctorMacc** [GeyserMC/Geyser#253]
**Describe the bug**
`/geyser shutdown` does not fully shutdown Geyser after a player has joined through Geyser - in Linux, two Control-Cs are required to terminate the process.

**To Reproduce**
1. Run Geyser
2. Join Geyser
3. Try to shutdown Geyser

**Expected behavior**
Geyser cleanly shuts down.

**Geyser version**
Jenkins Inventory Latest

**Comment by RednedEpic** [comment]
> **Describe the bug**
> `/geyser shutdown` does not fully shutdown Geyser after a player has joined through Geyser - in Linux, two Control-Cs are required to terminate the process.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Run Geyser
> 2. Join Geyser
> 3. Try to shutdown Geyser
> 
> **Expected behavior**
> Geyser cleanly shuts down.
> 
> **Geyser version**
> Jenkins Inventory Latest

Unable to reproduce. Ran Geyser bukkit and was able to join, shut it down using /geyser shutdown, then booted up Geyser standalone which pointed to a different server and had no problems in the process.

**Comment by rtm516** [comment]
This is happening for me as well with the latest build (https://github.com/GeyserMC/Geyser/commit/16388a1f85fb5a805c880fd176afd1f8ae47f4b4)
![image](https://user-images.githubusercontent.com/5401186/78550398-ecb4f400-77fb-11ea-96c5-ec9a403a6f87.png) with both ctrl+c and `/geyser shutdown` on Windows 10
