### ISSUE TITLE
Bedrock players appear on a void world

### ISSUE THREAD

**Issue by bripalow** [GeyserMC/Geyser#2532]
### Describe the bug

When a bedrock player joins to my server, he appears on a void world, and any command is useful..
I show you a picture of my bungecord console and the screen of the bedrock player.

### To Reproduce

1.Only put geyser-bungeecord.jar and floodgate into bungeecord plugins
2. Start bungeecord
3. Join from a bedrock client

### Expected behaviour

I wanna a solution for this, because for me is useful geyser, and it's the first time that I prove it

### Screenshots / Videos

![WhatsApp Image 2021-09-15 at 5 11 44 PM](https://user-images.githubusercontent.com/86530261/133524162-0c24a09f-5b54-44db-aa43-a73f4b666a8a.jpeg)
![image](https://user-images.githubusercontent.com/86530261/133524189-1be0fecb-d988-4529-8cea-e9881abe370a.png)

### Geyser Dump

https://dump.geysermc.org/MfhdQW7ho2YvuNjCuUadoe6IwKwudP3o

### Geyser Version

1.4.3-SNAPSHOT (git-master-e13643d) 

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Konicai** [comment]
Hi, please consider trying plugin debugging:
```
If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
- Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.
```

I would also definitely try using something other than FlameCord, like Waterfall or BungeeCord.

**Comment by l3unnyAnoF4** [comment]
I have this problem.

**Comment by RednedEpic** [comment]
> 
> 
> I have this problem.

If you're going to bump an issue please at least provide some meaningful information as to how you encountered this and try the steps given to you above, along with providing a dump and any other relevant info.

**Comment by l3unnyAnoF4** [comment]
same 
1.Only put geyser-bungeecord.jar and floodgate into bungeecord plugins
2. Start bungeecord
3. Join from a bedrock client

1.4.3-SNAPSHOT Build #858

Bedrock Edition 1.17.11

**Comment by l3unnyAnoF4** [comment]
https://streamable.com/xdc3mt

**Comment by Camotoy** [comment]
Please send a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by l3unnyAnoF4** [comment]
https://dump.geysermc.org/WoWSqld0nuYY4rXLJvNtXr9kAP0cKrts

**Comment by Camotoy** [comment]
Seems fine - please send logs from BungeeCord and your backend server.

**Comment by l3unnyAnoF4** [comment]
https://mclo.gs/gD269hK

**Comment by l3unnyAnoF4** [comment]
I have 2 server machines and one of them is not working.

**Comment by l3unnyAnoF4** [comment]
The config settings are the same, Java is the same.

**Comment by l3unnyAnoF4** [comment]
https://dump.geysermc.org/J5NVwdifl6oet0RGCduo2GvRoj4XHQEe

Log BungeeCord: https://mclo.gs/bRNEFhz
Log paper: https://mclo.gs/JyKbSIi

**Comment by l3unnyAnoF4** [comment]
So how can fix it?

**Comment by Camotoy** [comment]
Try toggling `send-floodgate-data` in your Floodgate config?

**Comment by l3unnyAnoF4** [comment]
I didn't change

**Comment by Camotoy** [comment]
Can you connect from Java Edition?

**Comment by l3unnyAnoF4** [comment]
Yes i can

**Comment by bripalow** [comment]
Please I would really aprecciate if you do the questions in another ticket.. I am constantly receiving mails in my inbox and it's so awful.. Thank you

**Comment by bripalow** [comment]
> Hi, please consider trying plugin debugging:
> 
> ```
> If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
> - Temporarily remove/move half of your plugins from your server's plugins folder.
> - If the problem persists, remove another half.
> - If the problem goes away, swap that half of your plugins with the other half.
> - Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.
> ```
> 
> I would also definitely try using something other than FlameCord, like Waterfall or BungeeCord.

Ok, I will do that

**Comment by l3unnyAnoF4** [comment]
Is this a problem with your server?  I'm looking for a solution  If it bothers me  I will open a new ticket

**Comment by bripalow** [comment]
Yes, please open a new ticket... I would really aprecciate it

**Comment by Camotoy** [comment]
Unless we determine that your issues are not related, please do not open a new ticket. You should be able to disable email notifications if you need to, or read through and see if anything applies to you. Thanks!

**Comment by l3unnyAnoF4** [comment]
I was looking for someone who had the same problem but was told me to open a new ticket.  I didn't even understand what he was thinking.

**Comment by ZeusRyu** [comment]
I have same issues, 
My server is based on paper, and I use geyser to connect java and pocket mc for ipad. 

It works perfect for 2 weeks(at that time I didn't use floodgate but use geyserconnect.net for offline mode) but suddenly my ipad couldn't get into server. So I tried few things; update geyser, install floodgate.

But after that I can connect to server but same things  happened that you guys mention above..

For java(and also localhost), it works perfect but not for pocket

**Comment by bripalow** [comment]
I proved removing all plugins, but it still gets bedrock player, in a void world

**Comment by l3unnyAnoF4** [comment]
This problem persists after using the floodgate as well.

**Comment by l3unnyAnoF4** [comment]
I use cpu ryzen server work normally
But cpu intel server not working 2 servers.

**Comment by l3unnyAnoF4** [comment]
![7ACF81BC-0F66-40E2-89C7-0922C672DB16](https://user-images.githubusercontent.com/67956962/134818769-548b5664-3617-451c-941a-3841e03bae52.png)

**Comment by Yuta12342** [comment]
This is normal usually, when you first join a Geyser World, however, sometimes Geyser takes a while to load things. If it takes too long, though, it could be that whatever you are using to run the server isn't powerful enough to load both at once, since it's technically 2 servers running. Check to make sure you have enough RAM and Storage to be able to run both simultaneously inside. Speaking of that, though... How long have you waited in this Void, before calling this an issue?

**Comment by marko-pilipovicc** [comment]
I get a similar issue, but it only occurs after running Geyser-Velocity after about 24 hours, however, it can be less time or more time depending on the total number of joins I believe. Players are able to load onto the server, however, past a certain point it goes from  taking 1-5 seconds like normal to around 10 minutes to load the world. Processing power shouldn't be an issue since we allocate 32GB and run it on an EPYC cpu.

**Comment by Camotoy** [comment]
What version of Velocity are you using?

**Comment by l3unnyAnoF4** [comment]
> This is normal usually, when you first join a Geyser World, however, sometimes Geyser takes a while to load things. If it takes too long, though, it could be that whatever you are using to run the server isn't powerful enough to load both at once, since it's technically 2 servers running. Check to make sure you have enough RAM and Storage to be able to run both simultaneously inside. Speaking of that, though... How long have you waited in this Void, before calling this an issue?

I use cpu i9 11900K ram 32 this problem still exists i waited five minutes, but there was no response.

**Comment by Jens-Co** [comment]
Hi @bripalow, I see that you closed the issue. Would you mind to tell us if you resolved the issue and maybe add info on how you fixed it for other people ? Thanks ;)
