### ISSUE TITLE
Trying to connect with 1.17.2 on pe

### ISSUE THREAD

**Issue by mei2011** [GeyserMC/Geyser#2533]
### Describe the bug

whenever i try to join on a updated mcpe client it gives me this:
Outdated Bedrock client! This server supports the following Bedrock versions: 1.17.10/1.17.11

### To Reproduce

1. Connect To 1.17.1 Server
2. Issue

### Expected behaviour

1. Join Server
2. Connect Normaly

### Geyser Version

latest as of 9/17/21 at 7:27 pm

### Minecraft: Bedrock Edition Version

1.17.2

**Comment by mei2011** [comment]
pls help

**Comment by RednedEpic** [comment]
As the kick message says, only 1.17.10/11 are supported. Please update your Minecraft Bedrock.

**Comment by Camotoy** [comment]
1.17.10 != 1.17.1

**Comment by mei2011** [comment]
did you look at the version

**Comment by Camotoy** [comment]
1.17.10 is newer than 1.17.2.

**Comment by mei2011** [comment]
ohh sorry i was confused

**Comment by eurom7020** [comment]
very sorry.
