### ISSUE TITLE
Connect vanilla 1.16.x server in mcbe 1.17.10

### ISSUE THREAD

**Issue by Phongvngg1** [GeyserMC/Geyser#2534]
### What feature do you want to see added?

I have up to date minecraft be but i cant join my server, i want play with my friends

### Are there any alternatives?

I tried use geyserconnect.net but not work

**Comment by Jens-Co** [comment]
There are 2 unaffiliated geyserconnect servers running( us.geyserconnect.net / eu.GeyserConnect.net ) please join their discord if further help is required. Thanks https://discord.com/invite/3r7T9fXzDE

**Comment by Camotoy** [comment]
You can also install ViaVersion if you own the server.
