### ISSUE TITLE
BungeeGlitch

### ISSUE THREAD

**Issue by HarshVardhanSingh-op** [GeyserMC/Geyser#2535]
### Describe the bug

Not Able To Join Server using Geyser .. Config -> https://paste.gg/3e10926f7e694ec2adeed8096ef5534c

Any Idea why?

### To Reproduce

No errors

### Expected behaviour

Idk Why its Happening.. my java ip and port are in config you can check... I am trying to Connect but its not working

### Geyser Dump

https://dump.geysermc.org/Cfdk1MWgM4m97xwv4qruGPhRlXFdMnPF

### Geyser Version

Latest

### Minecraft: Bedrock Edition Version

1.17.1

### Additional Context

F

**Comment by Camotoy** [comment]
What error do you get when attempting to join?

**Comment by HarshVardhanSingh-op** [comment]
@Camotoy No Ping..

**Comment by SuryanshxND24** [comment]
Please can provide the logs of ur server and the config again, and please check ur ip address are some on both bungee config and the geyser

**Comment by Camotoy** [comment]
You're welcome to continue support here, but we don't keep issues up of servers that can't be connected. You can also join our Discord for more help. Thanks!
