### ISSUE TITLE
Can't trust bedrock players to claims

### ISSUE THREAD

**Issue by elaineandsparky** [GeyserMC/Geyser#2536]
### Describe the bug

If a java player creates a claim using griefprevention they can not /trust a bedrock player to the claim. It says in the java players chat that they have been trusted but the bedrock player can't do anything in the claim like break blocks as it says they don't have permission to build in that claim.
We use the . prefix and include this in the /trust command.

### To Reproduce

Java player trusts bedrock to their claim
bedrock player tries to break a block in that claim

### Expected behaviour

for the bedrock player to be trusted to the claim

### Geyser Dump

https://dump.geysermc.org/2zwkahZ6sFlBombvnzRoMqsLYGDnjWLI

### Geyser Version

860

### Minecraft: Bedrock Edition Version

1.17.1

**Comment by Jens-Co** [comment]
Hello there, This is indeed an issue with the GriefPrevention plugin. Camotoy has an open pr to their repo (https://github.com/TechFortress/GriefPrevention/pull/1543) this pr is not yet merged so you need to wait.
