### ISSUE TITLE
Paper anti xray lags bedrock players

### ISSUE THREAD

**Issue by ramidep** [GeyserMC/Geyser#2537]
### Describe the bug

When paper anti xray is enabled, it lags bedrock players and some times disconect them for inactivity.

### To Reproduce

1-Enable paper anti xray in paper.yml and select engine mode 2
2- Start your minecraft server with geyser installed
3- Connect to the server on bedrock edition 

### Expected behaviour

Paper anti xray doesn´t lag bedrock players

### Server Version and Plugins

Purpur version git-Purpur-1393 (MC: 1.17.1)
Plugins (34): AutoBroadcast, BetterTeams, BlockLocker, Citizens, CustomCrafting, DiscordSRV, eBackup, Essentials, Geyser-Spigot, HolographicDisplays, Images, InvSeePlusPlus, LoginSecurity*, LuckPerms, Multiverse-Core, Multiverse-Portals, MythicMobs, NPC_Destinations, PlayerParticles, PlayerReport, ProtocolLib, Randomtp, Shopkeepers, SkinsRestorer, SpigotPing, TAB, Themis, UltimateAntiBot, Vault, ViaBackwards, ViaVersion, WolfyUtilities, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/92DOKag6eXWXXuvB1Wp93NmIz0TG5uRa

### Geyser Version

git-master-fdca9f9

### Minecraft: Bedrock Edition Version

1.17.11

**Comment by Greaper88** [comment]
Select engine mode 1 instead. The fake ores of mode 2 are what causes lag. The stone disguising is easier for Bedrock to handle. At least this was my previous experience.

**Comment by ramidep** [comment]
ok
