### ISSUE TITLE
Client crash when taking damage/respawning

### ISSUE THREAD

**Issue by cokeman439** [GeyserMC/Geyser#2538]
### Describe the bug

The bedrock edition clients (Xbox 1 S, & Windows 10 Edition) connected to the server crash when taking damage, or respawning. 

### To Reproduce

1.) Create a death tracking scoreboard objective.
2.) Add the above scoreboard objective to the sidebar.
3.) Take damage, or attempt to respawn.

### Expected behaviour

The client does not crash.

### Screenshots / Videos

[scoreboard.zip](https://github.com/GeyserMC/Geyser/files/7199853/scoreboard.zip)

### Server Version and Plugins

Paper-1.17.1-266
Floodgate Build #33

### Geyser Version

Geyser Build #861

### Minecraft: Bedrock Edition Version

1.17.11

**Comment by Camotoy** [comment]
Does this still occur with the latest Geyser build?

**Comment by Konicai** [comment]
Closing, let us know if this issue still occurs.
