### ISSUE TITLE
Quick command selector for non OP bedrock players 

### ISSUE THREAD

**Issue by AlexXanderGrib** [GeyserMC/Geyser#2539]
### What feature do you want to see added?

Facts:
1. Type commands on Xbox One is pain
2. Quick command selector ("/" button) is available only for OPs
3. Giving OP to somebody who is not a server owner is generally is bad practice.

I have a moderator, a really good one, but he is playing from Xbox and has struggled to teleport to players cause of this issue.

I know that the "/" button is enabled only for OPs on bedrock edition, but I think it's possible to check if the player has permissions:
```
minecraft.command.gamemode.survival
minecraft.command.gamemode.creative
minecraft.command.gamemode.adventure
minecraft.command.gamemode.spectator
minecraft.command.weather
minecraft.command.time
minecraft.command.setworldspawn
```
and mark them as OP on bedrock

### Are there any alternatives?
Giving the moderator OP

**Comment by Konicai** [comment]
I would suggest finding or creating a plugin that uses Bedrock Forms to make administration/running certain commands easier:
https://github.com/GeyserMC/Floodgate/wiki/Forms

I know of this one (which has *no* affiliation with Geyser):
https://github.com/ProjectG-Plugins/GeyserAdminTools

**Comment by RednedEpic** [comment]
Out of the scope of Geyser. You can use the plugins above, but this could also be made into an extension in the future.
