### ISSUE TITLE
Using GeyserMC with older versions

### ISSUE THREAD

**Issue by kamenooyatu** [GeyserMC/Geyser#2545]
### What feature do you want to see added?

Is it possible to cross-play with older versions?
I was not able to get in after installing ViaVersion.(Connection closed.)
Will I be able to do this again?
My server version is 1.9.

### Are there any alternatives?

Viaversion was impossible.

**Comment by RednedEpic** [comment]
This is supported by using ViaVersion, so we have no intention of adding support for multiple Java Edition versions inside Geyser. Please make sure you use the latest version of both Geyser and ViaVersion.
