### ISSUE TITLE
Using offhand

### ISSUE THREAD

**Issue by kamenooyatu** [GeyserMC/Geyser#2548]
### What feature do you want to see added?

I'm using geyser.jer instead of Geyser-spigot, but when I type geyser offhand in geyser.jer, it says that this command can only be executed by players of the general version.
Can I use geyser.jar to make this possible?
My version is 1.9.

### Are there any alternatives?

The version is 1.9, so geeser-spigot cannot be used.

**Comment by Camotoy** [comment]
Geyser.jar is a standalone program. It cannot be run as a program.

Please join our Discord for the best chance of getting support for such an old version.
