### ISSUE TITLE
Allow usage of .mcstructure files from bedrock edition

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Geyser#2549]
### What feature do you want to see added?

Could there be a possible feature that allows players or the people who have access to server files to import .mcstructure from bedrock structure blocks. For example on a bedrock single player world i put my build into a structure block with the name netherbike and export it into a  .mcstructure file, than I go into my server files and drop it into a folder, then on java I can use a structure block and input the name netherbike and it would generate the build. This would be an easier way for bedrock players to import their builds. Not sure if this is possible but it would be cool if it would.

### Are there any alternatives?

There are no alternatives of this.

**Comment by lukeeey** [comment]
This sounds like it should be a separate plugin, i’ll probably create one.

**Comment by Yuta12342** [comment]
It probably would have to be a separate plugin, and also... I'm pretty sure that MCStructure Files are just 3D Model Files. If you are talking about the normal Structure Files, those are usually tied specifically to Worlds themselves. So, possibly, it wouldn't be a separate plugin, as the Geyser Side would possibly need to actually translate World Data from Bedrock to Java. But, I can't personally be sure.

**Comment by RednedEpic** [comment]
Not within the scope of the Geyser project. Closing.
