### ISSUE TITLE
Below 0 Support

### ISSUE THREAD

**Issue by Yuta12342** [GeyserMC/Geyser#2551]
### What feature do you want to see added?

It should be possible to allow players to move below 0 on Bedrock Edition. Possibly by treating the World like an "Experimental Features" World, using the "Caves and Cliffs" Feature, which on Bedrock allows new Caves to spawn below 0.

### Are there any alternatives?

There is no real Alternative, without having some weird workaround, which may or may not exist for Bedrock Edition, but I see no way to make it possible anyway else.

(Please correct me if I'm wrong-)

**Comment by Camotoy** [comment]
This option already exists. Enable `extended-world-height` in your Geyser config!

**Comment by Yuta12342** [comment]
> This option already exists. Enable `extended-world-height` in your Geyser config!

Oh. Somehow during this, I ended up mistaking that, and the 'above-bedrock-nether-building' toggle. I didn't wanna turn everything that tried to go higher than a certain amount into the End for some reason or another. 

Oops!
