### ISSUE TITLE
Issues connecting through Bedrock edition

### ISSUE THREAD

**Issue by ReefSalty** [GeyserMC/Geyser#2554]
### Describe the bug

When i connect i get this:
[06:16:23 INFO]: [Geyser-Spigot] /0.0.IP.0 tried to connect!
[06:16:24 INFO]: [Geyser-Spigot] Bedrock user with ip: /0.0.IP.0 has disconnected for reason CLOSED_BY_REMOTE_PEER

### To Reproduce

1. Most recent version of spigot jar files

### Expected behaviour

[06:16:23 INFO]: [Geyser-Spigot] /0.0.IP.0 tried to connect!
[06:16:24 INFO]: [Geyser-Spigot] Bedrock user with ip: /0.0.IP.0 has disconnected for reason CLOSED_BY_REMOTE_PEER

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/74215798/135213354-34d0a599-1816-49b6-b10c-ec889d595078.png)

### Server Version and Plugins

This server is running Paper version git-Paper-235 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2973e1c)

### Geyser Dump

https://dump.geysermc.org/mghdyy2wUAXmVzu8ib2dNnmWUAdrqRdD

### Geyser Version

This server is running Geyser version 1.4.3-SNAPSHOT (git-master-7f4d3de) (Java: 1.17.1, Bedrock: 1.17.10/1.17.11 - 1.17.30)

**Comment by Jens-Co** [comment]
Are you logged into Xbox ?

**Comment by ReefSalty** [comment]
yes

**Comment by Jens-Co** [comment]
Are you able to join any server on the featured servers list?

**Comment by Konicai** [comment]
Please contact us on Discord if you're still having issues with this
