### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by BloxBoss6** [GeyserMC/Geyser#2555]
### What feature do you want to see added?

In the wiki, specifically in the setup section under prerequisites, you mention how if you're running the server on an older version you should look into using ViaVersion. The problem is that versions of Minecraft before 1.17 use Java 11 or lower whereas Geyser needs 
Java 16. The only way to get this to work (which took me about 12 hours to figure out) was to install the Geyser Standalone instead of plugin version, and run the Geyser Standalone with Java 16 separately. 

### Are there any alternatives?

If this could somehow be reflected in the wiki or at least brought up that it should run on standalone I think most people would appreciate it. Thanks for all the hard work you do though! It's really appreciated!

**Comment by Chew** [comment]
I could have sworn we suggested this _somewhere_ but my 3 AM memory fades me... but you are right.

What part specifically did you struggle with? Server-specific issues with Java 16? Usually, 1.16(.5) runs fine with Java 16.

**Comment by Camotoy** [comment]
I have added the Paper "ignore Java version" flag to the wiki and clarified that Geyser standalone is possible if you cannot run Java 16.
