### ISSUE TITLE
Scoreboards not updating

### ISSUE THREAD

**Issue by chandlerpl** [GeyserMC/Geyser#2556]
### Describe the bug

The scoreboard is displayed once but then doesn't get updated again after and gets stuck showing the original version of the scoreboard.

### To Reproduce

1. Use the Geyser version 1.4.3-SNAPSHOT (git-master-59c34fb)
2. Install ProjectKorra and JedCore.
3. Set `Properties.BendingBoard` in the ProjectKorra config.yml to false and restart.
4. Update the JedCore scoreboard by scrolling through the hotbar to change slot.

### Expected behaviour

Expected the board to update the arrow on the scoreboard to your current hotbar slot.  

### Screenshots / Videos

![Geyser](https://user-images.githubusercontent.com/1355437/135366308-a11581a8-9b0b-49e3-9d9a-df939197d19e.jpg)

https://user-images.githubusercontent.com/1355437/135366448-bcbb7082-9542-4b09-8dd8-729e1d63fcda.mp4

### Server Version and Plugins

This bug happens when using Geyser version 1.4.3-SNAPSHOT (git-master-59c34fb).
Reverting to Geyser version 1.4.3-SNAPSHOT (git-master-56d49f3) has fixed this issue.

Java Version 16
Minecraft Java Edition Version: 1.17

ProjectKorra 1.9.0
JedCore 2.9.5

### Geyser Version

Geyser version 1.4.3-SNAPSHOT (git-master-59c34fb)

### Minecraft: Bedrock Edition Version

1.17.30

**Comment by Chew** [comment]
Does this issue happen on [build 883](https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/883/)?

**Comment by chandlerpl** [comment]
I've just tested it and this issue does not happen on build 883.
