### ISSUE TITLE
Problem after updating serv from 16.5 to 17.1

### ISSUE THREAD

**Issue by M4thy** [GeyserMC/Geyser#2558]
### Describe the bug

Hi everyone, I was sent here by your discord as my issue is still here after a day. I'm desperate in here..
I'm running a server on paper spigot in 17.1 and since I updated from 1.16.5 this morning, everytime my friend on bedrock connects, if he opens his inventory for too long, the game crashes without any notice.
I tried changing the server version (to the highest geyser paper build I've on OMGserv), updating every plugins I have, nothing changes that issue. They can connect but not for long and can't properly use the inventory.

As you might notice I'm not really aware of what I'm doing, just trying to run a little serv with friends and family with the little I know... But there I'm more than lost.

(you might notice also on the logs that I've POI mismatches and I think that i located where I built gates with commandblocks but I have no idea how to fix that issue)

thank you in advance for the time given, I really hope somebody will be able to help me and my friends to play again together...
thanks for this huge job you guys are doing !

https://dump.geysermc.org/RJ9m1YbaTyT0b3TBDQZsRp4ZRBGyIDdi

https://mclogs.minestrator.com/Px9edBR

[2021-10-01-8.log.gz](https://github.com/GeyserMC/Geyser/files/7267987/2021-10-01-8.log.gz)
[2021-10-01-10.log.gz](https://github.com/GeyserMC/Geyser/files/7267988/2021-10-01-10.log.gz)
[2021-10-01-12.log.gz](https://github.com/GeyserMC/Geyser/files/7267989/2021-10-01-12.log.gz)
[2021-10-01-13.log.gz](https://github.com/GeyserMC/Geyser/files/7267990/2021-10-01-13.log.gz)
[2021-10-01-15.log.gz](https://github.com/GeyserMC/Geyser/files/7267991/2021-10-01-15.log.gz)
[2021-10-01-2.log.gz](https://github.com/GeyserMC/Geyser/files/7267992/2021-10-01-2.log.gz)
[2021-10-01-3.log.gz](https://github.com/Geyser
[2021-10-01-1.log.gz](https://github.com/GeyserMC/Geyser/files/7268000/2021-10-01-1.log.gz)
[2021-10-01-9.log.gz](https://github.com/GeyserMC/Geyser/files/7268001/2021-10-01-9.log.gz)
[2021-10-01-11.log.gz](https://github.com/GeyserMC/Geyser/files/7268002/2021-10-01-11.log.gz)
[2021-10-01-14.log.gz](https://github.com/GeyserMC/Geyser/files/7268003/2021-10-01-14.log.gz)
MC/Geyser/files/7267993/2021-10-01-3.log.gz)
[2021-10-01-4.log.gz](https://github.com/GeyserMC/Geyser/files/7267994/2021-10-01-4.log.gz)
[2021-10-01-5.log.gz](https://github.com/GeyserMC/Geyser/files/7267995/2021-10-01-5.log.gz)
[2021-10-01-6.log.gz](https://github.com/GeyserMC/Geyser/files/7267996/2021-10-01-6.log.gz)
[2021-10-01-7.log.gz](https://github.com/GeyserMC/Geyser/files/7267997/2021-10-01-7.log.gz)

### To Reproduce

1.update a server running on 1.16.15 spigot paper build 134 to spigot 1.17.1 build 196
2.update geyser, floodgate, dynmap, craftbook, luckyperms, FAWE, FAWE vizualizer, gobsh, gopaint
3.connect with a bedrock acount
4.use your inventory for 30 to 60 sec
5.your game crashed without giving any reason

### Expected behaviour

I would like them to be able to use their inventory without having their game crashing everysingle time

### Geyser Dump

https://dump.geysermc.org/RJ9m1YbaTyT0b3TBDQZsRp4ZRBGyIDdi

### Geyser Version

"1.4.3-SNAPSHOT (git-master-50896a2)

### Minecraft: Bedrock Edition Version

1.17.3

### Additional Context

my friend had an update of bedrock to 1.17.30 just this morning before everything got stuck.
I tried to change the serv to 1.17.1 to try to let him connect but now everything seems to work until he opens his inventory

**Comment by Camotoy** [comment]
Have you temporarily tried with no plugins? We will fix the issue if it's a plugin conflict, but it's most helpful if we know if we need to debug this with a plugin.

**Comment by M4thy** [comment]
Oh no I'll deinstall them all right now

**Comment by M4thy** [comment]
can I just deactivate them all or do I need to get rid of them from the plugin folder ?

**Comment by Camotoy** [comment]
Just move them to another folder.

**Comment by Camotoy** [comment]
Just Floodgate and Geyser.

**Comment by M4thy** [comment]
ok i wait for my friend to try on bedrock  in a minute

**Comment by M4thy** [comment]
damned nothing changed the game crashed the same way : just after he opened his inventory

**Comment by M4thy** [comment]
https://dump.geysermc.org/3YcZOBZzjLmQIXRNukCPsme3xwARKlzs

**Comment by M4thy** [comment]
we tested a little bit more : he can stay connected as long as he does not open his inventory for too long. I can still give him block and he can build/destroy without having any crash, but as soon as he opens the inventory, his game closes and he gets disconnected from the server with "time_out" as a reason on the console

**Comment by Camotoy** [comment]
What gamemode is this in? Does it happen when they have an empty inventory?

**Comment by M4thy** [comment]
we were in creative, full i think
I'll ask him to test with other configurations

**Comment by M4thy** [comment]
hi again, so my friend just had the 1.17.32 update. btw I'm updating geyser and floodgate roght now !

anyway he is still  able to connect on the serv like yesterday, he can move, build, destroy and use the inventory in survival. However in creative, he can pick blocks from the creative inventory, dump blocks, and click on menus exept for the last one top left (the one with the ground and flower on the pic) : when he can click on that one after a sec the game still closes and sometimes also when my friend just uses the inventory for too long while in creative, the game closes too
!
[Capturebug_Minecraft](https://user-images.githubusercontent.com/91743364/135723686-6b43806c-0771-45f9-8eca-0bab2713ead8.png)
o.

**Comment by M4thy** [comment]
update : I updated geyser to Geyser version 1.4.3-SNAPSHOT (git-master-f1098a9) from today and the issue seems to be solved except for lags !

Idk what you guys have done but I'm really thankfull for everything !

**Comment by Camotoy** [comment]
Great to hear. Let us know if anything changes!
