### ISSUE TITLE
Invalid characters

### ISSUE THREAD

**Issue by KOT4N** [GeyserMC/Geyser#2560]
### Describe the bug

Floodgate.
When i join to server i see "Invalid characters in your nickname".
I remove prefix, allow . to this and it error anyway

### To Reproduce

Install floodgate
Connect

### Expected behaviour

Not kick

### Geyser Version

1.4.3-SNAPHOT

### Minecraft: Bedrock Edition Version

1.17.30

**Comment by Camotoy** [comment]
Most likely not our issue. Make sure you're saving your config; otherwise, talk to the login plugin's developers about supporting the `.` character.

**Comment by KOT4N** [comment]
i REMOVED prefix, i write about it
