### ISSUE TITLE
BE user cannot enter

### ISSUE THREAD

**Issue by eyesonme1212** [GeyserMC/Geyser#2561]
### Describe the bug

It worked fine until a few months ago, but I recently received a new version of the plug-in as an update to BE, but it seems that the folder cannot be created and users cannot access it.

And Flodgate used to have a bucket version, but recently changed to a spigot version, is there a problem with this?

### To Reproduce

After installing the 1.16.5 version bucket and geyser spigot version floodgate spigot version, check the connection

### Expected behaviour

Folder not created?

### Server Version and Plugins

1.16.5

### Geyser Version

Geyser-spigot.jar

**Comment by Chew** [comment]
Impossible to diagnose anything without a full latest.log. Please provide one.

It's _very_ likely you need Java 16 that you don't have, but just in case.
Make sure you download an updated Geyser JAR [here](https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/spigot/target/Geyser-Spigot.jar).
Make sure you download an updated Floodgate SPIGOT Jar [here](https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/lastSuccessfulBuild/artifact/spigot/target/floodgate-spigot.jar).

DELETE floodgate-bukkit.jar if you still have it.

Restart server, let it boot, send the log.

**Comment by eyesonme1212** [comment]
https://mclo.gs/YoiLftr

**Comment by Camotoy** [comment]
Yup, you need to update to Java 16 or run Geyser standalone on something running Java 16. If you need assistance with this, please join our Discord. Thank you!
