### ISSUE TITLE
Opening "Nature" tab in inventory crashes game.

### ISSUE THREAD

**Issue by Greaper88** [GeyserMC/Geyser#2564]
### Describe the bug

Opening the nature tab in a player's inventory can cause the game to crash, particularly if player enters the game in creative mode (in my initial testing anyways).

### To Reproduce

Join a server, open inventory, and select the "Nature" tab. Game freezes then closes.
If it does not happen, set the player's game mode to creative, then restart the game and try again, player should crash.

### Expected behaviour

Nature tab should open and display the items in the category, allowing the player to navigate and select the items.

### Screenshots / Videos

https://user-images.githubusercontent.com/61922763/135779096-60f6126a-83ba-496c-b377-2d4e44f434e5.mp4

### Server Version and Plugins

Server 1: Survival
Version
`This server is running CraftBukkit version 3242-Spigot-6c1c1b2-d3cc412 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)`
Plugins
`Plugins (27): CoreProtect, LuckPerms, SetHome, dynmap, AntiCreeper, OpenInv, ArmoredElytra, Trade, LoginMessage, SmoothSleep, dynmap-mobs, SimpleTpa, MultiChat, Minepacks, DiscordSRV, WeatherNews, TreeAssist, MinecartSpeedPlus, NBTAPI, AntiSwear, MobHeads, GriefPrevention, BloodInMinecraft, JDynmapGriefPrevention, ProtocolLib, Matrix, Orebfuscator`

Server 2: Creative
Version
`This server is running Tuinity version git-Tuinity-"f0e91a4" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
Plugins
`Plugins (18): AntiCreeper, AntiSwear*, BlocksHub, CoreProtect, DiscordSRV, dynmap*, dynmap-mobs*, dynmap-structures, GriefPrevention, JDynmapGriefPrevention*, LoginMessage*, LuckPerms, MinecartSpeedPlus*, MultiChat*, SetHome*, SimpleTpa, SmoothSleep, TreeAssist`

### Geyser Dump

https://dump.geysermc.org/Z7tmlubp2OZ9AdaKPhW8uIaGoD4oOlBK

### Geyser Version

1.4.3-SNAPSHOT (git-master-b58cbd0)

### Minecraft: Bedrock Edition Version

1.17.32, Win10

### Additional Context

In my own testing, accessing the menu in survival on a survival server first seemed to prevent the issue from occurring.

https://user-images.githubusercontent.com/61922763/135779443-2026ef04-9439-484e-922b-e780d616455a.mp4

**Comment by Camotoy** [comment]
Likely related to #2558 though that person's issue was spontaneously fixed.

**Comment by Greaper88** [comment]
well, at least here is something that seems consistent, to me at least.

**Comment by Camotoy** [comment]
I don't have further time to debug, but I was unable to confirm this with vanilla 1.17.1 as the backing server. *However*, I have a suspicion that it's related to a sculk block in some capacity - I wonder if enabling `extended-world-height` would "resolve" your issue.

**Comment by Greaper88** [comment]
> 
> 
> I don't have further time to debug, but I was unable to confirm this with vanilla 1.17.1 as the backing server and Android/iOS clients. _However_, I have a suspicion that it's related to a sculk block in some capacity - I wonder if enabling `extended-world-height` would "resolve" your issue.

It seems to have..... But That shouldn't have a bearing on that. And we don't have the ability to enable that option in the GC config (which is where i've gotten two reports of the same issue)

**Comment by Greaper88** [comment]
Also @Camotoy latest server jar downloaded directly from minecraft.net does i

https://user-images.githubusercontent.com/61922763/135781832-de4040e0-d67a-4403-b5a6-fdbf01dca9f8.mp4

t:

**Comment by Greaper88** [comment]
The accessing in survival mode first still applies though:

https://user-images.githubusercontent.com/61922763/135782379-e8aae3ef-b97f-42cb-9298-e45c6e544932.mp4

**Comment by Camotoy** [comment]
> But I wouldn't expect that to have a bearing on that

Welcome to Bedrock. xd

More seriously, the experimental toggle doesn't just affect the world height. I don't know the exact behavior in 1.17.30, but in 1.17.10 the sculk sensor could only be properly seen if the experimental toggle was enabled.

**Comment by Camotoy** [comment]
OK, after restarting the game (I missed this last night), I'm able to confirm.
