### ISSUE TITLE
bug about the shield

### ISSUE THREAD

**Issue by DJelly4K** [GeyserMC/Geyser#2566]
### Describe the bug

When mobile bedrock players use shields or view other people using shields, the shield animation cannot be displayed correctly, and it is normal on the Java version.
[Picture in the screenshot area]
So i think this bug is only on mobile

### To Reproduce

1. a PC player joins the game
2. On his platform(Java&Win10), the shield animation is displayed correctly
3. a mobile player joins the game
4. He cannot see the right shield animation

### Expected behaviour

the shield animation can be displayed correctly

### Screenshots / Videos

On Java:
![image](https://user-images.githubusercontent.com/68630033/135863370-3c7774a5-9a00-40a7-afb3-b24503894b78.png)
On Bedrock:
1.win10
![image](https://user-images.githubusercontent.com/68630033/135863567-b077f8c9-9549-4ee7-b38c-785021c6ac15.png)
2.android
![9J$XCNZ C SATB1QMLHRW6](https://user-images.githubusercontent.com/68630033/135864107-f3000c88-35b8-4efe-ae97-615f2e2d938c.jpg)
(the player jitang404's shield)

### Server Version and Plugins

Geyser-Bungeecord version: 1.4.3-SNAPSHOT（git-master-50896a2）
Bungeecord: FlameCord 0.6.3
Downstream server: Sugarcane build104 (Airplane, Paper)

### Geyser Dump

https://dump.geysermc.org/xXvUrsZQtaDjWyj3i9ekayhk8zcCCCoc

### Geyser Version

1.4.3-SNAPSHOT（git-master-50896a2）

### Minecraft: Bedrock Edition Version

1.17.32

### Additional Context

I used machine translation

**Comment by DJelly4K** [comment]
This problem will still occur if you remove any additional texture packs on the Android side

**Comment by Camotoy** [comment]
As far as we are aware, this is a Bedrock bug, so I'm closing this. Thank you anyway!
