### ISSUE TITLE
Cannot connect from Bedrock Edition

### ISSUE THREAD

**Issue by wencafe** [GeyserMC/Geyser#2567]
### Describe the bug

When I connect from Bedrock Edition (tried both 1.17.0 and 1.17.1), I am stuck on "Locating Server" with a red dot instead of the ping. Joining in this state results in "Unable to connect to world" error.

I can connect to the same server with Java account (same versions, upgraded and downgraded for testing) therefore nothing is wrong with the server provider or my internet connection.

I've been playing in the same server for months before suddenly encountering this issue. Console + Logs have no errors.

### To Reproduce

1) Open Minecraft Bedrock edition (1.17.0 or 1.17.1)
2) Click Play and then Servers
3) In Additional Servers, click any server and it will be stuck on "Locating server"

### Expected behaviour

I should be able to enter the server and play

### Screenshots / Videos

![Screenshot_2021-10-04-20-24-19-417_com mojang minecraftpe](https://user-images.githubusercontent.com/91896264/135870488-3af9a200-21cf-4a5c-89b2-a12edc20dffb.jpg)
![Screenshot_2021-10-04-20-10-01-334_com mojang minecraftpe](https://user-images.githubusercontent.com/91896264/135870528-f2935f87-dbab-4998-947c-662cbbca9199.jpg)

### Server Version and Plugins

1.17.1
bStats
Economy
Floodgate
Harbor
HomeSpawn
MoneyNote
PluginMetrics
Vault

### Geyser Dump

https://dump.geysermc.org/VW9VS9OVKFqDk5bQY1MivBlrJhdEqHTJ

### Geyser Version

893 (Bedrock v1.17.10 - v1.17.30)

### Minecraft: Bedrock Edition Version

1.17.1

**Comment by TheClassic36** [comment]
Your version of Geyser only supports Bedrock 1.17.10-1.17.30. That may be why you can't connect from 1.17.0 or 1.17.1 lol

**Comment by wencafe** [comment]
> Your version of Geyser only supports Bedrock 1.17.10-1.17.30. That may be why you can't connect from 1.17.0 or 1.17.1 lol

i see! if joining on 1.17.0 fails then 1.17.1 must work right? since it supports from that to 1.17.3? sorry if i'm misunderstanding something

**Comment by Chew** [comment]
I think you confuse Java and Bedrock versions, both of y'all at least. Either way, please hop on our [Discord Server](https://discord.gg/geysermc) for assistance with this. Thank you!
