### ISSUE TITLE
StackOverflow error when booting Geyser Bungeecord

### ISSUE THREAD

**Issue by Carbuino** [GeyserMC/Geyser#2568]
### Describe the bug

When booting up with the latest version of Waterfall, Geyser will begin to load and then send a StackOverflow error to the console.

### To Reproduce

1. Run the waterfall.jar file
2. Geyser will output the StackOverflow error
3. Server boots without Geyser active.

### Expected behaviour

1. Run the waterfall.jar file
2. Server boots up without error

### Screenshots / Videos

Server Log: https://hastebin.com/ovudiroxun

### Server Version and Plugins

Waterfall (PaperMC) Build #450
BungeeResourcePacks version 1.8.5.1
BungeeTabListPlus version 3.4.4
Floodgate version 2.0 (unsure which exact build)
LuckPerms-Bungee version 5.3.65
SkinsRestorer version 14.1.3
VentureChat version 3.1.3

### Geyser Version

Geyser version 1.4.3-SNAPSHOT (git-master-175d9af)

### Additional Context

Server running on Manjaro KDE-Plasma (Arch-Linux) version 21.1.4
Running 16 GB of DDR3
Intel Core i5-3570k
Geforce GT 730

**Comment by Camotoy** [comment]
I'm unable to replicate this with Waterfall 450 and the latest Geyser. Does this happen with a specific plugin installed, perhaps?

**Comment by Carbuino** [comment]
As far as I can tell it might be the OS, I redownloaded both of them and the error still appears. Could my Java install be corrupt?

**Comment by Camotoy** [comment]
Have you tried without any other plugins temporarily just to see if Geyser boots?

**Comment by Carbuino** [comment]
I have and Geyser is the only one that shoots an error. Just to be sure, I also double-checked my Paper servers as well, nothing was erroring out there either. It only seems to be Geyser on the Proxy side that's erroring out.

**Comment by Camotoy** [comment]
(Geyser shouldn't be on the Paper servers, just as a heads-up)

**Comment by Xernium** [comment]
Please provide a complete set of information about your JVM.
You can obtain that by executing `java -version` (or `java --version`) in the **same** execution environment you're running the server in.

**Comment by Camotoy** [comment]
We should have a new build - does it persist by uploading a new jar file?
