### ISSUE TITLE
Geyser through Termux

### ISSUE THREAD

**Issue by PadMadoff** [GeyserMC/Geyser#2572]
### Describe the bug

After version 1.17, I, and not only I, now do not know how to launch a geyser on an android with a new version of Java. Looked at wiki and setup, didn't help.

### To Reproduce

1. Go to android.
2. Install Termux or UserLand.
3. Download java and Geyser.
4. Run Geyser.
5. Done.

### Expected behaviour

I thought that the termux or userland are already using the new version of Java.

### Geyser Version

Latest (I don't know where to see the version.)

### Minecraft: Bedrock Edition Version

1.17.30.04

**Comment by byquanton** [comment]
Try using `update-alternatives --config java` to change the default Java Version.

**Comment by byquanton** [comment]
Can you check the output of `java --version`

**Comment by jackson-57** [comment]
You can install Java 17 by using `apt install openjdk-17`

**Comment by Chew** [comment]
If termux doesn't support Java 16 or above, there's not much we can do. Unless there's a legitimate issue with running it through there, we'll have to close this issue. Thank you!
