### ISSUE TITLE
Crafting glitch

### ISSUE THREAD

**Issue by DJelly4K** [GeyserMC/Geyser#2576]
### Describe the bug

When crafting items, it sometimes glitching (e.g. items placed on the columns getting switched by another item in a player inventory)
like #2350 #2462 #2474 #2483 
I tried the methods in the comments section of these issues, but still no effect
Hope it can be fixed soon

### To Reproduce

Just crafting any item on a crafting table and place the ingredients onto the columns

### Expected behaviour

No item switching glitches/player can craft normally without any item they placed getting switched with a random item in their inventory

### Screenshots / Videos

https://user-images.githubusercontent.com/68630033/137014236-f8d3a9dc-262a-4744-9cf1-e2283beec37f.mp4

### Geyser Dump

https://dump.geysermc.org/qw6q9J0JtDq01PHvJ8SwU9HCkBE1E0T1

### Geyser Version

1.4.3-SNAPSHOT (git-master-265c42f)

### Minecraft: Bedrock Edition Version

1.17.34

### Additional Context

I used machine translation and some texts from #2350 (im too lazy)

**Comment by DJelly4K** [comment]
em

**Comment by Camotoy** [comment]
Can you re-test with the latest Geyser version?

**Comment by DJelly4K** [comment]
> Can you re-test with the latest Geyser version?

works great, thanks :) (this old bug is finally fixed xd)
