### ISSUE TITLE
1.17.1 | No Proxy | Spigot | Index out of bounds error 

### ISSUE THREAD

**Issue by EnderGamingFilms** [GeyserMC/Geyser#2577]
### Describe the bug

When a bedrock player joins there is an error in the console during the `ServerWindowItemsPacket`

### To Reproduce

1.17.1 Spigot Plugin on tunity platform. Floodgate and geyser are install on the unity server.are installed

### Expected behaviour

N/a

### Screenshots / Videos

N/a

### Server Version and Plugins

Version: git-Purpur-1400 (MC: 1.17.1)
System: Linux
Java: 16.0.2
Plugins: MiniMOTD v2.0.4, LuckPerms v5.3.55, LunarClient-API v1.0.1, PlaceholderAPI v2.10.10, spark v1.6.1, ProtocolLib v4.7.0, EnderLibs v0.2.1, ItemBridge v3.0.1, NashornPlus v1.1.0, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, floodgate v2.0-SNAPSHOT, DailyRewards v1.1.0, SolarisAdditions v1.4, BKCommonLib v1.17.1-v3, MyPronoun v0.2.2, HeadDatabase v4.14.1, Multiverse-Core v4.3.0-b846, TrMenu v3.0-RC-2, Recycler v1.2, FastAsyncWorldEdit v1.17-208;dc11b74, TradeSystem v2.0.6, ajLeaderboards v1.3.1, TAB v2.9.2, Geyser-Spigot v1.4.3-SNAPSHOT, GlobalMarketChest v1.10.1, WorldBorder v2.1.4, LevelledMobs v3.1.8 b517, ChatControlRed v10.6.4, AdvancedEnchantments v8.7.0, MoneyFromMobs v4.3, CMILib v1.0.3.11, SpecializedCrates v2.23.5, CMI v9.0.4.5, UltimateClaims v1.8.0, WorldGuard v7.0.5+3827266, Citizens v2.0.28-SNAPSHOT (build 2357), mcMMO v2.1.202-SNAPSHOT, PvPManager v3.14.12

### Geyser Dump

https://dump.geysermc.org/g08I7SP2Nf8fm960MezDJIirUW4dCrVA

### Geyser Version

1.4.3-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.34

### Additional Context

https://paste.helpch.at/vujibomiyu.pl

**Comment by Camotoy** [comment]
This should now be addressed.
