### ISSUE TITLE
Server spits out error log when someone tries to join.

### ISSUE THREAD

**Issue by ZellorNox97** [GeyserMC/Geyser#2579]
### Describe the bug

Okay, so, the server works fine for about 2 days, and then all of the sudden it spits out a string of errors and kicks anyone who tries to join, spitting out the error string again. i don't know what is causing it. i'm running a 1.17.1 server with geyser, floodgate, and discord SRV plugins, on a Mineos VM on my proxmox server, but it's done this on other setups too
[error.txt](https://github.com/GeyserMC/Geyser/files/7360445/error.txt)

### To Reproduce

1. plugins are discord srv, floodgate, and geyser
2. running the server from a mineos VM on proxmox

### Expected behaviour

for the server to run properly

### Server Version and Plugins

[16:54:10] [Thread-26/INFO]: This server is running Paper version git-Paper-329 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 5344798)
--
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads

Plugins are Discord SRV, Geyser, and floodgate

### Geyser Dump

https://dump.geysermc.org/s5BVomUTRY8Q5UNTRO3T8DVRMlK8oHJ5

### Geyser Version

Geyser-Spigot latest

### Minecraft: Bedrock Edition Version

1.17.1

**Comment by Camotoy** [comment]
I'm definitely skeptical here because the error you posted has nothing to do with Geyser or Floodgate.

**Comment by ZellorNox97** [comment]
Well, i've also tried running it without geyser, and it runs fine, and i've also tried running it without discord SRV or any other plugins and JUST geyser and floodgate, and this happens. the only time i get this issue is with geyser and floodgate installed

**Comment by Camotoy** [comment]
The exact same error? Maybe post them all here and see if they're the same or not. I'd also try without MineOS, if possible, and also using Geyser standalone which would isolate Floodgate as a possible issue.

**Comment by ZellorNox97** [comment]
I didn't save the error logs from the previous servers and i don't have those machines set up, but yeah, pretty much the same error string. i'll give running it without floodgate, but floodgate is what allows my console friends to play.

**Comment by Camotoy** [comment]
No - I mean just run Floodgate on the Paper server and run Geyser separately as standalone. See our wiki for a setup guide,

**Comment by ZellorNox97** [comment]
i'm trying to follow the geyser standalone tutorial but it's not working, just getting errors

**Comment by Jens-Co** [comment]
Since no more information was provided ill close this issue. If you are still having trouble please provide us with the info we asked. Ill close this for now.
