### ISSUE TITLE
Shields are broken and appear inside player

### ISSUE THREAD

**Issue by Armoured0** [GeyserMC/Geyser#2584]
### Describe the bug

On a bedrock client if a shield is used it appears as if it is inside the player. I have a video of this bug however this is not my own video:
https://www.youtube.com/watch?v=H6ICDzLllhs

Any help would be great. Thanks!

### To Reproduce

Join a Geyser server with a bedrock and java player.
Use shield in front of bedrock player as java player.
It does not seem to happen on PC bedrock only all console/android

### Expected behaviour

The shield will appear as if it is inside the player.

### Screenshots / Videos

https://www.youtube.com/watch?v=H6ICDzLllhs

### Geyser Version

Geyser-Spigot Build #903

### Minecraft: Bedrock Edition Version

1.17.34

**Comment by TheMonBonGH** [comment]
This has always been a client sided visual bug, and not Geyser.
