### ISSUE TITLE
Rain problem on Bedrock

### ISSUE THREAD

**Issue by vitorgueler22** [GeyserMC/Geyser#2588]
### Describe the bug

There's a problem with rain on Bedrock edition, I'll try to explain the best as I can. So, sometimes it starts raining only on Bedrock, on Java the weather is clear. And when it starts raining on Bedrock, I can't seem to clear the weather even with commands, the rain just don't go away... I try to rejoin the server,  the rain stops, but starts raining again after a minute or so and goes on forever... 

### To Reproduce

1. Join the server;
2. Start raining only on Bedrock;
3. Rain doesn't go away no matter what I do. 

### Expected behaviour

Sync Java and Bedrock weather, mainly for rain. 

### Server Version and Plugins

Server: PaperMC #345

Plugins: EssentialsX, Multiverse Core, Multiverse Portals, Multiverse Inventories, CoreProtect, WorldEdit, World Guard, Geyser and Floodgate.

### Geyser Version

1.4.3 Snapshot

### Minecraft: Bedrock Edition Version

1.17.40

### Additional Context

I saw you guys fixed thunder and lightning sounds after I reported, thank you so much for the support. This issue with rain seems to be a bit more complex, but I hope you can fix that.

**Comment by Camotoy** [comment]
Possibly related: https://bugs.mojang.com/browse/MCPE-131325

**Comment by Sammster10** [comment]
Here is a similar issue that shows rain on bedrock, here is how to reproduce it:

Create a world with the biome "the_void" then teleport a bedrock user into that world. Once they have been teleported in, it should show rain for the bedrock player even if it is not raining.

**Comment by Landy005** [comment]
have this issue aswell! We do /pweather clear or sun to get rid of it, but eventually it'll come back. My serer has alwaysday so for java players itll never rain.

**Comment by creativegamer03** [comment]
I have this issue too.
Java = clear weather
Bedrock = raining
DynMap reports it sunny, not rainy.
![image](https://user-images.githubusercontent.com/66676126/160830453-07826086-4b93-40aa-9681-a5994dfb3d90.png)

**Comment by HitaloSama** [comment]
I am also having this same problem, I use some plug-ins besides Geyser with PaperMC.

```
Plugins (12): AuthMe, CoreProtect, Essentials, floodgate, Geyser-Spigot, GeyserUpdater, GriefPrevention, Harbor, LuckPerms, ProtocolLib, SkinsRestorer, Vault
```

**Comment by HitaloSama** [comment]
> Possibly related: https://bugs.mojang.com/browse/MCPE-131325

Apparently that's exactly the problem I'm having. 🤔

**Comment by Konicai** [comment]
Does this still occur?

**Comment by lee3kfc** [comment]
I got same issue on paper-1.19.2-307.jar with Geyser-Spigot1255/floodgate-spigot73

**Comment by valaphee** [comment]
Geyser doesn't reset the weather when switching servers, it is only done when respawning, and Minecraft still has the bug where it randomly starts to rain, which is the reason why I always reset the weather on respawn and start game packet.

**Comment by 7Wdev** [comment]
Yea am facing the same issue, the rain is not synced between java and bedrock clients,
like when it rains in java it doesn't in bedrock

![image](https://user-images.githubusercontent.com/45117834/216358460-3ebdf442-0180-4002-8d9e-15249ff51cb1.png)

even when I type
/weather rain
it sets it to sun

![image](https://user-images.githubusercontent.com/45117834/216358611-d942f0ff-770a-457c-85ee-6772769fd964.png)

bedrock understands it and recieves it as sun
![image](https://user-images.githubusercontent.com/45117834/216358669-9c786198-299c-4f1f-ab82-0253f87f522c.png)

**Comment by agoniaprivat** [comment]
This is still a issue for me.
Should I open a new report?

Running Geyser on Java 1.20.1 server.

**Comment by Konicai** [comment]
Please check if #3679 encompasses your issue
