### ISSUE TITLE
Double doors sometimes cause rubber banding

### ISSUE THREAD

**Issue by SmearyThrower** [GeyserMC/Geyser#2589]
### Describe the bug

Sometimes double doors will rubber band players trying passthru them even tho the server is at a stable 20 tps

### To Reproduce

Place  2 doors and keep walking thru them after a while you will notice that sometimes you get rubber banded back after 1 to 2 seconds

### Expected behaviour

The doors should be able to let entities pass

### Screenshots / Videos

Video 1 https://drive.google.com/file/d/18MlwIY1B0Sjd_WnsKVeXK3XVqSfFjgB8/view?usp=drivesdk

Video 2
https://drive.google.com/file/d/193NcbqxnI1hpRaBK_BoV9mRE90DfZ6kE/view?usp=drivesdk

### Server Version and Plugins

Paper version git-Paper-349 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9472d38)

Plugins (16): CMILib, CoreProtect, EconomyShopGUI, Essentials, EssentialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, Graves, Jobs, LuckPerms, OldCombatMechanics, spark, Vault, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/ynJggMewRSUxgzhBDflnL7DQtoUxuyHc

### Geyser Version

Geyser version 1.4.3-SNAPSHOT (git-master-a7aa255)

### Minecraft: Bedrock Edition Version

1.17.40

### Additional Context

The bug became very noticeable after updating to 1.17.1 from 1.16.5 a month ago even after updating all plugins this bug still occurs

**Comment by kalizec** [comment]
I'm seeing a similar issue with GeyserMC. Though to me it appears not to be rubber banding, but the Bedrock client thinking it opened the door, while if you look from a JAVA client, then you see the door is actually still closed. Hence the Bedrock client rubber bands back, as the door isn't actually open according to the JAVA server.

**Comment by kalizec** [comment]
> I'm seeing a similar issue with GeyserMC. Though to me it appears not to be rubber banding, but the Bedrock client thinking it opened the door, while if you look from a JAVA client, then you see the door is actually still closed. Hence the Bedrock client rubber bands back, as the door isn't actually open according to the JAVA server.
> 
> I'm seeing this on Spigot 1.18.1 together with the Geyser Spigot plugin.

Did some further testing and it's not related to Geyser. Sorry for any confusion.

**Comment by RednedEpic** [comment]
Stated as unrelated to Geyser. Please open a new issue if this still occurs & there is an indication Geyser is at fault.
