### ISSUE TITLE
Player seems not to sleep on bedrock (but actually sleeping)

### ISSUE THREAD

**Issue by JuniorJPDJ** [GeyserMC/Geyser#259]
**Describe the bug**
When you click on bed playing on bedrock you are really sleeping, but bedrock client doesn't seem to know that - you are still standing near bed.

**To Reproduce**
1. Try to click on bed on bedrock at night.
2. It will look like sleeping is not working.
3. You are actually in this bed.

**Expected behavior**
See bed POV.

**Screenshots**
Java edition 3rd person:
![2020-04-01_01 49 34](https://user-images.githubusercontent.com/7334549/78085519-807d5f00-73bb-11ea-9a61-35bfcb9da8b6.png)
Bedrock 1st person:
![Screenshot_20200401-014923_BlockLauncher](https://user-images.githubusercontent.com/7334549/78085544-8ecb7b00-73bb-11ea-8d64-8f637e1ca087.png)
On screenshot you also can see some invisible beds, which is not nice ;/

**Server version**
Latest papermc

**Geyser version**
Latest jenkins inventory branch

**Bedrock version**
BlockLauncher patched 1.14.1 android arm (also bugs on other).

**Comment by DoctorMacc** [comment]
@JuniorJPDJ Could you compile this version of the inventory branch: https://github.com/GeyserMC/Geyser/tree/c21672e5ebf19358a2ad78b0ab50155489a8f23c and see if the problems with beds disappearing still persists?

**Comment by JuniorJPDJ** [comment]
Uh, sorry @DoctorMacc, I've not seen your message.
Now I see your pull was merged to inventory branch, I'll just test new version.

**Comment by JuniorJPDJ** [comment]
Sorry, no tests possible - latest version doesn't even start (bukkit plugin)

**Comment by JuniorJPDJ** [comment]
On latest build from CI beds are visible :)
(I probably ducked up my own build?)

**Comment by DoctorMacc** [comment]
Good to hear!
