### ISSUE TITLE
Recent fix is causing scoreboards to be invisible

### ISSUE THREAD

**Issue by chrismwiggs** [GeyserMC/Geyser#2590]
### Describe the bug

The latest fix for scoreboards (https://github.com/GeyserMC/Geyser/commit/9a159bf8be2111d30b95b73331369f04c7ed006b) is causing my scoreboards to actually go invisible. I've confirmed by building a copy of geyser with this commit and one without; the build without works as expected. 

### To Reproduce

Exclude this commit, build and run Geyser (standalone, 1.17)

### Expected behaviour

Score board should be there

### Server Version and Plugins

This server is running Purpur version git-Purpur-1345 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4e03b8f on ver/1.17.1)

### Geyser Version

N/A, Self building based on git repo

**Comment by chrismwiggs** [comment]
Scoreboard.dat: https://cdn.discordapp.com/attachments/718515358214127659/901632596155453490/scoreboard.dat

The plugin is Projectkorra, with the Jedcore addon. https://www.spigotmc.org/resources/projectkorra-core.2734/ And jedcore: https://github.com/plushmonkey/JedCore

**Comment by MrRazamataz** [comment]
My scoreboard randomly disappears and doesn't reappear until you restart geyser. 
I'm using geyser bungeecord
```
This server is running Geyser version 1.4.3-SNAPSHOT (git-master-1316f6e) (Java: 1.17.1, Bedrock: 1.17.10/1.17.11 - 1.17.40)
```

**Comment by Camotoy** [comment]
Can you update to the most recent build?

**Comment by MrRazamataz** [comment]
I have done so, Ill let you know of any issues.

**Comment by chrismwiggs** [comment]
Appears to be working fine in most recent builds, at least for me now!
