### ISSUE TITLE
Virtual guis/inventorys occasionally dont remove the virtual block

### ISSUE THREAD

**Issue by SmearyThrower** [GeyserMC/Geyser#2593]
### Describe the bug

After opening multiple chests or any block with a gui few of the virtual blocks dont get terminated unless they are interacted by the player

### To Reproduce

Place a lots of chest or any block with a gui

Keep switching chests 

After a while you will notice a lot of virtual blocks that wont go away till you interact with them

### Expected behaviour

After closing the block the virtual block should vanish in less then a second

### Screenshots / Videos

With chests - https://drive.google.com/file/d/198WELhlBlrfqJUeOPOdddljnjPx9mtds/view?usp=drivesdk

With furnace - https://drive.google.com/file/d/19C3H8cno7swi5vnJ1jT5GTuEp-B4wlIq/view?usp=drivesdk

### Server Version and Plugins

Paper version git-Paper-349 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9472d38)

Plugins (16): CMILib, CoreProtect, EconomyShopGUI, Essentials, EssentialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, Graves, Jobs, LuckPerms, OldCombatMechanics, spark, Vault, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/ynJggMewRSUxgzhBDflnL7DQtoUxuyHc

### Geyser Version

Geyser version 1.4.3-SNAPSHOT (git-master-a7aa255)

### Minecraft: Bedrock Edition Version

1.17.40

### Additional Context

The server was at a constant 20 tps

**Comment by SmearyThrower** [comment]
> I thought this was normal..?

Its normal for there to be a virtual inventory while you interact with the block but its somtimes bugs out and forgets to remove the virtual block

**Comment by onebeastchris** [comment]
Unable to replicate - if you still face this issue, comment with a Geyser dump here.
