### ISSUE TITLE
/geyser advancements incompatible with AdvancedAchievements

### ISSUE THREAD

**Issue by Shodwriter** [GeyserMC/Geyser#2594]
### Describe the bug

If I attempt to run the command /geyser advancements on bedrock, the GUI for Java advancements appears, but clicking on one of the options does nothing and the GUI disappears.

### To Reproduce

Run the command /geyser advancements on bedrock with GeyserMC 1.4.3-SNAPSHOT with a datapack called Blazeand Cave's Advancements pack (plugin link [here](https://www.curseforge.com/minecraft/customization/blazeandcaves-advancements-pack), but when I disable this datapack, the command still doesn't work, so I'm not sure what the issue is)(although this problem still occurred even with an older version of GeyserMC (I can't remember the version, it's the one that only supports bedrock clients up to 1.17.30) and an older bedrock client (1.17.30)

### Expected behaviour

Clicking on one of the buttons when running /geyser advancements should display advancements

### Geyser Dump

https://dump.geysermc.org/WnJHbeaXvYEopit1GEumN1PEfRkfEfXq

### Geyser Version

1.4.3-SNAPSHOT (git-master-9a159bf)

### Minecraft: Bedrock Edition Version

1.17.40

**Comment by Konicai** [comment]
Does removing AdvancedAchievements stop this from happening?

**Comment by Shodwriter** [comment]
> Does removing AdvancedAchievements stop this from happening?

Yes it does, thanks for stating this.

**Comment by onebeastchris** [comment]
Using 1.20.4 fabric, and the latest version of Geyser and the Blazeand Cave's Advancements pack works just fine here.
@Shodwriter can you update Geyser and see if the issue persists?

**Comment by Konicai** [comment]
This is an old boy - it can be reopened if needed
