### ISSUE TITLE
Shields dont auto rearm after hit while sneaking

### ISSUE THREAD

**Issue by SmearyThrower** [GeyserMC/Geyser#2595]
### Describe the bug

When shield is armed if the player clicks any thing thats not a entity the shield dosent auto rearm even if the player is still sneaking. this makes pvp or pve with shield on mobile difficult since unlike on pc where players can hold right click to block on mobile we can only block with sneak

### To Reproduce

Equip a shield and sneak

Click anything thats not a entity 

Shields dont auto rearm

### Expected behaviour

The shield should auto rearm on bedrock like on vanilla singleplayer

### Screenshots / Videos

The bug - https://drive.google.com/file/d/19QkC0Ch6rmfn6y2umHW_prM1L_Q0paBO/view?usp=drivesdk

How it should work - https://drive.google.com/file/d/19Y9zeSbQEEhf6HYvaEZkD9-tzsPgu3aK/view?usp=drivesdk

### Server Version and Plugins

Paper version git-Paper-349 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9472d38)

Plugins (16): CMILib, CoreProtect, EconomyShopGUI, Essentials, EssentialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, Graves, Jobs, LuckPerms, OldCombatMechanics, spark, Vault, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/ynJggMewRSUxgzhBDflnL7DQtoUxuyHc

### Geyser Version

Geyser version 1.4.3-SNAPSHOT (git-master-a7aa255)

### Minecraft: Bedrock Edition Version

1.17.40

### Additional Context

I tested it without OldCombatMechanics and the bug still happens

**Comment by RednedEpic** [comment]
Mechanics have been updated to follow vanilla Bedrock. Please open a new issue w/ updated repro steps if this still occurs.
