### ISSUE TITLE
Boats Vanish on Dismount [Bedrock]

### ISSUE THREAD

**Issue by BerryGooot** [GeyserMC/Geyser#2605]
### Describe the bug

When a Bedrock player dismounts a boat (crouch or jump) the boat disappears completely. It cannot be interacted with but the hitbox is still there, albeit buggy.

### To Reproduce

1. Place and ride a boat in Bedrock Edition
2. Exit the boat
3. Boat is gone
(Jump on boat's previous location to see hitbox)

### Expected behaviour

Boat stays put until player returns to continue riding it.

### Screenshots / Videos

https://streamable.com/9on3sb

### Server Version and Plugins

1.17.1
Geyser-Spigot
floodgate
Graves

### Geyser Dump

https://dump.geysermc.org/d4AVROKLDlfPnREIZIOyinBrxHOfOamh

### Geyser Version

1.4.3-SNAPSHOT (git-master-9de26f2)

### Minecraft: Bedrock Edition Version

1.17.41

### Additional Context

Bug found in Nintendo Switch edition using BedrockConnect.
Boat reappears on relog.
Server hosted by PebbleHost.

**Comment by awesomemax43** [comment]
I've experienced this same issue twice in a row now (Vanilla Bedrock on PC)

**Comment by tomrhollis** [comment]
This is a known bug in the Bedrock client itself that is supposed to be fixed in 1.18. It can happen without Geyser

**Comment by edelBCS** [comment]
This is still an issue in 1.18 Bedrock, just experienced it twice in a row

**Comment by afischer321** [comment]
> drock, just experien

Same here. Happens nearly every time, very annoying.  Exiting and re-entering the game seems to bring it back, or walking out of render distance of the boat and coming back after a while (haven't determined how long yet) seems to bring it back.  I saw a suggestion that fiddling with the render distance while still in the game can bring it back as well.

**Comment by afischer321** [comment]
> This is a known bug in the Bedrock client itself that is supposed to be fixed in 1.18. It can happen without Geyser

Unfortunately this isn't fixed in 1.18.

**Comment by tomrhollis** [comment]
> 

Yeah it's unfortunate they didn't get the fix in with 1.18. Seems to be worse now even. But it's still happening without Geyser so nothing for them to do here

**Comment by keltinuous** [comment]
Just happened to my daughter and I playing 1.18 Bedrock on Realms. I could see and interact with her boat and she could do the same with mine, but we were unable to see or break our own boats. Just switched boats, but strange.

Survival, cheats enabled (boats were cheated in), no other weirdness though.

**Comment by RednedEpic** [comment]
Seems to be a Bedrock bug; likely not much we can do here unfortunately. Closing.
