### ISSUE TITLE
1.8 support

### ISSUE THREAD

**Issue by ScoppyTech** [GeyserMC/Geyser#2607]
### What feature do you want to see added?

i want the feature of geyser can work on 1.8 and newer

### Are there any alternatives?

trying to add the plugin to bungeecord and all spigot server

**Comment by BlAnKcOd3** [comment]
Geyser only supports the latest java version. With viaversion, it allows from 1.12.2 to 1.17 with viaversion and Java runtime 16 and above. 1.8 is an really old version of minecraft. There are some options however. Either use standalone or update your server and added old combat mechanics.

**Comment by Jens-Co** [comment]
![7F485392-419F-4435-956F-C0AF3727AB41](https://user-images.githubusercontent.com/63231928/139643469-666c310b-9f71-4009-901c-20f2011e45f6.jpeg)

1.8 servers should work on your setup. 
you should join our discord (https://discord.gg/geysermc) if you need help setting up Geyser.

**Comment by Chew** [comment]
You mentioned bungeecord which, as mentioned above, is supported. You do NOT install Geyser on the sub-servers, ONLY the proxy. In this case, you are fine.
