### ISSUE TITLE
Players using bows do not have animation

### ISSUE THREAD

**Issue by Seamusmario** [GeyserMC/Geyser#261]
**Describe the bug**
Players in servers using the bow does not show "aiming" animation

**To Reproduce**
1. Make  a player use the bow
2. Look in bedrock
3. See no animation

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/33694155/78280254-ca169880-74e6-11ea-9a6a-a7bc120112e1.png)

**Server version**
Spigot 1.8.8

**Geyser version**
Chunks fix

**Bedrock version**
1.14.20

**Comment by rtm516** [comment]
This also happens with mobs such as skeletons using a bow.

**Comment by Dummiesman** [comment]
bows seem to not be working on build # 197

**Server Version**
CraftBukkit version git-Spigot-2040c4c-77fd87e (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Minecraft: Bedrock Edition Version**
v1.14.60

**Comment by Arktisfox** [comment]
bows seem to not be working on build # 197

**Server Version**
CraftBukkit version git-Spigot-2040c4c-77fd87e (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Minecraft: Bedrock Edition Version**
v1.14.60
