### ISSUE TITLE
Lag when i join in bedrock

### ISSUE THREAD

**Issue by ches7lancero** [GeyserMC/Geyser#2612]
### Describe the bug

Hi when i play on bedrock on mobile it just lags, idk why but can someone pls tell me the solution for this or else i will have to discontinue the support for bedrock :(

### To Reproduce

idk

### Expected behaviour

Yeah it just randomly lags

### Geyser Version

On the latest version

### Minecraft: Bedrock Edition Version

1.17.41

**Comment by Konicai** [comment]
Hi, please edit your post to contain the information asked (geyser dump, device information).
