### ISSUE TITLE
Locator map BUG

### ISSUE THREAD

**Issue by huanshentianling** [GeyserMC/Geyser#2617]
### Describe the bug

Cannot use and make empty locator maps (even if they are not empty)
For the BUG encountered in the game, the console did not report an error.

### To Reproduce

1:
First, after the JAVA server installs Geyser
2:
Android version enters the game to switch and create.
3:
Find the locator map
4:
Then you can drag
5:
But you can't really take it out, and you can't make it.

### Expected behaviour

I hope to be able to use and make the locator map normally.

### Screenshots / Videos

https://fantasymagicalart.files.wordpress.com/2021/11/wp-1636204220404.mp4

### Geyser Version

https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/924/

### Minecraft: Bedrock Edition Version

1.16.220/1.17.41

**Comment by huanshentianling** [comment]
Recorded video

https://fantasymagicalart.files.wordpress.com/2021/11/wp-1636204220404.mp4

**Comment by huanshentianling** [comment]
> ### Describe the bug
> 
> Cannot use and make empty locator maps (even if they are not empty)
> For the BUG encountered in the game, the console did not report an error.
> 
> ### To Reproduce
> 
> 1:
> First, after the JAVA server installs Geyser
> 2:
> Android version enters the game to switch and create.
> 3:
> Find the locator map
> 4:
> Then you can drag
> 5:
> But you can't really take it out, and you can't make it.
> 
> ### Expected behaviour
> 
> I hope to be able to use and make the locator map normally.
> 
> ### Screenshots / Videos
> 
> https://fantasymagicalart.files.wordpress.com/2021/11/wp-1636204220404.mp4
> 
> ### Server Version and Plugins
> 
> _No response_
> 
> ### Geyser Dump
> 
> _No response_
> 
> ### Geyser Version
> 
> https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/924/
> 
> ### Minecraft: Bedrock Edition Version
> 
> 1.16.220/1.17.41
> 
> ### Additional Context
> 
> _No response_

This bug also exists

**Comment by rtm516** [comment]
Quick video and the error message from console

> `[12:11:41 INFO]: [Geyser-Spigot] Missing mapping for bedrock item 515:2`

https://user-images.githubusercontent.com/5401186/158017491-0c11baae-7ea5-40d9-a711-f9b9a52ae1f7.mp4

`

**Comment by rtm516** [comment]
@huanshentianling This is all because in Java edition there is only one type of map which is the equivalent of a locator map so until something is implemented to make this more user friendly I suggest using a normal map

**Comment by huanshentianling** [comment]
> 

I think I can try the recommended method, thank you for your help and recommendation.
