### ISSUE TITLE
Game Pass Java Account not accepted

### ISSUE THREAD

**Issue by RookiePaw** [GeyserMC/Geyser#2618]
### Describe the bug

I've owned Game Pass for a few weeks. Game Pass is the only way I own Java Edition. When Java Edition release to Game Pass on November 2nd, I was able to use what I like to call the "Geyser Gateway" (us.geyserconnect.net) to connect to Java servers, both on mobile and on PS4 (using MC Server Connector).

Yesterday and today, however, I wasn't able to use the same credentials to join the same server, as well as a few others to test if something was wrong. Still, I was not able to connect, being met with the message along the lines of "this server required a paid Java account". 

I've tried signing in with Microsoft account through a web browser and through my Microsoft details in the "Gateway" itself; both denied me access with that same message.

### To Reproduce

1. Have an active Game Pass membership.
2. Open Minecraft Bedrock Edition. Be sure you're signed into your Microsodt account and able to play publicly. 
3. Navigate to Play>Servers>Add server. Enter the IP "us.geyserconnect.net" or just "geyserconnect.net". Set the port to "19132", if it is not already there. Press Play.
4. Once connected to the "Geyser Gateway", Tap Submit>Custom Server>Edit Servers>Add Server. Use a Java Edition server's IP and Port, leave other toggles as they are. For example, I tried IP "mcsl.tulipsurvival.com", port 25565. Press Sumbit, then navigate backward to the "Custom server" list. 
5. Locate the server you've added, and tap it to reach the login window. Sign in with a Microsoft account, either through a web browser or by using your credentials, using the same account details as your Game Pass account.
6. Tap the login/sumbit button.

### Expected behaviour

After a few seconds (depending on your internet) you'll be met with a screen saying that you must use a paid Java Edition account.

What should happen is that you should be relocated to the intended server, and arrive as though you joined on the Java Edition platform.

### Geyser Version

Whichever the "geyserconnect.net" server uses.

### Minecraft: Bedrock Edition Version

1.17.41

**Comment by MrZomka** [comment]
GeyserConnect.net is an unofficial project. Please try and host your own Geyser instance and see if the issue would be there.

**Comment by Chew** [comment]
To my knowledge, game pass accounts aren't, "premium." I've played the game through Java via game pass and it doesn't say I own the game, yet the account does indeed exist and I can play.

Can you ensure you've booted the Java version of the game at least once? That is, downloading the launcher, selecting Java, clicking play, entering a username, clicking confirm, then logging into a server, such as `test.geysermc.org`
