### ISSUE TITLE
Migrated Accounts Doesn’t Work

### ISSUE THREAD

**Issue by AdzKoz** [GeyserMC/Geyser#2620]
### Describe the bug

I have recently got back into minecraft servers and i use geyser to connect my servers with my phone and switch! When getting back in, updating all my server and geyser to 1.17.1 (must be a issue with previous versions too), when signing into my Mojang account, it will kick me and will say “migrated”

in the server console, it will give me this message

`[Geyser-Spigot] <Microsoft Name> has disconnected from remote Java server on address <ip> because of CLOSED_BY_REMOTE_PEER`

Then i logged into my alt account (which is not migrated) and it worked perfectly fine!

### To Reproduce

Log into a java server with a Mojang account that is migrated

### Expected behaviour

Have a “migrated” error and be kicked back to the server list

### Screenshots / Videos

![](https://cdn.discordapp.com/attachments/639913929086074922/907729836355776582/image0.png)

### Geyser Version

master: Build #926 of Revision 0274296366f03e6e83095bfc23ae9256d5463200 (master)

### Minecraft: Bedrock Edition Version

1.17.41

**Comment by Camotoy** [comment]
If you migrated your account, you need to click "Log in with Microsoft account" when prompted. If you use saved credentials, there is a Microsoft toggle you need to enable - see the config section on our wiki for more details.
