### ISSUE TITLE
Title not showing on bedrock edition of minecraft

### ISSUE THREAD

**Issue by TAPGODYT** [GeyserMC/Geyser#2621]
### Describe the bug

ok so I play on two Minecraft versions at the same time one is running java 1.8.9 and the other bedrock edition from Microsoft. both the accounts are connected to the same server using geyser and floodgate. my server version is 1.8.8 paper and I also use Bungeecord. the problem occur when one of my plugins sends a title to the player only the java player see the title for the bedrock player it didn't show up. 

to make sure it wasn't a game issue I tested in a single-player world on bedrock and I can see the title just fine.

### To Reproduce

it's in the description

### Expected behaviour

the bedrock player should be able to see the title when the java player see it

### Server Version and Plugins

Viaversion,Geyser,Floodgate,Bungeeguard on bungeecord
ZKitpvp,NBTAPI and some custom made plugins on paper(1.8.8)

### Geyser Dump

https://dump.geysermc.org/Fv5AFTFPPkknJySURoUWCoIrx8WCxD7X

### Geyser Version

Latest

### Minecraft: Bedrock Edition Version

1.17.41

**Comment by Camotoy** [comment]
I would verify and see if the title appears for a Java 1.17.1 player, since that's what Geyser is trying to emulate.

**Comment by TAPGODYT** [comment]
yes they do

**Comment by TAPGODYT** [comment]
this is still an issue but I've done a bit of testing and it looks like the title appears but for less than 0.5 seconds so most are something related to the depreciated method sendtitle that is not handled properly by a geyser server. I think the fade in and fade out is set to 0.

**Comment by TAPGODYT** [comment]
I tested on the new update for bedrock and I also tested on 1.8.9 all the way up to 1.18 for java

**Comment by RednedEpic** [comment]
Stale. Please open a new issue w/ updated reproduction steps (on a supported server version that is 1.12.2+) if this still occurs.
