### ISSUE TITLE
Particle Mapping apparently resets to defaults

### ISSUE THREAD

**Issue by chrismwiggs** [GeyserMC/Geyser#2622]
### Describe the bug

Not sure if anyone remembers me asking once upon a time, but I use a plugin called Project Korra that makes heavy use of particle effects for abilities in game. Because of the default Geyser particle mappings, many of these abilities create far too many particles on Bedrock clients (from what I can tell, it's the evoker/evoker_emitter particles, seems like where Java is spawning one particle, Bedrock spawns multiple from an emitter). To fix this, I've built my own copy of Geyser where all I change are the particle.json mappings file, to replace the emitter particles with endrod (not ideal, but matches enough for my needs and spawns single particles, vs emitters). 

This is all fine and good (although would be nice to not have to build my own open of Geyser just to change this), but I find that over time (usually hours or days) after starting my standalone Geyser instance, it's as if the mappings data is reset to defaults and my change is gone and we are back to crazy particle emitters. No changes on my side, still using my custom build with new mappings, but suddenly the mappings change. 

### To Reproduce

1. Build copy of Geyser with modified particles.json (replacing all bedrock emitter particles with end_rod)
2. Run Standalone Geyser server, with player load (sometimes 20+ players)
3. Try spawning mobspell particles; confirm endrod being used on bedrock
4. Wait for hours (sometimes a day or two) [unclear how long it takes, or if there is a clear trigger]
5. Try spawning mobspell particles again, particles are back to emitters/defaults.

### Expected behaviour

Of course, I would expect my mappings to be used forever, or until my copy of Geyser is updated to a "vanilla" build with the default mappings. I have no idea how it is even possible for the mappings to "reset", but it's unexpected for sure. 

I'm not sure I understand why the default mappings use emitters for single particles either honestly; I know the particles are limited but it would be nice to find something more similar to the Java counterpart, if possible too. 

### Geyser Dump

https://dump.geysermc.org/3dBxOsSMhZOAJq2Ri68HvFda6i66tayP

### Geyser Version

1.4.3-SNAPSHOT (git-master-62cded2)

**Comment by Camotoy** [comment]
We can't support custom builds reliably, even if it's just the mappings that changed. That being said, we don't update any of our mappings after initial startup.

**Comment by chrismwiggs** [comment]
So just to confirm, the mappings *are* being updated/pulled from remote on geyser startup?

**Comment by Camotoy** [comment]
The only asset that Geyser pulls from the internet is Minecraft Java client locales, and even that is only downloaded if we don't already have the specific locale.

**Comment by chrismwiggs** [comment]
I guess that doesn't make sense then, if the mappings used by Geyser are only ever the mappings in the jar used (mine or an official one), they should always be the same. Seems like something else is going on here, which I guess to your point, doesn't matter to anyone not using the official ones. Again +1 for making the configurable, or at the very least rethinking the emitters as part of the official mappings

**Comment by Camotoy** [comment]
Since this specific issue isn't a mainline Geyser issue, I'm going to close it. Feel free to keep discussing, however.
