### ISSUE TITLE
FPS Drop, Ps4 is unstable with geyser and it shows a lot of erros

### ISSUE THREAD

**Issue by MrNinja008** [GeyserMC/Geyser#2623]
### Describe the bug

Fps drops Suddenly While hitting a mob example: squid and it shows a lot of erros on screen only occurs on consoles (PlayStation)

### To Reproduce

• Join a geyser server with play station
• Hit any mob
• Enjoy the lag and bunch of erros in screen

### Expected behaviour

No lag and bunch of erros while hitting a mob on PlayStation

### Screenshots / Videos

https://user-images.githubusercontent.com/79526396/141240690-b561dee1-cb21-41e4-81b1-377319ae16c1.mov

### Geyser Dump

https://dump.geysermc.org/1Apm8iAhqpRJJsK6EwvpIfcpIcVQ3eqd

### Geyser Version

1.4.3-SNAPSHOT (git-master-62cded2)

### Minecraft: Bedrock Edition Version

1.17.40

**Comment by Camotoy** [comment]
That specific error should only happen with squids. Can you send a video showing it occurs with other mobs?

**Comment by MrNinja008** [comment]
@Camotoy  only happens with squid

**Comment by MrNinja008** [comment]
@Camotoy  is there any fix for this issue?

**Comment by onebeastchris** [comment]
Is this still an issue?
