### ISSUE TITLE
Item Dropping in Creative Gamemode

### ISSUE THREAD

**Issue by zOIDAdaJulian** [GeyserMC/Geyser#2626]
### Describe the bug

Hey, I noticed that dropping Items on Geyser won't work when you are in Creative Gamemode and you click on an plank area next to the Inventory. So if you take a Block from the Creative Menu and try to drop it by tapping on the Site (for example right next to the menu) the item isn't dropping! :D

### To Reproduce

1. Join on a Geyser Server
2. Make sure you are in Creative Mode
3. Try to drop an Item by grabbing it from the creative Menu und tapping next to the inventory
4. The Item won't drop

### Expected behaviour

In Singleplayer Mode the Item is dropping completely normal! :D

### Screenshots / Videos

How it is on Geyser: https://youtu.be/tC4qx1Qf7tk

How it should work (Singleplayer): https://youtu.be/mHqYKGWJdOw

### Server Version and Plugins

This server is running Paper version git-Paper-370 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 29bb5a9)

### Geyser Dump

https://dump.geysermc.org/mFFCELSXF2IMFapRQZfrdS5DE1GrxZMF

### Geyser Version

Geyser Version 1.4.3-SNAPSHOT (git-master-0b35449) (Java: 1.17.1, Bedrock: 1.17.10/1.17.11 - 1.17.40)

### Minecraft: Bedrock Edition Version

1.17.41

### Additional Context

Nothing to add :D

**Comment by Camotoy** [comment]
I'm busy updating Geyser to 1.18, but I did give this a quick test and on desktop I'm able to drop items fine. Looks like you're on touch controls which could make a difference.

**Comment by zOIDAdaJulian** [comment]
Yeah all good. I tried that on Mobile and there the Issue persists for me 😄 👍
I will also try it on Windows later!

**Comment by zOIDAdaJulian** [comment]
Okay, I can now confirm, this Bug only happens on Mobile. So on Windows everything is fine :D

**Comment by zOIDAdaJulian** [comment]
Anything new about the bug? Just tried it with the latest Geyser version on the mobile phone and the bug still persists ^^

**Comment by Konicai** [comment]
Please don't bump issues

**Comment by Camotoy** [comment]
Is the issue that you can't drop items directly from the creative menu (not your inventory)?

**Comment by zOIDAdaJulian** [comment]
Yeah exactly!
This happens if I try to drop Items directly from the creative menu! 😁![image](https://user-images.githubusercontent.com/66011845/147404259-b805b591-1817-4f37-a38e-85d59fcc20bd.png)
