### ISSUE TITLE
Spaces in Usernames

### ISSUE THREAD

**Issue by bundabrg** [GeyserMC/Geyser#263]
**Describe the bug**
I'm not sure whether to class this as a bug or feature because to my surprise Bedrock allows spaces in the username whilst Java edition does not like them (it breaks lots of things).

My suggestion is to remap the space to an underscore before passing it through to the next hop.  I'm happy to create a PR for it but can anyone comment on if there will be unintended consequences on things like floodgate etc?

**To Reproduce**
1. Have a username with a space in it in a bedrock client
2. Join server
3. See the chaos (Authme will block it, but if you add space to its regex then other plugins will have some real issues)

**Server version**
1.15.2 

**Geyser version**
Inventory branch build 2020-04-03

**Bedrock version**
1.14 I think

**Comment by Heath123** [comment]
Username clashes could happen 
This could be a good chance to add something that stores usernames and tweaks them (adds a 1 to the end maybe?) so that a clash is impossible

**Comment by bundabrg** [comment]
That just moved the goal posts though. Now someone can log in with user1 instead to either server.

I can't think of any easy way except for just treating them the same so that you can never have both users logged in at the same time.  It does open a security hole for users with spaces or underscores though.

**Comment by SupremeMortal** [comment]
I can't confirm this but I'm sure I remember testing that Xbox doesn't allow you to register the same name if the space or underscore is already taken. Could anyone check this to see if it's true or just something I dreamt up. 😄

**Comment by SlyWeirdoshep** [comment]
yeah, that's true

**Comment by Loganh4005** [comment]
The issue probably comes from java not meant to have spaces if you have spaces you cannot run commands which gives problems

**Comment by bundabrg** [comment]
It also breaks many json strings so lots of output breaks if you have a space. It does make me wonder how you run commands on bedrock with a space unless it uses quotes?

**Comment by alissonlauffer** [comment]
> I can't confirm this but I'm sure I remember testing that Xbox doesn't allow you to register the same name if the space or underscore is already taken. Could anyone check this to see if it's true or just something I dreamt up. smile

Minecraft Bedrock and Xbox don't allow nicknames with underscores (When you try to add an underscore to your nickname, it will fail).

**Comment by alissonlauffer** [comment]
I think there's no issue replacing spaces with underscores for server side, because you can't have the same nickname with spaces and underscores (because underscores are not supported by bedrock), unless you are using some custom Bedrock client that allow you to use nicknames with underscores (That could be fixed by asserting if the bedrock nickname has forbidden characters. If forbidden characters are found, the player will not be able to login).

**Comment by Heath123** [comment]
> That just moved the goal posts though. Now someone can log in with user1 instead to either server.
> 
> I can't think of any easy way except for just treating them the same so that you can never have both users logged in at the same time. It does open a security hole for users with spaces or underscores though.
> 
> Only other option is to see if java edition allows some character that you cant use normally and use that char instead to map but this may cause other issues.

Then call them user2 or user12

**Comment by bundabrg** [comment]
The vulnerability is this:

  1. Lets say "User Name" logs in via bedrock, and gets assigned a new name "user1"
  2. Another user can then log in via Java Client as "user1" and be the same user.

There is no way to prevent the above apart from renaming the players to names that are invalid to register with mojang for java minecraft but are still accepted to log in.  I'm talking online servers with a whitelist rather than offline since offline can just use another authentication plugin. 

It's not a huge issue since admins/ops can be required to rename their accounts to ones that can't possibly be collided with.

**Comment by rtm516** [comment]
The default config adds a star to the front of the Xbox username, which is something you cannot have in a Java username so doesn't that fix the duplicate names issue?

**Comment by Heath123** [comment]
> The default config adds a star to the front of the Xbox username, which is something you cannot have in a Java username so doesn't that fix the duplicate names issue?

We were talking about 2 Bedrock accounts having the same name

**Comment by yeenbean** [comment]
Forgive me, I'm not sure if I should open a new issue or not.

Another unintended side effect of gamer tags with spaces is the inability to link Java and Bedrock accounts with Floodgate. I did try replacing the space with an underscore, but it does not work. Is there a possible workaround for this?

**Comment by jackson-57** [comment]
Have you tried wrapping the bedrock username in quotes?

**Comment by yeenbean** [comment]
Yes. The command returns usage instructions, so I guess it doesn't understand the input that way.

**Comment by RednedEpic** [comment]
This is a toggle within Floodgate now. Only setup where this would really benefit is offline mode which we don't support. Thanks for reporting this though!
