### ISSUE TITLE
Hello, wrong version of server and bedrock

### ISSUE THREAD

**Issue by StalidUs** [GeyserMC/Geyser#2630]
### Describe the bug

I created server on Paper 1.16.5, and i installed geyser spigot, and change config, it works,but on bedrock it says for connect need 1.17 version of bedrock, and i installed 1.17 and it says "Outdated server! Im still on 1.16.5" what me do?

### To Reproduce

..

### Expected behaviour

Need to play on server :(

### Screenshots / Videos

![Screenshot_20211114-212201_One UI Home](https://user-images.githubusercontent.com/94302184/141685168-8c1c4905-af94-4ce8-93b5-8b8b72a0b640.jpg)

### Server Version and Plugins

1.16.5

### Geyser Version

latest 1.2.0 snapshot

### Minecraft: Bedrock Edition Version

1.17.40

### Additional Context

What me do?

**Comment by Chew** [comment]
I've commented somewhere but hard to find on mobile.

Essentially geyser emulates a Java 1.17 player so you'll need to upgrade to 1.17 or use something like [ViaVersion](https://viaversion.com) to allow them to join the 1.16 server.

Please let us know if you run into issues!

**Comment by StalidUs** [comment]
Thank, i can and my players can play on bedrock too
