### ISSUE TITLE
Some maps can crash phone players

### ISSUE THREAD

**Issue by hectozul** [GeyserMC/Geyser#2633]
### Describe the bug

Some maps, I don't know why can crash phone players, I tried to reproduce with Windows 10 edition but was not posible. I guess that the limit resources of the phones are part of the issue because a player told me that after get the map he can feel a lot of lag and this lag increases if he rejoin the server. After enter the server the map generates a massive lag and crashes the game (Sometimes) so, is hard to reproduce.

The only think that I can share you is the data of "bug map" imported with MythicMobs item import feature, it clones everything and is helpful to analyze all the data involced with the item.

bugmap:
  ItemStack:
    ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: FILLED_MAP
    meta:
      ==: ItemMeta
      meta-type: MAP
      display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"text":"Map
        (row 1, column 2)"},{"italic":false,"text":""}],"text":""}'
      ItemFlags:
      - HIDE_ENCHANTS
      - HIDE_ATTRIBUTES
      - HIDE_UNBREAKABLE
      - HIDE_DESTROYS
      - HIDE_PLACED_ON
      - HIDE_POTION_EFFECTS
      - HIDE_DYE
      map-id: 4435

### To Reproduce

1. Open minecraft Android edition 
2. Get the "bug map" from a chest (This can cause crash)
3. Leave the server and join again
4. After join the server with the map, a crash is spected or client side lag.

### Expected behaviour

Just dont crash

### Server Version and Plugins

git-Purpur-1427 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8bb5a93 on ver/1.17.1)

AuthMe, BungeeGuard, BuycraftX, CakeTwitch, ChatManager, Chunky, Citizens, Coins, ConsoleSpamFix, EconomyShopGUI, Essentials, EssentialsChat, FactionsX, floodgate, ImageOnMap, InventoryRollbackPlus, LevelledMobs, LibsDisguises, LuckPerms, MMOItems, MoneyFromMobs, MythicCrucible, MythicLib, MythicMobs, OPSecurity, Plan, PlayerKits, ProtocolLib, SecureOP, SkinsRestorer, StreamingDrops*, TradeSystem, Vault, ViaBackwards, ViaVersion, VoidTeleport, Votifier, VotingPlugin, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/8HffICwit7dqwOpaZkS4MpaRA630asYO

### Geyser Version

Geyser-Bungeecord

### Minecraft: Bedrock Edition Version

Latest (Android)

### Additional Context

The first time I noticed something weird related to maps was when we added a custom map item with all kind of displayname effects and I simplified it because it was crashing bedrock players.
I know that my info is poor but there is something rare with maps and Android players.

**Comment by Camotoy** [comment]
Are you able to send a world download containing this map in a chest or in a player inventory?

**Comment by Konicai** [comment]
Not much we can do without data to reproduce with, update us if you can
