### ISSUE TITLE
Add support for Minecraft: Education edition

### ISSUE THREAD

**Issue by MIOGMIOG** [GeyserMC/Geyser#2641]
### What feature do you want to see added?

Please add Education Edition support.

### Are there any alternatives?

[GeyserReversion by bundabrg](https://github.com/bundabrg/GeyserReversion), but this project is not updated.

**Comment by Camotoy** [comment]
Unfortunately, this is not something the core team is interested in at this time. None of us have Education Edition on hand. In the future we will revive the extension branch so that projects like GeyserReversion can be more easily maintained. Thank you anyway!
