### ISSUE TITLE
Dropped anvil crashes Geyser if a Geyser player drops it.

### ISSUE THREAD

**Issue by JustAssassinExists** [GeyserMC/Geyser#2643]
### Describe the bug

Title

### To Reproduce

Log in with 1 or more geyser accounts, drop an anvil, crass

### Expected behaviour

Not crass

### Screenshots / Videos

Don't currently have video but 
![image](https://user-images.githubusercontent.com/75682159/142714198-15a67e14-9034-4bb1-8526-731c0d545860.png)

Geyser dump:
![image](https://user-images.githubusercontent.com/75682159/142714251-851996b3-25ac-4d44-8a6a-531216194630.png)

### Server Version and Plugins

3258-Spigot-dc75aca-960f310 (MC: 1.17.1) 1.17.1-R0.1-SNAPSHOT
![image](https://user-images.githubusercontent.com/75682159/142714238-80f768b7-55d3-4773-bf2b-af5cfe11bc75.png)

### Geyser Version

1.4.3-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.41

**Comment by Camotoy** [comment]
Please provide your server logs located in `logs/latest.log`, upload them to https://mclo.gs/ and send the link here.

**Comment by JustAssassinExists** [comment]
Just needed to update geyser.
