### ISSUE TITLE
Curse of binding is ignored when equpping armour with right click

### ISSUE THREAD

**Issue by ziggykac** [GeyserMC/Geyser#2644]
### Describe the bug

Geyser seems to allow java players to swap armour pieces by right clicking (without inventory open) like in bedrock. This doesn't take into account curse of binding.
I've tested this on several servers. 

### To Reproduce

1. Equip a curse of binding armour piece
2. Hold a piece of armour that can be equipped in the same slot
3. Right click, you might have to right click several times

### Expected behaviour

That it shouldn't wok

### Server Version and Plugins

This server is running Paper version git-Paper-384 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 51b7b60)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-358 (MC: 1.17.1)

### Geyser Dump

https://dump.geysermc.org/1xH1s9SOeNj31eCK4ofVWgAggQk2yk8W

### Geyser Version

1.4.3-SNAPSHOT (git-master-b92b49b)

### Minecraft: Bedrock Edition Version

1.17.10/1.17.11 - 1.17.40

**Comment by Camotoy** [comment]
This sounds like a visual glitch. I'd verify on another client, or relog to see, if it actually goes into effect.

**Comment by ziggykac** [comment]
> This sounds like a visual glitch. I'd verify on another client, or relog to see, if it actually goes into effect.

It does, not a visual glitch sadly

**Comment by Camotoy** [comment]
I can't replicate this on a desktop setup with Paper 353 and the latest Geyser version - Bedrock doesn't even try to swap binding armor (we block it if it happens). Maybe one of your plugins replaces the enchantment system so Geyser doesn't officially mark the item with the Curse of Binding enchantment?

**Comment by ziggykac** [comment]
Really sorry, thought I'd disabled the enchantmentplugin

**Comment by Camotoy** [comment]
This might still be a bug we need to look into. Regardless, glad to see your issue is resolved.
