### ISSUE TITLE
Account completely disabled after using geyser with "online" auth method

### ISSUE THREAD

**Issue by SquirrelOn0IQ** [GeyserMC/Geyser#2645]
### Describe the bug

Whenever I use my Java credentials for Geyser, my account becomes completely unusable for hours after leaving the server. The java launcher signs me out and says "Invalid email or password" and so does Geyser. This is a very big bug and really irritates me as I'm just trying to enjoy my day with some Minecraft.

### To Reproduce

1. Connect to a server using the "online" auth type
2. Try logging in with your Java launcher or Geyser

### Expected behaviour

To be able to log back in.

### Geyser Version

This server is running Geyser version 1.4.3-SNAPSHOT (git-master-b92b49b) (Java: 1.17.1, Bedrock: 1.17.10/1.17.11 - 1.17.40)

### Minecraft: Bedrock Edition Version

1.17.41

### Additional Context

I am very angry.

**Comment by Camotoy** [comment]
What does the account say when logging in on a web browser? (Like logging into microsoft.com or xbox.com).

**Comment by SquirrelOn0IQ** [comment]
It's a Mojang account, and it says the same thing.

**Comment by Camotoy** [comment]
Where is Geyser hosted?

**Comment by SquirrelOn0IQ** [comment]
on my server using ggservers

**Comment by SquirrelOn0IQ** [comment]
Follow up: I contacted Mojang support 2 days ago and they haven't responded, I still can't use my account.

**Comment by MrZomka** [comment]
> Follow up: I contacted Mojang support 2 days ago and they haven't responded, I still can't use my account.

man, that sucks. I'm sorry for you :(

**Comment by Jens-Co** [comment]
Any news on this issue ? :/

**Comment by Seamusmario** [comment]
> Follow up: I contacted Mojang support 2 days ago and they haven't responded, I still can't use my account.

Damn. I'm sorry you are dealing with this situation.

**Comment by SquirrelOn0IQ** [comment]
I was a
