### ISSUE TITLE
Geyser support for Education Edition

### ISSUE THREAD

**Issue by thunder-red-star** [GeyserMC/Geyser#2646]
### What feature do you want to see added?

Yes, I feel like this is a dumb request. 

Geyser seems to be saying that the bedrock version needed to connect is 1.17.10. But I want to connect with Minecraft Education Edition, which is 1.17.30. If it isn't Education Edition blocking the connection, could you make an option to change the broadcasted version?

### Are there any alternatives?

Unarchiving the archive and editing files (unfortunately to no avail)

**Comment by Camotoy** [comment]
See my response here: https://github.com/GeyserMC/Geyser/issues/2641

Thank you anyway!

**Comment by Camotoy** [comment]
Also, do note: it's not as easy to simply support the protocol version, unless something has changed.
