### ISSUE TITLE
Hope to fix the white screen when joining the server

### ISSUE THREAD

**Issue by DJelly4K** [GeyserMC/Geyser#2647]
### What feature do you want to see added?

Hope to fix the white screen when joining the server

### Are there any alternatives?

Nope.

**Comment by Jens-Co** [comment]
Can you elaborate bit more about your issue ? Maybe a printscreen? Also please follow our issue template :)

**Comment by DJelly4K** [comment]
> Can you elaborate bit more about your issue ? Maybe a printscreen? Also please follow our issue template :)

White screen(the void)

**Comment by Jens-Co** [comment]
This is expected Geyser behavior and not something that is "fixable".

**Comment by DJelly4K** [comment]
> This is expected Geyser behavior and not something that is "fixable".

Can the branch "mainthreadchunks" fix this problem?

**Comment by Camotoy** [comment]
This behavior will be mitigated/fixed with 1.18. Yes, the mainthreadchunks branch also fixes the issue.

Thanks!
