### ISSUE TITLE
Custom domain support

### ISSUE THREAD

**Issue by zReport02** [GeyserMC/Geyser#2648]
### What feature do you want to see added?

Hi, I'm not sure this is possible with geyser currently so if in doubt I write it!
Is it possible to know the dns domain from where the player is connecting directly to bungeecord?

I have a bungeecord server and a standalone proxy geyser, in the bungeecord server I would like to know the domain that the player used to connect, maybe with bees if possible or something like that

Sorry for my bad english

### Are there any alternatives?

I don't know, i would like to know the used domain whatever it is

**Comment by Konicai** [comment]
You can enable `forward-hostname` in the remote section of Geyser's config

> Forwards the hostname/IP address that the Bedrock client used to connect over to the Java server. This is designed to be used for forced hosts on proxies.

Is that sufficient?
