### ISSUE TITLE
Xbox with MC Server Connector cant connect to Velocity Server

### ISSUE THREAD

**Issue by DaniGTA** [GeyserMC/Geyser#2649]
### Describe the bug

When a **Xbox** player joins the Velocity server the player gets "**Unable to connect to world**"
When a Minecraft for Windows 10 Bedrock edition player joins the Server, it works.
When a Minecraft java player joins the Server, it works.

The server log just says "Trying to connect" several times when the xbox player joins and one time when the Windows 10 Bedrock player joins

### To Reproduce

1. Have a Velocity Server with latest Floodgate velocity plugin and latest Geyser velocity plugin.
2. Use Android APP "MC Server Connector" to connect to the Velocity Server.
3. Join with a XBox to the Server.

### Expected behaviour

Xbox player joining the Server

### Server Version and Plugins

Velocity 3.0.1
floodgate 2.0-SNAPSHOT
geyser 1.4.3-SNAPSHOT (git-master-798f8da)

### Geyser Version

1.4.3-SNAPSHOT (git-master-798f8da)

### Minecraft: Bedrock Edition Version

1.17.41 Xbox and Windows

**Comment by Grizzly90** [comment]
Do you have a Xbox gold subscription for the Xbox?
Does it works if you use mc server connector with the windows bedrock edition?

**Comment by DaniGTA** [comment]
Windows Bedrock Edition
--> MC Server Connector --> Velocity  = WORKS
--> Velocity  = WORKS
--> Paper (Plugin version) = WORKS

Xbox with **Gold Subscription **:
--> MC Server Connector --> Velocity  = WORKS NOT (Logs:  "Trying to connect" several times)
--> Velocity  = WORKS NOT (Logs:  "Trying to connect" several times)
--> Paper (Plugin version) = WORKS

**Comment by Camotoy** [comment]
The way Bedrock players connect to Geyser does not change between plugin implementations - Velocity and Spigot should have the same initial connection experience. Is this on the same physical server? Perhaps query is interfering on Velocity?

**Comment by DaniGTA** [comment]
I write the xbox tests a little bit wrong.

So i have a paper Server on port 25565 and i planned to replace it with a velocity server.

I maked some test with the Windows Bedrock Edition and it works  without problems. Test was on local network direct connect to the velocity server and i testet it again on the paper server on the same network then i testet both on external network and  all works then i tested the xbox version and on velocity it wont work. And no there are not on the same physical server but both physical servers are tested with plugin version connection and both works.

**Comment by Grizzly90** [comment]
maybe a /geyser dump and a /velocity dump from the velocity your trying to connect from your xbox would be helpful.

Could you try MineProxyDroid? I Just tried MC Server Connector with windows 10 edition and had some strange behavior, like using /server command was executed immediately in the proxy but the client took like 60 seconds to load the world. With MineDroidProxy the client loaded the new world instant after the command.

**Comment by Camotoy** [comment]
Yes, please send a Geyser dump from both the working Geyser/Paper setup and the not working Geyser/Velocity setup.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by DaniGTA** [comment]
Xbox on Velocity with MC Connect: https://dump.geysermc.org/T7wwr09bpWlMmGg6NWvarVMeEedIwtDw
Xbox on Paper with MC Connect: https://dump.geysermc.org/No13adUqnqAAwH9CyBfO4dIBLOIJCbEk
PC Bedrock on Velocity: https://dump.geysermc.org/4TIHRakt1vqSBAjoZEr888G6zZiPOyLa

**Comment by RednedEpic** [comment]
Stale. Probably best to follow up in Discord if this still occurs as it may be a connection issue that needs to be troubleshooted.
