### ISSUE TITLE
Bedrock players are stuck in void after about 2 minutes of launching the server

### ISSUE THREAD

**Issue by bafgd** [GeyserMC/Geyser#2650]
### Describe the bug

When i launch the server i can play on it with my friends but after about 2 to 5 minutes the server is still playable but no bedrock players can play because if they are logged in they wont be able to do anything, they can try to break blocks but no animation or particles and no items dropped. on java side they will be stuck from when the Geyser stopped to respond. And when the bedrock players relog they are send into the void and they will be stuck there.
![unnamed](https://user-images.githubusercontent.com/95045282/143480861-d5315896-36cc-45df-9d98-61443644ef4a.jpg)
 

### To Reproduce

1. start a paper or spigot server without any plugins besides geyser
2. join on bedrock and java (no order in wich to login first)
3. start to load chunks with the bedrock account
4. in a couple of minutes all mobs and liquid will stop and when relogging on bedrock it will put you into the void
5. java will be able to play just fine

### Expected behaviour

bedrock players should be able to play just fine as long as the server is enable

### Screenshots / Videos

https://user-images.githubusercontent.com/95045282/143481491-64212f9a-9e54-4475-b7c1-f7b7595d3381.MOV

### Geyser Dump

https://dump.geysermc.org/Rc1HARPV8sbpkrfWyFSj78mh92y4lspE

### Geyser Version

1.4.3-SNAPSHOT (git-master-798f8da)

### Minecraft: Bedrock Edition Version

1.17.41

### Additional Context

- if you restart the server then it will be playable for another 2-5
- when a bedrock player chats (not running a command) it will show to java players and in console
- the server recognizes when the bedrock player joins so if a java player joins in the same name then it will kick the player from the server point but from the client in bedrock they are still in the void (chatting wont do anything now) 
- to people who want to switch to paper or to spigot because of the glitch, it is the same deal as i loaded a test server and it has the same bug

**Comment by bafgd** [comment]
i am using the latest build for geyser (yes i downloaded the latest one to see if this bug was patched)

**Comment by Camotoy** [comment]
Can you try this build? If it still doesn't work there will hopefully be new logs in the console. https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/network-dep-update/

**Comment by bafgd** [comment]
> Can you try this build? If it still doesn't work there will hopefully be new logs in the console. https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/network-dep-update/

alright i will try :)

**Comment by bafgd** [comment]
it is a little different i can move in the void but then in stead of the air bubbles that show up when you are drowning nothing shows up and im at y lvl -40 (also when i chat i can still see the message in console, and teleporting wont knock me back into the world)

https://user-images.githubusercontent.com/95045282/143483889-c6f8cbd2-2773-4a59-ad1f-972e9e221fae.MOV

**Comment by bafgd** [comment]
this is the latest log from when i joined in the recording


11:35:07] [Network Listener - #1/INFO]: [Geyser-Spigot] Bedrock user with ip: /192.168.1.1 has disconnected for reason CLOSED_BY_REMOTE_PEER
[11:35:07] [defaultEventLoopGroup-4-1/INFO]: [Geyser-Spigot] bafgd has disconnected from the Java server because of CLOSED_BY_REMOTE_PEER
[11:35:07] [Server thread/INFO]: bafgd lost connection: Disconnected
[11:35:07] [Server thread/INFO]: bafgd left the game
[11:35:14] [Network Listener - #1/INFO]: [Geyser-Spigot] /192.168.1.1:60552 tried to connect!
[11:35:14] [Network Listener - #0/INFO]: [Geyser-Spigot] Player connected with username bafgd
[11:35:20] [Geyser player thread-2-2/INFO]: [Geyser-Spigot] Attempting to login using offline mode... authentication is disabled.
[11:35:20] [defaultEventLoopGroup-4-2/INFO]: [Geyser-Spigot] bafgd (logged in as: bafgd) has connected to the Java server
[11:35:20] [User Authenticator #2/INFO]: UUID of player bafgd is fd805443-d8c4-33a0-8da3-669c96229977
[11:35:20] [Server thread/INFO]: bafgd joined the game
[11:35:20] [Server thread/INFO]: bafgd[/192.168.1.1:0] logged in with entity id 878 at ([world]-164.69999, 66.0, -303.30001)
[11:35:49] [Server thread/INFO]: bafgd issued server command: /tp bafgd 1 100 1
[11:36:01] [Server thread/INFO]: CONSOLE issued server command: /tp bafgd 1 100 1
[11:36:01] [Server thread/INFO]: Teleporting...
[11:36:08] [Async Chat Thread - #0/INFO]: <bafgd> hello
[11:36:19] [Network Listener - #1/INFO]: [Geyser-Spigot] Bedrock user with ip: /192.168.1.1 has disconnected for reason CLOSED_BY_REMOTE_PEER
[11:36:19] [defaultEventLoopGroup-4-2/INFO]: [Geyser-Spigot] bafgd has disconnected from the Java server because of CLOSED_BY_REMOTE_PEER
[11:36:19] [Server thread/INFO]: bafgd lost connection: Disconnected
[11:36:19] [Server thread/INFO]: bafgd left the game

**Comment by bafgd** [comment]
i disabled online mode for bedrock users because they dont want to login each time they enter the server

**Comment by Chew** [comment]
Please use Floodgate if you wish to allow bedrock users to join, offline mode is not recommended.

**Comment by bafgd** [comment]
yes i was going to set floodgate up but i want to be done with this bug

**Comment by bafgd** [comment]
> Please use Floodgate if you wish to allow bedrock users to join, offline mode is not recommended.

i am using floodgate and now my name is (.bafgd) not (bafgd) so i dont have any of my items

**Comment by bafgd** [comment]
also if i use floodgate it does not resolve the issue if anyone was wondering

**Comment by Austinizer** [comment]
whenever my friend joins he is in the server for a few seconds and is in the void before he is disconnected.

**Comment by bafgd** [comment]
> whenever my friend joins he is in the server for a few seconds and is in the void before he is disconnected.

Same but they don’t get disconnected they get frozen and when rejoining they get sent to void

**Comment by Austinizer** [comment]
i fixed my issue, for me it was a plugin issue ill update you when i figure out what plugin it was

**Comment by bafgd** [comment]
> i fixed my issue, for me it was a plugin issue ill update you when i figure out what plugin it was

thx bro appreciate it :)

**Comment by Austinizer** [comment]
actually what other plugins do you have installed?

**Comment by bafgd** [comment]
> actually what other plugins do you have installed?

![Screenshot 2021-11-25 204647](https://user-images.githubusercontent.com/95045282/143519099-72947ffe-fb2d-4e5c-a7f8-8635b6501e33.png)

**Comment by bafgd** [comment]
Yeah I have a lot

**Comment by Austinizer** [comment]
I didnt have any of those plugins other than dynmap and floodgate but i left dynmap enabled

**Comment by bafgd** [comment]
Dynmap is just rendering the world and saving it. The least it should do is help geyser to load faster

**Comment by bafgd** [comment]
So what do I do?

**Comment by valenvaio** [comment]
I have the same situation and for quite a long time. 

Appears such a message has disconnected for reason CLOSED_BY_REMOTE_PEER after several moves on the map through the portals. But in the client player visually still on the server. After the next time you enter the server, he hangs in the void. The situation is corrected with Geyser restart.

Checked with different versions of the latest.

**Comment by bafgd** [comment]
> I have the same situation and for quite a long time.
> 
> Appears such a message has disconnected for reason CLOSED_BY_REMOTE_PEER after several moves on the map through the portals. But in the client player visually still on the server. After the next time you enter the server, he hangs in the void. The situation is corrected with Geyser restart.
> 
> Checked with the latest versions.

Ok i will indeed try that because I have never tried to do a geyser restart

**Comment by valenvaio** [comment]
The error persisted on version 1.18. If you watch the place where the player is supposed to appear, then during the entrance to this place there are particles of smoke. But the player himself does not appear. In the player's client he hangs in the void. Checked the work without plugins.

**Comment by bafgd** [comment]
So do I restart geyser after 5 mins of the server starting?

**Comment by bafgd** [comment]
> The error persisted on version 1.18. If you watch the place where the player is supposed to appear, then during the entrance to this place there are particles of smoke. But the player himself does not appear. In the player's client he hangs in the void. Checked the work without plugins.

i have noticed that when i get frozen in bedrock edition and when i chat i can see msgs and commands in console. it actually does the thing such as setblock. Bet when i do /help it actually sends the /help help msg in chat. Then when i login to the server with the same name it kicks the player from the server (still is seen as player frozen in server client side) and then i have been left on the spot from when the bug happened. Any help i could get. killing the player does not work. reinstalling geyser.jar and its files does not work, switching from which computer the server is running on does not work, upgrading to windows 11 does not work, using spigot instead of paper does not work. only having geyser as a plugin and non other does not work, I have listed my trouble shooting, please tell me what i should do so i can get my server up and running again. Thankyou

**Comment by valenvaio** [comment]
https://github.com/GeyserMC/Geyser/issues/2376
Similar problem at the link

**Comment by Chew** [comment]
Exact opposite of this problem, it seems (they can play until they can't while this is they can't play until they can?)

**Comment by Jens-Co** [comment]
Any news on this issue ? If yes can you try to debug you plugins ?
![image](https://user-images.githubusercontent.com/63231928/146719639-1c6634e4-28e1-412f-9550-b45afa8fd769.jpeg)
Thanks

**Comment by valenvaio** [comment]
I have tried to just install geyser without any plugins and still same bug to

**Comment by ardha27** [comment]
is this already resolve? i have same problem :(

**Comment by Konicai** [comment]
If you have nothing to add please don't bump issues

**Comment by mcmohen** [comment]
I didn't experience this problem until I moved the server to the virtual machine.
I have also tried to remove all plug-ins except Geyser, but the problem still exists.
Because the server files before and after migration are completely consistent, I have to suspect that the problem lies on different computers or systems.
(My computer is running on Windows10 and virtual machine is on Windows Server 2019)
Hope my words can do some help and I am looking forward to any solution.(I'm Chinese so plz don't mind my unclear English)

**Comment by Camotoy** [comment]
Are you using a 10th or 11th generation Intel processor? If so, please try adding the following Java VM arguments to your server launch: `-XX:+UnlockDiagnosticVMOptions -XX:-UseAESCTRIntrinsics`.

**Comment by mcmohen** [comment]
> Are you using a 10th or 11th generation Intel processor? If so, please try adding the following Java VM arguments to your server launch: `-XX:+UnlockDiagnosticVMOptions -XX:-UseAESCTRIntrinsics`.

Thanks a lot! It actually work and totally solve my problem!
(My CPU is i5-11600K

**Comment by Camotoy** [comment]
This issue is likely the same as #2861. If it is not, then please open a new issue. Thanks!

**Comment by patrickfeeney03** [comment]
@Camotoy Do I paste -XX:+UnlockDiagnosticVMOptions -XX:-UseAESCTRIntrinsics this on the .bat? I did and it says tha X is not a recognized option.

**Comment by patrickfeeney03** [comment]
oh so it needs to be before the -jar part. 
I'm going to test and see if the bedrock bug still occurs.

**Comment by jacobwkaiser** [comment]
Update? im using havoc hosting and having the same issues.

**Comment by Chew** [comment]
Please refer to the linked issue Camotoy mentioned. This issue is a duplicate.
