### ISSUE TITLE
Bedrock Edition player enchanted items (ecoenchants) cannot be put into the backpack

### ISSUE THREAD

**Issue by wykwey** [GeyserMC/Geyser#2652]
### Describe the bug

Bedrock Edition player enchanted items (ecoenchants) cannot be put into the backpack

### To Reproduce

Bedrock Edition player enchanted items (ecoenchants) cannot be put into the backpack

### Expected behaviour

Items can be repaired

### Server Version and Plugins

[20:05:06 INFO]: Plugins (30): AdvancedChests, BloodMoon, CatSeedLogin, CMI, CMI
Lib, CoreProtect, CreativeManager, DragonTimer, eco, EcoEnchants, EcoEnchantsGUI
, Geyser-Spigot, GeyserSkinManager, Iris, LibsDisguises, LuckPerms, PlaceholderA
PI, PlugMan, ProtocolLib, QualityArmory, Residence, SlimeChunkMapPlus, Slimefun,
 spark, TrMenu, UltimateCatcher, Vault, ViaVersion, WhiteList*, WorldMania

### Geyser Version

 1.4.3-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.16.5

### Additional Context

[latest.log](https://github.com/GeyserMC/Geyser/files/7608632/latest.log)

**Comment by Konicai** [comment]
Closing in favour of https://github.com/GeyserMC/Geyser/issues/2034 (Item moving issues with eco)
