### ISSUE TITLE
Bedrock clients getting wrong/outdated version error

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [GeyserMC/Geyser#2654]
### Describe the bug

Bedrock clients trying to join get wrong/outdated version error. As far as I know or care right now that's because they're trying to join on 1.17. Can this problem be solved?

### To Reproduce

1. Go to Minecraft Bedrock Edition
2. Select Play
3. Select Servers
4. Entering server ip and port
5. Save
6. Connect
7. See the error

### Expected behaviour

Opened server

### Screenshots / Videos

/

### Server Version and Plugins

/

### Geyser Dump

/

### Geyser Version

1.4.3-SNAPSHOT (git-master-798f8da)

### Minecraft: Bedrock Edition Version

Latest version iOS (Updated 29.11.2021)

### Additional Context

/

**Comment by Camotoy** [comment]
Please post a Geyser dump and a screenshot or log of the exact error players are getting.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by admin-elvistrujanovic** [comment]
> Please post a Geyser dump and a screenshot or log of the exact error players are getting.
> 
> Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

Ok, I'm working on that

**Comment by Rarafaza5** [comment]
https://dump.geysermc.org/NXHmjZyO2B0n0YePIgQqFFBotKhhcgVD
