### ISSUE TITLE
Add backwards compatability for latest GeyserMC

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [GeyserMC/Geyser#2655]
### What feature do you want to see added?

Backwards compatability on latest GeyserMC versions to support 1.16.5 and lower mc servers because most servers is on 1.16.5 due to plugins not having been updated yet.

### Are there any alternatives?

No

**Comment by Jens-Co** [comment]
You can use the plugin ViaVersion (https://www.spigotmc.org/resources/viaversion.19254/) for backwards server compatibility.

**Comment by admin-elvistrujanovic** [comment]
> You can use the plugin ViaVersion (https://www.spigotmc.org/resources/viaversion.19254/) for backwards server compatibility.

But ViaVersion plugin - The updated version has the same issue as the updated geyser because they both need updated to function or backdated to function.

**Comment by admin-elvistrujanovic** [comment]
@Jens-Co

☝️

**Comment by Camotoy** [comment]
I'm not sure what you mean - the latest ViaVersion can be installed on a 1.16.5 server and allow Geyser players to join. Implementing older version support ourselves is therefore slightly redundant.

**Comment by admin-elvistrujanovic** [comment]
> I'm not sure what you mean - the latest ViaVersion can be installed on a 1.16.5 server and allow Geyser players to join. Implementing older version support ourselves is therefore slightly redundant.

Well, for example, the Ponyville Plaza MC server is 1.16.5 and has the latest version of the plugin installed but still doesn't work

ip: mc.ponyvilleplaza.com

**Comment by Chew** [comment]
Geyser requires Java 16 to run, you'd need to upgrade to running Java 16 or Geyser won't load.
