### ISSUE TITLE
ClientboundContainerSetContentPacket error in console

### ISSUE THREAD

**Issue by ziggykac** [GeyserMC/Geyser#2657]
### Describe the bug

Installed the new geyser update + floodgate update + via version for 1.18, thought you guys should know about this, sorry if this isn't specific enough

### To Reproduce

Not sure how it happens

### Expected behaviour

This error to not to happen

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/33180611/144125989-0d0503c4-0a2c-4fcc-856d-52b7c8e4204e.png)

### Server Version and Plugins

git-Paper-388 (MC: 1.17.1)
![image](https://user-images.githubusercontent.com/33180611/144126209-3f5efa67-183a-49d0-8650-a22f75907d6b.png)

### Geyser Dump

https://dump.geysermc.org/yrTkjuh2kIt53urmJYZ3arz7RoLeTl17

### Geyser Version

2.0.0-SNAPSHOT (git-master-75d1a63)

### Minecraft: Bedrock Edition Version

1.17.30 - 1.18.0

**Comment by Camotoy** [comment]
If you know how to replicate this, that would be lovely.

**Comment by ziggykac** [comment]
Not sure sadly, it's just spitting it out in console from time to other, I know that makes it very hard to fix but thought it would be worth posting it just in case

**Comment by Camotoy** [comment]
This is the same error as #2577 just for 1.18, so I'll close this in favor of that. Thank you anyway!
