### ISSUE TITLE
Wont let me join on bedrock. gives Connection refused/closed by remote peer

### ISSUE THREAD

**Issue by Xplodin** [GeyserMC/Geyser#266]
**Describe the bug**
Uhh does this: 
![image](https://user-images.githubusercontent.com/13007677/78423856-4ae4aa00-7637-11ea-9b64-ed8f767047f0.png)

**To Reproduce**
1. Go to 'servers'
2. Click on 'the custom server i put on'
3???

**Expected behavior**
Join in

**Screenshots**
![image](https://user-images.githubusercontent.com/13007677/78423871-60f26a80-7637-11ea-8b09-2fcccf37206f.png)

**Server version**
bukkit/spigot 1.15.2

**Geyser version**
bukkit/spigot 1.15.2

**Bedrock version**
1.14.30

**Additional context**
idk what to do but I run pterodactyl panel if that makes a difference however both ports are forwarded and allocated to the main server

[Network Listener - #1/INFO]: [Geyser-Bukkit] Player connected with username Autismo Bean
> [11:42:23] [Thread-37/INFO]: [Geyser-Bukkit] Autismo Bean has disconnected from remote java server on address 127.0.0.1 because of org.geysermc.platform.bukkit.shaded.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:25580
> [11:42:23] [Network Listener - #1/INFO]: [Geyser-Bukkit] Bedrock user with ip: /65.33.148.195 has disconnected for reason CLOSED_BY_REMOTE_PEER

**Comment by mrchu39** [comment]
Did you solve this? I am running into this problem as well.

**Comment by RednedEpic** [comment]
> Did you solve this? I am running into this problem as well.

See the common issues page.

**Comment by mrchu39** [comment]
I have the auth-type set to online and used the correct credentials, yet I'm still getting this error.

**Comment by Xplodin** [comment]
Solved by opening ports on the panel via allocation settings.
Unsure as the age of this is quite old.Try messing with ports and allocations
  


Did you solve this? I am running into this problem as well.

**Comment by ManifoldFlame83** [comment]
I'm having the same issue but I don't know anything about coding or computers I just want to play with my friends and I don't understand what allocation settings are

**Comment by DoctorMacc** [comment]
@ManifoldFlame83 Please see https://github.com/GeyserMC/Geyser/wiki/Common-Issues and if you have further problems please join us on Discord.

**Comment by ManifoldFlame83** [comment]
I just checked that link and there is nothing on it

**Comment by DoctorMacc** [comment]
Please join our Discord; it is very likely you have a config problem we can help you resolve.

**Comment by ManifoldFlame83** [comment]
what is the discord link?

**Comment by DoctorMacc** [comment]
http://discord.geysermc.org/

**Comment by Super-Toaster** [comment]
IT does the same thing for me but i use Bentobox + Bskyblock,challenges,control panel, when i open the gui "/island challenges or /island cp" it spawns a chest over my head(bedrock client only)
