### ISSUE TITLE
Tag Versions

### ISSUE THREAD

**Issue by myxxmikeyxx** [GeyserMC/Geyser#2660]
### What feature do you want to see added?

I would like to see Tags used for versions, this way when you change to 1.18 to 1.17 you can easily use a tag and get the last successful build/release for that version. The big reason why is because the 1.18 version does not support 1.17 any more and I had a heck of a time finding the 1.17 jar before the last update.

### Are there any alternatives?

Have releases with the .jar file for the different versions.

**Comment by Chew** [comment]
We already do this on the CI: https://ci.opencollab.dev//job/GeyserMC/job/Geyser/job/master/

![image](https://user-images.githubusercontent.com/8278263/144278111-69e359ae-7836-42a4-9ca3-b1c2d1916bca.png)


Obviously, keep in mind you won't get support and we highly encourage you to update to the latest and use ViaVersion/ViaBackwards. Do note the latest Geyser Jar supports SERVER version Java 1.12.2 - 1.18, but the player will be 1.18. For this, just toss ViaVersion on your 1.17.1 server.
