### ISSUE TITLE
Bugged Update?

### ISSUE THREAD

**Issue by ICodeDumbStuff** [GeyserMC/Geyser#2662]
### Describe the bug

i updated my geyzer and bungeecord .jar files for 1.18 and when i try and join my server i get "Please connect through the official Geyser" and i havent changed anything exept my 2 .jar's as i stated idk if floodgate needs updating or not but i have that installed

### To Reproduce

idk

### Expected behaviour

cant join on mcpe

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/91792657/144303967-e7380bfb-3b8d-4541-9895-a9a73260904f.png)

### Server Version and Plugins

latest bungeecord

### Geyser Dump

https://dump.geysermc.org/hAjLvxYBRyh1aSqossvlV7AGSfW0lvN7

### Geyser Version

newest one

### Minecraft: Bedrock Edition Version

1.18.0

**Comment by Camotoy** [comment]
Yes, Floodgate needs updating.
