### ISSUE TITLE
Clicking a block with food in your hand forces you to eat

### ISSUE THREAD

**Issue by DelxHQ** [GeyserMC/Geyser#2664]
### Describe the bug

When you click a block with food in your hand, it forces me to eat the food. I believe this is happening due to the Java server thinking I'm holding down right click.

### To Reproduce

1. Give yourself food.
2. Hold the food in your hand.
2. Click a block.

### Expected behaviour

You don't eat anything when clicking blocks.

### Server Version and Plugins

This server is running CraftBukkit version 3334-Spigot-a5dea1c-a008701 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT)

Plugins (4): Harbor, floodgate, ProtocolLib, Geyser-Spigot

### Geyser Dump

https://dump.geysermc.org/xuz8giyUzgyviI9SmxseSU55uchXDzao

### Geyser Version

2.0.0-SNAPSHOT (git-master-295e716)

### Minecraft: Bedrock Edition Version

1.18

**Comment by DelxHQ** [comment]
Can reproduce this everytime on touch controls.

**Comment by Camotoy** [comment]
I'm unable to replicate with Paper 1.18.0. No ProtocolLib. Yes, I am hungry.

**Comment by DelxHQ** [comment]
@Camotoy Equiping a shield causes the issue to happen more it seems. I couldn't produce it everytime eating bread, but uncooked potato I was able to reproduce it over and over again.

**Comment by RednedEpic** [comment]
May have to do with this being a crop food.

**Comment by jackson-57** [comment]
I think this might be the same or related to #1782.

**Comment by RednedEpic** [comment]
> I think this might be the same or related to #1782.

Seems to be the same, yeah. Will close this one in favor of that one.
