### ISSUE TITLE
tnt explosions don't match

### ISSUE THREAD

**Issue by kaaskroketde3e** [GeyserMC/Geyser#267]
**Describe the bug**
if I let a lot of TNT explode, the result will be different on bedrock and java

**To Reproduce**
1. enter a world with a java and bedrock client
2. place a lot of TNT on the java client
3. let it explode

**Expected behavior**
there are no ghost blocks on either side

**Screenshots**
https://imgur.com/a/gKoTvdS

**Server version**
1.15.2 papermc

**Geyser version**
Jenkins
jenkins latest inventory branch

**Bedrock version**
The version of your Minecraft pe
1.14.30

**Additional context**

**Comment by RednedEpic** [comment]
Superseded by #399.
