### ISSUE TITLE
Connect bedrock server through java editon

### ISSUE THREAD

**Issue by KaptanINO** [GeyserMC/Geyser#2673]
### What feature do you want to see added?

Connecting Bedrock Editon servers through java edition.

### Are there any alternatives?

I searched but I found nothing.

**Comment by Jens-Co** [comment]
Hello there, This is not something we are planning to create. Do know that there already a project (https://github.com/THEREALWWEFAN231/TunnelMC) which is an non active fabric mod. I will close this issue for now, thanks anyway:)

**Comment by Chew** [comment]
Also a duplicate of #2274
