### ISSUE TITLE
Player Tag prefixes don't reset color and style with &f

### ISSUE THREAD

**Issue by Hipopotofobia** [GeyserMC/Geyser#2674]
### Describe the bug

When using luckperms and TAB to set Vault prefixes on player tags above their head, the &f color code does not set the players name to white and non-bold
![Minecraft 12_6_2021 10_51_30 AM](https://user-images.githubusercontent.com/35430382/144880632-1a6556a7-262d-4afd-8363-326a62b6fbe1.png)
d.

### To Reproduce

Add luckperms and TAB or any other combo of plugins to make prefixes above player's heads.

My specific prefixes are set to:
prefix.1.#e0548b&lCreator &f

### Expected behaviour

The player name should be non-bold and white

![image](https://user-images.githubusercontent.com/35430382/144880869-910d9fe5-336d-4203-8569-807e0daf70ac.png)

### Screenshots / Videos

![Minecraft 12_6_2021 10_51_30 AM](https://user-images.githubusercontent.com/35430382/144880996-4ac5696c-7e05-49ab-a0ee-2ea575743fea.png)
![image](https://user-images.githubusercontent.com/35430382/144881006-90fab69f-0854-40b2-8c68-a007db19b40b.png)

### Server Version and Plugins

06.12 11:11:50 [Server] INFO This server is running Paper version git-Paper-"e04368045" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
06.12 11:11:50 [Server] INFO You are 814 version(s) behind

### Geyser Dump

https://dump.geysermc.org/gzo1e5T3c1Y4LXQymiuzrWmvSlYvwPep

### Geyser Version

2.0.0-SNAPSHOT (git-master-70ec77b) (Java: 1.18, Bedrock: 1.17.30 - 1.18.0)

### Minecraft: Bedrock Edition Version

1.18.0

**Comment by lukeeey** [comment]
This is because §f makes the text white, §r (&r) resets the formatting and color

**Comment by Camotoy** [comment]
Reopening; slight confusion on the subject of the issue.

**Comment by ofunny** [comment]
I can reproduce the problem. I'm using `tagprefix: '&7[&6premium&7] &6'` for example to show the rank in front of the user tag and end it with &6. 

Java clients show for each name (above the player) the correct colour while Bedrock clients seem to use a different colour. The wrong name colour however is not random – more like a wrong mapping?  &3 for example remains the same colour, while most other colours translate wrong.

I'm still not totally sure if this is a Geyser issue or a "Tab" plugin issue. On the other side, the problem does not appear in Java clients.


![name_color_bug](https://user-images.githubusercontent.com/9803838/144919990-e2bf8191-6cd0-43c2-986e-cb828faa673f.png)

Geyser dump: https://dump.geysermc.org/R4oOhWV9oXkVA4eNrC0AOFMS810GhIFP
TAB plugin: v3.0.0 (https://www.mc-market.org/resources/14009/)
