### ISSUE TITLE
Bedrock client crash with GUI 2FA plugins enabled

### ISSUE THREAD

**Issue by jondycz** [GeyserMC/Geyser#2677]
### Describe the bug

When joining a server that runs 2FA plugins (PinPrompt, AdvancedLogin - those are not plugins for offline mode! It is 2FA to protect staff accounts on online mode servers), the bedrock client crashes (tried on Bedrock for windows 10 and bedrock for Android). Console just shows that the client disconnected with no errors.

The plugin behavior is to only open the user inventory and modified items within it. Rarely the client doesn't crash. That could be due to the packets containing the opening inventory event are sent before the game fully connects to the server, game gets confused how the user is opening their inventory when the game is still in a loading screen. Ignoring those packets before the client fully joins the server could be a solution.

### To Reproduce

1. Install geyser and PinPrompt or AdvancedLogin
2. Join the server through bedrock client
3. Bedrock client crashes.

### Expected behaviour

Bedrock client doesn't crash and opens inventory UI with modified items (user clicks items to type in the pin)

### Server Version and Plugins

git-Paper-32
- geyser MC
- PinPrompt

### Geyser Version

2.0.0-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.40, 1.18.0

**Comment by Camotoy** [comment]
It appears both plugins are paid - though I see this as a plausible issue. If someone finds a free plugin that exhibits the same issue, I'll test.
