### ISSUE TITLE
New settings

### ISSUE THREAD

**Issue by alexey267** [GeyserMC/Geyser#2679]
### What feature do you want to see added?

Add in settings: disable Xbox live check.  Because of it, it is not always possible to enter the server (most often, but a high ping comes in)

**Comment by Chew** [comment]
This has been suggested dozens of times and the answer has been and remains to be: we will not be implementing this.

> This is not something that Geyser intends to fix. Xbox Live accounts are free.

> If this is for piracy, Geyser does not support piracy. Please buy the game and support Mojang.

**Comment by alexey267** [comment]
mmm .. class why bought a license without a clue (suffer)
