### ISSUE TITLE
FloodgateCP and proxy support.

### ISSUE THREAD

**Issue by BearLeonLight** [GeyserMC/Geyser#2683]
### What feature do you want to see added?

I hope I can add not an option, just use the API.
Because I currently have floodgateCP installed on the server, but he needs GeyserMC API.
My server structure is to connect to the server through a proxy (BC).
This will invert my back-end server occupies a port or display an error when the same port is set.
I hope that it can only load and start, but not operate any content, and only provide APIs to other plug-ins.

### Are there any alternatives?

I currently only have to let him keep the error at startup or change the port.
But this is not ideal.

**Comment by Camotoy** [comment]
FloodgateCP appears to only require Floodgate, which can be installed on the backend servers of a proxy: https://github.com/GeyserMC/Floodgate/wiki/Setup-and-Usage
Hope that helps!

**Comment by BearLeonLight** [comment]
> FloodgateCP appears to only require Floodgate, which can be installed on the backend servers of a proxy: https://github.com/GeyserMC/Floodgate/wiki/Setup-and-Usage. You do not need to install Geyser on the backend servers. Hope that helps!

I tested it at the beginning and it didn't work.

**Comment by BearLeonLight** [comment]
```Java
import org.geysermc.cumulus.SimpleForm;
import org.geysermc.cumulus.response.SimpleFormResponse;
```
https://github.com/MangoSwirl/FloodgateCP/blob/master/src/com/mshuman/floodgatecp/Util.java

**Comment by Camotoy** [comment]
These classes are provided in Floodgate.

**Comment by BearLeonLight** [comment]
> These classes are provided in Floodgate.

I just tested it. If I don't install geysermc and only install FloodgateCP, it doesn't work.

**Comment by BearLeonLight** [comment]
![image](https://user-images.githubusercontent.com/52900334/145355717-ca23a4f2-dae2-4475-b3d9-4b46c59fa8dd.png)

**Comment by BearLeonLight** [comment]
I found it, just remove the relevant dependencies, and I will report back to the author.
