### ISSUE TITLE
Box UI

### ISSUE THREAD

**Issue by whes1015** [GeyserMC/Geyser#2684]
### Describe the bug

When the player stays away from the box due to various reasons and does not close the box, it will cause all the screen UI to disappear

### To Reproduce

1. Open box
2. Attach the player,who opening the box.(Don't close the box)
3. Problem happened

### Expected behaviour

The Box UI should be closed,when player keep away the box

### Geyser Version

All Versions

### Minecraft: Bedrock Edition Version

All Versions

**Comment by whes1015** [comment]
This is an error that greatly affects the gaming experience. Not only boxes are affected, but also hoppers, ephemera boxes, end boxes, etc. I don’t understand why no one reports this problem? Or is this a problem that cannot be repaired?

**Comment by MrZomka** [comment]
What box? A shulker box?

**Comment by whes1015** [comment]
> What box? A shulker box?

Not just shulker boxes, as I said, any container similar to box UI, including funnels, has this problem

**Comment by onebeastchris** [comment]
Is this still an issue?

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
