### ISSUE TITLE
Player death

### ISSUE THREAD

**Issue by whes1015** [GeyserMC/Geyser#2685]
### Describe the bug

The player can receive damage when loading the world for the first time, or when respawning, which results in repeated deaths

### To Reproduce

1. A survival map
2. A player join game,and there have monster near by the player

### Expected behaviour

Player death when loading map,I want to make a plugin to solve this problem,use setNoDamageTicks to give player a temporarily invincible effect,then when player move (PlayerMoveEvent) remove this effect,but GeyserMC will teleport player when player finish map loading

### Geyser Version

All Versions

### Minecraft: Bedrock Edition Version

All Versions

**Comment by KalixWolf** [comment]
Players on my Purpur server die twice

**Comment by Chew** [comment]
Duplicate of your own issue (#2686)? As we said, duplicate of #2668. Thanks for reporting anyways!

**Comment by Konicai** [comment]
whes1015's issue is different, they are describing the player not being able to interact when loading in and being killed by mobs repeatedly. 

@whes1015 Please provide a geyser dump by running `/geyser dump` and a screen recording of the issue happening, if possible

**Comment by whes1015** [comment]
> whes1015's issue is different, they are describing the player not being able to interact when loading in and being killed by mobs repeatedly.
> 
> @whes1015 Please provide a geyser dump by running `/geyser dump` and a screen recording of the issue happening, if possible

https://dump.geysermc.org/QHiyayMejc7F6iFS33DUyIqs9vE1XBxt

**Comment by whes1015** [comment]
> whes1015's issue is different, they are describing the player not being able to interact when loading in and being killed by mobs repeatedly.
> 
> @whes1015 Please provide a geyser dump by running `/geyser dump` and a screen recording of the issue happening, if possible

By the way, "repetition" is a very important concern. If players are born in the wild at night in survival mode, they will inevitably fall into a vicious cycle of constant rebirth. No matter how good the performance of Bedrock Edition equipment, it seems that they cannot be avoided.

**Comment by onebeastchris** [comment]
Is this still an issue?

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.

**Comment by SmYt-INDIA** [comment]
Yes Its Happening with me often

**Comment by SmYt-INDIA** [comment]
https://dump.geysermc.org/65MTz4wihTZr0T2mw8jTDFN7YDWaRDdE
My dump

**Comment by ayaan2048** [comment]
I have a solution for this: [(https://github.com/ayaan2048/respawnglitchfix-instantrespawn2)]
