### ISSUE TITLE
Death UI

### ISSUE THREAD

**Issue by whes1015** [GeyserMC/Geyser#2686]
### Describe the bug

When the player dies, he will receive two death screens(not always)

### To Reproduce

1. A player death

### Expected behaviour

Send death UI only one time

### Geyser Version

All Versions

### Minecraft: Bedrock Edition Version

All Versions

**Comment by whes1015** [comment]
This problem look like someone already opened,but I report it fifteen days ago on https://github.com/GeyserMC/Geyser-Fabric/issues/39

**Comment by davchoo** [comment]
Duplicate of https://github.com/GeyserMC/Geyser/issues/2668. Thanks for reporting anyways!
