### ISSUE TITLE
Add custom model for bedrock

### ISSUE THREAD

**Issue by tbvns2** [GeyserMC/Geyser#2689]
### What feature do you want to see added?

Hello
I have a request : 
**Bedrock player** can't have optifine. So they can't have **custom model** for a entity with a **spesific name**.
can you please do a thing that can transform a java entity with a specific name into a  **custom bedrock entity** 
For the cofiguration file you can just do somthing like  _(entity type: ,entity name: ,custom entity:)_
Thank if you add it (and thank anyway fot this amazing plugins)

### Are there any alternatives?

Bedrock texture pack

**Comment by Konicai** [comment]
Progress for this is effectively tracked here: https://github.com/GeyserMC/Geyser/issues/210

**Comment by tbvns2** [comment]
no i dont want to have a pack translation
I want to have a custom entity replace the java entity whith another bedrock addon entity so we can use custom model

**Comment by Creeperz653** [comment]
> no i dont want to have a pack translation
> 
> I want to have a custom entity replace the java entity whith another bedrock addon entity so we can use custom model

Read the post mentioned
