### ISSUE TITLE
Entity dismount

### ISSUE THREAD

**Issue by tbvns2** [GeyserMC/Geyser#2691]
### Describe the bug

When a Bedrock player try to mount on a entity, it say somthing like **### _actin.hint.exit.(entityname)_**

### To Reproduce

1. connecte whith geyser
2. try to mount on somthing

### Expected behaviour

bedrock player can mount on entity

### Screenshots / Videos

![here](https://cdn.discordapp.com/attachments/706452413422501911/918188094505771059/Screenshot_2021-12-08-18-11-21-653_com.mojang.minecraftpe.jpg)

### Server Version and Plugins

Spigot:1.8.8-RO.1-SNAPSHOT
Waterfall:1.18-R0.1-SNAPSHOT:ab927be:462

Spigot:
WorldEdit, PlaceholderAPI, MicroJump, EasySetSpawn, ViaVersion, NametagEdit, HolographicDisplays, WorldGuard, LuckPerms, HolographicExtension, CrazyCrates, Vault, Citizens, ChestCommands, Essentials, UltraCosmetics, JumpPads, EssentialsChat, TAB, CommandNPC, ItemJoin, TitleManager
Waterfall:
BungeeHub, floodgate, Geyser-Bungeecord ,LuckPerms, PartyAndFriand

### Geyser Dump

https://dump.geysermc.org/oob9QBL9fZDZneuZovZiJmkbRdtbuVh9

### Geyser Version

2.0.2-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.18x

### Additional Context

It dosen't work
I try on every entity
If you want to try it go on pe.prisme-network.xyz (not an ad)

**Comment by Camotoy** [comment]
I'm fairly certain this is a message coming from Bedrock. Not sure if there's much we can do to get around it except a resource pack which defines this message correctly for all entities.

**Comment by RednedEpic** [comment]
This is due to a missing translation in the client locale, so not much we can do about this. Can be resolved in GeyserOptionalPack however. Closing as it is nothing Geyser on its own can solve.
