### ISSUE TITLE
Stonecutter was unusable in bedrock

### ISSUE THREAD

**Issue by FiresoftGH** [GeyserMC/Geyser#2692]
### Describe the bug

As the title said, the UI could be opened but the crafting bugged out and does not work (didn't consume the items).

### To Reproduce

Just use the stone cutter

### Expected behaviour

The stone cutter can not make stone related items

### Geyser Version

Lastest

### Minecraft: Bedrock Edition Version

1.18

**Comment by Camotoy** [comment]
Please actually try with the latest version of Geyser, and if the issue still persists, please provide a Geyser dump. We just recently fixed a similar bug. Thank you!
