### ISSUE TITLE
I want help Because when I am with version 1.16.4 it tells me that I have to install something better, look at the problem and I need help Pls

### ISSUE THREAD

**Issue by Missa13** [GeyserMC/Geyser#2696]
### Describe the bug

Please help me. It is because when I activate the server I get an error that in some days I use a GeyserMC plugin Which is to play with cell phone friends and when I go to the latest version it goes great but when I go to a version like 1.16.4 or 1.14.4 oh anyone tells me "Install a different version of the plugin 'Geyser-Spigot" and another that says "Delete the file' plugins / Geyser-Spigot.jar" I still don't know but I need help please someone help me :C

### To Reproduce

963

### Expected behaviour

My friends and I had planned this a long time ago until the error occurred, since without the geyserMC we would not be able to play, so that's why we ask for help please

### Screenshots / Videos

I couldn't but it told me to install "Delete the file 'plugins / Geyser-Spigot.jar"

### Server Version and Plugins

1.16.4

### Geyser Dump

Idk

### Geyser Version

963

### Minecraft: Bedrock Edition Version

1.16.4 and the pc 1.16.4

### Additional Context

I want to play with my friends

**Comment by Jens-Co** [comment]
Hello there, Can you please provide us with some console logs ?
You can upload logs with this link (https://mclo.gs) and paste the link in here.
And maybe a print screen of the client when you are trying to join the server.

Thanks
Jens

**Comment by Missa13** [comment]
> Hola, ¿podría proporcionarnos algunos registros de la consola? Puede cargar registros con este enlace ( https://mclo.gs ) y pegar el enlace aquí. Y tal vez una pantalla de impresión del cliente cuando intenta unirse al servidor.
> 
> Gracias Jens

I don't know what to do Lord puts this on m
![chrome_P30NYpC8yA](https://user-images.githubusercontent.com/94656418/145773298-f35b3ba3-3d95-40e2-84b3-018e027b181b.png)
e

**Comment by Jens-Co** [comment]
I will need some full logs, otherwise im unable to help you out. pase the wole latest.log file into mclo.gs and give us the link in here :)

**Comment by Missa13** [comment]
> Necesitaré algunos registros completos, de lo contrario no puedo ayudarlo. copie el archivo wole latest.log en mclo.gs y denos el enlace aquí :)

Is this safe? , because it seems a bit Malicious No offense

**Comment by Chew** [comment]
Geyser needs Java 16. You'd probably need to upgrade to the latest Paper 1.16.5 build (which is fully compatible with 1.16.4) as well as Java 16. Though, we'd recommend simply bumping to 1.17 since 1.16.5 is no longer supported by Paper, but this is up to you.

**Comment by Missa13** [comment]
I am from Aternos

**Comment by Missa13** [comment]
But is there a way to install 1.16.5 for mobile?
