### ISSUE TITLE
Chunk Loading On Join

### ISSUE THREAD

**Issue by deadbushmc** [GeyserMC/Geyser#2698]
### Describe the bug

So okay it doesn't happen but it happens sometimes and it's annoying. Since when you join server the chunks don't wanna load and all you see is void and yu have to rejoin for it to work

### To Reproduce

Join the server it happens sometimes randomly

### Expected behaviour

the world/chunk won't load and all you see is void and you gotta rejoin

### Server Version and Plugins

1.18 purpur

### Geyser Version

Latest

### Minecraft: Bedrock Edition Version

1.18

**Comment by Jens-Co** [comment]
Does this issue still happen on the latest Geyser version?

**Comment by Chew** [comment]
There's not enough information here to warrant keeping this open. If you do reproduce it, please make a new issue and fill out _everything_ _completely_.
