### ISSUE TITLE
Config option to disable mainthreadchunks

### ISSUE THREAD

**Issue by naturecodevoid** [GeyserMC/Geyser#2699]
### What feature do you want to see added?

On some servers with multiple cores, this causes a lot of unintended side effects and makes the game unplayable for bedrock players. I would like to be able to disable main thread chunks and revert to the old behavior, while still allowing the latest versions of minecraft to join. Is this possible?

### Are there any alternatives?

None so far, it may be possible to use ViaBackwards and an older version of Geyser but that would stop newer Bedrock players from joining.

**Comment by Camotoy** [comment]
I would not want to add a config option to disable behavior because of bugginess on our end. I'm not sure why multiple cores would come into play - we're using less threads now, not more. I'd rather you describe the issues you're having, along with replication steps, and we can address each.

**Comment by naturecodevoid** [comment]
For my situation, using more threads would be better because I have 4 cores on my server. This might just be an issue of not having a powerful enough server but when TPS gets low, bedrock players get what's happening on the java server around 1/4 speed and this causes desync and makes the server unplayable. This never happened when we used geyser in 1.16 or 1.17, before mainthreadchunks was merged.

**Comment by Camotoy** [comment]
Hmm, OK. Could you send a Spark report of this happening?

**Comment by naturecodevoid** [comment]
Sure, might take me a little while to replicate the lag

**Comment by naturecodevoid** [comment]
If you're wondering what's causing the lag, afaik it's 1. the amount of players on the server and 2. all of them loading chunks

I'll still try to replicate the lag and send a Spark report but it might take a few hours.

**Comment by naturecodevoid** [comment]
I have the link, do you think there's an alternative way for me to send it to you?

**Comment by Camotoy** [comment]
Here is fine, or you can DM me on Discord.

**Comment by naturecodevoid** [comment]
Thanks, I think some players are still having issues but I'll close this for now.

**Comment by Camotoy** [comment]
I took a look at their Spark plugin and chunks weren't even in the profile. The big issue - which lines up with the TPS issue - was us trying to get block data from the server. The performance regression was likely from no NMS-based world manager for 1.18. We can likely improve performance here regardless by batching requests somehow.
