### ISSUE TITLE
Client crashes immediately after successful login

### ISSUE THREAD

**Issue by ssterling** [GeyserMC/Geyser#27]
After successful authentication using the latest build from the `chunks` branch (bd8a00b), Minecraft crashes on the client's side whilst the server spans "Sent chunk packet!" till it says the user timed out.

I've experienced this on both the latest edition of MCBE on both Android and iPhone.

**Comment by Rxhys** [comment]
The chunks branch is a work in progress and is not stable. I think that it will be moved to the master branch when it is ready for use.

thanks

**Comment by Wesley-Chan-Hyperion** [comment]
What do you expect  it doesn't work and if does you still can't move because the player move packet isn't implemented

**Comment by Wesley-Chan-Hyperion** [comment]
@RednedEpic close this

**Comment by ssterling** [comment]
oops
