### ISSUE TITLE
About Resource Packs

### ISSUE THREAD

**Issue by ookami0104** [GeyserMC/Geyser#2702]
### What feature do you want to see added?

Nice to meet you.

I'm Japanese and I'm using a translator, so the text may not be correct.

The question I want to ask is how to apply the resource pack of "Magic Plug-in".

You can find it at https://rtm516.github.io/ConvertJavaTextureToBedrock/.
I was told that 1.17 is not supported even if I use this.
What should I do?

I'm waiting for your reply.

### Are there any alternatives?

![image](https://user-images.githubusercontent.com/80665012/146179401-94d5c352-ccc0-4a50-b7a8-284e678790b4.png)

**Comment by Konicai** [comment]
You'll have to either find a converter that supports 1.17 or 1.18 (whichever version you need), or manually convert the resource pack to Bedrock Edition format. Any Bedrock Edition resource packs you put in the `packs` folder are sent to the client
