### ISSUE TITLE
PlotSquared world error?

### ISSUE THREAD

**Issue by xs7884** [GeyserMC/Geyser#2703]
### Describe the bug

The server is a Java based 1.16.5 server.
In the normal world, the movement of BE users is very smooth,
Movement is choppy in worlds created with the PlotSquared plugin. (frames seem to keep dropping, not lag)
When walking on the ground, You can even only move back and forth!!(4 directions available when flying)
(Personally, I've never put something running on each movement event)

### To Reproduce

Simply...
One world is the default world,
A world can be created as a world in the PlotSquared plugin.

### Expected behaviour

...

### Server Version and Plugins

git-paper-790 (MC: 1.16.5)

### Geyser Version

Geyser-BungeeCord (At the time of inquiry, the most recent version)

### Minecraft: Bedrock Edition Version

v1.18.2

**Comment by Camotoy** [comment]
Have you tried with a clean PlotSquared world? It could be something on someone's plot lagging Bedrock?

**Comment by DJelly4K** [comment]
> The server is a Java based 1.16.5 server.
> In the normal world, the movement of BE users is very smooth,
> Movement is choppy in worlds created with the PlotSquared plugin. (frames seem to keep dropping, not lag)
> When walking on the ground, You can even only move back and forth!!(4 directions available when flying)
> (Personally, I've never put something running on each movement event)

My server also has this problem, the version is 1.17.1, I also think there is something on someone's plot lagging Bedrock, but i don't know how to fix it
