### ISSUE TITLE
Sculk sensors do not display properly

### ISSUE THREAD

**Issue by G2-Games** [GeyserMC/Geyser#2705]
### Describe the bug

Sculk sensors display as a dirt block texture with "Update" written on it

### To Reproduce

1. Create world with experimental settings
2. Join with a bedrock client
3. Place sculk sensor on a Java client

### Expected behaviour

Sculk sensors display normally

### Screenshots / Videos

![Sculkglitch](https://user-images.githubusercontent.com/72430668/146291626-ffccbddf-fbc6-439f-a8ac-3ddbc0ee899e.png)

### Server Version and Plugins

This server is running Paper version git-Paper-68 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 1c779c2)

Plugins:
- DiscordSRV 1.24.0
- floodgate 2.1.0-SNAPSHOT
- GeyserSkinManager 1.6
- Hat 1.4.2
- Multichat 1.9.6
- Plan 5.4

### Geyser Dump

https://dump.geysermc.org/r3nqGRefCz8fKlXEzIvLTsaWFWwBaAmd

### Geyser Version

2.0.0-SNAPHOT (git-master-90442a8)

### Minecraft: Bedrock Edition Version

1.18.2.03

**Comment by Camotoy** [comment]
Sculk sensors are locked behind the experimental toggle still in 1.18; that is not enabled for Bedrock clients. I'll have to see if there are any repercussions to enabling it.

**Comment by AnhNguyenlost13** [comment]
Is it possible to add an option on the config to allow those blocks (enabling the experimental toggles on Bedrock)?

**Comment by Camotoy** [comment]
We're going to just wait out until 1.19 at this point. Thanks!
