### ISSUE TITLE
Issue with plugins that use GUI when pressing an icon

### ISSUE THREAD

**Issue by bubbakadriu** [GeyserMC/Geyser#2707]
### Describe the bug

Hi Geyser Support, i have a good question and its one of the main problems i have (apart from custom model/head data)

With alot of plugins that use gui, you have to press the icon then press an empty spot in the gui to open the next menu

Is there a way to fix this so pressing the icon immediately opens the next gui menu?

### To Reproduce

1. Download a plugin that uses gui, for example EconomyShopGUI
2. Press an icon to open one of the shop categories.
3. Notice that you have to press the icon then press an empty spot for the next category to open.

### Expected behaviour

Pressing an icon should immediately open the next category

### Server Version and Plugins

latest

### Geyser Version

latest

### Minecraft: Bedrock Edition Version

1.17

**Comment by AnhNguyenlost13** [comment]
This is intentional for mobile Bedrock Minecraft. Just click to any other empty slot

**Comment by Chew** [comment]
To my knowledge, Bedrock doesn't send anything when you simply click on it (at least on mobile). 

Not sure this is something we can fix.

**Comment by Yucareux** [comment]
Talking about that plugin, you cant right click on an item to sell it. It takes you to the buy screen.

**Comment by Chew** [comment]
That's also Bedrock behavior, there is no way to send a "right click."

**Comment by Cal3y** [comment]
Had a same issue, couldn't figure much, but I tested EssentialsX's "/invsee [player]" command, which uses chest gui menu and with asigned permission "essentials.invsee.preventmodify" (prevents picking up items even for op users on java). It works on pocket edition and any bedrock device I tested - you can't pick up or throw items on the ground. If someone can take a look at this, it would solve a lot actually. For now I had to limit using gui menus and offer alternative chat-based commands for mobile users.

**Comment by Camotoy** [comment]
Can you send a video?

**Comment by Cal3y** [comment]
My apologies, I meant to post this on another issue. Deleting my previous comment.

**Comment by RednedEpic** [comment]
Bedrock client limitation. Closing.
