### ISSUE TITLE
Item cannot place properly in the column of inventory or GUI

### ISSUE THREAD

**Issue by QiuChen-Developer** [GeyserMC/Geyser#2709]
### Describe the bug

Item cannot place properly in the column of inventory or GUI then appearing small "ghost block". That is very annoying.

### To Reproduce

See the Screenshots below.

### Expected behaviour

Expecting to place the item properly in the column of inventory.

### Screenshots / Videos

![Record_2021-12-16-14-11-43_5c8300b655012b1930f2e0a7b81bf6a9 (1)](https://user-images.githubusercontent.com/51996408/146488892-0bd7e2fd-1b72-473a-b963-4f07be78504c.gif)

### Server Version and Plugins

Proxy Server: This server is running Waterfall version git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:bf5e3c4:466 by md_5
Bukkit Server: Previous version: git-Purpur-"9a7a4dc" (MC: 1.17.1)
Plugins (51): AACAdditionPro, BlockLocker, BungeeGuard, ChatControlRed, Citizens, CMI, CMIEInjector*, CMILib, CommandPanels, CoreProtect, DamageIndicator, DiscordSRV, EasyBackup, eco, EcoEnchants, EcoEnchantsGUI, floodgate, FloodgateCP, HolographicDisplays, InventoryRollbackPlus, Jobs, JumpPads, Lottery, LuckPerms, Marriage, mcMMO, Minepacks, MMOItems, MMOMana, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, MythicLib, MythicMobs, PlaceholderAPI, PlayerPoints, PluginManager, ProtocolLib, QuickShop, Residence, ResourceWorld, SelectionVisualizer, ShopGUIPlus, Shopkeepers, Spartan, TAB-BukkitBridge, TradeMe, UltimateTimber, Vault, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/QYw5mNS8UA6I713jgewIjpLQ0MNjreys

### Geyser Version

Geyser version 2.0.0-SNAPSHOT (git-master-90442a8) (Java: 1.18 - 1.18.1, Bedrock: 1.17.30 - 1.18.0)

### Minecraft: Bedrock Edition Version

1.18

### Additional Context

This happens on the Android platform, in windows10 edition it works fine.

**Comment by QiuChen-Developer** [comment]
Closed due to no responses for a long time.

**Comment by RednedEpic** [comment]
Closing due to lack of followup + further replication.
