### ISSUE TITLE
Fabric serverside support

### ISSUE THREAD

**Issue by DraxxisGH** [GeyserMC/Geyser#271]
**What feature do you want?**
A Fabric mod jar that works similar to the plugin, that works preferably with online servers.
**Alternatives?**
None that I know of, the fabric bukkit server jar could be a potential solution in the future though.

**Comment by Heath123** [comment]
> **What 
> **Alternatives?**
> None that I know of, 
You can just use standalone Geyser 
> that works preferably with online servers.
I think you're talking about Floodgate, so it might be better to post this there. You can always just use BungeeCord with Floodgate

**Comment by Tim203** [comment]
In Discord he said that he wanted to be able to use Geyser on Fabric + Lithium and that Fabric + Bukkit might be a potential solution.

**Comment by Heath123** [comment]
> In Discord he said that he wanted to be able to use Geyser on Fabric + Lithium and that Fabric + Bukkit might be a potential solution.

Why not just use standalone though? 
By the way I think there should be a Fabric version but I'm just thinking of alternatives ("None that I know of"). As far as I know the plugin version doesn't do anything extra.

**Comment by Tim203** [comment]
> Why not just use standalone though?
I did also say that, but I understand it since it requires a separate server, and not everyone has that.

**Comment by Heath123** [comment]
> > Why not just use standalone though?
> > I did also say that, but I understand it since it requires a separate server, and not everyone has that.

Oh, it's a hosted server 
Those don't always work with Geyser anyway though

**Comment by DoctorMacc** [comment]
There is now a Fabric version of Geyser at https://github.com/GeyserMC/Geyser-Fabric .

**Comment by Heath123** [comment]
Isn't it getting merged into main Geyser?

**Comment by DoctorMacc** [comment]
https://github.com/GeyserMC/Geyser/wiki/Geyser-Fabric#why-a-separate-repository

**Comment by Heath123** [comment]
Oh, OK.
