### ISSUE TITLE
/stopsound doesn't work for resource pack sounds

### ISSUE THREAD

**Issue by some1chan** [GeyserMC/Geyser#2710]
### Describe the bug

When using `/stopsound` with a specified source (or with a *), the sound will not stop.

### To Reproduce

Run the following commands on Bedrock:
1. `/playsound record.pigstep record @p`
2. `/stopsound @p record record.pigstep`

### Expected behaviour

Pigstep should stop playing, after running the `/stopsound` command in the repro section.

### Geyser Dump

https://dump.geysermc.org/haIF2KPMWKe4o7z0yY0ZzHsZtTRtn98D

### Geyser Version

2.0.0-SNAPSHOT (git-master-90442a8)

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

According to #1768, this was resolved, but maybe it broke (possibly around #2493?).

Coincidentally with #2493, I'm also using [JukeboxExtended](https://www.spigotmc.org/resources/jukebox-extended-add-custom-music-disc.76963/) to play custom music, and has gotten the music to play cross-platform. While getting this to work, I believe to have rediscovered the bug.

Extra notes: `/stopsound @p` does stop sounds properly, but `/stopsound @p * record.pigstep` doesn't.

**Comment by Camotoy** [comment]
I'm not marking this as confirmed, but I was able to replicate your behavior. I think I know what's up.
`record.pigstep` isn't a valid Java Edition sound. The format should be `minecraft:music_disc.pigstep`, which *is* a valid sound, and the Cat sound plays and stops with this format. But Pigstep doesn't have this mapping on our end, so it just passes on the sound.

**Comment by Camotoy** [comment]
I updated the mappings so `/playsound` will correctly start and stop Pigstep. Let us know if this fixes your issue!

**Comment by some1chan** [comment]
Although that fixed the repro, it unfortunately didn't fix my issue. Turns out, my actual issue was that Bedrock resource pack sounds could be played, but couldn't be stopped without stopping all sounds. Is that something that could be fixed?

### To Reproduce

1. [Download this example pack](https://anonfiles.com/rcP8vcm8w6/Test_mcpack), put it in the packs folder, then restart.

> This pack contains a file named example.ogg, along with the required `sound_definitions.json` data. This should make it playable in Minecraft via command.

2. Join the server on Bedrock, and run the following commands:

-  `/playsound example record @p`
- `/stopsound @p record example`

### Expected behavior

The example sound should stop playing, after running the last command.

### Additional Context

I definitely didn't do my due diligence of creating a fresh Paper server, and testing the pack. I only tested an already-existing server with different data, and with a Bedrock single-player world to see if the pack worked. Let me know if you have trouble reproducing it. Thanks!

**Comment by some1chan** [comment]
Sorry for the bump. Any updates on this?

**Comment by BoyStijn** [comment]
Same can be said about playsound from java if i run /playsound minecraft:music_disc.pigstep record @a bedrock players wont hear the audio

**Comment by MRuNanM** [comment]
I'm in the same situation. The resource pack sound does not stop. I hope it's resolved soon!

**Comment by Camotoy** [comment]
This issue is probably resolved now. If it isn't, let us know. Thanks!
