### ISSUE TITLE
Fishing rod pulls player forward

### ISSUE THREAD

**Issue by AxlRose-RX** [GeyserMC/Geyser#2715]
### Describe the bug

When using the fishing rod by a Bedrock player, he gets pulled forward.

### To Reproduce

1. Go to the nether
2. Fishing rod to a Ghast
3. If in a high place, you get pulled by the ghast a few blocks forward and fall into your death or lava!

### Expected behaviour

Should not pull the player forward

### Server Version and Plugins

Previous version: git-Purpur-1443 (MC: 1.18.1)

Plugins (28): CoreProtect, DiscordSRV, Essentials, EssentialsSpawn, floodgate, GeyserSkinManager, GriefPrevention, InventoryRollbackPlus, LuckPerms, MineSync, MobLimit, MyCommand, OpenInv, PlaceholderAPI, ProtocolLib, spark, TAB-Bridge, Vault, VentureChat, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, Vulcan, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

https://dump.geysermc.org/rrlyfVjTlUYokPQZzvKLCfu8eRTu5C0E

### Geyser Version

2.0.0-SNAPSHOT (git-master-222c9d7)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by Camotoy** [comment]
Fixed in 15522aed52b515b133f2866788ba8cd5731cd3a1.
