### ISSUE TITLE
Global player list option on Bungee Cord

### ISSUE THREAD

**Issue by AxlRose-RX** [GeyserMC/Geyser#2716]
### What feature do you want to see added?

I would love to make the player list global on a bungee server, maybe with an option on config file to enable. Example:

Not so experienced Geyser player joins the hub, sometimes see nobody on the player list and leaves. Players are most likely spread on the different servers: Bed Wars 4, Survival 8, Creative 3, total of 15 players.

### Are there any alternatives?

Not really.

**Comment by Chew** [comment]
This is definitely out of the scope of Geyser. You'd probably want a plugin to do this for you, maybe [BungeeTabListPlus](https://www.spigotmc.org/resources/bungeetablistplus.313/) but keep #171 in mind. I don't even know if plugins can even access the list like this...

**Comment by Camotoy** [comment]
Unless other developers would like to add input, I'm not sure if we can really mess with this. If you want to add in Java players then this definitely crosses the line on what Geyser should be providing. I would recommend looking into another plugin to implement this. (Also, wouldn't Java players have this same issue?)

**Comment by AxlRose-RX** [comment]
Java players won't suffer from this, because Java players have a tab list so for them there is not issue, look at the picture:

![image](https://user-images.githubusercontent.com/10159672/146697502-65cd1a84-4129-4cd4-8570-3f7fbb927a62.png)

**Comment by Camotoy** [comment]
Bedrock players should, if I am correct, see all those slots.

**Comment by AxlRose-RX** [comment]
I have no idea how to, I have tried with BTLP in the past and now with TAB, before with BTLP would see tons of fake bedrock players but that was needed with the plugin, thanks God those fake players won't show on TAB now that I did the switch
