### ISSUE TITLE
Items on heads

### ISSUE THREAD

**Issue by LGCoding** [GeyserMC/Geyser#2717]
### Describe the bug

When you put items on a player's head like a stone block it does not show up on bedrock this also applies to the GeyserOptionalPack and armor stands with blocks on their head.

### To Reproduce

1. /item command to put stone on the players head
2. Bedrock players can't see it

### Expected behaviour

The stone block should display over the players head like in java

### Geyser Version

latest

**Comment by Camotoy** [comment]
This is currently a limitation of Bedrock, and it has now been documented on the wiki. If we figure out a way to work around this in the future, we will address it. Thanks anyway!
