### ISSUE TITLE
There will be a mysterious line.

### ISSUE THREAD

**Issue by M1n1don** [GeyserMC/Geyser#2719]
### Describe the bug

When I enter the server, it looks like the image below.

Is this a problem with Geyser?
Or is it a problem with the client?

If it is a problem with Geyser, please let me know the cause and solution.
I couldn't figure it out, so I'll report it as a bug.

### To Reproduce

1. Join the server
2. Occurrence

### Expected behaviour

That nothing will happen.

### Screenshots / Videos

<img src="https://media.discordapp.net/attachments/915857847512891402/922475542823993404/IMG20211220220757.jpg?width=753&height=565">

<img src="https://media.discordapp.net/attachments/915857847512891402/922475880972972052/77.png?width=1189&height=446">

### Geyser Dump

https://dump.geysermc.org/DlK1IkxUGVf9k2FlRtQM9TMwHILpqsQZ

### Geyser Version

2.0.0-SNAPSHOT (git-master-15522ae)

**Comment by AnhNguyenlost13** [comment]
This is more like a Bedrock client bug I think

**Comment by RednedEpic** [comment]
This is a client issue.
