### ISSUE TITLE
Repeated console messages causing large logs and console spam

### ISSUE THREAD

**Issue by OliverP98** [GeyserMC/Geyser#2720]
### Describe the bug

On the proxy that has GeyserMC installed and its outputting exessive amount of issues relating the to the TAB plugin: https://github.com/NEZNAMY/TAB

### To Reproduce

Likely have the tab plugin installed in a proxy configuration and join under GeyserMC

### Expected behaviour

I would expect the exessive amount of logs to be reduced or zero.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/42102786/146779615-8e015899-84e8-4c59-ad65-ed4c3096505e.png)

### Server Version and Plugins

Proxy: Waterfall 468
Server: Paper 243

Tab: 3.0.1v

### Geyser Dump

 https://dump.geysermc.org/L3GuGKxlZaMkGCJMxihwjwjoWVQ4outG

### Geyser Version

2.0.0-SNAPSHOT

### Additional Context

I don't see this is game breaking but annoying for keeping large logs.

**Comment by RednedEpic** [comment]
A scoreboard plugin is sending invalid data. Likely would show similarly inside of the client logs of a Java Edition client. Closing.
