### ISSUE TITLE
Crafting a shield kicks a player 

### ISSUE THREAD

**Issue by Tombspyder** [GeyserMC/Geyser#2721]
### Describe the bug

When a bedrock player attempts to craft a shield within 1.18.1 their game immediately boots them from the server with this error:

https://mcpaste.io/c44fe5d76b968cce

### To Reproduce

1: Join a 1.18.1 java server via geyser
2: Craft a shield

### Expected behaviour

Players can craft a shield and not be kicked

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/88732543/146781436-346e1928-f291-4ac2-a26a-a2383f1cde42.png)

### Server Version and Plugins

This server is running Paper version git-Paper-82 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 8c5be16)
You are running the latest version
Previous version: git-Paper-77 (MC: 1.18.1)

### Geyser Dump

https://dump.geysermc.org/0B99S9RSW5GoKxbP97GWhlADvlzysLhj

### Geyser Version

2.0.0 SNAPSHOT

### Minecraft: Bedrock Edition Version

Any

**Comment by AnhNguyenlost13** [comment]
Say your exact version of your Minecraft client (can be found on the corner)
Also did you use quick crafting?

**Comment by Camotoy** [comment]
This is likely not us - that stack trace is coming from the server. Judging by the wording, something is trying to concurrently access an item and Geyser doesn't touch items at all. Are you sure this doesn't happen with a Java player?

**Comment by Camotoy** [comment]
Yeah, this looks like the same error as https://github.com/PurpurMC/Purpur/issues/797. I'm going to close it unless new information is found. Thanks anyway!
