### ISSUE TITLE
ALLOW_THIRD_PARTY_EARS sends requests for Citizen NPCs and possibly skulls

### ISSUE THREAD

**Issue by james090500** [GeyserMC/Geyser#2722]
### Describe the bug

When ALLOW_THIRD_PARTY_EARS is true, Geyser will send a request everytime a player joins for Citizens NPCs and possibly Skulls but I am unable to test currently

### To Reproduce

1. Make a Citizens NPC
2. Join game

### Expected behaviour

It shouldn't request capes or ears for Citizens NPCs ideally

### Screenshots / Videos

Here are some analytics for the past 24 hours from my site (minecraftcapes.net). As you can see none are real users so this are generated fake UUIDs for Citizens. 

/profile/5b9a3ab16a36291984c15b23196b81aa/ears
8.69k
/profile/8ff478983aec2fb88bdfd5325cc04712/ears
8.57k
/profile/5b27b5e6ef4828bf89b6502fe0ad0616/ears
8.42k
/profile/1ac3ee06eb2f271c8bc6c0b05aa2284f/ears
8.41k
/profile/7fe831fb7d7b2af89606a3c1c08bedc0/ears
8.39k
/profile/78e23fb321942864994a51cdbd0e6ec5/ears
8.33k
/profile/0a9770a50fdf25e39ff46eb45e74b5cc/ears
8.26k
/profile/651b2f7e91a6226d93556b9d73226b11/ears
8.07k
/profile/c2d2241571062766be142eaad5b3a3a5/ears
8.07k
/profile/59d9e22f24e325c6b547dbe553cc4a71/ears
8.07k
/profile/880771de594e2f4aac8037e7922cf566/ears
8k
/profile/ced740ae3ae7290ca76886dc14eb3683/ears
7.98k
/profile/b028ac4d48c62b8f8aaf0d32e65182f0/ears
7.93k
/profile/04754f336a0c2f4dacc1ea239b3a7de1/ears
7.87k

### Geyser Version

2.0.0-SNAPSHOT git-master-90442a8

### Minecraft: Bedrock Edition Version

1.17.30

**Comment by james090500** [comment]
Proposed Fix:

Real Minecraft Players use a version 4 UUID. Citizens use a version 2 and offline/cracked players use a version 3. 

You can probably fix this by doing a 

```
entity.getUuid(),version() == 4
```

Somewhere here. https://github.com/GeyserMC/Geyser/blob/763743a845796e4619ba596b82d4eabb39045448/core/src/main/java/org/geysermc/geyser/skin/SkinProvider.java#L178

Ideally UUID capes probably shouldn't be requested either as if the UUID isn't a real player uuid then nothing will be returned

**Comment by RednedEpic** [comment]
I've just pushed a fix for this on our end. @james090500 can you check that you are no longer receiving these requests on your end with the latest version of Geyser installed?

**Comment by james090500** [comment]
Thanks for the update, I can see the requests are declining which is looking good! Thank you!

![image](https://user-images.githubusercontent.com/20372645/148379037-b71fc5e2-8d8a-4049-ace0-e2d0e65cffb1.png)
