### ISSUE TITLE
GeyserMC error

### ISSUE THREAD

**Issue by Tuanvo29110** [GeyserMC/Geyser#2723]
### Describe the bug

geyser you kicked from server, reason: wrong ip adress 

### To Reproduce

.

### Expected behaviour

.

### Screenshots / Videos

![received_906319653420766](https://user-images.githubusercontent.com/96452478/146850908-3f742995-3842-4f36-a7cc-62b78ec538c0.jpeg)

### Server Version and Plugins

papmer-792 1.16.5 (IM plementing API VERSION 1.16.5-RO.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/hXdq0koA93T4UjNeq7rxNPXKqyv77Oep

### Geyser Version

Geyser 2.0.0 snapshot ( git-master-15522ae)

### Minecraft: Bedrock Edition Version

1.17.41

### Additional Context

Fix bugs fast!

**Comment by Camotoy** [comment]
This is not a Geyser nor a Floodgate error; another plugin is interfering with Floodgate, most likely. Please try searching your other plugins for this issue.
Closing as this is not our issue. Thanks anyway.
