### ISSUE TITLE
Chunks don't unload on bedrock

### ISSUE THREAD

**Issue by Shengalabu** [GeyserMC/Geyser#2725]
### Describe the bug

As the title suggests when a bedrock client joins a Geyser server and roams around for a bit, the chunks that they have explored or loaded don't get unloaded. The chunks do get unloaded by the server however they are still rendered by the bedrock client. This causes severe lag in low end devices as the unloaded chunks can be 500 blocks long.

### To Reproduce

1. Set your render distance to a really low number.
2. Use any type of bedrock client (mobile, pc, console) to join any server that has geyser enabled.
3. Move in any direction for about 500 blocks or more.
4. look behind you, the chunks will not be unloaded by your client.

### Expected behaviour

Say that you have set your render distance set to two. Move in any direction for about 500 blocks. You shouldn't be able to see blocks further than two chunks away.

### Screenshots / Videos

https://youtu.be/pXhN3PaevG4

### Server Version and Plugins

> version
[03:50:19 INFO]: Checking version, please wait...
[03:50:20 INFO]: This server is running Paper version git-Paper-99 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: cf621c5)
You are running the latest version
Previous version: git-Paper-81 (MC: 1.18.1)

Plugins
Geyser-Spigot.jar
floodgate-spigot.jar

### Geyser Dump

https://dump.geysermc.org/ixmup2gabSaICVn2A7TcgNQFfbuDWlsT

### Geyser Version

 Build #977 (Dec 21, 2021, 4:02:24 AM)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by Camotoy** [comment]
I'm not sure if there's anything we can do about this on our end; Bedrock doesn't have any packet to unload chunks and instead does this itself.

**Comment by Camotoy** [comment]
(Though, currently we don't forward the client's render distance to the server. We are aware that we need to implement this)

**Comment by HopHopHasan** [comment]
Can confirm - the server's render distance overrides the clients ( so you can get render distances of 64 on Switch where it should be 12 ). This does cause lag after a while.

**Comment by Shadowblitz16** [comment]
@Camotoy what about datapacks like terralith then?
are you saying the chunks will be desynced because the server will load one thing and bedrock will load another?

**Comment by Camotoy** [comment]
No.
