### ISSUE TITLE
3 Small issues

### ISSUE THREAD

**Issue by AxlRose-RX** [GeyserMC/Geyser#2730]
### Describe the bug

1) Heads (can't specify yet) that got enchanted with Curse Of Binding/Vanishing or maybe anything (also can't confirm ), will get disenchanted if placed down and picked up again.

2) Player's head/vision gets stuck in the block on top of them if they crouch while having levitation effect.

3)  Villager not showing actual price in their trading GUI after increasing any price in their trading list, instead, displayed the default price or discounted price <---(if was)

![image](https://user-images.githubusercontent.com/10159672/147399745-a2a1d49c-685d-4a56-ae60-13830fe6113f.png)
![image](https://user-images.githubusercontent.com/10159672/147399754-d867a98d-80df-4413-8af0-bfbd85ac3994.png)

First image is amount of stone i have before trading and the display name
Second image is amount of stone I have left after trading once
The villager GUI is displaying the wrong amount of stone required to complete a trade
in this case, it is displaying 19, where it is supposed to be saying 33 
64 - 31 = 33

### To Reproduce

1, 2 and 3 from Bug Description

### Expected behaviour

1, 2 and 3 from Bug Description

### Server Version and Plugins

Waterfall #473

This server is running Purpur version git-Purpur-1456 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7551c72 on HEAD)
You are running the latest version
Previous version: git-Purpur-1452 (MC: 1.18.1)

Plugins (39): ajParkour, BossBarMessage*, Citizens, CoreProtect, Denizen, DiscordSRV, DropHeads, dynmap, Essentials, EssentialsSpawn, floodgate, GeyserSkinManager, GriefPrevention, GSit, HeadDatabase, HoloExtension, HolographicDisplays, InventoryRollbackPlus, LuckPerms, mcMMO, MineSync, MobLimit, MyCommand, OpenInv, PlaceholderAPI, ProtocolLib, spark, TAB-Bridge, Vault, VentureChat, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, Vulcan, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

https://dump.geysermc.org/bAYijvKkz8cON8X2Jx7IA6V9hh0gm1FF

### Geyser Version

This server is running Geyser version 2.0.0-SNAPSHOT (git-master-68c13c0) (Java: 1.18 - 1.18.1, Bedrock: 1.17.30 - 1.18.0)

**Comment by Camotoy** [comment]
Please open three separate issues for each. It's much easier to track each and be able to close each when they're addressed. Thank you!
(Also the first issue doesn't sound like us since that's server behavior)
