### ISSUE TITLE
Mobs and monsters don't make noise by themselves

### ISSUE THREAD

**Issue by vitorgueler22** [GeyserMC/Geyser#2733]
### Describe the bug

They only make sounds when we hit them, and the spider walking. They don't make sounds naturally, like the ambient sounds.

### To Reproduce

1. Open Minecraft world;
2. Mobs don't make any sounds by themselves.

### Expected behaviour

Mobs should make sounds, mainly monsters, so we know they are close in caves and that kind of stuff... 

### Server Version and Plugins

Server: PaperMC 1.18.1 #104

Plugins: SkinsRestorer, EssentialsX, Geyser and Floodgate.

### Geyser Version

#987

### Minecraft: Bedrock Edition Version

1.18.2.03

### Additional Context

I've checked the sounds options for hostile and friendly mobs, it's all at max volume.

**Comment by code-monet** [comment]
Just built from head and seeing this issue as well.

**Comment by code-monet** [comment]
This got fixed sometime recently, possibly with 1.19 or otherwise within the last couple of months - I redeployed my server a few days ago and now can hear mob sounds.

**Comment by Camotoy** [comment]
We made some changes for 1.19, yeah. Not every mob sound will be translated, but many of them should be now.
