### ISSUE TITLE
Particle moove wrongly and cause massive lag

### ISSUE THREAD

**Issue by tbvns2** [GeyserMC/Geyser#2734]
### Describe the bug

When geyser translate a certain type particle, the particle fall and lag all bedrock client that can see the particle falling.

### To Reproduce

1. connecte to geyser with bedrock
2. summon a "dust" particle
3. watch the particle falling

### Expected behaviour

particule does not fall

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/88189738/147663428-0a9d389a-db1f-468b-9b11-4b2555308212.png)
![image](https://user-images.githubusercontent.com/88189738/147663250-c5bb7b43-17aa-49f2-8f1a-beb099f5e90a.png)

### Server Version and Plugins

version: git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ab927be:462

### Geyser Dump

https://dump.geysermc.org/KG92IBTcyXoIF4JbAXxvopeKPD9y8UP5

### Geyser Version

git-master-8e774ea

### Minecraft: Bedrock Edition Version

1.18x

### Additional Context

I use a plugins that add cosmetics and particle are broke.

**Comment by RednedEpic** [comment]
This is due to how the red dust particle works in Bedrock. Unfortunately, this is just due to how it is implemented inside of Bedrock.
