### ISSUE TITLE
Chunks still don't unload on bedrock

### ISSUE THREAD

**Issue by Shengalabu** [GeyserMC/Geyser#2735]
### Describe the bug

This is not a repost as this bug affects the latest version of geyser

Chunks still don't unload after the fix applied by RednedEpic

As the title suggests when a bedrock client joins a Geyser server and roams around for a bit, the chunks that they have explored or loaded don't get unloaded. The chunks do get unloaded by the server however they are still rendered by the bedrock client. This causes severe lag in low end devices as the unloaded chunks can be 500 blocks long.

### To Reproduce

1. Set your render distance to a really low number.
2. Use any type of bedrock client (mobile, pc, console) to join any server that has geyser enabled.
3. Move in any direction for about 500 blocks or more.
4. look behind you, the chunks will not be unloaded by your client.

### Expected behaviour

Say that you have set your render distance set to two. Move in any direction for about 500 blocks. You shouldn't be able to see blocks further than two chunks away.

### Screenshots / Videos

https://youtu.be/L8HHMM3yCSg

### Server Version and Plugins

[05:01:26 INFO]: Checking version, please wait...
[05:01:27 INFO]: This server is running Paper version git-Paper-110 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 6852c65)
You are running the latest version

Plugins
Geyser-Spigot.jar
floodgate-spigot.jar

### Geyser Dump

https://dump.geysermc.org/wX9Zlrwu8q6DmSTLeKULZHSSDFnDFQS0

### Geyser Version

Build #996 (Dec 29, 2021, 7:20:51 PM)

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

This problem still occurs in all devices despite the fix applied in #992

**Comment by Camotoy** [comment]
8a93f6a116e423db0716938b7057417398b20da0 should also help. Let us know here if there's still an issue, and if an issue still persists let us know which device you're using on Bedrock.
