### ISSUE TITLE
Cannot update Game mode and Game Difficulty

### ISSUE THREAD

**Issue by KnowledgeCenter123** [GeyserMC/Geyser#2737]
### Describe the bug

I am using a Aternos Server with GeyserMC plugin. When I change the game mode or game difficulty through the options on aternos, it is only changed on Java Edition, pocket edition players have to rejoin. The game mode and difficulty is not changed in pocket edition directly (without rejoining).

### To Reproduce

1. Join a Aternos Server on Pocket Edition.
2. Change the Game mode or Game difficulty through the options tab in aternos.

### Expected behaviour

The Game Mode and Game Difficulty should be changed automatically, when it is changed in the server.

### Geyser Version

996

### Minecraft: Bedrock Edition Version

1.18.1

**Comment by KurtThiemann** [comment]
The regular server.properties gamemode option only applies when you restart your server. Therefore, if Force Gamemode is enabled, Aternos will use the /gamemode command to update the gamemode for all currently online players immediately.

Could you try if the issue also occurs if you change everyone’s gamemode using the command (e.g. /gamemode survival @a) to find out whether this actually is an issue with Geyser or just an issue with Aternos?

**Comment by KnowledgeCenter123** [comment]
Thank you!! /gamemode survival @A - This helped me!!
