### ISSUE TITLE
Major Trident with Riptide dupe

### ISSUE THREAD

**Issue by AxlRose-RX** [GeyserMC/Geyser#2738]
### Describe the bug

- Trident with Riptide enchantment to whatever item you want by turning them into a Trident
- This works by hurling with the trident and instantly hotkey to the item you want

### To Reproduce

1. Stand on water with Riptide trident
2. Launch it and hot key to another item
3. The other item becomes trident
4. If other item had enchantments the new generated trident also keep those encahantments!

### Expected behaviour

Should not be able to dupe tridents
Tested on Java and did not work, only able to re-created on Bedrock

### Screenshots / Videos

https://youtu.be/5Khl1zWLkR8

### Server Version and Plugins

Purpur version git-Purpur-1465 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: f1ae453 on HEAD)

### Geyser Dump

https://dump.geysermc.org/76sMYZWQcaKpdKNbnhEy7rLgISLiPJVx

### Geyser Version

2.0.0-SNAPSHOT (git-master-b246d5b)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by Jens-Co** [comment]
Can you check a few things out for me?

*Can you replicate this on an default offline world?
* If you have the duplicated item in inventory and relog is the item still an trident or the block it was before ?

**Comment by FusedLeo** [comment]
Can you replicate this on a default offline world?

https://youtu.be/jxxUwjPwOvM

If you have the duplicated item in inventory and relog is the item still a trident or the block it was before?

From what I know, it is just a visual glitch so the item will turn back to its normal form after certain actions
The actions that will reset the transfer:
1. Logging out
2. Eating
3. Holding it with your cursor in your inventory
4. Throwing it out of your hotbar/inventory
5. Taking durability damage (If can)

I am sure there are more, but those are the ones I know.

**Comment by rtm516** [comment]
Might be able to get round this by after a trident use update the hotbar? Not the best fix but due to this being a bug in the client there isn't too much we can do.

**Comment by RednedEpic** [comment]
More or less a client problem. Will close as our options for potentially working around this on the Geyser end is limited.
