### ISSUE TITLE
cant connect to friends

### ISSUE THREAD

**Issue by joshuaword2alt** [GeyserMC/Geyser#2739]
### Describe the bug

when i went to friends tab i cant join the server

### To Reproduce

1. launch server to put server
2. go to friends 
3. when joining it unable to connect

### Expected behaviour

i cant join and trying

### Screenshots / Videos

![https://drive.google.com/file/d/1EFMIaT2koEibo5iGYOu24X8XzCbzCswk/view?usp=sharing](https://lh6.googleusercontent.com/VYq5T-Pjwlt-llFkt0nQvdwVP-K2XlT66jM_YDshkowG6ZkFEbsQ0ZfP81bOHVv2wfAiQ742F3MHLd-g9vES)

### Server Version and Plugins

1.18 - 1.18.1, Bedrock: 1.17.30 - 1.18.0 was not released yet

### Geyser Dump

https://dump.geysermc.org/ZqFH1IQF1ztMNsqK3CmlXGetQN3DOoCu

### Geyser Version

2.0.0-SNAPSHOT (git-master-3251d90)

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

i try to get it working

**Comment by joshuaword2alt** [comment]
i know because its just my pc not working its just ios and android

**Comment by Konicai** [comment]
Have you tried joining through the Servers tab? 

Does anything happen in Geyser's logs when you try connecting through the friends tab? If so, can you share your logs through https://mclo.gs

**Comment by Konicai** [comment]
Please contact us on Discord if you're still having issues: https://discord.gg/GeyserMC
