### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid value 4 on ClientboundLevelChunkWithLightPacket translating

### ISSUE THREAD

**Issue by casperge** [GeyserMC/Geyser#2744]
### Describe the bug

One of my users using RealisticSeasons (which messes with the ClientboundLevelChunkWithLightPacket, it replaces the byte[] buffer in ClientboundLevelChunkPacketData with a modified version that includes some custom biomes) is sometimes getting this error in the console. (https://pastebin.com/qvWsBACg). Everything works fine for java players so that's why I think it is a geyser issue and not something with my modified byte[].

### To Reproduce

No idea, have not managed to reproduce it myself. Just one user has this issue and no one else.

### Expected behaviour

No errors :)

### Geyser Version

2.0.0-SNAPSHOT (git-master-3251d90)

**Comment by Konicai** [comment]
The paste is no longer available. Also, please provide a geyser dump by running`geyser dump`

Regardless, I assume

**Comment by casperge** [comment]
Sure, here is the new pastebin: https://pastebin.com/g1uiJnqU

Also the geyser dump: https://dump.geysermc.org/ZZVaTXCow28VD8g5YA0aoKm7i9BZB5W2

**Comment by Camotoy** [comment]
Looks like the plugin is paid. Unless you're able to spin up a test server or point to one where this issue occurs, there's not much we can do at the moment.

**Comment by arima0k** [comment]
Bedrock windows 10
![image](https://user-images.githubusercontent.com/25037200/164229037-c1a41f6b-3a58-47db-a0dc-f698995b0f4f.png)

Exact timing logs: https://pastebin.com/XcLQ4LFf
dump: https://pastebin.com/zUmyzQGj (need to edit because the motd.

**Comment by casperge** [comment]
> Looks like the plugin is paid. Unless you're able to spin up a Java test server or point to one where this issue occurs, there's not much we can do at the moment.

If you need any info, code, or access to the plugin to resolve the issue, please let me know

**Comment by RednedEpic** [comment]
> > Looks like the plugin is paid. Unless you're able to spin up a Java test server or point to one where this issue occurs, there's not much we can do at the moment.
> 
> If you need any info, code, or access to the plugin to resolve the issue, please let me know

Any sort of replication code would be amazing for trying to reproduce this.

**Comment by Camotoy** [comment]
Oh, hi, it seems like you're the author of the plugin! My apologies for not responding sooner.

I'll be happy to look into the issue if it's easier to temporarily give access to the plugin. Here's my Spigot username: https://www.spigotmc.org/members/camotoy.6153/

**Comment by casperge** [comment]
No worries, I gave you access to the plugin. I will DM you the code on spigot that translates the biomes so it's easier to figure out on whose side the issue is. Thanks for your help!

**Comment by Camotoy** [comment]
Casperge, you mentioned elsewhere that Bungee players were having this issue because Floodgate is only on the proxy. Do note that we do have a forwarding option that allows Floodgate to also be used on the backend servers.

Other than that, I hope everything is working smoothly.

**Comment by arima0k** [comment]
I will run tests to see if everything works as intended.
