### ISSUE TITLE
pressing "/" in chat gets stuck for about 30 seconds on first run.

### ISSUE THREAD

**Issue by usma0118** [GeyserMC/Geyser#2745]
### Describe the bug

As ops user, i have tried issuing commands from minecraft bedrock on IPad. opening chat and pressing "/" for ist time in a session. makes game stuck for about 30 seconds.

### To Reproduce

1. Give user ops permissions
2. Open minecraft on ipad (haven't tested on windows bedrock)
3. connect to world
4. open chat and press "/"
5. App will stop responding for about 20-30 secods.

**PS! Non-ops user doesn't face this problem.

### Expected behaviour

App should show command list right away.

### Server Version and Plugins

Minecraft Server
**Paper 1.18.1-134**

**Plugins**
Dynmap-3.3-beta-4
EssentialsX-2.19.3
floodgate-spigot.
Geyser-Spigot-2.0.0
HolographicDisplays
LuckPerms-Bukkit-5.3.97
Multiverse-Core-4.3.1
Multiverse-Inventories-4.2.3-SNAPSHOT
Multiverse-Portals-4.2.1
Shopkeepers-2.14.0
worldedit-bukkit-7.2.8
worldguard-bukkit-7.0.6

### Geyser Dump
https://dump.geysermc.org/EvYarmpztUd3XSGpQDEluPcQy4JwiI8k

### Geyser Version

2.0.0

### Minecraft: Bedrock Edition Version

1.18

**Comment by Konicai** [comment]
Disable command-suggestions in Geyser's config.

Please attach a Geyser dump by running `/geyser dump`

**Comment by usma0118** [comment]
dump added. will test command-suggestion behavior.

**Comment by Chew** [comment]
This issue has been reported many times before, it's ultimately a client bug, not much we can do other than have that config option. Thanks for reporting, however!
