### ISSUE TITLE
the player's skin has not shown in the bedrock edition client

### ISSUE THREAD

**Issue by warma16** [GeyserMC/Geyser#2746]
### Describe the bug

I'm the host of the minecraft server which used the technology of geyser.the player's skin has not shown in the bedrock edition client.and the player was set up the local skin to the skin which provided by the skin site.

### To Reproduce

use the client to connect the geyser server can't see the player skin itself.

### Expected behaviour

the skin not only will be shown in the game  but also player see his skin.

### Server Version and Plugins

1.17.1

### Geyser Version

1.17.1

### Minecraft: Bedrock Edition Version

1.17.1

**Comment by Konicai** [comment]
Do you have Floodgate installed?

If its a single player, what is the skin and how long ago did the player set their skin to it? How long has the player been on Geyser servers with Floodgate? Are they using account linking? 

Please attach a Geyser dump using `/geyser dump`

**Comment by warma16** [comment]
the geyser dump link is https://dump.geysermc.org/prabuqoYIdUbVEUmuWBBxFYUt1OYDyzn

**Comment by Jens-Co** [comment]
Does this issue still persists? 
Otherwise I'll close this issue.

**Comment by Jens-Co** [comment]
Closed due to no response. if you still have this issue feel free to bump this and ill reopen. You also can join our discord https://discord.geysermc.org/ 

Thanks!
