### ISSUE TITLE
Missing/Broken Bossbar

### ISSUE THREAD

**Issue by AxlRose-RX** [GeyserMC/Geyser#2748]
### Describe the bug

Issue related to #348 (https://github.com/GeyserMC/Geyser/issues/348) and it was closed and still able to reproduce
@FusedLeo was still able to reproduce this on latest Geyser and server builds and made a video about it

https://www.youtube.com/watch?v=BEr0-iEay9o&ab_channel=GamersPlayground

### To Reproduce

1. Use the crystal to summon the Ender Dragon
2. Bossbard is normal
3. Relog to server and come back to the the End world to face the Dragon
4. Bossbar is gone, you can also TP, die, etc.
5. This is likely to effect any other kind of boss bar, like Wither, Raid or custom
6. Dealing damage wont change a thing, we thought it would be the first time

### Expected behaviour

Bossbar should stick while close to dragon, wither, raids

### Screenshots / Videos

https://youtu.be/BEr0-iEay9o

### Server Version and Plugins

Previous version: git-Purpur-1485 (MC: 1.18.1)

Plugins (28): CoreProtect, DiscordSRV, Essentials, EssentialsSpawn, floodgate, GeyserSkinManager, GriefPrevention, InventoryRollbackPlus, LuckPerms, MineSync, MobLimit, MyCommand, OpenInv, PlaceholderAPI, ProtocolLib, spark, TAB-Bridge, Vault, VentureChat, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, Vulcan, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

https://dump.geysermc.org/aFdjIt9IY7VSTCDtCj0tsbmAt2SsraLC

### Geyser Version

2.0.0-SNAPSHOT (git-master-3251d90)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by onebeastchris** [comment]
Is this still an issue?

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/commit/0d25a3f04d413ce4c4ec95e5dd9344bebb40b5c6 this was resolved in this commit - if not; please open a new issue.
