### ISSUE TITLE
Nasty XRay bug, only for bedrock players

### ISSUE THREAD

**Issue by AxlRose-RX** [GeyserMC/Geyser#2749]
### Describe the bug

This video shows the process of reproducing the Slab Air X-Ray Glitch

https://youtu.be/s3qpEpAy708

by @FusedLeo 

### To Reproduce

1. Find a spot to Air X-ray, the deeper the better. (Optional)
2. Place a block above your head.
3. Sneak and place a slab in between the gap of your head and the block.

### Expected behaviour

Should not be able to XRay! Java players are not affected. Paper Xray protection is enabled

### Screenshots / Videos

https://youtu.be/s3qpEpAy708?t=52

### Server Version and Plugins

Previous version: git-Purpur-1485 (MC: 1.18.1)

Plugins (28): CoreProtect, DiscordSRV, Essentials, EssentialsSpawn, floodgate, GeyserSkinManager, GriefPrevention, InventoryRollbackPlus, LuckPerms, MineSync, MobLimit, MyCommand, OpenInv, PlaceholderAPI, ProtocolLib, spark, TAB-Bridge, Vault, VentureChat, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, Vulcan, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

https://dump.geysermc.org/aFdjIt9IY7VSTCDtCj0tsbmAt2SsraLC

### Geyser Version

2.0.0-SNAPSHOT (git-master-3251d90)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by Camotoy** [comment]
1.19.70 fixes this issue!

**Comment by AxlRose-RX** [comment]
\o/
