### ISSUE TITLE
Unable To Connect World 1.18.2

### ISSUE THREAD

**Issue by WanFirash** [GeyserMC/Geyser#2750]
### Describe the bug

i cant join server my friend, my fried has added plugin **floodgate, geyser-spigot** and set up that all, but i _cant join_ :(

### To Reproduce

a

### Expected behaviour

a

### Screenshots / Videos

a

### Server Version and Plugins

1.18.1 Floodgate, geyser.spigot

### Geyser Dump

Dump

### Geyser Version

1.18.2

### Minecraft: Bedrock Edition Version

1.18,2

### Additional Context

a*

**Comment by Camotoy** [comment]
Please join our Discord for connection errors like these. Thank you!
