### ISSUE TITLE
Bedrock players clicking twice

### ISSUE THREAD

**Issue by ImpeccablePenguin** [GeyserMC/Geyser#2752]
### Describe the bug

While most noticeable in creative, left clicks are done twice and two blocks are broken. This causes issues when players need to click something with an item as it might cancel what they were trying to do.

### To Reproduce

1. Break a block on creative mode,
2. Two blocks are broken

another example:
1. click chest with redstone for use with signshops plugin
2. command is cancelled because there were two clicks

### Expected behaviour

Only one block is broken or one click is done

### Server Version and Plugins

paper 133
geyser 2.0.0-SNAPSHOT (git-master-3251d90)

Chunky, DecentHolograms essentials, essentialschat, essentialsprotect, floodgate, geyser-spigot, luckperms, multiverse-core, multiverse-inventories, multiverse-netherportals, multiverse-portals, placeholderAPI, SignShop, TAB, Vault, voidgen, worldedit, worldguard, worldspawn.

### Geyser Dump

https://dump.geysermc.org/W4jh9XjAuD6zkQdy2MfwqaEnpqeL4ZVF

### Geyser Version

geyser 2.0.0-SNAPSHOT (git-master-3251d90)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by Camotoy** [comment]
On Android desktop I can safely say that breaking a block in creative does not click twice. Can you share what platform (and perhaps input mode) this occurs with?

**Comment by spookymgmt** [comment]
I also have this issue. When using deluxemenus and adding commands to run on left click, when the click it, it runs twice no matter what. Causes insane issues for me.

**Comment by ImpeccablePenguin** [comment]
Upon further testing, this appears to be an issue especially while in creative mode because blocks can be instamined. I'm testing using windows 10 edition and changing into survival mode temporarily tends to fix the issue.

**Comment by Jens-Co** [comment]
Any updates on this issue? Ive tried with latest paper/ geyser-spigot/floodgate and was unable to replicate this behaviour.

**Comment by Jens-Co** [comment]
Since there was no response and was unable to replicate this on iOS and win 10 version I'll close this issue. If this still occurs bump this and I'll reopen.
