### ISSUE TITLE
geyser "online" mode isn't compatible with hybrid auth mode

### ISSUE THREAD

**Issue by 66Leo66** [GeyserMC/Geyser#2754]
### Describe the bug

Some mods/plugins, [Fabric EasyAuth](https://modrinth.com/mod/easyauth) for example, privides "hybrid" authentication mode.

In such mode, server is set to online-mode to enable communication to Mojang authserver. If online mode authentication passed, user is logged in direcrly. Otherwise, traditional /login command auth is present.

When using geyser in online mode, user can't set a custom (offline) username,which ought to be allowed by remote server.

### To Reproduce

- Set Geyser to online mode.
- Install EasyAuth and enable "premium-auto-login"
- Set remote server to online mode.

### Expected behaviour

Suggestion 1: Geyser pass user-entered username to server instead of validating on its own.

Or, suggestion 2: Provide a togglable feature to add "still use offline nickname" besides mojang and microsoft online login.

### Server Version and Plugins

Geyser-Fabric
EasyAuth(link given at description)

other mods are unrelated

### Geyser Version

Geyser-Fabric-2.0.0-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.18.2.03

### Additional Context

Although this is a small demand, I still hope it can be realized. thank you!

**Comment by Camotoy** [comment]
Geyser won't make workarounds for third-party authentication plugins. If you think Geyser is handling something incorrectly, send a Geyser dump. Thanks anyway.
