### ISSUE TITLE
Weird connection error after bedrock player died

### ISSUE THREAD

**Issue by Cabbidachi** [GeyserMC/Geyser#2755]
### Describe the bug

The player clicked on respawn and afterwards it took a pretty long time until a timeout error appeared which at first seemed like the usual situation when something takes too long. But afterwards the player was completly unable to connect to the server via Bedrock. The error simply is "Connection failed" and the log is saying the following:
[00:19:32] [Geyser player thread-3-1/WARN]: [Geyser-Spigot] Packet violation warning sent from client! PacketViolationWarningPacket(type=MALFORMED_PACKET, severity=TERMINATING_CONNECTION, packetCauseId=76, context=)

### To Reproduce

no idea as it happenend randomly all i can say that the server was already running for one day fulltime. The player died and then while they were respawning connection was suddendly lost due timeout. And then afterwards they were no more able to connect until i restarted the entire server.

### Expected behaviour

for the player to connect normally

### Server Version and Plugins

This server is running Paper version git-Paper-140 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: d9fb602)
Plugins (13): Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, floodgate, Geyser-Spigot, Harbor, LuckPerms, OpGuard*, PlugManX (PlugMan), SkinsRestorer, TabList, TogglePvp

### Geyser Dump

https://dump.geysermc.org/x6qko2WQ6dbSd9dMv9TfyZ9rwsu6ywdl

### Geyser Version

Geyser version 2.0.0-SNAPSHOT (git-master-3251d90)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by Camotoy** [comment]
This happens randomly sometimes. A temporary fix is to disable `command-suggestions` in the Geyser config.

**Comment by Cabbidachi** [comment]
i already disabled this due the high lag it caused. But still thanks for the suggestion
should i close this issue if it is a randomly occurring thing?

**Comment by onebeastchris** [comment]
Does this issue still occur - even rarely - with the latest version of Geyser? If it does, please send a new Geyser dump.

**Comment by Cabbidachi** [comment]
Hello
I totally forgot I still had this open actually 
The issue has not occured at my latest project that relies on Geyser a lot
I think that is a confirmation that the issue no longer exists
