### ISSUE TITLE
Misplaced Inventory Player Doll Glitch

### ISSUE THREAD

**Issue by AxlRose-RX** [GeyserMC/Geyser#2756]
### Describe the bug

Flying towards -z            =  Doll upside-down pose
Flying towards z             =  Normal-ish pose
Flying towards -x and x =  Pose inconsistent

### To Reproduce

1. Glide with an elytra.
2. Open your inventory.
3. Look at your player doll.
( Low priority visual bug )

### Expected behaviour

Player Doll should show the right way

### Screenshots / Videos

https://youtu.be/jXAlo9FK4oY

Every footage used in this video belongs to @FusedLeo (Fused#8594 Discord Username)

### Server Version and Plugins

Previous version: git-Purpur-1485 (MC: 1.18.1)

Plugins (28): CoreProtect, DiscordSRV, Essentials, EssentialsSpawn, floodgate, GeyserSkinManager, GriefPrevention, InventoryRollbackPlus, LuckPerms, MineSync, MobLimit, MyCommand, OpenInv, PlaceholderAPI, ProtocolLib, spark, TAB-Bridge, Vault, VentureChat, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, Vulcan, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

https://dump.geysermc.org/aFdjIt9IY7VSTCDtCj0tsbmAt2SsraLC

### Geyser Version

2.0.0-SNAPSHOT (git-master-3251d90)

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

Servers:
Gamers Playground
JAVA: play.gp-mc.net
BEDROCK: bedrock.gp-mc.net port: 19132
https://discord.com/invite/vsEgHQx
Web: https://www.gp-mc.net/

**Comment by Camotoy** [comment]
This is very likely a client bug we can't do anything about. I'd attempt to reproduce this in a singleplayer Bedrock world.

**Comment by Konicai** [comment]
Reproduced this on a default singleplayer world.

**Comment by Camotoy** [comment]
I'm going to close this then as we very likely can't do anything about it, and even if we could there's no reason to bother as it doesn't break gameplay. Thanks anyway!
