### ISSUE TITLE
Crafting Issues with Gnembon’s AutoCraftingTable Mod

### ISSUE THREAD

**Issue by QPCrummer** [GeyserMC/Geyser#2757]
### Describe the bug

- When crafting an item with AutoCraftingTable mod, the item is not given to the player until the inventory is closed
- When closing the table with an item in it, the item doesn’t show up when reopening the crafting table 

### To Reproduce

1. Install AutoCraftingTable mod and carpet mod on fabric and enable the carpet rule
2. Place down a crafting table
3. Try to craft an item with the recipe book
4. Keep an item in the table and close the GUI
5. Reopen the GUI to find your items are gone
6. Break the table to get your item back

### Expected behaviour

- Items show up in inventory when crafted
- Items show up in crafting table after closing and opening the GUI

### Server Version and Plugins

Java: 1.18.1 Fabric
Fabric: 0.12.12
Mod: My [fork](https://github.com/QPCrummer/carpet-autoCraftingTable) 

### Geyser Version

https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/997/

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

It may need code written on the mod itself. I have a [fork](https://github.com/QPCrummer/carpet-autoCraftingTable)  of the mod that updates the two current PRs to 1.18.1. If code is needed on the mod, and someone would like to tell a way to fix it and/or fix it themselves that would be very appreciated. Thanks for making BE possible with Java!

**Comment by QPCrummer** [comment]
I will get a dump and /geyser version when I get back on my PC

**Comment by LeoIMR** [comment]
[log.log](https://github.com/GeyserMC/Geyser/files/7930255/log.log)

Here's the log from the console while a Bedrock user in our server experiences the same bug. Hope this can help, we love this feature and we were forced to temporarely disable it. I add that breaking the crafting table after the bug occours may not give back the items that were inside it.

**Comment by QPCrummer** [comment]
@LeoIMR I have made a temporary “fix” mod for this issue. It is more of a workaround than a fix though. My mod (https://modrinth.com/mod/fabricautocrafter) doesn’t override the vanilla crafting table, but rather makes a new block, all while being server side. It also fixes a few bugs with the original AutoCraftingTable like it not being able to use an item filter. The crafting recipe for it is 8 redstone dust around one crafting table. 

*BE players sadly still cannot properly interact with this new table, but at least they can use the vanilla one.

**Comment by Camotoy** [comment]
Confirmed bug that the client doesn't show anything, but ultimately this is an error with the mod as a client gives a similar error:
```
Error executing task on Client
java.lang.IndexOutOfBoundsException: Index 46 out of bounds for length 46
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at gt.get(SourceFile:47)
	at bpx.a(SourceFile:275)
	at bpx.a(SourceFile:583)
	at elm.a(SourceFile:1051)
	at rp.a(SourceFile:44)
	at rp.a(SourceFile:11)
	at qt.a(SourceFile:21)
	at auh.c(SourceFile:151)
	at aul.c(SourceFile:23)
	at auh.y(SourceFile:125)
	at auh.bp(SourceFile:110)
	at dxo.f(SourceFile:1080)
	at dxo.e(SourceFile:733)
	at net.minecraft.client.main.Main.main(SourceFile:238)
```

**Comment by QPCrummer** [comment]
Camotoy, my mod that I gave above has fixed that error as of version 1.0.1. I’ll see if the bug still happens with the new fix.

**Comment by Camotoy** [comment]
https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/inventoryparity/ this build will show items in an auto crafting table.

**Comment by QPCrummer** [comment]
Well, now you can use my mod with the fixes and BE players can see items 👑
