### ISSUE TITLE
Paper 1.18.1-145 doesn't allow players to join

### ISSUE THREAD

**Issue by EscolarProgramming** [GeyserMC/Geyser#2758]
### Describe the bug

After an update to the latest Paper 1.18.1-142 tonight we've noticed that bedrock players can't join our servers anymore. They always get the error "Kicked whilst connecting to <Server>: Failed to verify username!". After downgrading to Paper 1.18.1-97 all works fine again. It seems like 1.18.1-121 broke it. Latest build (1.18.1-145) doesn't work too.

### To Reproduce

1. Create a bungee with Geyser
2. Create a Paper 1.18.1-142 server
3. Try to join the server

### Expected behaviour

Players should join the Paper 1.18.1-142 server

### Screenshots / Videos

![grafik](https://user-images.githubusercontent.com/6965961/148802797-46c47aa1-64b8-4212-918b-a2c87a0caf42.png)

### Server Version and Plugins

BungeeCord: git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:425ee4e:1618
Spigot working: Paper version git-Paper-97 (MC: 1.18.1)
Spigot not working: Paper version git-Paper-145 (MC: 1.18.1)

### Geyser Dump

https://dump.geysermc.org/XBjhfB4HDN910HYs4FpiX7axOk3y6PuU

### Geyser Version

2.0.0-SNAPSHOT (git-master-3251d90)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by Camotoy** [comment]
We are aware of this issue; for now, you can disable `unsupported-settings.perform-username-validation` in the `paper.yml` config. Floodgate will fix this issue in the future.

**Comment by Leahcimkrob** [comment]
After the Paper, Floodgate and Geyser-Update we get the error message again, regardless of whether we set the value to False or True

**Comment by Tim203** [comment]
This is a different issue, see #2802

**Comment by SleepingLaura** [comment]
> After the Paper, Floodgate and Geyser-Update we get the error message again, regardless of whether we set the value to False or True

Mojang changed their API, which broke Floodgate.
Floodgate has been fixed for both Paper and Velocity, but not yet for Bungeecord.

If you want to stay up to date on this, you can join the [GeyserMC Discord](https://discord.gg/GeyserMC).
