### ISSUE TITLE
Spectral arrows dont show aura for bedrock players

### ISSUE THREAD

**Issue by Marcof2004** [GeyserMC/Geyser#2762]
### Describe the bug

When a bedrock player shoots a spectral arrow towards a java player, the aura that the spectral arrow produces on  the player is not shown for bedrock player. 

### To Reproduce

1. Have a Bedrock player have an arrow and spectral arrows
2.  The bedrock player should shoot spectral arrows to a Java player.
3. The spectral arrow will not be shown to the bedrock player, but it will be shown to java players as well of the java player who was shooted. 

### Expected behaviour

When the bedrock player shoots the arrow it is expected that the aura is shown for every player that shoots. 

### Server Version and Plugins

Spigot 1.18.1
CraftBukkit version 3395-Spigot-f4ff00f-cc86ab1 (MC: 1.18.1)

### Geyser Version

CraftBukkit version 3395-Spigot-f4ff00f-cc86ab1 (MC: 1.18.1)

### Minecraft: Bedrock Edition Version

1.18.1

**Comment by Camotoy** [comment]
This is a Bedrock limitation - it doesn't have a glowing effect. We have it as something to potentially implement in https://github.com/GeyserMC/GeyserOptionalPack/issues/3 but the research shows this isn't feasible at the moment. Sorry, but thank you for reporting anyway!
