### ISSUE TITLE
Bedrock players able to fly in survival mode

### ISSUE THREAD

**Issue by usma0118** [GeyserMC/Geyser#2763]
### Describe the bug

At times when i join from Minecraft bedrock client on IOS devices. double jump results into flying. (while game mode is set to survival)

### To Reproduce

1. Join survival world from ipad
2. press jump button twice (same as when you want to go in fly mode in creative)
3. Character will start to fly.

PS! can't reproduce it everytime.

### Expected behaviour

Shouldn't fly in survival mode.

### Server Version and Plugins

Minecraft Server
Paper 1.18.1-134

Plugins
Dynmap-3.3-beta-4
EssentialsX-2.19.3
floodgate-spigot.
Geyser-Spigot-2.0.0
HolographicDisplays
LuckPerms-Bukkit-5.3.97
Multiverse-Core-4.3.1
Multiverse-Inventories-4.2.3-SNAPSHOT
Multiverse-Portals-4.2.1
Shopkeepers-2.14.0
worldedit-bukkit-7.2.8
worldguard-bukkit-7.0.6

### Geyser Dump

https://dump.geysermc.org/EvYarmpztUd3XSGpQDEluPcQy4JwiI8k

### Geyser Version

2.0.0

### Minecraft: Bedrock Edition Version

1.18

**Comment by AnhNguyenlost13** [comment]
When you join the server, does it say "Set fly mode enabled for <player>"? I think it's related to EssentialsX.

**Comment by hteppl** [comment]
This is EssentialsX option.

**Comment by usma0118** [comment]
Confirmed, this is due to EssentialsX

**Comment by EimohPvP** [comment]
essentialsX was not my problem, any other help?
