### ISSUE TITLE
Newly built server with most updated paper issues.

### ISSUE THREAD

**Issue by pupshadow** [GeyserMC/Geyser#2764]
### Describe the bug

I just made a Ubuntu Server Mineos gui frontend server replacement for my existing server and am having issues every few seconds in the logs of:

https://pastebin.com/HzHC78cb

Then I tried to do a geyser dump and this happened:

https://pastebin.com/XXBUiFcP

### To Reproduce

1st error: Just start the server up.

2nd error try to do geyser dump command.

### Expected behaviour

1st error idk what it is doing.

2nd error it was suppose to give me my dump I asked for.

### Server Version and Plugins

This server is running Paper version git-Paper-151 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 6663747)

[Server thread/INFO]: Plugins (2): floodgate, Geyser-Spigot

### Geyser Version

 This server is running Geyser version 2.0.0-SNAPSHOT (git-master-1c11a2e) (Java: 1.18 - 1.18.1, Bedrock: 1.17.30 - 1.18.0)

**Comment by Konicai** [comment]
Your server doesn't have access to the internet or your outgoing firewall is very strict.

Feel free to contact us on Discord if you need further help with this or any setup issues
