### ISSUE TITLE
Water and lava dont get accurately placed.

### ISSUE THREAD

**Issue by spookymgmt** [GeyserMC/Geyser#2775]
### Describe the bug

When a bedrock player places water or lava via a bucket, it won't place it where they click. It's always 1-2 blocks away from where they intended to place it.

### To Reproduce

1. load geyser, connect to java server on MOBILE or CONSOLE bedrock, try to place water bucket. (This isn't an issue on Windows 10 bedrock. Only an issue on Phone and Console.

### Expected behaviour

Water and lava should be placed where the user places it.

### Server Version and Plugins

git-Airplane-"a3b010c" 1.17.1 

### Geyser Dump

 https://dump.geysermc.org/zL46dX3Y6w85qKSsx7YBzN9AEBpN7Xme

### Geyser Version

2.0.0-SNAPSHOT git-master-1c11a2e

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by Camotoy** [comment]
This is most likely the same issue as https://github.com/GeyserMC/Geyser/issues/1891 so I will close this for that. Thank you anyway!
