### ISSUE TITLE
Error unable to find listening channel

### ISSUE THREAD

**Issue by itsmeR1F4I** [GeyserMC/Geyser#2777]
### Describe the bug

I can't use geyser on my vps, but for the Java server it's safe without any problems

### To Reproduce

No steps, just errors Unable to find listening channel

### Expected behaviour

I've set up the geyser and floodgate so that they can be used, but still can't, the geyser is getting unable to find listening channel.

### Screenshots / Videos

![Screenshot_2022-01-18-04-47-56-224_com android chrome](https://user-images.githubusercontent.com/76506048/149840540-d60e15af-448d-4197-a907-821b7c35549f.jpg)

### Server Version and Plugins

![Screenshot_2022-01-18-04-53-44-550_com android chrome](https://user-images.githubusercontent.com/76506048/149840832-aa306ad7-0b0d-492f-bcb7-fdb71528af70.jpg)

### Geyser Dump

https://dump.geysermc.org/uBo3LMePIrVzWcBrdyRRWGuEiVHq5feg

### Geyser Version

This server is running Ge yser version 2.0.0-SNAPSHOT (git-master-c1 e4040) (Java: 1.18 - 1.18.1, Bedrock: 1.17 .30 - 1.18.0) 

### Minecraft: Bedrock Edition Version

1.18.1

**Comment by Camotoy** [comment]
Did you use `/reload`?

**Comment by itsmeR1F4I** [comment]
> Did you use `/reload`?

Yes,  But when restarting the server, no error message appears, but I can't connect java server from bedrock edition.

**Comment by Camotoy** [comment]
Reloading currently breaks Geyser-Spigot which is documented here: https://github.com/GeyserMC/Geyser/issues/2665
For connection issues, please join our Discord server. Thank you!
