### ISSUE TITLE
ArmorStand marked as invisible is not invisible.

### ISSUE THREAD

**Issue by lazertester** [GeyserMC/Geyser#2780]
### Describe the bug

Armor stand that spawns as invisible is not invisible for bedrock players.

### To Reproduce

1. Download the source of the plugin https://github.com/lazertester/IShouldBeInvisible and build it (or use the [release](https://github.com/lazertester/IShouldBeInvisible/releases/tag/1.0))
2. Install it on a spigot/paper server (tested with 1.12 and 1.16)
3. Type `/ishouldbeinvisible`

### Expected behaviour

The armor stand that spawns should be invisible, it is not for bedrock players.

### Screenshots / Videos

https://gfycat.com/madgreedyatlanticbluetang

### Server Version and Plugins

Spigot 1.16.2 and 1.12.2, no other plugins.

### Geyser Version

https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1009/

### Minecraft: Bedrock Edition Version

1.18

**Comment by Camotoy** [comment]
Should be fixed with 1fba96c339ebbe1775bc886679afb5f35815c61f.
