### ISSUE TITLE
Misplaced Elytra Crosshair

### ISSUE THREAD

**Issue by AxlRose-RX** [GeyserMC/Geyser#2781]
### Describe the bug

Video shows the process of reproducing the Misplaced Elytra Crosshair and details about it

This also effect it's behavior, block placement, interaction, hitting, etc.

You can't/can hit entities from bizarre angles, watch how he can slash the snow golem without even looking at it.

### To Reproduce

1. Glide with an elytra.
2. Focus on your crosshair.
3. Interact with the crosshair, place a block, interact, hit, etc.
( Low priority feature error, maybe )

Extra:
Crawling and swimming doesn't have the same effect.

### Expected behaviour

Should hit where you aim at

### Screenshots / Videos

https://youtu.be/wTpQnU5CKH8

by @FusedLeo 

### Server Version and Plugins

This server is running Waterfall version git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475 by md_5

Previous version: git-Purpur-1502 (MC: 1.18.1)

Plugins (39): ajParkour, BossBarMessage*, Citizens, CoreProtect, Denizen, DiscordSRV, DropHeads, dynmap, Essentials, EssentialsSpawn, floodgate, GeyserSkinManager, GriefPrevention, GSit, HeadDatabase, HoloExtension, HolographicDisplays, InventoryRollbackPlus, LuckPerms, mcMMO, MineSync, MobLimit, MyCommand, OpenInv, PlaceholderAPI, ProtocolLib, spark, TAB-Bridge, Vault, VentureChat, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, Vulcan, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

https://dump.geysermc.org/xgxK85eHZxCH5puNpEOgdkST4MWx3L6V

### Geyser Version

2.0.0-SNAPSHOT (git-master-c1e4040) (Java: 1.18 - 1.18.1, Bedrock: 1.17.30 - 1.18.0)

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

**### Gamers Playground**

**JAVA:** play.gp-mc.net

**BEDROCK:** bedrock.gp-mc.net port: 19132

https://discord.com/invite/vsEgHQx
**Web:** https://www.gp-mc.net/

**Comment by hausemaster3734** [comment]
It's vanilla.

**Comment by Konicai** [comment]
Not likely anything we can do about this.
