### ISSUE TITLE
Add variables for the PlaceholderAPI

### ISSUE THREAD

**Issue by lonely-nightmare** [GeyserMC/Geyser#2784]
### What feature do you want to see added?

Added a variable to whether the player is a bedrock version

### Are there any alternatives?

Floodgate also donnt have

**Comment by Konicai** [comment]
GeyserMC itself doesn't maintain any PlaceholderAPI extensions. If you're referring to one of the following, please ask them to implement new placeholders:
https://github.com/ImDaBigBoss/GeyserPlaceholders
https://github.com/rtm516/FloodgatePlaceholders/
