### ISSUE TITLE
Bedrock players do not sync correctly and cannot log in

### ISSUE THREAD

**Issue by HideyBoi** [GeyserMC/Geyser#2786]
### Describe the bug

After some time, bedrock players are unable to play normally. Nothing registers on the client. For example when breaking a block, no effects spawn, but after relogging (and restarting the server because you can't get back into the server after it breaks) everything suddenly syncs up again and you have whatever items you had broken. Java players seem to see the bedrock plays as normal, but the bedrock plays cant see the Java players at all.

### To Reproduce

1. Start up a normal version of papermc with geyser
2. play with the bedrock player for a while, try breaking blocks
3. after a while block should stop producing particle effects

### Expected behaviour

Bedrock and Java players should be able to sync up correctly and play as normal

### Screenshots / Videos

[Java - YouTube](https://youtu.be/3tygom4tA4s)
[Bedrock - YouTube](https://youtu.be/iRMjU_xxe3A)

Both were recorded at the same time, and I am not at my pc at the time, so I apologized for the weird java movement.

### Server Version and Plugins

[20:07:29 INFO]: This server is running Paper version git-Paper-167 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: feb72b8)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-133 (MC: 1.18.1)

### Geyser Dump

https://dump.geysermc.org/mWeTSGxles1culmZJxE18JdHbiRFZdj1

### Geyser Version

2.0.0-SNAPSHOT (git-master-e92633d)

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

I've tried messing with config settings, so they're slightly changed, but even with default configs I was having issues.

**Comment by Camotoy** [comment]
Can you try this build? https://cdn.discordapp.com/attachments/613170125696270357/929130980223094815/Geyser-Spigot.jar it disables encryption, so you need to be careful, but we need to see if it addresses the issue at hand.

**Comment by HideyBoi** [comment]
I just did, it seems to work all right. Thanks for the help.

**Comment by Eduardjugon** [comment]
Hey there! I'm also affected by this.

It also seems that the bedrock players are not affected by plugins so for example they can break blocks even if world guard protects it (though it's only client-sided but they can still potentially get in areas they aren't supposed to)

**Comment by Camotoy** [comment]
Did the build linked above solve the issue? 
If it does, does this build work? https://discord.com/channels/613163671870242838/613170125696270357/934928852952678510

**Comment by HideyBoi** [comment]
@Camotoy the first one did, but the second one doesn't seem to work anymore.

**Comment by Camotoy** [comment]
Thank you.

**Comment by Camotoy** [comment]
This is the same issue as #2861, so I am closing for tidiness. Thanks!

**Comment by ADXIHacker** [comment]
I'm facing the same issue, but with 1.19.2. Any fixes?

**Comment by Chew** [comment]
The referenced issue is still open, this was closed as a duplicate, please don't reply here.
