### ISSUE TITLE
Bedrock Players Can Break Shields without giving crits using axe

### ISSUE THREAD

**Issue by BooyahSquadians69** [GeyserMC/Geyser#2788]
### Describe the bug

In Minecraft Java You Have To Give Crit To Break Shield But Bedrock Players Joining Using Geyser Can Break Shields Without Giving Crits And Can Also Spam Hit Using Axe, They Dont Have Cool Down For Using Axe

Its Really Annoying Playing With This Bug

### To Reproduce

1. Set Up A Server With Geyser Plugin
2. Add 1 Player From Java And Second From Bedrock
3. The Bedrock Players Can Break Shield Without Crits And Spam Click With Axe

### Expected behaviour

The Axe Should have A Cool Down Before It Could Be Used Again As Even An Iron Axe Can Kill A Player In 2-3 CRIT And For Ppl From Bedrock With No Cool Down And All Hits From Bedrock Players Deal Max Damage In All Hits 

### Server Version and Plugins

In All Geyser Versions It Has This Bug 

Geyser version 2.0.0-SNAPSHOT (git-master-f682cf1) (Java: 1.18 - 1.18.1, Bedrock: 1.17.30 - 1.18.0/1.18.1/1.18.2)

### Geyser Dump

https://dump.geysermc.org/4quYNYzPMyuXqlZxLD3sjpLxRdteUHIK

### Geyser Version

Geyser version 2.0.0-SNAPSHOT (git-master-f682cf1) (Java: 1.18 - 1.18.1, Bedrock: 1.17.30 - 1.18.0/1.18.1/1.18.2)

### Minecraft: Bedrock Edition Version

1.18

**Comment by Camotoy** [comment]
Geyser doesn't control this behavior; this should all be handled server-side. While not impossible, I do highly doubt this is an us issue. (Also, please update to the latest Paper 1.18.1 version, which is completely compatible with 1.18 Java)

**Comment by Camotoy** [comment]
There's been no update nor other reports on this issue; I'm going to close this therefore. If this is reproducable, please send a Geyser dump and exact replication steps. Thank you!
