### ISSUE TITLE
Client-Side game time visually out of sync

### ISSUE THREAD

**Issue by Budderman18** [GeyserMC/Geyser#2790]
### Describe the bug

Any connect Geyser player will see to be out-of-sync with the in-game time (5000 ticks). This can cause issues for anything revolving around gametime, as time-based events wont appear to be eorking for any Bedrock user

### To Reproduce

1. Join any world on bedrock
2. Mess around with the time (/time set). Best results are any time from 8000-13000 ticks, where the game will be nighttime visually, but its actually daytime for the server + java players.

### Expected behaviour

Time should be perfectly in-sync

### Screenshots / Videos

![Uploading 1C820E2F-C30A-4A6B-B716-300DD644A24F.png…]()

### Server Version and Plugins

This server is running Paper version git-Paper-176 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: b164899)

Plugins (78): AdvancedReplay\*, ajParkour, AntiCheatReplay, AutoKiller\*, BedrockPlayerManager, BedWars, BentoBox, betterbroadcaster, BuildBattle, BuycraftX, Citizens, ClearLag, CommandHook, CommandSigns, ConsoleSpamFix, CrazyAuctions, Curses, Duels, Essentials, Essentials\_WarpGUI, EssentialsChat, EssentialsDiscord, EssentialsGeoIP, EssentialsSpawn, F3NPerm, Factions, floodgate, Geyser-Spigot, gProtector, GriefPrevention, GroupManager, HideAndSeek, HoloExtension, HolographicDisplays, HungerGames, Images, JukeBox, KillerMoney\*, LibsDisguises, Lobbys\*, Maintenance, MinerWare, MobArena, Morphy, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, MultiWorldMoney\*, NoteBlockAPI, Parties, PlaceholderAPI, PlotSquared, PlugReloader\*, Prison, ProtocolLib, RandomTeleport, SignShop, SilkSpawners, SkQuery, Skript, SkyblockOres, Skywars, SpigotPing, SpleefX, StaffChat, StartupCommands\*, TheBridge, Themis, TimeManager, TitleManager, TowerDefense\*, UltraCosmetics, Vault, Votifier, VotingPlugin, Warns\*, WorldEdit

### Geyser Dump

https://dump.geysermc.org/N1yMPKn8HpjCW2RPKzhW1UqPxsvKecnE

### Geyser Version

This server is running Geyser version 2.0.0-SNAPSHOT (git-master-f682cf1) (Java: 1.18 - 1.18.1, Bedrock: 1.17.30 - 1.18.0/1.18.1/1.18.2)

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

I am aware that Essentials has a feature to visually fix playertimes. My time does match the server and has not been adjusted

**Comment by Camotoy** [comment]
Can you try with no other plugins besides Floodgate and Geyser-Spigot and see if the issue is resolved?

**Comment by Budderman18** [comment]
Doesn’t seem to occur in an empty server. One other note is the time is not off sync in every world. It seems to be random when it’s unlinked or not

**Comment by Budderman18** [comment]
> Can you try with no other plugins besides Floodgate and Geyser-Spigot and see if the issue is resolved?

as mentioned above, it does not occur in an empty server. reminding as this issue is still tagged as more info needed

**Comment by Camotoy** [comment]
Are you able to figure out which plugin this is caused by? It would help the debugging process a lot.

**Comment by Budderman18** [comment]
> Are you able to figure out which plugin this is caused by? It would help the debugging process a lot.

EssentialsX is causing it. I disabled it and everything went back to normal.

Also, after reinstalling EssentialsX, it seemed to still be back to normal, so the issue *may* be fixed, although im unsure atm.

**Comment by RednedEpic** [comment]
We made some changes to our time code which may resolve this. Haven't seen anything lately on this so will close.
