### ISSUE TITLE
Bedrock players can use riptide tridents even though it's not raining or if they are not in water

### ISSUE THREAD

**Issue by jaymesss** [GeyserMC/Geyser#2791]
### Describe the bug

Bedrock players can use riptide tridents even though it's not raining or if they are not in water

### To Reproduce

1. Log on bedrock
2. Get a trident
3. Throw it in an invalid environment
4. Error

### Expected behaviour

1. Log on bedrock
2. Get a trident
3. Can't throw it in an invalid environment
4. True success!

### Geyser Version

LATEST

**Comment by Konicai** [comment]
Please share a Geyser dump by running `/geyser dump` and sharing the link. 

Regardless, with the limited information, this is likely either modified server behaviour, or there was weather desync

**Comment by Konicai** [comment]
If you can provide more information this can be reopened
