### ISSUE TITLE
Support more Minecraft Bedrock Version

### ISSUE THREAD

**Issue by mcdudu233** [GeyserMC/Geyser#2793]
### What feature do you want to see added?

Minecraft Bedrock version update quickly so support more range of Minecraft Bedrock version.

### Are there any alternatives?

like Viaversion

**Comment by Chew** [comment]
We currently already support 1.17.30+, which came out [4 months ago](https://minecraft.fandom.com/wiki/Bedrock_Edition_1.17.30). Supporting multiple Bedrock versions isn't really viable with the everyone usually being up to date, we do try to keep it a major version behind to make sure everyone is up to date, but keep in mind this protocol changes a lot so supporting a lot of versions can get really tedious, so we're not gonna spend a long time supporting something only a handful of users are gonna use. We typically only drop versions when they become what I mentioned before: too tedious to support and not a lot of users are using it.

**Comment by Camotoy** [comment]
Chew sums it up well. It's work to support more versions, and Geyser is designed to be as lightweight as possible in terms of item and block mappings. For example, if we supported 1.16, we'd have to create a system to map all the new 1.17 blocks to 1.16 somehow. 
With our extension system being developed, it is possible someone can create a ViaVersion-like system for Geyser and Bedrock clients.
Do note that beta versions are not a priority for us, as we don't know much about their changes until close to their expected release.
Thank you anyway.
