### ISSUE TITLE
Geyser Doesnt Give bedrock players Nether quartz ore EXP

### ISSUE THREAD

**Issue by Anjiitay** [GeyserMC/Geyser#2794]
### Describe the bug

When they mine Nether quartz ore it doesnt give them exp..

### To Reproduce

1. Go to the nether
2. find quartz
3. mine it

### Expected behaviour

It should give them exp

### Screenshots / Videos

https://user-images.githubusercontent.com/98748534/151793373-43ab2b38-7079-446c-8259-2dd0b70ecf3c.mp4

### Server Version and Plugins

purpur 1.18.1 
Plugins (26): AdvancedPortals, Chunky, CMILib, CoreProtect, DecentHolograms, dynmap, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), Jobs, LuckPerms, Multiverse-Core, Multiverse-Inventories, NoChunkLag, PlaceholderAPI, PlayTime*, Shop, SimpleScore, TAB, TimeIsMoney, UberEnchant, Vault, Vulcan, Wild, WorldGuard

### Geyser Version

Bungee version/build #1014

### Minecraft: Bedrock Edition Version

1.18.1

**Comment by Camotoy** [comment]
Geyser can't control server behavior like that - while not impossible, I would be very surprised if this was an us issue.

**Comment by Konicai** [comment]
If you can reproduce this on a fresh Spigot or Paper server without any plugins, let us know
