### ISSUE TITLE
Custom SmithingRecipe not show

### ISSUE THREAD

**Issue by AgentSlim** [GeyserMC/Geyser#2795]
### Describe the bug

With the Code:
`SmithingRecipe smithingRecipe = new SmithingRecipe(new NamespacedKey(this, "test"),
                new ItemStack(Material.STONE),
                new RecipeChoice.MaterialChoice(Material.STONE),
                new RecipeChoice.MaterialChoice(Material.STICK));
        getServer().addRecipe(smithingRecipe);`
        
create a custom recipe for the smithing table, in Java works but Bedrock User not show result

### To Reproduce

1. write plugin code like describe field
2. craft in smithing table

### Expected behaviour

 The Item result as specified in the code

### Server Version and Plugins

Server Version: Paper-177 (1.18.1)
Plugins: own with only recipe code to test

### Geyser Dump

https://dump.geysermc.org/xRzZxlQAqGqAbHGG4K8goeEeMPExQ3Mb

### Geyser Version

2.0.0-SNAPSHOT (git-master-7853e8c)

### Minecraft: Bedrock Edition Version

1.18.1

**Comment by Camotoy** [comment]
This may be a limitation on the Bedrock end as we cannot define custom recipes for anvils already.

**Comment by Camotoy** [comment]
I'm marking this as a confirmed bug as 1.18.10 allows/requires smithing table recipes to be sent over the network. I did try with your code and while it did work on Java, it still did not work on Bedrock.

**Comment by Xemorr** [comment]
Hi, I've just came across this bug myself 
![image](https://user-images.githubusercontent.com/31805746/186780240-433dd895-eeb7-4828-a503-941ba1756373.png)

It would be great to see this fixed!

**Comment by Camotoy** [comment]
It appears that 1.19.60 resolves this issue - the code from the original post now works. Let us know if an issue related to this comes up.
