### ISSUE TITLE
Map is lagging

### ISSUE THREAD

**Issue by LinkexaYT** [GeyserMC/Geyser#2796]
### Describe the bug

So, for some reason the map is laggy; the map doesnt sync in real-time, as i move, the map doesnt nove my location on it, and so I struggled getting to my base because of it.

### To Reproduce

1. Grab an empty map
2. Right click on the empty map
3. Look at the map
4. Move around

### Expected behaviour

It should detect movement as fast as it does on Java Edition

### Server Version and Plugins

git-Purpur-1433 (MC: 1.18)

AdvancedReplay, BambooCollisionFix, CleanroomGenerator, Coreprotect, EconomyShopGUI, Essentials, floodgate, Geyser-Spigot, ImageonMap, Luckperms, Multiverse-Core, OnePlayerSleep, ProtocolLib, SmoothTimber, TrollingFreedom, Vault, WorldEdit

### Geyser Version

2.0.0-SNAPSHOT (git-master-6cd8b33)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by Camotoy** [comment]
Maps appear to sync in real time, at least for me on Paper. Perhaps a plugin conflict, or Purpur-specific behavior?

**Comment by Jens-Co** [comment]
Ill close this due to no response. Feel free to respond at anytime if you still have this issue and ill reopen this.

Thanks.
