### ISSUE TITLE
crash with leaves

### ISSUE THREAD

**Issue by Andriyx2007** [GeyserMC/Geyser#2798]
### Describe the bug

Every time I try to pick a leaf from a tree the game and host crashes but only for minecraft bedrock in java it works fine.

### To Reproduce

enter the server (with the plugin installed) try to stay 5 minutes or pick a tree leaf and the bug is found.

### Expected behaviour

I hope they fix the error that you can play normal as before and that it doesn't crash

### Screenshots / Videos

<img width="1062" alt="Captura de Pantalla 2022-02-01 a la(s) 16 08 15" src="https://user-images.githubusercontent.com/98850265/152051661-5654d2f5-1bba-4880-97e7-f9ba26fa74b5.png">

### Server Version and Plugins

1.18.1 the only plugin is the gayser

### Geyser Dump

https://dump.geysermc.org/YVqLUIy0JVBGuct0fDNco95zsGSWiups

### Geyser Version

Build #1015 (31 ene. 2022 00:26:46)

### Minecraft: Bedrock Edition Version

1.18.1

**Comment by Camotoy** [comment]
Please try this build: https://cdn.discordapp.com/attachments/613170125696270357/929130980223094815/Geyser-Spigot.jar
