### ISSUE TITLE
Geyser-Spigot should honor the server's `enable-status` property.

### ISSUE THREAD

**Issue by NyaomiDEV** [GeyserMC/Geyser#2799]
### What feature do you want to see added?

Geyser should honor the `enable-status` server property when used as a Spigot plugin. This is important to prevent malicious actors from bruteforcing IP combinations and then collecting data via the server ping packet to then attack private Minecraft servers.

Additionally, it would be nice if it offered its own `enable-status` property in the configuration file when it is ran stand-alone or as a BungeeCord plugin, to cover other use cases as well.

### Are there any alternatives?

Currently there is no way to suppress the Geyser middleware from responding to server pings.

**Comment by Camotoy** [comment]
If you are referring to blocking the MOTD/player count from appearing on server listings, there's nothing we can do about that. Bedrock requires that information is sent, or else it thinks the server cannot be connected to. We *can* block requests specific to the Query protocol, but that appears to be a separate issue.
Sorry for the inconvenience, but thank you for reporting anyway.
