### ISSUE TITLE
Not every Chest shows up

### ISSUE THREAD

**Issue by JuniorJPDJ** [GeyserMC/Geyser#280]
I'm sad that #278 didn't fix that @DoctorMacc :<
May be also the same reason as #225 

**Screenshots / Videos**
Java:
![Screenshot_20200407_054412](https://user-images.githubusercontent.com/7334549/78627879-d9a13300-7892-11ea-84a0-d936ca0b8bdf.png)

Bedrock:
![Screenshot_20200407-052725_BlockLauncher](https://user-images.githubusercontent.com/7334549/78627628-449e3a00-7892-11ea-8bd7-92345a5bec7b.png)

**Server Version**
Paper 161

**Geyser Version**
9 build of inventory branch

**Minecraft: Bedrock Edition Version**
v1.14.1 (android arm)

**Comment by RednedEpic** [comment]
> I'm sad that #278 didn't fix that @DoctorMacc :<
> May be also the same reason as #225
> 
> **Screenshots / Videos**
> Java:
> ![Screenshot_20200407_053759](https://user-images.githubusercontent.com/7334549/78627608-351ef100-7892-11ea-8cbd-9427e69e5b73.png)
> Bedrock:
> ![Screenshot_20200407-052725_BlockLauncher](https://user-images.githubusercontent.com/7334549/78627628-449e3a00-7892-11ea-8bd7-92345a5bec7b.png)
> 
> **Server Version**
> Paper 161
> 
> **Geyser Version**
> 9 build of inventory branch
> 
> **Minecraft: Bedrock Edition Version**
> v1.14.1 (android arm)

Are the missing chests trapped chests?

**Comment by JuniorJPDJ** [comment]
Oh well, I didn't think to check tbh. Gimme a sec.

**Comment by JuniorJPDJ** [comment]
Yes, they are.
![Screenshot_20200407_054412](https://user-images.githubusercontent.com/7334549/78628002-38ff4300-7893-11ea-90d9-c03dad699002.png)
It is then #225 duplicate. I'm closing this.
