### ISSUE TITLE
Bedrock players having problems when entering a custom dimension

### ISSUE THREAD

**Issue by justme-88** [GeyserMC/Geyser#2800]
### Describe the bug

This [datapack](https://www.planetminecraft.com/data-pack/pocket-dimension/) sends you in a ramdom location in that dimension. Java players have no problems moving and placing blocks, but when Bedrock players join that dimension, they can't move no matter what they try. Disconnecting and rejoining have no effect.

### To Reproduce

1. Install datapack
2. Craft the heivlian sphere.
3. Right-click it and join that dimension.

### Expected behaviour

Move freely, smoothly and place blocks.

### Screenshots / Videos

https://user-images.githubusercontent.com/98865941/152096645-cd42d8ac-9ca3-410c-8a1a-86dbf9c68c26.mp4

### Server Version and Plugins

Pufferfish version git-Pufferfish-38 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 3e75ff0 on HEAD)
Plugins: ClearLag, GeyserSkinManager, InvSeePlusPlus, MyCommand, SimpleTpa, SkinsRestorer, StackMob, WorldEdit, WorldGuard, zItemStacker

### Geyser Dump

https://dump.geysermc.org/QKNcka7fChVCfvkmKPdKmf7akAj4FJN8

### Geyser Version

2.0.0-SNAPSHOT (git-master-f702fb4)

### Minecraft: Bedrock Edition Version

1.18.2.03

**Comment by Camotoy** [comment]
This is unfortunately a Bedrock bug - large coordinates like the area you're located in are not supported well by Bedrock. https://minecraft.fandom.com/wiki/Bedrock_Edition_Far_Lands
Thank you for reporting anyway!
