### ISSUE TITLE
An Auto ResourcePack Converter

### ISSUE THREAD

**Issue by Abrar879** [GeyserMC/Geyser#2803]
### What feature do you want to see added?

I would like a feature or option or where if the java server is usin a resourcepack then itll be converted in bedrock format and be send to the player ( as far ik server resourcepack is also probably possible in bedrock )

Or and  alternative maybe 

To Add an option to host bedrock resourcepack just like java

### Are there any alternatives?

no?

**Comment by Camotoy** [comment]
All resource-pack-related queries are funneled into #210. Thank you anyway!
