### ISSUE TITLE
In bedrock cloud not show join/leave message and achievement message

### ISSUE THREAD

**Issue by srlss123** [GeyserMC/Geyser#2806]
### Describe the bug

In bedrock cloud not show join/leave message and achievement message
I use Waterfall and paper.

### To Reproduce

1.Use waterfall-1.18-477 and spigot
2.Install Geyser-BungeeCord and floodgate-bungee
3.join game

### Expected behaviour

Java:
xxx Join the game(xxx进入了游戏)(Chinese)
xxx get a advancement(xxxx取得了进度[钻石])(Chinese)
Bedrock:
multiplayer.player.join
chat.type.advancement.task

### Screenshots / Videos

![QQ截图20220203044658](https://user-images.githubusercontent.com/78008410/152235578-ff0f3a18-9f2a-44f2-900f-73621e383352.png)
![QQ截图20220203044706](https://user-images.githubusercontent.com/78008410/152235583-55dd9abc-04f7-4df3-b500-e742e5234e69.png)
![QQ截图20220203044926](https://user-images.githubusercontent.com/78008410/152235588-d630c2f1-4d5a-4569-9984-690707acd730.png)
![QQ截图20220203044912](https://user-images.githubusercontent.com/78008410/152235590-52abf236-ee0b-4307-9cd1-3fe15679d2aa.png)

### Server Version and Plugins

floodgate-bungee #61（56Min later）
Geyser #1017
No another plugins in Waterfall and paper.

### Geyser Version

git-master-9d908c5

### Minecraft: Bedrock Edition Version

v1.18.2

**Comment by srlss123** [comment]
I install flootgate in subserver.

**Comment by Camotoy** [comment]
It appears this is the same issue as #2600, so I'm closing this issue to consolidate. Thanks anyway!
