### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by timr2000** [GeyserMC/Geyser#2809]
### Describe the bug

Players are unable to join the server

### To Reproduce

Trying to login would create this error

### Expected behaviour

Should be able to join

### Server Version and Plugins

Purpur 1547
floodgate #63

### Geyser Version

Geyser 1017 Master

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

https://pastebin.com/QTkqiDEG

**Comment by Camotoy** [comment]
Please ensure you're using the very latest Floodgate version. Otherwise, send a Geyser dump and full logs.

**Comment by timr2000** [comment]
> Please ensure you're using the very latest Floodgate version. Otherwise, send a Geyser dump and full logs.

Yes very latest version

**Comment by Camotoy** [comment]
Also if you use Floodgate on the backends, ensure that is updated.

**Comment by timr2000** [comment]
https://dump.geysermc.org/DiMO7W1D3vXFPEiZS0E6RraZbvNQI9y0
https://mclo.gs/Qip595v

**Comment by Banaantje04** [comment]
I have gotten the same issue today on test.geysermc.org. At first I thought it was because I joined at the exact same moment on both Java and Bedrock with the same username and that first time I got a different error but repeated login attempts have given me this error on Bedrock. My Java client was still able to connect.

**Comment by Camotoy** [comment]
The test server needs to be updated to the latest Floodgate version.

**Comment by Camotoy** [comment]
After debugging on Discord, the problem lies with the AlwaysOnline plugin, which overwrites the PaperAuthenticationService that calls the events our workaround requires.
