### ISSUE TITLE
Bedrock Users Loose Access to Inventory after 4-10 min

### ISSUE THREAD

**Issue by XttinaGarnet** [GeyserMC/Geyser#2810]
### Describe the bug

When bedrock users log into my server they lose access to their inventory after about 4-10 minutes on the server (possibly as late as 15 minutes). When they try logging out and logging back in the whole environment turns blue. I have the server on Apex. We have tried manual and automatic installs on both Paper and Spigot versions. We have been dealing with these problems since 1/16 and they seemed to appear with the latest update of Geyser. Additionally here are the notes from Apex on their attempts to address the issue:

According to the agents who worked on it most recently, they based the workaround from what was mentioned here: https://github.com/GeyserMC/Geyser/issues/1879

Specifically, they tried reducing the mtu size in the geyser config.yml, reducing it from 1400 to 1000. We have also tried manually installing Geyser at the newest version.

Agents who have tried to join on Pocket Edition and on Windows edition have been in the void and unable to access inventory GUI. It briefly worked on Windows edition for one agent but is not allowing them in currently either.

### To Reproduce

On a Bedrock device (there are no errors for Java users) go to the server (Please contact me for IP and Port). Wait 15 minutes and then try to move or access your inventory. 

Here are the server settings: 

Allow Flying	
Enabled
Allow Nether	
Disabled
Difficulty	
Normal
Enable Query	
Disabled
Enable Rcon	
Enabled
Force Gamemode	
Enabled
Game Mode	
Creative
Generate Structures	
Disabled
Generator Settings	
Hardcore Mode	
Disabled
Hell World	
Disabled
Level Seed	
Level Type	
default
Max Build Height	
256
Message of the Day	
A Minecraft Server
Online Mode	
Disabled

Player Idle Timeout	
-1
Player vs Player	
Disabled
Resource Pack	
Snooper Enabled	
Disabled
Spawn Animals	
Enabled
Spawn Monsters	
Enabled
Spawn NPCs	
Enabled
Spawn Protection Size	
0
Texture Pack	
View Distance	
7
Whitelisting	
Disabled
Max Tick Time	
-1
Op Permission Level	
Use /stop
Announce Achievements	
Enabled
Enable Command Blocks	
Enabled
Net Compression Threshold	
256
Max World Size	
29999984
enable-jmx-monitoring	
false
rcon.port	
25575
query.port	
25565
require-resource-pack	
false
use-native-transport	
true
enable-status	
true
broadcast-rcon-to-ops	
true
resource-pack-prompt	
sync-chunk-writes	
true
prevent-proxy-connections	
false
hide-online-players	
false
entity-broadcast-range-percentage	
100
simulation-distance	
3
rcon.password	
debug	
false
rate-limit	
0
broadcast-console-to-ops	
true
function-permission-level	
2
text-filtering-config	
enforce-whitelist	
false
resource-pack-sha1	

### Expected behavior

You should be unable to access the large inventory that you search for, but still be able to access the 9 inventory spots that are visible at all times. Your visual field may be limited (see photos) as you try to move. Moving or logging back in may result in a world turned light blue and no ability to access anything or place blocks. 

### Screenshots / Videos

![Screenshot 2022-01-30 at 2 42 13 PM](https://user-images.githubusercontent.com/2962986/152317799-206b9ecc-773a-4f94-9a4d-aa4d19ef63a0.jpeg)
![66554078293__8D5B86CA-2F68-493C-893D-56C2BD1CA873](https://user-images.githubusercontent.com/2962986/152317874-5f7315a8-2ecb-4c32-ab65-a23e01872f15.jpeg)
![Screenshot 2022-01-31 at 1 23 57 AM](https://user-images.githubusercontent.com/2962986/152317920-9e5f7a49-02d7-42e8-921a-807d26d6d2e8.jpeg)

### Server Version and Plugins

Version: Thread-207/INFO You are running the latest version

It has happened on both spigot 1.18.1 and Paper 1.18.1 

Plugins: 
CoreProtect 20.4
floodgate (from Apex auto-install and latest on geyser website: https://github.com/GeyserMC/Floodgate/)
Geyser-Spigot (from Apex auto-install and latest on geyser website: https://github.com/GeyserMC/Floodgate/)
WorldEdit Bukkit 7.2.8
WorldGaurd Bukkit 7.0.6

### Geyser Dump

https://dump.geysermc.org/SmVT4AcYkpJNbTx1xzLDkgVzpcUMBqfW

### Geyser Version

2.0.0-SNAPSHOT (git-master-9d908c5

### Minecraft: Bedrock Edition Version

v1.18.2

### Additional Context

To see the error it is important to stay logged in for at least 10 minutes on a bedrock device.

**Comment by Camotoy** [comment]
Are you able to try this build? https://cdn.discordapp.com/attachments/613170125696270357/929130980223094815/Geyser-Spigot.jar It disables encryption for Bedrock players.

**Comment by XttinaGarnet** [comment]
We've tested it using bedrock on one ipad and we had no issues (we waited 45 min). After 45 min we logged out and logged back in and then force restarted Minecraft and still had no issues.

**Comment by XiaoNiuC** [comment]
I also have the same problem, is there a solution for the latest version?

**Comment by Chew** [comment]
Did the link Camotoy provided not work for you @XiaoNiuC ?

**Comment by XiaoNiuC** [comment]
@Chew It worked fine before yesterday's Bedrock Edition update, but now I can't log in with the old version of Geyser after the update.

**Comment by XttinaGarnet** [comment]
Yes it did!

**Comment by Camotoy** [comment]
This should be the same issue as #2861, so I am closing for tidiness. Thanks!
