### ISSUE TITLE
Make customModelData translate to a resource pack tag on bedrock.

### ISSUE THREAD

**Issue by Chromozone** [GeyserMC/Geyser#2811]
### What feature do you want to see added?

On the Java version of the game, a customModelData tag can be used to specify a texture or model to change only when the item has that tag.

For example:
/give @s minecraft:iron_ingot
Would give a regular iron ingot

/give @s minecraft:iron_ingot{CustomModelData:1234567}
Would give an item with the texture, specified as 1234567.

So how would this work on bedrock?
Instead of doing the impossible and translating a whole java resourcepack to minecraft bedrock, just translate customModelData to the bedrock resource pack equivalent.

Obviously it is not the same, but it would be really cool to have a way to load the bedrock resourcepacks for cross platform custom items.

### Are there any alternatives?

There is no real way to do this as java cannot broadcast through geysermc the bedrock equivalent of customModelData (it's like a tag thingy in the meta of a bedrock resource).

**Comment by Konicai** [comment]
Resource pack translation is tracked here: https://github.com/GeyserMC/Geyser/issues/210

You can ask around in our Discord for unaffiliated forks of Geyser that support custom model data one way or another. There are a few.
