### ISSUE TITLE
Geyser isn't working with TCPShield?

### ISSUE THREAD

**Issue by tdeverx** [GeyserMC/Geyser#2812]
### Describe the bug

Sorry if I've taken this issue to the wrong repository, but I something isn't working correctly.

When I don't have TCPShield installed, everything works correctly! But, for some reason, when I add the plugin bedrock players aren't syncing correctly.

I can still login on bedrock, but I'm joining as a "guest" and it's acting like a separate account. I played around with the setting and found that this is still present even when I force floodgate account link, it logs in. When floodgate is disabled nothing pops up to login.. I think the strangest thing about this, is I correctly get kicked from the server from logging in from a different location? Super strange.

### To Reproduce

1. Install TCPShield & ProtocolLib.
2. Setup TCPShield (enable Geyser support).
3. Connect to bedrock locally (bedrock access won't be public).
4. Issues.

### Expected behaviour

For Geyser to work with TCPShield.

### Server Version

Paper version git-Paper-126 (MC: 1.18.1)

### Geyser Dump

https://dump.geysermc.org/NlLm2szfPEWq14GjRqwMo280Kyw5NgKx

### Geyser Version

Geyser version 2.0.0-SNAPSHOT (git-master-7853e8c)

### Additional Context

Apologies in advance if this isn't a Geyser issue and more of a TCPShield issue

**Comment by Camotoy** [comment]
`I can still login on bedrock, but I'm joining as a "guest" and it's acting like a separate account.`

Can you explain this in more detail? I don't quite understand.

**Comment by tdeverx** [comment]
My bad, sorry about that. I'm using LuckPerms and have some prefixes setup. So "Guest", just means the default user. When I'm logged in on java, I have prefixes, nickname, items etc.. but when I login on bedrock everything is set to default, as if it's a different user account.

**Comment by Camotoy** [comment]
Yeah, this smells like a TCPShield issue. Please send a full server log?

**Comment by tdeverx** [comment]
Sure, here you go: https://gist.github.com/tdeverx/44fd5b93dd0fe086e68dbf7babcbd2c8

**Comment by RealCallum** [comment]
Check their pricing plans, it clearly states that only certain ones support Geyser.
They will also need to provide you with a bedrock tunnel (which is currently being manually provisioned) so open a support ticket with them.

**Comment by tdeverx** [comment]
Oh sorry I should've this more clear,

> Connect to bedrock **locally** (bedrock access won't be public).

I'm not connecting to bedrock through TCPShield, I'm just using my local IP address. I don't intend on making bedrock public, its mostly just a convince thing for my friends and me to play cross platform. Only "java" will be routed through TCPShield and made public. This is why I'm confused as to why it's not working, because i'm technically not using that service for bedrock, does that make sense?

**Comment by Camotoy** [comment]
I *think* this is a TCPShield issue. It seems to be completely bypassing the Floodgate code.

**Comment by tdeverx** [comment]
Seeming that way, I'll take this issue over to their GitHub. Thanks for looking into it anyway! Appreciated it.

**Comment by hausemaster3734** [comment]
> Seeming that way, I'll take this issue over to their GitHub. Thanks for looking into it anyway! Appreciated it.
Bedrock runs on UDP. Java on TCP.

**Comment by tdeverx** [comment]
TCPShield has support for bedrock using Geyser.

**Comment by wildmaster84** [comment]
TCPShield blocks access to connecting to the server using the direct ip for security. It is not recommended to allow users to connect to your server with the direct ip, but change "only-allow-proxy-connections" to false in the TCPShield config and it will allow you to connect with bedrock.

**Comment by RednedEpic** [comment]
Steps above should work. Closing.
