### ISSUE TITLE
Add URL retrieval option for .mcpack files

### ISSUE THREAD

**Issue by Greaper88** [GeyserMC/Geyser#2813]
### What feature do you want to see added?

The final result would be to have this in GeyserConnect, predominately for console users, but may be beneficial for some edge case users, and may even provide a gateway for future java-bedrock on-the-fly resourcepack conversion. I am posting this because of several questions about custom resourcepack support for users on consoles.

The feature I am referring to would be allowing users to set a URL of a resourcepack or other mcpack file that Geyser will send to bedrock players on connect. I would imagine an option in the Geyser config to tell it to search for "local" or "remote" mcpack files to send, or even both might be useful as well. Since it currently supports sending multiple packs, this would also need to be considered to allow local files, and remote files to all be sent (as would be the use case of GeyserConnect with the GeyserOptionalPack, and the once a year x-mas pack).

### Are there any alternatives?

Since this is desired for users of GeyserConnect, particularly console users, there is not a current alternative other than using something other than a console.

**Comment by Greaper88** [comment]
https://github.com/GeyserMC/GeyserConnect/issues/55
opened and linked

**Comment by Camotoy** [comment]
After discussion on Discord, this isn't feasible to implement as stated in Geyser. The Bedrock client cannot load packs remotely, and it can only load packs on login before the world loads in.
