### ISSUE TITLE
Banner bug if placed by bedrock

### ISSUE THREAD

**Issue by candrawardana** [GeyserMC/Geyser#2814]
### Describe the bug

just like description

### To Reproduce

1. create banner
2. edit
3. place it

### Expected behaviour

banner edit works

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/38995778/152484534-ede5fb85-0fa4-4bf6-9979-109686c0ec7a.png)
left : bedrock
right : java

they are the same banner

### Server Version and Plugins

1.18.1

gsit

### Geyser Version

9d908c5

### Minecraft: Bedrock Edition Version

1.18

**Comment by Camotoy** [comment]
I'm only seeing one image. Also, please post a Geyser dump.

**Comment by Jens-Co** [comment]
Hello there, are you still having this issue? If so can you please post a Geyser dump.

issue will be closed if no response is given.

**Comment by Jens-Co** [comment]
Closed due to lack of information. If you still having trouble on this subject please update this issue with the asked information.

thanks
