### ISSUE TITLE
support ipv6

### ISSUE THREAD

**Issue by mclk623** [GeyserMC/Geyser#2815]
### What feature do you want to see added?

support ipv6，my server only has ipv6

### Are there any alternatives?

Nginx

**Comment by Camotoy** [comment]
Can you clarify in more detail? As far as we're aware, Geyser supports IPv6.

**Comment by Tsukikoh** [comment]
I also came here looking for help.
You can access Bedrock (iPad) with an IPv4 address or a domain name that only has an A record (IPv4).
However, domain names with AAAA record (IPv6) cannot be accessed.
Even with IPv6, the server name and ping will be displayed.

**Comment by Tsukikoh** [comment]
I found a solution.
Normally we have IPv4 and IPv6 UDP 19132 ports open, but we will additionally open IPv6 UDP 19133 port.
Even if you change from port 19132, you still need the IPv6 UDP 19133 port if you want to use IPv6.
I could not find a way to change this port number.

**Comment by RednedEpic** [comment]
The steps mentioned above should work & we support IPv6 to my knowledge. Please feel free to comment clarifying if this is not what you meant. Closing.
