### ISSUE TITLE
Minecraft wont let me load into the server, it just says "Unable to connect to world".

### ISSUE THREAD

**Issue by NotFitergem** [GeyserMC/Geyser#2816]
### Describe the bug

Whenever I load up my server, I try to join on my Minecraft Win 10 version, and it doesn't let me. I can still connect on Java, just not on bedrock. I have a feeling it has something to do with Geyser or Floodgate, but I'm not really sure which one, or what the issue would even be. I did some research on it and it sounds like it has something to do with installing Nukkit on your server, and then reinstalling paper or something like that, but I'm not really sure. If someone would be able to help me with this that would be great!

(I am running Paper - 1.18.1: Latest, on my server right now. I also am using PebbleHost as my server hosting provider.)

### To Reproduce

I'm not really sure what to write here, I'm kinda new to all of this.

### Expected behaviour

I expected to be able to join my server on bedrock right away after I configured GeyserMC, but that didn't seem to work as I had thought.

### Server Version and Plugins

The server version is Paper 1.18.1 LATEST.

### Geyser Dump

https://dump.geysermc.org/0gqcZ8Zv2OMUTltdYI7EplxEEdbLSLWO

### Geyser Version

Build #1017 Geyser-Spigot.jar

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by Camotoy** [comment]
That Nukkit step is generally outdated and likely won't work for Spigot+ setups either. Unable to Connect to World means the Bedrock client cannot find/reach your server. See https://github.com/GeyserMC/Geyser/wiki/Fixing-'Unable-to-Connect-to-World' for a list of troubleshooting steps, or join our Discord. Thank you!
