### ISSUE TITLE
cant join on bedrock

### ISSUE THREAD

**Issue by windetrsfugwq** [GeyserMC/Geyser#2817]
### Describe the bug

cant join on bedrock no errors on logs and the plugin is ruining
but just the bedrock stuff is not working 
no not even the web stuff can see it
and yes java players can join
and commands work

### To Reproduce

make a paper sever 
add gizer and floodgate
run 

### Expected behaviour

well i expected it to run like it normlle does 

### Screenshots / Videos

just the message of cant connect to word 

### Geyser Dump

https://dump.geysermc.org/RUuKT27FisDZlDHdKxQNLnJxX3FOLvo1

### Geyser Version

2.0.0-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by windetrsfugwq** [comment]
i do love this plugin and i thank you so much for making it

**Comment by Chew** [comment]
This is covered by our [wiki page here](https://github.com/GeyserMC/Geyser/wiki/Fixing-'Unable-to-Connect-to-World').
If you need further assistance, please join us on [Discord](https://discord.gg/geysermc). Thank you anyway.
