### ISSUE TITLE
Windows 10 localhost help

### ISSUE THREAD

**Issue by AndyBaBaBoi** [GeyserMC/Geyser#2824]
### Describe the bug

Hello, I am trying to get this to work. At the moment only with my pc and not online yet. I am trying to join on windows 10 when it says that I am not able to connect. I already went through the common issues on the unable to connect section. I tried the two ways of fixing it but the first one with the windows powershell said "Error: Access Denied, run the command as an administrator". If someone could help that would be great.

### To Reproduce

idk

### Expected behaviour

I was supposed to join the server or in the powershell thingy it was supposed to say "Ok."

### Server Version and Plugins

1.18.1 on spigot
floodgate
geyser

### Geyser Dump

https://dump.geysermc.org/uZHgBsIVCZfbTJN2PDxnRppmkA7bgfuq

### Geyser Version

The latest one I just pressed the download button.

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by YHDiamond** [comment]
Please join our discord server for support (discord.gg/geysermc).

**Comment by YHDiamond** [comment]
And please close this issue

**Comment by YHDiamond** [comment]
Thank you camotoy
