### ISSUE TITLE
1.18.1 - Bedrock players unable to see custom enchantments

### ISSUE THREAD

**Issue by djoveryde** [GeyserMC/Geyser#2828]
### Describe the bug

I'm currently using a plugin called "Excellent Enchants (https://www.spigotmc.org/resources/excellentenchants-vanilla-like-enchantments-1-16-1-18.61693/)", and the latest as of (10th February) version of Geyser-Spigot.
For some reason bedrock players are unable to see any enchantments outside of vanilla ones both as a drop from the enchanting table and if given an item with custom enchantments on it (they are only able to see the vanilla enchantments on the item).

### To Reproduce

Run both Geyser-spigot and excellent enchants plugin on a paperspigot server. 
Add a custom enchant on an item and give it to a bedrock player. 
The bedrock player will be unable to see any enchantment that came from excellent enchants.

### Expected behaviour

Bedrock players should be able to see and use enchantments that the plugin injects into the server.

### Geyser Version

1.18.1 - #1024

### Minecraft: Bedrock Edition Version

Latest update

**Comment by Camotoy** [comment]
Oops, wrong issue here, sorry!

**Comment by Camotoy** [comment]
I'm unable to replicate on 1.18.0 Paper - I pulled a netherite sword from creative mode on Java Edition, then ran `/excellentenchants enchant bunny_hop 1` and dropped it to a Bedrock player. Is there some permission node getting in the way?

**Comment by RednedEpic** [comment]
Closing due to lack of response.

**Comment by Krazytrain** [comment]
I know this might of been closed as no response but iv got the same issue. 
For more detail on this:
Java and bedrock players can see the enchantments on the items but bedrock players cant add them to there gear.

To create this bug place a anvil and sword and one off Excellent Enchants books into the anvil to add it. 
The Excellent Enchant is not showing it can be added onto the sword.

If you do the same on java it works how it should but for some reason it dont show at all for bedrock but the Excellent Enchant does show on the sword when its added.

If you can reopen this and look into it for me please would be helpful.
