### ISSUE TITLE
Inventory Name Sync 

### ISSUE THREAD

**Issue by carbinerr** [GeyserMC/Geyser#2829]
### What feature do you want to see added?

is it possible to sync the inventory in java and bedrock? I've been searching how to remove the PREFIX period(.) in the name when playing bedrock, 'cause I have saved inventory in java. 

Example:
Java Username: Username (lots of items)
Bedrock Username: .Username (no items)

### Are there any alternatives?

none

**Comment by YHDiamond** [comment]
That already exists. 
https://github.com/GeyserMC/Floodgate/wiki/Features#what-is-global-linking
