### ISSUE TITLE
Loading in with certain blocks causes crash (Inventory branch)

### ISSUE THREAD

**Issue by DoctorMacc** [GeyserMC/Geyser#283]
**Describe the bug**

On the inventory branch, going into the End crashes the Bedrock client. Geyser and the Java server still believe the user is connected until they time out. The master branch has no such issue.

**To Reproduce**

**Server Version**
Paper 161

**Geyser Version**
Geyser Inventory 9

**Minecraft: Bedrock Edition Version**
1.14.30

**Comment by suerion** [comment]
it is also in spigot, with bungeecord, i can't jump to an other server

**Comment by Loganh4005** [comment]
> it is also in spigot, with bungeecord, i can't jump to an other server

It doesn't happen to me but to fix it maybe it needs a merge with master??

**Comment by steviebeenz** [comment]
> > it is also in spigot, with bungeecord, i can't jump to an other server
> 
> It doesn't happen to me but to fix it maybe it needs a merge with master??

Upvote!

**Comment by DoctorMacc** [comment]
The problem appears to not be The End but rather the End Portal and End Gateway blocks. End portal blocks are fine in the overworld.

**Comment by DoctorMacc** [comment]
Fixed with #306.
