### ISSUE TITLE
Linked Account Skin No Longer Working

### ISSUE THREAD

**Issue by waddon1** [GeyserMC/Geyser#2832]
### Describe the bug

My Linked Java account skin is no longer loading on bedrock. Not 100% certain, but I think it only stopped working after the bedrock 1.18.10 update.

### To Reproduce

1. Link bedrock and Java accounts
2.  Join Geyser Server
3. Skin is steve instead of custom java skin

### Expected behaviour

Skin uses custom java skin

### Server Version and Plugins

git-Purpur-1554 (MC: 1.18.1)

### Geyser Dump

https://dump.geysermc.org/b1iVRk6RbERSkb8NMzmKTFR3cloYkn1j

### Geyser Version

2.0.1-SNAPSHOT (git-master-44af9da)

### Minecraft: Bedrock Edition Version

1.18.10

**Comment by waddon1** [comment]
Slight update on this. If you login from java edition first and then leave and join from bedrock the skin will then load on bedrock edition. When it should load even if you joined with the bedrock account.

**Comment by Camotoy** [comment]
While not 100% confirmed, I believe I have seen this behavior and one of our fixes is likely suspect.

**Comment by Camotoy** [comment]
Floodgate build 65 should address this.

**Comment by aytimothy** [comment]
Still not working for me; https://dump.geysermc.org/b1qWBLuSvVVeBvFpx2CgwViQ9xbz8V8T

![image](https://user-images.githubusercontent.com/7418834/159151186-1addf21c-872f-4904-a2b0-072b35377bee.png)

I've upgraded to the latest version of Geyser (Build 1058; 2.0.2-SNAPSHOT) and Floodgate Build 65; 2.1.0-SNAPSHOT)
