### ISSUE TITLE
Kick Alt Accounts

### ISSUE THREAD

**Issue by UltimateSoviet** [GeyserMC/Geyser#2835]
### What feature do you want to see added?

You really should add an option to disable kicking accounts on the same internet. My and my friends' siblings can't play on my server.

### Are there any alternatives?

I tried doing a deep code search, which ended up being unsuccessful.

**Comment by Camotoy** [comment]
We don't do any managing of players per their IP addresses. (We don't even kick players if they're already on Geyser; we let the backend server handle that). If this was an us issue I would be very, very surprised. 
Best of luck.
