### ISSUE TITLE
Lily pads cannot be placed on mobile

### ISSUE THREAD

**Issue by nyatoru** [GeyserMC/Geyser#2836]
### Describe the bug

Lily Bug

### To Reproduce

1.place
2.disappear

### Expected behaviour

edited to be normal

### Screenshots / Videos

Uploading Screenrecorder-2022-02-14-05-59-08-281.mp4…

### Server Version and Plugins

latest

### Geyser Dump

no

### Geyser Version

2.0.1

### Minecraft: Bedrock Edition Version

1.18.10

**Comment by Jens-Co** [comment]
Hi there! 

Looks like your video/screenshot was not uploaded correctly. can you please re-add it? Also include an dump file ( console command; geyser dump. 

thanks!

**Comment by YHDiamond** [comment]
And expected behavior is just a . Can you please fix that?

**Comment by nyatoru** [comment]
Uploading Screenrecorder-2022-02-14-05-59-08-281.mp4…

**Comment by YHDiamond** [comment]
You're pressing send before the video actually uploads. Wait till it fully uploads before sending the comment

**Comment by nyatoru** [comment]
https://streamable.com/51k7zi

**Comment by nyatoru** [comment]
https://dump.geysermc.org/U70XCUGluR7VdZp5AL2TYhAXw6u1wPsr
