### ISSUE TITLE
Disable-bedrock-scaffolding cause block rollback 

### ISSUE THREAD

**Issue by tbvns2** [GeyserMC/Geyser#2840]
### Describe the bug

When a Bedrock player tries to make a bridge like a java player, the placed block will roll back 1 out of 20 times.

### To Reproduce

1. Install geyser
2. Set Disable-bedrock-scafolding to true
3. Try to make a bridge
4. Fall

### Expected behaviour

Block don't get rollback when a player is bridging like a java player

### Screenshots / Videos

https://user-images.githubusercontent.com/88189738/154678838-ffe27819-63c8-4645-a95d-9af80731afaf.mp4

### Server Version and Plugins

Waterfall(with geyser): git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477
Paper: 1.8.8

### Geyser Dump

https://dump.geysermc.org/C6bqId1yFeRIZ1Mw2JNHenSZnucQmMaA

### Geyser Version

2.0.1-SNAPSHOT (git-master-31fd57a)

### Minecraft: Bedrock Edition Version

1.18x

### Additional Context

That a big issue in Bed wars and Sky wars because they die without any reason

**Comment by RednedEpic** [comment]
Unable to replicate. Please let us know if this works on a supported server platform (anything 1.12.2+).
