### ISSUE TITLE
per server texture pack / per server custom model

### ISSUE THREAD

**Issue by Creeperz653** [GeyserMC/Geyser#2841]
### What feature do you want to see added?

so if you have an network you dont  need geyser on backends but i want to do per server texture pack  /  per server custom model if that comes out  Why?
I dont want all the servers to have same texture pack

### Are there any alternatives?

not really

**Comment by tbvns2** [comment]
Good idea

**Comment by Camotoy** [comment]
Looks like this is a duplicate of #2005. Thank you anyway! (Do note the limitations EasyClifton posted on that issue).
