### ISSUE TITLE
Players can't wake up villagers.

### ISSUE THREAD

**Issue by XIAYM-gh** [GeyserMC/Geyser#2842]
### Describe the bug

Players can't wake up villagers while villagers are sleeping.

### To Reproduce

1. Go to the next of a sleeping villager
2. The "Trade" button appears
3. Click on the button
4. Nothing happened

### Expected behaviour

The village could wake up by the button or by interacting it

### Server Version and Plugins

Server version: 1.18.1 paper

### Geyser Dump

https://dump.geysermc.org/fNVjxo9BErjRweUvY7zZ8ovRNNedFE7y

### Geyser Version

1.2.1-SNAPSHOT (git-master-31fd57a)

### Minecraft: Bedrock Edition Version

1.18.10

### Additional Context

I also tried interacting with it by long pressing it, but it didn't wake up.

**Comment by Konicai** [comment]
Pretty sure Java Edition players can only wake up villagers by breaking the bed. If I'm correct, this is expected behaviour, despite bedrock players thinking they can.

**Comment by XIAYM-gh** [comment]
Oh It's my fault XD
In fact, JE players need to interact with the bed and is'nt the villager
