### ISSUE TITLE
Arrow movement when shot

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#2844]
### Describe the bug

When shooting an arrow from a bow, it slowly transitions from the player to its destination.

### To Reproduce

1. Get a bow and arrow
2. Shoot it (I pulled the bow fully back)
3. Watch as it fires in a choppy motion

### Expected behaviour

Arrow movement should be smooth, or at least much smoother as it looks like the player (Bedrock) is lagging.

### Screenshots / Videos

https://user-images.githubusercontent.com/41856020/154472015-f18c7252-5c39-499f-8b25-9becc28d8570.mp4

### Geyser Dump

https://dump.geysermc.org/2swlbPQ7nFFUi7OcUgzHuzm0DLVmA3AD

### Geyser Version

2.0.1-SNAPSHOT (git-master-31fd57a)

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by pinkpig58** [comment]
Also replicable on Windows (multi-platform issue):
https://user-images.githubusercontent.com/41856020/157545188-a6abb5a3-bf9b-4b0f-8a2a-00fc7174d2e5.mp4

**Comment by onebeastchris** [comment]
Unable to replicate, closing.
If you can still reproduce this, send a geyser dump & video please

**Comment by jordanrmc** [comment]
Hope this gets fixed soon

**Comment by SleepyPopp** [comment]
Feel free to make a new GitHub issue with the necessary information to reproduce this Geyser issue. This one was closed due to being unable to be replicated.
