### ISSUE TITLE
Eating food animation with full hunger in peaceful mode

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#2845]
### Describe the bug

The eating animation is displayed when trying to eat with full hunger in peaceful mode

### To Reproduce

1. Set the server to peaceful
2. Give yourself food
3. Ensure you have full hunger
3. Try to eat the food

### Expected behaviour

No animation should display when trying to eat the food with full hunger

### Screenshots / Videos

https://user-images.githubusercontent.com/41856020/154474847-8b751473-cfdb-4d57-beb9-b6446f38b935.mp4

### Geyser Dump

https://dump.geysermc.org/OyY8R6hlptOA2UmWMrphweufB6VaNUvF

### Geyser Version

2.0.1-SNAPSHOT (git-master-31fd57a)

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by AnhNguyenlost13** [comment]
Can recreate 100% of the time with bread.

**Comment by onebeastchris** [comment]
Been able to replicate - weird one

**Comment by onebeastchris** [comment]
This seems to be a Bedrock thing ™️ - even in a singleplayer Bedrock world, it's possible to eat any food item while in peaceful difficulty. 
Maybe it's possible to work around this by not telling Bedrock clients about the difficulty - it shouldnt even change much as most things are server-side controlled (damage, hunger..)
