### ISSUE TITLE
MCPE: dropping items when cancelled

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#2846]
### Describe the bug

Only found on PE: when attempting to drop an item (when the event is canceled) the client visually shows the item gone from the hotbar, however, the item reappears when the inventory is updated.

I was thinking that this could be client-side, but I tested the same thing on a clean Nukkit server with the same event canceled and it didn't remove the item on the player's side.

### To Reproduce

1. Have a server that cancels the PlayerDropItemEvent
2. Connect and select a slot that has nothing in
3. Attempt to drop the item by pressing down the item in the hotbar
4. See the item disappear

It might take a few attempts, but I have been able to replicate this multiple times.

### Expected behaviour

The item should visually remain in the player's hotbar and not be removed.

### Screenshots / Videos

https://user-images.githubusercontent.com/41856020/154475990-33d9e6a7-e6a6-4caa-99c8-63955cae0d1d.mp4

### Geyser Dump

https://dump.geysermc.org/OyY8R6hlptOA2UmWMrphweufB6VaNUvF

### Geyser Version

2.0.1-SNAPSHOT (git-master-31fd57a)

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by Camotoy** [comment]
I'm unable to replicate this on Spigot and Paper 1.12.2:
```java
    @EventHandler
    public void drop(PlayerDropItemEvent event) {
        event.setCancelled(true);
    }
````
Cancels the drop event and places the item back in a player's inventory correctly. Can you send example test code?

**Comment by pinkpig58** [comment]
The code is exactly the same as mine. Did you try this on a touchscreen device?

**Comment by Camotoy** [comment]
Yes; I tried on an iPhone 8.

**Comment by pinkpig58** [comment]
Tried this on an Android again and still faced the same issue, so was able to replicate it even after closing Minecraft and the server

https://user-images.githubusercontent.com/41856020/155295123-3aa93925-ff84-4883-8640-57182afce707.mp4

**Comment by Camotoy** [comment]
Oh, I think I didn't try it with the different slot thing. Will re-test tonight.

**Comment by Camotoy** [comment]
So, uh, the bigger picture was that dropping items from any other slot, across the board, did not work.
