### ISSUE TITLE
Whitelist command not working anymore

### ISSUE THREAD

**Issue by agoniaprivat** [GeyserMC/Geyser#2847]
### Describe the bug

/whitelist add -Halvnaket
(Or any other bedrockuser) 

Is no longer working. Worked for some previous patches ago.

### To Reproduce

Whitelist a bedrock user

### Expected behaviour

Makes the player able to login with whitelist on

### Screenshots / Videos

-

### Server Version and Plugins

Paper:
![2022-02-17_23 06 57](https://user-images.githubusercontent.com/50961682/154578879-e29f3066-535e-46a5-bfe5-d775ada8c21f.png)

Geyser:
![2022-02-17_23 05 28](https://user-images.githubusercontent.com/50961682/154578816-344217df-af6c-4ef3-846e-59697c847f17.png)

### Geyser Version

Se above

**Comment by Camotoy** [comment]
Please use the `fwhitelist` command to add Bedrock players.
