### ISSUE TITLE
Shift-Clicking Enchanted Items

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#2849]
### Describe the bug

When on PC (Bedrock), you're unable to shift-click certain items that are enchanted into a chest.

### To Reproduce

1. Get an enchanted item (mine was an Unbreaking 2, Efficiency 1 Diamond Axe)
2. Attempt to shift-click it into a chest

### Expected behaviour

Items should transfer to the next available slot in the chest.

### Screenshots / Videos

https://user-images.githubusercontent.com/41856020/154664595-f5cca6dd-b8c3-4537-aa9a-1cb9f151c58c.mp4

### Geyser Dump

https://dump.geysermc.org/xu10HBInqy1kCnURU1PPPeqcbMleTN8b

### Geyser Version

2.0.1-SNAPSHOT (git-master-31fd57a)

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by onebeastchris** [comment]
this one seems to have been fixed some time ago, just tried it - i had no issues shift-clicking enchanted items into chests/shulkers

**Comment by pinkpig58** [comment]
I appear to still be having this issue.

**Comment by onebeastchris** [comment]
Does this issue still occur with the latest version of Geyser? If it does, please send a new Geyser dump.
