### ISSUE TITLE
Block placing is glitchy

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#2851]
### Describe the bug

When placing blocks by holding the block place button down (like Java bridging), the blocks begin to disappear and the player falls.

### To Reproduce

1. Pile up
2. Attempt to bridge as you would on Java, holding the block place button down as you move

### Expected behaviour

This is what happens on a single player Bedrock world:

https://user-images.githubusercontent.com/41856020/154669107-f56105ef-06d1-418a-ba0a-34f870cf69d8.mp4

### Screenshots / Videos

This is what happens when on a Geyser server:

https://user-images.githubusercontent.com/41856020/154669148-0639e197-1429-4781-bb18-991749607dd6.mp4

### Geyser Dump

https://dump.geysermc.org/xu10HBInqy1kCnURU1PPPeqcbMleTN8b

### Geyser Version

2.0.1-SNAPSHOT (git-master-31fd57a)

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by tbvns2** [comment]
Do you have disable-bedrock-scafolding set to true ?

**Comment by pinkpig58** [comment]
@tbvns2 Ah, I see. At least the issue can be confirmed on a clean server with no plugins.
