### ISSUE TITLE
Perpetual Lag for Bedrock players

### ISSUE THREAD

**Issue by MmeCromatique** [GeyserMC/Geyser#2855]
### Describe the bug

After a few seconds bedrock player end up in a "non sync state" they cannot recieve info from the server and are not even disconnected, this is True for Switch PC and Android, they basically cannot play

### To Reproduce

1. Log In to the server from Bedrock
2.After 1 minute it unsync

### Expected behaviour

Be able to play

### Screenshots / Videos

https://user-images.githubusercontent.com/73028175/154858420-3a0c17f0-c9f4-4c60-9170-628cc2044cfc.mp4

You can see in this video the cooldown stopping updating and the world freezing like the Iron Golems

### Server Version and Plugins

This server is running Paper version git-Paper-205 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 36a1650)
You are running the latest version
Previous version: git-Paper-175 (MC: 1.18.1)
 -LickPerms
-CoreProtect
-FallingOverride
-Floodgate
-Geyser
-Invsee++
-ServerRestorer
-Stress
-tabtps
-worldedit

### Geyser Dump

https://dump.geysermc.org/DqZ8uZIJmzo3kFD1uy4DIddaGwO11ceZ

### Geyser Version

Geyser version 2.0.1-SNAPSHOT (git-master-252348e)

### Minecraft: Bedrock Edition Version

1.18.12

### Additional Context

Additionnally this server is running on AMP on a physical machine I have access to.

**Comment by Camotoy** [comment]
Are you using a 10th or 11th generation Intel processor? If so, add the JVM arguments `-XX:+UnlockDiagnosticVMOptions -XX:-UseAESCTRIntrinsics` to your startup.

**Comment by MmeCromatique** [comment]
> 

Yes, i7-11700, it seems to have solved the issue. What did caused it ?

**Comment by Camotoy** [comment]
We don't know yet. However, as this issue is reported in other places, I will close this issue.
