### ISSUE TITLE
Combine Geyser and floodgate into one plugin

### ISSUE THREAD

**Issue by Budderman18** [GeyserMC/Geyser#2856]
### What feature do you want to see added?

I feel as this is necessary, because running a geyser server without floodgate is pretty pointless. All bedrock users would need a java account to even play, which basically defeats the purpose of even having bedrock support in the first place. So to help clear up some possible confusion with setting both of these up, it would be nice if Geyser and Floodgate were combined into one, and then have an “online-mode” setting that would toggle between enabling and disabling Floodgate’s features.

### Are there any alternatives?

Using geyser and floodgate as separate plugins.

**Comment by Konicai** [comment]
This is planned eventually

**Comment by Budderman18** [comment]
> This is planned eventually

Good to know. You can close this now.
