### ISSUE TITLE
No server response after some time. player stuc in something like "timeout" status?

### ISSUE THREAD

**Issue by janiiik** [GeyserMC/Geyser#2857]
### Describe the bug

After some time bedrock player end up in status when he is unable to see block break animation, nor chat is refreshing for player, sometime player see only blue sky with no blocks.  After a minute or so server starts to respond and all breaked blocks will reapear at once, chat messages will be recieved etc. I know that simillar issue happening with intel processors, mentioned here #2855. This looks like solved with adding additionals flags for java startup. But I am experiencing similar issue on AMD Ryzen CPUs. I have tried to test in on official geyser test server but it seems to work well there with no issues. So after attempts to solve issue myself I would like to ask you for help. 

### To Reproduce

- login to server 10 times in a row
- break some blocks
- over some time player is not synced with server correctly

### Expected behaviour

standard response times

### Screenshots / Videos

LONGER VIDEO:
https://user-images.githubusercontent.com/33089907/154983203-f2b0b162-b290-4ace-9c51-f3f6ec7d7847.mp4
SHORT GIF:
![Project 1](https://user-images.githubusercontent.com/33089907/154983362-15c3a543-1e0e-4714-9005-245e2d52a418.gif)

### Server Version and Plugins

[15:19:43 INFO]: This server is running Paper version git-Paper-207 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: b757019)
You are running the latest version

### Geyser Dump

https://dump.geysermc.org/DqJTKdI6OUKoys2pFHLVHucRVEOGkhoS

### Geyser Version

2.0.1-SNAPSHOT (git-master-252348e)

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by Camotoy** [comment]
Are you able to try without any scoreboard plugin?

**Comment by RednedEpic** [comment]
Closing due to lack of response.
