### ISSUE TITLE
Same But Bedrock 

### ISSUE THREAD

**Issue by CPlayxs** [GeyserMC/Geyser#2858]
### What feature do you want to see added?

It would be nice if you make the same plugin again but for bedrock, because you have to create a java server and put the plugin on it, but if the plugin were made for bedrock you can create a server for bedrock but the people from java can enter the bedrock server, although I think it would be somewhat difficult to do it but I think they could be based on the java code to do it again.

### Are there any alternatives?

Or it could be a server like before instead of a plugin like before

**Comment by RednedEpic** [comment]
This would require a substantial amount of work and is not something that we'd build into Geyser itself. This may be something we look in to in the future as it's own application but as it stands it will not be a feature of Geyser itself. Thanks for the suggestion though!
