### ISSUE TITLE
Geyser API

### ISSUE THREAD

**Issue by wildmaster84** [GeyserMC/Geyser#2859]
### What feature do you want to see added?

An api to hook into to check information about a bedrock player.

It would make back backwards compatibility much easier if there was an api to check if a user is on bedrock for developers to disable java features within server plugins or finding information to store for the player like the XUID for date and much more.

### Are there any alternatives?

Currently no alternatives.

**Comment by Jens-Co** [comment]
Hello, We are planning on changing the API but cannot give any eta's.

Floodgate got some decent api that you can use for checking if a player is a bedrock player and other things to!

https://wiki.geysermc.org/floodgate/api/ 
https://wiki.geysermc.org/floodgate/player/

**Comment by Camotoy** [comment]
Geyser already has a very basic API if you need Geyser: https://wiki.geysermc.org/geyser/using-geyser-or-floodgate-as-a-dependency/
As such, I will close. Thanks anyway!
