### ISSUE TITLE
Custom player heads display on mcbedrock 

### ISSUE THREAD

**Issue by Muzaki1** [GeyserMC/Geyser#2860]
### What feature do you want to see added?

Currently, on mcbedrock connecting to a geyser server you wont be able to see any custom heads like you would on java. This makes things look kinda weird when decorations or custom mobs that use player heads show up as generic steve heads

its not really anything important, but it would make things nicer

### Are there any alternatives?

something i do is i just retexture the steve heads and use that as a bedrock resourcepack, although its kinda clunky cuz then i have to restart the server every time i make a new custom head

**Comment by YHDiamond** [comment]
This is already a feature (at least for blocks). As of now, displaying heads in inventories isn't possible without clunky workarounds, but having them as blocks already works.

**Comment by Camotoy** [comment]
Yup, this is a limitation on Bedrock's end, and for armor stands we have this listed under #782. Thanks anyway!
