### ISSUE TITLE
I can't use player_head to show bedrock. This is bugs?

### ISSUE THREAD

**Issue by srlss123** [GeyserMC/Geyser#2862]
### Describe the bug

I can't use player_head to show bedrock. This is bugs?

### To Reproduce

1.Use Geyser
2.Enter server
3.give a player_head
4.It's steve

### Expected behaviour

All player_head in bedrock is steve

### Geyser Version

git-master-7bd5b59

### Minecraft: Bedrock Edition Version

1.18.10

**Comment by Camotoy** [comment]
Custom player heads don't exist on Bedrock. This is documented as a known limitation. Thanks anyway!
