### ISSUE TITLE
[1.18.1] Renaming items in anvil is finicky

### ISSUE THREAD

**Issue by creativegamer03** [GeyserMC/Geyser#2863]
### Describe the bug

Renaming an item suddenly reverts back to original name. Trying to rename an item is now more difficult, however, with the exception of bows (since I managed to painstakingly renamed it to "shut yo <random invalid ip address>" whilst having this painful bug). The bug is more obvious with long names than short ones.

### To Reproduce

1. Have an item with a long name **originally**.
2. Use an anvil.
3. Try to rename it.

### Expected behaviour

It should rename the item as what I wanted it to be named.

### Screenshots / Videos

https://user-images.githubusercontent.com/66676126/155452823-aade11ae-af50-41c4-af5b-8f4699d603d3.mp4

### Geyser Version

Geyser (git-master-44af9da) 1.18.10 (Vanilla)*

### Minecraft: Bedrock Edition Version

1.18.120

### Additional Context

As I said earlier, it's only noticeable on longer names.
For example: "Diamond Sword"
Trying to clear it will revert it immediately.

However, "Bow" is the shortest name I can find which is easier to rename.

_* according to mcsrvstat.us since I can't contact the admin at this time._

**Comment by Konicai** [comment]
If you can provide more information about the server, such as a Geyser dump, this issue can be reopened. For now this report is essentially incomplete

**Comment by creativegamer03** [comment]
Hmmm ok I found more information about this when I compare it with renaming it via anvil on different dimensions.
Renaming the item in the overworld is less buggy than renaming the item in the end.
