### ISSUE TITLE
Behaviour Packs To Java Custom Model Data Items

### ISSUE THREAD

**Issue by LimeDev8756** [GeyserMC/Geyser#2865]
### What feature do you want to see added?

Allowing Behaviour Packs In Geyser To Add Custom Ideas Which Can Translate Into Java CustomModelData Items

### Are there any alternatives?

No Alternatives

Edit : Translates Bedrock Behaviour Packs Into Java Items With Custom Tags Alongside CustomModelData

**Comment by Konicai** [comment]
Behaviour packs are for modifying bedrock edition servers, which Geyser isn't

Apart from that though, custom model data is currently being worked on by some people. There is a thread in our Discord about it. Also resource pack translation/CMD mapping is tracked here: https://github.com/GeyserMC/Geyser/issues/210
