### ISSUE TITLE
Bug when shifting (sneaking) and jumping when there is 1 block directly above you

### ISSUE THREAD

**Issue by Minionguyjpro** [GeyserMC/Geyser#2866]
### Describe the bug

When you shift and jump when there is a block directly above you (0 blocks between you and the first next block, you directly see a block) you are for a very small time inside the block.

### To Reproduce

1. Go into a server with Geyser from Bedrock Edition
2. Place a block directly above you
3. Hold shift and jump there
4. You now are a very small amount of time inside the block

### Expected behaviour

Not get inside the block, just touch the block its edge and get back directly to the ground.

### Screenshots / Videos

https://user-images.githubusercontent.com/66115754/155674398-ac30d371-2dde-42c0-8bae-e549c10b1773.mp4

### Server Version and Plugins

git-Purpur-1564 (MC: 1.18.1)
Plugins (10): ClearLag, floodgate, Geyser-Spigot, Hibernate, LaggRemover, spark, StackMob, ViaBackwards, ViaRewind, ViaVersion

### Geyser Dump

https://dump.geysermc.org/Jav4QbkWRTkJSk459aPo20YmCJPUWXvX

### Geyser Version

2.0.1-SNAPSHOT (git-master-7bd5b59)

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by Konicai** [comment]
This can probably be closed in favour of https://github.com/GeyserMC/Geyser/issues/2742
