### ISSUE TITLE
Bedrock client joins in Survival on a Creative server and cannot switch gamemode

### ISSUE THREAD

**Issue by code-monet** [GeyserMC/Geyser#2869]
### Describe the bug

Reported previously, eg #2492.

I have a creative mode server running, where if I join from a Java client, it joins in creative mode as expected. However, when connecting from Bedrock, the gamemode is Survival, and cannot be changed from client side settings.

If I delete my (bedrock) .dat file from the world/playerdata dir, restart the server and reconnect, then I join in Creative mode as expected. However, there's still something funny - in the client Settings, server game mode is apparently "survival", but personal game mode is "creative", and still cannot be changed. If I restore the old .dat file and (restart and) reconnect, then the issue is replicated.

I can try replicating, but it will be tedious - would the offending .dat file help (attached)?
[offending_player.zip](https://github.com/GeyserMC/Geyser/files/8159948/offending_player.zip)

### To Reproduce

Not sure. I have an offending player .dat file, but don't know how to reproduce otherwise.

### Expected behaviour

When connecting the Creative server from Bedrock client, client should a) join in the default Creative mode, and b) maybe be able to change personal gamemode from settings?

### Server Version and Plugins

This server is running CraftBukkit version 3443-Spigot-699290c-2c1e499 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
[08:26:24] [Server thread/INFO]: Checking version, please wait...
[08:26:24] [Thread-13/INFO]: You are 2 version(s) behind

Also using:
ViaVersion v4.2.1
floodgate v2.1.0-SNAPSHOT

### Geyser Dump

https://dump.geysermc.org/jzBQXQY1QudtmbehXMcATMa5kjtoerX6

### Geyser Version

2.0.2-SNAPSHOT (git-master-0fd903e)

### Minecraft: Bedrock Edition Version

1.18.12

### Additional Context

I'm not sure what led to the offending .dat file being created in the first place, so a bit of history:
1. The server originally existed as a vanilla Java server.
2. I added GeyserMC stand-alone a couple of days ago from master, and was able to connect from Bedrock in creative.
3. A few hours ago I added Spigot to the server, and installed GeyserMC as a plugin, along with floodgate (and ViaVersion). Now I see this bug.

**Comment by Camotoy** [comment]
The player data file shows up as survival for both Java and Bedrock.

**Comment by code-monet** [comment]
That player file is for the Bedrock client only - this is from before I linked accounts. It's just not clear why the profile got switched to survival - originally I was playing from Bedrock as creative, as described above.

Anyway, for posterity, to deal with this, there are a couple of options:
1. Have an admin change the target player's gamemode
2. Stop server, delete the offending profile, restart (will reset the player, of course)

**Comment by hausemaster3734** [comment]
> That player file is for the Bedrock client only - this is from before I linked accounts. It's just not clear why the profile got switched to survival - originally I was playing from Bedrock as creative, as described above.
> 
> Anyway, for posterity, to deal with this, there are a couple of options:
> 
>     1. Have an admin change the target player's gamemode
> 
>     2. Stop server, delete the offending profile, restart (will reset the player, of course)

You can create a event listener that sets creative gamemode on join.

**Comment by onebeastchris** [comment]
Closing due to this likely being server behavior - if you are still experiencing this, send a new geyser dump.
