### ISSUE TITLE
Trading will only select the first tradable item

### ISSUE THREAD

**Issue by dbones** [GeyserMC/Geyser#2870]
### Describe the bug

with a Trading villager, which sells different items but for the same item, it will only allow the bedrock player to select the first option

(it also happens with the shopkeeper plug in, i will demo it with the plugin)

### To Reproduce

given, note that the first 2 items require Redstone

![image](https://user-images.githubusercontent.com/183849/156488236-d2df1c02-c162-4b46-a793-ad3aa9cb0e23.png)

try and purchase the second item on the list

![image](https://user-images.githubusercontent.com/183849/156488393-5691c811-215e-4a3c-8d32-b6ef7a61718f.png)

see that it does not select the correct trade (it does the iron in this case not copper)

![image](https://user-images.githubusercontent.com/183849/156488427-89e03971-0f2b-4039-be8e-aaf8fb63b119.png)

### Expected behaviour

in this case it should have traded copper

### Server Version and Plugins

![image](https://user-images.githubusercontent.com/183849/156488573-606ff3e7-8369-4b8d-accb-13a59584ac2f.png)

Plugin list

![image](https://user-images.githubusercontent.com/183849/156488639-d3ce6d8b-267a-42e6-801e-a93c1c1617f3.png)
![image](https://user-images.githubusercontent.com/183849/156488664-00e58d3f-e3ad-4c5b-8e27-cd9deeed5459.png)

### Geyser Dump

https://dump.geysermc.org/t7kKVLnN9uYBxwb7ZU2VvFFIo9U44MYF

### Geyser Version

2.0.1-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by Camotoy** [comment]
Please re-test with the latest Geyser version from https://ci.geysermc.org. This should already be fixed. Thanks!

**Comment by dbones** [comment]
will do 👍
