### ISSUE TITLE
FOV zooms in and player's movement changes

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#2871]
### Describe the bug

This issue only seems to happen when on a Bungeecord server, but it might be replicable on a plain Spigot server.

When crouching and placing blocks forwards (noticeably upwards) the camera's POV zooms in and stays randomly and you get the crouching slowness (as if you were using a spyglass). Interestingly, when you crouch, your POV goes back to normal.

### To Reproduce

1. Create a Bungeecord Geyser server
2. When connected, get a block of choice (I was in creative, but happens in Survival too)
3. Crouch while trying to create a staircase upwards
4. After a short while, your POV will decrease when you stand still
5. You'll then be walking around with a slowness effect, even when you're not crouching

### Expected behaviour

The player's FOV should be normal and shouldn't change after being crouched and placing a few blocks.

### Screenshots / Videos

https://user-images.githubusercontent.com/41856020/156901686-f210326d-6ec8-4752-80b8-e2b4686039c8.mp4

https://user-images.githubusercontent.com/41856020/156901687-aebe8780-ef67-4765-9c4a-d7c7462355af.mp4

### Server Version and Plugins

Spigot Server: This server is running CraftBukkit version git-Spigot-79a30d7-f4830a1 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

I'm only running Geyser Bungeecord, Floodgate and ViaVersion - all the latest versions.

### Geyser Dump

https://dump.geysermc.org/jyVl5fwazEFl6F9k1akJmKdtf2rnbTff

### Geyser Version

2.0.1-SNAPSHOT (git-master-9b8e137)

### Minecraft: Bedrock Edition Version

1.18.12

### Additional Context

This issue massively impacts minigame servers, especially those that have SkyWars and Bedwars, and requires players to bridge to other islands. This puts them at a disadvantage over Java players since they'll have a "slowness effect" when they're actually trying to sprint normally.

**Comment by pinkpig58** [comment]
Update: I've spent a good amount of time trying to replicate this on Geyser-Spigot but can't get it to happen, whereas I can get it to happen almost instantly when connected to a server under a BungeeCord proxy using Geyser-BungeeCord.

**Comment by Camotoy** [comment]
I can't immediately replicate this on BungeeCord with standalone and Spigot 1.12.2.

**Comment by pinkpig58** [comment]
Standalone? If you're referring to the standalone version of Geyser, I only used Geyser-BungeeCord and any servers I connected to under that proxy had the same issue.

I recorded it again to show the slowness effect as my original video didn't capture it very well

https://user-images.githubusercontent.com/41856020/157127541-b7fd0c38-4927-44d4-b618-f6c8a351e6d5.mp4

**Comment by Camotoy** [comment]
The slowness and FOV effect being tied together makes sense. If I had to guess, Geyser thinks you're in a 1.5-block-tall space, and applying our workaround for that.

**Comment by Camotoy** [comment]
Are there any additional plugins on the backend server? Maybe it's tied to being in a flat world??

**Comment by pinkpig58** [comment]
The Proxy is running: floodgate-bungee, Geyser-BungeeCord and ViaVersion-4.2.1
The Spigot server doesn't have any plugins running.

I deleted the flat world, changed the level-type to "DEFAULT", booted the Spigot server and tried again, getting the same result.

https://user-images.githubusercontent.com/41856020/157317037-12b31917-3149-48f5-80bd-ede3a0b91bec.mp4

**Comment by Camotoy** [comment]
I still cannot replicate this. I'm starting to wonder if it's a JDK specific or Windows Server specific issue???

**Comment by pinkpig58** [comment]
Tested on a Linux machine and got the same issue: https://dump.geysermc.org/UAD4j3GuERqKIuxqtnmImB4gKKmQznVG

**Comment by pinkpig58** [comment]
Thought I may as well try it using Java 16, but sadly it's the same problem
https://dump.geysermc.org/2rH2pFVWfxQiwKFXaOIw5Z8HZLThFkqk

**Comment by Camotoy** [comment]
Are you able to *not* replicate it? Maybe you have to staircase in a certain direction? Or some specific quirk in how you build versus me?

**Comment by pinkpig58** [comment]
Being quite surprised at how quickly I was able to replicate it and you weren't able to, I thought I would start from the beginning.

I created a completely new directory for my Proxy and Spigot server, redownloaded everything and booted the servers again.
To my complete shock, I **wasn't** able to replicate this and I can't understand how.

Despite downloading it from the official Jenkins page, is it possible to download a funky/dodgy/incomplete version? Has this been known to happen? If not, I have no idea what was happening, but redownloding everything seemed to fix it. I didn't change any configs, they were all the same as before.

**Comment by Camotoy** [comment]
Your original dump matches the MD5 hash of the one on Jenkins: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1033/artifact/bootstrap/bungeecord/target/Geyser-BungeeCord.jar/*fingerprint*/ but it is also possible that specific build was corrupted somewhere. I'll close this since your issue is resolved, and since no one else has reported such a bug I'm going to assume it was some fluke in our weird universe.
