### ISSUE TITLE
Bedrock Edition players can't jump on half-brick grass paths, and ladders can't be used,Problem with crafting workbench

### ISSUE THREAD

**Issue by NGT233** [GeyserMC/Geyser#2872]
### Describe the bug

will bounce back,Problem with crafting workbench

### To Reproduce

Craft at workbench, jump at half brick

### Expected behaviour

Hope you can fix the problem soon

### Server Version and Plugins

Independent geyser, paper server 1.18.1

### Geyser Version

1.2.0

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by Camotoy** [comment]
Please create *separate* issues for each of these, assuming there isn't already an issue created. 
Please provide a Geyser dump.
Please provide a video or replication steps; we can't do anything with this amount of information.

**Comment by NGT233** [comment]
ok, please wait a moment
