### ISSUE TITLE
Bedrock Edition players cannot jump on grass blocks

### ISSUE THREAD

**Issue by NGT233** [GeyserMC/Geyser#2873]
### Describe the bug

Just jump and bounce back

### To Reproduce

1 Enter the server 
2 Find the grass path
3jump on it
4It will bounce back

### Expected behaviour

Think if it won't bounce back

### Screenshots / Videos

https://user-images.githubusercontent.com/96066999/156905765-8d762a6e-e268-4e2a-a23f-63d1fdaabff1.mp4

### Server Version and Plugins

![OAEAW%`LF49 KD%(BH5F7](https://user-images.githubusercontent.com/96066999/156905926-ac9fad2d-152d-4927-a6e1-c9e539710511.png)

### Geyser Dump

http://faka2.mcngt.icu/dump.json

### Geyser Version

2.0.1SNAPSHOT(git-master-252348e)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by AnhNguyenlost13** [comment]
Seems like you're using custom server software.

**Comment by NGT233** [comment]
ok i try

**Comment by NGT233** [comment]
solved!
