### ISSUE TITLE
Bedrock Edition players use the workbench to synthesize at high frequency

### ISSUE THREAD

**Issue by NGT233** [GeyserMC/Geyser#2874]
### Describe the bug

Bedrock Edition players use the dog workbench to synthesize at high frequency,always flashing

### To Reproduce

打开工作台,合成物品,即可重现

### Expected behaviour

If it's not like this,

### Screenshots / Videos

http://thx.mcngt.icu/3DEC6E3D64BD9B27DFF657D60D765E46.mp4

The video is 14mb and can't be uploaded to github, I had to put it on my website
[http://thx.mcngt.icu/3DEC6E3D64BD9B27DFF657D60D765E46.mp4](url)

### Server Version and Plugins

The following is the plugin loaded on the paper server

ActionWords：动作语言，在玩家进行各个操作时周围出现一个瞬时浮空动画。（已删除）
ajLeaderboards：排行榜，用于统计菜单内的各个数值的排行展示，也可用于浮空字等排行榜显示。
ajParkour：无限跑酷，用于游戏菜单内的跑酷游戏。
*AlonsoTagsPro：称号。用于称号菜单和聊天内的称号展示，在计分板亦有显示。
AngelChest：天使之箱。
AnvilRepair：铁砧修复，用于机制菜单内的铁砧机制。
AureliumSkills：生存技能，用于技能菜单。
AutoComposter*：自动堆肥桶，用于合成菜单中的自动堆肥桶合成。
AutoPickup：自动拾取，用于功能菜单中的自动拾取和自动熔炼功能。如果你修改了这种功能插件，还需要修改等级菜单中对于各个会员等级的描述，在此不再累述。
AxePumpkin：斧子南瓜，用于机制菜单中的南瓜机制。（已删除）
BalancedVillagerTrades：平衡化的村民交易，如需删除，必须在第一次开服之前进行。一旦开服，就不能再进行删除。
BestTools：自动切换工具，用于功能菜单中的自动切换工具功能。
BetterKeepInventory：更好的死亡不掉落。
BetterLogStrip：新增树木系列装饰方块的合成。
BetterProfiles：右键打开玩家个人页面。
BetterRTP：随机传送，用于传送菜单中的各个生存世界的传送。
BetterTridents：更好的三叉戟，用于机制菜单中的三叉戟机制。
ChestProtect：锁箱子，用于保护菜单。
ChestSort：箱子整理，用于功能菜单中的箱子整理功能。
Citizens：NPC。
CMI*：基础。服务器很多方面都用了该插件，请勿随意删除和修改其中的配置文件。
CMIEInjector：前置插件。
CMILib：前置插件。
CopperOxidizer：铜加速氧化。用于机制菜单中的铜块机制。
CoralStay：在地皮世界珊瑚不会脱水死亡。
CustomCrafting*：自定义合成。用于合成菜单内部分物品的合成。
CustomWings：自定义翅膀，用于装饰菜单中的翅膀特效。
DeluxeMenu：菜单插件。
DoorReloaded：更好的门。用于机制菜单中对于门的机制。
eco：前置插件。
EcoItems^：自定义物品。用于护身符物品的合成，是它们合成材料。
ElevatorsFree：电梯。用于合成菜单中的电梯合成。
EliteMobs：精英怪物。
elytradrop：击杀末影龙获得鞘翅。
EpicBackPacks：史诗背包。用于合成菜单中各个背包的合成和功能菜单中的更真实的随身背包。
EpicFurnaces^：史诗熔炉。用于机制菜单中的熔炉升级机制。
EpicHoppers^：史诗漏斗。用于机制菜单中熔炉升级机制。
EZColors：聊天颜色。用于装饰菜单的聊天颜色和聊天中的聊天颜色。
floodgate-spigot
FluffyMachines：粘液科技附属。
GrindstoneDisabler：禁用砂轮。由于精英装备使用砂轮获得的经验值过多，因此使用了该插件禁止。
HiveChecker：蜂箱查看。
HolographicDisplays：浮空字。
HolographicExtension：浮空字附属。可以在浮空字内显示 Placeholders。
InfinityExpansion：粘液科技附属。
InvUnload：自动卸载。用于功能菜单中的自动卸载功能。
item-nbt-api-plugin：前置。
ItemsAdder*：自定义物品、方块。
Jobs：职业。用于职业菜单。
JukeBoxPlus*：唱片机菜单。
Lava_Annihilator：让玩家放置的岩浆没有伤害，用于机制菜单中的熔岩桶机制。
LibsDisguises：伪装。用于精英怪物中部分怪物皮肤的显示。
LightAPI：前置。
LoneLibs：前置。
LuckPerms：权限组。
MenuMate：进服给予菜单钟。
Multiverse-Core：多世界。
NoOneFishing：独家钓鱼。用于钓鱼菜单。
NoOneRods：独家钓鱼附属，新增了新的鱼竿。用于合成菜单中各个鱼竿的合成。
ntdLuckyBlock*：幸运方块。用于合成菜单中幸运方块合成。
OhTheDungeon：地牢生成。也是 地牢 世界生成的插件，我们隐藏了该功能，并且不建议您透露该功能。
OSZOAntiWDL：禁止 WDL Mod进服。
OverleveledEnchanter：突破等级限制的附魔，用于功能菜单中的高级铁砧、附魔书等级叠加功能。
PlaceholderAPI：变量前置。
PlayerPoints：点券。用于菜单内各个需要消耗点券的地方，在计分板亦有显示。
PlayerShopGUIPlus*：玩家商店GUI。用于功能菜单中的玩家商店功能和交易菜单中的玩家商店。
PlotSquared^：地皮。
ProtocolLib：前置。
RealisicReason*：季节。
Reforges^：重铸。用于拓展玩法菜单中的重铸玩法。
RePlanet*：自动补种。用于功能菜单中的自动补种功能。
ShopGUIPlus*：商店GUI。用于交易菜单内的系统商店。
ShopGUIPlus-SellGUI：商店GUI附属。提供一键回收功能，用于交易菜单中的一键回收。
shulkerrespawn：单独为潜影贝额外制作新的重生规则，用于机制菜单中的潜影贝机制。
SleepFixer：睡觉加快夜晚速度。
Slimefun：粘液科技
Tab：Tab和计分板。
Talismans^：护身符。用于合成菜单中各个护身符的合成。
TalismansGUI：护身符附属，提供GUI功能，用于显示护身符菜单。
Terra：泰拉世界生成器。（已删除）
TorchGone：火把熄灭机制。
TradePlus*：玩家交易。
trash：垃圾箱，用于垃圾箱菜单。
Tweakin：生存小机制。用于功能菜单、机制菜单内大量的功能、机制。
UlitimateCatacher：终极捕捉。用于合成菜单中的捕捉蛋合成。
UlimateTimber：重力树。用于功能菜单中的一键砍树功能和等级菜单中VIP特权。
Unstripper：给树返上皮。用于机制菜单中上皮机制。（已删除）
UpgradeableSpanwer*：可升级刷怪笼。用于刷怪笼升级。
Vault：经济前置。
VentureChat：聊天。
ViaVersion：跨版本，允许1.18客户端加入你的服务器。
VoidGen：虚空生成器。
WaterEx：水瓶灭火，用于机制菜单中的水瓶机制。
Wind：风灾机制。
wolfyultilities：前置。
worldedit：创世神。
worldguard：世界和区域保护。

### Geyser Dump

https://dump.geysermc.org/UYjQAMutiLTQDxD4vueQNVeMfgIudEFE

### Geyser Version

2.0.1-SNAPSHOT (git-master-252348e) (Java: 1.18 - 1.18.1, Bedrock: 1.17.40 - 1.18.10)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by NGT233** [comment]
https://github.com/GeyserMC/Geyser/actions/runs/1947425503
The problem persists after using this version

**Comment by RednedEpic** [comment]
Video link is dead. Please open a new issue with this & ideally upload the video to YouTube.
