### ISSUE TITLE
Controller users crashing on lower levels of haste

### ISSUE THREAD

**Issue by ryankayz7** [GeyserMC/Geyser#2875]
### Describe the bug

My Prison server runs enchants through advancedenchantments. The haste in this plugin allows you to increase mining speed with fast digging based off bukkit enchantments as stated here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html . This gives the player increased potion effect of haste. I did a little bit of testing and managed to crash a player as low has having the effect of haste 7 or fastdigging 6 in this case. The error message that controller users got when this occured was something about "sending too many packets". Again this was only reproducible with controller users on PS4, Switch and when having a controller hooked up to PE. I was also able to reproduce this issue on other servers by giving players higher levels of the haste effect also showing it is not based around other plugins. I believe this could be to do with #1621 and how bedrock players are mining faster than Java players. Specifically using a controller makes this easier than the other alternatives. I could be wrong with that though.

### To Reproduce

Use a high level of haste using a bedrock account and playing with controller.

### Expected behaviour

I expected the user to be able to mine as normal without crashing with the haste effect.

### Screenshots / Videos

https://gyazo.com/41870be02767e7d64af81b2454bb2857

### Geyser Version

Geyser-BungeeCord.jar (Git Build #1041)

### Minecraft: Bedrock Edition Version

1.18.2 or 1.18.12

**Comment by Konicai** [comment]
What plugin or server software is actually sending that message? Can you provide a Geyser dump by running `/geyser dump`

**Comment by ryankayz7** [comment]
Sorry for the slow reply. 

Geyser dump: https://dump.geysermc.org/wLA9mpkDOKC1SX2cWeDYgVrDc9MiUyGX

Here is the crash message: https://gyazo.com/e8abe8acbdf91eea65f9bd7a73ca7eb4

I tested the threshold of where it crashed the player and it was at haste 6. This might not have previously been reported as this is higher than players get in vanilla minecraft?

**Comment by ryankayz7** [comment]
Also managed to get players to crash on windows 10 but not PE. I again assume due to how PE mines?

**Comment by Camotoy** [comment]
This is *probably* fixed by 00df4c26ba13fc8ddf0c92500b414061b592dae4.
