### ISSUE TITLE
Allow us to register server as xbox account so we can connect through friends list.

### ISSUE THREAD

**Issue by Shadowblitz16** [GeyserMC/Geyser#2878]
### What feature do you want to see added?

Please allow us to register a geyser mc server as a xbox account so we can connect through friends list.
It would really be nice if we could also use it in local network mode

### Are there any alternatives?

IP hack on consoles.

**Comment by rtm516** [comment]
> IP hack on consoles
What is that?

And you can use local tools like those listed on https://wiki.geysermc.org/geyser/using-geyser-with-consoles/ to allow it to show as a LAN game

**Comment by Shadowblitz16** [comment]
@rtm516 the ip hack is the thing where you change your dns settings so when you login to a server it gives you a server ui instead.

Idk if you would consider it a hack, but its very indirect on how you do it. for users that aren't tech savy, it might be confusing.
For example, I can understand it, but my sister might not. 

I am just asking that we can link the geyser mc server with our bedrock account so that other users can join on console versions of bedrock via friends list.

**Comment by rtm516** [comment]
> the ip hack is the thing where you change your dns settings so when you login to a server it gives you a server ui instead.

Ah so like GeyserConnect/BedrockConnect DNS settings change

This is something Ive wanted to do but not worked out how yet

**Comment by Shadowblitz16** [comment]
ya idk if its even possible to connect a java server to a bedrock account.
But if it were it would be a much better way to connect
