### ISSUE TITLE
Sitting cat has bad yaw (?!)

### ISSUE THREAD

**Issue by JuniorJPDJ** [GeyserMC/Geyser#288]
Cat sitting on bed has bad yaw? >___< TF?

**To Reproduce**
I'll try in few seconds, just reporting.
I was reconnecting to the same account and connected from another one to check if it happens and it does, but I haven't tried on other bed.

EDIT: Just spawn cat, tame it and watch it to sit on bed/chest.

**Screenshots / Videos**
Case 1:
![image](https://user-images.githubusercontent.com/7334549/78726971-a9f63780-7933-11ea-8ca3-e771f30a7480.png)
![image](https://user-images.githubusercontent.com/7334549/78726988-b4183600-7933-11ea-9e4b-c009afe8d0fa.png)
Case 2:
![image](https://user-images.githubusercontent.com/7334549/78729817-5687e780-793b-11ea-9dc0-b0769c05a6aa.png)

**Server Version**
Paper 1.15.2 build 144

**Geyser Version**
9 build of inventory branch from CI

**Minecraft: Bedrock Edition Version**
1.14.30 win10 edition

**Comment by DoctorMacc** [comment]
I've seen this orientation thing extend beyond cats.

**Comment by DoctorMacc** [comment]
Superseded with #299.
