### ISSUE TITLE
Make geyser return a player ModelData (Android phone model), not returning "Geyser"

### ISSUE THREAD

**Issue by TypicalShavonne** [GeyserMC/Geyser#2880]
### What feature do you want to see added?

Make geyser return a player ModelData (Android phone model), not returning "Geyser"
E.g: A player is playing on a Android device(A Samsung S22 Ultra)
Expected: The plugin will return their real device model which is ["SM-S908B/DS"](https://www.gsmarena.com/samsung_galaxy_s22_ultra_5g-11251.php) and not "Geyser"

### Are there any alternatives?

No

**Comment by TypicalShavonne** [comment]
https://github.com/GeyserMC/Geyser/blob/7f5d81772b035a6f9b9e3e77fd5d93591f9c97e4/core/src/main/java/org/geysermc/geyser/translator/protocol/java/JavaLoginTranslator.java#L101

**Comment by TypicalShavonne** [comment]
https://github.com/GeyserMC/Geyser/blob/7f5d81772b035a6f9b9e3e77fd5d93591f9c97e4/core/src/main/java/org/geysermc/geyser/util/PluginMessageUtils.java#L57

**Comment by RednedEpic** [comment]
Hey, thanks for the feature suggestion but for the sake of consistency, this is not something we are interested in implementing. We'd rather all players consistently returning "Geyser" through the client brand so it's very clear they are joining with Geyser. However, using the Floodgate API, there is a way to retrieve the device OS of the user and we highly recommend you use that instead. Regardless, thanks for the suggestion!

**Comment by TypicalShavonne** [comment]
Can you make it "Geyser <device model>" instead ? There's a cheat client on Android called "ToolBox" and it report its device model in lowercase instead of uppercase like vanilla client, so we can use that to kick cheat client users
