### ISSUE TITLE
Geyser incompatable with DiscordSRV v1.25.0

### ISSUE THREAD

**Issue by RUvlad1** [GeyserMC/Geyser#2881]
### Describe the bug

The server crashes after I try to open it, it stops at `[Geyser-Spigot] Started Geyser on 0.0.0.0:22688` for a minute or so and then crashes the server `[Aternos System/ERROR]: Server was stopped because it took too long to start. Try reducing the load to avoid this in the future.`
I didn't change any settings in geyser and just left it by default
The problem is gone if i use spigot, but I don't want to use it because it slows down the server a lot
The server starts just fine if I remove geyser

### To Reproduce

1. Make a 1.18.2 server with papermc on Aternos
2. Install the Geyser plugin
3. Start the server

### Expected behaviour

The server should start normally

### Server Version and Plugins

The server version is 1.18.2 with papermc on Aternos
Other plugins that are installed:
AuthMe
DiscordSRV
EasyInventory
Floodgate
NotTooExpensive
SkinsRestorer

### Geyser Version

1050

**Comment by MR-GAMER7644** [comment]
Yeah same happens to me but if I remove geyser it works fine or if I remove discordSRV it works fine but if both of them are in same server it's not working.

**Comment by Dibya07** [comment]
Same here
 Server Version & Plugins:-
 Java 1.18.2
 DiscordSRV
 SimpleTPA
 Floodgate
 ViaVersion
 ViaBackwards
 SetHome
 Better Teams
 MultiplayerSleep
 
 Geyser Version- 1050

**Comment by MR-GAMER7644** [comment]
> Same here Server Version & Plugins:- Java 1.18.2 DiscordSRV SimpleTPA Floodgate ViaVersion ViaBackwards SetHome Better Teams MultiplayerSleep
> 
> Geyser Version- 1050

Do you have geyser ?

**Comment by Dibya07** [comment]
> > Same here Server Version & Plugins:- Java 1.18.2 DiscordSRV SimpleTPA Floodgate ViaVersion ViaBackwards SetHome Better Teams MultiplayerSleep
> > Geyser Version- 1050
> 
> Do you have geyser ?

Yes I forgot to add now added

**Comment by rtm516** [comment]
So after some debugging with a user, it looks like a change to DiscordSRV between v1.24.0and v1.25.0 causes an issue to Geyser.
https://github.com/DiscordSRV/DiscordSRV/compare/v1.24.0...v1.25.0
So for now anyone having this issue should downgrade to [DiscordSRV v1.24.0](https://github.com/DiscordSRV/DiscordSRV/releases/tag/v1.24.0)

**Comment by Dibya07** [comment]
> ### Describe the bug
> The server crashes after I try to open it, it stops at `[Geyser-Spigot] Started Geyser on 0.0.0.0:22688` for a minute or so and then crashes the server `[Aternos System/ERROR]: Server was stopped because it took too long to start. Try reducing the load to avoid this in the future.` I didn't change any settings in geyser and just left it by default The problem is gone if i use spigot, but I don't want to use it because it slows down the server a lot The server starts just fine if I remove geyser
> 
> ### To Reproduce
> 1. Make a 1.18.2 server with papermc on Aternos
> 2. Install the Geyser plugin
> 3. Start the server
> 
> ### Expected behaviour
> The server should start normally
> 
> ### Screenshots / Videos
> _No response_
> 
> ### Server Version and Plugins
> The server version is 1.18.2 with papermc on Aternos Other plugins that are installed: AuthMe DiscordSRV EasyInventory Floodgate NotTooExpensive SkinsRestorer
> 
> ### Geyser Dump
> _No response_
> 
> ### Geyser Version
> 1050
> 
> ### Minecraft: Bedrock Edition Version
> _No response_
> 
> ### Additional Context
> _No response_

Well Degrading The DiscordSRV version fixed it

**Comment by Camotoy** [comment]
Looks like the DiscordSRV team has resolved this in their snapshot builds: https://github.com/DiscordSRV/DiscordSRV/issues/1376

**Comment by kudit** [comment]
Same here.  Discord1.24 works but 1.25 hangs and won't start.

**Comment by 12emin34** [comment]
seems like an Aternos specific issue, DiscordSRV 1.25.0 works fine with Geyser on my server

**Comment by Camotoy** [comment]
It's not Aternos specific; I was able to replicate it on my end. It's not consistent though.

**Comment by MR-GAMER7644** [comment]
> seems like an Aternos specific issue, DiscordSRV 1.25.0 works fine with Geyser on my server

Then why it's not working for me ? I'm not a aternos user

**Comment by Camotoy** [comment]
Looks like DiscordSRV has fully released an update on their end to address this.

**Comment by MR-GAMER7644** [comment]
> Looks like DiscordSRV has fully released an update on their end to address this.

So can I use geyser with the latest discordsrv now coz I have degraded my discordsrv to 1.24.0 that why I'm asking can I update ?

**Comment by RUvlad1** [comment]
> So can I use geyser with the latest discordsrv now coz I have degraded my discordsrv to 1.24.0 that why I'm asking can I update ?

Yes, I just updated DiscordSRV and reinstalled Geyser and the server starts normally now
