### ISSUE TITLE
i cant join in 1.18.1 java geyser server using bedrock 1.17.41 or 1.18.10 

### ISSUE THREAD

**Issue by revanth-minecraft** [GeyserMC/Geyser#2882]
### Describe the bug

i tried to join in my new java 1.18.1 aternos server with geyser, i open minecraft bedrock 1.18.10, i tried to join in server but it showing outdated client but when i am installing geyser in bracket it shows(1.17.41,1.18.0,1.18.10), i am using 1.18.10 olny but it is not working.then i changed the version to 1.17.41 in bedrock and server version to 1.17.1. but also it is not working 

can you say why 

### To Reproduce

*

### Expected behaviour

*

### Screenshots / Videos

*

### Server Version and Plugins

versions of server:
1.18.1 and 1.17.1
versions of bedrock:
1.18.10 and 1.17.41
plugins:
geyser
floodgate

### Geyser Dump

*

### Geyser Version

latest, it is only one in aternos plugins

### Minecraft: Bedrock Edition Version

1.18.10 and 1.17.41

### Additional Context

please slove this as fast as you can
plzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
i am begging you

**Comment by rtm516** [comment]
Install ViaVersion

**Comment by revanth-minecraft** [comment]
Tq rtm I will try that tomorrow

**Comment by revanth-minecraft** [comment]
it is not working
