### ISSUE TITLE
Geyser Legacy Download Link

### ISSUE THREAD

**Issue by 1470429149** [GeyserMC/Geyser#2884]
### What feature do you want to see added?

I'm using the 1.13 paper server, but I can't find a Geyser that supports it, and my server only works with java12.

### Are there any alternatives?

I tried to use the latest version of Geyser on the 1.13.2 paper server, but Geyser doesn't work.

**Comment by TypicalShavonne** [comment]
you can run a proxy that have geyser on it then connect to the server, the proxy can be velocity/bungeecord

**Comment by AnhNguyenlost13** [comment]
> Older builds have KNOWN SECURITY ISSUES.
- Camotoy

**Comment by RednedEpic** [comment]
Use the latest build with ViaVersion - we don’t support older Java servers natively within Geyser.
