### ISSUE TITLE
Make geyser return a player ModelData (Android phone model), not returning "Geyser"

### ISSUE THREAD

**Issue by TypicalShavonne** [GeyserMC/Geyser#2885]
### What feature do you want to see added?

Make geyser return a player ModelData (Android phone model), not returning "Geyser"
E.g: A player is playing on a Android device(A Samsung S22 Ultra)
Expected: The plugin will return the brand as Geyser [SM-S908B/DS](https://www.gsmarena.com/samsung_galaxy_s22_ultra_5g-11251.php) and not "Geyser"

There's a cheat client on Android called "ToolBox" and it report its device model in lowercase instead of uppercase like vanilla client, so we can use that to kick cheat client users

### Are there any alternatives?

nop

**Comment by RednedEpic** [comment]
Please do not open a new feature suggestion for something we have already denied. If you want to discuss. See comment on #2880.
