### ISSUE TITLE
Suggestion for Standalone Geyser

### ISSUE THREAD

**Issue by DmdPlayz** [GeyserMC/Geyser#2886]
### What feature do you want to see added?

A way to save your login info and remain authenticated (maybe with a check box) to avoid having to login repeatedly. To avoid any possible glitches/account stealing, have the auth code expire after 24 hours.

### Are there any alternatives?

Not really; none

**Comment by Camotoy** [comment]
Discussed on Discord; there is a manual option for saving user logins in the config, but besides that we aren't interested in arbitrarily saving logins. Saving logins behind an individual passcode is *possible*, but a very very very low priority as we don't want to play the security game.
