### ISSUE TITLE
Structure Block doesn't work in Crafting Table

### ISSUE THREAD

**Issue by Plattio** [GeyserMC/Geyser#2890]
### Describe the bug

Hi, this custom recipe doesn't work in Bedrock, but in JAVA.
It doesn't work because of the structure block, already tested it without it and then it worked fine.
I tested it with a downloaded plugin and also with a plugin developed by my developer and there it doesn't work also.
Would be cool if this can be fixed.

Edit: It doesn't work with structure void also

![unknown (1)](https://user-images.githubusercontent.com/65920067/158666295-1cfb9707-3010-4760-840d-59ace4e650df.png)

### To Reproduce

1. Install CustomCrafting Plugin https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-16-1-18-free.55883/
2. Create Crafting Recipe with a structure block (/customcrafting)
3. Try to craft with Java and then with Bedrock User

### Expected behaviour

I get the crafting result

### Server Version and Plugins

![image](https://user-images.githubusercontent.com/65920067/158666776-60890990-2858-44ce-9ec2-f2c29c776faa.png)

### Geyser Version

This server is running Geyser version 2.0.2-SNAPSHOT (git-master-9c0b9f1) (Java: 1.18.2, Bedrock: 1.17.40 - 1.18.10/1.18.12)

**Comment by AnhNguyenlost13** [comment]
Please provide the exact Bedrock and Geyser versions.

**Comment by Plattio** [comment]
done

**Comment by Plattio** [comment]
Same with Structure Voids
