### ISSUE TITLE
If the coordinate value becomes large, an error occurs in the movement of the BE account

### ISSUE THREAD

**Issue by xs7884** [GeyserMC/Geyser#2893]
### Describe the bug

If the coordinate value becomes large, an error occurs in the movement of the BE account.
In coordinates like '10000,65,10000', the movement of the BE account is normal, but in coordinates like '6000000,65,600000', problems such as moving in one direction are cut off.

### To Reproduce

In coordinates with large numbers, the movement of the BE account is very choppy, and it can only move in one direction.

### Expected behaviour

In coordinates with large numbers, the movement of the BE account is very choppy, and it can only move in one direction.

### Geyser Version

#1055 2022. 3. 18.

### Minecraft: Bedrock Edition Version

newest version

**Comment by Chew** [comment]
> This is unfortunately a Bedrock bug - large coordinates like the area you're located in are not supported well by Bedrock. [minecraft.fandom.com/wiki/Bedrock_Edition_Far_Lands](https://minecraft.fandom.com/wiki/Bedrock_Edition_Far_Lands)
Thank you for reporting anyway!
