### ISSUE TITLE
Support command descriptions

### ISSUE THREAD

**Issue by DJelly4K** [GeyserMC/Geyser#2895]
### What feature do you want to see added?

Support command descriptions
Currently in Bedrock Edition, all command descriptions are blank, I hope to support custom command descriptions
(yeah i know there is a branch called "customcommanddescriptions" that making on it, but it doesn't seem to be active anymore)

### Are there any alternatives?

-

**Comment by LegacyGamerHD** [comment]
Well you need spigot version for it other version don't have this
