### ISSUE TITLE
Villagers Won't Pick Up Food And Breed

### ISSUE THREAD

**Issue by 2009hearth** [GeyserMC/Geyser#2902]
### Describe the bug

Villagers Don't Breed

### To Reproduce

Place 3 beds
Get 2 villagers near the beds
Throw bread, beetroot, carrots, or potatoes at them
They won't even pick the foods up.

### Expected behaviour

When you have beds and throw food at villagers, they are supposed to breed, but they don't even pick the food up.

### Server Version and Plugins

ALL VERSIONS.

### Geyser Dump

Umm.....I have no Idea. Don't own the server and don't have access to those commands.

### Geyser Version

1.18 and above

### Minecraft: Bedrock Edition Version

1.16.1-current

### Additional Context

They don't breed and it is inconvenient for survival mode.

**Comment by Camotoy** [comment]
> Don't own the server and don't have access to those commands.

Geyser/Floodgate does not modify this server; this is very very unlikely to be us. You can try replicating without Geyser and Floodgate installed and I'm sure you will get the same results. Thanks anyway for reporting.
