### ISSUE TITLE
Nether Fortress Mobs Don't Spawn

### ISSUE THREAD

**Issue by 2009hearth** [GeyserMC/Geyser#2903]
### Describe the bug

Nether fortress mobs like wither skellies don't spawn as they are supposed to. Blazes rarely spawn and only usually spawn at the blaze spawners. You usually get 1 nether fortress mob spawn every 5 hours.

### To Reproduce

Go to the nether
Find a fortress
Wait....And see that nothing spawns.

### Expected behaviour

I play on a hard mode server, so there is supposed to be like 10 wither skeletons at the fortress at all times if they spawn right.

### Server Version and Plugins

1.18.12 at the moment. Don't have access to server commands.

### Geyser Dump

No access to server commands

### Geyser Version

1.18.12

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by Camotoy** [comment]
Geyser/Floodgate does not modify this server; this is very very unlikely to be us. You can try replicating without Geyser and Floodgate installed and I'm sure you will get the same results. Thanks anyway for reporting.
