### ISSUE TITLE
Geyser feature/extensions branch starts abnormally on Velocity

### ISSUE THREAD

**Issue by DJelly4K** [GeyserMC/Geyser#2905]
### Describe the bug

(I don't know if other geyser versions have startup exceptions)
I downloaded the latest branch build, but an exception is displayed after startup, even if you add velocity-plugin.json by yourself, NoDefClassError will appear

### To Reproduce

1. download the lastest branch build
2. put it on proxy
3. start abnormally

### Expected behaviour

Start normally

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/68630033/160243113-25669ada-0cab-4b2e-9f3d-6566354063f3.png)
after add velocity-plugin.json by yourself:
![image](https://user-images.githubusercontent.com/68630033/160243229-657970ee-9672-4cf1-8793-97555747e1d4.png)

### Server Version and Plugins

None.

### Geyser Dump

None.

### Geyser Version

None.

### Minecraft: Bedrock Edition Version

None.

### Additional Context

I used google translate because I don't understand English

**Comment by srlss123** [comment]
If you use fork , please report fork issues
如果你使用fork分支 请报告给fork的issues

**Comment by srlss123** [comment]
I try is bug it's like you
我试了和你一摸一样

**Comment by ImDaBigBoss** [comment]
[https://github.com/GeyserMC/Geyser/blob/1ebc3fd8f66bf737fa99da06e08bddc596cf26c9/bootstrap/velocity/build.gradle.kts#L8](https://github.com/GeyserMC/Geyser/blob/1ebc3fd8f66bf737fa99da06e08bddc596cf26c9/bootstrap/velocity/build.gradle.kts#L8) is supposed to be `platformRelocate("it.unimi.dsi.fastutil")`.

**Comment by DJelly4K** [comment]
> If you use fork , please report fork issues 如果你使用fork分支 请报告给fork的issues

first, the original fork already has this problem, i use the original fork to push this issue, so this place right, you know it?

**Comment by DJelly4K** [comment]
> https://github.com/GeyserMC/Geyser/blob/1ebc3fd8f66bf737fa99da06e08bddc596cf26c9/bootstrap/velocity/build.gradle.kts#L8
> 
> is supposed to be `platformRelocate("it.unimi.dsi.fastutil")`.

![image](https://user-images.githubusercontent.com/68630033/164172305-94fcfba6-cc85-43e0-9f0d-e7f473e30e14.png)
still doesn't work

**Comment by ImDaBigBoss** [comment]
Well this needs implementing [https://kotlinlang.org/docs/kapt.html](https://kotlinlang.org/docs/kapt.html)

**Comment by Konicai** [comment]
Closed in https://github.com/GeyserMC/Geyser/pull/2940
