### ISSUE TITLE
Bedrock lag issue

### ISSUE THREAD

**Issue by AekkyKJMs** [GeyserMC/Geyser#2906]
### Describe the bug

I host minecraft server and i saw some player on Bedrock edition is laggy but on Java just fine. I don't know what to do

### To Reproduce

-

### Expected behaviour

I want Bedrock Edition player play on normally like Java Edition

### Server Version and Plugins

3467-Spigot-ffceeae-e6cc7c7
1.18.2-R0.1-SNAPSHOT

### Geyser Dump

https://dump.geysermc.org/9I4wOwjQLRkcRZYoovrxK4fZelYJzMuM

### Geyser Version

2.0.2-SNAPSHOT (git-master-0067ba5)

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by Camotoy** [comment]
Are you able to try on another computer/Linux?

**Comment by AekkyKJMs** [comment]
> Are you able to try on another computer/Linux?

I've tried and Geysermc not working. It's say "Unable to connect to world"

**Comment by creativegamer03** [comment]
Hmmm try using Paper. Spigot's laggy compared to Paper. Affects Geyser too.
