### ISSUE TITLE
cant place and speed bugging 

### ISSUE THREAD

**Issue by Prex9090** [GeyserMC/Geyser#2907]
### Describe the bug

hello, im from bedrock user and this bugs really exist. i have own server paid hosting and that is pterodactyl site. also my players are bedrock cracked user and thats goona be effective on bugs.  i have completed and no wrong in setup of geyser and floodgate. i hope my complain reach ur team. thanks. cant place the blocks in farm and speed bug

### To Reproduce

cant place and speed bugging and water bucket lava

### Expected behaviour

hello, im from bedrock user and this bugs really exist. i have own server paid hosting and that is pterodactyl site. also my players are bedrock cracked user and thats goona be effective on bugs.  i have completed and no wrong in setup of geyser and floodgate. i hope my complain reach ur team. thanks.

### Screenshots / Videos

https://user-images.githubusercontent.com/102614294/160663846-a07e6c20-cda0-4473-8196-7c5324896aa7.mp4

https://user-images.githubusercontent.com/102614294/160663849-d9f881ba-7109-4e3d-997b-248fa857635c.mp4

thats the video 

### Server Version and Plugins

pterodactyl site console ang geyser, floodgates

### Geyser Dump

https://dump.geysermc.org/Jr4laPaLp8Hmdf9ELIh0228ucpuYUfr

### Geyser Version

lates version of geyser 

### Minecraft: Bedrock Edition Version

mcbe 

### Additional Context

thanks admin and deevs

**Comment by Heath123** [comment]
Please fill in the “Geyser Dump” part, you can get a dump link by running `geyser dump` in the server console

**Comment by Prex9090** [comment]
> Please fill in the “Geyser Dump” part, you can get a dump link by running `geyser dump` in the server console

done

**Comment by Camotoy** [comment]
The link appears to be invalid.

**Comment by Konicai** [comment]
You haven't even uploaded a new Geyser dump link to replace the old invalid one? And please don't bump issues for no reason

**Comment by Jens-Co** [comment]
I'll close this issue for now, if you still got this issue please update this one with the asked information. I'll close for joz

Thanks
