### ISSUE TITLE
Nether roof building didn't work

### ISSUE THREAD

**Issue by jeffry1829** [GeyserMC/Geyser#2909]
### Describe the bug

Even if I used above-bedrock-nether-building: true
Players still can't build upon nether roof.

### To Reproduce

1. Use Geyser and Floodgate only on bungeecord
2. above-bedrock-nether-building: true
3. Can't build

### Expected behaviour

Should be able to build upon nether roof.

### Server Version and Plugins

backend server: Paper version git-Paper-203 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5bb4549)
bungeecord: Waterfall version git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475 by md_5
plugins:
![image](https://user-images.githubusercontent.com/6897769/160875471-fe8f27cc-691d-4158-a811-537a8dc31ad4.png)

### Geyser Dump

https://discord.com/channels/613163671870242838/613168464634576897/958750267183091782

### Geyser Version

2.0.2-SNAPSHOT (git-master-0067ba5)

**Comment by Jens-Co** [comment]
As said in Discord, this is not a Geyser related issue since Java players also cannot build on nether roof. 

I'll close this issue; provided steps for fix in discord.
