### ISSUE TITLE
Bedrock players teleporting back to log in location after moving 

### ISSUE THREAD

**Issue by seanimusprime** [GeyserMC/Geyser#2910]
### Describe the bug

When joining the server on my fiance's Nintendo Switch and running/climbing/jumping a few blocks the player will be teleported back to the spot they logged in at. When checking the console log there's hundred (maybe thousands) of lines with the same error repeatedly.:

> [31Mar2022 15:16:50.999] [Geyser player thread-3-1/WARN] [/]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)

I have increased both **moved-wrongly-threshold** and **moved-too-quickly-multiplier** in the spigot settings but it did nothing.

### To Reproduce

1. Join server from Bedrock edition.
2. Run a few blocks.
3. Wait to get teleported back.

### Expected behaviour

To not get teleported back and to be able to play the game like normal.

### Server Version and Plugins

Mohist version 1.18.2

### Geyser Dump

https://dump.geysermc.org/pQepcOQXXvwVKMs0g8kHf5Fg090ucAAd

### Geyser Version

2.0.2-SNAPSHOT (git-master-2a05dd5)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by Camotoy** [comment]
> Mohist version 1.18.2
Mohist may not be a supported platform on our end. However, please attach a full server log. You can use https://mclo.gs/ to remove IP addresses from your log.

**Comment by seanimusprime** [comment]
Here is the most recent log: https://mclo.gs/g4ArXqr

**Comment by Camotoy** [comment]
`java.lang.NoSuchMethodError: 'net.minecraft.server.level.WorldServer org.bukkit.craftbukkit.v1_18_R2.CraftWorld.getHandle()`
This can be reverted by adding the JVM property `-DGeyser.UseDirectAdapters=false` before `-jar`.
