### ISSUE TITLE
setFlying(true) for Bedrock player doesn't set them to fly

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#2914]
### Describe the bug

On Java, when getPlayer().setAllowFlight(true) and getPlayer().setFlying(true) are run, it allows the player to fly and sets them in fly mode, but the Bedrock player doesn't remain in the air despite "setFlying" being true.

### To Reproduce

1. Create a method to setAllowFlight and setFlying to be true and teleport them up at the same time
2. See that the Java player stays in the air because they're in fly mode, but the Bedrock player doesn't

Here's what I used:

```
@EventHandler
public void onPlace(BlockPlaceEvent e) {
     Player p = e.getPlayer();

     p.teleport(p.getLocation().add(0, 10, 0));
     p.setAllowFlight(true);
     p.setFlying(true);
}
```

### Expected behaviour

The Bedrock player should be put into fly mode.

### Screenshots / Videos

https://user-images.githubusercontent.com/41856020/161401607-920816e8-1c54-4dff-8093-e274660f5a40.mp4

### Server Version and Plugins

CraftBukkit version git-Spigot-79a30d7-f4830a1 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Plugins: Geyser-Spigot, floodgate-spigot, ViaVersion-4.2.2-SNAPSHOT and a plugin that only contains the event I posted above.

### Geyser Dump

https://dump.geysermc.org/s2kHgowHhXgD0K3arvPUXrTmrFY70UjA

### Geyser Version

2.0.2-SNAPSHOT (git-master-fb26e26)

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by TheMonBonGH** [comment]
Is this with only Spigot 1.12.2, or does this occur in a 1.18.2 server?

**Comment by pinkpig58** [comment]
This also occurs on a 1.18.2 server.
**CraftBukkit version 3473-Spigot-ffceeae-2542945 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)**

**Comment by pinkpig58** [comment]
**Update:** I was playing around with this and decided to try setting a tick delay.

I set p.setFlying(true); to run 5 ticks after teleporting and setAllowFlight and it works as it does on Java.
Could it be that Geyser/Bedrock is setting/sending the fly attribute/packet too quickly?

**Comment by onebeastchris** [comment]
Is this still an issue on the latest version of Geyser?

**Comment by pinkpig58** [comment]
Does seem to be fixed now and can't reproduce it from the tests I've just done.
