### ISSUE TITLE
Shield does not protect you from a flame bow

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#2915]
### Describe the bug

On Bedrock, players holding a shield can still be set on fire and take damage when being shot by a Flame I bow.

### To Reproduce

1. Get a player to hold a shield in their off-hand (crouching to activate)
2. Get another player to shoot an arrow from a Flame bow

### Expected behaviour

The arrow should be blocked by the shield and shouldn't set the player on fire.

### Screenshots / Videos

https://user-images.githubusercontent.com/41856020/161401898-c9014a4e-f718-4c13-8cf0-2ea2e540f006.mp4

### Server Version and Plugins

CraftBukkit version git-Spigot-79a30d7-f4830a1 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Plugins: Geyser-Spigot, floodgate-spigot and ViaVersion-4.2.2-SNAPSHOT

### Geyser Dump

https://dump.geysermc.org/aH4mXEpwtpCYDLFV6vpotXutmIg9BpLN

### Geyser Version

2.0.2-SNAPSHOT (git-master-fb26e26)

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by Camotoy** [comment]
This definitely doesn't sound like something we control. Please try replicating it with a Java 1.18.2 player.

**Comment by pinkpig58** [comment]
Oh wow, yeah, I didn't know that was actually a feature. Never mind then, apologies!
