### ISSUE TITLE
Ignoring UseItemOnPacket from User Warning

### ISSUE THREAD

**Issue by TheRealArchie** [GeyserMC/Geyser#2917]
### Describe the bug

`[02:19:49 WARN]: Ignoring UseItemOnPacket from .RevoIxtion: Location (-67.31246185302734, 64.0, 360.2207336425781) too far away from hit block BlockPosition{x=-68, y=64, z=361}.`
Warning that occasionally cancels the placement of blocks with GeyserMC users which is breaking things. Any help? I've heard of other people having the same issue.

### To Reproduce

2. Be on a bedrock account
3. Be in creative
4. Build quickly while moving

### Expected behaviour

No warning in console, uninterrupted building.

### Server Version and Plugins

This server is running Paper version git-Paper-263 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 7b46444)

Plugins (16): BannerMaker, CommandHook, CoreProtect, DiscordSRV, dynmap, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, ImageOnMap, LuckPerms, PlaceholderAPI, QualityArmory, Simple-Drugs, Vault, WorldEdit

### Geyser Dump

https://dump.geysermc.org/QvxcSrxuyrcmlCXnwN7a3D5KsEd9VOrF

### Geyser Version

2.0.2-SNAPSHOT (git-master-732fd90)

### Additional Context

Our host is implementing Geyser over bungee. It is not done on our server directly. We do not have direct access to geyser.

**Comment by KygekDev** [comment]
Why close this issue without explanation?

**Comment by rtm516** [comment]
> Why close this issue without explanation?

It was closed due to a commit fixing the issue. (which is linked but ill link it again)
https://github.com/GeyserMC/Geyser/commit/1d3eebc678be9a17fb71141bdacd933c13477f0c

**Comment by KygekDev** [comment]
> > Why close this issue without explanation?
> 
> It was closed due to a commit fixing the issue. (which is linked but ill link it again) [1d3eebc](https://github.com/GeyserMC/Geyser/commit/1d3eebc678be9a17fb71141bdacd933c13477f0c)

Thank you for the fast response.
