### ISSUE TITLE
geysur stops server from starting

### ISSUE THREAD

**Issue by redstone47** [GeyserMC/Geyser#2918]
### Describe the bug

server wont finish starting when geyser spigot is loaded

### To Reproduce

i don't know it just started happening one day

### Expected behaviour

i expected it to start or just disable the plugin 

### Screenshots / Videos

[latest.log](https://github.com/GeyserMC/Geyser/files/8413137/latest.log)

### Server Version and Plugins

paper spigot 277, spigot dash, TAB, command pannels, deadchest, floodgate,image maps, minecraft server remote

### Geyser Version

geysur spigot 1070

**Comment by Camotoy** [comment]
Update DiscordSRV; this was a bug on their end that they addressed.
