### ISSUE TITLE
Regarding the problem that the bedrock version of the player may move slowly 

### ISSUE THREAD

**Issue by wlm1455925277** [GeyserMC/Geyser#2919]
### Describe the bug

Java players don't do this, only geyser players do this. Entering the server will go very slowly like adding slow effect. Mine is bc server 

### To Reproduce

It seems to happen after a while, then go to the back and re-enter and restart and it won't work 

### Expected behaviour

Solve this problem, thank you very much 

### Screenshots / Videos

https://user-images.githubusercontent.com/87473483/161845319-8f54d78f-30bf-450c-8430-de47677abc21.mp4

### Server Version and Plugins

1.18.2
![Screenshot_2022-04-06-04-45-36-251_com microsoft rdc androidx](https://user-images.githubusercontent.com/87473483/161846121-ca92a867-0955-4f98-832f-c457fbafc806.jpg)
![Screenshot_2022-04-06-04-45-00-618_com microsoft rdc androidx](https://user-images.githubusercontent.com/87473483/161846132-7dd37e8a-3ab5-46e0-8b41-b8af4104969b.jpg)

### Geyser Dump

bc:https://dump.geysermc.org/Kke2A1U4TOsXCwHCunXHP4xTUsMr9r

### Geyser Version

Latest Construction 

### Minecraft: Bedrock Edition Version

1.18.12

### Additional Context

paper:https://dump.geysermc.org/aQ4ddf1jtWbzcPdLabWDDrseGKdXpeMO

**Comment by RednedEpic** [comment]
Cannot replicate. Likely not a Geyser issue. Closing.
