### ISSUE TITLE
Abusing NACK results in a large number of wrong packet retransmissions

### ISSUE THREAD

**Issue by b23r0** [GeyserMC/Geyser#2920]
### Describe the bug

![1649230025(1)](https://user-images.githubusercontent.com/35518985/161919282-87d004ac-815b-4761-8806-4abbf44c37ae.png)

The Raknet protocol was not processed correctly, so that although the Geyser server received many packets correctly, it still sent a NACK to tell the client that it did not receive it, causing the client to retransmit for no reason, wasting a lot of bandwidth.

### To Reproduce

-

### Expected behaviour

-

### Geyser Version

2.02-snapshot

**Comment by rtm516** [comment]
This should be re-created over in https://github.com/CloudburstMC/Protocol/ since that's the library we use for raknet interaction
