### ISSUE TITLE
Block placing issues

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Geyser#2921]
### Describe the bug

Related to 1d3eebc678be9a17fb71141bdacd933c13477f0c

When a block is placed using the bedrock: Godbridging feature, ghost blocks appear.

### To Reproduce

1. Start godbridging on Bedrock.
2. Blocks sometimes disappear, then appear.  The same with the breaking blocks.

### Expected behaviour

Blocks should be placed normally.

### Server Version and Plugins

Spigot 1.17.1

### Geyser Version

Builded from 1d3eebc678be9a17fb71141bdacd933c13477f0c

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by Konicai** [comment]
Do you have `disable-bedrock-scaffolding` enabled or not?

**Comment by hausemaster3734** [comment]
> Do you have `disable-bedrock-scaffolding` enabled or not?

disabled.

**Comment by RednedEpic** [comment]
Please provide a dump & videos of this occurring.

**Comment by hausemaster3734** [comment]
Sorry, but that was a long time ago.  I will resubmit the complaint if I notice it again.

**Comment by hausemaster3734** [comment]
Builded a fresh version of Geyser (074d60d5b02cd0d0fc8deafe1a658f4aec15bdbd).  Here are the results https://youtu.be/JbO-jRxWS2c

Blocks are sometimes not placed.

 I can't provide a dump due to private reasons.

**Comment by hwittenborn** [comment]
I'm having the same issue, though it seems to only be happening on blocks that are placed far away from me.

**Comment by onebeastchris** [comment]
> I'm having the same issue, though it seems to only be happening on blocks that are placed far away from me (attempting to remine the same block over and over confirms this).
> 
> I'm using Geyser with a PaperMC instance.

Bedrock has a further reach than java, which causes this to occur - we are likely unable to fix this :/

As for the original issue - considering that there is no dump, and the video is offline, i'll close this as stale - if the issue still persists, open a new issue, with a Geyser dump, logs, and a video of the issue occurring. Thanks!
