### ISSUE TITLE
Blocks past y=265 height limit in the End don't show up

### ISSUE THREAD

**Issue by creativegamer03** [GeyserMC/Geyser#2922]
### Describe the bug

This is similar to issue #217 . It applies too on the End dimension, especially if using the Nullscape Modpack, or other datapacks that overhauls the End dimension exceeding the height limit on world generation.

When on a block, you "glitch" on it (aka gets tp'ed on a "safe" tp location). If I jump under this block, I get tp'ed down while jumping mid-air. If I jump over this block, I get tp'ed upward again until i move away from any of this "blocks".

If I try to break the "block", it acts as if its air.

### To Reproduce

1. Go to a build/structure that exceeds the height limit in the End.
2. Check the rest of the build above the limit.
3. (optional) Step on a block that is above the limit.

### Expected behaviour

I should be able to see the blocks above the height limit and be able to walk on it. I should also be able to break it as well.

### Screenshots / Videos

https://user-images.githubusercontent.com/66676126/162410895-c35894fd-ed29-44f5-9344-96a290271f40.mp4

Context on the video:
I was trying to retrieve my stuff from my graves (bc of Graves plugin) but failed multiple times due to this bug and shulkers. Was waiting for admins to come online.

NOTE: please ignore the part where I paused the game and was encircling something. I was trying to record the dynmap window encircling where I am. Here is where I was:
![image](https://user-images.githubusercontent.com/66676126/162411314-d6e2473c-7c73-4052-ac98-d4fb9c704234.png)

### Geyser Version

2.0.2-SNAPSHOT (git-master-37c854b)

### Minecraft: Bedrock Edition Version

1.18.120

**Comment by AnhNguyenlost13** [comment]
It probably can't be fixed without modification to the Bedrock client or swapping the End ID to Overworld ID.

**Comment by RednedEpic** [comment]
May possibly be fixed by 1.19 but unsure. Will keep opened for now.

**Comment by ItsMeTheKing** [comment]
Is there a way to fix this yet?

**Comment by ItsaGlitch1** [comment]
Here is a fix for now, in your datapack for nullscape, go to data/minecraft/dimension_type/the_end.json
Edit the file and change the 'height' and 'logical_height' to 256. Some areas may look like it's been cut off the top, but most of the time, it looks fine.

If you have a .jar file of nullscape, do the same thing by opening the jar file in an archive program like winrar.

**Comment by onebeastchris** [comment]
Closing in favor of https://github.com/GeyserMC/Geyser/issues/3804, as it is more general - thanks anyways for reporting!
