### ISSUE TITLE
Enchanting table quit unexpectedly

### ISSUE THREAD

**Issue by RICE0707** [GeyserMC/Geyser#2923]
### Describe the bug

Quit unexpectedly when using Enchanting table

### To Reproduce

1. Open Enchanting table
2. Place the item to be Enchanting on the Enchanting table

### Expected behaviour

Enchanting normally, without Quit unexpectedly

### Screenshots / Videos

[(Black Shark 4)](https://media.discordapp.net/attachments/906755198184218634/962010221612515328/Screenrecorder-2022-04-08-23-21-17-142.mp4) 

[(Xperia sony)](https://media.discordapp.net/attachments/906755198184218634/962009550741991474/mobizen_20220408_231824.mp4) 

[(i11 Pro)](https://media.discordapp.net/attachments/906755198184218634/962007711837458442/RPReplay_Final1649430818.mp4) 

[(i11)](https://media.discordapp.net/attachments/906755198184218634/962007140044791859/RPReplay_Final1649430702.mp4) 

### Server Version and Plugins

Version:

This server is running Mirai version git-Mirai-d3e2152 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: d3e2152 on ver/1.18.2)
Previous version: git-Paper-268 (MC: 1.18.2)

plugins( MiraiHost ):
AutoPluginLoader, BedrockPlayerManager, BrilliantRD, ChestCommands, ChestSort, CMILib, CoreProtect, CrazyAuctionsPlus, DiscordSRV, DriveBackupV2, EmployMe, Essentials, EssentialsProtect, EssentialsSpawn, explock*, FastAsyncWorldEdit (WorldEdit), floodgate, GSit, HolographicDisplays, InteractiveChat, LockettePro, LoneLibs, LuckPerms, MoneyDrops*, NoChunkLag, NoCollisions, PacketLimiter, PlaceholderAPI, Plan, ProtocolLib, PvPManager, Randomtp, Residence, SkinsRestorer, Skript, spark, TabTPS, TradeSystem, Vault

plugins( WaterfallHost ):
AltLimiter, floodgate, LuckPerms, ViaVersion

plugins( GeyserHost ):
Geyser

### Geyser Version

Build #1071

### Minecraft: Bedrock Edition Version

1.18.2 

### Additional Context

The server uses Geyser Standalone
BedrockPlayer <-> GeyserHost <-> WaterfallHost <-> MiraiHost

**Comment by Camotoy** [comment]
I'm unable to replicate this. Can you try with no other plugins (or as few as possible) and see if the issue persists?

**Comment by RICE0707** [comment]
> I'm unable to replicate this. Can you try with no other plugins (or as few as possible) and see if the issue persists?

We removed all plugins in one test and the problem still occurs.

**Comment by rtm516** [comment]
Could you try on stock paper or spigot? It might be something odd your specific fork is using. (Without any plusing again)

**Comment by RICE0707** [comment]
> Could you try on stock paper or spigot? It might be something odd your specific fork is using. (Without any plusing again)

After testing, the problem still occurs (using paper)

**Comment by Camotoy** [comment]
Using an opped account, please run `/paper dumpitem` (while using Paper or a fork) while holding any item that causes the crash and send the output here.

**Comment by RICE0707** [comment]
> Using an opped account, please run `/paper dumpitem` (while using Paper or a fork) while holding any item that causes the crash and send the output here.

Tested and every item that can be Enchanting will quit unexpectedly
And after using` /paper dumpitem `, the console output is` {Damage: 0} `

**Comment by RednedEpic** [comment]
Are you able to replicate this on 1.18.30 with the latest version of Geyser & Paper (not a fork)?

**Comment by RICE0707** [comment]
> 你能在 1.18.30 上用最新版本的 Geyser & Paper（不是叉子）複製這個嗎？

This problem still exists.

**Comment by Camotoy** [comment]
Can you please update and, if the problem still persists, add a new Geyser dump?

**Comment by RICE0707** [comment]
> 您能否更新一下，如果問題仍然存在，請添加一個新的間歇泉轉儲？

This problem still exists.
https://dump.geysermc.org/TYQD8jdx5kWpot0YWCo5hq358CqRIF4p

**Comment by RICE0707** [comment]
Thanks to the assistance of two developers, we solved this problem,
We found out that this is a "texture pack translation variable" issue
(those variables must be "%d" not "%s" )
After the change, the issue no longer occurs, thanks again for the developer's assistance
