### ISSUE TITLE
cannot interact with mobs or blocks while holding tools and you cant drop tools

### ISSUE THREAD

**Issue by nososho** [GeyserMC/Geyser#2924]
### Describe the bug

When holding a tool the player will not be able to hit entities. They will also not be able to mine blocks server-side, but client-side it will appear to be broken when it is not. Players are also able to client-side break blocks in worldguard no-build regions but are not server-sidedly broken. You also can't drop the tool, it will appear that you've dropped it but to other players it seems like you are still holding it.

### To Reproduce

1. hold a tool
2. find an entity or a block
3. try to hit the entity or break the block
4. the entity will not be harmed and the block will seem to be broken but it will not be broken to other players and will not drop after being broken

### Expected behaviour

the entity should be damaged and the block should be broken server-side and the item should be able to be dropped client-side

### Server Version and Plugins

output of `/version`:

`[18:07:23 INFO]: Checking version, please wait...
[18:07:23 INFO]: Current: git-Purpur-1566 (MC: 1.18.1)*
[18:07:23 INFO]: Previous: git-Purpur-1609 (MC: 1.18.2)
[18:07:23 INFO]: * You are running the latest version`

plugins:

`AdvancedRegionMarket, AuctionHouse, BerryMineIt, BungeeGuard, Citizens, CMILib, CombatLogX, CommandAliases, CommandPrompter, CrazyCrates, DecentHolograms, DeluxeMenus, Duels, eGlow, Essentials, EssentialsChat, EssentialsSpawn, GlobalExecute*, InteractiveBoard, Jobs, LuckPerms, Matrix, Multiverse-Core, Multiverse-NetherPortals, PlaceholderAPI, PlotSquared, PlugManX (PlugMan), ProtectionStones, ProtocolLib, Quests, QuickShop, RandomTeleport, SirBlobmanCore (SirBlobmanAPI, XSeries), SpawnerManager, TAB, TabCompleteFilter, Vault, VeinMiner, ViaBackwards, ViaRewind, ViaVersion, ViaVersionStatus, VoidGen, VoidSpawn, WorldEdit, WorldGuard`

### Geyser Dump

https://dump.geysermc.org/1JAPlTxWsQODqVB9LCXHU6sPHS4nWOEa

### Geyser Version

 2.0.2-SNAPSHOT (git-master-1d3eebc)

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by nososho** [comment]
never mind it was just that the item had weird characters in it which bedrock edition probably does not like

**Comment by Camotoy** [comment]
Can you hold the item and run `/paper dumpitem`? The output of that command will be posted in console - paste it here.

**Comment by nososho** [comment]
{Damage: 0, display: {Name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":true,"color":"#EAF79C","text":"i"},{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#9DA855","text":"Starter shovel"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":true,"color":"#EAF79C","text":"i"},{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#9DA855","text":""}],"text":""}', Lore: ['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#96826B","text":"»"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":true,"color":"#FEE8A8","text":"i"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#96826B","text":"User"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":true,"color":"#FEE8A8","text":"i"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#96826B","text":"«"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#CAB289","text":" +StonkyMonkey358"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"text":" "}],"text":""}', '{"extra":[{"text":" "}],"text":""}', '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#EAF79C","text":"⛏"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":true,"color":"gold","text":"i"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#EAF79C","text":"KaosMC"},{"italic":false,"obfuscated":true,"color":"gold","text":"i"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"#EAF79C","text":"⛏"}],"text":""}']}}

**Comment by Camotoy** [comment]
Seems like it works for me. It might be another plugin instead?
