### ISSUE TITLE
`Error thrown in PLAYER_NAME's event loop!`

### ISSUE THREAD

**Issue by From-pErfo** [GeyserMC/Geyser#2931]
### Describe the bug

[log.log](https://github.com/GeyserMC/Geyser/files/8500986/default.log)

Sorry I only provide some logs, if necessary I will run a separate server

### To Reproduce

This error occurs when a player joins the server, but only one player can trigger it
When I made a copy of the server [except the archive] for testing, everything is normal

### Expected behaviour

fix this bug or know how it happens

### Server Version and Plugins

```
> version
[12:51:14 INFO]: Checking version, please wait...
[12:51:14 INFO]: Current: git-Mirai-Purpur-934f245 (MC: 1.18.2)*
Unknown server version.
Previous version: git-Mirai-7838cca (MC: 1.18.2)
```
ProtocolLib, ViaBackwards, ViaVersion, SkinsRestorer, Multiverse-Core, Matrix, Geyser-Spigot, geyserhacks, floodgate-spigot, FastLoginBukkit, AuthM, ...

### Geyser Version

2.0.2-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.18.0

### Additional Context

Minecraft: Bedrock Edition Version: 
The background of this version is inside the mine
Is it a version incompatibility?

**Comment by RednedEpic** [comment]
Please try this on a supported server software like Paper or Spigot.
