### ISSUE TITLE
I can't use WiFi as a sever.

### ISSUE THREAD

**Issue by Tommyiup** [GeyserMC/Geyser#2932]
### Describe the bug

IDK why it happing, but if you do something in bedrock or java, you rejoin, and the Minecraft bedrock turns into a blank world, you can chat but only other users see it and you can't see others chat.

### To Reproduce

1. open bedrock and java
2. chat for a few minutes using bedrock and java
3. you can't see the java user chating you 
4. rejoin bedrock
5. blank world, can't move, you can chat but only other users see it and you can't see other chat

### Expected behavior

I think floodgate has some issues but IDK

### Screenshots / Videos

![螢幕擷取畫面 2022-04-17 184047](https://user-images.githubusercontent.com/102778906/163711107-e6bb5508-8be8-47ea-bb16-0d01b0be235d.png)

### Server Version and Plugins

 I using the newest geyserMC, floodgate, and spigot.

### Geyser Version

lastest

### Minecraft: Bedrock Edition Version

lastest as well

### Additional Context

I'm using WiFi and not LAN

**Comment by Camotoy** [comment]
Are you using a 10th or 11th generation Intel processor?

**Comment by Tommyiup** [comment]
so I find the issue, it was that I using wifi and not Lan. I find it everywhere and I didn't see anyone mention it issue for some reason. Can someone pls tell me how to fix it?
