### ISSUE TITLE
Unable to connect to server at all using 1.18.30

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#2934]
### Describe the bug

Since updating to the latest Geyser (and Minecraft client), I've been unable to connect using the Spigot version of Geyser.

### To Reproduce

1. Setup server using Geyser Spigot
2. Try to connect

### Expected behaviour

Be able to connect to the server.

### Server Version and Plugins

This server is running Geyser version 2.0.3-SNAPSHOT (git-master-137eb3e) (Java: 1.18.2, Bedrock: 1.18.0/1.18.1/1.18.2 - 1.18.30)

Spigot: 1.12.2-R0.1-SNAPSHOT git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)

Plugins (3): ViaVersion, floodgate, Geyser-Spigot (all newest versions)

### Geyser Dump

https://dump.geysermc.org/4aC973phK1hX6EfabVqInm7e5IpVZRNB

### Geyser Version

2.0.3-SNAPSHOT (git-master-137eb3e) (Java: 1.18.2, Bedrock: 1.18.0/1.18.1/1.18.2 - 1.18.30)

### Minecraft: Bedrock Edition Version

1.18.30

**Comment by Camotoy** [comment]
What error do you get when you try to connect? Try with a clean config with no changes?

**Comment by pinkpig58** [comment]
![connecting](https://user-images.githubusercontent.com/41856020/164070141-c6bbed7e-110c-4b73-81fc-a49bc711b0e0.jpg)

![timed out](https://user-images.githubusercontent.com/41856020/164070378-7f6f88a2-e1d9-4c39-b192-c02c569b87f1.jpg)

It just sits on this screen and doesn't connect me. It then times me out.
I've tried a fresh config: https://dump.geysermc.org/oyHca3UnqeDE3C7Jn7BefYKNaUi4LeI0

The only thing it says in the console is: [Geyser-Spigot] /IP tried to connect!

**Comment by Camotoy** [comment]
Have you tried restarting your client? Anything is possible, but I'm leaning towards this not being a Geyser issue, and probably not a Bedrock regression? I haven't heard anything with this specific message yet in the Discord since the update came out.

**Comment by pinkpig58** [comment]
Just tried restarting Minecraft and tried connecting on my phone, too, but no luck

**Comment by Camotoy** [comment]
Does connecting to other servers work? Maybe try with the vanilla Bedrock server?

**Comment by pinkpig58** [comment]
Yeah, I can connect to a Geyser Bungee server just fine.
I setup the new version of Geyser Spigot on a Windows server and I'm having the same issue with that as well: https://dump.geysermc.org/bJEUBXKYsIGF5gg6GEERJQBYCEYQUlhX

**Comment by Camotoy** [comment]
Can you send a dump from the BungeeCord Geyser? Does standalone Geyser work?

**Comment by pinkpig58** [comment]
Bungee dump: https://dump.geysermc.org/GkwnwSabU4gmjrJrrwkpFu97Asd1KfgW
I've never used standalone Geyser, personally, nor set up a server using that

**Comment by Camotoy** [comment]
So on the same port (if possible to test) and the same conditions where possible, it doesn't work on Geyser-Spigot but works on Geyser-BungeeCord?

**Comment by pinkpig58** [comment]
I've tried setting up Geyser-Spigot servers on two different machines, Linux and Windows.

I created a Geyser-Spigot and Geyser-BungeeCord server both using the default port on the same machine (with the same specs and config settings as my last Bungee dump I posted) and tried connecting and it still doesn't allow me in.

**Comment by Camotoy** [comment]
So which Geyser BungeeCord server were you able to successfully connect to? Was it yours?

**Comment by pinkpig58** [comment]
Yeah, the one I created yesterday: https://dump.geysermc.org/GkwnwSabU4gmjrJrrwkpFu97Asd1KfgW

**Comment by Camotoy** [comment]
Can you join our Discord? Ping me in #support.
