### ISSUE TITLE
Bedrock player can't drop glass bottle filled with water

### ISSUE THREAD

**Issue by jeffry1829** [GeyserMC/Geyser#2936]
### Describe the bug

Bedrock player can't drop glass bottle filled with water.

### To Reproduce

1. Let Bedrock player get a water bottle.
2. Fill it with water.
3. Drop it.
4. The dropped bottle is empty.

### Expected behaviour

Should drop bottle with water

### Server Version and Plugins

Paper version git-Paper-278 (MC: 1.18.2)
![image](https://user-images.githubusercontent.com/6897769/164158852-33d803b5-6d32-40c8-ad37-f56f5ac84682.png)

### Geyser Dump

https://dump.geysermc.org/abViRTyTaSdPRueVipewG7X05ehalORO

### Geyser Version

2.0.3-SNAPSHOT (git-master-137eb3e)

### Minecraft: Bedrock Edition Version

1.18.30

**Comment by Konicai** [comment]
The water bottle isn't actually filled with water. When the item is dropped the client "realizes" it was mistaken: https://github.com/GeyserMC/Geyser/issues/2727
