### ISSUE TITLE
Completed advancement colour is difficult to see in advancements menu

### ISSUE THREAD

**Issue by maxfire2008** [GeyserMC/Geyser#2937]
### What feature do you want to see added?

When viewing advancements with `/geyser advancements` it is difficult to see the text on completed advancements.
![image](https://user-images.githubusercontent.com/22722054/164160530-b5f0d42c-9025-4fdf-b80b-4d359f36c315.png)

The text colour should have more contrast with the light background - such as dark blue or red.

The colour is specified in [`core/src/main/java/org/geysermc/geyser/session/cache/AdvancementsCache.java`](https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/session/cache/AdvancementsCache.java#L143) line 143

### Are there any alternatives?

Adding a config option to change the colour would also suffice.

**Comment by Camotoy** [comment]
Personally I am against adding a config for something as small as this, but I am fine with changing this color.

**Comment by rtm516** [comment]
Maybe `§2` is better? (dark_green, #00AA00)
https://minecraft.fandom.com/wiki/Formatting_codes

**Comment by maxfire2008** [comment]
I think dark green would work well.
