### ISSUE TITLE
my laptop can't run geyserMC

### ISSUE THREAD

**Issue by Tommyiup** [GeyserMC/Geyser#2938]
### Describe the bug

I try to use my laptop as a server for my friends to play, but the server keeps going to the "blank world" when rejoining the server after the bedrock player does something. I try every way to fix it, using LAN and everything, and it didn't fix a damn thing. Ps fix.

### To Reproduce

1. join the server using bedrock
2. play for a bit
3. the game start run bad
4. rejoin
5. blank world

### Expected behaviour

geyser have some software bug

### Screenshots / Videos

![螢幕擷取畫面 2022-04-17 184047](https://user-images.githubusercontent.com/102778906/164193793-bee15d38-0a8e-4121-bf43-c8570baba279.png)

### Server Version and Plugins

the latest geyser, floodgate, etc.

### Geyser Dump

https://dump.geysermc.org/QWMXlt9yeqZvwhTG2HBBXB9eccnvhnow

### Geyser Version

1.2.0

### Minecraft: Bedrock Edition Version

1.18.12

### Additional Context

my laptop is Acer Swift 3 (SF314-511-71CY). Using 11th gen i7-1165G7, 16GB ram, and 1TB SSD.

**Comment by rtm516** [comment]
11th gen issue, see https://github.com/GeyserMC/Geyser/issues/2861
