### ISSUE TITLE
Can we add a config to adjust exactly which mods/plugins will be translated by Geyser?

### ISSUE THREAD

**Issue by Touch-Night** [GeyserMC/Geyser#2939]
### What feature do you want to see added?

Can we add a config to adjust exactly which mods/plugins will be translated by Geyser? When some mods required to be installed clientside are applied, while Geyser can't translate the features that those mods add, it continuously try to translate it, and that makes server laggy.

A config to adjust exactly which mods/plugins to be translated.

### Are there any alternatives?

remove the mods that need to be installed clientside.

**Comment by Camotoy** [comment]
This is incredibly difficult to add. When we receive packets from the server, we can't tell where they came from. If there's a performance concern, then please add a Spark dump `/spark profiler --thread *` with the bad performance.

This feature itself basically cannot be added. Thank you for filing an issue anyway.
