### ISSUE TITLE
Can't use anvil to change item name

### ISSUE THREAD

**Issue by YTiceice** [GeyserMC/Geyser#2942]
### Describe the bug

player can't use anvil to change item name

### To Reproduce

1. Open anvil
2. Put the item to be changing in the anvil
3. Enter new name

### Expected behaviour

player can use anvil to change item name

### Screenshots / Videos

https://cdn.discordapp.com/attachments/956776417595645953/966531214246821949/RPReplay_Final1650509379.mp4

### Server Version and Plugins

This server is running Mirai version git-Mirai-d7ef909 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: d7ef909 on ver/1.18.2)
You are running 8 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Mirai-d3e2152 (MC: 1.18.2)

### Geyser Version

2.0.3-SNAPSHOT(master-1078)

### Minecraft: Bedrock Edition Version

bedrock 1.18.30

**Comment by Jens-Co** [comment]
Update geyser, this issue was fixed in https://github.com/GeyserMC/Geyser/commit/575fe98c0f67e71eef9479eef03b9d89e0b947c2.
