### ISSUE TITLE
SignChangeEvent is not being fired

### ISSUE THREAD

**Issue by YellowZaki** [GeyserMC/Geyser#2944]
### Describe the bug

95% of the time SignChangeEvent (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/SignChangeEvent.html) is not being fired, so it can't by detected by plugins. On rare ocasions, it works.

No errors on console.

### To Reproduce

1. Setup a SignChangeEvent listener
2. Try to write a sign on bedrock
3. SignChangeEvent is not fired

### Expected behaviour

SignChangeEvent should be fired when the bedrock player finishes editing the sign

### Geyser Version

Geyser 2.0.3-SNAPSHOT (git-master-137eb3e) ( Java Edition: 1.18.2 Bedrock Edition: 1.18.0/1.18.1/1.18.2 - 1.18.30)

### Minecraft: Bedrock Edition Version

1.18.30

**Comment by Camotoy** [comment]
Is the sign actually saving on the server? (Try relogging and see if the text contents persist correctly)
This may be the same issue as #1063.

**Comment by YellowZaki** [comment]
> Is the sign actually saving on the server? (Try relogging and see if the text contents persist correctly) This may be the same issue as #1063.

I've just realised it is not being saved. The bedrock players sees the sign, but if he relogs, the text is gone (the sign block is not gone).

But the bug is different from https://github.com/GeyserMC/Geyser/issues/1063. Different symptoms.

**Comment by Camotoy** [comment]
What platform is Bedrock running on in this case? Switch, PC, etc.

**Comment by YellowZaki** [comment]
> What platform is Bedrock running on in this case? Switch, PC, etc.

I've tried with mobile and PC. And the same bug happens.

**Comment by Camotoy** [comment]
Let me know if everything is working in the next Geyser update.
