### ISSUE TITLE
Lag on bedrock edtion

### ISSUE THREAD

**Issue by username100099** [GeyserMC/Geyser#2945]
### Describe the bug

Lags every time you hit a mob the first time on bedrock edtion.

### To Reproduce

1. hit a mob (On bedrock edtion)

### Expected behaviour

not lag 

### Server Version and Plugins

just geyser and floodgate.

### Geyser Dump

unknown

### Geyser Version

latest

### Minecraft: Bedrock Edition Version

1.18 and up

**Comment by Konicai** [comment]
Does the client lag or does the mob lag (https://github.com/GeyserMC/Geyser/issues/2520)?

Please attach a video of it happening and a Geyser dump by running `/geyser dump` and sharing the link here.

**Comment by username100099** [comment]
The mobs lag only. On java edition its smooth
here's the geyser dump:https://dump.geysermc.org/tEtHs0AMrVbXD9WNhCxsPJF46islpRsH
The video is really laggy for some reason (obviously my device or the recorder) do you still need it? Basically the first hit takes a second to actually hit. It was tried on both an Amd cpu and an arm one. Both had the same results. I dont think i remember this being here in 1.16 and 1.17, just 1.18. The devices ram is 24gb and a 4 core cpu. But if you still need to video ill try again. The only plugins in the server is geyser,floodgate worldedit and worldguard.

**Comment by RednedEpic** [comment]
Thanks for the update! Will close in favor of #2520, but thanks for opening an issue regardless!
