### ISSUE TITLE
Geyser-Bungeecord not loading on WaterfallMC

### ISSUE THREAD

**Issue by byNixo** [GeyserMC/Geyser#2946]
### Describe the bug

Geyser is not loading on my Bungeecord server.

However, Floodgate works. Also on the subservers

Here is the error from the log:

![grafik](https://user-images.githubusercontent.com/74796414/164684515-e101f47a-51d0-4970-9e0c-0aa19226cdd9.png)

### To Reproduce

1. We added the plugin to our Bungeecord server
2. We added Floodgate (Floodgate goes)
3. We restarted the server and then this error came up

### Expected behaviour

Actually, the plugin should load. Unfortunately, it hasn't.

### Server Version and Plugins

Lobby:
![grafik](https://user-images.githubusercontent.com/74796414/164685194-0fe3a8ef-7c9c-4fa2-a377-434e2cc93ce0.png)

CityBuild: 
![grafik](https://user-images.githubusercontent.com/74796414/164685261-ffab2e8f-2731-4362-9e14-24d5e38d6de6.png)

### Geyser Version

this one: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1084/

**Comment by byNixo** [comment]
We installed ViaVersion on our Bungeecord.

Plugins from Bungeecord:
![grafik](https://user-images.githubusercontent.com/74796414/164686177-8454d2b8-8c8e-441b-bec5-6340134184ee.png)

**Comment by Konicai** [comment]
Geyser requires Java 16 or higher. Please join our Discord for any more setup issues
