### ISSUE TITLE
Boat triggers "moved wrongly"

### ISSUE THREAD

**Issue by GamuCEEP** [GeyserMC/Geyser#2947]
### Describe the bug

A client conected throught Floodgate to a server with geyser-spigot triggers a moved wrongly, sometimes it gives an ArrayIndexOutOfBounds 
![imagen](https://user-images.githubusercontent.com/91058173/164731683-425f67cc-2bb5-4d4e-b173-5190a17339b9.png)
![imagen](https://user-images.githubusercontent.com/91058173/164731762-f0e0cf9e-1f23-4c9d-9beb-f12252137ba0.png)

### To Reproduce

1. Have a server with geyser-spigot( 2.0.3-SNAPSHOT (git-master-5a94bda)) and floodgate installed(im on the lates version)
2. Have someone connect from a playstation(not sure if necesary) with minecraft bedrock edition
3. Have him place a boat

### Expected behaviour

Should place the boat without errors or warnings

### Server Version and Plugins

Papermc: 
![imagen](https://user-images.githubusercontent.com/91058173/164732670-c88f5481-eefb-4c6e-a01b-286386f96714.png)
Geyser
![imagen](https://user-images.githubusercontent.com/91058173/164732737-521e46a6-8202-46a6-9d16-419755edb9df.png)
Floodgate
![imagen](https://user-images.githubusercontent.com/91058173/164733075-69b9cc7e-c9cb-4296-8f15-f36f985b9f3b.png)

### Geyser Dump

 https://dump.geysermc.org/us6qWtyFAvcFuSFH1yzbAsZjuXMpzxoB

### Geyser Version

geyser-spigot( 2.0.3-SNAPSHOT (git-master-5a94bda))

### Minecraft: Bedrock Edition Device/Version

1.18.30 PlayStation 4

**Comment by Camotoy** [comment]
The ArrayIndexOutOfBounds error involves being in a chest inventory. I don't think it's related.

**Comment by Konicai** [comment]
Are those movement warnings occurring while the player is in the boat?

**Comment by GamuCEEP** [comment]
I think so, i could test it later, i think it is because when he went
exploring with a boat the logs filled with ilegal movement, aprox 3 or 4
per minute

**Comment by Camotoy** [comment]
Make sure you're updated to the latest Geyser version, just in case (we had some updates yesterday).

**Comment by GamuCEEP** [comment]
Oki, ill check it

**Comment by Jens-Co** [comment]
Closing due to lack of information, If you still having this issue please let us know and I'll reopen this issue.

thanks.

**Comment by neco222** [comment]
```diff
! [火 17:59:53 WARN  Server/PlayerConnection] Boat (vehicle of .〇〇〇〇〇〇) moved wrongly! 1.3935478839258835
! [火 17:59:53 WARN  Server/PlayerConnection] Boat (vehicle of .〇〇〇〇〇〇) moved wrongly! 1.6178538493409746
! [火 17:59:53 WARN  Server/PlayerConnection] Boat (vehicle of .〇〇〇〇〇〇) moved wrongly! 1.8359992853593994
! [火 17:59:53 WARN  Server/PlayerConnection] Boat (vehicle of .〇〇〇〇〇〇) moved wrongly! 2.0471830847029224
! [火 17:59:53 WARN  Server/PlayerConnection] Boat (vehicle of .〇〇〇〇〇〇) moved wrongly! 2.252958573349275
! [火 17:59:53 WARN  Server/PlayerConnection] Boat (vehicle of .〇〇〇〇〇〇) moved wrongly! 2.4539642384693536
! [火 17:59:54 WARN  Server/PlayerConnection] Boat (vehicle of .〇〇〇〇〇〇) moved wrongly! 2.6266585838883003
! [火 17:59:54 WARN  Server/PlayerConnection] Boat (vehicle of .〇〇〇〇〇〇) moved wrongly! 2.7624450528570534
! [火 17:59:54 WARN  Server/PlayerConnection] Boat (vehicle of .〇〇〇〇〇〇) moved wrongly! 2.868745969777379
! [火 17:59:54 WARN  Server/PlayerConnection] Boat (vehicle of .〇〇〇〇〇〇) moved wrongly! 2.951533800278945
! [火 17:59:54 WARN  Server/PlayerConnection] Boat (vehicle of .〇〇〇〇〇〇) moved wrongly! 3.0156050738630142
! [火 17:59:54 WARN  Server/PlayerConnection] Boat (vehicle of .〇〇〇〇〇〇) moved wrongly! 3.0916853961286392
! [火 17:59:54 WARN  Server/PlayerConnection] Boat (vehicle of 〇〇〇〇〇〇) moved wrongly! 3.1264430489254593```


How to fix?
