### ISSUE TITLE
Can't use stonecutter in 1.18.3

### ISSUE THREAD

**Issue by creativegamer03** [GeyserMC/Geyser#2949]
### Describe the bug

When I try to grind/craft a stone block using the stonecutter, it seems to reject the crafting event as it immediately reverts the crafting process. I thought this was fixed before the 1.18.3 update.

### To Reproduce

1. Use the stonecutter.
2. Place a stone block (or any quantity of stone blocks) on the first box.
3. Select a crafted stone option on the left panel.
4. Attempt to get the product.

### Expected behaviour

I should be able to collect the crafted block/s using the stonecutter.

### Screenshots / Videos

https://user-images.githubusercontent.com/66676126/164899930-eff96f94-436f-4ecf-af6a-01791e8d7ed3.mp4

### Geyser Version

2.0.3-SNAPSHOT (git-master-137eb3e)

### Minecraft: Bedrock Edition Device/Version

1.18.300

### Additional Context

I remember this bug has been fixed before. After the owner updated it to 1.18.3 because someone told him about it, it no longer works. I've already encountered this bug before.

**Comment by Konicai** [comment]
Your Geyser version is outdated and doesn't have the fix.
