### ISSUE TITLE
/fly in survival mode doesn't work

### ISSUE THREAD

**Issue by MathieuMQc** [GeyserMC/Geyser#295]
In my PaperMC server, I installed geyser-bukkit as a plugin (inventory) and everyting works perfectly but I can't fly in survival mode, I have to /gmc every time I want to fly... Can I do something about it ? Or is it a bug ? 

Thanks you and have a nice day !

**Comment by endevrr** [comment]
I imagine this has something to do with anti cheat, I'll look into it, When you say you can't fly what do you mean by that? You get kicked, teleported back or something else

**Comment by MathieuMQc** [comment]
When I double jump, I just stay on the ground. /fly is activated, and when I do /gmc (game mode creative), I can fly. The problem is in survival, impossible to fly. It works on java but not in bedrock. Thanks !

**Comment by DoctorMacc** [comment]
Confirmed with Paper-161 and Essentials. I cannot fly when in survival mode.

**Comment by RednedEpic** [comment]
> In my PaperMC server, I installed geyser-bukkit as a plugin (inventory) and everyting works perfectly but I can't fly in survival mode, I have to /gmc every time I want to fly... Can I do something about it ? Or is it a bug ?
> 
> Thanks you and have a nice day !

Please follow the issue format in the future.

**Comment by DoctorMacc** [comment]
Fixed with #396.
