### ISSUE TITLE
Bedrock player can place block on them

### ISSUE THREAD

**Issue by tbvns2** [GeyserMC/Geyser#2950]
### Describe the bug

All bedrock players can place block on on them

### To Reproduce

1. connect to a geyser server
2. place block under you

### Expected behaviour

They shouldn't place block here

### Screenshots / Videos

on bedrock:
https://user-images.githubusercontent.com/88189738/164977373-44a6299c-6cf1-47d6-8fc9-f51f6927c37f.mp4
on java:
https://user-images.githubusercontent.com/88189738/164977640-2f8e9816-1115-4be2-b867-a36cef34d079.mp4

### Server Version and Plugins

server: paper 1.8
bungee: waterfall (latest)

### Geyser Dump

https://dump.geysermc.org/TyIsKT6FapdOqoNuikmfJ7olHyAzDRaQ

### Geyser Version

2.0.3-SNAPSHOT (git-master-2f54bf0)

### Minecraft: Bedrock Edition Device/Version

windows edition

**Comment by RednedEpic** [comment]
Paper 1.8 / Via issue - see https://github.com/ViaVersion/ViaVersion/issues/1087.

We do not officially support 1.8 in any capacity & it is highly recommended you update off of such an ancient version to at least 1.12.2 but preferably the latest version of Minecraft.
