### ISSUE TITLE
Other versions (aternos)

### ISSUE THREAD

**Issue by BraveCaperCat** [GeyserMC/Geyser#2956]
### What feature do you want to see added?

I would like you to support earlier versions, so aternos add them as options for aternos.org servers.

### Are there any alternatives?

installing the latest version of geyser on a 1.12.2 server.

**Comment by Camotoy** [comment]
Install ViaVersion if your server is not on the latest. (1.18.2)

**Comment by BraveCaperCat** [comment]
BUT I CAN'T INSTALL GEYSER ON 1.12.2 USING ATERNOS!

**Comment by Camotoy** [comment]
This isn't something we can control. Ask Aternos to change this.

**Comment by BraveCaperCat** [comment]
I have a aternos account, but they don't let me use the forums.

**Comment by BraveCaperCat** [comment]
Aternos don't support earlier versions, because you don't.

**Comment by BraveCaperCat** [comment]
Via version doesn't affect plugins, only players.

**Comment by BraveCaperCat** [comment]
THAT IS SOMETHING THAT ISN'T TRUE, OR MIS INFO PASSED AROUND.

**Comment by Camotoy** [comment]
Geyser emulates Java players, however. So when it emulates connecting to a server, ViaVersion interacts with us there. 

This isn't misinformation. I have literally tested Geyser almost weekly with ViaVersion.

**Comment by BraveCaperCat** [comment]
I just tried using via-version and the latest version of geyser,
and it said geyser couldn't be loaded in the log.

**Comment by Camotoy** [comment]
You probably need to run with Java 16.

**Comment by BraveCaperCat** [comment]
That is a good point, but they only let me use JAVA 8 on 1.12.2 servers, since mods can only use JAVA 8 Features anyway, so it's pointless to use up more space.

**Comment by BraveCaperCat** [comment]
Wait, no they let me use java 16, but last time i checked it only said java 8 in the list.

**Comment by BraveCaperCat** [comment]
It worked with java 16!
