### ISSUE TITLE
The independent version of geyser uses too much bandwith

### ISSUE THREAD

**Issue by qwejerrywolf** [GeyserMC/Geyser#2960]
### Describe the bug

When using the independent version of geyser, the server will use too much bandwith which could cause players with low network bandwith to stuck for a long time when joining server. When using the plugin version then there's no such problem.

### To Reproduce

1.Use indepedent version of geyser on your server
2.Use bedrock client to join server with low bandwith
3.You'll stuck or simply disconnected

### Expected behaviour

The independent version of geyser should use the same amount of bandwith to plugin version

### Geyser Version

2.0.3-SNAPSHOT (git-master-31a84ea)

### Minecraft: Bedrock Edition Device/Version

1.18.31

**Comment by Camotoy** [comment]
There's nothing specifically code-wise that could cause standalone Geyser to use more bandwidth. But, bear in mind (depending on your setup), standalone has to make a TCP connection to your Java server. If that IP isn't local, then bandwidth has to be used on that.

**Comment by Konicai** [comment]
There isn't really much we can do about this issue, especially with the little information given. If you can provide more information and/or record some sort of metrics on Geyser standalone vs plugin usage, this could be reopened.
