### ISSUE TITLE
Arrow are very laggy

### ISSUE THREAD

**Issue by tbvns2** [GeyserMC/Geyser#2961]
### Describe the bug

When you try to shoot an arrow, it froze in air

### To Reproduce

1. take a bow
2. take some arrow
3. shoot with the bow
4. watch the arrow frozing in air

### Expected behaviour

We should see the trajectory of the arrow like on java

### Screenshots / Videos

On bedrock:
https://user-images.githubusercontent.com/88189738/166682720-b707f947-c244-4ad2-9d68-41d0ae475b5e.mp4
https://user-images.githubusercontent.com/88189738/166682744-91aeb11b-8484-4913-a01d-0bb49b6e0184.mp4
On java (what is expected):
https://user-images.githubusercontent.com/88189738/166682764-3450f854-e3f8-4583-8be6-82aae764aa57.mp4

### Server Version and Plugins

paper 1.8.8 (w/viaver)
Waterfall (latest w/geyser)

### Geyser Version

latest

### Minecraft: Bedrock Edition Device/Version

latest

### Additional Context

I don't think this is a bedrock or a java behavior, I also don't think it's caused by latency and all my server run a 20TPS

**Comment by Konicai** [comment]
Can you include a geyser dump please, and a list of plugins on the spigot server? It would also be useful to check if this occurs on newer server versions (1.12 or greater)

**Comment by Camotoy** [comment]
Looks like this is the same issue as #2844?

**Comment by tbvns** [comment]
also @Camotoy yea its seem like a duplicated

**Comment by Camotoy** [comment]
Then I'll close this issue so there isn't a duplicate. Feel free to continue there. Thanks.
