### ISSUE TITLE
Lore isn't showing correctly in Chest GUI

### ISSUE THREAD

**Issue by spikehidden** [GeyserMC/Geyser#2962]
### Describe the bug

When opening the Shop GUI of [EconomyShopGUI](https://www.spigotmc.org/resources/69927/) the Lore isn't showing correctly if you're either in Admin mode or use the player/global stock feature.

### To Reproduce

1. Install EconomyShopGUI
2. Open the GUI as OP/admin
3. See the error as a Bedrock Player.

OR

1. Install EconomyShopGUI
2. Create a new item or edit one to use the player/global stock feature
3. Open the item with Bedrock

### Expected behaviour

To have it correctly rendered as in Java Edition.

### Screenshots / Videos

**Java Edition**
![2022-05-04_16 07 17](https://user-images.githubusercontent.com/31257733/166704995-c1c0b117-bb84-4c28-87cc-92e8d24a3d7d.png)
**Bedrock Edition (Windows 11)**
![Screenshot (132)](https://user-images.githubusercontent.com/31257733/166705131-d286b9e3-e810-48fd-a17c-eb73dffd8142.png)

### Server Version and Plugins

This server is running Paper version git-Paper-264 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: a686ff5)
You are 53 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-260 (MC: 1.18.2)

### Geyser Dump

https://dump.geysermc.org/JwJqGRnC52exkgwpQXdf8Wml0lYcNHcn

### Geyser Version

2.0.3-SNAPSHOT (git-master-31a84ea)

### Minecraft: Bedrock Edition Device/Version

1.18.31 Windows 11, 1.18.31 Nintendo Switch

**Comment by spikehidden** [comment]
This seems to be fixed.
At least it doesn't happen anymore for me.

**Comment by onebeastchris** [comment]
Does this issue still occur with the latest version of Geyser? If it does, please send a new Geyser dump.

**Comment by spikehidden** [comment]
No it seems to fixed in the newest version.

In case it should appear again and you close this issue shall I open a new one or reopen this one?

**Comment by onebeastchris** [comment]
In case it re-appears, open a new one. Thanks for the reply!
