### ISSUE TITLE
Stair Movement Teleportation

### ISSUE THREAD

**Issue by JayeshRocks** [GeyserMC/Geyser#2963]
### Describe the bug

Whenever trying to go on stairs in Geyser-Spigot with floodgate, bedrock players keep teleporting up and down and then get kicked with message "(!) moved unexpectedly"

### To Reproduce

Setup server with Geyser-Spigot and Floodgate Auth on a minecraft 1.18.2 server and place stairs and walk on them

### Expected behaviour

Just walk normally on the stairs like in the Geyser standalone I am able to walk normally, Geyser-Spigot and Floodgate is teleporting on stairs and then finally kicking

### Server Version and Plugins

This server is running Geyser version 2.0.3-SNAPSHOT (git-master-31a84ea)
 (Java: 1.18.2, Bedrock: 1.18.0/1.18.1/1.18.2 - 1.18.30/1.18.31)

### Geyser Dump

https://dump.geysermc.org/Q0lbfWp3YipK4j7Km9UhSwhMvo2rmclD

### Geyser Version

Geyser version 2.0.3-SNAPSHOT (git-master-31a84ea)

### Minecraft: Bedrock Edition Device/Version

1.18.31 Minecraft Bedrock Mobile

**Comment by AnhNguyenlost13** [comment]
Can you list the server plugins? A normal Spigot/Paper server would never kick you after moving wrongly too much.

**Comment by Camotoy** [comment]
The server plugins are listed in the dump. Can you try with no other plugins?

**Comment by AnhNguyenlost13** [comment]
Can you try removing NoCheatPlus specifically?

**Comment by AnhNguyenlost13** [comment]
> The server plugins are listed in the dump. Can you try with no other plugins?

Well then technically we don't need the **Server Version and Plugins** section anymore 🙃

**Comment by Jens-Co** [comment]
> > The server plugins are listed in the dump. Can you try with no other plugins?
> 
> 
> 
> Well then technically we don't need the **Server Version and Plugins** section anymore 🙃

When Geyser fails to load a dump cannot be created, therefore mc version, plugins & logs are required.

**Comment by JayeshRocks** [comment]
Alright, it looks like it was NoCheatsPlus Plugin interferefing, my bad
