### ISSUE TITLE
Geyser doesn't handle velocity correctly

### ISSUE THREAD

**Issue by tbvns2** [GeyserMC/Geyser#2965]
### Describe the bug

When you apply velocity to an entity, it will not move on bedrock (arrow, tnt ...)

### To Reproduce

1. Spawn a mob
2. Apply a velocity to the mob

### Expected behaviour

Entity should move correctly when velocity is applied

### Screenshots / Videos

On bedrock:
https://user-images.githubusercontent.com/88189738/167261932-cc3b0cf2-4b29-4b9d-a496-8cf11c55c66f.mp4
On java:
https://user-images.githubusercontent.com/88189738/167261941-9ad5a005-97a4-49db-9736-52554e5bd8eb.mp4

### Server Version and Plugins

paper 1.8.8 w/ Waterfall (latest)
plugins: 
![Capture](https://user-images.githubusercontent.com/88189738/167262033-aae7fafc-4598-43b2-abaf-872a63e055f1.PNG)

### Geyser Version

latest

### Minecraft: Bedrock Edition Device/Version

latest/Windows

### Additional Context

It also happens with particles

**Comment by RednedEpic** [comment]
Can you please try this on a supported version like 1.18.2? Only reports I've seen of this are on 1.8 which we do not support.

**Comment by tbvns2** [comment]
ok

**Comment by tbvns2** [comment]
When I try to connect with a  java 1.18 player on the 1.18 server it work but for bedrock it writes an error message that say: “if you wish to use IP forwarding pls enable it in your bungee config as well”

**Comment by Jens-Co** [comment]
This can occur due to
1) a non functional key.pem that was being copied to the backend server ( fix would be re-copy the key )
2) floodgate wasn't installed on all backend servers
3) you have enabled send-data in floodgate config.yml without floodgate being present on the backend (2)

if you are not using/needing the floodgate api you should disable the option in floodgate config.yml in velocity.

**Comment by pinkpig58** [comment]
If I'm not mistaken, this is a pretty similar issue to #2844

**Comment by tbvns2** [comment]
Yea, I tested on 1.18 and there is no lag with arrow or TNT. It's sad that I can't update because it's a PVP server.

**Comment by tbvns2** [comment]
So I guess I can close this because you don't support 1.8
