### ISSUE TITLE
Chunck will not loaded on PS4-Players

### ISSUE THREAD

**Issue by Leahcimkrob** [GeyserMC/Geyser#2966]
### Describe the bug

Hello,
we are having problems with one of our Playstation 4 players.
She can join and as long as she is in a world with plotsuqared or oneblock she can move without any problems.
As soon as she goes to the farm world, Nether or End, her chuncks no longer load, she cannot move and a short time later the game crashes for her.
Bedrock players with Windows 10/11, Switch, cell phone, etc. do not have the problems.
Is this possibly due to Geyser or Floodgate?
do you know the behavior

Thanks in advance
Michael

### To Reproduce

Login to Server
Go to "Farmwelt"

### Expected behaviour

Hello,
we are having problems with one of our Playstation 4 players.
She can join and as long as she is in a world with plotsuqared or oneblock she can move without any problems.
As soon as she goes to the farm world, Nether or End, her chuncks no longer load, she cannot move and a short time later the game crashes for her.
Bedrock players with Windows 10/11, Switch, cell phone, etc. do not have the problems.
Is this possibly due to Geyser or Floodgate?
do you know the behavior

Thanks in advance
Michael

### Server Version and Plugins

https://athion.net/ISPaster/paste/view/0451f990dfac4b77b114e135a88397df

### Geyser Dump

https://dump.geysermc.org/sz3QC0JHF0OMtzH50bpIBx4AbOqb1XQk

### Geyser Version

2.0.3-Snapshot

### Minecraft: Bedrock Edition Device/Version

PS4

**Comment by Leahcimkrob** [comment]
we have updated to Build #1097 with the same issue. 
many other server like Yinandyang.eu

**Comment by onebeastchris** [comment]
Does this issue still occur with the latest version of Geyser?

**Comment by Leahcimkrob** [comment]
Now the problem still occurs in some regions, but the game then crashes completely on our console players, like xBox, PS4 and PS5. Handy and MC for Win so far everything is fine.

**Comment by onebeastchris** [comment]
Could you send a new Geyser dump?

**Comment by Leahcimkrob** [comment]
> version
[15:53:24 INFO]: Checking version, please wait...
[15:53:24 INFO]: This server is running Paper version git-Paper-383 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: b082d89)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-307 (MC: 1.19.2)

>geyser dump
15:54:46 [INFO] CONSOLE executed command: /geyser dump
15:54:46 [INFO] Collecting dump info
15:54:46 [INFO] Uploading dump
15:54:46 [INFO] We've made a dump with useful information, report your issue and provide this url: https://dump.geysermc.org/GoUpPKuIHst5umjgWvE8Z55ZU7FJpeP7

**Comment by onebeastchris** [comment]
Hm, nothing immediately obvious.. I don't think it's related to the encryption bug in #2861, nor does it appear that the chunk loading fix recently did much
I'm afraid there's not much I can do here, don't have a PS4 to test/troubleshoot. It's likely something geyser's debug mode will tell more about though..
Is there any error in the server when the Bedrock player gets booted?

**Comment by Leahcimkrob** [comment]
There are no mistakes.

**Comment by ManifestJW** [comment]
I'm having a similar issue to this. One of our PS4 players is complaining about chunk loading issues, though their game is not crashing. A relog seems to fix the chunks, but then different chunks begin to break, and it's becoming extremely frustrating for him. There's a console error that I'm getting. 
![image](https://user-images.githubusercontent.com/72364382/235575198-ed3dcc9c-ab1c-4c94-8985-3e766b41f558.png)

Running on Paper 1.16.5

**Comment by onebeastchris** [comment]
> I'm having a similar issue to this. One of our PS4 players is complaining about chunk loading issues, though their game is not crashing. A relog seems to fix the chunks, but then different chunks begin to break, and it's becoming extremely frustrating for him. There's a console error that I'm getting. 
> ![image](https://user-images.githubusercontent.com/72364382/235575198-ed3dcc9c-ab1c-4c94-8985-3e766b41f558.png)
> 
> Running on Paper 1.16.5

Could you try updating Geyser to the latest version? This downstream packet error should be fixed; would be interesting to see if that was related to PS4 players being unable to load chunks

**Comment by Leahcimkrob** [comment]
currently there is only the problem with the holograms, but I have opened a separate issue for that. So this can be closed.

**Comment by onebeastchris** [comment]
Closing due to no response.
