### ISSUE TITLE
You cannot put Infinty and Mending together. [PurPur]

### ISSUE THREAD

**Issue by spikehidden** [GeyserMC/Geyser#2972]
### Describe the bug

If you set `allow-infinity-and-mending-together` in the `purpur.yml` to `true` it's still not possible to put infinity and mending together on one bow.

### To Reproduce

1. Get a bow with either mending or infinity.
2. Get a book with the other enchantment
3. Try putting them together at an anvil as a Bedrock Player
4. Doesn't work...

### Expected behaviour

It should be possible the same way as for Java Edition players.

#### Java Edition
https://user-images.githubusercontent.com/31257733/168443198-23fb27bd-9f81-443b-bd57-cc34f259317b.mp4
#### Bedrock Edition
https://user-images.githubusercontent.com/31257733/168443201-11049d61-71b6-4074-8931-d1610b248974.mp4

### Server Version and Plugins

```
Current: git-Purpur-1623 (MC: 1.18.2)*
Previous: git-Paper-333 (MC: 1.18.2)
* You are running the latest version
```

### Geyser Dump

https://dump.geysermc.org/MtlIqLg5Ooorb9gDoaCr7dsipwaBQSpU

### Geyser Version

version 2.0.3-SNAPSHOT (git-master-db13b4c)

### Minecraft: Bedrock Edition Device/Version

1.18.32/33 | Windows 11 &  Nintendo Switch

**Comment by Camotoy** [comment]
If I had to guess, this is a Bedrock limitation, since it likes to make client-side assumptions about the result slot in an anvil.

**Comment by hausemaster3734** [comment]
> If I had to guess, this is a Bedrock limitation, since it likes to make client-side assumptions about the result slot in an anvil.

You can't make anvil recipes on Bedrock.  They cannot be changed in any way, and they are not even present in the Bedrock data. Clearly client side.

**Comment by From-pErfo** [comment]
Is it possible to fix these problems by sending fake enchanted books to Bedrock Edition players?
For example, showing the enchantment and level on the title of empty enchanted books, this will also solve the problem that some enchanted books cannot be seen in Bedrock Edition.

**Comment by Camotoy** [comment]
You'd have to trick Bedrock into showing an item in the result slot.

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/issues/3121 closing in favor of the linked issue
