### ISSUE TITLE
Jiggling blocks when teleporting long distances

### ISSUE THREAD

**Issue by Dex9379** [GeyserMC/Geyser#2973]
### Describe the bug

When teleporting long distances, say '/tp 1000000 1000000 1000000' the blocks would jiggle when moving.

### To Reproduce

1. Do /tp 1000000 1000000 1000000' or teleport to any coordinates far away
2. Walk around

### Expected behaviour

No jiggling blocks

### Geyser Dump

https://dump.geysermc.org/YyUzc8adQQpuzhKYRYRmbi2bN6tbqSDN

### Geyser Version

2.0.3-snapshot (git-master-db13b4c)

### Minecraft: Bedrock Edition Device/Version

1.18.31 Windows 10

**Comment by Camotoy** [comment]
This is unfortunately not something we can reasonably work around: https://minecraft.fandom.com/wiki/Bedrock_Edition_Far_Lands :/

Thanks anyway.
