### ISSUE TITLE
Bukkit's API Border compatibility

### ISSUE THREAD

**Issue by emmanuelvlad** [GeyserMC/Geyser#2974]
### Describe the bug

World border is not visible on `player.setWorldBorder()`

### To Reproduce

```java
WorldBorder wb = Bukkit.createWorldBorder();
wb.setCenter(location);
wb.setSize(size);

player.setWorldBorder(wb);
```

### Expected behaviour

World border should be visible

### Server Version and Plugins

Paper version git-Paper-312 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: ce059b4)

### Geyser Version

2.0.3-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.18.32, Android

### Additional Context

Wondering if the cause isn't that CraftBukkit doesn't send the packet `ClientboundInitializeBorderPacket` when `setWorldBorder` is invoked.

[Opened an issue there too](https://hub.spigotmc.org/jira/browse/SPIGOT-7020)

**Comment by Camotoy** [comment]
Thanks for opening an issue over at Spigot, but yeah, this is an issue on our end.

```java
Bukkit.getCommandMap().register(this.getName(), new Command("playerworldborder") {
            @Override
            public boolean execute(@NotNull CommandSender sender, @NotNull String commandLabel, @NotNull String[] args) {
                if (sender instanceof Player player) {
                    WorldBorder wb = Bukkit.createWorldBorder();
                    wb.setCenter(player.getLocation());
                    wb.setSize(100);

                    player.setWorldBorder(wb);
                }
                return false;
            }
        });
 ```
 
 This correctly makes a world border for me.

**Comment by emmanuelvlad** [comment]
Oh nevermind, the problem comes from `setWarningDistance` when set to `0` the border will not show

**Comment by Camotoy** [comment]
OK, adding that correctly does not let me pass, but no particles are shown.

**Comment by Camotoy** [comment]
https://github.com/GeyserMC/Geyser/commit/b885e22fa39afe6abcc66aaba4101aefabcbe3d0 should fix your issue by ensuring the world border is always visible five blocks away. Let me know otherwise.
