### ISSUE TITLE
Pocket Edition?

### ISSUE THREAD

**Issue by Draconis062** [GeyserMC/Geyser#2975]
### Describe the bug

Upon adding Geyser to my server, I have some Pocket Edition players joining the server that are unable to open/pass through single doors and can't place/open chests, nor can they break blocks. Any ideas on a fix for that?

### To Reproduce

1. Add geyser to Java Server
2. Pocket Edition players can join but have limited actions

### Expected behaviour

Pocket Edition players can't place/break blocks or open chests/doors

### Geyser Version

Spigot

**Comment by Camotoy** [comment]
Are you using a 10th- or 11th-gen Intel processor on the server running Geyser? If so: https://github.com/GeyserMC/Geyser/issues/2861

**Comment by Draconis062** [comment]
It's run through Multicraft

**Comment by Jens-Co** [comment]
I'll close this issue due to lack of information, if you still having this issue please add the needed info as Konica^ told. I'll reopen issue then.

thanks.
