### ISSUE TITLE
Mass "InitialHandler has pinged" Messages

### ISSUE THREAD

**Issue by runesage** [GeyserMC/Geyser#2977]
### Describe the bug

When running geyser with bungeecord I am getting nonstop messages about InitialHandler has pinged as described in the previous bug ticket #583 

Spigot: 3486-Spigot-b6d12d1-f3c7a6a (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)
Bungee: BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT
Geyser: Geyser 2.0.3-SNAPSHOT

### To Reproduce

1. Set up and Run Bungeecord
2. Run geyser
3. See mass alerts of initial handler has pinged

### Expected behaviour

no initialhandler spam

### Screenshots / Videos

<img width="491" alt="image" src="https://user-images.githubusercontent.com/56613600/168694184-bfa8819d-e56e-495a-bb07-1e94696eef7a.png">

### Geyser Version

Geyser 2.0.3-SNAPSHOT

**Comment by Camotoy** [comment]
Disabling the legacy ping passthrough setting should fix this. Let us know if it doesn't.

**Comment by runesage** [comment]
my legacy ping passthrough setting is false in the geyser config already

**Comment by runesage** [comment]
I can attach my config if that is helpful or provide any additional information to help resolve this.

**Comment by Camotoy** [comment]
Please provide a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by runesage** [comment]
https://dump.geysermc.org/JAv19cAo1Q54ChjYd5H8TOkx7Y7zAIkr

**Comment by Camotoy** [comment]
The standalone version always uses the legacy ping passthrough method. Unless you disable ping passthrough settings or filter the log in BungeeCord, there isn't anything we can do.
