### ISSUE TITLE
Java mod/plugin that changes java minecraft to match bedrock behaviour

### ISSUE THREAD

**Issue by JRBros2346** [GeyserMC/Geyser#2978]
### What feature do you want to see added?

Java have mods, which can do much better in modifying the game. While bedrock don't have a good feature to modify the game. Even if it is possible to modify our game using add-ons, we can't apply those to servers. It is impossible to make a java to bedrock pocket converter. But if java could better match bedrock (like god-bridging) then we bedrock players could play java servers seamlessly.

### Are there any alternatives?

make a geysermc mod/plugin that modifies java and connect bedrock simultaneously. Or if possible make the pocket converter to not allow god-bridging and such bedrock exclusive features and add java exclusive features to bedrock. The second feature is probably more difficult because bedrock is not flexible and java is flexible

**Comment by Gaming32** [comment]
I recommend checking out the [BedrockIfy](https://github.com/juancarloscp52/BedrockIfy) mod.

**Comment by RednedEpic** [comment]
See the mod posted above - this is unfortunately out of scope of the Geyser project.
