### ISSUE TITLE
Extreme lag on android devices

### ISSUE THREAD

**Issue by username100099** [GeyserMC/Geyser#2979]
### Describe the bug

While trying geyser on an apple device it was smooth and no lag issues but on android smartphones with 3gb ram it lags severely.

### To Reproduce

1. log onto a crossplay/geyser server on android

### Expected behaviour

For it to not lag

### Server Version and Plugins

Geyser and floodgate only

### Geyser Dump

https://dump.geysermc.org/n1jzxWdIllcxES6RIQfBpjyq1tk3XtZM

### Geyser Version

latest

### Minecraft: Bedrock Edition Device/Version

1.18.32

**Comment by sebastianjnuwu** [comment]
Hum

**Comment by username100099** [comment]
> Hum

hmm...

**Comment by Konicai** [comment]
Is it only one android device that experiences it? What model is it?

Older phones will inevitably suffer performance costs and there isn't really anything we can do about it. In the past I've seen issues with lots of player heads (`allow-custom-skulls` is enabled by default), lots of entities, large structures, etc.

**Comment by username100099** [comment]
> Is it only one android device that experiences it? What model is it?
> 
> Older phones will inevitably suffer performance costs and there isn't really anything we can do about it. In the past I've seen issues with lots of player heads (`allow-custom-skulls` is enabled by default), lots of entities, large structures, etc.

@Konicai it's a mid-high end device (samsung galaxy A20)

**Comment by username100099** [comment]
It's also not just my device. When running a server with some bedrock people in it most people say they felt laggy. I have a high feeling it's the amount of grass in java edition but I'm not sure.

**Comment by MrZomka** [comment]
> > Is it only one android device that experiences it? What model is it?
> > Older phones will inevitably suffer performance costs and there isn't really anything we can do about it. In the past I've seen issues with lots of player heads (`allow-custom-skulls` is enabled by default), lots of entities, large structures, etc.
> 
> @Konicai it's a mid-high end device (samsung galaxy A20)

That is not a mid-high end device, that's a 2-3 year old budget phone.

**Comment by RednedEpic** [comment]
Best to follow up with this on Discord. Very likely not a Geyser problem.
