### ISSUE TITLE
Save password for logging through mojang accounts.

### ISSUE THREAD

**Issue by DreamOneX** [GeyserMC/Geyser#2984]
### What feature do you want to see added?

I start a server with [authlib-injector authentication](https://github.com/yushijinhun/authlib-injector), logging a server through it is almost the same as logging through mojang accounts. Players must enter their account passwords every time they log in. Because the latest Geyser can't save passwords of mojang accounts. Can geyser support it again?

### Are there any alternatives?

Use an old geyser version that can save mojang accounts password.

**Comment by Konicai** [comment]
The password saving system was removed for a reason. Also, all mojang accounts must migrate to microsoft accounts at this point, and we might even remove logging in with passwords with microsoft for various reasons (https://github.com/GeyserMC/Geyser/issues/2868)

We only support authentication with legitimate auth logins and servers anyway.

**Comment by Camotoy** [comment]
The latest Geyser version still should support saving passwords - the config options have just been hidden by default and likely need to be pasted in from a previous config. However, be warned that we will be removing Mojang account support once real Mojang players can no longer log in.

**Comment by DreamOneX** [comment]
> The latest Geyser version still should support saving passwords - the config options have just been hidden by default and likely need to be pasted in from a previous config. However, be warned that we will be removing Mojang account support once real Mojang players can no longer log in.

I see, Thanks.
