### ISSUE TITLE
Rendering bug

### ISSUE THREAD

**Issue by Julienraptor01** [GeyserMC/Geyser#2986]
I made a fabric server with this [build of Geyser-Fabric](https://ci.opencollab.dev/job/GeyserMC/job/Geyser-Fabric/job/java-1.18/164/) and i got this when i connected with my bedrock client while when i connect with my java client it works just fine
https://www.youtube.com/watch?v=6YF3_gV4cEk
BEWARE OF THE FLASHING IMAGES !!!
Version used
Fabric 0.14.6
Fabric API 0.53.0
Geyser-Fabric https://ci.opencollab.dev/job/GeyserMC/job/Geyser-Fabric/job/java-1.18/164/

**Comment by davchoo** [comment]
I'm pretty sure this is a bug in Bedrock https://bugs.mojang.com/browse/MCPE-155509
I get this consistently when playing singleplayer at 32 chunk render distance on 1.18.32

**Comment by Julienraptor01** [comment]
> I'm pretty sure this is a bug in Bedrock https://bugs.mojang.com/browse/MCPE-155509 I get this consistently when playing singleplayer at 32 chunk render distance on 1.18.32

yep it's exactly this but idk why it doesn't happen on other worlds at the same render distance...
i guess i'm gonna lower it and try if it still heppen

**Comment by Julienraptor01** [comment]
Yeah it's vanilla problem idk why it still doesn't happen in solo and other multiplayer but it's not your fault
