### ISSUE TITLE
Entity rotation is (occasionally?) incorrect

### ISSUE THREAD

**Issue by DoctorMacc** [GeyserMC/Geyser#299]
**Describe the bug**
Entities appear to face the wrong way in certain scenarios. 

**To Reproduce**
View entity rotation from both Java and Bedrock

**Screenshots / Videos**
See #288 for an example with cats.

**Server Version**
Paper 161

**Geyser Version**
Geyser Master 21, Inventory 10

**Minecraft: Bedrock Edition Version**
1.14.30

**Comment by MrBlockCat** [comment]
I've noticed paintings sometimes are rotated sideways on bedrock vs appearing normally on Java whether placed by a Java or bedrock player; Would that be the same issue as this?

**Comment by DoctorMacc** [comment]
Potentially - I haven't looked into paintings yet.

**Comment by DoctorMacc** [comment]
Boats *almost* have the correct rotation values - mostly involves turning 90 degrees occasionally. Occasionally the boat will glitch back to its incorrect state, though, definitely after coming to a halt near a ledge. I plan on using this information and trying to apply it to the entire entity system.
