### ISSUE TITLE
Geyser perform poorly on bungee cord

### ISSUE THREAD

**Issue by tbvns2** [GeyserMC/Geyser#2990]
### Describe the bug

When you run geyser bungee cord, the latency for bedrock player increase by ~100 ms but on spigot it's only ~20 ms when i tested this I run both off them with 1gig of ram.

### To Reproduce

1. install geyser on bungee cord
2. connect to your bungee with bedrock.

### Expected behaviour

The latency should be like on the spigot version

### Server Version and Plugins

waterfall, latest

### Geyser Dump

https://dump.geysermc.org/tAECAHNK5DhAYItCbgvC2BTlN3faTlBP

### Geyser Version

git-master-3862531

### Minecraft: Bedrock Edition Device/Version

latest

### Additional Context

I also use via version to connect to my PVP server, but I have tested this on a 1.18 server.

**Comment by tbvns2** [comment]
I also tried to increase the ram allowed to waterfall from 1gig to 4 gig.

**Comment by MrZomka** [comment]
1. I'd remove the anti-bot plugin since it could be causing issues. Your server is online-mode, why do you even need an anti-bot?
2. You don't need Log4j-prevent if you are on the latest version of Bungeecord.
