### ISSUE TITLE
Bedrock players cannot see minecraft:effect particles

### ISSUE THREAD

**Issue by chandlerpl** [GeyserMC/Geyser#2991]
### Describe the bug

Bedrock players cannot see the particle with namespace key "minecraft:effect". This has been tested with and without the optional resource pack installed.

### To Reproduce

Use any Geyser build that works for v1.18.31
Spawn a particle using /particle minecraft:effect
Java players can see particle, Bedrock players can not

### Expected behaviour

Should be able to see the effect particle

### Server Version and Plugins

This server is running Paper version git-Paper-345 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: a90092e)
You are running the latest version
Previous version: git-Paper-388 (MC: 1.17.1)

### Geyser Version

Geyser version 2.0.3-SNAPSHOT (git-master-3862531)

### Minecraft: Bedrock Edition Device/Version

v1.18.31

**Comment by Kas-tle** [comment]
Effect is not modified by GeyserOptionalPack (see [developer_documentation.md](https://github.com/GeyserMC/GeyserOptionalPack/blob/master/developer_documentation.md#Particles)) and was working at the time of its release so I assume the regression is some time in between now and then.

**Comment by onebeastchris** [comment]
Unable to replicate:

https://github.com/GeyserMC/Geyser/assets/105284508/c60c9031-a87f-4677-8a02-81b0d142e96c
