### ISSUE TITLE
Bedrock players unable to interact fully

### ISSUE THREAD

**Issue by Eutaxy1** [GeyserMC/Geyser#2992]
### Describe the bug

Bedrock players are unable to open some chests, use some furnaces, break some blocks, etc.

### To Reproduce

Not sure what's causing it, but it might be that this world was converted from an older version of bedrock, i.e. Education Edition
1. Convert world from bedrock/education edition
2. Install both Geyser and Floodgate onto a Spigot server
3. Have a bedrock player join and try to interact with everything

### Expected behaviour

Bedrock players able to interact with everything

### Server Version and Plugins

CraftBukkit version 3491-Spigot-b081915-95d233d (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

Plugins:
EssentialsX
EssentialsChat
TrollBoss
CoreProtect
HerobrineAI
Brewery
OpenInv
WorldEdit
PermissionsEx (unconfigured yet)
Geyser
Floodgate

### Geyser Dump

https://dump.geysermc.org/mGmmipzKBZ9eKs66aycueSSdduiU3Y8V

### Geyser Version

2.0.3-SNAPSHOT (git-master-3862531)

### Minecraft: Bedrock Edition Device/Version

1.18.31, Xbox One

### Additional Context

Like I said above, this was a world that was converted from a Chromebook Education Edition version of minecraft, that was converted using Chunker after being tweaked by MCC Tool Chest PE to disable the education edition stuff.

**Comment by Camotoy** [comment]
I would assume the world is not the issue here. Can a player chat? Can you try with no other plugins other than Geyser and Floodgate?

**Comment by Eutaxy1** [comment]
> I would assume the world is not the issue here. Can a player chat? Can you try with no other plugins other than Geyser and Floodgate?

Yup, they can chat and fight each other no problem, but random blocks give them trouble. Some work, some don't. I'll have to get back to you on that second question as there are people playing at the moment.

**Comment by Eutaxy1** [comment]
It was the spawn protection of all things. Kind of disappointed in myself for not realizing sooner. Issue resolved.
