### ISSUE TITLE
Incorrect Item Names for Dyes

### ISSUE THREAD

**Issue by Firetop** [GeyserMC/Geyser#2993]
### Describe the bug

Playing on an Xbox (Bedrock) and a survival Java Geyser Server, Dyes (Such as white dye, or black dye) are incorrectly named in the crafting menu and your inventory.

### To Reproduce

Connect to a Java Server using an Xbox One (Bedrock)
Attempt to craft white dye using bone meal using the crafting menu.
The white dye will be called "Bone Meal" instead of "White Dye"

### Expected behaviour

For the item to have the correct name.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/1971404/170728106-15d85e47-f67a-445c-8dd9-2a4f0b452989.png)
![image](https://user-images.githubusercontent.com/1971404/170728124-f3e1683b-3747-4568-b2f3-128b5be76bd8.png)

### Geyser Dump

https://dump.geysermc.org/APiNHWAGMDIkmgjV8pkLCQH96DGD0UpO

### Geyser Version

Geyser version 2.0.3-SNAPSHOT (git-master-d74b0e2)

### Minecraft: Bedrock Edition Device/Version

1.18.31, Xbox One X

### Additional Context

paper-1.18.2-350.jar

**Comment by LimeDev8756** [comment]
With the way I **think** know how Geyser works, that is a bedrock thing (i **think**)

**Comment by Firetop** [comment]
> With the way I **think** know how Geyser works, that is a bedrock thing (i **think**)

I am confused, do you mean that this is a bedrock bug? 
Because on bedrock single player, the item names do show up as "White Dye" etc.

I figured it was an error in how it was translating the crafting of the item through Geyser, keeping the original item name/ID without translating it to use the Bedrock item name/ID, but I am very new to Geyser and so I am hoping for someone with more experience and background to fill me in and explain, even if this is by design. :)

Merci/Thank you.

**Comment by Camotoy** [comment]
I can't reproduce this, but I am on the 1.19 beta, so it may be patched for 1.19. I'll check back here after that update.

**Comment by Camotoy** [comment]
Both, for my work on getting ready for the update on June 7th.

**Comment by Firetop** [comment]
> Both, for my work on getting ready for the update on June 7th.

Well then; I updated my server yesterday and did a variety of testing throughout the day.
One of which was recreating this bug report on 1.19 and as you mentioned I am unable to recreate it in 1.19.

Not sure why 1.19 is fixed, I never got an explanation as to what was happening but either way it doesn't really matter the bug can be closed :)

Thanks for everyones pointers! Just a matter of waiting in this case :)
