### ISSUE TITLE
Close chat when running a command that shows Bedrock Menu

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#2994]
### What feature do you want to see added?

Currently, any command that brings up a chest inventory when executed closes the chat when the command is run and brings up the inventory.

For plugins that make use of Bedrock menus in commands, it would be nice if the same behavior was present.

Bedrock player runs command that brings up Bedrock UI Menu **-->** chat is closed by Geyser **-->** Bedrock UI is shown to player

### Are there any alternatives?

At the moment, the "main" solution is adding a player to a waiting list, telling the player to close the chat and move, when the move event is triggered and they're on that list, show them the menu they're expecting.

**Comment by Camotoy** [comment]
I am not aware of any way we can force Bedrock to close chat.

**Comment by pinkpig58** [comment]
Oh? I thought Geyser closed the chat when bringing up a chest inventory from a command, but perhaps that's client-side.
Not to worry. If it's not possible at the moment, by all means, close this request. :)
