### ISSUE TITLE
Dolphins Grace Not working for bedrock

### ISSUE THREAD

**Issue by TheElectronic317** [GeyserMC/Geyser#2995]
### Describe the bug

When I attempt to give my bedrock friend Dolphins Grace Via commands it doesn't work. It also doesn't work when he swims next to a dolphin

### To Reproduce

/effect give (Player) dolphins_grace 999999 0

### Expected behaviour

I expected him to get dolphins grace and he did not

### Server Version and Plugins

This server is running Paper version git-Paper-350 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 3f7fbe3)
You are running the latest version
Previous version: git-Paper-349 (MC: 1.18.2)

### Geyser Dump

https://dump.geysermc.org/YBF7zGKB4OJxbwb52PhjQfeHydysZblV

### Geyser Version

2.0.3

### Minecraft: Bedrock Edition Device/Version

Nintendo Switch

**Comment by Chew** [comment]
According to the wiki:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/8278263/170807672-cf3c689f-1085-467f-bf27-5b6c81378f62.png">

**Comment by Camotoy** [comment]
Reopening since the report is about the mechanics also not working.

**Comment by hausemaster3734** [comment]
Dolphins grace is working, but on Bedrock it's much bit slower.

**Comment by onebeastchris** [comment]
Closing - dolphins grace works, but bedrock has no visible effect for it.

**Comment by EnderSpider** [comment]
pretty sure bedrock edition just isnt able to use dolphins grace with commands
