### ISSUE TITLE
Server lag on Bedrock

### ISSUE THREAD

**Issue by JJGithuber** [GeyserMC/Geyser#2996]
### Describe the bug

A few months ago I decided to create a Minecraft Server with GeyserMC. It has been going very well until a few days ago, the world started to glitch on Bedrock and now there are a bunch of tik delays when playing. It sometimes takes a few seconds for the game to catch up. Mobs freeze for a few seconds, then appear and kill me, when endearing portals it takes a while to load and when it does it teleports me back to the portal repeatedly and many other delay problems occur that make the game annoying on bedrock. There is also the issue of crossbow animations not showing, but that could be a separate issue. As I said, this happened out of nowhere and the game was fine before. I'm not sure if this is actually a bug or not, but How do I fix this? I don't know much about Java or running servers. 

### To Reproduce

Play around on bedrock and see how the game is delayed and laggy.

### Expected behaviour

The game should run smoothly on both versions.

### Screenshots / Videos

[https://www.youtube.com/watch?v=jUfbOv5xiTs&feature=youtu.be](https://www.youtube.com/watch?v=jUfbOv5xiTs&feature=youtu.be)
[https://www.youtube.com/watch?v=_h0YAQA1oMo&feature=youtu.be](https://www.youtube.com/watch?v=_h0YAQA1oMo&feature=youtu.be)

As you can see, there are delays with mobs attacking and skeleton bows, the world runs a bit slow, opening chests are delayed, and piglin crossbows don't show being loaded. Although not shown here, other times the portal would take a while to load and would teleport me back as I said before.

### Server Version and Plugins

Train-Carts, BStats, luckPerms, BkCommonLib. This server runs on 1.18.2

### Geyser Dump

[https://dump.geysermc.org/5wocM5b0Bia9Zahj0zz3ErlaKHBvjTm0](https://dump.geysermc.org/5wocM5b0Bia9Zahj0zz3ErlaKHBvjTm0)

### Geyser Version

2.0.3

### Minecraft: Bedrock Edition Device/Version

Windows 10

**Comment by jackson-57** [comment]
Dump link for easier viewing: https://dump.geysermc.org/5wocM5b0Bia9Zahj0zz3ErlaKHBvjTm0

**Comment by Jens-Co** [comment]
Please update the YouTube links as they are currently non functional.

For crossbow issue please see #2747.

**Comment by JJGithuber** [comment]
@Jens-Co I'll fix the links, but the issue described with the bow is different, #2747 says that they don't change after being shot, my issue is the bow won't change while loading and being shot, it just stays in it's default state.

**Comment by JJGithuber** [comment]
@Jens-Co I tried fixing them, but it won't work. You can try telling me but if not, just copy and paste it into the search bar manually.

**Comment by JJGithuber** [comment]
Hello? is anyone there

**Comment by JJGithuber** [comment]
I fixed the youtube links

**Comment by onebeastchris** [comment]
Does this issue still occur with the latest version of Geyser? If it does, please send a new Geyser dump.

**Comment by onebeastchris** [comment]
my bad, closed too soon

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
