### ISSUE TITLE
Players that enter a boat on a slime block fly up 25 blocks

### ISSUE THREAD

**Issue by Budderman18** [GeyserMC/Geyser#2997]
### Describe the bug

Whenever a player enters a stationary boat on top of a slime block, they and the boat get shot upwards around 25 blocks. Not too much of a game-breaking issue but will cause issues with anticheats.

### To Reproduce

1. Place a boat on top of a slime block
2. Enter the boat, if you don’t shoot up, leave the boat and enter again

### Expected behaviour

Boat stays on the ground.

### Screenshots / Videos

https://user-images.githubusercontent.com/65318126/170838860-0b28b61f-a5aa-4157-a119-d0ce6a928229.MOV

### Server Version and Plugins

This server is running Pufferfish version git-Pufferfish-68 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 629b5b3 on HEAD)

Plugins (77): AdvancedReplay\*, ajLeaderboards, ajParkour, AntiCheatReplay, AutoKiller\*, BadlionClientModAPI, BedrockPlayerManager, BedWars, BentoBox, betterbroadcaster, BuycraftX, Citizens, ClearLag, CommandHook, CommandSigns, ConsoleSpamFix, CrazyAuctions, Curses, Duels, Essentials, Essentials\_WarpGUI, EssentialsChat, EssentialsDiscord, EssentialsGeoIP, EssentialsSpawn, F3NPerm, Factions, floodgate, Geyser-Spigot, gProtector, GriefPrevention, GroupManager, HoloExtension, HolographicDisplays, HungerGames, Images, IngotWarn\*, JukeBox, KillerMoney\*, LastLoginAPI, LibsDisguises, Lobbys\*, LunarClient-API\*, LunarClient-Impl\*, Maintenance, MobArena, Morphy, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, MultiWorldMoney\*, NoteBlockAPI, Parties, PlaceholderAPI, PlotSquared, PlugReloader\*, Prison, ProtocolLib, RandomTeleport, SignShop, SilkSpawners, SkyblockOres, SpigotPing, StaffChat, StartupCommands\*, Themis, TimeManager, TitleManager, TooExpensiveFix, TowerDefense, UltraCosmetics, Vault, Votifier, VotingPlugin, WorldEdit, XPDeathDropFix

### Geyser Dump

https://dump.geysermc.org/IQoaWOD3IHADQNBqG7Vvpl680vp40kPj

### Geyser Version

This server is running Geyser version 2.0.3-SNAPSHOT (git-master-d74b0e2) (Java: 1.18.2, Bedrock: 1.18.0/1.18.1/1.18.2 - 1.18.30/1.18.31)

### Minecraft: Bedrock Edition Device/Version

IPhone XR 1.18.31

**Comment by hausemaster3734** [comment]
This is a Vanilla behaviour.

**Comment by LimeDev8756** [comment]
Then wouldn't the anti-cheat not flag that because it would know that is normal behaviour?

**Comment by Konicai** [comment]
Vanilla Bedrock Edition behaviour, but not vanilla Java Edition behaviour.

**Comment by MWHunter** [comment]
If this was a java client, I would fix this bug server-sided by sending the velocity of the vehicle just before they enter it.

**Comment by onebeastchris** [comment]
This doesnt appear to be an issue anymore :)
