### ISSUE TITLE
Bedrock Edition players cannot load into the server properly

### ISSUE THREAD

**Issue by Mikeyreza** [GeyserMC/Geyser#2998]
### Describe the bug

When people log into the server from a Bedrock version of the game (more specifically, PS4, Windows 10, or Mobile), they are only able to load in a chunk or two, or, sometimes, no chunks at all. Their messages cannot be seen by themselves (although other players can see them), and they cannot see the messages of other players. Most of the time, they can't see other players at all, other than fellow bedrock players (the same thing basically happens when you look at the server on your server list). This bug started happening out of no where, as the first time I tried logging onto the server with a bedrock client, everything worked smoothly.

### To Reproduce

1. Have your geyser plugin installed by Apex Hosting (this was done through a support ticket; their automatic installer has been taken down for repair)
2.  Have a player on PS4, Windows 10, or Mobile attempt to log onto the server approximately one day after geyser installation

### Expected behaviour

I expect for bedrock players to be able to play with the ability to see and send messages in the chat as well as load chunks properly.

### Screenshots / Videos

![bedrock3](https://user-images.githubusercontent.com/48873254/170893669-20b0c8b2-86cd-49cb-92ee-c87f2a1cdd34.PNG)
![bedrock2](https://user-images.githubusercontent.com/48873254/170893672-6fe6bb82-fea6-4b7d-83a2-afc3643700b6.PNG)
![bedrock1](https://user-images.githubusercontent.com/48873254/170893673-c846ec1f-ee9b-402d-a517-c5b582cf2a42.PNG)

### Geyser Dump

https://dump.geysermc.org/No45juZPXi2TyIIOARbyhV9abJG9c6ZA

### Geyser Version

1.18.2

### Minecraft: Bedrock Edition Device/Version

1.18.31 Windows 10, Pocket Edition, PS4

**Comment by Camotoy** [comment]
Are you using a 10th generation or newer Intel processor on the server running Geyser? If so, see #2861.

**Comment by Mikeyreza** [comment]
No, according to Apex Hosting, the server hardware specifications for the Los Angeles region are: 

Ryzen 7 5800X 4.7GHz 8c/16t | NVME RAID1 | 128GB ECC DDR4 3200 MT/s
2x Xeon Gold 6348 3.50GHz 28c/56t | NVME RAID1 | 1024GB ECC DDR4 3200 MT/s

**Comment by Mikeyreza** [comment]
Can someone please help me? I don't know if me saying this will bump the post or whatever but I just need some help. I cannot find any solutions or even other instances of this issue occurring. Should I make a support ticket with Apex Hosting? They are the ones who set up the geyser.

**Comment by Camotoy** [comment]
Can you update to the latest version and post a new Geyser dump?

**Comment by ProPane865** [comment]
The Intel Xeon Gold 6348 is an Ice Lake (10th gen) based CPU and seems to be affected by the bug described in #2861.

**Comment by Camotoy** [comment]
Thanks for pointing that out - I only saw the AMD processor when I first looked at the message.

**Comment by Mikeyreza** [comment]
I also only saw the AMD processor, lol. Thank you for the help both of you. I will contact Apex Hosting for them to put what you guys said in the start up arguments.

**Comment by pcboii** [comment]
@Mikeyreza From what I was told by Apex Hosting is they currently do not support JVM arguments, so you will need to put in a support ticket to have them transfer your server to a different non-intel node.

**Comment by Mikeyreza** [comment]
I'll try that, thank you pcboii

**Comment by Jens-Co** [comment]
Any info on this issue?

**Comment by Jens-Co** [comment]
Closing this issue since no response was given. Feel free to bump this and I'll reopen!
