### ISSUE TITLE
What should i try to help with?

### ISSUE THREAD

**Issue by 4xk** [GeyserMC/Geyser#3]
Im very interested in where this server goes, and I would like to help it :)
What should i start working on now?

**Comment by RednedEpic** [comment]
> Im very interested in where this server goes, and I would like to help it :)
> What should i start working on now?

Geyser is not a server software actually. It's a proxy that allows you to join any Minecraft: Java Edition server with Minecraft: Bedrock Edition. We just wrapped up the text/command translations and will most likely be moving to authentication next.

Please join our Discord server for more information: https://discord.gg/mRjbCsS. I'll be able to help you there more easily.

**Comment by RednedEpic** [comment]
Closing as this is less of an issue and more of a question on how to contribute. Please read the comment above.
