### ISSUE TITLE
Missing Block Mappings

### ISSUE THREAD

**Issue by RednedEpic** [GeyserMC/Geyser#30]
This is just a list of missing block mappings that don't properly translate to bedrock.

**Fixed Mappings**
- [ ] Leaves
- [ ] Flowers
- [ ] Heads
- [ ] Cracked Stone Bricks
- [ ] Certain Log Directions (unconfirmed)
- [ ] Certain Stair Directions (unconfirmed)
- [ ] Block Entities (Chest, Furnace, Flower Pot, Skull, etc.)

**Comment by RednedEpic** [comment]
Resolved.

**Comment by WesleyVanNeck** [comment]
still a lot of missing stuff @RednedEpic
