### ISSUE TITLE
Getting kicked from servers after 30 seconds of inactivity

### ISSUE THREAD

**Issue by rineq** [GeyserMC/Geyser#3000]
### Describe the bug

When I stand still and don't move for exactly 30 seconds I get kicked from servers using the plugin for the reason "Disconnected from server". This started happening about 9 hours ago since a recent proxy update I believe. On the server I play on I asked in the main chat if any other bedrock players were experiencing this issue and they said yes.

### To Reproduce

Just stand still for about 30 seconds.

### Expected behaviour

Get kicked from the server for the reason "Disconnected from server"

### Screenshots / Videos

https://www.youtube.com/watch?v=uwuhwk77kFw

### Server Version and Plugins

Unsure

### Geyser Version

Unsure

### Minecraft: Bedrock Edition Device/Version

Windows 10 Edition

**Comment by Jens-Co** [comment]
I'll close this issue due to lack of information, if you are still having this issue please update this one with the asked information and I'll reopen this issue
