### ISSUE TITLE
Invisible Signs

### ISSUE THREAD

**Issue by RedestoneCrafter** [GeyserMC/Geyser#3004]
### Describe the bug

If you are on a Java Server with Bedrock Edition the signs are invisible.

### To Reproduce

1. Join
2. Go to position where signs are
3. You can't see the signs (but can click)

### Expected behaviour

You can't see the most signs of a server with bedrock edition. But you can click on the signs.

### Screenshots / Videos

![Screenshot_20220602-091527_Minecraft](https://user-images.githubusercontent.com/68423954/171574578-cc03ed4f-3cc8-40f9-b144-13676295087a.png)
Java Edition on ask

### Server Version and Plugins

![Screenshot_20220602-090525_Minecraft](https://user-images.githubusercontent.com/68423954/171573429-c4c705bd-07e3-4921-877c-55ced4ba5695.png)

### Geyser Dump

 https://dump.geysermc.org/njBQxzK9SKifnCxW8qngDfMRcogAhbAZ

### Geyser Version

2.0.3-SNAPSHOT (git-master-d74b0e2)

### Minecraft: Bedrock Edition Device/Version

1.18.32, Mobile

**Comment by onebeastchris** [comment]
Does this issue still occur on the latest version of Geyser & latest bedrock client?

**Comment by onebeastchris** [comment]
Closing due to no response.
