### ISSUE TITLE
Minecraft overworld has nether fog and sky

### ISSUE THREAD

**Issue by username100099** [GeyserMC/Geyser#3005]
### Describe the bug

When going to the overworld it has a nether sky, atmosphere and fog just like you would if you were in the nether

### To Reproduce

Note: The bug is a little hard to reproduce but will make bedrock edition impossible to play on and will happen unexpectedly even without following the steps however when it happens it happens to all bedrock players and even after restarts and reinstalling geyser it doesn't change anything.

1. go to nether
2. leave the game and come back while standing next to a nether portal
3. go through the portal 

### Expected behaviour

When leaving the nether portal the fog and nether environment shouldn't be there.

### Screenshots / Videos

![IMG_5914](https://user-images.githubusercontent.com/87804903/171670699-67ba994f-169d-4d11-9118-7fc17baec44c.png)

### Server Version and Plugins

/version command : 
[15:53:37 INFO]: Checking version, please wait...
[15:53:38 INFO]: This server is running Paper version git-Paper-347 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 79e07f3)
You are 19 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Purpur-1625 (MC: 1.18.2)

plugins:
 BlueMap, ChestShop, CoreProtect, floodgate, Geyser-Spigot, LiveKit, SeePlayerInventory, SkinsRestorer, TabTPS, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/H43cJhG6gsWqiPyxKBipkLiluYQSpq1k

### Geyser Version

version 2.0.3-SNAPSHOT (git-master-5a94bda)

### Minecraft: Bedrock Edition Device/Version

1.18.32 (latest)

**Comment by Camotoy** [comment]
If `above-bedrock-nether-building` is disabled this is weird. Do you have a world border enabled?

**Comment by username100099** [comment]
Yes

**Comment by username100099** [comment]
> If `above-bedrock-nether-building` is disabled this is weird. Do you have a world border enabled?

The world border is 5000 blocks big

**Comment by Camotoy** [comment]
That fog effect is supposed to show up if you're within the warning boundaries of the border.

**Comment by username100099** [comment]
i set the warning to 4800

**Comment by Camotoy** [comment]
Java's effect may increase as you get closer to the border. But I suspect this is the issue if you're withing 4800 blocks of the world border - I'd suggest to lower that number. We can't increase or decrease the fog level unfortunately.

**Comment by username100099** [comment]
> Java's effect may increase as you get closer to the border. But I suspect this is the issue if you're withing 4800 blocks of the world border - I'd suggest to lower that number. We can't increase or decrease the fog level unfortunately.

im actually at spawn which is at 0,0

**Comment by Yomamaeatstoes** [comment]
The bug is from core protect. Delete that plugin!!!

**Comment by Yomamaeatstoes** [comment]
The red fog is from core protect

**Comment by onebeastchris** [comment]
Closed as this appears to have been a plugin conflict

**Comment by TheAlmightyJeff** [comment]
I have a geyser server on exaroton and when using the /execute in command to teleport into a different dimension, this bug happens.
I do not have core protect, however I am teleporting a bedrock player from a custom dimension, into the overworld.
