### ISSUE TITLE
Lily Pad Placement issue

### ISSUE THREAD

**Issue by DuneSciFye** [GeyserMC/Geyser#3006]
### Describe the bug

Upon placing lily pads, sometimes it glitches and disappears from your inventory. When updating your inventory like opening a chest, the lily pad re-appears in the slot.

### To Reproduce

1. Have a pool of water and some lily pads in your inventory
2. Place lily pads down in the water

### Expected behaviour

Upon placing down the lily pad, it shouldn't disappear, but rather be placed.

### Screenshots / Videos

https://streamable.com/wexuy6

### Server Version and Plugins

Server version: Purpur-1609 (MC: 1.18.2)*
Plugins: Plugins (70): AdvancedEnchantments, AnotherDailyBonus, AntiBookBan, AntiDrop, AuctionHouse, AureliumSkills, AutoPickup, BambooCollisionFix, BuycraftX, ChatManager, ChestProtect, Citizens, CommandPrompter, CommandWhitelist, CoreProtect, CustomCrafting, CyberLevels, CyberStatistics, DecentHolograms, DeluxeMenus, DeluxeShop, DeluxeTags, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, ExecutableItems, floodgate, GadgetsMenu, GamePoints, GSit, JetsHoppers, JetsMinions, JSEngine, LibsDisguises, LuckPerms, Multiverse-Core, Multiverse-Inventories, MyCommand, NexEngine, OpenInv, PlaceholderAPI, PlayerPoints, Playtime, PluginManager, ProtocolLib, PyroFishingPro, PyroLib, Quests, SCore, SoaromaSAC, spark, StaffTools*, SuperiorSkyblock2, TAB, TradeSystem, UpgradeableSpawners, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WildChests, WildStacker, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

https://dump.geysermc.org/wIrCfwZjvT3y2rWa5QBR8TN4cpy4Lf10

### Geyser Version

I'm not sure, its on the velocity server and I'm not sure how to check.

### Minecraft: Bedrock Edition Device/Version

1.18.2, tested on Windows 10 Edition

**Comment by DuneSciFye** [comment]
#2012 also has a similar issue

**Comment by jecowa** [comment]
Tested in Geyser build #1111 for Spigot with Android 1.19 player. All lilly pads go back into my inventory when I try to place them. Java player can place lilly pads just fine.
