### ISSUE TITLE
Server lag on Bedrock (Reposted)

### ISSUE THREAD

**Issue by JJGithuber** [GeyserMC/Geyser#3007]
### Describe the bug

A few months ago I decided to create a Minecraft Server with GeyserMC. It has been going very well until a few days ago, the world started to glitch on Bedrock and now there are a bunch of tik delays when playing. It sometimes takes a few seconds for the game to catch up. Mobs freeze for a few seconds, then appear and kill me, when endearing portals it takes a while to load and when it does it teleports me back to the portal repeatedly and many other delay problems occur that make the game annoying on bedrock. There is also the issue of crossbow animations not showing, but that could be a separate issue. As I said, this happened out of nowhere and the game was fine before. I'm not sure if this is actually a bug or not, but How do I fix this? I don't know much about Java or running servers.

### To Reproduce

Play around on bedrock and see how the game is delayed and laggy.

### Expected behaviour

The game should run smoothly on both versions.

### Screenshots / Videos

[https://youtu.be/jUfbOv5xiTs](url)
[https://youtu.be/_h0YAQA1oMo](url)

### Server Version and Plugins

Train-Carts, BStats, luckPerms, BkCommonLib. This server runs on 1.18.2

### Geyser Dump

https://dump.geysermc.org/5wocM5b0Bia9Zahj0zz3ErlaKHBvjTm0

### Geyser Version

2.0.3

### Minecraft: Bedrock Edition Device/Version

Windows 10

### Additional Context

This is a repost since no one responded to my last one.

**Comment by Camotoy** [comment]
Please do not repost open issues. Thanks!

**Comment by MrZomka** [comment]
Why are using Linux 3.x? It's really old and EOL.

**Comment by JJGithuber** [comment]
@Camotoy ok here's the link if you need it [](https://github.com/GeyserMC/Geyser/issues/2996)
