### ISSUE TITLE
TerraformGenerator custom colors don't show on bedrock

### ISSUE THREAD

**Issue by JohnnyX071** [GeyserMC/Geyser#3009]
### Describe the bug

TerraformGenerator is a custom world generator plugin which includes custom colors. i contacted the developer and they told me to open a bug report because the colors don't show on bedrock

### To Reproduce

1. Make a server with geyser and terraformgenrator
2. Go to a biome that has custom colors

### Expected behaviour

The custom biome colors should show as they do in java

### Screenshots / Videos

![unknown](https://user-images.githubusercontent.com/63922728/172041871-87201d96-a091-41b6-af1d-2c44e0856c33.png)
![unknown (3)](https://user-images.githubusercontent.com/63922728/172041874-a40eccdb-96b7-4659-9a9b-2325cad6eae2.png)

### Server Version and Plugins

This server is running Paper version git-Paper-373 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 071a4a2)

### Geyser Dump

https://dump.geysermc.org/xTjY1yhRtC7ac0Y5KHJK5pySlrVHqfGp

### Geyser Version

Geyser version 2.0.3-SNAPSHOT (git-master-c83eb7f)

### Minecraft: Bedrock Edition Device/Version

1.18.31 Windows 10 edition

**Comment by Jens-Co** [comment]
Hello there!

Custom blocks/biomes are not(yet) possible on Geyser. This is something we eventually will add but is currently on low priority. For now I will close this issue since we already have an open one see #1752

thanks for reporting!
