### ISSUE TITLE
Multiverse not working on bedrock

### ISSUE THREAD

**Issue by kaiezzz** [GeyserMC/Geyser#3010]
### Describe the bug

Hello there! I am planning to open a Minecraft server that has a whole lot of plugins including Multiverse. I tested it on my phone and it says "Unable to Connect to World" even my friend tested it and got the same result. I tried uninstalling the Multiverse plugin and it worked. What is the problem here? Is it on Geyser or on the Multiverse?. I'm using aternos to host the server.

### To Reproduce

https://mclo.gs/B8htXOB

### Expected behaviour

Doesnt work when multiverse installed for bedrock edition. I need multiverse for this project

### Server Version and Plugins

Geyser-Spigot 1105
EssentialsX (GeoIP, Chat, Spawn, Protect and the Core)
Grief Prevention
Vault
Multiverse (Core, Portals, Inventories)
LuckPerms
Chestshop
EconomyShopGUI

### Geyser Version

1105

### Minecraft: Bedrock Edition Device/Version

1.18.0 Pocket Edition

**Comment by Camotoy** [comment]
I just tried with that build and was able to connect with Multiverse installed. There's likely something else going on.

**Comment by kaiezzz** [comment]
> 

i also forgot i used paper to run the server. what software did you use?

**Comment by byquanton** [comment]
Check if you configured Geyser correctly and use the right port to connect.
https://support.aternos.org/hc/en-us/articles/360051047631

**Comment by Jens-Co** [comment]
Since Camotoy tested this and issue being 2 months old I'll close this one. If you are still having this issue feel free to bump this and I'll reopen.
