### ISSUE TITLE
Action Bar in Chat 1.19 (Bedrock)

### ISSUE THREAD

**Issue by proferabg** [GeyserMC/Geyser#3012]
### Describe the bug

With the 1.19 update, Action Bar messages send to normal chat instead of to action bar.

### To Reproduce

1. Send action bar to client
2. See it in chat

### Expected behaviour

1. Send action bar to client
2. See it above hotbar/health

### Screenshots / Videos

![Java](https://i.imgur.com/iykB7a6.png)
![Bedrock](https://i.imgur.com/sF2cNA3.png)

### Server Version and Plugins

Waterfall #488
Paper #379
Geyser Build #1106

### Geyser Dump

https://dump.geysermc.org/QvUO7jCq0n7zIsSjVXTEXsbk9HHCunQL

### Geyser Version

Build #1106

### Minecraft: Bedrock Edition Device/Version

Minecraft Bedrock 1.19 (Microsoft Store on PC)

**Comment by pinkpig58** [comment]
I can confirm this issue when using BungeeCord and Spigot as well.

**Comment by JohnnyX071** [comment]
Yes, I can also confirm that. I am using BungeeCord and Paper

**Comment by Tim203** [comment]
I was unable to replicate this on Hypixel

**Comment by proferabg** [comment]
> I was unable to replicate this on Hypixel

Does Hypixel support bedrock clients?

**Comment by Tim203** [comment]
No, but I'm using Geyser standalone to connect to it.

**Comment by proferabg** [comment]
Ok. Are you able to replicate it using a bedrock client connecting to a Geyser-Bungee server? Hypixel doesn't use Geyser so standalone may differ...?

**Comment by Camotoy** [comment]
Geyser-BungeeCord doesn't differ in this manner over standalone. What plugin or datapack are you using for the action bar message?

**Comment by pinkpig58** [comment]
Contributing here, rather than creating a duplicate issue.

Plugins I'm using use (1.12 Spigot):
`e.getPlayer().spigot().sendMessage(ChatMessageType.ACTION_BAR, new ComponentBuilder("action bar text").create());`

**Comment by proferabg** [comment]
I do believe it is not an issue with Geyser. Sorry for the run around. It seems that something in the action bar has changed and it may be a packet issue possibly with ViaVersion and/or changed packets. Still looking into this issue.

**Comment by proferabg** [comment]
This is an issue with ViaVersion. Closing this issue.
