### ISSUE TITLE
Sending chat messages result in being disconnected

### ISSUE THREAD

**Issue by spookymgmt** [GeyserMC/Geyser#3015]
### Describe the bug

Upon sending a chat message on the latest bedrock windows 10 client, on a server using 1.18.2 puffer fish, latest velocity dev build, latest geyser dev build, you'll be disconnected for "An internal error occurred in your connection.".

### To Reproduce

Latest all files, send a chat message in server.

### Expected behaviour

Send chat messages normally.

### Server Version and Plugins

![image](https://user-images.githubusercontent.com/78775526/172527844-2030e8a0-269b-4ea9-bbaf-289410eed1e9.png)

Velocity 3.1.2-143.jar

Geyser

### Geyser Dump

https://dump.geysermc.org/t2NSUjFHI8bNSfNQushaSzHXtqALsrar

### Geyser Version

Geyser version 2.0.4-SNAPSHOT (git-master-78bb69b)

### Minecraft: Bedrock Edition Device/Version

1.19 Windows 10

### Additional Context

https://paste.gg/cb3ad1fc69814c7eb36f773730920079

**Comment by RednedEpic** [comment]
Fixed in latest velocity build.
