### ISSUE TITLE
Blocks are not translated correctly in the stonecutter gui

### ISSUE THREAD

**Issue by PureGero** [GeyserMC/Geyser#3017]
### Describe the bug

When using a stonecutter in Bedrock edition, random end stone bricks appear in the stonecutter's recipe menu where there should be other blocks.

### To Reproduce

1. Log into your server using both Java and Bedrock edition
2. Place down a stonecutter
3. Put some diorite in your inventory
4. Right-click the stonecutter and place the diorite into the left item slot on the gui
5. Observe that in the recipe menu on the left, only diorite-related blocks are shown on Java Edtion, but some of the diorite-related slabs are replaced with end stone bricks on Bedrock Edition

### Expected behaviour

Only diorite-related blocks should be shown in the stonecutter's recipe menu. There should be no end stone bricks.

### Excpected result: Java 1.19
<img width="369" alt="Screen Shot 2022-06-08 at 15 48 36" src="https://user-images.githubusercontent.com/8893026/172541506-c2094426-c9a7-4e01-8ff3-eae3fee862f7.png">

### Incorrect result: Bedrock 1.19.0
<img width="1360" alt="Screen Shot 2022-06-08 at 15 49 47" src="https://user-images.githubusercontent.com/8893026/172541546-f5136e9c-871d-48d1-bdb6-722d8cadc943.png">

### Server Version and Plugins

Vanilla 1.19 Java edition server

### Geyser Dump

https://dump.geysermc.org/iVKNAWUZKPUOGVSCGKTptNoZSYtehkk5

### Geyser Version

2.0.4-SNAPSHOT (git-master-78bb69b)

### Minecraft: Bedrock Edition Device/Version

Occurs on at least Windows 1.19.0, iOS 1.19.0, but potentially more devices

**Comment by Camotoy** [comment]
This might actually be a slab mapping issue. I've heard the name changed so we might need to too. Similar Reddit link?: https://reddit.com/r/GeyserMC/comments/v7floh/slabs_are_not_working_properly_on_bedrock_linked/

**Comment by SavageCabbage64** [comment]
I am having the same issue, making slabs on bedrock creates weird blocks that you cannot use to craft anything with

**Comment by Camotoy** [comment]
This should now be fixed. Let us know otherwise!
