### ISSUE TITLE
Invalid IPv6 address

### ISSUE THREAD

**Issue by CHaenf** [GeyserMC/Geyser#3021]
### Describe the bug

When I connect to an IP like 111.111.111.111:11111 it gives an invalid ipv6 address error. As far as I know, this server uses ipv4

### To Reproduce

1.enter ip like 111.111.111.111:11111 in config 2.start geyser 3. connect to it

### Expected behaviour

connection without error

### Screenshots / Videos

![redrfe](https://user-images.githubusercontent.com/107129902/172648824-3b184b79-5a08-4eff-83e3-39042c7a63f0.png)

### Geyser Version

2.0.3 snapshot

### Minecraft: Bedrock Edition Device/Version

1.18.31 xiaomi redmi note 7

**Comment by Camotoy** [comment]
You need to put the port under `remote` `port`. Don't add it to `remote` `address`. 

Hopefully that should solve your issue!
