### ISSUE TITLE
Players sometime carnt connect when using a VPN

### ISSUE THREAD

**Issue by Josh65-2201** [GeyserMC/Geyser#3022]
### Describe the bug

When a player with a VPN (surfshark is the only one ive tried) is trying to connect they get a "unable to connect to world" and on the console side it says "<IP> tired to connect" about 8 times

### To Reproduce

1. Create server (Paper 1.18.1)
2. Connect cleint to VPN
3. Attempt to connect ot server (Some time it works, not sure why)

### Expected behaviour

User should be adble to connect

### Server Version and Plugins

 Paper version git-Paper-216 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 30cb7d0)

AntiCheatReloaded, Chunky, CleanroomGenerator, dynmap, Dynmap-Essentials*, Essentials, EssentialsChat, floodgate, Geyser-Spigot, GeyserUpdater, GUIPlus, HolographicDisplays, HolographicScoreboard*, ImprovedFactions, LuckPerms, MCSF, MobArena, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, OpenInv, ProtocolLib, ServerBackup, Vault, ViaVersion, Vivecraft-Spigot-Extensions, WorldEdit, WorldGuard, XPEconomy*

### Geyser Dump

https://dump.geysermc.org/fvMYUVVKF5ihvddnXMlwKciwMnVPSE23

### Geyser Version

Geyser version 2.0.4-SNAPSHOT (git-master-78bb69b) (Java: 1.19, Bedrock: 1.19.0)

### Minecraft: Bedrock Edition Device/Version

1.19.0, Android

**Comment by onebeastchris** [comment]
VPNs can increase latency by a lot, and your server hosting provider might block VPNs. Therefore, this is unlikely to be a Geyser issue.
