### ISSUE TITLE
Slabs dissapear when taking from creative inventory

### ISSUE THREAD

**Issue by kabluinc** [GeyserMC/Geyser#3026]
### Describe the bug

When taking slabs from creative inventory, they dissapear. This only happens from bedrock 1.19, does not happen from java client.

### To Reproduce

Go to creative mode
Take slabs

### Expected behaviour

Slabs appear in inventory

### Server Version and Plugins

Paper 1.18.2 (#379 [276d830](https://github.com/PaperMC/Paper/commit/276d830d223ddf68611beacc248285ae5a4e8a1f)
Geyser-Bungeecord (#1108 git-master-78bb69b)
ViaVersion 4.3.2
Bedrock client 1.19

### Geyser Version

2.0.4-SNAPSHOT (git-master-78bb69b) (Java: 1.19, Bedrock: 1.19.0)

### Minecraft: Bedrock Edition Device/Version

1.19

**Comment by Folas1337** [comment]
One of my users has made a video that I'm willing to share:
https://cdn.discordapp.com/attachments/666734293183365130/984342731675537468/Record_2022-06-09-14-12-45.mp4

Having the same issue, would love this to get fixed :)

**Comment by Camotoy** [comment]
This is likely fixed now in the newest Geyser build. Let us know otherwise. Thanks!
