### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by tecMT** [GeyserMC/Geyser#3027]
### Describe the bug

every time a user tries to sign in it gives this error: (has disconnected from the Java server because of Connection closed.)

### To Reproduce

See error

### Expected behaviour

normal login

### Screenshots / Videos

https://prnt.sc/4aEgJJKc4oKj

### Server Version and Plugins

git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/MZ80O4Bpf0GU3IBiQw9q1fmFwbqNUsZb

### Geyser Version

Build #1108 (7 de jun de 2022 20:08:10)

### Minecraft: Bedrock Edition Device/Version

1.8.8

**Comment by Camotoy** [comment]
Please update BungeeCord and Floodgate. Thanks!
