### ISSUE TITLE
Connecting closed

### ISSUE THREAD

**Issue by RiMio827** [GeyserMC/Geyser#3029]
### Describe the bug

I can't log in to the server via bedrock, it gives connecting  closed

### To Reproduce

1. I log on to the server

### Expected behaviour

I was expecting to log in to the server

### Screenshots / Videos

![Screenshot_2022-06-09-11-18-36-500_com mojang minecraftpe](https://user-images.githubusercontent.com/107187290/172834338-3d3b76d0-6e29-4b0b-8f7e-aefaef7a205c.jpg)

### Geyser Version

2.0.4-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.0 bedrock edition

**Comment by Konicai** [comment]
There isn't enough information here to help you. This is likely due to a setup error or possibly your Geyser and Floodgate needing updating. Please join our Discord for help with this

**Comment by hausemaster3734** [comment]
update your BungeeCord.
