### ISSUE TITLE
Can't fish on bedrock edition

### ISSUE THREAD

**Issue by Zhwt** [GeyserMC/Geyser#303]
**Describe the bug**
Can't fishing on Bedrock Edition.

**To Reproduce**

1. Go to a place near a river.
2. Click on fishing rod.
3. Aim to the river.
4. Click the fishing button and nothing happens.

**Expected behavior**
Normal fishing behavior like in single player mode.

**Screenshots / Videos**
Maybe later.

**Server Version**
```
> version
[19:15:02 INFO]: This server is running Paper version git-Paper-161 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[19:15:02 INFO]: Checking version, please wait...
[19:15:06 INFO]: Previous version: git-Paper-155 (MC: 1.15.2)
[19:15:06 INFO]: You are 6 version(s) behind
```

**Geyser Version**
Using inventory branch #8 bukkit build.

**Minecraft: Bedrock Edition Version**
1.14.30.2 Android xbox version, not the original one.

**Additional Context**
The durability of fishing rod is dropping after I did some "fishing", but the bobber didn't come out.
Java Edition works fine.

**Comment by DoctorMacc** [comment]
Partially fixed with #353, presumably to the point where you *can* fish.
