### ISSUE TITLE
Books become andesite in the villager trade gui on Bedrock

### ISSUE THREAD

**Issue by PureGero** [GeyserMC/Geyser#3030]
### Describe the bug

Regular books in the villager's trading gui are shown as andesite in Bedrock. Note that regular books display correctly in the player's inventory.

Possibly related to #3017

### To Reproduce

1. Summon a villager
2. Place down a lectern
3. The villager is now a librarian. Check if the librarian's trades contain a trade that takes a regular book. If not, start again from step 1.
4. Observe in Bedrock that the regular book gets replaced with andesite

### Expected result: Java 1.19.0
<img width="570" alt="Screen Shot 2022-06-09 at 22 21 02" src="https://user-images.githubusercontent.com/8893026/172845757-a73d675f-0e3a-413e-a876-54992963de4c.png">

### Incorrect result: Bedrock 1.19.0
<img width="1305" alt="Screen Shot 2022-06-09 at 22 20 46" src="https://user-images.githubusercontent.com/8893026/172845842-ddda6ec9-2c64-430d-bd07-8744240f9fb9.png">

### Server Version and Plugins

Vanilla 1.19 Java edition server

### Geyser Dump

https://dump.geysermc.org/8lykKV5aJqRDtZKiXZEuW85UZFRs6adJ

### Geyser Version

2.0.4-SNAPSHOT (git-master-72a9df5)

### Minecraft: Bedrock Edition Device/Version

Occurs on at least Windows 1.19.0, iOS 1.19.0, but potentially more devices

**Comment by BbugsCO** [comment]
Happens for me too, at least it takes the book for the trade and not the block.

**Comment by Camotoy** [comment]
This is likely fixed now in the newest Geyser build. Let us know otherwise. Thanks!
