### ISSUE TITLE
The provided value for the 'code' parameter is not valid after logging in Minecraft Java account

### ISSUE THREAD

**Issue by RORY112345** [GeyserMC/Geyser#3031]
### Describe the bug

I'm trying to go in a server with GeyserMC (Java server, Joining with a Minecraft Bedrock) I can join at first, But after logging in my account It gave me the error "The provided value for the 'code' parameter is not valid.". Can anyone help to fix this, Please?

### To Reproduce

1. Go inside the GeyserMC Server
2. Log in with microsoft account
3. Error there.

### Expected behaviour

We can go in the server

### Server Version and Plugins

Spigot 1.19

### Geyser Dump

https://dump.geysermc.org/KgMk6vNhzvwPsY5kTdjlqbpWGfcbetma

### Geyser Version

2.0.4-SNAPSHOT (git-master-72a9df5) (Java: 1.19, Bedrock: 1.19.0)

### Minecraft: Bedrock Edition Device/Version

1.19.0, Bedrock Edition (Windows PC)

**Comment by RORY112345** [comment]
> Try logging in using the web browser and not your password?

I'll try that.

**Comment by Maxo6453** [comment]
I can confirm this issue exists in spigot 1.18

**Comment by RORY112345** [comment]
Using web browser to log in fixed it.

**Comment by nosferatie** [comment]
Is there any plans to fix the username/password way to login? Or is web browser the only option?

**Comment by TheMonBonGH** [comment]
> Is there any plans to fix the username/password way to login? Or is web browser the only option?

I would say no, because using the web browser is a more secure way to login.
