### ISSUE TITLE
Bedrock players will be kicked after a short time

### ISSUE THREAD

**Issue by Laro5444** [GeyserMC/Geyser#3032]
### Describe the bug

When a bedrock player joins us on the server, the error message spammed below appears in the console. Then he connects the players to the lobby and then after a short time kicks them with the code below.

### To Reproduce

None

### Expected behaviour

I dont know

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/83806525/172903366-7bea6f22-6449-4343-80db-e1be8f74ee8a.png)
![image](https://media.discordapp.net/attachments/613168464634576897/984469000601862154/Screenshot_20220609-164626_Minecraft.jpg?width=1440&height=648)

### Server Version and Plugins

Bungeecord: latest version
GeyserMC: latest version 
Floodgate: latest version
Viaversion: latest Version
Server: Paper-404 1.17.1-R0.1.SNAPSHOT

### Geyser Dump

https://dump.geysermc.org/vNJd7sL0n8dHElrvjo9hBagFkYa4Lhwi

### Geyser Version

Geyser Version 2.0.4-SNAPSHOT

**Comment by onebeastchris** [comment]
Does this issue still occur on the latest versions of..
- bedrock
- geyser
- BungeeCord?

**Comment by onebeastchris** [comment]
Closing due to no response.
