### ISSUE TITLE
Geyser Velocity Doesn't Support 1.19 Clients

### ISSUE THREAD

**Issue by ABUCKY0** [GeyserMC/Geyser#3034]
### Describe the bug

Any Clients Joining from 1.19 Fail to Join
![image](https://user-images.githubusercontent.com/81783950/172954916-ea521b56-f23b-4c74-ad29-9de4ff04c850.png)

### To Reproduce

Create a Velocity Server and add the Geyser Plugin.
Join the Velocity Server
Sign In
Get Kicked

### Expected behaviour

I expected the server to teleport me

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/81783950/172955251-2ed3e2df-fee1-4600-bde2-4f0d72e8474f.png)

### Server Version and Plugins

Geyser Version: 2.0.4 SNAPSHOT
Velocity Version: 3.1.1

Plugins:
GeyserMC

### Geyser Dump

https://dump.geysermc.org/H4LRASjKcAqZ678HF5JzpJ5YqgyZ7RUJ

### Geyser Version

2.0.4 SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.1 Windows 10

**Comment by Camotoy** [comment]
You probably need to use the latest Velocity build from https://papermc.io/downloads#Velocity. Please note that you will need to disable the `force-key-authentication` setting in `velocity.toml` that has been added.

**Comment by ABUCKY0** [comment]
I am on the latest build

**Comment by ABUCKY0** [comment]
and It still isnt working

**Comment by ABUCKY0** [comment]
> You probably need to use the latest Velocity build from https://papermc.io/downloads#Velocity. Please note that you will need to disable the `force-key-authentication` setting in `velocity.toml` that has been added.

1 .I am on the latest build
2.  It still isn't working
3. There is no force-key-authentication
