### ISSUE TITLE
Bedrock players with nicknames from Haonick Spigot plugin can't climb stairs or slabs

### ISSUE THREAD

**Issue by jecowa** [GeyserMC/Geyser#3035]
### Describe the bug

If I give a nickname to a Bedrock player, that player loses the ability to climb stairs and slabs (without jumping up each one). Removing their nickname allows them to walk up them again.

### To Reproduce

from Bedrock user with OP privileges, enter `/nick Bob`

try to walk up stairs (it doesn't work)

then type `/nick reset` to be able to use stairs again

### Expected behaviour

I want the Bedrock players to be able to walk up stairs and slabs even when they have a nickname.

Feature request: Alternatively, it seems like maybe a nickname plugin for Bedrock users could be kind of redundant with powers that Geyser already has (considering the prefixes before Bedrock user's name). Maybe you would consider adding a way to let server admins or player change the names of Bedrock players? Geyser could probably even do a better job of this than a nickname plugin.

### Server Version and Plugins

Server: spigot-1.19-R0.1-SNAPSHOT.jar

Spigot server plugins:

 * Geyser-Spigot v2.0.4-SNAPSHOT (git-master-78bb69b) – build [#1108]
 * floodgate-spigot.jar v2.2.0-SNAPSHOT (b66-5d5713e)
 * HaoNick-v4.6.1
 * NickAPI-v6.4.1

### Geyser Dump

https://dump.geysermc.org/3mzs1MCnuNHFg3o7TtT68xE2zOElgBEM

### Geyser Version

2.0.4-SNAPSHOT (git-master-78bb69b)

### Minecraft: Bedrock Edition Device/Version

Android Bedrock 1.19

**Comment by onebeastchris** [comment]
Does this issue still occur with the latest version of Geyser? If it does, please send a new Geyser dump.
