### ISSUE TITLE
Bedrock crash (playstation 4)

### ISSUE THREAD

**Issue by Olavvvv** [GeyserMC/Geyser#3036]
### Describe the bug

The user logs into the normal lobby server, and nothing happens. But when selecting a mode, it crashes automatically: it closes the application.

This did not happen before, since the user is not new and has things, but now when updating, yes.

### To Reproduce

1. Connect to Lobby
2. Connect another mode
3. Crash (playstation 4)

### Expected behaviour

?

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/94938785/172993749-16cf6f04-c0ab-476f-a3a6-cf0bf0b1c82c.png)
Video: https://youtu.be/1TtbwXeXjhg

### Geyser Dump

https://dump.geysermc.org/wlHjh7LNJr6jMSZgqcwu46zmQO5RbgTE

### Geyser Version

This server is running Geyser version 2.0.4-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19 PlayStation

**Comment by Camotoy** [comment]
Looks like this is the same error as #3025 so I'm closing. Thanks anyway.
