### ISSUE TITLE
Bungeeguard + Geyser

### ISSUE THREAD

**Issue by Olavvvv** [GeyserMC/Geyser#3037]
### Describe the bug

For several users, the connection is refused in the forms when trying to enter.
This has been happening for a long time on my server.

I use redisbungee, therefore I use two proxies (one for java, one for bedrock)

### To Reproduce

1. Connect lobby
2. Try connect another mode
3. You can't join

### Expected behaviour

?

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/94938785/172994301-d01187cb-1b0f-4544-8357-0534343c7dfd.png)

### Geyser Dump

https://dump.geysermc.org/wlHjh7LNJr6jMSZgqcwu46zmQO5RbgTE

### Geyser Version

This server is running Geyser version 2.0.4-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19 Bedrock PC

### Additional Context

This has been going on for a while, I updated geyser, floodgate, bungeeguard and it still goes on. It only happens to me with Bedrock users, and not java.

**Comment by onebeastchris** [comment]
Is this still an issue?
If yes, make sure player info forwarding is set up.

**Comment by Konicai** [comment]
Specifically, you should be using modern player info forwarding on velocity

**Comment by Jens-Co** [comment]
Since this issue has been answered ill close this. If you still got this issue please bump and ill reopen.
