### ISSUE TITLE
Bungeecord + GeyserMC disconect Backend Servers!

### ISSUE THREAD

**Issue by jrodlan** [GeyserMC/Geyser#3038]
### Describe the bug

There is my problem:

1. First server is Bungeecord (Geyser + Floodgate + Viaversion) The viaversion is because Bungeecord still not support 1.19

2. Then the users (java and bedrock) go to the first server "login" at this time is ok

3. When the user  (only happen with bedrock)walk or go to another server. Just disconect without any message just has disconnected from the Java server because of Bedrock client disconnected 

### To Reproduce

1. First server is Bungeecord (Geyser + Floodgate + Viaversion) The viaversion is because Bungeecord still not support 1.19

2. Then the users (java and bedrock) go to the first server "login" at this time is ok

3. When the user  (only happen with bedrock)walk or go to another server. Just disconect without any message just has disconnected from the Java server because of Bedrock client disconnected 

### Expected behaviour

The spected is the user just join to the servers normaly

### Screenshots / Videos

![WhatsApp Image 2022-06-09 at 11 23 33 PM](https://user-images.githubusercontent.com/107237081/172996061-d110a904-d3e0-4afb-8187-39f951e66b44.jpeg)

### Geyser Dump

https://dump.geysermc.org/h1tuZZMFJOu3Jus2BoOVu8Yq0xEudJkr

### Geyser Version

Geyser version 2.0.4-SNAPSHOT (git-master-691d674)

### Minecraft: Bedrock Edition Device/Version

1.19

**Comment by RednedEpic** [comment]
Ensure BungeeCord is updated to 1.19 (there is a version available for this). Also ensure that Floodgate is running the latest version as you are outdated here.
