### ISSUE TITLE
Velocity + Paper 1.19

### ISSUE THREAD

**Issue by AxlRose-RX** [GeyserMC/Geyser#3039]
### Describe the bug

With Java: Can login just fine to Velocity and all servers 1.18.2 Purpur but **only one server is 1.19** Purpur #1640
With Bedrock: Can login just fine Velocity > Hub and all server **but the 1.19** won't work

### To Reproduce

1. Join server (Velocity Proxy)
2. Land on the Lobby server (1.18.2)
3. Switch to any back end that is 1.18.2, they all work
4. Switch to the only 1.19 server and get: **This server requires you to connect with Velocity.**

[floodgate]: Floodgate player logged in as +CerealSeeker795 disconnected
com.mojang.authlib.GameProfile@a45e7ce[id=00000000-0000-0000-0009-01f00350d882,name=+CerealSeeker795,properties={},legacy=false]: (/51.222.93.55:53854) lost connection: This server requires you to connect with Velocity.

### Expected behaviour

Should be able to join the 1.19 server -_-

### Server Version and Plugins

Velocity: latest # 153
Server: git-Purpur-1640 (MC: 1.19)

Plugins:
Plugins (31): AlonsoLevels, CoreProtect, DiscordSRV, Essentials, EssentialsSpawn, floodgate, GeyserSkinManager, GriefPrevention, InventoryRollbackPlus, JSEngine, LuckPerms, MineSync, MobLimit, MyCommand, OpenInv, PlaceholderAPI, ProtocolLib, spark, Spartan, TAB, Vault, VentureChat, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

https://dump.geysermc.org/QlXL4RA12HRYxKA6yhI35m7o5bAsEbqN

### Geyser Version

2.0.4-SNAPSHOT (git-master-162aff4) (Java: 1.19, Bedrock: 1.19.0)

### Minecraft: Bedrock Edition Device/Version

1.19

### Additional Context

Floodate latest version for Velocity and Spigot # 66 (June 8th 2022)

**Comment by Chew** [comment]
Relaying from Camo

> You probably need to use the latest Velocity build from [papermc.io/downloads#Velocity](https://papermc.io/downloads#Velocity). Please note that you will need to disable the `force-key-authentication` setting in `velocity.toml` that has been added.

**Comment by arima0k** [comment]
Still, already did that.

**Comment by AxlRose-RX** [comment]
> Relaying from Camo
> 
> > You probably need to use the latest Velocity build from [papermc.io/downloads#Velocity](https://papermc.io/downloads#Velocity). Please note that you will need to disable the `force-key-authentication` setting in `velocity.toml` that has been added.

if you read the issue, it says there, latest build of Velocity # 153 and to get Geyser players in, even on the working servers I have with 1.18.2, the obvious setting is there already: force-key-authentication = false

**Comment by arima0k** [comment]
I setup floodgate like this BTW, https://wiki.geysermc.org/floodgate/setup/#installing-floodgate-also-on-spigot-servers-behind-bungeecord-or-velocity

**Comment by Kas-tle** [comment]
Could someone test without modern forwarding?

**Comment by arima0k** [comment]
For me it works with legacy forwarding on velocity -> paper.
*Fact: when using modern forwarding the Geyser appears on the friends tab of bedrock, with legacy it doen't.

**Comment by Camotoy** [comment]
> *Fact: when using modern forwarding the Geyser appears on the friends tab of bedrock, with legacy it doesn't.

Unless Geyser fails to boot, I highly doubt changing this setting affects if Geyser shows its ping.

**Comment by Kas-tle** [comment]
Also think this was said earlier in Discord or something, but can you just confirm that 1.18.2 backends work fine?

**Comment by arima0k** [comment]
Looks like Paper 1.19 issue.

**Comment by AxlRose-RX** [comment]
> > *Fact: when using modern forwarding the Geyser appears on the friends tab of bedrock, with legacy it doesn't.
> 
> Unless Geyser fails to boot, I highly doubt changing this setting affects if Geyser shows its ping.

what about the initial issue here Camotoy, is there anything I can do to get the one 1.19 server working as the rest of the servers on the same network for Bedrock players? for Java players it works just fine, only Bedrock players get **This server requires you to connect with Velocity** on that one server only

**Comment by Kas-tle** [comment]
If anyone would like to test this the change was introduced in 152, so you could try with build 151.

**Comment by arima0k** [comment]
Maybe?
https://github.com/PaperMC/Paper/commit/93fc89ef44c6cea184a0a07b91bafd0f64f7dc9e

**Comment by arima0k** [comment]
Velocity 151: same problem.

**Comment by AxlRose-RX** [comment]
> Velocity 151: same problem.

I know, either Geyser of Floodgate are not compatible just yet with [Velocity -> Modern -> {Paper 1.19 or Forks}]

**Comment by AxlRose-RX** [comment]
oh this is the error on velocity:

22:28:42
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.text.ChatTypeEntry.bedrockChatType()" because the return value of "org.geysermc.geyser.platform.velocity.shaded.fastutil.ints.Int2ObjectMap.get(int)" is null
at org.geysermc.geyser.translator.protocol.java.JavaSystemChatTranslator.translate(JavaSystemChatTranslator.java:44)
at org.geysermc.geyser.translator.protocol.java.JavaSystemChatTranslator.translate(JavaSystemChatTranslator.java:35)
at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Camotoy** [comment]
We probably fixed that. Are you on the latest build?

**Comment by AxlRose-RX** [comment]
yeah, updated today

**Comment by arima0k** [comment]
Still happens on the paper and geyser latest builds. And only happens when I use `send-floodgate-data: true` with Floodgate on the back end.

**Comment by AxlRose-RX** [comment]
Update: only works when velocity is on **player-info-forwarding-mode = "LEGACY"** setting

Updated to latest Geyser # 1112, Floodgate #68

Renamed the velocity.toml to get re-created with missing **forwarding-secret-file = "forwarding.secret"** setting

Let's go, be positive, is going to work now ... noup, same issue and only for Bedrock players: **This server requires you to connect with Velocity.**

All other servers that are on 1.18.2 the Bedrock player can join, only the 1.19 gives the error

**Comment by arima0k** [comment]
Latest paper 1.19 build, same.

**Comment by Camotoy** [comment]
Can you try with a Floodgate version before 1.19?

**Comment by Camotoy** [comment]
Why did that send now???
