### ISSUE TITLE
Bug With endStone slab or Just enstone

### ISSUE THREAD

**Issue by Phil200000** [GeyserMC/Geyser#3040]
### Describe the bug

When scroll in the hotbar and select endstone the Bedrock Client immediatly freeze and crash after 2 second

### To Reproduce

1. Scroll in the hotbar for select endstone 
2. And the game crash

### Expected behaviour

Just have the endstone in your main hand

### Geyser Dump

https://dump.geysermc.org/XE4dTpR9GZsVZi1PT6BIR8f3yrSwgH0R

### Geyser Version

2.0.4-Snapshot

### Minecraft: Bedrock Edition Device/Version

Bedrock Windows Edition i don't tested other version

**Comment by ABUCKY0** [comment]
Can you send a screen recording?

**Comment by Camotoy** [comment]
Please try updating Geyser as this is likely resolved. Thanks!
