### ISSUE TITLE
Bedrock Players with spaces in their name get disconnected

### ISSUE THREAD

**Issue by ABUCKY0** [GeyserMC/Geyser#3041]
### Describe the bug

MC Java doesn't support having spaces in the name so when a player tries to connect using a name with spaces the error occurs.

### To Reproduce

Make a minecraft bedrock account with a space in the name
Join a java server using McGeyser
get java.lang.IllegalStateException: Invalid characters in username

### Expected behaviour

The player with the space should have their name altered to allow them to join

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/81783950/173170433-067bea25-cd49-4dde-bf3b-5e8274259129.png)
![image](https://user-images.githubusercontent.com/81783950/173170437-dd7e0d59-7545-424b-94a7-5d5a817e3c57.png)

### Server Version and Plugins

Vanilla 1.19 Java Server
Geyser 2.0.4-SNAPSHOT

### Geyser Dump

https://dump.geysermc.org/tgokNAMD8EP6P3Jd70GYzUrXyAOnas3q

### Geyser Version

2.0.4-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19 WINDOWS 10

**Comment by ABUCKY0** [comment]
remove the space
mabye check the player file for any cross issues
then if there is, add an underscore

**Comment by AxlRose-RX** [comment]
you know Floodgate has the option right?

# Should spaces be replaced with '_' in bedrock usernames?
replace-spaces: true

**Comment by ABUCKY0** [comment]
I was running it standalone

**Comment by ABUCKY0** [comment]
> you know Floodgate has the option right?
> 
> # Should spaces be replaced with '_' in bedrock usernames?
> replace-spaces: true
https://github.com/GeyserMC/Geyser/issues/3041#issuecomment-1152846336

**Comment by ABUCKY0** [comment]
So I installed floodgate to velocity, but then this brings me back to this: #3042

**Comment by ABUCKY0** [comment]
So is it possible to add floodgate to the STANDALONE GEYSERMC?

**Comment by Chew** [comment]
You should be connecting with a premium Java account on standalone Geyser, and Java names do not have spaces in them. Why do you need floodgate?

**Comment by ABUCKY0** [comment]
Because I have my geyser and my server set up in offline mode, and floodgate has an option to remove spaces in names

**Comment by Konicai** [comment]
You can use floodgate with standalone Geyser. Follow the wiki https://wiki.geysermc.org/geyser/setup/ and join the Discord if you need help. 

We also typically don't offer support for offline-mode, which is why we already decided a while ago to not replace spaces with underscores in Geyser.

**Comment by ABUCKY0** [comment]
So it turns out that the stable version of Velocity doesn't support 1.19. J figured it out though
