### ISSUE TITLE
Geyser Velocity Doesn't Support 1.19 Clients {Repeat b/c the first one was closed]

### ISSUE THREAD

**Issue by ABUCKY0** [GeyserMC/Geyser#3042]
#3034

> You probably need to use the latest Velocity build from https://papermc.io/downloads#Velocity. Please note that you will need to disable the `force-key-authentication` setting in `velocity.toml` that has been added.

1 .I am on the latest build
2.  It still isn't working
3. There is no force-key-authentication

_Originally posted by @ABUCKY0 in https://github.com/GeyserMC/Geyser/issues/3034#issuecomment-1152850012_

**Comment by AxlRose-RX** [comment]
![image](https://user-images.githubusercontent.com/10159672/173172073-dc34d401-74a9-47e9-b02f-5e14a424f35d.png)

On velocity.toml

set it to false
and LEGACY

As in the image

**Comment by ABUCKY0** [comment]
I am running a 1.19 server, and I have online mode turned off on my server so the force key auth thing hasnt affected me but Ill try it anyway

**Comment by ABUCKY0** [comment]
and why is the forwarding mode capitalized?

**Comment by Chew** [comment]
Do not make new issues when the last one was closed, please continue the discussion and we can re-open if needed.
