### ISSUE TITLE
Request to adapt limboauth-velocity plugin

### ISSUE THREAD

**Issue by LatosProject** [GeyserMC/Geyser#3043]
### Describe the bug

The latest version of geyser cannot translate limboauth packets.However, the old version 1.18.30 geyser can be successfully translated and entered into the server

### To Reproduce

Bedrock edition players join the server and are always displayed in the connected server...

### Expected behaviour

Successfully translated the package file and entered the server

### Screenshots / Videos

![Screenshot_20220610_163552](https://user-images.githubusercontent.com/89125260/173172422-6cb449d5-7df9-4f5a-9e06-203d20ccca8d.jpg)

### Server Version and Plugins

geyser-Velocity master [#1112]
limboauth 1.0.5 (download from https://github.com/Elytrium/LimboAuth/releases)
limboapi 1.0.5 (download from https://github.com/Elytrium/LimboAPI )

### Geyser Version

geyser-Velocity master [#1112]

### Minecraft: Bedrock Edition Device/Version

1.19.0,android

**Comment by Tim203** [comment]
It looks like limboauth has fixed this issue
