### ISSUE TITLE
Statistic mappings are incorrect

### ISSUE THREAD

**Issue by Bitslayn** [GeyserMC/Geyser#3044]
### Describe the bug

Java statistics aren't showing their corresponding names correctly.

### To Reproduce

Use `/geyser statistics` on Bedrock 1.19 and go to any tab.

### Expected behaviour

The name of the statistic should be the same as in Java.

### Screenshots / Videos

<img src="https://user-images.githubusercontent.com/96226175/173173379-c214d778-12c7-42b5-8af2-dad39babb2d8.png" width="25%"> <img src="https://user-images.githubusercontent.com/96226175/173173376-4c0e0c3b-9f10-4055-b713-355f02f7d5fc.png" width="25%">

### Server Version and Plugins

This server is running Paper version git-Paper-373 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 071a4a2)
You are 6 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-335 (MC: 1.18.2)

Plugins (52): AdvancedHelp, AdvancedNMotd, AdvancedRegionMarket, AsyncWorldEdit, BedrockPlayerManager, BetterSleeping4, ChestSignOpen, ColoredEnderChests, DecentHolograms, DriveBackupV2, DyedBackpacks, dynmap, EcoPower, ElectricSpawners, EmptyServerStopper, Essentials, EssentialsDiscord, EssentialsSpawn, ExoticGarden, ExtraGear, FarmControl, FastChunkPregenerator, floodgate, Geyser-Spigot, GeyserHacks, GeyserSkinManager, GeyserUpdater, GSit, HeadDrops, HoloDropsX, HotbarPets, ImageOnMap, LiteXpansion, LobbyWorld, LuckPerms, PL-Hide, PlaceholderAPI, PrivateStorage, ProtocolLib, SkinsRestorer, Slabbo, Slimefun, SlimefunOreChunks, SlimyTreeTaps, SoaromaSAC, StackMob, TileDataSaver, Vault, ViaVersion, WhatIsThis, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/IqH9yn6IiUcouLDKY2DufB9JvnCHDW3k

### Geyser Version

2.0.4-SNAPSHOT (git-master-162aff4)

### Minecraft: Bedrock Edition Device/Version

Windows 10 Edition v1.19.0

### Additional Context

Issue relates only to item and mob mappings

**Comment by Camotoy** [comment]
I believe this is a ViaVersion issue - Java Edition exhibits the same issue. Therefore, closing. Thanks anyway!
