### ISSUE TITLE
Bug with stone slab craft

### ISSUE THREAD

**Issue by thedarkonekiller** [GeyserMC/Geyser#3045]
### Describe the bug

Hello
We have a problem since the passage in 1.19 of bedrock customers
When we want to craft stone slabs it shows us end stone brick when we take it from the crafting table it turns into mossy stone brick and when we put it down it's stone slab but if we reminent it then that becomes mossy stone brick again

### To Reproduce

1. Put 3 stone in crafting table for slab
2. craft result is not slab but end stone brick
3. put craft result done mossy stone brick
4. place this mossy stone brick they turn in slab 
5. mine slab turn into mossy stone brick

### Expected behaviour

fix this bug

### Screenshots / Videos

https://youtu.be/Xw0GbrMoqxA

### Server Version and Plugins

git-purpur-1610 (MC: 1.18.2)

### Geyser Version

Geyser-BungeeCord(#1108)

### Minecraft: Bedrock Edition Device/Version

1.19 windows

**Comment by Camotoy** [comment]
Please update to the latest Geyser build as this should be fixed. Thanks!

**Comment by jecowa** [comment]
I just tested in Geyser build #1111. 3 stones crafted into 6 stone slabs for an Android 1.19 player. And when placed on the ground, Java 1.19 players are seeing them as stone slabs too.
