### ISSUE TITLE
Bedrock players lose ability to open inventory after attempting to trade with Librarian villagers

### ISSUE THREAD

**Issue by OtterofDeath** [GeyserMC/Geyser#3046]
### Describe the bug

When Bedrock players attempt to trade with librarian or fletcher villager, the trade menu does not appear. After this, the player cannot open their inventory. Opening the trade menu of a mason villager allows the player to open their inventory again. 

I only have access to the mobile version of Bedrock and wasn't able to test it on other platforms. 

### To Reproduce

1. Join server on Bedrock.
2. Go to a librarian villager and tap "Trade," sometimes tapping trade more than once was required to activate the bug.
3. Attempt to open inventory.

### Expected behaviour

Players should be able to open the trading menu with any villager and be able to open their inventory. 

### Screenshots / Videos

![Screenshot_20220611-120530](https://user-images.githubusercontent.com/26151796/173195775-93213575-bfd8-4ec2-981e-e20779216952.png)

### Server Version and Plugins

Paper 1.18.2 version 349
floodgate 2.1.0-SNAPSHOT
ViaVersion 4.3.1
Essentials 2.19.4
GriefPrevention 16.18
Valut 1.7.3-b131

### Geyser Dump

https://dump.geysermc.org/SmwCSTQzEWu03O8iT9NEycdtoI0Ox8v4

### Geyser Version

2.0.4-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.0 Mobile

**Comment by Camotoy** [comment]
Can you try using the latest ViaVersion jar from here? https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.3.2-SNAPSHOT.jar

**Comment by jecowa** [comment]
I'm not having this issue in the Spigot version of Geyser (built #1111). Android 1.19 player could open trade window with librarian and fletcher and still open inventory afterwards.

**Comment by OtterofDeath** [comment]
Updating to ViaVersion 4.3.2 looks to have fixed the problem. I tested with my mobile client and I'll post an updated if it persists for the original players who encountered this bug.
