### ISSUE TITLE
Bedrock edition issues

### ISSUE THREAD

**Issue by looeyoxide** [GeyserMC/Geyser#3047]
### Describe the bug

I am using this plugin and it is great! But When I join the server with a bedrock edition client, after a minute or so every entity, block, particle etc. freezes. You can still move but other players can not see you moving. When you reconnect you fall into the void but not die

Help?

### To Reproduce

Open minecraft on both java and bedrock
join the server
wait a minute
error

### Expected behaviour

Open minecraft on java and bedrock
join server
play flawlessly

### Geyser Dump

https://dump.geysermc.org/Bt4HiRtuyjPR3tCLocrVoRPPsIzZrb8X

### Geyser Version

2.0.4-SNAPSHOT (git-master-162aff4)

### Minecraft: Bedrock Edition Device/Version

All

**Comment by Kas-tle** [comment]
You seem to be using an 11th gen CPU so likely a duplicate of https://github.com/GeyserMC/Geyser/issues/2861
Please see the potential workarounds there.
Thanks!

**Comment by looeyoxide** [comment]
worked, thanks :)
