### ISSUE TITLE
got kicked when typing chat

### ISSUE THREAD

**Issue by X2IX** [GeyserMC/Geyser#3050]
### Describe the bug

when open chat and typing something then send will got kick `An internal error occurred in your connection` but typing command work fine

i use velocity geyser and floodgate both and on sub server use fabric but i didnt have floodgate
all mod i use in fabric only fabric proxy lite

### To Reproduce

1. connect to server
2. open chat
3. typing something
4. got kicked with this erorr   `An internal error occurred in your connection`

### Expected behaviour

i want bedrock player can chat with java player

### Screenshots / Videos

https://youtu.be/SWfGWpiiLBU

### Server Version and Plugins

Proxy | velocity-3.1.2-SNAPSHOT-144
Sub 1 | Fabric 1.19 (0.14.7)
Sub 2 | Fabric 1.19 (0.14.7)
Sub 3 | Fabric 1.19 (0.14.7)

### Geyser Dump

https://dump.geysermc.org/du64Hnyl6Tb750rakhsAdecHJj2F7Xnf

### Geyser Version

Geyser version 2.0.4-SNAPSHOT (git-master-4a9581c) (Java: 1.19, Bedrock: 1.19.0)

### Minecraft: Bedrock Edition Device/Version

1.19.0 | Apple Ipad air 4

### Additional Context
erorr in velocity console
```
[20:22:49 INFO]: [connected player] Nayuta207 (/182.232.79.182:0) has disconnected: An internal error occurred in your connection.
[20:22:49 INFO] [floodgate]: Floodgate player logged in as Nayuta207 disconnected
[20:22:49 ERROR]: [connected player] Nayuta207 (/182.232.79.182:0): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@72b78d4f
com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). If you are a developer, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.
```

_No response_

**Comment by Kas-tle** [comment]
Could you please add `-Dvelocity.packet-decode-logging=true` to your server startup arguments on Velocity and provide the full log when the player is disconnected with that option enabled?
Also could you provide logs from the fabric back end?

**Comment by Camotoy** [comment]
Are Java 1.19 players affected?

**Comment by X2IX** [comment]
> Are Java 1.19 players affected?

java player are fine

**Comment by Kas-tle** [comment]
Floodgate I thought would be fixing this by default, but out of curiosity, could you try setting this setting to false (you may have to add it to your velocity.toml) and see if the issue still occurs?
https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/resources/default-velocity.toml#L19

**Comment by Camotoy** [comment]
You probably need to update Velocity from https://papermc.io/downloads#Velocity - looks like the very next build after yours fixes this issue. If the issue still occurs after updating, let us know, but that should fix it.
