### ISSUE TITLE
Click event actions from VentureChat and InteractiveChat 1.19

### ISSUE THREAD

**Issue by AxlRose-RX** [GeyserMC/Geyser#3054]
### Describe the bug

Tons of errors on console with new VentureChat build from yesterday for 1.19

Bedrock: Messages go to servers from Bedrock client but **Bedrock client doesn't see own messages** but Java clients can see what Bedrock client wrote
Java: Messages go to servers from Java and Java client is able to see what he wrote on chat

### To Reproduce

For both Java and Bedrock any message on chat spam console with errors

Back end 1.19 server logs when this happened: https://mclo.gs/DlNyM0E

Instructions per VentureChat developer is to keep [VentureChat 3.3.2] stable on both the Proxy (Velocity) and 1.18.2 servers, only add the new [VentureChat 3.4.0] to the 1.19 back end servers

Errors on Velocity on console when a player types from Bedrock: **Downstream packet error! invalid click action:**
Logs from Velocity when this happened: https://mclo.gs/6CjMuXz

Camotoy asked me to make issue with Geyser in Debug mode, but I can't at the moment, will try again later once I restart server and no players online I put back the VentureChat for 1.19 back on that server, right now with just EssentialsX Chat all OK, no errors but the problem is with EssentialsX I can't have global chat on all servers.

### Expected behaviour

Bedrock client should be able to see what he writes on chat no matter all the errors on console by using the new VentureChat for 1.19 and InteractiveChat with "Bungee support"

### Screenshots / Videos

![versions](https://user-images.githubusercontent.com/10159672/173881516-b1b1299e-f356-43a9-b276-0adc9bf0cf1b.PNG)

### Server Version and Plugins

Current: git-Purpur-1666 (MC: 1.19)*
* You are running the latest version
Plugins (35): AlonsoLevels, ChatInjector, CoreProtect, DiscordSRV, Essentials, EssentialsChat (replaced temporarily as too many errors from VentureChat), EssentialsSpawn, floodgate, GeyserSkinManager, GriefPrevention, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, JSEngine, LuckPerms, MineSync, MobLimit, MyCommand, OpenInv, PlaceholderAPI, ProtocolLib, spark, Spartan, TAB, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags

Velocity # 153

### Geyser Dump

https://dump.geysermc.org/1zmtBTpFxKr0vAphv0KpooqLhYEeqBSJ

### Geyser Version

2.0.4-SNAPSHOT (git-master-aa097ec) (Java: 1.19, Bedrock: 1.19.0)

### Minecraft: Bedrock Edition Device/Version

Windows 10 1.19

### Additional Context

Reported issues on VentureChat:

https://www.spigotmc.org/threads/venturechat.24005/page-518

Messages on Discord trying to figure out the issue from InteractiveChat Dev.

LOOHP | No DMs — Today at 5:12 AM
there seems to be some weird json formatting going on
I'll take a closer look a bit later
There are some click events with an action of nothing

LOOHP | No DMs — Today at 9:54 AM
Then I'm guessing this new 1.19 VentureChat build is sending stuff differently compare to how it used to
Let me give it a try

LOOHP | No DMs — Today at 9:59 AM
I'm testing it on a single paper 1.19 server
seems to be working

LOOHP | No DMs — Today at 10:04 AM
VentureChat is probably sending the chat components with empty click event actions
Which is invalid, but the java client somehow still accepts it
but either geyser or the bedrock client doesn't accept that (just like ic)
which explains why they don't show on bedrock

**Comment by Camotoy** [comment]
Can you send your VentureChat config?
