### ISSUE TITLE
Spigot page doesn't list 1.19 as supported

### ISSUE THREAD

**Issue by BobtheBob123456** [GeyserMC/Geyser#3055]
### What feature do you want to see added?

Hi GeyserMC Team,
Firs of, I'd like to thank you guys for making such an awesome plugin.

Secondly, I'd like to ask if Geyer fully supports 1.19? The reason I ask this question is because on the spigot page it says Geyser supports 1.18, while on the GitHub page, it says it support 1.19.

If Geyser does support 1.19, can you please update the spigot page so it says Geyser support 1.19? If it doesn't, can we have an approximate release date on when it will come out.

Thanks,
Bob

### Are there any alternatives?

I have none

**Comment by Camotoy** [comment]
Geyser does support 1.19 and the Spigot page simply does not mention it.

**Comment by BobtheBob123456** [comment]
Oh. Is there any way you can make it so the spigot page lists that Geyser MC has updated to 1.19?

Thanks

**Comment by Camotoy** [comment]
We'll close this issue when we do.

**Comment by BobtheBob123456** [comment]
Ok, thanks
