### ISSUE TITLE
Error connecting player to server

### ISSUE THREAD

**Issue by DimaSergeew** [GeyserMC/Geyser#3058]
### Describe the bug

I downloaded Geyser Standlone so that players from 1.19 could play on my server. But when they connect, this error pops up for everyone

### To Reproduce

just go to the server

### Expected behaviour

That, as in 1.18, I had everything normally connected to the server via standlone

### Screenshots / Videos

![Screenshot_2](https://user-images.githubusercontent.com/75163645/174003141-77e4a9b9-ad96-47b9-ae2a-16c760bf4116.png)
![Screenshot_3](https://user-images.githubusercontent.com/75163645/174003195-5350171f-6627-47ac-93ca-5ca3fde4fcea.png)

### Server Version and Plugins

1.18.2 purpur, geyser 1.19 lastet version

### Geyser Dump

https://dump.geysermc.org/9KgBWS9mA55uYVqUzQCCVaa4cnzzZoua

### Geyser Version

This server is running Geyser version 2.0.4-SNAPSHOT (git-master-5e1769d) (Java: 1.19, Bedrock: 1.19.0)

### Minecraft: Bedrock Edition Device/Version

Xiaomi MI 9T: Minecraft Bedrock v 1.19.0

### Additional Context

error - https://paste.gg/p/anonymous/c4fb736e0e464baca5894a7cf42e21d3

**Comment by Camotoy** [comment]
I'm closing since one of the errors is irrelevant, and I believe the first issue already exists. Either way, this needs to be recreated for 1.19.1 since the system has changed a bit. Thanks.
