### ISSUE TITLE
Block Break Interactions Fire Twice in Creative

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#3060]
### Describe the bug

When breaking a block in Creative mode, the BlockBreakEvent fires twice for a Bedrock place and once (like it should) for a Java player.

This is what I'm running:
```
@EventHandler
public void onBreak(BlockBreakEvent e) {
      e.getPlayer().sendMessage("breakEvent");
}
```

### To Reproduce

1. Create a plugin that does something on BlockBreakEvent
2. Connect to the Geyser server and break a block in Creative mode
3. Notice the event contents fire twice

### Expected behaviour

The block break interaction should only fire once for Bedrock players in Creative mode.

### Screenshots / Videos

https://user-images.githubusercontent.com/41856020/174140902-4eaaefae-7116-46fc-a30e-6f5903410233.mp4

### Server Version and Plugins

Spigot 1.12.2 - this issue also happens with Geyser-BungeeCord

ViaVersion 4.3.2
Small plugin with only the code at the top of the issue

### Geyser Dump

https://dump.geysermc.org/Hap6xekJ6zuIKNRb2NHF9uaaIS89Uv7Z

### Geyser Version

2.0.4-SNAPSHOT (git-master-5e1769d)

**Comment by onebeastchris** [comment]
Is this still an issue?

**Comment by onebeastchris** [comment]
closing as https://github.com/GeyserMC/Geyser/pull/3996 has been merged
