### ISSUE TITLE
Xbox One client slab problems

### ISSUE THREAD

**Issue by LunarHackett003** [GeyserMC/Geyser#3061]
### Describe the bug

My friend and I are currently on an aternos server on 1.19, and they tell me that quartz slabs are shown as being stone slabs.
I am on a java client and they are on Xbox
Current issues they've found are
- Slabs of any kind of rock or brick cannot be picked from the creative inventory. This includes normal stone slabs. Wooden slabs are as normal.
- When crafting slabs with base blocks, the crafting result is stone slabs regardless of the block
- Quartz slabs in their hand were displayed as stone slabs on their client but as Quartz slabs on my client (Java client)

### To Reproduce

PICKING BLOCKS
1. Enter an aternos server (unsure if this is a universal bug or an aternos bug)
2. Join Java server with Geyser from Xbox One client
3. Open creative inventory and find stone, purpur and quartz slabs (these were the ones tried)
4. The blocks will not be taken
CRAFTING BLOCKS
Repeat steps 1 and 2
3. Take base blocks, tested with quartz
4. On crafting table, attempt to craft slabs 
5. Crafting table showed stone slabs as the image provided shows

### Expected behaviour

We expected this to work normally, as the issue has only developed within the last day or two
Blocks should be picked as any other player would, slabs should be able to be crafted

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/61294652/174156574-64f081e7-08ed-4e75-ab09-33b24267f195.png)

### Server Version and Plugins

Spigot Version
![image](https://user-images.githubusercontent.com/61294652/174157775-173b4168-9732-4d65-a4ed-94e12b71bb65.png)
Join Events Pro Version: 4.3

### Geyser Dump

https://dump.geysermc.org/PBg6ZhM2l4oU4ylrwTkO9ZkZqjdkAChk

### Geyser Version

2.0.4-SNAPSHOT (git-master-78bb69b)

### Minecraft: Bedrock Edition Device/Version

1.19.0 Xbox

**Comment by Camotoy** [comment]
Your Geyser build is outdated. Please update it. Thank you!
