### ISSUE TITLE
Java acc linking to bedrock acc

### ISSUE THREAD

**Issue by Sonic0005000** [GeyserMC/Geyser#3066]
### What feature do you want to see added?

I want to be able to link my java acc to my bedrock one with the access to play java servers, instead of linking your bedrock acc to your java acc only.

### Are there any alternatives?

Fix the glitch where I can't unlink my bedrock acc from my java acc

**Comment by Camotoy** [comment]
Are you asking for a feature where Java players can log in as your Bedrock account? If so, we're not interested in doing that, because we'd have to modify Java connections.

**Comment by Konicai** [comment]
You can unlink your accounts on the global linking server: https://wiki.geysermc.org/floodgate/linking/
