### ISSUE TITLE
Players cannot trade or open GUIs

### ISSUE THREAD

**Issue by spikehidden** [GeyserMC/Geyser#3070]
### Describe the bug

When trying to try to open the trading GUI of a some villagers nothing happens but the Server still thinks the player is trading with the villager as other Java players cannot open the GUI then and it isn't possible for the player to open any inventory or GUI unless they rejoin the server.

### To Reproduce

1. Go to a villager
2. Interact with it
3. Nothing happens for the player.
4. Try to open a chest or another inventory.
5. Chest opens but not the inventory

### Expected behaviour

The player should be able to trade and open other GUIs afterwards.

### Screenshots / Videos

https://user-images.githubusercontent.com/31257733/174442249-b2e2dca9-7448-401f-8a71-4f14d6bd1454.mp4

### Server Version and Plugins

Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Purpur-1623 (MC: 1.18.2)
* You are running the latest version

### Plugins
AntiCheatReloaded, BedrockPlayerManager, Chunky, Citizens, CitizensGUI, CitizensPlaceholderAPI*, ClaimChunk, Denizen, Depenizen, DiscordSRV, DropEdit2, dynmap, Dynmap-ClaimChunk*, Dynmap-WorldGuard*, EconomyShopGUI-Premium, Essentials, EssentialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, GeyserHacks, GeyserSkinManager, Gringotts, HeadDrops, JShader, LuckPerms, MultiLang, Multiverse-Core, Multiverse-Portals, Multiverse-SignPortals, MyCommand, Pl-Hide-Pro, PlaceholderAPI, PowerBoard, ProtocolLib, RocketPlaceholders, Sentinel, StreamingDrops, Vault, ViaVersion, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/JpHUw0uuTZdBRIGv8unvUowJwSK8QJou

### Geyser Version

version 2.0.4-SNAPSHOT (git-master-fef0401)

### Minecraft: Bedrock Edition Device/Version

1.19.0 - Nintendo Switch, Wndows 11

#### Log with errors
https://paste.denizenscript.com/View/97732

#### Other
This also doesn't happen with all villagers but always with the same ones. It also doesn't seem to affect certain jobs.

**Comment by Camotoy** [comment]
Updating to the ViaVersion CI builds should fix your issue.
