### ISSUE TITLE
Scaffolding places sideways instead of upwards 

### ISSUE THREAD

**Issue by username100099** [GeyserMC/Geyser#3072]
### Describe the bug

when placing scaffolding it places sideways instead of stacking upwards.

### To Reproduce

place scaffolding down in a geyser server

### Expected behaviour

The scaffolding to place upwards instead of sideways

### Server Version and Plugins
Server Version: Paper (git-Paper-20 (MC: 1.19))
AntiCreeper, BlueMap, ChestShop, CommandBlocker, CoreProtect, DecentHolograms, EasyWhitelist*, EnderChestViewer*, floodgate, Geyser-Spigot, IPAuth*, LiveKit, OnePlayerSleep*, OreAnnouncer, SeePlayerInventory, Vault, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/Fq05iL5cAGoH0N5fIQiC4fjT0uqy63jG

### Geyser Version

2.0.4-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.0 (Latest)

**Comment by onebeastchris** [comment]
Hey,
try crouching and looking down while placing scaffolding in order to build the scaffolding vertically.

**Comment by Konicai** [comment]
This can be reopened if more information is provided.
