### ISSUE TITLE
Mobile players hang upon pressing slash for commands

### ISSUE THREAD

**Issue by MTGF947** [GeyserMC/Geyser#3074]
### Describe the bug

Upon joining, if you type “/“ in the chat at the start of your message, the game will hang and crash. Tested on iPhone 12 and Pixel 3a. Does not appear to happen on native bedrock servers.

### To Reproduce

1. Join the geyser server on a mobile device.
2. Open chat and press slash at the start of your message
2a. Alternatively press the commands button and chose one.

### Expected behaviour

Ability to type commands.

### Server Version and Plugins

Plugins:
    Bungeecord Proxy:
        -Geyser
    Server 1 (Purpur 1.19)
        -Floodgate
        -FAWE
    Server 2 (Purpur 1.19)
        -Floodgate

### Geyser Dump

(Will add when available)

### Geyser Version

(Will add when available)

### Minecraft: Bedrock Edition Device/Version

1.19 Pocket Edition

### Additional Context

Currently out of town and unable to provide info without a computer. (cant type commands on mobile lel)

**Comment by Camotoy** [comment]
This is a Bedrock bug that happens with a lot of command suggestions. Disable `command-suggestions` in your Geyser config will resolve this, but at the cost of no command suggestions. Thanks.
