### ISSUE TITLE
Villager level bar doesn't update

### ISSUE THREAD

**Issue by DominikSLK** [GeyserMC/Geyser#3075]
### Describe the bug

Villager level bar doesn't update while trading

### To Reproduce

1. Trade with villager

### Expected behaviour

Villager level bar should update

### Screenshots / Videos

https://user-images.githubusercontent.com/74055080/174558119-2f4e96d2-46f0-4454-8ae6-c938b0fe8296.mp4

### Geyser Dump

https://dump.geysermc.org/VmzvEM8HXI8h3YV3blijn0rzLxk2wR8n

### Geyser Version

2.0.4-SNAPSHOT (git-master-18f6836)

### Minecraft: Bedrock Edition Device/Version

1.19.0

**Comment by onebeastchris** [comment]
Does this issue still occur with the latest version of Geyser? If it does, please send a new Geyser dump.

**Comment by DominikSLK** [comment]
https://dump.geysermc.org/TbJ66G383zvja7VJIdjbgR2JX3kGkGWE
