### ISSUE TITLE
Console is spammed with error

### ISSUE THREAD

**Issue by Laro5444** [GeyserMC/Geyser#3076]
### Describe the bug

If Dkbans and Geyser are on the proxy with Floodgate and a Bedrock player joins then the console will be spammed with this error. After a short time the bedrock players will be kicked off the server. If I take DKBans down and leave Geyser and Floodgate on the proxy, then Bedrock players can join as normal. This error only occurs with Bedrock players.

### To Reproduce

Put DKBans and Geyser on the proxy with Floodgate and restart. When joining with a Java account, there is no error when joining with a Bedrock account, there is an error and after a short time the kick.

### Expected behaviour

That it works the same as before. Since Geyser was updated, the error has occurred

### Screenshots / Videos

![fehler](https://user-images.githubusercontent.com/83806525/174633811-2e2e3b0e-9b63-4f09-a482-4c026a6b2b0c.png)

### Server Version and Plugins

git-Paper-409 version 1-17-1-R0.1-Snapshot Git:c53577e on ver/1-17-1
Proxy: Bungeecord 1.19 #1644
ProxyPlugins: BedrockPlayerManagerProxy-1.2, floodgate-bungee #70, Geyser-Bungeecord #1125, JDA-4.4.0_350-all, Luckperms-Bungee-5.4.21, Plan-5.4-build-1583, Teamverify_-_Bungee, WoltlabSync BungeeCord, (DKBans 1.24.7.640)

### Geyser Dump

https://dump.geysermc.org/25XrINXH191lo1kFfaL1N7iRf1vJ4LXU

### Geyser Version

2.0.4-Snapshot (git-master-18f6836)

### Minecraft: Bedrock Edition Device/Version

1.19.0 All devices running Minecraft Bedrock

**Comment by DimaSergeew** [comment]
the same thing just cut it out of the geyser code so as not to spam

**Comment by Laro5444** [comment]
How?

**Comment by DimaSergeew** [comment]
Listen, I had this from a plugin, I don’t remember which one I calculated by the elimination method by deleting 1. try to remove unimportant plugins and check.

**Comment by Laro5444** [comment]
Only important plugins are on the proxy. If I take one away now, it will affect the security of the server.

**Comment by Camotoy** [comment]
Can Java 1.19 players connect fine?

**Comment by Laro5444** [comment]
So start again :)
If we have our ban system on the proxy and the Bedrock players join, the console will be spammed with the above. And then the Bedrock players will be kicked after a short time. Java players can play it normally and will not be kicked.
Strangely enough, if we remove our ban system from the proxy, it works. I hope you understand what I mean. Our bansystem is DKBans. The best thing is to test it yourself :) .

**Comment by Laro5444** [comment]
What is now ????

**Comment by onebeastchris** [comment]
Please try updating Geyser to the latest version - that issue might be already fixed. If it isnt, please provide a new Geyser dump

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
