### ISSUE TITLE
Local Geyser Server No Longer Visible on Xbox Since Paper Version #31

### ISSUE THREAD

**Issue by Firetop** [GeyserMC/Geyser#3079]
### Describe the bug

Bedrock Minecraft no longer sees local Geyser Java server after updating Paper to version 31.

### To Reproduce

Update Paper server to Version 31 found here: https://papermc.io/downloads#Paper-1.19
(c1dbb578757df41df45e1779c937de5ca9319caccbc23e1536782e8028787b20)

Start the server with no plugins but Geyser.

Try to find local LAN server on Xbox Bedrock edition, it won't appear anymore.

### Expected behaviour

For a Geyser server to be available over LAN.

### Server Version and Plugins

[19:47:37 INFO]: This server is running Paper version git-Paper-31 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: fb2c24b)
You are running the latest version
Previous version: git-Paper-30 (MC: 1.19)

No Plugins but Geyser and Floodgate.

### Geyser Dump

https://dump.geysermc.org/yGvrKwk009KXmRrngDo1efA5kGifhkte

### Geyser Version

Geyser version 2.0.4-SNAPSHOT (git-master-18f6836)

### Minecraft: Bedrock Edition Device/Version

Minecraft Bedrock 1.19 on Xbox

**Comment by Camotoy** [comment]
Disable the ping passthrough settings or enable legacy ping passthrough to resolve for now.

**Comment by Firetop** [comment]
> Disable the ping passthrough settings or enable legacy ping passthrough to resolve for now.

Dat turn around time though on a workaround. I love it. Thank you!

**Comment by thosegamer** [comment]
fix it please
