### ISSUE TITLE
Cartography table broken

### ISSUE THREAD

**Issue by onebeastchris** [GeyserMC/Geyser#3081]
### Describe the bug

Unable to create/change maps in the cartography table

### To Reproduce

1. Use Geyser-Velocity + Fabric Backend
2. Place cartography table
3. Unable to put in a map/compass

### Expected behaviour

Expected behavior: ability to use the cartography table 

### Server Version and Plugins

Geyser Version 2.0.4-SNAPSHOT (git-master-18f6836) (Java: 1.19, Bedrock: 1.19)

Plugins: 
On velocity: Floodgate + Geyser
On Fabric Backend: Luckperms, Floodgate, Phosphor, Lithium, FabricAPI, Ledger

### Geyser Version

Geyser Version 2.0.4-SNAPSHOT (git-master-18f6836) (Java: 1.19, Bedrock: 1.19)

### Minecraft: Bedrock Edition Device/Version

1.19

**Comment by hd189733** [comment]
I'm having the same issue with paper-1.19.3-384,  Geyser version 2.1.0-SNAPSHOT (git-master-af5d03f), floodgate v2.2.0-SNAPSHOT (b74-4f36112), RaspberryJuice v1.12.1, from bedrock 1.19.51.
