### ISSUE TITLE
geyser bungeecord 

### ISSUE THREAD

**Issue by KazuYuki-senpai** [GeyserMC/Geyser#3093]
### Describe the bug

the plugin geyser bungeecord is not working 

but the geyser spigot it working for me  

so when i use the geyser bungeecord in my bungeecord proxy it says unable to connect to world 

### To Reproduce

1. install the bungeecord geyser and floodgate then start 

### Expected behaviour

unable to connect to world

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/108244820/175841684-7081a20e-8630-41dd-b5ea-9d30bfed787f.png)

### Server Version and Plugins

1.18.2 bungeecord

### Geyser Version

Build #1126

**Comment by Camotoy** [comment]
Geyser-BungeeCord works for me, meaning this is likely a setup issue. Check for errors in your log files, check our wiki for steps on how to address this: https://wiki.geysermc.org/geyser/fixing-unable-to-connect-to-world/, and otherwise please join our Discord for further help. Thanks.
