### ISSUE TITLE
Spawn protection may need re-evaluated 1.19

### ISSUE THREAD

**Issue by XXdavodXX** [GeyserMC/Geyser#3094]
### Describe the bug

You cant open or close a door, chest, or anything else correctly even if the animation and sound are there.  Also, broken blocs just disappear. Everything in Java works perfectly in this chunk except for all Bedrock players.

I also tried to revert to the last update of Geyser and Purpur I had so it might not look up to date but it was during the video capture.

### To Reproduce

Check the linked Youtube video. https://youtu.be/9poE1CBIJ4U

### Expected behaviour

Bedrock users should be able to play like Java players in this chunk

### Screenshots / Videos

https://youtu.be/9poE1CBIJ4U

### Server Version and Plugins

Current: git-Purpur-1670 MC: 1.19  Previous git-Purpur-1684

### Geyser Dump

https://dump.geysermc.org/tTC8SdcGyHGsJJvAB6PkH7Q1ltpc4scx

### Geyser Version

2.0.4-SNAPSHOT (git-master-08241b8)

### Minecraft: Bedrock Edition Device/Version

1.19 Bedrock Windows edition

### Additional Context

It's really near the spawn point. It's only affecting this chunk for all Bedrock users. everything works properly with Java users.

**Comment by Camotoy** [comment]
Things being this buggy smells like a permissions issue/spawn chunk issue. However:
- If you `/op` the Bedrock player, does the issue go away?
- Are there any errors in your logs?

Otherwise feel free to DM the world/chunk file to me on Discord.

**Comment by XXdavodXX** [comment]
> Things being this buggy smells like a permissions issue/spawn chunk issue. However:
> 
> * If you `/op` the Bedrock player, does the issue go away?
> * Are there any errors in your logs?
> 
> Otherwise feel free to DM the world/chunk file to me on Discord.

I opped my Bedrock account and yes it's working. I don't have errors in my logs.

Is there a workaround if I don't want to op every Bedrock player?

Thank you.

**Comment by Camotoy** [comment]
Do unopped Java players have similar issues?

**Comment by XXdavodXX** [comment]
> Do unopped Java players have similar issues?

I deop myself with my Java account and I do have the issue on Java as well.

**Comment by Camotoy** [comment]
I don't remember spawn chunk properties correctly, but at that point it's definitely not an us issue. I will keep this issue open though because we may need to re-evaluate rollback behavior after 1.19.

**Comment by XXdavodXX** [comment]
Alright, thank you. 
I will do research on my side to fix this issue. Sorry to have bothered you with that.

**Comment by XXdavodXX** [comment]
I resolved the issue. I had to put 0 instead of 16 on the line Spawn protection in the server properties. Thank you for your help.

**Comment by zazzman** [comment]
I have the same issue. For bedrock users the animations work and it looks like you’ve destroyed something, but it’s still there. This happens anywhere w/in the spawn protection square. Java users are not affected.

I have spawn-protection set to 3. I would prefer to not set it to 0 because I want to make sure non-OP players don’t destroy the spawn.

**Comment by Camotoy** [comment]
Can you please try with the latest Geyser version?

**Comment by Jens-Co** [comment]
Any updates on this issue?

**Comment by Camotoy** [comment]
No response so I'm closing this issue. Please open a new issue if problems perist.
