### ISSUE TITLE
error Could not translate packet ClientboundContainerSetContentPacket

### ISSUE THREAD

**Issue by DimaSergeew** [GeyserMC/Geyser#3095]
### Describe the bug

I noticed such a mistake in my Velocity, it appeared recently that we didn’t put anything new on our parish

### To Reproduce

It happens from time to time

### Expected behaviour

that she won't)

### Screenshots / Videos

![Screenshot_1](https://user-images.githubusercontent.com/75163645/175932664-cffd2621-f430-4a1d-9e76-53806fe1a302.png)

### Geyser Version

[14:38:25 INFO]: This server is running Geyser version 2.0.3-SNAPSHOT (git-master-c83eb7f) (Java: 1.18.2, Bedrock: 1.18.0/1.18.1/1.18.2 - 1.18.30/1.18.31)

**Comment by Jens-Co** [comment]
I will close this issue since there is a new issue made with more reference to duplicate issues https://github.com/GeyserMC/Geyser/issues/3115
