### ISSUE TITLE
Cant trade with villagers

### ISSUE THREAD

**Issue by FlameQuard** [GeyserMC/Geyser#3097]
### Describe the bug

i cant trade books with villagers
when i trade the book it doesnt gives!

1.19.2 bedrock version

1.19 paper server version

### To Reproduce

same as #838

### Expected behaviour

when i tried to trade book with villager its not trading book
its same issue like #838 but in latest version

### Geyser Version

idk because i join through ip/port

**Comment by Camotoy** [comment]
If this isn't your server, we can't reliably debug it. Make sure they're using the latest Geyser, and if they need ViaVersion, make sure it's updated to the latest build from their CI. Thanks.
