### ISSUE TITLE
When shifting under block, it wont always register

### ISSUE THREAD

**Issue by bafgd** [GeyserMC/Geyser#3098]
### Describe the bug

When i crouch under a half slab it works as intended, but when i fly under the slab, i will just clip through all the slabs at normal speed.
NOTE: this only happens when the previous crouch was being held and you did not stand up while being under a slab causing geyser to give you a sudo slowness affect. (You will be able to see later in the clip)

### To Reproduce

1. Grab a elytra
2. make a pathway of 1.5 blocks of space in height
3. walk under it normaly *while holding shift the entire time*
4. then fly under the slabs
5. you will be able to go through slabs at walking speeds

### Expected behaviour

it should push you into crouching mode (similar to how it reacts when you let go of shift, while still being under a slab)

### Screenshots / Videos

https://www.youtube.com/watch?v=6GemeC_mpp0

### Server Version and Plugins

This server is running Paper version git-Paper-39 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 37afe98)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-14 (MC: 1.19
![Screenshot 2022-06-28 214859](https://user-images.githubusercontent.com/95045282/176340549-b04a3cf3-8e82-4fdc-98de-73c6429ee157.png)
)

### Geyser Dump

https://dump.geysermc.org/r1mXIpfbR3NkFGF5HGUGXTVOEat480NA

### Geyser Version

2.0.4-SNAPSHOT (git-master-5d29bda)

### Minecraft: Bedrock Edition Device/Version

1.19.2 windows 10

### Additional Context

The bug wont work if you uncrouch (release shift) while still being under slabs. You will need to hold shift the entire time for it to work normally then you can fly under the slabs and the bug will work

**Comment by onebeastchris** [comment]
Hey! If this issue is still occurring with the latest version of Geyser, please send a new Geyser dump by running "geyser dump" in the server console & sending the link you get here. Thanks!

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
