### ISSUE TITLE
Movement errors, bedrock player's movement is selectivly translating

### ISSUE THREAD

**Issue by icecold85** [GeyserMC/Geyser#3101]
### Describe the bug

logs: https://mcpaste.io/2081ad27df7ff8ad
note: I am new to github
Anyways on with the rest of the bug report! For some reason (and I don't know why) bedrock players on my server will just stop moving server side, causing them to "lag" or not be able to do anything, (meaning theyre standing still for me and the server, but they are actually moving on their screen) Nothing weird or abnormal is produced in the console when this issue happens.  (and yes i have made sure the player is NOT lagging, they can see all server movements of animals when this happens) 

### To Reproduce

at random

### Expected behaviour

Player on bedrock edition is not able to play the game/is moving on their screen, but not to the server or other java players

### Server Version and Plugins

All server plugins
bStats 
Chunky
Dynmap
Floodgate
Geyser-Spigot
TreeFeller

### Geyser Dump

https://dump.geysermc.org/2YE4J4UmMYIkheGAwykYCJdeGqyVF7kf 

### Geyser Version

2.0.4-SNAPSHOT (git-master-5d29bda)

### Minecraft: Bedrock Edition Device/Version

1.19 Xbox series S

### Additional Context

Edit: Refreshing geyser seems to fix this issue, however restarting the server dose not

**Comment by onebeastchris** [comment]
Hey! If this issue is still occurring with the latest version of Geyser, please send a new Geyser dump by running "geyser dump" in the server console & sending the link you get here. Thanks!

**Comment by onebeastchris** [comment]
Closing due to no response.
