### ISSUE TITLE
Stuck in Loading Geyser not responding

### ISSUE THREAD

**Issue by KJZH001** [GeyserMC/Geyser#3107]
### Describe the bug

*Translated from DeepL and mixing my English

Before that it was working fine(players already can through Minecraft Bedrock join game), but today after a restart of geyser, it got stuck at loading and no subsequent response

### To Reproduce

1.use `java -jar Geyser.jar nogui` on CMD
2.Once it outputs the following, there is no more new text output to the console
···
2022-07-02 21:12:38,657 main WARN Advanced terminal features are not available in this environment
[21:12:39 [36;1mINFO[m] [0m[1m******************************************[0m
[21:12:39 [36;1mINFO[m] [0m[1m[0m
[21:12:39 [36;1mINFO[m] [0m[1m加载 Geyser 中, 版本 1.4.0-SNAPSHOT (git-master-139167d)[0m
[21:12:39 [36;1mINFO[m] [0m[1m[0m
[21:12:39 [36;1mINFO[m] [0m[1m******************************************[0m
···

### Expected behaviour

Able to run properly

### Geyser Version

1.4.0-SNAPSHOT (git-master-139167d)

### Minecraft: Bedrock Edition Device/Version

1.17.0.56

### Additional Context

Java：java version "1.8.0_321"

Java(TM) SE Runtime Environment (build 1.8.0_321-b07)

Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

Also try to use Java 17 and OpenJDK 11 to run it,But the results have not changed

OS：windows server 2022 datebase

*Geyser is not updated because our server still needs to use an older version of Minecraft

Other attempts.

I copied the entire folder of Geyser running on the server to my PC and ran it with the above Java8 environment, but it works fine on my computer

Thanks!

**Comment by Camotoy** [comment]
Sorry, we don't support older Geyser versions.
