### ISSUE TITLE
Chests and crafting problems

### ISSUE THREAD

**Issue by Insidi0usAngel** [GeyserMC/Geyser#3111]
### Describe the bug

I am using the latest version of geyser-spigot on paper 1.19, there is a little bug where bedrock users cannot shift click items into chests, drag and drop works or standing on hoppers because on shift click the items get thrown onto the floor infront of player.  Also with crafting tables if a player wants to make any item such as say an iron chestplate they cannot click on the item they want to create - they have to know what the recipe is and place each item into each slot individually - i think this is linked to the shift clicking issue too as its similar.  Is there a way to download previous builds of geyser?  This problem with chests has been present in probably at least the last few geyser builds.

### To Reproduce

On running 1.19 latest paper server, try as a bedrock user to shift click items into a chest
2 try to craft anything you don't know the recipe for

### Expected behaviour

items go into chest
crafting tables where you click on an item and then can craft it without having to drag and drop items onto crafting table

### Server Version and Plugins

This server is running Paper version git-Paper-"9d0650e" (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 9d0650e)
![plugins1](https://user-images.githubusercontent.com/99332317/177057903-7b9ff71e-af65-4e19-86c0-015a3b31da6d.jpg)

### Geyser Dump

https://dump.geysermc.org/mE40gGxd7BZa1rlDjVrkHzTmC450oQrI

### Geyser Version

2.0.4-snapshot git-master-dc810f1 java 1.19 bedrock 1.19.0-1.19.2

**Comment by Camotoy** [comment]
Both of those work for me in a desktop environment. Maybe try with no other plugins besides Geyser and Floodgate? And where did you download Paper from? The versioning there seems off.

**Comment by Konicai** [comment]
> For issues with crafting recipes not holding on the table this was working once I removed all plugins to a backup folder. Interestingly another issue that appears in the console that others have reported (added some x's to protect user identity and cut error down as its quite long):  

If you can figure out specifically which plugin(s) is causing that issue, you can make a new bug report about it specifically

> 05.07 10:28:04 [Server] Startup[10:28:04 ]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@1e347xxx[id=00000000-0000-0000-0009-01fbf42fxxxx,name=_xxx,properties={},legacy=false
    
This issue is tracked here: https://github.com/GeyserMC/Floodgate/issues/329
