### ISSUE TITLE
VoidWorld when warping between worlds then crashes on attempting to warping to spawn

### ISSUE THREAD

**Issue by AgentH14** [GeyserMC/Geyser#3112]
### Describe the bug

From my understanding.. I've un-installed Minecraft Bedrock 1.19.2 so many times now so far at different day at different times of the day, and I still encounter a void world glitch when I warp between game lobbies on my pvp server (SlickZone).  And then eventually after warping back to spawn world, I crash and then my old client game crashes entirely after the fact.  And then sometimes sometimes, when warping between worlds I sometimes get a red screen crash too.  Been at this for a long time and still no fix yet that I can find myself. 

![unknown](https://user-images.githubusercontent.com/17691461/177060982-aab8b9da-0f73-4af2-a6d4-36171a87c0f6.png)
![unknown](https://user-images.githubusercontent.com/17691461/177061054-31d52cf2-d519-4dff-ba92-658850b37dd7.png)

 

### To Reproduce

n/a

### Expected behaviour

No issues when warping between worlds and game lobbies

### Server Version and Plugins

Spigot Software
version: 1.17.1_R01 Java Edition 

Minecraft Bedrock v1.19.2

Geyser-Spigot Version: Latest Support
Geyser-Floodgate: Latest Support

### Geyser Dump

Geyser version 2.0.4-SNAPSHOT (git-master-5d29bda) (Java: 1.19, Bedrock: 1.19.0/1.19.2)

### Geyser Version

Geyser version 2.0.4-SNAPSHOT (git-master-5d29bda) (Java: 1.19, Bedrock: 1.19.0/1.19.2)

### Minecraft: Bedrock Edition Device/Version

Windows 10

**Comment by Camotoy** [comment]
Does this issue still occur?

**Comment by AgentH14** [comment]
> Does this issue still occur?

yes it does as of 8/4/22

**Comment by onebeastchris** [comment]
Does this bug still appear?
If so, please try replicating the issue on a clear setup with no other plugins involved.

**Comment by onebeastchris** [comment]
Closing due to no further response. If the issue persists, please open a new issue with replication steps.
