### ISSUE TITLE
Beacons work for Java but not Bedrock??

### ISSUE THREAD

**Issue by TheGamingPenguin** [GeyserMC/Geyser#3114]
### Describe the bug

Java Players on my server can set the effects the beacon gives out (strength, haste ext.) But Bedrock players can't set them, they can open the GUI and place the ingot in the spot and it seems like its set at first, it then kicks you out of the GUI and the Beacon is same as before with no effect.

### To Reproduce

1. Build a basic beacon (make sure its activated)
2. Open the beacon GUI 
3. Place ingot in the slot
4. Choose a effect (step 3 and 4 can be flipped to no diffference)
5. Click the Checkmark
6. You are then kicked for the GUI and the Effect never procs but instead you lost your resources

### Expected behaviour

As expected from interacting with the beacon after fighting to aquire the resources, and sacrificing a ingot to start it me and muiltiple members of my server never got any of the effects from the beacon.

### Server Version and Plugins

Version: 1.19 or git-Paper-8 (MC: 1.19)
Pluggins: AureliumSkills, floodgate, Geyser-Spigot

### Geyser Dump

https://dump.geysermc.org/ezBkKCb5Jaz8D5u8dfjlMHBrbrvq2XG7

### Geyser Version

2.0.4-SNAPSHOT (git-master-4a9581c)

### Minecraft: Bedrock Edition Device/Version

Mobile (Android), Switch, Switch Lite

**Comment by Camotoy** [comment]
Your Geyser version is outdated. Please update it. (Likely not related but your Paper version should also get an update.)
