### ISSUE TITLE
unable to trade with villagers

### ISSUE THREAD

**Issue by Ramgaming** [GeyserMC/Geyser#3116]
### Describe the bug

when geyserver player are not able to open villagers trade.

### To Reproduce

1. join the server
2. go to any villager
3. try to open villager trade menu
4. it wont open

### Expected behaviour

it should open villager trade

### Server Version and Plugins

This server is running Geyser version 2.0.4-SNAPSHOT (git-master-dc810f1) (Java: 1.19, Bedrock: 1.19.0/1.19.2)

This server is running Paper version git-Paper-409 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c53577e on ver/1.17.1)

Plugins (36): BungeeGuard, ChatColor, ChatManager, Chunky, Citizens, CommandPanels, DiscordSRV, DragonSlayer, EconomyShopGUI, Essentials, GadgetsMenu, GPExtraProtections, GriefPrevention, GSit, Guilds, JFixLectern, LuckPerms, MobEggSpawnerBlocker*, NBTAPI, Pl-Hide-Pro, PlaceholderAPI, ProtocolLib, PvPToggle, SkinsRestorer, spark, TAB, TerraformGenerator, TradeSystem, Vault, ViaBackwards, ViaVersion, Votifier, Vulcan, WorldEdit, WorldGuard, zVoteParty

### Geyser Dump

https://dump.geysermc.org/l7CwURfwyGrkciYzm4TjYjgoisVnLuNc

### Geyser Version

Geyser version 2.0.4-SNAPSHOT (git-master-dc810f1) (Java: 1.19, Bedrock: 1.19.0/1.19.2)

### Minecraft: Bedrock Edition Device/Version

1.19

**Comment by Camotoy** [comment]
Please use this version of ViaVersion: https://ci.viaversion.com/job/ViaVersion/
Thanks!
