### ISSUE TITLE
MC Version Supporot List?

### ISSUE THREAD

**Issue by anar4732** [GeyserMC/Geyser#3117]
### What feature do you want to see added?

So I think we need a list like this:
Geyser Build # - Supported Java Versıon - Supported Bedrock Version

### Are there any alternatives?

idk

**Comment by RednedEpic** [comment]
No. It really serves no benefit since there is no reason to run an outdated Geyser build. If you’re running an older Java server, you can use the ViaVersion plugin.

**Comment by Chew** [comment]
> So you can make like this:
> Geyser Build # - Supported Java Versıon - Supported Bedrock Version - Supported?

U Got it!

| Geyser Build # | Supported Java Version | Supported Bedrock Version | Supported ? |
|----|----|---|--|
| Latest | Latest | Latest | Yes |
| Not Latest | Not Latest | Not Latest | No |

**Comment by anar4732** [comment]
😒
