### ISSUE TITLE
Shortcut instruction

### ISSUE THREAD

**Issue by pcl-aacin** [GeyserMC/Geyser#3118]
### What feature do you want to see added?

In the original server, when the player has the highest permission, an icon will appear on the left side of the chat bar, which can be expanded to quickly use instructions. Could you add a function? Sending a packet makes the client think it has the highest permission to use this shortcut

### Are there any alternatives?

none

**Comment by Camotoy** [comment]
Can you send a screenshot of what you're referring to?

**Comment by pcl-aacin** [comment]
Yes. My idea is to send a data packet to make players think that they have operator permissions to use this function

**Comment by Konicai** [comment]
I don't really think this is suitable within Geyser itself for multiple reasons. This would probably be better as a Geyser extension or a plugin on your server platform. The relevant code for informing the client is [here](https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/session/GeyserSession.java#L1627).

You could also use [Bedrock Forms](https://wiki.geysermc.org/floodgate/forms/) for command shortcuts though. Either code it yourself or use a plugin like [this](https://github.com/kejonaMC/CrossplatForms) (not endorsed or supported by GeyserMC)

**Comment by pcl-aacin** [comment]
Okay, thanks
