### ISSUE TITLE
Scoreboard color code

### ISSUE THREAD

**Issue by 111lzy9** [GeyserMC/Geyser#3120]
### What feature do you want to see added?

When translating the scoreboard for Java Edition to Bedrock Edition, replace & with §

### Are there any alternatives?

Replace & with §, although the Bedrock Edition scoreboard has color, but it results in Java Edition having no color

Please forgive the language error because it is a machine flip

**Comment by Camotoy** [comment]
I'm going to close this due to a lack of information and because something else is probably the issue here... Thanks though.
