### ISSUE TITLE
Bedrock doesn't support custom enchantments (or sweeping edge)

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Geyser#3121]
### Describe the bug

When players is enchanting items with ecoenchants books, it can't work
if is vanilla enchant book, it can work

### To Reproduce

1. Use a Ecoenchants enchant book to enchant a item
2. Can't show the result

### Expected behaviour

It can work

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/68630033/178038095-b3b16419-a749-487a-8f19-01d3cad1e085.png)

### Server Version and Plugins

![image](https://user-images.githubusercontent.com/68630033/178038173-e7e8b3c0-9d27-45a1-a292-2d5a62da77b6.png)

![image](https://user-images.githubusercontent.com/68630033/178038196-c076b382-7a1b-4457-aac5-a2669e3c88f5.png)

### Geyser Dump

https://dump.geysermc.org/XKyq1LpAAkrtn2z0q1aeojRRfhXvrug0

### Geyser Version

2.0.4-SNAPSHOT (git-master-dc810f1)

### Minecraft: Bedrock Edition Device/Version

1.19.2

### Additional Context

I use machine translation

**Comment by Camotoy** [comment]
There's probably nothing we can do here - Bedrock Edition does not allow the anvil output to be controlled server-side.

**Comment by DJelly4K** [comment]
> There's probably nothing we can do here - Bedrock Edition does not allow the anvil output to be controlled server-side.

Can he trick the Bedrock Edition into thinking it's a vanilla enchantment?

**Comment by hausemaster3734** [comment]
> > There's probably nothing we can do here - Bedrock Edition does not allow the anvil output to be controlled server-side.
> 
> Can Geyser trick the Bedrock Edition into thinking it's a vanilla enchantment?

The geyser can imitate an anvil with a fake inventory.

**Comment by onebeastchris** [comment]
Given that this is a can't fix, I'll close this in favor of it being documented on our wiki page:
https://wiki.geysermc.org/geyser/current-limitations/

For this issue specifically, unofficial third-party plugins such as e.g. https://modrinth.com/plugin/geyser-recipe-fix could be used as workarounds. But, sadly, unless Bedrock ends up adding custom enchantments, this is a can't fix on Geysers end.
