### ISSUE TITLE
Cant use a beacon

### ISSUE THREAD

**Issue by zap8600** [GeyserMC/Geyser#3123]
### Describe the bug

Tried to make a beacon. Was kicked from the server with the error message in the screenshot.

### To Reproduce

Open the beacon menu
Select an effect
Put in an item 
Confirm

### Expected behaviour

I should have haste and still be in the game.

### Screenshots / Videos

![Screenshot_20220709-111916_Minecraft](https://user-images.githubusercontent.com/95487746/178114337-cc34312c-7066-4f9f-852f-6a4280820e7c.jpg)

### Geyser Version

I'm not sure. 

### Minecraft: Bedrock Edition Device/Version

1.19.0 Mobile

**Comment by Konicai** [comment]
Update Geyser.
