### ISSUE TITLE
Bedrock crashando ao usar comando

### ISSUE THREAD

**Issue by sadreidelas** [GeyserMC/Geyser#3124]
### Describe the bug

Ao digitar "/" no chat o jogo congela e as vezes crasha na versão de celular

### To Reproduce

Tenha muitos comandos disponíveis 
Logue usando um celular
E digite "/" no chat
Meu servidor[thecraftmc.enxada.host:10024]

### Expected behaviour

Bom nem preciso falar

### Screenshots / Videos

Não consigo video pq sempre crasha
![Screenshot_20220619-173228_Minecraft](https://user-images.githubusercontent.com/96682202/178122939-51ca3c8f-69f3-4988-a418-14dbb8ad7426.jpg)

### Server Version and Plugins

1.19

### Geyser Dump

https://dump.geysermc.org/SLWqXcNr6uzoIS2iKVryqkqa2oU8JXaf

### Geyser Version

2.0.4-SNAPSHOT (git-master-dc810f1)

### Minecraft: Bedrock Edition Device/Version

Celular

### Additional Context

Não tem MT oq falar só sei que tem mts comandos disponiveis

**Comment by Konicai** [comment]
Please do bug reports or feature requests in english. If you have to use Google Translate or something similar thats alright
