### ISSUE TITLE
Players cannot join the sub server

### ISSUE THREAD

**Issue by xiaobao4909** [GeyserMC/Geyser#3129]
### Describe the bug

Players cannot join the sub server

### To Reproduce

Players join specific sub servers

### Expected behaviour

No error is reported when players join normally

### Screenshots / Videos

![Uploading image.png…]()

### Server Version and Plugins

![Uploading image.png…]()

### Geyser Dump

https://dump.geysermc.org/1HSJVzzXgNiw30GytRGTEXCqrLjPuyss

### Geyser Version

Build #1146

### Minecraft: Bedrock Edition Device/Version

1.19.2

**Comment by Jens-Co** [comment]
Can you please reupload the pictures? You probably posted the issue before the images were properly uploaded.

Also provide us some proxy server logs which you can upload using https://mclo.gs.
Thanks.

**Comment by xiaobao4909** [comment]
> 你能重新上传图片吗？您可能在正确上传图像之前发布了问题。
> 
> 还要向我们提供一些代理服务器日志，您可以使用 https://mclo.gs 上传这些日志。 谢谢。

ok
