### ISSUE TITLE
Custom entity tracking range

### ISSUE THREAD

**Issue by Lotzyprod** [GeyserMC/Geyser#3130]
### What feature do you want to see added?

Spigot have options to show specified entity types in specified range around player (trackingRange)
I suggest to add same feature to Geyser, because client has a large lags with high amount of entities (even if they are in caves)
Lags are happening not only on mobile devices, also on PC (I think its client problems).
Of course, we are talking about servers with an increased spawnrate.

For example:
if tracking range for monsters is 128 - its cause lags
but if tracking range is 48 - all is good

### Are there any alternatives?

First alternative - decrease values of tracking range in spigot config, but this will also affect java players (not cool)
Second alternative - decrease spawn rates, but this will also affect all gameplay (not cool)
Third alternative - handle sent packets , cancel send packet PacketPlayOutSpawnEntity by distance between player and entity.
Every % ticks check entities around player and send PacketPlayOutEntityDestroy if entity is too far and
send PacketPlayOutSpawnEntity if entity close

**Comment by Kas-tle** [comment]
Closing as not planned based on Camo's response.
