### ISSUE TITLE
Can't drop items

### ISSUE THREAD

**Issue by Manuel11243** [GeyserMC/Geyser#3132]
### Describe the bug

In my server I can't drop any block on the hotbar or in the inventory

### To Reproduce

1.start a server
2. Try to drop something

### Expected behaviour

The item drops

### Geyser Version

#1146

### Minecraft: Bedrock Edition Device/Version

Android 1.19.10

**Comment by Camotoy** [comment]
Fixed in 109e1c0.

**Comment by MaxRingnalda** [comment]
Hello! I am currently running a server with Geyser and some of my players, that use the mobile version of Bedrock, are unable to drop items by tapping and holding the item on their Hotbar as they usually would. People on Bedrock Pc are able to but mobile is not. Would this be the same issue?

https://dump.geysermc.org/ILoPoBNuARTHVC4w3IrwWXKz9XmD1pZ8

**Comment by Camotoy** [comment]
You are not using the latest Geyser version.

**Comment by Camotoy** [comment]
Yes.

**Comment by MaxRingnalda** [comment]
Thank you. Uninstalled the one I had and reinstalled that one and the issue was fixed. Thanks again
