### ISSUE TITLE
[Use Chinese language]空指针 Failed to parse message

### ISSUE THREAD

**Issue by xiaobao4909** [GeyserMC/Geyser#3133]
### Describe the bug

1.出现空指针 Failed to parse message

### To Reproduce

1.空指针情况未知

### Expected behaviour

1.解决空指针 Failed to parse message 问题

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/92622663/178660883-2eeba289-6a2f-43d3-b074-f84c15803aca.png)

### Server Version and Plugins

使用Geyser独立版

### Geyser Dump

https://dump.geysermc.org/JmGsuRGtEWvHvgKRYTZRO6D6qw0DgzGz

### Geyser Version

Build #1147

### Minecraft: Bedrock Edition Device/Version

1.19.2

### Additional Context
Log:
[2022-07-13-1.log.gz](https://github.com/GeyserMC/Geyser/files/9108209/2022-07-13-1.log.gz)

**Comment by Camotoy** [comment]
Please provide the `logs/latest.log` file from the standalone Geyser folder.

**Comment by xiaobao4909** [comment]
我使用Microsoft的openjdk Java17

**Comment by xiaobao4909** [comment]
> 请提供独立间歇泉文件夹中的文件。`logs/latest.log`

已完成

**Comment by Jens-Co** [comment]
Close this issue due to lack of provided information.
