### ISSUE TITLE
Echo Shards incorrectly Translated 

### ISSUE THREAD

**Issue by RealFinePoint** [GeyserMC/Geyser#3135]
### Describe the bug

When picking up echo shards, the bedrock player instead sees Trader Llama Spawn Eggs.

### To Reproduce

1. Have bedrock player pick up what used to be echo shards (They were in a chest prior for us)

### Expected behaviour

The echo shards remain echo shards

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/105620526/178798501-2121a44e-a8a1-415a-a48b-95b3bf968f0a.png)
![image](https://user-images.githubusercontent.com/105620526/178798465-0a8222c5-9c6b-4275-963c-ad5d4bb0dcba.png)

### Geyser Dump

https://dump.geysermc.org/BUOhAZwASoUj9cggwcNVVHcrTqnrD85N

### Geyser Version

2.0.5-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.10, Windows

**Comment by sctigercat1** [comment]
I recently did a PR likely to address this issue and it has been merged into Geyser master. Can you see if the bedrock player is still experiencing this issue?

**Comment by Konicai** [comment]
Fixed in 467286060c3074e0ee237246a40eb3d308cc0ba9
