### ISSUE TITLE
[Extension Branch]Пакеты текстур не отображаются должным образом

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Geyser#3137]
### Describe the bug

Texture packs are displayed normally, but features with custom texture pack items are not available
For example, slime items, slime guide books will not work properly. On Bedrock Edition, players cannot use right-click or long-press, but the materials of books are normal.

### To Reproduce

1.Install geyser extensions fork in bungee
2.Install slimefun plugins in back server
3.Use 1.19.10 join server and use slimefun guide book
4.Can't use guide book(All items with textures are invalid)

### Expected behaviour

The slime guide book should be opened normally, but cannot be opened

### Server Version and Plugins

geyser https://github.com/GeyserMC/Geyser/actions/runs/2657308213
purpur 1.19.0-1696

### Geyser Version

Geyser - extensions - 46faf02

### Minecraft: Bedrock Edition Device/Version

1.19.10 in win11

**Comment by klxf** [comment]
I also encountered this problem. Here are some additions to this question:
Open debug-mode, using slimefun guide book the following message appears in the console:
```
[Geyser-BungeeCord] Is player data valid? true
[Geyser-BungeeCord] Could not find packet for ClientToServerHandshakePacket
[Geyser-BungeeCord] Could not find packet for ClientCacheStatusPacket
[Geyser-BungeeCord] PlayerName's held item has desynced! Expected: 521 Received: 1469
[Geyser-BungeeCord] Packet: InventoryTransactionPacket(legacyRequestId=0, legacySlots=[], actions=[], transactionType=ITEM_USE, actionType=1, runtimeEntityId=0, blockPosition=(0, 0, 0), blockFace=255, hotbarSlot=5, itemInHand=ItemData(id=1469, damage=0, count=1, tag={
  "CustomModelData": 2200001i,
  "PublicBukkitValues": {
    "slimefun:slimefun_guide_mode": "SURVIVAL_MODE"
  },
  "display": {
    "Lore": [
      "",
      "§r§e右键 §r§8? §r§7浏览物品",
      "§r§eShift + 右键 §r§8? §r§7打开 设置 / 关于"
    ],
    "Name": "§r§aSlimefun 指南 §r§7(箱子界面)"
  }
}, canPlace=[], canBreak=[], blockingTicks=0, blockRuntimeId=0, usingNetId=false, netId=0), playerPosition=(-4994.4546, 163.62001, 6282.5923), clickPosition=(0.0, 0.0, 0.0), headPosition=null, usingNetIds=false, blockRuntimeId=0)
```

**Comment by DJelly4K** [comment]
![image](https://user-images.githubusercontent.com/68630033/179455341-7d446bd8-07a3-4938-987e-f9ce22b55b1b.png)
