### ISSUE TITLE
Lecterns don't work on 1.19.10

### ISSUE THREAD

**Issue by IceWaffles** [GeyserMC/Geyser#3138]
### Describe the bug

Bedrock players cannot open lectures.

### To Reproduce

1. Have a bedrock player join (preferably one a phone/mobile device as this is how user found the bug)
2. Try and open a lecturn

### Expected behaviour

They can open lecturns.

### Geyser Version

This server is running Geyser version 2.0.5-SNAPSHOT (git-master-109e1c0) (Java: 1.19, Bedrock: 1.19.0/1.19.2 - 1.19.10)

### Minecraft: Bedrock Edition Device/Version

1.19.10 on iPhone

**Comment by Camotoy** [comment]
This issue is still a thing as of 1.19.51 and I have no idea what's going on. To be fair, we're already hacky with lecterns, but I've tried sending the same packets as a vanilla Bedrock server to no avail. Perhaps it is related, somehow, to the subchunk system.

**Comment by Kas-tle** [comment]
Something very odd is going on here... in addition to the lectern not working, right clicking it causes you to be unable to open your inventory until you disconnect from the server.

**Comment by Kas-tle** [comment]
This is how pocketmine sends the data... to my knowledge they don't use the subchunk system yet? But their lecterns seem to work.

```
[CLIENT BOUND]  -  UpdateBlockPacket(flags=[NETWORK], blockPosition=(255, 73, 250), runtimeId=10718, dataLayer=0)
[CLIENT BOUND]  -  BlockEntityDataPacket(blockPosition=(255, 73, 250), data={
  "id": "Lectern",
  "x": 255i,
  "y": 73i,
  "z": 250i,
  "hasBook": 1b,
  "page": 0i,
  "book": {
    "id": 387s,
    "Count": 1b,
    "Damage": 0s,
    "tag": {
      "pages": [
        {
          "text": "somebook",
          "photoname": ""
        },
        {
          "text": "",
          "photoname": ""
        }
      ],
      "generation": 0i,
      "author": "Author Unknown",
      "title": "somebook"
    }
  },
  "totalPages": 2i
})
```
I notice they are using the id short instead of name string as that issue suggests... though trying to emulate this in Geyser still yields the same results :/
Perhaps I should try to just send it exactly?

**Comment by EagleDotNet** [comment]
I have the same problem, bedrock players via GeyserMC can't open lecture books, but java players can open lecture books!!

**Comment by WR8187** [comment]
this is still broken.. I'm looking into it .. maybe I can figure it out
