### ISSUE TITLE
Players’ camera effects didn’t be lifted after Authme logged in

### ISSUE THREAD

**Issue by fengye1003** [GeyserMC/Geyser#3139]
### Describe the bug

[translated from Chinese]
When I logged into the server using the Authme plugin, the visual effects in the unlogged-in state were not lifted, resulting in a very small view of the client. Only the Bedrock client of v.1.19.10 has this problem, after testing, both the Java client and the Bedrock client of v.1.19.0 have not reproduced this problem.

[Chinese version]
当我使用Authme插件登录到服务器后，未登录状态下的视觉效果未被解除，导致客户端的视野处于非常小的状态。仅有v.1.19.10的Bedrock客户端出现了此问题，经测试，Java客户端与v.1.19.0的Bedrock客户端均未复现此问题。

### To Reproduce

1.Install and run Paper Minecraft Server v.1.19(git-Paper 29)
2.Install plugin “AuthMe-5.6.0-SNAPSHOT”
3.Run Geyser 2.0.5-SNAPSHOT
4.Connect to server and login.(By Bedrock MC v.1.19.10)
5.Logged in but the effect haven't be lifted

### Expected behaviour

Login successful and the effect be lifted.

### Screenshots / Videos

Test:v.1.19.10: https://pan.huang1111.cn/api/v3/file/source/1578854/Bedrock_1_19_10_test.MP4?sign=jA5oGt_6E0PAp4uorOofauoG4CpWWe43cveftpuLvho%3D%3A0
(Problem)

Test v.1.19.0:
https://pan.huang1111.cn/api/v3/file/source/1578852/Bedrock_1_19_0_test.MP4?sign=_zPbWDikBk0NjvlA35TPeCdI2UDNEJtAiD0eYCKfQ7I%3D%3A0
(Expected)

Test Java v.1.19:
https://pan.huang1111.cn/api/v3/file/source/1578853/Java_1_19_test.mp4?sign=HNCid7cS1AE6GQWB5O7S0niIEPyBYw_rNiq7F448tDM%3D%3A0

### Server Version and Plugins

Java version server can be downloaded at:
https://pan.huang1111.cn/api/v3/file/source/1578859/server.jar?sign=3KzZ0YrSraQk4HpqrxQIiPYfYqDqQsPkS_IZLpB7kqI%3D%3A0
(git-Paper-29 MC:1.19)

Plugin “AuthMe” can be downloaded at:
https://pan.huang1111.cn/api/v3/file/source/1578862/AuthMe-5.6.0-SNAPSHOT.jar?sign=mipavbErFnxeW-Ssi_wL2RBIsyqlm_-qLxTyNDPH6uE%3D%3A0

### Geyser Dump

https://dump.geysermc.org/RYadb34dXAv7jNNQ5REYuMOZqOp5ZU95

### Geyser Version

2.0.5-SNAPSHOT (git-master-f6f886)

### Minecraft: Bedrock Edition Device/Version

1.19.10 iPad OS

### Additional Context

Paper server’s “latest.log” can be downloaded at:
https://pan.huang1111.cn/api/v3/file/source/1578857/latest.log?sign=iNtF2yY4MLEZPbCcN-pG7nGKoTIQgFM0oI7V53THgME%3D%3A0

**Comment by fengye1003** [comment]
I discovered that if I change the setting "allowMovement" to "true" in the config file of AuthMe , the effects can be removed.
But the players who havn't logged in can move around....
I don't know if that helps or not...

*The problem in #3140 can't be solved by adding args,too...
Finally , thanks for your reply!

**Comment by DominikSLK** [comment]
I also have this issue

**Comment by sebastianjnuwu** [comment]
in my case I use login , but I didn't change his version only of the geyser

**Comment by Camotoy** [comment]
Can anyone replicate this issue without a login plugin? I just don't want to download one unless I have to.

**Comment by sebastianjnuwu** [comment]
ok

**Comment by adalmo** [comment]
nope even i tried to set allowmovement to true with bilnd to false it doesn't working

**Comment by DominikSLK** [comment]
> Can anyone replicate this issue without a login plugin? I just don't want to download one unless I have to.

player.setWalkSpeed(0.0f);

**Comment by Camotoy** [comment]
Thanks.

**Comment by FortiethSwing61** [comment]
How can I use that player.setWalkSpeed(0.0f)?

**Comment by fengye1003** [comment]
> How can I use that player.setWalkSpeed(0.0f)?

The bug was fixed in the latest version of Geyser.
Just download the latest package and upgrade it.

**Comment by NovaPixell** [comment]
Hi, I have this issue also. But not using AuthMe or similar.. When a players falled back to a server (like bungeecord hub server)
