### ISSUE TITLE
玩家不显示血条和食物值

### ISSUE THREAD

**Issue by xiaobao4909** [GeyserMC/Geyser#3141]
### Describe the bug

玩家不会显示血条和食物值 这将造成玩家无法预判自己是该逃跑还是打架

### To Reproduce

玩家加入服务器

### Expected behaviour

正常显示血条和食物值

### Screenshots / Videos

无

### Server Version and Plugins

我使用了独立版Geyser和BungeeCord群组服务器

### Geyser Dump

https://dump.geysermc.org/serqm1aK9ftcNx5CHGM5JmaomJDb3H3z

### Geyser Version

Build #1147

### Minecraft: Bedrock Edition Device/Version

1.19.2

### Additional Context

Logs:
[2022-07-14-1.log.gz](https://github.com/GeyserMC/Geyser/files/9117025/2022-07-14-1.log.gz)

**Comment by DongShaoNB** [comment]
Have you noticed that you ask questions in a different language than others ?

**Comment by xiaobao4909** [comment]
> 你有没有注意到你用与其他人不同的语言提问？

Yes, but isn't this allowed?
