### ISSUE TITLE
Resourcepack hotloading

### ISSUE THREAD

**Issue by TypicalShavonne** [GeyserMC/Geyser#3143]
### Describe the bug

Putting a new resourcepack into packs folder while geyser is running and there is another pack already in there would cause none player able to join the server

### To Reproduce

1. Put this [pack](https://cdn.discordapp.com/attachments/917771012198780948/997488521583534202/geysertestpack1.zip) into packs folder
2. Start geyser
3. Overdrive the geysertestpack1.zip with this [pack](https://cdn.discordapp.com/attachments/917771012198780948/997488521885536266/geysertestpack2.rar)
4. Join the server

### Expected behaviour

Player join the server and download pack2 normally

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/53472591/179228899-597c9b2c-4dab-4e24-9807-4e3d88714b16.png)

### Server Version and Plugins

[20:06:17 INFO]: Velocity 3.1.2-SNAPSHOT (git-74edac96-b153)
[20:06:17 INFO]: Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[20:06:17 INFO]: velocitypowered.com - GitHub

### Geyser Version

[20:06:35 INFO]: This server is running Geyser version 2.1.0-SNAPSHOT (git-local/dev-240af3c) (Java: 1.19, Bedrock: 1.19.0/1.19.2 - 1.19.10)

### Minecraft: Bedrock Edition Device/Version

1.19.10

### Additional Context

I downloaded this version from jenkins branch feature/extensions latest

**Comment by Kas-tle** [comment]
Hot loading has (I believe) never been supported so this is more a feature request. Also I assume you meant 1.19.10 for the version?

**Comment by TypicalShavonne** [comment]
yea, sorry, i fixed it

**Comment by Konicai** [comment]
I cannot say whether or not this will be added to Geyser. However, `SessionLoadResourcePacksEvent` is available within the geyser api, allowing developers to choose which resource packs a client should be sent on the fly.

**Comment by onebeastchris** [comment]
You can use `/geyser reload` to reload the packs that Geyser reads from the pack folders. Hotloading resource packs from the packs folder can't be implemented, as that could result in a multitude of issues, such as an interruption while a pack is being sent to the Bedrock client.
However, https://github.com/GeyserMC/Geyser/pull/4205 will implement hot-loading for resource packs specified via url - as Geyser will then be able to provide a cached copy of the pack if the download fails.
