### ISSUE TITLE
Scaffolding not being placed after a few blocks up

### ISSUE THREAD

**Issue by DuneSciFye** [GeyserMC/Geyser#3144]
### Describe the bug

After placing scaffolding for a few blocks up, it stops to be placing, and the block placement is cancelled. Check the video for a better description

### To Reproduce

Place scaffolding

### Expected behaviour

It should keep being placed

### Screenshots / Videos

https://streamable.com/gje8d0
Using streamable since I can't directly upload it, the file is too big and the max for github is 10MB

### Geyser Version

I'm not sure, its on the velocity server and I'm not sure how to check.

**Comment by onebeastchris** [comment]
Unable to replicate. If this is still an issue, send a geyser dump.
Also, try sneaking while in scaffolding to build upwars
