### ISSUE TITLE
Cant open villager trade gui

### ISSUE THREAD

**Issue by ASAllenShih** [GeyserMC/Geyser#3148]
### Describe the bug

Cant open villager trade gui when right click/use the villager and you will cant open the inventory

[Geyser-Spigot] 下游數據包錯誤！ readerIndex(146) + length(1) exceeds writerIndex(146): PooledUnsafeDirectByteBuf(ridx: 146, widx: 146, cap: 146)

### To Reproduce

1.Join Server
2.Try right click/use the villager
3.Try open the inventory

### Expected behaviour

Open villager trade gui

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/65409535/179399279-af2ca706-9a28-4fd3-b74e-4535c5732582.png)
![image](https://user-images.githubusercontent.com/65409535/179399383-f519d998-3cb2-442f-8dc2-446597bcae64.png)

### Server Version and Plugins

This server is running Paper version git-Paper-216 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 30cb7d0)

Plugins (66): AdvancedBan, AutoMessager, ChestCommands, ChestShop, Citizens, ClearLag, CMILib, CommandNPC, ConsoleSpamFix, CoreProtect, CrackShot, CrazyAuctions, CrossplatForms, CyberLevels, DiscordSRV, dynmap, EconomyShopGUI, Essentials, F3Name, FarmProtect*, floodgate, Geyser-Spigot, GeyserPlaceholders, GeyserUpdater, GSit, ImageOnMap, JukeBox, KotLib, LPC, LuckPerms, Maintenance, McEventCore, mcMMO, MinecartSpeedPlus*, Multiverse-Core, MyPet, NoteBlockAPI, OpenInv, PacketWrapper*, PlaceholderAPI, PlayerStatueBuilderX, ProtocolLib, Residence, Scoreboard-revision*, ServerlistMOTD*, ServerRestorer, SetHomes, Shopkeepers, SkBee, SkQuery, Skript, skript-placeholders*, spark, SpectateCamera, TabList, Telecom, UltimateAutoRestart, UnlimitedAnvil, UnlimitedLava, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WorldEdit

### Geyser Dump

https://dump.geysermc.org/cSIIHrnVXXzAHRtSNAmu3SPUkxOzxx5W

### Geyser Version

2.0.5-SNAPSHOT (git-master-192ea1a)

### Minecraft: Bedrock Edition Device/Version

1.19.10, iOS, Windows

**Comment by Camotoy** [comment]
Please use the ViaVersion builds located at https://ci.viaversion.com/job/ViaVersion/ to solve this issue. Thanks!
