### ISSUE TITLE
Wrong FOV on bedrock 1.19.10

### ISSUE THREAD

**Issue by disymayufei** [GeyserMC/Geyser#3149]
### Describe the bug

When I updated my Minecraft Bedrock Edtion to version 1.19.10, I found that the FOV is abnormal：it looks like I have a high-level slowness effect (although I don't have it). Only version 1.19.10 has this bug, 1.19.2 or below are all no problem.

### To Reproduce

1. Using the version 1.19.10 (Bedrock Editon)
2. Joining the server which running Geyser-Bungeecord 2.0.5-SNAPSHOT
3. The bug will appear!

### Expected behaviour

a normal FOV like this:
![JE](https://user-images.githubusercontent.com/72013933/179416237-e3828132-7104-4003-b136-5b8950dd4196.png)

### Screenshots / Videos

on Bedrock Editon (bug):
![BE](https://user-images.githubusercontent.com/72013933/179416204-2657ac38-4c36-4d59-9476-77bbf64ebe60.png)

on Java Editon (normal)
![JE](https://user-images.githubusercontent.com/72013933/179416223-3f24b8fd-1927-484b-9a8f-f6ee7a8a731d.png)

### Geyser Version

2.0.5-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.10

**Comment by Camotoy** [comment]
It sounds like this is the same issue as #3139. Therefore I'm closing this. Thanks!
