### ISSUE TITLE
Lỗi không thể click vào npc khi dùng minecraft bedrock

### ISSUE THREAD

**Issue by vudz2310** [GeyserMC/Geyser#3152]
### Describe the bug

tôi không thể click vào npc khi chơi bằng bedrock 
Biểu hiện khi tôi click vào npc 
đầu tiền click vào npc sẽ không hiện vật phẩm để tôi trade
tiếp theo tôi không thể mở đc inv của mình 

### To Reproduce

tôi xin lỗi , tôi không thể quay video cho các bạn xem được 

### Expected behaviour

Tôi muốn khi tôi click vô npc nó sẽ không bị lỗi nữa 
và có thể mở vào sử dụng như bình thường 

### Screenshots / Videos

https://user-images.githubusercontent.com/109365543/179702161-b4045e14-3cd0-4303-ad4c-3d1140494b94.mp4

 thể quay video cho các bạn xem được 

### Server Version and Plugins

phiên bản máy chủ tôi là
từ 1.12.2-1.9

### Geyser Dump

 tôi xin lỗi , tôi không thể quay video cho các bạn xem được 

### Geyser Version

1.2.0

### Minecraft: Bedrock Edition Device/Version

1.19.0.2

**Comment by AnhNguyenlost13** [comment]
1. Bạn hãy cho tôi link GeyserDump (`/geyser dump`)
2. Bạn có thể cho con NPC đó một nghề được không?
3. Bạn hãy ghi chính xác phiên bản server (`/ver`) trong phần **Server Version and Plugins**
4. Bạn hãy list các plugin trong phần **Server Version and Plugins**

**Comment by Hahaa13** [comment]
Bạn đang sử dụng shopkeepers ?
Nếu thế thì 90% là do viaverson và bạn hãy xài bản viaverson của dev-build để có thể fix lỗi này nha
Viết tiếng việt ông hay vcl :))

**Comment by TypicalShavonne** [comment]
b có thể update https://ci.viaversion.com/job/ViaVersion/ lên bản mới nhất nhé ^^

**Comment by vudz2310** [comment]
> b có thể cập nhật https://ci.viaversion.com/job/ViaVersion/ up bản mới nhất nhé ^^

tôi đã cập nhật lên pb mới nhất

**Comment by vudz2310** [comment]
> 

npc đó tôi dùng plugin citizens , và plugin shopkeeper , nên k thể cho nó học nghề được 
Phiên bản tôi sử dụng là 1.17.1
hỗ trợ join đc từ phiên phản 1.12.2 - 1.19

**Comment by Konicai** [comment]
If you want your issues resolved faster, please use english: https://www.deepl.com
