### ISSUE TITLE
Cape Servers a bit Broken on Offline Mode

### ISSUE THREAD

**Issue by Volcan4436** [GeyserMC/Geyser#3157]
### Describe the bug

when i use skin restorer sometimes a user's optifine cape won't load till that player logs onto the server while that bedrock user is online.

### To Reproduce

1. login as a bedrock user on offline mode
2.  Use Skin Restorer to change the user skin to a user with an optifine cape
3. cape won't load
4. log onto the user you just set their skin as
5. cape will now appear

### Expected behaviour

i would expect the capes to load even on offline mode

### Geyser Version

2.0.5-SNAPSHOT (git-master-f6f8886)

### Minecraft: Bedrock Edition Device/Version

All bedrock versions

### Additional Context

it seems to only be an issue when the skin is changed which then causes geyser to pull a cape from a cape server

**Comment by Kas-tle** [comment]
Offline mode is not officially supported and as such some features may not work correctly.
