### ISSUE TITLE
Cannot see Bedrock players' skin even though it is a normal skin type

### ISSUE THREAD

**Issue by Shodwriter** [GeyserMC/Geyser#3159]
### Describe the bug

No Bedrock skins can be seen for Java clients; instead, the Steve skin is displayed. This issue occurs with all skins even if the Bedrock skin is a normal skin type and does not have any special features (e.g. 3d). However, other Bedrock clients can see each others' skins as normal.

### To Reproduce

Connect to a Java server with a Bedrock client with a normal-type skin that is different from the default Steve skin.
Connect to the same Java server with a Java client.

### Expected behaviour

The Bedrock skin should be visible to Java clients.

### Screenshots / Videos

![Bedrock client POV](https://user-images.githubusercontent.com/93199403/179980849-873040a9-e7af-47f7-b306-76f2e1b6cbfc.png)
![Java client POV](https://user-images.githubusercontent.com/93199403/179980855-19be7abe-fc24-4041-88f7-69675a5d2d05.png)

### Server Version and Plugins

Current: git-Purpur-1721 (MC: 1.19)*
Previous: git-Purpur-1632 (MC: 1.18.2)
* You are running the latest version
![List of plugins](https://user-images.githubusercontent.com/93199403/179979041-ed17be43-a952-4ca3-b28e-db8be561731e.JPG)

### Geyser Dump

https://dump.geysermc.org/Lv6YJEk9QffHpjLhjAdSEKsAvaABVg13

### Geyser Version

2.0.5-SNAPSHOT (git-master-f6f8886)

### Minecraft: Bedrock Edition Device/Version

1.19.10, Windows 10

**Comment by Michael-A-Sloan** [comment]
This happens to be a bunch as well.

**Comment by LimeDev8756** [comment]
same here half the time i join my server it doesnt have my skin

**Comment by Almighty-Shogun** [comment]
> same here half the time i join my server it doesnt have my skin

I have the same issue. I eventually kinda gave up on fixing it😂

**Comment by LimeDev8756** [comment]
im stupid so im probably wrong but i think the system geyser uses to give bedrock players the skin files might not be the greatest or its overwelled which would make sense

**Comment by Camotoy** [comment]
Skin issues are tougher to fix just because of the way everything is configured at the moment. Hopefully with the Geyser-Floodgate merge that'll be incoming at some point in the future we'll be able to streamline some elements of how we apply skins.

**Comment by Camotoy** [comment]
The GeyserSkinManager plugin *may* be able to resolve some skin issues. Just read the README for setup.

**Comment by onebeastchris** [comment]
Is this still an issue with the latest versions of geyser and floodgate?

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
