### ISSUE TITLE
Client stuck on loading screen

### ISSUE THREAD

**Issue by SnowmanFTW** [GeyserMC/Geyser#3161]
### Describe the bug

Every time a bedrock client switches instances, the loading screen with Building Terrain flashes then gets stuck.

### To Reproduce

1. Start a velocity server
2. Start the minestom server below and add 2 worlds "spawn" and "mines"
3. Link them
4. Join and type /world mines
5. Enjoy lol

### Expected behaviour

Supposed to tp between them without the screen getting stuck on the loading screen

### Geyser Dump

https://dump.geysermc.org/x5UGOmPe9ZI3fHsp2TetKTtEBMfulKjK

### Geyser Version

2.0.5-SNAPSHOT (git-master-109e1c0)

### Minecraft: Bedrock Edition Device/Version

1.19.10

### Additional Context

Here is the repo with the server for you to compile and run the server https://github.com/SnowmanFTW/GeyserIssue
Or download it directly here https://www.mediafire.com/file/g8v0whnzaakpruq/GeyserIssue-1.0-SNAPSHOT-all.jar/file

**Comment by 56738** [comment]
@TropicalShadow Minestom sends people to the nether and back when switching dimensions, you need to register `minecraft:the_nether` in the Minestom dimension type manager.

**Comment by HEROOSTECH** [comment]
https://github.com/CityWideMC/Geyser-Utils i fixed it here (i think)

**Comment by Camotoy** [comment]
SnowmanFTW, thanks for the repository to replicate the issue, and thanks for your patience.
