### ISSUE TITLE
Bedrock players getting sent to random nether coords instead of nether portals

### ISSUE THREAD

**Issue by Marciellemiavette** [GeyserMC/Geyser#3162]
### Describe the bug

Bedrock players goes through nether portal(on nether roof). Instead of coming out at the portal, they just appear at random coords in the nether

### To Reproduce

1. Be a Bedrock player connecting to a Spigot Java server
2. Go through a portal that leads to the nether roof
3. You are now at random coords on nether roof instead of portal exit

### Expected behaviour

Player goes through nether portal, comes out at another nether portal

### Geyser Dump

https://dump.geysermc.org/JXdRmnY9XdBYA1xT2rQuUm32o34kOnkc

### Geyser Version

2.0.5-SNAPSHOT (git-master-192ea1at)

### Minecraft: Bedrock Edition Device/Version

1.19.10, android

**Comment by Camotoy** [comment]
This doesn't sound like our issue - we don't touch server behavior, so it doesn't make sense that nether portal travel coordinates would be modified as such.

**Comment by onebeastchris** [comment]
closing due to no further activity & suspected server behavior
