### ISSUE TITLE
Items disappear while crafting

### ISSUE THREAD

**Issue by Elektrodemon0** [GeyserMC/Geyser#3166]
### Describe the bug

if you try to craft something the item disappears. I uploaded a Video which can explan it a little bit better.

 

### To Reproduce

Get some oak_log
Open your craft inventory
Craft planks multiple times

### Expected behaviour

It would be nice to fix this issue. I don't know if this has something to do with the server but I think it's a bug from the plugin.

### Screenshots / Videos

[Uploading Aufnahme_2022_07_22_21_43_18_554.mp4…](https://user-images.githubusercontent.com/107434317/180518648-f4480916-fcbe-4993-a9dc-80547bae92b5.mp4
)

### Server Version and Plugins

I'm using bungeecord and paper 1.16.5.

### Geyser Dump

https://dump.geysermc.org/6LHyzPkY1PnenAouXm6gieoNI6rL0S47

### Geyser Version

Build 1153

### Minecraft: Bedrock Edition Device/Version

PC: 1.19.1

**Comment by Elektrodemon0** [comment]
https://user-images.githubusercontent.com/107434317/180518648-f4480916-fcbe-4993-a9dc-80547bae92b5.mp4

**Comment by Konicai** [comment]
Can you update ViaVersion and share your plugin list on the paper server, and the result of `/version` on the paper server?

**Comment by unfairDude** [comment]
same bug

**Comment by onebeastchris** [comment]
Is this still an issue with the latest version of Geyser?
