### ISSUE TITLE
False Flying Kick On Bedrock

### ISSUE THREAD

**Issue by LimeDev8756** [GeyserMC/Geyser#3168]
### Describe the bug

Flying in the sky on bedrock then leaving and joining back prevents them from joining because they get kicked because "Flying is not enabled on this server". The bedrock player is in creative mode.

### To Reproduce

1. Set flying in server to false
2. Join on Bedrock
3. Fly up
4. Leave and rejoin

### Expected behaviour

To join the server without being kicked

### Screenshots / Videos

https://user-images.githubusercontent.com/100384210/180645774-62dc5b38-0354-413d-bd71-2205ca9ec3b1.mp4

Very buggy for some reason

### Server Version and Plugins

![image](https://user-images.githubusercontent.com/100384210/180645352-721b6441-08dc-400f-b8e2-145405f82cfb.png)
![image](https://user-images.githubusercontent.com/100384210/180645367-4688b84a-6fb7-4fc7-a9e8-034a8e3b07a4.png)

### Geyser Dump

https//dump.geysermo.org/vpR9XCOex4uojj3zbrFdrhltijygaJ6

### Geyser Version

2.0.5-SNAPSHOT (git-master-3de2b33)

### Minecraft: Bedrock Edition Device/Version

1.19.10, PC and Switch

**Comment by onebeastchris** [comment]
set "allow-flight" to "true" in your server.properties - that'll disable players getting kicked for flying.

**Comment by LimeDev8756** [comment]
yes but this server requires allow-flight to false to prevent hacks and if the bedrock client is in creative it shouldnt kick them

**Comment by TypicalShavonne** [comment]
allow-flight doesnt help you prevent fly hacks

**Comment by LimeDev8756** [comment]
maybe not hacks but mods that allow you to fly in survival do exist
![image](https://user-images.githubusercontent.com/100384210/180841772-17075e85-c2bf-4837-a01d-dd8ab825455b.png)

i dont want griefers either so i need to keep it on

**Comment by onebeastchris** [comment]
well, if you're really worried about that, use an Anti-Cheat plugin.. "allow-flight" has caused issues on my server with geyser on it - like bedrock players being unable to sneak on edges of a slab without getting kicked for "flying".

long story short - enable allow-flight, and if you're really worried about hackers, use a proper anticheat (geyser's wiki has a list of working one's)

**Comment by onebeastchris** [comment]
although yes, it could be argued that bedrock players in creative shouldn't get kicked for flying, since they're in creative

**Comment by LimeDev8756** [comment]
you are right about anti-cheat but since this shouldnt happen it would be a good bug to fix for other users

**Comment by TypicalShavonne** [comment]
https://github.com/GeyserMC/Geyser#whats-left-to-be-addedfixed

**Comment by TypicalShavonne** [comment]
it just caused by geyser not translating player movement perfectly, still some flaws tho

**Comment by TypicalShavonne** [comment]
> maybe not hacks but mods that allow you to fly in survival do exist ![image](https://user-images.githubusercontent.com/100384210/180841772-17075e85-c2bf-4837-a01d-dd8ab825455b.png)
> 
> i dont want griefers either so i need to keep it on

modern cheat clients can easily bypass that

**Comment by LimeDev8756** [comment]
> it just caused by geyser not translating player movement perfectly, still some flaws tho

i wouldnt think this is the issue because minecraft wont kick the player for flying if in creative which the in this case the player is, geyser doesnt modify server behaviour yet you still get kicked so i posted it here to see if there was a possible fix but maybe it isnt geyser, but then again, this is only bedrock

**Comment by TypicalShavonne** [comment]
server ignore that check if you are in creative mode

**Comment by Camotoy** [comment]
Can you try with the latest Geyser version?

**Comment by LimeDev8756** [comment]
seems fixed in the new versions
