### ISSUE TITLE
Unable to trade to villagers

### ISSUE THREAD

**Issue by EpicBirb** [GeyserMC/Geyser#3171]
### Describe the bug

The title says it

### To Reproduce

1. setup floodgate and geyser
2. spawn a villagers with custom trades
3. trade with them on mobile

### Expected behaviour

Should be able to trade with them

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/68750348/180663743-9b220354-36b3-40a1-a1ed-4ea3c042ef76.png)

### Server Version and Plugins

![image](https://user-images.githubusercontent.com/68750348/180663752-8c1bfb9d-6608-4795-9d4b-e5e3cad13fd1.png)

### Geyser Version

2.0.5-SNAPSHOT (git-master-4127300)

### Minecraft: Bedrock Edition Device/Version

1.19.10 MCPE

**Comment by Konicai** [comment]
Provide the plugin that you use to create custom trades please

Also share a geyser dump with `/geyser dump`

**Comment by EpicBirb** [comment]
it's not a plugin, its more of a datapack i found. it gave me a villager spawn egg and i just placed it down.

**Comment by Camotoy** [comment]
Please provide that datapack.

**Comment by EpicBirb** [comment]
[bedwars-2-3-e2340.zip](https://github.com/GeyserMC/Geyser/files/9176926/bedwars-2-3-e2340.zip)
