### ISSUE TITLE
Save Login Details

### ISSUE THREAD

**Issue by Elryyyyyyyy** [GeyserMC/Geyser#3172]
### What feature do you want to see added?

Saving your Login Details, either with logging in inside the app or with the browser method, but keep the login data.

### Are there any alternatives?

Using Floodgate, which doesnt really work (Jitter and bad synchronisation)

**Comment by Jens-Co** [comment]
I'll close this since we already have an open issue alike. 

https://github.com/GeyserMC/Geyser/issues/2448

Issue refers to GeyserConnect but will also imply to Geyser. This is something we will add in some form once that Microsoft migration is completed.

thanks!

**Comment by Camotoy** [comment]
> Jitter and bad synchronisation
This shouldn't be a Floodgate-specific issue because it doesn't deal with gameplay?

But Geyser itself does have a method of storing login details - see `saved-user-logins`. This feature doesn't exist in GeyserConnect as we don't want to remotely store users' credentials.
