### ISSUE TITLE
When a BEDROCK user enters my server this error appears in the console

### ISSUE THREAD

**Issue by RicarGamer** [GeyserMC/Geyser#3173]
### Describe the bug

The error is the following 

[geyser]: Could not translate packet ClientboundLoginPacket

### To Reproduce

1. Start my server - proxy
2. I let a BEDROCK player in
3. See the error

### Expected behaviour

does not connect players

### Screenshots / Videos

![help](https://user-images.githubusercontent.com/67794919/180933249-3cf92c52-711b-4a17-85e2-cf7891de490c.png)

### Server Version and Plugins

Server-Proxy Velocity 3.1.1

### Geyser Version

Geyser-Velocity.jar

### Minecraft: Bedrock Edition Device/Version

1.18, 1.19.2, 1.19.10

**Comment by Camotoy** [comment]
Please attach a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by RicarGamer** [comment]
We've made a dump with useful information, report your issue and provide this url: https://dump.geysermc.org/5Scu9BOdcB5XVbbTLVdcSjo6HwOGkxPp

**Comment by Jens-Co** [comment]
i think it's caused since you are using offline Velocity with limbo login plugin. 
Login plugins in general can cause issues a-like.

can you test it by removing that plugin and use online mode to see if that fixes the issue? 

Thanks.

**Comment by Jens-Co** [comment]
Closed due to no response. If you still encounter this issue, feel free to bump this and I'll reopen.
