### ISSUE TITLE
Gui menu/shop

### ISSUE THREAD

**Issue by AerialLine** [GeyserMC/Geyser#3174]
### What feature do you want to see added?

Geyser has not yet implemented the gui menu, so clicking on it does not produce display gui menu.
but, I'd like to see that implement it.

### Are there any alternatives?

It looks to like need to do is listen to the chest events...
But, I don't know, it's not working, is it?

**Comment by Camotoy** [comment]
This sounds like a Geyser bug. Can you explain what's not working? List the plugin and steps to reproduce.

**Comment by AerialLine** [comment]
ok
step1: set up Spigot(Paper) Server.

step2: install Shopkeepers.
  step2-1: command sending /shopkeepers
  step2-2: push shift & rigth click
  step1-3: https://gyazo.com/e533e5e1c703e386a18124773457ad99 <- Place any block like a birch

step3: click villager

It works in the java edition, but not in the bedrock edition.

**Comment by AerialLine** [comment]
I see.
I'll try it today.

By the way, due to the time difference, the time in my country is 8:30.
So I'm sorry to be late.

**Comment by AerialLine** [comment]
hmm Can't join server on localhost(bedrock edition) 
But, can join form java edition. 
why?

https://gyazo.com/5122fd16158e6a57a389cf6697553bdd

ps: I was able to join the test.geysermc.org server.
