### ISSUE TITLE
Can't use Virual currency with shopkeepers(bedrock) 

### ISSUE THREAD

**Issue by ThyCodex** [GeyserMC/Geyser#3175]
### Describe the bug

When using the plugin Shopkeepers, I can not use virtual currency to buy items from the shops on bedrocks side. I can only buy things with physical currency

### To Reproduce

1. Go to shopkeepers
2. click on shopkeeper
3. click on item to buy
4. item should go into inventory but it does not

### Expected behaviour

money should be deducted from virtual bank and item should go into players inventory

### Screenshots / Videos

https://user-images.githubusercontent.com/66132511/181037836-acc57455-0056-4465-9fe8-8794f5640e2e.mp4

### Server Version and Plugins

shopkeerpers, shopkeepers addon, bettereconomy, vault, geyser, floodgate

### Geyser Dump

https://discord.com/channels/613163671870242838/613168464634576897/1001495378442596382

### Geyser Version

2.0.5-SNAPSHOT (git-master-f4a5ccb)

### Minecraft: Bedrock Edition Device/Version

1.19 Win10, Mobile, Sony, Xbox

**Comment by zaldhyx77** [comment]
i believe its the addon fault not geyser nor shopkeeper. i use Coins in my server to trade with physical currency and it worked fine. even SK's devs recomending coins and the addon you are using never mentioned anywhere in the wiki

**Comment by ThyCodex** [comment]
So shopkeepers addon is the only way you can do vitural currency trades with the shopkeepers. Without the addon no one can do virtual currency trades. Is there something I can do to get geyser to work with shopkeepers addon?

**Comment by zaldhyx77** [comment]
Coins do exactly that. try it out https://www.spigotmc.org/resources/coins.33382/

**Comment by Creeperz653** [comment]
> i believe its the addon fault not geyser nor shopkeeper. i use Coins in my server to trade with physical currency and it worked fine. even SK's devs recomending coins and the addon you are using never mentioned anywhere in the wiki

Geyser doesn’t support custom villager Recipes I think

**Comment by foxaduce** [comment]
how to view item lore like

**Comment by Jens-Co** [comment]
Any updates on this issue?

**Comment by Jens-Co** [comment]
Close this issue due to no response.
