### ISSUE TITLE
Bedrock players sometimes failing to connect

### ISSUE THREAD

**Issue by Xemorr** [GeyserMC/Geyser#3178]
### Describe the bug

When bedrock players try to connect, it sometimes gets stuck on Locating Server (going off of the word of a player experiencing it). Most notably, this error appears in console coinciding with the error 
![image](https://user-images.githubusercontent.com/31805746/181260644-29035086-4812-4c5b-b8dc-5677d21bf406.png)

In order for the user to connect, they have to attempt to connect again and hope the issue doesn't occur that time.

### To Reproduce

I haven't worked out the exact steps to reproduce yet, but if you want to try and see if it happens when connecting to our server. The IP is mc.enchanted-skies.net and port 19132 for geyser.

### Expected behaviour

I would expect the user to connect successfully and for there to be no error in console.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/31805746/181260904-98b255a0-794f-427e-abd2-40277cb594dd.png)

### Server Version and Plugins

>....[13:39:01 INFO]: Velocity 3.1.2-SNAPSHOT (git-e4f57c36-bunknown)
[13:39:01 INFO]: Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[13:39:01 INFO]: velocitypowered.com - GitHub

[13:39:33 INFO]: Current: git-Purpur-1714 (MC: 1.19)*
Previous: git-Tuinity-"2683c77" (MC: 1.16.5)
* You are 21 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Geyser Dump

https://dump.geysermc.org/fsMOkN4Qh6BqxSYEsMhqwiTikCvUKgi7

### Geyser Version

>....>....[13:39:54 INFO] This server is running Geyser version 2.0.5-SNAPSHOT (git-master-f4a5ccb) (Java: 1.19, Bedrock: 1.19.0/1.19.2 - 1.19.10)

### Minecraft: Bedrock Edition Device/Version

Minecraft Windows 10 Edition

**Comment by Camotoy** [comment]
When did this start?

**Comment by Xemorr** [comment]
Last one or two days I think.

**Comment by Camotoy** [comment]
Since this is definitely on the Bedrock side, I don't think we have a clear way to reproduce it. Maybe hardware-related???

**Comment by onebeastchris** [comment]
If this is still an issue, send a geyser dump & logs - will reopen this then.
