### ISSUE TITLE
Cannot connect on iOS Mobile Patches

### ISSUE THREAD

**Issue by Lukas-Batema** [GeyserMC/Geyser#3180]
### Describe the bug

When trying to join from recent iOS Minecraft patch updates, it gives an outdated geyser proxy notice, because it looks like Mojang screwed up, since they updated to 1.19.2, but then went to 1.19.10.

### To Reproduce

1. Open Bedrock on iOS
2. Select server tab
3. Select desired geyser server
4. See the proxy message

### Expected behaviour

Actually loading the server would be nice.

### Screenshots / Videos

https://drive.google.com/file/d/10Nh_icK6uBRBnqZQIMTQtnfB2FVSkVlK/view?usp=drivesdk

https://drive.google.com/file/d/1sLwvCJIPa2jvLOixx8M8wAkUcgEGZahy/view?usp=drivesdk

### Geyser Version

2.0.4-SNAPSHOT (git-master-dc810f1)

### Minecraft: Bedrock Edition Device/Version

1.19.10/11

**Comment by onebeastchris** [comment]
try updating geyser, 1.19.11 should be supported

**Comment by Lukas-Batema** [comment]
I am currently attempting to do that

**Comment by Camotoy** [comment]
`since they updated to 1.19.2, but then went to 1.19.10`

No, this is just how Bedrock updates work. 10 > 2

Anyway, yeah, you're just outdated. Update Geyser and this should be resolved.

**Comment by Lukas-Batema** [comment]
It gave me a different message, `Outdated client! Please use 1.19.1`

**Comment by onebeastchris** [comment]
https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/feature%252F1.19.1/
download geyser for 1.19.1 from that link

**Comment by Lukas-Batema** [comment]
It works now. When I did `geyser version` in my console, it gave me the link to the master branch, so that’s why it didn’t work. Also, it would be nice if a message came up in game, when behind in versions. I was apparently 17 versions behind master, without knowing! Thanks for both of your help, have a nice rest of your day. Cheers!
