### ISSUE TITLE
1.19.11 update

### ISSUE THREAD

**Issue by Firepup6500** [GeyserMC/Geyser#3182]
### Describe the bug

Geyser does not support 1.19.11, which the switch has updated to.

### To Reproduce

Open Minecraft on the switch
Access the server list (I have instructions for this)
Add a cross platform server
Try to join
See issue

### Expected behaviour

Player is able to join

### Server Version and Plugins

Version:
```
This server is running Paper version git-Paper-86 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 4a4ee79)
You are running the latest version
Previous version: git-Paper-81 (MC: 1.19)
```
Plugins:
```
Plugins (29): AntiXRay, CCTV, Citizens, CitizensCMD, CitizensGUI, CitizensText, CustomCrafting, DecentHolograms, DefensiveTurrets, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, ExcellentCrates, FiveNightAtFreddysInMinecraft*, FlashLight*, floodgate, Geyser-Spigot, GriefPrevention, LuckPerms, NexEngine, NoCheatPlus*, PhysicsControl, PlayerHeads, ProtectionLib, RampenDrills, Vault, WolfyUtilities, WorldEdit
```

### Geyser Dump

https://dump.geysermc.org/On3bGT9zZCzkP6RuJKIiySCeYXCK2Y7z

### Geyser Version

This server is running Geyser version 2.0.5-SNAPSHOT (git-master-16bb79e) (Java: 1.19, Bedrock: 1.19.0/1.19.2 - 1.19.10)

### Minecraft: Bedrock Edition Device/Version

1.19.11, Nintendo Switch

**Comment by Camotoy** [comment]
Geyser does support 1.19.11 - it's protocol-compatible with 1.19.10. I'll update Geyser anyway to indicate support and clear the confusion.

**Comment by Firepup6500** [comment]
> Geyser does support 1.19.11 - it's protocol-compatible with 1.19.10. I'll update Geyser anyway to indicate support and clear the confusion.
Then why can the switch not join?

**Comment by Camotoy** [comment]
If the error you're getting isn't "Outdated Geyser Proxy" then your issue is something else.

**Comment by Firepup6500** [comment]
> If the error you're getting isn't "Outdated Geyser Proxy" then your issue is something else.

Attempting to join says that the switch is out dated, and to update

**Comment by Camotoy** [comment]
Make sure you're using the latest Paper (or fork) and Geyser version.

**Comment by Firepup6500** [comment]
Using the latest one Aternos will let me install
