### ISSUE TITLE
Patterns not appearing in loom

### ISSUE THREAD

**Issue by EldritchGarden** [GeyserMC/Geyser#3183]
### Describe the bug

Banner shapes that have pattern items in Bedrock are not appearing in the loom menu for bedrock players.

### To Reproduce

Open loom
Attempt to use pattern shape, such as Bordure Indented

### Expected behaviour

All shapes available in java should appear in loom menu

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/26440900/181636588-59f3c38d-c96d-43d8-a2b6-6209897a348d.png)

### Server Version and Plugins

Server: `Current: git-Purpur-1735 (MC: 1.19)*`
Velocity: `3.1.2-SNAPSHOT (git-6be344d9-b162)`

### Geyser Dump

https://dump.geysermc.org/wrHhV8zjvYZh7OkNtpdPCsuOJZ2upBsf

### Geyser Version

Geyser version 2.0.6-SNAPSHOT (git-master-8f89647) (Java: 1.19.1, Bedrock: 1.19.0/1.19.2 - 1.19.10)

### Minecraft: Bedrock Edition Device/Version

1.19.11, win10 & xbox

**Comment by Camotoy** [comment]
We don't have control of that portion of the UI, I can pretty confidently say. But aren't the pattern items unlocked when you use the pattern item? Otherwise, send a screenshot on Java and point out what's missing.

**Comment by EldritchGarden** [comment]
There are 2 patterns in Bedrock that don't have items in Java, Field Masoned and Bordure Indented. Screenshot shows the Bordure Indented pattern in the loom in java without a pattern item.

![image](https://user-images.githubusercontent.com/26440900/181647817-f7aae566-d949-43f0-8a22-b5f2cc4dd72a.png)

**Comment by Camotoy** [comment]
Yeah, I can't see any way we can resolve this.

**Comment by EldritchGarden** [comment]
How does Geyser handle loom pattern selection events? I can override pattern selection on the server side with an event listener, but it doesnt work for bedrock players.

**Comment by Chew** [comment]
As with a lot of things, I do believe this is client-sided which means we don't have control

**Comment by Camotoy** [comment]
Because of the way Bedrock works, we send the pattern selection, and then immediately send us clicking on the inventory slot.

**Comment by EldritchGarden** [comment]
I'm certainly not an authority on plugin development, but I don't think anything can be done on the server side either. It should be possible with a Geyser extension, but that's not something I care to attempt until extension support is included in the main release.

**Comment by Stuart-Cox** [comment]
Is there anyway to do the reverse and give java players/ server the item to make Bordure Indented pattern

**Comment by onebeastchris** [comment]
Not really, no. Even if there was a way, it would be outside the scope of Geyser - Geyser does not modify Java server behavior.

**Comment by onebeastchris** [comment]
Closing this issue in favor of it being documented on our current limitations page: https://wiki.geysermc.org/geyser/current-limitations/
