### ISSUE TITLE
Torch Offhanding

### ISSUE THREAD

**Issue by rishabhk571** [GeyserMC/Geyser#3184]
### What feature do you want to see added?

Can we have a system like when we do `/geyser offhand` and move torch to offhand, The torch should emit light just like it does in Java when Dynamic Lights are turned on!
Coz offhanding a torch makes useless in PE when light doesn't emit!

### Are there any alternatives?

Idk, haven't find any yet

**Comment by Camotoy** [comment]
We aren't going to add this feature because this is an Optifine feature and not a vanilla feature. Thanks though!

**Comment by MrZomka** [comment]
If you know Java, in theory, you could make a Geyser extension that does that. But again, it requires the knowledge of Java. And by Java, I mean the programming language and not the Java edition of the game.
