### ISSUE TITLE
Bedrock Players Will Place Fake Block

### ISSUE THREAD

**Issue by lolgam3r** [GeyserMC/Geyser#3185]
### Describe the bug

When Bedrock Players Are Bridging There Is a chance of this bug occuring.
When the bug occurs the players will place a fake block only visible on thier client. it dosen't exist for the server or anyone else.
trying to place a block using this block will result in it dissapearing.
(This bug seems to only occur when geyser is run on the server itself, and wont occur on servers that dont have geyser installed)

### To Reproduce

1. Set disable-bedrock-scaffolding to True In the geyser config. 
2. Join On Bedrock and give yourself 3 stacks or so of any block. (as long as u can scaffold)
3. give yourself speed 2 and start bridging while holding shift.
4. at some point (its kinda random) you will place a fake block.

### Expected behaviour

Fake block gets placed thats only visible client sided

### Screenshots / Videos

![example](https://user-images.githubusercontent.com/108252499/181831745-c9830f8f-d9af-469e-9c1d-2769f0aeb083.png)

### Server Version and Plugins

1.19.1 Spigot

### Geyser Version

2.0.6-SNAPSHOT (git-master-d826949)

**Comment by hausemaster3734** [comment]
Duplicate of #2921 .

**Comment by Konicai** [comment]
Run geyser dump (server console) / /geyser dump (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by onebeastchris** [comment]
Closing due to no response.
