### ISSUE TITLE
Hotkeys for moving items

### ISSUE THREAD

**Issue by lolgam3r** [GeyserMC/Geyser#3188]
### What feature do you want to see added?

Being able to press a key on your keyboard and being able to move the item to that spot in your hotbar 1,2,3,4,5 you get the point
(and move the item that was there to the spot you were hovering over if there is an item in that hotbar slot already)

### Are there any alternatives?

using a hacked client to get it

**Comment by Camotoy** [comment]
We don't have enough control of the client to do this - if a Bedrock singleplayer world can't do this, then we can't either. Thanks for the suggestion anyway.
