### ISSUE TITLE
Cannot load saved user tokens

### ISSUE THREAD

**Issue by Because66666** [GeyserMC/Geyser#3189]
### Describe the bug

I followed the article "Understanding the config" ,but I still met this problem. Of cause, the program was on the run , and I can also login. I really hope the procedure would be more convenient.

### To Reproduce

1,I open the config.yml with notepad, and I edit the "saved-user-logins" and write my bedrock account name, and saved
2,I created a new Text Document, and write the same thing as I did at the first procedure, and I saved.
3,Finally,I ran the procedure and it gave me a error.

### Expected behaviour

I hope the procedure could remember my account as I download the Geyser.jar for myself.

### Screenshots / Videos

![屏幕截图 2022-08-01 103722](https://user-images.githubusercontent.com/110363085/182063199-91e7980c-2d74-4f77-9792-6dcc490c14ba.png)
What I want to say is that I really don't know how to use "saved-user-logins", and I hope a better distribute on it.

### Server Version and Plugins

[10:59:36 INFO] 该服务器正在运行 Geyser 版本(version) 2.0.6-SNAPSHOT (git-master-d826949) (Java: 1.19.1, Bedrock: 1.19.0/1.19.2 - 1.19.10/1.19.11)
[10:59:36 INFO] 正在检查版本, 请稍候...
[10:59:37 INFO] 无新版本.
#What the output want to say is that it is the latest.

### Geyser Dump

 https://dump.geysermc.org/ev8LuK8sGrWgFtQAcBkZmOnLP8DkvYbx

### Geyser Version

2.0.6-SNAPSHOT (git-master-d826949)

### Minecraft: Bedrock Edition Device/Version

1.19.10 windows 11

### Additional Context

If I don't change the "saved-user-logins" and leave it default, it still output the same error. To be honest , I don't know how to use this correctly.

**Comment by Camotoy** [comment]
>  2,I created a new Text Document, and write the same thing as I did at the first procedure, and I saved.

Don't do this. Delete that document, and just do step 1. I'll clarify these steps.

**Comment by Because66666** [comment]
Thank you very much.
