### ISSUE TITLE
Players can switch to Creative on survival servers! 

### ISSUE THREAD

**Issue by Sckaletz** [GeyserMC/Geyser#3191]
### Describe the bug

This is the same issue as an old ticket in here, that I found. https://github.com/GeyserMC/Geyser/pull/228

We're using the latest version of Geyser for Bungeecord and has Floodgate on both Bungeecord and our paper 1.8.8 server. We can't do it on our 1.18.2 server.

### To Reproduce

Join the server and enter your settings where you can change your gamemode to Creative.

### Expected behaviour

Not being able to change gamemode

### Server Version and Plugins

Git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/KuiIZgQLZXVT7zQXvY8SnGQlhWrP4agx

### Geyser Version

Geyser Bungeecord build #1159

### Minecraft: Bedrock Edition Device/Version

1.19.11 Windows 10

**Comment by Camotoy** [comment]
I can confirm this, but have to yet figure out the solution. Note that only the Bedrock client thinks they're in creative; it doesn't actually change their difficulty.

**Comment by Sckaletz** [comment]
Both yes and no. They are still unable to kill or do harm to those bedrock players.
