### ISSUE TITLE
Spyglass bug, /offhand command.

### ISSUE THREAD

**Issue by SpeastTV** [GeyserMC/Geyser#3192]
### Describe the bug

We have found a bug with the command /geyser offhand. When you do /geyser offhand on a spyglass, the spyglass is not displayed in the offhand, but in the main hand.

Reproduce video: https://youtu.be/jL97asmIpKM

### To Reproduce

1. Take a spyglass in the main hand
2. Make /geyser offhand
3. Take an item in the main hand.
4. Look to the main hand, the spyglass is in the item.
5. finish
6. more details in the video(link) https://youtu.be/jL97asmIpKM

### Expected behaviour

The spyglass in the offhand. not in the main hand.

### Screenshots / Videos

https://youtu.be/jL97asmIpKM (too big for an upload to github)

### Server Version and Plugins

**Server Version:** git-Paper-91 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 65f0b2e)

**Plugins(Server in the video):** BlockedCommands*, ChestShop, ChestShopLogger, DecentHolograms, DiscordSRV, EconomyPlus, ExcellentCrates, FastAsyncWorldEdit (WorldEdit), floodgate, GeyserHacks, GeyserSkinManager, LPC, LuckPerms, MBAIO, MBJob, Multiverse-Core, MVdWPlaceholderAPI*, NexEngine, PlaceholderAPI, Playtimes*, PlotSquared, PluginHider*, PremiumVanish, ProtocolLib, Report, Reward*, RHSignItem, SearchChestshop, SimpleTpa*, TAB, Themis, UltimateHomes, Vault, Votifier, WorldGuard

**Plugins(Proxy Server):** spicord, libertybans, ban_announcer, floodgate, geyser
, geyserskinmanager-velocity, kaurivpn, luckperms, protocolize, mbmanager, minim
otd-velocity, teamchat, viaversion, viabackwards

### Geyser Dump

https://dump.geysermc.org/inofFenW9bpDlkTi18oH97KtJzZNb76h

### Geyser Version

2.0.6-SNAPSHOT (git-master-6856922)

### Minecraft: Bedrock Edition Device/Version

1.19.10 Windows 10 edition and 1.19.10 Minecraft Pocket (Mobile Version)

**Comment by Camotoy** [comment]
I can confirm this but I don't think we can fix this without a resource pack.

**Comment by SpeastTV** [comment]
The GeyserMC resource pack.

**Comment by Kas-tle** [comment]
Maybe. I will look into it.

**Comment by Kas-tle** [comment]
We can fix the display for both Bedrock and Java, as well as the animation when used by Java players per the linked PR above. However, we cannot allow the spyglass to be used in the offhand by bedrock players, as that appears to be hard coded client behavior.
