### ISSUE TITLE
Bug with Eatable. (1/2)

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Geyser#3195]
### Describe the bug

if while eating switch slot, edible item copy on this slot.  All inventory interactions work with this "copy".

### To Reproduce

1. Start eating.
2. Fastly switch slot.

### Expected behaviour

The server must synchronize the item.

### Screenshots / Videos

https://youtu.be/FRwBtcUkflE

### Server Version and Plugins

[14:03:16 INFO]: Checking version, please wait...
[14:03:17 INFO]: Current: git-Purpur-1747 (MC: 1.19.1)*
Previous: git-Purpur-1685 (MC: 1.19)
* You are running the latest version

### Geyser Dump

none

### Geyser Version

2.0.6-SNAPSHOT (git-master-6856922)

### Minecraft: Bedrock Edition Device/Version

1.19.11

**Comment by Camotoy** [comment]
I can't replicate this with the latest Geyser version on both desktop and mobile. Provide a Geyser dump and maybe a video?

**Comment by Camotoy** [comment]
Nevermind about the video.

**Comment by onebeastchris** [comment]
Unable to replicate - closing due to no further activity.
