### ISSUE TITLE
Bug with Eatable (2/2)

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Geyser#3196]
### Describe the bug

Eat bug.

### To Reproduce

1. Start eating
2. Drop the item
3. Wait

### Expected behaviour

Eating process must stop.

### Screenshots / Videos

https://youtu.be/Un_qTUtioY0

### Server Version and Plugins

[14:12:20 INFO]: Current: git-Purpur-1747 (MC: 1.19.1)*
Previous: git-Purpur-1685 (MC: 1.19)
* You are running the latest version

### Geyser Dump

none

### Geyser Version

2.0.6-SNAPSHOT (git-master-6856922)

### Minecraft: Bedrock Edition Device/Version

1.19.11

**Comment by Creeperz653** [comment]
Reposting won’t get someone to support immediately

**Comment by Creeperz653** [comment]
Oops sorry I didn’t see the 2/1

**Comment by onebeastchris** [comment]
Unable to replicate. If this is still an issue, send a geyser dump.
