### ISSUE TITLE
Ghost block issue

### ISSUE THREAD

**Issue by Bobby99as** [GeyserMC/Geyser#3198]
### Describe the bug

Breaking a bunch of grass causes a grass dirt block to appear.

### To Reproduce

Find a bunch of grass punch the grass in survival you will see a ghost grass dirt block to appear

### Expected behaviour

The grass just breaks and sometimes drop a seed

### Server Version and Plugins

1.19.1
Floodgate and geryser-spigot

### Geyser Version

2.0.6 snapshot

**Comment by Camotoy** [comment]
Can you please supply a Geyser dump?

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

Also if you're able to add a video of the issue, that would be helpful.

**Comment by Bobby99as** [comment]
Here this should help
[Geyser_dump](https://dump.geysermc.org/mPo4gNFSt5XTufBR4M5ofnY5kxq4B3Fi) 
[Video](https://endpoint.s3.cyber-creek.us/cybercreek/github/Geyser/Ghost%20block%20issue/Minecraft%202022-08-02%2011-02-40_Trim.mp4)

**Comment by ethpsa09** [comment]
yes, this is also happening to me

**Comment by Bobby99as** [comment]
To add to this it seems to clone whatever block is under the grass

**Comment by onebeastchris** [comment]
Is this still happening with the latest version? Iirc there was some kind of fix for it a while back

**Comment by Bobby99as** [comment]
> Is this still happening with the latest version? Iirc there was some kind of fix for it a while back

It seems to be fixed

**Comment by Bobby99as** [comment]
> Is this still happening with the latest version? Iirc there was some kind of fix for it a while back

It seems to be fixed
