### ISSUE TITLE
Error bedrock when join server

### ISSUE THREAD

**Issue by Allwizz** [GeyserMC/Geyser#3200]
### Describe the bug

I create some server use paper 1.19.1 and I use geyser.
I have issue when bedrock join on server is stay on locating world and in console appear massage geyser eror

### To Reproduce

1. Geyser

### Expected behaviour

Not stable with new paper 1.91.1 build

### Screenshots / Videos

![IMG_20220803_202708](https://user-images.githubusercontent.com/96964228/182619514-b27bdc52-2160-4537-99de-5925189cf051.jpg)
![IMG_20220803_202652](https://user-images.githubusercontent.com/96964228/182619529-073e1bc8-341a-44b6-b9a5-b144ba21c4b7.jpg)

### Server Version and Plugins

Paper version git-Paper-104 (mc : 1.19.1) (API version 1.19.1 -RO .1 -SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/Znjz7kF9O4WuMgHWWD5CPQkIm6EfjYCp

### Geyser Version

2.0.6-SNAPSHOT #1162

### Minecraft: Bedrock Edition Device/Version

1.19.1

**Comment by Camotoy** [comment]
Please take a look here for a workaround: https://github.com/GeyserMC/Geyser/issues/2861

Thanks.

**Comment by Allwizz** [comment]
Thanks :)
