### ISSUE TITLE
Mobs can attack through crevices of blocks

### ISSUE THREAD

**Issue by VenomousSteam81** [GeyserMC/Geyser#3203]
### Describe the bug

I don't know if there are any duplicates, but it would be kind of hard to find some.

Mobs can shoot, throw at, or attack Bedrock players if there are only 2 blocks around or 1 above them. I don't believe this happens to Java players

### To Reproduce

1. Take an iron door trap
2. Remove the pressure plate
3. Replace the 4 iron doors with any other blocks
4. Add a block above the center of the 2 doors

### Expected behaviour

I expected mobs to not be able to attack you through the crack

### Geyser Dump

This isn't my server, but it has happened on two servers with Geyser

### Geyser Version

That is unknown to me, because the servers are not mine and I don't have the permission to do `/geyser version`

### Minecraft: Bedrock Edition Device/Version

1.19.11, Android

**Comment by Camotoy** [comment]
This doesn't sound like our issue because we don't modify server mechanics.

**Comment by Konicai** [comment]
I wasn't able to reproduce this on a blank paper server.

> I don't believe this happens to Java players  

Please actually verify this

> That is unknown to me, because the servers are not mine

Please ask the server owner to open an issue if they can reproduce this issue on their server

**Comment by VenomousSteam81** [comment]
Ok, thank you. Sorry for a late response, as I forgot about this issue
