### ISSUE TITLE
Request to add to FAQ / known issues

### ISSUE THREAD

**Issue by Jacold** [GeyserMC/Geyser#3207]
### Describe the bug

Hello. I've asked for help on support channel on Discord server about extreme lags while using cellular data. After few days digging into it with my friend we discovered that APN should be ipv4 instead of ipv6 (which I have as default setting provided by my new carrier - I've moved my number to another provider). 
Just wanted to share that to save someone's hours of life.

### To Reproduce

-

### Expected behaviour

-

### Geyser Version

-

**Comment by Konicai** [comment]
Please make a PR to [GeyserMC/GeyserWiki](https://github.com/GeyserMC/GeyserWiki) (perhaps this page: https://github.com/GeyserMC/GeyserWiki/blob/master/_docs/geyser/common-issues.md)

or make an issue on that repository asking someone else to add it
