### ISSUE TITLE
Server Linking Not Working

### ISSUE THREAD

**Issue by AndrewG587** [GeyserMC/Geyser#3209]
### Describe the bug

Bedrock account unable to join linking server.

### To Reproduce

1: attempt to join on bedrock
2: see an error message

### Expected behaviour

expected: Bedrock account is able to join just fine. what happend: minecraft: "Disconnected from server"

### Geyser Version

i don't know this is your server not mine

### Minecraft: Bedrock Edition Device/Version

Windows 10 v1.19.11

### Additional Context

server requires 1.18 on java, that may be the problem

**Comment by Camotoy** [comment]
We literally JUST updated it. Try again.
