### ISSUE TITLE
Buckets

### ISSUE THREAD

**Issue by gaussandhisgun** [GeyserMC/Geyser#321]
**What feature do you want?**
There are missing implementation of bucket sync. So, I tap on water block, and Geyser shows that i *got* the water, but actually i did not. 

**Alternatives?**
None.

**Comment by RednedEpic** [comment]
> **What feature do you want?**
> There are missing implementation of bucket sync. So, I tap on water block, and Geyser shows that i _got_ the water, but actually i did not.
> 
> **Alternatives?**
> None.

Does this issue persist with the inventory branch?

**Comment by gaussandhisgun** [comment]
> Does this issue persist with the inventory branch?

I generally use the inventory branch. So yes.

**Comment by rtm516** [comment]
I tested this on master in creative and didn't get this issue.

**Comment by JuniorJPDJ** [comment]
This is probably whole sync issue and it's all about timings.

**Comment by Zhwt** [comment]
On inventory branch, both "get water" and "pour water" have problems. This can be reproduce if you dig a 1x1x5 hole and try to pour water into the middle space, the water will disappear, but if you tap on that space again, you can get your water back. And by doing this for several times, finally I got a dirt block that can't plant anything on it, PE and JE. Sorry for my poor English, maybe I'll upload a video later to demonstrate this problem.

**Comment by Artuto** [comment]
Can confirm buckets dont work. Latest inventory.

**Comment by Artuto** [comment]
Paper b201

**Comment by DoctorMacc** [comment]
Odd question - do bows work?

**Comment by RednedEpic** [comment]
This also includes placing water.

**Comment by AnonAlpha** [comment]
> Odd question - do bows work?

Yes, bows work, but it work weirdly, it seems the arrow is shot from inside your head

**Comment by AnonAlpha** [comment]
> Odd question - do bows work?

Yes, bows work, but it work weirdly, it seems the arrow is shot from inside your head

**Comment by mov51** [comment]
I got a video of the issue, it's also seems possible to get the bucket to place or pickup by holding the action. it seems to acting similar to how attacking an entity switching the actions around. You normale tap the screen to place and hold to break, then when breeding animals it's swapped compared to java in that the break action is what is used to breed and the normal use action is attack. 

https://youtu.be/G7ydg1mJQLc
https://youtu.be/oslZz0uk4HI
(sorry about the movement, I am very much not used to mobile.)

**Comment by MisterSheeple** [comment]
Honestly I think this bug should be at a higher priority. Not being able to use buckets to me is a big deal because a lot of people use them in a daily basis in Minecraft. It's one of those features that just seems important

**Comment by xiaowang2017** [comment]
I have the same problem when I want to get water bottles.It will disappear

**Comment by jabbink** [comment]
I found a buggy workaround to place water/lave. Buckets seem to work for me on the 1.16 branch when I long-tap the on the ground, as if I wanted to break the block.

This allows for placing water in air/on top of grass by the way.

**Comment by mov51** [comment]
I did mention as much in my last comment. it also works for the 1.15.2 branch but feels very clunky. It also doesn't seem to take the same amount of time to activate.
![image](https://user-images.githubusercontent.com/16448318/86926180-c3a84600-c0ff-11ea-9356-e29de0e73f90.png)
