### ISSUE TITLE
Bedrock client timing out

### ISSUE THREAD

**Issue by urxnot** [GeyserMC/Geyser#3211]
### Describe the bug

Whenever the bedrock client does pretty much anything it will just disconnect.

### To Reproduce

1. join server
2. try hit something or break a block
3. disconnect

### Expected behaviour

for everything to work normally

### Geyser Dump

https://dump.geysermc.org/BXtI7ikRkoB19gv7uGn5hGJ7iEobpYlV

### Geyser Version

2.0.6-SNAPSHOT (git-master-f74713c)

### Minecraft: Bedrock Edition Device/Version

1.19.11, Windows 10

**Comment by Kas-tle** [comment]
Hello, could you see if the issue persists with a clean server (only Geyser and Floodgate)?

**Comment by Konicai** [comment]
Please provide full server logs as well through https://mclo.gs

**Comment by Jens-Co** [comment]
Since no response was given i will close this issue. I will reopen this if you provide us with the missing info thanks.
