### ISSUE TITLE
Error in console from Geyser

### ISSUE THREAD

**Issue by DimaSergeew** [GeyserMC/Geyser#3212]
### Describe the bug

https://pastebin.com/qc1mPTib Constantly and quite often this error pops up in the console. I can't figure out what it's about

### To Reproduce

by itself

### Expected behaviour

That there will be no mistakes!

### Screenshots / Videos

![Screenshot_1](https://user-images.githubusercontent.com/75163645/183591643-636b1ded-1dc6-486a-924b-f93405557118.png)

### Server Version and Plugins

Velocity 171

### Geyser Dump

-

### Geyser Version

Geyser version 2.0.3-SNAPSHOT (git-master-c83eb7f) (Java: 1.18.2, Bedrock: 1.18.0/1.18.1/1.18.2 - 1.18.30/1.18.31)

### Minecraft: Bedrock Edition Device/Version

Xiaomi MI 9T: Minecraft Bedrock v 1.18.31

**Comment by Konicai** [comment]
Provide the link that  `/geyser dump` gives you and please list which steps it takes to make this occur.

**Comment by Jens-Co** [comment]
I'll close this issue since no response/additional info wasn't provided. If you are still having this issue please provide us with server logs, a Geyser dump and the replication steps.
I'll reopen when this is bumped.
