### ISSUE TITLE
PS4/Windows 10 (Bedrock Edition players 'Timed Out')

### ISSUE THREAD

**Issue by matomfg** [GeyserMC/Geyser#3223]
### Describe the bug

The bug consists of Bedrock Edition players timing out, specifically PS4 Players. 
- Issue occurs regardless with ViaVersion or not.

Things I've tried to resolve the issue:
- Compression is set to 9 - which is making no difference to the bug. 
- MC Connector (which is what is needed to make PS4 players connect) all battery optimizations are off for that app.
- Adding more ram to the server 6 >> 8GB - which is making no difference to the bug. 
- Upgrading Server Hosting from Ryzen 5 to 9 - which is making no difference to the bug. 

### To Reproduce

PS4 player joins the server, and times out either instantly or after a little bit.

### Expected behaviour

[01:07:33 INFO]: [floodgate] Floodgate player logged in as .Fluffy6007 disconnected
[01:07:33 INFO]: [Geyser-Spigot] Fluffy6007 has disconnected from the Java server because of Bedrock client timed out
[01:07:33 INFO]: .Fluffy6007 lost connection: Disconnected

### Geyser Dump

https://dump.geysermc.org/V7oogVbLYSEqnnmR2TZpiFClXJr8Z3o1

### Geyser Version

This server is running Geyser version 2.0.7-SNAPSHOT (git-master-25a18a2) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.20)

### Minecraft: Bedrock Edition Device/Version

v1.19.11

### Additional Context

"name": "ViaVersion",
                "version": "4.4.1",
"name": "floodgate",
                "version": "2.2.0-SNAPSHOT (b69-a46f43d)",
"name": "ViaBackwards",
                "version": "4.3.0",
"name": "ProtocolLib",
                "version": "5.0.0-SNAPSHOT-b565",
"name": "Geyser-Spigot",
                "version": "2.0.7-SNAPSHOT",
"name": "GeyserUpdater",
                "version": "1.6.2",

**Comment by kabluinc** [comment]
Experiencing similar issue since updating. For me all players on various device OS randomly get timed out at the same time.

**Comment by Konicai** [comment]
What happens if you remove VoiceChat?

**Comment by matomfg** [comment]
> What happens if you remove VoiceChat?

Hi, 

The issue started right at the beginning of the server, where I was told possibly updating geyser would fix it, and everything else just piled ontop over the few months. I can remove voicechat to test but I can confirm voicechat was only recently added with the 1.19 update. I have been using Geyser from version 1.18 with the issue persisting.

**Comment by mayberks** [comment]
1-1 I am having the same problem. Any progress?

**Comment by Kashalls** [comment]
Getting this when using Geyser Standalone to connect to a 1.18.2-1.19.2 ViaVersion paper server.

**Comment by matomfg** [comment]
Any update on this?

**Comment by Camotoy** [comment]
I don't know how to further debug this when I can't replicate it.

**Comment by WRF5riNr** [comment]
Here's my workaround:

1. Geyser config.yml - set ```use-direct-connection: false``` (default true)
2. server.properties - lowered to ```view-distance=12``` (initially 16)

Notes

- Using Geyser-Fabric but the issue is the same.
- The time outs partially stopped after # 1 but seem to have fully stopped after # 2. If # 2 only then it still occurs.
- I've also set ```compression-level: 9``` and ```command-suggestions: false``` but don't know if they're necessary.

So now it works, though not ideally because our server can have a higher view-distance.

**Comment by Kashalls** [comment]
> I don't know how to further debug this when I can't replicate it.

I haven't been able to replicate this since updating everything to  `version 2.0.7-SNAPSHOT (git-master-a16fc9c)`.

**Comment by Jens-Co** [comment]
Any updates on this issue? i will close in a week if not/no response thanks :)

**Comment by matomfg** [comment]
Hi Jen's, haven't been receiving any players timing out recently so I'd say
issue is resolved from my end.

Regards

**Comment by Jens-Co** [comment]
Im glad to hear that!
