### ISSUE TITLE
Events relating to pings

### ISSUE THREAD

**Issue by 7man7LMYT** [GeyserMC/Geyser#3225]
### What feature do you want to see added?

Adding events that get fired when Geyser gets pinged, one example could be a `GeyserPingEvent` that gets fired upon getting pinged, and allows for setting/getting the MOTD, player count, or more.

### Are there any alternatives?

The only thing closest is only getting and doesn't allow setting.

**Comment by Camotoy** [comment]
Definitely my hesitation here is that this event will be fired many times because of the way Bedrock pings work. (In LAN there's a bug where the event might be called many times each time a client pings [~3 seconds]). But, I do think this is valid as it covers an area that Java plugins can't.

**Comment by Konicai** [comment]
Event result caching?

**Comment by Camotoy** [comment]
Because this event will happen on many different threads, I don't think that's practical.
