### ISSUE TITLE
doesn't want to work with nginx for some reason

### ISSUE THREAD

**Issue by lootoos** [GeyserMC/Geyser#3226]
### Describe the bug

I am using nginx in the HAProxy role: https://ibb.co/FnpFhPk
minecraft java is working, but Geyser for some reason does not want to let in - an attempt to log in to Geyser is not even visible.
Geyser doesn't support Nginx yet-what? If so, why and will it be supported?
My geyser config: https://pastebin.com/MgBDS424

### To Reproduce

1. Enable in geyser config.yml:enable-proxy-protocol: true
2. Configure nginx as a HAProxy
3. Trying to log in to the server

### Expected behaviour

It is expected that there will be an attempt to log into Geyser packages, but for some reason, an attempt to log in to the player is not visible in the geyser logs.

### Screenshots / Videos

https://ibb.co/FnpFhPk 

### Server Version and Plugins

kernel:mirai 1.19.2.

### Geyser Version

Build #1174 (https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1174/)

**Comment by Camotoy** [comment]
Does setting `bedrock` `address` to `0.0.0.0` resolve the issue?

**Comment by lootoos** [comment]
> Does setting `bedrock` `address` to `0.0.0.0` resolve the issue?

no, it doesn't help

**Comment by lootoos** [comment]
> Does setting `bedrock` `address` to `0.0.0.0` resolve the issue?

home pc: https://ibb.co/xfLVGPq 
vds: https://ibb.co/Rb2dRGn 
addresses 10.228.228.1/10.228.228.2 are addresses created using Wireguard. Minecraft Java works fine - that is, it lets the server in, the ip addresses of the players are also forwarded instead of 10.228.228.1

**Comment by Camotoy** [comment]
I suspect something else is up because while we don't actively test the feature, TCPShield uses it and if this broke we would know. Is 19135 UDP correctly exempted on the firewall on the computer hosting Geyser?

**Comment by lootoos** [comment]
https://pastebin.com/vzKYbUPY 
with such settings, an attempt to log into the server is visible, but because Nginx uses proxy_protocol on; then the server geyser cannot accept packets because proxy_protocol is disabled in it.
https://ibb.co/9pzYrGn

**Comment by lootoos** [comment]
> I suspect something else is up because while we don't actively test the feature, TCPShield uses it and if this broke we would know. Is 19135 UDP correctly exempted on the firewall on the computer hosting Geyser?

the server is running on linux, there is not one firewall installed there because I put a clean debian 11.4

**Comment by Camotoy** [comment]
> with such settings, an attempt to log into the server is visible, but because Nginx uses proxy_protocol on; then the server geyser cannot accept packets

That looks like a completely separate issue where you need to set `remote` `address` to point to Nginx and not localhost (which is what `auto` defaults to). If you're getting connection logs by disabling Bedrock proxy protocol, then you're probably connecting to the wrong server.

**Comment by Camotoy** [comment]
Actually it sounds like this is all localhost, so set `remote` `port` to 25565.

**Comment by lootoos** [comment]
it doesn't help

**Comment by lootoos** [comment]
logs minecraft server:https://pastebin.com/6UxfuuGD

**Comment by lootoos** [comment]
I figured out what's the matter - it turns out that the geyser needs a white IP address, but then why does the java client connect to the minecraft server with the proxy-protocol option (if the provider allocates a gray IP), it does not connect to the geyser, but the server is visible in the game menu - that is, the server pings and it is not possible to log in (if you have a gray IP address)

**Comment by lootoos** [comment]
I figured out what's the matter - it turns out that the geyser needs a white IP address, but then why does the java client connect to the minecraft server with the proxy-protocol option, (if the provider allocates a gray IP), it does not connect to the geyser, while the geyser server is displayed in the game menu - that is, the server pings, but it is impossible to log in to the server (if the hosting on which the geyser has a gray IP)

**Comment by lootoos** [comment]
https://ibb.co/0cFXv42 https://ibb.co/pdzjQJ8 https://ibb.co/TcHCCNv

**Comment by Konicai** [comment]
By white IP do you mean static, and by gray IP do you mean dynamic?

**Comment by lootoos** [comment]
> 

gray ip when you can't open the ports because the gray address is not visible on the world Internet. 
the white ip is visible on the world Internet, so you will be able to open ports on your home computer.
to open ports with a gray IP, you need to rent a VDS, install wireguard on the VDS (to create a tunnel between the home computer and the VDS), after install Nginx on the VDS so that minecraft server can receive packets from the game client.

**Comment by lootoos** [comment]
mcbe-access.log(nginx):https://pastebin.com/bhVFWN3n

**Comment by mbenitog** [comment]
I have this issue too. My Bedrock client can see the server but won't connect to it when using Nginx.
I'm running Geyser as a plugin on one server and the Nginx proxy on other server. Both firewalls have UDP 19132 port open.

This is my config: https://pastebin.com/GwnDv6sb

Also nginx config:
`stream {
    server {
        listen 19132 udp;
        proxy_pass  MCServerWithGeyserIP:19132;
        proxy_protocol on;
    }
}`

**Comment by darallium** [comment]
I have the same issue.

nginx config:

`upstream bungeecord{
                server 192.168.0.199:19132;
        }
        server {
                listen 19132 udp reuseport;
                proxy_pass bungeecord;
        }
        `

**Comment by darallium** [comment]
Pings work and the MOTD shows, but connections end up failing. It just keeps saying "[IP] tried to connect!"

**Comment by onebeastchris** [comment]
@darallium please send a Geyser dump by running "geyser dump" and sending the link it'll give you here.

**Comment by darallium** [comment]
https://dump.geysermc.org/TQY4ZHUyzYUfikqO7Io8jYpzXcHOrtP8

**Comment by darallium** [comment]
I think nginx cannot udp forward ipv4 and ipv6 at the same time and, Geyser cannot receive udp connection with ipv4 and ipv6 at the same time.

**Comment by fileexists** [comment]
did anyone find a solution please?

**Comment by fileexists** [comment]
im currently using envoyproxy and i can connect successfully but on my bungeecord console i get a protobuf error, and my ip is the one of the machine where the envoyproxy is hosted, is there any solution to this?
I want to forward the real user IP and fix the protobuf error

**Comment by onebeastchris** [comment]
Closing this, as it's likely a configuration issue - and not a direct Geyser bug/issue.
Simultaneous ipv6 and ipv4 binding is an unrelated feature request, tracked here: https://github.com/GeyserMC/Geyser/issues/3547.

**Comment by mbenitog** [comment]
I have never seen this feature working. I asked several users on some Discord servers and we all have the same issue. Pings work and the MOTD shows, but connections end up failing.

Nginx configuration is pretty simple and straightforward, it is also a thoroughly tested piece of software. It was previously mentioned that this Geyser feature is not tested.

I wouldn’t disregard this as a Geyser issue

**Comment by Kas-tle** [comment]
This config will work:

```hocon
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

stream {
    upstream balancer {
        server 172.18.0.1:19132;
    }
    server {
        listen 10.0.0.208:19132 udp;
        proxy_requests 8640000;
        proxy_protocol on;
        proxy_pass balancer;
    }
}
```

If you do not wish to use proxy protocol that can be commented out.

**Comment by OurLobanov** [comment]
> This config will work:
> 
> user  nginx;
> worker_processes  auto;
> 
> error_log  /var/log/nginx/error.log notice;
> pid        /var/run/nginx.pid;
> 
> 
> events {
>     worker_connections  1024;
> }
> 
> stream {
>     upstream balancer {
>         server 172.18.0.1:19132;
>     }
>     server {
>         listen 10.0.0.208:19132 udp;
>         proxy_requests 8640000;
>         proxy_protocol on;
>         proxy_timeout 5s;
>         proxy_responses 0;
>         proxy_pass balancer;
>     }
> }
> If you do not wish to use proxy protocol that can be commented out. may need to be adjusted as this is how long it will take for nginx to truly close the connection if it doesn't get a response from the client.`proxy_timeout 5s;`

I ran into the same problem: I launch Nginx in Docker, I can connect to the Java server fine, but in Bedrock I can't. I see that the ping goes through and the IP is being inserted, but the connection to the server doesn't work, and the console is empty.

**Comment by OurLobanov** [comment]
> > This config will work:
> > user  nginx;
> > worker_processes  auto;
> > error_log  /var/log/nginx/error.log notice;
> > pid        /var/run/nginx.pid;
> > events {
> > worker_connections  1024;
> > }
> > stream {
> > upstream balancer {
> > server 172.18.0.1:19132;
> > }
> > server {
> > listen 10.0.0.208:19132 udp;
> > proxy_requests 8640000;
> > proxy_protocol on;
> > proxy_timeout 5s;
> > proxy_responses 0;
> > proxy_pass balancer;
> > }
> > }
> > If you do not wish to use proxy protocol that can be commented out. may need to be adjusted as this is how long it will take for nginx to truly close the connection if it doesn't get a response from the client.`proxy_timeout 5s;`
> 
> I ran into the same problem: I launch Nginx in Docker, I can connect to the Java server fine, but in Bedrock I can't. I see that the ping goes through and the IP is being inserted, but the connection to the server doesn't work, and the console is empty.

I used your config for the test, the problem is not getting resolved

**Comment by Novampr** [comment]
Please do not necropost on a GitHub issue, if you're having issues, please make a new issue, this one has already been closed for over a year.
