### ISSUE TITLE
closed connection

### ISSUE THREAD

**Issue by tecMT** [GeyserMC/Geyser#3229]
### Describe the bug

https://prnt.sc/w2AlPzXJb0D-
This is the error I get when I try to log in, I'm using the new version of geyser

### To Reproduce

open minecraft
try to enter
error, "connection closed"

### Expected behaviour

enter normally

### Screenshots / Videos

https://prnt.sc/w2AlPzXJb0D-

### Server Version and Plugins

git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/uH93709weD9QxAxdTjJhQyzNBTl3daG7

### Geyser Version

Build #1174 (10 de ago de 2022 23:06:22)

### Minecraft: Bedrock Edition Device/Version

1.19,2

### Additional Context

please

**Comment by Konicai** [comment]
Update BungeeCord
