### ISSUE TITLE
Issue When Connecting On Both Java & Bedrock

### ISSUE THREAD

**Issue by DuplexLake** [GeyserMC/Geyser#3232]
### Describe the bug

Me and my friend are doing tests with geyser, and we randomly keep disconnecting after a few minutes of no issues at all, I'm testing on java, and my friend is testing on bedrock

### To Reproduce

No real idea how to reproduce, it just happens after a few minutes every time the server is launched

### Expected behaviour

No disconnects or lag

### Server Version and Plugins

Minecraft Java Version 1.19.2/Minecraft Bedrock Version 1.19.20
Both of us are on windows 10
Currently there are no other plugins besides floodgate & geyser
Both Spigot and Paper have been tried, both of which had an issue

Spigot Version 1.19.2 (Can't find build or version, only see the release date which is Friday, August 05 2022)
Paper Version: 1.19.2-125

### Geyser Dump

Dump is in Additional Context

### Geyser Version

This server is running Geyser version 2.0.7-SNAPSHOT (git-master-33af9e0) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.20)

### Minecraft: Bedrock Edition Device/Version

I'm using java, friend is using windows 10 version of bedrock

### Additional Context

Logs, Geyser Dump, and start.bat file are here
[latest.log](https://github.com/GeyserMC/Geyser/files/9331997/latest.log)
https://dump.geysermc.org/i64pVxeuWOJOCVk2L0hxE9MNb89ppjle
https://hastebin.com/pubejiqura.css

If anything additional is needed, let me know, and I'll do what i can to help this issue get resolved

This server for info is hosted locally as a dedicated server, and not from a server host

**Comment by onebeastchris** [comment]
Wait, it disconnects both you on java AND bedrock? If it happens to java players aswell, it's likely not caused by geyser

**Comment by DuplexLake** [comment]
@onebeastchris it does, also i know it is in fact an issue with geyser, and when i run the server exclusively on java or geyser, there are no issues at all, when i run on specifically java or bedrock, instead of trying to make geyser run a hybrid

**Comment by DuplexLake** [comment]
> @onebeastchris it does, also i know it is in fact an issue with geyser, and when i run the server exclusively on java or geyser, there are no issues at all, when i run on specifically java or bedrock, instead of trying to make geyser run a hybrid

meant to say exclusively on java or bedrock

**Comment by Konicai** [comment]
Try the workarounds here please: https://github.com/GeyserMC/Geyser/issues/2861

**Comment by DuplexLake** [comment]
@Konicai i've tried this already, above, i put a hastebin for my start.bat file, and it's there

**Comment by Camotoy** [comment]
If Java is affected, then try without Floodgate. If it still happens with Geyser and Floodgate then almost certainly it's a performance thing of some sort. 
You can try attaching a Spark dump of you guys joining and playing:
Spark is a plugin that helps you monitor performance for you server.
https://spark.lucko.me/download

To record performance on your server use:
/spark profiler --thread * --timeout 240. This will run for 240 seconds then it will automatically stop.
It'll probably lag the server a good deal but it'll give us a link we might be able to process.

**Comment by DuplexLake** [comment]
@Camotoy i'll try this later today

**Comment by Jens-Co** [comment]
Any updates on this issue?

**Comment by Jens-Co** [comment]
Closed due to no response.
