### ISSUE TITLE
Bedrock Clients can play only a brief amount of time

### ISSUE THREAD

**Issue by ElandaOfficial** [GeyserMC/Geyser#3235]
### Describe the bug

When Bedrock players join, be it Switch or PlayStation (Windows 10 and XBox couldn't be tested), sometimes the player joins into a half loaded world that's stuck loading or, if they get in properly, after so around 30 seconds of playing, everything comes to a halt. The player can move, but the rest is stunned; the inventory, as well, can't be opened and no chat message can be issued.
Chat commands (and maybe messages too, didn't check) do get through to the server console, but nothing goes back to the client - so the client -> server does probably work but not server -> client.

Also, another problem was that sometimes when joining the player was kicked due to flying which I could fix by allowing flight in server properties. (I am mentioning this here, because I figured that might be the same reason, if not then I am sorry to mention a second issue)

Edit: I have tested now on Android, same issues, so there is a bigger issue because I can't join on anything. (besides Java)

### To Reproduce

1. Hosting a Spigot server on Nitrado.net
2. Installing GeyserMC and Floodgate through their interface
3. Joining server through Switch or PlayStation 4
4. Enjoy!

### Expected behaviour

This should not happen 

### Geyser Dump

https://dump.geysermc.org/axCxbHkmcHtMWAnVXoLnasN13oNGu2Mi

### Geyser Version

2.0.7-SNAPSHOT (git-master-33af9e0)

### Minecraft: Bedrock Edition Device/Version

1.19.20 (Switch, PS4, Android)

**Comment by Camotoy** [comment]
Please see #2861 for a workaround. Thanks!

**Comment by ElandaOfficial** [comment]
Unfortunately my hoster does not allow to add custom VM arguments. :/

**Comment by Camotoy** [comment]
Then unfortunately you're out of luck for now. The bug is a JDK issue and not something we can fix.
