### ISSUE TITLE
Bedrock lag issues

### ISSUE THREAD

**Issue by DogsMan010** [GeyserMC/Geyser#3236]
### Describe the bug

Bedrock has server lag while java its completely fine

### To Reproduce

*

### Expected behaviour

I want to play Bedrock without any server lag just like in Java

### Screenshots / Videos

File is too big so i had to upload to streamable

### Server Version and Plugins

This server is running Paper version git-Paper-130 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 4ba43fe)

### Geyser Version

1.19.2-R0.1-SNAPSHOT (Git: 4ba43fe)

### Minecraft: Bedrock Edition Device/Version

1.19.20 Windows 10

**Comment by Camotoy** [comment]
Closing this one as it doesn't have the Geyser dump.
