### ISSUE TITLE
Bedrock lag issues

### ISSUE THREAD

**Issue by DogsMan010** [GeyserMC/Geyser#3237]
### Describe the bug

Bedrock has server lag while java its completely fine

### To Reproduce

*

### Expected behaviour

I want to play Bedrock without any server lag just like in Java

### Screenshots / Videos

File is too big so i had to upload to streamable
https://streamable.com/4fh7v2

### Server Version and Plugins

This server is running Paper version git-Paper-130 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 4ba43fe)

### Geyser Dump

https://dump.geysermc.org/YG1Z1PxPuCYwoqghFzn7uw18imAutEPA

### Geyser Version

1.19.2-R0.1-SNAPSHOT (Git: 4ba43fe)

### Minecraft: Bedrock Edition Device/Version

1.19.20 Windows 10

**Comment by Camotoy** [comment]
Can you try without Floodgate and see if it produces the same result?

**Comment by DogsMan010** [comment]
> Can you try without Floodgate and see if it produces the same result?

How do i delete floodgate? (Sorry im new using GeyserMC

**Comment by Konicai** [comment]
Just remove floodgate from the plugins folder. Keep in mind that your bedrock players will then join with an offline mode UUID (because you're running offline-mode) instead of a floodgate UUID, so they won't have access to their existing data until you re-add floodgate.

**Comment by DogsMan010** [comment]
> Just remove floodgate from the plugins folder. Keep in mind that your bedrock players will then join with an offline mode UUID (because you're running offline-mode) instead of a floodgate UUID, so they won't have access to their existing data until you re-add floodgate.

Thanks i hope this works

**Comment by DogsMan010** [comment]
> Just remove floodgate from the plugins folder. Keep in mind that your bedrock players will then join with an offline mode UUID (because you're running offline-mode) instead of a floodgate UUID, so they won't have access to their existing data until you re-add floodgate.

Hey apparently it didnt work srry if i took too much time to respond now i cant join on bedrock it says "Unable to connect to the world"

**Comment by Konicai** [comment]
Connection issues can be solved on your Discord server, removing floodgate very likely didn't actually cause this

**Comment by Camotoy** [comment]
(Alternatively, the Geyser config is looking for Floodgate)

**Comment by DogsMan010** [comment]
> Connection issues can be solved on our Discord server, removing floodgate very likely didn't actually cause this (also don't worry about response times)

What's the invite?

**Comment by DogsMan010** [comment]
> Connection issues can be solved on our Discord server, removing floodgate very likely didn't actually cause this (also don't worry about response times)

Oh nvm but apparently the discord doesn't give support to any cracked servers

**Comment by DogsMan010** [comment]
> (Alternatively, the Geyser config is looking for Floodgate)

How can I fix that

**Comment by Konicai** [comment]
Ping me on the Discord (konica)

also please just make a single comment to make multiple replies

**Comment by DogsMan010** [comment]
> Ping me on the Discord (konica)
> 
> also please just make a single comment to make multiple replies

Thanks
