### ISSUE TITLE
Bedrock players cannot display the notice book.

### ISSUE THREAD

**Issue by fang2006-0643** [GeyserMC/Geyser#3239]
### Describe the bug

My server has a Notice book plug-in, which works normally for Java version players, but bedrock version players cannot display Notice book.
This plug-in is: https://www.mcbbs.net/thread-1370874-1-1.html
But there is no error prompt in my background.
I think this may be a problem with the player "translation" of the bedrock version.

### To Reproduce

Load geyser plug-in and Notice book plug-in.
And start the server.
Then, the bedrock version players have this problem.

### Expected behaviour

The Notice book plug-in can be displayed here in the bedrock version player

### Screenshots / Videos

![2022-08-18 (2)](https://user-images.githubusercontent.com/73422207/185407896-58d8ab09-546c-46d2-ac28-48480da3d4f8.jpg)

### Server Version and Plugins

 This server is running CraftBukkit version 3284a-Spigot-3892929-0ab8487 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/3jbf5AFUEKJWPYT7bHwt2mRUN8L0RHPH

### Geyser Version

2.0.7-SNAPSHOT (git-master-33af9e0)

### Minecraft: Bedrock Edition Device/Version

1.19.20 All platforms

**Comment by Camotoy** [comment]
This is a known limitation of Bedrock - see https://github.com/GeyserMC/Geyser/issues/1351. Unfortunately our only suggestion at this time is to send a Bedrock form instead.

**Comment by fang2006-0643** [comment]
Thank you for your reply. According to the situation of # 1351, I intend to replace it with the API provided by flodgate.
