### ISSUE TITLE
Infinite Death Screen

### ISSUE THREAD

**Issue by IceWaffles** [GeyserMC/Geyser#3240]
### Describe the bug

When a bedrock user dies, they're stuck on the death screen and cannot move or do anything. Leaving and rejoining sometimes do not help either (iirc, can't confirm). Attached a screenshot below.

### To Reproduce

There is no steady way to reproduce this bug, as it happens rarely and so incredibly randomly. I will note that the game rule for show death screen is off when this happens if that helps. This happens after a duel https://www.spigotmc.org/resources/duels.20171/ - but Java players are NOT affected at all. 

### Expected behaviour

Bedrock players to respawn normally.

### Screenshots / Videos

<img width="667" alt="image" src="https://user-images.githubusercontent.com/86599175/185710870-ec8c6078-8ee6-4a6a-bc63-b0bc958f18a4.png">

### Server Version and Plugins

1.18.2 paper (via version) and plugins are Duels (linked above), Geyser, and Floodgate.

### Geyser Version

This server is running Geyser version 2.0.6-SNAPSHOT (git-master-ef81bde) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.20)

### Minecraft: Bedrock Edition Device/Version

Latest as of writing

**Comment by Camotoy** [comment]
While we haven't made any changes in regards to respawning, you're not on the latest Geyser version so you may want to update.

**Comment by IceWaffles** [comment]
[21:44:21 INFO]: This server is running Geyser version 2.0.6-SNAPSHOT (git-master-ef81bde) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.20)
[21:44:21 INFO]: Checking version, please wait...
[21:44:21 INFO]: No updates available.

> While we haven't made any changes in regards to respawning, you're not on the latest Geyser version so you may want to update.

It does read latest...

[21:44:21 INFO]: This server is running Geyser version 2.0.6-SNAPSHOT (git-master-ef81bde) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.20)
[21:44:21 INFO]: Checking version, please wait...
[21:44:21 INFO]: No updates available.

**Comment by Camotoy** [comment]
Uhhhhh that's wrong.

**Comment by IceWaffles** [comment]
I'll update geyser and get back to you
