### ISSUE TITLE
Captcha won't show in chat

### ISSUE THREAD

**Issue by CreeperGamerGitHub** [GeyserMC/Geyser#3241]
### Describe the bug

I am using Switch version 14.1.2 and bedrock version 1.19.20. The captcha won't show. I am using BedrockConnect. Any help? Thanks!

### To Reproduce

Go to switch settings
go to your wifi's settings
change dns to manual
set primary dns to 104.238.130.180
go to mc > servers > any server
add geyserconnect.net with default port
go to a server
login
then the captcha doesn't show.

### Expected behaviour

Captcha to show in chat

### Server Version and Plugins

IDK. I was using GeyserConnect.net.

### Geyser Version

I don't know. it was GeyserConnect.net.

### Minecraft: Bedrock Edition Device/Version

Minecraft version 1.19.20, Switch Version 14.1.2

**Comment by Camotoy** [comment]
This is unfortunately not helpful without knowing what plugin creates the captcha.

**Comment by CreeperGamerGitHub** [comment]
> This is unfortunately not helpful without knowing what plugin creates the captcha.

i only know that the server was GeyserConnect.net, it's probably a problem on their end.

**Comment by Camotoy** [comment]
Yeah, we can't really do much here without knowing information about the server you're connecting to. I'm going to close this but if we get more info we can reproduce it, let me know.
