### ISSUE TITLE
How to make Geyser to listen to ipv6?

### ISSUE THREAD

**Issue by hb9eue** [GeyserMC/Geyser#3243]
### What feature do you want to see added?

The vanilla Java Server listens to ipv6 and ipv4. Java Clients preferably connect with Ipv6 and this works well.

After installing Geyser to allow Bedrock Clients to connect to my server, those fail to connect using the hostname which of course nowadays always point to dualstack ip addresses.

Using only ipv4 works.

Digging into the issue seems to show that Geyser only listens to IPv4 0.0.0.0 so I changed this to the more modern IPv6 notation "::" to tell it to listen to ANY IP Address.

```
bedrock:
  # The IP address that will listen for connections.
  # There is no reason to change this unless you want to limit what IPs can connect to your server.
  address: ::
  # The port that will listen for connections
  port: 19132
```

But the config parser does not like that notation. From the FAQ I read, that Geyser supports IPv4 and IPv6, but I fail to find any information how to make it listen on IPv6.

Please advise.

-Benoit-

### Are there any alternatives?

nope

**Comment by Camotoy** [comment]
We don't actively test IPv6 unfortunately, but last we checked I believe 0.0.0.0 worked for IPv4 and IPv6? Of course I could be wrong though.

**Comment by onebeastchris** [comment]
from https://github.com/GeyserMC/Geyser/issues/3547:
You can set address to 0:0:0:0:0:0:0:0 to make Geyser listen to ipv6. However, Geyser wont listen on both ipv4 and ipv6 simultaneously; see the issue above for details. 
Thanks anyway!

**Comment by Outfit8TSB** [comment]
in case of chris's idea, you have to use ipv6 in a seperate port UDP 19133(Recommended) using Geyser-Standalone. if you want to let geyser listen to both ipv6 and ipv4, do the following: 

1. make Geyser-Standalone listen to IPv6:19133
2. make Geyser-[PLUGIN] listen to IPv4:19132. you should Copy Your key.pem from floodgate folder and copy to your Geyser-Standalone directory. you might as well use Geyser in Server Directory.
or
1. Make Geyser-Standalone listen to IPv4:19132
2. Make Geyser-[PLUGIN] listen to IPv6:19133. you should Copy Your key.pem from floodgate folder and copy to your Geyser-Standalone directory. you might as well use Geyser in Server Directory.
i tested this with My own server software and it works. Consider Using both of Plugin and Standalone Version Of Geyser. if you are using floodgate, copy the keys to geyser folder. Consider running Server and Proxy in the same folder.
for server address part(java server), for plugins, set to auto and for standalone put your server address. for auth-type, install floodgate and keep it online for plugin, and set it to floodgate and copy key on standalone folder.

**Comment by intzaaa** [comment]
Port forwarding

**Comment by xfqwdsj** [comment]
By checking the code, I found Geyser uses Netty as its server framework, which supports binding both IPv4 and IPv6 addresses through the wildcard notation `[::]`.

In YAML configuration files, you need to explicitly define the value as a string type by adding quotation marks:
```yaml
address: "[::]"
```

Tested with Geyser `2.6.2-b793 (git-master-baac979)` and Minecraft `1.21.4`, and it works correctly.

**Comment by rudz70** [comment]
> We don't actively test IPv6 unfortunately, but last we checked I believe 0.0.0.0 worked for IPv4 and IPv6? Of course I could be wrong though.

I got it to work with 0.0.0.0 only - also for IPv6
0:0:0:0:0:0:0:0 and all its variances (::, with [], etc) do not work.
Geyser error message with ipv6 notation for address:

`[10:56:27] [GeyserServer-3-1/ERROR]: Failed to start Geyser on [::]:25565
[10:56:27] [GeyserServer-3-1/INFO]: [92mSuggestion: try setting `address` under `bedrock` in the Geyser config back to 0.0.0.0[0m
[10:56:27] [GeyserServer-3-1/INFO]: [92mThen, restart this server.[0m
[10:56:27] [Server thread/ERROR]: Could not pass event ServerLoadEvent to Geyser-Spigot v2.9.2-SNAPSHOT
java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed with error(-97): Address family not supported by protocol
`

Strangely, I did get it to work in a local network with Java & Bedrock sharing port 25565 - but that did not work through port forwarding of my router (and I had tcp and udp forwarded) - however after changing to a separate port for Bedrock (port 19132) with IP forwarding - ipv6 capable bedrock clients (ios for example) can connect from outside through my router, even though I have DS-light.
;o)

**Comment by rudz70** [comment]
> By checking the code, I found Geyser uses Netty as its server framework, which supports binding both IPv4 and IPv6 addresses through the wildcard notation `[::]`.
> 
> In YAML configuration files, you need to explicitly define the value as a string type by adding quotation marks:
> 
> address: "[::]"
> 
> Tested with Geyser `2.6.2-b793 (git-master-baac979)` and Minecraft `1.21.4`, and it works correctly.

This did not work for me with Geyser version 2.9.2-b1035 (git-master-f90c664) and Paper 1.21.11-97

Only address 0.0.0.0 works - but it also works for ipv6 - see other post in this thread.

**Comment by rudz70** [comment]
> from [#3547](https://github.com/GeyserMC/Geyser/issues/3547): You can set address to 0:0:0:0:0:0:0:0 to make Geyser listen to ipv6. However, Geyser wont listen on both ipv4 and ipv6 simultaneously; see the issue above for details. Thanks anyway!

This did not work for me with Geyser version 2.9.2-b1035 (git-master-f90c664) and Paper 1.21.11-97

Only address 0.0.0.0 works - but it also works for ipv6 - see other post in this thread.

**Comment by Robin-qwerty** [comment]
> By checking the code, I found Geyser uses Netty as its server framework, which supports binding both IPv4 and IPv6 addresses through the wildcard notation `[::]`.
> 
> In YAML configuration files, you need to explicitly define the value as a string type by adding quotation marks:
> 
> address: "[::]"
> 
> Tested with Geyser `2.6.2-b793 (git-master-baac979)` and Minecraft `1.21.4`, and it works correctly.


`address: "[::]"` and `address: 0:0:0:0:0:0:0:0` does not make ipv6 work for me, i have to actualy put in the full ipv6 addres of the server to make ipv6 work.

is there a working way to make geyser listen to both ipv4 and ipv6 on the same port? or is this ever gonna be added?

**Comment by Outfit8TSB** [comment]
> > By checking the code, I found Geyser uses Netty as its server framework, which supports binding both IPv4 and IPv6 addresses through the wildcard notation `[::]`.
> > 
> > In YAML configuration files, you need to explicitly define the value as a string type by adding quotation marks:
> > 
> > address: "[::]"
> > 
> > Tested with Geyser `2.6.2-b793 (git-master-baac979)` and Minecraft `1.21.4`, and it works correctly.
> 
> 
> `address: "[::]"` and `address: 0:0:0:0:0:0:0:0` does not make ipv6 work for me, i have to actualy put in the full ipv6 addres of the server to make ipv6 work.
> 
> is there a working way to make geyser listen to both ipv4 and ipv6 on the same port? or is this ever gonna be added?
> 

It already have. Use 0.0.0.0 instead.

**Comment by Outfit8TSB** [comment]
> > By checking the code, I found Geyser uses Netty as its server framework, which supports binding both IPv4 and IPv6 addresses through the wildcard notation `[::]`.
> > 
> > In YAML configuration files, you need to explicitly define the value as a string type by adding quotation marks:
> > 
> > address: "[::]"
> > 
> > Tested with Geyser `2.6.2-b793 (git-master-baac979)` and Minecraft `1.21.4`, and it works correctly.
> 
> 
> `address: "[::]"` and `address: 0:0:0:0:0:0:0:0` does not make ipv6 work for me, i have to actualy put in the full ipv6 addres of the server to make ipv6 work.
> 
> is there a working way to make geyser listen to both ipv4 and ipv6 on the same port? or is this ever gonna be added?
> 

It already have. Use 0.0.0.0 instead.

**Comment by Robin-qwerty** [comment]
> > > By checking the code, I found Geyser uses Netty as its server framework, which supports binding both IPv4 and IPv6 addresses through the wildcard notation `[::]`.
> > > 
> > > In YAML configuration files, you need to explicitly define the value as a string type by adding quotation marks:
> > > 
> > > address: "[::]"
> > > 
> > > Tested with Geyser `2.6.2-b793 (git-master-baac979)` and Minecraft `1.21.4`, and it works correctly.
> > 
> > 
> > `address: "[::]"` and `address: 0:0:0:0:0:0:0:0` does not make ipv6 work for me, i have to actualy put in the full ipv6 addres of the server to make ipv6 work.
> > 
> > is there a working way to make geyser listen to both ipv4 and ipv6 on the same port? or is this ever gonna be added?
> > 
> 
> It already have. Use 0.0.0.0 instead.
> 

When i use 0.0.0.0 i can not connect with bedrock using ipv6, it wil say that the client is having trouble establishing a connection to the multiplayer services.

**Comment by Outfit8TSB** [comment]
> > > > By checking the code, I found Geyser uses Netty as its server framework, which supports binding both IPv4 and IPv6 addresses through the wildcard notation `[::]`.
> > > > 
> > > > In YAML configuration files, you need to explicitly define the value as a string type by adding quotation marks:
> > > > 
> > > > address: "[::]"
> > > > 
> > > > Tested with Geyser `2.6.2-b793 (git-master-baac979)` and Minecraft `1.21.4`, and it works correctly.
> > > 
> > > 
> > > `address: "[::]"` and `address: 0:0:0:0:0:0:0:0` does not make ipv6 work for me, i have to actualy put in the full ipv6 addres of the server to make ipv6 work.
> > > 
> > > is there a working way to make geyser listen to both ipv4 and ipv6 on the same port? or is this ever gonna be added?
> > > 
> > 
> > It already have. Use 0.0.0.0 instead.
> > 
> 
> When i use 0.0.0.0 i can not connect with bedrock using ipv6, it wil say that the client is having trouble establishing a connection to the multiplayer services.

If that's the case, I don't know the solution.

**Comment by rudz70** [comment]
> > By checking the code, I found Geyser uses Netty as its server framework, which supports binding both IPv4 and IPv6 addresses through the wildcard notation `[::]`.
> > In YAML configuration files, you need to explicitly define the value as a string type by adding quotation marks:
> > address: "[::]"
> > Tested with Geyser `2.6.2-b793 (git-master-baac979)` and Minecraft `1.21.4`, and it works correctly.
> 
> `address: "[::]"` and `address: 0:0:0:0:0:0:0:0` does not make ipv6 work for me, i have to actualy put in the full ipv6 addres of the server to make ipv6 work.
> 
> is there a working way to make geyser listen to both ipv4 and ipv6 on the same port? or is this ever gonna be added?

0.0.0.0 worked for me as well - for both IPv4 and v6

**Comment by rudz70** [comment]
> > > > By checking the code, I found Geyser uses Netty as its server framework, which supports binding both IPv4 and IPv6 addresses through the wildcard notation `[::]`.
> > > > In YAML configuration files, you need to explicitly define the value as a string type by adding quotation marks:
> > > > address: "[::]"
> > > > Tested with Geyser `2.6.2-b793 (git-master-baac979)` and Minecraft `1.21.4`, and it works correctly.
> > > 
> > > 
> > > `address: "[::]"` and `address: 0:0:0:0:0:0:0:0` does not make ipv6 work for me, i have to actualy put in the full ipv6 addres of the server to make ipv6 work.
> > > is there a working way to make geyser listen to both ipv4 and ipv6 on the same port? or is this ever gonna be added?
> > 
> > 
> > It already have. Use 0.0.0.0 instead.
> 
> When i use 0.0.0.0 i can not connect with bedrock using ipv6, it wil say that the client is having trouble establishing a connection to the multiplayer services.

It works for me - and I use different ports for Bedrock and Java (standard ports). I first used the Java port also for Bedrock, and that did not work - but when I changed Geyser to the regular bedrock port, it started working.
Of course, I needed to configure port forwarding for both ports...

**Comment by Robin-qwerty** [comment]
> > > > > By checking the code, I found Geyser uses Netty as its server framework, which supports binding both IPv4 and IPv6 addresses through the wildcard notation `[::]`.
> > > > > In YAML configuration files, you need to explicitly define the value as a string type by adding quotation marks:
> > > > > address: "[::]"
> > > > > Tested with Geyser `2.6.2-b793 (git-master-baac979)` and Minecraft `1.21.4`, and it works correctly.
> > > > 
> > > > 
> > > > `address: "[::]"` and `address: 0:0:0:0:0:0:0:0` does not make ipv6 work for me, i have to actualy put in the full ipv6 addres of the server to make ipv6 work.
> > > > is there a working way to make geyser listen to both ipv4 and ipv6 on the same port? or is this ever gonna be added?
> > > 
> > > 
> > > It already have. Use 0.0.0.0 instead.
> > 
> > When i use 0.0.0.0 i can not connect with bedrock using ipv6, it wil say that the client is having trouble establishing a connection to the multiplayer services.
> 
> It works for me - and I use different ports for Bedrock and Java (standard ports). I first used the Java port also for Bedrock, and that did not work - but when I changed Geyser to the regular bedrock port, it started working.
> Of course, I needed to configure port forwarding for both ports...

Ye i use 19132 for bedrock, and for ipv4 it works fine and for ipv6 it only works when i put the ipv6 address of the server in the geyser config, but then ipv4 doesn't work anymore ofcourse.

What geyser and velocity version you use? I just checked and both of mine are the latest available.

**Comment by rudz70** [comment]
> > > > > > By checking the code, I found Geyser uses Netty as its server framework, which supports binding both IPv4 and IPv6 addresses through the wildcard notation `[::]`.
> > > > > > In YAML configuration files, you need to explicitly define the value as a string type by adding quotation marks:
> > > > > > address: "[::]"
> > > > > > Tested with Geyser `2.6.2-b793 (git-master-baac979)` and Minecraft `1.21.4`, and it works correctly.
> > > > > 
> > > > > 
> > > > > `address: "[::]"` and `address: 0:0:0:0:0:0:0:0` does not make ipv6 work for me, i have to actualy put in the full ipv6 addres of the server to make ipv6 work.
> > > > > is there a working way to make geyser listen to both ipv4 and ipv6 on the same port? or is this ever gonna be added?
> > > > 
> > > > 
> > > > It already have. Use 0.0.0.0 instead.
> > > 
> > > 
> > > When i use 0.0.0.0 i can not connect with bedrock using ipv6, it wil say that the client is having trouble establishing a connection to the multiplayer services.
> > 
> > 
> > It works for me - and I use different ports for Bedrock and Java (standard ports). I first used the Java port also for Bedrock, and that did not work - but when I changed Geyser to the regular bedrock port, it started working.
> > Of course, I needed to configure port forwarding for both ports...
> 
> Ye i use 19132 for bedrock, and for ipv4 it works fine and for ipv6 it only works when i put the ipv6 address of the server in the geyser config, but then ipv4 doesn't work anymore ofcourse.
> 
> What geyser and velocity version you use? I just checked and both of mine are the latest available.

Geyser-Spigot v2.9.2-SNAPSHOT
But not velocity…
Is that an alternative to floodgate? That’s what I am using. Latest version - at least a few weeks ago…

**Comment by hb9eue** [comment]
Hi

As the original reporter of this issue. Maybe this is an OS issue. But on Linux (with ipv6 sockets automatically also listening on ipv4 enabled) I do not seem to be able to reproduce, but I did not fully test. I have no bedrock client laying around at the moment.

plugins/Geyser-Spigot/config.yml

```
bedrock:
  # The IP address that will listen for connections.
  # There is no reason to change this unless you want to limit what IPs can connect to your server.
  address: 0.0.0.0
  # The port that will listen for connections
  port: 19132
```

```
remote:
  # The IP address of the remote (Java Edition) server
  # If it is "auto", for standalone version the remote address will be set to 127.0.0.1,
  # for plugin versions, it is recommended to keep this as "auto" so Geyser will automatically configure address, port, and auth-type.
  # Leave as "auto" if floodgate is installed.
  address: auto
  # The port of the remote (Java Edition) server
  # For plugin versions, if address has been set to "auto", the port will also follow the server's listening port.
  port: 25565
```

```
grep server server.properties
[...]
server-ip=
server-port=25565
```

```
# LANG=C; netstat -anp | grep java
tcp6       0      0 :::25565                :::*                    LISTEN      1420768/java        
udp6       0      0 :::19132                :::*                                1420768/java        
udp6       0      0 :::19132                :::*                                1420768/java
```

**Comment by Robin-qwerty** [comment]
i found out what the problem is, my ubuntu server has multiple(6) ipv6 addreses and apperently geyser is only listening to the first one, i was using one of the other ipv6 addreses. I think i have so many ipv6 addresses because i have some privacy setting on in ubuntu that gives me temporary IPv6 addresses.

i was using a velocity minecraft proxy with the velocity version of geyser, tought that that might had been the issue, but it was my own fault all this time.

**Comment by hb9eue** [comment]
Oh yeah, I also stumbled over that issue. Ubuntu is a 'Desktop' operating system not aimed at operating a server. Therefore they turned IPv6 privacy on by default, which causes the ipv6 addresses to be created temporarily and rotating randomly, which is fine for a client, but not for a server.

Debian unfortunately also has switched to this scheme some time ago.

Turn IPv6 privacy off, when operating a server which has to be reachable with a DNS published IP address.
