### ISSUE TITLE
Bedrock users experiencing major lag after update.

### ISSUE THREAD

**Issue by TheRealArchie** [GeyserMC/Geyser#3244]
### Describe the bug

Bedrock players have major lag/latency issues. The videos should explain it better. 
Worked fine before. Server TPS is 20. You can see one of the players using the /ping command to test the player-to-server connection.

### To Reproduce

1. Install Purpur 1.19.2 (git-Purpur-1761 (MC: 1.19.2))
2. Install GeyserMC (2.0.7-SNAPSHOT (git-master-33af9e0))
3. Install Floodgate (latest)
4. Play on a bedrock account

### Expected behaviour

For this not to happen.

### Screenshots / Videos

https://imgur.com/a/7PSTZm9

### Server Version and Plugins

git-Purpur-1761 (MC: 1.19.2)

Plugins[25]: BannerMaker, CommandPanels, CoreProtect, DiscordSRV, dynmap, Dynmap-WorldGuard, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, floodgate, Images, LuckPerms, NoEncryption, PlaceholderAPI, QualityArmory, Simple-Drugs, spark, squaremap, squaremap-worldguard, TAB, Vault, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

https://dump.geysermc.org/UaoqzKxTBbjtS76l7btLUi66yfMPtZAO

### Geyser Version

2.0.7-SNAPSHOT (git-master-33af9e0)

### Minecraft: Bedrock Edition Device/Version

Switch and consoles

**Comment by TheRealArchie** [comment]
GeyserMC and Floodgate is installed on a network not controlled by ourselves. Floodgate was installed extra here for the fwhitelist command as recommended by one of the devs last time I had asked.

**Comment by Camotoy** [comment]
We've been receiving some reports that people have seen lag after updating to 1.19.2. I have absolutely no leads other than it happens on 1.19.2 and not 1.19.1. Can you try with no other plugins?

**Comment by TheRealArchie** [comment]
I don't think I can really. Don't wanna break the server.

**Comment by Camotoy** [comment]
I'm going to close this as #3233 describes the same issue. I'm definitely lost on where to look next so maybe it's a specific platform or setting that needs to be enabled?

**Comment by TheRealArchie** [comment]
@Camotoy Maybe its this? https://github.com/GeyserMC/Geyser/commit/1d3eebc678be9a17fb71141bdacd933c13477f0c

**Comment by Camotoy** [comment]
I believe all of that code is reliant only on the client and not anything that the server does. Even so, I don't understand what would have changed in 1.19.2.

**Comment by TheRealArchie** [comment]
@Camotoy well it could be a client issue, no? Just misclassified?
