### ISSUE TITLE
IP Redaction Config

### ISSUE THREAD

**Issue by xXTheBigBearXx** [GeyserMC/Geyser#3246]
### What feature do you want to see added?

Recent versions of Paper & Velocity (Possibly BungeeCord too; haven't checked) contain a config option to prevent the Logging of IP Address' - Replacing them with "IP Withheld".

However with Geyser installed on Paper or Velocity, upon a Bedrock player joining; Geyser still logs their IP address.

Would it be possible for a similar config to be added, or for Geyser to respect the Server's config?

### Are there any alternatives?

I do not think there is any alternatives.

**Comment by Camotoy** [comment]
This is definitely feasible. But what's the motive for it?

**Comment by xXTheBigBearXx** [comment]
Just to give the players that little bit more privacy. 
As the Server I'm hosting is for a Friend's stream viewers, it would allow them to potentially feel safer joining the server if they know their IPs are not being logged.

Personally I feel that these configs should be default to false across the board, as the majority of the time there is no need for a Server to log IPs.
