### ISSUE TITLE
Bedrock Player cannot join server

### ISSUE THREAD

**Issue by SinonCute** [GeyserMC/Geyser#3247]
### Describe the bug

When u start the BungeeCord some player cant connect to the server at the second time join (they need to restart bungee to join)
When they join the second time it will said "[IP] tried to connect"
I still can ping and see the motd

### To Reproduce

Start BungeeCord
Join the server
out
Join again ( can ping and see the motd) but  cannot join and the screen just loading and loading....

### Expected behaviour

All player can join normally

### Screenshots / Videos

[08:05:15 INFO] [Geyser-BungeeCord]: /xxx.xx.xx.xx:56512 tried to connect!
![image](https://user-images.githubusercontent.com/81401485/186105834-e41d87ca-fd4c-499e-8dff-467f1a831162.png)

### Server Version and Plugins

Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:9c9bc55:502

### Geyser Dump

https://dump.geysermc.org/VTaq78GHhks9m3w02KTCz1aCUTLAhjck

### Geyser Version

Geyser version 2.0.7-SNAPSHOT (git-master-8241197) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.20)

**Comment by onebeastchris** [comment]
This is likely a configuration issue. See the links below for help:
https://wiki.geysermc.org/geyser/setup/
https://wiki.geysermc.org/geyser/fixing-unable-to-connect-to-world/
If those dont work; join our discord server and ask for help there:
https://discord.com/invite/geysermc
