### ISSUE TITLE
Cannot join on 1.19.21

### ISSUE THREAD

**Issue by Trains77** [GeyserMC/Geyser#3248]
### Describe the bug

Players on version 1.19.21 cannot connect to the server with an "Outdated Geyser Proxy" error

### To Reproduce

Update to Android 1.19.21

Connect to GeyserMC Proxy

Get kicked for having an outdated proxy

### Expected behaviour

Players are able to connect to the server on version 1.19.21

### Server Version and Plugins

Server Version: git-PufferfishPlus-11 (MC: 1.19.2)

### Geyser Dump

https://dump.geysermc.org/Nsodmte6VkkJBgt6wcC8OwKItt4yAB7I

### Geyser Version

Geyser version 2.0.7-SNAPSHOT (git-master-8241197) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.20)

### Minecraft: Bedrock Edition Device/Version

1.19.21, Android

### Additional Context

It appears Mojang made this version incompatible with 1.19.20 servers, as I also could not connect to any Featured Servers with an outdated server error

**Comment by Camotoy** [comment]
As you stated yourself, yeah, everyone was kind of caught off guard by this. We're aware.

**Comment by Camotoy** [comment]
The next version (currently building) will allow 1.19.21 clients to connect.
