### ISSUE TITLE
Pressing 'Cancel' while joining throws an error

### ISSUE THREAD

**Issue by 7man7LMYT** [GeyserMC/Geyser#3251]
### Describe the bug

Pressing the 'Cancel' button disconnects the client normally but produces an error in the server console as a result.

### To Reproduce

1. Join a server
2. During 'Locating Server', press 'Cancel'
3. Error

### Expected behaviour

For there to be no error in my server console

### Server Version and Plugins

Velocity version: `Velocity 3.1.2-SNAPSHOT (git-cae41c33-b177)`
Velocity plugins: `floodgate, geyser, luckperms, pistonmotd`

### Geyser Dump

https://dump.geysermc.org/q149hVikq4cZbyNQYe0plfTkZ2uDdCxq

### Geyser Version

Geyser version 2.0.7-SNAPSHOT (git-master-8dde4b4)

### Minecraft: Bedrock Edition Device/Version

1.19.21

### Additional Context

[Link to error just in case](https://paste.gg/f0fbb21253884c489a79d374228a8ea8)

**Comment by Jens-Co** [comment]
![image](https://github.com/GeyserMC/Geyser/assets/63231928/e81c08b8-91f8-481e-885c-286c9a3c5ab6)

mind testing again to see if this is still a thing? tried but to no avail.

**Comment by onebeastchris** [comment]
Closing due to no response :(
