### ISSUE TITLE
Sound "block.note_block.basedrum" is not played on Bedrock

### ISSUE THREAD

**Issue by Xeltica** [GeyserMC/Geyser#3252]
### Describe the bug

The sound ID:`block.note_block.basedrum` is not played on Minecraft:BE via Geyser.

It reproduces by both note-block and `/playsound`.

#### Using the command

1. `/playsound minecraft:block.note_block.basedrum player @p ~ ~ ~`

#### Using the block

1. Place a stone
2. Place a note block on the stone
3. Active the note block

### Expected behaviour

Sound plays normally

### Server Version and Plugins

Server Version: Minecraft 1.18.2 (Purpur 1632)
Plugins:
* AdvancedBan
* BackToTheRoots
* BlockHat
* BonemealPlus
* ChestCleaner
* Citizens
* CMILib
* CoreProtect
* DiscordSRV
* dynmap
* EbiFly
* FastChunkPregenerator
* floodgate,
* Geyser-Spigot
* GSit
* Harbor
* HolographicDisplays
* Jecon
* kotlin-stdlib
* LuckPerms
* LunaChat
* LWC
* MOTD
* Multiverse-Core
* Multiverse-Inventories
* Multiverse-NetherPortals
* NBTAPI
* NickNames
* NoteBlockAPI
* NoteBlockMusicPlayer
* OpenInv
* PermissionGamemode
* PlaceholderAPI
* PlugmanX
* PowerNBT
* ProtocolLib
* Scoreboard-revision
* ServerRestorer
* ServerTap
* Shop
* UltimateTimber
* Vault
* ViaVersion
* VoidGen
* VotingPlugin
* WorldEdit
* WorldGuard
* XCore
* YamipaPlugin

### Geyser Dump

https://dump.geysermc.org/PK6hIawsYTjkguAJo9C9GEtiauFOJmc9

### Geyser Version

2.0.7-SNAPSHOT (git-master-8dde4b4)

### Minecraft: Bedrock Edition Device/Version

Minecraft for Windows 1.19.21

**Comment by TypicalShavonne** [comment]
i asssume block.note_block.basedrum sound doesnt exist on minecraft BE, this could be fixed through GeyserOptionalPack
