### ISSUE TITLE
Packet Downstream Error

### ISSUE THREAD

**Issue by el211** [GeyserMC/Geyser#3253]
### Describe the bug

I am using Extension Branch of geyser
I use model engine 
whenever i load a mob i get instantly kicked and cant join server anymore 
here is the error i get
[message_1.txt](https://github.com/GeyserMC/Geyser/files/9424848/message_1.txt)

### To Reproduce

1 load mob with model engine
2 kicks us form game
3 cant join server anymore (connection error)

### Expected behaviour

i expected to stay in game and not get kicked and be able to use plugin

### Server Version and Plugins

version
[15:05:53 INFO]: Checking version, please wait...
[15:05:54 INFO]: Current: git-Purpur-1632 (MC: 1.18.2)*
* You are running the latest version
[message_1.txt](https://github.com/GeyserMC/Geyser/files/9425020/message_1.txt)

### Geyser Dump

i cannot collect dump getting an error

### Geyser Version

Geyser-BungeeCord version 2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

pc

**Comment by el211** [comment]
UPDATE : this issue also happens with normal geyser (not only extension )
here is the geyser dump i could get form normal geyser 
https://dump.geysermc.org/jzj0aJ5P9yLHfE7neWxyBmDOeWis2Hlv

**Comment by Camotoy** [comment]
Is this still an issue?

**Comment by onebeastchris** [comment]
Closing due to no response.
