### ISSUE TITLE
Geyser may not be able to translate the menu in TrMenu normally.

### ISSUE THREAD

**Issue by fang2006-0643** [GeyserMC/Geyser#3254]
### Describe the bug

As shown in my video, the bedrock player cannot see the items in the menu.
TrMenu: https://github.com/InsinuateProjects/TrMenu

### To Reproduce

Let the bedrock player open the menu provided by the trmenu plug-in.
Then the problem arises: the contents of the menu cannot be displayed

### Expected behaviour

Hope to translate the menu normally for bedrock version players.

### Screenshots / Videos

https://user-images.githubusercontent.com/73422207/186885741-5aa0e471-a73b-4c54-a729-aa36cac698c6.mp4

### Server Version and Plugins

This server is running CraftBukkit version 3284a-Spigot-3892929-0ab8487 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
TrMenu 
floodgate
Znpcs

### Geyser Dump

https://dump.geysermc.org/Y2TayQ7AYZOdasSCinylnZJFrGBm5F6j

### Geyser Version

2.0.7-SNAPSHOT (git-master-b7337fa)

### Minecraft: Bedrock Edition Device/Version

1.19.21

**Comment by Camotoy** [comment]
Can you share your TrMenu menu configuration?

**Comment by fang2006-0643** [comment]
[trmenu confirm.zip](https://github.com/GeyserMC/Geyser/files/9434503/trmenu.confirm.zip)


> 您可以共享您的 TrMenu 菜单配置吗？

**Comment by Camotoy** [comment]
We think we have a fix for this, so we'll push this within the next day. I'll publish my own replication steps for future reference:

Use Paper 1.17.1 and install PlaceholderAPI and TrMenu from https://repo.mcage.cn/repository/maven-public/me/arasple/mc/trmenu/trmenu/3.1.9/trmenu-3.1.9.jar. Copy at least the `menus` folder from the configs provided and run `trmenu open servers PLAYERNAME`
