### ISSUE TITLE
Per World Resource Pack Support 

### ISSUE THREAD

**Issue by BobtheBob123456** [GeyserMC/Geyser#3256]
### What feature do you want to see added?

Basically, if a server uses multiple worlds, then players would have the option to have one resource packs for each world.

### Are there any alternatives?

Having one resource pack for bedrock players for the entire world.

**Comment by Konicai** [comment]
This is basically covered by #210, as well as #2005 and #2912 (switching backend servers isn't much different than switching worlds in this context)
