### ISSUE TITLE
Error spamming console on Bungeecord

### ISSUE THREAD

**Issue by abhisantos** [GeyserMC/Geyser#3258]
### Describe the bug

Using Geyser-Bungeecord with Waterfall 1.19.
The Spigot servers vary from 1.8.8, to 1.17.1, 1.18 and 1.19

This error is spamming the bungeecord console all day long, non stop:

28.08 15:42:52 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
28.08 15:42:52 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
28.08 15:42:53 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.
28.08 15:42:53 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType.

### To Reproduce

Use Geyser-Bungeecord with Waterfall 1.19

### Expected behaviour

Not having this error spamming 24/7, like before.

### Server Version and Plugins

Geyser version 2.0.7-SNAPSHOT (git-master-8dde4b4).
Waterfall 1.19

Spigot servers from 1.8.8, 1.18, 1.19

### Geyser Dump

https://dump.geysermc.org/1WcL9OlmWf810lugnPtTpGcrXdHyAEKf

### Geyser Version

Geyser version 2.0.7-SNAPSHOT (git-master-8dde4b4).

**Comment by Camotoy** [comment]
Do you have wardens or sculk sensors anywhere? This is most likely related to one of those two so it's probably not the 1.8 server.

**Comment by abhisantos** [comment]
> 
Yes there is a Survival 1.19 and a 1.19.2. Both spigot

**Comment by abhisantos** [comment]
>
Yes there is a 1.19 survival and also a 1.19.2, both spigot

**Comment by abhisantos** [comment]
The error keeps spamming the console 24/7 

"06.09 00:06:55 [Server]  [Geyser-BungeeCord]: Downstream packet error! Value minecraft: has no mapping for key class com.github.steveice10.mc.protocol.data.game.level.particle.positionsource.PositionSourceType."

**Comment by gamer50082** [comment]
Why spigot use paper more efficient and better in some ways

**Comment by onebeastchris** [comment]
Does this issue still persist when using the latest version of Geyser?

**Comment by onebeastchris** [comment]
Closing as stale.
