### ISSUE TITLE
Canceling an InventoryOpenEvent in the Bukkit API doesn't work for Geyser players

### ISSUE THREAD

**Issue by consllogluke** [GeyserMC/Geyser#326]
**Describe the bug**

Running `InventoryOpenEvent#setCancelled​(boolean cancel)` in the Bukkit API cancels the event and doesn't open the inventory for Java players, but for Bedrock players who joined through Geyser, the inventory still opens.

**To Reproduce**

1. Create a simple Bukkit/Spigot/Paper plugin
2. Register an `InventoryOpenEvent` and inside, call `event.setCancelled(true)`
3. Load the plugin and try opening an inventory (I've only tested it with cartography table inventory)

**Expected behavior**

I expect the `InventoryOpenEvent` to be canceled, and the inventory to never be opened.

**Server Version**

`This server is running Paper version git-Paper-168 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

**Geyser Version**

I merged the `inventory` branch (the version we're using is from commit 605c9ef) and the `feature/entity-mounts` branch (commit 6eda36b). We're using the Bukkit version of Geyser.

**Minecraft: Bedrock Edition Version**

1.14.30

**Comment by RednedEpic** [comment]
Seems to be resolved from my testing.
