### ISSUE TITLE
lodestone not working

### ISSUE THREAD

**Issue by Bobby99as** [GeyserMC/Geyser#3262]
### Describe the bug

when using the lodestone it does not enchant the compass

### To Reproduce

Make lodestone
Use lodestone

### Expected behaviour

Compass points to lodestone

### Server Version and Plugins

Paper version git-Paper-102 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: e0486ae)

### Geyser Dump

https://dump.geysermc.org/FLNBvNy4LhcAKidXmYWqnvFnRnWMR3qg

### Geyser Version

2.0.7-SNAPSHOT (git-master-670308e)

### Minecraft: Bedrock Edition Device/Version

Xbox 1.19.2

**Comment by Bobby99as** [comment]
This seems specific to Xbox might be the same on PS4. It works on windows 10 Minecraft

**Comment by onebeastchris** [comment]
it also works on mobile bedrock, so it's likely console specific

**Comment by Camotoy** [comment]
If it's specific to platforms then I don't think it's our issue. Can you try on a singleplayer world and see if you get different results?

**Comment by Bobby99as** [comment]
It works on single player

**Comment by Bobby99as** [comment]
apparently removing Minecraft on the Xbox and reinstalling it fixed it
