### ISSUE TITLE
Changing worlds teleports player to 0 32k 0

### ISSUE THREAD

**Issue by DuneSciFye** [GeyserMC/Geyser#3265]
### Describe the bug

Having multiple issues where people do [/is go] to go to their island on my Skyblock server and they get teleported to 0 32k 0 or something like that, basically 0 0 with super high y
Multiple people having this issue. After a while some people get teleported to their island, others never get teleported

### To Reproduce

1. Change world

### Expected behaviour

Go to location and not 0 32k 0

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/65089425/188280525-b9282e9e-37b1-4899-80dc-a927f9010945.png)
![image](https://user-images.githubusercontent.com/65089425/188280541-22d0c2ad-3763-48f3-9d5a-b2e8cbc37eca.png)

### Server Version and Plugins

git-Purpur-1765 (MC:1.19.2)

Plugins (89): AdvancedEnchantments, AdvancedPortals, AdvancedReplay, AnotherDailyBonus, AntiCheatReplay, AntiDrop, AuctionHouse, AureliumSkills, AutoPickup, BuycraftX, ChatSentry, ChestProtect, ChunkVisualizer, Citizens, CommandPrompter, CommandWhitelist, ConsoleLogs, ConsoleSpamFix, CoreProtect, CraftBook, CrossplatForms, CustomCrafting, CyberLevels, CyberStatistics, DecentHolograms, DeluxeMenus, DeluxeShop, DiscordSRV, Essentials, EssentialsSpawn, ExcellentCrates, ExecutableItems, GSit, GadgetsMenu, GeyserHacks, HopperSorter, ImageOnMap, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, JSEngine, JetsAntiAFKPro, JetsMinions, KixsAutoAnnouncerPremium, KixsChatGames, LibsDisguises, LinkedPortals, LiteBans, LuckPerms, Markets, Multiverse-Core, Multiverse-Inventories, MyCommand, NexEngine, OpenInv, PlaceholderAPI, PlayerPoints, PocketGames, ProtocolLib, PyroFishingPro, PyroLib, Quests, SCore, ServerUtils, StaffTools, SuperiorSkyblock2, TAB, Themis, TradeSystem, UltraRegions, UpgradeableSpawners, Vault, VentureChat, VentureChatWorkaround, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WanderingTrades, WildChests, WolfyUtilities, WorldChangeScreenRemover, WorldEdit, WorldGuard, WorldGuardExtraFlags, ajLeaderboards, floodgate and spark

### Geyser Version

Geyser-Velocity 2.0.7-SNAPSHOT (git-master-f8a83f9)

**Comment by onebeastchris** [comment]
This looks like server behavior, not Geysers - to make sure, please try the plugin debugging steps as listed below.

- Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by onebeastchris** [comment]
Closing as stale.
