### ISSUE TITLE
Strange ghost block behavior

### ISSUE THREAD

**Issue by ViaBackwards** [GeyserMC/Geyser#3270]
### Describe the bug

When I am instantly breaking flowers, they are replaced with a grass ghost blocks for some reason.

### To Reproduce

instant mine dandelions

### Expected behaviour

Breaking the flowers should leave nothing behind

### Screenshots / Videos

https://streamable.com/s2ek1n

### Server Version and Plugins

This server is running Paper version git-Paper-102 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: e0486ae)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-83 (MC: 1.19.1)

### Geyser Version

2.0.7-SNAPSHOT

**Comment by Camotoy** [comment]
I suspect this is the same issue as #3198 so I'm closing this for now.
