### ISSUE TITLE
Not able to open inventories when above y 317

### ISSUE THREAD

**Issue by DuneSciFye** [GeyserMC/Geyser#3271]
### Describe the bug

When you fly up to y 317 or higher, and try to open an inventory like opening a chest, it won't open the chest and you won't be able to open any more inventories at all even if you go back down until you relog

### To Reproduce

1. Place a chest at build limit
2. Go above the chest
3. Open the chest

### Expected behaviour

You should be able to open the chest

### Screenshots / Videos

https://user-images.githubusercontent.com/65089425/188755187-77470b6f-f859-4fc9-a624-e91ee42260d1.mp4

### Geyser Version

Geyser-Velocity 2.0.7-SNAPSHOT (git-master-f8a83f9)

**Comment by valaphee** [comment]
I think this bug is not fixable, because every inventory needs a block to be placed, but 9x1, 9x2 and 9x3 inventories could be replaced with entity-based inventories.

I'll test it.

**Comment by Camotoy** [comment]
Fixed by 5ddb0ad.
