### ISSUE TITLE
Geyser not reading IP address

### ISSUE THREAD

**Issue by HeroDestrin** [GeyserMC/Geyser#3273]
### Describe the bug

When the server is starting, Geyser will issue a console warning stating that it failed to start on the server's IP. It then gives a message "Suggestion: try setting `address` under `bedrock` in the Geyser config back to [server IP]" and then disabled the plugin. But when I set the address to the server's IP, it will enable and issue no warnings, yet it won't allow bedrock players to join. Everything is up to date otherwise and ViaVersion is installed to allow newer clients to join, so I don't know what the issue is.

### To Reproduce

1. Download the newest stable build of Geyser
2. Restart the Minecraft server (using Apex Hosting)
3. Set up the config file using the newest stable build of Floodgate
4. Restart the server again
5. Scroll up in the console and cry that it's not working

### Expected behaviour

I expected Geyser to start as it did before I upgraded my server. Nothing changed except for the server IP, and I entered that into the config with no changes to the format or anything.

### Server Version and Plugins

[Server] INFO Plugins (27): ButterBurn, ClearLag, CommandPanels, CoreProtect, DecentHolograms, DestrinBlockManager, DestrinBuildings, DestrinEffects, DestrinEnchants, DestrinPossess, DestrinPushBack, DestrinUpsideDown, DestrinVecna, Essentials, EssentialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, GriefPrevention, GSit, LuckPerms, NBTAPI, Vault, ViaVersion, WorldEdit, WorldGuard, ZCQTalent

(a lot of these plugins are custom made by a very large man)

[Server] INFO This server is running Paper version git-Paper-12 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 3d37b42)
06.09 23:45:30 [Server] INFO You are 69 version(s) behind
06.09 23:45:30 [Server] INFO Download the new version at: https://papermc.io/downloads
06.09 23:45:30 [Server] INFO Previous version: git-Paper-299 (MC: 1.18.2)

### Geyser Version

Build #1188 (Sep 3, 2022, 7:13:04 PM)

### Minecraft: Bedrock Edition Device/Version

1.19.2 Pocket Edition

### Additional Context

I had just updated the server from 6GB Ram to 16GB Ram, and the whole FTP was copied into the new server. I changed the plugins that referenced the server's IP or Port, including Geyser - and yet Geyser is the only one that's failed.

**Comment by Camotoy** [comment]
> Suggestion: try setting address under bedrock in the Geyser config back to [server IP]
The IP in that message should always say `0.0.0.0`. Otherwise, there's some funky plugin hackery going on or something.

**Comment by Camotoy** [comment]
If it's still not working, perhaps try with a clean config - specifically the MOTD should be reset.

**Comment by Konicai** [comment]
This just seems like a firewall issue related to upgrading to a fresh server on Apex. If you still experience this specific issue, consider contacting us on Discord.
