### ISSUE TITLE
Players can't access the server correctly.

### ISSUE THREAD

**Issue by PonderFox0643** [GeyserMC/Geyser#3274]
### Describe the bug

If I use win10 bedrock version to access the server, I can access it.
If I use my mobile phone to enter the server, it will not be able to enter normally and will prompt "[phone player.txt](https://github.com/GeyserMC/Geyser/files/9501959/phone.player.txt)"
I changed my skin to 64x. Although I didn't continue to report errors, I still couldn't get in.
I heard that other players also encountered this problem when they entered my server.
（This problem is not limited to mobile phone players.）

### To Reproduce

1strat server
2Let other players in
3Then there was a problem

### Expected behaviour

I hope mobile phone players can enter normally.

### Screenshots / Videos

https://user-images.githubusercontent.com/73422207/188771561-97996b0c-8c20-4797-b1fa-2b6ad26deb43.mp4

https://user-images.githubusercontent.com/73422207/188772229-bbbe0373-7199-4d0d-b2ce-f268de79ce9f.mp4

### Server Version and Plugins

BC(waterfall-1.19-504) plugin: AdvancedNMotd-9.2.0 Bungee-Reconnect-1.6.3 floodgate-bungee Geyser-BungeeCord LuckPerms-Bungee-5.4.40 PlaceholderAPI-2.11.2 SkinsRestorer
lobby(version 3284a-Spigot-3892929-0ab8487 (MC: 1.17.1) (Implementing API vers
ion 1.17.1-R0.1-SNAPSHOT)) plugin:PlaceholderAPI, Stp, NoteBlockAPI, Notice, ViaVersion, tpLogin, floodgate, ServersNPC, Protoc
olLib, JukeBox, LuckPerms, BEMenuAPI, HolographicDisplays, Vault, Multiverse-Core, TrMenu, SuperLobby, WorldEdit, Skript, ChestCommands, skr
ipt-reflect, Floodgate-Skript

### Geyser Dump

https://dump.geysermc.org/X89yNRek6JJqWo5HXwZhjDtpv3PsxQtZ

### Geyser Version

2.0.7-SNAPSHOT (git-master-a16fc9c)

### Minecraft: Bedrock Edition Device/Version

1.19.21 Android（uncertain）

### Additional Context

[win10 player .txt](https://github.com/GeyserMC/Geyser/files/9501958/win10.player.txt)
[phone player.txt](https://github.com/GeyserMC/Geyser/files/9501959/phone.player.txt)

**Comment by onebeastchris** [comment]
Could you try updating to the latest version of Geyser, and see if the issue persists?
If it does, send a new Geyser dump by running "geyser dump" in your server console.

**Comment by onebeastchris** [comment]
Closing due to no response
