### ISSUE TITLE
bedrock sends double arm swing packets

### ISSUE THREAD

**Issue by ViaBackwards** [GeyserMC/Geyser#3275]
### Describe the bug

bedrock sends 2 animation packets instead of 1 at the same time, can cause anti-cheat incompatibility 

### To Reproduce

attack an entity on bedrock

### Expected behaviour

only 1 arm swing packet

### Screenshots / Videos

https://streamable.com/ie9afd
java edition on the right logging packets, can see the double arm swing for main hand.

### Server Version and Plugins

This server is running Paper version git-Paper-102 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: e0486ae)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-83 (MC: 1.19.1)

### Geyser Version

2.0.7-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

Windows

**Comment by onebeastchris** [comment]
Is this still an issue with the latest version of Geyser?

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
