### ISSUE TITLE
PlayerInteractEvent for tablets are ALWAYS right_click_block

### ISSUE THREAD

**Issue by JHarris12345** [GeyserMC/Geyser#3276]
### Describe the bug

When a bedrock player on tablet / phone smacks a block, the action received for the PlayerInteractEvent is always RIGHT_CLICK_BLOCK despite it should being LEFT_CLICK_BLOCK

### To Reproduce

1. Go on your iphone or tablet
2. Have a plugin output the action for the PlayerInteractEvent OR just try to preview crates (as this uses left click block)
3. See how when you hit a block, it fires RIGHT_CLICK_BLOCK

### Expected behaviour

It should fire LEFT_CLICK_BLOCK

### Server Version and Plugins

This server is running Pufferfish version git-Pufferfish-11 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: a593bf6 on HEAD)
You are running 23 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Pufferfish-71 (MC: 1.18.2)

### Geyser Dump

https://dump.geysermc.org/ApPGtgQ3jA11ONpAEX0YZ21Rn0yNxQXm

### Geyser Version

Build #1188

### Minecraft: Bedrock Edition Device/Version

Iphone 12

**Comment by Camotoy** [comment]
I highly doubt we can do anything about this without hampering the experience for mobile. If people want to left-click on mobile then they have to hold down on the block.

**Comment by JHarris12345** [comment]
Yeah sorry I didn't realise the open was hold click. This can be closed

**Comment by Konicai** [comment]
👍

**Comment by Konicai** [comment]
Why is gitthub being weird
