### ISSUE TITLE
Recipes bug

### ISSUE THREAD

**Issue by Wojtach99** [GeyserMC/Geyser#3278]
### Describe the bug

When I try to make stairs or half blocks from polished granite, they cannot be made.

### To Reproduce

1. Open crafting table
2. Put polished granite
3. Try to make stairs or half blocks

### Expected behaviour

I would expect that they can be produced

### Screenshots / Videos

![error2](https://user-images.githubusercontent.com/113087551/189046991-66ce4389-9088-4681-9c8a-d43900c4cca9.png)
![error1](https://user-images.githubusercontent.com/113087551/189046998-9bcabec5-8b4f-4caf-b3a0-75c5ade1e340.png)
![error3](https://user-images.githubusercontent.com/113087551/189047523-ade4642e-35b3-4849-aae5-8947ac47ba62.png)

### Server Version and Plugins

Geyser: 2.0.7-SNAPSHOT(git-master-a16fc9c)
Server: git-Purpur-1774 (MC: 1.19.2)

### Geyser Version

 2.0.7-SNAPSHOT(git-master-a16fc9c)

### Minecraft: Bedrock Edition Device/Version

1.19.22 ANDROID | 1.19.22 Windows 10/11 edition

**Comment by onebeastchris** [comment]
@Wojtach99 Is this still an issue with the latest version of Geyser?

**Comment by onebeastchris** [comment]
![image](https://github.com/GeyserMC/Geyser/assets/105284508/4ac2f99d-7ebc-479e-9e05-605852d4ce76)
![image](https://github.com/GeyserMC/Geyser/assets/105284508/3b07d905-1e2d-4043-8c98-60daa5ec4f37)

seems to work just fine now - not sure when it was fixed. Closing as complete
