### ISSUE TITLE
Crazy stair collision

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Geyser#3279]
### Describe the bug

For some reason geyser decides when a player is at the back of a stair to invalidly translate their movement up a block, even when they aren't on the stair, causing anticheat incompatability as shown in this video: https://streamable.com/091a96

### To Reproduce

Walk up to the back of a stair block

### Expected behaviour

Player should behave normally, not teleport up a block

### Screenshots / Videos

https://streamable.com/091a96

### Server Version and Plugins

This server is running Paper version git-Paper-102 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: e0486ae)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-84 (MC: 1.19.1)

### Geyser Version

2.0.7

**Comment by gamer50082** [comment]
Update geyser and try again.
