### ISSUE TITLE
floodgate access for unsigned players

### ISSUE THREAD

**Issue by denisryba** [GeyserMC/Geyser#328]
Please add possibility to connect to the offline java server which uses floodgate-type geyser for bedrock players who are not signed in their xbox/microsoft accounts.

**Comment by RednedEpic** [comment]
> Please add possibility to connect to the offline java server which uses floodgate-type geyser for bedrock players who are not signed in their xbox/microsoft accounts.

This opens up the possibility for people to use cracked versions of the game which we have no intention of supporting nor endorsing. If you want to change your nickname on a server, install a plugin like Essentials that allows you to /nick.
