### ISSUE TITLE
Error while downloading packs

### ISSUE THREAD

**Issue by agoniaprivat** [GeyserMC/Geyser#3280]
### Describe the bug

Error shows up for console players when trying to download a resourcepack from the "pack" folder in Geyser.
I host Geyser through our Velocity proxy.

Worked on PC, Mobile but not on console.

Here is a video of a player trying to connect:
https://discord.com/channels/613163671870242838/613168464634576897/1017780685785800786

### To Reproduce

1. Download https://github.com/GeyserMC/GeyserOptionalPack
2. Put it in the pack folder
3. restart

### Expected behaviour

Resourcepack downloads correctly and player can join.

### Screenshots / Videos

https://discord.com/channels/613163671870242838/613168464634576897/1017780685785800786

### Geyser Dump

https://dump.geysermc.org/BZX4XASgp6hwox7hidjggDBVeBRKr934

### Geyser Version

2.0.7-SNAPSHOT (git-master-a16fc9c)

### Minecraft: Bedrock Edition Device/Version

PS4

### Additional Context

-

**Comment by Konicai** [comment]
Does this happen on other bedrock edition servers such as Bedrock Dedicated Server, Nukkit, or Cloudburst?

**Comment by Jens-Co** [comment]
Any updates on this issue?

**Comment by millson1** [comment]
I have this issue too

**Comment by DGxInfinitY** [comment]
Same Problem here!
