### ISSUE TITLE
Incorrect argument for command

### ISSUE THREAD

**Issue by Loxstazz** [GeyserMC/Geyser#3282]
### Describe the bug

Hello
When I make a command, it says: "Incorrect argument for command"
Can you help me ?
Thank you
![image](https://user-images.githubusercontent.com/96184599/189494973-43ff09fc-cfc4-4883-8a74-366edb4d0720.png)

### To Reproduce

I don't know

### Expected behaviour

/gamemode 1 .Lolo70232010

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/96184599/189495002-cbbee13f-9c73-4327-9f7f-b6f0a5a75509.png)

### Server Version and Plugins

This server is running CraftBukkit version 3580-Spigot-e53686f-5901d58 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)
This server is running Geyser version 2.0.7-SNAPSHOT (git-master-a16fc9c) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.21/1.19.22)

### Geyser Version

 2.0.7-SNAPSHOT (git-master-a16fc9c)

### Minecraft: Bedrock Edition Device/Version

Nintendo Switch / PC

**Comment by EasyClifton** [comment]
Does `/gamemode creative` work?

**Comment by Loxstazz** [comment]
Thanks you
It's works
