### ISSUE TITLE
Bedrock coordinate issue workaround

### ISSUE THREAD

**Issue by ViaBackwards** [GeyserMC/Geyser#3283]
### What feature do you want to see added?

Bedrock struggles with coordinates over 64000, and they show no plans to fix the bug, my suggestion is to segment a world into 64000x64000 segments, so for example if the player is at the coordinates 64023 100 1034, all packets sent to them have their location changed to 23 100 1034 to fix precision loss. When a player crosses the 64000 segment border the world can be reloaded to fix any weird behavior.

### Are there any alternatives?

There are no alternative for non world bordered survival servers

**Comment by Konicai** [comment]
Thank you for the suggestion, but this has already been addressed in #2518
