### ISSUE TITLE
Custom Crafting Recipes Sometimes Dissapear

### ISSUE THREAD

**Issue by RealFinePoint** [GeyserMC/Geyser#3285]
### Describe the bug

When crafting a custom recipe on Bedrock, the output sometimes (but not always) dissapears.
This cannot be replicated on Java clients.

### To Reproduce

1.) Craft a custom item. 
2.) It disappears after taking it into inventory. 
See the video. 

### Expected behaviour

The custom item correctly appears in the inventory, which usually happens.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/613168464634576897/1017916464969298011/SVID_20220905_231554_1.mp4

### Server Version and Plugins

git-Paper-135 (MC: 1.19.2)

### Geyser Dump

https://dump.geysermc.org/hGC8PdXhAlQHpmrGFQNggbaJO9X5Dddk

### Geyser Version

2.0.7-SNAPSHOT (git-master-a16fc9c)

**Comment by Konicai** [comment]
How do you add the custom recipe and can you share a custom recipe definition that experiences this?

**Comment by RealFinePoint** [comment]
> How do you add the custom recipe and can you share a custom recipe definition that experiences this?

https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-16-1-19-free.55883/
I use this plugin. I brought this issues to the devs of the plugin first, and they basically told me it's not their issue and to talk to Geyser instead. 
I would just assume that it's not compatible, but as mentioned the custom recipes _usually_ work for Bedrock players, and in this video they successfully crafted all the custom recipes leading up to this one.

Github says it doesn't support the file type of the recipe file.

**Comment by Camotoy** [comment]
Paste it in text then?

**Comment by RealFinePoint** [comment]
> Paste it in text then?

{
  "@type" : "customcrafting:crafting_shaped",
  "group" : "",
  "hidden" : false,
  "vanillaBook" : false,
  "priority" : "NORMAL",
  "checkNBT" : false,
  "conditions" : {
    "values" : [ ]
  },
  "symmetry" : {
    "horizontal" : false,
    "vertical" : true,
    "rotate" : false
  },
  "shape" : [ "ABC", "DEF", "GHI" ],
  "ingredients" : {
    "E" : {
      "items" : [ {
        "custom_amount" : 1,
        "item" : {
          "==" : "org.bukkit.inventory.ItemStack",
          "v" : 3120,
          "type" : "ELYTRA"
        }
      } ],
      "tags" : [ ],
      "replaceWithRemains" : true,
      "allowEmpty" : false
    },
    "F" : {
      "items" : [ {
        "custom_amount" : 1,
        "executableitems" : "Spartan_Bronze_Ingot"
      } ],
      "tags" : [ ],
      "replaceWithRemains" : true,
      "allowEmpty" : false
    },
    "G" : {
      "items" : [ {
        "custom_amount" : 1,
        "executableitems" : "Spartan_Bronze_Ingot"
      } ],
      "tags" : [ ],
      "replaceWithRemains" : true,
      "allowEmpty" : false
    },
    "H" : {
      "items" : [ {
        "custom_amount" : 1,
        "executableitems" : "Spartan_Bronze_Ingot"
      } ],
      "tags" : [ ],
      "replaceWithRemains" : true,
      "allowEmpty" : false
    },
    "I" : {
      "items" : [ {
        "custom_amount" : 1,
        "executableitems" : "Spartan_Bronze_Ingot"
      } ],
      "tags" : [ ],
      "replaceWithRemains" : true,
      "allowEmpty" : false
    },
    "A" : {
      "items" : [ {
        "custom_amount" : 1,
        "executableitems" : "Spartan_Bronze_Ingot"
      } ],
      "tags" : [ ],
      "replaceWithRemains" : true,
      "allowEmpty" : false
    },
    "B" : {
      "items" : [ {
        "custom_amount" : 1,
        "executableitems" : "Enchanting_Crystal"
      } ],
      "tags" : [ ],
      "replaceWithRemains" : true,
      "allowEmpty" : false
    },
    "C" : {
      "items" : [ {
        "custom_amount" : 1,
        "executableitems" : "Spartan_Bronze_Ingot"
      } ],
      "tags" : [ ],
      "replaceWithRemains" : true,
      "allowEmpty" : false
    },
    "D" : {
      "items" : [ {
        "custom_amount" : 1,
        "executableitems" : "Spartan_Bronze_Ingot"
      } ],
      "tags" : [ ],
      "replaceWithRemains" : true,
      "allowEmpty" : false
    }
  },
  "checkAllNBT" : false,
  "settings" : { },
  "result" : {
    "items" : [ {
      "custom_amount" : 1,
      "executableitems" : "Armored_Elytra"
    } ],
    "tags" : [ ],
    "extensions" : [ ]
  }
}

**Comment by onebeastchris** [comment]
Closing due to no response.
