### ISSUE TITLE
Crafting Bug - unable to equip crafted iron helmet

### ISSUE THREAD

**Issue by Uniqeues** [GeyserMC/Geyser#3288]
### Describe the bug

On mobile when i play bedrock edition the crafting works normally and when i craft for example an iron helmet and click on it, it goes to my invertory. But when i do it on java server with latest geyser on version 1.19.2 the crafting dont work. I can freely move the helmet in my invertory and i can't put it in any slot in my inventory.

### To Reproduce

Open Crafting on mobile with geyser on java server and latest paper version of 1.19.2
Get some iron ingots and craft a helmet.
Than without closing crafting menu put the helmet somewhere in the invertory.

### Expected behaviour

On mobile when i play bedrock edition the crafting works normally and when i craft for example an iron helmet and click on it, it goes to my invertory.

### Geyser Dump

https://dump.geysermc.org/1tWKvV5ZVzyWdvqnoxAP9S5aAtXby21j

### Geyser Version

2.0.7 SNAPSHOT java 1.19.1-1.19.2

### Minecraft: Bedrock Edition Device/Version

1.19.2 Latest for mobiles

**Comment by Uniqeues** [comment]
Uploading Screenrecorder-2022-09-16-21-02-33-76.mp4…

Here is a video of how buggy the crafting is.

**Comment by gamer50082** [comment]
It’s always like that since day one lol Java doesn’t like it

**Comment by gamer50082** [comment]
Cause Java doesn’t have a crafting book and it looks like a hack to Java server

**Comment by gamer50082** [comment]
Packet limit maybe

**Comment by onebeastchris** [comment]
Is this still an issue with the latest version of Geyser & Bedrock?

**Comment by onebeastchris** [comment]
Closing due to no further response. If this is still an issue, please create a new issue & provide updated replication steps. Thanks!
