### ISSUE TITLE
PacketPlayInSetCreativeSlot too large

### ISSUE THREAD

**Issue by Eisenbahn** [GeyserMC/Geyser#3289]
### Describe the bug

Got this disconection issue when using 1.16.5 (Forge Client) (Paper Server 1.12.2 with Viaversion etc)

Happens as soon as I open my inventory:

lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/27 (PacketPlayInSetCreativeSlot) was larger than I expected, found 1 bytes extra whilst reading packet 27

### To Reproduce

Forge Client 1.16.5 (havent tested outside forge, but forge 1.12.2 works fine for me)
Paper Vanilla Server
Open Survival inventory

### Expected behaviour

not applied

### Server Version and Plugins

This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Geyser Version

#1188 dev

### Minecraft: Bedrock Edition Device/Version

Java 1.16.5

**Comment by Camotoy** [comment]
I... don't think this is a Geyser issue. If it goes away when removing Geyser then let us know.

**Comment by Eisenbahn** [comment]
Switched to 1.16.5 no Forge and worked fine.. Well..
