### ISSUE TITLE
Please add no xbox authencation please 

### ISSUE THREAD

**Issue by SunshroomChan** [GeyserMC/Geyser#3291]
### What feature do you want to see added?

Ok, let's talk about this, if you making a Geyser server but it needed xbox account, why? The piracy? It wasn't auth if you buy the game or not because after you bought the game, if you don't want to login to xbox the game on Bedrock Client still playable even on Windows 10, other thing is other server software or proxy they are good to make offline mode and even on the official Bedrock or Java official software they still want non-account player can join + can change it without offline mode so please make offline mode because it is important at this time for non-Xbox player because even that Xbox account is not authorize you bought the game or not because just in-game even not login to Xbox account still can playable. And my conclusion is even piracy or not, the official Minecraft still let cracked people join it!

### Are there any alternatives?

No

**Comment by Chew** [comment]
This has been suggested before, and the general consensus is to always require xbox login. At this point every argument here has a valid counter I don't feel like debating here. We aren't asking you to go into debt here, just make an account...

**Comment by SunshroomChan** [comment]
> This has been suggested before, and the general consensus is to always require xbox login. At this point every argument here has a valid counter I don't feel like debating here. We aren't asking you to go into debt here, just make an account...

If like that, like making a 2b2t for both bedrcok and java still need auth so what another do i do ?

**Comment by Chew** [comment]
You can set the server to offline mode (which would null your need for a Java account), but you still need an Xbox account. Only difference is Java is paid and Xbox is free.

**Comment by jackson-57** [comment]
(If you want to leave your server in online mode but still allow Bedrock players without needing a Java Edition account, we recommend using Floodgate.)
