### ISSUE TITLE
Support for Bedrock-specific custom fog and camera shake

### ISSUE THREAD

**Issue by DB20-official** [GeyserMC/Geyser#3292]
### What feature do you want to see added?

Bedrock has the ability to display custom fog and enable a camera-shaking effect to the player's view via commands. However, since Java normally has no support for either of those, this severely limits what kind of immersion can be achieved on the server side. If this is possible, it would be a big change for servers that want to enhance the experience significantly for Bedrock players, while keeping in mind Java players won't see any of those effects without relying on alternatives like FOV-based shake via slowness effect and vision-altering mob effects.

### Are there any alternatives?

There wasn't any alternatives for these features that I was aware of for adding custom fog and camera shake, asides from using the methods possible on Java servers, like FOV-based shake and vision-affecting mob effects.

**Comment by DarianLStephens** [comment]
Huh, I wonder if this could be used to fake the fog normally seen in Nether biomes if you use the End dimension as a substitute to allow for a 256-tall Nether on Bedrock?
