### ISSUE TITLE
Custom Items: Eating Animations do not work.

### ISSUE THREAD

**Issue by Tydium** [GeyserMC/Geyser#3293]
### Describe the bug

When trying to apply an animation in a resource pack, it won't work in a geyser server. Any consumable items I make its just a default standing animation. (Also makes it so people can eat while walking normally sometimes.)

### To Reproduce

1. Setup Custom Mappings for Custom Items in your Geyser (I wont specifically say how to do this. Its all user specific really)
2. If your (ITEM).json inside your pack. Use the `"use_animation":"eat"` component. 
Example: 
`{
	"format_version": 1.1,
	"minecraft:item": {
		"description": {
			"identifier": "apple_pie",
			"category": "Equipment"
		},
		"components": {
			"minecraft:icon": "apple_pie",
			"minecraft:use_animation": "eat"
		}
	}
}`
3. Join your server and try to eat something.

This is obviously for more expert individuals. If you want to try this yourself just look at the Custom Items guide on the wiki, and add check out bedrock.dev. (Its how I set it up)

### Expected behaviour

Nom nom nom nom (eating animation should show)

### Screenshots / Videos

I currently don't have one but I will make one soon.

### Server Version and Plugins

Geyser Standalone: Geyser version 2.1.0-SNAPSHOT (git-master-98cfdb0)
Velocity: Velocity 3.1.2-SNAPSHOT (git-213f3f88-b183)
Purpur: Current: git-Purpur-1760 (MC: 1.19.2)*
* I AM 21 version(s) behind on purpur. There hasn't been that many changes however.

I should state I also tested this on a normal Paper server. Should have same behavior

### Geyser Dump

https://dump.geysermc.org/crRBvwY0RNHLIjfsvo0vrPWlJcloInBY

### Geyser Version

https://dump.geysermc.org/crRBvwY0RNHLIjfsvo0vrPWlJcloInBY

### Minecraft: Bedrock Edition Device/Version

Minecraft Windows 11/10 Edition, Nintendo Switch, Android, Iphone, PS4, Xbox

### Additional Context

If you would like me to provide you with an example resource pack please feel free to ask. My packs are open source.

**Comment by Kas-tle** [comment]
Apparently there is a "use_animation" item component that we could set to "eat" for food items (and "drink" for... drinks I guess), so maybe that would work.

**Comment by Kas-tle** [comment]
@ImDaBigBoss would probably know better

**Comment by Tydium** [comment]
I would hope so, I think these animations are gonna be crucial for many people that want these types of consumable items (drinking, eating, other)

**Comment by onebeastchris** [comment]
This should have been fixed by rtm recently; closing as completed - if it's otherwise, please let us know.
