### ISSUE TITLE
Chunks cease to load in some instances

### ISSUE THREAD

**Issue by SpaceCanvas** [GeyserMC/Geyser#3294]
### Describe the bug

I'd be walking around the world and i'd suddenly see a chunk that refuses to load.

### To Reproduce

there is no clear way to reproduce the bug.

step 1 : spend time in a server either flying or walking and examine chunks.

### Expected behaviour

this should happen
![IMG_2887](https://user-images.githubusercontent.com/44347834/191396677-6ece4223-92d7-4fcf-bc24-50c7a0247a42.png)
![IMG_2886](https://user-images.githubusercontent.com/44347834/191396683-7b2df501-0fc5-45f4-a324-b66e17407739.png)

### Server Version and Plugins

version git-Paper-138 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 09904fd)

Plugins (16): DiscordSRV, dynmap, Essentials, EssentialsChat, FastChunkPregenerator, floodgate, Geyser-Spigot, Graves, LuckPerms, MineableSpawners, NoEncryption, ProtocolLib, ServerListPlus*, SpigotPing, TreeFeller, Vault

### Geyser Dump

https://dump.geysermc.org/iSyPxL45RBCUlSQZHkq36AksLYcLz3Sz

### Geyser Version

Geyser-Spigot v2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

Minecraft iOS

**Comment by Chew** [comment]
Anything in the console? (your Paper is also very outdated...)

**Comment by SpaceCanvas** [comment]
no, nothing out of the ordinary, but this issue never happens on the java client it only seems to happen to geyser players.

**Comment by SpaceCanvas** [comment]
it only seems to happen to geyser players, java clients don't experience this.

**Comment by SpaceCanvas** [comment]
i'll update the paper server and see if i can get better results.

**Comment by Sirherobrine23** [comment]
I'm having the same problem with my installation on Spigot, I've already updated the server to the latest version.

Chunks do not load on any device (win10/Android/Xbox).

[My dump](https://dump.geysermc.org/8sxtN3JTPe3dviEBaY5VaZO92NqJqrkG)

**Comment by gamer50082** [comment]
I also have that issue and also can’t enter the chunk and I am using geyserconnect so I can’t say much

**Comment by Sirherobrine23** [comment]
I managed to solve my problem by removing some plugins, because my CPUs were all being used now that I removed the Plugins I can load the chunks normally.

**Comment by onebeastchris** [comment]
@SpaceCanvas is this issue still occurring for you?
@gamer50082 please provide a Geyser dump by running "geyser dump" in the server console & sending the link you get here.

**Comment by onebeastchris** [comment]
Closing due to no response.
