### ISSUE TITLE
Custom Items with damage_predicate and unbreakable: true are all messed up

### ISSUE THREAD

**Issue by YellowZaki** [GeyserMC/Geyser#3296]
### Describe the bug

I have a custom resource pack that has custom items with custom model data y damage predicate.
While items with custom model data are working, items with damage predicate and unbreakable are not (then I'll explain).
I remember using an early build (some months ago) from branch feature/extensions where everything was working fine with the same resource pack and custom_mapping.json I'm using right now.

**¿How are items with damage predicate not working?**

If you define for example: https://pastebin.com/gVqBbUvM
On custom_mappings.json. 

All the unbreakable diamond chestplates with whatever durability, it will be translated to "gmdl_162".
But if you give yourself those diamond chestplates with 526 durability and 527 WITHOUT unbreakable, you will get the correct items. **It's like "unbreakable": true is being ignored.**

### To Reproduce

1. Define some custom items with different damage predicates and unbreakable:true for one vanilla item.
2. Give yourself items with differente damages and unbreakable.
3. All the items given will be a single custom item. But if you get those items non-unbreakable, they are fine.

### Expected behaviour

Damage predicates with unbreakable:true working fine

### Geyser Version

2.1.0-SNAPSHOT (git-master-8beae31)

**Comment by Camotoy** [comment]
Can you see if the latest build fixes this issue?

**Comment by YellowZaki** [comment]
> Can you see if the latest build fixes this issue?

It fixed the damage predicates, but:

- It broke custom model data predicates. Items with custom model data are not working (it used to work).
- Items with unbreakable=true and damage, show as damaged:
![image](https://user-images.githubusercontent.com/13599841/195078429-1a2f9a98-8426-45a0-8b0c-0afe350c1fd1.png)
(it shouldn't show the damaged bar, like in Java)

**Comment by Kas-tle** [comment]
Please attach the full mappings files, Java resource pack, and bedrock resource pack for the custom model data items that do not work. As for the durability bar, we can't hide that.

**Comment by YellowZaki** [comment]
Now everything is working fine.

The behaviour between Java and Bedrock is exactly the same. The behaviour is so equal, that it causes another issue: https://github.com/GeyserMC/Geyser/issues/3346
