### ISSUE TITLE
Config setting to enable gametest framework on existing java worlds

### ISSUE THREAD

**Issue by Agaloth** [GeyserMC/Geyser#3297]
### What feature do you want to see added?

We can do pretty cool things like emoji support with this format: **:smile:**

![image](https://user-images.githubusercontent.com/33335971/191666391-a465112a-33e5-4f90-a218-667bbc090267.png)
Like this addon did here, I'm not sure if it's possible though

### Are there any alternatives?

Not really

**Comment by Camotoy** [comment]
I would assume that GameTest is processed entirely on the server, meaning if we wanted to add support we'd need to do a LOT of work. Can you send the addon you mention?

**Comment by Agaloth** [comment]
> I would assume that GameTest is processed entirely on the server, meaning if we wanted to add support we'd need to do a LOT of work. Can you send the link to the addon you mention?

https://mcpedl.com/emoji-chat-addon/

**Comment by Kas-tle** [comment]
This addon only needs the Gametest framework to replace the chat players send with the Unicode character in question... but this can already be done on the chat side by any plugin that supports text replacement. For example, see VentureChat. Beyond that, you can make such a resource pack easily with no need to depend on GameTests, use a chat plugin for the text replacement, and then you have emoji that Bedrock players can see on your Geyser server.

**Comment by Camotoy** [comment]
This sounds like something that isn't feasible on our end; therefore I'll close it. Thanks anyway!
