### ISSUE TITLE
Custom Items: Custom Bows do not work.

### ISSUE THREAD

**Issue by Agaloth** [GeyserMC/Geyser#3298]
### Describe the bug

When trying to use a custom textured bow in a resource pack, it won't work in a geyser server. However, a normal bow will work.

### To Reproduce

Convert java resource pack into bedrock resource pack

### Expected behaviour

The bow would have an animation and would shoot arrows.

### Screenshots / Videos

https://streamable.com/5tevhr

### Server Version and Plugins

git-PufferfishPlus-12 (MC: 1.19.2)*

Plugins (106): AdvancedEnchantments, AdvancedVanish, ajStartCommands*, AutoBroadcast, BattlePass, BedrockPlayerManager, BlockLocker, BookNews, Brewery, BuycraftX, ChatComplete, ChatItem, ChatSentry, Chunky, ChunkyBorder, Citizens, ColoredAnvils, CommandPanels, CommandRegions*, CommunityChest, CoreProtect, CustomCrafting, CyberWorldReset, DailyRewards, DeathLocation, DecentHolograms, DeluxeCombat, DeluxeMenus, DeluxeTags, Essentials, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), floodgate, FloodgateCP, Geyser-Spigot, GSit, HeadDatabase, HeadDecapitator, HintJoin, ImageOnMap, Insights, InteractiveBooks, InventoryRollbackPlus, ItemsAdder, JakesRTP, JetsAntiAFKPro, JoinCommands, KauriVPN, KeepInventory, KixsChatGames, LavaSponge, Lib1711, LibsDisguises, LiteBans, LoneLibs, LuckPerms, MapTowny, mcMMO, MessageSounds, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, NightVision, OpenInv, PacketListenerApi, PlaceholderAPI, Plan, PlayerAuctions, PlayerKits, PlayerPoints, PlayerVaults, PlayerWarps, ProCosmetics, ProtocolLib, QuickShop, RandomEvents, RankupMenu, RoseStacker, RotationalWrench, SafariNet, ServerlistMOTD*, ServerUtils, ShopGUIPlus, spark, SpecializedCrates, StoreGoal, SuperbVote, SurvivalInvisiframes, TAB, Towny, TownyFlight, UltimateAutoRestart, Vault, Vehicles, VentureChat, ViaBackwards, ViaVersion, VillagerOverhaul, VoteParty, Votifier, Vulcan, WolfyUtilities, WorldGuard, WorldGuardExtraFlags, XLTournaments, XPBoost

### Geyser Dump

https://dump.geysermc.org/oXxvskGUDiLjBriUJ4MAhjRECGS7rDTP

### Geyser Version

Geyser-Spigot version 2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.30 Windows 10 Edition

**Comment by YellowZaki** [comment]
I can confirm

**Comment by Redned235** [comment]
Resolved in https://github.com/GeyserMC/Geyser/commit/178fb2136f46e1ad25d37067c35ceca39c211850 to the extent the client allows. Unfortunately there are a handful of limitations on the client side, but behavior should be far smoother on our end for this.
