### ISSUE TITLE
Custom Items: Elytras doesn't work

### ISSUE THREAD

**Issue by Agaloth** [GeyserMC/Geyser#3299]
### Describe the bug

When trying to a custom textured elytra in a resource pack, it won't work in a geyser server. However, normal elytra will work. On java edition, both will work.

### To Reproduce

Convert java resource pack into bedrock resource pack

### Expected behaviour

The elytra would work as intended.

### Screenshots / Videos

https://streamable.com/qrfv1e

### Server Version and Plugins

git-PufferfishPlus-12 (MC: 1.19.2)*

Plugins (106): AdvancedEnchantments, AdvancedVanish, ajStartCommands*, AutoBroadcast, BattlePass, BedrockPlayerManager, BlockLocker, BookNews, Brewery, BuycraftX, ChatComplete, ChatItem, ChatSentry, Chunky, ChunkyBorder, Citizens, ColoredAnvils, CommandPanels, CommandRegions*, CommunityChest, CoreProtect, CustomCrafting, CyberWorldReset, DailyRewards, DeathLocation, DecentHolograms, DeluxeCombat, DeluxeMenus, DeluxeTags, Essentials, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), floodgate, FloodgateCP, Geyser-Spigot, GSit, HeadDatabase, HeadDecapitator, HintJoin, ImageOnMap, Insights, InteractiveBooks, InventoryRollbackPlus, ItemsAdder, JakesRTP, JetsAntiAFKPro, JoinCommands, KauriVPN, KeepInventory, KixsChatGames, LavaSponge, Lib1711, LibsDisguises, LiteBans, LoneLibs, LuckPerms, MapTowny, mcMMO, MessageSounds, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, NightVision, OpenInv, PacketListenerApi, PlaceholderAPI, Plan, PlayerAuctions, PlayerKits, PlayerPoints, PlayerVaults, PlayerWarps, ProCosmetics, ProtocolLib, QuickShop, RandomEvents, RankupMenu, RoseStacker, RotationalWrench, SafariNet, ServerlistMOTD*, ServerUtils, ShopGUIPlus, spark, SpecializedCrates, StoreGoal, SuperbVote, SurvivalInvisiframes, TAB, Towny, TownyFlight, UltimateAutoRestart, Vault, Vehicles, VentureChat, ViaBackwards, ViaVersion, VillagerOverhaul, VoteParty, Votifier, Vulcan, WolfyUtilities, WorldGuard, WorldGuardExtraFlags, XLTournaments, XPBoost

### Geyser Dump

https://dump.geysermc.org/rcMig0cyPsP7sCcNeKDKOIaywGF2sE7Y

### Geyser Version

Geyser-Spigot version 2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.30 Windows 10 Edition

**Comment by Agaloth** [comment]
This is still not fixed

**Comment by Kas-tle** [comment]
This will likely never be fixed as it's a client limitation.

**Comment by onebeastchris** [comment]
Closing this issue in favor of it being documented on our current limitations page: https://wiki.geysermc.org/geyser/current-limitations/
