### ISSUE TITLE
Custom Items: Items shows differently in hand

### ISSUE THREAD

**Issue by Agaloth** [GeyserMC/Geyser#3300]
### Describe the bug

When trying to use a custom textured item in a resource pack, it won't show it as a non-textured item in a geyser server.

### To Reproduce

Convert java resource pack into bedrock resource pack

### Expected behaviour

Items should look like the non-textured ones.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/33335971/191790757-306b4bc7-1d6c-44ed-b3ef-b6c8e77da606.png)
![image](https://user-images.githubusercontent.com/33335971/191790781-1d94b008-a886-4559-8742-43cd4e7be259.png)

### Server Version and Plugins

git-PufferfishPlus-12 (MC: 1.19.2)*

Plugins (106): AdvancedEnchantments, AdvancedVanish, ajStartCommands*, AutoBroadcast, BattlePass, BedrockPlayerManager, BlockLocker, BookNews, Brewery, BuycraftX, ChatComplete, ChatItem, ChatSentry, Chunky, ChunkyBorder, Citizens, ColoredAnvils, CommandPanels, CommandRegions*, CommunityChest, CoreProtect, CustomCrafting, CyberWorldReset, DailyRewards, DeathLocation, DecentHolograms, DeluxeCombat, DeluxeMenus, DeluxeTags, Essentials, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), floodgate, FloodgateCP, Geyser-Spigot, GSit, HeadDatabase, HeadDecapitator, HintJoin, ImageOnMap, Insights, InteractiveBooks, InventoryRollbackPlus, ItemsAdder, JakesRTP, JetsAntiAFKPro, JoinCommands, KauriVPN, KeepInventory, KixsChatGames, LavaSponge, Lib1711, LibsDisguises, LiteBans, LoneLibs, LuckPerms, MapTowny, mcMMO, MessageSounds, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, NightVision, OpenInv, PacketListenerApi, PlaceholderAPI, Plan, PlayerAuctions, PlayerKits, PlayerPoints, PlayerVaults, PlayerWarps, ProCosmetics, ProtocolLib, QuickShop, RandomEvents, RankupMenu, RoseStacker, RotationalWrench, SafariNet, ServerlistMOTD*, ServerUtils, ShopGUIPlus, spark, SpecializedCrates, StoreGoal, SuperbVote, SurvivalInvisiframes, TAB, Towny, TownyFlight, UltimateAutoRestart, Vault, Vehicles, VentureChat, ViaBackwards, ViaVersion, VillagerOverhaul, VoteParty, Votifier, Vulcan, WolfyUtilities, WorldGuard, WorldGuardExtraFlags, XLTournaments, XPBoost

### Geyser Dump

https://dump.geysermc.org/oXxvskGUDiLjBriUJ4MAhjRECGS7rDTP

### Geyser Version

Geyser-Spigot version 2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.30 Windows 10 Edition

**Comment by Camotoy** [comment]
Can you send your Java pack, Bedrock pack, and mappings?

**Comment by Agaloth** [comment]
> Can you send your Java pack, Bedrock pack, and mappings?

This should have everything
[java pack.zip](https://github.com/GeyserMC/Geyser/files/9629491/java.pack.zip)


[bedrock pack.zip](https://github.com/GeyserMC/Geyser/files/9629490/bedrock.pack.zip)

**Comment by Kas-tle** [comment]
Hi, these values are set by the resource pack you have attached. As a result, this is not a geyser issue. If you wish to reposition the first person view of the items, please do so via the resource pack.

**Comment by Jens-Co** [comment]
> Hi, these values are set by the resource pack you have attached. As a result, this is not a geyser issue. If you wish to reposition the first person view of the items, please do so via the resource pack.

On that i will close this issue.
