### ISSUE TITLE
Can't enable GeyserMC on 1.12.2-Spigot server

### ISSUE THREAD

**Issue by tonton223** [GeyserMC/Geyser#3308]
### Describe the bug

GeyserMC does not start normally when starting the server and the following error is displayed.

"Plugin Geyser-Spigot v2.1.0-SNAPSHOT has failed to register events for class org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin$1 because org/bukkit/event/server/ServerLoadEvent does not exist."

all logs: https://mclo.gs/nnjz1E7

### To Reproduce

1. build 1.12.2 spigot server
2. add GeyserMC and Floodgate Plugin to server's plugin folder
3. start server 

### Expected behaviour

player should be able to connect successfully

### Server Version and Plugins

Server:
CraftBukkit version git-Spigot-79a30d7-f4830a1 (MC: 1.12.2)

Plugins:
ViaVersion-4.4.2
ViaRewind-2.0.2
ViaBackwards-4.4.2
floodgate-spigot  (2.2.0-SNAPSHOT (b73-4f36112))

### Geyser Version

Geyser-Spigot v2.1.0-SNAPSHOT

### Additional Context

Putting only GeyserMC and Floodgate in the plugins folder also gives the same error.

It is possible to connect to 1.12 with other versions becouse viaversion is introducing. However, I would like to avoid it if possible because plugins I have been using will not work.

Also, this problem started a few days ago.
(I have written some parts using translation software. Therefore, there may be errors in the text.)

**Comment by Camotoy** [comment]
Yes, this is a new error. While it's probably possible to work around this, we probably will just end up dropping 1.12 support on Spigot as we already have some workarounds exclusively for 1.12.

**Comment by onebeastchris** [comment]
assuming it would be dropped, what would be the oldest supported version then?

**Comment by Camotoy** [comment]
I would imagine we would still "support" 1.12 in other contexts but 1.13 would probably be the lowest.

**Comment by tonton223** [comment]
I will update the version for the future. Thank you for answering :D

**Comment by dadodasyra** [comment]
Damn pls not, 1.12.2 is the last world format which is pretty the same between Bedrock and Java and it makes sense to keep it alive

**Comment by onebeastchris** [comment]
1.12.2 is ancient, and lacks many modern features..
if you just want to convert worlds easier, use the official Minecraft world converter
https://chunker.app/
Atleast if I'm understanding your argument correctly that is.

**Comment by RednedEpic** [comment]
> Damn pls not, 1.12.2 is the last world format which is pretty the same between Bedrock and Java and it makes sense to keep it alive

The world formats in Java and Bedrock have never been close - Bedrock has always utilized LevelDB whereas Java uses Anvil, and the way in which blocks are stored differ significantly from both versions. Regardless, world format is not a concern for Geyser since we never touch this, and in actuality, converting the modern network format (which is relevant to us) of world data is actually easier on later versions of the game.
