### ISSUE TITLE
getDeviceOs() Windows return

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#3310]
### What feature do you want to see added?

For a Windows player, getDeviceOs() returns "Windows 10", even if the player is actually using Windows 11.
My suggestion is to change this to "Windows 10/11" or just "Windows".

### Are there any alternatives?

The alternative would be to have the plugin developer using this method to replace " 10" with " 10/11" or just remove " 10" on their own.

**Comment by jackson-57** [comment]
There's [technically a win32 version](https://github.com/GeyserMC/Geyser/blob/master/common/src/main/java/org/geysermc/floodgate/util/DeviceOs.java) of Minecraft Bedrock, so the name Windows 10 is used to signify that it's the UWP version instead. The proper term for the UWP version of the game seems to be 'Minecraft for Windows'.

**Comment by Chew** [comment]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/8278263/192354946-de56b375-e04d-420d-be3f-8c580428eaef.png">
Microsoft for Windows seems to be the best here, like jackson said.

**Comment by jackson-57** [comment]
I agree, in that case.
