### ISSUE TITLE
Geyser Fabric Crashing

### ISSUE THREAD

**Issue by mangosurvival** [GeyserMC/Geyser#3313]
### Describe the bug

Hello, I am using the latest build at the moment, and the server just doesn't work.

Here is my log.

https://mclo.gs/SRNndwK

I am only using fabric api, minimotd and geyser fabric.

fabric loader 0.14.9, latest fabric api, fabric 1.19.2.

it also says something about datapacks, i don't have any datapacks at the moment.

### To Reproduce

Just start the server

### Expected behaviour

The server to start without errors.

### Server Version and Plugins

1.19.2 Fabric, no plugins, no datapacks.

### Geyser Version

Build #55 (Sep 26, 2022, 4:58:50 PM) Geyser Fabric

**Comment by Mouy07** [comment]
I am also encountering this issue. The error message is "Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode" followed by a bunch of spam. It doesn't happen if floodgate is installed.

**Comment by Camotoy** [comment]
Seeing as this is currently a Geyser-Fabric issue, I'll close this in favor of https://github.com/GeyserMC/Geyser-Fabric/issues/69. Thanks.
