### ISSUE TITLE
Player model appears invisible randomly

### ISSUE THREAD

**Issue by ViaBackwards** [GeyserMC/Geyser#3315]
### Describe the bug

Sometimes bedrock player's playermodel disappears without reason, see video: https://streamable.com/r4gxs6

### To Reproduce

Not sure yet, has happened with multiple players though.

### Expected behaviour

Player model should not be invisible.

### Screenshots / Videos

https://streamable.com/r4gxs6

### Server Version and Plugins

Paper version is 1.19.2 #177 (latest as of writing)

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-d2b7b8c) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.30)

### Minecraft: Bedrock Edition Device/Version

v1.19.30

**Comment by Kas-tle** [comment]
@ViaBackwards could you please provide a Geyser dump and list of plugins on the affected server(s)? Simply run `geyser dump` in game or in console and provide the link it returns.

**Comment by HippieBeak** [comment]
Perhaps this has something to do with https://github.com/ViaVersion/ViaVersion/issues/3142 ?

**Comment by HippieBeak** [comment]
Here's a geyser dump: https://dump.geysermc.org/BXpoQMK2jkh4NMJqTfMJ1SWuVOlZhmvs
As well as plugins on a server that has been affected: https://pastebin.com/Lw35XBWE

**Comment by onebeastchris** [comment]
If this is still an issue; could you send a new dump & video?

**Comment by onebeastchris** [comment]
Closing due to no response. If this issue is still present, please open another issue with up to date reproduction steps
