### ISSUE TITLE
Bedrock players cannot use the § symbol

### ISSUE THREAD

**Issue by GameParrot** [GeyserMC/Geyser#3316]
### Describe the bug

When typing in chat or renaming items, the § symbol (the color code symbol) gets removed. It shows upon the bedrock client and then disappears when they send the message or rename an item.

### To Reproduce

1. Login from Bedrock
2. Send §bHi in chat
3. Notice how the § symbol was deleted and the text was not formatted

### Expected behaviour

The text should be formatted according to what is after the § symbol

### Server Version and Plugins

Version: 1.19.2
Plugins: Lithium, Geyser, Floodgate, Fabric API, NoChatReports, Starlight
Server: Fabric

### Geyser Version

2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.30, iPhone

**Comment by Camotoy** [comment]
This is intentional behavior as Java will not let you type the `§` symbol at all (and in some cases you will be kicked from the server for doing so). Thank you for reporting anyway!

**Comment by GameParrot** [comment]
> This is intentional behavior as Java will not let you type the `§` symbol at all (and in some cases you will be kicked from the server if you succeed). Thank you for reporting anyway!

Could a new option be added to the Geyser conf to allow Bedrock players to type this symbol if possible?

**Comment by Camotoy** [comment]
...Maybe. Feel free to open a new issue under the Feature Request category and we'll consider it.

**Comment by gamer50082** [comment]
U could add a chat plugin and use ‘&’ instead
