### ISSUE TITLE
The sun, moon and stars do not load / appear on geyser

### ISSUE THREAD

**Issue by Yomamaeatstoes** [GeyserMC/Geyser#3317]
### Describe the bug

As the title says there is no sun, moon or stars. Like literally, there are no stars, moon or sun when you look up in the sky. I have joined many geyser servers and this is an issue, please fix this! I love seeing the sun, moon and stars.

### To Reproduce

Look up in the sky at where the sun, moon or stars should be

### Expected behaviour

You should be able to see the sun, moon and stars. 

### Screenshots / Videos

These images are on geyser newest version

![2C856BBF-5131-4332-996A-E2DC0239FB1B](https://user-images.githubusercontent.com/114538961/192655855-5ff8f4aa-d25a-4c6f-9750-05d38d649365.jpeg)

![6FF923C6-CD74-4D8C-A4C0-D044132E9592](https://user-images.githubusercontent.com/114538961/192655862-234ac415-38b1-4fa8-b3aa-80385114d348.jpeg)

I was asked by Camotoy#5533 if I could see the sun, moon and stars in single player and I can. 

These second set of images are of the moon, stars and sun in my single player player world 

![C36009F3-8345-454C-B9CA-60AC57E7613E](https://user-images.githubusercontent.com/114538961/192656118-a00d51ed-7efe-41c3-a78f-f31887cc5105.png)
![412FF890-ABAF-4A60-8634-E8D7DAD38D8B](https://user-images.githubusercontent.com/114538961/192656121-6cdec274-feee-44d4-83ef-d8eeb29e7c26.png)
![4C68AA30-5799-4330-BA6D-754DCCC024DF](https://user-images.githubusercontent.com/114538961/192656123-26a707ec-aab9-4c08-b66a-2e85d53750b3.png)
![CD702196-71EF-4C64-8ED2-D59DFF8ED6ED](https://user-images.githubusercontent.com/114538961/192656125-be4f514d-f41f-421e-bf6e-770ac36e3a4a.png)

### Server Version and Plugins

“This server is running geyser version 2.1.0 snapshot (git-master- a84362a) 

running paper git-paper-173 (mc 1.19.2) 

plug-ins seem irrelevant for this happens on every geyser server I join but, BanItem*, BetterEconomy, ChatFilter, Chunky, ClansLite, CommandBlockAsPlayer, floodgate, Geyser-Spigot, HarmonyScoreboard, HolographicDisplays, LuckPerms, NoCheatPlus, Orebfuscator, PL-Hide, PlaceholderAPI, PlayerKits, PlugManX (PlugMan), ProtocolLib, ScoreboardChatShop, SecondThreadAPI*, SilkySpawnersLITE, Skywars, spark, Spleef*, StormerAntiNetherRoof, StormerAntiSpam, StormerHomes, StormerTPA, StormerWarps, Themis, TNTRun_reloaded, Vault, VaultToVanilla, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/ZSlN7EZScD0RXJ5WlJ0pid5Yvxvb0sTZ

### Geyser Version

This server is running geyser version 2.1.0 snapshot (git-master- a84362a)

### Minecraft: Bedrock Edition Device/Version

iOS, PC, and it probably affects every device. 

### Additional Context

I want to be able to see the sun, moon and stars

**Comment by onebeastchris** [comment]
Tested on an Android device with latest Geyser version on Velocity + 1.19.51 client; I'm able to see the skylights just fine. Does the issue still occur with the latest version of Geyser for you?

**Comment by Yomamaeatstoes** [comment]
nope this is fixed now ( :

**Comment by Camotoy** [comment]
Wonderful.
