### ISSUE TITLE
geyser reload have bug and not login

### ISSUE THREAD

**Issue by candy999** [GeyserMC/Geyser#3319]
### Describe the bug

geyser reload have bug and not login

### To Reproduce

geyser reload

### Expected behaviour

can login and can use geyser reload

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/2743971/192675115-62b8583c-3f45-4f0f-ac1b-434fb8138175.png)

### Server Version and Plugins

https://api.purpurmc.org/v2/purpur/1.19.2/1796/download

[10:40:25 INFO]: Checking version, please wait...
[10:40:25 INFO]: Current: git-Purpur-1796 (MC: 1.19.2)*
Previous: git-Purpur-1670 (MC: 1.19)
* You are running the latest version

### Geyser Version

#11992022年9月28日 上午12:25

**Comment by gamer50082** [comment]
Number 1 reload is never recommended 
Number 2 restarting a server is always the best option to test a fresh new edit
