### ISSUE TITLE
Everything is red!!! Nether fog everywhere and you can only see up a few blocks away

### ISSUE THREAD

**Issue by Yomamaeatstoes** [GeyserMC/Geyser#3320]
### Describe the bug

Everything is red!! Red fog everywhere, can't see beyond a few block away! When this happened to me, I reset the world from a backup of the day before when I did not have core protect.

After I did a reset from a backup from before this happened everything was fixed

For the potential fix please read the additional context

### To Reproduce

download core protect - no need to configure it or anything

This will happen at random. You might receive some errors and then bam everything for bedrock players is all red!

### Expected behaviour

The world looks normal and nothing is red

### Screenshots / Videos

![IMG_E2662](https://user-images.githubusercontent.com/114538961/192676738-0bf80193-75b8-47a4-9adc-6d1e5708dbbe.JPG)

![IMG_E2663](https://user-images.githubusercontent.com/114538961/192676745-0e6638af-e327-473d-88a9-a8f213d7bbbe.JPG)

### Server Version and Plugins

Using paper 1.19.2, of version sept 13

my plugins : BanItem*, BetterEconomy, ChatFilter, Chunky, ClansLite, CommandBlockAsPlayer, floodgate, Geyser-Spigot, HarmonyScoreboard, HolographicDisplays, LuckPerms, NoCheatPlus, Orebfuscator, PL-Hide, PlaceholderAPI, PlayerKits, PlugManX (PlugMan), ProtocolLib, ScoreboardChatShop, SecondThreadAPI*, SilkySpawnersLITE, Skywars, spark, Spleef*, StormerAntiNetherRoof, StormerAntiSpam, StormerHomes, StormerTPA, StormerWarps, Themis, TNTRun_reloaded, Vault, VaultToVanilla, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldGuard, Coreprotect

### Geyser Dump

geyser dump of when that happned - https://dump.geysermc.org/vWnK3mFoM6HwPAI9itMxk8TWVS6YK0sS

### Geyser Version

Was on version of sept 13, 2022

### Minecraft: Bedrock Edition Device/Version

IOS, PC and probably other devices

### Additional Context

It looks like this bug is from core protect, I say this because this guy ( https://github.com/GeyserMC/Geyser/issues/3005 ) had the same issue and plugin. During this event I also noticed this error from core protect. Here is the log of that day

[logs_latest__Radacted-Ips_.txt](https://github.com/GeyserMC/Geyser/files/9661191/logs_latest__Radacted-Ips_.txt)

-  There seems to be a potential solution, when I was talking to the mods at core protect about this error in the log. The discord mod Intelli#0001 said 

" [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
Try deleting the database.db file "

This could be a potential fix for someone who encounters this issue with the red fog

**Comment by Camotoy** [comment]
Thank you for posting, but if an issue is already up there's no need to create a new one. Thanks.

**Comment by Yomamaeatstoes** [comment]
Ok
