### ISSUE TITLE
Skin error in console

### ISSUE THREAD

**Issue by ViaBackwards** [GeyserMC/Geyser#3321]
### Describe the bug

 Got a message from skin uploader: received a skin with invalid geometry: the image width and height doesn't match the geometry data width and height

### To Reproduce

Paper 1.19.2, latest geyser, this happens.

### Expected behaviour

No error

### Server Version and Plugins

Paper version is 1.19.2 https://github.com/GeyserMC/Geyser/issues/177 (latest as of writing)

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-d2b7b8c) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.30)

### Minecraft: Bedrock Edition Device/Version

v1.19.30

**Comment by Camotoy** [comment]
Is this issue resolved?

**Comment by Jens-Co** [comment]
Closed due to inactivity. Feel free to bump this issue if it still occurs.
