### ISSUE TITLE
Geyser showing 2 name tags

### ISSUE THREAD

**Issue by SamGamerYT** [GeyserMC/Geyser#3323]
### Describe the bug

The TAB plugin on Bedrock with geysermc support shows the username double but the double name bug only happens to a few people not everyone.

### To Reproduce

Steps to reproduce
Get on Java and make the server supported
Get a bedrock alt account and view the Java Account or fellow bedrock account
You will see double usernames being merged into each other

### Expected behaviour

The player shouldn't see 2 Name tags being merged into each other and unreadable

### Server Version and Plugins

Purpur 1.19.2

TAB version v3.1.5

### Geyser Version

Build #1199

**Comment by SamGamerYT** [comment]
Still broken on latest

**Comment by onebeastchris** [comment]
please attach a screenshot of the "merged" nametag - also, what do the affected players have in common? All bedrock? If yes, all devices?

**Comment by SamGamerYT** [comment]
> please attach a screenshot of the "merged" nametag - also, what do the affected players have in common? All bedrock? If yes, all devices?

All devices.

**Comment by SamGamerYT** [comment]
https://gyazo.com/ffdb66b77fefe63ed71551f13c912a8d

**Comment by bubbakadriu** [comment]
![4DDB31ED-59DB-4413-8862-F3A5EE91466F](https://user-images.githubusercontent.com/38432044/209451493-271e15a6-c506-44b0-b256-8907104bd1d8.jpeg)

**Comment by bubbakadriu** [comment]
Sometimes the name doesnt work at all and puts literally just the players name in white text, tried both TAB and NameTagEdit and none of these seem to work on bedrock

**Comment by gululiJP** [comment]
Indicate that you are a GENERAL in Discord.
You can reproduce it here. : https://mclo.gs/LTbjYhL

**Comment by Camotoy** [comment]
Can you see if upcoming build #1289 fixes this?

**Comment by gululiJP** [comment]
> Can you see if upcoming build #1289 fixes this?

I checked with the latest build and it has disappeared properly. Thank you for your response.
