### ISSUE TITLE
BattlePass rewards - pages not turning 

### ISSUE THREAD

**Issue by roggy666** [GeyserMC/Geyser#3327]
### Describe the bug

When a player enters the tab with rewards and tries to turn the page or get a reward, the item is phantomly simply taken into inventory, and in the console bungee error -
[19:44:44 WARN] [Geyser-BungeeCord]: Could not translate packet ClientboundContainerSetSlotPacket
java.lang.NullPointerException: null

### To Reproduce

Idk, but this was not before I updated to 1.19.30

### Expected behaviour

For rewards to function properly

### Server Version and Plugins

Floodgate, BattlePass, ProtocolLib, ViaVersion, ViaBackwards, GeyserMC 

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-c31bd45)

### Minecraft: Bedrock Edition Device/Version

1.19.30, Android

**Comment by roggy666** [comment]
I found what the problem is when I changed minecarts with stoves and chests to regular chests, everything started working, it's the icons, but I don't understand why

**Comment by onebeastchris** [comment]
If this is still an issue, send a geyser dump logs
run "geyser dump" in the console, and share the link it gives you here. Additionally, share a log that includes the error by uploading the contents of your full latest.log file to mclo.gs , and send the link to that here
Currently, there isn't a lot of info to go on

**Comment by onebeastchris** [comment]
Closing due to no response & apparent fix.
