### ISSUE TITLE
Pistons disappear from inventory when getting them from creative tab

### ISSUE THREAD

**Issue by denisryba** [GeyserMC/Geyser#333]
**Description**
Piston items dissapear from inventory after obtaining them via creative tab.
(getting them from the ground works well both on creative and survival)

**To Reproduce**
1. Make sure your gamemode is creative
2. Find piston or sticky piston in your creative tab
3. Try to put it to your inventory

**Expected behavior**
Pistons shouldn't disappear from your inventory.

**Server Version**
Paper 1.15.2 git-183

**Geyser Version**
inventory #14

**Minecraft: Bedrock Edition Version**
1.14.30

**Comment by Loganh4005** [comment]
Same thing for Disspencers and Droppers...

**Comment by DoctorMacc** [comment]
Fixed with #347.
