### ISSUE TITLE
Actionbar send by plugin overlaping with item name and armor bar

### ISSUE THREAD

**Issue by cupangafk** [GeyserMC/Geyser#3333]
### Describe the bug

continuing #2843

the plugin send data to ```hud_tip_text``` rather than ```hud_actionbar_text``` from resource pack perspective

in return, the text appear to be overlapping the item name

### To Reproduce

1. use this plugin [ActionAnnoucer](https://www.spigotmc.org/resources/actionannouncer.1320/)
2. set ```announce_interval``` to somewhat sort like 5 in the plugin's ```config.yml```
3. login to the server using bedrock and set gamemode to survival
4. try pick some item or equip armor

### Expected behaviour

the plugin will use ```hud_actionbar_text``` and displayed text correctly

### Screenshots / Videos

![](https://cdn.discordapp.com/attachments/594353332508819457/1026513524509397002/unknown.png)

### Server Version and Plugins

Paper version git-Paper-191 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 928bcc8)

Plugins
-  [ActionAnnoucer](https://www.spigotmc.org/resources/actionannouncer.1320/)
- Geyser-Spigot

### Geyser Dump

https://dump.geysermc.org/dFi6ENS1PXCqpLkhO8c0IaFK1E2yf8IT

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-fc25592) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.30)

### Minecraft: Bedrock Edition Device/Version

1.19.30

### Additional Context

it happen on survival mode UI. ```hud_tip_text``` wont get pushed up like item name and ```hud_actionbar_text``` to give health bar, hunger bar, and armor bar some free space

i also tested another plugin [Action Bar Health](https://www.spigotmc.org/resources/action-bar-health.2661/)
but no change in result

 command ```/title actionbar``` actualy send the data to ```hud_actionbar_text```
 because of that, it will overlapped by ```hud_tip_text``` which is shouldn't happen in java *(java will briefly change the actionbar text before plugin change it back)*

my temporary fix is 
1. use official template [resource pack](https://feedback.minecraft.net/hc/en-us/articles/4414295731725-Bedrock-Add-On-Templates)
2. extract the zip to a folder
3. open ```ui/hud_screen.json```
4. change ```hud_tip_text``` offset from ```"offset": [ 0, -42 ]``` to ```"offset": [ 0, -60 ]```
5. zip the resource pack and rename to ```resource_pack.mcpack```
6. import ```resource_pack.mcpack``` to minecraft and apply 

or you can use this pre-made [.mcpack](https://cdn.discordapp.com/attachments/594353332508819457/1026500266268295198/actionbar_fix_geyser_spigot.mcpack) to test *(min game version 1.19.2)*

the .mcpack only contain ```ui/hud_screen.json```
```
{
  "namespace": "hud",
  "hud_tip_text": {
    "offset": [ 0, -60 ] //this will be equal with hud_actionbar_text... -42 default
  }
}
```
![preview](https://cdn.discordapp.com/attachments/594353332508819457/1026515331637841950/unknown.png)
but that also show a problem to enchanted item like this
![enchanted item problem](https://media.discordapp.net/attachments/594353332508819457/1026502039783608340/unknown.png)
it could be fixed by removing the enchanted property name like Unbreaking, Knockback, etc in the resource pack so it only show item name just like java

**Comment by cupang-afk** [comment]
i added this to compare ```/title``` command on both bedrock and java *(looks like i forgot to include this)*

on bedrock
I changed both ```hud_tip_text``` and ```hud_actionbar_text``` offset in ```ui/hud_screen.json``` to avoid overlapping
```
{
  "namespace": "hud",
  "hud_tip_text": {
    "offset": [ 0, -60 ] //this will be equal with hud_actionbar_text... -42 default
  },
  "hud_actionbar_text": {
    "offset": [ 0, "50%-78px" ] //default "50%-68px"
  }
}

```

![](https://cdn.discordapp.com/attachments/594353332508819457/1026661695332040734/unknown.png)

on java

https://user-images.githubusercontent.com/66926348/193714135-88963d61-5f1d-4fe2-b106-298c6716176f.mp4
