### ISSUE TITLE
Not joining on server ( auth-type: offline )

### ISSUE THREAD

**Issue by daniil12344official** [GeyserMC/Geyser#3343]
### Describe the bug

Every time I put in auth-type: offline
I can't get in. Just search for the server and that's it.

### To Reproduce

?

### Expected behaviour

Every time I put in auth-type: offline
I can't get in. Just search for the server and that's it.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1000394932852375572/1028983706746105936/Screenshot_2022-10-10-17-52-38-874_com.mojang.minecraftpe.jpg https://cdn.discordapp.com/attachments/1000394932852375572/1028983729588285460/Screenshot_2022-10-10-17-52-45-826_com.mojang.minecraftpe.jpg
![Screenshot_2022-10-10-17-52-45-826_com mojang minecraftpe](https://user-images.githubusercontent.com/115466475/194850639-b0be6f37-5eac-4f67-97c3-3c0fde90fa43.jpg)
![Screenshot_2022-10-10-17-52-38-874_com mojang minecraftpe](https://user-images.githubusercontent.com/115466475/194850644-e8e446da-cc0c-408f-abd1-95ab1ec7de86.jpg)

### Server Version and Plugins

1.19.1

### Geyser Version

2.1.0-SNAPSHOT (git-master-f4b8105) Standalone

### Minecraft: Bedrock Edition Device/Version

1.19.21, Poco x3 pro 8/256GB

### Additional Context

[11:47:21 WARN] Downstream packet error! Packet "ClientboundSetCarriedItemPacket" not fully read.
[11:47:21 WARN] Downstream packet error! Packet "ClientboundSetScorePacket" not fully read.

**Comment by Konicai** [comment]
1. Does this occur with `auth-type: online` ? Issues that are limited to offline mode are generally low priority because offline mode is not supported.
2. Do you have a valid xbox live account that owns Bedrock Edition? Geyser requires this.
2. Please run `/geyser dump` and share the link here. If you are using Geyser Standalone in GUI mode, follow this: 
https://media.discordapp.net/attachments/774372288061243482/776957132465373184/97361099-751ce400-1875-11eb-84b5-2945d840dfff.png

3. Share your geyser logs using https://mclo.gs and share the link here.

**Comment by daniil12344official** [comment]
> 1. Does this occur with `auth-type: online` ? Issues that are limited to offline mode are generally low priority because offline mode is not supported. No, on server " auth-type: offline "
> 2. Do you have a valid xbox live account that owns Bedrock Edition? Geyser requires this. Yes
> 3. Please run `/geyser dump` and share the link here. If you are using Geyser Standalone in GUI mode, follow this:
>    https://media.discordapp.net/attachments/774372288061243482/776957132465373184/97361099-751ce400-1875-11eb-84b5-2945d840dfff.png {
    "versionInfo": {
        "name": "Geyser",
        "version": "2.1.0-SNAPSHOT (git-master-f4b8105)",
        "javaName": "OpenJDK 64-Bit Server VM",
        "javaVendor": "Oracle Corporation",
        "javaVersion": "17.0.2+8-86",
        "architecture": "amd64",
        "operatingSystem": "Linux",
        "operatingSystemVersion": "4.19.0-16-amd64",
        "network": {
            "dockerCheck": true,
            "internalIP": "***"
        },
        "mcInfo": {
            "bedrockVersions": [
                "1.19.0/1.19.2",
                "1.19.10/1.19.11",
                "1.19.20",
                "1.19.21/1.19.22",
                "1.19.30"
            ],
            "bedrockProtocols": [
                527,
                534,
                544,
                545,
                554
            ],
            "defaultBedrockProtocol": 554,
            "javaVersions": [
                "1.19.1",
                "1.19.2"
            ],
            "javaProtocol": 760
        }
    },
    "cpuCount": 1,
    "cpuName": "AMD Ryzen 5 3600 6-Core Processor",
    "systemLocale": "en",
    "systemEncoding": "UTF-8",
    "gitInfo": {
        "buildNumber": "1209",
        "git.commit.id.abbrev": "f4b8105",
        "git.commit.id": "f4b810534b28027a9f828444ba14bb28776bdd18",
        "git.branch": "master",
        "git.remote.origin.url": "https://github.com/GeyserMC/Geyser.git"
    },
    "config": {
        "autoconfiguredRemote": false,
        "bedrock": {
            "address": "0.0.0.0",
            "port": 25647,
            "clone-remote-port": true,
            "motd1": "§6G§eK§r|§bS1/2§r|§cBW",
            "motd2": "Another Geyser server.",
            "server-name": "§6G§eK§r|§bS1/2§r|§cBW",
            "compression-level": 6,
            "enable-proxy-protocol": false,
            "proxy-protocol-whitelisted-ips": []
        },
        "remote": {
            "address": "***",
            "port": 25594,
            "auth-type": "ONLINE",
            "allow-password-authentication": true,
            "use-proxy-protocol": false,
            "forward-hostname": false
        },
        "userAuths": null,
        "metrics": {
            "enabled": true,
            "uuid": "e095b3cd-f517-4338-b851-aaa02a412933"
        },
        "floodgateKeyPath": "file:///home/container/key.pem",
        "saved-user-logins": [
            "ThisExampleUsernameShouldBeLongEnoughToNeverBeAnXboxUsername",
            "ThisOtherExampleUsernameShouldAlsoBeLongEnough"
        ],
        "floodgate-key-file": "key.pem",
        "command-suggestions": true,
        "passthrough-motd": false,
        "passthrough-player-counts": false,
        "passthrough-protocol-name": false,
        "legacy-ping-passthrough": true,
        "ping-passthrough-interval": 3,
        "forward-player-ping": true,
        "max-players": 2022,
        "debug-mode": false,
        "allow-third-party-capes": true,
        "show-cooldown": "title",
        "show-coordinates": false,
        "disable-bedrock-scaffolding": false,
        "always-quick-change-armor": false,
        "emote-offhand-workaround": "EMOTES_AND_OFFHAND",
        "allow-third-party-ears": false,
        "default-locale": null,
        "cache-images": 0,
        "allow-custom-skulls": true,
        "max-visible-custom-skulls": 128,
        "custom-skull-render-distance": 32,
        "add-non-bedrock-items": true,
        "above-bedrock-nether-building": false,
        "force-resource-packs": true,
        "xbox-achievements-enabled": false,
        "log-player-ip-addresses": true,
        "notify-on-new-bedrock-update": true,
        "pending-authentication-timeout": 120,
        "scoreboard-packet-threshold": 20,
        "enable-proxy-connections": true,
        "mtu": 1400,
        "use-direct-connection": true,
        "config-version": 4
    },
    "floodgate": {
        "gitInfo": null,
        "config": null
    },
    "userPlatforms": {},
    "hashInfo": {
        "md5Hash": "84c0de49e9a5e33188cb4661093d6dd2",
        "sha256Hash": "8afbc9c31bbce00d28a7b1d3905890c04b586e8be9a2a33c7d2c28d030d4f874"
    },
    "ramInfo": {
        "free": 75,
        "total": 124,
        "max": 1484
    },
    "logsInfo": null,
    "bootstrapInfo": {
        "platform": "STANDALONE",
        "gui": false
    },
    "flagsInfo": {
        "flags": [
            "-Xms128M",
            "-Xmx1536M",
            "-Dsip=95.217.92.211",
            "-Dspt=25647",
            "-XX:+UseSerialGC",
            "-Dlog4j2.formatMsgNoLookups=true",
            "-Dfml.queryResult=confirm",
            "-Dterminal.jline=false",
            "-Dterminal.ansi=true",
            "-DIReallyKnowWhatIAmDoingISwear=true",
            "-Duser.timezone=Europe/Moscow",
            "-Dfile.encoding=UTF-8"
        ]
    },
    "extensionInfo": []
}
> 4. Share your geyser logs using https://mclo.gs and share the link here. 

https://mclo.gs/nvFDFDU

**Comment by Jens-Co** [comment]
Any info on this issue?

**Comment by onebeastchris** [comment]
Closing due to no response.
