### ISSUE TITLE
Add option to show real item when it matches a predicate in geyser mappings

### ISSUE THREAD

**Issue by YellowZaki** [GeyserMC/Geyser#3346]
### What feature do you want to see added?

When working with texture packs based on damage predicates on Java, you have to add this last line (damaged:1, damage:0):

```
        { "predicate": { "damaged": 0, "damage": 0.997437 },"model": "item/model3" },
        { "predicate": { "damaged": 0, "damage": 0.998078 },"model": "item/model2" },
	{ "predicate": { "damaged": 0, "damage": 0.999359 },"model": "item/model1" },
	{ "predicate": { "damaged": 1, "damage": 0.0 }, "model": "item/diamond_hoe" }
```

Because if that line is not added, a non unbreakable diamond_hoe with damage 0.999359, will show as model1.
It's like a "dummy" predicate that has to be written.

In bedrock, it translates to this last line:

```
      {
        "name": "gmdl_209",
        "allow_offhand": true,
        "icon": "gmdl_209",
        "damage_predicate": 0,
        "unbreakable": false
      },
```
The behaviour of bedrock mappings matches java mappings correctly.

The problem is that normal diamond hoes (non unbreakable) has the name "gmdl_209". In addition, they can't be placed on smithing table, hoe animation doesn't exist... It causes a lot of issues.

I suggest, adding a new option to geyser mappings, indicating if that predicates matches, make the item default (it would not be a custom item, show the real item instead). Example:

```
      {
        "default": true,
        "damage_predicate": 0,
        "unbreakable": false
      },
```

### Are there any alternatives?

I have tried removing:

```
      {
        "name": "gmdl_209",
        "allow_offhand": true,
        "icon": "gmdl_209",
        "damage_predicate": 0,
        "unbreakable": false
      },
```

From mappings. But as it matches Java behaviour, breakable diamond hoes with damage values are showing like custom items.

**Comment by onebeastchris** [comment]
This is now implemented, issue can be closed
