### ISSUE TITLE
Custom Model Data Tools Mining Speeds Bug

### ISSUE THREAD

**Issue by DarkChromaMC** [GeyserMC/Geyser#3348]
### Describe the bug

Using a netherite enchanted tools (pickaxe, shovel, axes) with custom model data demonstrates slower mining speeds when enchanted beyond their respective vanilla limits (i.e., efficiency 6). 

This bug only occurs for tools with Custom Model Data, and a texturepack is applied for custom textures using custom mapings. Previously, without the texturepack, mining speeds were not affected. This bug is only present to those on Bedrock edition.

Please see the two videos shown below to see the issue in action.

### To Reproduce

1. Use a texturepack that has tools with custom model data
2. Obtain a tool with custom model data and apply a texture to it.
3. Enchant the tool with efficiency 6 or above
4. Mine/Chop/Shovel any type of block with the tool
5. Compare the mining speeds with an equivalent tool that doesn't have a texture applied to it.

### Expected behaviour

Mining speeds are consistent with vanilla, i.e., no discrepancies in mining speeds between java and bedrock edition users.

### Screenshots / Videos

https://www.youtube.com/watch?v=RcRs_fOUOpo

https://youtu.be/U8NSbDK3aTA

### Server Version and Plugins

git-petal-"eb64b15" (MC: 1.19.2)

### Geyser Dump

https://dump.geysermc.org/knONxAiGfdbpcGgHzxffwyERxrkQpqPL

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-2c5c72f) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.30)

**Comment by Hahaa13** [comment]
+1

**Comment by Kas-tle** [comment]
Hello, could you please check if this is still an issue with the latest version of Geyser on a **1.19.40 Bedrock Client**?

**Comment by Jens-Co** [comment]
Any updates on this issue? If not I'll close this one.

**Comment by Kas-tle** [comment]
It should be left open until the PR is closed. 1.19.40 fixed most of the blocks not working, but the tags themselves from Mojang miss some blocks so some blocks still have the issue.

**Comment by Jens-Co** [comment]
Issue can be closed when #3381 gets merged.

**Comment by lbrunton** [comment]
This mining speed issue for efficiencies greater than five is unfortunately not fixed in the latest Geyser version 2.1.0-SNAPSHOT (git-master-3282962). We have tested using a pickaxe on Deepslate.

**Comment by Kas-tle** [comment]
Apologies. Upon further investigation it seems the issue with the efficiency enchantment specifically cannot be fixed at this time as it seems custom items do not respect efficiency enchantments. There is a documented sub-component of `digger` called `use_efficiency` (which we do add) but it seems that this is broken. 

See https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemcomponents/minecraft_digger. If having this fixed is important to you, I would recommend reproducing this with a behavior pack in single-player and opening an issue with Mojang https://bugs.mojang.com/secure/CreateIssue!default.jspa.

**Comment by DarkChromaMC** [comment]
Quick update regarding this bug report. One of the recent geysermc versions has addressed the efficiency enchantments on custom items. However, a new issue has arisen where the new mining speeds surpasses that of Java, which creates an unfair advantage for Bedrock players over Java players. 

I have uploaded a video below that demonstrates the differences between a Java player and a Bedrock player. In the video, it is evident that the Bedrock player can mine significantly faster using the same pickaxe which can create an unfair advantage.

 https://youtu.be/W-ByI4oEyvY

**Comment by gamer50082** [comment]
Yep can see that. A huge difference
