### ISSUE TITLE
Signs are not visible.

### ISSUE THREAD

**Issue by applebee1558** [GeyserMC/Geyser#335]
**Describe the bug**

The text on signs are not visible when connecting to the server through geyser.
**To Reproduce**
1. Go in java and place a sign with some text.
2. Go in bedrock and look at the sign, it’s empty.

**Expected behavior**

The signs should still be visible with the text on it.

**Screenshots / Videos**

**Server Version**

Spigot 1.15.2 with BungeeCord 1.15

**Geyser Version**

Latest master branch and inventory 
**Minecraft: Bedrock Edition Version**
1.14.30

**Additional Context**

I think there has been issue with this that’s closed, but it’s clearly still an issue.

**Comment by gaussandhisgun** [comment]
using latest inventory, i see all the signs with text on it

**Comment by rtm516** [comment]
Can you make sure your using the latest inventory build, and provide a screenshot and any error logs as this should be fixed.

**Comment by applebee1558** [comment]
![4EBEC276-429B-4358-8A66-341C8237FCD7](https://user-images.githubusercontent.com/30390986/79279153-3e93f480-7e62-11ea-935d-35806e8102e7.png)
That’s a screenshot

**Comment by applebee1558** [comment]
https://applebee1558.com/uploads/2020/04/ApplicationFrameHost_rI15iTygMY.png
Happens on the PC geyser too

**Comment by DoctorMacc** [comment]
This may be a problem with Spigot; can we get a picture of the sign on PC as a reference point?

**Comment by applebee1558** [comment]
This is what I see in the console with debug: https://applebee1558.com/uploads/2020/04/putty_uG86WBOWRJ.png
There's nothing else except that and player join/leave

**Comment by DoctorMacc** [comment]
Also - try Paper and see if your problem is fixed.

**Comment by applebee1558** [comment]
@DoctorMacc https://applebee1558.com/uploads/2020/04/javaw_3hH7soTNas.png
here's the sign on PC

**Comment by applebee1558** [comment]
Don't really want to switch to paper, as I had spigot working fine and everything and don't want to disrupt it. It works fine with a Java client but not with bedrock. Is there any option other than switching to another server software?

**Comment by rtm516** [comment]
Paper just adds more optimisations to spigot, should be a drop in replacement.

**Comment by RednedEpic** [comment]
> Don't really want to switch to paper, as I had spigot working fine and everything and don't want to disrupt it. It works fine with a Java client but not with bedrock. Is there any option other than switching to another server software?

This is something we're looking into fixing, however for the time being, if you want signs to work you will need to switch to Paper. The transition to Paper is harmless and will only benefit your server altogether in many ways.

**Comment by applebee1558** [comment]
Ok, thanks

**Comment by MrPowerGamerBR** [comment]
Can confirm that signs does not work on [Tuinity](https://github.com/Spottedleaf/Tuinity), running standalone proxy.

**Comment by DoctorMacc** [comment]
That means that signs do not work on chunk load except for Paper - even Tuinity, the fork of Paper.

**Comment by DoctorMacc** [comment]
For anyone having troubles, please test with build #439. It's a WIP build because signs break on Paper with it.

**Comment by WreckingU** [comment]
The latest build for bukkit #96 (Apr 27, 2020, 10:49:32 PM) is now loading signs on my paper server! 
![Annotation 2020-04-29 035033](https://user-images.githubusercontent.com/25066928/80582844-a4d55700-89cc-11ea-80ef-d35b996f1f15.png)

**Comment by DoctorMacc** [comment]
@WreckingU It was my thought that signs worked fine on Paper. Did they not work with a previous build? What build were you using?

**Comment by applebee1558** [comment]
@DoctorMacc sorry for the late reply, but your pr does seem to fix the bugs with signs not loading on my server.
