### ISSUE TITLE
Behavior pack Compatibility for bedrock (and java players later) 

### ISSUE THREAD

**Issue by DMDCR** [GeyserMC/Geyser#3354]
### What feature do you want to see added?

part 1 Behavior packs for bedrock players
part 2 even if it means conversion for java (conversion in the future) (add part 1 first, slowly roll out part 2)
I don't know the limits of part 2 and 1, but it would be a nice feature

### Are there any alternatives?

I have not found any alternatives for this request.

**Comment by Camotoy** [comment]
Geyser doesn't modify the server; this is not something we're going to implement ourselves.
Thanks anyway for the suggestion.
