### ISSUE TITLE
Multiple lines to fishing rod

### ISSUE THREAD

**Issue by JxxIT** [GeyserMC/Geyser#3359]
### Describe the bug

If you throw a fishing rod when a other geyser player is fishing the lines connect.

### To Reproduce

1. Throw a fishing rod on java.
2. Throw a fishing rod on bedrock.
Now the lines are connected.

### Expected behaviour

The lines are only connecting to the fishing rod of the player.

### Screenshots / Videos

<img width="1440" alt="Screenshot 1" src="https://user-images.githubusercontent.com/110342008/197335832-652d4d6f-6f9d-4982-bbd1-447cc873b574.png">
<img width="1440" alt="Schermafbeelding 2022-10-22 om 13 01 33" src="https://user-images.githubusercontent.com/110342008/197336114-f7466c1d-33ea-42e5-b309-93e53b34a63e.png">

### Server Version and Plugins

Plugins:
BKCommonLib
Floodgate
Geyser
GeyserSkinManager
Worldedit.

### Geyser Dump

https://dump.geysermc.org/waQwr7G3Ee4FQe2KWueH74fJsaXFweda

### Geyser Version

2.1.0-SNAPSHOT (git-master-a612be6)

### Minecraft: Bedrock Edition Device/Version

1.19.31, iPhone

**Comment by Camotoy** [comment]
And this happens on Java? Does it happen with only the Geyser and Floodgate plugins?

**Comment by JxxIT** [comment]
Yes, even with only floodgate and Geyser. It can only be seen on java an the user cannot pull the other fishing rod.

**Comment by D3ATHBRINGER13** [comment]
I don't think this is a geyser issue as it occurs when two java players are fishing near each other.

**Comment by JxxIT** [comment]
Yes, but we are on java and bedrock.

**Comment by PikaMug** [comment]
![Zorro](https://y.yarn.co/61b96df4-f9e2-432b-b95c-ce4885bc2089_text.gif)

**Comment by onebeastchris** [comment]
Is this still an issue?

**Comment by JxxIT** [comment]
I will check as soon as possible, with the latest Geyser and Floodgate version.

**Comment by JxxIT** [comment]
I can confirm, that on 1.19.4 the bug is fixed!
