### ISSUE TITLE
Bedrock Clients Don't Load World

### ISSUE THREAD

**Issue by Megukaphii** [GeyserMC/Geyser#3363]
### Describe the bug

When loading into the Java server from a Bedrock 1.19.31 client, after signing in with a Microsoft account, the inventory toolbar loads in and some world entities such as boats load in. You can also hear wolves barking. However, no blocks load in and you can only see the horizon in all directions.

### To Reproduce

1. Open Bedrock
2. Join server via Friends list section
3. Sign in via Microsoft account
4. Issue occurs

### Expected behaviour

The world should load in properly.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/40730335/197534568-d5899bed-b4f8-4193-91fd-94e01bd53b89.png)

### Geyser Dump

https://dump.geysermc.org/A1HwuiX6nLbWYIsp5B6RbNVjXYTxiEYD

### Geyser Version

2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.31 Windows

### Additional Context

Find log here:
https://mclo.gs/f5cpTUp

Possibly of note, the server is running in a Docker container on a Synology DS1621+ NAS. The Docker registry is itzg/minecraft-server.

**Comment by nikissXI** [comment]
I got the same problem. qwq

**Comment by nikissXI** [comment]
I know why, config.yml -> set it to offline

**Comment by onebeastchris** [comment]
the better, and more secure solution would be to use floodgate (exists for fabric too)
It'll allow bedrock players without a java account to join, and bypass the java account login screen. It won't require offline mode though - making it therefore secure

**Comment by Camotoy** [comment]
Your issue should be resolved as it's tied to using online mode. Let us know otherwise!

**Comment by Jerry12228** [comment]
我将版本退回2.1.0-SNAPSHOT (git-master-f4b8105)暂时性解决了这个问题
