### ISSUE TITLE
inventory bug geyser velocity + protocolize velocity

### ISSUE THREAD

**Issue by frogglen** [GeyserMC/Geyser#3366]
### Describe the bug

hello, I am using protocolize velocity with geyser velocity, I found a bug that my users reported when they enter from bedrock

this does not happen when removing protocolize velocity

### To Reproduce

install protocolize velocity + geyser velocity

### Expected behaviour

I tried this without protocolize velocity and the recipes were filled correctly

### Screenshots / Videos

https://user-images.githubusercontent.com/6269642/197875388-e74da594-040b-4d09-ac61-2152d2ddeb73.mp4

https://user-images.githubusercontent.com/6269642/197875402-b6e99e58-405d-4e19-a588-cfb940cf366c.mp4

### Server Version and Plugins

velocity #184
Geyser Build: [1221]

### Geyser Version

Geyser Build: [1221]

**Comment by Konicai** [comment]
Please include a geyser dump by running `/geyser dump` and share the link it provides here.

**Comment by frogglen** [comment]
> Please include a geyser dump by running `/geyser dump` and share the link it provides here.

https://dump.geysermc.org/Z43CY7zKJ0qhuxYEFzagY19zHcWsOI3a

**Comment by nakanotti** [comment]
Same bug?

https://user-images.githubusercontent.com/95959939/198421052-a9de2fd8-9263-4efc-8fbe-7f7b5c1ed948.mp4

Melon Block returns to Melon Slice...

----
waterfall: 1.19-506
papermc: git-Paper-242 (MC: 1.19.2)
Geyser-BungeeCord: 2.1.0-SNAPSHOT build 1223

**Comment by nakanotti** [comment]
Fixed in build 1224, In my case.
Sorry if it's not the same bug.

**Comment by onebeastchris** [comment]
@frogglen does the issue still occur?

**Comment by onebeastchris** [comment]
Closing due to no further response + potentially being fixed.
If the issue persists, provide a new Geyser dump & it will get re-opened.
