### ISSUE TITLE
No clickable crafting (on table or inventory) for Playstation Players

### ISSUE THREAD

**Issue by Geyer2000** [GeyserMC/Geyser#3368]
### Describe the bug

I run a Java 1.19.2 Server with Geyser+Floodgate. Connectivity works just fine, everything is in order, no errors are thrown in the console.

Yesterday I updated to the newest version of Geyser-Spigot to accomodate players from Playstation who have updated to 1.19.4 and couldnt connect to the older Geyser-Spigot build. Updating has fixed this issue.

Now a new issue has appeared for all players on Playstation:

They can only craft blocks/items when they place the correct recipe in the square of their inventory OR the crafting table themselves. More precisely: When they click on a recipe in the green book, the recipe DOES in fact appear in the square. But when they want to move the crafted item out of the specified inventory slot, they cant. Nothing happens.

If they craft the same item (any item that is) by placing the crafting materials themselves, this issue does not appear. They can take the item from the square just fine.

### To Reproduce

1) Use paper server 1.19.2 with newest Geyser-Build. 
2) Connect via Playstation (4 or 5)
3) Use a crafting table by **clicking on a recipe**, instead of putting in the recipe manually. No item can be crafted that way.

### Expected behaviour

Any item should be craftable by either clicking on the recipe from the book and take it from the crafted-item-slot, or by placing the recipe directly.

### Server Version and Plugins

-git-Paper-133 (MC: 1.19.2)
-Geyser 2.1.0-SNAPSHOT (git-master-ca7799d)

Plugins:
-mcMMO
-WorldGuard
-Coreprotect
-mcMMO Horse
-Essentials
-Luckperms
-EzHomes
-ez-broadcast
-DivineDrop
-Dynmap
-UltimateShop
-Citizens 2.0.30
-EasyWhitelist
-Multiverse-Core
-Multiverse-Inventories
-Multiverse-NetherPortals
-Multiverse-Portals
-Multiverse-SignPortals
-Multiverse-hardcore
-NoEncryption
-NoPlugins
-PlaceholderAPI
-PlayerStats
-PluginConstructorAPI
-PluginManager
-pvparena
-ServerSigns
-SinglePlayerSleep
-spark
-UltimateAutoRestart
-Vault
-Wild
-WorldEdit
-Griefprevention
-GSit
-DisableElytra
-CMILib
-BanItem

### Geyser Dump

https://dump.geysermc.org/AUc72RbYHd1KeYZf3epxZ2S2k1cBLIBR

### Geyser Version

Geyser 2.1.0-SNAPSHOT (git-master-ca7799d)

### Minecraft: Bedrock Edition Device/Version

Playstation 4 and 5, MC Version Bedrock 1.19.40

### Additional Context

Problem does NOT appear with players connecting from tablet/phone/switch or x-box.

**Comment by Camotoy** [comment]
Try using the latest Geyser version - this is likely fixed. Let us know otherwise.
