### ISSUE TITLE
Bedrock players getting stuck/clipping in blocks

### ISSUE THREAD

**Issue by Impactic48** [GeyserMC/Geyser#3370]
### Describe the bug

Bedrock players seem to glitch/clip into blocks randomly ever since the new 1.19.40 update.

### To Reproduce

Login
Run into a block awkwardly or fall onto a block
You clip/glitch against blocks randomly
(Watch videos included you'll see what I mean)

### Expected behaviour

No clipping/glitching into blocks

### Screenshots / Videos

https://youtu.be/vv7CCozIj4A
https://youtu.be/ydHGqrU6QaM
https://youtu.be/YipYp9-FGnc

### Server Version and Plugins

Version: git-Purpur-1732

Plugins:
https://gyazo.com/f05125e6da2c0c5dab4b7e9c5604d59c

### Geyser Dump

https://dump.geysermc.org/KZIv5STerniCcd3ciIR5lvTb410sqFwW

### Geyser Version

2.1.0-SNAPSHOT (git-master-e9b99b2)

### Minecraft: Bedrock Edition Device/Version

Multiple Platforms

### Additional Context

Running Geyser Standalone for Bedrock Proxy
Running ViaVersion on Velocity for Java Proxy

**Comment by Konicai** [comment]
Can you share the exact bedrock edition devices/versions that this happens on?

I was definitely experiencing this earlier today on https://dump.geysermc.org/2OIaevE5kJCkcTkzDWwA9rCQDSYqq7Iq with WIndows 10 but for some reason I can't reproduce it anymore on 1.19.40.2 or 1.19.31.1

**Comment by Impactic48** [comment]
Xbox, Mobile, and Windows 

Also, it's all happening on version 1.19.40. But it's not happening on 1.19.31 according to one of my players.

**Comment by Impactic48** [comment]
https://youtu.be/IBAsW_9F-o8
https://youtu.be/NdngWTtcy8s
https://youtu.be/22L9zXrqLz8

Here are 3 more videos of this occurring from another player.

**Comment by Happyrobot33** [comment]
any update on this? im still getting issues related to this

**Comment by Dinowattz** [comment]
I've found out that this glitch doesn't seem to affect creative players.. and that's 'cause they don't respawn as often! This clipping bug has something to do with respawning/death of the player

Here's a video of it happening after respawn: https://youtu.be/EBk9pL0WtBI
I hope this helps somehow

**Comment by Happyrobot33** [comment]
The issue with jumping being rubberbandy is also back, likely related to 1.19.4 though

**Comment by pimentelleo** [comment]
Same here for my users, latest geyser, latest paper, latest bedrock client

**Comment by offhandsum** [comment]
Same for me. The problem appears only with 1.19.40 players on any devices

**Comment by onebeastchris** [comment]
Did some testing -
1. this affects geyser-spigot, geyser-velocity (didnt try others, but likely)
2. This only happens after a respawn, rejoining fixes it
so.. theres probably something odd going on with respawning

**Comment by SamGamerYT** [comment]
+1 Same issue happening, Player Respawned = Issues started happening

**Comment by purejosh** [comment]
Good to know this isn't just me. This is a terribly annoying bug. Please let me know if there's anything I can do to help test.

**Comment by Salubritas** [comment]
Still seeing this on Nintendo Switch even in creative mode so no deaths or respawns. Seems to be with less-than-full-height blocks like steps and carpet etc.

**Comment by Camotoy** [comment]
As a problem that has only started since 1.19.40? Can you provide a Geyser dump?

**Comment by googleooer** [comment]
Happens in 1.20.1

**Comment by Chew** [comment]
> Can you provide a Geyser dump?

**Comment by Bserz1331** [comment]
Me too,I'm still trying to figure out why.
https://dump.geysermc.org/TsCxKOVrcMmKk34VuDfpXVJ633SH4QMH

**Comment by audi4545** [comment]
Pls help bedrock player are just stucking to blocks ame issu like before 
https://dump.geysermc.org/bgCkxUFLdi16sxDUoVHAQWzk9O8nDagz

**Comment by onebeastchris** [comment]
This is an old issue, please open a new one with reproduction steps.

**Comment by audi4545** [comment]
I did with this 
https://github.com/GeyserMC/Geyser/issues/4269
Pls help
