### ISSUE TITLE
Server is working fine from Java but not in Bedrock edition.

### ISSUE THREAD

**Issue by zubaafs222** [GeyserMC/Geyser#3372]
### Describe the bug

I am facing an issue where Java players can join play with no problem but bedrock players are lagging. They can play for only first 2minutes without lag and then the lag starts. When they rejoin, they can't do anything.

### To Reproduce

Login
Play without lag for 2minutes
Starts lagging( can't break any blocks)

### Expected behaviour

Players from bedrock edition should not be lagging

### Screenshots / Videos

https://youtu.be/T7BOeJb0wKQ

### Server Version and Plugins

1.19.2 Minecraft

### Geyser Dump

c.org/MVuZ9uRcvw9KfrUowuZ5hGykoJOqYeQv

### Geyser Version

1229 Geyser

### Minecraft: Bedrock Edition Device/Version

Minecraft for windows and Pocket edition

**Comment by onebeastchris** [comment]
#2861 the workaround in that issue will fix yours too.
Also, please add the full dump link in future issues - also do note that we won't provide further support with offline mode.
