### ISSUE TITLE
Mapping multiple custom model data

### ISSUE THREAD

**Issue by MastoryMd5** [GeyserMC/Geyser#3377]
### Describe the bug

What i did:
```
      {
        "name": "my_item.custom",
        "allow_offhand": true,
        "custom_model_data": 49,
        "custom_model_data": 50,
        "custom_model_data": 51
      }
```

And the result unfortunately is that only the custom model data 51 gets mapped and the other ones get skipped

### To Reproduce

Do what i did above.

### Expected behaviour

Should be able to map multiple custom model data to one single item

### Server Version and Plugins

Velocity 3.1.2-SNAPSHOT (git-7d77bfb5-b184)

### Geyser Dump

https://dump.geysermc.org/UtKv0DsRKJcSr7QsWzpkCldhEBkXymqE

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-90c9d5b)

### Minecraft: Bedrock Edition Device/Version

Windows 10 edition, 1.19.40

**Comment by Kas-tle** [comment]
If you would like to achieve this, simply map the item (let's say item A) to custom model data 49, and put the entry for the next item (let's say item B) at custom model data 52. By this, custom model data 49 to 51 will all display as item A.

**Comment by MastoryMd5** [comment]
I understand, although not the best thing to do it works, thank you for the fast response.
