### ISSUE TITLE
[geyser]: Failed to translate ClientboundContainerSetContentPacket

### ISSUE THREAD

**Issue by DimaSergeew** [GeyserMC/Geyser#3379]
### Describe the bug

This error occurs after the recent updates of geyser, if this error is not the fault of geyser please tell me what causes it and what it means
https://mclo.gs/LgpZ4qg
### To Reproduce

They sometimes arise from the players Geyser who play at me, what exactly they do and its causes can not be understood

### Expected behaviour

That she will not be

### Screenshots / Videos

-

### Server Version and Plugins

[13:24:09 INFO]: Velocity 3.1.2-SNAPSHOT (git-7d77bfb5-b184)
On this server Geyser version 2.1.0-SNAPSHOT (git-master-48050e7) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.40)

### Geyser Dump

https://dump.geysermc.org/kkCR9NiHqg5whT9nJBlm9engeAJ0CHOJ

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-48050e7) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.40)

### Minecraft: Bedrock Edition Device/Version

Minecraft 1.19.40, phone - all

**Comment by onebeastchris** [comment]
Does this issue still occur?

**Comment by onebeastchris** [comment]
Closing due to no response.
