### ISSUE TITLE
Runtime Error Help

### ISSUE THREAD

**Issue by Game5048-bilibili** [GeyserMC/Geyser#3382]
### Describe the bug

Hello, after running Geyser, my server uses the bedrock version to enter, but it will always be inexplicably disconnected. After re entering, it will be stuck in the void and will not load the terrain. At this time, Java reports an error: Can not translate packet: ClientboundLevelChuckWithLightPacket. Then other players cannot enter the server. They must restart the server to re-enter the server, but the same server can operate normally on another server without any changes, What is this problem?

### To Reproduce

start my server
Join the geyser server
player is disconnected by error
rejoin and stuck in the void
restart the server

### Expected behaviour

I hope Geyser running normally

### Server Version and Plugins

Spigot 1.19
plugin only geyser

### Geyser Version

latast version

### Minecraft: Bedrock Edition Device/Version

1.19.2

**Comment by Camotoy** [comment]
Please provide a Geyser dump and a log of the error.

**Comment by Game5048-bilibili** [comment]
We have already found the wrong.Thanks.
Our CPU is 11th core so it has a physical problem that caused my server's crash
