### ISSUE TITLE
error when a bedrock player joins which causes most of the server players to get kicked

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#3383]
### Describe the bug

when a bedrock player joins, sometimes it will kick the majority of the online players. after this happens no player java or bedrock is able to join the server. they get the connection time out message on screen. the issue fixes its self if all remaining players on the server that didnt get kicked leave the server making the population 0. then players can join again. 

### To Reproduce

happens randomly when a bedrock player joins

### Expected behaviour

players getting kicked with error on below image, then attempting to join or rejoin they get connection timed out 

### Screenshots / Videos

![bandicam 2022-11-03 16-58-00-587](https://user-images.githubusercontent.com/92684055/199968936-7ed86f1f-a429-4be7-8edc-d7f857e11ec3.jpg)

### Server Version and Plugins

  [Fri 12:07:42 INFO ] Checking version, please wait...
  [Fri 12:07:42 INFO ] Current: git-Purpur-1835 (MC: 1.19.2)*
Previous: git-Paper-245 (MC: 1.19.2)
* You are running the latest version

### Geyser Dump

https://dump.geysermc.org/lOWb85K2CM1HTi8QI9GpZEZdUaLPwaEO

### Geyser Version

2.1.0-SNAPSHOT (git-master-592b48d)

### Minecraft: Bedrock Edition Device/Version

on the latest version and all bedrock devices

### Additional Context

this has been happening for about 4 weeks now.

**Comment by Camotoy** [comment]
I don't think this is our error... but even so, seeing as this is the first report I've seen of this issue, there's probably another plugin causing it. I'd try removing plugins on both the backend server and Bungee and seeing if the error stops.

**Comment by huangpianmao** [comment]
I think I have the same problem

**Comment by Jens-Co** [comment]
Any updates on this issue? Otherwise I'll close this in a few days.

**Comment by onebeastchris** [comment]
Closing due to no response.
