### ISSUE TITLE
Quickly change inventory while casting fishing rod

### ISSUE THREAD

**Issue by 1470429149** [GeyserMC/Geyser#3384]
### Describe the bug

When I repeatedly throw a fishing rod at the entity, my inventory is quickly switched，eg: I have a fishing rod in the first slot of my backpack, and when I throw a fishing rod to catch an entity, my held item will quickly switch to the second slot of the backpack.

### To Reproduce

Tossing a fishing rod at the entity, and then my holding item suddenly switches to the backpack slot in a different location

### Expected behaviour

Repeated throwing of fishing rods at entities I shouldn't be forced to change handheld inventory slots

### Screenshots / Videos

Uploading 124.mp4…

### Server Version and Plugins

Geyser 2.1.0-SNAPSHOT (git-master-cc82f4b) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.40)
Paper 1.17

### Geyser Dump

https://dump.geysermc.org/lNeUIs25tgdbFw3lm08D9bZ3qHYbCL2U

### Geyser Version

Geyser 2.1.0-SNAPSHOT (git-master-cc82f4b) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.40)

### Minecraft: Bedrock Edition Device/Version

1.19.0

**Comment by 1470429149** [comment]
Uploading 124.mp4…

**Comment by 1470429149** [comment]
Uploading 124.mp4…

**Comment by 1470429149** [comment]
Uploading 124.mp4…

**Comment by Konicai** [comment]
You need to wait for the file to finish uploading before you post the comment.

**Comment by 1470429149** [comment]
https://user-images.githubusercontent.com/96332168/200096252-16fd1cb4-0331-45c5-a969-4739ca61bf5a.mp4

**Comment by 1470429149** [comment]
Geyser dump：
https://dump.geysermc.org/lNeUIs25tgdbFw3lm08D9bZ3qHYbCL2U

**Comment by Konicai** [comment]
Does this only occur with Geyser/Floodgate/Viaversion?

**Comment by 1470429149** [comment]
> 您需要等待文件完成上传，然后才能发表评论。`/geyser dump`此外，请通过运行并在此处共享它提供给您的链接来包含间歇泉转储

ok , thank you

**Comment by 1470429149** [comment]
> 



> 这只发生在 Geyser/Floodgate/Viversion 上吗？

Yes, I didn't notice this problem when trying to use the java version of minecraft

**Comment by 1470429149** [comment]
> Does this only occur with Geyser/Floodgate/Viaversion?
Forgive me if my description is not clear, I'm using the java version minecraft doesn't have the problem of quickly switching inventory

**Comment by Konicai** [comment]
Are you still experiencing this issue?
