### ISSUE TITLE
Dying then respawning in another world creates ghost like state

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Geyser#3386]
### Describe the bug

When I die in a custom dimension, then respawn in the overworld, the playermodel is deleted, I cannot move, I have to relog to be able to move. Maybe because the custom dimension has an "overworld" world type?

Video: https://streamable.com/rdbkaj

### To Reproduce

Die in custom dimension, respawn

### Expected behaviour

Player should respawn normally

### Screenshots / Videos

https://streamable.com/rdbkaj

### Server Version and Plugins

paper 1.19.2 - 260 (latest) no via-version or any protocol hacks

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-592b48d) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.40)

### Minecraft: Bedrock Edition Device/Version

Minecraft windows 11

**Comment by Camotoy** [comment]
Please attach a Geyser dump.

**Comment by onebeastchris** [comment]
Could you re-send the video if this is still occurring?

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
