### ISSUE TITLE
Inventory does not refresh.

### ISSUE THREAD

**Issue by TermitCG** [GeyserMC/Geyser#339]
Sorry for my bad English.
**Describe the bug**
While playing on minigame servers you can move/drop things in your inventory even if you are in lobby and there's a plugin to prevent you from doing that.

**To Reproduce**
1.Make spigot/paperspigot/bukkit server.
2. install https://www.spigotmc.org/resources/system-lobby-source-gadgets.40471/ plugin
3. Now, you can do anything with your inventory, but when you hit other player, inventory refreshes and these dropped/moved items go back in place.

**Expected behavior**
I can't move things in my inventory while I'm on lobby server

**Screenshots / Videos**
-

**Server Version**
no permissions, but i think it's some custom server core or bungeecord

**Geyser Version**
latest.

**Minecraft: Bedrock Edition Version**
1.14.30

**Additional Context**
Inventory doesn't refresh by just hitting player on every server.

**Comment by RednedEpic** [comment]
> Sorry for my bad English.
> **Describe the bug**
> While playing on minigame servers you can move/drop things in your inventory even if you are in lobby and there's a plugin to prevent you from doing that.
> 
> **To Reproduce**
> 1.Make spigot/paperspigot/bukkit server.
> 2. install https://www.spigotmc.org/resources/system-lobby-source-gadgets.40471/ plugin
> 3. Now, you can do anything with your inventory, but when you hit other player, inventory refreshes and these dropped/moved items go back in place.
> 
> **Expected behavior**
> I can't move things in my inventory while I'm on lobby server
> 
> ## **Screenshots / Videos**
> **Server Version**
> no permissions, but i think it's some custom server core or bungeecord
> 
> **Geyser Version**
> latest.
> 
> **Minecraft: Bedrock Edition Version**
> 1.14.30
> 
> **Additional Context**
> Inventory doesn't refresh by just hitting player on every server.

Are you using the inventory branch? In the future, please specify a build number and branch for the Geyser version.

**Comment by TermitCG** [comment]
Full name of geyser version: 1.0-SNAPSHOT
Are you using the inventory branch?: Yes.

**Comment by toinouH** [comment]
@TermitCG Does this bug still exist? (and if yes update your issue and add more infos if it's possible)

**Comment by DoctorMacc** [comment]
As there has been no update on this issue, I am closing it. If a similar issue persists, please open a new one!
