### ISSUE TITLE
Unicodes cause signs to bug

### ISSUE THREAD

**Issue by CCSNova** [GeyserMC/Geyser#3390]
### Describe the bug

Adding special unicode characters on a sign causes weird behaviour with sign.

### To Reproduce

1. Copy this "■"
2. Put it at each end of a line of a sign

### Expected behaviour

The sign would render the text properly

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/100384210/200670306-7b893fba-6b16-42a2-9cda-87942dd4987b.png)
Java

![image](https://user-images.githubusercontent.com/100384210/200670356-3d5abbbd-68a7-47e0-88f4-dd467b095a04.png)
Bedrock

### Server Version and Plugins

![image](https://user-images.githubusercontent.com/100384210/200670455-7abea424-6027-41d1-8d4b-6d1989d71f9b.png)

### Geyser Dump

https://dump.geysermc.org/WyU9cPOdppq2UdXFkAicKpSIUnllUJIi

### Geyser Version

2.1.0 SNAPSHOT (git-master-592b48d)

### Minecraft: Bedrock Edition Device/Version

1.19.41 Windows

**Comment by onebeastchris** [comment]
Since 1.20 had some changes revolving around signs; could you re-test this with the latest version of Geyser?

**Comment by DiveaLism** [comment]
Yeah sure! Also I didn't know you checked issues so often, and very old ones, ~~long time no see btw, not sure if you even remember me~~

**Comment by Konicai** [comment]
Likely something to do with our character width calculation
