### ISSUE TITLE
Measurement warnings appeared after updating GeyserMC#1223

### ISSUE THREAD

**Issue by DimaSergeew** [GeyserMC/Geyser#3392]
### Describe the bug

Measurement warnings appeared after Geyser updated GeyserMC#1223, "[14:59:35 WARN] [geyser]: The server uses chunks higher than Bedrock can accept! To avoid problems, the height of the chunks must remain between Y0 and Y256 in the minecraft:the_nether dimension.
It keeps spamming the Velocity console and messing up the logs. Please fix it!

### To Reproduce

Appears when logging in because I use World_Nether for authorization and registration

### Expected behaviour

Hopefully such a simple fix will be accomplished. Thanks in advance

### Screenshots / Videos

![Screenshot_1](https://user-images.githubusercontent.com/75163645/201086613-a9664814-09ad-4751-9f12-3a9375dda739.png)

### Server Version and Plugins

[15:02:36 INFO]: Velocity 3.1.2-SNAPSHOT (git-2d072151-b185)
 Plugins: ajqueue, floodgate, geyser, limboapi, limboauth, limbofilter, litebans, luckperms, matrixbungee, minimotd-velocity, plan, skinsrestorer, spark

### Geyser Dump

-

### Geyser Version

This server has Geyser version 2.1.0-SNAPSHOT (git-master-592b48d) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.40)

### Minecraft: Bedrock Edition Device/Version

-

### Additional Context

-

**Comment by Camotoy** [comment]
Are these issues now resolved?

**Comment by DimaSergeew** [comment]
> Are these issues now resolved?

Yes, the warning is gone, but many people can't log in when you go to hell to authorize them, the game crashes. Before this update, we didn't have this at the time of landscape generation

**Comment by DimaSergeew** [comment]
Yes, some of our player, when trying to join the server, have their minecraft crashed, it seems like you changed the code which before was crashing their minecraft because of incompatibility with LimboFilter, and now the situation is worse

**Comment by Camotoy** [comment]
The crashing should also now be resolved in the latest build.
