### ISSUE TITLE
Right-to-left languages appear reversed on Bedrock

### ISSUE THREAD

**Issue by losttribemc** [GeyserMC/Geyser#3394]
### Describe the bug

When writing in a right-to-left language on a Java server and connecting with a Bedrock client, the Bedrock client sees the writing in reverse, so it is illegible.

### To Reproduce

Create a sign/hologram with words in either Hebrew/Arabic/other right to left language on a Java server with Geyser, and then attempt to view it on a Bedrock client.

### Expected behaviour

The words would appear normal, and not flipped.

### Screenshots / Videos

Photo 1 is how it is supposed to look (on Java, how it looks)
Photo 2 is how it looks (on Bedrock)
![Photo 1](https://user-images.githubusercontent.com/112014735/201178946-3489004b-da4f-434f-9ed8-d72efaf27109.png)
![Photo 2](https://user-images.githubusercontent.com/112014735/201178814-c8a5b2f2-65b5-4b12-9094-bffc89fe3b89.PNG)

### Server Version and Plugins

This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)
You are running the latest version
Previous version: git-Paper-409 (MC: 1.17.1)
Geyser build 1228 for Bungeecord, using multi-server instance, Bungeecord version
This server is running BungeeCord version git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:2d369e8:1664 by md_5

### Geyser Dump

https://dump.geysermc.org/R1aeTBRV4ee8uWr1S2wJCYXJcW0BnB7b

### Geyser Version

git-master-b1d832d

### Minecraft: Bedrock Edition Device/Version

1.19.41

**Comment by onebeastchris** [comment]
I think this is linked to a bedrock bug, e.g. the same happens on just bedrock with arabic 
https://bugs.mojang.com/browse/MCPE-140999

**Comment by Konicai** [comment]
https://bugs.mojang.com/browse/MCPE-102971 seems to be the main report

**Comment by onebeastchris** [comment]
Closing as this is a Bedrock edition bug - unfortunately nothing we can do about it.
