### ISSUE TITLE
[Geyser-Fabric] Can't join server, stuck on locating

### ISSUE THREAD

**Issue by TaydenThe** [GeyserMC/Geyser#3395]
### Describe the bug

Bedrock users are unable to join my server after the 1.19.41 update. It fails to locate the server.

### To Reproduce

1. Install Geyser-Fabric on a Fabric server
2. Attempt to join on Bedrock 1.19.41

### Expected behaviour

Bedrock users are able to join.

### Server Version and Plugins

I don't have a /version command.

 "platform": "FABRIC",
        "platformVersion": "0.14.9",
        "environmentType": "SERVER",
        "serverIP": "0.0.0.0",
        "serverPort": 25578,
        "mods": [
            {
                "name": "adventure-platform-fabric",
                "id": "adventure-platform-fabric",
                "version": "5.4.0-SNAPSHOT",
                "authors": [
                    "kashike",
                    "zml",
                    "Luck",
                    "Electroid"
                ]
            },
            {
                "name": "Carpet Mod",
                "id": "carpet",
                "version": "1.4.84",
                "authors": [
                    "gnembon, ..."
                ]
            },
            {
                "name": "Cloud",
                "id": "cloud",
                "version": "1.7.0-SNAPSHOT",
                "authors": [
                    "Citymonstret",
                    "zml",
                    "jmp"
                ]
            },
            {
                "name": "cloud-brigadier",
                "id": "cloud_commandframework_cloud-brigadier_",
                "version": "1.7.0-SNAPSHOT",
                "authors": []
            },
            {
                "name": "cloud-core",
                "id": "cloud_commandframework_cloud-core_",
                "version": "1.7.0-SNAPSHOT",
                "authors": []
            },
            {
                "name": "cloud-services",
                "id": "cloud_commandframework_cloud-services_",
                "version": "1.7.0-SNAPSHOT",
                "authors": []
            },
            {
                "name": "Collective (Fabric)",
                "id": "collective-fabric",
                "version": "5.11",
                "authors": [
                    "Rick South"
                ]
            },
            {
                "name": "jackson-dataformat-yaml",
                "id": "com_fasterxml_jackson_dataformat_jackson-dataformat-yaml",
                "version": "2.13.0",
                "authors": []
            },
            {
                "name": "ChoiceTheorem's Overhauled Villages",
                "id": "ctov",
                "version": "3.1.2",
                "authors": [
                    "ChoiceTheorem"
                ]
            },
            {
                "name": "When Dungeons Arise",
                "id": "dungeons_arise",
                "version": "2.1.51",
                "authors": [
                    "Aureljz, DiamondTown & Zephyrusj"
                ]
            },
            {
                "name": "Essential Commands Core",
                "id": "ec-core",
                "version": "1.3.0-mc1.19.2",
                "authors": [
                    "John Paul R. (JP79194)"
                ]
            },
            {
                "name": "Essential Commands",
                "id": "essential_commands",
                "version": "0.29.0-mc1.19.2",
                "authors": [
                    "John Paul R. (JP79194)"
                ]
            },
            {
                "name": "Fabric API",
                "id": "fabric-api",
                "version": "0.64.0+1.19.2",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric API Base",
                "id": "fabric-api-base",
                "version": "0.4.12+93d8cb8290",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric API Lookup API (v1)",
                "id": "fabric-api-lookup-api-v1",
                "version": "1.6.10+93d8cb8290",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Biome API (v1)",
                "id": "fabric-biome-api-v1",
                "version": "9.0.18+c6af733c90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Command API (v1)",
                "id": "fabric-command-api-v1",
                "version": "1.2.12+f71b366f90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Command API (v2)",
                "id": "fabric-command-api-v2",
                "version": "2.1.8+93d8cb8290",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Commands (v0)",
                "id": "fabric-commands-v0",
                "version": "0.2.29+df3654b390",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Containers (v0)",
                "id": "fabric-containers-v0",
                "version": "0.1.35+df3654b390",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Content Registries (v0)",
                "id": "fabric-content-registries-v0",
                "version": "3.4.0+6064db2a90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Convention Tags",
                "id": "fabric-convention-tags-v1",
                "version": "1.1.2+93d8cb8290",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Crash Report Info (v1)",
                "id": "fabric-crash-report-info-v1",
                "version": "0.2.6+aeb40ebe90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Data Generation API (v1)",
                "id": "fabric-data-generation-api-v1",
                "version": "5.2.2+b598f4ac90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Dimensions API (v1)",
                "id": "fabric-dimensions-v1",
                "version": "2.1.32+0dd10df690",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Entity Events (v1)",
                "id": "fabric-entity-events-v1",
                "version": "1.4.19+9ff28f4090",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Events Interaction (v0)",
                "id": "fabric-events-interaction-v0",
                "version": "0.4.29+c6af733c90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Events Lifecycle (v0)",
                "id": "fabric-events-lifecycle-v0",
                "version": "0.2.29+df3654b390",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Game Rule API (v1)",
                "id": "fabric-game-rule-api-v1",
                "version": "1.0.22+c6af733c90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Item API (v1)",
                "id": "fabric-item-api-v1",
                "version": "1.5.8+93d8cb8290",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Item Groups (v0)",
                "id": "fabric-item-groups-v0",
                "version": "0.3.32+70efcffe90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Lifecycle Events (v1)",
                "id": "fabric-lifecycle-events-v1",
                "version": "2.2.0+33ffe9ec90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Loot API (v2)",
                "id": "fabric-loot-api-v2",
                "version": "1.1.6+83a8659290",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Loot Tables (v1)",
                "id": "fabric-loot-tables-v1",
                "version": "1.1.9+9e7660c690",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Message API (v1)",
                "id": "fabric-message-api-v1",
                "version": "5.0.4+93d8cb8290",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Mining Level API (v1)",
                "id": "fabric-mining-level-api-v1",
                "version": "2.1.17+33fbc73890",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Networking API (v1)",
                "id": "fabric-networking-api-v1",
                "version": "1.2.5+c6af733c90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Networking (v0)",
                "id": "fabric-networking-v0",
                "version": "0.3.22+df3654b390",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Object Builder API (v1)",
                "id": "fabric-object-builder-api-v1",
                "version": "4.0.14+93d8cb8290",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Particles (v1)",
                "id": "fabric-particles-v1",
                "version": "1.0.11+79adfe0a90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "fabric-permissions-api",
                "id": "fabric-permissions-api-v0",
                "version": "0.2-SNAPSHOT",
                "authors": [
                    "Luck"
                ]
            },
            {
                "name": "Fabric Registry Sync (v0)",
                "id": "fabric-registry-sync-v0",
                "version": "0.9.26+c6af733c90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Rendering Data Attachment (v1)",
                "id": "fabric-rendering-data-attachment-v1",
                "version": "0.3.15+aeb40ebe90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Rendering Fluids (v1)",
                "id": "fabric-rendering-fluids-v1",
                "version": "3.0.8+c6af733c90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Resource Conditions API (v1)",
                "id": "fabric-resource-conditions-api-v1",
                "version": "2.1.0+aae9039d90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Resource Loader (v0)",
                "id": "fabric-resource-loader-v0",
                "version": "0.7.2+70efcffe90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Screen Handler API (v1)",
                "id": "fabric-screen-handler-api-v1",
                "version": "1.3.1+1cc24b1b90",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Transfer API (v1)",
                "id": "fabric-transfer-api-v1",
                "version": "2.1.1+93d8cb8290",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Transitive Access Wideners (v1)",
                "id": "fabric-transitive-access-wideners-v1",
                "version": "1.3.1+42d99c3290",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "Fabric Loader",
                "id": "fabricloader",
                "version": "0.14.9",
                "authors": [
                    "FabricMC"
                ]
            },
            {
                "name": "FerriteCore",
                "id": "ferritecore",
                "version": "4.2.1",
                "authors": [
                    "malte0811"
                ]
            },
            {
                "name": "fiber",
                "id": "fiber",
                "version": "0.23.0-2",
                "authors": [
                    "086",
                    "Pyrofab"
                ]
            },
            {
                "name": "Floodgate-Fabric",
                "id": "floodgate",
                "version": "2.2.0-SNAPSHOT",
                "authors": [
                    "GeyserMC"
                ]
            },
            {
                "name": "Geyser-Fabric",
                "id": "geyser-fabric",
                "version": "2.1.0-SNAPSHOT",
                "authors": [
                    "GeyserMC"
                ]
            },
            {
                "name": "Image2Map",
                "id": "image2map",
                "version": "0.3.0",
                "authors": [
                    "Essem",
                    "Patbox"
                ]
            },
            {
                "name": "geantyref",
                "id": "io_leangen_geantyref_geantyref",
                "version": "1.3.13",
                "authors": []
            },
            {
                "name": "OpenJDK 64-Bit Server VM",
                "id": "java",
                "version": "17",
                "authors": []
            },
            {
                "name": "LazyDFU",
                "id": "lazydfu",
                "version": "0.1.3",
                "authors": [
                    "tuxed"
                ]
            },
            {
                "name": "Lithium",
                "id": "lithium",
                "version": "0.10.0",
                "authors": [
                    "JellySquid",
                    "2No2Name"
                ]
            },
            {
                "name": "Map Canvas API",
                "id": "map-canvas-api",
                "version": "0.2.0+1.19.1",
                "authors": [
                    "Patbox"
                ]
            },
            {
                "name": "memory Leak Fix",
                "id": "memoryleakfix",
                "version": "1.19.1-0.7.0",
                "authors": [
                    "FX - PR0CESS"
                ]
            },
            {
                "name": "Minecraft",
                "id": "minecraft",
                "version": "1.19.2",
                "authors": []
            },
            {
                "name": "adventure-api",
                "id": "net_kyori_adventure-api",
                "version": "4.11.0",
                "authors": []
            },
            {
                "name": "adventure-key",
                "id": "net_kyori_adventure-key",
                "version": "4.11.0",
                "authors": []
            },
            {
                "name": "adventure-platform-api",
                "id": "net_kyori_adventure-platform-api",
                "version": "4.1.0",
                "authors": []
            },
            {
                "name": "adventure-text-logger-slf4j",
                "id": "net_kyori_adventure-text-logger-slf4j",
                "version": "4.11.0",
                "authors": []
            },
            {
                "name": "adventure-text-minimessage",
                "id": "net_kyori_adventure-text-minimessage",
                "version": "4.11.0",
                "authors": []
            },
            {
                "name": "adventure-text-serializer-gson",
                "id": "net_kyori_adventure-text-serializer-gson",
                "version": "4.11.0",
                "authors": []
            },
            {
                "name": "adventure-text-serializer-plain",
                "id": "net_kyori_adventure-text-serializer-plain",
                "version": "4.11.0",
                "authors": []
            },
            {
                "name": "examination-api",
                "id": "net_kyori_examination-api",
                "version": "1.3.0",
                "authors": []
            },
            {
                "name": "examination-string",
                "id": "net_kyori_examination-string",
                "version": "1.3.0",
                "authors": []
            },
            {
                "name": "Placeholder API",
                "id": "placeholder-api",
                "version": "2.0.0-beta.7+1.19",
                "authors": [
                    "Patbox"
                ]
            },
            {
                "name": "Pal",
                "id": "playerabilitylib",
                "version": "1.6.0",
                "authors": [
                    "Pyrofab"
                ]
            },
            {
                "name": "sgui",
                "id": "sgui",
                "version": "1.1.5+1.19.1",
                "authors": [
                    "Patbox"
                ]
            },
            {
                "name": "Smooth Boot",
                "id": "smoothboot",
                "version": "1.19-1.7.1",
                "authors": [
                    "UltimateBoomer",
                    "fantahund"
                ]
            },
            {
                "name": "Starlight",
                "id": "starlight",
                "version": "1.1.1+fabric.ae22326",
                "authors": [
                    "Spottedleaf"
                ]
            },
            {
                "name": "Towns and Towers - Structure Add-on",
                "id": "t_and_t",
                "version": "1.8.2",
                "authors": [
                    "Kubek and Biban_Auriu"
                ]
            },
            {
                "name": "Terralith",
                "id": "terralith",
                "version": "2.3",
                "authors": [
                    "Starmute"
                ]
            },
            {
                "name": "Towers of the Wild: Additions",
                "id": "totw_additions",
                "version": "1.2.3",
                "authors": [
                    "Aurelj"
                ]
            },
            {
                "name": "Your Items Are Safe (Fabric)",
                "id": "youritemsaresafe-fabric",
                "version": "2.1",
                "authors": [
                    "Rick South"

### Geyser Dump

https://dump.geysermc.org/f2iIqXlY31CL5BUcdNUnr8uDymE3o8yd

### Geyser Version

2.1.0-SNAPSHOT (Fabric)

### Minecraft: Bedrock Edition Device/Version

1.19.41, Windows 10 (probably all platforms)

**Comment by onebeastchris** [comment]
Are you using a server hosting provider? If yes, which one would that be?
Additionally, what does the "Geyser connectiontest [yourIP]:[yourGeyserPort]" in the server console (without square brackets) return?

**Comment by TaydenThe** [comment]
I am using Shockbyte, sorry for the late response. I don't have a geyser connection test command. I tried using both the console and in-game. I'm on the latest version (I updated like 20mins ago)

**Comment by TaydenThe** [comment]
I'm aware that Shockbyte only allows one UDP port. Geyser was working perfectly until Bedrock edition updated to 1.19.41

**Comment by onebeastchris** [comment]
For shockbyte specifically - you need to set bedrock address to the java address, and bedrock port to the java port.
Since this is a setup issue - please refer to our docs on https://wiki.geysermc.org/geyser/setup/, and if you are still facing issues, our support channel on the GeyserMC discord server would help :)
