### ISSUE TITLE
Geyser Anvil cannot be used to refine custom items.

### ISSUE THREAD

**Issue by Wisherss** [GeyserMC/Geyser#3396]
### Describe the bug

I've installed a plugin that can use the Enchant table and use Anvil to refine furnace-type equipment. In the Java version, Anvil furnace can be beaten with the Enchanted Book, but in the Bedrock version it can't. When I do it, there is always an error message on the console. I've contacted the admin of that plugin but they told me to contact Geyser.

### To Reproduce

When bringing the furnace and the Enchanted Book into the Anvil, an Eror message will appear.

### Expected behaviour

I would like to fix Bedrock version to work like Java version.

### Screenshots / Videos

![Screenshot 2022-11-11 123435](https://user-images.githubusercontent.com/107991332/201270889-75fff8dc-9c64-4832-a63b-84fe210bac3f.png)
![Screenshot 2022-11-11 123504](https://user-images.githubusercontent.com/107991332/201270892-8d1c38a0-4cdd-4adb-8b54-4ac09f174241.png)

### Server Version and Plugins

purpur-1838 (MC-1.19.2)
You are running the latest version
![Screenshot 2022-11-11 124757](https://user-images.githubusercontent.com/107991332/201272233-12dfde24-073b-4aeb-823b-321c02e5d226.png)

### Geyser Dump

https://dump.geysermc.org/bm6Kj2gpgrkQBblCwWG4KM9tQwdl8QaP

### Geyser Version

2.1.0-SNAPSHOT (git-master-b1d832d)

### Minecraft: Bedrock Edition Device/Version

1.19.41

**Comment by Camotoy** [comment]
I don't think this would work anyway because of the way Bedrock works, but we can at least silence the error. Can you post a video of how to reproduce this?

**Comment by onebeastchris** [comment]
Closing due to no response - to reopen this issue, please provide the info Camotoy asked for.
