### ISSUE TITLE
Geyser Bedrock sends people back to another location when rejoining 

### ISSUE THREAD

**Issue by username100099** [GeyserMC/Geyser#3398]
### Describe the bug

When joining on Bedrock edition it sends people back to a previous location that they were in. There's also other stuff where when players join they cant move, interact or do anything until I teleport them to themselves (/tp steve steve) then they can continue playing. There isn't any plugins that should be doing this because I only put general purpose plugins like Worldedit or Coreprotect.
Another issue is when a bedrock player starts to move their game crashes. It only works if i tp them to themselves (/tp steve steve).

### To Reproduce

Join a geyser server on Bedrock Edition.

### Expected behaviour

When Bedrock players join they don't get bugged out.

### Server Version and Plugins

 git-Purpur-1775 (MC: 1.19.2)

All plugins:

CommandBlocker, CoreProtect, DiscordSRV, EasyWhitelist*, floodgate, Geyser-Spigot, GeyserHacks, GriefPrevention, Images, LastLoginAPI, LiveKit, One, OnePlayerSleep*, OpenInv, OreAnnouncer, SkinsRestorer, spark, Vault, WorldEdit

### Geyser Dump

https://dump.geysermc.org/95AqDFI4OE3WlshoZW9Kg83a9zltrI2k

### Geyser Version

2.1.0-SNAPSHOT (git-master-b1d832d)

### Minecraft: Bedrock Edition Device/Version

1.19.40 Windows, Android, IOS

**Comment by Camotoy** [comment]
Can you try without any additional plugins? As this sounds like a plugin causing this behavior. In particular, it seems like LastLoginAPI is the culprit.

**Comment by username100099** [comment]
Now that I think of it, it might be that ill check soon. Thanks.

**Comment by username100099** [comment]
*It still didn't work.

**Comment by onebeastchris** [comment]
Does this issue still occur with the latest version of Geyser?

**Comment by onebeastchris** [comment]
Closing due to no response.
