### ISSUE TITLE
Commandes players list

### ISSUE THREAD

**Issue by LightMute** [GeyserMC/Geyser#340]
Hello,

it would be possible to add one or two commands to have the list of players and the number to connect to the geyser? because I use multicraft but it can't get the number to connect on the geyser

/ list gives the number to connect
/ geyser glist gives them connect

**Comment by RednedEpic** [comment]
> Hello,
> 
> it would be possible to add one or two commands to have the list of players and the number to connect to the geyser? because I use multicraft but it can't get the number to connect on the geyser
> 
> / list gives the number to connect
> / geyser glist gives them connect

This issue tracker is not used for questions. If you'd like to suggest a feature, please follow the proper template for that.
