### ISSUE TITLE
Error Failed to translate MovePlayerPacket

### ISSUE THREAD

**Issue by DimaSergeew** [GeyserMC/Geyser#3400]
### Describe the bug

Often I notice that when you log on to my server, many players immediately kicked with this error, why this happens I do not understand. After re-entering the player can log in normally, but sometimes it happens

### To Reproduce

It happens at random and by random players

### Expected behaviour

This was not expected to happen. I tried putting a fixed spawn in the lobby, but it didn't help

### Screenshots / Videos

Velocity: https://mclo.gs/mDHHXFl
Lobby: https://mclo.gs/ZqfSJYn

### Server Version and Plugins

Velocity 3.1.2-SNAPSHOT (git-2d072151-b185)
Plugins: ajqueue, floodgate, geyser, limboapi, limboauth, limbofilter, litebans, luckperms, matrixbungee, minimotd-velocity, plan, skinsrestorer, spark

### Geyser Dump

https://dump.geysermc.org/1EkBGbaYHs0DSOpela6hfXHVvD6OYuvQ

### Geyser Version

On this server Geyser version 2.1.0-SNAPSHOT (git-master-886d7e5) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.40)

### Minecraft: Bedrock Edition Device/Version

-

### Additional Context

-

**Comment by Camotoy** [comment]
There's a placed player skull somewhere in the world causing this issue. Are you able to try to locate the skull in question? If so, try pick-blocking it with a Java player in creative, and run `/paper dumpitem` if you use Paper on the backend server.
Or, my DMs are open if you can send the lobby world file my way. 
Either way, please specify the version of the backend server.

**Comment by DimaSergeew** [comment]
> There's a placed player skull somewhere in the world causing this issue. Are you able to try to locate the skull in question? If so, try pick-blocking it with a Java player in creative, and run `/paper dumpitem` if you use Paper on the backend server.
> Or, my DMs are open if you can send the lobby world file my way.
> Either way, please specify the version of the backend server.

[19:28:47 INFO]: Current: git-Purpur-1842 (MC: 1.19.2)*
Previous: git-Purpur-1839 (MC: 1.19.2)
* You are running the latest version
World file: https://drive.google.com/file/d/1436tt43qKQpM9qvWVvoQMY2ZZnPAIwrW/view?usp=sharing

**Comment by Camotoy** [comment]
I'm not seeing a player head in that world. Perhaps a plugin is adding one somewhere?

**Comment by DimaSergeew** [comment]
I tried the methods above is there any other way to find the problem?

**Comment by DimaSergeew** [comment]
:9

> I'm not seeing a player head in that world. Perhaps a plugin is adding one somewhere?

It would be cool if Geyser could tell me the coordinates where to look for this head

**Comment by mastermc05** [comment]
[here](https://github.com/GeyserMC/Geyser/blob/7171ade0bd2da19fc70e3c36005371c50048ab2a/core/src/main/java/org/geysermc/geyser/entity/type/player/SkullPlayerEntity.java#L113) i changed the code to 
```java
            try {
                SkullSkinManager.requestAndHandleSkin(this, session, (skin -> session.scheduleInEventLoop(() -> {
                    // Delay to minimize split-second "player" pop-in
                    setFlag(EntityFlag.INVISIBLE, false);
                    updateBedrockMetadata();
                }, 250, TimeUnit.MILLISECONDS)));
            } catch (Throwable t) {
                throw new RuntimeException("Skull: "  + skull.getPosition(), t);
            }
```
so the new error was [this](https://hastebin.com/ufixaxilup.csharp), every time it complains about the same coordinates, but in server proprieties we set `max-world-size: 8000`, so no player could go near that location, even every other server don't allow going to that location, so it's too strange
