### ISSUE TITLE
Server resource packs not showing up on bedrock

### ISSUE THREAD

**Issue by NBS-Paste** [GeyserMC/Geyser#3404]
### Describe the bug

When I join my server on bedrock none of the resource packs show up.

### To Reproduce

happens every time I join the server

### Expected behaviour

Resource packs would be applied and would work.

### Server Version and Plugins

Latest versions

### Geyser Version

Latest version

### Minecraft: Bedrock Edition Device/Version

1.19.2

**Comment by Kas-tle** [comment]
Please upload copies of the resource packs you are attempting to use. Also confirm that the packs load in single player.

**Comment by NBS-Paste** [comment]
[Clear+Glass+Pack+1.19.zip](https://github.com/GeyserMC/Geyser/files/10026504/Clear%2BGlass%2BPack%2B1.19.zip)
Yes it works in single player and in multiplayer when on Java.

**Comment by Kas-tle** [comment]
Well then there's the issue. Geyser doesn't convert packs to bedrock. You'll have to format your pack for bedrock if you'd like it to work.

**Comment by onebeastchris** [comment]
In order for the resource pack on bedrock to show up/work, you need to convert the pack to bedrock, and upload the .mcpack or .zip -ed bedrock pack to geyser's packs folder.

**Comment by NBS-Paste** [comment]
How would I convert the texture pack? And how would I get them on Xbox for my friends?

**Comment by Camotoy** [comment]
I'm closing since this isn't a bug.

**Comment by onebeastchris** [comment]
from the helpful geyser discord bot:
To add a Bedrock resource pack to your server, take a .zip or .mcpack file and put it in Geyser's packs folder. The resource pack needs to be a Bedrock resource pack, and if you only have it in Java format, you can convert it.

one converter is https://rtm516.github.io/ConvertJavaTextureToBedrock/ - but it's only for pre 1.17 java packs. For newer packs, the https://github.com/Kas-tle/java2bedrock.sh converter works. It is manual though.

**Comment by Kas-tle** [comment]
That's not exactly accurate. Fundamentally those converters do different things. Mine only does custom model data and damages based items, including 3D models. Rtm's only does vanilla items and does not do 3D models.

**Comment by onebeastchris** [comment]
wait, i thought yours could also be used to convert "simple" packs too? i assumed the pack isnt a custom model data pack/doesnt feature damage based items
but yes, i shouldve been more specific, sorry

**Comment by Kas-tle** [comment]
Nope. Does absolutely nothing if there's no custom model data or damage predicate.

**Comment by onebeastchris** [comment]
Oh shoot. Welllll.. yikes, i thought that one was an additional feature of sorts
so.. i guess there really isn't an up to date normal pack converter then
