### ISSUE TITLE
cmi compatibility issues

### ISSUE THREAD

**Issue by wykwey** [GeyserMC/Geyser#3405]
### Describe the bug

Problem 1 I use the /sell gui of the cmi plugin and it doesn't place items [win10 does, PE does not]
 Problem 2. When I open the Composition menu in survival mode, it doesn't seem to fill the 4 bars
The third problem is the inability to use the cmi's flight power

### To Reproduce

The first problem is installing the cmi, geyser. , using the pe platform, using the directive /sell gui You can see that you can't place it

### Expected behaviour

”want the composited menu all to be placed I hope to solve the problem of cmi

### Screenshots / Videos

![Screenshot_2022-11-17-08-00-41-908_com miui gallery](https://user-images.githubusercontent.com/73051894/202323041-ff60f27c-b598-4b2f-b5db-38b98a85c8f9.jpg)

https://user-images.githubusercontent.com/73051894/202323059-734654fe-f565-450b-bc0f-69dad1e19671.mp4

### Server Version and Plugins

mc 1.17.1
geyser 2.1.0-snapshot   （git-master-7d84928）

### Geyser Dump

https://dump.geysermc.org/NVbb1YEjthcUcGypQiqNwvTGixAWcAOF

### Geyser Version

geyser 2.1.0-snapshot   （git-master-7d84928）

**Comment by Jens-Co** [comment]
I will close this issue due to CMI being a payed resource and are unable to replace it due to it.

**Comment by Camotoy** [comment]
To be clear, if these issues can be replicated by our developers, these sound like a valid issues that would be fixed.
