### ISSUE TITLE
All player_head mapping is not work and will cause player boom his bedrock client

### ISSUE THREAD

**Issue by srlss123** [GeyserMC/Geyser#3412]
### Describe the bug

1. All player_head will change Purple glass plate
2. Player put this head will boom his client

### To Reproduce

1. Use 
[SlimefunItems.txt](https://github.com/GeyserMC/Geyser/files/10049136/SlimefunItems.txt)
mapping player_head
2. join game
3. All player_head will change Purple glass plate
4. Player put this head will boom his client

### Expected behaviour

Normal display and does not crash

### Screenshots / Videos

![QQ截图20221120161005](https://user-images.githubusercontent.com/78008410/202892191-8af57eb4-abac-46ed-888a-c5142ab90c4d.png)

### Server Version and Plugins

SERVER VERSION : 1.19.2

### Geyser Dump

https://dump.geysermc.org/JQLtO8L0BGmDWvhQpmWD39c3qha19pHB

### Geyser Version

2.1.0-SNAPSHOT (git-master-7171ade)

### Minecraft: Bedrock Edition Device/Version

1.19.40 Android

**Comment by Camotoy** [comment]
As per https://github.com/GeyserMC/Geyser/issues/3397, this is currently intended behavior unless you changed something in the mappings order.
