### ISSUE TITLE
Use new spectator gamemode

### ISSUE THREAD

**Issue by MIOGMIOG** [GeyserMC/Geyser#3413]
### What feature do you want to see added?

Geyser should use newly added Spectator mode. (It was added in 1.19.10)
It is less buggy and actually looks like spectator mode.

### Are there any alternatives?

I didn't find any alternatives.

**Comment by MIOGMIOG** [comment]
Still not fixed

**Comment by onebeastchris** [comment]
And it won't be fixed magically; we'd have to implement it properly.
I've tried playing around with it - while it's easy to just use the spectator mode, it is still far more limited than on Java. E.g.:
- spectating players/entities isn't a thing
- hotbar to e.g. tp to other players isn't visible
- flying speed adjustments are also lacking

So while it is possible to just switch to the bedrock spectator gamemode, not all java features would be present.
