### ISSUE TITLE
Bedrock Players having issues above nether roof

### ISSUE THREAD

**Issue by NBS-Paste** [GeyserMC/Geyser#3414]
### Describe the bug

When my friend(bedrock edition) places blocks above the nether roof it doesn't appear for him but it does for me.

### To Reproduce

place block on nether roof

### Expected behaviour

bedrock players be able to see blocks above the nether roof

### Server Version and Plugins

2.1.0

### Geyser Dump

https://dump.geysermc.org/jhkMxh2jfXigTbAxRyaSwXsiU9U0jUTe

### Geyser Version

2.1.0

### Minecraft: Bedrock Edition Device/Version

latest version pc

**Comment by Camotoy** [comment]
Enable the above Bedrock Nether workaround in the Geyser config.
