### ISSUE TITLE
1.19.50 and Geyser Crashing Bug

### ISSUE THREAD

**Issue by nicholasveronico** [GeyserMC/Geyser#3421]
### Describe the bug

Since updating the proxy to Geyser Bungeecord #1240 (from #1236) and updating the client to 1.19.50, I am unable to connect to a sub-server on the network without crashing or being stuck on "Building terrain."

### To Reproduce

1. Update server and client to the latest versions.
2. Join a server with multiple sub-servers.
3. Join one of the sub-servers after logging into the fallback server.

### Expected behaviour

Expected behaviour: logging in without issues.

### Screenshots / Videos

https://imgur.com/a/TneutzG

(Please note that I have tried this with two separate Microsoft accounts and have tried it on Windows 10 and IOS)

### Server Version and Plugins

The hub server is running ImanitySpigot 2022.11.1 LTS BUILD 2
The survival server is running git-Purpur-1854 (MC: 1.19.2)
The proxy is running git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:a24c106:158

### Geyser Dump

https://dump.geysermc.org/NX272ICwvwPoHcneV0ybKMkCQnJHwx3v

### Geyser Version

2.1.0-SNAPSHOT (git-master-49d3254)

### Minecraft: Bedrock Edition Device/Version

1.19.50 (Windows 10 and IOS)

**Comment by ofunny** [comment]
Can confirm same issue with Geyser-Velocity using the latest Velocity build 185 https://papermc.io/downloads#Velocity after upgrading to 1.19.50.

Clients crash while switching servers within the proxy, while the first join to the a given server works.

**Comment by HippieBeak** [comment]
Can also confirm on Geyser Standalone.

**Comment by SuprexDE** [comment]
+1

**Comment by Jens-Co** [comment]
We are aware there is a bug on switching servers/dimension. Please be patient while we are working things out. 
This issue will be closed once the fix is implemented.

**Comment by Despiro** [comment]
So i did a little extra testing on my own to see what triggers this issue for myself on my server and it seems that entering through vanilla portals like end and nether portals to said dimension works fine and tping out of said dimensions and entering em vis tp is fine as well but when doing /spawn /warp or /tp to custom dimensions (multiverse plugin on my server) it causes the bedrock player to crash but then upon reconnect they are at the location they sent the teleport to hope this helps in solving this bug

**Comment by Konicai** [comment]
Thank you

**Comment by jefflima1** [comment]
Same problem happens to me, when entering multiverse worlds for example, the player crashes and when he connects he returns to the world he tried to go.

**Comment by DaddyRobLIVE** [comment]
Can confirm on geyser-spigot
