### ISSUE TITLE
Incompatibility with Plan (Fabric)

### ISSUE THREAD

**Issue by uSniipez** [GeyserMC/Geyser#3423]
### Describe the bug

My server is unable to start when I have geyser and Plan | Player Analytics installed on the server.

Console log:
https://paste.dedimc.io/wibunexegu

### To Reproduce

1. Install geyser and plan
2. start server

### Expected behaviour

The server successfully starts with the geyser and plan both working.

### Server Version and Plugins

Version:
Minecraft 1.19.2 with Fabric Loader 0.14.10

Loaded Mods:
        - adventure-platform-fabric 5.4.0-SNAPSHOT via floodgate
        - antixray 1.2.6
        - architectury 6.3.49
        - audioplayer 1.19.2-1.4.5
        - c2me 0.2.0+alpha.9.0
        - c2me-base 0.2.0+alpha.9.0 via c2me
        - c2me-fixes-chunkio-threading-issues 0.2.0+alpha.9.0 via c2me
        - c2me-fixes-general-threading-issues 0.2.0+alpha.9.0 via c2me
        - c2me-fixes-worldgen-threading-issues 0.2.0+alpha.9.0 via c2me
        - c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.9.0 via c2me
        - c2me-notickvd 0.2.0+alpha.9.0 via c2me
        - c2me-opts-allocs 0.2.0+alpha.9.0 via c2me
        - c2me-opts-chunk-access 0.2.0+alpha.9.0 via c2me
        - c2me-opts-chunkio 0.2.0+alpha.9.0 via c2me
        - c2me-opts-math 0.2.0+alpha.9.0 via c2me
        - c2me-opts-scheduling 0.2.0+alpha.9.0 via c2me
        - c2me-opts-worldgen-general 0.2.0+alpha.9.0 via c2me
        - c2me-opts-worldgen-vanilla 0.2.0+alpha.9.0 via c2me
        - c2me-rewrites-chunkio 0.2.0+alpha.9.0 via c2me
        - c2me-server-utils 0.2.0+alpha.9.0 via c2me
        - c2me-threading-chunkio 0.2.0+alpha.9.0 via c2me
        - c2me-threading-lighting 0.2.0+alpha.9.0 via c2me
        - c2me-threading-scheduling 0.2.0+alpha.9.0 via c2me
        - c2me-threading-worldgen 0.2.0+alpha.9.0 via c2me
        - carpet 1.4.84
        - carpet-extra 1.4.84
        - carpet-fixes 1.19-1.12.2
        - chunky 1.3.38
        - cloth-basic-math 0.6.1 via cloth-config
        - cloth-config 8.2.88
        - cloud 1.7.0-SNAPSHOT via floodgate
        - cloud_commandframework_cloud-brigadier_ 1.7.0-SNAPSHOT via cloud
        - cloud_commandframework_cloud-core_ 1.7.0-SNAPSHOT via cloud
        - cloud_commandframework_cloud-services_ 1.7.0-SNAPSHOT via cloud
        - clumps 9.0.0+11
        - com_electronwill_night-config_core 3.6.6 via servercore
        - com_electronwill_night-config_toml 3.6.6 via servercore
        - com_github_llamalad7_mixinextras 0.1.0 via servercore
        - com_ibm_async_asyncutil 0.1.0 via c2me
        - com_moandjiezana_toml_toml4j 0.7.2 via antixray
        - com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
        - conditional-mixin 0.3.1 via carpet-fixes
        - dynmap 3.4
        - fabric-api 0.66.0+1.19.2
        - fabric-api-base 0.4.12+93d8cb8290 via fabric-api
        - fabric-api-lookup-api-v1 1.6.10+93d8cb8290 via fabric-api
        - fabric-biome-api-v1 9.0.18+c6af733c90 via fabric-api
        - fabric-block-api-v1 1.0.0+12bfe4ea90 via fabric-api
        - fabric-command-api-v1 1.2.12+f71b366f90 via fabric-api
        - fabric-command-api-v2 2.1.8+93d8cb8290 via fabric-api
        - fabric-commands-v0 0.2.29+df3654b390 via fabric-api
        - fabric-containers-v0 0.1.35+df3654b390 via fabric-api
        - fabric-content-registries-v0 3.4.1+6064db2a90 via fabric-api
        - fabric-convention-tags-v1 1.1.2+93d8cb8290 via fabric-api
        - fabric-crash-report-info-v1 0.2.6+aeb40ebe90 via fabric-api
        - fabric-data-generation-api-v1 5.2.3+b598f4ac90 via fabric-api
        - fabric-dimensions-v1 2.1.32+0dd10df690 via fabric-api
        - fabric-entity-events-v1 1.5.0+a1d87cb890 via fabric-api
        - fabric-events-interaction-v0 0.4.29+c6af733c90 via fabric-api
        - fabric-events-lifecycle-v0 0.2.29+df3654b390 via fabric-api
        - fabric-game-rule-api-v1 1.0.22+c6af733c90 via fabric-api
        - fabric-item-api-v1 1.5.8+93d8cb8290 via fabric-api
        - fabric-item-groups-v0 0.3.33+70efcffe90 via fabric-api
        - fabric-language-kotlin 1.8.6+kotlin.1.7.21
        - fabric-lifecycle-events-v1 2.2.0+33ffe9ec90 via fabric-api
        - fabric-loot-api-v2 1.1.7+83a8659290 via fabric-api
        - fabric-loot-tables-v1 1.1.10+9e7660c690 via fabric-api
        - fabric-message-api-v1 5.0.4+93d8cb8290 via fabric-api
        - fabric-mining-level-api-v1 2.1.18+33fbc73890 via fabric-api
        - fabric-networking-api-v1 1.2.5+c6af733c90 via fabric-api
        - fabric-networking-v0 0.3.22+df3654b390 via fabric-api
        - fabric-object-builder-api-v1 4.1.0+06e0e25190 via fabric-api
        - fabric-particles-v1 1.0.11+79adfe0a90 via fabric-api
        - fabric-permissions-api-v0 0.2-SNAPSHOT
        - fabric-registry-sync-v0 0.9.26+c6af733c90 via fabric-api
        - fabric-rendering-data-attachment-v1 0.3.16+12bfe4ea90 via fabric-api
        - fabric-rendering-fluids-v1 3.0.8+c6af733c90 via fabric-api
        - fabric-resource-conditions-api-v1 2.1.0+aae9039d90 via fabric-api
        - fabric-resource-loader-v0 0.7.3+3e1ba48e90 via fabric-api
        - fabric-screen-handler-api-v1 1.3.1+1cc24b1b90 via fabric-api
        - fabric-transfer-api-v1 2.1.1+93d8cb8290 via fabric-api
        - fabric-transitive-access-wideners-v1 1.3.1+42d99c3290 via fabric-api
        - fabricloader 0.14.10
        - fastbench 1.18.1-3
        - fastfurnace 1.19.2-5
        - ferritecore 4.2.1
        - floodgate 2.2.0-SNAPSHOT
        - geyser-fabric 2.1.0-SNAPSHOT
        - golfiv 0.6.0
        - image2map 0.3.0
        - improvedmobs 1.19-1.10.16
        - invview 1.4.9-1.19+
        - io_leangen_geantyref_geantyref 1.3.13 via cloud
        - java 17
        - krypton 0.2.1
        - lazydfu 0.1.3
        - ledger 1.2.5
        - lithium 0.10.1
        - luckperms 5.4.54
        - map-canvas-api 0.2.0+1.19.1 via image2map
        - me_lucko_spark-api 0.1-SNAPSHOT via servercore
        - minecraft 1.19.2
        - net_kyori_adventure-api 4.11.0 via adventure-platform-fabric
        - net_kyori_adventure-key 4.11.0 via adventure-platform-fabric
        - net_kyori_adventure-platform-api 4.1.0 via adventure-platform-fabric
        - net_kyori_adventure-text-logger-slf4j 4.11.0 via adventure-platform-fabric
        - net_kyori_adventure-text-minimessage 4.11.0 via adventure-platform-fabric
        - net_kyori_adventure-text-serializer-gson 4.11.0 via adventure-platform-fabric
        - net_kyori_adventure-text-serializer-plain 4.11.0 via adventure-platform-fabric
        - net_kyori_examination-api 1.3.0 via adventure-platform-fabric
        - net_kyori_examination-string 1.3.0 via adventure-platform-fabric
        - net_objecthunter_exp4j 0.4.8 via c2me
        - observable 3.3.0
        - org_jetbrains_kotlin_kotlin-reflect 1.7.21 via fabric-language-kotlin
        - org_jetbrains_kotlin_kotlin-stdlib 1.7.21 via fabric-language-kotlin
        - org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.21 via fabric-language-kotlin
        - org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.21 via fabric-language-kotlin
        - org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
        - org_threadly_threadly 7.0 via c2me
        - packet_tweaker 0.3.0+1.18.2 via server_translations_api
        - placeholder-api 2.0.0-pre.1+1.19.2 via servercore
        - plan 5.5 build 2076
        - server_translations_api 1.4.14+1.19-rc2 via ledger
        - servercore 1.3.3-1.19.2
        - sgui 1.1.5+1.19.1 via image2map
        - spark 1.9.45
        - starlight 1.1.1+fabric.ae22326
        - tenshilib 1.19-1.6.10
        - vmp 0.2.0+beta.7.11
        - voicechat 1.19.2-2.3.13
        - worldedit 7.2.12+6240-87f4ae1

### Geyser Version

geyser-fabric 2.1.0-SNAPSHOT

**Comment by JosTheDude** [comment]
This appears to be a PLAN issue, not one with Geyser

As PLAN has full support for Geyser on other versions

**Comment by uSniipez** [comment]
> This appears to be a PLAN issue, not one with Geyser
> 
> As PLAN has full support for Geyser on other versions

I have tried to use multiple versions of PLAN to see if older versions would work and I encountered the same error every time.
Additionally, I have already brought this to the attention of the PLAN developer and they seem to think it is an issue with geyser/fabric and they don't know how to go about fixing it. - https://github.com/GeyserMC/Floodgate-Fabric/issues/71

**Comment by AuroraLS3** [comment]
The injection that fails is
`@Inject(method = "changeGameMode", at = @At(value = "INVOKE", target = "Lnet/minecraft/server/network/ServerPlayNetworkHandler;sendPacket(Lnet/minecraft/network/Packet;)V"))`
