### ISSUE TITLE
Extreme lighting issues on Bedrock edition 

### ISSUE THREAD

**Issue by CrystalVortex** [GeyserMC/Geyser#3425]
### Describe the bug

In builds where there is light  and darkness the lighting breaks.

### To Reproduce

1 : Join a Geyser server
2 : Go to a building that has both lit up and dark parts and see that it looks chunky and broken (bedrock)
3 : See the difference on java

### Expected behaviour

The lighting should not break on bedrock.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/99749845/204733055-f34688e2-32e9-4fc0-b5a3-b5a65de64770.png)

^ Java edition

![image](https://user-images.githubusercontent.com/99749845/204733199-31bdbdaa-0262-4ef3-ab2c-cd14ba3fb62b.png)

^ Bedrock edition
It has been much worse than these screenshots. 
### Server Version and Plugins

git-Purpur-1775 (MC: 1.19.2)
ChestShop, CommandBlocker, CoreProtect, DiscordSRV, EasyWhitelist*, Essentials, floodgate, Geyser-Spigot, GeyserHacks, GriefPrevention, LiveKit, LuckPerms, One, OnePlayerSleep*, OpenInv, ProtocolLib, SkinsRestorer, Vault, WorldEdit, WorldGuard, YamipaPlugin

### Geyser Dump

https://dump.geysermc.org/a0N963clxm6B73NblPh8iuPKK3CIf4cS

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-c6e417a) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.20 - 1.19.50)

### Minecraft: Bedrock Edition Device/Version

Windows, ios, android ( all the same and tested ) version 1.19.40, 1.19.50

**Comment by Camotoy** [comment]
We may not be able to do much about this... as it stands, Bedrock's lighting system is mostly clientside.

**Comment by CrystalVortex** [comment]
Oh ok. Is there maybe something that could help with it or make it a little better?

**Comment by valaphee** [comment]
Technically we can sent lighting data, but this would come with the cost of higher cpu usage and more caching

**Comment by CrystalVortex** [comment]
Oh. I don't really mind higher cpu usage.

**Comment by TerdyTheTerd** [comment]
If this is implemented, it should be done so as an optional feature. Some servers are small and have spare resources, some are large and can't spare resources to correct bedrock lighting issues.

I for one would appreciate an option for this, given most of the time my small server runs just fine between 20-30mspt, and if I can I would rather utilize my spare resources to give players a better experience.
