### ISSUE TITLE
Standalone Crashing

### ISSUE THREAD

**Issue by PyroFT** [GeyserMC/Geyser#3428]
### Describe the bug

The whole geyser network dropped with the latest update that I just did.  Also, everyone someone switches servers it gives this error below. 

[23:32:43 ERROR] Haven't received PlayerListEntry packet before spawning player! We ignore the player cd436160-5e35-4699-96b0-a2474844fe83

Crash error: https://pastebin.com/B0NPiSvk

### To Reproduce

loaded standalone geyser
players joined
a few minutes later everyone from geyser dropped.

### Expected behaviour

.

### Server Version and Plugins

Purpur-1824 (mc: 1.19.2)

### Geyser Dump

https://dump.geysermc.org/KcZjC5TqqhftoW7Ml6vtCTdefgrsk6Ew

### Geyser Version

Loading Geyser version 2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.50 all

**Comment by PyroFT** [comment]
another error:

https://pastebin.com/P68nnKTe

**Comment by PyroFT** [comment]
more logs and info

https://mclo.gs/zo0JVuw
https://mclo.gs/ZHytmML

**Comment by Camotoy** [comment]
In Discord, this user implied it was TCPShield's fault. Therefore I'll close; do update if this is incorrect.
