### ISSUE TITLE
test.geysermc.org server is out of date

### ISSUE THREAD

**Issue by master-hax** [GeyserMC/Geyser#3429]
### Describe the bug

the test server at test.geysermc.org seems to be out of date - trying to join the test server from minecraft bedrock v1.19.50 fails with an error message.

### To Reproduce

1. open minecraft bedrock v1.19.50
2. try to join test.geysermc.org:19132

### Expected behaviour

I expected to be able to join the test server since this repository's readme says:
>Currently supporting Minecraft Bedrock 1.19.20 - 1.19.50 and Minecraft Java 1.19.1/1.19.2.

but I get an error message instead saying that the geyser proxy is outdated.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/17506434/205247500-afbdcfad-84c6-434d-a7c0-2787151359d0.png)

### Geyser Version

idk

### Minecraft: Bedrock Edition Device/Version

v1.19.50

**Comment by Camotoy** [comment]
Fixed.
