### ISSUE TITLE
Bedrock Players don't reveive packets after few seconds

### ISSUE THREAD

**Issue by HEROOSTECH** [GeyserMC/Geyser#3431]
### Describe the bug

When you join to server with bedrock 1.19.50 after few seconds you won't receive packets.

### To Reproduce

Just run geyser on velocity and play few seconds.

### Expected behaviour

Receiving packets by bedrock clients.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1036566252317048883/1048680886536786031/2022-12-03_20-16-42.mp4

### Server Version and Plugins

mysqlandconfigurateforvelocity, partyandfriends, cancelfriendrequest, floodgate, geyser, ia-for-paf, log-tool-for-paf, luckperms, max-friends, namelessmc, party-proxy-bridge-for-paf, party-toggle-loader, prefixesperms-for-paf, teleport-to-friend-paf-extension, viaversion, viabackwards, party-toggle-for-party-and-friends

### Geyser Dump

https://dump.geysermc.org/27OSvKBOt0gIeazrCUWLR3F54T4mTEc0

### Geyser Version

2.1.0-SNAPSHOT (git-master-02208a5)

### Minecraft: Bedrock Edition Device/Version

Windows 11

### Additional Context

When backend server is closed, bedrock client is still on server.

**Comment by Konicai** [comment]
Can you try the workaround listed in #2861 please

**Comment by HEROOSTECH** [comment]
> Can you try the workaround listed in #2861 please

works now correctly, thanks!
