### ISSUE TITLE
Bedrock Visibility Issue - Nether

### ISSUE THREAD

**Issue by RobellaMC** [GeyserMC/Geyser#3433]
### Describe the bug

Bedrock players are unable to see bedrock in the nether, and they are unable to go to the nether roof since the latest update. They also will glitch and become stuck in they get anywhere near it. 

### To Reproduce

1. Install Geyser Build #1244
2. Go to the nether on Bedrock edition

### Expected behaviour

Bedrock players used to be able to go to the nether roof no problem, and see bedrock with no issue. 

### Server Version and Plugins

Server Version: git-Purpur-1714 (MC: 1.19)
Plugins:
![plugins](https://user-images.githubusercontent.com/78275916/205464717-da403bcf-3d4d-43c2-91b5-f90863d9d8b5.png)

### Geyser Dump

https://dump.geysermc.org/2Tf00g9ucvkPZb88IzRf53Jjb5P8ntin

### Geyser Version

2.1.0-SNAPSHOT

**Comment by Camotoy** [comment]
Enable `above-bedrock-nether-building` in your Geyser config and restart.
