### ISSUE TITLE
Could not find packet for ClientboundSetDisplayChatPreviewPacket 

### ISSUE THREAD

**Issue by vanilovv** [GeyserMC/Geyser#3436]
### Describe the bug

Can't find two packages when joining the server
10:10:06 [INFO] [Geyser-BungeeCord] Could not find packet for ClientboundRecipePacket
10:10:06 [INFO] [Geyser-BungeeCord] Could not find packet for ClientboundSetDisplayChatPreviewPacket

### To Reproduce

1. Go to Server

### Expected behaviour

Authorizes to the server

### Server Version and Plugins

This server is running CraftBukkit version git-Spigot-eb3d921-b9f1615 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) (paper)
Plugins (33): BlockedCmds, WorldEdit, EasyPayments, PlaceholderAPI, SimpleFlyPlugin, NametagEdit, MessageAnnouncer, WorldGuard, VoidSpawn, AdvancedPortals, UltraBar, LiteJoin, CommandSync, ViaVersion, Visibility, LuckPerms, LastLoginAPI, ServerSelectorX, ProtocolLib, NoCheatPlus, SkinsRestorer, Vault, CommandBlocker, GadgetsMenu, HolographicDisplays, CommandPanels, HubParkour, ChatFormat, Citizens, TAB, ItemJoin, CommandNPC, EazyNick

### Geyser Dump

https://dump.geysermc.org/hU7UFcGb8qEzRP4RGg6iwbPLCK3EMPag

### Geyser Version

2.1.0-SNAPSHOT (git-master-3d66d27)

### Minecraft: Bedrock Edition Device/Version

1.19.20

**Comment by Camotoy** [comment]
These are debug messages and are expected as we don't handle these packets. You can disable `debug-mode` in the Geyser config to remove them.
