### ISSUE TITLE
Crafting Tables Crashing Client

### ISSUE THREAD

**Issue by ARR4NN** [GeyserMC/Geyser#3438]
### Describe the bug

When on bedrock and opening a crafting table the animation begins and then the game crashes and is un recoverable without killing game.

### To Reproduce

Place Crafting Table
Open Crafting Table

### Expected behaviour

The table to open normally

### Screenshots / Videos

https://user-images.githubusercontent.com/70060472/206307446-8fb6f46a-9e40-4768-b8ec-31cc0d40a263.mp4

### Server Version and Plugins

https://ci.opencollab.dev//job/GeyserMC/job/Geyser/job/master/ geyser-bungeecord latest

Plugins (25): BungeeGuard, CustomRecipeAPI, DecentHolograms, DeepStoragePlus, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), floodgate, GeyserSkinManager, HealthBar, ImageOnMap, LongerDays*, LuckPerms, MultiChat*, Multiverse-Core, ProtocolLib, PublicCrafters, sleep-most, SmoothTimber, spark, Vault, ViaBackwards, ViaVersion, WorldGuard

### Geyser Dump

https://dump.geysermc.org/kjZEnLVflMrTUFo3JyMlzBaROQz4FKqh

### Geyser Version

2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.3

**Comment by Camotoy** [comment]
There's probably some invalid recipe on the backend server. Do you use any datapacks?

**Comment by ARR4NN** [comment]
Ah will probably be CustomRecipeAPI and deep storage plugin > There's probably some invalid recipe on the backend server. Do you use any datapacks?

**Comment by onebeastchris** [comment]
Is this still an issue with the latest version of Geyser?

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
