### ISSUE TITLE
Geyser kicked out all players and timed out.

### ISSUE THREAD

**Issue by huangpianmao** [GeyserMC/Geyser#3444]
### Describe the bug

When a player tries to access the server, there is a probability that all players in the bedrock version will time out and disconnect, and then the geyser will stop working for about 30 seconds.

### To Reproduce

1.Let geysers work properly.
2.When a random player tries to connect, the geyser fails.

### Expected behaviour

If you join or rejoin, they will time out and be kicked out of the server.

### Server Version and Plugins

该服务器正在运行 Geyser 版本 2.1.0-SNAPSHOT (git-master-f505f13) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.40)

### Geyser Dump

https://dump.geysermc.org/j74srpWqLJIYDtFB9l7GYWZAWjwZyl72

### Geyser Version

2.1.0-SNAPSHOT (git-master-f505f13)

### Minecraft: Bedrock Edition Device/Version

1.18.10 and the latest version/all bedrock devices

### Additional Context

This problem has been bothering me for about two months,I always thought that there was something wrong with my configuration, or the update might fix it.From 1.17 until the latest version 1.19 a few days ago,I've tried everything, but I can't fix this bug.Both Geyser-Standalone and Geyser-Spigot have tried.（In addition, I'm sorry to use Google Translate to communicate.）

**Comment by onebeastchris** [comment]
Please see the steps in the issue here #2861 for how to fix this issue - thanks for reporting anyway!
