### ISSUE TITLE
Tried to log in as a Java Edition player

### ISSUE THREAD

**Issue by LittleChest** [GeyserMC/Geyser#3445]
### Describe the bug

I have Geyser and Floodgate deployed on my online BungeeCord server (requires players to have paid Java Edition) but when Bedrock Edition players try to connect it says they are connecting as Java Edition and the console outputs Lots of errors.

### To Reproduce

Start a waterfall server.
Start any minecraft server.
Make sure they have online mode enabled.
To install geyser and gate, change the authentication method to gate in geyser's config file.
Enable sending gate data in the gate configuration file, copy the key file from the waterfall server to the minecraft server.
Restart all servers, and use Bedrock Edition to log in to the server.

### Expected behaviour

Bedrock Edition enters the server normally.

### Server Version and Plugins

purpur-1838 (MC:1.19.2)

### Geyser Dump

https://dump.geysermc.org/RcXbhyQVMsIcjS6BwQ4xtrP9MjBEihwZ

### Geyser Version

2.1.0-SNAPSHOT (git-master-247edc6)

### Minecraft: Bedrock Edition Device/Version

1.19.50 Android & Windows 10 PC

### Additional Context

Minecraft log: https://mclo.gs/lmLSeyc

**Comment by Camotoy** [comment]
Please do not create multiple issues in the future (https://github.com/GeyserMC/Floodgate/issues/371). Thanks.

**Comment by LittleChest** [comment]
ok sorry about that
