### ISSUE TITLE
Bedrock Users Connection Issue

### ISSUE THREAD

**Issue by RobellaMC** [GeyserMC/Geyser#3446]
### Describe the bug

Bedrock users are able to connect to my server once, and then never again. They're throwing an error every time they do join. If they are able to connect, they are unable to go to the End, Nether, or other worlds besides the one they log in to, or it disconnects them and they are unable to reconnect. Prior to the 1.19.3 update I have had minimal issues with Geyser, and no connection issues at all. Outside of updating Geyser & Via Version, nothing else on our server has changed. I've reached out to my server host, we've uninstalled and reinstalled Geyser, but nothing seems to be helping the issue. 

We also made a mirror server, but were unable to replicate the issue. 

On the first installation of this version of Geyser, they were throwing a ditconnect.genericReason error, but now it's something different (attached below). My server host requested I reach out to the developer because there's nothing else they can do on their end to troubleshoot. 

### To Reproduce

1. Download most up to date version of Geyser. 

### Expected behaviour

Bedrock players are able to connect, stay connected, and reconnect after disconnect. 

### Screenshots / Videos

![IMG_3066](https://user-images.githubusercontent.com/78275916/206775763-71a8ba81-e8c5-45f2-9b14-10c16a07c95e.png)

### Server Version and Plugins

Version: git-Purpur-1714 (MC: 1.19)
Plugins: ![image](https://user-images.githubusercontent.com/78275916/206776351-a646f5ca-495a-4b89-a798-231d7a6875d7.png)

### Geyser Dump

https://dump.geysermc.org/eOeFw2DjHKb4bDFqJi9sWEVJZIAynVcR

### Geyser Version

2.1.0-Snapshot (git-master-02208a5)

### Minecraft: Bedrock Edition Device/Version

All versions, all devices

**Comment by Camotoy** [comment]
Can you please send a full set of logs from startup, and including when a player connects and disconnects?

**Comment by Kas-tle** [comment]
Please update Geyser. There have been many changes since the version you are using to address 1.19.3 specific bugs.

**Comment by RobellaMC** [comment]
Not completed, not sure what happened.

**Comment by RobellaMC** [comment]
Any update on this issue? I am keeping up with Geyser updates and players are still getting ditconnect.genericReason issues. No one has been able to stay on for the past week.

**Comment by Camotoy** [comment]
Please try this development build: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/dev/2/

**Comment by Seriaserena** [comment]
I have geyser, floodgate, viaversion and viabackwards installed but my users are still having trouble logging in. I have the link that gives me the command "Geyser dump": https://dump.geysermc.org/EyKxFCduJkRzDX10HSaqIHkCN6EB65cY
[17:19:34 INFO]: [Geyser-Spigot] Seriaserena has disconnected from the Java server because of §r§f¡Sólo para jugadores registrados! Por favor visita http://www.example.com/ para registrarte or too the issue: Please play on 1.19 version! (my server version is 1.19.2)

**Comment by amalon** [comment]
> Please try this development build: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/dev/2/

A bedrock user on my server was reporting being unable to connect, with the ditconnect.genericReason message in the logs. Switching from master branch build 1258 to dev branch build 3 seems to fix it (thanks!).

**Comment by onebeastchris** [comment]
pls close

**Comment by Jens-Co** [comment]
Close due to inactivity.
