### ISSUE TITLE
Bamboo's position doesn't match on BE and JE

### ISSUE THREAD

**Issue by denisryba** [GeyserMC/Geyser#345]
**Describe the bug**
Bedrock edition has different positioning of bamboo in comparison with java edition, which leads to collision issues. BE player may stuck in bamboo while passing through it or may be teleported back once he or she passed bamboo.

**To Reproduce**
1. Find bamboo forest or place it by your own
2. Try moving around through it

**Expected behavior**
Collision boxes have to correspond model and texture. Player mustn't be teleported or be able to get stuck.

**Screenshots / Videos**
Bedrock screenshot
![bedrock](https://user-images.githubusercontent.com/43182082/79343749-dc112600-7f3f-11ea-8ac2-53c64ebbcaa9.png)

Java screenshot
![java](https://user-images.githubusercontent.com/43182082/79343829-f9de8b00-7f3f-11ea-8627-d63943a3ffe3.png)

[Video](https://www.youtube.com/watch?v=ZJCeV3EU1Sc)

Server Version
Paper 1.15.2 git-183

Geyser Version
inventory #14

Minecraft: Bedrock Edition Version
1.14.30

**Comment by DoctorMacc** [comment]
There's likely nothing that can be done about this - it appears that bamboo placement is handled completely client-side.
