### ISSUE TITLE
基岩版玩家下界加载错误

### ISSUE THREAD

**Issue by Jerry12228** [GeyserMC/Geyser#3452]
### Describe the bug

基岩版玩家无法加载下界顶部的基岩上层的建筑, 但有空气墙。
java玩家视角：
![image](https://user-images.githubusercontent.com/86408775/207011337-5c128535-5b5f-4ee4-a638-23bae06c9d15.png)
基岩玩家视角：
![image](https://user-images.githubusercontent.com/86408775/207012127-46b76ccd-8ab8-4c8f-bb00-13744017a0b9.png)

### To Reproduce

1.去下界
2.通过任意方式来到基岩上层

### Expected behaviour

使基岩版可以正常显示基岩上部

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/86408775/207011337-5c128535-5b5f-4ee4-a638-23bae06c9d15.png)
![image](https://user-images.githubusercontent.com/86408775/207012127-46b76ccd-8ab8-4c8f-bb00-13744017a0b9.png)

### Server Version and Plugins

Spigot - 1.19.2（3608-Spigot-6198b5a-b5aa0be (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)）
Geyser - 1242

### Geyser Version

2.1.0-SNAPSHOT (git-master-c6e417a)

### Minecraft: Bedrock Edition Device/Version

1.19.41

**Comment by Jerry12228** [comment]
我尝试了1254     2.1.0-SNAPSHOT (git-master-b27b1c8)
出现同样问题

**Comment by valaphee** [comment]
Heya,

this is intentional behavior, because in Bedrock Edition the nether is limitied to 0-127, but there is a setting in the config.yml called "above-bedrock-nether-building" which you can change to true, then the nether will be replaced.

**Comment by Jerry12228** [comment]
> Heya,
> 
> this is intentional behavior, because in Bedrock Edition the nether is limitied to 0-127, but there is a setting in the config.yml called "above-bedrock-nether-building" which you can change to true, then the nether will be replaced, and you can use the full height of the nether.

Thank you.
