### ISSUE TITLE
How do I remove this from my Tab?

### ISSUE THREAD

**Issue by Y0hh** [GeyserMC/Geyser#3465]
### Describe the bug

My TAB gets all buggy, and I have no idea how to get it out. This happens when I put a plugin called "TAB Plugin"

### To Reproduce

There is not.

### Expected behaviour

That nothing happens in my TAB, from the bedrock that just stays normal.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/120335904/208276199-431f2f05-9dd3-40d3-94e5-6986f9e8cdf2.png)

### Server Version and Plugins

Plugins: TAB Plugin, Floodgate, LuckPerms

### Geyser Version

Latest Version

### Minecraft: Bedrock Edition Device/Version

Bedrock

**Comment by Tim203** [comment]
This is actually intended behavior. What you're seeing there is Bedrock's `list` display slot

**Comment by Y0hh** [comment]
O Problema foi resolvido já, do mesmo jeito, muito obrigado pelo atendimento!
