### ISSUE TITLE
Curseforge for geyser-fabric?

### ISSUE THREAD

**Issue by qwertykid** [GeyserMC/Geyser#3466]
### What feature do you want to see added?

Can you upload the geyser fabric releases to Curseforge? The server hosting service I'm using (Aternos) requires it to be on there.
(See [here](https://support.aternos.org/hc/en-us/articles/360052255311-Suggesting-new-mods-plugins-and-modpacks))

### Are there any alternatives?

You are not allowed to upload mods and there is no ftp server.
I'm not sure what else what to do.

**Comment by onebeastchris** [comment]
Geyser-Fabric (and floodgate-fabric) are now available on modrinth - as for aternos + geyser/floodgate-fabric; that's up to them whether to add

As for Curseforge specifically.. no idea if that's now needed

**Comment by Camotoy** [comment]
I think we'll be focusing our efforts on Modrinth and not CurseForge.
