### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Hiho2950** [GeyserMC/Geyser#3467]
I use oraxen on my paper server.
I want to use a resource pack i have convert the java texture to a bedrock resource pack using this (https://github.com/Kas-tle/java2bedrock.sh).

What can i do for enabling the resource pack? because when i use the resource pack on global packs the texture is not it show a vanilla texture

**Comment by Konicai** [comment]
Bedrock resource packs are added to the `packs` folder within the Geyser folder. Please join our Discord server for any further help with resource pack help: https://discord.gg/geysermc

**Comment by Hiho2950** [comment]
> Bedrock resource packs are added to the `packs` folder within the Geyser folder. If you need custom item mappings that is a whole other process that we have resources/info on Discord for. Please join our Discord server for any further help with resource pack help: https://discord.gg/geysermc

Ok thanks
