### ISSUE TITLE
Bug or crash idk

### ISSUE THREAD

**Issue by Hiho2950** [GeyserMC/Geyser#3468]
### Describe the bug

Server crash temporaly for bedrock players only

### To Reproduce

1.run server
2.enter the server from bedrock
3.the server is autoclosing not for all just for geyser players
4.in the console i see (0,0,0,0) multiple times

### Expected behaviour

I use geysermc, floodgate, oraxen, protocolLib and viaversion

### Screenshots / Videos

![Screenshot_20221219-210048_Termux](https://user-images.githubusercontent.com/109638489/208513186-5873a137-f832-4aae-a960-6d46f97f2947.jpg)

### Server Version and Plugins

geysermc
Floodgate
Viaversion
ProtocolLib
Oraxen

### Geyser Version

The lasted

### Minecraft: Bedrock Edition Device/Version

1.19.50, android

### Additional Context

*

**Comment by Konicai** [comment]
Running the command `geyser dump logs` will create a geyser dump of your server information, that also includes your server logs (IP addresses censored). Please run that command and share the link it provides you here

**Comment by Hiho2950** [comment]
> Running the command `geyser dump logs` will create a geyser dump of your server information, that also includes your server logs (IP addresses censored). Please run that command and share the link it provides you here

The server crash when i do it i think the problem is protocolLib plugin

**Comment by Konicai** [comment]
Find another way to share your logs please - we currently don't have anything to work with

**Comment by Pieter0313** [comment]
Similar issue here, but the server just crashes completely for everyone when a bedrock player joins the server. Here is my crash report:
[crash-2022-12-20_14.42.46-server.txt](https://github.com/GeyserMC/Geyser/files/10270344/crash-2022-12-20_14.42.46-server.txt)

My server is running on fabric though, not sure if it's the same issue.

**Comment by Chew** [comment]
That's just a watchdog error for lagging out. We need a full `latest.log`, or use the command like Konicai said.
