### ISSUE TITLE
Geyser not accepting Bedrock users properly

### ISSUE THREAD

**Issue by LimeDev8756** [GeyserMC/Geyser#3469]
### Describe the bug

Bedrock users can not reach the server, this was temporarily fixed when updating Geyser but now no longer works again.

### To Reproduce

1. Attempt to join server
2. Get error "Unable to connect to world."
Side-Note Geyser isn't showing a bedrock player

### Expected behaviour

To join the server

### Server Version and Plugins

Purpur 1.19.3

### Geyser Version

N/A Can't run /geyser version

### Minecraft: Bedrock Edition Device/Version

1.19.51 Windows

### Additional Context

I am making this bug report on behalf of Scandify#3371 and their server.

When attempting any Geyser commands including dump after doing /geyser reload it will not allow the command to execute and throws the error "An internal error has occurred"
Error here : https://pastebin.com/rkp2Xh8R

**Comment by Konicai** [comment]
Please join/ask our Discord server for help with this, as its likely a plugin/server misconfiguration
