### ISSUE TITLE
Soul Soil appears to break sooner on bedrock than on java

### ISSUE THREAD

**Issue by usrErr0r** [GeyserMC/Geyser#3473]
### Describe the bug

This may apply to other blocks too but I have noticed that soul soil takes longer to break than the block breaking animation indicates

(Attempted on empty server with just floodgate, fabric api and Geyser installed)

### To Reproduce

1. Go to the nether
2. Attempt to break soul soil up to the point where it should break on vanilla
3. You have to hold the button for longer than is visually indicated to break soul soil

### Expected behaviour

The animation matches the real break time of the block

### Geyser Dump

https://dump.geysermc.org/xs375dIAz05btnx4LWJx9p1h1RmInGCY

### Geyser Version

Geyser-Fabric.jar Build #1261

### Minecraft: Bedrock Edition Device/Version

1.19.51 on Minecraft for Windows

**Comment by onebeastchris** [comment]
That's an issue with different break speeds for certain blocks on both versions - e.g. java has a longer break speed for endstone bricks, bedrock has a shorter one for e.g. wood etc. Not sure what can be done about this :/

**Comment by onebeastchris** [comment]
Fixed natively in Bedrock 1.20.30 and higher - [source](https://feedback.minecraft.net/hc/en-us/articles/19545277817357-Minecraft-1-20-30-Bedrock-)
Specifically:
> We have adjusted the breaking times of 188 blocks to match Java Edition and our intended design. Some blocks couldn't be changed yet for technical reasons and Obsidian was left unchanged because we're still deciding what breaking speed it should have. Bringing more blocks to parity makes it easier for our team to keep both versions up to date. We also hope it will be easier for the community to make and share guides that work for all players on all platforms.

Soul soil breaking speeds should now be consistent across the platforms.
