### ISSUE TITLE
NPCs Bugs (NO CITIZENS)

### ISSUE THREAD

**Issue by BadSr92** [GeyserMC/Geyser#3479]
### Describe the bug

1: when hiding the name of the npc with /npc name it is hidden but when you enter again it is a bug since the name appears in the normal position if there were no holograms
2: Any npc's in the world that the player encounters appear in the player's list.

### To Reproduce

When creating an npc and hiding its name with /npc name and when re-entering the server the name appears in a buggy way and appears in the list of players

### Expected behaviour

That the npc name is hidden correctly and they don't appear in the player list like in 1.19.2

### Screenshots / Videos

![Screenshot_20221226-015630](https://user-images.githubusercontent.com/121424617/209586608-8b258da9-6833-431b-8735-d145d968b556.jpg)
![Screenshot_20221226-020315](https://user-images.githubusercontent.com/121424617/209586612-6bfc826d-d536-4d62-979a-cbc99eea28b6.jpg)

### Server Version and Plugins

![Screenshot_20221226-163038](https://user-images.githubusercontent.com/121424617/209586600-02ffa514-328e-4abd-bf63-37cb45defc07.jpg)

### Geyser Dump

https://dump.geysermc.org/QGSG5T3FwlqxaEG1RpAFFvVEvGnEwpzC

### Geyser Version

2.1.0 SNAPSHOT (git-master 6485200)

### Minecraft: Bedrock Edition Device/Version

1.19.50 Android

### Additional Context

I reported it to Citizens and they told me it's a Geyser problem since it only happens with bedrock players

I only have Geyser and Floodgate on Proxy Velocity and on PurpurMC servers I have only Floodgate

**Comment by BadSr92** [comment]
3: Also if an npc has a right click command it is not executed or you have to keep it pressed for 3 seconds which I think is left click

**Comment by Camotoy** [comment]
Is this issue now resolved?

**Comment by onebeastchris** [comment]
Closing due to no response.

**Comment by 0372JesusMtz0372** [comment]
3: no fix

**Comment by Jens-Co** [comment]
> 3: no fix

If you have this issue, please make a new bug report and provide us with the asked server details, logs, and replication steps.

do not bump older and closed issues next time, thanks.
