### ISSUE TITLE
Rejoin Issue

### ISSUE THREAD

**Issue by Bbro122** [GeyserMC/Geyser#3481]
### Describe the bug

Whenever a user joins the server for any amount of time and then leaves, they can no longer rejoin the server with the following error: 
`[Thu, 29. Dec 2022 01:41:06 GMT INFO] Heywoahboyz5 (logged in as: Heywoahboyz5) has connected to the Java server
[Thu, 29. Dec 2022 01:41:06 GMT INFO] UUID of player .Heywoahboyz5 is 00000000-0000-0000-0009-01fb26e9bfd2
[Thu, 29. Dec 2022 01:41:06 GMT INFO] Floodgate player logged in as .Heywoahboyz5 joined (UUID: 00000000-0000-0000-0009-01fb26e9bfd2)
[Thu, 29. Dec 2022 01:41:06 GMT INFO] Floodgate player logged in as .Heywoahboyz5 disconnected
[Thu, 29. Dec 2022 01:41:06 GMT INFO] Heywoahboyz5 has disconnected from the Java server because of ditconnect.genericReason
[Thu, 29. Dec 2022 01:41:06 GMT INFO] .Heywoahboyz5 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.reflect.InvocationTargetException`

### To Reproduce

Join, leave, rejoin.

### Expected behaviour

Rejoin should work properly

### Server Version and Plugins

Plugins (48): BetterStructures, BKCommonLib, Brewery, Burn, Carz, ChatManager, Citizens, CleanroomGenerator, ClearLag, CommandAlias, CommandAPI, Corpse, DiscordSRV, dynmap, EliteMobs, Essentials, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), FirePlayer*, floodgate, FlyHook*, Geyser-Spigot, GSit, HeadDB, HigherEnchants, JukeBox, LeashPlayers, LibsDisguises, LightCleaner, LuckPerms, MineableSpawners, ModelEngine, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, NoteBlockAPI, PlaceholderAPI, PlugMan, PremiumVanish, ProtocolLib, QualityArmory, RHForceResourcePack, RocketPlaceholders, Sentinel, Vault, ViaVersion, WorldBorderAPI, WorldGuard

This server is running Pufferfish version git-Pufferfish-10 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: cf5e9ba on HEAD)
You are running 43 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Paper-"e4f5e1c" (MC: 1.19)

### Geyser Dump

https://dump.geysermc.org/rIiuu7yuyX7W1s6gOzoGgDpjxuWOL6ty

### Geyser Version

2.1.0-SNAPSHOT (git-master-6485200)

### Minecraft: Bedrock Edition Device/Version

Mobile

**Comment by Camotoy** [comment]
Can you try this build? https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/dev/lastSuccessfulBuild/

**Comment by darkwolfie37** [comment]
Issue error doesnt occur when using Dev build 3.

**Comment by Camotoy** [comment]
This should now be fixed. Let us know otherwise.
