### ISSUE TITLE
Not able to go to nether without disconnecting and reconnecting

### ISSUE THREAD

**Issue by Meloooche** [GeyserMC/Geyser#3482]
### Describe the bug

Every time I go to the nether on my friends java server it will glitch me into blocks and the only way to fix this issue is for me to disconnect and reconnect every time I want to go to the nether.

### To Reproduce

1. Enter nether portal
2. Stuck in blocks
3. Disconnect and reconnect

### Expected behaviour

To be able to go through the nether portal normally.

### Geyser Version

Latest

### Minecraft: Bedrock Edition Device/Version

1.19.51

**Comment by Darksinga** [comment]
This issue also occurs with me when I die (playing on a Microsoft Switch.)

**Comment by onebeastchris** [comment]
Could you try updating to the latest version of Geyser, and see if the issue persists?
If it does, send a new Geyser dump by running "geyser dump" in your server console.

**Comment by onebeastchris** [comment]
Closing due to no response.
