### ISSUE TITLE
Bedrock Chat Does Not Show Secure/Maybe Not-Secure Messages

### ISSUE THREAD

**Issue by BrandonT80** [GeyserMC/Geyser#3484]
### Describe the bug

Bedrock users cannot see java players who are not considered secure. This has been confirmed by enabling enforce-secure-profiles which makes the bedrock user see all java messages, but cannot send messages themselves.

Edit:
I may have this backwards. My messages have a secure key and in console does not show [Not-Secure] but others who do show [Not-Secure] can be seen by the bedrock clients. Anyone who does not have [Not-Secure] does not show up to the bedrock players.

Example:
Shows Up: [04:37:47 INFO]: [Not Secure] <[Head-Mod] ~HackyHammyKitty> Heyoooo
Does Not Show Up: [04:34:23 INFO]: <[Admin] BrandonT80 > Alr yall

### To Reproduce

1. Use bedrock client
2. Have java players message in chat
3. Observe who you cannot see (usually with DiscordSRV)

### Expected behaviour

See all chat messages

### Server Version and Plugins

Geyser:
2.1.0-SNAPSHOT

Floodgate:
2.2.0-SNAPSHOT (b74-4f36112)

Paper:
This server is running Paper version git-Paper-366 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8d7d927)
You are running the latest version
Previous version: git-Paper-362 (MC: 1.19.3)

### Geyser Dump

https://dump.geysermc.org/J08cHJDvFegJI0AgWMBtYOSZP6sagpS7

### Geyser Version

2.1.0-SNAPSHOT (# 1263)

### Minecraft: Bedrock Edition Device/Version

Mobile (1.19.51), maybe more

**Comment by Camotoy** [comment]
We haven't gotten this bug report before, so I'm inclined to think another plugin is inadvertently causing this issue. Are you able to try removing a chunk of your plugins and seeing if the issue is resolved?

**Comment by BrandonT80** [comment]
I can try this tomorrow for sure

**Comment by BrandonT80** [comment]
> We haven't gotten this bug report before, so I'm inclined to think another plugin is inadvertently causing this issue. Are you able to try removing a chunk of your plugins and seeing if the issue is resolved?

Hello again,

I have spent hours trying to figure out if another plugin is conflicting but to my surprise I found that under identical servers between Pebblehost and Bloomhost, Pebble works fine and Bloom does not...

This makes me think it may have to do with startup flags? All configs and settings are identical, all plugins are identical, server versions and plugin versions identical, etc. Only difference is that on Pebble I do not have access to startup flags, see dump below:

https://dump.geysermc.org/6rz75SyD4kIna44EYglg26vxF7zCAbuK

**Comment by Camotoy** [comment]
Could you try the latest Geyser build and see if your issue is resolved?

**Comment by BrandonT80** [comment]
> Could you try the latest Geyser build and see if your issue is resolved?

It is not resolved using the latest release. [#1269]

**Comment by timr2000** [comment]
I'm having the same issue, also currently hosting at Bloomhost. This issue appears randomly. Yesterday it worked fine and it started to not work again after a few hours. Bedrock players can't read Java players' messages at all. I've got an error on velocity but this might not be the issue we are having https://pastebin.com/DttGSwez

**Comment by Camotoy** [comment]
That seems related, potentially. Can you enable debug mode in Geyser's config, restart, and look for the expanded version of that error?

**Comment by timr2000** [comment]
This spams my console now https://pastebin.com/3ce7zGEv

**Comment by Camotoy** [comment]
That's unrelated.

**Comment by BrandonT80** [comment]
Hello,

I got together with Bloom support and they opened a test server with only geyser and floodgate. Issue persisted on that server too. I am the first to bring this to their attention. We will keep looking at it but here is the dump from that test server.

https://dump.geysermc.org/sPBnAymYkOC52CBuGfnlZgjfZqgSg5hS

**Comment by Camotoy** [comment]
Feel free to have them reach out to me if they need any help debugging. We recently added a `disable-compression` setting in our config which *may* be related, if this setting is `false` then it replicates the old behavior.

**Comment by BrandonT80** [comment]
> 

They said if you join the BloomHost discord we can have you added to the ticket :)
https://discord.com/invite/bloom

**Comment by BrandonT80** [comment]
> Feel free to have them reach out to me if they need any help debugging. We recently added a `disable-compression` setting in our config which _may_ be related, if this setting is `false` then it replicates the old behavior. (These changes were pulled into master after your issue was created)

They said if you join the BloomHost discord we can have you added to the ticket :)
https://discord.com/invite/bloom

**Comment by BrandonT80** [comment]
We also got this error now:

https://cdn.discordapp.com/attachments/1060983387189424168/1060994081280508004/CleanShot_2023-01-06_at_13.50.542x.png

**Comment by Camotoy** [comment]
I've joined the Discord.

**Comment by timr2000** [comment]
> That's unrelated.

Found the error https://pastebin.com/U1QuC6qS

**Comment by BrandonT80** [comment]
> > That's unrelated.
> 
> Found the error https://pastebin.com/U1QuC6qS

After hours of testing we found the issue!

Make sure network-compression-threshold is set to 256. In 1.19.3 having this set to something like 512 breaks chat. Confirmed on BloomHost and Pebblehost at least.

**Comment by timr2000** [comment]
> > > That's unrelated.
> > 
> > 
> > Found the error https://pastebin.com/U1QuC6qS
> 
> After hours of testing we found the issue!
> 
> Make sure network-compression-threshold is set to 256. In 1.19.3 having this set to something like 512 breaks chat. Confirmed on BloomHost and Pebblehost at least.

That's weird, since I'm using Geyser on Velocity, my network-compression-threshold is set to -1 on all paper servers.

**Comment by BrandonT80** [comment]
> > > > That's unrelated.
> > > 
> > > 
> > > Found the error https://pastebin.com/U1QuC6qS
> > 
> > 
> > After hours of testing we found the issue!
> > Make sure network-compression-threshold is set to 256. In 1.19.3 having this set to something like 512 breaks chat. Confirmed on BloomHost and Pebblehost at least.
> 
> That's weird, since I'm using Geyser on Velocity, my network-compression-threshold is set to -1 on all paper servers.

What is your Proxy server network-compression-threshold?

**Comment by timr2000** [comment]
That threshold is 256

**Comment by BrandonT80** [comment]
> That threshold is 256

Ill ask the person who uses velocity what their settings are, their server works so ill message back when they tell me :)

**Comment by timr2000** [comment]
You can add me on Discord if that's better for communication: timr2000#0001

**Comment by BrandonT80** [comment]
> timr2000#0001
Brandon T80#3180
cant add you since your not accepting requests xD

**Comment by Camotoy** [comment]
This should now be fixed. Let us know otherwise. Thanks!

**Comment by scottaus** [comment]
> This should now be fixed. Let us know otherwise. Thanks!

Hello I am now having the same issue in 1.21...

**Comment by scottaus** [comment]
NVM, I redownload the mod (idk if updated) and it is fixed.
