### ISSUE TITLE
Normal Rabbits are Gaint Rabbits in Bedrock

### ISSUE THREAD

**Issue by TazAlonzo** [GeyserMC/Geyser#3486]
### Describe the bug

So we have a Rabbit sanctuary on my server and I realized whilst playing on my phone that the rabbits that should be normal adults are HUGE! (babies are normal sized however)

### To Reproduce

1. Spawn/Find normal rabbit
2. Realize it is a Gaint in bedrock

### Expected behaviour

should be a normal sized adult rabbit.

### Screenshots / Videos

Java adult/Normal adult Rabbit:
![javaw_gkBQKdkNRR](https://user-images.githubusercontent.com/51837790/210149534-85b40682-3e28-47a0-a658-2f62bd9e1087.png)
The GAINTS on Bedrock:
![NVIDIA_Share_ayLxEqHS4r](https://user-images.githubusercontent.com/51837790/210149540-a51f5622-9e71-4bc6-be41-f26f52d75272.png)

### Server Version and Plugins

This server is running Paper version git-Paper-353 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8e83c3c)

### Geyser Dump

{     "versionInfo": {         "name": "Geyser",         "version": "2.1.0-SNAPSHOT (git-master-03390b9)",         "javaName": "OpenJDK 64-Bit Server VM",         "javaVendor": "Amazon.com Inc.",         "javaVersion": "17.0.4.1+9-LTS",         "architecture": "amd64",         "operatingSystem": "Linux",         "operatingSystemVersion": "5.15.0-47-generic",         "network": {             "dockerCheck": false,             "internalIP": "***"         },         "mcInfo": {             "bedrockVersions": [                 "1.19.20",                 "1.19.21/1.19.22",                 "1.19.30/1.19.31",                 "1.19.40/1.19.41",                 "1.19.50/1.19.51"             ],             "bedrockProtocols": [                 544,                 545,                 554,                 557,                 560             ],             "defaultBedrockProtocol": 560,             "javaVersions": [                 "1.19.3"             ],             "javaProtocol": 761         }     },     "cpuCount": 112,     "cpuName": "Intel(R) Xeon(R) Gold 6348 CPU @ 2.60GHz",     "systemLocale": "en_US",     "systemEncoding": "UTF-8",     "gitInfo": {         "buildNumber": "1261",         "git.commit.id.abbrev": "03390b9",         "git.commit.id": "03390b99e8240dc96a12414a016812b5e34de4dd",         "git.branch": "master",         "git.remote.origin.url": "https://github.com/GeyserMC/Geyser.git"     },     "config": {         "autoconfiguredRemote": true,         "bedrock": {             "address": "0.0.0.0",             "port": 19132,             "clone-remote-port": false,             "motd1": "World of HMMM",             "motd2": "HMMM - Villager 196",             "server-name": "World of HMMM",             "compression-level": 7,             "enable-proxy-protocol": false,             "proxy-protocol-whitelisted-ips": []         },         "remote": {             "address": "***",             "port": 25565,             "auth-type": "FLOODGATE",             "allow-password-authentication": true,             "use-proxy-protocol": false,             "forward-hostname": false         },         "userAuths": null,         "metrics": {             "enabled": true,             "uuid": "b451ca93-0b4d-45a5-8348-6009fc6ae0ab"         },         "saved-user-logins": [             "ThisExampleUsernameShouldBeLongEnoughToNeverBeAnXboxUsername",             "ThisOtherExampleUsernameShouldAlsoBeLongEnough"         ],         "floodgate-key-file": "key.pem",         "command-suggestions": true,         "passthrough-motd": true,         "passthrough-player-counts": true,         "passthrough-protocol-name": true,         "legacy-ping-passthrough": false,         "ping-passthrough-interval": 10,         "forward-player-ping": false,         "max-players": 35,         "debug-mode": false,         "allow-third-party-capes": true,         "show-cooldown": "title",         "show-coordinates": true,         "disable-bedrock-scaffolding": false,         "always-quick-change-armor": true,         "emote-offhand-workaround": "EMOTES_AND_OFFHAND",         "allow-third-party-ears": false,         "default-locale": null,         "cache-images": 0,         "allow-custom-skulls": true,         "max-visible-custom-skulls": 50,         "custom-skull-render-distance": 12,         "add-non-bedrock-items": true,         "above-bedrock-nether-building": true,         "force-resource-packs": false,         "xbox-achievements-enabled": false,         "log-player-ip-addresses": true,         "notify-on-new-bedrock-update": true,         "unusable-space-block": "minecraft:barrier",         "pending-authentication-timeout": 120,         "scoreboard-packet-threshold": 2,         "enable-proxy-connections": false,         "mtu": 1000,         "use-direct-connection": true,         "config-version": 4     },     "floodgate": {         "gitInfo": null,         "config": null     },     "userPlatforms": {         "UWP": 1     },     "hashInfo": {         "md5Hash": "38352c322420af1e1275cb642aee730d",         "sha256Hash": "0491c21995c406ec322e52d8d53b6815c8d412b0724355304c32104f40924343"     },     "ramInfo": {         "free": 133,         "total": 896,         "max": 2048     },     "logsInfo": null,     "bootstrapInfo": {         "platform": "SPIGOT",         "platformName": "Paper",         "platformVersion": "git-Paper-353 (MC: 1.19.3)",         "platformAPIVersion": "1.19.3-R0.1-SNAPSHOT",         "onlineMode": true,         "serverIP": "",         "serverPort": 25565,         "plugins": [             {                 "enabled": true,                 "name": "Graves",                 "version": "4.9",                 "main": "com.ranull.graves.Graves",                 "authors": [                     "Ranull"                 ]             },             {                 "enabled": true,                 "name": "AureliumSkills",                 "version": "Beta 1.3.12",                 "main": "com.archyx.aureliumskills.AureliumSkills",                 "authors": [                     "Archyx"                 ]             },             {                 "enabled": true,                 "name": "floodgate",                 "version": "2.2.0-SNAPSHOT (b74-4f36112)",                 "main": "org.geysermc.floodgate.SpigotPlugin",                 "authors": [                     "GeyserMC"                 ]             },             {                 "enabled": true,                 "name": "zItemStacker",                 "version": "1.0.2.2",                 "main": "fr.maxlego08.zitemstacker.ZItemPlugin",                 "authors": [                     "Maxlego08"                 ]             },             {                 "enabled": true,                 "name": "Geyser-Spigot",                 "version": "2.1.0-SNAPSHOT",                 "main": "org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin",                 "authors": [                     "GeyserMC"                 ]             }         ]     },     "flagsInfo": {         "flags": [             "-Xmx2048M",             "-XX:+UseContainerSupport",             "-Dcofh.rf.crashOnOldAPI=false",             "-Dfile.encoding=UTF-8",             "-Dfml.readTimeout=240",             "-XX:MaxMetaspaceSize=512M",             "-XX:+UseG1GC",             "-XX:+ParallelRefProcEnabled",             "-XX:MaxGCPauseMillis=200",             "-XX:+UnlockExperimentalVMOptions",             "-XX:+DisableExplicitGC",             "-XX:+AlwaysPreTouch",             "-XX:G1NewSizePercent=30",             "-XX:G1MaxNewSizePercent=40",             "-XX:G1HeapRegionSize=8M",             "-XX:G1ReservePercent=20",             "-XX:G1HeapWastePercent=5",             "-XX:G1MixedGCCountTarget=4",             "-XX:InitiatingHeapOccupancyPercent=15",             "-XX:G1MixedGCLiveThresholdPercent=90",             "-XX:G1RSetUpdatingPauseTimePercent=5",             "-XX:SurvivorRatio=32",             "-XX:MaxTenuringThreshold=1",             "-Dusing.aikars.flags=���https://mcflags.emc.gs���",             "-Daikars.new.flags=true",             "-Dterminal.jline=false",             "-Dterminal.ansi=true",             "-XX:+UnlockDiagnosticVMOptions",             "-XX:-UseAESCTRIntrinsics",             "-DPaper.IgnoreJavaVersion=true"         ]     },     "extensionInfo": [] }

### Geyser Version

2.1.0-SNAPSHOT (git-master-03390b9)

### Minecraft: Bedrock Edition Device/Version

Latest update as of 12/31/22 for Windows

**Comment by T4ZERTAZ** [comment]
Forgot about the plugins so here they are.
![chrome_vwSe4Dk2gg](https://user-images.githubusercontent.com/51837790/210150042-34a9171a-e543-4e28-84ad-4c144cad3ba0.png)
