### ISSUE TITLE
npc and player not loading

### ISSUE THREAD

**Issue by tomzangsad** [GeyserMC/Geyser#3489]
### Describe the bug

An example is in the video.

### Screenshots / Videos

[Uploading 323720712_8880177578660864_6292917485891331764_n.mp4…](https://user-images.githubusercontent.com/63664294/210264534-cbf5145c-0b98-48b6-9511-41a5eed280e0.mp4)

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-1b4be61)

### Minecraft: Bedrock Edition Device/Version

1.19.51

**Comment by onebeastchris** [comment]
If this issue still occurs on the latest Geyser version, send a geyser dump & server logs

**Comment by onebeastchris** [comment]
Closing due to no response. If the issue is still occurring with the latest version, please provide a new geyser dump & a full log.
