### ISSUE TITLE
Loom is not woriking

### ISSUE THREAD

**Issue by Galilejo** [GeyserMC/Geyser#3491]
### Describe the bug

Hi, I'm not sure if this is because of the geyser but that's what I read somewhere, the loom on the server just doesn't work.

![image](https://user-images.githubusercontent.com/107082292/210722657-b884c995-fc07-4609-ab30-3ef23de789b3.png)

### To Reproduce

/

### Expected behaviour

-

### Server Version and Plugins

server version is 1.18.2 and there is ~90 plugins

### Geyser Dump

https://dump.geysermc.org/XutndwYdgn3oJf3BtV8djHQs9tTmNr14

### Geyser Version

2.1.0-SNAPSHOT (git-master-b27b1c8)

**Comment by Camotoy** [comment]
Seeing as this is a Java screenshot, this is very likely not our fault. See here? https://github.com/ViaVersion/ViaVersion/issues/2938

Thanks.
