### ISSUE TITLE
Can't go through nether portal without having to disconnect and reconnect to server

### ISSUE THREAD

**Issue by Meloooche** [GeyserMC/Geyser#3492]
Every time I go through a nether portal on my friends java server I get stuck in this weird state where I am inside of blocks and cant move, the only way to fix this is if I disconnect and reconnect from the server. It's only a minor inconvenience but it gets quite annoying having to disconnect and then login again every time I want to go to the nether or the end.

**Comment by Camotoy** [comment]
Duplicate of #3482 now. Thanks though!
