### ISSUE TITLE
bedrock users warned their chats likely aren't seen, chat functions completely normally

### ISSUE THREAD

**Issue by imbatthew** [GeyserMC/Geyser#3493]
### Describe the bug

when a bedrock user logs in and sends their first chat message, they are warned that their messages likely can't be seen because the server has "enforce-secure-profile" enabled in settings. the setting is not enabled. the user is able to chat completely normally, their messages are seen by java players and they can see java players' messages

### To Reproduce

1. log in as bedrock player
2. send a chat message
3. receive the message

### Expected behaviour

i expect to be able to send a message without this message appearing in my chat

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/56161143/211115532-b406d2d4-f19b-4040-80ce-776192d4d920.png)
![image](https://user-images.githubusercontent.com/56161143/211115644-8855d185-069b-48f6-837a-d0cee5def3d8.png)

### Server Version and Plugins

Current: git-Purpur-1883 (MC: 1.19.3)*
Previous: git-Purpur-1858 (MC: 1.19.2)
* You are 3 version(s) behind
Download the new version at: https://purpurmc.org/downloads

AutoReconnect-1.6.11.jar
BanManagerBukkit.jar
ChestShop.jar
Chunky-1.3.52.jar
ChunkyBorder-1.1.42.jar
CoreProtect-21.3.jar
DiscordSRV-Build-1.26.0.jar
Dynmap-3.5-beta-1-spigot.jar
EntityDetection.jar
EssentialsX-2.19.7.jar
EssentialsXProtect-2.20.0-dev+37-b7a4bea.jar
Factions.jar
floodgate-spigot.jar
FreedomChat-1.3.1.jar
Geyser-Spigot.jar
GSit-1.3.1.jar
InteractiveChat-4.2.5.2.jar
InteractiveChatDiscordSrvAddon-4.2.5.3.jar
InventoryRollbackPlus-1.6.8.jar
InvisibleFrames-0.0.jar
LibsDisguises-10.0.31-Free.jar
LPC.jar
LuckPerms-Bukkit-5.4.57.jar
Maintenance-4.0.1.jar
minimotd-bukkit-bungeecord-2.0.10.jar
multichat-1.9.6.jar
orebfuscator-plugin-5.3.2.jar
Pl-Hide-Pro-2.6.6.jar
PlaceholderAPI-2.11.2.jar
PlayerStats-1.7.2.jar
ProtocolLib.jar
RHLeafDecay-1.19_R3.jar
spark-1.10.25-bukkit.jar
SuperVanish.jar
Vault.jar
ViaBackwards-4.5.1.jar
ViaVersion-4.5.1.jar
ViewDistanceTweaks-1.5.4.jar
VotingPlugin.jar
Vulcan-2.7.1.jar
worldedit-bukkit-7.2.13.jar
WorldEditSelectionVisualizer-2.1.3.jar
worldguard-bukkit-7.0.7-dist.jar

### Geyser Dump

https://dump.geysermc.org/BceSg5k70hQitEpYDCvdg56aHTB4vBLY

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-7905581) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.50/1.19.51)

### Minecraft: Bedrock Edition Device/Version

v1.19.51 , windows 10 pc

### Additional Context

i saw a very similar seeming bug report recently about something with bedrock players and chat that seemed to affect specifically bloomhost, this server is also run off bloom

**Comment by Kas-tle** [comment]
Please remove all plugins except floodgate and Geyser, and see if the issue persists. If the issue does not occur with minimal plugins, add plugins back until you figure out which is causing the issue.

**Comment by imbatthew** [comment]
alright yeah it was a plugin causing the issue, sorry lol

**Comment by Kas-tle** [comment]
No worries. What was the plugin causing the issue? We'd still like to fix it of course if possible.

**Comment by imbatthew** [comment]
still adding them back in, i'll let you know!

**Comment by imbatthew** [comment]
seems like the culprit was freedomchat.

**Comment by Kas-tle** [comment]
Ah. I think that freedomchat tries to spoof chat signing, which means to Geyser packet-wise it looks like the server is enforcing secure profiles for chat. Keep in mind that if you have another chat plugin sending messages as system chat, freedom chat is not serving any purpose as system chat messages (grey bar) cannot be reported.

**Comment by imbatthew** [comment]
yeahh my friend and i just started this server up and he had it on his list of like must-have plugins, i'll go ahead and take it out because i'm 99.9% sure they're all marked as system messages anyway

thank you! sorry about the false alarm

**Comment by Camotoy** [comment]
I'll mark this as intentional for now. This can be disabled altogether with the system property `-DGeyser.PrintSecureChatInformation=false`. 
Thanks for the report.
