### ISSUE TITLE
Bedrock version players cannot see Java version players

### ISSUE THREAD

**Issue by CuteLittleSky** [GeyserMC/Geyser#3494]
### Describe the bug

> Bedrock version players cannot see Java version players

### To Reproduce

When joining the server, the Java version of the player is displayed normally, but after a while the Bedrock version of the player can not see the Java version of the player

### Expected behaviour

It's a probability event, it doesn't happen every time

### Server Version and Plugins

Plugins (66): AncientGates, AntiVillagerLag, BBSToper*, BedrockPocketUIWarn*, BEMenuAPI, BentoBox, BiliReward*, BookScoreBoard, ChestSort, ChunkHeat, Citizens, CompatNoCheatPlus, CoreProtect, DeEnchantment, DeluxeMenus, eBackup, EffectLimit*, Essentials, EssentialsSpawn, FarmControl, floodgate, Floodgate-Skript, GeyserHacks, GeyserSkinManager, HolographicDisplays, HuskHomes, LevelledMobs, LiteSignIn, LuckPerms, mcMMO, McMmoView, Multiverse-Core, NoCheatPlus, NonEnoughSpaceServerCloser*, NoSpawnChunks, PlaceholderAPI, PlayerTask, PlayerTitle, PlugManX (PlugMan), ProtocolLib, ProtocolStringReplacer, PuerkasMarriage*, qscompat-bentobox, QuickShop-Hikari, QuickShopForm, ScriptBlockPlus, Shopkeepers, Skript, skript-reflect, spark, TileDataSaver, TrChat, UltimateAutoRestart, UniqueUUID, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, ViewDistanceTweaks, VoxelMapSupport, WanderingTrades, WorldEdit, WTF*, XConomy, YeqiLib

### Geyser Dump

https://dump.geysermc.org/WwNlKObsfs5QFy4Q9nvsb9D1czVGWvtA

### Geyser Version

Build 1269

### Minecraft: Bedrock Edition Device/Version

1.19.51

### Additional Context

Viaversion dump: https://dump.viaversion.com/2770176ee45b6623256de67dd511c5cd94b19a08a4e765a79f955c4ff0d8b904

**Comment by onebeastchris** [comment]
Does this issue still occur on the latest version of Geyser?
If yes, it's likely an issue with another plugin. Do any of your plugin change how skins look/work?

**Comment by onebeastchris** [comment]
Closing due to no response.
