### ISSUE TITLE
Geyser-Spigot Server Crashing on Link posted in chat

### ISSUE THREAD

**Issue by CustomAmelia** [GeyserMC/Geyser#3495]
### Describe the bug

People on java (most of the time) disconnect whenever a link is posted in chat with someone in bedrock in the server too (bedrock not disconnected

### To Reproduce

1. Atleast 1 Bedrock player on server
2. Java person paste a link in chat
3. Crash with error

### Expected behaviour

Link is shown and doesnt crash

### Server Version and Plugins

Paper version git-Paper-368 (MC: 1.19.3)

Plugins: 
![javaw_8hOQuYYM8w](https://user-images.githubusercontent.com/66842247/211176848-85e4e9a2-36ab-44b4-bcd1-1abda726a73a.png)

### Geyser Dump

https://dump.geysermc.org/5gnX2xs5hqvOXIXzxM4gTfBbqQdhkDpW

### Geyser Version

2.1.0 Snapshot

### Minecraft: Bedrock Edition Device/Version

Java

**Comment by Camotoy** [comment]
Is there an error printed when this occurs? Can you send it?

**Comment by CustomAmelia** [comment]
No error

**Comment by CustomAmelia** [comment]
> Is there an error printed when this occurs? Can you send it?

Yes, here it is

`WARN [Geyser-Spigot] Downstream packet error! direct buffer
08.01 0216 [Server] WARN [Geyser-Spigot] Downstream packet error! direct buffer
08.01 0216 [Server] WARN [Geyser-Spigot] Downstream packet error! direct buffer
08.01 0216 [Server] WARN [Geyser-Spigot] Downstream packet error! direct buffer
08.01 0216 [Server] WARN [Geyser-Spigot] Downstream packet error! direct buffer
[02:11]
WARN java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.skin.SkinManager$GameProfileData.skinUrl()" because "data" is null
08.01 02:08:38 [Server] WARN at Geyser-Spigot.jar//org.geysermc.geyser.skin.SkullSkinManager.requestAndHandleSkin(SkullSkinManager.java:55)
08.01 02:08:38 [Server] WARN at Geyser-Spigot.jar//org.geysermc.geyser.entity.type.player.SkullPlayerEntity.updateSkull(SkullPlayerEntity.java:112)
08.01 02:08:38 [Server] WARN at Geyser-Spigot.jar//org.geysermc.geyser.session.cache.SkullCache.assignSkullEntity(SkullCache.java:175)
08.01 02:08:38 [Server] WARN at Geyser-Spigot.jar//org.geysermc.geyser.session.cache.SkullCache.updateVisibleSkulls(SkullCache.java:146)
08.01 02:08:38 [Server] WARN at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.bedrock.entity.player.BedrockMovePlayerTranslator.translate(BedrockMovePlayerTranslator.java:139)
08.01 02:08:38 [Server] WARN at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.bedrock.entity.player.BedrockMovePlayerTranslator.translate(BedrockMovePlayerTranslator.java:43)
08.01 02:08:38 [Server] WARN at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
08.01 02:08:38 [Server] WARN at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
08.01 02:08:38 [Server] WARN at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
08.01 02:08:38 [Server] WARN at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
08.01 02:08:38 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
08.01 02:08:38 [Server] WARN at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
08.01 02:08:38 [Server] WARN at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
08.01 02:08:38 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Camotoy** [comment]
Please try updating Geyser.

**Comment by CustomAmelia** [comment]
> Please try updating Geyser.

I'm not the owner of the server but as soon as the owner does that (ill tell them) ill lyk.

**Comment by CustomAmelia** [comment]
> Please try updating Geyser.

This worked

**Comment by CustomAmelia** [comment]
Please reopen, this issue is now continuing after it didn't do it for a few hours but I believe that was due to the lack of bedrock players on the server at the time.
