### ISSUE TITLE
BUG for the bedrock(mcpe)

### ISSUE THREAD

**Issue by DeeRenjie** [GeyserMC/Geyser#35]
Hi! I am from China, so my English is not very good.
Here are all the BUG
1.Stay in the Generating World（summon world）
2.The mode is visitor 
3.The backpack is empty
4.Blocks cannot be placed
5.The BossBar is no display
6.The weather does not change.Such as rain
Can you add server transfer?
Thank you！

**Comment by WesleyVanNeck** [comment]
What do you expect it's not finished

**Comment by DeeRenjie** [comment]
Come on,！thank you！
emmm……If I want to sponsor you, can you use Alipay?

**Comment by WesleyVanNeck** [comment]
you cant use alipay

**Comment by RednedEpic** [comment]
Hi, yes, this software is still very much a work in progress as Wesley said. You can view what is done and what isn’t in the README. 

We have a Patreon if you’re interested in donating. Unsure if it accepts Alipay but we do accept PayPal. 

Link: https://www.patreon.com/GeyserMC
