### ISSUE TITLE
Server kicks bedrock players on join

### ISSUE THREAD

**Issue by Sl0wYx** [GeyserMC/Geyser#3501]
### Describe the bug

When player from bedrock connects to geyser he gets immediately kicked without any console errors. Player gets message “Connection closed”. I tried to reinstall geyser now it works some time after restart, players can walk and get resources but they have only spawn chunks loaded. And again, after some time they can’t join again. And after java player joins bedrock players getting kicked

### To Reproduce

1. Download Geyser
2. Configure it
3. Try to join from bedrock

### Expected behaviour

Bedrock players playing as intended with plugin

### Screenshots / Videos

![B2C89B3B-8FAC-499D-AF9A-82D7E2A223C1](https://user-images.githubusercontent.com/87186926/211785668-e485f6e4-d1ec-4ba3-aa2a-8d7f55c9acac.jpeg)
![E8CA9DB2-627C-417F-9622-7E4EEDBE9CF5](https://user-images.githubusercontent.com/87186926/211785675-4436b99e-dd74-4a7e-a006-ffd3316acac5.jpeg)

### Server Version and Plugins

[10:41:51 INFO]: Checking version, please wait.
[10:41:51 INFO]: This server is running Paper v ersion git-Paper-307 (MC: 1.19.2 (Implementing
API version 1.19.2-RO.1-SNAPSHOT) (Git: 476ef2
5)
You are running the latest version
Previous version: git-Paper-370 (MC: 1.19.3)

Plugins (33): AuthMe, BlueMap, CoordinatesHud, CoreProtect, CustomJoin*, DiscordSRV, DriveBackupV2, EasyWhitelist*, FastChunkPregenerator, floodgate,
Geyser-Spigot, GSit,
Harbor, Hat, InvisibleItemFrames, JustOneMorePlus*, LightChatBubbles*, LPC, LuckPerms, NoCheatPlus, OpenAudioMc, OpenInventory*, Orebfuscator , PistonMOTD, PrivateMessages, Protocollib, SkinsRestorer, spark, TabList, Themis, TubeTils, ViaBackwards, ViaVersion

### Geyser Dump

https://dump.geysermc.org/KLAEmU9ha6Na5r7p5c1RVca0paHhf3st

### Geyser Version

2.1.0-SNAPSHOT (git-master-c928baf)

### Minecraft: Bedrock Edition Device/Version

1.19.51/1.19.50

**Comment by SageSphinx63920** [comment]
You downgraded your server. Maybe this could cause the chick problem

**Comment by Sl0wYx** [comment]
The issue was with NoCheatPlus
