### ISSUE TITLE
Frames are placed in the middle of the block

### ISSUE THREAD

**Issue by masterhacka** [GeyserMC/Geyser#3502]
### Describe the bug

Hi there, when placing frames they are bugging in the middle of a block. What can I do?
Checking in Java edition shows the correct position of the frames.

### To Reproduce

Just place or look on any previously placed frames.

### Expected behaviour

The frames with bedrock edition should show the same like on java edition.

### Screenshots / Videos

![Resizer_16734632896841](https://user-images.githubusercontent.com/9753608/212469674-b4a31be1-15c0-41a7-9f7d-5cc3f06c0f8a.png)

### Server Version and Plugins

This server is running Paper version git-Paper-216 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 30cb7d0)

### Geyser Version

Build #1270 (07.01.2023, 19:46:36)

**Comment by Camotoy** [comment]
This issue appears identical to #3014 so I'll close it. Thanks anyway!
