### ISSUE TITLE
Discord Unban

### ISSUE THREAD

**Issue by DaddyRobLIVE** [GeyserMC/Geyser#3503]
### Describe the bug

Hello, first of all, I'm sorry for using this platform. I just don't know where to appeal to enter the discord server again. My account got hacked before. You know those discord invite link spams where they post to all your discord servers and discord friends an invitation to their lewd discord server. I already have full access to my account restored. So please, I'm watching the discord to stay updated and connect to the community.

Discord ID: Daddy Rob#9033

### To Reproduce

Hello, first of all, I'm sorry for using this platform. I just don't know where to appeal to enter the discord server again. My account got hacked before. You know those discord invite link spams where they post to all your discord servers and discord friends an invitation to their lewd discord server. I already have full access to my account restored. So please, I'm watching the discord to stay updated and connect to the community.

Discord ID: Daddy Rob#9033

### Expected behaviour

Hello, first of all, I'm sorry for using this platform. I just don't know where to appeal to enter the discord server again. My account got hacked before. You know those discord invite link spams where they post to all your discord servers and discord friends an invitation to their lewd discord server. I already have full access to my account restored. So please, I'm watching the discord to stay updated and connect to the community.

Discord ID: Daddy Rob#9033

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/109517972/212546169-36ac0dcc-8569-48b4-bc11-9f718f034945.png)

### Geyser Version

Geyser-Spigot 2.1.0-SNAPSHOT

**Comment by Jens-Co** [comment]
Please fill in this form; https://docs.google.com/forms/d/1wOzU8LW7oc8vnYH0Af8LNCLyYPKF3Eg1Oi99fFe_91w

ill close this issue since its not relevant.
Thanks.
