### ISSUE TITLE
Error whilst checking for Geyser update!

### ISSUE THREAD

**Issue by sternschnaube** [GeyserMC/Geyser#3506]
### Describe the bug

Hello, It's nothing big but I wanted to share:
https://pastebin.com/raw/BF2M1nhB

### To Reproduce

/

### Expected behaviour

/

### Geyser Version

Fabric #1270

**Comment by Camotoy** [comment]
Thanks for reporting. This is probably a temporary issue, or an issue with your network connection.

**Comment by sternschnaube** [comment]
I use some mods who are affected the network like Raknetify, Connectivity and Krypton.
Maybe more. Maybe it comes from that.

I think it's just a temporary one - not sure how my internet should be created this issue, I was connected via Java and I'm not hosting the server. Thanks 😊

**Comment by Fungus-00** [comment]
> Thanks for reporting. This is probably a temporary issue, or an issue with your network connection.

I encounter the same error each time I start the server.
Might it be the firewall that blocks the network connection of updating?
