### ISSUE TITLE
I can join but no chunks load and i fall until y -104

### ISSUE THREAD

**Issue by Ej747** [GeyserMC/Geyser#3509]
### Describe the bug

I am able to join on bedrock but nothing loads in and I fall until i hit y -104 (video below). Java works fine though.

I get the error:
[nioEventLoopGroup-4-3/WARN]: Downstream packet error! Packet "ClientboundPlayerPositionPacket" not fully read.

Dump link is below

The server is running on a raspberry pi 4 with 4GB of ram. The pi's OS is Ubuntu 20.04. MC version is 1.19.3

### To Reproduce

1. Join server on bedrock.
2. Experience falling and a lack of chunks.
(this is probably really crappy but idk what else to say)

### Expected behaviour

I should load into the world and be able to play normally.

### Screenshots / Videos

https://user-images.githubusercontent.com/88404960/213263783-fa96d0c5-2334-434c-80a2-a593e82f47d2.mp4

### Server Version and Plugins

geyser version
[13:27:27] [Server thread/INFO]: This server is running Geyser version 2.1.0-SNAPSHOT (git-master-0b80c58) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.50/1.19.51)

![image](https://user-images.githubusercontent.com/88404960/213264378-5b8590fd-c03a-4e52-b4bc-3f4b034e87cf.png)

### Geyser Dump

https://dump.geysermc.org/p7CmLYKg2Cv50T3BfRJFf6aUhyKLRXrN

### Geyser Version

2.1.0-SNAPSHOT (git-master-0b80c58)

### Minecraft: Bedrock Edition Device/Version

1.19.3, problem is definitely with Minecraft for Windows and Minecraft Android app (I'm assuming it would happen with all)

**Comment by Camotoy** [comment]
Can you try without any other mods? In particular I think Immersive Portals has done something funky in the past.

**Comment by Ej747** [comment]
That seems to have worked. It lets me join and the world loads in but now whenever I open my inventory it freezes and crashes. This happened both on my pc with the windows version and on my phone with the app.

**Comment by onebeastchris** [comment]
Does this issue still occur on the latest version of Geyser? If yes, send a new Geyser dump & the latest.log file.

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
