### ISSUE TITLE
Pistons' heads do not display properly

### ISSUE THREAD

**Issue by denisryba** [GeyserMC/Geyser#351]
**Description**
1. Pistons do not change their model when activated
2. On joining the server pistons do not have their heads. When a piston is placed while bedrock player is in the game it displays properly (until rejoin) desipte the issue mentioned in first point. 

**To Reproduce**
1. Join the server that has pistons placed in the world
2. Observe piston's appearance
3. Place a piston
4. Try to activate it

**Expected behavior**
Piston's heads should always be visible and moved forward when activated

**Screenshots / Videos**
![model](https://user-images.githubusercontent.com/43182082/79381268-c6692400-7f72-11ea-8614-7769cabbaf71.png)
![onJoin](https://user-images.githubusercontent.com/43182082/79381288-ce28c880-7f72-11ea-8e48-04dc55cd83e8.png)

**Server Version**
Paper 1.15.2 git-183

**Geyser Version**
inventory #14

**Minecraft: Bedrock Edition Version**
1.14.30

**Comment by DoctorMacc** [comment]
Will be partially fixed with #334 - pistons that are updated will show properly.

**Comment by RERASER** [comment]
![Screenshot_20200425_155322](https://user-images.githubusercontent.com/63722060/80274495-63fbea80-870d-11ea-9115-8ef86f22cb41.jpg)

**Comment by RERASER** [comment]
It also occurs in the off state
