### ISSUE TITLE
Boats are Inconsistent in Bubble Columns

### ISSUE THREAD

**Issue by ItzFlipp** [GeyserMC/Geyser#3510]
### Describe the bug

I am not sure if this is just a Bedrock client issue, but when Bedrock players drive a boat into a bubble column (water elevator), they are booted out of the boat. In this specific case, I am running a boat race minigame where I cancel the `EntityDismountEvent`. Because of this, the Bedrock player gets booted out of the boat client-side and gets stuck in one position inside of the boat server-side. The first video linked below shows this. 

Furthermore, I have tried taking an alternative approach which is a very buggy fix. I have not cancelled the `EntityDismountEvent` but instead, force the player back into the boat 3 ticks later:

`Bukkit.getScheduler().runTaskLater(plugin, () -> e.getDismounted().addPassenger(p), 3);`

In the second video I have linked, I showed how it looks. It still ejects the player out of the boat while they are in the bubble column; however, it looks like sneaking repeatedly syncs the client back up with the server. This solution is not viable because this mechanic becomes very broken when going up taller bubble columns. 

### To Reproduce

1. Create a vertical bubble column with soul sand
2. Drive a boat into the bubble column on Bedrock edition
3. Optional: Cancel the `EntityDismountEvent` OR run a delayed task (3 ticks) to force the player back into the boat and repeat steps 1 and 2.

### Expected behaviour

It is expected that a Bedrock player goes up the bubble column in the boat without being ejected or glitching into and out of the boat while going up. It should function like my Java account (on the right side of the videos linked below).

### Screenshots / Videos

Video 1 - Cancelling EntityDismountEvent: https://www.youtube.com/watch?v=Yh6d8_2o3jA
Video 2 - Not cancelling EntityDismountEvent, but running a delayed task to force the player back into the boat: https://www.youtube.com/watch?v=aSmw53ua8CQ

### Server Version and Plugins

Backend: git-Purpur-1890 (MC: 1.19.3)
Proxy: git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:a24c106:158

### Geyser Dump

https://dump.geysermc.org/6FWRuG9MgXZdOUHRq7QWWwhievwy9SvE

### Geyser Version

2.1.0-SNAPSHOT (git-master-0b80c58)

### Minecraft: Bedrock Edition Device/Version

1.19.51 (Windows 10 and IOS)

**Comment by ItzFlipp** [comment]
Hello. I was wondering if there was any progress on this issue. It is still present as of 1.19.83.

Thanks

**Comment by JerryHan3** [comment]
This issue still exists in 1.20.0.01. I hope this bug can be fixed soon, since we are going to hold a competition for both JE & BE players, and we need to use this feature in the Boat Racing program.

**Comment by Konicai** [comment]
There is no ETA - I would not depend on it being fixed for something you consider important.

**Comment by JerryHan3** [comment]
> Closing as duplicate of #3510. Please follow there for updates.

Wait what? You say this issue is a duplicate of ITSELF???

**Comment by Kas-tle** [comment]
> > Closing as duplicate of #3510. Please follow there for updates.
> 
> Wait what? You say this issue is a duplicate of ITSELF???

My bad. I have edited my comment to correctly reflect that this is a duplicate of https://github.com/GeyserMC/Geyser/issues/2574.
