### ISSUE TITLE
bedrock players can't load new chunks on 1.12.2 and 1.16.5

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#3511]
### Describe the bug

no errors are appeared but when they tried to load new chunks (old chunk is fine to load) it will cause fps drops + high pings (like 10k) + chunks are stopped load and get disconnected from server

### To Reproduce

join the server with bedrock
and go to new chunks
and boom u got 10k ping with unplayable fps drops and u get disconnected

### Expected behaviour

no errors

### Screenshots / Videos

https://user-images.githubusercontent.com/88581750/213616314-a63047b5-2cef-4413-83d1-80c34c6300f9.mp4

### Server Version and Plugins

[13:13:16 INFO]: This server is running Paper version git-Paper-"e591764" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[13:13:16 INFO]: Current version: git-Paper-1620 (MC: 1.12.2)

### Geyser Dump

https://dump.geysermc.org/a2TPMQpRklVsUT2Xuq6JcTpvqAGKzrpc

### Geyser Version

1271 Build

### Minecraft: Bedrock Edition Device/Version

1.19.20 ~ 1.19.51

### Additional Context

it's not happening on 1.19.3

**Comment by Camotoy** [comment]
This is probably related to your other issue, #3507. Thanks anyway.
