### ISSUE TITLE
allow custom unusable-space-block

### ISSUE THREAD

**Issue by Hahaa13** [GeyserMC/Geyser#3512]
### What feature do you want to see added?

allow custom unusable-space-block with model data
ex:
unusable-space-block:
  material: minecraft:barrier
  model_data: 1

### Are there any alternatives?

no

**Comment by Camotoy** [comment]
Seems reasonable to me, but I would probably specify the custom Bedrock identifier instead.

**Comment by Kas-tle** [comment]
I'm not sure I follow? Blocks themselves don't have custom model data... the items that place them so sure, but the block in world only has its block states.

**Comment by Konicai** [comment]
> I'm not sure I follow? Blocks themselves don't have custom model data... the items that place them so sure, but the block in world only has its block states.

The config option is just worded weirdly lol
