### ISSUE TITLE
help!!!!!!!!!!

### ISSUE THREAD

**Issue by amogus123456789lol** [GeyserMC/Geyser#3514]
### Describe the bug

I cant connect to server on mobile!!!!

### To Reproduce

idk!!!!!!!!

### Expected behaviour

enter server

### Geyser Dump

https://dump.geysermc.org/Y1y5UYm674mAPSUgU5QHHKF3BBtVnVAS

### Geyser Version

idk

### Minecraft: Bedrock Edition Device/Version

mobile iphone

**Comment by Konicai** [comment]
Please use our Discord https://discord.gg/GeyserMC for setup help
