### ISSUE TITLE
Keystone version of the client skin does not display properly

### ISSUE THREAD

**Issue by HansOffice** [GeyserMC/Geyser#3516]
### Describe the bug

I personally built an external login skin station, allowing players to register server accounts and upload skins to the server in the skin station. java version of the client can display the player's skin normally, but the bedrock version does not seem to receive the correct skin here, resulting in abnormal display

### To Reproduce

I used my own skin site dl.cyumc.ltd:48803 for the registration and skin upload

### Expected behaviour

I wish the bedrock version of the client could display skins properly

### Screenshots / Videos

![AM BARQV CIT0D@Y9(~4{{V](https://user-images.githubusercontent.com/94523696/213912539-d4673072-b45d-4262-8ca9-a9611aaf5777.png)

### Server Version and Plugins

Waterfall1.19.3

### Geyser Version

1284 Geyser-BungeeCord

### Minecraft: Bedrock Edition Device/Version

1,19.51

**Comment by Camotoy** [comment]
I would be surprised if this works on a vanilla Java client without any modification. Therefore, I'm going to close this issue. If you believe this is our error, then please provide replication steps (how to spawn an NPC with the correct textures?). Thanks.

**Comment by HansOffice** [comment]
> 如果这在没有任何修改的情况下适用于普通 Java 客户端，我会感到惊讶。因此，我要关闭这个问题。如果您认为这是我们的错误，请提供复制步骤（如何生成具有正确纹理的 NPC？）。谢谢。

The Java version of the client did not make any changes affecting the skin side, and my server-side skin station is referenced authlib-injector as an external login.

**Comment by HansOffice** [comment]
> > 普通在的情况情况下适用适用适用于？）。谢谢。
> 
> Java版的客户端没有做任何影响皮肤端的改动，我的服务器端皮肤站引用authlib-injector作为外部登录。

I also asked a question on authlib-injector's issue tracking page, but they don't seem to be affected in this way
