### ISSUE TITLE
Issues with crafting lots of items at once

### ISSUE THREAD

**Issue by junxiesky** [GeyserMC/Geyser#3517]
### Describe the bug

When the player of bedrock edition synthesizes too fast, he will synthesize all the items.

### To Reproduce

1.Prepare a set of oak boards
2.Open the synthesis table.
3.Synthesis of Quick Click Button
4.All the boards will be made into buttons, which is stupid.

### Expected behaviour

When you click quickly to synthesize, you can synthesize several items by pressing it several times.

### Server Version and Plugins

Current: git-Purpur-1905 (MC: 1.19.3)
You are running the latest version

### Geyser Version

#1285

### Minecraft: Bedrock Edition Device/Version

1.19.51.01

**Comment by Camotoy** [comment]
Please provide a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

Please also provide the device you're using to play Bedrock Edition on. Or, even better, please supply a video of the bug occurring.

**Comment by junxiesky** [comment]
> 请提供间歇泉转储。
> 
> 在您的间歇泉实例或服务器上运行（服务器控制台）/（游戏内聊天），然后复制它将为您提供的链接并将其粘贴到此处。间歇泉转储是一种为我们提供有关您的服务器和间歇泉配置的大量有用信息的方式。这不包括任何 IP 或敏感数据。`geyser dump``/geyser dump`
> 
> 请同时提供您用于玩基岩版的设备。或者，更好的是，请提供发生的错误的视频。

https://dump.geysermc.org/RA1OPlAiOxjWjxjRfcF3AuJtFRKhieRa

**Comment by junxiesky** [comment]
https://user-images.githubusercontent.com/30452768/214428241-1a577256-f1ec-4845-8159-0c6d97eb7a33.mp4

**Comment by junxiesky** [comment]
> Please provide a Geyser dump.
> 
> Run (server console) / (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.`geyser dump``/geyser dump`
> 
> Please also provide the device you're using to play Bedrock Edition on. Or, even better, please supply a video of the bug occurring.

https://dump.geysermc.org/RA1OPlAiOxjWjxjRfcF3AuJtFRKhieRa

**Comment by junxiesky** [comment]
> Please provide a Geyser dump.
> 
> Run (server console) / (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.`geyser dump``/geyser dump`
> 
> Please also provide the device you're using to play Bedrock Edition on. Or, even better, please supply a video of the bug occurring.

I think this may be a problem caused by the high ping value of bedrock players?
On the local server with 0 delay, it is difficult for me to reproduce this problem.

**Comment by junxiesky** [comment]
@Camotoy emm？

**Comment by junxiesky** [comment]
@Camotoy

**Comment by junxiesky** [comment]
@Camotoy Is there any progress in this matter

**Comment by Kas-tle** [comment]
Cannot reproduce this issue. If this is still occurring, please reply with specific reproduction steps and the platform this occurs on (e.g. Switch, Windows, Xbox, etc.).
