### ISSUE TITLE
[BUG]Floodgate with the auth-type offline cause the bedrock player recognized as Java player

### ISSUE THREAD

**Issue by Ticozheng** [GeyserMC/Geyser#3518]
### Describe the bug

Floodgate with the auth-type offline cause the bedrock player recognized as Java player

### To Reproduce

1.install the Floodgate on bungee and spigot
2.change the address from "auto" to "127.0.0.1" in geyser config
3.restart

### Expected behaviour

I installed Geyser-bungee at early time, and install the Floodgate-bungee rencently(also install Floodgate on spigot server), bedrock player can be recognized correctly. Then I change the address from "auto" to "127.0.0.1" and keep the auth-type set to "offline" in geyser,  I found neither FloodgatePlaceholder or Matrix can recognize bedrock player, they were recognized as Java player. Now I have to remove Floodgate.(Java version 1.19.3, Floodgate using Build #74)

I use Floodgate because hope to check if a player is  bedrock player or not and get the result with Placeholder, and using with auth-type "offline" is for keeping the UUID of the bedrock player who also connect via Java version. 

I think although I install the Floodgate, I can decide which auth type to be use and not only "Floodgate", hope can deal with this problem

### Geyser Version

2.1.0-SNAPSHOT (git-master-48d7872)

### Additional Context

21:32:02 [信息] [Geyser-BungeeCord] /116.162.56.139:39030 尝试连接!
**21:32:03 [信息] [Geyser-BungeeCord] 玩家以 bilibiliayyy 的用户名建立了连接**
21:32:03 [信息] [Geyser-BungeeCord] bilibiliayyy (登录为: bilibiliayyy) 已连接到 Java 服务器
21:32:03 [信息] [bilibiliayyy,/116.162.56.139:39030] <-> InitialHandler has connected
21:32:03 [信息] [bilibiliayyy] <-> ServerConnector [world] has connected
**21:32:03 [信息] [MatrixBungee] [Debug] bilibiliayyy is not a bedrock player! (f:true)**
21:34:31 [信息] CONSOLE executed command: /geyser list
21:34:31 [信息] §e在线玩家 (1): §fbilibiliayyy

**Comment by Tim203** [comment]
Floodgate only works when you set the auth-type to Floodgate in the Geyser config.
