### ISSUE TITLE
unsupported bedrock version

### ISSUE THREAD

**Issue by Minecon724** [GeyserMC/Geyser#352]
**Describe the bug**
Cannot connect to server.

**To Reproduce**

1. Connect to Geyser
2. See error

**Expected behavior**

I want to join the server.

**Screenshots / Videos**

![Screenshot_2020-04-15-23-14-54-517_com mojang minecraftpe](https://user-images.githubusercontent.com/39800107/79390012-3bd2f580-7f6f-11ea-9aa7-28820c183ec0.jpg)

**Server Version**

1.15.2

**Geyser Version**

Jenkins master b44
Jenkins inventory b20

**Minecraft: Bedrock Edition Version**

PE 1.14.60

**Additional Context**

**Comment by RednedEpic** [comment]
> **Describe the bug**
> Cannot connect to server.
> 
> **To Reproduce**
> 
> 1. Connect to Geyser
> 2. See error
> 
> **Expected behavior**
> 
> I want to join the server.
> 
> **Screenshots / Videos**
> 
> ![Screenshot_2020-04-15-23-14-54-517_com mojang minecraftpe](https://user-images.githubusercontent.com/39800107/79390012-3bd2f580-7f6f-11ea-9aa7-28820c183ec0.jpg)
> 
> **Server Version**
> 
> 1.15.2
> 
> **Geyser Version**
> 
> Jenkins master b44
> Jenkins inventory b20
> 
> **Minecraft: Bedrock Edition Version**
> 
> PE 1.14.60
> 
> **Additional Context**

This is because Geyser is not yet compatible with Minecraft Bedrock 1.14.60.

**Comment by donovanh** [comment]
Thank you for producing the (temporary) version for this specific version. We had an automatic update on an iOS device that caused a bit of strife among the natives, but we can use this patched version (of the inventory branch) for now. Your quick work is much appreciated!

**Comment by DoctorMacc** [comment]
Fixed with #364 and #365.

**Comment by Zhwt** [comment]
Got same error, should BE 1.14.30 considered an outdated version? But the README said Geyser should be compatitable with 1.14.*
Using inventory branch build#22.

**Comment by RednedEpic** [comment]
> Got same error, should BE 1.14.30 considered an outdated version? But the README said Geyser should be compatitable with 1.14.*
> Using inventory branch build#22.

Only supports 1.14.60 now. Will update the README and wiki accordingly.

**Comment by Zhwt** [comment]
@RednedEpic Thanks!

**Comment by PaytonPlayz926** [comment]
It still doesnt work for me.

**Comment by RednedEpic** [comment]
> It still doesnt work for me.

Update to Bedrock 1.14.60.

**Comment by PaytonPlayz926** [comment]
It gives me the same error over and over.

**Comment by PaytonPlayz926** [comment]
i am

**Comment by DoctorMacc** [comment]
Please join us on Discord or share the error you are getting.

**Comment by RednedEpic** [comment]
> i am

Please join our Discord server: http://discord.geysermc.org.
