### ISSUE TITLE
Void Death shows as fell from a high place instead of fell out of the world

### ISSUE THREAD

**Issue by RKDUDE02** [GeyserMC/Geyser#3521]
### Describe the bug

When a bedrock client falls into the void on bedrock, they are seen as falling from a high place instead of falling out of the world

### To Reproduce

1. Load the Latest Version of Geyser on a 1.19.1 server with ViaVersion installed
2. Join the server on bedrock, go the the end and jump into the void
3. You will die from fall damage instead of dying from the void

### Expected behaviour

Expected for played to die from the void instead of fall damage

### Screenshots / Videos

[Youtube Video](https://youtu.be/APzzCADkYe8)

### Server Version and Plugins

Server Version: git-Purpur-1744 (MC: 1.19.1)
Plugins (9): EzHomes, floodgate, Geyser-Spigot, LuckPerms, NoEncryption, PrivateMessages, spark, ViaVersion, Voidkeepinv

### Geyser Dump

https://dump.geysermc.org/1kLMhPuthM0iyYjfzHlTHiFetwF4Pfeq

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-29f234d)

### Minecraft: Bedrock Edition Device/Version

1.19.41 on iPhone 11

**Comment by Camotoy** [comment]
My suspected reasoning is that the Bedrock player reports being on the ground due to the void floor. This should be an easy-ish fix.

**Comment by RKDUDE02** [comment]
Just a thought, maybe GeyserMC could detect the player hitting the bedrock floor, and possibly teleport the player through the void floor so that the player keeps falling? I'm not sure if teleporting the player below the void floor is even possible though.

**Comment by Camotoy** [comment]
We already do that.
