### ISSUE TITLE
Potion textures will not be mapped/applied on all potion types.

### ISSUE THREAD

**Issue by ofunny** [GeyserMC/Geyser#3523]
### Describe the bug

Potions with a custom model id and a mapping entry in the geyser_mappings.json will not work with all potion types.

Example: Geyser is not handling custom model mappings for potions of type "WATER" but potion types are currently not supported by Geysers custom item implementation at all and therefore should not matter or otherwise should have a supported/working attribute "type" what could be used in the mapping process. 

### To Reproduce

1. Create a custom texture for a potion and map it via custom model id e.g. 10006
2. Load the res pack on the Geyser server and perform the following commands:

`/minecraft:give <playername> minecraft:potion{Potion:"minecraft:empty",CustomModelData:10006}`
and
`/minecraft:give <playername> minecraft:potion{Potion:"minecraft:water",CustomModelData:10006}`

3. You will notice that the texture will be applied to the "uncraftable" (alias empty) portion only, even if both share the same model id.

### Expected behaviour

Either ignore potion types completely and handle all potion types within the same mapping category equally or add support for potion types within the mapping implementation.

### Server Version and Plugins

This server is running Paper version git-Paper-386 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)
You are running the latest version
Previous version: git-Paper-384 (MC: 1.19.3)

### Geyser Dump

https://dump.geysermc.org/hOtcu4D1lcAzDyz6xe4v27a6LY7hjNmJ

### Geyser Version

2.1.0-SNAPSHOT (git-master-48d7872)

### Additional Context

Minor problem: workaround for plugins like Itemsadder or similar implementations – fall back to "uncraftable" potions, they have no effect and mapping works fine for them.

Notice: "Uncraftable/Empty potion: It is also obtained any time a potion has invalid or missing potion effect tags, and thus serves as a placeholder. "

**Comment by Kas-tle** [comment]
https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/translator/inventory/item/PotionTranslator.java#L51-L52 returns null when the potion is `minecraft:empty` because `EMPTY` is not contained in the `Potion` enum https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/inventory/item/Potion.java#L33-L75, so it eventually works its way down to the `CustomItemTranslator`.
