### ISSUE TITLE
Inventory Craft glitch

### ISSUE THREAD

**Issue by adit4rt** [GeyserMC/Geyser#3526]
### Describe the bug

I have a problem with the crafting UI in inventory looking glitched or like Ghost Touch. i have tried various ways like deleting all plugins and installing geyser only and floodgate, even re-deleting the world still happens. and I also tried on several servers it also looks the same glitch when I want to craft. 

### To Reproduce

1. go inventory 
2. press any item
3. and it looks glitch

### Expected behaviour

this doesn't happen anymore, some of my players are also complaining about this kind of problem

### Screenshots / Videos

[youtube](https://youtu.be/Z21pSuZ4uzc) 
I can't upload videos here

### Server Version and Plugins

Paper version git-paper-386 (MC: 1.19.3)

### Geyser Dump

https://dump.geysermc.org/Q3LXfSAdA8rfLOp0VCkASA3FHOOdlYR6

### Geyser Version

2.1.0-SNAPSHOT (git-master-b8040a1)

### Minecraft: Bedrock Edition Device/Version

Minecraft bedrock edition 1.19.50 Playstore android

**Comment by Kas-tle** [comment]
Could you confirm that this is still an issue in the latest version of Geyser? Also, can you ensure this only happens on your server?

**Comment by onebeastchris** [comment]
Closing this issue due to no further response.
