### ISSUE TITLE
Issue Syncing Written Books... 

### ISSUE THREAD

**Issue by 7Wdev** [GeyserMC/Geyser#3527]
### Describe the bug

It's hard to explain, actually idk why that's happening...
I coded a plugin which is supposed to give the player a written book with pre configurated content inside.

I have to situations:

1) the code works for java, but bedrock sees empty page

2) I change the code so it works with bedrock, but java sees "invalid book tag" 

Maybe it's a book meta related bug. 

### To Reproduce

Just use my plugin, and type /guide.
Or try to code one yourself. 

### Expected behaviour

Both java and bedrock clients to see the same content inside! 

### Screenshots / Videos

Bedrock:
![image-16](https://user-images.githubusercontent.com/45117834/216178884-f38c0074-25ec-4a94-83ef-d87275cae4b6.png)

Java:
![image-10](https://user-images.githubusercontent.com/45117834/216178891-f475ff6d-5aac-4805-93fd-49461fc0c64b.png)

### Server Version and Plugins

Version: papermc 1.19.2
Plugins: https://github.com/7Wdev/ADE-SMP/tree/main/SERVER-CORE/plugins

### Geyser Version

1285 build

### Minecraft: Bedrock Edition Device/Version

1.19.51 bedrock, 1.19.2 java

**Comment by Kas-tle** [comment]
Could you please narrow this down to the specific plugin causing the issue?

**Comment by 7Wdev** [comment]
sure

this is the plugin:
![guidebook-1 0 0](https://user-images.githubusercontent.com/45117834/216356172-3037391f-52dc-4b06-8a03-f612a98d03bb.gif)

Note: After u download it, rename it from .gif to jar.
I just renamed it to .gif sothat github accept it

**Comment by davchoo** [comment]
Here is the NBT tag for the book produced by that plugin:
```
minecraft:written_book{
    display: {
        Name:'{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Guide Book"}],"text":""}'
    },
    pages: [
        '{"extra":[{"text":"gg"}],"text":""}',
        '{"extra":[{"text":"gg"}],"text":""}',
        '{"extra":[{"text":"."}],"text":""}',
        '{"extra":[{"text":"."}],"text":""}'
    ],
    title:"Blank"
}
```
Java edition considers this tag as invalid because it is missing an `author` string tag.
Geyser and Bedrock edition does not do any validation for this and will display the pages.

Can you please send the NBT tag of the book that "works for java, but bedrock sees empty page" with `/paper dumpitem`?

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps, specifically, the output of `/paper dumpitem`.
