### ISSUE TITLE
kicking bedrock only

### ISSUE THREAD

**Issue by CoolGunner** [GeyserMC/Geyser#3532]
### Describe the bug

it seems to be only for bedrock players that get kicked when they pvp 

plugins  AntiPopup, BeastTokens, BetterRTP, BlueSlimeCore (SirBlobmanAPI, SirBlobmanCore, XSeries), ChatSentry, Citizens, CMILib, CommandAlias, CoreProtect, CraftingStore, CrazyEnvoys, DailyRewards, DeluxeMenus, DiscoArmor, DiscordSRV, DisplayShops, EpicRename, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, ezAuctions, EZColors, FarmControl, FastAsyncWorldEdit (WorldEdit), floodgate, GeyserHacks, Guilds, HolographicDisplays, Infiniteannouncements, Jackpot, Jobs, LiteBans, LuckPerms, mcMMO, MineableSpawners, Multiverse-Core, NexEngine, PlaceholderAPI, PlayerWarps, PortableBeacons, ProtectionStones, ProtocolLib, PvPManager, Quests, Scyther, Sellwand, ShopGUIPlus, spark, TAB, TempFly, Themis, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, Vouchers, WorldGuard, zKoth 

also yes i disabled the glow on pvpmanger and the thing that says combat tag above there name

**- [Wed 01:55:18 ERROR Minecraft/PlayerConnectionUtils] Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInUseEntity@59e6159d for .Lovehate212 java.lang.IllegalStateException: Unregistered scoreboard component     at org.bukkit.craftbukkit.v1_19_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:403)     at org.bukkit.craftbukkit.v1_19_R1.scoreboard.CraftTeam.allowFriendlyFire(CraftTeam.java:154)     at net.minecraft.world.entity.player.Player.canHarmPlayer(Player.java:1013)     at net.minecraft.server.level.ServerPlayer.canHarmPlayer(ServerPlayer.java:1065)     at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1035)     at net.minecraft.world.entity.player.Player.attack(Player.java:1331)     at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2095)     at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2985)     at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.d**

### To Reproduce

when bedrock players pvp each other

### Expected behaviour

for players not to be kick and enjoy pvping 

### Server Version and Plugins

i run gesyer on my proxy

### Geyser Dump

https://dump.geysermc.org/sGRHdrk8pPd6g8IjnRkmMU6UoHMqi8UC

### Geyser Version

2.1.0-SNAPSHOT (git-master-af5d03f)

### Minecraft: Bedrock Edition Device/Version

1.19.51

**Comment by CoolGunner** [comment]
sorry first time ever filling out one of these kinda new to it  so dont mind if this looks horrbie

**Comment by Camotoy** [comment]
This probably isn't cause by one of our plugins. Can you try these debugging steps?

If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
- Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by CoolGunner** [comment]
ok i will take a look in it and see and will let you know

**Comment by onebeastchris** [comment]
Is this resolved?

**Comment by CoolGunner** [comment]
Ya

Sent from my iPhone

On Apr 24, 2023, at 7:32 PM, onebeastchris ***@***.***> wrote:

﻿

Is this resolved?

**Comment by onebeastchris** [comment]
Great! then please close this issue ;)
