### ISSUE TITLE
Team Nametags Not Always Showing Up

### ISSUE THREAD

**Issue by ItzFlipp** [GeyserMC/Geyser#3537]
### Describe the bug

Ever since build 1290 (which was a build with the changelog "Remove players from player team map on team remove"), player nametags for Bedrock players sometimes show as the default vanilla nametag instead of the custom nametag. 

### To Reproduce

1. Install build 1290 or above of Geyser
2. Install TAB on the backend server
3. Turn unlimited nametags off in TAB's config
4. Create a custom nametag with TAB
5. Join on Bedrock edition

### Expected behaviour

It is expected to show the custom nametag at all times.

### Screenshots / Videos

Here is a screenshot of the nametag bugging out on Bedrock edition. You can see here that some custom nametags show, but others do not. https://imgur.com/a/K792zPJ

Here is a screenshot from a Java account indicating that the custom nametag is actually there: https://i.imgur.com/sily4se.png

### Server Version and Plugins

Backend: git-Purpur-1906 (MC: 1.19.3)
Proxy: git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:a24c106:158

### Geyser Dump

https://dump.geysermc.org/Qq3SyQflKnNE1SzgMnwVIEvZs4Loke5M

### Geyser Version

2.1.0-SNAPSHOT (git-master-0bba18c)

### Minecraft: Bedrock Edition Device/Version

iOS, Windows 10

### Additional Context

Any Geyser version below build 1289 does not have this issue.

**Comment by Camotoy** [comment]
Build 1289 works fine though?

**Comment by ItzFlipp** [comment]
> Build 1289 works fine though?

1289 is broken too. Anything below that is fine.
