### ISSUE TITLE
Geyser Invalid packet error

### ISSUE THREAD

**Issue by MatinDark** [GeyserMC/Geyser#3538]
### Describe the bug

I am using Geyser with Floodgate, I enabled `enable-proxy-connections` and when a player tries to connect it throws an insane amount of errors in the console and the player fails to connect

Server log: https://paste.ubuntu.com/p/gtbYCF4c8G/ (I also had debug mode enabled for precise logging)

### To Reproduce

1. Put latest GeySer build in plugins folder
2. Put latest FloodGate build in plugins folder
3. Open GeySer configuration file and set  `enable-proxy-connections`  to `true`
4. Try to connect to server and you see those errors

### Expected behaviour

Players should be able to connect and also plugin should not throw any error

### Screenshots / Videos

![Screenshot_20230207-220854_Minecraft](https://user-images.githubusercontent.com/22664859/217341444-ab57b23f-1513-4c4f-8c28-fd7639ca9dad.jpg)
![photo_2023-02-07_22-36-34](https://user-images.githubusercontent.com/22664859/217341489-8dcafeab-ddd6-4592-b2ad-27bb25834222.jpg)

### Server Version and Plugins

Velocity Version: Velocity 3.1.2-SNAPSHOT (git-8deb0ff7-b198)

Velocity Plugins:
ajqueue, chatcensor, chatsentinel, commandforward, forcepack, geyser, grandmoderation, limboapi, limboauth, limbofilter, litebans, luckperms, protocolize, pl-hide-pro, plan, serverlistplus, serverutils, skinsrestorer, velocity_playtime, velocity_tools, velocitycontrol, velocityreport, velocityvanish, velocitywhitelist

### Geyser Dump

https://dump.geysermc.org/Gz8DI7aioJ8qwiZ2W6YZpA6nUxyvoAf9

### Geyser Version

This server is running Geyser version 2.1.0-SNAPSHOT (git-master-0bba18c) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.60)

### Minecraft: Bedrock Edition Device/Version

Beta 1.19.40.24 and 1.19.20

### Additional Context

Also did little digging by my self what throwing error is at https://github.com/GeyserMC/PacketLib/blob/master/src/main/java/com/github/steveice10/packetlib/tcp/TcpPacketCodec.java

line 65

**Comment by Camotoy** [comment]
You should disable `enable-proxy-connections` unless you're using WaterdogPE or ProxyPass (you very very likely aren't using the latter). Otherwise, update your Limbo plugins.

**Comment by MatinDark** [comment]
> You should disable `enable-proxy-connections` unless you're using WaterdogPE or ProxyPass (you very very likely aren't using the latter). Otherwise, update your Limbo plugins.

I did as you instructed but still getting error, I did update limbo plugins also updated velocity to latest build
now I am getting

https://paste.ubuntu.com/p/hc2PgCprYG/

**Comment by Camotoy** [comment]
You are probably trying to log into Geyser with a cracked Bedrock installation. We do not offer support in such instances; an Xbox account is free.
