### ISSUE TITLE
Can't Join to server (Villager Data error)

### ISSUE THREAD

**Issue by Ruymanphone** [GeyserMC/Geyser#354]
Describe the bug
Error in join

To Reproduce

1. Try to join in your server

Expected behavior
Don't have problems

Server version
Paper 184 (1.15.2)+Waterfall 327 with ViaVersion

Geyser version
Master 44

Bedrock version
1.14.30 (I tried in W10)

![Aldeanos](https://user-images.githubusercontent.com/24842739/79405545-a0507d80-7f8c-11ea-8711-b01232735054.png)

**Comment by RednedEpic** [comment]
> Describe the bug
> Error in join
> 
> To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Try to join in your server
> 
> Expected behavior
> Don't have problems
> 
> Server version
> Paper 184 (1.15.2)+Waterfall 327 with ViaVersion
> 
> Geyser version
> Master 44
> 
> Bedrock version
> 1.14.30 (I tried in W10)
> 
> ![Aldeanos](https://user-images.githubusercontent.com/24842739/79405545-a0507d80-7f8c-11ea-8711-b01232735054.png)

Did you compile this yourself?

**Comment by Ruymanphone** [comment]
No, I downloaded it in https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/

**Comment by DoctorMacc** [comment]
Unable to replicate with Paper 184 and the latest master Geyser.

**Comment by Ruymanphone** [comment]
I have suffered this bug since 35, but I have come to complain now because they still have not solved it and I have downloaded the geyser bungee and bukkit multiple times xdddd

**Comment by DoctorMacc** [comment]
Can you try without Waterfall? What plugins are you running?

**Comment by Ruymanphone** [comment]
I just did a test only with paper and without plugins, still without leaving me

**Comment by RednedEpic** [comment]
Unable to reproduce. The class is present in the latest version from master, meaning that your error is likely a result of an incomplete download or a file transfer issue.
![image](https://user-images.githubusercontent.com/29153871/79495603-74fc7b80-7fea-11ea-9116-561f4ed0efb9.png)
