### ISSUE TITLE
 Steve skin appears client side

### ISSUE THREAD

**Issue by TheGodPancake** [GeyserMC/Geyser#3540]
### Describe the bug

Steve skin appears client side, but to everyone else on the server the skin is normal.

### To Reproduce

Login to server on bedrock with new geyser update go into third person mode to see

### Expected behaviour

For Steve skin to appear

### Geyser Version

#1295

### Minecraft: Bedrock Edition Device/Version

Mobile, ps4

**Comment by Camotoy** [comment]
This appears to be a client bug as of 1.19.60.

**Comment by LinkexaHy** [comment]
when will this be fixed?

**Comment by Camotoy** [comment]
We have to wait for Bedrock to fix it. When that will happen, we don't know.

**Comment by LinkexaHy** [comment]
What caused it to stop working though

**Comment by Camotoy** [comment]
We don't know for sure. The client will only accept back its own skin file - we may be able to patch things to get that working, but as for other skins, we don't really have answers.

**Comment by LinkexaHy** [comment]
Well, everyone else can see my skin, but I cannot. So, the game just isnt detecting the skin file even though it's working on realms and bedrock-only servers

**Comment by neco222** [comment]
Is it reflected in the eyes of others?

**Comment by JimmySallofficial** [comment]
> We don't know for sure. The client will only accept back its own skin file - we may be able to patch things to get that working, but as for other skins, we don't really have answers.

I would report it myself on Mojang but you for sure know more about this from me so if you haven't already do you have any suggestions of what to type in the report?

**Comment by Camotoy** [comment]
1.19.62 should resolve this issue.
