### ISSUE TITLE
Bamboo Placement

### ISSUE THREAD

**Issue by Noradith** [GeyserMC/Geyser#3545]
### Describe the bug

Entities like bamboo do not show in the same spots on bedrock as java causing rubberbanding when walking through bamboo.

### To Reproduce

When bedrock players walk through tightly placed bamboo they get rubberbanding as how they see bamboo in a different place than the java server.

### Expected behaviour

Should be able to smoothly walk through it in both versions.

### Screenshots / Videos

![java view](https://user-images.githubusercontent.com/125026283/218069469-2fc42abc-7383-4128-b85c-95bb6ff96d64.png)
![bedrock view](https://user-images.githubusercontent.com/125026283/218069532-b073729a-69b4-4ea2-b278-9d073021124a.png)

### Server Version and Plugins

1.19.3,  java
floodgate
gyser

### Geyser Version

https://github.com/GeyserMC/Geyser/commit/9b3b2fba17ab6cbe621c016ebb01ab94ebbe77f0

### Minecraft: Bedrock Edition Device/Version

xbox one x 1.19.50

**Comment by onebeastchris** [comment]
Known bug, but workaround possible with the followong [plugin](https://github.com/Camotoy/GeyserHacks) installed

**Comment by Camotoy** [comment]
Thanks anyway for reporting!
