### ISSUE TITLE
Equipped Player Heads in 3rd Person

### ISSUE THREAD

**Issue by abyss-xd** [GeyserMC/Geyser#3548]
### Describe the bug

When you equip a player head as a helmet, it no longer shows the texture in 3rd person. GeyserMC added support for this back in November 2021, but I guess some commit broke this and very few noticed.

There's a few important details to note:
1. When you equip it, it shows the texture in the inventory player model, but when you reopen inventory, it doesn't show.
2. When you equip, unequip or change any other armor pieces, it shows it again, but when you reopen the inventory, it doesn't show it.
3. Obivously it doesn't show in 3rd person either, as if the texture gets cancelled a tick after equipping the head or smth.

### To Reproduce

1. Get a custom textured player head
2. Wear it

### Expected behaviour

That the head shows texture on 3rd person.

As per built -> https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/932/
and commit -> https://github.com/GeyserMC/Geyser/commit/798f8da573d7356898f217f3bd96bc27c22836c9

### Screenshots / Videos

https://www.youtube.com/watch?v=5vv-uHO4Zh4

### Geyser Version

Build #1299

**Comment by Camotoy** [comment]
See https://github.com/GeyserMC/Geyser/issues/3540; we can't fix this on our end.

**Comment by onebeastchris** [comment]
I've had this issue happen on pre-1.19.60, so this isn't necessarily related
