### ISSUE TITLE
Crash when opening inventory in creative mode

### ISSUE THREAD

**Issue by Aeldit** [GeyserMC/Geyser#3549]
### Describe the bug

When I open a chest or a block entity's interface, it works, but when I open the player's inventory the game just crashes (bedrock client, not the server)

### To Reproduce

Setup the server with geyser and floodgate on fabric 1.19.3
Connect to the server (the bedrock account is linked to the java one)
press the key to open inventory

### Expected behaviour

The inventory should be opened (the player's one)

### Screenshots / Videos

I put the link to the video on my google drive because it is too big for github : https://drive.google.com/file/d/14U1I-TOIpTKaYf5ZQfBo31DtUH5vpRgE/view?usp=share_link

On the video you can see that the enderchest is opened as intended, but the inventory crashes when it is the player's one

### Server Version and Plugins

This server is running Geyser version 2.1.0-SNAPSHOT (git-master-9b3b2fb) (Java: 1.19.3, Bedrock 1.19.20 - 1.19.60)

### Geyser Dump

https://dump.geysermc.org/vJWyWCbAkW4sQkOn8jQShjoMINIjZnq

### Geyser Version

2.1.0-SNAPSHOT (git-master-9b3b2fb)

### Minecraft: Bedrock Edition Device/Version

1.19.60 Windows 11

**Comment by rtm516** [comment]
Could you provide the players inventory dat file from the server?

**Comment by Aeldit** [comment]
Where do I find it ?

**Comment by Aeldit** [comment]
Nevermind I found them, here they are 
[Players inventory.zip](https://github.com/GeyserMC/Geyser/files/10714106/Players.inventory.zip)

**Comment by Camotoy** [comment]
I was unable to replicate with the supplied .dat file. Perhaps it's another mod?

**Comment by Aeldit** [comment]
Ok I'll investigate this this weekend

**Comment by Aeldit** [comment]
I removed every mods except Geyser, floodgate and the fabric API and it still crashes (I then updated geyser to the latest version, from Feb 17 23:55 #1305 and it still crashed without any other mod)

**Comment by Camotoy** [comment]
Hmm. Can you send a datapack with this tag?

**Comment by Aeldit** [comment]
Yep, here they are. You can find the concerned files in `data\coal_to_dye\advancements\recipes\misc\coal_to_dye` for the advancement and in `data\coal_to_dye\recipes` for the recipe (in both files)
[VanillaTweaks_crafting_crashing.zip](https://github.com/GeyserMC/Geyser/files/11065270/VanillaTweaks_crafting_crashing.zip)

[VanillaTweaks_crafting.zip](https://github.com/GeyserMC/Geyser/files/11065298/VanillaTweaks_crafting.zip)
