### ISSUE TITLE
Add command /geyser ping

### ISSUE THREAD

**Issue by bddjr** [GeyserMC/Geyser#3552]
### What feature do you want to see added?

Add command `/geyser ping` ,then bedrock client use this command ping geyser.

### Are there any alternatives?

It seems that the existing simulation method cannot be used to replace this instruction

**Comment by Konicai** [comment]
Do you just want to know the latency between the client and Geyser?

**Comment by bddjr** [comment]
> 您只想知道客户端和间歇泉之间的延迟吗？

yes

**Comment by onebeastchris** [comment]
Implemented in https://github.com/GeyserMC/Geyser/pull/4862
