### ISSUE TITLE
 Kenshins Hide and Seek 1.7.2 support for the plugin. 

### ISSUE THREAD

**Issue by IndulgeinDotNet** [GeyserMC/Geyser#3553]
### What feature do you want to see added?

the plugin doesnt load any gui where you can pick the blockhunt block and bedrock players cant see the blocks that java players are as they are invisible.

### Are there any alternatives?

disabling the blockhunt feature makes everything work perfectly

**Comment by Camotoy** [comment]
Please re-open this issue as a bug report. Thank you!
