### ISSUE TITLE
Parts of the map missing

### ISSUE THREAD

**Issue by clubjustin** [GeyserMC/Geyser#3555]
### Describe the bug

Some parts of the map are missing while traveling.

### To Reproduce

1. Join the server.
2. Fly around for a bit.
3. See that the chunks are not loading.

### Expected behaviour

For the chunks to load.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/117137254/218860992-8bce3390-c0e7-461b-9e55-5a239f5cdf37.png)

### Geyser Dump

https://dump.geysermc.org/y58Wk15gGZZBp6wLqp5ejznO4FngESm9

### Geyser Version

2.1.0-SNAPSHOT (git-master-f9705c1)

### Minecraft: Bedrock Edition Device/Version

Windows, and iOS

**Comment by Camotoy** [comment]
Do the chunks reappear after relog?

**Comment by Kas-tle** [comment]
This is the same bug as introduced by valaphees PR I believe... the mitigation I proposed does not seem to work pre 1.18 for some reason.

**Comment by clubjustin** [comment]
> Do the chunks reappear after relog?

Yes

**Comment by Camotoy** [comment]
This should now be fixed in the latest build. Let us know otherwise.
