### ISSUE TITLE
Can't get UUID from offline players that have Spaces/Underscores on their names.

### ISSUE THREAD

**Issue by yLordMagnus** [GeyserMC/Geyser#3556]
### Describe the bug

I mean, it is possible to get it, but it is a gamble.

Suppose my GamerTag is `yLorD Magnus`, geyser/floodgate converts to `-yLorD_Magnus`

If I'm offline and try to use the FloodGateAPI (as dependency of my plugin)/GeyserAPI (https://api.geysermc.org/) at max I can filter out the prefix `-`, ending up with `yLorD_Magnus` but then, since the UUID retrieval for offline players is based on the original GamerTag I have no way of knowing if the original GamerTag was `yLorD Magnus` or `yLorD_Magnus`, one will work, the other will just spit out an error or I might get the wrong profile.

This problem can get bigger and bigger depending on the amount of underscores/spaces the original gamertag had.

### To Reproduce

1. Gamble?

### Expected behaviour

1. Getting the player UUID 100% and not gamble.

### Geyser Version

2.1.0-SNAPSHOT (git-master-f9705c1)

**Comment by onebeastchris** [comment]
well, what you're describing though is an inherent gamble
How is the Geyser API supposed to know whether a player where the _ replacement, that coincides with another exact same java username, is or isn't a Bedrock player?
Without the prefix, there is no way to tell that. heck, it's why it's even there, to avoid such username issues

I really don't see how we're supposed to "guess" without the prefix

**Comment by onebeastchris** [comment]
https://api.geysermc.org/docs#/utils/GlobalApiWeb.Api.UtilsController.get_bedrock_or_java_uuid
However, if you use this endpoint *with the prefix*, you should probably get the correct UUID.

**Comment by yLordMagnus** [comment]
> https://api.geysermc.org/docs#/utils/GlobalApiWeb.Api.UtilsController.get_bedrock_or_java_uuid However, if you use this endpoint _with the prefix_, you should probably get the correct UUID.

it only filters out the prefix, it is unable to know if the underscores are indeed part of the gamertag or if they were introduced by Geyser

**Comment by yLordMagnus** [comment]
> I really don't see how we're supposed to "guess" without the prefix

Huh, I don't get what you are talking about here, that doesn't seem to be the same thing I mentioned on my post

**Comment by onebeastchris** [comment]
> > https://api.geysermc.org/docs#/utils/GlobalApiWeb.Api.UtilsController.get_bedrock_or_java_uuid However, if you use this endpoint _with the prefix_, you should probably get the correct UUID.
> 
> it only filters out the prefix, it is unable to know if the underscores are indeed part of the gamertag or if they were introduced by Geyser

From what I can tell it (that particular endpoint) uses the prefix to make a proper guess about if that's java or bedrock, and returns either a floodgate UUID for bedrock, and UUID for java players. Underscores shouldn't matter at all in that endpoint.

**Comment by onebeastchris** [comment]
> > I really don't see how we're supposed to "guess" without the prefix
> 
> Huh, I don't get what you are talking about here, that doesn't seem to be the same thing I mentioned on my post
> 

Let's ask it differently then, why are you filtering out the prefix before calling the Geyser API endpoint?

**Comment by yLordMagnus** [comment]
> Let's ask it differently then, why are you filtering out the prefix before calling the Geyser API endpoint?

I'm not...
![14_23-28-19_NUiwk](https://user-images.githubusercontent.com/20267487/218912034-f46b8691-32c1-48bb-a306-9285d96f6f7d.png)

![14_23-28-29_BVWi6](https://user-images.githubusercontent.com/20267487/218912033-def99b2f-d676-4cfb-9197-563dc17c727a.png)

my gamertag is `yLorD Magnus` but since Geyser converts my name on the game to `yLorD_Magnus` it just errors out...

**Comment by onebeastchris** [comment]
Okay, now that is a likely a bug with that endpoint; it should probably replace all underscores back to spaces if there's a prefix present

Then again, you could probably get away with checking if there's a prefix, and if there is, replace the "_" in the name to a space; and then call that endpoint. That should work as I don't think Xbox live allows for "_" in their usernames

Aka:
if (prefix present){
string.replace("_","")
callgeyserapi
}
if it's not present, you can call that endpoint directly

**Comment by yLordMagnus** [comment]
> Okay, now that is a likely a bug with that endpoint; it should probably replace all underscores back to spaces if there's a prefix present
> 
> Then again, you could probably get away with checking if there's a prefix, and if there is, replace the "_" in the name to a space; and then call that endpoint. That should work as I don't think Xbox live allows for "_" in their usernames

For some reason I was certain that I had already seen GamertTags with underscores, guess I was just wrong, after searching a bit about it, it doesn't seem to be possible to use underscores on gamertags, and I was just being stupid af, sorry bout that >.>
