### ISSUE TITLE
Sounds half updated

### ISSUE THREAD

**Issue by TomyGamy** [GeyserMC/Geyser#3557]
### Describe the bug

Minecraft Bedrock 1.19.60 update brought us new sound from Minecraft Java Edition for those things:
- Wooden (including Nether wood type) and Iron Doors
- Wooden (including Nether wood type) and Iron Trapdoors
- Fence gates (including Nether wood type)
- Wooden, stone and metal Pressure Plates
But joining a server with geyser removes those new sounds and uses:
- Wooden (including Nether wood type) and Iron Doors -> Old regular door sound
- Wooden (including Nether wood type) and Iron Trapdoors -> Old regular door sound
- Fence gates (including Nether wood type) -> Old regular door sound
- Wooden, stone and metal Pressure Plates -> regular Minecraft Click sound

For some reasons, Buttons, Nether wood type placing, breaking and walking works

### To Reproduce

Step on pressure plates
Open/close doors, trapdoors and fence gates

### Expected behaviour

Expected sounds should be:
- Wooden doors  -> play regular wood door sound
- Iron door  -> play Iron door sound
- Nether wood doors  -> play Nether wood door sound

- Wooden trapdoors  -> play regular wood trapdoor sound
- Iron trapdoor-> play Iron trapdoor sound
- Nether wood trapdoors -> play Nether wood trapdoor sound

- Wooden fence gates -> play regular fence gate sound
- Nether wood fence gates -> play Nether wood fence gate sound

- Wooden pressure plates -> play wood_click
- Nether wood pressure plates -> play nether_wood_button
- Stone pressure plates -> play their actual sound but low pitch
- Metal pressure plates -> play their actual sound but hight pitch

### Server Version and Plugins

Paper version git-Paper-399 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f2f9e8c)

Plugin List:
- BedrockSkinUtility-1.4.0
- BetterTridents-2.2.2
- debuginfo-be
- FallingSnow
- FireAspectPlusPlus
- floodgate-spigot
- GeyserHacks
- Geyser-Spigot
- lssmp-2.3.14
- MineTweaks-1.8.2
- SimpleArmorStandPose-2.0
- ViaBackwards-4.5.1
- ViaVersion-4.5.1

### Geyser Dump

 https://dump.geysermc.org/OLb2LauxVnMZsonvhvjffGBTx9WdTbw6

### Geyser Version

2.1.0-SNAPSHOT (git-master-f9705c1) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.60)

### Minecraft: Bedrock Edition Device/Version

1.19.60, Windows 10/11 and Android

**Comment by Konicai** [comment]
> For some reasons, Buttons, Nether wood type placing, breaking and walking works  

Likely due to the client handling these sounds itself

**Comment by TomyGamy** [comment]
> > For some reasons, Buttons, Nether wood type placing, breaking and walking works
> 
> Likely due to the client handling these sounds itself

still not working with direct player interraction (right click) but works with redstone interaction...
