### ISSUE TITLE
Namespaced GeyserMC command visible even with send-namespaced: false

### ISSUE THREAD

**Issue by TheNicestDev** [GeyserMC/Geyser#3559]
### Describe the bug

Even with `send-namespaced: false` the namespaced geyser command (`/geyser-spigot:geyser`) is visible

### To Reproduce

1. Go into the `spigot.yml` file
2. Change `send-namespaced` to `false`: 
```yml
commands:
  send-namespaced: false
```
3. Restart the Server

### Expected behaviour

Normally only the `/geyser` command should then be visible, but the namespaced command (`/geyser-spigot:geyser`) is still visible.

### Screenshots / Videos

![Geyser Command](https://cdn.discordapp.com/attachments/1075483187637125151/1075483187947524126/image.png)

### Geyser Dump

https://dump.geysermc.org/37uY4QdgxZoOLdMgq4zUs5hMqTiVv94E

### Geyser Version

2.1.0-SNAPSHOT (git-master-9b3b2fb)

**Comment by onebeastchris** [comment]
https://github.com/PaperMC/Paper/pull/9366 this appears to be a bug within paper; dont think there is much we can do to address this on our side :/

**Comment by onebeastchris** [comment]
Confirmed in the [paper discord](https://ptb.discord.com/channels/289587909051416579/555462289851940864/1137501279267070142); this isnt a bug that can be addressed on Geyser's side - you'll have to wait for the pr linked above, or use some plugin that hides them. Thanks for reporting anyways!

**Comment by onebeastchris** [comment]
https://github.com/PaperMC/Paper/commit/d928dda91d9ada673cdf48a42f0aa723d0c69052 this is now fixed in paper :p
