### ISSUE TITLE
Connection Closed on Velocity

### ISSUE THREAD

**Issue by e-splat** [GeyserMC/Geyser#3561]
### Describe the bug

When a Bedrock Player joins the Proxy, it gives Connection Closed

### To Reproduce

1. Go to the Bedrock Server List
2. Add the Server to the list
3. Join in

### Expected behaviour

Let me join

### Screenshots / Videos

![immagine](https://user-images.githubusercontent.com/82027617/219717800-d4dbfbde-7bdc-4dca-834c-58e681546fcd.png)

### Server Version and Plugins

Velocity 3.2.0-SNAPSHOT (git-697d08ba-b216)

Plugins on it:
![immagine](https://user-images.githubusercontent.com/82027617/219718518-c308b832-3292-45c9-b72a-91024415f01c.png)
Note: on Snap there are Botsentry, EnderSS, PebbleAntiVPN and TitanGuard

### Geyser Dump

https://dump.geysermc.org/IoAqPcWRdasjpSltFOmw3iDvCWt1mCHi

### Geyser Version

2.1.0-SNAPSHOT (git-master-406dfcb)

### Minecraft: Bedrock Edition Device/Version

1.19.60, Windows 11

**Comment by Camotoy** [comment]
Try removing TCPShield temporarily?

**Comment by e-splat** [comment]
i fixed changing an option in the tcpshield config
