### ISSUE TITLE
[Feature Suggestion] Auto-Updaye

### ISSUE THREAD

**Issue by LinkexaHy** [GeyserMC/Geyser#3562]
### What feature do you want to see added?

Adding auto updates would make it easier for those who enable auto update so they dont have to pull the latest build by going to the repos for it. This should be same for Floodgate too!

### Are there any alternatives?

N/A

**Comment by onebeastchris** [comment]
https://www.spigotmc.org/resources/geyserupdater.88555/
This is already possible with this plugin - as for Geyser auto-updating itself, that's not something that's likely to come due to security concerns

**Comment by Konicai** [comment]
Yeah, we have actively decided against such a feature within Geyser (for reasons Chris described).

Geyser will essentially come with Floodgate in the near future, which will make it easier to update.
