### ISSUE TITLE
Ping inaccurate getting

### ISSUE THREAD

**Issue by b1zey** [GeyserMC/Geyser#3563]
### Describe the bug

I enable forward-player-ping and try to get player ping via player.getPing and i get inaccurate values like 300 ms up to 5000 ms.
Sometimes it returns correctly ping but more often it returns inaccurate ping.

### To Reproduce

1.Download latest geyser
2.Try to player.getPing every second and watch for returned values in console. 

### Expected behaviour

I expected a correctly ping

### Geyser Version

latest

**Comment by Konicai** [comment]
Stale and very little information given - `forward-player-ping` has recently been refactored, so try updating.
