### ISSUE TITLE
Sign GUI Translation

### ISSUE THREAD

**Issue by BinaryBible** [GeyserMC/Geyser#3565]
### Describe the bug

Search does not function on console versions of game.

### To Reproduce

* Be on Bedrock *
Open an Advanced Chest
Move "Search" icon to another slot
Nothing happens

### Expected behaviour

Open Advanced Chest
Move "Search" icon to another slot
Prompt to request search term be entered on sign

### Screenshots / Videos

https://user-images.githubusercontent.com/41652148/219977997-989a0ecc-bb90-47bf-859f-f41349638f0d.mp4

### Server Version and Plugins

AdvancedChests
Essentials
WorldGuard
GadgetsMenu
Lootcrate
Shops
Astools
Announcer
Towny
Chestshop
DecentHolograms
Geyser
Map
InventoryRollback+
Brewery
Command Timer
Core Protect
DH
Jobs
Marry
mcMMO
Mythic Mobs
PA
Crates
Skript
Trade+
Voting Plugin

### Geyser Dump

https://dump.geysermc.org/UCINWww0H1DtAwvfA1UtfPY4OcqDX0Dk

### Geyser Version

2.1.0-SNAPSHOT (git-master-e7b8b4e)

### Minecraft: Bedrock Edition Device/Version

1.19.62, Samsung Galaxy S22 Ultra 5G

### Additional Context

Java Players are able to utilize sign gui

**Comment by Camotoy** [comment]
Unfortunately, we cannot fix this, as Bedrock does not allow signs to be opened server-side. Our recommendation would be to try replacing the search functionality with a Bedrock form. Thanks anyway for reporting.
