### ISSUE TITLE
Skulls having weird rendering issues

### ISSUE THREAD

**Issue by shadowtigercool** [GeyserMC/Geyser#3566]
### Describe the bug

Skull Rendering Issues, Having weird torso and arms

### To Reproduce

1. Place Down A Skull
2. Look

### Expected behaviour

Torso, And No Legs, rendering issues

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/36507966/220029226-c7d07d3a-2e46-435c-8e50-cf3397be41da.png)

### Server Version and Plugins

Paper version git-Paper-"4da844f" (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)

ArmorStandEditor, ArtMap, BannerMaker, BetterCommandSpy, BKCommonLib, ChatReaction ,ChestCommands, Clearlag, CoreProtect , Essentials , EssentialsChat , EssentialsGeoIP, EssentialsSpawn, FastAsyncWorldEdit (World Edit) , Floodgate, FreedomChat, Geyser-Spigot, Gsit , LuckePerms, Multiverse-Core, PL-Hide, PlotSquared, ProtocolLib, Skulls , Vault , VotifierPlus, VotingPlugin And WorldGuard

### Geyser Dump

https://dump.geysermc.org/KU2AKzlHrM4QltH4jmLdsoIzImYtWfsN

### Geyser Version

2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.60-1.19.62 (Tablets, Consoles, Windows Edition)

**Comment by purejosh** [comment]
I'm also having this issue. I can help test or fix, if needed. I'm running geyser on a velocity proxy.

**Comment by Camotoy** [comment]
Are there any notable logs when you enable `debug-mode` in Geyser's config, restart, then try loading the skulls?

**Comment by onebeastchris** [comment]
Does the issue still occur on the latest version of Geyser?
