### ISSUE TITLE
stuck in snow 

### ISSUE THREAD

**Issue by onebeastchris** [GeyserMC/Geyser#3568]
### Describe the bug

snow layers can cause rubberbanding in scenarios when the client attempts to "go up" to the higher block (auto jump off).
see attached video for details

### To Reproduce

1. place snow layers (3 or more) 
2. attempt to walk over them to get to a block that's +1 from the initial block
3. et voilà

### Expected behaviour

no lagback

### Screenshots / Videos

https://youtu.be/31kmZWu6aNc

### Server Version and Plugins

1.19.3 fabric, velocity build 229.
Also seen reports of it on other geyser versions, not just velocity

### Geyser Dump

https://dump.geysermc.org/7cOPExE0tEmaxjA96fe200FaPMJSE6CQ

### Geyser Version

geyser-velocity; #1305

### Minecraft: Bedrock Edition Device/Version

1.19.40 - 1.19.62

**Comment by TBYT** [comment]
Fixed in Bedrock 1.20.30.
You can now auto sprint over 5 layer high snow to a full block without lag back.
- vanilla parity
- - (blocks)
https://feedback.minecraft.net/hc/en-us/articles/19545277817357-Minecraft-1-20-30-Bedrock 


https://bugs.mojang.com/browse/MCPE-60024

**Comment by TBYT** [comment]
It is worth noting there is still the snow and soul sand crawling bug that is patched in bedrock 1.20.30 but still present in Geyser servers. https://bugs.mojang.com/browse/MCPE-170994
except on geyser, lagback occurs whilst being stuck unless you open the trap door or destory the slab you get stuck under.

**Comment by onebeastchris** [comment]
The crawling bug might be resolved once Geyser implements Bedrock native crawling properly - in the meantime, feel free to open a bug report :p
Thanks for the testing done - I'll close this as completed.

**Comment by TBYT** [comment]
> The crawling bug might be resolved once Geyser implements Bedrock native crawling properly - in the meantime, feel free to open a bug report :p Thanks for the testing done - I'll close this as completed.

i will open a bug report because I also found another bug.
