### ISSUE TITLE
Internal Exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by NFKRZZ** [GeyserMC/Geyser#3571]
### Describe the bug

whenever i connect with geyser and floodgate installed I get java.lang.NullPointerException on connect.

### To Reproduce

1. Have fresh install of geyser and floodgate
2. Run server
3. join server from bedrock.

### Expected behaviour

It shouldnt kick me.

### Server Version and Plugins

This server is running Paper version git-Paper-"f2f9e8c" (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: f2f9e8c)

Plugins (94): AdvancedEnchantments, AdvancedHelp, BKCommonLib, BlockVersion*, BuycraftX, ChatControl, Citizens, ClearLag, CoinFlipper*, CombatLogX, CoreProtect, Craftory, DependencyManager*, Discord*, DiscordSRV, DispenserTools*, DomingIsJew*, Duels, EliteMobs, ElytraCombatLog*, EnvvoyTimer*, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EssentialsXMPP, EventDebugger, ExcellentCrates, Factions, FactionsTop, FakePlayer, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), floodgate, FogusCore, GappleOptions, GenBucket, Geyser-Spigot, GiveAll*, HolographicDisplays, ImmortalTags, InteractiveChat, JellyLegs, KOTH*, KOTHFUUID*, LibsDisguises, LightCleaner, LuckPerms, mcMMO, MessageAnnouncer, MoneyPouch*, Multiverse-Core, MythicMobs, NBTAPI, NexelWilderness, NexEngine, NoteBlockAPI, ObsidianDestroyer*, OldCombatMechanics, OpenInv, Ping, PlaceholderAPI, Plan, PlayerParticles, PlayerVaults, PremiumCreeperEggs, ProtocolLib, ProtocolSupport, Sentinel, ShopGUIPlus, SilkSpawners_v2, SimplePets, SoaromaSAC, spark, Terra, ThrowableCreeperEggs, TitleManager, TNTFill*, TradeSystem, UltraRepair, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, WildBuster, WildStacker, WildTools, WorldBorderPearlBlock*, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV3

### Geyser Dump

https://dump.geysermc.org/NXIXsRK90PqjyhHSCOLS9F3CWnrNPp4H

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-e7b8b4e) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.62)

### Minecraft: Bedrock Edition Device/Version

Android Phone Bedrock Edition 1.19.62

**Comment by Aduhkiss** [comment]
I was having a similar issue on my server too, removing ViaVersion fixed the issue for me, reading the error logs revealed there is a duplicate handler created from some plugin called 'via-encoder'
Here's my error logs incase any dev's see this: https://pastebin.com/G5v3feNX

**Comment by NFKRZZ** [comment]
[21:58:01] [Network Listener - #1/INFO]: [Geyser-Spigot] /172.58.19.138:44248 tried to connect!
[21:58:02] [Network Listener - #3/INFO]: [Geyser-Spigot] Player connected with username Ravinator T100
[21:58:02] [defaultEventLoopGroup-5-2/INFO]: [Geyser-Spigot] Ravinator T100 (logged in as: Ravinator_T100) has connected to the Java server
[21:58:02] [Geyser Spigot connection thread-4-3/INFO]: [floodgate] Floodgate player logged in as .Ravinator_T100 disconnected
[21:58:02] [defaultEventLoopGroup-5-2/INFO]: [Geyser-Spigot] Ravinator T100 has disconnected from the Java server because of Internal Exception: java.lang.NullPointerException

This is what occurs when I try to join

**Comment by onebeastchris** [comment]
If this issue still persists: send a complete latest.log file - get it from the "logs" folder & upload it mclo.gs. Then, share the link here

**Comment by ver151set** [comment]
Happens to me as well. Waterfall - paper setup, also have viaversion

**Comment by onebeastchris** [comment]
@ver151set I'd recommend to check the logs of the backend server (behind the proxy) for errors.
If you need further help, please join our discord server & ask in #support :)

**Comment by onebeastchris** [comment]
Closing due to no further response. If the issue is still occurring with the latest version, please provide a new geyser dump & a full log.
As for the issues in the comments - those are likely issues stemming from other plugins. To verify, see the backend server log for the full error that kicked the player.
