### ISSUE TITLE
Custom Crafting Broken after Last Bedrock Update

### ISSUE THREAD

**Issue by RealFinePoint** [GeyserMC/Geyser#3572]
### Describe the bug

Custom Crafting via CustomCrafting (w/ WolfyUtilities) used to be functional on our server for both Java AND Bedrock players, but following the most recent Bedrock update, Bedrock players are no longer able to craft any custom items, but Java players still can just fine.

### To Reproduce

1. Create a custom crafting recipe with [CustomCrafting](https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-1-16-1-19-free.55883/) on a cross-platform Paper server with Velocity.
2. Attempt to craft the item on a Bedrock platform.
3. Fail.

### Expected behaviour

When a custom crafting recipe is filled out in a table, the custom result appears and can be crafted like a normal item. 

### Screenshots / Videos

Working for Java:
https://user-images.githubusercontent.com/105620526/220808730-c846b0c6-cfa4-4d9d-9660-062c942c34f1.mp4

Not working for Bedrock: 
https://user-images.githubusercontent.com/105620526/220811386-e687a120-25ae-4713-8199-3fd17dcbfc7e.mp4

### Server Version and Plugins

git-Paper-417 (MC: 1.19.3) running from git-Velocity-229 (MC: 1.19.3)

### Geyser Dump

https://dump.geysermc.org/oqnRlPbUfupxtIoEONFNRJM95tpe5ljZ

### Geyser Version

https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1306/

### Minecraft: Bedrock Edition Device/Version

Mobile

### Additional Context

As stated, custom crafting used to work for both Java and Bedrock players (with some exceptions) before the latest Bedrock update by Microsoft. Since that, none of them work at all, even those which worked just fine prior to that update. 

I am not a developer for CustomCrafting nor WolfyUtilities, so I don't know all the specifics for how they make custom recipes. In the past, though, I was able to tell Geyser about issues related to translating the crafting and it was fixed before, so I'm hoping that can happen again. Being a cross-platform server is becoming increasingly difficult and annoying with how unsupportive and random Microsoft is with their updates, and I understand that this is a free service with no obligation to fix issues related to other plugins, but if possible, I'd be delighted to see a solution, thank you.

Attached is the config file for CustomCrafting, as well as the file for the specific recipe demonstrated.
[EnchantingCrystal.zip](https://github.com/GeyserMC/Geyser/files/10809806/EnchantingCrystal.zip)

**Comment by BinaryBible** [comment]
Inability to custom craft has become quite burdensome. Being required to ask Java players to craft custom items on my behalf as a Bedrock user is uncomfortable even as an Admin, regular players may decide to simply not play rather than trust their best items to other players. A fix would be greatly appreciated.

**Comment by Kas-tle** [comment]
Could you please clarify what you mean by the most recent bedrock update? Are you referring to 1.19.62, or 1.19.60 in general?

**Comment by RealFinePoint** [comment]
> 

I believe just 1.19.62, though crafting certain things hasn't worked for a long time.

**Comment by onebeastchris** [comment]
Is this still broken with the latest version of Geyser?

**Comment by onebeastchris** [comment]
Closing due to no response - also, this seems to be working just fine now :)
![image](https://github.com/GeyserMC/Geyser/assets/105284508/955a11dc-9a02-459c-8a27-99a3956acda5)
