### ISSUE TITLE
Bedrock players crash a little after joining party games and playing the games 

### ISSUE THREAD

**Issue by IndulgeinDotNet** [GeyserMC/Geyser#3573]
### Describe the bug

 it takes about 30-60 seconds after the game starts and the bedrock playsers crash

[15:06:18] [Geyser player thread-8-1/WARN]: [Geyser-Spigot] Could not translate packet ClientboundContainerClosePacket
--
719 | java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container (org.geysermc.geyser.inventory.PlayerInventory and org.geysermc.geyser.inventory.Container are in unnamed module of loader 'Geyser-Spigot.jar' @56398d20)
720 | at org.geysermc.geyser.translator.inventory.chest.DoubleChestInventoryTranslator.closeInventory(DoubleChestInventoryTranslator.java:150) ~[Geyser-Spigot.jar:?]
721 | at org.geysermc.geyser.util.InventoryUtils.closeInventory(InventoryUtils.java:119) ~[Geyser-Spigot.jar:?]
722 | at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:41) ~[Geyser-Spigot.jar:?]
723 | at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:34) ~[Geyser-Spigot.jar:?]
724 | at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser-Spigot.jar:?]
725 | at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Spigot.jar:?]
726 | at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
727 | at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
728 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
729 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
730 | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
731 | at java.lang.Thread.run(Unknown Source) ~[?:?]
732 | [15:06:18] [Geyser player thread-8-1/WARN]: java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container (org.geysermc.geyser.inventory.PlayerInventory and org.geysermc.geyser.inventory.Container are in unnamed module of loader 'Geyser-Spigot.jar' @56398d20)
733 | [15:06:18] [Geyser player thread-8-1/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.translator.inventory.chest.DoubleChestInventoryTranslator.closeInventory(DoubleChestInventoryTranslator.java:150)
734 | [15:06:18] [Geyser player thread-8-1/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.util.InventoryUtils.closeInventory(InventoryUtils.java:119)
735 | [15:06:18] [Geyser player thread-8-1/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:41)
736 | [15:06:18] [Geyser player thread-8-1/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:34)
737 | [15:06:18] [Geyser player thread-8-1/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
738 | [15:06:18] [Geyser player thread-8-1/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
739 | [15:06:18] [Geyser player thread-8-1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
740 | [15:06:18] [Geyser player thread-8-1/WARN]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
741 | [15:06:18] [Geyser player thread-8-1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
742 | [15:06:18] [Geyser player thread-8-1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
743 | [15:06:18] [Geyser player thread-8-1/WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
744 | [15:06:18] [Geyser player thread-8-1/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
745 | [15:06:18] [Geyser player thread-8-1/WARN]: [Geyser-Spigot] Could not translate packet ClientboundContainerClosePacket
746 | java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container (org.geysermc.geyser.inventory.PlayerInventory and org.geysermc.geyser.inventory.Container are in unnamed module of loader 'Geyser-Spigot.jar' @56398d20)
747 | at org.geysermc.geyser.translator.inventory.chest.DoubleChestInventoryTranslator.closeInventory(DoubleChestInventoryTranslator.java:150) ~[Geyser-Spigot.jar:?]
748 | at org.geysermc.geyser.util.InventoryUtils.closeInventory(InventoryUtils.java:119) ~[Geyser-Spigot.jar:?]
749 | at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:41) ~[Geyser-Spigot.jar:?]
750 | at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:34) ~[Geyser-Spigot.jar:?]
751 | at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser-Spigot.jar:?]
752 | at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Spigot.jar:?]
753 | at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
754 | at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
755 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
756 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
757 | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
758 | at java.lang.Thread.run(Unknown Source) ~[?:?]

[15:08:47] [defaultEventLoopGroup-6-4/INFO]: [Geyser-Spigot] IndulgeIn has disconnected from the Java server because of Bedrock client timed out
--
796 | [15:08:47] [Geyser Spigot connection thread-9-3/INFO]: [floodgate] Floodgate player logged in as .IndulgeIn disconnected
797 | [15:08:47] [Server thread/INFO]: .IndulgeIn lost connection: Disconnected
798 | [15:08:47] [Server thread/WARN]: Now saving stats of player .IndulgeIn
799 | [15:08:47] [Server thread/INFO]: .IndulgeIn left the game

### To Reproduce

load in server.
join Party games. 
start game 
wait 30-60 seconds
times out

### Expected behaviour

sould have kepped playing the game

### Geyser Dump

https://dump.geysermc.org/MujZLmIJ4oR1P6B1uxNd1bX21fO4lhua

### Geyser Version

2.1.0-snapshot(git-master-e7b8b4e

### Minecraft: Bedrock Edition Device/Version

1.19.62

**Comment by onebeastchris** [comment]
Does the crash still occur in the latest version of Geyser? If yes, send a complete latest.log file, ideally, via mclo.gs
