### ISSUE TITLE
Shield is not working on bedrock

### ISSUE THREAD

**Issue by spacedout3** [GeyserMC/Geyser#3574]
### Describe the bug

It's just as the title says, i go to equip a shield and try and block on bedrock and it doesn't work. My server version is PaperMC 1.19.3.

### To Reproduce

1. set up a 1.19.3 paper server
2. join on bedrock edition (update: Just checked, java doesn't have this issue)
3. craft a shield
4. equip said shield
5. try and block
6. notice that it doesn't work

### Expected behaviour

I expected to be able to block

### Server Version and Plugins

Version: 1.19.3 paper MC

Plugins:
Geyser
Floodgate

Lifesteal: https://www.spigotmc.org/resources/lifesteal.105511/
Magic bag: https://www.spigotmc.org/resources/magic-bag.105656/
UltimateAutoRestart: https://www.spigotmc.org/resources/1-8-1-19-3-ultimateautorestart-need-an-autorestart-plugin-grab-the-best-one-today.64414/

### Geyser Dump

https://dump.geysermc.org/OeypxhQQvIig2piGTC3ZnlKPe0SOyife

### Geyser Version

1.19.3 geyser spigot

### Minecraft: Bedrock Edition Device/Version

Windows 10

**Comment by Camotoy** [comment]
Are you trying to block with sneak or right-click? Bedrock uses sneak to block, which we respect.

**Comment by onebeastchris** [comment]
Closing due to no response :/
