### ISSUE TITLE
Bedrock player skin in game is not showing 

### ISSUE THREAD

**Issue by Oddengineers** [GeyserMC/Geyser#3577]
### Describe the bug

After downloading the new geyser update as well as the floodgate update and updating my bedrock account to current 1.19.63 when i join my server the bedrock player in game is Makena skin but in menu its my regular skin. When i look at my character with my Java account in game its my regular skin however and not the Makena skin.

### To Reproduce

Downloaded new update for bedrock and updated Geyser and floodgate

### Expected behaviour

New update should have fixed Skin issues for Bedrock

### Screenshots / Videos

![geyser issues](https://user-images.githubusercontent.com/125910938/221303409-21b755e5-2ac3-4910-ba92-8e19228c9064.png)
![geyser issues2](https://user-images.githubusercontent.com/125910938/221303411-8010d77c-68f4-44c6-b605-20e39f59cf6e.png)
![geyser issues3](https://user-images.githubusercontent.com/125910938/221303412-1054abb0-ce27-4208-a95f-3137ac61b5a6.png)

### Server Version and Plugins

This server is running Paper version git-Paper-406 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 7baf427)
You are 14 version(s) behind
Download the new version at: https://papermc.io/downloads

plugins:
AntiCheatReloaded ,ClearLag, DeadChest, EconomyShopGUI Essentials, EssentialsChat, floodgate, Geyser-Spigot, GeyserUpdater, HolographicsDisplays, LuckPerms, Mobstacker, NFCNotes, Oneplayersleep, ProtectionStones, ProtocolLib, Shopkeepers, TDRPlaytime, Vault, WildTools, WorldEdit, WorldGaurd

### Geyser Dump

https://dump.geysermc.org/RkEwDpRutM3DpVs63f7kiw1d071JNMqj

### Geyser Version

version 2.1.0-SNAPSHOT (git-master-50104c9

### Minecraft: Bedrock Edition Device/Version

1.19.63 computer

**Comment by PQCraft** [comment]
Can confirm:
![image](https://user-images.githubusercontent.com/58464017/229896879-d7856d94-ab0d-4081-ba70-823a8547c770.png)
![image](https://user-images.githubusercontent.com/58464017/229896916-60e64638-8413-45b0-b18b-0c1c094e0b37.png)

**Comment by onebeastchris** [comment]
Unable to replicate with the latest version. Can you update Geyser, and retest?

**Comment by PQCraft** [comment]
@onebeastchris It seems to have been fixed since I opened this.

**Comment by onebeastchris** [comment]
Thanks for the reply, and the making of this issue! Glad to hear it's working.
