### ISSUE TITLE
Skin Uploading Floodgate

### ISSUE THREAD

**Issue by Hay127** [GeyserMC/Geyser#3583]
### Describe the bug

I have a problem when joining the server, the text appears got disconnected from skin uploader: failed to find the given code in combonation with verify code followed by disconnected from the server

### To Reproduce

turn on the server and join the server with bedrock client

### Expected behaviour

Skin uploading to server and java being able to see it

### Screenshots / Videos

![Screenshot_20230226_100849](https://user-images.githubusercontent.com/83993950/221390368-4d31f2f3-31c0-4d2c-aab3-f45eb68e7491.jpg)

### Server Version and Plugins

![Screenshot_20230226_100849](https://user-images.githubusercontent.com/83993950/221390375-98324d3d-7250-4f58-97b2-c34ff86137fc.jpg)
``

### Geyser Dump

https://dump.geysermc.org/78tGqYoDNSr6bNPfUiUrwr0NHiXgnrXS

### Geyser Version

2.1.0 Snapshot (git-master-bad077d) 

### Minecraft: Bedrock Edition Device/Version

1.19.63 Bedrock

**Comment by Hay127** [comment]
Server Version Is Paper 1.19.3

**Comment by onebeastchris** [comment]
This will be fixed once the next Geyser update with the protocol 3.0 branch releases

**Comment by onebeastchris** [comment]
Could you try updating to the latest version of Geyser, and see if the issue persists?
If it does, send a new Geyser dump by running "geyser dump" in your server console.

**Comment by onebeastchris** [comment]
Closing due to no response.
