### ISSUE TITLE
World stops loading after some time

### ISSUE THREAD

**Issue by Minecraftboerger** [GeyserMC/Geyser#3586]
### Describe the bug

I have a hosted spigot server, when joined, for a limited time, maybe one minute, everything works as expected. then the world stops loading and you cant interact with it, but if you chat it shows up in the console but also not on the client this happens not just for me, my friends also have issues with playing

### To Reproduce

join the server with gyser and floodgate
wait some time

### Expected behaviour

it stopps rendering the world and the client cant interact with the world
then after another join the world stays unloaded till the server is restarted

### Screenshots / Videos

![grafik](https://user-images.githubusercontent.com/114679034/221656653-164dabf7-d623-44b0-bf3c-971ee1e9e6c7.png)
![grafik](https://user-images.githubusercontent.com/114679034/221656362-6fa19f8e-6d1c-45b8-b221-9936e886ac62.png)
![grafik](https://user-images.githubusercontent.com/114679034/221656543-6435ca1c-cd1e-4c11-bd8c-bc59670c50e2.png)

### Server Version and Plugins

![grafik](https://user-images.githubusercontent.com/114679034/221656979-9c451910-f577-4331-9613-016cccf47316.png)
from the plugin side, I use Sethome. decentholograms, maintenance, chatfeelings, JoinMessagePlus, Clearlagg, permissionsEx, ViaVersion, mcMMO, Vault, floodgate, MultiverseCore, FAWE, Multiverse inventorys, VeinMiner, Gyser, RandomCoords, Chestshop, Gsit, Multiverse portals, griefprevention

### Geyser Dump

https://dump.geysermc.org/rSbm8aUx7W409yVb5LPks5gK58QadhhP

### Geyser Version

Geyser 2.1.0-snapshot

### Minecraft: Bedrock Edition Device/Version

1.19.60, PC and Mobile

**Comment by Camotoy** [comment]
Please see #2861. Thanks!
