### ISSUE TITLE
Bedrock Players can't connect after a while

### ISSUE THREAD

**Issue by Henrosr** [GeyserMC/Geyser#3588]
### Describe the bug

After a while players on Bedrock can't connect to my server. It happens about every 1-2 days. For example, my server restarted at 4AM today, and at 5PM players on Bedrock could not join anymore. When they try they are stuck on "Locating Server" and with no errors in the log. Players that are online on a Bedrock device can play like normal, but if they got kicked for example they can't reconnect. A restart fixes the issue, but then it happens again after some time.

### To Reproduce

This is what I know:
Start server
Let it stay online
After 12 hours or more, Bedrock players can't connect anymore. 
Restart to fix temporarily

### Expected behaviour

Join the server at 5PM and not be stuck on "Locating Server".

### Server Version and Plugins

git-Paper-307 (MC: 1.19.2)

Plugins:
AdvancedEnchantments, BetterTeams, BKCommonLib, BottledExp, BuildersWand, BuycraftX, ChatItem, ChestShop, Citizens, CMI, CMILib, CommandPanels, CoreProtect, DailyRewardsPlus, DiscordSRV, EvenMoreFish, ExcellentCrates, FastChunkPregenerator, FeatherBoard, floodgate, Geyser-Spigot, GPFlags, GriefPrevention, HolographicDisplays, Jobs, LibsDisguises, LuckPerms, mcMMO, MiniMOTD, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, NexEngine, PinataParty, PL-Hide, PlaceholderAPI, PlayerVaults, PlayerWarps, PlugManX (PlugMan), ProtocolLib, PvPManager, ShopGUIPlus, ShopGUIPlus-SellGUI, SilkSpawners_v2, spark, TAB, Themis, TradeSystem, UltimateTimber, Vault, ViaBackwards, ViaVersion, VoidGen, Votifier, Vouchers, WorldEdit, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV3

### Geyser Dump

https://dump.geysermc.org/PsybYjhHEVPBq2ovr2l2wBhC9bxvdeaM

### Geyser Version

2.1.0-SNAPSHOT (git-master-b0c4208) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.62)

### Minecraft: Bedrock Edition Device/Version

All Bedrock Devices

### Additional Context

This older post described almost the same issue https://github.com/GeyserMC/Geyser/issues/2883

I changed host pretty recently, and I talked with their support and they said it should not be caused by them since they have not heard about similar issues before.

**Comment by Camotoy** [comment]
It's a lot of effort, but would you be able to update to 1.19.3 and see if the issue persists? Or, try using Geyser standalone.

**Comment by Henrosr** [comment]
> It's a lot of effort, but would you be able to update to 1.19.3 and see if the issue persists? Or, try using Geyser standalone.

I have changed to Geyser standalone. I’ll have to wait 2 days to see if it helps.

**Comment by Henrosr** [comment]
> 

I ran Geyser standalone for two days, and the issue reappeared today.

**Comment by Henrosr** [comment]
Here is the log from when Geyser standalone "broke" and the same issue happend. https://mclo.gs/1O6HLd5

**Comment by Henrosr** [comment]
Still hasn't solved this
