### ISSUE TITLE
channel closed

### ISSUE THREAD

**Issue by Rlicardo** [GeyserMC/Geyser#3590]
### Describe the bug

[Geyser Spigot connection thread-4-3/WARN]: An exception 'java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.isOpen()" because "this.m" is null' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:

### To Reproduce

i dont know

### Expected behaviour

i dont know

### Screenshots / Videos

![334572243_769215010933505_7321851657062052340_n](https://user-images.githubusercontent.com/126685722/222158057-d9a76b9a-86bb-4a74-9ffe-274632dcbbef.png)

### Server Version and Plugins

1.19.3,  

### Geyser Dump

   {     "versionInfo": {         "name": "Geyser",         "version": "2.1.0-SNAPSHOT (git-master-b0c4208)",         "javaName": "OpenJDK 64-Bit Server VM",         "javaVendor": "Eclipse Adoptium",         "javaVersion": "18.0.2.1+1",         "architecture": "amd64",         "operatingSystem": "Linux",         "operatingSystemVersion": "5.4.0-90-generic",         "network": {             "dockerCheck": true,             "internalIP": "***"         },         "mcInfo": {             "bedrockVersions": [                 "1.19.20",                 "1.19.21/1.19.22",                 "1.19.30/1.19.31",                 "1.19.40/1.19.41",                 "1.19.50/1.19.51",                 "1.19.60",                 "1.19.62"             ],             "bedrockProtocols": [                 544,                 545,                 554,                 557,                 560,                 567,                 568             ],             "defaultBedrockProtocol": 567,             "javaVersions": [                 "1.19.3"             ],             "javaProtocol": 761         }     },     "cpuCount": 6,     "cpuName": "Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz",     "systemLocale": "en_US",     "systemEncoding": "UTF-8",     "gitInfo": {         "buildNumber": "1314",         "git.commit.id.abbrev": "b0c4208",         "git.commit.id": "b0c42086ad70c0b010bbfd3084a9205bc85d05d4",         "git.branch": "master",         "git.remote.origin.url": "https://github.com/GeyserMC/Geyser.git"     },     "config": {         "autoconfiguredRemote": true,         "bedrock": {             "address": "0.0.0.0",             "port": 19816,             "clone-remote-port": false,             "motd1": "Bizade Universal",             "motd2": "Bizade Universal",             "server-name": "Geyser",             "compression-level": 6,             "enable-proxy-protocol": false,             "proxy-protocol-whitelisted-ips": []         },         "remote": {             "address": "***",             "port": 19816,             "auth-type": "FLOODGATE",             "allow-password-authentication": true,             "use-proxy-protocol": false,             "forward-hostname": false         },         "userAuths": null,         "metrics": {             "enabled": true,             "uuid": "f8172bf2-9b4f-4be0-83c3-140544c57e10"         },         "disableCompression": true,         "saved-user-logins": [             "ThisExampleUsernameShouldBeLongEnoughToNeverBeAnXboxUsername",             "ThisOtherExampleUsernameShouldAlsoBeLongEnough"         ],         "floodgate-key-file": "key.pem",         "command-suggestions": true,         "passthrough-motd": false,         "passthrough-player-counts": false,         "passthrough-protocol-name": false,         "legacy-ping-passthrough": false,         "ping-passthrough-interval": 3,         "forward-player-ping": false,         "max-players": 100,         "debug-mode": false,         "allow-third-party-capes": false,         "show-cooldown": "title",         "show-coordinates": true,         "disable-bedrock-scaffolding": false,         "always-quick-change-armor": false,         "emote-offhand-workaround": "DISABLED",         "allow-third-party-ears": false,         "default-locale": null,         "cache-images": 0,         "allow-custom-skulls": true,         "max-visible-custom-skulls": 128,         "custom-skull-render-distance": 32,         "add-non-bedrock-items": true,         "above-bedrock-nether-building": false,         "force-resource-packs": true,         "xbox-achievements-enabled": false,         "log-player-ip-addresses": true,         "notify-on-new-bedrock-update": true,         "unusable-space-block": "minecraft:barrier",         "pending-authentication-timeout": 120,         "scoreboard-packet-threshold": 20,         "enable-proxy-connections": false,         "mtu": 1400,         "use-direct-connection": true,         "disable-compression": true,         "config-version": 4     },     "floodgate": {         "gitInfo": null,         "config": null     },     "userPlatforms": {},     "hashInfo": {         "md5Hash": "60cb3ea005e8c286440ace0616e3f00e",         "sha256Hash": "404ebfef296b53b1eb1c61d6465a8a993570b9f8c21b07c8c7b653170a72c3ae"     },     "ramInfo": {         "free": 5840,         "total": 11832,         "max": 16384     },     "logsInfo": null,     "bootstrapInfo": {         "platform": "SPIGOT",         "platformName": "CraftBukkit",         "platformVersion": "3619-Spigot-d90018e-6459934 (MC: 1.19.3)",         "platformAPIVersion": "1.19.3-R0.1-SNAPSHOT",         "onlineMode": false,         "serverIP": "0.0.0.0",         "serverPort": 19816,         "plugins": [             {                 "enabled": true,                 "name": "PlaceholderAPI",                 "version": "2.11.2",                 "main": "me.clip.placeholderapi.PlaceholderAPIPlugin",                 "authors": [                     "HelpChat"                 ]             },             {                 "enabled": true,                 "name": "PlayTime",                 "version": "3.6",                 "main": "me.f64.playtime.Main",                 "authors": [                     "F64_Rx"                 ]             },             {                 "enabled": true,                 "name": "HolographicDisplays",                 "version": "3.0.1",                 "main": "me.filoghost.holographicdisplays.plugin.HolographicDisplays",                 "authors": [                     "filoghost"                 ]             },             {                 "enabled": true,                 "name": "UltimateAntiBot",                 "version": "4.0.5-ABYSS",                 "main": "me.kr1s_d.ultimateantibot.UltimateAntiBotSpigot",                 "authors": [                     "Kr1S_D"                 ]             },             {                 "enabled": true,                 "name": "PL-Hide",                 "version": "1.5.21",                 "main": "me.nononitas.plhide.PLHide",                 "authors": [                     "Nononitas"                 ]             },             {                 "enabled": true,                 "name": "water",                 "version": "1.9.11 BETA",                 "main": "me.RealisticWater.Main",                 "authors": []             },             {                 "enabled": true,                 "name": "RHLeafDecay",                 "version": "1.19_R3",                 "main": "eu.raidersheaven.rhleafdecay.main.Main",                 "authors": [                     "X0R3",                     "GeekLegend"                 ]             },             {                 "enabled": true,                 "name": "CustomMobEXP",                 "version": "1.02",                 "main": "me.pabjr.custommobexp.CustomMobEXP",                 "authors": [                     "PabJr"                 ]             },             {                 "enabled": true,                 "name": "ViaVersion",                 "version": "4.5.1",                 "main": "com.viaversion.viaversion.ViaVersionPlugin",                 "authors": [                     "_MylesC",                     "creeper123123321",                     "Gerrygames",                     "kennytv",                     "Matsv"                 ]             },             {                 "enabled": true,                 "name": "NBTAPI",                 "version": "2.11.1",                 "main": "de.tr7zw.nbtapi.plugin.NBTAPI",                 "authors": [                     "tr7zw"                 ]             },             {                 "enabled": true,                 "name": "ViaBackwards",                 "version": "4.5.1",                 "main": "com.viaversion.viabackwards.BukkitPlugin",                 "authors": [                     "Matsv",                     "kennytv",                     "Gerrygames",                     "creeper123123321",                     "ForceUpdate1"                 ]             },             {                 "enabled": true,                 "name": "MiniMOTD",                 "version": "2.0.10",                 "main": "xyz.jpenilla.minimotd.bukkit.MiniMOTDPlugin",                 "authors": [                     "jmp"                 ]             },             {                 "enabled": true,                 "name": "ItemEditor",                 "version": "0.1.16",                 "main": "at.freakey.itemeditor.Core",                 "authors": [                     "Freakey"                 ]             },             {                 "enabled": true,                 "name": "PrettierExplosions",                 "version": "1.0.1",                 "main": "com.kixmc.PE.core.PrettierExplosions",                 "authors": [                     "kixmc"                 ]             },             {                 "enabled": true,                 "name": "LuckPerms",                 "version": "5.4.58",                 "main": "me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin",                 "authors": [                     "Luck"                 ]             },             {                 "enabled": true,                 "name": "ClearLag",                 "version": "3.2.2",                 "main": "me.minebuilders.clearlag.Clearlag",                 "authors": [                     "bob7l"                 ]             },             {                 "enabled": true,                 "name": "LoneLibs",                 "version": "1.0.23",                 "main": "dev.lone.LoneLibs.Main",                 "authors": [                     "LoneDev",                     "others"                 ]             },             {                 "enabled": true,                 "name": "ProtocolLib",                 "version": "5.0.0-SNAPSHOT-b612",                 "main": "com.comphenix.protocol.ProtocolLib",                 "authors": [                     "dmulloy2",                     "comphenix"                 ]             },             {                 "enabled": true,                 "name": "LibsDisguises",                 "version": "10.0.32",                 "main": "me.libraryaddict.disguise.LibsDisguises",                 "authors": [                     "libraryaddict",                     "Byteflux",                     "Navid K."                 ]             },             {                 "enabled": true,                 "name": "SimpleTpa",                 "version": "6.2",                 "main": "me.mulemuledupe.simpletpa.SimpleTpa",                 "authors": [                     "MuleMuleDupe"                 ]             },             {                 "enabled": true,                 "name": "floodgate",                 "version": "2.2.0-SNAPSHOT (b74-4f36112)",                 "main": "org.geysermc.floodgate.SpigotPlugin",                 "authors": [                     "GeyserMC"                 ]             },             {                 "enabled": true,                 "name": "Vault",                 "version": "1.7.3-b131",                 "main": "net.milkbowl.vault.Vault",                 "authors": [                     "cereal",                     "Sleaker",                     "mung3r"                 ]             },             {                 "enabled": true,                 "name": "Vehicles",                 "version": "13.7",                 "main": "es.pollitoyeye.vehicles.VehiclesMain",                 "authors": [                     "Pollitoyeye"                 ]             },             {                 "enabled": true,                 "name": "SkinsRestorer",                 "version": "14.2.8",                 "main": "net.skinsrestorer.bukkit.SkinsRestorerBootstrap",                 "authors": [                     "knat",                     "AlexProgrammerDE",                     "Th3Tr0LLeR",                     "McLive",                     "DoNotSpamPls"                 ]             },             {                 "enabled": true,                 "name": "Geyser-Spigot",                 "version": "2.1.0-SNAPSHOT",                 "main": "org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin",                 "authors": [                     "GeyserMC"                 ]             },             {                 "enabled": true,                 "name": "NexEngine",                 "version": "2.2.8 build-19/01/2023",                 "main": "su.nexmedia.engine.NexEngine",                 "authors": [                     "NightExpress"                 ]             },             {                 "enabled": true,                 "name": "LPC",                 "version": "3.6.0",                 "main": "me.wikmor.lpc.LPC",                 "authors": [                     "wikmor"                 ]             },             {                 "enabled": true,                 "name": "dynmap",                 "version": "3.5-beta-1-844",                 "main": "org.dynmap.bukkit.DynmapPlugin",                 "authors": [                     "mikeprimm"                 ]             },             {                 "enabled": true,                 "name": "WorldEdit",                 "version": "7.2.13+46576cc",                 "main": "com.sk89q.worldedit.bukkit.WorldEditPlugin",                 "authors": [                     "EngineHub"                 ]             },             {                 "enabled": true,                 "name": "Essentials",                 "version": "2.19.8-dev+3-1eb5d8a",                 "main": "com.earth2me.essentials.Essentials",                 "authors": [                     "Zenexer",                     "ementalo",                     "Aelux",                     "Brettflan",                     "KimKandor",                     "snowleo",                     "ceulemans",                     "Xeology",                     "KHobbits",                     "md_5",                     "Iaccidentally",                     "drtshock",                     "vemacs",                     "SupaHam",                     "mdcfe",                     "JRoy",                     "pop4959"                 ]             },             {                 "enabled": true,                 "name": "AdvancedBan",                 "version": "2.3.0",                 "main": "me.leoko.advancedban.bukkit.BukkitMain",                 "authors": [                     "Leoko"                 ]             },             {                 "enabled": true,                 "name": "Admintools3",                 "version": "3.1.2",                 "main": "dev.wwst.admintools3.AdminTools3",                 "authors": [                     "Weiiswurst"                 ]             },             {                 "enabled": true,                 "name": "XConomy",                 "version": "2.19.5",                 "main": "me.yic.xconomy.XConomy",                 "authors": [                     "YiC"                 ]             },             {                 "enabled": true,                 "name": "Multiverse-Core",                 "version": "4.3.1-b861",                 "main": "com.onarandombox.MultiverseCore.MultiverseCore",                 "authors": [                     "dumptruckman",                     "Rigby",                     "fernferret",                     "lithium3141",                     "main--"                 ]             },             {                 "enabled": true,                 "name": "DiscordSRV",                 "version": "1.26.0",                 "main": "github.scarsz.discordsrv.DiscordSRV",                 "authors": [                     "Scarsz",                     "Androkai",                     "Vankka"                 ]             },             {                 "enabled": true,                 "name": "AuthMe",                 "version": "5.6.0-beta2-b2453",                 "main": "fr.xephi.authme.AuthMe",                 "authors": [                     "Xephi",                     "sgdc3",                     "DNx5",                     "timvisee",                     "games647",                     "ljacqu",                     "Gnat008"                 ]             },             {                 "enabled": true,                 "name": "PlayerPoints",                 "version": "3.2.5",                 "main": "org.black_ixx.playerpoints.PlayerPoints",                 "authors": [                     "Esophose",                     "Black_ixx"                 ]             },             {                 "enabled": true,                 "name": "WorldGuard",                 "version": "7.0.7+216b061",                 "main": "com.sk89q.worldguard.bukkit.WorldGuardPlugin",                 "authors": []             },             {                 "enabled": true,                 "name": "BetterTeams",                 "version": "4.5.0",                 "main": "com.booksaw.betterTeams.Main",                 "authors": [                     "booksaw"                 ]             },             {                 "enabled": true,                 "name": "TabList",                 "version": "5.6.8",                 "main": "hu.montlikadani.tablist.TabList",                 "authors": [                     "montlikadani"                 ]             },             {                 "enabled": true,                 "name": "MythicMobs",                 "version": "5.2.1-fd1d0777",                 "main": "io.lumine.mythic.bukkit.MythicBukkit",                 "authors": [                     "Lumine"                 ]             },             {                 "enabled": true,                 "name": "BossShopPro",                 "version": "2.0.9",                 "main": "org.black_ixx.bossshop.BossShop",                 "authors": [                     "Black_ixx"                 ]             },             {                 "enabled": true,                 "name": "CoreProtect",                 "version": "21.3",                 "main": "net.coreprotect.CoreProtect",                 "authors": [                     "Intelli"                 ]             },             {                 "enabled": true,                 "name": "WorldGuardExtraFlags",                 "version": "4.2.1",                 "main": "net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin",                 "authors": [                     "isokissa3"                 ]             },             {                 "enabled": true,                 "name": "SimpleScore",                 "version": "3.12.2",                 "main": "com.r4g3baby.simplescore.SimpleScore",                 "authors": [                     "R4G3_BABY"                 ]             },             {                 "enabled": true,                 "name": "Essentials_WarpGUI",                 "version": "2.5",                 "main": "de.marcely.warpgui.EssentialsWarpGUI",                 "authors": [                     "Marcely1199"                 ]             },             {                 "enabled": true,                 "name": "LevelledMobs",                 "version": "3.9.3 b735",                 "main": "me.lokka30.levelledmobs.LevelledMobs",                 "authors": [                     "lokka30",                     "PenalBuffalo",                     "UltimaOath"                 ]             },             {                 "enabled": true,                 "name": "VeinMiner",                 "version": "2.0.0",                 "main": "wtf.choco.veinminer.VeinMinerPlugin",                 "authors": [                     "Choco"                 ]             },             {                 "enabled": true,                 "name": "MoneyFromMobs",                 "version": "4.6",                 "main": "me.chocolf.moneyfrommobs.MoneyFromMobs",                 "authors": [                     "Chocolf"                 ]             },             {                 "enabled": true,                 "name": "Citizens",                 "version": "2.0.30-SNAPSHOT (build 2888)",                 "main": "net.citizensnpcs.Citizens",                 "authors": [                     "fullwall"                 ]             },             {                 "enabled": true,                 "name": "Shopkeepers",                 "version": "2.16.4",                 "main": "com.nisovin.shopkeepers.SKShopkeepersPlugin",                 "authors": [                     "nisovin",                     "blablubbabc"                 ]             },             {                 "enabled": true,                 "name": "ExcellentCrates",                 "version": "4.1.6",                 "main": "su.nightexpress.excellentcrates.ExcellentCrates",                 "authors": [                     "NightExpress"                 ]             },             {                 "enabled": true,                 "name": "EconomyShopGUI",                 "version": "5.2.1",                 "main": "me.gypopo.economyshopgui.EconomyShopGUI",                 "authors": [                     "Gypopo"                 ]             },             {                 "enabled": true,                 "name": "BloodMoon",                 "version": "0.8.1",                 "main": "org.spectralmemories.bloodmoon.Bloodmoon",                 "authors": [                     "SpectralMemories"                 ]             },             {                 "enabled": true,                 "name": "PlayerParticles",                 "version": "8.3",                 "main": "dev.esophose.playerparticles.PlayerParticles",                 "authors": [                     "Esophose"                 ]             },             {                 "enabled": true,                 "name": "GriefPrevention",                 "version": "16.18",                 "main": "me.ryanhamshire.GriefPrevention.GriefPrevention",                 "authors": []             },             {                 "enabled": true,                 "name": "AngelChest",                 "version": "9.8.0",                 "main": "de.jeff_media.angelchest.Main",                 "authors": [                     "mfnalex",                     "JEFF Media GbR"                 ]             },             {                 "enabled": true,                 "name": "MythicLib",                 "version": "1.5",                 "main": "io.lumine.mythic.lib.MythicLib",                 "authors": [                     "Indyuce"                 ]             },             {                 "enabled": true,                 "name": "Vulcan",                 "version": "2.7.1",                 "main": "me.frep.vulcan.spigot.VulcanPlugin",                 "authors": [                     "frep",                     "GladUrBad",                     "Joshb_",                     "Elevated",                     "retrooper"                 ]             },             {                 "enabled": true,                 "name": "DeadlyDisasters",                 "version": "10.3",                 "main": "deadlydisasters.general.Main",                 "authors": [                     "davidclue"                 ]             },             {                 "enabled": true,                 "name": "MythicDungeons",                 "version": "1.1.2-SNAPSHOT",                 "main": "net.playavalon.mythicdungeons.MythicDungeons",                 "authors": [                     "MarcatoSound"                 ]             },             {                 "enabled": true,                 "name": "AdvancedEnchantments",                 "version": "9.0.0b59",                 "main": "net.advancedplugins.ae.Core",                 "authors": [                     "AdvancedPlugins"                 ]             },             {                 "enabled": true,                 "name": "MMOItems",                 "version": "6.9.1",                 "main": "net.Indyuce.mmoitems.MMOItems",                 "authors": [                     "Indyuce"                 ]             },             {                 "enabled": true,                 "name": "DungeonParties",                 "version": "1.0-SNAPSHOT",                 "main": "net.playavalon.avnparty.AvNParty",                 "authors": [                     "MarcatoSound"                 ]             }         ]     },     "flagsInfo": {         "flags": [             "-Xms128M",             "-Xmx16384M",             "-Dterminal.jline=false",             "-Dterminal.ansi=true"         ]     },     "extensionInfo": [] }

### Geyser Version

i just redownload it from geyser website today

### Minecraft: Bedrock Edition Device/Version

1.19.62

### Additional Context

[Geyser Spigot connection thread-4-3/WARN]: An exception 'java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.isOpen()" because "this.m" is null' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:

player cant join the server

**Comment by Jens-Co** [comment]
Are you still having issues? Please update your issue and provide us with server logs and a Geyser dump. Https://mclo.gs and for dump /geyser dump and paste link here.

**Comment by Jens-Co** [comment]
I will close this issue for now since lack of information. without server logs we cannot assist you with your problem. 
i will reopen this if you update and provide us with the server logs, Thanks.
