### ISSUE TITLE
[FABRIC] Stuck in bubble world on Bedrock

### ISSUE THREAD

**Issue by BlackberryCabbit** [GeyserMC/Geyser#3591]
### Describe the bug

I log in to Microsoft using the link and it doesn't clear, server says I joined but I never actually load in. I stay in the bubble joining world until i disconnect or get kicked.

### To Reproduce

1. Use BedrockConnect or any other device to try and join a server
2. Try to log into Microsoft
3. Wait
It won't do anything after that for me.

### Expected behaviour

It should instantly join as soon as the Microsoft login goes through

### Screenshots / Videos

https://github.com/Pugmatt/BedrockConnect/issues/url

### Server Version and Plugins

Fabric 1.19.3 loader 0.14.14 launcher 0.11.1

Mods (all server side only):
        - armor-stand-editor 2.1.0+1.19.3-rc1
	- banhammer 0.6.3+1.19.3
	- blossom-lib 2.5.0+1.19.3
	- blossom-tpa 2.1.0+1.19.3
	- cardinal-components-base 5.0.2 via goml
	- cardinal-components-world 5.0.2 via goml
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 9.0.94
	- com_mysql_mysql-connector-j 8.0.31 via banhammer
	- common-economy-api 1.0.0 via universal_shops
	- common-protection-api 1.0.0 via armor-stand-editor
	- dynmap 3.5-beta-2
	- fabric-api 0.73.2+1.19.3
	- fabric-api-base 0.4.21+70be179c85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.20+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.1.1+b5d379b085 via fabric-api
	- fabric-block-api-v1 1.0.5+e022e5d185 via fabric-api
	- fabric-command-api-v1 1.2.22+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.2.1+3fc4752e85 via fabric-api
	- fabric-commands-v0 0.2.39+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.47+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.5.1+1d37d50285 via fabric-api
	- fabric-convention-tags-v1 1.2.2+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.14+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.2.1+06937c4b85 via fabric-api
	- fabric-dimensions-v1 2.1.41+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.7+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.40+3baeb27a85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.44+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.30+99f9db8085 via fabric-api
	- fabric-item-api-v1 2.1.10+312c329485 via fabric-api
	- fabric-item-group-api-v1 2.1.12+1134c5b885 via fabric-api
	- fabric-lifecycle-events-v1 2.2.10+23a79c8a85 via fabric-api
	- fabric-loot-api-v2 1.1.20+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.24+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.14+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.31+49abcf7e85 via fabric-api
	- fabric-networking-api-v1 1.2.17+4017a8cb85 via fabric-api
	- fabric-networking-v0 0.3.34+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.4.1+eb2a3ba985 via fabric-api
	- fabric-particles-v1 1.0.20+f1e4495b85 via fabric-api
	- fabric-permissions-api-v0 0.2-SNAPSHOT via armor-stand-editor
	- fabric-recipe-api-v1 1.0.1+5176f73d85 via fabric-api
	- fabric-registry-sync-v0 2.0.5+1134c5b885 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.25+afca2f3e85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.18+f1e4495b85 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.3+1134c5b885 via fabric-api
	- fabric-resource-loader-v0 0.10.5+a91e48b785 via fabric-api
	- fabric-screen-handler-api-v1 1.3.13+99f9db8085 via fabric-api
	- fabric-transfer-api-v1 2.1.15+ccd377ba85 via fabric-api
	- fabric-transitive-access-wideners-v1 2.3.1+5b9a588b85 via fabric-api
	- fabricloader 0.14.14
	- fantasy 0.4.8+1.19.3 via multiworld
	- geyser-fabric 2.1.0-SNAPSHOT
	- goml 1.7.0+1.19.3
	- hologram-api 0.2.3+1.19.3 via goml
	- holograms 1.5.0+1.19.3
	- image2map 0.4.0
	- incendium 5.1.4
	- java 17
	- lithium 0.10.4
	- luckperms 5.4.61
	- luckperms-placeholders 5.4-SNAPSHOT
	- map-canvas-api 0.2.1+1.19.3 via image2map
	- minecraft 1.19.3
	- multiworld 1.6
	- nullscape 1.2
	- org_postgresql_postgresql 42.5.1 via banhammer
	- org_xerial_sqlite-jdbc 3.40.0.0 via banhammer
	- org_yaml_snakeyaml 1.31 via viafabric
	- packet_tweaker 0.3.0+1.18.2 via server_translations_api
	- placeholder-api 2.0.0-pre.4+1.19.3
	- player-data-api 0.2.2+1.19.3 via armor-stand-editor
	- playerabilitylib 1.6.1-alpha.patbox via goml
	- polymer-autohost 0.3.11+1.19.3 via polymer-bundled
	- polymer-blocks 0.3.11+1.19.3 via polymer-bundled
	- polymer-bundled 0.3.11+1.19.3
	- polymer-common 0.3.11+1.19.3 via polymer-bundled
	- polymer-core 0.3.11+1.19.3 via polymer-bundled
	- polymer-networking 0.3.11+1.19.3 via polymer-core
	- polymer-registry-sync-manipulator 0.3.11+1.19.3 via polymer-core
	- polymer-resource-pack 0.3.11+1.19.3 via polymer-bundled
	- polysit 0.1.1+mc.1.19.3
	- predicate-api 0.1.0+1.19.3 via styledchat
	- quickhomes 1.19.3-1.3.0
	- rtree-3i-lite-fabric 0.3.0 via goml
	- server_translations_api 1.4.19+1.19.3 via blossom-lib
	- sgui 1.2.1+1.19.3 via universal_shops
	- starlight 1.1.1+fabric.ae22326
	- structory 1.0.1
	- structory_towers 1.0.0
	- styled-nicknames 1.2.0+1.19.3
	- styledchat 2.1.2+1.19.3
	- styledplayerlist 2.3.0+1.19.3
	- terralith 2.3
	- universal_shops 1.1.2+1.19.3
	- viafabric 0.4.9+19-main
	- viafabric-mc119 0.4.9+19-main via viafabric
	- viaversion 4.4.3-SNAPSHOT via viafabric
	- vivecraft 1.19.3-0.0.13

### Geyser Dump

https://dump.geysermc.org/lnTElnBqYTwS06x5b9blMFc081jp5lvW

### Geyser Version

2.1.0-SNAPSHOT (git-master-b0c4208)

### Minecraft: Bedrock Edition Device/Version

1.19.63, Nintendo Switch/IOS/Android

### Additional Context

I also can't seem to get the Floodgate-Fabric mod to work. Even after completely removing both it and Geyser (aswell as the Geyser-fabric config folder) and reinstalling it.

**Comment by onebeastchris** [comment]
Is this still an issue occurring with the latest version of Geyser?
Additionally, this might be a duplicate of #2861 - please try updating the java jdk/jre

**Comment by onebeastchris** [comment]
Closing due to no response.
