### ISSUE TITLE
unable to skip the night by sleeing in a bed

### ISSUE THREAD

**Issue by onebeastchris** [GeyserMC/Geyser#3595]
### Describe the bug

hey. There seems to be a tiny little bug that can occur - sometimes, bedrock players sleep in a bed but are not able to skip the night (get kicked out from the bed as if they successfully slept; but night doesnt get skipped). The behavior isn't consistent, it sometimes works, sometimes doesn't - but it affects only bedrock players.

also observed by someone else in the Geyser discord, see here: https://discord.com/channels/613163671870242838/1081345129429864520
(only difference - they use Geyser-Fabric, i Geyser-Velocity)

### To Reproduce

1. Try to sleep
2. Bugrock player can sleep
3. upon "waking up", the night isn't skipped

### Expected behaviour

night shall be skipped

### Server Version and Plugins

1.19.3 fabric; no plugins or similar that might affect sleep. Only potentially relevant thing - the gamerule that dictates how many players have to sleep is set to 0, basically saying only 1 player has to sleep

### Geyser Dump

https://dump.geysermc.org/cHSe2I4BO0ubvAOUvEGsNO7vchMNcf5V

### Geyser Version

2.1.0-Snapshot, build #1316

### Minecraft: Bedrock Edition Device/Version

1.19.63

**Comment by TheSpyKid0906** [comment]
Hi! I run a server with Geyser and have been running into the same issue when 1.21.21 came out on bedrock edition and when I updated Geyser versions to support it. If someone could enlighten me on why or if anyone has a fix that would be greatly appreciated.

**Comment by onebeastchris** [comment]
This is an old issue - please create a new report with reproduction steps. Thanks.
