### ISSUE TITLE
Players not able to join

### ISSUE THREAD

**Issue by Batman2741** [GeyserMC/Geyser#3596]
### Describe the bug

Player getting unable to join message 

### To Reproduce

Just simply have the latest version of geyser and floodgate along with protocol lib and libs disguises

### Expected behaviour

Players joining 

### Server Version and Plugins

It's all on the latest for 1.19

### Geyser Dump

I can't access the console atm

### Geyser Version

Build 1303

### Minecraft: Bedrock Edition Device/Version

Xbox

**Comment by onebeastchris** [comment]
This is unlikely to be an issue related to any plugins, but instead an issue with how you configured Geyser/configured the host machine to accept outside connections. See the wiki article below:
- setup guide: https://wiki.geysermc.org/geyser/setup/
- fixing unable to connect after proper setup: https://wiki.geysermc.org/geyser/fixing-unable-to-connect-to-world/

If you are still facing issues after trying the steps above first - which you realistically shouldnt, as those wiki articles cover 99% of possible issues - join the GeyserMC discord for help: https://discord.com/invite/geysermc/

**Comment by onebeastchris** [comment]
This can be closed, as it's likely a configuration issue.

**Comment by Jens-Co** [comment]
Can you please follow the issue template and provide us with atleast a Geyser dump or server logs? 
Without more info we cannot replicate your issue.

**Comment by onebeastchris** [comment]
Closing due to no response.
