### ISSUE TITLE
Cannot destroy any squares after joining the server

### ISSUE THREAD

**Issue by linmiao233** [GeyserMC/Geyser#36]
Cannot destroy any squares after joining the server

**Comment by WesleyVanNeck** [comment]
Known issue

**Comment by WesleyVanNeck** [comment]
It isn't finise block breaking isn't inplamented

**Comment by LogicismDev** [comment]
Geyser is still a work in progress, so I wouldn't expect a lot to work so far besides just login, chat and commands.

**Comment by lukeeey** [comment]
Squares? Ahahaha

**Comment by EOT3000** [comment]
luke. Som
