### ISSUE TITLE
Shows unable to chat message anyway although enforce-secure-profile is disabled

### ISSUE THREAD

**Issue by charlie-moomoo** [GeyserMC/Geyser#3604]
### Describe the bug

When Bedrock players send a message, it will show unable to chat message, although the enforce-secure-profile is disabled in the Waterfall config.

### To Reproduce

1. Connect to the server using Bedrock
2. Send a message
3. The following message will show up
```
Bedrock players are likely unable to chat, as the server has enforce-secure-profile enabled on settings.
See https://geysermc.link/secure-chat for more information and details on how to allow chat.
```

### Expected behaviour

The message will not show up

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/65603222/224449386-9a917fe5-f3ce-4685-acf4-ce1429076639.png)

### Server Version and Plugins

Waterfall 510 build

### Geyser Dump

https://dump.geysermc.org/34Po0XQLmk5JJaMayoh5boZWHEgbxkjx

### Geyser Version

2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.19.60, Android

**Comment by Camotoy** [comment]
You're probably using some sort of anti-chat-report plugin. You can disable this message by adding the following system property: `-DGeyser.PrintSecureChatInformation=false`
