### ISSUE TITLE
Unusual nether portal behavior

### ISSUE THREAD

**Issue by ErrorGamer2000** [GeyserMC/Geyser#3606]
### Describe the bug

Sometimes, when a bedrock player goes through a linked nether portal (we have a portal to the stronghold) the server will ignore the portal (it creates a new portal a couple hundred blocks away). This appears to be an issue with nether sizing, although I am confused as to why this would be as those mechanics are the same in both games.

### To Reproduce

This bug appears to be random (we cannot manually recreate it) and only happens for bedrock players

### Expected behaviour

Bedrock players should come through the same portal every time.

### Server Version and Plugins

Server version: `git-Paper-307 (MC: 1.19.2)`

Plugins:

ViaVersion
Floodgate
Geyser

### Geyser Dump

https://dump.geysermc.org/U9D47YiOZ0jEJHJfHDzvV9h1XIVFFcq0

### Geyser Version

2.1.0-SNAPSHOT (git-master-cfd7aeb)

### Minecraft: Bedrock Edition Device/Version

Device: Xbox Version 1.19.XX (>= 1.19.62)

**Comment by Camotoy** [comment]
The only way I could see this being a Bedrock issue is the specific position of the Bedrock client when it enters the portal. Otherwise, we'd have no reason to touch the server behavior of portal mechanics.

**Comment by ErrorGamer2000** [comment]
Closing, because we have reproduced it with a Java player, so it's something else.
