### ISSUE TITLE
Double Tag Geyser

### ISSUE THREAD

**Issue by ElSxcrificio** [GeyserMC/Geyser#3610]
### Describe the bug

I have a bug that happens since the last update of Geyser, in which the player tags look double.

### To Reproduce

Running the latest version of Geyser currently

### Expected behaviour

That only the 3 normal lines appear as before

### Screenshots / Videos

https://imgur.com/a/TpL2Tei

### Server Version and Plugins

Pufferfish 1.19.2

### Geyser Dump

https://dump.geysermc.org/epdUqyt2Axm4D9RgPzAmslurg7NgGoAV

### Geyser Version

The most recent

### Minecraft: Bedrock Edition Device/Version

All

**Comment by JohnDoe1231ss** [comment]
This is not a geyser issue Minecraft is already aware and is working on I believe!

**Comment by JohnDoe1231ss** [comment]
Also image does not exist for me.

**Comment by Ekelgans** [comment]
The imgur works for me, and it passes to me too

**Comment by Camotoy** [comment]
I probably fixed this. Let me know if the issue still persists.
