### ISSUE TITLE
Weather all time

### ISSUE THREAD

**Issue by Ekelgans** [GeyserMC/Geyser#3611]
### Describe the bug

It's raining on my bedrock client even when I use /weather clear. Fix this please, on Java it does not happens. (I am on a Java Client and the weather is good, no raining, but in Bedrock Client, it's raining every time.

### To Reproduce

1. Join Bedrock Client
2. Put /weather clear
3. Look that it's raining

### Expected behaviour

That it didn't rain

### Server Version and Plugins

![image](https://user-images.githubusercontent.com/92401675/225421727-975715ef-8f28-4449-84dc-3642ec7f28a4.png)

### Geyser Dump

https://dump.geysermc.org/NNcefCdz39E7gSVqzjh9HPA9kGIB1tvu

### Geyser Version

Geyser 2.1.0-SNAPSHOT (git-master-6ec7326)

### Minecraft: Bedrock Edition Device/Version

All (I tried Windows 11)

**Comment by HippieBeak** [comment]
I’m also experiencing this on my 1.19.3 servers. I am using Geyser Standalone. This does not occur on my 1.17.1 servers.

**Comment by Kas-tle** [comment]
Could you guys please list the plugins on your back-end servers on which this is occurring? Thanks.

**Comment by Ekelgans** [comment]
Hello, here is the list: 
![image](https://user-images.githubusercontent.com/92401675/225637085-6e1d7193-3f4a-4f47-94c8-acb47a25ea6a.png)

**Comment by HippieBeak** [comment]
Just debugged this with Kastle. It is an issue with WorldGuard. To fix this, remove your weather-lock in the region.

**Comment by Leahcimkrob** [comment]
With us it's only like that in the plot world with Plotsquared. In all other worlds we don't have continuous rain. in the region i have already remove the weather-lock flag, with no change.
