### ISSUE TITLE
Paper server issue

### ISSUE THREAD

**Issue by Oddengineers** [GeyserMC/Geyser#3612]
### Describe the bug

On paper server my bedrock character has this image in the screen 

### To Reproduce

download Experimental 1.19.4 Branch 
log into server image comes up and cant be closed

### Expected behaviour

normal playing screen

### Screenshots / Videos

![Bedrockissue](https://user-images.githubusercontent.com/125910938/225434113-f540546c-4481-46fa-98d8-b8f04ddb44d0.png)

### Server Version and Plugins

version:
This server is running Paper version git-Paper-"d44cca7" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: d44cca7 on HEAD)
Error obtaining version information
Previous version: git-Paper-448 (MC: 1.19.3)

plugins:
Essentials, EssentialsChat, floodgate, Geysery-Spigot, GeyserUpdater, MilestoneRewards

### Geyser Dump

https://dump.geysermc.org/rIybrmpXztt89qwJQVlckXvZpEwYEmnH

### Geyser Version

2.1.0-SNAPSHOT (git-master-6ec7326) (Java: 1.19.4, Bedrock: 1.19.30/1.19.31 - 1.19.70)

### Minecraft: Bedrock Edition Device/Version

1.19.70 computer

**Comment by Kas-tle** [comment]
Please try with a clean server (no plugins other than Geyser/Floodgate) and without the resource pack.

**Comment by onebeastchris** [comment]
they cross-posted in the geyser discord server's support channel; removing the resource pack fixed it
