### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by mrunningmasterc** [GeyserMC/Geyser#3614]
### Describe the bug

After Build #1321 (Mar 10, 2023, 5:13:36 AM), there has been really high usage of memory. When bedrock player joined on Build #1321 it would only go up about 1 or 2%. Now on the latest Build #1326 (Mar 15, 2023, 3:36:17 PM), it goes up about 10-15% on ram. I only use about 2gb for the proxy server.

### To Reproduce

Run Build #1321 join bedrock player

Then run Build #1326 join bedrock player

You'll see higher ram usage in the new build

### Expected behaviour

Ram shouldn't have gone up so high. I lose almost all the proxy ram in 2 hours, I used to only run out in 24 hours.

### Server Version and Plugins

This server is running FlameCord version 1.3.9 by LinsaFTW & Sammwy.

### Geyser Dump

https://dump.geysermc.org/Z9e6nTtxb1jzHWv2dZPlcE6pUjjMaOhd

### Geyser Version

2.1.0-SNAPSHOT (git-master-d7c6865)

**Comment by Kas-tle** [comment]
Is this still an issue with the latest build? Also if your proxy is normally running out of me sort every 24 hours that may be a sign that there is something else wrong.

**Comment by onebeastchris** [comment]
Closing due to no response.
