### ISSUE TITLE
Downstream Packet Error

### ISSUE THREAD

**Issue by JacketJack113** [GeyserMC/Geyser#3618]
### Describe the bug

Upon updating the geyser in order to be compatible with Minecraft BE 1.19.70, this bug shows up when a Bedrock user tries to join the server. In which the CLI would be spam with "Downstream packet error! index: 3, length: 10275 (expected: range(0, 4))" or something similar to it, Bedrock user would stuck at Locating Server stage and unable to join, even it did found the exact WAN IP address of the hosted server.

### To Reproduce

1. Launch server.jar with geyser and floodgate installed
2. Use bedrock minecraft to join the server either using localhost IP or WAN IP with port 19132
3. expected behaviour would then show up

### Expected behaviour

Server Hoster CLI:
>The console would be spammed with Downstream Packet Error or string that were similar.
>The TPS will drop sometimes when this error occurs. (7.7 TPS in my case, displays for an extremely short time period before it returns back to 20 TPS)
>
>e.g.:
 >_Downstream packet error! Packet "ClientboundSetTitlesAnimationPacket" not fully read._
 >_Downstream packet error! Received id 63 for MetadataType when the maximum was 28!_
 >_Downstream packet error! com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $_
 
 User Interface (Bedrock):
 >The game would hang at locating the server stage instead of loading into the game.

### Screenshots / Videos

Video demonstration of how this error works:
https://user-images.githubusercontent.com/104156159/225671128-9ee65a23-ae2d-4c78-bb0f-bd23372bfaae.mp4

Log file of the latest server.jar execution (dated at 23:44:40 (UTC+8) on 16/3/2023):
[latest.log](https://github.com/GeyserMC/Geyser/files/10992744/latest.log)

### Server Version and Plugins

Server version: Minecraft 1.19.3 with Fabric Loader 0.14.14
List of mods:
        - adventure-platform-fabric 5.6.0-SNAPSHOT via floodgate
        - anvilformat 1.1
        - cloth-basic-math 0.6.1 via cloth-config
        - cloth-config 9.0.94
        - cloud 1.8.0-SNAPSHOT via floodgate
        - cloud_commandframework_cloud-brigadier_ 1.8.0-SNAPSHOT via cloud
        - cloud_commandframework_cloud-core_ 1.8.0-SNAPSHOT via cloud
        - cloud_commandframework_cloud-services_ 1.8.0-SNAPSHOT via cloud
        - collective 6.43
        - com_fasterxml_jackson_core_jackson-annotations 2.14.1 via mcdiscordchat
        - com_fasterxml_jackson_core_jackson-core 2.14.1 via mcdiscordchat
        - com_fasterxml_jackson_core_jackson-databind 2.14.1 via mcdiscordchat
        - com_google_code_gson_gson 2.10 via mcdiscordchat
        - com_neovisionaries_nv-websocket-client 2.14 via mcdiscordchat
        - com_squareup_okhttp3_okhttp 4.10.0 via mcdiscordchat
        - com_squareup_okio_okio 2.10.0 via mcdiscordchat
        - com_vdurmont_emoji-java 5.1.1 via mcdiscordchat
        - com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
        - fabric-api 0.73.2+1.19.3
        - fabric-api-base 0.4.21+70be179c85 via fabric-api
        - fabric-api-lookup-api-v1 1.6.20+49abcf7e85 via fabric-api
        - fabric-biome-api-v1 12.1.1+b5d379b085 via fabric-api
        - fabric-block-api-v1 1.0.5+e022e5d185 via fabric-api
        - fabric-command-api-v1 1.2.22+f71b366f85 via fabric-api
        - fabric-command-api-v2 2.2.1+3fc4752e85 via fabric-api
        - fabric-commands-v0 0.2.39+df3654b385 via fabric-api
        - fabric-containers-v0 0.1.47+df3654b385 via fabric-api
        - fabric-content-registries-v0 3.5.1+1d37d50285 via fabric-api
        - fabric-convention-tags-v1 1.2.2+8e4e694f85 via fabric-api
        - fabric-crash-report-info-v1 0.2.14+aeb40ebe85 via fabric-api
        - fabric-data-generation-api-v1 11.2.1+06937c4b85 via fabric-api
        - fabric-dimensions-v1 2.1.41+48349a3f85 via fabric-api
        - fabric-entity-events-v1 1.5.7+b83334a085 via fabric-api
        - fabric-events-interaction-v0 0.4.40+3baeb27a85 via fabric-api
        - fabric-events-lifecycle-v0 0.2.44+df3654b385 via fabric-api
        - fabric-game-rule-api-v1 1.0.30+99f9db8085 via fabric-api
        - fabric-item-api-v1 2.1.10+312c329485 via fabric-api
        - fabric-item-group-api-v1 2.1.12+1134c5b885 via fabric-api
        - fabric-lifecycle-events-v1 2.2.10+23a79c8a85 via fabric-api
        - fabric-loot-api-v2 1.1.20+75e9821185 via fabric-api
        - fabric-loot-tables-v1 1.1.24+9e7660c685 via fabric-api
        - fabric-message-api-v1 5.0.14+6ede1da985 via fabric-api
        - fabric-mining-level-api-v1 2.1.31+49abcf7e85 via fabric-api
        - fabric-networking-api-v1 1.2.17+4017a8cb85 via fabric-api
        - fabric-networking-v0 0.3.34+df3654b385 via fabric-api
        - fabric-object-builder-api-v1 5.4.1+eb2a3ba985 via fabric-api
        - fabric-particles-v1 1.0.20+f1e4495b85 via fabric-api
        - fabric-permissions-api-v0 0.2-SNAPSHOT via geyser-fabric
        - fabric-recipe-api-v1 1.0.1+5176f73d85 via fabric-api
        - fabric-registry-sync-v0 2.0.5+1134c5b885 via fabric-api
        - fabric-rendering-data-attachment-v1 0.3.25+afca2f3e85 via fabric-api
        - fabric-rendering-fluids-v1 3.0.18+f1e4495b85 via fabric-api
        - fabric-resource-conditions-api-v1 2.2.3+1134c5b885 via fabric-api
        - fabric-resource-loader-v0 0.10.5+a91e48b785 via fabric-api
        - fabric-screen-handler-api-v1 1.3.13+99f9db8085 via fabric-api
        - fabric-transfer-api-v1 2.1.15+ccd377ba85 via fabric-api
        - fabric-transitive-access-wideners-v1 2.3.1+5b9a588b85 via fabric-api
        - fabricloader 0.14.14
        - floodgate 2.2.0-SNAPSHOT
        - geyser-fabric 2.1.0-SNAPSHOT
        - io_leangen_geantyref_geantyref 1.3.13 via cloud
        - java 17
        - krypton 0.2.1
        - lithium 0.10.4
        - mcdiscordchat 2.1.2
        - mcdiscordchat-1_19_x 2.1.2 via mcdiscordchat
        - minecraft 1.19.3
        - net_dv8tion_jda 5.0.0-beta.2 via mcdiscordchat
        - net_kyori_adventure-api 4.12.0 via adventure-platform-fabric
        - net_kyori_adventure-key 4.12.0 via adventure-platform-fabric
        - net_kyori_adventure-platform-api 4.1.2 via adventure-platform-fabric
        - net_kyori_adventure-text-logger-slf4j 4.12.0 via adventure-platform-fabric
        - net_kyori_adventure-text-minimessage 4.12.0 via adventure-platform-fabric
        - net_kyori_adventure-text-serializer-gson 4.12.0 via adventure-platform-fabric
        - net_kyori_adventure-text-serializer-plain 4.12.0 via adventure-platform-fabric
        - net_kyori_examination-api 1.3.0 via adventure-platform-fabric
        - net_kyori_examination-string 1.3.0 via adventure-platform-fabric
        - net_sf_trove4j_trove4j 3.0.3 via mcdiscordchat
        - nodami 1.0.0
        - org_apache_commons_commons-collections4 4.4 via mcdiscordchat
        - org_jetbrains_kotlin_kotlin-stdlib 1.8.0 via mcdiscordchat
        - org_json_json 20220924 via mcdiscordchat
        - org_slf4j_slf4j-api 2.0.6 via mcdiscordchat
        - org_yaml_snakeyaml 1.33 via viafabric
        - placeholder-api 2.0.0-pre.2+1.19.3 via styledplayerlist
        - player-data-api 0.2.2+1.19.3 via styledplayerlist
        - serverstop 0.1.1
        - smoothboot 1.19-1.7.1
        - starlight 1.1.1+fabric.ae22326
        - styledplayerlist 2.3.0+1.19.3
        - textutilities 1.4.1+1.19.3
        - viabackwards 4.5.1
        - viafabric 0.4.9+24-main
        - viafabric-mc119 0.4.9+24-main via viafabric
        - viarewind 2.0.2
        - viaversion 4.6.0-23w04a-SNAPSHOT via viafabric

### Geyser Dump

https://dump.geysermc.org/yJcx2I5rz1U4Uj7WQI8AmBkaTqA2MwWK

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-d7c6865)

### Minecraft: Bedrock Edition Device/Version

1.19.70, either using Win10 and android 13

### Additional Context

When comparing to Geyser version 2.1.0-SNAPSHOT (git-master-fca726c), based on my observation, i.e. versions that doesn't support 1.19.70 but 1.19.62, could load bedrock player successfully without any issue, but not in this version (this refers (git-master-d7c6865))

**Comment by onebeastchris** [comment]
Could you try updating Geyser to the latest version to see if the issue persists?

**Comment by onebeastchris** [comment]
Closing due to no response.
