### ISSUE TITLE
Stone Pots

### ISSUE THREAD

**Issue by teamaonn** [GeyserMC/Geyser#3619]
### Describe the bug

Player on bedrock states that when they try to pick up a flower pot either in creative or breaking it via survival, it turns into a stone

### To Reproduce

Be in bedrock
Be in creative
Break flower pot
Get stoned (pun intended)

### Expected behaviour

it not being a stone.

### Screenshots / Videos

https://youtu.be/-3wfjyvw5xQ

### Server Version and Plugins

Spigot 1.19.3 
![image](https://user-images.githubusercontent.com/20132437/225796471-61ac946d-3692-4ea3-9081-97d7bf2df529.png)
https://imgur.com/a/r6tNZgB

### Geyser Dump

https://dump.geysermc.org/MpcTOdmgi51Q3wJHgD2LnSzakyn9D1m3

### Geyser Version

Build 1326

### Minecraft: Bedrock Edition Device/Version

Nintendo switch, just released version

**Comment by Camotoy** [comment]
Does this happen with Java Edition 1.19.4?

**Comment by teamaonn** [comment]
Yes, we tried it with 1.19.4 to see if it was the viaversion causing it before posting here. The result is the same.

**Comment by teamaonn** [comment]
Also it's happening with Build 1328 as well, have not tried 1329 yet.

**Comment by teamaonn** [comment]
Still happens somewhat, dropped plugins to this:
![image](https://user-images.githubusercontent.com/20132437/227663450-bfae74c7-5902-41b0-9278-75481044bf26.png)

As of now, we are able to obtain the pots, however when placing them its almost as if they're an illegal item, so it's weird. Happens on all bedrock versions that have been tested so far.

**Comment by teamaonn** [comment]
Also we are now strictly on 1.19.4
