### ISSUE TITLE
Error with Geyser/Floodgate on Velocity

### ISSUE THREAD

**Issue by patbeni** [GeyserMC/Geyser#3622]
### Describe the bug

I get [this](https://mclo.gs/Cr2enNo) error when my proxy starts

### To Reproduce

I just have to start my server.
Changes I made:
Set send-floodgate-data to true
Changed Geyser MOTD to the following

### Expected behaviour

Proxy to start with Geyser and Floodgate enabled

### Geyser Version

 Build #1329

**Comment by rtm516** [comment]
Please provide a geyser dump

**Comment by Jens-Co** [comment]
Closing this due to no response given.
