### ISSUE TITLE
Loading World Slower on 1.19.70

### ISSUE THREAD

**Issue by HealingHalo8** [GeyserMC/Geyser#3623]
### Describe the bug

Since the first release of 1.19.70, there has been slower world loading

I'm running on bungeecord and when players join the hub server everything is fine, but when players join another server a lot of the hub server will have ghost chunks. Players also when teleporting between worlds will now have slower Generating Terrain screens.

https://dump.geysermc.org/cff00DEkvZnsPhvbAweoKL0vuzxZXMcB

### To Reproduce

1. Join a bungeecord server
2. Switch Servers
3. View rendering issues

### Expected behaviour

Fast World Switching
Chunks loading properly

### Screenshots / Videos

![Minecraft 3_18_2023 9_40_09 PM](https://user-images.githubusercontent.com/88226371/226149102-85d8f484-6aeb-4148-8a8b-c932ca810afe.png)
![Minecraft 3_18_2023 9_40_04 PM](https://user-images.githubusercontent.com/88226371/226149107-bb3123b4-4621-4049-a587-c7cd0ba59c01.png)
![Minecraft 3_18_2023 9_39_57 PM](https://user-images.githubusercontent.com/88226371/226149108-719be391-0559-499c-9d25-89c883de2d4e.png)
![Minecraft 3_18_2023 9_39_52 PM](https://user-images.githubusercontent.com/88226371/226149109-534c31c3-d7a6-413e-8fa0-8808bb68ce3d.png)

### Geyser Dump

https://dump.geysermc.org/cff00DEkvZnsPhvbAweoKL0vuzxZXMcB

### Geyser Version

2.1.0-SNAPSHOT (git-master-9609686)

### Minecraft: Bedrock Edition Device/Version

1.19.70

**Comment by onebeastchris** [comment]
Could you try updating Geyser, and if the latest version still has these issues; send a new dump?

**Comment by onebeastchris** [comment]
Closing due to no response.
