### ISSUE TITLE
Crash When Typing "/" In The Chat

### ISSUE THREAD

**Issue by Grizzlybln** [GeyserMC/Geyser#3628]
### Describe the bug

Hi! 

Open Chat , And Write / the game will crash , not do anything , and only to fix it help game restart

### To Reproduce

1. Go Online On An Minecraft Server With GeyserMC Installed
2. Open The Chat
3. Type / In The Chat
4. The Game Will Be Stop Working And Not Do Anything

### Expected behaviour

My Server Use Geyser , I'm Bedrock User And My Server Are An Crossplay System,

And I Can't Play Momently , For The CrashBug.

### Screenshots / Videos

Have Not screen , The Bug Not Allowed This To Do , Sorry

### Server Version and Plugins

CraftBukkit version 3671-Spigot-41150f3-bcedf28 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/qLD5ac1KuGWlevSMz6SKp7Jcz4EbANtx

### Geyser Version

The Newest Version

### Minecraft: Bedrock Edition Device/Version

1.19.71 - 1.19.61.01

**Comment by Elavalur** [comment]
You can disable "command-suggestions=false" on geyser config.

**Comment by Grizzlybln** [comment]
it is fixed when i take off this option?

**Comment by Chew** [comment]
This is due to the game freezing, I'm going to assume "crash" in your case is the game freezing and not actually crashing (i.e., closing unexpectedly).

As @Elavalur said, you can turn that off to make the suggestions not show up, which will help mitigate this issue.
