### ISSUE TITLE
Lag/Crashing on bedrock with ConditionalEvents

### ISSUE THREAD

**Issue by DeepResonanceX** [GeyserMC/Geyser#3631]
### Describe the bug

Hey, so i run a survival server on Java with Geyser installed, i'm using the ConditionalEvents plugin to run certain actions randomly and, specifically, play sounds when those events happen.
I have events that turn PvP on/off for everyone in the server, plays a sound globally and sends a message in chat. I also have events that play a sound every time a player dies, and a different one every time a player is slain by another player.

I've had 2 different problems happen on bedrock clients:
1) one is the game lagging for about 4-6 seconds every time the PvP events run, after that time it all comes back to normal and works as usual, no crashes.
2) Another one is the game lagging for about the same time, and then (on mobile) crashing after respawning, no matter the cause of death. The death sounds play as normal, but then when respawning, u can move for about 3 seconds, then the lag kicks in, and once the game unfreezes it crashes right after. Worth noting the game DOESN'T crash on Windows 10 edition, but on pocket edition it DOES crash.

Whenever issue 1 happens, issue 2 doesn't, and when issue 2 happens issue 1 doesn't, yesterday issue 1 was happening to two other players on my server, while issue 2 was happening to me specifically, all of us were playing on pocket edition at the time. And yes, none of these issues are present for Java players.

### To Reproduce

not sure how to describe EVERYTHING, so here's an example for the events using ConditionalEvents plugin.

FOR ISSUE 1:
event to turn pvp on:

manualpvpon:
    type: player_command
    conditions:
    - '%main_command% == /mpvpon'
    - '%player% == playernamehere'
    actions:
      default:
      - 'cancel_event: true'
      - 'to_all: player_command_as_op: pvp on'
      - 'to_all: playsound_resource_pack: custom.pvpalarm;1;1'
      - 'to_all: message: §r§l[§a§l∆§r§l] PvP§r is now §a§lENABLED§r.'

After setting up the event, run command /mpvpon in-game, bedrock clients lag when this event is executed.

FOR ISSUE 2:
event running for player deaths:

event3:
    type: player_death
    conditions:
    - '%cause% == ENTITY_ATTACK execute dont'
    actions:
      default:
      - 'to_all: playsound_resource_pack: custom.deathlight;1;1'
      dont:
      - 'cancel_event: true'
      - 'to_all: playsound_resource_pack: custom.deathextreme;1;1'
    enabled: true

after setting up the event, kill a bedrock player in-game, then with bedrock client respawn to check if it lags/crashes. happens regardless of if the necessary resource pack with sounds is installed.

### Expected behaviour

All events should play without any lag, and no respawn crash should happen since there's no events running on player respawn.

### Server Version and Plugins

Server is running on Aternos Spigot/Bukkit, 1.19.3
Plugins installed:
- Geyser (1338 iirc) / Floodgate
- ConditionalEvents
- EssentialsX 2.19.7
- LaggRemover 2.0.6
- PlaceholderAPI 2.11.2
- PlayerTimeLimit
- PvPManager
- SkinsRestorer
- SternalBoard 2.0.4
- ViaVersion 4.6.0

### Geyser Dump

https://dump.geysermc.org/fbVYRSx8vhevtukJsvJIcSKVFkHlyWyb

### Geyser Version

1338

### Minecraft: Bedrock Edition Device/Version

1.19.63, Pocket edition and Windows 10 edition

**Comment by Camotoy** [comment]
Please also provide a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by DeepResonanceX** [comment]
> Please also provide a Geyser dump.
> 
> Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

Here, server was closed so i couldn't provide one:
https://dump.geysermc.org/fbVYRSx8vhevtukJsvJIcSKVFkHlyWyb

**Comment by onebeastchris** [comment]
Is this issue still occurring with the latest versions of Geyser & Bedrock? If so, please provide a new geyser dump :)

**Comment by Kas-tle** [comment]
Closing as stale since no update has been provided on this for a few months and there have been changes to how respawn/death screen is handled since then. If this still occurs, feel free to respond and I'll reopen it.
