### ISSUE TITLE
Adding the component tag "minecraft:conditional_bandwidth_optimization" to every entity to fix entity movement stuttering

### ISSUE THREAD

**Issue by ZodiussDev** [GeyserMC/Geyser#3632]
### What feature do you want to see added?

The component tag **"minecraft:conditional_bandwidth_optimization"** could be added to every entity to fix entity movement stuttering. I don't know if this is actually possible to do, but it could be a possible fix to the stuttering that can be seen when an entity moves. You can add it to a behavior pack so it seems like it's something that can be done server side.

[link to bedrock.dev](https://bedrock.dev/docs/stable/Entities#minecraft:conditional_bandwidth_optimization)
_(what this does im pretty sure is like tweens the entity movement so that it looks like an entity is moving smoothly and not just being teleported from one position to another)_

### Are there any alternatives?

no alternatives

**Comment by Kas-tle** [comment]
This component changes the rate at which a vanilla server sends packets. Your understanding of what it does is not really correct. The vanilla server would, when the conditions are met, send movement packets at a lower rate. This would result in choppier motion and is meant to make this sacrifice to preserve performance of the server, not the client.
Also, Geyser cannot add entity components in this sense. The only thing sent to the client with regards to being directly specified in a behavior pack are actor properties, and we don't currently use those anyways. So "implementing" this in Geyser's case would really just mean reducing the rate at which we send movement packets when server performance meets certain conditions. As I've stated, this would lead to choppier movement when active anyways.

**Comment by Camotoy** [comment]
I'm closing this issue due to the reasons Kastle specified. Thank you for your request anyway!
