### ISSUE TITLE
Bedrock players exit en masse

### ISSUE THREAD

**Issue by alanspike02** [GeyserMC/Geyser#3635]
### Describe the bug

I was able to maintain a stable connection until 1.19.3, but since 1.19.4, the number of times a Bedrock player times out from the server has increased dramatically.
It is exactly the same when mediating Waterfall, etc. Bedrock players start to time out one after another around 5 minutes after entering the server.
This does not happen in Java.

### To Reproduce

Using the latest fabric version of geyser/floodgate, join Bedrock and Java in a world (preferably a world that uses commands like the minigame world, but perhaps a normal world can be reproduced).
A few minutes after starting the mini-game, only Bedrock times out one after another.

### Expected behaviour

Bedrock is not timed out and can be played normally.

### Geyser Dump

https://dump.geysermc.org/8HWxuo0G89yP13PqPYXGoOjJUO2UYfFg

### Geyser Version

2.1.0-SNAPSHOT (git-master-7ef0050)

### Minecraft: Bedrock Edition Device/Version

1.19.71, Every device

**Comment by Kas-tle** [comment]
Is this still an issue on the latest version of Geyser?

**Comment by onebeastchris** [comment]
Closing due to no response.
