### ISSUE TITLE
Smithing table not placing

### ISSUE THREAD

**Issue by BeastiePlayz** [GeyserMC/Geyser#3638]
### Describe the bug

i try placing smithing table and it wont let me

### To Reproduce

1. Go to the craft menu
2. craft smithing table
3. 3. place smithing table

### Expected behaviour

The smithing table is supposed to place down

### Server Version and Plugins

Version 1.19.4

Plugins: 
EssenialsX spawn
EssenialsX chat
EssenialsX 
Discord srv
geyser
randomtp
luckperms
skinrestorer
skript
spawntp
TAB
vault
world edit
world gaurd

### Geyser Version

1339 (Bedrock v1.19.30 - v1.19.71)

### Minecraft: Bedrock Edition Device/Version

1.19.71

**Comment by Camotoy** [comment]
I can't reproduce on Paper 1.19.4. Does this issue persist when temporarily removing WorldGuard? You may want to try without other plugins as well.

**Comment by BeastiePlayz** [comment]
> I can't reproduce on Paper 1.19.4. Does this issue persist when temporarily removing WorldGuard? You may want to try without other plugins as well.

This is spigot 1.19.4

**Comment by BeastiePlayz** [comment]
> I can't reproduce on Paper 1.19.4. Does this issue persist when temporarily removing WorldGuard? You may want to try without other plugins as well.

I’ve tried what I can because I need all plugins for the server I’m running

**Comment by onebeastchris** [comment]
Unable to replicate. Update viaversion, geyser, and floodgate, and if the issue still occurs, send a Geyser dump.
