### ISSUE TITLE
double tooltip  issue 

### ISSUE THREAD

**Issue by rishabh098poi** [GeyserMC/Geyser#3639]
### Describe the bug

it shows name of items twice, and even worse for item with lore

### To Reproduce

.

### Expected behaviour

.

### Screenshots / Videos

https://user-images.githubusercontent.com/108084146/227698390-6e350f2f-7485-46c0-89b5-2d5159b44b02.mp4

### Server Version and Plugins

I'm user , but plugin ( slimefum and addons) 

### Geyser Dump

.

### Geyser Version

.

### Minecraft: Bedrock Edition Device/Version

1.19.71.02 

### Additional Context

.

**Comment by Camotoy** [comment]
This should be a Bedrock client bug; there's nothing we can do.
