### ISSUE TITLE
[ Bug ] Citizens and presumed all NPC Plugins. Names longer than 9 characters do not show for Bedrock Edition

### ISSUE THREAD

**Issue by Yomamaeatstoes** [GeyserMC/Geyser#3640]
### Describe the bug

When you create a NPC, names longer than 9 characters do not appear for bedrock players. 

The bug works like this, example qwertyuiop won't appear because it has 10 characters, but qwertyuio would appear because it has 9.

### To Reproduce

Download a npc plugin, like citizens and create a NPC - for citizens it is /npc create qwertyuiop and it won't appear.
Of course if you type qwertyuio it would because it has 9 characters.

### Expected behaviour

You should be able to create names larger than 9 characters.

### Server Version and Plugins

git-Paper-470 ( MC: 1.19.4 )

My plugins are DisableBreeding, DiscordSRV, dynmap, ElytraSpeed, floodgate, Geyser-Spigot, GlobalTrackedMaps, HarmonyScoreboard, IridiumSkyblock, LuckPerms, mcMMO, Multiverse-Core, Multiverse-NetherPortals, Parkour, PL-Hide, PlaceholderAPI, PlayerBountiesPlus, PlayerKits, ProtocolLib, ScoreboardChatShop, *SecondThreadAPI, SilkySpawnersLITE, Skywars, spark, Spartan, *Spleef, StackMob, StormerAntiNetherRoof, StormerAntiSpam, StormerHomesReloaded, StormerTPAReloaded, StormerWarpsReloaded, Themis, TNTRun_reloaded, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin

![IMG_3198](https://user-images.githubusercontent.com/114538961/227781603-9bd45612-50ca-4b5a-878c-460a101182e5.jpg)

### Geyser Dump

https://dump.geysermc.org/S4BclflsQP26RqHLquluImdLPRujIjs4

### Geyser Version

https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1340/

### Minecraft: Bedrock Edition Device/Version

All Bedrock, PC, iPhone, and presumably more

### Additional Context

None

**Comment by Kas-tle** [comment]
I haven't looked into this at all, but at face value surely this has to be a bedrock client issue...?

**Comment by Kas-tle** [comment]
What client version are you using?

**Comment by Yomamaeatstoes** [comment]
Minecraft Bedrock Edition version I was on is 1.19.71 

The server is running on 1.19.4 paper This server is running Paper version git-Paper-473 (MC: 1.19.4) 
Previous version: git-Paper-471 (MC: 1.19.4)

**Comment by Yomamaeatstoes** [comment]
Oh yea and they also show a [28.03 21:14:27] [Server] [WARN] [Geyser-Spigot] Could not find an entity definition with type TEXT_DISPLAY

**Comment by Yomamaeatstoes** [comment]
Issue has been fixed
