### ISSUE TITLE
Bedrock players getting timed isue

### ISSUE THREAD

**Issue by kyotalcfr** [GeyserMC/Geyser#3642]
### Describe the bug

when joining with bedrock, it will disconnected

### To Reproduce

1. Joining Server
2. Kicked by timed out

### Expected behaviour

Can join the server

### Geyser Dump

https://dump.geysermc.org/gbf6Y5x5rcXMJOiSqatzHij0LIgUcsC9

### Geyser Version

 Geyser version 2.1.0-SNAPSHOT (git-master-7474d2c)

### Minecraft: Bedrock Edition Device/Version

1.19.71

**Comment by Kas-tle** [comment]
Please join our Discord server for help with this: https://discord.gg/geysermc

**Comment by kyotalcfr** [comment]
I fix it. Thanks
