### ISSUE TITLE
Cannot connect to world:

### ISSUE THREAD

**Issue by Larika-Dev** [GeyserMC/Geyser#3643]
### Describe the bug

I downloaded Geyser and Floodgate and put them in the plugins folder for my Feather Paper Server, whenever I try to join from my PC or phone it is unable to connect to the server, which is a problem. I even tried localhost. Help me please!

### To Reproduce

Download Geyser and Floodgate
Put them in your plugins folder.
Start the server.
Join from Bedrock Edition
Bawl your eyes out.

### Expected behaviour

I expected this to allow me to connect from bedrock easily and simply so my friends could join from bedrock.

### Geyser Version

Build#38

### Minecraft: Bedrock Edition Device/Version

Phone, PC

**Comment by Camotoy** [comment]
Please join our Discord server for assistance here, as "Unable to Connect to World" is not a bug with Geyser but almost certainly just something that requires more configuration. Thanks.
