### ISSUE TITLE
Shulkers are the wrong color

### ISSUE THREAD

**Issue by DUDEbehindDUDE** [GeyserMC/Geyser#3646]
### Describe the bug

When using `/summon shulker` or spawning a shulker from a spawn egg, they are the wrong color.

### To Reproduce

1. Open world
2. run `/summon shulker`

### Expected behaviour

The shulkers should be purple

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/66212375/227840031-3e7ffda0-a8d6-4c79-aa89-03fa2558fdf8.png)

### Server Version and Plugins

Running on Fabric 1.19.4, installed mods:
![image](https://user-images.githubusercontent.com/66212375/227840565-cc078da2-37f7-4fad-9305-a3c4173cb0ea.png)

### Geyser Dump

https://dump.geysermc.org/1ESNuGDlJEX8oO5S58kk3CvlnnKulnu5

### Geyser Version

2.10-SNAPSHOT (git-master-a7c04d5) (fabric)

### Minecraft: Bedrock Edition Device/Version

1.19.71

**Comment by DUDEbehindDUDE** [comment]
I would assume this is a similar issue to #1112

**Comment by Kas-tle** [comment]
Please try the build artifact from https://github.com/GeyserMC/Geyser/actions/runs/4529182243 once the run is finished and see if it resolves the issue for you.

**Comment by DUDEbehindDUDE** [comment]
Thank you! I tried the build artifact and it has resolved the issue for me. I appreciate your help!
