### ISSUE TITLE
sometimes bedrock players can't send chat on server (not muted)

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#3657]
### Describe the bug

hmm there is none of warn & error msgs on my standalone geyser 

### To Reproduce

all of bedrock players are fine to chat but some times goes passed and starting to happend (not able to send chat) 

### Expected behaviour

i am not sure am i only getting this issue but yeah if any other users having this issue then chat on here

### Screenshots / Videos

force-key-authentication = false on velocity Velocity 3.2.0-SNAPSHOT
Build #2471 
enforce-secure-profile=false on Purpur-1952 (MC: 1.19.4)*

### Server Version and Plugins

Current: git-Purpur-1952 (MC: 1.19.4)*
* You are running the latest version
* 
![image](https://user-images.githubusercontent.com/88581750/229498928-80e1c40f-6516-4984-9c31-986ea1257336.png)

### Geyser Dump

https://dump.geysermc.org/mh0mAvm02YRftxRksmrRHtJZLXSmjGHQ

### Geyser Version

2.1.0-SNAPSHOT (git-master-0f99abc)

**Comment by onebeastchris** [comment]
Could you try updating to the latest version of Geyser, and see if the issue persists? The way we handle checking for the secure profile requirement has changed.
If the issue persists, send a new Geyser dump by running "geyser dump" in your server console.

Additionally. please attach a log from the backend server where players are not able to chat.

**Comment by onebeastchris** [comment]
Closing due to no response.
