### ISSUE TITLE
Certain Server-Side Fabric Mods Do Not Display Mod Features Or Function Incorrectly

### ISSUE THREAD

**Issue by Merancapeman** [GeyserMC/Geyser#3660]
### Describe the bug

I'm using Geyser Fabric in order to allow the use of server-side mods using Fabric on Bedrock clients so my family (mostly Bedrock users) and I can benefit from using commands and other functions. In particular, I'm utilizing server-side mods made by Patbox. In the screenshot included I'm using his mod called "Universal Shops" which allows players and admin to create personal/admin shops where you can trade one item for another that you specify. It works perfectly fine on Java clients, as expected. However, I brought it to Patbox's attention that when accessed on Bedrock clients, the custom ui that appears does not allow things to be edited, and the text is difficult to interpret. 

Here is his mod functioning on a Java client. This is what you can expect to see when it is working, and you can utilize the custom UI just fine.
![Screenshot 2023-04-03 025518](https://user-images.githubusercontent.com/13242139/229501258-c0722995-268f-499d-87ce-b754afc34e4e.png)

Here is his mod on a Bedrock client.
![Screenshot 2023-04-03 023443](https://user-images.githubusercontent.com/13242139/229501962-f4373c38-c943-42bf-893e-cd1dbe9bc6d9.png)

Patbox suggested it was a Geyser error, saying this:
![Screenshot 2023-04-03 025750](https://user-images.githubusercontent.com/13242139/229502255-6ff281e6-ef48-4e55-baea-99869832c0bd.png)

### To Reproduce

So far this issue only presents itself with this mod installed, but I have yet to discover other server-side mods that may utilize the same functions or custom UI's.

### Expected behaviour

UI functions should operate in Bedrock similar to how they function on Java clients, or at least call upon the same text data that they do in Java so they at least appear similar.

### Server Version and Plugins

Server: Geyser Fabric 1.19.4
Mods Installed So Far:  
![Screenshot 2023-04-03 080418](https://user-images.githubusercontent.com/13242139/229503869-d70e5693-420b-4cef-81e2-a3dba0fc5a5a.png)

### Geyser Dump

https://dump.geysermc.org/1nC8RbVaooOwDOEyuLtDPgbodnW81OPL

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-0f99abc)

### Minecraft: Bedrock Edition Device/Version

Windows 10 version 1.19.73

**Comment by Camotoy** [comment]
Patbox's comment is helpful, thanks. It appears that our chat serialization library supports the new chat fallback feature, and it *should* be relatively seamless to implement.

**Comment by Merancapeman** [comment]
Not sure if it's worth updating, but it looks like this problem occurs with other mods (which is probably like... DUH, lol) including Hey That's Mine for Fabric 1.19.4: 

![geyserissue](https://user-images.githubusercontent.com/13242139/230003843-baa774c0-abbd-4952-97bc-b793d135ff44.gif)

**Comment by Patbox** [comment]
This is the same issue, as both mods use same api for server translations (which uses fallbacks since 1.19.4, as it is just nicer option)

**Comment by Camotoy** [comment]
This issue should be fixed with this build: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/feature%252Fprotocol-3.0/ but please note this is an unstable branch and there may be more bugs than usual.

**Comment by Merancapeman** [comment]
This is most definitely improved, and I appreciate the work it must have taken to fix this. Currently, some values are showing up as %s such as in this case, or commands from mods like Get Off My Lawn where values show up likewise. Here is an example: 
![image](https://user-images.githubusercontent.com/13242139/232111620-8bea98b3-48be-4ac8-9220-b847f12fb9a8.png)


I hope this helps! Thanks for your toil!

**Comment by onebeastchris** [comment]
that looks like an issue with the mod's placeholders; do they work on java?

**Comment by Merancapeman** [comment]
Double checking now, will update this comment in a second

**Comment by Patbox** [comment]
Geyser (or Adventure) doesn't handle translation fallback correctly here. It uses it as final value, instead of a template (like vanilla)

**Comment by Camotoy** [comment]
Noted; will see what I can do.

**Comment by Merancapeman** [comment]
Another example from a different mod such as GOML.

Bedrock: 
![image](https://user-images.githubusercontent.com/13242139/232114573-aaa0f3d5-e38a-4243-bf97-517eabbb1bfa.png)

Java:
![image](https://user-images.githubusercontent.com/13242139/232115293-eccb98a5-65b8-4577-8fad-1749a52e63f2.png)

(not sure if this helps, just posting it here for reference just in case)

**Comment by lgc2333** [comment]
same issue, will subscribe

**Comment by Camotoy** [comment]
This should be fixed in the next Protocol 3.0 build. Thanks as always to the Adventure folks for addressing this quickly on their end.
