### ISSUE TITLE
Geyser-Spigot.jar gets flagged as malicious

### ISSUE THREAD

**Issue by mczero80** [GeyserMC/Geyser#3662]
### Describe the bug

I got a warning from my web hoster that malicious software was detected (mining software or something else). 
In the process of finding the culprit, I uploaded the recent Geyser-Spigot.jar to VirusTotal. It there got flagged as malicious by one security vendor, namely Ikarus, which detected a Trojan.Java.GenericGBA variant.

I am sure this is a false positive, but nonetheless, if my web service gets suspended, it is a problem for me and maybe others.

The Geyser-Spigot.jar is downloaded as usual from geysermc.org and not built from source by me.

### To Reproduce

1. Upload Geyser-Spigot.jar to VirusTotal.com
2. See the results

### Expected behaviour

Not being flagged as malicious

### Geyser Version

Build #47 2.4.2023

**Comment by Camotoy** [comment]
I can replicate this behavior, but it would seem that, unless this flagging is recent, someone would have to identify which commit specifically this started (and that's a LOT of commits).

It could also just be flagging how we read the CPU name. That would be an easy first test.

Notable GitHub issue: https://github.com/srikanth-lingala/zip4j/issues/232

**Comment by Kas-tle** [comment]
Yeah identifying the specific commit will be made yet more difficult by the fact that it seems the CI was purged quite recently and we now only have the last 30 builds.

**Comment by Camotoy** [comment]
The OpenCollab CI has always worked like that.

**Comment by Kas-tle** [comment]
Actually good news it appears the oldest build on the CI does not have the flag so I can ping pong back and forth til I find it

**Comment by Kas-tle** [comment]
Ok so I cannot get the exact number because it seems the last 1.19.3 build was saved due to the notice being placed on it... so basically it happened somewhere after 1321 and before or on 1331.

**Comment by Kas-tle** [comment]
I have found the cause. Unfortunately it seems to be flagging on an external library that is required for Geyser, so I don't think much can be done here. I sent the following email to Ikarus in hopes that they will resolve the issue... though I am less than optimistic as unlike many of the vendors on VirusTotal, they do not seem to have any official mechanism to report false flags.

> Hello,
> 
> I contribute to an open source project called GeyserMC. It has come to my attention that your vendor analysis on VirusTotal flags our compiled jar as "Trojan.Java.GenericGBA". On investigation, I have found that this seems to be due to our inclusion of the Java-Websocket library, specifically the class org.java_websocket.server.WebSocketServer. See https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/server/WebSocketServer.java. Uploading the compiled class alone leads to a flag from your analysis tool. This seems to be a fairly obvious false flag, as this library is used fairly commonly, as evidenced by its 10k stars on GitHub and 2.5k forks. If you could remove this false hit, that would be greatly appreciated.
> 
> For reference, you can find the GeyserMC project here: https://github.com/GeyserMC/Geyser. The jar in question that produces the flag can be downloaded from https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot. The specific cause can be confirmed by decompressing the jar and running the enclosed classfile org/java_websocket/server/WebSocketServer.class. This can also be confirmed by directly compiling the Java-WebSocket library, and uploading the referenced class file.
> 
> Thank you for your time and consideration.
> 
> Kind regards,
> 
> [...]

**Comment by Kas-tle** [comment]
I have received the following reply from Ikarus, so this should be resolved at some point in the future. Once this has been resolved, you can force a re-analysis on VirusTotal by either using the original analysis result link, or uploading the file, and clicking the circular arrow icon on the right side of the page. 

> Dear Ladies and Gentlemen,
> Sehr geehrte Damen und Herren,
> 
> Many thanks for the delivered file.
> 
> ***** false-positive *****
> 
> The false positive was removed and should not occur any more after our next database update.
> 
> This is an automatic generated e-mail, please do not reply.
> 
> 
> 
> Vielen Dank für die von Ihnen eingesandte Datei.
> 
> ***** Fehlalarm *****
> 
> Bei dieser Datei handelt es sich um einen Fehlalarm. Dieser wurde ausgebaut und wird mit dem nächsten Update nicht mehr auftreten.
> 
> Dies ist eine automatisch generierte Nachricht, bitte antworten Sie nicht auf diese Nachricht.
> 
> Kind Regards,
> Mit freundlichen Grüßen
> 
> ----------------------------------
> IKARUS Security Software GmbH
> Analyse
> Blechturmgasse 11, A-1050 Wien
> Web: http://www.ikarussecurity.com/
> ----------------------------------

**Comment by Kas-tle** [comment]
I have successfully reanalyzed our jar on VirusTotal and there are no longer any flags, so this can be closed.
See https://www.virustotal.com/gui/file/17f09829cda4a6859aec2b4c6ae64c3a0885dfe0b224f9d437f81ae2830e37b0.

**Comment by Camotoy** [comment]
Thank you for your work here, Kastle.
