### ISSUE TITLE
Resource packs being ignored, not downloading/applying

### ISSUE THREAD

**Issue by DeepResonanceX** [GeyserMC/Geyser#3664]
### Describe the bug

Hey, i'm having an issue with bedrock resource packs being entirely ignored when joining a server, i have 2 resource packs inside the Geyser packs folder that i use to play custom sound effects on my server, i used to have just one (which current players in my server were able to download with no issues), but then i wanted to update the resource pack to add new sounds, from here on out 2 things happened:

1- i updated that same pack and uploaded it as to not have to make a new pack and just have ALL of my sounds in one pack, when i uploaded it, connecting to the server on bedrock wouldn't prompt me to download the server's resource packs, and so, the updated pack wasn't downloaded.
2- I made an entirely new pack with JUST the new sounds, named it something different and edited the pack description. Again, connecting to the server would still entirely ignore the new resource pack.

Yes, the pack IS a bedrock resource pack, i ported it myself from Java manually, and tested in singleplayer as well, everything works as intented, the only issue here is Geyser not pushing the resource pack to bedrock players joining the server.

### To Reproduce

upload bedrock resource packs to the Geyser packs folder, then join in on a bedrock client

### Expected behaviour

all resource packs inside the packs folder should be downloaded for bedrock players upon joining the server

### Server Version and Plugins

Server is running on Aternos Spigot/Bukkit, 1.19.3
Plugins installed:

Geyser / Floodgate
ConditionalEvents
EssentialsX 2.19.7
LaggRemover 2.0.6
PlaceholderAPI 2.11.2
PlayerTimeLimit
PvPManager
SkinsRestorer
SternalBoard 2.0.4
ViaVersion 4.6.0

### Geyser Dump

https://dump.geysermc.org/UHJ89oIiECpVAy4i7RMBVEc1ivU2ZV51

### Geyser Version

version 2.1.0-SNAPSHOT (git-master-d7c6865)

### Minecraft: Bedrock Edition Device/Version

1.19.71, Pocket edition and Windows 10 edition

**Comment by Camotoy** [comment]
Would you be able to send a pack that has these issues?

**Comment by onebeastchris** [comment]
Closing due to no response.
