### ISSUE TITLE
Using ExtractableEnchants causes playstation players inventory to crash.

### ISSUE THREAD

**Issue by djoveryde** [GeyserMC/Geyser#3665]
### Describe the bug

When a player selects the enchantment extractor block, and clicks with it on an enchanted item it fails to bring up the menu which allows you to select which enchantment you want to extract.
This in turn bugs their inventory out and if they close it they can no longer open it.
They have to log out and back in again in order to fix this.

### To Reproduce

With the extractable enchantments plugin installed alongside geyser and paper. Create an enchantment extractor.
Select the enchantment extractor and click on any item that is enchanted. It should bring up a menu above the inventory which allows you to select the enchantment you want to extract, however this menu does not come up.
You have to have    "Extraction: SELECTION"    set in the config for this plugin.
Issue only occurs on Playstation version.
Works fine in Java and extracts as expected.

### Expected behaviour

 It should bring up a menu above the inventory which allows you to select the enchantment you want to extract, you then get the extracted enchantment as a book in your inventory.

### Screenshots / Videos

https://www.dropbox.com/s/ctptg3ho3ja9s70/Video%2005-04-2023%2C%2013%2014%2012.mov?dl=0

### Server Version and Plugins

Paper 1.19.4 477
ExtractableEnchants 9.8 https://www.spigotmc.org/resources/extractable-enchantments-remove-enchantments-1-14-1-19.73954/updates
Geyser
Floodgate

### Geyser Version

Geyser 1.19.4 Build 46

### Minecraft: Bedrock Edition Device/Version

Playstation

**Comment by onebeastchris** [comment]
Could you re-send that video, along with screenshots for how the menu would look on java?

**Comment by onebeastchris** [comment]
Closing due to no further response.
