### ISSUE TITLE
Duplication Entity & Sounds

### ISSUE THREAD

**Issue by MrZillaGold** [GeyserMC/Geyser#367]
**Describe the bug**
When turning into any mob on Hypixel via the cosmetics menu, the mob model is duplicated and their sounds too

**To Reproduce**
1. Connect to mc.hypixel.net
2. Turn into any mob using the cosmetics menu
3. Move to a few blocks

**Expected behavior**
No duplication

**Screenshots / Videos**
https://youtu.be/Anr8W-oMi5c

**Server Version**
1.15.2 

**Geyser Version**
latest (Inventory branch)

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by gaussandhisgun** [comment]
this issue is the same type as #311
