### ISSUE TITLE
infinite potion effects aren't supported

### ISSUE THREAD

**Issue by ViaBackwards** [GeyserMC/Geyser#3671]
### Describe the bug

since around 1.19.4 you can set a potion's duration to -1 to make it infinite, geyser doesn't support this.

### To Reproduce

give yourself an infinite potion effect, on bedrock it doesn't appear even though you have it.

### Expected behaviour

Should be infinite

### Server Version and Plugins

This server is running Paper version git-Paper-"29b17a8" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 29b17a8)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-"ad6c14c" (MC: 1.19.4)

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-0f99abc) (Java: 1.19.4, Bedrock: 1.19.30/1.19.31 - 1.19.70/1.19.71)

**Comment by Chew** [comment]
I'd need a Bedrock experts' insight but this is screaming parity issue, does it work in vanilla or is it only an issue on Geyser? What specifically doesn't work? Maybe Bedrock doesn't support infinite potions :(

**Comment by tt-thoma** [comment]
Can confirm on Bedrock 1.19.83, when using the new `infinite` duration

**Comment by Konicai** [comment]
Resolved in #3834
