### ISSUE TITLE
/geyser advancements and /geyser statistics do not work when typed by an unopped bedrock player.

### ISSUE THREAD

**Issue by ghostlyscythe** [GeyserMC/Geyser#3674]
### Describe the bug

When typing either of 
/geyser advancements
/geyser statistics

The command will reply with Unknown command.
![XhV1uNl](https://user-images.githubusercontent.com/46621990/230904955-b1fa06e2-ddea-4044-ba7a-8fa10302f968.png)

Yes Xbox achievements are disabled.
Yes it is the most recent update of geyser.

### To Reproduce

Download latest version  geyser
Set xbox achievements to be disabled in config.
Give permissions for commands.
Type /geyser advancements 
Type /geyser statistics

Op that bedrock account and try again.

### Expected behaviour

When typed it shows the relevant tab open.

### Geyser Dump

https://dump.geysermc.org/hNX2U1q5xH9vc0U6Tnfcbb29WZ0siF2H

### Geyser Version

Build #1350 (2 Apr 2023, 20:43:04)

### Minecraft: Bedrock Edition Device/Version

Latest versions of bedrock (Any device)

**Comment by rtm516** [comment]
Please can you try the below commands replacing `username` with a players username that should have permissions
```
/lp user username permission check geyser.command.advancements
/lp user username permission check geyser.command.help
/lp user username permission check geyser.command.statistics
```

**Comment by ghostlyscythe** [comment]
> 
![UA0Zdig](https://user-images.githubusercontent.com/46621990/230910756-d43d4dbd-8eff-42fb-b093-be5e56e1bf03.png)

**Comment by YHDiamond** [comment]
Hey, can you send a picture of the response you get when you try and run the geyser command? I believe if you do not have permission it will say that instead of saying unknown command.

**Comment by ghostlyscythe** [comment]
We actually figured out the issue. You need to give "geyser.command" persmission and then it will allow you to. Just isnt listed int he perms on the wiki
