### ISSUE TITLE
Enderman/Enderdragon Spawneggs Bug

### ISSUE THREAD

**Issue by BigJoys** [GeyserMC/Geyser#3675]
### Describe the bug

I found a bug with the spawnneggs. If you take an Enderman Spawnegg in the Bedrock Editon from the Creative you get an Enderdragon Spawnegg (Visually it is an Enderman Spawnegg in the Bedrock Edition, but if you look with Java it is an Enderdragon Spawnegg. Enderdragons are spawned as well. ) If you give yourself the Enderman Spawnegg via the /give command you will get the correct Spawnegg.

Furthermore you can take Llama Spawneggs in the Bedrock Edition but they are not shown in the Java Edition. Trader Llama Spawneggs (Java available, Bedrock not) are visible as Llama Spawneggs (If given with /give), if taken via Creative-Mode not visible at all. 

### To Reproduce

1. Get a Enderman Spawnegg in the Bedrock Edition from the Creative menu.
2. See which spawnnegg with the Java player which spawnnegg he holds in his hand or with /invsee.
3. If necessary, the Enderman/Enderdragon Spawnegg can also be used and an Enderdragon will be spawned, although the Bedrock player is actually holding an Enderman Spawnegg in his hand.

### Expected behaviour

Regarding the Enderman Spawnegg: That I get an Enderman Spawnegg and not an Enderdragon Spawnegg.

### Screenshots / Videos

![EggBug](https://user-images.githubusercontent.com/17522244/231568331-79dd9e74-3ff2-4ea6-b3b3-83c49577acb7.PNG)

### Server Version and Plugins

This server is running Paper version git-Paper-327 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: adb8e49)
You are 121 version(s) behind
Download the new version at: https://papermc.io/downloads

Plugins (17): CoreProtect, Essentials, EssentialsChat,
EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit
(WorldEdit), floodgate, Geyser-Spigot, GriefPrevention,
LuckPerms, Multiverse-Core, Multiverse-Portals, MyPet,
ViaBackwards, ViaVersion, VoxelSniper, WorldGuard

### Geyser Dump

https://dump.geysermc.org/pTkvcR6yngd8I0izULEwVTaZuzW2rG5h

### Geyser Version

2.1.0-SNAPSHOT (git-master-0f99abc)

### Minecraft: Bedrock Edition Device/Version

Windows 10 Editon, Mobile Edition

**Comment by TBYT** [comment]
Bumping this as this is a problem for me too.

**Comment by TBYT** [comment]
I also find that the wither skeleton spawn egg, spawns the wither. Llama spawn egg does not spawn anything. And these are the spawn eggs you pull from the creative inventory on bedrock.
