### ISSUE TITLE
Scoreboard on sidebar causes bedrock client to crash

### ISSUE THREAD

**Issue by viciscat** [GeyserMC/Geyser#3677]
### Describe the bug

So on my aternos server I added a scoreboard on the sidebar that displays the number of deaths for the funsies. When my friend on xbox joined the next morning, he crashed instantly.

### To Reproduce

1. Create a scoreboard
2. Display it on the sidebar
3. (I added values manually with `/scoreboard players add <user> deaths 5` cuz i added the scorebeard a bit late)
4. Join on bedrock client and witness crash

### Expected behaviour

I dunno don't crash

### Screenshots / Videos

Tried to reproduce on Bedrock PC, but couldn't be replicated

### Server Version and Plugins

git-paper-510 (MC: 1.19.4)
floodgate

### Geyser Dump

https://dump.geysermc.org/sku0zeZgYPOWISEdUfSmhpsqEbQoPcyg

### Geyser Version

2.1.0-SNAPSHOT(git-master-0f99abc)

### Minecraft: Bedrock Edition Device/Version

xbox series x, 1.19.73, connected use BedrockTogether

### Additional Context

None

**Comment by onebeastchris** [comment]
Does this issue still occur with the latest version of Geyser & Bedrock edition?

**Comment by onebeastchris** [comment]
Closing due to no response.
