### ISSUE TITLE
Distinguish BE players from JE players

### ISSUE THREAD

**Issue by Zhwt** [GeyserMC/Geyser#368]
**What feature do you want?**
We can distinguish Bedrock Edition players from Java Edition players.

Currently I'm not sure how to do this. For example they can have a special permission node like `geyser.player`, and I can check this permission to figure out if the player is a BE player or not. Or we can hook into permission system like LuckPerms and set some meta data.

Using conditions:
* When the player is joining via Android, I could adjust the chest menu and remove some unnecessary features like animated lore or frequently updated chests.
* Limiting their action such as pouring water, ~fishing~(fixed in PR#353), hanging paintings, etc. This can be a temporary workaround when some feature is missing implementation, many issues can be bypassed using similar mechanics.
* Or just simply add some custom prefixes.

**Alternatives?**
N/A

**Comment by Tim203** [comment]
You can use [Floodgate](https://github.com/GeyserMC/Floodgate) for this.
It also has an API so you can do more then knowing that the player is a Bedrock player.

**Comment by RednedEpic** [comment]
We also send this data through the mc:brand plugin message.
