### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [GeyserMC/Geyser#3680]
### Describe the bug

This is the error >> https://mclo.gs/Ejk1HgG

### To Reproduce

Download Geyser and Floodgate from the website

### Expected behaviour

No error in console

### Server Version and Plugins

  [Sat 03:01:48 INFO ] Checking version, please wait...
  [Sat 03:01:48 INFO ] Current: git-Purpur-1957 (MC: 1.19.4)*
* You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Geyser Dump

https://dump.geysermc.org/awyNZE2LmvB3FmM21f0UYm8LbFkgzKcy

### Geyser Version

  [Sat 03:02:50 INFO ] Geyser-Spigot version 2.1.0-SNAPSHOT   [Sat 03:02:50 INFO ] Website: https://geysermc.org   [Sat 03:02:50 INFO ] Author: GeyserMC

### Additional Context

Using floodgate and mysql database too.

**Comment by onebeastchris** [comment]
I think this should be safe to ignore?
In any case; this should be transferred to the floodgate repo
