### ISSUE TITLE
Incorrect Player Identification for Global Linked Players

### ISSUE THREAD

**Issue by DarkChromaMC** [GeyserMC/Geyser#3684]
### Describe the bug

We have observed an issue where players who linked their accounts (via https://link.geysermc.org/) and connect using Bedrock Edition are mistakenly identified as using the Vanilla Java Edition client. We could test this by running the command `/geyser list` and seeing it does not list them as GeyserMC players. 

When a linked player joins using Java Edition, they are identified as Java players and not listed in the /geyser list. Therefore, whether the linked player joins using Java or Bedrock Edition, both sessions will show them as a Java Edition player/client. This can be observed because their UUID remains the same as the Java type (e.g., cc60aa9c-87db-45f9-84e5-a494e59db5d7).

This misidentification has significant consequences, as it leads to plugins like Anti Cheats falsely detecting linked players (on Bedrock Edition) as Java users when they are actually playing on Bedrock Edition. This incorrect identification results in false checks and consequently bans. Anti-cheat plugins rely on the Global GeyserMC API to determine whether a player is GeyserMC client or Floodgate to exempt them from checks.

### To Reproduce

1) Join the server using Java Edition.
2) Observe that the player is seen as using the Vanilla client, and /geyser list does not list them as a GeyserMC player.
3) Disconnect and then join the server using Bedrock Edition.
4) Notice that the player is still identified as a Java player and not listed in /geyser list. The UUID remains the same as the Java version.

### Expected behaviour

When a linked player joins using Bedrock Edition, they should be correctly identified as a Bedrock player and listed in the /geyser list.

### Server Version and Plugins

Minecraft version: 1.19.2
Floodgate API version: 2.2.2-SNAPSHOT (b77-089b9a7) (branch: master)
GeyserMC version: 2.1.0-SNAPSHOT (git-master-96260cc) (Java: 1.19.4, Bedrock: 1.19.30/1.19.31 - 1.19.70/1.19.71)
Server operating system: Pufferfish+ Purpur
Anti-cheat plugin name and version: Vulcan 2.7.3

### Geyser Dump

https://dump.geysermc.org/1IroPMLavjq3oitTdgPsE15I28UOKg5p

### Geyser Version

2.1.0-SNAPSHOT (git-master-96260cc) (Java: 1.19.4, Bedrock: 1.19.30/1.19.31 - 1.19.70/1.19.71)

**Comment by Camotoy** [comment]
This is very likely just a Floodgate issue, so we'll keep the issue within that repository. Thanks.
