### ISSUE TITLE
Ender Dragon Boss Bar not visible 

### ISSUE THREAD

**Issue by OxygenCodez** [GeyserMC/Geyser#3690]
### Describe the bug

I want playing on my SMP, Its paper & have latest version of geyser.
In the end we noticed that the boss bar isnt visible to bedrock clients (visible to java clients)

### To Reproduce

Go into end with a bedrock client

### Expected behaviour

The bossbar should be visible as of wither for bedrock clients

### Screenshots / Videos

![Screenshot_20230422-100455_Minecraft](https://user-images.githubusercontent.com/122032829/233763009-0e52e869-be12-4a57-ba72-31b15d6e4104.jpg)

### Server Version and Plugins

1.19.4
Geyser, Floodgate

### Geyser Dump

https://dump.geysermc.org/vwrMNph2LcsVoPDkUWp2mHvGiSeaEy4o

### Geyser Version

2.1.0. Snapshot

### Minecraft: Bedrock Edition Device/Version

1.19.73

**Comment by Jens-Co** [comment]
Thanks, I was able to replicate this behavior. For now you could fix this by a client relog while in the end.

**Comment by onebeastchris** [comment]
This should be fixed now; could you try updating Geyser to the latest version?

**Comment by onebeastchris** [comment]
Closing due to no response.
