### ISSUE TITLE
Warning In GeyserStandalone

### ISSUE THREAD

**Issue by lecatos** [GeyserMC/Geyser#3693]
### Describe the bug

When I launch geyser standalone latest version it gives me this warning:

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.

It doesn’t seems right. How to fix it?

My Java version:
openjdk 17.0.7 2023-04-18 LTS
OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (build 17.0.7+7-LTS, mixed mode, sharing)

### To Reproduce

Launch geyser

### Expected behaviour

No warning

### Geyser Version

Latest

**Comment by Camotoy** [comment]
I'll leave this open, but this should just be an error from the logger and it should not affect game performance.
