### ISSUE TITLE
user IPs are no longer their actual IPs while using PROXY Protocol 

### ISSUE THREAD

**Issue by kuohsuanlo** [GeyserMC/Geyser#3703]
### Describe the bug

My use case involves the use of UDP's PROXY Protocol v2. In GeyserMC (bungeecord) version 1335, the user's are their actual IPs. https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1335/

I switched to the latest version of GeyserMC and found that the user's IP location has become the IP of the Proxy, rather than the user's original IP. I switched GeyserMC back to 1335 and was able to correctly display the user's original IP again. 
``

### To Reproduce

1. Use latest 1.19.80 geyserMC on bungeecord with UDP proxy protocol v2.
2. Log in through the proxy.
3. Found that user IPs are no longer their actual IPs but the proxy IPs.
4. Switch back to geyserMC older version, say 1335 https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1335/
5. Found that user IPs are now their actual IPs.

### Expected behaviour

User IPs should be their actual IPs.

### Geyser Version

[#1352](https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1352/)

**Comment by iVillager** [comment]
Up, this is a breaking issue

**Comment by CreationMC1** [comment]
Bump - Needed fixed asap

**Comment by Camotoy** [comment]
Please do not bump this issue - we are aware of the importance of the bug and are working to resolve it.

**Comment by CreationMC1** [comment]
> Please do not bump this issue - we are aware of the importance of the bug and are working to resolve it.

Yet, it takes you more than five days to either address a critical bug or even acknowledge its significance. Makes sense

**Comment by onebeastchris** [comment]
dude, this is free open source software.. If you're that adamant about getting a fix, go ahead and try to make one. 
You can't? Well, then you'll have to wait. Bumping it, complaining, or being angry about software that you don't even have to pay for will not help anyone.

**Comment by Camotoy** [comment]
My apologies for not addressing the bug on GitHub sooner.

No one on the team is familiar with PROXY protocol, so we're going into this issue largely blind.

**Comment by Chew** [comment]
If you can pinpoint the exact build this started happening, it would help is as well. What build between 1335 and 1352 started causing this issue?

**Comment by Camotoy** [comment]
We know where the bug started, and probably how to resolve it. I promise I've been looking into it, but I don't have anything to report back yet.
