### ISSUE TITLE
Scoreboards now cut off with the 1.19.80 Geyser update

### ISSUE THREAD

**Issue by ItzFlipp** [GeyserMC/Geyser#3705]
### Describe the bug

It seems like since the protocol-3.0 merge, Bedrock clients have experienced text cutoff on their scoreboards. The scoreboard has `...` to indicate it has been cut off.

### To Reproduce

1. Update to the latest Geyser (build 92)
2. Install the TAB plugin: https://github.com/NEZNAMY/TAB
3. Add a scoreboard with any long line (ex: &7&fTest: &atesttesttesttesttesttesttest)

### Expected behaviour

It is expected that Bedrock client scoreboards function the same as Java 1.13+ clients where scoreboard line length can be unlimited without any cutoffs. 

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/53582702/234906838-0249e0ed-1a47-4913-b4f1-a02b55dd7bbb.png)
![image](https://user-images.githubusercontent.com/53582702/234906938-d7ea79f1-ffc1-40d6-89b1-f5620037a9aa.png)

### Server Version and Plugins

Backend: git-Purpur-1933 (MC: 1.19.3)*
Proxy (with Geyser): git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:a24c106:158

### Geyser Dump

https://dump.geysermc.org/qAk1c79MBqBzzt6Tsx878L0nQj44CPIw

### Geyser Version

2.1.0-SNAPSHOT (git-master-c8afd34)

### Minecraft: Bedrock Edition Device/Version

1.19.80 iOS and Windows 11

**Comment by Camotoy** [comment]
This seems like a Bedrock change we might not be able to resolve. But I'll keep my eye out since I know scoreboard lengths are pretty important.

**Comment by alek4032** [comment]
We're experiencing a similar issue on our server; however, ours seems to be more random. Some scoreboard lines work and are much longer, while others are shorter and only show the ... instead of the placeholder outcome

![7cd6e49e2b65a4e88bce6789c3bb107d](https://user-images.githubusercontent.com/119686785/234996316-1240ae06-7b1e-46ba-8a1b-0ac7c71c26a9.png)

**Comment by mxson** [comment]
I've noticed that if the scoreboard line contains a unicode character (example: "▪"), then the scoreboard line text will render at a smaller size, allowing more characters per line.

**Comment by JH3Y50N** [comment]
> I've noticed that if the scoreboard line contains a unicode character (example: "▪"), then the scoreboard line text will render at a smaller size, allowing more characters per line.

Simple, just replace all scoreboard packets with unicode dot

This is not a normal dot, is a unicode char dot:
`․`

**Comment by Agaloth** [comment]
I've released a fix made with JSON UI, you can find the pack here! https://github.com/Agaloth/ScoreboardLimitFix

**Comment by Agaloth** [comment]
It should work perfectly, let me know if there are any bugs, I'm adding a PR for GeyserOptionalPack @mxson @alek4032 @ItzFlipp

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/GeyserOptionalPack fixes this issue - closing this :p
