### ISSUE TITLE
ENCHANTMENTS EXPLOSION NO WORKING

### ISSUE THREAD

**Issue by Olavvvv** [GeyserMC/Geyser#3707]
### Describe the bug

when my bedrock users try to mine with an explosive pick they can't, it's like the plugin doesn't work (advancedenchantments)
and when throwing the pick with the q, an error appears in the console
I am on the latest version of geyser and floodgate, it started to happen when updating

### To Reproduce

AdvancedEnchantments
Use "Trench" enchant

### Expected behaviour

a

### Screenshots / Videos

a

### Server Version and Plugins

a

### Geyser Version

Build #93

### Minecraft: Bedrock Edition Device/Version

Bedrock/PC/Movile version (last)

### Additional Context

a

**Comment by onebeastchris** [comment]
Dont make an issue report like that.
We need more details. Include a server log (latest.log from the logs folder, upload it to mclo.gs & send the link here), a geyser dump (run geyser dump in the console and send the link here), and include the description of what expected behaviour would be....
