### ISSUE TITLE
ENCHANTMENTS EXPLOSION NOT WORKING (ADVANCEDENCHANTMENTS)

### ISSUE THREAD

**Issue by Olavvvv** [GeyserMC/Geyser#3708]
### Describe the bug

when my bedrock users try to mine with an explosive pick they can't, it's like the plugin doesn't work (advancedenchantments)
and when throwing the pick with the q, an error appears in the console
I am on the latest version of geyser and floodgate, it started to happen when updating

### To Reproduce

1. AdvancedEnchantments
2. Use Enchantment "Trench" (3x3)

explosivo:
  display: '%group-color%Explosivo'
  description: 'Rompe en un area de 3x3x3'
  applies-to: 'Tools'
  group: 'FABLED'
  type: 'MINING'
  applies:
    - 'ALL_AXE'
    - 'ALL_PICKAXE'
    - 'ALL_SPADE'
  levels:
    '1':
      chance: 100
      effects:
        - 'CUSTOM_TRENCH:3:3:3'
        - 'REPAIR %victim%'
        - 'EXP:1'

### Expected behaviour

the pick must sting in a 3 block radius, and it will give the minerals, but it does not explode or give minerals

### Screenshots / Videos

https://imgur.com/eLWj0ds

### Server Version and Plugins

i use velocity

### Geyser Version

Build #93

### Minecraft: Bedrock Edition Device/Version

1.17.80 (PC/Movile)

**Comment by onebeastchris** [comment]
Why didnt you just edit your last issue?
Additionally, there still is no geyser dump / log file.

**Comment by Olavvvv** [comment]
Sorry, I didn't run the geyser dump, now I'm running the old version since the new one was buggy, I'm sending you the log.

https://anonymfile.com/NVDYl/2023-04-27-2.log

**Comment by onebeastchris** [comment]
Could you try updating Geyser to the latest version and see if that fixes the issue?

**Comment by onebeastchris** [comment]
This should be resolved now; can be closed
