### ISSUE TITLE
Files uploaded to Modrinth should have different names.

### ISSUE THREAD

**Issue by derspyy** [GeyserMC/Geyser#3709]
### What feature do you want to see added?

it would be interesting if every file uploaded to modrinth had its own filename because updating through ferium is currently broken.

> ➡️ https://github.com/gorilla-devs/ferium/issues/140 

my idea is for either the commit or snapshot number be appended to the filename for both geyser and floodgate.
(also possibly remove the capital letters from geyser's file names for consistency) 😊

some idea examples:

`geyser-fabric-2.1.0+build.94.jar` < similar to sodium's
`geyser-2.1.0+fabric.8a25afb.jar` < similar to starlight's

### Are there any alternatives?

currently, none

**Comment by Gaming32** [comment]
Removing [this line](https://github.com/GeyserMC/Geyser/blob/master/bootstrap/fabric/build.gradle.kts#L93) *should* be all that needs to happen.

**Comment by derspyy** [comment]
for reference, my solution was a name similar to sodium's.

closing since it's been addressed in a pr.
