### ISSUE TITLE
Anvil Keeps Rejecting Because Of Bedrock Creative Book

### ISSUE THREAD

**Issue by lrj1818** [GeyserMC/Geyser#3711]
### Describe the bug

If Bedrock Client Is Gamemode Creative And Grabs Mending Book Or Any Kind The Anvil Rejects It Only If You Trade With Villagers Or Java Player Gives Mending Book You Can Anvil The Mending Book Here's Why The Anvil Rejects Here's The Java Edition Mending Book 
![image](https://user-images.githubusercontent.com/77946452/235158019-79ab2d1c-3aff-4189-b9ac-2e865baf03df.png)
And Here's The Bedrock One
![image](https://user-images.githubusercontent.com/77946452/235158099-a7343b2f-fff9-47de-a333-9d9a785b60db.png)

### To Reproduce

Change The Book Taking From Gamemode Creative To Java Edition One's It Should Fix It

### Expected behaviour

I Expected To Work But It Didnt Lol

### Screenshots / Videos

Whoops I Already Send Them But Ill Do Again ![image](https://user-images.githubusercontent.com/77946452/235158019-79ab2d1c-3aff-4189-b9ac-2e865baf03df.png) ![image](https://user-images.githubusercontent.com/77946452/235158099-a7343b2f-fff9-47de-a333-9d9a785b60db.png)

### Server Version and Plugins

1.19.4 And 1.19.80 bedrock

### Geyser Version

The latest i guess

### Minecraft: Bedrock Edition Device/Version

PC

### Additional Context

1.19.80 but this bug should happen on every device

**Comment by onebeastchris** [comment]
thank you for the detailed bug report; i made a PR that fixes this issue :)
