### ISSUE TITLE
Weapon Doesn't work if it has custom attributes (MMOItems)

### ISSUE THREAD

**Issue by SamGamerYT** [GeyserMC/Geyser#3712]
### Describe the bug

Say I have 3 type of weapons, MMOItems, Vanilla and MMOItems without any attributes, While I'm switching the weapons from the server and other players pov they are not holding anything (Except Vanilla and MMOItems without any attributes) however the moment they hold a custom weapon (MMOItems) it actually doesn't switch and they can't damage anything, From their POV they are holding a weapon but from other players POV they aren't.

### To Reproduce

Get MMOItems, MythicLib plugin
Create a weapon
Place weapons in your hotbar
Use mouse wheel and have another alt/player on stand by
You will switch to all weapons except mmoitems weapons that has custom attributes.

### Expected behaviour

Before the newer updates, they were working properly and without an issue.

### Server Version and Plugins

Latest 1.19.4 Purpur
Latest GeyserMC

### Geyser Dump

https://dump.geysermc.org/qzTig21pA4D5xSzFfJlgF8YNEIvACi3S

### Geyser Version

Latest: Yes

### Minecraft: Bedrock Edition Device/Version

Windows 10, Xbox and Playstation

**Comment by onebeastchris** [comment]
this is now the 3rd bug about it. Please close this issue; it is a duplicate - already looking into it.

**Comment by Jens-Co** [comment]
Closing due to duplicate #3710
