### ISSUE TITLE
Geyser Proxy Version

### ISSUE THREAD

**Issue by PuglTnT** [GeyserMC/Geyser#3716]
### Describe the bug

My screen keeps telling me I have an outdated version on Minecraft Pocket Edition. It tells me the allowed versions, but never how to fix this.

### To Reproduce

1. Go to sever list
2. Click on said private server
3. Click ‘join’
4. See the error screen

### Expected behaviour

I expected it to be like every other time I joined and to just allow it to function, but it shows me the error screen.

### Screenshots / Videos

![E80B32C3-0C74-4828-A8D8-C8B2B7B54E66](https://user-images.githubusercontent.com/132107607/235262137-233c689a-c13f-4785-b2c7-be53cb8438d2.jpeg)

### Geyser Version

1.19.81 Pocket Edition

**Comment by Redned235** [comment]
Update Geyser.
