### ISSUE TITLE
Disconnected after 2 sec

### ISSUE THREAD

**Issue by myiron100** [GeyserMC/Geyser#3719]
### Describe the bug

When someone on bedrock join, 10 sec after they got disconnected.

### To Reproduce

Download the new geyser update
Join the server and that's it

### Expected behaviour

be able to play without disconnect error

### Server Version and Plugins

git-Paper 388 MC:1.18.2      1.18.2-R0.1-SNAPSHOT

Plugins (169):
EnchantControl, NaruseAPI, TemporaryFire, MoDispenserMechanics, Clockdisplay, EssentialsSelectors, UnclaimFinder, TrollBossPlus, Not-Too-Expensive, ViaVersion, NBTAPI, ViaBackwards, BaseFinder, LuckPerms, LootCrate, AutoMessage, Freeze, VoidSpawn, GhostBlock, ccNoSpecTeleport, DisguiseAPI, InfoHUD, Anvil, ImageOnMap, DisableWither, SwagChat, SimpleSit, InventoryRollbackPlus, PlaceholderAPI, Spicord, DisguisePlus, CrucialAPI, CensorReloaded, B_DiscordIntegration, SimpleTrash, HPWP, PsudoCommand, ClearLag, VariableEnderChests, DisplayName, BuycraftX, CometWelcome, HamsterAPI, NeoPerformance, SecondThreadAPI, AntiAltAccount, BlowableObsidians, floodgate, PublicCrafters, ViaRewind, JoinCommands, Scoreboard-revision, BetterReports, HolographicDisplays, CommandTimer, OfflineManager, Geyser-Spigot, CombatPlus, DailyRewardsPlus, spark, UltimateStatistics, DiscordSender, BlockParticles, EliteMobs, OpenAudioMc, JumpPads, BlockRegen, PortalGun, EpicRename, ComplexTurrets, DeadChest, BetterSleeping4, SCore, Spartan, FileGUI, antiRedstoneClock, Spleef, TabList, ChestCommands, WildChests, BattlePass, StaffPlus, UltimateAirdrops, BetterFarming, Skript, SkQuery, ServerTutorialPlus, ExecutableEvents, ExecutableItems, UltimateStacker, DamageIndicatorsPlus, ExecutableBlocks, BetterShulkerBoxes, ProtocolLib, AdvancedReplay, ClientDetector, Orebfuscator, Pl-Hide-Pro, DeluxeMotd, LibsDisguises, AntiCheatReplay, NametagEdit, Multiverse-Core, Animotion, CCTV, MessageOverHead, Citizens, TradeSystem, Plan, mcMMO, PlayerParticles, LemonBeehive, UpgradeableSpawners, ArmorStandTools, eco, EcoSkills, CitizensCMD, ajParkour, AuctionHouse, Factions, Markets, Reforges, Duels, AutoSellChests, NexEngine, CombatPets, BetterRTP, ReviveMe, CoreProtect, RealisticSeasons, dynmap, WorldBorder, WorldEdit, BetterStructures, WorldGuard, LevelledMobs, Essentials, EssentialsGeoIP, EssentialsChat, EssentialsSpawn, Elevator, HomeGUI, NotQuests, VeinMiner, Admin-GUI, BedWars, Leastereggs, Boosters, EconomyShopGUI-Premium, HeadDatabase, BanAnnouncer, LiteBans, EnchantGui, EcoEnchants, EcoEnchantsGUI, DiscordSRV, UpgradeableHoppers, PlugManX, SuperVanish, Vault, RankGrantPlus, Vegas, BountyHunters, DiscordEconomyBridge, PassLock, RepairGui, InteractiveChat, InteractiveChatDiscordSrvAddon, SecondThreadAPI

### Geyser Dump

https://dump.geysermc.org/dDMiAFvB1IR90I0s7A13OU9Iu5dwr7xU

### Geyser Version

2.1.0-SNAP

### Minecraft: Bedrock Edition Device/Version

1.19.80/81 - Mobile/PC

### Additional Context

29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] INFO [floodgate] Floodgate player logged in as .DyoN404 disconnected
29.04 00:13:40 [Server] INFO [Geyser-Spigot] DyoN404 has disconnected from the Java server because of disconnect.lost
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.04 00:13:40 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted
29.04 00:13:40 [Server] WARN [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

**Comment by myiron100** [comment]
![image](https://user-images.githubusercontent.com/132120158/235375027-f8093c21-8079-42b7-8716-34c18f5d3872.png)

**Comment by onebeastchris** [comment]
Send a geyser dump please - run "geyser dump" in the server console, and send the link you get here.

**Comment by myiron100** [comment]
https://dump.geysermc.org/evuzCXaRfGvUdX51WMgk9aeNbycy0VT1

**Comment by onebeastchris** [comment]
hm, that is the latest version. Could you send a log?
Upload the "latest.log" file from your "logs" folder to mclo.gs and send the link it gives you here

**Comment by myiron100** [comment]
https://mclo.gs/YqSadS4

**Comment by myiron100** [comment]
someone have some information or update for this issue?

**Comment by myiron100** [comment]
?

**Comment by onebeastchris** [comment]
I'd recommend to try and sort out the dozens of issues in your server log - there's like 10 plugins not loading/functioning properly. Additionally, make sure to update Geyser to the latest version.

**Comment by myiron100** [comment]
Yeah but the error isn't critical for the server. It was working fine before the geyser update

**Comment by onebeastchris** [comment]
But it's not "just" the one error, it's a dozen. Even if it doesn't fix this issue fully, it can still cause issues down the road - Additionally, you still should try updating to the latest version.

**Comment by myiron100** [comment]
I tried to fixed every error but it doesn't work. Also, maybe the problem is the host bc many people that having this error is on the same host then me.

**Comment by myiron100** [comment]
any info for this issue?

**Comment by myiron100** [comment]
I fixed the error myself. This error is caused bc the paper jar isn't update. I update my paper jar and everything is working fine now!
