### ISSUE TITLE
bedrock player is currently stuck in a void and can't move, only being able to see entitles a few blocks ahead of them

### ISSUE THREAD

**Issue by ozyloc** [GeyserMC/Geyser#3723]
### Describe the bug

Every time a bedrock player joins the server, they are greeted with being in the void, but are at the coordinates in the world, not the bottom of the world. There aren't any drowning bubbles either. The player can't move but can look around and still punch. It can't see any kind of entity that isn't 5 or so blocks in front of it, excluding items. I'm not sure how this happened. Any idea how to fix? If it helps, I'm using playit.gg for port forwarding.

### To Reproduce

I'm not sure how this happened in the first place, so I'm not sure how to recreate it.

### Expected behaviour

What I expected was bedrock players being able to play as normal.

### Screenshots / Videos

https://user-images.githubusercontent.com/103389280/235318419-5481df76-0c75-4b64-95ad-8d3111951b3a.mp4

### Server Version and Plugins

The server is running CraftBukkit version 3553-Spigot-14a2382-ef09464 version 1.19

The plugins I have are:
- Aurelium Skills
- DiscordSRV
- Dynmap
- Enchants Squared
- Essentials
- Graves
- GSit
- LuckPerms
- Minepacks
- Orebfuscator
- ProtocolLib
- Shopkeepers
- ViaVersion
- WorldEdit
- WorldGuard
- Yamipa

### Geyser Dump

https://dump.geysermc.org/rq53daWp1FgKAsUYWQVWcTpl8TGpWzyR

### Geyser Version

2.1.0-SNAPSHOT (git-master-baae468)

### Minecraft: Bedrock Edition Device/Version

Windows 10 PC, version 1.19.73

**Comment by onebeastchris** [comment]
Try the workaround mentioned here, it's likely the classic Intel 11th gen bug:
https://github.com/GeyserMC/Geyser/issues/2861

**Comment by frogglen** [comment]
> Try the workaround mentioned here, it's likely the classic Intel 11th gen bug: #2861

I am experiencing something similar in a few occasions it happens that the user stays like in the video and gets a message in the chat that says that his chat is disabled.
When this happens he can't do anything, he can't write in the chat, he can't move, he can't teleport, nothing.

I have to wait for them to disconnect, put them in spectator mode and then teleport them to another area and this solves the problem.

I have a AMD Ryzen 7 3700X

**Comment by onebeastchris** [comment]
Closing due to no response from original poster.
