### ISSUE TITLE
Bedrock players sometimes forced to login to java account

### ISSUE THREAD

**Issue by DuneSciFye** [GeyserMC/Geyser#3725]
### Describe the bug

At random times throughout the day, bedrock players will be shown the screen you get if you do not have floodgate installed.

### To Reproduce

1. Login
2. See the error

### Expected behaviour

You log into the server

### Screenshots / Videos

https://cdn.discordapp.com/attachments/758032519294877766/1100458612360478911/IMG_20230425_172854.jpg

### Server Version and Plugins

Lobby server version: Current: git-Purpur-1876 (MC: 1.19.3)*
floodgate-spigot installed on all gamemodes

Velocity plugins:
`Plugins (13): Always Online (6.2.0), BungeePackFix (Velocity) (1.1.0-r3), CommandWhitelist (2.6.0), ConnectorPlugin (1.3-SNAPSHOT (build 56)), CraftingStore (<UNKNOWN>), floodgate (2.2.2-SNAPSHOT (b82-2702bc3)), Geyser-Velocity (2.1.0-SNAPSHOT (git-master-8a25afb)), LiteBans (2.11.0), LuckPerms (5.4.46), MySQLDriver (1.0), NuVotifier (2.7.3), ServerUtils (3.5.4) and VotingPlugin (1.0)`

### Geyser Dump

https://dump.geysermc.org/vSRq1nCvG5k4HfpFs1UnhRBVsxkc8jd6

### Geyser Version

Geyser-Velocity (2.1.0-SNAPSHOT (git-master-8a25afb))

**Comment by onebeastchris** [comment]
Hey!
Please try and update Geyser and floodgate to the latest versions; if the issue persists, please send a new Geyser dump.

**Comment by onebeastchris** [comment]
Furthermore, could you try this step if it still occurrs?
https://github.com/GeyserMC/Geyser/issues/3741#issuecomment-1536779630

**Comment by onebeastchris** [comment]
Closing due to no response.
