### ISSUE TITLE
Bedrock players cant see java players after the bedrock player dies

### ISSUE THREAD

**Issue by xanthacreator** [GeyserMC/Geyser#3726]
### Describe the bug

bedrock players cant see java players after the bedrock player dies. the bedrock player can move around and eventually see the java player but eventually the bedrock player cant see the java player. the java player can always see the bedrock player no matter what movement is made. One way for the java player to be seen again is by turning vanish(in essentials) on for the java player then turning it off. I run geysermc on the velocity server and this only happens on one of my backend servers 

### To Reproduce

1. die as a player on bedrock
2.  walk up to java player
3. watch the java player disappear

### Expected behaviour

for the bedrock player to be able to see the java player at all times. even after death

### Screenshots / Videos

![screenshot of invisible player](https://user-images.githubusercontent.com/84642413/235327386-2324a3cd-0638-452b-a598-c6083625944c.png)
in the picture above i circled where the java player is standing u can also see the particles from the player 

![moving](https://user-images.githubusercontent.com/84642413/235327397-2fa9eba2-bee3-4f92-aa27-3aecf04c17e1.png)

in this picture above i moved the bedrock player to a different location and the java player appeared

https://user-images.githubusercontent.com/84642413/235327499-2c697a45-9619-4d5a-9657-4fe510a7fcc8.mp4

heres a video of it happening. bedrock player has already died in this instance and by moving around cant see the java player

### Server Version and Plugins

Minecraft Server Verison: Paper 1.19.3
Plugins
ajLeaderboards, BlueSlimeCore, BuycraftX, ChatManager, Citizens, ClearLag, CombatLogX, CoreProtect, CrackShot, CrazyCrates, DecentHolograms, dtlTradersPlus, Essentials, EssentialsChat, EssentialsSpawn, Factions, FactionsKore, floodgate, LuckPerms, MessageAnnouncer, MineResetLite, Multiverse-Core, MyCommand, OldCombatMechanics, Pl-Hide-Pro, PlaceholderAPI, PlayerVaults, PlayerVaultsGUI, ProtocolLib, ServerTutorialPlus, ShopGUIPlus, ShopGUIPlusSilkSpawnersBridge, SilkSpawners, SimpleScore, StaffSpectate, TAB, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, Vouchers, Vulcan, VulcanCrackshot, VulcanTopGUI, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/PoVKZJ86FaRn2L8iDNGf7CiWfTdrWLTm

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-baae468) (Java: 1.19.4, Bedrock: 1.19.40/1.19.41 - 1.19.80/1.19.81)

### Minecraft: Bedrock Edition Device/Version

1.19.80, 1.19.81 on PC

**Comment by frogglen** [comment]
same problem

**Comment by nicholasveronico** [comment]
Multiple players of mine have reported this as well, except it happens when a java player is killed by a bedrock player. See below for a video 

https://cdn.discordapp.com/attachments/1050568273068052491/1118677753118609448/64022eac-aec7-42f6-ba8c-b76d284bec5a.mp4

**Comment by onebeastchris** [comment]
Is this still happening?

**Comment by nicholasveronico** [comment]
> Is this still happening?

I have not noticed it on my network in a long time.

**Comment by onebeastchris** [comment]
In that case, ill close this issue - if this issue re-appears, please create a new issue report with updated replication steps. Thanks!
