### ISSUE TITLE
Chunk not loading 

### ISSUE THREAD

**Issue by Sabit205** [GeyserMC/Geyser#3727]
### Describe the bug

I make half trident farm and leave the server after few hours i joined the server and the chunk is not loading

### Screenshots / Videos

![Screenshot (16)](https://user-images.githubusercontent.com/130175838/235338718-9a1e818f-ec60-4357-9d48-f2712319c3e7.png)

### Server Version and Plugins

Paper version 1.19.3
plugins:
EconomyShopGUI,AuctionMaster, AuctionMasterItemDisplay, AuthMe, BetterRTP, BetterTeams, Citizens, CitizensText, ClearLag, CrazyCrates, DecentHolograms,DeluxeMenus, DiscordSRV, Essentials, FastAsyncWorldEdit, floodgate, Geyser-Spigot, GriefPrevention, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LoneLibs, LPC, LuckPerms, MortisBank, PacketWrapper, PlaceholderAPI, *PluginHiderPlus, PlugManX, ProtocolLib, ServerBooster,ServerListPlus, SkinsRestorer, TAB, TradeSystem, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, WorldGuard

### Geyser Version

2.1.0-SNAPSHOT (git-master-c8afd34)

**Comment by Camotoy** [comment]
This should be fixed with the upcoming update; can you please confirm?

**Comment by onebeastchris** [comment]
Closing this due to lack of response & likely being fixed.
