### ISSUE TITLE
"Exception thrown in RakNet pipeline" Preventing bedrock players from joining

### ISSUE THREAD

**Issue by ManifestJW** [GeyserMC/Geyser#3730]
### Describe the bug

Error exception thrown in the console whenever I or anyone else tries to join from Bedrock Edition. Bedrock players cannot connect to the server whatsoever, but they can see the server is online.

### To Reproduce

1. Download build #794 of PaperMC for minecraft 1.16.5
2. Download OpenJDK 16
3. Make a script to run the server with the following Java arguments on Java 16.
4. Accept the eula
5. Download Geyser git-master-eee8dd4
6. Download Floodgate git-master-2702bc3
7. Download ViaVersion 4.6.2
8. Change Auth type to floodgate
9. Start server and attempt to join.
[latest.log](https://github.com/GeyserMC/Geyser/files/11363286/latest.log)

### Expected behaviour

Bedrock client joins the server with no issues.

### Server Version and Plugins

[23:30:50 INFO]: Checking version, please wait...
[23:30:50 INFO]: This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

Plugins: Geyser, Floodgate, ViaVersion

### Geyser Dump

https://dump.geysermc.org/gOEVx387Kt754cijlgd8HwmEgzlqird7

### Geyser Version

git-master-eee8dd4

### Minecraft: Bedrock Edition Device/Version

1.19.81, Windows 10

**Comment by Camotoy** [comment]
We are aware of this issue and it will be fixed soon.
