### ISSUE TITLE
BUG NBT TAGS

### ISSUE THREAD

**Issue by Olavvvv** [GeyserMC/Geyser#3731]
### Describe the bug

When giving items with a high nbt tag, a huge spam appears in the console

### To Reproduce

Give a pickaxe or any item with nbt tag greater than 9 to a bedrock user

### Expected behaviour

I don't know, nothing should happen xd

### Screenshots / Videos

https://imgur.com/CGLyaIc.png

### Server Version and Plugins

Build #97

### Geyser Version

build 97

### Minecraft: Bedrock Edition Device/Version

1.18.90

### Additional Context

https://pastebin.com/2rZ91k7D

**Comment by frogglen** [comment]
This is a likely duplicate of the https://github.com/GeyserMC/Geyser/issues/3710 issue

**Comment by onebeastchris** [comment]
Could you try the latest Geyser build and see if the error persists?
Thanks!

**Comment by Konicai** [comment]
Should be fixed
