### ISSUE TITLE
Says I'm offline evn after logging into Java account

### ISSUE THREAD

**Issue by HierarchyMan** [GeyserMC/Geyser#3734]
### Describe the bug

I've tried 6 times but everytime I press done after logging into my mcjava account in my browser geyser says this server requires an online account to play
Yes I've tried waiting a long time after I log into browser cuz I know Microsoft login can be slow

### To Reproduce

Just try and logging into mcjava account with online mode enabled in geyser config yml

### Expected behaviour

It should just let me join 

### Screenshots / Videos

![Screenshot_2023-05-01-22-08-40-90_568ed85dd9b4e5f606052ed6d65243e4](https://user-images.githubusercontent.com/97939376/235489371-29b6e4a4-f5d3-4074-b490-1efa77a822bb.jpg)

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-71e091c)

### Minecraft: Bedrock Edition Device/Version

1.19.81

**Comment by Camotoy** [comment]
Have you tried using this account on a PC/using the Java Edition launcher before?

**Comment by HierarchyMan** [comment]
I don't have a pc (rn) (yes I do own mcjava on the account I'm trying to sign into)
https://user-images.githubusercontent.com/97939376/235490736-b8cf3b06-7c74-403d-9fb4-e6d858ab6639.mp4

**Comment by HierarchyMan** [comment]
![Screenshot_2023-05-01-22-18-53-13_bab8561a5f94f0a53956d8cbbeaad774.jpg](https://user-images.githubusercontent.com/97939376/235490895-ad9d32fa-3f7a-4ffe-ab1e-bbb0d52dd986.jpg)

Here's my session in pojav launcher (proof)

**Comment by HierarchyMan** [comment]
Is someone gonna help me?
