### ISSUE TITLE
Falling into void when in the end shows fell from a high place

### ISSUE THREAD

**Issue by DrkVader** [GeyserMC/Geyser#3738]
### Describe the bug

When a bedrock player falls into the void in the end, they die instantly to fall damage instead of falling into the void. Tested in other dimensions but only seen in the end. 

### To Reproduce

1. Play on the most recent version of Geyser on a 1.19.4 Paper server
2. As a bedrock player, go to the end and jump off into the void
3. Player will die instantly to fall damage as opposed to the void

### Expected behaviour

Player should fall out of the void as opposed to dying instantly.

### Geyser Dump

https://dump.geysermc.org/JjsRCM5W6oLMXOJ6nbHQHhRStkad7rLk

### Geyser Version

2.1.0-SNAPSHOT (git-master-f801dc0)

### Minecraft: Bedrock Edition Device/Version

1.19.81, iOS

**Comment by onebeastchris** [comment]
Can confirm, to recreate, jump into the end void.

**Comment by onebeastchris** [comment]
Could you test the linked PR (can be downloaded in the "checks" section, there are build artifacts there) and see if that resolves the issue?
