### ISSUE TITLE
Failed to load locale asset cache

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#3742]
### Describe the bug

in startup of standalone geyser it's showing this error msg [09:18:23 ERROR] Failed to load locale asset cache: Unrecognized token 'Connection': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"Connection reset"; line: 1, column: 11]

### To Reproduce

launch #1367 build of geyser standalone 
see this error msg on consol 
[09:18:23 ERROR] Failed to load locale asset cache: Unrecognized token 'Connection': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"Connection reset"; line: 1, column: 11]

### Expected behaviour

when i launch geyser standalone it's showing this 

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/88581750/236078550-99cbe040-0b77-48e8-9c42-60fbaeb5cbc2.png)

### Server Version and Plugins

git-Purpur-1967 (MC: 1.19.4)* 
![image](https://user-images.githubusercontent.com/88581750/236078631-415d4672-0226-42c6-8cce-9e300b942b7d.png)

### Geyser Dump

https://dump.geysermc.org/eCueAvpbJTICdC32PvahZlDt7SUDy4NO

### Geyser Version

2.1.0-SNAPSHOT (git-master-f3f3062)

**Comment by Camotoy** [comment]
I don't think there's much we can do about this error - it seems like wherever the server is running, it can't reach Mojang's servers.

**Comment by adalmo** [comment]
hmm somehow it got fixed on latest build of geyser so i ma close this one
