### ISSUE TITLE
Small capital letters will make the server unreachable in Bedrock.

### ISSUE THREAD

**Issue by elyrodso** [GeyserMC/Geyser#3744]
### Describe the bug

The bug happened when using the "MiniMOTD" plugin with Small capital letters generated in the first result of this link: [Fsymbols](https://fsymbols.com/generators/smallcaps/). [Minecraft server status](https://mcsrvstat.us/) will give as a result "Failed to read from socket." GeyserMC Discord bot will say `"Your server is running inside a docker container, please make sure the Geyser port (using UDP) is exported out to the host. If you're using Pterodactyl panel then you need to make sure you have allocated the port to the server."` for the Geyser dump.

### To Reproduce

1. Generate a MOTD using Small capital letters, I can't be sure of the need for MiniMOTD. Generating numbers from this generator may also be one of the reasons.
2. Set passthrough-motd to true in config.yml
3. Reload Geyser, try to locate the server in Bedrock.
4. It will keep locating the server with no result, trying to join will give an error of Unable to connect to world.

### Expected behaviour

Geyser should either render the text without problems and the server will be able to load, or it will disable passthrough MOTD for some incompatibility problem.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/48741697/236373793-b4ffad9c-168d-423c-b8aa-3f1618deb638.png)

### Server Version and Plugins

Current: git-Purpur-1963 (MC: 1.19.4)*  
- AntiVillagerLag, BetterTeams, BlockLocker, BlueSlimeCore, ChangeSlots, ChestSort, Chunky, CoreProtect, DecentHolograms, DiscordSRV, DriveBackupV2, Drop2Inventory, EntityDetection, Essentials, EssentialsSpawn, FarmControl, FastAsyncWorldEdit, floodgate, FreedomChat, Geyser-Spigot, GriefPrevention, GSit, ImageFrame, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, InvUnload, Leashable, LuckPerms, Maintenance, MiniMOTD, PlaceholderAPI, ProtocolLib, spark, SuperVanish, TAB, VanillaTweaks, Vault, VentureChat, ViewDistanceTweaks, voicechat, WorldGuard

### Geyser Dump

https://dump.geysermc.org/XAkA2rNWIDWFibA15Gru3APfLevBLjGi

### Geyser Version

2.1.0-SNAPSHOT (git-master-6e9b272)

### Minecraft: Bedrock Edition Device/Version

1.19.81 - Tested on Mobile, Xbox and PC.

**Comment by Camotoy** [comment]
Does the same result occur if you write the MOTD in the Geyser config and not use passthrough MOTD?

**Comment by onebeastchris** [comment]
Closing due to no response.
