### ISSUE TITLE
cannot connect to world, geyser spigot disables itself or has spigot.yml r/w error

### ISSUE THREAD

**Issue by petefeet** [GeyserMC/Geyser#3748]
### Describe the bug

Created Geyser Paper Floodgate server

Couldn't connect to world on xbox client

Console was saying:
[Geyser-Spigot] Enabling Geyser-Spigot v2.1.0-SNAPSHOT
[Geyser-Spigot] Disabling Geyser-Spigot v2.1.0-SNAPSHOT

I saw something about a bad spigot.yml file possibly being an issue, so deleted it and let the server recreate.

Now I have:
ERROR]: [Geyser-Spigot] Failed to read/create config.yml! Make sure it's up to date and/or readable+writable!

server start log and file list attached.
[server_start.txt](https://github.com/GeyserMC/Geyser/files/11411836/server_start.txt)
[files.txt](https://github.com/GeyserMC/Geyser/files/11411837/files.txt)

### To Reproduce

Start server

### Expected behaviour

No errors, connect to world... enjoy

### Geyser Version

Geyser-Spigot v2.1.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

Xbox

**Comment by Fammy001** [comment]
Most likely you using a false version of Geyser.
**Solutions:**
- Update the Geyser server 
- Check the correct Geyser version according to your server version

**Comment by Camotoy** [comment]
I don't think this is a false Geyser version - you probably formatted something in your config wrong. Try with a fresh config - otherwise, upload your config and we'll tell you where it's wrong.

Closing since this is not a Geyser bug. Thanks.
