### ISSUE TITLE
support 3rd party authentication

### ISSUE THREAD

**Issue by hlgzhx** [GeyserMC/Geyser#3751]
### What feature do you want to see added?

Is there any way to config geyser to use a 3rd party authentication server instead of mojang's?
My server is using Littleskin as my authentication server.i installed geyser and floodgate on my paper server.Now a player can play it from either BE or JE,but their player data can not be synced.I really want to change PE's the auth method from xbox or mojang to Littleskin,as same as the JE.so player's using this 3rd party account can login into the same account with BE or JE.just like using Mojang accounts.

### Are there any alternatives?

i've tried authlib-injector but it seems doesn't work with geyser.

**Comment by Camotoy** [comment]
We don't have an interest in supporting this. Also, our Mojang account support will be removed at some point, anyway.
