### ISSUE TITLE
"Downstream packet error! null" errors spamming console

### ISSUE THREAD

**Issue by purejosh** [GeyserMC/Geyser#3752]
### Describe the bug

Hello! Just wanted to report, when a bedrock player joins the server and for the duration of them playing, the console gets spammed with a bunch of "Downstream packet error! null" errors. 

Given previous bug reports, I've enabled debug mode and I'll try to reboot later tonight, if possible. I'll give the debug log as soon as I have it. 

I'm also going to attach my config, please let me know if there's any settings I can change to either fix this issue, or just improve the experience overall. 

### To Reproduce

Have a bedrock player login, and observe the console errors. 

### Expected behaviour

No console errors. 

### Server Version and Plugins

velocity-3.2.0-SNAPSHOT-244
Geyser-Velocity-95
floodgate-velocity-78

### Geyser Dump

https://dump.geysermc.org/PwMVyN32VYbZIt2Ynw9tc1HnKOAzQO53

### Geyser Version

Geyser-Velocity-95

**Comment by Camotoy** [comment]
Your Geyser build is rather outdated. Please update it, and if the errors persist, let us know. Thanks.

**Comment by purejosh** [comment]
I didn't realize I was that out of date. I've installed build 111, and I'll report if the errors stop.

**Comment by purejosh** [comment]
errors have stopped with new build. thanks.
