### ISSUE TITLE
Geyser-Spigot Resource Pack Bug

### ISSUE THREAD

**Issue by TheElectronic317** [GeyserMC/Geyser#3755]
### Describe the bug

Bedrock Users will not be able to connect to the server if you're forcing players to use a texture pack.

### To Reproduce

1. Put a Resource pack in the Geyser-Spigot Packs folder.
2. (Mine in this case changes a single texture in the game and changes alot of the music[The size of this texture pack is 178 mb{or 177,995,572 bytes exact}])
3. Have Require Resource/Texture pack enabled to True on your server in the config file
4. Restart the server to enable/save these changes
5. On a bedrock client attempt to connect to the server. 

### Expected behaviour

People being forced to use a texture pack and join the server

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/68921217/9f67c05f-783f-4b39-9a5f-3cfaa084842e)

### Geyser Version

Build 114

**Comment by onebeastchris** [comment]
Hey! A few things:
1. Does removing the enforcement allow the player to join? Or does the error still occur? I've seen this issue before, but usually unrelated to packs.
2. Is that pack in a bedrock format, and does it work when applied on the bedrock client directly?

**Comment by onebeastchris** [comment]
Closing due to no response.
