### ISSUE TITLE
NPE from GeyserBootstrap#getPingPassthrough()

### ISSUE THREAD

**Issue by Yomamaeatstoes** [GeyserMC/Geyser#3757]
### Describe the bug

On startup with  " pingPassthrough "  error on startup. 

Log 

https://mclo.gs/dnZ9tBh

Exact error in the log

https://paste.gg/p/anonymous/45d612793c124432bcd40bf02a7578ec

### To Reproduce

Start the server up

### Expected behaviour

No errors

### Screenshots / Videos

![Havok - Console - Budget Panel - BisectHosting and 5 more pages - Personal - Microsoft​ Edge 5_10_2023 2_21_19 AM](https://github.com/GeyserMC/Geyser/assets/114538961/a0881986-5085-479d-a5d8-dbb33079eecd)

### Server Version and Plugins

Plugins - AutoPay, BetterEconomy, BetterRTP, BisectHosting, ChatFilter, Chunky, Citizens, ClansLite, CommandBlockAsPlayer, DeluxeMenus, DisableBreeding, DiscordSRV, dynmap, ElytraSpeed, EpicHomes, FastAsyncWorldEdit, floodgate, Geyser-Spigot, GlobalTrackedMaps, HarmonyScoreboard, IllegalStack, Lifesteal, LuckPerms, mcMMO, Multiverse-Core, Multiverse-NetherPortals, NoCheatPlus, Parkour, PL-Hide, PlaceholderAPI, PlayerBountiesPlus, PlayerKits, PlugManX, PremiumVanish, ProtocolLib, RedLimiterReloaded, ScoreboardChatShop, SilkySpawnersLITE, spark, Spartan, StackMob, StormerAntiNetherRoof, StormerAntiSpam, StormerTPAReloaded, StormerWarpsReloaded, TerragenBiomesMockRegistry, Themis, TNTRun_reloaded, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WorldGuard

This server is running Paper version git-Paper-527 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 6884092)
You are running the latest version
Previous version: git-Paper-526 (MC: 1.19.4)

### Geyser Dump

https://dump.geysermc.org/xq66T4YD7mbttF5PkVlLo7WX8qx10AIP

### Geyser Version

This server is running Geyser version 2.1.0-SNAPSHOT (git-master-ed21a10) (Java: 1.19.4, Bedrock: 1.19.40/1.19.41 - 1.19.80/1.19.81)

### Minecraft: Bedrock Edition Device/Version

Any

### Additional Context

None

**Comment by Konicai** [comment]
If you're still experiencing this, can you enable debug mode in Geyser's config and share the log again?
