### ISSUE TITLE
Geyser Config Resets on Startup

### ISSUE THREAD

**Issue by BenTheMan69** [GeyserMC/Geyser#3759]
### Describe the bug

The geyser Config file resets on server startup. Particulary when changing the Port. I have tried the fix from #632 but it wont work. #632 is almoast 3 years old now so thats no suprise. I have this issue on a Paper/Spigot Server.

### To Reproduce

Go to config.yml
Change the port to a diffrent one
Restart your server

### Expected behaviour

To Host Geyser on the port i selected.

### Geyser Version

2.1.0-SNAPSHOT (git-master-d93f3dd)

**Comment by Camotoy** [comment]
Are you using Geyser on a server host/provider?

**Comment by BenTheMan69** [comment]
> Are you using Geyser on a server host/provider?

Yes. I am Using Shockbyte Hosting. Its a Paper/Spigot Server on 1.19.3

**Comment by Camotoy** [comment]
Shockbyte is messing with the config here, not us. This is how they handle their autoconfiguration for Geyser.
