### ISSUE TITLE
Jerky movement up stairs

### ISSUE THREAD

**Issue by madrig88** [GeyserMC/Geyser#376]
**Describe the bug**
On a Vanilla Minecraft Server, using Xbox One, Whenever walking up stairs, the movement gets jerky. 

**To Reproduce**
1. Place Stairs going upward.
2. Walk upstairs
3. Witness the jerking movement

**Expected behavior**
Walk up stairs smoothly and straight

**Screenshots / Videos**

**Server Version**
Vanilla Minecraft Server 1.15.2

**Geyser Version**
Geyser Build #24 Inventory Branch Standalone

**Minecraft: Bedrock Edition Version**
Bedrock Version 1.14.60 Xbox One

**Additional Context**
Xbox One is on the same network at Geyser Standalone and that forwards to the Java server on a different network. We are trying to keep the server Vanilla and not use plugins hence the use of the standalone version.

**Comment by RednedEpic** [comment]
> **Describe the bug**
> On a Vanilla Minecraft Server, using Xbox One, Whenever walking up stairs, the movement gets jerky.
> 
> **To Reproduce**
> 
> 1. Place Stairs going upward.
> 2. Walk upstairs
> 3. Witness the jerking movement
> 
> **Expected behavior**
> Walk up stairs smoothly and straight
> 
> **Screenshots / Videos**
> 
> **Server Version**
> Vanilla Minecraft Server 1.15.2
> 
> **Geyser Version**
> Geyser Build #24 Inventory Branch Standalone
> 
> **Minecraft: Bedrock Edition Version**
> Bedrock Version 1.14.60 Xbox One
> 
> **Additional Context**
> Xbox One is on the same network at Geyser Standalone and that forwards to the Java server on a different network. We are trying to keep the server Vanilla and not use plugins hence the use of the standalone version.

Stair lag may be due to having autojump enabled, however there are various movement bugs here and there within Geyser that are in the process of being fixed. Closing this in favor of #204.
