### ISSUE TITLE
Downstream packet error

### ISSUE THREAD

**Issue by ExtraSmartMiner** [GeyserMC/Geyser#3760]
### Describe the bug

Downstream packet error! Non [a-z0-9/._-] character in value of Key[minecraft:Test]

### To Reproduce

I am using skript to send a font chat tag

command /error:
	trigger:
		send formatted "<<font:Test>>Font" to player

### Expected behaviour

No error

### Server Version and Plugins

 Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

Skript

### Geyser Version

git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:7790783:1686

### Minecraft: Bedrock Edition Device/Version

Windows 11

**Comment by Camotoy** [comment]
Can you enable debug mode in Geyser and send a log with the error, please?

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
