### ISSUE TITLE
Bedrock cape

### ISSUE THREAD

**Issue by ThatFinnDev** [GeyserMC/Geyser#3764]
### Describe the bug

Bedrock capes are not shown to java users. (Java capes are visible to bedrock users and bedrock capes are visible to bedrock users)

### To Reproduce

1. Enable a bedrock cape (e.g pancake cape)
2. join with java and bedrock
3. See through the java client window that there is no cape attached to the bedrock user

### Expected behaviour

The java players should see bedrock capes

### Server Version and Plugins

Geyser 2.1.0-SNAPSHOT
Floodgate 2.2.2-SNAPSHOT (b??-1b9042e)
CraftBukkit version 3748-Spigot-7da74da-01b2e1a (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)

### Geyser Version

1.19.4

**Comment by Camotoy** [comment]
Yup, the mod is the only option. Sorry.

**Comment by ThatFinnDev** [comment]
Thanks
