### ISSUE TITLE
Spectator mode is not working

### ISSUE THREAD

**Issue by patyhank** [GeyserMC/Geyser#3769]
### Describe the bug

In spectator mode
Because AbilityLayer.Type.SPECTATOR has never been added to the UpdateAbilitiesPacket
so you can't fly and noclip with the default Abilities

### To Reproduce

1. /gamemode spectator
2. Move to the inside of the block
3. Player will keep falling down

### Expected behaviour

Player will not keep falling

### Screenshots / Videos

Youtube Reproduce: https://youtu.be/2HEQNU90WNU
Patched Workaround: https://youtu.be/rKMsBt_F9uo

### Geyser Version

2.1.0-SNAPSHOT (git-master-870a838)

### Minecraft: Bedrock Edition Device/Version

1.19.81

### Additional Context

A simple workaround https://github.com/GeyserMC/Geyser/blob/870a838c0f854665d2304fa0760af391d5e387f8/core/src/main/java/org/geysermc/geyser/session/GeyserSession.java#L1742 to 
```java
        if (spectator) {
            abilityLayer.setLayerType(AbilityLayer.Type.SPECTATOR);
        } else {
            abilityLayer.setLayerType(AbilityLayer.Type.BASE);
        }
```

**Comment by Camotoy** [comment]
PRs are more than welcome!
