### ISSUE TITLE
bedrock players cant move

### ISSUE THREAD

**Issue by devGyet** [GeyserMC/Geyser#3772]
### Describe the bug

bedrock players just can't move, can't turn the camera, etc.

### To Reproduce

1 login on the server
2 can't move

### Expected behaviour

players can play like java players

### Server Version and Plugins

1.19.4 purpur 
![image](https://github.com/GeyserMC/Geyser/assets/103088929/dbdacb0d-7fda-42c6-a38a-0c0d029fe05d)
![image](https://github.com/GeyserMC/Geyser/assets/103088929/caab26a1-4c37-4d60-806c-d3feaf415d9a)
![image](https://github.com/GeyserMC/Geyser/assets/103088929/6a8177cb-3de0-404a-8f76-ef8779b699b9)
![image](https://github.com/GeyserMC/Geyser/assets/103088929/70042301-929f-48cf-95c4-60f18a53998d)

### Geyser Dump

https://dump.geysermc.org/PD6cWxWSTfcdRCcXjlw3E5aY0tItQsAV

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-ea136b2) (Java: 1.19.4, Bedrock: 1.19.40/1.19.41 - 1.19.80/1.19.81)

### Minecraft: Bedrock Edition Device/Version

Android 1.19.81

**Comment by Jens-Co** [comment]
Hello there, Would you mind to do some plugin debugging for me as this is not a behaviour ive seen yet and do not think its a Geyser related issue.

If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
- Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

Also would you mind adding some server logs please?

thanks!

**Comment by CLMurikk** [comment]
Hello
Try removing the forcepack. Maybe the java texture pack is generating incompatibility (I had the same problem. I deleted the forcepack and it was fixed)

**Comment by onebeastchris** [comment]
Closing this issue due to no response from issue author. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.

**Comment by devGyet** [comment]
I forgot to answer, but I already solved it another way

**Comment by fridaystreet** [comment]
@devGyet super useful answer. what other way?
