### ISSUE TITLE
Unable to connect to world

### ISSUE THREAD

**Issue by sarimwaniR** [GeyserMC/Geyser#3773]
### Describe the bug

Hello mate I have a sever where I want cross play but if I try to change the port of the sever in the config file it updatees in there but doesn't when I start it though the command please help 

### To Reproduce

...

### Expected behaviour

To change port

### Geyser Version

Latest 

### Minecraft: Bedrock Edition Device/Version

Beta Android

**Comment by Konicai** [comment]
Please join our discord for setup issues: https://discord.gg/geysermc
