### ISSUE TITLE
Attribute display incorrectly if the attribute modifiers key name is in uppercase

### ISSUE THREAD

**Issue by clarkkentz** [GeyserMC/Geyser#3778]
### Describe the bug

Attribute display incorrectly if the key name is in uppercase.
Example:
generic.attack_speed -> Attribute display on bedrock is matched with Java.
GENERIC.ATTACK_SPEED -> Attribute display on bedrock is incorrect.

### To Reproduce

1. Set NBT Attribute modifiers key NAME to UPPERCASE

### Expected behaviour

Attribute display incorrectly on bedrock if the key name is in uppercase

### Screenshots / Videos

![ApplicationFrameHost_9zCWolccCH](https://github.com/GeyserMC/Geyser/assets/10612667/cf578ea4-37c4-4580-b2d6-d4a8804703ee)

### Server Version and Plugins

paper 1.18.2

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-a8b6268) (Java: 1.19.4, Bedrock: 1.19.40/1.19.41 - 1.19.80/1.19.81)

### Minecraft: Bedrock Edition Device/Version

1.19.81 iPhone iOS16

**Comment by Konicai** [comment]
Can you provide a give command to reproduce this please

**Comment by clarkkentz** [comment]
> Can you provide a give command to reproduce this please
I use Vanilla give command.
`/minecraft:give @p netherite_sword{AttributeModifiers:[{AttributeName:"generic.attack_damage",Amount:10,Slot:mainhand,Name:"GENERIC.ATTACK_DAMAGE",UUID:[I;-123420,8573,93155,-17146]},{AttributeName:"generic.attack_speed",Amount:9,Slot:mainhand,Name:"GENERIC.ATTACK_SPEED",UUID:[I;-123420,8673,93155,-17346]}]} 1`

**Comment by Konicai** [comment]
You can try a test build that fixes this here: https://github.com/GeyserMC/Geyser/actions?query=is%3Asuccess+event%3Apull_request+branch%3Afix%2Fuppercase-attributes

**Comment by clarkkentz** [comment]
> You can try a test build that fixes this here: https://github.com/GeyserMC/Geyser/actions?query=is%3Asuccess+event%3Apull_request+branch%3Afix%2Fuppercase-attributes

Didn't work, it show lowercase attributes instead.
![ApplicationFrameHost_lITztUili3](https://github.com/GeyserMC/Geyser/assets/10612667/337a9be2-f839-4ee6-a780-89fb5abad05e)

**Comment by Konicai** [comment]
yeah idk why the `minecraft:` is being added, i'll have to test tomorrow

**Comment by Konicai** [comment]
That is fixed now
