### ISSUE TITLE
No sound while connected to remote Java server

### ISSUE THREAD

**Issue by madrig88** [GeyserMC/Geyser#378]
**Describe the bug**
When a block breaks, tools break, or mobs are around, no sounds play at all.

**To Reproduce**
1. Do anything to interact with the world

**Expected behavior**
Sounds play when interacting with items, mobs or the world.

**Server Version**
Vanilla Minecraft Server 1.15.2

**Geyser Version**
Geyser Build #24 Inventory Branch Standalone

**Minecraft: Bedrock Edition Version**
Bedrock Version 1.14.60 Xbox One

**Additional Context**
Xbox One is on the same network as Geyser Standalone and that forwards to the Java server on a different network via domain name. We are trying to keep the server Vanilla and not use plugins hence the use of the standalone version.

**Comment by RednedEpic** [comment]
> **Describe the bug**
> When a block breaks, tools break, or mobs are around, no sounds play at all.
> 
> **To Reproduce**
> 
> 1. Do anything to interact with the world
> 
> **Expected behavior**
> Sounds play when interacting with items, mobs or the world.
> 
> **Server Version**
> Vanilla Minecraft Server 1.15.2
> 
> **Geyser Version**
> Geyser Build #24 Inventory Branch Standalone
> 
> **Minecraft: Bedrock Edition Version**
> Bedrock Version 1.14.60 Xbox One
> 
> **Additional Context**
> Xbox One is on the same network as Geyser Standalone and that forwards to the Java server on a different network via domain name. We are trying to keep the server Vanilla and not use plugins hence the use of the standalone version.

Not implemented, please see the README or #256. Also, before opening further issues for unimplemented features or bugs, make sure that they're not already referenced in the README or that there is an open issue/PR for them.

**Comment by madrig88** [comment]
Will do, thanks
