### ISSUE TITLE
Color Code broken in tooltips (possibly RGB related)

### ISSUE THREAD

**Issue by Folas1337** [GeyserMC/Geyser#3783]
### Describe the bug

A user of mine tried using goBrush by left clicking with a flint which brings up the following menu on java:
![image](https://github.com/GeyserMC/Geyser/assets/39222968/138238fb-f0cb-47b5-8366-330fd08da5ea)

The problem is that on Bedrock Edition clients it looks like this and all of the tooltips do, so you can't really tell them apart or tell what shape they are:
![image](https://github.com/GeyserMC/Geyser/assets/39222968/26687e09-d9c7-4f98-b563-7e8d2cab750b)

According to that user it has worked in earlier versions but broke somewhat recently.
To quote @rtm516 on Discord: `Maybe the colour mapping code broke? Bedrock doesn't support RGB so colours are limited to the build in legacy colour codes`

I'd appreciate this getting fixed at some point :)

### To Reproduce

1. Set up Geyser proxy (velocity in my case)
2. Have backend server behind it
3. Install goBrush
4. Try and use goBrush to find the tooltips all showing an "orange wall" of squares.

### Expected behaviour

It should obviously display the tooltips just like they show on Java Edition.

### Screenshots / Videos

(see above)

### Server Version and Plugins

This server is running Paper version git-Paper-538 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bcd8dc2)
You are running the latest version
Previous version: git-Paper-527 (MC: 1.19.4)

  [Sun 16:26:56 INFO ] Server Plugins (53):
  [Sun 16:26:56 INFO ] #0288d1Paper Plugins:
  [Sun 16:26:56 INFO ]  - BKCommonLib, CarbonChat
  [Sun 16:26:56 INFO ] #ed8106Bukkit Plugins:
  [Sun 16:26:56 INFO ]  - AntiPopup, Arceon, ArmorStandEditor, BetterGUI, BetterHeads, BuildersUtilities, CMILib, CoralStay, #ffd42a*CurveBuilding, CustomCommands
  [Sun 16:26:56 INFO ]  DiscordSRV, FartherViewDistance, FastAsyncVoxelSniper, FastAsyncWorldEdit, #ffd42a*FlySpeed, FrozenJoin, GCore, goBrush, goPaint, GSit
  [Sun 16:26:56 INFO ]  GWarp, ImageMaps, InvSeePlusPlus, #ffd42a*JoinFullServer, LightCleaner, LuckPerms, MetaBrushes, Multiverse-Core, NBTAPI, PixelPainter
  [Sun 16:26:56 INFO ]  Pl3xMap, PlaceholderAPI, PlayerTimeWeather, PlayerWarps, PluginConstructorAPI, ProtocolLib, RealScoreboard, RegionClaimPlus, SelectionVisualizer, #ffd42a*SimpleTpa
  [Sun 16:26:56 INFO ]  spark, SuperbVote, TAB, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, Votifier, WhitelistBypass, WorldGuard
  [Sun 16:26:56 INFO ]  #ffd42a*WorldSystem

### Geyser Dump

https://dump.geysermc.org/78PxbGjCKBO7vOkWVyLcmivaHkQhpHdR

### Geyser Version

2.1.0-SNAPSHOT (git-master-fbac0c1)

### Minecraft: Bedrock Edition Device/Version

1.19.81

**Comment by Camotoy** [comment]
Color codes are going to be broken on Geyser-Velocity since Velocity's built-in Adventure library does not have support for custom legacy color codes. We *can* temporarily fix this but also we can just wait it out until 1.20.

**Comment by Camotoy** [comment]
More specifically - something is using underline formatting.

**Comment by Folas1337** [comment]
Fine by me to wait until 1.20 when it's probably just weeks away.
Thanks for clarifying though! 👍

**Comment by onebeastchris** [comment]
Velocity had the change yesterday; so updating Velocity now should fix this issue :)
