### ISSUE TITLE
Cannot craft shield using multiple wood types.

### ISSUE THREAD

**Issue by DesolateIntention** [GeyserMC/Geyser#3784]
### Describe the bug

When placing more than one type of wood on the crafting table and trying to create a shield on Bedrock, it will not work. 

### To Reproduce

1. Put different types of wood on the crafting table (like oak and birch).
2. Put it in the shield recipe configuration.

No shield will be crafted.
![SmartSelect_20230521_175952_Minecraft](https://github.com/GeyserMC/Geyser/assets/63953363/32c327e8-c7fd-4f91-bbd0-b0e6f6235dd2)

### Expected behaviour

Shield will be crafted.
![image](https://github.com/GeyserMC/Geyser/assets/63953363/6eb036fa-99fc-4745-bf4d-4048e56099d8)

### Server Version and Plugins

1.19.4.
ViaVersion, Dynmap, LuckPerms, NoEncryption, PlaceholderAPI, Plugman, Spark.
I do not have more information. 

### Geyser Dump

https://dump.geysermc.org/klBnvjaGSPIuoElOLNuhmef50JZXlh4i

### Geyser Version

2.1.0-SNAPSHOT (git-master-1e79aa9)

### Minecraft: Bedrock Edition Device/Version

Android 13. Minecraft Bedrock 1.19.83.

**Comment by Konicai** [comment]
Shield recipe `Ingredient[]` received by Geyser: https://paste.gg/p/anonymous/2df9ba14759046fd98bc61d3b50656e5/files/7c23eec361e0465aaa87f72c1a7f5ae9/raw

**Comment by TBYT** [comment]
I can craft shield using multiple wood types on paper server version 1.20.1 with bedrock client 1.20.12.
