### ISSUE TITLE
Add Multi-Release: true to MANIFEST.MF

### ISSUE THREAD

**Issue by Kamillaova** [GeyserMC/Geyser#3785]
### What feature do you want to see added?

Multi-Release: true in MANIFEST.MF

### Are there any alternatives?

No.

**Comment by onebeastchris** [comment]
Why should we add it, if I may ask?
From my limited understanding of it; we aren't using that feature, so we shouldn't add it in the Manifest.. I could be wrong here; but why do you say we need it?

**Comment by Kamillaova** [comment]
>Why should we add it
Because you are using log4j2

**Comment by Kamillaova** [comment]
It also fixes #3693

**Comment by Konicai** [comment]
Yeah, log4j does indeed provide Java 9 code. PRs are welcome :)

**Comment by Konicai** [comment]
I'm just going to close this in favour of #3693
