### ISSUE TITLE
Bedrock player unable to connect to geyserMC fabric server

### ISSUE THREAD

**Issue by BladedDingo** [GeyserMC/Geyser#3789]
### Describe the bug

Bedrock players attempting to connect to  a minecraft Fabric server are unable to connect to the server.
after a few seconds, they are kicked off and unable to re-connect as continued attempts will disconnect them.

after a server re-start, the bedrock player may be able to connect and play/move/place/remove blocks. But if the bedrock user disconnects and then re-connects the error will occur.

The console will show the following error
[19:15:35] [epollEventLoopGroup-3-3/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.unix.Errors$NativeIoException: sendmmsg(..) failed: Operation not permitted

### To Reproduce

1. Bedrock player attempts to connect to GeyserMC/floodgate server
2. Player connects, but cannot move/interact
3. after 1-2 seconds, player is disconnected.

### Expected behaviour

bedrock user should be able to log in to the server as normal.

### Server Version and Plugins

latest log
https://mclo.gs/wMps5Ty

geyser dump
https://mclo.gs/ZoEqolq

Mods installed
lithium-fabric-mc1.19.4-0.11.1.jar
phosphor-fabric-mc1.19.x-0.8.1.jar
fabric-api-0.80.0+1.19.4.jar

Floodgate version
Build #98 (Apr 7, 2023, 7:05:26 PM)

### Geyser Dump

https://dump.geysermc.org/RyZdEyx8sqEJhEPp6sZ3AxskE2aIqmOK

### Geyser Version

2.1.0-SNAPSHOT (git-master-ba4e370)

### Minecraft: Bedrock Edition Device/Version

Minecraft - 1.19.83 (Bedrock) Android and Switch

**Comment by Camotoy** [comment]
I can't quite replicate. Does this happen without Phosphor and Fabric installed?

**Comment by Camotoy** [comment]
Also - can you send a log with you connecting with `debug-mode` enabled in Geyser's config?

**Comment by onebeastchris** [comment]
Interesting, it could be related to hardware then
Could you send a new geyser dump for reference? just out of curiosity

**Comment by BladedDingo** [comment]
> Interesting, it could be related to hardware then Could you send a new geyser dump for reference? just out of curiosity

sure
https://dump.geysermc.org/pot4c6V8ozzeEifPKnHoAIQa0pDEcPDl
