### ISSUE TITLE
Bedrock player spectator mode infinite fall glitch

### ISSUE THREAD

**Issue by JHarris12345** [GeyserMC/Geyser#3792]
### Describe the bug

If a bedrock player is in spectator mode and goes under ground, they fall to bedrock and cannot move

### To Reproduce

1. Go on a bedrock account
2. Go in spectator mode
3. Go underground

### Expected behaviour

You don't fall

### Geyser Dump

https://dump.geysermc.org/yMF3CqWpKaxWwO9SNPQFHJmbkI3ALWEl

### Geyser Version

2.1.0-SNAPSHOT (git-master-6e9b272)

### Minecraft: Bedrock Edition Device/Version

iPhone 12 Pro

**Comment by Elavalur** [comment]
Make sure the Geyser is up to date. I don't see any spectating issue from my end nor I can replicate your issue.

**Comment by onebeastchris** [comment]
I can replicate it, just try flying into a hill or through blocks

**Comment by Elavalur** [comment]
> I can replicate it, just try flying into a hill or through blocks

I can't see an issue from my end 😅 all looks good for me.

**Comment by onebeastchris** [comment]
Just out of curiosity; are you running a proxy setup?
I am able to replicate it with geyser-velocity, not e.g. geyser-fabric

**Comment by Elavalur** [comment]
> Just out of curiosity; are you running a proxy setup?
> 
> I am able to replicate it with geyser-velocity, not e.g. geyser-fabric

It's def. on velocity. https://dump.geysermc.org/27qPpzE882OxF1OGZobQqAvmklErkn2q

**Comment by Elavalur** [comment]
I feel like I'm not affected by it unless by any chances had to do with my plugins from my backend 😞

**Comment by onebeastchris** [comment]
Actually.. you're running the latest version, @JHarris12345 isnt. Please try updating first?

**Comment by Elavalur** [comment]
> Actually.. you're running the latest version, @JHarris12345 isnt. Please try updating first?

You said you can replicate it so I was wondering if it has to do with our end lol but anyhow that's all I can say here. Fin. :)

**Comment by onebeastchris** [comment]
i'm able to replicate, but i'm not running on the latest version either on said velocity server; i'm not on the main geyser branch - i think that's why i couldnt replicate it on geyser-fabric, as that's a test setup i have that's always up to date

**Comment by Elavalur** [comment]
> i'm able to replicate, but i'm not running on the latest version either on said velocity server; i'm not on the main geyser branch - i think that's why i couldnt replicate it on geyser-fabric, as that's a test setup i have that's always up to date

Ah quick to catch on! Forgot to add one thing in my message but you catched up.

**Comment by onebeastchris** [comment]
Yup, is fixed on latest Geyser version. @JHarris12345 , please update Geyser, and if the issue persists, send a new dump - if it doesnt, i'll close this as completed.

**Comment by Jens-Co** [comment]
Issue was fixed in #3770, thanks for reporting tho!
