### ISSUE TITLE
Console Spam PlayerSkinPacket

### ISSUE THREAD

**Issue by kolderz** [GeyserMC/Geyser#3793]
### Describe the bug

I got a lot of these messages spamming my console for a very long time until I restart the proxy.

Logs: https://controlc.com/50cf88a0

### To Reproduce

1. Let Bed Rock players join the server.

### Expected behaviour

Idk why it happened, might be something related to Bed Rock Skin? 

### Server Version and Plugins

Geyser version 2.1.0-SNAPSHOT (git-master-ba4e370)

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-ba4e370)

**Comment by onebeastchris** [comment]
Please attach a Geyser dump, and a server log.

**Comment by clarkkentz** [comment]
> Please attach a Geyser dump (run geyser dump in the server console & send the link here), and a server log (latest.log file from the logs folder via mclo.gs).

I don't think I can upload the logs. It's been spamming like crazy for the whole time the proxy ran (10gb logs). I'll try when the proxy restart.

**Comment by onebeastchris** [comment]
Velocity, just like most other servers, seperates logs into separate files - 10GB could maybe (unlikely, but theoretically possible) be the size of the "logs" folder. An individual log file is unlikely to ever be this huge.. 

Anyways, could you still send the geyser dump? It doesn't include logs/a restart.

**Comment by clarkkentz** [comment]
> Velocity, just like most other servers, seperates logs into separate files - 10GB could maybe (unlikely, but theoretically possible) be the size of the "logs" folder. An individual log file is unlikely to ever be this huge..
> 
> Anyways, could you still send the geyser dump? It doesn't include logs/a restart.

https://dump.geysermc.org/78dVpoSJPOsW0JEvjQTniAa0UzK3F2rs

**Comment by Konicai** [comment]
Does this still occur?

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
