### ISSUE TITLE
Jukebox doesnt stop play music

### ISSUE THREAD

**Issue by SuprexDE** [GeyserMC/Geyser#3794]
### Describe the bug

If you place a jukebox and put a record in it and then take it out again, the music keeps playing.

### To Reproduce

1. Place a jukebox
2. Put any vinyl in it
3. Take the record out of the box

### Expected behaviour

The music should stop

### Server Version and Plugins

https://suprexde.de/img/Vove1/DOZipeQE86.png

### Geyser Dump

https://dump.geysermc.org/EGwrT7WQWmkStpaq6JFXueosC0s4PbvA

### Geyser Version

2.1.0-SNAPSHOT (git-master-6da8d5e)

### Minecraft: Bedrock Edition Device/Version

1.19.83, Minecraft for Windows 10

**Comment by onebeastchris** [comment]
Please try updating Geyser-Standalone, and updating ViaVersion, this is likely already fixed.

**Comment by SuprexDE** [comment]
I tested it again on the two newest versions and the error is still there

**Comment by onebeastchris** [comment]
Okay, then send new dumps:
- for geyser: run "geyser dump" in the server console & send the link here.
- for viaversion: run "viaversion dump" in the server console & send the link here.

**Comment by SuprexDE** [comment]
ViaVersion-Dump: https://dump.viaversion.com/dfd1754d2541986d230754e057373612ce4291b2c46b4f3641e3f0ab4fe63825
Geyser-Dump: https://dump.geysermc.org/6febnjf4mdtSmyEAGT2lBMHUWR4gPrMR

**Comment by onebeastchris** [comment]
https://ci.viaversion.com/job/ViaVersion-DEV/825/
Could you try this via dev build? Seems like they havent pushed the record fix https://github.com/ViaVersion/ViaVersion/commit/638378cddf5421c88d27e4673673ee1d7a0e7dde to master yet.

**Comment by SuprexDE** [comment]
ahh now it works, thanks :)
