### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by kingboydeve** [GeyserMC/Geyser#3796]
### What feature do you want to see added?

Pls add pmmp and nukkit and waterdog and. Textures support

### Are there any alternatives?

?

**Comment by onebeastchris** [comment]
How exactly would you imagine us supporting pmmp or nukkit?
Geyser exists so bedrock players can join and play on java servers.
As for waterdog, that should be already possible - you could have geyser as a 'server' behind a waterdog proxy.

As for "textures", what are you referring to? Geyser already has support for loading bedrock edition resource packs.
