### ISSUE TITLE
Movement error (I can't move)

### ISSUE THREAD

**Issue by CLMurikk** [GeyserMC/Geyser#3801]
### Describe the bug

Every time I try to connect to my server from mc bedrock, for some reason it won't let me move. It is as if I had been made /freeze (example).
While trying to figure out what was going on, I noticed that the movement bug only affects the default rank (and ranks less than owner (op)).

### To Reproduce

Start the server and connect
As soon as you enter, the movement is already bugged (Not even at the time of logging (/login) does it let you move)

### Expected behaviour

That the player can move without problems.

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/127791368/63bd88b2-249e-47c9-a4a8-b3e7f072a56e

### Server Version and Plugins

Server ver:
Paper version git-Paper-468 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9087a64)

Plugins:
- ActionHealth-3.5.8-all
- AdvancedBan-Bundle-2.3.0-RELEASE
- AdvancedNMotd-9.2.0
- AuthMe-5.6.0-SNAPSHOT
- ChatEx
- ChatManager_3.7.7
- citizens-2.0.31-SNAPSHOT
- CitizensCMD-2.6.10
- citizenstext-1.20
- CommandPanels
- CoreProtect-21.2
- EasyCommandBlocker
- EasyJoin 2.2.3
- EssentialsX-2.20.0-dev+44-43d84de | EssentialsXChat-2.20.0-dev+44-43d84de | EssentialsXDiscord-2.20.0-dev+44-43d84de | EssentialsXSpawn-2.20.0-dev+44-43d84de
- FearFeeling_v2.15
- floodgate-spigot
- ForcePack-1.2.3
- Geyser-Spigot
- Graves-4.9
- HolographicDisplays
- ItemEdit-3.0.5
- KingdomsX-1.14.18.3.0.1
- LuckPerms-Bukkit-5.4.40
- MessageAnnouncer-1.12.3
- Minepacks
- Multiverse-Core-4.3.1
- PlaceholderAPI-2.11.3
- PlayerKits
- PlayerTimeLimit
- ProtocolLib-5.0.0-SNAPSHOT
- SkinsRestorer
- sleep-most-5.2.5
- StaffChatReloaded
- SternalBoard-2.0.2-all
- TAB.v3.3.1
- TradeSystem_v2.3.0
- UltimateTimber-2.3.6-stable
- Vault
- ViaBackwards-4.6.1
- ViaVersion-4.6.2
- worldedit-bukkit-7.2.13
- worldguard-bukkit-7.0.8-beta-01-dist

### Geyser Dump

https://dump.geysermc.org/RYDjFoOyv4fWrSTJuCl5t9ilSSMBDaH6

### Geyser Version

2.1.0-SNAPSHOT (git-master-ba4e370)

### Minecraft: Bedrock Edition Device/Version

1.19.83, pc (w10)

**Comment by rtm516** [comment]
This is mostlikely caused by authme (your auth plugins). Please remove that.

**Comment by CLMurikk** [comment]
nope The problem persists (delete the authme and nothing)

**Comment by CLMurikk** [comment]
nope The problem persists (delete the authme and nothing)

**Comment by rtm516** [comment]
Can you try following this

If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
Temporarily remove/move half of your plugins from your server's plugins folder.
* If the problem persists, remove another half.
* If the problem goes away, swap that half of your plugins with the other half.
* Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by CLMurikk** [comment]
THANK YOU! The problem was the plugin ''Forcepack''
Greetings!
![Captura de pantalla 2023-05-27 133243](https://github.com/GeyserMC/Geyser/assets/127791368/51c5aba0-b381-4143-98ad-da8ea38247b1)
