### ISSUE TITLE
"Operation not permitted" and disconnection quickly after joining

### ISSUE THREAD

**Issue by hicupalot** [GeyserMC/Geyser#3805]
### Describe the bug

When I join the Server from the Bedrock client I am disconnected after around 5 seconds, during this 5 seconds chunks fail to load and it's as though there is no packet conversion as all mobs and entities are frozen.

### To Reproduce

1. Join a server

### Expected behaviour

You can play normally

### Server Version and Plugins

Geyser version 2.1.0-SNAPSHOT (git-master-2773965) (Java: 1.19.4, Bedrock: 1.19.40/1.19.41 - 1.19.80/1.19.81)

Originally I thought this could be a plugin conflict but I tried removing all plugins except floodgate, geyser and protocollib and the same issue persisted. I have since moved all plugins back to the plugins folder as removing them didn't fix the issue.

### Geyser Dump

https://dump.geysermc.org/imFFAdVuVtuY9A79rHsu97IV5BCrNHur

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-2773965)

### Minecraft: Bedrock Edition Device/Version

1.19.83, PC, this also occurs on 1.19.83 Xbox One

### Additional Context

I don't know if this issue is related to how this version of Bedrock isn't yet supported, but other people have referenced issues with this version and there was no discussion of the version of bedrock being the issue.

The errors which are pasted into console when this happens are this 
`[29.05 16:32:30] [Server] [WARN] [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
[29.05 16:32:30] [Server] io.netty.channel.unix.Errors$NativeIoExceptionsendmmsg(..) failed: Operation not permitted
[29.05 16:32:30] [Server] [WARN] [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
[29.05 16:32:30] [Server] io.netty.channel.unix.Errors$NativeIoExceptionsendToAddresses(..) failed: Operation not permitted`

**Comment by hicupalot** [comment]
Bump! The issue is still happening

**Comment by AidenKingGit** [comment]
I have same problem

**Comment by hicupalot** [comment]
Error is still happening on 1.20

**Comment by AidenKingGit** [comment]
hicupalot are you also using budget bisect

**Comment by hicupalot** [comment]
> hicupalot are you also using budget bisect

Nope I'm using a different hosting provider

**Comment by yepikaiye** [comment]
Having the same issue

**Comment by onebeastchris** [comment]
Those of you with this issue; could you try the Geyser build here https://github.com/onebeastchris/Geyser/actions/runs/5489903438, and send back logs (via mclo.gs) with the errors?
Currently, ` An exceptionCaught() event was fired, and it reached at the tail of the pipeline. ` just shows that there is some exception, but not what the exception is - the linked build will hopefully show it, allowing us to fix it.

**Comment by AidenKingGit** [comment]
adding it right now

**Comment by AidenKingGit** [comment]
[08.07 13:45:15] [Server] [WARN] [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
[08.07 13:45:15] [Server] io.netty.channel.unix.Errors$NativeIoExceptionsendToAddresses(..) failed: Operation not permitted
[08.07 13:45:15] [Server] [INFO] [Geyser-Spigot] Luranic9062 has disconnected from the Java server because of disconnect.lost
[08.07 13:45:15] [Server] [INFO] [floodgate] Floodgate player logged in as .Luranic9062 disconnected
[08.07 13:45:15] [Disconnect] .Luranichas disconnected, reason: Disconnected
[08.07 13:45:15] [Server] [INFO] [-] .Luranic9062 Left the game.

**Comment by onebeastchris** [comment]
Please send a full log via mclo.gs

**Comment by AidenKingGit** [comment]
https://mclo.gs/7KcAydr

**Comment by onebeastchris** [comment]
Oh well, that test build did not work :/ Imma see if i can come up with a one that gives proper errors.

**Comment by AidenKingGit** [comment]
are you gonna be done with it in this hour or should i come back way later

**Comment by onebeastchris** [comment]
After asking around in netty's discord channel; the issue would most likely be with the server hosting provider - "Operation not permitted" issues from netty would imply something is blocking outgoing connections. Which is most likely related to your server hosting provider's docker/iptables config.

Basically, from what i understand - this is not up to Geyser to fix, but rather your server hosting provider :/

**Comment by onebeastchris** [comment]
Closing as this isn't an issue on Geysers end. If you're still encountering it, then please make sure your firewall is not blocking outgoing UDP traffic - if you are using a server hosting provider, contact their support for help.
