### ISSUE TITLE
server is not found at bedrock

### ISSUE THREAD

**Issue by lemonvace** [GeyserMC/Geyser#3811]
### Describe the bug

hi i have a problem so i installed geyser bungee cord but the server is not displayed on bedrock and i have tried everything but it still doesn't work. and in the bungee cord console it says stop if you joint with bedrock InitialHandler - read timed out

### To Reproduce

?

### Expected behaviour

i expected to be able to join bedrock

### Server Version and Plugins

Server Version: 1.17.1

### Geyser Dump

https://dump.geysermc.org/lMYNpe6qs6KmiYE1vHBvAyQfRmB0TFp5

### Geyser Version

Build #157

### Minecraft: Bedrock Edition Device/Version

v1.19.83 Pc Edition

**Comment by onebeastchris** [comment]
As this would be a configuration issue, not a bug, please follow our guides on the wiki:
Setup guide: https://wiki.geysermc.org/geyser/setup/, and a general guide to fix unable to connect issues: https://wiki.geysermc.org/geyser/fixing-unable-to-connect-to-world/

If those instructions don't help, join the GeyserMC discord and ask in the support channel there.
