### ISSUE TITLE
Stonecutter fails to cut a whole stack of blocks

### ISSUE THREAD

**Issue by payphone101** [GeyserMC/Geyser#3816]
### Describe the bug

Stonecutters seemingly gives up on crafting a stack of items when using the quick move button on a controller.

### To Reproduce

1. Join the game
2. Open/interact with a stonecutter
3. cut a stack of stone brick (or any eligible block) to slabs or stairs via pressing the quick move button on the controller
4. observe behaviour

### Expected behaviour

The stonecutter should craft all the stack of blocks into stair/slabs

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1110605776248123425/1115787697093623819/Screenrecorder-2023-06-07-07-33-03-459.mp4

### Server Version and Plugins

1.19.4
ArmoredElytra, BlueMap, BungeeGuard, Chunky, CoreProtect, DeluxeMenus, DiscordSRV, dynmap, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, Falling, floodgate, LuckPerms, NoEndermanGrief, PlaceholderAPI, Plan, ProtocolLib, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldBorder

### Geyser Dump

https://dump.geysermc.org/Tl1PDpun4m3KHbt83P2gnrc7slHG70zR

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-246ebdd) (Java: 1.19.4, Bedrock: 1.19.40/1.19.41 - 1.19.80/1.19.81)

### Minecraft: Bedrock Edition Device/Version

1.19.81 (Happens on multiple devices)

**Comment by hw2007** [comment]
I've seen this happen for me too, the controller player on our server always has trouble using stonecutters

**Comment by shantek** [comment]
Agreed. This is a huge pain for bedrock players on our server.
