### ISSUE TITLE
Infinite effect symbol breaks bedrock effects

### ISSUE THREAD

**Issue by mrunningmasterc** [GeyserMC/Geyser#3832]
### Describe the bug

With Minecraft's new change in 1.19.4 they added in an infinite sign whenever the effect or potion effect is infinite. This will break bedrock players potion effect/effects and won't give it to them. Can there be a fix for this?

### To Reproduce

Use latest paper version 1.19.4
use geysmc bungee and connect to a survival server
give infinite effect time to bedrock player
It won't give it to player.

### Expected behaviour

it won't give bedrock player the infinite effect with the change in Minecraft 1.9.4.

### Server Version and Plugins

git-Purpur-1983 (MC: 1.19.4)*

### Geyser Dump

https://dump.geysermc.org/qRdmjQGdzkJ3fOfInwj4Ihkuykc8lsu0

### Geyser Version

 2.1.1-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20

**Comment by Konicai** [comment]
>  give infinite effect time to bedrock player
can you provide a command to reproduce?
