### ISSUE TITLE
Geyser sends invalid emote packets

### ISSUE THREAD

**Issue by alexanderdidio** [GeyserMC/Geyser#3838]
### Describe the bug

Basically the player in the geyser log started the chain reaction of errors being thrown in the velocity log for all players that tried to join after them which persisted until the geyser player (in the geyser log) switched to a different server.

I'm not sure if the geyser log error is related to the issue in the velocity log, but it's **always** a geyser player that somehow gets corrupted and prevents anyone from joining the server until they leave.

Velocity: (https://mcpaste.io/34de884e4d428d4d)
Geyser: (https://mcpaste.io/230e85bfaf16f0bf)

### To Reproduce

Not really a way to explain how to reproduce.

### Expected behaviour

No error?

### Geyser Dump

https://dump.geysermc.org/Go4z66sz2jnAfdjtgmYVUhgWi2bS2r8D

### Geyser Version

 Geyser version 2.1.1-SNAPSHOT (git-master-b78ca43)

### Minecraft: Bedrock Edition Device/Version

All

**Comment by Konicai** [comment]
thats not the geyser dump, thats the log, but thank you

also include the geyser and velocity dump please

**Comment by alexanderdidio** [comment]
> geyser dump as well please

Fixed

**Comment by onebeastchris** [comment]
There is no need to refer to this issue in different one's - as you may have noticed, a bug fix was already made (https://github.com/GeyserMC/Geyser/pull/3841), which will probably resolve this.
