### ISSUE TITLE
Errors on PacketDefinition lookup up of ServerToClientHandshakePacket and ResourcePacksInfoPacket

### ISSUE THREAD

**Issue by alexanderdidio** [GeyserMC/Geyser#3846]
### Describe the bug

Error encoding ResourcePacksInfoPacket Geyser console errors: https://mcpaste.io/42d16e7b30b5c5ef

### To Reproduce

N/A

### Expected behaviour

N/A

### Geyser Dump

https://dump.geysermc.org/MAiWkF7VCom3Q6DTOaAfL3WGeJ83BbMu

### Geyser Version

2.1.1-SNAPSHOT (git-DEV-eb825ee)

**Comment by Konicai** [comment]
Is this only happening with one player? And can you update to the latest version here: <https://geysermc.org/download#standalone>

**Comment by Camotoy** [comment]
https://github.com/GeyserMC/Geyser/commit/3ec0d82d467041c70294582d4ec2cbccceea9492 should fix this.
