### ISSUE TITLE
Geyser-Fabric unnecessarily requiring the server to be 1.20

### ISSUE THREAD

**Issue by KewlSage** [GeyserMC/Geyser#3848]
### Describe the bug

geyser-fabric crashing the 1.19.4 server on launch because its not 1.20 even though it has viafabric allowing connections from 1.20 java clients

### To Reproduce

make fabric 1.19.4 server with viafabric
install geyser-fabric
crash on launch due to requiring 1.20

### Expected behaviour

server starts and runs perfectly with bedrock support on the base of fabric 1.19.4

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/46802123/42dcedfb-280f-46a9-8736-132f8041bda4)

### Server Version and Plugins

fabric

### Geyser Dump

unable

### Geyser Version

(geyser-fabric) 2.1.1-SNAPSHOT 231e9a1

**Comment by Camotoy** [comment]
Unfortunately this is a won't fix for now. As much as we'd love to support 1.19.4 and 1.20, Minecraft changed a function name (`getLevel()` to `level()`) and this screwed things up enough where it's not easy to support both versions. Fixing this issue would require a significant overhaul of how we treat Fabric to implement multi-version.
