### ISSUE TITLE
Maps don't display for Bedrock clients.

### ISSUE THREAD

**Issue by mibby** [GeyserMC/Geyser#385]
**Describe the bug**
Map data / packets aren't sent to the bedrock client. Maps mounted in item frames are instead invisible. 

**To Reproduce**
1. Look at map in item frame.
2. Maps are invisible.

**Expected behavior**
Being able to see custom maps / map data.

**Screenshots / Videos**

On Java.
![link](https://i.imgur.com/dy5odwD.png)

On Bedrock.
![link2](https://cdn.discordapp.com/attachments/144136525553205248/701622881137721364/Map1.png)
![link3](https://cdn.discordapp.com/attachments/144136525553205248/701622884543496332/Map2.png)
**Server Version**
Paper dev 201 (Spigot 1.15.2)
Waterfall dev 327 (BungeeCord 1.15.2)

**Geyser Version**
Geyser inventory dev 24 (Using as BungeeCord Plugin)
Floodgate development dev 5 (Using as BungeeCord Plugin)

**Minecraft: Bedrock Edition Version**
Minecraft Bedrock 1.14.60

**Additional Context**
Java 11.0.7 (AdoptOpenJDK LTS)
Centos 8 (Linux)

Map data loads and displays fine for Java clients.

**Comment by rtm516** [comment]
This is because item frames have not been implemented yet.

**Comment by RednedEpic** [comment]
Resolved in #423.
