### ISSUE TITLE
Smithing Tables

### ISSUE THREAD

**Issue by mrunningmasterc** [GeyserMC/Geyser#3857]
### Describe the bug

When right clicking smithing tables with bedrock account they don't open.

### To Reproduce

place smithing table
right click to open

### Expected behaviour

the smithing table won't open

### Geyser Version

2.1.1-SNAPSHOT

**Comment by Camotoy** [comment]
Please attach a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by Konicai** [comment]
Server version and `/geyser dump` please.

**Comment by mrunningmasterc** [comment]
https://dump.geysermc.org/HoLJOANx8Z0vVjHIzxQFHDdgwn1OGzqW


purpur- 1985 (1.19.4)

**Comment by onebeastchris** [comment]
https://github.com/ViaVersion/ViaVersion/issues/3338
This is unfortunately a ViaVersion bug - 1.20 java clients (and by extension, geyser too since it imitates a 1.20 client) can't use the smithing table on older java versions right now.

**Comment by mrunningmasterc** [comment]
Ahhhh ok thank you for notifying me of that.

**Comment by onebeastchris** [comment]
Closing this as it is a Via issue.
