### ISSUE TITLE
Armor trims don't work

### ISSUE THREAD

**Issue by Savariable** [GeyserMC/Geyser#3858]
### Describe the bug

Armor trims are not visible at all for the bedrock player, you can apply them however the armor does not say it has a trim in your inventory and the trim does not show up, and you also can't see trims on other players 

### To Reproduce

1) just apply a trim to armor and you can see that it doesn't show up

### Expected behaviour

that you can actually see the trim on your armor

### Screenshots / Videos

![Screenshot (940)](https://github.com/GeyserMC/Geyser/assets/136204175/1fe79ab6-0d23-42a5-a62d-fa881cab36dc)
![Screenshot (941)](https://github.com/GeyserMC/Geyser/assets/136204175/7013aaab-eb36-4be6-8418-076ba4d572ed)
![Screenshot (942)](https://github.com/GeyserMC/Geyser/assets/136204175/c5a673eb-046e-449b-a841-ac4d6e591911)
![2023-06-10_18 04 50](https://github.com/GeyserMC/Geyser/assets/136204175/5a825029-48d2-4e90-b677-2b35d9bf846d)
![2023-06-10_18 05 21](https://github.com/GeyserMC/Geyser/assets/136204175/4b0206d9-58f5-4d21-8a15-e52e3a099442)

### Geyser Version

geyser-fabric 1.20

### Minecraft: Bedrock Edition Device/Version

1.20.0, PC

**Comment by onebeastchris** [comment]
Please send a Geyser dump by running "geyser dump" in the server console & then send the link here.

**Comment by Savariable** [comment]
https://dump.geysermc.org/gWSFdWbOym8xpdQGiULQLco23FgicU5A

**Comment by onebeastchris** [comment]
You are running 8 commits behind; please try updating Geyser and see if the issue persists.

**Comment by Savariable** [comment]
updated, it works fine now!

**Comment by onebeastchris** [comment]
Coolio! Thanks for the reply, and will close this as completed.
