### ISSUE TITLE
The underlined color code shows different color

### ISSUE THREAD

**Issue by kolderz** [GeyserMC/Geyser#3859]
### Describe the bug

When using the underlined color code, it will show different colors for the Bed Rock player.

### To Reproduce

1. Rename the item using any color code and use the Underline color code
2. Rename the item using any color code.
3. Compare the two

### Expected behaviour

Show the correct color

### Screenshots / Videos

Bold and Color Code
![ApplicationFrameHost_5innFLpmiW](https://github.com/GeyserMC/Geyser/assets/10612667/dac3110c-754c-4825-9251-243316185d54)
Bold, Color, and Underlined color code
![ApplicationFrameHost_5sZcXsMt24](https://github.com/GeyserMC/Geyser/assets/10612667/498dfb7e-80d1-4d35-be93-af5788999989)

### Server Version and Plugins

git-Purpur-1632

### Geyser Version

This server is running Geyser version 2.1.1-SNAPSHOT (git-master-049d64d) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)

### Minecraft: Bedrock Edition Device/Version

1.20, iPhone iOS16.5

**Comment by rtm516** [comment]
Unfortunately this seems to be a bedrock bug, confirmed by trying the below in a singleplayer game
```
§l§4Bold Color
§l§4§nBold Color Underline
```
![image](https://github.com/GeyserMC/Geyser/assets/5401186/87102e52-b31c-48aa-8bab-5d3b4c0b89f4)
