### ISSUE TITLE
Bedrock clients do not get teleported to the correct location.

### ISSUE THREAD

**Issue by mibby** [GeyserMC/Geyser#386]
**Describe the bug**
Bedrock clients do not get teleported to the correct location.

**To Reproduce**

1. Hit button that teleports players away to a new location.
2. Get sent to a different area than intended.

The client hits a button that teleports from their current location (1242, 89, -228) to a new location underground (1167, 71, -251). For some reason Bedrock clients glitch and end up half way to the new location.

**Expected behavior**
The client teleported being sent to the correct location.

**Screenshots / Videos**

The button location that teleports players.
![link1](https://i.imgur.com/QplG2X6.png)

Where you are suppose to end up.
![link2](https://i.imgur.com/mBEBT9s.png)

Showing the distance of teleport with spectator mode. Player travels a couple chunks and underground.
![link4](https://i.imgur.com/gBCCiAj.png)
![link3](https://i.imgur.com/UCLmiB0.png)

Where bedrock players actually end up, usually in the center of the pond.
![link5](https://i.imgur.com/Fet3wuB.jpg)
**Server Version**
Paper dev 201 (Spigot 1.15.2)
Waterfall dev 327 (BungeeCord 1.15.2)

**Geyser Version**
Geyser inventory dev 24 (Using as BungeeCord Plugin)
Floodgate development dev 5 (Using as BungeeCord Plugin)

**Minecraft: Bedrock Edition Version**
Minecraft Bedrock 1.14.60

**Additional Context**
Java 11.0.7 (AdoptOpenJDK LTS)
Centos 8 (Linux)

Works fine with the java client. You can test behavior on my server if needed, as the starting location has an introduction for new players. (Assuming bedrock clients can connect with geyser and there is no broken pipe with it.)

It doesn't seem to happen all the time, but it happens enough that it's reproducible. You can ``/spawn`` to be brought back to the beginning introduction area if teleporting didn't break the first time.

IP: ``play.eoscraftmc.com``

**Comment by Loganh4005** [comment]
I can confirm this though for me the player spawns in the void and doesn't get killed by the void :( (bedwars)

**Comment by DoctorMacc** [comment]
The void is now its own issue - #406.

**Comment by BrianValente** [comment]
Probably related to my issue #281
