### ISSUE TITLE
All mounts spin when sitting on them

### ISSUE THREAD

**Issue by PapaBigMac69** [GeyserMC/Geyser#3860]
### Describe the bug

All mountables start spinning , and are uncontrollable by the player.

### To Reproduce

1: Put saddle on camel
2: Sit on Camel
3: Try to Move
4: Let the spinning begin.

### Expected behaviour

Mounts do not spin , and are controllable by the player.

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/99443917/6e62b2b7-0b26-4a06-b0ae-fbbddc81250c

### Server Version and Plugins

This server is running Paper version git-Paper-8 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: https://github.com/PaperMC/Paper/commit/3722877c3c16e4e88c45a5133ec7a0e9efdd1f92)

Plugins: CoreProtect, floodgate, ForcePack, Geyser-Spigot, GeyserUpdater, teleportScroll, Vault, ViaVersion, WorldEdit

Datapacks: [vanilla (built-in)], [file/bukkit (world)]

### Geyser Dump

 https://dump.geysermc.org/G9GEk90Qxx1jfKBfAvsw6TjvNxLQ8JPk

### Geyser Version

This server is running Geyser version 2.1.1-SNAPSHOT (git-master-53d0026) (Java: 1.20

### Minecraft: Bedrock Edition Device/Version

Bedrock: 1.19.80/1.19.81 - 1.20.0) , Switch , Windows , Xbox , Playstation

**Comment by TazAlonzo** [comment]
Any updates on this? My friends want to ride their new camels I spent 5 hours getting them.

**Comment by gamer50082** [comment]
Could use horse method of moving for camel for client side

**Comment by seriousfreezing** [comment]
And there's no way of walking on it

**Comment by USBCharger** [comment]
Wanted to bump this issue since one of my players had an issue with it a few days ago to see if anyone might be able to get further on it or anything :)

**Comment by MODNMETL** [comment]
Bumping too as our players are getting stuck spinning on various blocks when riding horses. Our server is running 1.20.4 at the mo.

**Comment by TankObliterator** [comment]
Any news on this bug yet?

**Comment by onebeastchris** [comment]
This has been implemented in the latest commit. Thanks for reporting it!
