### ISSUE TITLE
Geyser 1.20 not working on my Paper Server :(

### ISSUE THREAD

**Issue by jeziqt** [GeyserMC/Geyser#3864]
### Describe the bug

Details:

- When players login they enter the world and can either only see entities or nothing (void)
- I did the basic troubleshooting stuff but nothing
- So I decided to backup and reset the server (and delete everything), after loading the 1.20 paper jar file, I added the world, world_nether, and world_the_end from the back up, then added Geyser and Floodgate, then added the key.pem and set the config properly
- I then ran the server
- My Bedrock account was then able to join and I was able to play properly after a few minutes
- So I decided to join in with my Java account, to check if I can still play properly
- After a couple more minutes with my Bedrock and Java account together in the server, in my Bedrock account, I suddenly was not able to open chests, my invetory, there were no item drops when I mine stuff, etc

I hope I can get help for this, 1/3 of the players in my server use Bedrock, and Bedrock is so useful when I'm away from my pc. Thank you in advance!

### To Reproduce

I don't know how to reproduce this, Geyser should work but it doesn't :(((

### Expected behaviour

Bedrock players should be able to join and play in the server.

### Screenshots / Videos

![33F4C540-1696-4200-99A4-D7F1543784B3](https://github.com/GeyserMC/Geyser/assets/136465395/4f2e69bf-49c7-472d-8382-803fb9caf4f2)

### Geyser Dump

https://dump.geysermc.org/VYFmjMEDRA6VmYA3sx8KBIw4zaplp15b

### Geyser Version

Build 182

### Minecraft: Bedrock Edition Device/Version

1.20, Android and iPhone, Cracked and Official

**Comment by onebeastchris** [comment]
Likely caused by #2861  - see there for a fix.
