### ISSUE TITLE
Smithing tables from before 1.20 are unusable

### ISSUE THREAD

**Issue by Arqui9897** [GeyserMC/Geyser#3866]
### Describe the bug

**The Smithing Table** is not working since java and bedrock in the latest build of geyser bulid #182 and updating Floodgate build #59 this in paper/spigot when interacting with the smithing table makes the click animation several times like about 6

### To Reproduce

It's quite simple, it's just interacting with the Smithing Table, it doesn't work in bedrock or java

### Expected behaviour

 normal behavior The Smithing Table

### Screenshots / Videos

https://youtu.be/1jy27oHDV1s

### Server Version and Plugins

server host 1.19.2 using viaversion #4.7.0 compatibility until reaching 1.20

### Geyser Dump

https://dump.geysermc.org/smaY6ta9Hzdtx26hBF82seXRi1H81pv3

### Geyser Version

geyser bulid #182

### Minecraft: Bedrock Edition Device/Version

minecraft windows, movil y minecraft java

### Additional Context

I think it's the geyser because before updating the plugin it worked and after updating to a previous build of geyser that I'm reporting it works in java but not in bedrock now that I update to this version that I'm reporting java and bedrock no longer work

**Comment by Konicai** [comment]
This has been fixed in ViaVersion `4.7.1-SNAPSHOT`: https://ci.viaversion.com/job/ViaVersion-DEV/

**Comment by TBYT** [comment]
> This has been fixed in ViaVersion `4.7.1-SNAPSHOT`: https://ci.viaversion.com/job/ViaVersion-DEV/

it is not, they're using the furnace gui but bedrock has a client limitation where you can't put the netherite ingot in the fuel slot.
I'm taking it upon myself to edit the one nbt value and try out different gui's and find one that would work on bedrock.

**Comment by FlorianMichael** [comment]
> > This has been fixed in ViaVersion `4.7.1-SNAPSHOT`: https://ci.viaversion.com/job/ViaVersion-DEV/
> 
> it is not, they're using the furnace gui but bedrock has a client limitation where you can't put the netherite ingot in the fuel slot. I'm taking it upon myself to edit the one nbt value and try out different gui's and find one that would work on bedrock.

Maybe we could go with an Anvil GUI?

**Comment by onebeastchris** [comment]
Anvil GUI likely would not work due to a client limitation where we cannot influence the outcome.
Seeing that this issue is still there due to the geyser bug with the Via workaround, i'll reopen this

**Comment by TBYT** [comment]
> Anvil GUI likely would not work due to a client limitation where we cannot influence the outcome. Seeing that this issue is still there due to the geyser bug with the Via workaround, i'll reopen this

I think Anvil GUI would work, I don't know the nbt number for it though whereas the viaversion devs do. But i'm going through random gui menu's now until i could find that one.

**Comment by FlorianMichael** [comment]
> > Anvil GUI likely would not work due to a client limitation where we cannot influence the outcome. Seeing that this issue is still there due to the geyser bug with the Via workaround, i'll reopen this
> 
> I think Anvil GUI would work, I don't know the nbt number for it though whereas the viaversion devs do. But i'm going through random gui menu's now until i could find that one.

I can build you a ViaVersion jar with the anvil as gui if you want

**Comment by TBYT** [comment]
> > > Anvil GUI likely would not work due to a client limitation where we cannot influence the outcome. Seeing that this issue is still there due to the geyser bug with the Via workaround, i'll reopen this
> > 
> > 
> > I think Anvil GUI would work, I don't know the nbt number for it though whereas the viaversion devs do. But i'm going through random gui menu's now until i could find that one.
> 
> I can build you a ViaVersion jar with the anvil as gui if you want

I am building the different ones on a fork. msg me on discord. same username as github

**Comment by FlorianMichael** [comment]
> > > > Anvil GUI likely would not work due to a client limitation where we cannot influence the outcome. Seeing that this issue is still there due to the geyser bug with the Via workaround, i'll reopen this
> > > 
> > > 
> > > I think Anvil GUI would work, I don't know the nbt number for it though whereas the viaversion devs do. But i'm going through random gui menu's now until i could find that one.
> > 
> > 
> > I can build you a ViaVersion jar with the anvil as gui if you want
> 
> I am building the different ones on a fork. msg me on discord. same username as github

I have sent you the Jar

**Comment by FlorianMichael** [comment]
> Anvil GUI likely would not work due to a client limitation where we cannot influence the outcome. Seeing that this issue is still there due to the geyser bug with the Via workaround, i'll reopen this

I have now gone through all the GUIs that are available in the Java Edition and Bedrock Edition, and could not find one that works equally well on both editions and which would not be a downgrade compared to the current fix in ViaVersion.

**Comment by Camotoy** [comment]
Thanks for looking into it.

Perhaps the best solution on the client end would be to just... show the original smithing table, since as far as I can tell Bedrock doesn't actually have that removed.

I'll talk with the Via guys about an idea I have.

**Comment by raphaelfasilva** [comment]
Geyser Team,

Have prevision to solve these problem, because players of my server everytime ask me about about it

Thank You Raphael Silva

**Comment by roggy666** [comment]
How long will it take to fix this problem? And will it ever ?

**Comment by gre3x** [comment]
Any updates on this? My players also complaining about this

**Comment by Konicai** [comment]
If we provide a fix or workaround for this it'll be declared here. There is no ETA - asking for an update just clutters this issue

**Comment by Hay127** [comment]
Nah Guys to solve this problem I use Smithing Table Fix 1.0, you can download it via bukkit

**Comment by TBYT** [comment]
> Nah Guys to solve this problem I use Smithing Table Fix 1.0, you can download it via bukkit
It was good for the time being, but unlike this user-experience-intrusive closed source plugin, I have developed a much more seamless fix in my 3rd party open source plugin Spigot found here. https://github.com/TBYT/GeyserParity/releases

**Comment by frogglen** [comment]
> > Nah Guys to solve this problem I use Smithing Table Fix 1.0, you can download it via bukkit
> 
> It was good for the time being, but unlike this user-experience-intrusive closed source plugin, I have developed a much more seamless fix in my 3rd party open source Spigot plugin found here. https://github.com/TBYT/GeyserParity/releases

Does this plugin replace the GeyserHacks plugin?

**Comment by Camotoy** [comment]
They are separate plugins.

**Comment by Chenyu550** [comment]
Haven't fixed it yet?

**Comment by Hay127** [comment]
> Haven't fixed it yet? It has been more than one month.

Just Update Your Server Version And Bug Will Be Fixed

**Comment by Konicai** [comment]
No, this issue hasn't been fixed. Please don't simply comment asking if its been fixing - we'll provide updates or close the issue if it is ever fixed.
