### ISSUE TITLE
Smithing table not work in bedrock client 1.20

### ISSUE THREAD

**Issue by raphaelfasilva** [GeyserMC/Geyser#3867]
### Describe the bug

After via version team fixed smithing table throgh of issue https://github.com/ViaVersion/ViaVersion/issues/3338 where was made remap to use old upgrade gear intead new upgrade gear,on java 1.20 client stayed ok smithing table are work but how i use geyser on bed rock client 1.20 not work not accept netherite on bottom square.

### To Reproduce

1 . started paper server 1.19.4
2 . log on the server
3. i put smithing table on the floor
4. i opened smithing table(upgrade gear on implementation)
5. i tried upgrade diamond pickaxe to netherite
6. i cant put netherite bottom square not accept

### Expected behaviour

expected upgrade diamond tools in netherite.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/1753391/5deb252c-5e01-4d27-bf1d-de04da2ed1a4)

### Server Version and Plugins

Paper version git-Paper-545 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bacbf86)

Server Plugins (36):
Paper Plugins:
 - Minepacks
Bukkit Plugins:
- AngelChest, BestTools, BottledExp, ChestShop, ChestSort, Chunky, ClearLag, CMI, CMILib, DoorsReloaded
Drop2Inventory, dynmap, FastAsyncWorldEdit, floodgate, Geyser-Spigot, GriefPrevention, LeafPlugins, LeafScore, LuckPerms, Multiverse-Core
nChat, nLogin, PlaceholderAPI, ProtocolLib, SimpleClans, SkinsRestorer, UltimateTimber, Vault, VeinMiner, ViaBackwards
 ViaVersion, VoidGen, Vulcan, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

https://dump.geysermc.org/KPn8LwDMEJ2ffZu4UwhhngXrePW02rJ7

### Geyser Version

2.1.1-SNAPSHOT (git-master-446d3c2) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)

### Minecraft: Bedrock Edition Device/Version

Bedrock 1.20 Windows 10 

### Additional Context

nothing

**Comment by FlorianMichael** [comment]
This issue is already known

**Comment by raphaelfasilva** [comment]
> This issue is already known
ok i opened because i not found nothing  opened issue about it.

**Comment by Hay127** [comment]
> This issue is already known

So If You Know What To Do For Bedrock?
