### ISSUE TITLE
Incorrect scoreboard display

### ISSUE THREAD

**Issue by chelminski** [GeyserMC/Geyser#3870]
### Describe the bug

The scoreboard is displayed correctly in the java version, but incorrectly in the bedrock version.

### To Reproduce

///Not applicable

### Expected behaviour

///Not applicable

### Screenshots / Videos

JAVA: 
![image](https://github.com/GeyserMC/Geyser/assets/62246121/85f692cc-f7a1-4d4d-9f65-baa44d828f58)

BEDROCK:
![image](https://github.com/GeyserMC/Geyser/assets/62246121/6162b935-814d-4aee-b4d7-e47f967d5b59)

### Server Version and Plugins

Server version: 1.19.4-R0.1-SNAPSHOT
Plugin version (bungee): Geyser 2.1.1-SNAPSHOT (git-master-bf5e084) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)
Bugee: 1.20 (fork - Flamecord 1.5.5)
ViaVersion: 4.7.0

### Geyser Version

Geyser 2.1.1-SNAPSHOT (git-master-bf5e084) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)

### Minecraft: Bedrock Edition Device/Version

Android, latest version (so lazy to check)

### Additional Context

Scoreboard plugin: [QuickBoard](https://www.spigotmc.org/resources/quickboard-free-scoreboard-plugin-scroller-changeable-text-placeholderapi-anti-flicker.15057/)

text:
  - '&a----------------------'
  - ''
  - '• &bNick: &a%player_name%'
  - '• &bRanga: &a%placeholder%'
  - '• &bStan Konta: &a%placeholder% zł'
  - '• &bRegion: &a%placeholder%'
  - '• &bID: &a%placeholder%'
  - ''
  - '&a----------------------'

**Comment by chelminski** [comment]
It's not visible, but there's a black dot here instead of a white one.
![image](https://github.com/GeyserMC/Geyser/assets/62246121/fd43fc1f-9758-4454-901e-ac933e174ca7)

**Comment by Redned235** [comment]
Bedrock limitation - can be fixed by a resource pack but nothing we can do in Geyser directly.
