### ISSUE TITLE
Bamboo and stalactite bugs

### ISSUE THREAD

**Issue by Wyverex84** [GeyserMC/Geyser#3871]
### Describe the bug

Bedrock players cannot walk through bamboo and stalactite

### To Reproduce

place two two block tall bamboos and try to run through

### Expected behaviour

that we can walk through bamboo and stalactite

### Server Version and Plugins

Server: Paper 1.20 

### Geyser Dump

https://dump.geysermc.org/owh2K0nBIrXeciqlddkIHmvVrJKQA7Rh

### Geyser Version

Build #1415 

### Minecraft: Bedrock Edition Device/Version

_Xbox Series X_

**Comment by Camotoy** [comment]
Please see https://github.com/GeyserMC/Hurricane. Thanks!
