### ISSUE TITLE
Bedrock player can't craft beds?

### ISSUE THREAD

**Issue by kazkid1** [GeyserMC/Geyser#3875]
### Describe the bug

Bedrock players in my paper server (1.19.3) are unable to craft beds

### To Reproduce

1. Player has 3 oak and 3 white wool in its inventory
2. Player tries to craft bed
3. Player can't 

### Expected behaviour

Player should be able to craft a bed

### Screenshots / Videos

![IMG_5240](https://github.com/GeyserMC/Geyser/assets/112659239/c5a044ca-e9a9-4d00-8ec0-7214516455bc)

### Server Version and Plugins

Paper version git-Paper-398 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8d1acf6)

Geyser
floodgate 

### Geyser Version

Geyser version 2.1.1-SNAPSHOT (git-master-8b8d6dd) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)

### Minecraft: Bedrock Edition Device/Version

Mobile ps4 ps5

**Comment by onebeastchris** [comment]
Please attach a Geyser dump by running "geyser dump" in your server console & sending the link here.

**Comment by Konicai** [comment]
Outdated Geyser: https://github.com/GeyserMC/Geyser/compare/8b8d6dd...master

wool items have since been fixed
