### ISSUE TITLE
Hope the JSON mappings of Custom items with Geyser can support the "model" type

### ISSUE THREAD

**Issue by RICE0707** [GeyserMC/Geyser#3876]
### What feature do you want to see added?

Hope the JSON mappings of Custom items with Geyser can support the "model" type.
![](https://cdn.discordapp.com/attachments/1066372573799120966/1118911266807873688/image.png)

In the Java material package, we can read the 3D model through this type,
But in Geyser's JSON mappings, we can't do that....

This causes the 3d model to display in geyser bedrock like this:
![](https://cdn.discordapp.com/attachments/1066372573799120966/1118909349767692288/image.png)

Whereas in Java it looks like this:
![](https://cdn.discordapp.com/attachments/1084466431124570132/1113509733039624283/image.png)

Hope to display 3d models like Java in Geyser bedrock too

### Are there any alternatives?

none

**Comment by Kas-tle** [comment]
Items on bedrock do not have associated models. You have to use attachables in the resource pack. There would be no use in allowing you to specify a model in the mappings.
