### ISSUE TITLE
Boats sink into the ground

### ISSUE THREAD

**Issue by ghostlyscythe** [GeyserMC/Geyser#3879]
### Describe the bug

Since updating to 1.20 bedrock players will sink through the floor when trying to ride a boat on a nether highway.

The boat is ontop of a Rail/Powered rail.
Iron bars on either side.
With ice below the rails.

This was working perfectly fine prior to 1.20 update.

### To Reproduce

See the video below to see an example

https://github.com/GeyserMC/Geyser/assets/46621990/13935e38-fefe-4166-8d69-0cb71616ae5c

### Expected behaviour

For the bedrock players to be able to boat smoothly along the ice.

### Server Version and Plugins

Current: git-Purpur-1990 (MC: 1.20)*
Previous: git-Purpur-1984 (MC: 1.19.4)
* You are running the latest version

### Geyser Dump

https://dump.geysermc.org/jPvWqSwEzKBLVT9EyanBeiDsxtmbwchZ

### Geyser Version

 Geyser version 2.1.1-SNAPSHOT

**Comment by ghostlyscythe** [comment]
update: also happens on just any normal land. you will glitch through the floor

**Comment by Jeenvries** [comment]
Same here.

**Comment by agoniaprivat** [comment]
Same here.

**Comment by shantek** [comment]
Also having this same issue breaking nether highway transport for bedrock players

**Comment by frogglen** [comment]
same issue here

**Comment by ifloppy** [comment]
Same issue here

**Comment by Konicai** [comment]
The issue is clearly reproducible and we know it happens. "me too" is not constructive and won't get this fixed any sooner
