### ISSUE TITLE
The water cauldron is not rendered correctly

### ISSUE THREAD

**Issue by EternalGhostcore** [GeyserMC/Geyser#3881]
### Describe the bug

Water cauldron are incorrectly rendered as non-glowing lava cauldron textures.

### To Reproduce

Put down the cauldron and fill it with water

### Expected behaviour

Render it correctly

### Screenshots / Videos

![Screenshot-12](https://github.com/GeyserMC/Geyser/assets/136816151/1a7da210-c9ea-4fc5-b518-6b59415a53dd)

### Server Version and Plugins

paper-1.20.1-22
plugin: floodgate

### Geyser Version

Geyser-Standalone build#1418

### Minecraft: Bedrock Edition Device/Version

1.20.0

**Comment by Konicai** [comment]
Client bug: https://bugs.mojang.com/browse/MCPE-170427

**Comment by onebeastchris** [comment]
https://bugs.mojang.com/browse/MCPE-170427
1.20.10 is out & the bug is fixed; closing
