### ISSUE TITLE
Music disc Relic played as wrong music in jukebox

### ISSUE THREAD

**Issue by EternalGhostcore** [GeyserMC/Geyser#3882]
### Describe the bug

Insert music disc Relic in the jukebox and it will play C418-wait

### To Reproduce

-

### Expected behaviour

Play music disc Relic correctly

### Screenshots / Videos

![Screenshot-13](https://github.com/GeyserMC/Geyser/assets/136816151/812226be-9779-4de4-9388-cad754534410)

### Server Version and Plugins

paper-1.20.1-22
plugin: floodgate

### Geyser Version

Geyser-Standalone build#1418

### Minecraft: Bedrock Edition Device/Version

1.20.0

**Comment by Konicai** [comment]
Are you 100% sure that the client version is 1.20? This should only be happening for 1.19.80 clients, especially if you're on build 1418
