### ISSUE TITLE
Essentials Mod Compatibility

### ISSUE THREAD

**Issue by ExplosiveGeek77** [GeyserMC/Geyser#3889]
### What feature do you want to see added?

I want to see if it would be possible for GeyserMC to work with the Essential Mod or the e4mc that allows you to open a lan world but so anyone can access it.

### Are there any alternatives?

I have attempted it by myself using the e4mc mod and GeyserMC to no avail but I will try test ot more, I believe without updates though it will not be possible.

**Comment by onebeastchris** [comment]
That would be up to those mods, not us.
Geyser-Fabric works on a client already, so you can set up and use Geyser there manually - as for opening/creating a tunnel, it is quite different from java, since Geyser
