### ISSUE TITLE
Simulation Distance?

### ISSUE THREAD

**Issue by TazAlonzo** [GeyserMC/Geyser#3890]
### Describe the bug

I think that if you have a lower simulation distance than your render distance, stuff like vines and bamboo don't render on bedrock.

### To Reproduce

1. Put simulation distance lower than render distance
2. Go further than simulation distance, but less than render distance
3. look at some bamboo or vines near the end of the render distance

### Expected behaviour

Vines and bamboo should render

### Screenshots / Videos

https://youtu.be/1xmrMxDCEoc

### Server Version and Plugins

This server is running Paper version git-Paper-19 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 837cc25)

### Geyser Dump

https://dump.geysermc.org/7sVPBtj3LzhuGFoIZwIpqbmNaLh6Y9af

### Geyser Version

2.1.1-SNAPSHOT (git-master-bf5e084)

### Minecraft: Bedrock Edition Device/Version

v1.20.0 Windows 10/11

**Comment by Redned235** [comment]
Simulation distance is not something the Bedrock client handles over the network. This is likely on the client itself.
