### ISSUE TITLE
Bedrock users can't get flowers but java users can

### ISSUE THREAD

**Issue by mas6y6** [GeyserMC/Geyser#3897]
### Describe the bug

When the bedrock user tries to get a flower but he doesn't get it and it goes back to its original area, but Java users can get the item and break it

### To Reproduce

1. Find a flower (On bedrock)
2. break it

### Expected behaviour

To get the the flower

### Geyser Version

2.2.1-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20.1 iOS

**Comment by Konicai** [comment]
Please share a geyser dump `/geyser dump`

also share a video if you're able

**Comment by Konicai** [comment]
My best guess is that this is some sort of spawn protection or plugin thing going on. Without any information about your server or a `/geyser dump`, this issue report isn't going to go anywhere.
