### ISSUE TITLE
Bedrock Users Can Place Wool Or Craft Anything Using Wool

### ISSUE THREAD

**Issue by myvtecgoesbwamm** [GeyserMC/Geyser#3902]
### Describe the bug

Hi, Wondering If Anyone Can Help? I Am Having An Issue With All Bedrock Players On Our Server NOT Being Able To Place Or Use Wool In Game? They Are Not Able To Make Beds Nothing.

 We Have Just Recently Updated To The 1.20.1 Server And Now Dyes And Glow Sacs (The Effect) Is Invisible To Bedrock Users. The Brush Also Shows As A Brush To Java But Shears To Bedrock Users? I Have Also Found This Issues Is Happening To Another Member Here In Discord. Just Wondering If There Is A Solution To This? I Have Contacted Essentials And Also Our Server Host Who Are Both Unable To Resolve This Issue. The Issue Only Occurred After Geyser Update, And Before We Even Progressed To Update Our Server To 1.20.1.
Any Information Would Be Gately Appreciated As Players Are Becoming Frustrated On The Server. Thank You For Your Time. 

We Are On Paper Thank You,

Vtec!

### To Reproduce

1. Bedrock Users Can't Place Wool
2, Bedrock Users Cant Craft Anything With  Wool
3. Glow Inc Sacks EFFECT Invisible To Bedrock Users
4. Dyes Also Invisible To Bedrock Users
5. All Hanging Signs Except Cherry & Bamboo Wood Signs Only Work
6. The New Brush Shows As A Shear Icon To Bedrock Users And Not The Brush We Have On Java.

### Expected behaviour

I Manually Reinstalled The New Geyser Update Hoping This Would Resolve The Issue. It Didn't Work. I Also Have Been In Touch With Essentials Which They Advised Me To Come To You. Just Hoping This Issue Can Be Resolved For Bedrock Users To Enjoy Their Time On The Server As Some Bedrock Users Will Now Await For Us To Have This Issue Fixed Before Returning To Us. 

### Server Version and Plugins

This Server Is Running Paper Version git-Paper-43 (MC: 1.20.1)
(Implementing API version 1.20.1-RO.1-SNAPSHOT) (Git: 3756f5b)
You Are Running The Latest Version

### Geyser Dump

https://dump.geysermc.org/epqpKJv4do7P8rxiz1pnbS62rkpSLefZ

### Geyser Version

(Implementing API version 1.20.1-RO.1-SNAPSHOT) (Git: 3756f5b)

### Minecraft: Bedrock Edition Device/Version

all bedrock users

### Additional Context

This is for all bedrock users even if they are on kindle, pocket, switch, PlayStation or bedrock for pc.

**Comment by myvtecgoesbwamm** [comment]
just updated to the new geyser and they can place carpet and that's all they are not able to even open the crafting table with wool in their hand or place wool. They are unable to even craft a bed as it says they are missing wool and they have a stack of planks and wool on them. 

Thank you

**Comment by onebeastchris** [comment]
Send a new geyser dump then.

**Comment by myvtecgoesbwamm** [comment]
sent in the ticket on discord

**Comment by DuneSciFye** [comment]
My bedrock players also unable to craft beds. Geyser Dump: https://dump.geysermc.org/SWob99GPKkpRCFWrG62DMLU8L5LTlyjn

**Comment by Camotoy** [comment]
@DuneSciFye you are using the very first Geyser build with 1.20 support. Please update.

**Comment by onebeastchris** [comment]
Additionally, looking at the Geyser dump - specifically,  plugins -, it appears that this server is behind a BungeeCord proxy. Please install and update Geyser there; and remove it from all other servers.
