### ISSUE TITLE
Server desync with hanging signs

### ISSUE THREAD

**Issue by Konicai** [GeyserMC/Geyser#3903]
### Describe the bug

as described

### To Reproduce

1. place a hanging sign and write to it
2. wax it
3. text disappears

### Expected behaviour

e

### Geyser Dump

https://dump.geysermc.org/qBvTtaqRYubNL73BeKTDtB5RSLa5Ddl2

### Geyser Version

e

### Minecraft: Bedrock Edition Device/Version

1.20

**Comment by VoidNX64** [comment]
I experienced this bug too yesterday and I can add some details about what I know about this bug:
- hanging signs placed by bedrock players are uneditable by java players even before it's waxed
- hanging signs with text added by bedrock players will appear with no text displayed to java players (I suppose this reinforces the fact waxing a hanging sign removes the text)
- if a hanging sign was placed by a java player (with text) and then edited by a bedrock player, said sign will be uneditable to java players although it will retain the text that was written by the java player
