### ISSUE TITLE
recipe book not working

### ISSUE THREAD

**Issue by juxt12** [GeyserMC/Geyser#3907]
### Describe the bug

Hello, on my server the recipe book doesn't work correctly in bedrock, activate the debug mode and this is the error I got when trying to use the recipe book:

### To Reproduce

Try to craft something using the recipe book

### Expected behaviour

the blocks go to the crafting table normally

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/114199783/ad10f209-1193-40bb-9171-160022319403)

https://github.com/GeyserMC/Geyser/assets/114199783/9bd82d72-dc30-4472-bf37-dd8ee7b89622

### Server Version and Plugins

 bStaffs, reconnect_yaml, LuckPerms, XProtect-Client, Geyser-Ignore, BungeePlugins, KauriVPN, AWD, CommandBlocker, Spicord, BungeeDirecto, BanAnnouncer, LiteBans, BuycraftX, cmd_send, ChatSentinel, ajQueue, floodgate, Protocolize, LibreLogin, SkinsRestorer, VulcanBungee, Maintenance, NuVotifier, BungeeGuard, cmd_list, Geyser-BungeeCord, AdvancedNMotd, cmd_find, FriendSystem, BungeePing, cmd_alert, MyCommand for BungeeCord

### Geyser Dump

https://dump.geysermc.org/wleubas4FaIeQtdBe1gR2v47yzw386Nd

### Geyser Version

2.1.1-SNAPSHOT (git-master-50d7f56)

**Comment by Konicai** [comment]
You can append new information to your old report.
