### ISSUE TITLE
BE players can't see ground particles such as lingering potion

### ISSUE THREAD

**Issue by jesusisao** [GeyserMC/Geyser#3909]
### Describe the bug

JE players can see the remaining partiles of the lingering potion on the ground, but BE players cannot.
Also, the lingering breath caused by the Ender Dragon's attack from above is similarly invisible.
However, BE players can see the breath the dragon produces when it descends to the ground.
Since the effect is effective despite being invisible, BE players will receive an invisible attack while fighting the Ender Dragon.

### To Reproduce

1. Throw a lingering potion as a BE player

### Expected behaviour

Particles can be seen on the ground

### Server Version and Plugins

Paper version git-Paper-524 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9846d0d)

- AntiPopup
- ColoredSigns
- CoreProtect
- FarmControl
- floodgate
- Geyser-Spigot
- GSit
- HorseTpWithMe
- LastLoginAPI
- LuckPer
- *LunaChat
- LWC
- Multiverse-Core
- Multiverse-Inventories
- Multiverse-NetherPortals
- Multiverse-Portal
- OpenInv
- ViaVersion
- VoidGen
- WorldBord
- WorldEdit
- WorldGuard
- Zabbigot

### Geyser Dump

https://dump.geysermc.org/tcRAuwiinf7cvlNEazQ3WdTLdDLwdzkn

### Geyser Version

2.1.1-SNAPSHOT (git-master-50d7f56) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)

### Minecraft: Bedrock Edition Device/Version

1.20.1 PC(Windows)

**Comment by Konicai** [comment]
Lingering Water Bottle, and Mundane/Thick/Awkward Lingering Potion, which have no effects, are translated correctly (no area affect cloud)

All the other lingering potions with effects don't have their area affect clouds shown
