### ISSUE TITLE
Second skin layer is not displayed

### ISSUE THREAD

**Issue by MrZillaGold** [GeyserMC/Geyser#391]
**Describe the bug**
After you connect to the server, ask any player to take a screenshot of you.
Your skin model will not have a second layer

**To Reproduce**
1. Connect to any server
2. Ask any player to take a screenshot with you

**Expected behavior**
The second layer of your skin will be visible to all players, usually the client sends the server information about the state of the layers on the skin, as this changes on the client in the settings

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/42776347/79757481-7f5aa480-835f-11ea-9a6e-0fb50cd7e3ba.png)

**Server Version**
1.15.2 (Hypixel)

**Geyser Version**
latest

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by lukeeey** [comment]
I’m pretty sure java doesn’t have any concept of skin layers

**Comment by DoctorMacc** [comment]
Is this referring to Java skins - > Java or Java skins -> Bedrock? Java-to-Java skins should not be messed with.

**Comment by rtm516** [comment]
Java to java, its because the server relies on the client to send over the skin preferences displaying each part of the second layer.
https://discordapp.com/channels/613163671870242838/613169749525790737/701783639649681409

**Comment by Tim203** [comment]
Java does have the concept of skin layers. They have the normal layer and the top layer. The top layer can be transparent but the normal layer cannot.

**Comment by rtm516** [comment]
Looks like this just needs to be implemented: https://wiki.vg/Protocol#Client_Settings

**Comment by Tim203** [comment]
Yes
