### ISSUE TITLE
Folia server uses geyser-spigot plugin,Bedrock players can't play normally.

### ISSUE THREAD

**Issue by haoge114** [GeyserMC/Geyser#3920]
### Describe the bug

I use geyser-spigot plugin in the latest version of folia server in 1.20, and the entry of bedrock version will be delayed greatly, so I can't play games normally.You can't do anything when you enter the server, and the mining block can't be mined normally.(Only use floodgate and viaversion plugin)

### To Reproduce

1.Put it in the plugin folder of folia server.
2.Access the server using the bedrock version of Minecraft

### Expected behaviour

Entering the server will be very stuck, which is a very obvious delay.

### Geyser Version

spigot

**Comment by onebeastchris** [comment]
Please attach a Geyser dump, server version by running "/version", and the bedrock client version one can replicate this with.

**Comment by haoge114** [comment]
https://dump.geysermc.org/o3GsgmsfyI89v3STXHySM0xg6ywzr99g And version screenshots (I can't even dig a piece of wood)

**Comment by haoge114** [comment]
The screenshot may have failed to upload? I use the latest geyser-spigot [19:50:50 INFO]: This server is running Geyser version 2.1.1-SNAPSHOT (git-master-c7304f0) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0),I use 1.20.0.01 bedrock version, but as far as I know, the official version of 1.20 should be able to trigger this bug.

**Comment by haoge114** [comment]
I don't use github, and I don't know how to upload screenshots. After all, my English is really poor.

**Comment by LsrlYrsc** [comment]
> The screenshot may have failed to upload? I use the latest geyser-spigot [19:50:50 INFO]: This server is running Geyser version 2.1.1-SNAPSHOT (git-master-c7304f0) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0),I use 1.20.0.01 bedrock version, but as far as I know, the official version of 1.20 should be able to trigger this bug.

I help him to upload image
![IMG_6706](https://github.com/GeyserMC/Geyser/assets/111047831/062fb156-759a-43ba-aedb-ef7b16777f1e)

**Comment by onebeastchris** [comment]
Just wondering; but does the issue occur without "BlockLocker" installed?

**Comment by Camotoy** [comment]
This may partially be because we don't have an Adapters version for 1.20, so any block action will have more delays.

**Comment by Konicai** [comment]
Spigot adapter for 1.20 is available on the latest geyser build.

**Comment by haoge114** [comment]
Yes, this bug is still triggered without BlockLocker(It's just a plug-n to lock the chest).So now I can only use 1.19.80 to play normally?

**Comment by haoge114** [comment]
Geyser-Standalone can support folia, But there are always some small bugs, For example, if you re-enter the game after losing your key, you still can't talk, you can't display your skin. (Does this bug still exist? ).

**Comment by haoge114** [comment]
I tested it in the new spigot version, and there is really no such jam. The current jam should be the problem of the bedrock version itself(Of course, I can't promise.).

**Comment by Konicai** [comment]
jam?

**Comment by Kas-tle** [comment]
This issue does not have a specific problem identified or reproduction steps. If you are still experiencing a specific issue with Folia, please open a new issue and provide specific reproduction steps.
