### ISSUE TITLE
[Bug]Players will get stuck in the void and get disconnected after entering the server for a while

### ISSUE THREAD

**Issue by addpromax** [GeyserMC/Geyser#3926]
### Describe the bug

Players will get stuck in the void and get disconnected after entering the server for a while

### To Reproduce

1.Join Bungee server
2.Wait 1-3min
3.stuck in the void
4.disconnected server

### Expected behaviour

1.Not disconnected server

### Server Version and Plugins

Bungee

### Geyser Dump

https://dump.geysermc.org/lf4Ow0F7u3sEa5EF41s59t5pTELY9QJ5

### Geyser Version

2.1.1-SNAPSHOT (git-master-4077514)

### Minecraft: Bedrock Edition Device/Version

1.20.1 Windows 10

**Comment by onebeastchris** [comment]
#2861 likely duplicate of this issue. Please try the fix there - either the temporary workaround, or better, by updating Java to a version with a fix for that bug (as mentioned in the linked issue).

Furthermore, i would advise against using that many java flags unless you know what exactly you're doing - i've seen instances of them causing more harm than good.

**Comment by onebeastchris** [comment]
Closing as duplicate of #2861.
