### ISSUE TITLE
CustomCrafting plugin breaks vanilla recipes

### ISSUE THREAD

**Issue by ErikK81** [GeyserMC/Geyser#3927]
### Describe the bug

The bug started after the 1.19.4 update on server. Its as something with custom crafting, after delete cc, some crafts started working like the stone pickaxe.

### To Reproduce

1. After download the latest geyser version
2. And the latest CustomCrafting version
3. Just try to Craft something, like beds, stone tools or some custom crafting craft.

### Expected behaviour

Justo dont appear the result

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/119763939/fe393cdb-61c5-4b3f-ae19-6f98af68afad)

### Server Version and Plugins

Current: git-Purpur-1985 (MC: 1.19.4)*
Previous: git-Purpur-1858 (MC: 1.19.2)

### Geyser Dump

https://dump.geysermc.org/fxi9SLf8QVY3gvKGZDW5GDkrhx0lzxWD

### Geyser Version

This server is running Geyser version 2.1.1-SNAPSHOT (git-master-4077514) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)

### Minecraft: Bedrock Edition Device/Version

Any version.

**Comment by onebeastchris** [comment]
Is this issue still occurring with the latest version of Geyser? If yes, could you provide further replication steps with e.g. configs for the plugin needed to replicate the issue? Thanks :)

**Comment by onebeastchris** [comment]
Closing due to no response. Using CustomCrafting on 1.20.1 worked fine for me - both built-in recipes and newly added ones
