### ISSUE TITLE
Bug with Gsit plugin

### ISSUE THREAD

**Issue by DustyTech4** [GeyserMC/Geyser#3928]
### Describe the bug

this message (action.hint.exit.scheme.armor_stand) shows up when a player does /sit or /lay, the server uses the Gsit plugin, the message only shows up for a few seconds before fading.
furthermore; when i asked on the Gplugins discord they blamed geyser

### To Reproduce

 on bedrock do /sit
the server must be using the GSIT plugin

### Expected behaviour

a message that reads " Use your Sneak Key to ger up" 

### Screenshots / Videos

![Screenshot_20230629-091658](https://github.com/GeyserMC/Geyser/assets/120058519/f531c161-ce2a-4ec8-abc3-b420cac39134)
![image](https://github.com/GeyserMC/Geyser/assets/120058519/9cde4ef1-c6ef-4e37-b232-e4d11c4e91ae)

### Server Version and Plugins

current version: git-Purpur-2004 (MC: 1.20.1)*

plugins:
Gsit, floodgate and geyser

### Geyser Dump

https://dump.geysermc.org/zAb5hJi46xTh1Nu98LbxypTQwFZgWDBI

### Geyser Version

 2.1.1-SNAPSHOT (git-master-4077514) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)

### Minecraft: Bedrock Edition Device/Version

mobile and Minecraft for windows 

### Additional Context

for java players: 

https://github.com/GeyserMC/Geyser/assets/120058519/685b7edf-220e-44f7-977c-5870f157b347

**Comment by onebeastchris** [comment]
Seems like this is included here https://github.com/GeyserMC/Geyser/issues/2180 - this doesnt seem easily fixable (unless something has changed). Ill close this as duplicate, thanks for the detailed report :)

**Comment by paulinochawan-cmd** [comment]
Eu apoio Nick chawanp
