### ISSUE TITLE
Authentication servers are down

### ISSUE THREAD

**Issue by CrayCrayCreations** [GeyserMC/Geyser#3935]
### Describe the bug

When I try to join my Geyser-Spigot equipped server on Java, I get the error “Authentication servers are down. Please try again later, sorry!” I’ve had this same error for a couple of weeks and I don’t know what’s causing it. It’s only on my Geyser server too. Sorry if this is on my end or Mojang’s end. I do have a “Could no pass event ServerLoadEvent to Geyser-Spigot v2.1.1-snapshot…”

### To Reproduce

I don’t know specifically what I did, my geyser wasn’t working at all, and once I fixed it, i got this error. I can send a copy of the config file text

### Expected behaviour

I was expecting be to just be able to log in and play

### Geyser Dump

When i ran, it crashed my server

### Geyser Version

V2.1.1 for Java 1.18.2 with an outdated spigot

**Comment by rtm516** [comment]
This is not a Geyser issue, it will be caused by your server being unable to contact the Mojang Authentication servers.
