### ISSUE TITLE
GeyserMC players seeing java players frozen

### ISSUE THREAD

**Issue by MrOrtho** [GeyserMC/Geyser#3936]
### Describe the bug

Bedrock players can only see a frozen version of a java player when the java player respawns.
Then the bedrock player can hit the java player in the position he is stuck in to the bedrock player. The only solution is going into spectator and adventure

### To Reproduce

Kill Java Player
Teleport java player to bedrock player
If the java player is stuck their armour won't show 
Java players moves around
bedrock player hits frozen player

### Expected behaviour

We set up a PVP ring and both players get teleported. We were expecting both players to teleport without any issues

### Screenshots / Videos

Cannot upload video as its too big, but here is a screen shot
![image](https://github.com/GeyserMC/Geyser/assets/118650585/45ceef20-2c3e-4de3-aabd-155132eb2c4f)
I wasnt standing or crouching in the place and i had iron armour on
![image](https://github.com/GeyserMC/Geyser/assets/118650585/2f8be792-417a-4e7e-bc51-bca77cab7998)
he wasnt using a sword 

### Server Version and Plugins

It says i am running latest, but ill list everything.

git-paper-62 MC 1.20.1 1.20.1 R0.1 SNAPSHOT  GIT 4356758

PLUGINS:
floodgate
geyser-spigot
viaversion
worldedit

### Geyser Dump

https://dump.geysermc.org/tMxtoErB3fVWPl3DlUxqxbm3uSSnGGOV

### Geyser Version

2.1.2-SNAPSHOT git 30410f9

### Minecraft: Bedrock Edition Device/Version

1.19.81-1.20.1 xbox

**Comment by onebeastchris** [comment]
1.20.10/1.20.11 (depending on platform) potentially brought a fix to this. Could you update Geyser & your game and re-test if this issue still occurs?

**Comment by MrOrtho** [comment]
> 

After updating and restarting I can confirm it still is bugged but armor and correct tools are fixed. It has happened less and the new freezing might be from lag.

**Comment by MrOrtho** [comment]
Actually confirmed it was other issues. The update with 1.20.11 did fix it. Thank you
