### ISSUE TITLE
Missing server-icon and incorrect Server Version

### ISSUE THREAD

**Issue by GR3YH4TT3R93** [GeyserMC/Geyser#3939]
### Describe the bug

I'm currently on the latest Geyser (1444) and Purpur (1.20.1, build 2006) and when checking server data via mc server checker, the Java port correctly reports the server icon and server version but when checking the Bedrock port it shows the server as 1.20 and doesn't show the server icon

### To Reproduce

Place 64x64 server-icon.png into root directory of server

Restart server

Go to mcserverstatus.com

Check server URL or IP (preferably URL)

Tap "Get Data of Bedrock version of this Server"

Result: no icon and server version reports as 1.20.0

### Expected behaviour

Bedrock and Java data to report the same things i.e. both Icon properly showing and server version reporting the correct version (1.20.1) on both ports 25565 and 19132.

### Screenshots / Videos

![Screenshot_2023-07-05-01-09-14-71_3aea4af51f236e4932235fdada7d1643](https://github.com/GeyserMC/Geyser/assets/76727386/e6e387ee-ffb8-48e1-b8b1-ccf065e04201)
![Screenshot_2023-07-05-01-09-42-47_3aea4af51f236e4932235fdada7d1643](https://github.com/GeyserMC/Geyser/assets/76727386/2e50ce55-94be-402d-a677-0a09a8f78427)

### Server Version and Plugins

Version: git-Purpur-2006 (MC: 1.20.1)*

Plugins: AdvancedTeleport, *AlwaysOnline, AureliumSkills, AutoPickup, AutoTotem, BackpackPlus, BetterLogStrip, BetterStructures, ChestSort, CraftableTridents, CraftBook, DiscordSRV, DoorsReloaded, DynamicLights, EliteMobs, eShulker, Essentials, EssentialsSpawn, floodgate, Geyser-Spigot, GeyserHacks, Graves, HorseChestSaddle, InvUnload, *KeepEnchant, LibsDisguises, Lootin, LuckPerms, Mine_X_Farm_Regen, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, MyDog, PerWorldPlugins, PlaceholderAPI, ProtocolLib, PurpurExtras, spark, TerraformGenerator, TreeFeller, UltimateFood, Vault, VeinMiner, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/cD9SBv6pptsVybzCdUOWYN20R8NTajvN

### Geyser Version

2.1.2-SNAPSHOT (git-master-0e3e2d0) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)

**Comment by onebeastchris** [comment]
1. Bedrock has no support for server icons; hence why it's not shown.
2. you can stop versions from being displayed - or anything motd related - in Geysers config; e.g. the passthrough of motd, player counts, or protocol version.
