### ISSUE TITLE
BE version players can't create the recipe even if they have the materials for the hanging sign.

### ISSUE THREAD

**Issue by rororororo5** [GeyserMC/Geyser#3944]
### Describe the bug

BE version players can't create the recipe even if they have the materials for the hanging sign.

### To Reproduce

1. Assemble materials for hanging signs.
2. Open the workbench.
3. I can't find the crafting recipe anywhere.

### Expected behaviour

Once you have the ingredients, the recipe will be unlocked for you to create.

### Server Version and Plugins

This server is running Paper version git-Paper-62 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 4356758)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-58 (MC: 1.20.1)

### Geyser Version

#1441

### Minecraft: Bedrock Edition Device/Version

1.20.1

**Comment by onebeastchris** [comment]
Please send a Geyser dump by running "geyser dump" in the console & sending the link you get here

**Comment by rororororo5** [comment]
https://dump.geysermc.org/figCB0UKObxbkJRoEoKfeABKeHMyhDnq

**Comment by TimDegraaf** [comment]
Are you using 6 bamboo strip logs and two chains?

**Comment by rororororo5** [comment]
yes

**Comment by onebeastchris** [comment]
Interesting. From my testing (1.20.1 paper, latest geyser version) i can easily craft all hanging signs, but they are not shown in the recipe list.

**Comment by SonnenPingu** [comment]
Crafting works, but the bedrock players are so spoiled, if it's not in the recipe list, it doesn't exist.

In fact, I can confirm the whole thing 

Crafting works, but no matter if you have crafted it or not, it does not appear in the recipe list.

**Comment by onebeastchris** [comment]
Can confirm the bug, I'll include the fix in #4016. Thanks for the bug report!
