### ISSUE TITLE
/playsound not working after Build #1445

### ISSUE THREAD

**Issue by kolderz** [GeyserMC/Geyser#3953]
### Describe the bug

The command does not play any sound for Bedrock Client

### To Reproduce

1. Use /playsound on Bedrock Client
Example: /playsound minecraft:entity.blaze.hurt player <player.name>

### Expected behaviour

Play the sound for Bedrock player

### Server Version and Plugins

git-Purpur-1632-1.18.2

### Geyser Version

Geyser version 2.1.2-SNAPSHOT (git-master-872d7e3) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)

### Minecraft: Bedrock Edition Device/Version

1.20 IOs 16

**Comment by onebeastchris** [comment]
uff, did not think that this would break.. makes little to no sense.
Does it work without specifying "minecraft:" in front? just curious

**Comment by rtm516** [comment]
https://github.com/GeyserMC/Geyser/pull/3947

**Comment by onebeastchris** [comment]
That's a known issue; and unrelated to this PR

**Comment by mozileyu** [comment]
I also found this bug and made me can't upgrade game version to 1.20.10, because the /playsound was work well on my server before Build #1445

**Comment by onebeastchris** [comment]
It looks like you're trying to play a custom sound, but you didn't specify its identifier?
minecraft:rpg.palace would imply it's a minecraft sound due to the "minecraft:" namespace. Custom sounds should have a custom namespace - or does java work without the namespace?

**Comment by mozileyu** [comment]
> 

yes, java work well without the namespace

**Comment by onebeastchris** [comment]
Would you mind linking the plugin/resource pack you're using for custom sounds?
I was under the impression that custom sounds should always be played with an identifier (unlike Minecraft sounds), to eliminate name clashes.

**Comment by onebeastchris** [comment]
@mozileyu Nevermind the plugin/resource pack; mind testing the PR again? Made some changes which should allow for custom sounds without namespaces.
Btw; those are a bad idea, since if another plugin/resource pack does the same, your sounds will clash - hence why you should include a namespace.

**Comment by mozileyu** [comment]
#3956 I tried it just now, and the method of playing sound has been restored to the way it was before #1445. When using the command /playsound to play music, it can be played normally without "minecraft:" THANK YOU A LOT!
