### ISSUE TITLE
Geyser Spigot is stopping the server

### ISSUE THREAD

**Issue by SerSquirt** [GeyserMC/Geyser#3954]
### Describe the bug

Hello! Whenever I use Geyser and Floodgate on my server, the server will stop about every 2-5 minutes. This only happens for me when Geyser is in the plugins folder, and when I remove it this does not happen. Removing floodgate does not solve the problem either. This also happens even if no bedrock players are connected to the server, and it even does this when geyser and floodgate are the only plugins on the server.

### To Reproduce

1. Start the server with Geyser enabled
2. Wait a few minutes
3. The server stops

### Expected behaviour

I expected the server to only stop when i run /stop.

### Server Version and Plugins

Version:
This server is running Paper version git-Paper-67 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: e105354)
Previous version: git-Paper-64 (MC: 1.20.1)

Plugins:
EssentialsX 2.20.1
EssentialsXDiscord 2.20.1
EssentialsX 2.20.1
LuckPerms 5.4.84
ProtocolLib
SuperVanish
ViaVersion 4.7.0
ViaBackwards 4.7.0
InvSee++

### Geyser Dump

https://dump.geysermc.org/UJel5mtVqjtbwnFpZpIfYCMQq18Tu3YX

### Geyser Version

2.1.2-SNAPSHOT (git-master-872d7e3)

### Additional Context

I've checked the server, and nothing else should be making the server stop like this. It's not scheduled to restart in any way.

**Comment by onebeastchris** [comment]
Geyser does not have any capability to stop your server - is there anything in your logs/crash logs?

**Comment by SerSquirt** [comment]
Everytime it happens, the server console will say 
```
[Server thread/INFO]: Stopping the server
[Server thread/INFO]: Stopping server
```
and the server stops. This makes it seem like something's running the /stop command, but it only happens when Geyser is enabled, and it even happens when it's the only plugin enabled on the server. And there are no crash reports from when this happens.

**Comment by onebeastchris** [comment]
Are you using a server hosting provider? If so, that is likely their doing.. Geyser literally does not have anything built in to stop a server..
Also, mind sending a full log via mclo.gs?

**Comment by SerSquirt** [comment]
Here's a mclo.gs link: https://mclo.gs/UypXruH One thing I noticed when looking at the log is that the error from line 158 to line 174 doesn't appear when Geyser is disabled.
The server that it's running on is an Ubuntu server from Linode that I have full control of, so it's not likely to be stopping the server.  The server is also being run with [LinuxGSM](https://linuxgsm.com/), so maybe it's stopping the server, since GS4 is unable to initialize when Geyser is using the port?

**Comment by Konicai** [comment]
In most cases I've seen, when the GS4 Query listener fails to start because of Geyser, nothing else happens as a result. But I would still try to avoid it.

If you have full control over the node then you can probably run Geyser on 19132 (default bedrock port)?
If you still want or need to run Geyser on 25565, then I would recommend disabling query in server.properties. On modern servers query doesn't need to be enabled for server pinging to work.

**Comment by SerSquirt** [comment]
Apparently LinuxGSM uses GS4 to monitor the server, and it stopped the server when it wasn't able to monitor the server. Disabling the monitor cron job fixed the issue. Thanks for the help!
