### ISSUE TITLE
Geyser fabric server and BD-only packs 

### ISSUE THREAD

**Issue by ChosenMoren** [GeyserMC/Geyser#3959]
### What feature do you want to see added?

Do a Geyser-Server conflit somehow with a bedrock player logging with behavior packs?

### Are there any alternatives?

Maybe don't using the named packs

**Comment by onebeastchris** [comment]
No, it wouldnt. A bedrock client could at most have resource packs active, not addons/datapacks; those would be on the server.

**Comment by ChosenMoren** [comment]
Oh, ok. So things like BetterFoliage behavior pack for BD that's add falling leaves and 3d models don't work at all or work somehow?
