### ISSUE TITLE
Sitting on moss carpets broken with Gsit

### ISSUE THREAD

**Issue by IceWaffles** [GeyserMC/Geyser#3960]
### Describe the bug

When you sit on a moss carpet, you can't see anything. Please see the below screenshot on what it looks like.

### To Reproduce

1. Download both Geyser and Floodgate on latest build of Paper/Purpur 1.20.1
2. Download and install the plugin Gsit
3. Log on with Bedrock (I tested on mobile, iOS) and sit on a moss carpet

### Expected behaviour

For it to look normal/be able to see everything, as if you sat on a normal block

### Screenshots / Videos

![IMG_1092](https://github.com/GeyserMC/Geyser/assets/86599175/beb21ad9-ebcf-4a46-9440-0eb9b293bb8f)

### Server Version and Plugins

git-Purpur-2010 (MC: 1.20.1)*

Plugins: Geyser-Spigot, Floodgate, Gsit

### Geyser Version

This server is running Geyser version 2.1.2-SNAPSHOT (git-master-d1357df) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)

### Minecraft: Bedrock Edition Device/Version

Latest available (should be 1.20), on iOS 16

**Comment by onebeastchris** [comment]
Unable to replicate - is this still occurring?
