### ISSUE TITLE
Bedrock 1.20.10 fails with Outdated Geyser proxy error

### ISSUE THREAD

**Issue by RedRam567** [GeyserMC/Geyser#3963]
### Describe the bug

Bedrock 1.20.10 fails to connect to Java 1.20.1 server. It was working yesterday (July 10th 2023) on the previous version of Bedrock: 1.20.1 on Android and on Xbox Series X + BedrockTogether.

### To Reproduce

1. Update Android phone to Bedrock 1.20.10
2. Start java dedicated server 1.20.1
3. Start Geyser standalone version 2.1.2-SNAPSHOT (git-master-6296d4a)
4. Connect from Bedrock with direct connect
5. Fails with the error: "Outdated Geyser proxy! This server supports the following Bedrock versions: 1.19.80/1.19.81, 1.20.0"

Note: Also fails in the same way on Xbox Series X Bedrock 1.20.11 + BedrockTogether

### Expected behaviour

I expected to connect straight into the game with no issues. Which happened just before I updated my Android.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/449335447038984202/1128469335892037664/Screenshot_20230711_163358_Minecraft.jpg

### Server Version and Plugins

I do not know what you mean by "/version". "/version" and "version" does not work Geyser console, Server console or in game in java, and I cant join the server on Bedrock

- Java dedicated server 1.20.1 Docker image  based off of this https://github.com/itzg/docker-minecraft-server/blob/master/examples/docker-compose-modrinth.yml
- Fabric latest (idk version, its handled by docker)
- [1.20.1] Fabric API 0.85.0+1.20.1
- Lithium 0.11.2
- Some command-only data packs

### Geyser Dump

https://dump.geysermc.org/h4MJVGuwGhai8NE76EHHfop1uc0GDd5x

### Geyser Version

Geyser version 2.1.2-SNAPSHOT (git-master-6296d4a)

### Minecraft: Bedrock Edition Device/Version

Android 1.20.10, Xbox Series X 1.20.11

### Additional Context

1.20.11 on the Xbox seems to be typo by Mojang.
They say this on https://feedback.minecraft.net/hc/en-us/articles/17381681401357-Minecraft-1-20-10-Bedrock-
> NOTE: This update will appear as version 1.20.11 on Xbox

This is my first issue on GitHub so please be kind.

**Comment by Camotoy** [comment]
Update Geyser. We just released 1.20.10/1.20.11 Bedrock support.

**Comment by RedRam567** [comment]
Must've just missed it because I just reinstalled from the Arch aur AND compiled from source.

**Comment by Konicai** [comment]
Please just download it from our downloads webpage https://geysermc.org/download

**Comment by Camotoy** [comment]
...What do you mean, reinstalled from the Arch AUR? Is there a Geyser package on there?

**Comment by RedRam567** [comment]
Yeah its here: https://aur.archlinux.org/packages?O=0&K=geysermc-bin
I installed with `yay -S geysermc-bin`

**Comment by RedRam567** [comment]
Yeah I had the worst timing :p. You guys just updated as I was writing the issue. Reinstalling from Arch AUR or recompiling right now gives Geyser version 2.1.2-SNAPSHOT (git-master-6296d4a)
I'll make sure to recompile and retest just before submitting issues next time.
Also thank you for the speedy update.

**Comment by Camotoy** [comment]
Good to hear. Just note we don't maintain that package, so use it at your own risk.
