### ISSUE TITLE
Xbox cplayers can fly out side of claim 

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#3967]
### Describe the bug

i use a plugin called lands to claim land, i give a certain parent group the perms to fly within their claim and if the fly out side of their claim the lands plugin would ground them after 5 seconds. this isnt the case with Xbox players. they can keep flying and they dont get the warning that they have flied outside their claim

### To Reproduce

activate fly in claim
fly out side of claim

### Expected behaviour

they can fly anywhere with out being detected 

### Server Version and Plugins

proxy/bungeecord
back end 1 Current: git-Purpur-2008 (MC: 1.20.1)
back end 2 This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)

### Geyser Dump

https://dump.geysermc.org/qO4CclOpVEOYk485EEIRPfdQhcsfFfXR

### Geyser Version

3a0c1b7

### Minecraft: Bedrock Edition Device/Version

xbox 1.20.11

**Comment by onebeastchris** [comment]
That sounds like a plugin issue, not necessarily Geyser related..
Did it not occur before, and are java players affected?

**Comment by shawn695** [comment]
i trouble shooted with ApexHosting and it was determined its the new geyser update

**Comment by shawn695** [comment]
and no it did not happen before all players would get grounded if they flew out side their claim, but after this new update yesterday only xbox players can fly out side their claim with out getting a warning from the Lands plugin saying the have flown out, everyone else i tested on get grounded after 5 seconds flying outside of claim tested on pc bedrock works as expected, tested on mobile bedrock and works as expected. tested on 4 different xbox accounts doesnt work as expected

**Comment by shawn695** [comment]
that happen to me last night when i ran geyser dump on my proxy. restarted the server it didnt happen again but my issue im reporting is about the Xbox players flying

**Comment by shawn695** [comment]
with newest geyser update build #237 , xbox players can still fly outside their claims, how ever java and mobile and bedrock windows they get grounded flying outside of claim. (as expected)

**Comment by shawn695** [comment]
testing this bug with current build #238, bedrock players can still fly out side of claims, also in mini games that allow double jump will activate fly. this only happens with bedrock players. java players get grounded flying out side of claim and the dont activate fly while double jumping in minigames

**Comment by shawn695** [comment]
Confirmed, new update fixed issue. thank you !
