### ISSUE TITLE
Containers do not show up.

### ISSUE THREAD

**Issue by ItzCookies** [GeyserMC/Geyser#397]
**Describe the bug**
Chests/containers show as invisible blocks.

**To Reproduce**
Chests do not show up. Just place a chest in Java, join Geyser (inventory branch) and it will not show up (it shows invisible.)

**Expected behavior**
Containers should show up correctly.

**Screenshots / Videos**
Not required.

**Server Version**
 git-Paper-185 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
Tried inventory and master branch.

**Minecraft: Bedrock Edition Version**
v1.14.60
**Additional Context**
N.A

**Comment by RednedEpic** [comment]
Please make sure you are using the inventory branch as this is not a problem there.

**Comment by ItzCookies** [comment]
> 
> 
> Please make sure you are using the inventory branch as this is not a problem there.

I have already mentioned. "Tried inventory and master branch."

**Comment by DoctorMacc** [comment]
I am unable to replicate with Paper 184. Are you using any plugins that could interfere?

**Comment by ItzCookies** [comment]
Whoops sorry - it's working now. Sorry for wasting your time and thanks for taking the time to reply :)
