### ISSUE TITLE
Update to 1.20.11

### ISSUE THREAD

**Issue by MelonManssss** [GeyserMC/Geyser#3971]
### What feature do you want to see added?

As of now bedrock players cannot not use this or join cross play servers so please update to 1.20.11

### Are there any alternatives?

No

**Comment by Konicai** [comment]
1.20.11 is the same protocol version as 1.20.10 - they are compatible. And we already support 1.20.10. Please update

**Comment by onebeastchris** [comment]
Already done yesterday; 1.20.10 and 1.20.11 are identical
