### ISSUE TITLE
Cannot encode SNIFFING flag

### ISSUE THREAD

**Issue by ItzFlipp** [GeyserMC/Geyser#3972]
### Describe the bug

Hello! Every few minutes, an NPE is generated. The following are the two exceptions that I notice every few minutes:

https://mclo.gs/EI7oadH

### To Reproduce

Not sure. It happens every few minutes.

### Expected behaviour

No exceptions should occur.

### Server Version and Plugins

Bungee: git:Travertine-Bootstrap:1.16-R0.5-SNAPSHOT:a24c106:158
Spigot: git-Purpur-2005 (MC: 1.20.1)

### Geyser Dump

https://dump.geysermc.org/DQCaAQXnUWG6GjjmRKAo3eBaltJRxEV8

### Geyser Version

2.1.2-SNAPSHOT (git-master-3a0c1b7)

### Minecraft: Bedrock Edition Device/Version

1.20.10

**Comment by BufalinoSD** [comment]
Same

**Comment by Konicai** [comment]
Please make separate bug reports for separate issues

**Comment by onebeastchris** [comment]
the setscore packet thing is already here:
https://github.com/GeyserMC/Geyser/issues/3934
