### ISSUE TITLE
proxy erroring !

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#3973]
### Describe the bug

updated server to newest build and proxy is puking 

### To Reproduce

use new geyser build 236

### Expected behaviour

consol puke 

### Geyser Dump

https://dump.geysermc.org/vPcfUnxr5tSInHzMCdphQBTl9maorUKh

### Geyser Version

geyser bungee cord build 236

**Comment by Konicai** [comment]
Logs please. https://mclo.gs

**Comment by shawn695** [comment]
[proxy.log.zip](https://github.com/GeyserMC/Geyser/files/12033155/proxy.log.zip)

**Comment by shawn695** [comment]
their we go, more updated version got it to happen again https://mclo.gs/ImHJhTo

**Comment by Konicai** [comment]
Fixed in c1d8009b4066c8e09b1b1e42ff7d61e0af8b9898
