### ISSUE TITLE
Shulker Xray bug

### ISSUE THREAD

**Issue by DarkChromaMC** [GeyserMC/Geyser#3979]
### Describe the bug

When a shulker is positioned between the player and a lava source at the same level, opening and closing the shulker results in a brief period where entities can be seen through the lava.

### To Reproduce

Open and close a shulker and look between the space (allows viewing caves and ores).

### Expected behaviour

Player can not Xray.

### Geyser Version

2.1.2-SNAPSHOT (git-master-c1d8009) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

**Comment by onebeastchris** [comment]
![image](https://github.com/GeyserMC/Geyser/assets/105284508/da899af2-6f36-4cb4-b6a1-c34164f5c268)
I can replicate this with a singleplayer Bedrock world, therefore, i would recommend opening a bug report on the Bedrock issue tracker https://bugs.mojang.com/projects/MCPE/summary :)

**Comment by Camotoy** [comment]
I can't imagine there's anything we can do to mitigate this; this is out of our scope. Thanks for reporting anyway!
