### ISSUE TITLE
Unable to render chunks with campfires

### ISSUE THREAD

**Issue by haappi** [GeyserMC/Geyser#3985]
### Describe the bug

Having campfires/soul campfires (both lit and unlit) results in `[geyser]: Could not translate packet ClientboundLevelChunkWithLightPacket`

### To Reproduce

1. Set up a MineStom server
2. Make a map with both lit and unlit campfires
3. Load the MineStom server and have Velocity as a frontend
4. Observe the CampfireBlockEntityTranslator issue.

### Expected behaviour

World should load with no errors

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/74637670/86ac79c0-5fbe-4357-9853-639d801fdd9e)
Left = Java
Right = Bedrock

![image](https://github.com/GeyserMC/Geyser/assets/74637670/d953eaf1-3541-44fe-98ea-00ae89f71a90)
More chunks with campfires are unable to load.

### Server Version and Plugins

MineStom implementation
> velocity plugins
[20:02:49 INFO]: Plugins: duck-velocity, floodgate, geyser, viaversion, viabackwards

Note: duck-velocity is a plugin to handle Discord messaging via an API, it does not touch floodgate or GeyserMC

### Geyser Dump

https://dump.geysermc.org/KrV1nV1W8IgHghRtXWeK0NDVsvvEWDuX

### Velocity Logs
https://mclo.gs/cfn5ptg

### Geyser Version

2.1.2-SNAPSHOT (git-master-c1d8009) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

### Minecraft: Bedrock Edition Device/Version

1.20.1 Win 10 Edition

### Additional Context

WorldEditing all my Campfires resolved the issue.
Entities / particles still seem to load. However client cannot use wasd

**Comment by shawn695** [comment]
this also just started happening for my players on build 256 
![2a236318-712c-46aa-bdf8-7bf07e7b1394](https://github.com/GeyserMC/Geyser/assets/92684055/de7990d5-ac00-461c-8757-6b3069bec540)

**Comment by Konicai** [comment]
Is this related to campfires in specific or are you just having chunkloading issues? Do you see any errors in the log?

**Comment by Kas-tle** [comment]
I just tested with campfire and it works ok.
