### ISSUE TITLE
Adding the possibility to auto and manually add custom tags to the mappings to group items

### ISSUE THREAD

**Issue by ofunny** [GeyserMC/Geyser#3988]
### What feature do you want to see added?

In Molang we have the query functions  'query.equipped_item_any_tag' and 'query.equipped_item_all_tags' as well as 'query.any_tag' and 'query.all_tags". Especially the first two can be really useful in resource packs, because you could refer to a group of items easily.

For example: I have a attack swing fix, but to make sure it only applies to Geyser attachables I would need a way to identify them as a group.
That's where tags would help a lot.

I would suggest to auto group all items listed in the Geyser mappings JSON  files (as well as mappings made by extension) with the same tag, maybe 'geyser' or 'geyser_custom' by default, but also add an extra option 'tag' to the mappings file so people could add additional tags and group their items the way they want it (https://wiki.geysermc.org/geyser/custom-items/).

So you could rely on the fact that custom items/attachables can always be identified by the default GeyserMC tag, but you could also add tags on top, for example: Grouping all custom bows with one tag in the mappings JSON so you could avoid chaining endless names within multiple 'query.is_item_name_any(...)' functions and use 'query.equipped_item_any_tag(...)' instead.

You would normally assign such tag via behavior's pack, but that's not an option via GeyserMC so it has to be done directly by GeyserMC. The desired outcome would be to tag all custom items via either a default tag or optional custom defined tags, what than could be identified via  'query.equipped_item_any_tag' and 'query.equipped_item_all_tags ...

### Are there any alternatives?

There is no real alternative to this, because the query capabilities of Molang are very limited.

**Comment by Kas-tle** [comment]
It seems we already assign custom tags to tools. See https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/registry/populator/CustomItemRegistryPopulator.java#L308-L323.

Could you check if this works for items that would have the tags `minecraft:is_pickaxe`, `minecraft:is_axe`, `minecraft:is_shovel`, and `minecraft:is_hoe`? Assuming it does then I don't think there would be any objections to adding a way to do this from mappings and api.

**Comment by ofunny** [comment]
I just added a custom model to a pickaxe and ran my swing fix with adjusted queries using 

`query.equipped_item_any_tag('slot.weapon.mainhand', 'minecraft:is_pickaxe')`

That worked well, so adding a default geyser tag like 'geyser' or 'geyser_custom' to all custom items should work just fine, I would not expect any issues by adding extra tags as well.  Implementing that in the referenced code above as default would only add it to tools I guess?

Eventually allowing custom tags via API or mapping would suite all possible needs than.
