### ISSUE TITLE
Changes to chunks don't show up properly

### ISSUE THREAD

**Issue by Comstepr** [GeyserMC/Geyser#399]
**To Reproduce**
1. Install WorldEdit (or do /fill) on Java edition
2. The Bedrock user will not see the changes until they relog

**Expected behavior**
Changes should be automatically updated
**Screenshots / Videos**

**Server Version**
This server is running Paper version git-Paper-185 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
1.0 Snapshot, Inventory branch

**Additional Context**

**Comment by DoctorMacc** [comment]
I am able to replicate this on Paper 184 and the latest Geyser.

**Comment by Tim203** [comment]
Probably related to #267

**Comment by DoctorMacc** [comment]
Looks like the issue is that we ignore non-full chunks, and WorldEdit sends a non-full chunk packet.

**Comment by Tim203** [comment]
Yes

**Comment by ItzCookies** [comment]
Thank you for taking the time to review my issue :)

**Comment by JuniorJPDJ** [comment]
What do you guys think about asking server for sending full chunk, after receiving part chunk data? It would fix everything ;o

**Comment by Heath123** [comment]
> 
> 
> What do you guys think about asking server for sending full chunk, after receiving part chunk data? It would fix everything ;o

I don't think you can "ask" for chunks

**Comment by gaussandhisgun** [comment]
> > What do you guys think about asking server for sending full chunk, after receiving part chunk data? It would fix everything ;o
> 
> I don't think you can "ask" for chunks

you actually can, try to hit F3-A keystroke while playing Java Edition

**Comment by Heath123** [comment]
> > > What do you guys think about asking server for sending full chunk, after receiving part chunk data? It would fix everything ;o
> > 
> > 
> > I don't think you can "ask" for chunks
> 
> you actually can, try to hit F3-A keystroke while playing Java Edition

But that reloads all chunks

**Comment by DoctorMacc** [comment]
We'll probably be able to revisit this with the chunk caching in the sounds branch.

**Comment by DoctorMacc** [comment]
Every player will have a separate chunk cache for this reason.

**Comment by Heath123** [comment]
> 
> 
> > But that reloads all chunks
> 
> by asking of all of them.

https://bugs.mojang.com/browse/MC-96142
Please research before making assumptions
