### ISSUE TITLE
Some ingredients don't want to fit in brewing station

### ISSUE THREAD

**Issue by roggy666** [GeyserMC/Geyser#3992]
### Describe the bug

I use geyser velocity and purpur 1.17.1. I have a problem with brewing, some ingredients don't want to fit in brewing station

### To Reproduce

Make all ingredients compatible with brewing station

### Expected behaviour

All ingredients compatible with brewing station 

### Server Version and Plugins

Purpur 1.17.1, ViaVersion 4.7.0

### Geyser Version

2.1.2

### Minecraft: Bedrock Edition Device/Version

1.19.80, 1.20.x

**Comment by onebeastchris** [comment]
Please attach a geyser dump by running `geyser dump` in your server console, and sending the link it gives you here

**Comment by onebeastchris** [comment]
Unable to replicate with purpur 1.17.1 and Geyser on Velocity. Closing due to lack of response - we need proper reproduction steps to be able to fix issues, so if this issue is still occurring, please provide such steps.
