### ISSUE TITLE
"Abandoned Connection Closed" For bedrock clients joining.

### ISSUE THREAD

**Issue by Will07iam** [GeyserMC/Geyser#3997]
### Describe the bug

On any Bedrock Client attempting to join, they will load in, and then seconds later be hit by this error, either kicking them or outright crashing minecraft: https://imgur.com/c04hitN 
Server works perfectly fine for Java players, never really dropping below 20tps with 10 online.
(specs 10gb ddr3, gigabit ethernet, intel i7-3770 3.4ghz, running paper and floodgate, so should all be more than enough)

### To Reproduce

1.Enter ip and port correctly.
2.Enter the server
3. Wait 2-5 seconds (during this time everything works fine)
4. Be kicked

### Expected behaviour

The server working as usual.

### Server Version and Plugins

This server is running Paper version git-Paper-83 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c793bd9)
You are running the latest version

Geyser build #238 (7/17/23)
Floodgate build #59 (6/9/23)

### Geyser Dump

https://dump.geysermc.org/KIoaKybXHtD4eD5RBJ3BNrM9SwEuxzHi

### Geyser Version

Build #238

### Minecraft: Bedrock Edition Device/Version

1.20.10 Windows 10, Xbox One X, Ps4 Pro.

### Additional Context

Apologies if this isn't allowed here, seen a couple others with the same issue.

**Comment by PedroMPagani** [comment]
I have also seen reports of this on DonutSMP.net, and timeouts even after the newest geyser push are still happening, less rarely.

**Comment by Konicai** [comment]
Check if https://feedback.minecraft.net/hc/en-us/articles/17690571678605 resolves this please

**Comment by Will07iam** [comment]
> Check if https://feedback.minecraft.net/hc/en-us/articles/17690571678605 resolves this please

Yep, perfect. Apologies, was told that bedrock had been updated on my clients' sides, obviously not to .12. Cheers :)
