### ISSUE TITLE
Disconnect with DecoderException

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#3998]
### Describe the bug

players get DC when a bedrock player joins (not all the time) when this happens they sometimes cant rejoin with the same error they got for DC 
"disconnected with: DecoderException : java.lang.IndexOutOfBoundsException: readerIndex(1149) + length(1) exceeds writerIndex(1149): PooledUnsafeDirectByteBuf(ridx: 1149, widx: 1149, cap: 8192) @ io.netty.handler.codec.MessageToMessageDecoder:98"

### To Reproduce

happens randomly in my eyes

### Expected behaviour

players shouldnt be DC when a bedrock player joins 

### Geyser Dump

https://dump.geysermc.org/gn1BH9TQmjXH2HKapkpj2dC3NNMtAk30

### Geyser Version

Build 238

### Minecraft: Bedrock Edition Device/Version

all bedrock console's

**Comment by onebeastchris** [comment]
The second bug was already reported here - https://github.com/GeyserMC/Geyser/issues/3975, so there is no need to re-report it.

**Comment by Konicai** [comment]
Please report only one thing per issue - I removed the 2nd. Also, please include a log (https://mclo.gs) that displays the error occuring

**Comment by shawn695** [comment]
Proxy Logs
https://mclo.gs/BI6l8fJ

**Comment by onebeastchris** [comment]
Does the issue still occur with the latest version of Geyser + Floodgate + Bungee?

**Comment by onebeastchris** [comment]
Closing due to no response.
