### ISSUE TITLE
Bedrock connections timing out after around 30 seconds-1 minute of playing

### ISSUE THREAD

**Issue by JamieIsGeek** [GeyserMC/Geyser#3999]
### Describe the bug

When bedrock players connect through the Standalone version to a bungeecord network they will be able to play for around 30 seconds to 1 minute and then they will be timed out. No issues with Java players. Nothing unusual when turning on debug mode and nothing in both paper and bungeecord consoles.

### To Reproduce

1. Setup Geyser Standalone
2. Connect to the server on bedrock client
3. Wait 30 seconds - 1 minute

### Expected behaviour

Player is able to play wtihout issues

### Server Version and Plugins

Paper Server: git-Purpur-2004 (MC: 1.20.1)*
Bungeecord Server: git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536 by md_5
Standalone version: Build #238

### Geyser Dump

https://dump.geysermc.org/qMOrmj8HCOrnScXq8nbDVs4eUmuCKHvE

### Geyser Version

Geyser version 2.1.2-SNAPSHOT (git-master-396f4e4) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

### Minecraft: Bedrock Edition Device/Version

1.20.10

**Comment by Konicai** [comment]
What is the exact message displayed to the client and in the server log?

**Comment by JamieIsGeek** [comment]
The message displayed when kicked is just “Timed Out” and the same thing in console

**Comment by DB20-official** [comment]
I've experienced this myself, it turns out the `forward player ping` option causes the timeouts. Try turning it off in your Geyser config and restart your proxy. See if it helps. If it's already off and it still does it, I'm not sure what else could be causing that asides from just unstable internet.

**Comment by Konicai** [comment]
There have been improvements to `forward-player-ping` since the dump Jamiels shared. If you're not on the latest version, I would suggest retesting with the option enabled.

**Comment by RedCoder09** [comment]
Hey, it seems this is still happening to me. Maybe this issue is worth reopening?

**Comment by LukeTheDukeHatter** [comment]
This still happens, I can connect using things like MC:PE bedrock with a dedicated custom server list, and geyser works absolutely great, but if I am using some method to connect to a custom server from Nintendo Switch, my friend can get in, it seems to work absolutely fine, geyser allowing them to join and run around, but 30 seconds after I just get a "Connection Lost: Timed out" in logs and on their screen and can't find any way to fix it, I tried both with and without `forward-player-ping` to test it, does exactly the same thing. This is on a 1.21.5 server(when that was latest) and latest geyser and latest bedrock edition copy.

**Comment by Sakura-sx** [comment]
Same issue on 1.21.7
