### ISSUE TITLE
Geyser-Standalone Bungeecord LegacyPingPassthrough

### ISSUE THREAD

**Issue by AlohaLegend** [GeyserMC/Geyser#4003]
### Describe the bug

When attempting to use the Legacy Ping Passthrough feature in Geyser Standalone, an error occurs, preventing the successful retrieval of ping information from remote Minecraft servers. Specifically, an "EOFException" is encountered during the process of reading the server's response, which disrupts the communication flow and leads to a failed ping passthrough.

### To Reproduce

1. Start the Geyser standalone server.
2. Enable the Legacy Ping Passthrough feature in the Geyser configuration.
3. Try to ping a remote Minecraft server using the passthrough feature.
4. Observe the console output to encounter the EOFException error.

### Expected behaviour

The Legacy Ping Passthrough should function smoothly, allowing Geyser standalone to fetch and interpret the remote server's response without any issues. The ping information should be successfully retrieved and displayed in the console without any errors.

### Server Version and Plugins

Geyser-Standalone: 2.1.2-SNAPSHOT
BungeeCord: BungeeCord-Bootstrap:1.20-R0.1-SNAPSHOT:0199cb9:1720

### Geyser Dump

https://dump.geysermc.org/DXgkhfDgZufrYzm44lYTGnPOhLDwDqdZ

### Geyser Version

2.1.2-SNAPSHOT (git-master-ea2bac4)

### Minecraft: Bedrock Edition Device/Version

1.20.10, IOS

### Additional Context

- The issue may be related to the format or size of the server's response, which does not align with the expected data structure.
- I have verified that the remote Minecraft server being pinged is online and accepting connections on the specified address and port.
- I updated Geyser standalone to the latest version, but the problem still persists.
- No other significant changes were made to the Geyser standalone configuration or codebase.

**Comment by Konicai** [comment]
Are you able to share the address of the target server?

**Comment by Konicai** [comment]
Closing - this has become stale, and we can't begin to attempt fixing this without server details.
