### ISSUE TITLE
Players unable to left click mid air again

### ISSUE THREAD

**Issue by chrismwiggs** [GeyserMC/Geyser#4006]
### Describe the bug

There was once a fix for clicking midair on bedrock clients (issue #[2113](https://github.com/GeyserMC/Geyser/issues/2113)), but it has recently stopped working.

### To Reproduce

1. Start 1.20.1 server (paper/purpur)
2. Connect to server via Geyser standalone (latest #239)
3. Try to trigger a plugin event with left click (most often seen in clicking with an item to open an inventory GUI, or trigger abilities in plugins like Mcmmo and ProjectKorra)

### Expected behaviour

Ideally, the left click would fire as seen with Java, without targetting a block

### Server Version and Plugins

Paper 1.20.1 (Purpur-2016), but this has been an issue for a few versions, including on 1.1
Geyser Standalone (2.1.2-SNAPSHOT (git-master-3a0c1b7)

### Geyser Dump

https://dump.geysermc.org/R6WSo5W2O8ypLacGkpvy1YvIF4Jf5Ak7

### Geyser Version

2.1.2-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20.12

**Comment by Camotoy** [comment]
Check to see if the next build fixes this issue?

**Comment by chrismwiggs** [comment]
Appears to be fixed! Thanks!
