### ISSUE TITLE
Taking damage when jumping from high altitude onto slime block with carpet

### ISSUE THREAD

**Issue by MrZillaGold** [GeyserMC/Geyser#401]
**Describe the bug**
If you jump onto a block of mucus from a high height on top of which there is a carpet, we will be damaged

**To Reproduce**
1. Go to the server
2. Climb to a great height and jump onto the block of mucus on top of which the carpet

**Expected behavior**
No damage

**Screenshots / Videos**
https://youtu.be/UdslwDgJPf8

**Server Version**

![image](https://user-images.githubusercontent.com/42776347/79990985-1311a980-84f5-11ea-910e-119fec17a5a8.png)

**Geyser Version**
latest

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by MrZillaGold** [comment]
![image](https://user-images.githubusercontent.com/42776347/79992025-4c96e480-84f6-11ea-9351-88a9c3e498fd.png)
With enderchest in which water happens the same

**Comment by Trains77** [comment]
Yes this does 100% happen I have noticed it on my server

**Comment by MrZillaGold** [comment]
@rtm516 Could you check this bug, please? It looks like this report drowned in other issues

**Comment by rtm516** [comment]
@MrZillaGold Thanks for bringing this to my attention, after some testing this is down to the movement issues in Geyser as its treating the blocks as full blocks and the carpets as half blocks causing the client not to hit the water or slime blocks at all.

**Comment by RednedEpic** [comment]
As this is movement related, I'm closing and documenting this in #204 as it more or less covers the general "movement problems" within Geyser at the moment.
