### ISSUE TITLE
Invisible player

### ISSUE THREAD

**Issue by fileexists** [GeyserMC/Geyser#4010]
### Describe the bug

When the gamerule "doImmediateRespawn" is enabled, and a player dies by a bow shot by a player, when the victim respawns the killer sees them staying still at spawn even if the victim moved near them.
It happens only in the servers with the gamerule, and its kinda annoying to die from an invisible player

### To Reproduce

1) Enable the "doImmediateRespawn" gamerule
2) Kill a player using a bow

### Expected behaviour

See the player.

### Geyser Dump

https://dump.geysermc.org/AKb8eaPhxXXHdMh8NrMnwMMK2bvkrKoe

### Geyser Version

2.1.2-SNAPSHOT (git-master-c1d8009)

### Minecraft: Bedrock Edition Device/Version

Android version, and Windows Version

**Comment by Kas-tle** [comment]
Cannot reproduce. If this is still an issue, please reply with specific reproduction steps.
