### ISSUE TITLE
Allow /geyser offhand, advancements, statistics commands to be run from the standalone console for players

### ISSUE THREAD

**Issue by Analogged** [GeyserMC/Geyser#4013]
### What feature do you want to see added?

Currently `/geyser offhand` can only be run by a bedrock player directly. I would like to be able to run `/geyser offhand <bedrock playername>` from the Geyser standalone console and have it run the offhand command for the player.

I am trying to look into a way to alias the `/geyser offhand` commands into just `/offhand`. This is doable while running geyser as a plugin but not while running as standalone. 

If we were able to run offhand commands from the console for players it would allow me to setup command aliases from the java server that would inturn send commands to the standalone console.

### Are there any alternatives?

Normal command alias plugins will not work while running Geyser Standalone.

**Comment by Konicai** [comment]
This isn't suitable for every single player-command that Geyser registers - it would be better as an extension. 

If API needs to be added to geyser-api to make this possible without having to depend on geyser-core (I'm 99% sure), a feature request can be made for that.
