### ISSUE TITLE
Right-Click isn't working properly.

### ISSUE THREAD

**Issue by SamGamerYT** [GeyserMC/Geyser#4015]
### Describe the bug

Right Click acts as Left Click in a menu even if the console players has KBM

### To Reproduce

Right Click

### Expected behaviour

Should Popup a right click menu

### Server Version and Plugins

Purpur 1.20.1
Latest Geyser

### Geyser Version

Latest: Yes

### Minecraft: Bedrock Edition Device/Version

Playstation 4, Xbox One X

**Comment by Camotoy** [comment]
In inventory menus this is a can't-fix. Bedrock does not tell us clicks; it tells us where items are moving and that's it.
