### ISSUE TITLE
Exceptions on serializing ScoreComponent with null value

### ISSUE THREAD

**Issue by raksodnus61** [GeyserMC/Geyser#4017]
### Describe the bug

(sorry for bad english)

My players join without any problem, but once they join, my console spams

![resim](https://github.com/GeyserMC/Geyser/assets/82219658/e7fe2577-7699-4489-8217-01da10f34f8a)

 [Geyser player thread-4-1/WARN] [Geyser-BungeeCord]: Failed to parse message java.lang.NullPointerException: null
 [Geyser player thread-4-1/WARN] [Geyser-BungeeCord]: Failed to parse message java.lang.NullPointerException: null
 
 
 
 and exactly 9 minutes later they are all kick for time out

### To Reproduce

startup server
joins players
kick players
lonely me :/

### Expected behaviour

How can I solve this

### Server Version and Plugins

![resim](https://github.com/GeyserMC/Geyser/assets/82219658/8594278a-d963-4121-b215-46045560ad81)

### Geyser Dump

https://dump.geysermc.org/d0hA6tQMb0vQzmwwis9aHbgrt0LKdRCY

### Geyser Version

latest

### Minecraft: Bedrock Edition Device/Version

1.20.12

### Additional Context

I need HELP

**Comment by Konicai** [comment]
I'll assume this is the issue you shared in discord that was being caused by an action bar. 

What was causing the issue is that the action bar message contains a Score Component, and one of Geyser's dependencies is failing to serialize it correctly. 

I can give you an experimental build today that should fix it.

**Comment by raksodnus61** [comment]
YES PLEASE ı NEED ALL OF THEM 
ACTION BAR & PLAYERS

**Comment by raksodnus61** [comment]
I deleted my actionbar plugin but my players still kicking 9th minutes

**Comment by Konicai** [comment]
If the messages are gone and the kicking still occurs, its likely a separate issue.

**Comment by raksodnus61** [comment]
Messages gone and kicking keeps giving timeout message with no errors and kicks

**Comment by egeozcelik2** [comment]
I have same error in my server 
My players are kicking for nothing it says "time out"
but no command or any think is there
players can play just 9 minutes then they will log out "for time out"
