### ISSUE TITLE
Bedrock players cant join server

### ISSUE THREAD

**Issue by NBS-Paste** [GeyserMC/Geyser#4018]
### Describe the bug

When a bedrock player trys  to join the server they just get a screen that says unable to connect to server.

### To Reproduce

1. open server list on console or go to server tab on pc/mobile
2. click on server
3. let it load
4. get unable to connect to server screen.

### Expected behaviour

should be able to load into server.

### Server Version and Plugins

paper 1.20.1 #100 
plugins: Bukkit Plugins:
[21:03:51 INFO]:  - ChunkLoader, DeadChest, DiscordSRV, DropHeads, floodgate, Geyser-Spigot, HiddenArmor, ImageOnMap, LuckPerms, Multiverse-Core
[21:03:51 INFO]:  Multiverse-Inventories, Multiverse-SignPortals, Otherside, PlugManX, ProtocolLib, spark, VeinMiner, ViaBackwards, ViaVersion, VillagerSaver

### Geyser Dump

https://dump.geysermc.org/WNA2oUoUEaIHOThEru0zryi7KFqt8Rjn

### Geyser Version

1.20.1 snapshot that came out on 7/29/23

### Minecraft: Bedrock Edition Device/Version

all devices

### Additional Context

doesn't show in console that they are trying to connect.

**Comment by Konicai** [comment]
This is a networking issue, not a Geyser bug. Please join our Discord for help with this.
