### ISSUE TITLE
Cannot move items inside the backpack

### ISSUE THREAD

**Issue by 1470429149** [GeyserMC/Geyser#4019]
### Describe the bug

Geyser cannot move items with AttributeModifiers，And the item gets stuck in the backpack.
![Screenshot_2023-07-30-15-25-59-936_com mojang minecraftpe](https://github.com/GeyserMC/Geyser/assets/96332168/02647307-41f1-4a19-889f-9e4916e7bfde)
In the picture above, you can see the item stuck in the backpack.

### To Reproduce

1. Use the following command on any 1.12.2 spigot server
2. /give @p minecraft:iron_sword 1 0 {AttributeModifiers:[{Operation:0,Amount:58,UUIDLeast:75L,UUIDMost:75L,Slot:mainhand,AttributeName:"generic.attackDamage",Name:"generic.attackDamage"}]}
3. Try to move this item in the backpack.
4. Your game mode must be Adventure or Survival

### Expected behaviour

I can move anything in my backpack.

### Screenshots / Videos

![Screenshot_2023-07-30-15-25-59-936_com mojang minecraftpe](https://github.com/GeyserMC/Geyser/assets/96332168/1746f141-34b6-4ebf-baec-2bc1505ab1ea)

### Server Version and Plugins

1.12.2 Spigot
This server is running Geyser version 2.1.2-SNAPSHOT (git-master-3949fb1) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

### Geyser Dump

https://dump.geysermc.org/dadVKnwmae1svmHihGzJnmG6QIG97YXq

### Geyser Version

 This server is running Geyser version 2.1.2-SNAPSHOT (git-master-3949fb1) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

### Minecraft: Bedrock Edition Device/Version

1.20

### Additional Context

Attention, please!!
I already know some ways to fix this problem:
Add UUID in AttributeModifiers, for example:
/give @p minecraft:iron_sword 1 0 {AttributeModifiers:[{Operation:0,Amount:58,UUIDLeast:75L,UUIDMost:75L,UUID:[I;0,75,0,75],Slot:mainhand,AttributeName:"generic.attackDamage",Name:"generic.attackDamage"}]}
Because of the addition of "UUID:[I;0,75,0,75]" to the above command, the geyser will be able to move the items in the backpack normally
This fix is for developers only, because I can't add a UUID to each item to fix the problem of not being able to move the items in the backpack

**Comment by onebeastchris** [comment]
I am not able to replicate this issue with the item being unable to move, atleast not while using https://github.com/GeyserMC/Geyser/commit/7b409fd55b08e0d92bc768061b1c338bd05eb9ec on paper 1.20.1. If this is only an issue on 1.12.2, this might be a  ViaVersion bug? Not entirely sure.
![image](https://github.com/GeyserMC/Geyser/assets/105284508/4a09a2c1-ed9f-4a4f-80fc-4b113b02a99f)
However, there is some weirdness with how we show the name :p

**Comment by 1470429149** [comment]
> 我无法重现此问题，因为该项目无法移动，至少在1.20.1 纸上使用[7b409fd时不能。](https://github.com/GeyserMC/Geyser/commit/7b409fd55b08e0d92bc768061b1c338bd05eb9ec)如果这只是 1.12.2 上的问题，这可能是 ViaVersion 错误？不完全确定。 然而，我们显示名称的方式有些奇怪：p ![图像](https://user-images.githubusercontent.com/105284508/258155601-4a09a2c1-ed9f-4a4f-80fc-4b113b02a99f.png)

No, you have to use the command at 1.12.2 Server Core to reproduce this error

**Comment by onebeastchris** [comment]
Are there any issues with an up-to-date java client (aka 1.20) with moving that item?
If there are, this would be a ViaVersion issue
