### ISSUE TITLE
Geyser kicks players after some time

### ISSUE THREAD

**Issue by BlueBerrySans365** [GeyserMC/Geyser#4020]
### Describe the bug

For some reason when player (Tested from PS5 & Pocket Edition user) joins my server, geyser spams with:
![image](https://github.com/GeyserMC/Geyser/assets/46006335/ad94efb2-f05c-44b6-a1c2-d78fed2c05fb)
And after some time it kicks them because of timeout
![image](https://github.com/GeyserMC/Geyser/assets/46006335/de0a9efc-7f46-4f5d-a8bd-117591a69917)
Translation: Nssw2020 was disconnected from Java Server because of Bedrock Client timeout

### To Reproduce

Startup server
Bedrock players join the server

### Expected behaviour

To work normally

### Server Version and Plugins

Server version: git-Purpur-2019 (MC: 1.20.1)  

Paper Plugins: (1):
- PrefiX  

Bukkit Plugins: (36):
- BetterDragonFight, BlueMap, Celeste, ChaosHeads, ChatEmojis, ChatItem, Chunky, ClickVillagers, DeadlyDisasters, Essentials, EssentialsDiscord, FancyPhysics, FasterBoat, floodgate, Geyser-Spigot, ImageFrame, InvisibleItemFrames, JukeboxExtendedReborn, LuckPerms, Mailboxes, Maintenance, Mentions, PauseChat, PlaceholderAPI, ProtocolLib, Ships, SignEdit, SkinsRestorer, spark, TAB, Tamablefoxes, UltimateHomes, ViaBackwards, ViaRewind, ViaVersion

### Geyser Dump

https://dump.geysermc.org/cmmVh8GuFBzTp3FXyT7REqHB7bpnI7eJ

### Geyser Version

2.1.2-SNAPSHOT (git-master-d147ee3)

### Minecraft: Bedrock Edition Device/Version

1.20.12 PS5, Pocket Edition

**Comment by Konicai** [comment]
I can provide a jar later today that's able to count disconnect causes/ratios. 

If all bedrock players are disconnecting at once because of "Bedrock client timed out", then I imagine your server is likely either choking, the server's network connection became unstable or dropped for a short period of time, or some other odd issue. Mass disconnects have been reported before.

**Comment by onebeastchris** [comment]
Not sure if related, but it seems like https://github.com/GeyserMC/Geyser/issues/4116 covers the same issue.
Can you test the build from https://github.com/GeyserMC/Geyser/pull/4329 and see if that resolves the kicking issues?

**Comment by onebeastchris** [comment]
Closing due to no further response.
