### ISSUE TITLE
Improper movement and getting teleported back

### ISSUE THREAD

**Issue by Sparlott** [GeyserMC/Geyser#4028]
### Describe the bug

Getting teleported back, when colliding with small pointy dripstone. Can't move, can't jump, can't even rotate

### To Reproduce

1. Log in with bedrock account
2. Walk into small pointed dripstone, or other blocks with weird collisions

### Expected behaviour

A player should slide against dripstone's collision box

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/139014834/0cc553f0-1e12-4024-b37a-a9b452736f55

[14:49:06 INFO]: [Geyser-Spigot] Teleport (2) from -28.206493 120.0 -0.07275157
[14:49:06 INFO]: [Geyser-Spigot] to -28.114817 120.0 -0.26753712
[14:49:06 INFO]: [Geyser-Spigot] Teleport (3) from -28.230532 120.0 -0.046568036
[14:49:06 INFO]: [Geyser-Spigot] to -28.15989 120.0 -0.18051726
[14:49:06 INFO]: [Geyser-Spigot] Teleport (4) from -28.20839 120.0 -0.09535999
[14:49:06 INFO]: [Geyser-Spigot] to -28.15989 120.0 -0.18051726

### Server Version and Plugins

Aternos
git-Paper-98 (MC: 1.20.1)

Plugins:
- GeyserMC
- Floodgate
- WorldEdit
- WorldGuard
- bStats

### Geyser Dump

https://dump.geysermc.org/wSR0DDEU8T9x0OCwF2XDmWQawMvG1Miu

### Geyser Version

2.1.2-SNAPSHOT (git-master-396f4e4)

### Minecraft: Bedrock Edition Device/Version

1.20.10.01, Every device that connected to that server

### Additional Context

I am aware of issue #204. However, in this case Geyser-Spigot is the one that teleports, and not the Main server thread. Issue is also not affected by the distance from spawn. I also couldn't disable this feature in config.yml

**Comment by onebeastchris** [comment]
Please see https://geysermc.org/other/hurricane/ for a plugin/mod that fixes these. Thanks!
