### ISSUE TITLE
Action bars are pink by default

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Geyser#4030]
### Describe the bug

When you send an action bar to the bedrock client with no color, it defaults to pink (wtf?)

### To Reproduce

Send action bar to client using play.sendActionBar("test") it comes out pink

### Expected behaviour

It should be white

### Server Version and Plugins

paper-1.20.1-100

### Geyser Version

BUILD 247 (LATEST)

### Minecraft: Bedrock Edition Device/Version

UWP latest (1.20.12 I think?)

**Comment by onebeastchris** [comment]
Sorry, that was me in https://github.com/GeyserMC/Geyser/pull/3941/commits/65d7c8a7506c896854d779574cef1d3d35f31ee2. Weirdly enough, system chat overlays keep their color, just not text sent via actionbar.. I'll probably PR a revert after further testing, atleast for actionbar. System chat overlay seems to be unaffected (does not lose color, doesnt overlap with actionbar, and does not overlap with armor/left air bubble column).

**Comment by onebeastchris** [comment]
Would you mind testing #4066 (you can download the artifacts under the "checks" tab) for whether that resolves this issue?
