### ISSUE TITLE
Error PlayerListEntry

### ISSUE THREAD

**Issue by Z3r0xh** [GeyserMC/Geyser#4034]
### Describe the bug

Since I installed geyser in the proxy I get these messages in the console when a bedrock user wants to enter, the user enters fine and his uuid is assigned, but the uudi that appears in that message is not that of the ingame user

### To Reproduce

1. The user enters the proxy
2. while entering this spam skips.
3. After a while the spam stops coming out

### Expected behaviour

I would like spam not to happen, since it is sometimes and not always and it annoys me if I have to keep checking

### Screenshots / Videos

![geyser](https://github.com/GeyserMC/Geyser/assets/138524212/4aeba8b7-c717-40ff-b676-44de352f7974)

### Server Version and Plugins

![image](https://github.com/GeyserMC/Geyser/assets/138524212/d20d8216-bdd1-4134-8137-cd1f8e030f26)
Plugins:
Geyser-bungee
Floodgate-bungee
nLogin
minimotd
Proxy= NullCordX
SparkB
NuVotifier

### Geyser Dump

https://dump.geysermc.org/oXBPWpP3rof0jt3No7qsvEevLrBbIxw1

### Geyser Version

Geyser-BungeeCord 2.1.2-SNAPSHOT

**Comment by Kas-tle** [comment]
This warning is also sent by the java client when it receives a tab update for a player that has not been properly added to the tab list previously, so we also print it in the interest of emulating java behavior.
