### ISSUE TITLE
No blocks after playing for a period of time

### ISSUE THREAD

**Issue by NotKillerGod** [GeyserMC/Geyser#4035]
### Describe the bug

At the beginning, it is normal, but after playing for a period of time, there will be no blocks

### To Reproduce

Join the geyser server
play about 30 minutes
problem happened

### Expected behaviour

Fix this bug

### Screenshots / Videos

https://1drv.ms/v/s!AgamegtTIVLngw-7TvSFP5glIvxg?e=OeHxmZ

https://github.com/GeyserMC/Geyser/assets/89688029/1f30a98d-a23b-4b62-b869-17f2483930c7

### Server Version and Plugins

Server version: waterfall 1.20.1
Plugins version:Build 247 Bungeecord

### Geyser Dump

https://dump.geysermc.org/JFk8rh1YgJN0W9EDwYSbszRJMKujJwZo

### Geyser Version

build247 8/1

### Minecraft: Bedrock Edition Device/Version

v1.20.1

**Comment by onebeastchris** [comment]
Likely duplicate of #2861, try updating your java jdk/jre to Java 17.0.6 or higher, or by using the temporary workaround mentioned there.

**Comment by NotKillerGod** [comment]
Should I update to jdk20 to fix this bug？

**Comment by onebeastchris** [comment]
That should work, or try 17.0.6

**Comment by onebeastchris** [comment]
Closing as duplicate due to no further response.
