### ISSUE TITLE
Bedrock version players may get stuck using RandomTP

### ISSUE THREAD

**Issue by NotKillerGod** [GeyserMC/Geyser#4036]
### Describe the bug

Bedrock version players may get stuck using RandomTP
Can only destroy the blocks under feet
In the eyes of Java players, there is no movement
This is flying

### To Reproduce

1.Joined the server 
2.Use /rtp
3.Get stuck

### Expected behaviour

Solve the problem

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/89688029/cf1f5f88-c908-403b-967f-8dfa76d69b68
 
Java:
![b1849e5f49d05c4adfc95696df37520a_720](https://github.com/GeyserMC/Geyser/assets/89688029/31443957-a436-488c-a01b-ea238ea2b3d6)

### Server Version and Plugins

Server version: waterfall 1.20.1
Plugins version:Build 247 Bungeecord
Use jdk17.0.6

### Geyser Dump

https://dump.geysermc.org/tdTGEIlubKnd2jWPKQU3iArHKB499hFH

### Geyser Version

build247 8/1

### Minecraft: Bedrock Edition Device/Version

v1.20.1

**Comment by Kas-tle** [comment]
Hello, could you please isolate the specific plugin that is causing this issue (find the minimal plugins required to reproduce)?
