### ISSUE TITLE
ClientboundLoginDisconnectPacket not fully read

### ISSUE THREAD

**Issue by mister-proger** [GeyserMC/Geyser#4049]
### Describe the bug

Starting from some point they can't connect. I don't know which one. But for sure less than two weeks and updating the geyser did not help.

### To Reproduce

1. Restarting the server
2. Perhaps installing `HubConnector`

### Expected behaviour

The client will connect to the server

### Server Version and Plugins

Proxy: `BOTFILTER 1.8.X-1.20.X` (there is no `/version` command.)
Game servers:
> Lobby `git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
`CustomJoinItems`, `DeluxeMenus`, `Floodgate`, `HideStream`, `LuckPerms`, `PAPI`, `SetSpawn`, `TAB (PremiumTAB)`, `VV`/`VR`/`VB`, `WE`/`WG`.

> Game Server `git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
`Anti-RedstoneClock`, `BetterSleeping4`, `DynMap`, `Floodgate`, `TAB (PremiumTAB`, `VV`/`VR`/`VB`, `WE`.

There is also another server in the bungee. Unlikely, but maybe for some reason it can accept the connection.
> `git-Paper-782 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`
`ajLeaderboards`, `antiRedstoneClock`, `AntiRelog`, `AutoMessage`, `BetterRTP`, `BKCommonLib`,` ChatEx*`, `ChestCommands`, `Citizens`, `CustomJoinItems*`, `dtlTradersPlus`, `Duels`, `EasyPayments`, `Essentials`, `ExecutableItems`, `FeatherBoard`, `Floodgate`, `HideStream*`, `HolographicDisplays`, `LuckPerms`, `Maintenance`, `MoneyFromMobs`, `Multiverse-Core`, `Multiverse-NetherPortals`, `MythicMobs`, `PlaceholderAPI`, `PlayerStats`, `ProtocolLib`, `SCore`, `SetSpawn*`, `SimpleClans`, `SimpleSit*`, `TAB (PremiumTAB)`, `UltimateAutoRestart`, `Vault`, `ViaVersion`, `Vulcan`, `WorldBorder`, `WorldEdit`, `WorldGuard`, `WorldGuardGriefFix`, `zAuctionHouseV3`

### Geyser Dump

https://dump.geysermc.org/sDIIu5b71b3Xsvbg3xSXOAj6Aw9GKiU9

### Geyser Version

2.1.2-SNAPSHOT (git-master-505c065)

### Minecraft: Bedrock Edition Device/Version

1.20, Bedrock

### Additional Context

```
15:14:27 [INFO] [Geyser-BungeeCord] /194.50.13.23:3341 tried to connect!
15:14:28 [INFO] [Geyser-BungeeCord] Player connected with username YanDiReStInk
15:14:28 [INFO] [Geyser-BungeeCord] YanDiReStInk (logged in as: YanDiReStInk) has connected to the Java server
15:14:29 [INFO] [/194.50.13.23:0] <-> InitialHandler has connected
15:14:29 [INFO] [floodgate] Floodgate player logged in as .YanDiReStInk joined (UUID: 00000000-0000-0000-0009-01f8e4369c4e)
15:14:29 [INFO] [floodgate] Floodgate player logged in as .YanDiReStInk disconnected
15:14:29 [WARNING] [Geyser-BungeeCord] Downstream packet error! Packet "ClientboundLoginDisconnectPacket" not fully read.
15:14:29 [INFO] [Geyser-BungeeCord] YanDiReStInk has disconnected from the Java server because of Connection closed.
```
I've been using the plugin for about three weeks. But one day (today), after restarting the server, I will not be able to connect the mobile client. Initially I thought that the problem was in the `HubConnector`, but even after removing and cleaning it did not help. I thought that the problem was that I was adding another server to the bunge and I configured it incorrectly, but disabling it didn't help either. As far as I understand, the player does not go beyond the Proxy at all.

**Comment by Konicai** [comment]
Can you try reproducing the issue with BungeeCord instead of whatever BOTFILTER is?

**Comment by mister-proger** [comment]
Yes, probably, but not right now. Now I can only say one thing. I poked `Floodgate` after creating the request, but literally nothing has changed. Even changing the authorization type or auto-determining the port did not change anything. Attach more logs or try to specifically cause any errors to determine at what stage the problem occurs?

**Comment by mister-proger** [comment]
I removed all the old plugins, and installed the Velocity + Limbo build. Well, Geyser has been updated with Floodgate. Everything worked.
