### ISSUE TITLE
Client freezes when opening up commands for the first time

### ISSUE THREAD

**Issue by DoctorMacc** [GeyserMC/Geyser#405]
**Describe the bug**
When typing `/` in the command prompt, the client freezes for about 5 seconds until you can use the commands. This happens again after being killed but otherwise does not freeze up again. I have Essentials and WorldEdit installed.

**Server Version**
Paper-184

**Geyser Version**
Master 71

**Minecraft: Bedrock Edition Version**
v1.14.60

**Comment by RednedEpic** [comment]
> **Describe the bug**
> When typing `/` in the command prompt, your game freezes for about 5 seconds until you can use the commands. This happens again after being killed but otherwise does not freeze up again.
> 
> **Server Version**
> Paper-184
> 
> **Geyser Version**
> Master 71
> 
> **Minecraft: Bedrock Edition Version**
> v1.14.60

Does this freeze only the client or Geyser entirely?

**Comment by DoctorMacc** [comment]
Only the client - Geyser is fine.

**Comment by rtm516** [comment]
Doesn't always happen, seems to happen less when you just play for like 30s-1min then try. Unsure if we can fix this, maybe worth adding a config option to disable command completion?

**Comment by DoctorMacc** [comment]
I'd be OK with this.

**Comment by Tim203** [comment]
If the client does crash on NukkitX too, sure go ahead. Otherwise I would recommend finding a way to solve it instead of making it a config option.

**Comment by LegacyGamerHD** [comment]
i agree with tim

**Comment by rtm516** [comment]
We would need to get the command count up quite high to test, EssentialsX on java registers about 1k commands including all the `essentials:` prefixed commands.

**Comment by LegacyGamerHD** [comment]
@rtm516  you forget cmi

**Comment by Tim203** [comment]
You can make a Nukkit plugin to test that out. A plugin that makes over 1k commands by using random letters.

**Comment by Litleck** [comment]
Happening for me too, my plugins:

- floodgate-bukkit.jar
- Geyser-Bukkit.jar
- Multiverse-Core-4.1.0.jar
- worldedit-bukkit-7.1.0.jar
- EssentialsX-2.17.2.0.jar

**Comment by lukeeey** [comment]
Essentials is the big one out of them all.

You see, on bedrock you have a lot less commands for a start because it makes use of enums which is great and I think the java edition system is a pile of crap

**Comment by Litleck** [comment]
I removed EssentialsX and it still occurs, also with Multiverse-core.

**Comment by lukeeey** [comment]
I believe its related to vanilla commands, but this will be discussed more tomorrow

**Comment by blubbll** [comment]
cant you guys just disable the tab completions or limit them

**Comment by E404NNF** [comment]
i have the same problem but instead the client crashes instead of freezing

**Comment by ducanh2002123** [comment]
One temporary workaround that I know work is to use . Instead of /, it doesn’t activate command completion

**Comment by towuk118** [comment]
its real problem, i have this too! freeze on chat on login server :(

**Comment by Crypt97** [comment]
It's annoying :/

**Comment by DoctorMacc** [comment]
After some research, it seems that this is a Bedrock issue and not a Geyser issue. Bedrock clients freeze when given large commands, and combine that with the command arguments and it's worse with Geyser. We'll be looking at workarounds shortly.

**Comment by arshizx** [comment]
maybe it's about /pluginname:commands, but i'm not sure

**Comment by rtm516** [comment]
@arshizx we have a PR open for disabling those but if doesn't make too much of a different

**Comment by arshizx** [comment]
owh, but isn't that list of commands cannot be deleted? if can, i hope you can remove it by using the config (people can enable/disable) cause its really annoyed me. thx it's my suggestions xD
