### ISSUE TITLE
API to Modify Skins Sent to Bedrock Players

### ISSUE THREAD

**Issue by DokiDerg** [GeyserMC/Geyser#4050]
### What feature do you want to see added?

Since bedrock has 3d models for their players, would it be possible to send a java's 3d skin from figura or cpm, as a 3d skin model for bedrock

### Are there any alternatives?

- Check if a model is there, download it, and send it when sending the java skin+cape

**Comment by Kas-tle** [comment]
https://github.com/Camotoy/BedrockSkinUtility
https://github.com/Camotoy/GeyserSkinManager
Work on this has already been done with fabric, though the mod may require an update to 1.20. However, everything needed to do it through our API is already available and you can refer to GeyserSkinManager as an example.

**Comment by DokiDerg** [comment]
thank you, i am aware of java being able to see bedrock's 3d skins, but i was wondering if it is possible to do it the oppisite way, where if i have a figura avatar, allow bedrock players to see me in 3d

**Comment by Kas-tle** [comment]
Yes I suppose in theory we could provide an API to send skins with geometry to bedrock players.
