### ISSUE TITLE
unable to climb a block that is added from climbable.json by a datapack

### ISSUE THREAD

**Issue by CherubicBoot** [GeyserMC/Geyser#4051]
### Describe the bug

just like what the title said, using climbable block tag from a datapack is not working for the bedrock client.

### To Reproduce

1. Create a datapack that contain `climbable.json` inside `data/minecraft/tags/blocks`.
2. Add chain into the file:
`{
  "replace": false,
  "values": [
    "minecraft:chain"
  ]
}
`
3. Start the server.

### Expected behaviour

Bedrock player should be able to climb the chain, just like how the Java Players can.

### Geyser Version

Geyser version 2.1.2-SNAPSHOT (git-master-505c065) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

### Minecraft: Bedrock Edition Device/Version

1.20 Windows 10, 1.20 Android

**Comment by Camotoy** [comment]
I don't think Bedrock has an equivalent to this, so I cannot guarantee there is a fix here yet.

**Comment by onebeastchris** [comment]
Closing this issue in favor of it being documented on our current limitations page: https://wiki.geysermc.org/geyser/current-limitations/

**Comment by Julmik647** [comment]
I have a(n) (kinda stupid) idea for workaround: give players levitaton effect if they want to climb on custom climbable. Or slow falling if they want to climb down.
