### ISSUE TITLE
How do I fix the error (geyser.auth.floodgate.encryption_fail) for bedrock players trying to join my Minecraft Java world?

### ISSUE THREAD

**Issue by JeffTheMurderCat** [GeyserMC/Geyser#4054]
Whenever a bedrock player attempts to join my Minecraft java world they keep getting this error (geyser.auth.floodgate.encryption_fail). How do I fix this issue

Btw I'm running the server on Paper 1.20.1 if that's helpful

![Error message](https://github.com/GeyserMC/Floodgate/assets/102166148/75bfcb87-5599-4678-b285-82ea41090d20)

**Comment by JeffTheMurderCat** [comment]
> Could you upload your logs to https://mclo.gs and send the link here? This error on itself is not very useful.

https://mclo.gs/4xqYLyr

**Comment by Tim203** [comment]
Please send your whole log. This error normally only occurs when you also see 'Error while reading Floodgate key file'

**Comment by JeffTheMurderCat** [comment]
> Please send your whole log. This error normally only occurs when you also see 'Error while reading Floodgate key file'

[latest.log](https://github.com/GeyserMC/Geyser/files/12371897/latest.log)
I think this is it

**Comment by JeffTheMurderCat** [comment]
[latest.log](https://github.com/GeyserMC/Geyser/files/12371904/latest.log)

I believe this is the log

**Comment by JeffTheMurderCat** [comment]
I believe this is the log your looking for

https://mclo.gs/XUnTb5a

**Comment by Tim203** [comment]
Ok now that I have the whole log this makes more sense. Update Geyser & Floodgate to the latest version and everything should work again.
