### ISSUE TITLE
Bedrock does not get sent the block change with Player::sendBlockChange 

### ISSUE THREAD

**Issue by otDan** [GeyserMC/Geyser#4057]
### Describe the bug

Bedrock does not get sent a packet for block change like Java client with `Player::sendBlockChange `

### To Reproduce

1. Use `Player::sendBlockChange ` to send a block change
2. Look at Java client receiving the block change fine
3. Block change is not interpreted on Bedrock

### Expected behaviour

The block change packet is also done on the Bedrock client.

### Geyser Version

2.1.2-SNAPSHOT (git-master-505c065)

### Minecraft: Bedrock Edition Device/Version

1.20.12

**Comment by Kas-tle** [comment]
Could you please create and provide the source for an example plugin to trigger this so we can see exactly the conditions you're doing this under?

**Comment by otDan** [comment]
> 

just calling 

> Could you please create and provide the source for an example plugin to trigger this so we can see exactly the conditions you're doing this under?

just calling it in any circumstance does not update the block for bedrock players, for java players it always works

**Comment by Kas-tle** [comment]
If you want to provide an example (assuming you already have one since your posting the issue) that would make debugging it a lot quicker.

**Comment by otDan** [comment]
```java
private void sit(Player player) {
        UtilPlayer.exemptFromBeingKickedForFlight(player, () -> chair.getPassenger() == player);

        if (loc != null) {
            player.teleport(loc);
        }

        player.sendBlockChange(block.getLocation(), Material.AIR.createBlockData());

        chair.setPassenger(player);
    }
    
    @EventHandler
    public void on(PlayerInteractEvent event) {
        if (event.getHand() != EquipmentSlot.HAND) {
            return;
        }
        if (event.getClickedBlock() == null) {
            return;
        }

        Player player = event.getPlayer();
        Block clicked = event.getClickedBlock();

        if (block.equals(clicked)) {
            event.setCancelled(true);

            runSync(() -> sit(player));
        }
    }
```
