### ISSUE TITLE
Players kick with Velocity (Bedrock players with Geyser)

### ISSUE THREAD

**Issue by Loltik** [GeyserMC/Geyser#4059]
### Describe the bug

Try to log on to the server to play for about an hour and you will be kicked allegedly with your Internet. Kicks all players at the same time. With the new version, all players kick for the same IP and freeze it (USING NEOPROTECT AND HAPROXY IS ENABLED IN VELOCITY) I prescribed iptables -F and so on.

I use Velocity, Minecraft, Java 20, Geyser

NeoProtect says that the problem is not on their side. I have OVH, I have disabled all protection functions and left only a rule for allowing UDP port 19132

### To Reproduce

1. Log in to the server
2. Play for less than an hour
3. You will be kicked from the server

### Expected behaviour

It is necessary for the player to calmly go in and play on the server, because the problem is with the server.

### Screenshots / Videos

No, because the connection is simply broken there, and everyone kicks

### Server Version and Plugins

Velocity 3.2.0-SNAPSHOT (git-37fedf50-b260)
[velocity-dump-2023-08-16-21-48-22.txt](https://github.com/GeyserMC/Geyser/files/12362595/velocity-dump-2023-08-16-21-48-22.txt)

### Geyser Dump

https://dump.geysermc.org/vCBbs2t4EiC0UdssqCKR5dshRtkErrEl

### Geyser Version

2.1.2-SNAPSHOT (git-master-7b409fd) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

Thank you in advance, I hope they will help me (I use Java 20)

**Comment by Camotoy** [comment]
With offline mode being present in this environment, and maybe relevant to the situation, I cannot promise any result. But, have you tried without this NeoProtect to see if the same result occurs?

**Comment by Loltik** [comment]
Hi, I forget to check everything. I'll wake up tomorrow and check and tell you the result, it's just a mistake for almost a month, very strange. I'm sorry in advance if the error is from neoprotect

> With offline mode being present in this environment, and maybe relevant to the situation, I cannot promise any result. But, have you tried without this NeoProtect to see if the same result occurs?

**Comment by Loltik** [comment]
I want to note that more than 15-20 people from the hip start kicking when online

**Comment by Loltik** [comment]
That is, I think it's not NeoProtect, but I'll check

**Comment by Loltik** [comment]
We have checked that the kick is not a neoprotect, I ask for help

**Comment by Loltik** [comment]
Help me please

**Comment by GalkaDiscord** [comment]
I faced the same issue. Please help in solving it.

**Comment by frogglen** [comment]
same issue here with velocity

**Comment by onebeastchris** [comment]
Did you *try* disabling neoprotect and seeing if that fixes it?
Additionally, please send a full log via mclo.gs.

@frogglen are you also using the same setup, or does yours differ? If it does, send a dump + logs too.

**Comment by onebeastchris** [comment]
Closing due to no response.
