### ISSUE TITLE
Invisible floor under void / falling out of world may not kill player

### ISSUE THREAD

**Issue by Camotoy** [GeyserMC/Geyser#406]
**Describe the bug**
In certain instances at Y -40, you are stuck on an invisible floor. (This floor is documented and known to exist in Bedrock, but not in Java) It appears to not be in issue in survival but in creative, and at least one instance in a minigame.

**To Reproduce**
Fall to the void in creative.

**Server Version**
Paper-184

**Geyser Version**
Master 71

**Minecraft: Bedrock Edition Version**
v1.14.60

**Comment by RednedEpic** [comment]
This is a Minecraft bedrock limitation: https://minecraft.gamepedia.com/Void#Bedrock_and_Education_editions.

**Comment by DoctorMacc** [comment]
Correct - I recommend we reopen this to find a loophole around it. If it affects users then we should see if we can hack our way into ignoring it or simulating going down.

**Comment by Heath123** [comment]
I tested and it's possible to teleport the player below the floor and they'll fall from there

**Comment by Heath123** [comment]
So I think this should be reopened

**Comment by DoctorMacc** [comment]
I'm reopening this issue as, while this *is* a Bedrock limitation, it's something we should have the ability to fix.
