### ISSUE TITLE
Bedrock Problem

### ISSUE THREAD

**Issue by GalkaDiscord** [GeyserMC/Geyser#4064]
### Describe the bug

Try to log on to the server to play for about an hour and you will be kicked allegedly with your Internet. Kicks all players at the same time. With the new version, all players kick for the same IP and freeze it (USING NEOPROTECT AND HAPROXY IS ENABLED IN VELOCITY) I prescribed iptables -F and so on.

I use Velocity, Minecraft, Java 20, Geyser

NeoProtect says that the problem is not on their side. I have OVH, I have disabled all protection functions and left only a rule for allowing UDP port 19132

### To Reproduce

1. Log in to the server
2. Play for less than an hour
3. You will be kicked from the server

### Expected behaviour

It is necessary for the player to calmly go in and play on the server, because the problem is with the server.

### Screenshots / Videos

No, because the connection is simply broken there, and everyone kicks

### Server Version and Plugins

Velocity 3.2.0-SNAPSHOT (git-37fedf50-b260)
[velocity-dump-2023-08-16-21-48-22.txt](https://github.com/GeyserMC/Geyser/files/12362595/velocity-dump-2023-08-16-21-48-22.txt)

### Geyser Dump

https://dump.geysermc.org/vCBbs2t4EiC0UdssqCKR5dshRtkErrEl

### Geyser Version

2.1.2-SNAPSHOT (git-master-7b409fd) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

### Minecraft: Bedrock Edition Device/Version

o response

### Additional Context

No response

**Comment by onebeastchris** [comment]
Please send a full log that shows the kick via mclo.gs - you just mentioned an error without specifying one.

**Comment by onebeastchris** [comment]
Closing due to no response.
