### ISSUE TITLE
Unable to run commands from extensions

### ISSUE THREAD

**Issue by rayhanhamada93** [GeyserMC/Geyser#4067]
### Describe the bug

Geyser does not register commands by extensions, with and without permissions.

### To Reproduce

 1. install pickpack/magicmenu
 2 .try using their commands

### Expected behaviour

Geyser players should be able to run those commands.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/74540871/54586ecb-8e00-4d2c-ad2a-00cfc1b2c7e6)
![image](https://github.com/GeyserMC/Geyser/assets/74540871/bc9d41af-0a5c-4ec9-9cc6-634720de8bfd)
![image](https://github.com/GeyserMC/Geyser/assets/74540871/d56dcecb-da4e-43f2-a085-0326438dd61b)

### Geyser Dump

https://dump.geysermc.org/nHBS7lY8JQAHELjmdSe6942WiJAMnbsg

### Geyser Version

Geyser-Fabric, 661a9b4

### Minecraft: Bedrock Edition Device/Version

1.20 Windows 10

**Comment by onebeastchris** [comment]
Can verify. Spigot registers extension commands just fine - Proxy setups, such as Bungee/Velocity aren't able to register bedrock only commands with no permissions properly, but that can be worked around with adding a permission & manually granting it on the proxy's luckperms. (similar to built-in commands)
Fabric for some reason registers built in commands fine; but not those from extensions
