### ISSUE TITLE
some bedrock players causing erros on velocity 

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#4070]
### Describe the bug

bedrock play logs in and see unrender chunks in a certain location cause proxy spam

### To Reproduce

not sure 

### Expected behaviour

for chunks to render and proxy not to error 

### Screenshots / Videos

![2a236318-712c-46aa-bdf8-7bf07e7b1394](https://github.com/GeyserMC/Geyser/assets/92684055/71270ef5-917a-401f-80e5-872db50932b5)
![6b0a6597-8260-41fa-a83f-39bd4d84d930](https://github.com/GeyserMC/Geyser/assets/92684055/42cb7cad-ec87-4a03-bcf1-5786b258888a)

### Server Version and Plugins

[latest.log](https://github.com/GeyserMC/Geyser/files/12404816/latest.log)

### Geyser Dump

https://dump.geysermc.org/ceD73p4u0uYMr4r54XX0i3s37wb2yyCh

### Geyser Version

256

**Comment by shawn695** [comment]
downgraded to Build #1470 (Aug 18, 2023, 3:08:11 AM) and no issue

**Comment by Konicai** [comment]
use a paste website for the log please, eg https://nclo.gs

**Comment by shawn695** [comment]
https://mclo.gs/WNHpnXl

**Comment by shawn695** [comment]
weird i did the same, told them to remove the skulls then the chunk started to render and no more errors, but then they place more back down and issue doesnt come back.....yet

**Comment by Kas-tle** [comment]
Should be resolved by https://github.com/GeyserMC/Geyser/pull/4081. Please download the latest version and let us know if you still run into issues.
