### ISSUE TITLE
Try to avoid the "Can't keep up!" notice when load finished

### ISSUE THREAD

**Issue by MyBlueHorizon** [GeyserMC/Geyser#4071]
### What feature do you want to see added?

Try to avoid the "Can't keep up!" notice when geyser load finished.
Althought it isn't have any bad effort, solve it will be better.
After all, "INFO" is better than "WARN" when you see.

### Are there any alternatives?

No.

**Comment by onebeastchris** [comment]
That message is sent by your server software, not Geyser - there's nothing we can do about it.
