### ISSUE TITLE
Switching armor makes the same equipment when long press the right click a block 

### ISSUE THREAD

**Issue by Ayouuuu** [GeyserMC/Geyser#4072]
### Describe the bug

When a Geyser player right click on a Block to switch equipment it will cause another piece of equipment to be replaced.

### To Reproduce

1. Get two equipments
2. Look a block
3. Long press the right click to switch equipment

### Expected behaviour

You get same equipment but that's fake equipment item.

### Screenshots / Videos

![20230823-182616](https://github.com/GeyserMC/Geyser/assets/31991515/44e95156-4f9b-4a18-90a2-c3dd0f5647d2)

### Server Version and Plugins

This server is running Paper version git-Paper-"07227c9" (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 07227c9 on HEAD)
```text
Plugins (8): floodgate, PlugMan*, ProtocolLib, ProtocolSupportCustomPacket, TestPlugin, Vault, ViaBackwards, ViaVersion
```

### Geyser Dump

https://dump.geysermc.org/oOkzsBxHp4ywurfhfwiFTcx9BjpNZEYM

### Geyser Version

2.2.0(builds 256)

### Minecraft: Bedrock Edition Device/Version

Microsoft Minecraft v1.20.15

**Comment by onebeastchris** [comment]
This is done [on purpose by ViaVersion](https://github.com/ViaVersion/ViaVersion/pull/3267#issuecomment-1474766946). Armor switching was added in 1.19.4, and they don't plan to backport the functionality to older versions - hence, they stop the armour switching. If you want armour quick switching to work, you will need to use 1.19.4 or higher :/
