### ISSUE TITLE
Skins not working 

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#4074]
### Describe the bug

i get a error message everytime a bedrock play joins, and their skins dont work anymore
[Server] INFO [floodgate]: Got disconnected from the skin uploader: failed to find the given code in combination with the verify code

### To Reproduce

use latest version of geyser and floodgate on velocity

### Expected behaviour

for bedrock skins to work 

### Screenshots / Videos

https://mclo.gs/xfBZkkG

proxy logs ^^^

### Geyser Dump

https://dump.geysermc.org/I9vg7jWBbdEgQqYDoGbBXJSUGw89kHc5

### Geyser Version

Build 256

### Minecraft: Bedrock Edition Device/Version

all bedrock devices and clients

**Comment by shawn695** [comment]
just for fun i tried regnerating the key.pm on the proxy and then copy to the back end servers and i till get 
23.08 14:31:25 [Server] INFO [geyser]: Got disconnected from the skin uploader: invalid chain and/or client data
23.08 14:31:25 [Server] INFO [floodgate]: Got disconnected from the skin uploader: failed to find the given code in combination with the verify code

**Comment by Jim-m-y** [comment]
the same problem, it stopped working from one day to the next

**Comment by BackSam6348** [comment]
![image](https://github.com/GeyserMC/Geyser/assets/47339652/98571a3e-b38c-4564-92c3-d2a9effc1836)
![image](https://github.com/GeyserMC/Geyser/assets/47339652/dd10832c-39be-4888-a45a-6ce74ba653ed)
![image](https://github.com/GeyserMC/Geyser/assets/47339652/203218ea-85c5-4085-9402-7bc1a6011946)

Me too same problem

**Comment by DeCodeerHeer** [comment]
Having the same issue too

**Comment by rayhanhamada93** [comment]
I had the same problem too, any fixes?

**Comment by rtm516** [comment]
Fixed in https://github.com/GeyserMC/global_api/commit/5a8a22d013e1f3f5474cf0a5b05a492247b955c0 and deployed to prod
