### ISSUE TITLE
Npc no work left click [Citizens]

### ISSUE THREAD

**Issue by 0372JesusMtz0372** [GeyserMC/Geyser#4087]
### Describe the bug

An npc with an action left clicking the npc runs a command and this doesn't work on Bedrock, only right clicks work (you must press the npc for 3 seconds to execute the action)

### To Reproduce

1. /ncp create NameNpc
2. /npc select (looking at the npc)
3. /npc cmd add -p -l -r spawn (-l = left click and -r = right click)
4. Click only once on the npc (left click) and it does not execute the command 

### Expected behaviour

Just click the npc once and have him execute the command

### Server Version and Plugins

**Plugins:**
BankPlus, BedrockFormShop, BuycraftX, ChatManager, ConditionalEvents, CrazyVouchers, CrossplatForms, DecentHolograms, DeluxeMenus, ExcellentCrates,  Citizens, FastAsyncWorldEdit, floodgate, Geyser-Spigot, GeyserUpdater, LuckPerms, MasterCooldowns, Multiverse-Core, MyCommand, NexEngine, PlaceholderAPI, PlayerKits, ProtocolLib, ServerVariables, spark, SternalBoard, TAB, Themis, Triton, Vault, VoidGen, WorldBorder, WorldGuard, XConomy

**Versión:**
Current: git-Purpur-2045 (MC: 1.20.1)*

### Geyser Dump

https://dump.geysermc.org/Ij4ohvZiv2F63kCnaPRFDL53a87ui2aI

### Geyser Version

Geyser version 2.2.0-SNAPSHOT (git-master-35a8e15) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

### Minecraft: Bedrock Edition Device/Version

Móvil Andorid

**Comment by 0372JesusMtz0372** [comment]
/

**Comment by 0372JesusMtz0372** [comment]
Fix?

**Comment by Jens-Co** [comment]
Bumping issues will not speed up the process. Please be patient until we get around this, thanks.

**Comment by onebeastchris** [comment]
Unable to reproduce using 1.20.40, the latest version of Geyser (#348 at the time of writing), and a Citizens NPC created with the following command:
- NPC created using `/npc create test`
- Command added using `/npc command add give @a apple -l` 
Both the `-l` and `-r` flags seem to work fine for me - on Win10 they work as expected, on Android, left clicking works by just punching the NPC. Right clicking is unfortunately still a long press, but that's expected.

**Comment by onebeastchris** [comment]
Closing due to no response. If this still an issue, create a new post with exact reproduction steps.

**Comment by 0372JesusMtz0372** [comment]
Hello, the left click is the one that does not work on Android, sorry, I just saw this

**Comment by 0372JesusMtz0372** [comment]
1. /npc create test
2. /npc select
3. /npc cmd add -p help -l and /npc cmd add -p help -r

Left click: If I press/hit the npc nothing happens, if I hold down the npc nothing happens 
Right click: If you pressed/hit the npc once nothing happens, if I let you press the npc it executed the /help command 

What I hope will happen is that when the npc receives a left click (-l) command when pressing/hitting the npc once (do not hold down) the command is executed correctly, in the case of right click I think it is working correctly

https://mclo.gs/UpgYVFj
![Screenshot_2024-01-29-03-22-51-54_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/GeyserMC/Geyser/assets/106454514/55d33f52-1bac-4b17-a857-967591022821)

**Comment by onebeastchris** [comment]
Still unable to replicate. Using latest version of citizens (currently, at the time of writing, build 3312), and running the commands you provided works just fine for me.

To ensure both left and right click work, i've created two npc's during my testing.

Right click:
```
[10:49:40 INFO]: .onebeastofchris issued server command: /npc create test
[10:49:56 INFO]: .onebeastofchris issued server command: /npc select
[10:50:39 INFO]: .onebeastofchris issued server command: /npc cmd add -p help -r
[10:50:40 INFO]: .onebeastofchris issued server command: /help
```

Left click:
```
[10:53:39 INFO]: .onebeastofchris issued server command: /npc create testq
[10:53:45 INFO]: .onebeastofchris issued server command: /npc select
[10:54:08 INFO]: .onebeastofchris issued server command: /npc cmd add -p help -l
[10:54:09 INFO]: .onebeastofchris issued server command: /help
```

Tested on both 1.20.51 Windows edition and Android, both work fine for me.

**Comment by 0372JesusMtz0372** [comment]
Does the npc with left click command (-l) when hitting only once execute the /help command in this case?

**Comment by 0372JesusMtz0372** [comment]
Even though I updated citizens and purpur and deleted all the plugins, I have to stop pressing the npc with left click cmd (-l)

**Comment by onebeastchris** [comment]
> Does the npc with left click command (-l) when hitting only once execute the /help command in this case?

Yes.

At this point I'd honestly recommend to try and use a 1.20.4 paper server with just Geyser, Floodgate and citizens installed on it. If that still doesn't work there, please share an IP/port I can join to test it out

**Comment by 0372JesusMtz0372** [comment]
You were right my dear, using paper works

**Comment by onebeastchris** [comment]
Seems like it, since it does work on a clean paper server. That's on you to figure out though - you can use the steps below to do so.

If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.

Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by 0372JesusMtz0372** [comment]
Is there a possibility that this will fail for the world? I just created a new world and npc and this one works

**Comment by 0372JesusMtz0372** [comment]
Do you want to go in and see it? It is on my normal server

**Comment by onebeastchris** [comment]
That won't be necessary. Since the issue does not occur on a clean 1.20.4 paper server, this is an incompatibility with some other plugin - i doubt that the world itself would prevent it.

**Comment by 0372JesusMtz0372** [comment]
Believe me, it's the world, I can give you the IP so you can see

**Comment by 0372JesusMtz0372** [comment]
On the same server that fails I made a new world and moved the npc, in the new world it works and in the other it doesn't
