### ISSUE TITLE
Users get kicked when a bedrock player joins, Proxy set up

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#4088]
### Describe the bug

I can have like 10 members on and no issues, all the sudden a bedrock player joins and users get disconected. this happens randomly and with a random amount of players online, this has happen a few times to me. with a proxy set up. some days are good and some days are a pain, i use apex hosting for all my servers, i maintain 20tps and around 8-10mspt with 10-12 members on. yes i know a new build just came out a hour ago, i assure this issue has been on going for a while. i have also tried bungee, velocity, and now im on waterfall. and cant seem to get rid of this issue unless i run with out a proxy

### To Reproduce

randomly happens when a bedrock user joins, every time its when a bedrock user joins.

### Expected behaviour

for no one to get kicked when a bedrock user joins

### Screenshots / Videos

7.08 20:51:29 [Server] INFO UUID of player .Mariposa282 is 00000000-0000-0000-0009-01f2fafdeac2
27.08 20:51:30 [Server] INFO [floodgate] Floodgate player logged in as .Mariposa282 joined (UUID: 00000000-0000-0000-0009-01f2fafdeac2)
27.08 20:51:30 [Connect] User .Mariposa282, IP 158.62.138.198
27.08 20:51:30 [Server] INFO [floodgate] Floodgate player logged in as .Mariposa282 disconnected
27.08 20:51:30 [Server] INFO [floodgate] Floodgate player logged in as .silentbutginger disconnected
27.08 20:51:30 [Server] INFO [floodgate] Floodgate player logged in as .StealthPossum30 disconnected
27.08 20:51:30 [Server] INFO [floodgate] Floodgate player logged in as .cosmicecho92 disconnected
27.08 20:51:30 [Multicraft] .Mariposa282 ran command Message of the Day
27.08 20:51:30 [Server] INFO [⛏] [Noob] .Mariposa282 Joined the server
27.08 20:51:30 [Disconnect] User Blazzin0420 has disconnected, reason: Disconnected
27.08 20:51:30 [Server] INFO [OWNER] Blazzin0420 Has left the Server !
27.08 20:51:30 [Disconnect] User KikiTheGame9444 has disconnected, reason: Disconnected
27.08 20:51:30 [Server] INFO [STAFF]KikiTheGame9444 Has left the Server !
27.08 20:51:30 [Disconnect] User .StealthPossum30 has disconnected, reason: Disconnected
27.08 20:51:30 [Server] INFO [MOD].StealthPossum30 Has left the Server !
27.08 20:51:30 [Disconnect] User .silentbutginger has disconnected, reason: Disconnected
27.08 20:51:30 [Server] INFO [Duke] .silentbutginger Has left the Server !
27.08 20:51:30 [Disconnect] User SKYEink has disconnected, reason: Disconnected
27.08 20:51:30 [Server] INFO [VIP]SKYEink Has left the Server !
27.08 20:51:30 [Disconnect] User .cosmicecho92 has disconnected, reason: Disconnected
27.08 20:51:30 [Server] INFO [Grinder] .cosmicecho92 Has left the Server !
27.08 20:51:30 [Disconnect] User .Mariposa282 has disconnected, reason: Disconnected
27.08 20:51:30 [Server] INFO [Noob] .Mariposa282 Has left the Server !

### Server Version and Plugins

proxy logs https://mclo.gs/nEBIOvJ
main back end server logs https://mclo.gs/OMhTY8p

Plugins on main back end server 
BetterShulkerBoxes, BetterStructures, ChatGames, Chunky, ChunkyBorder, Citizens, CMILib, CommandPanels, Coordinates, CoreProtect, CrazyEnchantments, CrazyEnvoys, CrazyVouchers, DailyRewardsPlus, DeluxeMenus, *DiscordEconomyBridge, DiscordSRV, DiscordSRVUtils, DynDeath, dynmap, *Dynmap-WorldGuard, Essentials, EssentialsChat, EssentialsSpawn, floodgate, GemsEconomy, GHomeGuiForEssentialsX, Graves, GSit, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, JetsAntiAFKPro, JetsMinions, Jobs, Lands, LevelledMobs, LotterySix, LuckPerms, MoneyFromMobs, MoreMobHeads, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, MyPet, MyPetGUI2, Negativity, NewbsCreative, *NightVision, PlaceholderAPI, Plot2Dynmap, PlotSquared, ProCosmetics, Quests, ReleaseCommand, SimplePortals, SimpleSurvivalStats, sleep-most, SlotMachine, SteveGPT, TAB-Bridge, TabTPS, Terra, TPARequestGUI, UpgradeableHoppers, UpgradeableSpawners, Vault, ViaVersion, VoidGen, WildRegeneration

Plugins on proxy
geyser-bungee, floodgate-bungee, luckperms-bungee, miniMOTD-bungee, TAB
Also with geyser extentions
Xboxbroadcaster, hidecommand

### Geyser Dump

https://dump.geysermc.org/2QWgCCQguu1hzimpSLflKwzKITfRRi8w

### Geyser Version

build 259

### Minecraft: Bedrock Edition Device/Version

all clients 

### Additional Context

players get this error produced by the proxy, not by the back end server, back end shows no errors just players getting diconected when that one random bedrock player joins
![image](https://github.com/GeyserMC/Geyser/assets/92684055/58b53286-055b-457a-9dc4-5f98f79fd357)

**Comment by shawn695** [comment]
build 259 sorry

**Comment by Camotoy** [comment]
Please send a new Geyser dump with the latest Geyser build to verify the bug does not exist on that build.

**Comment by shawn695** [comment]
lmao grrr, it existed on previous builds. but sure i can update and then wait for this random event to happen and send the geyser dump

**Comment by shawn695** [comment]
updated !
https://dump.geysermc.org/lVBGDVJU5ie605LNaUHfiXZthe6LFcIq

**Comment by shawn695** [comment]
https://github.com/GeyserMC/Geyser/assets/92684055/a7498c68-02ee-408a-8ddb-50de87f759f1
might be hard to see but as u can see i couldnt get online and no error on back end and the proxy kept tossing the trasnfer back to fall back server. u could see i pointed out the last bedrcok player that joined. i got them to leave and then i was able to sign in and then they joined afterwords

**Comment by shawn695** [comment]
i just notice in the video when the bedrock player that was holding up other users from joining diconnect they produced this when disconnecting
28.08 14:22:47 [Server] WARN [/74.14.71.155:0|.MissMoo7177] -> UpstreamBridge - ClosedChannelException: null
28.08 14:22:47 [Server] INFO [.MissMoo7177] disconnected with: ClosedChannelException : null @ io.netty.channel.local.LocalChannel:368

**Comment by shawn695** [comment]
and also again as u can see here, .songoku6175 connected then a few players got kicked. only after goku left where those players able to rejoin 

28.08 16:32:59 [Server] INFO [floodgate]: Floodgate player logged in as .SonGoku6175 joined (UUID: 00000000-0000-0000-0009-01f6b46b174d)
28.08 16:32:59 [Server] INFO [.Bakugo20009199] disconnected with: The server you were previously on went down, you have been connected to a fallback server
28.08 16:32:59 [Server] INFO [floodgate]: Floodgate player logged in as .Bakugo20009199 disconnected
28.08 16:32:59 [Server] INFO [Geyser-BungeeCord]: Bakugo20009199 has disconnected from the Java server because of The server you were previously on went down, you have been connected to a fallback server
28.08 16:32:59 [Server] INFO [/71.236.216.130:0|.Bakugo20009199] -> UpstreamBridge has disconnected
28.08 16:32:59 [Server] WARN [Geyser-BungeeCord]: Haven't received PlayerListEntry packet before spawning player! We ignore the player 00000000-0000-0000-0009-01f0be5505bd
28.08 16:32:59 [Server] INFO [.cosmicecho92] disconnected with: The server you were previously on went down, you have been connected to a fallback server
28.08 16:32:59 [Server] INFO [floodgate]: Floodgate player logged in as .cosmicecho92 disconnected
28.08 16:32:59 [Server] INFO [Geyser-BungeeCord]: cosmicecho92 has disconnected from the Java server because of The server you were previously on went down, you have been connected to a fallback server
28.08 16:32:59 [Server] INFO [/24.162.192.198:0|.cosmicecho92] -> UpstreamBridge has disconnected
28.08 16:33:20 [Server] INFO [Geyser-BungeeCord]: /24.162.192.198:54571 tried to connect!
28.08 16:33:21 [Server] INFO [Geyser-BungeeCord]: Player connected with username cosmicecho92
28.08 16:33:21 [Server] INFO [Geyser-BungeeCord]: cosmicecho92 (logged in as: cosmicecho92) has connected to the Java server
28.08 16:33:21 [Server] INFO [floodgate]: Floodgate player logged in as .cosmicecho92 joined (UUID: 00000000-0000-0000-0009-01f24d14b205)
28.08 16:33:21 [Server] INFO [.cosmicecho92] disconnected with: The server you were previously on went down, you have been connected to a fallback server
28.08 16:33:21 [Server] INFO [floodgate]: Floodgate player logged in as .cosmicecho92 disconnected
28.08 16:33:21 [Server] INFO [Geyser-BungeeCord]: cosmicecho92 has disconnected from the Java server because of The server you were previously on went down, you have been connected to a fallback server
28.08 16:33:21 [Server] INFO [/24.162.192.198:0|.cosmicecho92] -> UpstreamBridge has disconnected
28.08 16:33:28 [Server] INFO [LuckPerms]: [Messaging] Received user update ping for '.songoku6175' with id: f64601f6-f190-417e-8d13-551a413beb78
28.08 16:33:40 [Server] INFO [Geyser-BungeeCord]: /71.236.216.130:60956 tried to connect!
28.08 16:33:42 [Server] INFO [Geyser-BungeeCord]: Player connected with username Bakugo20009199
28.08 16:33:42 [Server] INFO [Geyser-BungeeCord]: Bakugo20009199 (logged in as: Bakugo20009199) has connected to the Java server
28.08 16:33:42 [Server] INFO [floodgate]: Floodgate player logged in as .Bakugo20009199 joined (UUID: 00000000-0000-0000-0009-01f0be5505bd)
28.08 16:33:43 [Server] INFO [.Bakugo20009199] disconnected with: The server you were previously on went down, you have been connected to a fallback server
28.08 16:33:43 [Server] INFO [floodgate]: Floodgate player logged in as .Bakugo20009199 disconnected
28.08 16:33:43 [Server] INFO [/71.236.216.130:0|.Bakugo20009199] -> UpstreamBridge has disconnected
28.08 16:33:43 [Server] INFO [Geyser-BungeeCord]: Bakugo20009199 has disconnected from the Java server because of Connection closed.
28.08 16:34:33 [Server] INFO [Geyser-BungeeCord]: /24.162.192.198:58218 tried to connect!
28.08 16:34:34 [Server] INFO [Geyser-BungeeCord]: Player connected with username cosmicecho92
28.08 16:34:34 [Server] INFO [Geyser-BungeeCord]: cosmicecho92 (logged in as: cosmicecho92) has connected to the Java server
28.08 16:34:34 [Server] INFO [floodgate]: Floodgate player logged in as .cosmicecho92 joined (UUID: 00000000-0000-0000-0009-01f24d14b205)
28.08 16:34:34 [Server] INFO [.cosmicecho92] disconnected with: The server you were previously on went down, you have been connected to a fallback server
28.08 16:34:34 [Server] INFO [floodgate]: Floodgate player logged in as .cosmicecho92 disconnected
28.08 16:34:34 [Server] INFO [Geyser-BungeeCord]: cosmicecho92 has disconnected from the Java server because of The server you were previously on went down, you have been connected to a fallback server
28.08 16:34:34 [Server] INFO [/24.162.192.198:0|.cosmicecho92] -> UpstreamBridge has disconnected
28.08 16:34:56 [Server] INFO [Geyser-BungeeCord]: /71.236.216.130:60956 tried to connect!
28.08 16:34:58 [Server] INFO [Geyser-BungeeCord]: Player connected with username Bakugo20009199
28.08 16:34:58 [Server] INFO [Geyser-BungeeCord]: Bakugo20009199 (logged in as: Bakugo20009199) has connected to the Java server
28.08 16:34:58 [Server] INFO [floodgate]: Floodgate player logged in as .Bakugo20009199 joined (UUID: 00000000-0000-0000-0009-01f0be5505bd)
28.08 16:34:59 [Server] INFO [.Bakugo20009199] disconnected with: The server you were previously on went down, you have been connected to a fallback server
28.08 16:34:59 [Server] INFO [floodgate]: Floodgate player logged in as .Bakugo20009199 disconnected
28.08 16:34:59 [Server] INFO [Geyser-BungeeCord]: Bakugo20009199 has disconnected from the Java server because of Connection closed.
28.08 16:34:59 [Server] INFO [/71.236.216.130:0|.Bakugo20009199] -> UpstreamBridge has disconnected
28.08 16:35:03 [Server] INFO [Geyser-BungeeCord]: SonGoku6175 has disconnected from the Java server because of Bedrock client disconnected
28.08 16:35:03 [Server] INFO [floodgate]: Floodgate player logged in as .SonGoku6175 disconnected
28.08 16:35:03 [Server] INFO [/94.246.152.175:0|.SonGoku6175] -> UpstreamBridge has disconnected
28.08 16:35:08 [Server] INFO [Main] (5): .Capone983331, .GTAFluffy1996, .soonergrl1310, Blazzin0420, SKYEink
28.08 16:36:31 [Server] INFO [Geyser-BungeeCord]: /71.236.216.130:60956 tried to connect!
28.08 16:36:32 [Server] INFO [Geyser-BungeeCord]: /24.162.192.198:53203 tried to connect!
28.08 16:36:33 [Server] INFO [Geyser-BungeeCord]: Player connected with username Bakugo20009199
28.08 16:36:33 [Server] INFO [Geyser-BungeeCord]: Bakugo20009199 (logged in as: Bakugo20009199) has connected to the Java server
28.08 16:36:33 [Server] INFO [Geyser-BungeeCord]: Player connected with username cosmicecho92
28.08 16:36:33 [Server] INFO [Geyser-BungeeCord]: cosmicecho92 (logged in as: cosmicecho92) has connected to the Java server
28.08 16:36:33 [Server] INFO [floodgate]: Floodgate player logged in as .cosmicecho92 joined (UUID: 00000000-0000-0000-0009-01f24d14b205)
28.08 16:36:33 [Server] INFO [floodgate]: Floodgate player logged in as .Bakugo20009199 joined (UUID: 00000000-0000-0000-0009-01f0be5505bd)

**Comment by Amuria-Codes** [comment]
I have the same issue 

with the newst version from / bungeecord ( Waterfalls ) and Geyser Bungee and Floodgate Bunge and Floodgate Spigot

**Comment by onebeastchris** [comment]
Going to close this since it's a the same issue as https://github.com/https://github.com/GeyserMC/Geyser/issues/4116. (that issue is newer, let's move there)
Can you try https://github.com/GeyserMC/Geyser/issues/4116#issuecomment-1844835919 too and see if that PR build resolves the kicking issue?
