### ISSUE TITLE
funny number

### ISSUE THREAD

**Issue by eiwgogoogwe24** [GeyserMC/Geyser#4089]
### Describe the bug

funny number

### To Reproduce

69. funny number

### Expected behaviour

funny number

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/143397600/322c7c20-e769-4e59-b931-5831c4e641c9)

### Geyser Version

1.2.0-SNAPSHOT

**Comment by onebeastchris** [comment]
Thanks, but no thanks. Missing reproduction steps :)
