### ISSUE TITLE
Bedrock players crashing after joining

### ISSUE THREAD

**Issue by eduardo1299** [GeyserMC/Geyser#4099]
### Describe the bug

When a bedrock player joins, the game instantly crashes with a mojang loading screen, or after a few minutes playing.

### To Reproduce

1. Open minecraft bedrock
2. Join the geyser mc server
3. Play for a few minutes or just join
4. See a mojang loading screen flash
5. Crash

### Expected behaviour

not crashing

### Geyser Version

the lastet

**Comment by Konicai** [comment]
Please fill in every section of the bug report. Also report any resource packs that you're using

**Comment by eduardo1299** [comment]
Server version: 1.20.1
Plugins: Aurelium skills, fastleafdecay, healthbar, geyser mc, floodgate, simple tpa, set home
Resource packs: gal lab and gen's assets
Data packs: better babies, dev resources, dungeons and taverns, hephaes tools, jermsy's world overhaul
