### ISSUE TITLE
Furnace burning animation to fast for slower burning custom recipes

### ISSUE THREAD

**Issue by ofunny** [GeyserMC/Geyser#4104]
### Describe the bug

I'm not sure if that is fixable at all, but I report it for now. If a plugin (like Itemsadder) registers a custom Furnace recipe with a longer time for cooking, the arrow showing the the progress update still fill with vanilla speed. So the arrow will indicate that the cooking progress has finished way before it actually will finish. 

The resulting problem is, that most player than think that the recipe is not cookable at all and report it as a bug.

### To Reproduce

1. Use a custom Furnace recipe with longer cooking time
2. Compare the arrow fill speed in Bedrock with the speed in Java

### Expected behaviour

Adjusted arrow fill speed as in Java.

### Screenshots / Videos

https://resource.ofunny.world/dev/issuereports/slow_burning.mp4

### Server Version and Plugins

Paper 1.20.1 (build 167)
Itemsadder 3.5.0c-r4

### Geyser Dump

[Geyser Version 2.2.0-SNAPSHOT (git-master-bf81fc1) (Java: 1.20, Bedrock: 1.20.0 - 1.20.10)](https://dump.geysermc.org/GWrwFwEHx2y719MI2XdiNrqdBSOe1tS0)

### Geyser Version

Geyser Version 2.2.0-SNAPSHOT (git-master-bf81fc1) (Java: 1.20, Bedrock: 1.20.0 - 1.20.10)

### Minecraft: Bedrock Edition Device/Version

1.20.15

**Comment by onebeastchris** [comment]
https://wiki.bedrock.dev/loot/recipes.html
> The time required to heat an item is set by the used block and is unchangeable.

looks like it's hardcoded on Bedrock :/

**Comment by onebeastchris** [comment]
Closing this issue in favor of it being documented on our current limitations page: https://wiki.geysermc.org/geyser/current-limitations/

**Comment by Julmik647** [comment]
> https://wiki.bedrock.dev/loot/recipes.html
> 
> > The time required to heat an item is set by the used block and is unchangeable.
> 
> looks like it's hardcoded on Bedrock :/

"block" means furmance? If it's do, we can replace furnace with custom Item with furnace texture for a moment od smelting custom item
