### ISSUE TITLE
Custom recipes not showing up in the Bedrock knowledge book

### ISSUE THREAD

**Issue by ofunny** [GeyserMC/Geyser#4105]
### Describe the bug

I promise, it will be the last bug report today, but custom recipes to not show up within Bedrocks knowledge book.
Might be hardcoded again or maybe I do smth wrong, but the video is linked below.

### To Reproduce

1. Implement custom recipes via plugin on Java
2. Make sure you have unlocked the recipe in your knowledge book
(Get the ingredients and craft once so it's 100% there)
3. Try to find the recipe in Bedrock's knowledge book

### Expected behaviour

Being able to see custom recipes within Bedrock's knowledge book.

### Screenshots / Videos

https://resource.ofunny.world/dev/issuereports/missing_recipes.mp4

### Server Version and Plugins

Geyser Version 2.2.0-SNAPSHOT (git-master-bf81fc1) (Java: 1.20, Bedrock: 1.20.0 - 1.20.10)

### Geyser Dump

https://dump.geysermc.org/GWrwFwEHx2y719MI2XdiNrqdBSOe1tS0

### Geyser Version

Geyser Version 2.2.0-SNAPSHOT (git-master-bf81fc1) (Java: 1.20, Bedrock: 1.20.0 - 1.20.10)

### Minecraft: Bedrock Edition Device/Version

1.20.15

### Additional Context

Paper 1.20.1 (build 167)
Itemsadder 3.5.0c-r4

**Comment by onebeastchris** [comment]
This should be fixable :)
Can you add some kind of full reproduction steps with e.g. an example recipe?
There are other bugs similar to this reported on the issue tracker; thus far, no reproduction steps were provided that could help us fix this

**Comment by Boba194230** [comment]
I’ve got a similar issue (using an nbt recipe mod). I’d be able to post some example recipes if you wanted

**Comment by Boba194230** [comment]
[_blaze.json](https://github.com/GeyserMC/Geyser/files/13059892/_blaze.json)
The recipe is given to players with recipe give @s wasd.diamond:items/_blaze

**Comment by Boba194230** [comment]
Works fine with java players just not bedrock

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/issues/4279 going to close this issue in favor of the linked one - they're essentially the same. Thanks for reporting!
