### ISSUE TITLE
Getting 'Connecting:ReadTimeoutException: null' when trying to switch server on bungee

### ISSUE THREAD

**Issue by liquidman228** [GeyserMC/Geyser#4107]
### Describe the bug

All that helps is restarting the server that is impossible to join. I have the following system: authorization server, lobby and then game servers. It often even happens that players are not let into the lobby after authorization, and they just get stuck because of an error. Usually players can log into the lobby, but when they try to connect to the game server they get the error above

What I tried and it didn't help:
- Updating geyser
- Switching back from Waterfall to Bungeecord

### To Reproduce

1. Join the bungeecord server
2. Somehow activate the server change trigger
3. Get the timeout error

### Expected behaviour

Normal migration between servers

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/93479046/dff0f4f3-3c9a-48d7-9972-e03d8240d7b8)

### Server Version 

Bungee: git:BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:94ea027:1726
Auth: git-Paper-215 (MC: 1.19.2)
Lobby: git-Paper-215 (MC: 1.19.2)
Survival servers: git-Purpur-1980 (MC: 1.19.4)*

### Geyser Dump

https://dump.geysermc.org/yh3ESDHhZnBeo62WkuLm9X4FeGVl4Puk

### Geyser Version

2.2.0-SNAPSHOT (git-master-bf81fc1) (Java: 1.20, Bedrock: 1.20.0 - 1.20.10)

### Additional Context

This problem first appeared once a week and now every day. I've also noticed that it happens after auto restarting the game servers. It turns out you have to restart twice to get it to work properly, lol

**Comment by liquidman228** [comment]
UPDATE: It doesn't happen after a restart, it happens on its own at about the same time. And of course it only affects bedrock players

**Comment by hotspuraz** [comment]
I am also having this issue on a single realm but not the others and we can't figure it out either.

**Comment by liquidman228** [comment]
Any advice?

**Comment by onebeastchris** [comment]
Does this issue persist on the latest Geyser version?
If so, please run `geyser dump logs` in your server console & send the link you get here - it'll show what Geyser version you're on & attach logs (without ips) so we can check for further errors.

**Comment by liquidman228** [comment]
> Does this issue persist on the latest Geyser version? If so, please run `geyser dump logs` in your server console & send the link you get here - it'll show what Geyser version you're on & attach logs (without ips) so we can check for further errors.

Yeah, still getting this on the latest version
https://dump.geysermc.org/txOtPkC2i4g9UBdxtuFkLqJmzF5JW5E5

Game server logs are useless, because the console doesn't give any errors, like the player doesn't even connect to it. And the proxy console only shows that the player seems to connect to another server, and then disconnects with the error specified in the beginning

**Comment by onebeastchris** [comment]
Unfortunately, you are running paid close source software (flamecord) which we can't properly debug, aswell as in offline mode.
Are you able to reproduce the issue with e.g. Waterfall or BungeeCord & online mode?

**Comment by liquidman228** [comment]
> Unfortunately, you are running paid close source software (flamecord) which we can't properly debug, aswell as in offline mode. Are you able to reproduce the issue with e.g. Waterfall or BungeeCord & online mode?

I've tried Bungeecord and Waterfall - same problem. Can't replicate with online mode unfortunately. It was fine before and everything worked. I haven't changed any settings with the proxy server

**Comment by hotspuraz** [comment]
> Any advice?

Switching to standalone has fixed this issue for myself and several other servers who have had the issue

**Comment by liquidman228** [comment]
> > Any advice?
> 
> Switching to standalone has fixed this issue for myself and several other servers who have had the issue

Omg, i forgot about the standalone. Gonna switch and test it out for a few days. Thank you

**Comment by liquidman228** [comment]
Okay, so switching to standalone didn't fixed the issue. Getting the same results. I think this is a spigot server issue (some plugin or else)

**Comment by liquidman228** [comment]
Things are getting worse. Now this problem forces me to restart the servers every 3 hours. I wonder what will happen next

**Comment by onebeastchris** [comment]
Is this still happening?

**Comment by liquidman228** [comment]
> Is this still happening?

Nope. It was fixed by itself. Weird

**Comment by onebeastchris** [comment]
Okay, ill close this issue then.
