### ISSUE TITLE
Can't craft Wheat from Bale after Geyser build #1481

### ISSUE THREAD

**Issue by kolderz** [GeyserMC/Geyser#4110]
### Describe the bug

Can't craft Wheat from Bale after Geyser build 1481

### To Reproduce

1. Use  Geyser version 2.2.0-SNAPSHOT (git-master-acf24d4) (Java: 1.20, Bedrock: 1.20.0 - 1.20.10)
2. Craft Wheat using Bale

### Expected behaviour

Crafting Wheat from Bale

### Server Version and Plugins

git-Purpur-1632 (MC: 1.18.2)

### Geyser Version

 Geyser version 2.2.0-SNAPSHOT (git-master-acf24d4) (Java: 1.20, Bedrock: 1.20.0 - 1.20.10)

**Comment by onebeastchris** [comment]
Fixed in https://github.com/GeyserMC/Geyser/commit/c67d50c13ed90f79e92c0390bb7b2fa571b0b64a - please update Geyser to the latest version. Thanks for the bug report!
