### ISSUE TITLE
can not close player inventory

### ISSUE THREAD

**Issue by SpEeD11** [GeyserMC/Geyser#4121]
### Describe the bug

when you try to open an inventory (such as a menu gui) for a bedrock player while they have their own player inventory open, the new inventory doesnt open, but the server thinks it has. The player is then stuck unable to open any inventories (even their own) until relog.

a fix or a workaround to be able to force close a bedrock client's player inventory would be appreciated

using geyser and floodgate on proxy (waterfall)

### To Reproduce

1. open player inventory on bedrock client
2. do player.closeInventory(); then player.openInventory(menu), while the player inventory is still open. On java clients and server-side, the player closes their player inventory and opens the menu inventory
3. on bedrock client, the player inventory stays open, but the server thinks they have the menu inventory open. If the player then closes their inventory they can no longer open any inventory because the server thinks they are still inside the menu inventory. the only way to fix this is to do something that forces a closeInventory event, such as teleporting.

### Expected behaviour

the player should close their inventory and open the new inventory

### Geyser Dump

https://dump.geysermc.org/4aX28wRChDSetlqXK37Bw322CciobjCi

### Geyser Version

see dump

### Minecraft: Bedrock Edition Device/Version

Windows 10, Latest version

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaOpenScreenTranslator.java#L73-L81

https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/translator/protocol/java/inventory/JavaContainerCloseTranslator.java

Weird why this wouldn't work - Geyser should close inventories properly when the appropriate Java packet is sent, and when opening a new inventory, there's an explicit check for whether an inventory is already open (which would then be closed).

Does this issue occur only when trying to override/close the player inventory, or does it also occur with any other inventory (e.g. furnaces/chests/anvils etc)?

**Comment by SpEeD11** [comment]
it works correctly when going between any inventories except the player one, probably related to the player inventory being client sided.

I was able to replicate the bug on several large servers running geyser. its even easier with higher ping, all you have to do is interact with something that would open a gui, then quickly open your inventory before the gui opens. the double chest for the gui stays, and pressing e no longer does anything

only thing i can think of is there is something weird with my client, but i'm just using the latest version of 'minecraft for windows' from the launcher

**Comment by lucasfrederico** [comment]
It's happening to me too. I have an item that when you open your inventory and click on it, within your inventory, an inventory opens to show information about it.

The problem is that the inventory doesn't open. I later discovered that if I click on the item and quickly close my inventory, the GUI opens. I think there is a problem opening a GUI for a player when their inventory is open.

https://imgur.com/a/jTfR8Pz

**Comment by onebeastchris** [comment]
Hey @lucasfrederico @SpEeD11 - could you try the Geyser build in the linked PR, and see if that resolves this issue?
You can download them under the `Checks` tab :)
