### ISSUE TITLE
The observer is not showing the correct direction when placed.

### ISSUE THREAD

**Issue by kolderz** [GeyserMC/Geyser#4124]
### Describe the bug

The observer is not showing the correct direction when placed.

### To Reproduce

1. Place The observer in any direction

### Expected behaviour

Correct observer direction placed

### Screenshots / Videos

 Java POV: [https://imgur.com/z2fmw8Q](https://imgur.com/z2fmw8Q)
 Bedrock POV: [https://imgur.com/9nDq18i](https://imgur.com/9nDq18i)

### Server Version and Plugins

git-Purpur-1632 (MC: 1.18.2)
Plugins (2): floodgate, ViaVersion

### Geyser Version

Geyser version 2.2.0-SNAPSHOT (git-master-69f89ed) (Java: 1.20, Bedrock: 1.20.0/1.20.1 - 1.20.30)

### Minecraft: Bedrock Edition Device/Version

1.20.15 on PC

**Comment by onebeastchris** [comment]
Please attach a geyser dump - run `geyser dump` in the server console, and send the link you get here

**Comment by onebeastchris** [comment]
Do you have Geyser only on the proxy, or somewhere else too?
This looks like an already [fixed bug](https://dump.geysermc.org/mzSabacmFllO9yHVv6JCBtbgbfbMazbl)

**Comment by onebeastchris** [comment]
That's perfect. There's a chance [1.20.30](https://github.com/GeyserMC/Geyser/commit/9a8015e8b68e7710e0eb703e43d50c39d2204447) support broke it, I'll to replicate it in a few hours

**Comment by Konicai** [comment]
I need to backport https://github.com/CloudburstMC/BlockStateUpdater/pull/7 to the 1.20.10 updater.
