### ISSUE TITLE
UUID Changed when Player Offline

### ISSUE THREAD

**Issue by KevinAdhaikal** [GeyserMC/Geyser#4125]
### Describe the bug

Hello, why UUID Changed when Minecraft Bedrock Player Offline? is there anything to make UUID will not change when Player Offline?

Sorry for bad grammar

### To Reproduce

1. using uuid finder plugin
2. /uuid offlineplayerbedrock

### Expected behaviour

UUID will same even if the Player is Offline

### Server Version and Plugins

This server is running Paper version git-Paper-169 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) 

### Geyser Version

2.2.0-SNAPSHOT (git-master-bf81fc1) 

### Minecraft: Bedrock Edition Device/Version

1.20.15 Android

**Comment by Jens-Co** [comment]
Cracked/Offline players will never have a valid uuid, A Floodgate uuid (valid geyser uuid) is generateed from a microsoft XUID and thus what you are asking is not possible.

Thanks

**Comment by KevinAdhaikal** [comment]
> Cracked/Offline players will never have a valid uuid, A Floodgate uuid (valid geyser uuid) is generateed from a microsoft XUID and thus what you are asking is not possible.
> 
> note: if you are not talking about cracked/offline accounts please net me know and ill reopen this. can you please tell me the persons uuid + gamertag and the mismatched uuid from that same player?

yeah, i am using offline mode, im sorry 🙏 

but, if i am using online mode, it will get valid UUID?

**Comment by Jens-Co** [comment]
> > Cracked/Offline players will never have a valid uuid, A Floodgate uuid (valid geyser uuid) is generateed from a microsoft XUID and thus what you are asking is not possible.
> > note: if you are not talking about cracked/offline accounts please net me know and ill reopen this. can you please tell me the persons uuid + gamertag and the mismatched uuid from that same player?
> 
> yeah, i am using offline mode, im sorry 🙏 but, if i am using online mode, it will get valid UUID?
> 
> and btw, thanks for the information

Correct, if you use online mode the uuid will be a valid one and you will be able to lookup the uuid with GeyserAPI or with MCProfile.io

**Comment by KevinAdhaikal** [comment]
> > > Cracked/Offline players will never have a valid uuid, A Floodgate uuid (valid geyser uuid) is generateed from a microsoft XUID and thus what you are asking is not possible.
> > > note: if you are not talking about cracked/offline accounts please net me know and ill reopen this. can you please tell me the persons uuid + gamertag and the mismatched uuid from that same player?
> > 
> > 
> > yeah, i am using offline mode, im sorry 🙏 but, if i am using online mode, it will get valid UUID?
> > and btw, thanks for the information
> 
> Correct, if you use online mode the uuid will be a valid one and you will be able to lookup the uuid with GeyserAPI or with MCProfile.io

ohh, thanks for the information
