### ISSUE TITLE
Placeholders

### ISSUE THREAD

**Issue by SimpleWayx** [GeyserMC/Geyser#4126]
### What feature do you want to see added?

Placeholders to get version of what the client has in order to show a particular scoreboard thanks to conditional events.

### Are there any alternatives?

I believe there was a plugin but is better if is supported by geyser it self.

**Comment by onebeastchris** [comment]
https://github.com/rtm516/FloodgatePlaceholders there's a plugin for that which you can use. While it theoretically could be added to Geyser itself, it wouldnt work on some platforms anyways, so an external one is probably the best option - the Geyser API exposes plenty of info about connected clients :p
