### ISSUE TITLE
BLOCK_DISPLAY

### ISSUE THREAD

**Issue by viktorkozachok21** [GeyserMC/Geyser#4127]
### What feature do you want to see added?

[WARN]: [Geyser-Spigot] Could not find an entity definition with type BLOCK_DISPLAY

geyser version 2.2.0
minecraft version 1.20.1

### Are there any alternatives?

nothing

**Comment by onebeastchris** [comment]
Item and Block displays are currently not implemented in Geyser, they simply don't exist on Bedrock :/
A workaround implementing them in some capacity should come at some point, but it will take time.

Closing as duplicate of https://github.com/GeyserMC/Geyser/issues/3810 - thanks anyways.
