### ISSUE TITLE
Pack that are encrypted won't load for console users 

### ISSUE THREAD

**Issue by SamGamerYT** [GeyserMC/Geyser#4133]
### Describe the bug

Custom pack loading with key isn't working properly for playstations users
however the pack works fine for mobile/windows 10 (Yes the key is within "packs" folder)
Seems to be an issue after the new release

**Common Questions Asked:**
Same Pack and Key name?
> Yes pack name is UI.mcpack and key name is UI.mcpack.key

On the latest version of geyser?
> Absolutely, As latest as it can be but not on dev builds

Have you tried on mobile/bedrock?
> Yup! it works on mobile and bedrock without a problem

Does the download option appears on console?
> Yup! it does and it does gets downloaded and the other packs do work properly, just excluding the one that is protected

### To Reproduce

Create a pack thats protected with a Key
Name the pack ui.mcpack and the key ui.mcpack.keythat'skey that's

### Expected behaviour

The pack will load properly and the UI will show up

### Server Version and Plugins

[18:49:41 INFO]: Current: git-Purpur-2054 (MC: 1.20.1)*
Latest Velocity
Latest Geyser (Velocity)
Latest Floodgate (Velocity)

### Geyser Dump

https://dump.geysermc.org/7PcSWviALtN7E54Rptu7fXs9O3IU62IA

### Geyser Version

Commit: 7a28ef5 Branch: master

### Minecraft: Bedrock Edition Device/Version

Windows 10, Xbox, PS, Mobile

**Comment by onebeastchris** [comment]
Considering we haven't changed anything about how encrypted (or any packs at all) are loaded, this might be a client bug.. who knows
Does it work for console players who aren't on 1.20.30?

**Comment by onebeastchris** [comment]
Closing due to no further response.
