### ISSUE TITLE
bedrock players fly gamemode dont change

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#4136]
### Describe the bug

this happen before and u guys fixed it on the last bedrock update, that the server doesnt reconignze if bedrock player is flying or not.

### To Reproduce

allow berock player to fly only in a region or claim or world, and then exit world or move to a region where u cant fly and the bedrock player will still be able to fly

### Expected behaviour

to reconginze no flying worlds and or regions

### Server Version and Plugins

waterfall(Proxy)

### Geyser Dump

https://dump.geysermc.org/UTlZPYOsYe3Yn94W8cXSiGEG8BOKqjDM

### Geyser Version

build 299

### Minecraft: Bedrock Edition Device/Version

all bedrock devices

### Additional Context

issue only happens with bedrock players and not java

**Comment by ringo360** [comment]
Yes, I had the same problem on my server.
