### ISSUE TITLE
ACTUALICEN EL SERVIDOR 

### ISSUE THREAD

**Issue by CreadordePicraftsso** [GeyserMC/Geyser#4138]
### Describe the bug

SERVIDOR DESACTUALIZADO ACTUALICEN Minecraft A 1.20.30

### To Reproduce

DESCONOCIDO

### Expected behaviour

NO PERMITE ENTRAR AL SERVER

### Screenshots / Videos

![827440F3-D10F-44F2-ACA3-EE5F03653428](https://github.com/GeyserMC/Geyser/assets/145614776/4322c3b8-acef-4ace-b8f5-8e34a95ef436)

### Geyser Version

Desconocido 

### Minecraft: Bedrock Edition Device/Version

1.20.30

**Comment by onebeastchris** [comment]
Geyser is updated to support 1.20.30.
Download the latest version from https://geysermc.org/download - or the link you see on your screen. Then, turn the server off, and change the Geyser jar to the newly downloaded. Afterwards, start the server again.
