### ISSUE TITLE
ACTUALICEN EL SERVER DE MINECRAFT 

### ISSUE THREAD

**Issue by CreadordePicraftsso** [GeyserMC/Geyser#4139]
### Describe the bug

SERVIDOR DESACTUALIZADO 

### To Reproduce

Desconocido

### Expected behaviour

![99B9D854-6507-4092-84C5-8DBBF9F7DC26](https://github.com/GeyserMC/Geyser/assets/145614776/4ab01caa-0387-4a0a-886c-63c57c232806)
![EB0EFAFE-5C94-4F1C-879A-1D2922F6E08D](https://github.com/GeyserMC/Geyser/assets/145614776/8145adee-6e52-403b-8837-f5a803649ec5)

### Screenshots / Videos

![9B3A958B-001D-4A02-B86C-774C8FD6AB80](https://github.com/GeyserMC/Geyser/assets/145614776/863b1b1b-e970-4b7c-b2dd-3ccd011a36f6)

### Server Version and Plugins

ACTUALICEN EL S ![ Cargando D1515320-506F-427C-B5CF-A735E97FA4FD.png...]()

### Geyser Version

Desconocido

### Minecraft: Bedrock Edition Device/Version

1.20.30 IPHONE 15 PRO 256GB

### Additional Context

ACTUALICEN EL SERVIDOR

**Comment by onebeastchris** [comment]
Stop spamming issues. I've replied to your previous post - https://github.com/GeyserMC/Geyser/issues/4138.
If a server you play on has not updated, they need to update the Geyser plugin they use - Geyser itself is updated

**Comment by CreadordePicraftsso** [comment]
> Stop spamming issues. I've replied to your previous post - #4138.
> If a server you play on has not updated, they need to update the Geyser plugin they use - Geyser itself is updated

**Comment by CreadordePicraftsso** [comment]
I KNOW THEY HAVE TO UPDATE IT WE ARE INFLUENCERS OF TIKTOK SPAIN AND MEXICO IF YOU CAN'T HELP DON'T HARM YOURSELF

**Comment by onebeastchris** [comment]
If you know that they need to update, contact them, not us - we cannot help here.
