### ISSUE TITLE
Disconnected after a few seconds from joining

### ISSUE THREAD

**Issue by BillBodkin** [GeyserMC/Geyser#414]
Describe the bug
Disconnected after a few seconds from joining

To Reproduce

Join

Server Version
Cuberite via Bungee

Geyser Version
version 1.0-SNAPSHOT

Minecraft: Bedrock Edition Version
1.14.60

Additional Context
Using standalone Geyser connected to Bungee with ViaVersion plugin connected to a 1.12.2 Cuberite server.

Errors:
Bungee - https://pastebin.com/K4VhCzcX
Client    - https://photos.app.goo.gl/g66S8zwXCGoFApK46

**Comment by RednedEpic** [comment]
> Using standalone Geyser connected to Bungee with ViaVersion plugin connected to a 1.12.2 Cuberite server.
> 
> Errors:
> Bungee - https://pastebin.com/K4VhCzcX
> Client - https://photos.app.goo.gl/g66S8zwXCGoFApK46

Please fill out the issue template.

**Comment by Trains77** [comment]
Yeah I think that is a problem I play on a server that uses bunggeecord and viaversion in the hub and the when I connect, nothing happens until I get disconnected

**Comment by DoctorMacc** [comment]
Closing this as it does not appear to be related to Geyser, and we've received no future reports of this happening with the latest Geyser and ViaVersion. If this issue still occurs, please let us know!
