### ISSUE TITLE
Inventory not opening on the client

### ISSUE THREAD

**Issue by Dueris** [GeyserMC/Geyser#4140]
### Describe the bug

When using geyser with the GenesisMC plugin on modrinth with floodgate, you are unable to open your inventory or any inventory. There originally were a LOT more plugins, but I kept disabling them and the issue was unpredictable and inconsistent. Sometimes it would work and sometimes it wouldn't, even with the same settings.
The interesting thing is the code in the GenesisMC repository, it tries to open an inventory on join and makes it so while that inventory is open you are invulnerable. However, the inventory isn't open and the player's are still invulnerable, even tho Genesis updates that every tick. This means according to the server, the inventory is open when it isnt on the client.

### To Reproduce

Unsure. Its inconsistent.

### Expected behaviour

Open the inventory and be able to open other inventories

### Server Version and Plugins

Latest geyser and Floodgate, mc 1.20.1 PAPER

### Geyser Dump

Not working? Cmd not sending any feedback

### Geyser Version

Latest

### Minecraft: Bedrock Edition Device/Version

Latest

**Comment by onebeastchris** [comment]
Please try updating to the latest version of Geyser, and see if the issue persists. Further, please attach a geyser dump by running `geyser dump` in the server console & send the link here. Additionally, if you're seeing any errors in the server console, please also send a full log via `mclo.gs`. Thanks!

**Comment by Dueris** [comment]
Forgot to let you know that this issue was fixed in a later version of geyser, I'm sorry for not closing this!
