### ISSUE TITLE
Pumpkin helmets does not work without OP

### ISSUE THREAD

**Issue by SonnenPingu** [GeyserMC/Geyser#4142]
### Describe the bug

A user without [OP] cannot put on the carved pumpkin.

Self-tested, as soon as I deop I can no longer put a pumpkin on. 

I OP myself again I put it back on 

Applies only to Bedrock players. 

Java players have no problems. 

### To Reproduce

1: Bedrock on Android
2. Deop 
3: Carving pumpkin
4. Attempts to set up
5. Not working 
6. Op
7. Try putting it on. 
8. Works. 

### Expected behaviour

Normally, a user should be able to put on the pumpkin without it having to be op. 

### Screenshots / Videos

[Video of the error ](https://cdn.discordapp.com/attachments/613168464634576897/1154481280243732500/SVID_20230921_192713_1.mp4)

### Server Version and Plugins

  [Thu 22:26:57 INFO ] Checking version, please wait...
  [Thu 22:26:57 INFO ] This server is running Paper version git-Paper-183 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: eb60bff)
You are 13 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-174 (MC: 1.20.1) Update is not possible manually, HostingProvider informs. But should NOT be a problem. 

  [Thu 22:27:22 INFO ] Server Plugins (37):
  [Thu 22:27:22 INFO ] Bukkit Plugins:
  [Thu 22:27:22 INFO ]  - AcceptTheRules, AdvancedRegionMarket, AutomaticBroadcast, BlueBridgeCore, BlueBridgeWG, BlueMap, BlueMapCustomSkinProvider, BlueMapDeathMarkers, BlueMapFloodgate, BlueMapOfflinePlayerMarkers
  [Thu 22:27:22 INFO ]  BlueMapOfflinePlayerMarkers, BlueMapPlayerControl, ChestShop, ChestShopNotifier, ChestShopTools, CMI, CMILib, DeathChest, DiscordSRV, FastAsyncWorldEdit
  [Thu 22:27:22 INFO ]  floodgate, Geyser-Spigot, Jobs, LuckPerms, Multiverse-Core, PlaceholderAPI, SmoothTimber, spark, Spartan, Vault
  [Thu 22:27:22 INFO ]  ViaBackwards, ViaVersion, Votifier, VotingPlugin, WorldEditSUI, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

ODY4ODI4NTk2MjM4NzAwNjA0.GdC_hb.IsoaTiSqJVuTgHDp_0dcAkoZO6p11rvJ7Y2WxA

### Geyser Version

Git Master 

### Minecraft: Bedrock Edition Device/Version

Mobile phone on Android

**Comment by onebeastchris** [comment]
Hey, i am unfortunately unable to reproduce this issue - i can put on helmets just fine with and without op.

Versions used:
```
[18:46:51 INFO]: Checking version, please wait...
[18:46:51 INFO]: This server is running Paper version git-Paper-217 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: cfe311d)

[18:48:26 INFO]: This server is running Geyser version 2.2.0-SNAPSHOT (git-master-89d7225) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.30/1.20.31)
```

Judging by the video; it could be a plugin that is rejecting the equipping - i would recommend the following steps:
- Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.
