### ISSUE TITLE
ClientboundTakeItemEntityPacket Not Fully Read

### ISSUE THREAD

**Issue by SrathYT** [GeyserMC/Geyser#4145]
### Describe the bug

**I Can't Join My Server Stuck At Locating Server**

### To Reproduce

1. Starting Server
2. Server Running
3. Join Server
4. ClientboundTakeItemEntityPacket Error
5. Timed Out

### Expected behaviour

**Can't Join  Server Timed Out** 

### Screenshots / Videos

![Screenshot_2023-09-25-17-32-30-82_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/GeyserMC/Geyser/assets/93087364/7c8dc9f1-58aa-4712-bfe1-862440568a2b)

### Geyser Dump

https://dump.geysermc.org/EKvAW9uGvFmjYNIOFxpgRHEtZc7ojINR

### Geyser Version

2.2.0-SNAPSHOT (git-master-dead91b)

### Minecraft: Bedrock Edition Device/Version

1.20.15.01

### Additional Context

*

**Comment by HalfloveJAR** [comment]
I'm also experiencing this issue with Geyser Bungee on a Waterfall server connected to two Purpur servers: https://dump.geysermc.org/kd0RheEVkzCpuH3nTUUMkOjJgTfmf7Yu

**Comment by onebeastchris** [comment]
Unable to reproduce. Please try:
- updating BungeeCord/Waterfall and Geyser 
- removing ViaVersion/ViaBackwards from the proxy and instead installing those plugins on the individual backend servers

If that fails, send a full log using mclo.gs

**Comment by onebeastchris** [comment]
Closing due to no further response.
