### ISSUE TITLE
using command instantly crashes on bedrock

### ISSUE THREAD

**Issue by coolinhi** [GeyserMC/Geyser#4146]
### Describe the bug

as soon as you put a / in the chat box it will crash the game on bedrock

### To Reproduce

join geyser server
get OP
open chat box
type "/"
as suggestions load game crashes

### Expected behaviour

instant crash

### Server Version and Plugins

version 1.20.1 on server and 1.20.30 on client

### Geyser Version

build 299 1.20.1

### Minecraft: Bedrock Edition Device/Version

1.20.30 bedrock on PC

**Comment by saminator0107** [comment]
I am having the same issue. although the account is not OP

**Comment by Elavalur** [comment]
From Geyser's Wiki:
> Disable command-suggestions in your config. This will stop / from freezing Bedrock clients but will also disable command suggestions being sent.

Alternatively, you can try and reduce the amount of commands sent to Bedrock edition players - for example by using the HideCommands extension.

**Comment by onebeastchris** [comment]
Duplicate of https://github.com/GeyserMC/Geyser/issues/3990 - see more possible fixes there.
