### ISSUE TITLE
Java 1.20.2 is not supported

### ISSUE THREAD

**Issue by Leahcimkrob** [GeyserMC/Geyser#4150]
### Describe the bug

Loghin with Bedrock is not possible, players are kicked with an outdated client.

### To Reproduce

Login on Server

### Expected behaviour

If a Bedrock player wants to log in, he gets the message that he is using an outdated client.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/70509359/661479c4-5340-4d13-b8f3-cbf3323e6cc0)

### Server Version and Plugins

This server is running BungeeCord version git:BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:fed646d:1748 by md_5

07:22:29 [INFO] BPM+ > Plugins (21 + 7): BetterSecurity, BungeeChat, BungeePluginManagerPlus, BungeeSpy, BungeeTokens, CensorReloaded, CMIB, CraftingStore, ExceptionAnnouncer, floodgate, Geyser-BungeeCord, LiteBans, LuckPerms, Maintenance, MarriageMaster, NoVPN, NuVotifier, RankGift, RankUpgrade, spark, UltimateAutoRestartPassthrough, cmd_alert, cmd_find, cmd_kick, cmd_list, cmd_send, cmd_server, reconnect_yaml.

I try it with and without Viaversion.

### Geyser Dump

https://dump.geysermc.org/wkGzu1x8UUQi5DFLoAVnOMQdKXwkeXa9

### Geyser Version

Geyser-BungeeCord-1494

### Minecraft: Bedrock Edition Device/Version

1.20.30

**Comment by Leahcimkrob** [comment]
Serverlog: 
:16:16 [INFO] [Geyser-BungeeCord] ALLEYZEONME4581 (logged in as: ALLEYZEONME4581) has connected to the Java server
07:16:16 [INFO] [/87.122.126.80:0] <-> InitialHandler has connected
07:16:16 [WARNING] Plugin listener be.besuper.novpn.bungeecord.b.a took 203ms to process event PreLoginEvent(cancelled=false, cancelReasonComponents=null, connection=[*ALLEYZEONME4581,/87.122.126.80:0] <-> InitialHandler)!
07:16:16 [INFO] [floodgate] Floodgate player logged in as *ALLEYZEONME4581 joined (UUID: 00000000-0000-0000-0009-01f295e5e36b)
07:16:16 [WARNING] Event PreLoginEvent(cancelled=false, cancelReasonComponents=null, connection=[*ALLEYZEONME4581,/87.122.126.80:0] <-> InitialHandler) took 250ms to process!
07:16:16 [INFO] [*ALLEYZEONME4581] <-> ServerConnector [servertest] has connected
07:16:16 [INFO] [*ALLEYZEONME4581] disconnected with: Kicked whilst connecting to servertest: Outdated client! Please use 1.20.2
07:16:16 [INFO] [floodgate] Floodgate player logged in as *ALLEYZEONME4581 disconnected
07:16:16 [INFO] [*ALLEYZEONME4581] -> UpstreamBridge has disconnected
07:16:16 [INFO] [*ALLEYZEONME4581] <-> ServerConnector [servertest] has disconnected
07:16:16 [INFO] [Geyser-BungeeCord] ALLEYZEONME4581 has disconnected from the Java server because of Kicked whilst connecting to servertest: Outdated client! Please use 1.20.2

**Comment by SnowBiz** [comment]
Experiencing same issue, any ETA on when java version 1.20.2 will be supported?

**Comment by Leahcimkrob** [comment]
With the new build 1495, I get this message in Log:

```
20:23:01 [INFO] [BungeeChat] JOIN > servertest > *ALLEYZEONME4581: Ethria >> Neuling ›› *ALLEYZEONME4581 hat den Server betreten.
20:23:01 [WARNING] [Geyser-BungeeCord] Downstream packet error! Packet "ClientboundBlockDestructionPacket" not fully read.
20:23:01 [WARNING] [Geyser-BungeeCord] Downstream packet error! Index 10 out of bounds for length 9
20:23:01 [WARNING] [Geyser-BungeeCord] Downstream packet error! readerIndex(19632) + length(1) exceeds writerIndex(19632): PooledUnsafeDirectByteBuf(ridx: 19632, widx: 19632, cap: 19632)
20:23:01 [WARNING] [Geyser-BungeeCord] Downstream packet error! readerIndex(1) + length(1) exceeds writerIndex(1): PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1)
20:23:16 [WARNING] [Geyser-BungeeCord] Downstream packet error! readerIndex(9) + length(1) exceeds writerIndex(9): PooledUnsafeDirectByteBuf(ridx: 9, widx: 9, cap: 9)
```

**Comment by Konicai** [comment]
1. please share logs through https://mclo.gs
2. the master branch doesn't support 1.20.2 - the linked PR that moves Geyser to 1.20.2 does.

**Comment by Leahcimkrob** [comment]
Then I'll probably have to wait until the PR is released.

**Comment by Leahcimkrob** [comment]
Login with the 1496 is still not possible if Geyser is on the bungee cord.
Now the following error occurs:
Cannot get ID for packet class net.md_5.bungee.protocol.packet.LoginSuccess in phase GAME with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125

With Viaversion, I get the message:
Outdated client! Please use 1.20.2 

whole Log:
[proxy.log..txt](https://github.com/GeyserMC/Geyser/files/12774140/proxy.log.txt)

New Geyser Dump:
https://dump.geysermc.org/B2klb4v6M9iqXHPXzBjSs5jF1aSPkCOq

**Comment by rtm516** [comment]
We Jenkins is getting depricated and are pushing new builds to the downloads API see https://geysermc.org/download to grab these builds easily.

**Comment by Leahcimkrob** [comment]
Thank you. the Version from Geyser-Homepage will work.
