### ISSUE TITLE
The in-game skins are ridiculously wrong

### ISSUE THREAD

**Issue by YQCNM** [GeyserMC/Geyser#4159]
### Describe the bug

In the JE, it is possible to display the BE skin very well.
However in BE, the JE skin is black and purple coloured blocks.

### To Reproduce

Just join the server and there it is

### Expected behaviour

Shows normal skin, not weird colour blocks

### Screenshots / Videos

![66e86950d7afde0a1c585e233d6731fa](https://github.com/GeyserMC/Geyser/assets/75867440/00ab6878-f09b-4a1f-9fbd-fd956ab80e4c)
![3724c942586e86987a83c2b735f64642](https://github.com/GeyserMC/Geyser/assets/75867440/c4c30c08-4a08-4396-817f-d11531d6321e)

### Server Version and Plugins

welp im using geyser-spigot

### Geyser Dump

https://dump.geysermc.org/aVw7Qh4wsibGJXVNsn8uJ0g8NO7Ez2Ty

### Geyser Version

Paper-1.20.1-169

### Minecraft: Bedrock Edition Device/Version

1.20.15 Android Phone

### Additional Context

I apologise if you are confused about the above mentioned problem, I am using DeepL to translate my words.

If there is a solution for this problem in Discord, I'm sorry, my country does not allow the use of discord and other similar software, can't break the law for a server, I apologise for the added trouble.

**Comment by YQCNM** [comment]
Oh! and im also using authlib-injector
Is this a problem?

**Comment by Kas-tle** [comment]
Offline mode is not supported. Sorry.
