### ISSUE TITLE
Game Client Crash when pressing "/" key

### ISSUE THREAD

**Issue by ReefC** [GeyserMC/Geyser#4161]
### Describe the bug

Minecraft Bedrock for Windows crashes when pressing the "/" key.

This does not seem to be the case for all Bedrock clients, specifically clients on mobile. The issue is occurring on Bedrock for Windows on a Windows 11 PC.

It happens both when the key is simply pressed and also when the key is pressed when attempting to type a command in chat, however it does not crash the client if the "/" key is not at the start of the typed syntax.

The issue closely mimics this previous closed issue, however I am not aware whether they had this issue outside of the chat window: https://github.com/GeyserMC/Geyser/issues/1895

### To Reproduce

- Join server
- Press the "/", regardless of whether in chat or not
- Game client crashes
- (This will not be reproduced if the chat is opened, any other character is typed first and then the "/" is pressed)

### Expected behaviour

Players should be able to press the "/" without the server crashing and be able to type their desired command.

### Screenshots / Videos

I have not made a screenshot/video, but it is essentially identical to this video: https://www.youtube.com/watch?v=0I-KkIfAbfc

### Server Version and Plugins

paper-1.20.1-196

Server Plugins (16):
- BlockProt
- CoreProtect
- Essentials
- EssentialsChat
- EssentialsDiscord
- EssentialsProtect
- FastAsyncWorldEdit
- floodgate
- Geyser-Spigot
- GeyserHacks
- HuskHomes
- LuckPerms
- spark
- ViaBackwards
- ViaVersion
- WorldGuard

### Geyser Dump

https://dump.geysermc.org/LYeXhbgv1pAo35pEopOnK45pMygiTkhp

### Geyser Version

2.2.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

Bedrock 1.20.3 on Minecraft for Windows, on a Windows 11 PC

**Comment by rtm516** [comment]
Disable `command-suggestions` in your config. This will stop `/` from freezing Bedrock clients but will also disable command suggestions being sent.

Alternatively, you can try and reduce the amount of commands sent to Bedrock edition players - for example by using the [HideCommands extension](https://github.com/Redned235/HideCommands).
