### ISSUE TITLE
Beacons dont give out there respective effects

### ISSUE THREAD

**Issue by DreaOdev** [GeyserMC/Geyser#4166]
### Describe the bug

When you want to use a beacon they don't output there respective effect

E.g. Maxed beacon with haste doesn't give nearby players haste

However this doesn't include pre 1.20.2 beacons
I have 5 beacons placed and they all give there chosen effect however a beacon i just built takes my iron and outputs no effect

This however doesn't effect potions if u drink a strength potion u receive the effect 

### To Reproduce

1. Build a beacon in 1.20.2
2. Choose an effect
3. Wait for it to have outputted the effect
4. Recive no effect

### Expected behaviour

The beacon should give nearby players the selected effect for a certain radius.

### Screenshots / Videos

There should be a video but im not sure if it will work

### Server Version and Plugins

Im running the latest geyser version in the latest java and bedrock versions

The only plugin on the server a set home plugin

### Geyser Dump

https://dump.geysermc.org/22981vBzHG8AyE6gKA990ATjY8ZfZxl1

### Geyser Version

Geyser build 313 version 1.20.2

### Minecraft: Bedrock Edition Device/Version

1.20.31 xbox ps4 and mobile

**Comment by RICE0707** [comment]
I also encountered this vulnerability, Geyser version is Build #1497, bedrock client version is 1.20.31, server version is 1.20.1 (purpur-1.20.1-2022)

video:
https://cdn.discordapp.com/attachments/1158485512944889906/1158600135480188928/Minecraft_2023-10-03_11-01-48.mp4?ex=651cd5f6&is=651b8476&hm=156ebcc9a71304ece9d054f0fa79c326c7f99fc1548b5a0ab663d229c491fc5b&

**Comment by onebeastchris** [comment]
Can reproduce using the latest version of Geyser + a 1.20.2 server. Specifically, beacon effects are translated fine; what is broken is the way Geyser sends ServerboundSetBeaconPacket to the Java server - the current effect is removed, but there is no new selected effect.
In short: Bedrock players can't activate beacons.
