### ISSUE TITLE
Players cant join if a server requires a resource pack

### ISSUE THREAD

**Issue by Budderman18** [GeyserMC/Geyser#4179]
### Describe the bug

Self-explanitory. Pack still downloads but i guess the server thinks it didnt.

### To Reproduce

1. join any server that requires a resource pack

### Expected behaviour

can join afte4r downloading the pack

### Server Version and Plugins

This server is running Paper version git-Paper-207 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 38376f4)

### Geyser Dump

https://dump.geysermc.org/GioSfU8iqlLWaDkTM8NGg3N2XARlAWa1

### Geyser Version

This server is running Geyser version 2.2.0-SNAPSHOT (git-master-3547fab) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.30/1.20.31)

### Minecraft: Bedrock Edition Device/Version

1.20.31 / IPhone XR

**Comment by Kas-tle** [comment]
This will be resolved by https://github.com/GeyserMC/Geyser/pull/4183. Please feel free to test this PR by downloading the build artifacts from the latest build here https://github.com/GeyserMC/Geyser/pull/4183/checks and comment on the PR if you experience any issues.
