### ISSUE TITLE
Frequent failure to detect server online status

### ISSUE THREAD

**Issue by HansOffice** [GeyserMC/Geyser#4182]
### Describe the bug

My geyser is running successfully, but often I can't connect to the server, every time I can't connect I restart the waterfall server and it connects normally again but the latency is very high. I would like to know what is the reason for this, the same region detection using java version of the server detection server latency is only 50ms while the bedrock version of the detection of the latency of more than 1,000ms!

### To Reproduce

No errors reported

### Expected behaviour

I'd like to know what causes this, and hopefully fix the reason why Keystone Edition users often can't connect to the server

### Screenshots / Videos

This is my geyser config file.
[config.txt](https://github.com/GeyserMC/Geyser/files/12817896/config.txt)

### Server Version and Plugins

Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4d5746a:544
Geyser 2.2.0-SNAPSHOT (git-master-dead91b) (Java: 1.20, Bedrock: 1.20.0/1.20.1 - 1.20.30)

### Geyser Dump

https://dump.geysermc.org/UyMIE6Tyoc4bXGvhbrEXGRowo6RXwst6

### Geyser Version

2.2.0-SNAPSHOT (git-master-dead91b) (Java: 1.20, Bedrock: 1.20.0/1.20.1 - 1.20.30)

### Minecraft: Bedrock Edition Device/Version

1.20.31

**Comment by Kas-tle** [comment]
Please join our Discord for support if you require help with troubleshooting. This is more likely a setup/networking issue than a Geyser bug. https://discord.gg/geysermc
