### ISSUE TITLE
PlayerToggleFlightEvent doesn't fire

### ISSUE THREAD

**Issue by TheTobiCraft1** [GeyserMC/Geyser#4184]
### Describe the bug

Bukkit PlayerToggleFlightEvent doesn't fire when I toggle flight in creative mode or with allow flight enabled. In 1.20 it worked.

### To Reproduce

1. download latest build for geyser 1.20.1
2. listen to the PlayerToggleFlightEvent
3. start server with geyser 1.20.1
4. join with bedrock client
5. toggle flight | event won't fire

### Expected behaviour

The PlayerToggleFlightEvent should fire. On java it works just fine.

### Geyser Version

2.2.0-SNAPSHOT (git-master-89d7225)

### Minecraft: Bedrock Edition Device/Version

1.20.31, Windows

**Comment by onebeastchris** [comment]
Should be fixed with https://github.com/GeyserMC/Geyser/pull/4198 - mind testing it? The build can be downloaded in the `Checks` tab on the PR.

**Comment by TheTobiCraft1** [comment]
Thanks

**Comment by onebeastchris** [comment]
This is not yet fixed, but will be once the PR is merged - itll be closed automatically then :)
Additionally, can you test said PR?
