### ISSUE TITLE
Add Hacktoberfest label

### ISSUE THREAD

**Issue by matsyyy** [GeyserMC/Geyser#4185]
### What feature do you want to see added?

Hey!
The Hacktoberfest started (https://github.com/topics/hacktoberfest). Is Geyser planning to participate?
Maybe all other repositories too. Would be awesome to see a few issues fixed - there are 250 open!!

One more thing, how are donations used? Do contributors/devs/leads/mods get a bounty for issues fixed? If not, is there a way to donate to get specific bugs fixed? 

Thanks for this amazing project!

### Are there any alternatives?

no hacktoberfest label :(

**Comment by Kas-tle** [comment]
Currently I believe Ziax Ltd (Cubecraft parent) provides us with most of the recurring hardware we need (e.g. Floodgate Global Linking Server/API, Geyser Test Server, & Geyser Downloads API), but if this were no longer possible it would likely be used for that. Currently they are mostly just saved. You can see financial information regarding donations on OpenCollective: https://opencollective.com/geysermc.

**Comment by matsyyy** [comment]
Does Ziax Ltd provide any compensation for devs or similar for working on the project? Infrastructure is important, but I want to directly support developers that actively fix bugs, since that matters more to me.

**Comment by Kas-tle** [comment]
No one is paid for their work on Geyser.

**Comment by Kas-tle** [comment]
The tag has been added. If you have more questions regarding donations feel free to ask in our Discord (https://discord.gg/geysermc).
