### ISSUE TITLE
Problems with loading chunks

### ISSUE THREAD

**Issue by kartashovio** [GeyserMC/Geyser#4187]
### Describe the bug

Problems with loading chunks.

### To Reproduce

1. Use phone
2. Try to just fly around the map
3. Watch the chunks

### Expected behaviour

Chunks are being loaded.

### Screenshots / Videos

[Video](https://cdn.discordapp.com/attachments/1147150823298707528/1159465818829115442/Screenrecorder-2023-10-05-15-22-04-398.mp4?ex=65311fb1&is=651eaab1&hm=89d8496a7b193ca5b543c7707603bf4ad9df4dc4a01eaccc482ab120d0b64de0&).

### Server Version and Plugins

Patina 1.20.1 -
- ChatDiscord, Chatty, ConsoleSpamFix, CoreProtect, CoreProtectTNT, CustomCrafting, *EasyWhitelist, emotecraft, FastChunkPregenerator, floodgate, Geyser-Spigot, GeyserHacks, GSit, InventoryRollbackPlus, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, JukeboxExtendedReborn, LuckPerms, NBTAPI, OldCombatMechanics, PhantomRemover, PlaceholderAPI, PlugManX, ProtocolLib, SavePlayers, SkinsRestorer, TabCompleter, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, voicechat, voicechat-discord, WorldEdit

### Geyser Version

Geyser: version 2.2.0-SNAPSHOT (git-master-5276a1e) (Java: 1.20, Bedrock: 1.20.0/1.20.1 - 1.20.30)

**Comment by Kas-tle** [comment]
Please provide a Geyser dump by running `geyser dump` in console and updating your post with the link it provides.

**Comment by AlphaMSq** [comment]
Im the technical administrator of the server where this problem occurred. Dump: https://dump.geysermc.org/gCKdS6i1bytRlQ2ymNhKW27P7iyGqjfC

**Comment by Kas-tle** [comment]
What is your server render distance and what is the render distance of the client being used in the video? This looks quite similar to https://github.com/GeyserMC/Geyser/issues/3809 which seems to cause clients with lower render distances than the server to experience issues.

**Comment by iDarknessSam** [comment]
I'm having the same problem too
https://dump.geysermc.org/GOTGWfgSjfqNYj8dujdXS7QLbyX4Hjfw

**Comment by iDarknessSam** [comment]
> > What is your server render distance and what is the render distance of the client being used in the video? This looks quite similar to #3809 which seems to cause clients with lower render distances than the server to experience issues.
> 
> Server: view-distance=22 simulation-distance=12
> 
> Player view distance = 12

did you found a way to fix it?

**Comment by AlphaMSq** [comment]
> > > What is your server render distance and what is the render distance of the client being used in the video? This looks quite similar to #3809 which seems to cause clients with lower render distances than the server to experience issues.
> > 
> > 
> > Server: view-distance=22 simulation-distance=12
> > Player view distance = 12
> 
> did you found a way to fix it?

I set the view distance of the Java server to 12 and the problems solved.

**Comment by iDarknessSam** [comment]
> > > > What is your server render distance and what is the render distance of the client being used in the video? This looks quite similar to #3809 which seems to cause clients with lower render distances than the server to experience issues.
> > > 
> > > 
> > > Server: view-distance=22 simulation-distance=12
> > > Player view distance = 12
> > 
> > 
> > did you found a way to fix it?
> 
> I set the view distance of the Java server to 12 and the problems solved.

Well I tried to do it and it didn't help
the problem still persist
