### ISSUE TITLE
Chat doesn't work for bedrock

### ISSUE THREAD

**Issue by LeuuK** [GeyserMC/Geyser#4192]
### Describe the bug

The chat on my server, which is in the latest versions, is not working

It appears this

![Screenshot_20231006-211114_Minecraft](https://github.com/GeyserMC/Geyser/assets/90121572/2f4f0f35-5821-4828-bdd5-4693fa09cbb3)

### To Reproduce

.

### Expected behaviour

I wish it was possible to read the chat

### Server Version and Plugins

1.20.2

floodgate 
Geyser-Spigot 
GeyserSkinManager
GSit
ImageFrame
SkinsRestorer
ViaBackward
ViaVersion

### Geyser Dump

https://dump.geysermc.org/7RWcblgzOBkUTcTTvX2lecw2CEGu1Jay

### Geyser Version

332

### Minecraft: Bedrock Edition Device/Version

1.20.32 cellphone

**Comment by onebeastchris** [comment]
Try deleting the `locales` folder in `plugins/Geyser-Spigot`, and restart. This issue usually appears when Geyser could not load a locale - and defaults to the language strings (causing the issue here)

**Comment by LeuuK** [comment]
I deleted it and it's still the same

**Comment by onebeastchris** [comment]
Send a full log via [mclo.gs](https://mclo.gs/) then

**Comment by LeuuK** [comment]
i think another server mod fixed the chat, its working now, thx!
