### ISSUE TITLE
Downstream packet error - From geyser user, but not from Java user

### ISSUE THREAD

**Issue by KvasirQc** [GeyserMC/Geyser#4206]
### Describe the bug

This is from comming when my switch is connected. It's not happening when i'm connected with java.
We have the last velocity plugin. and one of the last paper, in 1.20.1 (I'd rather not update to 1.20.2 yet if possible)
Geyser and floodgate are updated
My debug is already set to false in geyser

PS: I do have a few custom NPC, I've read somewhere else that nametag or something close could cause these. any clue please?

Thanks for the support!

### To Reproduce

Connect with a switch account / bedrock to the server, and look at the console. Observe the console spamming.account/bedrock

### Expected behaviour

Having a clear console without spam "downstream packet error!"

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/40178706/3ed3c8b8-a914-45c7-a29b-c700c77c2595)

### Server Version and Plugins

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

Update geyser and floodgate to the last server.  #1514 and #94
Update viaversion and viabackward to the last version (4.8.1)

Velocity is updated to the last version 3.2.0-SNAPSHOT (Velocity 3.2.0-SNAPSHOT)
Build #269

### Geyser Dump

Open a server paper: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)  Update geyser and floodgate to the last server.  #1514 and #94 Update viaversion and viabackward to the last version (4.8.1)  Velocity is updated to the last version 3.2.0-SNAPSHOT (Velocity 3.2.0-SNAPSHOT) Build #269

### Geyser Version

#1514

### Minecraft: Bedrock Edition Device/Version

1.20.32 switch

### Additional Context

Thanks for your help!

**Comment by Camotoy** [comment]
Can you please send a new log with `debug-mode` enabled in the Geyser config?

**Comment by KvasirQc** [comment]
For sure, give me 5 min and i'm sending that back

**Comment by KvasirQc** [comment]
there you go sir :) thank you for your amazing plugin and help!

https://dump.geysermc.org/pMHXhhQvD6ddvNXR9pgCZXwxXlOuErta

**Comment by Camotoy** [comment]
Can you please attach a LOG file? With the debug setting enabled, there should be more information when that "Downstream packet error" occurs. Thanks! :)

**Comment by KvasirQc** [comment]
[latest.zip](https://github.com/GeyserMC/Geyser/files/12863103/latest.zip)
Thank you sir ! :)

**Comment by KvasirQc** [comment]
> I have the same issue

Hi, could you please send your dump and send your log as i did so they could compare what plugin we have in common and what could be the cause. Pretty please!

**Comment by EpicJosch** [comment]
Dump: https://dump.geysermc.org/iMVTD3HfOvS8cNqUiZtuFurYuzhGE7Oy
Log: [latest.log](https://github.com/GeyserMC/Geyser/files/12873093/latest.log)

**Comment by KvasirQc** [comment]
Thanks alot.. pretty sure it's gonna help him/them.

Have a great day.

Let's agree with one thing...its spamming freaking fast lolll!!

Later!

**Comment by EpicJosch** [comment]
> Thanks alot.. pretty sure it's gonna help him/them.
> 
> Have a great day.
> 
> Let's agree with one thing...its spamming freaking fast lolll!!
> 
> Later!

There is a ChatRoom for everyone that has this Geyser Downstream Error in case you wanna join: [ChatRoom](https://management.azrasoul.de/call/cvvoq3ii)

**Comment by KvasirQc** [comment]
We do not have the same behaveor; I just checked your .log and yours says: 

Downstream packet error! Unregistered serverbound packet class: com.github.steveice10.mc.protocol.packet.ingame.serverbound.player.ServerboundMovePlayerPosPacket
once when the player is connecting.

Mine is spamming my error more than a few time each seconds while the player is connected. So it's really not the same behaveor. 

It's close because of the first part of the sentence, but I would suggest you to create a new issue for your problem since it's not the same. Maybe @Camotoy can confirm if he will prefer a new issue or only this one is fine. 

Good evening!

**Comment by KvasirQc** [comment]
Fixed with [#275] of Velocity
(https://api.papermc.io/v2/projects/velocity/versions/3.2.0-SNAPSHOT/builds/275/downloads/velocity-3.2.0-SNAPSHOT-275.jar)
[f884e04](https://github.com/PaperMC/velocity/commit/f884e049c006f5fae14abaab9332ccaad9f001e0)

Finally found my patch / solution. 

Really happy with it. Thanks for the plugins guys!
