### ISSUE TITLE
Certain GUI's cause bedrock to crash ONLY ON PLAYSTATION

### ISSUE THREAD

**Issue by spookymgmt** [GeyserMC/Geyser#4208]
### Describe the bug

When opening random GUI's or possibly, not confirmed, rendering in custom resource pack items placed on itemframes, can cause PlayStation 5 players to crash.

https://cdn.discordapp.com/attachments/1051229489461465088/1161661348153929758/20231011_144606.mp4?ex=65391c70&is=6526a770&hm=516a1b363dd511d0ab93e695c5078860a390d0de2ddd18f9530fef1afd068d06&
 video ^ skip to end

### To Reproduce

Open various guis with resource pack enabled.

### Expected behaviour

No mc crashes.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1051229489461465088/1161661348153929758/20231011_144606.mp4?ex=65391c70&is=6526a770&hm=516a1b363dd511d0ab93e695c5078860a390d0de2ddd18f9530fef1afd068d06&

### Server Version and Plugins

1.20.1

### Geyser Dump

https://dump.geysermc.org/TofO6xGE3K31aLvq1aSZeeXsFS6jOubt

### Geyser Version

"2.2.0-SNAPSHOT (git-master-b17f4a4)",

### Additional Context

This didn't happen on the geyser version from 3 weeks ago. Started happening after updating.

**Comment by spookymgmt** [comment]
Players also crashing when opening vanilla chests (PS5 ONLY).

**Comment by spookymgmt** [comment]
also update - the crash happens on page load. So If theres a "next button" in a gui, if they click that fast, crash

**Comment by spookymgmt** [comment]
I've confirmed the issue occurs with OR without my resource pack loaded.

**Comment by rtm516** [comment]
Superseeded by #4221
