### ISSUE TITLE
Geyser List Bug

### ISSUE THREAD

**Issue by Legit4K** [GeyserMC/Geyser#421]
**Describe the bug**

Sometimes when bedrock players leave, they aren't removed from the Geyser list.

**To Reproduce**

idk what causes it atm so I'll do more testing

**Expected behavior**

A disconnected Player through Geyser should no longer appear in "/geyser list" 

**Screenshots / Videos**

**Server Version**

[Sat, 25. Apr 2020 10:25:54 BST INFO] This server is running Paper version git-Paper-211 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

[Sat, 25. Apr 2020 10:25:54 BST INFO] You are 3 version(s) behind

**Geyser Version**

Build Number: 70
Geyser Type: Plugin
Branch Type: master

**Minecraft: Bedrock Edition Version**

1.14.6(0)

**Additional Context**

**Comment by rtm516** [comment]
You can't be using geyser build 69 as 70 was the earliest that the geyser list command was added. Can you update to the latest version and see if it still occurs then update your issue.

**Comment by Legit4K** [comment]
My bad, I was using Build 70, I'm going to update and see if it still occurs

**Comment by AnonAlpha** [comment]
It still occurs, just tested with latest build
