### ISSUE TITLE
Unable to connect via frpc in docker

### ISSUE THREAD

**Issue by ruattd** [GeyserMC/Geyser#4212]
### Describe the bug

```
[Geyser-Spigot] /172.17.0.3:59866 tried to connect!
```
Repeat some times (~ 13 times) and the client shows "Unable to connect to world"

See also: [gofrp.org](https://gofrp.org/)

Bedrock address is set to `0.0.0.0`

It can be connected successfully in the LAN

*Forgive my poor English! :(*

### To Reproduce

1. Run a docker image of frp client (frpc)
2. Run a minecraft server with Geyser on the host (not under docker)
3. Connect to the server via frp server (frps)
4. "Unable to connect to world"

### Expected behaviour

Connect to the server successfully via frpc in docker

### Server Version and Plugins

`/version` output:
```
This server is running Paper version git-Paper-100 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f402f89)
```

### Geyser Version

2.2.0-SNAPSHOT (git-master-3fa35b2)

### Minecraft: Bedrock Edition Device/Version

1.20.32, Windows & Android

**Comment by Kas-tle** [comment]
Can you connect without running FRP in front? If so then its likely a misconfiguration of FRP.

**Comment by ruattd** [comment]
@Kas-tle I can, but can also connect via frpc out of docker

**Comment by Kas-tle** [comment]
Given that the connection attempt is logged that implies that you are getting incoming traffic from the client but somehow the response from Geyser is not being sent back to the right place when in docker.

**Comment by Kas-tle** [comment]
I wouldn't call it a bug but something wrong with the networking setup of docker.

**Comment by ruattd** [comment]
Thank you! I will check the networking setup of docker.

**Comment by Kas-tle** [comment]
You may also need to change Geyser's bind address explicitly to what you are expecting it to bind to within the container.

**Comment by onebeastchris** [comment]
Did you follow the docker setup steps on our portforwarding page?
https://wiki.geysermc.org/geyser/port-forwarding/#using-docker-or-pterodactyl

**Comment by ruattd** [comment]
@onebeastchris Tried but it didn't work.
And, it seems that the steps are work for Geyser under docker? (My server is running on host and frpc is under docker)

**Comment by Kas-tle** [comment]
Hmm so then could you please diagram/clarify the setup you have? FRPC is in Docker... is Geyser also, and on the same machine?

**Comment by ruattd** [comment]
As follows:
```
MACHINE
-> HOST (Arch Linux)
    -> CONTAINER (Docker)
        -> FRPC
    -> Minecraft Server & Geyser
```

**Comment by Kas-tle** [comment]
Geyser and the MC server are not running in docker containers as well?

**Comment by ruattd** [comment]
Yes, only frpc is running in docker.

**Comment by Kas-tle** [comment]
Closing since this is a networking setup issue. For further support, you can join our discord at https://discord.gg/geysermc.
