### ISSUE TITLE
Velocity 1.20.2 Downstream Packet Error

### ISSUE THREAD

**Issue by ItsmagmaMan09** [GeyserMC/Geyser#4213]
### Describe the bug

When I log into the proxy everything works fine but when I try to switch servers it spams me with a downstream packet error and then Times out the bedrock player with a a code of Read Time Out and the console spams me with [geyser]: Downstream packet error! Unregistered serverbound packet class: com.github.steveice10.mc.protocol.packet.ingame.serverbound.player.ServerboundMovePlayerPosPacket

### To Reproduce

1. Run Velocity Server with 2 or more paper servers and geyser installed
2. Connect with bedrock
3. attempt to switch servers

### Expected behaviour

The player is successfully switched to the next server

### Server Version and Plugins

Velocity Build #255 
Paper Build #227
Geyser 2.2.0-SNAPSHOT Java 1.20.2 Bedrock 1.20.0/1.20.1/1.20.30/1.20.31

### Geyser Dump

https://dump.geysermc.org/8oSjwwCunorbfu7gqPb9Wsjs4qqhvSQS

### Geyser Version

2.2.0-SNAPSHOT (Git-master-00800ac)

### Minecraft: Bedrock Edition Device/Version

1.20.32 Windows 11

**Comment by Kas-tle** [comment]
Hello,

I am slightly confused here as you've said you're using velocity build 255 but your Geyser dump indicates you're using build 275. I have setup a minimal server with no plugins on paper, and only Floodgate and Geyser on Velocity. I cannot reproduce this issue with that setup and switching servers works fine. Please try removing all plugins from Velocity except Geyser and Floodgate to see if you can still produce the issue.

**Comment by ItsmagmaMan09** [comment]
oh must have been a typo it is indeed Build 275, After disabling all but geyser and floodgate on my velocity server and updating paper it still gives me a Downstream Packet error, could it be a paper plugin thing

**Comment by Kas-tle** [comment]
Are you switching servers simply with `/server <servername>` or by some other means?

**Comment by ItsmagmaMan09** [comment]
i have a plugin on the lobby server that adds NPCs that run /server <servername> as the player and I have tried just using /server both result in the error

**Comment by Kas-tle** [comment]
Could you post the log from Velocity and the list of plugins on your paper servers?

**Comment by ItsmagmaMan09** [comment]
[latest.log](https://github.com/GeyserMC/Geyser/files/12889106/latest.log)
Goosecraft:
![image](https://github.com/GeyserMC/Geyser/assets/98629380/b10fbb1f-d259-4513-af7f-be76298699f8)
Lobby: 
![image](https://github.com/GeyserMC/Geyser/assets/98629380/b6956214-af45-45a7-b080-eaa951a6f884)

**Comment by Kas-tle** [comment]
I suppose try with all plugins disabled on the backends? Really not sure what it could be at this point since as I said, I cannot reproduce this on a clean setup.

**Comment by Kas-tle** [comment]
Also wait why do you have Geyser on the backend?

**Comment by ItsmagmaMan09** [comment]
it's from when that server used to be the only server that ran, but it gets disabled on startup cause it can't bind to a port

**Comment by ItsmagmaMan09** [comment]
and when I disabled all of the plugins the same error came through

**Comment by Kas-tle** [comment]
So to be clear, the only plugins on the proxy are Geyser and Floodgate, and there are no plugins on the backends whatsoever?

**Comment by ItsmagmaMan09** [comment]
Correct

**Comment by Kas-tle** [comment]
Try disabling the extension you have as well... don't see how that could have any effect but this really doesn't make sense at this point anyways.

**Comment by Kas-tle** [comment]
Also since I saw you previously had floodgate on one backend make sure send-floodgate-data is disabled in the floodgate config on Velocity.

**Comment by ItsmagmaMan09** [comment]
sadly still sends the error, idk how this happens, should I try resetting the config?

**Comment by Kas-tle** [comment]
I would try literally from scratch on both ends at this point. Just back everything up and start with no plugins and entirely clean servers on the backend.

**Comment by ItsmagmaMan09** [comment]
ok

**Comment by MattTheTekie** [comment]
> ok

use the latest version on github actions and lmk

**Comment by KvasirQc** [comment]
Just wondering:
Could these two bugs be related? Just wondering. It's not the exact same downstream error but I wanted to link these issue maybe if that could help! 

#4206 
https://github.com/GeyserMC/Geyser/issues/4206

Thank you

BTW: I am planning to swipe every plugin and add them one by one to find the source of the problem. What other plugin could cause that.

![image](https://github.com/GeyserMC/Geyser/assets/40178706/e05e0644-8a6a-474a-b506-a52751308b50)
![image](https://github.com/GeyserMC/Geyser/assets/40178706/146b497e-55a2-4847-bf3a-eade8074ab6a)
![image](https://github.com/GeyserMC/Geyser/assets/40178706/11956a70-61d1-4d3d-8fd9-50b908b0c47f)


If I find the faulty plugin i'll contact you back!

**Comment by KvasirQc** [comment]
@ItsmagmaMan09  Hi, do you use Velocitytab? 

I was using it, I did try to update it to the latest version, but either way, updated or not I have the error.

Do you use the same on your velocity proxy ? Thanks

**Comment by ItsmagmaMan09** [comment]
No i don't use velocitylab, I use a release version of velocity in a server wrapper called MCSS

**Comment by KvasirQc** [comment]
It wasn't the same exact issue anyway, but I tried to help! 

Good luck with your issue.

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/pull/4210 should fix this, update Geyser. Your dump shows that you are 2 commits behind (https://github.com/GeyserMC/Geyser/compare/00800ac...master)
