### ISSUE TITLE
CreatureSpawner bug

### ISSUE THREAD

**Issue by Almighty-Shogun** [GeyserMC/Geyser#4214]
### Describe the bug

When updating the CreatureSpawner to have the EntityType as null it doesn't update this for the bedrock players.

Updating the CreatureSpawner to have a different EntityType does work.

### To Reproduce

```java
CreatureSpawner creatureSpawner = (CreatureSpawner) location.getBlock().getState();

// This does not work
creatureSpawner.setSpawnedType(null);

// This does work
creatureSpawner.setSpawnedType(EntityType.ZOMBIE);

creatureSpawner.update();
```

### Expected behaviour

The spawner should be updated so that no mob entity will be set to null.

### Screenshots / Videos

https://streamable.com/40qkft

Left: Minecraft Java Edition
Right: Minecraft Bedrock Edition

### Server Version and Plugins

`/version` output
Paper version git-Paper-196 (MC: 1.20.1) (Implenting API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

Plugins:
LuckPerms 5.4.102
TAB 4.0.4
ViaVersion 4.8.1

Some plugins I made myself which do not conflict with this issue.

### Geyser Dump

https://dump.geysermc.org/2GBv1KWtPcfARllDGgEwAZCem2YnNRTg

### Geyser Version

2.2.0-SNAPSHOT (git-master-3fa35b2)

### Minecraft: Bedrock Edition Device/Version

1.20.32 Windows

**Comment by onebeastchris** [comment]
Was able to replicate, thanks for the replication steps.
https://github.com/GeyserMC/Geyser/compare/master...onebeastchris:Geyser:null-spawner-fix should fix it, however, it comes with the unfortunate side-effect of *all* empty spawners still showing spawning particles - which is less than ideal.
