### ISSUE TITLE
Windows Bedrock client freezes when opening a chat

### ISSUE THREAD

**Issue by KUSACHA** [GeyserMC/Geyser#4217]
### Describe the bug

When I try to open the chat screen, the client freezes before the screen opens.
It works fine on smartphones.
I tried changing versions (both 1.20.32.3 and 1.20.15.1) and disabling command suggestions,
but neither improved.

### To Reproduce

Press "ENTER" key or the "/" key, the game freezes.

### Expected behaviour

I want avoid freeze

### Server Version and Plugins

Paper Server 1.20.2 238
Floodgate plugin 85
DiscordSRV 1.26.2
BlueMap 3.17

### Geyser Dump

https://dump.geysermc.org/eXCJoHMuc1LNnlDEWyg5XKfqD7U2b1fj

### Geyser Version

2.2.0-SNAPSHOT (git-master-3fa35b2)

### Minecraft: Bedrock Edition Device/Version

Windows 11 1.20.32.3 and 1.20.15.1

**Comment by onebeastchris** [comment]
Unfortunately, a known issue (https://github.com/GeyserMC/Geyser/issues/3990). See https://github.com/GeyserMC/Geyser/issues/3990#issuecomment-1664188328 for a fix.

**Comment by KUSACHA** [comment]
I tried these methods but no improvement. Is it another issue?

・command-suggestion => false
・HideCommands install (I checked the enable log)
