### ISSUE TITLE
Velocity 1.20.2

### ISSUE THREAD

**Issue by Spyplayz13** [GeyserMC/Geyser#4218]
### Describe the bug

Players Of Bedrock Vr 1.20.2 Are Not Able To Join

<Player>has disconnected from the Java server because of This proxy software does not support Java Edition 1.20.2, and must be updated for Geyser to connect.

### To Reproduce

1.Run Velocity Server with 2 or more paper servers and geyser installed
2.Connect with bedrock
3.Not Able To Join With 1.20.2 Bedrock Vr

### Expected behaviour

The player is successfully Join The Server

### Screenshots / Videos

![Screenshot_2023-10-15-17-53-46-196_com mojang minecraftpe](https://github.com/GeyserMC/Geyser/assets/135302690/0c3f270c-e9eb-466b-9ece-14c39d1d05b3)

### Server Version and Plugins

Server Version=latest

Plugins
Velocity-GeyserMc= Build #330
Velocity-Floodgate= Build #85

### Geyser Dump

No Found

### Geyser Version

Velocity-GeyserMc= Build #330

### Additional Context

No response

**Comment by onebeastchris** [comment]
Update Velocity. If your backend server do not support 1.20.2, install ViaVersion on them - Geyser emulates a 1.20.2 Java client, which your server does not seem to support currently.

**Comment by Spyplayz13** [comment]
It Is Not Java Promblem It Is Bedrock Promblem.

**Comment by Spyplayz13** [comment]
If There Is Any Fix For It Please Tell
