### ISSUE TITLE
Air bubbles persist through servers

### ISSUE THREAD

**Issue by Folas1337** [GeyserMC/Geyser#4220]
### Describe the bug

I have a velocity network and a couple backend servers. I only run Geyser on the velocity proxies and not on the backend. People normally go from lobby1 to any backend server.

I have set up a portal system in lobby1 where people are in survival mode. They step into water and then get sent to another backend server (through some trickery that shouldn't matter for this). The issue is that if they are not sent to a server where they are in survival mode but instead creative mode, the air bubbles you get persist and never go away. So you'll be on a backend server where you are in creative but you will still see the air bubbles stick around.

There also seems to be no way to fix this easily and I hope there's something you can do to solve this.

### To Reproduce

- Set up velocity + geyser
- Set up two backend servers, one being the lobby where you are in survival mode, one where you are in creative mode
- Jump into water in the lobby and then connect to the second backend server
- See how you will keep the air bubbles you used to have on the lobby on the other backend server, forever

### Expected behaviour

The air bubbles should be cleared when joining a server with creative mode.

### Server Version and Plugins

Both backend servers: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-194 (MC: 1.20.1)

### Geyser Dump

https://dump.geysermc.org/ZHczs2TvdYPAUuX6SO6VFQscWRsBIBXK

### Geyser Version

geyser 2.2.0-SNAPSHOT (git-master-3fa35b2)

### Minecraft: Bedrock Edition Device/Version

1.20.32

**Comment by onebeastchris** [comment]
Please try updating Velocity & Geyser to the latest respective versions & see if the error persists :)

**Comment by Folas1337** [comment]
> Please try updating Velocity & Geyser to the latest respective versions & see if the error persists :)

Nope, it seems to be happening still.
I was running Geyser version 2.2.0-SNAPSHOT (git-master-574dad0)

**Comment by ch4ika** [comment]
I think that has something to do with it too.
https://github.com/GeyserMC/Geyser/issues/4273

**Comment by DxrkCat** [comment]
Checked with BungeeCord (Geyser-BungeeCord+Floodgate-BungeeCord+TAB-BungeeCord) the problem is the same bossbar goes lower.

**Comment by onebeastchris** [comment]
Could you try the build from the linked PR (https://github.com/GeyserMC/Geyser/pull/4278/checks) once it builds and see if that resolves the issue?

**Comment by Folas1337** [comment]
Still doesn't seem to do anything for me regarding the bubbles :(

**Comment by onebeastchris** [comment]
Send a Geyser dump please while running that build? Bubbles disappeared just fine during my testing...

**Comment by Folas1337** [comment]
Maybe worth noting, I'm sending them with the plugin ajQueue, not sure if it does anything different than using something like '/server'

**Comment by onebeastchris** [comment]
Hm, I was testing with Bungee, not Velocity - I guess I'll test that out. As for the plugin, that shouldn't really matter

**Comment by onebeastchris** [comment]
Just making sure; does a 1.20.2 Java client clear them fine?

**Comment by Folas1337** [comment]
Has been on all versions of Geyser I've ever seen, using the very same way of teleporting the user, yes.

**Comment by onebeastchris** [comment]
That's not really what the question was; please test a 1.20.2 Java client (not Geyser, just a normal java client). Additionally, do the bubbles disappear when using the normal `/server` command instead of whatever this other teleporting method is that you're using?

**Comment by onebeastchris** [comment]
Was able to reproduce. @Folas1337 can you re-try the latest build and see if that fixes the permanent air bubbles?

**Comment by Folas1337** [comment]
> Was able to reproduce. @Folas1337 can you re-try the latest build and see if that fixes the permanent air bubbles?

Sure, will try again, sorry I haven't gotten back earlier, was busy irl. Thanks for figuring it out though, I'll give it another shot and tell you in at least an hour :)
