### ISSUE TITLE
GUI Memory Leak (THIS IS A MOJANG BUG, BUT CAN GEYSER PLEASE FIX IT)?

### ISSUE THREAD

**Issue by spookymgmt** [GeyserMC/Geyser#4221]
### Describe the bug

Everytime you open a chest with a unique title, it's added to memory and never cleared.

### To Reproduce

Rename some vanilla chests, place them, open them. Watch your systems memory on windows 10 edition from task manager. (Every inventory with a unique title you open, it stays with you for life in memory).

### Expected behaviour

Remove the memory after chest inventory is closed.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1082472914034642955/1163580699647950980/2023-10-16_13-50-54.mp4?ex=654017f9&is=652da2f9&hm=281322d9cf9f487d8c5c4768aec3210093020c350f75aa1bd766e50af970c41b&

### Geyser Dump

https://dump.geysermc.org/zpYTWQZUwhFThCsKhdoqQiCIU01p4Xee

### Geyser Version

"2.2.0-SNAPSHOT (git-master-6b67e43)",

### Minecraft: Bedrock Edition Device/Version

1.20.32

### Additional Context

https://github.com/GeyserMC/Geyser/issues/4208

I created the above issue without having more information. After a lot of scientific research, I have pinpointed the issue.

**Comment by spookymgmt** [comment]
You can test this in single player, you don't even need to be on a geyser server. But I'm hoping geyser can patch it so we don't have to wait on mojang.

**Comment by onebeastchris** [comment]
As you stated yourself, it's a Mojang bug. Report it to them, *especially* if you can reproduce it on Singleplayer...

**Comment by spookymgmt** [comment]
> As you stated yourself, it's a Mojang bug. Report it to them, _especially_ if you can reproduce it on Singleplayer...

But if it's possible for geyser to fix, why not? Geyser isn't usable right now. If it's an easy fix, lets consider it?
