### ISSUE TITLE
2 Issues

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#4224]
### Describe the bug

hey i run geyser on my proxy, My server is whitelisted with discord SRV. when new bedrock players join for the first time geyser shows them a disconection closed error instead of the message displaying their 4 digit code so they can link their account

"18.10 00:24:36 [Server] INFO [.SeaRanger28901] disconnected with: Kicked whilst connecting to Main: YOU MUST LINK YOUR DISCORD ACCOUNT TO PLAY!!.
18.10 00:24:36 [Server] INFO Find The discord channel thats says {Link Code Here}
18.10 00:24:36 [Server] INFO And only enter this 4 digit code >> 3858 << to link your account.
18.10 00:24:36 [Server] INFO Discord Invite » https://discord.gg/2qfhUmBZkf
18.10 00:24:36 [Server] WARN [Geyser-BungeeCord]: Downstream packet error! Invalid packet id: 644
18.10 00:24:36 [Server] INFO [floodgate]: Floodgate player logged in as .SeaRanger28901 disconnected
18.10 00:24:36 [Server] INFO [Geyser-BungeeCord]: SeaRanger28901 has disconnected from the Java server because of Connection closed.
18.10 00:24:36 [Server] INFO [/72.204.105.102:0|.SeaRanger28901] -> UpstreamBridge has disconnected"

Second i get this warn 
"18.10 00:32:56 [Server] WARN [Geyser-BungeeCord]: Could not find an entity definition with type ITEM_DISPLAY"

### To Reproduce

run geyser on proxy, use SRV on back end, and whitelist system

### Expected behaviour

for the 4 digit code to be displayed instead of connection closed error with out the message

### Geyser Dump

https://dump.geysermc.org/SCuxKUoosBMuc6g1Q4X9n2tGqZjbuoiR

### Geyser Version

Build #333

### Minecraft: Bedrock Edition Device/Version

all bedrock devices and clients

### Additional Context

proxy logs 
https://mclo.gs/q85NN7b

**Comment by Redned235** [comment]
This is not a Geyser issue. Unfortunately, Bedrock only supports showing a limited amount of text in the disconnect message, so you will need to update the kick message to be something shorter. Nothing we can do on the Geyser side to resolve this.

Secondly, `Could not find an entity definition with type ITEM_DISPLAY"` is nothing to be worried about. It just means that Geyser cannot find a suitable Bedrock entity for item displays, which only exist in Java Edition.

In the future, when issues are encountered, please create separate issues for each individual problem, rather than one issue for multiple. It makes it easier for us to keep track of the issues.

**Comment by shawn695** [comment]
i have made the message as short a possible

18.10 15:44:32 [Server] INFO [Geyser-BungeeCord]: /90.210.88.42:59062 tried to connect!
18.10 15:44:35 [Server] INFO [Geyser-BungeeCord]: Player connected with username silentbutginger
18.10 15:44:35 [Server] INFO [Geyser-BungeeCord]: silentbutginger (logged in as: silentbutginger) has connected to the Java server
18.10 15:44:35 [Server] INFO [floodgate]: Floodgate player logged in as .silentbutginger joined (UUID: 00000000-0000-0000-0009-000009bc2d96)
18.10 15:44:36 [Server] INFO [.silentbutginger] disconnected with: Kicked whilst connecting to Main: YOU MUST LINK YOUR DISCORD ACCOUNT TO PLAY!!.
18.10 15:44:36 [Server] INFO Find The discord channel thats says {Link Code Here}
18.10 15:44:36 [Server] INFO And only enter this 4 digit code >> 7976 <<
18.10 15:44:36 [Server] INFO [floodgate]: Floodgate player logged in as .silentbutginger disconnected
18.10 15:44:36 [Server] WARN [Geyser-BungeeCord]: Downstream packet error! Packet "ClientboundLoginDisconnectPacket" not fully read.
18.10 15:44:36 [Server] INFO [Geyser-BungeeCord]: silentbutginger has disconnected from the Java server because of Connection closed.
18.10 15:44:36 [Server] INFO [/90.210.88.42:0|.silentbutginger] -> UpstreamBridge has disconnected
