### ISSUE TITLE
allow-password-authentication is removed

### ISSUE THREAD

**Issue by bddjr** [GeyserMC/Geyser#4233]
### Describe the bug

When I installed the latest version, I found that "mojang login" disappeared, which is very inconvenient for offline players. I cannot click "mojang login" as usual and enter the offline login username to enter.

My server has both online and offline players, and I hope that offline players can enter their offline login username instead of forcing them to use the bedrock username.

### To Reproduce

Install latest geyser, then use bedrock edition join the server. 

### Expected behaviour

I can choose 'mojang login'

### Screenshots / Videos

![1](https://github.com/GeyserMC/Geyser/assets/109646559/d7b4055e-0cfe-491b-9f19-ea63eff42738)

### Geyser Version

version 2.2.0-SNAPSHOT (git-master-6b67e43) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.30/1.20.31)

### Additional Context

Translate by fanyi.baidu.com

**Comment by Elavalur** [comment]
Install Floodgate.

**Comment by onebeastchris** [comment]
This has been done on purpose - Mojang account authentication is no longer available for online mode.
Offline mode is unsupported.

**Comment by bddjr** [comment]
Fortunately, it is still usable after being built with the old version.

https://github.com/bddjr/Geyser-roolback-for-mojang-login/releases/tag/20231021

**Comment by Camotoy** [comment]
Please note that Geyser, in general, does not endorse third-party builds of Geyser, and for anyone attempting to use said builds, please be wary of additional malicious modifications.
