### ISSUE TITLE
Windows 10 Minecraft Crashes on join

### ISSUE THREAD

**Issue by mastachef** [GeyserMC/Geyser#4241]
### Describe the bug

Game crashes when joining the server on the latest version of geyser/floodgate

### To Reproduce

Use latest velocity/geyser/floodgate

### Expected behaviour

Connect to server properly

### Geyser Version

Latest on downloads site

**Comment by Jens-Co** [comment]
duplicate of #4240.

thanks for reporting anyways :).

**Comment by mastachef** [comment]
> duplicate of #4240.
> 
> thanks for reporting anyways :).

Not the same bug, this is occuring on join of the server.

not while doing /spawn

Cant even get on the server.

**Comment by Jens-Co** [comment]
If that's the case please fill in the complete bug report and provide us with more information, a Geyser dump, server logs etc.
