### ISSUE TITLE
Windows 10 Minecraft Crashes on join

### ISSUE THREAD

**Issue by mastachef** [GeyserMC/Geyser#4242]
### Describe the bug

Game crashes when joining the server on the latest version of geyser/floodgate

Unable to even get on the server PERIOD as the game closes upon "joining"

Proxy is running velocity #276

Servers are running 
Pufferfish version git-Pufferfish-17 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f6a081a on HEAD)

Using latest bedrock (1.20.40) version that was released in the last 24hrs

### To Reproduce

Use the same versions as me

### Expected behaviour

Connect properly

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/80359894/ac03ccc2-2433-4a46-b614-8890dc0b3038

### Server Version and Plugins

Proxy is running Velocity #276

Servers are running 
Pufferfish version git-Pufferfish-17 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f6a081a on HEAD)

### Geyser Dump

 https://dump.geysermc.org/B94xFgyMn466UazUrp7Zy0Tprm3cOaNq

### Geyser Version

Geyser Velocity #339

**Comment by onebeastchris** [comment]
You're missing the affected Bedrock version and a Geyser dump, please add those.

**Comment by mastachef** [comment]
> You're missing the affected Bedrock version and a Geyser dump, please add those.

added

**Comment by mahehro** [comment]
The same on PS4/PS5 when trying to connect via BedrockTogether or BedrockConnect. All since the new version (1.20.40).

**Comment by DenzeOne1** [comment]
Hi, did you solve this problem?

**Comment by mahehro** [comment]
> Hi, did you solve this problem?

Nop. Everyone with Bedrock version 1.20.40 is affected, on all devices.
