### ISSUE TITLE
Mobile players can 'break' blocks at a far distance (visually)

### ISSUE THREAD

**Issue by Camotoy** [GeyserMC/Geyser#425]
**Describe the bug**
In creative mode on iOS or Android, attempt to break a block from far away. The client will think it's successfully broken when in fact it is not.

**To Reproduce**
On iOS or Android, break a block far away.

**Server Version**
Vanilla 1.15.2

**Geyser Version**
Master 79

**Minecraft: Bedrock Edition Version**
v1.14.60

**Additional Context**
https://wiki.vg/Protocol#Player_Digging "A Notchian server only accepts digging packets with coordinates within a 6-unit radius between the center of the block and 1.5 units from the player's feet (not their eyes). "

What would be ideal is to request the server for what block is at that position every time we break, but there appears to be no Java packets for that. I have a private branch where I send a message every time you break a block too far away, but that's not a perfect system and not a perfect solution.

**Comment by endevrr** [comment]
**Note**: To calculate distance to block use Pythagoras, `a^2+b^2=c^2` Where `a=player's X coord`, `b=player's Y coord` and `c = Distance from player to block`

**Comment by lukeeey** [comment]
Isn’t that only for right angled triangles?

**Comment by Heath123** [comment]
> 
> 
> Isn’t that only for right angled triangles?

Yes.

+---------------------Block
|  Right angle
| 
| 
Player

**Comment by lukeeey** [comment]
Ahh

**Comment by Heath123** [comment]
Better image:
![image](https://user-images.githubusercontent.com/13787163/81449150-882ce200-9177-11ea-9caf-ac962cbbb626.png)

**Comment by zanson** [comment]
I noticed this in survival as well.  I could mine bricks that would "break" and then re-appear because they were actually too far away.

**Comment by Camotoy** [comment]
This should be fixed. :)

**Comment by richbirch** [comment]
I'm seeing this issue with the latest papermc & geyser
