### ISSUE TITLE
Velocity/BungeeCord servers network: multiple instances runned, but the same port is used

### ISSUE THREAD

**Issue by ChefMC** [GeyserMC/Geyser#4262]
### Describe the bug

Velocity/BungeeCord servers network: multiple instances runned, but the same port is used. How to handle this network and have Geyser be able to use on multiple Velocity/BungeeCord instances?

### To Reproduce

^

### Expected behaviour

^

### Server Version and Plugins

1.20.2

### Geyser Version

All versions

**Comment by onebeastchris** [comment]
Simply put, you can't - different Geyser instances on the same machine need to run on different ports to work.

In case the question is about whether all servers connected by the proxy (backend servers as we call those) need to run Geyser, that would be a no - you only install Geyser on the proxy itself.

**Comment by onebeastchris** [comment]
Closing this as this isn't a bug/feature request; for help, ask in the Geyser discord server
