### ISSUE TITLE
Could not find an entity definition with type ITEM_DISPLAY

### ISSUE THREAD

**Issue by DexterSK** [GeyserMC/Geyser#4267]
### What feature do you want to see added?

Is there a way to disable/supress this warning?

`[Geyser-Spigot] Could not find an entity definition with type ITEM_DISPLAY`

### Are there any alternatives?

checking config file

**Comment by onebeastchris** [comment]
#4270 Moved the warning to debug level, so logs should not be spammed anymore - this however does not implement/make item or block displays show up.
