### ISSUE TITLE
"Connection Closed" and Whitelist message not showing

### ISSUE THREAD

**Issue by HzDeimos** [GeyserMC/Geyser#4272]
### Describe the bug

Whenever a player tries to join the server when it's whitelisted it kicks them out of the network and displays "Connection Closed"

This also happens when a player tries to join without registering. It should display AuthMe message but it says "Connection Closed"

Also some bedrock players are unable to join the server even when they're registered and the server is not whitelisted. The only error message they get is "Connection Closed"

This is really weird because most of the bedrock players are able to join. So I don't know why some of them can't.

### To Reproduce

Un-whitelist server
Try to join the server
Get the "connection closed" error message.

### Expected behaviour

Displaying the correct kick message (whitelist and authme message)

### Screenshots / Videos

Here is a video clip from a player who is unable to join:
https://github.com/GeyserMC/Geyser/assets/86536884/c0d3d53a-5c3b-4cd4-a8cd-cfd2328e5558

### Server Version and Plugins

git-Purpur-1632 (MC: 1.18.2)*
* You are running the latest version

Authme 5.6.0
Viaversion 4.8.1
Viabackwards 4.8.1
Geyser 2.2.0-SNAPSHOT (git-master-ec526a7)
Floodgate 2.2.2-snapshot (b85-71acc6c)

### Geyser Dump

https://dump.geysermc.org/CvvndUa2AVDPDpGOzfV8OiMoR55YCCzk

### Geyser Version

Geyser version 2.2.0-SNAPSHOT (git-master-ec526a7) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.40)

**Comment by onebeastchris** [comment]
Please send a full log via mclo.gs

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/commit/4e0cc92e93cf9e7f9bd9f529968aac7fe04a9153 should resolve this.
