### ISSUE TITLE
bossbar is retained after server switch

### ISSUE THREAD

**Issue by ch4ika** [GeyserMC/Geyser#4273]
### Describe the bug

The boss bar is retained on the server switch and stacks even if it is sent again and again.
The same is with rain, which remains after the switch.

We use the standalone Version over floodgate velocityproxy and backendservers.

### To Reproduce

/bossbar add test 123
/bossbar set minecraft:test players <player>

switch server 

### Expected behaviour

As soon as you switch the server, the boss bar should not be retained by the other server

### Geyser Version

 This server is running Geyser version 2.2.0-SNAPSHOT (git-master-8d2ebcf) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.40)

**Comment by onebeastchris** [comment]
Do Java 1.20.2 clients experience the same issue?

**Comment by ch4ika** [comment]
I just tried it, only Bedrock players have the problem.'

Important info: It can only be reproduced with Velocity with GeyserStanderlone and floodgate

**Comment by onebeastchris** [comment]
Could you try the build from the linked PR (https://github.com/GeyserMC/Geyser/pull/4278/checks) once it builds and see if that resolves the issue?

**Comment by ch4ika** [comment]
yes, that is fixed.

**Comment by Tamikaschu** [comment]
Im not quite sure if its worth opening a new issue but also rain is retained after server switch under the same conditions as with the bossbar.

**Comment by onebeastchris** [comment]
@Tamikaschu if true, please test with e.g. thunder or similar, and open a new issue
The bossbar/air bubbles etc should now be properly cleared.
