### ISSUE TITLE
Custom lore crashes bedrock clients

### ISSUE THREAD

**Issue by Z3r0xh** [GeyserMC/Geyser#4277]
### Describe the bug

Since the geyser update to 1.20.40, certain items with custom lore are causing bedrock players to crash

### To Reproduce

Using ItemEdit

You put lore like the one in the video and everything is fine.

Move it while it is made of bedrock and it will expel you.

I leave you a video of the problem

https://youtu.be/lAAOQzcnMqk

It is only a problem of the lores, not of the enchantments or anything else.

### Expected behaviour

These items did not expel anyone before and were functional, but with the latest update certain lores cause them to expel players

### Screenshots / Videos

https://www.youtube.com/watch?v=lAAOQzcnMqk&ab_channel=Neah
https://youtu.be/lAAOQzcnMqk

### Server Version and Plugins

Proxy: NullCordX last version

Backend: This server is running Pufferfish version git-Pufferfish-27 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 979d3a2 on HEAD)
Previous version: git-Pufferfish-26 (MC: 1.20.1)

### Geyser Dump

https://dump.geysermc.org/F6eIv7n0AZXWcfJanYaRTrq2MmuQUSEK

### Geyser Version

This server is running Geyser version 2.2.0-SNAPSHOT (git-master-574dad0) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.40)

### Minecraft: Bedrock Edition Device/Version

movile, pc, 1.20.41

### Additional Context

The lores that give expulsions if certain lines are deleted work fine again, it's strange, but it's breaking everything for me

**Comment by onebeastchris** [comment]
"Connection closed" would usually indicate a server error. Please attach full server logs via mclo.gs - both from the proxy with Geyser, and the backend server.

**Comment by onebeastchris** [comment]
Closing due to no further response. If this issue still occurs, send a full log here
