### ISSUE TITLE
Weather retained on server switch

### ISSUE THREAD

**Issue by Tamikaschu** [GeyserMC/Geyser#4280]
### Describe the bug

Weather is being retained for Bedrock players when they switch servers.
This allows Bedrock players to use e.g tridents to fly around on not raining servers.

### To Reproduce

Use Velocity and Geyser standalone (same conditions as in #4273)
Set weather to rain or thunder on one server
Let a Bedrock player switch from this to another server

### Expected behaviour

Weather should not be retained from one to another server.

### Server Version and Plugins

```
Paper version git-Paper-264 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 230682d)

FastAsyncWorldEdit
floodgate
PlotSquared
```

### Geyser Version

Geyser Version 2.2.0-SNAPSHOT (git-master-f40ca20)

### Minecraft: Bedrock Edition Device/Version

1.20.41, Windows

**Comment by onebeastchris** [comment]
Can you test the build found under `Checks` in the linked PR? It should reset the weather when switching servers.

**Comment by Tamikaschu** [comment]
Should be fixed now!
