### ISSUE TITLE
Absorption hearts are retained on server switch

### ISSUE THREAD

**Issue by Tamikaschu** [GeyserMC/Geyser#4286]
### Describe the bug

Absorption (Extra) Hearts are retained when switching servers

### To Reproduce

(Use Velocity and Geyser Standalone)
- Eat a golden apple on one server
- Switch to another server

### Expected behaviour

Extra hearts should not be retained when switching servers

### Server Version and Plugins

Paper version git-Paper-264 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 230682d)

PlotSquared
floodgate
FastAsyncWorldedit

### Geyser Version

Geyser Version 2.2.0-SNAPSHOT (git-DEV-1da1c99)

**Comment by onebeastchris** [comment]
Please attach a Geyser dump (run `geyser dump` in the console) - this should have been resolved in https://github.com/GeyserMC/Geyser/commit/aa899af90812af4f726dc971ef30a81bd10786d4

**Comment by Tamikaschu** [comment]
I'm using [81178ba](https://github.com/GeyserMC/Geyser/commit/81178ba2a070aa41a133c3817759c7b43e262d12)
Running `geyser dump` in console & ingame wont give me a Geyser dump right now

**Comment by onebeastchris** [comment]
according to the version you sent, you're running a dev version atm - that likely isn't up-to-date with master. Please switch back to the version found on https://geysermc.org/download - it too contains the weather reset fix.

**Comment by Tamikaschu** [comment]
Updating to Geyser Version 2.2.0-SNAPSHOT (git-master-4e0cc92) isn't resolving the problem

**Comment by onebeastchris** [comment]
Please send a geyser dump - without one, there's no way to verify that

**Comment by Tamikaschu** [comment]
How would i get geyser dump on standalone? The commands are not working for me in console neither ingame

**Comment by onebeastchris** [comment]
you can run the command in the geyser standalone console

**Comment by Tamikaschu** [comment]
https://dump.geysermc.org/uFAO2UsfpFnwlLnDn3gYkHyMbFqWfo4N

**Comment by onebeastchris** [comment]
Unable to reproduce with:
- Velocity build 294
- 2 paper 1.20.2 backends
- Geyser Standalone running https://github.com/GeyserMC/Geyser/commit/13339f1ed1273050fafd553ea6210c635d24e4a7 (build 355)

Please try reproducing the issue on a clean setup without plugins - and please ensure that you aren't accidentally using/joining via Geyser on a different server.

**Comment by Tamikaschu** [comment]
Using Velocity build 294 with Geyser Standalone build 355 seems to have fixed the problem
