### ISSUE TITLE
Fabric server reported an error

### ISSUE THREAD

**Issue by Adogs1** [GeyserMC/Geyser#4291]
### Describe the bug

log：
When I join the server or enter any portal reloading world, the server always reports an error

### To Reproduce

as above

### Expected behaviour

It does not report errors on the server

### Screenshots / Videos

![QQ截图20231114233125](https://github.com/GeyserMC/Geyser/assets/111733210/fee4bd21-f43a-40c9-8a44-564a4e439c0b)

### Server Version and Plugins

1.20.2Fabric
![QQ截图20231114233242](https://github.com/GeyserMC/Geyser/assets/111733210/62a54093-5277-4c16-a054-4955930ac7c2)
![QQ截图20231114233315](https://github.com/GeyserMC/Geyser/assets/111733210/553585c2-2ec4-49bc-931f-76aec1f865d9)

### Geyser Version

geyser-fabric-2.2.0-SNAPSHOT+build.357

### Minecraft: Bedrock Edition Device/Version

1.20.41.02

**Comment by onebeastchris** [comment]
Please set `debug-mode` to true in your Geyser config file, and send a full latest.log file using e.g. mclo.gs or mcpaste.io

**Comment by Adogs1** [comment]
> 请在您的 Geyser 配置文件中设置为 true，并使用例如 mclo.gs 或 mcpaste.io 发送完整的 latest.log 文件`debug-mode`

Using only geyser on fabric, Java player transfers will also cause this error to pop up.
And I have found a solution: install a carpet on the fabric and enable the anti CheatDisabled rule, so it no longer pops up these errors

**Comment by Adogs1** [comment]
> 请在您的 Geyser 配置文件中设置为 true，并使用例如 mclo.gs 或 mcpaste.io 发送完整的 latest.log 文件`debug-mode`

https://mclo.gs/7sXC8NN

**Comment by onebeastchris** [comment]
Please enable `debug-mode` in Geysers config, restart, and send a new log - it currently only shows a brief error, not the full one

**Comment by Adogs1** [comment]
> 请在 Geysers 配置中启用，重新启动并发送新日志 - 它目前只显示一个简短的错误，而不是完整的错误`debug-mode`

I set the language to English, but I don't know how to enable debugging mode

**Comment by onebeastchris** [comment]
It's an option in Geysers config (/mods/Geyser-Fabric/config.yml)

**Comment by Adogs1** [comment]
> It's an option in Geysers config (/mods/Geyser-Fabric/config.yml)

https://mclo.gs/nNbxXCV
其中有一个java玩家和一个基岩玩家

**Comment by Adogs1** [comment]
> 这是间歇泉配置（/mods/Geyser-Fabric/config.yml）中的一个选项

If the repair is fast, I can help with testing this Friday evening (East Eighth District Time).

**Comment by onebeastchris** [comment]
It looks like one of your mods is adding a new command argument type. Could you try and see if the error still appears with no mods other than Geyser?

Furthermore, do non-modded 1.20.2 java clients experience issues?

**Comment by Adogs1** [comment]
> 看起来您的一个模组正在添加新的命令参数类型。你能试着看看除了间歇泉之外没有模组的情况下是否仍然出现错误吗？
> 
> 此外，未修改的 1.20.2 java 客户端是否遇到问题？

Confirmed to be caused by a mod
It's a fabric mod: bookshelf

**Comment by Adogs1** [comment]
> > 看起来您的一个模组正在添加新的命令参数类型。你能试着看看除了间歇泉之外没有模组的情况下是否仍然出现错误吗？
> > 此外，未修改的 1.20.2 java 客户端是否遇到问题？
> 
> 确认是由 mod 引起的 这是一个织物 mod：书架

它无法修复吗

**Comment by onebeastchris** [comment]
It might be possible to ignore the value, but ultimately, Geyser isn't designed for modded environments. A 1.20.2 Java client wouldn't like an extra command parameter added as well :/

**Comment by Adogs1** [comment]
OK，Thanks！
