### ISSUE TITLE
This problem occurred when I used the mythicmobs plug-in to generate the model in this package.

### ISSUE THREAD

**Issue by 1111qqjzja** [GeyserMC/Geyser#4295]
This problem occurred when I used the mythicmobs plug-in to generate the model in this package.

_Originally posted by @1111qqjzja in https://github.com/GeyserMC/Geyser/issues/4058#issuecomment-1813878422_

**Comment by 1111qqjzja** [comment]
[Uploading Summer_Vehicles_Hyrex-zzkhpz.zip…]()

**Comment by onebeastchris** [comment]
What is "this problem"?
So far, you've just said that there is one...

Additionally, please fill out the full issue template, with logs, a geyser dump, issue description, replication steps and expected behavior.

**Comment by 1111qqjzja** [comment]
the log is here
https://github.com/GeyserMC/Geyser/issues/4058

**Comment by onebeastchris** [comment]
In that case, you're reporting a duplicate issue - closing this as duplicate.
