### ISSUE TITLE
Bedrock Players Get Kicked Because of Time Out, Used To Work First

### ISSUE THREAD

**Issue by Minionguyjpro** [GeyserMC/Geyser#4297]
### Describe the bug

Hello! My friend could just join my server fine, but now he can't. It's because when he joins he stays in for 10-30 seconds and then gets kicked because of a time out. This used to work fine at first.

### To Reproduce

1. Get a Purpur 1.20.2 server.
2. Install Geyser, setup as usual with Floodgate too.
3. Try to join the server from Minecraft Bedrock on PS4 (version 1.20.41).
4. Time out.

### Expected behaviour

The player stays in, doesn't time out and can play. Like I said, this used to work fine.

### Server Version and Plugins

Current: git-Purpur-2089 (MC: 1.20.2)*
Previous: git-Purpur-2086 (MC: 1.20.2)
* You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Geyser Dump

https://dump.geysermc.org/9CXtZcPj82P9eFLK5tkz59dneIF2SL93

### Geyser Version

2.2.0-SNAPSHOT (git-master-4e0cc92)

### Minecraft: Bedrock Edition Device/Version

1.20.41, PS4

### Additional Context

The server connection outside goes via a tunnel using the site PlayIt.gg. I redirected the port 19132 and this used to work, my friend could join and play when the proxy that the tunnel uses still did go via Frankfurt, but now goes via London which is further away from my friend. It may or may not be the case, but still the ping between my server and the proxy is around the same as with Frankfurt.

**Comment by Minionguyjpro** [comment]
I enabled ``enable-proxy-protocol`` and reloaded Geyser. We weren't able to test yet as the controller stopped working at my friend's side with his PS4.

**Comment by Minionguyjpro** [comment]
> I enabled ``enable-proxy-protocol`` and reloaded Geyser. We weren't able to test yet as the controller stopped working at my friend's side with his PS4.

Turns out it didn't work...

**Comment by Camotoy** [comment]
`enable-proxy-protocol` should not be enabled here. Just to confirm that playit.gg isn't the issue, I would test with the vanilla Bedrock server binary.

**Comment by onebeastchris** [comment]
You also have quite a few plugins that are disabled, maybe due to errors.. a full log might help clear up issues

**Comment by markiedokie** [comment]
happens to me too sometimes the it shuts off or more like time out whenever theres no players have joined for too long 

im using playit to so is it the problem on playit? or on our end?

**Comment by markiedokie** [comment]
i think this is something to go with the lan discovery thing

**Comment by Minionguyjpro** [comment]
> You also have quite a few plugins that are disabled, maybe due to errors.. a full log might help clear up issues

Yeah I think it's time to update some first and see.

**Comment by Minionguyjpro** [comment]
> `enable-proxy-protocol` should not be enabled here. Just to confirm that playit.gg isn't the issue, I would test with the vanilla Bedrock server binary.

I will disable it, but the same issue appears. Whether it's enabled or disabled.

**Comment by Minionguyjpro** [comment]
> You also have quite a few plugins that are disabled, maybe due to errors.. a full log might help clear up issues

Here we go:
[latest.log](https://github.com/GeyserMC/Geyser/files/13402839/latest.log)

Don't mind the server running behind notification. It's due to the Hibernate plugin that slows things down very much when no one's on the server in order to save power.

**Comment by Minionguyjpro** [comment]
> i think this is something to go with the lan discovery thing

I also lowered ``view-distance`` in the server.properties file. Once my friend comes online we shall test whether that works.

**Comment by Minionguyjpro** [comment]
Hmmm, I disabled ``enable-proxy-protocol`` and when I do the ``connectiontest`` command it still reports that it is enabled. I reloaded the configuration by running ``geyser reload``.

**Comment by Minionguyjpro** [comment]
> Hmmm, I disabled `enable-proxy-protocol` and when I do the `connectiontest` command it still reports that it is enabled. I reloaded the configuration by running `geyser reload`.

A restart of the server fixed this, but it's still happening. It's really frustrating because now my friend can't join and I don't know why that is. Let me get the list of plugins:
![afbeelding](https://github.com/GeyserMC/Geyser/assets/66115754/573f8d2b-0c4e-4237-8fa4-76b217dba856)

**Comment by Minionguyjpro** [comment]
Turns out I am not the only one:
https://www.reddit.com/r/GeyserMC/comments/17g0qrw/bedrock_keeps_crashing/
Same issue, same Minecraft version.

**Comment by onebeastchris** [comment]
A few notes:
- your setup does not require any of the proxy config options, turn those off.
- the linked reddit comment is likely unrelated.

Then: Please turn on `debug-mode` in Geysers config, join the server with Bedrock, and then send that log with the disconnection showing. Realistically speaking, that'll be the best shot at trying to resolve this.

**Comment by Minionguyjpro** [comment]
> A few notes:
> 
>     * your setup does not require any of the proxy config options, turn those off.
> 
>     * the linked reddit comment is likely unrelated.
> 
> 
> Then: Please turn on `debug-mode` in Geysers config, join the server with Bedrock, and then send that log with the disconnection showing. Realistically speaking, that'll be the best shot at trying to resolve this.

I will try this later once my friend comes online.

**Comment by Minionguyjpro** [comment]
> A few notes:
> - your setup does not require any of the proxy config options, turn those off.
> - the linked reddit comment is likely unrelated.
> 
> Then: Please turn on `debug-mode` in Geysers config, join the server with Bedrock, and then send that log with the disconnection showing. Realistically speaking, that'll be the best shot at trying to resolve this.

Okay finally, there you go:
https://pastebin.com/dRWCrfKe

**Comment by onebeastchris** [comment]
Does this issue still occur with the latest version of Geyser? If yes, please send a new log

**Comment by Minionguyjpro** [comment]
> Does this issue still occur with the latest version of Geyser? If yes, please send a new log

It sometimes does but it happens less. I think it's just his internet connection and is caused because the location of the tunnel changed from Frankfurt to London to open the server outside. He lives in a country that is closer to the Frankfurt one, but since they changed it to London we are stuck with that and that's slower for him.

**Comment by Kas-tle** [comment]
Closing since based on your response this is network related.
