### ISSUE TITLE
java.nio.channels.ClosedChannelException - On 2.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by TechnicallyCoded** [GeyserMC/Geyser#4298]
### Describe the bug

Bedrock players unable to connect. No one, not me, not other players, not right after startup, not after.  
(Java connection works perfectly fine)

### To Reproduce

1. Connect using bedrock (I was using a phone)

### Expected behaviour

Connect to server

### Screenshots / Videos

https://mclo.gs/6d5F3D7

### Server Version and Plugins

Velocity 3.2.0-SNAPSHOT (git-8dcc7ee3-b294)

### Geyser Dump

https://dump.geysermc.org/ZmIy0sJxmBuVkUYvxXE2EWuh8Tk6krfg

### Geyser Version

Geyser version 2.2.0-SNAPSHOT (git-master-dec0d13) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.40)

### Minecraft: Bedrock Edition Device/Version

1.20.41

**Comment by shiv-singh-shah** [comment]
Happen to me too but I'm on 1.20.32

**Comment by TechnicallyCoded** [comment]
Any updates?

**Comment by TechnicallyCoded** [comment]
I gave you the logs. To match the amount of help I got from this answer, I won't provide an answer as to what fixed this. I had other people help me fix the issue.

**Comment by TechnicallyCoded** [comment]
The backend had nothing to do with it. The fix was on the proxy alone :)
