### ISSUE TITLE
Config Doesn't Reload when Running ``geyser reload``, Reboot Required to Apply

### ISSUE THREAD

**Issue by Minionguyjpro** [GeyserMC/Geyser#4299]
### Describe the bug

This is a bug on the latest build where it doesn't save the changes until the Minecraft server reboots and the whole plugin reloads. I have reproduced this on build 2.2.0-SNAPSHOT (git-master-118e769).

### To Reproduce

1. Get a Purpur 1.20.2 server.
2. Change something in the configuration and save.
3. Reload the configuration with ``geyser reload``.
4. It doesn't apply the changes, until a restart of the server is being done.

### Expected behaviour

The changes get applied, without needing a restart of the server.

### Server Version and Plugins

Current: git-Purpur-2092 (MC: 1.20.2)*
Previous: git-Purpur-2089 (MC: 1.20.2)
* You are running the latest version
​
 Bukkit Plugins: (21):
- AutoPlug-Plugin, *BukkitOptimizer, Chunky, ClearLag, DiscordSRV, DriveBackupV2, floodgate, Geyser-Spigot, GSit, Hibernate, HideNametag, LaggRemover, PlaceholderAPI, *PluginUpdater, ProtocolLib, *SetHome, spark, ViaBackwards, ViaRewind, ViaVersion, WorldEdit

### Geyser Dump

https://dump.geysermc.org/l4st8Ap06H1zJYrGlHT2GvwspTGJF03z

### Geyser Version

2.2.0-SNAPSHOT (git-master-118e769)

**Comment by onebeastchris** [comment]
This is currently inconsistent across platforms:
- Bungee/Spigot platforms *don't* reload configs with the reload command
- Velocity, Fabric, Standalone *do* reload configs.

Marking as confirmed bug, please restart instead of reload for now.
