### ISSUE TITLE
The crafting recipe of fireworks is not displayed in the crafting table, and there are exceptions when synthesizing

### ISSUE THREAD

**Issue by RICE0707** [GeyserMC/Geyser#4301]
### Describe the bug

The synthesis recipe of fireworks is not displayed in the crafting table, and there are exceptions when synthesizing.
- In the mobile version, stacking fails when trying to batch crafting.
- In the Windows version, when trying to batch synthesize, an "unspeakable" situation occurs and there is no normal crafting.

### To Reproduce

1. Open crafting table
2. Place the crafting materials for fireworks on the crafting table
3. Batch crafting

### Expected behaviour

The crafting recipe for fireworks should be displayed on the crafting table,
And when batch crafting, "unspeakable" should not occur. After synthesis, it should also automatically stack with the fireworks in the backpack.

### Screenshots / Videos

mobile version:
https://cdn.discordapp.com/attachments/1175853509208453201/1176023244533407824/VID20231120125513.mp4

Windows version:
![1](https://github.com/GeyserMC/Geyser/assets/68499464/789d7ddd-188e-4c4e-9d5c-2c50833ede7f)

### Server Version and Plugins

git-Purpur-2082 (MC: 1.20.2)
```
Bukkit Plugins: (70):
- AutoTotem, BedrockPlayerManager, BlockLocker, BrilliantGayPlugin, BrilliantPollution, ChestSort, Chunky, CMILib, CoreProtect, creative-central
DiscordSRV, Drop2InventoryPlus, *Ersatz, Essentials, *explock, FastAsyncWorldEdit, floodgate, GeyserHacks, GlobalMarketPlus, GSit
HeadDatabase, HiddenArmor, HttpDonationAPIReborn, ImageFrame, InteractiveChat, InteractiveChatDiscordSrvAddon, InventorySaver, Join-Leave, Kitty, LibsDisguises
LiteAnnouncer, LiteBans, LiteSignIn, LoneLibs, LuckPerms, MaterialExchange, Matrix, MiningBonus, NatureRevive, NBTAPI
NoMobLag, Nurfpemtume, OreModitor, PlaceholderAPI, PlayerPoints, ProtocolLib, Residence, RHSignItem, SafetyLeashes, *ServerReturn
ShapePortal, ShulkerBoxPreview, SkBee, Skript, *skript-placeholders, skript-reflect, SomeCreativeLimit, spark, SuperHarvest, TAB
TabTPS, TaiwanifyEveryItem, Tether, UnbreakableLeashes, unemojis, Vault, VentureChat, *VentureChatTrigger, ViaBackwards, ViaVersion
```

### Geyser Dump

https://dump.geysermc.org/lXNZ9o8goBrVyipAenTAknUQGwPOAM9Y

### Geyser Version

Geyser-Standalone Build #1538

### Minecraft: Bedrock Edition Device/Version

1.20.41 / PC and PE

**Comment by onebeastchris** [comment]
Do you have the firework recipe unlocked?
In other words; try unlocking the recipe manually and see if it appears (`/recipe give @s minecraft:firework_rocket` and `/recipe give @s minecraft:firework_rocket_simple`; or just `/recipe give @s *` for all recipes). That should be the only reason why a recipe would not show up.

**Comment by RICE0707** [comment]
> Do you have the firework recipe unlocked? In other words; try unlocking the recipe manually and see if it appears (`/recipe give @s minecraft:firework_rocket` and `/recipe give @s minecraft:firework_rocket_simple`; or just `/recipe give @s *` for all recipes). That should be the only reason why a recipe would not show up.

我嘗試使用了 `/recipe give @s minecraft:firework_rocket` and `/recipe give @s minecraft:firework_rocket_simple `，但均顯示` No new recipes were learned `

**Comment by RICE0707** [comment]
In addition, I found that the batch compositing error only occurs when the UI Profile is set to Pocket. After changing it to Classic, the batch compositing error no longer occurs.

**Comment by RICE0707** [comment]
However, the error that `firework recipes` is not displayed exists in both `Classic` and `Pocket`.

**Comment by RICE0707** [comment]
In the changes at https://github.com/GeyserMC/Geyser/commit/119fbc86bc36f0cf2c1373ae462493386a47d2e6,
The crafting exception for `Pocket` has changed, but is still an exception.
- Geyser-Standalone Build # 364
![crafting](https://github.com/GeyserMC/Geyser/assets/68499464/2a69348d-36a0-4960-bea2-a6f6dd9bf14d)
