### ISSUE TITLE
Able to see names of TextDisplay entities on Bedrock, overriding the real text

### ISSUE THREAD

**Issue by Oth3r** [GeyserMC/Geyser#4308]
### Describe the bug

Setting the name of a TextDisplay, the text in the text display doesn't get shown, overridden by the custom name on bedrock.

### To Reproduce

Spawn a custom text display with a name and some custom text, `/summon minecraft:text_display ~ ~ ~ {CustomName:"\"Shouldnt be able to see this\"",text:'{"text":"real text"}'}`

### Expected behaviour

The text display's custom name should be invisible on bedrock, and show the text in the display instead of the custom name.

### Screenshots / Videos

![11 22 23-22 08 58](https://github.com/GeyserMC/Geyser/assets/68134921/27c02b3c-27a4-4209-9870-590774bc6d8f)
![11 22 23-22 18 27](https://github.com/GeyserMC/Geyser/assets/68134921/3c533126-d66f-49b2-9e03-c1832150d184)

### Server Version and Plugins

This happens on Geyser-Fabric, on 1.20+

### Geyser Version

2.2.0-SNAPSHOT (git-master-118e769)

### Minecraft: Bedrock Edition Device/Version

1.20.41, PC

**Comment by onebeastchris** [comment]
@Oth3r Thanks for the bug report. Could you test the Geyser build found under the `Checks` tab in the linked PR and see if that resolves the issue?
