### ISSUE TITLE
Cannot Take Villager Spawn Eggs

### ISSUE THREAD

**Issue by Loganh4005** [GeyserMC/Geyser#431]
**Describe the bug**

Can not Grab a Villager Spawn egg from creative Inventory, It changes to a bat spawn egg. Same For Zombie Villager Spawner

**To Reproduce**

1. Try to Take a Villager and Zombie Villager Spawn Egg
2. See Error
3. Or close the creative menu and See Error

**Expected behavior**

Be able to grab a villager and zombie villager

**Screenshots / Videos**

https://streamable.com/4wxb7p

**Server Version**

Paper version git-Paper-211 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**

#90 Geyser Version Master With Floodgate

**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

https://github.com/GeyserMC/mappings/pull/13 Should Fix It

**Comment by blubbll** [comment]
yeah, same here, the villager just gives me a bat lol

**Comment by Loganh4005** [comment]
Update Geyser
