### ISSUE TITLE
Bedrock players can no longer open menus in spectator mode

### ISSUE THREAD

**Issue by Astolate** [GeyserMC/Geyser#4312]
### Describe the bug

When in spectator mode bedrock accounts cannot open any menus, it just instantly closes. It did not used to do this a few versions back, it worked the same as java then.

### To Reproduce

1. Join a minecraft server that uses geyser on a bedrock account.
2. Go into spectator mode.
3. Attempt to open any menu and it will instantly close. 

### Expected behaviour

It's expected that it will open the menu the same way it does on java, it used to a few versions of Geyser ago.

### Screenshots / Videos

first half of video shows what bedrock does second half shows how java works: https://www.youtube.com/watch?v=2dyUrqAwL00

### Server Version and Plugins

This server is running Pufferfish version git-Pufferfish-"979d3a2" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) 

### Geyser Dump

https://dump.geysermc.org/5JKR5EqvcOtxjlxHznrdnShG9uOgAW0P

### Geyser Version

2.2.0-SNAPSHOT (git-master-44174fd)

### Minecraft: Bedrock Edition Device/Version

v1.20.41 ios (but results are the same on all bedrock devices with the most current client)

**Comment by onebeastchris** [comment]
That's a result of https://github.com/GeyserMC/Geyser/commit/3ec591509c6998221a23546d2db396fac28ab747 - Bedrock's native spectator mode unfortunately doesn't show any inventory/hotbar/etc.
This might be reverted again in the future to allow Bedrock players to spectate entities.
