### ISSUE TITLE
Bad packet id 13

### ISSUE THREAD

**Issue by AngelBePro** [GeyserMC/Geyser#4327]
### Describe the bug

Whenever you try to join, you are stuck at locating server

### To Reproduce

1. Join server
2. Quickly leave (under 5 mins)
3. Try to join again
4. You are stuck at "Locating server"

### Expected behaviour

Quickly join server withouth "Locating server" taking too long (should take a second or two, not more)

### Server Version and Plugins

[16:59:33 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version

### Geyser Dump

https://dump.geysermc.org/OSvS9TW9hGd24FkMbT8ZzswdoxaVvcXK

### Geyser Version

2.2.0-SNAPSHOT (git-master-998caee)

### Minecraft: Bedrock Edition Device/Version

1.20.15 pocket edition, and viaversions installed since server requires 1.20.50

### Additional Context

The exception it gives when it stucks:
```[16:39:23 INFO]: AngelBePro lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 13``` Very sorry if this is not a bug and a common issue.

**Comment by onebeastchris** [comment]
Try using ViaVersion 4.8.1 for now - it's far from ideal, but it should fix the issue temporarily. We're talking with ViaVersion about whether it's an issue on our side or their side (https://github.com/ViaVersion/ViaVersion/issues/3548, for reference)

**Comment by AngelBePro** [comment]
Thanks, that worked!

**Comment by AngelBePro** [comment]
Ok, no problem

**Comment by onebeastchris** [comment]
Fixed in Viaversion (https://github.com/ViaVersion/ViaVersion/issues/3548). Feel free to update viaversion again to the latest build!
