### ISSUE TITLE
ip_forward issue (Waterdog / Bungeecord)

### ISSUE THREAD

**Issue by totoberg123** [GeyserMC/Geyser#433]
**Describe the bug**
When using Waterdog (Bungeecord) the ip_forward function is not working properly with Geyser.

When I connect as W10 Bedrock client to the Bungeecord, and proceed to the Lobby server it all works good. When I then connect to the Paper (Spigot) server it disconnected with the following message:
> if you wish to use ip forwarding please enable it in your bungeecord config as well

In fact ip_forwarding is already set to true. When I set bungeecord to false in the Paper (Spigot) server I can connect without any problems. But then I am not able to transfer my players back to the lobby with signs oid..

**Expected behavior**
Able to join with bungeecord set to true so I can transfer players between servers.

**Screenshots / Videos**
Diagram: https://imgur.com/sHO6fUg

**Server Version**
Waterdog `Waterdog-Bootstrap:1.15-SNAPSHOT:a556bfd:308`
Nukkit (Lobby) `Nukkit version git-1deed3a "" (API 1.0.9)`
Paper* `git-Paper-208 (MC: 1.15.2)` 

**Geyser Version**
Not using Floodgate. Running the plugin in Spigot (see above).

Redned post in #announcements a post (26-04 @ 7:40 AM):
We're doing another sound and particle effects build. This is to help us identify missing sounds and missing particle effects.

I am using the Geyser-Nukkit.jar file from that Discord post.

**Minecraft: Bedrock Edition Version**
Windows 10 Edition (up-to-date)

**Additional Context**
I use a plugin with the following:
`this.getServer().getMessenger().registerOutgoingPluginChannel(this, "BungeeCord");`
For this to work I need bungeecord set to true, but then players are not able to join.

**Comment by AnonAlpha** [comment]
I think you need to set geyser up on bungeecord, for that's how I fixed the same problem

**Comment by totoberg123** [comment]
Floodgate fixed it for me. This is how it works for me:

**Bungeecord plugins**:
- Geyser
- Floodgate

**Bukkit/Spigot plugins**:
- Floodgate
