### ISSUE TITLE
Geyser never say [Geyser-Spigot] Geyser shutdown successfully

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#4334]
### Describe the bug

![image](https://github.com/GeyserMC/Geyser/assets/88581750/7d2a5f3e-2682-45be-b141-1cb15cd621fe)
hmm am wondering when i shutdown the server by using /stop the log just stucked at this moment and it's never end up the cmd it should send [Geyser-Spigot] Geyser shutdown successfully and server goes shutdown as well but it wasn't and keeps stucked at there so am not sure what to do so when i just forced shutdown server with clicked x button yeah it just reset old datas since the server didn't got saved 

### To Reproduce

type /stop for shutdown server cmd got stucked after it said [Geyser-Spigot] Kicked All Users.! and do nothing

### Expected behaviour

am not sure sometimes it doesn't happen but its so suddenly happend to me 

### Screenshots / Videos

Full logs https://mclo.gs/f8EYWyE 
![image](https://github.com/GeyserMC/Geyser/assets/88581750/7d2a5f3e-2682-45be-b141-1cb15cd621fe)

### Server Version and Plugins

Current: git-Purpur-2097 (MC: 1.20.4)*
Previous: git-Purpur-2095 (MC: 1.20.2)
* You are 1 version(s) behind

### Geyser Dump

https://dump.geysermc.org/NLc6vDwIFW6BA5eYtozeIiZEbiqKKmFa

### Geyser Version

Geyser-Spigot v2.2.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20.50

**Comment by onebeastchris** [comment]
Please try without any other plugins besides Geyser and Floodgate, and see if the issue persists

**Comment by adalmo** [comment]
it got fixed after i uninstall discordsrv
