### ISSUE TITLE
Autofill

### ISSUE THREAD

**Issue by Landy005** [GeyserMC/Geyser#4338]
### What feature do you want to see added?

 Support autofill for java plugins.
 
 Especially for builders and creators this would be handy.
Imagine for fawe it could autofill when typing block names etc... it would close a big gap between java and bedrock builders who are using geyser on java servers.
Iust thinking about my fellow bedrock builders 

### Are there any alternatives?

No there aren't

**Comment by Konicai** [comment]
Autofill of what? 

>Imagine for fawe it could autofill when typing block names etc

commands?

**Comment by Landy005** [comment]
Yes commands, like 
![image](https://github.com/GeyserMC/Geyser/assets/16018643/70e1d29b-f6ef-4f01-9cc6-93e5ca5624fb)

**Comment by Camotoy** [comment]
We can't easily add this. These autocompletions are requested as a Java client types it - Bedrock does not send what it is typing until the enter key is pressed.

It is possible but it's outside the scope of Geyser. An additional plugin would have to add support, or plugins like FAWE would have to hook into theoretical API that does not exist.

**Comment by Konicai** [comment]
Also listed here: https://wiki.geysermc.org/geyser/current-limitations/
