### ISSUE TITLE
Wardrobe sitting bug (?)

### ISSUE THREAD

**Issue by FrancescoJacovo** [GeyserMC/Geyser#4341]
### Describe the bug

I'm using the last version of everything, geyser, floodgate, CosmeticsCore, ItemsAdder, LoneLib, ProtocolLib and server.jar

The bedrock player glitch when enter the wardrobe. Idk if it force dismount off the armor stand or it's something else, maybe i'm still on it but cannot dismount.

The problems are: 
1. It'll close instantly the wardrobe menu that opens after entering the wardrobe (probably the frames were skipped in the gif)
2. You cannot click/interact to re-open the wardrobe menu 
3. You cannot SHIFT to exit. 

### To Reproduce

install all latest version and enter the wardrobe

### Expected behaviour

It'll glitch the player out of the armor stand or maybe disabling in same way the PlayerInteractEvent and the dismount.

### Screenshots / Videos

https://imgur.com/a/IuJc246

### Server Version and Plugins

I tried with:
- 1.17.1-R0.1 
- 1.19.2-R0.1

I tried also without any other plugin (same problems):
![2023-12-15_11 25 58_edited](https://github.com/GeyserMC/Geyser/assets/8696665/ede5bb01-4194-415a-b91e-1aa7ac9433c8)

### Geyser Dump

https://dump.geysermc.org/VPw0NMxZJLnGr5WipwCXL9t8JlaRgNxd

### Geyser Version

2.2.0

### Minecraft: Bedrock Edition Device/Version

1.20.51

**Comment by onebeastchris** [comment]
Is the player being switched to spectator mode while in the menu?
Also, please send a screenshot of the player menu on Java.

**Comment by FrancescoJacovo** [comment]
Not sure which gamemode is because it makes u invisibile the Player, items, hotbar and hand but u not see the invisibile armor stand near u (Idk if its possibile to make that in spectator with packets)

**Comment by FrancescoJacovo** [comment]
This is the Java behavior https://youtu.be/TU2ezGDsoZA?si=cSmSWN-_a39vo31U

**Comment by FrancescoJacovo** [comment]
Any news?

**Comment by FrancescoJacovo** [comment]
Guys?

**Comment by onebeastchris** [comment]
We don't have an update for now, would have responded otherwise.

Merry Christmas!

**Comment by FrancescoJacovo** [comment]
Happy New Year to u! 

Hope there's some news, this problem is present from the 1.20 first geyser release

**Comment by FrancescoJacovo** [comment]
Any news?

**Comment by onebeastchris** [comment]
Please test the geyser build from the "actions" tab in the linked PR and see if it resolves the issue.
