### ISSUE TITLE
Unable to create Maps at Cartography table 

### ISSUE THREAD

**Issue by mddunner** [GeyserMC/Geyser#4344]
### Describe the bug

Unable to create/change maps in the cartography table. When adding resources to the cartography table inventory, they are immediately kicked back to the player inventory.

### To Reproduce

Use Geyser-Velocity + Paper Backend
Place cartography table
Unable to put in a map/compass

### Expected behaviour

Ability to use the cartography table

### Server Version and Plugins

Velocity 3.2.0
Geyser 2.2.0-SNAPSHOT (git-master-3292718)
Bedrock 1.20.51

### Geyser Dump

None

### Geyser Version

2.2.0-SNAPSHOT (git-master-3292718)

### Minecraft: Bedrock Edition Device/Version

1.20.51

### Additional Context

Appears to be a duplicate of https://github.com/GeyserMC/Geyser/issues/3081
However, the cartography table always fails.

**Comment by onebeastchris** [comment]
Is this still an issue? Unable to replicate it on my end

**Comment by mddunner** [comment]
> Is this still an issue? Unable to replicate it on my end

It seems that this was a Minecraft client version issue. Bedrock players did not know the crafting ingredients were different for Maps at Cartography table. I believe we are good now. Thanks for the response!
