### ISSUE TITLE
Connection closed. (Velocity)

### ISSUE THREAD

**Issue by duman3344** [GeyserMC/Geyser#4345]
### Describe the bug

I have a bug when connecting a bedrock player. I have a Velocity proxy. Before the Geyser update, everything was fine, but after updating to “2.2.0-SNAPSHOT (git-master-58ff00d)” I started getting the error “Connection closed.”

### To Reproduce

1. Update geyser
2. Try to connect server(Velocity)
3. Get the "connection closed" error message.

### Expected behaviour

So that the bedrock player enters the velocity without the error "Connection closed."

### Server Version and Plugins

1.18.2, Protocolize, Floodgate, Geyser, Velocity-tools

### Geyser Dump

https://dump.geysermc.org/Lfw5RYXKPvmbSrbOu2DsG4ckX6frcdre

### Geyser Version

2.2.0-SNAPSHOT (git-master-58ff00d)

### Minecraft: Bedrock Edition Device/Version

1.20.40, Minecraft Windows

### Additional Context

Velocity-3.2.0-SNAPSHOT-296

**Comment by Konicai** [comment]
Velocity 3.2.0 doesn't support 1.20.4

Try their experimental builds

**Comment by duman3344** [comment]
Thanks!
