### ISSUE TITLE
Treasure maps get turned into regular maps when used. 

### ISSUE THREAD

**Issue by usermaf** [GeyserMC/Geyser#4348]
### Describe the bug

Treasure maps get turned into regular maps when used.

### To Reproduce

Find a buried treasure map.
Open it.
Get a normal map.

### Expected behaviour

A buried treasure map to appear.

### Geyser Version

latest to post.

### Minecraft: Bedrock Edition Device/Version

Bedrock, Windows 10.

**Comment by Konicai** [comment]
Share a `/geyser dump` please. Does this occur on both 1.20.4x and 1.20.5x ?

**Comment by onebeastchris** [comment]
Closing due to no further response - I've also not been able to reproduce this issue.

**Comment by EtheraelEspeon** [comment]
This happened to me on the 1.21.10 fabric mod. Heres a dump
https://dump.geysermc.org/Vxzgk9gQBXt9ypBt5D5iEjRhTgJzPsGg

Edit: It happened again with the second map I found. It seems to be consistent

Edit 2: Third map also did it, they seem to be completely broken on this version.

**Comment by EtheraelEspeon** [comment]
Treasure maps are suddenly working, this is a new dump https://dump.geysermc.org/lL3rB5nDVG30ykypz3m0JAavttwK2C5K

**Comment by jrcarl624** [comment]
I had a member of my server report a similar issue.
