### ISSUE TITLE
Player is repeatively sent back and forth when in contact with semi colidable objects, such as trapdoors and dripstones.

### ISSUE THREAD

**Issue by usermaf** [GeyserMC/Geyser#4349]
### Describe the bug

Your player gets stuck in a back and forth motion if you walk into a trapdoor, dripstone, or anything else with a small collision box.

### To Reproduce

Walk into something with a small collision box.

### Expected behaviour

.

### Geyser Version

latest to post.

### Minecraft: Bedrock Edition Device/Version

Bedrock, Windows 10.

**Comment by Konicai** [comment]
Stop creating issue reports with barely any of the required information. Make it again
