### ISSUE TITLE
This will be very usefull

### ISSUE THREAD

**Issue by Hiho2950** [GeyserMC/Geyser#4353]
### What feature do you want to see added?

can you add the ability to see the item icon in the inventory bar cause if the item or the block have a 3d texture without icon texture the item in the inventory be black and purple if i use fabric or paper if i use itemsadder
and this will help very much for modded fabric servers

### Are there any alternatives?

:( i didnt find one

**Comment by onebeastchris** [comment]
When adding custom items with 3d models, you need to create and set a 2d icon yourself. Geyser cannot do that for you; that's something you need to do in a Bedrock resource pack. Feel free to join our [discord server](https://discord.gg/geysermc) and ask in the #custom-resource-packs channel for help on that.
