### ISSUE TITLE
unable to connect due to missing key.pm on 1.20.4

### ISSUE THREAD

**Issue by strikersix23** [GeyserMC/Geyser#4356]
### Describe the bug

unable to connect to server due to key .pm not being found

### To Reproduce

setup as recomended and just run

### Expected behaviour

generate or write key.pm and connect

### Server Version and Plugins

CraftBukkit version 3979-Spigot-06d602e-f03fc3a (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)
Geyser-Spigot v2.2.0-SNAPSHOT git as of 24 minutes ago from 10:04 am cst dec 20th 2023

 floodgate v2.2.2-SNAPSHOT (b91-492be77)

### Geyser Version

 floodgate v2.2.2-SNAPSHOT (b91-492be77)

### Minecraft: Bedrock Edition Device/Version

1.20.51 Xbox Series S 

### Additional Context

i can upload a log if needed

**Comment by strikersix23** [comment]
log 
[latest.log](https://github.com/GeyserMC/Geyser/files/13729601/latest.log)

**Comment by onebeastchris** [comment]
Floodgate is a plugin, not a Geyser extension. For further configuration issues, please join our discord server for support:

discord.gg/geysermc

**Comment by onebeastchris** [comment]
For instructions on how to set up and use Floodgate on a standalone Geyser setup, see our wiki:
https://wiki.geysermc.org/floodgate/setup/
