### ISSUE TITLE
Running false events on PlotSquared protected plots

### ISSUE THREAD

**Issue by masterhacka** [GeyserMC/Geyser#4358]
### Describe the bug

Hi there. I talked to PlotSquared devs before and it seems there is an event issue for Bedrock players. Clicking doors on others plots at the lower block is working like it should. But clicking the upper block of the door allows Geyser players to open and close any doors. Is there any way to fix this? Geyser is running on Bungeecord. Subservers are running Paper 1.20.2

### To Reproduce

Visit a foreign plot and click the top of the door.

### Expected behaviour

The door should not move cause players aren’t allowed to.

### Server Version and Plugins

git-Paper-318 (MC: 1.20.2)

PlotSquared 7.2.1

### Geyser Dump

https://dump.geysermc.org/044bjnBAcOHPtLsYiVTnWxUzldyw380f

### Geyser Version

Build 407

### Minecraft: Bedrock Edition Device/Version

1.20.51, any device

**Comment by rtm516** [comment]
This seems like a big issue on the PlotSquared side, we just send packets to the server, so anything a Geyser client can do a modded Java client can do.
So it should be taken as a vulnerability in PlotSquared and also as an issue on our side as we are sending data not expected from a vanilla client.

**Comment by dordsor21** [comment]
We listen to the events that Spigot or paper send, there's nothing more we can do in P2

**Comment by SirYwell** [comment]
It seems like PlotSquared receives the event and properly cancels it, and opening the door, leaving the server, and joining the server will result in a closed door, so I assume this comes down to the client not correctly seeing the state of the door.

**Comment by onebeastchris** [comment]
In that case, it's likely a duplicate of https://github.com/GeyserMC/Geyser/issues/2819

**Comment by masterhacka** [comment]
The fix mentioned in #2819 is not working. You are getting teleported but the door is still opening.

**Comment by onebeastchris** [comment]
Unfortunately, since that's not an official plugin, that wouldn't be on us to fix :/
Does the rest of the issue description from there match the issue here?

**Comment by masterhacka** [comment]
I don‘t want to use extra plugins to fix this issue. This should be solved either with Geyser update or PlotSquared update.

I don‘t think it is exactly the same issue. The description from there shows an issue on the whole door and trapdoors. In my case trapdoors are working as they should and the issue appears only when trying to open the doors from the upper part.

**Comment by SirYwell** [comment]
> I don‘t think it is exactly the same issue. The description from there shows an issue on the whole door and trapdoors. In my case trapdoors are working as they should and the issue appears only when trying to open the doors from the upper part.

I assume you just found a far more obvious case of that issue, and trapdoors aren't working as they should but it's harder to trigger that bug there.

**Comment by masterhacka** [comment]
The fix for the error described in the other post works exactly as described.

If my error were the same, the fix would work in my case as well.

**Comment by Kas-tle** [comment]
Are the doors actually opened server side? Or only for the bedrock client?

**Comment by masterhacka** [comment]
They are actually opened server side. So this is not an optical issue. Bedrock and Java players can see the open door and move through it.

**Comment by Kas-tle** [comment]
Then you or PS should probably report this to Paper.

**Comment by Kas-tle** [comment]
Also is there a server I can join to see this bug?

**Comment by masterhacka** [comment]
Sure,
Java: ultimatebuild.de
Bedrock: mc.ultimatebuild.de Port: 19132

**Comment by Kas-tle** [comment]
Yeah hmm seems pretty bad assuming there's no other weird interactions going on.
https://github.com/GeyserMC/Geyser/assets/26531652/ab451d52-d464-4a3d-877b-315eb42a2686

**Comment by Kas-tle** [comment]
So actually your characterization that it's server side is incorrect.
https://www.youtube.com/watch?v=Ep-NoiGS1ZI

**Comment by Owen1212055** [comment]
@Kas-tle 
Am pretty confident that this is due to Geyser not properly resending blocks.
See: https://github.com/PaperMC/Paper/commit/9271ee7643614663a6d93323a9e8db2d52123166

Paper no longer resends blocks, instead using java's block prediction system.

**Comment by Kas-tle** [comment]
We get an update packet to close the door though from what I can tell. The fact it is fine if the door is opened from the bottom makes me think it's related to how we handle updates for adjacent blocks.
![image](https://github.com/GeyserMC/Geyser/assets/26531652/44ca3af8-c260-4a73-a232-90e710703fcb)

**Comment by Camotoy** [comment]
Part of the issue could lie in Bedrock updating the block and we have no indication that the door state is different on its end.

**Comment by Kas-tle** [comment]
Well we are properly sending the packets to close the door. It just seems Bedrock doesn't like it when we update the top of the door versus the bottom.

**Comment by Kas-tle** [comment]
But yeah there certainly seems to be some weirdness going on with doors. For example, the Bedrock client does not seem to have states for closed half doors... so I think there's just some weirdness where the bedrock client is doing its own calculation on if the door should or should not be closed, and we generally don't notice it because in the absence of this it's normally correct. In this case it seems we could fix it by just always opening doors from the bottom. Also it seems the Bedrock client is totally broken for half doors. Doesn't really seem to understand those can open/close.

**Comment by Kas-tle** [comment]
Should be resolved once the latest build is pushed.

**Comment by masterhacka** [comment]
Thank you so much!
