### ISSUE TITLE
Cant connect on 1.20.50 with velocity and minecraft 1.20.2

### ISSUE THREAD

**Issue by sekaom** [GeyserMC/Geyser#4361]
### Describe the bug

Cant connect to server ,stay at "Locating server"(velocity3.2.0#296) or "An internal error occurred in your connection."(velocity3.3.0#309)  
[Velocity3.2.0#296](https://katb.in/igotuwigawo)  
[Velocity3.3.0#309](https://katb.in/ehavajovawa)

### To Reproduce

1.Update geyser from  2.2.0-SNAPSHOT (git-master-118e769) to 2.2.0-SNAPSHOT (git-master-b0ccf45)
2.restart velocity and try to connect to velocity  
3.disconnect from server or stay(Describe said)

### Expected behaviour

connected to server without any error

### Server Version and Plugins

Server: 1.20.2Paper#git-Paper-318 (MC: 1.20.2)  
Velocity: 3.3.0#309 and 3.2.0#296  
### plugins(Velocity)
AuthMeVelocity (4.0.4), Geyser-Velocity (2.2.0-SNAPSHOT (git-master-b0ccf45)), LuckPerms (5.4.108), MiniMOTD (2.0.14), ServerUtils (3.5.4), SkinsRestorer (15.0.3), Snap (1.1-SNAPSHOT (build 34)), TrChat (2.0.9) and Velocitab (1.5.2-3b1be41)
### plugins(Server)
AuthMe (5.6.0-SNAPSHOT-b2614), AuthMeVelocity (4.0.4), Citizens (2.0.33-SNAPSHOT (build 3275)), DeluxeMenus (1.14.0-DEV-168), JoinMessagePlus (3.3), LuckPerms (5.4.108), MusicBox (2.0.13), NoteBlockAPI (1.6.2), PlaceholderAPI (2.11.5), ProtocolLib (5.1.1-SNAPSHOT-673), ServerUtils (3.5.4), SkinsRestorer (15.0.4), SpawnPlugin (1.0.3), TAB (4.0.9), TrChat (2.0.9), ViaBackwards (4.9.1) and ViaVersion (4.9.3-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/TWolt3tGMS9O4nifuvkzRZrEHcGfzPFo

### Geyser Version

2.2.0-SNAPSHOT (git-master-b0ccf45)

### Minecraft: Bedrock Edition Device/Version

1.20.50 iOS

**Comment by Kas-tle** [comment]
1. Offline mode is not supported
2. This is likely a setup issue. See https://wiki.geysermc.org/geyser/fixing-unable-to-connect-to-world/
