### ISSUE TITLE
Can't join a Bungeecord proxy with Geyser

### ISSUE THREAD

**Issue by Adrigamer2950** [GeyserMC/Geyser#4362]
### Describe the bug

I have a Flamecord 1.9.1 proxy with Geyser b407 installed and this happens sometimes when a bedrock player tries to join. This error appeared out of nowhere and it specifies to create a bug report on the relevant GitHub repository

### To Reproduce

1. Install Geyser on the Proxy
2. Try to join the server

### Expected behaviour

The Bedrock player connects to the server successfully

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/58531641/f04e5937-b480-4e6f-aedb-70e5faa934c6)

### Server Version and Plugins

FlameCord 1.9.1

Plugins:

- ajQueuePlus 2.5.0
- BungeeGuard
- BuycraftX
- CleanStaffChat
- Floodgate b85
- Geyser b407
- LuckPerms 5.4.102
- Pl-Hide-Pro 2.7.4
- Protocolize
- ServerUtils 3.5.4
- SkinsRestorer 14.2.12
- Spark 1.10.41
- LiteAnnouncer 6.2
- BungeeReports (Custom Plugin)
- CmdBlockBungeeCord
- BungeeCMD
- NauticCoreBungee (Custom Plugin)
- ABPS

### Geyser Dump

https://dump.geysermc.org/5SMbZruJsttjwN6ckD4NErHTxXS0qGC6

### Geyser Version

2.2.0-SNAPSHOT (git-master-cdb8ab3)

### Minecraft: Bedrock Edition Device/Version

1.20.50

**Comment by onebeastchris** [comment]
Please read the error, it tells you to report it to ViaVersion. 

Closing as this isn't a Geyser issue
