### ISSUE TITLE
Error whilst serializing LevelSoundEvent2Packet

### ISSUE THREAD

**Issue by timr2000** [GeyserMC/Geyser#4366]
### Describe the bug

From what I can see, it spits out errors because of the Decorated pots.
Error: ~~https://mclo.gs/2tCjz3EI~~ https://pastebin.com/cnq8Yhhj

### To Reproduce

Can't seem to find what's causing this error to happen

### Expected behaviour

No error should appear

### Server Version and Plugins

git-Purpur-2110 (MC: 1.20.4)

### Geyser Version

Geyser version 2.2.0-SNAPSHOT (git-master-b0ccf45) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.50/1.20.51)

**Comment by onebeastchris** [comment]
Please run `geyser dump` in console, and send the link you get here. Additionally, can you check your minecraft bedrock client version?

**Comment by timr2000** [comment]
Oh forgot about the geyser dump, there you go: https://dump.geysermc.org/9mMdzVkscHufFhTKu1OBqF4jg67ltc9w
Minecraft bedrock client version: 1.20.51

**Comment by Konicai** [comment]
The log as already expired somehow

**Comment by timr2000** [comment]
> The log as already expired somehow

That's weird, here is the error: https://pastebin.com/cnq8Yhhj

**Comment by Konicai** [comment]
thanks

**Comment by onebeastchris** [comment]
Should be resolved now - thanks for reporting
