### ISSUE TITLE
Cannot reply to ClientboundHelloPacket without profile and access token

### ISSUE THREAD

**Issue by daniel-skopek** [GeyserMC/Geyser#4368]
### Describe the bug

Some players cannot join

### To Reproduce

https://pastebin.com/raw/Qgn7Y4bU

### Expected behaviour

All players should be able to join

### Geyser Version

Geyser version 2.2.0-SNAPSHOT (git-master-592a58a)

### Additional Context

Velocity 3.3.0-SNAPSHOT (git-a39274a7)

**Comment by Konicai** [comment]
Please join our discord for issues like this first (especially if you're not completely filling out the bug report)
