### ISSUE TITLE
"Tried to log in as a Java Edition player! Is Floodgate set up correctly?" keeps appearing when joining on bedrock

### ISSUE THREAD

**Issue by itsmePP8** [GeyserMC/Geyser#4371]
### Describe the bug

A few days ago, I started a minecraft cross-play server on Aternos for me (java), my friend (java) and my sister (bedrock edition). At first, everything was normal, but then a few days ago when my sister was trying to join the server, it wouldn't let her. The error message was: "Tried to log in as a Java Edition player! Is Floodgate set up correctly?". I tried googling what to do but couldn't find anyone who had this issue with joining a server that was similar to mine. At that time, I only had GeyserMC installed as a plugin. I used and still use the Spigot/Bukkit software. Both my plugins and software are updated to the latest version. I tried re-installing the old plugins and installing new ones, but she still couldn't join. After a few tries the error message changed to "Unable to connect to world". I tried installing ViaVersion and ViaBackwards but nothing happened. I even tried connecting to the server using another server, geyserconnect.net, but nothing. Then again, one random moment, the message changed back to the one from the beginning! I made a new server to see if the server was the problem, but she couldn't join the other one either. I tried to join from a different device (same account), but nothing. I'm not sure what to do as nothing seems to work for me, I'll attach any logs if needed.

P.S. The testing server I made had only GeyserMC installed. 

### To Reproduce

I'm not sure how to reproduce, as I don't know if it's my sister's account, or something else. I would appreciate it if someone with a bedrock account would try to join my server. If someone is able to, I'll send the IP and adress,

### Expected behaviour

A regular joining process. I never expected this error. 

### Screenshots / Videos

![IMG_2858](https://github.com/GeyserMC/Geyser/assets/155299439/951b274a-a8e3-4556-8330-e36784ace889)

### Server Version and Plugins

software: Spigot/Bukkit v1.20.4 (4003)
ViaVersion v4.9.2
ViaBackwards v4.9.1

### Geyser Version

 410 (Bedrock v1.20.40 - v1.20.51)

### Minecraft: Bedrock Edition Device/Version

v1.20.51, iPad pro

### Additional Context

This is the 1st time I've seen this error.

**Comment by onebeastchris** [comment]
Please re-install Geyser from the Aternos plugin panel. This will also automatically update Floodgate, which should resolve this issue

**Comment by itsmePP8** [comment]
I did this and it worked thank you so much!
