### ISSUE TITLE
shopkeeper can open in bedrock. but it cant trade , how to fix it

### ISSUE THREAD

**Issue by ComLauReview** [GeyserMC/Geyser#4372]
### Describe the bug

i setup shopkeeper in java, it cant active in bedrock, although i try test shopkeeper, it also not active 
how to fix it 
thanks

### To Reproduce

![image](https://github.com/GeyserMC/Geyser/assets/120564607/e8b68a94-8e7e-4cea-a1b2-441bac710aca)
i want to help fr u fpls

### Expected behaviour

it isnt active shopkeeper

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/120564607/a5ce6f6e-9166-4d70-9c0a-811fc45b880a)

### Server Version and Plugins

my server has viaversion , geyser and shopkeeper

### Geyser Dump

https://dump.geysermc.org/iSeIZVW5znINEQueN9NQRACqA5ro2LRr

### Geyser Version

Geyser version 2.2.0-SNAPSHOT (git-master-6e56666) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.50/1.20.51)

### Minecraft: Bedrock Edition Device/Version

BEDROCK (1.20.50/1.20.51)

### Additional Context

PLS HELP ME

**Comment by onebeastchris** [comment]
Can you send a screenshot of what it looks like on Java vs. what is showing on Bedrock edition?

**Comment by ComLauReview** [comment]
> Can you send a screenshot of what it looks like on Java vs. what is showing on Bedrock edition?

![Uploading image.png…]()
caNT TRADE =(
