### ISSUE TITLE
Issue with geyser and teams 

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#4375]
### Describe the bug

i have bedwars on my server and im having  a teams issue with bedrock players where they cant open their shop for their team 
everytime they click it, in consol i get this 03.01 20:36:24 [Server] INFO [Geyser-Spigot] Ignoring team [NPC] 24767e56e8. It overrides without removing old team.   indicates it overrides but doesn't really ?

now iv tested it on java works as expected, tested on bedrock pc works as expected, bedrock on consol seems to be the issue

### To Reproduce

i use screaming bed wars
play with bedrock, start a match and then try opening the shop to get blocks or get upgrades for the match.

### Expected behaviour

for geyser players to be able to open the shop in bedwars

### Server Version and Plugins

1.20.1 purpur

plugins:
screaming bedwars
TAB
Via version
CMI
CMI LIB

### Geyser Dump

https://dump.geysermc.org/KhpngREP0xosWLoemr66XUg9g3aAfYEo

### Geyser Version

Build 410

### Minecraft: Bedrock Edition Device/Version

bug occur on consol

**Comment by shawn695** [comment]
issue solved by switching to citizens instead of using NPC from BedWars

**Comment by onebeastchris** [comment]
Geyser imitates the warnings that a Java client would send (specifically, the duplicate teams). You can verify this by checking the client logs of a 1.20.4 client - ultimately, you should report this issue to the plugin that causes them.
