### ISSUE TITLE
Can't use Raytracing in Geyser sever

### ISSUE THREAD

**Issue by MoTao233** [GeyserMC/Geyser#4376]
### Describe the bug

if i enable raytracing in geyser sever, certain lighting effects will flicker, and some blocks become invisible.
but if you disable raytracing, everything will be ok.

Below, I'll attach screenshots and further details. 

This seems to be an issue related to ray tracing, but when I attempted it in single-player mode, everything was fine. 
The situation only occurs on the Geyser server. This server is hosted locally.(Because i want to use raytracing in Java survival) 
Since I'm unaware of other Geyser servers, I'm not sure if the same issue exists elsewhere. 

I also attempted to use Better RTX, update the graphics card driver, change the RTX resourcepack,but it didn't work.

A few months ago, I also set up a Fabric core Geyser server locally, added several mods, and enabled ray tracing. Everything worked fine.

### To Reproduce

1.enable raytracing
2.join a geyser sever
3.wait for a while

### Expected behaviour

solve it

### Screenshots / Videos

![TRANSFERMinecraft Screenshot 2024 01 04 - 15 15 16 95](https://github.com/GeyserMC/Geyser/assets/136603340/28e649db-e290-43e1-b417-a30c6a09af6a)
![TRANSFERMinecraft Screenshot 2024 01 04 - 15 15 46 03](https://github.com/GeyserMC/Geyser/assets/136603340/6b963f51-452c-40b1-93f7-dac60809586a)
![TRANSFERMinecraft Screenshot 2024 01 04 - 15 19 17 55](https://github.com/GeyserMC/Geyser/assets/136603340/274cbdd3-20f5-4493-bf8d-5669870e5a6b)

### Server Version and Plugins

fabric-server-mc.1.20.4-loader.0.15.3-launcher.1.0.0

the server has only 3 mods:
-fabric-api-0.92.0+1.20.4, 
-Geyser-Fabric,
-floodgate-fabric-2.2.0-SNAPSHOT+build.17

you may see many mods in Geyser Dump. Yes, I added many mods, but when I encountered this issue, I tried to uninstall mods to debug it. However, even when only these three essential mods remained, the problem persisted. Hence, I don't think this issue is caused by mods.

### Geyser Dump

https://dump.geysermc.org/13hNgftZwfYzvJddhasBbXAyqkhjTUoM

### Geyser Version

2.2.0-SNAPSHOT (git-master-46bde0c)

**Comment by rtm516** [comment]
I'm unable to replicate the issue on my end.
Can you provide a copy of the pack you used and the world the issues were in?

**Comment by MoTao233** [comment]
> I'm unable to replicate the issue on my end. Can you provide a copy of the pack you used and the world the issues were in?

After seeing your reply, I reconstructed the server to try replicating this BUG. 
This time, it seems I found the reason; it appears to be caused by the map. Is ok if you use vanailla map.
  
I subsequently entered the server using the Java edition, and everything seemed normal. 
However, I noticed that this map appears to contain some custom resource packs (certain leaves are red, while the grass is yellow). Could this be the cause? 
The address of the map is: [Grand Roost](https://www.planetminecraft.com/project/grand-roost-8000-x-8000-survival-landscape-map-1-20-structures-free-download/)
Could you assist me in checking this?

**Comment by onebeastchris** [comment]
Given that this is a client side issue, there's likely nothing we can do on our end.
