### ISSUE TITLE
Add support for Java server EntityPlayer#latency field

### ISSUE THREAD

**Issue by AuroraLS3** [GeyserMC/Geyser#4379]
### What feature do you want to see added?

I got a feature request to improve data gathering for player latency (https://github.com/plan-player-analytics/Plan/issues/3395) - currently on Java+Geyser server the player latency field is not updated on Java server side and is 0ms at all times.

Possibly related: #4131

### Are there any alternatives?

Alternative could be to implement a FloodgatePlayer#getPing method which I can call, though I'm not 100% sure of the setup the user requesting the data has (Is Floodgate even required on the Java server?). They might have Geyser in front of a game server in which case some packet is missing from the Geyser proxy-Java server communication.

**Comment by AuroraLS3** [comment]
Alright I have given the `forward-player-ping` as an option for the request - I think it is more what they are after since my plugin doesn't support Geyser API directly, only through Floodgate, so the ping needs to be available on the java server for my plugin to detect it

**Comment by onebeastchris** [comment]
Implemented a ping api in https://github.com/GeyserMC/Geyser/pull/4862. Thanks for the suggestion!
