### ISSUE TITLE
Geyser cannot be shut down gracefully

### ISSUE THREAD

**Issue by hseermc** [GeyserMC/Geyser#4382]
### Describe the bug

when I shut down my server 
[12:49:22] [Server thread/INFO]: [Geyser-Spigot] Disabling Geyser-Spigot v2.2.0-SNAPSHOT
[12:49:22] [Server thread/INFO]: [Geyser-Spigot] Geyser关闭中
[12:49:22] [Server thread/INFO]: [Geyser-Spigot] 正在踢出 1 玩家
[12:49:22] [defaultEventLoopGroup-6-4/INFO]: [Geyser-Spigot] RotaryApe119114 因为 Geyser代理正在关闭 与 Java 版服务器 断开了连接
[12:49:22] [Server thread/INFO]: [Geyser-Spigot] 踢出所有玩家!

The server then did not respond.But when the server does not have Bedrock Edition players, it is possible to shut down the server normally. I think it is supposed to be caused by geyser not successfully closing.

### To Reproduce

1. Have a Bedrock Edition player online 2. Close the server

### Expected behaviour

Geyser was successfully closed

### Geyser Version

 2.2.0-SNAPSHOT (git-master-7613bdb)

### Minecraft: Bedrock Edition Device/Version

1.20.4 Android phone

**Comment by onebeastchris** [comment]
Please send the full `latest.log` file from the `logs` folder using mclo.gs. Additionally, send a geyser dump by running `geyser dump` and sending the link you get here

**Comment by minecraft-fff** [comment]
latestlog:   https://mclo.gs/AMOfgBw
geyser dump:  https://dump.geysermc.org/5P9uZ7GrjMYGo6GGrYlHpNaFKqqmSCwF

**Comment by minecraft-fff** [comment]
I waited for more than half an hour on my server and it never proceeded to the next step (closing viaversion and saving the server archive)

**Comment by onebeastchris** [comment]
Does it also occur with just Geyser and Floodgate installed?

**Comment by minecraft-fff** [comment]
I remove some plugins(floodgate-skript crossplatforms geyserhacks geyserskinmanager-spigot residenceform tpa) and my server can shutdown successfully.

**Comment by onebeastchris** [comment]
If that's the case, the issue likely isn't Geyser directly. I'd recommend to try and narrow it down to what plugin causes it, and ask the authors of it for help

**Comment by hseermc** [comment]
Today I had the same issue again on my server, but this time I only ran geyser and floodgate, not the geyser community plugin. Until then (when this issue was first opened) the server had been normal

geyser dump: https://dump.geysermc.org/sUBr8xKyxNdHjO2LSooKyJbW0W7Urm3H
latest log: https://mclo.gs/mBfYkXT

There are no errors in the logs.i don't know why.

**Comment by onebeastchris** [comment]
You're running more than just the Geyser/Floodgate plugins - there's a dozen more. Please try replicating the issue with *just* Geyser and Floodgate, to ensure that the issue doesn't come from a different plugin.

**Comment by hseermc** [comment]
Even though I just run geyser and floodgate and it's necessary viaversion, it still has this issue
latest.log https://mclo.gs/qnXhJMW
geyser dump https://dump.geysermc.org/AsA86Hmwu3Ma7hGMWG98sKgQLszJg1CC

**Comment by hseermc** [comment]
Do I need to provide a configuration file?

**Comment by onebeastchris** [comment]
@hseermc Please try and see if the issue persists without Viaversion - while you wont be able to connect, you should be able to check if the server shuts down properly. We've seen some reports before that it was the thing introducing the shutdown issue - not sure if that also occurs with just Via* installed, or whether that occurs when via *and* Geyser are installed

**Comment by hseermc** [comment]
This issue occurred when a Bedrock Edition player was online.If I remove Via plugin,the bedrock player may not be able to connect the server,so this issue will not happen.When there isn't bedrock edition player online, the server can shutdown.

**Comment by onebeastchris** [comment]
Does the server shut down fine with just ViaVersion (without geyser/floodgate)?
If it does, this indeed sounds like an issue on our side

**Comment by hseermc** [comment]
是的

**Comment by hseermc** [comment]
I've asked other people and they say it's been Geyser's question for a long time.They advise me to use Geyserstandalone.

**Comment by onebeastchris** [comment]
I'm unable to replicate this issue with the latest version of Geyser and ViaVersion - is it still occurring?

**Comment by hseermc** [comment]
It doesn't occure. Thanks!
