### ISSUE TITLE
Bedrock kicked depending on the symbol that appears in the chat

### ISSUE THREAD

**Issue by GalleyRP** [GeyserMC/Geyser#4402]
### Describe the bug

Literally the title, bedrock players are being kicked out when some specific symbols appear in their chat, giving a decoding failure error.

### To Reproduce

1 Log the server
2 Use any command of "LuckPerms" or "spark"

### Expected behaviour

I think the problem is in the bungeecord, but I went back to several versions and the problem persisted, but when I went back to an old version of geyser, even in the 1.20.51 update, the problem stopped

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/154942862/4d2484ad-e7b9-4db7-91a1-56b4069c2908)
![image](https://github.com/GeyserMC/Geyser/assets/154942862/1526800d-75ea-4962-8776-2937160ef57e)

### Server Version and Plugins

git:BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:3deaaad:1781
Bungeecord: Ajqueue, Bungeeguard, luckperms, MyCommand, Floodgate
Back-End: Spark, superlobby, citizens e etc.

### Geyser Dump

https://dump.geysermc.org/38JDbV3QSov9kQi3UpGMxxnFFobRTjWY

### Geyser Version

Geyser version 2.2.0-SNAPSHOT (git-master-16f9f0d) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.50/1.20.51)

### Minecraft: Bedrock Edition Device/Version

1.20.51 All Devices

### Additional Context

Commands like /tps (spark) or /lp info (luckperms) cause this crash.

**Comment by onebeastchris** [comment]
Update ViaVersion to 4.9.3, this should resolve the issue
