### ISSUE TITLE
Xbox quick crafting items positions them at the rightmost hotbar slot

### ISSUE THREAD

**Issue by Estrobeda** [GeyserMC/Geyser#4405]
### Describe the bug

When connecting to geyser through Xbox (only tested on PC, Android and Xbox), there's a bug when crafting from the left items list.
Hovering over one of these items and pressing (craft) "should" make the item appear in the leftmost hotbar slot assuming there's enough place for it to be placed there, this is the behavior on Android and PC.
However, on Xbox the items glitches and gets placed on the rightmost slot instead.

This bug only happens in the rightmost crafting slot (see attachment for what I mean, screenshot on PC but described as if on Xbox)

![image](https://github.com/GeyserMC/Geyser/assets/4711353/b1589b8b-05bc-4f0e-b6bc-c18ed0fce41d)

### To Reproduce

For example:
1: Connect to a Geyser enabled server on Xbox
2: Shop down a log
3: Open the inventory and try to craft planks from the left side items list
4: Make note of where the planks are placed (will be at the rightmost hotbar)

Generic ways to reproduce this is to try to craft any new stack of items from any recipe shown in the leftmost items list.

Crafting through the 4 slot window itself will however work as intended thus, only quick crafting from the left items list menu causes this issue. 

### Expected behaviour

The items crafted no matter if it's from the left items side menu or elsewhere, the new items stack should end up
1: in the left and uppermost stack if a stack of the crafted item already exists.
2: in the left most hotbar slot if a hotbar slot is available and no itemstack already exists
3: in the left and upper most slot in the inventory if there's no place in the hotbar and no itemstack already exists

### Screenshots / Videos

Se the attachment in the description.

### Server Version and Plugins

PaperMc 1.20.4 (Although I've tried this on known Spigot servers too so I'm fairly sure its "server independent")
GeyserMC Version 2.2.0-SNAPSHOT (git-master-509e00c)

### Geyser Version

2.2.0-SNAPSHOT (git-master-509e00c)

### Minecraft: Bedrock Edition Device/Version

1.20.4 Xbox

**Comment by Kas-tle** [comment]
This is the client's choice so this is likely working as intended.
