### ISSUE TITLE
Add mojang account support again

### ISSUE THREAD

**Issue by HatsukiYukina** [GeyserMC/Geyser#4411]
### What feature do you want to see added?

In this [change](https://github.com/GeyserMC/Geyser/commit/7983448ce637656db1fca95eb65344a8c6d90de3)，Geyser removed mojang login support. This feature can be retained for a long time,[Yggdrasil Api ](https://github.com/bs-community/blessing-skin-server)require mojang auth（use [authlib-injector](https://github.com/yushijinhun/authlib-injector)），These two are the same APIs. If removed mojang auth, Yggdrasil Api will be unavailable. Due to this requirement, please do not remove the mojang login. My English is not very good, I am a student. There may be some grammar errors or incorrect meanings. Thank you very much for reading my issue
在这个[更改](https://github.com/GeyserMC/Geyser/commit/7983448ce637656db1fca95eb65344a8c6d90de3)，geyser移除了对mojang登录的支持，我认为这个功能可以长期保留，因为[yggdrasil api](https://github.com/bs-community/blessing-skin-server)（使用[authlib-injector](https://github.com/yushijinhun/authlib-injector)）需要使用mojang登录，这两者是类似的api。如果移除了mojang登录，yggdrasil将会再也无法使用，因为这个需求，我认为需要保留mojang登录。感谢您阅读我的issue

### Are there any alternatives?

There is no way to make any alternative，The yggdrasilAPI must be implemented using mojang login on geyser
我没有找到任何替代方法，在geyser上，yggdrasilapi必须使用mojang登录实现

**Comment by Camotoy** [comment]
We will not re-add Mojang account support, because Mojang themselves dropped it. In the future it *might* be possible that extensions happen to allow this. That would be the only option for Mojang login support.

Thank you anyway for the request.
