### ISSUE TITLE
geyser list command don't work with multiple proxies

### ISSUE THREAD

**Issue by lucasfrederico** [GeyserMC/Geyser#4414]
### Describe the bug

My server is available at play.loverfella.com:19132 and when the player connects, it is distributed between 4 Velocity proxies that we have available. The problem is that the geyser list command only lists players from the proxy where I am typing the command.

### To Reproduce

1. Set up an environment with multiple proxies
2. Run /geyser list.

### Expected behaviour

Expected to list all players from all proxies.

### Geyser Dump

https://dump.geysermc.org/OJFIh6BRBO11XPW6iZOb8jSyHYEZUdaX

### Geyser Version

2.2.0-SNAPSHOT

**Comment by onebeastchris** [comment]
Unfortunately, this isn't something we can fix - running multiple Geyser proxies isn't recommended nor officially supported, and even if they would be, Geyser proxies wouldn't be able to communicate with one another.

If you're working with player counts that do require multiple Geyser proxies, and need to track geyser player counts across them, some custom plugin that queries the Geyser api & uses redis would work.

**Comment by Camotoy** [comment]
We don't have any official setups with multiple Geyser proxies, but doing so to balance load is fine. Still, in this case we would recommend creating an extension to satisfy your request.
