### ISSUE TITLE
1.20.60 Version Support

### ISSUE THREAD

**Issue by okunamayanad** [GeyserMC/Geyser#4416]
### Describe the bug

Playstation bedrock players can't connect, because geyser doesn't support 1.20.60 yet.

The update just got published, Playstation players can't play online without updating and there is no way of reverting so this is urgent

### To Reproduce

1. Download Minecraft on Playstation (I'm using a PS4)
2. Set up a [phantom](https://github.com/jhead/phantom) server to allow connecting custom servers (Playstation doesn't support that natively)
3. Connect to the server

### Expected behaviour

Player logs in

### Server Version and Plugins

Geyser 2.2.2-SNAPSHOT (git-master-226a4bb)
Velocity 3.3.0-SNAPSHOT (git-00ef92bc-b312)

### Geyser Dump

https://dump.geysermc.org/ctivrQAmLyp4o2Jl49DitjCpqGBsJldW

### Geyser Version

Geyser 2.2.2-SNAPSHOT (git-master-226a4bb)

### Minecraft: Bedrock Edition Device/Version

1.20.60, Playstation 4

**Comment by Konicai** [comment]
Support will be released some time today. I understand the urgency, but "bug" reports aren't necessary for version updates

**Comment by okunamayanad** [comment]
Sorry, I thought opening an issue over here would allow people to discuss over this becaue this update only came out to PS4 (as far as I know) and I thought it can be missed

**Comment by Kas-tle** [comment]
Initial Bedrock updates are released on the same day for all platforms, not just PS4. While the PS4 update happened to come out an hour or so before other platforms this time, all platforms still released 1.20.60 sometime yesterday.
