### ISSUE TITLE
Server Closed (Just happens on Build #427) Velocity

### ISSUE THREAD

**Issue by LUIS9799** [GeyserMC/Geyser#4422]
### Describe the bug

When updating the plugin, new builds reject the request from client answering with a "Connection Closed" and not connecting the Bedrock Proxy to Java Proxy

### To Reproduce

1. Delete the last .Jar
2. Upload the new Geyser-Velocity.jar (BUILD #427)
3. Start the server
4. Try to connect from Bedrock client

### Expected behaviour

Accept the connection: "Connect to forced-host" in this case:
Client joins ---> Connect Auth ---> Connect Lobby ----> Connect Games
Instead:
Client joins ---> Drop Connection ---> Wait for Timed Out (120s)

### Server Version and Plugins

Latest Velocity Build: Velocity 3.2.0-SNAPSHOT (git-b30802c1-b277)
Unsigned Velocity
Floodgate
MultiLobby
VLobby
V4Guard (Nothing to do with V4Guard as it is deactivated, so V4Guard.jar.dis) **DEACTIVATED**
nAntibot
nLogin
MCKotlinVelocity
SkinsRestorer
Mantainance
Litebans
...
(Custom plugins that are not related, just for simple commands as /help)

### Geyser Dump

https://dump.geysermc.org/ieOBoXJorXdAF2DNgLYMMT58AQfCdGO3

### Geyser Version

Geyser version 2.2.2-SNAPSHOT (git-master-226a4bb) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.50/1.20.51)

### Minecraft: Bedrock Edition Device/Version

Bedrock 1.20.60 (Windows - IOS- Android)

**Comment by onebeastchris** [comment]
Please send a full log a (via mclo.gs) and a geyser dump (`geyser dump` in the console`) here. Additionally, judging by the Geyser version that you entered, that doesn't seem to be the latest version

**Comment by LUIS9799** [comment]
Sure! https://dump.geysermc.org/ieOBoXJorXdAF2DNgLYMMT58AQfCdGO3

**Comment by LUIS9799** [comment]
Issue solved by updating Bungeecord version and Floodgate

**Comment by LUIS9799** [comment]
Issue solved by updating Bungeecord version and Floodgate
