### ISSUE TITLE
Player nametags are gone

### ISSUE THREAD

**Issue by spookymgmt** [GeyserMC/Geyser#4424]
### Describe the bug

On console I can only see player nametags from within a 2 block distance.

### To Reproduce

Update to latest, look at players, you cant see their nametags.

### Expected behaviour

See nametags from like 64 block away.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/78775526/44c7dff1-fe27-463e-bfe7-3c796b8f8146)

### Server Version and Plugins

Spigot server is on 1.20.1, geyser is well lets see below

### Geyser Dump

https://dump.geysermc.org/CbaLJBPAWKns1PjympMJqK9c932X52Ye

### Geyser Version

Run 426 https://github.com/GeyserMC/Geyser/actions/runs/7816162067

### Minecraft: Bedrock Edition Device/Version

latest bedrock console

**Comment by CayanNet** [comment]
same issue

**Comment by JorisvD01** [comment]
We're experiencing the same issue. After updating to the latest build yesterday people are reporting this issue

**Comment by Pikaswelt** [comment]
Same. Pls fix

**Comment by onebeastchris** [comment]
This is fixed in the latest version of Geyser.
