### ISSUE TITLE
Unable to access books on lectern

### ISSUE THREAD

**Issue by LOURENT4462** [GeyserMC/Geyser#4426]
### Describe the bug

Minecraft Java players can access the book on Lectern but Minecraft Bedrock players can't, I've tried it outside WorldGuard and it still doesn't work, and I've also tested it on my test server.

### To Reproduce

1. Put the book on the lecturer
2. Open the book
3. players can't open it (only bedrock players)

### Expected behaviour

players can open the book on the lectern

### Screenshots / Videos

-

### Server Version and Plugins

Server Version: This server is running Paper version git-Paper-307 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: b37bbcf)

### Geyser Dump

-

### Geyser Version

Geyser Standalone Version: This server is running Geyser version 2.2.2-SNAPSHOT (git-master-19a3dc3) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.60/1.20.61)

### Minecraft: Bedrock Edition Device/Version

1.20.61

### Additional Context

-

**Comment by onebeastchris** [comment]
Should be resolved in the latest build. Thanks for reporting!
