### ISSUE TITLE
legacy console edition support

### ISSUE THREAD

**Issue by ListLostLisp** [GeyserMC/Geyser#4429]
### What feature do you want to see added?

It's always been a wish of mine for some type of proxy for the Xbox 360 or PlayStation 3/vita versions so you can join a Java server with other consoles.

from what I can tell, apparently the packets are somewhat similar to the Java ones, moreso than bedrock is, meaning it should be easier to implement.

there is a decompilation in progress for the Nintendo switch legacy version which will be great help when it's more complete: https://github.com/GRAnimated/MinecraftLCE/blob/main/src/Minecraft.Network/PacketType.h

my idea to be able to join the server is to have a dedicated PS3 that will always say it's playing MC waiting for people to join. when you join it routes the data to the Java server to handle. 
everyone has to be friends with this one account to join, no console mods for the user should be necessary. A dedicated PS3/vita shouldn't be necessary if there is a way to trick PSN into thinking a PC is a PS3, though I am doubtful, haven't looked into it. There is a psn emulator though iirc so it could be possible using that.

It's far fetched that anyone will want to implement this but I thought I'd try to put it out there.

### Are there any alternatives?

no

**Comment by Camotoy** [comment]
While such a project would be very cool, such an implementation would not be within Geyser's roadmap. (Mainly, if anything, because the legacy console versions are not being updated but Bedrock is)
