### ISSUE TITLE
Entity send old flags

### ISSUE THREAD

**Issue by OurLobanov** [GeyserMC/Geyser#4430]
### Describe the bug

If an entity floats and then unloads it for another player and the entity stops floating and returns to it visually, it will float

### To Reproduce

1. player on GLIDING
2. /tp ~900 ~10 ~233
3. player  off GLIDING
4. /tp player

### Expected behaviour

Entiti doesn't swim

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/114523572/19f4ec99-f6e2-4631-85ec-d7d193c6a1c8)

### Geyser Version

https://github.com/GeyserMC/Geyser/actions/runs/7816162067

**Comment by TBYT** [comment]
Not sure about the title as well as there is nothing about the geyser version, I can confirm that this is replicatable on my end.
This server is running Paper version git-Paper-389 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 848a396)
"This server is running Geyser version 2.2.2-SNAPSHOT (git-master-63fd97a) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.60/1.20.61)"
![GeyserFalseAnimationGlitch](https://github.com/GeyserMC/Geyser/assets/48810871/2d5f5f21-f402-494b-8cd0-8be77761dfd8)

**Comment by onebeastchris** [comment]
What exactly would need to be done to reproduce this issue? Please provide full replication steps & if needed, the plugin needed to reproduce it.

**Comment by OurLobanov** [comment]
1 player https://youtu.be/CsT-8GJ-KwI

2 player https://www.youtube.com/watch?v=A3tz8hooBrQ

**Comment by onebeastchris** [comment]
Hey, could you test the latest Geyser build and see if that resolves the issue?

**Comment by OurLobanov** [comment]
![image](https://github.com/GeyserMC/Geyser/assets/114523572/982505a9-8d85-42fc-94da-3d97a0dbb092)
![image](https://github.com/GeyserMC/Geyser/assets/114523572/a1d79bde-9ce3-46a6-9db7-41946d769800)
I sat on shift with 2 accounts, teleported 1000 blocks from one account, then got up from shift and teleported from the second account. Also, Minecraft crashed when I tried to enter a command; as soon as I typed ‘/’, the game crashed. I removed all plugins, and it became normal. This hasn’t happened before

**Comment by OurLobanov** [comment]
> Hey, could you test the latest Geyser build and see if that resolves the issue?

 https://dump.geysermc.org/94Oj4yFH0F00CPkYZ1gb7HrH0QAQNaHx

**Comment by onebeastchris** [comment]
To resolve command crashing, you can disable the command suggestions in the geyser config

**Comment by tbyt** [comment]
I just replicated it again the same way, the issue is still present. Also, I tped the bedrock player away, then killed him so he can respawn where my java player is and the issue is still there. On the latest geyser version.

**Comment by OurLobanov** [comment]
The problem remains with the items in your hands will send the old item

**Comment by onebeastchris** [comment]
Hey! Could you try the linked PR and see if that resolves these issues?
