### ISSUE TITLE
entity nametags are gone 

### ISSUE THREAD

**Issue by OurLobanov** [GeyserMC/Geyser#4435]
### Describe the bug

Nameteg disappears or does not appear at all

### To Reproduce

Go to Chunk where the entity is with the nametag and then leave it so that it unloads for you and then go back in

### Expected behaviour

no bug 1.20.50 [https://youtu.be/zXKlZ1WjyFE](url)
1.20.60 bug https://youtu.be/iiPJ67-ynQo

### Geyser Dump

https://dump.geysermc.org/mrBfghyVGdcObULonqGmPDQvODjwvLOj

### Geyser Version

2.2.2-SNAPSHOT 

### Minecraft: Bedrock Edition Device/Version

Purpur-2035 1.20.1

**Comment by onebeastchris** [comment]
player nametags are fixed in the latest version of geyser; seems like your fork hasn't pulled the latest commit

**Comment by OurLobanov** [comment]
![image](https://github.com/GeyserMC/Geyser/assets/114523572/fc542e0e-92f0-4264-be5b-30bd084f471b) There were the most recent comets

**Comment by onebeastchris** [comment]
Please try using the latest version of Geyser and see if the issue persists. Additionally, please try replicating your issue with the master build found on the official download site - we cannot provide support for closed-source forks.

**Comment by Kas-tle** [comment]
We cannot provide support for custom forks. If this is an issue on the main branch of Geyser, please open a new bug with reproduction steps.
