### ISSUE TITLE
it does not work GeyserApi.api().isBedrockPlayer 

### ISSUE THREAD

**Issue by andfont** [GeyserMC/Geyser#4438]
### Describe the bug

I have the geyser-Waterfall / BungeeCord and the bedrock and java players connect, then I try from the server to get them to know if it is bedrock or java and there is no way! It always gives me null, I install the geryser-paper plugin on the destination server but nothing, and from programming I try to use the api to access this information, but nothing!
I try to use the PluginMessageListener like in bungeecord to ask geyser, but there is no way.

Please, why doesn't it work when the player enters their final destination? Why can't I ask Geyser?
greetings

### To Reproduce

-install geyser-Waterfall/BungeeCord on the proxy
-install the geyser-paper plugin on the destination server
-ask whether or not it is bedrock, example GeyserApi.api().isBedrockPlayer

### Expected behaviour

I have the geyser-Waterfall / BungeeCord and the bedrock and java players connect, then I try from the server to get them to know if it is bedrock or java and there is no way! It always gives me null, I install the geryser-paper plugin on the destination server but nothing, and from programming I try to use the api to access this information, but nothing!
I try to use the PluginMessageListener like in bungeecord to ask geyser, but there is no way.

### Geyser Dump

https://dump.geysermc.org/fchn8W3iUX3iiGWO6Ev9wzZS7zmWKcZU

### Geyser Version

429-geyser-Waterfall

**Comment by onebeastchris** [comment]
Installing Geyser on the backend server will not work.
Instead, you should install Floodgate on all servers, and set up floodgate forwarding across them - that will give you access to the Floodgate API on all servers (which also allows you to check whether they're Bedrock players).

Floodgate setup docs:
https://wiki.geysermc.org/floodgate/setup/
Floodgate API docs:
https://wiki.geysermc.org/floodgate/api/
