### ISSUE TITLE
Text display position / offset is different than on java

### ISSUE THREAD

**Issue by alexdev03** [GeyserMC/Geyser#4439]
![bedrock](https://github.com/GeyserMC/Floodgate/assets/56083016/0c8f90de-6fad-4409-97b9-75dfafea6bbd) Bedrock
![java](https://github.com/GeyserMC/Floodgate/assets/56083016/3ff03350-6102-4c46-887c-6dcc975df05b) Java

**Comment by onebeastchris** [comment]
Moved to the Geyser repository, since this is a Geyser issue

**Comment by alexdev03** [comment]
Oh sorry, I pressed the wrong link on discord

**Comment by onebeastchris** [comment]
ill close this issue then since you've made a new one

**Comment by onebeastchris** [comment]
Hey, mind testing <https://github.com/GeyserMC/Geyser/pull/4883> (You can find a build under the `Checks` tab there) and see if that resolves this issue?
