### ISSUE TITLE
Achieve accurate translation y offest with text display as passengers

### ISSUE THREAD

**Issue by alexdev03** [GeyserMC/Geyser#4440]
### Describe the bug

Currently, if you add a text display as a passenger to a player, with the right offset you can achieve something like this: 
![image](https://github.com/GeyserMC/Geyser/assets/56083016/a516855a-fadb-4dfc-ad4b-ef5e76432a67)
But on bedrock since text displays don't exist, there is a workaround with armor stands as passengers to create multi lines.
The translation offest is not handled and with that the lines are inside the skin of the player.

### To Reproduce

I made a custom plugin to replace current nametag system: https://github.com/alexdev03/UnlimitedNametags/tree/packet-based

### Expected behaviour

On bedrock there should be n more lines based on the text display offest in entity metadata packet ([Display#11](https://wiki.vg/Entity_metadata#Display)). Maybe you could find a formula to calculate the number of lines from a float y value.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/56083016/d7436e3d-b394-46ae-b602-cecba25ea3f0)
![image](https://github.com/GeyserMC/Geyser/assets/56083016/a516855a-fadb-4dfc-ad4b-ef5e76432a67)

### Server Version and Plugins

I'm using geyser velocity and a paper fork 1.20.4 backend.

### Geyser Dump

https://dump.geysermc.org/G6hEiqmDkQhRcaRSwPTSzuU0VEPMm20u

### Geyser Version

 Geyser version 2.2.2-SNAPSHOT (git-master-19c6648) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.60/1.20.61)

### Minecraft: Bedrock Edition Device/Version

1.20.60

**Comment by onebeastchris** [comment]
could you test if https://github.com/GeyserMC/Geyser/pull/4676 resolves this issue?
You can get a build of that PR in the "checks" tab.

**Comment by alexdev03** [comment]
Hi, it is clearly better, but could you move it a bit more up?
![image](https://github.com/GeyserMC/Geyser/assets/56083016/efc93dbf-454e-4988-b995-96c1b8dfa5fc)

**Comment by alexdev03** [comment]
![image](https://github.com/GeyserMC/Geyser/assets/56083016/28d698dd-87a0-440d-984d-f87e1b9556da)
Here you can see both java and bedrock

**Comment by stromsoftware** [comment]
> ![image](https://private-user-images.githubusercontent.com/56083016/332447042-28d698dd-87a0-440d-984d-f87e1b9556da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5Nzk3NjksIm5iZiI6MTcxNjk3OTQ2OSwicGF0aCI6Ii81NjA4MzAxNi8zMzI0NDcwNDItMjhkNjk4ZGQtODdhMC00NDBkLTk4NGQtZjg3ZTFiOTU1NmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDEwNDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNWExMTQzMmJlNzA0YjBjYTdkMTdlNjdlMmI2MWFmYjAxZjZjNzNjNWZhMGUxYWQ0MzE3MjBiYTQwYjFhMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IJgSGd-aT2zh-44A8WWs9kVruvsuOfhUfFbtonPPctY) Here you can see both java and bedrock

I balanced the offset difference in [4503e45](https://github.com/GeyserMC/Geyser/pull/4676/commits/4503e45b157b002d4991f7b96b28a58fad2f54d1)

**Comment by alexdev03** [comment]
> > ![image](https://private-user-images.githubusercontent.com/56083016/332447042-28d698dd-87a0-440d-984d-f87e1b9556da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5Nzk3NjksIm5iZiI6MTcxNjk3OTQ2OSwicGF0aCI6Ii81NjA4MzAxNi8zMzI0NDcwNDItMjhkNjk4ZGQtODdhMC00NDBkLTk4NGQtZjg3ZTFiOTU1NmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDEwNDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNWExMTQzMmJlNzA0YjBjYTdkMTdlNjdlMmI2MWFmYjAxZjZjNzNjNWZhMGUxYWQ0MzE3MjBiYTQwYjFhMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IJgSGd-aT2zh-44A8WWs9kVruvsuOfhUfFbtonPPctY) Here you can see both java and bedrock
> 
> I balanced the offset difference in [4503e45](https://github.com/GeyserMC/Geyser/pull/4676/commits/4503e45b157b002d4991f7b96b28a58fad2f54d1)

I don't see a difference 
![image](https://github.com/GeyserMC/Geyser/assets/56083016/8d06e8cb-e220-4c02-9124-cd78d02a45fa)

I'm using this build 
![image](https://github.com/GeyserMC/Geyser/assets/56083016/ae2159b8-226f-4feb-8ca1-5a9db2416e03) is it correct?

**Comment by alexdev03** [comment]
Now it's clearly better, thanks 
![image](https://github.com/GeyserMC/Geyser/assets/56083016/23534159-c1ac-491e-9d7a-5e8792184ea2)

I think the offset it's enough

**Comment by onebeastchris** [comment]
Closing as completed - the latest commit should resolve this.
