### ISSUE TITLE
Invalid username caused by wrong UUID

### ISSUE THREAD

**Issue by zhengguoyi** [GeyserMC/Geyser#4441]
### Describe the bug

When a Bedrock Edition player enters the game, it prompts that the username contains invalid characters. I don’t know if it is too long or contains invalid characters. From the console, it seems that it is because it is too long?

### To Reproduce

A bug occurs after entering the game

### Expected behaviour

Loggin success

### Screenshots / Videos

![3E1BD197C41D038D9DDFE82C47A394FF](https://github.com/GeyserMC/Geyser/assets/59115157/d0598444-26da-4a32-9605-d15629c9a665)
![image](https://github.com/GeyserMC/Geyser/assets/59115157/e0a982c4-89ae-417d-8198-8758f7c9f891)

### Server Version and Plugins

Geyser-Fabric

### Geyser Version

Geyser-Fabric-2.2.2-SNAPSHOT-429

### Minecraft: Bedrock Edition Device/Version

1.20.4 Minecraft for Windows

**Comment by sandeepjak2007** [comment]
I am on it

**Comment by onebeastchris** [comment]
Please send a geyser dump (run `geyser dump` in the server console & send a link here)

**Comment by RaTaiHok** [comment]
> Please send a geyser dump (run `geyser dump` in the server console & send a link here)

hello,I am the server's owner
this is the result in console:
https://dump.geysermc.org/NgoD0Nkql2Iz63bApuAxH3mJpuwA0cd5

**Comment by onebeastchris** [comment]
This issue is caused by your auth plugin; not Geyser. Furthermore - we do not support offline mode servers.

**Comment by RaTaiHok** [comment]
> This issue is caused by your auth plugin; not Geyser. Furthermore - we do not support offline mode servers.

well,thank for your answer
