### ISSUE TITLE
Can make lower version of Bedrock join higher server？

### ISSUE THREAD

**Issue by loond0l** [GeyserMC/Geyser#4442]
### What feature do you want to see added?

Such as，can make the Bedrock 1.18.31 join a 1.20.2 version server

### Are there any alternatives?

Such as，can make the Bedrock 1.18.31 join a 1.20.2 version server

**Comment by Camotoy** [comment]
As Geyser auto-updates, this is not something we're interested in doing. Thanks anyway.
