### ISSUE TITLE
Player Nametags Disappear upon death.

### ISSUE THREAD

**Issue by Quoats** [GeyserMC/Geyser#4444]
### Describe the bug

Player Nametags Disappear upon death. (Relogging fixes but only until another player dies.) 
This is also done on a completely fresh install of literally everything so I'm assuming its not specific to me.

### To Reproduce

Kill another player on bedrock and when they respawn u cant see their nametag.

### Expected behaviour

Player nametags always show even when not being looked at.

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/117341325/569716b3-73f8-4a7d-a902-13be9a017980

### Server Version and Plugins

![image](https://github.com/GeyserMC/Geyser/assets/117341325/fe7f004c-3b66-475b-afb3-1c7bbefa2979)
![image](https://github.com/GeyserMC/Geyser/assets/117341325/2e6dae56-f3dc-46f3-9228-c346c400951d)

### Geyser Dump

https://dump.geysermc.org/hFoDfMnzBBMCgJPuxhNr22eMgarYGYnf

### Geyser Version

Build #430 2/14/24 (latest as of now) (Was happening to me in earlier though)

### Minecraft: Bedrock Edition Device/Version

Win 10 Bedrock 1.20.60

**Comment by Quoats** [comment]
Not sure if I downloaded right (new to github sry lol), but I clicked the download under artifacts and with that the issue is still persisting. 
![image](https://github.com/GeyserMC/Geyser/assets/117341325/def7a08b-fef1-4338-a013-c86cccfdc63f)

Do I need to build it myself or did I do it right?

**Comment by onebeastchris** [comment]
https://geysermc.org/download
Download the latest version here :)

**Comment by Quoats** [comment]
thx much, but issue is still happening for me :(

**Comment by Quoats** [comment]
Wow interesting, do you think that luck perms ranks would fix at as-well then? gonna test real quick.

**Comment by Quoats** [comment]
ohh makes since lol

**Comment by Quoats** [comment]
Ya that works, ima just setup a default team for everyone for now, thx for the fix!

**Comment by Quoats** [comment]
ya np

**Comment by Quoats** [comment]
yes it does work, Thanks A Million!
