### ISSUE TITLE
NPCs error with Citizens

### ISSUE THREAD

**Issue by Mdsh9** [GeyserMC/Geyser#4448]
### Describe the bug

When you create NPC Player with Citizens, the console in the proxy spam this: Haven't received PlayerListEntry packet before spawning player! We ignore the player UUID from Citizen.

### To Reproduce

1. Create a NPC Citizen
2. Restart server
3. Join with a Bedrock account
4. See the console of the proxy

### Expected behaviour

Spam from the UUIDs of the Citizens

### Screenshots / Videos

Console log

![imagen](https://github.com/GeyserMC/Geyser/assets/113609845/6a7407d2-4227-4017-9551-a94a6c7d670f)

UUID from Citizens Config "saves.yml"

![imagen](https://github.com/GeyserMC/Geyser/assets/113609845/e24679b3-f29b-4a5a-850f-235088a0fc22)

Citizens Version

![imagen](https://github.com/GeyserMC/Geyser/assets/113609845/a2f292e0-c486-41fd-a70d-6e77b21fc7bd)

### Server Version and Plugins

![imagen](https://github.com/GeyserMC/Geyser/assets/113609845/924df90d-97e8-491e-a92c-5e3acc38ac3e)

### Geyser Dump

https://dump.geysermc.org/m2rlYXEUfffAuJ2qbtpvEz9GoYW1yNpG

### Geyser Version

Geyser versión 2.2.2-SNAPSHOT (git-master-8b170d6) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.60/1.20.61

### Minecraft: Bedrock Edition Device/Version

Android

### Additional Context

Issue in Citizens GitHub

https://github.com/CitizensDev/Citizens2/issues/3094

**Comment by onebeastchris** [comment]
A Java client would behave the same way - a player list entry must be sent to the client before a player can be spawned.

Possible issues here:
- Check if a 1.20.4 Java client gets the same errors in the client log.
- Check for other errors, especially from e.g. ViaVersion.

Ultimately, this is Geyser imitating a Java client, and not a bug.
