### ISSUE TITLE
Unable to connect after update 1.20.62

### ISSUE THREAD

**Issue by MicheleBiena** [GeyserMC/Geyser#4452]
### Describe the bug

Bedrock users got "Unable to connect to world" error immediately after the new update. On Discord I saw that it's an hotfix and it shouldn't break current Geyser version but I tried updating Geyser, Floodgate, Paper, even recreated the server from scratch but every test returns "Your server is likely unreachable from outside the network!"

Last session log: https://mclo.gs/CFCoIGb
Current geyser config file: https://pastebin.com/DxrgTfqS

The server is hosted on LowHosting and I've never had any problem with Geyser before.

### To Reproduce

Restart the server and try to connect from bedrock, or run "geyser connectiontest"

### Expected behaviour

No errors as before this update.

### Server Version and Plugins

Paper version git-Paper-430 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4939f87)

Floodgate Version 2.2.2-SNAPSHOT (b96-7f38765) (branch: master)

### Geyser Dump

https://dump.geysermc.org/6JnRFm0jnMQ206mkgoZ73Y4eU2U6cL2r

### Geyser Version

 Geyser version 2.2.2-SNAPSHOT (git-master-8b170d6) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.60/1.20.61)

### Minecraft: Bedrock Edition Device/Version

1.20.62

**Comment by mvnd06** [comment]
+1 I'm also encountering this error after updating to 1.20.62

**Comment by onebeastchris** [comment]
"Unable to connect" errors usually imply a configuration issue, and should not be version specific. Here specifically, i've tried to connect to your server on both 1.20.62 and 1.20.50 - both failed.
Please see our wiki for how to setup Geyser correctly: https://wiki.geysermc.org/geyser/setup/
For further configuration help, please ask in our discord server - we'll be able to help there.
