### ISSUE TITLE
Cannot join to Waterfall.

### ISSUE THREAD

**Issue by TomatoGarden666** [GeyserMC/Geyser#4457]
### Describe the bug

I am a server admin.If i use Geyser,the bedrock player can join 3 second then be kick.I see my server log(waterfall),it's because"A decoder exception has been thrown",i find the error in github,a user says:Client sends invalid packet.So i want to fix the bug.

### To Reproduce

This error will reproduce if you use it directly, and it will appear on some servers.You can join to "ee707007-d4cf-0213-a07b-e5033e99ca63.openfrp.cc:19133"to see the error.

### Expected behaviour

fix this error

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/94282242/12671ba0-a3a2-4617-9f34-2a502dfda3c1)

### Server Version and Plugins

![image](https://github.com/GeyserMC/Geyser/assets/94282242/fb8b6cf6-e581-47f2-b981-8c2b34d351c3)
Waterfall plugins:
![image](https://github.com/GeyserMC/Geyser/assets/94282242/aea25362-e1b9-482d-8d35-f84a03f8116d)
Paper plugins:
![image](https://github.com/GeyserMC/Geyser/assets/94282242/83495c1d-03ce-4f4b-95be-95f668824f07)

### Geyser Dump

https://dump.geysermc.org/ykb2R4aYii7ETReZQ5xmqQnjMbi1m2IU

### Geyser Version

 2.2.0-SNAPSHOT (git-master-a0d6048)

### Minecraft: Bedrock Edition Device/Version

1.20.50 "Microsoft Windows 10"

**Comment by onebeastchris** [comment]
Update ViaVersion to 4.9.3 or later; that should resolve it

**Comment by TomatoGarden666** [comment]
ok,i will try.thanks!



---Original---
From: ***@***.***&gt;
Date: Sat, Feb 24, 2024 19:15 PM
To: ***@***.***&gt;;
Cc: "Guancheng ***@***.******@***.***&gt;;
Subject: Re: [GeyserMC/Geyser] Cannot join to Waterfall. (Issue #4457)




 
Update ViaVersion to 4.9.3 or later; that should resolve it

**Comment by TomatoGarden666** [comment]
hmm...but now have a new bug:skin cannot be see.other(java)player see this player's skin is Alex.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Sat, Feb 24, 2024 19:15 PM
To: ***@***.***&gt;;
Cc: "Guancheng ***@***.******@***.***&gt;;
Subject: Re: [GeyserMC/Geyser] Cannot join to Waterfall. (Issue #4457)




 
Update ViaVersion to 4.9.3 or later; that should resolve it

**Comment by onebeastchris** [comment]
Please join our discord (https://discord.gg/geysermc) server for further support - we don't provide support via GitHub.

**Comment by TomatoGarden666** [comment]
sorry!I am in China mainland,so I cannot join your discord.can you tell me in there or in email?



---Original---
From: ***@***.***&gt;
Date: Sat, Feb 24, 2024 19:42 PM
To: ***@***.***&gt;;
Cc: "Guancheng ***@***.******@***.***&gt;;
Subject: Re: [GeyserMC/Geyser] Cannot join to Waterfall. (Issue #4457)




 
Please join our discord (https://discord.gg/geysermc) server for further support - we don't provide support via GitHub.
