### ISSUE TITLE
Modded biomes are shown as missing texture on bedrock.

### ISSUE THREAD

**Issue by mageowl** [GeyserMC/Geyser#4458]
### Describe the bug

When using the [Terralith](https://modrinth.com/mod/terralith) mod/datapack on fabric, all blocks inside the custom biomes are missing textures.

### To Reproduce

1. Install Terralith for 1.20.4 from [Modrinth](https://modrinth.com/mod/terralith)
2. Make a world with the seed -7126332531693232147
3. Join on Bedrock

### Expected behaviour

Blocks appear normally, even in modded biomes.

### Server Version and Plugins

This server is running Geyser version 2.2.2-SNAPSHOT (git-master-f8e6d26) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.60/1.20.61)

### Geyser Version

2.2.2-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20.40, IPad

**Comment by onebeastchris** [comment]
Terralith, to my knowledge, doesn't add custom blocks, and just uses vanilla blocks.
Could you send a screenshot of what happens on Bedrock vs Java?

**Comment by mageowl** [comment]
Nevermind. This was an issue to do with YUNG's API, not Geyser.
