### ISSUE TITLE
User Infomation cannot be saved.

### ISSUE THREAD

**Issue by TomatoGarden666** [GeyserMC/Geyser#4459]
### Describe the bug

When using online mode, the user's information cannot be saved on the server side, resulting in the user having to log in every time they rejoin the game.

### To Reproduce

I don't know how to reproduce.

### Expected behaviour

save user information

### Geyser Dump

https://dump.geysermc.org/EuGmXCsTMUB9QgmTAmjPf27JVIlXsQEF

### Geyser Version

 2.2.0-SNAPSHOT (git-master-a0d6048)

### Minecraft: Bedrock Edition Device/Version

1.20.50 "Microsoft Windows 10"

**Comment by onebeastchris** [comment]
Please try replicating the issue with an official build from [our downloads page](https://geysermc.org/download) - we do not provide support for non-official builds. Especially those that implement deprecated features :p

**Comment by onebeastchris** [comment]
Closing due to no further response.
