### ISSUE TITLE
Geysermc-Bedrockify

### ISSUE THREAD

**Issue by GrayFoxyos** [GeyserMC/Geyser#4460]
### What feature do you want to see added?

I just downloaded bedrockify mod on my geysermc server hoping geyser will translate this mod correctly having in mind that the mod adds only existing blocks from bedrock to java. Unfortunately putting a dye in cauldron will make the block dissapear for bedrock players realizing i was wrong. I think if you two work together you can succeed to bring bedrock and java players even more closer. It will be the perfect cross over episode. I hope to see you working together! 

### Are there any alternatives?

I hope to see you working together!

**Comment by guifenske** [comment]
Hi, I think that bedrockify is a client-side only mod..

**Comment by GrayFoxyos** [comment]
Maybe if they work together will make the mod for servers too

**Comment by Camotoy** [comment]
This is not something we'd want to add within Geyser itself, but making a Geyser extension to add the cauldron block would be fine by us! 

Thanks for the request anyway.

**Comment by CherubicBoot** [comment]
any update for the extension for this?
