### ISSUE TITLE
Block placing is glitchy on Bedrock

### ISSUE THREAD

**Issue by facredit** [GeyserMC/Geyser#4461]
### Describe the bug

.

### To Reproduce

.

### Expected behaviour

.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/613168464634576897/1209815063532277840/Minecraft_2024-02-21_14-07-49.mp4?ex=65e84b14&is=65d5d614&hm=cdd1ed0e9731c881de5608826844f06161627ce2a7f602ddaaa7d25e68e98577&

### Server Version and Plugins

![image](https://github.com/GeyserMC/Geyser/assets/157518377/615b1e4d-280d-4ebc-9b48-3a20e43b95af)

### Geyser Dump

.

### Geyser Version

latest

### Minecraft: Bedrock Edition Device/Version

1.20.60, Windows 10

### Additional Context

.

**Comment by facredit** [comment]
disable-bedrock-scaffolding is false*

**Comment by onebeastchris** [comment]
This issue isn't filled out properly, and the linked video is no longer available.

If this bug still exists, please fill out the template fully, and provide reproduction steps
