### ISSUE TITLE
Players can't join my server

### ISSUE THREAD

**Issue by Adrigamer2950** [GeyserMC/Geyser#4462]
### Describe the bug

I am receiving a lot of reports from the bedrock players of my server beacuse they can't join the server in random moments of the day, throwing this error: "Hasn't been able to connect to the world". When it happens it also makes the server doesn't ping, and it happens to random players, not everyone at once

### To Reproduce

1. Setup the proxy
2. Try to join the server
3. Receive an error (or get in, it sometimes does let you in and sometimes it doesn't)

### Expected behaviour

You get connected to the server successfully

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/58531641/fb2ed646-46f6-4161-8826-eabef5b66e72)

### Server Version and Plugins

Velocity 3.3.0-SNAPSHOT (git-6d7335b2-b325)

### Geyser Dump

https://dump.geysermc.org/8pgdUPgRG0OsKCHmJXBG66c8fRmvL6iK

### Geyser Version

2.2.2-SNAPSHOT (git-master-aca368e)

### Minecraft: Bedrock Edition Device/Version

Every version, Every device

### Additional Context

Users can't join my server, sometimes it doesn't ping, sometimes it just doesn't let you in, but always there's an error in the client: "Hasn't been able to connect to the world"

**Comment by onebeastchris** [comment]
This is a setup/configuration issue; so please look at the following guides:
- setup guide: https://wiki.geysermc.org/geyser/setup/
- unable to connect troubleshooting guide: https://wiki.geysermc.org/geyser/fixing-unable-to-connect-to-world/

For further configuration help, please join the Geyser discord for help.
