### ISSUE TITLE
Blocks dont break having low and high ping

### ISSUE THREAD

**Issue by Dakigex** [GeyserMC/Geyser#4467]
### Describe the bug

Me and my friends got a server open and played on it, since i have java edition the server works perfectly for me, since it is a purpur server, but my friends reported that **they cant break and place blocks**, they cant punch, **they cant do almost everything**, i checked the configurations of the server and the geyser ones, **nothing is wrong**, also, the server is from HolyHosting

### To Reproduce

_**I dont know what this means at all, but i will try to give instructions**_

1: Create a server (Mines form HolyHosting)
2: Make it Purpur 1.20.4
3: Upload the Spigot and the Floodgate .jar
4: Run the server (obviously with the port configured)
5: Connect to the server

### Expected behaviour

_**Also dont know what this means but i will try to explain**_

I expected to work as usual, i made servers before with the geyser plugin and this never happened.

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/74074223/e9a0fa9b-e90a-4bb5-8642-6a3a51b6bc51

### Server Version and Plugins

Purpur Build 2152 Minecraft 1.20.4

### Geyser Dump

https://dump.geysermc.org/V1U7j3r71rAVE0E0S5I0z2yTG7wq407Y

### Geyser Version

Geyser version 2.2.2-SNAPSHOT (git-master-6a51d82) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.60/1.20.61)

### Minecraft: Bedrock Edition Device/Version

1.20.62, Android

**Comment by Kas-tle** [comment]
This is likely just spawn protection. Have your friends move further from spawn or disable spawn protection in your server properties.

**Comment by onebeastchris** [comment]
Closing as this is likely not a Geyser issue, as mentioned by Kastle
