### ISSUE TITLE
Unable to join server when use frp and enable use-proxy-protocol

### ISSUE THREAD

**Issue by DongShaoNB** [GeyserMC/Geyser#4469]
### Describe the bug

I use frp software to forward my geyser server, after enable bedrock.use-proxy-protocol in config, i can't join geyser server

### To Reproduce

1. Use frp client forward geyser server
2. Enable bedrock.use-proxy-protocol in config
3. Use frp server IP join geyser server

### Expected behaviour

Be able to join geyser server

### Geyser Dump

https://dump.geysermc.org/apk0WdRDGDo2ta4FC4AV9TsirLmFmjWO

### Geyser Version

2.2.2-SNAPSHOT (git-master-f8e6d26)

### Additional Context

debug log: https://mclo.gs/B31I5HI

**Comment by Camotoy** [comment]
Does it work if you disable use-proxy-protocol?

**Comment by DongShaoNB** [comment]
> Does it work if you disable use-proxy-protocol?

yes, but i want to get player real ip

**Comment by Camotoy** [comment]
You'd need to use something that supports the HAProxy Protocol then, which forwards the correct IP.
