### ISSUE TITLE
World border does not render/stop player on bedrock

### ISSUE THREAD

**Issue by appletechgeek** [GeyserMC/Geyser#447]
**Describe the bug**

the bedrock client does not see the world border or get stopped by walking past it
but does get damaged.
**To Reproduce**

set world border small 
login with bedrock client and java to see where border is and walk past it using bedrock

**Expected behavior**

the player at least gets preventing from walking farther/notified they has reached the border

**Server Version**

craftbukkit version git-spigot-9de398a09c887d4 (mc 1.14.4) (implementing API Version 1.14.4-r0.1-Snapshot)
**Geyser Version**
using bukkit plugin 
i've got no idea. its the one from announcements on 26-04-2020 i cant find any ver numbers anywhere
**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

only plugins are world edit/viaversion and floodgate

**Comment by rtm516** [comment]
Bedrock doesn't have a world border but could be replaced by a chat message and just stoping movement past where it should be.
https://wiki.vg/Protocol#World_Border

**Comment by AnonAlpha** [comment]
Try to use the worldborder plugin, that works for me, it can be an alternative now

**Comment by awgybop1** [comment]
You could substitute the WorldBorder by a small invisiblebedrock barrier

**Comment by Trains77** [comment]
this could be substituted with the new border blocks in Minecraft Bedrock, make the client think there are border blocks at the world border and the Survival/Adventure players wont be able to leave it

**Comment by CleanCorpze** [comment]
Yeah I have this problem too, players just run through the border and die, it's kinda funny, hopefully, can be fixed, I would try the bedrock thing, players can still ender pearl, and its a factions server so people are always at the border building bases, but confused where exactly the border is. 
![image](https://user-images.githubusercontent.com/67211024/89134485-4e0b7c00-d4eb-11ea-869b-4debfea998a4.png)
![image](https://user-images.githubusercontent.com/67211024/89134509-624f7900-d4eb-11ea-95f9-15d639c17884.png)

**Comment by E404NNF** [comment]
As a temporary workaround you can use the WorldBorder plugin

**Comment by huwusky** [comment]
Bumping this, upon flying out of the world border all players using geyser will get disconnected

**Comment by elaineandsparky** [comment]
is there any news on if this is going to be added to the plugin as i don't really want to be adding another plugin to my server to work around this problem. (image of bedrock player beyond the border)

![image](https://user-images.githubusercontent.com/69724087/94897361-5cdcc380-0487-11eb-8f09-2a7e7fe8f2df.png)

**Comment by lukeeey** [comment]
We were working on this [here](https://github.com/GeyserMC/Geyser/commits/feature/world-border) and got it working, but it currently on displays a warning message when you're near the edge of the border.

**Comment by Comstepr** [comment]
@lukeeey is it possible you try to update the world border branch to 1.16 and then work on it from there? an alternative will just be to prevent any user from exiting the world border and have it be a config option.

**Comment by Loganh4005** [comment]
Uhh I not sure if any1 knows but the border block exists

**Comment by DoctorMacc** [comment]
We had someone else continue progress on the world border. I'll reach out to them soon.

**Comment by ConnorServers** [comment]
This shouldn't be low-priority.

It causes HUGE issues with mini-game and gamemode servers

**Comment by ConnorServers** [comment]
Wow... this was opened on "28 Apr 2020" as well.

**Comment by ConnorServers** [comment]
We can't use alternative plugins for mini-game/gamemode related worldborders ):

**Comment by ConnorServers** [comment]
**SOLUTION**

**BLUE & RED PARTICLES THERE INSTEAD when closely approaching WITH A 'BARRIER BLOCK' INSIDE OF IT.**

Cheers.

**Comment by rtm516** [comment]
> **SOLUTION**
> 
> **BLUE & RED PARTICLES THERE INSTEAD when closely approaching WITH A 'BARRIER BLOCK' INSIDE OF IT.**
> 
> Cheers.

Please see the linked PR

**Comment by ConnorServers** [comment]
> PR

I looked through the whole thread, where is it located?

**Comment by rtm516** [comment]
> > PR
> 
> I looked through the whole thread, where is it located?

On the right and also in the thread it says Camotoy linked it

**Comment by TheMonBonGH** [comment]
> **SOLUTION**
> 
> **BLUE & RED PARTICLES THERE INSTEAD when closely approaching WITH A 'BARRIER BLOCK' INSIDE OF IT.**
> 
> Cheers.

if a world border was moving, you can’t use physical blocks
