### ISSUE TITLE
Bedrock players get stuck on elevation changes (grass paths, soulsand, stairs, slabs, etc.)

### ISSUE THREAD

**Issue by googleooer** [GeyserMC/Geyser#4472]
### Describe the bug

The player character in Minecraft automatically steps up blocks with a height equal to or smaller than half a block, like slabs, stairs, grass paths, etc. This doesn't seem to work properly in Bedrock when playing on Geyser servers, because the player just rubberbands back to where they were.

### To Reproduce

1. Join the server from Bedrock
2. Try to automatically step up a block
3. The player rubberbands and gets stuck.

### Expected behaviour

The player should step up blocks as expected instead of rubberbanding.

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/35429559/a3cd5cec-ecad-42ce-805e-a03e9b8e387e

### Geyser Dump

https://dump.geysermc.org/1X4XuM9ZUhmg03s19VnGZXk4Zq08w8b1

### Geyser Version

2.2.2-SNAPSHOT (git-master-3c4a1a8)

### Minecraft: Bedrock Edition Device/Version

1.20.62, iPadOS 17

**Comment by onebeastchris** [comment]
This is likely caused by an anti-cheat plugin since Geyser doesn't emulate Java player movement exactly. If you have one; try without that.
Further, why do some slabs not have a texture in your world? Are you using an old/corrupted resource pack, or are those custom blocks?

**Comment by googleooer** [comment]
Oh i see, thanks, i'll check if there are any settings i can change to prevent this, and that's just a broken resource pack

**Comment by Kas-tle** [comment]
Closing since this is caused by an external plugin. Geyser is known to be incompatible with many anticheat plugins.
