### ISSUE TITLE
Epoll is not available; Erosion's Unix socket handling will not work.

### ISSUE THREAD

**Issue by Paper-wand** [GeyserMC/Geyser#4474]
### Describe the bug

Geyser crashed immediately after launching on my mac.
I enabled the debug mode and the last DEBUG is:
[12:43:54.487 main/DEBUG] Epoll is not available; Erosion's Unix socket handling will not work.

### To Reproduce

1. Double click Geyser-Standalone.jar
2. Geyser crashes a few seconds after the GUI appears. The mac crash report window appears.

### Expected behaviour

Launch normally

### Server Version and Plugins

Minecraft 1.20.2 with Fabric Loader 0.15.6
	- animatica 0.6+1.20
	- bettermounthud 1.2.2
	- borderlessmining 1.1.9+1.20.2
	- c2me 0.2.0+alpha.11.24
	   |-- c2me-base 0.2.0+alpha.11.24
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.24
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.24
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.24
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.24
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.24
	   |-- c2me-notickvd 0.2.0+alpha.11.24
	   |-- c2me-opts-allocs 0.2.0+alpha.11.24
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.24
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.24
	   |-- c2me-opts-math 0.2.0+alpha.11.24
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.24
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.24
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.24
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.24
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.24
	   |-- c2me-server-utils 0.2.0+alpha.11.24
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.24
	   |-- c2me-threading-lighting 0.2.0+alpha.11.24
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.24
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- capes 1.5.3+1.20.2
	- citresewn 1.1.3+1.20
	   \-- citresewn-defaults 1.1.3+1.20
	- cloth-config 12.0.119
	   \-- cloth-basic-math 0.6.1
	- continuity 3.0.0-beta.4+1.20.2
	- controlify 1.7.0+1.20.2
	   |-- dev_isxander_libsdl4j 2.28.2-11
	   |-- org_hid4java_hid4java 0.7.0
	   \-- org_quiltmc_quilt-json5 1.0.3
	- debugify 1.20.2+1.0
	- dynamic_fps 3.3.3
	- e4mc_minecraft 4.0.1
	- enhancedblockentities 0.9.1+1.20.2
	   |-- advanced_runtime_resource_pack 0.8.0
	   \-- spruceui 5.0.3+1.20.2
	- entity_model_features 1.2.3
	- entity_texture_features 5.2.1
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.3
	- fabric-api 0.91.4+1.20.2
	   |-- fabric-api-base 0.4.33+fce67b32a0
	   |-- fabric-api-lookup-api-v1 1.6.42+b1792f7da0
	   |-- fabric-biome-api-v1 13.0.14+b1792f7da0
	   |-- fabric-block-api-v1 1.0.12+73761d2ea0
	   |-- fabric-block-view-api-v2 1.0.1+73761d2ea0
	   |-- fabric-blockrenderlayer-v1 1.1.43+f4b7e424a0
	   |-- fabric-client-tags-api-v1 1.1.4+86b12645a0
	   |-- fabric-command-api-v1 1.2.37+f71b366fa0
	   |-- fabric-command-api-v2 2.2.16+b1792f7da0
	   |-- fabric-commands-v0 0.2.54+df3654b3a0
	   |-- fabric-containers-v0 0.1.80+df3654b3a0
	   |-- fabric-content-registries-v0 5.0.5+b1792f7da0
	   |-- fabric-convention-tags-v1 1.5.8+b1792f7da0
	   |-- fabric-crash-report-info-v1 0.2.20+f4b7e424a0
	   |-- fabric-data-generation-api-v1 13.1.10+b1792f7da0
	   |-- fabric-dimensions-v1 2.1.57+b1792f7da0
	   |-- fabric-entity-events-v1 1.5.26+b1792f7da0
	   |-- fabric-events-interaction-v0 0.6.10+b1792f7da0
	   |-- fabric-events-lifecycle-v0 0.2.69+df3654b3a0
	   |-- fabric-game-rule-api-v1 1.0.42+a44e16a6a0
	   |-- fabric-item-api-v1 2.1.33+b1792f7da0
	   |-- fabric-item-group-api-v1 4.0.15+e3d2bf3fa0
	   |-- fabric-key-binding-api-v1 1.0.38+f4b7e424a0
	   |-- fabric-keybindings-v0 0.2.36+df3654b3a0
	   |-- fabric-lifecycle-events-v1 2.2.27+b1792f7da0
	   |-- fabric-loot-api-v2 2.1.1+3ba460fba0
	   |-- fabric-message-api-v1 6.0.2+e3d2bf3fa0
	   |-- fabric-mining-level-api-v1 2.1.55+f4b7e424a0
	   |-- fabric-model-loading-api-v1 1.0.6+b1792f7da0
	   |-- fabric-models-v0 0.4.5+9386d8a7a0
	   |-- fabric-networking-api-v1 3.1.4+3fe0ff24a0
	   |-- fabric-object-builder-api-v1 12.1.2+2ff98d3ba0
	   |-- fabric-particles-v1 1.1.4+f4b7e424a0
	   |-- fabric-recipe-api-v1 2.0.13+52b3ebe5a0
	   |-- fabric-registry-sync-v0 4.0.11+b1792f7da0
	   |-- fabric-renderer-api-v1 3.2.1+2034447ca0
	   |-- fabric-renderer-indigo 1.5.1+2034447ca0
	   |-- fabric-renderer-registries-v1 3.2.49+df3654b3a0
	   |-- fabric-rendering-data-attachment-v1 0.3.39+73761d2ea0
	   |-- fabric-rendering-fluids-v1 3.0.30+f4b7e424a0
	   |-- fabric-rendering-v0 1.1.52+df3654b3a0
	   |-- fabric-rendering-v1 3.0.11+b1792f7da0
	   |-- fabric-resource-conditions-api-v1 2.3.11+239dafd8a0
	   |-- fabric-resource-loader-v0 0.11.12+b1792f7da0
	   |-- fabric-screen-api-v1 2.0.12+b1792f7da0
	   |-- fabric-screen-handler-api-v1 1.3.46+b1792f7da0
	   |-- fabric-sound-api-v1 1.0.14+f4b7e424a0
	   |-- fabric-transfer-api-v1 3.3.12+4944b5a5a0
	   \-- fabric-transitive-access-wideners-v1 5.0.3+fce67b32a0
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- fabricskyboxes 0.7.3+mc1.20.2
	- fabrishot 1.11.0
	- fastquit 3.0.0+1.20+
	- ferritecore 6.0.1
	- floodgate 2.2.0-SNAPSHOT
	   \-- cloud 1.8.4
	        |-- cloud_commandframework_cloud-brigadier_ 1.8.4
	        |-- cloud_commandframework_cloud-core_ 1.8.4
	        |-- cloud_commandframework_cloud-services_ 1.8.4
	        |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	        \-- io_leangen_geantyref_geantyref 1.3.13
	- fsb-interop 1.3.6+mc1.20.2-build.52
	- gammautils 1.7.17
	- immediatelyfast 1.2.8+1.20.4
	   \-- net_lenni0451_reflect 1.3.1
	- indium 1.0.27+mc1.20.1
	- iris 1.6.10
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- isxander-main-menu-credits 1.1.2
	- java 21
	- lambdynlights 2.3.3+1.20.2
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.3+1.20.2
	- languagereload 1.5.10+1.20.2
	- lithium 0.12.0
	- minecraft 1.20.2
	- mixintrace 1.1.1+1.17
	- modelfix 1.14
	- modernfix 5.10.1+mc1.20.2
	- modmenu 8.0.1
	- morechathistory 1.1.1
	- moreculling 1.20.4-0.22.0
	   |-- conditional-mixin 0.3.2
	   \-- mixinsquared 0.1.1
	- no_fog 1.3.5+1.16.5-1.20.4
	- nochatreports 1.20.2-v2.3.1
	- noisium 1.0.2+mc1.20.x
	- optigui 2.1.7
	   |-- optiglue 2.1.7-mc.1.19.3
	   |-- org_apache_commons_commons-text 1.10.0
	   \-- org_ini4j_ini4j 0.5.4
	- paginatedadvancements 2.4.2
	- puzzle 1.6.0+1.20.2
	   |-- midnightlib 1.5.0
	   |-- puzzle-base 1.6.0+1.20.2
	   |-- puzzle-gui 1.6.0+1.20.2
	   |-- puzzle-models 1.6.0+1.20.2
	   \-- puzzle-splashscreen 1.6.0+1.20.2
	- reeses-sodium-options 1.7.0+mc1.20.2-build.97
	- reterraforged 0.0.6
	- rrls 3.2.4+mc1.20.2-fabric
	- sodium 0.5.3
	- sodium-extra 0.5.3+mc1.20.2-build.114
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- starlight 1.1.3+fabric.5867eae
	- xaerominimap 23.9.7
	- xaeroworldmap 1.37.8
	- yet_another_config_lib_v3 3.2.1+1.20.2
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yosbr 0.1.2
	- zoomify 2.13.0
	   |-- com_akuleshov7_ktoml-core-jvm 0.5.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6

### Geyser Dump

I didn't find this option

### Geyser Version

2.2.2 build 446

### Additional Context

log:
[latest.log](https://github.com/GeyserMC/Geyser/files/14471810/latest.log)

It works properly when geyser-fabric-2.2.0-SNAPSHOT+build.393 is used.

**Comment by onebeastchris** [comment]
Please provide more information. Which java version are you using? Why do you give us a mod list when the issue is apparently with Geyser-Standalone?

Further, please try launching Geyser-Standalone without the GUI (`java -jar Geyser-Standalone.jar --nogui`); that should include a bit more info about this issue.

**Comment by Paper-wand** [comment]
Java version:
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Zulu21.32+17-CA (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Zulu21.32+17-CA (build 21.0.2+13-LTS, mixed mode, sharing)

Terminal output:
<img width="697" alt="截屏2024-03-15 21 19 52" src="https://github.com/GeyserMC/Geyser/assets/112165427/d43bb6f3-ac5d-4761-b274-63ac64b8cb36">

I give the mod list because the issue prompt asks me to do so. (Maybe I got it wrong because I'm not a native English speaker)
<img width="869" alt="截屏2024-03-15 21 27 38" src="https://github.com/GeyserMC/Geyser/assets/112165427/c5d1c5ec-0ac3-490c-ae52-a78eb2ea1e29">

**Comment by Kas-tle** [comment]
Is this an apple silicon mac?

**Comment by Paper-wand** [comment]
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 ports)
3.1GHz dual-core Intel Core i5
macOS Ventura 13.6.3 (22G436)

**Comment by Camotoy** [comment]
Maybe try https://adoptium.net/temurin/releases/?version=17 - get macOS aarch64.

I don't know if any of us have Apple Silicon Macs at our disposal.

**Comment by Paper-wand** [comment]
Still not working.
<img width="682" alt="截屏2024-03-16 12 31 38" src="https://github.com/GeyserMC/Geyser/assets/112165427/1b162c85-c2b8-4456-926c-e28db728039a">

In addition, this computer uses Intel silicon. So I got macOS x64.

**Comment by Kas-tle** [comment]
The thing is, Macs flat out do not support epoll. So I think it may not be a coincidence that such check is the last thing that's failing. Would be interesting to make a build without that check and see if it still fails.

**Comment by Kas-tle** [comment]
I do still have an old intel based mac so I guess I can see if I have this issue on there.

**Comment by Kas-tle** [comment]
Can reproduce on an intel based mac

**Comment by Kas-tle** [comment]
Should be resolved in the latest build (466) https://geysermc.org/download
