### ISSUE TITLE
Bedrock players can't join using Geyser on fabric servers

### ISSUE THREAD

**Issue by EchoEllet** [GeyserMC/Geyser#4479]
### Describe the bug

![image](https://github.com/GeyserMC/Geyser/assets/73608287/d8ca543a-d330-4c6f-ac1f-de36ea291a4c)

The server appears to be offline even though it's running without any errors

![image](https://github.com/GeyserMC/Geyser/assets/73608287/9e79eb01-553f-48ad-bc01-a56e6a1c1a9a)

I tried changing the default port and it didn't help, I tried server address and I still getting the same result

I tried different versions of Geyser mod for fabric, the server is offline and I also changed the auth mode to offline

![image](https://github.com/GeyserMC/Geyser/assets/73608287/6d4ddc4c-4053-4823-916c-81d58429408e)

I also tried out running the server with the default values and it didn't work

I have no mods installed other than Geyser and Fabric api

### To Reproduce

1. Install the latest version of Fabric server loader (Minecraft 1.20.4 with Fabric Loader 0.15.7)
2. Download the latest version of Fabric Api and Geyser (which both are in the mods folder)
3. Run the server in offline mode (update it in server.properties, set online-mode to false) and change the auth mode to auto or offline in the config of Geyser fabric

### Expected behaviour

It would be nice to be able to join and crossplay

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/73608287/72485324-a842-43a1-961b-d820b25af67b)

![image](https://github.com/GeyserMC/Geyser/assets/73608287/668fc7b6-a3b4-42e9-8d74-44a736a3ae3c)

![image](https://github.com/GeyserMC/Geyser/assets/73608287/71d40905-84ad-4386-b96b-984ca64cc010)

### Server Version and Plugins

Output: 
This server is running Geyser version 2.2.2-SNAPSHOT (git-master-621dc6f) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.60/1.20.61)

(Minecraft 1.20.4 with Fabric Loader 0.15.7)
I don't have any other mods/plugins installed

### Geyser Dump

https://dump.geysermc.org/NwjDEfGxriIqFZen6kE6iEqKXxNnYR4w

### Geyser Version

Geyser version 2.2.2-SNAPSHOT (git-master-621dc6f)

### Minecraft: Bedrock Edition Device/Version

v1.20.62

**Comment by Kas-tle** [comment]
Check https://wiki.geysermc.org/geyser/fixing-unable-to-connect-to-world/, specifically the section at the end about loopback. Please join our Discord for further support questions, as this is likely a configuration issue.

**Comment by onebeastchris** [comment]
Closing as this is likely a configuration issue - see the link Kastle sent for the fix.

**Comment by ellet0** [comment]
> Closing as this is likely a configuration issue - see the link Kastle sent for the fix.

That's not correct, the bedrock server appears to be offline 

I didn't change anything in the configurations, it's the default so it's supposed to work

**Comment by Kas-tle** [comment]
Please read the documentation we sent. It describes the exact issue you're having (trying to connect to a server hosted on the same machine as the bedrock client).

**Comment by onebeastchris** [comment]
As our setup guide mentions, there unfortunately are issues even when self-hosting with a default configuration - most notably, a windows issue that's preventing Minecraft: Bedrock edition to connect on the server if both are on the same device. Our setup guide, and the docs linked by Kastle earlier mention this & show what's needed to get it working.

If you still face issues with using Geyser, we'd gladly provide further help in the GeyserMC discord server :)

**Comment by ellet0** [comment]
> As our setup guide mentions, there unfortunately are issues even when self-hosting with a default configuration - most notably, a windows issue that's preventing Minecraft: Bedrock edition to connect on the server if both are on the same device. Our setup guide, and the docs linked by Kastle earlier mention this & show what's needed to get it working.
> 
> If you still face issues with using Geyser, we'd gladly provide further help in the GeyserMC discord server :)

I just tried the bedrock version on a different device, and it seems to work, I tried this mod before 2 years, and it works on the same machine without any issues or changing anything 

But I was using paper (spigot plugin), so I thought it was an issue with the fabric apo specific code, but it wasn't 

Thank you for your time
