### ISSUE TITLE
Incorrect Attack Indicators on custom mapped weapons

### ISSUE THREAD

**Issue by amnithyst** [GeyserMC/Geyser#4486]
### Describe the bug

Attack Indicators on custom mapped weapons are either not showing or not showing correctly

### To Reproduce

1. Create a custom mapped netherite sword for example
2. Hover over the item in-game and compare to default netherite sword

### Expected behaviour

To display the correct attack indicator.

### Screenshots / Videos

![2024-03-12_12 30 30](https://github.com/GeyserMC/Geyser/assets/20825291/06f13b1d-76af-4872-aee9-1e8837462399)
![Screenshot 2024-03-12 123003](https://github.com/GeyserMC/Geyser/assets/20825291/51a97cb4-05b6-45a4-a6f8-ab239cb35bc8)
![Screenshot 2024-03-12 122948](https://github.com/GeyserMC/Geyser/assets/20825291/d094bb2d-da85-48af-8ee5-f421b7efc395)
![Screenshot 2024-03-12 124315mappings](https://github.com/GeyserMC/Geyser/assets/20825291/769e7a36-1a66-4837-98f1-8ef080d65901)

### Geyser Version

Geyser version 2.2.2-SNAPSHOT (git-master-1df63c6)

**Comment by onebeastchris** [comment]
Should be resolved in the latest build, no mappings changes necessary (extends from the item, as on Java). Thanks for creating the issue!
