### ISSUE TITLE
Chat crashes client

### ISSUE THREAD

**Issue by Adrigamer2950** [GeyserMC/Geyser#4487]
### Describe the bug

Whenever someone tries to chat, the game just crashes.

### To Reproduce

1. Use Geyser b459
2. Try to chat

### Expected behaviour

The game doesn't crash and the player can use chat freely

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/58531641/02853d3d-5fdb-4289-a70a-7e10591b10bc

### Server Version and Plugins

Velocity 3.3.0-SNAPSHOT (git-a008464e)
Plugins are listed in Geyser Dump

### Geyser Dump

https://dump.geysermc.org/HioMdjcZlxcCSKhI9islqtKBqB7pE4Ic

### Geyser Version

2.2.2-SNAPSHOT (git-master-1df63c6)

### Minecraft: Bedrock Edition Device/Version

1.20.70/71

**Comment by noaskers** [comment]
Can confirm same issue here ^

**Comment by onebeastchris** [comment]
Can you re-test on the latest Geyser build?
It seems like re-sending the commands packet isn't currently working - which unfortunately does break different commands on different servers :/

**Comment by onebeastchris** [comment]
send a new geyser dump

**Comment by noaskers** [comment]
https://dump.geysermc.org/xaJNXPSzsLgQQgmyLARKOdJ8gD0FOIml


Is still the issue with / commands

**Comment by onebeastchris** [comment]
try setting `command-suggestions` to false

**Comment by Kas-tle** [comment]
You can try again with the latest build http://download.geysermc.org/

**Comment by Adrigamer2950** [comment]
Ok, I'll test it when I have time

**Comment by Dxzo** [comment]
same issue here

**Comment by onebeastchris** [comment]
As mentioned in Kastle's comment above, please try updating to the latest version of Geyser and see if the issue persists. If it does, send a geyser dump here
