### ISSUE TITLE
Server Sent Broken Packet

### ISSUE THREAD

**Issue by 420noscope-exe** [GeyserMC/Geyser#4488]
### Describe the bug

I have two players, one on xbox one S, and one on playstation 4, who are unable to join the server after updating my Geyser version today.  However, I have other players on playstation 4  _and_ 5 who can join and play without issue.  All of these bedrock players did today's update (1.20.70/71).

### To Reproduce

1. Attempt to join server with Bedrock 1.20.70-1.20.71

### Expected behaviour

Players should be able to join without issue

### Screenshots / Videos

A picture sent from one of my players on xbox one S:

![IMG_0603](https://github.com/GeyserMC/Geyser/assets/25134554/1a20852b-6098-4d7c-9dfa-dc4767e83fd0)

### Server Version and Plugins

This server is running CraftBukkit version 4045-Spigot-c198da2-38fd4bd (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

dynmap, WorldEdit, eggThrow420, OpenInv, floodgate, personal420, bedrockhelpgeyser, caseyGun420, TeleCraft, Geyser-Spigot

### Geyser Dump

https://dump.geysermc.org/i5JIxyu66aNzFOLgJJb79jhMzRuV1Egp

### Geyser Version

This server is running Geyser version 2.2.2-SNAPSHOT (git-master-1df63c6) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.70)

### Minecraft: Bedrock Edition Device/Version

Xbox One S and Playstation 4 on 1.20.70

**Comment by onebeastchris** [comment]
If only consoles are affected, then it's likely an issue with the method how consoles join servers.

For example:
- if you're using BedrockConnect (often called the "DNS method"), you may need to use a DNS server that's updated to support 1.20.70.
- if you're using BedrockTogether/different app on the phone to connect, you should update it to connect.

**Comment by 420noscope-exe** [comment]
They all use BedrockTogether.  It's strange that some are having issues, and some aren't. I will make sure the two players having issues have updated their apps, and come back with the results.

**Comment by Kas-tle** [comment]
Given this seems to be a result of Bedrocktogether and not a packet we're sending, I'll close this.
