### ISSUE TITLE
Stuck in Building terrain forever

### ISSUE THREAD

**Issue by BlueBurgersTDD** [GeyserMC/Geyser#449]
**Describe the bug**
Bedrock client gets stuck at _Building terrain_

**To Reproduce**
Get a server and get multiverse, then send yourself to different worlds, the most times you try it will send you to the correct world. But some times it just gets stuck at _Building terrain_.

**Expected behavior**
It should send you to the world

**Screenshots / Videos**
https://i.imgur.com/LzddwfS.png

**Server Version**
PaperMC 1.12.2

**Geyser Version**
Latest standalone version (master branch)

**Minecraft: Bedrock Edition Version**
Latest (1.14.60)

**Additional Context**
Java version "1.8.0_241"
I'm not using any plugins that alter how you get sent to worlds

**Comment by RednedEpic** [comment]
Likely due to low latency or a laggy server. Please contact us on Discord.

**Comment by DoctorMacc** [comment]
I told him on Discord to make this issue so there's some documentation of it. :P There's at least two people who have gotten this issue.

**Comment by RednedEpic** [comment]
> I told him on Discord to make this issue so there's some documentation of it. :P There's at least two people who have gotten this issue.

If it continues to occur for other people, I will reopen this issue.

**Comment by BlueBurgersTDD** [comment]
> Likely due to low latency or a laggy server. Please contact us on Discord. 

It's not because of lag, it had 2 GB of ram and 19.8 TPS. Geyser and the server was locahosted. I also played on the same network, everything had 0 ping
