### ISSUE TITLE
Bedrock players become java players

### ISSUE THREAD

**Issue by angga7togk** [GeyserMC/Geyser#4498]
### Describe the bug

Either for bugs from geysermc or floadgate, sometimes the bedrock player is detected as a java player, there is no _ prefix and the resulting UUID is also the same as the java player, and this is very annoying,

This is very annoying because previously the Bedrock player played on a gamertag account that started with _, then he experienced a bug, became a Java player, and the items he produced on a gamertag account that started with _ would disappear, and that created problems for my server players.

### To Reproduce

join the server sometimes

### Expected behaviour

I want this to be fixed immediately, because my server member is confused and confused about why his items on the server are missing, even though he is experiencing a bug entering the server using Minecraft Bedrock but Minecraft Java is detected on the server.

### Screenshots / Videos

this is when experiencing a bug
![image](https://github.com/GeyserMC/Geyser/assets/90005225/4b3215f8-e585-45b1-a820-63e720aa365b)

and this is when you don't experience bugs, you can see it from the gamertag
![image](https://github.com/GeyserMC/Geyser/assets/90005225/354dfa2a-12fa-480d-9b1b-af028d3b877c)

### Server Version and Plugins

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version

[20:30:41 INFO]: Plugins (57): ajLeaderboards, AuctionHouse, AureliumSkills, BankPlus, BetterGUI, ChatCooldown*, Chunky, ClansLite, CMILib, CustomRank, CustomVoting, CyberLevels, DailyRewards, DecentHolograms, EconomyShopGUI, EntityClearer, Essentials, EssentialsSpawn, ExcellentCrates, floodgate, Geyser-Spigot, GeyserSkinManager, GreenJobs, GSit, InteractiveBooks, JSEngine, KeepItems*, LevelledMobs, LPC, LuckPerms, MessageAnnouncer, Minepacks, MOTD, Multiverse-Core, NBTAPI, NexAuth, NexEngine, Nightvision, ODailyQuests, PacketOrigin, PlaceholderAPI, ProtocolLib, Randomtp, RankMigrate, RedProtect, ServerSide, ServersNPC, SuperVanish, SupremeTags, TAB, uShop, Vault, ViaBackwards, ViaVersion, Votifier, WorldEdit, WorldGuard

### Geyser Version

2.2.2-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20.40 - 1.20.71

**Comment by Kas-tle** [comment]
Provide a geyser dump by running `geyser dump` in console and post the link here.

**Comment by angga7togk** [comment]
> Provide a geyser dump by running `geyser dump` in console and post the link here.

https://dump.geysermc.org/aeNhiTLNuFfaKGJMyry0n9b6t244Y6Ae

**Comment by Kas-tle** [comment]
Offline mode and login plugins are not supported.

**Comment by Dxzo** [comment]
I reported this issue a long time ago and until now they haven't solved it, it even happens if you only have the geyser and floogate plugin on the server, but it happens more frequently when you have many more plugins. My only solution was to use a proxy (velocity) since using it does not happen.

And yes, it is a very annoying problem that's why I had to migrate it

**Comment by angga7togk** [comment]
> I reported this issue a long time ago and until now they haven't solved it, it even happens if you only have the geyser and floogate plugin on the server with online mode, but it happens more frequently when you have many more plugins. My only solution was to use a proxy (velocity) since using it does not happen.
> 
> And yes, it is a very annoying problem that's why I had to migrate it

thanks for the suggestion
