### ISSUE TITLE
Index Out of Bounds Error

### ISSUE THREAD

**Issue by Ninjawolf0007** [GeyserMC/Geyser#4508]
Describe the bug
Random disconnecting/inability to join server from java client (on the same machine)

To Reproduce:
Unsure. This happens shortly after logging in.

Expected Behavior:
No index out of bounds error

Server Version and Plugins
Fabric loader 0.15.7 launcher.1.0.0 for Minecraft 1.20.4
Geyser for Fabric Build GeyserMC/Floodgate#466
Floodgate for Fabric Build GeyserMC/Floodgate#96

Geyser Dump
https://dump.geysermc.org/eSCGo5PxikQXJK8yPh6uVU6jAUltdtTj

Additional Context
If I connect via a bedrock client on the same machine, this error does not happen.

**Comment by Ninjawolf0007** [comment]
Here is the most recent log file: https://mclo.gs/TF7cCU3

**Comment by onebeastchris** [comment]
Unfortunately, that log does not show any errors. Please send a log that's showing the errors you're getting when trying to join using Geyser

**Comment by Ninjawolf0007** [comment]
![IooB Error](https://github.com/GeyserMC/Geyser/assets/11599572/379545ee-a639-4c07-bb52-dac1988aa896)

**Comment by onebeastchris** [comment]
That's a java client error. Geyser does not modify anything for Java clients.
Please ask in the fabric discord for help with this issue.
