### ISSUE TITLE
sound support

### ISSUE THREAD

**Issue by ayunami2000** [GeyserMC/Geyser#451]
**What feature do you want?**
Is it possible to use the code from https://github.com/DragonetMC/DragonProxy to implement support for sound?

**Comment by RednedEpic** [comment]
> **What feature do you want?**
> Is it possible to use the code from https://github.com/DragonetMC/DragonProxy to implement support for sound?

This is being worked on in the sounds branch.

**Comment by ayunami2000** [comment]
o

**Comment by lukeeey** [comment]
is it possible to use the code from https://github.com/GeyserMC/Geyser in DragonProxy?

**Comment by Tim203** [comment]
?

**Comment by Heath123** [comment]
> 
> 
> is it possible to use the code from https://github.com/GeyserMC/Geyser in DragonProxy?

You actually can if you keep the copyright header (which would effectively be a big boock of text saying "THIS IS COPIED")
