### ISSUE TITLE
Resource Packs not applying when in server

### ISSUE THREAD

**Issue by NEINtje** [GeyserMC/Geyser#4514]
### Describe the bug

So whenever a player tries to apply their own resource pack to my server it doesn't get applied.

The resource pack does work on a singleplayer world, and I am not using a proxy server.

### To Reproduce

1. Log onto a geyser server
2. Try to apply personal resource pack (one that has been installed without using the shop)
3. Doesn't apply

### Expected behaviour

Resource pack gets applied for the user

### Server Version and Plugins

This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)

![image_2024-03-21_193000420](https://github.com/GeyserMC/Geyser/assets/91952040/f14e9634-2002-4dd4-8e77-98d6dc336c39)
![image](https://github.com/GeyserMC/Geyser/assets/91952040/1a6e59e6-58f7-46e1-bc6d-576439a7a44b)

### Geyser Dump

https://dump.geysermc.org/51DGdRAFytC1TquONzCP8zvgioZfdE3E

### Geyser Version

2.2.2-SNAPSHOT (git-master-c3d4277) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.70/1.20.71)

### Minecraft: Bedrock Edition Device/Version

1.20.71

**Comment by Kas-tle** [comment]
I cannot reproduce this issue. Ensure the pack is active in the settings menu under global resources. Note this must be done before joining the server.

**Comment by NEINtje** [comment]
So I got some more "info", what happens is that the person applies the resource pack, then when logging on it removes the resource pack.
