### ISSUE TITLE
Some mobs' animation are lost

### ISSUE THREAD

**Issue by anthony114669** [GeyserMC/Geyser#4516]
### Describe the bug

When I am using Bedrock Edition to play my server, I can't see skeleton's shooting animation. There may be more mobs have this problem.

### To Reproduce

1.Switch gamemode to survival.
2.Look for a skeleton.
3.Wait for the skeleton shoot.

### Expected behaviour

The skeleton can have a correct shooting animation.

### Server Version and Plugins

Server Version

git-Paper-196(MC:1.20.1)

Geyser Version

version: 2.2.2-SNAPSHOT

Minecraft: Bedrock Edition Version

1.20.71

### Geyser Version

version: 2.2.2-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.20.71

**Comment by Camotoy** [comment]
With GeyserOptionalPack we can probably fix this, but I believe this is how a skeleton shooting looks like on Bedrock.

**Comment by Kas-tle** [comment]
In the case of the skeleton there does seem to be a slight difference between how shooting looks on Geyser and Bedrock singleplayer

![image](https://github.com/GeyserMC/Geyser/assets/26531652/bbc27c2e-87ec-4bf1-961b-b6942c005354)
![image](https://github.com/GeyserMC/Geyser/assets/26531652/b0d7077a-8fd0-4aee-b8f0-a768674f7533)

Notice in the top image of singleplayer Bedrock the skeleton draws its non-bow arm in towards the bow, while in the bottom image of the Geyser server the non-bow arm does not draw in towards the bow.

**Comment by anthony114669** [comment]
i just wanna add more information to see if maybe help with the fix, a will atacch another video showing the zombie not having his attack animation either

https://github.com/GeyserMC/Geyser/assets/60707163/96e93d62-3781-4664-947e-095bcd68f764

.

**Comment by anthony114669** [comment]
i dunno if this si related with the same bug but with a custom bow created with the optional pack and custom bow example this is hapening:

https://github.com/GeyserMC/Geyser/assets/60707163/45925a61-ef21-47e4-9b0b-9af18ba795aa

**Comment by anthony114669** [comment]
hello! any updates with this issue? thanks in advance!
