### ISSUE TITLE
Bedrock players unable to join - UUID Forward to bungee plugins

### ISSUE THREAD

**Issue by ICEconchy** [GeyserMC/Geyser#452]
**Describe the bug**
So I use the plugin advancedban and it requires UUID's to keep track of users. But it appears that when a bedrock player joins via geyser, it does not forward their UUID to the bungeecord plugins.

**To Reproduce**
Install a plugin which does not let users on without a UUID, for example advancedban.
Join with bedrock

**Expected behavior**
Bedrock players to be able to join.

**Screenshots / Videos**
N/A

**Server Version**
This server is running BungeeCord version git:BungeeCord-Bootstrap:1.15-SNAPSHOT:a1969b2:1493 by md_5

**Geyser Version**
Geyser version 1.0-SNAPSHOT bungeecord plugin
Floodgate, latest? I'm sorry but I'm unsure how to find this out

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by lukeeey** [comment]
This should already work in online mode

**Comment by ICEconchy** [comment]
> 
> 
> This should already work in online mode

It does not, the bungeecord is in online-mode

**Comment by DoctorMacc** [comment]
Are there any logs you can attach?

**Comment by ICEconchy** [comment]
> Are there any logs you can attach?

There is nothing from what I can see. Only a message from advanced ban saying a player tried to join without a UUID.

**Comment by DoctorMacc** [comment]
Looks like someone submitted an issue to AdvancedBan: https://github.com/DevLeoko/AdvancedBan/issues/317 
Are those steps any help?

**Comment by ICEconchy** [comment]
Ok so I tried it with those settings and got the same outcome. Here's what the console says
`29.04 19:16:40 [Server] INFO /MYIPNOTOUCHY tried to connect!
29.04 19:16:42 [Server] INFO Player connected with username ICEconchy
29.04 19:16:44 [Server] INFO Attempting to login using floodgate mode... authentication will be encrypted
29.04 19:16:44 [Server] INFO Loaded Floodgate key!
29.04 19:16:45 [Server] INFO ICEconchy (logged in as: ICEconchy) has connected to remote java server on address SERVERIPHERE
29.04 19:16:45 [Server] INFO ICEconchy has disconnected from remote java server on address SERVERIPHERE because of [AdvancedBan] Failed to fetch your UUID
29.04 19:16:45 [Server] INFO Bedrock user with ip: /MYIPNOTOUCHY has disconnected for reason CLOSED_BY_REMOTE_PEER`
https://gyazo.com/e1a4c880ea7dac7fdfdaf020eac17f5d

**Comment by DoctorMacc** [comment]
Seems like the latest AdvancedBan may have fixed it - are you able to compile that?

**Comment by ICEconchy** [comment]
> 
> 
> Seems like the latest AdvancedBan source on GitHub may have fixed it - are you able to compile that?

No I do not know how

**Comment by benrobson** [comment]
I will give it a compile and test it out.

**Comment by benrobson** [comment]
I compiled and tested it and it didn't work
```
10:27:27 [INFO] [Geyser-BungeeCord] /IP tried to connect!
10:27:27 [INFO] [Geyser-BungeeCord] Player connected with username shadowolfau
10:27:33 [INFO] [Geyser-BungeeCord] Attempting to login using floodgate mode... authentication will be encrypted
10:27:33 [INFO] [Geyser-BungeeCord] Loaded Floodgate key!
10:27:33 [INFO] [Geyser-BungeeCord] shadowolfau (logged in as: shadowolfau) has connected to remote java server on address 192.168.1.2
10:27:33 [INFO] [/192.168.1.2:55870] <-> InitialHandler has connected
10:27:34 [INFO] !! Failed fetching UUID of *shadowolfau
10:27:34 [INFO] !! Could not find key 'id' in the servers response
10:27:34 [INFO] !! Response: No Content
10:27:34 [INFO] Trying to fetch UUID form BackUp-API...
10:27:36 [INFO] !! Failed fetching UUID of *shadowolfau
10:27:36 [INFO] !! Could not find key 'uuid' in the servers response
10:27:36 [INFO] !! Response: OK
10:27:36 [INFO] !! !! Warning we have not been able to fetch the UUID of the Player *shadowolfau
10:27:36 [INFO] !! Make sure that the name is spelled correctly and if it is change your UUID-Fetcher settings!
10:27:36 [INFO] [Geyser-BungeeCord] shadowolfau has disconnected from remote java server on address 192.168.1.2 because of [AdvancedBan] Failed to fetch your UUID
10:27:36 [INFO] [Geyser-BungeeCord] Bedrock user with ip: /IP has disconnected for reason CLOSED_BY_REMOTE_PEER
```

**Comment by benrobson** [comment]
In my compilation test, I download and used the latest version of Geyser and Floodgate bungee cord and compiled the latest from the AdvancedBan master.

**Comment by DoctorMacc** [comment]
Closing as AdvancedBan should have fixed this problem.
