### ISSUE TITLE
Mod is not loaded into memory at all times, causing it to stop functioning when automatically updated.

### ISSUE THREAD

**Issue by Magicrafter13** [GeyserMC/Geyser#4526]
### Describe the bug

I kept trying to connect from my phone getting the generic (unable to connect) message. Checking my server logs I saw a lot of output but realized the first couple lines or so pretty much answer my question.

![Screenshot_20240327_092135_Termius](https://github.com/GeyserMC/Geyser/assets/29127566/cc69062a-bd44-42eb-90cc-a032ab73ac26)

See, in the screenshot it says NoSuchFileException and shows build 473 of the mod. In my mods folder I have build 474. I have a script automatically update a few crucial mods that need to remain at their latest versions. However the server only restarts every few days or so (based on Fedora security updates).

My understanding was that on startup, the Fabric server loaded all mods into RAM, and as such, deleting a file would not cause an issue. Apparently this is not entirely correct? But I've never had this issue with other mods to my knowledge, so I'm hoping there's something that can be done on the geyser side.

### To Reproduce

1. Start Fabric server with Geyser mod.
2. Delete Geyser jar file.
3. Try to connect from a Bedrock client.

### Expected behaviour

The mod continues working regardless of updates (file removal).

### Server Version and Plugins

There is no /version command, however I'm running `fabric-server-mc.1.20.4-loader.0.15
.7-launcher.1.0.0.jar`.

I have over 100 mods, and listing them all would take quite a while. Since the issue involves the Geyser file itself and not anything else, I don't think this information would help regardless.

### Geyser Dump

[09:30:34] [Server thread/INFO]: An unexpected error occurred trying to execute that command

### Geyser Version

Fabric build 473 ("loaded") / 474 (in filesystem).

### Minecraft: Bedrock Edition Device/Version

Android, iOS, and Xbox One (but presumably any version)

**Comment by onebeastchris** [comment]
This isn't a Geyser specific issue, and will instead happen with any mod that's copying resources from it's jar. Here, specifically, it's likely the translations - which are copied once initially.

Updating mod jars while the server is running is generally a bad idea, and you must restart the server to load mods properly.

**Comment by Magicrafter13** [comment]
Okay but could it be turned into some kind of config setting?

> generally a bad idea

That's nice in theory, except: if Geyser gets too out of date, suddenly Bedrock clients can't connect. Asking sysadmins to constantly manually implement updates (when they're able to safely restart) is, in my opinion, too much to ask.

And, specific to this case, I don't even need any extra locales. Even if our server gets non English speakers (doubtful), I don't need good strings and such, I really only care that they're able to play the game.

**Comment by onebeastchris** [comment]
I don't see how this is supposed to be a config option...?
You'd still have to restart the server/geyser to apply configuration changes, which makes it fairly pointless.

As for Bedrock updates: Yes, Geyser has to update frequently to support the newest Bedrock versions. However, that occurs ~once every two months. Other commits between that time are usually features, bugfixes, or somewhere in between.

If you want to auto-update - which is a good idea - you should. Managing when to restart your server to actually apply updates isn't something that's on us though - for any plugins or mods, heck, most programs, yeeting the jar and replacing it while the server is running is a bad idea. Instead, you could, for example, adapt a restart script to also pull in mod changes/replace jars that should be updated
