### ISSUE TITLE
Bossbar not showing the correct color

### ISSUE THREAD

**Issue by maxw2000** [GeyserMC/Geyser#453]
**Describe the bug**
The bossbar is not using the correct color.

**To Reproduce**
Having a red bossbar in the server.

**Expected behavior**
The bossbar should be red

**Screenshots / Videos**
https://youtu.be/z-eI8-VuOH4

**Server Version**

![image](https://user-images.githubusercontent.com/22998325/80578185-6198d980-8a08-11ea-9a36-f5b92e3aacf4.png)

**Geyser Version**
Build 96

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**

We are using 4 plugins, One of the plugin called Enthix_Core is our custom plugin that is doing almost everything.
![image](https://user-images.githubusercontent.com/22998325/80578352-9c027680-8a08-11ea-9248-6a323f730f87.png)
Code I used to create the bossbar
![image](https://user-images.githubusercontent.com/22998325/80578552-ea177a00-8a08-11ea-8174-295ec440de38.png)
![image](https://user-images.githubusercontent.com/22998325/80578629-0f0bed00-8a09-11ea-8233-34b70a8dd9b8.png)

**Comment by Tim203** [comment]
Thanks for providing such an detailed issue, but the fact is that even though protocol wise you can give them a color, the bedrock client will ignore it

**Comment by lukeeey** [comment]
So basically it’s not implemented in bedrock yet, go to the issue tracker and make (or comment on an existing) issue about bossbars lacking colour support.
