### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by RockyTheProtogen** [GeyserMC/Geyser#4537]
### Describe the bug

The server starts and runs up until geyser starts.

### To Reproduce

Start server normally and the server will do as expected.

Now add geyser-fabric-2.2.2-SNAPSHOT+build.479.jar

Start the server.

Server starts and crashes.

### Expected behaviour

To do as if the server were started without geyser-fabric-2.2.2-SNAPSHOT+build.479.jar

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/124413320/54285af1-9738-4529-ae05-03e122053c96

[crash-2024-04-02_17.51.00-server.txt](https://github.com/GeyserMC/Geyser/files/14828945/crash-2024-04-02_17.51.00-server.txt)

[latest.log](https://github.com/GeyserMC/Geyser/files/14828950/latest.log)

### Geyser Version

geyser-fabric-2.2.2-SNAPSHOT+build.479

**Comment by SageSphinx63920** [comment]
Port 25565 is already used by query so you might want to disable it.

**Comment by onebeastchris** [comment]
Yeah, that could be it. Generally speaking, this error means something (likely another instance of Geyser, or the Minecraft Query) is running on the port you have specified in the config. Please make sure you close all applications running on this port. If you don't recall opening anything, usually restarting your computer fixes this. See the [setup guide](https://wiki.geysermc.org/geyser/setup/) for instructions on how to configure Geyser.

Going to close this as this is likely a configuration issue - feel free to join our discord if you need further help.

**Comment by SageSphinx63920** [comment]
Actually it is pretty sure as query runs on UDP

**Comment by RockyTheProtogen** [comment]
Well thank you all for the help, it just kind of happened out of the blue so I wanted to be sure this wasn't some bug.

> Port 25565 is already used by query so you might want to disable it.

Port 25565 has been working, with surprisingly little to no compromise. I will change it if the problem persists.

>Yeah, that could be it. Generally speaking, this error means something (likely another instance of Geyser, or the Minecraft Query) is running on the port you have specified in the config. Please make sure you close all applications running on this port. If you don't recall opening anything, usually restarting your computer fixes this. See the [setup guide](https://wiki.geysermc.org/geyser/setup/) for instructions on how to configure Geyser.

Thanks, I will try these.

**Comment by RockyTheProtogen** [comment]
After a small amount of looking, I had curiously enabled query with no clue on what it did. This indeed was a configuration problem and entirely my fault.
The `enable-query=false` seems to fix it
