### ISSUE TITLE
Elytra Glige

### ISSUE THREAD

**Issue by OurLobanov** [GeyserMC/Geyser#4544]
### Describe the bug

The player constantly looks up and his wings open every time.

### To Reproduce

Start flying near the player

### Expected behaviour

To see where the player is flying and also so that the opening of the wings is not shown every time.

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/114523572/8e102ca3-1b6a-4f43-b4b6-89735ebe7fe2

### Geyser Version

Git Repo

### Minecraft: Bedrock Edition Device/Version

1.20.73

**Comment by rtm516** [comment]
Please provide a dump. Also what is your discord handle just incase I need to reach out?

**Comment by OurLobanov** [comment]
> Пожалуйста, предоставьте дамп. Кроме того, какой у вас псевдоним в Discord на случай, если мне нужно будет связаться?

https://dump.geysermc.org/Zk36WJzVSv2dub4vQ4ns2LrAxrnXcdyp 
Discord ourdev

**Comment by onebeastchris** [comment]
Is this still an issue with the latest version of Geyser?

**Comment by OurLobanov** [comment]
> Это все еще проблема с последней версией Гейзера?

yes

**Comment by onebeastchris** [comment]
This appears to be a client-side Bedrock bug (tested on a singleplayer 1.21.0 world) - see here for the bug report on Mojang's bug tracker: https://bugs.mojang.com/browse/MCPE-176172
Closing as this is a client-side bug. We'll have to wait until a Bedrock update fixes this
