### ISSUE TITLE
Items randomly disappears

### ISSUE THREAD

**Issue by SamGamerYT** [GeyserMC/Geyser#4550]
### Describe the bug

https://cdn.discordapp.com/attachments/1225659391433248778/1225664501588820059/18eac81471442-master_playlist.mov?ex=6621f404&is=660f7f04&hm=e0ca77a28d9f2e7f0727c6e4e0c8050368220c71c88222aa75d549773d89e57b&

Items has been disappearing whenever they open a GUI (sometimes)

### To Reproduce

Open a GUI

### Expected behaviour

Item not disappearing

### Screenshots / Videos

https://cdn.discordapp.com/attachments/1225659391433248778/1225664501588820059/18eac81471442-master_playlist.mov?ex=6621f404&is=660f7f04&hm=e0ca77a28d9f2e7f0727c6e4e0c8050368220c71c88222aa75d549773d89e57b&

### Server Version and Plugins

Latest
JK

[16:49:01 INFO]: Current: git-Purpur-2160 (MC: 1.20.4)*
Previous: git-Purpur-2159 (MC: 1.20.4)
* You are 6 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Geyser Dump

https://dump.geysermc.org/RVWd0WXZJq7ZXUkAcxfgGo2FQz1xyKzz

### Geyser Version

https://dump.geysermc.org/RVWd0WXZJq7ZXUkAcxfgGo2FQz1xyKzz

**Comment by onebeastchris** [comment]
Do the items reappear once you relog?
Otherwise, this is likely behavior from the Java server. Please also provide full replication steps with the least needed plugins

**Comment by SamGamerYT** [comment]
> Do the items reappear once you relog? Otherwise, this is likely behavior from the Java server. Please also provide full replication steps with the least needed plugins

They sadly don't reappear, it actually disappears.

**Comment by SamGamerYT** [comment]
> Do the items reappear once you relog? Otherwise, this is likely behavior from the Java server. Please also provide full replication steps with the least needed plugins

Happens quite randomly, Hard to give info about it. Most of the time it's opening a deluxe menu and then it disappears

**Comment by onebeastchris** [comment]
Unfortunately, without being able to reproduce this, there's nothing we can do on our end. I've not seen this behavior during my testing; and if this occurs only with specific plugins, that's likely an issue on their side.

If you have exact reproduction steps, please feel free to comment here/open a new issue.
