### ISSUE TITLE
geyser player Hud's disapear after Teleporting

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#4552]
### Describe the bug

when a geyser playe TP's they hud disapears (hotbar, health, armour everything)

### To Reproduce

teleport in world 

### Expected behaviour

for players huds to not disapear

### Screenshots / Videos

![IMG_0134](https://github.com/GeyserMC/Geyser/assets/92684055/f7a916fa-a379-4e40-8812-b3812e1b25d0)

### Server Version and Plugins

Current: git-Purpur-2166 (MC: 1.20.4)*

### Geyser Dump

https://dump.geysermc.org/g7EO6ugKQJJUhaYXVvlMsgJg9SOa0o84

### Geyser Version

487

### Minecraft: Bedrock Edition Device/Version

all bedrock clients

**Comment by lucasfrederico** [comment]
This is happening to me too

**Comment by prxgma** [comment]
Yep, happening to me too.

**Comment by lucasfrederico** [comment]
Any ETA to solve it?

**Comment by lucasfrederico** [comment]
@onebeastchris

**Comment by lucasfrederico** [comment]
ETA?

**Comment by 1470429149** [comment]
me too

**Comment by onebeastchris** [comment]
Unable to reproduce. Please provide further reproduction steps - does this occur with the `/tp` command? Or only with a specific plugin? Or specific distances?

**Comment by onebeastchris** [comment]
Closing due to no further response. If this bug still occurs, please provide updated replication steps here, and we'll attempt to reproduce it.

**Comment by WaffleBits** [comment]
hello this is happening to me is there a solution somewhere else or just not enough info ?

**Comment by onebeastchris** [comment]
@WaffleBits This was closed due to incomplete reproduction steps/us being not able to replicate the issue. If you can replicate it, let us know how, and we'll try and resolve it.
