### ISSUE TITLE
Geyser can be used in UDP Reflect DDOS Attack (?)

### ISSUE THREAD

**Issue by MossCG** [GeyserMC/Geyser#4558]
### Describe the bug

-------
About 2024.03, we found our server has some abnormal upload traffic on port 19132 with udp protocol.
![VK_7JD %MI0YILB4QM_MM8T](https://github.com/GeyserMC/Geyser/assets/77914339/7c80b3b9-cb51-4313-89bc-12ed1213562b)
with only one player or even no player in game, geyser create an upload traffic up to 50Mbps(My server only has 50Mbps upload bandwidth)
we capture packets(lan1, 19132 port only) by ikuai and found geyser send an 148-length packet after an connection with a cracy speed.
![image](https://github.com/GeyserMC/Geyser/assets/77914339/0eb6bd9d-44a2-4b06-b6e9-5e1d5cb0000d)
The version of geyser is 2.2.0-SNAPSHOT (git-master-acf24d4)  / Build 268
-------
Then we update to 2.2.2-SNAPSHOT (git-master-c9ca4c8) 
it seems temporary fix this issue, at least we didnt found geyser create so many upload traffic .
But we receive a report from data center hosting provider, they tell us my server still has outgoing attack on port 19132
we check our router and found geyser will still create connection with other server after an connection(52-length per packet)
![image](https://github.com/GeyserMC/Geyser/assets/77914339/e30cc56e-002b-4e91-b738-96f6d09cf3a8)
-------
about 26 minecraft servers(java) running on this vps, only geyser has this problem
geyser.jar was verified same as we download from geysermc
we turn off the port 19132‘s forwarding on router, and problem disappear temporary

maybe geyser can be used in UDP reflect attack?

### To Reproduce

its hard to reproduce, because i cant get what attacker send to my geyser server
but this problem really appear on my server

### Expected behaviour

try to verify IP of source UDP connection?
idn

### Screenshots / Videos

[Packet capture result.zip](https://github.com/GeyserMC/Geyser/files/14926655/Packet.capture.result.zip)
this is packet capture result

### Server Version and Plugins

in description

### Geyser Version

2.2.2-SNAPSHOT (git-master-c9ca4c8)

**Comment by Camotoy** [comment]
Please try this PR: https://github.com/GeyserMC/Geyser/pull/4554

**Comment by MossCG** [comment]
> Please try this PR: #4554

![image](https://github.com/GeyserMC/Geyser/assets/77914339/ebfef87a-b8c8-4c79-8ec1-2a80b0ac5160)
tried
still has some connection on router's backend
i have no idea if it fixed
[Test version- 1.zip](https://github.com/GeyserMC/Geyser/files/14928911/Test.version-.1.zip)

**Comment by MossCG** [comment]
> > Please try this PR: #4554
> 
> ![image](https://private-user-images.githubusercontent.com/77914339/321142646-ebfef87a-b8c8-4c79-8ec1-2a80b0ac5160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzQxMDEsIm5iZiI6MTcxMjczMzgwMSwicGF0aCI6Ii83NzkxNDMzOS8zMjExNDI2NDYtZWJmZWY4N2EtYjhjOC00Yzc5LThlYzEtMmE4MGIwYWM1MTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA3MjMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZjhlNjZlYWQ5MTg5MGQ5MDY2OWU1ZjI1MWFmNDNkNTU4Y2JmOGM0ZTIzZjE5MmRjNTNkYzFjNzc1YzA0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6c370tJ9ttbHf94RAV031HqdgbTUf_4Vlj7Brv0YYCg) tried still has some connection on router's backend i have no idea if it fixed [Test version- 1.zip](https://github.com/GeyserMC/Geyser/files/14928911/Test.version-.1.zip)

![image](https://github.com/GeyserMC/Geyser/assets/77914339/a511ff10-f7c8-4a0c-8abe-a359b3214e30)
router backend

**Comment by jhqwqmc** [comment]
#4527
Already reported and fixed
已经反馈并且修复了
As one of the first victims, I quickly realized something was wrong.
作为第一批受害者，也是很快就发现不对劲了
