### ISSUE TITLE
Enderchests are invinsible.

### ISSUE THREAD

**Issue by MrZomka** [GeyserMC/Geyser#456]
**Describe the bug**
Ender chests are for some reason invisible but they can be opened.
**To Reproduce**
Get a 1.8.8 server with ViaVersion, then place an ender chest in Java and log into the server with Bedrock.
**Expected behavior**
To see an invisible ender chest.
**Screenshots / Videos**
https://imgur.com/a/5lo1rs5
**Server Version**
Spigot 1.8.8 + ViaVersion (1.8-1.15)
**Geyser Version**
Geyser: Latest
Floodgate: Latest
**Minecraft: Bedrock Edition Version**
Latest release (1.14.60)
**Additional Context**
Java version "1.8.0_252" for (L)ubuntu

**Comment by Loganh4005** [comment]
Probably related to #225
