### ISSUE TITLE
Your server is likely unreachable from outside the network!

### ISSUE THREAD

**Issue by Wildhooray** [GeyserMC/Geyser#4563]
### Describe the bug

The bug happens when I do the command /geyser connectiontest (IP:Port)
Also bedrock players can not fined the server

```
Your server is likely unreachable from outside the network!
[15:58:42 INFO]: Got the error message: Connection timed out
[15:58:42 INFO]: If you still face issues, check the setup guide for instructions: https://wiki.geysermc.org/geyser/setup/
[15:58:42 INFO]: If that does not work, see https://wiki.geysermc.org/geyser/fixing-unable-to-connect-to-world/, or contact us on Discord: https://discord.gg/geysermc
```

### To Reproduce

1. When I do the command /geyser connectiontest (IP:Port)
2. I see the error in console

### Expected behaviour

I expect when I run the command connectiontest it will do this

geyser connectiontest (IP:Port)

```
12.04 04:46:16 [Server] ForkJoinPool.commonPool-worker-6/[INFO] Testing server connection to 91.134.127.106 with port: 25590 now. Please wait...
12.04 04:46:16 [Server] ForkJoinPool.commonPool-worker-6/[INFO] Your server is likely online and working as of now!
12.04 04:46:16 [Server] ForkJoinPool.commonPool-worker-6/[INFO] If you still face issues, check the setup guide for instructions: https://wiki.geysermc.org/geyser/setup/
12.04 04:46:16 [Server] ForkJoinPool.commonPool-worker-6/[INFO] If that does not work, see https://wiki.geysermc.org/geyser/fixing-unable-to-connect-to-world/, or contact us on Discord: https://discord.gg/geysermc
```

### Server Version and Plugins

spigot 1.20.4

Plugins (9): WorldEdit, KeepItems, Essentials, floodgate, EssentialsChat, WorldGuard, CoreProtect, WorldEditSelectionVisualizer, Geyser-Spigot

### Geyser Dump

   {     "versionInfo": {         "name": "Geyser",         "version": "2.2.3-SNAPSHOT (git-master-e856a8a)",         "javaName": "Java HotSpot(TM) 64-Bit Server VM",         "javaVendor": "Oracle Corporation",         "javaVersion": "18+36-2087",         "architecture": "x86_64",         "operatingSystem": "Mac OS X",         "operatingSystemVersion": "10.13.6",         "network": {             "dockerCheck": false,             "internalIP": "***"         },         "mcInfo": {             "bedrockVersions": [                 "1.20.40/1.20.41",                 "1.20.50/1.20.51",                 "1.20.60/1.20.62",                 "1.20.70/1.20.73"             ],             "bedrockProtocols": [                 622,                 630,                 649,                 662             ],             "defaultBedrockProtocol": 662,             "javaVersions": [                 "1.20.4"             ],             "javaProtocol": 765         }     },     "cpuCount": 8,     "cpuName": "Cannot run program \"reg\": error=2, No such file or directory",     "systemLocale": "en_AU",     "systemEncoding": "UTF-8",     "gitInfo": {         "buildNumber": "490",         "git.commit.id.abbrev": "e856a8a",         "git.commit.id": "e856a8af847051c4fb5420ebf23dcbee5b6e758c",         "git.branch": "master",         "git.remote.origin.url": "https://github.com/GeyserMC/Geyser"     },     "config": {         "autoconfiguredRemote": true,         "bedrock": {             "address": "0.0.0.0",             "port": 25565,             "broadcast-port": 25565,             "clone-remote-port": true,             "motd1": "Geyser",             "motd2": "Another Geyser server.",             "server-name": "Geyser",             "compression-level": 6,             "enable-proxy-protocol": false,             "proxy-protocol-whitelisted-ips": []         },         "remote": {             "address": "***",             "port": 25565,             "auth-type": "FLOODGATE",             "use-proxy-protocol": false,             "forward-hostname": false         },         "metrics": {             "enabled": true,             "uuid": "a52ad13a-8e89-4db0-8808-2c64957b83b8"         },         "disableCompression": true,         "saved-user-logins": [             "ThisExampleUsernameShouldBeLongEnoughToNeverBeAnXboxUsername",             "ThisOtherExampleUsernameShouldAlsoBeLongEnough"         ],         "floodgate-key-file": "key.pem",         "command-suggestions": true,         "passthrough-motd": true,         "passthrough-player-counts": true,         "legacy-ping-passthrough": false,         "ping-passthrough-interval": 3,         "forward-player-ping": false,         "max-players": 100,         "debug-mode": false,         "allow-third-party-capes": false,         "show-cooldown": "title",         "show-coordinates": true,         "disable-bedrock-scaffolding": false,         "emote-offhand-workaround": "DISABLED",         "allow-third-party-ears": false,         "default-locale": null,         "cache-images": 0,         "allow-custom-skulls": true,         "max-visible-custom-skulls": 128,         "custom-skull-render-distance": 32,         "add-non-bedrock-items": true,         "above-bedrock-nether-building": false,         "force-resource-packs": true,         "xbox-achievements-enabled": false,         "log-player-ip-addresses": true,         "notify-on-new-bedrock-update": true,         "unusable-space-block": "minecraft:barrier",         "pending-authentication-timeout": 120,         "scoreboard-packet-threshold": 20,         "enable-proxy-connections": false,         "mtu": 1400,         "use-direct-connection": true,         "disable-compression": true,         "config-version": 4     },     "floodgate": {         "gitInfo": null,         "config": null     },     "userPlatforms": {},     "hashInfo": {         "md5Hash": "5db9dd6d8e8705ce801b13b52cc7a360",         "sha256Hash": "3728f8fab88a9d41cd2486696b59bb4461be83617122fec8cdc55281144925ae"     },     "ramInfo": {         "free": 806,         "total": 2788,         "max": 4096     },     "logsInfo": null,     "bootstrapInfo": {         "platform": {             "platformName": "Spigot"         },         "platformName": "CraftBukkit",         "platformVersion": "4081-Spigot-b754dcc-e8f9149 (MC: 1.20.4)",         "platformAPIVersion": "1.20.4-R0.1-SNAPSHOT",         "onlineMode": true,         "serverIP": "",         "serverPort": 25565,         "plugins": [             {                 "enabled": true,                 "name": "WorldEdit",                 "version": "7.2.19+6642-415ef95",                 "main": "com.sk89q.worldedit.bukkit.WorldEditPlugin",                 "authors": [                     "EngineHub"                 ]             },             {                 "enabled": true,                 "name": "KeepItems",                 "version": "1.0.rc3",                 "main": "net.robinjam.bukkit.keepitems.KeepItems",                 "authors": [                     "robinjam"                 ]             },             {                 "enabled": true,                 "name": "Essentials",                 "version": "2.21.0-dev+63-52a638f",                 "main": "com.earth2me.essentials.Essentials",                 "authors": [                     "Zenexer",                     "ementalo",                     "Aelux",                     "Brettflan",                     "KimKandor",                     "snowleo",                     "ceulemans",                     "Xeology",                     "KHobbits",                     "md_5",                     "Iaccidentally",                     "drtshock",                     "vemacs",                     "SupaHam",                     "mdcfe",                     "JRoy",                     "pop4959"                 ]             },             {                 "enabled": true,                 "name": "floodgate",                 "version": "2.2.2-SNAPSHOT (b96-7f38765)",                 "main": "org.geysermc.floodgate.SpigotPlugin",                 "authors": [                     "GeyserMC"                 ]             },             {                 "enabled": true,                 "name": "EssentialsChat",                 "version": "2.21.0-dev+63-52a638f",                 "main": "com.earth2me.essentials.chat.EssentialsChat",                 "authors": [                     "Zenexer",                     "ementalo",                     "Aelux",                     "Brettflan",                     "KimKandor",                     "snowleo",                     "ceulemans",                     "Xeology",                     "KHobbits",                     "md_5",                     "Okamosy",                     "Iaccidentally",                     "mdcfe",                     "JRoy",                     "triagonal"                 ]             },             {                 "enabled": true,                 "name": "WorldGuard",                 "version": "7.0.9+5934e49",                 "main": "com.sk89q.worldguard.bukkit.WorldGuardPlugin",                 "authors": []             },             {                 "enabled": true,                 "name": "CoreProtect",                 "version": "22.2",                 "main": "net.coreprotect.CoreProtect",                 "authors": [                     "Intelli"                 ]             },             {                 "enabled": true,                 "name": "WorldEditSelectionVisualizer",                 "version": "2.1.5",                 "main": "fr.mrmicky.worldeditselectionvisualizer.WorldEditSelectionVisualizer",                 "authors": [                     "MrMicky",                     "ZathrusWriter",                     "Rojetto"                 ]             },             {                 "enabled": true,                 "name": "Geyser-Spigot",                 "version": "2.2.3-SNAPSHOT",                 "main": "org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin",                 "authors": [                     "GeyserMC"                 ]             }         ]     },     "flagsInfo": {         "flags": []     },     "extensionInfo": [] }

### Geyser Version

2.2.3-SNAPSHOT (git-master-e856a8a)

### Minecraft: Bedrock Edition Device/Version

1.20.73,pocket edition

### Additional Context

I am using my own computer to run this server.

**Comment by Redned235** [comment]
The command is behaving as expected. Something is wrong on your side, hence why the server is unreachable. Please reach out on Discord regarding this.
