### ISSUE TITLE
Bedrock players can not push minecarts

### ISSUE THREAD

**Issue by lucasfrederico** [GeyserMC/Geyser#4574]
### Describe the bug

Bedrock players can not push minecarts

### To Reproduce

1. Put an minecart on the floor.
2. Try to push the minecart.

### Expected behaviour

Make a bedrock player walk through a minecraft

### Screenshots / Videos

Java Player:
https://imgur.com/a/fObWibv

Bedrock Player:
https://imgur.com/a/jtOo7Ki

### Geyser Dump

https://dump.geysermc.org/2Ecpykj0ksWHhZVp2qjs7TiXo7B8twZ1

### Geyser Version

2.2.2-SNAPSHOT (git-master-a9467cf)

**Comment by tbyt** [comment]
Update Geyser! I cannot replicate this on the latest geyser version.
