### ISSUE TITLE
dragon breath doesn't show for bedrock users

### ISSUE THREAD

**Issue by ghost** [GeyserMC/Geyser#4578]
### Describe the bug

dragon breath doesn't show for bedrock users

### To Reproduce

spawn dragon breath

 world.spawnParticle(Particle.DRAGON_BREATH, location, 20, radius, 0, radius, radius / 100, null, true);

### Expected behaviour

should show, or at least a substitute particle if bedrock doesn't have dragon breath

### Server Version and Plugins

This server is running Paper version git-Paper-"4445d23" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4445d23)

### Geyser Version

Geyser version 2.2.3-SNAPSHOT (git-master-5151c25) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.70/1.20.73)

### Minecraft: Bedrock Edition Device/Version

1.20.51

**Comment by onebeastchris** [comment]
Might be resolved by https://github.com/GeyserMC/Geyser/commit/29a613b85c59f030bcfbaf9f1b80b1fe1a8a2aba - could you update Geyser to the latest version and re-test?

**Comment by OurLobanov** [comment]
![image](https://github.com/GeyserMC/Geyser/assets/114523572/69e8d7fd-e2cb-4d62-a57f-598d49f66511) Particles decomposition correction work not checked by world.spawnParticle(Particle.DRAGON_BREATH, location, 20, radius, 0, radius, radius/100, null, true);

**Comment by onebeastchris** [comment]
Setting particles via spigot/paper api and potions shouldn't differ much, would be surprised if that doesn't work.

Thanks for testing! Closing as resolved.
