### ISSUE TITLE
Kicks when connected

### ISSUE THREAD

**Issue by TsuckermanDev** [GeyserMC/Geyser#4591]
### Describe the bug

[20:17:21 ERROR] [geyser]: Packet violation warning sent from client! PacketViolationWarningPacket(type=MALFORMED_PACKET, severity=TERMINATING_CONNECTION, packetCauseId=40, context=BinaryStream read() incomplete
readNoHeader failed! packetId: 40)

### To Reproduce

join to the server

### Expected behaviour

normal join

### Server Version and Plugins

Velocity 3.3.0, bug on Purpur server

### Geyser Dump

https://dump.geysermc.org/JnRBw62Se8so9ip9NMHwlNpGYJxklLVH

### Geyser Version

Build #507 (Geyser Velocity)

### Minecraft: Bedrock Edition Device/Version

1.20.40-1.20.80(test on 1.20.50)

### Additional Context

There was no error before the update

**Comment by XPaladiumyX** [comment]
I agree, i have the same issue since the update!!! but on bungeecord

**Comment by Kas-tle** [comment]
Could you try with the build artifact attached here?
https://github.com/Kas-tle/Geyser/actions/runs/8805089694

**Comment by TsuckermanDev** [comment]
I'm going to try now

**Comment by TsuckermanDev** [comment]
The error has been fixed, thank you!

**Comment by XPaladiumyX** [comment]
It has been fixed i agree on **Bungeecord version.**

Thanks you,
XPaladiumyX
