### ISSUE TITLE
Abuse with the Horion mod

### ISSUE THREAD

**Issue by Press22300** [GeyserMC/Geyser#4599]
### Describe the bug

Greetings,
Some players of my server use the mod Horion to abuse, like get creative gamemode, get unlimited fly, give experience and repair their items.

Here you have the link of the mod: https://horion.download/

Could you patch these abuses to avoid cheat on BE client please ?

Thanks a lot

### To Reproduce

1 Install Horion
2 Connect on a GeyserMC server
3 Type all of your commands

### Expected behaviour

No abuse possible.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/121343872/9d84782b-f63d-40ba-8afb-08f750ce814f)
https://cdn.discordapp.com/attachments/1016396994018820266/1230595413011071016/RPReplay_Final1713466709.mov?ex=6633e449&is=66216f49&hm=cf3dd9739cf132d079f54474231fa463f20dac30dee5c77c1889e080d6749496&

### Server Version and Plugins

2.2.3-SNAPSHOT (git-master-16385a4) (velocity version)

### Geyser Version

2.2.3-SNAPSHOT (git-master-16385a4)

### Minecraft: Bedrock Edition Device/Version

Windows 10 Edition

**Comment by Kas-tle** [comment]
If a hacked client can get creative mode on your server, then that is an issue with the underlying Java server. We do not have access to server internals, meaning we do not, for example, have the ability to directly set a client's game mode. We translate packets from the Bedrock player and forward them to the Java server. As far as the Java server is concerned, a player connected to Geyser is just another Java player.
