### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by SrRelampa** [GeyserMC/Geyser#4600]
### Describe the bug

What happens is that I installed GeyserMC with the floodgate and I entered the server and I got an error

### To Reproduce

Just install the GeyserMC plugin and then log in to the server

### Expected behaviour

I was hoping you would let me play

### Screenshots / Videos

![Screenshot_20240423-211750](https://github.com/GeyserMC/Geyser/assets/138189143/9291173b-6fbe-498b-a838-34a9cabd2e37)

### Geyser Version

Geyser-Spigot v2.2.3-SNAPSHOT

**Comment by onebeastchris** [comment]
This error is usually related to using a broken ViaVersion dev build - use ViaVersion 4.9.3 and it should work

**Comment by SrRelampa** [comment]
although in fact I was using the version via version 4.10.0-24w09a-SNAPSHOT+317 I already changed to that version and everything is correct, thank you
