### ISSUE TITLE
Extreme CPU Overload due incomplete I/O operations

### ISSUE THREAD

**Issue by ByteExceptionM** [GeyserMC/Geyser#4602]
### Describe the bug

Since I update from build 478 to the latest build 512 for 1.20.80 support, I have had extreme CPU peaks. Diff:
 https://github.com/GeyserMC/Geyser/compare/b469904951bfa38ad5e950d58bb3e0dcbe2b9d73...2471de100be3f229bfa415ec887e48a29002d2b2

### To Reproduce

Update to latest build

### Expected behaviour

No CPU overload

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/47250043/21f2e47d-b284-43c6-9527-d43fa0d11edd)
![image](https://github.com/GeyserMC/Geyser/assets/47250043/cae6739e-3ba1-4c28-87f7-bd8f65af69af)
![image](https://github.com/GeyserMC/Geyser/assets/47250043/aa9aeccf-40c3-415b-bc84-d3e784771541)
![image](https://github.com/GeyserMC/Geyser/assets/47250043/812d8fc9-76b9-409d-90b4-945b3c2ced5e)

### Geyser Version

2.2.3-SNAPSHOT 2471de1

**Comment by onebeastchris** [comment]
Please send a spark report - that should show what Geyser is doing. Here's how:

Spark is a plugin that helps you monitor performance for you server.
<https://spark.lucko.me/download>

To record performance on your server use:
`/spark profiler --thread * --timeout 60`. This will run for 60 seconds then it will automatically stop.
It'll probably lag the server a good deal but it'll give us a link we might be able to process.

**Comment by ByteExceptionM** [comment]
Geyser runs standalone, cannot start a spark profiler here

**Comment by onebeastchris** [comment]
If you're able to compile it yourself, we do have a spark geyser extension that you could use: https://github.com/GeyserMC/spark
If you're not able to compile it, I could send a build of it in a few hours

**Comment by ByteExceptionM** [comment]
All right. I'll take care of it

**Comment by onebeastchris** [comment]
I'm unable to try and replicate the issue at the moment, but I will try and fix the spark extension so that could be used to get proper data to resolve this issue

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/spark/pull/1 This should resolve the issue with spark not working.
Here's a working build:
[spark-1.10.0-geyser.zip](https://github.com/GeyserMC/Geyser/files/15112013/spark-1.10.0-geyser.zip)

Does this issue occur at some specific playercount? In any case, without some concrete data on what's causing the high usage uptick it'll be difficult to guess what the issue is caused by.

**Comment by ByteExceptionM** [comment]
Sounds great. Already checked out your branch and deploying it to start a profiler.

In any case, the CPU load increases with the number of players - it doesn't go higher than 90%. The number of processes waiting for I/O doesn't change much, either. Enclosed screenshots

![image](https://github.com/GeyserMC/Geyser/assets/47250043/f33c2917-36d0-4d45-8344-578b6992bc2c)
![image](https://github.com/GeyserMC/Geyser/assets/47250043/4d035ad1-1fc2-41b7-9302-e8d7c8e5a0e7)

**Comment by Kas-tle** [comment]
At this point it would help quite a bit if you could isolate the issue to a certain commit as the range you've provided is quite a bit to go through, especially given we cannot reproduce the issue due to your complex setup.

**Comment by ByteExceptionM** [comment]
I am already debugging with Chris. It's not really possible for me to search through your code or check what the problem is. The Geyser Spark extension had some problems - which Chris has now fixed. I currently have the Geyser traffic routed to another machine so I can make the changes and debugs there. We are a network with almost 5,000 different players - unfortunately it's not that easy with restarts. As soon i get more information, ill come back. Im on it!

**Comment by ByteExceptionM** [comment]
The error has not occurred again to date. Could not trace the source of the error. If it occurs again, I'll be sure to profile it properly with the fixed spark extension. I will reopen the issue, when it occurs again - but close the issue here at this point.

**Comment by nicolube** [comment]
We're heaving the same behavior...

![grafik](https://github.com/user-attachments/assets/84f22191-fa23-49c5-b847-6c881eaa3354)

We're currently running on an Advance-3 Gen 2 from OVH.
HW Specs:

CPU
    AMD Ryzen 9 5900X - 12c/24t - 3.7 GHz/4.8 GHz 
RAM
    128 GB ECC 2666 MHz
Storage:
    2×960 GB SSD NVMe
    Soft RAID

We're running the latest geyser-version, it will get updated every day at 4am.

We're running ur geyser standalone behind an haproxy and with an resourcepack.
Everything else is basicly vanilla.

And just added geyser-spark to it.

**Comment by onebeastchris** [comment]
@nicolube please open a new issue instead of commenting here. Further, please attach further information, such as a spark profiler run and similar - server specs alone and rather vague screenshots are unfortunately not particularly helpful to debug the issue. Thanks!

**Comment by nicolube** [comment]
@onebeastchris 
Hello, I opened a new issue, and attacked a spark profile, I just did not have one with load this morning.
https://github.com/GeyserMC/Geyser/issues/5050
