### ISSUE TITLE
won't let you connect 

### ISSUE THREAD

**Issue by Mr-Saitam** [GeyserMC/Geyser#4608]
### Describe the bug

When any Bedrock user tries to enter the server, it expels them with the reason "could not connect to the world" (it only allows 1 user to enter, if more than that enters, that problem will arise)

### To Reproduce

They enter the server

### Expected behaviour

I was hoping it would let the user in.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/81599393/273ce0f4-2362-4455-a617-08a1f97ad1a0)

### Server Version and Plugins

version: supports from java 1.7 to 1.20.4 and bedrock supports 1.20.40/1.20.41
                 1.20.50/1.20.51
                 1.20.60/1.20.62
                 1.20.70/1.20.73
                 1.20.80
                 
                 
                 plugins: 
                 
                 Maintenance
                 nAntiBot
                 nuvotifier
                 SkinsRestorer
                 BungeeAliases
                 AuthMeBungee
                 AntiBungeePluginSteal
                 AdvancedServerList
                 BungeeGuard
                 FallBackServer
                 Geyser

### Geyser Dump

https://dump.geysermc.org/OkNpT8chaQJUFgGDoaik0NhPGzJJsMoz

### Geyser Version

2.2.3-SNAPSHOT (git-master-42a9ba6)

### Minecraft: Bedrock Edition Device/Version

all

### Additional Context

I am running geyser on the proxy.

**Comment by onebeastchris** [comment]
This is likely a configuration issue.
See here for help: https://wiki.geysermc.org/geyser/setup/

If you still have questions after that, please join our discord and we'll help there. Thanks!
