### ISSUE TITLE
A shulker with 'too much' NBT Data can not be placed

### ISSUE THREAD

**Issue by DarkChromaMC** [GeyserMC/Geyser#4609]
### Describe the bug

Since the most recent update, there appears to be a issue where players holding shulker boxes with a high volume of NBT data (items with various lores, enchantments, etc.) are unable to place the shulker. I've noticed this bug was reported by another user on the discord server as it seems to happen for players on Pocket Edition (from our experience)?

### To Reproduce

1. Join the server on Bedrock edition / pocket-edition
2. Fill a shulker box with items that have extensive NBT data, including multiple enchantments, lore descriptions, and other attributes.
3. Place the shulker box in the player's inventory.
4. Attempt to place the shulker box
5. Observe player is unable to place a shulker box unless they remove the number of items inside.

I've uploaded a .schematic file of the shulker box in question and a video to demonstrate.

### Expected behaviour

Players should be able to place shulker boxes filled with items, regardless of the amount of NBT data associated with the items.

### Screenshots / Videos

[bugged_shulker.schem.zip](https://github.com/GeyserMC/Geyser/files/15138151/bugged_shulker.schem.zip)
https://youtu.be/IOEX7HGHVUE

### Geyser Dump

https://dump.geysermc.org/JpIGlnozUQVJerWSk4E41R8P5SUzslfL

### Geyser Version

Geyser version 2.2.3-SNAPSHOT (git-master-c19b4ad) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.80)

**Comment by Kas-tle** [comment]
I'm confused here. You state the player is crashing, but that is not at all demonstrated in the video provided.

**Comment by AJ-Ferguson** [comment]
Here is error message
```
Failed to decode packet
org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst deserializing InventoryTransactionPacket(legacyRequestId=0, legacySlots=[], actions=[], transactionType=ITEM_USE, actionType=0, runtimeEntityId=0, blockPosition=(-196, 62, 121), blockFace=1, hotbarSlot=2, itemInHand=null, playerPosition=null, clickPosition=null, headPosition=null, usingNetIds=false, blockDefinition=null)
	at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:70) ~[bedrock-codec-ade21be.jar:?]
	...
Caused by: java.lang.IllegalStateException: Unable to read item user data
	at org.cloudburstmc.protocol.bedrock.codec.v431.BedrockCodecHelper_v431.readItem(BedrockCodecHelper_v431.java:151) ~[bedrock-codec-ade21be.jar:?]
	...
Caused by: java.io.IOException: Read size exceeded limit: read=102997, limit=102400
	at org.cloudburstmc.nbt.util.stream.LimitedDataInput.tryRead(LimitedDataInput.java:35) ~[nbt-3.0.3.Final.jar:?]
	at org.cloudburstmc.nbt.util.stream.LimitedDataInput.readUTF(LimitedDataInput.java:127) ~[nbt-3.0.3.Final.jar:?]
	at org.cloudburstmc.nbt.NBTInputStream.deserialize(NBTInputStream.java:111) ~[nbt-3.0.3.Final.jar:?]
	...
```

**Comment by DarkChromaMC** [comment]
> I'm confused here. You state the player is crashing, but that is not at all demonstrated in the video provided.

Apologies for the mixup. I've updated the bug report to reflect the actual issue (placing shulker boxes).

**Comment by Camotoy** [comment]
This is likely fixed as a result of the new update. Please let us know if that is not the case!
