### ISSUE TITLE
HUD Command for Geyser API

### ISSUE THREAD

**Issue by letsgoawaydev** [GeyserMC/Geyser#4610]
### What feature do you want to see added?

Bedrock Edition v1.20.80 added a /hud command which lets you hide different ui elements on the players screen. Obviously major things need to be done like 1.20.5 component support before any bedrock specific api is made, but it would be a nice feature to have for developers like the CameraData and fog api.
https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/hud?view=minecraft-bedrock-stable

### Are there any alternatives?

There arent any alternatives, but the player can hide their hud manually in video settings.

**Comment by onebeastchris** [comment]
Implemented & available in Geyser API version 2.3.2 onwards (https://github.com/GeyserMC/Geyser/commit/0ca42308ebfdf2c940ce714437e39e2e72bf62ae). Thanks for the suggestion!
