### ISSUE TITLE
Packets only sending to bedrock players when actioning something (moving, etc)

### ISSUE THREAD

**Issue by MiguVT** [GeyserMC/Geyser#4613]
### Describe the bug

All packets only sending when actioning something (moving, etc)
Video from one of my players: https://cdn.discordapp.com/attachments/1233898202319818882/1233944272118485083/Screenrecorder-2024-04-27-18-43-44-987.mp4?ex=662eefa8&is=662d9e28&hm=5ca469ac9ef9e312eb6100c69c3aef48cd92c19e1148fa746b5e249f6f150dbb&

### To Reproduce

1. Play a little like 2h or 3h with server on
2. Dont move or do some action, just stay afk (You will not see anything new, just stay the same image, mobs in their position freezed, 

### Expected behaviour

I wanted to play normal, no with this bug

### Screenshots / Videos

I am like this:
![image](https://github.com/GeyserMC/Geyser/assets/71216796/7027d4e2-bccc-4932-af51-6accbe856169)
I move in java and this happens:
![image](https://github.com/GeyserMC/Geyser/assets/71216796/da7fb538-8cf4-4942-9935-a06eb425a37d)
And when i move the camera or punch:
![image](https://github.com/GeyserMC/Geyser/assets/71216796/d1cb47eb-a097-49af-8e2d-87c83715c6de)

### Server Version and Plugins

Paper:
![image](https://github.com/GeyserMC/Geyser/assets/71216796/6b98ad4b-75ec-4947-8d30-e04620651f0a)
Proxy:
![image](https://github.com/GeyserMC/Geyser/assets/71216796/0a7a1924-48fb-4056-b6c0-7a4bd321eb39)

### Geyser Dump

https://dump.geysermc.org/BOGrhN2MHhE0BXMuMIohHbcV4Fac5shX

### Geyser Version

2.2.3-SNAPSHOT (git-master-42a9ba6)

### Minecraft: Bedrock Edition Device/Version

1.20.62 (All versions, android and windows tested)

**Comment by MiguVT** [comment]
tried with forward-player-ping true and false and nothing changes

**Comment by Kas-tle** [comment]
Try without protocolize and simple voice chat

**Comment by Kas-tle** [comment]
Well, ideally try with no plugins to confirm it's not a conflict.

**Comment by md5nake** [comment]
I've identified the cause of this. Starting the Spark profiler on Velocity causes this bug to occur.
You can trigger it during runtime by running `sparkv profiler start`.

**Comment by MiguVT** [comment]
> I've identified the cause of this. Starting the Spark profiler on Velocity causes this bug to occur. You can trigger it during runtime by running `sparkv profiler start`.

Tested and, yes, its the problem, tysm <3
