### ISSUE TITLE
hey guys, I need some help, I have the same problem but I don't understant how to fix it, maybe one of u can explain me how can I disable the proxy protocol in Geyser.

### ISSUE THREAD

**Issue by walflofer** [GeyserMC/Geyser#4614]
hey guys, I need some help, I have the same problem but I don't understant how to fix it, maybe one of u can explain me how can I disable the proxy protocol in Geyser.

_Originally posted by @walflofer in https://github.com/GeyserMC/Geyser/issues/2808#issuecomment-2081698567_

**Comment by Chew** [comment]
Please re-open this with a [new issue](https://github.com/GeyserMC/Geyser/issues/new?assignees=&labels=&projects=&template=bug_report.yml), or, since you need assistance, join the [GeyserMC Discord server](https://discord.gg/geysermc) and ask.
