### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Sakshyam69** [GeyserMC/Geyser#4618]
### Describe the bug

hello i need help to fix this of geyser mc plugin that phone can't play in my server while they load in the server they just get this

after server restarted they enter and can play normally but while server runs for 3 4 minutes and after 3 4 minutes of server uptime player gets this error and players who join earlier gets frezze and i can't fix this and average of half or more than half player of my server is phone player and from yesterday server is ofline beacause of this problem
you are only the hope
if you can help me please help me

### To Reproduce

just see the ss and description

### Expected behaviour

no console errors

### Screenshots / Videos

![Screenshot_20240429_191529_Minecraft](https://github.com/GeyserMC/Geyser/assets/154460230/c86bea6a-8c25-4697-938c-97d6bdef150d)

### Server Version and Plugins

paper 1.20.4

### Geyser Dump

https://dump.geysermc.org/dMO5GRwvhMeyrsmZtTAX1j4Avf4uhJo8

### Geyser Version

2.2.3-SNAPSHOT (git-master-9cb9a14)

### Minecraft: Bedrock Edition Device/Version

1.20.40 above

### Additional Context

please help me

**Comment by onebeastchris** [comment]
See #2861 for a solution for this issue - you'll want to use an updated java jdk (17.0.6 or higher, or 21)
