### ISSUE TITLE
Geyser is giving invalid data to server, causing players to lose their entire inventory

### ISSUE THREAD

**Issue by Ampersand20** [GeyserMC/Geyser#4619]
### Describe the bug

MCLogs: https://mclo.gs/80odqle

Geyser has been sending invalid data to the host server, causing a crash of the proxy which makes the connected Bedrock player lose their entire inventory. I am a Java-only player, but several Bedrock players on my server have experienced this issue. Bedrock players are more active than Java players on my server, and I'd like to find a solution if possible.

Server specs:
Host: Falixnodes (they have told me the issue is not on their end)
Version: 1.20.4 Purpur
Plugins: Geyser, Floodgate, Dynmap
RAM: 7 GB

This has occurred to two Bedrock players. As their Bedrock version automatically updates, they are playing on 1.20.80, which is a newer version than 1.20.4 Java. This caused a world corruption that made a server reset necessary, but after the server reset, two Bedrock players reported the following sequence of events:

1. They log off in a safe area (sometimes in a thick box).
2. They log on hours later and find themselves dead.
3. They respawn at their spawn bed and go back to where they died but their inventory is gone.
4. This inventory glitch applies to their ender chest inventory as well.

One player lost 3 shulker boxes worth of valuable/rare material from an expedition.

### To Reproduce

I don't believe there is a way to reproduce this. It seems like a glitch between versions but I can't fix that without losing both players.

### Expected behaviour

Obviously, nobody should be logging on with a completely wiped inventory.

### Screenshots / Videos

![Geyser1](https://github.com/GeyserMC/Geyser/assets/96956366/a16a3686-c8ec-4e20-bb8b-c278e677eca2)
![Geyser2](https://github.com/GeyserMC/Geyser/assets/96956366/088d90fc-0e56-4722-812b-211aac19bfad)
![Geyser3](https://github.com/GeyserMC/Geyser/assets/96956366/ac814548-5c4c-4ccf-8b96-d28b3fffdc8f)

### Server Version and Plugins

1.20.4 Purpur

GeyserMC
Floodgate
Dynmap

### Geyser Dump

https://dump.geysermc.org/Wx4pHIfYXhDfmVo2iH4tqmkvd7d42ffD

### Geyser Version

Latest - 9cb9a14

**Comment by Ampersand20** [comment]
Player is using a Samsung Note 9 if that helps.

**Comment by onebeastchris** [comment]
The errors you've sent in the log are irrelevant debug errors, and not related to this issue. Generally speaking, Geyser does *not* modify the inventory. As for server versions: 1.20.80 Bedrock is not "newer" than 1.20.4 Java. Geyser currently emulates a 1.20.4 java client, while supporting Bedrock client versions 1.20.40-1.20.80. Regardless of which Bedrock client version is used to connect to the server, Geyser will emulate a 1.20.4 Java client, and that's what the Java server then sees.

You should turn off the debug mode in Geysers config, and check your logs for actual errors/that crash you mentioned

**Comment by Ampersand20** [comment]
Debug is off. The websocket closing is being treated like a proxy-side crash by the server (it temporarily disconnects Geyser). While it may be emulating a 1.20.4 client, it is still a Bedrock connection. 

This still does not explain why when the update first dropped, it caused chunk version errors that prevented the server from starting. That's not the point of this bug, though.

There are no other errors associated with these events. The server host dev team has not heard of this issue before, so I was hoping this might be something that the Geyser team may have run across in the past. I guess I'll have to keep cheating him his loot again and again.

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/blob/master/core%2Fsrc%2Fmain%2Fjava%2Forg%2Fgeysermc%2Fgeyser%2Fskin%2FFloodgateSkinUploader.java
That error is related to skin uploading, nothing else. If something is crashing your server, you should check your crash logs or similar, because this certainly isn't it..

As for chunk version errors: That's entirely server-side, and could be caused by a newer world (e.g. 1.20.4) being loaded on an older server (e.g. 1.20.2). Those are not related to Geyser at all.

What would help narrow the issue down would be a full server log - the snippet you've provided aren't errors that could crash the server

**Comment by Ampersand20** [comment]
There are no other errors in the logs. The server runs perfectly fine otherwise. The logs have been overwritten by now anyway since the server is fairly busy.

**Comment by onebeastchris** [comment]
In that case, please open a new issue once you have any error in the log related to that/proper reproduction steps. Geyser does not modify Java server behavior, so this is likely an issue with a different plugin.

**Comment by t4ba** [comment]
same inv wipe issue but i only got report from java players

**Comment by Camotoy** [comment]
Try updating Spigot (or preferably use Paper).
