### ISSUE TITLE
The "." is replaced with "/" in chat

### ISSUE THREAD

**Issue by TheMasterBlaster** [GeyserMC/Geyser#462]
**Describe the bug**

When typing in chat on Bedrock, any " . " is replaced with an " / ". So typing something like "Oh..." is changed to "Oh///"

**To Reproduce**

1. Open chat

2. Type "Oh..."

3. See that it was changed to "Oh///"

**Expected behavior**

Typing " . " in a message should not have it changed to " / "

**Screenshots / Videos**

N/A

**Server Version**

PaperMC #229 

**Geyser Version**

Geyser Standalone Build #101

**Minecraft: Bedrock Edition Version**

v1.14.60

**Additional Context**

I do like the idea of the first "." being replaced with a "/" because it allows you to type in a command (that you already know) and still be able to see the chat.

**Comment by Heath123** [comment]
It seems to happen here @rtm516 
https://github.com/GeyserMC/Geyser/blob/f8c3cf1aaccf7c1419b40b067ded702ea0c4e149/connector/src/main/java/org/geysermc/connector/network/translators/bedrock/BedrockTextTranslator.java#L42

**Comment by lukeeey** [comment]
Who the hell thought that was a good idea lol

**Comment by EOT3000** [comment]
uuh

**Comment by rtm516** [comment]
> Who the hell thought that was a good idea lol

It's for commands like `/help` that bedrock overrides sometimes

**Comment by lukeeey** [comment]
Actually I just realised I have a similar issue 😂😂
