### ISSUE TITLE
hide tooltip item data component not working on geyser side

### ISSUE THREAD

**Issue by anthony114669** [GeyserMC/Geyser#4622]
### Describe the bug

hide item attributes not working on geyser side while on java are hiden correctly

### To Reproduce

hide a attribute item on java, and check on bedrock,

### Expected behaviour

reflec the hiden attributes on java items in bedrock 

### Geyser Version

2.2.3-SNAPSHOT

**Comment by onebeastchris** [comment]
does it work on the 1.20.5/.6 version (aka, now latest version) of Geyser?
1.20.5 changed item handling quite a lot, so it's possible it's also working on Geyser as well now

**Comment by anthony114669** [comment]
> does it work on the 1.20.5/.6 version (aka, now latest version) of Geyser? 1.20.5 changed item handling quite a lot, so it's possible it's also working on Geyser as well now

mmm i dunno, since im not usein minecraft 1.20.5 due plugin compatibilities, but thits problem it has been happening so long ago. i just report it rn but was happening on all versions before (since the 1.19.2) im belive

**Comment by Camotoy** [comment]
Please update to the latest Geyser version with ViaVersion, send a Geyser dump, and test if the issue is still present there. Thanks!

**Comment by anthony114669** [comment]
> Please update to the latest Geyser version with ViaVersion, send a Geyser dump, and test if the issue is still present there. Thanks!

ok for sure, i will do that for testing purpouses, in other hand i want to report other issue but i think i will create separate report, its about mobs attak animations they are not displaying it. thanks!

**Comment by Camotoy** [comment]
For mob attack animations, please verify and see if they exist on a singleplayer Bedrock world first.

**Comment by anthony114669** [comment]
> For mob attack animations, please verify and see if they exist on a singleplayer Bedrock world first.

ok i check already, and on single player the attack animatiosn works fine, its just on geyser where are not working, the mobs are like "static" when they attack, all hostile mobs

**Comment by anthony114669** [comment]
> For mob attack animations, please verify and see if they exist on a singleplayer Bedrock world first.

hi! ok im already update viaversions plugins and im on geyser plugin lastest version and the item attributtes hiding feature still not working. so i guess is a bug

**Comment by anthony114669** [comment]
> Please update to the latest Geyser version with ViaVersion, send a Geyser dump, and test if the issue is still present there. Thanks!

i did that and still not hiding the attributes on geyser side, here is the dump file:

 https://dump.geysermc.org/HhQbQvxps0qxRqlcGZgbiUHzxljEmqNg

**Comment by onebeastchris** [comment]
Unable to reproduce on a paper 1.20.6 server.

Reproduction steps i've used:
- give myself an axe with attributes, once with the hide attributes flag:

`/give @p iron_axe[attribute_modifiers={modifiers:[{type:"player.block_interaction_range",name:"player.block_interaction_range",amount:20,operation:"add_multiplied_total",uuid:[I;-1451731879,-342601818,-1938458044,532216741]},{type:"generic.armor",name:"generic.armor",amount:1,operation:"add_value",uuid:[I;2114322050,480790117,-1213153182,1728138811]}],show_in_tooltip:false}] 1`

and once without:
``/give @p iron_axe[attribute_modifiers={modifiers:[{type:"player.block_interaction_range",name:"player.block_interaction_range",amount:20,operation:"add_multiplied_total",uuid:[I;-1451731879,-342601818,-1938458044,532216741]},{type:"generic.armor",name:"generic.armor",amount:1,operation:"add_value",uuid:[I;2114322050,480790117,-1213153182,1728138811]}]}] 1`


![image](https://github.com/GeyserMC/Geyser/assets/105284508/ea288552-4069-4f1b-942e-08cac6fcd560)
![image](https://github.com/GeyserMC/Geyser/assets/105284508/1278f0e3-1ab5-43f9-9954-b825b34f5710)

Seems to work as expected for me - please provide exact replication steps for how to reproduce the issue you're facing.

**Comment by anthony114669** [comment]
> Unable to reproduce on a paper 1.20.6 server.
> 
> Reproduction steps i've used:
> 
> * give myself an axe with attributes, once with the hide attributes flag:
> 
> `/give @p iron_axe[attribute_modifiers={modifiers:[{type:"player.block_interaction_range",name:"player.block_interaction_range",amount:20,operation:"add_multiplied_total",uuid:[I;-1451731879,-342601818,-1938458044,532216741]},{type:"generic.armor",name:"generic.armor",amount:1,operation:"add_value",uuid:[I;2114322050,480790117,-1213153182,1728138811]}],show_in_tooltip:false}] 1`
> 
> and once without: `/give @p iron_axe[attribute_modifiers={modifiers:[{type:"player.block_interaction_range",name:"player.block_interaction_range",amount:20,operation:"add_multiplied_total",uuid:[I;-1451731879,-342601818,-1938458044,532216741]},{type:"generic.armor",name:"generic.armor",amount:1,operation:"add_value",uuid:[I;2114322050,480790117,-1213153182,1728138811]}]}] 1`
> 
> ![image](https://private-user-images.githubusercontent.com/105284508/328164266-ea288552-4069-4f1b-942e-08cac6fcd560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMzkwNDYsIm5iZiI6MTcxNTAzODc0NiwicGF0aCI6Ii8xMDUyODQ1MDgvMzI4MTY0MjY2LWVhMjg4NTUyLTQwNjktNGYxYi05NDJlLTA4Y2FjNmZjZDU2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQyMzM5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzVmODg4ZGUwMjNlZjUxNGY2OWJhMmJkYjc3YzllODUzMmQyM2ZiZTEyMDg4NDE0MDBiN2U4N2IwYzQ0NGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uclsNkgOXZq5TWfzEED7pEZjTw_dlpO5XC1eWpvBlnU) ![image](https://private-user-images.githubusercontent.com/105284508/328164278-1278f0e3-1ab5-43f9-9954-b825b34f5710.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMzkwNDYsIm5iZiI6MTcxNTAzODc0NiwicGF0aCI6Ii8xMDUyODQ1MDgvMzI4MTY0Mjc4LTEyNzhmMGUzLTFhYjUtNDNmOS05OTU0LWI4MjViMzRmNTcxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQyMzM5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzZlMTBlMjg3MDU2MjI4ZTYzYTQ5NTBjZjdjYzdiNGY3NDc2ZTgyNTBiZmFiYjc1YTY1MWQzODY2ODhjNzc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mNtm-imsSmzVUhT8v4oN8pGT3HvZXLzzegO6tJzGviU)
> 
> Seems to work as expected for me - please provide exact replication steps for how to reproduce the issue you're facing.

hi! thanks for checking the issue.

mmm, well actually in that pucture (the one with attributes hided already) still shows the attribute to me, so thats is has is supouse to be?

because on java the item attribute hide at all, i mean just remain the item name, but on bedrock geyser the attribute still there, let me attach some example to show you..

![Captura de pantalla 2024-05-06 184648](https://github.com/GeyserMC/Geyser/assets/60707163/6132d234-b727-461f-89fb-af3f470e141a)

![image](https://github.com/GeyserMC/Geyser/assets/60707163/97721a04-9ef7-429a-8068-d486ac44eb33)


so as you can see, the sword attributes on java are totally hide, and on bedrock does not hide at all.

**Comment by anthony114669** [comment]
i forgot to tell you the command im using

/give Lord_Anthony1 iron_sword 1 {HideFlags:10}

this is the command to hide attributes i use

**Comment by onebeastchris** [comment]
that command hides a lot more than just attributes :p
but yeah, it seems like we currently do not translate that component properly
