### ISSUE TITLE
1.20.6 Bug

### ISSUE THREAD

**Issue by jurohn** [GeyserMC/Geyser#4623]
### Describe the bug

Console error:

02.05 21:31:44 [Server] INFO [Geyser-Spigot] Started Geyser on 146.59.139.99:26023
02.05 21:31:44 [Server] INFO [Geyser-Spigot] Done (4.696s)! Run /geyser help for help!
02.05 21:31:44 [Server] WARN [io.netty.channel.ChannelInitializer] Failed to initialize a channel. Closing: org.geysermc.geyser.network.netty.ChannelWrapper@58d42ebc
02.05 21:31:44 [Server] INFO java.util.NoSuchElementException: encoder
02.05 21:31:44 [Server] INFO at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:302) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:290) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at Geyser-Spigot.jar/org.geysermc.geyser.platform.spigot.GeyserSpigotInjector$1.initChannel(GeyserSpigotInjector.java:123) ~[Geyser-Spigot.jar:?]
02.05 21:31:44 [Server] INFO at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
02.05 21:31:44 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### To Reproduce

Install paper 1.20.6
Run it with geyser and floodgate

### Expected behaviour

No errors

### Server Version and Plugins

Paper 1.20.6 Dev version 35

### Geyser Dump

https://dump.geysermc.org/oTfEjjl2LJGqQlNvDL1kz45kjnzc0z8z

### Geyser Version

Build #517 • 2-5-2024

**Comment by onebeastchris** [comment]
You're not running the latest Geyser version (would be 2.3.0). Please update.

**Comment by jurohn** [comment]
Ìm sorry. I updated yesterday for the last time.
Fixed with 2.3.0.
