### ISSUE TITLE
Custom Mappings Add Leather Recolor Option

### ISSUE THREAD

**Issue by tyepavitt** [GeyserMC/Geyser#4624]
### What feature do you want to see added?

Add option in Items Mappings for leather items to keep the leather color overlay as the custom leather color is removed for custom items currently. Then for the item texture in a resource pack you can create a tga file like the leather horse armor texture, Would be cool as is needed for the magiccosmetics plugin to allow dyable items:

![image](https://github.com/GeyserMC/Geyser/assets/35017430/6d8e202b-9d09-4d82-b860-09962a609236)

### Are there any alternatives?

Don't think so. Haven't found any

**Comment by Camotoy** [comment]
I believe due to Bedrock being Bedrock, custom colors only work with the vanilla leather items. Sorry!
