### ISSUE TITLE
Downstream packet error

### ISSUE THREAD

**Issue by daniel-skopek** [GeyserMC/Geyser#4628]
### Describe the bug

[geyser]: Downstream packet error! readerIndex(63) + length(4) exceeds writerIndex(63): PooledUnsafeDirectByteBuf(ridx: 63, widx: 63, cap: 63)

### To Reproduce

Don't know the cause

### Expected behaviour

Fix the error

### Geyser Version

Geyser version 2.3.0-SNAPSHOT (git-master-cab1a20)

**Comment by PedroMPagani** [comment]
If you don't attach logs they can't begin to start to Investivate....

**Comment by onebeastchris** [comment]
please enable `debug-mode` in Geysers config, restart the server, and send a full latest.log file via mclo.gs
