### ISSUE TITLE
Geyser Fabric geyser-fabric-2.2.3-SNAPSHOT+build.563 the floodgate prefix disappeared

### ISSUE THREAD

**Issue by eslicarrillo** [GeyserMC/Geyser#4632]
### Describe the bug

I updated from version 563 to 583 and the floodgate prefix disappeared, this caused all users to lose their data, it was necessary to downgrade to return to the previous state

### To Reproduce

Update from 563 to 583
login a bedrock user to the server.
the prefix dissapear and no data for user

### Expected behaviour

the floodgate prefix appear

### Geyser Version

Geyser Fabric geyser-fabric-2.2.3-SNAPSHOT+build.583

**Comment by onebeastchris** [comment]
Please send a full log file via mclo.gs

**Comment by onebeastchris** [comment]
Additionally, please also run `geyser dump` in the server console & send the link you get here

**Comment by onebeastchris** [comment]
Closing due to no further response.
