### ISSUE TITLE
mobs attack animations are not working/not displaying

### ISSUE THREAD

**Issue by anthony114669** [GeyserMC/Geyser#4633]
### Describe the bug

i did several test and with geyser plugin the attack animations from hostile mobs are just not working . i mean they dont display the attak animation.
i tested on bedrock single player and works but no with geyser.

### To Reproduce

just spawn an hostile mob liek a zombie and you will see is attacking without moving their hands. same with huks and other hostile mobs.

### Expected behaviour

do the attack animation as intented.

### Server Version and Plugins

pappermc 1.20.4 build 496 and via verison plugins lastest versiosn  4.10.0

### Geyser Version

Build #100 • 29/4/2024

**Comment by onebeastchris** [comment]
Closing - you already have an issue for this: https://github.com/GeyserMC/Geyser/issues/4516
