### ISSUE TITLE
lucky icon effect does not show up the icon at all.

### ISSUE THREAD

**Issue by anthony114669** [GeyserMC/Geyser#4638]
### Describe the bug

maybe is just an small bug but i want to report it, the effect works fine, but the icon wont show up as intented.

### To Reproduce

give yourself lucky effect ans see how the icon is not appearing.

### Expected behaviour

show the lucky con effect as the other ones.

### Server Version and Plugins

papermc1.20.4

### Geyser Version

Build #521 • 4/5/2024

**Comment by onebeastchris** [comment]
Unfortunately, the luck effect doesn't exist on Bedrock (same as with e.g. dolphin's grace). The player will properly have those attributes, but due to Bedrock limitations, won't see them

**Comment by anthony114669** [comment]
> Unfortunately, the luck effect doesn't exist on Bedrock (same as with e.g. dolphin's grace). The player will properly have those attributes, but due to Bedrock limitations, won't see them

oh ok that makes a lot of sense, thank you for the fast response, i will close the issue then!
