### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by xXkguyXx** [GeyserMC/Geyser#4646]
### Describe the bug

An ArrayIndexOutOfBounds occurs: https://pastebin.com/tMg64EyW

### To Reproduce

N/A

### Expected behaviour

No error

### Server Version and Plugins

Velocity 3.3.0-SNAPSHOT (git-1228f147-b389)

### Geyser Version

This server is running Geyser version 2.3.0-SNAPSHOT (git-master-8addcad) (Java: 1.20.5 - 1.20.6, Bedrock: 1.20.40/1.20.41 - 1.20.80/1.20.81)

**Comment by AJ-Ferguson** [comment]
Please try updating. This might have been fixed an hour ago

**Comment by xXkguyXx** [comment]
> Please try updating. This might have been fixed an hour ago

Just rebooted the network... unfortunate timing... :/
Will do so in a day or two.

**Comment by xXkguyXx** [comment]
Issue is gone. Thanks.
