### ISSUE TITLE
DeadChest Spawning below Y=0 in the void for Bedrock players

### ISSUE THREAD

**Issue by DrBlacktv** [GeyserMC/Geyser#4649]
### Describe the bug

I have discussed this with support on Discord and they told me to report it in GitHub to make the issue known better. So here I am. 

Initial Context: I am using a plugin called "DeadChest" which saves the player's inventory, XP, and armor on death. It gives them the exact coordinates in chat and they can even /back and teleport to its location. 

Issue: The Death Chest is spawning below Y=0 (around Y=-40) in the VOID for CONSOLE bedrock players. They can't recover their chest themselves because the game will kill them if they go below Y=0. 

My report on Discord:
For Java players, the chest will spawn at Y = 0 which is FINE. So Java players aren't the issue! 
For Bedrock players, the chest will spawn at the exact location where they died in the VOID (example: Y = -40) which is impossible to get to. The chest is not visible (probably because it is below 0 so it can't be accessed. I can still give its content back to the user with commands provided by the Deadchest Plugin as it still saves the chest).

(NOTE: I tested it out on Bedrock PC version and the Deathchest spawns at Y=0 like Java players, so this might just be for Bedrock Players on any other platform besides PC Bedrock Edition).

The guys from the Death Chest plugin said it was weird as usually, the chest spawns at Y = 0. They are going to look for fixes but in the meantime, They said this: "I don't know if the geyser reports wrong coordinates or if the Bedrock player does. But it should not attempt to create chests below 0. It can be hard to debug when I don't have bedrock". 

I have discussed with user onechris on Discord about this and he told me that it was an issue on Geyser's end. This is the link that shows why: https://github.com/GeyserMC/Geyser/blob/master/core%2Fsrc%2Fmain%2Fjava%2Forg%2Fgeysermc%2Fgeyser%2Ftranslator%2Fprotocol%2Fbedrock%2Fentity%2Fplayer%2FBedrockMovePlayerTranslator.java#L99-L111

This is what Chris said: essentially, without this, bedrock clients would survive much longer in the void.. I'll see if there's a better compromise. all I'm saying is that, theoretically, a modified Java client could also cause the same issue with dying that low.

I would like to know more about this issue and if it can be fixed, thank you. 

### To Reproduce

This is the error that it gave me whenever I reproduced the bug.

- https://mclo.gs/eptC3h4

### Expected behaviour

Chest should spawn at a reachable location by any player in any dimension. In this case, in the void, the dead-chest should spawn at Y=0.

### Screenshots / Videos

![BUGGEYSER](https://github.com/GeyserMC/Geyser/assets/169298206/80a76f62-12a2-4189-a665-4da4e9b66e14)

### Server Version and Plugins

/version: 
- This server is running Paper version git-Paper-485 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 862299b). You are 11 version(s) behind.

/plugins: 
- AuctionHouse, BetterRTP, ChatItem, ChestShop, CMILib, CoreProtect, DeadChest, DecentHolograms, DiscordSRV, EssentialsX, EssentialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, GriefPrevention, GSit, InvisibleItemFrames, Jobs, JukeBox, LuckPerms, mcMMO, NobleWhitelist, NoteBlockAPI, OpenInv, PlaceholderAPI, ProtocolLib, PvPManager, SilkSpawners, SimpleScore, SinglePlayerSleep, spark, TabList, UberEnchant, Vault, VeinMiner, Withdrawer, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/uuoWQPPg3I4j2jUFwbASMq48FFShuVHf

### Geyser Version

Geyser version 2.2.3-SNAPSHOT (git-master-9cb9a14) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.80)

### Minecraft: Bedrock Edition Device/Version

PS5, XBOX, Nintendo Switch, Mobile

### Additional Context

Everything is described in the Bug description.

**Comment by onebeastchris** [comment]
@Impactic48 that sounds like an entirely different issue - please create a new issue with complete reproduction steps.

Here, the issue is that players are dying of fall damage due to a "void floor" that exists on Bedrock edition. On Java, players are supposed to fall until they die of void damage.
