### ISSUE TITLE
Older paper server version with ViaVersion plugins not work.

### ISSUE THREAD

**Issue by N-aksif-N** [GeyserMC/Geyser#4657]
### Describe the bug

Download geysermc-spigot.jar but it didn't create files.

### To Reproduce

1. Download the paper.jar
2. Run it.
3. Download floodgate, geyser-spigot, via version, via backwards 
4. Rerun the server
5. All the plugins except for geyser-spigot create the config file

### Expected behaviour

Geyser-spigot.jar creates config.yml files

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/162333410/f9ccf94e-bf4e-496e-86cf-4e76302eb599)

### Server Version and Plugins

Server Version: 1.16.5
Java: 8
Plugins:
- Floodgate
- Geysermc
(Both was downloaded from the main geysermc page)
- Viaversion (4.10.2)
- Via Backwards (4.10.3)

### Geyser Dump

it didn't start

### Geyser Version

latest

### Minecraft: Bedrock Edition Device/Version

1.16.201

**Comment by onebeastchris** [comment]
Please share the full latest.log file via mclo.gs - it'll show why Geyser didn't start.

**Comment by N-aksif-N** [comment]
Full logs here: https://api.mclo.gs/1/raw/JeoAggD

![image](https://github.com/GeyserMC/Geyser/assets/162333410/0e40bc9c-edb4-4afd-ab3a-33ca1b147806)

**Comment by N-aksif-N** [comment]
SO, I should install the Minecraft server on the latest version, right?

**Comment by N-aksif-N** [comment]
Cuz according to this page https://wiki.geysermc.org/geyser/faq/#:~:text=What%20server%20versions%20does%20Geyser,or%20the%20standalone%20build%20instead.
It's flexible for me to set up geysermc server with the help of viaversion

**Comment by onebeastchris** [comment]
As that page said - Geyser requires Java 17 to run. This isn't your Minecraft version - those are separate.
You'd have to ask your server hosting provider if it's possible to run a 1.16.5 server with Java 17.

To find out how to change your Java version on hosts or other platforms, look at https://docs.papermc.io/java-install-update

If you’re running a version of Paper that does not support Java 17 or later, you can add the flag `-DPaper.IgnoreJavaVersion=true` to your startup Java arguments to allow Paper to run on Java 17.
