### ISSUE TITLE
Vanilla Movement broken after PR changes

### ISSUE THREAD

**Issue by Legit4K** [GeyserMC/Geyser#466]
**Describe the bug**

The teleport fix pr might have made normal movement worse. Players can no longer walk in small areas. See video [here](https://imgur.com/a/Jexjkdw)

**To Reproduce**

Watch video above

**Expected behavior**

Move correctly without teleporting

**Screenshots / Videos**

[Here](https://imgur.com/a/Jexjkdw)

**Server Version**

Paper version git-Paper-229

**Geyser Version**

Version: Geyser-Bukkit
Branch: feature/sounds
Build: 7

**Minecraft: Bedrock Edition Version**

1.14.6(0)

**Additional Context**

I believe this may be caused by the recent teleport fix PR which was merged.
It seems to have re introduced #204

**Comment by ForceUpdate1** [comment]
Please test this version if the issue still occurs.
https://github.com/GeyserMC/Geyser/pull/473
