### ISSUE TITLE
Latest release for velocity generate new error and block user to join.

### ISSUE THREAD

**Issue by HyCore** [GeyserMC/Geyser#4660]
### Describe the bug

On latest release for velocity (86dafbc) it generate a massive error and block the user from joining.
Velocity version used: latest (https://github.com/PaperMC/velocity/commit/afd8b55fb52daa36e59f10b3ceb1fa953c29c485)

https://pastebin.mozilla.org/KUrGAHnb

### To Reproduce

Use the latest geyser and velocity.
enable proxy.
try joining.

### Expected behaviour

The user should join without issue & without generating huge error log.

### Geyser Version

latest velocity 86dafbc

**Comment by HaHaWTH** [comment]
Same issue.

Velocity version: 3.3.0-SNAPSHOT build 390 (legacy mode)

Geyser version: Geyser-Velocity(git-master-[b11a6d7](https://github.com/GeyserMC/geyser/commit/b11a6d7176bb046dbc0b91a8d2faf251342978e5))

Backend server: Paper 1.20.6 build 77

Logs on backend server: https://mclo.gs/3rzPZP2

Logs on Velocity proxy: https://mclo.gs/NvGUKA1

**Not 100% reproducable, need some more tests.**

**Comment by onebeastchris** [comment]
This just shows that the Java backend server is terminating the connection - and as Geyser isn't on the backend server, but rather on the proxy, this likely is not a Geyser issue. Please check if 1.20.6 Java clients also have the same issue - to find out what's causing the issues on the backend, you should try and remove plugins temporarily until you find what makes it work.
