### ISSUE TITLE
Geyser hasn't been updated on Hangar since March 2023

### ISSUE THREAD

**Issue by letsgoawaydev** [GeyserMC/Geyser#4661]
### What feature do you want to see added?

Geyser hasn't been updated on Hangar since march 20 2023
https://hangar.papermc.io/GeyserMC

### Are there any alternatives?

Downloading from site, but I noticed it also wasn't updated on hangar so I thought I would make an issue to let you know.

**Comment by Camotoy** [comment]
The download link provided always points to the latest Geyser version. We may upload the jar directly to Hangar in the future, but we need to shrink the file size first before that's an option. Thank you for pointing this out regardless!
