### ISSUE TITLE
Warped and crimson doors not working properly

### ISSUE THREAD

**Issue by valaphee** [GeyserMC/Geyser#4664]
### Describe the bug

Warped and crimson doors don't open, and the collision model seems to be wrong, as clicking on a warped door doesn't open  the door at all. Placing warped doors places a warped door, but doesn't show up until the chunk is loaded again.

### To Reproduce

- Try to place a warped door
- Try to open/close a warped door 
- Try to strafe along a crimson door (this only occurs when the door is in the opposite state as when the chunk has loaded)

### Expected behaviour

Same behavior as with all oak type doors and iron door.

### Screenshots / Videos

https://youtu.be/gLkOHi2jTVY

### Server Version and Plugins

Geyser running on Velocity, Paper 1.20.4 with ViaVersion 4.10.2.

### Geyser Version

4d61766d0adf17849ecd66538c3889f76a763b3f

### Minecraft: Bedrock Edition Device/Version

Any

**Comment by valaphee** [comment]
Probably just an issue with the mappings even though they are auto-generated anyway.

Also tested with Java Edition 1.20.6 to rule out ViaVersion issues.

**Comment by onebeastchris** [comment]
Unable to reproduce with the latest version of Geyser & a 1.20.6 paper server - please attempt to replicate this with the official builds found on our downloads site.

**Comment by valaphee** [comment]
Not reproducible with Geyser upstream
