### ISSUE TITLE
Bedrock player  display "server positioning"

### ISSUE THREAD

**Issue by bcsm114514** [GeyserMC/Geyser#4666]
### Describe the bug

[Geyser-Spigot] Downstream packet error! readerIndex(29) + length(1) exceeds writerIndex(29): PooledUnsafeDirectByteBuf(ridx: 29, widx: 29, cap: 29)
server:1.20.4 leaves jar17
client:Bedrock 1.20.80

### To Reproduce

idk

### Expected behaviour

Entering the server

### Server Version and Plugins

1.20.4
"enabled": true,
                "name": "ViaVersion",
                "version": "4.10.0-24w05b-SNAPSHOT",
                "main": "com.viaversion.viaversion.ViaVersionPlugin",
                "authors": [
                    "_MylesC",
                    "creeper123123321",
                    "Gerrygames",
                    "kennytv",
                    "Matsv"
                ]
            },
            {
                "enabled": true,
                "name": "ProtocolLib",
                "version": "5.2.0-SNAPSHOT-679",
                "main": "com.comphenix.protocol.ProtocolLib",
                "authors": [
                    "dmulloy2",
                    "comphenix"
                ]
            },
            {
                "enabled": true,
                "name": "Orebfuscator",
                "version": "5.4.3",
                "main": "net.imprex.orebfuscator.Orebfuscator",
                "authors": [
                    "Ingrim4",
                    "NgLoader",
                    "lishid",
                    "SydMontague",
                    "ProgrammerDan",
                    "Aleksey-Terzi"
                ]
            },
            {
                "enabled": true,
                "name": "WorldEdit",
                "version": "7.2.18+6616-abda4e0",
                "main": "com.sk89q.worldedit.bukkit.WorldEditPlugin",
                "authors": [
                    "EngineHub"
                ]
            },
            {
                "enabled": true,
                "name": "Slimefun",
                "version": "2024.04-release",
                "main": "io.github.thebusybiscuit.slimefun4.implementation.Slimefun",
                "authors": [
                    "The Slimefun 4 Community"
                ]
            },
            {
                "enabled": true,
                "name": "GuizhanLibPlugin",
                "version": "Build 43 (git 26e3dd7)",
                "main": "net.guizhanss.guizhanlibplugin.GuizhanLibPlugin",
                "authors": [
                    "ybw0014"
                ]
            },
            {
                "enabled": true,
                "name": "LuckPerms",
                "version": "5.4.113",
                "main": "me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin",
                "authors": [
                    "Luck"
                ]
            },
            {
                "enabled": true,
                "name": "ElectricSpawners",
                "version": "Build 5 (git 6fa0de2)",
                "main": "io.github.thebusybiscuit.electricspawners.ElectricSpawners",
                "authors": [
                    "TheBusyBiscuit"
                ]
            },
            {
                "enabled": true,
                "name": "ExoticGarden",
                "version": "Build 17 (git 2a33c6d)",
                "main": "io.github.thebusybiscuit.exoticgarden.ExoticGarden",
                "authors": [
                    "TheBusyBiscuit"
                ]
            },
            {
                "enabled": true,
                "name": "InfinityExpansion",
                "version": "Build 14 (git 3c5db36)",
                "main": "io.github.mooy1.infinityexpansion.InfinityExpansion",
                "authors": [
                    "Mooy1"
                ]
            },
            {
                "enabled": true,
                "name": "Essentials",
                "version": "2.21.0-dev+24-0af4436",
                "main": "com.earth2me.essentials.Essentials",
                "authors": [
                    "Zenexer",
                    "ementalo",
                    "Aelux",
                    "Brettflan",
                    "KimKandor",
                    "snowleo",
                    "ceulemans",
                    "Xeology",
                    "KHobbits",
                    "md_5",
                    "Iaccidentally",
                    "drtshock",
                    "vemacs",
                    "SupaHam",
                    "mdcfe",
                    "JRoy",
                    "pop4959"
                ]
            },
            {
                "enabled": true,
                "name": "floodgate",
                "version": "2.2.2-SNAPSHOT (b96-7f38765)",
                "main": "org.geysermc.floodgate.SpigotPlugin",
                "authors": [
                    "GeyserMC"
                ]
            },
            {
                "enabled": true,
                "name": "ViaBackwards",
                "version": "4.10.0-24w05b-SNAPSHOT",
                "main": "com.viaversion.viabackwards.BukkitPlugin",
                "authors": [
                    "Matsv",
                    "kennytv",
                    "Gerrygames",
                    "creeper123123321",
                    "ForceUpdate1"
                ]
            },
            {
                "enabled": true,
                "name": "GeneticChickengineering",
                "version": "Build 8 (git a6cd374)",
                "main": "space.kiichan.geneticchickengineering.GeneticChickengineering",
                "authors": [
                    "kiichan"
                ]
            },
            {
                "enabled": false,
                "name": "FluffyMachines",
                "version": "DEV - 132 (git ccf029ba)",
                "main": "io.ncbpfluffybear.fluffymachines.FluffyMachines",
                "authors": [
                    "NCBPFluffyBear"
                ]
            },
            {
                "enabled": true,
                "name": "TranscEndence",
                "version": "DEV - 41 (git 98d7d47e)",
                "main": "me.sfiguz7.transcendence.TranscEndence",
                "authors": [
                    "sfiguz7"
                ]
            },
            {
                "enabled": true,
                "name": "ExtraHeads",
                "version": "Build 2 (git 6c77b79)",
                "main": "io.github.thebusybiscuit.extraheads.ExtraHeads",
                "authors": [
                    "TheBusyBiscuit"
                ]
            },
            {
                "enabled": true,
                "name": "GuizhanCraft",
                "version": "Build 12 (git 1ced47e)",
                "main": "net.guizhanss.guizhancraft.implementation.GuizhanCraft",
                "authors": [
                    "ybw0014"
                ]
            },
            {
                "enabled": true,
                "name": "ExtraGear",
                "version": "Build 2 zh-CN(ybw0014) (git ff13031)",
                "main": "io.github.thebusybiscuit.extragear.ExtraGear",
                "authors": [
                    "TheBusyBiscuit"
                ]
            },
            {
                "enabled": true,
                "name": "DynaTech",
                "version": "Build 74 (git 75957dd)",
                "main": "me.profelements.dynatech.DynaTech",
                "au

### Geyser Version

2.3.1-SNAPSHOT (git-master-4d61766

### Minecraft: Bedrock Edition Device/Version

1.20.80

**Comment by bcsm114514** [comment]
My English is not very good

**Comment by onebeastchris** [comment]
Update ViaVersion, you're running an older build.
