### ISSUE TITLE
java.lang.NoClassDefFoundError: io/netty/handler/codec/dns/DnsQuestion when transferring bedrock players to other servers with ServerTransferEvent listener

### ISSUE THREAD

**Issue by Eeshe** [GeyserMC/Geyser#4668]
### Describe the bug

When using a `ServerTransferEvent` listener to set the bedrock hostname and port for a `/transfer` command, a NoClassDefFoundError is thrown.

### To Reproduce

1. Implement the following event listener using the GeyserAPI.

```java
    private void registerListeners() {
      if (pluginManager.isPluginEnabled("Geyser-Spigot")) {
        GeyserApi.api().eventBus().subscribe(this, ServerTransferEvent.class, this::onGeyserTransferPacket);
      }
    }

    @Subscribe
    public void onGeyserTransferPacket(ServerTransferEvent event) {
        event.bedrockHost(event.host());
        event.bedrockPort(event.port());

        getLogger().warning("HOST: " + event.host());
        getLogger().warning("PORT: " + event.port());
        getLogger().warning("BEDROCK HOST: " + event.bedrockHost());
        getLogger().warning("BEDROCK PORT: " + event.bedrockPort());
    }
```

2. Run the `/transfer` command on a Bedrock player with the IP and port of a 2nd server with geyser installed.

### Expected behaviour

The bedrock player is successfully transferred to the 2nd server with Geyser installed.

### Screenshots / Videos

Error screen after running the command
![imagen](https://github.com/GeyserMC/Geyser/assets/75171906/d61c3702-637c-4f39-81b0-a628aea79d6d)

### Server Version and Plugins

**Spigot version**: This server is running CraftBukkit version 4165-Spigot-e2c1eee-4af0f22 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

**Plugins (4)**: floodgate, EmperixLib, Geyser-Spigot, EmperixQOL

EmperixQOL is the plugin that contains the event listener. EmperixLib is a library for the QOL plugin.

### Geyser Dump

https://dump.geysermc.org/zfo18oMqy1QR77XsBpA7sZKMJKgNHuvP

### Geyser Version

This server is running Geyser version 2.3.1-SNAPSHOT (git-master-4d61766) (Java: 1.20.5 - 1.20.6, Bedrock: 1.20.40/1.20.41 - 1.20.80/1.20.81)

### Minecraft: Bedrock Edition Device/Version

v1.20.81, Windows

### Additional Context

- Transferring a Java player doesn't cause any problems.
- The IP and port used on the `/transfer` command are the same used to connect to the 2nd server directly through the menu.

**Comment by onebeastchris** [comment]
Able to reproduce, marking as confirmed
