### ISSUE TITLE
Potion effect won't be cleared when changing server in BungeeCord

### ISSUE THREAD

**Issue by AnonAlpha** [GeyserMC/Geyser#467]
**Describe the bug**

When players get a effect in the bungeecord lobby, then goto another server, the effect won't be cleared, but players actually don't have them on.
**To Reproduce**

1. Setup geyser on bungeecord
2. Give yourself a effect in lobby
3. goto another server using `/server xxx`
4. see errors

**Expected behavior**

The effect will be cleared when changing server
**Screenshots / Videos**

**Server Version**

**Geyser Version**

latest master build

**Minecraft: Bedrock Edition Version**

latest 1.14.6
**Additional Context**

**Comment by rtm516** [comment]
This is master https://github.com/GeyserMC/Geyser/commit/b07161b0a911d6ebb91dd9d5db3522ab8048f527

**Comment by AnonAlpha** [comment]
Just tested with build 103, still happens

**Comment by HazardTheDutchAD** [comment]
![ApplicationFrameHost_SlTh0MfW1w](https://user-images.githubusercontent.com/20299632/82342432-82da5d80-99e9-11ea-8979-8d048487f33c.png)
![ApplicationFrameHost_0pvHdQGjAr](https://user-images.githubusercontent.com/20299632/82342438-85d54e00-99e9-11ea-803e-c9d10b49087a.png)

Screenshots of the issue after playing Skywars, Vampirez, and Duels on Hypixel
