### ISSUE TITLE
Geyser is unaccusable outside network (Port Forwarded java paper server)

### ISSUE THREAD

**Issue by mas6y6** [GeyserMC/Geyser#4674]
### Describe the bug

Hello Geyser support team!

I am currently experiencing an issue that is not allowing players outside my network to join

I have tried a different port about 500 of them and none work and contacted my ISP if they are blocking the port which it they are not and tried standalone and tried with no other plugins installed and opened the port with TCP and UDP and with UDP alone
and nothing works..

And also my brother in my local network is able to join but the online players that are not in my local network is not able to join

I need your help please...

### To Reproduce

Create a server spigot-paper server with geyser installed and listening to port 19132.

### Expected behaviour

For the players outside my network to join

### Server Version and Plugins

Server version: git-Paper-496

- AdvancedBan
- AuctionHouse
- BetterRTP
- ChestShop
- ChestShopTools
- Chunky
- Citizens **(Not Functional)**
- CMILib
- EssentialsX
- EssentialsChat
- Essentials Discord
- Essentials DiscordLink
- EssentialsSpawn
- floodgate
- Geyser-Spigot
- GriefPrevection
- Jobs
- LuckPerms
- Maintenance
- Mclogs
- Multiverse-Core
- Multiverse-Inventories
- Multiverse-NetherPortals
- Multiverse-Portals
- PhantomX
- PlayerReport
- ServerListPlus
- SimplePortals
- TradeSystem
- Vault
- ViaBackwards
- ViaVersion

### Geyser Dump

https://dump.geysermc.org/sqQ9AfJp8ZLEeNBbgAeJ8ZjssR1J8VKf

### Geyser Version

2.3.1-SNAPSHOT

**Comment by Camotoy** [comment]
I would try temporarily testing with the vanilla Bedrock server: https://www.minecraft.net/en-us/download/server/bedrock

That will help isolate the problem between Geyser and your setup.

**Comment by onebeastchris** [comment]
Please join our discord server for support - we'll be able to provide help there.

https://discord.com/invite/geysermc

Further, please read our documentation on our wiki:

Setup guide: https://wiki.geysermc.org/geyser/setup/
Portforwarding guide/specific notes for setups: https://wiki.geysermc.org/geyser/port-forwarding/
Unable-to-connect troubleshooting guide:
https://wiki.geysermc.org/geyser/fixing-unable-to-connect-to-world/

**Comment by mas6y6** [comment]
I had tried that
