### ISSUE TITLE
io.netty.handler.codec.haproxy.HAProxyProtocolException: header length (over 548) exceeds the allowed maximum (108)

### ISSUE THREAD

**Issue by Rejxcted** [GeyserMC/Geyser#4679]
### Describe the bug

https://pastebin.com/A6HAbUJ7

Found errors in the log!
See below for details and possible fixes
io.netty.handler.codec.haproxy.HAProxyProtocolException: header length (over 548) exceeds the allowed maximum (108)
Unknown fix!
Class: ProxyProtocolDecoder
Method: fail
Line: 419
Link: [ProxyProtocolDecoder.java#L419](https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/network/netty/proxy/ProxyProtocolDecoder.java#L419)

### To Reproduce

I started server with latest flood/geyser

### Expected behaviour

Should let me connect??

### Server Version and Plugins

Lifesteal - 1.20.4 
![image](https://github.com/GeyserMC/Geyser/assets/85765707/742548d9-a989-4f93-978d-564170797891)

Hub - 1.20.1 
![image](https://github.com/GeyserMC/Geyser/assets/85765707/39e11792-29ae-4b75-bd18-09ff0070272f)

### Geyser Dump

https://dump.geysermc.org/Omb8Qz2YYcYhYwlHAdDYXPxWKlZrSkST

### Geyser Version

534

**Comment by onebeastchris** [comment]
Are you using a reverse proxy infront of your Geyser instance? If so, which one?
This looks like a malformed packet being received; my guess would be to improper configuration

**Comment by Rejxcted** [comment]
> Are you using a reverse proxy infront of your Geyser instance? If so, which one? This looks like a malformed packet being received; my guess would be to improper configuration

Yes, we're using TCPShield, only had this problem after we updaed to the latest geyser lol

**Comment by onebeastchris** [comment]
Which version did you update from? That might be able to pin down what might have changed between now and then

**Comment by Rejxcted** [comment]
No clue but the last JAR we installed before this was 23 days ago, so I guess one on that date or the closest

**Comment by Kas-tle** [comment]
Is this running in docker or no?

**Comment by Rejxcted** [comment]
Yes, we're running our servers on Pterodactyl

**Comment by Kas-tle** [comment]
Can you run the following while reproducing the error? You can either post the resulting pcap here or if you are afraid of sharing sensitive info feel free to DM it to me on Discord (`kastle`). For the container name that should be the full uuid of the server found in the Servers tab of the Pterodactyl admin menu. 

```sh
sudo docker run --rm --net container:$(sudo docker ps -qf name=CONTAINER_NAME_HERE) nicolaka/netshoot:latest tcpdump -s 0 -U -n -w - udp port 19132 > out.pcap
```

**Comment by caseyjmorton** [comment]
What was the ultimate resolution here?  I am getting the exact same error message.
