### ISSUE TITLE
 Exception in thread "pool-34-thread-14" java.lang.IllegalArgumentException: Invalid skin length

### ISSUE THREAD

**Issue by Z3r0xh** [GeyserMC/Geyser#4691]
### Describe the bug

When bedrock users enter, some return this error. after a while it makes me expel them

### To Reproduce

Install bungeecord geyser and floodgate in their latest versions

### Expected behaviour

What was mentioned above

### Screenshots / Videos

https://mclo.gs/kPKCLwu
https://mclo.gs/HHmYAjp

### Server Version and Plugins

NullCordX » by shieldcommunity.net 3.8.6

Lobby: PandaSpigot version git-PandaSpigot-119 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (Git: 858ab0f)
Backends: Pufferfish version git-Pufferfish-49 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 852ea89 on HEAD)

### Geyser Version

This server is running Geyser version 2.3.1-SNAPSHOT (git-master-5f7a31a) (Java: 1.20.5 - 1.20.6, Bedrock: 1.20.40/1.20.41 - 1.20.80/1.20.81)

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/commit/b7931f8d704f638273bb13215df0077fd144e049 updates our Bedrock protocol library, which increased allowed skin size limits - this issue should be resolved now.
