### ISSUE TITLE
Hello, I wanted to know if you could add something to the geyser

### ISSUE THREAD

**Issue by LuizaumOFC** [GeyserMC/Geyser#4701]
### What feature do you want to see added?

I would like you to add plugin support for all versions of Minecraft, which would be very good for people who make minigame servers for the game

### Are there any alternatives?

adding support from version 1.8 and up

**Comment by onebeastchris** [comment]
https://wiki.geysermc.org/geyser/setup/

As mentioned in our setup guide & FAQ - Geyser-Spigot currently supports 1.16.5-1.20.6 natively. If you want to use versions other than that, you'll have to use ViaVersion & install Geyser on a BungeeCord/Velocity proxy - or use Geyser-standalone. Or, if you're using Viaproxy, you can install Geyser as a plugin there to then connect to any server version.
Native support for 1.8 - 1.16.5 isn't planned, nor possible as Geyser uses Java 17.
