### ISSUE TITLE
Wind charge bug

### ISSUE THREAD

**Issue by ZedaMC** [GeyserMC/Geyser#4702]
### Describe the bug

When a bedrock player uses the wind charge / or (as my friend says) breeze uses the wind charge, the terrain looks like there was a creeper explosion. However in java nothing happened and the terrain is normal.

### To Reproduce

1. Play as a bedrock player
2. Use the wind charge
--------------------------
1. Make a breeze shoot the wind charge at you

### Expected behaviour

The wind charge working normally

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/74785598/08bd4e83-352d-411f-9ab1-d53f529fcb97

### Server Version and Plugins

You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.20.6-88-980cff9 (MC: 1.20.6)

[18:59:32 INFO]:  - *AutoUpdateGeyser, CoreProtect, CurrencyPlus, floodgate, Geyser-Spigot, GSit, Lifesteal, LuckPerms, ProtocolLib, SimplePolice
[18:59:32 INFO]:  SkinsRestorer, *XP-Transfer

### Geyser Dump

https://dump.geysermc.org/oprHSQbmonzDPXJAmR7CQMUi9reId1IO

### Geyser Version

This server is running Geyser version 2.3.1-SNAPSHOT (git-master-0fcf0f9) (Java: 1.20.5 - 1.20.6, Bedrock: 1.20.40/1.20.41 - 1.20.80/1.20.81)

### Minecraft: Bedrock Edition Device/Version

Not sure i think the version is the latest. My friend is using a PS5.

**Comment by Camotoy** [comment]
This issue will be fixed when Geyser supports Java Edition 1.21.
