### ISSUE TITLE
Custom smithing ingredients don't work

### ISSUE THREAD

**Issue by animation-is-always-taken** [GeyserMC/Geyser#4706]
### Describe the bug

I added [this](https://github.com/animation-is-always-taken/the-cust-engine/blob/main/data/minecraft/recipes/buzo_helmet.json) to my server and it works perfectly fine on java, but bedrock players aren't able to place the custom ingredient on the smithing table

### To Reproduce

Add the datapack to a server running on 1.20.5/1.20.6
get a copper block, chainmail armor piece and any trim material
try using them on the smithing table
see how it doesn't work

### Expected behaviour

Custom trim to be peaceable (making the recipe craftable)

### Server Version and Plugins

Fabric 1.20.6 loader version: 0.15.11

used mods:
adventure-platform-fabric (adventure-platform-fabric) v5.13.0
AntiXray (antixray) v1.3.3
Architectury (architectury) v12.1.2
cloth-basic-math (cloth-basic-math) v0.6.1
Cloth Config v14 (cloth-config) v14.0.126
Cloud (cloud) v2.0.0-beta.6
Config to Brigadier (config2brigadier) v1.2.3
EntityCulling (entityculling) v1.6.5
Fabric API (fabric-api) v0.99.0+1.20.6 (35 child mods)
Fabric Language Kotlin (fabric-language-kotlin) v1.11.0+kotlin.2.0.0
fabric-permissions-api (fabric-permissions-api-v0) v0.3.1
Fabric TPS (fabric_tps) v1.20.4-1.4.2
Fabric Loader (fabricloader) v0.15.11
Fabric Tailor (fabrictailor) v2.4.1
FerriteCore (ferritecore) v6.1.1
Floodgate-Fabric (floodgate) v2.2.3-SNAPSHOT
Geyser-Fabric (geyser-fabric) v2.3.1-SNAPSHOT
Krypton (krypton) v0.2.7
Lithium (lithium) v0.12.3
Loom Generated (loom-generated) (65 child mods)
Minecraft (minecraft) v1.20.6
MixinExtras (mixinextras) v0.3.5
ModernFix (modernfix) v5.17.3+mc1.20.6
Mods Command (mods-command) v1.1.6
No Chat Reports (nochatreports) v1.20.6-v2.7.0
Not Enough Crashes (notenoughcrashes) v4.4.7+1.20.6
Placeholder API (placeholder-api) v2.4.0-pre.1+1.20.5
Player Data API (player-data-api) v0.4.0+1.20.3
Predicate API (predicate-api) v0.4.0+1.20.5
Styled Player List (styledplayerlist) v3.4.0+1.20.5
ThreadTweak (threadtweak) v1.20.6-0.1.3
Very Many Players (vmp) v0.2.0+beta.7.155+1.20.6
WorldEdit (worldedit) v7.3.2+6779-3aca580

### Geyser Dump

https://dump.geysermc.org/GZEtZMYxkiY6hlAAoCY4jKmYo6UrEyCO

### Geyser Version

2.3.1-SNAPSHOT (git-master-66f30a2)

### Minecraft: Bedrock Edition Device/Version

1.20.81 windows 10/1.20.81 PE

### Additional Context

This doesn't work with geyser spigot either, i'm pretty sure no custom smithing recipes work on any capacity (i could be wrong)

**Comment by onebeastchris** [comment]
This is unfortunately a can't fix as Bedrock doesn't allow adding custom trim patterns/materials as of now.

Bedrock does support adding vanilla trim patterns to custom armor, but that's unfortunately it.

**Comment by animation-is-always-taken** [comment]
are there any work arounds?

**Comment by onebeastchris** [comment]
unfortunately, there aren't

**Comment by onebeastchris** [comment]
Closing this issue in favor of it being documented on our current limitations page: https://wiki.geysermc.org/geyser/current-limitations/

**Comment by MrBsng** [comment]
> are there any work arounds?

yes, you can develop a plugin that makes bedrock players use a custom gui and container slots for the smithing table.

**Comment by JosTheDude** [comment]
For future people looking at this post, this plugin implements a fix which allows for the use of custom books & recipes in anvils for Bedrock players: https://modrinth.com/plugin/geyser-recipe-fix
