### ISSUE TITLE
Skins from bedrock players appear only as Steve and Alex skins

### ISSUE THREAD

**Issue by ioannis2008** [GeyserMC/Geyser#4708]
### Describe the bug

I’m running a paper mc(v1.20.6) online mode server with floodgate and GeyserMC installed. In the server.properties file on the server folder enforce secure profile is set to false because chat doesn’t work otherwise on bedrock, but skins are appear broken, always showing a Steve or Alex skin. Can you please help me I want to be able to chat from both bedrock and Java and have bedrock skins working as expected. Moreover, I want the server to continue to be on online mode.

### To Reproduce

Make a paper mc server with the Geyser mc and Floodgate plugins installed. On the server.properties file set enforce secure profile to false. Now connect to the server from bedrock edition client. You will be able to chat normally, but bedrock player skins default to Steve or Alex 

### Expected behaviour

I expect bedrock player skins to be working properly and still be able to chat

### Server Version and Plugins

Paper 1.20.6, plugins: Viaversion, Secure server backup, simple tpa, Floodgate, geysermc 

### Geyser Dump

https://dump.geysermc.org/xNpEQa93ICZ8iXzvJyApCff50tRJKi9g

### Geyser Version

2.3.1-SNAPSHOT (git-master-66f30a2)

### Minecraft: Bedrock Edition Device/Version

1.20.81 on iOS, Android, Xbox series s, PlayStation 5 slim and PC(running Minecraft for windows)

### Additional Context

I know that turning enforce secure profile off will fix the skin problem, but it would make bedrock edition players more manly to chat

**Comment by onebeastchris** [comment]
![Screenshot_2024-05-31-22-14-23-88_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/GeyserMC/Geyser/assets/105284508/379d2965-0aba-414e-b3bc-10aeda177fdf)

The current skin upload queue is a bit long due to an recent short outage - new skins may not be showing up properly at the moment. This should be resolved in maybe a day/two; the estimate tends to be a bit off

**Comment by ioannis2008** [comment]
Thanks a lot!!! I really appreciate the work you are doing!!!

**Comment by onebeastchris** [comment]
Issue should be resolved, the skin queue is getting shorter - it should be close to empty within a day.

**Comment by onebeastchris** [comment]
The skin queue has cleared up - closing this issue as completed.

**Comment by ioannis2008** [comment]
Good job guys
