### ISSUE TITLE
[BUG] Cannot break blocks on bedrock client

### ISSUE THREAD

**Issue by DDAN-17** [GeyserMC/Geyser#4709]
### Describe the bug

When connecting to a java server, I am not able to break blocks.

### To Reproduce

Connect to a geyser running paper server and try to break a block.

### Expected behaviour

Being able to break blocks

### Server Version and Plugins

Geyser 2.3.1-SNAPSHOT (git-master-66f30a2)
Floodgate 2.2.3-SNAPSHOT (b107-c4a4487) (branch: master)
LifeStealZ 1.1.16

### Geyser Dump

https://dump.geysermc.org/ISSfGhJqi18GfWG2AiJsBy0RbVfcAdzZ

### Geyser Version

2.3.1-SNAPSHOT (git-master-66f30a2)

### Minecraft: Bedrock Edition Device/Version

1.20.51, iPhone

**Comment by DDAN-17** [comment]
I cannot place blocks either.

**Comment by DDAN-17** [comment]
I just tried it with the newest version of bedrock, and it still didn't work.

**Comment by Camotoy** [comment]
Are you in spawn chunks? Try further out in the world?

**Comment by DDAN-17** [comment]
I was in spawn chunks, and I just tried it outside of spawn chunks and it worked.

**Comment by onebeastchris** [comment]
To disable that, set the spawn-protection-radius setting in your server.properties file to 0
