### ISSUE TITLE
CanDestroy flag on items doesn't work with Bedrock clients

### ISSUE THREAD

**Issue by Complex1t** [GeyserMC/Geyser#4710]
### Describe the bug

The CanDestroy flag on items is not respected on Bedrock clients. For example, an iron pickaxe with a CanDestroy cracked_deepslate_bricks flag should be able to destroy cracked deepslate bricks, but you cannot using a Bedrock client.

### To Reproduce

1. Set up a Paper 1.20.4-497 server.
2. Install ViaVersion 4.10.2, Geyser 546, and floodgate 107, set them up accordingly.
3. Use this command to get an iron pickaxe with a CanDestroy flag.
`/give @p iron_pickaxe{CanDestroy:["minecraft:cracked_deepslate_bricks"]} 1`
4. Place some cracked deepslate bricks and go into adventure mode.
5. Observe that you cannot break the cracked deepslate bricks with the pickaxe on a Bedrock client, but you can on a Java client (1.20.4-1.20.6) who is also in adventure mode and is also using the same pickaxe.

### Expected behaviour

The Bedrock client should be able to destroy the cracked deepslate bricks with the pickaxe.

### Server Version and Plugins

Paper 1.20.4 497
Geyser 546
floodgate 107
ViaVersion 4.10.2

### Geyser Version

This server is running Geyser version 2.3.1-SNAPSHOT (git-master-66f30a2) (Java: 1.20.5 - 1.20.6, Bedrock: 1.20.40/1.20.41 - 1.20.80/1.20.81)

### Minecraft: Bedrock Edition Device/Version

Bedrock 1.20.81 iOS

**Comment by Camotoy** [comment]
Try with this build? https://github.com/GeyserMC/Geyser/actions/runs/9312034862 it has a limited implementation of CanPlaceOn/CanDestroy flags that should be enough for 1.20.4 support.

**Comment by Complex1t** [comment]
Yes, it works with that build.

**Comment by Camotoy** [comment]
That build has been merged into master, which resolves this issue. Thank you for reporting it!
