### ISSUE TITLE
Bedrock players cannot dye wolf armor

### ISSUE THREAD

**Issue by MrFoxMC** [GeyserMC/Geyser#4712]
### Describe the bug

Normally, you are able to dye wolf armor in the crafting table menu. However, this feature is not working for my Bedrock players.

### To Reproduce

Obtain wolf armor through the creative menu on a Bedrock account.
Obtain any dye through the creative menu on the same Bedrock account.
Place both the wolf armor and the dye into the crafting grid.
The output is undyed wolf armor.

### Expected behaviour

Normally, the crafting output would be wolf armor dyed with the color of the dye you placed in the crafting grid.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/106888731/262e5fe4-3e7d-495c-b864-25abdda2ec43)

### Geyser Dump

https://dump.geysermc.org/C1V9w9JF17A82IFO9lmFOcwruozsbvFJ

### Geyser Version

2.3.1-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

Windows 10 Edition and Mobile

**Comment by Camotoy** [comment]
This is a visual issue. It will be resolved when Geyser supports Java Edition 1.21.
