### ISSUE TITLE
Incorrect world height and effects in End and Nether dimensions

### ISSUE THREAD

**Issue by UNeverUser** [GeyserMC/Geyser#4713]
### Describe the bug

I am experiencing some issues related to the height of my Minecraft world:

- In the End dimension, the world height is limited to 128 blocks, although it should be 256. Conversely, in the Nether, the height is set to 256 blocks, whereas it should be 128. (The dimensions seem to have swapped places.)
- The effects in the End dimension are replaced by the effects of the Nether and vice versa. (Screenshots 1.1)
- In the Nether, the effects are similar to those that should be in the End dimension.(Screenshots 1.2)
- Additionally, in the End world, when I attempt to pour water, it behaves as if it is in the Nether, creating the effect of evaporation.
- Bedrock players in the End dimension cannot ascend beyond a height of 128 blocks, and they cannot see blocks placed above this height(Video 1.5). Java players experience no issues in either dimension. 
We also reverted Geyser to a few previous versions, and the bug disappeared.

### To Reproduce

- Enter the End dimension and observe the world height limit.
- Enter the Nether dimension and observe the world height limit.
- Observe the environmental effects in both dimensions.
- Try to pour water in the End and note the evaporation effect.

### Expected behaviour

- The End dimension should have a height limit of 256 blocks.
- The Nether should have a height limit of 128 blocks, and Bedrock players should be able to see blocks at a height of 128 blocks.
- The environmental effects should correspond to their respective dimensions.(Screenshots 1.3/1.4)
- I think there are still many things that need to be fixed related to this bug.
### Screenshots / Videos

<details>
  <summary>Screenshots / Videos</summary>
  
  1.1  - What the End world shouldn't look like
  ![image](https://github.com/GeyserMC/Geyser/assets/159032792/fac3b04c-7985-42a0-a16f-e8cde3cc4c58)
  
  1.2  - What the Nether world shouldn't look like
  ![image](https://github.com/GeyserMC/Geyser/assets/159032792/49255b23-86d9-421d-9475-5c34e0dfb9ab)
  
  1.3  - How it should be in the End world
  ![image](https://github.com/GeyserMC/Geyser/assets/159032792/f367f91b-7a10-4294-9cee-cb47ac659759)
  
  1.4  How it should be in the Nether world
  ![image](https://github.com/GeyserMC/Geyser/assets/159032792/56b5470c-d02a-4b75-9466-c0eb0773a841)
  
  Player video:  
  1.5 
  [Video](https://github.com/GeyserMC/Geyser/assets/159032792/8b1b29df-40f0-497b-af94-e8ccba1a5163)
  
</details>

### Server Version and Plugins

The server is on version 1.17.1
The bug works the same way on an empty assembly without plugins.

### Geyser Version

2.3.1-SNAPSHOT (git-master-66f30a2)

### Minecraft: Bedrock Edition Device/Version

All

**Comment by Camotoy** [comment]
Please send a Geyser dump of the broken Geyser version and the working Geyser version. Additionally, please do ensure that Java players are not experiencing the "evaporation" bug,

**Comment by onebeastchris** [comment]
Does this also occur on a 1.20.81 client?
