### ISSUE TITLE
Read Timed Out

### ISSUE THREAD

**Issue by Clumsiifi** [GeyserMC/Geyser#4718]
### Describe the bug

I installed Velocity in front of a Fabric server. I am using Velocity's Modern mode and I cannot connect to the proxy nor the server. Bedrock gets "Locating Server..." and then after 30 seconds goes to Read Timed Out.

### To Reproduce

1. Host a Fabric server.
2. Run Velocity in front.
3. Try to connect with playit.gg or NeoProtect.
4. fails

### Expected behaviour

Player can connect to the proxy and enjoy Minecraft.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/151397240/ad4b67ee-3694-44b0-8be1-aa85b9f0c770)

### Server Version and Plugins

fabric-server-mc.1.20.6-loader.0.15.11-launcher.1.0.1
velocity-3.3.0-SNAPSHOT-396
Geyser Build #546 • 2024-05-29
Velocity Build #107 • 2024-05-27
limboreconnect, limbo api

### Geyser Dump

https://dump.geysermc.org/3JRfgUTBz0Q4FLClwgbnuVuahKuvmBhw

### Geyser Version

Geyser-Velocity -> Build #546 • 2024-05-29

### Minecraft: Bedrock Edition Device/Version

Minecraft: for iOS / Minecraft Windows 10 Edition 1.20.81

### Additional Context

Server side mods:
![image](https://github.com/GeyserMC/Geyser/assets/151397240/1a6939e6-80a1-4e6f-9168-764316499cda)

**Comment by onebeastchris** [comment]
"Read timed out" just says that the Java server/client hasn't responded in over 30 seconds, and therefore boots the client. 

Please ensure that a 1.20.6 vanilla client can join the server. If it can't, try removing floodgate-fabric & disabling send-floodgate-data temporarily (there's a known incompatibility with floodgate-fabric and fabricproxylite's hack-early-send option).

**Comment by Clumsiifi** [comment]
1.20.6 vanilla can connect, hackEarlySend is already at false and I disabled and removed floodgate from the main server. The proxy's floodgate has the option send-floodgate-data set to false and bedrock still cannot join.

**Comment by onebeastchris** [comment]
Please enable "debug-mode" in geysers config, restart, and try to connect again. Then, please send that complete log file here, for example using mc.logs

**Comment by Clumsiifi** [comment]
https://mclo.gs/VkTPBkA

**Comment by onebeastchris** [comment]
Please try without the limbo plugins on the proxy - further, please send a log from the fabric server too

**Comment by Clumsiifi** [comment]
Proxy log without limbos: mclo.gs/7AZIsgJ

Fabric server logs: mclo.gs/al0egwi

**Comment by onebeastchris** [comment]
It's odd that the Fabric backend server isn't even showing a connection attempt - I'll try to replicate the issue on a velocity/fabric setup later today, maybe I'll find out more. Generally speaking, I'd recommend trying to replicate this issue on a clean velocity+fabric setup, just to rule out configuration/plugin/mod issues

**Comment by Clumsiifi** [comment]
Oké, I'll comment if I find issues or not.

**Comment by Clumsiifi** [comment]
Got it working, but NeoProtect's ip isn't. I think k this is not the place for neoprotect support so should we close the issue? Thanks for your time by the way, you deserve one!

**Comment by onebeastchris** [comment]
What was the issue that prevented the connection? 
If a vanilla java client is able to connect, it should usually work with a Bedrock/Geyser client too.

As for NeoProtect - you'd have to ask them

**Comment by onebeastchris** [comment]
Closing since this got resolved. For further issues, please use our support channels in our discord server - thanks!
