### ISSUE TITLE
Players crash on Hypixel

### ISSUE THREAD

**Issue by DoctorMacc** [GeyserMC/Geyser#472]
**Describe the bug**
When logging into Hypixel, the Bedrock client crashes. The queue world does not crash.

**To Reproduce**
Log onto Hypixel.net during non-peak hours

**Geyser Version**
Master 104

**Minecraft: Bedrock Edition Version**
Bedrock 1.14.60

**Additional Context**
The `AvailableCommandsPacket` sent to Bedrock is what crashes the client.

**Comment by theminecoder** [comment]
Is it possible that this is a result of the client being unable to handle the amount of commands being sent in that packet? Hypixel has a ton of commands that get left in as random one off developer test commands so it can often be that 200+ commands are being sent at once when jumping around the server.
