### ISSUE TITLE
bedrocks clients crashing their game

### ISSUE THREAD

**Issue by cupboardunderscore** [GeyserMC/Geyser#4726]
### Describe the bug

the bedrock clients are crashing when playing the game (accounts are globally linked with floodgate)
this happens randomly and there is no way to fix it other than playing the java version for sometime and trying the bedrock version again

### To Reproduce

1. link accounts globally and use floodgate
2. play with a bedrock client
3. crash

### Expected behaviour

not crashing the bedrock client

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/54553422/81f6fdfa-217c-41b7-b368-8cb62af6dcd0

### Server Version and Plugins

/version gives: "You are running the latest version"
tried with no plugins but the issue still persisted

### Geyser Dump

https://dump.geysermc.org/bniRYh5Uw7gfBnk0T26O0FDmBiI9woFW

### Geyser Version

2.3.1-SNAPSHOT (git-master-9b776b5)

### Minecraft: Bedrock Edition Device/Version

1.20.72 and 1.20.80 on iOS, 1.20.81 - Windows 11

**Comment by onebeastchris** [comment]
Linking should be in no way related, as nothing changes for the Bedrock client. Please try and narrow down the replication steps - we've not seen random crashing reports thus far.

For example, please verify/answer the following:
- Does the crashing only occur with this specific world at these specific coordinates?
- Does only this device crash (indicating a possible device-specific issue), or do other clients crash as well?
- Does this occur with specific render/view distances configured?
- Do you stop crashing when your account isnt linked/when linking is disabled?
- How frequently does the crashing occur? Is it always the same location?
- Are you seeing any errors in the server console? Please send a full latest.log via mclo.gs .

Unfortunately, "happens randomly" is not something we're able to replicate on our end.

**Comment by cupboardunderscore** [comment]
1. Does the crashing only occur with this specific world at these specific coordinates?
2. Does only this device crash (indicating a possible device-specific issue), or do other clients crash as well?
3. Does this occur with specific render/view distances configured?
4. Do you stop crashing when your account isnt linked/when linking is disabled?
5. How frequently does the crashing occur? Is it always the same location?
6. Are you seeing any errors in the server console? Please send a full latest.log via mclo.gs


1. no, happens everywhere, even in other words like nether
2. happened on ipad 9, iphone 13 mini and windows 11 computer, so i don't think its a platform issue
3. i tried lowering it but that didn't help (only to 6 chunks, i can try lowering it more when it starts crashing again)
4. its random, sometimes it does not crash, but when it crashes, reconnecting does not help, it'll just crash again in a bit
5. only changed my bedrock username because it has my legal name in it https://mclo.gs/9Gs22SI


sorry i don't have more to share, i don't think i can get crash logs from ios device, but if there is a way, i'll try to get one from the windows machine when it starts again

**Comment by onebeastchris** [comment]
Closing due to no further response.
