### ISSUE TITLE
Double Chests Displayed as Single Chests Until Clicked

### ISSUE THREAD

**Issue by ByteExceptionM** [GeyserMC/Geyser#4729]
### Describe the bug

Players are reporting an issue where double chests are displayed as single chests. This problem occurs immediately upon logging in or loading the area. The chests appear as individual single chests and only display correctly as double chests after they are clicked. Upon clicking, the chest briefly opens and closes, and then it is correctly shown and usable as a double chest.

### To Reproduce

1. Log in to a server using GeyserMC.
2. Locate a double chest in the game world.
3. Observe that the double chest is displayed as two single chests.
4. Click on one of the single chests.
5. Notice that the chest opens and closes immediately, and then displays correctly as a double chest.

### Expected behaviour

Double chests should display correctly as double chests upon initial loading without requiring interaction

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/47250043/d0aa1f4d-dea9-4903-973f-b5e8aac98a60

### Server Version and Plugins

Paper-196 (1.20.1) - Waterfall 1.20-R0.3-SNAPSHOT:a65bb68:578

### Geyser Dump

Not possible due to sensitive data.

### Geyser Version

2.3.2-SNAPSHOT (git-master-18ad652)

**Comment by onebeastchris** [comment]
Please provide a geyser dump, as well as server version/plugins - those fields exist for a reason :p

**Comment by ByteExceptionM** [comment]
> Please provide a geyser dump, as well as server version/plugins - those fields exist for a reason :p

Unfortunately, providing a Geyser dump is not possible as it contains sensitive data, including plugins and IPs. We are a well-known network in Germany with a daily player base of 6,000. For security reasons, we cannot share this information publicly.

**Comment by Camotoy** [comment]
Please, at the very least, provide a Java server version to give us a quick baseline to test with. Thank you!

**Comment by onebeastchris** [comment]
Knowing that you're a "well-known German network" does not provide any info for us to reproduce issues. If you are afraid to share that information, replicate the issue with a minimum reproducible setup and share a dump, and server version/plugins from that...

**Comment by ByteExceptionM** [comment]
> Knowing that you're a "well-known German network" does not provide any info for us to reproduce issues. If you are afraid to share that information, replicate the issue with a minimum reproducible setup and share a dump, and server version/plugins from that...

This was not intended as a comment on the bug resolution process but rather an explanation of why I cannot provide a Geyser dump. As a company, we must protect sensitive information such as plugins and IPs. We are committed to providing all necessary information for debugging and are more than willing to help replicate the issue in a controlled environment if needed.

> Please, at the very least, provide a Java server version to give us a quick baseline to test with. Thank you!

Sure! We're running on Java 17 (itzg/bungeecord:java17)

**Comment by Camotoy** [comment]
I was looking for a Minecraft server version! E.G. 1.20.6 ^^

**Comment by ByteExceptionM** [comment]
> I was looking for a Minecraft server version! E.G. 1.20.6 ^^

Oh - already wrote it in the Bug Description. But sure: Paper-196 (1.20.1) - Waterfall 1.20-R0.3-SNAPSHOT:a65bb68:578
