### ISSUE TITLE
Component count in advanced tooltips is not always correct 

### ISSUE THREAD

**Issue by YHDiamond** [GeyserMC/Geyser#4732]
### Describe the bug

In Java, the advanced tooltips displays a count of the Components giving the item extra data. The Geyser implementation sometimes does not display this at all, and when it does, the count can be incorrect. 

### To Reproduce

1. Join a world on Java, enable advanced tooltips (F3 + H), generate items with custom components using commands (or even look at unmodified items, which seem to always have 6 components by default)
2. Join with Bedrock through Geyser, enable advanced tooltips (/geyser tooltips), and generate the same items 
3. Notice the discrepancy 

### Expected behaviour

The text for the components in the advanced tooltips should be the same in both Bedrock and Java.

### Screenshots / Videos

Java:
![image](https://github.com/GeyserMC/Geyser/assets/47502993/46f752bc-8af6-4fdc-bc2e-5c5207f97a73)
Bedrock: 
![image](https://github.com/GeyserMC/Geyser/assets/47502993/1a5e1ef3-fb47-4f0c-9a20-1a717d3baa70)

### Server Version and Plugins

Geyser Standalone (running on IntelliJ debugging 29dacd2)
Minecraft 1.20.6
Server is Paper 1.20.6-138-master (Implementing API version 1.20.6-R0.1-SNAPSHOT)
No plugins

### Geyser Dump

https://dump.geysermc.org/pEj7Sm3NtwdlPrlgUHNBl7jajhUVDbQy

### Geyser Version

Commit 29dacd2

**Comment by Camotoy** [comment]
Java assigns a "default" set of data components to items.
