### ISSUE TITLE
Why Bedrock can't used Anvil & Enchanted Table For Geyser Velocity In SMP Server

### ISSUE THREAD

**Issue by NyaruToru** [GeyserMC/Geyser#4734]
### Describe the bug

When the bedrock player Try to Anvil 
Bedrock Player can't pickup item like( cancel)

### To Reproduce

1.Open Anvil 
2.add enchant or repair fishing rod
3. Pickup
4. Can't pickup

### Expected behaviour

Fix Anvil & Enchanted Table

### Geyser Dump

https: //dump.geysermc.org/GWGwvRLCGm8IvC0y3D7vk0dduJ52u9w3

### Geyser Version

Geyser version 2.3.2-SNAPSHOT (git-master-b78c7b2)

### Minecraft: Bedrock Edition Device/Version

1.20.81

**Comment by onebeastchris** [comment]
Please provide a description of the issue, alongside reproduction steps. What's broken with the anvil? Combining items? What about the enchanting table, what's not working there?

Furthermore, please run `paper dumpitem` while holding the items that you are trying to combine, and send that output here. That'll give us the exact replicate of the items, allowing us to reproduce the issue.

**Comment by onebeastchris** [comment]
Closing due to no further response.
