### ISSUE TITLE
Items not distributing evenly with Left-Click in Inventories

### ISSUE THREAD

**Issue by ByteExceptionM** [GeyserMC/Geyser#4741]
### Describe the bug

Players are experiencing issues with the functionality of distributing items evenly by holding the left-click button in the crafting bench or in their ivnentory. This feature, which allows for quick and even distribution of items across the crafting grid, is either not working at all or failing to distribute the items evenly as intended.

### To Reproduce

1. Log in to a server using GeyserMC on the Bedrock Edition.
2. Open a crafting bench or the player inventory
3. Hold the left-click button while attempting to drag and distribute items evenly across the crafting grid.
4. Observe the behavior of the items being distributed.

### Expected behaviour

Holding the left-click button should allow for the even distribution of items across the inventory.

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/47250043/94b987f2-02c0-4442-be6e-a472461644a4
https://github.com/GeyserMC/Geyser/assets/47250043/5306e6f3-d8e8-42d0-a87f-a3e72dbf1074

### Server Version and Plugins

git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

Plugins:
- floodgate-spigot (Build 107 - 27.5.2024)
- ViaVersion (4.10.2)

### Geyser Dump

https://dump.geysermc.org/OkAy0dYNyg82XORgXBS2lausiCZaFIUT

### Geyser Version

2.3.2-SNAPSHOT (git-master-9db1dd1) (Java: 1.20.5 - 1.20.6, Bedrock: 1.20.80/1.20.81 - 1.21.0)

### Minecraft: Bedrock Edition Device/Version

1.20.81 Windows

**Comment by Camotoy** [comment]
Hello! Is the issue resolved if you use these builds? https://ci.viaversion.com/job/ViaVersion/

**Comment by ByteExceptionM** [comment]
> Hello! Is the issue resolved if you use these ViaVersion builds? https://ci.viaversion.com/job/ViaVersion/

Yes - the latest ViaVersion Release fixes the issue!
