### ISSUE TITLE
Could not translate packet ClientboundLevelChunkWithLightPacket

### ISSUE THREAD

**Issue by andrewkm** [GeyserMC/Geyser#4742]
### Describe the bug

https://pastebin.com/raw/4pymCATh

### To Reproduce

Paper 1.20.4 Build 497
Geyser compiled against: https://github.com/GeyserMC/Geyser/commit/db5a5289659d8b07abdcca83e5549672ddc0e272
Bungeecord compiled against: https://github.com/SpigotMC/BungeeCord/commit/8a88ce464e0b107b15523109afd7810096e635ca

### Expected behaviour

N/A

### Screenshots / Videos

N/A

### Server Version and Plugins

N/A

### Geyser Dump

https://dump.geysermc.org/6Fa1ejdxemNTnrlV20YEZjJa8L4CJvGN

### Geyser Version

2.3.2-SNAPSHOT (git-DEV-db5a528)

### Minecraft: Bedrock Edition Device/Version

N/A

### Additional Context

N/A

**Comment by onebeastchris** [comment]
The Geyser dump you've shared isn't loading. Additionally, we do not provide support for Geyser forks - please download Geyser from the official site - https://geysermc.org/download - and replicate the issue with a build from there. Thanks!

**Comment by andrewkm** [comment]
@onebeastchris same thing, I'm quite literally building the project on our Jenkins as it's better for our workflow.

**Comment by Camotoy** [comment]
Does the latest master build resolve the issue?

**Comment by andrewkm** [comment]
> Does the latest master build resolve the issue?

I've been unable to reproduce, and the players who were doing so are gone.
I will update and will monitor for issues. Will close issue for now with the assumption it's fixed, and will re-open should it be seen again.
