### ISSUE TITLE
on bedrock 1.21 but says I am on 1.20.5

### ISSUE THREAD

**Issue by scottaus** [GeyserMC/Geyser#4743]
### Describe the bug

![image](https://github.com/GeyserMC/Geyser/assets/42150960/cb3484b8-fdd0-40ae-8789-7fe556e4a147)
![image](https://github.com/GeyserMC/Geyser/assets/42150960/5d908c9f-2739-43b8-bb15-9de8655cbfe6)
Clearly I am on 1.21 but says I am on 1.20.5 and because of that wornt let me connect. 

### To Reproduce

I have the latest version of both Geyser and Floodgate. Updated 1.21 bedrock version on computer. Wornt work. 

### Expected behaviour

expected to allow em to join since I am on the correct version

### Geyser Version

1.21

### Minecraft: Bedrock Edition Device/Version

1.21

**Comment by Camotoy** [comment]
https://github.com/GeyserMC/Geyser/pull/4740 for builds that support Java Edition 1.21.
