### ISSUE TITLE
Certain 1.21 Features Not Working Correctly

### ISSUE THREAD

**Issue by HavokminReal** [GeyserMC/Geyser#4744]
### Describe the bug

Certain features in 1.21 either don't work as they should or are being translated incorrectly to Bedrock Edition. Crafters are uninteractable, and items such as Ominous Keys and Ominous Bottles are being translated as Trial Keys and Glass Bottles, respectively. Custom enchantments made via Java Edition datapacks also cause any inventory they're kept in to not load whatsoever in Bedrock Edition, though disabling the datapack and removing the enchantment fixes this issue.

### Crafters
1. Place a Crafter down
2. Try to interact with it
3. The Crafter does not open its GUI

### Ominous Bottles + Keys
1. Obtain Ominous Bottles or Ominous Keys
2. They appear as Glass Bottles or Trial Keys on Bedrock Edition

### Custom Enchantments
1. Create a custom enchantment via Java Edition datapacks
2. Enchant an item with the custom enchantment
3. The inventory containing the enchanted item does not load on Bedrock Edition
(Disabling the datapack and removing the enchantment fixes this issue)

### Expected behaviour

Crafters are interactable on Bedrock Edition, Ominous Bottles and Ominous Keys get translated as their correct items, and custom enchantments are displayed and load properly in Bedrock Edition.

### Geyser Dump

https://dump.geysermc.org/VDByfLL7hkMvzpFo2nnNnGu0IBE2oAca

### Geyser Version

Geyser version 2.4.0-SNAPSHOT (git-DEV-6a71577)

### Minecraft: Bedrock Edition Device/Version

1.21.0, Windows 11, Mobile (Android)

**Comment by HavokminReal** [comment]
After further testing it seems items that modify player attributes also give similar issues to custom enchantments on Bedrock Edition. 
To reproduce,
1. Use this command on Java Edition to give yourself an item that modifies attack damage in the mainhand: 
`give @p trident[custom_name='{"italic":false,"text":"Big Fork"}',lore=['{"text":"You should try the salmon."}','{"text":"KC:R Season 6 Launch"}'],max_damage=1,unbreakable={},enchantment_glint_override=true,attribute_modifiers=[{type:"generic.attack_damage",id:"generic.attack_damage",amount:-9,operation:"add_value",slot:"mainhand"}],item_name=c] 1`
2. Leave the item in your inventory and log out
3. Log back in on Bedrock Edition
Your inventory is not loaded on Bedrock Edition. Removing the item from your inventory will properly load your inventory when you relog.

Using a modified command that removes the attribute modifier component, we can see that the resulting item does not cause this issue:
`give @p trident[custom_name='{"italic":false,"text":"Big Fork"}',lore=['{"text":"You should try the salmon."}','{"text":"KC:R Season 6 Launch"}'],max_damage=1,unbreakable={},enchantment_glint_override=true,item_name=c] 1`

**Comment by Camotoy** [comment]
Ominous items should now appear properly in the next build.

**Comment by Camotoy** [comment]
All these issues should be resolved as of the next build. If issues persist, please make a new issue for each concern (it's easier for us to track this way). Thank you!
