### ISSUE TITLE
Bedrock players cannot trade with Priest Villagers

### ISSUE THREAD

**Issue by alexfreitas** [GeyserMC/Geyser#4747]
### Describe the bug

Console/Windows 10/Bedrock players cannot interact specifically with priest/cleric villagers. They can trade with villagers of any other profession, but when they interact with a priest/cleric villager, the trading menu does not appear and they are locked out of using any kind of interface, including their inventory until they logout 

### To Reproduce

1. Join a 1.21 Geyser server with the latest Floodgate and interact with a cleric/priest villager. Nothing will happen.
2. Attempt to open your inventory. It won't work
3. Logout and come back, your inventory will work again. 
4. Trade with a villager of any other profession, it should work normally

### Expected behaviour

Console players should  be able to trade with cleric villagers

### Geyser Dump

https://dump.geysermc.org/iG6mHERinZ37Jn1Kea43zAF05XUeGFUa

### Geyser Version

2.4.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.21.0

### Additional Context

I have the latest version of Floodgate, downloaded from the Geyser website installed. I do not have any other plugins that would affect villager trades or UI function installed.

**Comment by Camotoy** [comment]
Are there any errors in your logs?

**Comment by alexfreitas** [comment]
Unfortunately not. Nothing strange appears in the console at all. 

Additionally we've found that interacting with a farmer also causes this bug to occur, contrary to previous statements.

**Comment by alexfreitas** [comment]
Further update: butcher also does not work

**Comment by Camotoy** [comment]
Are you certain this is all villagers of that kind? Can you, more specific, show the trades the villagers have to offer? I have yet to get around to seeing this bug myself.

**Comment by alexfreitas** [comment]
Final update: Fisherman do not work. 

And do you mean the working villagers or the bugged ones? Because the bugged ones have no trades, the GUI just doesn't appear.

**Comment by onebeastchris** [comment]
This sounds similar to https://github.com/GeyserMC/Geyser/issues/4102 - is only the first trade on the list broken?

**Comment by alexfreitas** [comment]
No, you can't trade with the villagers at all, the menu doesn't open

**Comment by Camotoy** [comment]
Can you send screenshots of what their trades look like on Java?

**Comment by alexfreitas** [comment]
No, on the bugged villagers, the trade menu does not appear at all. We simply cannot trade in any capacity and then our inventories and abilities to use interfaces break after

**Comment by alexfreitas** [comment]
![clerictrades](https://github.com/GeyserMC/Geyser/assets/5935587/5636e5f8-7313-4b1f-9b50-96e783ac3d92)

Here's a cleric trade list on Java. Perfectly normal. 

On bedrock, this menu would just not appear at all.

**Comment by AJ-Ferguson** [comment]
This should be fixed in the latest build. bd30b34
