### ISSUE TITLE
Bedrock Players cannot see/place blocks on the nether roof

### ISSUE THREAD

**Issue by AvidCoder27** [GeyserMC/Geyser#4748]
### Describe the bug

It may be debatable as to whether this is a bug or not, but in Java you can build on the nether roof.
Bedrock users are unable to see portals and other blocks placed above the top layer of bedrock in the nether.
They can see entities and they can traverse the roof, but it's very difficult for them to go through portals since their client doesn't think that the blocks are there.

### To Reproduce

1. Join a geyser server on a Java client
2. Break through the bedrock on the roof of the nether
3. Place some blocks up there
4. Join the server from a bedrock client
5. Go above the nether roof and see no blocks placed up there
6. Also, attempt to place blocks above the roof and see that it is impossible

### Expected behaviour

I would expect the bedrock players to be able to interact with blocks above the nether roof, since it is a feature of java edition.

### Geyser Dump

https://dump.geysermc.org/C3OVFWkevDgyaZICA8LIHNoQEk8CmbOk

### Geyser Version

2.3.1-SNAPSHOT (git-master-688b642)

### Minecraft: Bedrock Edition Device/Version

1.20.81, Windows and Pocket Edition

**Comment by Camotoy** [comment]
See the `above-bedrock-nether-building` config option.
