### ISSUE TITLE
Unable to connect the world

### ISSUE THREAD

**Issue by D3sp1r4t** [GeyserMC/Geyser#4749]
### Describe the bug

Hi. I have server. It has plugins such as Geyser and floodgate. As I restarted server, geyser doesnt working. Bedrock players cant connect to server. Error is: Unable to connect to the world. In logs nothing.

### To Reproduce

1. Reboot of server.
 2. Connect. 
 3. Error

### Expected behaviour

I expected what geyser will work

### Server Version and Plugins

[22:52:23 INFO]: Checking version, please wait...
[22:52:24 INFO]: This server is running Paper version 1.20.6-140-ver/1.20.6@9e7f6c3 (2024-06-14T11:52:59Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-484 (MC: 1.20.4)

### Geyser Dump

https://dump.geysermc.org/0lbvparxZctkxRwyNUdUIF6gutoV9Imq

### Geyser Version

2.3.2-SNAPSHOT (git-master-4a334a2)

### Minecraft: Bedrock Edition Device/Version

1.21.0.0.3

**Comment by onebeastchris** [comment]
"Unable to connect" is usually a configuration issue. Please refer to our setup guide: https://wiki.geysermc.org/geyser/setup/

Help guides:
https://wiki.geysermc.org/geyser/common-issues/

If you need further help, please join our - discord and ask in the support channels there. Thanks!
