### ISSUE TITLE
Message Starts With "." Will be Replaced With "/"

### ISSUE THREAD

**Issue by Xuwznln** [GeyserMC/Geyser#475]
**Describe the bug**
see title.

**To Reproduce**
join a server with 1.14.60, send a message starts with . and there you go.

**Expected behavior**
send the original message instead.

**Screenshots / Videos**

**Server Version**
bungeecord

**Geyser Version**
standalone, version 108

**Minecraft: Bedrock Edition Version**
1.14.60.5

**Comment by RednedEpic** [comment]
This is intended behavior as certain commands (such as /help) are replaced by bedrock edition's version of it.
