### ISSUE TITLE
bedrock players unable to connect due to outdated client 

### ISSUE THREAD

**Issue by bajamaster13** [GeyserMC/Geyser#4750]
### Describe the bug

as stated, whenever a player attempts to connect it sends back "has disconnected from the Java server because of Outdated client! Please use 1.21". did confirm that players are using an updated version of minecraft client.

### To Reproduce

1 attempt to connect
2 wait for response 
3 get response of outdated client

### Expected behaviour

players to connect 

### Geyser Dump

 https://dump.geysermc.org/ZdAvvt8jeqgpwuf5BRbjtBzmknKjRXxH

### Geyser Version

 Geyser version 2.3.2-SNAPSHOT

**Comment by Camotoy** [comment]
https://github.com/GeyserMC/Geyser/pull/4740 use this build for now.

**Comment by bajamaster13** [comment]
worked. thanks for prompt response.
