### ISSUE TITLE
Attempting to send a message from Bedrock with secure chat enabled surfaces a dead link

### ISSUE THREAD

**Issue by korverdev** [GeyserMC/Geyser#4752]
### Describe the bug

The following link is raised to inform how to resolve the error:
https://geysermc.link/secure-chat

I believe this should actually be:
https://wiki.geysermc.org/geyser/secure-chat/

### To Reproduce

1. Send a message from Bedrock with secure chat enabled.

### Expected behaviour

Provide a working link on the error.

### Geyser Version

Build #560

**Comment by Camotoy** [comment]
The link is intentional, but we'll either fix the dead link or update it. Thanks.

**Comment by Chew** [comment]
Should be all good now, thank you for pointing it out!
