### ISSUE TITLE
Containers don't work as expected

### ISSUE THREAD

**Issue by efekurbann** [GeyserMC/Geyser#4754]
### Describe the bug

After the new geyser update, my players started to experience errors when interacting with the chest.

https://github.com/GeyserMC/Geyser/assets/58657492/975d483e-e87c-48be-b2e4-9451e995bf49

### To Reproduce

none

### Expected behaviour

Players should be able to interact with containers

### Server Version and Plugins

![image](https://github.com/GeyserMC/Geyser/assets/58657492/32429045-9389-40c7-becc-e684257d8481)
![image](https://github.com/GeyserMC/Geyser/assets/58657492/8c179e0c-69ec-47fb-868b-a7d10a23d4f4)

### Geyser Version

2.4.0-SNAPSHOT

**Comment by onebeastchris** [comment]
Please share a geyser dump, and affected java server version

**Comment by efekurbann** [comment]
https://dump.geysermc.org/92dXwgA7YKAwFuO4CCSYYBBhQ9OwZJkX

**Comment by onebeastchris** [comment]
Able to replicate on a 1.16.5 Paper server with the latest version of ViaVersion.

**Comment by Camotoy** [comment]
This should be fixed after https://github.com/ViaVersion/ViaVersion/pull/3949 is merged.

**Comment by onebeastchris** [comment]
It was just merged - closing as completed. You'll need to update ViaVersion (probably use their dev builds) to resolve this.
