### ISSUE TITLE
Improve the "supported versions" section on the README to be reliably linkable

### ISSUE THREAD

**Issue by explor4268** [GeyserMC/Geyser#4773]
### What feature do you want to see added?

Sometimes players is asking for "what Minecraft Bedrock versions is supported on your server?"

As the currently supported versions updates overtime, we would like to directly link to the Geyser's README for a reference of supported Minecraft Bedrock versions to join (using Markdown links). Everytime the supported versions updates, the link will also changes, thus all previous link no longer jumps directly into the supported versions section on the README.

As of **editing** this issue, the link https://github.com/GeyserMC/Geyser#currently-supporting-minecraft-bedrock-12080---1212-and-minecraft-java-121 is working correctly.

However, links like https://github.com/GeyserMC/Geyser#currently-supporting-minecraft-bedrock-12080---1210-and-minecraft-java-121 no longer works because the text changes. (though linking to specific commits like https://github.com/GeyserMC/Geyser/tree/fc529a661cc85655ef95e72cc96caa20d5f08218#currently-supporting-minecraft-bedrock-12080---1210-and-minecraft-java-121 still works, but it's useless anyway since we wanted the latest one)

So, instead of:

> ## Currently supporting Minecraft Bedrock 1.20.80 - 1.21.2 and Minecraft Java 1.21

**Make it into a dedicated section instead:**

## Supported Versions

Geyser is currently supporting Minecraft Bedrock **1.20.80 - 1.21.2** and Minecraft Java Server 1.21 (on the FAQ Geyser supports Java servers above 1.16.5 if i'm not wrong)

We do not support older version because most of Minecraft Bedrock clients are automatically updated. Please update to the recent version if your Minecraft version is no longer supported by Geyser. (insert another reasons or issuecomment links here)

(or make it a totally seperate Markdown file)
So the heading never changes and the links will be kept static.

### Are there any alternatives?

- **Use https://geysermc.org/wiki/geyser/supported-versions instead of the README**. https://github.com/GeyserMC/Geyser/issues/4773#issuecomment-2241828577
- Just write down "latest Minecraft Bedrock version" (but if Geyser is not updated yet this will no longer be true)
- Changing the link everytime the supported versions updates (tedious)
- Using text fragments, which only some recent browsers (notably Chromium-based ones) works: https://github.com/GeyserMC/Geyser#:~:text=Currently%20supporting (I'm using Firefox-based ones, which doesn't work)
- ~~Using https://wiki.geysermc.org/geyser/ (https://github.com/GeyserMC/Geyser/issues/4773#issuecomment-2180356276) seems like a good solution.~~

Other than that, are there any other alternatives?

**Comment by onebeastchris** [comment]
You could link players to the site on our wiki that shows the supported Bedrock versions: https://wiki.geysermc.org/geyser/
However, updating the readme seems like a reasonable option too; so i'll leave this feature request open

**Comment by explor4268** [comment]
Oh, I didn't even notice notice that wiki page existed, but thanks for pointing out anyway.

**Comment by Camotoy** [comment]
Would you be interested if we had an API endpoint for querying the latest versions?

**Comment by explor4268** [comment]
No, but that's a great addition.

**Comment by onebeastchris** [comment]
https://geysermc.org/wiki/geyser/supported-versions
We've now included a dedicated page to which versions Geyser supports on our new wiki :)
Leaving this open as i think there's still a need to give the readme a refresher.
