### ISSUE TITLE
False colour on the Notice Board

### ISSUE THREAD

**Issue by superwfox** [GeyserMC/Geyser#4774]
### Describe the bug

When using the bedrock version and writing color text on the NoticeBoard, the text cannot display color correctly.

•EG：
   input：§eThis is a message
    output：This is a message

it just the default message not cover the color.
![IMG_3532](https://github.com/GeyserMC/Geyser/assets/65709399/bd280fa7-0280-47bb-9d69-95911cbb1b9f)

### To Reproduce

input：§eThis is a message
    output：This is a message

### Expected behaviour

demonstrate the right text with wonderful color！

### Screenshots / Videos

![IMG_3532](https://github.com/GeyserMC/Geyser/assets/65709399/69a9cb42-4f07-456a-891a-bae304c1e0b2)

### Server Version and Plugins

1.20.6 PurPur
latest geyser

### Geyser Version

latest

**Comment by onebeastchris** [comment]
When you're talking about "named boards", are you talking about signs?

**Comment by superwfox** [comment]
Yes！Sorry for my Unauthentic expression

**Comment by Camotoy** [comment]
Hello! Can you send an image of what this looks like on Java? Thank you!!

**Comment by superwfox** [comment]
sorry i have no pc yet.Do you mean that you can't reproduce this situation?
emm，i will call my friend to have a try

**Comment by superwfox** [comment]
> When you're talking about "notice boards", are you talking about signs?

OMG,i found the “§” not work in java edition so it leads to false color
So i changed my idea:Can geyser support “§”?

**Comment by onebeastchris** [comment]
This isn't something we intend to support. As we emulate a Java client, you would have to use Java color codes to display colors on signs.

**Comment by superwfox** [comment]
Yes id tried Java color codes but it doesn't work either on java or be.SignEdit did solve my problem.
But I want to ask if Geyser can automatically convert the color code when I display this kind of color text to the bedrock version of players.

**Comment by valaphee** [comment]
In Java you can't use §, in Bedrock you can, but Geyser strips it out, as otherwise a Java server would just kick you.

Theoretically the logic could be changed so that § is converted to &, and a plugin like SignEdit then can convert & back to §, but this is not gonna happen. (but can be easily done in a fork https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/translator/text/MessageTranslator.java#L292)
