### ISSUE TITLE
Minecraft skin appears as steve 

### ISSUE THREAD

**Issue by SpringPea** [GeyserMC/Geyser#4775]
### Describe the bug

For some reason, my minecraft skin from thr minecraft marketplace appears as Steve from my perspective,  other players can see the custom skin from their side but from my side it appears  as steve. I asked thr dev about it and he said he can't do anything about it. And it's a bug from Geyser itself

### To Reproduce

1. Select a custom minecraft skin or a skin from mc marketplace 
2. Enter the server ip address and then join game
3. Wait for game to load finish. Once finished, open up inventory and thr skin appears as steve instead of the custom minecraft skin

### Expected behaviour

Thr skin should instead shows the custom minecraft skin

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/173324550/a89f65f8-38f9-4437-87f3-4ec33f258e26

### Server Version and Plugins

1.17 to 1.21.

Plugins 

 treecapitator, shop plugin, auction house, chestshop, advanced enchantments , single player sleep, fly, sellgui, sell hand,  player vault,  server voting

### Geyser Version

Latest version

### Minecraft: Bedrock Edition Device/Version

1.21.0.03, android

**Comment by onebeastchris** [comment]
Hey, thanks for reporting the issue - it's already being tracked on the Floodgate repo here: https://github.com/GeyserMC/Floodgate/issues/519, so I'll close this one. Thanks anyways!
