### ISSUE TITLE
 Geyser Fabric with Floodgate and MCXboxBroadcast Extension hangs server shutdown 

### ISSUE THREAD

**Issue by Practor009** [GeyserMC/Geyser#4778]
### Describe the bug

Setup is a raspberry PI running Debian GNU/Linux 12 (bookworm), installed openjdk version "21.0.3" 2024-04-16 LTS, and geyser dump as shown below

[https://dump.geysermc.org/DYzhC2DoOSdIVashEGK2r2bed8IDmfUB](url)

Installing the MCXboxBroadcast extension for Geyser Fabric causes the server shutdown to hang (see attached images)

The issue presents itself when loading the Geyser extension. Removing the extension results in a successful server shutdown which led me to believe the extension itself was the source of the issue.
However, after some troubleshooting from the MCXboxBroadcast extension creator in this thread: [https://github.com/rtm516/MCXboxBroadcast/issues/81](url)
It was identified that the issue most likely originates from Geyser itself.

Additionally running Geyser in debug mode for logging produces the following console log, indicating that even though Geyser states to have disabled the extension on server stop, the extension is still running and preventing server shutdown. (see attached image)
![image](https://github.com/GeyserMC/Geyser/assets/163452913/170aabaf-2ca6-4521-9dea-f557c152bddd)

Having the server shut down successfully is essential as it is managed through  systemd and this behaviour will break all my scripts.

### To Reproduce

1. Create a Geyser Fabric java server version 1.21 with floodgate authentication.
2. Install MCXboxBroadcast extension.
3. Start the server.
4. Use the "stop" command to shutdown server.
5. Server hangs.
![image](https://github.com/GeyserMC/Geyser/assets/163452913/bce542a4-9af5-470c-bc98-1e23ed98f0d0)

### Expected behaviour

When "stop" command is issued in console, server shuts down completely.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/163452913/d4e30876-ee19-4496-bd57-3dfcec9e904b)

### Fabric server with following latest release mods:

1. fabric-api-0.100.1+1.21.jar 
2. ViaFabric-0.4.14+73-main.jar
3. ViaBackwards-5.0.0.jar
4. ViaRewind-4.0.0.jar
5.  viewdistancefix-fabric-1.21-1.0.2.jar
6. spark-1.10.73-fabric.jar 
7. lithium-fabric-mc1.21-0.12.5.jar
8. Geyser-Fabric.jar
9. Floodgate-Fabric-2.2.3-SNAPSHOT+build.28.jar

### Geyser Dump

https://dump.geysermc.org/DYzhC2DoOSdIVashEGK2r2bed8IDmfUB

### Geyser Version

2.4.0-SNAPSHOT (git-master-2e6cf2f)

### Minecraft: Bedrock Edition Device/Version

1.20.80/1.20.81

**Comment by onebeastchris** [comment]
Update the extension, that was recently fixed. For the future, please open issues relating to third-party software on their respective repo (https://github.com/rtm516/MCXboxBroadcast). Thanks!

**Comment by Practor009** [comment]
Please review again! In my post I am explaining that the issue was opened to the  third-party software repo, but was identified to be an issue of Geyser itself. The third-party software creator attempted to solve the issue, but later admitted to be unable to stop the server hanging issue with or without his software installed. See relevant raised issue here: 
[https://github.com/rtm516/MCXboxBroadcast/issues/81](url)

**Comment by onebeastchris** [comment]
Does this issue occur without the MCXboxBroadcast extension installed?

**Comment by Practor009** [comment]
Yes, as shown in the first log screenshot provided.

**Comment by onebeastchris** [comment]
That would again indicate that it's an extension issue, not a Geyser one. Please open a new issue on their repo.
I'd recommend to also attach a thread dump in that new issue there, as that would show which thread is running/not shut down. See https://www.baeldung.com/java-thread-dump for how to create that.

**Comment by Practor009** [comment]
Will do! Thank you so much for the tip and your quick response.
