### ISSUE TITLE
Trial chamber map invisible to bedrock players

### ISSUE THREAD

**Issue by shantek** [GeyserMC/Geyser#4781]
### Describe the bug

When you have a new trial chamber map in your hands, it's invisible for bedrock players as if they're holding nothing.

### To Reproduce

1. Trade for a trial chamber map or be given one by a Java player
2. Map is invisible in the players hands

### Expected behaviour

Map should be visible 

### Geyser Dump

https://dump.geysermc.org/8IdeW4KlK9MY1hbe1hvTUQoQtuqwaps0

### Geyser Version

Geyser version 2.4.0-SNAPSHOT (git-master-dd9d5f3)

### Minecraft: Bedrock Edition Device/Version

Xbox Series X

**Comment by basaigh** [comment]
Hi, thanks for the bug report, this should be resolved in the latest build. Feel free to reopen this issue if the behaviour continues.
