### ISSUE TITLE
[Velocity] Tab Complete throws warning messages on console

### ISSUE THREAD

**Issue by davidgb8246** [GeyserMC/Geyser#4786]
### Describe the bug

The bug consists of just typing geyser related commands inside the game. By doing that, in the proxy console, there will be a message saying "Missing locale: en_CA" even if you are running another locale or just the default configuration.

### To Reproduce

1. Download Velocity 3.3.0-SNAPSHOT (git-9d25d309-b400)
2. Download Geyser 2.4.0-SNAPSHOT (git-master-e6bf3ff)
3. Start Velocity with Geyser on the plugins folder.
4. Join the server.
5. Type any geyser command
6. Done

### Expected behaviour

Hide that warning message.

### Screenshots / Videos

https://youtu.be/talB4poFFSg

### Server Version and Plugins

Proxy:
Geyser 2.4.0-SNAPSHOT (git-master-e6bf3ff)
Floodgate 2.2.3-SNAPSHOT (b109-49bd564) (branch: master)
![image](https://github.com/GeyserMC/Geyser/assets/85250523/e5f6ade7-61ff-4002-b7d6-cae0f0474e36)

Backend Server:
Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z)
![image](https://github.com/GeyserMC/Geyser/assets/85250523/36802816-2306-4eef-8b48-a29489bec604)

### Geyser Dump

https://dump.geysermc.org/P5hLhUX8YD4VvhWHvpJ5ITmVMeD0uvxz

### Geyser Version

Geyser 2.4.0-SNAPSHOT (git-master-e6bf3ff)

### Minecraft: Bedrock Edition Device/Version

Java 1.20.1 Fabric

**Comment by onebeastchris** [comment]
Should be resolved with https://github.com/GeyserMC/Geyser/pull/4940 - those messages are now logged only in debug mode.
