### ISSUE TITLE
Falling in void then teleporting still applies fall damage

### ISSUE THREAD

**Issue by Josh65-2201** [GeyserMC/Geyser#4787]
### Describe the bug

It seems when falling then getting teleported the fall damage still applied (same if I hit a block while falling without teleporting)
This doesn't happen in Java

### To Reproduce

1. I'm using a plugin to disable void damage and teleport to spawn
2. Install Denizen https://ci.citizensnpcs.co/job/Denizen_Developmental/7044/
3. Add [void.txt](https://github.com/user-attachments/files/15937956/void.txt) to `Denizen\scripts`
4. Rename extension `txt` to `dsc` (GitHub file type limitations)
5. Start server
6. fall into void

### Expected behaviour

Fall damage/velocity should be canceled when teleporting happens

### Server Version and Plugins

Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT). You are running the latest version

### Geyser Dump

https://dump.geysermc.org/nH4avmlreSu1CR6Aw5MQpXz3O8DXpvA3

### Geyser Version

2.4.0-SNAPSHOT (git-master-e6bf3ff)

### Minecraft: Bedrock Edition Device/Version

Windows 1.21.1

**Comment by onebeastchris** [comment]
Hey! Thanks for creating an issue.
I'm not able to reproduce this on my end, but i have an idea of what might be going on.
Could you test the build found here (https://github.com/onebeastchris/Geyser/actions/runs/9627657694) and see if the issue still occurs with those?

**Comment by Josh65-2201** [comment]
Tried the linked build, didn't change anything

**Comment by onebeastchris** [comment]
Can you send a video demonstrating the behavior on a Java client vs Bedrock? I think i may be misunderstanding what the specific issue here is.

**Comment by Josh65-2201** [comment]
The file too big for GitHub so it here https://1drv.ms/v/s!AhxyZFeyfhCxgphyO1xGI6adJrywrA?e=dGWI3j

**Comment by Josh65-2201** [comment]
Watching the video back I realized I was in creative. It is happening on java too. Thanks
