### ISSUE TITLE
Bedrock players cannot load or place blocks above height 128 in the Nether

### ISSUE THREAD

**Issue by royosub** [GeyserMC/Geyser#4788]
### Describe the bug

Due to the inherent rules of the Bedrock edition, Bedrock players cannot load or place blocks above height 128 in the Nether

### To Reproduce

1.A Nether transportation system was built above the top bedrock layer in the Nether
2.Bedrock players cannot use

### Expected behaviour

Circumventing this limitation by altering the Nether coordinates

### Geyser Version

55e90b6

### Minecraft: Bedrock Edition Device/Version

Release 1.21.0 windows

**Comment by Camotoy** [comment]
Enable the Nether height workaround in the Geyser config.
