### ISSUE TITLE
Java custom enchantment support

### ISSUE THREAD

**Issue by rwnd-bradley** [GeyserMC/Geyser#4789]
### What feature do you want to see added?

Java has provided a method to add custom enchantments via data packs, and Paper allows you to achieve this programmatically through their [lifecycle API](https://docs.papermc.io/paper/dev/registries#create-new-entries). The sole issue is that custom enchantment names do not appear anywhere (books, tools, or in the enchantment table preview) for Bedrock clients. Additionally, the anvil does not present an offer for the client to select when combining a tool with a custom enchantment book.

![image](https://github.com/GeyserMC/Geyser/assets/75290033/3001c801-a11e-4af1-95e0-dc2f6ccec9fb)
![image](https://github.com/GeyserMC/Geyser/assets/75290033/48aad369-63fb-4021-a604-67afec8e3e08)
![image](https://github.com/GeyserMC/Geyser/assets/75290033/2c1139cd-4b19-4911-b6f9-4aaa58df329a)
![image](https://github.com/GeyserMC/Geyser/assets/75290033/e2b1b976-08bc-45d6-84b3-a621431be3d5)

I'm aware this, unfortunately, may not be possible due to Bedrock client limitations but would appreciate if it could be looked into. 

### Are there any alternatives?

None that I'm aware of.

**Comment by onebeastchris** [comment]
Regarding translations: You'd have to add them manually for all languages as of now. See the section on `Modifying/Adding Minecraft Java translations` on this wiki page: https://wiki.geysermc.org/geyser/translations/

Regarding showing custom enchantments in the enchanting table, or the anvil - that is unfortunately a Bedrock client limitation. That's documented here: https://wiki.geysermc.org/geyser/current-limitations/
Closing this issue as this is sadly not something that we can really fix (except *potentially* adding custom translations automatically in the future).

**Comment by Camotoy** [comment]
I do intend to explore workarounds for allowing custom enchantments to be applied in an anvil. There's no ETA for this, however.
