### ISSUE TITLE
Unable to place grass or open chests while holding grass

### ISSUE THREAD

**Issue by TheDogg** [GeyserMC/Geyser#4794]
### Describe the bug

Bedrock players cannot put down grass (sometimes works when spam clicking it but very rare) and they cannot open a chest while holding grass in their hand.

### To Reproduce

1. Hold grass in your hand
2. Place grass on any block
3. try to open a chest while holding the grass

### Expected behaviour

Able to put down grass and open chests while holding the grass

### Server Version and Plugins

Velocity 3.3.0-SNAPSHOT (git-9d25d309-b400)
Paper version 1.20.6-147-ver/1.20.6@e41d44f

### Geyser Dump

https://dump.geysermc.org/4FFuGmutR6cF2us6FfINjNpmgugzPOhp

### Geyser Version

2.4.0-b582 (git-master-55e90b6)

### Minecraft: Bedrock Edition Device/Version

1.21.0.3

**Comment by SpringPea** [comment]
I couldn't place down grass too
