### ISSUE TITLE
The Chunk failed to load correctly after a rail tour

### ISSUE THREAD

**Issue by Gnfhaotian** [GeyserMC/Geyser#4796]
### Describe the bug

The Problem is different from #4791 or #4413.
It works better than that —— blocks without full hitboxes are rendered and players can move.

### To Reproduce

1. Joining to server
2. Modifying the rendering distance to about 7 chunks
3. Traveling by minecarts
4. Bugs appear when traveling or arriving stop

### Expected behaviour

Well.. It should be rendered correctly and completely

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/52871253/fa9266f0-849d-4ff7-83c4-665862c1a581)

### Server Version and Plugins

Server runs on Spigot
Java 21
Minecraft:
Java: 1.20.6

### Geyser Version

Geyser 2.4.0 with branch #723( Otentially fix render distance issues )

### Minecraft: Bedrock Edition Device/Version

1.20.81, Android

**Comment by onebeastchris** [comment]
What's the client/server render distance set to?

**Comment by Gnfhaotian** [comment]
> What's the client/server render distance set to?

6 Chunks

**Comment by onebeastchris** [comment]
Are both client and server on 6 chunks? Please specify that so we can reproduce the issue.

**Comment by Gnfhaotian** [comment]
> What's the client/server render distance set to?

The server render distance is 6 chunks, the client's is 8 chunks

**Comment by Gnfhaotian** [comment]
> Are both client and server on 6 chunks? Please specify that so we can reproduce the issue.

server is on 6 chunks and the client is over 6 chunks. What the screenshot shows is on 7 chunks. This bug does not exist when client render distance is 4 or 5 chunks.

**Comment by rorychatt** [comment]
Also mentioned here

https://github.com/GeyserMC/Geyser/issues/4678#issuecomment-2184198768

**Comment by Gnfhaotian** [comment]
> Also mentioned here
> 
> [#4678 (comment)](https://github.com/GeyserMC/Geyser/issues/4678#issuecomment-2184198768)

Well, but how can I merge it with another branch ？

**Comment by Gnfhaotian** [comment]
Has any developer seen this？

**Comment by onebeastchris** [comment]
Given that this is the same issue as https://github.com/GeyserMC/Geyser/issues/4413, ill close this - there's no need to have multiple issues about the same problem.

**Comment by Gnfhaotian** [comment]
> 鉴于这是与#4413相同的问题，我将关闭它——没有必要针对同一问题提出多个问题。

The phenomenon in #4413 is also happening with the fixing build :0

**Comment by onebeastchris** [comment]
Try the builds found here: https://github.com/GeyserMC/Geyser/actions/runs/9607076730?
