### ISSUE TITLE
Mobile Bedrock InventoryOpenEvent not being cancelled.

### ISSUE THREAD

**Issue by stromsoftware** [GeyserMC/Geyser#4797]
### Describe the bug

When mobile Bedrock users click on anvil I cancel InventoryOpenEvent but it shows anyways.  

### To Reproduce

1. Use InventoryOpenEvent to cancel all events
2. Click on anvil while in Mobile Bedrock edition.

### Expected behaviour

Anvil should not open.

### Geyser Version

55e90b6

### Minecraft: Bedrock Edition Device/Version

Mobile/Pocket Edition latest

**Comment by onebeastchris** [comment]
Unable to reproduce on Paper 1.21 and Minecraft: Bedrock Edition on Android/iPad/Win10 (all on 1.21.1) using the following bit of code:
```java
@EventHandler
  public void onInventoryOpen(InventoryOpenEvent event) {
      if (event.getInventory() instanceof AnvilInventory) {
          System.out.println("Anvil inventory is being opened!");
          event.setCancelled(true);
      }
  }
```

Please provide complete reproduction steps, a Geyser dump, and specify which Bedrock/Java versions this occurs with.

**Comment by onebeastchris** [comment]
Closing due to no further response.
