### ISSUE TITLE
Skin Error

### ISSUE THREAD

**Issue by superwfox** [GeyserMC/Geyser#4798]
### Describe the bug

Environment:
 server:1.20.6 purpur
geyser: 2.3.2-SNAPSHOT (git-master-18ad652)

Situation:
  1.When I opened the combination of Floodgate and geyser and installed GeyserSkinManager, the java version of Minecraft can display the skin of be normally, but the players in the bedrock version can only see each other's steve skin, including myself.
  2.Someone told me that installing SkinStorer can solve the problem, after I installed it, players in the bedrock version can see the skin correctly.However,players in the java version can only see the skin of Efe.
   In addition ,cape never show correctly for bedrock players.

### To Reproduce

……

### Expected behaviour

The skin and cape of the bedrock version are displayed normally.

### Geyser Version

2.3.2-SNAPSHOT (git-master-18ad652)

### Minecraft: Bedrock Edition Device/Version

1.20.6

**Comment by superwfox** [comment]
which build should i choose,the latest one won’t work on 1.20.6

**Comment by onebeastchris** [comment]
Install ViaVersion - the latest Geyser builds emulate a 1.21 Java client, so if your server isn't on 1.21, ViaVersion is needed.
