### ISSUE TITLE
The attribute name does not display correctly

### ISSUE THREAD

**Issue by kolderz** [GeyserMC/Geyser#4800]
### Describe the bug

The attribute name does not display correctly on Bedrock.

### To Reproduce

1. Modify an item with any attribute.

### Expected behaviour

Display the correct attribute name.

### Screenshots / Videos

**Java:**
![Java attributes](https://github.com/GeyserMC/Geyser/assets/10612667/65c41bb1-4606-44d5-9816-6f9bc8ba7017)
**Bedrock:**
![SnippingTool_n7FLe602MP](https://github.com/GeyserMC/Geyser/assets/10612667/3f4c9cbc-ea9b-4d7d-a21e-733edbc58a2a)

### Server Version and Plugins

git-Purpur-2176 (MC: 1.20.4).
No plugins.

### Geyser Version

Geyser version 2.4.0-b583 (git-master-a8bd93a) (git-master-a8bd93a) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.0/1.20.1)

### Minecraft: Bedrock Edition Device/Version

1.21.0 on Windows 11

**Comment by Camotoy** [comment]
Please send us a Geyser dump link.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by onebeastchris** [comment]
You're using an outdated Geyser build. Please update Geyser (download from here: https://geysermc.org/download), and see if the issue still occurs with the latest version of Geyser.

**Comment by Camotoy** [comment]
That dump is from an older Geyser version on Velocity?

**Comment by onebeastchris** [comment]
Do 1.21 Java clients see the correct values?

**Comment by onebeastchris** [comment]
This would indicate a ViaVersion issue - please report it to them (comparing 1.20.4 Java with 1.21 Java).
