### ISSUE TITLE
Unable to get on/off blocks and going down ladders

### ISSUE THREAD

**Issue by SpringPea** [GeyserMC/Geyser#4801]
### Describe the bug

After the dev of the mc server updated the anti cheat, I seemed to be unable to get off chests/blocks and going down ladders as I will be continuously be stuck if I attempt to go down ladders or getting off blocks once I stood on them 

It seems to affect bedrock players like myself, most likely mobile players specifically 

### To Reproduce

1. Have the anti cheat updated on the server
2. Walk on top of blocks or going down ladders
3. Try to get off blocks or chests
4. Players will be stuck continuously 

### Expected behaviour

Player should be able to normally getting down from chest or blocks or going down ladders without getting stuck,  even if anti cheat is updated

### Server Version and Plugins

Version: 1.17 to 1.20

Plugins: singleplayer sleep, auction, treecapitator,  chestshop, shop, advanced enchantments,  claim, 

### Geyser Version

Latest version

### Minecraft: Bedrock Edition Device/Version

1.21.0.03, android

**Comment by onebeastchris** [comment]
Geyser currently does not emulate movement of a Java client perfectly. Hence, anticheats should currently ignore Bedrock players, or check them with more leeway.

Here's a list of anticheats that work with Geyser:
https://wiki.geysermc.org/geyser/anticheat-compatibility/

Further - when reporting issues about a specific plugin, mentioning which specific one it is would be really helpful.

Closing as this isn't something that we'll be able to address at the moment.
