### ISSUE TITLE
unable to connect to server - java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by FantasyPvP** [GeyserMC/Geyser#4804]
### Describe the bug

i get a long error stating there is an out of bounds exception when trying to connect a bedrock client.

### To Reproduce

- run a velocity proxy on the frontend, setup according to the geyser/floodgate wiki instructions for velocity
    - velocity has viaversion, geyser and floodgate installed.
- paper server on the backend 1.20.1
    - the paper server only has floodgate installed, according to instructions on the wiki

- attempt to connect to the proxy with a bedrock client

### Expected behaviour

player can connect to server

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/80643031/d121abee-87b0-49ca-a648-e92d9356a8d2)

### Server Version and Plugins

frontend:
velocity-3.3.0-snapshot-400.jar
geyser-velocity.jar       build #584
floodgate-velocity.jar  build #109
ViaVersion-5.0.1.jar

backend: 
paper 1.20.1-196.jar
floodgate-spigot.jar build #109

### Geyser Dump

https://dump.geysermc.org/4kkI7fD2gRtuMemva7D2f81pixb5ek9M

### Geyser Version

2.4.0-b584

### Minecraft: Bedrock Edition Device/Version

1.21.1 android

**Comment by onebeastchris** [comment]
This occurs when the velocity forwarding mode is set to "none". Setting up the modern forwarding type should resolve this. Alternatively, you can disable "send-floodgate-data", however, that will result in no data being forwarded from the proxy's floodgate to the backend server.

See here for a guide on how to set up modern forwarding: https://docs.papermc.io/velocity/player-information-forwarding
