### ISSUE TITLE
Jungle leaves ‘s Appearance is wrong 

### ISSUE THREAD

**Issue by superwfox** [GeyserMC/Geyser#4805]
### Describe the bug

The leaves look like pink not the normal one
![IMG_1506](https://github.com/GeyserMC/Geyser/assets/65709399/dd31a191-654c-470e-81cd-fa0d6ba18bd5)

### To Reproduce

Every progress game can steadily reproduce this problem.

### Expected behaviour

Green leaves

### Geyser Version

2.4.0-b584 (git-master-ca2312c) (git-master-ca2312c) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.0/1.20.1)

### Minecraft: Bedrock Edition Device/Version

1.21.0

**Comment by onebeastchris** [comment]
Unable to replicate - this is likely an issue with a resource pack.
