### ISSUE TITLE
gamepad

### ISSUE THREAD

**Issue by xiaoniangaoh** [GeyserMC/Geyser#4808]
### What feature do you want to see added?

In Minecraft Bedrock Edition, there will be a bug when using a controller to open the Java server, and I hope to make a game controller adapted to Java Edition

### Are there any alternatives?

No

**Comment by Camotoy** [comment]
Gamepads are supported through Geyser. Can you send a step-by-step of how to replicate what you're seeing, or error messages, or a video?

**Comment by onebeastchris** [comment]
Closing due to no further response. If this is about Java edition players being able to use controllers, there are Java client mods for that - if it's about Bedrock players not being able to use controllers with Geyser, please open a detailed issue with detailed replication steps.
