### ISSUE TITLE
A error from geyser for Minecraft 1.21.1

### ISSUE THREAD

**Issue by lyJinZhi** [GeyserMC/Geyser#4809]
### Describe the bug

The Minecraft Bedrock Edition client looks at Java Edition when a player uses a Wind Bomb to explode and make the block pretend to disappear, but the block is still there, and the person on the block will be unable to move, and the Trials answer will be blank

### To Reproduce

1.Use wind bomb
2.The block was broken by wind bomb(it should not break any block but it was,just like tnt)
3.I can't move when I am standing on air block

### Expected behaviour

Same as the Java Edition Client

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/173550071/fcbfc59a-baa0-4758-8031-359a80391397)

### Geyser Version

2.3.2-SNAPSHOT (git-master-09c0ada)

### Minecraft: Bedrock Edition Device/Version

1.21.1 for Windows and 1.21.1 from Google Play

### Additional Context

Paper Version is 1.21-21-master@0a1b133 (2024-06-21T09:19:07Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

**Comment by onebeastchris** [comment]
You're using an outdated version of Geyser - please update. This was resolved.
