### ISSUE TITLE
Geyser Velocity - Read timed out

### ISSUE THREAD

**Issue by xiaohe123awa** [GeyserMC/Geyser#4811]
### Describe the bug

Some players cannot access the server due to read timed out, and other players can access the server normally.

### To Reproduce

1.Set up a Velocity server, that has both Floodgate and GeyserMC, with a Paper Backend, Install floodgate as well
2.Set the Bedrock port to be the same as the Java port.
3.Attempt to join the server on a Bedrock client.

### Expected behaviour

All players can enter the server normally.

### Server Version and Plugins

Velocity-3.3.0
Paper-1.20.4

### Geyser Dump

https://dump.geysermc.org/0M4tagqITdlDDjnDXiBLoDseZw5bPgry

### Geyser Version

Geyser2.4.0-b585(git-master-130b272)

### Minecraft: Bedrock Edition Device/Version

1.20.80

**Comment by onebeastchris** [comment]
"Read timed out" implies that the Java server didn't send any packets for 30 seconds. Based on the info provided here, narrowing down the issue won't be possible.

Please test the following:
- Does this occur with a 1.21 Java client?
- Does this also occur without any Java resource packs being sent?
- Does this occur without unsupported offline mode auth plugins?

Further, please enable debug-mode in Geysers config, and send a full log via mclo.gs that shows a join attempt of a Bedrock player.

**Comment by xiaohe123awa** [comment]
1.No
2.Yes
3.Yes
Logs: https://mclo.gs/rYSHgZh

**Comment by onebeastchris** [comment]
Please provide a full log, not just a snippet. Further, this sounds like a potential plugin issue, so please attempt to reproduce the issue on a setup with no plugins - I'm unable to reproduce the issue on a clean setup.

see the instructions here (for both the proxy & backend server:)

If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
- Temporarily remove/move half of your plugins from your server's plugins folder.
- *If the problem persists*, remove another half.
- *If the problem goes away*, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by xiaohe123awa** [comment]
Full logs: https://mclo.gs/NSntUuj

**Comment by xiaohe123awa** [comment]
This problem still occurs when I remove all plugins except Geyser and Floodgate.New Log:https://mclo.gs/SR6hwjs

**Comment by onebeastchris** [comment]
Try removing plugins from the backend/connecting to a clean server?

**Comment by xiaohe123awa** [comment]
This problem has been successfully solved, thank you

**Comment by onebeastchris** [comment]
Which plugin was it? There could still be a Geyser issue, we just need to know where to look

**Comment by xiaohe123awa** [comment]
I don't know which of the three plugins had problems, but when I removed them the problem was solved.
limboapi
LimboReconnect
McKotlinVelocity
