### ISSUE TITLE
[F-Req] A way to change mappings at runtime. 

### ISSUE THREAD

**Issue by letsgoawaydev** [GeyserMC/Geyser#4813]
### What feature do you want to see added?

Anyway to change mappings at runtime (eg, sound, blocks, biomes) This could be via an api, providing the direct jsons inside of geysers data folder, or just any way to do it without having to recompile the entire project.

### Are there any alternatives?

No alternatives other than recompiling geyser afaik, but you can do custom item mappings but thats all i think is available at runtime

**Comment by Kas-tle** [comment]
If you really don't want to recompile Geyser you can just unzip the jar file and replace the mappings.
