### ISSUE TITLE
Display Entities Support for MEG4

### ISSUE THREAD

**Issue by DontMessWithDis** [GeyserMC/Geyser#4818]
### What feature do you want to see added?

I would love to be able to utilize MEG4 and include my bedrock players in on the experience. Currently armor stands are the only known supported option.

### Are there any alternatives?

Yes, using MEG3 the only issue is it can cause lag at scale.

**Comment by onebeastchris** [comment]
Hey! Thanks for the feature request. However, this is already requested here: https://github.com/GeyserMC/Geyser/issues/3810 - so I'll close this as duplicate.
