### ISSUE TITLE
issues with doors after villagers or java players open and leaves door open

### ISSUE THREAD

**Issue by Jsaunders411** [GeyserMC/Geyser#4826]
### Describe the bug

when a villager or java player opens a door and leaves it open it appears closed to the bedrock client and you cant go thru it and it acts like its closed and dont let the bedrock player pass thru it until the door is closed by the villager or java player or the bedrock player breaks the door.

### To Reproduce

1. have java player open the door and leave it open.
2. have the bedrock client interact and open the door it wont let the player pass thru
3. door wont work like normal until java player either closes the door or the door is broken and placed back down.

### Expected behaviour

door should open close no matter who opens it or iif its left open.

### Server Version and Plugins

paper 1.21 build #44

### Geyser Dump

https://dump.geysermc.org/xIvKVNIP3j0me5tldwC6e9hW2rWdxxmb

### Geyser Version

Geyser version 2.4.0-b592 (git-master-74cabed) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.0/1.20.1)

### Minecraft: Bedrock Edition Device/Version

Minecraft bedrock 1.21

**Comment by onebeastchris** [comment]
Can you test the build found under "Checks" in the linked PR? https://github.com/GeyserMC/Geyser/pull/4827
It should resolve the issue.
