### ISSUE TITLE
Bedrock players get kicked when certain entities are near

### ISSUE THREAD

**Issue by Kingminer7** [GeyserMC/Geyser#4828]
### Describe the bug

When certain entities are near, a bedrock player on a server I'm on gets kicked.
So far I know of:
Paintings
The Warden
Falling Sand

### To Reproduce

1. Spawn one of the listed entities
2. The bedrock player is kicked for some reason

### Expected behaviour

The bedrock player should be able to play as normal

### Server Version and Plugins

CraftBukkit version 4244-Spigot-0a642bd-13ece47 (MC: 1.21)]

Plugins:
Geyser
AutoUpdateGeyser
Floodgate
_**Kicks still happen without the following plugins - unsure about above**_
Shopkeepers
WorldEdit

### Geyser Dump

Said that an internal error occurred

### Geyser Version

Geyser 2.4.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

Xbox 1.21.1

**Comment by Camotoy** [comment]
Please post a complete server log.

**Comment by onebeastchris** [comment]
Closing due to no further response - this sounds like a server issue. If you still encounter this issue, please attach server logs & a new geyser dump. Thanks!
