### ISSUE TITLE
Cannot join game after using universal shop mod(a polymer mod)

### ISSUE THREAD

**Issue by oldsheep0205** [GeyserMC/Geyser#4831]
### Describe the bug

I add universal shop mod. Then I cannot join the game, from java edition its ok but from bedrock it said connection closed. I set "add-non-bedrock-items: true" but it doesnt work. What should I do next?

### To Reproduce

1. put universal shop in mods.
2. open favbric geyser server
3. no error showed in console.
4. cannot join from bedrock side.

### Expected behaviour

need to join the game.

### Server Version and Plugins

1.21 version. 

### Geyser Version

2.4.0-b589 git-master-ff1e1dd

### Minecraft: Bedrock Edition Device/Version

1.21.1 bedrock edition

**Comment by oldsheep0205** [comment]
after I open debug mode, I found that the console will return geyser.skin.bedrock.fail, skin size = 256*256 if I use default bedrock skin. When I change another skin, the console will not return anything, then my bedrock client will return connection closed....

**Comment by onebeastchris** [comment]
Please send a full server log (latest.log file in the logs folder; you can send it via https://mclo.gs/ to censor ip's), and attach a geyser dump. I can join just fine using the latest version of Geyser-Fabric, Floodgate-Fabric, and the universal shops mod (https://modrinth.com/mod/universal-shops).

**Comment by onebeastchris** [comment]
Looks like Polymer added a workaround for https://github.com/GeyserMC/Geyser/issues/2776 which just checks Bedrock players using floodgate - which is why it works with Floodgate. You can set `forward-player-ping` to `true` to resolve this issue. Further, offline mode is not supported.
