### ISSUE TITLE
Packet downloading error ! Invalid packet id: 108.

### ISSUE THREAD

**Issue by Leo-le-jeune** [GeyserMC/Geyser#4833]
### Describe the bug

When a player connects to the server, the following warn appears on our Proxy console :
```
[Geyser-BungeeCord]: Packet downloading error ! Invalid packet id: 108
```

### To Reproduce

Another player has got the same bug and we have both reported this on your Discord support but without any solution.
[The other player's screen.](https://discord.com/channels/613163671870242838/613168464634576897/1259424641303314476)

### Expected behaviour

No warn.

### Screenshots / Videos

Here are the normal [logs.txt](https://github.com/user-attachments/files/16120006/logs.txt).
Here are the logs in the Geyser's debug mode : [debug_geyser.txt](https://github.com/user-attachments/files/16120008/debug_geyser.txt).

### Server Version and Plugins

 We usually use FlameCord, a waterfall fork. (Find this fork config here : [config_flamecord.txt](https://github.com/user-attachments/files/16120000/config_flamecord.txt))
We have tried without any other plugin which hasn't succeeded.
We have tried to change our Proxy from our FlameCord proxy to a normal BungeeCord proxy without any success.
We have tried to use Velocity and this time, the warn doesn't appear.
We have disabled the whole firewalls without any success.

### Geyser Dump

https://dump.geysermc.org/hQ5FECcayKfuo7l8HnpH8W6XMBLcDnPJ

### Geyser Version

2.4.0-b595 (git-master-e0af0a5)

### Minecraft: Bedrock Edition Device/Version

1.21.1, Minecraft for Windows

### Additional Context

Here is our [bungeecord Geyser's config](https://github.com/user-attachments/files/16120016/config_bungeecord.txt).

**Comment by onebeastchris** [comment]
This is the same root issue as this issue: https://github.com/GeyserMC/Geyser/issues/4790, as MCPL (our java library) isn't properly switching between protocol states. We're working on a fix, but due to the complexity of the state system, that'll take a while. Thanks for reporting - however, since this is essentially the same bug, I'll close this report as duplicate.
