### ISSUE TITLE
Bedrock players can’t see coloured dog armor.

### ISSUE THREAD

**Issue by ioannis2008** [GeyserMC/Geyser#4838]
### Describe the bug

When you colour dog armor and then put it on your hog you can’t see the colours from bedrock clients, only the basic dog armor texture.
![IMG_7752]

(Images / videos of what happens when you colour and wheeze the armor to your god)
(https://github.com/GeyserMC/Geyser/assets/83643262/98a3feab-5bf6-4e4c-a9c0-6a8640c291e0)

https://github.com/GeyserMC/Geyser/assets/83643262/288df0d0-d9d0-4976-bc5f-deffd1d45336

### To Reproduce

Craft a dog armor and colour it. Then wear it to your dog. You can’t see the colours, only the basic texture.

### Expected behaviour

I expected to be able to see the colours of coloured dog armor.
 
 (Video of what happens on singleplayer bedrock)
https://github.com/GeyserMC/Geyser/assets/83643262/61ffda87-0ba8-4ab9-906f-bd94f0b46a53

### Screenshots / Videos

Image of bedrock edition with bug (multiplayer):
![IMG_7752](https://github.com/GeyserMC/Geyser/assets/83643262/5ec26eca-631d-4bf5-89ee-7765ce52a854)

https://github.com/GeyserMC/Geyser/assets/83643262/6b9f7f55-ef7e-45a3-add4-f19d7091bc12

Image of bedrock edition without bug (singleplayer):
https://github.com/GeyserMC/Geyser/assets/83643262/d08801a7-12fe-4465-a4b0-11d8036394cd

Image of the same dogs on Java edition (with visible armor colours): 

![IMG_7791](https://github.com/GeyserMC/Geyser/assets/83643262/e1cac62a-05dd-44f1-b030-91dcfb2c33f1)
![IMG_7790](https://github.com/GeyserMC/Geyser/assets/83643262/d9b9178b-7ea3-4dc1-82be-2fc8148233fb)
![IMG_7789](https://github.com/GeyserMC/Geyser/assets/83643262/702cda68-7359-48d1-a2ef-7a5587b9c30a)

### Server Version and Plugins

“This server is running Paper version 1.20.6-129-master@0513374 (2024-05-31T15:53:34Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are 19 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-344 (MC: 1.20.4)”

### Geyser Dump

https://dump.geysermc.org/iLdtNPSprSoSfrBiy7p5R5y4eqgUoAsY

### Geyser Version

Geyser 1.21

### Minecraft: Bedrock Edition Device/Version

1.21, Minecraft ps4 edition but players from mobile and pc have reported the same behaviour.

**Comment by onebeastchris** [comment]
Try updating Geyser - you're 92 commits behind
