### ISSUE TITLE
The bedrock version cannot normal use the scaffolding

### ISSUE THREAD

**Issue by XiaCurtain** [GeyserMC/Geyser#4841]
### Describe the bug

The bedrock version cannot perform downward movement on the scaffolding properly when using the new operating method.
If using the old operating mode, it is also necessary to maintain squatting in order to move down normally

### To Reproduce

1.Switch to new version operation
2.Use the down key to move on the scaffold.

### Expected behaviour

Both the new and old versions of the operation can be moved downwards on the scaffolding, whether squatting or not

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/110004489/88bc1978-a71c-4308-9f8e-a9435f484b28

https://github.com/GeyserMC/Geyser/assets/110004489/eacba8a1-2e25-4c5c-a630-508cf4b2127a

### Server Version and Plugins

server:fabric1.21
mods:hurricane
geyser version:Build #580

### Geyser Version

fabric Build #580

### Minecraft: Bedrock Edition Device/Version

1.21.1.03

**Comment by ScolderCreations** [comment]
Can replicate.

**Comment by JoshuaPHYT** [comment]
Any solution I'm using geyser spigot

**Comment by CherubicBoot** [comment]
I'm still getting this issue when running on the latest standalone version on mobile but not windows. any update to this?

**Comment by CherubicBoot** [comment]
https://github.com/user-attachments/assets/bbc2e81c-8d8f-4f12-99cb-090a2d83472f

-2025-02-28-1
