### ISSUE TITLE
Not able to craft/take items out of enderchest after adding a Datapack

### ISSUE THREAD

**Issue by chaozbtw** [GeyserMC/Geyser#4844]
### Describe the bug

I added a datapack called TCC (The Creepers Code) and I knew it would cause bedrock players to not be able to use the datapacks content but for some reason bedrock players cant even craft or take items out of enderchests anymore. The recipe menu is gone completely and if you insert items manually it doesnt work.

I don't know if this bug is specific to this one datapack or if it applies to a lot of them.

### To Reproduce

1. Download TCC
2. Start Server with GeyserMC
3. Open Enderchest/Crafting Table

Alternative
1. Download any other Datapack (with new content)
2. Start Server with GeyserMC
3. Open Enderchest/Crafting Table

### Expected behaviour

All vanilla items work normally while the datapacks items would be bugged.

### Screenshots / Videos

![Screenshot 2024-07-10 101520](https://github.com/GeyserMC/Geyser/assets/122107600/4a6ff08a-0676-4698-b4d7-2e13f95a3b45)
![Screenshot 2024-07-10 101527](https://github.com/GeyserMC/Geyser/assets/122107600/571b121a-f514-4dbc-8a26-a9f8fa2d2c4e)

### Server Version and Plugins

This server is running CraftBukkit version 4261-Spigot-491f367-aceddcd (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)
Checking version, please wait...
You are running the latest version

### Geyser Dump

https://dump.geysermc.org/3IAoMrpcCUDAK1V5lAdbmBRXIkFLEaaj

### Geyser Version

This server is running Geyser version 2.4.0-b598 (git-master-7fdb410) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.2))
Checking version, please wait...
No updates available

### Minecraft: Bedrock Edition Device/Version

PC

**Comment by onebeastchris** [comment]
Please send the full server log file using mclo.gs

**Comment by chaozbtw** [comment]
> Please send the full server log file using mclo.gs

https://mclo.gs/RZbfhE0

**Comment by onebeastchris** [comment]
Should be resolved in the latest version (https://github.com/GeyserMC/MCProtocolLib/commit/86903ecd73d0360646270ebdd751fbd470867e52 was included as part of the mcpl bump that includes the new auth lib). Thanks for reporting!
