### ISSUE TITLE
Blocks are not being remade correctly in the stonecutter 

### ISSUE THREAD

**Issue by neboykot** [GeyserMC/Geyser#4845]
### Describe the bug

https://github.com/GeyserMC/Geyser/assets/142654613/b948904c-2fe4-4264-922d-a6ac9cbb356d

All custom and vanilla recipes do not work correctly. For example, I choose a brick slabs, and at the exit I get stairs

### To Reproduce

1. We use a stone cutter
2. We put the block that we want to recraft
3. Recrafting

### Expected behaviour

Normal craft

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/142654613/9e8fd695-63d1-4b41-97c6-23c52a4e8635

### Server Version and Plugins

Paper 1.21 (version 47)

### Geyser Dump

https://dump.geysermc.org/vsst7RxuJniHozwe4bl9kIa2JjAehX4T

### Geyser Version

2.4.0-b598 (git-master-7fdb410)

### Minecraft: Bedrock Edition Device/Version

1.21.2

**Comment by 7Wdev** [comment]
yea I faced this issue too, it works well with vanilla recipies. but when you add custom recipies the whole stonecutter crafting system corrupts for some reason

**Comment by onebeastchris** [comment]
Hey! Can either of you share a datapack/provide reproduction steps to add such custom recipes to make it easier to reproduce? Thanks!

**Comment by 7Wdev** [comment]
Custom stonecutter recipes in this plugin doesn't work properly in geyser in the bedrock client. For example stripped log gives u boat instead. 
https://www.spigotmc.org/resources/betterlogstrip.99456/

**Comment by onebeastchris** [comment]
Able to reproduce, it seems to somehow select the wrong recipe.
