### ISSUE TITLE
Bug with BungeeCord (BetterBungee)

### ISSUE THREAD

**Issue by CcNicebruh** [GeyserMC/Geyser#4846]
### Describe the bug

before i load the plugin it's not working.

### To Reproduce

1. download the plugin
2. put in /plugins folders
3. run the proxy

4. this error message
```
21:24:07 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@3f270e0a, id=35, owner=org.geysermc.geyser.platform.bungeecord.GeyserBungeePlugin@1259b2a5, task=org.geysermc.geyser.platform.bungeecord.GeyserBungeePlugin$$Lambda/0x00007fb3a0201ac8@6779af40, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.GeyserImpl.isReloading()" because the return value of "org.geysermc.geyser.GeyserImpl.getInstance()" is null
    at org.geysermc.geyser.platform.bungeecord.GeyserBungeePlugin.onGeyserEnable(GeyserBungeePlugin.java:139)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1583)
 ```

### Expected behaviour

running normal

### Server Version and Plugins

21:35:12 [INFO] This server is running BetterBungee version Stable(1.5) by Luca_zPlays
21:35:12 [INFO] More Infos at https://dsc.gg/betterbungee
21:35:12 [INFO] BungeeCord Version #6820013

### Geyser Version

latestt

**Comment by CcNicebruh** [comment]
https://mclo.gs/gH3b16T

**Comment by onebeastchris** [comment]
It looks like this bungee fork breaks assigning the logger in the constructor
(https://github.com/GeyserMC/Geyser/blob/master/bootstrap%2Fbungeecord%2Fsrc%2Fmain%2Fjava%2Forg%2Fgeysermc%2Fgeyser%2Fplatform%2Fbungeecord%2FGeyserBungeePlugin.java#L67) for reference.
Report this issue to them, not us - we officially only support BungeeCord.
