### ISSUE TITLE
Some blocks will not load in propperly when joining server.

### ISSUE THREAD

**Issue by maxw2000** [GeyserMC/Geyser#485]
**Describe the bug**
Blocks like Pistons will not show the top part.
Sometimes trapped chests will now show up at all.

**To Reproduce**
Join a server with those blocks already placed.

**Expected behavior**
Blocks should be shown propperly

**Screenshots / Videos**
https://youtu.be/0uH-sr8O9tU

**Server Version**
![image](https://user-images.githubusercontent.com/22998325/81067324-d1163980-8ede-11ea-87fe-4832de13c1c2.png)

**Geyser Version**
Build 109

**Minecraft: Bedrock Edition Version**
v1.14.60

**Additional Context**
I am using 4 plugins.
![image](https://user-images.githubusercontent.com/22998325/81067561-20f50080-8edf-11ea-998c-ff1068b64a37.png)
The Enthix_Core plugin is a custom plugin for the lobby.
Bungeecord is using Floodgate.

**Comment by DoctorMacc** [comment]
Please update your build of Geyser - we've fixed both of those issues. Thanks for the report anyway!
