### ISSUE TITLE
Sticky Piston Bug

### ISSUE THREAD

**Issue by 7Wdev** [GeyserMC/Geyser#4863]
### Describe the bug

a sticky piston does not close after removing redstone source.

### To Reproduce

just make a paper/spigot server,
put in geysermc and floodgate.
now try to play with sticky pistons and you should notice the bug.

### Expected behaviour

the sticky piston to update properly

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/81238cc6-8de2-4fe4-8906-eed3943630aa)

### Server Version and Plugins

1.21

### Geyser Dump

https://dump.geysermc.org/pFM4ZL8jk9DbCQVGIcAfy5Fcn1SVolR6

### Geyser Version

Geyser version 2.4.0-b604

### Minecraft: Bedrock Edition Device/Version

Windows 11 PC

**Comment by onebeastchris** [comment]
Does this also occur when testing with a 1.21 Java client?

**Comment by 7Wdev** [comment]
No, only in the bedrock client.

**Comment by onebeastchris** [comment]
There are two potential options here:
1. You may have accidentally discovered quasi-connectivity (https://youtu.be/eyuYNDsxIHY) - in which case the piston staying extended is exactly what Java behavior is (which Geyser doesnt modify).

or:

2. This could be a Geyser issue related to pistons not updating, however, this is unlikely - I've not been able to reproduce this issue on a paper 1.21 paper server.

If you believe it's 2., please provide exact replication steps for how to reproduce the issue. Thanks!

**Comment by 7Wdev** [comment]
I am sure it's 2, I have tried it in a clean paper 1.21 server. The piston works well, I am talking about sticky pistons they does not update as you can see in the image I detached it from any other redstone source and it is still open

**Comment by onebeastchris** [comment]
We've received another report that it is apparently also occurring with Java clients, so there's probably a third option - please double-check that this isnt occurring for Java players

**Comment by 7Wdev** [comment]
for me in java it is working normally

**Comment by onebeastchris** [comment]
For me, Bedrock is working fine, so here we are. If possible, please provide detailed replication step on how to run into that issue - further, see if paper's non-experimental 1.21 builds work.
