### ISSUE TITLE
PLAYER_BLOCK_INTERACTION_RANGE Attribute do not apply to Bedrock Edition Player.

### ISSUE THREAD

**Issue by superwfox** [GeyserMC/Geyser#4864]
### Describe the bug

Can not set the attribute correctly.

### To Reproduce

1.Set the PLAYER_BLOCK_INTERACTION_RANGE Attribute for both Java and Bedrock Player
2.Dig the squares at the same starting point
![IMG_0357](https://github.com/user-attachments/assets/5915d172-24a4-49eb-a337-84e51206867a)

### Expected behaviour

Bedrock Player should get the right hand

### Geyser Version

latest

### Minecraft: Bedrock Edition Device/Version

1.21.2,IOS/windows11

**Comment by onebeastchris** [comment]
This is unfortunately a can't fix as this feature does not exist on Bedrock edition :/

**Comment by superwfox** [comment]
However the original client support 7blocks and even 10blocks on BE

**Comment by onebeastchris** [comment]
Yes, block ranges up until that could probably be supported.

**Comment by superwfox** [comment]
i tried but  it doesn't work at all

**Comment by Camotoy** [comment]
Further block ranges will be respected as much as we are able to support them.
