### ISSUE TITLE
Cant craft dispensers in crafting table.

### ISSUE THREAD

**Issue by Jsaunders411** [GeyserMC/Geyser#4865]
### Describe the bug

Cant craft dispensers by clicking picture in crafting table. even if you have all the needed items on you to craft it still shows red and only able to craft it by manually putting it in the crafting table and crafting it.

### To Reproduce

Go to crafting table with needed items to craft dispenser in your inventory.
Look for dispenser in crafting table pictures.
They will  show red and uncraftable.
Manually put its in crafting square then you can craft it by clicking the item next to the crafting grid it will work. If you select it from known recipes in the book it will go back to red and not craft able.

### Expected behaviour

Have items in your inventory  for dispenser and be able to click recipe in book and craft it.

### Geyser Version

Geyser 1.21 build 606

### Minecraft: Bedrock Edition Device/Version

Minecraft bedrock

**Comment by onebeastchris** [comment]
Hey, could you try updating Geyser and testing whether the issue persists? Thanks :)

**Comment by Jsaunders411** [comment]
> Hey, could you try updating Geyser and testing whether the issue persists? Thanks :)

**Comment by Jsaunders411** [comment]
It was still persisting with an update with build  609 . But i will try agian with 611 tomorrow and let you know.

**Comment by Jsaunders411** [comment]
Nope still persists in updated geyser build 7-17-611 can have all items in inventory click on dispenser in book it then unselects it and goes to dropper and acts like you dont have the needed items and goes red and not craftable.

**Comment by onebeastchris** [comment]
Please send a screenshot of the issue - further, please make sure that you have the dispenser crafting recipe unlocked

**Comment by Jsaunders411** [comment]
![20240718_135729](https://github.com/user-attachments/assets/3983b647-d684-4035-b830-cac4de898c47)

**Comment by Jsaunders411** [comment]
Crafting recipe is unlocked as i have manually crafted many dispensers. Just would really like to go back to just being able  to click on the recipe and craft multiple also noticing some other crafting glitches occurring  with stone cutter miss crafting  stars into walls and walls into stairs. Blocks like polished adesite stairs come out as items other than stairs so maybe its linked in some  way was not happening  from older builds before 600 or so.

**Comment by onebeastchris** [comment]
What's the output of `geyser version` in the server console?

**Comment by Jsaunders411** [comment]
![Screenshot_20240718_222101_Chrome](https://github.com/user-attachments/assets/8cd43946-11ae-42a3-8257-73fa4d521415)

**Comment by Jsaunders411** [comment]
Running the current build been updated each time new comes out to see if it would change anything.

**Comment by onebeastchris** [comment]
Could you list all recipes that still seem to be broken?
I'll take a more detailed look tomorrow; although I would've thought that the latest fix should've addressed these crafting issues.. odd

**Comment by Jsaunders411** [comment]
Polished andesite stairs come out as slabs,cobbled deepslate stairs come out as deep slate walls,brick stairs come out as slabs for stone cutter. Are the ones if noticed so far. Its not game breaking by any means just  slightly annoying when i go to craft a large stack of something and it outputs different then what i clicked lol.

**Comment by Jsaunders411** [comment]
I just didn't  post that bug because i saw another one about it and generally try to avoid reporting a duplicate of another bug report.

**Comment by Camotoy** [comment]
Can you send a Geyser dump while you're on the server? Thanks.

**Comment by Jsaunders411** [comment]
https://dump.geysermc.org/iigJfmulW3exOjyzUqNdQz3FXpgW9a46

**Comment by Camotoy** [comment]
Were you online when you made this dump?

**Comment by Jsaunders411** [comment]
https://dump.geysermc.org/slPtyZBYCktI2ntS5iYdNxjivJWCmh5p 

Sorry copied the wrong link.

**Comment by Jsaunders411** [comment]
This dump was while im online.

**Comment by Jsaunders411** [comment]
Update on issue it seems the issue is only a problem with custom recipes data packs. upon removing master cutter data pack it clears the issue with with any customs added it causes geyser clients to have issues with stone cutter crafting. Java clients are not effected.

**Comment by onebeastchris** [comment]
I've tried testing this on various devices, and i just cannot reproduce it. Hence, ive made a little debug build to see what recipes are being sent to the client - please download and use the build found [here](https://github.com/onebeastchris/Geyser/actions/runs/10116968908) and send a log once you see the huge packet being printed (you can use https://mclo.gs/ to share logs easily)

**Comment by Jsaunders411** [comment]
Ok so going thru and testing it only happens when i have a custom stone cutter data pack installed master cutter data pack. Removing it clears the issues with dispenser and the issue with the stone cutter out out being off for certain blocks. Was working fine up until the new 1.21 builds so not sure if its on geysers end or just a data pack issue. But the data pack was updated to 1.21 as well so im at a lose.

**Comment by onebeastchris** [comment]
The stone cutter thing was fixed, update Geyser - as for dispenser recipes, if it still occurs with the latest build and with a datapack, please link it here

**Comment by onebeastchris** [comment]
Hm, just realized that my testing build didn't have that stonecutter fix included. I'll rebuild it, one sec

**Comment by onebeastchris** [comment]
New download: https://github.com/onebeastchris/Geyser/actions/runs/10151686741
this has the latest master changes which include the stonecutter fix, and also the debug line to print relevant details
