### ISSUE TITLE
Geyser don't work for bedrock players

### ISSUE THREAD

**Issue by GuiD-22** [GeyserMC/Geyser#4866]
### Describe the bug

When I try to enter on a Minecraft server with geyser plugin using a bedrock version, the messages "The server sent a broken packet" or "Unable to connect to the server" appears. I have already configured the ports in the settings several times, but the error still persists.

### To Reproduce

1. Click to login to the server. 
2. The error appears

### Expected behaviour

I expected it to enter the server, as expected, but the error did not allow it.

### Geyser Version

609 (bedrock v1.20.80 - v1.21.2)

### Minecraft: Bedrock Edition Device/Version

1.21.2, cellphone. 1.21.2, computer

**Comment by EmeraldGltch** [comment]
Hello! I had the same issue. It seemed to start working for me after installing ViaVersion onto my server.

**Comment by onebeastchris** [comment]
This is likely a configuration issue. Please join our discord for configuration help: https://discord.com/invite/geysermc
