### ISSUE TITLE
allow-third-party-capes/ears missing in the config files

### ISSUE THREAD

**Issue by R4csu** [GeyserMC/Geyser#4875]
### Describe the bug

Even with the extension added properly, this options seems to be missing in the config file of geyser, and adding them manually doesn't seem to work at all

### To Reproduce

1. Install GeyserMC plugin
2. Install Geymser thirdpartycapes extension
3. Run the server, try to find the options in the config file and make them work

### Expected behaviour

Bedrock players should be available to see optifine/minecraftcapes

### Geyser Dump

https://dump.geysermc.org/lvuPiYD6mkpQ6dErYqSxp4qAbN0zx8nO

### Geyser Version

1.21.2

### Minecraft: Bedrock Edition Device/Version

1.21.2

**Comment by Camotoy** [comment]
The extension is not dependent on the config options in Geyser. Please open an issue here instead https://github.com/GeyserMC/ThirdPartyCosmetics, and maybe give a test username to verify with. Thanks!
