### ISSUE TITLE
Add to the API a way to filter out users by their getDeviceOs and getName.

### ISSUE THREAD

**Issue by sergiotarxz** [GeyserMC/Geyser#4877]
### What feature do you want to see added?

Add to the extensions API a way to filter out users by their getDeviceOs and getName.

Currently there is no way without changing the geyser source code to allow only lists of devices and names to connect and changing the source code implies harder server mainteinance.

### Are there any alternatives?

Implement a whitelist of usernames and devices that only applies to a certain instance of Geyser.

**Comment by sergiotarxz** [comment]
I am running a minecraft server that is under a Wireguard VPN, but I made a endpoint to access a console specific geyser instance open to internet, but I do not want no console users to use it and I want to manually approve who can connect to that geyser instance.

 I do not want to bother users in the geyser instance who are using the VPN with the whitelist, but console users should be manually approved by myself.
 
 I have 1 spigot server and 2 standalone Geysers one for VPN and the other for access from internet for consoles.

**Comment by sergiotarxz** [comment]
Floodgate whitelist approach does not fit for me since that means bothering all my users, not only console ones.

**Comment by onebeastchris** [comment]
This is already possible to implement - you can create a [Geyser extension](https://wiki.geysermc.org/geyser/extensions/), which listens to the [`SessionLoginEvent`](https://github.com/GeyserMC/Geyser/blob/master/api/src/main/java/org/geysermc/geyser/api/event/bedrock/SessionLoginEvent.java), and checks a connecting GeyserConnection's [Bedrock Username](https://github.com/GeyserMC/api/blob/master/base/src/main/java/org/geysermc/api/connection/Connection.java#L46) or [BedrockPlatform](https://github.com/GeyserMC/api/blob/master/base/src/main/java/org/geysermc/api/connection/Connection.java#L73). You can than cancel the event based on whatever criteria you have.
