### ISSUE TITLE
Translation system for Geyser strings

### ISSUE THREAD

**Issue by rtm516** [GeyserMC/Geyser#489]
**What feature do you want?**
A translation system for Geyser so we can support different languages for hardcoded strings sent to the client. Could be an extension of the current locale system, I will probably look into this.

**Alternatives?**
N/A

**Comment by KotoHacker** [comment]
I made a partial translation into Russian into a slightly outdated version. Translated main messages related to getLogger()
Download: [[click]](https://drive.google.com/open?id=1GmWfsbVBHPT670aP_VC_mfNtggHT_O1N)
