### ISSUE TITLE
MCXboxBroadcast does not work.

### ISSUE THREAD

**Issue by Holy725** [GeyserMC/Geyser#4895]
### Describe the bug

MCXboxBroadcast does not work after installing 2.4.0-SNAPSHOT-621

### To Reproduce

MCXboxBroadcast does not work on PaperMC-1.21-109 server with GeyserMC 2.4.0-SNAPSHOT-621 and floodgate v2.2.3-SNAPSHOT (b109-49bd564)

### Expected behaviour

MCXboxBroadcast functions properly.

### Geyser Version

2.4.0-SNAPSHOT-621

**Comment by Camotoy** [comment]
Hi! Please make an issue over at https://github.com/rtm516/MCXboxBroadcast and provide specific details of what's going on - for example, any errors in the console you're seeing. Thank you!
