### ISSUE TITLE
llama with carpet cannot display carpet 

### ISSUE THREAD

**Issue by cgw2023** [GeyserMC/Geyser#4896]
### Describe the bug

Java is left, Bedrock is right
In geyser bedrock, llama carpet cannot be displayed. But this can be see before, I am not sure when does this start occur after updated geyser/floodgate a few times 
![llama](https://github.com/user-attachments/assets/65107b82-faed-44ea-a204-80925490a53a)

### To Reproduce

1. tame a llama
2. put on carpet

### Expected behaviour

carpet can be see

### Screenshots / Videos

provided above

### Server Version and Plugins

This server is running Folia version git-Folia-"ec6b172" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: ec6b172)

Paper Plugins:
FancyHolograms, FancyNpcs
Bukkit Plugins:
AnnouncerPlus, AntiPopup, ArmorStandEditor, Attollo, AxInventoryRestore, AxShulkers, BedrockPlayerSupport, BetterRTP, BlockLocker, BlueMap
[15:38:59 INFO]: DeluxeMenus, DiscordSRV
DragonDropElytra, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, ExecutableItems, floodgate, FoliaFlow, GHomeGuiForEssentialsX
 GreenChunk, GSit, HeadDatabase, HeadDrop, LuckPerms, Matrix, packetevents, PlaceholderAPI, PlayerWarps, ProtocolLib
QuickShop, QuickShopForm, Residence, ResidenceForm, SCore, ShulkerRespawner, SimpleAutoRestart, SuperHarvest, TAB-Bridge, TimeIsMoney
Vault, ViaBackwards, ViaVersion, WorldEdit, zAuctionHouseV3

### Geyser Dump

https://dump.geysermc.org/LmoJhfbbzy4ZmKmmIMcug72WtWCLzru5

### Geyser Version

2.4.0-b621 (git-master-a85b312) (Java: 1.21、 Bedrock: 1.20.80/1.20.81 - 1.21.2/1.21.3)

### Minecraft: Bedrock Edition Device/Version

Windows 10 bedrock  1.21

**Comment by onebeastchris** [comment]
This seems to be a ViaVersion issue - 1.21 Java clients are also affected.

**Comment by onebeastchris** [comment]
Update ViaVersion to their latest dev build, it's resolved there :)
