### ISSUE TITLE
Option to remember login by storing tokens with encryption

### ISSUE THREAD

**Issue by NinCollin** [GeyserMC/Geyser#4903]
### What feature do you want to see added?

While a similar thing was mentioned in #558, it was dismissed due to tokens stored plaintext server-side, allowing server owners access of saved Microsoft accounts.

My idea is to allow users to remember their login on a server, but require a password to encrypt their token with. Upon reconnect, they can either enter the password, or clear their token and sign in again.

Now, one may wonder what the point of saving a login is if it'll require a password anyways. The big reason is the hassle of signing in with a Microsoft account is that you can't simply copy and paste the login code, and must sign in with email + password, making it much more of a hassle than a single password alone.

### Are there any alternatives?

N/A

**Comment by Camotoy** [comment]
Hi. Thanks for the feature request.

At this time, we're not interested implementing and maintaining such a thing - at this point, you should consider self-hosting your own Geyser-Standalone instance for the best security (and you can add your name to the config to add the token), or look into Floodgate account linking if this is a server you own.

Have a good day!
