### ISSUE TITLE
[Fabric/JE1.21/BE1.21.2.02] "Could not translate packet ..." Error

### ISSUE THREAD

**Issue by Pairman** [GeyserMC/Geyser#4907]
### Describe the bug

On my JE 1.21 fabric server, I configured and set up Geyser-Fabric properly on another port (online-mode enabled). No other mods are installed except for Fabric-API.

After logging in to my Microsoft account with the code prompted, the game will be stuck at "Building terrain".

### To Reproduce

1. Set up Geyser-Fabric on JE 1.21 with online-mode enabled, on another UDP port.
2. Join the proxy server with BE 1.21.2.02, and login with Microsoft account.
3. BE will be stuck at "Building terrain", and server-side is spammed with error tracebacks.

### Expected behaviour

BE should join the server successfully as expected.

### Server Version and Plugins

mcje 1.21
fabric 0.15.11
fabric-api-0.100.6+1.21

### Geyser Dump

https://dump.geysermc.org/HNHG36mxAZLNntDuIZ5G6n0ExBxw5l1C

### Geyser Version

2.4.0-SNAPSHOT (git-DEV-8d4f259)

### Minecraft: Bedrock Edition Device/Version

1.21.2.02, Android 12 arm64

### Additional Context

Geyser 2.4.0-SNAPSHOT (git-DEV-8d4f259) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.2/1.21.3)

[**latest.log**](https://github.com/user-attachments/files/16402419/latest.log)

**Comment by Camotoy** [comment]
Does the latest build fix the issue?

**Comment by Pairman** [comment]
This is fixed now. Thanks.
