### ISSUE TITLE
更新后玩家无法连接服务器

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [GeyserMC/Geyser#4910]
### Describe the bug

![image](https://github.com/user-attachments/assets/dc36facb-0564-4eab-aee5-e76bd0e29b4a)

### To Reproduce

更新你的geyser-bungee

### Expected behaviour

玩家还能进入服务器

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/1136679b-0908-42a8-a663-b72998cf26ca)

### Geyser Version

2.4.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.21.2

**Comment by Camotoy** [comment]
Your BungeeCord server needs to support Java Edition version 1.21.

**Comment by MinecraftEarthVillage** [comment]
> Your BungeeCord server needs to support Java Edition version 1.21.

How should I fix it? If you don't update the geyser plug-in, then the bedrock client can't enter the game, and if you update it, you still can't.

**Comment by Chew** [comment]
Update Bungeecord

**Comment by MinecraftEarthVillage** [comment]
> Update Bungeecord

I have updated to the latest version of bungee.
![image](https://github.com/user-attachments/assets/abaec9ce-2565-4116-9f64-75f11732bc00)

**Comment by Camotoy** [comment]
Install ViaVersion on the backend server.

**Comment by MinecraftEarthVillage** [comment]
> Install ViaVersion on the backend server.

I already have it😭
![image](https://github.com/user-attachments/assets/8711e24e-c4c5-450c-8fb1-5c90a73a9d6f)
Is it because of forge
