### ISSUE TITLE
Transfer Command not Working

### ISSUE THREAD

**Issue by MakiTazo** [GeyserMC/Geyser#4913]
### Describe the bug

The Java Transfer Command it's not working with Bedrock Players.
BDS (Bedrock Dedicated Server) users can use transfer to access any server with Geyser.

### To Reproduce

1. Use the transfer command with a Bedrock Account in the Geyser Java Server
2. It will appear a Minecraft screen with the message "Transferred to another server" with an Accept button.
3. Press "Accept"  and will happen nothing. (Only will exit the server)

### Expected behaviour

The transfer command should work as the Bedrock Edition one, which is responsible for transporting users to other servers (like a proxy, but it is not). 

### Geyser Dump

https://dump.geysermc.org/kzyxWaPTvKrP6agcTWMy89SQvsDdPH6q

### Geyser Version

2.4.0-b625 (git-master-258d6aa)

### Minecraft: Bedrock Edition Device/Version

Bedrock: 1.20.80/1.20.81 - 1.21.2/1.21.3

**Comment by onebeastchris** [comment]
See https://github.com/GeyserMC/Geyser/issues/4677#issuecomment-2119354468 for reference, and https://github.com/GeyserMC/Geyser/issues/4677#issuecomment-2145832132 for how to properly configure transfers with Geyser.
