### ISSUE TITLE
Villagers not showing trades (nintendo switch issue maybe?)

### ISSUE THREAD

**Issue by StinkyPinky045** [GeyserMC/Geyser#4915]
### Describe the bug

Villagers trades apear invisable

### To Reproduce

Open any villager with a job on nintendo switch.

### Expected behaviour

See what u are about to trade

### Screenshots / Videos

![07d971aa-e2bc-4093-a89c-d12a34d2bd18](https://github.com/user-attachments/assets/5689b1ae-9895-4127-bbc5-86b89d30efed)

### Server Version and Plugins

version [21:37:11 INF0]: Checking version, please wait... [21:37:12 INFO]: This server is running Paper version 1.21-117-master@0246a9d (2024-07-29T00:51:10Z) (Implementing API version 1.21-RO.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/8Ey6BuQvYvLxkibXbfB86ew4FAXq0Z7H

### Geyser Version

Geyser version 2.4.0-b626 (git-master-45f96a0)

### Minecraft: Bedrock Edition Device/Version

1.20.2 nintendo switch

**Comment by StinkyPinky045** [comment]
Bedrock edition version 1.21.2 nintendo switch*

**Comment by StinkyPinky045** [comment]
Only running CMI and CMILIB on paper server

**Comment by onebeastchris** [comment]
Are this "normal" vanilla villagers, or are they spawned by a plugin?
For the latter, please provide replication steps. Further, please test whether 1.21 Java clients are able to see the trades.

**Comment by StinkyPinky045** [comment]
Hi, i am going to close this. As it was a user error. Something with my texture pack is messing with villagers. Sorry
