### ISSUE TITLE
Sending a large number of data packets to the player's IP

### ISSUE THREAD

**Issue by enderLuoxh** [GeyserMC/Geyser#4918]
### Describe the bug

Regularly, even after restarting the server, Geyser will continue to send data packets to a random player IP until the network is full, and then the Bedrock version player will start to experience latency spikes and disconnections

### To Reproduce

Geyser did not report any errors. The occurrence of this problem is uncertain, but it occurs dozens of times within a day, which has a significant impact on server gameplay

### Expected behaviour

Stop Geyser from sending a large number of data packets to a certain player, causing all players in the Bedrock version to disconnect

### Server Version and Plugins

Current Purpur Version: 1.21-2275-82ccc76 (MC: 1.21)*

[18:34:37 INFO]: Paper Plugins: (1):
[18:34:37 INFO]:  - HuskHomes
[18:34:37 INFO]: Bukkit Plugins: (32):
[18:34:37 INFO]:  - AuthMe, Backuper, BedrockPlayerSupport, Coins, Dominion, Economy, Essentials, ExcessCleanup, floodgate, Geyser-Spigot
[18:34:37 INFO]:  GiftPack, KcLoginGui, KissKiss, LagFixer, LegendaryDailyQuests, LegendaryGuild, LiteSignIn, LuckPerms, Matrix, MiniMOTD
[18:34:37 INFO]:  packetevents, PlaceholderAPI, PlayerJoinMessage, PlayerTitle, ProtocolLib, QuickMenu, squaremap, TAB, UltimateShop, Vault
[18:34:37 INFO]:  YukiNoaAPI, Zhpb

### Geyser Dump

https://dump.geysermc.org/Wzbq1f7nIJ5ipKdZ6AeERyRWxlT7doPu

### Geyser Version

Geyser version 2.4.0-b626 (git-master-45f96a0) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.2/1.21.3)

### Minecraft: Bedrock Edition Device/Version

1.21.2

**Comment by oldsheep0205** [comment]
I have the same issue, once bedrock player logged into server, only 3 minutes later the whole server will crash

**Comment by enderLuoxh** [comment]
I am a server, but due to strange external transmission, the entire server network freezes and all players disconnect

**Comment by oldsheep0205** [comment]
when some bedrock players join the game, the backstage will show "resending teleport x " all the time, then the server crashed

**Comment by onebeastchris** [comment]
What's the underlying data that makes you think that Geyser is sending huge amounts of packets? Are you looking at packet logs? Please provide more information - so far, there's little information for us to start diagnosing this issue.

**Comment by enderLuoxh** [comment]
I'm very sorry, here is the task manager and detailed network connection data of my computer when geyser was offline. You can see a large number of udp connections. Then I reloaded geyser, and the problem temporarily disappeared. It can be ruled out that it was caused by too many players, because all players had already been disconnected due to high latency when geyser was offline. There were no errors reported in the geyser backend

![Image_1722468483214](https://github.com/user-attachments/assets/573b56d4-08a7-4bee-beb4-9267f630b9bd)

![Image_1722468483214](https://github.com/user-attachments/assets/10f9ca16-32a5-4698-b87a-f7a12c678b83)

![Image_1722468502306](https://github.com/user-attachments/assets/93b4b4cd-b4d8-47ed-a139-f505ed1466e1)

![Image_1722468497917](https://github.com/user-attachments/assets/5e03d0d1-be8d-4359-bb8b-3e0b17aee2db)

**Comment by enderLuoxh** [comment]
![Screenshot_20240801_222032_com microsoft rdc androidx](https://github.com/user-attachments/assets/38a78621-21ee-4746-941e-f6a1fefa8acf)
![Screenshot_20240801_222036_com microsoft rdc androidx](https://github.com/user-attachments/assets/7084dc68-b4a2-4782-a2fe-bf1f77b83e6a)
The above two pictures are the error logs I just found when geyser was sending a large number of packets

**Comment by onebeastchris** [comment]
Following up on this - is this still occurring?
If it is, please provide said pcap file :)

**Comment by onebeastchris** [comment]
Closing due to no further response. If this is still occurring, please provide more data as requested!
