### ISSUE TITLE
cannot login from Bedrock side

### ISSUE THREAD

**Issue by oldsheep0205** [GeyserMC/Geyser#4919]
### Describe the bug

I have a 1.21 fabric server with fabric-api-0.100.8+1.21 and geyser 2.4.0-b627. my bedrock client version is 1.21.2, when I try to connect, it always showed "cannot connect to the world."

### To Reproduce

1. download fabric and fabric-api-0.100.8+1.21.
2. open geyserMC, click "download", click "fabric"
3. open fabric server.
4. use 1.21.2 windows bedrock mc to connect the server 

### Expected behaviour

Backstage does not have any infomation about my connection.

### Geyser Version

2.4.0-b627 (git-master-efe2736)

### Minecraft: Bedrock Edition Device/Version

1.21.2

**Comment by onebeastchris** [comment]
"Unable to connect to world" is a typical configuration issue. Please see https://geysermc.org/wiki/geyser/setup/ for setup instructions - if you face further issues, please take a look at other troubleshooting guides on our wiki, or join our discord for help. Thanks!
