### ISSUE TITLE
Can Bedrock Addon support Java Mod Entity

### ISSUE THREAD

**Issue by superwfox** [GeyserMC/Geyser#4923]
### What feature do you want to see added?

Through the Addon package of the bedrock version, the mod entity of the Java version is translated to the bedrock version client, so as to realize the Java module of the bedrock version client.

### Are there any alternatives?

just imagine

**Comment by onebeastchris** [comment]
This will not be done automatically by Geyser, but Hydraulic may be able to do that in the future. We're working on a custom entity api - although not too actively lately - so eventually, this will be possible. 
I'll close this issue as automatic transaction of mod entities won't be done within Geyser, but maybe at some point in hydraulic. Thanks for the suggestion!
