### ISSUE TITLE
Items in a TrMenu can be removed from the container

### ISSUE THREAD

**Issue by Noogear** [GeyserMC/Geyser#4928]
### Describe the bug

I can't interact in the chest menu, please help! Thanks a lot!

### To Reproduce

[menu.zip](https://github.com/user-attachments/files/16472014/menu.zip)
Menu file as above

the trmenu: https://github.com/Dreeam-qwq/TrMenu

### Expected behaviour

When I interact with items in the menu, I only drag items into the backpack, No commands will be executed

### Server Version and Plugins

paper 1.20.4

### Geyser Dump

https://dump.geysermc.org/aV4G5i2BAxTUo6IwMnWhT54BAr5XoKkN

### Geyser Version

2.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

pe: 1.21.2.02

**Comment by onebeastchris** [comment]
Can you send a video of how the menu works on a Java 1.21 Client, and what it's doing on a 1.21 Bedrock client?

**Comment by RAURORA2** [comment]
> Can you send a video of how the menu works on a Java 1.21 Client, and what it's doing on a 1.21 Bedrock client?

the trmenu is currently having problems in java1.21, so I'm using version 1.20.4

This is how it looks in bedrock1.21

https://github.com/user-attachments/assets/fd428e29-a96f-48dd-b5af-5227bea83b1a

**Comment by onebeastchris** [comment]
The reason why I'm asking about a Java 1.21 Client is because Geyser emulates one - you don't need to change the server version to test that.

**Comment by RAURORA2** [comment]
> The reason why I'm asking about a Java 1.21 Client is because Geyser emulates one - you don't need to change the server version to test that.

I'm so sorry, that's my problem. The following are additions to java1.21 Client.

https://github.com/user-attachments/assets/cc1b96e0-27da-47cb-ac45-ff4e3d34caeb

**Comment by Noogear** [comment]
The problem of the menu plugin
