### ISSUE TITLE
Spigot - Can't break blocks with the same username with floodgate

### ISSUE THREAD

**Issue by ZARSYNTEX** [GeyserMC/Geyser#493]
**Describe the bug**
Can't break blocks as *ZARSYNTEX only if ZARSYNTEX (Java) ist connected.

ZARSYNTEX is the java account
*ZARSYNTEX is the bedrock account

**To Reproduce**

Install spigot server
Load plugin
Connect with PE -> can't break blocks
Connect with Java -> now PE can break blocks

Server Version
latest spigot(1.15.2

Geyser Version
1.0-SNAPSHOT (05.05.2020 commit)

Minecraft: Bedrock Edition Version
1.14.60 PE on Android / Windows 10

**Comment by DoctorMacc** [comment]
If you're able to test PRs, could you test #490 and see if the problem persists?

**Comment by robinfre** [comment]
I'm not in Java, maybe if someone give me another commit I can try it ;)

**Comment by ZARSYNTEX** [comment]
You made it! It works I downloaded the the .jar and everything is working!!
