### ISSUE TITLE
When I enter the server with Bedrock Edition, the server crashes

### ISSUE THREAD

**Issue by Hzm20** [GeyserMC/Geyser#4931]
### Describe the bug

When I enter the server with Bedrock Edition, the server crashes

### To Reproduce

no

### Expected behaviour

I'm a Chinese gamer
I  found out today that when I enter a server with Bedrock Edition, the server crashes
This question arose a few days ago
This issue affects me a lot to play the game
I hope you guys can solve it soon
Here are my server crash logs

### Geyser Version

2.4.1-spigot

### Minecraft: Bedrock Edition Device/Version

Bedrock Edition，1.21.2.02,andriod

**Comment by Hzm20** [comment]
[Uploading 2024-08-03-1.log…]()

**Comment by Hzm20** [comment]
[2024-08-03-1.log](https://github.com/user-attachments/files/16479143/2024-08-03-1.log)

**Comment by Hzm20** [comment]
[2024-08-03-1.zip](https://github.com/user-attachments/files/16479377/2024-08-03-1.zip)

**Comment by onebeastchris** [comment]
This issue is caused by reloading, which generally isn't supported.
Please restart the server, and it'll work fine.
