### ISSUE TITLE
player cant spawn in nether world.

### ISSUE THREAD

**Issue by sleepingmagg** [GeyserMC/Geyser#4938]
### Describe the bug

if mobs attack a player and he leaves, the player enters the server and cannot move, and if he is killed in this state, this bug occurs

### To Reproduce

player cant spawn

### Expected behaviour

player can spawn

### Screenshots / Videos

![Screenshot_2024-08-05-20-14-35-778_com mojang minecraftpe](https://github.com/user-attachments/assets/e5af6a3f-6ff5-45e3-8b99-bbb90c018745)

### Server Version and Plugins

worldedit, placeholderapi,vault,towny,townymap,flagwar,betterrtp,citizens,PI3xmap,AutoMessage,RogueParkour,GeyserExtras,EzsentialXSpawn,EssentialX,TAB,Jobs,multiverse-core,luckperms,chestshop,townychat,bedrockplayersupport,floodgate - latest version, geyser-spigot

### Geyser Dump

https://dump.geysermc.org/waseamxN8mP7FfC7bAJNRacloaNkHgIp

### Geyser Version

2.4.0-b617

### Minecraft: Bedrock Edition Device/Version

1.21.2, Android

### Additional Context

the player cannot spawn when the server is restarted and remains in this state forever.and i cant kill,tp and others to a player with this state,at the same time the player hears the environment around him

**Comment by onebeastchris** [comment]
Please try updating Geyser, this should be resolved in the latest version.

**Comment by sleepingmagg** [comment]
> Попробуйте обновить Geyser, эта проблема должна быть решена в последней версии.

Dont fixed
![Screenshot_2024-08-05-21-01-48-943_com mojang minecraftpe](https://github.com/user-attachments/assets/a728f70d-8111-4467-93be-82643d1dfcb9)

**Comment by onebeastchris** [comment]
please run `geyser version ` in the console, and send the output here

**Comment by sleepingmagg** [comment]
[21:04:08 INFO]: На этом сервере Geyser версии 2.4.1-b634 (git-master-61ae5de) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.2/1.21.3)

**Comment by Camotoy** [comment]
Did you run the Geyser dump when players were on the server?

**Comment by sleepingmagg** [comment]
> Вы запускали сброс Гейзера, когда игроки были на сервере?
yes

**Comment by sleepingmagg** [comment]
> How are you connecting to your Geyser server? Are you directly connecting, or are you using GeyserConnect?

directly connecting

**Comment by onebeastchris** [comment]
The geyser dump you sent shows no connections while taking it, nor does it show any connection attempts at all.
Please join the server, and run/send a new `geyser dump` while connected to it

**Comment by sleepingmagg** [comment]
> The geyser dump you sent shows no connections while taking it, nor does it show any connection attempts at all. Please join the server, and run/send a new `geyser dump` while connected to it

IDK. I have velocity, hub-server, and base - server, so I’m dumping all 3 servers
Velocity dump:
https://dump.geysermc.org/Yk9GVf0ySMHHCPockCkE91vxq7pByxxO
Hub dump:
https://dump.geysermc.org/zIDM0XW25PWVaBKKqglrIF6PY459aLJ2
Base dump:
https://dump.geysermc.org/SU0q1rXzxTsETywD7gGvUrjUwwaHU3dQ

**Comment by onebeastchris** [comment]
And there's the issue - you should only install Geyser on the proxy server, *not* the backend one's. See our setup guide for reference: https://geysermc.org/wiki/geyser/setup/

Please uninstall Geyser from all servers except the proxy, and update Geyser on the proxy.

**Comment by sleepingmagg** [comment]
> И вот в чем проблема - Geyser нужно устанавливать только на прокси-сервере, _а не_ на бэкенд-серверах. Смотрите наше руководство по настройке для справки: https://geysermc.org/wiki/geyser/setup/
> 
> Пожалуйста, удалите Geyser со всех серверов, кроме прокси-сервера, и обновите Geyser на прокси-сервере.

THANK YOU
