### ISSUE TITLE
Breaking animation doesn't match up when in water

### ISSUE THREAD

**Issue by Heath123** [GeyserMC/Geyser#494]
**Describe the bug**

Breaking takes longer in water, but this is not reflected in break times. This means that the block doesn't break after the animation finishes.

**To Reproduce**

1) Join with Geyser
2) Go underwater
3) Try to break a block

**Expected behavior**
The animation should match up.

**Screenshots / Videos**
A screenshot can't really show it. A video would but this is easy to reproduce/imagine

**Server Version**
Paper version git-Paper-245 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
This is currently the latest

**Geyser Version**
Geyser-Bukkit PR #490 as this fixes breaking, but it should happen on any version

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
This isn't easy to solve without chunk caching because you don't know if the player is in water

**Comment by endevrr** [comment]
Confirmed, I knew this when I submitted the block breaking pr, "This isn't easy to solve without chunk caching because you don't know if the player is in water", is absolutely correct
