### ISSUE TITLE
need help with geyser

### ISSUE THREAD

**Issue by ImNotVirgola** [GeyserMC/Geyser#4946]
### Describe the bug

Despite i set in the right way the plugin for letting bedrock users to join in my server, it doesn't do that. I tried everything and reset the setting several times, but it didn't work

### To Reproduce

1. Open Minecraft Bedrock edition
2. Go to Server list
3. Add "vianshade.ddns.net" server with 25565 port
4. Try to connect
5. It says "Impossible connecting to the world"

### Expected behaviour

Let a Bedrock edition Minecraft user to join in my server

### Server Version and Plugins

This server is running CraftBukkit version 4287-Spigot-fb8fb72-759061b (MC: 1.21) (Implementing API version 1.21-R0.1-SNAPSHOT)
plugins added on the server:
![immagine_2024-08-07_171724866](https://github.com/user-attachments/assets/657a383b-e69c-4dcc-a5fa-14b2ba0a981b)

### Geyser Dump

https://dump.geysermc.org/Ubo76zPKb5g2BY6tiqg3QBtTozZSXn33

### Geyser Version

Geyser version 2.4.1-b634 (git-master-61ae5de)

### Minecraft: Bedrock Edition Device/Version

1.21.2, PC

**Comment by onebeastchris** [comment]
This is likely a common configuration issue. Please see our setup guide for help: https://geysermc.org/wiki/geyser/setup/

For further questions, please join our discord and ask questions there - we don't provide support via GitHub.
