### ISSUE TITLE
Mangrove sapling does not appear grown on Bedrock

### ISSUE THREAD

**Issue by Zegery** [GeyserMC/Geyser#4949]
### Describe the bug

The mangrove saplings appear in the first growth stage when viewed on Bedrock even if they have grown.

### To Reproduce

Find a grown Mangrove sapling hanging from the tree
Observe on Bedrock that it appears to not be grown

### Expected behaviour

It should appear at the proper growth stage on Bedrock.

### Screenshots / Videos

https://github.com/user-attachments/assets/78ae1f3f-c723-4c99-8e7b-a22ab572fdc0

### Server Version and Plugins

Fabric 1.21

### Geyser Dump

https://dump.geysermc.org/GWuQNcix9f8skdsoYFO0mfZAgNdiWBDD

### Geyser Version

2.4.1-b633

### Minecraft: Bedrock Edition Device/Version

1.21.2 Windows

### Additional Context

The issue appears on all Bedrock devices

**Comment by Camotoy** [comment]
Without testing in-game, this seems plausible. Bedrock has several stages we ignore at the moment.

**Comment by Camotoy** [comment]
Once 1.21.20 support is added into Geyser, this bug will be fixed for all Bedrock versions.
