### ISSUE TITLE
Players cant join server

### ISSUE THREAD

**Issue by Rj979** [GeyserMC/Geyser#4950]
### Describe the bug

After the latest update cant join servers showing unable to connect to world , config is proper and port has udp on it 

### To Reproduce

1. Get latest update [8d1e9e9](https://github.com/GeyserMC/Geyser/commit/8d1e9e95ef89e12b05fdb8fdb7561c1fecf2a0c4)
2. Get latest floodgate
3. start a paper server with 12 gb ram with Amd epyc having 4 cores
4. setup and restart

### Expected behaviour

After proper setup players should be able to join connect and play 

### Screenshots / Videos

![pK5c59t](https://github.com/user-attachments/assets/7719aea6-0d9c-479c-8136-bc98d1cf05d4)

### Server Version and Plugins

 Paper version 1.21-2-master@b4b8208 (2024-06-18T00:51:08Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
 Floodgate version 2.2.3-SNAPSHOT (b109-49bd564)
 Geyser version 2.4.1-SNAPSHOT

### Geyser Dump

https://dump.geysermc.org/1MhyJSiMf0srRANaL4Epbgb0kkIoAKUM

### Geyser Version

2.4.1-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.21.2 S21 Ultra

### Additional Context

having this problem since last 3 updates and all staff are avoiding this question and all query related about it

**Comment by Camotoy** [comment]
Have you tried rolling back your Geyser build and seeing if that is functional? I.E. https://github.com/GeyserMC/Geyser/actions/runs/10229053870

**Comment by Rj979** [comment]
> Have you tried rolling back your Geyser build and seeing if that is functional? I.E. https://github.com/GeyserMC/Geyser/actions/runs/10229053870

how many build back is that?

**Comment by Camotoy** [comment]
About five.

**Comment by Rj979** [comment]
> About five.

trying rn give me 10 mins

**Comment by Rj979** [comment]
> Have you tried rolling back your Geyser build and seeing if that is functional? I.E. https://github.com/GeyserMC/Geyser/actions/runs/10229053870

Nope dosent work , here are the logs
https://dump.geysermc.org/wUrhkkdSEHs2HhYJOUaGmH8jxApuPQvD
https://mclo.gs/lu45qT4

**Comment by onebeastchris** [comment]
This looks like a common configuration issue, or potential client issue if the connectiontest command is working properly. Hence, please re-visit our configuration guide on the wiki, look at the troubleshooting steps, and then test if you're able to join other servers.
We didn't change anything connection related in the recent updates, which is also apparent since rolling back the Geyser build did not change the outcome.

For further help, please join our discord, and ask for help there - we use GitHub issues for bug reports and feature requests only. Thanks!

**Comment by Rj979** [comment]
[config.txt](https://github.com/user-attachments/files/16540306/config.txt)
[config (2).txt](https://github.com/user-attachments/files/16540307/config.2.txt)


whenever you run outta reasons you start yappin with the "This looks like a common configuration issue,"

**Comment by onebeastchris** [comment]
Because it quite literally is. As I've said already, please join our discord, and we'll help there.
