### ISSUE TITLE
GeyserMC - Spawn doesn't reflect paper MC coordinates.

### ISSUE THREAD

**Issue by monckey100** [GeyserMC/Geyser#4956]
I have isolated the issue, bedrock players will spawn at the highest block possible and will avoid lower blocks if there is a higher block present. To resolve this, I placed a block into the sky and used a command block that will TP any users nearby to the correct spawn point.

_Originally posted by @monckey100 in https://github.com/GeyserMC/Geyser/issues/1496#issuecomment-2278693089_

**Comment by Camotoy** [comment]
Thank you for creating an issue. However, please create an issue using the template and fill in all the details - that way, we can diagnose the issue properly with all the variables you have in your setup.
