### ISSUE TITLE
maven cant find MinecraftAuth dependency

### ISSUE THREAD

**Issue by Wolf2323** [GeyserMC/Geyser#4961]
### Describe the bug

Since version [2.4.1-SNAPSHOT](https://github.com/GeyserMC/Geyser/commit/41e65b0fcc5d4c905b4c6bc21a25d3c7b464ba81) MinecraftAuth is not fetched anymore from Maven central , instead it is now fetched from https://s01.oss.sonatype.org/content/repositories/snapshots/

### To Reproduce

1. Depend on org.geysermc.geyser:Velocity 2.4.1-SNAPSHOT
2. let maven resolve all dependencies

### Expected behaviour

All dependencies and transitive dependencies should be fetched

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/bbea65b6-f661-45a1-bc93-8f7077c4f8f3)
https://discord.com/channels/613163671870242838/613170125696270357/1272879310893617222
![image](https://github.com/user-attachments/assets/e54e36ab-e55d-46ef-8bed-bb1fd245a8e0)

### Geyser Version

2.4.1-SNAPSHOT

**Comment by onebeastchris** [comment]
The only dependency that's intended to be consumed by other projects is the geyser api module, not the core or project specific ones - personally I don't see why or how we should fix this.

You can either add the repos on your end, or exclude that transitive dependency on your end
