### ISSUE TITLE
Could not load plugin from file plugins/Geyser-BungeeCord(3).jar

### ISSUE THREAD

**Issue by wiltark** [GeyserMC/Geyser#4964]
### Describe the bug

The server encountered an error when attempting to load the plugin Geyser-BungeeCord(3).jar. The error is a java.util.zip.ZipException indicating that the ZIP end header of the JAR file is missing or corrupted. This suggests that the file may be incomplete or damaged, preventing the server from properly loading and initializing the plugin.

### To Reproduce

Place the Geyser-BungeeCord(3).jar file into the plugins directory of the server.Restart or reload the server.Observe the server logs for the warning message about the plugin loading failure.

### Expected behaviour

The plugin Geyser-BungeeCord(3).jar should load without errors upon server startup. The server should recognize and initialize the plugin, and no warnings related to file corruption should appear in the logs.

### Geyser Version

Build #647 

### Minecraft: Bedrock Edition Device/Version

1.21.20

**Comment by onebeastchris** [comment]
Re-download Geyser, this sounds like a corrupted download on your end
