### ISSUE TITLE
Custom enchantments are not visible

### ISSUE THREAD

**Issue by ChrisTVH** [GeyserMC/Geyser#4965]
### Describe the bug

Custom enchantment plugins from 1.20.6 onwards use minecraft's vanilla system to display these enchantments in the tooltip, these enchantments cannot be seen in books or objects.

### To Reproduce

In my case to have custom enchantments on my server I use excellent enchants.

### Expected behaviour

To be displayed correctly in the enchantment on bedrock clients.

## Proxy
- Velocity 3.3.0-SNAPSHOT (git-00ed2284-b415)
- plugins: advancedserverlist, awd, cmiv, commandwhitelist, floodgate, geyser, geyserextras, litebans, luckperms, nantibot, nlogin, vpacketevents, onetimepack, skinsrestorer, tebex
## Backend
- UniverseSpigot version 1.21-DEV-ver/1.21@c1a9d30
### Paper Plugins:
- CarbonChat, FancyNpcs
### Bukkit Plugins:
- AntiPopup, CataMines, ChatColor2, ChatSentinel, Chunky, ChunkyBorder, CMI, CMILib, CoinsEngine, CommandPanels
- CommandWhitelist, CoreProtect, DeluxeCombat, ExcellentCrates, ExcellentEnchants, Fadah, FastAsyncWorldEdit, floodgate, GadgetsMenu, GeyserExtras
- GrimAC, ItemEdit, ItemTag, Jobs, LiteBans, LuckPerms, Multiverse-Core, nightcore, PlaceholderAPI, ProtectionStones
- ProtocolLib, RealisticSeasons, ShopGUIPlus, ShopGUIPlus-SellGUI, TAB, Tebex, ToastedAFK, UltimateClans, Vault, ViaBackwards
- ViaVersion, WorldGuard

### Geyser Dump

https://dump.geysermc.org/cXTgaRvl3GUclkpX2gfmZgNp0GnjboMr

### Geyser Version

Geyser 2.4.2-b647 (git-master-0bc39d5)

### Minecraft: Bedrock Edition Device/Version

1.21.20

### Additional Context

Here I also deposit the error that appears when the custom enchantment package cannot be translated.
https://mclo.gs/XAvOcka

**Comment by onebeastchris** [comment]
Hey! Thanks for reporting the issue.
Could you try and run the build found under the "checks" section of the following pull request: https://github.com/GeyserMC/Geyser/pull/4849? It might just resolve this issue. Thanks!

**Comment by ChrisTVH** [comment]
> Hey! Thanks for reporting the issue. Could you try and run the build found under the "checks" section of the following pull request: #4849? It might just resolve this issue. Thanks!

I am about to try it right now, I will be telling you about the results.

**Comment by ChrisTVH** [comment]
Now there is no error in proxy, but it is still not visible.
![image](https://github.com/user-attachments/assets/b88fcafb-3055-41ad-b7be-3cd45b30dc09)

This is what it looks like in java.
![image](https://github.com/user-attachments/assets/c8c8cd91-5b96-4cd6-8ae7-7bbd0fb45d4d)

**Comment by ChrisTVH** [comment]
Resubmitting, because they have forgotten.
