### ISSUE TITLE
Internal error when trying to create a custom banner

### ISSUE THREAD

**Issue by ChrisTVH** [GeyserMC/Geyser#4972]
### Describe the bug

One of my players is working on creating a custom flag, but when he did it, the server banned him with this message:
![image](https://github.com/user-attachments/assets/1ec86a62-e68b-4766-ac73-8665ab275200)

### To Reproduce

Create a banner, then enter the banner customization table and try to make one.

### Expected behaviour

It is mandatory to put something here, but it is already obvious.

### Screenshots / Videos

https://github.com/user-attachments/assets/134884b7-b76e-4ccc-91ab-9bfc7e8b2310

### Server Version and Plugins

Is a fork of Purpur/Pufferfish: UniverseSpigot version 1.21-DEV-ver/1.21@a62044c

### Geyser Dump

https://dump.geysermc.org/OqWzO8hgIlpy8fzGiZh2Mj0UhwxH2K6l

### Geyser Version

Geyser 2.4.2-SNAPSHOT (git-DEV-5d11140)

### Minecraft: Bedrock Edition Device/Version

1.21.21

**Comment by Kas-tle** [comment]
Please try:
1. Reproducing with the vanilla java client
2. Reproducing with Paper

**Comment by Kas-tle** [comment]
Also I just noticed you are using a fork of Geyser. Please use the build from our downloads page: https://geysermc.org/download/

**Comment by ChrisTVH** [comment]
I tested it with the version  Geyser 2.4.2-b650 (git-master-7da1d7d)
It remains exactly the same, I will try it later on my other server when I have time, but probably the result will be the same, after all my fork does not modify anything related to the vanilla logic of the game.

**Comment by Frostbite593** [comment]
This happened to me too on bedrock

**Comment by ophelovie** [comment]
i can also reproduce this issue on geyser standalone 2.4.2-b650 (git-master-7da1d7d)
when a player interacts with a loom they get disconnected from the world.

**Comment by Camotoy** [comment]
Issue has been pinpointed to a decoding error for inventory requests.

**Comment by Kharakhov** [comment]
I have this same issue. I tried on a paper server latest version (1.21.1) with no plugins other than geyser and floodgate, and latest bedrock version, after freshly redownloading both geyser and floodgate. The issue still occurred.
