### ISSUE TITLE
Support shouldAuthenticate = false field of ClientboundHelloPacket

### ISSUE THREAD

**Issue by masmc05** [GeyserMC/Geyser#4987]
### What feature do you want to see added?

Currently if I want to create encryption between geyser and the java server, the current error is printed
```
[geyser]: Cannot reply to ClientboundHelloPacket without profile and access token.
```

But that's needed only if the server forces to login to Mojang servers, while with the floodgate's detecting of geyser, this can be disabled

### Are there any alternatives?

An alternative would be to leave as it is, but if minecraft now supports this encryption, don't see why not use it

**Comment by Camotoy** [comment]
Is there a way we can replicate this behavior?

**Comment by onebeastchris** [comment]
Reopening - the mcpl dependency needs to be bumped in geyser first

**Comment by onebeastchris** [comment]
MCPL was bumped in https://github.com/GeyserMC/MCProtocolLib/issues/823; so this should be now supported. Thanks for your PR!
