### ISSUE TITLE
PE rains but JavaEdition doesn't rain

### ISSUE THREAD

**Issue by BeeAZ-pm-pl** [GeyserMC/Geyser#4990]
### Describe the bug

If you use the command, it will rain on both sides, but if it's random, sometimes PE will rain and JE won't rain

### To Reproduce

Random

### Expected behaviour

**It rains on both sides at the same time, not on each PE**

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/6f013824-984f-4a3f-8405-aff7f0cb1a44)
![image](https://github.com/user-attachments/assets/ce5e50cc-1338-4e0d-ba13-cb4a6a229e23)

### Geyser Version

latest

### Minecraft: Bedrock Edition Device/Version

1.21.x

**Comment by onebeastchris** [comment]
Duplicate of https://github.com/GeyserMC/Geyser/issues/3679
