### ISSUE TITLE
Crosbow bugging

### ISSUE THREAD

**Issue by KotoHacker** [GeyserMC/Geyser#500]
Crossbow with enchantment "Quick Charge 3" is bugging and this summon a infinity reload if u holding a RMB. This bug there is and on the phones.

Video: [[click]](https://youtu.be/8e8yeWlmYnY)

**Server version**
1.15.2 Paper

**Geyser version**
[#125](https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/125/)

**Bedrock version**
1.14.60

07/05/2020 - 12:00 - GMT+ (Moscow +3)

**Comment by Chew** [comment]
I have this issue. The Crossbow "Charged" state isn't being sent to the client I assume. Very annoying! Even when you charge it says it isn't, but it is

**Comment by DoctorMacc** [comment]
Probably fixed by #1359 - however the Bedrock animation will look weird as it stops loading when done while Java can hold while loading as long as it wants.
