### ISSUE TITLE
bedrock player cant sleep

### ISSUE THREAD

**Issue by cath7ARSE** [GeyserMC/Geyser#5001]
### Describe the bug

My only bedrock player on the server is unable to sleep as they described it 
"I haven’t been able to sleep the past few days whenever I click on a bed it just glitches like it lets me sleep for a second and then it stops and it’s still nighttime"

### To Reproduce

Not sure whats causing this i was able to replicate it on my own bedrock client as well.

### Expected behaviour

to sleep?

### Screenshots / Videos

https://github.com/user-attachments/assets/70465b8a-f69b-43c4-be5f-c8a636f72333

### Server Version and Plugins

[20:11:32] [Server thread/INFO]: This server is running Geyser version 2.4.2-b658 (git-master-8356b63) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.20/1.21.21)
[20:11:32] [Server thread/INFO]: Checking version, please wait...
[20:11:32] [Server thread/INFO]: No updates available.

Here's a list of my mods and data packs (yes, I've tried disabling server sleep)
![image](https://github.com/user-attachments/assets/27392caf-0ca5-418e-90f5-03d3e7ab0bdb)
![image](https://github.com/user-attachments/assets/35f9d96b-3351-459e-86aa-59d7f7953f9c)
![image](https://github.com/user-attachments/assets/4ff1d34f-66b6-4406-a17d-92306d4f4eb7)

### Geyser Dump

https://dump.geysermc.org/byjLmwrVcWvwoKR8yj15J1LGZCpKjmMG

### Geyser Version

geyser-fabric-Geyser-Fabric-2.4.2-b658

### Minecraft: Bedrock Edition Device/Version

tested on Windows Edition v1.21.22

**Comment by Dr-Kasuka** [comment]
Second this issue.
Have an Apex Hosting server. Issue is specific to those that are [geyser].

**Comment by Goldenfire644** [comment]
This is happening on my Fabric server as well.
Server host: Aternos
![image](https://github.com/user-attachments/assets/54a0cae7-806f-49c4-800f-619136d8b182)
![image](https://github.com/user-attachments/assets/026a5fc1-50e6-4018-bb14-881f7da59096)
These are the versions of the mods I have installed (the latest versions for 1.21.1)
