### ISSUE TITLE
Geyser-Velocity fails to register commands when players join immediately

### ISSUE THREAD

**Issue by DarkChromaMC** [GeyserMC/Geyser#5005]
### Describe the bug

Experiencing an issue where running the MCXBoxBroadcast extension on the production proxy causes the GeyserMC plugin to malfunction, preventing players from connecting. This problem does not occur on a test proxy under identical conditions on the same machine.

### To Reproduce

1. Add the MCXBoxBroadcast extension on the production proxy.
2. Observe that players are unable to connect to the server, and an error is generated.

### Expected behaviour

The MCXBoxBroadcast extension should not interfere with the functionality of the GeyserMC plugin, allowing players to connect without issues.

### Server Version and Plugins

- **Velocity Version:** 3.3.0-SNAPSHOT (git-09f687e5-b413)
- **Server Version:** Minecraft 1.21.1

### Geyser Dump

https://dump.geysermc.org/F1pO1epHwYtOsHFDBL67H3EyBvIqS3sV

### Geyser Version

**Geyser Version:** 2.4.2-b658 (git-master-8356b63) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.20/1.21.21)

### Additional Context

- A similar setup on a test proxy and sub-server does not reproduce the issue, suggesting the problem is specific to the production environment or the way GeyserMC handles rapid player connections.
- Attempts to mitigate the issue by whitelisting the hub server to control the rate of player connections were unsuccessful.

Logs:
[2024-08-28-7.log](https://github.com/user-attachments/files/16786662/2024-08-28-7.log)
https://mclo.gs/seaeusw

**Comment by onebeastchris** [comment]
Please report this issue to MCXboxBroadcast - if it's causing connections to fail, it would need to address it. Thanks!

**Comment by DarkChromaMC** [comment]
I have already reported it but its related to how GeyserMC software is coded:

"I believe this is due to players immediately connecting once Velocity binds, and the way Geyser is currently setup leads to its command registration being somewhat "interrupted""

**Comment by onebeastchris** [comment]
Just re-checked the log; i see it now - that has nothing to do with mcxboxbroadcast.

**Comment by onebeastchris** [comment]
IIRC this would happen if players connect to the proxy while Geyser hasn't fully started yet - that should be resolvable on Geyser's side by registering commands at an earlier stage.

**Comment by Konicai** [comment]
Yes, that quote was of me

**Comment by JerichoTorrent** [comment]
Any update on this?

**Comment by Konicai** [comment]
Its on the list - this issue will be closed when it has been fixed

**Comment by JerichoTorrent** [comment]
Is there a build I can revert to that allows players to late on the latest bedrock protocol but doesn't break due to the registering of commands?

**Comment by Konicai** [comment]
@JerichoTorrent Please try the build archived under the `Checks` tab of #5013
