### ISSUE TITLE
Players cannot walk through the bamboo

### ISSUE THREAD

**Issue by Z3r0xh** [GeyserMC/Geyser#5009]
### Describe the bug

Players cannot walk through the bamboo, it seems like they have an invisible block in front of them and they get stuck

### To Reproduce

Put bamboo
Try to pass between the bamboo

### Expected behaviour

You should be able to get through the bamboo.

### Screenshots / Videos

https://youtu.be/vSARiSKUrdE

### Geyser Version

Geyser version 2.4.2-b660 (git-master-63e60bc) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.20/1.21.21)

### Minecraft: Bedrock Edition Device/Version

mobile and pc

**Comment by PythonChicken123** [comment]
There is a workaround for this issue by using Hurricane: [https://github.com/GeyserMC/Hurricane/releases](url)

**Comment by Camotoy** [comment]
Closing as Hurricane is the workaround for the issue. Thank you!

**Comment by Z3r0xh** [comment]
> Closing as Hurricane is the workaround for the issue. Thank you!

Sorry, I didn't know about this plugin. Thank you very much!
