### ISSUE TITLE
SimpleSit conflicting.

### ISSUE THREAD

**Issue by KotoHacker** [GeyserMC/Geyser#501]
When you prescribe "/sit", then you sit down with other players, but you can move yourself. You cannot load chunks/interact with something if it is not within the radius of your sitting character.

Screenshot: [[click]](https://imgur.com/a/jRzlSjs)
Video: [[click]](https://youtu.be/ywJwTn7dsTs)
Plugin SimpleSit: [[click]](https://www.spigotmc.org/resources/simple-sit-spigot-bukkit-1-8-1-9-1-10-1-11-1-12.14706)

**Server version**
1.15.2 Paper

**Geyser version**
[#125](https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/125/)

**Bedrock version**
1.14.60

07/05/2020 - GMT+ - 12:05 (Moscow +3)

**Comment by nedogimov** [comment]
I confirm it. This is the same as with the bed.

**Comment by rtm516** [comment]
Geyser doesn't support mounting entities yet so this will not work.
