### ISSUE TITLE
Operation not permitted. Player disconnects immedietly upon joining.

### ISSUE THREAD

**Issue by netcore10** [GeyserMC/Geyser#5019]
### Describe the bug

When a player joins through bedrock, they hit an exception.

### To Reproduce

I don't really know. 

### Expected behaviour

To join

### Server Version and Plugins

purpur 2284

Current Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)*
* You are running the latest version
Previous: 1.21-130-b1b5d4c (MC: 1.21)

### Geyser Dump

https://dump.geysermc.org/wqP1VE63qFuvlyt0heSK45i8nePeFQZe

### Geyser Version

2.4.2-b666 

### Minecraft: Bedrock Edition Device/Version

1.21.23

### Additional Context

This is also with floodgate. If i link my java account it works. Unlinked accounts can join, but it only lasts about 3 seconds.

**Comment by onebeastchris** [comment]
Contact your server hosting provider - operation not permitted just tells us that the server host doesn't allow outgoing UDP traffic (or hasn't configured their firewall properly for Geyser to work).
