### ISSUE TITLE
Invalid entity mobtype mapping

### ISSUE THREAD

**Issue by larsjarred9** [GeyserMC/Geyser#502]
**Describe the bug**

I opend a case at my server that uses particles + hologram to display an item the player receives (Like hypixel's mysterie box)

**To Reproduce**

**Expected behavior**

There should be no error at all.....

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/31996561/81320216-1da17680-9091-11ea-9a1c-71a716026a14.png)

**Server Version**

![image](https://user-images.githubusercontent.com/31996561/81320510-97d1fb00-9091-11ea-9603-7f3f95d1e44c.png)

**Geyser Version**

#125 gyserbungecord

**Minecraft: Bedrock Edition Version**

1.14.50

**Additional Context**

https://pastebin.com/Dtza917d

**Comment by larsjarred9** [comment]
To Reproduce
1. Connect to play.reforgedtime.eu
2. Find the Enchantement Table (Case opener)
3. Open Case
4. See the error for yourself.

**Comment by RednedEpic** [comment]
> **Describe the bug**
> 
> I opend a case at my server that uses particles + hologram to display an item the player receives (Like hypixel's mysterie box)
> 
> **To Reproduce**
> 
> **Expected behavior**
> 
> There should be no error at all.....
> 
> **Screenshots / Videos**
> 
> ![image](https://user-images.githubusercontent.com/31996561/81320216-1da17680-9091-11ea-9a1c-71a716026a14.png)
> 
> **Server Version**
> 
> ![image](https://user-images.githubusercontent.com/31996561/81320510-97d1fb00-9091-11ea-9603-7f3f95d1e44c.png)
> 
> **Geyser Version**
> 
> #125 gyserbungecord
> 
> **Minecraft: Bedrock Edition Version**
> 
> 1.14.50
> 
> **Additional Context**
> 
> https://pastebin.com/Dtza917d

That error should not be possible unless you have a plugin doing some wrong things. Could you send us a list of all your plugins?

**Comment by larsjarred9** [comment]
![image](https://user-images.githubusercontent.com/31996561/81320902-2b0b3080-9092-11ea-9f9d-43b1f4429299.png)

**Comment by rtm516** [comment]
> To Reproduce
> 
> 1. Connect to play.reforgedtime.eu
> 2. Find the Enchantement Table (Case opener)
> 3. Open Case
> 4. See the error for yourself.

Just attempted this and didn't get kicked with the latest version of Geyser. Can you confirm this still happens?
