### ISSUE TITLE
Custom enchantments using the new method are not visible in the tooltip

### ISSUE THREAD

**Issue by ChrisTVH** [GeyserMC/Geyser#5024]
### Describe the bug

- New plugins that take advantage of the vanilla enchantment system cannot be displayed in bedrock.
- This is a feature added in 1.20.5.

### To Reproduce

- It is easy to replicate, you just need to have geyser in your proxy/backend and use a plugin that uses the above mentioned, for example in this case it is [ExcellentEnchants](https://www.spigotmc.org/resources/excellentenchants-%E2%AD%90-75-vanilla-like-enchantments.61693/).

### Expected behaviour

- It is expected that these custom enchantments can be displayed in the bedrock client correctly in the tooltip.

## Bedrock:
![image](https://github.com/user-attachments/assets/9571a74b-8488-4fe6-b96d-30f13e72496e)
## Java:
![image](https://github.com/user-attachments/assets/c8c8cd91-5b96-4cd6-8ae7-7bbd0fb45d4d)

## Server version
- Paper 1.21.1 Build `65`
## Paper Plugins
- CarbonChat, FancyNpcs
## Bukkit Plugins
- AntiPopup, CataMines, ChatColor2, ChatSentinel, Chunky, ChunkyBorder, CMI, CMILib, CoinsEngine, CommandPanels, CommandWhitelist, ConditionalEvents, CoreProtect, DeluxeCombat, ExcellentCrates, ExcellentEnchants, Fadah, FastAsyncWorldEdit, floodgate, GadgetsMenu, GeyserExtras, GrimAC, ItemEdit, ItemTag, Jobs, LiteBans, LuckPerms, Multiverse-Core, nightcore, PlaceholderAPI, ProtectionStones, ProtocolLib, RealisticSeasons, ShopGUIPlus, ShopGUIPlus-SellGUI, TAB, Tebex, ToastedAFK, UltimateClans, Vault, ViaBackwards, ViaVersion, VoidGen, WorldGuard, WorldGuardEvents.

### Geyser Dump

https://dump.geysermc.org/Q9zwWXq7OBIDbbvb0fxKnf8WbQwye5Cg

### Geyser Version

Geyser 2.4.2-b666 (git-master-9dad34d)

### Minecraft: Bedrock Edition Device/Version

v1.21.20/v1.21.23

**Comment by onebeastchris** [comment]
https://geysermc.org/wiki/geyser/translations#modifyingadding-minecraft-java-translations
This looks like missing Java translation strings to me (Geyser doesn't download Java edition resource packs which would contain them). Try adding the translation strings as shown on the wiki?

**Comment by ChrisTVH** [comment]
> https://geysermc.org/wiki/geyser/translations#modifyingadding-minecraft-java-translations This looks like missing Java translation strings to me (Geyser doesn't download Java edition resource packs which would contain them). Try adding the translation strings as shown on the wiki?

Are you telling me I can add it myself?

**Comment by onebeastchris** [comment]
Yes, you'd need to create that folder yourself, and add the language files from the java resource pack there

**Comment by ChrisTVH** [comment]
> Yes, you'd need to create that folder yourself, and add the language files from the java resource pack there
I was researching and reading the wiki and I see that just adding the missing enchantment strings would be enough.
But I don't know if I can get the language files directly from the server.

**Comment by onebeastchris** [comment]
The resource pack that is sent to the Java client will contain them

**Comment by ChrisTVH** [comment]
> The resource pack that is sent to the Java client will contain them

Right now my head, is trying to think how do I get that from the client, but anyway I have a command to pull the components of the objects from there I can get the id, which I require to do what it tells me in the wiki.

**Comment by ChrisTVH** [comment]
> The resource pack that is sent to the Java client will contain them

I tried to do as you said and it didn't work....
![image](https://github.com/user-attachments/assets/4ab0176c-d66d-4ca8-bc18-891313b196cd)

**Comment by onebeastchris** [comment]
- Did you restart the server after adding the translations?
- What text is shown to players when you run `/tellraw @a {"translate":"enchantment.minecraft.confusion"}`? The translation that you added, or the key?
- Is the client using the es_es language?

**Comment by ChrisTVH** [comment]
> * Did you restart the server after adding the translations?
> * What text is shown to players when you run `/tellraw @a {"translate":"enchantment.minecraft.confusion"}`? The translation that you added, or the key?
> * Is the client using the es_es language?

Well, I used a command called /itemnbt to get that, from there I got the ID of each enchantment.

The other plugins detect the enchantments with that id as if they were native to miencraft, because of what I mentioned in the issue.

But I'm going to try that and see.

**Comment by ChrisTVH** [comment]
This appears:
![image](https://github.com/user-attachments/assets/adfa8d60-0011-43e7-b99e-c7611c7c9fd9)

**Comment by onebeastchris** [comment]
is that on a java client? If so, it would indicate that the enchantment IDs that you checked aren't actually the language keys that are used for the enchantment.  

I'm not able to try and debug the issue at the moment, I'll try and do that later today/tomorrow.

**Comment by ChrisTVH** [comment]
> is that on a java client? If so, it would indicate that the enchantment IDs that you checked aren't actually the language keys that are used for the enchantment.
> 
> I'm not able to try and debug the issue at the moment, I'll try and do that later today/tomorrow.

I tried it in bedrock and it came out the same as well.

**Comment by onebeastchris** [comment]
Could you try using the linked PR's Geyser build?
It can be downloaded under the `Checks` tab.

**Comment by ChrisTVH** [comment]
> Could you try using the linked PR's Geyser build? It can be downloaded under the `Checks` tab.
Wuaaah they are finally visible.
![image](https://github.com/user-attachments/assets/2558d2e4-91ed-4330-bb4f-75d9641c9568)

**Comment by ChrisTVH** [comment]
Some bugs came up on console, so I'll pass them along here.
https://mclo.gs/KT1lAq9

**Comment by Camotoy** [comment]
Would you be able to send the full latest.log file? Thanks.

**Comment by ChrisTVH** [comment]
> Would you be able to send the full latest.log file? (Through MCLogs is fine) Thanks.
Here you can capture all the errors I made during the test.
https://mclo.gs/9kZoTlP

**Comment by onebeastchris** [comment]
The last issue should be resolved by https://github.com/GeyserMC/Geyser/pull/4849 - the latest version of Geyser should at least show the enchantment name properly.

**Comment by ChrisTVH** [comment]
> The last issue should be resolved by #4849 - the latest version of Geyser should at least show the enchantment name properly.
I'm sorry for the delay, I tested the build of #4849 today and I got a comment and the enchants stopped appearing again.
![image](https://github.com/user-attachments/assets/860c2bbf-f372-4a6c-b842-954c1d3f588c)

**Comment by ChrisTVH** [comment]
As a side note, the errors that used to appear when trying to view custom enchantments are no longer displayed, but now they are not.

**Comment by Camotoy** [comment]
Please try the latest Geyser build.

**Comment by ChrisTVH** [comment]
It works very well and without errors, the thing is that you can't use the custom enchantments to enchant objects from bedrock using the anvil.

**Comment by ChrisTVH** [comment]
- Here I have the complete log file to report certain errors of not being able to translate certain packages related to the issue: https://mclo.gs/SYprHQ0
- Version: Geyser 2.4.2-b673
- https://dump.geysermc.org/LxbGnBXqvGwoMJxZjhT9VnsWlCPIy0m2
