### ISSUE TITLE
interacting with a sign makes the server respond multiple times

### ISSUE THREAD

**Issue by Artuto** [GeyserMC/Geyser#503]
**Describe the bug**
When you tap on a sign to interact with it (with plugins like ServerSign) the action gets repeated multiple times.

**To Reproduce**
- I'm gonna use ServerSigns to reproduce this, but other plugins that create signs that can run commands should work.

1. Install ServerSigns https://www.spigotmc.org/resources/serversigns.10693/
2. Put a sign and run `/svs add <server> say Hello`
3. Right click the sign to apply the command.
4. Right click it again.

**Expected behavior**
Only execute the sign action once.

**Screenshots / Videos**

**Server Version**
Paper b201 (yes i know im outdated but this also occurred when the build was new)

**Geyser Version**
Geyser master b125

**Minecraft: Bedrock Edition Version**
Minecraft for Switch 1.14.60, reproduced also in Android

**Additional Context**

**Comment by TheMasterBlaster** [comment]
I can confirm this happens, even with the latest Paper builds with the latest Master Geyser (Standalone). Seems it repeats four or more times.

**Comment by Arktisfox** [comment]
This happens on any block it seems. Bells are easiest to test with. 
Testing with CoreProtect spams "Database is busy" several times as well.

**Comment by Kooldude183** [comment]
This also happens when using GriefPrevention; when using the golden shovel or stick, GP thinks there's multiple right-click inputs.
