### ISSUE TITLE
player location null

### ISSUE THREAD

**Issue by REDKING-11** [GeyserMC/Geyser#5033]
### Describe the bug

when bedrock player joins the game they are all ready dead and when they respawn there comes massive errors

### To Reproduce

join
respawn
error

### Expected behaviour

to be able to play

### Server Version and Plugins

1.21 arclight
![Näyttökuva 2024-09-10 165300](https://github.com/user-attachments/assets/126d59bb-13b2-4107-b684-da27aa860c48)
![Näyttökuva 2024-09-10 165414](https://github.com/user-attachments/assets/c91f541e-8208-402d-8bcb-468fe7a3af4a)

### Geyser Dump

https://dump.geysermc.org/Q7pJ8S691JWd9NjJKeB4BeqpK8AmolaT

### Geyser Version

newest velocity i think

### Minecraft: Bedrock Edition Device/Version

ps5 newest update

### Additional Context

https://mclo.gs/6T6UY3P

**Comment by onebeastchris** [comment]
That's an arclight issue. Report it to them instead.

Do note that we do not officially support platforms such as arclight as they are prone to break plugins/mods.
