### ISSUE TITLE
Custom stone cutter recipes broken 

### ISSUE THREAD

**Issue by Jsaunders411** [GeyserMC/Geyser#5043]
### Describe the bug

Crafting recipes become broken  when you add custom recipe packs like master cutter and renewable resources packs.

### To Reproduce

Have the custom recipe pack like renewable recoures installed or master cutter installed. Now try to craft stone brick walls and turn polished andesite block into stairs in stone cutter.
You will see the andesite block will become slabs not stairs and the stone or stone brick blocks will become cobble stone walls instead of stone walls or stone brick walls.

### Expected behaviour

Be able to craft the right recipes even with custom recipes data packs installed.

### Server Version and Plugins

This server is running Paper version 1.21.1-83-master@2aaf436 (2024-09-17T15:10:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
17.09 19:08:20 [Server] INFO You are running the latest version
17.09 19:08:20 [Server] INFO Previous version: 1.21.1-81-13a2395 (MC: 1.21.1)

### Geyser Dump

https://dump.geysermc.org/gwbbTYv3cwxKLVuUYeMUOgSg39NP56ek

### Geyser Version

This server is running Geyser version 2.4.3-b675 (git-master-11f76b6) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.30)

### Minecraft: Bedrock Edition Device/Version

Xbox bedrock edition 1.20.30

**Comment by onebeastchris** [comment]
Try updating Geyser to the latest version, that should resolve this issue

**Comment by Jsaunders411** [comment]
Issue was resolved in latest build appreciate the quick resolution as always!
