### ISSUE TITLE
Invalid mappings for Purpur_Pillar

### ISSUE THREAD

**Issue by Tjorven-Liebe** [GeyserMC/Geyser#5045]
### Describe the bug

The purpur_pillar has gotten it's own item id, now geyser doesn't map that correctly - i think.

If you place the purpur_pillar, in previous bedrock versions the rotation is tracked, so the purpur_pillar block is rotated.
in the latest version however it firstly shows a rotation animation but the block then is rotated back 

### To Reproduce

Drag the item out of the creative inventory, it disappears.
/give the item to yourself, the item has the item id of purpur_pillars but the texture of purpur_block.

### Expected behaviour

The item should have the texture of the purpur_pillar

### Screenshots / Videos

https://github.com/user-attachments/assets/10234892-1f6d-40cf-91ad-8e39912a0aac

### Geyser Version

2.4.2-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

1.21.30

**Comment by Camotoy** [comment]
This should be fixed on the latest version.

**Comment by Tjorven-Liebe** [comment]
You are partially right.
The block is fixed, but not the item in the inventory.
In creative mode you still cannot pick the purpur_pillar from the creative inventory. And if you elsewhere get the block it still has the texture of purpur_block
