### ISSUE TITLE
Enchantment Glow on Vanilla or Custom items breaking crafting recipes 

### ISSUE THREAD

**Issue by ChiefWarPig** [GeyserMC/Geyser#5049]
### Describe the bug

When a player has either a custom or vanilla item with the enchantment glow on it in their inventory they can not get crafting recipes suggested in either the inventory crafting grid or crafting table. Remove the item with the glow on it and the recipes work. 

### To Reproduce

Give yourself a bunch of items with the enchantment glow on it (Oak Logs for example) Place a few and break them with a pickaxe. The logs you break should be regular vanilla Oak Logs with no glow. When you open a crafting grid to turn the vanilla logs to planks with some of the logs with the glow effect still applied in your inventory, the recipe for planks will show in red. Remove the items with the glow effect on completely and just have normal vanilla logs in your inventory and the recipe for planks is suggested. 

### Expected behaviour

Crafting grid should ignore the items with the enchantment glow on but still suggest the plank recipe as being accessible with the vanilla planks in the players inventory. 

### Screenshots / Videos

https://github.com/user-attachments/assets/72bad9fe-e83d-4caa-a3b3-1b2eeef3afc0

https://github.com/user-attachments/assets/9957f752-1dfe-4542-b3d1-409037114ede

### Server Version and Plugins

This server is running Paper version 1.21.1-56-master@227c94a (2024-08-31T19:12:03Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

Server Plugins (107):
19.09 16:26:04 [Server] INFO Paper Plugins:
19.09 16:26:04 [Server] INFO - AdvancedServerList, TicketManager, TicketManagerCore
19.09 16:26:04 [Server] INFO Bukkit Plugins:
19.09 16:26:04 [Server] INFO - AdvancedAntiVPN, AdvancedChests, ajAntiXray, ajLeaderboards, AnvilColors, ArmorStandEditor, AutoComposter, AxKoth, AxRankMenu, AxRewards
19.09 16:26:04 [Server] INFO AxSellwands, AxTrade, BeastLib, BeastWithdraw, BeautyQuests, BetterRTP, BlockLocker, BlocksToCommand, ChatControlRed, Chunky
19.09 16:26:04 [Server] INFO Citizens, CitizensCMD, CMILib, CommandPanels, CommandWhitelist, CoreProtect, CrazyEnvoys, CustomCommands, DecentHolograms, DiscordSRV
19.09 16:26:04 [Server] INFO DragonSlayer, DragonTimer, Elevators, Essentials, EssentialsSpawn, EternalTags, ExcellentCrates, ExecutableBlocks, ExecutableItems, FastAsyncWorldEdit
19.09 16:26:04 [Server] INFO floodgate, GCore, Geyser-Spigot, GSit, HeadsPlus, HelpCommand, InventoryRollbackPlus, InvSeePlusPlus, ItemsAdder, Jobs
19.09 16:26:04 [Server] INFO Lands, LiteBans, LoneLibs, Lootin, LuckPerms, MobFarmManager, MobsToEggs, Multiverse-Core, Multiverse-Inventories, NBTAPI
19.09 16:26:04 [Server] INFO nightcore, NotBounties, PhoenixDuels, PlaceholderAPI, PlayerAuctions, PlayerKits2, PlayerVaults, PlayerWarps, Protect, ProtocolLib
19.09 16:26:04 [Server] INFO PvPManager, PvPStats, PyroFishingPro, PyroLib, qsaddon-discordsrv, qsaddon-displaycontrol, qssuite-limited, QuickShop-Hikari, SCore, signatureDeluxe
19.09 16:26:04 [Server] INFO SpawnerMeta, squaremap, squaremap-essentialsx, squaremap-vanish, squaremap-worldguard, StackMob, SuperVanish, TAB, TicTacToe, UpgradeableHoppers
19.09 16:26:04 [Server] INFO Vault, Vehicles, VeinMiner, ViaBackwards, ViaVersion, VoidWorld, VotifierPlus, VotingPlugin, Vulcan, WhackaMole
19.09 16:26:04 [Server] INFO WildRegeneration, WorldBorder, WorldGuard, *xAntiAFK

### Geyser Dump

https://dump.geysermc.org/ls9kfiezHoGqurYE6OWT304gLBIs59oK

### Geyser Version

Geyser Spigot 2.4.3-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

Playstation and Pocket Edition 

### Additional Context

This has come to light with infinite blocks made using the Executable Items plugin, they have the enchantment glint to make them distiguishable from vanilla items. I have run the test with EI items and vanilla items using the /minecraft:give command using the "[enchantment_glint_override=true]" argument and had the same outcome. The issue still arises if you place an enchantment on the item to give it the glow effect also.

**Comment by Camotoy** [comment]
Thanks for the report. This sounds like it may be a client issue - in which case a solution would be difficult for us to tackle. I assume crafting manually would still work, though?

**Comment by ChiefWarPig** [comment]
Yes if you manually move the log you can then craft them manually.

**Comment by ChiefWarPig** [comment]
> Thanks for the report. This sounds like it may be a client issue - in which case a solution would be difficult for us to tackle. I assume crafting manually would still work, though?

Just received reports from players this bug seems to have been fixed in a recent update. :)
