### ISSUE TITLE
Baby turtles look grown up

### ISSUE THREAD

**Issue by duemir** [GeyserMC/Geyser#5055]
### Describe the bug

Turtles that has only hatched from the eggs and look like babies on the Java server look fully grown up on tablet.

### To Reproduce

1. Bread turtles and hatch eggs on Java client
2. Look at the baby turtles from Bedrock client

### Expected behaviour

Baby turtles look like babies on both Java and Bedrock client

### Geyser Dump

https://dump.geysermc.org/xpCaPTqjdiFFElulqPBsLv2ncyOpQBfN

### Geyser Version

2.4.3-b679 (git-master-7af5bac)

**Comment by Camotoy** [comment]
Thanks for the report! There does seem to be a size difference with turtles in general between Java and Bedrock - can you send a screenshot as an example of what you're seeing?

**Comment by duemir** [comment]
Yes. Of course. Sorry it took me so much time:
My Java Client:
![Screenshot 2024-09-22 at 08 23 09](https://github.com/user-attachments/assets/6edaf600-c768-49fb-8776-869372e41d06)
Kid's Tablet:
![Screenshot_20240922-082332](https://github.com/user-attachments/assets/89c3dfea-b9ac-4eb6-9000-ce904872ee87)

**Comment by Camotoy** [comment]
How do they look with the latest Geyser build?

**Comment by duemir** [comment]
I've got an old Windows laptop. I'll update everything and try to hatch some more and compare.

**Comment by duemir** [comment]
Sorry. It all looks good. Bedrock baby turtles indeed significantly bigger than adults but not as big.
