### ISSUE TITLE
Gradlew

### ISSUE THREAD

**Issue by Project2667** [GeyserMC/Geyser#5056]
### Describe the bug

Hi there! I have a problem with Gradlew build command, it doesn't work.
![Snímek obrazovky 2024-09-22 110100](https://github.com/user-attachments/assets/8ce7d5ae-0ddb-49b5-ac3c-2ce8f4c98a69)
This is an error output.

←[31mFAILURE: ←[39m←[31mBuild failed with an exception.←[39m                                                                                                                                                                                    * What went wrong:                                                                                                      org.gradle.api.internal.catalog.GeneratedClassCompilationException: No Java compiler found, please ensure you are running Gradle with a JDK                                                                                                     ←[33m> ←[39mNo Java compiler found, please ensure you are running Gradle with a JDK                                                                                                                                                             * Try:                                                                                                                  ←[33m> ←[39mRun with ←[1m--stacktrace←[m option to get the stack trace.                                                 ←[33m> ←[39mRun with ←[1m--info←[m or ←[1m--debug←[m option to get more log output.                                     ←[33m> ←[39mRun with ←[1m--scan←[m to get full insights.                                                                ←[33m> ←[39mGet more help at ←[1mhttps://help.gradle.org←[m.                                                                                                                                                                                    ←[31;1mBUILD FAILED←[0;39m in 1m 19s

### To Reproduce

Commands:
1. git clone <repository-url>
2. cd Geyser/
3. git submodule --init --recursive
4. ./gradlew build
5. And there I can't continue because of an error.

### Expected behaviour

I think the program should continue to a successful build.

### Geyser Version

Latest one as of 22 Sep 2024 11:00 UTC +2

**Comment by Project2667** [comment]
Is there another way to run Minecraft Java Server with Geyser and Hydraulic?

**Comment by onebeastchris** [comment]
Hydraulic is not currently in a working state. As for downloading Geyser, we'd recommend getting the latest Geyser jar from our downloads website: https://geysermc.org/download/

The error you're seeing seems to indicate that you don't have a JDK installed

**Comment by Project2667** [comment]
Thanks
