### ISSUE TITLE
Disparity in horse movement speed between Java and Bedrock players

### ISSUE THREAD

**Issue by MODNMETL** [GeyserMC/Geyser#5059]
### Describe the bug

When Bedrock players on horseback are racing against Java players, both with the exact same stat horses, Bedrock players move faster, often even when they have a horse with lower stats than the Java players.

### To Reproduce

1. summon two horses with same set of stats
2. have one ridden by a Java player and one by a Bedrock player
3. Get them to race around a track
4. Watch the Bedrock player moving faster than the Java and winning the race every time

### Expected behaviour

Horse movement should be consistent regardless of whether the player is on Java or Bedrock

### Server Version and Plugins

[12:13:44 INFO]: This server is running Pufferfish+ version git-PufferfishPlus-46 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: f7716da on HEAD)
[PlugMan] Plugins (70): AdvancedPortals, ajLeaderboards, AltDetector, AntiAFKPlus, ArmorStandTools, Autorank, AxKoth, AxQuestBoard, BlockLocker, ChatSentry, Citizens, CMILib, ColoredAnvils, ColoredBooked, ConsoleSpamFix, CoreProtect, CrazyVouchers, DecentHolograms, DeluxeCombat, dtlTradersPlus, dynmap, EntityDetection, Equine, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, FarmLimiter, floodgate, ForcePack, FreedomChat, GSit, HeadDatabase, HeadDrop, Images, Jobs, KeepChunks, KixsAutoAnnouncerPremium, KixsChatGames, LootChest, LuckPerms, mcMMO, MCPerks, MODNMETL, MyCommand, NightMarket, OfflineManager, OtherAnimalTeleport, PlaceholderAPI, PlayerAuctions, PlayerPoints, PlayerWarps, PlugManX, ProtocolLib, ServerTutorialPlus, SignShop, SimpleArmorStandPose, spark, Statz, Stopwatch, TangledMazePlus, Tebex, TimeIsMoney, TooManyGen, Vault, ViaVersion, VirtualRealty, Votifier, VotingPlugin, WorldEdit

### Geyser Dump

https://dump.geysermc.org/Cd0LGl5BMmiHVFh95AIgplX6uoPpRcVf

### Geyser Version

2.4.3-b676 (git-master-7332c6b)

### Minecraft: Bedrock Edition Device/Version

1.21.30

**Comment by onebeastchris** [comment]
Should be resolved with https://github.com/GeyserMC/Geyser/commit/c8dadd8342c5c8fba14a5da962700f741c3b116b. Thanks for reporting!
