### ISSUE TITLE
Glass Blocks show all black on Android

### ISSUE THREAD

**Issue by mreic** [GeyserMC/Geyser#5063]
### Describe the bug

I got a Paper-Installation (1.21.1-99) running with Geyser 2.4.3-b680 and Floodgate (v2.2.3-SNAPSHOT (b111-3db8e59)).

After updating from an older version from Geyser (Ingame chat told me that there is a new version) i now cannot see any glass blocks in Bedrock mobile client (Android). Glass appears as black block. It doesnt matter which type of Glass. Same Issue for Glass blocks as well as colored glass or glass pane.

Android Bedrock client is also updated to newest Version.

PS: Bedrock PC Client works fine!

### To Reproduce

I dont know how to reproduce. Probably setting up a server with the same versions as described will reproduce the bug.

### Expected behaviour

Seeing Glass as Glass.

### Screenshots / Videos

![WhatsApp Image 2024-09-26 at 09 16 39](https://github.com/user-attachments/assets/887f4d27-0987-489e-be51-7147564272fe)

### Geyser Dump

https://dump.geysermc.org/cAimjDOCv0BbCIxQVxWNSt6IbaEZSZEe 

### Geyser Version

2.4.3-b680 (git-master-84dac08)

### Minecraft: Bedrock Edition Device/Version

1.21.30 Build 27468798

**Comment by Camotoy** [comment]
Have you tested to see if this issue persists in a singleplayer world?

**Comment by mreic** [comment]
> Have you tested to see if this issue persists in a singleplayer world?

It seems to be a Android-Version problem. I've not testet singleplayer before and it seems to have the same issue.
Maybe i just need to reinstall the app.
