### ISSUE TITLE
Geysermc port isn't working

### ISSUE THREAD

**Issue by NIGHTGAMER95** [GeyserMC/Geyser#5065]
### Describe the bug

I've tried many different setting configurations. The remote port always works but bedrock refuses to listen on the port I assign it. I even tried 7013 for both.

### To Reproduce

bedrock:
address: 0.0.0.0
port: 7013 #Also tried 19132
clone-remote-port: false #Also tried true
compression-level: 6
remote:
address: 127.0.0.1 #Also tried auto
port: 25565
auth-type: floodgate #also tried online

### Expected behaviour

Console log, no open port, no error.

### Screenshots / Videos

![image_2024-09-29_022949104](https://github.com/user-attachments/assets/5d1325a3-f513-4723-a1d4-e10065aeecc6)
![image_2024-09-29_023012251](https://github.com/user-attachments/assets/381771ba-980a-45fc-bc58-b2b327ff871c)

### Server Version and Plugins

2.4.0-b616

### Geyser Dump

https://dump.geysermc.org/cXWDkIMCtzymLC5Yp1pTykOMufDzg1P1https://dump.geysermc.org/cXWDkIMCtzymLC5Yp1pTykOMufDzg1P1

### Geyser Version

[09:30:31 INFO]: This server is running Geyser version 2.4.0-b616 (git-master-b248abf) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.2/1.21.3)

### Additional Context

Server isn't pinging

**Comment by Camotoy** [comment]
You're trying to ping port 7013 but you put 7012 in your config.

**Comment by onebeastchris** [comment]
Please join our discord server for support! I'll close this issue since we use GitHub issues for bug/feature request tracking only.
