### ISSUE TITLE
I can't download libraries using java 21

### ISSUE THREAD

**Issue by OurLobanov** [GeyserMC/Geyser#5068]
### Describe the bug

I can't download libraries using java 21

A problem occurred configuring project ':fabric'.
> Could not resolve all artifacts for configuration ':fabric:includeTransitive'.
   > Could not find net.raphimc:MinecraftAuth:4.1.1-20240806.235051-7.
     Searched in the following locations:
       - https://libraries.minecraft.net/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.pom
       - https://repo.maven.apache.org/maven2/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.pom
       - https://libraries.minecraft.net/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.jar
       - https://repo.maven.apache.org/maven2/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.jar
       - https://repo.opencollab.dev/main/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.pom
       - https://repo.papermc.io/repository/maven-public/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.pom
       - https://maven.neoforged.net/releases/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.pom
       - https://repo.viaversion.com/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.pom
       - https://s01.oss.sonatype.org/content/repositories/snapshots/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.pom
       - https://maven.architectury.dev/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.pom
       - file:/C:/Users/kloba/Documents/GitHub/GeyserMC/.gradle/loom-cache/remapped_mods/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.pom
       - file:/C:/Users/kloba/.gradle/caches/fabric-loom/minecraftMaven/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.pom
       - file:/C:/Users/kloba/Documents/GitHub/GeyserMC/.gradle/loom-cache/minecraftMaven/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.pom
       - file:/C:/Users/kloba/.gradle/caches/fabric-loom/forge/transformed-dependencies-v1/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.pom
       - https://maven.fabricmc.net/net/raphimc/MinecraftAuth/4.1.1-SNAPSHOT/MinecraftAuth-4.1.1-20240806.235051-7.pom
     Required by:
         project :fabric > project :core

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

### To Reproduce

c

### Expected behaviour

c

### Geyser Version

q

**Comment by onebeastchris** [comment]
This was resolved in https://github.com/GeyserMC/Geyser/commit/84dac08058d3d2130442ddfc33a32ae028e1a5d4
