### ISSUE TITLE
Big desync for BE players 

### ISSUE THREAD

**Issue by KosyakMakc** [GeyserMC/Geyser#5069]
### Describe the bug

actions of BE players are very smoothed and delayed, very unplayable(

### To Reproduce

Nothing special.
I'm just download plugin and restart server, in configuration auth is "offline".
Before reporting I'm do some experiments with configuration and nothing changes

### Expected behaviour

Actions of player is actual in online (not delayed)

### Screenshots / Videos

Recorded 1 game session in 2 views

BE player - https://youtu.be/dg2zV6M5Ei4 
Java player - https://youtu.be/ifDkoPvqpKA

### Server Version and Plugins

Folia 1.21.1
latest Geyser

### Geyser Dump

https://dump.geysermc.org/9YGVH1tG1QaRQY5bBNTuIFrm9SjZuV4F

### Geyser Version

2.4.3-b680

### Minecraft: Bedrock Edition Device/Version

1.21.31 - Android (one player also report of this on PlayStation)

**Comment by Camotoy** [comment]
Can you send a Spark report?
Spark is a plugin that helps you monitor performance for you server.
https://spark.lucko.me/download

To record performance on your server use:
`/spark profiler --thread * --timeout 60`. This will run for 60 seconds then it will automatically stop. Send us the link when prompted.

**Comment by KosyakMakc** [comment]
https://spark.lucko.me/GUVFzuRrvj
