### ISSUE TITLE
add support for world heghts lower than -64 or higher than 320

### ISSUE THREAD

**Issue by antu2010** [GeyserMC/Geyser#5074]
### What feature do you want to see added?

there are some datapacks like infinity cave that extend the world height for example in my case i have a -128 as the lowest height, it would be really good for bedrock players to experience this datapacks as well in a geyser server

**Comment by onebeastchris** [comment]
This has been implemented to the extent possible by Bedrock's limitation in https://github.com/GeyserMC/Geyser/commit/26c4c5250a55fc81ad2848a18d308e06064563a9 - update Geyser.

This supports heights between -512 and 512 for the overworld dimension. Unfortunately, there is no way to achieve the same in other dimensions as of yet.

**Comment by antu2010** [comment]
> This supports heights between -512 and 512 for the overworld dimension. Unfortunately, there is no way to achieve the same in other dimensions as of yet.

How can I use it then if I try and use the data pack nothing generates below y-64

**Comment by onebeastchris** [comment]
- Run `/geyser version` to check if you're on the latest version of Geyser; it'll only work on the latest build
- Make sure that the dimension that is expanded is the overworld dimension
