### ISSUE TITLE
I have an error (I have a little english

### ISSUE THREAD

**Issue by AnvXprogs** [GeyserMC/Geyser#5079]
### Describe the bug

[2024-10-11-11.log](https://github.com/user-attachments/files/17344298/2024-10-11-11.log)

### To Reproduce

IDK

### Expected behaviour

i am connect and then i have this error in the reding in Google i found "send-floodgate-date "
but i not fond this in the code Help PLS

### Geyser Version

1.21.1

**Comment by onebeastchris** [comment]
The log you sent does not show any Geyser-related issue. It merely shows that "LoginSecurity" failed to load. Offline mode, and login plugins by extension, are *not* supported.
