### ISSUE TITLE
Item Names are JSON strings sometimes on Bedrock

### ISSUE THREAD

**Issue by Dirt-Nasty** [GeyserMC/Geyser#508]
**Describe the bug**
When holding a map I noticed the map name is JSON string.

**To Reproduce**
1. Hold Map on Xbox Bedrock

**Expected behavior**
Should say Item Name

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/21373824/81361883-8e568c00-90ad-11ea-8cf0-dd666b81103a.png)

**Server Version**
Paper-260

**Geyser Version**
Master - Build #125

**Minecraft: Bedrock Edition Version**
1.15.2

**Comment by rtm516** [comment]
I believe this also happens with the ominous banner

**Comment by DoctorMacc** [comment]
Possibly related to #241.

**Comment by rtm516** [comment]
Related but not the same fix, they both need to be passed through the message translation utils
