### ISSUE TITLE
player nametags text plugins are not displayed correctly on geyser side (bug)

### ISSUE THREAD

**Issue by anthony114669** [GeyserMC/Geyser#5080]
### Describe the bug

basically using some plugins to change their player nametags with custom text are not displayed correctly on bedrock side

### To Reproduce

install unlimited tags plugin
and just see the nametag for both players, the bedrock side is wrong position

### Expected behaviour

correct the position and the name duplication on bedrock

### Screenshots / Videos

![bug](https://github.com/user-attachments/assets/1bd11fc6-e43e-4f0d-a1c5-d34c5b1c4e00)

### Server Version and Plugins

papermc build 120
unlimited tags lastest version
minecrft 1.21.1

### Geyser Version

1.21.1

### Minecraft: Bedrock Edition Device/Version

1.21.1

**Comment by cupang-afk** [comment]
+1 on this because other plugin ([DisplayNameTags](https://github.com/Matt-MX/DisplayNameTags)) also show the same

from bedrock
![image](https://github.com/user-attachments/assets/bd0973bf-16a0-46ea-914c-55664ced710e)

from java
![image](https://github.com/user-attachments/assets/9550a490-e0f9-4251-b092-2dceee809b56)

**Comment by Tim203** [comment]
@anthony114669 what is the plugin 'unlimited tags'? Is it alonsotags or supremetags or something else? Those were the first two that popped up after a quick search

**Comment by cupang-afk** [comment]
> @anthony114669 what is the plugin 'unlimited tags'? Is it alonsotags or supremetags or something else? Those were the first two that popped up after a quick search

it might be [this](https://www.spigotmc.org/resources/unlimitednametags.117526/)

**Comment by Exohayvan** [comment]
+1 on this as well. Using TABs plugin will still show the bedrock players original name overtop of the custom player nametags, heres a photo:
 
![20241024_023555](https://github.com/user-attachments/assets/50f9368c-bbee-421a-b080-1bde2600a64a)
