### ISSUE TITLE
Players can't join on Bungeecord

### ISSUE THREAD

**Issue by Z3r0xh** [GeyserMC/Geyser#5084]
### Describe the bug

For some versions of Geyser, players have not been able to access it.

### To Reproduce

create a clean bungeecord installation and put geyser and floodgate and it will not allow access and this message will appear:
![image](https://github.com/user-attachments/assets/721d3c05-7144-4f86-826a-4bb0c83033bb)

### Expected behaviour

.

### Server Version and Plugins

BungeeCord-Bootstrap:1.21-R0.1-SNAPSHOT:2bacf65:1875

Server log: 
https://mclo.gs/xKCIngs

### Geyser Dump

https://dump.geysermc.org/MO7vVFrcQfSf6BNioYcVSbGcF1CM0dpd

### Geyser Version

2.4.3-b689 (git-master-d64c0b3)

### Minecraft: Bedrock Edition Device/Version

1.21.31

**Comment by SinonCute** [comment]
+1

**Comment by ShawnFoxter** [comment]
this error is happening on Velocity too, try updating Floodgate if you got that in your server

**Comment by Z3r0xh** [comment]
> this error is happening on Velocity too, try updating Floodgate if you got that in your server

Both versions are the most recent and the problem persists

**Comment by Camotoy** [comment]
Please try using the builds here: https://github.com/GeyserMC/Geyser/actions/runs/11333965938 scroll down here

**Comment by SinonCute** [comment]
> Please try using the builds here: https://github.com/GeyserMC/Geyser/actions/runs/11333965938 scroll down here

Yes, it worked

**Comment by onebeastchris** [comment]
Hey! Could you test the linked PR, and see if it resolves the issue? You can find a build under "Checks", then "Artifacts" on the linked pull request. Thanks!
