### ISSUE TITLE
NPC does not display the correct name

### ISSUE THREAD

**Issue by DavyCraft648** [GeyserMC/Geyser#5089]
### Describe the bug

The NPC does not display the correct name after updating Geyser to commit ef4acb121f0f8746fa18a27f6acb1fc032ec7b2b. This might be related to issues #5085 and #5080. The last commit where this bug did not occur was c656e41.

### To Reproduce

1. Update Geyser to the latest version.
2. Install the [ZNPCsPlus](https://www.spigotmc.org/resources/znpcsplus.109380/) plugin on Paper.
3. Run `/npc create 1 player`.
4. Run `/npc holo add 1 tesss`.

### Expected behaviour

![image](https://github.com/user-attachments/assets/fbc57f8d-8c95-4c13-9866-3398a3e097ab)

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/518da026-b628-4647-9f63-751b99c3564c)

### Geyser Version

2.4.3-b685 (git-master-ef4acb1) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.30/1.21.31)

### Minecraft: Bedrock Edition Device/Version

1.21.31 Windows, 1.21.20 Android

**Comment by Tim203** [comment]
Thank you for adding steps to reproduce it. I'll take a look later today

**Comment by Tim203** [comment]
Quick update: apparently this bug is in fact two bugs. 1 that prevents the nametag from showing 'tesss' and one that prevents the nametag of the actual NPC '419' from being hidden.
The first one is resolved locally and the other one is still a WIP.
