### ISSUE TITLE
Having speed effect make player unable to move up a block

### ISSUE THREAD

**Issue by SinonGame** [GeyserMC/Geyser#509]
**Describe the bug**

When having speed effect, player can't get onto blocks in the cave such as 1x2 caves

**To Reproduce**

1.having the speed effect
2. go up the fullblock stairs
3. see error

**Expected behavior**

No gliches and be able to move up
**Screenshots / Videos**

[Video](https://ptb.discordapp.com/channels/613163671870242838/613169749525790737/708136421290016869)
**Server Version**

Paper latest
**Geyser Version**

latest
**Minecraft: Bedrock Edition Version**

1.14.6
**Additional Context**

**Comment by Chew** [comment]
Might've been fixed in #699. Needs some testing to make sure though.

**Comment by RednedEpic** [comment]
Issue has been resolved from my testing.
