### ISSUE TITLE
Stone Brick Wall seen as Cobblestone Wall on bedrock client

### ISSUE THREAD

**Issue by Noahkjn** [GeyserMC/Geyser#5095]
### Describe the bug

When playing on java and placing stone brick wall or  even holding the item, the bedrock player will see it as cobblestone wall and if they break them they will have cobblestone wall in their inventory and if they show it in their hand java players will still see stone brick wall and if the bedrock player place them this will stay the same as bedrock player will still see cobblestone wall and java player will see stone brick wall. This is since the beginning of the server when we had only plugins like Geyser, floodgate, ViaVersion, SimpleTpa and Sethome. ( sorry my spelling, english is not my main language )

### To Reproduce

1. Craft a stone brick wall on java
2. Place it
3. The bedrock player will see it as cobblestone wall
4. The bedrock player can try to pick them and replace them but this won't change anything

### Expected behaviour

Should be able to see the same block on both platform.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/3bae5f97-7ad1-4f78-986e-7f19ffb50474)
![image](https://github.com/user-attachments/assets/68ec70ea-47a0-40c4-9804-9974b3fe5979)

### Server Version and Plugins

Paper version 1.21.1-13-master@7c9240f (2024-08-12T16:54:16Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
Geyser
Floodgate
SimpleTpa
SetHome
ViaVersion
MobsManager
MinecartSP
LuckPerm

### Geyser Dump

https://dump.geysermc.org/ueBTlluvx1hDK4XOvmByyectZQXoVrOB

### Geyser Version

1.21.1

### Minecraft: Bedrock Edition Device/Version

Latest, 1.21.31

**Comment by Camotoy** [comment]
Please try updating Geyser as you are several builds outdated. Thanks for the report!
