### ISSUE TITLE
Geyser forcing custom resource packs despite it being disabled.

### ISSUE THREAD

**Issue by Rockin21** [GeyserMC/Geyser#5098]
### Describe the bug

The geyser pack is forced upon the user even though it is set to optional.

### To Reproduce

Open bedrock edition, select a server, and log in.

### Expected behaviour

An option to decline the pack

### Server Version and Plugins

This server is running Pufferfish+ version git-PufferfishPlus-"a9f972b" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a9f972b on HEAD)

### Geyser Dump

https://dump.geysermc.org/RTL0GPzfvxmWUbMiwLQhdqLOdC5bcQW1

### Geyser Version

This server is running Geyser version 2.4.4-b694 (git-master-e7ecb55) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.40/1.21.41)

**Comment by onebeastchris** [comment]
This would occur if a resource pack was previously accepted - the bedrock client "remembers" the packs it accepted, and won't re-prompt the same pack. To get the prompt again, clear the saved pack in your Bedrock client settings.
