### ISSUE TITLE
Players are randomly crashing when a player who have broken skin enter the server

### ISSUE THREAD

**Issue by ducanh2002123** [GeyserMC/Geyser#510]
**Describe the bug**

When players are playing, some of them randomly get crashes frequently, the devices that get crashes include 2 iPhone 6s, 1 Sony Android phone, and 1 Minecraft Windows 10 edition user (maybe more but I didn’t get enough data), but I do find that if the area have a lot of blocks (aka like in spawn or something), then it crashes, but in other places it didn’t. 
**To Reproduce**

Unknown, 
**Expected behavior**

Game don’t crash and should be able to play normally
**Screenshots / Videos**

**Server Version**

Paper version 251
**Geyser Version**

Geyser build 128
**Minecraft: Bedrock Edition Version**

Bedrock edition version 1.14.60
**Additional Context**

It seems to be some sort of memory issue? Also, another thing that I noticed (but Idk if it’s related), is that the Render Distance slider on all bedrock players DOES not work, it ALWAYS load 8-10 chunks in (My estimation), although the settings is at minimum

Extra info: 
Auth Mode: Offline
Floodgate: Not using
Skin Restorer: Not currently using, can install to see what happens.

**Comment by ducanh2002123** [comment]
I can give you guys the crash log on my iPhone 6s if needed

**Comment by ducanh2002123** [comment]
Okay... so after some internal investigation in my server, I found out that the issue is because of some player’s skin. Their skin is not displayed correctly on any of us (although they’re using default Steve skin), and when they’re in the server we get crashes.

**Comment by blubbll** [comment]
The last time i remember all Bedrock players on the java and bedrock side are Steves anyway, how would a clientside bedrock skin make a difference on both sides?

**Comment by ducanh2002123** [comment]
I don’t know, on the discord server someone said that they recently added Bedrock to Bedrock skin support. I haven’t received a crash report with someone on Java Edition.

**Comment by ducanh2002123** [comment]
The issue seems to not have been fixed completely, some players on my server is still getting broken skins, and it’s still making others crashes

**Comment by ducanh2002123** [comment]
![3B948EF8-06D5-46F7-BF36-6E55FC6F18B1](https://user-images.githubusercontent.com/10848519/81809739-0ad4e900-954c-11ea-8129-fce64170e22c.jpeg)

**Comment by rtm516** [comment]
@ducanh2002123 Does this issue still occur in the latest version or has it been resolved?

**Comment by toinouH** [comment]
Is there anyone having this bug or can we close it ?

**Comment by RednedEpic** [comment]
Closing due to lack of response and lack of future reports relating to this. If this issue is still happening, please comment here stating so and we'll open this back up :)
