### ISSUE TITLE
Progress Update for 1.21.2/3

### ISSUE THREAD

**Issue by Camotoy** [GeyserMC/Geyser#5100]
### Recipes
- [x] basic shaped recipe support
- [x] complex shaped recipes (recipes that are based on tags or have multiple inputs for one slot)
- [x] shapeless recipes
- [x] smithing recipes
- [x] on-the-fly smithing recipes
- [x] stonecutter recipes
- [ ] verify old recipes work (decorated pots, shulker boxes, fireworks)
- [x] when should we clear a recipes packet?

### Movement
- [x] move to server-authoritative movement (this will allow us to utilize the expanded input packet)
- [x] verify mounts work
- [ ] entity teleport packet re-implement
- [x] why does the player spawn with weird rotation?
- [x] implement ClientboundPlayerRotationPacket

### Other
- [x] #5119
- [x] new inventory packets
- [x] cooldown isn't showing on missed hit

**Comment by KungAnka** [comment]
Hello, Is there a date when this is done?

**Comment by Camotoy** [comment]
No. Hopefully soon, though.

**Comment by Camotoy** [comment]
1.12.3 Java has been merged.

**Comment by Loose-countess19** [comment]
when will bedrock be able to chat agiain?
