### ISSUE TITLE
Client 1.21.41 not working with Spygot 1.21.3 by Geyser-Spigot

### ISSUE THREAD

**Issue by max-sgt** [GeyserMC/Geyser#5115]
### Describe the bug

This error occurs when connecting:
[20:25:10] [localSession-7-2/INFO]: [Geyser-Spigot] USER has disconnected from the Java server because of Outdated client! Please use 1.21.3

Spigot 1.21.3
Geyser-Spigot Build #112 · 29.09.2024

How can the problem be solved?

### To Reproduce

no comments

### Expected behaviour

no comments

### Server Version and Plugins

Spygot 1.21.3

### Geyser Version

Geyser-Spigot v2.4.4-SNAPSHOT Build #699

### Minecraft: Bedrock Edition Device/Version

1.21.41, Nindendo Switch

**Comment by eclipseisoffline** [comment]
Geyser does not yet support 1.21.2/1.21.3. You have to use ViaVersion with ViaBackwards on paper or downgrade to 1.21/1.21.1 and wait until Geyser supports 1.21.2/1.21.3.

**Comment by max-sgt** [comment]
The problem was solved after installing ViaBackwards to the existing ViaVersion 5.10
