### ISSUE TITLE
NPCs becoming invisible on latest Geyser

### ISSUE THREAD

**Issue by Paceski** [GeyserMC/Geyser#5117]
### Describe the bug

Essentially, when I updated to latest Geyser, the NPC have become invisible.

Using FancyNPCs and Geyser latest in my lobby;
![image](https://github.com/user-attachments/assets/a26701d7-e1ff-4db5-9659-574e611fc2c5)

zNPCsPlus on Survival and Geyser latest;

![image](https://github.com/user-attachments/assets/adb50122-aa07-4644-8f7c-50aa0229c68c)

Reverting back to https://github.com/GeyserMC/Geyser/commit/6331cb6d586d1a19bf9d0daabb535d82c9a58e29
fixes this issue for me and NPCs are displayed once again, but not on latest.

### To Reproduce

Install latest Geyser, cannot see NPCs no more.

### Expected behaviour

NPCs should be displayed.

### Server Version and Plugins

1.20.1/1.20.4

### Geyser Version

latest

**Comment by Tim203** [comment]
Awaiting reproducing steps from the issuer.

**Comment by Paceski** [comment]
https://github.com/user-attachments/assets/a22984f9-b3b3-4b6f-9997-24004b31ecba

**Comment by Paceski** [comment]
I cannot see any players on bedrock on latest version, moving back 8 builds behind works. So it's not only NPCs

**Comment by Paceski** [comment]
Wrong again, it's this.

https://github.com/GeyserExtensionists/GeyserModelEnginePackGenerator

Issue resolved, we can close
