### ISSUE TITLE
Floating items don't float

### ISSUE THREAD

**Issue by james090500** [GeyserMC/Geyser#512]
**Describe the bug**
Floating items will fall to the ground and despawn even if they have no_gravity 

**To Reproduce**
Easiest way is to create a floating item with the HD plugin
https://dev.bukkit.org/projects/holographic-displays

**Expected behavior**
Well, the item should float and not despawn

**Screenshots / Videos**
Bedrock: https://i.imgur.com/yQK0d4T.jpg
Java: https://cdn.discordapp.com/attachments/401201630244110338/708328857551241246/unknown.png

**Server Version**
git-Paper-257 (MC: 1.15.2)

**Geyser Version**
Geyser version 1.0-SNAPSHOT (git-master-e58ffdd)

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
HolographicDisplay, you can set floating items with labels. They do not float but fall to the ground and eventually despawn.

**Comment by RednedEpic** [comment]
Unable to reproduce. Can you confirm if this issue still persists on your end?
![image](https://user-images.githubusercontent.com/29153871/82746045-07620e80-9d51-11ea-95f8-9ad56a748c8b.png)

**Comment by james090500** [comment]
Yes this seems to be fixed in latest.
