### ISSUE TITLE
cartography table does not work

### ISSUE THREAD

**Issue by typetypee** [GeyserMC/Geyser#5120]
### Describe the bug

I'm on bedrock pocket edition, and when I try to put paper in the first slot of the cartography table to make a map, it puts the paper back into the inventory. This also happens with my friend on java in the same server.

### To Reproduce

1, Use geyser spigot.
2. Open cartography table.
3. Put paper in the first slot.
4. The paper is put back in inventory automatically.

### Expected behaviour

The paper should stay in the first slot and you're allowed to make an empty map.

### Screenshots / Videos

https://github.com/user-attachments/assets/b4ded6cf-0dfd-448a-bda5-ef41df2b6a95

### Geyser Dump

https://dump.geysermc.org/SLQartfz3GB4DPRdniNqGMrsl8W1Xsfx

### Geyser Version

705

### Minecraft: Bedrock Edition Device/Version

1.21.44

**Comment by Camotoy** [comment]
This is a Bedrock-only recipe; it does not exist on Java, hence why this does not work.

Thank you anyway for the issue report.

**Comment by typetypee** [comment]
ohhh that makes sense, very sad 😔😔😔
