### ISSUE TITLE
Bedrock players unable to see Java players

### ISSUE THREAD

**Issue by DarkChromaMC** [GeyserMC/Geyser#5125]
### Describe the bug

Bedrock players are unable to visually see Java players. It's as if they're not there. This only happened after updating to the latest Geyser version.

### To Reproduce

1. Use Geyser build 706
2. Join the server as a Java player and teleport to a Bedrock player
3. Observe Bedrock players are unable to see you

### Expected behaviour

Java players do not appear invisible to Bedrock players

### Geyser Dump

https://dump.geysermc.org/a8xYK4Bd3eXT5PdBEBrPWvJF3mVAuWDy

### Geyser Version

2.5.0-b706 (git-master-6983095) (Java: 1.21.3, Bedrock: 1.20.80/1.20.81 - 1.21.40 - 1.21.44)

**Comment by Camotoy** [comment]
What is your backend Java server version?
