### ISSUE TITLE
Unable to upgrade netherite armour

### ISSUE THREAD

**Issue by Ippadey** [GeyserMC/Geyser#5126]
### Describe the bug

Unable to upgrade to netherite amour in bedrock edition

### To Reproduce

1. Hop on Minecraft bedrock
2. Join the server
3. Try to upgrade diamond armour to netherite

### Expected behaviour

I hope it will fix soon

### Screenshots / Videos

[netherite.pdf](https://github.com/user-attachments/files/17645543/netherite.pdf)

### Geyser Version

Geyser java 1.21.2 - 1.21.3

### Minecraft: Bedrock Edition Device/Version

1.21.40 android

**Comment by cloakfox** [comment]
Our bedrock players have been reporting the same.

The backend server is on paper 1.21.1
![received_1693767011206670](https://github.com/user-attachments/assets/2eefe6a3-d696-4ec8-ae74-96ebfd01aa4e)

**Comment by Ippadey** [comment]
To add up this happens with some bedrock players and some of the time they can only upgrade once or twice for some reason

**Comment by benshan36** [comment]
I have another person reporting this issue on Paper 1.21.1 
https://discord.com/channels/613163671870242838/1304263288690835497/1304263288690835497

**Comment by Brasil150** [comment]
This problem is also occurring on my server. Any solution?

I see there is another open issue for the same situation. #5144

**Comment by lucasdimatteo** [comment]
Same problem here. Any solution?

**Comment by Camotoy** [comment]
Please try the latest Geyser version.

**Comment by onebeastchris** [comment]
Closing as resolved since this was addressed - if it's still occurring, please open a new issue. Thanks!
