### ISSUE TITLE
Breaking grass sometimes makes stone breaking sound

### ISSUE THREAD

**Issue by ImT3chy** [GeyserMC/Geyser#513]
**Describe the bug**
Sometimes when you go around break grass it will play the stone breaking sound instead of grass

**To Reproduce**
1. join a geyser server
2. start breaking grass
3. have sound on
4. hear that it sometimes play stone breaking sound

**Expected behavior**
When breaking grass it only plays the grass breaking sound

**Screenshots / Videos**
https://youtu.be/NPDNvupJBTo

**Server Version**
Git-spigot-2040c4c-77fd87e (MC:1.15.2) (implementing API version 1.15.2-ro.1-snapshot)

**Geyser Version**
Im using geyser#128 Bukkit version with floodgate#21

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by DoctorMacc** [comment]
Can you re-test this with the latest Geyser?

**Comment by ImT3chy** [comment]
Yeah i will test it in a bit when i get my server working and you mean #142 right?

**Comment by ImT3chy** [comment]
Tested on #145 and its still happning

**Comment by DoctorMacc** [comment]
Thanks for the update.

**Comment by RednedEpic** [comment]
Seems like in survival when I click between each block break its fine, but if I hold down my click and start breaking other blocks with a hardness of zero, the stone sound starts playing. Will investigate further.

**Comment by toinouH** [comment]
Is this bug still present in the latest versions of Geyser?

**Comment by toinouH** [comment]
Ok, I've been able to reproduce that bug. 
You have to break the block from the farthest distance.
