### ISSUE TITLE
Virtual lectern does not work

### ISSUE THREAD

**Issue by KabanFriends** [GeyserMC/Geyser#5139]
### Describe the bug

When showing a lectern GUI of a lectern that does not exist in the world, bedrock players don't see the book text.

### To Reproduce

1. Run a code like this to open a virtual lectern GUI:
```java
Inventory inv = Bukkit.createInventory(null, InventoryType.LECTERN);
ItemStack book = new ItemStack(Material.WRITTEN_BOOK);
BookMeta bookMeta = (BookMeta) book.getItemMeta();
bookMeta.addPage("Example Page Text");
bookMeta.setTitle("Example Title");
bookMeta.setAuthor("Sigong");
book.setItemMeta(bookMeta);
inv.setItem(0, book);
player.openInventory(inv);
```
2. Observe the text in the book

### Expected behaviour

Bedrock players can see the text "Example Page Text" correctly

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/b1b61c76-ec58-46cf-8b2d-344fe9148529)

### Geyser Dump

https://dump.geysermc.org/HlvLXuJ81Kd6Eb3zHAMo0pnpjT0Vxs0Z

### Geyser Version

2.5.0-b711 (git-master-4598ffe)

### Minecraft: Bedrock Edition Device/Version

1.21.41, Windows 11

### Additional Context

This is the plugin I quickly wrote to reproduce the bug: [TestPlugin.zip](https://github.com/user-attachments/files/17689022/TestPlugin.zip)
Type /books in chat to see the virtual lectern GUI.

**Comment by onebeastchris** [comment]
hey, thanks for the bug report & reproduction plugin! Can you see if https://github.com/GeyserMC/Geyser/pull/5169 resolves the issue?

**Comment by KabanFriends** [comment]
> hey, thanks for the bug report & reproduction plugin! Can you see if #5169 resolves the issue?

Tested, and I confirmed that the issue no longer happens on the PR build!
