### ISSUE TITLE
upgrading gear from diamond to netherite

### ISSUE THREAD

**Issue by YTCoolGunner** [GeyserMC/Geyser#5140]
### Describe the bug

upgrading gear from diamond to netherite dose not work it just shows a x

### To Reproduce

upgrading templete and then amrour and then neithertire

### Expected behaviour

upgrading netheitre

### Screenshots / Videos

![Screenshot 2024-11-09 164143](https://github.com/user-attachments/assets/2f5669e3-0b61-44d7-bfe9-1a00c74770f6)

### Geyser Dump

https://dump.geysermc.org/8OvEXkTwnYQUMIhkD2N3enlGYSO3ZiPm

### Geyser Version

2.5.0-b707 (git-master-881b8e9)

### Minecraft: Bedrock Edition Device/Version

lastest verison

**Comment by Camotoy** [comment]
Duplicate of #5126. Thank you for the report though!

**Comment by YTCoolGunner** [comment]
Np
