### ISSUE TITLE
massive log consol

### ISSUE THREAD

**Issue by UnknowUser0** [GeyserMC/Geyser#5141]
### Describe the bug

geyser sends logs to the console in less than 1 second continuously

### To Reproduce

*

### Expected behaviour

 *

### Screenshots / Videos

![{B2535748-B340-4F62-BAE3-7D13015985AD}](https://github.com/user-attachments/assets/d55144d4-77a1-4484-bd74-4400b0e2622c)

### Geyser Dump

https://dump.geysermc.org/yaBSPXt1NiMFWKp1qU1NL5Sby8Fr0SXB

### Geyser Version

Build #711

### Minecraft: Bedrock Edition Device/Version

1.21.3

**Comment by lodzen** [comment]
I am facing the same issue and i can't see an option to decrease the log level
