### ISSUE TITLE
Netherite Upgrade issue

### ISSUE THREAD

**Issue by RaftixKun** [GeyserMC/Geyser#5144]
### Describe the bug

netherite upgrade erro

### To Reproduce

a

### Expected behaviour

b

### Screenshots / Videos

![Screenshot_2024-11-11-16-34-18-89_2cbc9fd271adfa2ebd7600c42501803f](https://github.com/user-attachments/assets/deb12809-5852-441e-9a37-b6a09503fabd)

### Server Version and Plugins

version 1.21.1-DEV-ver/1.21.1

### Geyser Version

Geyser version 2.5.0-b711 (git-master-4598ffe)

**Comment by cgw2023** [comment]
seems like same as #5126

**Comment by Brasil150** [comment]
Same problem here.

**Comment by Camotoy** [comment]
Duplicate indeed of #5126. Thank you for reporting, though!
