### ISSUE TITLE
Stonecutter not working properly 

### ISSUE THREAD

**Issue by bajamaster13** [GeyserMC/Geyser#5150]
### Describe the bug

Stonecutter recipes are not showing correctly on bedrock clients 

### To Reproduce

1. go to stonecutter
2. attempt to make a slab or stair
3. get different version of item you were attempting to get 

### Expected behaviour

should be able to get the item you clicked not the opposite 

### Geyser Dump

https://dump.geysermc.org/NJ8zUYmFUUOyaJSlb5Ym6RUmAZp9EKdm

### Geyser Version

Build #714

**Comment by Camotoy** [comment]
Do you have any datapacks installed on your server?

**Comment by bajamaster13** [comment]
> Do you have any datapacks installed on your server?

no data packs

**Comment by Camotoy** [comment]
What device are you using to connect to Geyser?

**Comment by bajamaster13** [comment]
> What device are you using to connect to Geyser?

xbox one, ps4, pixel 7.

**Comment by bajamaster13** [comment]
https://youtu.be/GXyeGT5NRhk 
video of issue in question

**Comment by dom64** [comment]
Still happens as of build #716. Player selected chiseled stone bricks but got slabs instead.

**Comment by GGTEC** [comment]
Same bug here

**Comment by SilverServerT** [comment]
same here, makes the wrong item
![javaw_yZVIVuon5b](https://github.com/user-attachments/assets/f0daaacc-111b-410f-b1e4-ecf37df5555c)

**Comment by srenderfrance** [comment]
Same issue for me as well. Running a papermc server, happens with both my PC(bedrock) and on Kindle Fire.

**Comment by S-SHI777** [comment]
same bug here.
here is a video I encounted the problem
https://youtu.be/b7b9-rAaGjA?si=-DI6lHoi0iFCH6Sb
and geyser dump
https://dump.geysermc.org/qfTNSV1X8xE5VNAcytsSwAsY0c2i7dIo

**Comment by bajamaster13** [comment]
Update:
Everything within the stone branch, Nether bricks, Red nether bricks, Mossy cobblestone, Quartz, and Purpur are all affected with this issue. continuing to test and will update if i find more.

**Comment by S-SHI777** [comment]
I will share my friend's video.
Something like an error message is shown at the end of that video. Perhaps it may help to solve the bug.
https://youtu.be/OL0V3vys7hY?si=PSbk0AYncEBOfhcr
Note: The server they are playing on is my server.
