### ISSUE TITLE
Bedrock Players having a constant load-bar when switching items.

### ISSUE THREAD

**Issue by frogman-pal** [GeyserMC/Geyser#5158]
### Describe the bug

Whenever a Bedrock Player switches items in my server, a full-blacked out loading bar appears for about half a second. It becomes very disruptive when its everytime.

My guess, is its trying to load something? I'm not sure, and I can't find any details online.

### To Reproduce

1. Play on a Bedrock Geyser Server
2. Switch Items
3. See if it happens?

### Expected behaviour

Should not show up with that loading bar all the time.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/6415da96-4ce9-4832-a842-76ad433c2b47)

### Server Version and Plugins

1.21.3, using Fabric, with a few server-side mods.

### Geyser Version

Build #715

### Minecraft: Bedrock Edition Device/Version

Latest, Xbox One

**Comment by Camotoy** [comment]
If you would like the cooldown indicator present, you can "fix" the black outline by going into Bedrock settings under the accessibility tab and setting "Text Background Opacity" to 0.
