### ISSUE TITLE
Invinsible players from BE side

### ISSUE THREAD

**Issue by E404NNF** [GeyserMC/Geyser#518]
**Describe the bug**

BE Players won't be able to see JE players in some scenarios (ex. a player joning a duels game or a skywars game)
**To Reproduce**
For me, it was joining a Duels game using the Duels plugin and that's it

**Expected behavior**

JE players appearing normally
**Screenshots / Videos**

https://streamable.com/z9k5az (Just take the Invinsible player thing from the vid only, the other bugs were fixed by just downgrading the ViaVersion plugin)
**Server Version**

This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Geyser Version**

build number 128
**Minecraft: Bedrock Edition Version**

1.14.60
**Additional Context**

LOG: https://pastebin.com/raw/hC1n1xva

**Comment by nedogimov** [comment]
Fix in 129.

**Comment by TheBloom46** [comment]
Having the same issue

**Comment by Mespeczek** [comment]
By using SkinRestorer, and Citizens2 entities like players are not visible for Bedrock Edition

**Comment by rtm516** [comment]
> By using SkinRestorer, and Citizens2 entities like players are not visible for Bedrock Edition

Tested Citizens2 in 1.15.2 paper yesterday and it didn't cause any issues.

**Comment by E404NNF** [comment]
Citizens 2 invisible bug was fixed with that "invincible players " commit, but it didn't slove my problem, still occurrs on build #140

**Comment by DoctorMacc** [comment]
Possibly a 1.12/1.13 issue?

**Comment by E404NNF** [comment]
I tried on 1.15.2 and I can confirm its indeed an issue on it too

**Comment by DoctorMacc** [comment]
OK, thank you.

**Comment by bundabrg** [comment]
I've reduced it down. In java by calling player.hidePlayer() the player will go invisible. Calling player.showPlayer() does not seem to reverse this.

You can replicate by installing EssentialX and typing /vanish which effectively does the same thing, or using SkinRestorer and changing skins (it hides/shows to refresh the skin)
