### ISSUE TITLE
Crafting recipes on Bedrock are annoyingly specific on Bedrock.

### ISSUE THREAD

**Issue by peashizzy** [GeyserMC/Geyser#5182]
### Describe the bug

Some examples include only being able to craft Crafting Tables using Dark Oak, and furnaces using cobbled deepslate.

### To Reproduce

1. Join the server on a bedrock client.
2. Get try and craft certain items such as crafting tables or furnaces.
3. recipie book won't auto place the items in the grid so you place them yourself.
4. the desired item won't appear even though it should.

### Expected behaviour

Bedrock players should be able to craft these without having to travel to specific biomes so that they can progress through the game normally.

### Screenshots / Videos

![image_2024-12-02_154200842](https://github.com/user-attachments/assets/e803cac7-ec8f-44e0-918d-d50a8b4c27a2)

### Server Version and Plugins

1.21.3 Paper

### Geyser Dump

https://dump.geysermc.org/7FnDS31CFv2kIqCehEjsgzmbdMhpOmVa

### Geyser Version

721 (Bedrock v1.20.80 - v1.21.44)

### Minecraft: Bedrock Edition Device/Version

1.21.44 Windows

### Additional Context

Aternos Logs https://mclo.gs/nWDwNdU

**Comment by adudeman** [comment]
I am experiencing this issue aswell, specifically for pistons and grindstones, is there a current fix or patch?

**Comment by Airtuboat72588** [comment]
Estoy teniendo exactamente el mismo problema 🫤

**Comment by Regaena** [comment]
i am also having this issue

**Comment by TripleBaconn** [comment]
having this issue too, mobile 1.21.50, java 1.21.3, bukkit/paper
