### ISSUE TITLE
Update to 1.21?

### ISSUE THREAD

**Issue by Villylily** [GeyserMC/Geyser#5187]
### What feature do you want to see added?

some way to fix bedrock players not being able to go under them and is geyser being updated with 1.21.0?

### Are there any alternatives?

nope

**Comment by onebeastchris** [comment]
Support for Bedrock versions below 1.21.40 was intentionally dropped to avoid maintenance complexity. We will not be re-adding it back - Bedrock automatically updates on all platforms, so there's few to none legitimate users stuck on older versions.

**Comment by Villylily** [comment]
it was java 1.21.0

**Comment by onebeastchris** [comment]
https://geysermc.org/wiki/geyser/supported-versions/ see our wiki for an answer to that.
