### ISSUE TITLE
Trap door bug

### ISSUE THREAD

**Issue by Villylily** [GeyserMC/Geyser#5188]
### Describe the bug

bedrock players crawling under trap doors get stuck and glitched  

### To Reproduce

Have a bedrock player enter crawl mode with a trap door and have them crawl Thur a tunnel 

### Expected behaviour

You will get stuck and glitched back as you try to crawl into a tunnel or under anything 

### Server Version and Plugins

fabric server 1.21.0 (java)

### Geyser Version

geyser-fabric-Geyser-Fabric-2.4.4-b705

### Minecraft: Bedrock Edition Device/Version

All devices 

### Additional Context

im pretty sure  this disables crawling in general

**Comment by Villylily** [comment]
i can get videos if needed

**Comment by Villylily** [comment]
and for java clients the crawl mode does work

**Comment by onebeastchris** [comment]
You're using an old version of Geyser - these are not supported. Please see https://geysermc.org/wiki/geyser/supported-versions/#using-geyser-fabric-or-geyser-neoforge-on-servers-that-do-not-run- on how you can continue to use an updated version of Geyser on an older fabric server.

**Comment by Villylily** [comment]
ik but the problem exist with the new one to

**Comment by onebeastchris** [comment]
In that case, please create a fully filled out issue report - with a geyser dump, reproduction steps, and screenshots/videos

**Comment by Villylily** [comment]
ok np
