### ISSUE TITLE
Text gui

### ISSUE THREAD

**Issue by OurLobanov** [GeyserMC/Geyser#5191]
### Describe the bug

Updated to the latest version of geysermc and got this situation on any version of minecraft, it's a geyser
![Screenshot_2024-12-05-01-08-07-90_04f6c37ab55ecd623db95e3ae9ffb9dc](https://github.com/user-attachments/assets/4a94cf58-ba26-4096-b0de-3ec1fb953b56)
![Screenshot_2024-12-05-01-10-16-87_04f6c37ab55ecd623db95e3ae9ffb9dc](https://github.com/user-attachments/assets/790dee03-dfc1-4318-b44b-07d0d5b44f79)

### To Reproduce

..

### Expected behaviour

..

### Geyser Version

https://github.com/GeyserMC/Geyser/commit/9e276c10777ddf73dacb4d35769f1801d42882d6

**Comment by OurLobanov** [comment]
we use a resource pack and it binds a specific event by text

**Comment by Camotoy** [comment]
Please share the resource pack code that makes this happen. To my knowledge, we wouldn't have changed anything concerning text.

**Comment by onebeastchris** [comment]
This appears to be purely client side - if it's fine without the resource pack, that's on you to fix in your pack

**Comment by OurLobanov** [comment]
I'm not very eager to share the resource pack with everyone. You can contact me on Discord, and I might send it to you. This might be related to the commit https://github.com/GeyserMC/Geyser/commit/ef4acb121f0f8746fa18a27f6acb1fc032ec7b2b.

I had to roll back the changes because the skins for entities were not attached, but Scarboard was working fine.

Perhaps some new commits have been released, which broke Scarboard due to this rework.

Tested on the original Geyser!

Discord: ourdev

**Comment by OurLobanov** [comment]
![IMG_20241205_174622_238](https://github.com/user-attachments/assets/3f408271-6bd8-4200-82ad-e398a965fd97)

**Comment by OurLobanov** [comment]
Our model should have been here but after that commit it broke

**Comment by onebeastchris** [comment]
I'm *assuming* you're talking about the way that your floating text (probably bound to the scoreboard) isn't aligned anymore. In which case, please send a screenshot *without* a resource pack enabled. That'll be more useful for us to see if we're misrepresenting the scoreboard, or whether you need to update your resource pack.

**Comment by OurLobanov** [comment]
![image](https://github.com/user-attachments/assets/0b535cb1-0dba-495a-aa83-9e0a286ae710)

**Comment by OurLobanov** [comment]
![image](https://github.com/user-attachments/assets/f680ab37-0929-4245-a0dc-b1822b356bcc)
Fixed
