### ISSUE TITLE
Java 1.21.4

### ISSUE THREAD

**Issue by I3iiel** [GeyserMC/Geyser#5193]
### What feature do you want to see added?

Hi guys, How you doing?
Do you know anything about a version compatible with New Java 1.21.4?

I did try the last version 05/12/2024 and i think Its only Works with 1.21.3

### Are there any alternatives?

.

**Comment by onebeastchris** [comment]
1.21.4 is being currently worked on, as per the announcement in the Geyser discord server:
![image](https://github.com/user-attachments/assets/0aac688c-261c-464a-81a6-2344eb6941c1)

**Comment by I3iiel** [comment]
Thank you for the answer!!
