### ISSUE TITLE
Crafting and game issues 

### ISSUE THREAD

**Issue by Woodsun190** [GeyserMC/Geyser#5204]
### Describe the bug

When I attempt to craft certain items while playing bedrock edition , for example, when I try to craft a crafting table I’m only able to use dark oak planks. Some other crafts, including, but not limited to making a shocker box i’m currently unaware of any other crafting issues.

### To Reproduce

to reproduce this load up a Java spigot server (current server version 1.21.4) and upload the geyser plug-in and the floodgate plug-in 
When the server is up log into Minecraft bedrock on PC and or mobile (problem occurs on consoles too, but the first two options are easier) and attempt to craft crafting table. As you will notice, you will only be able to use dark oak planks to craft the crafting table. 

### Expected behaviour

As from what I have experienced, you will only be able to craft certain items and or items will not be able to be crafted without specific material

### Screenshots / Videos

![IMG_1210](https://github.com/user-attachments/assets/debb0169-731c-4e95-8394-ee4d6a005dac)
![IMG_1209](https://github.com/user-attachments/assets/c500bfee-0ec7-423d-b170-132e9eb3d9a6)

### Server Version and Plugins

Spigot server version-1.21.4 
Geyser version-2.5.1
ViaVersion plugin-5.2.0
ViaBackwords plugin-5.2.0
Floodgate version-2.2.3

### Geyser Version

Geyser version-2.5.1 snapshot

### Minecraft: Bedrock Edition Device/Version

Minecraft bedrock 1.21.50 / PC

**Comment by ZhyKun22** [comment]
we have the same problem do you have any solution for that?
![Uploading Screenshot_20241209-191711.jpg…]()
