### ISSUE TITLE
Pale Oak showing up as missing/incorrect textures in new update for bedrock

### ISSUE THREAD

**Issue by w3edrat** [GeyserMC/Geyser#5205]
### Describe the bug

Pale oak logs, pale oak saplings, and the creaking heart all show up as "unknown" textures on bedrock console. The new flower for the biome appears as a torchflower.

### To Reproduce

Get any pale garden block on a bedrock console.

### Expected behaviour

Regular pale garden textures and blocks.

### Screenshots / Videos

I am not on my computer at the moment so I can't provide any, but please check if this is a geyser bug!

### Server Version and Plugins

1.21.4 spigot, 1.21.4 viaversion, viabackwards, geyser-spigot, floodgate

### Geyser Version

latest snapshot

### Minecraft: Bedrock Edition Device/Version

xbox, switch, pc

**Comment by onebeastchris** [comment]
This will be resolved by https://github.com/GeyserMC/Geyser/pull/5178 - it'll implement 1.21.4 features.
