### ISSUE TITLE
issue template to describe the bug with custom_mappings and custom model data:

### ISSUE THREAD

**Issue by xinge4088** [GeyserMC/Geyser#5212]
### Describe the bug

I have encountered a display bug when using custom_mappings to apply custom model data. The issue is that custom model data should only apply to specific items, but currently, it is being applied to all items of that type. This results in incorrect or unexpected item displays.

### To Reproduce

1.Set up a custom_mappings configuration with custom model data for specific items.
2.Apply this configuration to the items.
3.Observe that the custom model data is being applied to all items of the same type, not just the intended ones.

### Expected behaviour

custom model data should only be applied to the specific items defined in custom_mappings. Other items of the same type should not be affected and should display normally.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/a72a27b0-dfc1-4de0-bb00-3e285b4ad372)

### Server Version and Plugins

geyser and floodgate-spigot using last version

### Geyser Version

last version

### Minecraft: Bedrock Edition Device/Version

1.21.5

**Comment by xinge4088** [comment]
server have slimefun

**Comment by onebeastchris** [comment]
Could you provide an example? What kind of item does it apply to when it shouldn't? 

Please add e.g. commands (or show the item's data components with the `paper dumpitem` command while holding the item in question) so we can reproduce the issue.

**Comment by xinge4088** [comment]
As far as I know, almost all similar custom items in Slimefun, such as the iron ingot, will apply the specific custom model data 2200102 shown in the screenshot above. However, it will apply to all custom-textured iron ingots.

**Comment by onebeastchris** [comment]
Based on the mapping you showed it should apply to all item ingots with the custom model data of "2200102". What else does it apply to when it shouldn't? What item + custom model data is it?

**Comment by xinge4088** [comment]
Steps to Reproduce
Apply the custom models from the Slimefun resource pack.
Set CustomModelData: 2200102 for a specific iron ingot (using the resource pack).
Observe that all iron ingots with a custom texture (from Slimefun) are applying the model data 2200102, not just the intended items.

Expected Behavior
Only the specific iron ingots with the custom model data should have the model data 2200102, and other iron ingots with different custom textures should not use it.

**Comment by xinge4088** [comment]
even iron ingots with custom model data but a different value than 2200102 (i.e., other custom-textured iron ingots) are being incorrectly applied the same texture as the one with custom_model_data: 2200102 from the pack.

**Comment by xinge4088** [comment]
![Screenshot_2024-12-11-10-30-38-905_com mojang minecraftpe](https://github.com/user-attachments/assets/87e36234-f63e-46a8-bb09-be557d6bad85)

**Comment by onebeastchris** [comment]
Please run `paper dumpitem` with the other items, just so we can see what the data there is set to.

Further, please share your full mappings.json/resource pack - this sounds like an issue with how those are set up.

**Comment by xinge4088** [comment]
![image](https://github.com/user-attachments/assets/b156aa36-b495-41e4-97f4-cbdfea605ad6)
![image](https://github.com/user-attachments/assets/bd9fe02e-165f-4f73-8d7a-3f231010d760)

**Comment by xinge4088** [comment]
![Screenshot_2024-12-11-10-54-54-092_com mojang minecraftpe](https://github.com/user-attachments/assets/7788e8bf-5fcb-4678-b5fc-0a60d8563cba)
look zinc amd andmagnesium also using ai res

**Comment by onebeastchris** [comment]
There's the issue - you have multiple item mappings with the same item name (aluminum_ingot) without an icon property specified.

When there is no "icon" property set, it'll use the mapping's name to look for the texture in the Bedrock resource pack.

The solution here is:
- don't give different custom items the same name in the mappings
or
- set the "icon" mapping property that points to the texture that should be shown.

**Comment by xinge4088** [comment]
![Uploading Screenshot_2024-12-11-11-00-36-816_com.microsoft.rdc.androidx.jpg…]()

**Comment by xinge4088** [comment]
![Screenshot_2024-12-11-11-00-36-816_com microsoft rdc androidx](https://github.com/user-attachments/assets/4334c1b9-2fa0-4b86-ad4f-09129fe6e8c4)

**Comment by onebeastchris** [comment]
That's fine, and not the issue. The issue is in your mappings, you have multiple iron ingot's with different custom model data mapped to the same custom item texture
