### ISSUE TITLE
After updating geyser, bedrock people can't enter the server

### ISSUE THREAD

**Issue by senhorbe207** [GeyserMC/Geyser#5214]
### Describe the bug

Before the 1.21.50 geyser update, the bedrock players entered the server normally, after updating it, now i doesn't work,

I run the command "geyser connectiontest <IP> <Port>" in the console and it says my server is accessible from outside network, but when players try to enter the server i get the message "Unable to connect to world", what can i do i have seen the wiki but nothing works, sometimes bedrock players can enter but after 1-2 minutes they can't anymore

### To Reproduce

1. Start the server on Purpur 1.21.3-2358
2. Run playit.gg agent with bedrock tunnel configured
3. Try to enter the server on bedrock 1.21.50

### Expected behaviour

Bedrock players should enter normally

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/e2be5ae8-291f-4780-85c1-518923cfa810)

### Server Version and Plugins

Version: Purpur Version: 1.21.3-2358-16ce24a
Plugins: Geyser-spigot, Floodgate-Spigot, ViaVersion, ViaBackwards, Simple Voice Chat Spigot

### Geyser Dump

https://dump.geysermc.org/3HrVqfNzortzt7eyVuC97R1IhJ7SzbHF

### Geyser Version

Geyser version 2.5.1-b729 (git-master-b2045a5)

### Minecraft: Bedrock Edition Device/Version

1.21.50, Mobile, Windows 10/11 Edition

**Comment by onebeastchris** [comment]
When playing Minecraft: Bedrock edition on the same PC as where the server/geyser is hosted, you should set up loopback using this guide - https://geysermc.org/wiki/geyser/fixing-unable-to-connect-to-world#using-geyser-on-the-same-computer - and also connect with the local ip instead of the playit tunnel IP.

For further configuration help, please join the Geyser discord - we'd be happy to help there.

**Comment by senhorbe207** [comment]
loopback was activated but players from outside network can't enter

**Comment by onebeastchris** [comment]
Please join the Geyser support discord - we'll be able to help in detail there.

**Comment by senhorbe207** [comment]
entered it, making a support thread  now
