### ISSUE TITLE
Some sound effects are incorrect in BE

### ISSUE THREAD

**Issue by BUGTeas** [GeyserMC/Geyser#5217]
### Describe the bug

- `entity.generic.burn` (droping an item into lava) will make the incorrect sound of player being hurt
- `item.firecharge.use` (using a fire charge) will make the incorrect sound of using flint and steel
- `entity.arrow.hit_player` will make the incorrect sound of arrow hitted (it should make the sound of experience pickup).

### To Reproduce

(All operations are done on the Bedrock client)
1. Using a fire charge
2. Heard the sound of using flint and steel
3. Droping an item into lava
4. Heard a high-pitched sound of player being hurt
5. Use command: `/playsound item.firecharge.use player @s ~ ~1 ~`
6. Still heard the sound of using flint and steel
7. Use command: `/playsound entity.generic.burn player @s ~ ~1 ~`
8. Heard the sound of player being hurt
9. Use command: `/playsound entity.arrow.hit_player player @s ~ ~1 ~`
10. Heard the sound of arrow hitted

### Expected behaviour

I think Geyser is wrong with the sound mapping of the Bedrock, which should be correctable.

### Screenshots / Videos

Sounds in Java:

https://github.com/user-attachments/assets/eb2e1193-9164-4aa0-9271-ad16102899c6

---

Sounds in Bedrock:

https://github.com/user-attachments/assets/e3a8ae85-027f-4c72-bfa1-2c1f16d920a5

### Server Version and Plugins

CraftBukkit version 4402-Spigot-33ece3e-665900b (MC: 1.21.4) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
Plugins (1): Geyser-Spigot

### Geyser Dump

https://dump.geysermc.org/u90My6zCT1spAyvTec7lFr9gjjRvnwfw

### Geyser Version

2.6.0-b730 (git-master-ba5b422)

### Minecraft: Bedrock Edition Device/Version

1.21.50, Windows & Android

### Additional Context

This is a long-standing problem, not a recent one.

**Comment by letsgoawaydev** [comment]
seems like a mappings issue: https://github.com/GeyserMC/mappings

**Comment by onebeastchris** [comment]
Should be resolved in the latest version of Geyser, it bumps the mappings. Thanks once more for the PRs!
