### ISSUE TITLE
Blocks do not stack after crafting

### ISSUE THREAD

**Issue by kilivan4iK** [GeyserMC/Geyser#5220]
### Describe the bug

After I crafted a watermelon from my phone, it went into the inventory but did not stack

The same thing happens with the snow block, and with all the blocks that are similarly crafted

### To Reproduce

enter the crafting_table
click on the watermelon from the quick craft
craft a watermelon

### Expected behaviour

the watermelon after crafting should be stack with other watermelons

### Screenshots / Videos

https://github.com/user-attachments/assets/32f0c3d5-cfa8-45b6-9213-b5c8b25d81f7

https://github.com/user-attachments/assets/74a7e432-4e23-4427-ac84-fd87d1b67a6d

### Server Version and Plugins

Current Purpur Version: 1.21.3-2358-16ce24a (MC: 1.21.3)*
* You are running the latest version
Previous: 1.21.1-2329-803bf62 (MC: 1.21.1)

Velocity 3.4.0-SNAPSHOT (git-965db127-b454)

### Geyser Dump

https://dump.geysermc.org/Kg2iEg7DqTKK09vCD5d6PH3ExzHdWmZu

### Geyser Version

2.6.0-b730 (git-master-ba5b422) velocity

### Minecraft: Bedrock Edition Device/Version

1.21.50 android

**Comment by TotallyNotRiley** [comment]
I'm having the same issue, It seems to only affect mobile players as I couldn't replicate it on Bedrock Windows.

**Comment by OneLiteFeather** [comment]
A player on our server can replicate this issue on latest geyser (we update automaticly) and Paper 1.21.1 with prismarine shards on mobile

**Comment by xjulian3x** [comment]
Can confirm on Fabric 1.21.4

**Comment by onebeastchris** [comment]
Fixed with https://github.com/GeyserMC/Geyser/commit/6bd60d42339482580dd7f501d5ff436f63945a97. Thanks for reporting!
