### ISSUE TITLE
Water blocks are incorrectly displaying as red on maps

### ISSUE THREAD

**Issue by TotallyNotRiley** [GeyserMC/Geyser#5221]
### Describe the bug

Water blocks are incorrectly displaying as red on maps when viewed by Minecraft: Bedrock Edition clients.

### To Reproduce

1. Use a map near a body of water
2. Observe red water on map

### Expected behaviour

Water should appear blue on maps.

### Screenshots / Videos

![Capture](https://github.com/user-attachments/assets/e8cc9ae6-4095-4dbf-b779-5006722e5111)

### Server Version and Plugins

fabric-server-mc.1.21.4-loader.0.16.9-launcher.1.0.1
No plugins or mods

### Geyser Dump

https://dump.geysermc.org/6gFWGgtp5N1LtUnFDo3ZVLwI0UczO8lO 

### Geyser Version

Geyser version 2.6.0-b730 (git-master-ba5b422)

### Minecraft: Bedrock Edition Device/Version

1.21.51, Desktop and Mobile

**Comment by TotallyNotRiley** [comment]
Update: it seems that the sand block color is off as well. I've yet to test it with more blocks but I assume block colors are mostly off for bedrock maps.

**Comment by darkwolfie37** [comment]
I can confirm this. My Mother only plays on a playstation and is getting these red maps making it difficult to see biomes and such.

**Comment by dullstaples** [comment]
Also running into this issue.
Players on bedrock with map art are reporting this. Was able to replicate this on mobile.
