### ISSUE TITLE
Проблемы с крафтом

### ISSUE THREAD

**Issue by MisterHamster** [GeyserMC/Geyser#5222]
### Describe the bug

Предметы которые можно скрафтить из нескольких вариантов ресурса(например верстка, его можно скрафтить из досок любого дерева) больше не крафтится
Например верстка можно скрафтить только из досок тёмного дуба. 

### To Reproduce

1.взять любые доски (кроме досок тёмного дуба) 2.попытаться скрафтить из них верстка. 

### Expected behaviour

Я ожидаю возвращения возможности крафтите предмет такие как верстка, сундук, стол картографа, бочькаи т.д из разных видов досок.
И если есть ещё кикето предметы с такой-же ошибкой то жду возвращения ванильные крайтов этих предметов (тоесть из разных ресурсов). 

### Geyser Version

Я незнаю.

### Minecraft: Bedrock Edition Device/Version

Minecraft (patch) 1.21.50.  Устройство: Honor pad v6

**Comment by onebeastchris** [comment]
Please fill out bug reports in English!

Further, the bug you're describing was fixed in a recent version of Geyser - please update.
