### ISSUE TITLE
Failed to map the Packet ID 60 to a PacketType constant

### ISSUE THREAD

**Issue by daniel-skopek** [GeyserMC/Geyser#5223]
### Describe the bug

https://api.mclo.gs/1/raw/VNrCoXm

### To Reproduce

1. Join server with PacketEvents and after a some time you will be kicked

### Expected behaviour

No error

### Geyser Version

Geyser version 2.6.0-b730 (git-master-ba5b422)

### Additional Context

packetevents version 2.7.0

**Comment by onebeastchris** [comment]
Please test whether this is also occurring with a 1.21.4 Java client - this looks like a packetevents issue, not a Geyser one.

**Comment by onebeastchris** [comment]
Please actually verify that claim with a 1.21.4 Java client, which is what Geyser is emulating. 

Based on the info so far, this would probably be either a ViaVersion issue when remapping packets from 1.21.4 -> 1.21.2, or a Packetevents issue with 1.21.4. But, so far, without a plugin list or a geyser dump it's impossible to tell

**Comment by onebeastchris** [comment]
According to the Geyser dump you sent, which also includes a plugin list, you're running PacketEvents 2.6.0, not 2.7.0
