### ISSUE TITLE
Bedrock Players can't enter

### ISSUE THREAD

**Issue by senhorbe207** [GeyserMC/Geyser#5229]
### Describe the bug

When bedrock players try to enter the server, in the console says "127.0.0.1 tried to connect" (im using playit.gg btw) and they get the error "Unable to connect to world" what can i do?

### To Reproduce

1. Start the server
2. Try to enter with a bedrock 1.21.51-1.21.50 client

### Expected behaviour

Players enter normally

### Server Version and Plugins

Version: Purpur Version: 1.21.4-2371-4a204f1 (MC: 1.21.4)* 
Plugins: - AuthMe, floodgate, Geyser-Spigot, InvSeePlusPlus, ProtocolLib, ViaBackwards, ViaVersion, voicechat

### Geyser Dump

https://dump.geysermc.org/RJicelVRE4IkB9XHd3z65wTtvUYHibaU

### Geyser Version

Geyser version 2.6.0-b731 (git-master-c8dadd8)

### Minecraft: Bedrock Edition Device/Version

1.21.51, Mobile, Windows 10/11 Edition

**Comment by onebeastchris** [comment]
Please join the Geyser discord server for troubleshooting help with connection issues - it's easier to communicate there than here. Thanks!
