### ISSUE TITLE
Can't join bedrock players.

### ISSUE THREAD

**Issue by Yurielvillanueva** [GeyserMC/Geyser#5230]
### Describe the bug

**They cannot join to my minecraft server, it said Locating server**
i din't get the issues, so i crated a bug report. thanks for understanding

### To Reproduce

Always location Server

### Expected behaviour

Always location Server

### Server Version and Plugins

1.20.6 / 1.20.60

### Geyser Dump

https://dump.geysermc.org/RPmpEev5MRpQmrr9ki1Yn7ZWBWXzBJAr

### Geyser Version

version 2.5.0-b715 (git-master-abf6860) (Java: 1.21.3, Bedrock: 1.20.80/1.20.81 - 1.21.40 - 1.21.44

### Minecraft: Bedrock Edition Device/Version

1.20.6 / 1.20.60

**Comment by onebeastchris** [comment]
Please join the Geyser discord server and ask for help there - it's easier to troubleshoot connection issues there than here on Github. Thanks!

**Comment by Yurielvillanueva** [comment]
> Please join the Geyser discord server and ask for help there - it's easier to troubleshoot connection issues there than here on Github. Thanks!

I already joined.
