### ISSUE TITLE
Cow death sound mapped incorrectly 

### ISSUE THREAD

**Issue by JadeGril** [GeyserMC/Geyser#5233]
### Describe the bug

I don't know if it's terror, it's very common or someone else has already experienced it, but when you play in bedrock there is always a problem with the cows, they sound like fish when you kill them, there are also problems with the bamboo, if you try to cross the bamboo, it makes you bounce back. Will it be normal or good also the other problem is with the stalactite also the same thing that the bamboo makes you tilt backwards and that should not happen 

### To Reproduce

https://github.com/user-attachments/assets/062af4b9-efdb-4d6a-bcf7-831b2297bc65

https://github.com/user-attachments/assets/e351be4f-8c83-4ee2-9706-28aeb8384c69

### Expected behaviour

If there is a solution to this I hope it behaves as Minecraft bedrock should

### Screenshots / Videos

How can I solve those two errors that are in the video

### Server Version and Plugins

version 1.19.4 : Plugins_ floodgate,Geyser-Spigot,spark,Viaversion

### Geyser Dump

https://dump.geysermc.org/v3tfnptnhbtfG5HH95RHLnz6lMmzX1ab

### Geyser Version

Paper-550 (MC: 1.19.4) (Git: 483368)

**Comment by Jsaunders411** [comment]
Hurrican fabric mod/ paper plugin will fix bamboo and drip stone issue its a difference in hit boxes between java and bedrock.
