### ISSUE TITLE
Geyser don't want to load on mohist mc

### ISSUE THREAD

**Issue by LittleCoderX** [GeyserMC/Geyser#5234]
### Describe the bug

I want to start my geyser server with via version on moist fabric 1.21.1 but it doesn't. the log is linked
[latest.log](https://github.com/user-attachments/files/18210842/latest.log)

### To Reproduce

1. Install banner on your server
2. start server with geyser

### Expected behaviour

It doesn't load but I can connect to the server via java

### Server Version and Plugins

banner-1.21.1-149

### Geyser Version

the newest

**Comment by Camotoy** [comment]
This is an issue with one of our libraries. Regardless, we don't support Bukkit-Modded hybrids. Try using the Geyser modded platform instead.

**Comment by LittleCoderX** [comment]
is there a way to use geyser on 1.21.1 with the newest bedrock version
