### ISSUE TITLE
Problems running Geyser on Termux

### ISSUE THREAD

**Issue by E404NNF** [GeyserMC/Geyser#524]
**Describe the bug**

Geyser not able to download and save the the "en_us" local file
**To Reproduce**

just run Geyser on Termux using Ubuntu

**Expected behavior**

Just running normaly
**Screenshots / Videos**

https://prnt.sc/sdz3hu
**Server Version**

**Geyser Version**

Geyser build 129
**Minecraft: Bedrock Edition Version**

**Additional Context**

OS: Ubuntu 18 with XFCE
IPV4

**Comment by ItzLightyHD** [comment]
So, are you using Andronix Modded OS, right? I just use official Ubuntu distro from Andronix, then I install openjdk, and... it works really well, especially on good phones. Try using normal Andronix OSes, Ubuntu is recommended.

**Comment by rtm516** [comment]
No, he's likely just using the official Termux method. As mentioned here: https://github.com/GeyserMC/Geyser/wiki/Setup#Termux-Android

**Comment by E404NNF** [comment]
I'm using normal andronix not modded

**Comment by E404NNF** [comment]
Using arch Linux works instead

**Comment by rtm516** [comment]
> Using arch Linux works instead

So it works with Arch now?

**Comment by E404NNF** [comment]
Yeah

> > Using arch Linux works instead
> 
> So it works with Arch now?
