### ISSUE TITLE
Objects don't stack up and bags don't work.

### ISSUE THREAD

**Issue by MrShard** [GeyserMC/Geyser#5240]
### Describe the bug

When crafting, items don't stack up.
An ordinary bag has the texture of a shell, and also any bag does NOT work at all.

### To Reproduce

This happens for all players!

### Expected behaviour

-

### Screenshots / Videos

https://github.com/user-attachments/assets/55053de4-3f49-412a-be41-b652564e47e4

https://github.com/user-attachments/assets/b034eee1-4719-4b95-a642-2596547bd2ef

https://github.com/user-attachments/assets/625f84f5-e074-46c2-9da8-d7dda95a7b9f

### Geyser Version

2.6.0-b735

**Comment by onebeastchris** [comment]
Thanks for reporting the issues. However, they are both duplicates - of https://github.com/GeyserMC/Geyser/issues/5220 and https://github.com/GeyserMC/Geyser/issues/5146 respectively, so I'll close this issue.
