### ISSUE TITLE
Bedrock players cannot see blocks on nether roof

### ISSUE THREAD

**Issue by JustRedTTG** [GeyserMC/Geyser#5242]
### Describe the bug

On bedrock my friend was very confused when I told them to leave some materials in the nether when they went to the roof and saw no blocks at all, they couldn't even interact with them

### To Reproduce

1. As a Java player build something on the nether roof
2. Join from bedrock and go to the nether roof through a portal on the nether roof
3. You can't see or interact with the blocks on the nether roof

### Expected behaviour

Bedrock players should be able to see and interact with these blocks

### Screenshots / Videos

![IMG_0552](https://github.com/user-attachments/assets/a743accb-7d4e-4048-8187-65acaa18b347)

### Server Version and Plugins

Paper version 1.21.3-81-master@da71382

### Geyser Dump

https://dump.geysermc.org/y1mXCetlYiA0wRlsU995rAXDauKDtBbt

### Geyser Version

Geyser version 2.5.1-b726 git-master-2019e53

### Minecraft: Bedrock Edition Device/Version

Latest on IOS

**Comment by onebeastchris** [comment]
You can enable `above-bedrock-nether-building` in the Geyser config for a workaround that tricks the Bedrock client into being able to build on the nether roof.
