### ISSUE TITLE
Water does not place

### ISSUE THREAD

**Issue by MisterSheeple** [GeyserMC/Geyser#525]
**Describe the bug**
Water and lava buckets do not place water and lava

**To Reproduce**
1. Get a bucket of water or lava
2. Place it

**Expected behavior**
I expected it to place, but instead, the fluid vanishes almost instantly.

**Screenshots / Videos**
N/A

**Server Version**
git-Spigot-800b93f-29737cc (MC: 1.15.2)

**Geyser Version**
git-master-eeb4caf standalone

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
N/A

**Comment by MisterSheeple** [comment]
Just tested and this also is broken with lava

**Comment by ducanh2002123** [comment]
Hi,I got this issue too, one temporary workaround is to hold instead of tapping, somehow it just register as a right click on PC.

**Comment by MisterSheeple** [comment]
> Hi,I got this issue too, one temporary workaround is to hold instead of tapping, somehow it just register as a right click on PC.

This works for me too. Thanks!

**Comment by RednedEpic** [comment]
Closing in favor of #321 (added more info there). Long taps work for the time being, but this is not an ideal solution.
