### ISSUE TITLE
Ping Info

### ISSUE THREAD

**Issue by Legit4K** [GeyserMC/Geyser#527]
**What feature do you want?**
Correct ping measurements for Bedrock Players so anticheat can adjust accordingly. 

**Alternatives?**
Can't think of any alternatives

**Comment by Pan00Pernicek** [comment]
i support , antichet triggered jesus , when i was on vannila bedrock

**Comment by E404NNF** [comment]
"Ping measurements" will not fix anitcheat, if you are talking about anticheats like the CubeCraft one then yes, it will help but it will not help in anticheats like AAC

**Comment by Legit4K** [comment]
Perhaps not, but it helps in Premium anticheats like Spartan, the one we use.

**Comment by E404NNF** [comment]
Spartan uses ping to make sure the player is lagging, AAC doesn't, it just flags no matter what, because players can spoof their ping

**Comment by Legit4K** [comment]
Spartan has protection against sping poof u know

**Comment by E404NNF** [comment]
last time i tried like 5 months ago, i was able to bypass it somehow

**Comment by Legit4K** [comment]
Previous build had lots of false positives too, tho the recent build (346) performs quite well so far

**Comment by E404NNF** [comment]
hey, atleast it's better than NCP in 1.12.2 lmao

**Comment by Legit4K** [comment]
Lol forgot about the existence of NCP

**Comment by E404NNF** [comment]
they really need to update it, it got one of the best fly detections

**Comment by rtm516** [comment]
This may have to be added to Floodgate? Depending on how its implemented.

**Comment by Tim203** [comment]
> This may have to be added to Floodgate? Depending on how its implemented.

I don't see why this should be implemented into Floodgate

**Comment by rtm516** [comment]
> > This may have to be added to Floodgate? Depending on how its implemented.
> 
> I don't see why this should be implemented into Floodgate

I don't see a way geyser can do this, so I thought it could be spoofed using Floodgate to reflect the correct value
