### ISSUE TITLE
Incorrect hitboxes for Pigs

### ISSUE THREAD

**Issue by Legit4K** [GeyserMC/Geyser#528]
**Describe the bug**
Bedrock Players attempting to hit Pigs will have a small chance of actually getting a successful hit registered because their hitboxes seem to small.

**To Reproduce**
Find a Pig and try to kill it

**Expected behavior**
All hits should get registered

**Screenshots / Videos**
https://imgur.com/a/HLHMbWC

**Server Version**
This server is running Paper version git-Paper-272 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
Branch: Master
Type: Geyser-Bukkit
Build: 130

**Minecraft: Bedrock Edition Version**
1.14.6(0)

**Additional Context**
None for now

**Comment by rtm516** [comment]
Looks like the height is correct but the width gets set to 0
https://github.com/GeyserMC/Geyser/blob/edc8ea998c576bd7a7571ee4a1886619ffcc444b/connector/src/main/java/org/geysermc/connector/entity/type/EntityType.java#L45
