### ISSUE TITLE
[Suggestion] Turn this into an actual plugin (For people who are not able to host a standalone server).

### ISSUE THREAD

**Issue by EnderBro123** [GeyserMC/Geyser#54]
**What feature do you want?**
Make this a plugin for people who don't want to break their PC/public server.

**Alternatives?**
Any alternatives you have tryed
N/A

**Comment by RednedEpic** [comment]
This has been in consideration and is expected to come in the near future.

**Comment by Heath123** [comment]
How would it break anything?

**Comment by Malfrador** [comment]
> **What feature do you want?**
> Make this a plugin for people who don't want to break their PC/public server.
> 
> **Alternatives?**
> Any alternatives you have tryed
> N/A

I mean, it does not "break your server" in any way. The effects are similar to that of using a bungeecord server.

**Comment by EnderBro123** [comment]
Well, it can't run like, ANYTHING pretty much. And there's literally no plugins, for this "Software/Proxy" or whatever its called.

**Comment by RednedEpic** [comment]
> Well, it can't run like, ANYTHING pretty much. And there's literally no plugins, for this "Software/Proxy" or whatever its called.

Because there haven't been any plugins made for it yet. Geyser is not a server software, it's simply a proxy. The advantage to it being a proxy is that you can use it to join _any_ Java server, while if it were only a plugin, only servers with the "plugin" installed would be joinable with Bedrock edition.

**Comment by Malfrador** [comment]
> Well, it can't run like, ANYTHING pretty much. And there's literally no plugins, for this "Software/Proxy" or whatever its called.
> 
> Bukkit/Spigot intergration is pretty much the only way this'll grow.

I don't see any use for plugins here honestly. What should a plugin do? The goal is to translate the protocol from Bedrock to Java, so all "stuff" still happens on the Java server. 
Currently missing features like Inventories, Block breaking etc. are planned for Geyser itself, not for plugins.

**Comment by RednedEpic** [comment]
> > Well, it can't run like, ANYTHING pretty much. And there's literally no plugins, for this "Software/Proxy" or whatever its called.
> > Bukkit/Spigot intergration is pretty much the only way this'll grow.
> 
> I don't see any use for plugins here honestly. What should a plugin do? The goal is to translate the protocol from Bedrock to Java, so all "stuff" still happens on the Java server.
> Currently missing features like Inventories, Block breaking etc. are planned for Geyser itself, not for plugins.

The plugin API for Geyser will most likely be going away.

**Comment by Malfrador** [comment]
The only useful thing I could imagine would be a plugin that provides an API for the java server that returns the original IP of the player, as currently the server (obviously) only knows the IP of the Geyser proxy. Similar to how Bungee Cord and Spigot do it.

**Comment by Tim203** [comment]
I will probably not do it with an api, because it should be correct when logging in. But I can see that people would like to be able to use custom mappings or something like that. Or beeing able to tell that a client is a Geyser (Bedrock) client with some info like; is it a mobile player or a pc or...

**Comment by Malfrador** [comment]
> tell that a client is a Geyser (Bedrock) client with some info like; is it a mobile player or a pc or...
Telling if its a Geyser client or not should be possible by comparing the IP address I think. But if its PC or not would be useful, if the Bedrock client has that information.

**Comment by EnderBro123** [comment]
So, is this possible?

**Comment by RednedEpic** [comment]
> So, is this possible?
> 
> Also, we all know plugins, like Rainbow Armors or Hub creation plugins, etc. From Bukkit/Spigot.
> 
> With this, none of that can be used, so this is basically the vanilla jar with this support added to it.

This is going to have support to run as a plugin eventually, but as I already stated, this is not meant to run _in place_ of Bukkit or Spigot. You run this in addition to your Java server.

**Comment by Heath123** [comment]
This is possible, but what you said isn't true. This runs separately to the vanilla JAR. You don't have to modify your server and you can still use plugins. You can also use this to join servers like Hypixel.

**Comment by EOT3000** [comment]
already made. I'm closing this

**Comment by RednedEpic** [comment]
This is not yet in master though.

**Comment by EOT3000** [comment]
alright
