### ISSUE TITLE
Plugin support for Geyser standalone

### ISSUE THREAD

**Issue by tlaundal** [GeyserMC/Geyser#542]
**What feature do you want?**
Geyser standalone should have a simple infrastructure to load plugins from jar files.

**Alternatives?**
In lack of plugin support I had to modify the source code for the standalone bootstrap to run my plugin code. In my specific use case the plugin was sending logs and metrics from Geyser to a database for central analysis.

**Comment by Heath123** [comment]
Geyser used to have a plugin system but it was removed. I can think of a few uses for it (ViaVersion, things that they don't want to add but may be useful to some people) so maybe they should bring it back?

**Comment by RednedEpic** [comment]
> **What feature do you want?**
> Geyser standalone should have a simple infrastructure to load plugins from jar files.
> 
> **Alternatives?**
> In lack of plugin support I had to modify the source code for the standalone bootstrap to run my plugin code. In my specific use case the plugin was sending logs and metrics from Geyser to a database for central analysis.

This is something we had in the past and ultimately we decided plugins went beyond the scope of what Geyser was trying to accomplish. Most of the reasons we had the plugin API for initially could be done with Floodgate or other plugins installed on the server instead, so we decided to take it out due to that.

**Comment by tlaundal** [comment]
Just to provide some more information of my use case, which I think would not be possible to achieve with Floodgate:

- Get the amount of players connected to each Geyser instance (we are running multiple in parallel)
- Get memory information about the JVM Geyser is running in
- Adding a custom log appender to the logger Geyser is using

**Comment by endevrr** [comment]
You're right, what you want is currently not available from our current implementation, and the only way I can see you achieving what you want is adding plugin support, I think if we want to move in the direction of supporting larger networks (although we're a way from that right now) plugin support is necessary, I'll let the rest of the team know and hopefully we can get something figured out.

**Comment by Heath123** [comment]
I can see some uses for this too. I think we should consider adding it back.

**Comment by DoctorMacc** [comment]
To give my opinion, there's definitely merit in reviving plugins; I don't think it's a good idea now that 1.16 is surely around the corner, and we are getting closer to feature-perfect. Once that's done I don't see why we can't have a basic plugin API, or giving developers or statistics nerds something to play it.

**Comment by DoctorMacc** [comment]
Reopening so we don't keep getting issue requests for this.

**Comment by DeeRenjie** [comment]
If only mobile players could display GUI like menus.

**Comment by Camotoy** [comment]
Update: that branch has been merged.
