### ISSUE TITLE
Cant join server because of resourcepack

### ISSUE THREAD

**Issue by xxminersx** [GeyserMC/Geyser#546]
**Describe the bug**
When i join a server i get kicked because i need to accept a resourcepack

**To Reproduce**
1. Go to server.sprookjescraft.nl 
 2. Walk around for a bit
 3. Get kicked because you need to accept a resourcepack

**Expected behavior**
I can just join the server and play on it 

**Server Version**
1.8.x-1.15.x (BungeeCord) 

**Geyser Version**
Geyser version 142 standalone / Geyser version 1.0-SNAPSHOT (git-master-46b0054)

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by RednedEpic** [comment]
> **Describe the bug**
> When i join a server i get kicked because i need to accept a resourcepack
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to server.sprookjescraft.nl
> 2. Walk around for a bit
> 3. Get kicked because you need to accept a resourcepack
> 4. See error
> 
> **Expected behavior**
> I can just join the server and play on it
> 
> **Server Version**
> 1.8.x-1.15.x (BungeeCord)
> 
> **Geyser Version**
> Geyser version 142 standalone / Geyser version 1.0-SNAPSHOT (git-master-46b0054)
> 
> **Minecraft: Bedrock Edition Version**
> 1.14.60

Resource pack translation is not implemented in Geyser yet, which is why you’re getting this. Closing in favor of #210.
