### ISSUE TITLE
Carpets cause Bedrock Edition players to float

### ISSUE THREAD

**Issue by piperwillow** [GeyserMC/Geyser#548]
**Describe the bug**
When a bedrock player is standing on carpet, java players see them standing a half block up.

**To Reproduce**
![image](https://user-images.githubusercontent.com/18108126/81828469-6c229b00-94ff-11ea-95ab-2e5cda634922.png)

**Expected behavior**
To not be floating above the carpet.

**Server Version**
This server is running Paper version git-Paper-282 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-273 (MC: 1.15.2)

**Geyser Version**
Geyser-Bukkit Build 140 with Floodgate

**Minecraft: Bedrock Edition Version**
Version 1.14.60
Build: 3968506

**Additional Context**
Don't know if this would affect it at all but I also have ViaVersion/ViaBackwards 3.0.0 SNAPSHOT and Vivecraft Spigot Extensions.

**Comment by LiteButInversed** [comment]
Looks like that's the same on water lilies

![2020-05-15_01 52 37](https://user-images.githubusercontent.com/65375598/81997869-49a09700-9651-11ea-9c91-ee4fbde168d5.jpg)

**Comment by RainMa22** [comment]
This also means that bedrock player cant go through 2 block high space if carpet is in place.

**Comment by DoctorMacc** [comment]
Sneaking works as an alternative to that for the time.

**Comment by MarioFinale** [comment]
I would like to add that it also happens with beds (in this case beds are counted as a full block).
Screenshot:
![image](https://user-images.githubusercontent.com/15223565/88112881-b61ea180-cb7e-11ea-9d34-afbd00316611.png)

**Comment by ChickenSaysBak** [comment]
This also happens with pressure plates.

**Comment by Hellohi3654** [comment]
any half-block causes this action as far as I know

**Comment by rtm516** [comment]
> any half-block causes this action as far as I know

It will happen with anything that isn't a full block or exactly half as it rounds up to the nearest full block
