### ISSUE TITLE
Ominous banner does not have translation

### ISSUE THREAD

**Issue by Vesek** [GeyserMC/Geyser#555]
**Describe the bug**
When you have ominous banner in your inventory it is white and name is not translated.

**To Reproduce**
1. Get ominous banner.
2. Open your inventory and click on it.
3. It will show {"color":"gold,"translate":"block.minecraft.ominous_banner"}

**Expected behavior**
It will show Ominous banner in gold as name.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/61123478/81965850-ee52b280-9618-11ea-96c5-c93aa277c410.png)

**Server Version**
Paper 1.15.2 Version 208

**Geyser Version**
Geyser bukkit, newest master merged with resource branch and entity-mounts branch.

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
Nothing

**Comment by RednedEpic** [comment]
Closing in favor of #508.
