### ISSUE TITLE
Could not translate packet ServerTitlePacket

### ISSUE THREAD

**Issue by OverBrave** [GeyserMC/Geyser#556]
**Describe the bug**
Geyser spamming error when join the server.

Note : 
This issue only occurs when geyser is run alone. If run in bungeecord or another server, not giving this error.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/47111280/81968521-2a8c1000-9625-11ea-8abc-906a81757147.png)

**Server Version**
![image](https://user-images.githubusercontent.com/47111280/81968615-4c859280-9625-11ea-8a8a-534e3175108f.png)

**Geyser Version**
Dev build #148

**Minecraft: Bedrock Edition Version**
1.14.60

Server ip: Oyna.SonCesurlar.Com (its java version ip)

**Comment by OverBrave** [comment]
This problem happens because I use the AuthmeTitle plugin.

**Comment by rtm516** [comment]
https://www.spigotmc.org/resources/authmetitle-now-with-animated-titles.54477/

He is also using animated titles, so likely the message handler is getting some strange json data

**Comment by RednedEpic** [comment]
Closing in favor of #557.
