### ISSUE TITLE
Geyser Packet Errors

### ISSUE THREAD

**Issue by OverBrave** [GeyserMC/Geyser#557]
**Describe the bug**
Geyser spamming error when join the server.

Note :
This issue only occurs when geyser is run alone. If run in bungeecord or another server, not giving this error.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/47111280/81970042-940d1e00-9627-11ea-913c-889284a34e4e.png)
![image](https://user-images.githubusercontent.com/47111280/81970026-8e173d00-9627-11ea-9b61-d7606e6ab472.png)
![image](https://user-images.githubusercontent.com/47111280/81970072-9ec7b300-9627-11ea-89e9-f5597f1b2388.png)
![image](https://user-images.githubusercontent.com/47111280/81970175-c1f26280-9627-11ea-9525-6677d3e75029.png)

**Server Version**
![image](https://user-images.githubusercontent.com/47111280/81970257-e2bab800-9627-11ea-835d-ac58f8c450a8.png)

Geyser Version
Dev build #148

Minecraft: Bedrock Edition Version
1.14.60

Server ip: Oyna.SonCesurlar.Com (its java version ip)

**Comment by blubbll** [comment]
Does this issue only happen after the user timed out? And does connecting work?

**Comment by OverBrave** [comment]
No, players cant join the server.

**Comment by OverBrave** [comment]
I use CMI as the chat plugin.

https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

**Comment by rtm516** [comment]
First 2 are something related to armour stands the last is chat

**Comment by OverBrave** [comment]
When will be fixing this bug ?

**Comment by bundabrg** [comment]
It was failing in getBedrockMessage with a message of these bytes:
```
[32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, -89, 98, 63, -89, 51, 63, 32, -89, 51, -89, 108, 83, 79, 78, -89, 98, -89, 108, 67, 69, 83, 85, 82, 76, 65, 82, 32, -89, 98, 63, -89, 51, 63, 32, -89, 57, -89, 110, 80, 65, 84, 67, 72, 32, 35, 49, 53, 46, 50, -89, 114, 10, 32, 32, 32, 32, 32, 32, -89, 102, -89, 108, -69, 32, -89, 99, 89, 101, 110, 105, 32, -25, 101, 107, 105, 108, 105, -2, 32, 118, 101, 32, 105, 110, 100, 105, 114, 105, 109, 108, 101, 114, 105, 32, 115, 97, 107, -3, 110, 32, 107, 97, -25, -3, 114, 109, 97, 33]
```

This string apparently passes the isMessage check to see if its a JSON string (its not).

**Comment by bundabrg** [comment]
actually I was looking at the wrong thing. It looks like its failing when a Message has no text component and is instead only made up of extra. Still investigating.

**Comment by bundabrg** [comment]
Related to #686 

It happens because there the Message contains a null color. I'm not even sure how thats possible.

**Comment by OverBrave** [comment]
I know,
&d its pink but showing white.
