### ISSUE TITLE
Option to Remember login

### ISSUE THREAD

**Issue by TheMasterBlaster** [GeyserMC/Geyser#558]
**What feature do you want?**
A toggle switch on the "Login Details" prompt to "Remember" the last Java account you logged in as (possibly check for same Username and IP?). Geyser could  then add a button on the "Login" prompt for you next time you connect to join as that account again. I'm not sure if this would even be possible but It could be very useful for people that cant use or don't want Floodgate to link Java accounts to Bedrock accounts on their server.

**Comment by RednedEpic** [comment]
> **What feature do you want?**
> A toggle switch on the "Login Details" prompt to "Remember" the last Java account you logged in as (possibly check for same Username and IP?). Geyser could then add a button on the "Login" prompt for you next time you connect to join as that account again. I'm not sure if this would even be possible but It could be very useful for people that cant use or don't want Floodgate to link Java accounts to Bedrock accounts on their server.

This is not something we intend to do as it directly gives server owners the login credentials of other players. There is a `userAuths` section in the config which allows for you to enter your credentials into the file itself and have it automatically log in for you, but it is only recommended you use this in instances where you're the only one joining Geyser or the only one with access to the config file.
