### ISSUE TITLE
Bedrock Players Can Not see Java 

### ISSUE THREAD

**Issue by christianfirecup** [GeyserMC/Geyser#562]
**Describe the bug**
When teleporting to a new world java player can see bedrock but not vise versa

**To Reproduce**
teleport to any world using muitiverse 
look for java players
java can see you but bedrock cant see java

**Expected behavior**
both bedrock and java can see each other

**Screenshots / Videos**

**Server Version**
1.13.2 stable

**Geyser Version**
git-master-919af52

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**

**Comment by rtm516** [comment]
Possibly a duplicate of #518

**Comment by DoctorMacc** [comment]
Yes, I'm closing this in favor of #518 for a central issue.
