### ISSUE TITLE
ViaVersion Broken PIPE

### ISSUE THREAD

**Issue by zRedblood** [GeyserMC/Geyser#577]
There are a problem when BedRock player try to join on a 1.14 server that allow 1.15.2 players to join thanks ViaVersion plugin, this cause crash of Geyser Proxy/Plugin.

Fix this and add a blacklist servers for bungee to deny player join in certain servers.

Error: https://pastebin.com/raw/SQpRYbrt

**Comment by DoctorMacc** [comment]
Please follow the issue template.

**Comment by RednedEpic** [comment]
Duplicate of #384, and disable ping passthrough for the time being to fix this.
