### ISSUE TITLE
Issues with the new remapper

### ISSUE THREAD

**Issue by Malfrador** [GeyserMC/Geyser#58]
Issues with the new remapper I found so far:

- Some Leaves (Oak?) have no collision, you can walk/bug yourself inside of them
- CPU usage is still very high and also spikes now when loading a new chunk
![jprofiler_2019-10-10_16-40-39](https://user-images.githubusercontent.com/6106558/66579865-c6c8d280-eb7d-11e9-9a61-7c824e38d940.png)
- Water gets more transparent if you go near it and finally becomes invisible
- Stairs have the collision of a normal full size block, you can only walk downwards. Steps work fine
- Ladders do not work (but probably also do not work in the old remapper
- Wall signs with text on them are invisible. Signs without text work fine
- All blocks have no collision from below when flying/jumping into them
- Pistons are missing the head
- Prismarine lamps (how are they called? the underwater glowstone thingy) are still dirt

**Comment by EOT3000** [comment]
can you post a larger timings image? This doesn't show much...

**Comment by Malfrador** [comment]
![javaw_2019-10-10_17-09-15](https://user-images.githubusercontent.com/6106558/66603698-01962f00-ebad-11e9-8d63-d54e8141fa7a.png)
That is the other image I have currently, using VirtualVM as a profiler.

**Comment by EOT3000** [comment]
that is scary... WIll commit soon, try using that

**Comment by Tim203** [comment]
pr* :wink:

**Comment by EOT3000** [comment]
to a new branch though,

**Comment by EOT3000** [comment]
whoops

**Comment by EOT3000** [comment]
partly fixed

**Comment by RednedEpic** [comment]
The CPU usage is only noticeable upon joining the proxy and changing worlds. Other than that, chunk loading seems to have very little impact on performance. As for some of the issues stated, some of them have to do with the fact that block entities aren't supported yet, and collision hasn't been entirely added either.

Currently, piston heads are the only issue right now that I encountered related to the remapper. The water issue has to do with some extra stuff that doesn't exactly relate to the remapper. I was unable to replicate the issue with leaves; I could not walk through them.

**Comment by RednedEpic** [comment]
Piston head is a block entity. This should be resolved in [`block-entities`](https://github.com/GeyserMC/Geyser/tree/block-entities).

**Comment by RednedEpic** [comment]
Closing since the only problem remaining in this issue doesn't quite pertain to the remapper or blocks itself. It has since been resolved in the block entities branch as mentioned above, and will find it's way into master once merged.
