### ISSUE TITLE
Bedrock players cannot be pulled with fishing rod.

### ISSUE THREAD

**Issue by jackson-57** [GeyserMC/Geyser#582]
**Describe the bug**
On Java Edition, players can be "fished up" by using the fishing rod on them. This will move them around and/or launch them into the air. When a fishing rod is used on a Bedrock player connected via Geyser, they stay still and aren't launched into the air.

**To Reproduce**
1. Attach the fishing rod to a Bedrock player connected via Geyser
2. "Reel in" the fishing rod

**Expected behavior**
Bedrock player should be moved around or launched into the air.

**Screenshots / Videos**
Let me know if a video demo of the bug would be helpful.

**Server Version**
Paper 284, Minecraft 1.15.2

**Geyser Version**
Geyser master branch 152, Bukkit plugin version.

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by DoctorMacc** [comment]
Should be fixed with #580.

**Comment by jackson-57** [comment]
I didn't know if that PR was just for the fishing rod line visual or if it would fix this. I'll go test that PR, thanks

**Comment by jackson-57** [comment]
Just checked, #580 does not fix this bug.

**Comment by DoctorMacc** [comment]
Thank you for testing.
