### ISSUE TITLE
Mass "InitialHandler has pinged" spam from Geyser to Bungeecord

### ISSUE THREAD

**Issue by SpazmasterYT** [GeyserMC/Geyser#583]
**Describe the bug**

After loading the geyser plugin on bungeecord the logs will quickly fill up with 
"[/127.0.0.1:43782] <-> InitialHandler has pinged" hundreds of times in a minute. Other than that, no other strange behavior found. This is a problem as logs are stored on the hard drive for some users for backup and security reasons and this can quickly clutter the logs and use up space.

**To Reproduce**

1) install and configure Geyser and Floodgate plugins on Bungeecord
2) run MC server on external VPS
3) run Bungee after its been configured to point to VPS 
4) once Bungee is fully started and Geyser and Floodgate are enabled "[/127.0.0.1:xxxx] <-> InitialHandler has pinged" will begin to start piling up quickly, about 1 per second.

**Expected behavior**

Definately not a flood of ping notifications. I expected ping notifications to show up when users initiate a ping request from their client but not a localhost ping every second

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/44085597/82135154-e3d51c00-97c4-11ea-9675-5c399e1ad6ca.png)

**Server Version**

Paper version git-Paper-274 (MC: 1.15.2)

**Geyser Version**

plugin Geyser-BungeeCord version 1.0-SNAPSHOT by GeyserMC
plugin floodgate-bungee version 1.0-SNAPSHOT by GeyserMC

**Minecraft: Bedrock Edition Version**

v1.14.60 

**Additional Context**

Other than the piles and piles of ping notifications from localhost, users are able to join without any other problems.

**Comment by DoctorMacc** [comment]
This is a result of Geyser's ping passthrough thread updating every second. This will be fixed with #468 .
