### ISSUE TITLE
Trading button will not be displayed

### ISSUE THREAD

**Issue by SinanGentoo** [GeyserMC/Geyser#593]
**Describe the bug**
Trading button will not be displayed when facing villagers (long press is effective)

**To Reproduce**
1.Facing a villager
2.Trading button will not be displayed

**Expected behavior**
The button can be displayed correctly

**Screenshots / Videos**
![Pictures](https://i.niupic.com/images/2020/05/19/7TEX.jpg)

**Server Version**
PaperSpigot 1.15.2(174)

**Geyser Version**
#2 feature/villager-trading

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**

**Comment by RednedEpic** [comment]
Unimplemented, see the README. There is also a branch where this is being worked on, so feel free to test that.
