### ISSUE TITLE
ProtocolSupport is incompatible; only with Floodgate

### ISSUE THREAD

**Issue by oezingle** [GeyserMC/Geyser#599]
**Describe the bug**
When connecting with MCPE iOS, the user returns the error 
 Invalid packet id: 27
Only while using Floodgate authentication and the ProtocolSupport plugin. without floodgate, the system both works in online and offline modes. Java Minecraft players can connect in any version, as is supported by ProtocolSupport.

**To Reproduce**
Install Geyser-Bukkit, Floodgate-Bukkit and ProtocolSupport on a PaperMC server in /plugins/. Configure Geyser to use Floodgate. 
When the bug occurs, the output is exactly the same as that of an incorrectly configured Floodgate installation

**Server Version**
[17:13:44 INFO]: This server is running Paper version git-Paper-301 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**

**Minecraft: Bedrock Edition Version**
1.14.60 hotfix

**Comment by DoctorMacc** [comment]
I'm closing this since it's a Floodgate issue; could you please file this as an issue in the Floodgate repository?
