### ISSUE TITLE
Mappings should be dynamically updated

### ISSUE THREAD

**Issue by bundabrg** [GeyserMC/Geyser#601]
**What feature do you want?**
Instead of packing mappings in the jar the system should check at runtime during startup and pull down the latest relevant version.

This will save all the mappings updates and remove even the need for submodules.

**Comment by lukeeey** [comment]
Mappings are unlikely to change between game versions (and new game versions would mean Geyser has to be updated anyway)

**Comment by Camotoy** [comment]
> Mappings are unlikely to change between game versions (and new game versions would mean Geyser has to be updated anyway)

I agree here that this isn't relevant for block and item mappings. Languages, maybe, but it's better to update those with new strings anyway.
