### ISSUE TITLE
Signs invisible on older Paper builds

### ISSUE THREAD

**Issue by Giant3004** [GeyserMC/Geyser#603]
Bedrock client
no signs are visible

Java version 1.12.2

i using viaversion and protocol support

This bug is in the current geyser build

The geyser 120 build cannot find this error.

The signs appear when we knock out the boards and then they appear

video: https://www.youtube.com/watch?v=2GKCNLLCajs

I apologize for the errors a
I'm Hungarian

**Comment by rtm516** [comment]
> Bedrock client
> no signs are visible
> 
> Java version 1.12.2
> 
> i using viaversion and protocol support
> 
> This bug is in the current geyser build
> 
> The geyser 120 build cannot find this error.
> 
> The signs appear when we knock out the boards and then they appear
> 
> video: https://www.youtube.com/watch?v=2GKCNLLCajs
> 
> I apologize for the errors a
> I'm Hungarian

Please follow the issue format

**Comment by Mespeczek** [comment]
This same problem ;/

**Comment by DoctorMacc** [comment]
This specifically should affect Paper builds up until recent 1.15.2 builds.

**Comment by Mespeczek** [comment]
So... Paper Spigot 1.12.2 is not supported?

**Comment by towuk118** [comment]
I use spigot 1.11 version server and geyser bukkit worked!!!

**Comment by Mespeczek** [comment]
I am using geyser as standalone

**Comment by Hyronymos1337** [comment]
same problem with latest tacospigot 1.8.8, geyser on bungeecord

**Comment by E404NNF** [comment]
![image](https://user-images.githubusercontent.com/37207067/83332413-5a7d1980-a29b-11ea-97b4-09fbe7b3d8c7.png)
this problem is on uhh, paper 1.15.2

**Comment by DoctorMacc** [comment]
@E404NNF which Paper version?

**Comment by E404NNF** [comment]
It says "git-Paper-143" "you're 184 versions behind"

**Comment by DoctorMacc** [comment]
Update the Paper build and signs should reappear.

**Comment by RednedEpic** [comment]
Is this still a problem?

**Comment by DoctorMacc** [comment]
Invisible text on signs is still a problem. Invisible signs I cannot confirm.

**Comment by Hyronymos1337** [comment]
I can confirm that the bugg doesn’t happen on 1.8.8 tacospigot

**Comment by Camotoy** [comment]
This appears to have been resolved.
