### ISSUE TITLE
Tridents not rendering on BR

### ISSUE THREAD

**Issue by HURULD** [GeyserMC/Geyser#604]
**Describe the bug**
Tridents do not render for the bedrock client. The sounds play and they can be thrown and picked up. Only visual.

**To Reproduce**
Throw a trident either from Java or Bedrock.
The trident will be visible on Java but not on bedrock

**Screenshots / Videos**
![tridents](https://user-images.githubusercontent.com/20422328/82444133-a7dad900-9a9a-11ea-989a-a5b04fffc80a.gif)

**Server Version**
Paper version git-Paper-298 (MC: 1.15.2)

**Geyser Version**
Geyser-Bukkit master/164

**Minecraft: Bedrock Edition Version**
Windows 10 - 1.14.6005.0

**Additional Context**
Plugins:
`Clearlagg,
CoreProtect,
DiscordSRV,
EssentialsX,
EssentialsX Chat,
EssentialsX Spawn,
Floodgate,
InventoryRollback,
LuckPerms,
Orebfuscator,
PlaceholderAPI,
ProtocolLib,
SaveDeathDrops,
ServerListPlus,
CommandSigns,
Vault,
WorldBorder,
WorldEdit,
WorldGuard,
WorldGuardExtraFlags`

**Comment by rtm516** [comment]
Likely caused by a missing EntityType identifier
