### ISSUE TITLE
Bug with stone varients of stairs

### ISSUE THREAD

**Issue by Legit4K** [GeyserMC/Geyser#605]
**Describe the bug**
The stone varients of stairs will disappear when a Bedrock Client walks over them.
I can verify that they were successfully placed because a simple relog shows that the stone stairs were still in their correct position. 

**To Reproduce**
Walk up some (stone varient) stairs. 

**Expected behavior**
Successfully walk up stairs without them disappearing and causing movement desync. 

**Screenshots / Videos**
[Video 1](https://imgur.com/a/0OpWefr)
[Video 2](https://imgur.com/a/2A1RetH)

**Server Version**
`git-Paper-304`

**Geyser Version**
Type: Geyser-Bukkit
Branch: master
Build: 162

**Minecraft: Bedrock Edition Version**
1.14.6(0)

**Additional Context**
I can further verify that the stairs were all placed because I was able to mine and retrieve them in my inventory.
Furthermore, the disappearnce happens *after*  walking on the top half of the stair block.

**Comment by Pan00Pernicek** [comment]
similiar isue (but with bamboo) exist too
when walking in bamboo bamboo sometimes disapears

**Comment by Legit4K** [comment]
After discovering that this Bug is specific to my server, I will close this issue. The root cause lies in the Spartan anticheat plugin, who released a fix for this issue a few days ago so I've updated and everything is fine now :smile:
