### ISSUE TITLE
Internal error on reload Geyser (Bungee)

### ISSUE THREAD

**Issue by Paul19988** [GeyserMC/Geyser#613]
**Describe the bug**
Internal errors after having an incorrect or invalid assignable address

**To Reproduce**
1. Set invalid IP address
2. Reload Geyser(Bungee)

**Expected behavior**
Fail to run server and report error, then allow reload to fix broken IP

**Server Version**
git-paper-300

**Geyser Version**
Build number 170

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by endevrr** [comment]
From what I can tell this is a bug with our config reloading system

**Comment by RednedEpic** [comment]
> **Describe the bug**
> Internal errors after having an incorrect or invalid assignable address
> 
> **To Reproduce**
> 
> 1. Set invalid IP address
> 2. Reload Geyser(Bungee)
> 
> **Expected behavior**
> Fail to run server and report error, then allow reload to fix broken IP
> 
> **Server Version**
> git-paper-300
> 
> **Geyser Version**
> Build number 170
> 
> **Minecraft: Bedrock Edition Version**
> 1.14.60

Can you please provide the error itself?

**Comment by Paul19988** [comment]
Here's the error it threw
```
10:49:59 [SEVERE] [Geyser-BungeeCord] Failed to start Geyser on <ip>:19132
10:49:59 [SEVERE] java.util.concurrent.CompletionException: java.net.BindException: Cannot assign requested address
10:49:59 [SEVERE] 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
10:49:59 [SEVERE] 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
10:49:59 [SEVERE] 	at java.util.concurrent.CompletableFuture.biRelay(CompletableFuture.java:1298)
10:49:59 [SEVERE] 	at java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1284)
10:49:59 [SEVERE] 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
10:49:59 [SEVERE] 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
10:49:59 [SEVERE] 	at com.nukkitx.network.util.Bootstraps.lambda$allOf$0(Bootstraps.java:111)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:994)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:553)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
10:49:59 [SEVERE] 	at java.lang.Thread.run(Thread.java:748)
10:49:59 [SEVERE] Caused by: java.net.BindException: Cannot assign requested address
10:49:59 [SEVERE] 	at sun.nio.ch.Net.bind0(Native Method)
10:49:59 [SEVERE] 	at sun.nio.ch.Net.bind(Net.java:433)
10:49:59 [SEVERE] 	at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:698)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.SocketUtils$6.run(SocketUtils.java:125)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.SocketUtils$6.run(SocketUtils.java:122)
10:49:59 [SEVERE] 	at java.security.AccessController.doPrivileged(Native Method)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.SocketUtils.bind(SocketUtils.java:122)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:199)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:194)
10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
10:49:59 [SEVERE] 	... 12 more
10:49:59 [INFO] §cAn internal error occurred whilst executing this command, please check the console log for details.
10:49:59 [WARNING] Error in dispatching command
java.util.concurrent.CompletionException: java.net.BindException: Cannot assign requested address
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.biRelay(CompletableFuture.java:1298)
	at java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1284)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at com.nukkitx.network.util.Bootstraps.lambda$allOf$0(Bootstraps.java:111)
	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:994)
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:553)
	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at org.geysermc.platform.bungeecord.shaded.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:698)
	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.SocketUtils$6.run(SocketUtils.java:125)
	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.SocketUtils$6.run(SocketUtils.java:122)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.SocketUtils.bind(SocketUtils.java:122)
	at org.geysermc.platform.bungeecord.shaded.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:199)
	at org.geysermc.platform.bungeecord.shaded.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:194)
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	... 12 more
```

**Comment by RednedEpic** [comment]
> Here's the error it threw
> 
> ```
> 10:49:59 [SEVERE] [Geyser-BungeeCord] Failed to start Geyser on <ip>:19132
> 10:49:59 [SEVERE] java.util.concurrent.CompletionException: java.net.BindException: Cannot assign requested address
> 10:49:59 [SEVERE] 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
> 10:49:59 [SEVERE] 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
> 10:49:59 [SEVERE] 	at java.util.concurrent.CompletableFuture.biRelay(CompletableFuture.java:1298)
> 10:49:59 [SEVERE] 	at java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1284)
> 10:49:59 [SEVERE] 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
> 10:49:59 [SEVERE] 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
> 10:49:59 [SEVERE] 	at com.nukkitx.network.util.Bootstraps.lambda$allOf$0(Bootstraps.java:111)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:994)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:553)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 10:49:59 [SEVERE] 	at java.lang.Thread.run(Thread.java:748)
> 10:49:59 [SEVERE] Caused by: java.net.BindException: Cannot assign requested address
> 10:49:59 [SEVERE] 	at sun.nio.ch.Net.bind0(Native Method)
> 10:49:59 [SEVERE] 	at sun.nio.ch.Net.bind(Net.java:433)
> 10:49:59 [SEVERE] 	at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:698)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.SocketUtils$6.run(SocketUtils.java:125)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.SocketUtils$6.run(SocketUtils.java:122)
> 10:49:59 [SEVERE] 	at java.security.AccessController.doPrivileged(Native Method)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.SocketUtils.bind(SocketUtils.java:122)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:199)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:194)
> 10:49:59 [SEVERE] 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
> 10:49:59 [SEVERE] 	... 12 more
> 10:49:59 [INFO] §cAn internal error occurred whilst executing this command, please check the console log for details.
> 10:49:59 [WARNING] Error in dispatching command
> java.util.concurrent.CompletionException: java.net.BindException: Cannot assign requested address
> 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
> 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
> 	at java.util.concurrent.CompletableFuture.biRelay(CompletableFuture.java:1298)
> 	at java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1284)
> 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
> 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
> 	at com.nukkitx.network.util.Bootstraps.lambda$allOf$0(Bootstraps.java:111)
> 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
> 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
> 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
> 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
> 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
> 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
> 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:994)
> 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:553)
> 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
> 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
> 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
> 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
> 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
> 	at org.geysermc.platform.bungeecord.shaded.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
> 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
> 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
> 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
> 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.net.BindException: Cannot assign requested address
> 	at sun.nio.ch.Net.bind0(Native Method)
> 	at sun.nio.ch.Net.bind(Net.java:433)
> 	at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:698)
> 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.SocketUtils$6.run(SocketUtils.java:125)
> 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.SocketUtils$6.run(SocketUtils.java:122)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.SocketUtils.bind(SocketUtils.java:122)
> 	at org.geysermc.platform.bungeecord.shaded.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:199)
> 	at org.geysermc.platform.bungeecord.shaded.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:194)
> 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
> 	... 12 more
> ```

Seeing that you censored your IP here (`[Geyser-BungeeCord] Failed to start Geyser on <ip>:19132`), I'm going to assume that you are using an external IP. Can you modify this to `127.0.0.1` and report back here if the bug still persists?

**Comment by Paul19988** [comment]
Once returning it to an internal IP/ or 0.0.0.0 reloading Geyser does still throw an internal error (if the IP was previously incorrect) however works fine after a restart

**Comment by Eternal-plasma** [comment]
I have this problem also. If I try to connect instead of the IP I gave it trys to connect to 127.0.0.1 insted

**Comment by DoctorMacc** [comment]
I assume this is still an issue with the latest Geyser?

**Comment by RednedEpic** [comment]
Just gave this a test and there are no errors thrown in console. Closing as this appears to no longer be an issue.
