### ISSUE TITLE
Scaffolding does not work correctly

### ISSUE THREAD

**Issue by TheMasterBlaster** [GeyserMC/Geyser#617]
**Describe the bug**

Scaffolding on Bedrock does not work as it should when on my Geyser Standalone server. I can walk into it but holding the jump key makes me slowly jump up it, and holding crouch just causes me to crouch as if I was standing on something like stone. I have even noticed that placing Scaffolding seems kind of off but it might just be me.

**To Reproduce**

1. Place down Scaffolding

2. Try to climb up/down it

3. See it doesn't work as expected

**Expected behavior**

Being able to climb up it or down it as you can on Bedrock Single player or Java

**Screenshots / Videos**

**Server Version**

Paper version git-Paper-282 (MC: 1.15.2)

**Geyser Version**

Geyser standalone version 1.0-SNAPSHOT (git-master-81d3b0e)

**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

**Comment by SinanGentoo** [comment]
I faced the same problem too

**Comment by DoctorMacc** [comment]
This is something we're hoping to tackle when we implement stair/slab fixes.

Technically speaking, we need to send certain scaffolding-relating entity flags when a player is in scaffolding. I have an implementation of this working but it required checking for scaffolding every time the player moves. Perhaps we can only check when the player attempts to jump or sneak.

**Comment by Heath123** [comment]
Will be fixed by #699

**Comment by DoctorMacc** [comment]
This is largely fixed now.
