### ISSUE TITLE
Geyser on Bungeecord doesn't respect forced hosts

### ISSUE THREAD

**Issue by ryan77627** [GeyserMC/Geyser#619]
**Describe the bug**
Geyser running on Bungeecord doesn't respect Forced Hosts

**To Reproduce**
1. Add geyser to bungeecord
1. Define a new forced host
1. Try to connect to it.
1. You get conncted to whatever server the regular domain would connect to.

**Expected behavior**
I would expect Bedrock clients to connect to the forced host server like java players

**Server Version**
 Waterfall version git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344 by md_5

**Geyser Version**
I am not using floodgate, and I am running Geyser version 1.0-SNAPSHOT (git-master-83c7858)

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
Plugins are EssentialsX, Grief Prevention, DynMap, and Chest Shop

**Comment by RednedEpic** [comment]
> **Describe the bug**
> Geyser running on Bungeecord doesn't respect Forced Hosts
> 
> **To Reproduce**
> 
> 1. Add geyser to bungeecord
> 2. Define a new forced host
> 3. Try to connect to it.
> 4. You get conncted to whatever server the regular domain would connect to.
> 
> **Expected behavior**
> I would expect Bedrock clients to connect to the forced host server like java players
> 
> **Server Version**
> Waterfall version git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344 by md_5
> 
> **Geyser Version**
> I am not using floodgate, and I am running Geyser version 1.0-SNAPSHOT (git-master-83c7858)
> 
> **Minecraft: Bedrock Edition Version**
> 1.14.60
> 
> **Additional Context**
> Plugins are EssentialsX, Grief Prevention, DynMap, and Chest Shop

Are you using an SRV record?

**Comment by ryan77627** [comment]
No, should I be? Currently, my setup looks like the following:

CNAME record for subdomain pointing to my domain -> A record for main domain pointing to my IP address -> Connection to subdomain1.example.com in minecraft leads to port 25565/19132 by default -> Bungeecord determines host and connects java players to correct server but not bedrock players.

Hopefully that made sense. If it didn't let me know and why so I can clarify.

**Comment by rtm516** [comment]
Is Geyser using the domain in the config or just IP?

**Comment by ryan77627** [comment]
Using either the IP (In my case 127.0.0.1) or the domain (example.com) give the same motd. It's giving the same motd as if a java player would try to connect using example.com (no subdomain).

**Comment by eve0415** [comment]
This issue also goes with `Velocity`

**Comment by SinonGame** [comment]
The best expection is to detect the domain bedrock player are using and do as the same way of bungeecord's forced host

**Comment by theminecoder** [comment]
As far as I know the bedrock network protocol does not support this functionality at this point. As far as the java server is aware geyser is only ever using the one hostname that's defined in the config, and nothing else. Once the protocol allows for this it will likely become a feature but until then we can only wait.

**Comment by RednedEpic** [comment]
As mentioned above, this appears to be a limitation of the Bedrock protocol in general, so I'm going to close this issue.
