### ISSUE TITLE
Map captcha doesnt work

### ISSUE THREAD

**Issue by KirilCrut** [GeyserMC/Geyser#620]
Map captcha doesnt work
https://youtu.be/GyaByOS5Pxw
(ip:mc.spworlds.ru)

Server version: 1.15.2
Geyser build: 173
Minecraft bedrock version:1.14.60

This bug was in previous versions of geyser

**Comment by DoctorMacc** [comment]
Please follow the issue template. What version is the server on? What build of Geyser are you using?

**Comment by KirilCrut** [comment]
> Please follow the issue template. What version is the server on? What build of Geyser are you using?
Server version: 1.15.2
Geyser build: 173
Minecraft bedrock version:1.14.60

This bug was in previous versions of geyser

**Comment by rtm516** [comment]
Closed in favour of https://github.com/GeyserMC/Geyser/issues/625
