### ISSUE TITLE
Support for v1.15.0.9 (Minecraft RTX) (should be the same of v1.14.6 on the packets side)

### ISSUE THREAD

**Issue by Leonardo-Fiori** [GeyserMC/Geyser#622]
From what i know there is nothing different in version 1.15.0.9 from the currently supported version (v1.14.6) at least on the networking side. It should be based on the bee update, but with differences only in the rendering engine.

Since lots of users like me are on minecraft beta 1.15.0.9 (RTX), it would be cool if you added support for it! (And in addition many users like me are stuck on this version too, due to a bug in the Xbox insiders program)

So IF it's just a matter of allowing a different version number to connect, it would be a nice thing to have. If it requires any additional coding i fully agree that this request should be ignored at least for now! :)

**Comment by jackson-57** [comment]
@lukeeey tried to do this with DragonProxy, there are some differences in the networking stuff.

**Comment by DoctorMacc** [comment]
With 1.16's release being imminent, support for the RTX beta version 1.15. Should the RTX beta update to be on par protocol-wise with 1.16 we will add support. Ideally, an update will come that uses the exact protocol.

**Comment by RednedEpic** [comment]
Appears that RTX support did not make it into 1.16, however this is something that would need to be done over at https://github.com/CloudburstMC/Protocol first before here. Until and if something like that happens, I'm going to close this issue.

**Comment by Frozen-Tofu** [comment]
The new RTX beta 1.16.30.52 is updated to Nether Update.

**Comment by Leonardo-Fiori** [comment]
And I am still stuck on RTX beta 😂 but that's another issue... Microsoft uwp platform is just broken
