### ISSUE TITLE
Map with captcha is not working

### ISSUE THREAD

**Issue by 6789012** [GeyserMC/Geyser#624]
Map with captcha is not working. BotFilter.
![P00412-211047](https://user-images.githubusercontent.com/65409390/82730338-8af70d80-9d07-11ea-87e7-08afec57f5f7.jpg)
A map with a captcha just doesn't appear.
version 1.12.2
build 173
version of minecraft bedrock 1.14.60.5

**Comment by rtm516** [comment]
> Map with captcha is not working. BotFilter.
> ![P00412-211047](https://user-images.githubusercontent.com/65409390/82730338-8af70d80-9d07-11ea-87e7-08afec57f5f7.jpg)
> A map with a captcha just doesn't appear.

Follow the issue template format

**Comment by rtm516** [comment]
Closed in favour of https://github.com/GeyserMC/Geyser/issues/625
