### ISSUE TITLE
Captcha maps dont get displayed

### ISSUE THREAD

**Issue by rtm516** [GeyserMC/Geyser#625]
**Describe the bug**
Captcha maps dont get displayed, they just show invisible

**To Reproduce**
1. Join a server with BotFilter
2. Captcha map is invisible

**Expected behavior**
1. Join a server with BotFilter
2. Captcha map is visible

**Screenshots / Videos**
https://youtu.be/GyaByOS5Pxw (IP: mc.spworlds.ru)
![P00412-211047](https://user-images.githubusercontent.com/65409390/82730338-8af70d80-9d07-11ea-87e7-08afec57f5f7.jpg)

**Server Version**
1.15.2 or 1.12.2 (Doesn't seem to matter)

**Geyser Version**
Build 173

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
The merged issue with the information from https://github.com/GeyserMC/Geyser/issues/620 and https://github.com/GeyserMC/Geyser/issues/624

**Comment by DoctorMacc** [comment]
I believe this is the source for BotFilter: https://github.com/maythiwat/BungeeCord-BotFilter/tree/master/proxy/src/main/java/ru/leymooo/botfilter

**Comment by 6789012** [comment]
?

**Comment by SGE074** [comment]
You can use my mods:
[CursedConnector](https://sgemine.ru/CursedConnector/) 
Allows you to connect you Java-Bot Filter server.
On this site you can find "ShieldProxy" and "CursedConnector".
ShieldProxy — modded Geyser MC project
CursedConnector — modded BotFilter
Connection to this site is not protect, but who cares?
1. Download CursedConnector
2. Delete your Bungee Bot Filter
3. Install CursedConnector
4. Delete your Geyser MC (config, locales, logs, JAR)
5. Install ShieldProxy

If you encounter difficulties write me:
VK - vk.com/raphtalia074
Ask for updates ↑↑↑
