### ISSUE TITLE
Please use your own logo

### ISSUE THREAD

**Issue by Selim042** [GeyserMC/Geyser#63]
https://www.spigotmc.org/resources/geyser-core.58825/

**Comment by EOT3000** [comment]
@RednedEpic

**Comment by LegacyGamerHD** [comment]
@Selim042  your project are dead second of all who cares

**Comment by EOT3000** [comment]
@LegacyGamerHD Selim has been using this for longer than us, and it is still plaigerism, as for @Selim042 I will request the owner to make a new logo. TYSM for telling us

**Comment by AlissonLauffer** [comment]
A friend of mine is thinking of making a new logo for Geyser.

**Comment by RednedEpic** [comment]
> https://www.spigotmc.org/resources/geyser-core.58825/

Your logo came up with a simple Google search with various filters applied so nothing copyrighted showed up. If I remember correctly, I pulled the image off of imgur or one of those photo sharing sites with no link to your resource, so I was completely unaware that you made this. Whether or not you uploaded this or not, we will be changing our logo over the next few days; considering you're using this already for one of your projects and that it's your work.

Thank you for reaching out to us and I apologize for any troubles caused.

**Comment by Selim042** [comment]
No troubles caused, thanks for addressing it though
