### ISSUE TITLE
Standing In Bubble Column Creates Mass Amount Of Incorrect Particles

### ISSUE THREAD

**Issue by Arktisfox** [GeyserMC/Geyser#630]
**Describe the bug**
When standing in an upwards bubble column, there's tons of incorrect black potion effect / potion bottle particles created. 

**To Reproduce**
Create/find an upwards bubble column and stand in it.

**Expected behavior**
The correct water particles should show instead.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/65837019/82745768-14cdc780-9d56-11ea-8c96-a209f309695d.png)
![image](https://user-images.githubusercontent.com/65837019/82745790-4b0b4700-9d56-11ea-97fb-0b052a29da9b.png)

**Server Version**
CraftBukkit version git-Spigot-2040c4c-77fd87e (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
build # 185

**Minecraft: Bedrock Edition Version**
v1.14.60

**Comment by RednedEpic** [comment]
Unable to reproduce. Please update to the latest version of Geyser and see if the issue persists.

**Comment by RednedEpic** [comment]
Nevermind, looks like mappings submodule was set back a commit for some reason. Will fix shortly.
