### ISSUE TITLE
Shields of other creature off-hands cannot be displayed normally

### ISSUE THREAD

**Issue by SinanGentoo** [GeyserMC/Geyser#631]
**Describe the bug**
- As the title

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**
![](https://i.niupic.com/images/2020/05/24/7VYD.jpg)

**Server Version**
Paper b307(1.15.2)

**Geyser Version**
The latest master

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**

**Comment by RednedEpic** [comment]
Seems to only be a problem with zombie pigmen and zombies.

**Comment by OnlyBMan** [comment]
The same bug occurs in Vanilla Bedrock.

**Comment by RednedEpic** [comment]
As this is a bug within the game itself, there is nothing we can really do in that regard. Closing.

**Comment by Sleuth56** [comment]
BTW it's not just pigmen. I had it happen when a Java player holds a shield. To the bedrock player it looks like it goes through their head just like in the photo above.

**Comment by Camotoy** [comment]
That happens on a normal Bedrock server as well. It's a bug introduced in 1.16.210.

**Comment by Sleuth56** [comment]
Well that's fun they should have noticed it in QA. I mean a shield sticking out of someones head is pretty obvious. Thanks for the clarification. I was clearing up that it's not just pigmen.
