### ISSUE TITLE
Chat made with TextComponent does not show up in chat

### ISSUE THREAD

**Issue by maxw2000** [GeyserMC/Geyser#634]
**Describe the bug**
When you try to send a message in chat with TextComponent it does not show up in chat
It only shows up on java

**To Reproduce**
Install a plugin that uses TextComponent to send chats.
chat.

**Expected behavior**
Chat will show up on Bedrock and Java

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/22998325/82747783-e1625b80-9d9c-11ea-9dbb-b0c7ef3eee51.png)

**Server Version**

![image](https://user-images.githubusercontent.com/22998325/82747793-ff2fc080-9d9c-11ea-9df6-7662af61226b.png)

**Geyser Version**

Master build 188

**Minecraft: Bedrock Edition Version**

V 1.14.60

**Additional Context**

I use my own plugin to handle chat, here is the code I use to make it:
![image](https://user-images.githubusercontent.com/22998325/82747848-7cf3cc00-9d9d-11ea-8bc7-c7cf4e239ec7.png)

**Comment by james090500** [comment]
Works fine for me. Update Geyser, also I highly recommend you update Paper as well...

![image](https://user-images.githubusercontent.com/20372645/82761645-f6b6a480-9df3-11ea-9cf0-9d68f284280e.png)

**Comment by maxw2000** [comment]
I am dumb, I was testing this code a while back but never finished it(I forgot to send it to all players)
Sorry that I wasted time.
