### ISSUE TITLE
Hand disappears in some places of the world

### ISSUE THREAD

**Issue by towuk118** [GeyserMC/Geyser#635]
**Describe the bug**
Sometimes in some places on the player's hand disappears, there is no such problem on items!

**To Reproduce**
Just create a world and walk in it, in some biomes or places the hand will start to disappear

**Expected behavior**
Not have

**Screenshots / Videos**
Video: https://streamable.com/1eshmh

**Server Version**
This server is running CraftBukkit version git-Spigot-2f5d615-d07a78b (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
For Bukkit #188 (24 мая 2020 г., 6:45:56)

**Minecraft: Bedrock Edition Version**
Win10Ed | 1.14.60

**Additional Context**
Discord link: `TOWUK | YouTube ✅#7761`

**Comment by DoctorMacc** [comment]
I'm able to confirm this but I think it's a client bug. No metadata is changed, nor is a game mode updated.

**Comment by E404NNF** [comment]
Able to confirm it too, happens only on windows 10 edition

**Comment by DoctorMacc** [comment]
Was also able to encounter it in Xbox and desktop Android.

**Comment by E404NNF** [comment]
I wasn't able to reproduce on Android, only was able to do on windows 10

**Comment by DoctorMacc** [comment]
The place where I was able to replicate this no longer exhibits the bug. Closing.
