### ISSUE TITLE
New versions not working with Velocity

### ISSUE THREAD

**Issue by mpztilera** [GeyserMC/Geyser#637]
**Describe the bug**
Geyser is not working with Velocity anymore. With the version from April 23 everything worked fine, but now I have updated Geyser and when I try to join and login with my MC account, after that I only stand in an empty world. The Geyser console shows, that I am connected, but the Velocity console just says nothing. After a few seconds, I get disconnected and the Geyser cosole says, that it is a timeout and the Velocity console now shows, that I have disconnected. I testet it with standalone Geyser and the Geyser plugin for Velocity, but both fails.

**To Reproduce**
1. Install Velocity and Geyser
2. Set Geyser to online mode and let it point to the port of Velocity
3. Try to join on Geyser

**Expected behavior**
I should normally join on the Server, like before the update.

**Screenshots / Videos**
http://leyt.xyz/geyser/geysererror.PNG
http://leyt.xyz/geyser/velocityerror.PNG

**Server Version**
1.0.8

**Geyser Version**
Build 188

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by mpztilera** [comment]
Has anyone an idea?

**Comment by mpztilera** [comment]
With Bungeecord everything works fine, so it is a problem specifically with Velocity

**Comment by DoctorMacc** [comment]
Update to Velocity 1.1.0-SNAPSHOT?

**Comment by mpztilera** [comment]
I can only find the 1.0.8-SNAPSHOT. From which source you have 1.1.0-SNAPSHOT?

**Comment by rtm516** [comment]
> I can only find the 1.0.8-SNAPSHOT. From which source you have 1.1.0-SNAPSHOT?

https://ci.velocitypowered.com/job/velocity-1.1.0/

**Comment by mpztilera** [comment]
Oh, thank you, I will try this

**Comment by mpztilera** [comment]
Thank you, it worked
