### ISSUE TITLE
Decoder Exception

### ISSUE THREAD

**Issue by OnlyBMan** [GeyserMC/Geyser#64]
I updated to the latest commit on the master branch and whenever I log in with PE, I get 

> io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value minecraft:nbt_compound_tag has no mapping for key class com.github.steveice10.mc.protocol.data.game.command.CommandParser.

**Comment by RednedEpic** [comment]
> I updated to the latest commit on the master branch and whenever I log in with PE, I get
> 
> > io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Value minecraft:nbt_compound_tag has no mapping for key class com.github.steveice10.mc.protocol.data.game.command.CommandParser.

What server are you trying to join, just out of curiosity?

**Comment by OnlyBMan** [comment]
Just a private world I'm running on my host

**Comment by lukeeey** [comment]
Report it on the MCProtocolLib repo

**Comment by Seamusmario** [comment]
this is a MCProtocolLib issue,  not geyser, report there instead.

**Comment by RednedEpic** [comment]
> this is a MCProtocolLib issue, not a geyser issue, report there instead.

One is already opened there.

**Comment by Seamusmario** [comment]
oops

**Comment by lukeeey** [comment]
Whenever i have an issue i just open it there and he usually fixes it fairly quickly

**Comment by RednedEpic** [comment]
Resolved in Steveice10/MCProtocolLib#496.
