### ISSUE TITLE
When a java player walks on glass it makes the wrong sound(splash potion sound effect)

### ISSUE THREAD

**Issue by maxw2000** [GeyserMC/Geyser#641]
**Describe the bug**

When a java player walks on glass, the bedrock player hears the wrong sound.

**To Reproduce**
Let a java player walk on glass

**Expected behavior**

It should make the correct sound.

**Screenshots / Videos**

https://youtu.be/FOvVQUcxBiI

**Server Version**

![image](https://user-images.githubusercontent.com/22998325/82757697-789dd200-9de2-11ea-9a64-241f63b62035.png)

**Geyser Version**

master build 188

**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

**Comment by RednedEpic** [comment]
Unable to reproduce. Try updating your Paper version as you are 85 builds out of date. Unsure if this will fix it on your end, but regardless give it a try and let us know of the result.

**Comment by maxw2000** [comment]
I've updated paper + waterfall to the latest build, I still have the same issue.

**Comment by RednedEpic** [comment]
Can you try without plugins?

**Comment by maxw2000** [comment]
I found the issue, It was ProtocolSupport. I never noticed that. Thank you for your help.
