### ISSUE TITLE
Players are able to place blocks in Y axis while they are on a block

### ISSUE THREAD

**Issue by E404NNF** [GeyserMC/Geyser#646]
**Describe the bug**

Players are able to place blocks in Y axis while they are on a block
**To Reproduce**

1. Place a block in Y axis while you are on a block
**Expected behavior**

Players not able to place blocks in Y axis while they are on a block
**Screenshots / Videos**

https://cdn.discordapp.com/attachments/613163671870242842/714190777193988192/2020-05-24_20-57-19.mp4
Screenshot(s) from java: 1: https://prnt.sc/smywp4 2: https://prnt.sc/smyydi
**Server Version**

git-PaperSpigot-"4c7641d" (MC: 1.8.8
**Geyser Version**

Geyser-Bungeecord #183
**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by toinouH** [comment]
@E404NNF Does this bug still exist?

**Comment by E404NNF** [comment]
Idk

**Comment by RednedEpic** [comment]
Seems to have been resolved by movement fixes.
