### ISSUE TITLE
Boats show both players in the same spot

### ISSUE THREAD

**Issue by TheMasterBlaster** [GeyserMC/Geyser#647]
**Describe the bug**

When in a boat, if a player gets in the boat with you they show as in the front spot with you.

**To Reproduce**

1. Get in a boat
2. Have another player get in the boat
3. See that both players show as in the front spot

**Expected behavior**

Second player shows up in the second seat.

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/9083212/82764956-d16c6b00-9de0-11ea-88fe-2988cebd27a5.png)

**Server Version**

Paper version git-Paper-282 (MC: 1.15.2)

**Geyser Version**

Geyser Standalone version 1.0-SNAPSHOT (git-master-7154e1c)

**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

**Comment by DoctorMacc** [comment]
I saw this extend to not just players but mobs as well.

**Comment by rtm516** [comment]
There is an extra packet sent by BDS that sets the seat positions when someone gets in iirc
