### ISSUE TITLE
Another firework nullptr (still!)

### ISSUE THREAD

**Issue by sowhatifimlazy** [GeyserMC/Geyser#648]
**Describe the bug**
Some firework's just don't show up on Bedrock clients and throws this error in the Geyser console:
https://hasteb.in/welaziba.rb

**To Reproduce**
Create a firework w/ this code:
https://hasteb.in/iyuyofoz.coffeescript

**Expected behavior**
Firework should appear.

**Screenshots / Videos**
Not needed, the firework just doesn't appear on Bedrock clients.

**Server Version**
Tuinity version git-Tuinity-"973b5c7" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
Geyser version 1.0-SNAPSHOT (git-master-7154e1c)

**Minecraft: Bedrock Edition Version**
iOS v1.14.60

**Additional Context**
n/a

**Comment by rtm516** [comment]
These fireworks display as expected on java edition right?

**Comment by rtm516** [comment]
And mind sharing the IP where this occuring so we can test any fixes and do some more debugging as that line shouldn't error and adding and NPE check would cause there to be no effect

**Comment by sowhatifimlazy** [comment]
Yes, https://i.imgur.com/KmMQX4d.png

**Comment by sowhatifimlazy** [comment]
Sure, pe.quad.gg is the Geyser proxy, and quad.gg is the remote Java server.

**Comment by rtm516** [comment]
@sowhatifimlazy Awesome I'll do some debugging in a bit, incase I need it what's your discord handle?

**Comment by sowhatifimlazy** [comment]
$$$#2959
