### ISSUE TITLE
Curse of binding pumpkin bugs

### ISSUE THREAD

**Issue by EasyClifton** [GeyserMC/Geyser#649]
**Describe the bug**

The enchantment glare is not displayed on an enchanted pumpkin.

If you try to remove a curse of binding pumpkin from your head in survival mode and put it into your inventory, the pumpkin will immediately go back on your head but also a fake pumpkin will stay in your inventory. It will disappear if the inventory is updated.

If you try to throw the pumpkin out of your inventory **directly** from the head it will visually disappear but still stay there server-side. If you then try to put something else onto your head the pumpkin will reappear and the item you were trying to put on will "bug out" and you will not be able to put it into your inventory until you throw it out.

**To Reproduce**

1. Get yourself a curse of binding pumpkin.
2. The enchntment glare is not displayed on the pumpkin.
3. Put it on your head and go into survival mode.
4. See the errors.

**Expected behavior**

The enchantment glare should display properly.
The pumpkin should always return on my head, no matter what I do with it.

**Screenshots / Videos**

https://streamable.com/o9puq5

**Server Version**

This server is running Paper version git-Paper-313 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**

Geyser-bukkit, version #647 196

**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

Plugins (10): Essentials, EssentialsChat, EssentialsSpawn, Geyser-Bukkit, JukeBox, LuckPerms, Multiverse-Core, NoteBlockAPI, Vault, WorldEdit (yea, a bunch of random plugins but that's a test server)

**Comment by rtm516** [comment]
This happens with any item that has the `Curse of Binding` or `Curse of Vanishing`, by the looks of it these aren't implemented fully yet in Bedrock causing the item to not be converted back properly, therefore, the java server refuses to move the item.

**Comment by EasyClifton** [comment]
They will be in 1.16 but you probably already knew this.

**Comment by DoctorMacc** [comment]
I believe we can fix this in 1.16.
