### ISSUE TITLE
Hologram bold text formatting issues

### ISSUE THREAD

**Issue by sowhatifimlazy** [GeyserMC/Geyser#651]
**Describe the bug**
If a hologram contains bold text, all text after the bold text will be bold even if it is not supposed to be bold.

**To Reproduce**
1): Download HolographicDisplays
2): Create a hologram with /hd create test_holo
3): Set the hologram's text with /hd setline test_holo 1 &6&lSome bold text &6some non-bold text

**Expected behavior**
Text shouldn't be bold if reset.

**Screenshots / Videos**
Java: https://i.imgur.com/PiJwHWi.png
Bedrock: https://i.imgur.com/n7ALo59.png

**Server Version**
https://i.imgur.com/uH6yOiE.png

**Geyser Version**
Geyser version 1.0-SNAPSHOT (git-master-7154e1c)

**Minecraft: Bedrock Edition Version**
iOS v1.14.60

**Additional Context**
n/a

**Comment by sowhatifimlazy** [comment]
Update: Seems to happen in chat messages sometimes as well...

Java: https://i.imgur.com/xaROQrV.png
Bedrock: https://i.imgur.com/itHwrmn.png

**Comment by rtm516** [comment]
A likely fix to this is to pass armour stand names through the same function as chat messages

**Comment by DoctorMacc** [comment]
This should be fixed by now. Let us know if it's not!
