### ISSUE TITLE
Chat message bold text formatting

### ISSUE THREAD

**Issue by sowhatifimlazy** [GeyserMC/Geyser#652]
**Describe the bug**
If a rank prefix contains bold text, all text after the bold text will be bold even if it is not supposed to be bold.

**To Reproduce**
1): Use DeluxeChat (a paid plugin) for chat formatting.
2): Set group prefix to "&9[&9&lDEVELOPER&9] "

**Expected behavior**
Text shouldn't be bold if reset.

**Screenshots / Videos**
Java: https://i.imgur.com/xaROQrV.png
Bedrock: https://i.imgur.com/itHwrmn.png

**Server Version**
https://i.imgur.com/uH6yOiE.png

**Geyser Version**
Geyser version 1.0-SNAPSHOT (git-master-7154e1c)

**Minecraft: Bedrock Edition Version**
iOS v1.14.60

**Additional Context**
n/a

**Comment by SkedgyEdgy** [comment]
Ye, I think I know why this happens, 'cause in Java color codes reset formatting while Bedrock doesn't do that.

There could probably just be something in place to put §r in front of every color code or something like that.

**Comment by DoctorMacc** [comment]
This should be fixed by now. Let us know if it's not!
