### ISSUE TITLE
Capes seem to "glitch" at random

### ISSUE THREAD

**Issue by TheMasterBlaster** [GeyserMC/Geyser#659]
UPDATED!

**Describe the bug**

I have noticed an issue with players Elytra capes today. It seems Elytra capes have a glitch where they can randomly "mix up". I have an Optifine cape as well as the same cape on MinecraftCapes, and a friend on Java has a Banner Optifine Elytra cape but I noticed for whatever reason I had his Elytra cape. and later on I noticed alot of people without a cape (so they said) had my Elytra cape. From what I have seen it will even flip between multiple Elytra capes.

**To Reproduce**

1. Join Server Via Bedrock

2. Join Server Via Java

3. TP to Bedrock Player

4. Possibly see the Elytra capes mess up.

**Expected behavior**

Capes to not glitch out / mix up.

**Screenshots / Videos**

How my cape is meant to look.
![image](https://user-images.githubusercontent.com/9083212/82846681-131c1500-9eb8-11ea-8ba6-0f111c5c5c34.png)

How my friends cape looks.
![image](https://user-images.githubusercontent.com/9083212/82846726-4d85b200-9eb8-11ea-8e52-37c3916864a2.png)

After random glitch/mix up happends.
![image](https://user-images.githubusercontent.com/9083212/82846761-71e18e80-9eb8-11ea-9831-fc76578b82b9.png)

**Server Version**

Paper version git-Paper-282 (MC: 1.15.2)

**Geyser Version**

Geyser Standalone version 1.0-SNAPSHOT (git-master-6b68bbb)

**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

I dont understand how to reproduce this issue. I have randomly noticed it today.

**Comment by DoctorMacc** [comment]
Any update on this issue?

**Comment by TheMasterBlaster** [comment]
![image](https://user-images.githubusercontent.com/9083212/93865760-c2190380-fc94-11ea-8c4b-6a767ba252cc.png)
Still happen for Bedrock users. No one with an Optifine cape so I used NPCs

**Comment by RednedEpic** [comment]
Not seen this reported in a long time + we had some issues with Citizens in the past with capes. Feel free to comment here if this is still an issue, but regardless, thanks for the report.
