### ISSUE TITLE
End Crystals cannot be punched on bedrock

### ISSUE THREAD

**Issue by Nithindanday** [GeyserMC/Geyser#668]
**Describe the bug**

Hitting an end crystal won't make it explode on bedrock. You can use a bow, but hitting it wont make it explode.
**To Reproduce**

Place End Crystal on bedrock or obsidian
Punch it on bedrock
It doesn't explode

**Expected behavior**

It should explode and do damage, this will happen if you bow it on bedrock or punch it on java.
**Screenshots / Videos**

https://youtu.be/enmhxxqyjws
**Server Version**

This server is running Paper version git-Paper-280 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-Snapshot)
**Geyser Version**

git-master-14fcd77
**Minecraft: Bedrock Edition Version**

Windows 10 Edition
**Additional Context**

Geyser on Paper with Floodgate.

**Comment by chenxi050402** [comment]
It works when you punch from the top but no other directions

**Comment by rtm516** [comment]
Please can you test https://github.com/GeyserMC/Geyser/pull/716 for me
