### ISSUE TITLE
Fix metrics

### ISSUE THREAD

**Issue by TRose2000** [GeyserMC/Geyser#671]
**Describe the bug**
random warning about metrics (org.geysermc.connector.metrics.Metrics)

**Screenshots / Videos**
https://gyazo.com/120f32a31741d54070a99c776e785f73

**Server Version**
git-Purpur-581 (MC: 1.15.2)

**Geyser Version**
198

**Comment by DoctorMacc** [comment]
This was brought up in the Paper Discord, so I'm copying what was said there.

> zzzCat: The issue is that you're still sharing classes, you just prefer your own classloader, which creates some headaches in some oddball states
> A248: whoever did the pom stuff just needs to relocate jackson just like you did for packaged versions of netty and fastutil
