### ISSUE TITLE
Player's move on their screen but are stuck in place on the server

### ISSUE THREAD

**Issue by sowhatifimlazy** [GeyserMC/Geyser#673]
**Describe the bug**
When players switch servers from the lobby, they join the server just fine and are able to move around on their screen, but the server and Java players just see them standing still w/ sprinting particles under their feet.

**To Reproduce**
Not sure, it happens sometimes and sometimes it doesn't happen. Happens most of the time you switch servers though.

If it changes anything, we're using Velocity, not BungeeCord. Velocity can be found at https://github.com/VelocityPowered/Velocity

**Expected behavior**
A player should obviously be able to move around after switching servers.

**Screenshots / Videos**
n/a

**Server Version**
https://i.imgur.com/uH6yOiE.png

**Geyser Version**
Geyser version 1.0-SNAPSHOT (git-master-14fcd77)

**Minecraft: Bedrock Edition Version**
iOS v1.14.60

**Additional Context**
n/a

**Comment by alex11441** [comment]
Running Floodgate, Velocity, and standalone Geyser, bug still occurs

**Comment by DoctorMacc** [comment]
Might be the same thing as #576.

**Comment by alex11441** [comment]
It seems this only happens on first login to a server.

**Comment by PotatoesDuck** [comment]
I can confirm I get this issue as well. It happens sometimes though and gets fixed after the bedrock player TPs anywhere.

**Comment by Trains77** [comment]
Yeah I had that to and it seems like the only real solution is to simply have the bedrock player relog,
after that they move just fine, at least for me that is

**Comment by RednedEpic** [comment]
Has this issue occurred lately?

**Comment by sowhatifimlazy** [comment]
I'm unable to confirm/deny if this issue still occurs as we've dropped our Geyser proxy.

**Comment by Camotoy** [comment]
I suspect that the recent dimension fixes have fixed this issue.
