### ISSUE TITLE
GeyserMC Native Plugin Support

### ISSUE THREAD

**Issue by bundabrg** [GeyserMC/Geyser#676]
**What feature do you want?**
Add the ability to support compiled plugins for GeyserMC itself.

It would require:
  * A lightweight event system
  * Events for each packet (or a single event covering them all) both directions plus the ability to modify the packet or cancel it entirely
  * Able to register commands, so an event right after initialization is required
  * Some place to list useful plugins

Features:
  * Allows pulling out hacks from the main code to a plugin. For example one could have a plugin to filter playerlist packets containing certain keywords
  * Another useful plugin could be one that interfaces with bungeecord/spigot/velocity etc and can provide access to realtime data that would otherwise need caching but without requiring everyone run it.

**Comment by DoctorMacc** [comment]
We've had this request several times before; I think the main thread was #542. I'm going to close this and reopen that one.
