### ISSUE TITLE
Support the PROXY protocol

### ISSUE THREAD

**Issue by bundabrg** [GeyserMC/Geyser#677]
**What feature do you want?**

GeyserMC should support the [PROXY Protocol](https://www.haproxy.com/blog/haproxy/proxy-protocol/) both upstream and downstream.

Features:
  * Allows GeyerMC itself it run behind a proxy (like haproxy) and retain IP forwarding.
  * For downstream servers that support it (Bungeecord does) it allows passing IP forwarding on without needing additional plugins.

**Comment by DoctorMacc** [comment]
Is this possible for UDP?

**Comment by bundabrg** [comment]
Whoops totally forgot and it might not. However worth it maybe on the downstream side then. Still researching it.

**Comment by bundabrg** [comment]
Apparently UDP is also covered, TIL. Here's a link to the spec: 

https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

**Comment by rtm516** [comment]
Don't think it would be UDP as it it would be added over the TCP connection to the Java server?

**Comment by bundabrg** [comment]
It could be both sides but I'm mainly interested in the java side so tcp.

**Comment by applebee1558** [comment]
It would be very useful if this could be implemented as, I cannot connect to my geyser server from the outside, which is nginx forwarding UDP traffic to my server through a vpn tunnel (yes nginx stream udp, not nginx http server). Pings work and the MOTD shows, but connections end up failing. It just keeps saying "[IP] tried to connect!"

**Comment by amcmanu3** [comment]
I'm also interested in this being implemented. I have everything behind an nginx proxy and I can't really use Geyser as a solution until this is implemented.

**Comment by Camotoy** [comment]
This is possible downstream (Geyser -> PROXY-protocol-accepting server) thanks to Mikroskeem, and PROXY-protocol-server -> Geyser will be available later.

**Comment by Camotoy** [comment]
Downstream was implemented in #1688; upstream was implemented in #1713.
