### ISSUE TITLE
Command suggestions default setting

### ISSUE THREAD

**Issue by Elapy** [GeyserMC/Geyser#687]
**What feature do you want?**
It's not a feature lol. I'm just suggesting command suggestions to be set to false in geyser config on default, so people don't have to change it to stop it from freezing.

**Alternatives?**
Well, it's not a feature, so yea

**Comment by Heath123** [comment]
Most servers don't freeze with command suggestions though

**Comment by Heath123** [comment]
It's just if you have A LOT of plugins and commands

**Comment by LegacyGamerHD** [comment]
like my server tbh

**Comment by DoctorMacc** [comment]
If you're running a vanilla Minecraft server, you are fine (one of the reasons I set it to be enabled by default). But as soon as you put in Essentials (a common plugin) it can freeze. I'm fine with keeping this issue up for discussion as I'm not set on keeping it as true by default.

**Comment by Elapy** [comment]
Oh ok thanks :)

**Comment by DoctorMacc** [comment]
Closing this issue, as with 1.16.100 command freezing still exists but crashing appears to be gone, entirely reducing the need for this to be a feature request. :)
