### ISSUE TITLE
Java servers with double jump allow flight

### ISSUE THREAD

**Issue by HazardTheDutchAD** [GeyserMC/Geyser#690]
**Describe the bug**
When connected to the CubeCraft server, and you have Plus rank, you can fly without :Emerald: rank. I think the flying system and the double jump system are connected together.

**To Reproduce**
Connect to a GeyserMC proxy that connects to CubeCraft Games (or any Java server with double jump)
Add the Plus subscription rank onto your account
Go to your lobby settings and enable double jump
Tap on the jump button twice and it will enable flight.

**Expected behavior**
You should be able to double jump around the lobby

**Screenshots / Videos**
https://www.youtube.com/watch?v=p_a5xzuX6ww

**Server Version**
Unsure. Please can a CubeCraft staff member add this?

**Geyser Version**
N/A Unsure how to check the version. I will attach the file instead. 

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
This might cause players to get reported on accident and be banned by a moderator.

**Comment by HazardTheDutchAD** [comment]
[geyser_for_bug_report.zip](https://github.com/GeyserMC/Geyser/files/4701993/geyser_for_bug_report.zip)

**Comment by DoctorMacc** [comment]
This probably isn't tied to anything with double jump but us translating permissions incorrectly. E.G. Java tells us we can double jump but Bedrock interprets that as an OK to fly.

Is there a way one of the Geyser developers can test and debug this?

**Comment by HazardTheDutchAD** [comment]
> This probably isn't tied to anything with double jump but us translating permissions incorrectly. E.G. Java tells us we can double jump but Bedrock interprets that as an OK to fly.
> 
> Is there a way one of the Geyser developers can test and debug this?

I doubt many CubeCraft players would be using a GeyserMC proxy to connect at this time, but I thought this is something important to report as it allows an Emerald and Obsidian perk by just purchasing a subscription rank.
