### ISSUE TITLE
Spectator mode players are invisible and still hold items

### ISSUE THREAD

**Issue by rtm516** [GeyserMC/Geyser#698]
**Describe the bug**
When a player enters spectator mode holding an item, a bedrock player (also in spectator) cant see them at all (not even a head) apart from the item they where holding.

**To Reproduce**
1. Hold an item
2. Go into spectator
3. View from a bedrock client in spectator mode

**Expected behavior**
There is a floating head with nametag and no held item. (like in Java)

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/5401186/83329108-60fd9800-a27f-11ea-9fec-da8efc02c34d.png)

**Server Version**
Paper version git-Paper-313 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
Master as of https://github.com/GeyserMC/Geyser/commit/14fcd77925f2246ad5e526038d21a521c141dd8d

**Minecraft: Bedrock Edition Version**
Win10 1.14.60

**Additional Context**
Might not be something we can fix, or maybe something that will fix itself if spectator mode is in bedrock 1.16

**Comment by RednedEpic** [comment]
Closing in favor of #915.
