### ISSUE TITLE
Version support

### ISSUE THREAD

**Issue by DeeRenjie** [GeyserMC/Geyser#70]
Hope to add 1.13.0 support to bedrock, come on!
希望对基岩版增加1.13.0版本支持，加油！

**Comment by alissonlauffer** [comment]
We need to wait for [NukkitX](https://github.com/NukkitX/Protocol) to implement its protocol first.

**Comment by DeeRenjie** [comment]
It's great to be able to support both old and new versions
能够同时支持旧版本与新版本加入就太棒了

**Comment by SupremeMortal** [comment]
I'm almost there with the protocol. Many changes this time around and we had to wait for release due to no symbols in client betas.

**Comment by EOT3000** [comment]
release has symbols?

**Comment by Tim203** [comment]
Yes. The BDS has symbols, not the client.

**Comment by EOT3000** [comment]
ah

**Comment by RednedEpic** [comment]
You can test out 1.13 version support in the `feature/1.13` branch.

**Comment by RednedEpic** [comment]
Geyser now supports 1.13.
