### ISSUE TITLE
Wooden CARDS and floating characters cannot be displayed properly

### ISSUE THREAD

**Issue by pbs666** [GeyserMC/Geyser#701]
Bedrock edition players cannot see wooden signs, or sometimes floating characters
I think maybe it's because I forgot to refresh the wooden board and float the empty characters. Maybe it's an oversight?
hope it will be fixed soon...

**Comment by RednedEpic** [comment]
> Bedrock edition players cannot see wooden signs, or sometimes floating characters
> I think maybe it's because I forgot to refresh the wooden board and float the empty characters. Maybe it's an oversight?
> hope it will be fixed soon...

Please follow the issue template. This is also likely a duplicate of #603 but we need more information (see issue template).

**Comment by RednedEpic** [comment]
Closing for the time being as this seems likely to be a duplicate of #603. If this is not the case, please provide more information about your problem.
