### ISSUE TITLE
Use sub-titles (not audio subtitles) for attack cooldown

### ISSUE THREAD

**Issue by E404NNF** [GeyserMC/Geyser#703]
**What feature do you want?**
Since there is no way to implement the cooldown easily, what just about using subtitles like how ViaRewind does? 

**Alternatives?**
nothing

**Comment by Heath123** [comment]
That sounds like a good idea

**Comment by DoctorMacc** [comment]
Do subtitles exist in Bedrock? Unless you mean the message above the hotbar.

**Comment by E404NNF** [comment]
yeah they do exist if i remember correctly, i will try

**Comment by E404NNF** [comment]
![image](https://user-images.githubusercontent.com/37207067/83332751-34587900-a29d-11ea-8c87-a04590b9f8b4.png)
yep they exist!

**Comment by Heath123** [comment]
> ![image](https://user-images.githubusercontent.com/37207067/83332751-34587900-a29d-11ea-8c87-a04590b9f8b4.png)
> yep they exist!

That's not a subtitle, that's a normal title

**Comment by Heath123** [comment]
These are subtitles
https://minecraft.gamepedia.com/Subtitles
But yes, it should be possible like that

**Comment by E404NNF** [comment]
> /titleraw @a subtitle {"rawtext":[{"text":"hey"}]}
these are called subtitles

**Comment by Heath123** [comment]
True
Anyway, whatever they're called that's possible (a hotbar message might be better though? Maybe there could be a setting?)

**Comment by E404NNF** [comment]
![image](https://user-images.githubusercontent.com/37207067/83332885-fc056a80-a29d-11ea-905e-c7adfca130b0.png)
well, they exist too, an option for it will be good, choosing subtitle or actionbar
