### ISSUE TITLE
Players cannot open the enchantment table interface

### ISSUE THREAD

**Issue by iBumpy** [GeyserMC/Geyser#705]
**Describe the bug**
Players cannot open the enchantment table interface

**To Reproduce**
1. I'm just trying to use the enchantment table

**Expected behavior**
That players can enchant

**Server Version**
This server is running Paper version git-Paper-313 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
Geyser-Bukkit version 1.0-SNAPSHOT 14fcd77

**Minecraft: Bedrock Edition Version**
Android 1.14.60

**Comment by DoctorMacc** [comment]
This is a known issue and will likely not be fixed before 1.16

**Comment by RednedEpic** [comment]
Already listed in readme as unimplemented. Won’t be until 1.16.
