### ISSUE TITLE
Items which are wearable can't be weared

### ISSUE THREAD

**Issue by SinonGame** [GeyserMC/Geyser#706]
**Describe the bug**

Items that can be weared in java edition can't be weared in bedrock edition
(Similar to offhand according to Camotoy)
**To Reproduce**

1. Get a plugin that add a block wearable
2. try to wear it on bedrock edition
3. see error

**Expected behavior**

Items can be weared as usual
**Screenshots / Videos**

[bedrock side](https://streamable.com/de87m6)
[java side](https://streamable.com/sm2wmh)
**Server Version**

Paper version git-Paper-322
**Geyser Version**

Inventory fix pull request build

**Minecraft: Bedrock Edition Version**

1.14.6
**Additional Context**

**Comment by AnonAlpha** [comment]
I think rtm have an idea to use an anvil formate GUI to replace the vanilla GUI, 5 slot for four armor and offhand

**Comment by RednedEpic** [comment]
Closing as this is a Bedrock limitation, not much we can do here.
