### ISSUE TITLE
Sitting using Armor Stands seems incorrect

### ISSUE THREAD

**Issue by TheMasterBlaster** [GeyserMC/Geyser#709]
**Describe the bug**

CMI gives players the ability to sit on Stabs and Stairs, but Geyser(Standalone) seems to have you too low. I have pictures showing how it looks for Bedrock clients,

**To Reproduce**

1. Sit using a plugin like CMI on Stairs or Slabs

2. See that your inside the ground/floor

**Expected behavior**

Sit/see in/from the same location as Java

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/9083212/83360888-b9ea3080-a352-11ea-9938-eb34c6ca366f.png)

**Server Version**

Paper version git-Paper-325 (MC: 1.15.2)

**Geyser Version**

Geyser Standalone version 1.0-SNAPSHOT (git-master-b8a3009)

**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

I have had this issues for awhile.

**Comment by E404NNF** [comment]
i have that problem too

**Comment by DoctorMacc** [comment]
Redned updated the armor offset while mounting, but to match with the GSit plugin.

**Comment by E404NNF** [comment]
Which PR? (If it's one)

**Comment by DoctorMacc** [comment]
https://github.com/GeyserMC/Geyser/commit/681cbeeae5d47bd37e72c067deb546cb858bf539

**Comment by E404NNF** [comment]
I'm using the build 205 (if I remember correctly) on my friend's server that has BetterChairs, that commit doesn't seem to fix it since it was build 185

**Comment by DoctorMacc** [comment]
Likely different plugin mechanics.

**Comment by E404NNF** [comment]
The issue mentioned CMI which is a paid plugin, so ofc you can't see the source, however BetterChairs is open sourced, you can look at the source code, perhaps fixing it with that plugin will fix the plugin in the issue 

BC sourcecode: https://github.com/BlackScarx/BetterChairs

**Comment by HelveticaToast** [comment]
Still an issue:
This server is running Geyser version 1.1.0 (git-master-dfba278) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)23.10 23:26:25 [Server] INFO This server is running Paper version git-Paper-246 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
latest version of gsit
