### ISSUE TITLE
Bedrock 1.13 branch missing dependency

### ISSUE THREAD

**Issue by ApertureDevelopment** [GeyserMC/Geyser#71]
I tried to manually compile the 1.13 branch and noticed that the referenced NukkitX-Protocol dependency is non-existant on the maven repository. ( https://repo.nukkitx.com/maven-snapshots/com/nukkitx/protocol/ )

```xml
<dependency>
    <groupId>com.nukkitx.protocol</groupId>
    <artifactId>bedrock-v388</artifactId>
    <version>2.4.0-SNAPSHOT</version>
    <scope>compile</scope>
</dependency>
```

**Comment by RednedEpic** [comment]
> I tried to manually compile the 1.13 branch and noticed that the referenced NukkitX-Protocol dependency is non-existant on the maven repository. ( https://repo.nukkitx.com/maven-snapshots/com/nukkitx/protocol/ )
> 
> ```
> <dependency>
>     <groupId>com.nukkitx.protocol</groupId>
>     <artifactId>bedrock-v388</artifactId>
>     <version>2.4.0-SNAPSHOT</version>
>     <scope>compile</scope>
> </dependency>
> ```

You have to manually build the protocol library using `mvn clean install` so it’s added to your local repo then attempt to build the 1.13 branch.

I will point out that the 1.13 branch is not yet functional if you intend to try and use it.
