### ISSUE TITLE
Supportquestions

### ISSUE THREAD

**Issue by MuschelBoss** [GeyserMC/Geyser#718]
When does it come to the support for Minecraft Forge/mods?

Do you have a discord server or something like that? 

Does it come to support for older/newer versions?

Do you have to be logged in with your Microsoft account in your Windows or just with your Microsoft account in your Minecraft?

I would appreciate it when you answer me. I know that's a lot of questions, but I would be happy if you answer me.
Greetings Thilo

**Comment by DoctorMacc** [comment]
For all future questions, and to answer your second question, our Discord is https://discord.geysermc.org.

No client-side Forge support, but serverside-only mods may work.

You need to be logged in with your Xbox account on Minecraft.
