### ISSUE TITLE
XBL Authentication is not enforced

### ISSUE THREAD

**Issue by am714** [GeyserMC/Geyser#719]
**Describe the bug**
Xbox Live Authentication is not checked when joining Geyser.

**To Reproduce**
- Add anyone's Geyser proxy to your server list;
- Wait it to ping;
- Click edit and then delete it;
- The server will appear in the friends menu and you will be able to join without being authenticated (This should also work of you join directly from the friends menu on a LAN hosted Geyser)

**Expected behavior**
Being kicked for not being authenticated

**Screenshots / Videos**
https://youtu.be/G5luEmXNQZM

**Server Version**
In this case I am using standalone connecting to Mineplex

**Geyser Version**
Build #213 

**Minecraft: Bedrock Edition Version**
1.14.60 (Android) 

**Additional Context**
This could lead to account stealing.

**Comment by DoctorMacc** [comment]
This is not an issue with Floodgate.

**Comment by Heath123** [comment]
This should have been fixed by https://github.com/GeyserMC/Geyser/commit/e2a956692620dd09dc46afe9c0774bb26c4fc3ca
