### ISSUE TITLE
Invisible Chests On Relog

### ISSUE THREAD

**Issue by Nerdtality** [GeyserMC/Geyser#72]
**Describe the bug**
Chests disappears on re-log

**To Reproduce**
Place chest;
re-log;
chest is invisible;
panic!

**Expected behavior**
Chest is not supposed to be invisible

**Screenshots**
Cannot, because they are invisible, lol

**Server version**
1.14.4

**Geyser version**
"SNAPSHOT 1"

**Bedrock version**
1.12.1

**Comment by RednedEpic** [comment]
Yep, this is known. Thanks for opening an issue!

**Comment by RednedEpic** [comment]
Fixed in [`block-entities`](https://github.com/GeyserMC/Geyser/tree/block-entities) branch.

**Comment by JuniorJPDJ** [comment]
Also chests which was placed by another person are invisible (but you probably know that)

**Comment by LegacyGamerHD** [comment]
@JuniorJPDJ well if use inventory branch it has it lol

**Comment by JuniorJPDJ** [comment]
Yes, thank you ;)

**Comment by RednedEpic** [comment]
Implemented in inventory branch.
