### ISSUE TITLE
Parrot pant sound error... again

### ISSUE THREAD

**Issue by CuteTadpole** [GeyserMC/Geyser#721]
**Describe the bug**
> Sometimes parrots can pant when the wolf is near, and this pant sound causes error and kick.

This bug was already fixed with #623 PR, and I've just tested this PR (using Standalone Geyser) - it works, no errors, no player kicks, _no parrot pant sounds..._ But using latest Standalone Geyser build I again get this error, same as in reports #618 and #516.

**To Reproduce**
1. Spawn the parrot and the wolf next to each other (in Java Minecraft):
![image](https://user-images.githubusercontent.com/61086561/83468068-67109600-a484-11ea-83e7-c7362f82d1d6.png)
2. Switch to Bedrock Minecraft
3. Wait a little bit
4. Get this errors in console
![image](https://user-images.githubusercontent.com/61086561/83468146-97f0cb00-a484-11ea-927f-bb2e28fb851d.png)

**Expected behavior**
A normal play without this error

**Screenshots / Videos**
Screenshots above

**Server Version**
![image](https://user-images.githubusercontent.com/61086561/83468232-d1c1d180-a484-11ea-9e8c-f9262b932dbf.png)

**Geyser Version**
Standalone build 213

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
I don't know, why PR doesn't work. So please help me 🥺

**Comment by DoctorMacc** [comment]
This lines up with the work we've done thus far.

Are you able to play on Geyser?

**Comment by CuteTadpole** [comment]
Yes, I can play on Geyser

**Comment by DoctorMacc** [comment]
That's good. I'll confirm this as a bug but I'm not sure what we'll do about it. How frequent is the spam?

**Comment by rtm516** [comment]
Re implement the fix that was done in MCProtocolLib

**Comment by CuteTadpole** [comment]
> How frequent is the spam?
![image](https://user-images.githubusercontent.com/61086561/83469351-20bd3600-a488-11ea-8c52-ad5dd447e2b8.png)
Almost every second

**Comment by DoctorMacc** [comment]
I assume the server uses ViaVersion? Which version is it?

**Comment by CuteTadpole** [comment]
![image](https://user-images.githubusercontent.com/61086561/83469756-37b05800-a489-11ea-860e-a484c956165a.png)

**Comment by DoctorMacc** [comment]
That could be the source of the issue.

**Comment by CuteTadpole** [comment]
Why? 2.2.3 is the latest version of ViaVersion.

**Comment by DoctorMacc** [comment]
a) ViaVersion 3.0.0 (otherwise known as ViaVersion-ABSTRACTION) exists, which could perhaps have fixed some sound mapping issue that normal Minecraft ignores.
b) It could still be their fault that such a sound was never picked up. We should see if you can get a wolf pant sound with ViaVersion and normal Minecraft Java 1.15.2.

**Comment by DoctorMacc** [comment]
Ah, no, I found the true issue.
Minecraft wiki: `19w44a: Parrots no longer imitate polar bears, wolves, and zombie pigmen.`

So the sound literally does not exist in 1.15.2, and the only solution here is to just remove that error.

**Comment by Steveice10** [comment]
As you mentioned, this was fixed in ViaVersion's abstraction branch [here](https://github.com/ViaVersion/ViaVersion/commit/6b9e67f96be0eac910840a4937d8f24e0dff3684) after I submitted an issue ticket about it.
