### ISSUE TITLE
CanBreak Adventure Mode Tools Don't Work

### ISSUE THREAD

**Issue by JammSpread** [GeyserMC/Geyser#723]
Tools which have had the CanBreak NBT tag applied to them do not work. They simply work like a normal tool.

To reproduce this issue you have to be in Java Edition (NOT via GeyserMC), have cheats on and type a command with the following syntax : ` /give @p [item] 1 0 {"can_destroy":{"blocks":["the block"]}} `. Now go into the adventure gamemode and try breaking the block specified with your tool.

It is expected to be able to break the specified block with the tool. Even though you are in Adventure mode where you can't break or place.

Minecraft Java Edition Server Software 1.15.2

Standalone Geyser [# 208](https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/208/)

Minecraft Bedrock 1.14.60.5

This was vanilla Minecraft and was done on multiplayer.
The CanPlace NBT tag was not tested.

**Comment by E404NNF** [comment]
tested CanPlaceOn flag, doesn't work too

**Comment by DoctorMacc** [comment]
According to the Minecraft Wiki, these tags do not exist on Bedrock so we will have to apply a workaround.

**Comment by E404NNF** [comment]
i suggested a workaround on discord that might be easy

**Comment by DoctorMacc** [comment]
I have a partial implementation of this - the problem is that we need to translate Java namespaced IDs into Bedrock ones (and potentially vice versa). We don't store Bedrock names in code as far as I'm aware.
