### ISSUE TITLE
Scoreboard, Double name tag, chat, entity bug with TAB plugin

### ISSUE THREAD

**Issue by OverBrave** [GeyserMC/Geyser#724]
**Describe the bug**
No scoreboard, no illusioner and vindicator. Player names appear 2 times. I can't write anything in the chat and I can't see anyone writing it. No book on lectern and no beacon purple light on end gateway 

**Screenshots / Videos**
All in one picture
![image](https://user-images.githubusercontent.com/47111280/83487093-14020780-a4b3-11ea-8ffa-0ee021f883b8.png)

Note: I can write chat on bedrock edition but i cant see on my chat, but i can see on java edition.

**Server Version**
![image](https://user-images.githubusercontent.com/47111280/83487153-2c722200-a4b3-11ea-993b-2f8cc3634f51.png)

**Geyser Version**
Standalone https://github.com/GeyserMC/Geyser/pull/722 this build

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by bundabrg** [comment]
Does the server run protocollib or Viaversion?  My feeling is they are all related as they are textual in nature.

**Comment by OverBrave** [comment]
I dont use viaversion. Server main version its 1.15.2. I using protocollib.

**Comment by bundabrg** [comment]
Sorry I meant ProtocolSupport.

**Comment by OverBrave** [comment]
Same answer.

**Comment by rtm516** [comment]
Tested in the latest version of Geyser and Paper 313:

- Illusioner and Vindicator work fine and display, (Illusioner displays as a Pillager in bedrock as its not part of the game). Evokers however do not which is what is displayed in the image
- Scoreboards work fine on vanilla with a normal deaths scoreboard.
- Chat works fine
- Only 1 player name appears
- There is a PR open for lecterns (https://github.com/GeyserMC/Geyser/pull/424)
- Normal beacon beams appear, even coloured using glass

**Comment by OverBrave** [comment]
Yes, of course
Don't forget, i using standalone and floodgate
JAVA IP: Oyna.SonCesurlar.Com
Bedrock IP: Mc.SonCesurlar.Com

![image](https://user-images.githubusercontent.com/47111280/83521627-29ddef80-a4e8-11ea-8d06-fe759ee48ff2.png)

**Comment by TheMasterBlaster** [comment]
I use standalone as well with Floodgate and don't have issues with chat but I do have the same issues with seeing the players nametag twice.

**Comment by TheMasterBlaster** [comment]
Are you using CMI to handle chat? We use VentureChat and have no issues.

**Comment by OverBrave** [comment]
Yes.

**Comment by OverBrave** [comment]
I found something for chat

![image](https://user-images.githubusercontent.com/47111280/83542483-b4801800-a503-11ea-88ba-d21ca7072162.png)

In java edition chat hover:
![image](https://user-images.githubusercontent.com/47111280/83542562-ce215f80-a503-11ea-87ca-964bc513f504.png)

**Comment by rtm516** [comment]
If your not typing that `tellraw` command by hand then its likely a bad plugin and need fixing on their end. If it is manually typed just add `"` around the player name.

**Comment by TheMasterBlaster** [comment]
I found the default floodgate prefix " * " can actually freak out some plugins. We are using " . " for the prefix and our plugins seem to have no problems with it. Might be worth testing.

**Comment by DoctorMacc** [comment]
For future reference, please keep each error as its own issue so we can track everything better.

**Comment by OverBrave** [comment]
No its tellraw sending buy plugin.
My prefix its "°"

**Comment by OverBrave** [comment]
Entitys are now appear
![image](https://user-images.githubusercontent.com/47111280/83718923-ab479600-a63e-11ea-900b-9659babcea9a.png)
![image](https://user-images.githubusercontent.com/47111280/83719371-9fa89f00-a63f-11ea-9d1f-489054ae62f5.png)

**Comment by OverBrave** [comment]
Ah now not appear witch
![image](https://user-images.githubusercontent.com/47111280/83720642-1e064080-a642-11ea-868b-a84d3eb88cba.png)

**Comment by rtm516** [comment]
Just connected to your server via the latest geyser, everything seems to work fine.
Chat, witches, beacon beam and scoreboard are all fine, lecterns are not implemented, see below images for proof of all.

![image](https://user-images.githubusercontent.com/5401186/83751368-9f6bcc00-a65e-11ea-9881-e1875e933cd6.png)
![image](https://user-images.githubusercontent.com/5401186/83751405-b4e0f600-a65e-11ea-8301-7cc434c9ecf3.png)
![image](https://user-images.githubusercontent.com/5401186/83751387-a98dca80-a65e-11ea-8294-dbb2da68e155.png)
![image](https://user-images.githubusercontent.com/5401186/83751445-c88c5c80-a65e-11ea-8f4d-a59d1bd398c5.png)

**Comment by rtm516** [comment]
I can confirm the duplicate names bug though.
![image](https://user-images.githubusercontent.com/5401186/83752780-fecadb80-a660-11ea-98dc-d55f1e573165.png)

**Comment by TheMasterBlaster** [comment]
Pretty sure I talked to you about the duplicate name bug before rtm516

**Comment by OverBrave** [comment]
@rtm516 You join without floodgate. Can you join on MC.SonCesurlar.Com ? This ip with floodgate.
Ok problem only on floodgate i think.

**Comment by TheMasterBlaster** [comment]
Did you ever try to change the bedrock prefix? I'm using floodgate without most those issues. As I said I use " . " for the prefix

**Comment by OverBrave** [comment]
Yeah after put "." chat working correctly but scoreboard, witch, double nametag contiunes keep not appear.
![image](https://user-images.githubusercontent.com/47111280/83882650-19797f00-a74b-11ea-9cd2-db03ab77d404.png)

**Comment by OverBrave** [comment]
I'm sure now that the problem is related to floodgate.

**Comment by TheMasterBlaster** [comment]
The double name issue it not due to floodgate. Since I had that issue even when I had my Geyser set to online mode. And scoreboards seem fine for me. With and without floodgate.

**Comment by OverBrave** [comment]
I know that showing names twice is not related to floodgate. But I think others are related to floodgate. Because if you try to enter the server without connecting floodgate, you will see this time scoreboard.

**Comment by TheMasterBlaster** [comment]
The scoreboard from McMMO and Jobs Reborn works just fine for me. Its possible it's your plugin. Since with Floodgate it adds a prefix.

**Comment by OverBrave** [comment]
I use the paid version of the TAB plugin. It includes scoreboard support and I use it on all my servers. The table is displayed successfully when there is no Floodgate.

https://www.mc-market.org/resources/14009/

**Comment by TheMasterBlaster** [comment]
As I said the prefix could be causing the issue. Does it happen with a linked account since there would be no prefix?

**Comment by OverBrave** [comment]
I am not using the linked account feature. Because it causes problems on my server. The name and UUIDs interlock.

**Comment by TheMasterBlaster** [comment]
It's still possible TAB has issues with the prefix. Since a . Or any symbol like that is not allowed in a username. I wonder if it would work without a prefix set?

**Comment by OverBrave** [comment]
I try it in new machine and same, again not appear scoreboard

**Comment by OverBrave** [comment]
Problem still contiunes,
same on 1.16.1 version.

**Comment by OverBrave** [comment]
@RednedEpic Can you take a look at this event? If you want, I can share my machine information. on PM

**Comment by OverBrave** [comment]
Now to sum up the event
1- If I open it on my own VDS, some entitys and scoreboard are not visible.
2- If @rtm516  opens as standalone, everything is working properly.
3- If I install it in bungeecord everything works fine but this time I have to give the main server's ip address for the players to enter.
4- There is a waterdog fork for this, but I use the Aegis fork for crash protection, so I cannot use it.
Now we only know them. What should we do in this situation?

**Comment by OverBrave** [comment]
https://github.com/GeyserMC/Geyser/issues/977

**Comment by OverBrave** [comment]
Duplicate of #977

**Comment by OverBrave** [comment]
Don't forget, double nametag problem contiunes.

**Comment by CleanCorpze** [comment]
Im having the same thing with TAB plugin the name above player heads stack and its as if there are duplicate name tags above the head. Im using Paper Spigot and version 1.15.2. Im not sure but is this glitch still a thing because I would really like to use TABS plugin, I have substituted it with NameTagEdit. But I would much rather use TAB.

**Comment by mA0w0** [comment]
It seems that the normal name and the name of the TAB plugin are displayed.
Originally, the Java version seems to have no problem because the TAB plugin has a function to hide the normal name.
The Bedrock version has no effect, so it seems to be displayed twice.

An easy solution is the option to hide the player's name.
If you have a TAB plugin, you might want to implement an option to hide the name.
Nickname plugins can be supported by TAB plugins, so by making TAB plugins available, nicknames can also be used.

**Comment by mA0w0** [comment]
I've noticed that this issue doesn't occur if the Bedrock player logs in first and the Java player logs in later.
This problem occurs in the opposite case.
If the Java player logs in first and then the Bedrock player logs in, the name will be displayed twice.

**Comment by Hay127** [comment]
![IMG-20230317-WA0024.jpg](https://user-images.githubusercontent.com/83993950/226528420-89eb49a7-2edd-4586-bd1e-d324f05e3be5.jpg)

I Have Read Various Opinions And Solutions From Various Web Especially The Solution From This Report, The Bug Still Occurs Even If No Java Player Joins, Duplicate Nicknames Still Appear Somehow I Have To Get Rid Of It

**Comment by Hay127** [comment]
The Bug Occurs In All Bedrock And Java Players

**Comment by Hay127** [comment]
Before this there was no problem or bug like this, I have been using the same tab file for months without any problem only this time it showed up a duplicate name

**Comment by Camotoy** [comment]
Make sure you're using the very latest Geyser build. Otherwise, please send a Geyser dump in a new issue.

**Comment by Hay127** [comment]
https://dump.geysermc.org/I4tgOiCJPxmLLqxnLDhjnLydl3cRtqTc  

This My Geyser Dump

**Comment by agoniaprivat** [comment]
Issue still persists with almost all nametag plugins. Both on TAB and other plugins using "Unlimited nametags".

A feature from Geyser to disable "vanilla nametags" would fix a lot of incompabilitys with plugins.
