### ISSUE TITLE
Auto jump not working

### ISSUE THREAD

**Issue by Nerdtality** [GeyserMC/Geyser#73]
Describe the bug
Auto jump not working

Expected behavior
Player is supposed to be automatically elevated up the next near block they intend to go up. This is a normal behavior for (PE)

Server version
1.14.4

Geyser version
"SNAPSHOT 1"

Bedrock version
1.12.1

**Comment by Nerdtality** [comment]
This is also most likely related with ladders not working as intended

**Comment by RednedEpic** [comment]
Autojump can be toggled in the game. Make sure that it is enabled (using Windows 10 edition, it is disabled by default for all input types).

**Comment by Nerdtality** [comment]
> 
> 
> Autojump can be toggled in the game. Make sure that it is enabled (using Windows 10 edition, it is disabled by default for all input types).

@RednedEpic I am using pocket edition, autojump is enabled and not working. However it works correctly on other worlds and servers

**Comment by RednedEpic** [comment]
> @RednedEpic I am using pocket edition, autojump is enabled and not working. However it works correctly on other worlds and servers
Alright, thanks for letting us know.
