### ISSUE TITLE
CMI tpa title shows null instead of nothing

### ISSUE THREAD

**Issue by TheMasterBlaster** [GeyserMC/Geyser#732]
**Describe the bug**

The Title that shows when tpa'ing with CMI shows null on Bedrock when it should be blank.

**To Reproduce**

1. send a tpa request

2. wait for it to be accepted

3. see error

**Expected behavior**

The title message to show nothing like in Java

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/9083212/83596601-0724f880-a533-11ea-80e8-37ff40148a1a.png)

**Server Version**

Paper version git-Paper-325 (MC: 1.15.2)

**Geyser Version**

Geyser Standalone version 1.0-SNAPSHOT (git-master-5eef265)

**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

**Comment by E404NNF** [comment]
can confirm, happens on DeluxMentions for me too

**Comment by rtm516** [comment]
Not having this issue, still need to look into it more though.
![image](https://user-images.githubusercontent.com/5401186/84326713-863eb000-ab75-11ea-95ad-438e7af00c7e.png)

**Comment by TheMasterBlaster** [comment]
The server I use has the top line blank on Java the bottom one is the only one that should show text with our setup

**Comment by Chew** [comment]
This should've been fixed in #1498, if not, let us know. Thank you for the report!
