### ISSUE TITLE
Whitelist/blacklist for specific commands

### ISSUE THREAD

**Issue by 20Jonas18** [GeyserMC/Geyser#733]
**What feature do you want?**
I want a command whitelist and a blacklist because the screen freezes if there are too many plugins on the server.

**Alternatives?**
I did not try any alternatives, because in my situation this would not go so well.

**Comment by arshizx** [comment]
check config.yml, set ``command-suggestions: true`` to ``command-suggestions: false``, save, then use /geyser reload or reload/restart the server

**Comment by DoctorMacc** [comment]
This user is specifically referring to whitelisting/blacklisting specific commands that will not be sent to the server.

**Comment by arshizx** [comment]
he say because his screen freezes if there are too many plugins on the server. but hmm idk

**Comment by DoctorMacc** [comment]
I discussed with this person on Discord.

**Comment by arshizx** [comment]
Oh k i just want to help xD

**Comment by DoctorMacc** [comment]
All good.

**Comment by RednedEpic** [comment]
Thanks for the suggestion, however this is likely to not be implemented into mainline Geyser. This is a much more fitting feature for a Geyser extension which is currently being implemented in the feature/extensions branch.

I've also created a quick extension [here](https://github.com/RednedEpic/HideCommands) that essentially implements this. Feel free to give this a go once extensions are within mainline Geyser.
