### ISSUE TITLE
Commands like /workbench don't work

### ISSUE THREAD

**Issue by rtm516** [GeyserMC/Geyser#737]
**Describe the bug**
Commands like `/workbench` don't work

**To Reproduce**
1. Install EssentialsX
2. Use the command `/workbench`

**Expected behavior**
A crafting table GUI opens

**Server Version**
Paper version git-Paper-313 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
Master as of https://github.com/GeyserMC/Geyser/commit/5fca5d5ef50c04dcfc0932e997f10bac6f7269dd

**Minecraft: Bedrock Edition Version**
Win10 1.14.60

**Comment by DoctorMacc** [comment]
Can confirm this bug - tried to fix it by putting a crafting table above the head like we do for chests, but no luck.

**Comment by Wumpotamus** [comment]
It's not possible to send a crafting table inventory to Bedrock players.

**Comment by DoctorMacc** [comment]
This now works in 1.16.
