### ISSUE TITLE
Mojang Account Authentication Caching

### ISSUE THREAD

**Issue by francescomikulis** [GeyserMC/Geyser#739]
**Objective: reduce the pain for mobile sign-in**
Geyser is absolutely wonderful but I find myself signing into my Mojang account every single time I login to (my) same server.  Would it be possible to cache the credentials?  I'm suggesting the following:
1. Cache the RESULT of the credential authentication in a running version of the server - never actually storing credentials to the application or to disk.
2. Cache the Xbox email address as "verified" once the first Mojang login in successful - thus a HashMap from Xbox IDs (available on the client) to a boolean for "is Mojang authenticated".

**Why this approach?**
This approach does not require any changes on the client side of the application; it saves time to login and invites more people to jump onto the server from their mobile devices.

**Minor issues with this approach**
Users that authenticate on one server will be prompted again if they logout and log back into another server that uses Geyser.

**Comment by Heath123** [comment]
This isn't something we could do because it gives server owners complete access to player's Minecraft accounts. Try using Floodgate with account linking.

**Comment by DoctorMacc** [comment]
To follow up on this: there is a field for inputting your Mojang credentials in your config. See: https://github.com/GeyserMC/Geyser/wiki/Understanding-the-Config
