### ISSUE TITLE
the problem with the drawing

### ISSUE THREAD

**Issue by danila163** [GeyserMC/Geyser#741]
problem with drawing, the player draws more than necessary, this greatly affects the performance of the device

Image in server:
https://media.discordapp.net/attachments/624959336275509248/718761021405396992/Minecraft_06.06.2020_13_39_32.png?width=763&height=408

Config:
#Minecraft server properties
#Sat Jun 06 12:55:16 MSK 2020
spawn-protection=16
max-tick-time=-1
query.port=16639
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=2
enable-query=true
player-idle-timeout=0
difficulty=3
spawn-monsters=true
op-permission-level=4
pvp=true
snooper-enabled=true
level-type=DEFAULT
hardcore=false
enable-command-block=false
network-compression-threshold=256
max-players=1000
resource-pack-sha1=
max-world-size=29999984
rcon.port=17639
server-port=25639
debug=false
server-ip=192.162.244.254
spawn-npcs=true
allow-flight=false
level-name=world
view-distance=6
resource-pack=
spawn-animals=true
white-list=false
rcon.password=SGRgvrZUsL
generate-structures=true
max-build-height=256
online-mode=false
level-seed=
use-native-transport=true
prevent-proxy-connections=false
motd=Hosting Craft-Hosting.ru
enable-rcon=false

**Comment by rtm516** [comment]
> problem with drawing, the player draws more than necessary, this greatly affects the performance of the device
> 
> Image in server:
> https://media.discordapp.net/attachments/624959336275509248/718761021405396992/Minecraft_06.06.2020_13_39_32.png?width=763&height=408
> 
> Config:
> #Minecraft server properties
> #Sat Jun 06 12:55:16 MSK 2020
> **SNIP**

Please follow the issue template and this also looks like a client issue nothing todo with Geyser.

**Comment by DoctorMacc** [comment]
Yes, this should be controlled by the server. Because of this I'm closing this issue; if you feel this does not replicate Java behavior please comment.

**Comment by rtm516** [comment]
Reopening this, as we have had reports of it causing issues and we seem to ignore the clients render distance settings. This causes issues when the clients render distance is less than the java servers.

**Comment by Camotoy** [comment]
This should now be resolved. Let us know otherwise!
