### ISSUE TITLE
Skin issue with linked accounts

### ISSUE THREAD

**Issue by TheMasterBlaster** [GeyserMC/Geyser#744]
**Describe the bug**

After linking an account, Iv noticed the skin is not visible after you relog. Even if you have a Bedrock and Java skin. From what I have seen the only way to see your skin again is to unlink then relink your account.

**To Reproduce**

1. Link your bedrock account to your Java account

2. Relog

3. See yourself as Steve

**Expected behavior**

For the Linked account to see the skin.

**Screenshots / Videos**

**Server Version**

Tuinity version git-Tuinity-"e41b5ce" (MC: 1.15.2)
It also happened with Paper

**Geyser Version**

Geyser version 1.0-SNAPSHOT (git-e7b072ac546cdf8b258c6b9b860785e64f66f0da-e7b072a)
but it happened with Geyser ccb44f6 as well 

**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

I am using Geyser Standalone with Floodgate on a Bungeecord server.

**Comment by Heath123** [comment]
This is a Floodgate issue- can someone move it there?

**Comment by DoctorMacc** [comment]
I'll leave that up to RTM - it's possible this is handled on Geyser's side.

**Comment by TheMasterBlaster** [comment]
I asked in Discord if I should post it on here 

![image](https://user-images.githubusercontent.com/9083212/83951977-8d775e00-a803-11ea-9f9a-c5f9822bba6e.png)

**Comment by Heath123** [comment]
This is when you look from Java, right? I don't see any way that geyser could interfere with that. By the way I knew that there were skin issues when I first started on account linking

**Comment by TheMasterBlaster** [comment]
The skin is not visible to the Bedrock client after linking accounts and relogging. sorry if I wasn't clear on that.

**Comment by bundabrg** [comment]
Can you test with #680 which greatly fixes skin issues.

**Comment by TheMasterBlaster** [comment]
Seems #680 fixes my issue.
![image](https://user-images.githubusercontent.com/9083212/83975534-6c297700-a8c2-11ea-80e6-42a57eb5fa4f.png)
