### ISSUE TITLE
Cant destroy bamboo

### ISSUE THREAD

**Issue by danielboos1** [GeyserMC/Geyser#745]
**Describe the bug**
I just cant destroy this(check images) also moving around those when they are grown close to each other causes rubber banding issues. Breaking animations show when trying to break it but it doesn't end up breaking

![unknown](https://user-images.githubusercontent.com/46797782/83951001-0f9e6b80-a872-11ea-9f90-c787c8e13dd2.png)

**Expected behavior**
To be able to destroy it and more around it properly
**Screenshots / Videos**

**Server Version**
1.15.2
**Geyser Version**
master 203

**Minecraft: Bedrock Edition Version**
Latest I think latest is 1.14.6

**Comment by DoctorMacc** [comment]
I'm unaware of an issue with breaking it - bamboo position is calculated differently in Java and Bedrock (literally the positions are different) but this may be resolved with movement fixes.

**Comment by Heath123** [comment]
That's bamboo...

**Comment by Heath123** [comment]
Maybe this is the reach issue? The moving issue is separate though

**Comment by DoctorMacc** [comment]
What client are you using? (iOS, Android...)

**Comment by danielboos1** [comment]
Windows 10 minecraft edition

**Comment by DoctorMacc** [comment]
Survival or creative?

**Comment by danielboos1** [comment]
Survival

**Comment by lukemagdalin** [comment]
I have tested this and it works using git-paper-368 1.15.2, and geyser build #244.

**Comment by RednedEpic** [comment]
Stale + unable to be reproduced. Please open a new issue w/ updated replication steps if this still occurs.

**Comment by xcomcadx** [comment]
i can confirm its happening with me aswell, I seem to get stuck to blocks above me and other half blocks such as stone fences
