### ISSUE TITLE
Animations don't work properly when jumping before breaking a block

### ISSUE THREAD

**Issue by danielboos1** [GeyserMC/Geyser#746]
**Describe the bug**
When breaking dirt breaking animations don't match it when breaking
like the little cracks that are created when you break dirt are like little and the dirt breaks before the creaks reach all the way.

**To Reproduce**
1. Jump of a block to dirt block placed next to water
2.while still in air start mining that block

**Expected behavior**
Block breaks when animations are correct.

**Screenshots / Videos**
Video[video](https://cdn.discordapp.com/attachments/613163671870242842/714075397670567977/Minecraft_2020-05-24_-_21-09-59-01.mp4) 

**Server Version**
1.15.2

**Geyser Version**
master 203

**Minecraft: Bedrock Edition Version**
1.14.6

**Comment by RednedEpic** [comment]
This goes for any block if you start jumping before you start breaking them. I've updated the title to include this.
