### ISSUE TITLE
Trading with villagers causes client crash.

### ISSUE THREAD

**Issue by YaUhYeah** [GeyserMC/Geyser#747]
**Describe the bug**
When attempting to trade with a villager, bedrock edition client crashes,
I use paper 1.8.8 as my server version so could potentially be legacy version exclusive bug.

**To Reproduce**
Spawn a villager and attempt to trade with it on any bedrock edition client.
Be sure to try a few different server versions such as 1.8.8 1.13 etc

**Expected behavior**
When interacting with a villager the expected outcome is for the villager trading menu to open and depending on the villager you will have different items you can trade.

**Screenshots / Videos**
In attached zip file
[villagererror.zip](https://github.com/GeyserMC/Geyser/files/4741412/villagererror.zip)

**Server Version**
paperspigot 1.8.8

**Geyser Version**
geyser master build 223

**Minecraft: Bedrock Edition Version**
Tried with a nintendo switch, android phone and win10 edition ALL on latest bedrock edition.

**Additional Context**
I also have the shopkeeper plugin which could have caused some interference however did try without and same effect.

**Comment by E404NNF** [comment]
can confirm on 1.13.2 paper too
![image](https://user-images.githubusercontent.com/37207067/83960952-d4f6fc00-a88e-11ea-86aa-6abb0f0e6f17.png)
Video: https://cdn.discordapp.com/attachments/613169749525790737/719058121590308864/2020-06-07_07-18-32.mp4

**Comment by AJ-Ferguson** [comment]
Will be fixed by #748
