### ISSUE TITLE
When Bedrock touchscreen client adds/breaks blocks more than 5 blocks away, Java server ignores the changes. Client and server are out of sync.

### ISSUE THREAD

**Issue by firebus** [GeyserMC/Geyser#749]
**Describe the bug**

Two clients connected to server, one Java, one Bedrock. Both are building things. The things the Java client is building are visible to the Bedrock client. Most of the things that the Bedrock client are building are invisible to the Java client.

Both clients disconnect and reconnect. The things the Bedrock client built are gone.

**To Reproduce**

Bedrock touchscreen client creates or removes blocks more than 5 blocks away from their current position.

**Expected behavior**

Bedrock clients can build things that are visible to all other clients, and persist in the world.

**Screenshots / Videos**

[Screenshot](https://photos.app.goo.gl/5Tq76TqkLC1vRHLc7)

The Bedrock client is on the left, they have replaced the gold and blue (glass?) blocks at the end of the path with gold ore. The Java client is on the right, they still see the old state.

**Server Version**

Spigot 1.15.2

**Geyser Version**

```
[15:53:10] [Server thread/INFO]: [Geyser-Bukkit] Loading Geyser version 1.0-SNAPSHOT (git-master-ccb44f6)
```

**Minecraft: Bedrock Edition Version**

1.14.60, on iPad

**Additional Context**

No other plugins on the server besides Geyser and Floodgate.

**Comment by DoctorMacc** [comment]
Looks like that error points to some sort of item frame issue.

**Comment by firebus** [comment]
Per a suggestion in Discord, I downloaded the latest GeyserMC, but the issue reoccurred. I didn't see the same warning in the log, so it's possible that the warning is totally unrelated.

The problem is intermittent, not continuous. Sometimes block placement/removal works, sometimes it doesn't. 

When this happens, while the view for the Bedrock client matches the actions taken by the Bedrock client, movement obeys the state of the world on the server. For example, if the broken Bedrock client removes a wall, and then tries to walk through where the wall was, they will be blocked by the wall that still exists server-side.

**Comment by DoctorMacc** [comment]
This *may* be a mobile and reach problem - we already have a PR that fixes block removal on long reach, yet you confirm that this happens with place. We also had a report in Discord a very long time ago describing block placement, yet we've never had a replica of such an issue until now. It's likely some sort of mobile issue since the block removal is too.

Does this happen in creative mode or survival mode too?

**Comment by firebus** [comment]
We've only tried in creative mode. I can try survival and see if there's any difference...

**Comment by DoctorMacc** [comment]
Yes, please do if you can; that'll help narrow down the problem. Touchscreen clients in creative allow for a greater reach that Java servers do not accept, which causes problem.

**Comment by firebus** [comment]
Defintely more reliable in survival, though we still saw a few skipped blocks. I'll do some more experiments on this tonight to see if I can reliably reproduce it!

**Comment by CCF100** [comment]
I had my friend record a video demonstrating this issue if it helps: https://youtu.be/6p5f8n7DKZM

**Comment by DoctorMacc** [comment]
@CCF100 thank you for the video! 

I'll try to get this going again; the problem is that I want to ensure I get the math right.

**Comment by DoctorMacc** [comment]
If anyone is affected by this issue and runs a modern server version, please try #1336.
