### ISSUE TITLE
Duplicate in-game names being populated in player list

### ISSUE THREAD

**Issue by Nerdtality** [GeyserMC/Geyser#75]
**Describe the bug**
Duplicate in-game names being populated in player list

**Expected behavior**
No duplicates

**Screenshots**
![image](https://user-images.githubusercontent.com/19711169/68094595-bb5c8480-fe67-11e9-8583-0b1dc927e76b.png)

**Server version**
1.14.4

**Geyser version**
SNAPSHOT 1.0

**Bedrock version**
1.12.1

**Comment by RednedEpic** [comment]
> **Describe the bug**
> Duplicate names being created
> 
> **Expected behavior**
> No duplicates
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/19711169/68094595-bb5c8480-fe67-11e9-8583-0b1dc927e76b.png)
> 
> **Server version**
> 1.14.4
> 
> **Geyser version**
> SNAPSHOT 1.0
> 
> **Bedrock version**
> 1.12.1

This is expected. One of them is the name of your bedrock account, the other is the name of your java account. If your java account name is different from your bedrock one, it'll show up differently. Not fully sure if this is fixable without causing other problems. I'll leave this open until this information is known.

**Comment by EOT3000** [comment]
Here's a hack. Remove the bedrock player's name from the player list on join.

**Comment by Loganh4005** [comment]
> Here's a hack. Remove the bedrock player's name from the player list on join.

How do you?
