### ISSUE TITLE
Command blocks don't open

### ISSUE THREAD

**Issue by EvanMcGregor** [GeyserMC/Geyser#754]
**Describe the bug**
Both command blocks and villager trading do not work. Command blocks cannot be opened and villagers cannot be traded with as their trade menu cannot be opened.

**To Reproduce**

For commands:
1. Get a command block using /give @p command_block.
2. Place it.
3. Its interface cannot be opened.

**Expected behavior**
You should be able to open and edit command blocks and villager trading should work.

**Server Version**
Vanilla 1.15.2

**Geyser Version**
Build 129

**Minecraft: Bedrock Edition Version**
1.14.6 Pocket Edition

**Comment by Heath123** [comment]
Shouldn't these be separate issues?

**Comment by Heath123** [comment]
Also build 129 is ridiculously outdated

**Comment by EvanMcGregor** [comment]
I guess... but I’ve already created it

**Comment by RednedEpic** [comment]
Villager trading is now implemented, and there is already an issue tracking it. Command blocks are unimplemented. In the future, _please_ use the latest version of Geyser before opening an issue of any kind.

**Comment by Heath123** [comment]
You can edit it
Also download the latest build from https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/
Trading was added recently

**Comment by Heath123** [comment]
You can edit out the villager part and make it an issue about command blocks

**Comment by DoctorMacc** [comment]
Also in the future, *please* create separate issues for each problem. Also ensure the villager has an occupation which allows for trading.

**Comment by EvanMcGregor** [comment]
It has been updated everyone

**Comment by EvanMcGregor** [comment]
Command blocks are still bugged however on latest version

**Comment by EvanMcGregor** [comment]
The same with enchantment tables but I think that has been mentioned

**Comment by DoctorMacc** [comment]
Thank you for updating. We are aware of enchantment tables (see our README).

**Comment by EvanMcGregor** [comment]
Ah ok. I am guessing that will be a 1.16 fix. Will command blocks also be featured then?

**Comment by Heath123** [comment]
Maybe

**Comment by DoctorMacc** [comment]
We’ll look into it then.

**Comment by EvanMcGregor** [comment]
OK. In addition, banners are totally broken for me as well - I can only see the colour. Is that expected behaviour?

**Comment by EvanMcGregor** [comment]
Alright - and on the topic of villager trading, it is bugged for players I am talking to right now. They are saying the villagers do not level up...

**Comment by Heath123** [comment]
> Alright - and on the topic of villager trading, it is bugged for players I am talking to right now. They are saying the villagers do not level up...

Please either open an another issue or ask about it on the Discord

**Comment by EvanMcGregor** [comment]
Whoops - forgot this was about the command block issues! I apologise for that

**Comment by DoctorMacc** [comment]
This has been fixed in the latest Geyser.
