### ISSUE TITLE
Players killable without clicking respawn after death

### ISSUE THREAD

**Issue by Nerdtality** [GeyserMC/Geyser#76]
**Describe the bug**
Player can be killed without clicking respawn after death.

**Server version**
1.14.4

**Geyser version**
SNAPSHOT 1.0

**Bedrock version**
1.12.1

**Comment by RednedEpic** [comment]
> **Describe the bug**
> Player can be killed without clicking respawn after death.
> 
> **Server version**
> 1.14.4
> 
> **Geyser version**
> SNAPSHOT 1.0
> 
> **Bedrock version**
> 1.12.1

Apologies for the late reply on this. Could you please test this out with the 1.13 branch considering quite a bit changed when it comes to respawning in that version?

**Comment by RednedEpic** [comment]
Resolved in latest commit.
