### ISSUE TITLE
Errors on Xbox

### ISSUE THREAD

**Issue by D3ATHBRINGER13** [GeyserMC/Geyser#760]
**Describe the bug**

Many errors coming down from the top of the screen

**To Reproduce**

Connect to a geyser server and walk around for a while

**Expected behavior**

Nothing

**Screenshots / Videos**

![geysertest1](https://user-images.githubusercontent.com/53559772/84417940-4d9ee500-ac0e-11ea-9cf6-5826e700b048.jpeg)

**Server Version**

git-Paper-318 (MC: 1.15.2)

**Geyser Version**

Geyser-Bukkit build 231

**Minecraft: Bedrock Edition Version**

1.14.60 on Xbox

**Additional Context**

**Comment by D3ATHBRINGER13** [comment]
Don't know if this is xbox specific, but I thought it would be good to mention it anyway

**Comment by Heath123** [comment]
This could be a client bug

**Comment by D3ATHBRINGER13** [comment]
should i reinstall and then try again?
see if that helps

**Comment by DoctorMacc** [comment]
These sorts of errors don’t seem to be Geyser errors. What other plugins do you have installed?

**Comment by D3ATHBRINGER13** [comment]
Only worledit and it wasn't being used at the time

**Comment by DoctorMacc** [comment]
Molang refers to Mojang's internal language. I agree that it may be a client bug or Xbox displaying errors that other platforms do not,

**Comment by D3ATHBRINGER13** [comment]
Ok
