### ISSUE TITLE
Show java.lang.NullPointerException at login

### ISSUE THREAD

**Issue by duanjiangDJ** [GeyserMC/Geyser#761]
(I'm Chinese,so I can't say English very well.If you are confused about the meaning of English, you can try to translate Chinese.)
**Describe the bug**
En:Disconnect after show java.lang.NullPointerException at login 
Zh:在登录时显示“java.lang.NullPointerException”之后退出服务器

**To Reproduce**
En:
1.Enter the login interface.
2.Enter the correct account and password.
3.Click the login button.
4.eject java.lang.NullPointerException
Zh:
1.进入登录界面
2.输入正确的账号和密码
3.点击登录按钮
4.弹出“java.lang.NullPointerException”错误

**Expected behavior**
En:Player successfully logged in server
Zh:玩家成功登录服务器

**Screenshots / Videos**
![Screenshot_2020-06-12-01-46-17-158_com mojang minecraftpe](https://user-images.githubusercontent.com/61219272/84425836-c6289480-ac54-11ea-8b3d-d6adfe3ffaca.jpg)
![Screenshot_2020-06-12-00-40-27-408_com microsoft rdc android beta](https://user-images.githubusercontent.com/61219272/84425887-e6585380-ac54-11ea-99b4-a773466c844c.jpg)

**Server Version**
spigot1.15.2

**Geyser Version**
Geyser-Bukkit build 231

**Minecraft: Bedrock Edition Version**
1.14.60 on Android

**Additional Context**
Nothing

**Comment by Heath123** [comment]
It looks like the error happens here:
https://github.com/GeyserMC/Geyser/blob/7fcd8f2daf9cc39c61d37934751251e22b202e14/connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java#L332

**Comment by DoctorMacc** [comment]
Could you redownload Geyser?

**Comment by DoctorMacc** [comment]
Could you redownload Geyser?

**Comment by duanjiangDJ** [comment]
> Could you redownload Geyser?

I tried, but it still went wrong

**Comment by CuteTadpole** [comment]
Can you send your configuration file?

**Comment by duanjiangDJ** [comment]
> It looks like the error happens here:
> https://github.com/GeyserMC/Geyser/blob/7fcd8f2daf9cc39c61d37934751251e22b202e14/connector/src/main/java/org/geysermc/connector/network/session/GeyserSession.java#L332

It seems so, but there seems to be no problem in that line

**Comment by duanjiangDJ** [comment]
> Can you send your configuration file?

Sure.
# --------------------------------
# Geyser Configuration File
bedrock:
  address: 0.0.0.0
  port: 19132
  motd1: Geysermc
  motd2: Another GeyserMC forced host.
remote:
  address: 127.0.0.1
  port: 19132
  auth-type: floodgate
floodgate-key-file: public-key.pem
command-suggestions: true
passthrough-motd: false
passthrough-player-counts: false
legacy-ping-passthrough: false
ping-passthrough-interval: 3
max-players: 100
debug-mode: false
general-thread-pool: 32
allow-third-party-capes: true
allow-third-party-ears: false
default-locale: en_us
cache-chunks: false
above-bedrock-nether-building: false
metrics:
  enabled: true
  uuid: c0cc1fba-cb3b-4da9-a361-f0887a88bdd9
config-version: 3

**Comment by CuteTadpole** [comment]
Okay, does your remote server use port 19132 or other? (or just send `server.properties` file in server directory)

**Comment by duanjiangDJ** [comment]
> > Can you send your configuration file?
> 
> Sure.
> 
> bedrock:
> address: 0.0.0.0
> port: 19132
> motd1: Geysermc
> motd2: Another GeyserMC forced host.
> remote:
> address: 127.0.0.1
> port: 19132
> auth-type: online
> floodgate-key-file: public-key.pem
> command-suggestions: true
> passthrough-motd: false
> passthrough-player-counts: false
> legacy-ping-passthrough: false
> ping-passthrough-interval: 3
> max-players: 100
> debug-mode: false
> general-thread-pool: 32
> allow-third-party-capes: true
> allow-third-party-ears: false
> default-locale: en_us
> cache-chunks: false
> above-bedrock-nether-building: false
> metrics:
> enabled: true
> uuid: c0cc1fba-cb3b-4da9-a361-f0887a88bdd9
> config-version: 3

**Comment by duanjiangDJ** [comment]
> Okay, does your remote server use port 19132 or other? (or just send `server.properties` file in server directory)
Only port 19132.

**Comment by rtm516** [comment]
Login to a microsoft account, it should fix your problem

**Comment by ppfirework** [comment]
你的问题吧
我昨天还可以的

**Comment by duanjiangDJ** [comment]
> 你的问题吧
> 我昨天还可以的

你是用哪个核心的

**Comment by ppfirework** [comment]
paperspigot

**Comment by duanjiangDJ** [comment]
> paperspigot

都差不多的，应该不会出错的吧

**Comment by duanjiangDJ** [comment]
> > paperspigot
> 
> 都差不多的，应该不会出错的吧

是不是我哪里设置不对

**Comment by duanjiangDJ** [comment]
> paperspigot

是不是我哪里设置不对？

**Comment by rtm516** [comment]
> Login to a microsoft account, it should fix your problem

@duanjiangDJ are you logged in to a Microsoft account?

**Comment by ppfirework** [comment]
肯定是
这么多人用geyser就你有这个问题？

**Comment by duanjiangDJ** [comment]
> > Login to a microsoft account, it should fix your problem
> 
> @duanjiangDJ are you logged in to a Microsoft account?

yes

**Comment by duanjiangDJ** [comment]
> 肯定是
> 这么多人用geyser就你有这个问题？

我不知道别人有没有
至少目前没有

**Comment by duanjiangDJ** [comment]
> > Login to a microsoft account, it should fix your problem
> 
> @duanjiangDJ are you logged in to a Microsoft account?

I don't know if I set it up wrong?

**Comment by duanjiangDJ** [comment]
> > > Login to a microsoft account, it should fix your problem
> > 
> > 
> > @duanjiangDJ are you logged in to a Microsoft account?
> 
> yes

It's my Xbox account

**Comment by duanjiangDJ** [comment]
> 肯定是
> 这么多人用geyser就你有这个问题？

能不能发一下你的配置文件，我对照我的看一下哪里不对

**Comment by ppfirework** [comment]
> > 肯定是
> > 这么多人用geyser就你有这个问题？
> 
> 能不能发一下你的配置文件，我对照我的看一下哪里不对

就是把auth type改成true
其他我都没动过

**Comment by duanjiangDJ** [comment]
> > > 肯定是
> > > 这么多人用geyser就你有这个问题？
> > 
> > 
> > 能不能发一下你的配置文件，我对照我的看一下哪里不对
> 
> 就是把auth type改成online
> 其他我都没动过

真奇怪，我用win10版又可以进
