### ISSUE TITLE
java.util.zip.DataFormatException: No zlib header

### ISSUE THREAD

**Issue by AlexDev404** [GeyserMC/Geyser#762]
I'm not sure if this is a bug or not, but just in case I am still reporting this. Whenever I try to connect to Geyser using Minecraft PE it shows up with the error

**`java.util.zip.DataFormatException: No zlib header`**

Is this a problem with me (the host) or with the software itself?

**Comment by DoctorMacc** [comment]
Are you using the beta version of Minecraft?

**Comment by AlexDev404** [comment]
yes

**Comment by DoctorMacc** [comment]
That would be why, I'm afraid. Geyser does not support the beta versions. Please downgrade back to 1.14.60 in order to use Geyser.

**Comment by AlexDev404** [comment]
Oh alright. Sorry for the inconvenience.

**Comment by DoctorMacc** [comment]
No worries whatsoever.
