### ISSUE TITLE
/playsound volume does seem to translate to Bedrock

### ISSUE THREAD

**Issue by TheMasterBlaster** [GeyserMC/Geyser#770]
**Describe the bug**

The Volume of the playsound command does not seem to make it to the Bedrock client.

**To Reproduce**

1. Run the playsound command with a high volume(I used a Music Disc).

2. Move away from the sound/music.

3. See the volume is default(or close).

**Expected behavior**

For the Volume to work as it does on Java

**Screenshots / Videos**

**Server Version**

Tuinity version git-Tuinity-"2051fe3" (MC: 1.15.2)

**Geyser Version**

Standalone Build # 231

**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

**Comment by RednedEpic** [comment]
Looks to be a Bedrock bug: https://bugs.mojang.com/browse/MCPE-104500.
