### ISSUE TITLE
Cannot see the top of the nether.

### ISSUE THREAD

**Issue by benrobson** [GeyserMC/Geyser#772]
**Describe the bug**
Cannot see anything on the top of the Nether

**To Reproduce**
On a Bedrock client, access the top of the Nether with a nether portal.

**Expected behaviour**
Should be able to see the top of the nether.

**Screenshots / Videos**
Java: https://imgur.com/a/w6GlDvZ
Bedrock: https://imgur.com/a/NVolH1J

**Server Version**
https://gyazo.com/f23805b40ac743c747d9937a6cae8326

**Geyser Version**
Master branch, I can't see what build I am using.

**Minecraft: Bedrock Edition Version**
Windows 10, build 3968506

**Comment by rtm516** [comment]
Please see the `above-nether-bedrock-building` setting in the (config)[https://github.com/GeyserMC/Geyser/wiki/Understanding-the-Config], we cannot fix this other than the way that is mentioned there as its a client limitation

**Comment by Tim203** [comment]
And is a duplicate of #217
