### ISSUE TITLE
Can't create firework rockets in Bedrock->Java server

### ISSUE THREAD

**Issue by SkibbleBip** [GeyserMC/Geyser#774]
**Describe the bug**

When gathering materials to create a firework (paper, gunpowder), opening both the crafting table and the inventory crafting area (E) the user is unable to create fireworks.

**To Reproduce**

1) collect gunpowder and paper
2) open E
3) place 1 paper and 1 gunpowder 
4) nothing happens

OR
1) collect gunpowder and paper
2) open crafting table
3) place 1 paper and 1 gunpowder 
4) nothing happens

**Expected behavior**

gunpowder should be crafted

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/44085597/84711624-6966fb80-af2c-11ea-915e-5876019431f4.png)

**Server Version**

Paper version git-Paper-350 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**Geyser Version**

1.0-SNAPSHOT (git-master-a6f91d5) for Bungee

**Minecraft: Bedrock Edition Version**

v1.14.60
**Additional Context**

rockets don't show up in the crafting table suggestions either (the left panel that shows all the possible items creatable with your inventory)

**Comment by E404NNF** [comment]
This issue has been reported before and it's known it's WIP

**Comment by DoctorMacc** [comment]
It has not been reported in GitHub.

**Comment by E404NNF** [comment]
oh? didn't know, but it was reported before on discord alot so

**Comment by CCF100** [comment]
Does anyone know what causes this?

**Comment by toinouH** [comment]
@SpazmasterYT Can you update and tell us if it still exist please

**Comment by CCF100** [comment]
@toinouH The issue still exists...

**Comment by Hellohi3654** [comment]
Shouldn't this pull request be closed since DoctorMacc has a fix?

**Comment by toinouH** [comment]
We(or you) close the issue when it is merged
