### ISSUE TITLE
The bedrock edition cannot get the chat information of the Java edition.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#775]
### Bedrock：

- version：1.14.6
- OS：Windows 10 & Android

### Java：

- version：1.15.2

**Comment by endevrr** [comment]
Please follow the issue template and provide us with more information.

**Comment by DoctorMacc** [comment]
I'm closing this because of a lack of information. If you could ensure you are using the latest version of Geyser, follow the issue template and give us more information, we would be hapy to reopen.
