### ISSUE TITLE
Not binding to port

### ISSUE THREAD

**Issue by nwl** [GeyserMC/Geyser#779]
I am running the latest build (1.0-SNAPSHOT (git-master-6388a91)) on Ubuntu 18.04 with openjdk-11 (11.0.7+10-2ubuntu2~18.04) in standalone mode.

I am starting the process with java -Xms1024M -jar Geyser.jar which starts normally:

root@groucho[~/geyser]# sh run.sh
[00:55:56 INFO] ******************************************
[00:55:56 INFO]
[00:55:56 INFO] Loading Geyser version 1.0-SNAPSHOT (git-master-6388a91)
[00:55:56 INFO]
[00:55:56 INFO] ******************************************
[00:55:59 INFO] Started Geyser on 0.0.0.0:19132
[00:55:59 INFO] Done (3.095s)! Run /geyser help for help!
>

However, I am unable to connect to localhost (or the external IP) on port 19132. 

levine@groucho[~]$ telnet localhost 19132
Trying ::1...
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

Changing the bedrock address: variable in the config file to localhost or the external host doesn't change the behaviour. There are no firewall rules in place (I can run netcat on port 19132 and connect to it successfully).

**Comment by RednedEpic** [comment]
Connection problems or problems covered on the common issues pages should not have issues created for them. This is mentioned in the issue template itself which it appears you have ignored. Please join our Discord for support regarding this.

**Comment by DoctorMacc** [comment]
Just tested with my working instance of Geyser and I get the same thing when I run the `telnet` command.

**Comment by bundabrg** [comment]
Telnet is TCP. Netcat is generally tcp though it supports UDP with the correct flags.
