### ISSUE TITLE
Armor stands and Heads translation feature

### ISSUE THREAD

**Issue by TheBloom46** [GeyserMC/Geyser#782]
**What feature do you want?**
Pets for the miniature pets plugin are created with armor stands, and it seems Geyser does not animate or display them correctly, this issue also happens for heads being worn by players and what happens to players also happens to pets.  All heads are steve heads even when they are in pets or are being worn by players.  If armor stands and heads could be translated to resemble how they look on java Minecraft, this issue would be resolved.  I have linked two photos below. If more info is required, I can provide it. 

The pets plugin I use can be found here - https://www.spigotmc.org/resources/miniature-pets-create-your-personal-companions.23991/
**Alternatives?**
None, many pets do not show on bedrock clients, heads don't display correctly either.

**Comment by bundabrg** [comment]
Bedrock itself has no support for custom heads. However #683 does a pretty good job of emulating it by spawning players with a head geometry over the custom heads placed in the world. I'm not sure of any solution for custom heads in the inventory. There may potentially be a solution for heads being worn but it would require some further research.

**Comment by YaUhYeah** [comment]
Now that the custom skull block support is merged into master, wearing the skull / armor stand would be a really cool edition. I hope it is possible.

Sorry for commenting on old post idk if allowed just wanted to comment it.

**Comment by onebeastchris** [comment]
This is now possible by defining custom skulls - see here for more information.
https://wiki.geysermc.org/geyser/custom-skulls/
