### ISSUE TITLE
Item nbt missing

### ISSUE THREAD

**Issue by SinanGentoo** [GeyserMC/Geyser#783]
**Describe the bug**
When you get an enchanted item that is not normally available and move it in a backpack or drop it, it will cause nbt tag disappears

**To Reproduce**
1. Use /give to give yourself an apple with Protection III enchantment and try to move it in your backpack
2. See error

**Expected behavior**
The nbt tag of the item will not be lost

**Screenshots / Videos**
Not yet

**Server Version**
The latest Paper(1.15.2)

**Geyser Version**
The latest master

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
This bug will not be triggered when items move within the container. This is just an example, This error can also occur in some custom enchanting plugins

**Comment by RednedEpic** [comment]
Hi, can you please provide the "error" you're talking about?

**Comment by YFshadaow** [comment]
Explanation of what is mentioned by @SinanGentoo :

Whenever the item is moved in the inventory, the nbt tags(eg: name, lore, enchantments) are lost and the item becomes a normal item.

My server is using a chest menu plugin and requires a clock item to open the menu. I gave the item special name and lore to inform players about how to use the item. However whenever bedrock players try to move this clock item in their inventories, the clock loses its name and lore. This has caused the item to lose its function.

**Comment by RealBitslayn** [comment]
I can add information to this. Enchantments from Bedrock don't translate or become invisible to Java players. Affects enchantment books/enchanted items. Bedrock players see Java enchantments but not the other way around.
