### ISSUE TITLE
Movement - Banned from Hypixel

### ISSUE THREAD

**Issue by Redblock6YT** [GeyserMC/Geyser#785]
**Describe the bug**

You can get banned on various servers when on a floating bridge
**To Reproduce**

1. Get Minecraft on the Nintendo switch
2. Hook that bad boy up with Bedrock Connect
3. Get the latest version of geyser running on a computer.
4. Connect to hypixel.net on geyser
5. Play bedwars
6. Keep playing untill you go on a bridge and get banned.

**Expected behavior**
Normal Hypixel bedwars gameplay, where you do not get banned for going on a bridge.

**Screenshots / Videos**

**Server Version**
I think Hypixel uses 1.8 with via version but I am not quite sure.

**Geyser Version**
I believe it is 2.3.8

**Minecraft: Bedrock Edition Version**
Nintendo switch edition

**Additional Context**

A Hypixel member said there are bugs with geyser causing the player to possibly have movement hacks or move a bit quicker then usual.

**Comment by Heath123** [comment]
This is known, and is being worked in #699

**Comment by Tim203** [comment]
Yes, this is a known issue and someone is working on a new movement system.
Try to avoid servers like Hypixel for the time being and hopefully you didn't get a perm ban.

**Comment by Redblock6YT** [comment]
How long untill this will be done do you think?

**Comment by E404NNF** [comment]
huh i got banned after i killed someone on a bridge on bedwars, maybe i was banned for the same problem? idk tbh

**Comment by Redblock6YT** [comment]
Probably the same problem. I only got banned for 30d

**Comment by E404NNF** [comment]
> Probably the same problem. I only got banned for 30d
same actually, huh ok

**Comment by Redblock6YT** [comment]
Ok

**Comment by Heath123** [comment]
> How long untill this will be done do you think?

Soon™

Seriously though, probably a while. It could be months before it's fully done (I have a lot of homework to do). Hopefully it will be usable sooner than that.

**Comment by DoctorMacc** [comment]
After the 1.16 process is completed, I can also lend a hand.

**Comment by Redblock6YT** [comment]
Ok thanks.

**Comment by RednedEpic** [comment]
Closing in favor of #209
