### ISSUE TITLE
Villager's strange sleep posture.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#791]
**Screenshots**
![%J66A$%HD4G6(UVT$ 8BJEP](https://user-images.githubusercontent.com/16282726/85196241-6ba1cf00-b30b-11ea-96c9-b46336dfe2dc.png)

**Server Version**
1.15.2 / Paper-354

**Geyser Version**
240

**Minecraft: Bedrock Edition Version**
1.14.6

**Comment by AnonAlpha** [comment]
This might be a entity rotation problem? I think a pr may fix this? Not sure about it

**Comment by DoctorMacc** [comment]
The entity rotation PR has been merged. This is something else.

**Comment by DoctorMacc** [comment]
Fixed by #933.
