### ISSUE TITLE
Native fill command doesnt effect BE players

### ISSUE THREAD

**Issue by anar4732** [GeyserMC/Geyser#792]
**Describe the bug**

Native fill command doesnt effect BE players

**To Reproduce**

 1. Set a command block to fill command
 2. run it
 3. see blocks placed on JE but not in BE

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by Heath123** [comment]
Please fill in the issue template next time

**Comment by Heath123** [comment]
Duplicate of #399
