### ISSUE TITLE
Citizens NPCs with lookclose tag have unnatural rotations

### ISSUE THREAD

**Issue by Saraistupid** [GeyserMC/Geyser#793]
**Describe the bug**

as i said in the title, i can't describe it better than that

**To Reproduce**

1. Get Citizens
2. Create an NPC
3. Enable lookclose using `/npc lookclose`
4. Move around the NPC and see the rotation

**Expected behavior**

The NPCs to rotate naturaly

**Screenshots / Videos**

https://cdn.discordapp.com/attachments/613169749525790737/723945505272365096/2020-06-20_18-56-46.mp4

**Server Version**

![image](https://user-images.githubusercontent.com/37207067/85207969-fc3cd700-b32c-11ea-8015-8d89024229a4.png)

**Geyser Version**

git-master-6388a91

**Minecraft: Bedrock Edition Version**

1.14.60
**Additional Context**

**Comment by Mespeczek** [comment]
I think it's a Machine problem ( low CPU, or RAM for server )
I'am on 1.14.6(0) too, and i don't have this problem.

**Comment by DoctorMacc** [comment]
Is this still an issue?

**Comment by E404NNF** [comment]
Yes it does, but it's much less laggy, they rotate but with a delay and sometimes they broke

**Comment by onebeastchris** [comment]
is this still an issue?

**Comment by onebeastchris** [comment]
Closing due to no response. Please open a new issue with reproduction steps if this is still occurring.
