### ISSUE TITLE
/ban-ip support

### ISSUE THREAD

**Issue by MaksPV** [GeyserMC/Geyser#795]
Can you add full support for this command?

**Comment by jackson-57** [comment]
I'm pretty sure Floodgate has IP passthrough, which would allow this command to work.

**Comment by E404NNF** [comment]
First: Please follow the template next time
Second: If you use floodgate ban-ip will work

**Comment by RednedEpic** [comment]
As mentioned above, Floodgate _has_ to be used for this in order for the command to work. Not much we can do about this if you're not using Floodgate. Closing.
