### ISSUE TITLE
Mobile user can't place the boat normally

### ISSUE THREAD

**Issue by SinanGentoo** [GeyserMC/Geyser#796]
**Describe the bug**
Mobile user can't single click to place boat

**To Reproduce**
1.Hold a boat
2.Single click to place it
3.See error

**Expected behavior**
Mobile user can single click to place the boat

**Screenshots / Videos**
Not yet

**Server Version**
Paper 1.15.2

**Geyser Version**
The latest master

**Minecraft: Bedrock Edition Version**
1.14.60

**Additional Context**
Mobile user can place the boat by long pressing

**Comment by D3ATHBRINGER13** [comment]
That no longer seems to be a problem
Though could you tell us what build of paper you were using, and what build of geyser?

**Comment by rtm516** [comment]
This is no longer an issue
