### ISSUE TITLE
Geyser gets stuck

### ISSUE THREAD

**Issue by MaximilianGaedig** [GeyserMC/Geyser#797]
**Describe the bug**
Geyser gets stuck on
`[12:39:49 INFO] Player connected with username Username
[12:39:51 DEBUG] Could not find packet for RequestChunkRadiusPacket
[12:39:51 DEBUG] Could not find packet for TickSyncPacket`
after some time it continues with
`[12:42:02 INFO] Bedrock user with ip: /192.168.8.180 has disconnected for reason TIMED_OUT`

**To Reproduce**
1.Start Geyser using java -jar Geyser.jar
2.Try to connect a client
3.wait

**Expected behavior**
Continue with `using stored credentials... ` or prompt the client

**Screenshots / Videos**

**Server Version**
Spigot 1.15.2

**Geyser Version**
1.0-SNAPSHOT (git-master-d0c95d3)

**Minecraft: Bedrock Edition Version**
v1.14.60

**Additional Context**
I am running Geyser MC on a rpi 0 with oracle java 8. I know the performance is not the best but it should at least run, but even after a 10min wait it did not work.

**Comment by DoctorMacc** [comment]
Please join us on our Discord for more support - this is likely a problem specific to your system. Also, did you try again? Sometimes a client gets stuck the first time.
