### ISSUE TITLE
NPE when logging into a non-premium Mojang account

### ISSUE THREAD

**Issue by rtm516** [GeyserMC/Geyser#803]
**Describe the bug**
NPE when logging into a non-premium Mojang account on a online-mode server

**To Reproduce**
1. Start Geyser in online mode
2. Connect to online mode server
3. Login using a non-premium Mojang account
4. See NPE

**Expected behavior**
It gracefully fails and lets the user know what has gone wrong

**Screenshots / Videos**
![image0](https://user-images.githubusercontent.com/5401186/85391486-27e4da80-b542-11ea-9291-d5fa4918587f.jpg)

**Server Version**
N/A - Been seen on almost any version from Hypixel to 1.15.2

**Geyser Version**
master as of https://github.com/GeyserMC/Geyser/commit/d0c95d3

**Minecraft: Bedrock Edition Version**
1.14.60 - Both Win10 and Mobile

**Additional Context**
Likely we can just catch it a kick the user with a nice error message. This was reported by multiple users, I'm just creating the issue so we can track it. I believe there is also another NPE on the line next to this if Xbox auth fails.

**Comment by DoctorMacc** [comment]
Fixed with #975.
