### ISSUE TITLE
During Bedwars, Bedrock players spawn in the void, while their bodies remain at the team spawn point

### ISSUE THREAD

**Issue by J-SHarper** [GeyserMC/Geyser#806]
**Describe the bug**

While playing [ScreamingBedWars](https://www.spigotmc.org/resources/screamingbedwars-1-9-1-15.63714/), upon death, Bedrock players spawn in the void below the map. They can run around, punch, and otherwise lead normal lives, except for the fact that they can't play the game. However, despite their perspective, their bodies remain at the team spawn point, where they should be. To other players, it appears that they are just standing at the team spawn point, punching the air. When the game is over, Bedrock players are teleported to the exit spawn like everyone else, which is expected behavior. 

One person suggested that waiting long enough may result in players being teleported back to their team spawn. I left my bedrock alt in the void for 3 or more minutes, and he never teleported. I have never observed a bedrock player TPing back to the respawn point. 

**To Reproduce**

Bedrock players respawn at the team spawn, and are able to rejoin the battle.

**Screenshots / Videos**

For the Geyser player, this is what happens after they respawn:
https://media.giphy.com/media/Ss6Dv5BQRO3jFDTCDZ/giphy.gif

For other players, this is what they look like:
![image](https://user-images.githubusercontent.com/6518001/85437346-700ef780-b558-11ea-9d71-791e8c010f07.png)

**Server Version**

PaperMC-347

**Geyser Version**

Geyser-Bukkit Build #225

**Minecraft: Bedrock Edition Version**

Has been tested on latest iPad edition and Minecraft for Windows 10.

**Additional Context**
Thank you!

**Comment by RednedEpic** [comment]
Does this appear to still happen?

**Comment by Chew** [comment]
No response from the author in quite some time :(. If you are able to reproduce this, please reply and we'll be happy to re-open the issue. Thank you for your contribution!

**Comment by Loganh4005** [comment]
I remember this bug... When my server worked
