### ISSUE TITLE
Support for 1.16 on JE and BE

### ISSUE THREAD

**Issue by chenxi050402** [GeyserMC/Geyser#807]
**What feature do you want?**
Support for 1.16 on JE and BE

**Alternatives?**
Install 1.14.60 back which I can't, except on Android

**Comment by D3ATHBRINGER13** [comment]
this is currently being worked on
in the mean time you can run geyser with viaversion which will let you join join it on 1.16, though it won't be a 1.16 world

**Comment by Tim203** [comment]
As stated in [our discord server](https://discord.geysermc.org) we are aware of the 1.16 release and we're currently working to support it. At this point in time, there are no ETA's as to when Geyser will be updated, though know that we're working on it and hope to have a build out soon. Please feel free to run !rank GeyserNews in #bot-spam if you want to be notified when this update rolls out.

**Comment by DeeRenjie** [comment]
Come on update, thank you！

**Comment by Heath123** [comment]
> Come on update, thank you！

Mojang takes months to update the game, and you expect a small team of devs who don't even get paid to update Geyser in a day or two when a lot of the game's workings have completely changed? If you want it to be done quickly you can always help us (and realise how hard it is to reverse-engineer new versions of the game with no documentation).

**Comment by Heath123** [comment]
https://youtu.be/6yfjpr5KLbg

**Comment by RednedEpic** [comment]
See the 1.16 branch. Closing.
