### ISSUE TITLE
Memory leak w/ ping passthrough

### ISSUE THREAD

**Issue by alex11441** [GeyserMC/Geyser#813]
**Describe the bug**

Enabling any feature that enables ping passthrough will cause the proxy to memory leak.

**To Reproduce**
Enable `passthrough-motd` or `passthrough-player-counts` in the config.

**Geyser Version**
Standalone git-master-e81c6f2

**Additional Context**
Heap dump: https://www.mediafire.com/file/bqyuz2sum1mpn2u/java_pid30423.hprof/file

**Comment by RednedEpic** [comment]
Resolved in 8ac5d6e13d92e3c8919a410c34d94850491a0861.
