### ISSUE TITLE
Inventory and Crafting UI bug in Geyser on the Bedrock Client

### ISSUE THREAD

**Issue by shwubby** [GeyserMC/Geyser#815]
**Describe the bug**
Any attempt to add, remove or create values in the inventory or crafting ui starts either blocking the user from stacking items (such as cobblestone, or dirt) or scatters your items.

**To Reproduce**
 1. Make sure you're on Bedrock Version 1.14 (Buzzy Bees update) logged onto a server with geyser loaded. 
 2. Open a chest with a stackable item that is not fully stacked
 3. try to add more than 10 of that item onto itself in the chest at once 

**Expected behavior**
The stackable item from your inventory should merge with the same type of item that is in the chest. 

**Server Version**
 1.16.1

**Geyser Version**
 1.0.0 

**Minecraft: Bedrock Edition Version**
 1.14 

**Additional Context**
 None

**Comment by Heath123** [comment]
This is on the expermental 1.16 build of Geyser, right?

**Comment by shwubby** [comment]
Yes it is.

**Comment by Heath123** [comment]
That was just to find bugs, you probably want to use the latest master build and ViaBackwards

**Comment by bundabrg** [comment]
This seems to work fine for me now, though i'm 1.16 both sides. So possibly can be closed.

**Comment by DoctorMacc** [comment]
I am closing this. If the issue persists, please re-comment.
