### ISSUE TITLE
Error on bungee join

### ISSUE THREAD

**Issue by JavyMC123** [GeyserMC/Geyser#817]
Is spamming all the console.

When someone join, this error appear:
(Is only for certain people)

https://pastebin.com/w1MpF0JK

Is the LATEST version of Geyser and Floodgate. (https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/)
And the latest version of Waterfall

**Comment by DoctorMacc** [comment]
Those people are on 1.16, and Geyser does not support 1.16. However I will leave this up so people who are searching know what the error is.

**Comment by JavyMC123** [comment]
> Those people are on 1.16, and Geyser does not support 1.16 yet. However I will leave this up so people who are searching know what the error is.

These error is occuring before the 1.16 update.

**Comment by RednedEpic** [comment]
This is because someone joined a non 1.16 version of Geyser. Closing.
