### ISSUE TITLE
Door sound cannot be played

### ISSUE THREAD

**Issue by jQubz** [GeyserMC/Geyser#819]
**Describe the bug**
The door sound cannot be played. Geyser tries to play it multiple times regardless, which breaks gameplay.

**To Reproduce**
1. Login to server
2. Open door (in my case by pressure plate)

**Expected behavior**
Door opens, sound plays.

**Screenshots / Videos**
https://imgur.com/V3GJeZa

**Server Version**
1.16.1

**Geyser Version**
version 1.0-SNAPSHOT (git-feature/1.16-7743f6d)

**Minecraft: Bedrock Edition Version**
1.16.0

**Comment by MattElekHarris** [comment]
I have the same issue. It seems to be exacerbated by using pressure plates, oddly enough.

**Comment by chenxi050402** [comment]
And pressure plates lets you move wrongly

**Comment by RednedEpic** [comment]
No longer a problem. Closing.
