### ISSUE TITLE
1.13 - Could not translate packet ServerPlayerListEntryPacket.

### ISSUE THREAD

**Issue by andrew121410** [GeyserMC/Geyser#82]
**Describe the bug**
I get this error when i join my server.
https://sourceb.in/f152573f94.java

**Server version**
Paper 1.14.4 git-226

**Geyser version**
feature-1.13-bedrock

**Bedrock version**
1.13.1

**Comment by RednedEpic** [comment]
This is known. I’ll look into fixing this soon.

**Comment by RednedEpic** [comment]
Players now show up in the latest commit. Some work needs to be done on skins still so they show up on the right player, but you should be able to see other players now.

**Comment by RednedEpic** [comment]
Fixed.
