### ISSUE TITLE
Only Warped wooden planks work to craft.

### ISSUE THREAD

**Issue by Savagetechguy** [GeyserMC/Geyser#821]
**Describe the bug**
when on bedrock you can not craft with any wood except warped wood.
**To Reproduce**

go on bedrock 
click on a crafting bench
try crafting with a different variant of wood

**Expected behavior**

craft a wooden object
**Screenshots / Videos**

**Server Version**

1.16
**Geyser Version**

1.16
**Minecraft: Bedrock Edition Version**

1.16
**Additional Context**

**Comment by DoctorMacc** [comment]
I'm able to craft a button and pressure plates with at least birch planks. Regardless this is still an issue.

**Comment by RednedEpic** [comment]
Unable to reproduce. Can you please update to the latest version and send a video if the issue is still a problem?

**Comment by Savagetechguy** [comment]
Just updated it is fixed
