### ISSUE TITLE
Smithing Table UI Broken

### ISSUE THREAD

**Issue by Tristan3030** [GeyserMC/Geyser#822]
**Describe the bug**
When opening the Smithing Table, it shows the furnace UI instead of its own UI and it isn’t functional.

**To Reproduce**
1. Play on bedrock/mcpe
2. Get a smithing table 
3. Open the smithing table

**Expected behavior**
When opening a smithing table you are expected to see the smithing table ui instead of the furnace.

**Screenshots / Videos**
![8CBEA3D7-4B8B-44B9-A9E7-46A0D6BB02D9](https://user-images.githubusercontent.com/67524464/85934860-23f4e780-b8b7-11ea-8c8a-b74b3388583b.jpeg)

**Server Version**
This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1)(Implementing API Version 1.16.1-R0.1-SNAPSHOT) You are 43 Version(s) behind 

**Geyser Version**
Not known

**Minecraft: Bedrock Edition Version**
v1.16.0
**Additional Context**
None

**Comment by DoctorMacc** [comment]
The smithing table now appears in the latest update (though it does not build). Nothing can be taken out of the output but that may be another bug.
