### ISSUE TITLE
Bedrock Hangs on Respawn

### ISSUE THREAD

**Issue by elliotnash** [GeyserMC/Geyser#825]
**Describe the bug**
pressing respawn hangs you on a generating world screen

**To Reproduce**
1) die
2) press respawn
3) get stuck on generating world screen

**Expected behavior**
to respawn 

**Screenshots / Videos**
![Screenshot (1)](https://user-images.githubusercontent.com/53949099/85940597-2fa1d780-b8d2-11ea-9bdd-e5207b0ecbab.png)

**Server Version**
waterfall 1.16-R0.1-SNAPSHOT:6bfefea:357
spigot 1.16.1 : git-spigot-1a27cfd-d77f4d9

**Geyser Version**
Geyser build #39 of feature/1.16
Floodgate #24

**Minecraft: Bedrock Edition Version**
bedrock 1.16.0

**Additional Context**
No other plugins on the server

**Comment by RednedEpic** [comment]
Fixed in the latest build.
