### ISSUE TITLE
Blocks don't show the breaking animation

### ISSUE THREAD

**Issue by elliotnash** [GeyserMC/Geyser#826]
**Describe the bug**
When breaking a block in survival, the breaking animation is not shown

**To Reproduce**
go into survival
break a block

**Expected behavior**
an animation to be shown showing the breaking progress

**Screenshots / Videos**
![ezgif-4-47200f560ab3](https://user-images.githubusercontent.com/53949099/85940811-9f649200-b8d3-11ea-98b9-fdbb7d0e4a6f.gif)

**Server Version**
waterfall 1.16-R0.1-SNAPSHOT:6bfefea:357
spigot 1.16.1 : git-spigot-1a27cfd-d77f4d9

**Geyser Version**
Geyser build #39 of feature/1.16
Floodgate #24

**Minecraft: Bedrock Edition Version**
bedrock 1.16.0

**Additional Context**
No other plugins on the server

**Comment by DoctorMacc** [comment]
Sometimes block breaking animations will now show but incorrectly.

**Comment by DoctorMacc** [comment]
This is now fixed.

**Comment by elliotnash** [comment]
It seems block breaking animations work correctly when nothing is modifying the breaking speed, but block break animations don't work underwater or while riding an entity or while jumping (the speed isn't modified correctly) to reproduce try mining a block while underwater or on a entity or try jumping and mining a block mid air

**Comment by DoctorMacc** [comment]
Do you have chunk caching on?

**Comment by elliotnash** [comment]
No I don't, I'm running the same versions of everything (geyser bungeecord) except using geyser build 103

**Comment by rtm516** [comment]
Enable chunk caching, and see if it resolves the issue.

**Comment by elliotnash** [comment]
Chunk caching seems to fix everything except for the issue while jumping. Normally when you're mid air the break speed would slow down and that works, but when you land back on the ground it would resume. On bedrock it's not resuming normal speed when you land back (try jumping and mining a block mid air and holding it when you land)
