### ISSUE TITLE
[1.16] Wolf make unlimited noise.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#827]
**Describe the bug**
Let the wolf sit down and keep making noise.

**Screenshots / Videos**
![](https://user-images.githubusercontent.com/16282726/85945871-27e63f80-b973-11ea-851b-7f48a18cec4d.gif)

**Server Version**
1.16.1 / Paper-8

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16.1

**Comment by DoctorMacc** [comment]
Is this still an issue?

**Comment by HeyDon-Lee** [comment]
> Is this still an issue?

It's been repaired.
