### ISSUE TITLE
[1.16] Bucket-related items cannot be used.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#829]
**Describe the bug**
Bucket-related items cannot be used.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/16282726/85948040-fbd1bb00-b980-11ea-99ba-a1fdf5117e2a.png)

**Server Version**
1.16.1 / Paper-10

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16

**Comment by DoctorMacc** [comment]
Existing pre-1.16 bug known from #321. Thank you for reporting anyway!
