### ISSUE TITLE
bStats player count isn't correct.

### ISSUE THREAD

**Issue by Tim203** [GeyserMC/Geyser#833]
**Describe the bug**
When you look at our [bStats page]() you can see that we have a really low player count compared to the server count.
At the time I made that screenshot we had 1098 instances running (only the ones with metrics enabled) and those 1098 had in total 68 players online. If that is true that will mean that atleast 1030 instances have no players online at all (1098 - 68 = 1030) and that doesn't sound right.

**Screenshots / Videos**
![bStats page](https://i.imgur.com/S9zblEG.png)

**Comment by RednedEpic** [comment]
Going to close this - there is no confirmation that a bug is at play causing the player count to be so low. Although it does look low for how many servers are running Geyser, we have no way of confirming this.
