### ISSUE TITLE
Bedrock client user is lefty

### ISSUE THREAD

**Issue by AdyaGD** [GeyserMC/Geyser#836]
**Describe the bug**
When going on Java version when the bedrock player interacts/break/place he uses the left hand

**To Reproduce**
1. go on java edition
2. look at a bedrock user
3. go on that bedrock client and punch
4. the player punches with the left hand instead of right

**Expected behavior**
The player should punch with the right hand

**Server Version**
This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Spigot, 46 Build

**Minecraft: Bedrock Edition Version**
Pocket Edition

**Comment by rtm516** [comment]
This can be fixed after https://github.com/Steveice10/MCProtocolLib/pull/560 is merged.

**Comment by DoctorMacc** [comment]
Fixed.
