### ISSUE TITLE
Bedrock player doesnt update the items to air

### ISSUE THREAD

**Issue by AdyaGD** [GeyserMC/Geyser#837]
**Describe the bug**
When the bedrock player looks at a java player that is holding an item/armor, then removing it the item stays instead of air

**To Reproduce**
1. go in java
2. the bedrock client should look at him
3. hold an item/armor
4. removing the item/armor
5. the bedrock user still sees that the java user is holding/wearing something

**Expected behavior**
the bedrock user should see that the java user is not holding/wearing anything

**Server Version**
This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version  1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Build #46 1.16

**Minecraft: Bedrock Edition Version**
Pocket Edition

**Comment by endevrr** [comment]
Can confirm, I have experienced this too

**Comment by endevrr** [comment]
Fixed in latest build
