### ISSUE TITLE
[1.16] Players cannot trade with villagers.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#838]
**Describe the bug**
After the transaction between the player and the villagers, the traded items will be returned to the player after a while, and the emerald will disappear.

**Screenshots / Videos**
![image](https://media.giphy.com/media/jQnEW7Y9jLmY1uITNQ/giphy.gif)

**Server Version**
1.16.1 / Paper-27

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16.1

**Comment by KolaKattz** [comment]
Happens on my server aswell. 

**Server Version**
Spigot 1.16.1

**Comment by jkcoxson** [comment]
It sometimes takes the emeralds, but I never get the goods.

**Comment by SinanGentoo** [comment]
This problem also appeared on the old version

**Comment by ishland** [comment]
Also affects wondering trader

**Comment by CleanCorpze** [comment]
Yup, I had the same issue,  I was trying to implement a plugin with traders, because its a lot easier for Mobile / Xbox / PS4 to use a villager trade menu rather than a classical java chest Gui. However, the VIllager would do the same thing as seen in the above Gif. The plugin I was trying to use was Shopkeepers [https://dev.bukkit.org/projects/shopkeepers](url) , it would be really cool if Geyser could fix this because it would add a Gui Menu that's easily usable for all the platforms.

**Comment by AJ-Ferguson** [comment]
Trading will be fixed in the new inventory system that is being worked on.

**Comment by jkcoxson** [comment]
This was not fixed, I have a fletcher which I traded sticks to. I get my sticks back atleast, but still no emeralds or villager upgrades.

**Comment by bundabrg** [comment]
You definitely have the latest build? Because I did that exact trade on mine and it works but I compiled it myself so if you're still having issues I'll need to test the build here.

**Comment by jkcoxson** [comment]
The latest builds are here https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/ correct? As of last night I used the latest build there.

**Comment by bundabrg** [comment]
I'll check when I wake up unless someone else does. If the build on CI does not work it may mean the build is caching an old dependency. On my repo I had to add -U to maven for tagged builds otherwise it used an older protocol build which resulted in broken inventory.

**Comment by DoctorMacc** [comment]
We should have the build with the latest inventory updates (we had to update Geyser to support a breaking change).
