### ISSUE TITLE
[1.16] Bedrock players cannot name things.

### ISSUE THREAD

**Issue by CombedKnight4** [GeyserMC/Geyser#839]
**Describe the bug**
Whenever you try to name an item or object, after a while it turns back into its old name. The worst part is, you don't get your xp back!

**To Reproduce**

1. Get anvil
2. Try to name something
3. Witness bug

**Expected behavior**
1. Name an object or item such as a name tag
2. Use the name tag on a good/bad mob
**Screenshots / Videos**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/66476833/85959257-21eb6100-b969-11ea-8c7c-a7ddc1e38033.gif)

**Server Version**
Java Edition 1.16.1
Bedrock Edition 1.16.0
**Geyser Version**

Standalone
Build #47 
**Minecraft: Bedrock Edition Version**
1.16.0

**Comment by AdyaGD** [comment]
Relog and you should get your xp back

**Comment by CombedKnight4** [comment]
yeah but thats not the problem
the problem is that u can't name anything

**Comment by DoctorMacc** [comment]
Is this still an issue with the latest build?

**Comment by CombedKnight4** [comment]
idk lemme check

**Comment by CombedKnight4** [comment]
nope. its all fixed now. thx!
