### ISSUE TITLE
Pressure Plates broken

### ISSUE THREAD

**Issue by Paul19988** [GeyserMC/Geyser#842]
**Describe the bug**
When a player places down pressure plates they are invisible until switching back to that world & Bedrock players cannot interact with pressure plates.

**To Reproduce**
1. Put down a pressure plate in front of a bedrock player using a Java player
2. Plate is invisible

1. Walk onto a pressure plate as a bedrock player

**Expected behavior**
Plate should appear & Plate should compress down & cause an interaction.

**Server Version**
Paper Spigot 354 (1.15.2)

**Geyser Version**
feature/1.16/#46

**Minecraft: Bedrock Edition Version**
v1.16.0

**Comment by endevrr** [comment]
Jumping on pressure plates actuates them

**Comment by endevrr** [comment]
Duplicate of #865
