### ISSUE TITLE
Block Breaking sounds dont play (In creative mode)

### ISSUE THREAD

**Issue by AdyaGD** [GeyserMC/Geyser#847]
**Describe the bug**
When breaking a block, the sound of breaking doesn't play

**To Reproduce**
1. break a block
2. no sound plays

**Expected behavior**
There should be a breaking sound

**Server Version**
This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Build #46 Spigot

**Minecraft: Bedrock Edition Version**
Pocket Edition

**Comment by rtm516** [comment]
Make sure you have chunk caching enabled, but this is likely due to sounds being broken on 1.16 builds currently

**Comment by AdyaGD** [comment]
> Make sure you have chunk caching enabled, but this is likely due to sounds being broken on 1.16 builds currently

block placing sound work tho, so I don't think thats the issue

**Comment by rtm516** [comment]
> block placing sound work tho, so I don't think thats the issue

Its likely the sounds not being mapped as they seem to have changed some things related to them

**Comment by AdyaGD** [comment]
> > block placing sound work tho, so I don't think thats the issue
> 
> Its likely the sounds not being mapped as they seem to have changed some things related to them

yes, they added alot of new block sounds (bone blocks, netherrack, nether bricks etc)

**Comment by chenxi050402** [comment]
It does not play sound in survival too (breaking grass, slime blocks, etc.)

**Comment by jackson-57** [comment]
The block breaking animations, particles, or sound don't work at all for me, in creative. Survival is fine, though.

**Comment by RednedEpic** [comment]
Able to reproduce.

**Comment by DoctorMacc** [comment]
This should now be fixed (though chunk caching is wonky so it may not always play right now).
