### ISSUE TITLE
You can't place soul torches on the ground, and glitchy on walls

### ISSUE THREAD

**Issue by AdyaGD** [GeyserMC/Geyser#848]
**Describe the bug**
You can't place torches on the ground, and on walls the hitbox is in the opposite side

**To Reproduce (1st glitch)**
1. Place a soul torch on ground
2. The torch disappeared and didnt place serverside

**Expected behavior (1st glitch)**
The soul torches should of placed

----------------------------------------------------------------------

**To Reproduce (2nd glitch)**
1. Place a soul torch on a wall
2. The hitbox and particles are on the opposite side

**Expected behavior (2nd glitch)**
The hitbox and particles should of been with the torch (sorry if I didnt phrase that well)

**Server Version**
This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Build #50  Spigot

**Minecraft: Bedrock Edition Version**
Windows 10

**Comment by rtm516** [comment]
This is likely just a simple mappings issue

**Comment by endevrr** [comment]
Can confirm this is a mappings issue, will fix today

**Comment by AdyaGD** [comment]
Good!

**Comment by endevrr** [comment]
Fixed by [ebc1f13e9b775bc103e36279d6d0e777c4f8e7ca](https://github.com/GeyserMC/Geyser/commit/ebc1f13e9b775bc103e36279d6d0e777c4f8e7ca)
