### ISSUE TITLE
Baby piglins, zombified piglins, zoglins are rendered as adult

### ISSUE THREAD

**Issue by AdyaGD** [GeyserMC/Geyser#849]
**Describe the bug**
Baby piglins, zombified piglins, zoglins are rendered as adult instead of babies

**To Reproduce**
1. Look at a baby Piglin/Zombified Piglin/Zoglin
2. they are adults in bedrock edititon

**Expected behavior**
They should of been babies

**Server Version**
This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Build #46 Spigot

**Minecraft: Bedrock Edition Version**
Windows 10

**Comment by rtm516** [comment]
This should be fixed in the latest build

**Comment by AdyaGD** [comment]
Thanks :D
