### ISSUE TITLE
Lodestones don't work

### ISSUE THREAD

**Issue by AdyaGD** [GeyserMC/Geyser#850]
**Describe the bug**
When right clicking a lodestone with a compass, the compass does not point to do lodestone and does not have a enchantment glint

**To Reproduce**
1. Place a respawn anchor
2. Right click it with a compass
3. Witness bug

**Expected behavior**
The compass should have an enchantment glint and should point to the right clicked anchor

**Server Version**
This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Geyster Build #53 - Spigot

**Minecraft: Bedrock Edition Version**
Pocket Edition

**Comment by DoctorMacc** [comment]
Should be fixed with 7710261b70d864429edcb887254f20be60ffc4ff.
