### ISSUE TITLE
[1.16] The new record cannot be displayed or heard.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#852]
**Describe the bug**
The new record cannot be displayed or heard.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/16282726/86030771-8260c800-ba67-11ea-8f28-460798cf74d7.png)

**Server Version**
1.16.1 / Paper-21

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16

**Comment by rtm516** [comment]
The item is now displayed, but the sound is still to be fixed

**Comment by DoctorMacc** [comment]
I successfully listened to the new record in Geyser.
