### ISSUE TITLE
[1.16] Watermelons do not show up correctly in-hand

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#853]
**Describe the bug**
Item will show an error on your hand.

**Screenshots / Videos**
- Java:
![image](https://user-images.githubusercontent.com/16282726/86031226-2480b000-ba68-11ea-8b3c-94913e34ebfd.png)
- Bedrock:
![image](https://user-images.githubusercontent.com/16282726/86031248-2b0f2780-ba68-11ea-936c-226c763bc537.png)

**Server Version**
1.16.1 / Paper-21

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16

**Comment by rtm516** [comment]
Any more info? Im not sure what these are meant to look like or anything so we cant do a lot with this.

**Comment by HeyDon-Lee** [comment]
Some items show errors in my hand, as shown in the picture, I have Melon, in my hand, but Bedrock Edition players see that I am Melon Slice, and my left hand does not have items, but the game shows that I have Andesite.

**Comment by DoctorMacc** [comment]
Please try the latest Jenkins build (55) and see if your error is fixed.

**Comment by HeyDon-Lee** [comment]
Version:57
Java:
![image](https://user-images.githubusercontent.com/16282726/86066713-8ca1b700-baa5-11ea-94e0-151b89fa214f.png)
Bedrock:
![image](https://user-images.githubusercontent.com/16282726/86066715-90353e00-baa5-11ea-9e59-ff5947412507.png)
@DoctorMacc

**Comment by rtm516** [comment]
This has been fixed in the mappings, so should be fixed in the next build

**Comment by DoctorMacc** [comment]
Please confirm that this is fixed with Jenkins build 60.

**Comment by HeyDon-Lee** [comment]
The problem has been solved.
@DoctorMacc
