### ISSUE TITLE
[1.16] Respawn anchor will ignore the rules of the game and remove items from the player.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#854]
**Describe the bug**
Respawn anchor will ignore the rules of the game and remove items from the player.

**To Reproduce**
```
/give @s stone 64
/gamerule keepinventory true
/kill @s
```

**Server Version**
1.16.1 / Paper-21

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16

**Comment by DoctorMacc** [comment]
This is not a Geyser problem; we do not mess with server behavior. Unless this is a temporary visual bug it is invalid.

**Comment by HeyDon-Lee** [comment]
The problem is that both Java edition and bedrock edition have tested that, Java edition is fine, and the bedrock edition player's items are emptied directly.
@DoctorMacc

**Comment by rtm516** [comment]
I have just checked this on the latest bedrock, and latest geyser versions and it is not an issue.
