### ISSUE TITLE
[1.16] Twisting Vines and Weeping Vines display errors.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#855]
**Describe the bug**
Twisting Vines and Weeping Vines display errors.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/16282726/86032165-7ece4080-ba69-11ea-9c61-f669701e1c15.png)
![image](https://user-images.githubusercontent.com/16282726/86032178-8261c780-ba69-11ea-990b-d327e954c921.png)

**Server Version**
1.16.1 / Paper-21

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16

**Comment by endevrr** [comment]
Fixed by [ebc1f13e9b775bc103e36279d6d0e777c4f8e7ca](https://github.com/GeyserMC/Geyser/commit/ebc1f13e9b775bc103e36279d6d0e777c4f8e7ca)
