### ISSUE TITLE
[1.16] Something that can't be used.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#856]
**Describe the bug**
- Items that cannot be used.
  1. ~~Lodestone~~
  2. Grindstone
  3. Elytra
  4. Armor Stand
  5. ~~Cauldron~~
  6. Smithing Table
- Unable to open GUI.
  1. Enchanting table
  2. Stonecutter
  3. Loom

**Server Version**
1.16.1 / Paper

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16

**Comment by rtm516** [comment]
Lodestone - Works but NBT of the compass isn't passed to the bedrock client
Grindstone - Is broken
Elytra - Works fine
Armor Stand - Putting armour on works, but taking it back off doesn't
Cauldron - Works fine but doesn't update bedrock side

Enchanting table + Stonecutter - Are both not implemented as mentioned in the readme
Loom - Is broken

**Comment by DoctorMacc** [comment]
What platform is the elytra not working with?

**Comment by HeyDon-Lee** [comment]
Windows 10 @DoctorMacc

**Comment by rtm516** [comment]
My testing was on windows10 so its likely something todo with your server or plugins

**Comment by HeyDon-Lee** [comment]
The server plug-in has only one bukkit plug-in called clearlagg.
https://dev.bukkit.org/projects/clearlagg
The problem with Elytra may be an input method error, because I am not an English operating system.

**Comment by AdyaGD** [comment]
the elytra also doesnt work for me

**Comment by rtm516** [comment]
Loadstones now work in the latest build

**Comment by Legit4K** [comment]
It's a hit and miss with the elytra, it deactivates mid-air when trying to use it even after replacing it with a new one. Sometimes when I join, it just works. When I change to Survival gamemode, it almost always works, when I transfer dimensions, it stops working ¯\_(ツ)_/¯

Kinda ressembles a similar thing to auto jump not being consistent in older versions of Geyser.

**Comment by TheMasterBlaster** [comment]
Only time I have seen issues with the Elytra is either when in Creative or when Fly is enabled via a plugin like CMI

**Comment by DoctorMacc** [comment]
I'm closing this because, while not everything has been fixed, a large majority have and some now have separate issues or are listed in the readme.
