### ISSUE TITLE
[1.16] When the player is equipped with the Mob head, it still displays when it is taken off.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#859]
**Describe the bug**
When the player is equipped with the Mob head, it still displays when it is taken off.

**Server Version**
1.16.1 / Paper-21

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16

**Comment by rtm516** [comment]
This works fine as of the latest bedrock and geyser.
