### ISSUE TITLE
spectator mode problem

### ISSUE THREAD

**Issue by D-Jy-lab** [GeyserMC/Geyser#860]
In spectator mode it is possible to break blocks, which actually still exist, but are not shown in the bedrock client.
Server version paper 1.15.2

**Comment by rtm516** [comment]
> In spectator mode it is possible to break blocks, which actually still exist, but are not shown in the bedrock client.
> Server version paper 1.15.2

Please follow the template and this is because bedrock doesn't have a propper spectator mode.

**Comment by D-Jy-lab** [comment]
OK. Thanks！
