### ISSUE TITLE
[1.16] The spectral arrow is not visible to the player.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#861]
**Describe the bug**
The spectral arrow is not visible to the player.

**Expected behavior**
Replace with resources for normal arrows.

**Screenshots / Videos**
- Java:
![image](https://user-images.githubusercontent.com/16282726/86034482-46306600-ba6d-11ea-8b40-c074545bc7c8.png)
- Bedrock:
![image](https://user-images.githubusercontent.com/16282726/86034493-4af51a00-ba6d-11ea-9190-77d4ae4d7ee2.png)

**Server Version**
1.16.1 / Paper-21

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16

**Comment by rtm516** [comment]
They already display as normal arrows, we are planning on making this better but not ETA on that yet. Closing this for now.
