### ISSUE TITLE
[1.16] Players cannot switch swimming states.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#862]
**Describe the bug**
Players cannot switch swimming states.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/16282726/86034658-9f989500-ba6d-11ea-984d-db8d164a1b17.png)

**Server Version**
1.16.1 / Paper-21

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16

**Comment by rtm516** [comment]
This works fine from both bedrock and java points of view.

**Comment by HeyDon-Lee** [comment]
No problem.
I suspect it is caused by the input method bug of Minecraft for Windows 10.
