### ISSUE TITLE
Bartering animations are missing.

### ISSUE THREAD

**Issue by AdyaGD** [GeyserMC/Geyser#863]
**Describe the bug**
When bartering you can't see the piglin looking at the gold and throwing the item

**To Reproduce**
1. Spawn in a piglin
2. right click with a gold ingot
3. you barter without animations

**Expected behavior**
The piglin should look at the gold and throw the item back

**Server Version**
This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Build #53 - Spigot

**Minecraft: Bedrock Edition Version**
Pocket Edition

**Comment by rtm516** [comment]
Fixed with https://github.com/GeyserMC/Geyser/commit/c2be7a181da8c72bbb143aed318b185b62b77dda and build feature/1.16#103
