### ISSUE TITLE
Blocks do not update their state

### ISSUE THREAD

**Issue by endevrr** [GeyserMC/Geyser#865]
**Describe the bug**
Some blocks do not update their state automatically, to update their state, a block update must happen close to the block

**To Reproduce**
- Place a block with state, a trapdoor for example, 
- get another player to open/close it
- See that the hitbox has updated but the block has not

EDIT: Trapdoors are fixed in Build 56 but some blocks with state such as Potted Plants do not update automatically

**Expected behavior**
Blocks with state should update automatically.

**Screenshots / Videos**
Java:
![image](https://user-images.githubusercontent.com/37273113/86051680-b4fdc700-ba4d-11ea-8c67-9dcd161fb89c.png)

Bedrock:
![image](https://user-images.githubusercontent.com/37273113/86051640-a4e5e780-ba4d-11ea-8d88-9e98d8d0db16.png)

**Server Version**
Irrelevant

**Geyser Version**
Geyser Build 55

**Minecraft: Bedrock Edition Version**
1.16.0

**Additional Context**
None

**Comment by endevrr** [comment]
Fixed in build 56

**Comment by endevrr** [comment]
reopen this as not all blocks are fixed

**Comment by MasterLuke117** [comment]
this related to?: https://github.com/DoctorMacc/Geyser/tree/non-full-chunk

similar issue when using world edit, things don't update until you re-log , the above "non-full-chunk" seams to resolve it, however it still needs more testing to make sure it doesn't create performance issues.

perhaps someone can update this pr to 1.16?

**Comment by Heath123** [comment]
> this related to?: https://github.com/DoctorMacc/Geyser/tree/non-full-chunk
> 
> similar issue when using world edit, things don't update until you re-log , the above "non-full-chunk" seams to resolve it, however it still needs more testing to make sure it doesn't create performance issues.
> 
> perhaps someone can update this pr to 1.16?

No, I think this is different.

**Comment by DoctorMacc** [comment]
@MasterLuke117 the intention of this issue is to fix any block that did update pre-1.16 and does not now.

Unfortunately I intend to update my PRs that are not part of the 1.16 cycle after 1.16 is merged into master.

**Comment by DoctorMacc** [comment]
Closing this issue as I believe all item frames now show properly.
