### ISSUE TITLE
Blocks are unbreakable

### ISSUE THREAD

**Issue by D3ATHBRINGER13** [GeyserMC/Geyser#866]
**Describe the bug**

In a large section of my world I cannot break or place blocks, if I place blocks it uses up the block but it disappears, and if I break a block it disappears for an instant the reappears.
Though if I set my account to op, it fixes it

**To Reproduce**

Unknown

**Expected behavior**

Blocks to break/place

**Screenshots / Videos**

**Server Version**

Paper 1.16 #24

**Geyser Version**

1.16 #55

**Minecraft: Bedrock Edition Version**

1.16.1 Xbox

**Additional Context**

N/A

**Comment by endevrr** [comment]
This is spawn protection and not a Geyser bug

**Comment by D3ATHBRINGER13** [comment]
Oh nvm

**Comment by AdyaGD** [comment]
you are most likely in a spawn protection radius, please check your server settings

**Comment by AdyaGD** [comment]
oh
