### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by D3ATHBRINGER13** [GeyserMC/Geyser#867]
**Describe the bug**

When I load into the world I hear a minecart rolling sound

**To Reproduce**

Load into a world and listen

**Expected behavior**

No minecart sounds

**Screenshots / Videos**

**Server Version**

Paper 1.16 24

**Geyser Version**

1.16 55

**Minecraft: Bedrock Edition Version**

1.16.1

**Additional Context**

**Comment by AdyaGD** [comment]
"Expected behavior: nothing"
there cannot be "nothing"

**Comment by DoctorMacc** [comment]
It's certainly possible that the server sends a null sound - perhaps to stop all other sounds.

**Comment by D3ATHBRINGER13** [comment]
I just meant no minecart sound

**Comment by DoctorMacc** [comment]
Is this still an issue?

**Comment by D3ATHBRINGER13** [comment]
I don't think so
