### ISSUE TITLE
[1.16] Wrong position after riding Strider.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#869]
**Describe the bug**
Wrong position after riding Strider.
Zombified Piglin's position becomes half of Strider's height.
The player's position becomes at the foot of Strider, and there is no way to see the way.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/16282726/86067628-e30ff500-baa7-11ea-9bb8-f37af025978e.png)

**Server Version**
1.16.1 / Paper-25

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16.1

**Comment by DoctorMacc** [comment]
Fixed by ba6adc988be440639d2d717517c884404bdf274e.

**Comment by HeyDon-Lee** [comment]
![image](https://user-images.githubusercontent.com/16282726/86076922-92a39200-babd-11ea-97cb-e26e2044e3a8.png)

**Comment by HeyDon-Lee** [comment]
version 69:

![image](https://user-images.githubusercontent.com/16282726/86304641-17b7b400-bc42-11ea-8e2b-7e8b87a14510.png)
