### ISSUE TITLE
Device freezes when asking for command list

### ISSUE THREAD

**Issue by chenxi050402** [GeyserMC/Geyser#870]
**Describe the bug**
Device freezes while asking for command list

**To Reproduce**
1.log into the server as an admin
2.type "/" in chat
3.see error

**Expected behavior**
no any freezes or lags

**Server Version**
Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Geyser Version**
master build#247

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by rtm516** [comment]
This is a known issue with the client, please set `command-suggestions` to false in the config.
