### ISSUE TITLE
Block breaking animations are messed up

### ISSUE THREAD

**Issue by chenxi050402** [GeyserMC/Geyser#871]
**Describe the bug**
Block breaking animation time is not correct on almost all blocks

**To Reproduce**
Log into a server
Break a block
See error

**Expected behavior**
Block animation ends and the block breaks at the same time

**Server Version**
paper 1.15#372 and paper 1.16#27

**Geyser Version**
1.16-#60 BungeeCord

**Minecraft: Bedrock Edition Version**
1.16 Xbox

**Comment by DoctorMacc** [comment]
This is a similar problem to #826, so I'm closing this in favor of that.
