### ISSUE TITLE
[1.16] After the player drowns, there is no death GUI, but free movement.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#872]
**Describe the bug**
After the player drowns, there is no death GUI, but free movement.
After exiting the server, the GUI keeps showing death and does not resurrect the player.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/16282726/86129093-c362e600-bb14-11ea-8dab-578ce57d38bb.png)

**Server Version**
1.16.1 / Paper-27

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16.1

**Comment by AnonAlpha** [comment]
And after other death, they can't respawn, the only way to respawn is by rejoining

**Comment by endevrr** [comment]
Fixed in build 64

**Comment by HeyDon-Lee** [comment]
version: 65

When the player dies, the display death GUI, clicks the resurrection button, the death GUI, is shown again and there is no death GUI after clicking the resurrection button again, and the player has not been resurrected, staying in the interface of the picture all the time.
![image](https://user-images.githubusercontent.com/16282726/86193626-f9d54b00-bb7e-11ea-8c2f-1215206d1148.png)

@endevrr @rtm516

**Comment by AnonAlpha** [comment]
I have the same as @HeyDon-Lee

**Comment by HeyDon-Lee** [comment]
There is a problem that has not been solved.
@DoctorMacc

**Comment by AnonAlpha** [comment]
Hmmm, maybe reopen this issue

**Comment by endevrr** [comment]
We were under the impression we had fixed this, it turns out we haven't this should be reopened

**Comment by DoctorMacc** [comment]
Please confirm that this bug has been fixed with build 68.

**Comment by elliotnash** [comment]
Seems to all be working in build 68

**Comment by HeyDon-Lee** [comment]
The problem has been solved.
