### ISSUE TITLE
Building up block causes you to giltch through them

### ISSUE THREAD

**Issue by Jakeahorner** [GeyserMC/Geyser#873]
**Describe the bug**

When you are building straight up the block underneath you disappear when placed
**To Reproduce**

Place a block
Place another block on top of that block quickly we’ll standing on it
**Expected behavior**

The block to not disappear 
**Screenshots / Videos**

**Server Version**

1.16.1
**Geyser Version**

1.16.1
**Minecraft: Bedrock Edition Version**

1.16.0
**Additional Context**

**Comment by DoctorMacc** [comment]
See also #1389.

**Comment by RednedEpic** [comment]
Appears to be fixed in the latest version. Please comment here with update video evidence if this still occurs. Thanks for the report!
