### ISSUE TITLE
Shield can't be used on 1.16

### ISSUE THREAD

**Issue by SinonGame** [GeyserMC/Geyser#874]
**Describe the bug**

Shield can't be used on 1.16 server
**To Reproduce**

1. Go into a server
2.Use a shield
3. see error
**Expected behavior**

Shield can be used properly

**Screenshots / Videos**

Not yet
**Server Version**

Paper 1.15.2 with viaversion
**Geyser Version**

 geyser build 60 with floodgate
**Minecraft: Bedrock Edition Version**

1.16.0
**Additional Context**

**Comment by AnonAlpha** [comment]
Players will have their shield used when they are eating things

**Comment by rtm516** [comment]
This is possible but it seems quite buggy, needs more investigation. You can right-click to block but you have to either shift to stop or swap items.

**Comment by RednedEpic** [comment]
Appears to be fixed in the latest build of Geyser.
