### ISSUE TITLE
java.lang.RuntimeException: Unable to inflate buffer data

### ISSUE THREAD

**Issue by Champion0912** [GeyserMC/Geyser#876]
Full error message: https://mcpaste.io/3dd4f8cac786029f

Problem: Players from MCPE is not able to connect while Java edition players are able to connect.
MCPE players can see the server (ping the server), but when trying to connect the player is left onn loading screen forever while the server produces the error message from the link above.

**Comment by endevrr** [comment]
Use the latest version of Geyser from [here](https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/feature%252F1.16/)
