### ISSUE TITLE
Exp sound effects missing

### ISSUE THREAD

**Issue by AdyaGD** [GeyserMC/Geyser#878]
I've been playing Hypixel Skyblock on my phone for a while and saw realized that something was off, most of Skyblock's sound effects are from exp sounds, did a test and sure enough, exp sounds are missing.

**Describe the bug**
The experience/levelup sounds are missing

**To Reproduce**
1. collect exp
2. no sounds

**Expected behavior**
exp sound effects

**Server Version**
This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Geyser #64 - Spigot

**Minecraft: Bedrock Edition Version**
Pocket Edition

**Comment by Heath123** [comment]
Just as a warning, it's very easy to permanently banned on Hypixel with Geyser randomly.

**Comment by DoctorMacc** [comment]
Has this been fixed?
