### ISSUE TITLE
[1.16] When Sneaking is close to other players, there will be a trade button.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#880]
**Describe the bug**
When Sneaking is close to other players, there will be a trade button.
This problem occurs on Android devices, and I don't know if iOS will do that.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/16282726/86186852-bd005880-bb6c-11ea-8ed9-483348064b57.png)

**Server Version**
1.16.1 / Paper-27

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16.1

**Comment by HeyDon-Lee** [comment]
This bug was asked by a player using an Android phone to replace the feedback.
The screenshot was also provided by him.

**Comment by DoctorMacc** [comment]
We've gotten zero other reports of this so I'm going to go close it.
