### ISSUE TITLE
Mobile players can’t place water

### ISSUE THREAD

**Issue by Savagetechguy** [GeyserMC/Geyser#881]
**Describe the bug**

Water buckets are not able to be placed on mobile 
**To Reproduce**

Go on bedrock on mobile
Place water with a water bucket
**Expected behavior**

Water to be placed
**Screenshots / Videos**

**Server Version**

1.16.1
**Geyser Version**

1.16.1
**Minecraft: Bedrock Edition Version**

1.16.1
**Additional Context**

**Comment by DoctorMacc** [comment]
Duplicate of #321.
