### ISSUE TITLE
 An exception occurred in RakNet

### ISSUE THREAD

**Issue by itsyecoder** [GeyserMC/Geyser#882]
Updated to 1.16 and got error " An exception occurred in RakNet". Not sure if this is due to nether update or not.

**Comment by itsyecoder** [comment]
here is pastebin of error https://pastebin.com/wtWPLr8x

**Comment by jkcoxson** [comment]
You need to use the version from here: https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/feature%252F1.16/

**Comment by DoctorMacc** [comment]
Please use our `feature/1.16` branch, as stated above.
