### ISSUE TITLE
Can't use the brewing stand slots except fuel slot.

### ISSUE THREAD

**Issue by erkekk** [GeyserMC/Geyser#885]
**Describe the bug**
When you try to put water bottle on bottle slot or potion making materials to upper slot it can't be placed.
**To Reproduce**
Get a brewing stand
Try to put glass bottle or potion making materials to slots

**Expected behavior**
Expected to put potion materials in brewing stand slots

**Screenshots / Videos**

**Server Version**
1.16

**Geyser Version**

**Minecraft: Bedrock Edition Version**
1.16

**Additional Context**

**Comment by rtm516** [comment]
I'm unable to replicate this in the latest build on 1.16.1, can you confirm this is still an issue and give a full step by step on what you did if it is.

**Comment by rtm516** [comment]
This was fixed as of https://github.com/GeyserMC/Geyser/commit/50176e10a87ea4a566e373389f88a6d770cff6a2 please update Geyser.
