### ISSUE TITLE
Pressure Plates don't actuate when walked over

### ISSUE THREAD

**Issue by endevrr** [GeyserMC/Geyser#888]
**Describe the bug**
Pressure plates only actuate when jumped on

**To Reproduce**
- Place pressure plate with door
- Walk over pressure plate
- See that the door does not open
- Jump on pressure plate
- See that the door does open

**NOTE:** Sprinting over pressure plates work correctly

**Expected behavior**
Pressure plates should actuate when jumped on and walked over

**Screenshots / Videos**
N/A

**Server Version**
Vanilla 1.16.1

**Geyser Version**
Geyser Latest development builds as of time of issue

**Minecraft: Bedrock Edition Version**
1.16.1

**Additional Context**
N/A

**Comment by DoctorMacc** [comment]
Perhaps an issue with how we offset the player on any non-full block?

**Comment by endevrr** [comment]
That was my initial theory

**Comment by chenxi050402** [comment]
pressureplates does work normally but the door won't make any sounds

**Comment by Heath123** [comment]
> Perhaps an issue with how we offset the player on any non-full block?

But pressure plates have no collision as far as I know, so the position should still round down

**Comment by Heath123** [comment]
I think this is because pressure plates have collision on Bedrock but not Java.

**Comment by chenxi050402** [comment]
> I think this is because pressure plates have collision on Bedrock but not Java.

The new bedrock beta removed the collision.

**Comment by ishland** [comment]
My pressure plates keeps opening and closing the door when I walked over in BE 1.16.1

**Comment by DoctorMacc** [comment]
This is likely fixed! If people are still having issues, please let us know here!
