### ISSUE TITLE
Map not being displayed on Bedrock client

### ISSUE THREAD

**Issue by 1MagicSweet** [GeyserMC/Geyser#890]
**To Reproduce**
1. Bring or generate an empty map
2. Don't see anything there

**Expected behavior**
Map generating and showing correclty as in Java or Bedrock editions without Geyser.

**Screenshots / Videos**
![Annotation 2020-07-02 142033](https://user-images.githubusercontent.com/49122140/86353015-5f086980-bc6f-11ea-814c-66d8c219e455.png)
![Annotation 2020-07-02 142058](https://user-images.githubusercontent.com/49122140/86353021-60399680-bc6f-11ea-8b01-1ad23fdd63e1.png)
![Annotation 2020-07-02 142116](https://user-images.githubusercontent.com/49122140/86353024-60d22d00-bc6f-11ea-87e2-529281eb0262.png)
![Annotation 2020-07-02 142131](https://user-images.githubusercontent.com/49122140/86353029-62035a00-bc6f-11ea-8abf-fd0f6383f600.png)

**Server Version**
1.16.1, vanilla

**Geyser Version**
git-feature/1.16-699ae0b

**Minecraft: Bedrock Edition Version**
1.16.0

**Additional Context**
I think everything that explained above is enough.

**Comment by chenxi050402** [comment]
Mine works fine

**Comment by lukemagdalin** [comment]
A less confusing title would be **Map not being displayed on Bedrock client**.

**Comment by 1MagicSweet** [comment]
> 
> 
> A less confusing title would be
> **Map not being displayed on Bedrock client**

yea, thanks for the tip, my english isn't so good

**Comment by DoctorMacc** [comment]
Please check and see if the latest build fixed this.

**Comment by 1MagicSweet** [comment]
> 
> 
> Please check and see if the latest build fixed this.
Nope, it didn't. git-1.16-pr-9359f40
![image](https://user-images.githubusercontent.com/49122140/86730533-4d401100-c037-11ea-802c-381086321daa.png)

**Comment by rtm516** [comment]
This should be fixed as of https://github.com/GeyserMC/Geyser/commit/75f2891ec0fe093ff88891434e7a24df58591ea2 and build feature/1.16#101
