### ISSUE TITLE
No Knockback

### ISSUE THREAD

**Issue by ChrisKimZHT** [GeyserMC/Geyser#891]
**Describe the bug**
No knockback

**To Reproduce**
1.Join the Hypixel server
2.Join the Duels games
3.When the players hit you, you have no knockback and stand still.

**Expected behavior**
When I am hit by other players, I should have a knockback. But I keep still and don't move.

**Server Version**
Where is the output from /version?

**Geyser Version**
1.0-SNAPSHOT (git-master-ed3fbf3)

**Minecraft: Bedrock Edition Version**
1.14.60

**Comment by toinouH** [comment]
Is this bug still present in the latest versions of Geyser @ChrisKimZHT ?

**Comment by KingRainbow44** [comment]
Yes, this bug is still present.

**Comment by RednedEpic** [comment]
Any update on this?

**Comment by KingRainbow44** [comment]
> Is there a relatively safe way to test this? I have two Java accounts - is there some non-timed place I can get both of them in to just punch around?

You can get on Hypixel, "/duel" the other account (any duel except combo should work) and you can test. Do note, you could be flagged by the anti-cheat but when this happened to me, I didn't get flagged/banned.

**Comment by Camotoy** [comment]
Thank you for providing replication steps! I played a Classic Duel between two of my accounts, and the one on Geyser did take knockback. As such, I am assuming Hypixel fixed the problem on their end, or we did.
