### ISSUE TITLE
[1.16]  The Skeleton Horseman is in the wrong location.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#892]
**Describe the bug**
The Skeleton Horseman is in the wrong location.

**Server Version**
1.16.1 / Paper-44

**Geyser Version**
1.16

**Minecraft: Bedrock Edition Version**
1.16

**Comment by lukemagdalin** [comment]
More information is needed to debug this. Things like screenshots and a description of what you are trying to do would be useful.

**Comment by RednedEpic** [comment]
Yes, please provide more information to this issue. Going by what you posted there is very little we can gather.

**Comment by DoctorMacc** [comment]
Closing to keep things clean - if you have more information to provide to us, please feel free to attach it!
