### ISSUE TITLE
[1.16] Scoreboard with RGB colors causes issues

### ISSUE THREAD

**Issue by RHX0R3** [GeyserMC/Geyser#893]
Bug report:

Timeout OR Read timeout because of the scoreboard containing the new 1.16 implemented color codes (the # ones). In my case I am using the latest version of "FeatherBoard".

I am using Waterfall (#360) on Paper-Spigot 1.16.1 (Geyser-Bungeecord). I am using it inside a Cloud Solution (for your interest).

I have copied the entire log from the bungeecord console for you:

https://pastebin.com/dZpxSWWh

(The procedure means a "clean" startup of the bungeecord, then connecting from Bedrock 1.16.1 and wait until the caused timeout).

------
(* - freshly downloaded, 4th July 2020)

Geyser-version: *the latest current 1.16 beta
Bungeecord: *latest Waterfall (fork)
Spigot: *latest Paper-Spigot 1.16.1
Log/ Info: above
Plugin involved: FeatherBoard (latest 1.16 build) using the new 1.16 implemented # colorcodes.

It seems like Geyser cant read those codes and keep up, so it time outs the Bedrock user.

How does my scoreboard look? (Please don't see it as advert)
![IMG_20200704_045330_053](https://user-images.githubusercontent.com/37308703/86503903-d72b7800-bdb2-11ea-9372-51abd4212f13.png)

And this is the "error" scoreboard:
![Screenshot_20200704-051636_Minecraft](https://user-images.githubusercontent.com/37308703/86504177-cdefda80-bdb5-11ea-8510-2938d6243558.jpg)

And this is the complete FeatherBoard scoreboard config (scroll down to see the colorcodes and lineups):
https://pastebin.com/Pyeb5JXG

What should be done: Implement the colorcodes in the handover translation, so that Bedrock can see it and Geyser/ Bungeecord won't overflow.

I hope that I had all Information you need above.

**Comment by DoctorMacc** [comment]
This should be fixed by this point. If not, please comment and we will reopen!
