### ISSUE TITLE
[1.16] Large amounts of scoreboard packets when connecting to 50kilo.org

### ISSUE THREAD

**Issue by DoctorMacc** [GeyserMC/Geyser#896]
**Describe the bug**
When attempting to join the 50kilo.org server, you load in and go down to Y -40 with empty chunks before eventually timing out.

**To Reproduce**
- Join 50kilo.org with Geyser

**Expected behavior**
Joining in with no problems.

**Server Version**
Some form of 1.16.1.

**Geyser Version**
`feature/1.16` build 74

**Minecraft: Bedrock Edition Version**
Bedrock 1.16.1

**Comment by AnonAlpha** [comment]
I got the Y -40 too, but players will be teleported back after a while

**Comment by DoctorMacc** [comment]
Is this on another server or this server specifically? I am aware that this can happen sometimes but not to the point where it leads to a timeout.

**Comment by toinouH** [comment]
I only got this bug on that server.

**Comment by DoctorMacc** [comment]
@AdyaGD does the same thing happened as described here? What server version are they on?

**Comment by DoctorMacc** [comment]
Wynncraft likely does not work because of the requirement for a resource pack.
