### ISSUE TITLE
Delay command autocomplete

### ISSUE THREAD

**Issue by Madis0** [GeyserMC/Geyser#900]
**What feature do you want?**
On a big server with lots of plugins, entering a slash `/` causes a lag up to 15 seconds due to the huge amount of commands the client recieves. How about delaying that to at least when a letter is added, so e.g. `/e` would give a smaller amount of commands to autocomplete.

**Alternatives?**
Workarounds include copying slash + letter or typing a letter before slash to avoid autocomplete until the command is written.

**Comment by DoctorMacc** [comment]
This is something we are unable to do, I'm afraid. We send the declare commands packet at the beginning of the login cycle, so it's only when you type `/` that the client processes it. I believe we've determined what you're suggesting is impossible. Thank you anyway for suggesting!

**Comment by Madis0** [comment]
> We send the declare commands packet at the beginning of the login cycle, so it's only when you type / that the client processes it. 

So you're saying the lag is strictly client-side and no additional requests are made for subsequent `/` types?

**Comment by DoctorMacc** [comment]
Correct.
