### ISSUE TITLE
[1.16] 1.16 double slabs not displayed correctly on bedrock clients

### ISSUE THREAD

**Issue by YFshadaow** [GeyserMC/Geyser#904]
Describe the bug

When logging in to a geyser server using a bedrock client, 1.16 double slabs (crimson slabs, warped slabs, and all three blackstone slabs) are not displayed correctly. They are displayed as bottom half slabs. If the bedrock player tries to walk over it without jumping, the player will get stuck as if there is an invisible wall in front.

To Reproduce

Place a slab mentioned above onto another half slab (Applicable on both java and bedrock clients)

Expected behavior

On bedrock clients, the double slabs are displayed as bottom half slabs. Players cannot walk over without jumping.

Server Version

Paperspigot git-Paper-74 (MC: 1.16.1)

Geyser Version

1.16 - build 85

Minecraft: Bedrock Edition Version

1.16.1

**Comment by RednedEpic** [comment]
Resolved in https://github.com/GeyserMC/mappings/commit/83a3468766b82ea97bd1ae8a1e92bffcc2745349.
