### ISSUE TITLE
[1.16] Extinguishing fire causes the block below to be broken as well, on bedrock clients

### ISSUE THREAD

**Issue by YFshadaow** [GeyserMC/Geyser#906]
Describe the bug

When trying to extinguish fire on bedrock edition (I tested on both Android and Windows 10), the block below will also get broken. (In singleplayer mode player can extinguish fire without breaking the block)

To Reproduce

Extinguish fire.

Expected behavior

Block underneath also get removed.

Server Version

Paperspigot git-Paper-74 (MC: 1.16.1)

Geyser Version

1.16 - build 85

Minecraft: Bedrock Edition Version

1.16.1

Other context

I saw an issue (#875 ) about bedrock clients not able to extinguish fire, so I guess the issue mentioned above is a temporary fix for that issue?

**Comment by DoctorMacc** [comment]
Does anyone know if this was an issue pre-1.15?
