### ISSUE TITLE
No grass break animation

### ISSUE THREAD

**Issue by elliotnash** [GeyserMC/Geyser#911]
**Describe the bug**
When breaking grass (or flowers) directly, the particle effect/animation doesn't show, however it shows when breaking the block under the grass

**To Reproduce**
join on bedrock
break a grass
see no animation
break the block under the grass
see the expected animation

**Expected behavior**
It is expected for a green particle effect/animation to appear when you break the grass

**Screenshots / Videos**

![ezgif com-optimize](https://user-images.githubusercontent.com/53949099/86731434-6370b180-bfe4-11ea-9272-2401e5b31c7a.gif)

**Server Version**
Running Paper 1.16.1 build 74
Waterfall 1.16-R0.2-SNAPSHOT (Build 360)

**Geyser Version**
Geyser bungeecord, 1.16pr build 2. Running with floodgate build 24 on all servers with send bedrock data enabled.

**Minecraft: Bedrock Edition Version**
Bedrock 1.16.1

**Additional Context**
No other plugins.

**Comment by RednedEpic** [comment]
This has now been fixed. Thanks for the report!
