### ISSUE TITLE
Bedrock Player can't reconnect after death

### ISSUE THREAD

**Issue by katzerax** [GeyserMC/Geyser#913]
**The Bug**
Xbox Bedrock player unable to reconnect, stuck on generating world, building terrain screen. Player shown to have been connected in tablist and in chat, but no physical location for the player.

**To Reproduce**
1. Fall into and die in lava in the nether
2. Disconnect from death screen to menu
3. Reconnect to server

**Expected behavior**
Reconnection established

**Screenshots / Videos**

**Server Version**
Geyser Version 1.0.0 (git-feature/1.16-c2be7a1) (Java: 1.16.1, Bedrock 1.16.0)

**Geyser Version**
Build 103, branch is feature/1.16. Floodgate is being utilized.

**Minecraft: Bedrock Edition Version**
1.16 Xbox bedrock

**Additional Context**
We are using plugins such as essentials and sethome and warp which might interfere?

**Comment by Ashesh3** [comment]
Having the same issue.

**Comment by Ashesh3** [comment]
Update to latest build, it fixed the issue for me

**Comment by DoctorMacc** [comment]
Is this issue still occuring?

**Comment by Ashesh3** [comment]
I tested it with latest version, and this seems to be resolved, leaving the game after death using title screen option, then rejoining would give me the death screen and clicking respawn works, i am not stuck. so the issue seems to be resolved at least from my tests.
