### ISSUE TITLE
[1.16] Spectator mode issues

### ISSUE THREAD

**Issue by ayunami2000** [GeyserMC/Geyser#915]
**Describe the bug**

Using the 1.16 release, when in spectator mode, (1) only held items can be seen by others in spectator mode, (2) when clicking on another entity the player is still put inside the entity's view but they can still move around freely, and when sneaking they will be teleported back to the entity that they had previously clicked, (3) when breaking blocks in spectator mode, they appear client side to be broken but upon right clicking them they reappear, and (4) when loading in items from the creative inventory while in spectator, they appear to load into your inventory client side but eventually the server and client sync the player's inventory and the client side inventory reverts to before.
**To Reproduce**

(1)
1. Go into spectator mode
2. log on with another bedrock edition (or probably java edition, though not tested) account onto the server
3. hold an item and go to spectator mode
4. you should be able to see the item in the other player's hand.

(2)
1. Go into spectator mode
2. left click an entity, e.g. a creeper
3. attempt to move around
4. sneak to go back to the creeper

(3)
1. Go into spectator mode
2. break any block
3. right click the area where the block was to update it

(4)
1. Go into spectator mode
2. get any item from your inventory now that you are in spectator mode
3. (optional for demonstration purposes) try placing an item in an empty slot and holding it. log on with another bedrock account and they will not see the item because the slot is actually empty
**Expected behavior**

(1) When in spectator mode, others in spectator mode should only be a translucent head (or whatever may be possible in bedrock edition, maybe the person is shown as invis and as having no items and to other spectator players they are wearing their own player head? idk just my guess as to how to implement this)
(2) When in spectator mode, clicking on another entity should not only teleport their camera view to the entity but should also prevent them from moving around until they sneak out of spectating that entity.
(3) When in spectator mode, blocks that the user attempts to break should not remain broken like a ghost block but should immediately be updated via the server.
(4) When in spectator mode, items loaded into the inventory via the creative menu should not remain in the creative menu until the server updates the inventory but should be locked by the server from being edited.
**Screenshots / Videos**

(please note that I am using a client on java edition so I am able to use a different username and I am also using a number of mods because I didn't want to edit my mods folder. they do not affect this issue. please also note that I am using a resource pack for bedrock edition that makes it look like java edition. I do not believe that this affects this issue)
![image](https://user-images.githubusercontent.com/24785136/86822895-30690500-c05a-11ea-8d85-85a5dd077f82.png)
Other issues are in this video: https://youtu.be/_233jMjCsUc

**Server Version**

`Paper version git-Paper-79 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`
**Geyser Version**

`Geyser version 1.0.0 (git-feature/1.16-f68632f)`
**Minecraft: Bedrock Edition Version**

Minecraft Windows 10 edition v1.16.1
**Additional Context**

Plugins:
Geyser (Spigot plugin)
LibsDisguises 10.0.14 (Free)
ProtocolLib 4.6.0-SNAPSHOT-b472

**Comment by DoctorMacc** [comment]
World interaction will be fixed in #1034.
