### ISSUE TITLE
Idea for offline accounts and Java accounts via codes or ingame link with Bedrock account.

### ISSUE THREAD

**Issue by JanisPlayer** [GeyserMC/Geyser#918]
**What feature do you want?**
I am looking for a way to link the Java accounts to Bedrock (microsoft live accounts).
For example, that you make a request to the account and they have to confirm it in-game.
Or you can set a code in game with which you can link accounts.
Or quite normal via the java login. (for non plugin version)

And a possibility to join the server offline if GeyserMC runs as a plugin.
So that the player can link an offline account with his Bedrock account.
This only if this account is not currently in use.
If the account is no longer free, all account files should be automatically assigned a new free account.

I don't know if the idea is good for you.
But I find that better than if you send the password in plain text to the server.
You should only do this if there is no other option.
And if there is no other option, then not always.
The data protection guidelines are a bit problematic to implement.

Can I change the code for myself so that I can test whether my idea works?

Exemple:
![MCLogin](https://user-images.githubusercontent.com/54918417/86949286-b6667800-c14e-11ea-8a05-5c8e8404fbfd.png)

**Comment by RednedEpic** [comment]
Account linking already exists in Floodgate.

**Comment by edcous** [comment]
@RednedEpic hey, how do I enable it with floodgate? I have floodgate enabled but it says account linking is not enabled.

**Comment by jackson-57** [comment]
Go into the floodgate config.yml and turn on account linking.

**Comment by edcous** [comment]
Thanks! One more question, how does Floodgate work?

**Comment by Tim203** [comment]
You can learn more about Floodgate here: https://github.com/GeyserMC/Geyser/wiki/Floodgate
