### ISSUE TITLE
Use Inventory Hidden Bug For Spectator

### ISSUE THREAD

**Issue by Loganh4005** [GeyserMC/Geyser#922]
**What feature do you want?**
Using the Hotbar Hidden Bug to accomplish Spectator Mode

**Alternatives?**
Not Really, For MCPE it might be a problem but maybe it should be jus for Win10 and Switch, Xbox, Etc

**Comment by RednedEpic** [comment]
While in theory this _could_ work, once the "hidden bug" happens to a player, the HUD cannot be "unhidden" without requiring the player to relog, so unfortunately this wouldn't work out. Regardless, thanks for the feature suggestion!
