### ISSUE TITLE
The Bedrock player cannot join in.

### ISSUE THREAD

**Issue by hui2007** [GeyserMC/Geyser#924]
**Describe the bug**

The Bedrock player cannot join in.
On server,it said
An exception occurred in RakNet
java.lang.AssertionError: Expected AES to be available”
**To Reproduce**

1.Start the server
2.Start Geyser as a plugin.
3.Connect from Bedrock
3.Cannot join in.
**Expected behavior**

The bedrock player can join in.
**Screenshots / Videos**

None
**Server Version**

git-Spigot-0287a20-7560f5f (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**

Geyser version 1.0.0 (git-master-cbb2586) (Java: 1.16.1, Bedrock: 1.16.0) 

**Minecraft: Bedrock Edition Version**

1.16.0

**Comment by DoctorMacc** [comment]
Unfortunately the only solution to this is to update your Java. See https://adoptopenjdk.net/ for the best downloads.
