### ISSUE TITLE
Java can join Bedrock

### ISSUE THREAD

**Issue by CombedKnight4** [GeyserMC/Geyser#925]
**What feature do you want?**
I want another version of geyser where "Java" players can join "Bedrock" player servers.

**Alternatives?**
none

**Comment by RednedEpic** [comment]
Hi, thanks for the suggestion, but unfortunately something like this would essentially require an entirely new project. This is something we've been looking in to, but at this time there isn't a lot of demand for something like that. Perhaps if there is higher demand and we feel that we have the time and motivation to create and maintain a project like this, we'll come back to it.

**Comment by CombedKnight4** [comment]
ok
