### ISSUE TITLE
[1.16] Unable to access the server.

### ISSUE THREAD

**Issue by HeyDon-Lee** [GeyserMC/Geyser#939]
**Describe the bug**
Unable to access the server.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/16282726/87236894-404d6400-c421-11ea-985e-4616a10e8471.png)

**Server Version**
1.16.1 / Paper-89

**Geyser Version**
264

**Minecraft: Bedrock Edition Version**
1.16.1

**Comment by RednedEpic** [comment]
Can you please send the error from console?

**Comment by HeyDon-Lee** [comment]
Failed to load locale asset cache: Unrecognized token 'Unexpected': was expecting ('true', 'false' or 'null')
 at [Source: (String)"Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"; line: 1, column: 11]

**Comment by RednedEpic** [comment]
> Failed to load locale asset cache: Unrecognized token 'Unexpected': was expecting ('true', 'false' or 'null')
> at [Source: (String)"Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"; line: 1, column: 11]

Can you paste the full error in [hastebin](https://hasteb.in) please?

**Comment by HeyDon-Lee** [comment]
https://hasteb.in/egeyuzif.sql

**Comment by DoctorMacc** [comment]
You may need to redownload Geyser?

**Comment by HeyDon-Lee** [comment]
It may be the failure of the en_us.lang update. Can you tell me the download address of the download en_us.lang? I'd like to upload it manually.

**Comment by DoctorMacc** [comment]
The internal Geyser language or the Java Minecraft one?

**Comment by HeyDon-Lee** [comment]
> The internal Geyser language or the Java Minecraft one?

Geyser

**Comment by DoctorMacc** [comment]
That's provided in the jar file.

**Comment by DoctorMacc** [comment]
Is this still an issue?

**Comment by HeyDon-Lee** [comment]
It's all right.

**Comment by LostAraneus** [comment]
I have the same problem im looking for solutions

**Comment by Chew** [comment]
Hello, please hop onto our [discord server](https://discord.geysermc.org) for help with this. Please don't bump old issues
