### ISSUE TITLE
Bedrock client can not join the server.

### ISSUE THREAD

**Issue by PQguanfang** [GeyserMC/Geyser#94]
**Describe the bug**
When I try Bedrock 1.13.2 join the server,it says "Outdated client,please use 1.13.2".
However,my Minecraft Bedrock Edition version is 1.13.2.

/223.104.146.241:42232 tried to connect!
Attempting to login using offline mode... authentication is
disabled.
Player connected with username PQguanfang
PQguanfang (logged in as: PQguanfang) has connected to remo
e java server on address mc.cloud6.fun
PQguanfang has disconnected from remote java server on addr
ss mc.cloud6.fun because of Outdated client! Please use 1.1
.2
Bedrock user with ip: /223.104.146.241 has disconnected for
reason CLOSED_BY_REMOTE_PEER

**Comment by LegacyGamerHD** [comment]
Is your server 1.14.4 or got viaversion

**Comment by LegacyGamerHD** [comment]
1.12 mc java servers aren't supported @RednedEpic close this

**Comment by linmiao233** [comment]
Shouldn't it be 1.14?

**Comment by LegacyGamerHD** [comment]
1.14.4 to be clear

**Comment by linmiao233** [comment]
> 1.14.4要明确

Row..

**Comment by Heath123** [comment]
> > 1.14.4要明确
> 
> Row..

?

**Comment by SupremeMortal** [comment]
You're trying to connect to an unsupported server
