### ISSUE TITLE
Feature Request: Dual-Server authtype

### ISSUE THREAD

**Issue by oezingle** [GeyserMC/Geyser#941]
This is a nice-to-have, but I think it would be a good idea. If possible, I would like to see a new authtype where Geyser directs a player to an in-between bedrock server, to authenticate their connection. Geyser then would, assuming the player has a legitimate Xbox live account, kick the player and move them to the java server and proceed as normal.

**Comment by jackson-57** [comment]
I don't think this would be needed, because we already have the Floodgate plugin which can authenticate Xbox Live players

**Comment by oezingle** [comment]
Floodgate can authentificate Xbox live? Is that new? Also, very cool!

**Comment by jackson-57** [comment]
Nope, it's been a feature of Floodgate since the beginning. https://github.com/GeyserMC/Floodgate

**Comment by RednedEpic** [comment]
Players are already checked if they're authenticated through Xbox live by default in Geyser. Using something like Floodgate allows them to join online mode servers without having to have a Minecraft: Java Edition account. If you're suggesting an option for players to choose if they want to authenticate as a Java account or use their Xbox Live account, that's not something we intend to add as it defeats the entire purpose of Floodgate. However, one thing we have implemented into Floodgate is account-linking support so you can link your accounts.
