### ISSUE TITLE
The ability to fake or specify a minecraft java version

### ISSUE THREAD

**Issue by CactiChameleon9** [GeyserMC/Geyser#942]
**What feature do you want?**
The ability to fake or specify a minecraft java version, for example pretending all clients are 1.12.2

**Alternatives?**
Possibility to disable minecraft version checking on a self hosted server?

**Comment by DoctorMacc** [comment]
Hi; thanks for the suggestion! Since Geyser emulates a Java 1.16 client, we can't just flip a switch to allow it to act as different versions. In the future we will certainly consider this but it will require a large amount of work.

**Comment by CactiChameleon9** [comment]
OK... thanks. Is there a way I can run geyser for 1.12.2?

(cuberite server)

**Comment by conroy-cheers** [comment]
If your Java server is running an older version (e.g. 1.12.2), you can use [ViaVersion](https://github.com/ViaVersion/ViaVersion) to allow newer Java clients to connect. Geyser emulates a Java 1.16 client, so you can then connect as such:
1.16 Bedrock client -> Geyser emulated 1.16 Java client -> 1.12.2 Java server with ViaVersion

**Comment by CactiChameleon9** [comment]
OK thanks that helps a lot. So I can use cuberite with velocity proxy with geyser and viaversion plugins. I wonder how well that will run on a pi zero :D

**Comment by CactiChameleon9** [comment]
Hmm... When I connect though geyser velocity I get a blank screen with a read time out, but it works when just connecting from normal java though velocity

**Comment by Vesek** [comment]
Do not run it on pi zero, i don't believe it has enough power to do that, just run it on your PC or phone.

**Comment by CactiChameleon9** [comment]
I am allowed to try... what is wrong with that?

**Comment by RednedEpic** [comment]
We currently cannot support multiple protocol versions on the Java end due to limitations within the Java protocol library we use. Would advise using something like ViaVersion if you run a legacy server and want to support 1.16.2.
