### ISSUE TITLE
Make the resources branch a option in the config file

### ISSUE THREAD

**Issue by Hellohi3654** [GeyserMC/Geyser#961]
**What feature do you want?**
Could you add an option in the config file that creates the packs folder and loads the texture packs instead of having a separate branch so that the resources branch is up to date with the master branch

**Alternatives?**
You can manually merge the two branches but it's time-consuming and it would be a lot faster if it was just an option in the config file

**Comment by DoctorMacc** [comment]
Hello! We'll merge in the resource branch normally when we're ready (which requires merging anyway). Thank you for the idea anyway!
