### ISSUE TITLE
Advancement viewer

### ISSUE THREAD

**Issue by Madis0** [GeyserMC/Geyser#962]
**What feature do you want?**
A chest-based GUI that lets the users view their advancements, accessible via a command.

**Alternatives?**
A list of granted advancements in text (book?).

**Comment by rtm516** [comment]
Maybe not a chest GUI, but using the built-in forms might be an idea.

**Comment by YHDiamond** [comment]
This is hopefully going to be added in the next 2 days.

**Comment by Camotoy** [comment]
Resolved with #1579.

**Comment by Rishik9989** [comment]
Wht is command for advancemnt viewer

**Comment by Chew** [comment]
Please do not bump old issues for support.

You can view the commands list on the wiki: https://github.com/GeyserMC/Geyser/wiki/Commands
