### ISSUE TITLE
Block cracking animation not working on bedrock client

### ISSUE THREAD

**Issue by cloakfox** [GeyserMC/Geyser#963]
**Describe the bug**
The block cracking animation is not working on bedrock client (windows edition & pocket edition)

Information about setup:
hub runs paper 1.12.2
rest of servers run paper 1.15.2
ViaVersion installed on all the servers (not installed on bungee)

**To Reproduce**
Join: play.darkscorner.net
and try to break blocks, you will notice the block cracking animation doesnt show on bedrock but does on java.

**Expected behavior**
Normal block cracking animation

**Screenshots / Videos**
x

**Server Version**
FlameCord 0.3.4 (was running everything under tcpshield before with waterfall but that doesnt work when you use geyser ;(

Running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1 SNAPSHOT)
Running Tuinity version git-Tuinity-"6bf9015" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Running Tuinity version git-Tuinity-"9a6fb96" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**

This server is running Geyser version 1.0.0 (git-master-64d5390) (Java: 1.16.1, Bedrock: 1.16.0)

I'm also running the floodgate plugin on all back end servers and on bungee

**Minecraft: Bedrock Edition Version**
1.16.0 I think

**Additional Context**

https://dump.geysermc.org/tw5XWlaDOfQyBGCBASUQBcyOXMDOxOm8

**Comment by rtm516** [comment]
Enable chunk caching in the config and it should fix this issue.

**Comment by cloakfox** [comment]
How badly does that effect ram usage though?

**Comment by rtm516** [comment]
Not alot from what we have seen.

**Comment by cloakfox** [comment]
I've tried with cache-chunks: true and have the exact same issue.

**Comment by cloakfox** [comment]
Would be great if more users are able to reproduce this, so far this seems only to happen to me? I must have configured something wrong then?

I've checked if cache-chunks is true, and it is. Are there more options I should defiantly check? I've looked over everything related to geyser but couldn't see anything that could affect the block breaking animation

**Comment by E404NNF** [comment]
Same issue actually

**Comment by cloakfox** [comment]
Same issue on geyser Build #378

Bump.

**Comment by E404NNF** [comment]
Same issue too on latest build

**Comment by DoctorMacc** [comment]
@E404NNF you have cache chunks enabled? Could you also provide a Geyser dump?

**Comment by DoctorMacc** [comment]
@cloakfox can we get an updated Geyser dump for you as well with cache chunks enabled?

**Comment by E404NNF** [comment]
Yeah I do have it on, and I will provide one later

**Comment by DoctorMacc** [comment]
Confirmed on Tuinity.

**Comment by DoctorMacc** [comment]
Specifically, it looks like Tuinity does not send the start break/stop break packets we currently depend on.

**Comment by RednedEpic** [comment]
Another thing to mention about this is despite the server sending the block break animations in Spigot/Paper, this is not required on Java clients as this is also done clientside.

**Comment by E404NNF** [comment]
> @E404NNF you have cache chunks enabled? Could you also provide a Geyser dump?

https://dump.geysermc.org/pCydI0SomxhvxjCCtLhOkU1GULNFtiki

**Comment by E404NNF** [comment]
It's a paper server, iirc I had chunk caching enabled on it, can't check rn

**Comment by rhld16** [comment]
I fixed the issue on my server by disabling Tuinity's lag-compensate-block-breaking option and upon further inspection of the patch I'm going to assume that [this](https://github.com/Spottedleaf/Tuinity/blob/8056d130970b8fa4810d3d20cad5f6e473c4a93c/patches/server/0011-Lag-compensate-block-breaking.patch#L106) is why the animation never starts.

**Comment by DoctorMacc** [comment]
Good catch.
