### ISSUE TITLE
Bedrock Players kicked at once "due to keepalive timeout”

### ISSUE THREAD

**Issue by Adamsapplespie** [GeyserMC/Geyser#965]
This bug occurs under normal usage conditions. All of a sudden, all the Bedrock players of my server are kicked by either timing out, or as it says in the console for some people, “was kicked due to keepalive timeout”.

To Reproduce?
No specific steps other than running the server.

**Expected behavior**
I would expect this not to happen.

**Screenshots / Videos**
I think its self explanatory... 
![Annotation 2020-07-17 103129](https://user-images.githubusercontent.com/43221920/87797452-b2a2b780-c818-11ea-871b-a6b21db60243.png)

**Server Version**
in screenshot
![Annotation 2020-07-17 102737](https://user-images.githubusercontent.com/43221920/87797047-3019f800-c818-11ea-9ae5-452dba2583ba.png)

**Geyser Version**
Version 1.0.0 (git-master-64d5390) (Java: 1.16.1, Bedrock: 1.16.0)

**Minecraft: Bedrock Edition Version**
1.16.1 Minecraft Bedrock

**Additional Context**
We have a few other plugins like Coreprotect, Easywhitelist, DiscordSRV, Inventoryrollback. Total of 11 plugins. We also have a scoreboard for number of deaths in the tab menu.

The server was upgraded yesterday from 4gb of ram to 7gb of ram. Not sure if there is a causation there...

**Comment by RednedEpic** [comment]
Does this appear to still be happening? And if so, can you please provide a console log (or at least the relevant parts containing where players were kicked due to this keepalive timeout)?

**Comment by w8oo** [comment]
I have this issue..........

**Comment by adalmo** [comment]
[23:30:54 WARN]: literal{Abdaxd1} was kicked due to keepalive timeout!
[23:30:54 INFO]: Abdaxd1 lost connection: Timed out

**Comment by Chew** [comment]
Don't say you have issues if you aren't going to, at the least, provide the details Redned specified. Additionally, please make a new issue instead.

**Comment by w8oo** [comment]
https://github.com/GeyserMC/Geyser/issues/3528
