### ISSUE TITLE
Forward bedrock skin to Java Edition players using Geyser-Spigot

### ISSUE THREAD

**Issue by ishland** [GeyserMC/Geyser#966]
**What feature do you want?**
I can see my own skin in BE but not in anyone else using JE. So forward it so JE players can see it instead of a steve or alex. 

**Alternatives?**
Nope

**Comment by MrZomka** [comment]
Not fixable.
And would never be.

**Comment by Heath123** [comment]
> Alternatives?
Nope

There's SkinRestorer

**Comment by Heath123** [comment]
> Not fixable.
> And would never be.

It is, people are working on it, it's just not easy

**Comment by MrZomka** [comment]
> > Not fixable.
> > And would never be.
> 
> It is, people are working on it, it's just not easy

Wait, really? That’s cool!

**Comment by ishland** [comment]
> > Alternatives?
> > Nope
> 
> There's SkinRestorer

SkinRestorer can only restore JE skins, not BE skins

**Comment by DoctorMacc** [comment]
This will be a feature in the future; we are unsure whether it will be Floodgate or Geyser functionality.

**Comment by Heath123** [comment]
> > > Alternatives?
> > > Nope
> > 
> > 
> > There's SkinRestorer
> 
> SkinRestorer can only restore JE skins, not BE skins

I've tested, it does work on BE too if you use a skin URL to set the skin

**Comment by CCF100** [comment]
> > > > Alternatives?
> > > > Nope
> > > 
> > > 
> > > There's SkinRestorer
> > 
> > 
> > SkinRestorer can only restore JE skins, not BE skins
> 
> I've tested, it does work on BE too if you use a skin URL to set the skin

Can confirm myself
![2020-07-17_11 39 08](https://user-images.githubusercontent.com/29297989/87810210-4036d500-c822-11ea-9370-651398446f67.png)

**Comment by RednedEpic** [comment]
This is something being implemented in Floodgate 2.0, and there is already an Issue opened on Floodgate [here](https://github.com/Tim203/Floodgate/issues/4). Closing.
