### ISSUE TITLE
Nether Brick mapped to Nether Brick Block

### ISSUE THREAD

**Issue by ishland** [GeyserMC/Geyser#972]
**Describe the bug**
Nether Brick mapped to Nether Brick Block

**To Reproduce**
1. Get a nether brick and nether bricks
2. See no difference in BE

**Expected behavior**
Should see Nether Brick and Nether Brick Block

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/30385023/87847897-0216df80-c90e-11ea-9d43-a63948df8d49.png)

**Server Version**
`This server is running Paper version git-Paper-"81f6d51f0" (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`

**Geyser Version**
This server is running Geyser version 1.0.0 (git-master-64d5390) (Java: 1.16.1, Bedrock: 1.16.0)

**Minecraft: Bedrock Edition Version**
`v1.16.1`

**Additional Context**
https://dump.geysermc.org/lCzSC1dnx5Wyr6wyrKynlFQpF37MiP6F

**Comment by DoctorMacc** [comment]
Fixed with #979.
