### ISSUE TITLE
authlib-injector plz

### ISSUE THREAD

**Issue by WindLeaf233** [GeyserMC/Geyser#973]
**New server auth -- authlib-injector**
authlib-injector enables you to build a Minecraft authentication system offering all the features that genuine Minecraft has.
My server is using authlib-injector to authenticate user. Please be sure about add that, thanks.

authlib-injector Github: https://github.com/yushijinhun/authlib-injector

**Alternatives**
I tried use '-javaagent:authlib-injector.jar=[yggServer]' to start geyser, not working.

**Comment by Heath123** [comment]
Are you looking for [Floodgate](github.com/GeyserMC/Floodgate)?

**Comment by RednedEpic** [comment]
Hi, can you please update your issue with the issue template for a feature request properly filled out? Also, have you looked into [Floodgate](https://github.com/GeyserMC/Floodgate) as it may do something similar to what you're wanting?
