### ISSUE TITLE
authlib-injector auth

### ISSUE THREAD

**Issue by WindLeaf233** [GeyserMC/Geyser#974]
**New server auth -- authlib-injector**
authlib-injector enables you to build a Minecraft authentication system offering all the features that genuine Minecraft has.
My server is using authlib-injector to authenticate user. Please be sure about add that, thanks.

authlib-injector Github: https://github.com/yushijinhun/authlib-injector

[authlib-injector.zip](https://github.com/GeyserMC/Geyser/files/4941934/authlib-injector.zip)

**Alternatives**
I tried use **-javaagent:authlib-injector.jar=[yggServer]** to start Geyser, but it not working.

**Comment by DoctorMacc** [comment]
Hi! I looked into `authlib-injector`, but I'm unsure what it does. Are there English documents that explain its purpose?

**Comment by Heath123** [comment]
Does Floodgate not work?

**Comment by WindLeaf233** [comment]
No, I tired to use Floodgate to start server, but I can't join my server...

**Comment by WindLeaf233** [comment]
I'm sorry, it not English documents here...
But the general idea is to use a ygg server to authenticate MC server users. For example, I can use an account created from a ygg server to access the server opened by authlib-injector. That's probably what it meant. Then, the start command of authlib-injector is java -javaagent:{/path/to/authlib-injector.jar}={API Root of Authentication Server}, such as java -javaagent:authlib-injector.jar=https://myserver .com/ygg. You can use Google Translate to translate this page https://github.com/yushijinhun/authlib-injector/wiki. If you don't understand it, I can find the author of authlib-injector and try to translate it into English... Thanks.

**Comment by DoctorMacc** [comment]
Geyser is not a server itself; it connects to a server.

**Comment by WindLeaf233** [comment]
I know, but what do I join my BE geyser server use authlib-injector?
I think you can add it, to change BE auth.

**Comment by DoctorMacc** [comment]
What's your complete server setup?

**Comment by WindLeaf233** [comment]
config?

**Comment by DoctorMacc** [comment]
The layout of your server - where is Geyser setup, or which server is Geyser trying to connect to?

**Comment by WindLeaf233** [comment]
trying to connect own 1.16 server

**Comment by WindLeaf233** [comment]
hm, just forget it, i will try to find other ways to connect my server, thanks a lot
