### ISSUE TITLE
All packages cannot be sent.

### ISSUE THREAD

**Issue by OverBrave** [GeyserMC/Geyser#977]
I using standalone geyser and and I have a problem I couldn't solve for 3 months.
When we enter the server with the standalone geyser, some packages cannot be sent to the bedrock player. These are usually mobs. And the most common is the scoreboard.

I tried many times on my side, thinking that the problem would be on me.

I tried it with bungeecord + plugin WITHOUT plugins. Same.

I tried it on localhost, disabled it and tried the firewall. Same.

I tried the PC format. Same.

I changed the Java version a lot of time. Same.

But:
If I put geyser in bungeecord, this time everything will appear and work correctly! However, this time the player needs the real ip address of the server machine.

Where's the problem? Please let's go fix it.

(!) Same problem on hypixel or anyserver.
Don't forget, if @rtm516 open the geyser server, always again working correctly!

![image](https://user-images.githubusercontent.com/47111280/87874908-381f9680-c9d6-11ea-9aa9-a0d9f5fc24ba.png)

Some logs on geyser (A lot of null): 
[latest.zip](https://github.com/GeyserMC/Geyser/files/4943715/latest.zip)

**Comment by TheMasterBlaster** [comment]
I never had issues when using Standalone or Bukkit or Bungeecord. I honestly have no clue why you have so many issues. Everything you have issues with works perfectly from my tests, as I have said multiple times. :/

**Comment by OverBrave** [comment]
I dont understand too...

**Comment by OverBrave** [comment]
Aha! 
My server is running on a centos operating system and when running geyser on another centos operating system, everything worked properly!

I think problem on Windows OS.

**Comment by TheMasterBlaster** [comment]
Iv done tests on a Windows 10 machine.

**Comment by youngchief-btw** [comment]
🤔

**Comment by OverBrave** [comment]
I also tried both Windows 10 Pro and Windows 2012 R2 edition. It did not work on either.

**Comment by TheMasterBlaster** [comment]
I'm using a insider preview of Windows 10 Pro but that shouldn't matter.

**Comment by OverBrave** [comment]
Why man why, now i again tried on different centos operator again not appear.......................

**Comment by RednedEpic** [comment]
Does this still appear to be an issue?

**Comment by toinouH** [comment]
@OverBrave Can you confirm with the latest

**Comment by OverBrave** [comment]
When I installed the Centos operating system as a full package, the problem was resolved.

**Comment by rtm516** [comment]
Closing this since it was reported as resolved.
