### ISSUE TITLE
slime fun's machine （skull'skin）can not display

### ISSUE THREAD

**Issue by abc13131412** [GeyserMC/Geyser#981]
can not display skull's skin (my english is poor....sorry about this)
geyser:  1.0.0 (git-master-64d5390) (Java: 1.16.1, Bedrock: 1.16.0)
server:Paper version git-Paper-80(MC:1.16.1)(Implementing API version 1.16.1-R0.1-SNAPSHOT)
slime fun:vDEV - 582(git 8fd0afd8)
https://dump.geysermc.org/R1UBDqK4E7wB85puXlvR2I9kCQXZzPgi

**Comment by MastoryMd5** [comment]
Same thing as skull in the inventory using DeluxeMenus, i think it's a skin related.
![image](https://user-images.githubusercontent.com/17986972/87925283-58a42b00-ca80-11ea-80fa-3e5ee462d41d.png)
