### ISSUE TITLE
More dump info

### ISSUE THREAD

**Issue by rtm516** [GeyserMC/Geyser#983]
**What feature do you want?**
More info added to the `/geyser dump` command. This will be a thread for any suggestions and things that should be added to the dump command. (Please comment any suggestions)

- Detect if server query is on

**Alternatives?**
N/A

**Comment by toinouH** [comment]
-A description of "complicated" lines like ping-passthrough and what it does on geyser depends on how that line is configured (true, false etc.)
-The amount of ram allocated to geyser (this may help for users of the standalone version)

**Comment by rtm516** [comment]
> -A description of "complicated" lines like ping-passthrough and what it does on geyser depends on how that line is configured (true, false etc.)
> -The amount of ram allocated to geyser (this may help for users of the standalone version)

I don't think we will add any descriptions to the dump but getting the allocated ram is a good idea.

**Comment by DoctorMacc** [comment]
Yeah, we don't need descriptions as the purpose of a dump is to help us who already know how these lines work.

Maybe getting the platforms of anyone currently on the server?

**Comment by EasyClifton** [comment]
I think it'd be nice to add:
* Whether the server is in online mode or not
* I'd surely want some more things, but I just can't remember what I need.
