### ISSUE TITLE
Ask the player to connect to the ip

### ISSUE THREAD

**Issue by abc13131412** [GeyserMC/Geyser#987]
**What feature do you want?**
When the player enters the geyser, a dialog box pops up to prompt to enter the IP to be connected

在玩家进入geyser的时候弹出对话框提示输入需要连接的IP

**alternatives?**
The server ip is preset, the selection window pops up when the player enters
预设好服务器ip，玩家进入时弹出选择窗口

**Comment by BlueBurgersTDD** [comment]
do you mean like this? https://github.com/GeyserMC/GeyserConnect
