### ISSUE TITLE
Standalone | Nickname with space bug

### ISSUE THREAD

**Issue by towuk118** [GeyserMC/Geyser#993]
**Describe the bug**
dont see config name with space!
**To Reproduce**
just autologin in config change items:
![image](https://user-images.githubusercontent.com/28830162/88089511-c772a880-cb94-11ea-9e2b-10ded82b8da8.png)

**Expected behavior**
none

**Server Version**
latest now

**Geyser Version**
latest now

**Minecraft: Bedrock Edition Version**
latest now

**Comment by DoctorMacc** [comment]
In the future, please specify specific versions. The server version is not needed since there is no server being connected to.

Add two spaces before the `email` and `password` parameters.
